### ISSUE TITLE
Crash in multiplayer lobby/global chat using game filter

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#10006]
(Playtest 20151114) Win 8.1
To recreate click/go:
* Multiplayer
* Connect to global IRC
* select (single click) one of the servers (so that you can see the map preview)
* open filter and deselect and reselect the "empty" filter
(crash)

Ther might be other ways to replicate this, but this is easy enough. I tested nad crashed 4 times in a row.

exception.log
http://www.megafileupload.com/i4mo/exception.log

* If for some reason you don't crash select another server and do a bit of filter switching. "Works" for me :)

**Comment by pchote** [comment]
Having to dig through adds to download the log is a pain, so here's the contents:
```
Red Alert Mod at Version playtest-20151114
on map f952d7560302bcb9b5363ce65a66ebaf2a1590d7 (Desert Shellmap by Scott_NZ).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Widgets.CachedTransform`2.Update(T input)
   at OpenRA.Mods.Common.Widgets.Logic.MultiplayerLogic.<LoadBrowserPanel>c__AnonStorey2.<>m__1()
   at OpenRA.Mods.Common.Widgets.LabelWidget.Draw()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Widgets.Widget.DrawOuter()
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by pi99y** [comment]
Playing with it some more I can confirm it's not just the "empty" filter that does it, at least "waiting" aswell, possibly others. Sometimes you do need to try a few times (switch server selection and "spam" filters ON/OFF). 

Also it might be related to map on the server.
64H PlayTest D2K MapSync - Battle for Dune is one server - map combination that resulkted in crash at least once.

**Comment by pchote** [comment]
This smells like a race condition.  I suspect that replacing MultiplayerLogic.cs#L300 with `Game.RunAfterTick(() => RefreshServerListInner(null));` should fix this.

**Comment by penev92** [comment]
Nope, that didn't fix it.
