### ISSUE TITLE
AttackMove into shrouded areas

### ISSUE THREAD

**Issue by teees** [OpenRA/OpenRA#10016]
You can send units with "MoveIntoShroud: false" into shrouded areas via AttackMove

http://gfycat.com/HappyParchedFeline

Responsible code:
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Widgets/WorldCommandWidget.cs#L97-L109
##

**Comment by Mailaender** [comment]
I think this should better be solved at trait level and submitted https://github.com/OpenRA/OpenRA/pull/13935 as a proposed solution.
