### ISSUE TITLE
Preserve the original behaviour of spies (don't force players to force fire them)

### ISSUE THREAD

**Issue by kyrylo** [OpenRA/OpenRA#10012]
Spies on `bleed` have been "fixed". So, in order to detect them you have to use either dogs (only Soviets) or try to select them and if that doesn't work, you're sure it's a spy, which is super confusing (and then you have to force-fire them). 

I'm strongly against that new behaviour. Firstly, nobody complained about spies being detectable with cursors. Usually there's a lot of infantry on the map, so it takes a while to scan all of them with your cursor, which already is punishing (but totally fine). Secondly, it's already pretty hard to detect spies. They can disguise as anyone, so there are no common patterns like "oh, I see a rifler, I know spies can only be riflers, so it's easy for me to select all riflers with the "W" key and check if it's my unit or a spy". Thirdly, new players might not know about the ability to force fire.

Please, reconsider this behaviour. Ideally, I would like them not to be "fixed".

**Comment by pchote** [comment]
Just to be clear - this is specifically about requiring force-fire to target spies, right?

This was a small part of a larger set of fixes for unit behaviour with regards to spys.
It would be relatively simple to undo that one change for the cursor.

**Comment by pi99y** [comment]
I'm not sure which behaviour is better, but two more points: 
 
* I would say that "no attack cursor" (so that you have to force fire) makes sense if the spy is disguised as ally or enemy unit, but not when disguised as the unit of a player who tries to select/target them. 
 
* Spies now also detect spies, no?

**Comment by kyrylo** [comment]
> @pchote 
> Just to be clear - this is specifically about requiring force-fire to target spies, right?

Yes and no. Yes, because I assume that if you don't require force-fire, you also automatically get the "enemy" cursor. And no, because the current spy behaviour has been tested very well (many players do use spies these days and I never seen anyone complaining, including the spy users). My main point is that it should stay as it is in the latest release.

Cheers :)

**Comment by kyrylo** [comment]
I also forgot to mention one more serious problem with spies. In team games, how are you able to tell between spies and your ally's infantry now?

**Comment by pi99y** [comment]
You're not supposed to know that. That's the point IMO.
Other way around: Allied spies have (or should if they don't) have a "spy icon" (eye) nex to them, so you know it's not the enemy.

**Comment by pchote** [comment]
The old targeting logic was full of bugs related to spys, stealth, fog of war, etc.  It has been significantly rewritten since the last release to fix these. Reverting it to "like the last release" simply isn't an option.  Making additional changes to the new state is still possible, though.

**Comment by GraionDilach** [comment]
@pi99y You're supposed to see your allies' eye icon, indeed.

**Comment by cjshmyr** [comment]
To be clear, if this is only about re-adding the attack cursor for Spies, I'm in favor of that. If it happens I'd like to see the attack cursor behavior something configurable on the `Spy` trait.

**Comment by cjshmyr** [comment]
This is tricky because it was a bug that became an accepted feature, so I'd like to just make a bit more informed decision on truly making the attack cursor not show. I want it configurable in case that ever switches.

**Comment by pchote** [comment]
IIRC you got an attack cursor over a spy in both RA1 and RA2, but I may be wrong.
