### ISSUE TITLE
D2k, selling a building displays full crumble frame last

### ISSUE THREAD

**Issue by OmegaBolt** [OpenRA/OpenRA#10028]
When selling a building the "full rock" crumble frame is displayed as the very last frame shown, as if perhaps it loops round, and looks crappy because of it.
##

**Comment by pchote** [comment]
IIRC we have a specific workaround in the make animation code to handle this same problem there.  The rock overlay is separate to the make animation code, so the fix should be as simple as adding one line to copy what the make anim does.

**Comment by pchote** [comment]
This is caused by the make anim code, not the crumble overlay.  Tried to debug it, but didn't find anything obviously wrong.

**Comment by pchote** [comment]
No repro on current bleed, so we must have accidentally fixed this at some point.
