### ISSUE TITLE
Airplanes given "return to base" command do an unnecessary loop (if already flying towards base) 

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#10029]
(playtest: 20151114, and probably in previous versions too)
If an airplane (Yak, Mig... but not helicopters) is given a "return to base command" (default hotkey = "F") it sometimes does an unnecessary loop before returning home.
It turns out that it happens (only) when the airplane is already flying in the "right" direction (towards own base). 
 
This is quite annoying if it happens when the aircraft is in danger (over enemy troops) and since it is unexpected.
 
Here's a short replay. Watch the top, green player. When the Yak flies away from base (first right, then left) and is given the "return to home" command it works nicely. But it "fails" the third time (flying up, just before replay ends) since the Yak was already facing the base.
http://www.megafileupload.com/5v52/yakTurn.orarep

**Comment by epicelite** [comment]
Yeah can confirm, many a good plane lost to this.

**Comment by vietman391** [comment]
Same as my post at #9502 , but I didn't know they did that when they were facing the base.
