### ISSUE TITLE
Orcas have trouble hitting close targets

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#10024]
Regression from #8717. RA Longbows might be affected as well.

Tweaking the vertical ROT and maybe minimum range should be enough.

**Comment by matija-hustic** [comment]
It's about the minimum launch angle. Try putting it to -32 or -64.

**Comment by anjew175** [comment]
Just so you know, if i recall correctly, the same occurs if you have an orca on top of an Advanced Guard Tower

**Comment by matija-hustic** [comment]
This second is the guard tower's maximum launch angle. Maybe I should have put the defaults in the code to -256 for minimum and +256 for maximum so that it's perfectly flexible.
