### ISSUE TITLE
Spy, hijacker go out and enter again if given the same infiltrate command multiple times

### ISSUE THREAD

**Issue by Szunti** [OpenRA/OpenRA#10031]
(It happened in every version I tried: playtest-20151114 and the release before)

I don't know about others, but I sometimes click multiple times the same command for 'emphasis'.
Move commands and attack commands handle it well: my vehicles don't stop and start moving again.

But if I give the same infiltration order while the spy is already entering the building, it goes out and starts entering again. Same with the hijacker entering a vehicle.

**Comment by pchote** [comment]
Duplicate of #3923.
