### ISSUE TITLE
Latest OpenRA playtest does not install with Lua 5.3

### ISSUE THREAD

**Issue by wouterbeek** [OpenRA/OpenRA#10030]
I try to install the latest OpenRA playtest on Fedora 23 from RPM:

```bash
$ rpm -U openra-20151114-1.1.noarch.rpm 
error: Failed dependencies:
	lua = 5.1 is needed by openra-20151114-1.1.noarch
	mono(ICSharpCode.SharpZipLib) = 0.86.0.518 is needed by openra-20151114-1.1.noarch
	mono(Mono.Nat) is needed by openra-20151114-1.1.noarch
```

I have Lua 5.3 and Mono 4.0.4 installed.  Will a future version of OpenRA playtest support Lua 5.3 or should I downgrade to Lua 5.1?

**Comment by penev92** [comment]
For the time being we have a hard dependency on 5.1 and I don't see that changing in the foreseeable future.

**Comment by pchote** [comment]
The Lua 5.X releases feature major API changes that make them mutually incompatible (for the things we care about, at least).  We may eventually upgrade to 5.2 or 5.3, but there are no active plans for that.

**Comment by wouterbeek** [comment]
@pchote @penev92 Thanks for the info.  This makes compilation on Fedora 23 (which ships with these Lua and Mono defaults) slightly more complicated.  I'll wait for the maintainer of http://software.opensuse.org/download.html?project=games:openra&package=openra (currently supporting Fedora 22) to provide an updated solution for my OS as well.
