### ISSUE TITLE
Tiberium Sun: Selling tech should still allow you to build the advanced units

### ISSUE THREAD

**Issue by anjew175** [OpenRA/OpenRA#10053]
In the original game selling off a radar or advanced tech center would still allow all existing production buildings to make use of the tech. eg. building an advanced tech center and selling it straight away would still allow the creation of banshees from an existing helipad.
If the last production building of that type was destroyed the tech would then be reset.
Also if sold the tech center before building the helipad you wouldn't be able to build banshees.
Think this would be great to implement into the Tiberium Sun mod

**Comment by GraionDilach** [comment]
:-1: for reimplementing this too-famous Westwood bug.

**Comment by epicelite** [comment]
No.

**Comment by anjew175** [comment]
I feel it was an interesting feature that gave tiberium sun a difference in how players would go about their macro when playing multiplayer. Whether to tech fast or keep it until you fill all the production queues and it also made tech sniping different.

**Comment by pchote** [comment]
This bug was also present in the original RA (and probably TD).

**Comment by anjew175** [comment]
I never played the originals as competitively as TS so I didn't learn too many tricks.
Interesting to call it a bug if it manages to survive 3 games though?

**Comment by r34ch** [comment]
:-1:

It removes a large element of strategically targeting tech-structures to slow down an enemy teching their army.

**Comment by penev92** [comment]
Sounds like a bug to me.
A simplified technical explanation: the engine didn't bother to revoke/destroy the granted prerequisite when the structure was sold (did it stay if the building was destroyed?), which is an oversight on WW's part. Also they were pretty pressed for time, so they wouldn't have had the time to fix this (there are other much worse bugs and hacks that they left in).

**Comment by anjew175** [comment]
Yes the tech would stay if it was destroyed or even captured. If anything not having a tech building is a set back as all the enemy needs to do it capture or destroy your production facility and then you cant produce units at all until you build a new one then tech it up again. There are games were you would purchase the tech building multiple times, making it the tech center more of an active upgrade building rather than building once and just protecting it. This was only for high level play though, most players never sold their buildings.
I still feel it isnt really a bug if it manages to survive ~5 years.

**Comment by pchote** [comment]
The community patches to the original games hacked the exes to fix this issue (plus others).  The multiplayer communities of the originals certainly considered them to be a bug :smile:

**Comment by ScottNZ** [comment]
:-1:

**Comment by anjew175** [comment]
Nobody I know plays multiplayer with the community patches. Today most of the current Tiberium Sun players I know are on CnCNet which still has the existing bugs (such as the deploy/building glitch). The only downfall of the CnCNet Tiberium Sun is the lack of fog of war. Depends if you want you go for the original feel or the new OpenRA feel. Judging from the dissent, new gameplay is devs choose.

**Comment by GraionDilach** [comment]
Most TS mods I know of were all against this "feat" and do their best to reduce the chances of this happening. (It didn't got fixed in an exe hack though, that's true).
