### ISSUE TITLE
Phase Tank is worthless.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#10051]
Purpose of Phase Tank: To sneak past base defenses
What it cant do: Sneak past base defenses

**Comment by pchote** [comment]
This has been fixed in the playtests.

**Comment by epicelite** [comment]
All you did was give it more passengers and barely increase the sight.

**Comment by pchote** [comment]
Increasing the sight improves its ability to sneak past base defenses.

**Comment by epicelite** [comment]
Nearly every map is full of chokepoints that get quickly packed with defenses.
