### ISSUE TITLE
Cursors don't work correctly over bridges.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#10070]

**Comment by pchote** [comment]
This affects more than just rallypoints: units now show a move-blocked cursor over bridges too.

**Comment by pchote** [comment]
This is also a problem on playtest-20151114

**Comment by obrakmann** [comment]
git bisect says the culprit is c3dce785a54637301b941206fadbcd28271b499b from #9327.

**Comment by pchote** [comment]
I've fixed this properly in #10118.  For prep, we may want to revert #9327 (but then check that c4/repair still work! they already broke once)
