### ISSUE TITLE
GPS Inconsistency

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#10073]
So I should probably use a image to make this easier to see but I'm too lazy to make one.

You know the little "house" marker you get from GPS to indicate a building? Then if you scout the area it shows the building but not the little marker. Well, say that player sells that building or some shit like that, then the GPS will just leave you seeing the building, however if it were the house marker, that would disappear.

How to put this?

GPS will show changes for buildings you have not actually scouted yet. However buildings that you have scouted won't show changes.
So its kinda inconsistent if you see what I'm saying?

Possible solution: Show house marker over known buildings.

**Comment by pchote** [comment]
You've been around long enough to know that you should test the playtest before filing bugs like this :smile:  This has already been fixed.

**Comment by epicelite** [comment]
Nobody is ever on the playtest or maybe I would.

**Comment by penev92** [comment]
That's
a) not entirely true
b) not necessary to test something.
