### ISSUE TITLE
Convert Missile RangeLimit from ticks to WDist

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#10086]
In its current form, `RangeLimit` is not intuitive (when I read 'Range', I think of distance rather than time) and hard to get right on top of that (even more so now that missile speed can change during flight).

Converting it to WDist (defaulting to weapon range) would make the property name far less ambigous and the functionality much easier to control.

**Comment by pchote** [comment]
The issue is that it is inherantly measured / used in ticks.  How about we rename it to something more consistent/intuitive like `FuelDuration` instead?

**Comment by penev92** [comment]
Problem: Would the WDist account for arks? Or will it be the distance in a straight line?

**Comment by GraionDilach** [comment]
In TS/Ares, RangeLimit was RangeLimit and AFAIK is measured via passed distance, including arcs.

**Comment by pchote** [comment]
We could accumulate the total distance by adding the current velocity times to a counter each tick.

**Comment by reaperrr** [comment]
Closed by #11205.
