### ISSUE TITLE
Rocketsoldier anti-air rockets unintentionally buffed

### ISSUE THREAD

**Issue by cjshmyr** [OpenRA/OpenRA#10081]
Not sure when this happened (assuming the missile refactor). Comparing release-20150919 to playtest-20151114 gives me some different results.

Test case:
> Produce an `e3` and longbow or chinook
> Order `e3` to fire on the heli
> Keep moving heli around to evade missiles, while `e3` walks to catch up and shoot it

In release we can evade most missiles, in playtest we cannot.

**Comment by cjshmyr** [comment]
Might only want to dial back the `RedEye` yaml a bit? Destroyers seemed fine to me. No idea about land missiles but I'd rather not touch every single one.

**Comment by GraionDilach** [comment]
Just tweak the yaml. This is a definite improvement we should keep in the codebase (reverting it will hurt TS/RA2 in the long term and I've listed numerous ways to tweak it yamlwise).

**Comment by penev92** [comment]
The thing is to make sure the e3's anti-air missiles are the only thing affected across all 3 official mods, which I doubt.

**Comment by cjshmyr** [comment]
Remade under #10129 with more information, this might confuse people who land here first, since it affected more than just this.
