### ISSUE TITLE
Using a rotated display does not function correctly.

### ISSUE THREAD

**Issue by flakeydabanana** [OpenRA/OpenRA#10084]
When attempting to use a 180 deg rotated monitor ( dont ask me why :P ) the first run and installation of assests was successful but any attempts to open the application after the first run resulted in severe graphical glitches mainly the display flipping between 0 deg and 180 repeatedly. 

OS : Ubuntu 15.04
Graphics : AMD 7970
Version : playtest-20151114 affects all modes
##

**Comment by abcdefg30** [comment]
I can't reproduce this on the last release.
