### ISSUE TITLE
Earned/min stats across all mods needs adjustment.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#10090]
Currently there's the 'Earned/min' and 'Earned this minute' in the Economy tab. I don't know how 'Earned/min' is calculated but I suspect it's done over a relatively long time-interval. If the economy of a player shifts somewhere past 10 minutes (often earlier), then for some reason it feels like the stat takes forever to catch up to reality, making comparisons of players' economy for this stat nonsensical in the late-game.

The 'Earned this minute' is accurate but it requires you to follow the numbers for a little while as it builds up and resets every minute. You don't want to wait for that. Perhaps if this instead showed 'Earned last minute' and only updated itself every minute then it would be something you would want to have a peak at from time to time.
##

**Comment by GraionDilach** [comment]
Earned/min is calculated for the whole game.

**Comment by penev92** [comment]
That's actually the idea. It's an average number for the whole game.

**Comment by pchote** [comment]
IMO we should remove both of these stats, which are calculated in bogus ways.  The info in the resource graph is much more useful.

**Comment by GraionDilach** [comment]
I find the stats more useful than the graph tbh.

**Comment by RoosterDragon** [comment]
I think changing "Earned this minute" to "Earned last minute" (i.e. earnings over the last 60 seconds) would be a good idea.

**Comment by SoScared** [comment]
Any chance to revisit this before the next release?

E.g. a simple 'Earned/min' calculated over the past 3 minutes (including present) could quick-fix this and replace two relatively redundant stat posts.
