### ISSUE TITLE
Players get kicked from server upon game start when they have just downloaded the map being played.

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#10098]
I didn't debug this in-depth, but I just came across [this code](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Network/UnitOrders.cs#L98-L107) and am pretty sure that the reason for the kicking is that the downloaded map doesn't get added to the `MapCache` properly.
##

**Comment by FrameLimiter** [comment]
This was fixed by #10939
