### ISSUE TITLE
Unusable "grey ping" servers

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#10094]
These have been increasingly common over the last few releases.  We still don't know what triggers them, but we do know that restarting the server fixes them.

Clients can connect to the server and recieve the initial MOTD and map, but the ping then immediately switches to grey and players are kicked for "connection problems".

When connecting to one of these servers I see the following traffic: http://pastebin.com/raw.php?i=jyWF8cAF

There are two things to notice here:

1.  128 orphaned ClientPing entries in the `SyncInfo` order (only the last one, for my client id 496, is valid).
2.  No `SyncClientPings` or `SyncLobbyClients` orders, which should have followed immediately after this if the server was working properly.

I strongly suspect that this was introduced by #5115, but don't have the time to investigate further.
Hopefully this is a good enough start to identify the trigger and kill this issue for good.

**Comment by pchote** [comment]
```
[22:59:54]	<Spy1> can someone do something about the screwed up servers?
[22:59:57]	<Spy1> I think norman broke the game 
```
I less strongly suspect that clients that drop themselves or who are booted for connection problems aren't cleaned up properly, leaving orphaned ping entries and perhaps somehow triggering the issue.

**Comment by obrakmann** [comment]
First (related) mention of "grey ping" in the IRC logs is from 2015-05-04, so it looks likely that the problem was introduced with release-20150424.

**Comment by obrakmann** [comment]
There are probably only two PRs really that were merged during the 20150424 cycle that could have introduced the bug: #6946 and #7238.

**Comment by LipkeGu** [comment]
maybe the limit is too short 

https://github.com/OpenRA/OpenRA/pull/6946/files#diff-fd20fd5094d207b3a7dea8cf8dc1d2d2R22

**Comment by anjew175** [comment]
I currently just caused this bug on the skynet server.

xerver join the server, lagged out, rejoined whilst his old self was there, i kicked the old self and it killed the server

**Comment by pchote** [comment]
I've identified the cause of this, and can now trivially drop a server into the grey ping state.  
The fix isn't too hard, so I'll file a PR for our next playtest and do a backport branch for our Baxxster/64H release servers.

**Comment by pchote** [comment]
I've split #12072 out into its own ticket, that is a distinct issue unrelated to this.
