### ISSUE TITLE
Display user's IP-address on connect, nick change and disconnect

### ISSUE THREAD

**Issue by baxxxster** [OpenRA/OpenRA#10097]
I have noticed that someone is fakenicking me and joining my servers.

It is as of now not possible to find out who this is, and I'd love if you could see a user's IP-address in the console/log like this:

[2015-11-24T04:58:41] Baxxster (127.0.0.1) has joined the game.
[2015-11-24T04:58:42] Baxxster (127.0.0.1) is now known as King.
[2015-11-24T04:58:43] Baxxster (127.0.0.1) has disconnected.

**Comment by pchote** [comment]
It will be a simple one-line fix to log the IP on join.

**Comment by Mailaender** [comment]
Already tried it when doing https://github.com/OpenRA/OpenRA/pull/10067. When a player joins, you don't have the information yet.

**Comment by pchote** [comment]
`IpAddress = ((IPEndPoint)newConn.Socket.RemoteEndPoint).Address.ToString(),`

The information is encoded in the socket, which is the very thing that the player uses to connect!
