### ISSUE TITLE
debug in VS 2015

### ISSUE THREAD

**Issue by A51UK** [OpenRA/OpenRA#10107]
How are you able to debug the code using Visual Studio  2015? When I try the game take over the whole screen and I am unable to use the breakpoints. 

It be good to be able to use the breakpoint so I would be able to step though the flow of the game and make it more easy to debug error / code in the game. 

Is there any way to make the game only take part of the screen and be able to use breakpoint ?

**Comment by penev92** [comment]
Debugging in fullscreen is possible, but not very comfortable. Go to the Settings menu ingame and set it to run in Windowed mode.

**Comment by A51UK** [comment]
Thank You. I will try it tonight.
