### ISSUE TITLE
You can actually install the OpenRA shortcut without installing OpenRA

### ISSUE THREAD

**Issue by StexoO** [OpenRA/OpenRA#10102]
Is it possible to check and disable the Game checkbox in the installer ?

![meh](https://cloud.githubusercontent.com/assets/8930382/11383093/299a0c0a-9306-11e5-8ad5-b908557f3d7b.png)

IMHO only *real players* are able to play with the shortcut only. :trollface:

**Comment by Mailaender** [comment]
Yes, http://nsis.sourceforge.net/Graying_out_Section_(define_mandatory_sections)
