### ISSUE TITLE
Animations tick inside rendering functions

### ISSUE THREAD

**Issue by RoosterDragon** [OpenRA/OpenRA#10111]
Some areas call Animation.Tick from inside rendering functions instead of tick functions. This means the animation is tied to the framerate rather than the world time. This may lead to some animations becoming out of sync with the apparent world state.

Offending callsites are:
- [x] [WithDecoration](https://github.com/OpenRA/OpenRA/blob/da1485dab7e168be004f51bcf73046d5692822ef/OpenRA.Mods.Common/Traits/Render/WithDecoration.cs#L167)
- [x] [WithParachute](https://github.com/OpenRA/OpenRA/blob/da1485dab7e168be004f51bcf73046d5692822ef/OpenRA.Mods.Common/Traits/Render/WithParachute.cs#L149)
- [ ] [Carryall](https://github.com/OpenRA/OpenRA/blob/da1485dab7e168be004f51bcf73046d5692822ef/OpenRA.Mods.D2k/Traits/Carryall.cs#L208)

**Comment by pchote** [comment]
#10216 fixes this for WithDecoration.

**Comment by teees** [comment]
#10775 fixes this for Carryalls

**Comment by reaperrr** [comment]
#11291 fixes this for WithParachute.

**Comment by reaperrr** [comment]
#11501 fixed this for Carryalls.
