### ISSUE TITLE
self-defense spy?

### ISSUE THREAD

**Issue by vipches** [OpenRA/OpenRA#10116]
Ok, I have few idea about the allies spy, I was thinking we already set every unit on a defend mode already, why not let the spy has the same mode that can choose? when spy a not in disguise, they will automatic shoot any enemy unit nearby if they reach the fire range, and change on hold fire mode if it on disguise, so if you can doing that, then the allies can finally have a anit-spy unit that can protect not to get stole, because you spy will kill any disguise enemy spy on side.
##

**Comment by abcdefg30** [comment]
This is possible in newer version by setting the stance of the unit.
