### ISSUE TITLE
Map editor doesn't set Creeps' enemies

### ISSUE THREAD

**Issue by cjshmyr** [OpenRA/OpenRA#10127]
Creating a new map with a player results in yaml like such:

```
Players:
	PlayerReference@Neutral:
		Name: Neutral
		OwnsWorld: True
		NonCombatant: True
		Faction: england
	PlayerReference@Creeps:
		Name: Creeps
		NonCombatant: True
		Faction: england
	PlayerReference@Multi0:
		Name: Multi0
		Playable: True
		Faction: Random
		Enemies: Creeps
```

Missing `Enemies: Multi0` for Creeps

**Comment by penev92** [comment]
I can see this causing issues in new TD/D2k maps, as well as custom maps with "neutral" forces that are supposed to fight everybody, so adding to the release milestone.
