### ISSUE TITLE
Repair all building hotkey.

### ISSUE THREAD

**Issue by vipches** [OpenRA/OpenRA#10122]
I think mabye we can make a hotkey that can repair all building once you use it, because some time my building was get place too close on each other, that make me a difficult to see which building a damaged and which one don't, so if we can make this hotkey working, we may be much quickly to avoid some unnecessary building get destroyed just because those life bar a too close to each other.

**Comment by penev92** [comment]
I don't like all these "Make the game play itself" ideas. :-1:

**Comment by vipches** [comment]
The problem is, is really diffuculty to see life bar when you ore refinery and slot stay together, some time I even forgot to repair the slot, just because the refinery life bar was blocking it.

**Comment by pchote** [comment]
That should be fixed by #10011.

**Comment by Mailaender** [comment]
No consensus that this is actually wanted.
