### ISSUE TITLE
Missiles need some fine adjusting

### ISSUE THREAD

**Issue by cjshmyr** [OpenRA/OpenRA#10129]
The `Missile` enhancements that have gone in since the past release have been awesome and needed, but at the same time they beefed up missiles in all mods. I'm not proposing any code changes to the missiles, only yaml tweaks to get them back/similar to their release version states. **I'm also thinking TS is fine as-is, and this ticket applies only for RA, TD, and D2K**. We had received negative feedback in RA on this during a playtest, can't speak for other mods yet or if it's a concern there.

I have an automated RA test map here https://github.com/cjshmyr/OpenRA/commit/f941a0ed7f58f4fd184258f02ad38dce6893b5f2 that runs on both bleed and release. It should be useful when comparing the two, also when applying any balance changes back to bleed.

I've observed the following for RA:
- E3 anti-air is better
- Mammoth anti-air is better
- Destroyers all-around are better
- E3 and Chronotank land targeting seems unaffected

Not yet checked SAM sites.

**Comment by cjshmyr** [comment]
Seems that setting `Acceleration: 0` (currently `5`) gets us very close to the release's behavior, since acceleration is a new thing.

Excuse the quality, here's one snippet of the test map ran on three different builds
![dd-fix-comparison](https://cloud.githubusercontent.com/assets/566742/11454030/63eec0c4-95dd-11e5-8663-94238d98c0ee.png)

Also SAM sites seem fine.

**Comment by pchote** [comment]
Looks good to me. Lets set the default in the missile class to 0 (so it applies to all mods) and :ship:it

**Comment by cjshmyr** [comment]
Explaining some of [Missile.cs](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Effects/Missile.cs#L24) for context:

`MaximumLaunchSpeed` - Missiles are launched at this speed. In heightmap enabled mods this varies depending on a height difference, which may use `MinimumLaunchSpeed`.
`MaximumSpeed` - Highest speed the missile can attain. The default is `384` and all missiles currently have this value.
`Acceleration` - Under certain conditions the missile will [change speed](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Effects/Missile.cs#L398) to reach its target. The default acceleration results in changes of `+/-5`.

So speedup results from `Accceleration` and `MaximumSpeed`. Acceleration really kicks in often when altitude shifts. If rockets are being targeted against ground units they may change speed just `0-4` times. Airborne rockets on the other hand (any of destroyers', since they arc, or rocket soldier anti-air) accelerate extremely fast.
- Destroyer AG/AA accelerates from [`170`](https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/weapons/missiles.yaml#L296)/[`255`](https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/weapons/missiles.yaml#L336) to  `~250`/`384 (max)` within a second.
- Rocket soldier AG/AA accelerates from [`213`](https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/weapons/missiles.yaml#L46)/[`298`](https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/weapons/missiles.yaml#L232) to `~213-240`/`384 (max)` within a second.

---

I'm not convinced on the magical maximum speed value all missiles now have. If we look at tweaking individual missiles to tail off faster, it's still bogus that a missile can boost itself up +100 in under a second, so acceleration and/or max speed still needs a visit.

**Comment by reaperrr** [comment]
In my opinion, `MaximumSpeed` should be slightly refactored to be `MaximumAddedSpeed`, and internally max speed should then be `MinimumSpeed` + `MaximumAddedSpeed`. This would have several advantages, 
1) by default, the difference between minimum and maximum speed would be the same for all missiles,
2) the risk of modders accidentally setting a `MinimumSpeed` higher than `MaximumSpeed` would disappear,
3) we could set the internal default of `MaximumAddedSpeed` to `0`, meaning min speed = max speed, which is a much saner default for our shipping mods.

**Comment by pchote** [comment]
Did #10636 fix this enough?

**Comment by cjshmyr** [comment]
I'd say yes since it restored original behavior.

**Comment by pchote** [comment]
I guess we're done here then.
