### ISSUE TITLE
WavLoader crash: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by OmegaBolt** [OpenRA/OpenRA#10124]
http://pastebin.com/pZPYGGq9

They are IMA ADPCM 22khz mono files, that work in RA2/YR but crash the game here. Sounds in the download below.

https://www.dropbox.com/s/0b7dm6ct013ym1c/grenadier.rar?dl=1
##

**Comment by Mailaender** [comment]
The download is 404. If you re-upload I can take a look otherwise closing.
