### ISSUE TITLE
Add actor categories to the map editor

### ISSUE THREAD

**Issue by OmegaBolt** [OpenRA/OpenRA#10139]
Some kind of flag to set a category in the map editor. This would be very useful to organise faction buildings, civilian buildings and rocks & trees, vehicles, infantry etc etc. The lack of organisation becomes a lot more evident in TS and of course RA2, which has hundreds of civilian buildings.
##

**Comment by pchote** [comment]
:+1:

We may already have a ticket for this, but i'm not sure.

**Comment by GraionDilach** [comment]
This is something I'd advocate practically - mods using voxels end up terribl laggy when the sidebar reaches them.

**Comment by reaperrr** [comment]
I'd like to see this sooner rather than later myself and will take a stab at this, targeting the next (major) release.

**Comment by reaperrr** [comment]
@rob-v since you're already working on related editor aspects, would you mind taking this on? UI isn't my strong point, so I'd actually prefer to concentrate on other things on my roadmap.

**Comment by rob-v** [comment]
Ok. Should there be Category dropdown below current owner dropdown?

**Comment by reaperrr** [comment]
That's what I had in mind, yes.

**Comment by rob-v** [comment]
#13353
