### ISSUE TITLE
Annoying the actors?

### ISSUE THREAD

**Issue by scskwirl** [OpenRA/OpenRA#10132]
Is there a way for putting in voices for when you click on an actor multiple times, that they may say something else besides when being selected normally? Some games they say things that show they're annoyed and is usually a fun gimmick.

A sort of throwback easter egg from games like Warcraft 2 when you did it many, many times to a neutral actor (ie: an animal), the unit would unexpectedly blow up and die.
##

**Comment by abcdefg30** [comment]
This is likely doable in custom mods (using `INotifySelected`), but I don't see it happening for the default mods.
