### ISSUE TITLE
Graphics quality setting

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#10149]
I propose a new `bool Game.Settings.Graphics.CosmeticEffects` which switches optional effects such as trails, decorational sprite overlays and palette rotations on and off. For traits like `WithIdleOverlay` there needs to be a new setting in TraitInfo like `bool PurelyDecorational` which decides if this is optional or has to be rendered. The might not have much effect on (rendering) performance, but in sum should add up. The original Tiberian Sun and Red Alert 2 had a slider named "Visual Details" as well.

**Comment by pchote** [comment]
:-1: to adding a placebo setting on the justifiction "I saw game critics actively search for such settings to judge how developed an engine is and complain if they are missing." (from #10133).  We are not doing any complicated rendering, so if I were an outside observer I would see such an option as a sign that something was deeply wrong with the OpenRA engine.

**Comment by Mailaender** [comment]
I wasn't planing to add a placebo although my thinking my be naive here: z-sorting of effects is expensive https://github.com/OpenRA/OpenRA/issues/7520#issuecomment-75443959 so less effects improves performance. The question is probably where to draw the line: which effects are required for gameplay: removing corpses e.g. might cause some irritations etc. but if the whole plan won't make the game run smoother on less powerful hardware, then we don't need to pursue this further.

**Comment by pchote** [comment]
That comment is based on outdated info.  @RoosterDragon ran the numbers on recent code and found it to be cheap: #10119

> Sorting just the actors alone costs 1.4% CPU, whilst sorting both actors and effects raises it to 1.8%. So the performance impact isn't too bad.
