### ISSUE TITLE
A sub-option for the debug checkbox Build Everything

### ISSUE THREAD

**Issue by xan2622** [OpenRA/OpenRA#10157]
Couldn't the debug option "Build Everything" have a "sub-option" (a checkbox placed bellow) ?
Unchecked, this checkbox would allow to build everything (but restricting the units/buildings to the current player's faction). Checked, the checkbox would allow to build everything (all factions).

![screenshot002](https://cloud.githubusercontent.com/assets/1732773/11484428/3c790856-97ae-11e5-95db-049692c077b1.jpg)
##

**Comment by pchote** [comment]
This isn't really possible.  The cheat disables all prerequisite checks.  You want to swap in a different set of prerequisites, which is a completely different feature / set of code.

**Comment by MustaphaTR** [comment]
I think we should make current one remove normal ones but but check for "~"'s on prerequisite and All factions should enable really all.

**Comment by GraionDilach** [comment]
:-1:

Current one is good as-is. It does not merge the queues so multifactory with sidespecific queues won't be overridden via that way.

**Comment by obrakmann** [comment]
I don't think this is really necessary. You can always either set the correct faction in the lobby or quickly build the other faction's conyard, both of which take ~5 secs. max. It's not worth it to write new code for this.

**Comment by penev92** [comment]
I agree with @obrakmann

**Comment by pchote** [comment]
Closing as unlikely to happen.
