### ISSUE TITLE
Limit of 2 MCV's max in Red Alert.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#10159]
Having a fun game and then, you know that guy, that guy decides "Im just gonna build me a bunch of artirs/V2's and keep them save with base defenses!" and ruins all of the fun.

I leave a game at the first sign of basewalking because its just not fun for anyone involved.

**Comment by Aaron-Lloyd** [comment]
I don't really like this idea as a default game rule, but maybe a drop down for a limit of MCVs in the game options might be nice. It'd in the very least allow for some experimentation with the idea I suppose.

**Comment by epicelite** [comment]
I say 2 but MAAAAAAYBE 3.

The theory is you have one for your main base, and another for a secondary base or you can try to basewalk with it but it will be actually risky since you only get 2 of them.  You cant just replace it instantly without sacreficing the safety of your only other MCV or waiting for another to build.

So you can still basewalk, but it will actually be potentially stoppable for the defending player. You could still have like more then 1 enemy player working together but unless its a shitty map like doubles that would leave openings to flank.

Those fucking games where the attacking players have a seemingly endless supply of MCV's so you can't do shit about it are not fun. You use up most of your army to take out 1 MCV and 2 more have already taken its place.

BONUS POINTS: You can't deploy 2 MCV's in the same build radius. Friendly players that is, enemy's should still be able to I guess to prevent lockout scenarios.

**Comment by pchote** [comment]
This could be done in a third party mod or a map, but I don't see these arbitrary limits being included in our default mods.

**Comment by anjew175** [comment]
The basewalking problem should be fixed at the root, the artillery units and the base defences. I agree with pchote, it is an arbitrary limit since the it is in the game to allow up 5(?) MCVs to make construction time shorter. I could see a limit at 5 or whatever but not anything less.

**Comment by penev92** [comment]
Yeah, what @pchote said. Also the "fix at the root" thing.
