### ISSUE TITLE
Homing AreaBeam weapon

### ISSUE THREAD

**Issue by UberWaffe** [OpenRA/OpenRA#10181]
Followup feature request to #9357 which introduced an area beam A.K.A. line impact projectile.

The existing area beam weapon has a static target, not re-adjusting its aim if its target is on the move. Instead it just keep firing at the spot the target was when it started shooting.

This is fine for Railgun weapons (Ghost + Mammoth Mk2) but the original TS disruptor tanks tracked their targets with their beam even if the target moved.

The following behavior should apply for a `HomingAreaBeam`:
- Should have a `RangeLimit` similar to missiles, in that it can continue tracking the target until this many ticks have passed since it started being emitted.
- Otherwise function as the existing `AreaBeam`.
##

**Comment by reaperrr** [comment]
In my opinion we should simply add tracking support to `AreaBeam`, and add a `TracksTarget` boolean property to toggle it on/off.
