### ISSUE TITLE
[Playtest-20151129] Cannot power down production facilities.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#10188]
In original RA you could power down production buildings, why not in this one? Really useful early game when you get you're low on power and just need a little more to speed up construction but you don't have all the high tech power hungry stuff yet.

**Comment by jaZzKCS** [comment]
I can't actually remember. Were you really able to power down a weapons factory or barracks? Mind rip.

**Comment by pchote** [comment]
Power down was only in TS.  It definitely wasn't in the original RA, and I don't think it was in RA2 either(?).

**Comment by abcdefg30** [comment]
It wasn't in RA2, yes.

**Comment by jaZzKCS** [comment]
Definitely not, and I don't recall being able to powerdown for example a Hand of Nod as well. I can only recall being able to powerdown the high tech power users like stealth gen and radar...

**Comment by Mailaender** [comment]
Duplicate of https://github.com/OpenRA/OpenRA/issues/3769 I assume.
