### ISSUE TITLE
Destroyer Max Range Damage Bug

### ISSUE THREAD

**Issue by fgdzfggsfgsfgsf** [OpenRA/OpenRA#10186]
Basically when the destroyers are at max range they do 0 or effectively 0 damage.  FiveAces has mentioned this a lot but I didn't see anything in issues other than this [erroneously?] closed issue.
https://github.com/OpenRA/OpenRA/issues/8476

**Comment by abcdefg30** [comment]
Can you provide an reproduction case / more examples than in #8476?
In #8476 the destroyers didn't fire at the target but rather in front of it, so I guess the player did a missclick with forcefiring there.

**Comment by fgdzfggsfgsfgsf** [comment]
" the destroyers didn't fire at the target but rather in front of it"  - that's the bug.  Sometimes you target a building (not force firing) and the destroyers don't or can't drive up close enough to the target so their missiles hit very poorly.  The building looks like it has been properly targeted though (red line to it's center).  It still seems to do about 10% of the damage of a non-glitched unit (this might vary).  Happens even with shroud and fog disabled.  If you move the unit closer (and you don't even have to re-target) the glitch stops.  Seems to happen more often when the destroyer isn't facing it's target.

Also a related possible bug is that when the destroyer targets a building out of it's immediate range (and thus has to drive up to it), the first shot almost always misses.

**Comment by abcdefg30** [comment]
Ah, thanks for the clarification.

**Comment by penev92** [comment]
What version is this happening on?

**Comment by fgdzfggsfgsfgsf** [comment]
Release.

**Comment by fgdzfggsfgsfgsf** [comment]
Might be fixed in playtest, testing now.

This part appears to be fixed at a minimum:  
Also a related possible bug is that when the destroyer targets a building out of it's immediate range (and thus has to drive up to it), the first shot almost always misses.

**Comment by fgdzfggsfgsfgsf** [comment]
As far as I can tell this is fixed in 2015-11-29, so feel free to close.

**Comment by cjshmyr** [comment]
If it was fixed, probably a nice side effect of the missile behavior improvements lately

**Comment by fgdzfggsfgsfgsf** [comment]
This is back unfortunately, newest release.

**Comment by abcdefg30** [comment]
I actually saw that myself on latest bleed. It's quite easy to reproduce now:
![destroyerbug](https://cloud.githubusercontent.com/assets/7704140/14171500/9f9caeee-f733-11e5-8bfb-f22b9390c1db.png)

**Comment by GraionDilach** [comment]
`Stinger` has `Spread: 128` with the default 2XX `CloseEnough`. That's kinda expected to happen with these seetings tbh.

**Comment by Phrohdoh** [comment]
The combat overlay would be pretty helpful here regarding spread.

**Comment by GraionDilach** [comment]
This situation is obvious though, the combat debug overlay wouldn't add more info than that.

If `CloseEnough` > `Spread`, then the missile will be a proximity one and would only deliver full damage if the target ran straight into it. Since `CloseEnough` defaults to 298 and the `Spread` is 128 with a `Speed` of 170, the weapon will deliver between 37% (less than 256 world unit distance) and 14% (256-298 world unit distance) of the intended damage. It can only deliver the full damage to a static target in a really edge case, because 298-170=128 and I haven't looked up the code to check if `CloseEnough` would trigger the explosion at it's exact distance.
