### ISSUE TITLE
Cannot download the game

### ISSUE THREAD

**Issue by inmytime** [OpenRA/OpenRA#10194]
Hi, i'm a chinese player. Maybe this is a low level problem. But i can't download the build no mater "releases" or "playtest" on http://www.openra.net/download/. And the browser tips it's a SSL error occurred. :(

**Comment by penev92** [comment]
Which packages are you trying to download? For which OS?

**Comment by inmytime** [comment]
i use mac. but when i try to download windows packages, it also failed.

**Comment by inmytime** [comment]
i use mac. but when i try to download windows packages, it also failed.

**Comment by inmytime** [comment]
i use mac. but when i try to download windows packages, it also failed.

**Comment by inmytime** [comment]
i use mac. but when i try to download windows packages, it also failed.

**Comment by inmytime** [comment]
i use mac. but when i try to download windows packages, it also failed.

**Comment by inmytime** [comment]
i use mac. but when i try to download windows packages, it also failed.

**Comment by fgdzfggsfgsfgsf** [comment]
Maybe try disabling your anti-virus?  And/or restart your computer, use VPN, use a different browser.

**Comment by Mailaender** [comment]
Try copy pasting the download link and change HTTPS to HTTP.

**Comment by Mailaender** [comment]
If the problem persists, contact @GitHub support. This may also be a censorship problem if you are trying to download the game from mainland China. For reference: we lost our whole Asian mirror network a while ago. https://github.com/OpenRA/OpenRAWeb/pull/261
