### ISSUE TITLE
[Playtest-20151129] Error codepage 850 not supported 

### ISSUE THREAD

**Issue by VanDeWetering** [OpenRA/OpenRA#10197]
Installation works fine, but getting trouble while  downloading /installing dune2K assests : 
Error: CodePage 850 not supported
OS: Mint 17.1
uname -a: 
Linux Tuxedo 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pchote** [comment]
If i remember correctly this is caused by a bug in mono when your system language is set to greek (and probably other languages). Try forcing it to english and it should work.

**Comment by VanDeWetering** [comment]
my system language is german....

**Comment by VanDeWetering** [comment]
if I set up a VM - what (linux) os and system specifications are recommended? I know for example that Ubuntu 12.04 LTS troubles because of libsdl2 dependencies.

**Comment by GraionDilach** [comment]
0 A.D.'s PPA worked for me regarding the libsdl2 dependency on 12.04 Kubuntu.

**Comment by VanDeWetering** [comment]
@GraionDilach can give me a bit more detailed information about what you did.. I wasn't able to install libsdl2 -  do i have ti install 0 A.D.?

**Comment by GraionDilach** [comment]
@VanDeWetering No, you have to add ppa:wfg/0ad to your list of software sources then you can install libsdl2 via apt-get. See https://launchpad.net/+help-soyuz/ppa-sources-list.html for a detailed tutorial.

**Comment by VanDeWetering** [comment]
@GraionDilach thanks for the tip ... but it didn't worked for me:
sudo add-apt-repository ppa:wfg/0ad
[...]
sudo apt-get update
[...]
sudo apt-get install libsdl2
[...]
Package libsdl2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libsdl2' has no installation candidate

**Comment by pchote** [comment]
@VanDeWetering if you're setting up a VM from scratch I recommend using the 14.04 LTS over 12.04. 14.04 includes all the dependencies you need in the upstream repositories.

**Comment by VanDeWetering** [comment]
Hello again
it is ot, but openra is extremly slow within the vbox (14.04 System). Firefox is fine...Does someone has experience with actual release in a box?

**Comment by pchote** [comment]
You should be able to work around the codepage error by forcing the encoding to UTF8 (set the `LANG` environment variable to `en_US.UTF-8`)

**Comment by VanDeWetering** [comment]
I tried 
LANG=en_US.UTF-8 openra
 Still codepage error

**Comment by VanDeWetering** [comment]
the variable was set:
echo $LANG
en_US.UTF-8

**Comment by VanDeWetering** [comment]
Openra is running in the box, but extremely slow. May I copy the  assests from the box to the host system? What folders / files do I have to consider?

**Comment by DestructionOfPlanetJupiter** [comment]
Same error here. I tried to install either of three games that have been made available, but neither would go through with the installation. Every time I get the 850 error

**Comment by FoxVK** [comment]
export LANG=en_US.UTF-8
openra

solved this issue for me

**Comment by VanDeWetering** [comment]
after 
export LANG=en_US.UTF-8
openra
ferror code changed to Codepage 437 not supported
