### ISSUE TITLE
Option serverside to save replays 

### ISSUE THREAD

**Issue by anjew175** [OpenRA/OpenRA#10190]
Would be nice to implement an option for the server owner to allow replays to be saved serverside primarily in the case of competition and tournaments. It would allow players to play unhindered by having an official or witness present. It would also be useful for casters as they could easily access tournament replays.
##

**Comment by jaZzKCS** [comment]
This is a splendid idea.

:+1:

**Comment by klaas1** [comment]
Related to this: it would be nice if the server can keep track of Wins-Loses coupled to name/IP. Ideally one would be able to setup a server for a league, with some sort of ranking algorithm.

**Comment by penev92** [comment]
That doesn't work without player authentication. Let's not mix thing up on this ticket.

**Comment by StexoO** [comment]
@klaas1 See https://github.com/OpenRA/OpenRA/issues/2815

**Comment by SoScared** [comment]
In addition to competitions another big potential is gathering data from games in general, including playtest maps.

**Comment by jaZzKCS** [comment]
Very yes. Major server hosts could accumulate replays and certain problems/new additions could be evaluated much easier.

**Comment by deleted-user-1** [comment]
#14686,  #17578, #18696

**Comment by pchote** [comment]
This has now been implemented.
