### ISSUE TITLE
use cd option on fresh openra start ends in an infinite loop

### ISSUE THREAD

**Issue by jose1711** [OpenRA/OpenRA#10200]
reproduce on i686, arch linux, openra 20150919

1. download CD1_ALLIED_DISC.ISO from CNCNZ.com
2. mount it to /mnt (-o loop)
3. delete ~/.openra
4. start openra
5. when asked about content: go with "use cd" option
6. progressbar displays but then dialog pops up still asking about cd

installer manages to extract and copy the following files from cd:
allies.mix
conquer.mix
general.mix
interior.mix
REDALERT.MIX
russian.mix
scores.mix
snow.mix
sounds.mix
temperat.mix

**Comment by penev92** [comment]
Just a wild guess, but the names of the extracted files don't match the names that the game expects because your OS is case-sensitive when it comes to file names and it derps hard, thinking the files are missing.

**Comment by jose1711** [comment]
thank you, indeed renaming REDALERT.MIX to lowercase version stopped the prompt from appearing but now the quesiton is: am i not supposed to see and play the original missions?

**Comment by abcdefg30** [comment]
> am i not supposed to see and play the original missions

Unfortunately we can't just copy the missions out of the original game, but have to re-script them.
So you should be able to play a few of them, but not all (`Main Menu` -> `Singleplayer` -> `Missions`).

**Comment by jose1711** [comment]
i see. does it mean - for linux users - that the only way to run all the original missions (sans emulator) is to use openredalert from http://sourceforge.net/projects/openredalert/ ?

**Comment by pchote** [comment]
I believe that project died before it was completed.  You'll need to use Wine with the original exe if you want the full original experience.

**Comment by pchote** [comment]
When mounting the isos under linux you need to specify `map=off` to disable the automatic filename translation.  The ISO format specifies that filenames are in upper case, and this is what OpenRA expects, but the linux `mount` utility will convert all filenames to lowercase by default unless you tell it not to.
