### ISSUE TITLE
URLError on resource.openra.net

### ISSUE THREAD

**Issue by StexoO** [OpenRA/OpenRA#10202]
I can see a map like http://resource.openra.net/maps/1801 and it works.
If a map doesn't exist like http://resource.openra.net/maps/99999999, I get back to the index.
If I try to go to http://resource.openra.net/maps/1802, server "crash".
I don't know if other maps are affected.
![urlerror](https://cloud.githubusercontent.com/assets/8930382/11757136/3f87746a-a05f-11e5-8846-ee26e1e35a15.png)

**Comment by obrakmann** [comment]
Moved to the resource site's issue tracker: openra/openra-resources#267
