### ISSUE TITLE
[Question] helping out

### ISSUE THREAD

**Issue by johanneslumpe** [OpenRA/OpenRA#10218]
Hi, first of: huge kudos for this project - amazing work! I really would like to help out, but I don't really have prior experience in C#. Do you think I could still help out via learning by doing? If not that's fine too, just curious what your opinion on this is.

Really want to see Tiberian Sun happen ;)

**Comment by abcdefg30** [comment]
Feel free to join us in IRC (channel: [`#openra`](http://webchat.freenode.net/?channels=openra)).

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/wiki/Contributing should get you started.
