### ISSUE TITLE
IndexOutOfRangeException in OpenRA.Mods.D2k.Traits.LaysTerrain.AddedToWorld

### ISSUE THREAD

**Issue by kiores** [OpenRA/OpenRA#10212]
Dune 2000 Mod at Version playtest-20151129
on map e1d72e09ab83a0ac5982e92ad1f037e697b429ef (The Fight by kiores).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000

Exception of type `System.IndexOutOfRangeException`: Index was outside the bounds of the array

   vid OpenRA.CellLayer`1.get_Item(MPos uv)
   vid OpenRA.Map.GetTerrainIndex(CPos cell)
   vid OpenRA.Map.GetTerrainInfo(CPos cell)
   vid OpenRA.Mods.D2k.Traits.LaysTerrain.AddedToWorld(Actor self)
   vid OpenRA.World.Add(Actor a)
   vid OpenRA.World.CreateActor(Boolean addToWorld, String name, TypeDictionary initDict)
   vid OpenRA.World.CreateActor(String name, TypeDictionary initDict)
   vid OpenRA.Mods.Common.Traits.PlaceBuilding.<ResolveOrder>c__AnonStorey0.<>m__0(World w)
   vid OpenRA.World.Tick()
   vid OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   vid OpenRA.Game.LogicTick()
   vid OpenRA.Game.Loop()
   vid OpenRA.Game.Run()
   vid OpenRA.Program.Run(String[] args)
   vid OpenRA.Program.Main(String[] args)

**Comment by kiores** [comment]
[exception.txt](https://github.com/OpenRA/OpenRA/files/60488/exception.txt)

**Comment by RoosterDragon** [comment]
This can be recreated by placing concrete off of the map in the extreme top-left or bottom-right corner of the off-map area.
