### ISSUE TITLE
Changing the volume / notification on Ubuntu crashes the game

### ISSUE THREAD

**Issue by fmestevez** [OpenRA/OpenRA#10219]
In any of OpenRA's mods, when I press Volume Up/Volume Down on my keyboard in-game, the game freezes, and I have to switch to another terminal (Ctrl + Alt + F1-6), and kill openra, compiz and nautilus to get it working again.
I don't know if this is because the volume itself or the Gnome/Ubuntu desktop notification.

**Comment by pchote** [comment]
This looks to be a duplicate of #9914, which is caused by a linux kernel bug.  Thanks for the report!
Closing, as there's nothing that we can do about this.  Please let us know if upgrading the kernel doesn't fix this.

**Comment by fmestevez** [comment]
Sorry for that, a quick search didn't bring up anything before posting :) 
Will let you know, thanks for the quick response.
