### ISSUE TITLE
"Targeted-units" (red) selection boxes do not appear on already selected units

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#10220]
Tested on: release-20150919, playtest-20151213 

When your units are already selected and you try to target them with the iron curtain (possibly chrono shift as well - not tested) the additional "targeted units" boxes (red) do not appear. Only the "+" shaped area is visible on ground - but is sometimes harder to see.

Current behaviour:
![iconselectedunits](https://cloud.githubusercontent.com/assets/10639257/11775256/8f4fdc50-a23d-11e5-80a8-2693d413994b.jpg)

Suggested:
![suggested_iconselectedunits](https://cloud.githubusercontent.com/assets/10639257/11775259/9600ff02-a23d-11e5-9eba-38319c86c732.jpg)
##

**Comment by matjaeck** [comment]
> the additional "targeted units" boxes (red) do not appear.

This is fixed,  they are all red no matter if you had the units selected before.
