### ISSUE TITLE
Neutral frozen actors are not revealed when starting with explored map

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#10228]
Noticed during stream of playtest-20151213.  May be a duplicate.  Affects tech structures, walls, etc.

**Comment by RoosterDragon** [comment]
Regression introduced by cbc090dd3873480a8f3b1d0cee982a9a3c97fdbc (bleed) / (f26b0f12518c5e31ea15617d9e50ff495ec80eb7) prep.

**Comment by RoosterDragon** [comment]
Assuming you're from the future and wanting to unstick this for the milestone but no fix has materialized: reverting would totally be fine.

**Comment by obrakmann** [comment]
Well, here's what I found: In `FrozenActor`'s constructor, `NeedRenderables` is set to the value of `startsRevealed`. At the end of the constructor `UpdateVisibility` is called, which overwrites `NeedRenderables` with the result of `Visible && !wasVisible`, so the value of `startsRevealed` basically never has any effect. Removing the call to `UpdateVisibility` from the constructor fixes the issue for me. I'm just not sure if it's needed for anything else, ie. if that's the right fix.
