### ISSUE TITLE
Spy gets detected by enemy soldiers and flame towers

### ISSUE THREAD

**Issue by dkessel** [OpenRA/OpenRA#10226]
I am using playtest 20151213
When playing the RA single player mission "Tanya's Tale", the spy gets detected by the soldiers and the flame turrets.
This makes completing the mission very hard, if not impossible.

I believe in the original game, the soldiers did not detect a spy. I am unsure about the flame towers, though.

**Comment by obrakmann** [comment]
Stupid question, but did you disguise the spy?

**Comment by dkessel** [comment]
nevermind :) it's really been a while

**Comment by abcdefg30** [comment]
I filed #10267 to make it clearer that you have to disguise your spy.
