### ISSUE TITLE
Lobby crash due to yaml-hardcoded teams / spawns

### ISSUE THREAD

**Issue by impulse9** [OpenRA/OpenRA#10230]
Game crashes in lobby under specific conditions. Attached picture explains how to reproduce the crash.

![openra_crash_report](https://cloud.githubusercontent.com/assets/2159248/11810389/f92a18ca-a32d-11e5-8dea-cac8c4a59a68.jpg)

Note: should say "select another SLOT" under step 2.

Some clarifications: map has 4 slots, it defines the 1st slot to be team 1, spawn A and other slots to be team 2 with a chooseable spawn. I believe the bug happens because the game allows spawn A to be selected when slot 1 is unoccupied. When a player enters slot 1 and spawn A is already occupied, the game crashes.

I fixed the issue for now by hardcoding spawns so it doesn't keep crashing but should someone investigate this issue they can use this version of the map: http://resource.openra.net/maps/6611

**Comment by ThisBlunt** [comment]
I found that if you set up teams like this:

![screen shot 2015-12-29 at 11 42 01 am](https://cloud.githubusercontent.com/assets/14940856/12037918/8eb42158-ae21-11e5-9495-35f0c552a42b.png)
Where LockSpawn is applied to all the spawns 

it will prevent the spawn from being occupied in the lobby.
