### ISSUE TITLE
Remember irc/lobby chat username

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#10231]
Now irc-username is not remembered i RC3, and I have to type it in every time.

**Comment by pi99y** [comment]
Tested on bleed and it works (nickname remembered). You have to connect before it remembers it.

**Comment by kyrreso** [comment]
It could also be the change between playtest/release, but I have this problem in RC3, and I always connect. Could also be in option if it does not work elsewhere..

**Comment by obrakmann** [comment]
Yeah, if you switch back and forth between release and playtest it would forget your irc username (just as with any other newly introduced settings, like the target line setting, or the status bar one that will be in next+1.
