### ISSUE TITLE
Fedora: SDK path could not be resolved

### ISSUE THREAD

**Issue by liquidat** [OpenRA/OpenRA#10248]
Dear team,
I try to build playtest 2015-12-13 on Fedora 23 but it fails during the make all command with the following error:

    $ make all
    + download_dir=./thirdparty/download
    + mkdir -p ./thirdparty/download
    + cd ./thirdparty/download
    + '[' '!' ']'
    + which nuget
    + '[' '!' -f StyleCopPlus.dll ']'
    + '[' '!' -f StyleCop.dll ']'
    + '[' '!' -f ICSharpCode.SharpZipLib.dll ']'
    + '[' '!' -f MaxMind.GeoIP2.dll ']'
    + '[' '!' -f SharpFont.dll ']'
    + '[' '!' -f nunit.framework.dll ']'
    + '[' '!' -f Mono.Nat.dll ']'
    + '[' '!' -f FuzzyLogicLibrary.dll ']'
    + '[' '!' -f SDL2-CS.dll ']'
    + '[' '!' -f Eluant.dll ']'
    + '[' '!' -f SmarIrc4net.dll ']'
    CSC fixheader.exe
    error CS8001: Warning as Error: SDK path could not be resolved
    Compilation failed: 1 error(s), 0 warnings
    Makefile:251: recipe for target 'fixheader.exe' failed
    make: *** [fixheader.exe] Error 1

I wonder what the given SDK could be. I installed the following mono and sdl packages:

    mono-addins-1.1-2.fc23.x86_64
    mono-core-4.0.5-1.fc23.x86_64
    mono-data-4.0.5-1.fc23.x86_64
    mono-data-sqlite-4.0.5-1.fc23.x86_64
    mono-devel-4.0.5-1.fc23.x86_64
    monodevelop-5.9.7-1.fc23.x86_64
    monodoc-4.0.5-1.fc23.x86_64
    mono-extras-4.0.5-1.fc23.x86_64
    mono-locale-extras-4.0.5-1.fc23.x86_64
    mono-mvc-4.0.5-1.fc23.x86_64
    mono-mvc-devel-4.0.5-1.fc23.x86_64
    mono-wcf-4.0.5-1.fc23.x86_64
    mono-web-4.0.5-1.fc23.x86_64
    mono-winforms-4.0.5-1.fc23.x86_64
    mono-winfx-4.0.5-1.fc23.x86_64
    SDL-1.2.15-20.fc23.x86_64
    SDL2-2.0.3-7.fc23.x86_64
    SDL2-devel-2.0.3-7.fc23.x86_64
    SDL2_gfx-1.0.0-7.fc23.x86_64
    SDL2_gfx-devel-1.0.0-7.fc23.x86_64
    SDL2_gfx-docs-1.0.0-7.fc23.noarch
    SDL2_image-2.0.0-8.fc23.x86_64
    SDL2_image-devel-2.0.0-8.fc23.x86_64
    SDL2_mixer-2.0.0-8.fc23.x86_64
    SDL2_mixer-devel-2.0.0-8.fc23.x86_64
    SDL2_net-2.0.0-3.fc23.x86_64
    SDL2_net-devel-2.0.0-3.fc23.x86_64
    SDL2_ttf-2.0.12-5.fc23.x86_64
    SDL2_ttf-devel-2.0.12-5.fc23.x86_64
    SDL-devel-1.2.15-20.fc23.x86_64
    SDL_gfx-2.0.25-3.fc23.x86_64
    SDL_gfx-devel-2.0.25-3.fc23.x86_64
    SDL_image-1.2.12-12.fc23.x86_64
    SDL_image-devel-1.2.12-12.fc23.x86_64
    SDL_mixer-1.2.12-10.fc23.x86_64
    SDL_mixer-devel-1.2.12-10.fc23.x86_64
    SDL_net-1.2.8-7.fc23.x86_64
    SDL_net-devel-1.2.8-7.fc23.x86_64
    SDL_Pango-0.1.2-21.fc23.x86_64
    SDL_Pango-devel-0.1.2-21.fc23.x86_64
    SDL_sound-1.0.3-15.fc23.x86_64
    SDL_sound-devel-1.0.3-15.fc23.x86_64
    SDL-static-1.2.15-20.fc23.x86_64
    SDL_ttf-2.0.11-7.fc23.x86_64
    SDL_ttf-devel-2.0.11-7.fc23.x86_64

So what am I missing here?

Steps to reproduce:

1. take a Fedora 23
2. install the neecssary packlages mentioned above
3. download the archive, extract it
4. cd to the archive, make depedencies, make all
5. see the error

**Comment by Mailaender** [comment]
@rapgro may be able to help.

**Comment by obrakmann** [comment]
Googling the error message ("CS8001: SDK path could not be resolved") suggests that something is wrong with your mono installation, which wouldn't surprise me at all on Fedora.

**Comment by rapgro** [comment]
Well, it seems to be some issue with nuget. You may consider to ask at mono mailing list:
https://lists.fedoraproject.org/admin/lists/mono.lists.fedoraproject.org/

Please be aware that Fedora does not support thirdparty binaries from outside the official repositories. We're working currently on official packages, maybe you would like to help there?

**Comment by Mailaender** [comment]
> Well, it seems to be some issue with nuget.

In that case try uninstalling nuget. We have a backfall script in place.

**Comment by liquidat** [comment]
Dear team, thanks for the replys, I will try to see what the Fedora people say about that.

**Comment by Mailaender** [comment]
This problem is also failing our https://build.opensuse.org/package/show/games:openra/release for Fedora 23.

**Comment by Mailaender** [comment]
I tried fixing it, but https://github.com/OpenRA/OpenRA/commit/0ce1b300f74477eada96048f122a1027bc3b120b didn't solve the compiling for Fedora 23. It even broke the compilation for Fedora 22:

> error CS8026: Invalid sdk version name

**Comment by Mailaender** [comment]
Reported upstream at https://bugzilla.redhat.com/show_bug.cgi?id=1294967

**Comment by Mailaender** [comment]
Use http://www.mono-project.com/docs/getting-started/install/linux/#centos-7-fedora-19-and-derivatives or our https://software.opensuse.org/download.html?project=games%3Aopenra&package=mono-core until this is fixed in Fedora.

**Comment by pchote** [comment]
This is also a problem with the mono 4.2.1 packages shipped in Ubuntu 16.04.  It looks like all the big distros who ship a recent mono have decided to not package the .NET 4 SDK.  We may want to consider removing the `-sdk:4.0` flag from our default (non-travis) makefile.
