### ISSUE TITLE
Any way to have both fractions videos available? (Red Alert)

### ISSUE THREAD

**Issue by marekjedrzejewski** [OpenRA/OpenRA#10241]
As in topic. I was trying to get it to work with cd isos released on cncnz, or with video files available on PortableRA site.
Tried 'use CD' option, but it doesn't copy video files (and gets stuck on REDALERT.MIX, and I have to change it in content directory to lowercase).
Copying MAIN.MIX (and changing it to lowercase, obiously) does work, but I get videos from only one fraction. Tried naming it main1, main2, but didn't work.
So, after this description, I ask again: any way to have both available at the same time?

**Comment by abcdefg30** [comment]
You can, but you have to extract the mixes from MAIN.MIX of each CD. You want `movies1.mix` from the MAIN.MIX of the allied disk and `movies2.mix` from the MAIN.MIX of the soviet disk.

**Comment by marekjedrzejewski** [comment]
Thanks :)

In case anyone has same problem:
I used XCC Mixer that can be downloaded from here:
http://xhp.xwis.net/utilities/

Works fine with wine.
