### ISSUE TITLE
Add options to re-size the lobby window.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#10253]
I love the functionality of the new lobby window but it's starting to look a bit crowded. It could be nice to have an option to increase the size (Skirmish, Missions, Multiplayer, Settings, everything in Extra) to accommodate additional options into an open and clean design. I'm sure that would be useful for future additions as well.
##

**Comment by PunkPun** [comment]
Is this still relevant?

**Comment by dragunoff** [comment]
> Is this still relevant?

No, I think it's not relevant anymore. It has no context and the UI has probably changed since the issue was created. Also some of the issues with chrome panels and windows sizes were addressed in #19681.
