### ISSUE TITLE
+1 view range for the Allies Light Tank, following the ability to kill off husks in the Ore Refinery

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#10250]
With the ability to destroy husks in front of the harvester dump spot, the light tank will have very few roles left on the battlefield.

+1 view range has been discussed frequently on and off the forums. It would have +1 view range above basic infantry (same as dogs), making it more attractive to use with infantry squads in the early to mid game. Especially when going Radar Dome tech before the service depot. It also will serve as a more useful scout unit all through the game, even late game (probing specific areas).

Regardless, having the same view range for the Light Tank as basic infantry, just doesn't make sense.

*Also, there's been discussions on increasing the ROT +2 (rotation of turret?) for the light tank. That will make it a bit stronger against light vehicles (e.g. flak trucks).

**Comment by cjshmyr** [comment]
:+1: for the vision increase

**Comment by MicroJOo** [comment]
:+1: for the ROT buff

**Comment by r34ch** [comment]
:+1:

If it still needs a buff further down the line I would like to see a damage buff vs `heavy` armour (maybe even in combination with a $100 price drop). Allies don't have any early game hit and run / flanking units so a slight buff could make OT and V2 harassment a viable option.

Although the dog would need fixed first to combat early mass lights / infantry.

**Comment by klaas1** [comment]
Although I do agree that light tanks can use a buff, I do think the Allies are generally better and easier to play than the Soviets in about every gamephase and map. Making the light tank too strong can disrupt the balance further. Maybe the flactruck could also get a vision range increase (it got its attack range nerved anyway, and it already has trouble hunting down hinds late game).

I also think Soviets need something that can provide vision, now that vision got even more important. I think the Hind is just so much easier to use as the Yak for vision, having a unit with a large vision range would be very useful to counter basewalking or chokepoints as a soviet player.

**Comment by MicroJOo** [comment]
@klaas1 : we could get rid of this problem by removing the FlakTruck ... add "Hind" to the Soviets , remove "Hind" from the Allies ... make Longbows allies primary AirUnit ... 

so it would be like the original :)

@ScottNZ , @cjshmyr  ^

**Comment by klaas1** [comment]
@MicroJOo and ignore 6 years of OpenRA testing and balancing? IMHO OpenRA is better than the original in every aspect, so changing things back to the original state will be a downgrade.

Maybe it would be good to rename the Hind, just to stop people from whining it should be a Soviet unit.

**Comment by SoScared** [comment]
Just to be clear, I'd like to see a +1 vision increase for the light tank only AFTER the ore ref husk issue has been dealt with. The tiny vision range is currently the only thing that makes ore-ref blocks manageable for the target player.

I agree with klaas in that making the light tank overall stronger (damage vs heavy armor) might be to strong. I don't want to see Allies balancing favorably against Soviet armor on the battlefield.
