### ISSUE TITLE
Change labels in the game-lobby (chat) - from 'Lobby/Global' to 'Game/Lobby'

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#10254]
As discussed in this forum thread:
http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=293879#293879

This would change the labels 'Lobby' with 'Game' and 'Global' with 'Lobby'. It just feel right since the 'Lobby' is where I go to find me a 'Game'.

**Comment by penev92** [comment]
That might just be me, but those sound more confusing to me.

**Comment by Phrohdoh** [comment]
I personally think `Game` and `Global` would be best.

**Comment by penev92** [comment]
Also we should eventually enable use of the global IRC chat ingame too, so "Lobby" won't work for that. Then it would be truly "Global" :P

**Comment by SoScared** [comment]
@penev I see you point regarding Global IRC chat. @phrodo  'Game' and 'Global' sounds nice  actually.

**Comment by SoScared** [comment]
I'm creating a seperate issue with Phrodos suggestion.
