### ISSUE TITLE
Change of building palette order (cnc)

### ISSUE THREAD

**Issue by Truth99A** [OpenRA/OpenRA#10257]
I already wrote a post on this with images:
http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=19220&postdays=0&postorder=asc&vote=viewresult
basically changing the positions of the buildings so that they follow the technology path (and look better)

i'll post the building palette order here:
NUK2: 80
PYLE/HAND: 30
WEAP/AFLD: 40
HPAD: 50
FIX: 60
- note i did not post the ones that did not need to be changed

**Comment by abcdefg30** [comment]
I think this is a good idea.

**Comment by francisxxx0** [comment]
we need this for c&c... also in red alert!

**Comment by pchote** [comment]
Fixed by #10443.
