### ISSUE TITLE
Move "Other" group in spectator shroud selector to the top

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#10263]
When there are a lot of players, it is necessary to scroll down in the spectator shroud selection list in order to reach "All Players" and "Disable Shroud" options. It would be better if these were listed first.

![shroud_selector](https://cloud.githubusercontent.com/assets/6599106/11964376/ee8a94bc-a8f5-11e5-91e9-cc07c6bfb3d4.png)

**Comment by pchote** [comment]
Sounds reasonable to me.
