### ISSUE TITLE
please make the map editor more user friendly

### ISSUE THREAD

**Issue by francisxxx0** [OpenRA/OpenRA#10262]
Hey, it would be awsome if you could add some bigger brushes for water and terrain. Its so anoing to paint with 1x1

**Comment by x-a-n-a-x** [comment]
Hi francisxxx0. See https://github.com/OpenRA/OpenRA/issues/5164

**Comment by pchote** [comment]
Thanks for the report.  This is a duplicate of #9935, so i'll close this one.
