### ISSUE TITLE
Global chat not working

### ISSUE THREAD

**Issue by hacikenks** [OpenRA/OpenRA#10277]
The global chat feature does not work on my computer. It says that I am connected to the irc channel but i cannot type or see anything. Also it logs out of the chat every 2 minutes.
##

**Comment by Mailaender** [comment]
Sounds like a personal firewall issue. You are on a Windows machine? What does irc.log tell you?

**Comment by hacikenks** [comment]
I use WIndows 8. I turned off the Windows firewall but the problem persists. It says "Connecting to irc.openra.net:6667 ..." and  the next line says: "Connected.". Then it goes back to the global chat log in window.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/wiki/FAQ#my-game-just-crashed will tell you the location of the `irc.log` file I mentioned.

**Comment by pchote** [comment]
The global chat feature has been removed.
