### ISSUE TITLE
Captured vehicles (mechanic) are not grouped together with the ones that you build

### ISSUE THREAD

**Issue by hacikenks** [OpenRA/OpenRA#10275]
The same might be true for the hijacked vehicles. I have not checked it.
##

**Comment by hacikenks** [comment]
Could this be because soviet and allied tanks are actually different?

**Comment by anjew175** [comment]
I have seen this problem in relation to engineer captured husks in TD. It was evident on the original Top Control minigame map. It either classed the tank as an enemy (because the rounds would not end with captured vehicles) or made it an entirely new class.

**Comment by FrameLimiter** [comment]
This is no longer an issue and can be closed.
