### ISSUE TITLE
Main menu not showing up

### ISSUE THREAD

**Issue by XenGi** [OpenRA/OpenRA#10282]
When I open the game the loading screen comes up. Then I here the sounds of the main menu and it seems that I can click on menu items because I can here the sounds but the menu screen doesn't show up and I'm stuck in the loading screen.

Tried with version 20151224 and with the current bleed branch (commit 7335c4a8ce47c1b50eb844423d117c3be4cf8caf).

OS is Archlinux, Kernel 4.3.3, Intel grafics.

`debug.log` has 15000 entries of `Could not find collection 'dialog'`. All other logs are empty or contain normal stuff.

**Comment by pchote** [comment]
It sounds like you are missing the artwork for rendering the ui (which is in the dialog.png file). Not sure how this could happen - have you done anything unusual with your install?

**Comment by XenGi** [comment]
just installed the package from my distro. I'll try reinstall it. Where is this file normally located?

**Comment by obrakmann** [comment]
If you mean what I think you mean, then I get the same issue occasionally (Ubuntu, but also Intel gfx here). Does the menu appear when you move the window around a few pixels by grabbing the title bar? If so, retrying it a few times eventually makes it work, a reboot will fix it for sure (until the next time).

As far as I can see, it's not OpenRA's fault, since I have the same problem with Gimp, of all things.

**Comment by XenGi** [comment]
@obrakmann How do I start openra in windowed mode?

I have no problems with gimp.

**Comment by obrakmann** [comment]
Settings -> Display -> Mode: Windowed, and then enter the size of the window.

**Comment by XenGi** [comment]
I can't access the menu. Can I set this in a config file?

**Comment by obrakmann** [comment]
Sure, see here https://github.com/OpenRA/OpenRA/wiki/Settings.

**Comment by XenGi** [comment]
Starting in windowed mode several times and moving the window around doesn't change anything. Trying the same with the bleed branch now.

**Comment by RoosterDragon** [comment]
I can confirm plenty of `Could not find collection 'dialog'` on bleed here (in the modchooser) so we should probably fix the root cause of that either way.

Not sure if that will fix the issue you're seeing with no main menu though.

**Comment by Mailaender** [comment]
This should work fine with Intel graphics (which hardware exactly). I feel this is a graphics driver related problem. Maybe textures aren't loaded? A regression introduced by https://github.com/OpenRA/OpenRA/pull/8387#issuecomment-119801214? I don't know. @chrisforbes to the help.

**Comment by r34ch** [comment]
Not to sound patronising but did you run `make`? I forgot to run it switching branches and got an interesting 'blurred' background with no menu.

**Comment by XenGi** [comment]
I'm using a Thinkpad X250 (Intel HD5500, driver version 2.99.917+519+g822939)

I ran `make dependencies` and then `make all` like it said in the `INSTALL.md`. No errors while compiling.
