### ISSUE TITLE
Balanced 1v1 maps in the offical pool

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#10298]
In the RA1 mod particularly, we ship many 1v1 maps that I feel are not balanced. Although competitive maps are trickling into the resource centre and are slowly being added to the official pool, we have had a number of competitive tournaments where official maps have been used.

I think we should update some of the more unbalanced maps to match our current drive of unit balancing. At the same time, I think we should also increase the aesthetics of the much older maps.

I am _not_ suggesting that maps should be redone to be perfectly symmetrical or such. I do feel however that oRA's gameplay has evolved over time to provide some unique gameplay mechanics and quirks that now cause issues on some maps.

-Base walking to initial ore patches within CY build radius
-Ore mine distance to REFs, accounting for northern REF disadvantage
-Distances to expansions, attack range distances and tech buildings

I will be creating some PR's to show off some changes I am proposing to remedy this. This is more of an announcement to get peoples thoughts on the idea. 

As always suggestions are welcome. And testing.

- [x] Add various community maps #10320
- [x] Singles #10301
- [x] Man to Man #10312 
- [x] Kotg 2 #10347

**Comment by klaas1** [comment]
I agree, in SoScared tournament we've seen some really nice maps, and I'm glad that two of them made it to the official map pool. But also to me the whole official map pool feels a bit cluttered. I'd say that the official maps should be:

1) Balanced (although this does not mean symetric per se)
2) Aestehic
3) Showcasing all the tilesets
4) Include both small and big maps, and some maps with naval warfare
5) Not include near duplicates, nor have to many maps

**Comment by r34ch** [comment]
I would like to add a couple more 1v1 community maps over time (especially some naval ones) but for now we should have enough competitive official maps in the 1v1 pool for variation in future tourneys.
