### ISSUE TITLE
Chronotanks cannot directly chronoshift onto infantry

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#10293]
On bleed. Holding shift to chronoshift onto infantry with chronotanks turns the chrono cursor into the attack cursor.
##

**Comment by Phrohdoh** [comment]
Is this a bug?
Why would they be able to?

**Comment by r34ch** [comment]
Oh maybe this is just my poor memory. 

I thought I remembered chronotanks being able to chronoshift onto infantry because they were crushable. Maybe I'm just thinking of the chronosphere

**Comment by pchote** [comment]
They should be able to, yes.

**Comment by r34ch** [comment]
They can chronoshift onto infantry if you click on an area in the cell not occupied by infantry.

Maybe i'm not remembering correctly but I thought that previously if you had the shift button held, no matter what you moused over the chronotanks would chrono to that cell as closely as possible - even if that cell is occupied. It seems the attack cursor is overriding this.

**Comment by pchote** [comment]
It is a function of the force move modifier, which is normally Alt.  IIRC a special case hack was added only for chronotanks to also make it work for shift, because apparently this use case is much more important than the general force move :s

**Comment by AndriiYukhymchak** [comment]
this is fixed in release and bleed
