### ISSUE TITLE
Standardising tiles across theatres

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#10306]
So I learned today that (for the RA mod at least, and between snow and temperate) changing the theatre manually in the yaml within the oramap will do a very good job of converting all the tiles and actors to the correct theatre. Missing tiles are simply rendered as black squares.

I am planning to add some of these missing tiles with their equivalents from other theatres (where appropriate). The tiles that need new/adjusted artwork I was thinking of duplicating with a similar existing tile already in that tileset. This would allow artistic contributors to change the artwork in future while keeping yaml code changes to a minimum (if any).

In the long term though, I _think_ this could evolve into a theatre selection option in the map lobby. Perhaps with a random default setting. Throw in a small chance to have the new weather effects play for each theatre and you have a way to make all maps seem a little different each time.

Is this actually realistic though?

**Comment by GraionDilach** [comment]
This won't work well with TS and RA2. Their terrains are completely different in too many levels - their respective map editors used look-up tables to convert between theaters and even then messed up stuff badly.

**Comment by r34ch** [comment]
Closing as not currently realistic

**Comment by ShadowA** [comment]
What about between TD and RA ? 

I just discovered TD mod has a lot of nice maps (team maps especially), those maps would be interesting for RA.

**Comment by penev92** [comment]
Not even between those, as far as I'm aware.

**Comment by ShadowA** [comment]
@penev92 Oh ok ... 
Thanks for the answer !
