### ISSUE TITLE
Missiles often crash prematurely

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#10305]
When shooting north (facing 0), missiles quite often make a sharp curve to the right and explode, sometimes several cells before the target. Other directions don't seem to be affected.

Introduced by #8717 or one of its follow-ups (#9646, #9746).

**Comment by reaperrr** [comment]
@matija-hustic, could you help tracking down and fixing this?

**Comment by matija-hustic** [comment]
I'm looking at this. I've got a new version of missile. I just want to polish it and I'll PR it. Probably also discuss in IRC beforehand

**Comment by pchote** [comment]
@matija-hustic do you have any progress to show here?  We've passed the feature freeze point now, so we'll probably need to fix rather than replace the missiles.

**Comment by GraionDilach** [comment]
https://github.com/matija-hustic/OpenRA/tree/missile_followup - although at first glampse, it probably will not hit the release.

**Comment by pchote** [comment]
This is caused by the following line in `HomingTick`:
```csharp
if (allowPassBy && System.Math.Abs(desiredHFacing - hFacing) >= System.Math.Abs(desiredHFacing + 128 - hFacing))
```

Taking facing differences without accounting for the 255 &rarr; 0 wrap-around is bogus.  When moving north the (totally expected) facing jitter can trigger this wraparound case, which makes the missile think it has passed the target.

**Comment by reaperrr** [comment]
North is mostly fixed, but other directions got much worse. Reopening.

**Comment by Phrohdoh** [comment]
That sounds like we want to revert that PR then.

**Comment by reaperrr** [comment]
@Phrohdoh not yet, @pchote proposed a possible fix on IRC.

**Comment by pchote** [comment]
#11170 hopefully closes this for good.
