### ISSUE TITLE
gdi guard tower needs com center, nod oby of light needs temple of nod????

### ISSUE THREAD

**Issue by Truth99A** [OpenRA/OpenRA#10318]
the oby of light is almost unused and to add to the pain the oby of light required the temple of nod while the guard tower for gdi only requires the comm centre

**Comment by anjew175** [comment]
That isn't really the problem since the obelisk is much better than an AGT. It can destroy an AGT while taking little damage. Obelisks also 1hit kill light tanks. The main problem is how slow they are to fire and how much power they take up.

**Comment by Truth99A** [comment]
hmmmmm true true 150 power and 1500$ :P

**Comment by anjew175** [comment]
I also felt kind of the same way until I realised that the SAM site is available for NoD after constructing a barracks

**Comment by pchote** [comment]
As discussed, there's no problem here so closing.
