### ISSUE TITLE
Extending the lobby

### ISSUE THREAD

**Issue by ephja** [OpenRA/OpenRA#10314]
This doesn't seem possible by way of polymorphism, since nothing related to the lobby relies on either interfaces nor classes with virtual methods. Do you think it would be a good idea to support this?
##

**Comment by pchote** [comment]
Modifying in what way?  There are plans to split out the map options, but most other settings are driven by the mod / map data (factions, bots, etc) or hardcoded at the lowest level of the engine (maps, teams, spawns, etc) and so aren't really available for customization.

**Comment by ephja** [comment]
My original idea was silly, and maybe it should indeed be limited to map options.

**Comment by pchote** [comment]
Map options are now generated dynamically based on the map rules, so closing.
