### ISSUE TITLE
Terrain overlay is broken

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#10311]
The terrain overlay in bleed is broken in funny ways.

git bisect says af344452eaa936187c453510037b3202dafbe0a4 is the first bad commit.

```
commit af344452eaa936187c453510037b3202dafbe0a4
Author: Paul Chote <pchote@users.noreply.github.com>
Date:   Sat Dec 19 22:06:55 2015 +0000

    Convert RgbaColorRenderer to TriangleList.
```

![screenshot from 2015-12-28 15 00 17](https://cloud.githubusercontent.com/assets/4331210/12020300/126c100c-ad7b-11e5-9f3b-c7500022e9bd.png)
##

**Comment by RoosterDragon** [comment]
I can't recreate this on 7cc8846d72a567d8dbce956953fcbf3e310b6f3c. Does it happen every time? Can anbody else recreate this?

**Comment by abcdefg30** [comment]
I can reproduce similiar glitches when scrolling around on latest bleed.

**Comment by pchote** [comment]
I expect this is somewhat driver-dependent.

**Comment by Mailaender** [comment]
Not reproducible on my end.

**Comment by pchote** [comment]
Not reproducible doesn't mean not a bug, especially for low level gpu stuff like this.  Reopening.

**Comment by LipkeGu** [comment]
maybe it is Linux / MacOS related? i tried it on Windows... nothing...

**Comment by derestle-htwg** [comment]
Maybe somebody who is affected can give details?
OS?
Driver version?
GPU?

**Comment by obrakmann** [comment]
FWIW, I don't get this anymore
