### ISSUE TITLE
Spy into building veterancy upgrade applies to crate units.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#10313]
Or maybe I'm crazy, someone confirm?

**Comment by abcdefg30** [comment]
I think so too, but I'm not sure if we should consider this a bug.

**Comment by MustaphaTR** [comment]
Spies effect crates in RA2/YR too. That shouldn't be a bug.

**Comment by abcdefg30** [comment]
Closing here then, as people on IRC think this is rather a feature, too.
