### ISSUE TITLE
Add `LC_ALL=en_EN openra` to linux launchers

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#10332]
This works around mono choking on non-english locales.

**Comment by Mailaender** [comment]
I think setting `ZipConstants.DefaultCodePage` everywhere would be the correct solution.

**Comment by obrakmann** [comment]
FWIW, `ZipConstants.DefaultCodePage` is 437 on my system, `Encoding.Default.CodePage` is 65001 (which is UTF-8 according to [this](https://msdn.microsoft.com/en-us/library/windows/desktop/dd317756%28v=vs.85%29.aspx))

**Comment by pchote** [comment]
@obrakmann try changing your `LC_CTYPE` environment var to something else: I bet that will change.

**Comment by obrakmann** [comment]
Yep. It's 20127 (`us-ascii`) when `LC_CTYPE` is `C` (the only non-UTF8 locale I have installed).

**Comment by Mailaender** [comment]
On my system `ZipConstants.DefaultCodePage` is 850.
