### ISSUE TITLE
Crash when trying save a map in the editor after manually editing the map.yaml

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#10339]
On bleed

I am trying to reduce the size of some maps due to the boundaries being in weird places. I manually edit the boundaries to nearly match the overall map size, then use the copy paste tool to move the entire map to the correct position. The game then throws an exception when I try and save.

http://pastebin.com/znKCYkBf

The error happens in `SaveMapLogic.cs` line `141`

    var combinedPath = Platform.ResolvePath(Path.Combine(directoryDropdown.Text, filename.Text + fileTypes[typeDropdown.Text]));

http://i.imgur.com/SGrmTWo.png

**Comment by Phrohdoh** [comment]
Your link is just to pastebin.com, not a paste you created there.

**Comment by obrakmann** [comment]
Can you please show us what your save dialog looks like right before you click on save? Or, even better since you seem to know how to use monodevelop, can you put a breakpoint on that line 141 and tell us what the value of `typeDropdown.Text` is when you hit it?

**Comment by r34ch** [comment]
@obrakmann `".oramap_FILES"`

**Comment by r34ch** [comment]
Ok, so I extracted the files from the .oramap and did the edits manually. 

When I saved using the default settings '.oramap_FILES', it crashes. When I click on the dropbox to choose different options I only see `oramap` and `(unpacked)`, which then work just fine.
