### ISSUE TITLE
Delayed unit order execution

### ISSUE THREAD

**Issue by ephja** [OpenRA/OpenRA#10341]
There's a delay between giving a unit an order and the order being executed. Even in singleplayer games. Why is that?

**Comment by obrakmann** [comment]
The idea is to prevent the pathfinder from being flooded with requests when a bunch of units all receive move orders at once. So a little (random) delay is inserted before the pathfinder is queried.

See also #3288.

**Comment by ephja** [comment]
Got it. Thanks.
