### ISSUE TITLE
Footprint HitShape

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#10349]
For buildings in isometric perspective:

> [22:53:09]    pchote reaperrr: footprint is the way to go in any case
> [22:53:36]  pchote not hard to add
> [22:53:44]  pchote its just the superposition of a bunch of rectangles
> [22:53:51]  pchote the outer radius is the radius of the bounding rect
> [22:54:01]  pchote the falloff distance is the minimum distance from each of the rects
> [22:54:27]  pchote then divide it into N rects based on rows
> [22:54:33]  pchote merging adjacent rows of the same size 
##

**Comment by pchote** [comment]
The rest:
```
22:54 <+pchote> then divide it into N rects based on rows
22:54 <+pchote> merging adjacent rows of the same size
22:55 <+pchote> and then for each rect take the corners and transform to world coords
```

Note that this works for both isometric and classic perspective (and also auto-calculates the sizes and accounts for weird footprint shapes).

**Comment by pchote** [comment]
Alternatively we could add an arbitrary polygon shape and then trace out each footprint by hand.

**Comment by Phrohdoh** [comment]
:+1: for defining splines/verts.

**Comment by reaperrr** [comment]
A dedicated Footprint HitShape will effectively become unnecessary once the updated version of #13314 is merged.
