### ISSUE TITLE
Add documentation how to set up a RasPi dedicated 

### ISSUE THREAD

**Issue by MicroJOo** [OpenRA/OpenRA#10356]
https://github.com/OpenRA/OpenRA/wiki/Dedicated

im looking for a easy  "step for step" tutorial ... with all the dependencies (+ commands) i'll need 
what do i need to run a dedicated-openra-server on a raspberry pi ?

ive seen @Zogg managed to run one

**Comment by Zogg** [comment]
https://github.com/OpenRA/OpenRA-Resources/wiki/OpenRA-on-RaspberryPi feel free to add your corrections. ;)

**Comment by ScottNZ** [comment]
@Zogg This page should go on https://github.com/OpenRA/OpenRA/wiki. OpenRA-Resources is for the resources website.

**Comment by Zogg** [comment]
Fixed.

**Comment by MicroJOo** [comment]
@Zogg : im having kinda troubles getting libsdl2-2.0 ... 

Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package libsdl2-2.0
E: Couldn't find any package by regex 'libsdl2-2.0'

**Comment by Zogg** [comment]
pi@raspberrypi:~ $ cat /etc/issue
    Raspbian GNU/Linux 8 \n \l

    pi@raspberrypi:~ $ apt-cache search libsdl2-2.0
    libsdl2-2.0-0 - Simple DirectMedia Layer


The instructions are for latest and greatest raspbian. Which version are you using?

**Comment by MicroJOo** [comment]
about to update and then repeat the procedure according to your documentation ... ill give an update later

**Comment by MicroJOo** [comment]
everything works now ... except , when i start the dedicated .sh ... it tells me : 

Warning: Server ports are not forwarded.
Game has not been advertised online.

i did edit the server to "port forward: true" ... and i can run a dedicated perfectly on my windows machine , so its not the fault of my router-settings

**Comment by MicroJOo** [comment]
@Zogg : is your pi hanging on a network cable ... or do you use a wlan stick ?

**Comment by Mailaender** [comment]
> https://github.com/OpenRA/OpenRA/wiki/OpenRA-on-RaspberryPi

Thanks.

**Comment by Zogg** [comment]
@MicroJOo It is on the cable. I have forwarded network port on the router, and left "port forward" option as `false`.

**Comment by Zogg** [comment]
Welcome to the 2016!!!

**Comment by MicroJOo** [comment]
@Zogg : thx , you helped a lot ! 

ive added some last important information on the page (first steps , port forwarding) 
you can jump into irc - freenode - #openra if you need any help with OpenRA :)

thx again !

**Comment by Zogg** [comment]
Your welcome! Allright! :)
