### ISSUE TITLE
hijacker can be run over

### ISSUE THREAD

**Issue by Truth99A** [OpenRA/OpenRA#10351]
i tried capturing a harvester with a hijacker, it got run over XD
p.s just a thing i've been wondering: how do we add labels to issues?
##

**Comment by Phrohdoh** [comment]
That is correct.
https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/rules/infantry.yaml#L456

**Comment by Truth99A** [comment]
shouldn't it be impossible to run over them... because you know? they run directly at the vechicle and their sole perpose is to get as close as possible (to the point where they are on the same square) and capture the vechicle
+ able to run over them makes them even weaker because if they get unlucky and are facing the wrong side of the vehicle when trying to capture it they die! O_o

**Comment by Phrohdoh** [comment]
I do not think they should have a 100% success rate for stealing a vehicle.

**Comment by Truth99A** [comment]
but they cost $500 and they die so easily, trying to even get them close to enemy vechicles is a challange let alone trying to get them next to a harvester only to have them die by chance :P

**Comment by Phrohdoh** [comment]
That is part of a strategy game.
Spies also inherently require some work from the player.

**Comment by Truth99A** [comment]
spys are 100% to get into the enemy building and are able to disguise themselves, they are more used because they are actually effective where as hijacker be like:
[url=https://imgflip.com/gif/wlqou][img]https://i.imgflip.com/wlqou.gif[/img][/url][url=https://imgflip.com/gifgenerator]via Imgflip GIF Maker[/url]
no joking that was me sending it after a vehicle, it ran past it a couple of times and even disappeared and re-appeared on another square (i think thats a bug) and then got squished....

**Comment by penev92** [comment]
Yes, it can be annoying, but making it too easy isn't fun either.
On the other hand, I have personally seen good players use them to great effect (before the latest buffs!), so I guess it is possible with some training (and that's the fun part ;) ).

**Comment by pchote** [comment]
Related to #9879.  We plan on making hijackers (and other actors that enter actors) more effective by having them complete their task when they move inside the target health bounds instead of requiring them to move exactly to their center position.

**Comment by matjaeck** [comment]
Fixed by https://github.com/OpenRA/OpenRA/pull/15661#issuecomment-427656171?
