### ISSUE TITLE
Fake structures revealed by spies

### ISSUE THREAD

**Issue by leodew** [OpenRA/OpenRA#10355]
Hello everyone :) 

I just tested out (release 151224) : spies can't infiltrate fake structures (WF, Radar, Navy), so they can easily identify them.

I think ScottNZ talked about it here : https://www.bountysource.com/issues/7983378-add-more-fake-buildings

I think it would make the french faction even more interesting if Fake buildings could be infiltrable, without giving the veterancy (or reveal for Radar) as supposed . 

Is this behaviour planned for future releases ? 

Thank you all ! :)

**Comment by penev92** [comment]
Best case - infiltrate and exit immediately with no effect, since it's a fake structure.

**Comment by leodew** [comment]
imho I'd say infiltrate and not exit (like being killed by a trap or by awaiting soldiers ^_^) (just like a normal building, spies don't exit it after stealing top secret documents ... :) ).  

Otherwise with 1 spy you could check all the buildings, thus rendering this feature useless.

**Comment by pchote** [comment]
IMO the most logical behaviour is for the spy to be consumed, and the 'fake' tag being revealed to the infiltrator.

**Comment by MustaphaTR** [comment]
I agree with @pchote. That's also the behavior in orginal game.

**Comment by leodew** [comment]
+1 Agree

**Comment by r34ch** [comment]
+1 @pchote's idea. 

Consuming spies via fake structures would add another defensive element to France.
