### ISSUE TITLE
Suggestion : Restarting GPS Satellite when destroyed

### ISSUE THREAD

**Issue by leodew** [OpenRA/OpenRA#10359]
Hi :) 
Related to #9962 (Suggestion: Hide GPS icons when player has low power)

IIRC I think GPS is the only ability which doesn't get restarted after being destroyed and rebuilt, unlike other special abilities / superweapons. 

Maybe restarting the whole 10 min is too much ... but actually same happens with an Abomb if gets destroyed  :)

Maybe a reset for a few mins (5 min ?) could be a middle ground ? 

Thoughts ? :)
##

**Comment by atlimit8** [comment]
First of all, the satellite is only launched once.

You could try moving time from `ChargeTime` to `RevealDelay` to represent a longer connection initialization time.

**Comment by abcdefg30** [comment]
> You could try moving time from  ChargeTime  to  RevealDelay  to represent a longer connection initialization time.

`RevealDelay` isn't shown anywhere in the UI (timers) IIRC, so increasing that might confuse players (the timer is over, but I still don't have an active GPS????).

**Comment by atlimit8** [comment]
There probably should be some kind of secondary or combined timer anyways since the GPS superpower is not available the moment the current timer reaches 0:00.

**Comment by abcdefg30** [comment]
Balance has changed a lot since 2015, so I don't see this happening. (Also see #17269.)
