### ISSUE TITLE
Can't shoot at units frozen under fog

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#10361]
![image](https://cloud.githubusercontent.com/assets/756669/12070549/d6503a4a-b07b-11e5-8ae0-0b809c4bbeba.png)

Found out about it while testing https://github.com/OpenRA/OpenRA/pull/9452, but it is already in `bleed` so it didn't regress there, but before.

**Comment by obrakmann** [comment]
It seems to only affect turreted units, so that narrows is down some.

**Comment by obrakmann** [comment]
git bisect points to d235ea3a52bd2bb5492259074d5aacfd9550bc7b
```
commit d235ea3a52bd2bb5492259074d5aacfd9550bc7b
Author: Pavel Penev <penev92@gmail.com>
Date:   Sun Nov 15 16:07:22 2015 +0200

    Don't attack actors that you can't see
```

**Comment by obrakmann** [comment]
OK, [this is what I've got now](https://github.com/OpenRA/OpenRA/compare/bleed...obrakmann:fix10361_frozen-actor-targeting). I'm pretty sure that that approach is too simplistic and would just result in gazillioin cases of 'Attempted to get trait from destroyed object', though.

**Comment by Mailaender** [comment]
I propose https://github.com/OpenRA/OpenRA/issues/10420 so we get a stable bleed until this has been resolved in a large scale.

**Comment by obrakmann** [comment]
Yeah, I agree by now. I tried two different approaches to fix this properly, but ran into roadblocks with both of them.
