### ISSUE TITLE
Add additional admin options to players in the lobby

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#10379]
Suggested at www.sleipnirstuff.com/forum/viewtopic.php?t=19306.

We can replace the current kick button with a dropdown with additional options:
- Transfer admin: This would allow an admin to pass control over to another specific player without having to do the quit-rejoin dance that is currently required.
- Move to spectator: This is a less harsh alternative to kicking an idle player, and is a problem that comes up fairly often in streamed games.
##

**Comment by pchote** [comment]
This will be included as part of the UI tweaks in #2265.

**Comment by Micr0Bit** [comment]
#12873

**Comment by Aaron-Lloyd** [comment]
@pchote I believe this can be closed now in light of #15307 . 😄
