### ISSUE TITLE
MAD tank needs buff

### ISSUE THREAD

**Issue by Truth99A** [OpenRA/OpenRA#10389]
not sure how to get gifs working on github but i got one working on the forum:
http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=294107#294107

the MAD tank at the moment is pretty much a really bad version of the demo truck with very small damage, takes it time detonating and is very slow
##

**Comment by ShadowA** [comment]
True that his damage is lower, but on the other hand you can Chrono / Iron Curtain it, whereas demo trucks can't be.

**Comment by ShadowA** [comment]
But i agree that damage is too low ... to destroy an IC / Abomb for instance, you need 3 MAD tanks !

**Comment by pchote** [comment]
> to destroy an IC / Abomb for instance, you need 3 MAD tanks !

This is the point!  MAD tanks apply a percentage damage, not an absolute damage.  1 MAD tank will *always* do 33% damage, and 3 MAD tanks going off at the same time will kill *anything* (that they can target).

**Comment by ShadowA** [comment]
Oh I see, didn't know that ... thnaks for info :)

I think it is the only unit which works like that, isn't ? 

And if so, why this special behaviour ? Was is like that in original RA ?

**Comment by ShadowA** [comment]
I think this info might be unknown for many people, could be written in the description of the unit :) 

Also, maybe buffing it to 50% could be better ? Building 3 MAD tanks will be too much time / money consuming comparing to a Demo truck, maybe 2 MAD would make it a more useful unit.

On the other hand, I'd understand that it would become an OP unit, coupled with IC or chrono. But still 3 MAD tanks is too much IMO ^_^

**Comment by GraionDilach** [comment]
Yes, this is how it worked in orig RA.

**Comment by abcdefg30** [comment]
This ticket is now quite old and balance has changed since. If this is still an issue it should be discussed on the forums or Discord.
