### ISSUE TITLE
Map suddently becomes completely unrevealed for one player

### ISSUE THREAD

**Issue by mmmh81** [OpenRA/OpenRA#10398]
About 25 minutes into one game (about 83/84% in the replay), the map suddenly became completely unrevealed again for one player (not for the other one):
![map_midgame](https://cloud.githubusercontent.com/assets/12261410/12079618/25c1aa44-b240-11e5-99c3-619c3b7057f8.png)
![map_lategame](https://cloud.githubusercontent.com/assets/12261410/12079619/27129cfa-b240-11e5-91ba-dcb0d9fd90a9.png)

The white patch in the upper left corner is due to https://github.com/OpenRA/OpenRA/issues/10396
This is the replay of the game: [OpenRA-2016-01-03T153137Z.zip](https://github.com/OpenRA/OpenRA/files/76654/OpenRA-2016-01-03T153137Z.zip)

**Comment by pchote** [comment]
They probably found a "reveal map" crate.

**Comment by mmmh81** [comment]
Sorry for the to and fro editing, I was confused myself.

The "reveal map" crate should reveal the map for them, but not unreveal them for other players. Or am I misunderstanding something?

**Comment by pchote** [comment]
Infiltrating an enemy radar dome with a spy will reveal what the enemy can see to the infiltrator, as well as resetting the enemy shroud.

**Comment by mmmh81** [comment]
Thanks, I did not know that infiltration also resets enemy shroud. I checked the replay again and did not see any spy, tough.

**Comment by pchote** [comment]
The replay shows that your flak truck triggers a hide-map crate inside your base, which resets your shroud.  No bug here!
