### ISSUE TITLE
Global chat can crash the game when the player is ingame

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#10395]
I started a singleplayer game, which crashed immediately upon start with an NRE [here](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Widgets/ScrollPanelWidget.cs#L382). `makeWidget` was null, presumably because there is no UI for the global chat ingame.
The calling method was [this](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Widgets/ScrollPanelWidget.cs#L377).
`item` was `[13:05:06] *** SharpTeeth has quit IRC`.

**Comment by pchote** [comment]
`makeWidget` is explicitly set to null when the widgets are unbound.  Adding an `if (makeWidget == null) return;` will fix this.
