### ISSUE TITLE
Invisible and non-targetable flame turret on Monster Tank Madness

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#10403]
The turret is in the middle of the three tanks, and you can see the fireball that it has just shot at the tank on the left:

![screen shot 2016-01-03 at 17 47 01](https://cloud.githubusercontent.com/assets/167819/12079929/59e6cd7a-b242-11e5-9266-517ba177138c.png)

It cannot be seen or manually targeted, but units will autotarget it.

Replay: https://www.dropbox.com/s/9c5sc9aehk3b10x/OpenRA-2016-01-03T174451Z.orarep?dl=0

**Comment by abcdefg30** [comment]
This is a general problem, I just didn't get to open an issue yet (also I couldn't compile latest bleed).
I found this bug also in skirmishes:
My view:
![invisiblesam](https://cloud.githubusercontent.com/assets/7704140/12081002/16c6135e-b26d-11e5-86c3-8e9ba45b48f5.png)
Shroud disabled:
![invisiblesamb](https://cloud.githubusercontent.com/assets/7704140/12081003/17620926-b26d-11e5-8ffc-27113b4d76b2.png)

You can also see this good with the fences of the first soviet base in allies05a (some of the fences are invisible). Using /visibility will hide the issue.

**Comment by pchote** [comment]
Is this reproducible on the release?

**Comment by RoosterDragon** [comment]
Regression from #10256.

**Comment by Mailaender** [comment]
I probably should stop testing everything with `/all` developer cheats.
