### ISSUE TITLE
Manual powering down is inconsistent in D2K

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#10402]
Only four arbitrary buildings can be powered down: outpost and palace (but none of the other tech structures), starport (but none of the other production structures), and the missile turret (but not the gun turret).

We should either fix it properly (by defining and then implementing consistent rules for what can and can't be disabled) or (preferrably IMO) remove it completely.

**Comment by MustaphaTR** [comment]
I don't see too much problem with curret behavior but it would be better if power requirement (not sure is it already removed in orginality changes) and ability to toggle power it. Palaces has Support Powers, Outpost Provides radar. Missile Turret requires Power to Operate, gun turret doesn't.

Just remove it from startport, rest looks good for me.

**Comment by elena-v2** [comment]
Regarding my PR, I personally support removing manual power toggles completely from D2k, but I figured that fixing the most egregious offender is a good first step before any further decisions are made regarding that situation.

**Comment by MustaphaTR** [comment]
I would call this done. I still think Palace (provides superweapons), Outpost (provides radar) and Rocket Turret (Requires Power) being able to powered down is good.

**Comment by abcdefg30** [comment]
> I would call this done

Closing then.
