### ISSUE TITLE
Pinwheel of death on OS X El Capitan

### ISSUE THREAD

**Issue by nodesocket** [OpenRA/OpenRA#10408]
Installed the latest version of Mono 4.2 Stable (4.2.1.102) via the universal installer. When I start OpenRA it goes fullscreen, clears the screen, but then the pinwheel of death starts. I have to force quit OpenRA.

Running OS X El Capitan 10.11.3 Beta (15D9c).

Unfortunately, all of the OpenRA logs are empty:

````
➜  Logs  ll
total 0
-rw-r--r--+ 1 justin  staff     0B Jan  3 13:38 debug.log
-rw-r--r--+ 1 justin  staff     0B Jan  3 13:38 geoip.log
-rw-r--r--+ 1 justin  staff     0B Jan  3 13:38 graphics.log
-rw-r--r--+ 1 justin  staff     0B Jan  3 13:38 irc.log
-rw-r--r--+ 1 justin  staff     0B Jan  3 13:38 perf.log
-rw-r--r--+ 1 justin  staff     0B Jan  3 13:38 server.log
-rw-r--r--+ 1 justin  staff     0B Jan  3 13:38 sound.log
-rw-r--r--+ 1 justin  staff     0B Jan  3 13:38 syncreport.log
````

**Comment by pchote** [comment]
This is caused by mono insisting on reindexing all the fonts on your system.  Let it run for a few minutes, and OpenRA will then start (this only needs to be done once, until the next time mono decides it needs to reindex them).

**Comment by obrakmann** [comment]
Not sure why this ticket is still open. Thanks @nodesocket for adding that to our FAQ.
