### ISSUE TITLE
Weird Frame per second Issue 

### ISSUE THREAD

**Issue by Stuka88** [OpenRA/OpenRA#10419]
When I start the game it completely freaks out FPS wise. How can I stabilize the frame rate so I'm not seeing all these weird black spots on the screen while the game is trying to put the frames in order? 
##

**Comment by pchote** [comment]
This sounds like it might be caused by buggy GPU drivers - it certainly isn't a common issue.  Can you please give us the details of your system (OS, GPU, driver version, etc)?

**Comment by colonelpopcorn** [comment]
Might be a problem with integrated graphics? I just built it and there's a lot of weird drawing issues (black boxes) on intel integrated graphics.

**Comment by pchote** [comment]
The HD5500 is plenty capable to run OpenRA well.  If you are on Linux then you probably need to upgrade your graphics stack (some distros ship very old and buggy drivers).

**Comment by colonelpopcorn** [comment]
Changed it to windowed and it fixed my issue I'll try putting it back later today to see if the problem persists. I'm on Win7, btw.

**Comment by Stuka88** [comment]
After I reboot it works, but only once. Got Win8.1, intel graphics card but
a 3 month old laptop so that shouldnt be the issue

2016-01-06 14:05 GMT+01:00 Jonathan Ling <notifications@github.com>:

**Comment by penev92** [comment]
Intel HD Graphics are very capable, but their windows drivers are ... not very good.

**Comment by Stuka88** [comment]
so any advice how to fix?

2016-01-06 20:58 GMT+01:00 Pavel Penev <notifications@github.com>:

**Comment by penev92** [comment]
Sorry, no. The best I can give you is "try different driver versions until you find one that isn't *too* bad". I'm on Windows with an Intel HD 3000. I had some issues. Downgrading the drivers reduced the number of issues.

**Comment by obrakmann** [comment]
Since this is almost certainly a driver issue, I don't think we can do much here anymore.
