### ISSUE TITLE
Question : shoot over concrete walls bug ?

### ISSUE THREAD

**Issue by ShadowA** [OpenRA/OpenRA#10413]
Hello !

I have played a game where enemy riflemen could shoot over my concrete walls, when they were exactly behind them. If they are further away, their shots get stopped by the walls, which is the behaviour I'm familiar with. 

Is it a bug or is it intended ?

**Comment by abcdefg30** [comment]
It's a bug. See #5294.
Fortunately this was fixed for the next playtest in #10243.
Thanks for the report though!

**Comment by ShadowA** [comment]
Ok thanks ! :)
