### ISSUE TITLE
tesla tank doesn't auto attack while moving

### ISSUE THREAD

**Issue by Truth99A** [OpenRA/OpenRA#10424]
so it got a buff which allows it to attack while moving but the thing is it doesn't auto attack while moving so you have to click on the enemy and then move and then once that enemy is dead you have to click on another. this is horrible when fighting vs infantry

**Comment by penev92** [comment]
That's how it's supposed to be (it uses AttackOmni, not AttackTurreted), and I'm personally fine with not making it too OP against infantry that you can already kite.

**Comment by GraionDilach** [comment]
No, it uses AttackTurreted with an invisible turret since the last release cycle.

**Comment by Truth99A** [comment]
at the moment, if you want it to attack an army while moving you must first click on the enemy, have it turn towards it and then click where you want to go and have it turn in that direction

**Comment by ShadowA** [comment]
I think it's the same for all units Truth99A (medium tank for instance), not a specific bug. 

Try to use Attack move, then Normal move. The tesla tank will automatically acquire a target with Attack move and stop, then with Normal move go to the direction you want.

**Comment by Truth99A** [comment]
oh yeah alright.
