### ISSUE TITLE
Building with turrets gets broken when attacked before finishing make anim.

### ISSUE THREAD

**Issue by DoGyAUT** [OpenRA/OpenRA#10438]
Building with turrets gets broken when attacked before finishing make anim.

How to reproduce:
- Build a defense with a turret.
- While it's displaying the make anim, attack it.
- Building should now not have a turret at all, makeing it not able to attack or beeing sold.
- In some rare cases the turret gets displayed but then shares the same problems as the one without displayed turrets.
##

**Comment by Unit158** [comment]
This is a regression.
