### ISSUE TITLE
dogs bug

### ISSUE THREAD

**Issue by Truth99A** [OpenRA/OpenRA#10431]
1 dog < 1 rilfeman
$200 > $100
+ mass dog < mass of riflemen

dog has its perks (moves faster, detects spies) but there is a problem with the way in which it attacks where it doesn't attack instantly but instead moves a couple squares then attacks which is horrible because with how low its health is when it is up against most other units it dies before ever attacking.
this is even worse when doing an attack move moves

**Comment by GraionDilach** [comment]
Dogs are bugged, yes. However the bug the dogs have atm works for their benefits: `AttackJump` ignores `ReloadDelay`. So if a dog reaches a mass of infantry, then it can do a chainjump with killing an inf each frame pretty much.

**Comment by penev92** [comment]
We have a generic "dogs are bugged" ticket, which covers this. We also closed a bunch of other dog bug issues.
