### ISSUE TITLE
(When using dual monitors?) Print screen shows an old version of the openRA window.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#10447]
Hit print screen and it will just show the openRA logo/loading screen. Sometimes if you're REALLY lucky it will show you the game lobby!
If you are SUPER lucky and all the planets are aligned! You might actually get a shot of the current game you're playing!

**Comment by pchote** [comment]
This is caused by your graphics card drivers, nothing we can do there.  We added our own screenshot hotkey specifically to avoid issues like this: use ctrl+p instead.
