### ISSUE TITLE
Add support for the OpenGL Shader Language

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#10445]
A nice Feature would be to add support for GLSL in OpenRA. Shader programing gives us and the Modders the ability to "change" many things at based on vertex and fragment shaders for vertexes.

We can change:
* lightining (for Day / night), 
* Color (for Debug overlay)
* shadows, 
* cloaking (alpha) 

based on vertex manipulation and shaders Shaders can be written and modified in textfiles and has to be compiled  at gamestart, they could be passed via mod.yaml ```Shaders:```

what i mean what we could have is like this (example in minecraft)
look at the water and lighting 

http://i1.wp.com/minecraftsix.com/wp-content/uploads/2014/11/shader-mod.jpg

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/tree/bleed/glsl

**Comment by pchote** [comment]
In short: we use shaders for technical features, and all of those effects are already implemented using palette modifiers.  Shader mods like minecraft are fundamentally incompatible with the engine design, so theres nothing more to do here.
