### ISSUE TITLE
Difficulty to reload Hinds / Longbows - Blocking behaviour

### ISSUE THREAD

**Issue by ShadowA** [OpenRA/OpenRA#10448]
(See also #10449)
Hello :)

I think air units behaviour have improved throughout releases, but I still have problems managing Hinds, in order to reload them. 

While Yaks seem to have a good behaviour (i.e. sending a group of 4 Yaks to reload, while having 4 Airstrips works good), Hinds don't, and tend to block each other (i.e. sending a group of 4 Hinds to reload, while having 4 Helipads doesn't work most of the time).

Therefore, I have to send Hinds individually to each Helipad, which is too much time consuming, and makes them harder to use than Yaks (balance problem).

Possible solution : 
Maybe this could be solved by allowing Hinds to pass over / through each other ? 
##

**Comment by ShadowA** [comment]
I tested this again : 
- it seems it works fine, when they are shooting at a target, empty their ammo, then automatically go back to helipads
- however, it doesn't work when i select the whole group, and click on 1 helipad. But doing this for Yaks on 1 airstrip works fine
- it works fine when I click F (deploy button), I just discovered about it

**Comment by Platypants** [comment]
I'd like to add what may be a separate bug. Recently, in a game with about 7 hinds and 3 open helipads, my hinds were only able to use one helipad to reload. With individual hinds selected, the two other open helipads would display a "cannot enter" cursor (a red slashed circle around the green triangles). I had to individually micro each hind to use the single non-bugged helipad, costing me a lot of time.

Will test this out / screenshot if I see it again.

**Comment by pchote** [comment]
This has been addressed in the latest releases.

**Comment by gardolf** [comment]
Related to [#10449](https://github.com/OpenRA/OpenRA/issues/10449)
