### ISSUE TITLE
Camo Pillbox visable under fog of war.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#10446]
1)Get shot at by a enemy Camo Pillbox
2)Move out of view range of it
3)Fog of war regrows before Camo Pillbox cloaks
4)It is now visible just like any other building until you uncover the area again

**Comment by pchote** [comment]
This is working as intended.  The fog of war persists buildings in the last state that you saw them.  The most recent knowledge that you had before the fog covered it was that there was an uncloaked pillbox there, and so an uncloaked pillbox is visible just like any other building until you uncover the area again.
