### ISSUE TITLE
Permanent "Fake" tag for fake buildings

### ISSUE THREAD

**Issue by ShadowA** [OpenRA/OpenRA#10456]
Similar to the "Always show status bars" option, but for Fake buildings.

To keep track of your own buildings / fake buildings, without having to select them.

Also could be used on enemy identified fake buildings, if this #10355 is implemented 

" pchote:  IMO the most logical behaviour is for the spy to be consumed, and the 'fake' tag being revealed to the infiltrator. "
##

**Comment by penev92** [comment]
So not a fan of the "add a checkbox for EVERYTHING" notion.

**Comment by ShadowA** [comment]
Agree @penev92 
Maybe not a checkbox, but applying it by default ? 

IIRC in CnC Generals Fake Buildings were surrounded by a yellow rectangle (http://cnc.wikia.com/wiki/Fake_buildings_(Generals)) 

imo I don't think this would be bad looking or annoying to have the Fake tag by default.

**Comment by penev92** [comment]
It would be shown only to allies (until #10355 is implemented), so I can live with that.

**Comment by GraionDilach** [comment]
Having the `Fake` tag as a `WithDecoration` only visible to owner & allies sound solid IMO.

**Comment by chrisforbes** [comment]
Always on, only to owner & allies sounds good. :+1:
