### ISSUE TITLE
Sending back air units after being reloaded

### ISSUE THREAD

**Issue by ShadowA** [OpenRA/OpenRA#10452]
One more problem with air units :)

I didn't find a way to back air units to a predefined position 
- either a previously targeted building they didn't finish to destroy 
- or to the rally point

(Is there any way ?)

For example, rally point works for the Service Depot, so you don't need to micro a repaired unit. 
I think the same would be useful for air units.

Another reason to fix this : reloaded air units in stand-by block the production. Sending them back automatically to the field could solve the problem.

Micro wouldn't disappear, as you would have to manage your units and their reload cycles, if you have more units than airfields / helipads. 
But it would reduce the annoyances I cited before, and make airforce more comfortable to use.
##

**Comment by abcdefg30** [comment]
Do you mean just planes or helicopters too? I think helicopters go to their rally-point after reloading, at least I saw it some time ago.

**Comment by ShadowA** [comment]
Both. 

Here is a replay trying both situations (shooting a target / emptying ammo), and on both types.
http://s000.tinyupload.com/?file_id=11594505168032214995

**Comment by ShadowA** [comment]
Same also if I use F button to send them to base to reload, they will stay there after reloading.

**Comment by ShadowA** [comment]
Ok so I tested this again ... not sure what's happening ^_^
http://s000.tinyupload.com/?file_id=00162137559507896823

So sometimes it works, sometimes not.
+ Seems to work fine if already empty, acquiring a target, then going to reload and coming back to target.
+ Weird bug sometimes : Hind going back and forth between target and helipad. Happens when having 1 shot left, shooting it, then going back to reload.
