### ISSUE TITLE
British Spy cash trick - Lowering minimum theft to 250$

### ISSUE THREAD

**Issue by ShadowA** [OpenRA/OpenRA#10451]
Hi :) 

When entering a refinery, while enemy not having resources, the British Spy steals 500$, while costing 250$.
Spamming spies next to an enemy ref can get you an instant economy boost, which is not justified IMO for England particularly.

This could be capped to a 250$ theft.

**Comment by Phrohdoh** [comment]
If the spy cost you $250 and you get a maximum of a $250 return there is no incentive / reason to use spies.

If you allow the enemy to produce spies (or anything) next to your refineries you are already defeated.

**Comment by MicroJOo** [comment]
@Phrohdoh : what he means is : 

the normal spy costs 500 ... and will always atleast get its money worth out of a ref (even when the refinery is empty) ... so you will always get atleast 500 out no matter what 

this hasnt been adjusted to the "british" spy .. which is a cheaper version (thats the only advantage) ... but while his costs are 250 ... you will still get "atleast" 500 out of the refinery ... 

so you can basicly create money from nothing with a british spy

**Comment by ShadowA** [comment]
I see your point :) 

However, British spies are still very useful and very cost-effective, and you still might need to spam them, especially for powering down (+ power-down cooldown has been reduced, so you need more spies for a long power down, or for the risk of being spotted and killed). Other Allied factions might think twice before spamming them, as they are more time / cost consuming.

Also, you can get the cash trick by sending an heli transport full of spies, an APC, etc ... not necessarily by base push, and for an instant cash boost (too late for enemy to react)

There is no other faction who can get this cash boost, so I think this might cause a balance problem, especially for late games on low resources maps.

**Comment by ShadowA** [comment]
Yeah exactly @MicroJOo

**Comment by abcdefg30** [comment]
Sorry, but :-1: from me here. I think this should stay as faction special and thus allow "faction special tactics". Also there are a lot of maybe's in the example, your opponent could detect the transport, have a camo pillbox near to the refinery and you still need to block your infantry production queue by producing the spies while your opponent can use that time to get units out (-> this tactic is kind of a risk maybe? For each spy you can get one rocket soldier or two rifle men).

Back to my original argument (the last one isn't too good actually): You should still be able to get kind of an advantage of choosing the British faction, why should you play it if it is the same (even worse, as the other factions have stuff the British doesn't) as other factions?

**Comment by ShadowA** [comment]
Yes I agree with all your points @abcdefg30 

But I think the main problem would occur in a late game, where nobody has access to ore, must manage carefully their last units .. and there UK is the only who can get back a whole army just out of nothing ^_^ (even though I agree it's counterable .. but less when nobody has money to counter)

I mean yeah it could be possible why not ... I used this trick several times ^_^ and Allied factions are good at late game in general.

But it feels more like a hack for me than a trait faction ^_^

**Comment by klaas1** [comment]
In addition, you can use a Ref from a disconnected opponent to create money. 

This won't happen often, and IMHO not really a problem balance wise.

**Comment by ShadowA** [comment]
True @klaas1 
(A disconnected player ruins the game anyway :p )

**Comment by Micr0Bit** [comment]
@abcdefg30
i think you guys dont get the point here ... getting money out of nothing isnt a faction special ... 

the only real "advantage" a "british spy" should ever have ... is , that he is cheaper (and therefor quicker to build) then a normal spy ... 

and this is not a "balance ticket" ... cause  ShadowA  is basicly reporting a bug

**Comment by GraionDilach** [comment]
Does OpenRA Spies still give money to their owner if the target player doesn't have money at all? If no, then I don't see what is a bug here.

If the target player had that $500 the Spy steals, then it's good as-is. But if the infiltrator gets $500 even if the infiltrated only loses say that $150 (s)he had, then that's the bug which needs to be fixed.

I don't see what makes the British Spy special here.

**Comment by Phrohdoh** [comment]
It isn't a bug technically, but maybe it isn't desired.
I have no opinion either way on preventing stealing from an empty storage.

The argument here seems to be "I shouldn't have to defend my refs from spies", which I think is bogus.

**Comment by Micr0Bit** [comment]
theres no problem having him steal money from a empty storage ... but it shouldnt be more the his own value  -> 250 ... while for the normal spy its 500

**Comment by Phrohdoh** [comment]
Okay so the request here is to make (British) spies an unprofitable investment, and instead try to have players use them for sabotage instead of money making?

**Comment by Micr0Bit** [comment]
@Phrohdoh : he does profit ...as long as the player has money , hes gonna steal half of the pot everytime a spy enters ... "but" when there isnt enough money in it , then he will get atleast his own value out .. thats to prevent a wasted spy ... 

please dont make this conversation harder as it allready is

**Comment by ShadowA** [comment]
Yes

**Comment by GraionDilach** [comment]
> "but" when there isnt enough money in it , then he will get atleast his own value out .. thats to prevent a wasted spy

This sounds as a valid issue to me tbh. The infiltrator should accept the risk of gambling with the money infiltration - there shouldn't be a "strict enforced minimum" at all.

**Comment by pchote** [comment]
Removing the minimum return would turn this into an anti-feature – decent players try to maintain a float of less than $1k, so it would almost always be a net loss.

**Comment by ShadowA** [comment]
Yes @pchote IMO we should not remove the minimum return. 
We should only change it to 250$ for British spies who cost 250, and keep it at 500$ for normal spies who cost 500.

For the reason that you cited, and also because you already have the risk of your spy / spies being spotted and killed.

@GraionDilach "No minimum return" could be an option. 
But players will become afraid to use it and lose spies for nothing (especially if they aren't UK and cost 500). Whereas they'll never hesitate to use to power down.

If this is implemented -> #10355 , then France would be the only faction who could deter usage of spies, which would make sense IMO.
