### ISSUE TITLE
Add a way to tag actors via the Lua API

### ISSUE THREAD

**Issue by kyrylo** [OpenRA/OpenRA#10464]
Scenario: I spawn a bunch of crates and do not store them in a variable. Then I use `Map.ActorsInBox` to destroy some actors including these spawned crates. My simplified function:

```lua
function ClearMap()
  local unitsToDestroy =
    Map.ActorsInBox(Map.TopLeft,Map.BottomRight, function(actor)
      return IsHusk(actor) or actor.Owner ~= neutral or actor.HasProperty('Crate')
    end)

  Utils.Do(unitsToDestroy, function(actor)
   -- destroy...
  end)
end
```

As you can see the `actor.HasProperty('Crate')` part is not going to work because there's no such property. It would be rather handy to tag actors, so I could query them directly, without storing them in variables.

**Comment by kyrylo** [comment]
Now I'm not sure it's needed, because I [re]discovered `actor.Type` :(

**Comment by Unit158** [comment]
Set them in the global table.

**Comment by Phrohdoh** [comment]
This seems like a workaround for improper programming (not storing them in variables, but want to access them later).

On the other hand engines such as Unity 3D have a very similar functionality.

**Comment by pchote** [comment]
A simpler method would be to have a `ScriptTags` trait (like our existing `ScriptTriggers`) and a `ScriptTagsProperties : : ScriptActorProperties, Requires<ScriptTagsInfo>` that exposes methods for `AddTag`, `HasTag`, `RemoveTag`.
