### ISSUE TITLE
Menu shown in screenshot even if not used in-game

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#10474]
The image show the menu in the screenshot even if I did not open it in-game. Windows 7 and the "Print Screen" button is pressed and opened in paint.
![menu show in screen capture even if not in-game](https://cloud.githubusercontent.com/assets/7798635/12224510/2abcc782-b7f3-11e5-89ed-f387c9a40ff1.png)

**Comment by Snurre86** [comment]
Other outcomes are completely white or black picture.

**Comment by pchote** [comment]
We can't support the windows "printscreen" feature, because it doesn't work properly with OpenGL in many drivers.  Use our ingame screenshot feature (ctrl + p) instead.

**Comment by Snurre86** [comment]
But can you tell me why the menu show up in the screenshot?

**Comment by pchote** [comment]
The best answer I can give is "because your GPU drivers are being weird".
