### ISSUE TITLE
Long country names will overlap the server status field.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#10473]
I originally decided not to use `WidgetUtils.TruncateText` because I assumed that I had given enough room for all the country names.  The GeoIP country database disagrees.

![screen shot 2016-01-10 at 19 39 36](https://cloud.githubusercontent.com/assets/167819/12223519/fa280c10-b7d1-11e5-8bbe-c4c95a7f230f.png)

**Comment by GraionDilach** [comment]
Wonder how GeoIP has the Former Yugoslavian Republic of Macedonia...
