### ISSUE TITLE
Abort 1v1 games, when opponent crashes at start

### ISSUE THREAD

**Issue by ShadowA** [OpenRA/OpenRA#10485]
I just played a game for 5 mins ... only to realize that I was playing alone, as my opponent crashed at start :) 

The victory menu should be shown and the game stopped.
##

**Comment by ShadowA** [comment]
(He probably dropped because of the map download bug (installed map, then didn't exit / come back))

**Comment by pchote** [comment]
What map download bug is this?

**Comment by ShadowA** [comment]
Recently there have been a bug : 
when you click "Install map" from lobby, tick ready, and game starts, then you get kicked out when the game starts.

You have to install the map, exit the lobby, then enter again, to avoid being kicked. 

I dunno if happens on all maps / everytime, but happening to a lot of players recently.

**Comment by ShadowA** [comment]
I'll open an issue for that.

**Comment by anjew175** [comment]
That particular bug happens to spectators only I am pretty sure.

**Comment by ShadowA** [comment]
@anjew175 I tested this out now, seems you're right, thx for pointing out.

I'm not sure then why he didn't get into the game. Maybe I ticked ready, and he just left the lobby ?

**Comment by Mailaender** [comment]
I think we should leave the choice to the players. Maybe warn a bit louder about this or https://github.com/OpenRA/OpenRA/issues/3001.

**Comment by anjew175** [comment]
Perhaps have a box asking "are you sure you want to play vs no one"

**Comment by abcdefg30** [comment]
Closing as covered by #13725.
