### ISSUE TITLE
Statistics : Army size (number of units)

### ISSUE THREAD

**Issue by ShadowA** [OpenRA/OpenRA#10497]
Currently, I think that currently only the "Assets" information can compare the size of the armies (all mixed)

It would be interesting to know what number of units each player has.

Maybe this could be : 
- further detailed into types of units ? (infantry, vehicles, air, naval + maybe buildings ?) 
- a new 6th tab in the statistics (after "Basics", ...)
##

**Comment by ShadowA** [comment]
Now I'm thinking of, Starcraft 2 even display the detailed units composition.

There might be less different units in Starcraft 2 (?) and also gameplay is different I think ... but still it could help compare army compositions.

**Comment by GraionDilach** [comment]
I'd :-1: this because I'm not sure how this'd look with my planned-to-be-between-150-and-200 unit type amount. (Unless it'd only show existing units and not possible ones, but even then I could pull cases where it would end up running out from the screen with ease.)

**Comment by ShadowA** [comment]
Could it be then a deactivatable tab for a mod ? (are you making a mod or what is it ? :) )
Or maybe it could be cropped, or using a horizontal scroll.

But I don't think it will cause any pbms with original mods, would it ?

**Comment by Micr0Bit** [comment]
http://logs.openra.net/?year=2017&month=01&day=17#14:10:43

**Comment by WolfGaming** [comment]
👍 To anyone who wants to implement this (would if I had the time).

**Comment by rob-v** [comment]
Do you want to add numbers by type (infrantry, vehicles,..) or by Rifle, Rocket... It will be many columns then. I didn't find in OpenRA any horizontal scrollbar, so I am not sure how easy it is to add it. Probably not too difficult. Alternatively we could move Players from rows to columns and add one row for each unit type, building type, metric ....
                                                 Player1         Player2
Rifle created                                 100              50
Rifle killed?                                     20
anything agreed/feasible

What metrics (units created, alive at the end, killed?) we could start with? If agreed what/how to report, I could implement it.

**Comment by Smittytron** [comment]
#15767 gave us the $ value side of this.

**Comment by matjaeck** [comment]
I agree with Graion Dilach that a horizontal list of all units is too much. If there is the need for more detailed information about army composition, I could imagine that a new tab with colums for value/amount of units per production type (inf, veh, air, ship) might work.

**Comment by teinarss** [comment]
This is how it looks in Starcraft 2 and it would work good with the new spec ui.
![army](https://user-images.githubusercontent.com/19173272/59567574-ce64e880-906f-11e9-99ec-c51cd7d5d1d5.png)
