### ISSUE TITLE
Idea : A "keep formation" movement

### ISSUE THREAD

**Issue by ShadowA** [OpenRA/OpenRA#10495]
When a group of units move from A to B, they arrive at B with the same arrangement as they were at A.

This would be useful in cases like : 
- setting a "+" formation of 5 units (point A), sent them to the target (point B) and arriving there with the same "+" formation, then Iron Curtained there.
- keeping long range units behind tank units

They don't need to keep the formation along the path, but only at point B.

**Comment by ShadowA** [comment]
Oh maybe it's this ? Formations [$20] #3880 
Though I'm not sure it's the exact same thing

**Comment by Mailaender** [comment]
Kinda https://github.com/OpenRA/OpenRA/issues/3880#issuecomment-160869166. Let's keep the discussion at one place.
