### ISSUE TITLE
Difficulty to see enemy with GPS Satellite under FoW, if enemy's color is close to terrain's [$10]

### ISSUE THREAD

**Issue by ShadowA** [OpenRA/OpenRA#10504]
When some players choose colors close to terrain's (on temperal maps, dark green, dark blue, ... or even manage to get black with some color trick), it is very hard to see their GPS symbols under the FoW. 

So it can become much easier to sneak attack, which is almost impossible for players who use colors with contrast to terrain.

Not sure what the solution could be. 
- Maybe an equivalent of #9801, but changing the whole color of the enemy team (GPS symbols + maybe units themselves). Not happy with this solution though.
- And further limiting colors might not be an option (#10217)
- Or maybe a white outline on the symbols ? Not liking this too ...

**Comment by pchote** [comment]
The best option is to create new icon artwork that is larger and has a border to match our other overlay icons (repair, powerdown).

**Comment by ShadowA** [comment]
@pchote Nice :+1:

**Comment by riiga** [comment]
I tried doubling the size of the icons and adding a white outline to them, which makes them looks like this (click for full):

![Icon zoomed out](https://dl.dropboxusercontent.com/u/24401393/OpenRA/openra-icon-1.png)

![Icon zoomed in](https://dl.dropboxusercontent.com/u/24401393/OpenRA/openra-icon-2.png)

Thoughts?

**Comment by cjshmyr** [comment]
Definitely an improvement!

**Comment by pchote** [comment]
Maybe use the icons from the build palette tabs for the things they match with, and then make new ones in the same style for the ones that are missing?

**Comment by riiga** [comment]
Thanks, I used that for the tank and naval icons now, but for the rest they're pretty much identical to what I already have, or they won't look good at all, e.g. the infantry icon which would either look like crap at too small a size or take up too much space if larger, so I'll stick to a dot for infantry.

![Ships](https://dl.dropboxusercontent.com/u/24401393/OpenRA/openra-icon-4.png)
![Tanks](https://dl.dropboxusercontent.com/u/24401393/OpenRA/openra-icon-3.png)

**Comment by GraionDilach** [comment]
This'll be troublesome. The outer white edge will not work on snow terrain - you should use 2 pixel width outrlines with the outer being white, the inner being black.

**Comment by riiga** [comment]
I've checked them on a snow map and they look just fine, they're only shown underneath the fog which help add contrast.

Final result, the smaller dots will be the ones used.
![Icons](https://dl.dropboxusercontent.com/u/24401393/OpenRA/icons.png)

**Comment by GraionDilach** [comment]
IMO give the buildings' inner the outline as well - looks odd with all the rest (esp since tanks do have it).

**Comment by riiga** [comment]
I tried that before, but I think looks better like this. There's a darker colour on the inner outline, so the background doesn't shine through.

**Comment by Mailaender** [comment]
@riiga You can claim your https://www.bountysource.com/issues/29853092-difficulty-to-see-enemy-with-gps-satellite-under-fow-if-enemy-s-color-is-close-to-terrain-s
