### ISSUE TITLE
Make WithParachute respect player remap colors.

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#10503]
Currently it does not remap as expected.
[It only has a palette property, not a matching player flag](https://github.com/OpenRA/OpenRA/blob/8a755e673c20ede44cab5d82e2a1b21e9b98fa97/OpenRA.Mods.Common/Traits/Render/WithParachute.cs#L34-L35).

![](https://cloud.githubusercontent.com/assets/756669/12301729/e1e0cb04-ba21-11e5-9a01-b34efab82a72.png)

**Comment by pchote** [comment]
It also appears to be missing the lint attribute.
