### ISSUE TITLE
Same start positions and option to start game with all conyards/robes

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#10501]
Ability to select the same starting position for different players will give players more freedom of choice in a team game.

Like StarCraft, let the first player chose the first starting pozschitsiyu appears precisely at this point, and the player who chose the first position after the first player, let him appear in close proximity to this position.
## http://i081.radikal.ru/1601/df/3c806a763023.png

Start game with all conyards/robes awalebel in mod (may be ALL SIDES in side select BOX?)
i meen it must work somthing like that:
https://www.youtube.com/watch?v=iDWZ2Y0rgG4
In start the game player have GDI and NOD conyards in td/ts mods
in ra/ra2 mod, player have Soviet and Allied conyards
## in d2k mod he have all three conyards (Harkonnen, Ordos, Artreiders) 

I think it'll be intresting things

PS. sorri for my bad Inglish.

**Comment by yaaaaa** [comment]
*Start game with all conyards/robes available in ANY mod, sorry another time

**Comment by GraionDilach** [comment]
Rewording the thing incase some gets confused: Allow players to share the starting slot, with one player spawning directly there, and others spawning in a radius of X cells (to allow their MCV deployed in their spawning cell).

I'm not certain but AFAIK RA2 Unholy Alliance mode worked this way, with spawning two MCVs for the player. (Notsure though, I always played UA in YR.)

Probably not feasible though due to maps weren't planned with such amount of buildspace.

**Comment by yaaaaa** [comment]
Yes! Unholy Alliance!
https://www.youtube.com/watch?v=QjrwlepZweE :)
but it would be more convenient if it is available to each player individually, but not in play mode.
It may be in the form of a check mark next to the selection of fractions?

**Comment by yaaaaa** [comment]
"Probably not feasible though due to maps weren't planned with such amount of buildspace."
I think the players now can create maps that do not have enough space for the construction of even a single player.
I think this should not be a problem, as players choose their cards and the starting positions for the game

**Comment by penev92** [comment]
For a thirdparty mod it's beyond easy to have a "Starting Units" option that includes all sides' MCVs.
For the official mods, though, 1) I don't see it happening and 2) for some of them it's not possible, as the building prerequisites include the player's faction, not the present ConYards.

As for N players spawning at the same place - I don't see anything beneficial in that, and also the maps need to be specifically designed with that in mind (which they are obviously not). It might be a fun feature for a thirdparty mod to implement, but I really don't see the point (it can be done per map by placing the player spawns really close together).

**Comment by yaaaaa** [comment]
"for some of them it's not possible, as the building prerequisites include the player's faction, not the present ConYards"
May be more specific? in this case, what happens when a player plays for the Allies, captures the ConYard with the help of an engineer?
By the way, in the RA2 Unholy Alliance modе,additional SCV not give the player the possibility of using units of concreaт race, such as the Korean planes or Teslatanks , only based units and structures from Allied or Soviet side

"As for N players spawning at the same place - I don't see anything beneficial in that, and also the maps need to be specifically designed with that in mind (which they are obviously not)." 
I do not think that we need some reworking of CI, it's just an additional opportunity for greater freedom of choice.
In fact StarCraft maps uses the same in this type game.
In any case, the choice is left to the players, if map with few resources around startins position, they will choose a different map, and perhaps even on the contrary, the players want to play on a map where there are few resources from one spawning

**Comment by yaaaaa** [comment]
It may add *Unholy Alliance* funktionality by adding checkbox or Drop-down list of gamemodes (free for all, team alianse, unholy Alliance... etc).
And if Unholly Alliance is checked, you may shoose standard maps and game automaticaly turn off "starting units" Drop-down list and use:
```
MPStartUnits@UnhollyAllianceAllies:
		Class: light
		ClassName: UnhollyAlliance
		Factions: allies, america, germany, england, france, korea
		BaseActor: amcv
		SupportActors: smcv
```
from world.yaml 

Now it works fine in RA2 mod, but D2000 mod needs to some works, that makes structures and some units different for all three factions, example:

```
mcva:
	Inherits: ^Vehicle
	Buildable:
		Queue: Vehicle
		BuildPaletteOrder: 110
		Prerequisites: repair_pad, upgrade.heavy, ~techlevel.medium
		IconPalette: chromedune
		BuildDuration: 648
		BuildDurationModifier: 40
	Valued:
		Cost: 2000
	Tooltip:
		Name: Atreides Mobile Construction Vehicle
		Description: Deploys into Atreides Construction Yard\n  Unarmed
	Selectable:
		Priority: 4
		Class: mcv
	Health:
		HP: 4500
	Armor:
		Type: light
	Mobile:
		Speed: 31
		Crushes: fence, crate, infantry
	RevealsShroud:
		Range: 2c768
	MustBeDestroyed:
		RequiredForShortGame: true
	BaseBuilding:
	Transforms:
		Voice: Move
		IntoActor: construction_yard_a
		Offset: -1,-1
		Facing: 16
		TransformSounds: BUILD1.WAV
		NoTransformNotification: BuildingCannotPlaceAudio
	RenderSprites:
		PlayerPalette: d2kpal2
		Scale: 1.75
	WithFacingSpriteBody:
	SelectionDecorations:
		VisualBounds: 42,42
	SpawnActorOnDeath:
		Actor: mcv.husk
	SelfHealing:
		Step: 5
		Delay: 3
		HealIfBelow: 50
	Voiced:
		VoiceSet: VehicleVoice
	
		
mcvh:
	Inherits: ^Vehicle
	Buildable:
		Queue: Vehicle
		BuildPaletteOrder: 110
		Prerequisites: repair_pad, upgrade.heavy, ~techlevel.medium
		IconPalette: chromedune
		BuildDuration: 648
		BuildDurationModifier: 40
	Valued:
		Cost: 2000
	Tooltip:
		Name: Harkonnen Mobile Construction Vehicle
		Description: Deploys into Harkonnen Construction Yard\n  Unarmed
	Selectable:
		Priority: 4
		Class: mcv
	Health:
		HP: 4500
	Armor:
		Type: light
	Mobile:
		Speed: 31
		Crushes: fence, crate, infantry
	RevealsShroud:
		Range: 2c768
	MustBeDestroyed:
		RequiredForShortGame: true
	BaseBuilding:
	Transforms:
		Voice: Move
		IntoActor: construction_yard_h
		Offset: -1,-1
		Facing: 16
		TransformSounds: BUILD1.WAV
		NoTransformNotification: BuildingCannotPlaceAudio
	RenderSprites:
		PlayerPalette: d2kpal2
		Scale: 1.75
	WithFacingSpriteBody:
	SelectionDecorations:
		VisualBounds: 42,42
	SpawnActorOnDeath:
		Actor: mcv.husk
	SelfHealing:
		Step: 5
		Delay: 3
		HealIfBelow: 50
	Voiced:
		VoiceSet: VehicleVoice
		
mcvo:
	Inherits: ^Vehicle
	Buildable:
		Queue: Vehicle
		BuildPaletteOrder: 110
		Prerequisites: repair_pad, upgrade.heavy, ~techlevel.medium
		IconPalette: chromedune
		BuildDuration: 648
		BuildDurationModifier: 40
	Valued:
		Cost: 2000
	Tooltip:
		Name: Ordos Mobile Construction Vehicle
		Description: Deploys into Ordos Construction Yard\n  Unarmed
	Selectable:
		Priority: 4
		Class: mcv
	Health:
		HP: 4500
	Armor:
		Type: light
	Mobile:
		Speed: 31
		Crushes: fence, crate, infantry
	RevealsShroud:
		Range: 2c768
	MustBeDestroyed:
		RequiredForShortGame: true
	BaseBuilding:
	Transforms:
		Voice: Move
		IntoActor: construction_yard_o
		Offset: -1,-1
		Facing: 16
		TransformSounds: BUILD1.WAV
		NoTransformNotification: BuildingCannotPlaceAudio
	RenderSprites:
		PlayerPalette: d2kpal2
		Scale: 1.75
	WithFacingSpriteBody:
	SelectionDecorations:
		VisualBounds: 42,42
	SpawnActorOnDeath:
		Actor: mcv.husk
	SelfHealing:
		Step: 5
		Delay: 3
		HealIfBelow: 50
	Voiced:
		VoiceSet: VehicleVoice 
```
some units in Dune2000 mod like harvester do not needs to factionclones, because they do not affect the constructiontree.

**Comment by matjaeck** [comment]
I doubt that this discussion is ever continued, and penev's initial feedback suggests that the requested feature is possible for mods downstream, but unlikely to be included in the default mods. So I think this can be closed.

**Comment by abcdefg30** [comment]
I agree, this is already doable but unlikely to happen for the default mods. Map mods are an option.
