### ISSUE TITLE
Assign specific AI type to spawn

### ISSUE THREAD

**Issue by noobmapmaker** [OpenRA/OpenRA#10522]
For missions and other specific maps it could be handy to be able to assign specific AI to certain spawnpoints (e.g. Multi3 = Naval AI).

**Comment by penev92** [comment]
By the way, I don't think this makes any sense from a technical standpoint, so you shouldn't get your hopes up about this happening, sorry.

**Comment by abcdefg30** [comment]
This is possible, simply define `Bot: rush` or similar on the `PlayerReference` in `map.yaml`. See our campaign missions for example which assign the `campaign` bot.
