### ISSUE TITLE
Installing from CD does not work

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#10529]
The installer creates the /Content directory, but not the Content/mod subdir.  It then fails because it can't find the dir to copy the files to.

**Comment by pchote** [comment]
We should also truncate the error message to fit the dialog.

![screen shot 2016-01-16 at 11 40 53](https://cloud.githubusercontent.com/assets/167819/12372180/20cf2bfa-bc46-11e5-9305-9ec8a3c78802.png)

**Comment by yaaaaa** [comment]
maybe it halp to metod finde te path on disk?


[startool.zip](https://github.com/OpenRA/OpenRA/files/92871/startool.zip)

**Comment by Mailaender** [comment]
This was already fixed for the TFD installation in https://github.com/OpenRA/OpenRA/pull/9622.
