### ISSUE TITLE
Position of Leave and Stay buttons in TD reversed compared to other mods

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#10527]
In the TD mod 'Leave' is on the right, in the other mods on the left.

Personally I think TD's positioning makes more sense, as I consider 'Stay' to be the equivalent to 'Back'.
##

**Comment by pchote** [comment]
The TD UI has a convention through all the UI that actions that take the user "forward" are on the right, and actions taking them "back" on the left.

**Comment by pchote** [comment]
This discussion caused controversy when it was brought up on IRC [the first time](https://logs.openra.net/?year=2016&month=01&day=24#12:40:47).  Do we want to give it another stab, or should we give up and close this as a WONTFIX?

**Comment by dragunoff** [comment]
TD has a clear convention and a UI distinct from the rest of the mods. I think this is a WONTFIX.

**Comment by pchote** [comment]
Closing as WONTFIX.
