### ISSUE TITLE
download-error codepage 437 not supported

### ISSUE THREAD

**Issue by nyov** [OpenRA/OpenRA#10524]
(current latest debian package, running on debian jessie.)

While testing the asset download, the following error occured:

![downloadfail](https://cloud.githubusercontent.com/assets/438293/12366801/6bfaf24c-bbd5-11e5-86e6-e516dbdb09ae.gif)

Since the message always pops up _after_ successfully downloading, I would guess this error happens at the unpacking stage (is this a zip?), the error message doesn't make sense in any other context. Doing a quick search for the message, I came across something to do with [SharpZipLib library](https://stackoverflow.com/questions/4600923/monotouch-icsharpcode-sharpziplib-giving-an-error).

**Comment by pchote** [comment]
Thanks for the report! This has already been fixed for the next release.
In the meantime you can download the assets manually (find the urls in the mirror lists at https://github.com/OpenRA/OpenRAWeb/tree/master/content/packages) and extract them to `~/.openra/Content/<mod id>/` or launch the game forcing an english locale.

**Comment by BenjaminHerbert** [comment]
@pchote: For the latest release-20160508, this still does not work on my machine.

**Comment by pchote** [comment]
@BenjaminHerbert: installing the `libmono-i18n4.0-all` package should fix it.  The next release will automatically pull that in via the package dependencies.
