### ISSUE TITLE
release-20151224 / OS X not starting

### ISSUE THREAD

**Issue by lacombar** [OpenRA/OpenRA#10544]
On OS X, in the following environment:
 - OS X El Captain (10.11.2)
 - Mono for Mac OS X Universal (4.2.1.102)

The game is not starting *at all*. Looking at `top`, the `launchgame` process utilizes 100% of the CPU without any sign of progress. Meanwhile, the UI is completely frozen.

**Comment by Mailaender** [comment]
You are probably suffering from https://github.com/OpenRA/OpenRA/wiki/FAQ#pinwheel-of-death-when-starting-on-os-x-for-the-first-time

**Comment by lacombar** [comment]
indeed, feel free to close.
