### ISSUE TITLE
Types of GivesBuildableArea:

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#10550]
This would be cool for mods that allowing tech buildings gives area for defences but not normal buildings.
##

**Comment by Phrohdoh** [comment]
Makes sense to me. :+1:

**Comment by ABrandau** [comment]
This could potentially make building addons a thing.

**Comment by fgdzfggsfgsfgsf** [comment]
I don't get it?  You shouldn't be able to build a power plant near a tech center?  Why not?  Or it gives extra area?

**Comment by MustaphaTR** [comment]
No not tech center. Tech buildings are Oil Derrick, Hospital, Bio Lab and stuff like that which are preplaced on map.

**Comment by StexoO** [comment]
Tournament Isle would be played slightly differently... :yum:

**Comment by fgdzfggsfgsfgsf** [comment]
Ahh ok, in that case I would definitely be against this as a default - being the first to capture a tech building is already a big advantage, this would make it OP.  As an option for future maps designed with this in mind - sure.

**Comment by MustaphaTR** [comment]
I'm just making thinking this for Mods. I also disagree to using it for vanilla mod. But remember in RA2/YR u can build everything around tech buildings.
