### ISSUE TITLE
Error messages during mod installation are not truncated to fit the dialog

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#10556]
![screen shot 2016-01-16 at 11 40 53](https://cloud.githubusercontent.com/assets/167819/12372180/20cf2bfa-bc46-11e5-9305-9ec8a3c78802.png)

We may want to implement new options for truncating strings so that we can specify that the start of the path should be chopped off (which is at an arbitrary position inside the string).

**Comment by Mailaender** [comment]
Maybe better do a line break instead as this string contains vital information.
