### ISSUE TITLE
d2k-infantry missing idle animation

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#10566]
except for the grenadier , theres no infantry with idle-animation in the release

**Comment by Unit158** [comment]
These sequences don't exist, in fact.

**Comment by Micr0Bit** [comment]
you are right , thx

**Comment by Micr0Bit** [comment]
nope, this is actually cant be true ... i saw the infantry having idle-movement here : https://www.youtube.com/watch?v=4CbUr-MV5ho

so this sequences do or should exist ...

**Comment by reaperrr** [comment]
This was fixed in #11949.
