### ISSUE TITLE
Stuck AI harvesters can be a problem

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#10565]
This happens in TS/RA2 where the AI stacks building too close together or builds a refinery which exits to a cliff as the bibs are solely decoration. Harvesters failing to path constantly is expensive.

![image](https://cloud.githubusercontent.com/assets/756669/12529587/ce325cb0-c1bc-11e5-9a30-05043d5ddf80.png)
##

**Comment by pchote** [comment]
The exit/docking cells aren't set up properly for basically all the buildings in TS.  See also #9678 and the stream where fiveaces complains about barracks being blocked by cliffs.

**Comment by reaperrr** [comment]
Additionally, our current AI refinery placement logic places the ref in the direction of resources if possible, but as close to the base center (c. yard) as possible, as visible in the above screenshot. Would be nice if we could add some minimum adjacency from base center to this.
