### ISSUE TITLE
ReloadDelay does not appear to correctly apply to ObeliskLaserFire

### ISSUE THREAD

**Issue by whinis** [OpenRA/OpenRA#10574]
While working on  #10563 I noticed that the reason it didn't fire was because ReloadDelay was set to 120. Setting it to 1 allows it to fire but prevents animations from functioning correctly. Any Value less than 4 seems to have no effect on the Obelisk firing while any value greater than 4 prevents it from firing more than once.
##

**Comment by reaperrr** [comment]
What broke the charge animation was the removal of `ReloadTime` on `AttackCharge`.

The `InitialChargeDelay` really only applies to the very first charge, if I remember correctly.
Look at the TD obelisk yaml rules for comparison, where the animation works fine.

**Comment by whinis** [comment]
Removing ReloadTime just sets it to 120 as discussed in the PR

**Comment by reaperrr** [comment]
Oh, I forgot about the internal default. Nevermind then.

**Comment by whinis** [comment]
Your not entirely wrong, it is because the time is now 120, the animation fires and there is still 6 seconds before the obelisk does. But thats because ReloadDelay doesn't appear to work so you can set it to reload at 60 with a delay of 60. You have to set it to 120 for balance.

**Comment by reaperrr** [comment]
I think the problem can be summarized to "`AttackCharge` and its related activities are a mess". I suspect the reason why 4+ didn't work for you has to do with ChargeDelay, which has an internal value of 3. According to my tests, setting a higher ChargeDelay on AttackCharge allows a higher ReloadDelay on the weapon without breaking the firing.
And the fact that the ChargeFire activity performs  Attack.DoAttack before it adds the delay plays a role as well.

Last but not least, the "Charges: true" on some weapons seems to have bitrotted, I can't find anything that ties some logic to it.

**Comment by reaperrr** [comment]
This should be fixed with the recent AttackCharge rewrite.

**Comment by GraionDilach** [comment]
It still applies to AttackTesla, but whatever.
