### ISSUE TITLE
Port Stargus from Stratagus engine to OpenRA engine is possible?

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#10575]
"Disclaimer

Stargus is not an official Blizzard product, it's a Starcraft modification, by Starcraft fans for Starcraft fans. You need a copy of the original Starcraft version to make use of Stargus. Starcraft is a registered trademark of Blizzard Entertainment."

**Comment by pchote** [comment]
This is something that a mod could do, but is outside of the scope of our core project.

**Comment by yaaaaa** [comment]
Excellent, it means that it is reasonably possible, thank you.
It is unfortunate that only a third-party mod.
