### ISSUE TITLE
Game can get stuck in low tech

### ISSUE THREAD

**Issue by ottoville** [OpenRA/OpenRA#10586]
Consider a following scenario:

Players start game with tech level low tech in map which have sea.
One player build an ship yard and transport vessel. Then he move hes MCV to transport vessel, move the vessel away from shore. If that player now leave the game, there is an AI controlled MCV in ship which cannot be destroyed in any mean, because low tech level does not allow anyone to build war ships.
##

**Comment by reaperrr** [comment]
In my opinion, MCVs should not be builable at low tech.

**Comment by MustaphaTR** [comment]
That won't fix problem on long games (short game disabled). We should disable ships completely or enable Gunboat and Normal Sub. here.

**Comment by abcdefg30** [comment]
> In my opinion, MCVs should not be builable at low tech.

You can always unpack your original mcv. :p
(Also: Building mcvs is already restricted to the [medium techlevel](https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/rules/vehicles.yaml#L286).)

Short game won't fix it too, probably, as mcvs are [required for short game](https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/rules/vehicles.yaml#L314).

**Comment by HenrytheSlav** [comment]
Gunboats are rather weak to deal with subs though, it would give Soviets massive naval edge.

**Comment by klaas1** [comment]
What are you going to do with your massive naval edge in your low tech game? Protect your MCV in a transport?

**Comment by Smittytron** [comment]
I think gun boat and sub to low tech is the way to go here. 
In addition to disconnections, another issue is the sore loser type that will hide their MCV in a transport. This doesn't have to be on a naval map to happen. (i.e. Sidestep, Winter Storm) Unfortunately I've seen people hide mcv's to delay the inevitable more than once in this game, and if they are playing low tech for whatever reason, they can do so without being finished off.

**Comment by Elizadmin** [comment]
You can hide your last MCV in a transport ship, wait for the players to quit the game if they don't search it and then re-deploy your MCV.
It's not delaying the loss, it's the last one and only chance to __WIN__ the game.
Finally, who is the real "sore loser", the survivor in his transport ship or the "winner" who leaves before the end ? 😋

**Comment by pchote** [comment]
> Finally, who is the real "sore loser", the survivor in his transport ship or the "winner" who leaves before the end ? 😋

The survivor in his transport ship, definitely.  If you've been beaten fair and square then it's only polite to concede.  Frustrating the other player to the point of them quitting the game is just rude.
