### ISSUE TITLE
No way to assign a Default AI on Custom Missions

### ISSUE THREAD

**Issue by Narg6** [OpenRA/OpenRA#10589]
I was learning how to create new custom missions when I noticed there is not current way to assign a default AI to an enemy team, by default AI I mean the HackyAI. That would be lovely since not every scenario design needs a coded .lua AI and even useful as a placeholder.
##

**Comment by reaperrr** [comment]
I agree, this is somewhat overdue, and by now we should have enough control over most HackyAI aspects that it could actually work quite well in missions.

**Comment by Mailaender** [comment]
It may just need to interface with `IBot.Activate`.

**Comment by Narg6** [comment]
Sorry to bother, but any news on this ?

**Comment by abcdefg30** [comment]
Unfortunately not, as it seems.

**Comment by kyrreso** [comment]
Related to  #12949

**Comment by lovalmidas** [comment]
I have managed to use a custom HackyAI on my mission: http://resource.openra.net/maps/19901/
Is there still a problem with linking a HackyAI in your scripts?

**Comment by Narg6** [comment]
How did you do it?

**Comment by pchote** [comment]
#15540 and related PRs are working to split HackyAI into separate modules.  One of the goals of this work is to allow map scripts to enable specific bits of AI logic at will.

**Comment by abcdefg30** [comment]
#17129 shows how this is possible to do. (https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/maps/soviet-05/map.yaml#L52)
