### ISSUE TITLE
Display Freezes Until the Window is Refreshed

### ISSUE THREAD

**Issue by pianoasis** [OpenRA/OpenRA#10598]
Once I open the game and try to play it does not have any crashes or faults but the graphical display does not register in realtime, instead it freezes on whatever frame it was opened to until I refresh the window. I can't, rather, I don't want to play the game when I have to keep pressing Alt + Tab to see what my units are doing.

**Comment by Townes27** [comment]
Are you by any chance using KDE and 3D animation for switching between windows?
I had the same problem until I disabled the 3D animation.

**Comment by pchote** [comment]
OpenRA is at the mercy of the window manager and system compositor.  The behavior described doesn't seem like something we could trigger from OpenRA itself, so I don't think we will be able to fix this.
