### ISSUE TITLE
[D2K] Crash in a new map

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#10607]
I created a new Test Poligon map, and put all groundtypes and all units to MULTI0, to test unit speeds

and:

Dune 2000 Mod at Version {DEV_VERSION}
on map 324071129ab0c66652a13166bf8e55ba7e67ceb1 (Test Poligon by Remuneration).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Attempting to query the position of an invalid Target
   в OpenRA.Traits.Target.get_CenterPosition() в d:\Games\OpenRA-bleed\OpenRA.Game\Traits\Target.cs:строка 130
   в OpenRA.Mods.Common.Traits.AttackBomber.Tick(Actor self)
   в OpenRA.World.<Tick>b__7(TraitPair`1 x) в d:\Games\OpenRA-bleed\OpenRA.Game\World.cs:строка 303
   в OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text) в d:\Games\OpenRA-bleed\OpenRA.Game\WorldUtils.cs:строка 52
   в OpenRA.World.Tick() в d:\Games\OpenRA-bleed\OpenRA.Game\World.cs:строка 0
   в OpenRA.Game.InnerLogicTick(OrderManager orderManager) в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 557
   в OpenRA.Game.LogicTick() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 582
   в OpenRA.Game.Loop() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 709
   в OpenRA.Game.Run() в d:\Games\OpenRA-bleed\OpenRA.Game\Game.cs:строка 749
   в OpenRA.Program.Run(String[] args) в d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:строка 117
   в OpenRA.Program.Main(String[] args) в d:\Games\OpenRA-bleed\OpenRA.Game\Support\Program.cs:строка 39

**Comment by pchote** [comment]
It looks like you have customized the rules to make a unit with `AttackBomber` player-controllable.  This is not supported.

**Comment by yaaaaa** [comment]
No, I do not costumize anithing, i just place AttackBomber on a map in map editor, I'll try to delete it from the map now.

**Comment by jaZzKCS** [comment]
Well, if you just place it on the map it would be neutral, right? It will already be a problem since the owner of that AttackBomber is not the airstrike actor. If I understood that correctly, that is...

**Comment by yaaaaa** [comment]
hmmmm...

![image](https://cloud.githubusercontent.com/assets/11130958/12582495/bbb368ec-c467-11e5-9ce3-b7c99aa43c3e.png)

Wich of this is AttackBomber?

**Comment by yaaaaa** [comment]
oops
![image](https://cloud.githubusercontent.com/assets/11130958/12582549/fcbba28c-c467-11e5-90f8-5d1d7ab4d7fe.png)

**Comment by reaperrr** [comment]
The ornithopter.

**Comment by yaaaaa** [comment]
this is the map
[testpoligon.zip](https://github.com/OpenRA/OpenRA/files/105000/testpoligon.zip)

**Comment by yaaaaa** [comment]
yes, after delete ornitropters, crash is gone.
