### ISSUE TITLE
Where I can edit unit speeds on rock, sand, dunes etc?

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#10605]
And Where I can ask same questions?

**Comment by Phrohdoh** [comment]
IRC is a great place to ask questions and get help: #openra on the freenode network.

As for your question you will want to modify `TerrainSpeeds` on the `Mobile` trait.
[docs](https://github.com/OpenRA/OpenRA/wiki/Traits#mobile)

**Comment by yaaaaa** [comment]
Thanks!

**Comment by reaperrr** [comment]
As the question was specific and has been answered, I guess this can be closed.
