### ISSUE TITLE
if carryall is free, it must bring half-damaged units to service depot and comeback in battlefront after repair

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#10606]

**Comment by MustaphaTR** [comment]
Like in Dune2? That was a good think when i was playing it but sometimes finding units on service deport when searching them in your defence may be annoying.

**Comment by yaaaaa** [comment]
it will be good think if it was a optional function or availrble in third party mods.
I want to make Dune 2000 total rebalance mod

**Comment by MustaphaTR** [comment]
If Dune 2 mod will be added (someone was working on it, not sure about current status) we need to add support of this because this is anything in Dune 2.

**Comment by abcdefg30** [comment]
You can already manually order that. Just click with the repair wrench on a damaged unit and a free carryall should transport it to the next service depo. (It doesn't transport the unit back, though.)

**Comment by yaaaaa** [comment]
Yes, i know it. may I forced command to bing it back after repair? and maybe as varisnt set to all units avtomatically get repair commands, if damage <50%?

**Comment by Mailaender** [comment]
Those "let the game play itself" convenience requests are often futile. Also this will probably be annoying, if you are making a push and take some damage, but your carryalls will retreat half the tank army and let the others die a useless death as you don't have the critical mass to push through.

**Comment by yaaaaa** [comment]
Yes, I understand that, but some like the way they behave in the DUNE2, so it would be desirable make this functionality in my mod. Ideally, of course that it was an option if it is possible to add such aircraft to mode (by pressing the button the deploy command)

**Comment by Unit158** [comment]
I can't see this happening with D2K, but it would be fairly easy to make some new functionality for a dune 2 mod.

**Comment by pchote** [comment]
The consensus looks to be that this is out of scope for our default mods, so closing.
