### ISSUE TITLE
Some players have connection issues when they leave

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#10614]
Like Scuba Steve, many times I play with him, when he leaves when the game is ended, he got connection issues, then we have to wait for him to be dropped. If anyone exit while that countdown is, then it crash.
We should find out what systems he uses..

I see this also when he is winning, so I don't think its wifi-dc, etc...
##

**Comment by pchote** [comment]
> If anyone exit while that countdown is, then it crash.

Do you have a crash log from this?

**Comment by kyrreso** [comment]
Sorry, its only stall.. no crash.. so no logs I think?

**Comment by kyrreso** [comment]
can anyone ask him next time they meet him, what kind of system he runs? and how he leave? It happened again, after game was done..

**Comment by kyrreso** [comment]
![openra-2016-02-09t192307z](https://cloud.githubusercontent.com/assets/526956/12927938/260fc8c6-cf6b-11e5-80bc-d425ef5f6e0b.png)
He is using win10, and usually do first surrender, then abort game

**Comment by AoAGeneral** [comment]
Not sure if it relates to this but recently there has been some issues where some players will havea DC countdown timer. In some cases exactly this will happen and just locks the server up. But it gives no "Connection aborted message." or anything. Its just stuck. Screen can be scrolled around and you can click on stuff as if the game is waiting for players to connect. Just nothing.

Ive sat for about 30 minutes once before and it gave no progress. Once I left the server it took the server itself about 5 minutes to reset itself and pop back up.

If it happens again i will sit in the server for much longer and see what happens.

**Comment by pchote** [comment]
With a quick look I have narrowed this down to the frame associated with the Drop Client order (`0xBF`).  The timedout detection always uses `-1` and this is parsed by the other clients fine.  Other drops (including a player disconnecting normally) uses `Connection.MostRecentFrame`.

When a player drops while another player is stalling the game then the drop client order is *not* parsed by the other clients, and so the game will stall forever waiting for this other client.  I need to dig deeper, but I suspect that something in either the client or server has decided that all the orders from that client have already been dealt with, and so the drop is ignored.

I've confirmed that replacing `MostRecentFrame` with `-1` fixes the issue, but I expect this will have other unwanted side effects.  I strongly suspect that using `-1` for lag-drops is what caused #6241, and that this general drop-frame bogosity is causing our sporadic quit desyncs.

**Comment by pchote** [comment]
More specifically, for some reason `MostRecentFrame` is being set to 0 for a player who drops while the game is stalled (it is a sensible positive number for players who drop when the game is running normally).  This makes the server try and parse it as a server order which then fails and silently drops it on the floor instead of sending it to the other players.

Changing the `DispatchOrders` to `DispatchOrdersToClients` in `DropClient` provides another workaround, but the real bug and fix will be to work out why `MostRecentFrame` is being set to 0 in the first place.

**Comment by pchote** [comment]
Ok, well that was stupid.  `MostRecentFrame` is being set unconditionally with the frame for each order, which means it gets set to 0 when the client sends an immediate order like "hey i'm about out quit".
