### ISSUE TITLE
Lua Function Suggestion

### ISSUE THREAD

**Issue by Narg6** [OpenRA/OpenRA#10619]
Hello everyone, I wanna suggest a lua function that GIVES certain prerequisites to a player, example:

-> Until enemy radar is destroyed, the player is not allowed to build airfields.
->> After destroying the radar, the player receives the ability to build airfields.

I'm not sure if this is already implanted, but I couldn't find it anywhere, so I'm really sorry if that was the case.

**Comment by GraionDilach** [comment]
Probably you can do that already via spawning a dummy actor to the player which grants the prereqs.

**Comment by obrakmann** [comment]
Yes, please use dummy actors for this. Have a look at the `Intervention` mission in ra, which also grants a prerequisite that unlocks some actors for production when a certain event happens.
