### ISSUE TITLE
Custom map lightning affect icons that use custom palettes.

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#10622]
I was using a bleed version downloaded on the 25 of january of 2016, tested on the maps Sunstroke, an empty test map and Casey's Canyon.
![sin titulo](https://cloud.githubusercontent.com/assets/11763228/12621831/ce235eec-c4f8-11e5-923a-2d3adbe25a69.png)
![sin titulo4](https://cloud.githubusercontent.com/assets/11763228/12621923/4dc1e556-c4f9-11e5-872c-7fe0eb9383ab.png)
![sin titulo3](https://cloud.githubusercontent.com/assets/11763228/12621832/ce2b5afc-c4f8-11e5-9a94-e3f0fd3d0a31.png)

**Comment by pchote** [comment]
It looks like you're using a custom palette fro those icons.  You need to disable modifiers in that palette definition.

**Comment by GraionDilach** [comment]
So this is what `AllowModifiers: false` means on the cameo palettes! Never noticed it on my own. :D

**Comment by ABrandau** [comment]
lol graion, and yes, that fixed it, sorry!
