### ISSUE TITLE
Tiberium sun Waste Refinery in building menu for GDI

### ISSUE THREAD

**Issue by s7jones** [OpenRA/OpenRA#10631]
Playing latest bleed with commit 7b315aa9ccf47b1a5a55213677f9b13a1a1fa93d.

The waste refinery is in the GDI building menu when I'm playing a skirmish.

![waste_refinery_gdi](https://cloud.githubusercontent.com/assets/16854898/12664603/d5eae7ae-c628-11e5-9097-62136fee8283.png)

**Comment by Phrohdoh** [comment]
[nawast](https://github.com/OpenRA/OpenRA/blob/7b315aa9ccf47b1a5a55213677f9b13a1a1fa93d/mods/ts/rules/nod-structures.yaml#L409)
[namisl](https://github.com/OpenRA/OpenRA/blob/7b315aa9ccf47b1a5a55213677f9b13a1a1fa93d/mods/ts/rules/nod-support.yaml#L244)

**Comment by reaperrr** [comment]
nawast is missing `~structures.nod` prerequisite.

**Comment by Phrohdoh** [comment]
`namisl` shouldn't be satisfied without `structures.nod` anyway.
Am I reading this incorrectly?
