### ISSUE TITLE
Replace Server.LockBots option with Server.DisableSinglePlayer

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#10660]
The LockBots option was originally added in response to players using dedicated servers to play 1vbot games (back in the days when only TD had the skirmish mode).  Disabling bots even for proper multiplayer games is overkill, and rather unfair.

This has become topical again with the recent flood of players who have been asking / complaining about port forwarding.  Our best response "You don't need to - we provide dedicated servers for this" falls flat when one of the main game options for casual players is explicitly disallowed on them.

This is easy to fix and gives a big usability win, so i'm suggesting that we prioritise this for the next release. We already have code in place to disable the game starting if specific lobby slots are not full, and this can be extended with an additional check for > 1 human players.

**Comment by cjshmyr** [comment]
:+1:

**Comment by RockyTV** [comment]
Would this check here do what you're looking for? (of course, I haven't renamed the option yet):
```csharp
if (playerClients.Count() == 1 && 
server.Settings.LockBots && 
server.LobbyInfo.GlobalSettings.Dedicated)
```

**Comment by pchote** [comment]
That's the right idea, yeah.

**Comment by Micr0Bit** [comment]
:+1:
