### ISSUE TITLE
Use the battlefield news query to send system stats to the master server

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#10662]
Before we can fix #10661 we need an idea of how many players this will affect.
The battlefield news query runs once per game start, so it gives us a simple way to track active player statistics (unless the player explicitly opts out).

Implementation:

1. Add a `http://master.openra.net/gamenews` page, which can initially just do a http redirect to http://openra.net/gamenews.
2.  Change the `NewsUrl` to this new value.
2. Add an advanced setting for sending system statistics (enabled by default).
3. If the setting is enabled, send the current mod, `Platform.CurrentPlatform`, `Environment.OSVersion`, and `Platform.RuntimeVersion` (these are the same things we include in exception.log) as either GET or POST data along with the news query.
4. (can be left until after release) Change the gamenews page to start logging this information so that we look at aggregate OS/usage stats.

If we want to do anything about #10661 in the next year we really need to get this logging in the next release, so adding to the milestone.

**Comment by pchote** [comment]
We may want to include OS language too, as this will inform our plans for #10475.

**Comment by obrakmann** [comment]
https://github.com/OpenRA/OpenRA/compare/bleed...obrakmann:player-census
