### ISSUE TITLE
Problem with WithProductionDoorOverlay: and Transforms:

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#10671]
When transforming a building with WithProductionDoorOverlay: door anim doesn't disappear during make animation playing.

Just add `Transforms:` and other transforming stuff to war factory to test.
##

**Comment by penev92** [comment]
Just to clarify: when transforming *to* a building with that overlay, or *from* a building with that overlay?

**Comment by ABrandau** [comment]
Weeeeird, I had a similar issue with the fist of nod, where the door didn't dissapear when undeploying, better make a .gif man.

**Comment by MustaphaTR** [comment]
> Just to clarify: when transforming _to_ a building with that overlay, or _from_ a building with that overlay?

from

**Comment by MustaphaTR** [comment]
I recorded a video of it. I don't know how to make a .gif. https://www.youtube.com/watch?v=dNNL7AYmUJ8&feature=youtu.be

**Comment by GraionDilach** [comment]
Confirming, `WithProductionDoorOverlay` doesn't implement `INotifyTransform`.
