### ISSUE TITLE
Sometimes, the freezes shooting effect at Sardaukar.

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#10674]
It is happend, then sardakuar kills something.
[bandicam 2016-02-02 03-15-17-136.zip](https://github.com/OpenRA/OpenRA/files/113064/bandicam.2016-02-02.03-15-17-136.zip)

**Comment by Mailaender** [comment]
Duplicate of https://github.com/OpenRA/OpenRA/issues/7131.

**Comment by Mailaender** [comment]
or https://github.com/OpenRA/OpenRA/issues/5884.
