### ISSUE TITLE
Crashing on Windows 10 - error C5145: must write to gl_Position

### ISSUE THREAD

**Issue by DavidST44** [OpenRA/OpenRA#10691]
Trying to run OpenRA on my computer it opens I see the wallpaper background of the app and then my computer immediately restarts (as if the power went off). After doing this several times and giving I opened the Windows Troubleshooter and then OpenRA opened had a critical error (yay! now we got a logged error instead of nothing) and here's what it left me with.

I have the latest graphics drivers installed for my card Im using a Geforce 760 GTX and I run Geforce Experiance to keep that all up to date. Any followup questions let me know.

Running OpenRA release 20151224

From the Exception.log
------------------------------------------------------------------------------------------

Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: No suitable renderers were found. Check graphics.log for details.
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

From the Graphics.log
------------------------------------------------------------------------------------------

GL Info Log:
Vertex info
-----------
(0) : error C5145: must write to gl_Position

System.InvalidProgramException: Link error in shader program 'rgba'
   at OpenRA.Platforms.Default.Shader..ctor(String name)
   at OpenRA.Platforms.Default.Sdl2GraphicsDevice.CreateShader(String name)
   at OpenRA.Renderer..ctor(GraphicSettings graphicSettings, ServerSettings serverSettings)
   at OpenRA.Game.Initialize(Arguments args)
GL Info Log:
Vertex info
-----------
(0) : error C5145: must write to gl_Position

System.InvalidProgramException: Link error in shader program 'rgba'
   at OpenRA.Platforms.Default.Shader..ctor(String name)
   at OpenRA.Platforms.Default.Sdl2GraphicsDevice.CreateShader(String name)
   at OpenRA.Renderer..ctor(GraphicSettings graphicSettings, ServerSettings serverSettings)
   at OpenRA.Game.Initialize(Arguments args)

**Comment by pchote** [comment]
What version of OpenRA is this?

**Comment by GraionDilach** [comment]
>Running OpenRA release 20151224

**Comment by pchote** [comment]
[This stackoverflow post](http://stackoverflow.com/questions/25818858/opengl-3-3-glsl-c-error-must-write-to-gl-position) suggests that this might happen if the game fails to load the shader source.  Try reinstalling the game (something may have corrupted the install), and make sure that your virus scanner isn't interfering with the game files.

@GraionDilach: that was edited in after I asked.

**Comment by DavidST44** [comment]
Reinstalling OpenRA and disabling the virus scanner didn't help. It's now gone back to immediately restarting the computer whenever I try to run it can't even get a log now. Any other ideas let me know, interestingly I've got a different machine running Windows 10 and it works completely fun on that (but its a different hardware configuration). But as this is my main computer would like to get it running on this one.

**Comment by pchote** [comment]
Unfortunately I don't think there's much more we can do to help.  OpenRA itself can't trigger these types of errors, so it must be a bug in your drivers or some other OS-level thing.
