### ISSUE TITLE
Ra2 installation instructions for ubuntu

### ISSUE THREAD

**Issue by no-glue** [OpenRA/OpenRA#10694]
Can you provide more detailed installations instructions for ra2 on ubuntu?

**Comment by ScottNZ** [comment]
All ra2 issues should go on the ra2 repo. See https://github.com/OpenRA/ra2/wiki for ra2 installation instructions.

**Comment by no-glue** [comment]
those instructions do not work

**Comment by AbdoZaghloul** [comment]
I can't get RA2 to work on windows as well !!

**Comment by x-a-n-a-x** [comment]
@AbdoZaghloul : have you tried the step-by-step tutorial on the wiki ?

1. Go to https://github.com/OpenRA/ra2/wiki
2. On the right of the page click on **How to get the RA2 mod in OpenRA (bleed), under Windows**

**Comment by pchote** [comment]
Alternatively, file a bug on the RA2 repo's issue tracker.

**Comment by AbdoZaghloul** [comment]
@x-a-n-a-x 
I managed to get it shown at OpenRA  http://i.imgur.com/heRWA8r.jpg

,but when I load it I get this error http://i.imgur.com/RyBFl7D.png

**Comment by x-a-n-a-x** [comment]
@AbdoZaghloul : join us on our IRC channel : http://webchat.freenode.net/?channels=openra
This way, we will be able to help you more easily than here,

**Comment by penev92** [comment]
>All ra2 issues should go on the ra2 repo.

There is a reason RA2 isn't among the official mods.
