### ISSUE TITLE
[TS] aircraft can't fly into unexplored terrain.

### ISSUE THREAD

**Issue by jtyle6** [OpenRA/OpenRA#10699]
1. Make aircraft.
2. Select aircraft.
3. Move cursor into unexplored terrain.

Only unaffected aircraft is the [orca transport](http://cnc.wikia.com/wiki/Orca_Transport),
Affected aircraft are Orca Fighter • Orca Bomber • Orca Carryall • Banshee • Harpy

![aircraft](https://cloud.githubusercontent.com/assets/12602985/12867173/4e5985c8-cd32-11e5-9be0-061dba7c46e5.png)

**Comment by GraionDilach** [comment]
The bug is not what you think.

This is the TS behaviour and right now OpenRA aims to restore the TS gameplay as a start, not readopting one from the grounds with TS assets. The bug is thereby that Orca Transport should also be only capable of flying into previously revealed terrain.

**Comment by jtyle6** [comment]
Ah, haven't played much of Ts,

**Comment by Templarfreak** [comment]
Orca Transports are intended to move into Terrain. In vanilla TS's rules, the ORCATRAN does not have "MoveToShroud=no"

**Comment by penev92** [comment]
@Templarfreak is right. The Orca Transport is unbuildable, so this doesn't affect gameplay. Also changing it may potentially cause trouble in the long run when scripting missions.
Just play with cheats off.
