### ISSUE TITLE
Re-read map files on dedicated servers without restarting it

### ISSUE THREAD

**Issue by baxxxster** [OpenRA/OpenRA#10690]
I'm getting a few questions regarding the map sync on my servers if they are working or not, because when people join my servers and try to pick a map they've uploaded to resource center for greater than 5 minutes ago, they get "Map not found on server" - Even though it's there.

This seems to be because the maps are only loaded on server start (Same with client).

Is there any chance to put in a looping check of map files after the mod has been loaded? So the servers check the <mod>\maps every X minutes? (At least for dedicated servers, as these are usually unattended)

This way the servers don't need  to be restarted / play a game before they become available.

**Comment by baxxxster** [comment]
Other solution could be to check the maps folder on new admin joined / admin assigned?

**Comment by psydev** [comment]
Please fix this bug asap, it's really annoying. >:-|

Thanks.

**Comment by pchote** [comment]
If we expanded the MapPreview data / resource center API to include the extra data that the server needs to know about we could drop the requirement to sync maps completely.  The server could simply query and cache map info from the resource center as needed.
