### ISSUE TITLE
Default Game Speed doesn't change?

### ISSUE THREAD

**Issue by Templarfreak** [OpenRA/OpenRA#10709]
So, I wanted to make the Fastest game speed the default. I made these changes: http://pastebin.com/qs5DASzK and it sort of worked. In the lobby options, Fastest is the default selected game speed. Actually in game though the game speed **remains unchanged** from normal despite Fastest being highlighted in the lobby. I have to change the game speed to something else than back to Fastest for the game speed to actually be Fastest.

**Comment by swkeemink** [comment]
I ran into the same problem. I think this might be because the timestep and order latency are both also set in Session.cs (in OpenRA.Game/Network). It would make sense to link this to the 'default' option from the yaml file (although not sure how myself).

**Comment by pchote** [comment]
The followup PR to #11364 will be reworking the game speed backend, which should fix this.

**Comment by pchote** [comment]
This was fixed by #11556.
