### ISSUE TITLE
Mute and/or volume button for game sounds in while in menu

### ISSUE THREAD

**Issue by Crayeth** [OpenRA/OpenRA#10700]
Feature request: a simple mute button or clickable symbol to completely mute the game sounds when in menu's. Menu sounds could / should be unaffected.

Currently I play a lot of RA mod with teamspeak etc. on but it is mildly annoying that I cannot easily mute the game sounds when setting up the game.

Alternatively a slider specifically for the sounds of the rolling demo in the background.
##

**Comment by SzabKel** [comment]
You mean the shellmap sounds?

**Comment by Crayeth** [comment]
Yes, please tell me I haven't overlooked a simple toggle.

**Comment by GraionDilach** [comment]
There are no differences between shellmap and an ordinary game in that level of the engine.

**Comment by Crayeth** [comment]
Yeah, so, all the more reason I would like to be able to mute it or lower its volume while in the menu but when I start a match it should go back to normal, or its seperate volume. But like I said it is a minor annoyance only.
