### ISSUE TITLE
[RA] The official map pool. Altering existing maps.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#10718]
I encourage you to give specific feedback/contribututions to: 
**The Official Map Pool - collaboration thread** 
http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=294875#294875

I've gone through the existing RA maps and noted specific changes that IMO needs to be done. The changes are partially aesthetic and some balance related. This may or may not give the map new life but in any case they will look much better in the map chooser and in-game. If we are to hold on to the classic maps, they should at least be up to par with competing maps on aesthetics and balance. I've done my best to preserve as much of the maps' original character with the recommended changes.

Separate issues will eventually be submitted for each map for a final review and chance for additional discussion. All maps have been thoroughly playtested and altered after feedback from players before being submitted individually.

Map and author names should stay unchanged unless the map is altered a lot beyond it's original structure.

**Map list:**

Screenshots and comparisons are found on the altered maps' pages.

[**Forest Path**](http://resource.openra.net/maps/7295/) (2 players)
Move player spawns one cell away horizontally from the ore patches.
Change layout of actors around secondary ore patches to equalize access for both spawns.
Switch out actors (trees) to vary the fauna.
[Altered](http://resource.openra.net/maps/9138)
**Playtested, submitted at #10928**

[**Keep Off The Grass 2**](http://resource.openra.net/maps/7242/) (2 players)
Move the first ore patch for both spawns to balance ore access.
[Altered](http://resource.openra.net/maps/9008/)
also see #10347 
**Playtested, submitted at #10954**

[**Man to Man**](http://resource.openra.net/maps/7196/) (2 players)
Remove oil derricks -or- access them by bridge.
[Altered](http://resource.openra.net/maps/9230/)
also see #10312
**Playtested, submitted at #10953**

[**Sidestep**](http://resource.openra.net/maps/8176/) (2 players)
Add edge ridges for more distinction.
Add more roads, actors and debris to make the map less blank.
[Altered](http://resource.openra.net/maps/9353/)
**Playtested, submitted at #10927**

[**Singles**](http://resource.openra.net/maps/7353/) (2 players)
Map structure overhaul. see #10301
Work on balance and aesthetics.
[Altered](http://resource.openra.net/maps/9487)
**Playtested, submitted at #10987**

[**Snowy Ridge**](http://resource.openra.net/maps/7996/) (3 players)
Move the first ore patch for all spawns to balance ore access.
Move horizontal ridge north to equalize size of north/south fields.
[Altered](http://resource.openra.net/maps/9373/)
also see #10712
**Playtested, submitted at #10952**

[**Doubles**](http://resource.openra.net/maps/7153/) (4 players)
Map structure overhaul. see #10303
Work on balance and aesthetics.
[Altered](http://resource.openra.net/maps/9489/)
**Playtested, submitted at #10988**

[**Chokepoint**](http://resource.openra.net/maps/7285/) (4 players)
Make the corners' cliff and ore more symmetrical.
Narrow the top water a little on it's west side so player A and D symmetrically has equal fields towards the chokes.
[Altered](http://resource.openra.net/maps/8920/)
**Playtested, submitted at #10833**

[**East vs West**](http://resource.openra.net/maps/7583/) (4 players)
Add more detail scenery.
Tweak spawn spots so as making them distinguishable in the lobby.
[Altered](http://resource.openra.net/maps/9367/)
**Playtested, submitted at #10950**

[**Temperal**](http://resource.openra.net/maps/7233/) (4 players)
Add actors and debris to out-of-reach and vacant areas.
Slightly tweak the north players poor economic start position.
[Altered](http://resource.openra.net/maps/9456/)
**Playtested, submitted at #10980**

[**Asymmetric Battle**](http://resource.openra.net/maps/6790/) (6 players)
Add actors (trees) to areas unlikely to be used for base-building and battle.
[Altered](http://resource.openra.net/maps/9157/)
**Playtested, submitted at #10951**

[**Encounter**](http://resource.openra.net/maps/7290/) (6 players) 
Make the corner ridges more symmetrical.
Make all ridges more distinctive.
Balance east/west ore patches for corner player spawns.
[Altered](http://resource.openra.net/maps/9516/)
**Playtested, submitted at #10798**

[**High & Low**](http://resource.openra.net/maps/7999/) - 8 players
East/west are uneven in build areas, distance to deploy site and the map is slightly offset from the middle. Needs an overhaul.
Make ridges around player spawns more distinctive.
Add roads from the edges of player spawns leading out to the middle ground.
[Altered](http://resource.openra.net/maps/9457/)
**Playtested, submitted at #10979**

[**North by Northwest**](http://resource.openra.net/maps/6720/) (8 players)
Add more ore mines.
Remove 4 x middle edge ore patches, replace with debris.
Remove trees outside 4 entrances to the middle ground.
Add decorative trees.
[Altered](http://resource.openra.net/maps/9486/)
**Playtested, submitted at #10985**

[**Mass Confliction**](http://resource.openra.net/maps/7427/) (12 players)
Fix uneven build areas east/west (8 cell difference!)
Make ridges more symmetrical east/west.
Make ridges more distinctive.
[Altered](http://resource.openra.net/maps/9376/)
**Playtested, submitted at #10949**

**Additional altered maps by other users:**

[Artic Triangle Resort](http://resource.openra.net/maps/8081/) (3 players) -Major structural overhaul including balanced ore access.

**Suggested maps to be altered:** - Murto The Ray

[Artic Triangle Affair](http://resource.openra.net/maps/1313/) (3 players)
Make starting ore equidistant from spawns and make room for all player's MCVs in middle.
 
[First Come, First Served](http://resource.openra.net/maps/7249/) (4 players)
Widen center passage to encourage larger armies.

[Puddles Redux](http://resource.openra.net/maps/7961/) (4 players)
Take ore from near middle and place nearer starting positions.

[Tabula Rasa](http://resource.openra.net/maps/6750/) (4 players)
Make oil derrick valley entrance equal in size for both sides.

[Vegetation](http://resource.openra.net/maps/8066/) (6 players)
Widen gap between players and add small gap where walls join with the outer wall.

**Comment by r34ch** [comment]
Some of the 1v1 concerns have been addressed in #10298

**Comment by Micr0Bit** [comment]
i would prefer @SoScared 's "Man to Man" as it stays closer to the Original then the version from @r34ch ... and i gave allready a +1 for the Kotg2-version from @r34ch (which seem better balanced cause of the changed ore-fields ... which is in a better position for both players)

snowy-ridge should be fine (although theres not a lot of changes ... )

**Comment by SoScared** [comment]
Added screenshot comparison for each rework.

**Comment by SoScared** [comment]
Redecorated the maps and added screenshots to the map pages.

**Comment by SoScared** [comment]
There's also something to say about improving maps that improves the preview images in the map chooser. Example:
![examples](https://cloud.githubusercontent.com/assets/2715583/12935944/0c571ebe-cf9a-11e5-8c1b-b060d5775af1.png)

**Comment by SoScared** [comment]
I've done some work on all listed maps. Should each map be discussed in it's own issue or would this issue suffice for all?

**Comment by SoScared** [comment]
The Official Map Pool - collaboration thread 
http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=294875#294875
