### ISSUE TITLE
[RA] The official map pool. ...in with the new.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#10710]
The hardest maps to replace are the 6 player maps and up since few people are making regular mass player maps, and they vary greatly in quality. However here's a list containing some 2-player maps, and a variety of team and FFA maps. 

**Playtested**:

[Behind The Veil](http://resource.openra.net/maps/8795/) (2 players)
[Dual Cold Front](http://resource.openra.net/maps/9160/) (2 players)
[Northwest Passage](http://resource.openra.net/maps/8564/) (2 players)
[Warwind](http://resource.openra.net/maps/8925/) (2 players)
[Winter Storm](http://resource.openra.net/maps/6902/) (2 players)
[Sunstroke](http://resource.openra.net/maps/9020/) (3 players, FFA)
[Sudden Death](http://resource.openra.net/maps/9356/) (5 players, FFA)
[Pool Party](http://resource.openra.net/maps/9134/) (10 players, 5v5)

**Re-instate map removed from the latest playtest/bleed**:
[Caffeinated](http://resource.openra.net/maps/7369/) (8 players)

This map is the same map type, size and has the same player number (8) as Raraku. Raraku is a monstrosity and is suggested for removal in #10708. Imo, Raraku looks hideous, the map itself and in the map chooser, but also has poor options for team play and FFA. Caffeinated on the other hand looks decent as a non-symmetrical map, has multiple options for team-play, even multiple 4v4 positions. Personally, the games I remember on this map was generally fun. The are numerous maps  in the map pool currently that should be dumped _way_ before Caffeinated.

**Comment by pchote** [comment]
For reference, here are the top played maps (with >= 30 plays) that are available from the resource center rsync.

Resource Site						  | Plays
--------------------------------------|------
http://resource.openra.net/maps/8257/ | 669
http://resource.openra.net/maps/7972/ | 202
http://resource.openra.net/maps/6722/ | 201
http://resource.openra.net/maps/7018/ | 124
http://resource.openra.net/maps/4017/ | 119
http://resource.openra.net/maps/6899/ | 111
http://resource.openra.net/maps/6852/ | 105
http://resource.openra.net/maps/8228/ | 99
http://resource.openra.net/maps/8258/ | 98
http://resource.openra.net/maps/5676/ | 95
http://resource.openra.net/maps/8227/ | 84
http://resource.openra.net/maps/8232/ | 84
http://resource.openra.net/maps/8230/ | 74
http://resource.openra.net/maps/8214/ | 72
http://resource.openra.net/maps/8296/ | 70
http://resource.openra.net/maps/8075/ | 69
http://resource.openra.net/maps/6868/ | 61
http://resource.openra.net/maps/7100/ | 61
http://resource.openra.net/maps/8237/ | 59
http://resource.openra.net/maps/8331/ | 57
http://resource.openra.net/maps/4178/ | 55
http://resource.openra.net/maps/7038/ | 53
http://resource.openra.net/maps/7123/ | 52
http://resource.openra.net/maps/7798/ | 51
http://resource.openra.net/maps/8260/ | 50
http://resource.openra.net/maps/6998/ | 44
http://resource.openra.net/maps/8322/ | 41
http://resource.openra.net/maps/7269/ | 39
http://resource.openra.net/maps/8238/ | 39
http://resource.openra.net/maps/8079/ | 34
http://resource.openra.net/maps/6804/ | 32
http://resource.openra.net/maps/7289/ | 32
http://resource.openra.net/maps/8116/ | 30
http://resource.openra.net/maps/8239/ | 30

**Comment by Micr0Bit** [comment]
didnt the maps all get new hashes since the release ? 

i mean ... "top played maps" since when ?

**Comment by r34ch** [comment]
Behind the veil has already been added to the official pool. #10320

I agree with the suggested maps on balance, but I still think the aesthetics of some of the maps should be improved by their respective authors first. Some are a bit bare.

Pizza Atomicas maps are a great example of how maps can be balanced and aesthetically nice looking. Imho this is the bar that should be aiming for adding maps to the official pool.

**Comment by GraionDilach** [comment]
What about Tournament Isle and Terraform? They apparently look popular and pleasing at first glance.

**Comment by ScottNZ** [comment]
Tournament Isle is just a custom modified Tournament Island (which we already ship officially). Not much point in having both of them.

**Comment by SoScared** [comment]
@r34ch I think Sunstroke's chokepoint is fine for a 1v1v1 match. It's hard to lock down any key position on the map with multiple paths and 2 opponents. We're lacking 3 player maps. I think we should give this a chance. Which maps do you think should up the aesthetics?

**Comment by r34ch** [comment]
@SoScared My bad, I meant from a usability point of view rather than tactical. 

Because these choke points are only 2 cells wide, the unit path-finding with medium+ attack groups of tanks and infantry is pretty frustrating. Tanks get blocked easily and then try take the long way round which means more effort simply microing your army. This makes coordinating separate attacks much harder (frustrating)

I think that frustration can easily be avoided by adding a second mud crossing right beside each single mud crossing on the map (the bridges are fine). That would still keep them as tactical choke points but would help unit pathfinding _considerably_ so players can focus on the actual gameplay.

**Comment by SoScared** [comment]
That makes good sense.  I'll pass on the message to the author!
8. feb. 2016 09:44 skrev "r34ch" <notifications@github.com>:

**Comment by SoScared** [comment]
Sunstroke has been altered.
![sunstroke compare](https://cloud.githubusercontent.com/assets/2715583/13084216/d65fe2de-d4d8-11e5-9819-05c3586e7448.png)
Changes:
3 river passovers has been replaced by an open passage on the edges.
Remaining (3) river passovers has become twin passovers.

**Comment by jaZzKCS** [comment]
Reminder for SoScared: Dual Vegetation diversity.

**Comment by SoScared** [comment]
Dual Vegetation successfully diversified http://resource.openra.net/maps/9096/

**Comment by SoScared** [comment]
@r34ch Strange, somehow Behind The Veil has been dropped from the official map pool tab with the latest release. I thought it was just me but apparently noone can find the map there. 

Kyrylo made a new revision making it a 2 player map instead of a 4 player map. I'm adding it to the list.

Also had the pleasure of watching some games on Sudden Death (5 player FFA) and Pool Party (10 Player) by PizzaAtomica. e.g. Pool Party replay w 10 players: http://www.gamereplays.org/openra/replays.php?game=92&show=details&id=310681

Both are good looking, plays well and supplements the official map pools FFA and 10 player maps. Added those to the list.

**Comment by SoScared** [comment]
Added Dual Cold Front. Proved itself a great 1v1 custom map over a long period of time.

I'm not 100% on Dual Vegetation concerning playability. It's a good map IMO but way too big and macro for casual players. Removing it for now.
