### ISSUE TITLE
Alpha fade-in/fade-out effect support on sprite sequences

### ISSUE THREAD

**Issue by Apollo-X** [OpenRA/OpenRA#10727]
Implement Westwood like alpha fader trait/blending mode (Translucent=yes) that runs animation with 3 stages (or more for smoother) of alpha transparency toward fade out. 

WW does sorta /3 amount(?) of shp frames to for the value used: 25,50,75, in ORA this would be 75,50,25 order.

This would allow replicate effect fade out used in TS/RA2.
##

**Comment by GraionDilach** [comment]
A better and more OpenRAworthy approach would be to just create proper fading, without the Westwoody supercrude steppings.

**Comment by Mailaender** [comment]
Is this used for the Firestorm generator effect?

**Comment by penev92** [comment]
I don't think so. The sprite there looks just like it should.

**Comment by GraionDilach** [comment]
The wakes used this for a first look. https://github.com/LipkeGu/TSIniFiles/blob/master/art.ini#L2909

**Comment by Apollo-X** [comment]
Wakes, explosions, muzzles for starters... Quite many use it if look art.ini.
But yeah proper fading would be most ideal like whole 1.0 to 0 range and if specify alpha value, use it as starting point perhaps and by default start from 1.0 perhaps. Possibility consider fade-in support by allowing reverse direction (thus 0 would be start)

One idea could be to implement  it as timed steps like color cycling RotationStep if not elaborate frame support for specifying amount of alpha per wanted frame.

Fade-in buildups could be cool thing for high tech mods as one interesting idea.

**Comment by MustaphaTR** [comment]
> Fade-in buildups could be cool thing for high tech mods as one interesting idea.

Fade-in buildups are a thing in PS edition of CnC and RA. I think is support should be added to OpenRA too because it's better than having an empty placeholder buildup for a buildupless building in mods.

**Comment by pchote** [comment]
#18310 added the low level plumbing needed to support this. The question is now how to expose this to sequences: would a `FrameAlpha: ` list that specifies the alpha to use for each frame in the sequence be good enough?

**Comment by reaperrr** [comment]
I'm unsure about longer sequences. Think about something like the RA/TD smoke beacon animation with well over 100 frames...

Personally, I'd prefer something a bit more modder-friendly, for example:
```
Length: 44
DefaultAlpha: 128
AlphaFrameOverrides:
   0: 192
   1: 176
   2: 160
   3: 144
   40: 144
   41: 160
   42: 176
   43: 192
```

**Comment by pchote** [comment]
We could perhaps do:
```
Alpha: 0.5 # Applies to all frames in the sequence
```
```
Alpha: 1.0, 0.75, 0.5, 0.25 # One number for each frame in the sequence, throws an exception if the count doesn't match Length
```
```
Alpha: 0.5 # Applies to all frames in the sequence
   0: 1.0
   42: 0.25 # Except specific frame overrides
```

**Comment by reaperrr** [comment]
I prefer the latter. Having to mentally map a horizontal list of entries to the respective frame numbers is doable, but definitely more mental work and more error prone (and harder to edit, too).

**Comment by pchote** [comment]
I meant having the one implementation that supports all 3.

**Comment by reaperrr** [comment]
Ah, OK. Looks fine to me.

The only further improvement I could think of from a modders' perspective (feel free to ignore if it would create too much extra work) would be if it was possible to define ranges as well in the 3rd example, like

```
Alpha: 0.5 # Applies to all frames in the sequence
   0,11: 1.0
   12,20: 0.75
   42: 0.25 # Except specific frame overrides
```

**Comment by Apollo-X** [comment]
Well, why not just do something like

0: 1.0
10: 0.75
20: 0.50
30: 0.25

So the earlier value is used as long as next is not declared so ranges 0-9 use 1.0 and 10-19 use 0.75 so would not need to declare all of them necessarily. Granted, reaperrr's idea of actually specifying the range would be clearer if we need specify else a default alpha value and know when to use it.

However, for modder simplicity needing simple 'fade out' and not much fuss there could be single automated function that takes the total frame count and then math determine it (255/frame count? if over 255 use the max) out the amount of alpha steppings needed per every frame to go from 1.0 to 0.0 alpha float as mostly this would be closest match to westwood Translucent=yes yet achieve smoother given more alpha steppings if bigger amount of frames. Other option is modder provides a divisor value directly to the amount of frames in total to count the steppings. Another scenario is when you have say 1 frame artwork only but you need it faded out so it would need to determine how many steps/frames duplicate to run full alpha cycle in smooth manner without having to do an shp holding same frame dozen times just to get smooth fade out.

Just some thoughts.
