### ISSUE TITLE
Adding the Map Title somewhere in spectator view

### ISSUE THREAD

**Issue by anjew175** [OpenRA/OpenRA#10729]
Currently there is no way (that i can see) to find what map is currently being played from the spectator view.

Possibly add the map title in the statistics screen

**Comment by penev92** [comment]
:+1: 
I already added that to my WIP branch for #5121, but since I can't give an ETA for that, this can easily be done in the current UI.

**Comment by obrakmann** [comment]
Fixed by #10839. Maps now always include a map.png, [which will cause the briefing screen to be visible](https://github.com/OpenRA/OpenRA/blob/2d98e41f11f4c03f52f470fc04827c6ec53690f1/OpenRA.Mods.Common/Widgets/Logic/Ingame/GameInfoLogic.cs#L57), thereby showing the map title.
