### ISSUE TITLE
OpenRA.Utility.exe cant find my .ini world

### ISSUE THREAD

**Issue by KanickelKanone** [OpenRA/OpenRA#10724]
I tried to convert the .ini maps to .oramap but it keeps saying it cant find the .ini and OpenRA.Utility.exe crashes. I never converted or mapped anything like that so i dont know much about it. So what am i doing wrong?

**Comment by abcdefg30** [comment]
What command did you use (and which parameters)? And could you please post the crash report?

**Comment by KanickelKanone** [comment]
I navigated to the openRA folder and used the OpenRA.Utility.exe cnc --map-import filename.ini
I got a folder on my desktop where the old TD maps are. And i used scb01ea.ini
So i used the command : OpenRA.Utility.exe cnc --map-import scb01ea.ini
Crash log: 
Received args: --map-import scb01ea.ini
System.IO.FileNotFoundException: File not found: scb01ea.ini
Dateiname: "scb01ea.ini"
   bei OpenRA.FileSystem.GlobalFileSystem.Open(String filename)
   bei OpenRA.Mods.Common.UtilityCommands.LegacyMapImporter.ConvertIniMap(String iniFile)
   bei OpenRA.Mods.Common.UtilityCommands.LegacyMapImporter..ctor(String filename, Ruleset rules, Action`1 errorHandler)
   bei OpenRA.Mods.Common.UtilityCommands.LegacyMapImporter.Import(String filename, String mod, Ruleset rules, Action`1 errorHandler)
   bei OpenRA.Mods.Common.UtilityCommands.ImportLegacyMapCommand.Run(ModData modData, String[] args)
   bei OpenRA.Utility.Program.Main(String[] args)

**Comment by ihptru** [comment]
Try full path to ini file

**Comment by KanickelKanone** [comment]
how do i do a full path to a ini file?

**Comment by abcdefg30** [comment]
Just the path the ini file has. E.g. `C:\Users\KanickelKanone\Desktop\TDmaps\scb01ea.ini`.
(I.e. `OpenRA.Utility.exe cnc --map-import "C:\Users\KanickelKanone\Desktop\TDmaps\scb01ea.ini"`)

**Comment by KanickelKanone** [comment]
Thanks it worked!

**Comment by abcdefg30** [comment]
No problem. ;)
