### ISSUE TITLE
Refactor Domain Index possible performance improvements.

### ISSUE THREAD

**Issue by Codes4Fun** [OpenRA/OpenRA#10730]
Just some observations regarding the domain indices, and not from actual testing for performance issues (my computer is probably too fast to notice performance issues).

1) domain indices are built after a map is loaded, it seems as though it is something that could be done before or when saving the map and avoided when loading the map. It will increase the map size but it is easily compressed, maybe simple run length encoding will be enough.
2) If the map starts with a destroyed bridge, you end up with separate domains which is good for performance (early rejection before heavier path finding). When the bridge is repaired it creates a permanent connection between the domains to not reject path finding across those domains but when it is destroyed again those connections are not removed so you lose that benefit and will do heavier path finding each time after.
3) If the map starts with a bridge not destroyed it creates a single domain between both sides of the bridge, it loses out on the early rejection from #2 when the bridge is destroyed. It will do a heavier path search if there are no connection between both sides of the bridge.

So for #2 and #3, it would make sense that bridges are somehow ignored when building a domain index, separating both sides of a bridge into separate domains (unless there is a non-bridge connection between both sides of course). Bridge tiles getting their own domain value would probably work best for that and will also benefit in early rejecting trying to path to a destroyed bridge. And 'living' bridges would reference connections between domains, if a bridge is destroyed it dereferences the connection, and the connection is removed when there are zero references (zero bridges between domains).

I'm thinking on working on this when I get some time, maybe do some profiling first, but I wanted to throw it on here first.
##

**Comment by GraionDilach** [comment]
This is actually interesting, because TS ice logic might also get affected by this - where if units stood too much time on the "bridge", the tiles simply broke.

**Comment by pchote** [comment]
For the purposes of pathfinding there's no difference between bridges and ice.

**Comment by Codes4Fun** [comment]
For (1) I looked at perf.log after loading lots of maps in the 4 mods and found that in the worst case scenarios DomainIndex.WorldLoad was only 7% of load time somewhere between 20 ms and 170 ms. Making changes DomainIndex generation does not seem like it would save a lot of time and probably not worth the effort or complexity it would add.

I did notice that for all mods except D2k, most of the time was spent in PrepareMap, and most of that time (more than 1 second) is not currently profiled. I would say the average seconds for TS is 1.8, RA 1.5, TD 1. The peak I saw was 2.7 seconds for the largest map in TS.

**Comment by pchote** [comment]
That unprofiled time in PrepareMap is reloading all of the mod files.  I have a project underway with the eventual goal of removing that completely. (#10717).

**Comment by Mailaender** [comment]
I added `DomainIndex` support to https://github.com/OpenRA/OpenRA/pull/10760 this morning and it is a huge performance hog. Loading a TS map with many ice cells like Tread Lightly takes 15 seconds on my i5 laptop. With debugger attached it is about 45 seconds. It is a bit stupid to do domain indices, then setup all ice tiles and update for each ice tile individually though. Regrowable ice may be a real challenge.

**Comment by Codes4Fun** [comment]
Out of curiosity is there something that prevents putting IceLayer before DomainIndex in world.yaml?

**Comment by Mailaender** [comment]
Relying on trait ordering is usually something to avoid as it makes setting up the rules a bit harder, but it will probably be my intermediate solution. We could also invent a new interface `IBeforeWorldLoaded` for traits that change the map like bridges. https://github.com/OpenRA/OpenRA/pull/10764

**Comment by Mailaender** [comment]
A simpler fix was to just exclude all decorational ice tiles and focus on the water tiles marked as clear, which should actually clearly separate land masses for https://github.com/OpenRA/OpenRA/pull/10760:

```diff
@@ -109,14 +109,14 @@ public void WorldLoaded(World w, WorldRenderer wr)
 					Strength[cell] = strength;
 
 					if (strength < 4)
-					{
 						w.Map.CustomTerrain[cell] = w.TileSet.GetTerrainIndex(info.ImpassableTerrainType);
+
+					// Saves some resources by only updating domain indices for previous water tiles.
+					if (strength == 1)
 						updatedCells.Add(cell);
-					}
 				}
 			}
 
-			// TODO: This dramatically increases map load time.
 			var domainIndex = w.WorldActor.TraitOrDefault<DomainIndex>();
 			if (domainIndex != null)
 				domainIndex.UpdateCells(w, updatedCells);
```

**Comment by Codes4Fun** [comment]
RenderIceState is pretty cool, BTW, I used it as a basis for creating one for the DomainIndex, it makes it a lot easier to see what was happening in [6684](https://github.com/OpenRA/OpenRA/issues/6684) and [7539](https://github.com/OpenRA/OpenRA/issues/7539).

**Comment by Mailaender** [comment]
https://github.com/pchote/OpenRA/tree/cliffdomains also has a domain index debug overlay.

**Comment by Mailaender** [comment]
`DomainIndex` was removed in https://github.com/OpenRA/OpenRA/pull/19591
