### ISSUE TITLE
RA2 Fatal Error i can not understand

### ISSUE THREAD

**Issue by Druid-Sonne** [OpenRA/OpenRA#10736]
Win7 64bit

debug note
conquer.mix: failed to resolve filenames for 1 unknown hashes
conquer.mix: failed to resolve filenames for 1 unknown hashes
Found 35 domains for movement class 2923 on map Defend Crash Site.
Found 7 domains for movement class 32 on map Defend Crash Site.
Found 32 domains for movement class 7019 on map Defend Crash Site.
--Tick: 1 (net)
--Tick: 2 (local)
--Tick: 3 (local)
--Tick: 4 (net)
--Tick: 5 (local)
--Tick: 6 (local)
--Tick: 7 (net)
--Tick: 8 (local)
--Tick: 9 (local)
--Tick: 10 (net)
--Tick: 11 (local)
--Tick: 12 (local)
--Tick: 13 (net)
--Tick: 14 (local)
--Tick: 15 (local)
--Tick: 16 (net)
--Tick: 17 (local)
--Tick: 18 (local)
--Tick: 19 (net)
--Tick: 20 (local)
--Tick: 21 (local)
--Tick: 22 (net)
--Tick: 23 (local)
--Tick: 24 (local)
--Tick: 25 (net)
--Tick: 26 (local)
--Tick: 27 (local)
--Tick: 28 (net)
--Tick: 29 (local)
--Tick: 30 (local)
--Tick: 31 (net)
--Tick: 32 (local)
--Tick: 33 (local)
--Tick: 34 (net)
--Tick: 35 (local)
Could not find collection 'dialog'

**Comment by pchote** [comment]
The RA2 mod is not part of the main OpenRA repository.  Its bug tracker is at https://github.com/OpenRA/ra2/issues.
