### ISSUE TITLE
[RA] Option to show/hide '% of game played' information in the replay viewer.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#10745]
Like TD and D2K the U.I. shouldn't reveal how much of the game has passed. It's a spoiler for viewing other people's replays, including casts.

**Comment by pchote** [comment]
What if we showed the percentage progress in the ingame menu (when you press escape) instead?

**Comment by SoScared** [comment]
That would sounds fine.

**Comment by pchote** [comment]
Duplicate of #12017.
