### ISSUE TITLE
Add bigger terrain tiles to the map editor.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#10752]
Easy way to help map makers work much faster. 3x3 and 5x5 tiles would be nice.

**Comment by pchote** [comment]
#9935 suggests putting this as a modifier on the placement cursor.

**Comment by SoScared** [comment]
#9935 looks like a great solution. Perhaps adding new tiles (if it's easy) could be done temporarily if #9935 takes too long to finish.

**Comment by Smittytron** [comment]
Closing as wontfix after discussion in Discord. The Copy/Paste function of the Map Editor now covers the gist of this issue.

**Comment by Mailaender** [comment]
Also, the bucket fill is a far better option. I basically undid this in https://github.com/Dzierzan/OpenSA/pull/206.
