### ISSUE TITLE
Change grid color for the map editor.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#10753]
IMO the red grid is a bit straining for the eyes. It should be darker, e.g. dark red or black.

**Comment by Mailaender** [comment]
This defaults to:

```yaml
General:
	HeightDebugColors: FF0000
```

but can be overwritten per https://github.com/OpenRA/OpenRA/tree/bleed/mods/ra/tilesets

**Comment by abcdefg30** [comment]
Should be fixed by #10929.
