### ISSUE TITLE
Palettes in the assets browser don't work properly when the shellmap is disabled

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#10762]
![shellmapassets](https://cloud.githubusercontent.com/assets/7704140/13036592/c291e8b0-d36b-11e5-893e-50991ccba80f.png)
Only the `chrome` and `colorpicker` palettes seem to work with shellmap disabled.

**Comment by Mailaender** [comment]
Probably a regression from https://github.com/OpenRA/OpenRA/pull/10089.

**Comment by pchote** [comment]
Confirmed that this is indeed introduced by #10089.  Reverting that PR would be the best solution.

**Comment by abcdefg30** [comment]
This issue is back. Probably regressed by https://github.com/OpenRA/OpenRA/commit/31bdb1495d15879ba2f2830da68c49c3d8107921 ?

**Comment by pchote** [comment]
Oh, so now we know what to blame for the frustrating #11279.
