### ISSUE TITLE
Voxel preview shadows are drawn above units

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#10794]
Looks like they are adhering to a heightmap related default when they shouldn't.

![image](https://cloud.githubusercontent.com/assets/756669/13201977/909df05c-d888-11e5-8a72-37339e598278.png)

**Comment by pchote** [comment]
It ends up being based on the height of the cell at 0,0 in the map.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/issues/10689 may be related.

**Comment by abcdefg30** [comment]
This is actually fixed on bleed last I checked.
