### ISSUE TITLE
[RA] Official Map Pool: Alter Encounter (6 players) - balance, aesthetics

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#10798]
[**Encounter, current**](http://resource.openra.net/maps/7290/), (6 players)

Changes:
Make the corner ridges more symmetrical.
Make all ridges more distinctive.
Balance east/west ore patches for corner player spawns.

[**Encounter, altered**](http://resource.openra.net/maps/9516/), incl. fixed bottom right player spawn..

![encounter compare](https://cloud.githubusercontent.com/assets/2715583/13379382/42983c7c-de24-11e5-8474-f95630f17a6f.png)

![encounter compare](https://cloud.githubusercontent.com/assets/2715583/13379406/08dd1114-de25-11e5-9708-092017ba6a42.png)

**Comment by fgdzfggsfgsfgsf** [comment]
Looks good to me.

**Comment by SoScared** [comment]
fixed bottom right player spawn deployment with a new revision. issue updated.
