### ISSUE TITLE
Option to "lock the map" on dedicated servers. (Custom map-pools / Themed servers)

### ISSUE THREAD

**Issue by jaZzKCS** [OpenRA/OpenRA#10796]
Super self-explaining, and totally important feature needed for servers.

The ability to set - for example - something in the veins of "lock.map=true", effectively greying out the "change map" button even for the admin (person joining first), so that the map the server starts/loops with (that is defined under map=) cannot be changed.

This would enable us to have themed servers, e.g. servers dedicated to minigames like Fort Lonestar.
_
A step further would be to have "map pool" for the server, instead of just deleting all unwated maps from the servers' map repository, but that is another story for another day..._

**Comment by jaZzKCS** [comment]
Yes, I know that it is already possible by deleting all maps besides the one you want to lock from the servers' map dir. Albeit this just makes every other map selected to be labelled as "N/A on the server".

Having the button greyed out and the map selection screen totally inaccessible would look/work much better, IMO.

**Comment by Mailaender** [comment]
A `mapcycle.txt` in the support folder with hashes of the allowed maps could work.

**Comment by pchote** [comment]
Supporting limited map pools is a distinct feature, which is covered by #3558.

**Comment by jaZzKCS** [comment]
Yes, in addition to the map pool system already in planning apparently - it would be handy to lock the server to one map only, effectively greying out the change map button completely, so ppl will immediately see it is a one-map-only/themed server. (E.g. Lonestar)

**Comment by jaZzKCS** [comment]
> Yes, I know that it is already possible by deleting all maps besides the one you want to lock from the servers' map dir. Albeit this just makes every other map selected to be labelled as "N/A on the server".

Having the button greyed out and the map selection screen totally inaccessible would look/work much better, IMO.

This is - obviously - not an option anymore.

**Comment by pchote** [comment]
Servers can disable that by running the server with `Server.QueryMapRepository=false`.

**Comment by PunkPun** [comment]
Closed by #21179
