### ISSUE TITLE
Visceroids fusing

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#10791]
WIP at https://github.com/teees/OpenRA/tree/visceroid

**Comment by GraionDilach** [comment]
I'm not certain if that is right. Crushing a visceroid with another to upgrade the latter's art is already possible, the art upgrade can be triggered on that already and the random wandering wasn't really target-aware.

**Comment by Mailaender** [comment]
Yes, I agree our crushing framework already does the hard part. However I went with `Transforms` instead of artwork and rule upgrades in https://github.com/OpenRA/OpenRA/pull/13934.
