### ISSUE TITLE
subs "underwater" do not take damage from nukes

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#10812]
on a direct hit 

thats is just wrong , for the nuke there should be a exception on this sub-rule imo

**Comment by MustaphaTR** [comment]
This is becuase `Underwater` is not a `VaildTarget:` for `Atomic:`

https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/rules/ships.yaml#L27
https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/weapons/superweapons.yaml#L36

**Comment by StexoO** [comment]
I don't know anything about submarines in real life but they are at a depth of several hundred feet, are they affected by a nuke exploding above the water (density, pressure, stuff...) ?

**Comment by kyrylo** [comment]
Perhaps, they should also take damage from force firing?

**Comment by Micr0Bit** [comment]
well im not advertising "force firing -> damage underwater" ... just that nukes not doing a single hp damage on any sub underwater is kinda ... 

i have no idea about real-life subs either ... but this isnt really the point here (although a interesting question) ... as openra is allowing lots of stuff that doesnt follow real-world physics

**Comment by whinis** [comment]
Unless the nuke hits water most things in the water in real life will be fine, if it hits the water then a pressure wave will pretty much crunch everything within range. The reason they are fine if it doesn't hit the water is the pressure wave will glide over the water the same for trenches which you can see in some old atomic test videos.

**Comment by obrakmann** [comment]
So I searched online for information on this, and am now on probably many more lists than I already was =)

The closest thing to answering this question seems to be this: http://physics.stackexchange.com/questions/109888.

The reasoning seems sound to me. There are four major effects to nuclear explosions (radiation, thermal, blast and EMP), and a big body of water provides protection against all of them (assuming the explosion is an air-burst). With a (sub-)surface burst, [anything within at least a mile will be gone](https://medium.com/war-is-boring/how-to-nuke-a-submarine-2f0bd50f39e#.bqaf7na3h).

So the current behaviour is ok from a simulation standpoint. If it is from a gameplay standpoint is another question. I suggest we focus on the second question.

Personally, I think changing the nuke to affect submerged subs would be reasonable. Targeting subs with nukes is a game of chance at best anyway, so I doubt such a shame would have any real consequences except in corner cases.
