### ISSUE TITLE
Does not work combine many PNG in SHP.

### ISSUE THREAD

**Issue by Alex34567889** [OpenRA/OpenRA#10811]
Help me combine 8bits PNG in one common SHP. 
I tried OpenRA.Utility.exe --shp file1.png file2.png, file3.png ...and so on.Image size was the same, indexed color.But in the end it did not work. Help, please since I am new to this.

**Comment by abcdefg30** [comment]
What exactly did go wrong, can you post the error message/the content of `utility.log`, please?

(Btw, I also think it's possible to do `OpenRA.Utility.exe --shp file*.png`;))

**Comment by Alex34567889** [comment]
`Received args: --shp wall-0000.png wall-0001.png wall-0002.png
System.IO.InvalidDataException: Interlacing not supported
   в OpenRA.FileFormats.PngLoader.Load(Stream s)
   в OpenRA.FileFormats.PngLoader.Load(String filename)
   в OpenRA.Mods.Common.UtilityCommands.ConvertPngToShpCommand.<Run>m__1(String a)
   в System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   в System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   в OpenRA.Mods.Common.UtilityCommands.ConvertPngToShpCommand.Run(ModData modData, String[] args)
   в OpenRA.Utility.Program.Main(String[] args)`

I tried and so

`Received args: --shp wall-0000.png *wall-0001.png *wall-0002.png
System.IO.InvalidDataException: Interlacing not supported
   в OpenRA.FileFormats.PngLoader.Load(Stream s)
   в OpenRA.FileFormats.PngLoader.Load(String filename)
   в OpenRA.Mods.Common.UtilityCommands.ConvertPngToShpCommand.<Run>m__1(String a)
   в System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   в System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   в OpenRA.Mods.Common.UtilityCommands.ConvertPngToShpCommand.Run(ModData modData, String[] args)
   в OpenRA.Utility.Program.Main(String[] args)
`

**Comment by pchote** [comment]
> System.IO.InvalidDataException: Interlacing not supported

You need to disable interlacing when saving the pngs.

**Comment by Alex34567889** [comment]
Thank you!!! I understand where there was an error.

**Comment by Micr0Bit** [comment]
close please
