### ISSUE TITLE
Units can walk below veinholes

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#10815]
![image](https://cloud.githubusercontent.com/assets/756669/13266974/f0053778-da7a-11e5-8c68-4a1039ddeabe.png)

**Comment by epicelite** [comment]
No, it ate and is digesting the poor bastard.

**Comment by LordSyke** [comment]
Couldn't codding it to have logic that is similar to the pavement fix this? it would be a terrain building and block subterranean activities from occurring where it is at?

**Comment by pchote** [comment]
This will be fixed by #7520.

**Comment by reaperrr** [comment]
Should be fixed on bleed.
