### ISSUE TITLE
Add support to the GRP graphic file format (to use it in custom mods)

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#10829]
About file format:
http://www.file-extensions.org/grp-file-extension-starcraft-graphics-group-file

I want let possible mods, somthing like that:
http://repo.openpandora.org/?page=detail&app=package.starcraft
I meen "Data files from original full game are required"
"You need oroginal data CD or payed Steam copy оf SC/Brood War,  to play this mods"

**Comment by penev92** [comment]
1. OpenRA is specifically set up so thirdparty mods can set up their own sprite format parsers.
2. Blizzard has been known to be quite hostile when it comes to people using their stuff, so this is unlikely to happen at all, and will definitely won't happen in the original OpenRA.
3. If you are interested, I could point you to a working parser, but I wouldn't advise using it (I wouldn't advise using Blizzard property, the parser itself is fine).

**Comment by yaaaaa** [comment]
1. It's wonderfull.
2. I know how they relate to copying, but I have bought disk, and I plan to use content directly on it (do not copy/modify their stuff)
3. It will be very intresting to me, thank You. =)

**Comment by penev92** [comment]
Well, I will have to check later if I still have it.

**Comment by GraionDilach** [comment]
Yes, the GRP is a realllllllllllllllllllllllly bad idea due to Blizzard being terribly hostile.

**Comment by jaZzKCS** [comment]
That Blizzard is bad news. Leave that Blizzard alone.

**Comment by yaaaaa** [comment]
> 
> 
> Well, I will have to check later if I still have it.

Can You help me with parser?
