### ISSUE TITLE
Shift locks arrow key scrolling

### ISSUE THREAD

**Issue by lasselaak** [OpenRA/OpenRA#10828]
When shift is held down and any arrow key is pressed this arrowkey will be locked as being pressed.

Example situation:
I want to put a light tank to scout a certain area, I'll be holding shift down to allow for waypoints. The issue is, I also tend to scroll using arrow keys at the same time. If I press the left arrow while shift is held down, the left arrow will be locked and the map will scroll endlessly left until left is re-clicked.

This issue appeared in the previous playtest before the current release, before that no locking was done.

**Comment by rob-v** [comment]
> If I press the left arrow while shift is held down, the left arrow will be locked and the map will scroll endlessly left until left is re-clicked.

Probably fixed by #13115
