### ISSUE TITLE
Is it possible to disable the shellmap?

### ISSUE THREAD

**Issue by EpocDotFr** [OpenRA/OpenRA#10826]
Is it possible to disable the shellmap via a launch argument, a settings option, whatever?

Ps: you are awesome! Thank you for your work :)

**Comment by pchote** [comment]
Yes: there should be a checkbox on the main screen of the settings menu.  In a future release we are also planning to do something to reduce/mute the combat sounds, which is the main issue that people have with the shellmap.

**Comment by EpocDotFr** [comment]
Thank you! I did not see this checkbox.
