### ISSUE TITLE
Directional smoke trail support

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#10823]
Would allow modders to implement smoke, dust and wave trails that actually match the actor's or projectile's facing.

Would also spare me from shipping custom variants of Smoke, Missile and Bullet in my MechCommander mod.

**Comment by Micr0Bit** [comment]
this sounds like a useful addition

**Comment by Apollo-X** [comment]
Yes, this would very useful. I  have seen modern games even use this method with tiled art that gets fade out by alpha.
