### ISSUE TITLE
Framework .net version issue.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#10825]
The title could be wrong but Scott pointed out its a version .net issue. Said to make a ticket.

Linked examples when I unpacked the bleed:

https://www.dropbox.com/s/t1apap1sl5egs14/exception.log?dl=0

https://www.dropbox.com/s/koxpo0tkc8kuk4c/ORA%20Bleed%202242016%201721.png?dl=0

If the issue already exists then I missed it and apologize.

**Comment by reaperrr** [comment]
@AoAGeneral : Judging by the .net version listed there, yours is probably too old. I have Win7 as well, but with newer .Net, and no problems like this.
Make sure you have .Net 4.5 installed, and if you do, use windows updates to update it to the latest version.

That being said, our error messages should probably cover these cases better.

**Comment by pchote** [comment]
The powershell script should explicitly check / give an error if .NET 4.5 isn't available.

This doesn't affect the ability to run *the game* (compiled elsewhere) on .NET 4, so i'm not too concerned about adapting the script to work there.

**Comment by TSnake41** [comment]
The exception in log is not about .net version but game rendering.
@AoAGeneral You gpu don't seem support sdl2, try to update your graphics drivers and retry.
I have the same problem on an old computer (with Linux and Windows both).

**Comment by pchote** [comment]
The exception is caused by the missing sdl.dll, which isn't downloaded because of the incompatible powershell script.

**Comment by AoAGeneral** [comment]
Currently running .net 4.0 however when installing 4.5 and 4.6 it does not install. The graphic drivers I can try and check but its an R9 200 series at 4gb. 

Will update when troubleshooting the following

**Comment by RoosterDragon** [comment]
I have .NET 4.6.1 on my Win 10 machine and it works fine.

You should be able to find the dll under `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.IO.Compression.FileSystem.dll` (or in the v4.5 folder or later should do).

If you're missing that dll, you should try installing 4.6.1 again and retrying (rebooting for good measure may help too).

**Comment by AoAGeneral** [comment]
Only v3.0 and v3.5 is only in the folder. In regedit.exe I have v4.6.1. In add/remove programs 4.6.1 also shows up in there too. Although win 10 and win 7 might have different structures in comparison to how the regedits work.

I pulled the DLL file though and got it installed in the two folders and it works just fine. Just comes up with that packing error. But the system registers 4.6.1 and in the games too.
