### ISSUE TITLE
Are you interested in creating the C&CTD/RA and D2K crossover mod (not thirdparty)?

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#10832]
I meen to make another one mod (maybe "Official OpenRA Crossower mod"), which will be regularly absorb the entire contents/stuff of the other official mods.

Tiberian origins mod was so fun...
http://www.moddb.com/mods/command-conquer-tiberian-origins/downloads
But that mod stop upgrades in 2014y.

**Comment by pchote** [comment]
There are no plans for an official mod of this type.

**Comment by penev92** [comment]
Does not sound like something that will happen to me.

**Comment by Micr0Bit** [comment]
openra gives the opportunity to make a brand new rts - games ... with original ideas ... tbh. im really far from being interested playing another crossover-cnc

and time is better spend on making our existing main-mods more unique from gameplay-feeling ... a crossover using the same graphics "again" would be just boring imo
