### ISSUE TITLE
Game shouldn't crash if Valued: is not set on a Buildable unit.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#10844]
Currently it causes a crash when you hover on the actor's cameo. If vauled is not set it should be free and shouldn't cost at all.

**Comment by GraionDilach** [comment]
???

**Comment by Phrohdoh** [comment]
> when you hover on the actor's cameo

`Tooltip` has a hard dependency on `Valued` (`.Trait`, not `.TraitOrDefault`).
I agree that this is an unnecessary annoyance.

> If vauled is not set it should be free and shouldn't cost at all.

I'm not sure about this.
On one hand it makes logical sense to imply a 0-cost, but on the other that is putting more behind-the-scenes assumptions into the game and I think it is better to be explicit in a situation like this.

**Comment by pchote** [comment]
`BuildableInfo` can add `Requires<ValuedInfo>`

**Comment by Mailaender** [comment]
This has already been resolved in https://github.com/OpenRA/OpenRA/commit/17daac11a114fa9ca2fa3fbe8677aaad0268efc3 as part of https://github.com/OpenRA/OpenRA/pull/10557.
