### ISSUE TITLE
Remove remaining floating point calculations from simulation code.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#10845]
The Shattered Paradise stream had a couple of desyncs, which I suspect may be caused by fp disagreements that we don't see in the default mods because of our default values.  For consistency and safety we should work to remove the remaining fp calculations from the simulation code.

The ones I know (there may be more) are:
- [x] `WVec.LerpQuadratic` (can use Decimal or long)
- [x] `ReturnToBase.CalculateTurnRadius` (can use int constants)
- [x] `ProductionQueueInfo.BuildSpeed` (can use an int percentage)
- [x] `CapturableInfo.CaptureThreshold` (can use an int percentage)
- [x] `CapturesInfo.SabotageHPRemoval` (can use an int percentage)
- [x] `EmitInfantryOnSellInfo.ValuePercent` (can use an int percentage)
- [x] `EmitInfantryOnSellInfo.MinHpPercent` (can use an int percentage)
- [x] `StrategicVictoryConditionsInfo.RatioRequired` (can use an int percentage)
- [x] `SelfHealingInfo.HealIfBelow` (can use an int percentage)
- [x] `MinelayerInfo.MinefieldDepth` (can use WDist)

**Comment by reaperrr** [comment]
Is it just me, or does nothing actually use `EmitInfantryOnSellInfo.MinHpPercent`? Couldn't find any logic making use of it...
