### ISSUE TITLE
[TS] Units Ignoring Terrain and Just Pass Thru

### ISSUE THREAD

**Issue by WilliamWsyHK** [OpenRA/OpenRA#10842]
[TS]
Units would directly ramp-up on the cliff and just like ignoring the fact cliff is impassable (esp. for ground vehicle)

(It also affect RA2 mod, BTW; OpenRA/ra2#150)

**Comment by pchote** [comment]
I expect that the TS/RA2 pathfinder had a check that prevented movement across non-continuous height/slopes.

**Comment by penev92** [comment]
Can you show an example of that happening in TS?

**Comment by WilliamWsyHK** [comment]
Pardon my late respond... :cake: 

(Version I use is downloaded on 8 Feb)

Here is the Wolverine by-passing the "cliff" (technically it is a ramp looks like a tunnel entrance)
![tsignoreterrain-1](https://cloud.githubusercontent.com/assets/10591975/13461166/e7defa66-e0ba-11e5-8247-84ef9fd7e902.png)

This one with Terrain Geometry
![tsignoreterrain-2](https://cloud.githubusercontent.com/assets/10591975/13461279/67cec95e-e0bb-11e5-90b5-9bd1baaf0ab8.png)

**Comment by pchote** [comment]
Thats not really a bug.  Tunnels are not implemented yet.

**Comment by WilliamWsyHK** [comment]
Oh.. yeah I agree this is not a bug, but I don't see this one pretty as ground units can just walk through the tunnel entrance as ramp and got onto the higher ground.

**Comment by penev92** [comment]
That is how they are supposed to work at this point. They will stop once tunnels are implemented.
This is different from the RA2 bug you linked to above.

**Comment by LordSyke** [comment]
Giving it a building foundation should fix this part of it.

**Comment by LordSyke** [comment]
Also setting it to use the logic a repair bay uses but making it so it's locked from allowing units to enter them would be a good addition to add also until we figure out how to code them to work just like the Original TS's ones work. I say make it closed by setting the owner ship to a side that doesn't exist or a dummy side such as "mutants" for now should be good.

**Comment by pchote** [comment]
Tunnels are covered by #6410.  Lets keep this ticket limited to the issue where units move over height discontinuities.

**Comment by LordSyke** [comment]
Could tunnels be given an invisible shadow addition that hides or overlaps anything it covers?

**Comment by PunkPun** [comment]
This is no longer an issue
