### ISSUE TITLE
You can just undeploy your MCV to save it from C4.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#10846]
It should still blow up anyway, obvious bug.

EDIT: or sell any building.

**Comment by AMHOL** [comment]
I was thinking about this, even when you get the "flash" from Tanya C4 they can still un-deploy and save it, I think players should be rewarded for noticing and un-deploying, I was thinking maybe the MCV could explode with some burst damage, enough to seriously harm or kill the tanya and maybe cause a bit of damage to nearby structures, maybe getting a power-down or something.
