### ISSUE TITLE
Replace map descriptions with more appropriate metadata.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#10858]
The map `Description` field is an inconsistent mess that is used for disjoint purposes:
 * Mission briefings (in the mission browser).
 * General comments shown on the resource center, but not suitable to display in the lobby.
 * Instructions for minigames, which would be suitable to display in the lobby.
 * "Describe your map here".
 * "Converted by Dan9550".

I think that there's a general consensus that it would be good to let maps display some info somewhere (either as a tooltip or a chat message) in the lobby, but the vast majority of the descriptions are not useful or suitable to display (for reference: [here's a list of all the descriptions from the 4966 RA maps available on the resource center, collapsed to 807 unique entries](http://pastebin.com/raw/CMnRDgAq)).

I think the best approach here is to ~~migrate the map Description field to the resource center database~~ (already done) and remove it from the map files.  We can then introduce specific trait properties for mission descriptions and for messages that are displayed in the chat when a map is selected in the lobby.

**Comment by pchote** [comment]
The resource center is already set up to support my proposal:
```
17:31 <+ihptru> pchote, for information: map description is fetched to resource site database during uploading. Additional information which can be added later is placed to another field.
17:32 <+ihptru> removing it from yaml will leave description field empty. Nothing is going to be broken.
17:32 <+pchote> we will still want people to be able to add descriptions for the resource center
17:32 <+pchote> and then maybe edit them too
17:32 <+pchote> using fields on the site itself
17:32 <+ihptru> this exists
17:32 <+pchote> oh, I didn't know that
17:33 <+ihptru> people always could add more info, most of them do it
17:33 <+ihptru> and then can edit, or remove
17:33 <+pchote> does it just use the map description as the initial value?
17:33 <+ihptru> yes, and additional info is concatenated afterwards with new line.
17:33 <+pchote> great
17:34 <+ihptru> api serves that too
17:34 <+ihptru> example: http://resource.openra.net/map/hash/445031937c804e22c431cb9565c44208d38ccfe0
17:34 <+ihptru> `description` and `info`
17:35 <+ihptru> first from yaml.
17:35 <+pchote> ah, makes sense
17:35 <+ihptru> http://resource.openra.net/maps/9204/
17:35 <@orabot> Title: OpenRA Resource Center - Map details - Abnormality
```

**Comment by Mailaender** [comment]
Good idea. :+1:

**Comment by pchote** [comment]
Added in #10857.
