### ISSUE TITLE
AI without Refinery but not in low power will stop production.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#10852]
Compared to that, AI in low power and without Conyard will still train new stuff from the remaining factories.

**Comment by obrakmann** [comment]
Are you sure about that? I just tested it and the AI kept on producing units just fine:
![screenshot from 2016-03-08 19 18 02](https://cloud.githubusercontent.com/assets/4331210/13611405/b1a63e08-e562-11e5-92ad-69dec0662cb3.png)

The AI *will*, however, stop producing things when it is out of refineries. Could that be what you saw?

**Comment by GraionDilach** [comment]
It finishes building what it started but does not queue any more. I'm watching AI matches all day, it's definitely not the refinery.

**Comment by obrakmann** [comment]
Hmmno, I couldn't reproduce that. One AI was building hordes of infantry after I destroyed its conyard.

**Comment by abcdefg30** [comment]
Sorry, can't reproduce this on my end in RA either. Could it be your AI definition?

**Comment by GraionDilach** [comment]
It might be the refinery as well though. TBH I lost my ideas too.

**Comment by abcdefg30** [comment]
Yep, it is the refinery.

**Comment by MustaphaTR** [comment]
Are you sure it is not because AI loses al the doposited ore and goes of money, so it can't build anything.

**Comment by abcdefg30** [comment]
I just gave the AI some map placed buildings. With a refinery it happily started to produce blobs of units. Without a refinery (but still with the starting money) it just did nothing.

**Comment by pchote** [comment]
This appears to be by design: HackyAI checks for this this specific case and disables production: see https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/AI/HackyAI.cs#L1017 and https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/AI/HackyAI.cs#L432

**Comment by pchote** [comment]
`HasAdequateProc` should probably include a check for the construction yard to avoid a permanent stall if you destroy its refineries and structure production.

**Comment by GraionDilach** [comment]
The autocloser ended up bogus.
