### ISSUE TITLE
[Resource Center] Add mod filter to the web for maps.

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#10867]
The Resource Center site needs a mod filter,browsing maps for specific mods its a pain right now.
Things like mod,terrain type,official rules,player number, are missing right now.just saying.

**Comment by MustaphaTR** [comment]
https://github.com/OpenRA/OpenRA-Resources/issues is for resource center there is for game.

**Comment by KOYK** [comment]
darn it,my bad.
