### ISSUE TITLE
Star Wars: Galactic Battlegrounds mod is possible?

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#10869]

**Comment by wolxXx** [comment]
i would <3 this :)

**Comment by pchote** [comment]
Technically possible, yes, but out of scope of our core project.  It could be done as an external mod.

**Comment by yaaaaa** [comment]
=)

**Comment by Phrohdoh** [comment]
@yaaaaa If you are looking to star a SW:GB mod ping either myself or @penev92 on IRC for information.
