### ISSUE TITLE
Property name inconsistencies

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#10864]
In a lot of places we use different terms for the same thing.

For example, `SmokeTrailWhenDamaged`'s `Sprite` property serves the same purpose as `Image` on most other traits, projectiles and so on.
Another example is `Trail` on `Bullet` vs. `TrailImage` on `Missile`.

And there are surely more cases like these.

**Comment by pchote** [comment]
Do you have a specific list of things to fix to resolve this issue?
The projectile trailts have been done, but `SmokeTrailWhenDamaged` still needs fixing.
