### ISSUE TITLE
Navigation issues with current UI and mod platform concept

### ISSUE THREAD

**Issue by hollowsmith** [OpenRA/OpenRA#10868]
**Thoughts on UI and future development**

After more than year of playing OpenRA I found it more than sufficient in terms of in-game feature development, but somehow disappointing in terms of UI enhancements. This could lead to turning away from the game from the start for people who aren't familiar with C&C but tried to play OpenRA. I'm basing on personal experience and experience of friends and familiar designers. Current UI is straightforward, but not intuitive and bulky. Now you can expect to see things not fitting for place, like "Music" section in "Skirmish".

I and many other devs see OpenRA as base platform for development. That's where we need to start.

**1. Mods Section**
OpenRA is a platform that gathered old C&C games around it. And we remember that there are a lot of mods that base on main games. So we should take original main games as _"MASTER MODS"_ and name every mod that bases on them as _"BRANCH MODS"_. People still can create their own Master Mods that heavily modify engine and serve as independent game. People who add couple of new tanks to opposite sides and bunch of missions usually heavily rely on Master Mods, so they only need a link to Master Mod.

![oramods](https://cloud.githubusercontent.com/assets/17611709/13489867/6cd9ed1e-e13a-11e5-932f-a2e3b54a2778.jpg)

One problem still exists up to this day - when you select "Mods" section you don't have option to go back to menu - it uses first time starting screen as default confingurator. Either load mod (which takes some time) or quit from game - no turning back. This is what should be fixed first.

**2. Single Player**
While single player missions is under construction development of this section UI can be put on hold. But basic point on Single Player structure should be noted:

Single Player:
**+-** Campaigns (Main and Branch squential mission packs)
**+-** Missions (Main and Branch separate missions maps, challenges and non-sequential mission packs)
**+-** Skirmish

**3. Multiplayer, Coop and Skirmish**
This is the main reason for writing this. Problems I see:
- Chat section takes much space, but is necessary so it needs a "Hide" button (especially for Skirmish, where you don't write to anyone)
- Chat typing section is small in comparison to chat log. Typing long sentences is incovenient.
- "Start Game" and "Back" buttons are so close and misclicking is probable.
- "Music" section in multiplayer game options??? I doubt the usefulness in this.
- Whole UI needs some kind of folder bookmark style to intuitively navigate though options. Sections and buttons are scattered on the screen right now.
- You can't get whole summary on used options fast.

So I suggest new multiplayer (coop and skirmish too) UI system:
![oramulti](https://cloud.githubusercontent.com/assets/17611709/13491666/bcfb945a-e144-11e5-8636-a5831e0d8941.jpg)

_Sections:_
Players - self-explanatory.
Options - this is where admon decides what type of game it will be (standart battle, infantry war, naval war, e.g.) and all types options in list that support that kind of game type (you don't need "Ally Con. Yards" or "Starting Cash" in mode without bases, for example). That will determine what maps can be used. This will require to mark maps with labels (what game types that map will support).
Mutators - this is where you can add and delete your micro-mods. Much like Unreal Tournament 2004. "Double range of the artillery" or "No aircraft", for example. Could be useful for quick balance changes and checks too. Fun intended too. Mutators must have labels as well - which game type they will support.
Summary - quick glance on all options: selected map, players, game type, options, mutators and mutator options.

Map section now will have technical data instead of creator name. Map selector don't need map type selector anymore in new UI.

**Comment by pchote** [comment]
How would the Players tab look like in your mock up?  The tabs on top conflict with the column labels.

Music controls in the lobby was a long-requested feature.  Setting up a MP game can take quite a while (waiting for players, choosing options, general chatting), and previously players would need to leave the lobby (and possibly lose their spot) if they want to change the music track.

**Comment by hollowsmith** [comment]
1) Players tab would be the same - everything there seems to be logical. The only thing I would change - "Slot Admin" button. I would place it on top so you won't need to scroll down all the way down to reach it.
Or functions can be separated on different buttons. Like this:
![orateams](https://cloud.githubusercontent.com/assets/17611709/13493198/bb048b12-e14d-11e5-93f9-84d373c41334.jpg)
Different setup functions can be placed on top of list: configure teams, configure bots, configure colors for players (I miss the standart 8 color pallette, though).

2) Music control - well, I don't know the real reason why player control can't be placed in the corner of the screen as small simple panel. "Prev, Play / Pause, Next, Shuffle On/Off, Select track (popup list)". Then you can change music anywhere from main menu to depth of mission selection or map selection.
![oraplay](https://cloud.githubusercontent.com/assets/17611709/13493504/839c5978-e14f-11e5-9501-ce380e212f9a.jpg)

**Comment by pchote** [comment]
With regards to the player tab, I mean the specific design implementation: in our existing UIs tabs are attached to the top or bottom of a scrollpanel or bin.  The player bin has a static row of labels (which don't scroll) above the scrollpanel, and the player rows are then inside the bin (which do scroll).  Placing the tabs at the top means either removing the labels, moving them inside the bin, or having a scroll panel nested inside a bin: none of these are very good options.

**Comment by hollowsmith** [comment]
My opinion: buttons and colummn labels should be always visible if "Players" tab is opened. You can only scroll list of players, cause it's the only thing that dynamically changes over time.
![oracol](https://cloud.githubusercontent.com/assets/17611709/13494027/d271f1c2-e152-11e5-90ce-15edeec57d6a.jpg)

**Comment by pchote** [comment]
The lobby window has evolved a fair bit since this was created, and some of these ideas have been incorporated.  The ingame mod browser has been completely removed.

Closing as fixed/no longer valid.
