### ISSUE TITLE
Theoretical NullReferenceException in GameInfoStatsLogic

### ISSUE THREAD

**Issue by RoosterDragon** [OpenRA/OpenRA#10878]
Discovered by Coverity.

There are null checks in `GameInfoStatsLogic` to guard against `client` being null. Previous feature, bug and fix for context: #6360 #6444, #6450.

As of #10067, `client` is now directly dereferenced [here](https://github.com/OpenRA/OpenRA/blob/aa78dc32e391acdf95de879a26d15509429a8a3b/OpenRA.Mods.Common/Widgets/Logic/Ingame/GameInfoStatsLogic.cs#L55) (and the called method also unconditionally deferences it).

I can't grok enough of it to decide what the fix is. Either we can drop the null checks because they're redundant now - or null is still possible in which case the line I called out needs to handle that somehow (but I have no idea how).

**Comment by pchote** [comment]
The main difference is that it only gets called once during setup there, and client shouldn't be null.  We can probably get away with squashing the error by adding an `if (client != null)` check before calling that method: if something is bogus enough for client to be null then they simply won't get a tooltip.

**Comment by RoosterDragon** [comment]
Fixed in #11079.
