### ISSUE TITLE
Inner Exception of type `System.DllNotFoundException`: libgdiplus.so

### ISSUE THREAD

**Issue by YuGiOhJCJ** [OpenRA/OpenRA#10872]
Hello,

I have just built OpenRA-20151224 on Slackware 14.1 and mono-4.2.2.30:
```
$ make dependencies
$ make
```
After that I have run the game:
```
$ mono --debug OpenRA.Game.exe
Platform is Linux
Using SDL 2 with OpenGL renderer
Desktop resolution: 1366x768
No custom resolution provided, using desktop resolution
Using resolution: 1366x768
Detected OpenGL version: 3.0
Using OpenAL sound engine
Using default device
AL lib: (EE) alcOpenDevice: Option 'format' is deprecated, please use 'channels' and 'sample-type'
Available mods:
	all: All mods ({DEV_VERSION})
	cnc: Tiberian Dawn ({DEV_VERSION})
	d2k: Dune 2000 ({DEV_VERSION})
	modchooser: Mod Chooser ({DEV_VERSION})
	ra: Red Alert ({DEV_VERSION})
	ts: Tiberian Sun ({DEV_VERSION})
Exception of type `System.TypeInitializationException`: The type initializer for 'OpenRA.Support.PerfHistory' threw an exception.
Inner Exception of type `System.TypeInitializationException`: The type initializer for 'System.Drawing.KnownColors' threw an exception.
  Inner Exception of type `System.TypeInitializationException`: The type initializer for 'System.Drawing.GDIPlus' threw an exception.
    Inner Exception of type `System.DllNotFoundException`: libgdiplus.so
      TypeName=``
        at (wrapper managed-to-native) System.Drawing.GDIPlus:GdiplusStartup (ulong&,System.Drawing.GdiplusStartupInput&,System.Drawing.GdiplusStartupOutput&)
  at System.Drawing.GDIPlus..cctor () [0x000cc] in /tmp/build/mono-4.2.2/mcs/class/System.Drawing/System.Drawing/gdipFunctions.cs:119 
      at System.Drawing.KnownColors..cctor () [0x0001a] in /tmp/build/mono-4.2.2/mcs/class/System.Drawing/System.Drawing/KnownColors.cs:215 
    at System.Drawing.Color.get_Red () [0x00000] in /tmp/build/mono-4.2.2/mcs/class/System.Drawing/System.Drawing/Color.cs:879 
  at OpenRA.Support.PerfHistory..cctor () [0x00000] in /tmp/build/OpenRA-20151224/OpenRA.Game/Support/PerfHistory.cs:21 
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x00278] in /tmp/build/OpenRA-20151224/OpenRA.Game/Game.cs:250 
  at OpenRA.Program.Run (System.String[] args) [0x00007] in /tmp/build/OpenRA-20151224/OpenRA.Game/Support/Program.cs:115 
  at OpenRA.Program.Main (System.String[] args) [0x00050] in /tmp/build/OpenRA-20151224/OpenRA.Game/Support/Program.cs:39 
AL lib: (EE) alc_cleanup: 1 device not closed
```

And as you can see there is an exception indicating a missing library: libgdiplus.so.
Indeed, this one is not built as I have no result with this command:
```
$ find . -name "libgdiplus.so"
```

Any idea how to solve this issue?

Thank you.
Best regards.

**Comment by pchote** [comment]
I'm not sure how the slackware mono packages are set up, but it looks like you are missing parts of mono.  There should be a package called `libgdiplus` that is pulled in as part of the `mono-complete` or `mono-devel` (or equivalent) packages.

**Comment by YuGiOhJCJ** [comment]
I have built myself mono because it is not provided by Slackware.
```
$ tar xvf mono-4.2.2.30.tar.bz2
$ cd mono-4.2.2
$ ./configure --prefix=/usr
$ make
```
I have not patched mono at all so it is the default set up and I can't do better.

You speak about mono-complete or mono-devel.
After a research, I found that it is the name of packages available for Ubuntu:
http://packages.ubuntu.com/wily/mono-complete
http://packages.ubuntu.com/wily/mono-devel

I checked for "libgdiplus.so" on the Ubuntu website:
http://packages.ubuntu.com/search?searchon=contents&keywords=libgdiplus.so&mode=exactfilename&suite=wily&arch=any

It seems that the package containing this library is named libgdiplus:
http://packages.ubuntu.com/wily/libgdiplus

It is indeed part of the mono-project:
http://www.mono-project.com/docs/gui/libgdiplus/

I thought that it was part of the game because "gdi" remind me the Global Defense Initiative in the Command & Conquer game :p 

So, yeah the libdgiplus library source code is available separately here:
https://github.com/mono/libgdiplus

I think I must build and install it.
I tell you later if it works.

**Comment by YuGiOhJCJ** [comment]
OK, it is fixed after installing this library.
Problem solved I can play the game now :)
