### ISSUE TITLE
Submarine Titans mod is possible?

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#10870]

**Comment by pchote** [comment]
The engine is designed to be flexible, so it is probably technically possible (I'm not familiar with the game).  We do not have the manpower to expand our core project to cover additional games, but this could be done by others as an external mod.

**Comment by Micr0Bit** [comment]
#10871

**Comment by Askmewho** [comment]
This would be awesome..

**Comment by yaaaaa** [comment]
https://www.youtube.com/watch?v=G_tffw7g_dE
