### ISSUE TITLE
Inability to spam "building placement" shortcuts on bleed

### ISSUE THREAD

**Issue by kyrylo** [OpenRA/OpenRA#10881]
Hey! Sorry for a possible duplicate, but it's pretty hard to search for this kind of issue (and also hard to describe it).

On bleed, I noticed you can't keep the "E" button ("R", "T", etc) pressed to spam the "place building" command. That is, on current release you can press "E" while producing a building, which will trigger an infinite "switch tab" sound and as soon as your building is ready, you will be able to put it on the map. I have recorded this technique recently, so the video illustrates what I am talking about (mind the timestamp): https://youtu.be/P0fj_h_JxD4?t=2m48s 

Was it intentional? Can we bring this behaviour back? It's actually very useful.

**Comment by abcdefg30** [comment]
Related to #10734.

**Comment by obrakmann** [comment]
Duplicate, even.
