### ISSUE TITLE
GravityBomb cannot lack an image.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#10883]
It crashes when firing the default value of null. The common projectiles (Missile and Bullet) do not.

**Comment by Drtikul** [comment]
Hello, 

I am fan of this project/game so I decide to start contributing something back to the community. This bug seems like a something I can start with. Is this ok with you? :+1:

**Comment by abcdefg30** [comment]
@reaperrr already submitted a fix: #10886
So I don't think this would be good to start with, sorry.
