### ISSUE TITLE
Un-deploying conyard removes all targets

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#10887]
If you target an enemy conyard and they un-deploy it, the MCV is treated as a new unit so your units un-target it, this is very annoying for air units (especially fast ones like migs and yaks) and annoying for a ground army which normally just target the nearest harvester leaving the MCV to get away.

**Comment by Micr0Bit** [comment]
i dont see that necessarily as a issue ...  the "conyard-shake off" is widely accepted  by good players (i have never heard any concerns about)

**Comment by StexoO** [comment]
It generally gives you one chance to save your const yard... if you know the trick and if you react quickly.

**Comment by AMHOL** [comment]
I've seen people abuse this when attacking with yaks, they just constantly deploy and un-deploy making it impossible to take down, then they just build an AA gun or SAM site, assuming they have another conyard and build it next to it when they deploy it, taking out your air fleet and retaining their conyard

**Comment by SMIFFGIG** [comment]
Seem's like a bug to me, doesn't make any sense as a feature, even if it can be manipulated to be useful for the player who owns the CNST it's potentially frustrating and annoying for the attacker, as it makes no sense.

**Comment by GraionDilach** [comment]
It probably cannot and won't be fixed as being a sideeffect of Transforms and MCV-Conyard deploy is too much change in terms of functionality to shift that to upgrades.

@SMIFFGIG Pretty sure TS/RA2 works this way, because of the WW deploy limits as well.

**Comment by Phrohdoh** [comment]
This is entirely a consequence of the way [`Transforms`](https://github.com/OpenRA/OpenRA/blob/0dcc51b3a395d06f5d77a0b9e9cdd2d875383217/OpenRA.Mods.Common/Traits/Transforms.cs#L131) works as a trait.
The [`Transform`](https://github.com/OpenRA/OpenRA/blob/0dcc51b3a395d06f5d77a0b9e9cdd2d875383217/OpenRA.Mods.Common/Activities/Transform.cs#L81) activity creates a brand new actor.

Discussion from IRC:
```
[01:41:16]	<Phrohdoh> AMHOL: the engine creates a new actor when Transforms is used
[01:41:49]	<AMHOL> Ahh OK, so no way to retain targets?
[01:42:00]	<Phrohdoh> So from a gameplay perspective yes it is broken but the engine doesn't think so. We have DeployToUpgrade to somewhat resolve this, but there are valid cases for Transforms.
[01:42:23]	<Phrohdoh> Correct, the new actor would have to alert the ones targeting the old one that it changed, and afaik we don't have anywhere to store that data.
[01:42:26]	<Phrohdoh> (the list of attackers) 
```

**Comment by Micr0Bit** [comment]
this should get closed then

**Comment by GraionDilach** [comment]
99% certain WONTFIX issues are still issues so a ticket opened for them is still valid.

**Comment by Micr0Bit** [comment]
nice , lets keep all the "99% certain WONTFIX"-tickets open for the eternity ...

**Comment by AoAGeneral** [comment]
While the undeploy and deploy bug resets the attacks on the structure there might be one solution to fix this involving C4 deployments. (Tanyas, Commandos). Slow the deployment animation down just enough where the C4 would still explode. This makes the two units deadlier rather then "Well I can't C4 the conyard because it will just undeploy and deploy again." Also benefits the risk factor of "I can take out some of the production or risk it for the conyard. Hmm."

**Comment by Mailaender** [comment]
> This is entirely a consequence of the way Transforms works as a trait.
> The Transform activity creates a brand new actor.

The `ActorID` simply has to be moved as well or if that causes problems an interface needs to update all current attack states with the new actor ID. Probably not easy, but not impossible to fix.
