### ISSUE TITLE
UPnP has bad discoverability

### ISSUE THREAD

**Issue by Alex34567889** [OpenRA/OpenRA#10903]
Hello.Sorry a silly question. Why can not check the box the Automatic port forwarding in the Create Server dialog. Prompt me please.
![2016-03-10_105058](https://cloud.githubusercontent.com/assets/17353812/13662956/4ba45ca4-e6af-11e5-8bcb-27324ec7ef91.jpg)

**Comment by jaZzKCS** [comment]
It means that UPnP port forwarding is either disabled or unavailable on your system.
In this case - if you are behind a router - you would have to log-on into your router and forward the neccessray ports manually to the internal LAN address of the computer you want the server to run on / want to host the game.

**Comment by ScottNZ** [comment]
I think it would be good to have a tooltip explaining this when you hover over the checkbox

**Comment by Alex34567889** [comment]
UPnP enabled. It remains a problem in other.
![2016-03-10_162422](https://cloud.githubusercontent.com/assets/17353812/13670778/e3c7578e-e6dc-11e5-8719-df41fcb68758.jpg)
That is without this command, the server does not create?

**Comment by pchote** [comment]
The current UPnP library is quite broken and relatively unmaintained, and our preferred alternative requires us to upgrade our minimum depedencies to .NET 4.5.2 (which means dropping support for Windows XP and certain older but still supported Linux distributions).

We're making steps to hopefully make this switch in the second release after 20151224.

**Comment by KevinYeti** [comment]
@pchote hi, I'm new here and I just want to know the UPnp library has been upgraded for now ? because the Upnp function seems not work fine for me.

**Comment by pchote** [comment]
Not yet, but soon (for the next release). #11284 finally removed support for windows xp and the older versions of mono that were holding us back, and #11286 is currently open to switch to the new UPnP library and enable it by default.

**Comment by fadyanwar** [comment]
Is UPnP still and issue? I'm unable to host a server on my machine. Release 20190314
  Operating System: Ubuntu 19.04
  Kernel: Linux 5.0.0-16-generic
  Architecture: x86-64
