### ISSUE TITLE
D2k worm attack sound not playing

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#10936]
You no longer hear the worm attacking.
Must be caused by some recent change.

**Comment by obrakmann** [comment]
Introduced by ccdbdebdb19965b17db93caefdf3b3268ff50520 as part of #10530.

**Comment by pchote** [comment]
Probably a case sensitivity issue.

**Comment by obrakmann** [comment]
yep

**Comment by pchote** [comment]
We probably want a (non-lint, like sequences) check for these issues.
