### ISSUE TITLE
Crash on Linux

### ISSUE THREAD

**Issue by BenjaminHerbert** [OpenRA/OpenRA#10945]
The game crashed while playing skirmish.

This is the log entry:

> Red Alert Mod at Version release-20151224
> on map 1ab7971f4efcd61f4a3007704c1f08f72d8686a2 (Mad Science by PizzaAtomica).
> Operating System: Linux (Unix 3.16.0.38)
> Runtime Version: Mono 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1) CLR 4.0.30319.17020
> Exception of type `System.InvalidOperationException`: Attempted to finalize an undisposed DisposableAction. hind (446) reserved fix (398)
>   at OpenRA.Mods.Common.Traits.Reservable+<Reserve>c__AnonStorey0.<>m__2 () [0x00000] in <filename unknown>:0 
>   at OpenRA.Primitives.ActionQueue.PerformActions (Int32 currentTime) [0x00000] in <filename unknown>:0 
>   at OpenRA.Game.LogicTick () [0x00000] in <filename unknown>:0 
>   at OpenRA.Game.Loop () [0x00000] in <filename unknown>:0 
>   at OpenRA.Game.Run () [0x00000] in <filename unknown>:0 
>   at OpenRA.Program.Run (System.String[] args) [0x00000] in <filename unknown>:0 
>   at OpenRA.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0

**Comment by GraionDilach** [comment]
Thank you for the report, however...

This is a duplication of #9783 which was fixed in #9786, the fix will be in the next version.

**Comment by abcdefg30** [comment]
Yep, looks like a duplicate, thanks for the report though!
