### ISSUE TITLE
Bring back artillery chain-explosion

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#10958]
It was the only real way to deal with arty spam and now its gone(or broken).

**Comment by Ovrclockd** [comment]
Yes, arty is ridiculous in this game right now... I think it should be less accurate as well and when I tell my infantry to run away after they get blasted they need to hurry up and not stay prone for so long... This would reward micro and erode the overpowered arty, especially when people spam them so early in the game...

**Comment by cjshmyr** [comment]
I think this can be re-opened if the feedback on the recent arty nerf and balance changes warrant it.

**Comment by AMHOL** [comment]
@cjshmyr is this still open for discussion? I think that it was a nice mechanic to make artillery spam counter-able and actually makes using them require at least a modicum of skill to use.

**Comment by abcdefg30** [comment]
I think discussion should take place on the forums, but having an issue open won't hurt either, I guess.

**Comment by Smittytron** [comment]
Artillery has gotten a couple of nerfs recently; minimum range increase and removal of GPS targeting. Even if we decide artillery needs more reduction of power, a chain explosion won't be the way we take it.
