### ISSUE TITLE
Infantry cannot attack anything

### ISSUE THREAD

**Issue by SinineSiil** [OpenRA/OpenRA#10962]
They don't attack not they can't be attacked
Happens in current bleed build but not in release version.
Here's replay https://dl.dropboxusercontent.com/u/26177594/ShareX/2016/03/OpenRA-2016-03-21T211226Z.orarep

**Comment by SinineSiil** [comment]
Nevermind this, all infantry is broken

**Comment by obrakmann** [comment]
Introduced by #10910.

**Comment by Micr0Bit** [comment]
confirmed "They don't attack not they can't be attacked"

**Comment by jtyle6** [comment]
Only exception is attack dog.
