### ISSUE TITLE
TD - Bridge Repair Bug

### ISSUE THREAD

**Issue by fir3w0rx** [OpenRA/OpenRA#10977]
If a vehicle is sitting at the entrance of a broken bridge, that vehicle will explode if the bridge is repaired.

![bridge repair bug 1](https://cloud.githubusercontent.com/assets/18079970/14057794/eb3db38a-f35e-11e5-9d9d-80bbfeb048cb.png)
![bridge repair bug 2](https://cloud.githubusercontent.com/assets/18079970/14057793/eb3cd5aa-f35e-11e5-9e31-eb0d2cdb74f8.png)

**Comment by GraionDilach** [comment]
Duplicate of #9378.

**Comment by epicelite** [comment]
What map is that? Because those bridges are missing a few tiles.

**Comment by GraionDilach** [comment]
@epicelite: They don't. See #6412 and #10971.

**Comment by abcdefg30** [comment]
Closing as duplicate of #9378 here. Thanks for the report though!
