### ISSUE TITLE
TD - Construction Yard Bug

### ISSUE THREAD

**Issue by fir3w0rx** [OpenRA/OpenRA#10976]
Production tab number increments each time CY is redeployed:

![td - production tab number increments if mcv is redeployed](https://cloud.githubusercontent.com/assets/18079970/14057749/e1bee29e-f35d-11e5-9818-588d037b8112.png)

**Comment by GraionDilach** [comment]
I'd call this "Production queue numbers are never reiterated." This happens if you build a warfactory, sell it and build another as well.

**Comment by abcdefg30** [comment]
Reverse duplicate of #15050 (closing this as the other issue has a more fitting title imho).
