### ISSUE TITLE
Starting C&C Causes Crash

### ISSUE THREAD

**Issue by karlsminton** [OpenRA/OpenRA#10970]
Playing red alert doesn't cause this. But upon starting a game of c&c (original) my machine crashes.
It doesn't write to any logs, and I cannot escape it.
It works fine on RA but not c&c.
In my particular case I know this happens when I play a skirmish against bots, but unsure about online.

I'm running windows 10 and if you need any additional info, just let me know.

**Comment by reaperrr** [comment]
What version of OpenRA? Does it happen on every map you try?

**Comment by karlsminton** [comment]
Initially it appeared to be just on Tiberium Dawn, but I've actually found it to happen at random times in startup for RA as well.
It happens at seemingly random points, including on the menu.
I'll confirm my version later - Is this in the foot of the menu?

**Comment by GraionDilach** [comment]
Yes, it's shown on the menu. An exception.log (`Users/username/My Documents/OpenRA`) would be also nice.

**Comment by pchote** [comment]
@GraionDilach:
>  It doesn't write to any logs, and I cannot escape it.

**Comment by karlsminton** [comment]
it appears to be happening on all mods, after playing through a bit longer.
I'm running release-20151224.

**Comment by Mailaender** [comment]
Does it also happen on the latest playtest?

**Comment by pchote** [comment]
There's nothing we can act on here, so closing.
