### ISSUE TITLE
TD campaign: Mission victory / failure music not playing

### ISSUE THREAD

**Issue by Biofreak1987** [OpenRA/OpenRA#10983]
The faction specific mission victory / failure music is missing since the map rules changes.

**Comment by obrakmann** [comment]
I think I can't reproduce that.

**Comment by Biofreak1987** [comment]
Only the GDI victory music appears to be working. GDI failure and Nod victory / failure doesn't play. I've rechecked it with the latest bleed on following maps:

**GDI:**
"Knock out the Refinery"
**Nod:**
"Nookimba's Demise"
"Invasion of Egypt (a)"

**Comment by pchote** [comment]
Confirmed on Knock out the Refinery.

**Comment by pchote** [comment]
Regression from #10535.  It turns out that the two files with unknown hashes in scores.mix are `nod_win1.aud` and `nod_map1.aud`.  We can fix this by patching the global mix database to include these now known hashes.

**Comment by pchote** [comment]
Actually, a better solution will be to ship these files in `bits`.  The win theme is included with the default download (it lives in transit.mix), and its a bit crap that we play music on win but not on loss for people that don't go out of their way to install the music.

**Comment by GraionDilach** [comment]
Just did a check - downloaded transit.mixes already have them - with a local mix database.dat?! O_o

**Comment by pchote** [comment]
They must have been edited in.  That would explain why @obrakmann can't reproduce the issue (assuming he downloaded instead of installing from disk).
