### ISSUE TITLE
[RA] Official Map Pool: Alter Temperal (4 players) - minor balance, aesthetics

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#10980]
[**Temperal, current**](http://resource.openra.net/maps/7233/), (4 players)

Changes:
Add actors and debris to out-of-reach and vacant areas.
Slightly tweak the north players poor economic start position.

[**Temperal, altered**](http://resource.openra.net/maps/9456/), playtested. No issues encountered.

![temperal compare](https://cloud.githubusercontent.com/assets/2715583/14062312/c01c9dba-f39a-11e5-9302-f235c281572c.png)

![temperal compare](https://cloud.githubusercontent.com/assets/2715583/14062315/c9ef1d0e-f39a-11e5-91c5-d75bd5147692.png)

**Comment by epicelite** [comment]
Booo! I want muh hilltops back! Where do you expect me to chrono my MCV to now?
