### ISSUE TITLE
explosion effects/warheads

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#10997]
I have to register separately missiles mammoth explosion effect ground and air. considering that he primary and secondary weapons. Of course I can not make a third type of weapon for air with its effects. it is possible to register the effects of explosions for every type of target?

**Comment by pchote** [comment]
> Of course I can not make a third type of weapon for air

Why not?

**Comment by yaaaaa** [comment]
How can I register third weapon?

**Comment by pchote** [comment]
The same way you register the first two.  OpenRA lets you define as many weapons as you want.

**Comment by yaaaaa** [comment]
Primary
Secondary
tertiary?
quaternary, quinary, senary, septenary, octonary, nonary, and denary?

**Comment by GraionDilach** [comment]
```
ramka:
	[...]
	Armament@primary:
		Weapon: RamkaAccGun
		UpgradeTypes: eliteweapon
		UpgradeMaxEnabledLevel: 0
		UpgradeMaxAcceptedLevel: 1
	Armament@elite:
		Weapon: RamkaAccGunE
		UpgradeTypes: eliteweapon
		UpgradeMinEnabledLevel: 1
	Armament@primary_var1:
		Weapon: RamkaInAccGun
		UpgradeTypes: eliteweapon
		UpgradeMaxEnabledLevel: 0
		UpgradeMaxAcceptedLevel: 1
	Armament@eliteprimary_var1:
		Weapon: RamkaInAccGunE
		UpgradeTypes: eliteweapon
		UpgradeMinEnabledLevel: 1
	Armament@primary_var2:
		Weapon: RamkaInAccGun
		UpgradeTypes: eliteweapon
		UpgradeMaxEnabledLevel: 0
		UpgradeMaxAcceptedLevel: 1
	Armament@eliteprimary_var2:
		Weapon: RamkaInAccGunE
		UpgradeTypes: eliteweapon
		UpgradeMinEnabledLevel: 1
	Armament@primary_var3:
		Weapon: RamkaInAccGun
		UpgradeTypes: eliteweapon
		UpgradeMaxEnabledLevel: 0
		UpgradeMaxAcceptedLevel: 1
	Armament@eliteprimary_var3:
		Weapon: RamkaInAccGunE
		UpgradeTypes: eliteweapon
		UpgradeMinEnabledLevel: 1
```

```
StormboltBolt:
	ReloadDelay: 60
	Range: 6c256
	MinRange: 0c001
	Report: sbltfir1.wav
	ValidTargets: Air, Ground, Water
	Projectile: TeslaZap
		BrightZaps: 0
		DimZaps: 3
		Palette: heroicra2aiexp
		Image: litninga
	Warhead@1Dam: SpreadDamage
		ValidTargets: Air
		Spread: 64
		Falloff: 100, 50
		Damage: 37
		DamageTypes: DefaultDeath, ElectroDeath
		Versus:
			None: 30
			Plate: 30
			Hero: 30
			Light: 20
			Medium: 40
			Harvester: 30
			Wood: 70
			Concrete: 75
			CYArmor: 50
			TechArmor: 75
			Tier3: 66
			ShipArmor: 66
			Electric: 85
	Warhead@2Dam: SpreadDamage
		Spread: 64
		Falloff: 100, 50
		Damage: 25
		DamageTypes: DefaultDeath, ElectroDeath
		Versus:
			None: 30
			Plate: 30
			Hero: 30
			Light: 20
			Medium: 40
			Harvester: 30
			Wood: 70
			Concrete: 75
			CYArmor: 50
			TechArmor: 75
			Tier3: 66
			ShipArmor: 66
			Electric: 85
	Warhead@2Eff: CreateEffect
		Explosions: stormboltexp
		ExplosionPalette: rookiets2exp
```

Both are possible.

**Comment by yaaaaa** [comment]
Thanks!!

**Comment by GraionDilach** [comment]
If a trait/property can have multiple instances, then it doesn't matter what you write after @ as long as it's unique. You can even call them whatever you like.

**Comment by yaaaaa** [comment]
whether it is possible to add a delay when switching from one weapon to another?

**Comment by GraionDilach** [comment]
Set up a shared `AmmoPool` between the weapons with `SelfReloads: yes` and use that.

**Comment by yaaaaa** [comment]
> Set up a shared AmmoPool between the weapons with SelfReloads: yes and use that.

Ammopool: 
Armament@PRIMARY:
Weapon: 120mmDual
LocalOffset: 900,180,340, 900,-180,340
MuzzleSequence: muzzle
SelfReloads: yes
Armament@SECONDARY:
Weapon: MammothINFMissiles
Armament@TETRIARY:
Weapon: MammothAAMissiles
LocalOffset: -85,384,340, -85,-384,340
LocalYaw: -100, 100
MuzzleSequence: muzzle
SelfReloads: yes
Armament@QUATERNARY:
Weapon: MammothMissiles 
LocalOffset: -85,384,340, -85,-384,340
LocalYaw: -100, 100
MuzzleSequence: muzzle 
SelfReloads: yes

??

**Comment by GraionDilach** [comment]
https://github.com/OpenRA/OpenRA/wiki/Traits-%28playtest%29#ammopool
https://github.com/OpenRA/OpenRA/wiki/Traits-%28playtest%29#armament

RTFM. If you can't comprehend it, get a new brain then. I'm not gonna spoonfeed toddlers here.

**Comment by yaaaaa** [comment]
Thanks! its work! but 120mm start reload too...

**Comment by GraionDilach** [comment]
Because you didn't specified a different `AmmoPoolName` on `120mm`, ffs. Again, RTFM.
