### ISSUE TITLE
Air units and its place

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#11000]
![tuer5rfwx6c 1](https://cloud.githubusercontent.com/assets/11130958/14109702/31122070-f5e5-11e5-9ab1-4f60e9726f80.jpg)
![67jgt9uz2q0 1](https://cloud.githubusercontent.com/assets/11130958/14109732/4e77feaa-f5e5-11e5-8337-67a1e241f877.jpg)
which parameter is responsible for the return Orca Plane to the its base place?
how can I learn Orca Helicopter from TD mod return and land in base place after shooting, like Orca Plane from RA2 mod?

**Comment by GraionDilach** [comment]
https://github.com/OpenRA/OpenRA/wiki/Traits-%28playtest%29#returnonidle

**Comment by obrakmann** [comment]
@yaaaaa: This issue tracker is meant for reporting software defects. It is not a support site. Please consult our wiki (and especially http://wiki.openra.net/traits) first if you have questions. If that does not help, the best place to ask for help is probably our forum or IRC channel.

**Comment by yaaaaa** [comment]
Understud, Thanks!

**Comment by abcdefg30** [comment]
You can also always ask questions on [the modding section of Sleipnir's Stuff](http://www.sleipnirstuff.com/forum/viewforum.php?f=83).
