### ISSUE TITLE
Tiberian Sun tunnel passing concept

### ISSUE THREAD

**Issue by StrikerASD** [OpenRA/OpenRA#11003]
Hi there.

I have some conceptual thoughts about Tiberian Sun and its tunnel passing issue.
Maybe it will bring some new light on a problem, or maybe ideas described here has been already on the table.

I will divide the whole tunnel passing into events. So here we go.

Event one: Unit is approaching the tunnel and when it does, there is a graphical effect on its passing. The shadow casts on that unit.

Event two: The unit is under tunnel and it obviously dissapears. There should be a graphical effect for that event. 

Event three: The map should have some maybe scripted spots that the units visualy turn from normal  look to dots. The dots should be green for friendly and red for enemy. And in that case when friendly units will approach enemy units in the tunnel, the effects of gunfire or explosions are not visible too. How do we do that? By scripts? How we can change the behaviour of certain spots on the maps? Is it like collectable crates? It's definetly not an easy part for a programmer.

Event four: Units are emerging from tunnel, so the dots dissapears and the unit is visible with shadow casting on it. So we have two events. The dot dissapears, the unit pops in it's place. Maybe there is a way of fluent passing from dot to normal look like warping or something like that?

Event five: The unit exits tunnel and the shadow on the unit is no more.

I know it's complicated to implement, maybe i even missed something. I don't know that, i'm not the programmer. It is simply a concept that i have in my mind. I hope this will help in any way to improve TS mod.

**Comment by pchote** [comment]
I've outlined a skeleton of how to implement tunnels in #6410.  It's relatively straightforward to implement, but really far down the priority list.

**Comment by StrikerASD** [comment]
Oh. Shame that this is not a priority, but i understand that are some higher priority issues/features to take care off. 

Cheers
