### ISSUE TITLE
Randomly at some games, cannot attack other units or attack-move

### ISSUE THREAD

**Issue by vizcay** [OpenRA/OpenRA#11010]
I've been playing with a friend like 6 games.. game 5 something strange happened, I wasn't able to "attack", let me explain:

- When I pressed "A" to attack move the cursor and line didnt' changed to red.. It was like just moving.
- When an enemy unit appeared I wasnt able to press right mouse to attack directly.. I was like I was selecting the other players unit.
- No, we werent on a team. It was a 1on1 game.

Ok.. strange, we played game 6 and every back to normal. Then I try to play an online game with some dudes I don't know and the same thing happened, the strange thing that ther others didn't have the same problem.

Running version 24/12/2015 on Ubuntu Linux.

**Comment by Mailaender** [comment]
Were engineers, medics or other weaponless units in the same attack group?

**Comment by vizcay** [comment]
@Mailaender no, I realized of the problem at the very beginning.. I usually send my firsts soldiers to scout with A + right click so if they engage if see some enemy troops. Didn't have any engineers of something at that point for sure.

The replays are useful? I can attach them..

**Comment by Mailaender** [comment]
Does it also happen in the latest http://www.openra.net/news/playtest-20160403/?

**Comment by vizcay** [comment]
@Mailaender havent downloaded that one.. it isn't something that hapenns all the time.. it happened to me 2 times out of 10 (never to any of my friends), so its random (and not easy to debug). But I've opened the ticket so others will find it and also post here if it is a general issue.

**Comment by GraionDilach** [comment]
You should, because this sounds like a duplication of #9851 at first and that one got fixed within the playtest.
