### ISSUE TITLE
.lua support powers doesnt include nuke power

### ISSUE THREAD

**Issue by ThisBlunt** [OpenRA/OpenRA#11011]
I was looking through https://github.com/OpenRA/OpenRA/wiki/Lua-API and it doesn't seem to show support powers such as nukepower or iron curtain.powers to use. It would be nice to have them as a reference instead of me manually finding out how to use these options.

**Comment by abcdefg30** [comment]
Added `Ion Cannon` and `Nuke` in #11030.

You can already do `Iron Curtain` by manually granting a timed upgrade to the actor you want to be IC'd.

**Comment by ThisBlunt** [comment]
I'm more concerned with a launching a nuke
