### ISSUE TITLE
There's no way to run ORA on Windows 10

### ISSUE THREAD

**Issue by hawkao** [OpenRA/OpenRA#11020]
I can't run it on my Windows 10 PC. My log files below:
(exception)
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: No suitable renderers were found. Check graphics.log for details.
   於 OpenRA.Game.Initialize(Arguments args)
   於 OpenRA.Program.Run(String[] args)
   於 OpenRA.Program.Main(String[] args)

**Comment by Biofreak1987** [comment]
Isn't NT 6.2.9200.0 Widnows 8 and not 10?

**Comment by abcdefg30** [comment]
Could you please attach your `graphics.log`, too?

**Comment by GraionDilach** [comment]
There definitely is a way to run OpenRA on Windows 10 otherwise i couldn't mod it at all. Do you still use the Microsoft graphics drivers for your GPU?

**Comment by epicelite** [comment]
I'm on Win 10 and run ORA no problem. So its a problem on your end I guess?

**Comment by RockyTV** [comment]
@Biofreak1987 like people say, Win10 is a "skin" for Windows 8. I don't know why they did it, but until something is set in the App.config file, Windows 10 users will get flagged as Windows 8. Not much of a problem.

I run OpenRA just fine on Windows 10, so, try updating your graphics drivers.

**Comment by pchote** [comment]
We can't do anything to help without the info in graphics.log.

I expect that will say that you need to install vendor-provided GPU drivers that include proper OpenGL support.

**Comment by LipkeGu** [comment]
@hawkao: you should install as Pchote says an vendor-provided GPU Driver for Windows 10
Microsoft doesnt provide OpenGL in there shipped Drivers. Yes they are also from the Vendor but limited. Can you Tell us what GPU Driver you are using (Name of the Device and Vendor)

**Comment by pchote** [comment]
There's nothing more we can do here, so closing.
