### ISSUE TITLE
Transport with Demo Truck inside should produce a thermonuclear explosion on death.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#11037]
Yes?

**Comment by StexoO** [comment]
:+1: 
It would be fun but if a transport doesn't have the same health/speed as a demo truck then these "nuke transport attacks" would be really devastating because all water units/ammunitions can be dodged by transport ships.

**Comment by HenrytheSlav** [comment]
:+1: I never thought about it, but hiding demo truck in your base in transport is actually smart. But to comply with what @StexoO said, we should reduce the damage by 50-75% (it is after all just small tactical warhead inside a strudy metal transport.

**Comment by Smittytron** [comment]
Closing this one after discussion in Discord. There was not enough support and the conversation brought up several balance related edge-cases.

**Comment by pchote** [comment]
I think the best option here is for someone to put together a test map with this implemented and get feedback from the active teamgame community. If it gets general support there then I wouldn't necessarily object to adding this.
