### ISSUE TITLE
"Team colors" affecting (superweapon) countdown timers

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#11048]
(Playtest 20160403)
When "team colors" are enabled the coutdown timers of super weapons (like GPS satelite) gets colored in team colors as well. So you could see **multiple** GPS **countdown timers** all **in the same** red **color.**

I say this is not helping since you usually want to know specifically (in order to prevent it) who's building it. Disabling team colors during game is an option (but an additional step) and many (new) players may not know how to do it (shortcut).

It would be usefull if **both pieces of information** would be represented: 
- TEAM "membership" (color) and 
- PLAYER COLOR.

Example:
- Ally: GPS countdown 3:00
- Enemy: GPS countdown: 2:15
  (both in their colors)

Additionaly words **"Ally" and "Enemy" could be team colored** (to distinguish multiple teams).
... or "Enemy (Team 2)", "Enemy (Team 3)" ...

Best regards.

**Comment by pchote** [comment]
The purpose of the team colors is to help distingush players who have colors that are similar to others, or to the terrain.  In its current state you can flick between modes to distingush who is who. Removing the timer colors would break that and make them inconistent with the rest of the ui colors which we have *finally* made internally consistent. :-1: in my opinion, especially for the sake of the horrible and hacky GPS.

**Comment by pi99y** [comment]
Don't you think that the suggested syntax:
* **Enemy (Team 2):** _GPS countdown 2:33_
* **Ally:** _GPS countdown 1:22_

where the **bold parts** are printed in TEAM COLOR and _the rest_ in PLAYERS COLOR would not break the team-color-consistency while still be more informative?

**Comment by pchote** [comment]
To be honest, I don't. That would add a lot of visual clutter all the time to solve a problem that only happens occasionally.

**Comment by pi99y** [comment]
What about adding the player's nickname to the otherwise team colored counter?
* pchote: GPS countdown 1:39

**Comment by abcdefg30** [comment]
That was already rejected: #6282

**Comment by GraionDilach** [comment]
I was playing the original Dota (on Warcraft 3) on the other day and I noticed something - even if you enable their equivalent of `PlayerStanceColor`, the game will use the original colors in the text messages mentioning players. So while I can see it looks weird (Warcraft 3 only uses text messages for chat and some events anyway), I also like the idea of reopening #6282.

**Comment by pchote** [comment]
A better solution would be to drop the text timers completely, replacing them with a row of mini icons with player/stance color either as a border or tint, and the owner name in the tooltip.

**Comment by PunkPun** [comment]
This is the main reason why I don't use PlayerStanceColors. Knowing who's the owner of a superweapon is cruitial
