### ISSUE TITLE
Fatal Error when starting OpenRA

### ISSUE THREAD

**Issue by justinmarcusmiller** [OpenRA/OpenRA#11043]
When starting OpenRA, I get a white screen and then a popup saying that there is a fatal error. 

I am currently running playtest-20160403. Release-20151224 works fine.

**Here are the contents of my exception.log:**

Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenRA.Manifest..ctor(String modId)
   at OpenRA.ModData..ctor(String mod, Boolean useLoadScreen)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by pchote** [comment]
The exception message indicates an issue with the installed files. Did you install on top of an older version, or to a separate directory?

If you installed on top then try uninstalling, removing any stray files, then reinstalling. If in a separate dir to the release, then launch the release and switch to the mod chooser before quitting and rerunning the playtest.

Some heavy handed virus scanners also like to quarantine important files, so you may want to check that too.

**Comment by justinmarcusmiller** [comment]
Thanks! That fixed it.

I had the playtest installed in a different folder. I uninstalled the release version and then reinstalled the playtest in the original OpenRA folder.

Thanks again!
