### ISSUE TITLE
Can't give attack orders via standard left-click on enemy in left-click orders control scheme

### ISSUE THREAD

**Issue by LavenderMoon** [OpenRA/OpenRA#11042]
On playtest-20160403, left-clicking on an enemy will select the enemy rather than attack it using left-click orders in all included mods. This is despite the appropriate cursor (attack or C4) being displayed over the enemy. Force fire works. Right-clicking will deselect as usual. Right-click orders works as normal.

**Comment by LavenderMoon** [comment]
Probably related to #11041.

**Comment by pchote** [comment]
This is indeed the same, so closing as duplicate. Thanks for the report!
