### ISSUE TITLE
GPS mouse tootltip reveals structure

### ISSUE THREAD

**Issue by derestle-htwg** [OpenRA/OpenRA#11047]
If the fog of war hides a building but as an allied i have GPS i can see on the tooltip what kind of Building it is.

**Comment by obrakmann** [comment]
Please show a screenshot of what you mean. I just tried to reproduce it and don't get a tooltip for building icons.

**Comment by derestle-htwg** [comment]
One shows how it should be. a Discovered Building is shown with tooltip under the fog of war.
the second Screenshot shows what kind of building it is if it has been marked on the map by GPS
I hope i said what i wanted to say :-D

![openra-2016-04-05t211820z](https://cloud.githubusercontent.com/assets/5612007/14298442/3c6a8ba6-fb85-11e5-8e70-56a7659bd268.png)
![openra-2016-04-05t211947z](https://cloud.githubusercontent.com/assets/5612007/14298441/3c6a96c8-fb85-11e5-920d-a9f86a3c082f.png)

**Comment by jaZzKCS** [comment]
Hot damn, that's serious.

**Comment by pchote** [comment]
I can't reproduce this either.  I see from the screenshots that you have the debug menu enabled.  Did you use any of the visibility-related cheats before this?  They really mess up the world state, so I wouldn't be at all surprised if they could trigger this specific behaviour.

**Comment by StexoO** [comment]
Yes, playtest-20160403
![gps cheat](https://cloud.githubusercontent.com/assets/8930382/14718353/75fb5440-07f6-11e6-898d-e6c220bf6d9f.png)

**Comment by pchote** [comment]
Introduced by 3c930c3ef9194eeaf7cbe2145724acf598e383fc in #10324.

**Comment by pchote** [comment]
The `fa.RefreshState()` populates the `TooltipInfo`, which is what causes the tooltip to be shown.

**Comment by RoosterDragon** [comment]
Perhaps `fa.RefreshState()` should also be guarded by `if (fa.HasRenderables)` to prevent it updating until the frozen actor has been revealed?
