### ISSUE TITLE
Can't deploy MCV, send vehicles to service depot or land aircraft in left-click order mode

### ISSUE THREAD

**Issue by riiga** [OpenRA/OpenRA#11041]
It seems the latest playtest has a bug where I can't use the deploy or similar action on a vehicle or building, it just selects the building instead. I was able to deploy the MCV using the keyboard shortcut instead, but this makes the game quite unplayable for the rest.

I am using classic left-click orders and have verified it working with right-click orders.

**Comment by pchote** [comment]
I expect this will be caused by #11008.

**Comment by pchote** [comment]
`UnitOrderGenerator.InputOverridesSelection` actually returns the exact opposite of what it claims (it returns *false* if the input overrides selection.  Fixing that re-breaks the guard case, of course.

The left-click orders code appears to completely ignore `world.OrderGenerator`, and just hardcodes `UnitOrderGenerator`.  It's no wonder it is so broken.
