### ISSUE TITLE
Subs not attackable

### ISSUE THREAD

**Issue by derestle-htwg** [OpenRA/OpenRA#11046]
A Submarine can't be attacked anymore by a helicopter or a land unit. 
a Gunboat can attack it.

**Comment by GraionDilach** [comment]
Was the submarine cloaked when you were unable to attack it? If yes, that's intended, you have to get the submarine to surface level (decloak) to attack it with most weapons.

**Comment by jtyle6** [comment]
I was playing with the playtest, and my missile sub's won't being attacked by the enemy.
Plus, there surfacing.

**Comment by derestle-htwg** [comment]
Yes, thats true.

Submarines on the surface can't be attacked by units. Even if i try to let them attack the submarine with CTRL the submarine won't be hit.
On the last stable release this issue wasn't there. So i think this should be labeled regression.

**Comment by reaperrr** [comment]
I did some quick testing and granting/revoking upgrades via `Cloak.WhileCloakedUpgrades` seems to work fine. The problem must be something else.

**Comment by obrakmann** [comment]
Introduced with f46185b85f458f44f32787f481983d91575d6808 in #9808. I'm trying to work out what part of it broke it now.
