### ISSUE TITLE
Audio feedback when queuing production

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#11052]
(Playtest 20160403)
Previous versions of the game played an immediate "building" or "training" sound when you queued multiple units or buildings for production. 

Example: Clicking on rifle infantry and immediatly on the rocket infantry (queuing it) would play "training" sound twice. This gave an audio confirmation of your action.

Now the "training" sound of the queued unit plays only when the unit actually starts producing (so much later).

While this could be intentional it seems less usefull to me.

**Comment by Phrohdoh** [comment]
I am a bit torn on this.

> This gave an audio confirmation of your action.
Is true and is a good thing but on the other hand you are not training this actor yet.

**Comment by pi99y** [comment]
The main problem I think is that a later "building/training" sound dosen't help at all... Especially for buildings (since you have to place the previous building first and since it takes so much longer so the next "building" sound might seem a bit random at that time)

**Comment by obrakmann** [comment]
This was actually talked about in the PR (#10570). Moving the notification was meant to deconflict it with the "Insufficient funds" warning, which otherwise would play at the same time. Unfortunately, now we get "Building" and "Production complete" playing at the same time, which also sucks. This surely needs more work.

**Comment by anjew175** [comment]
You may not be training the actor yet but the fact you heard the one before it complete lets you know and the fact you clicked the button and received feedback lets you know that your changes have made effect or you have added more items to be made. With out this i have to double check what im producing. 

The sounds may be annoying to spectators but for players these auditory cues are essential. The "training" sound is annoying as directly before it, a "completed" sound is played.

If anything, a sound for when you arent producing from a building should be played

**Comment by pchote** [comment]
Why didn't we add a delay to the insufficient warning notification instead?  Trigger an internal countdown when production is started, and then if funds are still low after ~5 seconds *then* play it.

**Comment by abcdefg30** [comment]
> Why didn't we add a delay to the insufficient warning notification instead? Trigger an internal countdown when production is started, and then if funds are still low after ~5 seconds then play it.

That's what I suggested but it was rejected by most of the reviewers.

**Comment by abcdefg30** [comment]
But tbh, I somehow even like this behaviour more.

**Comment by LipkeGu** [comment]
btw There is already a PR (or Two) about this... issue
