### ISSUE TITLE
TD Visceroids

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#11056]
In TD playtest version 20160403 Visceroids don't attack anything when spawned from Chem Troopers. (Currently untested if it is spawned via map.)

Shown in replay example at 9:20 and onward.

https://www.dropbox.com/s/n46hvd1ag7a5hkx/OpenRA-2016-04-05T194601Z.orarep?dl=0

**Comment by obrakmann** [comment]
Works fine with pre-placed viceroids, but also happens with regular infantry dying in tib fields, doesn't need chem troopers.

I already checked whether the owner was assigned correctly, but they do get spawned with Owner set to Creeps, so something else broke.

**Comment by AoAGeneral** [comment]
Did some more games and the visceroids actually did start attacking in those games. However, im scratching my head in that replay as to why they didn't attack.

**Comment by reaperrr** [comment]
Haven't looked at the code, but maybe this is another case where some trait lookup needs to be done from `INotifyCreated` instead of ctor? Would explain why it sometimes works and sometimes not.

**Comment by pchote** [comment]
I bet that this is caused by a change in the AutoTarget or other attack logic.  See also #11156.

**Comment by pchote** [comment]
I wasn't quite right, but debugging along those lines revealed the real problem.  The Aggressive Tendencies map has a bad player setup, with the Creeps player not considering the human players as enemies. *yay for asymmetric teams*.

We should check that there aren't other maps hiding the same issue.

**Comment by AoAGeneral** [comment]
Oh wow that is weird O.o Never considered that a map property would cause things like that.
