### ISSUE TITLE
Game drops to crawl speed 

### ISSUE THREAD

**Issue by Levan7** [OpenRA/OpenRA#11061]
I created a map and noticed that the game's speed drops to crawl speed online.
Offline i have not experienced any issues, well i had a issue when there were no ore mines but after i added 7 or 8 the frame game started to function correctly can anyone help me trouble shoot this issue.
Is this because of this map or something else.

This is the map
http://resource.openra.net/maps/11468/

**Comment by GraionDilach** [comment]
Could be. That map is quite chokey and the pathfinder might indeed be a problem. Keep in mind that in MP, all players will slow down to the one with the worst config.

**Comment by Levan7** [comment]
@GraionDilach 
Thank you for the reply are we talking about PC specs or connection speed, Does this game has log files that i can share or check ?

**Comment by Levan7** [comment]
Finally the game crashed, well the game client was working but the game crashed it froze. 
Here is the reply if it helps i don't think so.
https://www.sendspace.com/file/9tc9mo

here is the debug log output 
http://paste.ubuntu.com/15659956/

looks pretty useless

**Comment by cjshmyr** [comment]
Was there anything in `exception.log` after it crashed?

**Comment by Levan7** [comment]
@cjshmyr 

This is the only entry i see but the hash does not match
http://paste.ubuntu.com/15660457/

**Comment by HenrytheSlav** [comment]
I dare to guess a pathfinfing issue due to middle being likely clogged and pathfinder having issues. Our pathfinding is definitely not perfect and with such bottlenecks performance can drop significantly.

**Comment by Mailaender** [comment]
Duplicate of https://github.com/OpenRA/OpenRA/issues/12938 and https://github.com/OpenRA/OpenRA/issues/12435.
