### ISSUE TITLE
TD Selling = Mass Engineers

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#11069]
Selling simple structures such as a power plant gives one engineer. Selling a refinery gives about six engineers. 

This is pretty badly broken in which the enemy can sell out a bunch of structures (Even early on) and do quick capturing. Which then can be sold for more engineers and capture more stuff.

https://www.dropbox.com/s/2bpinhzcf1d1zkj/OpenRA-2016-04-08T055654Z.orarep?dl=0

Official map: Two Ponds

**Comment by anjew175** [comment]
It seems the chance to get an engineer has been fucked with as it is possible to 5 riflemen and 6 engineers from a refiniery

**Comment by abcdefg30** [comment]
This is also present in the other mods, see #11045.
On bleed this should be already fixed by #11053, thanks for the report though. :)
