### ISSUE TITLE
idea - let servers to use custom maps.

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#11063]
Lot of gamers has'nt white IP, but want to play with selfmaded maps together.

Now, If they connect to official ORA server and try to use custom map, server do not load the map.
if the servers will download custom maps, it will be a very useful feature

**Comment by ihptru** [comment]
It's already implemented in the latest playtest.

**Comment by abcdefg30** [comment]
It should also already be possible on the last release, the server just needs to sync with the resource site.

**Comment by yaaaaa** [comment]
=)
