### ISSUE TITLE
Add ranks to paratroopers

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#11066]
poll : http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=19535

this is more of a "polish" instead of a "balance"-ticket,
we could either spread the ranks randomly everytime a paradrop is happening ... or have them set in a specific order which never changes ... here a example : 
- E1 - 4th rank (Star)
- E2 - 3rd rank (3 Stripes)
- E2 - 2nd rank (2 Stripes)
- E1 - 1st rank (1 Stripe)
- E1 - unranked

(i personally would enjoy the "random" assignment on every drop ... but im indifferent on the implementation)

**Comment by GraionDilach** [comment]
Spawning them with random ranks is imba and stupid, Mr Balance Expert. Giving them a starting rank can work, albeit noidea how will it conflict with the spy-infiltrate-barracks-veterancy.

**Comment by Micr0Bit** [comment]
you probably dont understand this ... with "random ranks i mean the "ranks" (aka only 1 unranked , 1 stripe ...etc) get randomly assigned on the team ... which "could" leave you with a 1-star E2  ... 1 stripe E2 ... etc. if you are lucky (and that isnt unbalanced)
any i have i've never claimed that im a "Balance Expert" ... 

i really hope you just finish you mod and then piss off ... cause i really despise you and your shitty attitude ... the only reason why you are here , is because you feed off of openra (everyone knows that) ... having actually programmers actually work on your mod , and the only thing you do is ... keeping sure everything is running a direction so your own crap isnt compromised
apart from that , you spit your poison randomly on issues/threads/whatnot because you think you know everything better (or more about it) but you only show one more time ... that you dont even try to be different (before you got into OpenRA) 

congrats

**Comment by GraionDilach** [comment]
Random != different. Different can work though. Sorry then, I thought random at each drop.

**Comment by SoScared** [comment]
What about trying out an overall 1 ranked paradrop squad in the next playtest? The drop would be a bit stronger with two 1-ranked rocket troopers, but the real benefit I imagine would be aesthetic. Would look gorgeous.

**Comment by Mailaender** [comment]
You could also make this a faction specific buff inspired by http://cnc.wikia.com/wiki/Airborne#American_Airborne

**Comment by MustaphaTR** [comment]
This is addressed by #12739.
