### ISSUE TITLE
TD Custom Map Tabs

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#11070]
When uploading a custom map from the resource center into the folder no custom tab pops up.

However, if I put it into the Playtest folder map directory directly, it does not pop up with a custom tab but the map shows up in official maps tab.

**Comment by abcdefg30** [comment]
We now version our map directory. Did you try putting the custom map(s) into `maps\cnc\playtest-20160403`?

**Comment by AoAGeneral** [comment]
That is a confirmed. Putting them into the test directories works. Does this mean all maps must be moved over to the new version manually?

**Comment by abcdefg30** [comment]
Yeah, you need to do that.
