### ISSUE TITLE
Mammoth Tank Speed Buff

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#11077]
Increase Mammoth tank speed from 42 to 50

It seems like every attack done with Mammoth tank nowadays is a guaranteed suicide run. When target fired upon the tank simply can't get away in time. Pulling back damaged Mammoths in time for health regeneration isn't working. The ability of crushing walls in the playtest is great but only accounts for use in specific situations. 

For comparisons, the Soviet MAD tank moves at speed 54. Zombies at 42 :)

The current Mammoth Tank is a sleeping beast.

**Comment by AoAGeneral** [comment]
Considering that in TD the mammoth speed is 56 and performs rather well, might want to look at testing the Mammoth tanks missile fire. See what its like if it fires cannons and missiles at all targets. This sort of change might actually make the mammoth a lot more dangerous then what it is now.

**Comment by HenrytheSlav** [comment]
We can return to this now, sicne feature freeze is over. I feel like 50-56 seems okay. I could make a PR after this gets decided. Maybe introduce a poll on forum? It is a balance change after all.

**Comment by SoScared** [comment]
I've been fiddling a bit with the 50 speed on a modded map. The reason I like this speed is that it's fast enough to allow for better damage pull-backs (including IC and wall crush play) and can follow infantry squads better but slow enough to not simply become a heavy tank upgrade.

**Comment by MustaphaTR** [comment]
#12040 has merged, i think this can be closed.
