### ISSUE TITLE
TD SAM Site and Advanced Guard Tower delay before building cost applies

### ISSUE THREAD

**Issue by AidanTallon** [OpenRA/OpenRA#11075]
When building these, the building process starts but money isn't taken from the player until construction is about 1/8th done. Production cannot be put on hold during this time, instead the building is cancelled, which made me think this isn't working as intended.

Possibly related to [#11073](https://github.com/OpenRA/OpenRA/issues/11073)?

**Comment by obrakmann** [comment]
This is related to the `CustomBuildTimeValue`. When you remove that, it works as expected, also the "Building..." notification (#11073) is then played.

**Comment by obrakmann** [comment]
That actually already happens in the current stable release.

**Comment by abcdefg30** [comment]
Fixed by #15387.
