### ISSUE TITLE
Add a checkbox for the data collection to the installer

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#11071]
or add some kind of popup when the game first starts as suggested [in the comments section](http://www.openra.net/#comment-2611870483).

I think adding a `[x] Allow OpenRA to collect anonymous statistics (about xyz)`
(checked by default) to the installer is a good idea.

**Comment by pchote** [comment]
IMO this is a completely disproportionate amount of work to address unreasonable demands from people who we have probably already lost as players.

This won't help under OSX or Linux that don't have installers that we can add checkboxes to.

**Comment by obrakmann** [comment]
I also think this is putting too much focus on the topic. The way we've been approaching this is open enough. We've clearly stated what we're doing and our intent in the news post (and I guess we'll copy that section over to the news posts of future PRs as well the the release's), and people have the ability to disable it in numerous ways, and it's also again spelled out in the settings dialog itself.

A popup right in your face on the first start also leaves a very bad first impression of the game. There's a reason why people hate nag screens. Worse, the popup wouldn't even have anything to do with the core of the game, it would just be distracting.

As for the installer idea: what pchote said. It would only work on Windows (while most of the privacy-conscious people are probably running Linux) and would involve way too much work to teach the installer to locate the support dir and write to settings.yaml, without clobbering the existing one. :-1:
