### ISSUE TITLE
20160403 Playtest - Spectator chat labels almost indistinguishable

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#11078]
```
SoScared (Spectator): I can chat with everyone - specs, players, (dead) players.
SoScared (Spectators): My chat is only visible to other spectators.
```

Might seems clear enough here but when you're in-game, it's easy to make a mistake when there's a lot of action and excitement involved. Also different chat colors might be a bit difficult to read in specific situations.

**Comment by SoScared** [comment]
(Spec. Chat) could be a better alternative.

**Comment by cjshmyr** [comment]
Personally I'd opt for putting it before the player's name (w/ square brackets), and we should fix that too for team chat.
