### ISSUE TITLE
alt-tab on linux , losing control over the UI

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#11099]
OpenRA 20151224
Debian GNU/Linux 8 (jessie) 32-Bit , Gnome 3.14.1

on linux (for me it seems) ... when i try to alt-tab (whilst ingame) although there isnt any other program running beside openra , almost every hotkey stops working including "Esc" all the  "F-Keys" and "Stance-Hotkeys"  (Enter works) apart from that , i lose the ability to do stuff with "right click" such as giving attack/move-order for example

10:52:58        +chrisf | it's an sdl bug , tap alt again and everything will start working

**Comment by ihptru** [comment]
I met this bug too.

**Comment by Micr0Bit** [comment]
some guy today ... could be related but cant say for sure because he left immediately

![cantplay](https://cloud.githubusercontent.com/assets/9139965/14691408/6288a62e-0751-11e6-9b2f-221be2981e7d.png)

**Comment by Micr0Bit** [comment]
this issue seems to be not relevant anymore

**release-20170527** 
**Debian Stretch (Unix 4.9.0.3)**

@ihptru : is it still relevant for you ?

**Comment by Micr0Bit** [comment]
alright , because its fixed for me and @ihptru doesnt react im closing this
