### ISSUE TITLE
Utility crash when trying to make check

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#11109]
Ever since #11058 was merged, I'm getting a weird utility crash when trying to `make check`. Something about

> method `get_GLVersion` in type `OpenRA.Platforms.Null.NullGraphicsDevice` (...) has no implementation

Since the utility crashes on that, I can't run style checks locally at the moment.

Cleaning and refetching dependencies didn't help.

**Comment by pchote** [comment]
The null renderer doesn't exist any more, so your working dir can't be clean.

**Comment by reaperrr** [comment]
Right, but the reason why it wasn't clean is that I copied it there since the windows version of make check also complained when it was missing. Looks like the check wasn't removed from make.ps1 when `Platforms.Null` got removed.
