### ISSUE TITLE
Reaperr, have you considered a recreation of Return of the Dawn?

### ISSUE THREAD

**Issue by skeights** [OpenRA/OpenRA#11100]
I love this mod, and as such should claim the mantle of TS based go to TD Mod. Ps I love this impl for original TS Engine.

**Comment by reaperrr** [comment]
I'm thinking about it, but no promises.

**Comment by skeights** [comment]
Good stuff:) I played a game on it the other day 8 players in total on a map called Tread carefully. It lasted an intense 6 hours and left the map completely scarred. It's things like this that make the mod great.

**Comment by obrakmann** [comment]
I think this can be closed now.
