### ISSUE TITLE
Fix grenadier damage vs heavy and concrete

### ISSUE THREAD

**Issue by anjew175** [OpenRA/OpenRA#11103]
Currently the grenadier does 5 damage per hit on ALL defense structures because it uses the heavy armor class (the only structures that do)
The grenadier also does its full damage to concrete walls because concrete isn't defined in the weapons

**Comment by pchote** [comment]
Finer balancing discussion aside, doing 20x more damage against walls than a guard tower is clearly a bug.

**Comment by cjshmyr** [comment]
Probably a result from defense armor changing from wood -> heavy. The concrete damage is probably intentional so heavy can be tweaked.

**Comment by cjshmyr** [comment]
This also has a side effect of grenades being better against tanks

**Comment by anjew175** [comment]
Give concrete damage values then make defense structures concrete?

**Comment by pchote** [comment]
On a related note: we should change our default mod rules to include all versus definitions to avoid this kind of confusion in the future, and maybe even go as far as adding a lint rule to enforce it.

**Comment by GraionDilach** [comment]
>maybe even go as far as adding a lint rule to enforce it

No. No. NO. Huge no. This lint rule should be optional at best then. I wouldn't be happy this rule throwing out 500 warnings incase someone starts to use layered armor structure - the one I suggested for the TD Guardtower balance issue months ago.

**Comment by Phrohdoh** [comment]
The good thing about lint rules is that mods don't have to follow all of them if they don't wish.
Perhaps this section of the util should be beefed up some to allow easily ignoring certain rules in custom scripts/makefiles (similar to what StyleCop and other analyzers do).

**Comment by GraionDilach** [comment]
Yes, but if you get 100+ warnings from your coding style not following a lint rule, you'll definitely lose/ignore the one warning which actually makes sense.

**Comment by abcdefg30** [comment]
> we should change our default mod rules to include all versus definitions 

Not a fan of that, tbh. We don't explicitly include all defaults anywhere else too...

**Comment by pchote** [comment]
This appears to be the last unassigned / unfixed blocker, so is now holding up the next playtest.
