### ISSUE TITLE
Help with graphics

### ISSUE THREAD

**Issue by AJSully421** [OpenRA/OpenRA#11101]
I'm not even a newb... I am not even in the same planet as any of you.  I just want to play and enjoy.  I have a dell inspiron and when i open the RA game, it is all screwed up. there are large black blocks and some partial triangles that jump around, but seem to stick to buildings and units.  i did update my intel graphics unit drivers, but it is still doing it.  Help? here is a screen shot of that it is doing:

![image](https://cloud.githubusercontent.com/assets/18405084/14438434/d1dee28a-ffeb-11e5-9696-5ad16b073167.png)

Again, I literally know nothing about software, so any help will be greatly appreciated.  Thanks!

**Comment by obrakmann** [comment]
What's your graphics card? Is there anything gfx-related in graphics.log or debug.log?

**Comment by AJSully421** [comment]
So, you know on the IT crowd show where they answer the phones, "I.T., Have you tried turning it off and on again?"

I had to restart for another update and now it works fine.  Told you I was worse than a newb.  Thanks Guys.
