### ISSUE TITLE
Map Chooser: Make the client remember your latest view.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#11116]
For convenience sake I'd love to see the map chooser going to the latest map tab (Official/Custom) and map type (if chosen) for the map I've not only played, but also looked at. Currently, when switching back and forth between the map chooser and the lobby without selecting a map (happens frequently for various reasons) the map chooser starts with the _picked_ map's tab and centers on this map's position.

This would also be very convenient when looking through maps with the Editor's map chooser as well. Currently the Editor's map chooser solely remember the view from a selected map in a game lobby.

**Comment by rob-v** [comment]
The best solution for this would be to simply show/hide the window, however it seems OpenRA doesn't suppport hiding modal windows atm or am I wrong @pchote? (hiding of windows opened by Ui.OpenWindow - when I tried to hide returned Widged it hided also main/parent window). 

It is simple to select last focused map (after Close) and tab, but it is more work to recover last category. It can be done but I need at first confirmation this is wanted.

**Comment by PunkPun** [comment]
Now the last edited map shows up first in map chooser selection. For other cases I think random suits best
