### ISSUE TITLE
[Rendering] [TS] "Alpha light images" disappears when scrolling around

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#11115]
One of the Depth-buffer Pr`s introduce an "Cut-Away"-Effect while scrolling.

Reproduce case:
1. Start TS in bleed
2. Load the map "town of ka..." (the snow map)
3. Enter "/all"
4. Scroll around the map and look to the light posts`s Alpha images!

**Comment by abcdefg30** [comment]
I think that is because those effects are only rendered when you see the actor "generating" it.
Same goes for shadows. So that is not really a new issue (or did I missunderstand something here?).

**Comment by LipkeGu** [comment]
In the older Days these alpha images was removed when they are not in the renderable area but no they are removed before they completely out of screen...

**Comment by pchote** [comment]
This sounds like another place where we need `CustomSelectionSize` (or to fix the auto selection size).  Its not related to the depth buffer at all.

**Comment by Phrohdoh** [comment]
Fixing the auto bounds to take shadow frames/pixels into account would polish TS and RA2 nicely.

**Comment by Mailaender** [comment]
For the alpha lights it isn't really a shadow, but a huge `WithIdleOverlay` whose size gets ignored by default. I fixed it in `RenderSprites.AutoSelectionSize`, but ended up separating `ScreenMap` and `SelectionDecoration` bounds in https://github.com/OpenRA/OpenRA/pull/13925 as well to avoid regressions.
