### ISSUE TITLE
Map editor regularly scrambles player positions.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#11125]
I think this is somewhat important. When you place the player spawns in your editor, the map seldom saves them in the order that you placed them. The letter-positions gets to be random. This is why most maps often look like 

this
![engagement orig](https://cloud.githubusercontent.com/assets/2715583/14581528/aee3867a-03ef-11e6-80a3-66bfd56957a5.png)

instead of this
![engagement rew](https://cloud.githubusercontent.com/assets/2715583/14581530/b23dd302-03ef-11e6-8dc7-11b9103ec719.png)

*edit: the bug seem to appear when editing existing maps, removing and re-placing player spawns. In  order to reproduce the bug with a new map you need to save it, exit the editor, re-open the map and replace the player spawns with new player spawns.

The scrambling sort of defeats the purpose of having lettered positions in the lobby. In the editor I'm currently solving this by placing player spawns one by one,  _save and quit the map_ and reopen the map after each one,  until I have them all there.

**Comment by pchote** [comment]
This sounds like an odd one.  Is it a recent regression, or has it always done this?

**Comment by SoScared** [comment]
I think this might have been an issue before the latest release. I've never really delved into big team maps before so I can't say for sure. The oldest maps in the map pool have scrambled letter-marked player spots but that's probably because they weren't tweaked after the feature was introduced in the UI.

**Comment by pchote** [comment]
I can't reproduce this.  Can you give a list of specific steps (e.g. open map "foo", do specific thing "x", save map) that shows the bug?

**Comment by SoScared** [comment]
https://www.youtube.com/watch?v=vaXQmPUZAhE

The bug seem to happen solely when editing existing maps; open any map in the editor, remove and re-place the player spawns. The more spawns, the more likely the spots will be scrambled.

**Comment by pchote** [comment]
Found the problem, and #11146 will fix it for the next playtest.

**Comment by SoScared** [comment]
Wohoo! Thanks!

**Comment by SoScared** [comment]
Wohoo! Thanks!
