### ISSUE TITLE
20160403 Playtest: Ctrl-zooming bug

### ISSUE THREAD

**Issue by CountHanx** [OpenRA/OpenRA#11127]
Using the ctrl-zooming option (or whatever key it's mapped to) doesn't correctly update the cursor. It seems like it doesn't properly track if you zoomed in or out, because zooming in this way causes the pixel doubling hotkey to try to zoom in again (only updating the cursor in the process).

**Comment by pchote** [comment]
Was this fixed by #11135?

**Comment by obrakmann** [comment]
That's what I got from the description, yes.
