### ISSUE TITLE
[TS] Destroyable Roads via Ice layer logic?

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#11123]
In TS we have Paved roads with destroyed Ends maybe we can enable it to destroy paved roads.
For example when a cluster missile Explodes on them :) So the buildings and Roads gets destroyed.

We could attach an ICE Layer logic to Road to give them the ability... to get destroyable :)

**Comment by pchote** [comment]
A third party mod could do this if they wanted, but this is definitely out of scope for our official TS mod.
