### ISSUE TITLE
20160403 Playtest: Left-click control issues

### ISSUE THREAD

**Issue by CountHanx** [OpenRA/OpenRA#11126]
Although the release notes state that "a couple of issues related to left-click controls have been solved", it actually feels more broken than before.

A couple of issues that I've noticed in Tiberian Dawn (haven't tested other mods):
- Attack orders do not work at all. This includes ordering Harvesters to harvest specific patches of Tiberium and ordering vehicles onto the Repair Bay.
- Left clicking the minimap does nothing and seems to instead issue clicks behind it (like being able to select units hidden by the minimap).

**Comment by pchote** [comment]
You're quite right: the fixes we referred to weren't tested properly, and they broke pretty much everything else with the left click controls.  We've already fixed this in #11081, which will be included with the next playtest.  Thanks for the report!
