### ISSUE TITLE
Selecting default mod when launching

### ISSUE THREAD

**Issue by SzabKel** [OpenRA/OpenRA#11121]
Right now, the last mod is launched when you start the game for the next time. The modchooser should have a setting where you can select the default mod.

**Comment by GraionDilach** [comment]
What is the default mod?

**Comment by SzabKel** [comment]
The mod that is launched when you start the game. First time not set, you get the map chooser, but after you already successfully loaded a mod, the game automatically loads the previous mod based on : documents\OpenRA\settings.yaml -> Game: Mod: ra option.

**Comment by ihptru** [comment]
you can make custom launcher with Game.Mod=cnc for example.

**Comment by abcdefg30** [comment]
I agree to @ihptru here.
