### ISSUE TITLE
Buildable range indicator Cycle turns Red when placing Buildings.

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#11134]
I mean not the footprint!

In Cnc when placing Buildings while you have selected the construction Yard, the white range Indicator turns red when placing a building and turns back to white which is senseless. It could be stay white or shortly hidden.

Yes i know for what the range indicator is but it would be make more sense that the indicator turns red when the Player is trying to place a structure outside the buildable range...

it would be also make more sense to toggle the indicator on or off by hotkey to show my buildable range

Reproduce case:
1. start a cnc match and undeploy your MCV
2. Select the construction yard and build a structure (while leaving the construction yard  selected)
3. place it... the white cycle turns to red and after 2 Seconds back to white...

**Comment by pchote** [comment]
When you place a building within range of the construction yard there is a delay before you can place another one.  This rate limit is there to stop you from deploying an mcv in an enemy base and then immediately placing a bunch of defensive structures.

The range indicator turns red to indicate this.

**Comment by LipkeGu** [comment]
ah ok ...
