### ISSUE TITLE
[bleed/prep] Left-click orders: unable to select new unit while another is already selected

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#11132]

**Comment by pchote** [comment]
It looks like @Mailaender forgot to cherry pick https://github.com/OpenRA/OpenRA/pull/11081/commits/7a32c8e8e7cdd7b42098338fde02c604bd5fe846 on to the prep branch.

**Comment by obrakmann** [comment]
Yep. I pushed that commit now.
