### ISSUE TITLE
[Replay] Missing requiered maps should be auto downloaded... or embedded

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#11149]
When i want to watch a replay... an the map is missing but the map is in the resource center ... the map should be downloaded by the game instead of showing the map-hash :/

Or allow an option to embedded a map in a replay on custom maps the game could remove the "MAP-DATABLOCK" after extracting them :/

**Comment by ihptru** [comment]
if it shows map-hash, you can copy it and paste into search field on Resource Center btw.

**Comment by pchote** [comment]
It would be easy to make it use the same UI that the lobby uses for map installation.

**Comment by LipkeGu** [comment]
on my site where i got the map hash for the issue "game drops to crawl speed" it wasnt able to copy the map hash =/

**Comment by SoScared** [comment]
This would be super helpful for reliably sharing replays all around.

**Comment by LipkeGu** [comment]
Phrohdoh Mentored, easily send him the map isnt also handy because you have sometimes the problem that some hosters "wich you prefer" not available for others and also sometimes you doesnt know any method to contact the "issue starter" directly or quickly... so it would be nice when OpeNRA says "Yeah the map is in the Ressource center, should i download (and install) the map for you?" and then run the Replay!

**Comment by Phrohdoh** [comment]
It needs to be stated that I am all for suggesting/automating map downloading.

Of course the replay format could be extended to have a mapdata block and commands could be built to (un)pack maps from replays, but I do not think we should be embedding them by default.

**Comment by LipkeGu** [comment]
OpenRA could remove the MAP Block after extracting... :)

**Comment by pchote** [comment]
:-1: to embedding maps in replay files.

**Comment by rob-v** [comment]
PR #13233
