### ISSUE TITLE
Actors can't have multiple Cloakable traits

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#11159]
Looks like #11154 was poorly tested by us reviewers.

While it fixed #11055, now actors like the TS stealth tank crash the game because they have more than one cloakable trait.

The fix for that would probably be to change

`cloak = self.TraitOrDefault<Cloak>();`

to

`cloak = self.TraitsImplementing<Cloak>().FirstOrDefault(Exts.IsTraitEnabled);`

**Comment by pchote** [comment]
The multiple-trait check needs to be done at the places/times that the checks are used.  Caching the first enabled trait at creation time won't work.

**Comment by reaperrr** [comment]
Would introducing an `INotifyCloakStateChanged` interface that gets notified every time an actor cloaks/uncloaks possibly make sense here? The trait lookup in `Targetable` could then be updated every time the cloak state changes (in addition to creation), which should normally cover `Cloak` traits getting enabled/disabled.

**Comment by GraionDilach** [comment]
Multiple cloak traits always crashed on me though, so I guess the Stealth Tank not crashing beforehand is just pure luck.

**Comment by Phrohdoh** [comment]
@reaperrr Sounds like the best way forward to me.
Please include the previous state and the new state.

**Comment by pchote** [comment]
Sounds like overkill for this bug.  Just cache all of them, and then use a .Any in the one place in that checks them.

**Comment by reaperrr** [comment]
> Sounds like overkill for this bug. Just cache all of them, and then use a .Any in the one place in that checks them.

Makes sense.

> Multiple cloak traits always crashed on me though, so I guess the Stealth Tank not crashing beforehand is just pure luck.

I'd say it was bad luck that it didn't always happen, otherwise we'd have fixed this earlier.

The TS stealth tank not crashing was just a trait order thing, one `Cloak` trait constructed before and one after `Targetable`.

**Comment by GraionDilach** [comment]
Either way, I wouldn't call this a regression.
