### ISSUE TITLE
Moving units do not attack enemy units...

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#11155]
If I give move command without "A" button pressed, my Appocalipse tank goes near enemy harvester without attak it. 
In original RA2 Appocalipse and tesla tanks do it automaticaly.

**Comment by Phrohdoh** [comment]
Is this a bug?

Seems to me an [`AutoTarget`](https://github.com/OpenRA/OpenRA/wiki/Traits#autotarget) trait is missing.

This should be in the RA2 tracker.

**Comment by yaaaaa** [comment]
in RA and TD mods moving units do not attack enemy units too

**Comment by yaaaaa** [comment]
but I noticed that if it set his sights on something before the movement itself or on the order, he then shoots while driving
