### ISSUE TITLE
The game crashes when open "settings" from main menu [Linux, playtest-20160424]

### ISSUE THREAD

**Issue by grafviktor** [OpenRA/OpenRA#11181]
Hi! When I'm clicking on "settings" button in the main game menu, the game immediately crashes with System.NullReferenceException . I believe it's a sound related problem if judge by the game output. Please find log files in the attachment. I tested it only on my Linux machine.

[exception.txt](https://github.com/OpenRA/OpenRA/files/233581/exception.txt)
[sound.txt](https://github.com/OpenRA/OpenRA/files/233582/sound.txt)

**Comment by obrakmann** [comment]
Is that reproducable? What sound card do you have? Did you maybe unplug speakers or head-phones or similar while the game was running?

**Comment by grafviktor** [comment]
Thanks for your reply obrakmann.
Yes, that is reproducible. I'm attaching lspci output with all devices list of my pc, in case you still need it.
[lspci.txt](https://github.com/OpenRA/OpenRA/files/233594/lspci.txt)

**Comment by Mailaender** [comment]
Can you check if https://github.com/OpenRA/OpenRA/pull/11183 fixes it for you?

**Comment by grafviktor** [comment]
Checking

**Comment by grafviktor** [comment]
Mailaender, I've just tested and unfortunately it does not fix the issue for me, but maybe the following will help you somehow:
` 
      if (next == IntPtr.Zero || AL10.alGetError() != AL10.AL_NO_ERROR)
      {
        Log.Write("sound", "Failed to query OpenAL device list using {0}", label);
        return new string[] { };
      }

      do
      {
        var str = Marshal.PtrToStringAnsi(next);
        if (null == str) { // this condition is true, on a 2nd iteration, on my machine
          Console.WriteLine("-------------------------------------------- str is null");
          break;
        }
        next += str.Length + 1;
        devices.Add(str);
      } while (Marshal.ReadByte(next) != 0);

      return devices.ToArray();`
The app works fine with this null checking, but when I close the app I see that one of my audio-devices left unclosed. The output:
Available mods:
	all: All mods ({DEV_VERSION})
	cnc: Tiberian Dawn ({DEV_VERSION})
	d2k: Dune 2000 ({DEV_VERSION})
	modchooser: Mod Chooser ({DEV_VERSION})
	ra: Red Alert ({DEV_VERSION})
	ts: Tiberian Sun ({DEV_VERSION})
Loading mod: ra
-------------------------------------------- str is null or empty
AL lib: ReleaseALC: 1 device not closed

**Comment by Mailaender** [comment]
I updated https://github.com/OpenRA/OpenRA/pull/11183 again.

**Comment by grafviktor** [comment]
That works just fine now, thank you! Though I'm not sure that checking that the String is empty is necessary here. Buy the way, I still see the message:
_AL lib: ReleaseALC: 1 device not closed_

**Comment by Mailaender** [comment]
That is a known issue. https://github.com/OpenRA/OpenRA/issues/11193

**Comment by grafviktor** [comment]
Got it! Thank you very much Matthias! :-)

**Comment by Mailaender** [comment]
The fix won't be accepted as is: https://github.com/OpenRA/OpenRA/pull/11183#discussion_r62430644 so we probably still need your investigation skills.

**Comment by GraionDilach** [comment]
Could you add an `IsWin32Atom(next)` check to the `if (next == IntPtr.Zero || AL10.alGetError() != AL10.AL_NO_ERROR)` line and retest, please?

**Comment by grafviktor** [comment]
Sorry friends, I'm not really familiar with .Net. The condition
`if (IsWin32Atom(next) || next == IntPtr.Zero || AL10.alGetError() != AL10.AL_NO_ERROR)...`
gives me a compilation error:
`OpenRA.Platforms.Default/OpenAlSoundEngine.cs(59,8): error CS0103: The name `IsWin32Atom' does not exist in the current context`

**Comment by grafviktor** [comment]
I am not sure, but it seems to me that if a String contains an 'incorrect' character, then Marshal.PtrToStringAnsi returns null. The call ALC10.alcGetString(IntPtr.Zero, type); on my machine returns strings which contain character with a code 65533. The crap code below is working on my machine, maybe it will give you some clue:
```
static unsafe string[] QueryDevices(string label, int type) {
....
do {
	var preFetchedStr = new String((sbyte *)next);
	char replacementCharacter = Convert.ToChar(65533);
	if(preFetchedStr.Contains(replacementCharacter)) {
		Console.WriteLine("Warning: device name contains a \'Replacement Character\': " + preFetchedStr);
		next += preFetchedStr.Length+1;
		continue;
	}
	var str = Marshal.PtrToStringAnsi(next);
	next += str.Length+1;
	devices.Add(str);
} while(Marshal.ReadByte(next) != 0);
```
And the game's output is:
```
Warning: device name contains a 'Replacement Character': �алоговое стерео
Warning: device name contains a 'Replacement Character': �ео
Warning: device name contains a 'Replacement Character': �
```

**Comment by Mailaender** [comment]
Oh, special chars. That explains why `PtrToStringAnsi` fails. I updated https://github.com/OpenRA/OpenRA/pull/11183. Can you give it another try?

**Comment by mamantoha** [comment]
Well. I've found a temporary solution to open "settings".

```
apulse openra
```

Hope this issue will be fixed soon and my solution will help somebody :)

P.S.  Arch Linux, openra 20160508-2

**Comment by Mailaender** [comment]
Can you verify https://github.com/OpenRA/OpenRA/pull/11183 fixes it for you with a :+1: there?

**Comment by mamantoha** [comment]
@Mailaender yes, #11183 fixes this issue for me.
