### ISSUE TITLE
Allow private servers' host to give away Admin position in the game lobby.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#11198]
Not sure if possible, or perhaps this is in line with other issues asking for the ability to give away the Admin rank. It would be really nice to be able to give away control of the game lobby to other players e.g. if you want to spec, be afk or  perhaps host competition matches.

**Comment by Aaron-Lloyd** [comment]
Duplicate of #10379 I think.

**Comment by SoScared** [comment]
Appears so. #10379 looks to be working both on private and dedicated servers.
