### ISSUE TITLE
Using "restart (mission)" button does not re-randomize the "random/any" game settings

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#11190]
Tested in skirmish, playtest 20160424

When a skirmish game has 
- factions and / or
- spawn points 
  set to random / any they don't get re-randomized when you restart the game.

I think it would be better - more fair if they get new values since the restart button is probably used when you fail and want to try again. 
Knowing the factions and spawn points of opponents in a bit of a cheat...

**Comment by GraionDilach** [comment]
TBH that is consistent with the other RTSes I know of.

**Comment by pi99y** [comment]
I (and maybe some other players too) don't expect current behavior from the restart function and rather reconfigure a skirmish match, which makes the function useless in this case. I don't want an easier match I just want to try again and I chose the random settings for a reason (so I must scout).

I'm guessing since the mechanics to randomize the factions and positions are already in place, this would be a ~simple (guessing) improvement.

While I doubt the current behaviour is a genre's standard, "breaking" it would just improve and maybe stand out a good way...

**Comment by pchote** [comment]
The random number generator seed is stored in the `LobbyInfo.GlobalSettings`.  To address this ticket the reset code would need to reseed this value.
