### ISSUE TITLE
OpenAL device not being properly closed

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#11193]
I always get reminded in the command line when closing the game window with `x` buttons.

> AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by pchote** [comment]
This happens because `OpenAlSoundEngine`'s Dispose uses `Game.RunAfterTick` to do the actual disposing, but that never runs because the game has already finished ticking by that point.

**Comment by pchote** [comment]
I assume @RoosterDragon had a good reason for introducing the RunAfterTick in #10346, but that pr doesn't explain why.

**Comment by RoosterDragon** [comment]
Just for marshaling, I imagine I was assuming it was a thread-affine item. If not, the easy fix is just to dispose it directly.

**Comment by chrisforbes** [comment]
It would be worth ensuring that those queues are fully drained before
exiting.

**Comment by LipkeGu** [comment]
It seems the Device isnt closed at the time where we want to cleanup the Device Resources

**Comment by Fahrradkette** [comment]
Just a wild guess: the issue might lie at https://github.com/OpenRA/OpenRA/blob/25c640679ca0f7a3ebb8d0dd5a2f5525d17e13bb/OpenRA.Platforms.Default/OpenAlSoundEngine.cs#L319-L320
We're not properly destroying, we don't even look at the return value of alcCloseDevice()
https://www.openal.org/documentation/openal-1.1-specification.pdf says on section 6.1.2. that we have to first destroy the buffer and context, I guess section 6.2.6. explains how to get rid of the context, and rightfully chrisforbes mentioned the buffer which we have to get rid of, too.
I have no idea what OpenAL-to-C# wrapper OpenRA is currently using, so take this with a grain of salt, I didn't try to read what magic happens there:)
