### ISSUE TITLE
Commits to include if we release another playtest before stable release

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#11200]
- [133a0f5](https://github.com/OpenRA/OpenRA/pull/10813/commits/133a0f54a3673a84ebfff671fc967421d81af3f2)
- [21989ac](https://github.com/OpenRA/OpenRA/pull/11172/commits/21989acd28560e65b84094f187d8d8e726b2a924)
- ~~[b87b2c0](https://github.com/OpenRA/OpenRA/pull/11199/commits/b87b2c010f2bb67fc4fd1082579a561130971d3f)~~

There may be more.

**Comment by obrakmann** [comment]
I'm hesitant to include 133a0f5, its regression potential is too high for my taste. Wrt to 21989ac, I don't think any of our does any 3rd party mod make use of that, and is it likely that that mod will produce a usable release before our next one?

**Comment by reaperrr** [comment]
> I'm hesitant to include 133a0f5, its regression potential is too high for my taste.

I don't see what makes it so risky, and it's only supposed to go in if there's another playtest first, but ok.

> Wrt to 21989ac, I don't think any of our shipped mods require it. Is there any 3rd party mod that makes use of that, and is it likely that that mod will produce a usable release before our next one?

I don't know, @pchote fixed it and suggested on IRC to potentially include it in stable.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/commit/133a0f54a3673a84ebfff671fc967421d81af3f2 shouldn't cause trouble. It just adds additional safe guards as seen in other warheads to avoid game crashes.

**Comment by obrakmann** [comment]
I cherry-picked those two now. Changelog edited accordingly.
