### ISSUE TITLE
[NEEDS CONFERMATION] Anti-Air can see cloaked phase tank.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#11204]
My phase tank drove near an AA gun and suddenly everything attacked it. Is this the intended behavior?

**Comment by Phrohdoh** [comment]
Yes, [see here](https://github.com/OpenRA/OpenRA/blob/cc9f84f1362f2672e3697206ea224d104d0ad389/mods/ra/rules/structures.yaml#L492-L493).

**Comment by epicelite** [comment]
But why though? Its an anti-AIR gun why should it be able to detect cloaked shit??
