### ISSUE TITLE
Map upgrading is broken with FileNotFoundException

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#11203]
I'm getting a `System.IO.FileNotFoundException` when running upgrade rules on any mod for every `.oramap`. 

> File `*path*\*mapname*.oramap.451.tmp` not found 

And something about `WinIOError`. Can't post the full exception because the utility doesn't write it to any log.

Win7x64.

**Comment by GraionDilach** [comment]
OpenRA.Utility.exe modname --upgrade-map > logname.txt (the > logname.txt part lets you to send the standard console output into the file, that will include the exception, this is how you have to convert the TS terrains also.)

**Comment by GraionDilach** [comment]
I was stupid 17 days ago and 17 minutes ago, bear with me. >_>

**Comment by pchote** [comment]
https://github.com/pchote/OpenRA/tree/hack-hack-hack-the-upgrader has workarounds to make the upgrader functional again.
