### ISSUE TITLE
Player owned Oil Derricks nameless. (TD)

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#11219]
A player owning an oil derrick in TD does not show who owns the oil derrick. It simply just has the name "Oil Derrick" on it. Yet the color shows the owner of the structure.

(Unsure if this is a bug or intentional.)

**Comment by pchote** [comment]
I'm pretty sure that this is both unintentional and a regression.  Maybe from the recent PR removing the owner row from trees etc?

**Comment by pchote** [comment]
We should check the other tech buildings (hospital, biolab) too.

**Comment by AoAGeneral** [comment]
This is confirmed. Same bug applies to other tech structures as well.
