### ISSUE TITLE
Turning looks too smooth

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#11212]
I've read criticism about how OpenRA's turning mechanism doesn't look good visually, and I'm inclined to agree. It's particularly noticable on half-circles around 1-cell obstacles and such, it somehow looks unnatural and too smooth.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Activities/Move/Move.cs#L390

**Comment by reaperrr** [comment]
At least one of the reasons seems to be that actors are literally "cutting corners" when the next cell on their path requires turning. Even actors that don't share cells (vehicles) don't move from cell center to cell center, but rather turn as soon as they enter a cell. I'm not just talking about corners of cells adjacent to their path, but even cells *on* their path.
This behavior is clealy different from the original games and probably contributes a lot to this issue, it might even be the only problem here.

**Comment by pchote** [comment]
Indeed.  That behavior is controlled by the block I linked above, which dates right back to the very first movement implementation.

**Comment by reaperrr** [comment]
As discussed on IRC, that alone doesn't do the trick because it makes actors stop for a bit until they finish turning, effectively slowing them down.

I looked at the movement behavior of the original TD for a bit and noticed a few things:
1. OpenRA's L-turn actually looks relatively fine. However, in TD units would always perform the diagonal move first (unless that cell is occupied, of course), while in OpenRA, actors usually (but not always) perform the straight move first.
2. OpenRA's U-turn is crap and the main problem. In our engine, actors start turning as soon as they enter the first cell, whereas In RA/TD, actors only start to turn shortly before reaching the cell center of the first cell. It also seems the distance from cell center at which they start turning scales depending on the turn rate (higher ROT means they move closer to cell center before turning), while in OpenRA they simply turn as early and quickly as they can.
3. OpenRA performs L-moves where the original performs a "_/¯". I assume this is because our Move code only checks two cells ahead (next + next+1), seems like the originals checked at least next+2 as well.

**Comment by reaperrr** [comment]
Tackling 1. wouldn't hurt either, though, because the result of OpenRA's behavior - performing the straight move first and the turn second - is that quite often, the final facing after the unit stops is slightly of, because it reached the destination a tick or two before it could completely finish the turn.
