### ISSUE TITLE
[RA] France - add fake Service Depot

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#11229]
The supposed strength of France is deception so where is the fake Service Depot? Deciding between Service Depot and the Radar dome is the first choice in picking the tech route for Allied players.

**Comment by HenrytheSlav** [comment]
Well, we just added fake Power Plant. Let's see the reception for that first. I have no real problem with adding it, however it is better that it will be in future and not this release. Future freeze is on for weeks anyway.

**Comment by SoScared** [comment]
That would be unfortunate. For the most part, players are unwilling to take advantage of the fake structures. It's still percieved as inconsequencial. As per playtest the fake powerPoint has gone unnoticed with exception in the context of a pun. :/

**Comment by HenrytheSlav** [comment]
I for one am very pleased with fake Power Plant and I tried to push it through, since it gives allies some "defence" against spies and power-down tactics.

**Comment by Lukemtesta** [comment]
I would agree, as a player also, that the service depot is a key milestone through the allied tech route. A deceptive defense should provide the player with a way of protecting their tech tree (to some degree). I guess an argument against it is continuously building fake service depots - A building limit for this?

**Comment by HenrytheSlav** [comment]
There is no issue with fake spam I think. They are easy do destroy, the don't work as intented (obviously, they are fake) and they cost money. We allow unlimited fakes.

**Comment by Townes27** [comment]
I suggest that fake helipad and fake AA gun should also be included along with fake service depot.
That would strengthen France by a lot in my opinion since it would then be possible to really hide the tech route.

**Comment by HenrytheSlav** [comment]
Fake defense was not implpemented in original, and making it here is kinda dangerous , I think. Sapmming these around your base for almost nothing forces your opponent to abandon airforce because single even if two-three of these are not fake it will wreck his air units in seconds. Helipad seems kinda usefull, so I let others discuss that I guess, no opinion either way here.
