### ISSUE TITLE
Minelayer - reloading heard by everyone ingame

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#11236]
follow-up from #11230 ( @Mailaender : please stop closing (my) tickets without giving a prove-link for the fix ... thx)
 
release-20151224 - RedAlert

- you can hear "every" minelayer" including your enemys minelayer , when they stand on a repair-pad and reload

**Comment by Mailaender** [comment]
@Micr0Bit please don't put multiple bugs into one ticket and test against the latest playtest version before opening an issue.

**Comment by Micr0Bit** [comment]
still theres no reason to close unfixed issues ... as im capable of "editing" my tickets , and i usually keep my them clean and tidy
