### ISSUE TITLE
Error codepage 850 not supported

### ISSUE THREAD

**Issue by DestructionOfPlanetJupiter** [OpenRA/OpenRA#11256]
Basically a follow-up of this:
https://github.com/OpenRA/OpenRA/issues/10197

still not working. 

OS:
Linux Mint 17.1 64 Bit

**Comment by abcdefg30** [comment]
Could you try to install the `libmono-i18n4.0-all` package (as suggested by @pchote the last time someone got this error, I think)?

**Comment by marsjaninzmarsa** [comment]
@abcdefg30: works for me, thanks!
