### ISSUE TITLE
openra fails to start: Missing method .ctor in assembly /usr/lib/openra/OpenRA.Game.exe

### ISSUE THREAD

**Issue by MarcSchmitzer** [OpenRA/OpenRA#11255]
Fresh install on Fedora22 from the openSUSE Build Service repository, openra fails to start.

Full output:
```
$ openra
Missing method .ctor in assembly /usr/lib/openra/OpenRA.Game.exe, type System.Runtime.CompilerServices.ExtensionAttribute
Can't find custom attr constructor image: /usr/lib/openra/OpenRA.Game.exe mtoken: 0x0a000002

Unhandled Exception: System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'OpenRA.Game'.
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.ExtensionAttribute' from assembly 'OpenRA.Game'.
```

Package versions:
- openra-20160508-1.1.noarch
- mono-winfx-2.10.8-8.fc21.i686
- mono-core-2.10.8-8.fc21.i686

**Comment by pchote** [comment]
mono 2.10 is extremely outdated.  Try updating to mono 4.2.x.

**Comment by MarcSchmitzer** [comment]
Thanks for the quick reply. Seems like I had that really old mono pinned in my system by a manual installation of sparkleshare I had alrady forgotten about.

After a little cleanup, I'm on mono-core 4.2.1 now and the game starts. Maybe the openra package should declare a minimum mono version.

**Comment by Mailaender** [comment]
> Maybe the openra package should declare a minimum mono version.

Good idea. Done.
https://build.opensuse.org/package/rdiff/games:openra/release?linkrev=base&rev=32
