### ISSUE TITLE
Internet crashes soon after starting an online or skirmish match

### ISSUE THREAD

**Issue by dhoffsteder** [OpenRA/OpenRA#11259]
I need help, I can't play Openra online because whenever I go online and play the very beginning of a multiplayer match or a skirmish with internet connected. It crashes the connection and I have to restart my computer to regain internet access. This has been happening for months and patches haven't fixed it. I use a wired internet connection, and this has made me only be able to download updates from chrome and play skirmish and missions while disconnected. I really want to play multiplayer again. Your help would be greatly appreciated. I use Windows 10 in case that matters.

**Comment by HenrytheSlav** [comment]
Is it possible that maybe your internet access is restricted to some content (f.e. it is not allowed to play games, visit blacklisted sites) and thus shuts your connection because it detects violation?

**Comment by dhoffsteder** [comment]
No, Every other game I play works online. Just not Openra. Plus I can visit any site I want. As far as I know there are no restrictions.

**Comment by obrakmann** [comment]
Do you happen to have UPNP enabled in the advanced settings dialog? If so, can you try to turn it off and see it it helps, please?

Also, do you have any firewall or anti-virus scanner running that might interfere with network traffic?

Some more questions:

1. Can you use the server browser? Does doing so cause your connection to die?
2. Can you connect to servers? Does doing so cause your connection to die?
3. Can you *create* a server? Does doing so cause your connection to die?
4. Can you download maps in-game? Does doing so cause your connection to die?
5. Can you connect to the lobby chat? Does doing so cause your connection to die?
6. Does starting a *single-player* skirmish (ie. Main Menu -> Single-Player -> Skirmish) cause your connection to die?
7. When the connection dies, does the game keep running? If it crashes, please let us know the contents of exceptions.log.

**Comment by dhoffsteder** [comment]
I have no fire wall or anti-virus scanner running. If there is it is hiding from me.

From what I remember it crashes my connection only soon after I start a game in multiplayer or skirmish. When it happens in skirmish the game keeps going but my connection fails. The game keeps running after connection fails during an online match, but that forces me to only play skirmish and missions offline. (it responds by disconnecting my internet) Thus forcing me to restart my computer to get internet back.

1.yes,no
2.yes,no
3.never tried, don't know
4.yes,no
5.yes,no
6.yes
7.yes,internet crashes but the game itself (not online) keeps going. The computer itself is also fine (just the internet connection fails and remains that way until computer is restarted)

UPNP is off and has always been.

**Comment by abcdefg30** [comment]
Is this issue still present on the latest playtest?

**Comment by pchote** [comment]
A lot has changed since 2016, so there is nothing else that we can do here.
