### ISSUE TITLE
FileNotFoundException when initializing the game

### ISSUE THREAD

**Issue by Marty** [OpenRA/OpenRA#11252]
Hi,
I just installed the game and fiddled with the settings, saved and restarted.
Then I had an invisible cursor, so I reset the configuration.

Now the game does not start anymore (even after reinstall) and fails with this being the only error:

**exception.log**
```
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.18444
Exception of type `System.IO.FileNotFoundException`: Das System kann die angegebene Datei nicht finden. (Exception from HRESULT: 0x80070002)
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at OpenRA.Sound..ctor(String engineName)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

```

Is there a possible workaround for me? (:

**Comment by abcdefg30** [comment]
Could you try downloading https://github.com/OpenRA/OpenAL-CS/releases/download/20151227/OpenAL-CS.dll and putting it into your main game directory? That seems to have fixed it for another user.

**Comment by Marty** [comment]
Thanks for the suggestion, but the exception still occurs. I also still had the file.

**Comment by abcdefg30** [comment]
Hm, do you also have the `OpenRA.Platforms.Null.dll` and `OpenRA.Platforms.Default.dll`?

**Comment by Marty** [comment]
```OpenRA.Platforms.Null.dll``` is missing

**Comment by obrakmann** [comment]
Please try the following steps. Retry starting OpenRA after each one, stop when it's working again.

1. Install all pending Windows updates.
2. Repair your .net framework installation ([this](https://www.microsoft.com/en-us/download/details.aspx?id=30135) and [this](https://support.microsoft.com/en-us/kb/2698555) might help with that, but I'm not a windows user myself, so can't tell)
3. If you happen to have Visual Studio installed, repair that as well.
4. This one's a shot in the dark, but try disabling your anti-virus software. Don't forget to turn it on again afterwards.

**Comment by Marty** [comment]
Don't get me wrong. It worked the first time I launched it. I downloaded the ra2 game files, saw the menu etc. etc. and I'm pretty sure I could've started a game. Then after the above mentioned steps it wouldn't start anymore.

But I will try those steps.

**Comment by Marty** [comment]
I did all of the steps, but it did not help.

**Comment by GraionDilach** [comment]
You say you have/had(?) the RA2 mod installed.  Could you remove the RA2 mod from your home directory then (if you haven't done yet? I'm unsure what the exception would be but the RA2 mod relies on the TS mod which is missing from the release and that exception do sound like if it tries to complain about the missing TS mod's dll logics.

**Comment by Marty** [comment]
Yes, I had the ra2 mod installed. I deleted it now (`mods/ra` ... anything else?), but it had no effect. The exception remains the same.

**Comment by StexoO** [comment]
@Marty "It worked the first time I launched it."
What about a fresh OpenRA install ?
(Uninstalling OpenRA, deleting all the remaining OpenRA folders in your computer and installing the latest release)
The OpenRA installer has all the required files so technically no FileNotFoundException.

**Comment by Marty** [comment]
@StexoO I tried that first, as I mentioned above. Are there any other folders somewhere, other than the main game folder where I pointed the installation to?

I also saw some registry entries, but there were no references to non-existing files, so I left them untouched.

**Comment by GraionDilach** [comment]
My Documents/OpenRA (the place the RA2 mod would been). Only those two.

**Comment by Marty** [comment]
@GraionDilach That did the trick, thanks!

However, what stays is the invisible mouse cursor, I have to use windowed mode to see it.

**Comment by StexoO** [comment]
@Marty Maybe https://github.com/OpenRA/OpenRA/issues/10172 ?
I have no cursor everytime I start OpenRA. I click on Mods (with Alt-Tabs or the hover color in the menu to know where the cursor "is") and the cursor comes back.

**Comment by hasufell** [comment]
I had the same under linux. I removed the whole `~/.openra` folder, then it worked. What a mess.

**Comment by pchote** [comment]
This regression affects all platforms, not just windows, and was introduced by #11005.  It turns out that we *did* need `OpenRA.Platforms.Null.dll`, which was loaded directly by the sound code(!).

I have a branch that introduces some sanity to the platform initialization and will fix this.

**Comment by hasufell** [comment]
pewdiepie
