### ISSUE TITLE
Sometimes units will move rather than attack a camo pill under fog

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#11265]
You can see this on [this replay](http://www.gamereplays.org/openra/replays.php?game=92&show=details&id=311530) just after 11:15.

This only seems to happen sporadically and apparently happens in other instances too (not just with camo pills)

**Comment by Micr0Bit** [comment]
i have i noticed that i cant just attack "frozen" camopillboxes under fog ... the attack-cursos doesnt appear ... but still i see the frozen camo ... and "force fire" is also not allowed ... 

the only thing i can do , is shoot on a cell near by and hope to kill it with damage "spreading" over

**Comment by obrakmann** [comment]
@Micr0Bit: with what kind of unit does that happen? Worked fine for e1 infantry and yaks in my tests:
![screenshot from 2016-05-14 00 41 27](https://cloud.githubusercontent.com/assets/4331210/15263715/b8a499e6-196c-11e6-8a9d-8ac7a829e2ac.png)

A difference is that the tooltip isn't shown for a cloakable frozen actor, which is a bug.

**Comment by Micr0Bit** [comment]
@obrakmann : do they actually attack when you right-click on it ?

Artillery cant attack a frozen-camo ... you see the attack-cursor and the attack-line ... but it doesnt attack (i just checked it again)

**Comment by obrakmann** [comment]
@Micr0Bit: yup, you're right, they don't. Sorry, I was focusing on you saying that the attack cursor wouldn't appear.

**Comment by Micr0Bit** [comment]
@obrakmann : yeah my bad

**Comment by pchote** [comment]
The problem will be that the frozen actor targeting will be handing off to the real underlying actor.  If the real actor is currently cloaked then the targeting will be rejected.

To fix this properly we will need to implement proper targeting handling for frozen actors, which is something i've been pushing for for years.  We've had at least one attempt, from @obrakmann, to implement this, but I couldn't find the pr/branch.

**Comment by AMHOL** [comment]
I think a possible solution to this would be for structures not to re-cloak once revealed, the replay didn't save but there was an instance where someone had a tanya pillbox and I had to keep running infantry at it to reveal and kill it before I could move in. I guess this wouldn't be so much of a problem if force-fire worked but I think it makes sense for structures to not re-cloak anyway.

**Comment by pchote** [comment]
There doesn't seem to be much interest in fixing this, so i'm not prepared to delay the next release over it.  Removing from milestone.

**Comment by SamKeightley** [comment]
While this issue should definitely not delay any releases, it is something that needs to be fixed.

**Comment by pchote** [comment]
#12333 attempted a solution, but was not completed because this is actually a very difficult issue to fix.

**Comment by Snurre86** [comment]
The camo pillboxes can be targeted if you scout it with something that is out of its target range or a air unit. This will unrevealed it so you need to remember where it is.
