### ISSUE TITLE
White screen when running OpenRA with USB-Dockingstation

### ISSUE THREAD

**Issue by Firestorm87** [OpenRA/OpenRA#11268]
Hi,

at Home i am using an "Plugable UD-3900" USB-Dockingstation to use my Notebook on my Desk.
If i run OpenRA (20160508) on the dedicated Notebook, everything works fine,
If i run OpenRA while the Dockingstation is connected i just get a white Screen.

After I disconnect the dockingstation while i see the white Screen, i can see the running OpenRA at the Notebook.

There is no Error on the Log-Files and OpenRA keeps running normal (no crash!).

**Comment by GraionDilach** [comment]
Is this in windowed mode? If not, please try that out as well.

On the other hand, the device itself doesn't support gaming either. http://plugable.com/products/ud-3900#gaming The implication of the CPU doing the GPU calculations sound suspiciously as the cause.

**Comment by Firestorm87** [comment]
The white screen is only in fullscreen mode.
In windowed mode everything works fine.

Thank's for that tip. For me it's also ok to use the windowed mode.

And of course i know, that USB-Dockingstations are not really great for gaming, but while there's life, there's hope :)

**Comment by Mailaender** [comment]
Try contacting the vendor. I doubt there is anything we can do. We use SDL for windowing and OpenGL for rendering. Nothing really fancy that should cause problems on our end.
