### ISSUE TITLE
Fedora / Centos / Suse Repos are in 20151224 release 

### ISSUE THREAD

**Issue by maxtrix** [OpenRA/OpenRA#11260]
Hi, I succesfuly installed openra in my centos 6.7 server, but it was installed the previous release 20151224 instead the 20160508 release.

Please update the repository

Can I manually update overwriting the installed files using the github source?

**Comment by pchote** [comment]
According to https://build.opensuse.org/package/show/games:openra/release the centos 6 build failed because it doesn't provide the necessary dependencies.

**Comment by maxtrix** [comment]
I achieved installing, the only two dependencies that where mising are SDL2 and openal that I solved myself.

The issue is other, the repositories are out of date.

**Comment by Mailaender** [comment]
Updated it 3 days ago. https://build.opensuse.org/package/rdiff/games:openra/release?linkrev=base&rev=30

**Comment by pchote** [comment]
As I mentioned above, the update 3 days ago broke the dependencies for Centos 6.

**Comment by Mailaender** [comment]
Fixed it. https://build.opensuse.org/package/rdiff/games:openra/release?linkrev=base&rev=31

**Comment by maxtrix** [comment]
Thanks, I updated and works flawessly!!!
