### ISSUE TITLE
Left click orders don't work for navigating the mini map

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#11263]
When you use left click orders, you still have to use right click to navigate via the mini map

// Edit:
Not sure whether this was present before the latest release

**Comment by GraionDilach** [comment]
That's how it always was, I think.

**Comment by MustaphaTR** [comment]
If something isn't selected, left click(or both) does the moving on radar, if we have a unit selected left gives command, right moves the view in original games iirc.

**Comment by gardolf** [comment]
I believe this can be closed.

Release 20180923
