### ISSUE TITLE
Wall rendering broken when Explored Map is enabled

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#11279]
![openra-2016-05-14t144749z](https://cloud.githubusercontent.com/assets/4331210/15269176/bc0e9024-19f7-11e6-9a86-af5a8ae8e227.png)

**Comment by abcdefg30** [comment]
This is turning out to be very weird:
- We could only reproduce this in multiplayer
- But not every player and even spectator does see the bug

(For example: I had two spectating clients, one saw it, the other not).

**Comment by pchote** [comment]
I've been able to show that this happens because/when Game calls RenderTick before the regular Tick... which shouldn't be possible, but is happening anyway.  I don't have a reliable way to reproduce the glitch, so I haven't yet been able to debug this any further.

**Comment by pchote** [comment]
Got it.  #12148.
