### ISSUE TITLE
No Credits given on nod08a - "Battle for Zaire (a)"

### ISSUE THREAD

**Issue by jtyle6** [OpenRA/OpenRA#11287]
Doesn't give Credits to player upon recovering nod base.

https://github.com/OpenRA/OpenRA/pull/11280

**Comment by Biofreak1987** [comment]
You have to sell the construction yard, like in the original. It's worth $2500.

**Comment by jtyle6** [comment]
Ok, odd.

**Comment by jtyle6** [comment]
Should have read that the briefing
