### ISSUE TITLE
System.NullReferenceException after starting the game (crash) (Windows 10)

### ISSUE THREAD

**Issue by pnoepel** [OpenRA/OpenRA#11309]
Hi,

from one day to another, I'm unable to start the game anymore.

This is the description out of the exception log:

Red Alert Mod at Version release-20160508
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei OpenRA.Map..ctor(ModData modData, IReadOnlyPackage package)
   bei OpenRA.ModData.PrepareMap(String uid)
   bei OpenRA.Game.StartGame(String mapUID, WorldType type)
   bei OpenRA.Game.LoadShellMap()
   bei OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   bei OpenRA.Game.InitializeMod(String mod, Arguments args)
   bei OpenRA.Game.Initialize(Arguments args)
   bei OpenRA.Program.Run(String[] args)
   bei OpenRA.Program.Main(String[] args)

Greetings
pnoepel

**Comment by pchote** [comment]
Have you modified any files inside the OpenRA install directory, or installed any custom shellmaps from the resource center?

**Comment by pchote** [comment]
The exception message suggests that the shellmap (the battle that plays behind the main menu) has become corrupted or has gone missing for some reason.  You should also check that your anti-virus hasn't quarantined any of the OpenRA files.

**Comment by pchote** [comment]
This doesn't appear to be a bug (on our end), so closing.
