### ISSUE TITLE
Modding Guides "Actor-Upgrades" not working properly

### ISSUE THREAD

**Issue by Divadawm** [OpenRA/OpenRA#11313]
hello,

I followed step by step instruction guide "Actor-Upgrades," a crash is generated when the upgrade "laser" and apply, let the attached report "exception":

```
Tiberian Dawn Mod Version at release-20151224
on map 268a0231dc35d5d2054d7b165be64c452d2183c6 (Pirates & Emperors by Psydev).
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of the type `System.InvalidOperationException`: Actor Does not-have trait of the type` OpenRA.Traits.IDefaultVisibility`
   to OpenRA.TraitDictionary.TraitContainer`1.Get (UInt32 actor)
   to OpenRA.TraitDictionary.Get [T] (Actor actor)
   to OpenRA.Actor.Trait [T] ()
   to OpenRA.Actor..ctor (World world, String name, TypeDictionary initDict)
   to OpenRA.World.CreateActor (Boolean addToWorld, String name, TypeDictionary initDict)
   to OpenRA.World.CreateActor (String name, TypeDictionary initDict)
   to OpenRA.Mods.Common.Traits.Production. <DoProduction> c__AnonStorey1. <> m__0 (World w)
   to OpenRA.World.Tick ()
   to OpenRA.Game.InnerLogicTick (OrderManager OrderManager)
   to OpenRA.Game.LogicTick ()
   to OpenRA.Game.Loop ()
   to OpenRA.Game.Run ()
   to OpenRA.Program.Run (String [] args)
   to OpenRA.Program.Main (String [] args)
```

Ps: i'am french

**Comment by MurtoTheRay** [comment]
I've had this problem before too. At the moment you need to attach an "AlwaysVisible:" trait to the upgrade actor definition.

**Comment by pchote** [comment]
I added a note to the wiki page that the examples no longer work.  I don't have the time to fix them properly myself.

**Comment by lawando** [comment]
@pchote I used conditional actors upgrades for my RA Upgrade Mod based on dummy actors that grant a prerequisite once produced in conjunction with `GrantConditionOnPrerequisite` which triggers change of armaments, multipliers or other things. If this is the recommended way to use actor upgrades, I can update the wiki page accordingly.

**Comment by GraionDilach** [comment]
@lawando You need to see that conditions were called as upgrades up til a point in last year/two years ago and the tutorials on that site are still using the traits' old names from that era. GlobalUpgradable is GrantConditionOnPrerequsite for example.

**Comment by mazarf** [comment]
I've updated this guide to use the condition traits.  I left out the segment on UpgradeMinEnabledLevel, UpgradeMaxEnabledLevel, etc.  because I don't see an equivalent in the current release.  Also the segment on purchasable upgrades still needs to be updated.

**Comment by abcdefg30** [comment]
Thanks for tackling the examples. I updated the last one and renamed the page to "Conditions": https://github.com/OpenRA/OpenRA/wiki/Conditions
