### ISSUE TITLE
Odd "Restart Mission" Menu button placement

### ISSUE THREAD

**Issue by xrabohrok** [OpenRA/OpenRA#11318]
This is a little thing, and I seem to recall it was kind like this originally, but the "Restart Mission" button should be front and center of a mission failure screen.  It was jarring enough where I spent a minute or two clicking things at random, looking...

Right now, it's like this:
I just _eat it_, Tanya walks in front of a Tesla coil, and dies.  Dang.  I want to restart, but the screen looks like this.
![where](https://cloud.githubusercontent.com/assets/3222168/15381131/602c3c0e-1d42-11e6-97e7-331b8f710ce5.png)

After looking and looking, I just say screw it, and quit.  Lo and Behold.
![oh](https://cloud.githubusercontent.com/assets/3222168/15381143/7df4f69a-1d42-11e6-92b7-6a7800557b8e.png)

Personally, I think it could be better.

**Comment by GraionDilach** [comment]
To the system's defense, the Restart button was "hidden" in this same way in the Westwood games.

**Comment by xrabohrok** [comment]
Sure. But we also found it prudent to add right-click controls...

**Comment by pchote** [comment]
It might make sense to replace the surrender button, which is otherwise disabled, with restart in this case.

**Comment by noobmapmaker** [comment]
Just like to add that it is difficult to find. 

AND it seems that if you win the game you are unable to restart the game, only quit.
