### ISSUE TITLE
Gas bomb idea for Red Alert

### ISSUE THREAD

**Issue by sajwang** [OpenRA/OpenRA#11315]
This might be a bit ambitious for me (toyed around with the idea for a few hours, couldn't figure it out), but I just wanted to throw out an idea:

A chemical weapon- mustard gas, basically. The thought was to basically have a badger drop a bomb that detonates to create a Tiberium-like zone (minus the visceroid transformation). Graphically, nothing ambitious, just an explosion followed by the playersmoke animation.

I attempted to the bomb paradrop as a "vehicle" which can be deployed to detonate like the demolition truck, thus creating the smoke.

Has anyone tried something similar to that already? If so, I'd like to play around with it to see how it was done.

**Comment by HenrytheSlav** [comment]
I would probably use badger to drop it (modify parabombs to drop single bomb and change the werhead, including a flare spawned in middle.)

**Comment by GraionDilach** [comment]
For modding support, please open a topic at http://www.sleipnirstuff.com/forum/viewforum.php?f=83 next time.

Yep, starting at the parabomb is a good idea. You can chain a lot of `SpreadDamageWarhead`s with `Delay` to simulate a damage-over-time effect (an example case is at the `Nuke` weapon).

**Comment by sajwang** [comment]
Alright, I'll play around with it a little more and then post on Sleipinir's Stuff if I have any follow up, then.

**Comment by sajwang** [comment]
Looks like I got it to work but it's going to need some refinement. I might follow up on Slepinir's stuff.

Thanks both of you

**Comment by sajwang** [comment]
Link to Slepinir's Stuff thread is here: http://www.sleipnirstuff.com/forum/viewtopic.php?f=83&p=296096#296096
