### ISSUE TITLE
Gobbled rendering with AMD Radeon Graphics

### ISSUE THREAD

**Issue by kiroxsu** [OpenRA/OpenRA#11324]
Hello, 
I started up the game for this first time on a seperate computer which is not older then a year. 
My game ended up having a "seizure". 
![remove](https://cloud.githubusercontent.com/assets/19477553/15406229/e674ed88-1e05-11e6-8af5-588853189d7b.png)
After booting it up again it still has the "seizure". 
I did tab out for a bit but my mouse went missing during the "seizure" and I was unable to 
quit the game by any normal means.
The mouse is premamently gone after booting it up a third time. 

After reinstalling it I still have a problem with the "seizure" going on. 
I attempted to start a game and the problem is still all over the screen.
My mouse was however working fine, only tabbing out once.

EDIT: I use Windows 7 with a system type of 64-bit operating system. My graphics card is _AMD Radeon Graphics Processor_.

Cheers,
-kiroxsu

**Comment by obrakmann** [comment]
What's your OS and which graphics card do you use?

**Comment by reaperrr** [comment]
@kiroxsu If it's not a hardware defect, a driver issue is the most likely reason.

For what it's worth, I have a Radeon 7790 and Windows 7 x64 as well, and OpenRA works just fine.

My driver version is Crimson 16.3.2, so maybe a driver update would fix this for you.

**Comment by obrakmann** [comment]
Since this is almost certainly a driver issue, I don't think we can do much here anymore.
