### ISSUE TITLE
Naming of difficulty levels is inconsistent

### ISSUE THREAD

**Issue by rosannaf** [OpenRA/OpenRA#11322]
Some missions have medium; others have normal.

**Comment by jaZzKCS** [comment]
The missions are subject to regular change and spruce up and far from finished. In addition there are also numerous difficulty levels missing still for various missions. The final spruce up will also make sure the naming of aforementioned difficulty levels is consistent.

**Comment by HenrytheSlav** [comment]
Cross-referencing into campaign issues so it gets noticed when we will be polishing/finishing the campaigns. #4989, #4988, #9287.

**Comment by obrakmann** [comment]
Looks like only Intervention and Survival01 use medium, the others all use easy, normal, hard and tough.
