### ISSUE TITLE
Spies Can Be Seen

### ISSUE THREAD

**Issue by bratwiz** [OpenRA/OpenRA#11335]
I'm playing the latest stable release 20160508 and apparently spies can be seen. I sent some over to my enemy's base and he said he could see them, they looked like spies-- not like his own units, and his base defenses killed them. Apparently they were cheap, low-budget spies. Beware imitations!

**Comment by pi99y** [comment]
Just checking: Did you disguise them (selected a spy and targeted an enemy unit)? They will look like enemy unit to you too...

**Comment by bratwiz** [comment]
I built the spies, and sent them over to my enemy's base. It was his units and base defenses that killed them. They passed through all of my units unmolested. He was playing allies so did not have dogs or anything that could have sniffed them out. He did not specifically target them. The units and base defenses reacted on their own.

**Comment by obrakmann** [comment]
Yes. Enemy units will detect spies as long as they are not disguised. You disguise spies by selecting the spy and right-clicking on an enemy infantry unit, whereupon your spy takes on the enemy unit's appearance - color, weapons and all - and shows a little moving eye symbol on its top right to indicate that it's disguised. Play the fifth allied mission ("Tanya's tale") to try it out for yourself.

**Comment by bratwiz** [comment]
Okay. Thanks. Is this a different behavior than in the original RA game? I don't recall it working like that? We played RA not too long ago and all the other factions just saw the spy as one of their own soldiers.

**Comment by abcdefg30** [comment]
Yeah, it is different from original RA and works rather like RA2.

**Comment by bratwiz** [comment]
Hmm - thanks for the info. 

    On Sunday, May 22, 2016 6:17 PM, abcdefg30 <notifications@github.com> wrote:
 
 

 Yeah, it is different from original RA and works rather like RA2.—
