### ISSUE TITLE
Blue lines in Spec / Replay mode when zooming out

### ISSUE THREAD

**Issue by ShadowA** [OpenRA/OpenRA#11332]
Blue horizontal lines appear in Spec / Replay modes when zooming out (0,5x or 0,25x)
Doesn't happen all the times, very varaible behaviour.

![2016-05-21 23_51_41-openra](https://cloud.githubusercontent.com/assets/16516251/15450999/0f18366e-1faf-11e6-96e5-220baa15155b.png)

**Comment by obrakmann** [comment]
I guess this'll end up being a driver or hardware bug. What GPU and operating system are you using?

**Comment by ShadowA** [comment]
GeForce GT 640 and Win 8.

Some other spectators on the chat reported the same issue.

**Comment by pchote** [comment]
This is a known and very old (going back to at least 2011) issue on nvidia hardware. This was the main reason i objected to adding extra zoom levels for so long.

**Comment by ShadowA** [comment]
@pchote 
Ok I see.

On the side note, despite this esthetical issue, I really loved this new implementation in the spec / replay mode and I almost use it every time ^_^
