### ISSUE TITLE
OpenRA.Utility.exe ra --extract does not work as described on linux

### ISSUE THREAD

**Issue by nice-hat** [OpenRA/OpenRA#11344]
OpenRA.Utility.exe ra --extract does not work as described here: https://github.com/OpenRA/OpenRA/wiki/Game-Content on a debian GNU/linux system. Steps to reproduce:
1. put MAIN.MIX from "Red Alert Allied" CD into folder $Home/.openra/Content/ra
2. open terminal and do:
```
cd /usr/share/games/openra
mono --debug ./OpenRA.Utility.exe ra --extract movies1.mix
```

Expected result: file movies1.mix in folder /usr/share/games/openra.

Actual result: The following error message
```
Error: Utility application crashed. See utility.log for details

Unhandled Exception:
System.IO.FileNotFoundException: File not found: movies1.mix
File name: 'movies1.mix'
  at OpenRA.FileSystem.FileSystem.Open (System.String filename) <0x41312470 + 0x000af> in <filename unknown>:0 
  at OpenRA.Mods.Common.UtilityCommands.ExtractFilesCommand.Run (OpenRA.ModData modData, System.String[] args) <0x413373f0 + 0x0009d> in <filename unknown>:0 
  at OpenRA.Utility.Program.Main (System.String[] args) <0x412d4040 + 0x005f0> in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: File not found: movies1.mix
File name: 'movies1.mix'
  at OpenRA.FileSystem.FileSystem.Open (System.String filename) <0x41312470 + 0x000af> in <filename unknown>:0 
  at OpenRA.Mods.Common.UtilityCommands.ExtractFilesCommand.Run (OpenRA.ModData modData, System.String[] args) <0x413373f0 + 0x0009d> in <filename unknown>:0 
  at OpenRA.Utility.Program.Main (System.String[] args) <0x412d4040 + 0x005f0> in <filename unknown>:0 
```

In fact, when in the same folder as MAIN.MIX and typing
```
mono /usr/share/games/openra/OpenRA.Utility.exe ra --extract MAIN.MIX
```
it says
```
MAIN.MIX saved.
```
but nothing else happens.

Am I missing something concerning usage of the utility? Is there a technical reason not to just have the program take two arguments, namely file name of the archive (MAIN.MIX) and file name of the desired file to extract?

**Comment by chrisforbes** [comment]
Your normal user account won't be allowed to write to `/usr/share/games/openra`.

**Comment by nice-hat** [comment]
While this is true, the error message has nothing to do with it. But, to be sure, I did
```
cd /usr/share/games/openra
chmod 777 .
mono --debug ./OpenRA.Utility.exe ra --extract movies1.mix
```
with the same result. Same result if I copy MAIN.MIX to /root/.openra/Content/ra and run the commands as root.

**Comment by pchote** [comment]
> Is there a technical reason not to just have the program take two arguments, namely file name of the archive (MAIN.MIX) and file name of the desired file to extract?

The extract command is there to extract files referenced by a mod.  Extracting files from an arbitrary archive is a somewhat different use case.

The next release should include some mod asset installer improvements that will make this silly song and dance for installing fmvs unnecessary.

**Comment by Ludo444** [comment]
Same issue here with Debian 9.

> The extract command is there to extract files referenced by a mod. Extracting files from an arbitrary archive is a somewhat different use case.

Is it bug then or are we doing something wrong?

**Comment by nice-hat** [comment]
By the way, I am willing to read code to try and figure out what the utility does. However, I have no experience with C# so it is extremely difficult for me to figure out what actually happens in
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Utility/Program.cs
(especially, what is the result of lines 60, 62, 63 and 84?)

I am afraid, the question what actually happens when the utility is run with the --extract command will only be solved by one of you who know the code providing an answer.

**Comment by pchote** [comment]
> Is it a bug then or are we doing something wrong when executing command with MAIN.mix in Content/ra directory?

I don't have an answer for that - it is also possible that the wiki instructions are wrong.
The utility is not a good tool for this job, XCC mixer under wine is a much more usable tool for extracting files from arbitrary mixes.

The real fix here is to improve the content installer so that these manual steps aren't needed, which is something that i'm slowly working on for hopefully the next release.

**Comment by nice-hat** [comment]
Thanks for the hint, pchote. In fact, the XCC mixer works completely straightforward with wine. Although I have to admit that it feels weird to need a program that provides a free implementation of a proprietary operating system's API to run a free program on a free operating system. :-)

**Comment by pchote** [comment]
Indeed.  Fortunately #11375 should make that unnecessary from the next release on.
