### ISSUE TITLE
Mod Chooser freezes on Quit

### ISSUE THREAD

**Issue by zaklogician** [OpenRA/OpenRA#11343]
When in Pseudo-fullscreen mode, the Mod Chooser freezes on pressing the Quit button. The freeze does not happen in Windowed mode.

**To reproduce:**
1. Start OpenRA with any mod selected.
2. Ensure that the game runs in Pseudo-fullscreen mode.
3. Click Mods.
4. In the Mod Chooser, click Quit.

**What happens?**

The application freezes. The Mod Chooser remains visible, but it does not react to any further mouse clicks or key presses.

**What I expected to happen?**

The application terminates.

**Relevant Information**

No exception is thrown and `exception.log` is not created.

Last 5 lines of `debug.log`: 

```
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
Could not find collection 'dialog'
```

**Version Info**

OpenRA release-20160508, Mono JIT compiler version 4.4.0, on Linux 4.5.4-1-ARCH

**Comment by pchote** [comment]
Mono 4.4 is still in alpha, and may be buggy.  Can you reproduce this with mono 4.2?

**Comment by zaklogician** [comment]
@pchote Downgraded to Stable 4.2.1.102, issue persists.

**Comment by pchote** [comment]
Can you please try to reproduce this with the new `playtest-20160904`?

**Comment by reaperrr** [comment]
Mod Chooser has been removed, closing.
