### ISSUE TITLE
D2k Map Editor: Grenadier bounds aren't cropped

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#11351]
Compared to everything else in every mod AFAIK.

![openra-2016-05-24t143142z](https://cloud.githubusercontent.com/assets/1136302/15507773/3f4cf28c-21cd-11e6-8a7c-c618808901a2.png)

**Comment by reaperrr** [comment]
The grenadier uses an .shp, iirc.

**Comment by pchote** [comment]
This happens because the actor sidebar sets the size based on the union of the Renderable bounds.  If we ever get around to defining a proper general "editor metadata" trait then a custom display size could be included there.

**Comment by Mailaender** [comment]
Using https://github.com/OpenRA/OpenRA/issues/2344 will probably fix this as well.
