### ISSUE TITLE
replay: crash GetExternalIP

### ISSUE THREAD

**Issue by derestle-htwg** [OpenRA/OpenRA#11357]
unfortunatelly, github doesn't accept my zipped replay:(

Red Alert Mod at Version release-20160508
on map 3dfd7c90747516ebde1a80e70ba22bd4bee60f65 (High & Low by Captain Mel).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.Reflection.TargetInvocationException`: Ein Aufrufziel hat einen Ausnahmefehler verursacht.
Inner Exception of type `System.NullReferenceException`: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
     bei OpenRA.Mods.Common.Widgets.Logic.LobbyUtils.GetExternalIP(Int32 clientIndex, OrderManager orderManager)
   bei OpenRA.Mods.Common.Widgets.Logic.ClientTooltipLogic..ctor(Widget widget, TooltipContainerWidget tooltipContainer, OrderManager orderManager, Int32 clientIndex)
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei OpenRA.ObjectCreator.CreateUsingArgs(ConstructorInfo ctor, Dictionary`2 args)
   bei OpenRA.ObjectCreator.CreateObject[T](String className, Dictionary`2 args)
   bei OpenRA.Widgets.Widget.<PostInit>c__AnonStorey0.<>m__0(String l)
   bei System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   bei System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   bei System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   bei OpenRA.Widgets.Widget.PostInit(WidgetArgs args)
   bei OpenRA.WidgetLoader.LoadWidget(WidgetArgs args, Widget parent, MiniYamlNode node)
   bei OpenRA.WidgetLoader.LoadWidget(WidgetArgs args, Widget parent, String w)
   bei OpenRA.Widgets.Ui.LoadWidget(String id, Widget parent, WidgetArgs args)
   bei OpenRA.Mods.Common.Widgets.TooltipContainerWidget.SetTooltip(String id, WidgetArgs args)
   bei OpenRA.Mods.Common.Widgets.ClientTooltipRegionWidget.MouseEntered()
   bei OpenRA.Widgets.Ui.HandleInput(MouseInput mi)
   bei OpenRA.DefaultInputHandler.<OnMouseInput>c__AnonStorey2.<>m__0()
   bei OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   bei OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input)
   bei OpenRA.Platforms.Default.Sdl2Input.PumpInput(IInputHandler inputHandler)
   bei OpenRA.Platforms.Default.Sdl2GraphicsDevice.PumpInput(IInputHandler inputHandler)
   bei OpenRA.Renderer.EndFrame(IInputHandler inputHandler)
   bei OpenRA.Game.RenderTick()
   bei OpenRA.Game.Loop()
   bei OpenRA.Game.Run()
   bei OpenRA.Program.Run(String[] args)
   bei OpenRA.Program.Main(String[] args)

**Comment by abcdefg30** [comment]
Duplicate of #11246. Thanks for the report though!

And, thanks for trying to upload the replay, but I don't think we need it, I can reproduce this with almost all of my replays as well. :)
