### ISSUE TITLE
Red Alert Enemy Units Off Map

### ISSUE THREAD

**Issue by lottilux** [OpenRA/OpenRA#11350]
After desperately searching for the last remaining enemy units we just surrendered and found these units off map and in parachute mode :)

![openra_bug](https://cloud.githubusercontent.com/assets/19551529/15502924/28d1a964-21b7-11e6-8a2d-bb2a7e073a37.png)

**Comment by GraionDilach** [comment]
Duplicate of #9750.

**Comment by lottilux** [comment]
Yep, you're right. I'll close it then
