### ISSUE TITLE
Allow tilesets to allocate multiple sheets.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#11359]
This is something I mentioned some months ago already - http://logs.openra.net/?year=2016&month=02&day=07#12:00:08 - but IIRC it didn't got anywhere since then.

Might be a prereq for maps defining custom tileset additions even?

**Comment by pchote** [comment]
Most of the work for this was done in #10246.

**Comment by pchote** [comment]
This was fixed by #18982.
