### ISSUE TITLE
dependency problems prevent configuration of openra

### ISSUE THREAD

**Issue by alepcat1710** [OpenRA/OpenRA#11360]
Hello.
This is my OS details:

**Distributor ID:	Ubuntu
Description:	Ubuntu 16.04 LTS
Release:	16.04
Codename:	xenial**

I got this problem

> Unpacking openra (20160508.release) ...
> dpkg: dependency problems prevent configuration of openra:
>  openra depends on mono-runtime (>= 2.10); however:
>   Package mono-runtime is not installed.
>  openra depends on libmono-system-core4.0-cil; however:
>   Package libmono-system-core4.0-cil is not installed.
>  openra depends on libmono-system-drawing4.0-cil; however:
>   Package libmono-system-drawing4.0-cil is not installed.
>  openra depends on libmono-system-data4.0-cil; however:
>   Package libmono-system-data4.0-cil is not installed.
>  openra depends on libmono-system-numerics4.0-cil; however:
>   Package libmono-system-numerics4.0-cil is not installed.
>  openra depends on libmono-system-runtime-serialization4.0-cil; however:
>   Package libmono-system-runtime-serialization4.0-cil is not installed.
>  openra depends on libmono-system-xml-linq4.0-cil; however:
>   Package libmono-system-xml-linq4.0-cil is not installed.
>  openra depends on libsdl2 | libsdl2-2.0-0; however:
>   Package libsdl2 is not installed.
>   Package libsdl2-2.0-0 is not installed.
> 
> dpkg: error processing package openra (--install):
>  dependency problems - leaving unconfigured

**Comment by GraionDilach** [comment]
http://askubuntu.com/a/40050 sounds like a solution.

**Comment by GraionDilach** [comment]
That actually sounds interesting because I was unaware Ubuntu pushed out gdebi as the default package installer, which did dealt with issues like this without a problem.

**Comment by alepcat1710** [comment]
Already solved this issue. 
Just use the method you say.
$ sudo apt-get -f install
