### ISSUE TITLE
Fix helis being pushed off map pls.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#11366]
How do I img tags here?

https://lh3.googleusercontent.com/-tsKlx_ssdOg/V0kzecGEjKI/AAAAAAAABuE/KbSa4SWIOXc5IlpkcNoAFKf3A8MBpoglACCo/s697/helis%2Boff%2Bmap%2Bbug.JPG

**Comment by obrakmann** [comment]
This is tracked in #9552, closing as duplicate.
