### ISSUE TITLE
my menu buttons won't show up!

### ISSUE THREAD

**Issue by GeneralJMan** [OpenRA/OpenRA#11371]
When I load up OpenRA it ggoes straight to tiberian dawn and the menu buttons that say things like Quit, Settings, Multiplayer, and etc don't show up! What should I do?

**Comment by Townes27** [comment]
ctrl+shift+h

**Comment by GeneralJMan** [comment]
that just gets rid of the rec camera thingy

**Comment by Townes27** [comment]
rec camera thingy?

**Comment by GraionDilach** [comment]
Did you switched resolutions lately to smaller or something similar? (You can ofc remove your My Documents/OpenRA/settings.yaml so it would revert back to default).

**Comment by pchote** [comment]
We can't act on this without more info, so closing.
