### ISSUE TITLE
TD: Missions screen is too small for mission names

### ISSUE THREAD

**Issue by Biofreak1987** [OpenRA/OpenRA#11388]
See screenshot:

![missions_screen](https://cloud.githubusercontent.com/assets/4711816/15753570/00a3e968-28f4-11e6-93a8-273ee3ee2988.jpg)

I dunno if I should shorten the names or if the missions screen should receive a redesign. The names are as follows:

- Destroy the Mammoth Tank Facility
- Recapture The Ezekiel's Wheel (a)
- Recapture The Ezekiel's Wheel (b)

And probably some other missions that haven't been ported yet.

**Comment by pchote** [comment]
If you can find the longest mission name then we can make the window wide enough for it to fit.
This is just a temporary workaround anyway, until we have proper campaign progression.

**Comment by Biofreak1987** [comment]
In that case it would be:

Restore GDI Presence Near Salzburg

or

Restore GDI Presence Near Salzburg (a), since it's the mission gdi08a

**Comment by obrakmann** [comment]
We can't just simply increase the size of the window, because it's made to exactly match the FMV dimensions.

**Comment by pchote** [comment]
I was thinking that we could increase the height (going into the description, which is uncomfortably short) to keep the aspect ratio the same.

**Comment by K4T** [comment]
All too long names could be trimmed with "..." and when the mouse cursor is above trimmed item, then the item would begin to scroll to reveal the rest of the name or simple tooltip with full name could be displayed.

What do you think?
