### ISSUE TITLE
Add support for GIMP palette *.gpl files

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#11385]
https://github.com/PintaProject/Pinta/blob/7a6408db10534aff4ba5c14333b606b6324e82e7/Pinta.Core/Classes/Palette.cs#L183 can be used as a template to parse the file. It would add a file format to the engine that can be edited with free software across platforms.

**Comment by GraionDilach** [comment]
This palette format isn't strict with the 256 color limit. I am indifferent on it though, consider this as a friendly warning.

**Comment by pchote** [comment]
:+1: to adding additional palette formats.  This format appears to be a simple list of r,g,b and then a descriptive name (which we would ignore).  We could add a lint rule to verify that any palette referenced by a mod in this format had <= 256 colours.

**Comment by reaperrr** [comment]
If we simply skip the header (everything before the first valid color) and do not bother explicitly reading the header string, we could implicitly add support for JASC-PAL as well which is basically identical except for the header and lack of descriptive names. JASC-PAL is supported by OS Palette Editor and older, abandonware versions of Paint Shop Pro, so it's used by some people in the C&C modding scene. 

```
JASC-PAL
0100
256
255 255 255
254 254 254
253 253 253
(...)
```

**Comment by GraionDilach** [comment]
@reaperrr JASC-PAL has been added by @penev92 in his fork for Age of Empires support a good while ago. The main issue which popped up with that is that the AoE PAL-JASCs use 0 0 0 as transparent instead the C&C color slot #0 approach.

This actually brings up issues with all these similar RGB formats.

**Comment by pchote** [comment]
@GraionDilach that's only a problem because these palette formats don't support alpha.

**Comment by x-a-n-a-x** [comment]
> pchote commented on 31 May 2016 
> 👍 to adding additional palette formats


Maybe one could reuse code from [Cyotek Color Picker](https://github.com/cyotek/Cyotek.Windows.Forms.ColorPicker).

It's open-source, C# and it already supports many palettes:
https://github.com/cyotek/Cyotek.Windows.Forms.ColorPicker#color-palettes-and-external-palette-files
- [Adobe Color Table (*.act)](https://github.com/cyotek/Cyotek.Windows.Forms.ColorPicker/blob/master/Cyotek.Windows.Forms.ColorPicker/AdobeColorTablePaletteSerializer.cs)
- Adobe PhotoShop Color Swatch (*.aco) - see also [this link](https://www.cyotek.com/blog/reading-photoshop-color-swatch-aco-files-using-csharp) and [this link](https://www.cyotek.com/blog/writing-photoshop-color-swatch-aco-files-using-csharp)
- Adobe Photoshop (*.ase) - see also [this link](https://www.cyotek.com/blog/reading-adobe-swatch-exchange-ase-files-using-csharp) and [this link](https://www.cyotek.com/blog/writing-adobe-swatch-exchange-ase-files-using-csharp)
- [GIMP (*.gpl)](https://github.com/cyotek/Cyotek.Windows.Forms.ColorPicker/blob/master/Cyotek.Windows.Forms.ColorPicker/GimpPaletteSerializer.cs)
- Deluxe Paint (*.bbm; *.lbm) [read only]
- [JASC (*.pal)](https://github.com/cyotek/Cyotek.Windows.Forms.ColorPicker/blob/master/Cyotek.Windows.Forms.ColorPicker/JascPaletteSerializer.cs)
- Paint.NET (*.txt)
- Raw RGB Triplets (*.pal)

**Comment by pchote** [comment]
> The main issue which popped up with that is that the AoE PAL-JASCs use 0 0 0 as transparent instead the C&C color slot #0 approach.

According to http://ppmforums.com/viewtopic.php?p=560299#560299 the transparency index is actually encoded in the shp frame header.  Not really useful for the current discussion, but still interesting.

**Comment by Smittytron** [comment]
Did #14851 fix this? (commit was cherry-picked)

**Comment by pchote** [comment]
It did.
