### ISSUE TITLE
TD: Missing scientist unit

### ISSUE THREAD

**Issue by Biofreak1987** [OpenRA/OpenRA#11387]
There are a few missions with scientist units: Dr. Mobius and Dr. Wong Hu Chan. 
Compared to civilians they...
- Can't attack.
- Feature different animations.
- Have different voice samples.
- Display their full name in the tooltip.

**Following missions use those scientists:**
- GDI 8b (Dr. Mobius)
- GDI 12a (Dr. Mobius)
- GDI 12b (Dr. Mobius)
- Nod 10a (Dr. Wong Hu Chan)

Required for: #4988

**Comment by Mailaender** [comment]
Which actor name do they have?

**Comment by Mailaender** [comment]
According to http://nyerguds.arsaneus-design.com/cnc95upd/inirules/infantry.ini it is `MOEBIUS` and `CHANG`.

**Comment by Biofreak1987** [comment]
I'm not sure if chan has his own voice set, since you don't control him in the campaign... but mobius does.
