### ISSUE TITLE
[RA] Destroyable civilian buildings and fuel drums

### ISSUE THREAD

**Issue by kruug** [OpenRA/OpenRA#11384]
In the original Red Alert, you could target fuel drums and civilian buildings to attack.  This allowed the player to clear out areas for building on.  Riflemen and grenadiers could target everything and Tanya could C4 buildings.

Currently, this does not exist in the current version (20160508).

**Comment by pchote** [comment]
Can you elaborate on where this isn't working for you?

This does exist in the default rules – you can see it in e.g. the Tournament Island map (civilian buildings and drums in the middle), and in the first allied mission (target the drums to kill the power before the civilians are killed).

**Comment by kruug** [comment]
Specifically the Bloody Delta map, to the North East of deploy point A.

**Comment by StexoO** [comment]
On release-20160508.
These barrels and buildings are your allies. :yum: 
I don't know if they have to be your enemies but you can attack them with Ctrl + Right click.

![neutral](https://cloud.githubusercontent.com/assets/8930382/15691838/61c80c20-278b-11e6-97cb-a50436a98b9b.png)

**Comment by kruug** [comment]
I'll have to double check, but Ctrl+Right click didn't work for me when I tried it.  Wouldn't they be more neutral than allies, since they'd be neutral to both players?

**Comment by MustaphaTR** [comment]
There is no neutral state in OpenRA, in fact it was only a thing in vanilla D2K. Current state is good but force fire supposed to work on these.

**Comment by kruug** [comment]
@StexoO: Just played through again this evening.  This issue is "resolved".  Thinking back, I believe this was a version back that I noticed the issue and never tried again after updating.
