### ISSUE TITLE
Building was inherited by this yaml

### ISSUE THREAD

**Issue by sajwang** [OpenRA/OpenRA#11400]
Inner Exception of type `OpenRA.YamlException`: <no filename available>:1632: Parent type `^Building` was already inherited by this yaml tree at <no filename available>:1446 (note: may be from a derived tree)

I have no idea where this comes from (I tried to track it), no idea where this came from. Anyone else ever encounter this?

Specifically, I try to remove a ~!structures.country function (removing the unique version of the building as well) and this exception results.

**Comment by sajwang** [comment]
Relevant code:

SAM:
	Inherits: ^Defense
	Buildable:
		Queue: Defense
		BuildPaletteOrder: 100
		Prerequisites: dome, ~structures.soviet,~!structures.cuba, ~techlevel.medium
	Valued:
		Cost: 750
	Tooltip:
		Name: SAM Site
		Description: Anti-Air base defense.\nRequires power to operate.\nCan detect cloaked units.\n  Strong vs Aircraft\n  Weak vs Ground units
	Building:
		Footprint: xx
		Dimensions: 2,1
	RequiresPower:
	CanPowerDown:
	DisabledOverlay:
	Health:
		HP: 400
	Armor:
		Type: Heavy
	RevealsShroud:
		Range: 5c0
	Bib:
		HasMinibib: Yes
	Turreted:
		TurnSpeed: 30
		InitialFacing: 0
	-WithSpriteBody:
	WithTurretedSpriteBody:
	Armament:
		Weapon: Nike
		MuzzleSequence: muzzle
	AttackTurreted:
	WithMuzzleOverlay:
	RenderRangeCircle:
		RangeCircleType: aa
	Power:
		Amount: -40
	DetectCloaked:
		Range: 5c0
	BodyOrientation:
		UseClassicFacingFudge: True

SAM.Cuba:
	Inherits: SAM
	Buildable:
		Queue: Defense
		BuildPaletteOrder: 100
		Prerequisites: dome, ~structures.cuba, ~techlevel.medium
	Valued:
		Cost: 750
	Tooltip:
		Name: Cuban SAM Site
		Description: Slightly more powerful than normal SAM sites. \nRequires power to operate.\nCan detect cloaked units.\n  Strong vs Aircraft\n  Weak vs Ground units
	Building:
		Footprint: xx
		Dimensions: 2,1
	RequiresPower:
	CanPowerDown:
	DisabledOverlay:
	Health:
		HP: 400
	Armor:
		Type: Heavy
	RevealsShroud:
		Range: 5c0
	Bib:
		HasMinibib: Yes
	Turreted:
		TurnSpeed: 30
		InitialFacing: 0
	WithTurretedSpriteBody:
	Armament:
		Weapon: NikeCuba
		MuzzleSequence: muzzle
	AttackTurreted:
	WithMuzzleOverlay:
	RenderRangeCircle:
		RangeCircleType: aa
	Power:
		Amount: -40
	DetectCloaked:
		Range: 5c0
	BodyOrientation:
		UseClassicFacingFudge: True
    RenderSprites:
        Image: SAM


These work as is but once I remove Sam.Cuba and !~structures.cuba from structures.yaml, this exception occurs. (the lines referred to in the exceptions log are typically in unrelated structures, as well.)

**Comment by abcdefg30** [comment]
Hm, that is weird. For me your changes worked, are you sure that the error occurs because of the SAM?
(One thing though: If you go into editing mode on your last comment, you can see that
`RenderSprites: Image: SAM` has spaces instead of tabs as indentation.
You should fix that if it is the same in your yaml files.)

**Comment by GraionDilach** [comment]
Do you have consistent line-endings? The default yamls use LF only. If you're modding on a Mac, your text editor might use CR alone and since the parser first founds LFs, it will assume the whole yaml uses LFs and that could actually merge every new line you added into a one single long one which can cause issues like that.

It would also explain why the line numberings go off.

**Comment by pchote** [comment]
> If you're modding on a Mac, your text editor might use CR alone

It's 2016, not the 1990's :wink:.  CR-only line endings died off with OS 9, well over a decade ago now.

**Comment by GraionDilach** [comment]
Well, I still keep "Running in the '90's". That and the sole thing I knew about Mac was ^.

Either way, I still keep my opinion about mixed line-endings as the cause of this issue.

**Comment by sajwang** [comment]
Strangely, leaving everything unchanged (not even reverting any changes, I mean leaving the file untouched, period) doesn't incur the exception, only when I edit something, SAM Site PR not. That includes rendering the sprite.

I'll check the line endings and report back.

**Comment by pchote** [comment]
I'll be that this has nothing to do with line endings, and probably little to do with the yaml snippets you have posted above.  There will be some other change that is being overlooked.

**Comment by Phrohdoh** [comment]
> since the parser first founds LFs, it will assume the whole yaml uses LFs

The parser makes no such assumptions.
https://github.com/OpenRA/OpenRA/blob/ad9fac57a3acd3f6f5cb09b3e80152469d652d2d/OpenRA.Game/MiniYaml.cs#L257

**Comment by sajwang** [comment]
Alright- so I was able to change spaced lines into indented ones using Notepad ++.

Then I eliminated Sam.cuba to get this exception:

Exception of type `System.AggregateException`: One or more errors occurred.
Inner Exception of type `OpenRA.YamlException`: <no filename available>:907: Parent type `SAM` was already inherited by this yaml tree at :0 (note: may be from a derived tree)
     at OpenRA.MiniYaml.ResolveInherits(String key, MiniYaml node, Dictionary`2 tree, Dictionary`2 inherited)

**Comment by sajwang** [comment]
Alright, got it- it works again. 

(this exception apparently occurs if you neglect to delete every line of a block dedicated to a unit/structure. Also, don't use the delete button. Backspace when deleting something.)
