### ISSUE TITLE
Tileset textures are never unloaded from VRAM.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#11419]
They are cached instead. This works great with gen1, but gen2 mods (for example, Yuri's Revenge with it's 5+1 (lunar was underutilized afterall) terrains all starting on 4096 sheetsizes (even RA2 temperate has 4096) end up a major danger to VRAM utilization.

This, along with #11359 will cause a lot of problems if mods with custom terrain (D-Day, Twisted Insurrection, Project Phantom) decide to give a try at porting over.

**Comment by pchote** [comment]
Can you identify where they are being cached and/or leaked?  The textures are associated with the `Theater` class, not `TileSet`, and should in theory be disposed along with the rest of the world.

**Comment by pchote** [comment]
Using the OSX OpenGL debugger I can confirm that we are correctly unloading tileset textures at least there.

**Comment by pchote** [comment]
Please reopen if you can provide a repro case.

**Comment by abcdefg30** [comment]
I don't know if it is related, but I often get this when I load maps in the RA2 mod:
```
GL Error: 1285
   at OpenRA.Platforms.Default.OpenGL.CheckGLError()
   at OpenRA.Platforms.Default.Texture.SetData(Byte[] colors, Int32 width, Int32 height)
   at OpenRA.Graphics.Sheet.GetTexture()
   at OpenRA.Graphics.SpriteRenderer.DrawVertexBuffer(IVertexBuffer`1 buffer, Int32 start, Int32 length, PrimitiveType type, Sheet sheet, BlendMode blendMode)
   at OpenRA.Graphics.TerrainSpriteLayer.Draw(Viewport viewport)
   at OpenRA.Graphics.TerrainRenderer.Draw(WorldRenderer wr, Viewport viewport)
   at OpenRA.Graphics.WorldRenderer.Draw()
   at OpenRA.Game.RenderTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by GraionDilach** [comment]
I was monitoring the memory usage earlier today. Did the following:

started AS
loaded testmap (empty map with 10 players, each having a starting slot and three mines, no preplaced resource, all AI, with me spectating, tileset is only the LAT grass tiles of RA2 temperate to keep it within the 512 sheetsize)
abandoned game immediately
restarted game
abandoned game
restarted game - decided to watch this one
got a VRAM crash in the first minute

Yes, I'm still on my despised Intel HD2000, but without restarting the game I can watch 30-40 minutes without a crash (depends on action). Somewhere VRAM is getting leaked for sure. I'm willing to create a tileset package for RA2 containing the YR-Terrain Expansion tiles as well, if that helps debugging this.

**Comment by GraionDilach** [comment]
TBH, after that 30-40 minutes, I get out-of-memory (not VRAM) crashes even.

**Comment by pchote** [comment]
Please use a debugger that can tell you the actual vram usage (texture vs vbo vs other stuff).  As it stands your description doesnt match the way the engine should be working, so without that extra info the most likely explanation is a buggy driver.

**Comment by GraionDilach** [comment]
This turned out to be a bug of the Windows Intel driver. The Linux one has no such issues like this. O_o
