### ISSUE TITLE
TD Obelisk Charge Idea

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#11415]
Is there a way to implement a mechanic that after the Obelisk has fully charged up for a shot that it can retain its charge for five seconds?

This would allow it to have another chance to fire its shot off instead of having to recharge the shot after the unit has died without using my idea for the Obelisk balance.

Obelisk Initial Charge Delay reduced to 1 from 50.

Obelisk Reload Delay increase to 75 from 40. (Requires more testing.) 

An idea that Pchote has explained is a charge decay which I personally like a lot too. Instead of holding a five second charge the charge would decay slowly instead at the same rate as the charge up for the Obelisk. Which would also prevent the complete charge rest. Personally, this idea I like a lot more.

**Comment by pizzaoverhead** [comment]
:+1: for charge decay. It's an intuitive addition.

**Comment by Apollo-X** [comment]
Alternatively you could just specify by ammo of sorts how many shots the charge holds (Like RA1 tesla coil) than some timed charge concept. The charge being 1 shot style is supposed to be the drawback of the obelisk in original design anyways so it can be overwhelmed in numbers.

**Comment by AoAGeneral** [comment]
If it was to act like the tesla coil this would be more destructive to armored units and become a very OP defense structure. Seeing as an Obelisk takes 3 shots to kill a mammoth I would prefer it to have the one charge shot setup. (Specially since a lot of vehicles get one shot as it is.)

The 1 charge style is the draw back for it to be overwhelmed quite true. But the problem is the charge up and targeting system itself. When the unit dies it resets the charge without firing a shot and has to recharge up again before it can fire. This makes the Obelisk a lot weaker and is very easily overwhelmed more so then I would like.

**Comment by GraionDilach** [comment]
In default RA (not OpenRA RA), the Tesla Coil could either attack infantry with 3 shots or attack noninfantry with a single shot from one charge. This logic is missing from OpenRA AFAIK.

**Comment by MustaphaTR** [comment]
In fact it attacks 3 times to vehicles too, but it deals 3x damage at once, if it manages to kill the vehicle in less than 3 hits other bolts goes to other units. I'm not sure if there is really an infantry like that in vanilla RA other way around should be possible for infantry if it can't be killed by one bolt.

**Comment by MustaphaTR** [comment]
In fact it attacks 3 times to vehicles too, but it deals 3x damage at once, if it manages to kill the vehicle in less than 3 hits other bolts goes to other units. I'm not sure if there is really an infantry like that in vanilla RA other way around should be possible for infantry if it can't be killed by one bolt.

**Comment by MustaphaTR** [comment]
In fact it attacks 3 times to vehicles too, but it deals 3x damage at once, if it manages to kill the vehicle in less than 3 hits other bolts goes to other units. I'm not sure if there is really an infantry like that in vanilla RA other way around should be possible for infantry if it can't be killed by one bolt.

**Comment by MustaphaTR** [comment]
In fact it attacks 3 times to vehicles too, but it deals 3x damage at once, if it manages to kill the vehicle in less than 3 hits other bolts goes to other units. I'm not sure if there is really an infantry like that in vanilla RA other way around should be possible for infantry if it can't be killed by one bolt.

**Comment by GraionDilach** [comment]
#11428 is a much better solution for the original problem than what has been brought up IMO.

**Comment by AoAGeneral** [comment]
Does this mean the target switches while its charging and still utilizing the full charge attack?

This can work as well. Only problem I could see this happening is if the unit hears the charge and steps back or allows the one unit to die after one Obelisk fires then sends in the rest. Allowing the initial charge to reset.

**Comment by AoAGeneral** [comment]
That didn't change the obelisk mechanic. Still works the same.

**Comment by GraionDilach** [comment]
Yes, because after I pointed out the benefits that PR would bring in, it immediately got rejected.
