### ISSUE TITLE
Sort the support powers countdowns

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#11413]
It's a feature request.
As a spectator you can't instantly know "who will launch the next atom bomb" when there are many players in a game, so it could be useful to sort the countdowns from the lowest to the highest.
It could be useful for the players too.

![many support powers](https://cloud.githubusercontent.com/assets/8930382/15837726/bebcad56-2c3a-11e6-899a-96000b8d836e.png)

**Comment by GraionDilach** [comment]
:-1:

Runtime sorting them would actually be confusing because the orders would change in any second, leading to take more time to associate the values to the respective sources and preventing skimming techniques being used for this.

**Comment by airetaM** [comment]
I like the idea because in games with many players i often dont know who will drop the next bomb. Would take too much time to search the long list of supers all the time. 
The system as it is now is absolutely confusing for me. 
Just looking at the top whoś bomb is next would help me much.

**Comment by x-a-n-a-x** [comment]
It remembers me of https://github.com/OpenRA/OpenRA/pull/8619

**Comment by abcdefg30** [comment]
Spectators will nowadays see whom a power belongs to in the support powers spectator tab.
