### ISSUE TITLE
Get rid of WithSpriteRotorOverlay

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#11427]
As mentioned in #9910, this trait is actually redundant now, because it's functionality can be completely replicated with `WithIdleOverlay` + aircraft upgrades.

**Comment by reaperrr** [comment]
For the record, I'm somewhat working on this, but haven't finished it yet mostly because the upgrade rule will be more work than the actual trait removal and yaml changes.

**Comment by pchote** [comment]
I assume the issue with the upgrade rules is knowing where to add the cruise upgrade without accidentally overwriting any existing definitions, right?

Personally, I would have the rule swap the rendering traits and then write a message prompting the upgrades to be set manually.

**Comment by GraionDilach** [comment]
I'd be moreso attach an additional upgrade like `rotor` to the affected actor's  `AirborneUpgrades` and check for that.

**Comment by reaperrr** [comment]
> I assume the issue with the upgrade rules is knowing where to add the cruise upgrade without accidentally overwriting any existing definitions, right?

That's just the icing on the cake. 
What put me off far more is that actors might have one rotor overlay without `@` separator, one with and one without, two with them, or even more than two. And each of them would need to be split into two idle overlays, so I'd have to make sure the upgrade rule won't write duplicate separators anywhere.

I just think that'd be far too much work for something that will rarely affect more than 2 or 3 actors per mod.

> Personally, I would have the rule swap the rendering traits and then write a message prompting the upgrades to be set manually.

I'll do that, then. Modders can take the manually fixed rules from our mods as reference, afterall.
