### ISSUE TITLE
Units told to guard stop guarding after killing one enemy.

### ISSUE THREAD

**Issue by anjew175** [OpenRA/OpenRA#11439]
As title, units given the order to guard will stop guarding once they target a unit

**Comment by FrenzyTime** [comment]
Same thing for Mechanics / Medics, after fully healing a friendly unit.

**Comment by WolfGaming** [comment]
Guard actually uses AttackMove and an inner MoveFollow order and not its own activity so I guess the AttackMove order isn't playing nice with the MoveFollow order, maybe replacing it with a normal move order going to the guards position?

**Comment by pchote** [comment]
AttackMove doesn't play nicely with anything, so this makes sense.

**Comment by WolfGaming** [comment]
Attack move should really be refactored, it was a mess last time I tried to work on it and I guess its still a mess. Guess its hard though since its so closely related to the move order which is a monster in and of itself.

**Comment by yaaaaa** [comment]
Same situation? https://github.com/OpenRA/OpenRA/issues/11156

**Comment by WolfGaming** [comment]
@yaaaaa No this is not the same thing, as your situation does not use AttackMove.
