### ISSUE TITLE
Add settings-option to turn off specific graphical numbers or symbols

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#11453]
such as unit-ranks , bounties and ore-dumps
in case someone wants a screenshot or recording without all that stuff being visible ... 

http://logs.openra.net/?year=2016&month=02&day=29#11:46:34

![numbers](https://cloud.githubusercontent.com/assets/9139965/16014567/fd17b9b8-3191-11e6-8c8e-55cfe6ddae07.png)

**Comment by SoScared** [comment]
Liking it. we already have available CTRL+H to turn off the U.I. This would be a nice addition to make great screenshots.

**Comment by pchote** [comment]
Bounties are no longer enabled by default, so this probably isn't needed anymore. Comment and complain if you disagree.
