### ISSUE TITLE
Output Disabled, no audio

### ISSUE THREAD

**Issue by Truth99A** [OpenRA/OpenRA#11465]
only 2 options in the output selection tab:
output disabled
output disabled

audio isn't working at all

**Comment by obrakmann** [comment]
Do you happen to not have speakers/headphones connected when you start the game? We've had various reports of things like this when people forgot to plug in their headphones or something.

**Comment by Truth99A** [comment]
I don't use headphones or speakers or anything like that, just my laptops built in speakers. The audio (from the game) use to work fine and I believe for a short while on the new update the sound also worked but after a while it stopped.
p.s this happened about a month ago XD audio is working fine on my computer

**Comment by obrakmann** [comment]
You mean audio in general works on your laptop, just not in OpenRA? Or do you mean that the problem happened a month ago and all is fine now?

Either way, if the problem persists or comes back, please try jacking in headphones anyway and see if it helps.

**Comment by Truth99A** [comment]
i mean that the audio on my laptop works fine, openra audio does not work at all
- i've tried plugging in headphones and speakers, it only has 2 options: Output disabled & Output disabled. picking the second one and restarting the game does nothing

**Comment by Truth99A** [comment]
hey!!! i found out how to fix it!!!!

go into C:\Users\**username**\Documents\OpenRA (windows 10) and go into the settings.yaml script, there under sound you'll find engine: null  
delete it and don't replace it with anything.
start up the game and bam! 
also if that doesn't work then simply delete the whole settings file and start up the game, the audio should come back. (note! uninstalling the game doesn't delete this file)

To the Dev's, i found out that the audio output default is set to "disabled" (#L27) , for some reason though there is a bug where if it is set to output disabled then the other options including default will no longer appear in the output selection tab.

**Comment by pchote** [comment]
Fixed by #11757.
