### ISSUE TITLE
Custom Resolutions or Pixel Quadrupling 

### ISSUE THREAD

**Issue by blackhandcommando** [OpenRA/OpenRA#11494]
Sorry if this is a double post, but I only found topics regarding the display resolution associated with the UI. Can we get an option for pixel quadrupling or custom resolutions that are not dependent on the systems resolution? 

For example I run on a 4k environment and even with pixel doubling I'm only down to 1080p which is still quite tricky to handle when playing online. Some people of my stream also wondered why we have to adjust the system resolutions everytime we start the game for the wanted resolution.

Is this a thing that could be done, or is there a relevant ticket allready?

**Comment by pchote** [comment]
Thanks for the report!  #10382 specs out the plan to fix this.
