### ISSUE TITLE
Add support for a non-proprietary OpenRA SHP format

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#11506]
While I couldn't find anything conclusive about the legal status of TD/RA SHP compression algorithms (though any patents covering them should have expired by now), at least the RLE zeros compression used by SHP(TS) is too generic to be patented/copyrighted.

Therefore, a possible approach might be to use the same compression(s) SHP(TS) uses and just use different file and frame headers.
For the file header, we could replace the always-zero uint16 at the start with some other value (or a string, maybe `ORASHP`).
For frame headers, compared to SHP(TS) we could simply throw out the (unused) 3-byte-align, the following uint32 RGBA radar color (not used by OpenRA), and the following uint32 (unused).

That way, it should be easy to add support for this format to OS SHP Builder and XCC Mixer (though at least some command-line encoder will be needed for platforms on which these don't run, of course).
A minor additional benefit would be that total filesize would decrease by 11 bytes per frame due to the slimmed down frame header (which could save about 6 KB per TS infantry shp with e1 sequences, for example) as a little extra benefit.

This should avoid any hypothetical problems with the proprietary nature of Westwood-developed SHP formats.

**Comment by Mailaender** [comment]
I also did a quick search. Westwood Studios didn't submit any patent claims and you also can't patent a whole file format, but rather inventions that are used in compression formats. As the SHP compression is mostly prior art anyway that doesn't apply. You also can't copyright a file format, but you can own the rights of a documentation describing it and your initial implementation is subject to copyright, but not the idea and concept behind it. Creating an incompatible derivative doesn't improve the legal situation and certainly doesn't help with modding.

https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/FileFormats/BlowfishKeyProvider.cs#L17 is one of the few code parts where I guess intellectual property is at least debatable. It looks to be converted from assembler language into C, but it already received several cleanups so it probably isn't identical to the original Westwood library. We never had access to official specifications nor the original source code, so there is no risk of this being a direct copy. There might be valid reason for a rewrite or improvement of existing file format parts to increase readability and ease maintenance. Legal affairs isn't a matter here.

**Comment by reaperrr** [comment]
Okay, thanks for shedding some light on this. I wasn't sure to what degree the file header layout might be proprietary, hence my suggestion.

**Comment by Mailaender** [comment]
I thought about adding support for https://en.wikipedia.org/wiki/ILBM which is exotic, but was used a lot at that time for 8 bit pixel art. Palette based cross platform Open Source software like http://pulkomandy.tk/projects/GrafX2 supports it. There is also a plugin for GIMP. https://github.com/unwind/gimpilbm

**Comment by Phrohdoh** [comment]
@reaperrr Can this be closed?

**Comment by reaperrr** [comment]
I guess so.
