### ISSUE TITLE
Engineers don't want to move to the unload area of the allied refineries

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#11507]
Release 20160508.
With the Alt key pressed I can't ask my engineer to move there, I get the repair cursor instead.

![insubordination](https://cloud.githubusercontent.com/assets/8930382/16282700/2f639038-38ca-11e6-93ba-a183d61e33d4.png)
![insubordination2](https://cloud.githubusercontent.com/assets/8930382/16282799/8f16b820-38ca-11e6-83d6-aa528e6940aa.png)

If the refinery is damaged I also have the repair cursor, even with the Alt key pressed.

![insubordination3](https://cloud.githubusercontent.com/assets/8930382/16282949/219e50f4-38cb-11e6-9a63-92970cbb77c5.png)

**Comment by pchote** [comment]
Related to #8128.

**Comment by abcdefg30** [comment]
This is possible on bleed.
