### ISSUE TITLE
Engineer can repair enemy building.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#11505]
STEPS TO REPRODUCE:
1)Capture an oil derrick
2)Have it damaged a little bit somehow
3)Have the derrick captured by a enemy player (The derrick should go underneath the fog of war)
4)Select a engineer and try to tell them to capture the derrick, it will give the repair option
5)Capture option will be restored once the derrick is revealed, but it you use the repair command and don't re-issue commands to the engineer they will just repair it.

I say oil derrick because that's what happened to me, but I bet it would work with any building.

**Comment by Phrohdoh** [comment]
Once the target is revealed we'll need to reevaluate what order should be given, and decide whether or not human interaction is necessary (can we automatically give the new order?).

**Comment by pchote** [comment]
The simpler and more correct fix (as a baseline, at least) is to properly validate the target before applying the repair, and have the engineer leave again if it fails.  This is what we do in most other unit -> building cases.

**Comment by epicelite** [comment]
Well double check that it actually does because I stopped the engineer just before he would of done it because it was the middle of a game and I needed him to capture it, but it looked like he was gonna fix it.

**Comment by obrakmann** [comment]
FWIW, there's a real bug here. The engineer enters the enemy building and is lost. Didn't check whether any repairing actually happened.

**Comment by TheRaffy** [comment]
Looks like my reported bug #12121 was somehow already known. Thanks to abcdefg30 for connecting the dots. That means I can prove this issue here with a replay. Feel free to check #12121.
Somebody also might wanna close my issue report, because of dupplication.  Thanks!
