### ISSUE TITLE
Crash  @ nuke

### ISSUE THREAD

**Issue by ThisBlunt** [OpenRA/OpenRA#11502]
Exception:
"Attempted to calculate the square root of a negative integer: -964165632"
 after second nuke..
![screen shot 2016-06-21 at 9 43 03 pm](https://cloud.githubusercontent.com/assets/14940856/16252081/5dda1756-37f9-11e6-8ebe-408d53ab0771.png)

at:

![screen shot 2016-06-21 at 9 43 13 pm](https://cloud.githubusercontent.com/assets/14940856/16252090/6a0f79b2-37f9-11e6-9cd1-e30ccd206f2a.png)

with mods:

http://pastebin.com/raw/6FVCZU8U

Don't know if this is a bug but I get this exception with a few modifications to the "Spread" subset of the Warhead trait by increasing 5c0 to 10c0. In the previous release I didn't run into this problem.

**Comment by abcdefg30** [comment]
Could you post the entire `exception.log`, please?

**Comment by ThisBlunt** [comment]
http://pastebin.com/raw/sK2akWa6
I suspect its the increase in smudge, destroy resource, or spread dmg

**Comment by ThisBlunt** [comment]
http://pastebin.com/raw/sK2akWa6

Values changed from original Atomic trait :
Warhead: SpreadDamage >10c0 
LeaveSmudge:
-second set: >10
-third set: >15
DestroyResource:
-second set: >10
-third set: >15

**Comment by pchote** [comment]
The only way this could be negative is if the length calculation overflows.

**Comment by ThisBlunt** [comment]
I'm sorry but what does that mean?

**Comment by abcdefg30** [comment]
Should be fixed by #13645.
