### ISSUE TITLE
Ore trucks look up for ore indefinitely in only one direction

### ISSUE THREAD

**Issue by StexoO** [OpenRA/OpenRA#11508]
Release 20160508.
I created a custom map with this configuration, __no ore and no ore mine__.
The ore truck starts from the refinery and goes to the bottom left of the map (until it reaches it) in order to find ore.
If it encounters an obstacle it comes back and retries forever.
The short lags are due to "Pathfinder" and "tick_activities" pikes.
![harvester infinite loop](https://cloud.githubusercontent.com/assets/8930382/16283570/945fe56a-38cd-11e6-9d6d-53ceeba3d0d8.gif)

It could stop searching after a while or try another direction.

**Comment by GraionDilach** [comment]
IIRC it stops if the map had ore (mined them all) without ways to replenish.

**Comment by Nelax** [comment]
Just out of curiousity. What's with the walled in MCV? You can just start a game with just yourself. No need to wall in an AI MCV.

**Comment by StexoO** [comment]
@Nelax The walled MCV is an AI and is here only to have another AI on the map. I could have put a power plant instead, or anything else.

**Comment by Mailaender** [comment]
Don't wall in the AI MCV. It has routine to start looking for a place to deploy. That will also cause performance problems.

**Comment by Phrohdoh** [comment]
This ticket isn't at all about performance and shouldn't be found when someone is searching for performance-related issues, so that label shouldn't be applied, IMO.

**Comment by obrakmann** [comment]
> I created a custom map with this configuration, no ore and no ore mine.

There's your error. Don't do that. We won't try to optimize for this situation.
