### ISSUE TITLE
OpenRA freezing every few seconds.

### ISSUE THREAD

**Issue by MurtoTheRay** [OpenRA/OpenRA#11548]
Recently i have been having a bug where, once i have had it open for a game or two, OpenRA will start freezing for a couple of seconds, then resume for a few seconds, then freeze and so on. I have tried a fresh install and the freezing does not lead to a crash but while it is frozen i am unable to interact with OpenRA at all. The freezing also affects other players in multiplayer.

This is my system's specification:

OS Name	Microsoft Windows 10 Pro
Version	10.0.10586 Build 10586
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	USER
System Manufacturer	Dell Inc.
System Model	Latitude E5440
System Type	x64-based PC
System SKU	Latitude E5440
Processor	Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz, 2501 Mhz, 2 Core(s), 4 Logical Processor(s)
BIOS Version/Date	Dell Inc. A01, 9/18/2013
SMBIOS Version	2.7
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Dell Inc.
BaseBoard Model	Not Available
BaseBoard Name	Base Board
Platform Role	Mobile
Secure Boot State	Off
PCR7 Configuration	Binding Not Possible
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume1
Locale	United States
Hardware Abstraction Layer	Version = "10.0.10586.420"
User Name	User\Steele
Time Zone	GMT Daylight Time
Installed Physical Memory (RAM)	4.00 GB
Total Physical Memory	3.91 GB
Available Physical Memory	1.12 GB
Total Virtual Memory	6.45 GB
Available Virtual Memory	2.26 GB
Page File Space	2.54 GB
Page File	C:\pagefile.sys
Hyper-V - VM Monitor Mode Extensions	Yes
Hyper-V - Second Level Address Translation Extensions	Yes
Hyper-V - Virtualization Enabled in Firmware	Yes
Hyper-V - Data Execution Protection	Yes

**Comment by pchote** [comment]
Does your perf.log say anything interesting?

**Comment by MurtoTheRay** [comment]
Here is the perf log: http://pastebin.com/MLEb6Z17

**Comment by Mailaender** [comment]
What network connection do you have?

**Comment by MurtoTheRay** [comment]
Wireless, however when my network connection fails the game still  allows me to click things, move my mouse around and hear the music but this all stops for duration of each freeze. I have also tried testing my network connection whilst this is happening and there have been no disconnects/slower speeds during.

**Comment by obrakmann** [comment]
How do other programs work when this happens? Does browsing the 'net still work, does a music player still play music, can you navigate in the explorer...? Also check your windows event log if there's anything suspicious in there.

**Comment by Mailaender** [comment]
Try if connecting to a wired connection improves things (it will at a certain degree, but not necessarily fix your disproportional problems). You can also do basic network quality measurements with http://www.pingtest.net/

**Comment by MurtoTheRay** [comment]
I don't see how my network could be an issue. The freezing persists outside of multiplayer games. Even the menu freezes. I will have to try to alt-tab out when this happens to see if it affects explorer, although I have been able to use mumble/discord whilst this is happening.

**Comment by Mailaender** [comment]
Your hardware looks capable enough.

**Comment by Mailaender** [comment]
Closing as no new info was provided since ~1 month and it doesn't seem the problem lies in our hands.

**Comment by Mailaender** [comment]
Try updating your graphics card drivers if the issue persists.
