### ISSUE TITLE
AttackGarrisoned-related bug

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#11552]
I cannot come up with a better title, if you have one feel free to change the title.
I was trying to reproduce #11454 when I came across this.

4d90361b8bcd9193f372756acfd7f33d05b0bde2

![ra-11454](https://cloud.githubusercontent.com/assets/4861023/16509613/6b40d81e-3f04-11e6-9895-e73cc17df177.gif)

**Comment by obrakmann** [comment]
Looks like an instance of #9404, where the visual position doesn't match the real position.

**Comment by pchote** [comment]
Does this only happen when you use the "alt to enter nearby transports" feature?  I think its more likely that feature isn't handling the enter-actor behaviour properly.

**Comment by obrakmann** [comment]
It does indeed only happen after alt-entering, and is a duplicate of #11454.
