### ISSUE TITLE
Deploying overrides queued actions (except MCV)

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#11582]
It seems the MCV is the only unit that can deploy after queued actions (waypoints). 
Other deployable units can't do that (APC, Chinook, Nuke Truck, ...) the deploy action will override all the previous queued actions.

For instance, it is impossible to tell a nuke truck to follow waypoints, then explode at the last waypoint. (Shift + RMB on the truck will make it explode instantly).
However, with a MCV, it's possible.

**Comment by WolfGaming** [comment]
At least for the Cargo trait (haven't looked at the Nuke Truck) we don't check in the ResolveOrder method if the order is queued and just cancel all queued activities.
