### ISSUE TITLE
Force firing on a submerged unit plays an explosion animation instead of splash

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#11584]
But does no damage. 

In RA mod, on bleed.

**Comment by pchote** [comment]
Ping @reaperrr: any thoughts on this one?  The cleanups in #12633 don't change this.

**Comment by reaperrr** [comment]
I think this would require fixing the `ImpactType`s to take target validity into consideration, but all attempts at this that I've made locally a few months ago caused regressions or would have made the yaml setup quite a bit more complicated, so I haven't looked into this for a while.

**Comment by Smittytron** [comment]
Seems to be splashing now. Was this fixed by #14058?

**Comment by reaperrr** [comment]
Earlier than that, but fixed in any case.
