### ISSUE TITLE
"Error:CodePage 936 not supported"

### ISSUE THREAD

**Issue by SolonPotam** [OpenRA/OpenRA#11591]
Here's Ubuntu 15.10 using Chinese language. After finishing downloading any of the three assets of dune 2000, Red Alert or Tiberian Dawn, it says "Error:CodePage 936 not supported". The release is 20160508. Could it be fixed? Or is there anything I should do? Thx!

**Comment by abcdefg30** [comment]
I think you can fix that by installing the `libmono-i18n4.0-all` package (see https://github.com/OpenRA/OpenRA/issues/11256#issuecomment-218277011).

**Comment by SolonPotam** [comment]
Solved! Thanks a lot! ^_^
And I also tried changing the system language to English and it also works, yet to install the package is much more convenient.
Thank you for your help!
