### ISSUE TITLE
LeavesTrails is bugged.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#11595]
![tfdfguf](https://cloud.githubusercontent.com/assets/1136302/16672484/b00c2fdc-44a6-11e6-8ef5-783fb1d7c5b3.gif)

When a unit starts moving, it skips the first cell. TS mod.

**Comment by chrisforbes** [comment]
This smells like a `MoveFirstPart` kind of headache...

**Comment by GraionDilach** [comment]
It isn't.

Looking at the yaml - it spawns a trail every 18 frame when idle and 6 frame when moving - the bug is that if remainingframes > state-delay (like here) then it doesn't refresh it with the new value.
