### ISSUE TITLE
Add white border to countdown timers

### ISSUE THREAD

**Issue by Raymond-cnc** [OpenRA/OpenRA#11590]
It is very hard to read the timers of players who have selected a dark color. Perhaps a white border would help them stand out against the fog of war.

**Comment by StexoO** [comment]
Related to https://github.com/OpenRA/OpenRA/issues/7592#issuecomment-77610285.

**Comment by abcdefg30** [comment]
How #11647 looks:
![timerbordera](https://cloud.githubusercontent.com/assets/7704140/16810705/537685dc-4925-11e6-9cf9-03b30e57cbfc.png)
![timerborderb](https://cloud.githubusercontent.com/assets/7704140/16810710/54f70346-4925-11e6-8ff7-d63c5872799f.png)
