### ISSUE TITLE
Destroying bridge makes units inop

### ISSUE THREAD

**Issue by djlists** [OpenRA/OpenRA#11606]
If a unit has a destination across a bridge when the bridge gets destroyed, the unit gets stuck and cannot be given new orders.

**Comment by pchote** [comment]
I'm surprised to confirm that this is real.  This is a nasty regression from somewhen (not sure when this broke, but it was present in at least the last release).

**Comment by obrakmann** [comment]
Looks a lot like #9378.

**Comment by StexoO** [comment]
It is the same behavior as #6684 which was fixed.

**Comment by pchote** [comment]
This regression was introduced by #7430.  The change from `CanEnterCell` &rarr; `CanMoveFreelyInto` wasn't explained or questioned there.
