### ISSUE TITLE
When building submaries, audio clip "Training" plays instead of "Building"

### ISSUE THREAD

**Issue by djlists** [OpenRA/OpenRA#11618]

**Comment by pchote** [comment]
This applies to all non-building queues in RA.

**Comment by GraionDilach** [comment]
Pretty sure that's how all C&Cs acted, with the Building sound only used on the building/defense (where existed) queues.

**Comment by pchote** [comment]
The original RA used Building for everything except infantry.

**Comment by SoScared** [comment]
I wouldn't mind hearing 'Building' for everything but the infantry. Makes sense.

**Comment by abcdefg30** [comment]
Is any other mod affected as well?
