### ISSUE TITLE
Helicopter does not remember / re-attack surfacing sub

### ISSUE THREAD

**Issue by djlists** [OpenRA/OpenRA#11617]
If you send a heli to attack a sub, the heli will stop shooting and remain hovering when the sub submerges. When the sub resurfaces, the heli needs to be told to attack again.

**Comment by pchote** [comment]
This is intentional behaviour.  Units drop targets that become inaccessible so that they can attack other things.

**Comment by djlists** [comment]
The heli's do not re-engage if they are idle and hovering over the submarine when it resurfaces.

**Comment by pchote** [comment]
Helis default to the "Hold Fire" stance to conserve ammo.  Use ctrl+z to cycle to a difference stance if you want them to auto-target enemies.

**Comment by airetaM** [comment]
If they would keep they'r attack mode on the sub, they would follow the submerged sub what is a bit unfair.
Was the case a few releases ago i think.
I let them fly with ctrl-A over the water, working well.

**Comment by KenSharp** [comment]
This isn't a bug...

**Comment by e1d1s1** [comment]
Ctrl+A or stance change is the way to go. If the sub moves, you probably wouldn't want to follow it everywhere it went, kind of cheat then. I do believe Classic RA would deal damage to subs from force fire of an area, but I think the current way it works in OpenRA is more "correct".
