### ISSUE TITLE
Remove additional "Kills/Death" column

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#11628]
from the statistic-screen , as it is wasting space and only adds useless information 

the original idea of this , was to sort of determine a "skill" by calculating "kills : deaths" which is a established form of measuring skill in some FPS's ( Battlefield for example)

since OpenRA's is containing (at this point) mostly RTS-games ... this column is useless ... 
as in realtime-strategy games there are more things important beside "killing units" to win a game 

@obrakmann 's player-experience is (imo) something that helps getting a column with more useful information

![statistic](https://cloud.githubusercontent.com/assets/9139965/16715035/ae38b690-46d5-11e6-812e-639aac1c556d.png)

**Comment by Mailaender** [comment]
I guess this should be replaced by "assets destroyed" / "assets lost" both calculated in credits to indicate positive outcomes of army encounters, which is an indicator of who is ahead.

**Comment by abcdefg30** [comment]
This should be fixed by #11645 now.
