### ISSUE TITLE
In progress for -1 minute

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#11646]
Release-20160508.
It happens when a game has just started.

![t minus one](https://cloud.githubusercontent.com/assets/8930382/16809217/c123d1c6-491f-11e6-9cc5-7db2c6556d0a.png)

**Comment by chrisforbes** [comment]
Suspect two different clocks being compared here...

**Comment by abc013** [comment]
@chrisforbes: you're right, I tried to fix this but noticed that `startTime` _is not_ the starttime.
There is a difference of ca. 100 seconds between the real starttime and `startTime` on my computer...

**Comment by pchote** [comment]
This will be fixed as part of my MP player list / master server API upgrade PR.
