### ISSUE TITLE
Cannot move units

### ISSUE THREAD

**Issue by vadimkantorov** [OpenRA/OpenRA#11652]
Just installed OpenRA for the first time. Opened Singleplayer of Red Alert. Can select units, but using left-click won't move selected units.

Very possibly I'm missing something very simple...

**Comment by Phrohdoh** [comment]
By default right-click is the order giving button.
So select with left click and give movement / attack / etc orders with right click.

**Comment by vadimkantorov** [comment]
Thanks! The game loads very fast btw, much faster than RA2 back in the day :)
