### ISSUE TITLE
Error downloading 'FuzzyLogicLibrary.1.2.0'

### ISSUE THREAD

**Issue by jtyle6** [OpenRA/OpenRA#11655]
I tried to redownload, remake. Now I get this.

```
make dependencies
Fetching FuzzyLogicLibrary from NuGet.
Feeds used:
  /Users/JoelTyler/.local/share/NuGet/Cache
  /Users/JoelTyler/.nuget/packages/
  https://www.nuget.org/api/v2/

Attempting to gather dependency information for package 'FuzzyLogicLibrary.1.2.0' with respect to project '/Users/JoelTyler/Documents/OpenRA/thirdparty/download', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'FuzzyLogicLibrary.1.2.0' with DependencyBehavior 'Lowest'
Resolving actions to install package 'FuzzyLogicLibrary.1.2.0'
Resolved actions to install package 'FuzzyLogicLibrary.1.2.0'
  GET https://www.nuget.org/api/v2/package/FuzzyLogicLibrary/1.2.0
  OK https://www.nuget.org/api/v2/package/FuzzyLogicLibrary/1.2.0 1623ms
Acquiring lock for the installation of FuzzyLogicLibrary 1.2.0
Acquired lock for the installation of FuzzyLogicLibrary 1.2.0
Installing FuzzyLogicLibrary 1.2.0.
Error downloading 'FuzzyLogicLibrary.1.2.0' from 'https://www.nuget.org/api/v2/package/FuzzyLogicLibrary/1.2.0'.
The UTC time represented when the offset is applied must be between year 0 and 10,000.
Parameter name: offset
WARNING: Install failed. Rolling back...
Error downloading 'FuzzyLogicLibrary.1.2.0' from 'https://www.nuget.org/api/v2/package/FuzzyLogicLibrary/1.2.0'.
  The UTC time represented when the offset is applied must be between year 0 and 10,000.
  Parameter name: offset
make: *** [cli-dependencies] Error 1
```
Error downloading 'FuzzyLogicLibrary.1.2.0' from 'https://www.nuget.org/api/v2/package/FuzzyLogicLibrary/1.2.0'.
The UTC time represented when the offset is applied must be between year 0 and 10,000.
Parameter name: offset
WARNING: Install failed. Rolling back...
Error downloading 'FuzzyLogicLibrary.1.2.0' from 'https://www.nuget.org/api/v2/package/FuzzyLogicLibrary/1.2.0'.
  The UTC time represented when the offset is applied must be between year 0 and 10,000.
  Parameter name: offset

**Comment by GraionDilach** [comment]
What is your timezone?

**Comment by GraionDilach** [comment]
This sounds like a mono 4.4 bug with NuGet 3  - https://bugzilla.xamarin.com/show_bug.cgi?id=37970 - sorry @Mailaender, but definitely doesn't seem Windows's bug.

**Comment by Mailaender** [comment]
https://bugzilla.xamarin.com/show_bug.cgi?id=40916 is marked as fixed. Try updating Mono.

**Comment by jtyle6** [comment]
The os is Mac os x 10.10.5.
@GraionDilach Time zone is AEST (GMT+10).
@Mailaender I have reinstalled Mono and I still get the error.

**Comment by Mailaender** [comment]
This issue is still out of our hands. Try uninstalling NuGet. We provide a backfall script.

**Comment by Phrohdoh** [comment]
There is no need to uninstall NuGet.
From the thirdparty dependencies invoke the `fetch-thirdparty-deps-osx.sh` script.

**Comment by Mailaender** [comment]
That has nothing to do with the NuGet dependencies which get downloaded by https://github.com/OpenRA/OpenRA/blob/bleed/thirdparty/fetch-thirdparty-deps.sh

**Comment by jtyle6** [comment]
I have booted into a 10.9 partition and downloaded there.

**Comment by Mailaender** [comment]
Suggest you report your issue at https://bugzilla.xamarin.com if it isn't already listed there.
