### ISSUE TITLE
Player Info Panel does not become active until you hover the pointer over the players latency

### ISSUE THREAD

**Issue by DeclanMurphyCit** [OpenRA/OpenRA#11664]
In a Game Lobby, I have noticed that when you hover the cursor over a spawn point on the map it displays the player name and team name.

For some reason this information panel only becomes active after you hover over any of the players latency indicator (Green / Orange / Red / Grey rectangle).

I'm guessing this is a bug? It's useful on large maps where players have similar colors to each other but might have selected the wrong team.

**Comment by obrakmann** [comment]
I can't reproduce this on either -release or bleed.

**Comment by Mailaender** [comment]
Me neither.

**Comment by DeclanMurphyCit** [comment]
Ok I'll try figure out the steps in reproducing this. Maybe it has something to do with when I alt-tab to a different window.
