### ISSUE TITLE
Force Fire on a unit that gets hidden by fog

### ISSUE THREAD

**Issue by DeclanMurphyCit** [OpenRA/OpenRA#11663]
When you force fire on a point on the map where a unit is visible but then gets hidden by fog. The force firing unit will stop their action and just auto attack the closest enemy.

The best example of this having a V2 that is ordered to force fire on a location which was revealed by a spy plane.

I think force firing should override the "can't fire into fog" fix

**Comment by GraionDilach** [comment]
Regardless of force-firing, you targeted a unit.

You can force-fire into the fog but then force-fire into the fog.

**Comment by obrakmann** [comment]
Cannot reproduce this on bleed

**Comment by DeclanMurphyCit** [comment]
I tried it on the last release and it occurred. I will test it out on the latest version once I set up the proper development environment.

**Comment by Raymond-cnc** [comment]
I don't think they should be able to "track" the unit if it moves. If they get covered by fog, attacks should be made at last cell that was forced fired on. Imagine ordering your artillery to fire at certain coordinates, doesn't matter if they can " see" or not.

**Comment by WolfGaming** [comment]
I guess we currently don't differentiate between a force fire and normal attack if the target is an actor which imo is wrong since theoretically a fast unit could mess up the targeting on a group of slow units if we force fired a V2 on it, force fire should always target the cell imo.

I've thrown my 2 cents.

**Comment by Raymond-cnc** [comment]
Only reason I can think of where it's necessary to focus fire on a specific actor is in debug mode when trying to simulate by attacking your own units..

**Comment by GraionDilach** [comment]
>force fire should always target the cell

Hell no.

While this game so far doesn't have chain/shrapnel logics (#11624), such logics would give reasons forceattacking unit a lot of times. In RA2, it was a common trick to attack trees-nearby-to-the-target with elite Prism Tanks (especially if they were near buildings) and let the shrapnel destroy stuff (elite Prism Tanks are complete broken afterall).

**Comment by WolfGaming** [comment]
but thats the definition of force firing, shooting a specific place, if I wanted to fire against a unit I would just attack it normally.
If attacking a tree to make shrapnel that damages targets was op then that wasn't balanced correctly and wouldn't be the fault of the feature.

**Comment by GraionDilach** [comment]
It was imba because of the high damage output the shrapnel had and not because of the forcefire. Also, the MOBA (DoTA, LoL, etc.) denying feature also relies on forcefiring units. I am also quite certain that forcefiring targeted units instead of their position already in Warcraft 2 (which is the oldest RTS I played a lot and not just tried out). Your definition about forcefire is very wrong there.

**Comment by Phrohdoh** [comment]
@WolfGaming It is valid to want to force-fire against units (owned, allied, neutral).

**Comment by WolfGaming** [comment]
Well whatever it doesn't matter to me that much, I just figure that if I click somewhere with force fire I want them to shoot that spot and not follow the unit that could be running away from me while I am getting ready to shoot there.

For example if I am aiming into the middle of a pack of units and the unit moves away from all the other ones I would've wasted the aoe damage of that shot.

Force firing would still allow you to kill owned, allied or neutral the actor just wouldn't be aiming at them specifically.

That's just my opinion though and I guess I am overruled here.

**Comment by GraionDilach** [comment]
Attack Ground != forcefire though, that has a separate button in every game I know of.

**Comment by WolfGaming** [comment]
If I remember correctly starcraft 2 does it only with the attack button,
age of empires 2 too.

**Comment by GraionDilach** [comment]
AoE2 has a crater button on the catapults for attacking ground. Never played Starcraft (2), but a simple search on the internet shows modders asking how to restore Attack Ground itself - https://www.sc2mapster.com/forums/development/map-development/1171-attack-ground/.

**Comment by WolfGaming** [comment]
well consider me convinced then, I say we need attack ground though and if I complete my pet project of an Ability/Order viewer we could implement that without adding another hidden hotkey.

**Comment by pchote** [comment]
The current consensus from several other messy issues and other places of community discussion is that Artillery and V2 in the RA mod should "attack ground" when force firing.  This can be implemented via a flag on `AttackBase`.

Adding to the milestone for the next playtest as part of the fog targeting fixes.
