### ISSUE TITLE
Replays on bleed crash with an out-of-sync exception

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#11660]
some time during playback, not immediately at the start or end.

Edit: commit 5b61206
[This replay](https://seacloud.cc/d/5d1adbebce/files/?p=/ora_bug11660_replay_desync.orarep) desyncs in frame 4476.

**Comment by GraionDilach** [comment]
I already get that replay crashed on https://github.com/OpenRA/OpenRA/commit/8c8fa2d258f45d797547a732478efab7ad912447 and reading from the logs where you were talking about SharedRandom usage, I'd blame https://github.com/OpenRA/OpenRA/pull/10684/files#diff-90995d9756122b52b0ff4cedc81af1b8R59.

**Comment by Holloweye** [comment]
Crash when settings building in multiplayer or capturing a oil derrick

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/issues/11721 for a suggested fix.
