### ISSUE TITLE
Additional hotkey modifiers for producing units

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#11675]
Hello,

currently there are 3 "**modifiers**" for producing units(/buildings): 
shift+lmb (add 5 units),  shift+rmb (remove 5 units),  ctrl+rmb (remove all units of type)

**I would propose adding some more**, most importantly:
shift+ctrl+rmb  (**cancel all units in queue**, e.g. "all infantry")

And as important, but more controversial:
**rmb->hold->release for holding production** and rmb->release for cancelling one unit. Since you use the latter way more often and there is no way of cancelling during production right now.
I think the behaviour as it is now is annoying, only that one got used to it :D ("hold! ""hold!""cancelled!")
EDIT: Middle-mouse button cancels during production. However, not all mouses have middle mouse buttons!

_[please ignore following section, see comment below]_
Also, an infinite modifier would be nice: 
ctrl+lmb (adds one unit to a "infinite queue")

The infinite queue behaviour could be like this:
- produce x units as ordred, then go to next order
- if there are no more ordinary orders, check infinite queue entries and add one round of them to the production queue order list
- in the UI a little infinity sign would show before the ammount of units ordered in one round
- additional unit orders of the same type add/substract allways from the infinite queue (so there cannot be an ordinary and infinite order in parallel)

i.e. suppose 5 rocket troopers are in a queue. Shift+crl+lmb(rocket soldier icon) would add 5 more rocket soldiers and transform this order into an infinite queue order. (Rocket sodier icon)^(inf 10)

Thanks, i hope we will see at least rmb-hold and crtl+shift-cancel soon in the future :)

**Comment by GraionDilach** [comment]
The current release should already have middle-click to cancel directly and ctrl-click to cancel the whole queue.

See the discusion of #10169 why infinite queue will not happen.

**Comment by CH4Code** [comment]
Thanks, I checked it. Middle-mouse-button works fine but ctrl+rmb only cancels all units of ONE TYPE as stated above, not the whole queue. Is this a bug?

**Comment by pchote** [comment]
pausing/cancelling the queue would be better exposed by right clicking on the queue tab.

**Comment by Fahrradkette** [comment]
Sorry for hijacking this issue but would it make sense to be able to swap queued production? Like I expect an infantry attack so I queue a few e1 and e3 after. Now I see that my enemy is setting up a heavy vehicle attack, it would be great if I could simply (drag drop) move the stack of e1 to the end of the queue. Imagine a Starcraft 1 queue...

**Comment by CH4Code** [comment]
I don't think this is a good idea. The queue order is only present in the imagination of the player, it has no representation in the production menu. And a starcraft queue would deviate too far from RA, imho.

**Comment by pchote** [comment]
* #15764 introduced a ctrl + left click shortcut to queue an actor at the front of the stack
* #15021 introduced an infinite build queue concept for custom maps and mods to use.
