### ISSUE TITLE
Listing an actor in Cargo.InitialUnits which grants an upgrade through Passenger won't be applied to the transport.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#11674]

**Comment by WolfGaming** [comment]
This is simply an oversight, InitialUnits is enumerated inside the constructor for the Cargo trait, it does not do any of the upgrade checking that's done inside ReserveSpace and Load.

**Comment by penev92** [comment]
> InitialUnits don't grant LoadedCondition or PassengerConditions

> You need to make passenger leave and enter back to Conditions to be granted properly.
