### ISSUE TITLE
[RA] Official Map Pool: Alter Seaside 2 (6 players) - aesthetics

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#11683]
[**Seaside 2, current**](http://resource.openra.net/maps/13261/), (6 players)

Changes:
Aesthetics - trees, debris, ore

[**Seaside 2, altered**](http://resource.openra.net/maps/15228/)

![seaside 2 compare](https://cloud.githubusercontent.com/assets/2715583/17044580/a5f72166-4fc1-11e6-84ab-58aff64adf04.png)

![seaside 2 compare](https://cloud.githubusercontent.com/assets/2715583/17044585/b423a30e-4fc1-11e6-92a8-0de8494b0364.png)

**Comment by Micr0Bit** [comment]
did you add a gem-mine in the middle ? ...i think the biggest problem on this map is the lack of $$ 
there was probably a couple of old gem(rail)mines on their (until they got removed from the game) but nobody ever bothered to add the new gem mines

**Comment by SoScared** [comment]
I didn't. There were some usless gem mines that I removed. I'll just add a gem mine (or 2?) in the middle.

**Comment by Micr0Bit** [comment]
idc. ... just feels like there should be something in the middle ... producing something ... 
you could also just go for ore mines

**Comment by SoScared** [comment]
Updated. I added 2 regular ore mines in betwwen the middle gems. Not viewable in the preview image but they're there.

**Comment by Micr0Bit** [comment]
:+1:
