### ISSUE TITLE
[RA] Official Map Pool: Alter Snowy Island (6 players) - aesthetics, ridge/shoreline tweaks

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#11681]
[**Snowy Island, current**](http://resource.openra.net/maps/12448/), (6 players)

Changes:
Minor aesthetics - ore patches and ridge/shoreline fixes.

[**Snowy Island, altered**](http://resource.openra.net/maps/13121/), playtested multiplayer.

![snowy island compared](https://cloud.githubusercontent.com/assets/2715583/17041761/8d0dba70-4fa8-11e6-8618-f95a19ce2e09.png)

![snowy island compare](https://cloud.githubusercontent.com/assets/2715583/17041766/92d28418-4fa8-11e6-9585-06dae12b35f8.png)

**Comment by Micr0Bit** [comment]
:+1:
