### ISSUE TITLE
[RA] Official Map Pool: Alter Warwind (2 players) - balance

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#11682]
[**Warwind, current**](http://resource.openra.net/maps/12545/), (2 players)

Changes:
Split oil derric access in middle, minor aesthetics

[**Warwind, altered**](http://resource.openra.net/maps/15165/)

![warwind compare](https://cloud.githubusercontent.com/assets/2715583/17042592/17a345a0-4faf-11e6-87ef-86982410f8ba.png)

![warwind compare](https://cloud.githubusercontent.com/assets/2715583/17042596/1d56afd2-4faf-11e6-8ad0-d65fe2219751.png)

**Comment by cjshmyr** [comment]
:+1: good changes!

**Comment by Micr0Bit** [comment]
:+1:
