### ISSUE TITLE
[RA] Official Map Pool: Northwest Passage (2 players) - Aesthetics

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#11714]
[**Northwest Passage, current**](http://resource.openra.net/maps/8564/), (2 players)

Changes:
Minor aesthetic overhaul

[**Northwest Passage, altered**](http://resource.openra.net/maps/15326/)

![northwest passage compare](https://cloud.githubusercontent.com/assets/2715583/17105841/2e128184-5289-11e6-952c-24f9843865c9.png)

![northwest passage compare](https://cloud.githubusercontent.com/assets/2715583/17105846/36589c66-5289-11e6-9864-a2e07fded575.png)

**Comment by GraionDilach** [comment]
Uhm, isn't there a typo in this map's name (Passage?)

**Comment by SoScared** [comment]
Indeed. Fixed.

**Comment by Raymond-cnc** [comment]
As the original map creator, I must say this looks great. Didn't imagine it making it to the map pool, awesome!

**Comment by SoScared** [comment]
Thanks Ray! It's always feels a bit edgy editing other peoples map so I'm glad you approve.

**Comment by Raymond-cnc** [comment]
The added water makes sense seeing as I was referring to the actual northwest passage!

**Comment by Raymond-cnc** [comment]
http://resource.openra.net/maps/16075/

Newest edit, fixed mines.
