### ISSUE TITLE
OpenRA refuses to launch after detecting OpenGL 1.1 support despite system supporting OpenGL 2.1.

### ISSUE THREAD

**Issue by aaronfranke** [OpenRA/OpenRA#11717]
OS: Windows 10, GPU: Intel Mobile 965 Express Chipset Family

OpenRA: release-20160508

Intel only officially supports OpenGL 1.1 on this GPU but it is simple to add unofficial support for OpenGL 2.1. This works for launching Minecraft 1.10.2, which requires OpenGL 2.1, and Minecraft 1.10.2 does not launch on the drivers Intel provides. However, OpenRA refuses to try to launch due to it incorrectly detecting the maximum OpenGL version. I am confident that if OpenRA skipped this check and launched anyway then it would work fine. 

A fix for this issue could simply be to check for the Intel Mobile 965 Express Chipset Family GPU and ignore whatever the detected OpenGL version is and instead assume that it is 2.1.

exception.log: 

> Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: No suitable renderers were found. Check graphics.log for details.
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

graphics.log: 

> Unsupported OpenGL version: 1.1.0

>OpenGL Information:
Vendor: Microsoft Corporation
Note:  The default driver provided by Microsoft does not include full OpenGL support.
Please install the latest drivers from your graphics card manufacturer's website.

>Renderer: GDI Generic
GL Version: 1.1.0
Shader Version: 
Available extensions:
GL_WIN_swap_hint GL_EXT_bgra GL_EXT_paletted_texture
System.InvalidProgramException: OpenGL Version Error: See graphics.log for details.
   at OpenRA.Platforms.Default.OpenGL.Initialize()
   at OpenRA.Platforms.Default.Sdl2GraphicsDevice..ctor(Size windowSize, WindowMode windowMode)
   at OpenRA.Platforms.Default.DeviceFactory.CreateGraphics(Size size, WindowMode windowMode)
   at OpenRA.Renderer.CreateDevice(Assembly platformDll, Int32 width, Int32 height, WindowMode window)
   at OpenRA.Renderer..ctor(GraphicSettings graphicSettings, ServerSettings serverSettings)
   at OpenRA.Game.Initialize(Arguments args)
Unsupported OpenGL version: 1.1.0

>OpenGL Information:
Vendor: Microsoft Corporation
Note:  The default driver provided by Microsoft does not include full OpenGL support.
Please install the latest drivers from your graphics card manufacturer's website.

>Renderer: GDI Generic
GL Version: 1.1.0
Shader Version: 
Available extensions:
GL_WIN_swap_hint GL_EXT_bgra GL_EXT_paletted_texture
System.InvalidProgramException: OpenGL Version Error: See graphics.log for details.
   at OpenRA.Platforms.Default.OpenGL.Initialize()
   at OpenRA.Platforms.Default.Sdl2GraphicsDevice..ctor(Size windowSize, WindowMode windowMode)
   at OpenRA.Platforms.Default.DeviceFactory.CreateGraphics(Size size, WindowMode windowMode)
   at OpenRA.Renderer.CreateDevice(Assembly platformDll, Int32 width, Int32 height, WindowMode window)
   at OpenRA.Renderer..ctor(GraphicSettings graphicSettings, ServerSettings serverSettings)
   at OpenRA.Game.Initialize(Arguments args)

**Comment by pchote** [comment]
I'm quite confident that this won't work for OpenRA. We require driver features that arent provided by microsofts rather poor default GL driver.

**Comment by aaronfranke** [comment]
Which driver do you recommend I use? At the moment, I'm using a driver designed for future Intel chipsets, but still technically works. The default driver is 1 MB, the one I'm using is 18 MB.

**Comment by Mailaender** [comment]
We can't guarantee that the game will be playable with such old cards. Our graphical prerequisites are more demanding than one might think. See https://github.com/OpenRA/OpenRA/wiki/Requirements#hardware

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/wiki/FAQ#no-suitable-renderers-were-found

**Comment by aaronfranke** [comment]
I managed to get OpenRA to run by installing Linux instead of Windows 10. It detects my OpenGL version as "2.1 Mesa 11.0.2". Such a shame that OpenRA doesn't run on the same hardware but with Windows 10 instead, it should be supported on all platforms equally IMO.

**Comment by pchote** [comment]
Indeed it is a shame, but there's not much that we can do about broken drivers - that's a problem between Intel, Microsoft, and (unfortunately) yourself.

**Comment by Mailaender** [comment]
Yeah, it is a known fact that Linux Intel driver support is better for legacy cards. We also documented it at http://pcgamingwiki.com/wiki/OpenRA#System_requirements
