### ISSUE TITLE
[RA] Official Map Pool: Coastal Influence (8 players) - Aesthetics, balance

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#11711]
[**Coastal Influence, current**](http://resource.openra.net/maps/11907/), (8 players)

Changes:
Less smudgy ore patches, added ore mines, aesthetic overhaul

[**Coastal Influence, altered**](http://resource.openra.net/maps/15321/)

![coastal influence compare](https://cloud.githubusercontent.com/assets/2715583/17097934/39801a6e-5260-11e6-991c-788f5e124555.png)

![coastal influence compare](https://cloud.githubusercontent.com/assets/2715583/17097937/3e913ca4-5260-11e6-9336-be9a5a503756.png)

**Comment by SoScared** [comment]
Not happy about the ore patches. Will revise.

**Comment by chrisforbes** [comment]
I like this a lot better, but I still think this map is a bit of a disaster.

Spawn D (in the revised version) is particularly awful, with the bridges
choking off ore access. The mine below spawn H is also not good -- that
patch grows unusually slowly due to a lot of the random walks failing.
