### ISSUE TITLE
D2K - A small cliff problem

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#11712]
It is passable. Must be easy to fix but need to check original game first.
![wrong cliff](https://cloud.githubusercontent.com/assets/7933210/17096725/7a4e8ece-5263-11e6-9567-d665e66db893.png)

**Comment by MustaphaTR** [comment]
Looks like left-bottom tile of that 2x2 part isn't passable in original game.

**Comment by abcdefg30** [comment]
I can't reproduce this:
![d2kbug](https://cloud.githubusercontent.com/assets/7704140/17271156/0a920384-5675-11e6-831b-2a57876c8692.gif)

**Comment by MustaphaTR** [comment]
Maybe neightboring tiles have problems. Try in Atr3b nearby to start. There was where i tried.

**Comment by abcdefg30** [comment]
Can't reproduce it there either. I guess someone fixed this in the meantime.
