### ISSUE TITLE
Optionally mute on unfocus

### ISSUE THREAD

**Issue by chrisforbes** [OpenRA/OpenRA#11736]
It would be nice if the game could mute itself when in the background.

**Comment by Mailaender** [comment]
Such a setting has it's own entry http://pcgamingwiki.com/wiki/OpenRA#Audio_settings so indeed it seems to be an often requested polish feature.

**Comment by PunkPun** [comment]
Mute button / keybind have been added. In singleplayer the game pauses when in menu, which obviously mutes the game
