### ISSUE TITLE
Chat textbox should be disabled in replays

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#11743]
It's currently possible to type and send messages, which are then eaten by the game.  Disabling the text field would be an easy polish win.

**Comment by FrenzyTime** [comment]
I use it currently in my Youtube videos, to write commentaries 
(I don't have a mic, and there are better ways  of doing that ^_^ but that's my current solution) 
(For instance : https://www.youtube.com/watch?v=52Wx4Gc9sOA )

**Comment by obrakmann** [comment]
https://xkcd.com/1172/ :D

**Comment by FrenzyTime** [comment]
^^

**Comment by Raymond-cnc** [comment]
In replays you can use the chatbox to go back and read people conversations from when they were in the lobby.. kind of creepy.
