### ISSUE TITLE
Helicopters will freeze mid-air if stopped while landing or taking off.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#11748]
This is most easily reproduced by stopping a helicopter (`LandWhenIdle: false`) when it is taking off from or landing on a helipad.

The easy and hacky fix is to make landing and taking off non-cancellable activities.  A better fix should have some understanding of the next step, and choose whether the helicopter should complete its move or undo it before leaving the activity.

**Comment by matjaeck** [comment]
This will hopefully be fixed by #16509.
