### ISSUE TITLE
custom unit crashes game on production

### ISSUE THREAD

**Issue by Aquilar** [OpenRA/OpenRA#11756]
I'm trying to make a custom unit for my mod but i get this crash

Red Alert Expanded Mod at Version v1
on map 065791667982ccb50a4c3acdd6c752430db9a4a8 (Behind The Veil by Kyrylo Silin).
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `OpenRA.YamlException`: ActorInfo("mobu") failed to initialize because of the following:
Missing:
OpenRA.Mods.Common.Traits.ArmamentInfo 
Unresolved:
OpenRA.Mods.Common.Traits.WithMuzzleOverlayInfo: { OpenRA.Mods.Common.Traits.AttackBaseInfo, OpenRA.Mods.Common.Traits.ArmamentInfo }

   at OpenRA.ActorInfo.TraitsInConstructOrder()
   at OpenRA.Actor..ctor(World world, String name, TypeDictionary initDict)
   at OpenRA.World.CreateActor(Boolean addToWorld, String name, TypeDictionary initDict)
   at OpenRA.World.CreateActor(String name, TypeDictionary initDict)
   at OpenRA.Mods.Common.Traits.Production.<DoProduction>c__AnonStorey1.<>m__0(World w)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

and this is the units code.

MOBU:
	Inherits: ^Tank
	Buildable:
		Queue: Vehicle
		BuildPaletteOrder: 160
		Prerequisites: fix, stek, ~vehicles.soviet, ~techlevel.high
	Valued:
		Cost: 1500
	Tooltip:
		Name: Mobile Bunker
		Description:  unique infantry transport.\n  Strong vs nothing\n  Weak vs everything
	Health:
		HP: 1000
	Armor:
		Type: Heavy
	Mobile:
		Speed: 71
		Crushes: wall, mine, crate, infantry, heavywall
		UpgradeTypes: notmobile
		UpgradeMaxEnabledLevel: 0
	RevealsShroud:
		Range: 5c0
	AttackGarrisoned:
		Armaments: garrisoned
		PortOffsets: 384,0,128, 224,-341,128, -224,-341,128, -384,0,128, -224,341,128, 224,341,128
		PortYaws: 0, 176, 341, 512, 682, 853
		PortCones: 88, 88, 88, 88, 88, 88
	AutoTarget:
	Cargo:
		Types: Infantry
		MaxWeight: 5
		PipCount: 5
		LoadingUpgrades: notmobile
	ProducibleWithLevel:
		Prerequisites: vehicles.upgraded

so the question is does Openra support garrisioned attackers in vehicles and if not is it possible it can be added at a later date?

**Comment by obrakmann** [comment]
You're missing an `Armament` trait on your actor, as the error message tells you:

```
ActorInfo("mobu") failed to initialize because of the following:
Missing:
OpenRA.Mods.Common.Traits.ArmamentInfo
```
