### ISSUE TITLE
Crate drops shouldn't prevent units from moving onto the tile before the crate lands.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#11766]
A slight annoyance but I never really thought about it much before I watched the first seconds of this video: https://www.youtube.com/watch?v=xKHzfOg7gLw

I hope there's a way to make it so that you can stand directly below the drop and get the crate once it lands.

**Comment by StexoO** [comment]
In fact it's a "regression", I used to do this in the previous release (< 20160508).
IIRC a building built under the drop got the crate too.

**Comment by r34ch** [comment]
Yes is indeed annoying #9555

**Comment by Micr0Bit** [comment]
:+1:

**Comment by obrakmann** [comment]
Closing as duplicate
