### ISSUE TITLE
Replace warhead Verses percentages with absolute damage values

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#11764]
Instead of defining one Damage value and then setting percentage Verses values for each armor type, it might be a more sensible approach to set explicit base damage values versus each armor type and only use the main Damage field as fallback for armor types that don't have a custom damage defined.

This would reduce the number of percentage modifiers applied to damage by one, and make balancing a bit more easy and straightforward.

**Comment by pchote** [comment]
How would actors with multiple armor classes work?  Right now we just multiply the modifiers together.

**Comment by GraionDilach** [comment]
:-1: for explicitly the reason above. Sorry.

**Comment by reaperrr** [comment]
Ok, just wanted to throw the idea out there, but currently I don't have a solution for armor handling either.
