### ISSUE TITLE
"Select units by type", across screen

### ISSUE THREAD

**Issue by FrenzyTime** [OpenRA/OpenRA#11761]
If I understood how the "Select all combat units" hotkey works : when nothing is selected, the range is the screen. If a unit is already selected, the range is the map.
 
But for "Select units by type", it's always across the map. 

Could sth like that be implemented also for the "Select units by type" hotkey ? So we can select across screen only. For instance : first usage's range is the screen, second is the map. 

Selecting across the map just messes up everything if you have multiple armies on different fronts.

**Comment by Phrohdoh** [comment]
> first usage's range is the screen, second is the map. 

This is what is done currently (the left-most soldier was outside of my viewport).
Tested on a73163c476c18412f997fe60f26af73de5887f7a.

![screen shot 2016-08-03 at 7 18 46 am](https://cloud.githubusercontent.com/assets/4861023/17365229/90605e0c-594a-11e6-812e-095dc204d484.png)

**Comment by obrakmann** [comment]
Yep, that's exactly the way it works.
