### ISSUE TITLE
Enemies try to hunt down walls in Survival01

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#11760]
![image](https://cloud.githubusercontent.com/assets/756669/17354490/454cbcd6-5949-11e6-8194-060ef64acf0e.png)

This means the mission won't properly end when the player should loose.

**Comment by obrakmann** [comment]
This is a weird screenshot.

1. Why isn't the AI targeting the walls then?
2. Why wouldn't the mission end? Walls don't have the `MustBeDestroyed` trait, afaik.

Anyway, changing the walls' owner to Neutral should fix that.

**Comment by Mailaender** [comment]
1. `AutotargetIgnore` maybe? Actually I am not sure.
2. There are still two buildings left, but the AI is too busy surrounding the walls.

**Comment by WolfGaming** [comment]
This is probably a bug in the Hunt lua command, does it hunt all enemy actors? If so this can be fixed by filtering by MustBeDestroyed and maybe adding an optional parameter to switch that filtering on/off if it breaks something.
