### ISSUE TITLE
Clamp minimum damage to 1 unless versus value is 0 vs armor type

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#11765]
Issues like #11425 or #4778 could have been avoided that way.

**Comment by pchote** [comment]
My preference would be to go for something like #11719 instead.

**Comment by MustaphaTR** [comment]
Agreed with @pchote .

**Comment by reaperrr** [comment]
Well, this was a bit of a brain-storming idea. #11719 is probably the better approach (less risky regarding potential regressions in any case).
