### ISSUE TITLE
Question: what infiltration types are there?

### ISSUE THREAD

**Issue by Aquilar** [OpenRA/OpenRA#11762]
as title.

I've been trying to get the thief to work again but it wont infiltrate for cash unless I make it infiltrate for everything.

**Comment by Aquilar** [comment]
Nevermind figured out what to do, it wasn't obvious that i needed to add TheifInfiltrate to both infiltrationtypes: and targetabletypes.

**Comment by pchote** [comment]
Please don't use the bug tracker for modding questions. The forum or IRC channel are much better places.
