### ISSUE TITLE
TD Supply Aircraft not being removed from world

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#11784]
Current bleed (90ab5023a69081d60cd9cd3514dca79d827dad4b): the planes are sitting just outside the map circling.

![screen shot 2016-08-07 at 14 54 03](https://cloud.githubusercontent.com/assets/167819/17462744/e94f268a-5cae-11e6-9807-3d8c069f4aca.png)

**Comment by pchote** [comment]
Not sure if related, but the airstrip's rally point is placed on a non-pathable location (the area above the cliff).

**Comment by GraionDilach** [comment]
Isn't this http://logs.openra.net/?year=2015&month=11&day=09#19:06:09 again?

**Comment by obrakmann** [comment]
It seems this only happens when the airfield is closer than eight cells to the map's border.

**Comment by WolfGaming** [comment]
Might be because the code isn't allowing the plane to despawn since it hasn't gone a certain distance from the airfield because its stopping on the end of the map.

**Comment by obrakmann** [comment]
@WolfGaming: no, aircraft don't care about the map's boundaries, not even the cordon. The bug here is that [this condition](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Activities/Air/Fly.cs#L71) is never met. The question is why.

**Comment by GraionDilach** [comment]
Seems like an issue with Speed mostly - the aircraft can never get that close to the target position because it always overshoots the constant due to being too fast.

This is an issue with CloseEnough as well, btw.

**Comment by WolfGaming** [comment]
Then can we change it so if we are within half the speed of the aircraft we despawn it?

**Comment by reaperrr** [comment]
The TD transport plane has a speed of 326, so there's indeed a chance of overshooting (`91022` roughly equals 302*302 WDist).
Increasing that value to `1048576` (= `1024*1024`) might be a good enough fix, as 1 cell from the target cell sounds like an acceptable margin (and if anyone gave an aircraft a speed higher than 1 cell/tick, I'd consider that an unreasonable decision on the modders' end).
I haven't tested this, so I might be wrong.

**Comment by pchote** [comment]
I think a better fix would be to change the check from "am I within some arbitrary constant distance" to "am I close enough that I would reach the target in the next movement tick"
