### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ryanehlol** [OpenRA/OpenRA#11792]
I think it might be the shellmap, idk. 

Red Alert Mod at Version release-20160508
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.InvalidDataException`: No valid shellmaps available
   at OpenRA.Game.ChooseShellmap()
   at OpenRA.Game.LoadShellMap()
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by obrakmann** [comment]
Yes, the game doesn't find your shellmap. Have you tried to edit it perhaps?

Re-installing the game will fix this.

**Comment by ryanehlol** [comment]
I've re-installed the game several times, and just tried re-installing it again, however the problem has persisted. The game won't progress past a black screen before it crashes, so I don't know how to perform edits unless I can do so in the game files.

**Comment by obrakmann** [comment]
OK. In the path where you installed OpenRA, check for a file named `map.yaml` in the `mods/ra/maps/desert-shellmap` directory. Somewhere among the first few lines are two entries called `Visibility` and `Categories`. Check that both say "Shellmap` after the colon.

**Comment by ryanehlol** [comment]
They both had 'Shellmap' after them when I checked, though I don't know if it matters that there is no space between them and the next entries. 

Bounds: 1,1,126,126

Visibility: Shellmap

Categories: Shellmap

Players:

**Comment by obrakmann** [comment]
Alright, that is very strange. Can you start other mods? (To reset the game, edit the `settings.yaml` file in `%USERPROFILE%\My Documents\OpenRA\` and remove the line that says `Mod: ra`. Then start the game and select either TD or D2k.

**Comment by ryanehlol** [comment]
I get the option of two settings.yaml files, one C:/Program Files (x86)/OpenRA/mods/cnc/chrome and the other C:/Program Files (x86)/OpenRA/mods/ra/chrome, but I can't find 'Mod: ra' in either. I am searching 
in ThisPc/Windows8_OS(C:)/ProgramFiles(x86)/OpenRA.

**Comment by StexoO** [comment]
@ryanehlol 

`C:\Users\[User]\Documents\OpenRA\settings.yaml` ?

You should see
```
Game:
	Mod: ra
```

**Comment by ryanehlol** [comment]
I found the file, and I'm able to play TD and D2K.

**Comment by obrakmann** [comment]
OK, so there's just something wrong with your ra install, not the game in general. I still can't imagine what, though, since the game should at least find the proper shellmap after you reinstalled it. Can you show your debug.log file (right after trying to start the ra mod), please?

Also, can you please state in which ways, if any, your install is customized? Are there any third-party maps or mods installed, for example? Did you modify any of the files in `c:\program files (x86)\OpenRA`? Do you have more than one installation of the game?

**Comment by ryanehlol** [comment]
Found 14 domains for movement class 215 on map shellmap.
Found 2 domains for movement class 1024 on map shellmap.
Found 48 domains for movement class 1247 on map shellmap.
--Tick: 1 (net)
--Tick: 2 (local)
--Tick: 3 (local)
--Tick: 4 (net)
--Tick: 5 (local)
--Tick: 6 (local)
--Tick: 7 (net)
--Tick: 8 (local)
--Tick: 9 (local)
--Tick: 10 (net)
--Tick: 11 (local)
--Tick: 12 (local)
--Tick: 13 (net)
--Tick: 14 (local)
--Tick: 15 (local)
--Tick: 16 (net)
--Tick: 17 (local)
--Tick: 18 (local)
--Tick: 19 (net)
--Tick: 20 (local)
--Tick: 21 (local)
--Tick: 22 (net)
--Tick: 23 (local)
--Tick: 24 (local)
--Tick: 25 (net)
--Tick: 26 (local)
--Tick: 27 (local) 

Failed to load map: temp.oramap
Details: System.IO.InvalidDataException: Map format 7 is not supported.
   at OpenRA.MapPreview.UpdateFromMap(IReadOnlyPackage p, IReadOnlyPackage parent, MapClassification classification, String[] mapCompatibility, MapGridType gridType)
   at OpenRA.MapCache.LoadMaps()
Failed to load map: desert-shellmap
Details: System.IO.InvalidDataException: Map format 7 is not supported.
   at OpenRA.MapPreview.UpdateFromMap(IReadOnlyPackage p, IReadOnlyPackage parent, MapClassification classification, String[] mapCompatibility, MapGridType gridType)
   at OpenRA.MapCache.LoadMaps()


I have a lot of third party maps installed, and some of those have custom features. I haven't personally altered any files in C:\program files (x86)\OpenRA, so I think that they are as they should be. I'm not certain if I have multiple installations of the game.

**Comment by WolfGaming** [comment]
It seems to find the map but doesn't like its formatting...
I don't get why though.

**Comment by Phrohdoh** [comment]
`Map format 7 is not supported.`
AFAIK we are on format 11 now as of `release-20160508`.

**Comment by obrakmann** [comment]
First of all, please verify that the `map.yaml` file of the shell map in `c:\program files (x86)\openra\mods\ra\maps\desert-shellmap` has the line `MapFormat: 11` somewhere at the top.

If it does, please try and rename the `C:\Users\[User]\Documents\OpenRA\maps\ra` directory. I suppose you have an old copy of the shellmap around there. I don't know why the game doesn't pick up the other copy in the install dir, though.

If if doesn't, please completely uninstall the game, make sure the directory `c:\program files (x86)\openra` is gone, then download the installer again from http://openra.net/download and reinstall.

**Comment by ryanehlol** [comment]
Rename it to what?

**Comment by ryanehlol** [comment]
It does have mapformat 11

**Comment by yaaaaa** [comment]
try to delete temp.oramap file or convert it into map format 11

**Comment by ryanehlol** [comment]
The problem is **fixed**, I think my uninstaller wasn't deleting all the Openra files and I had the game installed in two places (sorta, there were files in C:\Program Files(x86)\ and in C:\Users\[User]\Documents) so I just deleted all of the files manually and re-installed, which worked. Thank you to everyone who commented, you all helped, even if I was a bit frustrating at some points ;p

**Comment by WolfGaming** [comment]
C:\Users[User]\Documents is not an OpenRA installation but user specific files, you probably had a bad shellmap there :)
