### ISSUE TITLE
AI gets bored and stops spending money

### ISSUE THREAD

**Issue by djlists** [OpenRA/OpenRA#11797]
I have found that in most games the AI will eventually just stop spending money. I started an Infantry Only tech level skirmish to test a few things. The computer worked for a while and eventually stopped. There's 2 barracks, 4 ore refineries, lots of silos, and 12 infantry (two of them just outside the screencap area. 

![infantry](https://cloud.githubusercontent.com/assets/20367532/17557623/e85c4756-5ee5-11e6-9c51-844417a73b5c.png)

This is a pitiful force which could be easily overcome with some infantry. The computer never explores, attacks, or continues building.

**Comment by GraionDilach** [comment]
The summary of the infantry army percentages in all `HackyAI->UnitToBuild`s in the RA mod are <100% and the bug happens when the AI manages to fulfill all of the listed percentages.

**Comment by pchote** [comment]
@GraionDilach nice catch.  That's a really silly mistake to make - lets fix it and double check the other mods for the next release.
