### ISSUE TITLE
[SOLVED] System.InvalidTimeZoneException: TZ file too big for the buffer

### ISSUE THREAD

**Issue by The-Loud** [OpenRA/OpenRA#11805]
Game loads fine but clicking on anything results in a crash this includes clicking on 'Quit.'

Google searched and searched this repository and FAQ, but nothing around this issue.

![image](https://cloud.githubusercontent.com/assets/20816697/17589596/436604c4-5f9b-11e6-8c21-1eb7c6608cab.png)

Machine is an Arch Linux running within a VM.

![image](https://cloud.githubusercontent.com/assets/20816697/17589624/7232a2c6-5f9b-11e6-87bf-daa6fc0fb7a7.png)

**Comment by GraionDilach** [comment]
Could you please test it after https://bbs.archlinux.org/viewtopic.php?pid=1613953#p1613953?

**Comment by The-Loud** [comment]
Thank you for the reply.  This fixed the issue.  Please marked as resolved.
