### ISSUE TITLE
OpenaRA startup error

### ISSUE THREAD

**Issue by RyderFive** [OpenRA/OpenRA#11818]
I have a friend here that also made a post named daskew87 we appear to have the same problem but im not sure.

As soon as i open the program OpenRa a message pops up saying.

OpenRa has encountered a fatal error and must close.Refer to the crash logs and FAQ for more information.

here is some information i seen that people asked daskew87 for

Sound:
	Shuffle: True
	Repeat: True
	Engine: Null
Graphics:
	CapFramerate: False

Exception from OpenRa

Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.IO.FileNotFoundException`: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at OpenRA.Sound..ctor(String engineName)
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

**Comment by pchote** [comment]
Remove the `Engine: Null` line and it will work.  This issue has been fixed for the next release.

**Comment by RyderFive** [comment]
thanks alot im sorry im not that great with computers yet.
