### ISSUE TITLE
Airstrike Power broken on targets with elevation.

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#11820]
On the first case I aim at powerplants on elevated ground, on the second I aim at targets at the lowest elevation possible, the map was A river runs near. Weapon code http://pastebin.com/i5rCHk1D .
![meteor1](https://cloud.githubusercontent.com/assets/11763228/17671107/38bab4ca-62e3-11e6-9dc4-b3cb2bcf7b5c.gif)
![meteor2](https://cloud.githubusercontent.com/assets/11763228/17671108/38bc6040-62e3-11e6-8769-5a80794e8ee8.gif)

**Comment by reaperrr** [comment]
This looks like either the airstrike support power or `SpawnActorWarhead` is not height-level-aware.

**Comment by Mailaender** [comment]
Can you verify that https://github.com/OpenRA/OpenRA/issues/11916 fixes it for you?
