### ISSUE TITLE
Update .NET

### ISSUE THREAD

**Issue by ROCKNROLLKID** [OpenRA/OpenRA#11822]
While it doesn't have to be in the next release or anything, but maybe update .NET to 4.5.2? This version can still run on Vista and up as well as Visual Studio 2013, so no system requirements are changed.

Alternatively, you can update to 4.6, which will still run on Vista, however, I do not know if it can run with Visual Studio 2013

Sorry if this was already discussed, but I didn't see this being talked about anywhere.

**Comment by pchote** [comment]
We looked into this in the past, and it breaks compatibility with older (and maybe even newer) versions of monodevelop that don't know about the 4.5.2 profile.  I'm not aware of anything useful that 4.5.2 brings over 4.5.0, so there's really no drive to do this in the short term.

**Comment by ROCKNROLLKID** [comment]
4.5.2 had some fixes for high DPI monitors. Not sure what 4.5.1 offered.

Anyways, you are right, it looks like monodevelope only runs 4.5.0. My mistake.

**Comment by Mailaender** [comment]
https://msdn.microsoft.com/en-us/library/ms171868(v=vs.110).aspx#v452 We don't use any Windows only GUIs but our own, so the those high DPI fixes for WPF don't affect us.
