### ISSUE TITLE
Spies keep their disguise from a dead player

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#11831]
spies should lose their disguise when disguise-associated player surrenders or dies ... but probably keep the disguise when disguise-associated player only disconnects

**Comment by Micr0Bit** [comment]
no idea what here the "idea" is ... but i think spies that keep their disguise-color from a dead player (which isnt on the battlefield) should be "polished" ...

**Comment by Comanche93** [comment]
Personally i dont think this should be "polished" and find it interesting "feature", if you want.
Player should change disguise by himself, that makes more sense to me. He should be watchful about it and his enemy should watch for that obsolete disguise too. IMHO

**Comment by pchote** [comment]
IMO having a spy keep its disguise, with the unit AI continuing to ignore it, is much better for gameplay than having the spy automatically drop his disguise and suddenly become vulnerable to enemy auto-targeting.

**Comment by Micr0Bit** [comment]
@pchote : tbh ... it would be fair that they would drop their disguise ...

what i found interesting is , that a lot of devs dont realize what a pain it is to spot an spy , especially during the heat of battles and distractions (which is so easy to get into )... and its so punishing ... to have one enter your powerplant or refinery ... 
and the difficulty to spot them increases with the size of the map and expansions that you have to do

so im not gonna eat your "better gameplay"-argument here ...

**Comment by abcdefg30** [comment]
> IMO having a spy keep its disguise, with the unit AI continuing to ignore it, is much better for gameplay than having the spy automatically drop his disguise and suddenly become vulnerable to enemy auto-targeting.

I agree.
