### ISSUE TITLE
feature request: resourcemultipler trait

### ISSUE THREAD

**Issue by Aquilar** [OpenRA/OpenRA#11833]
As the title, just asking that this be added in, as certain buildings in RA2, namely the ore purifier, use it.
This would give modders more ways to play with the resource system without having to add coding.

**Comment by GraionDilach** [comment]
The relateds are unrelated. Only one feature request per ticket, please.

**Comment by GraionDilach** [comment]
Regarding the Ore Purifier, it's quite simple to do it upstream though.

**Comment by Aquilar** [comment]
it's still nice to have you want to do some more interesting things such as increase your global income for a few minutes, or reduce global income for a few minutes via crate drop.

**Comment by GraionDilach** [comment]
Implemented with #15798.
