### ISSUE TITLE
Refactor warhead ImpactTypes

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#11848]
We currently have too many of them, some make hardcoded assumptions, some use the soon-to-be-deprecated `IsWater` check, and most ignore `TargetTypes` completely.

**Comment by 7heSAMA** [comment]
I would like to be assigned to this along with #12582 and #12574 as a combined fix.

**Comment by abcdefg30** [comment]
Seems like I can only assign team members... Your comment should be enough however. Happy coding! ^^

**Comment by 7heSAMA** [comment]
I wanna be on the team! Hah
