### ISSUE TITLE
Multiple spy infiltration bonus

### ISSUE THREAD

**Issue by PUOjACKz** [OpenRA/OpenRA#11846]
I was thinking that, while playing RA with Alliance, the player often send a spy inside a building, or to shutdown the power grid, getting veteran units etc. (even if I still don't have understand what happend, when you send a spy inside a radar dome). If you try to send someone on the deployed MCV, you can't access it. After the player have sent a spy inside the enemy building, he doesn't need to use the unit more again (at least, for OpenRA, where you can use it for tactical kills). My idea was instead to keep the interest on player, on infiltrating enemy bases, adding a scalar system. For example, if you send a spy on enemy barracks, the first time, you get veteran units. If you send him again, you get the possibility to build one new enemy unit, that usually could be obtained only constructing the enemy barrack, after taken over the enemy MCV.

In short, spy infiltration (I throw just some ideas about how it could be):

Enemy barracks: (1) Get veteran units, (2) Get Granade launcher soldier, (3) Get Flamethrower soldier, (4) Get Hijacker, (5) Get Shock Trooper, (6) Get Attack Dog ....
Enemy warfactory: (1) Get veteran units, (2) Get APC unit (for example), (3) Get V2 Rockets... or even (4) Get Chrono Tank, (5) Get Demotruck ...
Enemy MCV: (1) Get Flame Tower, (2) Get Airplane strip, (3) Get Subpen, (4) Get French fake structures ...
Enemy Research Center: (1, Among with Radar Dome infiltrated) Get Spy plane, (2, Among with Radar Dome infiltrated) Get  Paratrooper, (3, Among with Radar Dome infiltrated), Get Parabombs, Get Counterstrike B-52 Air-Fuel bomber
Enemy Airstrip: (1) Get vetera units, (2) (After you infiltrated a research center and obtained an enemy airstrip for infiltration) Counterstrike Nuclear Mig

So you can even, using this kind of concept, introduce the hidden/secret counterstrike/aftermath units, like nuclear mig, fuel-air bomber, volkov, chitzkoi, even "strange" units from Paradox equation mission or various tipes of Giant Ants.

**Comment by PUOjACKz** [comment]
For example, with Radar dome infiltration, you can do something like: (1) I don't know what it does now, (2) Enemy Units command (like the effect obtained on RA YR when creating a psichic radar, that you can see enemy where are moving/attacking, (3) Gas beacons or Player radar alert when the enemy place a bombing order, (4) You can permanently see the area around an enemy unit or to all the units created by a particular structure (es. an airstrip), with the same concept used for the Firestorm limpet drone.

If you infiltrate an enemy allied research center, you can see all their units moving (not just place-holder icons), if you infiltrate enemy superweapons you can booby trap them (if a chronosphere, when the enemy use it, it explodes instantly, if an enemy nuclear silo, it explode causing a nuclear detonation etc.)...

This keeps the player to continue on infiltration and the enemy to use dogs and check for potential base penetration points, more actively.

**Comment by Micr0Bit** [comment]
thats a bit overkill ... our current spy is already pretty useful imo ... although theres lots of ways to improve him further and further ... it will bet hard to justify all the buffs/improvements on a units that is available for "all" allied factions ...

**Comment by PUOjACKz** [comment]
They can always be eventually limited to a specific number. The problem could be for the soviet faction, for they don't have a valid spy.

**Comment by obrakmann** [comment]
I agree that the spy already has enough capabilities. I'm also sick and tired of adding special cases and exceptions throughout the code just for the spy.

**Comment by PUOjACKz** [comment]
Ok. Let's close this.
