### ISSUE TITLE
Update battlefield-news with ragl season 2 - registration

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#11844]
@SoScared : just a reminder ... that we still have no battlefield-news for ragl2 ... and the registration will close in 11 days...

registration :
http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=19734

rulebook :
http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=19750

**Comment by jaZzKCS** [comment]
Bump.
Hype.
Everything.
#AllForTheCommunity

**Comment by obrakmann** [comment]
https://github.com/OpenRA/OpenRAWeb/pull/309

(also wrong repo)
