### ISSUE TITLE
feature request: productionspeedmultipler trait

### ISSUE THREAD

**Issue by Aquilar** [OpenRA/OpenRA#11851]
This is another one that's related to RA2, a soviet building the industrial plant, uses this but it can be applied for other uses too.

**Comment by obrakmann** [comment]
A little more info than just dropping a name would be nice. What should it do exactly?

#11311 is re-writing the way the build speed calculation works. Please have a look whether those changes already fulfill your requirements.

**Comment by GraionDilach** [comment]
The request is about an external/upgradable queuebuildspeedmultiplier.

However, the YR (not RA2) Industrial Plant changed unit costs in a queue primary (with buildtimes only changing because they were derived from the costs alone).

**Comment by Aquilar** [comment]
@obrakmann  not what I'm after, as by the title, it would be in the same vain as the other multipliers, except it wont double the amount of scripting because I added upgrades the production structures specifically for this, then to duplicate the classicproductionqueue traits to essential get the same effect. with this, one wouldn't need to do that.

**Comment by MustaphaTR** [comment]
Making Valued and CustomBuildTimeValue upgradeable should do the trick here.

**Comment by pchote** [comment]
a `ProductionSpeedMultipler` trait would be simpler and more general.

**Comment by MustaphaTR** [comment]
https://github.com/OpenRA/OpenRA/pull/15305 closes this.
