### ISSUE TITLE
(Bleed) RA/TD Minigunners damage vs Heavy Armor fix threatens balance.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#11850]
#11460 doubles minigunners' damage vs heavy armor in order to retain damage output against veteran heavy armor. In effect, heavy armor melts in the prescense of infantry blobs making tanks less relevant as infantry support and the whole range of heavy armor units is effectively nerfed. 

The issue came out of riflemen/minigunners doing 0 damage vs veteran heavy armor. #11425

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/issues/11719 is probably the solution.
