### ISSUE TITLE
Restart button for replay

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#11860]
Ideally, would be perfect to be able to play in reverse (rewind a certain portion) the replay ^^

But maybe for a first step : having a "restart" button for replays ?

**Comment by obrakmann** [comment]
Rewinding replays is a very difficult problem. It may be become possible to jump back to a number of checkpoints once savegame support is added (which in itself is a just as difficult problem to solve), but don't hold your breath.

A restart button exists, even in the current stable release.
