### ISSUE TITLE
Explain the Inherits: syntax for Traits

### ISSUE THREAD

**Issue by Quetip** [OpenRA/OpenRA#11877]
It's not there

**Comment by PunkPun** [comment]
ping @penev92

**Comment by penev92** [comment]
I am not sure what warrants documenting/explaining here or how/where we could do it, but [the OpenRA extension for VSCode](https://marketplace.visualstudio.com/items?itemName=openra.oraide-vscode) already adds a hover tooltip for it.
I don't see a more general solution.
