### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by 10769241** [OpenRA/OpenRA#11874]
so i got it up and running and it was working for a bit then i changed the volume and now it wont run. i checked the logs and its [Exception of type System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)] anyone have a quick fix for this?

**Comment by obrakmann** [comment]
Delete the line that says `Engine: null` from the `settings.yaml` file which is located in `C:\Users\USER\Documents\OpenRA`. This will be fixed in the next release.

**Comment by 10769241** [comment]
that total worked! thanks man, i owe you a pint
