### ISSUE TITLE
WithInfantryBody only supports a single firing animation.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#11892]
This is a problem with artwork like http://ppmforums.com/viewtopic.php?t=42518 which has more firing animations for different weapons.

**Comment by pchote** [comment]
It would take only a couple of lines of code to replace the `AttackSequence` string with a dictionary keyed on armament name.

**Comment by GraionDilach** [comment]
Prolly do it after playtest then.

**Comment by reaperrr** [comment]
I wonder whether we should do the same for `WithAttackAnimation`. Though once WAA is upgradable, it might be enough to simply 'link' it to armament names.
