### ISSUE TITLE
Attack-move inconsistency 

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#11896]
steps to reproduce , to understand what im referring to : 
- select a bunch of units
- press "one time" "A" (assuming thats your attack-move hotkey)
- [the cursor should be red now] 
- right click "one time" on a free spot (your units will start attack-moving)
 
what does the cursor look like now ? 

  
  now do this : 
- select a bunch of units
- press "A" and keep holding "A" (assuming thats your attack-move hotkey)
- [cursor should be red now]
- while still holding "A" ... make a right click on a free spot (your units will start attack-moving)
- release "A" ... 

what does the cursor look like now ? 

so basicly , when i keep holding A ... instead of only pressing it one time ... i will stuck in "attack-move-mode" ... and i have to do a "inbetween-left-click" to free myself from it 

and this "inbetween-left-click" can get quite annoying while in combat

**Comment by pchote** [comment]
This was fixed in the original release of the command bar, but that was then treated as a regression (#13804) and the behaviour reported here was reintroduced (#13807).  Closing as being now a deliberate feature.
