### ISSUE TITLE
Selecting a map with zero player spots resets player color in settings.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#11898]

**Comment by obrakmann** [comment]
What do you mean with player spots? Spawn points or player references?

**Comment by GraionDilach** [comment]
Well, the particular map only has `Neutrals` and `Creeps`.

**Comment by Micr0Bit** [comment]
theres other things that can reset your color while in the lobby ... just didnt figure out what causes this

**Comment by Micr0Bit** [comment]
when you switch you color inside the lobby ... and then change the slot ... it will reset

**Comment by rob-v** [comment]
@pchote, @GraionDilach Can you please review this 'fix'? It isn't clear to me, so I didn't create PR.
https://github.com/rob-v/OpenRA/commit/0a72dbc9ef757b923a63864bc173a290077f74bf
