### ISSUE TITLE
Update OpenGL

### ISSUE THREAD

**Issue by ROCKNROLLKID** [OpenRA/OpenRA#11919]
Don't know if this has been discussed, but any plans to update OpenGL to something like 3.3 or even 4.5 (preferably). Alternatively, you can try Vulkan, too, but it's still pretty new and would probably be better to wait a few years before implanting to OpenRA, especially since it would raise system requirements to Windows 7 x64 minimal and requires new(er) generation cards to run.

**Comment by chrisforbes** [comment]
If this happens, it will be driven by an actual need in the renderer. We don't want to just write off piles of old hardware because a newer spec exists.

**Comment by ROCKNROLLKID** [comment]
Well yes, I know, but not really what I was meaning by this.

I mean it's not like something like this would have to be done in the next release or anything, but at least it will give OpenRA some graphical/performance enhancements.

**Comment by reaperrr** [comment]
Graphics performance normally isn't a problem with OpenRA, unless the hardware is just way too weak and/or old or the drivers are buggy.

At least on Win7x64, even a tray i5-2500 'HD' IGP with only 4 EUs is currently enough to play OpenRA fluently (on the rendering side).
But to my knowledge, Sandy Bridge IGP's driver support for OGL3.x is incomplete at best.

My point is, most (i)GPUs that could use a performance uplift probably don't support these newer APIs, a lot of (i)GPUs that *don't need* a performance uplift don't support these newer APIs, and most GFX hardware that *does* support these newer APIs doesn't have noteworthy performance issues with OpenRA to begin with (and if any of them do, there's no guarantee a newer API version would help).

**Comment by ROCKNROLLKID** [comment]
I know the game itself doesn't have any performance degrade on it, but extra performance is always a good thing.

I guess what I am trying to say is I would like to see stuff that new(er) OpenGL versions offered that aren't in the game already, like for example, enhancements to shaders, tessellations (don't know if it would be noticeable in OpenRA, but still nice to know you have the option and all), improved rendering features, better textures.

As far as hardware is concerned, I mean OpenGL runs as far back as HD 5000 series (7000 series for 4.5) for AMD and Nvidia GeForce 400 series and those are 1gb cards (these are OpenGL 4.5 specs). I mean, to run Windows just find (well at least since Windows 7 to Windows 10), you basically need a 1gb card and all.

**Comment by Mailaender** [comment]
As told by @chrisforbes that only increases the requirements. "Updating OpenGL" in OpenRA does not have the same effect of you buying new hardware or updating your drivers.

**Comment by GraionDilach** [comment]
>At least on Win7x64, even a tray i5-2500 'HD' IGP with only 4 EUs is currently enough to play OpenRA fluently (on the rendering side).
But to my knowledge, Sandy Bridge IGP's driver support for OGL3.x is incomplete at best.

On Windows, yes, it's bugged. On Linux, the driver only gives you 3.0 but at least that works flawlessly.

@ROCKNROLLKID I have a backup PC with an Intel GMA 950 GPU which could run Win10 x86 good enough for my mother - on the Microsoft GDI software renderer. I've also used a Radeon HD 3000 integrated for a good while with OpenRA (which I used from '11-12 onwards, first with Win7, then Kubuntu 12.04 and ultimately with Win10). I have no idea where you got the idea that 1 GB cards are required for Win7, also pretty sure the playerbase would heavily disagree you there.

Yes, OpenRA uses textures. Generated from spritesheets, so pretty much all the feats you listed are useless in this case. Bumping the minimum requirements __is__ a problem - even dropping XP was for some. This is not the game AAA gamers play or pick up even, so don't apply gamer PCs as primary target.

**Comment by ROCKNROLLKID** [comment]
"I have no idea where you got the idea that 1 GB cards are required for Win7, also pretty sure the playerbase would heavily disagree you there."

That's not what I meant by when I said that. Yes, it is not required, but what I meant was, in order to run Windows 7 - 10 without any slow downs or issues, you need to have at least a 1 gb card, atleast for the x64. I understand x86 is a little more lightweight so maybe users there can get away with only 512mb card.

Anyways mailaender and chrisorbes made it clear they have no plans for right now, but maybe someday it will happen.

**Comment by GraionDilach** [comment]
>in order to run Windows 7 - 10 without any slow downs or issues, you need to have at least a 1 gb card, atleast for the x64

Intel HD 2000 works fine on Windows 10 x64, as long as you don't rely on the driver's buggy OpenGL implementation. 64 MB VRAM. I've also ran my Radeon HD 3000 in 128 MB VRAM mode. Again, you're thinking in gamer PCs. Or you simply have no idea what you're talking about and believe that bigger number must be better as well.
