### ISSUE TITLE
Stats for unit production

### ISSUE THREAD

**Issue by ChristianDK** [OpenRA/OpenRA#11914]
I’d like to see stats added for unit production. So it’s possible to see how many rifle soldiers, medium tanks, yaks etc. have been produced during the game for all players.

**Comment by pchote** [comment]
This is probably best done by a community made tool that parses replay files.  Implementing it in our ingame UI would add a lot of complexity that I don't think is justified.

**Comment by Smittytron** [comment]
After discussion in the github-cleanup Discord channel, I'm closing this as wont-fix for out of scope / lack of interest.
