### ISSUE TITLE
AI can place Rally points to unavailable places

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#11938]
I was testing about adding MGG and MRJ to AI. Noticed that this happens.
![ai rally point](https://cloud.githubusercontent.com/assets/7933210/18166740/2a30dbb0-704d-11e6-88ff-6619e95170c8.png)

**Comment by pchote** [comment]
This can be easily fixed with a DomainIndex check.

**Comment by chrisforbes** [comment]
Mine! I need a patch in this next release, right?
