### ISSUE TITLE
Add a small deadzone for standard scrolling 

### ISSUE THREAD

**Issue by Sininini** [OpenRA/OpenRA#11940]
https://github.com/OpenRA/OpenRA/pull/11879 seems to have exposed issue with lack of deadzone for standard scrolling when it's used on right mouse button. Ever so slight mouse movements while ordering units around count as standard scrolling making orders not go through.

**Comment by obrakmann** [comment]
It happens with joystick scrolling, too. I'll look into it.

**Comment by Sininini** [comment]
Yup, managed to replicate it with joystick scrolling as well
