### ISSUE TITLE
RA - Ant and Zombie can be built from Kennel

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#11942]
Not sure about ant but zombie shouldn't be able to.

**Comment by pchote** [comment]
Having these buildable at all is stupid, and serves no gameplay purpose.

**Comment by MustaphaTR** [comment]
Are you sure? Ants are pretty useful. Problem is almost(maybe really) none of the shipped maps have bio lab in them. Ants are highly used on my maps.

**Comment by pchote** [comment]
Mod maps are still free to do whatever they want. I'm talking about our standard gameplay, where they are not at all balanced or thematically suitable. That will almost certainly be why normal mappers dont use them.

**Comment by MustaphaTR** [comment]
I can't understand your logic, you was against gates in ra mod too. It is not about "mod" maps. Almost no-one is using Bio-Lab in their maps doesn't mean we should remove them.

**Comment by pchote** [comment]
I'm not saying that the biolab should be removed because nobody uses them.  I'm saying they should be removed because they are badly implemented and, in their current form, do not contribute positively to the gameplay.  The fact that nobody uses them is just a point in support of that conclusion.

**Comment by MustaphaTR** [comment]
>badly implemented

I something is badly implemented you should fix them, not remove.

**Comment by pchote** [comment]
You seem to be starting from the assumption that all ideas are inherently worth including, and should only be discarded as a last resort. That is not how you design (good) games.

**Comment by r34ch** [comment]
Was there not some general agreement to remove zombies at least?

**Comment by MustaphaTR** [comment]
Talking about the discussion at #11650? I can't call it an agreement.

**Comment by MustaphaTR** [comment]
> all ideas 

No, there can be ideas i would like to be against/don't include/remove/change. But this is defenetly not one of them.
