### ISSUE TITLE
Planes will not stay on their airfields

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#11953]
They immediately take off again.  This must be a relatively recent regression.

**Comment by obrakmann** [comment]
This is due to [this](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Activities/Air/ResupplyAircraft.cs#L39) not working as intended.

**Comment by pchote** [comment]
> The problem that needs to solved here in general is that a landed aircraft somehow needs to be informed of another aircraft requesting a reservation. The former then needs to yield its reservation.

I agree that this is the only viable fix for our giant mess of aircraft problems. I'm sick of shuffling hacks around that swap one undesirable edge case for another. 

If someone doesn't want to take that task on this weekend then I think reverting #11393 is our only option.  We have far too many other improvements and fixes on bleed to justify holding up a release over that.
