### ISSUE TITLE
nod07a: crash because script tries to kill camera

### ISSUE THREAD

**Issue by clemty** [OpenRA/OpenRA#11963]
when reaching the bridge on the left side of the map, the Nod base is discovered
this triggers a flare at the Nod base, and creates a camera which shows the base

when reaching the Nod base from the left (not from the south!), reinforcements are triggered
this triggers a timer which kills the flare and the camera after a delay (2 minutes)
when the timer runs out, the mission crashes since cameras can't be killed:

```
Fatal Lua Error: [string "BindingSupport.lua"]:30: Actor 'camera' does not define a property 'Kill'
```
to reproduce more easily: 
in line 217 in nod07a.lua (Trigger.AfterDelay(DateTime.Minutes(2), function()) change "Minutes(2)" to "Seconds(2)", then just send the light tank to the area to the left of the Nod base to trigger the reinforcements

**Comment by pchote** [comment]
This will be a regression from #11920.
