### ISSUE TITLE
campaign-disable-experience.yaml unused?

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#11971]
Unless i'm missing something obvious, this file doesn't appear to be included in any of the missions in any of our mods.

**Comment by abcdefg30** [comment]
From https://github.com/OpenRA/OpenRA/pull/11627#issuecomment-233756627:
> Moved the rules that disable player experience out into a separate file, so mappers can choose if they want it.

So I guess this is intentional?

**Comment by obrakmann** [comment]
It is currently unused, but I added it on purpose, with the intention of it being used by mappers who want to use the score for other things. Having the file already available means that not everyone has to come up with the magic incantations to keep `GivesExperience` and friends from contributing to `PlayerExperience` by themselves over and over again.

**Comment by pchote** [comment]
Fair enough, but can we please rename it if we're intentionally not using it for the campaign?
