### ISSUE TITLE
Corner edge scrolling by mouse.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#11999]
When scrolling the corners of the screen with the mouse it moves at .001 speed. But the other areas of the screen works fine.

UPDATE:

This happens randomly everytime the game starts. It sometimes moves faster and sometimes super slow. This was not in the release and happened since the start of the first playtest. Currently happening now as well.

However, if you turn double pixels off it scrolls just fine. If you put double pixel on (Zoomed in) it has the problem.

**Comment by AoAGeneral** [comment]
UPDATE:

It happens randomly. When a new game starts it ranges from a scroll rate of perfectly fine to barely a crawl range.

**Comment by AoAGeneral** [comment]
Still currently present in the new playtest.

**Comment by pchote** [comment]
I have not been able to reproduce this.  Can you please make a video showing the bug and give a list of any relevant settings (OS / window mode / input config / etc)?

**Comment by AoAGeneral** [comment]
Windows 7 professional
Fullscreen, fullscreen legacy, windowed mode. (Window doesnt matter. Happens to all of them.)

Stream video here: https://www.twitch.tv/shadowst78/v/94336183

Because when I record this using fraps it works just fine. If I use OBS it keeps the problem so I can show it.
It has all the input information at the end of the stream.

**Comment by pchote** [comment]
I'm still unable to reproduce this with zooming enabled and the frame limiter disabled.  This appears to be windows / driver weirdness rather than a regression, so removing from the milestone.

**Comment by gardolf** [comment]
Unable to reproduce this on Release 20180923
