### ISSUE TITLE
First Decade DVD not detected (On OSX at least)

### ISSUE THREAD

**Issue by JoshuaPettus** [OpenRA/OpenRA#12002]
I assume it works on Windows.  
I am using a bleed build I put together from src 20 min ago as of typing.

Maybe this would help:
The path to reach the DVD on OSX is:
"/Volumes/CNCTFD"

I wish I could try other CDs  but the only other copy of C+C I own is the Classic MacOS (7-9) version which I'm not surprised you do not support.

**Comment by pchote** [comment]
Is this a physical disk, or an image?

**Comment by JoshuaPettus** [comment]
physical but it shouldn't make a difference at that path

**Comment by pchote** [comment]
The reason I asked is that I encounted the same issue while developing the new installer setup, but assumed it was related to the disk image that I was using.  If this affects physical disks as well it means this is a mono bug.

**Comment by pchote** [comment]
The problem is that mono is returning `DriveType.Fixed` instead of `DriveType.CDRom` for the TFD disc.

We can hack a work around by checking `d.DriveType == DriveType.CDRom || (d.DriveType == DriveType.Fixed && d.DriveFormat == "udf")` instead.

**Comment by JoshuaPettus** [comment]
Ah,  thanks for looking into it!
