### ISSUE TITLE
Target lines need an overhaul

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#12019]
Most of the `SetTargetLine` calls are currently done from trait code, which means that when you're queuing commands, the last command overrides all the previous target lines and becomes the only one visible.

A solution would be to instead call `SetTargetLine` when an activity is about to run for the first time.

**Comment by pchote** [comment]
I've been pushing in #11998 to kill `SetTargetLine` completely, and get this info from the activities themselves.
