### ISSUE TITLE
Traits Documentation Page "Won't Render"

### ISSUE THREAD

**Issue by ThisBlunt** [OpenRA/OpenRA#12018]
This happens when trying to load traits page...

![screen shot 2016-09-12 at 12 21 00 pm](https://cloud.githubusercontent.com/assets/14940856/18443653/d73fc480-78e3-11e6-9560-b9fb685ed4c4.png)

My internet and web pages are loading fine so i doubt it's an issue with my CPU.

Edit: a word

**Comment by obrakmann** [comment]
Seems like something broke on Github's end:
![screenshot from 2016-09-12 18 51 22](https://cloud.githubusercontent.com/assets/4331210/18444654/737cd244-791a-11e6-9536-e501a792fc14.png)

In the meantime, you can use the local copy installed with the game. It should be `C:\Program Files (x86)\OpenRA\DOCUMENTATION.html` or something like that.

**Comment by obrakmann** [comment]
It's working fine again now thanks to Github's support team.
