### ISSUE TITLE
Openra (red alert) freezes completely with playtest 20160904 and 20160508

### ISSUE THREAD

**Issue by prutskip** [OpenRA/OpenRA#12016]
Dear dev's,

With the latest two playtests I have issues. With both it happend to me a few times already that after playing skirmish with a little brake in a game (pause) that I could continue playing for a while again, but after some time the game suddenly freezes and can only be shut down by using task manager.

This is not really nice after building up a nice game and being dropped out, but you'll understand that probably :-D

I have a machine with Windows 7 x64, 8gb ram, Core i7 2600, AMD Radeon 9650 (latest drivers) and Z77 mainboard.

Is there someway you can see if this issue is with my system or with the updated code?

Kind regards

**Comment by x-a-n-a-x** [comment]
Hello.

Can you check the **exception.log** file located in your  \Documents\OpenRA\Logs\ folder ?

Then just paste the content of this file here or use https://gist.github.com (in this case, don't forget to share the generated link here, once it's done).

**Comment by obrakmann** [comment]
The freeze in the playtest would probably be fixed by https://github.com/OpenRA/OpenRA/pull/11982/commits/daa1f16e987a26120436aa31a38f06223dc5fc9b. I've never heard of a freeze in the current stable release.

**Comment by prutskip** [comment]
Hi x-a-n-a-x, there is no exeption.log file in my log-folder. There is a debug.log and several others. How can I help?

**Comment by x-a-n-a-x** [comment]
Can you join us on our IRC channel (live chat)? It will be easier to discuss this way.
http://webchat.freenode.net/?channels=openra

**Comment by abcdefg30** [comment]
I suspect this is fixed on the latest version(s).
