### ISSUE TITLE
D2K - Missions lack of Harvester Reinforcements for Player

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#12028]
In original D2K's missions if you are out of harvester you get a new one with carryall. This is coded into original missions, but abcdefg30 looks like missed them on OpenRA. Reinforcement waypoints can be looked from original missions.

I can take a look to it when i back to home tomorrow or anyone else can do it now as it sounds easy to fix.

**Comment by pchote** [comment]
You will get a new harvester (only) if your last one is eaten by a worm.

**Comment by MustaphaTR** [comment]
I'm pretty sure you get a new harvester in any way that it killed. There is no check that it is killed by worm. But i'll check.

**Comment by MustaphaTR** [comment]
> You will get a new harvester (only) if your last one is eaten by a worm.

Is this hardcoded? I think it should be removed and scripted to work only in missions. This doesn't happen in original Skirmish and Multiplayer.
