### ISSUE TITLE
Music reset issue on playtest

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#12024]
The music will reset randomly in the game whether you are playing or spectating. It seems to be causing it when the airstrikes or other ion/nukes are being used which has those notifications missing as well.

**Comment by pchote** [comment]
Possibly related to #11781?

**Comment by AoAGeneral** [comment]
I think it is. If the change makes it so units don't constantly repeat themselves that can do it. Probably the reason why notifications aren't heard half the time with A10/Nuke much like RA.

I actually haven't checked D2K yet if that happens there too.
