### ISSUE TITLE
OpenRA won't start or crash

### ISSUE THREAD

**Issue by temporary99** [OpenRA/OpenRA#12025]
It's happens when dwm.exe (Windows service) is disabled. When I start it manually - all works fine. Crash when full-screen and won't start in pseudo-fullscren and windowed mode.

I have this situation with Intel GMA x3100 under Windows 7 Home Basic. And I want to disable dwm service with OS general performance reason (this service no need on Home Basic).

Unfortunately, I can't give my graphic.log because it's standalone computer without Net. But I am sure that you can repeat this bogus on any Windows installation (with dwm service of course).

**Comment by pchote** [comment]
https://en.wikipedia.org/wiki/Desktop_Window_Manager is the desktop compositor for windows.

I'm not surprised that OpenRA (and probably other OpenGL applications) doesn't work if you disable it.

**Comment by temporary99** [comment]
Thank you for fast answer. Seems you are right. Some OpenGL applications doesn't work too. However, in Direct3D all works fine. It should be better to keep WDM on (unfortunately). How it runs before WDM (e.g. on Windows XP? =)

Exception.log:
Red Alert Mod at Version release-20160508
on map 1b896bb92014607fc1d9c3c1feff5f2a22f902ea (Desert Shellmap by Scott_NZ).
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: OpenGL Error: See graphics.log for details.
   в OpenRA.Platforms.Default.OpenGL.CheckGLError()
   в OpenRA.Platforms.Default.Sdl2GraphicsDevice.DrawPrimitives(PrimitiveType pt, Int32 firstVertex, Int32 numVertices)
   в OpenRA.Renderer.DrawBatch[T](IVertexBuffer`1 vertices, Int32 firstVertex, Int32 numVertices, PrimitiveType type)
   в OpenRA.Graphics.SpriteRenderer.<DrawVertexBuffer>c__AnonStorey1.<>m__0()
   в OpenRA.Platforms.Default.Shader.Render(Action a)
   в OpenRA.Graphics.SpriteRenderer.DrawVertexBuffer(IVertexBuffer`1 buffer, Int32 start, Int32 length, PrimitiveType type, Sheet sheet, BlendMode blendMode)
   в OpenRA.Graphics.TerrainSpriteLayer.Draw(Viewport viewport)
   в OpenRA.Graphics.TerrainRenderer.Draw(WorldRenderer wr, Viewport viewport)
   в OpenRA.Graphics.WorldRenderer.Draw()
   в OpenRA.Game.RenderTick()
   в OpenRA.Game.Loop()
   в OpenRA.Game.Run()
   в OpenRA.Program.Run(String[] args)
   в OpenRA.Program.Main(String[] args)

Graphics.log:
GL Error: 1286
   в OpenRA.Platforms.Default.OpenGL.CheckGLError()
   в OpenRA.Platforms.Default.Sdl2GraphicsDevice.DrawPrimitives(PrimitiveType pt, Int32 firstVertex, Int32 numVertices)
   в OpenRA.Renderer.DrawBatch[T](IVertexBuffer`1 vertices, Int32 firstVertex, Int32 numVertices, PrimitiveType type)
   в OpenRA.Graphics.SpriteRenderer.<DrawVertexBuffer>c__AnonStorey1.<>m__0()
   в OpenRA.Platforms.Default.Shader.Render(Action a)
   в OpenRA.Graphics.SpriteRenderer.DrawVertexBuffer(IVertexBuffer`1 buffer, Int32 start, Int32 length, PrimitiveType type, Sheet sheet, BlendMode blendMode)
   в OpenRA.Graphics.TerrainSpriteLayer.Draw(Viewport viewport)
   в OpenRA.Graphics.TerrainRenderer.Draw(WorldRenderer wr, Viewport viewport)
   в OpenRA.Graphics.WorldRenderer.Draw()
   в OpenRA.Game.RenderTick()
   в OpenRA.Game.Loop()
   в OpenRA.Game.Run()
   в OpenRA.Program.Run(String[] args)
   в OpenRA.Program.Main(String[] args)


OpenGL Information:
Vendor: Intel
Renderer: Intel 965/963 Graphics Media Accelerator
GL Version: 2.0.0 - Build 8.14.10.1930
Shader Version: 1.10  - Intel Build 8.14.10.1930
Available extensions:
GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_blend_color GL_EXT_abgr GL_EXT_texture3D GL_EXT_clip_volume_hint GL_EXT_compiled_vertex_array GL_SGIS_texture_edge_clamp GL_SGIS_generate_mipmap GL_EXT_draw_range_elements GL_SGIS_texture_lod GL_EXT_rescale_normal GL_EXT_packed_pixels GL_EXT_separate_specular_color GL_ARB_multitexture GL_EXT_texture_env_combine GL_EXT_bgra GL_EXT_blend_func_separate GL_EXT_secondary_color GL_EXT_fog_coord GL_EXT_texture_env_add GL_ARB_texture_cube_map GL_ARB_transpose_matrix GL_ARB_texture_env_add GL_IBM_texture_mirrored_repeat GL_EXT_multi_draw_arrays GL_NV_blend_square GL_ARB_texture_compression GL_3DFX_texture_compression_FXT1 GL_EXT_texture_filter_anisotropic GL_ARB_texture_border_clamp GL_ARB_point_parameters GL_ARB_texture_env_combine GL_ARB_texture_env_dot3 GL_ARB_texture_env_crossbar GL_EXT_texture_compression_s3tc GL_ARB_shadow GL_ARB_window_pos GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_ARB_vertex_program GL_EXT_texture_rectangle GL_ARB_fragment_program GL_EXT_stencil_two_side GL_ATI_separate_stencil GL_ARB_vertex_buffer_object GL_EXT_texture_lod_bias GL_ARB_occlusion_query GL_ARB_fragment_shader GL_ARB_shader_objects GL_ARB_shading_language_100 GL_ARB_texture_non_power_of_two GL_ARB_vertex_shader GL_NV_texgen_reflection GL_ARB_point_sprite GL_EXT_blend_equation_separate GL_ARB_depth_texture GL_ARB_texture_rectangle GL_ARB_draw_buffers GL_ARB_pixel_buffer_object GL_WIN_swap_hint GL_EXT_framebuffer_object

**Comment by MikeHolder** [comment]
> Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
You are running Windows 7 with Service Pack 1 installed.

> Runtime Version: .NET CLR 4.0.30319.42000
It looks like you have .NET Framework 4.6.x installed.

>OpenRA.Platforms.Default.Sdl2GraphicsDevice.DrawPrimitives(PrimitiveType pt, Int32 firstVertex, Int32 numVertices)
The crash occurs here and you're receiving a **GL Error: 1286** which means you're having a frame buffer overload.

Your graphics adapter is an Intel 965/963 Graphics Media Accelerator. After doing some research I found that the maximum supported version of OpenGL that it supports is 2.0. **However**, your graphics adapter supports up to shader version 1.10 which the game requires a minimum of 2.0 as [referenced here](https://github.com/OpenRA/OpenRA/wiki/Requirements#hardware).

While the game does appear to be working in Direct3D, it is going to throw that error anytime you try to run it in OpenGL. My recommendation is to run it in Direct3D.

**Comment by pchote** [comment]
Thanks for the info @MikeHolder, that sounds plausible.  @temporary99 please try upgrading your graphics drivers, and if the problem persists file a new ticket with the new logs.
