### ISSUE TITLE
Crash when trying to open replays

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/OpenRA#12034]
Hey, 
I was at http://www.gamereplays.org and tried to open the replay file with OpenRA.
(with firefox from the temp location directory)
Then it crashed due to no rights to access that file.

![openopenra replay crash](https://cloud.githubusercontent.com/assets/5147014/18553689/ac16959c-7b61-11e6-99cd-8b7e14af1cc5.png)

(Note: 
- Opening OpenRa with a loaded replay streight from the normal replay directory works fine. 
- Even, if I don't have the fitting map, I'll get an "incompatible replay" message.

 )

**Comment by pchote** [comment]
This will be an easy fix - wrap the loading attempt in a try-catch and show an error if it throws.
