### ISSUE TITLE
D2K Disc not found

### ISSUE THREAD

**Issue by Sora93** [OpenRA/OpenRA#12033]
I have a physical disc of Dune 2000 but OpenRA (20160904) says it cannot find the disc and suggests I download the content. Current OpenRA Release (20160508) locates the disc perfectly fine.

Edit: Forgot to mention this is for Windows.

**Comment by pchote** [comment]
Is your disc english, or a different language?

**Comment by Sora93** [comment]
English disc as far as I can tell.

**Comment by pchote** [comment]
Please insert the disc and the run this debug utility:
https://www.dropbox.com/s/3me1sbn9pzv0mxz/checkdisk.zip?dl=1

Sorry, a Dropbox link is a bit dodgy, the code is here if you want to inspect and compile it yourself:
https://gist.github.com/pchote/ffb5582a027274e6fe0ab750404e1521

This will write a file called `disclist.txt` with output like the following:
```
C:\
	Type: Fixed Format: NTFS
	C:\MUSIC/AMBUSH.AUD: (not found)
	C:\SETUP/SETUP.Z: (not found)
D:\
	Type: CDRom Format: CDFS
	D:\MUSIC/AMBUSH.AUD: bd5926a56a83bc0e49f96037e1f909014ac0772a
	D:\SETUP/SETUP.Z: 937f5ceb1236bf3f3d4e43929305ffe5004078e7
```

Please copy what it says here.

**Comment by Sora93** [comment]
Here you go directly from disclist.txt

```
C:\
	Type: Fixed Format: NTFS
	C:\MUSIC/AMBUSH.AUD: (not found)
	C:\SETUP/SETUP.Z: (not found)
D:\
	Type: Fixed Format: NTFS
	D:\MUSIC/AMBUSH.AUD: (not found)
	D:\SETUP/SETUP.Z: (not found)
E:\
	Type: CDRom Format: CDFS
	E:\MUSIC/AMBUSH.AUD: bd5926a56a83bc0e49f96037e1f909014ac0772a
	E:\SETUP/SETUP.Z: 029722e70fb7636f8120028f5c9b6ce81627ff90
F:\
	Type: CDRom Format: (not ready)
	F:\MUSIC/AMBUSH.AUD: (not found)
	F:\SETUP/SETUP.Z: (not found)
```

**Comment by pchote** [comment]
Ok, that's what I was afraid of.  It looks like there were multiple editions of the install disc.

I'll write another tool to scan your disc contents so that I can update the OpenRA metadata, but for now can you please share the README.TXT from the root of the CD?

**Comment by Sora93** [comment]
Here is the readme directly from the CD http://pastebin.com/edg3ajK6

**Comment by pchote** [comment]
@Sora93 can you please provide a copy of the SETUP/SETUP.Z file? It should be roughly 30MB.

**Comment by Sora93** [comment]
Sorry for late response, have had some computer issues, and im going to be gone for 5 days starting today. As soon as I get back I will gladly upload it for you :)

Also, Any service you would prefer for the upload?

**Comment by LipkeGu** [comment]
dropbox for example

**Comment by Sora93** [comment]
http://www.mediafire.com/file/1cdsai8hzpmt9t8/SETUP.Z

I forgot I already had a mediafire account, so I used it instead of creating a dropbox account. Sorry for the advertisements on the download page.

**Comment by pchote** [comment]
@Sora93: Can you please try replacing the contents of your `&gt;openra install dir&lt;/mods/d2k/installer/d2k.yaml` with http://pastebin.com/raw/0QfgaE1N and check the disc detection again?

**Comment by pchote** [comment]
@Sora93: Are you able to test this fix out?  It will soon be too late to include this in the release otherwise.

**Comment by Sora93** [comment]
Very sorry for the delay, ill get on it right now.
