### ISSUE TITLE
No longer possible to close chat dialog in replays with hotkeys

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#12031]
#11957 has the side-effect that you can no longer use enter to close the expanded chat overlay.  This is a minor but annoying regression.  We could assign enter as the cancel hotkey in that situation.

**Comment by obrakmann** [comment]
That won't work, `TextFieldWidget`s discard all keyboard input when they're disabled.

**Comment by pchote** [comment]
assign enter as the cancel *button* hotkey, I mean.
