### ISSUE TITLE
OSX Fullscreen Issues

### ISSUE THREAD

**Issue by djlists** [OpenRA/OpenRA#12043]
On OSX, choosing "fullscreen" seems to be a pseudo-fullscreen. The frame is not properly centered, resulting in a gap above the border on the top and no border on the bottom for the initial start-game menu. Unable to change between desktops (command + arrow) like with previous release. RA mod

**Comment by djlists** [comment]
The game isn't playable because bringing the mouse to the bottom of the screen does not scroll down because the frame extends off the screen.

**Comment by pchote** [comment]
What version of OSX and OpenRA are you using.  It works as expected for me.

**Comment by JoshuaPettus** [comment]
Works as expected for me, I am using 10.11 on 2010 Macbook Pro

**Comment by djlists** [comment]
OSX 10.11.6 and the OpenRA Playtest 20160904
![openra](https://cloud.githubusercontent.com/assets/20367532/18610914/7265cd3a-7cf7-11e6-8f06-3be5832670a6.jpg)

**Comment by djlists** [comment]
That's with a MBP, clamshell closed, playing on an external 4k monitor. If I disconnect the monitor and open the clamshell, the play border is properly framed. However, the mouse cursor appears about an inch above where the program thinks it is, so hovering over "settings" causes "quit" to become highlighted.

Using Control+Arrow (not command+arrow as I mentioned before) still doesn't work to switch back to the desktop.

**Comment by pchote** [comment]
Does pseudo-fullscreen work correctly?  The (non-pseudo) fullscreen option is really only there for backwards compatibility.

**Comment by djlists** [comment]
I was using "fullscreen" because it allowed me to switch back to the desktop without closing the application. Pseudo-fullscreen didn't allow that option. I tried to switch back to pseudo-fullscreen just now and the pulldown is empty. Also, all of the text has some poor aliasing going on.

**Comment by pchote** [comment]
It sounds like you have something very unusual going on with your OSX installation.  Have you installed any special GPU drivers or other OS modifications?

The "Fullscreen" mode uses the old-school modal fullscreen behaviour, which will override and disable mission control / spaces / returning to desktop.

The "Pseudo-fullscreen" mode integrates with OSX's native fullscreening behaviour, so integrates properly with mission control and spaces.

**Comment by djlists** [comment]
Nope. Should be pretty vanilla. I tried rebooting with no external monitor. The pull-down is still empty.

**Comment by djlists** [comment]
If I plug the external monitor back in, the display is offset again but the pointer is in the correct location and the pull-down is populated properly.
