### ISSUE TITLE
[RA] Add 1-rank to paratroopers

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#12042]
This is a minor version of what was originally proposed in #11066. This idea really fascinates me for some reason and it's worth bringing up again now if it has a chance to get implemented before the next release.

Having the paratroopers drop with 1-ranks would look really gorgeous. Balance wise it would make the drop _slightly_ stronger with the upgrades but given the current strength of the paradrop one would expect it to be regarded as an aesthetic finish more than anything else.

As an added easter-egg feature it would be really cool to have the paradrop upgrade to rank 2 with a spy in those fringe cases where a player gets control of both factions.

**Comment by Micr0Bit** [comment]
http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=19535

**Comment by SoScared** [comment]
closed via #12739
