### ISSUE TITLE
Starting units can be incarcerated

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#12057]
![image](https://cloud.githubusercontent.com/assets/756669/18617366/fcdfaee6-7dcd-11e6-88f9-8ac46839e36b.png)

Similar to https://github.com/OpenRA/OpenRA/issues/6515.

**Comment by pchote** [comment]
The suggestion in #6515 isn't really feasible: the domain index doesn't know about buildings partitioning off areas.

A simpler fix is to put impassible map props in these bad cells on a map-by-map basis.

**Comment by Mailaender** [comment]
This was discovered on http://resource.openra.net/maps/13001/ Not a fan of invisible walls and working it around on a map-by-map basis. As the distance to the MCV is small, maybe a real pathing check could be added prior to spawn without effecting performance too much.

**Comment by RoosterDragon** [comment]
We now have the building blocks to make this possible.

Pathfinder exposes a `PathExistsForLocomotor` method that currently checks only terrain, but we could introduce another one that checks for the (subset of) immovable actors that `hierarchicalPathFindersBlockedByImmovableByLocomotor` knows about.
https://github.com/OpenRA/OpenRA/blob/fe35c42eadcfd6fb7b05eb3df28207b7981b450b/OpenRA.Mods.Common/Traits/World/PathFinder.cs#L245-L259

Then we can generate some candidate locations (e.g. area around the MCV) and filter to only those with a reachable path, even taking the immovable actors into account. The check is quite cheap so could be applied to #6515 as well.
