### ISSUE TITLE
Veterancy icons cannot be seen in the current Tiberian Sun  Bleed

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#12058]

**Comment by reaperrr** [comment]
My guess would be a Z-sorting issue.

**Comment by LipkeGu** [comment]
It is a regression indeed, i can remember they was there before we put steps in the direction of the per Pixel depth data and Z-Ordering a half year ago

**Comment by pchote** [comment]
Another omission from #11862.
