### ISSUE TITLE
OpenRA-bleed b820f421c0f46e76c85f2be6feae13fa594b0a08 - Exception of type `System.InvalidOperationException`: Out of sync

### ISSUE THREAD

**Issue by Cilyena** [OpenRA/OpenRA#12059]
> Exception of type `System.InvalidOperationException`: Out of sync

After 20min / 1 hour the game crash with this return inside exception.log

**Players and host :**
**Slide :** host and player
**RedWolf + bombe :** Players

**Slide (host) :** SharedRandom: 1307596139 (#1021274)
**RedWolf and bombe :** SharedRandom: 1938207618 (#1021275)

In logs.zip exception + syncreport off all players.

[logs.zip](https://github.com/OpenRA/OpenRA/files/478909/logs.zip)

**Comment by reaperrr** [comment]
@Cilyena Could you upload the replay as well?

**Comment by Cilyena** [comment]
Slide replay : 
[OpenRA-2016-09-18T174409Z_Slide.zip](https://github.com/OpenRA/OpenRA/files/478934/OpenRA-2016-09-18T174409Z_Slide.zip)

It's OpenRA-bleed of today + only one patch (+2-1) https://github.com/OpenRA/OpenRA/pull/12056/files (waiting commit) for the Channel "sync".

**Comment by Cilyena** [comment]
bombe replay :
[Uploading OpenRA-2016-09-18T174408Z_bombe.zip…]()

**Comment by Cilyena** [comment]
bombe replay :
[OpenRA-2016-09-18T174408Z_bombe.zip](https://github.com/OpenRA/OpenRA/files/478955/OpenRA-2016-09-18T174408Z_bombe.zip)

**Comment by Cilyena** [comment]
RedWolf replay :
[OpenRA-2016-09-18T174409Z_RedWolf.zip](https://github.com/OpenRA/OpenRA/files/478965/OpenRA-2016-09-18T174409Z_RedWolf.zip)

**Comment by Mailaender** [comment]
https://gist.github.com/Mailaender/551512e7235c1a74d4acec38ee97028d/revisions `AutoTarget` also differs, so this could be something sight related.

**Comment by pchote** [comment]
What specific commit were you using?  There were a lot of merges on the 18th, so this could easily happen if you didn't fetch / check out at the same time.  You should always use `make version` before playing bleed games to guard against that possibility.

**Comment by Cilyena** [comment]
https://github.com/OpenRA/OpenRA/tree/b820f421c0f46e76c85f2be6feae13fa594b0a08
+ only one manual patch (+2-1) https://github.com/OpenRA/OpenRA/pull/12056/files (waiting commit) for the Channel "sync".
