### ISSUE TITLE
[D2K] Show unlocked things in tooltips

### ISSUE THREAD

**Issue by tytannial** [OpenRA/OpenRA#12069]
![20160917010742](https://cloud.githubusercontent.com/assets/11215623/18677354/169678d8-7f8b-11e6-9a33-95703f7a00f9.png)
The upgrade tooltips are too simple. It should show unlocked things.

**Comment by ltem** [comment]
Hi,

I would like to do the PR for this issue. It is already working on my side but such topics are prone to style/text changes.

Upgrade Conyard:
![d2k_upgrade_conyard](https://cloud.githubusercontent.com/assets/20945684/21624408/2e225dae-d207-11e6-9c72-11df9db7237c.png)

Upgrade Barrack:
![d2k_upgrade_barrack](https://cloud.githubusercontent.com/assets/20945684/21624406/2e1f59b0-d207-11e6-9f46-2a6508f46dc5.png)

Upgrade Light Factory:
![d2k_upgrade_light](https://cloud.githubusercontent.com/assets/20945684/21624409/2e243c96-d207-11e6-9498-391cb8bcc8a0.png)

Upgrade Heavy Factory:
Maybe this should be split on two lines.
![d2k_upgrade_heavy](https://cloud.githubusercontent.com/assets/20945684/21624407/2e20dc5e-d207-11e6-8715-17404da391a2.png)


Upgrade Research Center:
![d2k_upgrade_research](https://cloud.githubusercontent.com/assets/20945684/21624410/2e275d22-d207-11e6-8b72-fad9dabe2edf.png)


Would this be possible? I'm new to git but if I follow the OpenRA wiki I think it should work :)

**Comment by MustaphaTR** [comment]
Well, it looks fine but

1-) You miswrote Atreides. There is no s after A.
2-) Use full and current names of units, Large Concrete, Thumper Infantry, Missile Quad and IX Research Center,
3-) Put Trooper before Engineer.

**Comment by ltem** [comment]
1-) Removed the awkward s

2-) Concrete: Large concrete inherits from ^concrete and doesn't have its own tooltip, so ingame both concrete slabs are called "Concrete" [LinkToLine](https://github.com/OpenRA/OpenRA/blob/bleed/mods/d2k/rules/structures.yaml#L12)
I added the `Tooltips` (`Concrete Slab` and `Large Concrete Slab`) in the structure yaml


Thumper: There is no `Thumper Infantry` in the infantry.yaml just `Thumper`... so I kept it this way

3-) Done

![upl](https://cloud.githubusercontent.com/assets/20945684/21655070/af1edade-d2b8-11e6-9da6-cc2f3a32f5e3.png)

So can I PR it?

**Comment by pchote** [comment]
These tooltips are unreasonably wide, so you should add linebreaks.

**Comment by ltem** [comment]
@MustaphaTR: Yeah the naming is generally a bit inconsistent (IX Research Centre (UK form: [manual](http://nyerguds.arsaneus-design.com/manuals/Dune%202000/Dune%202000%20-%20English.pdf) and in OpenRA [yaml](https://github.com/OpenRA/OpenRA/blob/bleed/mods/d2k/rules/structures.yaml#L855)) <> IX Research Center (US form: gruntmodversion and [online-wiki](http://dune2k.com/Duniverse/Games/Dune2000/Details/Structures))
I have chosen the UK version because it is like this in the yaml-file...

@pchote: less wide version
![ulp3](https://cloud.githubusercontent.com/assets/20945684/21661759/16df13f6-d2d6-11e6-8d1b-d8655c429d4f.png)

**Comment by chrisforbes** [comment]
Default language should be consistently US English.

**Comment by ltem** [comment]
Okay, I can do these renames but I don't know if there are any additional changes needed.

The repository search listed me these files: [Link](https://github.com/OpenRA/OpenRA/search?utf8=%E2%9C%93&q=research_centre)
- 4 yaml files 
- 1 C# file

**Comment by MustaphaTR** [comment]
There shouldn't be any additional changes needed, except maps that may have IX Research Center placed, which is a thing map makers need to do, not you. None of the maps comes with OpenRA D2K mod have such as only Atr1-3 is made yet.

**Comment by ltem** [comment]
Okay, I will only change the Tooltip

**Comment by reaperrr** [comment]
Closed via #12547.
