### ISSUE TITLE
Unable to join public and private servers - ArchLinux release-20160508

### ISSUE THREAD

**Issue by lazarus477** [OpenRA/OpenRA#12060]
When trying to join a public or a private server I never get fully  connected. I get to the lobby of the server but see none of the other players. Also the map screen keeps trying to download the map while the busy marker ticks back and forth, says the map is not available. This happens on any server I attempt to join.

OS: ArchLinux, latest as of 2016-09-19
Package installed is: openra-20160508-2

Have attempted to rename the game directory from my local user directory and start fresh, no change.

I am attaching a Wireshark dump performed during server join along with a screenshot of how far I get when joining a server. The screenshot is not from the attempt made during the Wireshark capture but has the exact same visual content (except for the IP address).

[openra-failed-server-join.pcapng.gz](https://github.com/OpenRA/OpenRA/files/479109/openra-failed-server-join.pcapng.gz)

![screenshot from 2016-09-19 01-04-52](https://cloud.githubusercontent.com/assets/7715430/18620710/26133338-7e18-11e6-9bfb-0601d9cf9d65.png)

**Comment by pchote** [comment]
I believe that #12066 (now merged for the next playtest) should fix this.  Thanks for the report!
