### ISSUE TITLE
Idle AI ore trucks

### ISSUE THREAD

**Issue by whi7ed3vil** [OpenRA/OpenRA#12065]
I've noticed several times that AI players will become completely ineffective after ore trucks stop harvesting. No amount of poking or prodding will help them "get with the program." Sometimes this is drawn by scarcity of resource, but then ore regenerates and the collection should be initiated again. Perhaps a backoff timer to scan for nearby ore in discovered/monitored map space instead of a complete idle scenario would be better? There is nothing less satisfying than defeating an AI that has incapacitated itself for minutes on end with a ton of nearby resources and no good reason. From my observations, it can happen with any AI style. Even more of an issue with allies who slowly let themselves be killed off. I've seen them stall out despite infusion with cash trucks just for fun.

**Comment by LipkeGu** [comment]
Maybe your refineries are blocked or the path to them. i have seen this very often when specting two Ai bots :) the AI blocks itself by producing Units.

**Comment by whi7ed3vil** [comment]
Nope, refineries were fully accessible. At one point I started pumping money into a bankrupt AI to see if I could revive the fight. No dice.

**Comment by pchote** [comment]
#15540 and related PRs are working to split HackyAI into separate modules.  One of the goals of this work is to allow map scripts to enable specific bits of AI logic at will.

**Comment by abcdefg30** [comment]
AI and harvester behaviour has changed a lot since 2016. Please reopen this if you have a reliable reproduction case on a newer version.

**Comment by GraionDilach** [comment]
This has been fixed in the last two cycles.
