### ISSUE TITLE
Carryalls stay still on air after putting a unit back

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#12081]
Noticable if Carryall has Plane characteristics as in my [modmaps](http://resource.openra.net/maps/16391/) instead of Helicopter. This doesn't happens after lifting a unit, but only putting it back.

There is a video that showing the problem: https://www.youtube.com/watch?v=e2WTRuwOFCc&feature=youtu.be

**Comment by pchote** [comment]
Carryall is designed only to work with helicopters.  I am strongly against cluttering up our already complicated carryall traits with the junky workarounds that drive the plane flying logic.

**Comment by MustaphaTR** [comment]
I know i don't know much abut coding but this sounded like an easy fix to me, just the carryall already works as expected when lifting unit, when both plane or heli, so same thing should be codded for putting unit back. 

Note that problem is not plane is vertically landing, i'm fine with that. I would love to see it take off normally as it does when first built and after lifting unit when placing unit too.
