### ISSUE TITLE
AI does not use factories until they are rebuilt in Nod missions

### ISSUE THREAD

**Issue by RoosterDragon** [OpenRA/OpenRA#12090]
Per @pchote in https://github.com/OpenRA/OpenRA/pull/12084#issuecomment-248976728:
> Is it just me, or does at least nod07a only start producing actors from these facilities after they have been destroyed and rebuilt? The ProduceInfantry and ProduceVehicle functions are only called from BuildBuilding and themselves. The behaviour ingame seems to confirm this.

I can confirm this does appear to be the case.

**Comment by abcdefg30** [comment]
I can't confirm: https://github.com/OpenRA/OpenRA/blob/bleed/mods/cnc/maps/nod07a/nod07a.lua#L211-L213
