### ISSUE TITLE
TS laser turret preview shows random voxel instead of turret

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#12109]
Before placing them down, the preview often shows some other randomly chosen voxel. Once placed down, everything is fine.

I assume this affects voxel turrets in general.

**Comment by pchote** [comment]
Something seems to have regressed our texture bindings.  See also http://logs.openra.net/#21:33:03

**Comment by abcdefg30** [comment]
Could #11341 be related as well?

**Comment by pchote** [comment]
It very likely is.

**Comment by pchote** [comment]
Closing as duplicate of #11341.

**Comment by reaperrr** [comment]
This is actually still a problem on bleed, but it *is* fixed by #13485 so I won't bother reopening this.
