### ISSUE TITLE
OutOfMemoryException (external mod)

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#12108]
After letting a huge (estimated 200+) amount of actors fire at an empty cell for a while, I stopped them, let them fire again for a while, same for a third time, then selected all units of a specific type (only about 6 of them) and then ordered them to shoot at an empty cell again, which is when the OOM triggered.

It should be noted that after every time I let all 200+ actors fire for a while and then ordered them to stop, ms/Tick did not recover entirely, so the 'idle' tick load was building up over time. For comparison, before the 3rd all-unit firing phase, it was only ~15ms/tick, before the first shooting at that empty cell it was single-digit (don't remember the excact value).

based on bleed from Sept. 18th, right after #12014 was merged.

[exception.log](https://gist.github.com/reaperrr/a15daf3d23ba210b931d65fdd18c556f)
[perf.log](https://gist.github.com/reaperrr/f796279a71e0386fdc5e1ed946679153)

No custom warheads were used. Custom projectile code was used, I'll see if I can repro the OOME with bleed's projectiles and/or a specific projectile type.

custom code can be found here, if necessary: 
https://github.com/reaperrr/OpenRA/tree/mods-mw-code

**Comment by reaperrr** [comment]
This issue appears to be exclusive to `LaserZap`, and it affects bleed, not just my mod code.

Repro case: Give Minigunner in TD mod the Laser weapon, build a massive amount of them, write down or memorize the tick and render performance before firing, let them fire for 1-2 minutes or so, order them to stop, compare the tick/render ms with the values from before they started firing.

**Comment by reaperrr** [comment]
It might be better to change ReloadDelay to something higher than the beam's Duration to avoid beams stacking up faster than they fade (I used a ReloadDelay of 25 for above repro case).

**Comment by pchote** [comment]
If the projectile doesn't define a hit animation it will never be removed from the world.
