### ISSUE TITLE
[TS/RA2] Some Ideas about bridges...

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#12105]
- Low Bridges could be reduce the speed of a unit. (Low: 75% / 100% or High: 90% / 100%)
- The Unit weight could be affecting the health of bridges and damage them.
- The Amount of using a Bridge could initiate a "Tired material" effect.

This would effect the Gameplay:
- A Unit can damage Bridges ( By moving over them, or by its weight)
- Players / AI has to repair a Bridge when they gots damaged
- 100 Units cant use the Bridges at the same time :)
- Non-repairable bridges are broken forever...
- Unit Speed changes on type of damage states and bridge types

**Comment by pchote** [comment]
Mods or scripted maps have the ability to change things like this, but for the default mod we aren't looking to rework the default bridge mechanics.
