### ISSUE TITLE
Negating the minimum value of a twos complement number is invalid.

### ISSUE THREAD

**Issue by nicefive** [OpenRA/OpenRA#12101]
Version: playtest-20160904

Hello all, I keep crashing with this error and have some information about it.

Exception of type `System.OverflowException`: Negating the minimum value of a twos complement number is invalid.

I have seen something about this error before but can only find a cached page on Google asking someone for a replay, 

I am seeing this error a lot and can produce multiple log file sets and replays if required.  We play large custom maps (normally 256x256) with modified rules to make games challenging and longer and work well on very large maps.  We spend much time working out how to make big MP maps run faster by carefully tweaking rules and map layout.  We archive all of our games' log files and replays by default and create our own maps.  We have a number of games producing this error which is becoming troublesome.

I think this problem is related specially to Allied AA guns firing.  It seems to connected to the instant a new gun is built and happens more regularly when the gun is near the edge of the map (and the target aircraft is off the map) although it can also happen when the gun is anywhere.

After looking at a number of exception call stacks, I am suspicious that before the turret is "fully built", some angle values between the turret and the target aircraft pass an invalid value to System.Math.AbsHelper() when calculating the inverse tangent between the 2 sets of coordinates to check whether the gun's yaw matches the target bearing.  In short, it seems to depend where the target aircraft when the gun is built.

I can't say that I am right about the AA gun theory, but there is some evidence of this.

This particular game was suffering poor performance patches due to the pathfinder not liking units on a long thin bridge, we were in the process of producing this on demand and ending it again by taking them out!  I don't think performance is linked to this crash, I just wanted to explain the timings in perf.log.

[Logs.zip](https://github.com/OpenRA/OpenRA/files/491514/Logs.zip)

Keep up the good work.

James

**Comment by nicefive** [comment]
Forgot to mention we only play RA.

**Comment by pchote** [comment]
Yes, please provide some replays triggering this (ideally ones that crash early into the game).  You'll also need to share the custom maps and rules that go with them.

**Comment by nicefive** [comment]
[2016-09-05 1201 Second Attempt v4 [256x256].zip](https://github.com/OpenRA/OpenRA/files/491832/2016-09-05.1201.Second.Attempt.v4.256x256.zip)

Attached is everything you should need (logs/screenshots/maps/rules).  This game crashed after about 1h 20m, I am sorry if this seems like ages but our games often go on for several hours.

**Comment by nicefive** [comment]
We have played 2 games today and it has crashed both times after a couple of hours or so.

Interestingly the second time it happened after I selected a unit that was off the map (a Mig pilot who had been there for some time unnoticed).  So it may not all be about AA guns but I am convinced it is to do with aiming at objects that are off the map.

James
![openra-2016-09-25t182022863z](https://cloud.githubusercontent.com/assets/22424535/18817527/63fd5d6c-835a-11e6-9107-0259424de5ba.png)

**Comment by nicefive** [comment]
I found another game in our database.  This game has the same error but crashes after just 18 minutes which should make debugging less tedious.

[2016-09-22 2048 Big Island v4 [256x256].zip](https://github.com/OpenRA/OpenRA/files/491843/2016-09-22.2048.Big.Island.v4.256x256.zip)

**Comment by nicefive** [comment]
Might be worth noting that the game always crashes if paused for around 6 hours but I will start a new issue for that later on when I have found the logs as I suspect it is unrelated.

**Comment by pchote** [comment]
That replay was exactly what I needed to identify the issue, thanks!
Fixed in #12107.

**Comment by nicefive** [comment]
Excellent.  Reproducing a bug is often the hard part!
