### ISSUE TITLE
RA: V2 Rockets shake when aiming at certain angle

### ISSUE THREAD

**Issue by kyrylo** [OpenRA/OpenRA#12117]
The GIF describes everything. At certain angles v2's animation looks really strange (it starts shaking):

![untitled](https://cloud.githubusercontent.com/assets/1079123/18855046/7284fed6-8458-11e6-97dd-f93844090f0d.gif)

**Comment by SoScared** [comment]
Yeah that bug has been there for quite some time. It can get worse sometimes when it goes into complete seisure mode for a longer period of time.

**Comment by MikeHolder** [comment]
I think what's happening is a tracking issue mixed with a bit of lag. It's trying to track the target but it mistakens the target in being in a spot before it realizes where it's actually at. I'll see if I can debug it.

**Comment by reaperrr** [comment]
At least part of the problem is probably that the V2 has only 8 facings for aiming, if the 'real' facing is smack in the middle between two facings the art supports, it probably can't decide which one to use.

Something similar can be observed with planes flying in certain directions (their art only covers 16 facings).

**Comment by MikeHolder** [comment]
That's a very good point. So not really a bug, but more appropriately something that needs polished - as was tagged.

**Comment by pchote** [comment]
Polish bugs are still bugs!

**Comment by Arular101** [comment]
I always wondered why this happens only for the V2 rocket launcher and not for the artillery. Maybe a nice workaround of the missing facings is, that the V2 faces towards the enemy only when the rocket is loaded and ready to launch. This behavior is present in the original Tiberian Sun where the Mammoth mk. II only aims at the enemy when its railgun was reloaded and ready to shoot.
