### ISSUE TITLE
RA2 lobrdb* sprites are not parsed correctly

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#12115]
https://github.com/OpenRA/OpenRA/pull/12098 hides the crash, but didn't really solve https://github.com/OpenRA/ra2/issues/292. Looks like https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/SpriteLoaders/ShpTSLoader.cs doesn't fully implement the compression used or it doesn't swallow corrupt data like the original game.

**Comment by GraionDilach** [comment]
I haven't checked if it applies to the particular files, but the TS SHP loader marks all SHPs which start with an empty frame invalid.

**Comment by GraionDilach** [comment]
Funfact: apparently they only crash if you enable compression on them.

**Comment by reaperrr** [comment]
> Funfact: apparently they only crash if you enable compression on them.

I'm not surprised, if they aren't compressed then the color index for each pixel will be defined and the frame bounds will equal the source pngs/pcxs.
