### ISSUE TITLE
[TS] Selection Boxes of Buildings have wrong offsets

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#12119]
Map was converted and is the TS Map "Grand Canyon"

![sell_bounds](https://cloud.githubusercontent.com/assets/2057932/18876718/09291ed6-84cb-11e6-8a25-b0d2d7c62788.png)

**Comment by abcdefg30** [comment]
This will be fixed when we get "3D" health bars (and selection boxes), I guess.

**Comment by StexoO** [comment]
The long "undamaged" building seems to be cut by the ground.

**Comment by Mailaender** [comment]
@reaperrr already tweaked the selection boxes for the base buildings, but we haven't corrected the civilian buildings. The automatically calculated offsets seem to be optimized for the RA/TD era SHP format.

**Comment by Mailaender** [comment]
In fact: we have sprite offsets since https://github.com/OpenRA/OpenRA/pull/3407, but that pull request didn't adapt the surroundings.

https://github.com/OpenRA/OpenRA/pull/13926 fixes this issue.
