### ISSUE TITLE
Don't render all off-screen selection decorations

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#12111]
They are not effects so they're not covered by #11676, but selection decorations are more expensive than actor sprite graphics and many effects, so screen-partitioning them as well would help render performance when the player has any significant force selected outside his current viewport.

In my case, with a bit over 200 actors off-screen, the difference between 'all selected' and 'none selected' was ~9 Render ms/tick (~12.5 vs. ~3.1), so the potential win in these situations is rather huge.

**Comment by pchote** [comment]
The standard RenderBounds filtering should be preventing these (and anything else on the actor) being rendered if it is off screen.  Is this still valid?

**Comment by reaperrr** [comment]
This is still valid even with #14482, yes.

The most expensive ones - selection box and health bar - are `IRenderAboveShroud(WhenSelected)`, so they'll only be filtered once #14082 is merged.
