### ISSUE TITLE
Technicians

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#12122]
When you sell a building ... you actually dont get a civilian in the original ... but "Technicians"... that use civilian-sprites ... 

![technician](https://cloud.githubusercontent.com/assets/9139965/18911574/204ac71e-857e-11e6-849a-3e3c0165641d.png)

according to http://cnc.wikia.com/wiki/Technician_%28Red_Alert%29 :
```
... technicians in Red Alert 1 could do mild damage to units with no armour whatsoever, like the V2 Rocket Launcher ...
```

**Comment by abc013** [comment]
Should we rename the civilians or create new units?
If we rename them, we have the Problem that villages are then only populated by technicians 😄.

**Comment by Micr0Bit** [comment]
@abc013 : new unit of course , because "civilians" also exist in the original ... only the buildings can leave technicians
