### ISSUE TITLE
Engineer walks in oil derrick (RA1)

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/OpenRA#12121]
Map:  http://resource.openra.net/maps/16481/
Replay: (note I zipped the replayfile because this uploader does not support the replay format)
[EngineerBug (watch yellows Oil) map Orion.zip](https://github.com/OpenRA/OpenRA/files/496510/EngineerBug.watch.yellows.Oil.map.Orion.zip)

The replay shows an engineer (from player yellow) walking in a oil derrick.

The Mod Is RA1 where normally engineers have to get close, but not walk inside buildings.
That map has custum rules, yes, but engineers are using the normal RA1 behaviour on this map. 
I even checked tha yaml file. And there's no Lua script added. 
In my understanding of the custum rules, they can't change between those 2 capture modes while the match is running. 
I think this could be a rare bug.
I tried to recreate the capture behaviour but was unable to do so.

Thanks for checking, greetings yellow

**Comment by TheRaffy** [comment]
talked with framelimiter, he can confirm that issue, he saw it at other maps too.  (Behind the veils)

**Comment by abcdefg30** [comment]
Could this be #11505?
(Was the oil derrick already captured before and then you tried to recapture?)

**Comment by TheRaffy** [comment]
Yes, It was already captured by an enemy and also damaged. In the replay you can clearly see that the HPbar of the enemy oil derrick gets restored.

This means, yes it is #11505

**Comment by pchote** [comment]
Closing as duplicate.
