### ISSUE TITLE
OpenRa has encountered a fatal error while playing Mission 04 - RA: Ten to one

### ISSUE THREAD

**Issue by ckweb1** [OpenRA/OpenRA#12128]
Hi,
my OpenRa encountered a fatal error:
[copied from EventLog]
Name der fehlerhaften Anwendung: OpenRA.Game.exe, Version: 0.0.0.0, Zeitstempel: 0x00000000
Name des fehlerhaften Moduls: unknown, Version: 0.0.0.0, Zeitstempel: 0x00000000
Ausnahmecode: 0xc00000fd
Fehleroffset: 0x0c04d158
ID des fehlerhaften Prozesses: 0x3228
Startzeit der fehlerhaften Anwendung: 0x01d21a8d2cce6c1b
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\OpenRA\OpenRA.Game.exe
Pfad des fehlerhaften Moduls: unknown

An Exeptionlog was not created.

[Logs.zip](https://github.com/OpenRA/OpenRA/files/501642/Logs.zip)
Any ideas?

Thanks :)

CK

**Comment by reaperrr** [comment]
Going by perf.log, CallLuaFunc ran into an infinite loop at tick 8312.
