### ISSUE TITLE
Game still too slow, even with suggested modifications

### ISSUE THREAD

**Issue by liverheadbutt** [OpenRA/OpenRA#12127]
Hi,

first of all thanks for this wonderful game :)
As the title says, it's unfortunately too slow.

I'm using Trisquel GNU/Linux,
I have libmono 3.2.8 (I think... I also have 2.0 and 4.0), and managed to spawn a new x server:
xinit /usr/games/openra mono --gc=sgen -- :1 vt$XDG_VTNR

1) Average tick is between 4 (calm screen) and 13ms (busy screen)
and render time is around 75/80ms

2) perf.log:

          LoadMaps
    38 ms |   Sahara.oramap
     5 ms |   a-path-beyond.oramap
    10 ms |   alaska-anarchy-redux.oramap
     6 ms |   all-connected.oramap
     9 ms |   arctic-triangle-affair.oramap
    44 ms |   asymmetric-battle.oramap
     3 ms |   bad-neighbors.oramap
     5 ms |   barracuda.oramap
     4 ms |   behind-the-veil.oramap
     7 ms |   blitzkrieg.oramap
    15 ms |   bloody-delta.oramap
     5 ms |   bombardment-islands.oramap
     6 ms |   caffeinated.oramap
     5 ms |   calm-before-storm.oramap
     9 ms |   chaos-canyon.oramap
    15 ms |   chokepoint.oramap
     5 ms |   coastal-influence.oramap
     7 ms |   cold-front-1v1.oramap
     7 ms |   cold-front.oramap
     5 ms |   doubles.oramap
     8 ms |   doughnut.oramap
     4 ms |   east-vs-west.oramap
     5 ms |   encounter.oramap
     9 ms |   engagement.oramap
     4 ms |   equal-opportunity.oramap
     5 ms |   first-come-first-served.oramap
     7 ms |   forest-path.oramap
     9 ms |   ghost-town.oramap
    14 ms |   haos-ridges.oramap
    12 ms |   high-and-low.oramap
     6 ms |   keep-off-the-grass-2.oramap
    10 ms |   mad-science.oramap
     3 ms |   man-to-man.oramap
     5 ms |   marooned-2.oramap
    11 ms |   mass-confliction.oramap
    15 ms |   north-by-northwest.oramap
     6 ms |   northwestpassage.oramap
    16 ms |   ore-lord.oramap
    11 ms |   pool-party.oramap
     6 ms |   pressure.oramap
     5 ms |   puddles-redux.oramap
     8 ms |   regeneration-basin.oramap
    20 ms |   seaside-2.oramap
     9 ms |   sidestep.oramap
     4 ms |   singles.oramap
     8 ms |   snowy-island.oramap
     3 ms |   snowy-ridge.oramap
     6 ms |   sudden-death.oramap
     3 ms |   suffrage.oramap
     9 ms |   sunstroke.oramap
     4 ms |   synergy.oramap
    10 ms |   tabula-rasa.oramap
     6 ms |   tainted-peak.oramap
    11 ms |   temperal.oramap
     6 ms |   tournament-island.oramap
     9 ms |   vegetation.oramap
     3 ms |   warwind.oramap
     8 ms |   winter-storm.oramap
     7 ms |   allies-01
     8 ms |   allies-02
    19 ms |   allies-03a
    35 ms |   allies-03b
    25 ms |   allies-05a
     7 ms |   bomber-john
    10 ms |   center-of-attention-redux-2
    17 ms |   desert-shellmap
     3 ms |   drop-zone
     3 ms |   drop-zone-battle-of-tikiaki
     3 ms |   drop-zone-w
     5 ms |   fort-lonestar
    47 ms |   intervention
    22 ms |   koth-hopes-anchor
    42 ms |   monster-tank-madness
     9 ms |   poland-raid
     8 ms |   snow town
     8 ms |   soviet-01
     8 ms |   soviet-02a
     8 ms |   soviet-02b
    18 ms |   soviet-03
     9 ms |   soviet-04a
     9 ms |   soviet-04b
     9 ms |   soviet-05
    20 ms |   soviet-06a
     9 ms |   soviet-06b
    11 ms |   soviet-07
    17 ms |   survival01
    13 ms |   survival02
     8 ms |   training-camp
   924 ms --------------------------------------------------
          SpriteFonts
     8 ms |   PrecacheColor common|FreeSans.ttf 14px White
     2 ms |   PrecacheColor common|FreeSans.ttf 14px Red
     2 ms |   PrecacheColor common|FreeSansBold.ttf 14px White
     2 ms |   PrecacheColor common|FreeSansBold.ttf 14px Red
     5 ms |   PrecacheColor ra|ZoodRangmah.ttf 48px White
     5 ms |   PrecacheColor ra|ZoodRangmah.ttf 48px Red
     3 ms |   PrecacheColor common|FreeSansBold.ttf 18px White
     3 ms |   PrecacheColor common|FreeSansBold.ttf 18px Red
     4 ms |   PrecacheColor common|FreeSansBold.ttf 24px White
     4 ms |   PrecacheColor common|FreeSansBold.ttf 24px Red
     4 ms |   PrecacheColor common|FreeSans.ttf 12px White
     2 ms |   PrecacheColor common|FreeSans.ttf 12px Red
     2 ms |   PrecacheColor common|FreeSans.ttf 10px White
    20 ms |   PrecacheColor common|FreeSans.ttf 10px Red
     2 ms |   PrecacheColor common|FreeSansBold.ttf 10px White
     2 ms |   PrecacheColor common|FreeSansBold.ttf 10px Red
    83 ms --------------------------------------------------
          StartGame
          |   PrepareMap
          |   |   Map
    38 ms |   |   |   LoadSequences
    47 ms |   |   |   new Sequence("shok")
  1841 ms |   |   ------------------------------------------
     5 ms |   |   Map.Music
  1980 ms |   ----------------------------------------------
   552 ms |   NewWorld
          |   LoadComplete
     0 ms |   |   ScreenMap.WorldLoaded
     0 ms |   |   MenuPaletteEffect.WorldLoaded
     0 ms |   |   TerrainGeometryOverlay.WorldLoaded
    34 ms |   |   ShroudRenderer.WorldLoaded
     0 ms |   |   ResourceType.WorldLoaded
     0 ms |   |   ResourceType.WorldLoaded
     0 ms |   |   DevCommands.WorldLoaded
     0 ms |   |   PlayerCommands.WorldLoaded
     0 ms |   |   HelpCommand.WorldLoaded
     0 ms |   |   ScreenShaker.WorldLoaded
     6 ms |   |   BridgeLayer.WorldLoaded
          |   |   DomainIndex.WorldLoaded
    62 ms |   |   |   BuildDomains: Desert Shellmap for movement class 699
    53 ms |   |   |   BuildDomains: Desert Shellmap for movement class 4096
   127 ms |   |   ------------------------------------------
     6 ms |   |   SmudgeLayer.WorldLoaded
    43 ms |   |   SmudgeLayer.WorldLoaded
     1 ms |   |   ResourceClaimLayer.WorldLoaded
     0 ms |   |   PathfinderDebugOverlay.WorldLoaded
   666 ms |   |   SpawnMapActors.WorldLoaded
    65 ms |   |   LoadWidgetAtGameStart.WorldLoaded
    22 ms |   |   ResourceLayer.WorldLoaded
   401 ms |   |   LuaScript.WorldLoaded
  1375 ms |   ----------------------------------------------
  4054 ms --------------------------------------------------
    28 ms [1] Activity: Move
     4 ms [1] Activity: HeliFly
     2 ms [1] Trait: world->ActorMap
     3 ms [1] Trait: world->LuaScript
     5 ms [1] Trait: player->PlayerResources
     1 ms [1] Trait: player->EnemyWatcher
     6 ms [1] Trait: player->FrozenActorLayer
     1 ms [1] Trait: player->ClassicProductionQueue
     1 ms [1] Trait: player->SupportPowerManager
     3 ms [1] Trait: hpad->ProductionBar
     3 ms [1] Trait: tran.husk2->Burns
     7 ms [1] Trait: mine->SeedsResource
     1 ms [1] Trait: pbox->AttackGarrisoned
     5 ms [1] Trait: lst->WithLandingCraftAnimation
     1 ms [1] Render: world->SmudgeLayer
     2 ms [1] Render: world->ResourceLayer
     3 ms [2] Activity: Move
     2 ms [2] Activity: MoveFirstHalf
    19 ms [2] Activity: CallFunc
     8 ms [2] Activity: FindResources
     1 ms [2] Activity: Fly
     2 ms [2] Trait: tran->Aircraft
     1 ms [3] Activity: Move
     1 ms [3] Activity: AttackMoveActivity
     1 ms [3] Activity: Move
     1 ms [3] Activity: AttackMoveActivity
     1 ms [3] Activity: Move
     1 ms [3] Activity: AttackMoveActivity
     3 ms [3] Activity: Move
     3 ms [3] Activity: AttackMoveActivity
     9 ms [3] Activity: Move
     9 ms [3] Activity: AttackMoveActivity
     2 ms [3] Activity: Move
     2 ms [3] Activity: AttackMoveActivity
     5 ms [8] Activity: MoveFirstHalf
     1 ms [13] Activity: MoveSecondHalf
     3 ms [21] Activity: MoveSecondHalf
     3 ms [21] Activity: AttackMoveActivity
     1 ms [49] Trait: apwr->RenderSprites
     1 ms [52] Activity: AttackMoveActivity
     1 ms [52] Activity: Move
     1 ms [52] Activity: AttackMoveActivity
     2 ms [52] Activity: Move
     2 ms [52] Activity: AttackMoveActivity
     3 ms [52] Activity: Move
     3 ms [52] Activity: AttackMoveActivity
    67 ms [62] Trait: tran->RevealsShroud
     7 ms [79] Trait: ftrk->RevealsShroud

3) CPU and graphics card of x200
CPU: Intel(R) Core(TM)2 CPU         P8400  @ 2.26GHz
Graphics card: 00:02.0 VGA compatible controller: Intel Corporation Mobile 4 Series Chipset Integrated Graphics Controller (rev 07)

Any help appreciated.

**Comment by GraionDilach** [comment]
OpenRA requires and utilizes OpenGL 2.0 technology what your GPU only archives through a hacked GPU driver (this is the GMA 3000-4000 series) which probably falls back to software rendering at cases.

Doubt much can be done in this regard, your issue is clearly the rendering performance (you can even see it yourself if you enable Performance Stats in Options-Debug and compare the render and tick rates).

**Comment by Mailaender** [comment]
I encountered similar problems many years ago. Trisquel seems to ship an older Kernel. Try a distribution with a more recent version of it and also updating your Intel Mesa drivers.

**Comment by liverheadbutt** [comment]
@GraionDilach: Definitely rendering, the red line is still above the green one. Thanks for the data about the GPU. Maybe there's a way thanks to this.

@Mailaender: Thanks, I'll try this option then, though I doubt the Intel Mesa drivers are free software though (since I care about that more than playing the game).

**Comment by Mailaender** [comment]
Intel drivers should be free software. http://www.mesa3d.org/license.html Closing the issue here.
