### ISSUE TITLE
Yaml merge errors are silently dropped by the linter.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#12130]
The default rules are loaded instead.  This then causes confusing errors like the ones seen in #12086.  I suspect some of the linter weirdness we've seen on the resource center is caused by this.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Map/Map.cs#L390

**Comment by PunkPun** [comment]
Is this still an issue?

**Comment by abcdefg30** [comment]
I don't think so?
