### ISSUE TITLE
Cloak->UncloakOn: Damage only uncloaks when the damage state gets changed.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#12146]
Instead of all the cases when the actor suffers damage.

**Comment by LipkeGu** [comment]
There seems also be anather Bug?! In the originals it was able to uncloak Buildings when Units was next to it ~1 cell in OpenRA it doesnt happen. So it is unable for Factions (that doesnt have the ability to uncloak Units) to uncloak Units / Buildings. This gives them a totally dissadvantage

**Comment by Phrohdoh** [comment]
@LipkeGu That is completely unrelated to damage and OpenRA does support uncloaking an actor within a proximity.
