### ISSUE TITLE
Desync in AutoTarget TargetedActor

### ISSUE THREAD

**Issue by PanzerFurrry** [OpenRA/OpenRA#12143]
Clients crashed for all players in playtest-20160914 on map Barracuda by PizzaAtomica while playing on our dedicated server.
http://imgur.com/iqyFqKx

Exception.log - Player 1 (me, Linux): http://pastebin.com/iV4jkLXT
Syncreport.log - Player 1 (me, Linux): http://pastebin.com/hyR3yxWP

Exception.log - Player 2 (Linux): http://pastebin.com/HAjWriNr
Syncreport.log - Player 2 (Linux): http://pastebin.com/UxEs1BFm

Exception.log - Player 3 (Mac): http://pastebin.com/irp2LJr4

EDIT: As of this moment, new playtest is available, we will try to reproduce the problem again.

**Comment by LipkeGu** [comment]
can you test the about an hour released playtest 20161001?

**Comment by PanzerFurrry** [comment]
We played two times on the same map, same people, same settings with the new playtest-20161001 without crash.

**Comment by Mailaender** [comment]
Diff: https://gist.github.com/Mailaender/22b0acf83b1afe7977956477748d06d3/revisions Thanks for the report. This gives valueable intel.

**Comment by pchote** [comment]
This will be a duplicate of #12253, which was fixed by #12260.
