### ISSUE TITLE
Health bars are rendered for paradrop planes

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#12145]
... and probably other actors that have health but not selection decorations.

**Comment by anjew175** [comment]
I personally am a fan of seeing this information (specifically for the badgers) even if its just available on the "Always show" status option.

**Comment by pchote** [comment]
That should be done by adding the appropriate traits to the actors, not by leaving a bug unfixed.

**Comment by MustaphaTR** [comment]
In vanilla RA2 you can see units health bar by hovering over it even if the actor is unselectable. I'm not sure what exactly is the case here but i think we should add a way to see badger/paradrop plane and maybe D2K carryall health in OpenRA too.

**Comment by pchote** [comment]
This was broken by ed349f9086de53923b665e21e5a906422da1164d.
