### ISSUE TITLE
Settings - Audio - Audio Device showing unknown characters

### ISSUE THREAD

**Issue by pwust** [OpenRA/OpenRA#12150]
Seen in Windows binaries of "playtest-20161001", and "playtest-20160904", did not appear on "release-20160508": from main menu open "Settings", click on tab "Audio", and open drop down "Audio Device".
![2016-10-02_11-09-26](https://cloud.githubusercontent.com/assets/3417544/19019760/59e5e532-8892-11e6-93dd-8c9061635e4f.png)
The "Default Output" option is shown as expected, but any other audio device option is showing only a mixture of small rectangles and a few extra signs.
Trying to select any of these "crapped" audio device options, and restarting OpenRA will not change audio output away from default.
I have seen this on all three Mods in both "playtest-" Windows builts. PC is Win8.1-64bit. I did not test on any other platform.

**Comment by senneschall** [comment]
This already happened in playtest-20160904 on my machine with Win7 x64: [screenshot](http://imgur.com/gc39uUt). I have 4 soundcards installed, so there are 4 lines for me.

The sound.log is empty, no significant entry in any other log file is found.

**Comment by pchote** [comment]
What are you system languages?

**Comment by senneschall** [comment]
german

**Comment by reaperrr** [comment]
The list looks the same on my system, and I have only onboard sound.

**Comment by pwust** [comment]
my OS language in en-GB:
HKEY_CURRENT_USER\Control Panel\Desktop
    PreferredUILanguages    REG_MULTI_SZ    en-GB
, my locale (number and date formats) is German:
HKEY_CURRENT_USER\Control Panel\International
    LocaleName    REG_SZ    de-DE

**Comment by Basti504** [comment]
Got the same issue.

![Image](http://i.imgur.com/wdOf78k.png)

A quick debug in the playtest codebase shows the following.
System language is dutch.

![Image](http://i.imgur.com/h8zQsmX.png)
