### ISSUE TITLE
Forbidden maps should not be automaticly updated with new release

### ISSUE THREAD

**Issue by airetaM** [OpenRA/OpenRA#12157]
http://resource.openra.net/maps/13484/
This map was already forbidden and you can download it now

**Comment by abcdefg30** [comment]
I think that should be rather reported at https://github.com/OpenRA/OpenRA-Resources.
(Thanks for the report though! :) )

**Comment by x-a-n-a-x** [comment]
The third report made the map impossible to download.

**Comment by abcdefg30** [comment]
See @ihptru's comments on the map.
