### ISSUE TITLE
OpenRA: AI will not deploy new MCV

### ISSUE THREAD

**Issue by vincentvandenbergh** [OpenRA/OpenRA#12159]
After killing the MCV of an AI opponent, the AI will make a new MCV (if it has the service depot and war factory intact), but let the MCV idle around without deploying. 

This problem was first introduced in **Playtest 20160904.** 

Something in the codebase change between **release 20160508** and the previously mentioned playtest caused this. As I do not have any programming skills (I am learning some basic stuff in my little spare time) I can not fix it.

Reproducing the bug is easy, just let the AI make a warfactory and service depot and kill of the MCV.

**Comment by abcdefg30** [comment]
See #11305.

**Comment by LipkeGu** [comment]
The AI is currently only able to build an MCV when the AIs ConYard is destroyed maybe we should look over that part in HackyAI.cs :/

**Comment by GraionDilach** [comment]
@LipkeGu You're wrong. Adding a UnitsToBuild percentage will allow the AI to build MCVs even when the current MCV is deployed (That's the sole reason the AI over here can utilize mobile war factories, they have a percentage in UnitsToBuild and are listed in the Mcvs list).

**Comment by LipkeGu** [comment]
Yes it builds them but does not deploy them as far far i see in the code

**Comment by LipkeGu** [comment]
I tried to reproduce this with the following result:
30 minutes later the base had 8 Construction Yards and the game begun to lag
![mcv](https://cloud.githubusercontent.com/assets/2057932/19193973/612b5b7e-8cac-11e6-87b9-bd2c38611088.png)
