### ISSUE TITLE
TD Grenadier Crush Idea.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#12165]
When the time allows since I know everyone is busy :D if it would be possible to allow a mechanic of grenadier crushing.

A vehicle such as a light tank crushes a grenadier and causes damage to vehicles. Would help prevent some of the mass crushing issues vs GDI and give another reason to mix some Grenadiers in the infantry builds.

This is a mechanic idea similar to #11415

**Comment by anjew175** [comment]
Duplicate of #11409?

**Comment by AoAGeneral** [comment]
Oh hey so it is lol
