### ISSUE TITLE
Fatal error after downgrading to "release"

### ISSUE THREAD

**Issue by VoittajaTomi** [OpenRA/OpenRA#12166]
I am using Opensuse linux 42.1 and my openra version is the newest playtest. First I had the previous playtest, then downgraded to release. After first downgrading it I have not been able to launch the game and I am getting a "Openra has encountered a fatal error".

[exception-2016-10-03T192051Z.txt](https://github.com/OpenRA/OpenRA/files/507012/exception-2016-10-03T192051Z.txt)

I tried deleting  ~/.openra/ with all of its contents without any luck.

**Comment by pchote** [comment]
This is a known bug with mono.  You'll need to wait for the distro maintainer to update their mono packages.  Unfortunately this means that the playtest will be broken too!

**Comment by pchote** [comment]
Actually, looking again, I misread the mono version in your exception.log – 4.0.4 is pretty old, so it probably isn't that.  I'll reopen this until we know what's going.

**Comment by VoittajaTomi** [comment]
Also if I install the release and remove ~/.openra/*, it still won't work for me now.

**Comment by GraionDilach** [comment]
This sounds like a compiler optimization introduced in .NET 4.6 which Mono lacks - https://bugzilla.xamarin.com/show_bug.cgi?id=36942. The question is, how did it got there. I assume one of the dependencies we use got an update to .NET 4.6 and that's causing the trouble.

**Comment by pchote** [comment]
Sigh. This is *exactly* the kind of problem that have been trying avoid by complaining in PRs that update dependencies without a good reason.

Somebody will need to downgrade their mono and then check if this is repeatable / bisect over the dep update prs.

**Comment by GraionDilach** [comment]
On a second check, I'm still on Mono 3.2.8 and I'm unaffected, so... :D

**Comment by pchote** [comment]
I was able to reproduce this crash on my first launch after downgrading to mono 3.2.0.  Second and subsequent launches worked.  This must be occurring on a side code path.

**Comment by pchote** [comment]
#11933 is also a candidate.

**Comment by Mailaender** [comment]
I wiped https://build.opensuse.org/package/show/games:openra/mono-core for 13.2 and 42.1 which will trigger a rebuild of https://build.opensuse.org/package/show/games:openra/release and allow you to use your system Mono instead of the one provided by our repository.

**Comment by pchote** [comment]
I'd like to keep this open for now, because if that fix works for @VoittajaTomi then we will also need to revert #12100 and maybe #11933.

**Comment by Mailaender** [comment]
lt isn't required to revert #12100 and maybe #11933 as we have proper reproducible builds for SUSE not those built on an ancient Ubuntu VM. @VoittajaTomi just need to run `sudo zypper dup` to fix his installation.

**Comment by pchote** [comment]
That won't help people who download our ubuntu-compiled OSX and ubuntu/debian packages.

**Comment by pchote** [comment]
On OSX, at least, this is only a problem for 4.6 compiled builds.  #12100 came after the prep split, so this is now only a problem for bleed.

**Comment by pchote** [comment]
Comment from #12181: 
> Looks like this was a false alarm, I had forgotten that we now explicitly pass the sdk flag from travis, instead of having it in the default makefile. Building on mono 4.6 explicitly specifying the 4.5 sdk works fine for me locally.

@Mailaender: you should update your openSUSE scripts to pass the sdk flag when compiling.

**Comment by Mailaender** [comment]
Shouldn't we rather put the SDK flag into the Makefile?

> That won't help people who download our ubuntu-compiled OSX and ubuntu/debian packages.

The proper fix for that would be to build in VMs for each specific Ubuntu version to ensure compatibility with system Mono (and Lua) https://github.com/OpenRA/OpenRA/issues/9201 via Launchpad PPA or Open Build Service.

For Mac OS X I assume bundling https://github.com/OpenRA/OpenRA/issues/12170 or a version check in https://github.com/OpenRA/OpenRALauncherOSX would be an option.

**Comment by Mailaender** [comment]
> @Mailaender: you should update your openSUSE scripts to pass the sdk flag when compiling.

https://build.opensuse.org/package/rdiff/games:openra/playtest?linkrev=base&rev=34
https://build.opensuse.org/package/rdiff/games:openra/release?linkrev=base&rev=33

Done.

**Comment by Mailaender** [comment]
Notifying @svenstaro as https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/openra also needs to get updated when Mono 4.6 lands in Arch Linux.
