### ISSUE TITLE
The spy's tooltip doesn't match the spy's abilities.

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#12185]
The spy's tooltip says:
"Can detect cloaked units and **spies**."

According to [#8616](https://github.com/OpenRA/OpenRA/pull/8616) the "IgnoresDisguise:" trait was added to make spies detect other spies.  However they're missing the AutoTarget trait so they're unable to function correctly.

I'd suggest adding:
SPY:

> AutoTarget:
> 
> > InitialStance: HoldFire
> > ScanRadius: 5 (So they'll be able to move towards an enemy spy instead of just standing still.)

**Comment by reaperrr** [comment]
Closed via #12565.
