### ISSUE TITLE
TD tiberium silo, refinery explosion mechanic.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#12187]
This is part of the major balance needed for TD on the economy side. Upon destroying the silo and refinery it causes an explosion to happen. Refinery can be moderate to damage harvesters near by it and silos can be major. Enough to blow up power planets at least. This would cause extra protection and caution upon clustering up refineries and silos.

The balance of silos will be implemented if this can be featured in.

This is apart of the balance ideas such as #11415 
and #11409

**Comment by GraionDilach** [comment]
You can already use Explodes to create a nuke from a silo.

However, ideas like this just rings my warning bell that you're not exactly qualified to balance TD, but creating you8r own mod under a disguise of balance patches.

:-1:

**Comment by AoAGeneral** [comment]
Nice meme.

http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=17430

**Comment by obrakmann** [comment]
People already barely build any silos. Discouraging players from building them is exactly the opposite of what we'd want to do. 👎

**Comment by AoAGeneral** [comment]
You might want to check the forum thread. There are plans to change the capacity to utilize the silos due to economy strat issues.

**Comment by pchote** [comment]
A lot has changed in the mean time, and it seems this idea is no longer relevant.
