### ISSUE TITLE
RA: Building placement / overlap (Service Depot / Missile Silo)

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#12184]
Current bleed.
(without "build everywhere")

![ora_build_overlap](https://cloud.githubusercontent.com/assets/10639257/19162912/1a793564-8bfa-11e6-85be-75b800c167f8.jpg)

**Comment by GraionDilach** [comment]
The Repair Depot has a + foundation, that's to be expected. It's a legacy thing, WW had it this way.

**Comment by pchote** [comment]
For better or worse this is intentional, so closing.
