### ISSUE TITLE
Multiplayer scorescreen ought not to cancel chat or chat message

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#12180]
It's a slight annoyance but often at the end of games people like to spend time typing in the chat. The scorescreen takes you out of the chat and furthermore cancels text written beforehand.

**Comment by rob-v** [comment]
Fixed by #13408. The text is still cancelled if you are writing while the game ends, but you can chat in menu chat now.

**Comment by pchote** [comment]
Fixed by #13408.
