### ISSUE TITLE
Hijacked units carry on with computers orders RA missions

### ISSUE THREAD

**Issue by Nineeva** [OpenRA/OpenRA#12183]
Much like captured war factories and barracks in C&C, hijacked tanks etc. carry on with their old orders once taken over by the player.  This means for example in exodus, if I hijack the enemy mammoth tanks they keep driving off to where the computer last sent them.

**Comment by pchote** [comment]
Why aren't we disabling hijackers in the RA missions? They weren't an original unit, and will introduce a bunch of potentially-breaking strategies and bugs like this.

**Comment by Mailaender** [comment]
The rules were converted from a 2013 OpenRA era version where hijackers didn't exist yet https://github.com/OpenRA/OpenRA/pull/11679 and the case where you capture enemy production buildings wasn't tested as getting the complex "as it is supposed to be played" logic done was hard enough.

**Comment by Nineeva** [comment]
Might be worth noting, to a less level their seems to be a bug with using engineers to capture vehicle husks in missions in C&C TD.  They don't seem to be moving but their turrets always face the wrong way and stay focused on one direction.
