### ISSUE TITLE
Add an "unstable" parameter to the [Desc] attribute.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#12188]
Our expectation for features to be complete and stable before merging them upstream makes life difficult for people who want to work on small parts of bigger features or for niche traits that we don't have test cases for in our default mods.

I believe that we can improve this situation, without hurting the stability or maintainability of our default mods, by allowing trait fields or entire traits to be marked as unstable using `[Desc("foo", unstable=true)]`.

These would be marked in the trait docs as unstable, indicating that modders should use these properties at their own risk.  We can then relax our review standards on these features, e.g. not requiring upgrade rules for incompatible changes, or allowing them to be merged with missing features or bugs if the benefits of the feature still outweigh the issues.

The main technical benefit comes from adding a `--disallow-unstable` flag to the `--check-yaml` utility command.  This would let us actively prevent unstable features from being accidentally or intentionally included in our shipping mods via the `make test` rule.

**Comment by pchote** [comment]
Since somebody asked on IRC I want to clarify that I see this as a compromise to cover the cases where our current review system fails.  It is *not* a golden ticket to people to be lazy and file a half-done PR because they've lost interest or coded themselves into a corner.

**Comment by reaperrr** [comment]
`WithSpriteBarrel` is a good example where this would help, it has 'lagged behind' the other sprite/voxel traits at least twice in terms of regressions due to lack of test cases.

**Comment by Phrohdoh** [comment]
We are in a sore spot of C# when implementing this on top of `Desc`.

```csharp
public sealed class DescAttribute : Attribute
{
	public readonly string[] Lines;
	public DescAttribute(params string[] lines) { Lines = lines; }
}
```

`params` arguments _must_ be at the end of the argument list which means the boolean would need to be the first argument.

We cannot simply change this like so,
```csharp
public sealed class DescAttribute : Attribute
{
	public readonly bool IsUnstable;
	public readonly string[] Lines;
	public DescAttribute(bool isUnstable = false, params string[] lines) { Lines = lines; }
}
```

because a value needs to be given everywhere (the default does us no good here).

```
OpenRA.Game//Traits/World/Shroud.cs(29,9): error CS1503: Argument `#1' cannot convert `string' expression to type `bool'
```

We may be better off implementing this as a separate attribute.

```csharp
[AttributeUsage(AttributeTargets.All)]
public sealed class UnstableAttribute : Attribute
{
	public readonly string Reason;
	public readonly string GitHubTicketUrl;

	public UnstableAttribute(string reason, string gitHubTicketUrl)
	{
		Reason = reason;
		GitHubTicketUrl = gitHubTicketUrl;
	}
}

[Unstable("Math is hard, yo!", "https://github.com/OpenRA/OpenRA/issues/12345")]
public class HealthInfo : ITraitInfo, UsesInit<HealthInit>
{
	// ...
}
```

**Comment by GraionDilach** [comment]
FWIW, i think we can safely add this to the list of issues closed in favor of the new external mod support system/plan.

**Comment by pchote** [comment]
IMO this is an orthogonal issue: mods are no longer *forced* to upstream engine changes if they want to do something new, but it is still the preferred option.

**Comment by pchote** [comment]
> We cannot simply change this like so,

You can add a second explicit constructor that has a bool as the first argument.
I like your idea of linking a github issue (id is enough, don't need the full URL) explaining why the feature is unstable, so I would support having this as a separate attribute.

**Comment by abcdefg30** [comment]
Do we still want this?

**Comment by pchote** [comment]
I still think its a good idea in theory, but in practice I doubt we have the manpower or organizational conventions to actually use it properly.
