### ISSUE TITLE
RA Phase Transport, TD Stealth tank & D2k Stealth Raider don't uncloak on damage

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#12192]
Aside from `Move`, which is obviously intentional, `Damage` is the only trigger not listed in the internal default of `Cloak.UncloakOn`.

`UncloakType.Damage` was most likely ommitted by accident in
https://github.com/OpenRA/OpenRA/commit/f46185b85f458f44f32787f481983d91575d6808
because unlike the other 5 possible triggers, damage was previously hardcoded to trigger an uncloak and did not have a boolean field.

This also means this is a regression and should probably go into stable, as it affects at least 1 unit in each shipping mod + actors collecting stealth crates in TD.

**Comment by GraionDilach** [comment]
Note #12161 which - while isn't in stable itself - will heavily affect this.

**Comment by pchote** [comment]
This isn't a regression: RA/TD/D2K have never uncloaked on damage.  The `UncloakType.Damage` flag was added for TS specifically in #9808.

**Comment by reaperrr** [comment]
Looks like I was too focused on the changes and overlooked [this line](https://github.com/OpenRA/OpenRA/commit/f46185b85f458f44f32787f481983d91575d6808#diff-1971dbf9d98b975ede94b16b1ffd260cL105). 
My bad.

**Comment by reaperrr** [comment]
IIRC, we want at least D2k to stay as true to the original as possible, so we might want to change it at least on the Stealth Raider, Fremen and possibly Saboteur.
