### ISSUE TITLE
[RA] Misplaced ore on Dual Cold Front (both the revised & RAGL02 versions)

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#12199]
Maps:
http://resource.openra.net/maps/14034/
http://resource.openra.net/maps/16089/

Northern gem mine:
![dcf-nw-ore](https://cloud.githubusercontent.com/assets/22008761/19224482/02ee5584-8e55-11e6-943c-2deab8da40b2.png)

Southern gem mine:
![dcf-se-ore](https://cloud.githubusercontent.com/assets/22008761/19224484/1518b2b8-8e55-11e6-9b57-49ab5ca8840d.png)

**Comment by SoScared** [comment]
Wow they just keep popping up :) Well spotted.

I can do the PR - it's originally my own error after all.
