### ISSUE TITLE
Navy AI in RA using aircraft that can't attack air to try to attack air

### ISSUE THREAD

**Issue by Nineeva** [OpenRA/OpenRA#12190]
It seems like in Skirmish mission the Navy AI at least tries to use migs to attack my helicopters which they can't succeeded in doing as they don't have anti-air weapons.  They end up just circling around them and following them, making them very easy to kill.

**Comment by GraionDilach** [comment]
I can see this happening vice versa, AI gathering his stuff under helicopters.

**Comment by abcdefg30** [comment]
See #3468.

**Comment by abcdefg30** [comment]
Closing as duplicate of #3468.
