### ISSUE TITLE
Radar Jammer doesn't deflect V8 missiles

### ISSUE THREAD

**Issue by salsero** [OpenRA/OpenRA#12200]
It seems the radar jammer doesn't work for any kind of missile, i noticed for example the ones launched from the V8 trucks aren't deflected. Is this by design?

**Comment by SoScared** [comment]
I assume you mean V2 trucks? :) Then yes, it's by design.

**Comment by AMHOL** [comment]
That would be funny

**Comment by obrakmann** [comment]
Yes, that's by design, as SoScared explained.
