### ISSUE TITLE
Chinook Transports are unable to remain airborne over open terrain. [Playtest_20161001]

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#12201]
With the removal of "attackmove:" from  the Chinook, it has lost its ability to remain airborne over open terrain.  I think having the ability to remain airborne without hovering over trees/water/debris is a desirable feature.

This affects both TD & RA Chinooks.

**Comment by pchote** [comment]
I'm not sure i'd call this a regression, being able to use attack-move for this was the side-effect of a bug, not a deliberate feature.

Saying that, i'm all for making force-move do this for aircraft.  I had already enabled this for player-controlled carryalls in #11501
