### ISSUE TITLE
Ubuntu: Force move (Alt + right click) only works with "Lock mouse to window"

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#12205]
Mint 18 Xfce 64bit, live session.

Without the "lock mouse to window" the command seems to get totally ignored (no green line move indicator when clicked)

Also it seems that the force move isn't documented anywhere... in wiki or input hotkey settings.

**Comment by obrakmann** [comment]
Your window manager is intercepting the Alt key, OpenRA never sees it.

Try changing it to something else. I had to do the same on Unity/compiz.

**Comment by Mailaender** [comment]
The same is true on KDE 4 with the default settings in window mode. This is unrelated to OpenRA.

> Also it seems that the force move isn't documented anywhere... in wiki or input hotkey settings.

Thanks for letting us know. [Fixed it.](https://github.com/OpenRA/OpenRA/wiki/Hotkeys/_compare/dd8568daa8860f0f3f051a890e8e08516d134c39...acfeffea20c47fdc71dba143011584cdc1919bfb)
