### ISSUE TITLE
D2K - Text notifications

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#12209]
In original D2K there are some red text notifications appear on same place as chat and mission messages(we should go with Mission messages' place on OpenRA, on top.). AFAIK there are only 4, "Airstrike Ready", "Fremen Ready", "Saboteur Ready" and "One of our buildings has been captured"(not sure about exact wording). 

I would prefer having voice notifications but as we don't have sounds for them going with the way that original game would be good.

**Comment by dragunoff** [comment]
@MustaphaTR Should this be added only for missions or as a general notification?

**Comment by MustaphaTR** [comment]
General.
