### ISSUE TITLE
D2k arrakis.yaml tilesets mixed up

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#12202]
Bug description and Fix suggestion.

In an attempt to use OpenRA.Utilities.exe to import mission A1V1 i noticed some misplaced tiles.
Using the correct tileset for this map `BLOXTREE.R8` (phrase "BLOXTREE" found in a original D2k .Sav file of the mission) only some of the misplaced tiles were correct now.

I compared in the map editor with original game "screenshots" and found:
Rock-Detail 94 should be Rotten-Base 251
Rotten Base 250 and 251 together should be Sand-Detail 117

In `arrakis.yaml` (tileset file of d2k) i found the corresponding entries under `ID:94, ID:250, ID:251`
Replacing`Images: BLOXBASE.R8` with `Images: BLOXTREE.R8` fixed the issue. The map is now displayed correctly with no manual edit.
![capture](https://cloud.githubusercontent.com/assets/16046997/19252391/e443b52a-8f44-11e6-9cf0-de329f1d24f3.png)

Is this the right way to do it? I guess one could find the correct frames of  `ID:94 ID:250 ID:251` as an alternative way to fix it.
Maybe someone with insight to the underlying mechanics can deduce a general fix for all tiles/tilesets?

One thing i noticed after the fix: the tiles like       

```
Tiles:
            0: Sand
```

show up in wrong color in the map preview. i think the tiletype would have to be corrected as well...

Cheers,
    SirCake

**Comment by Mailaender** [comment]
I assume it might be better to adjust the legacy map import converter instead of the tileset to stay compatible with the OpenRA d2k maps out in the wild. Otherwise we would need to write a converter to migrate the tile changes.

**Comment by CH4Code** [comment]
I'll look into it which approach is better. Adjustig the coverter means lots of C# ...

**Comment by pchote** [comment]
Note that we semi-intentionally don't support the original tilesets, but instead merge them all into one combined tileset that has all the unique tiles from each.  The converter needs to guess the translation from old &rarr; new tileset, and sometimes gets it wrong.

**Comment by CH4Code** [comment]
Surely you mean there is a mapping (tileset->arrakis) for each tileset defined, right? This, one could change. 
If it is some advanced image processing algorithm ...  :/ well, I'll have to look at it.

**Comment by Mailaender** [comment]
I feel like your are overcomplicating things. Try reading through https://github.com/OpenRA/OpenRA/pull/7135 and https://github.com/OpenRA/OpenRA/issues/4281 to find out how we solved it.

**Comment by CH4Code** [comment]
Hi, 
I think I found a fix! All "misplaced" tiles are actually missing tiles from the arrakis tileset.
By using Tile Attribute Editor from the D2k+ homepage and a lot of comparing using openRA Map editor I could find out the missing tiles/tilecomplexes and added them to the arrakis.yaml.
Now the missions (only BLOXBGBS for now) all are generated without error :):):) very happy about this! :)
I will commit my arrakis.yaml as soon as I have the other tilesets integrated as well. Should be fully backwards compatible since I am not removing any old tiles (though they are mighty wrong sometimes...^^).

**Comment by CH4Code** [comment]
#12244 I fixed it :) Now all 39 mission maps will convert without error!
Also see https://github.com/CH4Code/D2k-Campaign-Resources for the converted maps with gerneric factions (Allowing opening in map editor and test start without crash).
Now only scripting for completion of #9287 remains :)

**Comment by CH4Code** [comment]
Hello, an Update. 
My fix sadly is only temporary, because this should be done: (as discussed with pchote)
1) an openra tileset for each mission tileset (Blox*), which will only be used in the d2k map-importer to map the mission tilesets onto the arrakis.yaml (which is a reduced tileset containing all tiles only once)
2) a proper arrakis tileset without errors
3) a proper map-importer using openra mission tilesets

Maybe someone else wants to continue from here on out.
I put a lot of time into this yaml fix but it seems this has to be redone completely to get rid of annoying duplicates which show up in the map editor tile selection.
