### ISSUE TITLE
[RA] Units attack building under capture by engineer

### ISSUE THREAD

**Issue by whi7ed3vil** [OpenRA/OpenRA#12203]
I don't know where you guys will find this on the micro/macro spectrum, but I'm sick and tired of having to sequester units defending an engineer away from the building he's capturing. Was there any logic in the original game to stave off the attack of nearby units to a building that's currently under capture by an (allied) engineer? If I start a building capture, but my invading force is too strong, I lose out on the ability to take buildings pretty quickly. At least if they don't automatically become aggressive against buildings that are already in capture progress, the game's macro makes sense.... obviously different if I choose to attack the building with direct orders.

**Comment by abcdefg30** [comment]
This is already implemented in the latest release/playtest. See #9854. You just need to tell the units to stop shooting once, then they won't start targeting the actor which is being captured again.
