### ISSUE TITLE
Sequence ZRamp does not behave correctly for sprites that specify frame offsets

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#12229]
Railway tracks don't render properly in the editor sidebar or on the map.  This is probably related to depth metadata.

More specifically, the Z coordinate for sprites assumes that the sprite is centered at the requested position. We need to account for the extra `ZRamp * Offset.Y` term.

**Comment by Mailaender** [comment]
They also don't render in-game anymore.

**Comment by abcdefg30** [comment]
See #12726.

**Comment by Mailaender** [comment]
Current state on the map Cityscape:

![image](https://user-images.githubusercontent.com/756669/34374308-ce7eb14c-eae0-11e7-9e48-54132866c128.png)

**Comment by pchote** [comment]
Reopening as there is more to do here.

**Comment by Mailaender** [comment]
Current state is only these don't get rendered:

![image](https://user-images.githubusercontent.com/756669/71719049-657f6b00-2e1d-11ea-953a-3fc43806f087.png)

**Comment by pchote** [comment]
tib07 frame 1 (corresponding to tiberium density 2) also suffers from this. I bet that this is related to the internal shp y offset not being accounted for when calculating the sequence's base z offset.

**Comment by pchote** [comment]
garadr and naradr might also suffer from this (see #19135).

**Comment by reaperrr** [comment]
I suspect there are more (`gaarty` lower-left edge looks a bit cut off at first glance, too).

**Comment by abcdefg30** [comment]
From Discord:
> https://github.com/pchote/OpenRA/commit/fbed29e19b063e216202a3ff64fff0c65fbff4c7 is the fix, but the problem is that this then breaks all the existing sequences that were tuned around the bug

**Comment by pchote** [comment]
While that does fix the tracks, some of the other depth related issues (e.g. bridge shadows) require a more comprehensive overhaul.

My progress towards this can be found on https://github.com/OpenRA/OpenRA/compare/bleed...pchote:fix-depth-offset, expect this to evolve until such a time that it becomes a PR.
