### ISSUE TITLE
Make dead players specs in an FFA

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#12226]
I'm not sure whether this is exclusive to FFAs or whether it's just when there are no specs in a game, but when players are defeated in an FFA they can only use global chat, spectator chat is not available.

I'm not sure whether this is by design for some reason, but it seems like a reasonable change IMHO.

**Comment by abcdefg30** [comment]
Also see #4772.

**Comment by kyrreso** [comment]
I will promote this, and also ask for it to be put under future. Combined with #13600 this would be awesome improvement. Also have a look at #14996

**Comment by kyrreso** [comment]
Can we please put this in the "future" milestone, since it is wanted by many players..

**Comment by Mailaender** [comment]
The "Future" milestone is more like a graveyard for interesting features. Checkout and review #15615 if you want this in.
