### ISSUE TITLE
Change spy-tag

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#12225]
noticed that the lettering of the "fake buildings" actually fit also on Infantry ... so i suggest we use a tag that actually is readable instead of the "eye?" 
this would actually fit very well , since buildings aswell as infantry can actually be fake ... so the lettering would make it consistent 

![spytag](https://cloud.githubusercontent.com/assets/9139965/19400107/f5a375ea-9254-11e6-9808-c07164b5eee5.png)

**Comment by pchote** [comment]
:+1: the eye has always felt out of place to me.

**Comment by Micr0Bit** [comment]
im struggeling to get a shp out of a single .png ... having to index the picture with the red_alert.act on linux ... if anyone is interested doing this , go ahead and use the graphic i created
![spytag](https://cloud.githubusercontent.com/assets/9139965/19411103/fcf010c8-92fa-11e6-9fe1-08f913124568.png)

**Comment by MustaphaTR** [comment]
Don't we have a text decoration logic, why create an shp?

**Comment by Micr0Bit** [comment]
MustaphaTR : so it fits to the "fake-buildings" tags ... and these are sprites

the current spy-tag is located in mods/ra/bits/ and is called "pip-disguise.shp" ... its animated , and we want to switch it with a single frame instead .. 

this icon need to be adjusted though, since the old one (the eye) did get overlapped by the healthbar ... so i assume this need to be adjusted here : 

 mods/ra/rules/infantry.yaml 
------------------------------------------
Spy:
     WithDecoration@disguise:
		ReferencePoint: Top, Right
                Offset: 4, -2

**Comment by MustaphaTR** [comment]
Looks like WithTextDecoration is only used ny TS mod not RA, so OK, go with shp.
