### ISSUE TITLE
Defeated players in an FFA can pause the game

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#12227]
As with #12226, I'm not sure whether this applies exclusively to defeated players or whether specs can do this too, but earlier I lost in an FFA and accidentally paused the game. It seems wrong that a player that can no longer interact with the gameplay can pause the game.

**Comment by rob-v** [comment]
PR #13050

**Comment by abcdefg30** [comment]
#13050 was merged.
