### ISSUE TITLE
[RA] Nuke Truck ought to burn down trees in range.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#12236]
Title says it all :) Would look really cool, especially if the'd burn them down in progression from ground zero.

**Comment by pchote** [comment]
You just need to add `Trees` to the list of `ValidTargets`, and then add `Incendiary` to the warhead `DamageTypes`.

**Comment by abcdefg30** [comment]
They already ignite trees. I think @SoScared was refering to demo trucks burning trees entirely down?

**Comment by SoScared** [comment]
Yes. Burn'em down! If the effect would burn them down in a progressive manner that would be double plus good.

**Comment by pchote** [comment]
Oh.  We rejected that idea because it will mess with map balancing and expose visual bugs in cases where trees are used to segment the map (instead of water or cliffs) or used to hide tile mismatches.

**Comment by SoScared** [comment]
No I meant just burn em. Not remove them. Now they just catch fire a little and stay unburnt after.

**Comment by pchote** [comment]
Ah, well that brings us back to my original point: the weapon needs to do more damage to trees, which you can do by adding an extra warhead that does large damage to only trees.

**Comment by SoScared** [comment]
I think I can do that.

**Comment by hypercube33** [comment]
This appears to be present and working in the 11/07 Bleeding code - can this be marked closed?

**Comment by abcdefg30** [comment]
It's not exactly the wanted behaviour. At the moment they just ignite.
From https://github.com/OpenRA/OpenRA/issues/12236#issuecomment-255743383:
> No I meant just burn em. Not remove them. Now they just catch fire a little and stay unburnt after.

**Comment by reaperrr** [comment]
Closed via #12467.
