### ISSUE TITLE
[RA] Flamethrowers should explode when killed

### ISSUE THREAD

**Issue by abc013** [OpenRA/OpenRA#12233]
I noticed that in the original game.

**Comment by MustaphaTR** [comment]
Grenadiers are already very useless just because they explode. I don't think we need this on Flamers.

**Comment by abc013** [comment]
@MustaphaTR, you're right, but maybe add a small explosion to the death anim?

**Comment by airetaM** [comment]
I think in original game the exploding damage did not totally kill other units (means a slight damage) wich prevents chain reactions, could be a solution for this.
There should also be a small fire animation for this wich would be really cool for this game.
The grenadiers also had a small fire animation in original game btw
and they are not very useless if you know how to use them, just separate them and they are a really strong unit in early game or for sneaky attacks.

**Comment by klaas1** [comment]
Flamethrowers are pretty well balanced and fun as they are I think. They are usefull, strong, but also easy to counter. Having them explode upon death sounds like a bad idea in that regard.

An explosion animation won't hurt though...

**Comment by 3Lucian** [comment]
could the explosion just be enough to take out a 1/5 or so of the health of another infantry style unit? both visually effective and with a function, but not enough to cause them to be a fragile blob - just an interesting gambit when they are mixed in with other units.

**Comment by abc013** [comment]
Now you can vote [here](http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=299293#299293) about this.

**Comment by abc013** [comment]
![image](https://user-images.githubusercontent.com/21260178/31034123-f5c5667e-a562-11e7-8158-0d7f2f68f2d2.png)

**Comment by reaperrr** [comment]
Going by that voting, the majority wants them to explode (first two options, 23 to 6), but not deal damage (2nd & 3rd option, 17 to 12).
