### ISSUE TITLE
Game crashes immediately, 'System.Reflection.ReflectionTypeLoadException'

### ISSUE THREAD

**Issue by nwvtskiboy** [OpenRA/OpenRA#12239]
Just installed release 20161015 on Windows 7 and it encounters a fatal error and quits upon trying to start.  I updated video driver, restarted system, and tried running as administrator. Several attempts resulted in the same error.

![image](https://cloud.githubusercontent.com/assets/22862191/19414295/02a749b2-9316-11e6-9f62-bb503804cb17.png)

**Comment by cjshmyr** [comment]
OpenRA requires at least version 4.5 of the .NET framework, looks like you are on 4.0. Can grab it [here](https://www.microsoft.com/en-ca/download/details.aspx?id=42642).

**Comment by nwvtskiboy** [comment]
Yup, that fixed it.  Thanks!

**Comment by pchote** [comment]
Strange, I thought the installer was supposed to detect and complain about this?

**Comment by Mailaender** [comment]
Duplicate of https://github.com/OpenRA/OpenRA/issues/13773
