### ISSUE TITLE
Basic Condition System for the Map Editor

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/OpenRA#12230]
Hey, 
the idea is to give the mapers, who are affraid of coding and Lua scripting, some basic editor tool to click-create simple logic conditions for maps.  

Like selecting some pre arranged condition from a dropdown menu.
for example:
- If "atMissionStart" then "give cash" "2500" to "player1". 

Sure, that tool will never be as mighty as scripting directrly with lua. This shall not replace something here. It's more about filling the gabs. 
I'm aware that my suggestion is rly amazing complex and it has to grow slowly to cover all the basic needs (Timers, Counters,.), but it would significantly lower the entry barrier to "maps with logic".
In my opinion it would be nice to see an average mapper being able to create maps with logic.
It also could boost the recreation of the singleplayer campaigns for example. 
Think about it, why aren't they done yet? A big problem is that only a few mapers understand the basics of Lua scripting. The singleplayer campaigns are the ideal testcase for such a map tool.

You can imagine that logic tool like that of SC1. Watch a bit of this here and you should understand what I'm talking about: https://www.youtube.com/watch?v=kDx4CWotPKA

**Comment by pchote** [comment]
I'm going to close this one as a wontfix.  As nice as this would be, we don't even have the man power to maintain the Lua API.  Building a significantly more complex option as an alternative simply isn't going to happen.

**Comment by TheRaffy** [comment]
You are right!
