### ISSUE TITLE
selecting and directing multiple mvcs

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#12247]
i built 4 mvcs and selected them one by one sending them to different locations wide across the map. when i pointed the 4th i realized that all 4 mvcs were headed to the 4th location.
seems mvcs aren't unselected like before when a next one is selected?
perhaps the same with other units, but didn't notice it there.

not sure what i observed, but it works different.

happened multiple times during the same game. also with already 2 mvcs etc.

**Comment by pchote** [comment]
Are you sure you aren't double or triple clicking on an MCV? That is a shortcut to select all on screen / all on map.

**Comment by anvilvapre** [comment]
that must have been it. different from the last version? never had it before. ill close this.

**Comment by GraionDilach** [comment]
You should check your mouse. My previous mouse tended to occasionally doubleclick when clicked-once after a while as a sign of getting weary.

**Comment by anvilvapre** [comment]
my middle mouse button died. i enabled emulate3buttons. 
i also think i may have the habit of making sure i selected the right unit by clicking it more often then needed - in the process of clicking many things all the time. taught myself as it was needed somehow. 

i tried to see if i could disable the select-all mouse click. but didn't see it in the input dialog list. the select all might be useful, i'll try to adjust.

this version plays different in many ways, attacks, how long units last against others. harvesters that because they are smarter in looking for ore will nicely drive into the base of the opponent where a tesla kills them off one by one. seems you should never have more harvesters than that there is ore, as all other harvesters get lost anyway.
