### ISSUE TITLE
Cursor color does not change when using A+right click with Tanya

### ISSUE THREAD

**Issue by bagage** [OpenRA/OpenRA#12250]
I'm testing the game, playing the third mission (Dead end 1) and discovered the nice shortcut "Move + Fire" `A+Right click`. When typing `A` the cursor is expected to move from green to red but it does not work on my side for **Tanya only** (while it works for a friend of mine!):

1. If Tanya alone is selected, when typing `A` nothing happens (cursor remains green). If I still right click, she does not fire on ennemies.
2. If selecting Artillery tank, when typing `A` cursor goes red and it fire on ennemies as expected.
3. If I select Tanya and Artillery, when typing `A` cursor goes red, Artillery fires on ennemies but not Tanya.

I have tested release-20161015 on both [Windows 8.1](https://github.com/OpenRA/OpenRA/releases/download/release-20161015/OpenRA-release-20161015.exe) and [Debian](https://github.com/OpenRA/OpenRA/releases/download/release-20161015/openra_release.20161015_all.deb).

No GPU here (integrated intel HD4000).
Any idea?

**Comment by pchote** [comment]
When you first start the mission a dialogue from tanya is written to the screen:
> According to the rules of engagement I need your explicit orders to fire, Commander!

The attack-move behaviour is disabled for tanya on the default difficulty for these missions because it otherwise makes them far too easy.

**Comment by bagage** [comment]
Ooooooops! My bad, I was feeling strong and wanted to increase difficulty but I did not catch the dialogue. Shame on me @pchote and thanks a lot!
