### ISSUE TITLE
Windows installer .NET 4.5 detection doesn't seem to work

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#12256]
I've seen more than one report of crashes on XP and other windows with only .NET 4.0.  The installer should be preventing these people from installing the new version in the first place.

**Comment by Mailaender** [comment]
Well, we ask politely to please install .NET 4.5, which you can cancel or just ignore to read. I would like to have a confirmation that the detection is flawed on Windows XP and 7 starter before making any claims.

**Comment by pchote** [comment]
We probably want to change the warning to an error for at least Windows XP, since we know for a solid fact that it won't run there.

**Comment by Mailaender** [comment]
An easier and more immediate fix would be to update http://www.openra.net/download/ with notice.

**Comment by pchote** [comment]
Another example from the website comments:
![screen shot 2016-10-19 at 19 54 27](https://cloud.githubusercontent.com/assets/167819/19533008/eee147ac-9635-11e6-8e24-360651ea62b3.png)

**Comment by Mailaender** [comment]
http://www.openra.net/news/release-20161015/#comment-2958767059 apparently a double post.

**Comment by Mailaender** [comment]
[Updated the FAQ](https://github.com/OpenRA/OpenRA/wiki/FAQ/_compare/07f2ef33e147d787b3948bfe9d92a2188f0a6ec6...87a8e69460e120c87540274745d49b3de90b5063).

**Comment by pchote** [comment]
Another example:
```
19:03 < Assist> how are you? I have a problem running openra
...
19:04 < Assist> windows 7. its only with the new release. the old releases works perfectly fine
...
19:14 <+pchote> Assist: did you click through a warning dialog when you started the new version installer?
19:14 <+pchote> about your .net version
19:14 < Assist> yes
19:15 <+pchote> well that's why then!
19:15 <+pchote> the warning was there for a reason :)
19:15 < Assist> but its either yes or no
19:16 <+pchote> if you install .net 4.5 it will work again
```

**Comment by Mailaender** [comment]
Hmm, I thought it is rude to enforce the installation, but I guess Steam does it for a reason to relieve the customer support from these repetitive enquirers.

**Comment by Phrohdoh** [comment]
IMO it only makes sense to disallow installation if the user has explicitly chosen to not install a hard dependency.
