### ISSUE TITLE
Nickname resets to default

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#12259]
(Release-20161015)
In skirmish lobby (RA, I didn't test multiplayer lobby or other mods) player's nickname is always reset to the default one (the one in the setting)
- when you start a game
- when you alter other player slots

**Comment by yokaiboy** [comment]
did you confirm the change by pressing enter?

**Comment by pi99y** [comment]
@yokaiboy Pressing Enter indeed solves the case ..but it's not very intuitive so I wouldn't mark this as fixed.

**Comment by rob-v** [comment]
#5802

**Comment by obrakmann** [comment]
Closing as duplicate
