### ISSUE TITLE
Out of sync game on current release (20161015)

### ISSUE THREAD

**Issue by paulvt** [OpenRA/OpenRA#12253]
The exception log:

```
Red Alert Mod at Version release-20161015
on map 1eea52d14b025381c96a1e87c585748e375b1bfe (Arctic shelf by Aneyrin).
Date: 2016-10-17 21:58:48Z
Operating System: Linux (Unix 4.7.0.1)
Runtime Version: Mono 4.6.1 (Debian 4.6.1.3+dfsg-4) CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Out of sync in frame 8511.
 Compare syncreport.log with other players.
  at OpenRA.Network.OrderManager.OutOfSync (System.Int32 frame) [0x00038] in <e8e2e8fbcf8043d0bde34796e2e884f1>:0 
  at OpenRA.Network.OrderManager.CheckSync (System.Byte[] packet) [0x00046] in <e8e2e8fbcf8043d0bde34796e2e884f1>:0 
  at OpenRA.Network.OrderManager+<TickImmediate>c__AnonStorey0.<>m__0 (System.Int32 clientId, System.Byte[] packet) [0x00049] in <e8e2e8fbcf8043d0bde34796e2e884f1>:0 
  ...
```

I have attached some syncreports that I gathered.

[syncreport-2016-10-17T215846Z.log.txt](https://github.com/OpenRA/OpenRA/files/534794/syncreport-2016-10-17T215846Z.log.txt)
[syncreport-2016-10-17T215847Z.log.txt](https://github.com/OpenRA/OpenRA/files/534795/syncreport-2016-10-17T215847Z.log.txt)
[syncreport_AMHOL.log.txt](https://github.com/OpenRA/OpenRA/files/534797/syncreport_AMHOL.log.txt)
[syncreport_kyrylo.log.txt](https://github.com/OpenRA/OpenRA/files/534796/syncreport_kyrylo.log.txt)

**Comment by paulvt** [comment]
More logs...
[syncreport-2016-10-17T215837Z kazu.log.txt](https://github.com/OpenRA/OpenRA/files/534811/syncreport-2016-10-17T215837Z.kazu.log.txt)
[syncreport-2016-10-17T215846Z_jazz.log.txt](https://github.com/OpenRA/OpenRA/files/534812/syncreport-2016-10-17T215846Z_jazz.log.txt)

**Comment by paulvt** [comment]
Moar...
[syncreport-2016-10-17T215847Z_Ugly.log.txt](https://github.com/OpenRA/OpenRA/files/534835/syncreport-2016-10-17T215847Z_Ugly.log.txt)

**Comment by paulvt** [comment]
Remaining logs we need are from: Hi, Teew, Kizomba is fail, OMnom, wee man, and Yellow.

**Comment by TheRaffy** [comment]
yellow:
[syncreport-2016-10-17T215409Z_log.txt](https://github.com/OpenRA/OpenRA/files/536122/syncreport-2016-10-17T215409Z_log.txt)

**Comment by pchote** [comment]
Note that spectators can desync the game too, so we need potentially all 14 syncreports from this game.  So far all of the posted logs match, so it was one of the other players or spectators who desynced.

**Comment by pchote** [comment]
Can somebody please also post the replay from this game?

**Comment by paulvt** [comment]
The list I provided above are all the syncreports that remain to be hunted down. I am on it, but it will take some time!
For now, here is the replay:
[OpenRA-2016-10-17T213903Z.orarep.txt](https://github.com/OpenRA/OpenRA/files/536164/OpenRA-2016-10-17T213903Z.orarep.txt)

**Comment by pchote** [comment]
For completeness, we have:
- [x] Blue
- [x] jaZz_KCS
- [x] kazu.
- [x] kyrylo
- [x] Moz
- [x] SRUNKsCAoScKared
- [x] Ugly
- [x] Yellow
- [ ] Hi
- [ ] OMnom
- [ ] Teew
- [ ] Kizomba is fail
- [ ] wee man

**Comment by pchote** [comment]
I tracked down Teew, who was our desyncer.  He has mentioned that many of his games are crashing, which suggests a runtime level issue affecting him specifically:

```diff
-Player: Teew (Windows Microsoft Windows NT 6.2.9200.0 .NET CLR 4.0.30319.42000)
+Player: jaZz_KCS (Windows Microsoft Windows NT 6.1.7601 Service Pack 1 .NET CLR 4.0.30319.42000)
 Game ID: 0a05e2cd-8206-4e48-a61a-713710fa0f7c (Mod: Red Alert at Version release-20161015)
 Sync for net frame 8511 -------------
 SharedRandom: 1791148093 (#805374)
@@ -13262,9 +13262,9 @@
 		 QuantizedFacings: 8
 	 1574 e3 Kizomba is fail Health (20)
 		 hp: 20
-	 1574 e3 Kizomba is fail Mobile (58360)
-		 PathHash: 1848
-		 Facing: 192
+	 1574 e3 Kizomba is fail Mobile (58802)
+		 PathHash: 354
+		 Facing: 208
 		 CenterPosition: 64000,7680,0
 		 FromCell: 62,7
 		 ToCell: 62,7
@@ -13284,13 +13284,13 @@
 		 IsTraitDisabled: True
 	 1574 e3 Kizomba is fail WithParachute (1)
 		 IsTraitDisabled: True
-	 1574 e3 Kizomba is fail TakeCover (154)
+	 1574 e3 Kizomba is fail TakeCover (138)
 		 remainingProneTime: 90
 		 QuantizedFacings: 0
-		 TurretFacing: 192
-	 1574 e3 Kizomba is fail AutoTarget (108855298)
+		 TurretFacing: 208
+	 1574 e3 Kizomba is fail AutoTarget (82575362)
 		 nextScanTime: 2
-		 TargetedActor: ftrk 1661 (not in world)
+		 TargetedActor: proc 1260
 		 IsTraitDisabled: False
 	 1575 mcv Hi DamageMultiplier (1)
 		 IsTraitDisabled: True
```

**Comment by pchote** [comment]
> TargetedActor: ftrk 1661 (not in world)

This looks dodgy.  AutoTarget shouldn't be picking dead actors to target.

**Comment by pchote** [comment]
Teew's replay desyncs when observed with the generic observer view, but runs to completion if observed from his view.  This suggests that we now have everything we need to debug the desync.

**Comment by pchote** [comment]
Confirmed that `AutoTarget.ChooseTarget` is behaving different depending on the player view:
```diff
--- choosetarget_teewvis.log	2016-10-18 17:58:38.000000000 +0100
+++ choosetarget_observervis.log	2016-10-18 18:10:02.000000000 +0100
@@ -3728,4 +3728,7 @@
 25525 e3 1592 ftrk 1661
 25527 e1 1593 ftrk 1661
 25527 arty 1609 ftrk 1661
-25540 e3 1639 yak 1559
+25530 e3 1574 proc 1260
+25532 e3 1518 proc 1260
+25532 e3 1548 proc 1260
+25532 e3 1592 proc 1260
```

**Comment by pchote** [comment]
The desync is caused by the `CanTargetActor` check at https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/AutoTarget.cs#L202, which returns false for Teew at tick 23330 for `e3 1574` vs `proc 1260`.

**Comment by TheRaffy** [comment]
good catch

**Comment by Mailaender** [comment]
Impressive investigation!

**Comment by jvdgroup** [comment]
Same problem here. Exception log:

```
Red Alert Mod at Version release-20161015
on map be29c5181870e7f081ae32cd92e030dd202dd4bd (Ahti III by Jopani Kansaro).
Date: 2016-10-18 14:17:56Z
Operating System: OSX (Unix 15.6.0.0)
Runtime Version: Mono 3.12.0 ((detached/a813491) CLR 4.0.30319.17020
Exception of type `System.InvalidOperationException`: Out of sync in frame 11465.
 Compare syncreport.log with other players.
  at OpenRA.Network.OrderManager.OutOfSync (Int32 frame) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.OrderManager.CheckSync (System.Byte[] packet) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.OrderManager+<TickImmediate>c__AnonStorey0.<>m__0 (Int32 clientId, System.Byte[] packet) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.EchoConnection.Receive (System.Action`2 packetFn) [0x00000] in <filename unknown>:0 
  at OpenRA.Network.OrderManager.TickImmediate () [0x00000] in <filename unknown>:0 
  at OpenRA.Sync+<CheckSyncUnchanged>c__AnonStorey0.<>m__0 () [0x00000] in <filename unknown>:0 
  at OpenRA.Sync.CheckSyncUnchanged[Boolean] (OpenRA.World world, System.Func`1 fn) [0x00000] in <filename unknown>:0 
  at OpenRA.Sync.CheckSyncUnchanged (OpenRA.World world, System.Action fn) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00000] in <filename unknown>:0 
  at OpenRA.Game.LogicTick () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Loop () [0x00000] in <filename unknown>:0 
  at OpenRA.Game.Run () [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Run (System.String[] args) [0x00000] in <filename unknown>:0 
  at OpenRA.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0 
```

Find attached syncreports from all 4 players involved.

[syncreport-2016-10-18T141756Z 2.log.txt](https://github.com/OpenRA/OpenRA/files/537168/syncreport-2016-10-18T141756Z.2.log.txt)
[syncreport-2016-10-18T141756Z 3.log.txt](https://github.com/OpenRA/OpenRA/files/537165/syncreport-2016-10-18T141756Z.3.log.txt)
[syncreport-2016-10-18T141756Z.log.txt](https://github.com/OpenRA/OpenRA/files/537166/syncreport-2016-10-18T141756Z.log.txt)
[syncreport-2016-10-18T141757Z.log.txt](https://github.com/OpenRA/OpenRA/files/537167/syncreport-2016-10-18T141757Z.log.txt)

**Comment by AoAGeneral** [comment]
Sync file for Kizomba is fail

https://www.dropbox.com/s/xq169hszd2iuqti/syncreport-2016-10-17T215848ZKizomba-is-fail.log?dl=0

**Comment by Omnomon** [comment]
Hi

Sorry, I don't really check the forums...i thought these files were uploaded automatically. 

[syncreport-2016-10-17T215850Z.txt](https://github.com/OpenRA/OpenRA/files/537478/syncreport-2016-10-17T215850Z.txt)
