### ISSUE TITLE
localised moves is play with unsinchronisation of audio and video

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#12255]
Tested in RA and TD.
Audio stream is playing with normal speed.
But Video stream have a lower speed than audio stream.
How can I fix this?

**Comment by pchote** [comment]
We don't support any support for non-english assets.  Once #10475 is completed we will be able to support the different localizations and let players switch between them in the mod chooser.

**Comment by abcdefg30** [comment]
Closing as covered by #10475.
