### ISSUE TITLE
Hijacker vs apc -> recolored units

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/OpenRA#12266]
release-20161019
just rename that txt file extension to only orarep
[Hijaker bug.orarep.txt](https://github.com/OpenRA/OpenRA/files/540418/Hijaker.bug.orarep.txt)

You will see a hijacker running in a apec. the result was surprisingly funny. I got his units in the color of my opponent,

**Comment by Nineeva** [comment]
Just tested this, got the same result, was quite funny!
