### ISSUE TITLE
Crash when another player joins a server lobby as a game is starting.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#12271]
Reported in the ingame IRC channel:

```
04:40 < pchote> what were you doing when it crashed?
04:40 < OMnom> besides clicking the start button?
04:41 < pchote> ah, so this happened when starting a game from the lobby?
04:41 < OMnom> yeah i was in teh lobby, i pressed ready, game crashed
04:41 < OMnom> i did see that someone snuck into the game, and then the game started immediately afterwards
```

```
Red Alert Mod at Version release-20161019
on map 5f58c7df7d0c9f3650a204a31a2243c85c2b8971 (Northwest Passage by Raymundo).
Date: 2016-10-21 03:32:59Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Widgets.ScrollPanelWidget.<BindingRefresh>m__1()
   at OpenRA.Primitives.ActionQueue.PerformActions(Int64 currentTime)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)
```

**Comment by pchote** [comment]
On closer inspection, the global chat is the only thing in the lobby that uses the binding logic.

**Comment by abcdefg30** [comment]
I was never able to reproduce this reliably, but it also happened in singleplayer for me.

**Comment by cjshmyr** [comment]
Reproducible in skirmish by leaving global lobby and starting a game in quick succession.

**Comment by pchote** [comment]
The problem here is a "race condition" between unbinding the scroll panel during UI disposal and a message being received by the IRC client.  It's not a real race condition because it is caused by our frame end tasks rather than thread safety issues.

I tied myself in a knot trying to outline the exact code flow that triggers this... the key points are that:
* `ScrollPanelWidget.Bind(null, null, null, false)` runs first, queuing a frame end task to tear down the state but doing nothing immediately.
* `ScrollPanelWidget.BindingAdd` or `ScrollPanelWidget.BindingRefresh` run next, queuing their own frame end tasks to update the scroll panel contents
* The (un)binding task runs, removing the bindings and setting `collection` to null.
* The refresh task runs and explodes because the state it assumed to be sane has been destroyed.

Specifically, [ScrollPanelWidget.cs#L441](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Widgets/ScrollPanelWidget.cs#L441) is running with `collection == null` and exploding.

I suspect that the best fix here will be to add `collection` arguments to the `ScrollPanelWidget.Binding*` methods, and then check that `this.collection == collection` at the start of the frame end tasks that they queue.  If they don't match then someone has changes the bindings out from under them and they should immediately return.
