### ISSUE TITLE
Any tank type can be loaded into ANY transportation unit by using a trick

### ISSUE THREAD

**Issue by runeavalon** [OpenRA/OpenRA#12273]
I found out that you can load ANY tank type into choppers, Phase tanks, APC's, rangers, just by using a simple trick. Normally you should only be able to do this in a naval transport, But i found out that by selecting an over-amount of units that the transports u have at the shoreline which the naval transports can hol, using the Alt-shift combination on 2 naval transports(so thats 10 tanks of any kind, And besides that you can remove the second naval transport before units reach them to load themselves in), In combination with ANY other transport unit like a chopper, phase transport, apc, or a ranger, setup close to the same shoreline will make the tankgroup which is left after the naval transport is fully loaded, load into the other transport units that are placed close to the same shoreline. I tested this over and over in single player and multiplayer. And it works. You can basicly make a chinook drop with 16 artilleries behind the enemy base without any trouble. which is much faster and than a chronoshift, and lasts indefinately. and the amount can be stacked as high as you want to. I really think this is a bug that needs to be fixed. Waiting for a response, And before that, CHEERS!!! :D Ohmk Torque (ingame player name)

**Comment by Micr0Bit** [comment]
This is what he means : 

1. build a transporter and a chinook
2. put them parallel on a shore 
3. alt-move "whatever" units you have into the transporter (should be more then 5)
4. once the transporter is filled and there is still units , the chinook gets loaded

**Comment by Micr0Bit** [comment]
This is what he means :

1.   build a transporter and a chinook
2.   put them parallel on a shore
3.   alt-move "whatever" units you have into the transporter (should be more then 5)
4.   once the transporter is filled and there is still units , the chinook gets loaded

**Comment by runeavalon** [comment]
yes that is what i mean. Exept that it also works on any other transport vehicle, so phase transporters, apc's rangers. so for example, you can load 5 mammoth's into an apc, then load 8 of thos apc's filled with 5 mammoth's into a chinook. that would mean that you can load 40 mammoth tanks into 1 chinook. Or any other combination that you can think of. Cheers, Ohmk Torque
