### ISSUE TITLE
RA - Make Radar Dome lose Stealth Detection ability if Powered Down/on Low Power

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#12272]
Was watching FiveAces' video and as a comment at here says, i agree that it doesn't make any sense that Stealth Detection ability of Radar still work if it is Powered Down. Also doing this would make players another reason to not Power Down the Radar.

https://www.youtube.com/watch?v=oPJvGgy-ZHs&t=1529s

Also maybe same should go for Defences.

**Comment by Phrohdoh** [comment]
@EspressoDan is taking a stab at this.

**Comment by MustaphaTR** [comment]
I think this is now possible thanks to this: https://github.com/OpenRA/OpenRA/commit/1f44e9174689c32736d7cb4749c50ea22f2df3e0
(Couldn't find the PR)

**Comment by pchote** [comment]
@MustaphaTR you're right, this can now be done with one line of yaml (adding `RequiresCondition: !disabled` to `DetectCloaked`).  Github lists the PR associated with a commit just below the commit message.

**Comment by MustaphaTR** [comment]
Fixed by #13790.
