### ISSUE TITLE
Using MAD tank makes the game crash

### ISSUE THREAD

**Issue by Afijak** [OpenRA/OpenRA#12279]
As is in the title.
Version 19.10.16.
Mod is RED ALERT.
The exception log is as follows:
```
Red Alert Mod at Version release-20161019
on map 0eaed2c6d18b4760593b77346edbaddef638dc18 (Barracuda by PizzaAtomica).
Date: 2016-10-22 00:04:34Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.18331
Exception of type `System.IO.InvalidDataException`: madchrg2.aud is not a valid sound file!
   в OpenRA.Sound.LoadSound(ISoundLoader[] loaders, IReadOnlyFileSystem fileSystem, String filename)
   в OpenRA.Sound.<Initialize>c__AnonStorey0.<>m__0(String s)
   в OpenRA.Exts.GetOrAdd[K,V](Dictionary`2 d, K k, Func`2 createFn)
   в OpenRA.Primitives.Cache`2.get_Item(T key)
   в OpenRA.Sound.Play(Player player, String name, Boolean headRelative, WPos pos, Single volumeModifier, Boolean loop)
   в OpenRA.Sound.Play(String name, WPos pos)
   в OpenRA.Mods.RA.Traits.MadTank.<StartDetonationSequence>m__2()
   в OpenRA.Activities.CallFunc.Tick(Actor self)
   в OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act)
   в OpenRA.Actor.Tick()
   в OpenRA.World.Tick()
   в OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   в OpenRA.Game.LogicTick()
   в OpenRA.Game.Loop()
   в OpenRA.Game.Run()
   в OpenRA.Program.Run(String[] args)
   в OpenRA.Program.Main(String[] args)
```

**Comment by pchote** [comment]
What method did you use to install the game assets?

**Comment by Afijak** [comment]
I installed OpenRA distrib from the RA site and used the original distribs + addons for music and brifings...

**Comment by pchote** [comment]
Did you use the original RA95 + aftermath discs, TFD, or Origin?

**Comment by Afijak** [comment]
original RA95 + aftermath discs...
And all the content from those disks - so I did not downloaded anything from the sitem only from discs

**Comment by Afijak** [comment]
now trying to download base game files from site and will look...

**Comment by Afijak** [comment]
So must assume the following:
Downloaded base game files and base game music via the OpenRA program (did not install additional music and briefings) - and the MAD tank is OK now...
But I want to install all the staff from discs... here is the problem.

**Comment by pchote** [comment]
It looks like there is an issue with the files extracted from the aftermath disc.  For now you should be fine with extracting everything except the aftermath files from the original discs (or if you have access to them extracting everything from TFD or Origin).

**Comment by Afijak** [comment]
ok, thanks

**Comment by abcdefg30** [comment]
Checking if the assets are valid is covered by #12807, so closing here.
