### ISSUE TITLE
Rebinding Fn keys no longer works in TD

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#12280]
I rebind my Fn keys to production tabs for placing buildings, i.e. F1 for Norman building structs, F2 for defence structs, this no longer works in TD, F1 builds the item on slot 0 of the active menu etc. I am drunk and just remembered this, sorry if this issue makes no sense

**Comment by rob-v** [comment]
@AMHOL Can you reproduce it?
I propose to close this issue, according to my test (switched F1 - E keys) it works properly.

**Comment by AMHOL** [comment]
@rob-v sorry I think the problem was between the chair and the keyboard with this one.
