### ISSUE TITLE
Suggestion: Remove Map "Blody Delta" from official maps (RA) 

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/OpenRA#12282]
I talked to some pro players and they all confirmed that this map doesn't satisfies the standard map quality anymore.

**Comment by kruug** [comment]
While this map is unbalanced for competitive play, not all players of OpenRA play it competitively. Please restore the map for posterity.

**Comment by abcdefg30** [comment]
It is still available on the RC, so you can download it and update it to fit the newest OpenRA version: https://resource.openra.net/maps/28393/
