### ISSUE TITLE
Selecting issues

### ISSUE THREAD

**Issue by salsero** [OpenRA/OpenRA#12286]
With the newest release, i have unit selection issues, sometimes, it doesn’t work in the way that nothing gets selected.
I am using kubuntu 16.04

**Comment by abcdefg30** [comment]
Related to #12118?

**Comment by salsero** [comment]
No, also happens with ground units only. I think it happens when the selection square has to cover fog or shroud.

**Comment by Micr0Bit** [comment]
could be #11099 ?

**Comment by salsero** [comment]
This lastest release, i installed it on top of the previous, recently i removed everything and installed the release again and i think the issue got solved; give me a few more days.

**Comment by atlimit8** [comment]
@salsero is it fixed.

**Comment by pchote** [comment]
There's not enough info to go on here, so closing.  Please file a new issue if this is still a problem.
