### ISSUE TITLE
Add Mute Button to lobby

### ISSUE THREAD

**Issue by Truth99A** [OpenRA/OpenRA#12299]
In the music tab, add a mute button that mutes all sound, this would get rid of the sound of the units in the background that get annoying when trying to listen to music in the lobby
(I understand that you can mute by going into the settings tab in the main menu but you'd have to leave the lobby in order to do that)

**Comment by pchote** [comment]
My preference would be to mute the shellmap completely, for all mods.

**Comment by Truth99A** [comment]
I'll admit it's cool the first time but there really should be an option to mute the shellmap
