### ISSUE TITLE
help to repair and script the map i made

### ISSUE THREAD

**Issue by runeavalon** [OpenRA/OpenRA#12304]
I made a map with a lot of effort. Took me a coule of months to create it so that it is as beatufull as possible, that it is balanced for both teams qua ore placement and such. But the idea of the map is to make a map that looks like the standard map of league of legends but then in red alert. I have a lot of requests for scripting and i would like to get help with that as i am not able to do the scripting. if this is not possible (when i can get contact with somewone willing to do this for me) then my request is just to repair the map and upload it without the scripting, aswell as some coorperation in taking a look at the map for improvements. Plzz let me know if there is someone willing to do this and give me an email so i can send it to you. The map that i have on my pc crashes now all the time i try to loadit even in skirmisch mode. So i think that has to do with some updates that came in later on. Besides that a guy named zjordy tried to script it and uplaod it but he did a terrible job at it. and uploaded the map while its completely wrongly scripted, it crashes, and he quited half way the attempt to finish it. The map name is Summoners rift. the same name of the map in league of legends.  (so maybe you  can find it allready online, but that is the uploaded version with the crappy scripting of zjordy. Sorry if i insult zjordy with this. that is not my intention. I just want to finish this map on which i put so much effor in to make it). TIf there is someone willing to help me with this i will send my requests for scripting through email. and ofcource the map that i have on my pc. Forward thatns for the one, if there is someone, willing to help me with this. Sorry for the long story. i just took my medication and im kinda buzzed out :/ anyway i hope to get a reaction soon

cheers Leander Letwory (gamename Ohmk Torque

**Comment by runeavalon** [comment]
btw my email adress is runeavalon@gmail.com. So anyone willing to help me with this can contact me there. Greetings Ohmk Torque

**Comment by airetaM** [comment]
You have some Actors inside this map wich is not listed in the rules.
Actor4170: gap2
maybe it should be  gapz ?
There are not so many errors you can click on the red fail in resource center to see the errors
Or just open the exception.log after your map crashed

**Comment by runeavalon** [comment]
ok, ty. but i have absolutely zero understanding of programming or scripting. i actually just play the game and made 1 map, and put a lot of effort in it. so actually my question is if someone could do that for me, if someone is willing to do that. its a really nice map. i think its worth it. also ofcource i will take a look at the things you describe. but i bet my chances of repairing something are very slim. besides that. i gave zjordy a whole list of things i would like to have scripted so it would be a really big change of play style of red alert which i think would be very interresting so..... i feel a bit tiied with my hands on my back with this. but i will take a look at all what you are advising ty though
cheers Ohmk Torque

**Comment by CH4Code** [comment]
Hi Torque,

i took a look at your map and unbugged it, so it can be edited in the map editor again and be played (in theory).[Map on resource center](http://resource.openra.net/maps/17561/).
I wanted to help you with this because its a huuuge map, and im sure it took you lots and lots of time to tile this. However, i disagree with your treatment of Zjordy, who put HIS time forward to help YOU. You should be more grateful, even if he did not acieve your vision. Map scripting isn't easy.

Anyway - how is this map supposed to work?
(1) How are players supposed to harvest ore? They dont have ore on their home isle and can't build refs on either isles, bottom/top and left/right. Only way would be to ferry harvesters, which isn't fun - at all. And on the left/right they can only harvest by passsing bridges, which is super prone to harvesters getting stuck and painstakingly slow harvesting. You'll have to make changes here(more room for bases)!
(2) Balance: most oil derricks can't be reached by soviet (no air transport)
(3) there are lots of trees in the water, is this intentional?

Please explain in less than 3 sentences how your map is supposed to work. And please don't use references to LoL as i'm no LoL player. Then, if it is possible, I might help you with scripting this.

Cheers, SirCake

**Comment by runeavalon** [comment]
wow sir cake, ty very much. I didnt expect any response anymore. anyway.
about your question. i edited the map so that everywhere where there is a
river, u can pass it either by boats AND with land units, so expansion is
no problemo. i filtered out all river possibilities out where you can do
that and implemented them in the map. now that you fixed it i would love to
have the map send back to my email adress which is (runeavalon@gmail.com).
I worked 6 months on this map to make it work like this. But the final goal
of the map is to make it so that its as similar as possible to the main map
of league of legends. I took the map of that game, made a screen shot of
it, and copied all obstacles and pathways on the main land, and made it
simetrical for both top team and bottem team. And calculated the amount of
ore and travel time towards the ore from the main islands so that it is
equal for both teams.

Now to make it as similar as possible i really need someone who can do
scripting. i hope you can and are up for the task. Maybe you know the game
league of legends and its main map "summoner's rift". And the playstyle of
it. Else maybe you can take a look at youtube movies. There you can see
that there are 3 main "lanes" on which they fight. Each of them has a
certain "team" from which the outer lanes consist mostly of 2 members the
most right land usually is taken by 1 player and ends up in a 1 vs 1. mid
lane is allways 1 vs 1. and the 5th usually can either choose to take part
of the leftmost lane OR go in the jungle, where there are "jungle creeps"
which you can kill and get money from. And bigger jungle creeps from which
you can get a bonus from.

so to make it as similar as possible i added the turrets at the right spot
which should start as an ally of those who belong to that particular lane.
In the jungle i cant remember what exactly i changed and which version of
the map you repaired. But i do know that i finished the path way right
through the middle. In the real summoner's rift map of league of legends
that a river which you can walk through. I made it so that it looks a bit
like that. And i know that i placed a service depot on the 2 spots where
there should be a dragon in the original which gives you a sort of ultimate
bonus. i put a mammoth tank on the service depot which should be edited so
that its extreeeeeeeemely powerfull in terms of attack rate and dmg and
health. becouse in the original you can only defeat that dragon if you
attack it with your whole team after your whole team is leveled up to a way
stronger level than which they are starting at. in the Original summoner's
rift you have places where there is grass in which you can hide so that the
enemy can't see you. So i placed on all of those spots a gapgenerator which
you can take over by engineer. i also placed other neutral buildings in the
map. And the idea is that the turrets can be destroyed but they have to be
made way stronger, so that they can hold off an entire army. the
gapgenerators should be indestructable, so that they can be taken over
again and again by either of the teams. then another thing that should be
changed is the other lesser bonus places. I was thinking about placing a
barrack there which can only build very strong units like upgraded zombies
or ants. But u should only be given acces to it when you killed a couple of
neutral creeps, and as soon as they are destroyed you should only be given
a limited time to build those upgraded units from the barrack behind it.
After that the creeps should return and you can do it again but only if you
killed the creeps protecting it again. So building a base surrounding those
places should be made impossible becouse red alert is a way different game
then league of legends xD. Then there is a concept in the game that from
out the main base in league of legends creeps are released in intervals of
a sertain time period. Which follow the 3 lanes implemented in the map
which are allies of your team. The enemy team can kill tho's for money.
They meet the enemy creeps in the middle if you dont intervene with them
and they stay there to fight eachother. but the goal is to get to the enemy
base through all turrets and base defences and kill the enemy base core in
the original. Now i dont know if such a thing can be edited in the script
so just killing all enemy opposition could also work and be fun. Since its
red alert and not league of legends you can build boats, so therefore i
added a whole sea surrounding the level. and those boats are able to
penetrate in the middle of the enemy base becouse of the fact that i made
the rivers so that you can either pass them by boat AND land units. so i
added also a couple of neutral creeps on the water which should simulate
pirate boats. All neutrall creeps in the entire level should attack
anything from any team at sight.

So the question is which version of the map i made did you repair? Is there
anything of the discribed above that i should change, becouse you maybe
have an older map version? and what are your capabilities of
editing/scripting of all things i discribed above. I hope you can help me
with all the scripting part of the job. but you might want to give me the
repared map you have back to me on my email, as said above(
runeavalon@gmail.com ). Also if you can give me your email adress i can
send it back to you as soon as all the base-objects are corrected again and
checked, so that you can do the scripting of all things allready there in
the map maybe.

I think i leave it to this first becouse i notice this email has becoume
very long allready :/. i hope to hear a response from you soon. And thanks
again for repairing the map.

Cheers back to you, Leander Letwory (Ohmk Torque)

2016-12-12 15:46 GMT+01:00 CH4Code <notifications@github.com>:

**Comment by runeavalon** [comment]
oh crap. it seems that i didnt read the 3 sentences and references to LoL
part. :S. sorry for that. i also will change the other things like oil
derrecks cant be reached by soviets. And more room for base building. I
think you have an older version of the map i see, becouse i did change the
room for base building. This time 5 sentences, I hope you dont mind my long
message before this one, becouse its a big projects


2016-12-12 21:34 GMT+01:00 Leander Letwory <runeavalon@gmail.com>:

**Comment by runeavalon** [comment]
:S i cant take those long stories back now


2016-12-12 21:38 GMT+01:00 Leander Letwory <runeavalon@gmail.com>:

**Comment by CH4Code** [comment]
holy shit man! thats not 3 sentences!

**Comment by runeavalon** [comment]
and you are right about Zjordy, i was just disapointed that he quit the job
and said its an impossible task. i dont remember what i said about him. i
hope it didnt sounded insulting or judging too much. i am very greatfull
for him wanting to help me. And very greatfull for you wanting to help me
as i did put a lot of effort in this map. i was just a bit disapointed. and
it IS a very difficult thing i ask to do, i know that. But i think if we
can succeed in finishing the map to work, many people will find a lot of
joy in playing it.

2016-12-12 21:39 GMT+01:00 Leander Letwory <runeavalon@gmail.com>:

**Comment by runeavalon** [comment]
hmmm i see i need to learn to read better also :/. sry for that. I
downloaded the map through your link and will take a look at the things you
mentioned

2016-12-12 21:45 GMT+01:00 Leander Letwory <runeavalon@gmail.com>:

**Comment by runeavalon** [comment]
Ahhhhhhh you responded!!!!!! i know i know. I should learn to read better
:/ SORRY!!!!!!!!!!!!!!!!!! but its a very big thing to explain in 3
sentences also :S. plzz forgive me

2016-12-12 21:48 GMT+01:00 Leander Letwory <runeavalon@gmail.com>:

**Comment by runeavalon** [comment]
i just got a bit overexited,,,,,mannnnnnnnnn -_-

2016-12-12 21:53 GMT+01:00 Leander Letwory <runeavalon@gmail.com>:

**Comment by runeavalon** [comment]
ok i think i changed a lot of the problems you mentioned. I made it
possible for soviets to acces all oil derrecks, i fixed stat defence
placement. as far as i know you can access now every location either by
boat or by land units.

for the question about harvesting and building space near the orepatches:
It is first of all ment to have infinite ore, BUT you need a lot of
harvesters. It is possible for 1 person to build a conyard at the patch
places left and right. And i made just enough room for 1 or 2 refinaries
there. The starting cash comes from the most upper and most lower ore
patches.

Then after that it is ment to expand as soon as possible towards the 3 mid
spots( left middle and right) where both teams can fight for the 1 ore
patch that is there on each of the 3 lanes.

Then it is also ment to gain money out of killing creeps which have to
respawn after a certain amount of time after being killed as i explained in
my way too long message above.

Shall i upload the map with the changes? or shall i send it to your email
adress? that is if these messages werent too long for you :/ and you are
still willing to help me out with this

cheers Ohmk Torque

2016-12-12 21:53 GMT+01:00 Leander Letwory <runeavalon@gmail.com>:

**Comment by obrakmann** [comment]
Please take this to the forums, the subreddit or wherever else. This bug tracker is not meant for support requests.
