### ISSUE TITLE
[TS]Harpy and Titan render bug

### ISSUE THREAD

**Issue by tytannial** [OpenRA/OpenRA#12319]
![2](https://cloud.githubusercontent.com/assets/11215623/19834354/40eab48a-9e96-11e6-8095-471f4024e736.png)
![3](https://cloud.githubusercontent.com/assets/11215623/19834391/cb3db32a-9e97-11e6-9bb7-247c43fb540f.png)

Harpy is under the Service Depot And the titan's barrels are missed in some specific angles.

version:latest bleed

**Comment by reaperrr** [comment]
The Harpy bug is actually a service depot bug, I'll fix that shortly.
The voxel barrel bug is known, too, but no idea when it will be fixed.
