### ISSUE TITLE
Can't capture neutral camo-pillbox

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#12312]
because its camouflaging when you get near it ... (what i mean by that is , you may see it when "explored is on" but when you get close with an engi for example , it gets invisible and you cant capture it)

sometimes this actor is empty and therefor should always be visible unless captured

**Comment by Mailaender** [comment]
This has been fixed by https://github.com/OpenRA/OpenRA/pull/16803 as infantry can now detect cloaked buildings with a range of 1. It is a bit fiddly, but now possible to capture them:

![image](https://user-images.githubusercontent.com/756669/83407330-cd5bd100-a410-11ea-96d5-cb388d0422e8.png)
