### ISSUE TITLE
DirectX renderer

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#12321]
I guess there is more than one solution to this, e.g.:
- indirectly with OpenGL ES through ANGLE
- through some kind of framework like @MonoGame
- natively with MDX or @SharpDX

Note: Just opening this ticket as it is an often requested feature. I don't plan to work on this myself.

**Comment by chrisforbes** [comment]
We used to have one. It wasn't worth maintaining.

**Comment by LipkeGu** [comment]
by the way we could implement this for mobile platforms (Notebooks with mobile Graphic Drivers)  we could negotiate the FeatureLevels for the Drivers and platforms... Im starting to working on a sandbox engine with directX11

Input can be used with dinput8 dll and sound via daudio.dll
