### ISSUE TITLE
The Radar Jammer can no longer defend other units.

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#12327]
In the previous release, you could use the defend command ("d") to make Radar Jammers follow your units around keeping them safe. This made them a lot easier to use.

This is probably caused by [#11637](https://github.com/OpenRA/OpenRA/pull/11637)  -- where units without weapons no longer have combat related abilities (attack move & defend).

Also related to [#12201](https://github.com/OpenRA/OpenRA/issues/12201)

**Comment by abcdefg30** [comment]
Closing as covered by the more general #18004 which proposes to introduce a "follow" command.
