### ISSUE TITLE
GPS Bug

### ISSUE THREAD

**Issue by openrarocks** [OpenRA/OpenRA#12320]
Just played two games, in one the GPS took about 4.4 minutes to "activate" after the satellite was lauched, in the second game it never did (I forfeited after a fair amount of time, opponent's GPS which lauched well after mine was working btw).  Looks like a bug.

[release-20161019.zip](https://github.com/OpenRA/OpenRA/files/560293/release-20161019.zip)

**Comment by Mailaender** [comment]
Did you disable your radar? https://github.com/OpenRA/OpenRA/pull/11018/

**Comment by openrarocks** [comment]
That appears to be the cause, thanks Mailender.

Disabling GPS without radar seems logical, but a) it doesn't look like it was announced anywhere in any of the recent news posts b) an audio or even text warning about this during the game might be useful for a release or two so players can get used to it.

**Comment by Mailaender** [comment]
I agree that it is quite hidden in the massive https://github.com/OpenRA/OpenRA/wiki/Changelog that I guess nobody reads. Indeed that should have been communicated a bit better. Pinging @SoScared who is the master of social media and Red Alert balancing nowadays.
