### ISSUE TITLE
Aircraft reveals shroud/fog based on animation, not actual position.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#12330]
Actual position meaning the cell the aircraft hovers above. It's a balance issue really. Aircrafts approaching from the south has a significant advantage due to being able to fire and being fired upon from the occupied cell. This concerns all mods.

Left vs Right, no difference.
![gap1](https://cloud.githubusercontent.com/assets/2715583/19876250/9d66974e-9fd4-11e6-939a-ef30dfecbdf0.jpg)

Top vs Bottom, big difference.
![gap2](https://cloud.githubusercontent.com/assets/2715583/19876260/bf42772a-9fd4-11e6-9455-cffcf6677bb8.jpg)

AA Gun targeting range edging the Longbow's cell position (shadow).
![gap3](https://cloud.githubusercontent.com/assets/2715583/19876270/d6f2ac1e-9fd4-11e6-964e-e2345144a52b.jpg)

Longbows' missile range based upon cell position.
![gap4](https://cloud.githubusercontent.com/assets/2715583/19876292/fe3024fa-9fd4-11e6-9e88-b2fdaee834f9.jpg)

This discrepancy plays out in all air to ground engagements giving the south position a significant advantage of about 2-4 cells (due to variable shroud rendering) in vision/targetting involving helicopters and even more so with YAK/MiGs which has an higher altitude - giving the south position a staggering 4-6 cells advantage.

This issue has probably gone unnoticed because of the shroud reveal visually looks logical from the placement of the animated aircraft.

**Comment by AoAGeneral** [comment]
This actually is the same reason why AA can't hit air units when flying on the north side hiding in out of map shroud while the shadow is still visible.

**Comment by pchote** [comment]
This was a deliberate trade-off that was made to let vision work in TS and RA2.

**Comment by SoScared** [comment]
I think this constitutes a significant balance problem, especially now that the RA mod is in a phase of balance "polishing" in which balance changes aims to fine tune the fast evolving competetive sector. For example, as referenced above the newly adopted GAP feature isn't reliably balanceable with aircrafts with this issue in mind.
