### ISSUE TITLE
The 120mm cannon is unable to harm infantry. [RA]

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#12335]
If you force fire the ground with the Mammoth tank, then walk infantry into the shots, they won't be harmed.
"Infantry" should be removed from Warhead's "InvalidTargets:" list.

120mm:
+Warhead@1Dam: SpreadDamage
++InvalidTargets: Air, **Infantry**

**Comment by obrakmann** [comment]
The balance implication of changing this as suggested would probably outweigh the impact of this bug.

**Comment by FrameLimiter** [comment]
How so? The 120mm itself has separate target conditions that excludes infantry. This would only affect the warhead in the event of splash damage & force firing right?

120mm:
+InvalidTargets: Air, Infantry
+Warhead@1Dam: SpreadDamage
++InvalidTargets: Air, Infantry

**Comment by obrakmann** [comment]
Haven't checked, but yeah, that sounds plausible.
