### ISSUE TITLE
Encountered Undeploy Bug

### ISSUE THREAD

**Issue by ThisBlunt** [OpenRA/OpenRA#12359]
Can't undeploy Construction Yard. This happened after I iron curtained a construction yard and Tanya C4'd it. Notice the red circle as I didn't snapshot the cursor. I have a replay if need be.
![screen shot 2016-11-06 at 9 06 14 pm](https://cloud.githubusercontent.com/assets/14940856/20044829/14ac7f00-a46a-11e6-8a42-f8a34b5bb94e.png)

**Comment by Micr0Bit** [comment]
easy to reproduce , curtain a conyard ... then try to c4 it .... after this , you cant undeploy anymore ... when you hover over your conyard ... the cursor always looks like this : 

![cursor](https://cloud.githubusercontent.com/assets/9139965/20058827/47d99474-a4f3-11e6-9fba-fc126bc28ff6.png)

**Comment by FrameLimiter** [comment]
This actually breaks all structures, not just the Construction Yard:
You're unable to sell, produce units, or power on/off any structure after this occurs.

**Comment by pchote** [comment]
This was fixed a while ago when the Building lock was removed from Demolish.
