### ISSUE TITLE
Dedicated Server no longer allows single player

### ISSUE THREAD

**Issue by djlists** [OpenRA/OpenRA#12364]
The new dedicated server does not allow starting games with a single human player. Tried both Server.DisableSinglePlayer=False (from web page) and Server.EnableSinglePlayer=True (from man page).

**Comment by abcdefg30** [comment]
Seems like you need `EnableSingleplayer` (no uppercase "P"): https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Settings.cs#L75

**Comment by djlists** [comment]
That works. I updated the Dedicated Server wiki. Thanks!
