### ISSUE TITLE
Suicide behavior of rocket soldiers

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#12368]
Rocket soldiers tend to get themselves killed by wandering away from the group to chase down enemy ground units. This is very annoying.

This occurs because the AutoTarget ScanRadius defaults to the unit's max weapon range. Since the rocket soldier has two different weapons with two different ranges, it uses the one with the longest range. This makes rocket soldiers chase ground units with a scan radius of 7.5 cells (AA range) instead of 5 cells (AG range). 
Setting their ScanRadius to 5 cells should prevent this excessive chase behavior.

OpenRA\mods\ra\rules\infantry.yaml
E3:
+AutoTarget:
++**ScanRadius: 5**

Source infantry chase behavior:
OpenRA\mods\ra\rules\default.yaml
^Soldier:
+AutoTarget:
++ScanRadius: -1 ([default to maximum weapon range](https://github.com/OpenRA/OpenRA/wiki/Traits#autotarget))

**Comment by RobAWilkinson** [comment]
This looks pretty easy, is there an IRC channel for the dev?

**Comment by Phrohdoh** [comment]
@RobAWilkinson #openra on the freenode network.

**Comment by reaperrr** [comment]
Closed via #12376.
