### ISSUE TITLE
Repair Submarines

### ISSUE THREAD

**Issue by ThisBlunt** [OpenRA/OpenRA#12361]
I should be able to repair submarines or any naval with the repair cursor...
![screen shot 2016-11-07 at 9 56 56 am](https://cloud.githubusercontent.com/assets/14940856/20063048/d35f8104-a4d3-11e6-930f-bfdde16fa628.png)

**Comment by FrameLimiter** [comment]
This feature is also needed for air units.

**Comment by pchote** [comment]
This is probably because ships have the `RepairableNear` trait instead of `Repairable`.

**Comment by openrarocks** [comment]
Why should you be able to?

**Comment by abcdefg30** [comment]
You can use the repair cursor to tell tanks to move to the next service depot. It sounds reasonable to me to also have ships/subs move to the next repair bay when using the repair cursor on them.

**Comment by ThisBlunt** [comment]
Because submarines and Aircraft are vehicles.

**Comment by damoch** [comment]
Can I take it?

**Comment by Phrohdoh** [comment]
@damoch If you mean claiming this ticket, sure!

**Comment by damoch** [comment]
I'm on it then!

**Comment by Snurre86** [comment]
Pretty difficult to press the wrench on the mig IMO.

**Comment by rob-v** [comment]
PR #13104

![obrazok](https://cloud.githubusercontent.com/assets/16348750/24917514/c2ec9b52-1edd-11e7-953c-65f14b3873e6.png)

**Comment by atlimit8** [comment]
#13104 was merged.
