### ISSUE TITLE
Save spectator-only chat for spectators

### ISSUE THREAD

**Issue by ShadowA** [OpenRA/OpenRA#12373]
In replays, spectator-only chat is not saved, even when spectating during the game. 
Some interesting conversations can be lost ... 

Would it be possible for spectators to keep the chat in the replays ? While the players still don't see it.

**Comment by Townes27** [comment]
All chat is being saved, it just isn't being displayed when you watch the replay.

**Comment by ShadowA** [comment]
Oh I see. 

Is this the intended behaviour ? If yes, is it important that non-spectators shouldn't read the chat ?
 
I could understand, that it is difficult to figure out who's watching the replay (can be downloaded ... or also the player becomes spectator). Maybe with the IP or sth ? 

Even for the players, it can be interesting : good commentary or advices can be said on spec-chat, and it could be read afterwards when watching the replay.

**Comment by Townes27** [comment]
You can open a replay file with any text editor for example and search for "chat" or "teamchat" and find the appropriate lines.
Displaying all chat while watching a replay would be a few lines of code.

**Comment by ShadowA** [comment]
Oh cool thanks, I didn't know that !
