### ISSUE TITLE
Infantry shoot animation freezes (All mods)

### ISSUE THREAD

**Issue by Fincer** [OpenRA/OpenRA#12375]
If infantry stops shooting, the attack animation freezes for a while until the idle animation comes to the scene. This bug affects all mods (including RA2)

The bug is not so visible in older titles (RA, TD, D2K). In TS you can see it better. It's clearly visible in RA2 (muzzle flashes freezing and so on). Got muzzle flash frozen in D2K (with Trooper unit), too.

To reproduce:

1) Hold ctrl + attack random target (e.g. terrain) with an infantry unit
2) Give a sudden stop command to the unit while it's shooting
3) Unit freezes for a moment until idle animation continues

-----------------------------------------
For RA2, a custom hotfix (https://github.com/Fincer/openra-tibsunra2/blob/master/data/hotfixes/linux/hotfix-infantryanimations_shoot.patch) for shoot animations were applied first to fix https://github.com/OpenRA/ra2/issues/322

**Comment by reaperrr** [comment]
I suspect the state in `WithInfantryBody` doesn't reset properly when an attack is aborted by a stop command.

**Comment by GraionDilach** [comment]
The same happens if an infantry kills the target and no other one is around.

**Comment by abcdefg30** [comment]
Also see #5884.
