### ISSUE TITLE
Bug when trying to deploy concrete walls on moving units 

### ISSUE THREAD

**Issue by Omnomon** [OpenRA/OpenRA#12372]
Hi all,

I don't know if there's a system log or a replay that can prove this, but I have found that deploying a (single) concrete wall on top of a moving unit stops the wall from being placed, and takes away the money I spent on the wall. 
This has happened in several games where I have used the walls to block pillbox fire, but a rifleman or another unit moved into the build zone right as I had placed it, and then both my wall and my money disappear. 

Although this is a minor issue, it is kind of annoying since I just lost $100 that could have gone towards a pillbox (lol).

**Comment by rob-v** [comment]
PR #13051

**Comment by pchote** [comment]
Fixed by #13025, apparently.

From #13051:

> I didn't reproduce the bug after rebase, this PR and issue #12372 can be closed.
