### ISSUE TITLE
Replace upgrade levels with BooleanConditions

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#12380]
## Motivation

When the upgrades system was first introduced (#6110, #6556) it used single string conditions as boolean flags for enabling/disabling a trait, with a fuzzy overrideable definition for "can I accept an upgrade of this type" that was used by the stats modifier trait to allow multiple upgrades to increment the applied bonuses.  #6750 overhauled this by changing the upgrade types from booleans to integer levels, and added a framework for turning traits on and off at arbitrary upgrade levels.  This had the very nice benefit of allowing stacked upgrades to activate higher levels of behavior.

As time has gone on it become clear that the benefit of upgrade levels / stacked upgrades is significantly outweighed by our inability to define conditions that depend on non-trivial combinations of upgrades.

As an example, we would like to have the RA radar dome's `ProvidesRadar` trait to be active when:
* The buildup sequence has completed (i.e. not during the make / sell animations).
* The Player is not low-power.
* The building has not been manually powered down.
* A radar jammer is not in range.

This can't be represented using our current upgrade system, but can easily be defined in terms of a boolean expression: `buildcomplete && !(lowpower || powerdown || jammed)`.  We have a number of projects (e.g. removing `IDisabled`, removing the BuildComplete hacks from traits, removing the hardcoded radar jamming logic, finishing TS carryalls) that are stalled over similar syntax problems.

## Discussion

This is going to be a painful migration to complete because it can only be partly automated.  It's not so bad for our default mods because we only use multi-level upgrades for veterancy.  I have heard that other mods rely on these much more extensively, but as far as I know they aren't publicly available so I can't look at their rules.  Based on earlier discussions I expect this to be a controversial change.

The new system will be able to replicate stacked upgrades in two ways:

* A `ConditionCombiner` trait that can (among other things) convert parallel conditions `a`, `b`, `c` (granted in any order) to ordered conditions `1`, `2`, `3`:
```
ConditionCombiner@1
	EnableCondition: a || b || c
	GrantCondition: 1
ConditionCombiner@1
	EnableCondition: (a && b) || (a && c) || (b && c)
	GrantCondition: 2
ConditionCombiner@1
	EnableCondition: a && b && c
	GrantCondition: 3
```

* Making `UpgradeActorsNear`, `GrantUpgradeWarhead`, etc, grant the first disabled upgrade in their type list.  E.g. for a hypothetical "slow" weapon that stacks to two levels
```
GrantUpgradeWarhead:
	GrantCondition: slow-1, slow-2
	Duration: 50
```

The first warhead impact would grant the `slow-1` condition on the target.  The second warhead impact would see that `slow-1` is already enabled, and grant `slow-2` instead.  The third and subsequent impacts would see that all upgrades are already active, and instead recharge the timeout on the shortest one (first `slow-1` then `slow-2` and so on).  This can be combined with `ConditionCombiner` on the target actor if the modder wants the warhead to trigger multiple conditions on the target actor.

This overhaul is explicitly trading off convenience for the stacked upgrade case for the ability to solve a lot of problems that currently aren't possible.  I have tried to cover all the bases in this PR introduction because I want to avoid a rehash of the ill-informed argument when I first outlined this plan in IRC a few months ago.

**Comment by GraionDilach** [comment]
I have one particular usecase where the limitations with this plan shines: Generals China horde logic, which is just a handful of liines on a template inheritable in the current system:

```
^DragonInfantry:
	WithRankDecoration@horde:
		Image: rank
		Sequence: horde
		Palette: apolred
		ReferencePoint: Bottom, Right
		UpgradeTypes: infhorde
		UpgradeMinEnabledLevel: 5
	FirepowerMultiplier@salvage:
		UpgradeTypes: infhorde
		Modifier: 116
		BaseLevel: 5
	ReloadDelayMultiplier@salvage:
		UpgradeTypes: infhorde
		Modifier: 87
		BaseLevel: 5
	UpgradeActorsNear@horde:
		Upgrades: infhorde
		AffectsParent: true
		Range: 1c768
```

With your conditions, I can see that UpgradeActorsNear would need to list 5 GrantConditions into a ConditionCombiner trait which grants the actual horde bonuses BUT that'll be confusing since with UANs granting different upgrades, it sounds to me that the horde bonus ends up failing if units don't overlap each other's aura exactly and it'll lead to granting mzultiple instances of the same infhorde subupgrade - unless you intend to refactor UpgradesActorsNear to constantly lookup the grantcondition, which I doubt you would.

**Comment by pchote** [comment]
The following should work exactly the same:
```
^DragonInfantry:
	WithRankDecoration@horde:
		Image: rank
		Sequence: horde
		Palette: apolred
		ReferencePoint: Bottom, Right
		EnableCondition: infhordea && infhordeb && infhoardec && infhorded && infhordee
	FirepowerMultiplier@salvage:
		UpgradeTypes: infhordea && infhordeb && infhoardec && infhorded && infhordee
		Modifier: 116
		BaseLevel: 5
	ReloadDelayMultiplier@salvage:
		UpgradeTypes: infhordea && infhordeb && infhoardec && infhorded && infhordee
		Modifier: 87
		BaseLevel: 5
	UpgradeActorsNear@horde:
		Upgrades: infhordea, infhordeb, infhoardec, infhorded, infhordee
		AffectsParent: true
		Range: 1c768
```

Or alternatively you could define:
```
ConditionCombiner:
	EnableCondition: infhordea && infhordeb && infhoardec && infhorded && infhordee
	GrantCondition: infhoarde
```

if you don't like repeating the longer condition on all the consumer traits.

**Comment by pchote** [comment]
Actually, I missed the `WithRankDecoration`, which I assume is showing a sprite that increments as you get more nearby?  You would indeed need to use `ConditionCombiner` to define the 1-5 neighbour conditions to toggle the correct sequence.  Take a look at how the veterancy icons work in #12381.

**Comment by GraionDilach** [comment]
Nah, WithRankDecoration is basically a WithIdleOverlay there - I don't even know why I'm using a WRD instead of a WIO. You're missing the main point here, which I'd illustrate:

![hordebonus](https://cloud.githubusercontent.com/assets/1136302/20248235/e5242d7a-a9df-11e6-936a-15f795bfdfe3.png)

Sorry for the image being messy though, but each UAN level is shown with a different color. Red, green and blue on the left gains horde bonus. Pink is missing yellow. Yellow is missing pink but gets a second blue instead since the 6th unit assumes blue is the first level missing and itself lacks them all. How do you intend to resolve that case?

**Comment by pchote** [comment]
I'm finding it difficult to interpret your diagram, so i'll take a guess.  Do you mean: you have 6 infantry in a group, with 5 of these each granting one of infhordea - infhordee, and one not applying anything.  Moving one of these infantry away would then break the condition unless the 6th one can re-evaluate itself and grant the now-missing condition?

**Comment by GraionDilach** [comment]
Yeah, that's also a good example. Both that and mine leads to possibilities when unit A needs to grant infhordea to unit B but infhordee to unit C.

**Comment by pchote** [comment]
> possibilities when unit A needs to grant infhordea to unit B but infhordee to unit C.

There's no problem here.  My example where UAN-having actors move will need further thought.

**Comment by pchote** [comment]
The only feasible solution will be to drop support for stacked upgrades from `UpgradeActorsNear`.

Your hoarde use case was a stretch of a use case for UAN, and can be easily and more efficiently done with a new `HoardBonus` trait that uses a proximity trigger that counts compatible actors inside range and then grants a local upgrade/condition when the threshold is met.

**Comment by GraionDilach** [comment]
Ah yes, that's a good idea. Come to think of it, I already have such a system implemented for proximity bounty. So carry on.

I know it will be a PITA to convert everything to the new system but except this case, every usecase I can think of can be resolved with really long walls of texts, so I'd say you have dealt with my "eventual tantrum".

**Comment by GraionDilach** [comment]
Yes, I have no concerns regarding this anymore. Will take care of the update/conversion in the mods I am participating in.

**Comment by WolfGaming** [comment]
This will probably simplify a lot of the logic in the end since it is easier to wrap your head around a condition that is either on or off instead of the 2 million something levels that were possible with the current system.
:+1: from me on this idea.

**Comment by pchote** [comment]
Timed upgrade stacking from warheads has the same issues mentioned for UAN above, so i'm going to have to drop that too.  If that's going to be a problem then we will need to think about introducing a new concept for these stackable and timed conditions that bridge to regular bool conditions on the actor.

**Comment by GraionDilach** [comment]
I'm not certain what do you mean here. The `GrantCondition` list you sketched in the first post already implied dropping timed upgrade stacking, superseding them with as many values on this `GrantCondition`s list as the amount of level it had, with the additional footwork of specifying `ConditionCombiner`s for each possible combination levels.

If that's still feasible, then my previous statement regarding the adjuration still applies, it'll lead to a PITA converting timed upgrades with many levels, but still not impossible.

**Comment by pchote** [comment]
It has the same problem as UAN, except replace "granting actor moves out of range" with "upgrade times out".  Instead of having an upgrade go from level 1 to level 2 then back to level 1 (when the first source times out), then gone you go from level 1 to level 2, then it stays at level 2 even after the level 1 upgrade disappears.

**Comment by GraionDilach** [comment]
```
GrantUpgradeWarhead:
	GrantCondition: slowtrigger1, slowtrigger2
	Duration: 50

ConditionCombiner@slow75:
	EnableCondition: slowtrigger1 || slowtrigger2
	GrantCondition: slow75
ConditionCombiner@slow56:
	EnableCondition: slowtrigger1 && slowtrigger2
	GrantCondition: slow56
SpeedMultiplier@slow75:
	EnableCondition: slow75
	Modifier: 75
SpeedMultiplier@slow56:
	EnableCondition: slow56
	Modifier: 75			;56.25 with slow75 also being enabled, stacking is possible
```

Am I missing something?

**Comment by pchote** [comment]
Compare the final applied conditions / modifiers with the old system (levels change based on number of active upgrade instances) vs new system (conditions fixed on behaviour at impact time):

```
warhead 1:     x  x  x  x  x  x  x  x
warhead 2:                 x  x  x  x  x  x  x  x
Old system:    56 56 56 56 75 75 75 75 56 56 56 56
New system:    56 56 56 56 75 75 75 75 75 75 75 75
```

**Comment by GraionDilach** [comment]
Right, I see what you mean now, but that's why my example uses intermediate ConditionCombiners and doesn't use the GUW upgrades to trigger the modifiers directly. It just needs a further level of abstraction, I don't see that as a problem.

Excluding that it straight flatout denies @WolfGaming's simplicity claim, but that's acceptable.

**Comment by pchote** [comment]
Ah yes, now I see your point.

I am still leaning towards handling this with an `ExternalCondition` trait (for lack of a better name) that bridges these outside toggles (from warheads, other actors, lua) to conditions similarly to how `GlobalUpgradable` currently bridges prerequisites to upgrades.

This has two benefits:
* Lua, warheads, and UAN keep the same behaviour they have now, supporting stacking and time delays.
* We can move delays out of the core upgrade/condition logic, simplifying that even further.
* Conditions are granted and consumed entirely within the same actor, which makes it easy to lint.

The trait could look like the following for the slow warhead example:
```
ExternalCondition@slow:
    Type: slow
    GrantCondition:
        1: slow75
        2: slow56
```

or for stealth generation from UAN (with only one level)
```
ExternalCondition@stealth:
    Type: stealthgen
    GrantCondition: stealthgen
```

The tradeoff here is the extra complexity that comes from having conditions vs external conditions vs prerequisites that can be bridged together and named the same but are otherwise distinct concepts.

I'll need to think about this some more before I decide which approach I prefer.

**Comment by Phrohdoh** [comment]
Would that example grant `slow75` and `slow56`, or just the latter?

**Comment by pchote** [comment]
#12406 implements the `ExternalCondition` behaviour above on the `UpgradeManager` itself.
