### ISSUE TITLE
Tool bars are too small in HiDPI screen

### ISSUE THREAD

**Issue by sudoyang** [OpenRA/OpenRA#12385]
Hi guys,

I am running ubuntu 16.04 on a 2015 thinkpad x1 carbon with screen resolution 2560x1440. When I run openra, the map looks good if I enable double-pixel function but the toolbars and mouse cursor are still too small to use.

**Comment by pchote** [comment]
Thanks for the report!  This is covered by #10382, so I'll close this one as a duplicate.
