### ISSUE TITLE
File not found: temperat.pal ?

### ISSUE THREAD

**Issue by KevinYeti** [OpenRA/OpenRA#12394]
Hi
I ran the game under RA mods and got the exception File not found: temperat.pal  when initializing by code. 
But when i tried to run the game by the downloaded release, everything went well. I can not find the file of "temperat.pal"  in both folders . 
Is there anything I missed ? 

System.IO.FileNotFoundException
  HResult=-2147024894
  Message=File not found: temperat.pal
  Source=OpenRA.Game
  FileName=temperat.pal
  StackTrace:
        OpenRA.FileSystem.FileSystem.Open(String filename)  c:\svn\client\trunk\OpenRA.Game\FileSystem\FileSystem.cs:Line 228
        OpenRA.Graphics.CursorProvider..ctor(ModData modData) c:\svn\client\trunk\OpenRA.Game\Graphics\CursorProvider.cs:Line 41
        OpenRA.ModData.InitializeLoaders(IReadOnlyFileSystem fileSystem) c:\svn\client\trunk\OpenRA.Game\ModData.cs:Line 129
       OpenRA.Game.InitializeMod(String mod, Arguments args)  c:\svn\client\trunk\OpenRA.Game\Game.cs:Line 398
        OpenRA.Game.Initialize(Arguments args)  c:\svn\client\trunk\OpenRA.Game\Game.cs:Line 335
        OpenRA.Program.Run(String[] args)  c:\svn\client\trunk\OpenRA.Game\Support\Program.cs:Line 176
        OpenRA.Program.Main(String[] args) c:\svn\client\trunk\OpenRA.Game\Support\Program.cs:Line 92
  InnerException:

**Comment by Phrohdoh** [comment]
How exactly are you launching the OpenRA you built from source?

I am running c4b5b745efe800d987a9b24f5ba05cda4a9163ed on macOS.

I completely removed the `ra/v2` directory (from `/Users/thill/Library/Application Support/OpenRA/Content/`) then ran `OpenRA.exe` from source which prompted me to install the necessary assets.

If you have this `ra/v2` directory also would you delete it and have (the from-source) OpenRA redownload the files for you?

**Comment by KevinYeti** [comment]
Hi @Phrohdoh , thank you for repling
I built the source code of release 20161019  on windows10. I just copy the ra/v2 content directory to my own source folder which was  newly downloaded by  the release 20161019.

**Comment by reaperrr** [comment]
> I just copy the ra/v2 content directory to my own source folder which was newly downloaded by the release 20161019. 

You shouldn't need to copy anything, by default a correctly compiled OpenRA should download/access files in `C:\Users\username\Documents\OpenRA` (Win7, exact path might differ on Win10).

**Comment by GraionDilach** [comment]
Doesn't differ between Win7 and Win10.

**Comment by KevinYeti** [comment]
@reaperrr  you mean the file "temperat.pal" will be downloaded to this folder C:\Users\username\Documents\OpenRA ?

**Comment by GraionDilach** [comment]
temperat.pal is part of C:\Users\username\Documents\OpenRA\Content\ra\v2\local.mix - you sure you ahve the base assets installed via the content manager?

**Comment by KevinYeti** [comment]
yes, I'm pretty sure the file is there and I've checked the file size again.

**Comment by pchote** [comment]
Try deleting / moving anything in `C:\Users\username\Documents\OpenRA\Content\ra` and running the game.  When it prompts for content let the game install it.

**Comment by KevinYeti** [comment]
@pchote I have removed everything in C:\Users\username\Documents\OpenRA\Content\ra and Support\Content\ and download all the files again. But still not working.

**Comment by KevinYeti** [comment]
Solved! After involved into the code deeply, I finally found I lost a file of "global mix database.dat" which is the key file to decrypt the mix file.  when I copy a new to the folder, everything went well.
