### ISSUE TITLE
Glitched Map

### ISSUE THREAD

**Issue by Squakas** [OpenRA/OpenRA#12399]
I tried Uninstalling and reinstalling Open RA But there is a custom map stuck in my official maps and it's annoying because I accidentally put in there and it sucks

**Comment by abcdefg30** [comment]
You can manually delete it by navigating to your OpenRA install and then going to `mods/ra/maps`
(assuming you talk about the ra mod).

**Comment by Squakas** [comment]
It's not there, I tried showing hidden files it still not there.

**Comment by Squakas** [comment]
I'm talking about red alert btw.

**Comment by pchote** [comment]
I assume that you are running Windows, and that your OS has redirected the file to the VirtualStore.  Take a look in `C:/Users/<your username>/AppData/Local/VirtualStore/Program Files/OpenRA` instead.

FYI this specific issue is why we insist that players should never modify their installed OpenRA program files.

**Comment by Squakas** [comment]
It was an accident of saving into official maps, got it fixed Ty xD, sorry for the trouble,
