### ISSUE TITLE
Vehicles stopping before the target location

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#12395]
When issuing a move order to a group of similar vehicles in a packed group, it seems that the ones in the back stop at some point, and don't continue to the target location.

https://www.youtube.com/watch?v=XU06HAaFnrM

It seems to be happening on short distances, or at the end of a long path. 

I didn't check if it happens with other configs (infantry in the front and vehicles in the back, slow vehicles front and fast behind, ...)

**Comment by reaperrr** [comment]
Duplicate of #5968.
