### ISSUE TITLE
[idea] add support long .wav sound files. 

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#12404]
When I try to add .wav music over 10 minutes, and start play it in game, - game is crach:

> Exception of type `System.IO.EndOfStreamException`: Attempted to read past the end of the stream.

**Comment by GraionDilach** [comment]
I have a song with a length of 12 minutes 9 seconds in 176 kbps IMA ADPCM WAV (22 kHz stereo) format. I never seen this issue.

**Comment by yaaaaa** [comment]
hmm, I have several music files from one source in this format:
![image](https://cloud.githubusercontent.com/assets/11130958/20465181/92819e98-af81-11e6-8043-7730e01e4116.png)
All files < 9 minutes plays fine, but files > 9 minutes craches the game.
After your answer I tryied to convert thouse files withowt change format, and now its work...
 stange... original files maybe was some corrupted, but any other payers works with it fine...

Anyway converted long files is work and I think I may close issue.
