### ISSUE TITLE
Medic cannot heal through concrete wall; tries anyway

### ISSUE THREAD

**Issue by whi7ed3vil** [OpenRA/OpenRA#12407]
Medics appear unable to heal through a concrete wall, but the sound effect is given when the medic is in range and the attempt is made with no effect. Don't know whether that should be resolved by allowing medic to heal through wall or by stopping him from trying. Current release-20161019.

**Comment by Micr0Bit** [comment]
stop him from trying , otherwise we had to allow him to heal while inside a pillbox

**Comment by MustaphaTR** [comment]
I also think we should make them don't try to fire against wall.

**Comment by Snurre86** [comment]
https://www.youtube.com/watch?v=kGS4ng3ZcXg

**Comment by abc013** [comment]
this happens to mechanics too.

**Comment by pchote** [comment]
Superseded by #12635.
