### ISSUE TITLE
[Bleed] Crash with the GPS Sattelite

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#12402]
Reproducable by building a Radar Dome and Tech Center in Debug mode.

Seems to crash a few moments after the GPS satellite goes up.

Produces the same exception logs:
http://pastebin.com/nFscnK36

**Comment by kyrylo** [comment]
For what it's worth, we were testing this together with @SoScared and the game crashed for us both at the same time.

**Comment by GraionDilach** [comment]
Could you try the replay with #12398? I guess this is what #12397 is about.

**Comment by SoScared** [comment]
I can still reliably reproduce the bug with #12398. It still involves building a Radar Dome and Tech Center getting the GPS up (using Debug menu and Disable Visibility Checks->off in my case). However if I build everything else in the build tabs _before_ the tech center (structures, units) then the crash don't happen.

**Comment by obrakmann** [comment]
Cannot reproduce, please provide detailed step-by-step reproduction steps.

I started a game with debug options enabled, checked the first five boxes of the debug menu, built a radar and then a tech center, and nothing happened, except that I got GPS.

**Comment by AoAGeneral** [comment]
Couldn't reproduce either.

I tried same map (Tournament Island by Scott_NZ) and every allied faction going Radar Dome > Tech Center. Waited 2 min in the game and even tried with scouting the enemy base.

**Comment by Micr0Bit** [comment]
same, cant reproduce

**Comment by SoScared** [comment]
I'll ask @kyrylo to help me reproduce this again soon. It's possibly a more narrow bug than the initial description suggests.

**Comment by pchote** [comment]
Are you sure this isn't just a duplicate of #12418 which was fixed by #12425?

**Comment by SoScared** [comment]
@pchote: I believe it's actually likely.

**Comment by pchote** [comment]
Closing as duplicate and/or no repro.  If this really is a separate issue we can reopen it later.
