### ISSUE TITLE
Capture can't be done by a group of engineers

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#12400]
If a group of engineers is sent to capture a building, only 1 will capture, the others will stay inactive.

_Situation I've came across : capturing enemy expansion, the only unit who could kill my engy was an ore truck. The enemy MCV being captured, no reinforcements could be brought (barracks, defence). And two engies at opposite sides of the MCV could have finished the work. 
But my first engy was crushed, so the second one had to start the capture all over again. Resulting in not being able to cap it, so I destroyed it._

Shouldn't multiple engineers be able to pass the relay ? 

Also, a subsequent idea would be to make the capture faster, at a certain rate (for instance : +50% faster per engy). Engies could then become a more useful unit on the field.

**Comment by abcdefg30** [comment]
See #4875.
