### ISSUE TITLE
[Tiket] make SpawnActorOnDeath trait is upgradabe

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#12414]
If it will spawn actors with KillsSelf: depending on the unit upgrades it wold be niser than make upgradable many other treats of unit to totaly transform it.

**Comment by Phrohdoh** [comment]
SpawnActorOnDeath was made upgradable / conditional in 2e4cd8d8209277a0076b5b5228ce5de2abb1e069.

**Comment by yaaaaa** [comment]
Great News!)
