### ISSUE TITLE
Nerf Rusher Strategy

### ISSUE THREAD

**Issue by TechnichalDoge** [OpenRA/OpenRA#12416]
I'm sure most of you have encountered it where people amassed an army early on, and there was no counter, that needs to be nerfed somehow.

**Comment by TechnichalDoge** [comment]
[http://www.gamereplays.org/openra/replays.php?game=92&show=details&id=315549#/replay_overview](replay)
Dont comment on topic of whats in the chat.

**Comment by FRenzy-OpenRA** [comment]
??????????????????????????????????????

Rush is a valid strategy. But this isn't even a rush ... 
First attack occurs at 8th min, which is unbearably long to watch, even at max speed.
Your team wasn't producing army, while the other was. 

And what exactly do you want to nerf ? It doesn't make sense.

There is absolutely no topic here.

**Comment by Micr0Bit** [comment]
there is no issue here , please close

**Comment by Snurre86** [comment]
What map is it?
