### ISSUE TITLE
It will play multiplayer fine, but won't play Skirmish or Singleplayer at ALL.

### ISSUE THREAD

**Issue by CanOPringles** [OpenRA/OpenRA#12413]
it doesn't crash when i try to play SP, rather, i can click on "play" all day and it won't do nothing.

**Comment by jaZzKCS** [comment]
This definitely needs more elaboration...

Do you mean with "play" the play-button in the Single Player mission select window?
What exactly happens when you try to click it?
Did you try out Skirmish? What happens when you click "Start Game" there?

What are your settings/specs/OS/etc...

**Comment by CanOPringles** [comment]
> Do you mean with "play" the play-button in the Single Player mission select window?

yes. i can select any mission and nothing happens when i hit play.

> What exactly happens when you try to click it?

nothing, that's the problem 

> Did you try out Skirmish? What happens when you click "Start Game" there?

it actually never got to the skirmish screen. it gets stuck "connecting".

> What are your settings/specs/OS/etc...

OS is windows 10, idk the specs, all i can tell you is its a notebook, Toshiba.

**Comment by pchote** [comment]
Something is blocking the game from connecting to the internal server it uses for running skirmishes and missions.  Do you run Norton or another aggressive antivirus/system management tool?

**Comment by CanOPringles** [comment]
pchote no. i do have AVG, though.

**Comment by yaaaaa** [comment]
If I open ower 50 tabs with active content in Chrome on Windows, then my ping is RED in skirmish...
I think You need to try clear Your running processes in Windows, check any virus activity, check firewall settings.

**Comment by WolfGaming** [comment]
Try to put OpenRA as an exception in the AVG firewall to allow access.

**Comment by jaZzKCS** [comment]
Your AVG firewall might be auto-blocking your own request to connect to yourself on localhost (127.0.0.1)

**Comment by CanOPringles** [comment]
i've been looking for the settings to either let OpenrA through AVG's firewall or to disable it completely. regardless, i'm more worried about not being able to play the missions than skirmish, it looks like a fun game but i keep getting owned in MP, because half the time idk what i'm doing.

**Comment by pchote** [comment]
Does it work if you disable your network (disconnect from wifi / unplug ethernet)?

**Comment by CanOPringles** [comment]
it's still trying to connect even when it's not connected to the internet.

**Comment by jaZzKCS** [comment]
If it is still (unsuccessfully) trying to connect even if you are not connected to the internet then Security Software is blocking your own localhost network interface. Could you try with both [unplugged ethernet cable / disabled wi-fi + Secority Software off]?

**Comment by CanOPringles** [comment]
idk how to turn off AVG, even then it shouldn't stop the singleplayer from working.

**Comment by jaZzKCS** [comment]
But it totally can. it may very well be blocking your attpemt to connect to your own local server (127.0.0.1) which is used for singleplayer. You have to understand that - even if you start a singleplayer skirmish or mission - that your ARE technically playing on a server still, albeit it is hidden and you do not even notice.

**Comment by BTGbullseye** [comment]
I have the EXACT same issue. Already tried disabling Avast, and even restarting with Avast disabled. (even though I don't have the Avast Firewall installed) I put all the exes in the game folder in their own Windows Firewall rule, and gave them complete access, changed nothing.

This is on Windows 7 x64 Ultimate.

**Comment by pchote** [comment]
Have either of you modified your hosts file?

**Comment by BTGbullseye** [comment]
I most certainly have... None of it should be blocking 127.0.0.1.

Interestingly, this is the exact same issue that has been preventing me from even starting the launcher for the game Dreadnought. (they just got fed up with trying to fix the problem, and said it was the fact that my PC specs were too low that was causing the issue)

**Comment by pchote** [comment]
Please try reverting the hosts file and see if it fixes the problem.

**Comment by yaaaaa** [comment]
try to ping 127.0.0.1

**Comment by BTGbullseye** [comment]
Tried both, no change.

**Comment by CanOPringles** [comment]
how can i revert host files? idk how to do that.

**Comment by yaaaaa** [comment]
DRWEB CUREIT FREE utility wiil check and fix hosts file
You can find and fix this file by notepad yourself (Windows\System32\drivers\etc\hosts)

**Comment by obrakmann** [comment]
closing here, not an OpenRA issue.
