### ISSUE TITLE
Make rendersprites trait is upgradable

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#12419]

**Comment by GraionDilach** [comment]
That sounds like a bad yaml coding - you don't need this.

**Comment by Phrohdoh** [comment]
Why is this not necessary?

**Comment by GraionDilach** [comment]
Because every time you want to mess with sprite artwork, it's the With* traits you want to mess with.

**Comment by yaaaaa** [comment]
I dont see any way to transform one unit to another unit with dependencies any prerequisites  or upgrades, and without killing first unit...

If make fundamental (visible to player) parametrs (like speed, name, view, armament) of units is upgradable, then we will can change one unit into many variations of alternative upgraded units, or we will can use it only in necessary trait to change only sprites applied an necessary  upgrade.

**Comment by GraionDilach** [comment]
IIRC tooltips just became upgradable, so you really don't need this. You can upgrade stats through applying a statmultiplier and armaments are upgradable for a great while ago. The With* traits are all upgradable (excluding WithDeathAnimation, which is the sole "reason" why the RA2 WithSwimSuit is needed).

IOW: you should be capable of doing everything to "upgrade" a unit  externally to something else. It does require careful planning atm - I acknowledge this is a case where the condition setup will simplify this - and you shouldn't need to upgrade any Render* traits for this.

**Comment by yaaaaa** [comment]
hmm... maybe i need to waiting condition setup, becouse Harvester trait  (to train harvester bring another resourse type by upgrade ) and many other traits is not upgradable.

**Comment by GraionDilach** [comment]
Upgrading the Harvester trait has nothing to do with upgrading RenderSprites. Also, the upgrade-to-condition setup won't change anything on the list-of-upgradable-traits front, but change the methods-to-effectively-set-up-trait-upgrades front, like allowing to fix the RA2 IFV without being forced to set up like 26 levels of eliteweapons.

Still, you haven't listed a single reason so far why you want to upgrade RenderSprites. I am getting the implication that you don't even know what you want.

**Comment by pchote** [comment]
@GraionDilach's underlying point is correct: Making RenderSprites upgradable/conditional does not properly solve any problems, and creates its own set of very difficult problems.

This discussion isn't going anywhere polite, so i will close this now.
