### ISSUE TITLE
Red Alert Crash - fixit1.aud is not a valid sound file

### ISSUE THREAD

**Issue by docholiday** [OpenRA/OpenRA#12420]
Hi there,

I was playing a skirmish game in Red Alert with openra-bleed, when the following error occurred:

----------------------------------------------
Red Alert Mod at Version {DEV_VERSION}
on map 6bbf6ff670d9f19ccbb380e475df6c5129477ddb (Pie of Animosity by Janitor).
Date: 2016-11-23 18:26:12Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.InvalidDataException`: fixit1.aud is not a valid sound file!
   bei OpenRA.Sound.LoadSound(ISoundLoader[] loaders, IReadOnlyFileSystem fileSystem, String filename) in c:\Users\myuser\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Sound\Sound.cs:Zeile 73.
   bei OpenRA.Sound.<>c__DisplayClass1.<Initialize>b__0(String s) in c:\Users\myuser\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Sound\Sound.cs:Zeile 78.
   bei OpenRA.Exts.GetOrAdd[K,V](Dictionary`2 d, K k, Func`2 createFn) in c:\Users\myuser\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Exts.cs:Zeile 131.
   bei OpenRA.Primitives.Cache`2.get_Item(T key) in c:\Users\myuser\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Primitives\Cache.cs:Zeile 36.
   bei OpenRA.Sound.Play(Player player, String name, Boolean headRelative, WPos pos, Single volumeModifier, Boolean loop) in c:\Users\myuser\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Sound\Sound.cs:Zeile 102.
   bei OpenRA.Sound.Play(String name, WPos pos) in c:\Users\myuser\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Sound\Sound.cs:Zeile 123.
   bei OpenRA.Mods.Common.Traits.Armament.<>c__DisplayClass13.<CheckFire>b__d()
   bei OpenRA.Mods.Common.Traits.Armament.ScheduleDelayedAction(Int32 t, Action a)
   bei OpenRA.Mods.Common.Traits.Armament.CheckFire(Actor self, IFacing facing, Target target)
   bei OpenRA.Mods.Common.Traits.AttackBase.DoAttack(Actor self, Target target, IEnumerable`1 armaments)
   bei OpenRA.Mods.Common.Activities.Attack.InnerTick(Actor self, AttackBase attack)
   bei OpenRA.Mods.Common.Activities.Attack.Tick(Actor self)
   bei OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act) in c:\Users\myuser\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Traits\ActivityUtils.cs:Zeile 37.
   bei OpenRA.Actor.Tick() in c:\Users\myuser\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Actor.cs:Zeile 164.
   bei OpenRA.World.Tick() in c:\Users\myuser\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\World.cs:Zeile 344.
   bei OpenRA.Game.InnerLogicTick(OrderManager orderManager) in c:\Users\myuser\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Game.cs:Zeile 559.
   bei OpenRA.Game.LogicTick() in c:\Users\myuser\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Game.cs:Zeile 586.
   bei OpenRA.Game.Loop() in c:\Users\myuser\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Game.cs:Zeile 713.
   bei OpenRA.Game.Run() in c:\Users\myuser\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Game.cs:Zeile 753.
   bei OpenRA.Program.Run(String[] args) in c:\Users\myuser\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Support\Program.cs:Zeile 134.
   bei OpenRA.Program.Main(String[] args) in c:\Users\myuser\Downloads\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Support\Program.cs:Zeile 41.

----------------------------------------------

I guess it could be, that the file is corrupt, but as everything else was working I'm not sure, that's the case.
Is there a crc-check when extracting the files from the Original discs?

And if it was corrupted, how do I get it extracted again (and from which disc)?

**Comment by yaaaaa** [comment]
If file is corrupt, try to use this one
[WinRAR ZIP archive.zip](https://github.com/OpenRA/OpenRA/files/610028/WinRAR.ZIP.archive.zip)

**Comment by pchote** [comment]
What source did you use for installing the original assets?

**Comment by docholiday** [comment]
@pchote I used ISO images, but that was my question - I don't know from which disc this file comes.

I will try the file from @yaaaaa and report back.

**Comment by pchote** [comment]
`fixit1.aud` comes from the aftermath expansion disk.  The aftermath iso from [CNCNZ](http://www.cncnz.com/features/freeware-classic-command-conquer-games/) is corrupted, so if you used that version it would explain this.

**Comment by docholiday** [comment]
I first tried it with the CNCZ one, but as written in another thread that wasn't recognized at all by the installer. I then used an ISO from a buddy which was recognized and the installer copied everything needed.

There is indeed a difference concerning the CRC checksum between my fixit1.aud and the one from @yaaaaa.

Could someone please create a sfv file for all ra mod files?
Wouldn't it make sense to have a crc check during importing the asset files?

**Comment by pchote** [comment]
>  Wouldn't it make sense to have a crc check during the import of the asset files?

We thought we could get away without it for simplicity, but it's become clear that we do indeed need this.

**Comment by abcdefg30** [comment]
Checking if the assets are valid is covered by #12807, so closing here.
