### ISSUE TITLE
Chat (type) visibility selection for the replay viewer

### ISSUE THREAD

**Issue by paulvt** [OpenRA/OpenRA#12421]
It would be nice, for reviewing and/or casting purposes, to be able to toggle:

- viewing spectator (team) chat (default on)
- viewing other teams chat  (default off)
- public chat (default on)

For casting is will give less distractions when all are off, while spectator/team chats may provide insights when reviewing.

I am not sure if you should be able to toggle them only beforehand or whether it should be toggles that can be changed "replay time".

**Comment by paulvt** [comment]
This is somewhat related to #12373 too.

**Comment by dragunoff** [comment]
Related: #5775
