### ISSUE TITLE
A possibility to hide the replay % when watching a replay.

### ISSUE THREAD

**Issue by noobmapmaker** [OpenRA/OpenRA#12438]
It would be nice if the user is able to hide the number that shows how far the replay is in % (and turn it back on if wanted).

This to make replays more exciting to watch.

**Comment by pchote** [comment]
This has already been fixed (by #12096) for the next release.

**Comment by abcdefg30** [comment]
Duplicate of #12017 which was closed by #12096.

**Comment by abcdefg30** [comment]
Well, ninja'd.
