### ISSUE TITLE
Harvester husk on refinery untargetable

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#12444]
Unlike tanks husks, harvester husks on refinery are untargetable
Whether enemy or own harvester.

Replay : https://drive.google.com/open?id=0B4bdF_48xIwKUFpsSlhRYkFVcnM

**Comment by FrameLimiter** [comment]
I just tested this, but was unable to reproduce the issue. The targeting of ore truck husks seems to work fine for me.

**Comment by FRenzy-OpenRA** [comment]
Weird. 
It was also reported to us from other players, thus we tried testing it in the replay above

**Comment by FRenzy-OpenRA** [comment]
Rectification ! 
Husk on OWN refinery is untargetable. Still whether enemy or own harvester.
Husk on enemy ref is targetable though, but that's irrevelant gameplay-wise.

**Comment by FrameLimiter** [comment]
From my tests I've found it's simply the angle of the ore truck that makes it more difficult to target. A husk that leaves little exposed below the ref landing is much more difficult to target. So a horizontal husk is much easier than a northeast & northwest facing husk.

**Comment by FRenzy-OpenRA** [comment]
Oh yeah, after other tries, it seems that the husk is targetable below the landing zone.
Targeting on the husk cell shows "Ore Refinery", but bringing the mouse a bit lower targets the husk.

Thanks for poiniting it out Frame.

Closing this
