### ISSUE TITLE
crashed by System.AggregateException

### ISSUE THREAD

**Issue by huyumars** [OpenRA/OpenRA#12447]
When I try to run the program it come out a crash prompt. then I found the message in log that :
Exception of type `OpenRA.YamlException`: Actor type ^amcv.colorpicker: FieldLoader: Cannot parse `110, 130` into `Modifier.System.Int32`

**Comment by pchote** [comment]
What mod are you trying to run?  The exception message is telling me that you're trying to run an outdated mod on a recent version of OpenRA.

**Comment by GraionDilach** [comment]
I assume one of the many outdated RA2 mods.

**Comment by huyumars** [comment]
Thanks for your help. It seems to be an outdated mods issue. Once I switched a RA2 mods downloaded from other place, it works prefectly.  I don't know why. I just clone the git from https://github.com/OpenRA/ra2. Is it a old version?

**Comment by Iamgoofball** [comment]
@huyumars Do you happen to know where you got your copy from?
