### ISSUE TITLE
Infantry "kickbox" animation use for combat instead of idle animation

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#12456]
As the tile says, i think the primary use of that animation was for close combat,or for some sort of "movie scene" in-game,like in modern 3D games.

but it needs to be a weapon activated by distance and target. 

And it is rather boring seen all your infantry dancing around like some martial art masters,and never do any real close combat.

**Comment by pchote** [comment]
What is the gameplay motivation for this?

**Comment by KOYK** [comment]
by motivation you mean its use? well its an extra,and i thing its realistic.more realistic from having attack dogs kill entire squads :p

**Comment by pchote** [comment]
OpenRA is primarily a game, so if a feature doesn't add to the gameplay then there is no reason for it to exist.

**Comment by KOYK** [comment]
having your infantry engage in close combat does not add to the game? man have you ever played Dawn of war? the strategy game?

**Comment by GraionDilach** [comment]
Do that in your own mod then.

**Comment by KOYK** [comment]
yea sorry for saying my idea and backing it up....

**Comment by GraionDilach** [comment]
Main issue with this idea is that the martial arts idle anim only has artwork for left and right facings at best, while everything else has 8 animations. The end result would look akin to how pre-4 Heroes looked or Street Fighter if they were used as actual animations and not idle visuals. Which would look really jarring next to the fact that every actual fighting anim has 8 or 32 facings.

I never played Dawn of War, nor I am interested in it, but infantry engaging in close combat only makes sense if said infantry has unit command bars where you can set the infantry to drop it's range. (Case in point I'd think of is Colonel Burton's knife in Generals, where Burton could kill infantry if you set that mode.) This unit command bar feature is missing from OpenRA however, and using the deploy command for this might not be visible enough to illustrate that this Minigunner is now in melee mode.

**Comment by KOYK** [comment]
i was thinking more like a secondary weapon,that is activated if the enemy infantry is at the same cell with the other infantry, no need for command bar. the animation its the real problem here.

btw how are you not interested for something you never played? academic question. try that game, you won't lose.
