### ISSUE TITLE
AI Squads and AI map locations

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#12454]
AI in OpenRa is like a child that needs guidance,it needs love and.. ok to the point

AI Squads: multiple squads for multiple targets, based on IF system an example..
enemy targeted player has (6) of (tnk3), then build squad (anti_tank_squad).

the squad must be defined of course. another example 

enemy target player has (1) (nuke), then build squad (attack_hellis)
self have squad (attack_hellis) in squad pool, then attack defined target.

so basically like red alert 2 AI.

AI map locations:
ok here is the interesting part,in order for example to make the AI to transport units from island to island,you have to script it,so what if the AI will just search of existing pre defined map locations to do that. you place a point on the map called lets say "NavyPortLoad" and you link it with the player starting point,so the AI will know that it relates to it,and can use it.so the AI builds up a transport ship and sent it at that point,and then loads up the units,and then it sent them to another point called "NavyPortUnLoad" that point is linked to "NavyPortLoad" of the AI that is currently attacking,so the AI will know that it can path to that point.in some detail

Player01 starting point
        Links: NavyPortLoad1, NavyPortLoad2

NavyPortLoad1:
        Links: NavyPortUnLoad4, NavyPortUnLoad1, NavyPortUnLoad6

NavyPortUnLoad4
        LinksToPlayer: Player07, Player03

I Know all this sound like mambo jumbo,but the execution is up to the dev's,the point is the idea.
the maper just needs to add some points that act like "highways" and link them so the AI will know what it can reach and use.

**Comment by Nineeva** [comment]
+1

**Comment by pchote** [comment]
This is mostly covered by #9021 and #4947, so closing as a duplicate.
