### ISSUE TITLE
Change the stats layout

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#12478]
This is just a fast draft as I am just drawing this not to forget so here is the proposed layout for the stats in replay/spectator view with tabs on top. Might add a team row on top of player row also.
![openra game_2016_12_15_15_05_31_446](https://cloud.githubusercontent.com/assets/7798635/21227626/1bc5a53e-c2db-11e6-9c30-afdfc2b9f3f5.png)

**Comment by abcdefg30** [comment]
The spectator UI was changed.
