### ISSUE TITLE
Game Not Starting And Causing Reboots

### ISSUE THREAD

**Issue by Bradzilla1** [OpenRA/OpenRA#12471]
I've been attempting to run the 20161019 version of OpenRA, on my Sony Vaio VGN-NR310E. While doing so, the game sort of "sputtered" while loading and caused the computer to restart. I've pulled up the error logs, but there's nothing in them. The included text below is the contents from one of two text files which was labeled "exception-2016-12-10T022430Z"

Date: 2016-12-10 02:24:30Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Program.Run(String[] args)
   at OpenRA.Program.Main(String[] args)

I've tried installing the manufacturer's drivers for the GPU, but it didn't help. The GPU is an Intel 900 series unit and I have Dot Net 4.5 installed.

**Comment by Mailaender** [comment]
That sounds like a hardware problem. Try undusting your laptop and post your `graphic.log` here.

**Comment by Bradzilla1** [comment]
Would you clarify what you mean by "undusting", please? I would post the graphics log, but I'm sorry to say there's nothing in it. I open it up and there's nothing. The computer originally had Windows Vista Home Premium, but I did an upgrade to 7 Home Premium. It's 32-Bit. Here is some more info on the graphics.

Display adapter 0	
	Display name		\\.\DISPLAY1
	Name			Mobile Intel(R) 965 Express Chipset Family
	Board Manufacturer	0x104D (0x902D)
	Memory size		384 MB
	PCI device		bus 0 (0x0), device 2 (0x2), function 0 (0x0)
	Vendor ID		0x8086 (0x104D)
	Model ID		0x2A02 (0x902D)
	Performance Level	0

Display adapter 1	
	Board Manufacturer	0x104D (0x902D)
	Memory size		384 MB
	PCI device		bus 0 (0x0), device 2 (0x2), function 1 (0x1)
	Vendor ID		0x8086 (0x104D)
	Model ID		0x2A03 (0x902D)
	Performance Level	0

Win32_VideoController		AdapterRAM = 0x18000000 (402653184)
Win32_VideoController		DriverVersion = 8.15.10.1930
Win32_VideoController		DriverVersion = 8.15.10.1930
Win32_VideoController		DriverDate = 09/23/2009
Win32_VideoController		DriverDate = 09/23/2009

I hope this helps.

**Comment by Mailaender** [comment]
You are below our https://github.com/OpenRA/OpenRA/wiki/Requirements#hardware Sorry.
