### ISSUE TITLE
Engineers disappear in MCV deployment state.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#12474]
https://youtu.be/uZnOcNABER0?t=42s

Video here shows this happening. I never realized this happens lol

**Comment by Deadairx** [comment]
# Issue
When a player attempts to capture someones Construction Yard the engineer(s) could disappear without capturing the building if the opposing player un-deploys the building to an MVC as the unit(s) are entering.

# Reproduction
I was able to reproduce this issue on `release-20161019` and `bleed` as of 01/18/17 1:00 AM CST (replays below)

### Steps

1. Start 2 clients and put them in the same multiplayer game.
2. Build multiple engineers on player 1 and get them near player 2's base
3. Order player 1 engineers to capture player 2's construction yard (from a bit of a distance)
4. Switch to player 2 and have construction yard selected and ready to un-deploy
5. Un-deploy to MVC just as player 1 engineers reach the edge of the building (see image for reference)
6. Engineers will disappear but the MVC will stay in player 2's control

# Resources

![00](https://cloud.githubusercontent.com/assets/12243529/22054733/c658f8ba-dd1c-11e6-8672-4268d1458b03.png)
[Map in video](http://resource.openra.net/maps/13528/)

### Replay Files
[Issue in video](https://mega.nz/#!Zs8HDZrQ!s6cpa3yQCttISRRt8GOEzsijGy6HK0a0qcX58fJGv78)
[Reproduction on release branch](https://mega.nz/#!xolUmLpb!aYJ2OaVjDggmCzjsmfras5PjGYPl9MGlNIdRGXYyCJU) (starts about 9 min in)
[Reproduction on bleed branch](https://mega.nz/#!8pVn2DCb!PG_cGZhU_ZmeKQtdYZw0dOAKKCTaIvY_w_WPoWAGywQ) (last commit [`59619a4e0d4c3eec1dd0d1841d627ad7689d2f5c`](https://github.com/OpenRA/OpenRA/commit/59619a4e0d4c3eec1dd0d1841d627ad7689d2f5c))

**Comment by AoAGeneral** [comment]
This actually happens when the MCV is standing at point too. This one is extremely hard to pull off however but it is caused when two engineers enter at the exact same time.

Replay showing here: https://www.dropbox.com/s/yjflrooxlp12im2/OpenRA-2017-01-18T040223Z.orarep?dl=0

This is also on the release version. Map is official and not downloaded.
