### ISSUE TITLE
ReinforceWithTransport doesn't work on Concrete tiles

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#12479]
another Bug with the ReinforceWithTransport LUA function: Transports called in with this function can't land on top of concrete tiles. see picture.
![carryallbug](https://cloud.githubusercontent.com/assets/16046997/21231653/58c8cd40-c2e9-11e6-9cd5-e6a58bbddfa9.png)
See also [other issues](https://github.com/OpenRA/OpenRA/issues/12464).
Cheers,
     SirCake

**Comment by ltem** [comment]
same problem with "rocky ground"

![landingblocked](https://cloud.githubusercontent.com/assets/20945684/21281425/0502d2aa-c3ed-11e6-9945-9a65976f032d.png)

**Comment by CH4Code** [comment]
Cosidering "rough"(= rocky ground) terrain is impassable for vehicles (and carryall may transport vehicles) that is more of an issue of [this](https://github.com/OpenRA/OpenRA/issues/12464) "bug", since it should scatter onto landable tiles i.m.o..

**Comment by ltem** [comment]
I agree with you, my interpretation of this function wasn't considering vehicles. I expected that if the carryall (only) transports infantry, it can put them down wherever infantry is allowed to stay. Still your point is more reasonable.
