### ISSUE TITLE
Bug http://openra.ppmsite.com/ra-base.zip not valid archive file

### ISSUE THREAD

**Issue by talregev** [OpenRA/OpenRA#12482]
When OpenRA try to download and extract http://openra.ppmsite.com/ra-base.zip
It say it not valid archive file.
When I try to download and extract my self, it happen the same error.

please fix.

**Comment by reaperrr** [comment]
I re-uploaded the package to the ppmsite mirror.

Could you retry and tell us if it helped?

**Comment by talregev** [comment]
I download and extract it manually and it work.
I guess it will work with download from the game itself. 
Thanks!
