### ISSUE TITLE
Touchpad Gestures and Touchscreen support

### ISSUE THREAD

**Issue by MichaelShaulskiy** [OpenRA/OpenRA#12489]
I'd like to propose implementing a common interface for input devices which translates specific input events (e.g. three finger swipe on a macbook trackpad...) coming from a myriad of input devices (like touchscreens, trackpads, mice, gamepads etc...) into general game events (like moving a unit somewhere or selecting a few units etc..) so, for example, touch screen controls on windows 10 tablets can be made more pleasant (I don't actually own a windows 10 tablet, however i can't imagine that simply treating touch events like a mouse could be as intuitive as it should be). 

The reasoning behind this proposal is that I sometimes like to play a bit of OpenRA casually on my Macbook, however most often without a mouse, although it's not too bad of an experience, I'd like to implement proper trackpad gestures like multiselecting with a three swinger swipe across the trackpad or focusing on the MCV with a three finger double tap on the trackpad, just to name a few examples. I think that this could be a major improvement to the experience overall and by having a proper plugabble driver-like architecture in the engine for input devices, we could make the gameplay more pleasant across the board and therefore attract more players. I personally think that having such an architecture where everybody could write "drivers" against would benefit the project immensly and I would be willing to do the necessary work (after exams...) of implementing my proposal. With a common input architecture, we could also make a TV-mode, which would work surprisingly well (I played Red Alert on my Playstation 1 back in the days) without duplicated effort

**Comment by abcdefg30** [comment]
Thanks for the input. I think #7154 already covers this though, so closing as duplicate.
