### ISSUE TITLE
Add RequiresPower trait on Production trait [feature]

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#12480]
Hi,
if a building is able to be powered down, then it also should stop producing stuff. This has currently no impact since all producing structures can't be powered down, but it would be nice to have the option to make production structures power-down-able.

This came up when trying to add a production queue to the d2k outpost.

Maybe a solution would be to add a boolean sub-trait `RequiresPower` to the `Production` trait, which enables production of a certain queue on a unit/structure. Or just geneally disable production when powered down ( != low power).

Advantage of the `RequiresPower` trait would be, that it is a general concept which can be applied to may building traits (compare C&C3, where you could power down everything). Disabling/Stopping is of course simpler and maybe a more straight forward rule.

Cheers,
---SirCake

**Comment by pchote** [comment]
#10237 covers the technical aspects of this.
