### ISSUE TITLE
openra fails to start on osx 10.12.2

### ISSUE THREAD

**Issue by sudoyang** [OpenRA/OpenRA#12495]
After I upgrade to osx 10.12.2, openra can not start any more. Thanks! Previous version of osx is fine.

**Comment by pchote** [comment]
Please see https://github.com/OpenRA/OpenRA/wiki/FAQ#pinwheel-of-death-when-starting-on-os-x-for-the-first-time

**Comment by sudoyang** [comment]
@pchote  Thanks! It takes a longer time to return to normal. Problem solved!
