### ISSUE TITLE
A speed between normal and faster: "Brisk" or "Fast-ish"

### ISSUE THREAD

**Issue by 3Lucian** [OpenRA/OpenRA#12509]
Call it "Brisk" or something similar. Speed choices are great, but the current choices are essentially "slow, but i can micro", "too fast for micro" and "unplayable" (not taking into account lagging games). 

The goal would be to make "Brisk" play at the fastest speed where you can still micro (albeit with increased effort).

A speed between normal and faster would be great for a few things, IMO. 

**League matches:** I believe currently the RAGL rules allow the home player to choose normal or faster when playing their "home game", however, no-one chooses faster - likely cause of the fact its VERY hard to micro at all. a "Brisk" speed would allow a macro player to take back some of the micro advantage from a good micro player and help mix things up a bit by using game speed as a part of your tactic to beat another player.

**Streaming:** SoScared has used faster in the past when unknown players play on stream. This has been to ensure games get into the action quicker and are finished quicker (in case the players are terrible and or uninteresting to watch). It's essentially a very sensible choice for a streamer, but not fair to the players. Brisk may be a happy medium and a good solution to this.

**Time poor casual players:** We all have lives and jobs, between which we try to play as much OpenRA as possible. If "Brisk" becomes a reality, maybe i can fit another game into the time i have available to play that evening - while still retaining the core experience.

**Anti Lag for 1v1 games:** When playing people with suspicious latency, Brisk might be a good way to get an anti lag effect without game-breaking speed if the game does not lag (as opposed to using faster for this purpose).

**Tool for practicing your micro:** If you can learn to micro whilst on Brisk, you should see your normal speed game micro abilities improve!

I'm not sure how to express exactly how much faster I'm talking about, but I will put it in the following terms: At normal speed a nuke takes 9 mins to charge, on faster it takes 6:45. Brisk should be around 7:45-8mins to charge a nuke.

**Comment by FRenzy-OpenRA** [comment]
Good idea ! 

I think Faster = 133% and Fastest = 200% speed ? 
(durations are multiplied by 0,75 and 0,5 respectively)

Maybe around x0,85 for "Brisk" ? (115% speed)

**Comment by SMIFFGIG** [comment]
Or maybe just a slideable scale with the current options as pre-sets along the slider?

**Comment by 3Lucian** [comment]
I think a slider is too variable. god knows what sort of havoc it would cause for the dev team also.

**Comment by 3Lucian** [comment]
@FRenzy-OpenRA That would be the ideal starting point. I've now thought about this for a while, and I think the sweet spot will definitely be in the 10-20% range. But like anything, it will need to be tested by people. and I think how you do that is find a really good micro player and a equally good t0-t1 spammer or basepusher and find the speed where one is complaining and feeling overwhelmed, and dial it a notch back from there. I can already think of a few names, and I'm sure just the series of test games alone would prove a very interesting watch if we could get any of the top tier players involved.

Also, "brisk" may or may not be suitable for the actual name of the game speed - it was the best word i could come up with at the time.

"Fast-ish" actually appeals to me more now Ive had more time to dwell on this idea.

**Comment by 3Lucian** [comment]
Absolutely. Doesn't really matter what it's called, as long as it's clear that it's between normal and faster
