### ISSUE TITLE
More flexible objectives

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#12506]
In IRC, people have requested the following feature:

* Allow winning the game by completing any of the primary objectives (currently, you have to complete all of them)

Additionally:
* Hidden objectives that aren't visible in the UI
* 'Decorative' primary objectives that don't influence the outcome of the game when failed

**Comment by pchote** [comment]
Isn't this already possible with lua?  When any primary objective is complete deregister all the others, then the player should automatically win.

**Comment by obrakmann** [comment]
You can't 'de-register' objectives. Well, you could mark the others as completed as well in the callback, but that's not quite ideal, either. But yeah, there are ways to do this, but they won't look polished.

**Comment by abcdefg30** [comment]
It might sound weird... but I'd also like to have a way to let the player win the game when failing a primary objective. (Might be a different issue though.)

As example I've got this one Twisted Insurrection mission in mind, where you had to (iirc) escort a VIP to a evacuation zone. But as soon as you reach the destination, the transport gets destroyed by bombers and the mission ends (the VIP dying is part of the story). So you have accomplished the mission, but the objective "Escort the VIP safely to the extraction zone" being marked as "Successful" would seem odd to me.

Maybe we can do that with "unregistering" (so it doesn't get too messy)?

**Comment by obrakmann** [comment]
@abcdefg30: no, I see your point. The same would be useful for the gdi06 mission in TD, where you have to destroy the airfield, but only get scrambled orders and destroying any building will end the mission. We'd probably also need 'hidden' objectives that aren't visible in the UI for that. Will update the summary.

**Comment by abcdefg30** [comment]
> We'd probably also need 'hidden' objectives that aren't visible in the UI for that.

C&C Renegade used "Ternary Objectives". They'd be like Secondary Objectives, but only reveal themselves after being completed.

**Comment by obrakmann** [comment]
We'd probably not want to hardwire that, but make the reveal optional.

Also, I just realized that the first request that lead to this PR can actually be accomplished with a combination of hidden and decorative objectives. So that's the way I'll do this then, I suppose.

**Comment by abcdefg30** [comment]
Sounds good to me.

**Comment by abcdefg30** [comment]
This is possible nowadays.
