### ISSUE TITLE
OperRA crash in start

### ISSUE THREAD

**Issue by mirkas02** [OpenRA/OpenRA#12514]
LOG:
Date: 2016-12-27 16:54:17Z
Operating System: Windows (Microsoft Windows NT 6.1.7600.0)
Runtime Version: .NET CLR 4.0.30319.1
Exception of type `System.Reflection.ReflectionTypeLoadException`: Jeden nebo více požadovaných typů nelze načíst. Další informace získáte načtením vlastnosti LoaderExceptions.
   v System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   v System.Reflection.RuntimeModule.GetTypes()
   v System.Reflection.Assembly.GetTypes()
   v OpenRA.Exts.GetNamespaces(Assembly a)
   v OpenRA.ObjectCreator.<ObjectCreator>m__1(Assembly asm)
   v System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   v System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   v System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   v OpenRA.ObjectCreator..ctor(Manifest manifest, FileSystem modFiles)
   v OpenRA.ModData..ctor(Manifest mod, InstalledMods mods, Boolean useLoadScreen)
   v OpenRA.Game.InitializeMod(String mod, Arguments args)
   v OpenRA.Game.Initialize(Arguments args)
   v OpenRA.Program.Run(String[] args)
   v OpenRA.Program.Main(String[] args)

Please help, i love this game

**Comment by reaperrr** [comment]
Going by runtime version, it looks like you have only .NET 4.0 installed. OpenRA requires 4.5 by now, try installing 4.5 or newer:

https://www.microsoft.com/en-US/download/details.aspx?id=42642

**Comment by mirkas02** [comment]
Great, i thanks you.

**Comment by Mailaender** [comment]
Duplicate of https://github.com/OpenRA/OpenRA/issues/13773
