### ISSUE TITLE
Desert Bridge Water Sections sometimes don't fully repair

### ISSUE THREAD

**Issue by StormWingDelta** [OpenRA/OpenRA#12510]
Noticed this when playing on a map and tried to correct the issue and it seems if there's enough water sections like in this case: http://i.imgur.com/7xuqEvK.png it might just be the choice of tiles.

Also here's the original map I found this happening. http://resource.openra.net/maps/17878/#comments

This only seems to happen with the water sections placed by the map editor that cause this.

**Comment by pchote** [comment]
There is a specific destroyed bridge template.  If the bridge doesn't use this specific template for all cells connecting the broken ends then it won't be repairable.

**Comment by abc013** [comment]
I assume that are just errors in the map:
![openra-2016-12-25t224956298z](https://cloud.githubusercontent.com/assets/21260178/21473162/20879c7e-cafd-11e6-8996-42e1c3d8a494.png)

I've also tested the bridges on an own desert-map, they are working fine.

**Comment by StormWingDelta** [comment]
Yep noticed the tile selection error as well and got it mostly fixed, also noticed there's two different main segments to the undestroyed bridge that could have tripped the original maker up.

**Comment by pchote** [comment]
Closing as "not our problem".
