### ISSUE TITLE
Source won't compile

### ISSUE THREAD

**Issue by Captaintoottoot** [OpenRA/OpenRA#12529]
I've been following the guide at https://github.com/OpenRA/OpenRA/wiki/Compiling

The solution won't compile.  I get a errors like: "OpenRA\source\OpenRA.Game\Actor.cs(16,7,16,13): error CS0246: The type or namespace name 'Eluant' could not be found (are you missing a using directive or an assembly reference?)"

I'm thinking these compile errors are because the right dependencies aren't copied?  I wasn't able to do the make properly.  When I go to the command prompt and run "make.cmd dependencies" I just get the message " 'powershell' is not recognized as an internal or external command, operable program or batch file.

**Comment by pchote** [comment]
You must install powershell before running the script.

**Comment by Captaintoottoot** [comment]
I'm on Windows 7 which has powershell 2.0 I believe, which I didn't know.  I ran it from powershell and the message I got was:

"The term 'make,cmd' is not recognized as the name of a cmdlet, function, script file, or operable program.  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.  At line: 1 char: 9  + make.cmd <<<< dependencies

+CategoryInfo  : ObjectNotFound: (make.cmd:String) [], CommandNotFoundException
+FullyQualifiedErrorId  : COmmandNotFoundException"

**Comment by reaperrr** [comment]
I recommend installing PowerShell 4.0
https://www.microsoft.com/en-US/download/details.aspx?id=40855

I think that's what I did some years ago, because I'm on Win7 too and make.cmd works flawless here.

**Comment by GraionDilach** [comment]
There's also some systems where PowerShell execution is disabled at start and you have to enable it before running one.

http://www.howtogeek.com/106273/how-to-allow-the-execution-of-powershell-scripts-on-windows-7/

**Comment by Captaintoottoot** [comment]
GraionDilach:
I set the execution policy to unrestricted and still got the same message

 reaperrr:
At that link the only packages I see are for Windows 6.1 ad 8.1  none for 7?

All this browsing around the net has me wondering, has anyone released the openra code with all the dependencies already there, and it just compiles right off the bat?

**Comment by GraionDilach** [comment]
If the PowerShell command would work, then it'd compuile right off the bat.

**Comment by Captaintoottoot** [comment]
reaperrr:
I downloaded the Windows6.1-KB2819745-x64-MultiPkg.msu because that's what the instructions said windows 7 users need.  When I run it, it crashes and says "Installer encountered an error: 0x80070422  The service cannot be started, either because it is disabled or because it has no enabled devices associated with it."

**Comment by obrakmann** [comment]
Please take this to the forums, the subreddit or wherever else. This bug tracker is not meant for support requests.
