### ISSUE TITLE
Mod Help + Start Error

### ISSUE THREAD

**Issue by Ghazter** [OpenRA/OpenRA#12527]
I got this error while trying to install a new mod I'm developing:
[exception.txt](https://github.com/OpenRA/OpenRA/files/679375/exception.txt)

I have a feeling it has to do with the new  release-20161019 mod.yaml, but I can't figure out what's wrong.

**Comment by GraionDilach** [comment]
It has nothing to do with that.

You're using an SHP(TS) file without SpriteLoaders: ShpTS listed or you have saved an SHP(TD) file wrong in SHP Builder (when you save TD files in the 3.38 betas, you have to make sure the status bar says the game type is TD or RA before saving them otherwise it'll mix the file formats).

**Comment by Ghazter** [comment]
Do you know what file(s) exactly?  This is from the latest fresh install.
All I have done is copy the original ra mod and rename the copied folder.
After that it was all mod.yaml.

**Comment by abcdefg30** [comment]
What did you change inside mod.yaml? Maybe the `SpriteFormats`?

**Comment by Ghazter** [comment]
Not much. All I did was replace all occurances of 'ra' with 'RA-1.5'. I
haven't checked to see if I can't use those characters though, it didn't
occur to me.

**Comment by MustaphaTR** [comment]
I can't check the error message right now, is the error invaild characters.

Then solition is adding `$modsname: modsname` on mod yaml, other mods have similar stuff, just put under them.

**Comment by pchote** [comment]
There is no clear actionable path forward here, so closing.  Please file a new issue with new logs if this is still a problem!
