### ISSUE TITLE
Ideas: Map Editor Features:

### ISSUE THREAD

**Issue by 3Lucian** [OpenRA/OpenRA#12522]
**Ideas/Wishlist**

**Tile selection information**
Ability to select a group of cells and have the editor display dimensions in length and width and the amount of resources that are in those cells.

**A mirroring tool**
Highlighting a cell lists its a corresponding cell both the the map we're mirrored both vertically or horizontally.

**Build/Weapon radius display**
A build radius should be displayed when an conyard, defencive structure, etc are placed.

**Passable/impassable tile overlay**
Simple red/green see through over lay showing which tiles cannot be occupied (because of trees, other units, debris, etc)

**Ability to highlight and move cells - replacing them with blank terrain.**

**Ability to do a mirror/reverse of all selected items(tiles, actors, etc), both horizontally and vertically**

**Actual copy/paste clipboard, allowing other things to be adjusted before pasting. Instead of current system which is essentially a drag and drop copy.**

**An undo/redo feature**

**Change Map Property Interface**
add weather effects
change size
change tileset (snow, desert, etc)
change mod (will create a host of issues, but have some thoughts on how these can be solved)

**Tile editor - Ability to edit which tiles are passable.**
Fix road tiles that include a debris cell, etc.

**Tile art editor**
Simple image editor
I'm still on the fence about this one - I want some new tiles, and to change a few existing ones, but don't want to open the door to complete trash. Perhaps simply expanding the official tile-set is a better option - would like to hear thoughts on this.

**Ability to change whether a tile is passable or not**
Fix bad road tiles that have a unpassable debris cell in them.
Stop crates dropping in unwanted areas
Simplify mini map for players
balance maps easily
Fix weird cliff tiles that don't conform to 2x2 tiles

**Yaml editor**
Change unit values such as
weapon equipped
health
damage
veterancy
garrison-able/or not
etc etc

**Comment by netnazgul** [comment]
> Passable/impassable tile overlay
please add "Building placement" overlay too. Some tiles are passable by units, but cannot be built upon

**Comment by Mailaender** [comment]
Closing as this is too many things per ticket and contains duplicates such as #10076 plus many unrealistic goals way out of scope such as

> Simple image editor

or already existing ones like

> Tile editor

https://github.com/OpenRA/TilesetBuilder (though currently unmaintained and broken)

Some ideas are interesting. Please open individual tickets for them, but do a quick search first, if someone already posted the idea.

**Comment by FRenzy-OpenRA** [comment]
Can we add this idea (similar to "Passable/impassable tile overlay") : 
**"Buildable/unbuildable tile overlay"** 
(some debris are very hard to notice, and some are not obvious to map maker if they are buildable or not)

**Comment by Mailaender** [comment]
> Yaml editor

I opened a separate ticket for that https://github.com/OpenRA/OpenRA/issues/14506 as the idea is not bad.
