### ISSUE TITLE
Can't play multiplayer

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/OpenRA#12521]
once click "join" it will return to mod selector, only can play singleplayer and skirmish

**Comment by GraionDilach** [comment]
You probably picked a server which uses a different mod?

**Comment by cookgreen** [comment]
i choose three mods

**Comment by cookgreen** [comment]
each mod can't enter a server

**Comment by GraionDilach** [comment]
You're not using a development version, right? Development versions require `make version` to get a proper version string, also different game versions will also be prevented to play together.
