### ISSUE TITLE
Mod support for custom render circle

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#12539]
Hi, I began modding OpenRA and came up with this OP unit:

IRON:
...
	# Iron curtain generation action haha
	UpgradeActorsNear:
		Upgrades: invulnerability
		Range: 10c0
		Duration: 25
...

The iron curtain now GENERATES iron curtain effect to nearby units until it is destroyed :)

However, when I try to draw the range circle, I can't find any suitable effect module.
Candidates are

* RenderDetectionCircle : To use this I need to make the Iron curtain a detector.
* RenderJammerCircle : Iron curtain will become a radar jammer
* RenderShroudCircle : IC needs to be a shroud generator
* RenderRangeCircle : Most side-effect-less choice, as I can give the iron curtain a damageless weapon. However, it still has glitches as the player can select the structure and issue an attack order.

I think there should be a more generic RenderCircle option.

**Comment by pchote** [comment]
Take a look at https://github.com/OpenRA/OpenRA/wiki/Traits#withrangecircle.

**Comment by forcecore** [comment]
Thank you, I got it customized 👍
