### ISSUE TITLE
Upgrade ra2 mod error - Utility.exe crashed

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/OpenRA#12538]
I try to use OpenRA.Utility.exe to upgrade the ra2 mod, but Utility.exe crashed and noticed:
'System.NullReferenceException'

**Comment by obrakmann** [comment]
We'd need the complete stacktrace to figure out what went wrong.

**Comment by cookgreen** [comment]
did you guys need utility.log?

**Comment by cookgreen** [comment]
Received args: --upgrade-mod 20160508
System.NullReferenceException: An object reference is not set to an instance of the object。
   在 OpenRA.Mods.Common.UtilityCommands.UpgradeRules.UpgradeActorRules(ModData modData, Int32 engineVersion, List`1& nodes, MiniYamlNode parent, Int32 depth)
   In OpenRA.Mods.Common.UtilityCommands.UpgradeRules.UpgradeActorRules(ModData modData, Int32 engineVersion, List`1& nodes, MiniYamlNode parent, Int32 depth)
   In OpenRA.Mods.Common.UtilityCommands.UpgradeRules.UpgradeActorRules(ModData modData, Int32 engineVersion, List`1& nodes, MiniYamlNode parent, Int32 depth)
   In OpenRA.Mods.Common.UtilityCommands.UpgradeModCommand.ProcessYaml(String type, IEnumerable`1 files, ModData modData, Int32 engineDate, UpgradeAction processFile)
   In OpenRA.Mods.Common.UtilityCommands.UpgradeModCommand.OpenRA.IUtilityCommand.Run(Utility utility, String[] args)
   In OpenRA.Program.Main(String[] args) position c:\Repository\OpenRA\OpenRA.Utility\Program.cs:line 97

**Comment by pchote** [comment]
20160508 is almost certainly wrong, and will make the updater do unexpected things.  You need to give it the date that the rules actually target, which I assume will be sometime in October - December.

**Comment by cookgreen** [comment]
But which date i should give?

**Comment by pchote** [comment]
The RA2 mod doesn't document the engine date that it targets, so you'll have to work it out based on commit dates and trial and error.

**Comment by cookgreen** [comment]
I checked, last merged PR is 20170101, i tried this date, still error:
Failed to upgrade map valley
Error was: System.AggregateException: 发生一个或多个错误。 ---> OpenRA.YamlExcep
tion: ra2|rules/allied-infantry.yaml:26: There are no elements with key `AutoTar
get` to remove
   在 OpenRA.MiniYaml.ResolveInherits(String key, MiniYaml node, Dictionary`2 tr
ee, Dictionary`2 inherited) 位置 c:\Repository\OpenRA\OpenRA.Game\MiniYaml.cs:行
号 324
   在 OpenRA.MiniYaml.Merge(IEnumerable`1 sources) 位置 c:\Repository\OpenRA\Ope
nRA.Game\MiniYaml.cs:行号 274
   在 OpenRA.MiniYaml.Load(IReadOnlyFileSystem fileSystem, IEnumerable`1 files,
MiniYaml mapRules) 位置 c:\Repository\OpenRA\OpenRA.Game\MiniYaml.cs:行号 394
   在 OpenRA.Ruleset.MergeOrDefault[T](String name, IReadOnlyFileSystem fileSyst
em, IEnumerable`1 files, MiniYaml additional, IReadOnlyDictionary`2 defaults, Fu
nc`2 makeObject) 位置 c:\Repository\OpenRA\OpenRA.Game\GameRules\Ruleset.cs:行号
 93
   在 OpenRA.Ruleset.<>c__DisplayClass9.<LoadDefaults>b__3() 位置 c:\Repository\
OpenRA\OpenRA.Game\GameRules\Ruleset.cs:行号 107
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
   在 OpenRA.Ruleset.LoadDefaults(ModData modData) 位置 c:\Repository\OpenRA\Ope
nRA.Game\GameRules\Ruleset.cs:行号 134
   在 OpenRA.ModData.<.ctor>b__2() 位置 c:\Repository\OpenRA\OpenRA.Game\ModData
.cs:行号 83
   在 System.Lazy`1.CreateValue()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Lazy`1.get_Value()
   在 OpenRA.ModData.get_DefaultRules() 位置 c:\Repository\OpenRA\OpenRA.Game\Mo
dData.cs:行号 40
   在 OpenRA.Ruleset.LoadDefaultsForTileSet(ModData modData, String tileSet) 位
置 c:\Repository\OpenRA\OpenRA.Game\GameRules\Ruleset.cs:行号 145
   在 OpenRA.Map.PostInit() 位置 c:\Repository\OpenRA\OpenRA.Game\Map\Map.cs:行
号 394
   在 OpenRA.Map..ctor(ModData modData, IReadOnlyPackage package) 位置 c:\Reposi
tory\OpenRA\OpenRA.Game\Map\Map.cs:行号 379
   在 OpenRA.Mods.Common.UtilityCommands.UpgradeMapCommand.UpgradeMap(ModData mo
dData, IReadWritePackage package, Int32 engineDate)
   在 OpenRA.Mods.Common.UtilityCommands.UpgradeModCommand.OpenRA.IUtilityComman
d.Run(Utility utility, String[] args)
---> (内部异常 #0) OpenRA.YamlException: ra2|rules/allied-infantry.yaml:26: Ther
e are no elements with key `AutoTarget` to remove
   在 OpenRA.MiniYaml.ResolveInherits(String key, MiniYaml node, Dictionary`2 tr
ee, Dictionary`2 inherited) 位置 c:\Repository\OpenRA\OpenRA.Game\MiniYaml.cs:行
号 324
   在 OpenRA.MiniYaml.Merge(IEnumerable`1 sources) 位置 c:\Repository\OpenRA\Ope
nRA.Game\MiniYaml.cs:行号 274
   在 OpenRA.MiniYaml.Load(IReadOnlyFileSystem fileSystem, IEnumerable`1 files,
MiniYaml mapRules) 位置 c:\Repository\OpenRA\OpenRA.Game\MiniYaml.cs:行号 394
   在 OpenRA.Ruleset.MergeOrDefault[T](String name, IReadOnlyFileSystem fileSyst
em, IEnumerable`1 files, MiniYaml additional, IReadOnlyDictionary`2 defaults, Fu
nc`2 makeObject) 位置 c:\Repository\OpenRA\OpenRA.Game\GameRules\Ruleset.cs:行号
 93
   在 OpenRA.Ruleset.<>c__DisplayClass9.<LoadDefaults>b__3() 位置 c:\Repository\
OpenRA\OpenRA.Game\GameRules\Ruleset.cs:行号 107
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()<---

Failed to upgrade map xdustbowl
Error was: System.AggregateException: 发生一个或多个错误。 ---> OpenRA.YamlExcep
tion: ra2|rules/allied-infantry.yaml:26: There are no elements with key `AutoTar
get` to remove
   在 OpenRA.MiniYaml.ResolveInherits(String key, MiniYaml node, Dictionary`2 tr
ee, Dictionary`2 inherited) 位置 c:\Repository\OpenRA\OpenRA.Game\MiniYaml.cs:行
号 324
   在 OpenRA.MiniYaml.Merge(IEnumerable`1 sources) 位置 c:\Repository\OpenRA\Ope
nRA.Game\MiniYaml.cs:行号 274
   在 OpenRA.MiniYaml.Load(IReadOnlyFileSystem fileSystem, IEnumerable`1 files,
MiniYaml mapRules) 位置 c:\Repository\OpenRA\OpenRA.Game\MiniYaml.cs:行号 394
   在 OpenRA.Ruleset.MergeOrDefault[T](String name, IReadOnlyFileSystem fileSyst
em, IEnumerable`1 files, MiniYaml additional, IReadOnlyDictionary`2 defaults, Fu
nc`2 makeObject) 位置 c:\Repository\OpenRA\OpenRA.Game\GameRules\Ruleset.cs:行号
 93
   在 OpenRA.Ruleset.<>c__DisplayClass9.<LoadDefaults>b__3() 位置 c:\Repository\
OpenRA\OpenRA.Game\GameRules\Ruleset.cs:行号 107
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   在 System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)
   在 OpenRA.Ruleset.LoadDefaults(ModData modData) 位置 c:\Repository\OpenRA\Ope
nRA.Game\GameRules\Ruleset.cs:行号 134
   在 OpenRA.ModData.<.ctor>b__2() 位置 c:\Repository\OpenRA\OpenRA.Game\ModData
.cs:行号 83
   在 System.Lazy`1.CreateValue()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   在 System.Lazy`1.get_Value()
   在 OpenRA.ModData.get_DefaultRules() 位置 c:\Repository\OpenRA\OpenRA.Game\Mo
dData.cs:行号 40
   在 OpenRA.Ruleset.LoadDefaultsForTileSet(ModData modData, String tileSet) 位
置 c:\Repository\OpenRA\OpenRA.Game\GameRules\Ruleset.cs:行号 145
   在 OpenRA.Map.PostInit() 位置 c:\Repository\OpenRA\OpenRA.Game\Map\Map.cs:行
号 394
   在 OpenRA.Map..ctor(ModData modData, IReadOnlyPackage package) 位置 c:\Reposi
tory\OpenRA\OpenRA.Game\Map\Map.cs:行号 379
   在 OpenRA.Mods.Common.UtilityCommands.UpgradeMapCommand.UpgradeMap(ModData mo
dData, IReadWritePackage package, Int32 engineDate)
   在 OpenRA.Mods.Common.UtilityCommands.UpgradeModCommand.OpenRA.IUtilityComman
d.Run(Utility utility, String[] args)
---> (内部异常 #0) OpenRA.YamlException: ra2|rules/allied-infantry.yaml:26: Ther
e are no elements with key `AutoTarget` to remove
   在 OpenRA.MiniYaml.ResolveInherits(String key, MiniYaml node, Dictionary`2 tr
ee, Dictionary`2 inherited) 位置 c:\Repository\OpenRA\OpenRA.Game\MiniYaml.cs:行
号 324
   在 OpenRA.MiniYaml.Merge(IEnumerable`1 sources) 位置 c:\Repository\OpenRA\Ope
nRA.Game\MiniYaml.cs:行号 274
   在 OpenRA.MiniYaml.Load(IReadOnlyFileSystem fileSystem, IEnumerable`1 files,
MiniYaml mapRules) 位置 c:\Repository\OpenRA\OpenRA.Game\MiniYaml.cs:行号 394
   在 OpenRA.Ruleset.MergeOrDefault[T](String name, IReadOnlyFileSystem fileSyst
em, IEnumerable`1 files, MiniYaml additional, IReadOnlyDictionary`2 defaults, Fu
nc`2 makeObject) 位置 c:\Repository\OpenRA\OpenRA.Game\GameRules\Ruleset.cs:行号
 93
   在 OpenRA.Ruleset.<>c__DisplayClass9.<LoadDefaults>b__3() 位置 c:\Repository\
OpenRA\OpenRA.Game\GameRules\Ruleset.cs:行号 107
   在 System.Threading.Tasks.Task.InnerInvoke()
   在 System.Threading.Tasks.Task.Execute()<---

**Comment by cookgreen** [comment]
Please help!!!

**Comment by cookgreen** [comment]
@pchote

**Comment by cookgreen** [comment]
@pchote

**Comment by LinuxDonald** [comment]
@cookgreen i think pchote mean that you need the date of the lastest working version of openra on that ra2 worked before it get broken with changes in openra master.

**Comment by GraionDilach** [comment]
@cookgreen You shoulda sit down and figure out things on your own. The last upgrade rule applied to the RA2 mod would be the AttackSequence->DefaultAttackSequence rule IIRC, but tbh at this point it'll probably need someone with at least the level of an experienced modder to get it up'n'running again due to the upgrade->conditions rules and pretty sure not every one of them gets converted manually. I don't have time to push someone to that level currently nor I have the intention to tutor you, due to my previous explaining attempts constantly falling flat.

**Comment by cookgreen** [comment]
so what will me do? fix the yaml files myself? or just wait your guys fix?
