### ISSUE TITLE
Harkonnen death hand launch animation missing

### ISSUE THREAD

**Issue by ltem** [OpenRA/OpenRA#12537]
Hello, 

The animation/overlay of the death hand launch is missing in the OpenRA D2K mod. 
It looks like this in the original: https://youtu.be/dmflM70vtZI?t=5m18s 

The sequence is already captured (the asset browser is great) in mods/d2k/rules/sequences/structures.yaml ([LinkToLine](https://github.com/OpenRA/OpenRA/blob/bleed/mods/d2k/sequences/structures.yaml#L973)) but outcommented.

I played a little bit around and tried to copy/mimic the opening of the missile silo during the nuke launch from RA but I couldn't find out how the `active:`-key for the animation of the RA launch gets activated...Am I looking at the wrong spot?

It's just polish but I think the animation is cool :)

**Comment by GraionDilach** [comment]
IIRC this is due to that superweapon launches atm only support entire image changes (working like a With*Animation) while that animation is supposed to be an overlay but I might be wrong on this one.

**Comment by reaperrr** [comment]
Should be relatively easy to fix either way.
