### ISSUE TITLE
Can't start the Game

### ISSUE THREAD

**Issue by RayonDeLumiere** [OpenRA/OpenRA#12532]
Did try copying the file OpenRA.Mods.RA2.dll from %USERPROFILE%\Documents\OpenRA\mods\ra2\OpenRA.Mods.RA2\bin\Debug to %USERPROFILE%\Documents\OpenRA\mods\ra2.
[exception.txt](https://github.com/OpenRA/OpenRA/files/679985/exception.txt)

**Comment by pchote** [comment]
The RA2 mod isn't maintained here, please see https://github.com/OpenRA/ra2/issues.
