### ISSUE TITLE
Please don't update so quickly

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/OpenRA#12530]
RA2 mod needs time to follow your guys update,

**Comment by Mailaender** [comment]
Haha, no. Actually https://en.wikipedia.org/wiki/Release_early,_release_often is good and OpenRA development has already slowed down a lot https://www.openhub.net/p/openra as the contributer numbers are declining. The https://github.com/OpenRA/ra2 mod just needs a new maintainer.

**Comment by pchote** [comment]
The RA2 mod (and other mods that sporadically track bleed) need to declare the engine commit that they target.

**Comment by Mailaender** [comment]
I made some attempts towards that at https://github.com/OpenRA2 but that is also broken now.
