### ISSUE TITLE
Poor cursor render performance with many actors selected

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#12549]
On my system, when I have lots of actors selected (~400), moving the mouse cursor on clear terrain or the shroud outside the map bounds is still ~2 *render* ms more expensive than holding the mouse over the build menu.
Holding the mouse cursor over any actor while I have those 400 actors selected costs another 2 render ms, regardless of what animation is played and regardless of whether the tooltip is visible.

I suspect the cursor rendering is done for every selected actor, because when only a single actor is selected, there is no noticable performance difference between these cases.

**Comment by pchote** [comment]
This is almost certainly not the *actual* cursor rendering, but instead the code that works out what cursor type to display (which needs to check all the order issuing traits on all the selected actors).

**Comment by reaperrr** [comment]
Ok, I somewhat suspected that might be the case, but it puzzled me that the ms went to Render instead of Tick.
