### ISSUE TITLE
PlaceBuildingOrderGenerator overlay should be centered on a building's corner cell

### ISSUE THREAD

**Issue by maven27135** [OpenRA/OpenRA#12541]
When about to place buildings, there is a shaded/patterned guide that shows you how the building will be placed if you click to put it on the map. I don't know what you call this, but I'll call it the shaded placing guide, or SPG, here.

Using the SPG can cause unintended placing of buildings because the cursor focuses irregularly on the SPG, instead of a reliable and fixed section. I believe (but I don't know) that the cursor is supposed to focus the SPG in the middle tile, but this causes errors when buildings aren't 3x3, like in Dune 2000.

I ask that the cursor focuses on the upperleftmost OR bottomrightmost tile/section of the SPG, regardless of it actually being a part of a building's needed space.

Example:

X = shaded area which the building will occupy
O = shaded area which the building will occupy, with the cursor on it

```
 X 
XXX
XOX
XXX
```

```
OX 
XXX
XXX
XXX
```

Or maybe preferably..

```
 X 
XXX
XXX
XXO
```

**Comment by maven27135** [comment]
Thanks for the rename, probably makes more sense for the devs. :)

**Comment by pchote** [comment]
> Using the SPG can cause unintended placing of buildings because the cursor focuses irregularly on the SPG, instead of a reliable and fixed section.

Do you have any images demonstrating this?  I'm strugging to visualize how moving the fixed point from the center of the actor to the center of an arbitrary cell changes anything.  In both cases the actor is fixed relative to the cursor, so at best you're just moving the boundary for cursor weirdness from one place to another.

**Comment by PunkPun** [comment]
I'm guessing this should be closed due to inactivity
