### ISSUE TITLE
deploy to upgrade with cooldown and duration

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#12542]
https://github.com/OpenRA/OpenRA/wiki/Actor-Upgrades

I have looked at upgrades and traits but it seems that I can't have a deploy special ability with cooldown, as in RA3.

What I have in mind is :
	DeployToUpgrade:
		DeployedUpgrades: invulnerability
		Duration: 500
		CanDeployOnRamps: yes
		ChargeDelay: 1000
self iron curtain ability, which is a Soviet equivalent of self chronoshifting.

* It has to have a Duration, otherwise the unit must "undeploy" to get un-ironcurtained.
* It must have a charge delay, otherwise tanks can permanently re-ironcurtain itself as much as the player wants.

This feature may support many other features such as
* Over-charging tanks so that they may gain rate of fire bonus for a brief moment
* Transform into something for a while
* Self heal rapidly for a few seconds, like Tsunami tanks in RA3

**Comment by GraionDilach** [comment]
I am okay with anyone shifting https://github.com/GraionDilach/OpenRA.Mods.AS/blob/master/Traits/Conditions/GrantTimedConditionOnDeploy.cs to upstream to fulfill this request. I won't do it myself though.

**Comment by GraionDilach** [comment]
Note to whoever who would do this c'n'p-styled inclusion - it currently uses `GrantConditionToDeploy` as it's internal order name because I didn't wanted to duplicate `UnitCommandWidget` for this, so you have to fix that and include the unique order name in UCW's `PerformDeploy` list.

**Comment by MustaphaTR** [comment]
This i think is also required for Timed Cloak ability of D2K's Ordos Saboteurs.

**Comment by abcdefg30** [comment]
Should be closed by #20824.
