### ISSUE TITLE
MCV deploy anywhere bug 

### ISSUE THREAD

**Issue by Omnomon** [OpenRA/OpenRA#12558]
If you shift queue two move commands and then the deploy command (click on MCV), then release shift, the MCV will not only deploy instantaneously, but it will ignore all units and terrain blocking the deployment. 

https://www.mediafire.com/?4nc0z7478qijok2

Some bugs are good for the game, but if this one catches on, it's gamebreaking.

**Comment by pchote** [comment]
This is a high priority for the next release, but don't think it needs to be done before the next playtest.  This *should* end up being a simple 2 or 3 line fix, so can be cherry picked to the prep branch.

**Comment by pchote** [comment]
The trick here is to queue up a move activity between the [CallFunc being queued](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Transforms.cs#L122) and it actually executing.  We then have:

1.  The deploy sanity check runs, finds that the location is valid, and queues the Transform activity *after the already queued move activities*.
2.  The move activities run, and the unit drives to a location that is no longer valid.
3.  The transform runs, deploying the MCV at a now bogus location.

The proper fix here is to rewrite this whole thing using @obrakmann's new parent/child activity plumbing, but for this next release we can go with the much safer workaround of cancelling the activity queue just before queueing the transform.
