### ISSUE TITLE
TS needs balance

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/OpenRA#12556]
TS's Ai is too unbalanced, bot attack player endlessly, i have no time to build defense.
PS: why did not TS open source?

**Comment by jaZzKCS** [comment]
1) It is far too soon to talk about balance at this point in time as there is a vast list of game mechanics not implemented yet. A lot of units - though already present in the game - are not fully operational, yet. As is the terrain for that matter, but these are just a few examples.
2) Pretty much the same reason as above...

**Comment by obrakmann** [comment]
> PS: why did not TS open source?

It IS open-source, it's just unreleased.

As such, it will be balanced when the time comes.
