### ISSUE TITLE
Idea: Server can be filtered by mod

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/OpenRA#12555]
As we all know, when we play multiplayer, it will show a couple list of servers including many mods, but we didn't know which mod the server run. 
So we need a filter can filter the server by mod, OpenRA can only show the server that sane as mod that we are running like Source-Engine Game, or we can show the whole server list but need a column in the server browser listview to show the mod that the server is running like Mount&Blade Series

**Comment by jaZzKCS** [comment]
I am confused. We already have this. The first games listed will always correspond to the mod that is currently loaded. The "other 2" + servers running third party mods are displayed down below in the serverlist, each in their own list, clearly showing you which mods are being played.

**Comment by obrakmann** [comment]
The UI already differentiates between mods, filtering is unnecessary. Are you sure that you are running a current version of OpenRA?

**Comment by rob-v** [comment]
I would like to filter by mod. There are atm 22 mods. Each can have games in various state. To find your mod(s) after each refresh can be tedious. There isn't too much free space, but one idea:
![obrazok](https://cloud.githubusercontent.com/assets/16348750/25143708/b91b0e22-246b-11e7-8735-b7a918642b90.png)
