### ISSUE TITLE
RA. E3 damage values not working.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#12578]
Im not entirely sure how this can be fixed or if it should be fixed since this could cause a major strain on the balance right now and that there aren't any complaints on E3.

The damage values on the E3 vs armor types is incorrect and not taking effect from its main damage.

E3 base damage of 40.
None: 90
Wood: 75
Light: 60
Heavy: 25

11 shots vs Heavy Tank 440 damage. HP 550

6 shots vs APC 240 damage. HP 300

18 shots vs Mammoth Tank 720 damage. HP 900

9 shots vs Medium Tank 360 damage. HP 450

I haven't tested all the units but I have done things such as putting vs light value to 1 and attacking a V2. Made no change. Again, not sure how this can be done as it may effect balance greatly and people seem to be fine with how E3 damages work now.

SELF:

This is a reminder for me to look at both Primary and Secondary attributes rather then seeing Primary as the valid target ground. Kudos to FrameLimiter for pointing out my fail

**Comment by FrameLimiter** [comment]
I think you're looking at the E3's AA weapon the RedEye.  The E3's ground weapon is the "Dragon" which has:
base damage of 50.
None: 10
Wood: 75
Light: 35
Concrete: 50
