### ISSUE TITLE
Carryalls can still pick up unit after unit somehow changed owner (e.g. hijacking)

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#12575]
Similar problem we had with engineers i guess, they were repairing enemy structures.

In my D2K mod i added a Hijacker unit for  Smugglers, i hijacked an enemy harvester when a carryall came to pick it up, but carryall still did that and put it to their refinery.

If owner of the waiting unit changes, carryall's order should be canceled.

**Comment by ltem** [comment]
Can confirm. 
However I got the ownership over the enemy harvester via a deviator missile.

**Comment by MustaphaTR** [comment]
I took a look to the code and i think i know how to solve this. Will test and file a PR if it works when i back home.

But still a proper Stance check for Carryalls would be better. Also we could make Emperor: BfD style carryalls that can carry enemy units.
