### ISSUE TITLE
Reordering the list of units/structures in .yaml files

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#12585]
I find it odd that for example RA structures.yaml start with Missile Silo, or vehicle.yaml has V2 etc. I think we those are left at where they was added at first place and never changed. I think .yaml files should use the same order with `BuildPaletteOrder:`s of units, so it can be easier to find stuff when we look for.

**Comment by reaperrr** [comment]
I think the other mods are (mostly) fine, but RA's actor yaml files are indeed rather messy in that regard.

**Comment by MustaphaTR** [comment]
If others agree too, i can take a look to fixing that today evening.
