### ISSUE TITLE
Capture the flag game mechanics.

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#12594]
for a game like this the only idea that comes to mind is attaching a shp to a shp,and be able to "pick" up a shp. For example,a unit enter the same cell with the flag,then the unit picks up the flag until it enters his own flag cell,then it "drops" the flag and the enemy flag is returned to its previous position.
Like ordinary c.t.f. games in fps.
and like koty have its own GUI elements like scoring for victory,max number of captures set by the author of the map.

it can be like this:

E1:
carryflag: true
drobflagondeath: true

ctf:
ctfmax: 6

something like that.

**Comment by airetaM** [comment]
Something like that?
http://resource.openra.net/maps/15151/
http://resource.openra.net/maps/17948/

**Comment by KOYK** [comment]
no that is capture the point. in capture the flag you must take the enemy flag from the enemy base,and return it to your own flag,at your own base.having your flag at enemy hands prevent you from scoring.If the unit\player that holds the flag dies,then the flag is dropped to the ground and can be repicked by the enemy or automatically return to its home base if picked by the team that owns the flag.

**Comment by WolfGaming** [comment]
You should already be able to do this by adding a WithSpriteBody or WithFacingSpriteBody on every unit in the map and have a condition on it that is activated through LUA when you pick up the flag.

**Comment by KOYK** [comment]
It wont be fixed\added, closing it.
