### ISSUE TITLE
External Condition whitelist crashes.

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#12620]
So, I am using Grant external condition to stack levels of a condition on actors, when they reach the max level possible by the condition, something fancy happens (kudos because this wasn't possible with the upgrade system), in this case your guys will be able to fire a final projectile that has the change onwer warhead.

The issue here is that the External Conditions trait crashes if I don't give every single condition a clear use, like what you can see here for example, I am forced to use the level conditions for dummy multipliers, if I remove a single range multiplier, then the game will crash after the first BoardingPod projectile reaches it's target.

The exception is below the template code.

```
^Boardable:
	TemporaryOwnerManager:
	StackedCondition@Boarding:
		Condition: Boarded
		StackedConditions: Boarded2, Boarded3, Boarded4, Boarded5, Boarded6
	ExternalConditions@Boarded:
		Conditions: Boarded, Boarded2, Boarded3, Boarded4, Boarded5, Boarded6
	RangeMultiplier@Boarded:
		RequiresCondition: Boarded
		Modifier: 100
	RangeMultiplier@Boarded2:
		RequiresCondition: Boarded2
		Modifier: 100
	RangeMultiplier@Boarded3:
		RequiresCondition: Boarded3
		Modifier: 100
	RangeMultiplier@Boarded4:
		RequiresCondition: Boarded4
		Modifier: 100
	RangeMultiplier@Boarded5:
		RequiresCondition: Boarded5
		Modifier: 100
	RangeMultiplier@Boarded6:
		RequiresCondition: Boarded6
		Modifier: 100
	Targetable@Boardable:
		TargetTypes: Boardable
		RequiresCondition: Boarded6

BoardingPodDebuff:
	Inherits: BoardingPod
	InvalidTargets: Boardable
	ValidTargets: CapitalShip, Frigate, Corvette, Ground, Air, AirHit
	Warhead@1Dam: SpreadDamage
		InvalidTargets: Boardable
		ValidTargets: CapitalShip, Frigate, Corvette, Ground, Air, AirHit
	-Warhead@4OwnerChange: ChangeOwner
	Warhead@Boarded: GrantExternalCondition
		Range: 350
		Duration: 350
		Condition: Boarded
		InvalidTargets: Boardable
		ValidTargets: CapitalShip, Frigate, Corvette, Ground, Air, AirHit
		AffectsParent: True
		ValidStances: Enemy, Neutral
```

```
Nomad Galaxy Mod at Version {DEV_VERSION}
on map 612c38a8e91b973e3a7c4034682fd31da5b621f7 (FFA Test by Nolt).
Date: 2017-01-24 13:15:15Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.Collections.Generic.KeyNotFoundException`: La clave proporcionada no se encontró en el diccionario.
   en System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   en OpenRA.Mods.Common.Traits.ConditionManager.OpenRA.Traits.ITick.Tick(Actor self)
   en OpenRA.World.<Tick>b__a(TraitPair`1 x) en c:\Users\Alfred\Documents\OpenRA-Bleed\OpenRA.Game\World.cs:línea 345
   en OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text) en c:\Users\Alfred\Documents\OpenRA-Bleed\OpenRA.Game\WorldUtils.cs:línea 75
   en OpenRA.World.Tick() en c:\Users\Alfred\Documents\OpenRA-Bleed\OpenRA.Game\World.cs:línea 0
   en OpenRA.Game.InnerLogicTick(OrderManager orderManager) en c:\Users\Alfred\Documents\OpenRA-Bleed\OpenRA.Game\Game.cs:línea 556
   en OpenRA.Game.LogicTick() en c:\Users\Alfred\Documents\OpenRA-Bleed\OpenRA.Game\Game.cs:línea 580
   en OpenRA.Game.Loop() en c:\Users\Alfred\Documents\OpenRA-Bleed\OpenRA.Game\Game.cs:línea 707
   en OpenRA.Game.Run() en c:\Users\Alfred\Documents\OpenRA-Bleed\OpenRA.Game\Game.cs:línea 747
   en OpenRA.Program.Run(String[] args) en c:\Users\Alfred\Documents\OpenRA-Bleed\OpenRA.Game\Support\Program.cs:línea 134
   en OpenRA.Program.Main(String[] args) en c:\Users\Alfred\Documents\OpenRA-Bleed\OpenRA.Game\Support\Program.cs:línea 41
```

**Comment by pchote** [comment]
I can't reproduce this on bleed (adding `StackedCondition` to TS's emp disabling).  Can you please come up with a set of changes to reproduce this in our default mods?

**Comment by GraionDilach** [comment]
Eh... I told @ABrandau to open the ticket but not about the crash though since I agree that is likely a modder error. However, the dummy (rangemultipliers here) condition receivers are apparently needed to prevent lint errors if a condition would only trigger an actual effect in say the 3rd level and beyond.

**Comment by pchote** [comment]
Good point.  The simplest fix would be to switch to a less clear but more flexible dictionary syntax:
```yaml
StackedCondition:
	StackedConditions:
		2: something-happens-at-level-2
		6: something-new-happens-at-level-6
		7: something-new-happens-at-level-7
```

**Comment by ABrandau** [comment]
Sorry for the delay, I cannot reproduce the bug on vanilla ra1, and since your idea of placing the same upgrade on many levels works, I'd rather say you could keep everything as it is, thanks.

This is what I tried, and it works, I do not understand why (tested on ra1).

Apply this on the test unit.

	KillsSelf@asd:
		RequiresCondition: Suicide5
	StackedCondition@asd:
		Condition: Suicide
		StackedConditions: Suicide1, Suicide2, Suicide3, Suicide4, Suicide5
	ExternalConditions@sdgfdgs:
		Conditions: Suicide, Suicide1, Suicide2, Suicide3, Suicide4, Suicide5
	WithDecoration@asfdsa-1:
		Image: rank
		Sequence: rank-veteran-1
		Palette: effect
		ReferencePoint: Bottom, Right
		RequiresCondition: Suicide
		ZOffset: 256

Apply this on the weapon of any unit (I went for rifleman).

	Warhead@Suicide: GrantExternalCondition
		Range: 1c0
		Duration: 500
		Condition: Suicide
		ValidTargets: Ground, Infantry, Vehicle

So, I guess there must be an specific trait doing something somewhere, I will close this issue and re open it once I find what causes it, thanks.

**Comment by GraionDilach** [comment]
@ABrandau you should rename this issue and reopen it to be about the StackedCondition needs dummy consumers if you want to activate a condition above certain levels. >_>

**Comment by pchote** [comment]
No need.  I have already filed #12657 to address that.
