### ISSUE TITLE
Menu is too small

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#12629]
Can we make the menu bigger, I can't really see anything.
![openra game_2017_01_26_11_54_57_948](https://cloud.githubusercontent.com/assets/7798635/22328824/7b848f7c-e3be-11e6-8877-98c682f7a35b.png)

**Comment by StexoO** [comment]
The text boxes ?

**Comment by Snurre86** [comment]
And audio devices and the scroll has only 5 line and ... and ...

**Comment by pchote** [comment]
Anecdotal evidence shows that a fair number of openra players use an abysmal 1366 x 768 screen resolution (note: we really should include this in the sysinfo survey), and our ingame menus are designed to accomodate that.  Implementing and then maintaining flexibly sized windows would be a significant amount of work that nobody so far is willing to put in.

**Comment by Snurre86** [comment]
the menu is 600x450

**Comment by PunkPun** [comment]
Is this still relevant?

**Comment by pchote** [comment]
No, the settings menu overhaul for the next release should have resolved this.
