### ISSUE TITLE
Include window size in system information prompt.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#12630]
Having some statistics on screen resolutions / window sizes would be very useful when discussing issues like #12629.  We are already bumping the sysinfo version with the next release, so we should include this too.

**Comment by ROCKNROLLKID** [comment]
While including resolution in sys info would be useful in some cases, I am not sure why it should be a reason to decide whether https://github.com/OpenRA/OpenRA/issues/12629 should be done or not. You recently did HiDPI support and you didn't base that off any statistics, so why suddenly do it for here? I have a 4K display and the UI is pretty small on my screen, so I think doing some type of UI scale would be nice to have.

**Comment by pchote** [comment]
This has nothing to do with #12629 directly, but with having enough information to make informed decisions before increasing our minimum required specifications if/when we are forced to make that choice.  HiDPI support improves things for people with high specced machines but doesn't affect anything at the low end.
