### ISSUE TITLE
Engineer tries to repair enemy buildings

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#12639]
When a building has been captured by an enemy and you haven't had vision of it since, an engineer will try to repair the building as-if it were still your building, i.e. with oil derricks, see example video taken from https://www.twitch.tv/videos/117999892.

http://sendvid.com/lfj5elhr

**Comment by pchote** [comment]
This has been fixed for the next release by #12535

**Comment by AMHOL** [comment]
My bad, thanks
