### ISSUE TITLE
Option to play or spec

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#12642]
Option to jump in and play as a spectator when a player leaves.

"Player" left do want to play in his place?

Will also help somewhat on spectators being auto kicked before game start.

**Comment by obrakmann** [comment]
Duplicate of #3255 and #6131.

**Comment by Snurre86** [comment]
not really a duplicate as you don't rejoin the game.

**Comment by obrakmann** [comment]
Doesn't matter, spectators still need the full state of the game, so just jumping into a running game doesn't work.
