### ISSUE TITLE
Idea - Horizontal Launch angle for missile and bullet.

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#12651]
A small idea that could work well in fancy tanks or maybe even ships, missiles could be fired from an angle away from the front of a unit to create more diversity, would only be useful for modders. 

an example can be seen here in the first 5 seconds, see the yellow ship. https://www.youtube.com/watch?v=PGxgwv61RF4 

The same effect in bullet could be used to make weapons damage units in a cone in front of them, or other things.

**Comment by forcecore** [comment]
Sounds like RA2 aegis 👍

**Comment by pchote** [comment]
This has always been possible.  Take a look at the LocalYaw field on Armament.
