### ISSUE TITLE
D2K - Upgrades require Construction Yard

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#12665]
They shouldn't. It actually is easy to fix by moving upgrade production to `Player:` actor. But there is a small problem with it. If i do that After deploying the MCV at start, Upgrade Menu is shown rather than Structure. This is because `ProvidesPrerequisite:` trait takes effect before the `Production:` trait. `Production`, afaik, waits for the buildup to finish before taking effect, while `ProvidesPrerequisite:` doesn't.

**Comment by reaperrr** [comment]
>  while ProvidesPrerequisite: doesn't.

In my opinion, changing that would probably be the most reliable fix for this issue.

**Comment by GraionDilach** [comment]
I don't like that implication though - if both undeployed and deployed states provide the same prereq, but not the deployanimation, the players would complain about legit bugs when their build orders become noisy. Examples where such a setup was used was YR Slave Miner and RA3 Empire of the Rising Sun.

**Comment by MustaphaTR** [comment]
@GraionDilach is right, that would break my Stailn's Fist too. The best is to add a tag to set that on `ProvidesPrerequisite:`

**Comment by pchote** [comment]
In an ideal world those units would all be done using conditions instead of actor replacement, so there wouldn't be an issue.

**Comment by MustaphaTR** [comment]
Instead of moving upgrades to player, we can try to allow all upgradeable structures to produce upgrades. I'll test how that works out.
