### ISSUE TITLE
Unit slow crush trait.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#12661]
This has been around for fast moving units and has made mention. Is it possible to create a slow crush trait?

Units moving to crush infantry are slowed by half speed with the trait which gives infantry a chance to move out from the way. (APCs, Phase Transports are a few examples).

Having this as a trait would allow heavy tanks and the likes to remain at normal speed for their crushes.

Reason is units that move faster have a higher chance to crush infantry despite the dodge chance because the unit is on the move.

**Comment by GraionDilach** [comment]
I don't see how "slowing-down the unit if the order is a crush order" would be good at all - such an effect would make no difference if I start microing out infantry crushes by ordering the crusher to move to the cell beyond the infantry from the crusher's POV. Something one has to do in RA2 because that one has this as a locomotor bug, actually.

My opinion on this is that slowing down these fast units when they hit the first infantry would be the best way to resolve this because that wouldn't act erratic.

**Comment by AoAGeneral** [comment]
Thats essentially the point.

When a fast unit doesn't get slowed down upon crushing a unit they crush more effectively. These units that do cell to cell turns crush entire packs of 5 easily and units that transition to a new cell do not roll the RNG of dodge chance because they are on the move.

So the unit that makes contact with the first set of infantry that has this trait can slow down a bit which at least gives the infantry a chance to dodge.

**Comment by GraionDilach** [comment]
I am guessing what you want is https://github.com/GraionDilach/OpenRA.Mods.AS/blob/master/Traits/Conditions/GrantExternalConditionToCrusher.cs with a condition which applies a slowdown, but I won't shift this one to upstream incase  I am getting blamed for not doing what you want.

**Comment by AoAGeneral** [comment]
I do like the customized ticking on how long the unit will be slowed for and can be changed as well. @SoScared pinging.

**Comment by SoScared** [comment]
Hi! Yeah we've been daydreaming about this for some time :)

Slowdown **speed** and **duration** sounds like necessary basics.

Having the trait available for wall/fence and perhaps even vehicles would open up some new exciting possibilities.

**Comment by pchote** [comment]
I suspect that you'd want to be able trigger conditions on `WarnCrush` too / instead.

**Comment by GraionDilach** [comment]
My trait was implemented for the GLA salvage mechanic with the burning husks having this trait to grant salvage upgrades as a pickup mechanic (because crates couldn't be used for this role due to reasons). I definitely wouldn't want to trigger conditions on WarnCrush.
