### ISSUE TITLE
General tunnel issues

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#12662]
- [x] Actors in tunnels (ground-level, underground, in-air) should not be damaged by `DamagedByTerrain` #12666
- [ ] We should probably not show the healthbars of damaged non-friendly actors while underground or in ground-level tunnels
- [x] Actors should be (if chosen by the rules author) forced out of tunnels when idle

**Comment by Phrohdoh** [comment]
Here is [a solution for the first issue](https://github.com/OpenRA/OpenRA/compare/bleed...Phrohdoh:damagedbyterrain-respect-tunnels) but I can't promise it is the right way to do this.

**Comment by pchote** [comment]
A simpler fix is to disable it using a condition, which is what I did for several other traits.  We want to avoid having to add a code dependency from every trait onto the tunnel logic.

**Comment by GraionDilach** [comment]
Issue 2 is complex, units in tunnels were always shown by health bar in TS and detected enemy subterranean units also revealed themselves via them.

**Comment by pchote** [comment]
I was planning on repurposing our RA GPS icons (but not the code) for friendly units in tunnels and enemy units detected with sensors.

**Comment by Phrohdoh** [comment]
@pchote That would indeed be much easier.
I'll give the DamagedByTerrains `!in-tunnel` condition.

**Comment by pchote** [comment]
Point 3 was solved by #13149, and the second point is covered by #12913.
