### ISSUE TITLE
Idea: New Trait - Airship

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/OpenRA#12674]
The problem in ra2 mod is the Kirov Airship, In ra2, Westwood makes a new kind of aircraft, it is the Kirov Airship, the Kirov will throw the bombs to enemy units directly not like the Aircraft in OpenRA, it is not like the AttackBomber either.
In ra2 mod, we use Aircraft to describe the Kirov, but it is not enough, so we need a new trait to describe the Kirov 
Yes, there is no Airship in original OpenRA, but i think we need to give support to the people who want to create something like Kirov

Of course, we can give more options to make people implemt their own style Airship, not only Kirov, it can be Zeppelin

**Comment by GraionDilach** [comment]
Wrong, wrong and ohboy, this is so wrong. Someone should close this ticket, it's such wrong.

If one wants to completely replicate the Kirov's bombing path behaviour, use AttackHeli with a relatively huge FacingTolerance (I'm using 30), give the Kirov the actual GravityBomb weapon with the range from where it should start bombing it's path (so something like 2-3 cell ranges) AND give the Kirov a dummy weapon with a really small range which will trigger the Kirov to still try to closing on the target while attacking. The support is already there.

**Comment by cookgreen** [comment]
@GraionDilach but how to slow down the Kirov's speed when we make it as a attackheli?

**Comment by cookgreen** [comment]
And when i try to make it as a attackheli, OpenRA says error:`Parent type ^AttackHeli not found`

**Comment by WolfGaming** [comment]
To your first question, this can be done by using a condition on AttackHelicopter and a SpeedModifier.
And to your second problem if you are having this problem I don't think you know how the yaml works and I recommend you have a better look at how it works.
You are trying to inherit from a definition that isn't there @GraionDilach was talking about a trait called AttackHelicopter which has no connection to inheritance in the yaml (aka Inherits: )

**Comment by cookgreen** [comment]
@WolfGaming 'AttackHeli' is from the wiki, not my creation
 <img src=http://i67.tinypic.com/aoqdzt.jpg />

**Comment by pchote** [comment]
Please keep ra2 mod specific discussion over at https://github.com/OpenRA/ra2/.

**Comment by cookgreen** [comment]
@pchote please change the 'AttackHeli' to 'AttackHelicopter ' in wiki

**Comment by WolfGaming** [comment]
Nvm my bad, it is AttackHeli https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Air/AttackHeli.cs you were using it incorrectly however.

**Comment by GraionDilach** [comment]
@cookgreen Please learn how to comprehend information out of the manual. 

AttackHeli has nothing to do with a unit's speed. That's defined on the Aircraft trait. This is like the umpteenth time I am explaining things to you with you failing them to understand and darwing wrong conclusions IF you even draw a conclusion.

My conclusion so far is that you're lacking the mindset to actually understand what you are trying to talk about and I really, really advise to pick it up before opening a new issue.

**Comment by ibrokemypie** [comment]
@GraionDilach So how would one get the kirov to keep moving till in range of the dummy weapon? Tried a few things but it still seems to just stop before the target...
