### ISSUE TITLE
Commanding multiple helicopters to land results in stall of commands

### ISSUE THREAD

**Issue by ibrokemypie** [OpenRA/OpenRA#12701]
If you select a group of helicopters and command them to land at a helipad, one may land and stay there, while the rest just hover above indefinitely.

**Comment by forcecore** [comment]
Kinda glitchy, but if you set rally point for the helipad then the helis will proceed to reload the next unloaded heli.

**Comment by forcecore** [comment]
I just remembered that this applies to service depots too. If you repair multiple tanks the repaired tank wont get out of the way for.other tanks unless the rally point for FIX is set.

**Comment by marsjaninzmarsa** [comment]
> command them to land at a helipad, one may land and stay there, while the rest just hover above indefinitely.

AFAIR same behavior as in original TD. 😜

**Comment by PunkPun** [comment]
Aircraft behaviour had seen some major changes, I'm not sure this is relevant

**Comment by PunkPun** [comment]
This was fixed with aircraft activity rework. There are still issues with ~~rearming~~ repairing but that's covered in #18313
