### ISSUE TITLE
More rank priority for servers with spectators only in the MP Lobby.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#12707]
For various purposes like hosts looking for players in competitions and attracting players testing out new maps. Ranking servers with spectators only above completely empty servers would be useful.

**Comment by jaZzKCS** [comment]
As in "lots of specs waiting for possible players..."?
:+1: all the way.

**Comment by SoScared** [comment]
Currently we have to occupy a player spot until someone else pops in and takes it :)

**Comment by SoScared** [comment]
Wow great!! Thanks a ton @pchote !
