### ISSUE TITLE
Helicopters do not repair at helipad

### ISSUE THREAD

**Issue by ibrokemypie** [OpenRA/OpenRA#12700]
They will land, reload and take off, but will not repair

**Comment by forcecore** [comment]
I'm sure it is intentional. That's what exactly happens in RA1, they are fixed at the service depot.
Even migs get repairs at the service depot in RA1.

**Comment by ibrokemypie** [comment]
ah, understood

**Comment by pchote** [comment]
Note that the helicopters in TD *do* repair at the helipad.  The underlying code allows each mod to set this up however they want.
