### ISSUE TITLE
Ore truck glitch (Actually a question about SequenceActivities)

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#12715]
This glitch is hard to pull off but here it is:
https://youtu.be/S4kc_d4OW4Y

* Normally when you order a full harvester to mine ore, it will return to the refinery.
* However, if you move the ore truck to where it unloads then order it to mine ore, it tries to reach the refinery but will not unload. (Being already there at the docking position causes the bug)

Not usually a problem but when you try to mod and try to make "Marv", which virtually "dock" by skipping drop-off location check, you get to skip the follwing SequenceActivities() call:

```csharp
DeliverResources.cs:Tick()

		if (self.Location !=  proc.Location + iao.DeliveryOffset)
				{
					var notify = self.TraitsImplementing<INotifyHarvesterAction>();
					foreach (var n in notify)
						n.MovingToRefinery(self, dest, this);

					return ActivityUtils.SequenceActivities(movement.MoveTo(dest, 0), this);
				}
```

If you get to skip this SequenceActivities(), you get the glitch shown as the video above.

Why are all the actions queued by iao.OnDock() not working if SequenceActivities is skipped?
What does SequenceActivities do? Not too sure as it has no comments in the code or documentation.

I am 99% sure it is SequenceActivities.
When I replace the if condition in the above code to something else (such ase actor's facing) and let the actor turn its facing with return ActivityUtils.SequenceActivities(new Turn(self, 0), this); you get no problem. (Unless the harvester is facing exactly 0 at the time of trying to dock)

**Comment by Smittytron** [comment]
I believe this is the same issue that cost Medium Tank in the King of the Hill Tournament vs Lorrydriver.
https://www.twitch.tv/videos/117999892 (truck gets stuck around 3:33:30 after a lag spike)

**Comment by forcecore** [comment]
Looks like it. Manual dock order to the refinery should get it sorted out. I wonder if he kept clicking on the ore.

**Comment by forcecore** [comment]
A quick and dirty fix is to return a dummy activity sequencing when the harvester is already at the dock:

	if (self.Location ==  proc.Location + iao.DeliveryOffset)
    {
        return ActivityUtils.SequenceActivities(new Wait(5), this);
    }
    else
	{
		var notify = self.TraitsImplementing<INotifyHarvesterAction>();
		foreach (var n in notify)
			n.MovingToRefinery(self, dest, this);

		return ActivityUtils.SequenceActivities(movement.MoveTo(dest, 0), this);
	}

Still I don't understand what is really happening when ActivityUtils.SequenceActivities is called. What happenes to the actions queued by iao.OnDock()? iao.OnDock() queues 3 actions but they never get to tick().

**Comment by pchote** [comment]
This bug has existed for a long time, and is one of the many broken activity cancelling bugs that @obrakmann's activity refactor is aiming to fix.

`DeliverResources` enters the `if (!isDocking)` branch, sets `isDocking` to true, and then queues the docking activities.  Issuing the harvest order somehow (I haven't dug deep enough to work out exactly how) overrides the activity queue to remove the docking activies without cancelling them, but keeps the `DeliverResources` active with `isDocking` true.  `DeliverResources` then ends up stuck in a loop where it waits forever for the docking that no longer exists to complete.

**Comment by pchote** [comment]
I'm going to remove this from the milestone because it's old and does not have a simple fix.

**Comment by obrakmann** [comment]
The problem here is that `Refinery.OnDock()` queues its activities onto the wrong activity. `harv.CurrentActivity` is still the initial `FindResources` that gets queued when the "Harvest" order is given.

The block of the `harv.IsFull` check in `FindResources` however breaks the queue (it just returns a fresh `DeliverResources` activity, and `FindResources.NextActivity` is usually null at that point). This is a nice example why [this comment](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Activities/Activity.cs#L37) exists.

But the `iao.OnDock()` call in `DeliverResources` causes the activities to be queued to the harvester's `CurrentActivity`, which is still `FindResources`, and essentially a dead end. When the tick ends, that `FindResources` activity will be left behind, and `DeliverResources` will be the `CurrentActivity`.

The patch below fixes it. I'm going to leave the wrong queuing behaviour after the `harv.IsFull` check in, just because I don't particularly feel like messing with the potential fallout of changing that.

```diff
diff --git a/OpenRA.Mods.Common/Traits/Buildings/Refinery.cs b/OpenRA.Mods.Common/Traits/Buildings/Refinery.cs
index 97d4c47..497f958 100644
--- a/OpenRA.Mods.Common/Traits/Buildings/Refinery.cs
+++ b/OpenRA.Mods.Common/Traits/Buildings/Refinery.cs
@@ -139,12 +139,12 @@ public void OnDock(Actor harv, DeliverResources dockOrder)
                {
                        if (!preventDock)
                        {
-                               harv.QueueActivity(new CallFunc(() => dockedHarv = harv, false));
-                               harv.QueueActivity(DockSequence(harv, self));
-                               harv.QueueActivity(new CallFunc(() => dockedHarv = null, false));
+                               dockOrder.Queue(new CallFunc(() => dockedHarv = harv, false));
+                               dockOrder.Queue(DockSequence(harv, self));
+                               dockOrder.Queue(new CallFunc(() => dockedHarv = null, false));
                        }
 
-                       harv.QueueActivity(new CallFunc(() => harv.Trait<Harvester>().ContinueHarvesting(harv)));
+                       dockOrder.Queue(new CallFunc(() => harv.Trait<Harvester>().ContinueHarvesting(harv)));
                }
 
                void INotifyOwnerChanged.OnOwnerChanged(Actor self, Player oldOwner, Player newOwner)
```
