### ISSUE TITLE
Stackable external condition duration cannot be reset by the source, a new instance will be applied instead.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#12720]
This is a regression due to #8658 became undone during the upgrades->conditions rewrite.

**Comment by pchote** [comment]
Do you have a use case demonstrating how this is an issue?

**Comment by pchote** [comment]
The changelog entry for #8658 is:
> Changed timed upgrades to accumulate instead of refreshing if they are granted from different sources. 

We should have this same behaviour now re multiple sources.  If you want to reset a condition instead of stacking it from the *same* source then you need to explicitly revoke the token that was returned the first time you granted it.

**Comment by GraionDilach** [comment]
Disco power!

![dancingpowerbarsohyeah](https://cloud.githubusercontent.com/assets/1136302/22696427/403654d4-ed4e-11e6-9684-aca8a297a47e.gif)

```
napowr:
	ExternalConditions@tesla:
		Conditions: tesla
	StackedCondition@tesla:
		Condition: tesla
		StackedConditions: tesla2, tesla3, tesla4, tesla5
	Power@default:
		Amount: 150
		RequiresCondition: !tesla
	Power@charged1:
		Amount: 200
		RequiresCondition: tesla && !tesla2
	Power@charged2:
		Amount: 250
		RequiresCondition: tesla2 && !tesla3
	Power@charged3:
		Amount: 300
		RequiresCondition: tesla3 && !tesla4
	Power@charged4:
		Amount: 350
		RequiresCondition: tesla4 && !tesla5
	Power@charged5:
		Amount: 375
		RequiresCondition: tesla5

TrooperCharge:
	ReloadDelay: 25
	Range: 2c0
#	Report: iteschaa.wav	NTM this is annoying as fuck when normalized
	ValidStances: Ally
	ValidTargets: TeslaBoost
	Projectile: TeslaZap
		BrightSequence: bright-charge
		DimSequence: dim-charge
		DimZaps: 1
		Palette: ra
	Warhead@charge: GrantExternalCondition
		Spread: 42
		Duration: 55
		Condition: tesla
		ValidStances: Ally
		ValidTargets: TeslaBoost
```

#8658's code made so that external conditions would have use their source of origin as a token and not just a single boolean about being external and if the token exists, then refresh the duration. Yet my Tesla Trooper can apply the tesla boost twice and now all my players complain about this disco powerbar.

**Comment by pchote** [comment]
See my edit above.  It is now the caller's responsability to revoke the first condition, instead of the condition code having to guess at the behaviour you want.

**Comment by GraionDilach** [comment]
And how am I supposed to do that? Are you really suggesting to me at this point to duplicate the external condition warhead and try to keep a list of actors applied it somewhere?

That PR was written exactly to resolve these stacked usecases (since this same happened during the original TeslaBoost implementation on the RA1 tesla coil).

**Comment by pchote** [comment]
Yes, that is indeed what i'm suggesting you to do to fix this issue.  It is no longer possible to hardcode these special-case rules in the conditions code.

**Comment by GraionDilach** [comment]
So I'm gonna ask again, is https://github.com/GraionDilach/OpenRA.Mods.AS/commit/55ffe409bb9cbf66516444179ea6b824d7f07e25 what you consider the fix for this issue? I'm not asking for a code review, I'm just asking to confirm it's place (because it works).

**Comment by GraionDilach** [comment]
If yes, then the followup question is if you want that behaviour PRd.

**Comment by pchote** [comment]
I was originally thinking something along those lines, but looking at your implementation made me realize that we could do this in a better way by removing external conditions from `ConditionManager` completely, and have the warheads/etc interact with the `ExternalConditions` trait directly like you do with `ExternalConditionStackManager`.  `ExternalConditions` can then have a new flag that sets whether it stacks or resets.

**Comment by pchote** [comment]
I've started working on a PR to reorganize the `ExternalConditions` code to build a cleaner base for fixing this.
