### ISSUE TITLE
Group of units wont wait for other units to pass narrow paths

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#12723]
In the original games sending a group of units to cross a bridge will cause the rest of the units to wait and not change direction to find an other way around.
exceptions are if there's a another path nearby such as 10 cells away or so.

the problem is that you basically lose half of your units that are trying to go to a completely different and long way out route forcing you to rage and buy a new screen... :p joke aside this is really annoying and bugged.following the steps of the original games on this will be a positive thing for the game.

**Comment by AoAGeneral** [comment]
The units do this because of harvester/ore truck issues when they would get themselves stuck on narrow pathways or bridges. (Although the bridges they sometimes still do it). So when they congregate in an area they venture for a different route. This was a common problem in the original games.

**Comment by KOYK** [comment]
No am not talking about 2 units trying pass the same bridge or narrow path from the opposing ends,am talking about units trying to pass from the same stating point to the same ending point of bridge or a narrow path,in the original games this never happens(at least in ra2).

(Correct me if i am wrong, my english are not the best and i may got what you said wrong)

**Comment by StormWingDelta** [comment]
A simple fix to this would be having some kind of AltPathSearchRadius thing in the yaml so we could tell the path finding AI of the units how wide an area they should search for another path if the main one is totally stopped up with units.

And yes this is extremely annoying to say the least when I'm expecting my whole force to go through an area and not stupidly take a path to their deaths over a few of my other units being too stubborn to move out of their way. >.>

**Comment by dazrave** [comment]
+1 for this issue. Just started playing the latest build again after some time away and this is the number one factor for me. I was just about to create a bug until I spotted this one. 

I've seen it happen with as little as 3 units. As soon as the two slower units clog up a bottleneck in the path, the faster unit approaching from the rear almost instantly gives up and goes a very very longer way around (even though waiting would still have been quicker), often resulting in death by driving via an enemy base.

Highly frustrating.

**Comment by KOYK** [comment]
It wont be fixed\added, closing it.
