### ISSUE TITLE
Setup Wizard For New Mods

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#12721]
Hi does setting up a new mod feels like a boring job to do? 
all this Packages map folders ect? how about a mod setup wizard with questions and staff?
an example will be: 
1) set mod name
2) mod dir (mix files,videos)
3) (Question) mod type (ra,ts,td,d2k,ra2,ect)
4) (Question) mod dependencies (like dll and mix files from other mods) 
5) ect ect.

So?

**Comment by GraionDilach** [comment]
Why would one need a wizard for doing something which only needs to be done once per a mod? Setting up a new mod isn't tedious at all.

Besides, 9 modders out of 10 starts their mod with duplicating another and then doing a replace on the mod's folder in the mod.yaml.

**Comment by KOYK** [comment]
it is tedious for an inexperienced user,but overall its not a hard thing to do as you said.but for the sake of automation i might do such an installer some day,and post it to the forums, source included,hopefully some one will add to the main game as a tool.

**Comment by pchote** [comment]
The mod template that will be developed from #12638 will simplify this.

**Comment by pchote** [comment]
This is now implemented in https://github.com/OpenRA/OpenRAModTemplate.
