### ISSUE TITLE
D2K wrong trike armament offset 

### ISSUE THREAD

**Issue by ltem** [OpenRA/OpenRA#12740]
@abcdefg30 found this issue

Problem: Trikes damage walls in the cell behind it but only if the walls are positioned vertical (not horizontal) 

![screenshot - 2017-02-10 - 14 22 16](https://cloud.githubusercontent.com/assets/20945684/22828242/78bb84aa-ef9c-11e6-80bd-3c84c88b850b.png)

First guess is that trikes have a wrong offset for its armament.
However, this will only happen to walls other buildings or units won't be effected.

----------------------
Edit 1: Yeah, offset is pretty off (:D)
- Trike: `LocalOffset: -416,0,0
` [LinkToLine](https://github.com/OpenRA/OpenRA/blob/bleed/mods/d2k/rules/vehicles.yaml#L126)
- Raider Trike: `LocalOffset: 170,0,0`

Still I don't understand why this behavior is only triggered by walls...

**Comment by pchote** [comment]
See also #12683, #12684.  Most of the muzzle offsets across our default mods were set to make the muzzle flashes look correct, before we had a tool to visualize the actual positions that we now know to be wrong.  We really need someone to go through all the mods and set all the offsets correctly.

**Comment by ltem** [comment]
Yeah, the wrong gun offset was due to a correct muzzle offset...at least it seems so...

1. Question: If the fire/gun position gets corrected, should the muzzle-sequence also be modified that it needs the same offsets as the fire position to look correct?

2. Question: Many units don't have a z-offset (like the Trikes), should they have one? In my opinion yes.

**Comment by pchote** [comment]
Yes and yes.  It may be necessary to define a new MuzzleOffset field on armaments to avoid editing the artwork.

**Comment by MustaphaTR** [comment]
Actually most weapons in original D2K, including Trikes', wasn't blocked by walls. IIRC only combat tank and Devastator did. While in OpenRA's D2K almost all weapons do except.

**Comment by ltem** [comment]
Maybe I find the time to go over the other units with 0 or no z-offset in D2K:
Vehicles:
- [ ] Raider
- [ ] Combat Tank
Infantry
- [ ] Light Infantry
- [ ] Fremen
- [ ] Sardaukar

**Comment by ltem** [comment]
I close this particular issue because it is fixed by #12746 but I will open a new one for the missing z offsets.
