### ISSUE TITLE
Utility has trouble linting custom sequences

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#12744]
See  #12743 (https://travis-ci.org/OpenRA/OpenRA/builds/200429481#L1197) and #12729 (https://travis-ci.org/OpenRA/OpenRA/builds/199918666#L1168). From https://github.com/OpenRA/OpenRA/pull/12729#discussion_r100334460:
>  &lt;orabot&gt; Mailaender, offline msg from `abcdefg30` at `2017.02.09 10:56 UTC`: https://travis-ci.org/OpenRA/OpenRA/builds/199918666#L1168 
> ...
> [13:13:12]	&lt;Mailaender&gt; moving the xxicon definitions onto the mod fixes things
[13:13:45]	&lt;abcdefg30&gt; weird stuff
[13:13:51]	&lt;abcdefg30&gt; yaml merging bug I suppose
[13:15:45]	&lt;abcdefg30&gt; hm fun, it already gives me those erros when I use "Sequences: sequences.yaml
[13:15:45]	&lt;abcdefg30&gt; " with an empty sequences.yaml file

**Comment by pchote** [comment]
These are real errors with the trait defaults and/or mod rules.  The only reasons why they haven't been noticed before are that (a) they are benign errors (aren't actually used ingame, so don't crash) and (b) the sequence lint is disabled everywhere except for maps with custom sequences.

**Comment by abcdefg30** [comment]
I submitted #12753 so that we don't lose track of the "underlying" issue once this is closed.
