### ISSUE TITLE
Support powers should have designated keybind slots

### ISSUE THREAD

**Issue by Smittytron** [OpenRA/OpenRA#12752]
Currently support power keybinds are assigned to the powers in the order that they are constructed. For example, if I keybind support power command slot 1, the keybind will be the spy plane if I build an airfield first, and will be an iron curtain if I build that before the airfield.

If I anticipate always building an airfield before the iron curtain the keybind slot for the IC will change based on if I’m Ukraine or Russia because of parabombs. Also, it would be handy to have a similar keybinding scheme between Allies and Soviets for players who play both.

Powers should correspond with a specific keybind slot. This will allow players to reduce the amount of keybinds they use and/or be more timely with their support power usage. 

An example from FiveAces on timely support power usage: https://www.youtube.com/watch?v=Ak8igonFVDE#t=24m25s

My recommendation would be:

Slot 1: Iron Curtain/Chronosphere

Slot 2: Atomic Bomb

Slot 3: Spy Plane

Slot 4: Paratroopers

Slot 5: Parabombs

Slot 6: Sonar Pulse

**Comment by pchote** [comment]
A better solution (balancing off usability vs technical feasibility) would be to add a `SupportPaletteOrder` field to `SupportPower` and sort the power palette the same way we do the build palette.

**Comment by StormWingDelta** [comment]
While it'd be nice to give them key bindings it doesn't take into account the fact we can set things up in the yaml to have more than one of them.  That said it sounds like there could be a way to give them some kind of order and make it so the ones with the least time left could float to the top or something. :)

**Comment by abcdefg30** [comment]
Was #16645 enough to consider this fixed?

**Comment by abcdefg30** [comment]
Closing as resolved then.
