### ISSUE TITLE
Additional Tiberium types

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#12760]
The original had 4 types out of which 2 are unused (except by mappers):

```ini
[Tiberiums]
0=Riparius
1=Cruentus
2=Vinifera
3=Aboreus
```

* http://modenc.renegadeprojects.com/Tiberium_(fictional_substance)
* http://modenc.renegadeprojects.com/Tiberiums

**Comment by pchote** [comment]
What's the problem?

Maps that need these or even more resource types should be able to define them in their own yaml.  The map importer also knows how to import these four types.

**Comment by Mailaender** [comment]
> The map importer also knows how to import these four types, but converts the latter three to the same blue tib.

Yes, that is what happened in https://github.com/OpenRA/OpenRA/pull/12729 which featured a dark orange Aboreus.

**Comment by PunkPun** [comment]
Is this relevant?

**Comment by Mailaender** [comment]
I guess not.
