### ISSUE TITLE
D2k missing z offset of infantry

### ISSUE THREAD

**Issue by ltem** [OpenRA/OpenRA#12771]
Infantry with 0 z-offset for their armament in prone position will shoot "into" the ground and won't damage itself or the enemy during this time.

![image](https://cloud.githubusercontent.com/assets/20945684/22879323/c9a6f2da-f1dd-11e6-8bf5-d7d0ba84746f.png)

Units with 0 z-offset in D2K:
Infantry:
- [ ] Light Infantry
- [ ] Fremen
- [ ] Sardaukar

Vehicles:
- [ ] Raider
- [ ] Combat Tank

**Comment by ltem** [comment]
It seems that this is already fixed...quite possible an error in my side...

**Comment by MustaphaTR** [comment]
This was fixed by https://github.com/OpenRA/OpenRA/pull/12684
