### ISSUE TITLE
Complete OpenRA Video Game Trailer for OpenRA's 10th Anniversary (June 19th, 2017)

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#12773]
June 19th marks the 10th Anniversary for OpenRA:
OpenRA's first commit: https://github.com/OpenRA/OpenRA/commit/b59ba43934a3a6837410db51cf60157cf854e52d

This issue is here to collaborate various aspects of the video making process.

Aim of producing the complete video is June 4th (Sunday) around 2 weeks before the Anniversary date.

The final product will be uploaded to the official OpenRA channels (YouTube, Facebook...).

- - - - - - - -

This video project started around November 2014 with #6891 but stalled at the end of 2015 due to other commitments taking precedence up until today. In order to avoid the same trap I'll be season forfeiting the league and cut down the Monday streams down to every other week starting with Monday March 13th.

- - - - - - - -

Product so far:
https://www.dropbox.com/s/ih2tlyhgx2eyfnv/Produced_177.mp4?dl=0

Topics to cover (will flesh this out during this week):

- Total video time: 2m:04s of which 1m:15s is produced and 0m:49s remaining.
- Sealed intro sequence. Possible alteration with new text/theme/style.

- [x] Re-shoot outdated game-play sequences.
- [x] Remaining content.
- [x] Redo intro and replace text graphics.
- [x] Tweak/add effects.
- [x] Outtro/End title.

**Comment by pchote** [comment]
Some fixups on the current version:
* I would like to see the "Open ☭ Sourced" in the intro sequence changed to "Open Source" (drop the D and logo), possibly using a font like http://imgur.com/iFgp3ED.  "Open Sourced" is an action, implying that the code was previously closed source.  Dropping the logo is to simplify life in the near/medium future when we change the main project logo - removing it here means that we only need to replace the title card when that happens.
* The RA shot with the destroyers shows the old GPS icons and should be updated.
* D2K has changed a lot in the last couple of years, so i'm sorry to say that I think it all needs to be updated (the big clips at least - the small montages are probably fine).  Specific issues include the weapon effects, bounties, and sandworm.
* One of the TD clips shows a christmas present crate.  It's a minor point, but IMO that should be cut out to avoid confusion.

**Comment by kyrylo** [comment]
I agree with @pchote's feedback. It sucks to redo so much stuff, but I think those are valid concerns.

My two cents: I think it would be beneficial to showcase at least one demo truck explosion in the RA mod. It always makes people happy :)

**Comment by Smittytron** [comment]
> My two cents: I think it would be beneficial to showcase at least one demo truck explosion in the RA mod. It always makes people happy :)

https://www.youtube.com/watch?v=Ak8igonFVDE#t=27m04s
Would be a good demo truck hit + bonus reaction from 5a.

**Comment by SoScared** [comment]
*cracks fingers*

I should have the complete footage (basic edit) + video text/themes ready by Sunday, April 9th, after which volunteers (warman) can start review for alteration of text/theme style, possible after effects and eventually the end title. At the end of April (no later than May 7th) I should have the final edit of the video montage. The last 4 weeks (May 8th - June 2nd) should concern itself to nothing else than refining text-style/after-effects and the end-title - this will likely prove very demanding, going back and forth on countless issues in this time period.

@pchote: the intro title text/logo can possibly be altered by bringing aboard new titles that overlap the original footage. unfortunately the project file covering the first 10 seconds has been lost so there's limited maneuverability without compromising video quality. I'll early re-shoot the D2K Sonic Tank "lazer" weapon but for the rest outdated features it'll stay a bit behind in the priority queue.

@kyrylo: had planned for a Demo Truck in a ending-montage sequence ;)

@Smittytron: I'll grab that webcam footage thankyouverymuch \o/

**Comment by SoScared** [comment]
Allright so basically there's just two stages left of footage:

1. Mods
2. Mash-up of intense action shots


**1. Mods**

Planned official mods

- Tiberian Sun
- Red Alert 2

Might need help getting hold of a functional RA2 mod working on my computer (Win 7) - only need basic skirmish to work.

Significant long standing external mods/projects - on top of my head

- Crystallized Doom
- Nomad Galaxy
- Shattered Paradise
- Attack Superior

**2. Mash-up**

More or less anything goes. Crazy modded maps, competition, reactions, anything that builds up to a finale seconds before the end-title.

**Comment by pchote** [comment]
RA2 isn't being developed as an official mod, and I expect that advertising it as such would cause us more grief than I would like to deal with.

**Comment by SoScared** [comment]
Then it shouldn't be advertised as such. If ok I'll add it with the other mods. On video time we're only talking split seconds exposure (perhaps mixed) for each of them.

**Comment by SoScared** [comment]
Leaked documents from the command bunker. Plans on video montage sequence.

![battleplans](https://cloud.githubusercontent.com/assets/2715583/24331574/141a2a48-1237-11e7-9bbc-b973570e3c48.jpg)

This is why I struggle working with groups :P

**Comment by ABrandau** [comment]
I am Nolt, I can give you access to both of my mods, no problem, btw you could also add Combine's medieval warfare there, he's doing a nice job so far.

**Comment by pchote** [comment]
A couple more candidates for the mod section:
* http://www.moddb.com/mods/enigma-sc
* @reaperrr's [Tiberan Dawn Xtended](http://ppmforums.com/index.php?f=561) (showing the carribean tileset) and mech mods.

**Comment by SoScared** [comment]
@ABrandau Excellent. I already have the medieval mod in mind for some split second exposure.

@pchote Sure why not. Some of these moddb sections has some great gifs to them that I think I could use.

**Comment by GraionDilach** [comment]
I'd also list @Holloweye's http://www.moddb.com/mods/openra-the-great-war-wwi-mod WWi mod because atm it's among the biggest RELEASED projects with the most originality.

**Comment by SoScared** [comment]
**List of video text/titles - checking for good English and considering new text graphic/style _only_-post. Focus on video shots and style in a later post**
- - - - - - -
1st video sequence (linked in OP): https://www.dropbox.com/s/ih2tlyhgx2eyfnv/Produced_177.mp4?dl=0

00:08 - Remade, Modified, Open Sourced - **Main Text Style** - https://github.com/OpenRA/OpenRA/issues/12773#issuecomment-279481190

_The only alteration that poses a challenge - the complete project file for the intro sequence is lost and would have to be painstakingly rebuilt, at least partially, something I'll hold off 'til last._

00:11 - Red Alert - **Custom Text Style** - **From the Heavens** 
00:19 - (?) room for text at YAK flyover scene - **Commentary Style**
00:23 - Soviet, Allied, the factions and more - **Commentary Style**
00:30 - Mod Chooser (brand the metal gate?)
00:33 - Dune 2000 - **Custom Text Style** - **From the Heavens** 
00:35 - (?) room for text at Ordos base scene - **Commentary Style**
00:38 - (?) room for text at Ordos base scene - **Commentary Style**
00:57 - Tiberian Dawn - **Custom Style** - **From the Heavens**
01:00 - (?) room for text over multiple TD scenes - **Commentary Style**
- - - - - - -
2nd video sequence: https://www.dropbox.com/s/hv6y56oqam870so/Produced_220.mp4?dl=0

Text in the 2nd sequence are for the most part presented simply as placeholders for later alteration of graphic/style.

00:03 - Official Mod In Development - **Main Text Style**
00:04 - Tiberian Sun - **Custom Text Style**
00:07 - Custom Mods - **Custom Text Style**
00:08 - Crystallized Doom - **Custom Text Style**
00:08 - Shattered Paradise - title ingrained in logo
00:09 - Attaque Superior - **Custom Text Style**
00:10 - Nomad Galaxy - **Custom Text Style**
00:11 - Modded Maps - **Custom Text Style**

00:13 - Best! Map! Evur! - **Commentary Style**
00:16 - Enigma Mod - **Custom Text Style**
00:17 - Play Co-Op With Friends - **Commentary Style**
00:20 - Big Team Games - **Commentary Style**
00:26 - Play Competitive OpenRA - **Commentary Style**
00:37 - OpenRA - **Main Text Style** - **Title Style**
- - - - - - -
I'll hand-hold anyone through the info jungle presented here if/when necessary.

**Comment by GraionDilach** [comment]
It's Attacque, with a c included.

**Comment by SoScared** [comment]
A little over 3 weeks left of the stated deadline.

Work that remains:

Replace outdated footage. (easy)
Add new "commentary" titles to the featured mods segment RA/D2K/TD, tweak current ones. (easy)
Fix transition between 'custom maps' and the last segment ("best map evur" transition) (easy)
Tweak/add misc. effects. (easy)
Outtro (hard)

As a bonus I managed to pull together the original intro and can alter it however I like. I've added the new title style to it while simultaneously. Making a decent new outtro will be tough 

Video so far: https://www.dropbox.com/s/1qmd2o5zlyt2rzt/Produced_11.mp4 (download to view 1080p 30fps).

**Comment by SoScared** [comment]
Accidentally uploaded a 60fps high bitrate video making it hard to watch for most users. Updated link: https://www.dropbox.com/s/3zk2pyika4zb4l4/Produced_18.mp4

Also, some polish on the main titles.

**Comment by SoScared** [comment]
Needs additional text:

Main Titles:

OPEN SOURCE GAME ENGINE

Commentary: 

PARTAKE IN ALTERNATE HISTORY
THE COLD-WAR THAT TURNED HOT
THE SPICE MUST FLOW
THE GAME THAT DEFINED MODERN RTS

**Comment by SoScared** [comment]
New work in progress video: https://www.dropbox.com/s/2tjpkpg71px4ce5/Produced_484.mp4 (download to view 1080p 30fps)

A little more than a week left but it looks like the remaining tasks will be completed in time. Making a list because I like making lists:

Must-do:

- [ ] Secure against copyright (Westwood trademark) in intro.
- [ ] Complete OpenRA end title.
- [ ] Credits/outtro.

Should do:

- [ ] Add final commentary/titles by Warman.
- [ ] Replace outdated footage (D2K Sonic Tank, GPS (naval scene), ++)
- [ ] More Image-2-Frames images and effects in before OpenRA end title.

Can do:

- [ ] Improve 'Custom Maps' sequence to end-montage transition.  
- [ ] Tweak ad-infinitum.

Review now or forever hold your peace!

**Comment by pchote** [comment]
Looks good, but IMO the outdated footage really should be a must do, like I mentioned back in Feb all the headline footage for d2k is visibly outdated - old worm effects, bounties, as well as the blue lasers.

**Comment by reaperrr** [comment]
I agree, at least re-shooting D2k is a must, in my opinion.

**Comment by pchote** [comment]
The old GPS icons is pretty minor by comparison, and could be skipped if time is a problem.

**Comment by SoScared** [comment]
Moved it over to must do. 

I'll work to get the most obvious D2K ones out of the way (mass-bounties, Sonic lazers) but I dare not promise to have _all_ D2K footage replaced. The outdated worm effect would be the lower priority.

Keep in mind this video is more 'flashy' compared to the old one which was more of a 'showcase' trailer, presenting accurately what the game could do. This time more than anything the aim is flash and hype points. I think.

**Comment by SoScared** [comment]
@pchote Could you do me a favor? Or anyone else for that matter? I wanna have a professional looking 'disclaimer' written in the intro before the use of the Westwood logo. If nothing else, just to underscore the videos' importance and production value (like with the old video) and I think it would fit in all right. Would you have the time to draft up something for me before next Sunday?

I'm tweaking the Westwood logo intro part to better signal that this isn't a Westwood product (EA closed down  Westwood Studios aeons ago but whatever) but more as an inspiration that has carried itself over into OpenRA.

**Comment by pchote** [comment]
I wouldn't bet on it, sorry.  If it comes down to it, it would be better to delay this than to release something that we might end up regretting.  It is afterall only a slightly less arbitrary date than any other date.

**Comment by SoScared** [comment]
I thinking actually for some kind of standardized, over-arching statement I could use. It also will depend on the final video product itself but it would be nice to have a pointer to where to look for these sorts of disclaimers. This would also be put down with the video description in addition to credits on use of various graphical assets (in that department I have a decent grasp on things). In any case I should be able to present several options this week-end that'll have a few decent "safe" versions - more than anything else I want to ship it no later than the anniversary date.

**Comment by SoScared** [comment]
latest product: https://www.dropbox.com/s/e0n4ac8fh3gdofu/Produced_596.mp4?dl=0 (download to view 1080p 30fps)

@pchote could you list the scenes you think should be replaced ordered in a high-low priority? I've done some, I probably have some time to replace more but not all.

**Comment by SoScared** [comment]
Text graphics redo wish list:

Reduce dark spots (lighting) on main titles:

'Modded Maps'
'Play Co-Op with friends'
'Big Team Games'
'Play Competetive OpenRA'
'Open Source
Game Engine'

**Comment by kyrylo** [comment]
> @pchote 
> One of the TD clips shows a christmas present crate. It's a minor point, but IMO that should be cut out to avoid confusion.

This is still an issue (timestamp 1:11)

**Comment by SoScared** [comment]
That should be easy.

**Comment by Smittytron** [comment]
I bet your disclaimer doesn't have to be too complex. Could probably go with something like:

OpenRA is an open-source re-imagination of Command & Conquer, Command & Conquer Red Alert, and Dune 2000. These titles are the property of Electronic Arts and Westwood Studios.

**Comment by SoScared** [comment]
latest product: https://www.dropbox.com/s/ibhp0s3jeglwqro/Produced_707.mp4 (download for 1080p 30fps)

Alright so with some mixed feedback I decided to go half-n-half on the Westwood logo issue since in my opinion it bonds with the main message of the intro. I had plans to rip it off completely but I couldn't find any other solutions that would deliver the same punch in the intro. As it currently stands it should be safely protected under fair use but in any case I take responsibility for whatever would come of it.

As with the old trailer I could upload it to my channel first, let it make itself known and then later upload it to the official OpenRA YouTube or Facebook. I prefer putting it up on the official channels so unless any of you (devs/owners) speak out against it from here on I'll upload it to the official channels with a planned date/time reveal at Monday 19th, 08:00 UTC.

As mentioned there are still visibly outdated footage involved but for the target audience it won't really matter. Although this is partially a tribute to the current game and community the ultimate goal is to create a brawl and see if it can't attract some attention to the game from the greater gaming community.

With some minor nitpicking the only thing that's really left is some outtro/end-title polish and end credits.

**Comment by SoScared** [comment]
(hopefully) final product: https://www.dropbox.com/s/8eu21xrnjd35jb2/Produced_748.mp4 (download to watch 1080p, 30fps, ca 300MB)

for a quick peek at the disclaimer section: https://www.dropbox.com/s/i47df10e42vs7pm/Produced_744.mp4?dl=0
Proofread and ready to go.

I'll upload this vod as a planned event (06:00 UTC) on the official youtube and facebook pages and in absence of further issues will be revealed publicly by then.

**Comment by SoScared** [comment]
https://www.youtube.com/watch?v=93b7TKooj-M
https://www.facebook.com/openra/videos/1436256269763919/

Probably my most satisfactory issue closing ever! This was a pain in the ass to make but I learned a ton in the process that I can make use of in future projects.

On we go!
