### ISSUE TITLE
Missions with paradrop crashing on bleed (eef4c9b)

### ISSUE THREAD

**Issue by HenrytheSlav** [OpenRA/OpenRA#12780]
Upon building a power plant.
[exception-2017-02-14T220221Z.TXT](https://github.com/OpenRA/OpenRA/files/775423/exception-2017-02-14T220221Z.TXT)

I narrowed the source to the Para() function after quick testing by calling it at WorldLoaded().

Looking into it now.

EDIT: Not only Soviet05 is broken, probably any mission using paradrop is, for example Survival01.

[exception-2017-02-14T223228Z.txt](https://github.com/OpenRA/OpenRA/files/775461/exception-2017-02-14T223228Z.txt)

**Comment by pchote** [comment]
Probably introduced by #12751.
