### ISSUE TITLE
Allied harvesters get stuck when trying to harvest the same tile

### ISSUE THREAD

**Issue by binyata** [OpenRA/OpenRA#12817]
I was playing a game last night with my brother, and we teamed up against computers. 

The maps we played were:
1. Morbid Aimless Poseidon
2. Escalations

To reproduce you basically have you and your allies harvesters gather tiberium in the same location. Eventually they will compete for the same tiberium, resulting in harvesters being stuck and never continuing their harvesting, which will cause you to never increase your cash amount, if you are not paying attention to your harvesters.

Maybe a potential fix would be to add some smarts to the harvester to recognize that something is in the way of its path, sort of like the minigunners that can avoid the tiberium, so that the harvester will move to a different tiberium tile instead of being stuck.

**Comment by StormWingDelta** [comment]
I've run into this in all the mods, it also happen when harvesters come in to drop off at refineries so they fight over who gets to move where instead of simply going for another one.

**Comment by forcecore** [comment]
Can you reproduce your error and look into the cause?
I suspect that they are not competing over same tiberium but instead they are trying to harvest what is underneath each other like in this video:

https://youtu.be/jvlP--VUnyE

**Comment by forcecore** [comment]
I did it myself and it seems to be the same thing.
https://youtu.be/7zaAJdPD4NM
