### ISSUE TITLE
Remove Hind from Allied build tree and give the Apache a chain gun as a secondary weapon

### ISSUE THREAD

**Issue by SamKeightley** [OpenRA/OpenRA#12810]
I find it odd that the allies build Hinds, instead I propose that the hind be removed from the Allied build tree and instead bolster the armament of the Apache with it's M230 30mm chain gun. This weapon is great against infantry and lightly armed targets like jeeps, flack tracks and apcs. Then you can use the missiles for taking out heavily armed units like tanks, harvesters and buildings.  

For balance, they should not be able to engage air units with their Hellfire missiles as these are an air to ground missile. But the chain gun can be used to target other helicopters would not look out of place.  

This will of course require two bars for ammunition, which isn't such a bad thing.

On top of this, the hind could also be changed to account for it's Yak-B 12.7mm machine gun, and S-5 rocket pods.

**Comment by MustaphaTR** [comment]
👎 

If the Hind is a Soviet Helicopter problem will be fixed, it should be as just renaming and maybe changing the artwork. But stats like weapon/hp/speed should stay same.

**Comment by SamKeightley** [comment]
Then the Hind should be moved back to the Soviet build tree. This is supposed to be RA right? Why was it moved to the Allies in the first place?

**Comment by MustaphaTR** [comment]
> This is supposed to be RA right?

Not really: https://github.com/OpenRA/OpenRA/wiki/FAQ#this-is-not-true-to-the-original

> Why was it moved to the Allies in the first place?

Balance reasons. Planes are now Soviet, helis are Allied.

**Comment by SamKeightley** [comment]
I have nothing wrong with the idea of improving RA beyond the original, my comments merely point out that how helicopters are now are too far away from the directions RA was heading. In fact a way more balanced solution would be to give both Allies and Soviets both planes and helicopters since no military force, even fictitious ones would do without all capabilities that provide then an advantage over an opposing force, but I digress. 

The Hind is a Soviet designed helicopter and is out of place being in the allied arsenal. As for changing it's art, why not make it a Cobra instead. And give the Soviets their Hind back, it's an iconic unit in an iconic franchise. You wouldn't give the Allies the Mammoth tank right?

**Comment by Smittytron** [comment]
As a history major, the Hind being an Allied unit bugged me initially. (A lot)
As a player, it's very important to keep air power close to the way they have it now. I just don't see a good way to change the hind outside of just renaming it that would leave balance in a good state.

**Comment by SoScared** [comment]
Your biggest hurdle would be to convince the community to move away from the established tier2 and tier3 air play. The Hind reflects the YAK, the Longbow reflects the MiG. Both sides has an air support unit for different stages of the game. With heli and plane classes behaving differently it gives the sides an added distinction. Removing this for the sake of orthodoxy isn't worth it.

Still the name 'Hind' isn't too ideal. I'd love to see a new good name for it but if you ask around, players in general don't really care much about it.

**Comment by Micr0Bit** [comment]
>Removing this for the sake of orthodoxy isn't worth it.

especially now after a decade of openra , it proved that our balanced (with ups and downs) air-gameplay with planes on one side and choppers on the other side was generally well received

for everything else, theres cncnet

**Comment by SamKeightley** [comment]
The balance is good, that can't really be argued. I'm just not a fan of the Hind being on the allied build tree. Look I'll make something that would be more appropriate.

**Comment by Micr0Bit** [comment]
SamKeightley : 

we have also a APC on soviets-side "only" ... and then a "flak-truck" on soviet-side that doesnt even exist in the original ... in the original multiplayer, allies could also build demo-trucks ... and soviet tanyas

**Comment by SamKeightley** [comment]
That's not what I'm getting at. While I love the original to bits, there is nothing wrong with making the changes that have been made by OpenRA. However, the Hind being used by the allies stick out like a sore thumb:P

Personally I like the addition of the flak-truck and while the APC looks sort of like an m113, it doesn't feel out of place being used by the Soviets.

**Comment by MustaphaTR** [comment]
I agree @SamKeightley about Hind being Allied unit doesn't makes sense. That's why it should be renamed to an actual Allied Helicopter IRL.

**Comment by SamKeightley** [comment]
Well there's really only two that would fit really well. Either the: 
- Bell AH-1 Cobra - minus the stub-wing mounted rocket pods - https://en.wikipedia.org/wiki/Bell_AH-1_Cobra#/media/File:AH-1G_Cobra_Vietnam.jpg
- 'Bell UH-1 Iroquois, nicknamed "Huey" in gunship configuration minus the rocket pods and troop carrying capability - https://img.rcgroups.com/http://www.richard-seaman.com/Aircraft/AirShows/Nellis2007/Highlights/Uh1Gunship07.jpg?h=cVDNrXJ8kOtzP_QrPdvqng

**Comment by MustaphaTR** [comment]
Both planes are actually newer than the times RA acts in, but so does Longbow and Chinook. This was more like WW's mistake.

I feel like Huey is better to use.

**Comment by Smittytron** [comment]
In OpenRA's lore, not only did Albert Einstein kill Time-Hitler, but Soviet aerospace engineer Mikhail Mil gets angry with Stalin for being a meanie, defects to the Allies and designs the Hind for them.
There, problem solved.

**Comment by GraionDilach** [comment]
There were talks if the Hind could be moved back to a new Soviet subfaction which would have Helipads instead of Aircrafts but this was really loose and I have no idea how feasible would be from the playerside.

**Comment by Micr0Bit** [comment]
what does it matter if its called hind, huey, gunship or flying duck ?

**Comment by SamKeightley** [comment]
@MustaphaTR I also found it odd that 70's and 80's military vehicles where being used in RA's time period of 50's/60's, but I also think that that is part of it's charm. Yeah agreed on the Huey too.

@GraionDilach That sounds like it would be interesting, and allow for the reintroduction of the Hind in a Soviet build tree. 

@Micr0Bit The name can be anything, but the shp can't. So the name has to reflect what shp represents. Also the name has to fit in with the RA and other unit names.. So ask yourself:

Does Flying Duck sound good when compared to Longbow?

Just so where clear, Micr0Bit, I'm making a new shp too, not just chasing a name change:P

**Comment by Micr0Bit** [comment]
>Just so where clear, Micr0Bit, I'm making a new shp too, not just chasing a name change:P

im not gonna hold you up from most likely wasting your time with this ... but you should know that we are (atleast to my knowledge) following a direction of keeping any "none-westwood-content" out of our main-mods ... we have exception like the already mentioned flak-truck ... this unit is introduced to help the balance and is a rare exception along with some environmental additions like the gem-mine for example ... so unless you are doing the shp for a personal mod or map-mod you'll probably find yourself having a hard time getting that into one of our main-mods ... afterall OpenRA is giving everyone the possibility to create their own version of RA ... or really whatever you want

**Comment by SamKeightley** [comment]
I agree completely with the above sentiments, but I think you can agree that this case is an exception.

**Comment by Micr0Bit** [comment]
@SamKeightley : keeping new custon art out of our mods is mostly a decision made by the main-devs (which i support) if there would be an easy way to remove the flak-truck and move units around so we still have everything balanced and everyone pleased .. i would totally vote for getting even that out

**Comment by SamKeightley** [comment]
How do you think the Allies building Hinds is logical?

**Comment by Micr0Bit** [comment]
i simply dont care ... i see a faction that is using choppers ... and a faction with planes

having "just" the longbow on allies side would be pretty boring for allies air-gameplay,  i assume

**Comment by SamKeightley** [comment]
Well you might not, but you are one person with one opinion on the matter. There is more than one person in the OpenRA community with more than one opinion. 

The plane helicopter paradigm is completely fine, it works. I wouldn't go so far to say that just having Longbows would be boring, in anything they would have to be re-balanced to account for the capabilities of a helicopter equipped with machine guns if they where the only helicopter available to the Allies. 

There are far better choices of helicopter the Allies could use than to just use the Hind. Firstly it's out of place and sticks out like a sore thumb, secondly it shows laziness by equipping a Allies with Hinds and then calling it done. Finally the Hind is quintessentially Russian, I would say as much as the AK-47.

**Comment by Micr0Bit** [comment]
>Well you might not, but you are one person with one opinion on the matter. There is more than one person in the OpenRA community with more than one opinion.

that is true , as said ... im not gonna hold you up from doing anything ... just pointed out what you probably gonna run into , so you're not disappointed or lose interest on openra when this isnt going immediately in your direction

**Comment by SamKeightley** [comment]
I'm aware of that, if you recall I said that If the developers like it then I would love to see it included, not you will include the work I make or I'll loose interest lol. Worst case, I make it to exact Westwood standards and it gets declined, I can still just put it on PPM ;P

But on a more serious note, Allies with Hinds? really. How was that justified as a good design choice!

**Comment by Micr0Bit** [comment]
>But on a more serious note, Allies with Hinds? really. How was that justified as a good design choice!

i really could ask the same about Soviets and V2 - rocket launcher

https://en.wikipedia.org/wiki/V-2_rocket

**Comment by SamKeightley** [comment]
Hahaha, You are skewing the point just a tad there, perhaps reaching abit too far. While V2 is inaccurate it's better than calling it 9K52 Luna-M or if you want to refer to it's rocket then 9M21B. It's not as blatantly inaccurate as giving the Allies Hinds..

**Comment by Micr0Bit** [comment]
We can rename a Lockheed AH-56 as "Hind" the same way that Westwood can call a 9K52 Luna-M "V2".

**Comment by SamKeightley** [comment]
It's funny you bring up the AH-56 since it's a precursor to the Longbow:P 

The thing is Micr0Bit, The Hind is famous, and as I have said before quintessentially Russian. It is out of place in the Allied build tree. You can quote old idiosyncrasies and inaccuracies from RA all you want but nothing is going to change that fact.

**Comment by ScottNZ** [comment]
I see no reason not to have these changes if you can keep the aircraft balanced.

**Comment by SamKeightley** [comment]
There would be no need to change anything regarding it's rules or function, this is only aesthetic.

**Comment by Micr0Bit** [comment]
@SamKeightley : he means "giving the hind back to soviet" ... 

and i also dont have a problem with that , if someone can balance the longbow properly

**Comment by SamKeightley** [comment]
I see, either way would be just as good.

**Comment by Micr0Bit** [comment]
@SamKeightley : i have started a poll http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=19975

if you want me to rename anything to be more neutral ... then tell me

**Comment by SamKeightley** [comment]
Nope looks fine to me,

I've also created a poll at PPM https://ppmforums.com/viewtopic.php?p=554690#554690

**Comment by GraionDilach** [comment]
Okay, for one: Soviets in traditional RA1 skirmish have Chinooks. That's a perfect vice versa example to this issue.
For two, what PPM says, is basically completely unimportant. If you want to reach the actual playerbase, SleipnirStuff is where you head at.

I guess the idea of renaming the unit to Cobra would work well, however. It's just a generic attack chopper in the RA1 detail level, so don't think the artwork matters much.

**Comment by SamKeightley** [comment]
"The Hind is famous, and as I have said before quintessentially Russian. It is out of place in the Allied build tree, even if by name as you are trying to put it. You can quote old idiosyncrasies and inaccuracies from RA all you want but nothing is going to change that fact. It's a poor design choice."

I also found it strange that the Soviets where using Chinooks and find the change to the Allied build tree a welcome and logical one. There's no "Vice Versa" point to be made here so trying to figure that one out.   

I disagree, A forum a user post's in doesn't determine the importance and validity of their input, such sentiments are quite elitist. But sure there are forums where the majority of a player base would reside, that is a given.

The shape of the Hind is unique and unmistakable, even in it's shp form. Also would love to see a "generic attack helicopter".

**Comment by Micr0Bit** [comment]
>I disagree, A forum a user post's in doesn't determine the importance and validity of their input, such sentiments are quite elitist. 

if someone would make a poll on cncnet about OpenRa-related changes ... i would find it hard to believe that this could influence OpenRA ...

the only polls that ever mattered were on sleipnirstuff , that forum is actually owned by a main-developer that has write-permission on github/openra

**Comment by SamKeightley** [comment]
That's a rather naive sentiment you have there Micr0Bit.

**Comment by pchote** [comment]
The tone of the discussions around the hind/cobra/huey topic across Github/forums/IRC has been downright disgusting, and at this point it seems clear that merging *any* of these changes will only continue the toxic drama.

The Allied Hind will have to stay until people can approach the solution and eachother with some basic respect.
