### ISSUE TITLE
user configurable build palette order

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#12827]
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Buildable.cs#L49 so my suggestion would be to have a chrome (or settings yaml, but that requires #8276) entry where the sorting is defined.

The Half-Life mod Natural-Selection had bindable commander keys in a simple one dimensional array. We could do something similar for simplicity sake:
```
BuildPaletteOrder@Buildings: WEAP, PROC, HPAD...
BuildPaletteOrder@Vehicles: 1TNK, 2TNK, 3TNK...
```

**Comment by forcecore** [comment]
I like this idea, I don't have to go all over the place to get the order sorted out.

**Comment by GraionDilach** [comment]
That would overcomplicate the setup above a certain amount of units, which is why I don't like it.

**Comment by pchote** [comment]
That comment was added back in 2010 when the `Buildable` trait only had that order and the hotkey (which *was* fluff).  The trait now holds a lot more UI configuration, and it doesn't make sense in 2017 to remove *only* the BuildPaletteOrder.

I propose that a better solution would be to remove that now outdated comment.

**Comment by Mailaender** [comment]
Okay, I thought it would still apply today.
