### ISSUE TITLE
[RA] [release-20161019] [Ubuntu] Not possible to use custom maps

### ISSUE THREAD

**Issue by j2k15** [OpenRA/OpenRA#12825]
Hi,
I'm running latest version release-20161019 of OpenRA on Ubuntu 14.04.
I still have all my maps install under openra/maps/ra but they don't appear in the map selection (in Skirmish, ...).
I tried to move them under the new subfolder openra/maps/ra/release-20161019 but still I can see my maps in the map selection.
The maps are in oramap format and used to work in previous versions.
Did something change with customer maps in the latest version ?

**Comment by jaZzKCS** [comment]
Do you have the maps residing in _openra_/maps/ra/release-20161019 (game install folder) or in _.openra_/maps/ra/release-20161019 (user files in home folder?)

**Comment by j2k15** [comment]
Hi,

They are in /home/<my user>/Bureau/openra/maps/ra

**Comment by j2k15** [comment]
Hi,

They are in ~/.openra/maps/ra/release-20161019

Like with previous versions.

**Comment by abcdefg30** [comment]
They probably have the wrong map version. You can either redownload them from the resource center or try using the utility to update them: https://github.com/OpenRA/OpenRA/wiki/Utility

**Comment by j2k15** [comment]
I only use customs maps created by Westwood.
So I tried the first one "Pattern of Islands" : http://resource.openra.net/maps/7917/

I does not appear in the available maps in Skirmish mode.

**Comment by pchote** [comment]
That map is for `release-20151224`, and won't be compatible with the newer releases.

**Comment by pchote** [comment]
You can use the 'revisions' link on the resource center to jump to the latest revision of a map, such as http://resource.openra.net/maps/12341 which should be compatible.

**Comment by j2k15** [comment]
OK, I'll retry this evening and close the issue if working.
Thanks for your support.

**Comment by j2k15** [comment]
It's working with maps as of release-20160508.
Issue can be closed.
Thanks for the support.
