### ISSUE TITLE
Travis path resolve broken

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#12823]
`Failed to enumerate mod search path ^/mods: Directory '/home/travis/.openra/mods' not found.`

A relatively recent regression.

Windows/AppVeyor is fine.

**Comment by reaperrr** [comment]
See #12822.

**Comment by pchote** [comment]
Nothing has really changed, I just added some extra logging in one of my recent PRs.

**Comment by reaperrr** [comment]
Well, it seems to only pop up if there's a rules error, for example, but the error message is displayed for every StyleCop check and so on as well, which is at least confusing.

**Comment by pchote** [comment]
it should appear in all travis logs, because a support directory hasn't been created on those fresh checkouts.

**Comment by reaperrr** [comment]
Ok, I guess it's not really an error then. It just looked quite weird to me when I saw it.

**Comment by pchote** [comment]
We can always just remove the logging again.
