### ISSUE TITLE
Add tooltips to production statistics

### ISSUE THREAD

**Issue by abc013** [OpenRA/OpenRA#12820]
![image](https://cloud.githubusercontent.com/assets/21260178/23140994/d822a750-f7b4-11e6-9acb-497d9a628c8b.png)

The current look could cause confusion because (especially in third party mods) icons can be very similar.

**Comment by rob-v** [comment]
I looked at it, but it is more work than usually to add a tooltip to a Widget. In this case, there are more created/updated icons inside 1 Widget.

**Comment by rob-v** [comment]
I have this ready, let me know if it would be interesting and accepted. It is simpler. (the same list is displayed regardless of 'focused' icon, maybe it is even better?)

![obrazok](https://cloud.githubusercontent.com/assets/16348750/24161009/92df30e4-0e63-11e7-90a1-50ae9bb293fa.png)
![obrazok](https://cloud.githubusercontent.com/assets/16348750/24161014/95b776dc-0e63-11e7-9724-3831b689174e.png)

**Comment by pchote** [comment]
Fixed by #13007.
