### ISSUE TITLE
Make an Option to Disable Surrendering

### ISSUE THREAD

**Issue by airetaM** [OpenRA/OpenRA#12821]
Some LUA maps just crash or the Game is ruined if someone surrenders, it would be really nice if there is an option to just disable surrender.
If someone dont want to play further then he could just quit without crashing the game

**Comment by pchote** [comment]
This is already possible, just remove the `ConquestVictoryConditions` trait.  If scripts are crashing on surrender then it is a bug in the map's script that the map author needs to fix.

**Comment by airetaM** [comment]
Ah okay thanks for the answer.
I'ḿ a selfmade mapscripter so my learning progress is going on slowly thx ;D

**Comment by airetaM** [comment]
Hmm i cant start the map anymore if i disable this an get this message in debug.log
at System.Convert.FromBase64String (System.String s) <0x7fe72ff60d80 + 0x0004b> in <filename unknown>:0 
  at OpenRA.MapPreview.UpdateRemoteSearch (MapStatus status, OpenRA.MiniYaml yaml, System.Action`1 parseMetadata) <0x41d60050 + 0x004a0> in <filename unknown>:0 
Failed to load rules for `Room Control` with error :RCrules.yaml:20: There are no elements with key `ConquestVictoryConditions` to remove
MapCache.LoadAsyncInternal ended
Is there a Trait for makeing buildings not destructable, that would solve my problem

**Comment by airetaM** [comment]
Ah sorry i had this in world: not in Player: works now 
but
Now i see what my enemys see

Is there a Trait for makeing buildings not destructable? that would solve my problem

**Comment by obrakmann** [comment]
> This is already possible, just remove the `ConquestVictoryConditions` trait.

Actually it's not.  The logic that handles the surrender order lives in `MissionObjectives`, which cannot be removed, and there's no option to just disable surrendering.

>  If scripts are crashing on surrender then it is a bug in the map's script that the map author needs to fix.

This is still true, though.  Surrendering just sort of "fast-forwards" a player failing all their objectives, so the situation (ie. your crash) could just happen in regular gameplay as well.

> Is there a Trait for makeing buildings not destructable?

Look at how the ra shellmap does it.

**Comment by abcdefg30** [comment]
I don't see this happening for normal games, sorry.
