### ISSUE TITLE
Units Disregard Owned Mines

### ISSUE THREAD

**Issue by RadicalEdward2** [OpenRA/OpenRA#12835]
I don't recall this being an issue in the original game (especially with Ore Trucks) but, owned-units completely disregard placed mines and even park on top of them (detonating them) if they can't move to the exact location they were given (near but not on the mine).

**Comment by FrameLimiter** [comment]
#12337 Makes friendly units aware of friendly mines.

**Comment by RadicalEdward2** [comment]
I don't understand. Is that referring to a newer upcoming build? Because I'm using the most recent one and I just lost 3 heavy tanks and an ore truck because they ran over friendly mines and exploded.

**Comment by FrameLimiter** [comment]
Yes, the issue has been fixed for the next release.

**Comment by RadicalEdward2** [comment]
Update: Player-owned units still run over player-owned mines

**Comment by Mailaender** [comment]
The technical problem is solved, but the feature is disabled for balancing reasons. https://github.com/OpenRA/OpenRA/pull/12967

**Comment by RadicalEdward2** [comment]
I'm aware of that thread but, what was it trying to balance?
