### ISSUE TITLE
"Real tough guy" difficulty doesn't fit the UI

### ISSUE THREAD

**Issue by HenrytheSlav** [OpenRA/OpenRA#12844]
Using this nicely requires changing the UI or changing it to something like Extreme or Very Hard.

![openra-2017-02-24t193522642z](https://cloud.githubusercontent.com/assets/12610736/23318441/b5ca6b54-fad2-11e6-99c9-52ccd576ae78.png)

**Comment by rob-v** [comment]
silly question, where I can find this Difficulty? I don't see it.

**Comment by abcdefg30** [comment]
For example here https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/maps/allies-02/rules.yaml#L24.

**Comment by rob-v** [comment]
thanks. when you select it, it is all visible, but almost without any margin. there is also 'Endless mode' in one map fort-lonestar (though I didn't find this mission in OpenRA).
If preferred we could make it wider, but as 'Real tough guy' is used only in 2 missions, I propose to rename it. It is called tough in rules, so it could be simply Tough (or Very hard better?).
I noticed now that you are Contributor. Do you want to fix it yourself or can I update it for these 2 maps?

**Comment by abcdefg30** [comment]
I'd prefer if the dropdown was made wider, as `Real tough guy` is an allusion to Tanya.

**Comment by rob-v** [comment]
PR created https://github.com/OpenRA/OpenRA/pull/12982

**Comment by joereynolds** [comment]
This can be closed, #12982 fixed the issue and was merged
