### ISSUE TITLE
Spy disguise removed if the spy is targeted

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#12854]
If you target your own spy as target for a disguise he is disguised as a spy this is logical and (right) logically but in game it is a pain to disguise your spies. This is also a bit random as sometimes some of the spies will keep there disguises. In the pictures below you can see the targeted spy losing his disguise and the spy to his left gets his disguise the others do nothing.
![openra-2017-02-26t121911439z](https://cloud.githubusercontent.com/assets/7798635/23339585/4a1bcee8-fc26-11e6-83d4-9bce68acedfe.png)
![openra-2017-02-26t121921695z](https://cloud.githubusercontent.com/assets/7798635/23339584/4a1b8c58-fc26-11e6-8ac9-e7c423658b54.png)

**Comment by Smittytron** [comment]
Reverse duplicate #19182
