### ISSUE TITLE
Turrets following

### ISSUE THREAD

**Issue by CombinE88** [OpenRA/OpenRA#12856]
Turrets following units into the fog of war and lock on the unit till a new target is choosen.
By this you can see where the enemy armee is going throu the fog and shadow,

**Comment by Snurre86** [comment]
This is easy to see when you have been in range of the bots SAM site it will forever know where it is.

**Comment by GraionDilach** [comment]
Turrets also don't drop targets if the target ends up invalidated due to changed TargetTypes. I believe these are related.

**Comment by pchote** [comment]
A fix for this comes along for free in a branch that I hope to PR shortly fixing #11265.

**Comment by matjaeck** [comment]
Good luck!!!
