### ISSUE TITLE
When changing rally point also make primary

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#12855]
When you change a buildings rally point also make that building the primary building.
![openra-2017-02-26t123631476z](https://cloud.githubusercontent.com/assets/7798635/23339737/a6c6b0a2-fc28-11e6-9b00-90482c967650.png)

**Comment by pchote** [comment]
I like this idea, but think it would be best done with a modifier (ctrl+click).

**Comment by Snurre86** [comment]
Do we have to, why would you change the rally point if you did not intend the building to be the primary?
If you need that rally point later you would just change the rally point later when you want to change the primary.

**Comment by Snurre86** [comment]
But then again what happens if you have more then one building of the same type selected when changing there rally points?
![openra-2017-02-26t130224570z](https://cloud.githubusercontent.com/assets/7798635/23339899/392191c6-fc2c-11e6-9155-14f659cf98c8.png)

**Comment by rob-v** [comment]
PR created https://github.com/OpenRA/OpenRA/pull/12977

Set PrimaryBuilding together with RallyPoint when Ctrl is pressed for each building which is the only selected building of that type. Ctrl is optional, could be removed to set PrimaryBuilding.

Barracks + Light factory, Ctrl+Right click = RallyPoint + PrimaryBuilding

![rallypointwithprimarybuilding](https://cloud.githubusercontent.com/assets/16348750/24041792/496b0e80-0b0f-11e7-9cfb-ba17bccfe542.jpg)

2 Barracks = only RallyPoint

**Comment by abcdefg30** [comment]
#12977 was merged.
