### ISSUE TITLE
[TS] Allow for air units that have different altitudes to pass freely through and occupy the same tiles.  

### ISSUE THREAD

**Issue by SamKeightley** [OpenRA/OpenRA#12864]
This is a concept I had though of previously when I was experimenting with giving different aircraft types different altitudes to reflect an abstraction on real functionality. Say for example a helicopter and a fighter jet, where the helicopter would have a much lower altitude than the jet. 

Currently even though these units travel with different altitudes, they bump into each other, which looks quite odd. For mods that use larger numbers of aircraft the chances of these collisions occurring increase.  

Now in the spirit of gauging the dev's interest in this, if this is something you would consider valuable and be willing to have functionality like this in the engine itself, I would be more than happy to look into it, implement it and create PR. I not, I'd be just as happy creating the specific functionality on a per mod basis.

**Comment by pchote** [comment]
Repulsation only applies to aircraft that share the same cruise altitude (see [Aircraft.cs#L246](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Air/Aircraft.cs#L246)).  Are you saying that this check no longer works?

**Comment by SamKeightley** [comment]
Double checked and functionality works as intended. Pleas disregard this issue.
