### ISSUE TITLE
Keyboard debouncing problem

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#12866]
I didn't have this problem on Windows platforms but on my Linux machine, the game seems to get my input twice when I type anything. I tried changing my system keyboard settings for debouncing problems (repetition delay, speed) but the problem is probably with OpenRA, I think. Currently I'm on Plasma Desktop with Linux 4.9.8-1-ARCH #1 SMP PREEMPT Mon Feb 6 12:59:40 CET 2017 x86_64 GNU/Linux. The game is installed via package, which is the latest stable release. (community/openra 20161019-1 [installed])

- Pressing esc opens up pause menu but another esc closes it immediately.
- Pressing z, x, c (sell, powerdown, repair) gets pressed twice that I cant sell/power down/repair with short cut keys.
- Key doesn't get pressed three times that I never get these functions to work by any chance.

Windows is my main platform and dev environment, not that urgent for me though. I wonder if other Linux users have similar problems -- I wonder if it is reproducible on some other Linux distros.

**Comment by forcecore** [comment]
Might be duplicate of #12436, except that I don't use IBus

**Comment by andrewts** [comment]
i have the same
gentoo linux; awesomewm (window manager); keyboard input is through evdev; release-20170421, compiled from source

**Comment by PunkPun** [comment]
Is this still relevant?

**Comment by anvilvapre** [comment]
Many SDL versions later. I would propose to close this unless reconfirmed.
