### ISSUE TITLE
[TS] Some Tiberium is rendered wrong

### ISSUE THREAD

**Issue by abc013** [OpenRA/OpenRA#12876]
![openra-2017-03-03t142709166z](https://cloud.githubusercontent.com/assets/21260178/23554919/3e4c12e4-0027-11e7-982f-f78c40d8373a.png)
![openra-2017-03-03t142713313z](https://cloud.githubusercontent.com/assets/21260178/23554921/3ee4db28-0027-11e7-84d8-fdb7e76e9446.png)

**Comment by pchote** [comment]
This is caused by depth-fighting when pixel doubling is enabled.  #10382 will fix it.
