### ISSUE TITLE
Badger has no icon

### ISSUE THREAD

**Issue by dandels** [OpenRA/OpenRA#12870]
I wanted to train Badger bombers in a custom map so I made them buildable, but the game crashes on entering the aircraft-tab, because Badgers have no icon defined by default. I couldn't find where to add it to make it work for myself, but an official icon does exist: 

http://vignette1.wikia.nocookie.net/cnc/images/5/54/RA1_Badger_Bomber_Icons.gif/revision/latest?cb=20120308043802

**Comment by MustaphaTR** [comment]
You can add it with your map, but it is indeed wierd that it is not defined in here.

You can add 
```
badr:
	icon: badricon
```
to your sequences file/part. To fix it for your map. You can look http://resource.openra.net/maps/19284/ if you didn't understand, that has a buildable badger too.

**Comment by reaperrr** [comment]
Generally speaking, we don't add sequences like icons if the mod in its shipping state doesn't need them. Adding them via map rules like in @MustaphaTR's example is the recommended approach, sorry.
