### ISSUE TITLE
Contrail gets rendered between loading in and loading out position

### ISSUE THREAD

**Issue by abc013** [OpenRA/OpenRA#12877]
![rabug2 gif](https://cloud.githubusercontent.com/assets/21260178/23555416/25f1b8dc-0029-11e7-90e5-e361a05398cc.gif)

Reproducable by giving any ground unit the `Contrail:` trait.

**Comment by pchote** [comment]
This should be easy enough to fix: implement `INotifyAddedToWorld` on the contrail trait and use it to reset the contrail state.
