### ISSUE TITLE
"Connection Failed" when trying to join custom map

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#12881]
Hi, this bug has been existing for a while. if you try to join a custom map, sometimes there shows a "connection failed" error. This only happens in d2k.
![grafik](https://cloud.githubusercontent.com/assets/16046997/23559831/94ef5cc6-0038-11e7-94d6-f3cfe93b43b3.png)

Through testing I could pinpoint it:
using the **PlayerResources** trait in the rules causes this bug.

to reproduce:
1. open two instances of OpenRA: A and B
2. choose [this map](http://resource.openra.net/maps/18574/) with A and try to join with B (->fail)
3. choose [this map](http://resource.openra.net/maps/19769/) with A and try to join with B (->success)

Only difference is PlayerResources removed in (3). 
Also tested in [these revisions](http://resource.openra.net/maps/19768/revisions/) for DefaultCash: and DefaultCashLocked (set-lock, lock-set, no-lock, no-set, nonzero values and values selectable in the dropdown menu (i.e 2500$ instead of 0$ )) but none showed success.

**Comment by rob-v** [comment]
PR created https://github.com/OpenRA/OpenRA/pull/12975

**Comment by rob-v** [comment]
fixed PR https://github.com/OpenRA/OpenRA/pull/12976

**Comment by abcdefg30** [comment]
Fixed by #12976.
