### ISSUE TITLE
tiberium trees are 1 cell higher than they should be on almost all maps

### ISSUE THREAD

**Issue by shpookys** [OpenRA/OpenRA#12884]
did something happen when the maps were converted from older releases to newer ones?
i also heard that the TD maps format was changed or something like that? could that be the issue?

the reason i noticed that the trees changed their position is cause the cell below them is empty in Tiberium patches at the start of the game(and i don't remember seeing this in older releases)

**Comment by pchote** [comment]
Yes, but this was a *long* time ago (between `release-20131223 ` and `release-20140608`).

**Comment by MustaphaTR** [comment]
Didn't 1x2 buildings like Advanced Guard Tower, Tesla Coil, AA Gun, Tiberium Trees, Obelisk and WindMill changed to 1x1 in last or one before last release? his should be the issue. I'll try to find the PR.

**Comment by pchote** [comment]
I strongly suspect that this is only an issue on custom maps that were copied over from the previous release instead of updating.  Theres probably nothing more we can do here, so closing. Otherwise, please file a new issue listing the specific maps that show problems.
