### ISSUE TITLE
Traits-playtest page threw a Travis error.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#12897]
https://github.com/OpenRA/OpenRA/wiki/Traits-%28playtest%29

I would fix that, but the cause should be figured out beforehand.

**Comment by pchote** [comment]
Related to #12823.

**Comment by abcdefg30** [comment]
Removed the warning from the wiki page manually, thanks for mentioning that @GraionDilach.

**Comment by GraionDilach** [comment]
Requesting this to be reopened - the wiki page threw that error again.

**Comment by pchote** [comment]
The problem is that @abcdefg30 didn't cherry-pick #12910 onto the prep branch.  We noticed and fixed that last night after pushing the new playtest.

Somebody should double check that other commits weren't similarly forgotten.

**Comment by abcdefg30** [comment]
Ah crap. Sorry.

**Comment by pchote** [comment]
Don't worry, we've all done it at least once :smile:
