### ISSUE TITLE
Playtest 20170304 Mission campaign 06a allies fails

### ISSUE THREAD

**Issue by xp65** [OpenRA/OpenRA#12895]
The latest playtest 20170304 fails to detect the action of capturing the ore refinery and tech center.

![openra-2017-03-04t211823420z](https://cloud.githubusercontent.com/assets/6690499/23582354/97570522-0128-11e7-8777-0c7b63c7a074.png)

**Comment by abcdefg30** [comment]
I think you're actually supposed to infiltrate those structures with a spy. We should still detect if they are captured though.

**Comment by MustaphaTR** [comment]
I don't think you should win if you capture the lab, actually maybe lose. You meant to infiltrate them, not capture.

**Comment by xp65** [comment]
That's also an english/language issue. If you take over a buiding, you're also infiltrating (how else would you take over a building?). I wasn't thinking about the spy when I read it.  Then at least state "infiltrate with a spy the..."

**Comment by MustaphaTR** [comment]
In CnCs case what spies do is called infiltrating, what engineers do is capturing. Of couse somemone who is not familiar with the game may misunderstand that sentence in objective.

**Comment by abc013** [comment]
we could remove the `ExternalCapturable:` trait on the tech center to prevent this.

**Comment by pchote** [comment]
That would go against the goal of #12806.  Missions shouldn't be making arbitrary exceptions to the standard game just because it makes scripting easier.

**Comment by MustaphaTR** [comment]
I think someone should check the original game to be sure what would happen if we capture the Tech Center.

**Comment by xp65** [comment]
It seems the original Red Alert also allows these buildings to be destroyed and you still win: https://www.youtube.com/watch?v=-sFKVGdDcCk

**Comment by abc013** [comment]
that's the last objective of the mission, it is shown after you infiltrated one of the tech centers.

**Comment by abcdefg30** [comment]
In my opinion you should accomplish the objective when capturing the tech centers. It's not how it was planmed, but hey, you're just supposed to get the information, right? Not sure about the refinery, I'm leaning towards having the objective fail when it is captured, but don't really have an argument for or against that.

**Comment by VolkovChitzkoi** [comment]
I can assure that, infiltrating them makes the system identify as a completed secondary mission, as usual.

**Comment by MustaphaTR** [comment]
If i were a soviet scientiest and i saw an Allied Engineer coming to capture the lab, i would try to eraze the data, before they can capture it. You can't do that for spies.

For Refinery i'm not sure, doesn't the capturing a ref/silo also give some cash. If it does, capturing alsı should make secondary mission conpleted. But if not, it should be failed if it is captured. (There is one ref right?)

**Comment by xp65** [comment]
Well, if the objective is clear, i.e. adding "spy" in the description, I wouldn't mind, then that's just the goal.
About the refinery, when I took it over, the ore truck was also in it, so I got an ore truck for free as well, as seen on the screenshot, giving me new source of income.

I never use spies in multiplayer so, I kinda totally forgot about them when playing this mission :) A simple reminder in the objective would have fixed it. I guess in the original game, there is a video which makes it very clear.

**Comment by abc013** [comment]
Okay, I summarize:
- Adding the "with a spy" to the `infiltrate`-objectives
- fail `infiltrate`-objective if all tech centers are captured (and the `inflitrate` objective isn't completed yet)
- (possible) send a warning if player captured one tech center (and the `inflitrate` objective isn't completed yet)
- complete `cash`-objective also if the refinery is captured

Any other points? If not, I'll make a PR.

**Comment by pchote** [comment]
Please do.  This is now the last thing blocking a new playtest / final release.

**Comment by abc013** [comment]
could you please first merge #12842?

**Comment by pchote** [comment]
Since that has no reviews yet it would be more efficient if you could push your new fixes on top so that they can be reviewed at the same time.
