### ISSUE TITLE
Source tarballs and zips don't have the correct version set

### ISSUE THREAD

**Issue by dtluna** [OpenRA/OpenRA#12907]
The binary versions for releases have correct versions in the game. But if you compile from source, for example, for [latest playtest](https://github.com/OpenRA/OpenRA/archive/playtest-20170304.tar.gz), it will say "{DEV_VERSION}" instead of "playtest-20170304".

**Comment by Snurre86** [comment]
Your PR is really shitty.

**Comment by obrakmann** [comment]
@Snurre86: If you don't have something constructive to add, don't post anything at all. And if you post something like this again, I will block you from OpenRA.

**Comment by obrakmann** [comment]
@dtluna: the source tarball and zip are created automatically by Github from the repository contents, we don't create them ourselves.  And since the files in the repository contain the placeholder, they end up in the archives as well.

I think the proper solution here is to add instructions how to set the version without git installed to the [Compiling](https://github.com/openra/openra/wiki/Compiling) page

**Comment by obrakmann** [comment]
[Which I have now done.](https://github.com/OpenRA/OpenRA/wiki/Compiling/_compare/abb6afc3b9ad40bd18b4f98d6f72b835cd85df33)

**Comment by dtluna** [comment]
@obrakmann No, if I download the source tarball and compile the sources, the correct version is not set.

**Comment by dtluna** [comment]
@obrakmann thank you very much.

**Comment by pchote** [comment]
Since we have moved to a (prep-) branched model and dont care about maintaining linear history i think we could consider implementing a local / automated command that sets the version and then tags *that* commit.

**Comment by GraionDilach** [comment]
I like @pchote's suggestion.

**Comment by Mailaender** [comment]
It would be simpler if we just create a versioned source tarball (maybe tar.bz2) during release compilation that includes all thirdparty libraries, the changelog and a GeoIP database so it builds without any further downloads. :battery: included so to speak.

**Comment by pchote** [comment]
Dependency fetching is platform specific (macOS binaries, linux lua config), so can't be done up front.
