### ISSUE TITLE
Create and add mirrored bridge tiles in the Map Editor.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#12905]
It might not be the easiest thing to do considering shadow work and making it fit other tiles but having a bridge option going bottom-right to top-left in addition to the default would bring about new options for making good naval maps.

Default:
![bridge](https://cloud.githubusercontent.com/assets/2715583/23586268/1fff7d8c-0192-11e7-8c35-451ada78057a.jpg)

**Comment by MustaphaTR** [comment]
I think Nooze already made those, and some other tile stuff. I think we can add those.

But i think this is a duplicate, i remember someone else said thr same thing.

**Comment by SoScared** [comment]
Duplcate of #12874
