### ISSUE TITLE
Subterranean / Jumpjet actors should return to the ground layer when idle

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#12914]

**Comment by KOYK** [comment]
what if you deploy the Jumpjet,and allow Subterranean to stay underground as a trap method? just saying

**Comment by abc013** [comment]
If you disable short game, you would never be able to find and kill units in the underground.

**Comment by KOYK** [comment]
@abc013 hmm yea you are right,and i can't think any a work around.
