### ISSUE TITLE
Turreted units in tunnels will try to attack from underground.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#12917]
I accounted for this for `AttackFrontal` (for the Devil's tongue), but didn't think about other Attack* units inside tunnels.  The [CanInteractWithGroundLayer](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Activities/Attack.cs#L105) check needs to be added to the other attack types.

**Comment by reaperrr** [comment]
What would be the best spot to put this check? I put it [here](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Attack/AttackFollow.cs#L95) and that successfully prevents the unit from shooting, but in my opinion units inside tunnels should also reject orders and continue moving until out of the tunnel, like in the original, to prevent them from being forgotten or intentionally hidden inside tunnels (if it's possible to make units stay in tunnels, players are sure to abuse that in MP).

**Comment by pchote** [comment]
You'll need a second check in the `Follow` activity.

**Comment by reaperrr** [comment]
Are you sure? The problem I see there is that if a unit follows another unit, and the leading unit drives through a tunnel, the following unit will stop inside the tunnel, which is not what we want to happen in this case.

**Comment by pchote** [comment]
The idea is to make the existing check for "am I in range" fail unconditionally if the unit can't interact with the ground layer.  This should force it to do another MoveWithinRange, which is already smart enough to move the actor outside the tunnel.
