### ISSUE TITLE
Unify ingame message prefixes.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#12923]
We still have several messages that are by "Server" (e.g. player drop) or by nobody (game paused/unpaused).  These probably should change to "Battlefield Control".

**Comment by abc013** [comment]
Should modders be able to change the prefix? If yes, how to do that?

**Comment by pchote** [comment]
Via the translation mechanism, once somebody decides to create that.

**Comment by rob-v** [comment]
PR created: https://github.com/OpenRA/OpenRA/pull/12974

**Comment by joereynolds** [comment]
We should close this PR as #12974 has been merged
