### ISSUE TITLE
Selection lost on bridge tiles / impossible to move to bridgehead without attack-move

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#12922]
Hi, an issue especially nasty when controlling flimsy units like Yak's:
![grafik](https://cloud.githubusercontent.com/assets/16046997/23610481/f83b1e3c-0272-11e7-92b8-a7fe73473a6a.png)
When clicking (using left-click orders) the units get deselected. Also is true for ground units. (so without attack move there is NO WAY to position ground units onto the bridgehead)

You would not expect this, since the bridge isn't even selectable. EDIT: ~~This also happens with trees!! This makes using Yaks on maps with lots of trees very hard.~~

If this is fixed I would also propose to make civilian buildings "immune" to clicking, too. (If you want to destroy, you can still force fire there, and hovering the mouse should display the building name)

**Comment by rob-v** [comment]
You're right. You can't move to some bridge tiles (to middle of bridge you can). You also can't move above buildings with left-click orders. I understand you prefer left-click orders, but it seems right-click orders are generally better, you can move also above buildings and bridgers.
As you wrote building is selectable, bridge not so you should be able to move there with left click. If someone can confirm this is bug, I would investigate it.
