### ISSUE TITLE
TD Obelisk target reset issue.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#12926]
When the obelisk locks onto a target but drives out from its firing range it will not target another unit. However if you press S for stop itll start a new target.

**Comment by ltem** [comment]
The solution for this issue, could possibly fix the turret-follow-issue (#12856).

So that if the enemy is out of weapon range and the unit cannot follow the enemy even if it is insight (because it is a tower/structure/immobilized), it will stop "targeting" it
