### ISSUE TITLE
Mousover tooltip for map names, difficulties and more

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#12930]
We have issues with long map names #12595 and difficulties #12844 .
There are other cases, like what kind of map categories and more. 
More uses of tooltip will fix this.

**Comment by rob-v** [comment]
PR  #13005,  #12982 (closed)

**Comment by reaperrr** [comment]
#13005 and #12982 have been merged, and fixing this entirely would require increasing the UI size which has disadvantages of its own (bad for low-res screens), so I assume this can be closed.
