### ISSUE TITLE
Closing a player slot in the lobby ought to trigger an option for spawn point.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#12936]
In case you want to close down specific spawns. A lot of maps has multiple team options with various sizes. Negotiating with players manually through the chat can often be time consuming and it's not always fun 
to order players around verbally.

**Comment by pchote** [comment]
I would prefer letting admins adjust the spawn/team/etc of any player on the server.

**Comment by SoScared** [comment]
I like that idea. Can't we have both? :v:

**Comment by rob-v** [comment]
PR create https://github.com/OpenRA/OpenRA/pull/13002

Host can change Team and Spawn of any player to make it simpler and quicker to setup new game.
Adapted for all our mods. New mods will also have this feature. Existing external mods with custom lobby_players screen will keep current functionali (Team and Spawn readonly for Host), but they can simply adapt it to support this feature.

SoScared's initial idea isn't clear for me, I assume it would be harder.

**Comment by rob-v** [comment]
An idea: with this PR host can change team/spawn of players. we could allow host to change it for slots in advance. so joined players could simply accept it or change it. spectators could also simply choose one of ready slots.

![obrazok](https://cloud.githubusercontent.com/assets/16348750/25312266/983e1232-2815-11e7-993a-a59bc5f3239c.png)

**Comment by SoScared** [comment]
Will players be able to override the host or will the settings be locked? Just asking since I'm thinking it shouldn't be locked - if players are for whatever reason uncooperative the host always has the option to kick anyway.

**Comment by rob-v** [comment]
It is not locked.

**Comment by reaperrr** [comment]
Closed via #13002.

**Comment by rob-v** [comment]
I noticed that host can change team and spawn of another player also when he is 'ready'. It might be better to allow it only until player checks 'ready'.
