### ISSUE TITLE
Expected behavior for lua api function "Production: Build"?

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#12931]
I'm using following code to produce vehicles with a GDI weapons factory:
```
AttackPaths = { { AttackPath1 }, { AttackPath2 } }
VehicleProductionTypes = { "jeep", "mtnk", "msam", "htnk" }
VehicleAttackGroup = { }
VehicleGroupSize = 5
VehicleProductionCooldown = DateTime.Minutes(4)

ProduceVehicle = function(building)
	if building.IsDead then
		return
	end

	local delay = Utils.RandomInteger(DateTime.Seconds(12), DateTime.Seconds(17))
	local toBuild = { Utils.Random(VehicleProductionTypes) }
	local Path = Utils.Random(AttackPaths)
	
	local innerFunc = function(unit)
		VehicleAttackGroup[#VehicleAttackGroup + 1] = unit[1]
		if #VehicleAttackGroup >= VehicleGroupSize then
			SendUnits(VehicleAttackGroup, Path)
			VehicleAttackGroup = { }
			Trigger.AfterDelay(VehicleProductionCooldown, function() ProduceVehicle(building) end)
		else
			Trigger.AfterDelay(delay, function() ProduceVehicle(building) end)
		end
	end

	if not building.Build(toBuild, innerFunc) then
		Trigger.AfterDelay(DateTime.Seconds(2), function() ProduceVehicle(building) end)
	end
end
```
I'm expecting that "**building.Build(toBuild, innerFunc)**" returns false if it attempts to produce a vehicle that has a missing prerequisite: Say a mtnk when the hq got destroyed.

It never appears to return false in such a case and thus the entire production comes to a hold. 

I've seen a similar implementation in gdi04b.

**Comment by pchote** [comment]
This appears to be an oversight/bug in the Build function.  It checks that the item is valid for the queue (i.e. that you're not trying to build a helicopter from a weapons factory), and that the queue isn't currently active, but it does not appear to check prerequisites.

**Comment by pchote** [comment]
As a workaround you would need to manually check that the AI has the right buildings before trying to build something.

**Comment by Smittytron** [comment]
Duplicate #10617
