### ISSUE TITLE
Add logic for graduating radius range

### ISSUE THREAD

**Issue by Smittytron** [OpenRA/OpenRA#12948]
It would be helpful to have logic that allows a radius to increase or decrease per set time. 
My idea in particular has to do with RA balance. I’d like to look at giving MCV’s a three cell build radius and then having it expand by one cell every ten seconds until it hits the max radius.
I can see this having more use outside of MCV range in official and unofficial mods. Radioactive decay and siege-tank mechanics come to mind.

**Comment by AoAGeneral** [comment]
Wouldn't this promote more base crawling? O.o

**Comment by Omnomon** [comment]
No, he's trying to make it so that you can't base crawl as quickly. The closest I could get to testing this out was implementing an 8s cooldown before you could deploy anything, which had a drastic effect on the game. This could be a lot more milder, if I could test it out.

**Comment by pchote** [comment]
Why don't you just tweak the existing Adjacency ranges?

**Comment by Omnomon** [comment]
Tweaking the adjacency ranges wasn't an idea people came up with...I'd venture a guess it's because a lot of maps are designed with that 2c adjacency in mind or that people would feel it was not faithful to the original RA.  It would appease a lot of players if the modders were able to implement a RadiusGrowth Interval/Step to the BaseProvider Range trait.

**Comment by GraionDilach** [comment]
I fail to see the reasoning behind "modders-would-like-to-create-increasing-adjacency-stuff". There is no RTS I am aware which had such a logic - closest I can think of is the War3 Undead Blight logic, but even that worked kinda differently (similar to TS veins, if I think about it).

**Comment by Omnomon** [comment]
For the sake of clarity, adjacency is the trait that defines the maximum number of cells that buildings can be placed away from each other, correct? If so, then Smitty and the others are not trying to tweak that trait...it's the BaseProvider Radius of the MCV that they want to change. In a nutshell, people have been asking me to test the 10c BaseProvider Radius as if it were Zerg creep from Starcraft or the blight from WC3.

**Comment by pchote** [comment]
Adding condition support to `BaseProvider` ought to satisfy this without adding a pile of speculative code.

**Comment by Smittytron** [comment]
Closing as base crawling isn't the monster it once was with the defensive stance change.
