### ISSUE TITLE
Option for textsupport as alternative for soundeffects

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#12954]
When i installed the original Dune2, ive noticed that when i dont select a soundcard for music/effects, the game will switch to a subtitle-mode alarming me for all sorts of events that are happening ingame, such as "Harvester deployed", "Construction complete" or "Base is under attack" ... 

Back then in the 90s it wasnt quite uncommon to have a machine with no soundcard so i guess that was the reason for this feature.

However, i think we could use this (as "Silent Mode" -option in the settings) to support people with a hearing disorder so they can play OpenRA without difficulties

![baseunder](https://cloud.githubusercontent.com/assets/9139965/23828877/60280bce-06e0-11e7-8995-d1e1eed1a290.png)

**Comment by rob-v** [comment]
I displayed for test chat lines with notification names (ConstructionComplete, BaseAttack,...) when playing notification. I just had to filter out some notifications like CashTick. We would need to define in some file text for each notification we would like to display.

**Comment by Snurre86** [comment]
Could there be an option for both, so you can hear the sound and see the text it the game is shared or for other reasons?

**Comment by rob-v** [comment]
It could be an option if agreed.

**Comment by MustaphaTR** [comment]
I agree that enabling both should be a thing, when i was playing Dune 2 on phone on last 2 missions i used to close the sound because it is easier to see Missile Launch Detected text than hearing the notification. But it is not really fun to play without sounds either.

**Comment by ltem** [comment]
I think #12209 is somehow related to this topic

**Comment by rob-v** [comment]
PR #13067

![obrazok](https://cloud.githubusercontent.com/assets/16348750/24706354/a4b17446-1a0f-11e7-94cc-6be209cd5e6f.png)

**Comment by Micr0Bit** [comment]
one thing that could be interesting ... instead of the "arrows showing the direction of a ping"

maybe we could add that as a text ... so when someone places a beacon ... then a text like " Player x has placed a beacon -cardinal direction-" (from your current position, or center of the map ...)
