### ISSUE TITLE
Idea: Screenshot

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/OpenRA#12950]
Many games support make screenshot in their game, so I think OpenRA should do too. And It is convenient  if OpenRA has screenshot(Players can share their game play with their friends and developers can post the bug screenshot easily)

**Comment by FrameLimiter** [comment]
You can take screenshots in OpenRA with Ctrl+P:

Settings Menu/Input/Game_Commands

**Comment by cookgreen** [comment]
Oh, i see
