### ISSUE TITLE
Technology Centers and Bio Labs

### ISSUE THREAD

**Issue by RadicalEdward2** [OpenRA/OpenRA#12958]
I'm late to the party so this has probably been discussed multiple times but, I'll just post about it anyway.

**Technology Centers**
![technology_center](https://cloud.githubusercontent.com/assets/25542788/23836106/544a7f3a-0749-11e7-8237-5d5927f39bdb.jpg)

Right now the Technology Center serves no purpose. 
If it was given a feature, it could present the team that captures it with a unit or structure that's exclusive to another faction or a specific country of either faction (regardless of the captors allegiance).

Could be a spy, grenadier, mammoth, phase tank, airfield, iron curtain, flamethrower, chronosphere (or tank), mechanic, medic, Tesla trooper, kennel, heavy tank, etc.

The only reason I bring this up is because in Yuri's Revenge there was the Tech Secret Lab which served that exact purpose.

![vhaps20](https://cloud.githubusercontent.com/assets/25542788/23835917/09ebe47c-0746-11e7-9eb1-d7c2a1efaae7.png)

------

**Biological Labs**
![sarin](https://cloud.githubusercontent.com/assets/25542788/23836160/46f9b552-074a-11e7-906b-a15442049d51.png)

To follow the theme of the missions in the beginning of Red Alert as well as Aftermath/Retaliation, if captured, the Biological Labs could provide access to Sarin Nerve Gas either in the form of Chem Trucks or Chemical Bombing Runs.

![faluuko](https://cloud.githubusercontent.com/assets/25542788/23835926/2f94f0a6-0746-11e7-8f78-2a2a6e8bce99.jpg)

Whereas the Demo Truck and the Airstrikes could damage anything within their vicinity, the Chem Trucks and/or Chemical Bombing Runs could harm and kill ONLY infantry within its area of influence.
It would then leave the green gas effect used for the nerve gas in the campaign (recolor of the flare sprite).

The truck could detonate like the Demo Truck and have a similar blast radius.

In terms of sprite work, I guess the Demo Truck's atomic decal could be recolored green instead of yellow.

------

![itcamefromredalert_poster](https://cloud.githubusercontent.com/assets/25542788/23836062/48d2d84c-0748-11e7-807e-46d7ef00e590.jpg)

I've heard that the Bio Labs were going to produce zombies and ants which seem kind of out of place. I know "It CAmE FrOm ReeEeeed AleEeeErt oooOoOoo~ spoooOooky~ !" 
I still have the folder with the promo ant wallpaper and desktop theme on my laptop (cause I use the interface sounds for my desktop theme). 

But, I never was crazy about those ants or the dinosaurs. It just came off as out of place but, at the same time, Jurassic Park came out when Dawn did and "Mars Attacks!" came out the same year as Red Alert 1 so throwing in cheesy B Movie horror monsters was a fun little gag but, it was better off on its own; not as an ongoing feature.

If you guys are dead set on having an entrepreneur mad scientist lab that wants to capitalize on the market for BOTH giant insects AND Soviet (not Nazi) zombies then, maybe at the very least make two versions of the Biological Lab:

One for the Sarin and another just for the B-Movie stuff.

![g1zgdrk](https://cloud.githubusercontent.com/assets/25542788/23835982/05b944e8-0747-11e7-9f6d-2a510442840b.jpg)

Or better yet, use some assets for some of the fan-made castle stuff to make a spoopy castle for the zombies and ants and keep the Bio Lab just for the chemical warfare. 

I think I was one of the only people playing the game back in the day that said, "They get tanks with two barrels, lightning tanks, AND poison gas?! Why can't I use poison gas?!" 

Opting to make the campy gag units available as part of the norm in a Red Alert/C&C game is just weird because it'll go against the whole "too much of a good thing" motif and the zombies and ants will quickly lose their novelty value (much like the zombie game genre today).

That's just my thought on the matter though.

![tech tech](https://cloud.githubusercontent.com/assets/25542788/23835962/bd1ac8d8-0746-11e7-8d9f-53edd354d960.png)

I wouldn't say the Tech Lab placement would need to be fixed in existing maps. Most of the time, people place hazards near them in anticipation of them someday serving a purpose.
In fact, almost every map that features the Tech Lab has barbed wire and barrels around it or even entire concrete wall perimeters. 

https://www.youtube.com/watch?v=x6loeCpRBZ4

The Renegade X style of adding new tech would be cool. Maybe instead of adding Tiberian Sun tech it could add Tiberian Dawn tech to save on resources by reusing existing ones.

While the one additional unit would be completely random, it could add some interesting tech. 

- If a faction owns an airfield, they could get the Warthogs (the jets used in the airstrikes).
- If a faction owns a helipad, they could get either the Apache or the Orca.
- They could even get the Advanced Comm Center to grant access to Ions but, since it's being used against 1940s buildings, it would be a 1HK against whatever is directly under the crosshair (cursor).

I don't think the Temple would be necessary though. Maybe Dawn vehicles with slightly more damage than all standard vehicles would be okay.
Ex: GDI Medium Tank could do as much damage as a Heavy Tank and slightly higher damage resistance than the RA version. 

I won't go too in-depth since this is all essentially wishful thinking.

But, yeah, the possibilities would be endless.

**Comment by atlimit8** [comment]
> Right now the Technology Center serves no purpose.
It is present for missions such as allies-05a (where it is a prison for Tanya) that use it.

**Comment by RadicalEdward2** [comment]
I am completely aware of that. I'm talking about about giving them a purpose.

**Comment by atlimit8** [comment]
If you want to make a modified version of the ra mod, you could ask on the IRC channel; however, we do not just throw new actors/units into the shipped mods. Not that long ago there were arguments over different replacements for Hind that fell apart and the PRs are now closed.

**Comment by RadicalEdward2** [comment]
I see. Well, I guess do as you please with my proposal. I just thought it would have been interesting to actually see Sarin nerve gas as a weapon.

**Comment by atlimit8** [comment]
No interest.
