### ISSUE TITLE
Sort 'Playing' games in the lobby by play time.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#12959]
'Playing' games are now sorted top-bottom by the amount of players in a match as with 'Waiting' games. You can sort of get an idea of how many players are online by looking down the 'Playing' servers to the top.

Still I think I'd find it more interesting to see what games started moments ago vs games that has elapsed for longer by progressively looking down the list.

**Comment by Phrohdoh** [comment]
I do not understand what players would gain from this.
If a game is being played you cannot enter it regardless of length.

**Comment by SoScared** [comment]
I can only speak for myself but now and then I look through the 'Playing' list to look for games I've missed the boat on (what happened to the game that was just here) and sometimes waiting for specific matches to be over in order to catch up with a certain player or group of players.

**Comment by rob-v** [comment]
PR created https://github.com/OpenRA/OpenRA/pull/12973

**Comment by Snurre86** [comment]
Would also like F5 to refresh or auto refresh the multiplayer lobby.

**Comment by SoScared** [comment]
> Would also like F5 to refresh or auto refresh the multiplayer lobby.

Juicy :+1:

**Comment by obrakmann** [comment]
Closed by #12973.
