### ISSUE TITLE
Volkov (Soviet Tanya)

### ISSUE THREAD

**Issue by RadicalEdward2** [OpenRA/OpenRA#12957]
I have proposed this idea on the forum but, decided to pitch the idea here as well with some additional notes I've compiled from both playing OpenRA and reception received on the forum.

As a disclaimer, I have never played Mental Omega and only know of the characters from playing the original games on CD. 

------

I noticed that with all the new vehicles and abilities added to Red Alert, there actually are some preexisting assets that somehow haven't made a return yet.

Sure everyone remembers Tanya, the RA Lara Croft-turned-007 via countless re-castings but, what about the Soviet "Tanya"? 

I'm not talking about Boris. I'm talking about Volkov and his canine companion, Chitzkoi.
http://cnc.wikia.com/wiki/Volkov
http://cnc.wikia.com/wiki/Chitzkoi

For those of you that don't remember, Volkov, was a Russian cyborg supersoldier armed with a sniper rifle for long range, high powered pistol for close range, and a heavy explosives cannon for air units and naval/ground vehicles.

He was an underrated character that was even supposed to return in Red Alert 2 but, was ultimately cut despite still appearing on the cover art.

![ra2-cover](https://cloud.githubusercontent.com/assets/25542788/23835470/43919bf2-073e-11e7-8d21-128a7de0fe99.jpg)

Like Volkov, Chitzkoi was cut from Red Alert 2 as well and only appeared in campaign missions.
He was cybernetically enhanced like Volkov with his own sets of perks to boot.

Despite resembling the average attack dog, he was capable of scaling cliffs and could take a few more beatings than a regular Attack Dog. Despite being a cyborg dog, he could still be crushed by vehicles, however, he had a movement speed of 8 as opposed to the Attack Dog movement speed of 4 (the increased speed can be achieved in the current build of OpenRA by having dogs walk on roads).
Interestingly, all Attacks Dogs in the game inherited Chitzkoi's cliff climbing ability.

To keep up with the new additions that came with OpenRA, both units could be able to detect cloaked units.

---------

- Below are additional notes I compiled after receiving feedback on the forum -

I have heard some concerns about Volkov being "overpowered" but, in the original Red Alert, both factions had access to Tanya but, this did not carry over into OpenRA.

Right now, the Soviets don't have a Hero unit and the sprite work for Volkov is in the original game's files (or the expansions) so it wouldn't require a complete recreation from the ground up.

If we were to really take a moment to look at Volkov, he's just a Mammoth Tank in infantry form which isn't all that OP if you think about it. 

Since the Sniper already exists in-game and may be going to England, why not repurpose Volkov into being a Soviet anti-vehicle and infantry sniper?

Instead of giving him a high-powered pistol (like RoboCop), give him a PTRD (the Russian anti-armor rifle from WW2). https://en.wikipedia.org/wiki/PTRD

He could use the PTRD to inflict rocket launcher-like damage to vehicles from a safe distance and 1HK towards infantry (maybe 4 shots against Tanya for balancing). 
To add to the gory nature of classic Red Alert, firing the rifle at infantry could make them explode (as if they were killed with a grenade). Essentially, he would become the equivalent to Havoc in C&C: Renegade (or RenX) multiplayer. He could have the movement speed of a grenadier or rifleman.

Being a cyborg, he would keep his explosive canon for warding off aircraft. Also, he can't be crushed by vehicles (because cyborg and that would be a waste of about $1000 and he was also uncrushable in Aftermath). 

Like Tanya, only one of each (Volkov and Chitzkoi) can be present at any given time (unless given via crate) and like the Mammoth, he could regenerate 50% of his health (introduced in Counterstrike except regenerated 100%). 

For the sake of balancing, Volkov's PTRD could have the same fire rate as a medium tank (giving the illusion of reloading since it's a bolt-action). He also wouldn't be able to C4 buildings; making that a trait exclusive to Tanya (outside of campaign missions). His effective range could be one tile further than artillery or V2 to avoid having a game of "who will die first". 

Another suggestion to add some flare to his character, his death animation could be the electrocution death animation by-default (because cyborg).

If you guys don't want to add Chitzkoi, that's up to you. I heard he could attack vehicles in Mental Omega but, that sounds a bit too overpowered. Since he's just a dog, his price could be a fair $800 instead of $200.

I think that covers everything until I come up with something else to add later.
Do as you please with my proposal. I mean there's ants, zombies, and tech that was never in the original games so Volkov would be a considerably tame addition to the Soviet arsenal.

**Comment by pchote** [comment]
This idea has been suggested and rejected many times now.

The main issue always comes back to: What gameplay issue is this supposed to solve?  Adding units just "because why not?" is horrible game design.

> Right now, the Soviets don't have a Hero unit 

The factions are deliberately assymetric.  Why should the soviets have a hero unit?

> the sprite work for Volkov is in the original game's files (or the expansions) so it wouldn't require a complete recreation from the ground up.

Volkov was an expansion pack mission specific unit.  He didn't have his own artwork or rules, but instead was implemented with custom map rule overrides on the existing "field marshal" civilian.  The only reason that he is different to e.g. the Super Tanks in Monster Tank Madness is that he was used across more than one mission.

**Comment by RadicalEdward2** [comment]
I guess that logic could be used but, that didn't stop adding the Phase Tank, Flak Truck, Sniper, or the Supply Truck.

Also, even if he wasn't actually on the cover art, he would at least make more sense than adding zombies to the game. Considering you threw out the whole "Add units because why not?" logic. 
I never said, add him just because. I have my reasons. 

Sure, the tech trees would still be asymmetrical (because Allied air units can attack Soviets air units but, not vice versa) but, at least make a Hero unit based on the existing character to fill the gap with something that fits the Soviet's vehicle based arsenal with an infantry unit that can take out vehicles like a sniper.

**Comment by pchote** [comment]
The Flak Truck and Supply Truck were all added to fix specific gameplay problems.  The sniper was removed as a buildable unit exactly because it no longer had a useful ingame role.

I have heavily argued for removing the sniper and zombie artwork completely from OpenRA, and they only exist now because other developers like them for reasons that I can't understand.  Responses like your demonstrate why keeping them is bad – they have set a precident for adding things that really should not exist in OpenRA.

**Comment by RadicalEdward2** [comment]
Now that I know that I'm not the only one that hates the zombies, I can at least agree with that point. Making the Sniper available could still work as a sub-faction specific unit since Britain had it in RA2. Except, they would have to have a range that's on-par to the Commandos.

**Comment by atlimit8** [comment]
No interest.
