### ISSUE TITLE
TD Nod mission 06a airstrikes.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#12961]
In the mission Nod06a when you attack the village as the secondary objective it triggers an airstrike from the AI and the three planes instantly kills the army. This renders completing the secondary objective impossible.

**Comment by Snurre86** [comment]
The first strike is at about 3:40 so clump then scatter the units right before this time.

**Comment by Smittytron** [comment]
Can confirm, the airstrike will wipe you out unless you are gaming the system with everything spread out with one unit triggering the airstrike. Might be more fitting in a 'Real tough guy' difficulty.
