### ISSUE TITLE
TD Campaign AI Harvesters.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#12962]
Whenever the AI runs out of the tiberium field or rebuilds a harvester they love to hug the bottom right of the map rather then finding more tiberium. (IE: Nod mission 07b)

**Comment by pchote** [comment]
This can be solved by enabling the `HarvesterBotModule` for the scripted players in campaign missions.

**Comment by PunkPun** [comment]
Probably the same issue as #16205 which was fixed
