### ISSUE TITLE
VeteranProductionIconOverlay doesn't update if Prerequisites are removed

### ISSUE THREAD

**Issue by theKalash** [OpenRA/OpenRA#12963]
In my custom mod I noticed that the VeteranProductionIconOverlay isn't removed if the Prerequisite for ProducibleWithLevel is removed (I granted the Prerequisite via a building instead of infiltration).

So if the building is destroyed it will still show the production Icon with the overlay but the units will no longer be produced with veterancy.

**Comment by WolfGaming** [comment]
This seems to be a simple fix as if you look at the bottom of
https://github.com/OpenRA/OpenRA/blob/285e9a803067ddf8bbfee3b89f487029d6118833/OpenRA.Mods.Common/Traits/Render/VeteranProductionIconOverlay.cs
You see it simply doesn't implement PrerequisitesUnavailable.
maybe add
```
var ai = self.World.Map.Rules.Actors[GetName(key)];
overlayActive[ai] = false;
```
into PrerequisitesUnavailable?

**Comment by abcdefg30** [comment]
That worked, thanks @WolfGaming.
