### ISSUE TITLE
UncloakOn: Damaged is trigged by SelfHealing

### ISSUE THREAD

**Issue by theKalash** [OpenRA/OpenRA#12964]
A unit with Cloak Trait with UncloakOn: Dock and a SelfHealing Trait will uncloak as soon as the selfheal triggers.

not quite sure if this is intended. I expected it to only apply to repairs/rearm from the designated building.

**Comment by forcecore** [comment]
Self healing is - damage so it could be uncloak on Damage not Dock.

**Comment by atlimit8** [comment]
`SelfHealing` does not trigger `UncloakOn: Dock`, but it does trigger `UncloakOn: Damage`.

**Comment by theKalash** [comment]
Oh yeah .. I mixed that up. 

However now that I rechecked it was actually _Damage_ that uncloakes while repairing at a naval yard too .... so what does _Dock_ actually do?

**Comment by pchote** [comment]
Harvesters docking with a refinery.

**Comment by Unit158** [comment]
I've started work on a patch
