### ISSUE TITLE
Investigate renaming OpenRA.Game to OpenRA.Engine

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#12988]
It would be more correct and less misleading, especially on Windows with its separate launcher exe(s).

Related to #12554 and #12966.

**Comment by pchote** [comment]
Please wait until my next big mod-support PR before considering this, because that will affect the discussion of this.

**Comment by abcdefg30** [comment]
What is the status here?

**Comment by pchote** [comment]
#17989 will address this by changing `OpenRA.Game` from an executable to a library.
