### ISSUE TITLE
Tile errors on the map Vihaan Lunta

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#12998]
This map was introduced into the official RA map pool by #12767 but has a few bad tiles.

Bad tile locations:
49,60
51,62
51,67
45,59
39,68
106,83 (non-issue; under shroud)
70,0 (non-issue; under shroud)
44,106 (non-issue; under shroud)
56,98 (ore on cliff)
50,69(misplaced piece of ore)

*This map also contains out of bounds ore under the shroud for most of the exterior patches.  (I left this unchanged.)
Link to revision:
http://resource.openra.net/maps/20046/

**Comment by SoScared** [comment]
Vihaan Lunta was slightly altered with #12933 could you cross check these tile errors with this version?

**Comment by FrameLimiter** [comment]
Sure,
The errors are also present in that version as well.
Here is a revision using the latest version of the map from #12933:
http://resource.openra.net/maps/20064/

**Comment by SoScared** [comment]
:+1: will add it to the latest PR commit later today

**Comment by reaperrr** [comment]
Fixed in #12997.
