### ISSUE TITLE
Tile errors on the map Ensio Kaivo

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#12994]
This map was introduced into the official RA map pool by #12767 but it has a number of bad tiles.

Bad tile locations:
12,102
59,106
108-111,91
94,75
106,59
108,55
103,29
94,19
11,62
22,25
10,0(non-issue; under shroud)
0,16(non-issue; under shroud)

I've fixed all the tile errors except the one at 22,25 as it is quite minor and requires an altered design to fix.

Link to revision:
http://resource.openra.net/maps/20035/

**Comment by SoScared** [comment]
👍 This map slipped through the quality check process, my bad.

I think generally you can edit maps structure if it's not intrusive.

**Comment by reaperrr** [comment]
Fixed in #12997.
