### ISSUE TITLE
Unsupported OpenGL version on Intel Atom N450 (GMA3150)

### ISSUE THREAD

**Issue by VoodooJungle** [OpenRA/OpenRA#13004]
Hi! I'm trying to run OpenRA on my ASUS EeePC 1005PE netbook equipped with an Intel Atom N450 processor (integrated Intel GMA3150 graphics processor) and 2GB or RAM. OpenRA fails to run claiming that OpenGL 1.4.0 is not supported. What is the minimum OpenGL version is required to run the game? Thanks!

Here is the graphics.log file.

Unsupported OpenGL version: 1.4.0 - Build 8.14.10.2230

OpenGL Information:
Vendor: Intel
Renderer: Intel Pineview Platform
GL Version: 1.4.0 - Build 8.14.10.2230
Shader Version: 
Available extensions:
GL_EXT_blend_minmax GL_EXT_blend_subtract GL_EXT_blend_color GL_EXT_abgr GL_EXT_texture3D GL_EXT_clip_volume_hint GL_EXT_compiled_vertex_array GL_EXT_cull_vertex GL_SGIS_texture_edge_clamp GL_SGIS_generate_mipmap GL_EXT_draw_range_elements GL_SGIS_texture_lod GL_EXT_rescale_normal GL_EXT_packed_pixels GL_EXT_separate_specular_color GL_ARB_multitexture GL_EXT_texture_env_combine GL_EXT_bgra GL_EXT_blend_func_separate GL_EXT_secondary_color GL_EXT_fog_coord GL_EXT_texture_env_add GL_ARB_texture_cube_map GL_ARB_transpose_matrix GL_ARB_texture_env_add GL_IBM_texture_mirrored_repeat GL_EXT_multi_draw_arrays GL_NV_blend_square GL_ARB_texture_compression GL_3DFX_texture_compression_FXT1 GL_EXT_texture_filter_anisotropic GL_ARB_texture_border_clamp GL_ARB_point_parameters GL_ARB_texture_env_combine GL_ARB_texture_env_dot3 GL_ARB_texture_env_crossbar GL_EXT_texture_compression_s3tc GL_ARB_shadow GL_ARB_window_pos GL_EXT_shadow_funcs GL_EXT_stencil_wrap GL_ARB_vertex_program GL_ARB_fragment_program GL_EXT_stencil_two_side GL_ARB_vertex_buffer_object GL_EXT_texture_lod_bias GL_NV_texgen_reflection GL_ARB_depth_texture GL_WIN_swap_hint 
System.InvalidProgramException: OpenGL Version Error: See graphics.log for details.
   at OpenRA.Platforms.Default.OpenGL.Initialize()
   at OpenRA.Platforms.Default.Sdl2GraphicsDevice..ctor(Size windowSize, WindowMode windowMode)
   at OpenRA.Platforms.Default.DefaultPlatform.CreateGraphics(Size size, WindowMode windowMode)
   at OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings)
   at OpenRA.Game.Initialize(Arguments args)
Unsupported OpenGL version: 1.4.0 - Build 8.14.10.2230

**Comment by MustaphaTR** [comment]
Minimum OpenGL version required is 2.0.

**Comment by obrakmann** [comment]
The GMA3150 windows driver only supports OpenGL 1.5, you need to run Linux to get OpenGL 2.1 and make it work with OpenRA. Nothing we can do here, closing.
