### ISSUE TITLE
Condition support for AmmoPool Trait

### ISSUE THREAD

**Issue by theKalash** [OpenRA/OpenRA#13013]
Have been playing around with units that gain or change weapons via upgrades but ran into Problems with this.

For example if you have a unit with two Armament both with it's own AmmoPool but the secondary Armament is disabled, the unit will not return to reload (because it still has Ammo in the inactive pool).

Also it would be nice if you could hide the Pips as long as an Armament is disabled. 

In addition:
Maybe even allow conditions instead of boolean values for things like _SelfReloads_ or _ResetOnFire_

**Comment by MustaphaTR** [comment]
I think it should be possible to not render a Ammo pip even tho unit has an Ammo Pool,i think it is not now (or ypu can define empty pip image but that would be hacky). It was possible in RA2 as Pips and Ammo was handled with different tags.

**Comment by theKalash** [comment]
Well you can hide pips with _PipCount: 0_ but that means they are permanently invisible and can't be enabled with conditions later on.

**Comment by MustaphaTR** [comment]
Oh, good then, i thought it was not possible.

But yes you are right there are still lots of Traits that would be good to have proper condition support.

**Comment by reaperrr** [comment]
I have this on my roadmap, but no promises on when it will land.

**Comment by reaperrr** [comment]
This was effectively resolved in #13538 (except for the pips, which I consider a separate issue).

**Comment by GraionDilach** [comment]
Did the pips get a separate ticket? Because I was looking for the history to find one and I can't find it.

**Comment by reaperrr** [comment]
Don't think so. Filed #17346.
