### ISSUE TITLE
dog training must wait the soldiers trained completed in playtest20170304

### ISSUE THREAD

**Issue by carlos444** [OpenRA/OpenRA#13022]
RA mod: Russia kennel was a independence building, when barrack and kennel built, and training soldiers and attack dogs, dogs must wait the soldiers trained completed. But I think dog and soldiers should training at the same time.

**Comment by carlos444** [comment]
![openrabugs](https://cloud.githubusercontent.com/assets/2613235/24322641/8b69712e-11a3-11e7-9e3b-25f436bb9d58.png)

**Comment by Wobling** [comment]
So dogs should train independently of infantry?

**Comment by carlos444** [comment]
because dogs and soldiers come out of the different building.

**Comment by Nineeva** [comment]
This will give the soviets a huge advantage early on as they'll have two useful lines of production and make it very easy to rush other players.

**Comment by pchote** [comment]
This is intentional, and consistent with the original game.  I recommend posting about this on the forum, as github is not a good place for open-ended balance discussions.  Closing as this isn't really an actionable ticket.
