### ISSUE TITLE
[TS]GDI & NOD Advanced PowerPlant at the different tech level.

### ISSUE THREAD

**Issue by carlos444** [OpenRA/OpenRA#13026]
in bleed branch (download 2017-03-26)NOD Advanced PowerPlant require NOD Vehicle Production, but GDI PowerTurbine Just need GDI PowerPlant.

**Comment by theKalash** [comment]
Pretty sure that's how it's been in the original. 

NOD has two powerplants, with the advanced unlocking after the war factory, GDI only has a basic ones but can be upgraded.

**Comment by reaperrr** [comment]
Yes, the tech level setup matches the original game. Currently our plan is to stick to the original as much as possible, so this is a "won't fix" issue.
