### ISSUE TITLE
Crash System.InvalidOperationException when clicking on map after harvester attacked

### ISSUE THREAD

**Issue by TheLEAX** [OpenRA/OpenRA#13032]
Hello, Im new one, played this game - Dune 2000 Mod at Version playtest-20170304 - for the first time and after a while I got a crash with this log :
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (harvester 108 (not in world))
more in file attachment 

[exception-2017-03-29T192601Z.txt](https://github.com/OpenRA/OpenRA/files/880195/exception-2017-03-29T192601Z.txt)
[debug.txt](https://github.com/OpenRA/OpenRA/files/880198/debug.txt)

**Comment by pchote** [comment]
Repro case:  add `self.World.AddFrameEndTask(w => cargo.Dispose());` to the bottom of `PickupUnit.Attach` and wait on the d2k shellmap.

**Comment by rob-v** [comment]
@pchote Thanks to your repro case it was easy to reproduce. This worked for me as bug fix, but I don't know if the correct one, so feel free to ignore it:

```
Carryall:
		IEnumerable<IRenderable> IRender.Render(Actor self, WorldRenderer wr)
		{
		 	if (State == CarryallState.Carrying)
			{
				if (Carryable.Disposed)
				{
					DetachCarryable(self);
					yield break;
				}

			}
			// …
		}
```

**Comment by pchote** [comment]
Modifying the simulation state from the rendering code will cause desyncs in MP games.
