### ISSUE TITLE
"Watch Briefing" button not available for 03a and 03b: Dead End

### ISSUE THREAD

**Issue by Thunderforge** [OpenRA/OpenRA#13037]
In Red Alert, the "Watch Briefing" button is not available for 03a and 03b: Dead End. 

![dead end mission select](https://cloud.githubusercontent.com/assets/6200170/24532720/254b9e06-1588-11e7-9012-d5159d25db48.png)

Every other mission (aside from Aftermath/Counterstrike missions) has a "Watch Briefing" button in the bottom left corner of the window. These two are missing it.

**Comment by Biofreak1987** [comment]
Dead End has no Briefing Videos. It only displays the text.
![2017-03-31_10-57-54](https://cloud.githubusercontent.com/assets/4711816/24543811/3a08728c-1601-11e7-82f0-ab808c9bcd0e.png)

**Comment by abcdefg30** [comment]
I don't think we can do much here. Thanks for the report though. :)
