### ISSUE TITLE
Missing Interior Corner Tile

### ISSUE THREAD

**Issue by RadicalEdward2** [OpenRA/OpenRA#13035]
I decided to try my hand at making an interior skirmish map and discovered there's a missing corner tile.
To better assist in finding the missing tile, I provided a screenshot from the mission, Mousetrap, from Aftermath.

![missing interior tile](https://cloud.githubusercontent.com/assets/25542788/24485086/020f6836-14d0-11e7-8654-aeeb7871ba5b.png)

CORRECTION: Apparently the missing tile is labelled as a "floor" tile.

**Comment by RadicalEdward2** [comment]
Brown walls are also missing. Same goes for "green crates".
![missing interior object](https://cloud.githubusercontent.com/assets/25542788/24485450/8a9cb896-14d2-11e7-8daf-458da44d675c.png)

**Comment by airetaM** [comment]
The missing corner tile is just listed in the floor tab
