### ISSUE TITLE
Would an espionage building be helpful?

### ISSUE THREAD

**Issue by fusion809** [OpenRA/OpenRA#13044]
Hi,

One feature I have seen on other RTS games that resemble OpenRA (e.g., Outlive) is an espionage building which users can use (for a charge and these capabilities may take some time for them to come into affect after the user selects them, sort of how it takes a while to create military units and buildings) to spy on their enemies (see everything their enemy sees, see their finances), lock their buildings (rendering them unusuable for several seconds), redirect/neutralize atomic bombs, view a small segment of area presently under the fog-of-war, *etc.* Not sure if anyone is interested in adding such a feature to this game, but it would certainly be enticing to me. 

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
I know that there are spies and England's special ability is espionage, plus there's the sky plane ability to view a small area under the fog of war, but still an espionage building might be a pleasant addition to the game.

**Comment by Cr0s** [comment]
Hi.

There's already implemented features for building infiltration such as:

- Infiltration of Ore Refinery steals the credits from victim player
- Infiltration of Power Plant with spy causes temporary power down of entire victim's base
- Infiltration of Barracks will give the additional rank boost for the infantry units produced by offender player
- Infiltration of Sub Pen will give a Sonar Pulse ability for the offender player (not sure about that tbh)

And maybe something else that I might forget, but as you can see, there's a plenty of benefits from espionage against enemy's buildings that already implemented.

**Comment by atlimit8** [comment]
I think @Cr0s is referring to a building that has spying abilities along the lines of the GPS support power but with production costs. If that is the case, support power proxy actors can be produced.

**Comment by pchote** [comment]
Thanks for the ideas!  Our official mods are aiming to remain close in spirit to the original games, so we're not looking to implement new buildings or support powers, but these could be useful for community mods.  I'm going to close this ticket since it isn't actionable, but feel free to repost these on the community forum.
