### ISSUE TITLE
TS building light animations need to glow in the dark

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#13046]
All building light overlays in the original were unaffected by map lighting, so we need to define a separate palette for them that won't get modified by global lighting and such.

**Comment by pchote** [comment]
What about explosions and muzzle flashes?

**Comment by reaperrr** [comment]
Yeah, those too. I consider that a separate issue, though (at least as far as PRs are concerned, because muzzles in infantry sprites will require some additional palette magic).

**Comment by pchote** [comment]
> The original game used ... Normalized=yes/no for the whole art.ini entry (yes = affected by map lighting), and hardcoded for the indices 240-255 of the player palette.

Do we need to support different index ranges for different palettes / only applying to some palettes, or can we get away with disabling effects for the same index ranges on *all* palettes?

**Comment by reaperrr** [comment]
> Do we need to support different index ranges for different palettes / only applying to some palettes, or can we get away with disabling effects for the same index ranges on all palettes?

If we disabled global lighting for the last 16 indices on _all_ palettes in TS, I'm afraid that would break some terrain (though I haven't tested this).

**Comment by GraionDilach** [comment]
Water's using the last indices on the terrain palette in TS.

**Comment by pchote** [comment]
The core of this feature is easy to do: the following line just needs to change to `< 240`:
https://github.com/OpenRA/OpenRA/blob/3cf9d47b39601cb1daa9053cfee471809057b831/OpenRA.Mods.Common/Traits/PaletteEffects/GlobalLightingPaletteEffect.cs#L73

The problem, as @GraionDilach mentioned, is that this breaks the water shore rendering.  To fix that we need to be able to be able to specify at least two different sets of index ranges for terrain (up to 255) vs everything else (up to 240), which isn't going to be possible without compatibility-breaking changes to `GlobalLightingPaletteEffect`.

The "easy" (but bogus) option would be to support multiple `GlobalLightingPaletteEffect`s, one for the terrain, and the other for everything else.  This then breaks the Lua API, as well as making the map overrides slightly uglier.

The viable approach is to define a new way of defining palette:range pairs on the traitinfo, but this is going to depend on a larger reworking of our palette modifier infrastructure so as to not hurt performance.

**Comment by pchote** [comment]
Note: Most of the discussion above was mode obsolete by #18310 which changed the global lighting implementation from a palette modifier to vertex-based lighting in the shaders. We can now opt specific sequences out of the lighting effects using `IgnoreWorldTint: True` (see #19122), but this doesn't help the case where there are a mix of tinted and non-tinted palette indices within the same sprite. Starting again from scratch:

I spent a bit of time last night auditing which sprite frames use these high range indices, and then checking how they behave ingame. It seems that different behaviours are hardcoded for different units (or different techno or animation types?).

e.g:
* e3.shp uses the blue range between 250-255 on its barrel, which definitely *isn't* bright ingame.
* floater.shp uses the blue range between 250-255 for its electro attack, which definitely *is* bright ingame.
* Various infantry animations (stand, run, etc) use indices 240-245 which don't make sense to be arbitrarily bright, while various building animations using these (e.g. the lights above the GDI barracks door) definitely should be bright.

This arbitrary behaviour tips the balance away from implementing this as an engine feature and towards doing it using sequence workarounds. We can add a new `WithTSInfantryBody` trait that renders the attack animation twice, once with normal tint effects and indices 245-249 set to transparent, then again with tints disabled and everything except indices 245-249 set to transparent. Buildings can do the same thing (but with differerent index sets) using the existing overlay traits.

I'll work on this as a followup to #19122.

**Comment by pchote** [comment]
This approach works pretty well, although it ended up being fiddlier than I expected:

<img width="607" alt="Screenshot 2021-02-02 at 23 42 53" src="https://user-images.githubusercontent.com/167819/106677375-9269f880-65b0-11eb-826e-06ef63ca8d73.png">

I will file a PR once i've worked through all of the building animations.
