### ISSUE TITLE
Chronoshifted tanks not teleported back after timeout

### ISSUE THREAD

**Issue by duckdodger** [OpenRA/OpenRA#13059]
I was playing a 2v2 game with my friends and towards the end of the game (I had to stop it since this really screwed me over) my opponent chronoshifted a bunch of mammoth tanks into my base to destroy my missile silo. But after the chrono timeout, only some of the tanks got teleported back to his base while 4 remained _permanently_ in my base, continuing to destroy the rest of my buildings.

I'm not sure how this happened, but I noticed that the tanks which remained after the chrono timeout were ones that got hit by my artillery units although I could be wrong. I have provided a link to the replay file below so that you can examine it. It might be related to #8670 which has not been closed yet, but I felt a new report was needed since that is quite old and we're on a newer version of the game. 

[Link to replay file](https://www.dropbox.com/s/df7oqp8f85hrhvf/OpenRA-2017-04-03T162557Z.orarep?dl=0) 

The bug can be seen in the last few minutes of the game, and the chronoshift happens at the bottom left base (red Germany).

**Comment by jaZzKCS** [comment]
Did the original spot from which they were chrono-ed away got obstructed afterwards before they were recalled?

**Comment by atlimit8** [comment]
Should I reopen #9419?
It would need to be reworked for hit shapes plus bug fixes.

**Comment by duckdodger** [comment]
@jaZzKCS No, there was no obstruction in the initial spot.

**Comment by Basti504** [comment]
Just checked, the way I reproduced it in #8670 is still possible in the current release.

https://github.com/OpenRA/OpenRA/issues/8670#issuecomment-124958707 for example

**Comment by CH4Code** [comment]
I just had a case where the location to teleport back to was totally empty and still 3 of 4 units didnt go back.
http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=305997#305997
I have a suspicion this bug has to do with units beeing in between cells when the chrono expires, since I moved my units right before that. 
In a similar way I have "missed" a lot of Iron curtains already..
