### ISSUE TITLE
Bib of Spawned Actors via lua

### ISSUE THREAD

**Issue by CombinE88** [OpenRA/OpenRA#13060]
The Bib of lua spawned actors is not working correctly.
You can for example build on it.

**Comment by CombinE88** [comment]
![bib](https://cloud.githubusercontent.com/assets/20419820/24629037/e7b168d6-18b7-11e7-9643-7b5322311745.gif)

Made a map where a building gets replaced via lua with a random one

**Comment by GraionDilach** [comment]
The SpawnActorPower of OpenRA's ignore all placement rules.

**Comment by abcdefg30** [comment]
Looks like the bibs were using the wrong footprint type?
