### ISSUE TITLE
Spawnpoint mousover fails in lobby minimap

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#13077]
In lobby, sometimes when the focus is another place, the MapPreviewWidget fails to show spawnpoint on mouseover. This could make it hard to fix teams.
A way to fix this, is to bring focus on the minimap again, but that could deselect your spawnpoint.

**Comment by rob-v** [comment]
I couldn't reproduce it in playtest 20170304. In which map it happens?

**Comment by kyrreso** [comment]
Its not related to maps, its the focus of the mapwindow. Have not managed to reproduce it in playtest.

**Comment by kyrreso** [comment]
Still valid in new release, screenshot did not work in lobby, but was on map Vegetation

**Comment by rob-v** [comment]
Can you paste a screenshot?

**Comment by PunkPun** [comment]
I can't reproduce it on bleed
