### ISSUE TITLE
Pre-damaged bridge tiles visually transform to new when attacked

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#13076]
In RA if you create a map with the pre-damaged bridge tiles 236, 242, and 239 they'll visually transform back to full health when taking a small amount of damage.

Before attacking:
![openra-2017-04-07t134605702z](https://cloud.githubusercontent.com/assets/22008761/24802767/2301e2a0-1b77-11e7-9bbc-c1da277e1386.png)
After attacking (1 rifle shot):
![openra-2017-04-07t134625264z](https://cloud.githubusercontent.com/assets/22008761/24802768/26f34192-1b77-11e7-8502-846f40fa4911.png)

**Comment by rob-v** [comment]
PR #13089
