### ISSUE TITLE
Opening .orarep or .oramod files opens the latest OpenRA installation.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#13082]
(Windows 7) This is a minor inconvenience if you know this but likely a problem for those who don't. So the latest installment of OpenRA be it a release or playtest will be the go-to client for any replay or mod file opened directly from Windows. If you just installed the latest playtest for example, your files will open it and display a message 'Missing Dependencies' and ask you to fully install the correct client version.

For me it's a minor inconvenience but for newer users probably confusing since they likely already have the necessary client installed.

**Comment by reaperrr** [comment]
Support for .oramod files will be cut completely as part of our mod support refactor, and opening .orarep from outside the game will go away as well: #12909 

So the April release will be the last one to have this issue.
