### ISSUE TITLE
base game music only disables music player

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#13084]
When the v2 game music isn't installed, but the game assets through quick install, you get one music track, but no way to mute/stop/pause it as the audio player has greyed out buttons and tells you to please install the music instead of showing the current tracks.

**Comment by rob-v** [comment]
@Mailaender You mean only in main screen as when I start game there is no music track played in TD.

**Comment by Mailaender** [comment]
Sorry I forgot to mention that this happens only in the RA mod.

**Comment by rob-v** [comment]
It should be clear for me based on v2 game music I guess now. When I start from RA quick install - no music installed, still there is no music played in match. What I could do wrong?
In main screen, stop/pause is disabled, but volume control is available so I can change track volume.

**Comment by pchote** [comment]
Do you mean the default background track?  This sounds like the intended behaviour that was implemented back in #8876.

**Comment by Mailaender** [comment]
Yeah, it is probably intended. https://github.com/OpenRA/OpenRA/pull/8876/commits/c6e246102ea07c05748d8e017165d5bce58dcddd
