### ISSUE TITLE
Add a setting to disable DPI scaling

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#13099]
See https://github.com/OpenRA/OpenRA/pull/12501#issuecomment-292999888, #13097 and [playtest-20170408/#comment-3250354354](http://www.openra.net/news/playtest-20170408/#comment-3250354354).

**Comment by pchote** [comment]
As mentioned in IRC, I consider a hidden `Graphics.DisableWindowsDPIScaling` setting (that must be manually added to settings.yaml) to be sufficient.  If we added it to the ingame settings menu then we would need to deal with the different behaviour on windows/osx/linux which would turn a simple patch into a monster.
