### ISSUE TITLE
OpenRA fails to launch on Gentoo Linux: libopenal.so.1 can't be found

### ISSUE THREAD

**Issue by fusion809** [OpenRA/OpenRA#13100]
Hi,

On Gentoo Linux both OpenRA playtest 20170304 and 20170408 I get this error:

```bash
Platform is Linux 
Using SDL 2 with OpenGL renderer 
Desktop resolution: 1600x900 
No custom resolution provided, using desktop resolution 
Using resolution: 1600x900 
Using window scale 1.00 
OpenGL version: 3.0 Mesa 17.0.3 
Using default sound device 
Renderer initialization failed. Check graphics.log for details. 
Using SDL 2 with OpenGL renderer 
Desktop resolution: 1600x900 
No custom resolution provided, using desktop resolution 
Using resolution: 1600x900 
Using window scale 1.00 
OpenGL version: 3.0 Mesa 17.0.3 
Using default sound device 
Renderer initialization failed. Check graphics.log for details. 
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details. 
 at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x00116] in <96f18ea93b7243efbb9796e0b8fa3e27>:0  
 at OpenRA.Program.Run (System.String[] args) [0x00006] in <96f18ea93b7243efbb9796e0b8fa3e27>:0  
 at OpenRA.Program.Main (System.String[] args) [0x00048] in <96f18ea93b7243efbb9796e0b8fa3e27>:0  


(zenity:1983): Gtk-WARNING **: Theme parsing error: gtk.css:1036:92: Missing closing bracket at end of linear gradient 

(zenity:1983): Gtk-WARNING **: Theme parsing error: gtk.css:1036:94: Expected semicolon 

(zenity:1983): Gtk-WARNING **: Theme parsing error: gtk.css:1036:124: Expected semicolon 

(zenity:1983): Gtk-WARNING **: Theme parsing error: gtk.css:1147:50: Expected semicolon 

(zenity:1983): Gtk-WARNING **: Theme parsing error: gtk.css:3129:50: Expected semicolon 
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged
```

while [here](http://paste2.org/BPK8XkgZ) are the contents of `~/.openra/graphics.log`. [Here](http://paste2.org/xCLycC1U) are the contents of `exception-2017-04-11T105334Z.log`. Not sure why I'm getting this error. My Mono version is 4.8.0, is there some problem with building OpenRA against this version of Mono?

Thanks for your time,
Brenton

**Comment by fusion809** [comment]
If it helps [here](http://paste2.org/K9yWGW53) is the log I get from:

```bash
LD_DEBUG=libs openra > ~/openra-debug.log 2>&1
```

**Comment by fusion809** [comment]
Never mind folks, I found out what the problem was. I asked for help on the Gentoo forums (specifically [here](https://forums.gentoo.org/viewtopic-p-8054930.html#8054930)) and that lead me to reinstalling media-libs/openal (which is meant to provide libopenal.so.1) and it turned out that for some reason even though media-libs/openal had already been installed some files meant to be installed from that package was missing from my filesystem.

**Comment by Mailaender** [comment]
Have you installed https://packages.gentoo.org/packages/media-libs/openal?

**Comment by fusion809** [comment]
@Mailaender Rofl, thanks. Ya were right it was just that openal hadn't been installed properly. I re-merged it and the problem is now fixed.
