### ISSUE TITLE
AttackGarrisoned trait 

### ISSUE THREAD

**Issue by MartinCurwen** [OpenRA/OpenRA#13107]
I'm having a problem with this trait, it seems to drop all attacks if it encounters a weapon that can't attack the target despite others being capable.

To reproduce this issue:
using the RA mod set the yaml PBOX cargo size & weight to 5.
set the initial unit from e1 to e3.
set the AttackGarrisoned, Armaments: to "primary,secondary".

now in game place a pill box and build a land unit and air unit, notice how you can force fire on the air unit and it works fine, but it will not attack the land unit at all. if you add other units inside they will also not attack unless they can hit the aircraft, also works in reverse with the rocket soldier going in last being unable to attack aircraft.

This issue stops garrisons from having more than a single weapon and having single unit cargo. I'm not sure if it was set up in RA to get around this bug, but I think it will be a good idea to fix for other mods.

having downloading the source and messing around with AttackGarrisoned.cs I noticed that commenting out line 159 and 160
158				var barrel = a.CheckFire(a.Actor, facing.Value, target);
159				//if (barrel == null)
160				//	return;
this makes it work as intended and without error so hopefully someone can work out why the return cancels the other armaments as I need this for a mod, thank you.

**Comment by pchote** [comment]
That `return` needs be a `continue`.  Right now it exits the method, when it should be skipping to the next armament.

**Comment by Phrohdoh** [comment]
This is a great first-time contributor ticket!

**Comment by MartinCurwen** [comment]
Decided to give a pull request a go 👍

**Comment by pchote** [comment]
Fixed in #13110.
