### ISSUE TITLE
Scroll-Lock while using viewport bookmaks

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#13111]
Found this bug while reviewing #13096 .

If you simultaneousely scroll with keyboard input (i.e. "UP") and recall a viewport bookmark (i.e. "ALT+Q") the view wont stop scrolling up after releasing "UP", locking the view scrolling upwards. Edge scrolling or scrolling with mouse buttons held down while recalling a bookmark doesnt trigger this bug.
recreate:
1. bookmark a view ("ctrl"+"q")
2. press "UP" or "DOWN" or ...
3. also press "ALT+Q"
-> your viewport is now scroll-locked

I could not find an obvious reason in the code.
Should not be too dramatic of a bug because of rare occurrence, but I wanted to post it anyway.

**Comment by rob-v** [comment]
Fixed by PR #13115 
This happens for some combinations/orders of pressed/released control keys (ctrl/shift/alt) and scroll keys.
Thanks for reviewing/testing #13096
