### ISSUE TITLE
Tiling errors on maps "Countercross","Siberian Pass","Six below zero"

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#13112]
**Countercross**
Bad tile locations:
47,25 - tile
142,125 - tile
172,79 - tile
187,16 - road
177,12 - inaccessible ore
35,141 - misplaced ore
34,143 - misplaced ore
Link to revision:
http://resource.openra.net/maps/20541/

**Siberian Pass**
Bad tile locations:
9,33 - road
10,30 - road
17,33 - road
19,33 - road
5,51 - road
3,53 - road
72,57 - road
50,41 - misplaced ore
Link to revision:
http://resource.openra.net/maps/20542/

**Six Below Zero**
Bad tile locations:
24,42 - road
43,17 - road
30,48 - road
36,49 - road
76,65 - road
77,107 - road
86,112 - road
74,88 - road
44,110 - road
109,81 - road
109,56 - road
109,18 - debris
106,19 - road
87,28 - road
Link to revision:
http://resource.openra.net/maps/20543/

**Comment by pchote** [comment]
See also #13098.

**Comment by SoScared** [comment]
An oversight on my part with the last few map PRs.

Revisions looks great.

**Comment by FrameLimiter** [comment]
I missed a few more on Six Below Zero, all quite minor but regardless I uploaded another revision:
http://resource.openra.net/maps/20570/

45,94
70,53
2,56
Also did some road polish on sharp edges. e.g. (84,110), (96,110) ect.

**Comment by SoScared** [comment]
@FrameLimiter: added to the #13123 commit.

Good find, that map is incredibly detailed.
