### ISSUE TITLE
ProvidesRandomPrerequisite (i.e. YR Tech Secret Lab)

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#13114]
Actually what was in my mind was a Random Condition Granter, rather than Prerequisite Provider, but it looks like `ProvidesPrerequisite:` is not conditional. Making `ProvidesPrerequisite:` conditional and adding a `GrantsRandomCondition:` might be a better approach.

What i need such trait for is in my D2K mod, i'm planning to give Ixian IX Lab ability to give one of other sides IX Lab tier unit randomly.

Here is a example .yaml code of how it may look like.

    ix_reseach_center:
      ProvidesRandomPrerequisite@Ixian:
        RandomiseForEach: false # if true, different ix_reseach_center: actors can provide different prerequisites, if false all provide same thing during the same game
        Factions: ixians # can also be set under each prerequisite
        ResetOnOwnerChange: false
        Prerequisite@1:
          Prerequisites: ix.sonic
          Chance: 8
        Prerequisite@2:
          Prerequisites: ix.deviator
          Chance: 10
        Prerequisite@3:
          Prerequisites: ix.devastator
          Chance: 7
    ...........................

Apart from my mod plan, we need that for RA2 mod as i said on Title anyway. Not sure if that would belong to commons or RA2 mod dll tho.

**Comment by GraionDilach** [comment]
You mean YR. It has been stated that the RA2 project aims strictly for vanilia RA2 and Secret Labs were added in YR.

**Comment by pchote** [comment]
> Making `ProvidesPrerequisite:` conditional and adding a `GrantsRandomCondition:` might be a better approach.

This has been done, so closing.
