### ISSUE TITLE
Missing high resolution and source artwork for D2K mod logo

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#13121]
We have two problems with the D2K logo:
* The sources for the current version were not added to the [artwork source repository](https://github.com/OpenRA/ArtSrc/tree/master/d2k).  The moons are noticeably different.
* The logo was created in 2D, and is too small to use for native system icons for the new mod launchers.  OSX requires sizes rendered up to 1024px for best results, and even windows wants at least a 256px version.  The largest version we have is ~110px.

The most efficient approach will be to recreate the logo in 3D so that we can render out the resolutions we need.

**Comment by pchote** [comment]
Warman has rendered out a nice new logo at all the sizes we need.

![d2kl_2_512](https://cloud.githubusercontent.com/assets/167819/25102456/74d448fc-23b0-11e7-84a0-3ce1d6778642.png)

I'll wait for #13129, #13133 and #13138 to be merged before filing a PR so that we can replace all uses of the logo at the same time.

**Comment by Micr0Bit** [comment]
not sure if thats the latest version ... but the big moon in the back looks kinda odd ... i mean the lightning ... (or shouldnt he be darker?... idk)
