### ISSUE TITLE
Crash while using the minimap

### ISSUE THREAD

**Issue by Elizadmin** [OpenRA/OpenRA#13128]
release-20161019, 100% AI and local game.
I was using the minimap (keeping LMB pressed and moving around on the minimap) and got a crash.
(Not sure if it's the cause but the game crashed while I was doing that)
I have only debug.log, irc.log and perf.log.
debug.log is uploaded here : https://ufile.io/cc0711.
Replay is uploaded here : https://uploadfiles.io/625d6.
The map is Buttisland : http://resource.openra.net/maps/12213/.

**Comment by rob-v** [comment]
@Elizadmin In the same directory, could you find a exception-2017-02-07T131106Z.log file with that error?

**Comment by Elizadmin** [comment]
The only exception-X.log I have is exception-2017-03-27T164219Z.log.
It is two weeks older than this crash.

**Comment by Elizadmin** [comment]
Anyway I'm unable to reproduce this. I tried keys combinations, Alt-Tabs and so on.

**Comment by Elizadmin** [comment]
I can't find any clue (not even the exception.log) and the replay seems to be corrupted.
Like a crash from something on my computer and not from OpenRA ?
Feel free to close this issue !

**Comment by rob-v** [comment]
There will be soon new release version and you can't reproduce it so I propose that you close it (I can't). If it happens again, send us also the exception...log file if possible.

**Comment by Elizadmin** [comment]
Fine ! 👌
