### ISSUE TITLE
Guard command.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#13136]
The guard command (Hitting G and selecting it on a unit) Works rather well but is it possible to add a limit on this?

IE: Unit on guard follows MCV and then engages the enemy. MCV then runs away but the units don't follow the MCV and instead stay back to fight.

This would make vehicles that are on guard (Mainly the turreted ones) more dangerous. Infantry would pose some issues possibly in which case manual use can be done. The Guard command also works on aircraft.

It also has the issue of when a unit kills a unit/structure the unit is no longer on Guard follow and instead jus stands in the place it was attacking at last.

**Comment by abcdefg30** [comment]
See #11439 for the last part.
