### ISSUE TITLE
Original C&C Enginners don't capture full health buildings 

### ISSUE THREAD

**Issue by MarkOBrienAU** [OpenRA/OpenRA#13131]
The Engineer's are acting like engineers from later games, you need either multiple engineers or to pre-damage buildings prior to capture.

**Comment by MustaphaTR** [comment]
WAI. https://github.com/OpenRA/OpenRA/wiki/FAQ#this-is-not-true-to-the-original

**Comment by MarkOBrienAU** [comment]
Is there an prebuilt option to undo the balance changes ?

 

If not, how difficult would it be to have an option that toggles between modified and original gameplay. Is it just building a mod that undoes the changes or something else.

**Comment by MustaphaTR** [comment]
A classic mode has requested and some tried to make in the past (iirc never released). But the idea got ditched out as it is nearly impossible to do, becuase how some game logics act different than original games.

Making engineers able to capture full health structures is i think just a 1-line .yaml change. But that's not the only thing OpenRA mods different that originals. RA and TD mod are highly rebalanced with the time. For D2K mod and future TS mod, our plan for now is to stick with original gameplay, but of course those will get balance changes after they are properly completed.

OpenRA mods are not clones of original games. Having a better balance is one of the aims of it.

**Comment by AoAGeneral** [comment]
If you wouldn't mind can you post this in the TD Balance Thread on the forums? http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=17430

Im reworking on the engineers in TD (All be it will be after next release) but im looking to change it to more of the CNC3 approach and ditch the multi engineer capture.

**Comment by Datastreamx** [comment]
At line 610 in defaults.yaml at OpenRA\mods\cnc\rules you can add CaptureThreshold: 100 to have it like it's supposed to be. Just remove it if you want to play online. 

Considering it's yaml you might be able to override things in campaign-maprules.yaml but I can't be arsed and won't play it online anyway.

**Comment by MunWolf** [comment]
@ccsv Its easy having it in a multiplayer game, you just have to have a server with that yaml change or have a map that overrides the yaml.

**Comment by abcdefg30** [comment]
This has been changed since.
