### ISSUE TITLE
Separate spectators lag from players ? 

### ISSUE THREAD

**Issue by leodew** [OpenRA/OpenRA#13145]
The idea : let the players continue fluidly and ignore the spectator lag.

If the specs missed some moments of the game, their view could just skip to the current moment (similarly to watching a live video on YT, Twitch, FB, ... with a bad connection )

Or they could just be kicked out if their ping is bad, without holding or freezing the game. 

Is it possible, the way the game is coded ?

**Comment by leodew** [comment]
Maybe related to this : #6131 #13062 ?

**Comment by obrakmann** [comment]
Spectators don't cause lag any more than any "regular" player does, so this is kind of pointless. It's also not really possible with the way things work in openra.
