### ISSUE TITLE
Unknown settings should be stored and resaved

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#13142]
Our settings parser ignores any yaml entries that do not map to defined options, and so these are lost when the settings are reserialized.  This is a major problem for forward and backward compatibility now that we are aiming to support parallel installs.

**Comment by rob-v** [comment]
We could keep these unknown fields and save them with known fields to preserve them, however when 1 instance knows and changes this field it could be overwritten by 2nd instance with original value. This issue can happen also now with known fields with 2 instances. For different mods it can be solved by settings per mod. Shouldn't we have also settings per parallel install?
Or we don't need to keep these unknown fields after loading them, but rather before saving, load all unknown settings and save new settings file with known fields + unknown fields to prevent overwriting them.

**Comment by atlimit8** [comment]
Yes, if you have per mod settings, then they should also be per version. If that is done then another solution would be for mods to look for their latest installed version, copy the settings, and then run an upgrade utility on them. The downside to that is that setting changes won't be carried over to parallel installs or downgrades.

**Comment by pchote** [comment]
IMO the best solution might be be to have per-mod settings for everything except player name and graphics configuration, but then share settings (remembering unknown settings, as per this ticket) across different versions of the same mod.

I don't consider it worthwhile to support the use case of having two different versions of the same mod running at the same time.

**Comment by atlimit8** [comment]
Alright, the only major use-case for parallel installs is testing and backing up should be easy enough for a modder.

**Comment by rob-v** [comment]
You want to prevent losing settings from mod's newer version by running mod's older version, right? (another mod has separate settings so no problem). I assume it is then sufficient to keep these unknown fields after loading them and resave them with know settings lately. Can I work on this?

**Comment by pchote** [comment]
Sorry @rob-v, I missed your comment asking to take this on.  I have opened #13226 to fix this.

**Comment by rob-v** [comment]
@pchote Ok, better that you did it.
