### ISSUE TITLE
Mouse button implementation?

### ISSUE THREAD

**Issue by wanderrful** [OpenRA/OpenRA#13158]
Hi there I thought it'd be faster to get the developers' attention by posting here rather than on the OpenRA subreddit.  Feel free to close this after one of you guys can get back to me.

I've been working on making my own RTS personal project using the Unreal Engine and even though I've successfully found a way to implement the LMB and RMB game functionality...  I thought it'd be a lot better to see how people who are much better than me imeplement those game mechanics.

I tried looking through your repository but I'm not experienced enough with browsing other peoples' code to be able to identify where that specific logic is located.  Can you maybe give me a function name or something to search for or otherwise link me to where the implementation exists in the OpenRA game logic?

**Comment by obrakmann** [comment]
You probably mean [this](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Widgets/WorldInteractionControllerWidget.cs#L72), but I'd advise you strongly against even looking at it. Our input handling is god-awful, and should not be taken as any sort of best practice.

I don't know what the state of the other open-source RTSs input handling is, but you might have better luck looking at theirs.
