### ISSUE TITLE
Submarines play their Uncloak sound at the start of a map

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#13169]

**Comment by pchote** [comment]
The [GrantCondition](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Conditions/GrantCondition.cs) trait shows to to implement conditional condition granters for the `CloakedCondition`.

For the sound specifically we will want to set `wasCloaked = true` during `TraitEnabled` if (and only if) `TraitEnabled` is called before the first `ITick.Tick`.

**Comment by forcecore** [comment]
Happens in RA1 too, I think

**Comment by pchote** [comment]
This regression was discussed on @SoScared's stream tonight, in the context that subs now globally announce themselves when built (like tanya).  We should aim to squash this in the bugfix release.
