### ISSUE TITLE
Icons for Friendlies in Tunnels & Detected Underground Enemies.

### ISSUE THREAD

**Issue by atlimit8** [OpenRA/OpenRA#13163]
This ticket is for the expanded use of the icons (such as the RA GPS icons) rendered where actors should not be rendered themselves:
 * Friendly actors in tunnels (TS)
 * Enemy actors underground but detected (TS)
 * Possibly other use cases by external mods?

This would require a rendering trait using a condition expression and a render player stance check.

Basically @pchote's comment [here in "General tunnel issues"](https://github.com/OpenRA/OpenRA/issues/12662#issuecomment-276376126).

**Comment by pchote** [comment]
#12912

**Comment by aydjay** [comment]
Hello,

I'm new to this project and I'm going to attempt to fix this issue.

Thanks,

Aydajy

**Comment by pchote** [comment]
A word of caution: This feature interacts with several subtle and tricky parts of the game logic, and is going to be fiddly even for those of us very familiar with the code.  It might be a bit much for somebody new to the codebase to take on!

**Comment by aydjay** [comment]
I'll not feel too discouraged if I don't manage to fix it then :)

**Comment by dragunoff** [comment]
Related: #15880

**Comment by PunkPun** [comment]
Friendlies in tunnels are now shown #18000 and detection is covered by #12912
