### ISSUE TITLE
Scripted aircraft are broken (at least in Intervention)

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#13167]
They don't leave the map but just go to some random place on the map and start circling.

**Comment by obrakmann** [comment]
This is caused by `FlyAttack` inserting  a `ReturnToBase` activity when the ammo pool runs dry.  `ReturnToBase` doesn't find a base and cancels the queue, causing `ReturnOnIdle` to kick in, leading to random circling.

**Comment by pchote** [comment]
Can we work around this in lua for now?

**Comment by abcdefg30** [comment]
Not sure, as we reverted #13021.

**Comment by pchote** [comment]
The description mentions them leaving the map, so i'm assuming their entire life cycle is scripted.  Why can't we just change the ammo count so they don't try to reload automatically, and then script whatever we want here?

**Comment by abcdefg30** [comment]
Ah yeah, some maps have those fly off the map. I guess we can try that on them.

**Comment by abcdefg30** [comment]
Seems like this is fixed on latest bleed.
