### ISSUE TITLE
Mac OS hot corners and dock enabled in game

### ISSUE THREAD

**Issue by Trychlik** [OpenRA/OpenRA#13179]
in last 20170421 is a bug, that hot corners and hinding dock is enabled in fullscreen mode, so moving on the map with mouse is complicated and its better to disable it before starting openra
hot corners settings  is in settings/mision control/hot corners and it should be functional only in system, not in fullscreen apps

**Comment by gdavegdave** [comment]
@Trychlik, does it persist when changing to desktop and back again to OpenRA? Also, are they active every time you start OpenRA? I do rarely see the dock enabled, but switching (using the four-finger swipe gesture on my Macbook Pro) to Desktop and back again to OpenRA seems to disable it.

**Comment by Trychlik** [comment]
i cant reproduce dock again :/, but hot corners is fuctional everytime. swipe to desktop and back doesnt change anything. interesting is, that only some  function in hot corners do this. i tested it all and bad are: mission control, notification center, launchpad and dashboard, only desktop and application windows are ok and do nothing.

**Comment by pchote** [comment]
This is a general macOS "feature" that affects all games and other applications that use the "fullscreen desktop" API to integrate nicely with mission control/spaces, alt/tab switching etc.

You can switch to "Fullscreen (Legacy)" in the settings to work around this, but beware that this will also disable swiping between desktops and alt-tab.  It also does not work properly on the current release with Retina displays (#13216), but we'll fix that for the next release.  Apple doesn't provide an API to disable hot corners without also disabling these other features, so there's not really anything more we can do here, sorry.
