### ISSUE TITLE
Choice of helipad for reloading 

### ISSUE THREAD

**Issue by leodew** [OpenRA/OpenRA#13173]
Hinds and Longbows seem to reload at the previous helipad they were. Not the closest one. 
On the opposite, Yaks and Migs seem to choose the closest one. 

Is there any reason for this different behaviour ?

**Comment by rob-v** [comment]
I don't know how it should be, but if I read it correctly:

planes - return to **nearest** not reserved base if exists, otherwise to nearest
helis - return to **any** not reserved base if exists, otherwise to nearest

**Comment by theKalash** [comment]
Helis will actually fill up helipads chronological (always go to the oldest one available)

This is quite annoying if you establish forward helipads. You'll have to sell older helipads to actually make use of them.

Should be the nearest, like with planes and airfields.

**Comment by rob-v** [comment]
@theKalash  your're right. "any" in my description above means "first/oldest". I provided fix which will be reviewed.
