### ISSUE TITLE
Multiple Chinooks land on top of eachother

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13177]
Happens in RA mod and probably in CNC mod too. Happens in current stable version. (20170421)
Produce multiple chinook transports and order them move order. When the ground is clear for landing, some of them will land on top of another.

**Comment by forcecore** [comment]
Maybe related to #4605 ?

**Comment by GraionDilach** [comment]
It's actually a duplicate.

**Comment by abcdefg30** [comment]
Closing as duplicate.
