### ISSUE TITLE
Weird Compression and Missing Visuals Post-Update

### ISSUE THREAD

**Issue by RadicalEdward2** [OpenRA/OpenRA#13170]
I just installed the update and noticed everything became noticeably "scrunched" (for a lack of a better word). On top of that, the windowed resolution seems smaller than it was before as well.
I read that the crispier resolution was a bit of a highlight of the update but, I think I somehow received the opposite of what was intended.

Here's some a before and after screenshot...

Before the update:
![field tunnels](https://cloud.githubusercontent.com/assets/25542788/25296247/539714fa-26b5-11e7-8c1c-d78fd33a4a16.png)
![field gdi base](https://cloud.githubusercontent.com/assets/25542788/25296377/fd8ae59a-26b5-11e7-98a0-b6453269e914.png)

After the update:
![post update](https://cloud.githubusercontent.com/assets/25542788/25296257/5faee128-26b5-11e7-80d5-bb8860fc8bfc.png)
![post update 2](https://cloud.githubusercontent.com/assets/25542788/25296322/b1293e4a-26b5-11e7-8d9e-a40bedb5eff7.png)

In the last screenshot, you can see the diagonal lines on the placement tiles are distorted unless you double pixel (in-game).

Here's a shot of the RA background as well:
![post update 5](https://cloud.githubusercontent.com/assets/25542788/25296679/933173b0-26b7-11e7-9f4d-90971096516f.png)
I know it's not the same as a recording but, when it's panning, everything looks like it's vibrating because of how compressed everything looks. This also carries over to fullscreen as well.

Here's a shot of the UI. It looks "unaligned" and stretched:
![post update 6](https://cloud.githubusercontent.com/assets/25542788/25296821/399a63ec-26b8-11e7-9508-a8cc7f4b8eba.png)

**Comment by pchote** [comment]
You must be running windows with a non-integer scaling factor.  You can add `DisableWindowsDPIScaling: true` under the Graphics section in your settings.yaml to restore the old behaviour.

This issue demonstrates why it is so important for people to try the playtests, and the consequences when they do not.  The HiDPI enabled builds with this problem have been available since december, and we only recieved a couple of reports of these problems which we believe to be very rare/isolated. If we had known how how widespread they were we would have addressed the problem properly instead of requiring players to manually edit their settings.yaml.

**Comment by RadicalEdward2** [comment]
While I totally understand the importance of testing and quality control, I wasn't exactly around during the playtest period (I was out of country due to a family emergency). 
I will definitely try to be around for the next playtest though.

**Comment by pchote** [comment]
I apologise if that came across as being a complaint at you directly, I intended it as a general observation (we are now seeing quite a few reports of this issue) for everyone who reads this ticket.

**Comment by RadicalEdward2** [comment]
It's totally fine. I was actually looking forward to playtesting but, sadly fate had other plans for me.
Where I went didn't exactly have suitable internet to download the playtest anyway (Philippines aka 3rd world bandwidth of a whopping 5 - 10 MB )

**Comment by Fauntleroy** [comment]
Just had the same issue on my computer. Windows 10 does some real interesting stuff with resolution scaling, multiple monitors, and display switching. Ultimately I had to make sure I only had one monitor on, and then restart Windows.

Windowed resolutions worked properly.
