### ISSUE TITLE
Main screen is very choppy and laggy. Also game play. 

### ISSUE THREAD

**Issue by chazechad** [OpenRA/OpenRA#13188]
The main screen is very laggy since the update. 
My computer can run all modern games so that shouldn't be a issue. 
Somebody mentioned the bitmap having done this.
I've also noticed when there's a lot of units in the game i start to have odd lag. 
Its choppy lag just like the main screen. These problems just started after the update. 
I have tried and reinstalled the game.

**Comment by reaperrr** [comment]
With 'update', do you mean the new release of OpenRA compared to an older release?
If yes, what was the last release that performed well for you?

**Comment by chazechad** [comment]
The last 2016 release that was out. The current 2017 one makes me lag. The old one was fine.

**Comment by reaperrr** [comment]
I assume your OS is some Windows?

If yes, could you start the game, wait on the main menu until you have had those lags for several seconds, then close the game, look for `C:\Users\*your username*\Documents\OpenRA\Logs\perf.log` and upload that file somewhere?

That might show us what exactly is slowing the game down on your system.

Another thing you could do is to go to Settings - Advanced and set the hook at "Show Perf Graph" and make a screenshot when you get lag (you can use the Print button on your keyboard and then paste it directly on imgur, for example).

**Comment by rob-v** [comment]
@chazechad  See also http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=20080

**Comment by pchote** [comment]
@chazechad: Can you please upload your performance log so that we can debug this?

**Comment by chazechad** [comment]
Sorry guys ive been busy and i forgot about this post, ill do that right now.

**Comment by chazechad** [comment]
https://www.4shared.com/get/31itAfSoei/perf.html

You can download it from here.

**Comment by chazechad** [comment]
Also important! I went and was playing Crystallized Doom. Well i was spectating a game and the game was lagging for everybody. After i left they said that it fixed. So i don't know if this is latency related. This really only happened when there was a bunch of units on screen. My pc is powerful enough for all modern games. So this seems to be some form of bug.

**Comment by chazechad** [comment]
https://www.4shared.com/photo/JV3StEYCca/pers.html

Here's the picture as well.

**Comment by chazechad** [comment]
I have also gotten the recent hotfix. That did not change anything for me. :)

**Comment by chazechad** [comment]
@pchote  any ideas?

**Comment by pchote** [comment]
The tick time from your screen shot is indeed atrocious.
Your hosting site won't let me download your perf log without registering an account.  Can you please rehost it on https://pastebin.com/ or another service?

**Comment by reaperrr** [comment]
Gist here on github would work, too:
https://gist.github.com/

**Comment by chazechad** [comment]
https://pastebin.com/8Lh4xqXE

**Comment by chazechad** [comment]
https://gist.github.com/chazechad/ee9173195df4d8a9780ddaf0b32b1c91

**Comment by chazechad** [comment]
@pchote  is this just a problem for me? Or is it a common thing? Running windows 10 on 64 bit. I cant really play team battles because of lag etc.

**Comment by GraionDilach** [comment]
What is your CPU?

**Comment by chazechad** [comment]
intel g4560

**Comment by reaperrr** [comment]
The perf.log you uploaded isn't showing anything unusual, my own Win10x64 notebook is a bit slower, and yet OpenRA doesn't lag nearly as much as it did on your screenshot.

Do you get that very bad performance from your screenshot all the time right from the start, or only after some time has passed?

**Comment by pchote** [comment]
> The perf.log you uploaded isn't showing anything unusual

That was my first thought too.  It doesn't match at all with the numbers I was expecting based on the perf graph in the screenshot.

**Comment by chazechad** [comment]
The bad performance is heavy in the main screen. Its constant stuttering when i open the multiplayer or skirmish menus. Then when i play multiplayer the game plays fine until a few hundred units are on screen. 3v3's lag pretty bad. Sometimes 2v2's depending on unit count.

**Comment by pchote** [comment]
This is a long shot, but are you running aggressive anti-virus software like Norton?  If yes, try temporarily disabling it or whitelisting OpenRA and see if this changes anything.

**Comment by chazechad** [comment]
I have recently just got Malwarebytes free. Let me uninstall it.

**Comment by chazechad** [comment]
@pchote  you're gonna love this. It was actually windows defender the whole time. I had to go through CMD and uninstall it. Games running fine now.  A lot of people are complaining about the ora map lagging as well. I removed that too.
