### ISSUE TITLE
Technicians looking all the same

### ISSUE THREAD

**Issue by airetaM** [OpenRA/OpenRA#13187]
I dont know if this is wanted but is looking a bit curious now.
This is a result of https://github.com/OpenRA/OpenRA/pull/12174

**Comment by GraionDilach** [comment]
Technicians never had multiple artwork, they aren't civilians.

**Comment by airetaM** [comment]
"Technicians never had multiple artwork, they aren't civilians."
I know in original game it was that way but https://github.com/OpenRA/OpenRA/wiki/FAQ#this-is-not-true-to-the-original
In my opinion this is a visual step backwards.

**Comment by Smittytron** [comment]
IIRC there was grey shirt and yellow shirt technicians. Yellow shirt guy isn't in OpenRA.

**Comment by forcecore** [comment]
I remember yellow guy too! I think it can be handled easily using current system. Current paratroopers are E1R, E3R that are E1 and E3 variants. The question is, people agree to put him in or not.

**Comment by airetaM** [comment]
They already was in before but now they are removed.
-ActorTypes: e1,e1,e1,e1,e1,e1,e1,e1,e1,e1,e1,e1,e1,e1,e1,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,e6,e6,e6,e6,e6
+ActorTypes: e1,e1,e1,tecn,tecn

This is only a small detail but i'm asking myself just why?
If someone is selling his whole base it's looking really odd.

**Comment by Smittytron** [comment]
![yellow guy](https://cloud.githubusercontent.com/assets/23546299/25362723/541aaa28-291b-11e7-8fe2-5a426a734bb5.png)

**Comment by airetaM** [comment]
You are right @Smittytron the yellow shirt guy is not in game,
these civs are in.
![civs](https://cloud.githubusercontent.com/assets/14834585/25376069/389016ca-29a3-11e7-9d87-841f1fb1dab4.jpg)
@Micr0Bit is it intentionally that it is looking like this now?
![civs2](https://cloud.githubusercontent.com/assets/14834585/25376810/be236c7c-29a5-11e7-802f-b662f7d67631.png)
I just want to know this.

**Comment by Micr0Bit** [comment]
we have only 3 different civilian-sprites ... and the 3rd one (black hair , grey clothes) is custom colored by me ... (so not even in the original)

from what i've been told ... is that those 2 civilians are the only "shp's" that exist for civs (in red alert) ... and the color-variation is done via code in the original ... you probably wont find anyone fancy to programm that ...so my suggestion is to recreate him via shp ... (take a screenshot in the original ... edit one of our civilians and change the colors)

this is a great way to get into shp's ... couple of years i had some "plans" , but never finished it ... 

![civs](https://cloud.githubusercontent.com/assets/9139965/25406666/cd8e8388-2a07-11e7-96c8-0f586b49b0f0.png)

**Comment by MustaphaTR** [comment]
I have made artwork for original civilians for RA Classic mod, do we want them on normal RA mod too? If so what we should do with custom c3 we have right now?

**Comment by Smittytron** [comment]
> I have made artwork for original civilians for RA Classic mod, do we want them on normal RA mod too?
👍 To getting yellow shirt guy into the game.
