### ISSUE TITLE
Using SHIFT+key to build units stopped working.

### ISSUE THREAD

**Issue by MeSaber** [OpenRA/OpenRA#13199]
Had my hotkeys set in a grid like 1 2 3 q w e etc with SHIFT to build units that worked in some previous version. Stopped working now. CTRL+key to build units do work though.

**Comment by rob-v** [comment]
The reason Shift + Key doesn't work to build a unit is that it is used to build units by 5. I don't think this will be changed, but Shift + key could be prevented in Settings to avoid this issue.
Left click or by default F1 - build 1 unit
Shift + Left click or Shift + F1 - build 5 units

**Comment by MeSaber** [comment]
But my hotkeys worked in previous versions. It didnt add 5 units then. And the 5 units per shift click has exited for quite some time no?

**Comment by rob-v** [comment]
I didn't check when this changed. I tested it in last 2 releases (apr 2017, oct 2016,. so it had to be some older release if it worked.

**Comment by MeSaber** [comment]
I just installed 20160508 release and SHIFT+Q worked. While also SHIFT+mouseclick worked for queue 5 units of the same unit type (powerplant).

Version 20161019 didnt work though with SHIFT+Q. Seems logical as ive been gone for like a year so havent played that release and havent had time to tell you guys about it being changed :p

**Comment by pchote** [comment]
The original behaviour (shift modifier working for mouse, but not hotkeys) was a bug that is now long fixed.  I'm sorry that this fix broke your workflow, but this was an intentional change and not a regression.
