### ISSUE TITLE
Out of Date Documentation - make install-all

### ISSUE THREAD

**Issue by Enverex** [OpenRA/OpenRA#13192]
The documentation (https://github.com/OpenRA/OpenRA/blob/bleed/INSTALL.md#linux) states to run make install-all to install, but that doesn't appear to be correct any more as it results in "make: *** No rule to make target 'install-all'.  Stop.".

The Makefile itself seems to imply the correct form is now just "make install" so it's a simple fix.

**Comment by Enverex** [comment]
Added pull to fix here https://github.com/OpenRA/OpenRA/pull/13191

**Comment by pchote** [comment]
Fixed by #13191.
