### ISSUE TITLE
Make Airstrikes a "toggle-able" Option

### ISSUE THREAD

**Issue by RadicalEdward2** [OpenRA/OpenRA#13207]
In OpenCNC, there's four tech levels:
- Low : Everything except stuff unlocked by having a Comm.Center
- Medium : Everything except the top tier buildings (Adv.Comm.Center/Temple)
- No Powers : Everything except airstrikes and nukes
- Unrestricted : Everything

I feel like the airstrikes should be something that could be turned on/off in the menu before starting a match instead of something exclusive to Unrestricted. Most of the game, you get access to Airstrikes before you even learn about superweapons. Airstrikes shouldn't be pooled together with the "end game" weapons since they're not even classified as "super". You get access to airstrikes in the third mission of the GDI campaign which is pretty much a tutorial mission since you're still learning how everything works.

I know in cnc.net they had an option to turn on/off airstrikes from the menu before matches in case players wanted to have matches with them but, without superweapons.
Players should be able to utilize them at any tech level that grants access to the Comm. Center rather than being limited to a "nothing or everything" based tech system.

Seeing as the RA side has "No Superweapons" as a tech level but allows bombing runs, making airstrikes toggle-able in CNC wouldn't hurt.

**Comment by RoyiAvital** [comment]
I can see the option "No Powers". Is it as described above?

**Comment by penev92** [comment]
Sorry, this seems to be pretty niche and there doesn't seem to be much support for it. Hopefully one day it could be implemented as a user-defined rule preset (like custom map rules, but applicable to any map from the lobby). Until then I don't see this happening.
