### ISSUE TITLE
Be able to set NoKey('unknown') to a hotkey.

### ISSUE THREAD

**Issue by MeSaber** [OpenRA/OpenRA#13200]
First off i noticed that when i remove all hotkeys in settings.yaml it gets rewritten with default values that doesnt even get written out in the file (if you change a hotkey in the game it gets added into settings.yaml)

Its a small concern but my biggest one is not being able to 'delete' a key ingame so its value becomes 'unknown' that some hotkeys have by default. Instead i have to move keys i dont use to a corner of my keyboard to isolate em out of my game. This might sound silly but i do not like hotkeys hotkeyed if i dont use em.

The 'unknown' value maybe can be set but if so i dont know how to. 

Also i dont think its reasonable you can have multiple things hotkeyed to same key. It should be overwritten and become 'unknown'.

**Comment by rob-v** [comment]
You can't change it to Unknown in Settings dialog, but this works - change it to some key and then update it to UNKNOWN in settings.yaml, e.g.: PowerDownKey: UNKNOWN None
Support for multiple hotkeys is useful - e.g. observers can use simple hotkeys used by players for different action.

**Comment by pchote** [comment]
Seems reasonable.  We could inlay a clickable delete button glyph in the hotkey entry field.

**Comment by dragunoff** [comment]
I was looking for a way to achieve just that. It's reasonable to have a delete button. I think that a `reset to default` button also makes sense in case of accidentally remapping a key.
