### ISSUE TITLE
Game Freeze 

### ISSUE THREAD

**Issue by Azdizius** [OpenRA/OpenRA#13229]
Skirmish mode on one the maps 3 players game freezed on me when I was fighting 2 bots at same time. was in the middle of constructing a defence. deployed the defence and thats when it froze up.

**Comment by GraionDilach** [comment]
Coul you upload the replay of this game or the perf.log?

**Comment by Azdizius** [comment]
I reinstalled the game and since havent had a issue for future reference I will do that next time Sorry GraionDilach. Ill remember next time

**Comment by abcdefg30** [comment]
No problem. Leave a comment or reopen this with your logs attached if it happens again.
