### ISSUE TITLE
Coop lobby

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#13225]
Well it will be nice to have that, we can sure use video Buttons. 
Also allow **all videos to be able to play at least using a Button**, the ending videos will play but not the starting ones. 

And before some one say "you can currently play all videos right now" my answer will be "Nope" 
and i will continue with: "here is an example
World:
		StartVideo: IwontPlayForYouSucka.vqa 
**the starting video won't play at mission start on multiplayer**"

**Comment by KOYK** [comment]
Labels: None yet
So no one care for a coop lobby?

**Comment by MunWolf** [comment]
How many coop maps do we have? That and if no really important task exist control how much it is needed (also developer free time / interest).

**Comment by MustaphaTR** [comment]
> How many coop maps do we have? 
3

**Comment by MunWolf** [comment]
Then it is most likely a concern of priority and interest.
It is always hard to get people that are interested in UI work.

**Comment by KOYK** [comment]
It wont be fixed\added, closing it.
