### ISSUE TITLE
AI picks support power/superweapon targets without vision

### ISSUE THREAD

**Issue by Fauntleroy** [OpenRA/OpenRA#13222]
AI in both the Tiberium Dawn and Red Alert mods will use airstrikes, nukes, and ion cannons on targets they do not, and never had, vision of. This is exacerbated by the incredible power of the nuke, and the near-instantaneous effect of the airstrike.

Ideally the AI would try to scout for targets, or "guess" based on things like spawn location or buildings/units that they *have* seen before.

**Comment by atlimit8** [comment]
Duplicate of #7659
