### ISSUE TITLE
Anti virus false alarm (avast)

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#13234]
Avast removes OpenRA.Game.exe and places it under the "virus chest"  this could be a problem with some one new to the game as a trusting issue and could also stop players from playing the game if they don't know how an anti virus work. 

This should be added as troubleshooting information, and maybe contact the anti virus company?

**Comment by SoScared** [comment]
I use Avast Free. I had to deactivate and and reinstall due to the same issue. Avast sent the file to a cloud for further examination and came back to me after ca 30 minutes telling me it was safe, which I guess is a nice thing.

**Comment by Mailaender** [comment]
Please report it at https://www.avast.com/false-positive-file-form.php

**Comment by KOYK** [comment]
did any one reported it?

**Comment by Mailaender** [comment]
More people reporting it as a false positive will probably make them more aware and take action faster.
