### ISSUE TITLE
Unit ignoring movement commands until exiting from the tunnel.

### ISSUE THREAD

**Issue by aydjay** [OpenRA/OpenRA#13239]
![2017-05-04_19-07-49](https://cloud.githubusercontent.com/assets/9460838/25718466/1c3b136e-30fe-11e7-86b2-21dc8580b34f.gif)

Shown in the above gif, I'm sending a unit to the other side of the tunnel. Once the unit has entered the tunnel, I'm unable to send the unit back where he comes from. This is evident by the clicking animation on the cursor.

**Comment by pchote** [comment]
This is the expected behaviour.  Once a unit enters a tunnel it cannot stop until it exits the other side, and will then respond to any orders that you have given it in the meantime.

**Comment by aydjay** [comment]
It would appear that the original behaved in the same manner as demonstrated here:

**Comment by matjaeck** [comment]
> Shown in the above gif, I'm sending a unit to the other side of the tunnel. Once the unit has entered the tunnel, I'm unable to send the unit back where he comes from. 

This works now.
