### ISSUE TITLE
OS Version inconsistent on Windows 10

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#13243]
Yesterday I did a fresh install of Windows 10 1703 and (immediately) a fresh install of OpenRA 20170421.

This version of Windows is 10.0.15063 but OpenRA detects it as 6.2.9200.

![real_windows_version](https://cloud.githubusercontent.com/assets/25843400/25742559/47ff3286-3190-11e7-9a4a-90a54b4a4c90.jpg)

![openra_windows_version](https://cloud.githubusercontent.com/assets/25843400/25742562/499f0c60-3190-11e7-89b3-bb5783d0f13d.jpg)

According to [https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions](https://en.wikipedia.org/wiki/List_of_Microsoft_Windows_versions) NT 6.2.9200 is Windows 8.

Internet says people reported this bug in Windows 10 [https://www.google.com/search?q=windows+10+6.2.9200](https://www.google.com/search?q=windows+10+6.2.9200).

Commands like `ver`, `winver` or even `cmd` return the correct version number anyway.

**Comment by rob-v** [comment]
You're right: With the release of Windows 8.1, the behavior of the GetVersionEx API has changed in the value it will return for the operating system version. The value returned by the GetVersionEx function now depends on how the application is manifested.

Applications not manifested for Windows 8.1 or Windows 10 will return the Windows 8 OS version value (6.2).

I added this small .manifest file with listed supported Win 10 in this PR #13244 for consideration of inclusion.

**Comment by pchote** [comment]
We've known about this from the start, but haven't seen it as a big deal.  Our main interest is in distinguishing between "Modern Windows" (8.1+) vs "Legacy Windows" (7/Vista), which is still captured using the fallback behaviour.

**Comment by abcdefg30** [comment]
This seems to be fixed by now.
