### ISSUE TITLE
Potential z-offset issue with depth-buffer enabled sprites

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#13246]
See discussion in #12726.

**Comment by Mailaender** [comment]
Not sure if this is related, but if I render pavement with sprite offset using:

```csharp
var s = theater.TileSprite(tile);
dirty[cell] = new Sprite(s.Sheet, s.Bounds, s.ZRamp, s.Offset, s.Channel, s.BlendMode);
```

units will go through it when entering the cell:

![openra-2018-09-18t134705570z](https://user-images.githubusercontent.com/756669/45692118-4d1d0b80-bb5a-11e8-9105-1a25c81fb4a5.png)

Setting the offset to zero:

```csharp
dirty[cell] = new Sprite(s.Sheet, s.Bounds, s.ZRamp, float2.Zero, s.Channel, s.BlendMode);
```

breaks rendering of the pavement:

![image](https://user-images.githubusercontent.com/756669/45692194-7d64aa00-bb5a-11e8-97b2-b3b145a1f056.png)

**Comment by pchote** [comment]
Sprites that lie on the ground must define a ZRamp of 1 so that they can be treated as horizontal instead of vertical planes.

**Comment by pchote** [comment]
And the first screenshot, where you have ZScale 0 and a positive ZOffset, is defining this situation:
![hiding](https://user-images.githubusercontent.com/167819/45694624-9029af80-bb57-11e8-8d5a-558318971436.png)

The concrete layer is tilted, but pushed closer to the camera.   This pulls it in front of the tank, hiding the bottom part of it (from the perspective of the camera).

**Comment by pchote** [comment]
Note that this is not related to the original issue that this ticket is about.

**Comment by Mailaender** [comment]
Thanks. Your explanations helped me a lot with https://github.com/OpenRA/OpenRA/pull/15625. Maybe move them to the wiki.

**Comment by pchote** [comment]
Closing as duplicate of #12229.
