### ISSUE TITLE
Selling structure (PP) doesn't always give Rifleman

### ISSUE THREAD

**Issue by leodew** [OpenRA/OpenRA#13240]
In case of an enemy engy capture, selling a structure to get a rifleman can save your MCV.

However, I figured out today that is seems to be random. I sold a first PP, getting only technicians, then realized it too late. Sold another PP, got low power, but lost my MCV nevertheless, killed the engy too late. 

Shouldn't there be no random factor in it ? It's double punishing to lose a building (maybe getting low power) and still risking to lose the MCV due to chance.

**Comment by aydjay** [comment]
I think a little element of randomness is a good thing too keep but to force a minimum of 1 rifleman to spawn would be an adequate solution.

**Comment by Elizadmin** [comment]
And a maximum too or selling a $500 advanced power plant could give you $900 in riflemen.
