### ISSUE TITLE
Debug menu for spectators ?

### ISSUE THREAD

**Issue by Elizadmin** [OpenRA/OpenRA#13252]
Watching 100 % AI games is very helpful to find bugs.
As a spectator/admin/host, if you enable the debug menu in the lobby then you don't have it ingame.
Could it be possible to add a special debug menu for spectators (with Vizualizations only) ?

![debug_menu_enabled](https://cloud.githubusercontent.com/assets/25843400/25773991/ce638dfc-3287-11e7-99bf-3ee202f248bc.jpg)

![no_debug_menu](https://cloud.githubusercontent.com/assets/25843400/25773994/d126e3f4-3287-11e7-97f4-afa17445f72e.jpg)

**Comment by forcecore** [comment]
+1 for this, actor tags are very useful for conditional break points

**Comment by pchote** [comment]
We have a chat command `/terrainoverlay` to enable the terrain visualization, which works for spectators.  The simplest fix is to add similar commands for the other ones.

**Comment by rob-v** [comment]
Fixed by #13328 (partially - only showcombatgeometry, showactortags)
