### ISSUE TITLE
why mod-chooser removed in trunk branch?

### ISSUE THREAD

**Issue by carlos444** [OpenRA/OpenRA#13268]
It is very good and easy to switch game, is it abandon?

**Comment by Phrohdoh** [comment]
See #12554 and #13049.

**Comment by abcdefg30** [comment]
I wonder if we could bring it back (if it was maintainable) as external program and use the metadata to launch different mods.

**Comment by carlos444** [comment]
I hope it back, it is useful for ordinary player to easily switch games, if you switch game you need not to restart the game program by hand. The new one is good for modders, and that's true. So can it be in different binary files to load the different mod chooser and keep them both?

**Comment by rob-v** [comment]
In case you want to join existing multiplayer game, there is simpler/faster approach - in lobby, join (compatible) game of another mod - you are asked to switch - when confirmed, you switch mod and immediately join lobby.

**Comment by StormWingDelta** [comment]
Ya instead of removing it outright disconnect it and bring it back as a launcher that can be used to change between the different mods and is able to pickup and change between all versions of any mods on the computer or at least in the directory of it.

It'll help a lot for maintaining the ability to quickly change mods and versions of mods.

**Comment by pchote** [comment]
We already have external launchers that are able to pick up and change between all versions of any mods on the computer and show them together in one list: your OS's start menu / launchpad / dock / etc.  They even support downloading, installing, and uninstalling different versions :wink:

**Comment by pchote** [comment]
Question has been answered, so closing.
