### ISSUE TITLE
Add an option to disable Shellmap

### ISSUE THREAD

**Issue by Zogg** [OpenRA/OpenRA#13279]
The option to disable shellmap is gone in latest stable release. :(

**Comment by rmoriz** [comment]
Pleas re-add this issue. It's an enormous energy waste on my Macbook Air, leaving the fan running on top-speed.

**Comment by abcdefg30** [comment]
We could readd this option through letting the option start an empty shellmap like https://resource.openra.net/maps/28847/.

**Comment by pchote** [comment]
Pausing the simulation and rendering a static scene would look better, and with the frame buffer rendering we will only need to render the world once too.

**Comment by PunkPun** [comment]
It's now possible to pause  #18973
