### ISSUE TITLE
Renderingproblems: Letter alignment & grey lines

### ISSUE THREAD

**Issue by hderksen** [OpenRA/OpenRA#13272]
Hello,

since the new release I'm getting two kinds of renderingproblems.

1) Letters of one word are placed on different heights (especially on higher res)
2) Seeing some kind of a grid (grey and sometimes black lines). The grid appears and disappears randomly in each frame.

1024x768
![openra-1024x768](https://cloud.githubusercontent.com/assets/6515778/25915727/aec1144a-35c2-11e7-814f-9503dc45d680.png)

1920x1080
![openra-1920x1080](https://cloud.githubusercontent.com/assets/6515778/25915740/b6ec8230-35c2-11e7-81bc-814be8bde56c.png)

3440x1440
![openra-3440x1440](https://cloud.githubusercontent.com/assets/6515778/25915748/bdcb9906-35c2-11e7-9bfe-9d3a4e020644.png)

I tried different resolutions, windowed mode, is there anything i can provide to help you identifying the issue?

**Comment by reaperrr** [comment]
This is definitely the HiDPI scaling at work.

For a temporary solution, see @pchote's first comment on #13170.

I guess for our next release we need to disable this by default, at least on Windows.
