### ISSUE TITLE
Ship a bugfix release

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#13274]
The next major release will be very disruptive (removal of mod chooser, building hit shapes and presumably some more), and at the current pace of reviewing it will be an autumn release at the earliest, so I was thinking it might be better to release a bugfix release based on the last one as soon as we can, then we'd be under less pressure to get out the next major release quickly, possibly giving us more time 'to get it right'.

The number of reports about HiDPI issues on Windows systems is troubling, and things were pretty bad with DPI scaling enabled on my secondary system as well (Win10 laptop), so I'd say we should disable Windows DPI scaling by default, cherry-pick a few other un-risky fixes from bleed and ship it later this or early next month.

Candidates for cherry-picking:

General Improvements
- [x] #13278
- [x] #13248
- [x] #13089 
- [x] #13119
- [x] #12987
- [x] #13050
- [x] #13216
- [x] #13135 

Red Alert
- [x] #12982 
- [x] #13083 
- [x] #13085
- [x] #13086 
- [x] #12887

Tiberian Dawn
- [x] #13176 

Dune 2000
- [x] #13024 

Engine/Modding
- [x] #12888

______
Not yet implemented/merged:
- [x] #13205

**Comment by pchote** [comment]
:+1:

I'd like to ship a non-branching playtest at some point soon, getting the hit shape and autotarget changes out into the community for balancing.  That shouldn't affect this, however.

**Comment by pchote** [comment]
#13135 should be on our radar for this too.

**Comment by pchote** [comment]
We'll also want #13205 or ideally a modified version of it that is future proofed against future new errors.

**Comment by reaperrr** [comment]
Maybe #13050, too.

**Comment by pchote** [comment]
I'm not convinced about including balance changes in this release, I haven't heard any new balance complaints so its probably not worth the risk (expecting that this will be a direct release without any playtests first).

**Comment by reaperrr** [comment]
Okay, though I'd keep the D2k Sonic Tank fix, since it's really a fix (matching original).

**Comment by reaperrr** [comment]
@pchote I'm not sure how risky they are and whether they actually affect the shipping mods, what's your stance on these?

- Fixed GrantConditionOnPrerequisite not refreshing when the actor's owner changes.[#12981]
- Fixed stack traces not resolving debug symbols. [#12888]
- Fixed armaments blocking the use of other armaments in AttackGarrisoned. [#13110]

**Comment by GraionDilach** [comment]
By that logic the RangeMultiplier bugfix of #13219 could also hit that release. I'm not certain if that's a good scopecreep.

**Comment by pchote** [comment]
We definitely want the debug symbol fix, but I don't think the others are worthwile.  If i'm not mistaken they will only affect third party mods, and those should be migrating to the mod template instead of to this new release.

**Comment by pchote** [comment]
We should set a target date for this so that it doesn't drag on unnecessarily.

**Comment by reaperrr** [comment]
I've set Saturday next week for now, but if you think we should target a later (or earlier) date, feel free to update the milestone.

**Comment by GraionDilach** [comment]
What about including #13273?

**Comment by pchote** [comment]
That seems reasonable to me.

@reaperrr: have you started on a news post for this, or should I set some time aside to write one?

**Comment by reaperrr** [comment]
> What about including #13273?

Done.

> @reaperrr: have you started on a news post for this, or should I set some time aside to write one?

I hadn't started one, no, but I've thrown together something you can use as foundation, if you want: https://gist.github.com/reaperrr/86875dadf062d8b13d548ae0117e56bf

**Comment by abcdefg30** [comment]
I guess we want to include the fix for #13357 as well.

**Comment by pchote** [comment]
@reaperrr: do you want to join us on IRC while we coordinate deploying this?

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/releases/tag/release-20170527
