### ISSUE TITLE
Player name "shifted" when changing map

### ISSUE THREAD

**Issue by Elizadmin** [OpenRA/OpenRA#13287]
Release-20170421.
With no player in the first slot, selecting a smaller map does this :

![shift_1](https://cloud.githubusercontent.com/assets/25843400/26027555/419a48fa-3810-11e7-868f-71ac4f0634b6.jpg)
![shift_2](https://cloud.githubusercontent.com/assets/25843400/26027556/4581a062-3810-11e7-8d27-c43ba0f21369.jpg)

Selecting another slot gives your name back.

![shift_3](https://cloud.githubusercontent.com/assets/25843400/26027559/52b8c468-3810-11e7-81aa-eaeab69298ef.jpg)

**Comment by rob-v** [comment]
PR #13290
