### ISSUE TITLE
OpenRA crashing on FreeBSD after fresh install

### ISSUE THREAD

**Issue by soverysour** [OpenRA/OpenRA#13281]
Just installed it ( `#pkg install openra` ), which was the `release-20170421`, the latest stable one, according to the openra website.

The time when the game crashes varies; the first time i did not even get to the modchooser screen, and later i had to pray to not crash before downloading an 8 MB file. It crashed and crashed.

I did not see an `~/.openra/Logs/exception.log` file, but a `~/.openra/Logs/exception-0001-01-01T005718Z.log`. There was no `~/.openra/exception.log` file as specified on the FAQ page. That `exception-0001-01-01T005718Z.log` contained no characters. After deleting the `~/.openra/` directory and running the game to crash a few times, that `exception-0001-01-01T005718Z.log` file or any other `exception*.log` were not generated.

Right before the === message ===, after the `Stacktrace:` part, this was occasionally printed in the terminal: 
`* Assertion at sgen-alloc.c:384, condition *p == NULL' not met`

Also, the message enveloped in === was:
`Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.`

And here's a typical crash output from the terminal: https://pastebin.com/3L58XLeV

FreeBSD 11.0-RELEASE-p1, amd64.

**Comment by pchote** [comment]
This looks like something is fatally wrong with your `mono` install and/or the freebsd port for it.

The best I can suggest is to downgrade to an earlier mono version that may work better.  Anything above 4.0 should work fine with OpenRA.

**Comment by soverysour** [comment]
Installed the `/usr/ports/lang/mono` port ( 4.8.1.0 , compared to pkg's 4.6.? ), but it still crashed just the same. Still no exception.log.

When the occasional Assertion error prints, the message enveloped in === is the same, but complains about an SIGABRT instead of SIGSEGV.

**Comment by pchote** [comment]
Is this still an issue with the latest versions of mono and OpenRA @soverysour?

**Comment by soverysour** [comment]
Sorry, I unfortunately can't test it at the moment. If I ever get to test it, though, I'll let you know.

**Comment by abcdefg30** [comment]
No progress since a while. Please reopen this if you can reproduce the issue.
