### ISSUE TITLE
AI computes new rallypoints multiple times

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#13289]
Release-20170421.
AIs compute new rallypoints two or more times. Maybe one time could be sufficient ?

![multiple_rallypoints](https://cloud.githubusercontent.com/assets/25843400/26027677/6afef14e-3812-11e7-9d71-1e7bc126a4c4.gif)

**Comment by GSonderling** [comment]
The situation on the battlefield changes very quickly, it is conceivable that there is tactical value to different positions of rallypoint.

**Comment by St3x** [comment]
Just saw this on bleed.
The AI always computes two to four times the new rallypoint for every production building after any unit goes out from it.

**Comment by PunkPun** [comment]
On bleed AI sometimes still changes rally point 2 times like in the gif, but it's much rarer and doesn't I didn't notice it happening more than twice
