### ISSUE TITLE
[Idea][Lobby] Show "No of games currently running" somewhere around the server list

### ISSUE THREAD

**Issue by jaZzKCS** [OpenRA/OpenRA#13283]
Leaving the "Started"-filter off by default is - no questions asked - the more favorable alternative to having it set to enabled on default, as it would be both 1) a mess to scroll down each time during high-tide when there are a lot of games running - as well as 2) disadvantageous for other mods as their chance of being seen decreases even further...

Would it be beneficial to instead have (as simple number presented somewhere above/below/next to server list) the number of currently running games indicated (in the veins of RA: 0 (37); TD: 0 (12); D2k: 0 (0))??

That way we could both 1) decrease the number of players coming online and thinking there are no players/games happening at all, just because there are no games "waiting" - not immediately realizing that there are indeed 7 games "running" (not displayed) (this mostly happens during the low-tide hours, when you have a few games running but - most of the time - no games "waiting", giving the impression that there are no games happening at all) - as well as 2) decrease the usage of orabot-commands like "]players" at the same time.

**Comment by rob-v** [comment]
Next to title?

![obrazok](https://cloud.githubusercontent.com/assets/16348750/26029278/5381cbda-3831-11e7-92b5-3da404362bd5.png)

**Comment by jaZzKCS** [comment]
Maybe not exactly after the Multiplayer title, but yes, I was thinking of exactly this. Maybe we can find a nice place for it where it is immediately seen by ppl joining the MP lobby. I hope this will decrease the chance of ppl leaving - believing that there are no games running/waiting at all and also further decrease the amount of the ]players command in the IRC.
