### ISSUE TITLE
Map editor incorrectly reports all money on the map

### ISSUE THREAD

**Issue by kyrylo** [OpenRA/OpenRA#13299]
1. Create a new map
2. Place 4 ore tiles like this:
    ![openra 2017-05-14 22-39-02](https://cloud.githubusercontent.com/assets/1079123/26037147/27f1d5b2-38f6-11e7-8749-3f5d7944a84b.png)
3. Evidence that the map contains $500 worth of ore
4. Start a game with the created map
5. Place a refinery and order the spawned harvester to harvest this ore
6. Evidence that your harvester is full and there's 1 more unharvested tile left:
    ![openra 2017-05-14 22-35-39](https://cloud.githubusercontent.com/assets/1079123/26037158/74f1223c-38f6-11e7-972c-ce96499edc74.png)
7. Send the harvester to the refinery and evidence that you received $500 worth of ore
8. Send the harvester to grab the ore that's left and send it back to the refinery
9. Evidence that you received $100 worth of ore

Problem: map editor says that there's $500 worth of ore on the map. Harvester's capacity is exactly $500 worth of ore. When the harvester is full, there's still some ore on the map, which means the map has more ore than the map editor actually reports (in my example, it's $600).

Expected behaviour: the harvester collects all the ore on the map OR map editor reports the correct amount of ore on the map ($600).

**Comment by rob-v** [comment]
PR #13318
