### ISSUE TITLE
RA aircraft can inappropriately land when at ground elevation

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#13301]
If you hit "s" stop when an airplane is landing and it is at ground level, it will force land before properly reaching the airstrip.

![aircraft_bug](https://cloud.githubusercontent.com/assets/22008761/26039306/5be32e3e-38e7-11e7-892c-621cda30cdfe.png)

**Comment by pchote** [comment]
I expect a fix for this should fall out automatically if the aircraft activities are rewritten to use child activities.

**Comment by FrameLimiter** [comment]
Closing - this has been fixed on bleed.
