### ISSUE TITLE
Map editor: make certain terrain in multiple tabs available 

### ISSUE THREAD

**Issue by noobmapmaker** [OpenRA/OpenRA#13303]
In the map editor we have different categorytabs for different kind of terrain: roads, river, cliffs, etc.

Some of the tiles can be used in several categories. In bridges for example we find bridges for rivers. It would be nice to also have those in the River-category tab.

There are a couple examples of such tiles that allow the user to convert one type of terrain into the other:
- beach becomes cliff (could be both in Beach and Cliffs)
- bridges can be both in Beach, Road and River
- River going into cliff would be nice both in Cliffs and River
- .. any others?

If this would be implemented the I suggest doing them at the very end of a category.

**Comment by rob-v** [comment]
PR  #13339 enables to define more categories to be displayed at the end of list.
In case it was accepted, another PR is needed to add these categories to desired tiles, e.g.
Templates:
	Template@255:
		Category: Terrain, Bridge, River
