### ISSUE TITLE
HeliFly.cs activity hangs the game (zero minimum range case)

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13307]
Infinite loop:

A helicopter is very likely to hover over the target when controlled by AI. In this case
* HeliFly.tick() : Try to move towards target evaluates that the helicopter is inside the maximum range of the weapon so it thinks that it may proceed to Attack activity.
* Attack.cs, InnerTick(): However, this one thinks it needs to move, because
```
			if (!Target.IsInRange(self.CenterPosition, maxRange) || Target.IsInRange(self.CenterPosition, minRange)
				|| (mobile != null && !mobile.CanInteractWithGroundLayer(self)))
```

* The first expression correctly evaluates that the helicopter is in maxRange, proceeds to the next expr.
* The second one, evaluates that target is in minimumRange.
* IsInRange is INCLUSIVE and Helicopters with minRange of 0 will think that it needs to move away out of minimum range.
* Then it goes to HeliFly.tick() to move again then comes back to attack because it is within maximum range.

There's nothing that prevents modders having 0 range for helis!
Another thing is that 0 range makes sense when the "helicopter" is an airborne aircraft carrier!

**Comment by abcdefg30** [comment]
I think this is also related to the bug, that you can't paradrop units at 0 range.

**Comment by GraionDilach** [comment]
Oh yes, this is the bug which is why all jumpjets in RA2 has a minrange of (0c00)1.
