### ISSUE TITLE
No attack cursor for most units and harvesters. Impossible to attack.

### ISSUE THREAD

**Issue by rlees85** [OpenRA/OpenRA#13306]
The bug seems to be simply that there is no attack cursor therefore making it impossible to issue the attack command. Instead, only the normal green move cursor is shown and when clicked the unit moves, not attacks, even if an enemy is being hovered over.

Additionally, harvesters cannot be controlled as ore cannot be "targeted" only moved on top of.

Interestingly, aircraft and APCs **can** be given the attack order successfully.

About my system:

```
OS: ArchLinux
Kernel: 4.10.13-1-ARCH
OpenRA: 20170421-1
Mono: Mono JIT compiler version 5.0.0 (Stable 5.0.0.100/9667aa6 Fri May 12 07:20:13 UTC 2017)
```

Seems to have started happening after Mono was upgraded last night.

**Comment by abcdefg30** [comment]
Looks like the same issue as #13135.

**Comment by rlees85** [comment]
Yep identical. I did search for issues before posting but with "attack" and "cursor"... ooops!

**Comment by abcdefg30** [comment]
No problem, and thanks for reporting. :)
Closing this as duplicate now.
