### ISSUE TITLE
Right click joystick scrolling getting stuck

### ISSUE THREAD

**Issue by dsimmons87** [OpenRA/OpenRA#13300]
I have my mouse set up to right click joystick scrolling (like in generals), however sometimes when issues orders (also with right click), and panning the camera around, the camera seems to randomly start moving one way, and the only way to stop it is to right click, which often means troops end up being sent to the other side of the map.

If it helps, I think it may be something to do with left click too. Immediately left clicking while in a right click joystick move maybe.

I've attached a screenshot of my input settings:

![openrainputsettings](https://cloud.githubusercontent.com/assets/27823149/26037536/ca7aa62e-38ec-11e7-85f7-8bca99007172.png)

To replicate pretty easily:
1. Enter an openra game.
2. Make sure you have right mouse scrolling set to joystick in input options as in the screenshot.
3. In one quick action, right click + hold, move mouse,  left click while panning, release right click. This needs to be done pretty quickly.
4. Screen will continue panning after right mouse is released.

**Comment by dsimmons87** [comment]
Ok, I think I've fixed this on a local version of the game. I'll run it for a while to make sure it hasn't broken anything and submit a PR shortly if it's all good.

**Comment by rob-v** [comment]
Hi @dsimmons87, that are good news.
I'm sorry, if I knew you are working on the fix, I wouldn't start. I was just going to send PR when I noticed your update.
Anyway, feel free to submit your PR, it might be better. I will then close mine, instead of trying to improve it.

**Comment by dsimmons87** [comment]
Well I've tested mine and it's still not perfect. I've fixed the issue with left click which joystick moving making the camera move by overriding the YieldMouseFocus method. Is this the same thing you done?

However there is also another issue I've noticed when testing, where if you are moving the mouse around quickly and right clicking, for example if you are guiding a yak around, it moves the camera because it is triggering the right-click joystick.

I'm not sure if this is another issue entirely, but was going to see if it was easy to fix. The only thought I've had is maybe have a time delay or something?

**Comment by rob-v** [comment]
Yes, exactly, overriding the YieldMouseFocus method to cancel scrolling. It worked, but I had to do another small change. It is quite difficult to find, resolve, test this issue.

**Comment by rob-v** [comment]
I think the issue with Yak is that you are not doing it quickly, but that while you do it quickly you move the mouse little while holding right mouse button (which you use for moving and also scrolling), so it works as should.

**Comment by dsimmons87** [comment]
Yeah true, it is just to do with the mouse moving while issuing an order. I've also just tested this in Generals, and it does the same thing.
