### ISSUE TITLE
Mouse attack cursor not working in skirmish

### ISSUE THREAD

**Issue by rarules** [OpenRA/OpenRA#13311]
Hi,

I am on arch linux (antergos). When i play Single player skirmish there is no attack cursor. so i can send tanks to a location but if i hover the mouse over the enemy i cannot command to attack. 

Works in mission mode though.

Thank you for your help

**Comment by rob-v** [comment]
Are you using mono 5.0? Please check #13135.

**Comment by rarules** [comment]
Yes i am read the post thank you. can agree issue is also on linux mono 5.0
