### ISSUE TITLE
Cannot command harvester to harvest ore. OpenRA Red Alert 20170421, Mac OS 10.12.4

### ISSUE THREAD

**Issue by flybrianfly** [OpenRA/OpenRA#13316]
In previous versions of OpenRA, I could command harvesters where to harvest ore. Now that option appears gone; I can command harvesters to a location, where they will sit idle, or I can command harvesters to a use a specific ore repository, but I cannot command them to harvest ore at a specified location.

Possibly related, I also used to be able to use the command button to force units to attack things that were not enemy units, which was useful for destroying items like bridges, but that option appears missing in this version of OpenRA.

**Comment by rob-v** [comment]
Are you using mono 5.0? Please check #13135.

**Comment by pchote** [comment]
Please downgrade to mono 4.8.1 (https://download.mono-project.com/archive/4.8.1/macos-10-universal/) until we can release a new version of OpenRA that works around the bug.

**Comment by flybrianfly** [comment]
Yes, I was running mono 5.0 and this bug appears the same as #13135. Sorry, I used the wrong search terms looking through open issues. I downgraded mono to 4.8.1 and can confirm that this fixed the issue. Thanks!
