### ISSUE TITLE
Player filter for blocks projectiles.

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#13320]
A tag that allows blocks projectiles to block bullets only if the firer of the bullet has certain stance (ally, enemy) with the onwer of the wall, could be cool to support some kind of cover system.

**Comment by forcecore** [comment]
Probably a good way to implement Firestorm Defense in TS.

**Comment by PunkPun** [comment]
related #10789

**Comment by PunkPun** [comment]
fixed by #18796
