### ISSUE TITLE
Full screen is too full on Windows OS at current bleed

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13326]
![too_full](https://cloud.githubusercontent.com/assets/632278/26280042/ded6e0d0-3d8b-11e7-8ea8-7fb69e5b7e68.png)

As you can see from the super weapon timer and side bar getting out of the screen, the UI is too full.

![ignore_opt](https://cloud.githubusercontent.com/assets/632278/26280048/ffa713ca-3d8b-11e7-96f4-3e1cb5b47bd9.png)

Another problem is that it seems to be ignoring my windowed mode and resolution option.

**Comment by pchote** [comment]
I guess that you are running windows with a 1.25 display scaling factor, giving your desktop an effective resolution of 1536 x 864 for DPI-unaware applications.  We recently re-disabled our DPI awareness on windows, which means that it is once again using its legacy rescaling behaviour, and the 1600 x 900 size is now bigger than your effective screen size.  Making the window smaller will fix the issue.

**Comment by forcecore** [comment]
Changed resolution to 1280x720 and it is now OK.
