### ISSUE TITLE
[TS] Aircraft hover logic

### ISSUE THREAD

**Issue by aveferrum** [OpenRA/OpenRA#13334]
Currently, the aircraft in TS change their altitude through a full stop and hover up/down cycle depending on the elevation of the next tile. This is causing animation glitches and really weird behaviors in hilly maps. 

Instead of an on-the-spot hover up/down, I think a better method should be implemented like calculating an altitude curve which is easing depending on the target elevation and changes in between.

**Comment by GraionDilach** [comment]
Related: https://github.com/OpenRA/ra2/issues/361#issuecomment-294093687

**Comment by pchote** [comment]
The long standing plan here was to extract and generalize the height prediction code from the Missile projectile so it can be shared by both.

**Comment by GraionDilach** [comment]
The hover-on-the-spot behaviour is RA2-jumpjet-accurate though.

**Comment by aveferrum** [comment]
@GraionDilach yes, but  RA2 has only one unit where as TS has several and using the same behavior doesn't really look good though - especially for Harpys & Orca Fighters.  Banshee looks good though adjusting it's height smoothly, but then it's not a hovercraft.

**Comment by GraionDilach** [comment]
I never said it's aircraft-accurate. I said it's jumpjet-accurate. The following units were jumpjets and thereby had hover-on the spot behaviour: Nighthawk, Rocketeer, Kirov (along with YR's Siege Chopper, Floating Disk and Cosmonaut). Note that the Harrier or the Black Eagle ain't among them.

If the bleed VTOL flag would work properly (apparently not), then we would already be able to replicate TS/RA2 aircraft behaviour with CanHover: no and VTOL: yes but apparently such a setup doesn't take off vertically when built. As I've said in my linked comment already.

**Comment by reaperrr** [comment]
@GraionDilach That's a known issue, but the PR that will fix it depends on #13973 which hasn't gotten any reviews so far.

**Comment by Punsho** [comment]
All aircraft in TS now move over terrain smoothly
