### ISSUE TITLE
Tooltip on build menu flickers when game is set to 'slow' speed.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#13335]
![sdfg](https://cloud.githubusercontent.com/assets/2715583/26287492/0ffcf32e-3e7d-11e7-8644-888c72f60d51.jpg)

When moving the mouse slowly over the build menu the tooltip flickers. It happens only when the game is set to 'slow' speed.

**Comment by rob-v** [comment]
Thanks for this report, it helped us to find interesting situation. We found the reason, not sure how to fix yet.

Tip: Pause game, then you can read tooltips without flickering... :-)

**Comment by pchote** [comment]
Related to #12356.

**Comment by rob-v** [comment]
Fixed by #13365
