### ISSUE TITLE
TS - EMPed units continue to fire if was already firing

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#13355]
i.e. They don't lose target when EMPed. You can test by EMPing a unit forcefiring to ground.

Adding `RequiresCondition: !empdisable` to `Arrament:`s of each unit can be a solution. But in that case they would be unable to get a new attack command while EMPed, but they can get a move or deploy command for example.

**Comment by pchote** [comment]
Also Wolverines (see #14731):
![](https://user-images.githubusercontent.com/11763228/34922927-d23c9e14-f974-11e7-95d3-ac59789e7db2.gif)

**Comment by matjaeck** [comment]
Do we have an issue for the bug that units disappear under the EMP overlay (right wolverine in the gif above)?

**Comment by reaperrr** [comment]
Yes, though I haven't found the exact one yet. It's related to #13246, in any case.
