### ISSUE TITLE
OpenRA.Game.exe mod support

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13369]
Dear Devs,

Not many mods feature space but I found Nomad Galaxy (http://www.moddb.com/mods/nomad-galaxy) and tried to give Nolt support on displaying "skybox".

https://www.youtube.com/watch?v=sFV7S5zTavY

I sort of did it but the problem is, the background image and tile display code is in OpenRA.Game module, not DLL. Any suggestions on distributing such modifications for gamers to play? Also, per-map background image also modifies OpenRA.Game code, there is no way I can avoid modifying the very core part of the engine.

My changes:
https://github.com/forcecore/OpenRA/commit/27959a17afca9a716c85d64eaa6adc44dba0164a

**Comment by pchote** [comment]
Moving the terrain renderering into a mod-level trait has been planned for a while now (e.g. #13027), but hasn't been a priority feature.  More generally, the mod template is designed to allow mods to be able to ship custom engine versions if they want to make changes that aren't possible through mod code alone.

**Comment by forcecore** [comment]
"More generally, the mod template is designed to allow mods to be able to ship custom engine versions if they want to make changes that aren't possible through mod code alone."

Can you explain a bit more about this please? Can I include OpenRA.Game.exe in mod assemblies in YAML?

**Comment by GraionDilach** [comment]
No, the new mod template encourages the mods to package themselves as a separate installation.

**Comment by pchote** [comment]
The current bleed branch and future playtests/releases have a new modding system where mods do not depend on our "official" releases.  The [mod template](https://github.com/OpenRA/OpenRAModTemplate) is the modding SDK that we are developing to make it easy to develop/test/build installers for these new stand-alone mods.

The default behaviour of the SDK will be to fetch a specific engine version (e.g. a playtest or release build) from our main repository, but it will be a one line configuration file change to pull the engine from a different source (e.g. @GraionDilach's modder-friendly [Attacque Superior fork](https://github.com/AttacqueSuperior/Engine) or your own custom version).

The template is still a work in progress and missing quite a few features, but we are going to finish all the main features before we ship the OpenRA release that removes the old modding support.  You may have to just trust me for now that this will make life *so much better* for modders and players.

**Comment by forcecore** [comment]
OK I see
