### ISSUE TITLE
Add support for sight 'cones'

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#13368]
What I'd like to see implemented is support for 'directional sight', instead of revealing shroud/fog in a circle around the actor.

**Comment by mabulsoud** [comment]
I would also suggest adding limited firing arcs and sight blocking by objects. Although that might be orders of magnitude more difficult.

**Comment by Unit158** [comment]
@reaperrr Wouldn't this logic want to be found in a 3rd party mod rather than in the main repo? I don't know what is and isn't out-of-scope for mods.common.

**Comment by reaperrr** [comment]
@Unit158 I guess so. This particular feature may still require upstream changes, but I guess we don't really need an open ticket for this.

**Comment by Unit158** [comment]
@reaperrr I'd still be happy to code a quick solution if you need it. There shouldn't be any upstream changes needed because revealing shroud is done on a cell-by-cell basis (at least on the part of a trait)

**Comment by reaperrr** [comment]
I don't have an actual use/need for it at the moment, this idea just came up on a whim. But thanks for the offer, I'll notify you if the situation changes.
