### ISSUE TITLE
ResourceCenter: Carry over stats to next revision [feature]

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#13361]
Hi,
by uploading a new revision of a map, the "played" statistic gets reset - so it looks like the map has never been played before. This is kind of disheartening ^^. I would like to request this to be changed so that the statistic is accumulated over all revisions.

This applies to the "viewed ", "downloaded"  and "rated" as well.
Especially in rating this would be important. Currently this disencourages uploading revisions (if you care for the rating) and rating other maps yourself, since the rating will disappear anyway if the map is improved.

**Comment by pchote** [comment]
Please file this over at https://github.com/OpenRA/OpenRA-Resources/issues.
