### ISSUE TITLE
"Current cash" in replay

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#13375]
Similar to the earning graph in the replays, could there be a "Current cash" graph ? 
(But not on a 1min timescale like the earning graph, that would be too imprecise. Maybe every 10 secs ?)

Could be useful to identify the moments when players are broke (or floating), therefore help to improve one's gameplay.

**Comment by abcdefg30** [comment]
We do have "Income" now.
