### ISSUE TITLE
Need a way to check Condition Token from other Traits.

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13393]
This may sound odd but RequiresCondition can't cover slave miners.

In original YR. slave miners deployed and became structures. When the miner is undeployed while its slave outside, the slaved unit management trait is passed to the vehicle so that slaves continue to exist.

The best way to implement this in OpenRA would be to start from Tick tank (TS) and not deploy into structures but just change graphically. Fine.

However, when it comes to deployedness checking, RequiresCondition is not enough.  This slave management unit is active whether it is deployed or not. However, whether it is fine to spawn the slaves or not depends on deploy condition.

**Comment by GraionDilach** [comment]
Slave Miner should use Transforms though - it changed footprint during deploying in YR.

**Comment by forcecore** [comment]
Then it raises another problem of trait inheriting too

**Comment by penev92** [comment]
Sounds like a problem that should be manageable with Conditions + ActorInits. Also it may eventually be implemented in [OpenRA/ra2](https://github.com/OpenRA/ra2) and will concern the engine repo only if it actually requires engine changes.
