### ISSUE TITLE
INotifyDeploySuccess and INotifyDeployFail

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13400]
In continuation of slave miner thing, rather than querying DeployedState from activities, it could get notification from the deploy module instead. If it gets deployed successfully then it continues mining. If it fails, it can find another spot to deploy.

**Comment by forcecore** [comment]
Current existing OnDeploy implies DepoySuccess so only OnDeployFail is needed. Could be caused by queued order or tiberium growing on intended deploy position.

**Comment by pchote** [comment]
See the relatively new `INotifyDeployTriggered` and `INotifyDeployComplete` interfaces.

**Comment by forcecore** [comment]
But when the actor knows that deploy is triggered and wait for deploy to be complete, do we time out to detect failure?

**Comment by forcecore** [comment]
OK, DeployFail sounds to broad, it could be due to Death or anything. How about DeployBlockedByInvalidTerrain?

**Comment by forcecore** [comment]
#13400 indirectly solves this problem
