### ISSUE TITLE
Can you make Neutral enemies and Buildings Hostile?

### ISSUE THREAD

**Issue by ashman510** [OpenRA/OpenRA#13406]
So I finished making a map earlier and placed several neutral actors throughout, hoping that they would just fire on anyone that goes near them but they do nothing. Is there a a way to make them auto hostile towards anyone?

**Comment by Elizadmin** [comment]
Place creeps actors instead of neutral ones.

**Comment by abcdefg30** [comment]
Yes, that should be the right approach.

**Comment by ashman510** [comment]
lovely, thanks a bunch!
