### ISSUE TITLE
units occupying the same position at the same time only while moving

### ISSUE THREAD

**Issue by RRPRIME** [OpenRA/OpenRA#13418]
units occupying the same position at the same time only while moving 20170527.
notice APC and Flacktruck

![screen shot 2017-06-01 at 10 48 08 pm](https://cloud.githubusercontent.com/assets/6293391/26700133/89c9419c-471c-11e7-98a9-478a1e286c97.png)

Mainscreen map

**Comment by PunkPun** [comment]
This has been fixed
