### ISSUE TITLE
Units standing on water

### ISSUE THREAD

**Issue by RRPRIME** [OpenRA/OpenRA#13419]
Units standing on water
![screen shot 2017-06-01 at 11 11 55 pm](https://cloud.githubusercontent.com/assets/6293391/26702314/c9479dc0-4724-11e7-983d-334bde31e9ec.png)

maybe a square should be marked as impassable ?

**Comment by reaperrr** [comment]
Is that the desert terrain? Hard to make out since the screenshot is so cropped...

**Comment by RRPRIME** [comment]
Indeed it is desert terrain. I was thinking if the block contains water it should be impassable for vehicles/inf/ground units that should fix any units floating on water.

**Comment by Elizadmin** [comment]
It's the tile 409.
![walk_on_water](https://cloud.githubusercontent.com/assets/25843400/26731934/0b543174-47b6-11e7-9e4c-aaf5e70244fd.jpg)
