### ISSUE TITLE
Units rendered on battlefield and outside of it

### ISSUE THREAD

**Issue by RRPRIME** [OpenRA/OpenRA#13416]
From time to time you can "see" units rendered both on the battlefield and on the top left corner outside of the playable map:
![screen shot 2017-05-31 at 6 53 32 pm](https://cloud.githubusercontent.com/assets/6293391/26674001/1fb05528-46bf-11e7-9a06-c52ef69f7a55.png)
![screen shot 2017-05-21 at 2 59 43 pm](https://cloud.githubusercontent.com/assets/6293391/26674045/364aa900-46bf-11e7-9a38-c1d3dbc6e9fd.png)

**Comment by Elizadmin** [comment]
I noticed that too.
I first thought it was a paradrops bug but no, this guy is there on some maps before you even deploy.
For example he can be seen on Northwest Passage (http://resource.openra.net/maps/16075/) or Ore Lord.
He can be revealed by a simple paradrop at the top left cell.
![alone](https://cloud.githubusercontent.com/assets/25843400/26698033/89fb926c-4714-11e7-92ad-aef64bf44af0.gif)
The map editor shows nothing special there.
I have never found anybody else at the other corners.

**Comment by RRPRIME** [comment]
it even attacks which is annoying....unable to kill the unit

**Comment by abcdefg30** [comment]
The paratroopers issue has been fixed since.
