### ISSUE TITLE
If pathfinding algorithm fails to find a path unit does not move

### ISSUE THREAD

**Issue by RRPRIME** [OpenRA/OpenRA#13423]
If pathfinding algorithm fails to find a path unit does not move which is an issue if you have a way of 1 square and you want to retreat making the whole army freeze if something is blocking the path.

Algorithm should reflect the original RA as far as I remember it was finding the closest accessible square and moving there and re-evaluating the original path if now if free or not.

**Comment by Townes27** [comment]
[No Retreat, No Surrender](http://www.imdb.com/title/tt0089695/)

**Comment by obrakmann** [comment]
Duplicate of #12435
