### ISSUE TITLE
Deploying MCV automatically switched build menu to buildings

### ISSUE THREAD

**Issue by RRPRIME** [OpenRA/OpenRA#13421]
Deploying MCV automatically switched build menu to buildings which is quite annoying since you have your defense tab and want to deploy a defense ASAP

**Comment by FRenzy-OpenRA** [comment]
From my personal experience, this is a good thing at game start, so you can immediately start building, and gain a few seconds over your opponent. 

Also, as you are talking about basepushing, you don't only drop basedefences, but also buildings, so it's not that bad.

Finally, use hotkeys to quickly switch to whatever tab you like.

**Comment by RRPRIME** [comment]
But that does not fix the issue. My proposition is to leave the build menu at the exact state it is when deploying the MCV, further more if you want: if there is no build menu then default to the buildings one (when deploying the very first MCV).

Furthermore weighing in the values: you have 1 time benefit at the very start which might not be that important (also that is the only available menu since the game just started so it makes sense to show the buildings menu) versus a benefit that can come in handy any time during a play.

Imagine a new scenario:  you have the Vehicles queue and you are selecting the vehicles you want and in between you deploy a MCV and now you have to do an extra move to switch back to the queue you were just a second ago.

**Comment by pchote** [comment]
This is a feature that applies to all production structures across all the default mods - selecting a production structure switches to its default queue.

**Comment by RRPRIME** [comment]
I think this should change, this should not be a default action for a RTS game with a permanent display of queues. The purpose of the permanent queue is to be able to build when you are far away from the base.

StarCraft does not have a permanent display and it makes sense to "select" the queue of the building.

Will have a look at RA2

**Comment by GraionDilach** [comment]
RA3 works like this for sure. Also this behaviour is more practical. Especially when individual queues are used, like in TD. You can forget which production structure is which queue afterall.

**Comment by obrakmann** [comment]
I think we are mostly in agreement that this long-standing behaviour will not change. Closing as WONTFIX.
