### ISSUE TITLE
Tesla firing below a adv power plant

### ISSUE THREAD

**Issue by RRPRIME** [OpenRA/OpenRA#13420]
Tesla firing below a adv power plant
![screen shot 2017-06-01 at 11 47 09 pm](https://cloud.githubusercontent.com/assets/6293391/26702351/eae80078-4724-11e7-9a3f-881b4d4d6176.png)

**Comment by obrakmann** [comment]
In this case you could argue that it's firing behind the building, and with the weird perspective the original games used, it would even make sense. It would look equally strange if the bolts were drawn above the building. Closing as WONTFIX.

**Comment by djohe** [comment]
This needs to be reopened, this is an actual bug of the projectile.
![OpenRA_Teslazap_proj_bug](https://user-images.githubusercontent.com/771748/62943427-bc3ac880-bdda-11e9-93e1-920ec0d0e679.png)
