### ISSUE TITLE
Complete the mod template/sdk to an initial 1.0 state.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#13446]
Depends on:
- [x] https://github.com/OpenRA/OpenRAModTemplate/issues/7
- [x] https://github.com/OpenRA/OpenRAModTemplate/issues/9

https://github.com/OpenRA/OpenRAModTemplate/issues/8 would be nice, but shouldn't block the playtest.

**Comment by pchote** [comment]
Done.

**Comment by Mailaender** [comment]
I assume https://github.com/OpenRA/OpenRA/wiki/User-Created-Content needs an update now?
