### ISSUE TITLE
Ranked pillbox-inhabitant losing sight

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#13459]
Release 20170527

1.Place a pillbox near enemy-infantry and let it kill a couple so the E1 inside will rank up 
2.Sell the Pillbox 

The ranked E1 inside will be under the fow and lose its sight

![pillshadow](https://cloud.githubusercontent.com/assets/9139965/26791078/4afe3f60-4a16-11e7-9924-26e101cec889.png)

**Comment by Micr0Bit** [comment]
this is still present in playtest 20170902

**Comment by abcdefg30** [comment]
I don't think this is still an issue.
