### ISSUE TITLE
TD: Aircraft rearming and repairing

### ISSUE THREAD

**Issue by ymladenov** [OpenRA/OpenRA#13457]
Release-20150527
GDI
- Chinook doesn't repair at helipad
- Orca doesn't repair at helipad
- Orca rearms itself (is this normal behavior?)
NOD
- Apache doesn't repair at helipad
- Transport doesn't repair at helipad

**Comment by reaperrr** [comment]
> Orca rearms itself (is this normal behavior?)

Yes, for our TD mod that's intentional.

A fix for the repair issue has already been merged, so this will be fixed by the next playtest/release. Closing as solved.
