### ISSUE TITLE
Aircraft leave the map

### ISSUE THREAD

**Issue by gdavegdave** [OpenRA/OpenRA#13451]
In TD, aircraft can leave the map and are then difficult to control. When orcas and apaches are towards the edge of a map, especially the corners and especially in larger groups, some will often go on an excursion. The aircraft can then only be made to return at certain angles, along certain paths. You can not bring them back directly. Left alone, the aircraft are prone to moving large distances outside of the map, even along the entire length of a map.

This is easy to reproduce: build five apaches or orcas then tell them, as a group, to move to the corner of the map. Keep them selected and watch as one leaves the map and e.g. comes back to another corner. I attach an example replay (on a stock map and created in release-20170527). 

This issue seemed to arise a release or two ago. Perhaps it coincided with the fix to the bug that meant aircraft could not be targeted when at the very top of the map. 

N.B. Just remove the .txt suffix, which I had to add to get github to accept the replay upload (only certain file types are accepted)
[OpenRA-2017-06-04T135454Z.orarep.txt](https://github.com/OpenRA/OpenRA/files/1050366/OpenRA-2017-06-04T135454Z.orarep.txt)

<img width="1920" alt="screen shot 2017-06-04 at 15 05 11" src="https://cloud.githubusercontent.com/assets/26625017/26762252/30e1f8ea-4937-11e7-9dcc-b5e214c440ae.png">

**Comment by reaperrr** [comment]
> The aircraft can then only be made to return at certain angles, along certain paths.

@pchote Am I right in suspecting that your fix that was supposed to prevent them from leaving the map in the first place (by pushing them back) also makes it hard for them to return to the map once they do managed to leave it somehow?

**Comment by pchote** [comment]
It is supposed to continuously push them back into the map, but it is possible that there is a bug that pushes them in the wrong direction in some (most?) circumstances.

**Comment by theKalash** [comment]
A similar thing also happens in RA.

If planes circle near the edge of the map they sometimes get pushed along the map edge and drift of, potentially going quite deep outside the map (and also moving along the side of the map)

**Comment by BGluth** [comment]
@pchote 
I took a look at the code to generate a repulsion force when a unit goes outside of the map. I don't really understand what's going on with the calculations to calculate the repulsion force, but I inserted a `WriteLine` and got some interesting output when planes/helicopters leave the map in RA.

Every map boundary except the north side is always applying a force in the wrong direction. For example, the west boundary is actually applying a force in the negative x direction which should push the air unit further west. Here's the output for east, south, and west (for both helis and planes):  

```
East:
Out of bounds force applied: 298,979,0 to position: 132116,45975,2560 with map center at: 66047,66559,0

South:
Out of bounds force applied: -996,236,0 to position: 81718,132854,2560 with map center at: 66047,66559,0

West:
Out of bounds force applied: -298,-979,0 to position: 978,86558,2560 with map center at: 66047,66559,0
```

What I found a bit surprising is that the north boundary is applying the correct force in the y dimension for planes but not for helis:

```
North (planes):
Out of bounds force applied: 1023,24,0 to position: 67663,914,2560 with map center at: 66047,66559,0 

North (helis):
Out of bounds force applied: 1020,-85,0 to position: 60596,1014,1280 with map center at: 66047,66559,0
```
I also noticed that for helicopters they don't seem to be affected any force applied to them until they are past about 3-4 cells outside of the boundary.

This is where the `WriteLine` is located:
```csharp
// Actors outside the map bounds receive an extra nudge towards the center of the map
if (!self.World.Map.Contains(self.Location))
{
	// The map bounds are in projected coordinates, which is technically wrong for this,
	// but we avoid the issues in practice by guessing the middle of the map instead of the edge
	var center = WPos.Lerp(self.World.Map.ProjectedTopLeft, self.World.Map.ProjectedBottomRight, 1, 2);
	repulsionForce += (new WVec(1024, 0, 0).Rotate(WRot.FromYaw((self.CenterPosition - center).Yaw)));
	System.Console.WriteLine("Out of bounds force applied: {0} to position: {1} with map center at: {2}", repulsionForce, self.CenterPosition, center);
}
```

**Comment by gdavegdave** [comment]
That sounds in keeping with my experience. When air units leave the map
they are not static, but move in particular directions.

Also, they can only return (via user input) along certain vectors, as
expected if they are being pushed in a particular direction (that should
be, but isn't, towards the map).

**Comment by gdavegdave** [comment]
That sounds in keeping with my experience. When air units leave the map they are not static, but move in particular directions. 

Also, they can only return (via user input) along certain vectors, as expected if they are being pushed in a particular direction (that should be, but isn't, towards the map).

**Comment by tovl** [comment]
The repulsion is actually always wrong, because it is pointing 90 degrees from what it should be. This causes the planes to orbit the center instead of being pulled towards it.

```csharp
	repulsionForce += new WVec(1024, 0, 0).Rotate(WRot.FromYaw((self.CenterPosition - center).Yaw));
```
should be
```csharp
	repulsionForce += new WVec(0, 1024, 0).Rotate(WRot.FromYaw((self.CenterPosition - center).Yaw));
```

because we define yaw to be 0 in the negative y direction.
