### ISSUE TITLE
[bleed branch]unbreakable building in Knock out the Refinery mission of Tiberian Dawn

### ISSUE THREAD

**Issue by carlos444** [OpenRA/OpenRA#13468]
bleed branch building on 20170607 on debian 8.8 i386
![- 2017 06 07 - 11 25 47](https://user-images.githubusercontent.com/2613235/26861166-9f8f127a-4b74-11e7-919f-d7b42a572f5d.png)
This NOD PowerPlant is unbreakable, I will never beat down NOD. :-P

**Comment by carlos444** [comment]
![- 2017 06 07 - 12 35 33](https://user-images.githubusercontent.com/2613235/26862447-e0069194-4b7d-11e7-9b77-14351650ba15.png)
unbreakable Soviet Ore Refinery in mission ten to one of RedAlert.
same bleed branch.

**Comment by MustaphaTR** [comment]
WAI, after the HitShape PR, stuff got broken. I think only D2K works fine right now. They'll be fixed when their HitShape PRs are merged.

**Comment by pchote** [comment]
Yes, we know and this was planned.  Wait for #13460 and #13448.
