### ISSUE TITLE
Move macOS builds to 64 bit.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#13478]
From https://developer.apple.com/videos/play/wwdc2017/102/

> High Sierra will be the last macOS release to support 32-bit apps without compromises.
> From the next major release after High Sierra we are going to start aggressively warning users if apps are not compatible with 64 bit.

This gives us about 12 - 15 months to move to a 64 bit build.  Apple will be removing 32 bit support entirely in a further year or so, so there is no point offering a fat binary with both architectures.

Mono 5.0 now ships with the 64 bit runtime, so the technical parts are easy:
* Recompile `libSDL2.dylib` and `liblua.5.1.dylib` as 64 bit.
* Change `-m32` to `-m64` in the [osx launcher makefile](https://github.com/OpenRA/OpenRALauncherOSX/blob/master/Makefile)
* Bump our minimum mono requirement to 5.0.

The launcher should then automatically load and use the 64 bit runtime.

Before we do this we need to make sure we understand and prepare for any potential stability or performance effects.  The best way to do this will be to collect a few representative replays for the main mods recorded on the current (32 bit) release, and then play them back using `mono64`.  Comparing the play times should give us some stats on the overall perf changes, and any runtime incompatibilities will manifest as desyncs.

**Comment by Mailaender** [comment]
See also https://github.com/OpenRA/OpenRA/issues/12587

**Comment by reaperrr** [comment]
Do we have representative numbers on how many players with Vista/7+ @32bit we have? If that number is low enough, might as well consider doing the same for Windows builds.

**Comment by Mailaender** [comment]
Version | OS X total | x64 machines | %
-- | -- | -- | --
release-20170421 | 624 | 501 | 80,29 %
release-20170527 | 1030 | 815 | 79,13 %
playtest-20170722 | 20 | 15 | 75,00 %
playtest-20170408 | 57 | 48 | 84,21 %
playtest-20170304 | 101 | 73 | 72,28 %

Will post other Windows/Linux at https://github.com/OpenRA/OpenRA/issues/12587 as this seems to be the macOS ticket and Apple is setting the pace anyway.

**Comment by pchote** [comment]
In practice 100% of (non-hackintosh) macs that will be capable of running OpenRA are natively 64 bit.  The numbers given by our sysinfo (from `Environment.Is64BitOperatingSystem `) should correlate hopefully perfectly with mono versions older/newer than when [xamarin#37414]( https://bugzilla.xamarin.com/show_bug.cgi?id=37414) was shipped.

**Comment by pchote** [comment]
Our minimum program-enforced minimum mono version on macOS is still 3.2.  We could consider bumping this to 4.4 before our next release: this would give us more accurate stats and players some nice performance improvements.

**Comment by Mailaender** [comment]
Indeed Mac users are already 64-bit. Numbers trying to incorporate xamarin#37414]( https://bugzilla.xamarin.com/show_bug.cgi?id=37414) show that:

Version | Mac users total | Mono 4.0.X (bugged) | Mono 4.2.X (bugged) | Mono 4.4.X (bugged) | valid Mac users | x64 machines | %
-- | -- | -- | -- | -- | -- | -- | --
release-20170421 | 1528 | 18 | 36 | 37 | 1437 | 1449 | 100,84 %
release-20170527 | 2067 | 34 | 59 | 46 | 1928 | 1951 | 101,19 %
