### ISSUE TITLE
Mad Tank moves after deploy with attack order

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13470]
Normally you can't make them move after deploying.
However, if you queue it by giving it an attack order mad tank deploys and moves while thumping. It doesn't seem to blow.

https://youtu.be/UFqJG38KHbY

**Comment by AMHOL** [comment]
This is the same with the MCV, if you issue a move command, followed by a queued deploy command and a queued move command, it will just deploy at the destination of the first move command.

**Comment by RRPRIME** [comment]
no repro on 20170527. also what I noticed is that the attack vector in the video stays active/visible a lot longer then it does on 20170527

**Comment by forcecore** [comment]
Ugh, sorry about that, probably because I'm sort of behind eventhough I thought I am on bleed. I'll re-check after the PR is accepted.

#13336

**Comment by RRPRIME** [comment]
partial repro on 20170527,  1 out of 30-40 tries (maybe a race condition ?) also the tank explodes
![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/6293391/26886404-867c9ef2-4ba5-11e7-9d2b-a38669a54023.gif)

**Comment by RRPRIME** [comment]
full repro on 20170527 steps:
1) get mad tank
2) queue attack on an enemy building
3) queue another attack on a further away enemy building (to keep it alive)

failure to move the unit further away from the deploy fast zone will result in unit exploding even though moving.

**Comment by CH4Code** [comment]
Works with a shift-queued move order right after deploy order on a moving MAD Tank, too.
1. Give a move order to the MAD Tank
2. Oder deploy between activities/cells
3. Shift-queue a move order immediately
