### ISSUE TITLE
Black screen problem

### ISSUE THREAD

**Issue by zylexcrome97** [OpenRA/OpenRA#13479]
every time i launch OpenRA, i always get a black screen... i can't even find the UI to launch the game.. but i can only see the game cursor.

 is there a solution for this? please help :(

**Comment by abcdefg30** [comment]
Which OS are you on? (OSX is known to cause this: https://github.com/OpenRA/OpenRA/wiki/FAQ#pinwheel-of-death-when-starting-on-os-x-for-the-first-time ).

**Comment by zylexcrome97** [comment]
Windows 7

**Comment by GraionDilach** [comment]
Wait, if you have a GeForce 310... why are you using the Intel graphics?

**Comment by zylexcrome97** [comment]
@GraionDilach idk.. smhow after updating the Intel Graphics, the screen went back to normal. :/

**Comment by abcdefg30** [comment]
So, your blackscreen issue is resolved now?

**Comment by zylexcrome97** [comment]
@abcdefg30 yeah it's solved now. but im having a huge lag when playing

**Comment by MunWolf** [comment]
Maybe it is lagging because your computer is using the integrated card instead of the nvidia one, could be a configuration or driver problem.

**Comment by abcdefg30** [comment]
I guess the lag is a different issue so this can be closed now.
