### ISSUE TITLE
Attack move inconsitency betwen Heli and Planes

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13474]
Heli: after attack move and running out of ammo, it will reload and comback and continue with attack move

Plane: It will run out, reload and will not leave the airfield. Unless this is intended, in C&C Generals, aircrafts had "guard area" which behaved similar to above heli behavior.

https://youtu.be/Pb7YtlVp3cs

Sort of related to bigger issue of #12564

**Comment by Smittytron** [comment]
The Helis continuing an a-move is annoying as they tend to get themselves killed a minute after the original order.
From a players perspective the ideal would be for helis and planes to take off to the rally point after reloading.

**Comment by matjaeck** [comment]
A thing to note is that it has a *significant* effect on performance if planes are landed or circling in air. That alone justifies IMO that planes in RA land / stay landed when ordered to rearm / return to base. They do not block the airfield for planes without ammo.

Regarding the continuing attack move i agree with what Smitty said. Aircraft are IMO much too valuable and vulnerable to let them move across the map without explicit order from the player.

**Comment by matjaeck** [comment]
Can we try to fix this for the playtest as part of the attack-move /aircraft refactorings? IMO helicopters should go to the rally point after reloading while planes should remain landed - the attack move should always be aborted in both cases when aircraft need to reload.
