### ISSUE TITLE
[bleed branch]if openra fold owner is root, a lot of map missing.

### ISSUE THREAD

**Issue by carlos444** [OpenRA/OpenRA#13486]
building on 20170608 on debian 8.8 i386
put openra folder in /opt/games/
if chown root:root openra -R
just 2 maps left in Select Map:
![root_privileged](https://user-images.githubusercontent.com/2613235/26999558-56bb6226-4dcf-11e7-8939-b3c0b5916d9b.png)
but if chown carlos:carlos openra -R
all maps will be show:
![carlos_privileged](https://user-images.githubusercontent.com/2613235/26999562-6c0ec794-4dcf-11e7-9c80-e879a2a70b9a.png)

The files and folders mod bits are 644 and 755.

**Comment by abcdefg30** [comment]
I don't think there is much we can do here.
