### ISSUE TITLE
chinooks stack on top of each other when landing

### ISSUE THREAD

**Issue by RRPRIME** [OpenRA/OpenRA#13480]
chinooks stack on top of each other when landing
Mission:Intervention
![ezgif com-video-to-gif 3](https://user-images.githubusercontent.com/6293391/26943112-c057fc18-4c84-11e7-9d41-c3785536ce94.gif)

**Comment by FRenzy-OpenRA** [comment]
Duplicate of this ? #13177

**Comment by atlimit8** [comment]
Duplicate of #6068 & arguably #4605.
