### ISSUE TITLE
TS Juggernaut busts part of the editor Actor list

### ISSUE THREAD

**Issue by cjshmyr** [OpenRA/OpenRA#13492]
When the map editor is initializing actor panel previews, specifically for `jugg`, an odd `IdealPreviewSize` is being set and preventing it + further actors in the loop from being selectable.

In [ActorPreviewWidget](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Widgets/ActorPreviewWidget.cs#L69), `r` yielded 3 renderables -- the third is a `FinalizedVoxelRenderable`, and its `ScreenBounds()`  is returning an off width/height.

**Comment by Mailaender** [comment]
This seems to be resolved now.
