### ISSUE TITLE
Rush AI produces too many airfields

### ISSUE THREAD

**Issue by djlists** [OpenRA/OpenRA#13498]
Rush AI created 19 air fields but no airplanes in skirmish game. Debug mode was on and "Instant Build Speed" was selected.

**Comment by pchote** [comment]
Having debug mode on will not impact this: turns out that rush ai defines `afld` as a production building, with *no build limit*, and no desire to build planes.  That means that after its base reaches a certain stage it will decide to build endless airfields but no aircraft.
