### ISSUE TITLE
SyncReport grows too large and causes out of memory crash

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13499]
In some mods, there are so many effects that

In SyncReport.cs, GenerateSyncReport(), 

					report.Effects.Add(new EffectReport()

The report accumulates and eventually crashes the game. At the start of the game the games takes up about 400MB then explodes to 1.2GB then dies. Can it be turned off?

**Comment by aydjay** [comment]
Would caching be an option instead or is it just growing endlessly can not being cleared down when appropriate?

**Comment by forcecore** [comment]
It grows endlessly without being cleared. If it can be cleared the game will run much smoother due to improved cache memory usage. (I commented it out temporarily and performance got better)

**Comment by forcecore** [comment]
I'd like to mention that it happens in a very long SINGLE game
