### ISSUE TITLE
Unplayable on Dell XPS 15 running Ubuntu

### ISSUE THREAD

**Issue by rmetcalf9** [OpenRA/OpenRA#13494]
Hi,
I have downloaded OpenRA on my Dell XPS 15. I am running Ubuntu 16.04 with the resolution set to 3840x1260
The graphics (Both in game and menu are tiny)
I am running the latest release "release-20170527"
![example](https://user-images.githubusercontent.com/14248366/27012655-c67191ce-4ecb-11e7-8d59-f4fd12828e10.png)
I have attached a screenshot of it running in windowed mode next to the openra home page for a comparison.
I have been through all the options and I can't find anything that would do anything about this. I need to make the game 3 or 4 times bigger in order to view anything at all.
Robert

**Comment by pchote** [comment]
You can set the `OPENRA_DISPLAY_SCALE` environment variable to enable HiDPI rendering on Linux.  E.g. from a terminal run `OPENRA_DISPLAY_SCALE=2 openra` or set it in your startup config.

**Comment by rmetcalf9** [comment]
Hi,
Thanks that worked. I set it to 3.
Just working out how to put it into the startup config.
Maybe this can be added to the FAQ (I did check that before posting)
Robert
