### ISSUE TITLE
can't install thridparty deps

### ISSUE THREAD

**Issue by wangjianpeng** [OpenRA/OpenRA#13501]
i am a newer to shell scripts.
I want to build the solution in window 7. when i double click the shell file under the thirdparty folder, nothing happen.I make step under the Install file instruction to download dll from nuget, but i found some dll can't find in nuget file,for example liblua 5.1 . how can i use make dependencies command, should i install some tool?
Please help me,i am newer to shell script.
Why the source repository  can't contains its thirdparty  dependencies  so that i have not to download them after clone from git.

**Comment by GraionDilach** [comment]
You shouldn't doubleclick the dependencies shells within the thirdparty folder directly, but launching make.ps1 which will set them all up properly, as the build instructions tell you.

>Why the source repository can't contains its thirdparty dependencies so that i have not to download them after clone from git.

That's untidy, sometimes can differ between OSes, and conflicts with Linux package guidelines.

**Comment by Phrohdoh** [comment]
- Launch PowerShell
- `cd` to the root of OpenRA's source
- run `.\make.ps1 all`

**Comment by pchote** [comment]
Double clicking `make.cmd` should also work.

**Comment by wangjianpeng** [comment]
thank you all , It wok now.
