### ISSUE TITLE
RA1 cameo text plugin for GIMP

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13507]
I made a GIMP plugin to automate letter embedding for RA1 cameos.

https://www.youtube.com/watch?v=IHOe-uCPbh8

One of the common-case use for OS SHP Builder would be making cameos. Unfortunately

* It doesn't run without Wine, on Linux.
* RA1 cameo is bugged to use RA2 font

Parameters can be adjusted to support other fonts too by defining widths of each letter and the path where the PNG files of the letters are. I think it can become part of OpenRA tools? (such as tile builder?)

**Comment by Mailaender** [comment]
Can you link the source code of your GIMP plugin? What makes it Windows only?

**Comment by forcecore** [comment]
I meant OS SHP Builder works on Windows. My plugin isn't Windows only, I just haven't tested it on Linux version of Gimp.

https://github.com/forcecore/yupgi_alert0/blob/master/assets/put_ra1.py : This script

https://github.com/forcecore/yupgi_alert0/tree/master/assets : Contains ra1_cameo_font folder which holds needed alphabet letters in PNG.

**Comment by Mailaender** [comment]
I suggest you place it into it's own repository and then we can fork it.

**Comment by forcecore** [comment]
OK, I'll do the polishing then make its own repository + write installation instructions.

**Comment by forcecore** [comment]
https://github.com/forcecore/CameoTextEmbedder : Repository created and installation instructions wrote.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/CameoTextEmbedder
