### ISSUE TITLE
[bleed branch][TS]Visceroid can not hurt any unit.

### ISSUE THREAD

**Issue by carlos444** [OpenRA/OpenRA#13505]
build on 20170613 on debian 8.8 i386
In Tiberian Sun mod, Visceroid can not hurt player or AI unit, even the soldier stand at the side of it.

**Comment by rob-v** [comment]
@reaperrr In #13196 InstantHit was recently changed target from Actor GuidedTarget to Terrain PassiveTarget when TargetCenterPosition is false (default). It effects TargetDamageWarhead used for SlimeAttack by VISC_LRG as TargetDamageWarhead supports only TargetType.Actor so no damage is done to e.g. infantry.
Can you please check it? I am not sure what is the right solution to this issue.
