### ISSUE TITLE
INotifyOwnerChanged interface doesn't deliver enough information

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13503]
It needs to have "what action changed the ownership" field, preferably in string type.

Scenario: Let's say there is building mind controller, like Yuri Prime. His MC is temporary so that when the mind control effect goes away due to Yuri's death or Yuri controlling something else, the building's ownership should be reverted back to creator owner.

However, MC isn't the only method of ownership change. There is already a permanent MC, in the name of "Engineer capture". For engi capture, creatorOwner must change so that if the captured actor gets mind controlled, it should be returned to the new capturer = the new creatorOwner.

In Kane's Wrath, cultists can mind control enemy units. In Traveller mirror, they often fight over a few high tier units. Even the creator owner can mind control what enemy has mind controlled! (In this case, the owner gets the unit 100% back, the unit is not counted as mind controlled anymore.)

Then there's slave miner. Killing the slave driver changes the creatorOwner of the slaves, in case they get mind controlled.

Maybe RA2 Garrison needs this too?

**Comment by forcecore** [comment]
Maybe not, if I track mindcontrol very carefully. Leaving open for just a few days in case anyone agrees

**Comment by pchote** [comment]
Take a look at D2K deviator implementation.  It is pretty much a time-limited mind control.
