### ISSUE TITLE
Investigate replacing some lint rules with YamlExceptions

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#13533]
Yaml testing has become horribly slow, taking over 10 minutes on Travis and nearly 2.5 minutes locally on my system for the official mods.

Some of the current lint checks might be replacable with YamlExceptions (or other exceptions) without much of a risk, basically just moving the moment the yaml error is noticed from lint to mod launch.

**Comment by pchote** [comment]
YamlExceptions thrown during *Info parsing will also be caught during linting.

The real issue is that the linting infrastructure was not designed with performance in mind.  That should be fixed regardless of whether some things can be moved away from tests.

**Comment by Mailaender** [comment]
> Some of the current lint checks might be replacable with YamlExceptions (or other exceptions) without much of a risk, basically just moving the moment the yaml error is noticed from lint to mod launch.

Isn't that moving bad performance from build machines to players at game start then?

**Comment by reaperrr** [comment]
> Isn't that moving bad performance from build machines to players at game start then?

I don't think so. First of all, we're only talking about a handful (at most) lint checks, and less 'expensive' ones at that.
Second, the lint rules check all 4 official mods, while the YamlExceptions would be limited to the played mod.
Well and third, what @pchote said, the lint infrastructure probably takes much longer for the same amount of checks, or performs far more redundant checks.

**Comment by Mailaender** [comment]
I saw that my CheckBuildingFootprint was replaced in https://github.com/OpenRA/OpenRA/commit/46dc827d46bbb7dce353ac04bcb299d130c73022. Just noting it down for others to see an exemplary change.

**Comment by Mailaender** [comment]
Since the .NET Core migration I think this needs a re-evaluation. The lint tests are actually quite fast now.

**Comment by abcdefg30** [comment]
Agreed. Speeding up the checks itself is covered by #13937 so closing this here.
