### ISSUE TITLE
Make condition manager exception useful.

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#13550]
Currently, when the game crashes due to a condition manager error, the exception will only tell you that, for us modders that is quite painful, because we got a thousand conditions in use, would it be possible if the exception could be more accurate? say, actor X does not accept condition Y? The exceptions of the sequence handler are a good example, they tell you which actor is messed up, and which frames.

**Comment by abcdefg30** [comment]
ConditionManager was removed, and I'm not sure what the specific issue here is (we do have linting for conditions).
