### ISSUE TITLE
Lua scripting: Hunt activity cancels itself

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13560]
I've been trying to fix Hunt activity which is broken (reuse of "this" and doesn't update targets). No matter what I do, I can't fix it. Here's why:

a.Hunt() is supposed to make the actor hunt down everything until all the enemy units die or itself dies. However, attackMove activity underlying Hunt cancels the Hunt activity.

In attackbase.cs:
public void AttackTarget(Target target, bool queued, bool allowMove, bool forceAttack = false)
This is called as a non-queued move so 

			if (!queued)
				self.CancelActivity();

This code cancels the hunt code.

I can't make Hunt attack individual targets one by one because there's no such thing as an Attack activity. Attack.cs exists but the activity is only for AttackFrontal and not to be used directly. Another problem is, when queueing attack activities by calling GetAttackActivities, what if the unit has multiple attack bases?

**Comment by abcdefg30** [comment]
In scripts we work around this by letting the actor hunt when it is idling, so maybe this is even expected behavior, although it looks suspicious to me.

**Comment by GraionDilach** [comment]
See also the discussion in #13018 (which was closed prematurely).

**Comment by forcecore** [comment]
#13018 is back and in top priority milestone, closing
