### ISSUE TITLE
[TS]Tiberian Fiend did not attack player unit.

### ISSUE THREAD

**Issue by carlos444** [OpenRA/OpenRA#13565]
Build on 20170629 bleed branch.
![tiberian fiend](https://user-images.githubusercontent.com/2613235/27694580-0c1be844-5d1f-11e7-8573-adf5ffa792b5.png)
Tiberian Fiend did not attack player unit. I don't know if it is normal.

**Comment by reaperrr** [comment]
Which map?

**Comment by carlos444** [comment]
did not remember which map...

**Comment by ltem** [comment]
The image is from the bottom left corner of the map `Tiberium Garden Redux` .

**Comment by carlos444** [comment]
@ltem right, at the A position of the map.

**Comment by GraionDilach** [comment]
The TibFiend is an infantry. I suspect #5841 - I see a lot of similar moments with my own melee weapons since WDist rescale.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/13924 was easy to fix, but hard to spot.

**Comment by GraionDilach** [comment]
This ticket predates the target priorities though IIRC, albeit #5841 is fixed since as well, so that PR will probably indeed resolves the issue.
