### ISSUE TITLE
minor perf improvement, no ToArray() in Select()->ToArray()->Select()

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#13575]
In at least the below places in the code the expensive ToArray method is called inbetween two Enumerable Select calls. They are not needed/overhead? You could have 2 Selects in a row or combine all in one Select?

Performance impact is minor, but the amount of these statements may grow as code is copied.

```bash
 find . -type f -name "*cs"  -exec  grep -H -i "ToArray().Sel" {} \; | grep -v electable
./OpenRA.Mods.Common/Traits/Air/Aircraft.cs:                    speedModifiers = self.TraitsImplementing<ISpeedModifier>().ToArray().Select(sm => sm.GetSpeedModifier());
./OpenRA.Mods.Common/Traits/Armament.cs:                        rangeModifiers = self.TraitsImplementing<IRangeModifier>().ToArray().Select(m => m.GetRangeModifier());
./OpenRA.Mods.Common/Traits/Armament.cs:                        reloadModifiers = self.TraitsImplementing<IReloadModifier>().ToArray().Select(m => m.GetReloadModifier());
./OpenRA.Mods.Common/Traits/Armament.cs:                        damageModifiers = self.TraitsImplementing<IFirepowerModifier>().ToArray().Select(m => m.GetFirepowerModifier());
./OpenRA.Mods.Common/Traits/Armament.cs:                        inaccuracyModifiers = self.TraitsImplementing<IInaccuracyModifier>().ToArray().Select(m => m.GetInaccuracyModifier());
./OpenRA.Mods.Common/Traits/Mobile.cs:                  speedModifiers = Exts.Lazy(() => self.TraitsImplementing<ISpeedModifier>().ToArray().Select(x => x.GetSpeedModifier()));

```

Also in Armament.cs the modifiers are stored are private enumerations and each time they are used inside the class the ToArray() method is called on the enumerations. Better to to store the enumerations are array to begin with.

In general arrays are faster than Enumerations, yet Enumeration.ToArray() is expensive.

**Comment by pchote** [comment]
In Armament the modifiers are dynamic, so the values themselves can't be cached.

**Comment by RoosterDragon** [comment]
`self.TraitsImplementing<ISpeedModifier>().Select(sm => sm.GetSpeedModifier()).ToArray();`

This would only capture the speed modifiers the first time it is called. The speed modifiers change over time though, which means caching their initial values is no good to us. So we can't use this version.

`self.TraitsImplementing<ISpeedModifier>().Select(sm => sm.GetSpeedModifier());`

This would work. Every time it is called it would do the trait lookup and then give us the latest speed modifiers. We can make it more efficient though.

`self.TraitsImplementing<ISpeedModifier>().ToArray().Select(sm => sm.GetSpeedModifier());`

In OpenRA, after an actor is created, the traits on it are fixed and can never change (i.e. self.TraitsImplementing<T>() would always returns the same list of traits) Therefore it is safe for us to cache the trait lookup by using `ToArray`.

Every time this is evaluated, it gives us the latest speed modifiers but there is no trait lookup.

Let me know if I've explained that well enough.

**Comment by anvilvapre** [comment]
I understand the first and second - the need to each time call GetSpeedModifiers() on the trait, why they will only do it once. 

I guess my assumption on the order of execution is wrong. It seems the class variables store the result of the last Select as an WhereSelectArrayIterator. Which each time get enumerated over when calling ToArray() causing GetModifiers to get called each time. I thought the results of the last select were stored. 

Still the ToArray() seems 'unnatural' to me, but I guess i need to see it as a terminator of the previous stream.

Need to wrap my head around Linq/streams. 

Thanks.
