### ISSUE TITLE
Bridge gets bounty if it destroys units by repair

### ISSUE THREAD

**Issue by airetaM** [OpenRA/OpenRA#13572]
![bountybug](https://user-images.githubusercontent.com/14834585/27745355-4bae5bbe-5dc3-11e7-9b89-7d2191001265.png)

**Comment by jaZzKCS** [comment]
Gotta say, this is a weird one.

**Comment by GraionDilach** [comment]
Bounty doesn't filter via damagetypes in RA and bridge repair doesn't have any damagetypes either so yeah, that's expected.

Adding a damagetype for Bounty on all warheads however will regress bounty given on crushing because crushing also lacks damagetypes.

**Comment by airetaM** [comment]
Same with units on the bridge if tanya destroys it.
![bountybug2](https://user-images.githubusercontent.com/14834585/27810038-e9cef68e-6055-11e7-82d7-71b7f68bef7e.png)

**Comment by dsimmons87** [comment]
Should the bounty go to the player repairing or destroying the bridge?

**Comment by abcdefg30** [comment]
> Should the bounty go to the player repairing or destroying the bridge?

Imho yes.

**Comment by PunkPun** [comment]
Can't reproduce this on bleed
