### ISSUE TITLE
aboveShroudEffects Select as operator

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#13581]
The below Select shows up as one (2nd worst) of the most heavy Linq queries in the game - after initialization. 

I must be caused by the ```as``` operator - which i guess needs to do type lookups.

Perhaps you could store the different type of effects in different containers. I understand there are many type of effects. Not sure what the best solution is.

```c#
WorldRenderer.cs

WordlRenderer.Draw()
{
     var aboveShroudEffects = World.Effects.Select(e => e as IEffectAboveShroud)
                                .Where(e => e != null)
                                .SelectMany(e => e.RenderAboveShroud(this));

}

```

Called 173 thousand times. 170 msec total spent in 15min game. Avg  response time 0.00097 msec.

Of all time spent in all Linq calls, 12% of the time is spent in this Select call.

I.e. the other Selects in the same Draw method are less heavy.

**Comment by anvilvapre** [comment]
I read the implementation of Select, it ofcourse only creates an Iterator. So rather I should measure the time in the iterator or function call passed to the select. Strange however that some Select calls are more heavy then others.

**Comment by MunWolf** [comment]
Just some information even though the issue has been closed, I would guess none of the linq here was expensive, it would most likely be the call to e.RenderAboveShroud(this).
