### ISSUE TITLE
Make engineer fix power-down from infiltration

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#13595]
followup from #13588 and http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=20186

```
once you are under a power-outage (and the powerplants are black) ... engineers can enter these powerplants and fix that problem immediately ?

so when youre having a engineer ready in your base, ready near a powerplant (which is mostly a costly risk) ... you would benefit ?

and it would be a 500 - 500 trade ... thats the cost for a spy and an engi (except for the british one of course)

this would give the spys an excellent reason to use their silent--pp before entering a powerplant
```

**Comment by Elizadmin** [comment]
Interesting idea.
Spies would finally have a _counter_-unit, better than "watch your base every ten seconds" or "have dozens of dogs everywhere", and they would still be able to do their job.
They could also shot down the engineer, if he is there, right before entering the power plant.

**Comment by Micr0Bit** [comment]
well ... a "counter" for the power-down ... not more

**Comment by Comanche93** [comment]
So you have to perform amazing micro-management with spy to take him to powerplant just to be countermeasured by some engineer after 5-10 seconds?
IMO its gonna make spies underpowered and more useless...

**Comment by FRenzy-OpenRA** [comment]
Depends how many spies are sent into base, and how many engies are waiting

**Comment by Micr0Bit** [comment]
>Depends how many spies are sent into base, and how many engies are waiting

exactly ... it doesnt make spies "underpowered" ... the spy is way over the top for a single special-unit if anything  ... and it wont hurt to give other factions a bit of a counter against atleast one action that he can perform , even more so when it makes sense and helps to give anther unit a bit more usefullness

**Comment by abcdefg30** [comment]
Balancing has changed a lot since 2017, so closing to clean up.
