### ISSUE TITLE
Factions with no description crash the lobby

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#13599]
If a selectable faction has no description, it crashes the game with some yaddayadda exception that most modders surely won't be able to interpret.

We should either add `FieldLoader.Required` to `Faction.Description` so it throws a meaningful error (though that would cause redundancy on unselectable factions), or fix the crash and just show no description if none is defined.

**Comment by GraionDilach** [comment]
Oh yes, this made me confus during the weekend.
