### ISSUE TITLE
Where's the exception on modded maps

### ISSUE THREAD

**Issue by Flamewh33l** [OpenRA/OpenRA#13615]
when people aren't interested in making community mods or are just testing stuff out via the safety-net of mod maps, they shouldn't have to feel alienated with the fact they can't be given exception logs when their maps aren't compatible with the version of the mod they're running. if OpenRA knows what is wrong, why is it not distributing it's fine knowledge onto the person making mod maps to allow them to figure out what is wrong?

**Comment by pchote** [comment]
`debug.log`.
