### ISSUE TITLE
"Mods" menu item is missing when building from bleed

### ISSUE THREAD

**Issue by hartmark** [OpenRA/OpenRA#13617]
I have probably missed something. I tried to look around for any clues but to no avail.

When I start the game downloaded from http://www.openra.net/download/
I have a "Mods" menu item in the main menu, from there I can switch between the different game types.

But in my version I have compiled myself I must provide which gametype I want to play.
for examle "OpenRA.Game.exe Game.Mod=ra"

Failing to provide Game.Mod option the game just crashes.

And the "Mods" menu item is missing when starting RA for example.

**Comment by atlimit8** [comment]
It was replaced with system launchers after a long discussion about supporting external mods and multiple engine versions. Use `./launch-game.sh` on Linux/BSD and `launch-game` / `launch-game.cmd` on windows.

# Closed Issues
 * Improve support for features needed by external mods #11813
 * Replace ingame mod chooser with self-contained mod runtimes. #12554
 * Automatically register mod metadata during installation. #12764
 * Utility: Available mod list regression #12792
 * Opening .orarep or .oramod files opens the latest OpenRA installation. #13082
 * Game.Mod argument missing or mod could not be found.
 * OpenRA.Game.exe mod support #13369


# Merged pull requests
 * Add support for switching to mods from other engine installations. #12600
 * Add engine plumbing to support externally developed mods. #12638
 * Fix utility mod listing. #12793
 * Use external mod switching plumbing to restart after settings changes. #12795
 * Add the current mod to the external mods database on launch. #12891
 * Remove oramod and orarep file type handlers from Windows and Linux. #12909
 * Reorganize Windows game launcher to support per-mod launchers. #12966
 * Overhaul launch-game.sh #12992
 * Remove ingame mod chooser. #13049
 * Add support for using launch-game.cmd with parameters #13116
 * Update OSX packaging for per-mod launchers. #13129
 * Update Windows packaging for per-mod launchers. #13133
 * Update Linux packaging for per-mod launchers. #13138
 * Remove metadata that was only used by the mod chooser. #13172
