### ISSUE TITLE
DeliversExperience/AcceptsDeliveredExperience (Generals Pilot Logic)

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#13618]
While answering http://www.sleipnirstuff.com/forum/viewtopic.php?f=83&t=20191&start=0&postdays=0&postorder=asc&highlight= i realised Generals Pilot logic is pretty similar to what we have for Supply Trucks. Unit enters another unit, but instead of cash, it gives XP. So it sounds easy to implement to me.

I'll take a look to that when i back home this Wednesday.

**Comment by GraionDilach** [comment]
NTM: Try to file a PR to expand EjectOnDeath with the alterations I added to it's AS duplicate (and make it conditionable if it isn't) ages ago before I go to the astronomy camp.

**Comment by MustaphaTR** [comment]
Actual entering and giving levels logic is added with #13623, but what @GraionDilach said is also a part of this logic. So i'm not sure about closing this issue.

**Comment by GraionDilach** [comment]
The more ungh aspect is since the times I've added my duplicate (was in 2015 IIRC), it regressed and I only assume it was due to initial experience being shifted from constructor to Created since. One should probably create a GiveExperienceLevelInit field and pass that IMO (the current experienceinit accepts percentage values).

**Comment by MustaphaTR** [comment]
EjectOnDeath is now conditional so i'm not sure how much the changes in AS are required to do this logic. So i guess this can be closed.

**Comment by PunkPun** [comment]
> EjectOnDeath is now conditional so i'm not sure how much the changes in AS are required to do this logic. So i guess this can be closed.

closing
