### ISSUE TITLE
Modding guide does not contain the Linux path

### ISSUE THREAD

**Issue by aaronfranke** [OpenRA/OpenRA#13625]
https://github.com/OpenRA/OpenRA/wiki/Modding-Guide

"Each mod has a directory inside the mods directory in the game root. It is the name of this directory which is used when naming mods to load. Everything related to a particular mod is contained within this directory (with the possible exception of user maps, which can be loaded from other locations too.)"

Where is the `mods` directory? On Windows this is located at `C:\Program Files (x86)\OpenRA\mods` but the wiki doesn't say where it is on Linux. It doesn't appear to be in `~/.openra`.

**Comment by GSonderling** [comment]
In my build it's in `folder-where-you-put-your-games-in/OpenRA/`

**Comment by aaronfranke** [comment]
I installed OpenRA from the .deb package on Ubuntu, there is no "folder-where-I-put-the-game-in".

**Comment by aaronfranke** [comment]
Found the path, added to wiki https://github.com/OpenRA/OpenRA/wiki/Modding-Guide/_compare/fa2c3b324e54704fca1f907b12d02545fb989ef8...8edd800a8af6df2077911cd2764cb627e5c078f9 and closing bug.

**Comment by aaronfranke** [comment]
Just FYI, this information is no longer present in the wiki page. https://github.com/OpenRA/OpenRA/wiki/Modding-Guide Although I won't re-open this issue since the change seems to be on purpose.
