### ISSUE TITLE
Let the user define what "rules.yaml" he wants in lobby

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#13629]
it would be nice to let the user define what "rules.yaml" he want from a list of "rules.yaml" shipped with a map, that will allow him to pick completely different types of gameplay on same map. something like a drop down menu with a list of rules added by the map author on the map.

**Comment by Mailaender** [comment]
Duplicate of https://github.com/OpenRA/OpenRA/issues/9422?

**Comment by KOYK** [comment]
@Mailaender i don't think this is actually a duplicate, i am thinking about a single drop down menu not multiple checkboxes. Also not a mutator list, more like a simple "rules.yaml" change on the fly thingy. It seams more easy considering only adding an extra drop-down menu. 
This is how **i see it**, I am not the expert here, just saying.

**Comment by Smittytron** [comment]
Reverse duplicate of #14325. Closing as that ticket has more information.

**Comment by KOYK** [comment]
I am opposed on closing this, since the other issue has unrealistic goals with the current work-flow of openra.
