### ISSUE TITLE
Walls (LineBuild) show buildable building overlay for unbuildable terrain in adjacent range

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#13632]
I was testing stuff for my code about #10550 and noticed that on D2K, first thought it was something with my code, but it happens on bleed too. It just shows wrong overlay, clicking there still gives "Cannot Build Here" notification as should be. ~I only tested on D2K, but other mods should be effected too~. Edit: Yes happens on RA too. It shows unbuildable overlay as it should be for furter places from its `Adjacent:`

Not sure when this regressed, but #13025 is best candidate i can see.

Edit: Image
![adsiz](https://user-images.githubusercontent.com/7933210/28182361-408e554c-680c-11e7-87d5-6a2959077770.png)

**Comment by pchote** [comment]
I have a fix for this, so adding to the milestone.
