### ISSUE TITLE
Fire Weapon Based on the number of units in targeted affected cell

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#13647]
so you have a unit with 2 weapons, a grenade and a rifle, the grenade can do splash damage,so the unit will fire the grenade weapon to hit more targets\units in the same cell or cells(in case of an artillery type unit)  instead of using the rifle to hit 1 target\unit.

**Comment by GraionDilach** [comment]
You can do a ProximityExternalCondition to grant conditions on actors which could switch between targettypes.

**Comment by KOYK** [comment]
what if they are all the same target type and you have 5 units on the same cell,would that make the attacking unit use a weapon based on the number of the units on that cell?

**Comment by GraionDilach** [comment]
Actors can have multiple targettypes and multiple Targetable traits, so adding a few instances of Targetable just for units which would utilize this setup is completely sound. If you're a good modder, you will realize that the above what I wrote is how you set up this feature - the engine is already capable of doing this feature.

**Comment by KOYK** [comment]
So from what i understand lets say we have X number of units of type A, with a range of X between them, add a "tag" to them, and if unit type B is on specified range with them, then use "secondary" weapon for example? 

but if that is correct how will you prevent the B unit from attacking a more near unit of a different target type with the same weapon? that sounds a bit of colossal type of work. like add target types on any actor of the game i am correct? 

p.s. i haven't fully understand the Condition traits to be honest

**Comment by GraionDilach** [comment]
@pchote I looked at the logs - please leave a note regardless if I should try carry over my Generals-Horde imitation implementation though.
