### ISSUE TITLE
Have a "Load Map" option in the Map Editor-menu

### ISSUE THREAD

**Issue by noobmapmaker** [OpenRA/OpenRA#13649]
Currently when you´re editing a map in the Map Editor and you'd like to open a different map, you have to go back exit the map editor first. You then arrive in the main menu and have to go to map editor again and load a map.

I think it's usefull when Im in the map editor and press menu or [Esc] to also have a "Load Map" option (between the "Save Map" and the "Exit Map Editor" option?).

**Comment by Smittytron** [comment]
Duplicate of #10136
