### ISSUE TITLE
[bleed branch][RA]mission 05a:Tanya's tale, Mammoth Tank didn't fight and move

### ISSUE THREAD

**Issue by carlos444** [OpenRA/OpenRA#13657]
Build on 20170718, debian 8.8 i386. another AI bug？
![- 2017 07 18 - 23 07 25](https://user-images.githubusercontent.com/2613235/28325068-8361b650-6c0f-11e7-9f08-a8505b84309a.png)

**Comment by abcdefg30** [comment]
Couldn't reproduce. Can you report back if you know how to trigger this bug?
