### ISSUE TITLE
Add Documentation On How To Use Conditions

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#13658]
We need an extensive tutorial on Conditions for average joes like me, in my case Conditions are really untouchable to the point of being useless for me. 

As the wise man said:
Give a man a fish, and you feed him for a day. Teach a man to fish, and you feed him for a lifetime.

**Comment by MunWolf** [comment]
This should probably be possible now as the condition framework itself is pretty stable atm, the only big change coming to the condition system would be IntegerExpressions if they decide to add them.

**Comment by yaaaaa** [comment]
good idea

**Comment by GraionDilach** [comment]
IntegerExpressions are already included. PausableConditions is the next leap - framework is in, but most traits haven't been shifted to be pausable iirc.

Conditions are simple, okay, you do need a sense of binary logic to understand them though, but I believe if you can't figure that out on your own via experimenting and comprehending the already-included setups (which there are quite a lot of in the TS mod already), you lack the brainpower to even mod efficiently and you'll be unable to reach your aims anyway. In which case you shouldn't even mod.

**Comment by MunWolf** [comment]
@GraionDilach Everything is simple when you understand it.
It is hard to learn when there is no documentation about a topic and you have to go digging to find the relevant information.
Sure programmers live and breathe with figuring stuff out but not everyone is a veteran programmer and even we tend to like our documentation ;).

**Comment by KOYK** [comment]
Closing this since @abcdefg30 made a guide on conditions here https://github.com/OpenRA/OpenRA/wiki/Conditions :+1:  with minor fixes by @Mailaender
