### ISSUE TITLE
Setting to disable the command bar (visually)

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#13676]
As requested on Discord. Imho that makes sense, as it "clutters" the screen for experienced players who only use the hotkeys anyway.

**Comment by pchote** [comment]
Hotkeys are now wired through the command bar, so outright hiding it would also disable those.

**Comment by pchote** [comment]
I'd like to propose that we WONTFIX this.  IMO the request to be able to hide it is simply a knee-jerk reaction to change which will go away/be reduced once players have time to get used to it.

We don't offer a way to hide the sidebar (while keeping the game playable), so I don't think that the command bar deserves special treatment.

**Comment by Micr0Bit** [comment]
>I'd like to propose that we WONTFIX this. IMO the request to be able to hide it is simply a knee-jerk reaction to change which will go away/be reduced once players have time to get used to it.

We don't offer a way to hide the sidebar (while keeping the game playable), so I don't think that the command bar deserves special treatment.

i agree

**Comment by abcdefg30** [comment]
Yes, we already agreed on IRC about closing this the day it was opened. I simply forgot to do it, sorry. ^^
