### ISSUE TITLE
Counterstrike and Aftermath not imported from The First Decade DVD

### ISSUE THREAD

**Issue by JoshuaPettus** [OpenRA/OpenRA#13678]
Is there a reason for this?

**Comment by pchote** [comment]
The reason we don't import the Counterstrike and Aftermath music from the TFD DVD is that it isn't there!  EA forgot about / accidentally deleted these when they assembled the collection.

There's nothing we can do here, but thanks for the report!

**Comment by JoshuaPettus** [comment]
Wasn't it included in the 1.02 patch?  Anyway we can get it from there as part of a download?
