### ISSUE TITLE
Make tutorial maps for new players

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#13671]
New players often get confused about what is happening in the battlefield, and old players that have little or no tolerance left will 70% get mad at them, because some things like kill an enemy engineer that is capturing your construction yard is just too obvious for them, but not for a new player.

Also new players might get frustrated by the RTS idea, examples will be: like "what to do with the car in the start" and "ore? tiberium??? whats all this?" ect.

I strongly believe that in order to keep new players in the game we will need a 4 stage tutorial.

Stage 1:  map 1
Fundamentals of rts gaming, what is a base building, why we need units, how the resource management works, or even how we win the game.

Stage 2: map 1
Learn how to build and what to build, read the descriptions of each unit and building, use of super weapons, gather this amount of resources, use of the radar, complete minor objectives, expand your base, learn the usage of some units and buildings and how to use them when its needed, ect.

Stage 3: map 2
Use what you learn vs Bot, allow the player to recover via scripts (money gift, reinforcements, ect) 
guide him to use advance tactics like use of artillery type units with a combination of air units,  use iron curtain with shock troopers, use chrono on tanks vs the enemy base and mechanics to repair them after they return back, help your AI ally with defenses and money trucks and repair his buildings.

Stage 4: map 2
Multiplayer interaction, beacons, chat short messages (cap=capture, AA=build allied anti air defense here), assist other players, sent money, plan ahead with your ally, be aware of notifications on mini map, combine your forces with your ally forces, be aggressive (don't fear that your enemy has 10 tesla coils on his base, go get that oil derrick that is way far from your base).

Also using a voice tutorial will assist on keeping the player interested on staying, 
objectives could be announced once with a voice notification and continue to notify the player with text notifications at repeated rates.

Providing the player with the link of https://github.com/OpenRA/OpenRA/wiki/Playing-the-game at the end of each tutorial will also be a good idea.

**Comment by MunWolf** [comment]
Adding support for displaying messages with Lua and probably run some sound clip would be nice and could even be used for custom missions in the future.

**Comment by Micr0Bit** [comment]
i would say an extra-button "Tutorial" under "Singleplayer" would be nice for that ...

**Comment by airetaM** [comment]
I am thinking about such a map quite a while, because of no time and other maps didnt start this,
Would be nice to have more of these actor tiles then you could create own maps for the zenes.
Not so hard to do this with lua.

**Comment by dragunoff** [comment]
A duplicate of #4993 but here we have more details.

**Comment by KOYK** [comment]
It wont be fixed\added, closing it.
