### ISSUE TITLE
Makefile header still refers to `make docs` which no longer exists

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#13682]

**Comment by GSonderling** [comment]
But there is still code referencing the 'make docs' on lines 498-499:


`@echo 'to generate documentation aimed at modders, run:`

`@echo '  make docs'`

**Comment by abcdefg30** [comment]
> Should that be removed too?

Yeah, I'd say so.

**Comment by GSonderling** [comment]
Ok, just so we are clear. This is about OpenRA/Makefile itself and not about make.cmd, make.ps1 correct?

**Comment by abcdefg30** [comment]
Yes, `make.ps1` still has a `docs` command and thus doesn't have to be touched here.

**Comment by pchote** [comment]
#13697 has been merged. 

@GSonderling: FYI if you say "Fixes #13682" or "Closes #13682" in the PR description then github will automatically close the issue when the PR is merged ([github docs](https://help.github.com/articles/closing-issues-using-keywords/)).
