### ISSUE TITLE
ReturnToBase is queued TWICE in Playtest-20170722

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13685]
Unlike previous releases, if you press F,
* new IssueDeployOrder in Aircraft.cs queues ReturnToBase. (New code in Playtest)
* UnitCommandWidget.cs PerformDeploy then queues "ReturnToBase" order.

It might mess up reservation stuff. It definitely messes stuff up in my current branch where I'm unifying all the dock activities and multi-dock stuff.

**Comment by pchote** [comment]
`UnitCommandWidget` is deprecated and superceded by the command bar.  The two should not be used together!

**Comment by forcecore** [comment]
Believe it or not, it is still there in the bleed and the code still gets executed when I press F to make aircraft reload.

**Comment by pchote** [comment]
`ra`, `cnc`, and `d2k` have removed `UnitCommandBar`.  Only TS uses `UnitCommandBar`, because the command bar isn't implemented there yet.

**Comment by forcecore** [comment]
OK, thank you.
