### ISSUE TITLE
[Playtest 20170722] Auto attack issues

### ISSUE THREAD

**Issue by xp65** [OpenRA/OpenRA#13681]
The items I found to be an issue in the latest playtest:

- Auto attack, they often stop going to target, standing idle in the middle of the map, or after attacking a unit, they won't keep on going to their auto attack target, totally forgetting their mission.
- New units are always created with the default option "not attacking buildings". It would be great to also be able to set the state of the creation buildings, because I want them to attack buildings. I often forgot to change it and then they stand idle in a base and in the end the AI wins there from those troops. Same for attacking with base building, units are created but they don't attack the building next to them.
- Airplanes when you want to group them to a location, they just fly away again, not possible to keep a large group of airlpanes grouped on a location anymore.
- Airplanes when auto attack just fly sometimes home with still ammo available (A new panic feature where they run from war ? ;-)  )
- Airplanes with auto attack often circle with lots of attack targets, but not picking one, or they picked one but unable to reach it in their current circle and they keep circling it.

**Comment by Elizadmin** [comment]
- Giving attack-move orders to planes make them crazy or send them at random locations. I gave an attack-move order to a Mig, he left its airfield at the very left of the map, attacked the building at the very right of the map one time before going straight to the very top of the map on its own, coming back to the center of the map, doing one circle and coming back to its airfield. 😕
- Units could have the Attack anything stance by default so we could continue to adjust stances for special situations like we did until now.

**Comment by WhoCaresora** [comment]
Other suggestion i wanted to ask

Could the units with a “turrets weapons” could automaticly adquier target in range and fire in simple move command respecting the stance they are in :

Current mechanic : 

Move command :

Tank move from A to B and doesn't fire at anything until reaching its destination

Amove command : 

Tank move from A to B and will STOP and engage any enemy (or building according his stance)


I wanted to know if the MOVE command could allow the tank to target and fire at the closest enemy in range while it is passing by, So it does'nt stop, it proceed to his waypoint but use his fire power to inflict damage at anything crossing his path. And to be complete, respecting the stance :

Move in hold fire : like the current behavious, move A to B and does'nt shoot
Move in return fire : Move A to B, return fire in case of attacked but does'nt stop or break the move to B
Move in defence : Move A to B, fire at any unit/defence building in range (alwais targeting the closest so when a unit is out of range the tank doesn't get “focused/frozen” on it and starts firing at the next closest target) but does'nt break the move to B
Move in attack anything : Move A to B firing at anyhing in range, but does'nt stop or break the move to B

I beleive that could bring the buff vehicules need to compete vs infantry blob and for once take adavantage of their mobility. From this, you could circle around a stationary force and your tanks would move and harrass at the same time without a intense (and delayed by the latence) micro work.

**Comment by pchote** [comment]
@xp65, @Elizadmin: Could you please post some replays + timestamps to see some of these issues?

**Comment by xp65** [comment]
@pchote  Certainly, later tonight I'll be able to provide it.

**Comment by xp65** [comment]
The bug of the aircraft is as #13703 decribes in the youtube.  
I think you guys already are on this issue why it goes back to base everytime.

I modified a map to see the outer limits of the Attack-A command, to make sure it's more often not working, where it works on the current release:
http://resource.openra.net/maps/22281/

The replay:
[OpenRA-2017-07-21T193143Z.zip](https://github.com/OpenRA/OpenRA/files/1170872/OpenRA-2017-07-21T193143Z.zip)

A warning, this map only works on very fast computers... 

But a new problem, I can't show the problem..., somehow my replay freezes at 2 minutes 22 seconds.

![image](https://user-images.githubusercontent.com/6690499/28539661-ca94559e-70b2-11e7-9278-cc591a450bdd.png)

**Comment by forcecore** [comment]
Oh yes, in Kane's wrath, you could set attack stance on the production building and the units followed the producer's stance.

**Comment by pchote** [comment]
Thanks for the reports here, but it is going to be hard to track these going forward: some of the issues reported have been fixed in the new playtest (e.g. the aircraft issues) and others are duplicates of other issues.  Can you please file new tickets (one per issue) for anything that isn't already covered or fixed?

**Comment by xp65** [comment]
@pchote Thanks, I'll certainly test it soon. Will there be a new playtest/release candidate first? as I don't have visual studio and the source installed right now.

**Comment by xp65** [comment]
Never mind :) already found it: https://github.com/OpenRA/OpenRA/releases
