### ISSUE TITLE
Building Footprint still bugged

### ISSUE THREAD

**Issue by CombinE88** [OpenRA/OpenRA#13694]
When a building spawns another building via trait/code whatsoever
the Footprint gets messed up and "=" footrint completly ignored.

**Comment by abcdefg30** [comment]
This can be easily reproduced by adding
```
	SpawnActorOnDeath:
		Probability: 100
		Actor: NUK2
```
to `NUKE` in Tiberian Dawn, destroying it and then trying to build something on the bib.

**Comment by abcdefg30** [comment]
Ok, so the problem here seem to be that the old building's influence is only removed after the new building was added to the world (which causes no influence to be added as the old building still blocks it).

**Comment by pchote** [comment]
I think it's reasonable to bump this onto the milestone so that we can mark a giant FINISHED label next to our footprint code.

**Comment by CombinE88** [comment]
Abcdefg30 mentioned it could have something to do with the footprint occupy, the new actor checks if space is free, but it isn't free the old footprint still there waiting to get deleted with last stuff in the same tick. And "=" somehow checks if it's free and doesn't apply when it's occupied by "x". 
Tl:Dr footprint checks and creates before old gets deleted, but old isn't deleted so it won't create.

**Comment by reaperrr** [comment]
Haven't checked, but my guess would be that using INotifyKilled to remove occupancy as soon as the actor is killed should probably work.
