### ISSUE TITLE
Something has broken touchscreen drag playtest 20170722

### ISSUE THREAD

**Issue by louisvarley** [OpenRA/OpenRA#13702]
i play openra on the train to work daily. up until the latest play test i could move the screen around easily by dragging my fingers to the sides of the screen. 

in the latests play test this seems to no longer work. has something changed with the code which moves the mouse around.. 

https://youtu.be/ngtvHfiz-co (working)
https://youtu.be/VZlMuNCzPd8 (not working)

im aware touch screen has never been offically supported but this does rule me and any other players using windows 10 tablets out from upgrading further than the current release.

**Comment by louisvarley** [comment]
https://youtu.be/ngtvHfiz-co (working)
https://youtu.be/VZlMuNCzPd8 (not working)

im aware touch screen has never been offically supported but this does rule me and any other players using windows 10 tablets out from upgrading further than the current release.

**Comment by louisvarley** [comment]
i did a bit of further testing today. it seems scrolling is possible but you have to really carefully drag the unit selection where as before you copd also throw it to the side of the window. ive tried changing all the settings and none make a difference. it may be that the ara the screen begins to scrol has moved further out where i cant get the mouse using touch. happy to run any tests required by devs. i can totally easily play full games  even online games on previous release without any major handicap (minus keyboard shortcuts. so command bar is great for me) . with this playtest play is impossible

**Comment by pchote** [comment]
The edge-scroll trigger area was reduced from 15 pixels to 5 pixels around the edge of the screen to stop it from triggering when people move their cursor down to use the control bar.

**Comment by louisvarley** [comment]
Would there be a chance for some way of toggling this as this would seem to be the cause the issue on touch screens. Shame as command bar is perfect for me. I play 80% of the time on touch screen as I am away from home on business.

**Comment by pchote** [comment]
It would be easy to add a hidden preference to settings.yaml that you could set with a text editor to define a custom scroll margin.  Would that be suitable?

**Comment by louisvarley** [comment]
Yes very much so. I would go crazy if I can't keep up with the latest releases and gives all touchscreen users an option.

**Comment by pchote** [comment]
@louisvarley: In the next playtest you will be able to add `ViewportEdgeScrollMargin: 15` to the `Game:` section in Documents\OpenRA\settings.yaml to restore the earlier behaviour.

**Comment by louisvarley** [comment]
Fab. Thanks guys. 


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Paul Chote <notifications@github.com> Date: 10/08/2017  11:54  (GMT+00:00) To: OpenRA/OpenRA <OpenRA@noreply.github.com> Cc: louisvarley <louisvarley@googlemail.com>, Mention <mention@noreply.github.com> Subject: Re: [OpenRA/OpenRA] Something has broken touchscreen drag playtest 20170722 (#13702) 
@louisvarley: In the next playtest you will be able to add ViewportEdgeScrollMargin: 15 to the Game: section in Documents\OpenRA\settings.yaml to restore the earlier behaviour.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OpenRA/OpenRA","title":"OpenRA/OpenRA","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OpenRA/OpenRA"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pchote in #13702: @louisvarley: In the next playtest you will be able to add `ViewportEdgeScrollMargin: 15` to the `Game:` section in Documents\\OpenRA\\settings.yaml to restore the earlier behaviour."}],"action":{"name":"View Issue","url":"https://github.com/OpenRA/OpenRA/issues/13702#issuecomment-321519047"}}}
