### ISSUE TITLE
(Playtest-20170722) [Attack-]move orders outside the map

### ISSUE THREAD

**Issue by Elizadmin** [OpenRA/OpenRA#13707]
You can now ask units to go outside the map with [attack-]move orders.
(In the previous versions units were going to the limit of the map if a path was available)
- It's a bit illogical
- Units simply stop moving because they can't find any path
- You can't anymore send a scout to discover the bounds of a map
- Beware of misclicks

On the following screenshots I click outside the top left corner of the map.

__Playtest-20170722__

![openra-2017-07-23t143807347z](https://user-images.githubusercontent.com/25843400/28500272-78b0c9bc-6fc5-11e7-9575-daae4056a524.png)

__Release-20170527__

![openra-2017-07-23t144235772z](https://user-images.githubusercontent.com/25843400/28500298-0a568b68-6fc6-11e7-8ef9-c4663ce9c083.png)

**Comment by rob-v** [comment]
note: Move, Force Move (Alt), Force Attack (Ctrl) work in release as described, but Attack Move (A) does nothing, units don't move also in release.
