### ISSUE TITLE
Queuing Amoves

### ISSUE THREAD

**Issue by WhoCaresora** [OpenRA/OpenRA#13708]
I have been playing since februrary this years and i never been able to queue amove orders.

I mean i would love to use the shift key (or now the hud) to queue some amove allowing my units to follow a multiple waypoint trajectory and staying in attackmove and engaging enemy at any moment.

That would allows to do manual effective/offensive patrols as well, right know i can just make in patrol a unit that will just look enemy units pass by minding its own bizness.

I wanted to know if it's intended that way or a feature to come or a bug. (ultimate case, maybe i did thing wrong and just could't do it)

**Comment by pchote** [comment]
It's a bug, but I don't think anybody had reported it before.  I filed #13709 to fix this.

**Comment by WhoCaresora** [comment]
sry to bother again, it has been reported that people would like to be able to queue a deploy order wich apprently doesn't work either:

**Comment by Micr0Bit** [comment]
this could have been a ticket a year ago ... solved in 2 days 

http://logs.openra.net/?year=2016&month=02&day=10#12:14:57

**Comment by WhoCaresora** [comment]
I have read the log about it.

Can I ask why you diden't solve it a year ago ? You had the full conversation with all the pertinent view and argument "half baked feature". Just out of curiosity.

**Comment by Micr0Bit** [comment]
@WhoCaresora : pchote was afk or missed the conversation, and i didnt create a ticket (probably because i thought it already has been made or it would be low-priority anyway ... or ..  its not a bug but maybe "not wanted" or "too complicated"
