### ISSUE TITLE
[RA - Playtest] SAM ought to have a single hitpoint.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#13713]
As the only heavy armor structure affected by the new hitshapes it ought to retain a single target point. Rebalancing AoE damage output vs heavy armor isn't happening.

![openra 2017-07-24 16-06-00-05](https://user-images.githubusercontent.com/2715583/28527240-3a128b62-708a-11e7-8023-de33288b8b8b.png)

Might also be solved through #13675

**Comment by reaperrr** [comment]
Disabling the two outer target points is the way to go, I think.
In that case it might make sense to reduce the horizontal hitshape width to match the sprite width as well.

**Comment by pchote** [comment]
Reducing the hit shape size to 1 cell would be an easy fix.
