### ISSUE TITLE
Interface locked

### ISSUE THREAD

**Issue by CombinE88** [OpenRA/OpenRA#13727]
When scrolling with middle mousebutton pressed, the interface (not Ui) sometimes (very often) locks itself. Cann neither click nor select something or place a building, nothing is possible.
Im able to unlock while giving the middle mosubutten a single press again.

**Comment by ltem** [comment]
I had this issue as well but it happens randomly or at least I cannot reliable reproduce it. I'll play around, maybe I find a way how to create it.

**Comment by CombinE88** [comment]
i have seen othe rpalyer strugle with that issue

**Comment by reaperrr** [comment]
Most likely caused by either #13310 or #13115.

**Comment by rob-v** [comment]
@CombinE88 Please paste here your Settings-Input. It isn't clear to me what 'interface locks' exactly means.

**Comment by CombinE88** [comment]
Wich settings you mean exactly? 

It means that you won't be able to interact with the map anymore. 

Well happens wehen you scroll the map with mouse wheel pressed

**Comment by rob-v** [comment]
These settings. The issue can happen only for some combination, I would like to reproduce that problem.

![image](https://user-images.githubusercontent.com/16348750/28812390-d0e7eb3a-7694-11e7-9fa1-9acf72f22d9e.png)

**Comment by ltem** [comment]
I send you mine as well.

![ettings](https://user-images.githubusercontent.com/20945684/28812493-3ab6da44-7695-11e7-83db-36a5b6678ede.png)

<details>
<summary>Display Settings</summary>

![display](https://user-images.githubusercontent.com/20945684/28812559-8a57d792-7695-11e7-8120-61dabcff779f.png)

</details>

**Comment by rob-v** [comment]
Thanks @ltem . I expected some special combination, this one is standard (for me, I have also 'Edge Scrolling' disabled).
How to reproduce: with MMB pressed, move to Minimap, release MMB, return back to map.

@pchote Please check your change here: https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Widgets/ViewportControllerWidget.cs#L306
Either it should be reverted/fixed or isStandardScrolling has to be reset to false in some place.

**Comment by CombinE88** [comment]
I figured out when this happens:
when u scroll using middle mouse button, and the cursor (while scrolling) comes above the icon panel, your whole screen gets locked until u press the middle mouse button again.

**Comment by pchote** [comment]
If this is a regression from one of the issues @reaperrr mentions then this should be tagged as such and added to the release milestone.
