### ISSUE TITLE
Unit targeting stutter step.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#13722]
Essentially the units (All units from what I saw) do a stutter step move when targeting units on the move. Tanks are the strangest as they turn their chassies then stop again then move once more. However, if the unit stands still they move to attack the unit just fine.

You can see this happening when you target a unit and have it run circles around the map.

**Comment by pchote** [comment]
I suspect that this and #13710 are both introduced by #13528, which means that the before-pathfinding delay is now applying in cases where it previously was skipped.

**Comment by Smittytron** [comment]
Possibly related, but I'm feeling like rocket soldiers are having a much harder time engaging aircraft in a timely manner.
