### ISSUE TITLE
Stavros / gnrl unit has incorrect/weird sequences

### ISSUE THREAD

**Issue by Inqubi** [OpenRA/OpenRA#13724]
This **gnrl:** unit (or Stavros) is useful for campaign missions & 3rd party mods.
In the current release version. The (unused?) gnrl or Stavros unit has incorrect sequence settings.

### **Current Release:**
	
`run:`
`		Start: 8`
`		Length: 5`
`		Facings: 8`
`		Tick: 80`

### **Fixed:**
`run:`
`		Start: 8`
`		Length: 6`
`		Facings: 8`
`		Tick: 100`

Another issues is he looks like he is having a seizure when shooting at a target & also taking incoming fire.

### **Current Release:**
`prone-stand:`
`		Start: 88`
`		Stride: 2`
`		Facings: 8`
`	prone-run:`
`		Start: 104`
`		Length: 4`
`		Facings: 8`

### **Suggested Fix:**
`prone-stand:`
`		Start: 104`
`		Stride: 4`
`		Facings: 8`
`	prone-run:`
`		Start: 104`
`		Length: 4`
`		Facings: 8`
`		Tick: 100`

This may have been intentional. However with my fix he returns fire from the prone position like other infantry.

**Comment by Mailaender** [comment]
> This may have been intentional.

I don't think so. Just no one noticed as the unit is currently unused. We don't have a mission featuring him.
