### ISSUE TITLE
Crushing dosen't get vehicule veteran

### ISSUE THREAD

**Issue by WhoCaresora** [OpenRA/OpenRA#13728]
EDIT Thx to smitty comment i tested it more and my issue isen't one.

In a game i was surprised to have an apc that did for 1500$ of damage crush and weapon and diden't get vet 1. I was assuming it came from the crushes not giving kills. i realize now that i missassume the prize of the APC and it needs the double of its value to get the veterancy.

I wish i never posted that or that i can delete it.

**Comment by Smittytron** [comment]
In the playtest? Because they for sure get veterancy in the release.
