### ISSUE TITLE
Win automatically when you are the last player in the game

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#13725]
It's an __option__ request.
I played a 5v5 game where all the players in my team left after "gging" because we were overnumbered.
I was the last of my team versus 5 players so these players "gged" too and left the game.
Finally I was alone versus nobody so I had to destroy every enemy asset to get the correct/normal ending and actually __win__ that game.
With this option enabled the game could automatically give you the victory if you are the last player on the server.

**Comment by pchote** [comment]
#13284 would solve this.

**Comment by PunkPun** [comment]
closing as a reverse duplicate of #13284 and #18643
