### ISSUE TITLE
SpawnActorPower: Sound Bug

### ISSUE THREAD

**Issue by Inqubi** [OpenRA/OpenRA#13735]
When using **SpawnActorPower:** for mods etc.

On current release build, 

Both:

`LaunchSound:`  and `LaunchSpeechNotification:`

Fail to function when they are used.

`DeploySound:`  works, but this is also heard by all players. (I imagine thats intentional?)

**Comment by reaperrr** [comment]
@Inqubi could you test https://ci.appveyor.com/api/buildjobs/kmdjkly7y7m7qwru/artifacts/OpenRA-e4b4750.exe and report back if it fixes the issue for you?

**Comment by Inqubi** [comment]
Tested it, works as intended now. thanks.
