### ISSUE TITLE
Disable click sound on command bar buttons when they are activated by hotkey

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#13730]
The additional click sounds appears to be a common source of irritation on the playtest.
C&C3 avoids this problem by only playing the click sound when the button is activated using the mouse.

**Comment by Micr0Bit** [comment]
not gonna lie ... but its not a secret that the "sound" itself is pretty awful to listen at ...

**Comment by rob-v** [comment]
It could be removed globally by removing 2 lines for all buttons. If it is wanted only for some buttons like command bar buttons, #13782 adds this new property and disables sound for these buttons only.
