### ISSUE TITLE
Playtest 20170722 would not run on Win 7

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#13747]
I have installed the playtest but it crashes when I try to run any of the default mod executables. I have the current release running smoothly on the same system. Here's a copy of the message I get:

>   Problem Event Name:	APPCRASH
>   Application Name:	RedAlert.exe
>   Application Version:	0.0.0.0
>   Application Timestamp:	00000000
>   Fault Module Name:	KERNELBASE.dll
>   Fault Module Version:	6.1.7601.23807
>   Fault Module Timestamp:	5915f98e
>   Exception Code:	e0434352
>   Exception Offset:	0000c54f
>   OS Version:	6.1.7601.2.1.0.256.1
>   Locale ID:	1026
>   Additional Information 1:	0a9e
>   Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
>   Additional Information 3:	0a9e
>   Additional Information 4:	0a9e372d3b4ad19135b953a78882e789
>

**Comment by reaperrr** [comment]
Might be a similar issue to #4571.

**Comment by pchote** [comment]
Do Tiberian Dawn and Dune 2000 crash in the same way? Or just Red Alert?

**Comment by dragunoff** [comment]
The three shipping mods (RA, TD, D2k) crash in the same way.

**Comment by pchote** [comment]
Which version of the .net framework do you have installed?
https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed might be helpful.

**Comment by dragunoff** [comment]
.NET framework is at version 4.5 (Release DWORD is 378389 and Version is 4.5.50709 in the registry).

**Comment by pchote** [comment]
It is possible that one of the changes in the playtest has accidentally introduced a dependency on framework version 4.6.  Would it be possible for you to install the newer version, and see if that fixes the crashes?

**Comment by dragunoff** [comment]
Yes! Installing .NET 4.6 solved it. Now playtest and release are running side by side. I thought it might be the .NET version but I figured the game should let me know that I need a higher version. I guess other folks would also run into this issue (there is already one comment with the same error under the annoucement blog post).

**Comment by pchote** [comment]
Right.  We'll need to fix this for the next playtest then.

**Comment by rob-v** [comment]
IMO there is no new 4.6 dependency and it looks like local problem with a corrupted file/profile or sth like that. It is strange that release worked of course, but I guess reinstalling also 4.5 might solve the problem also.

**Comment by pchote** [comment]
@AoAGeneral confirmed/reproduced the problem by uninstalling .net 4.6 on windows 7 to fall back to 4.5.

**Comment by rob-v** [comment]
Yes, right, sorry, I wrongly checked .net on Win7, it was 4.7 in my test. So I can confirm the problem. I didn't find it in OpenRA so I assumed there is no new dependency. 
The reason might be that it seems it happens in WindowsLauncher, but I can't find it in main solution.

**Comment by ScottNZ** [comment]
.NET moved to a new update model in 4.5. From 4.5 it would "patch" earlier versions of .NET, so any subtle bugs or issues in the new version of .NET would affect programs targeting older versions of .NET.

**Comment by rob-v** [comment]
The problem is in WindowsLauncher. Marshal.​Size​Of - 2 overloads (of 4) - Supported in the .NET Framework 4.5.1 and later versions.

> As previously announced, starting January 12, 2016 Microsoft will no longer provide security updates, technical support or hotfixes for .NET 4, 4.5, and 4.5.1 frameworks. All other framework versions, including 3.5, 4.5.2, 4.6 and 4.6.1, will be supported for the duration of their established lifecycle.

Due to out of support I assume we can ignore this problem, users should use at least 4.5.2. This can probably happen only with turned off Windows updates and not maintained OS.

**Comment by rob-v** [comment]
My assumption: It can run in .net 4.5 with 4.5 SizeOf overload, but it is compiled in Mono using 4.5.1 overload so it doesn't run.

**Comment by JozkoMrkvicka** [comment]
After upgrade .NET framework fom 4.5 to version 4.6 or 4.7, Dune 2 and Tiberian sun works, but Red alert immediately crashes with error "BEX: StackHash_0a9e".

**Comment by rob-v** [comment]
@JozkoMrkvicka Please send us exception...log and debug.log from C:\Users\...\Documents\OpenRA\Logs (on Win).

**Comment by JozkoMrkvicka** [comment]
I have nothing to send, RedAlert.exe crashes before directory Documents\OpenRa\Logs is created.

**Comment by JozkoMrkvicka** [comment]
Now RedAlert.exe works. After clean installation, checkbox "run in compatibility with windows 95" in RedAlert icon was checked, I was uncheck this and program works.

**Comment by pchote** [comment]
@AoAGeneral: Can you please reproduce this problem with the playtest, and then see if this launcher fixes it?

https://www.dropbox.com/s/oj4x688fn2q258g/RedAlert.exe?dl=0

**Comment by AoAGeneral** [comment]
Windows crash. I reverted to 4.5 with the new client but doesn't work.

https://www.dropbox.com/s/c0aduvtjkdq5ens/Win7%20Pro%20.net%204.5%20RA%20Client%20Update.rtf?dl=0

**Comment by rob-v** [comment]
@AoAGeneral if my assumption is correct, it should work with OpenRA.Game.exe Game.Mod=ra. Could you please verify it to confirm it is launcher only issue?

**Comment by AoAGeneral** [comment]
Actually I just ran it again with 4.6.2 and the new client does a windows crash as well.

**Comment by AoAGeneral** [comment]
Just did a test. The OpenRA.Game.exe Game.Mod=ra method didn't work. What I did instead was replaced the existing client in the actual folder itself with the one pchote has. Once I did that it worked with both versions 4.5 and 4.6.2. Both versions works for accessing replays as well.
