### ISSUE TITLE
Helicopter unit's can't move in Z direction while attacking

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13748]
Cause: Only one activity runs at a time with the current code. (Although multiple children activity is possible in current system)

I have a slow moving airborne aircraft carrier. When it is produced from the airfield, it moves in Z direction, slowly rising to its cruising altitude. When it finds an attackable target while doing Z move, it will stop the Z move and attack target. It will stay below cruising height until it is told to move.

**Comment by pchote** [comment]
This is an old known limitation, which also ties in strongly with heightmap support.  The best/proper fix to this is to generalize the missile movement code so it can be shared with aircraft.

**Comment by pchote** [comment]
@reaperrr is this fixed with the current rework?

**Comment by reaperrr** [comment]
It will be, yes.

**Comment by pchote** [comment]
Moving to cruise altitude now takes priority, so fixed / no longer relevant.
