### ISSUE TITLE
Expand statistics control for spectators

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#13743]
Two small additions that looks easy to implement.
a) make statistics screen hotkey (default F1) toggle instead of just pop up statistics so that you can open/close it instead of just open.
b) add hotkeys for opening (toggling) statistics tabs directly (F2 - Economy, F3 - production, F4 - combat f.e.)

**Comment by GSonderling** [comment]
The question is if those keys `F2 - F4` aren't reserved for something else.

**Comment by rob-v** [comment]
Implemented by #13781 
The dialog is already closed by Esc what is default hotkey for this action. There is no support for 2 hotkeys for the same action and it wouldn't be standard. You can quickly open-close it by F1 + ESC.

New hotkeys F1-F4 for Basic, Economy, Production, Combat. Earned graph is by default not assigned, as F5 is already used, but you can assign your hotkey.
