### ISSUE TITLE
Investigate refactoring Aircraft

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#13746]
By either splitting it into Plane and Helicopter again, or alternatively splitting all the movement logic into separate locomotor trait(s).

In its current form, it seems `Aircraft` and its bulk of related activities is too monolithic and complicated to be properly maintainable, judging by all the issues we've had and still have.

Only sharing truly common elements and otherwise making helicopter/plane logic more clearly separated  and modular would allow for easier debugging and 3rd-party mod customization.

**Comment by pchote** [comment]
The real issue is that the work to merge Plane and Helicopter never proceeded past merging the top-level traits, the promised cleanups that would come from merging the activities never came.  That leaves us with the *worst* of both systems.

**Comment by atlimit8** [comment]
I will start with breaking `Mobile` aspects into locomotive first.

**Comment by pchote** [comment]
@reaperrr do you think this is still in-scope for Next + 1, or shall we drop this off?

**Comment by reaperrr** [comment]
Considering our review bandwidth, probably better to drop it.

I've gotten quite far on the activity front, but getting everything polished and merged will likely take time and the milestone is large enough (too large?) even without this.

**Comment by pchote** [comment]
It is probably time to rename Next + 1 to Next Release, and then push this and a few others over to that.  I'd like, ideally, to target a christmas playtest with not much more than what is already in the pull queue.

**Comment by PunkPun** [comment]
Afaik Aircraft code has been refactored by tovl. Now all aircraft have `Aircraft` trait
