### ISSUE TITLE
Missions missing

### ISSUE THREAD

**Issue by joe-death** [OpenRA/OpenRA#13741]
On both RA and TD it seems im missing several (almost half Id say) of the missions in the mission list. It also seems theres "tabs" but Im unable to click on them.

**Comment by abcdefg30** [comment]
Note that the campaigns aren't fully ported yet. See  #4988 and #4989. Also, not sure which "tabs" you are referring to. Would you mind posting a screenshot?

**Comment by joe-death** [comment]
![capture](https://user-images.githubusercontent.com/6081126/28695989-b17392f0-7300-11e7-85dd-438b56e7dd19.PNG)

**Comment by joe-death** [comment]
The tabs are the top 3 things. 

I was not aware the missions had to be ported. That may be why.

**Comment by reaperrr** [comment]
The 'tabs' are actually just categories, normally the missions should be listed unter the category they belong to.

That part seems indeed broken/missing, though.

**Comment by pchote** [comment]
@reaperrr that is a bug we've seen happen sporadically for a long time now, but so far nobody has come up with a way to reproduce it or identify specifically what is failing to break the campaign-path to map-path matching.

**Comment by reaperrr** [comment]
IIRC we merged a fix for this a couple of weeks (months?) ago, and I haven't seen the issue since. I'll risk closing it for now.
