### ISSUE TITLE
WithMakeAnimation prevents idle animation from playing

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13742]
https://github.com/OpenRA/OpenRA/pull/13737 : Found while making this PR for D2K Thumper.

The following code is supposed to show a deploy animation on deploy then stay in looping thump sequence.

	WithInfantryBody:
		RequiresCondition: undeployed
	WithSpriteBody@DEPLOYED:
		Sequence: thump
		RequiresCondition: !undeployed
	WithMakeAnimation@DEPLOYING:
		Sequence: deploy
	WithIdleOverlay@DEPLOYED:
		Sequence: thump-sand
		RequiresCondition: deployed

It doesn't work. WithMakeAnimation seems to occupy the body and thump shows only once. If I comment WithMakeAnimation out, the idle animation loops successfully.

	WithInfantryBody:
		RequiresCondition: undeployed
	WithMakeAnimation@DEPLOYING:
		Sequence: deploy
	WithSpriteBody@DEPLOYING:
		Sequence: thump
		RequiresCondition: !deployed && !undeployed
	WithSpriteBody@DEPLOYED:
		Sequence: thump
		RequiresCondition: deployed
	WithIdleOverlay@DEPLOYED:
		Sequence: thump-sand
		RequiresCondition: deployed

A walkaround is to have separate WithSpriteBody traits for deployed and deploying states.

**Comment by reaperrr** [comment]
Let's not use work-arounds, this sounds like a bug in either WMA or WithSpriteBody.PlayCustomAnimation. It should resume playing the default WSB.Sequence after the custom anim has completed, if it doesn't, that's a bug.
