### ISSUE TITLE
Add hotkeys for spectators to toggle players' vision

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#13744]
Self-explanatory. 
Now there are hotkeys for "All players" and "Disable shroud". Numeric keys could be used to switch to a specific player.

**Comment by rob-v** [comment]
Numeric keys are already used:
0 - switch between 'No Team' players so works for 1v1 without team and for players having 'No Team' in team game. It doesn't work for 1v1 when they are in Team 1 and Team 2.
1 - switch between players in Team 1
2 - switch between players in Team 2 ....

**Comment by netnazgul** [comment]
Not mentioned either ingame or in https://github.com/OpenRA/OpenRA/wiki/Hotkeys then

**Comment by abcdefg30** [comment]
Thanks for the report, [updated the wiki page](https://github.com/OpenRA/OpenRA/wiki/Hotkeys/_compare/8587c6e9e9476a119ecccf7b994e8e18b7aa75dc...53e931f3550bde31965bd7f81c6c1df5908e50f7).
