### ISSUE TITLE
Targeting issue with YAK strafing PR#13677

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#13752]
PR: #13677
When you queue up two targets with the YAK, the second target doesn't get hit correctly.
The bullets of the second strafe strike the ground behind the unit, then in front of the unit:

Start of 2nd strafe:
![1](https://user-images.githubusercontent.com/22008761/28748018-00636cf2-747b-11e7-9170-e295b8c39673.png)

End of 2nd strafe:
![2](https://user-images.githubusercontent.com/22008761/28748023-148ac720-747b-11e7-98b2-2868de5f211e.png)

**Comment by reaperrr** [comment]
Since that PR wasn't merged and put on the backburner for now, moving to future milestone.

**Comment by reaperrr** [comment]
The PR is referencing this and this issue doesn't affect bleed or any release, so closing until it actually becomes relevant.
