### ISSUE TITLE
one person start multiplayer game with two CY truck

### ISSUE THREAD

**Issue by AliT1993** [OpenRA/OpenRA#13759]
i check one multiplayer game replay and see in time 00:32 pink player (Rodrigo Vargas) get free CY truck and have 2 CY !!!
i think this player use cheat
i attach replay file here for check
[OpenRA-2017-07-27T153314Z.orarep.zip](https://github.com/OpenRA/OpenRA/files/1190962/OpenRA-2017-07-27T153314Z.orarep.zip)

**Comment by FrameLimiter** [comment]
It was a Fake Construction yard. The faction France can build fake structures.
