### ISSUE TITLE
Mammoth tank full healed in multiplayer game

### ISSUE THREAD

**Issue by AliT1993** [OpenRA/OpenRA#13750]
on playing 3v3 multiplayer game i see unbelievable thing in game! one mammoth tank full healed automatically!
i think he bring new mammtoh tank against me but after game ended i check game replay and  see that mammoth tank is really healed and dont see any crate or engineer there !!!!!!
how is this can happend ? is this a bug or cheat ?
i attach replay file here for check
it happends in : 11:20
pink team (yo) (yo) do this in center of map near his tesla coil and against me (yellow team - Blade
replay file : [FILE]
[OpenRA-2017-07-27T155929Z.orarep.zip](https://github.com/OpenRA/OpenRA/files/1184839/OpenRA-2017-07-27T155929Z.orarep.zip)

**Comment by reaperrr** [comment]
It's possible that the mammoth tank had reached elite rank.

All units that can gain experience and reach elite rank can fully heal themselves if they are not attacked in the meantime.

**Comment by pchote** [comment]
Thanks for the report!

I can confirm from the replay that this just a lucky player, not a bug.  Yo collected a crate with his MCV which granted a global heal to all of his units:

![screen shot 2017-07-29 at 11 36 30](https://user-images.githubusercontent.com/167819/28744120-4a928e12-7452-11e7-9a79-503eba6270f7.png)

**Comment by pchote** [comment]
Note: I agree that this behaviour really isn't obvious, so if others agree it would be worth opening a bug tracking adding some artwork effect over units that are healed by this global crate action.
