### ISSUE TITLE
HealthPercentageDamageWarhead in't compatible with hitshapes.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#13755]

**Comment by pchote** [comment]
Isn't compatible in what way?

If this is a real issue then it will affect the MAD Tank in RA.  That makes it a release blocker.

**Comment by GraionDilach** [comment]
It wasn't updated during https://github.com/OpenRA/OpenRA/commit/43b55ae333ac92ded26fd937f0936f81f0c7cf12.

**Comment by reaperrr** [comment]
I didn't 'update' it because it ignored shapes before as well.
I can understand that proper hit-shape handling by this warhead is a wanted feature, but the behavior on bleed shouldn't be any different from previous releases (in which case targeting Next+1 should be sufficient).

**Comment by pchote** [comment]
Ok, that makes things easy for the short term then.

**Comment by pchote** [comment]
IMO `HealthPercentageDamageWarhead` and `TargetDamageWarhead` should share the same behaviour and code aside obviously from the damage amount that is applied.  This will require changes/fixes to both warhead types.

**Comment by GraionDilach** [comment]
I can't imagine `TargetDamageWarhead` behaviour suitable with the MAD Tank. Sure you didn't mean `SpreadDamageWarhead`?

**Comment by reaperrr** [comment]
Updated #13675.

It still won't account for actual *shape* (we'd have to somehow measure distance from the warhead Spread radius/ring's closest edge position to the shapes' edge, not sure how to go about that), but it will account for trait disabled and ArmorTypes.

**Comment by pchote** [comment]
> I can't imagine `TargetDamageWarhead` behaviour suitable with the MAD Tank. Sure you didn't mean `SpreadDamageWarhead`?

I did indeed mean `TargetDamageWarhead`, and implemented this deduplication in #14991.
