### ISSUE TITLE
Can't use cheat commands in replay mode

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13761]
Recently, more cheat commands have been added for replay debugging:
https://github.com/OpenRA/OpenRA/pull/13328
https://github.com/OpenRA/OpenRA/issues/13252

However, the chat UI seems to be entirely disabled in the new Playtest:

![openra-2017-08-02t051858140z](https://user-images.githubusercontent.com/632278/28858727-43184942-7718-11e7-87e9-2aa8d84e7aa0.png)

**Comment by abcdefg30** [comment]
I think it was disabled because chatting didn't make sense as a replay viewer.

**Comment by rob-v** [comment]
See  #11743.
@pchote Do you agree to revert it? We could also enable in Replays only text starting with / (chat commands).

**Comment by pchote** [comment]
I think a better option would be to add an "Enable debug commands during replays" checkbox to the debug settings menu.  I don't agree with outright reverting #11743 because that still holds true for the vast majority of people viewing replays.

**Comment by rob-v** [comment]
Rather in Settings - Advances or in Replay browser? There is no 'Debug settings' menu in Replays.

**Comment by pchote** [comment]
The "Debug" section of the "Advanced" tab of the main settings menu.

**Comment by rob-v** [comment]
Ok, I'll add it.

**Comment by rob-v** [comment]
Fixed by #13813
