### ISSUE TITLE
Add an Issue Template

### ISSUE THREAD

**Issue by ltem** [OpenRA/OpenRA#13774]
Such a template would automatically fill the issue post with a guideline and could help to assure that certain key information are provided. It would be more prominent than the `OpenRA Contributing Guidelines`. 
A drawback could be that it would scare off people for some reason or would be too much effort for its benefits.

Github-Documentation:
https://help.github.com/articles/creating-an-issue-template-for-your-repository/

Such a template can also be added for PRs but I don't see any advantage than e.g. a reminder which issue gets fixed (`Fixes: #...`) or a motivational quote to do reviews 😄. 

<details>
<summary>Example template (not adapted to OpenRA)</summary>

[Source-SublimeTextIssues](https://github.com/SublimeTextIssues/Core/blob/master/ISSUE_TEMPLATE.md)

```markdown
When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.


When submitting a bug report, please follow the following template:

---

### Summary

...

### Expected behavior

...

### Actual behavior

...

### Steps to reproduce

1. First step
2. Second step
3. Third step

### Environment

* Operating system and version:
  * Windows ...
  * Mac OS ...
  * Linux ...
* Monitor:
  * Resolution ...
  * `dpi_scale` used in ST ...
* Sublime Text:
  * Build 3...
  * ... bit

```
</details>

**Comment by Mailaender** [comment]
Seems like a good idea. I saw it recently on a comparable game engine recreation project https://github.com/OpenRCT2/OpenRCT2/blob/develop/.github/ISSUE_TEMPLATE.md

**Comment by pchote** [comment]
:+1:

**Comment by ltem** [comment]
I made a mixup of the two mentioned already existing issue templates and I'm open for feedback.

It is quite long text but imo it covers all the important parts and it is not like the user must stick to it.

```
<!--
  This is a guideline, which shall help to write enhancement requests or bug reports.
  Check if a similar request/bug report already exists in the github issue tracker and comment there.
-->
<!--
  Fill in the placeholders below. Delete any headings and placeholders that you do not fill in.
-->

When submitting a feature or enhancement request:

1. Explain briefly what the enhancement is and why you think it would be useful.
2. Provide any other necessary or useful information regarding your issue, such as (code) examples or related links.


When submitting a bug report, please follow the following template:

### System Information
- **Operating System:** [e.g. Windows 10, Mac OS 10.12, Ubuntu 16.04, ...]
- **.NET / Mono Version:** [e.g. .net 4.5.2, Mono 3.2.8, ...]
- **OpenRA Version:** [e.g. release-20170527, playtest-20170722, ...]
- **Mod:** [e.g. Red Alert, Tiberian Dawn, ...]


### Issue Summary
<!-- Explanation of the issue. Expectation vs. actual behavior. -->
... ... ...

#### Additional Information:
- Steps to reproduce
<!-- 
1. Step
2. Step
3. Step
-->

- Logs 
<!-- If you have a log (e.g. debug.log, exception.log), zip and attach it. -->

- OpenRA Replays (When does the issue appear? [e.g. 10:33])
<!-- You have to zip it before you can attach it -->

- Screenshots & Videos
<!-- You should be able to attach screenshots by drag&drop. Videos need to be uploaded to an external platform (e.g. https://youtube.com) -->
```

The documentation mentions that the template should put into the `root`, `doc`-subfolder or `.githubg`-subfolder. Are there any preferences?

**Comment by MunWolf** [comment]
I vote root as that is where all the other information files are (AUTORS, VERSION etc)

**Comment by pchote** [comment]
My preference is the hidden .github dir -- AUTHORS and VERSION are used by the game, and CONTRIBUTING and CODE_OF_CONDUCT are useful in contexts outside of github, but the issue template really is only useful for the github web integration.
