### ISSUE TITLE
Guard/Follow waits too often for repathing

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#13784]
While reviewing #13749, I stumbled over this bug: since #13528, the repathing delay is performed by every `Move` activity, while before the delay was shared between all activities.

Since `Follow` creates a new `Move` activity every time it runs, the delays add up so that the guarding unit appears to react slowly and cannot keep up with its target.

I think other activities that make use of `Move` will be affected in similar ways, though maybe not in such a noticeable way.

The calculation of the repathing delay should probably be moved back into `Mobile`.

**Comment by pchote** [comment]
> I think other activities that make use of `Move` will be affected in similar ways, though maybe not in such a noticeable way.

#13710 and #13722
