### ISSUE TITLE
Helicopters cannot be repaired in C&C

### ISSUE THREAD

**Issue by kerryhall** [OpenRA/OpenRA#13805]
Running version release-20170527.

Reproduce by trying to send a helicopter to the repair facility in C&C. Cursor is a "move" cursor, not a "land" cursor. When sending the move order, the helicopter hovers above the repair facility.

Helipads do not repair helicopters either, though helicopters can land on them.

Expected behavior: when helicopter is selected and cursor is on repair facility, cursor changes to "land" and helicopter can be repaired. If multiple helicopters are selected and ordered to the repair facility, they get repaired one by one.

Thanks!

**Comment by gdavegdave** [comment]
Yep, this bug was introduced in release-20170527, but it was fixed in playtest-20170722.

**Comment by pchote** [comment]
Closing as duplicate/fixed.
