### ISSUE TITLE
Multiple attack moves no longer issued when holding down 'A' [playtest 20170722] [bug]

### ISSUE THREAD

**Issue by gdavegdave** [OpenRA/OpenRA#13804]
With offensive units selected, holding down the 'A' key and clicking multiple times results in a single attack move order, followed by multiple move orders. This is in playtest-20170722

Previously (confirmed by testing in release-20170527, and in previous releases from memory), each click would result in an attack move. This is how it should be.

Any idea why the behaviour changed? Can it be reverted please?

**Comment by AoAGeneral** [comment]
Does A+Shift work?

**Comment by rob-v** [comment]
Yes, I know about this issue, I wondered why nobody complained so far and if current behavior is better or not. 
For many keys you need the action only once on press, like changing stance. So for many buttons we started to use only the first press. With new command bar it also disabled the click sound while holding A key iirc so it was applied for all command bar buttons/actions.
We can change it back and now also disable 'click sound' on hotkey so it will work like before.

**Comment by rob-v** [comment]
Fixed (Reverted) by #13807, but there might be better solution.

**Comment by gdavegdave** [comment]
Thanks @rob-v, that was quick!
