### ISSUE TITLE
ReflectionTypeLoadException when starting game

### ISSUE THREAD

**Issue by hartmark** [OpenRA/OpenRA#13803]
I get this exception now when trying to run with latest code from OpenRA.

Tried using mod ra and ts without any difference.

```
System.Reflection.ReflectionTypeLoadException occurred
  HResult=0x80131602
  Message=Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
  Source=mscorlib
  StackTrace:
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at OpenRA.Game.Initialize(Arguments args) in C:\Users\musku\Source\Repos\OpenRA\OpenRA.Game\Game.cs:line 296
```

And with this value to the LoaderExceptions property:
```
-		LoaderExceptions	{System.Exception[2]}	System.Exception[]
+		[0]	{"Method 'Play2DStream' in type 'OpenRA.Platforms.Default.OpenAlSoundEngine' from assembly 'OpenRA.Platforms.Default, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.":"OpenRA.Platforms.Default.OpenAlSoundEngine"}	System.Exception {System.TypeLoadException}
+		[1]	{"Method 'get_Complete' in type 'OpenRA.Platforms.Default.OpenAlSound' from assembly 'OpenRA.Platforms.Default, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.":"OpenRA.Platforms.Default.OpenAlSound"}	System.Exception {System.TypeLoadException}
```

**Comment by reaperrr** [comment]
Might be related to #13747? (Accidentally using .net 4.6 features?)

Pinging @RoosterDragon since 'Play2DStream' indicates the streaming code might be the culprit.

**Comment by pchote** [comment]
The simplest explanation and fix might be stale files.  Before we debug this further, can you please confirm that a full clean and rebuild (or a fresh clone and build) doesn't fix this?

**Comment by hartmark** [comment]
Alright, I'll try clean and rebuild

**Comment by rob-v** [comment]
@reaperrr IMO there are no 4.6 features, only 4.5.1 in the Windows launcher itself (so I guess you can run OpenRA with Game.Mod like before). As 4.5.1 on Win is not supported, we might also change Win requirements min. 4.5.2.

**Comment by RoosterDragon** [comment]
Because `OpenRA.Platforms.Default` isn't referenced directly by `OpenRA.Game` (it's loaded at runtime) - it won't be rebuilt if you build the `OpenRA.Game` project. You need to explicitly build the whole solution for it to be built and work correctly.

Sounds like you got it working. :)
