### ISSUE TITLE
Repair all buildings with a single key

### ISSUE THREAD

**Issue by kerryhall** [OpenRA/OpenRA#13806]
I would like to see a new feature where you can press one key to repair all buildings. If you have a ton of buildings, especially base defenses, it can be extremely difficult to click on all of them one by one. I have lost games because I couldn't click directly on the correct base defense in time.

It can be particularly troublesome to try and click on a base defense to repair it, and click repair on a unit by mistake and have them suddenly missing from combat as they return to the repair facility.

If you have the money, and wish to do so, why not press a button and have all buildings repair? Seems like something to make sense having in the game.

Thanks!

**Comment by abcdefg30** [comment]
Sorry, I don't see this happening in the default mods. Also see #17339.
