### ISSUE TITLE
cropped view of fullscreened chrome mac osx after quit game back to os

### ISSUE THREAD

**Issue by Trychlik** [OpenRA/OpenRA#13821]
when i have chrome on my mac in fullscreen mode, play openra and quit back to macOS, view of chrome is cropped, i must to exit fullscreen mode and enable it back to correct view. another fullscreen apps are ok, such as mail or evernote.

https://i.imgur.com/C4sU5jP.jpg

all software is latest versions
system 10.12.6
chrome 60
openra 2017 stable and playtest (both same problem)

i tested another browsers
safari, firefox ok
opera ko

is problem in browsers or in openra? its the first app, where i hit on this problem

**Comment by pchote** [comment]
This sounds like a bug in Chrome.  Opera uses the same browser engine as Chrome now, so it is not surprising that they both suffer from this problem but that Safari and Firefox (which use their own browser engines) don't.

**Comment by Trychlik** [comment]
i tested it more
problem appears only if in openra settings is display to "fullscreen legacy", if i set only "fullscreen" browsers are ok, but then system hot corners are enabled and its unplayable because of corners actions

**Comment by pchote** [comment]
There doesn't seem to be anything we can do here, so closing.
