### ISSUE TITLE
Issue "set primary" for a building by using "deploy/return to base" hotkey

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#13820]
Seems reasonable, as even the cursor shape is the same for deploying and primary building selection.

**Comment by rob-v** [comment]
We would need to either check if only one building of that type is selected or simply/faster? always set first one of each type in selection as primary.
I could look at it, question is if this is supported, not all new hotkeys are approved.

**Comment by CH4Code** [comment]
I wanted to contradict this idea, but thinking about it it is actualy a good idea for now as long as the limitation of one deploy action per unit is kept as a feature.

If you want something like the "Fist of Nod" mobile warfactory of TS firestorm this leads to conflicts though..

**Comment by abcdefg30** [comment]
Fwiw, you can set primary building via a hotkey by pressing ctrl while setting a rally point. Is that sufficient to close this issue?

**Comment by PunkPun** [comment]
> Fwiw, you can set primary building via a hotkey by pressing ctrl while setting a rally point. Is that sufficient to close this issue?

I say yes
