### ISSUE TITLE
Settings: non-english names for audio devices are garbled

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#13837]
Change of font or Unicode support required?
https://ibb.co/cuWb9v

**Comment by pchote** [comment]
Does #13621 fix this for you?

**Comment by netnazgul** [comment]
Looks the same (I have russian locale for those names).

If it's merged into the coming playtest I'll check for it there

**Comment by abcdefg30** [comment]
Fixed by #13621.
