### ISSUE TITLE
Keep Battlefield News open on the game launch

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#13832]
For better exposure of the news to players.

**Comment by x-a-n-a-x** [comment]
If it's always open (always expanded), then there no need to have a dropdown menu.. I guess you just want a simple frame with the news inside.

**Comment by rob-v** [comment]
When there is new news, the News is automatically expanded first time.

**Comment by netnazgul** [comment]
oh, right. Didn't think about that. 

I'll drop some other ideas for Battlefield news then

**Comment by pchote** [comment]
> When there is new news, the News is automatically expanded first time.

It's pretty clear that many people click past it without reading.  Having it open *all* the time would increase the chances of seeing it eventually.

**Comment by netnazgul** [comment]
On your discretion then. I'd also suggest showing it on other screens too, but that requires coding obviously.

Also, in fact if it's only in the main menu then there is no point in hiding it, because the screen is empty anyway.

**Comment by pchote** [comment]
The main issue with showing it on other screens is that the second most common screen resolution among players is 1366x768.  The MP and lobby windows take up too much of this space to leave room for the news display.

**Comment by netnazgul** [comment]
Checked 1366x768, I think there is just enough space at the top to squeeze in Battlefield news. But then thought that noone actually would use that anyway, so probably there is no reason of doing it. 

Maybe keeping the popup open in the main menu is still a good idea.
