### ISSUE TITLE
Guarding actors slightly lag behind guarded unit

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#13844]
Even if both actors have the same speed and move on the same terrain type, you can watch the distance slowly grow when they move on a straight path, with the guarding unit slowly falling behind.

Either the Follow activity, or the Guard code seems to insert a (presumably 1 tick) delay somewhere (even on previous release and current bleed, so not caused by recent changes to Move/Mobile).

**Comment by FrameLimiter** [comment]
The faster the guarded target moves the slower the guarding actor will follow. Tell a Flak Truck to guard a MiG and it'll have a hard time moving at all.
This isn't just for guarding either, it also applies to attack targeting.

**Comment by forcecore** [comment]
Probably return ActivityUtils.SequeneActivities(new activity, this): will make you lose the tick, if you don't tick the new activity before returning the new activity graph.
