### ISSUE TITLE
Sub pen and naval not targetable from certain angles(for chopper).

### ISSUE THREAD

**Issue by F5544** [OpenRA/OpenRA#13846]
The sub pen and naval yard are not attacked when the chopper is from a diagonal angle or up and down.
They just aiming but not attacking.
Something to do with this?
	HitShape:
		TargetableOffsets: 1273,939,0, -980,-640,0, -980,640,0
		Type: Rectangle
			TopLeft: -1536, -598
			BottomRight: 1536, 598
	HitShape@TOPANDBOTTOM:
		TargetableOffsets: 811,0,0, -811,0,0
		Type: Rectangle
			TopLeft: -555, -1110
			BottomRight: 555, 1110

**Comment by abcdefg30** [comment]
I tried to reproduce this with a single helicopter but didn't notice anything. Would you mind providing screenshots/replays?

**Comment by F5544** [comment]
hmm sorry it was my mod in the weapons.
No bug.

**Comment by abcdefg30** [comment]
No problem. ^^ Still better than not reporting what could have been a legit bug.
