### ISSUE TITLE
Capture bug renders structure uncontrollable.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#13841]
This is hard to describe so im going to leave the replay here.

https://www.dropbox.com/s/wqac62c3mf1fcid/Airstrip%20bug.orarep?dl=0

This is in the playtest version. Engineer enters the structure as it is being sold then pops back up under the players color but can't be controled. This was seen happening a few releases back as well with the Commando.

**Comment by netnazgul** [comment]
#12474 tied to this one too?

**Comment by pchote** [comment]
This should have been fixed by the engineer rework shipped in release-20190314.
