### ISSUE TITLE
HasAnyValidWeapons doesn't check if Armament is disabled by a condition

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#13855]
https://github.com/OpenRA/OpenRA/blob/0a1083e5542c11f9d2974fd7a6ac53c5d1a5756e/OpenRA.Mods.Common/Traits/Attack/AttackBase.cs#L201-L215

On the image, Overlord tanks that under Hunt() activity tries to attack the Comanches, even tho they don't have Overlord Gatling upgrade (so Gatling weapon is disabled)
![overlords](https://user-images.githubusercontent.com/7933210/29414472-7805e874-8368-11e7-80af-a48796243da1.png)

**Comment by pchote** [comment]
You can work around this in your yaml, and still should even after #13856 to improve performance:  use your upgrade condition to switch between `AutoTargetPriority`s that do/don't target aircraft.

**Comment by MustaphaTR** [comment]
I already did that after noticing the bug, but it doesn't look like fixing it alone, this is something to do with Hunt() too, not just AutoTarget behaviour.

**Comment by GraionDilach** [comment]
That's probably due to #12856.
