### ISSUE TITLE
Rename EditorTilesetFilter to something more generic

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#13857]
From IRC:
```
[17:17] <reaperrr> pchote: Would removing 'Tileset' from the trait name be enough ('EditorFilter'), or would 'EditorVisibility' be better?
[17:18] <+pchote> I would prefer something like MapEditorData
```

**Comment by Ashiko124** [comment]
I am looking to help out with the project but am not really sure how to start? I am somewhat effective with programming but have only been writing code for about 5 years and only 3 mo in a professional capacity. 

Thanks, Jonathan Greeneselectronics@gmail.com

**Comment by abcdefg30** [comment]
Would you mind joining our IRC channel #openra? (http://webchat.freenode.net/?channels=openra)

**Comment by abc013** [comment]
@Ashiko124 are you working on this?

**Comment by Ectras** [comment]
I could do this. However, I think that it could crash all mods, because the .yaml files reference the "EditorTilesetFilter". Can be fixed for the official mods, but might be a problem for the unofficial ones. 
Please correct me if I'm wrong.
