### ISSUE TITLE
D2k-Playtest: Sonic tank damage too high

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#13850]
Hi, I just went for the most likely unit to be bugged and affected by hitshapes.
I placed a sonic tank to the bottom left corner of a conyard and fired it to the top right corner above it.

Damage report (in shots to destroy):
Release: ..............17
Playtest: ..............9
Original (1.02): 22

Other tests (release, playtest,original)
no concrete heavy factory (2, 1.5, 13)
Infantry (2, 2, 2(but larger AOE) )

Clearly the sonic tank has become much more powerful by the hit-shapes-change and should be tuned down.

Other units (Siege tank & combat tank tested) seem fine (some deviations from original aside, Release==Playtest).

**Comment by CH4Code** [comment]
Im not sure how the ORA sonic tank weapon works, seems to be a blend of grapic representation of the beam and warheads applied to subjects "coated" by the beam. Unfortunately I dont see a way to change the AOE without changing the graphical representation (width) of the beam... So no AOE like in the original atm.

However, changing the damage values of the warheads of the sonic weapon to **40** would reproduce the original values (shots to kill) perfectly. Tested for combat tanks, harvesters, infantry, quads, missile and siege tanks. The AOE again, however, is very weak in comparison to the original (0.5 cells to 1.25 cells radius)...

**Comment by pchote** [comment]
> However, changing the damage values of the warheads of the sonic weapon to 40 would reproduce the original values (shots to kill) perfectly.

You mention that you tested for several vehicles, but nothing about buildings.  How does 40 damage fare there?

**Comment by CH4Code** [comment]
Pretty much back to to the release: 
conyard: 18
warfacory: 3
(Infantry is 4 shots however... :/ )

**Comment by CH4Code** [comment]
So my latest suggestion :  80 damage, but halve all the Versus: values.

Then: buildings are back to the release, tanks and infantry are back to the original.

**Comment by pchote** [comment]
The amount of damage applied includes the specified damage multiplied by the versus, so 80 * <halved versus> should be identical to 40 * <normal versus>.

**Comment by CH4Code** [comment]
That was the intention, since infantry isn't listed in Versus: explicitly.
Probably because Infantry has the armor type "None". So I assume it takes takes full damage and everything else reduced ammounts.
Infantry died "too slowly" with 40 dmg (4 shots instead of 2 shots like in release).

**Comment by reaperrr** [comment]
I think it would be more straightforward to add none: 200 then (1 additional line instead of x changed lines).

**Comment by pchote** [comment]
There are also the "wood" and "concrete" versus types which aren't declared on Sound.  I tried setting it up with damage 40 and versus 200 where necessary, but was not able to reproduce the desired hit-kill-counts listed above.  At this point I basically gave up trying to understand what is going on with the d2k weapon/armor definitions.

**Comment by CH4Code** [comment]
Did you keep in mind that sound does only half damage vs own units while testing?

**Comment by pchote** [comment]
I did, yeah.

**Comment by CH4Code** [comment]
I dont claim to understand what is going on with the areabeam the sound weapon uses (I tried to, but some values in the yaml seem ridiculous while others seem to have no effect beeing changed), but empirical testing with 80 damage and halved versus values for this weapon has the desired result...

**Comment by CH4Code** [comment]
Hmm, for me 40 dmg and none: 200 works, though... o.O

**Comment by pchote** [comment]
@CH4Code do you want to put together a PR?

**Comment by reaperrr** [comment]
While testing #13870 I noticed that something fishy is going on with the Sound weapon. For example, if it shoots down the left or right vertical row of the CYard, it does zero damage, which is definitely absolutely wrong.

In other words, either `AreaBeam`, `SpreadDamageWarhead` or some element of victim scanning must have a bug.

**Comment by reaperrr** [comment]
@pchote what would be the best way to find out for sure whether our `FindActorsOnLine` overselecting is broken?

**Comment by CH4Code** [comment]
yes, i posted that in #13851 allready.
and I  noticed another one... It also does not discriminate between friend and foe as yaml suggests (the falloff is irrelevant) i'll adjust the PR in a moment...
I realize why pchote was so confued now ^^
