### ISSUE TITLE
System.Reflection.ReflectionTypeLoadException

### ISSUE THREAD

**Issue by beckno9** [OpenRA/OpenRA#13863]
Today I open the game and then I found the game crash with a System.Reflection.ReflectionTypeLoadException , I found something on wiki said it means game require .NET Framework 4.5, but for develop reasons I have 4.5 and higher version (4.7) installed (include SDK), so I want to know what exactly happened.
One more thing, I just installed the RedAlert 2 mod, is this thing caused the exception?

**Comment by pchote** [comment]
What version of OpenRA, and which RA2 mod (there are several different versions floating around)?

**Comment by beckno9** [comment]
@pchote I get from repo OpenRA/ra2 , it should be the latest version.
