### ISSUE TITLE
Chronosphere and Cargo/Transport conflict

### ISSUE THREAD

**Issue by runeavalon** [OpenRA/OpenRA#13866]
i played a mp game this day and something strange happened.
a teammate of mine selected an mcv of mine not knowing i was going to load it into a transport boat at the same time. I guess my teammate targetted the final destination only after my mcv was loaded. I fled to another place on the map, but after unloading in the timer of the chrono started ticking of, and after timing out it chrono'ed my mcv back to where i came from,,,,,,,,,,,,in the middle of all the danger,,,,,,,,,,,, -_-,,,,,,,,,,so i lost

but that doesnt mather,

i hope you guys can reproduce this bug

cheerzz,

Ohmk Torque

**Comment by CH4Code** [comment]
lol ^^ that must have been very precise timing!

But I managed to reproduce it. 
If you chrono the mcv while it is entering a transport, the chrono does not go off immediately. instead the MCV turns around and as it reaches the shore again, then chrono is triggered "normally".
However, you can order the MCV that has just turned to turn again and embark the transport, canceling the chrono once again. After that it doesn't attempt to chrono-move anymore. When the bar is empty however, the MCV returns to the position where the crono was originaly applied, like normal.

Nice find :D

**Comment by runeavalon** [comment]
Haha ok Great that you managed to reproduce it!!!! It was indeed an insane timing. I was afraid it was such a narrow timing that it would be too difficult to reproduce. I guess not :D. Well then, I am glad to have made a small contribution again to this game. Good luck programming guys,

Cheerzzz,

Ohmk Torque

**Comment by abcdefg30** [comment]
I can't reproduce this on latest bleed.
