### ISSUE TITLE
Planes stop mid-air for a tick when the stop hotkey is pressed

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#13861]
Repro case: build a Yak in RA and then spam <kbd>s</kbd>.

This is not new, but I'm not aware of any existing tickets for this.

**Comment by tovl** [comment]
I cannot reproduce this on bleed.

**Comment by GraionDilach** [comment]
My AI can reproduce something suspiciously similar - aircraft just stops in air if their target dies mid-burst.

**Comment by pchote** [comment]
This was presumably fixed during the aircraft or more general activity rework.
