### ISSUE TITLE
Follow activity sometimes fail to Cancel()

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13879]
CancelActivity() or Cancel() doesn't work on Follow activity sometimes.
I think it has something to do with child/inner activity.
When fails, it gets stuck at WaitFor activity when seen through Show actor tags debug function.

I use follow activity for the slave miner. When the slave miner undeploys and gets going, slaves are assigned follow task. When the miner deploys, Follow is canceled for slaves and FindResources is newly assigned.

**Comment by abcdefg30** [comment]
I don't think this has enough information for us to go on. A reproduction case in the default mods would be good.
