### ISSUE TITLE
OpenRA build on Linux uses both curl and wget

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13888]
While building from a freshly installed Linux build system, I noticed that the build scripts require both of these tools, instead of only one of them.

https://github.com/OpenRA/OpenRAModSDK/issues/36 (see the discussion here)

https://github.com/OpenRA/OpenRA/blob/57fb5515456dd688f29ed91e67aa09a21d644dec/thirdparty/fetch-thirdparty-deps-windows.sh#L22

**Comment by pchote** [comment]
This impacts compatibility for the mod SDK, so adding to the release milestone.
