### ISSUE TITLE
Inconsistent expiration of ExternalCondition timers when TotalCap is reached.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#13918]
As discovered in #13719, `ExternalCondition` will expire always expire the shortest remaining timer if the `TotalCap` is reached, rather than the shortest *from the same source*.  This is inconsistent with both the comment and with the way it handles `SourceCap`.  `TotalCap` should behave the same way as `SourceCap` with a fallback to the `timedTokens[0]` only if there are no tokens from the same source.

`TotalCap` handling:
https://github.com/OpenRA/OpenRA/blob/fd6b2c01070657c67e5ca66be7894ec24291e4cc/OpenRA.Mods.Common/Traits/Conditions/ExternalCondition.cs#L128-L131

`SourceCap` handling:
https://github.com/OpenRA/OpenRA/blob/fd6b2c01070657c67e5ca66be7894ec24291e4cc/OpenRA.Mods.Common/Traits/Conditions/ExternalCondition.cs#L111-L115

**Comment by pchote** [comment]
On further thought, expiring the shortest (ignoring the source) is the more sensible behaviour.  Removing the incorrect comment is be a better fix for this issue.

**Comment by reaperrr** [comment]
An inaccurate comment isn't a blocker, so removing from milestone.

**Comment by pchote** [comment]
This issue came up as part of the github-cleanup initiative. I don't have time right now to refamiliarise myself with this code and work out what I actually wanted / want now, but there is no reason why we can't resolve this before the next release.
