### ISSUE TITLE
Drop Pods Support Power

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#13928]
http://cnc.wikia.com/wiki/Drop_pod_control_plug

Assets:
`rad1icon.shp`
`gaplug_d.shp`
`podsicon.shp`
`droppod.shp`
`droppod2.shp`
`droppody.shp`
`droppody2.shp`
`pod.shp`
`podring.shp`

**Comment by Mailaender** [comment]
http://www.moddb.com/mods/shattered-paradise/images/drop-pods#imagebox not sure how the Shattered Paradise people solved it and if code already exists.

**Comment by GraionDilach** [comment]
That's a heavy workaround with SpawnActorWarhead and a dummy superpower and completely inaccurate IMO.

**Comment by GraionDilach** [comment]
Drop Pods worked as the following:

When ordered:
pod is spawned at a fixed offset from the target location, plays a from-orbit animation
pod fires a weapon at the target location while landing at it
landing anim plays
infantry exits from the pod
pod fades out.

**Comment by reaperrr** [comment]
> plays a from-orbit animation

Could be reproduced by timing the speed and launch altitude with Aircraft + FallsToEarth trait.

> landing anim plays
infantry exits from the pod
pod fades out.

landing anim and pod fade-out are just visual and could be reproduced with `Explodes`.
infantry exit can be done via `EjectOnDeath`.

So basically, what we need the SupportPower to do is trigger the pod launch at the right offset(s) and make the pods force-fire on their respective landing cell. Also, they must not launch towards cells occupied by buildings.
