### ISSUE TITLE
Set "all players" vision setting as default for spectators/replays

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#13923]
Because no one ever uses "Disable shroud" and switches it anyway.

**Comment by rob-v** [comment]
It is simple to change, but with not Explored map, it starts all black. Is it suitable?

![image](https://user-images.githubusercontent.com/16348750/29769834-54f8da1c-8bec-11e7-83be-a159b2266ae5.png)

Explored Map:

![image](https://user-images.githubusercontent.com/16348750/29769977-f58f7bfc-8bec-11e7-8e3d-24f5f18a266e.png)

**Comment by pchote** [comment]
> It is simple to change, but with not Explored map, it starts all black. Is it suitable?

IMO, no.  This is why we kept it on disabled to start.

**Comment by netnazgul** [comment]
Yes, setting "explored map = TRUE" and "Crates = FALSE" by default is also a request

**Comment by DoomsdayRA** [comment]
Would it be possible to have "all players" if game has explored map and clear if map has shroud?

**Comment by rob-v** [comment]
Yes, it is possible. I'll create PR and we'll see if also accepted.
