### ISSUE TITLE
Repair Pad & Service Depot are overlapped by civilian crop fields

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#13939]
This is a poor looking overlap, especially in RA:

![td-ra--sd_field_overlap](https://user-images.githubusercontent.com/22008761/29883475-7286d640-8d7e-11e7-815a-088aff099764.png)

**Comment by reaperrr** [comment]
I guess we could try to give the fields lower Z offsets to make any adjacent actors overlap them, but that's pretty much the only solution I can think of, apart from changing the footprint of the pad/depot.

**Comment by FrameLimiter** [comment]
With a Z offset of -2c512:
![sd](https://user-images.githubusercontent.com/22008761/29996428-2c30a14e-8fcc-11e7-91ac-73d1f0b83a77.png)

**Comment by FrameLimiter** [comment]
The RA Service Depot is also getting overlapped by bridges:
![a](https://user-images.githubusercontent.com/22008761/31191184-5e4d2c26-a90b-11e7-91ae-783af4b58590.png)
