### ISSUE TITLE
Sprites not pixel exact - scaling issues

### ISSUE THREAD

**Issue by BlueMax** [OpenRA/OpenRA#13963]
Hallo,
the sprites are not pixel exact. Look at the head of the infantry or the trousers of the engineer (compare with other pic). They are broader/wider in x-axis. Some vertical (pixel)lines are duplicated (sprites only - not background). These are scaling bugs that differ from the original game. I'm not talking about general resizing or relative size of the sprites. Its about bad rendering/representation/graphic engine issues.

Is there any fix for this?

Ignore the red circle. I've taken the picture from the [forum](http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=16896).

Click to enlarge. 
![Image](http://abload.de/img/sprite-size-fs8s8ldp.png)

Arch Linux 4.12.8
OpenRA 20170527
Display 1600x1200

**Comment by GraionDilach** [comment]
>These are scaling bugs that differ from the original game.

This is exactly how it looks in RA95. Red Alert also used different infantry sprites between the DOS and the Windows version, compared to C&C where only sidebar and it's contents were respective for the game versions.

**Comment by BlueMax** [comment]
What Windows version are we talking about? Mine is original CD-ROM from 1996 (german version) with 1.08 patch. I start the game directly in Win7 with RA95.exe. It runs fine on 640x480 with most Windows compatibility settings (win98) enabled. The graphics are ok (they are not badly stretched as in the picture above). Unfortunately, i neither can take a screenshot with windows clipboard nor anything with msi afterburner. It always results in mostly black graphics with false colors (the game is ok though).

Win7 x86-64
Command & Conquer: Red Alert v1.08 (unofficial patch)

**Comment by GraionDilach** [comment]
If you look at the original WW redalert.mix/lores.mix with a MIX editor, you'll find the non-badly stretched but TD-sized versions of the infantry, combined with some simple 32x24 sized cameos (which OpenRA repurposed into beacon images for superweapons). These were only loaded by the DOS executables. On the right image, the infantry versions are from redalert.mix/hires.mix, the MIX RA95 should load up.

I'm not sure what this 1.08 patch contains, but no official patch changed on this front. I acknowledge that i only gave a try to 2.00 and 3.03 myself though.

**Comment by reaperrr** [comment]
@BlueMax The original game actually stretches an internal resolution of 640x400 to 640x480.

OpenRA displays the sprites as they actually are, i.e. it's the original that stretched them vertically, not OpenRA stretching them horizontally.

**Comment by pchote** [comment]
Note that it's a bit more subtle than that: CRT monitors had a much fuzzier definition of a pixel than modern LCD displays, and they were typically not square.  The stretching was a factor of the display hardware rather than something explicitly done in software.

**Comment by BlueMax** [comment]
> If you look at the original WW redalert.mix/lores.mix with a MIX editor, you'll find the non-badly stretched but TD-sized versions of the infantry

The original CD doesn't have this files thus the Windows version works properly as well (at least up to patch 1.08). The HIRES1.MIX and LORES1.MIX were introduced in the unreleased v3.03 beta patch. 

Do we really need to rely on this obviously corrupt data? This is not the original graphic nor Westwood quality. Its EA quality.

**Comment by pchote** [comment]
I'm not sure what you mean @BlueMax: the original CDs (RA95, The First Decade, and the Origin digital release) *did* ship those files.  You can see the rules for extracting them from the various original game media by reading the metadata files in https://github.com/OpenRA/OpenRA/tree/bleed/mods/ra/installer.

**Comment by Micr0Bit** [comment]
>OpenRA has to use the windows versions of these sprites because the Shock Trooper (as being an expansion unit) was unreleased for the DOS version

@GraionDilach : thats bad news for #11650 then

**Comment by BlueMax** [comment]
> the original CDs (RA95 -- the freewared release --, The First Decade, and the Origin digital release) did ship those files.

I cannot see them on my CDs (in main.mix). Program is xcc mixer. I couldn't get 'openra.utility.exe ra --extract *.mix' to work (error: mix file in use).

![ccra](https://user-images.githubusercontent.com/1403092/29998933-683596fc-9037-11e7-939a-e41c20089043.png)

I guess everyone is using the extensions (aftermath, counterstrike) and the bug is present there as well. I cannot check that as i don't have the extensions. 

It seems most users call this bug simply "bigger sized sprites". That's a very euphemistic term for such a terrible mess they've done to the sprites.

But i see you already know about that problem even though i don't understand why the missing sprites can't be backported or the old ones converted to the new format.

Thanks for the help. Feel free to close.

**Comment by reaperrr** [comment]
> That's a very euphemistic term for such a **terrible mess they've done to the sprites. They just rescaled the sprites by some pixel with 'pixel duplication' (probably automated with Photoshop - how cheap...)**.

That's something I personally actually agree with, but we're using the resized sprites anyway because a) most people only played the Win95 version and are used to them and b) at high resolutions the DOS sprites are very tiny and harder to distinguish.

@GraionDilach @Micr0Bit To my knowledge, the Mechanic is just a recolored Medic and the Shock Trooper a recolored Flamethrower, so we could take the DOS sprites of those and try to recolor them as accurately as possible with OS SHP Builder (can give it a try when I find the time).

**Comment by BlueMax** [comment]
> at high resolutions the DOS sprites are very tiny

Maybe a 3x, 4x (global) zoom might come in handy for todays high-dpi displays. 
Or an optional 2x (integer) scaled zoom of the lores sprites.

**Comment by abcdefg30** [comment]
> Anyway, thanks for the help. Feel free to close.

The other things from the last posts seem to concern other tickets.
