### ISSUE TITLE
Cannot issue 'repair' on helicopters

### ISSUE THREAD

**Issue by praetp** [OpenRA/OpenRA#13975]
When you do a 'repair' on a vehicle, it will return to the service depot for repair.
This does not work for helicopters...

**Comment by spetsnaz84** [comment]
Well, it would be nice if it did :-)

**Comment by pchote** [comment]
We only recently fixed this for ships, so it makes sense to support it for aircraft too.

**Comment by rob-v** [comment]
It will be more advantageous for helicopters than planes as planes are moving.

**Comment by dsimmons87** [comment]
Just a suggestion, but could an extra key binding be added for repairing units?

The return to helipad f binding is likely to be getting stripped out for TD air units (see issue #14641), and trying to use the repair tool on a flock of 7 helicopters will be a lot more difficult than the current mechanic of just selecting them all and pressing f.

This extra binding would also be very nice to have for planes / helicopters too in RA, or vehicles in all mods.

**Comment by Smittytron** [comment]
Adding the repair tool to aircraft would be a welcome feature for competitive play. I see via crash-log that `Repairable` apparently wants the actors to have `Mobile`. 

> It will be more advantageous for helicopters than planes as planes are moving.

I don't see a balance issue here. I want the repair tool for my planes as much as I do for my helicopters. Still faster than scrolling back to your service depot to give the order, even with a misclick or two.

**Comment by pchote** [comment]
Pretty much all the code involved with this is awful and needs to be rewritten from scratch.  I don't see this happening in the near future so it is not realistic to delay the milestone over it.
