### ISSUE TITLE
F button does not work for Chronotank

### ISSUE THREAD

**Issue by spetsnaz84** [OpenRA/OpenRA#13977]
In release-20170527, you can hit the F button for 'deploying' e.g. an MCV. I would expect you can also use this to activate the Chronotank's special ability.
This does not work.

**Comment by GraionDilach** [comment]
Duplicate of #13105.

**Comment by netnazgul** [comment]
You can also use force move (alt+click) to chrono (multiple tanks at the same time too)

**Comment by pchote** [comment]
Closed by mistake? Reopening.

**Comment by Mailaender** [comment]
> Duplicate of #13105.

**Comment by pchote** [comment]
Ah, my bad.
