### ISSUE TITLE
RA capturing barracks while building unit bug?

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/OpenRA#13983]
Hey, I'm not sure about this is a issue:
I was capturing a barrack while my enemy was producing a unit,
his %bar stops at 100%, the unit building time is complete, but it doesn't leave the barrack due to capturing. Then my capturing process is finished and the unit is leaving the barrack, but the unit is still an enemy. Indented?

Stable version release-20170527

**Comment by TheRaffy** [comment]
would a reply help?

**Comment by TheRaffy** [comment]
https://www.dropbox.com/s/tg03zijw2l4jsyt/capturing%20while%20building%20bug.orarep?dl=0

**Comment by abcdefg30** [comment]
Stopping at 100% is intended, see #11951. But the unit exiting after the capture was successful not.

**Comment by penev92** [comment]
I guess  #14220 should have fixed this?
