### ISSUE TITLE
MCV Deployment overlaps with adjacent MCVs

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#13984]
Discovered by the player egg.

(Release & Playtest)
So long as the MCVs are all facing the same direction and at least 1 cell apart, they can deploy on top of one another if deployed at the same time:
![mcv_deploy](https://user-images.githubusercontent.com/22008761/30038981-d198e308-9198-11e7-8931-c4c726374f34.png)

**Comment by Elizadmin** [comment]
Similar to https://github.com/OpenRA/OpenRA/issues/6683, https://github.com/OpenRA/OpenRA/issues/9902 and https://github.com/OpenRA/OpenRA/issues/12558.

**Comment by abcdefg30** [comment]
Afaik this was fixed.

**Comment by PunkPun** [comment]
Still possible

![Screen Shot 2020-08-29 at 23 20 54](https://user-images.githubusercontent.com/37534529/91645520-52757700-ea4e-11ea-9885-fb8a40f132c8.png)
