### ISSUE TITLE
TiberianSunRefinery not needed in the future?

### ISSUE THREAD

**Issue by forcecore** [OpenRA/OpenRA#13992]
From #13721 :
> And I came to a conclusion that it is the activity that knows what to do when docking, not the client/host actors. For example, if I ordered an MNLY to dock at a FIX it should move to the rally point after reloading and repairing. On the other hand, if it was laying mines and it came back to the dock to reload, it should reload and continue to lay the mines.

If this discussion is accepted, then TiberianSunRefinery should be deleted, as it only provides the dock sequence, which is what VoxelHarvester should know better.

This change will allow mixing voxel and non-voxel harvesters to dock at a refinery.

**Comment by GraionDilach** [comment]
Related: it would be a better option than TiberianSunRefinery to grant a condition for the artwork switching. The current setup prevents using harvesters based on the RA2 Soviet War Miner concept art, where the turret was on top of the container and voxellers tended to flip it along with the container for unload.

**Comment by pchote** [comment]
This is a problem for/with the refinery code in general, not just `TiberianSunRefinery`.  I hope/expect #13732 and followups will fix this.

**Comment by yaaaaa** [comment]
I just add blank VXL file (or make it invisible by small size) to sprite harvester unit, and its work for my mod.
