### ISSUE TITLE
d2k-playtest only: pixel errors in superweapon-icons

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#13999]
![bugged_icons](https://user-images.githubusercontent.com/16046997/30209742-d079158e-9499-11e7-9ef9-acf8f33a293b.png)
This applies to all powers. Even custom icons (thats how I noticed..)
However only in d2k. RA and TD are fine. Occurs in playtest 20170722 and 20170902.

**Comment by pchote** [comment]
I expect that this happened during the chrome artwork reorganization for the command bar.
