### ISSUE TITLE
Paratroopers should notify player when they land

### ISSUE THREAD

**Issue by Smittytron** [OpenRA/OpenRA#14003]
Players will often forget paratroopers after they call in a drop as planes may take a long time to arrived after the order has been issued. This is frustrating for not just players but spectators as well as paratroopers may go unused for several minutes. 

Players should be notified when the drop reaches the LZ by the ReinforcementsArrived notification.

IIRC this is also true to the original.

**Comment by rautamiekka** [comment]
When you called in reinforcements through paradrop you received no notifications, only during the campaign (or if scripted ?).

**Comment by GraionDilach** [comment]
Yes, only mission scripts gave you EVA notifs about paradrops.

**Comment by pchote** [comment]
IMO that seems like a bug or limitation in the original, and fixing this for our RA mod seems like a no brainer to me.  This is a simple polish and gameplay improvement, so i'd like to include this in the next playtest if there are no objections.

**Comment by GraionDilach** [comment]
Only if it's disableable by the modder. I find this a let-the-gameplay-itself kind of feature.

**Comment by pchote** [comment]
> Only if it's disableable by the modder.

Of course.  The default should be for no notification, and then the RA mod can turn it on.

**Comment by SoScared** [comment]
The announcer always came before the units appeared on the map. It's probably more fitting for the voice track to pop right before the first paratrooper is dropped from the badger.

**Comment by Phrohdoh** [comment]
@gkaretka is working on this.

**Comment by abc013** [comment]
can be closed?
