### ISSUE TITLE
playtest: building placement preview not centered around mouse cursor

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#14000]
In all three mods in the playtest 20170902 the building preview "attaches" to the mouse on the lower center(right) corner. In the release it was allways the center(right)-most cell.

Example PP release | playtest (C=cursor):
XX | XX
XC | XX
XX | XC

Example temple of nod  release | playtest (C=cursor):
XXX | XXX 
XCX | XXX 
XXX | XCX

**Comment by pchote** [comment]
I expect this will be a regression from the bib footprint changes.
