### ISSUE TITLE
Linter error? Or error editing/making shps?

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#14002]
Hi, 
I have been killing all linter errors I could find in my maps, like Chrisf suggested (by rolling eyes at me ignoring lint checks).

But this last one I don't grasp, pchote suggested I file it here...
It first appeared when I added custom shp's to my map. Anyone has an Idea what this might have caused? Keep in mind that I was using a mash-up of editing tools including gimp, os shp builder and XCC utilities to generate those shps, so there might be some error there as well.
However, the map (and all of its successors) runs without crashes, afaik.

```
Testing map: [VS.mis] Atreides Mission 1
OpenRA.Utility(1,1): Error: OpenRA.Mods.Common.Lint.CheckSequences failed with exception: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei OpenRA.Mods.Common.Lint.CheckSequences.<CheckDefintions>c__AnonStorey6.<>m__0(MiniYamlNode n)
   bei System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   bei OpenRA.Mods.Common.Lint.CheckSequences.CheckDefintions(String image, SequenceReferenceAttribute sequenceReference, KeyValuePair`2 actorInfo, String sequence, String faction, FieldInfo field, ITraitInfo traitInfo)
   bei OpenRA.Mods.Common.Lint.CheckSequences.Run(Action`1 emitError, Action`1 emitWarning, Map map)
   bei OpenRA.Mods.Common.UtilityCommands.CheckYaml.OpenRA.IUtilityCommand.Run(Utility utility, String[] args)
```
Map where this first occurs: http://resource.openra.net/maps/20201

**Comment by MustaphaTR** [comment]
I'm not sure this is the same error, i haven't seen it for a while. But afaik SHP (TD) files saved with SHP builder don't work with OpenRA.

**Comment by CH4Code** [comment]
I save as shp(ts) and convert that with XCC to shp. Using shp(td) directly from SHP builder causes a crash. So, thats not the cause of this error.

**Comment by CH4Code** [comment]
just noticed the error isnt there anymore when using lint with the playtest, so maybe just wait for next release and then see if it is still there.
