### ISSUE TITLE
Allow engineers to repair damaged bridges.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#14029]
Currently not possible. You need to first destroy it before you can repair it to full.

Broken bridges slows down vehicle movement. Allowing the player to repair bridges with the engineer would be a nice detail for maps that use broken bridges for various effects.

**Comment by SoScared** [comment]
Never mind, just learned you have to CTRL+Right-Click to get the engineer repairing a damaged bridge.

**Comment by pchote** [comment]
We should mention this in the force-attack command bar tooltip.
