### ISSUE TITLE
Decide whether to keep EjectOnDeath on RA vehicles

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#14020]
#13892 had an unintentional side-effect of fixing an old, long broken and forgotten feature in the RA mod to spawn infantry from destroyed vehicles. 

If we want to keep this "new" feature then it should be listed in the Changelog.  If not, then `EjectOnDeath` should be removed from the `^Vehicle` default.

Related IRC discussion / initial report: https://logs.openra.net/?year=2017&month=09&day=11#23:10:07

**Comment by Smittytron** [comment]
Personally I'm against keeping eject on death for vehicles. It makes sense for air units as a parachute at least adds something visual, but in ground combat spawning rifles will die almost instantly the majority of the time. This adds more distraction then flavor. For the vehicle's owner, this will only result in an additional unit-lost notification, and for the opponent, an additional $10 bounty.

**Comment by F5544** [comment]
Or use it to rescue it, for a bonus or put it in a unit for veterancy

**Comment by SoScared** [comment]
Adding a passive target on the field probably adds a nuisance within tank-to-tank combat especially considering tanks weak performance vs none in general.
