### ISSUE TITLE
Generals and Emperor Dune?

### ISSUE THREAD

**Issue by ROCKNROLLKID** [OpenRA/OpenRA#14037]
I am curious if, once Tiberian Sun and Red Alert 2 are done and the engine is much closer to how the team wants it to be, will you move on to add 3D support and do games like CNC Generals and Emperor Battle for Dune?

**Comment by reaperrr** [comment]
Some preliminary work to allow adding support for more model formats than voxels has already been done, but for legal reasons I highly doubt we'll ever consider making 'official' Generals/E:BFD mods.
External modders may still try and possibly succeed, though.

**Comment by pchote** [comment]
Generals allows for free-form actor placement and moving, which fundamentally changes many core engine design decisions.   Changing OpenRA to support this would be conceptually like changing a boat to be able to fly.  While it might be *technically* possible, it would be significantly harder than starting from scratch on something that was fit for purpose.

Question has been answered, so closing.

**Comment by Mailaender** [comment]
Have a look at https://github.com/TheAssemblyArmada/Thyme by @omniblade instead.

**Comment by ROCKNROLLKID** [comment]
Thank you Mailaender. I did see that once before in the past and I have been waiting for builds to be released. Too bad it isn't for emperor battle for dune.

**Comment by cookgreen** [comment]
@ROCKNROLLKID  I have created a open source project which is aim to re-create this game, here is repo: 

https://github.com/cookgreen/CorrinoEngine
