### ISSUE TITLE
Game crashes if a SpriteEffect starts with an empty frame

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#14047]
Regression from #13979.

The problem will be the fact that compressed shp(ts) files with empty first frame return an `Animation.Image` size of `0, 0`.

One possible solution would be to check for the largest frame of the animation and return that as `Animation.LargestImage` so we can pass that to the ScreenMap to calculate the bounds, but I'm not sure what performance impact this approach might have.

**Comment by pchote** [comment]
`SpriteEffect.Tick` needs to update the screen map after ticking the animation so that it can set the right size for the visible frame.

**Comment by reaperrr** [comment]
Ouch, forgetting that for the most important effect... well, at least it was caught quickly, thanks @GraionDilach.
