### ISSUE TITLE
tiberium dawn tree infect/grow tile?

### ISSUE THREAD

**Issue by shpookys** [OpenRA/OpenRA#14051]
1. when are we going to get the tree infection?
would be cool to see this feature implemented in a way that it would be optional
like map makers could add trees that are infect able and ones that aren't

2. would like to see a tile/object that slowly grows Tiberium thats is placed by maps makers  and or is created by the Tiberium its-self 

basically this tile would act as Tiberium roots

"No matter how small, an isolated patch of Tiberium can spread to cover acres. The process is not entirely understood, but it is believed that a patch of Tiberium will release underground shoots in every direction, which will then grow into Tiberium proper. In this way, the amount of Tiberium in an area will increase exponentially. Tiberium patches can be completely de-'forested' temporarily, but will grow back even if the Tiberium is completely removed, due to its underground "roots", as well as smaller crystals, that will remain in the soil and become clusters for further crystalline growth. As such, the ground from which Tiberium grows sounds like shattered glass when walked on" http://cnc.wikia.com/wiki/Tiberium

**Comment by shpookys** [comment]
also the root tile would be non harvest-able of course

**Comment by ltem** [comment]
A developer is already on it, take a look at #13969.

**Comment by shpookys** [comment]
oh ok

**Comment by AoAGeneral** [comment]
I was under the impression that this would create a balance issue when this idea was brought up in the past. I had no idea this was being worked on already.

**Comment by jimbojones1987** [comment]
Is this implemented? :)
