### ISSUE TITLE
Cooldown on healing

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#14076]
A medic blob can turn an infantry blob almost invincible : 
https://www.youtube.com/watch?v=sbHfPqXKf-0&t=2m13s

This is due to the fact that a single unit can be healed instantly by several medics, soaking damage indefinitely. 

Therefore, I suggest there should be a cooldown on how fast a unit can be healed (similar to the weapon cooldown). See it as if 1 medic heals 1 unit, so a group of medics would still be useful healing several  damaged units, but not the same single unit. 

Not sure if it should be applied to mechanics.

**Comment by AoAGeneral** [comment]
This has been an issue for a long time. The reduction on medic HP has helped a bit in this regard but its good to note that medics heal infantry at full health everytime. If they healed at either 60% of their HP instead this would help to alleviate some of the damage soaking problems mentioned here. (Same method done in RA95)

**Comment by GraionDilach** [comment]
This is completely doable already with YAMLs alone. One needs to expand Medic's heal with a GrantExternalConditionWarhead and then use the new condition to prevent medics targeting said infantry.

Pinging @Smittytron for consideration.

**Comment by Smittytron** [comment]
I have no plans for an additional medic nerf at this time.

When you build a large number of medics you are trading a considerable amount of dps for healing. This makes high medic infantry compositions more vulnerable to concentrations of heavy armor and to air attack, as there are less rockets than normal. Additionally, they still can't out-heal hits from artillery and V2s. If you lose to this composition, it is most likely you were way behind already, as is the case of the above video. Also, note that the pink player was still receiving bounties from pillbox shots; I counted 4 of 6 shots killing infantry.

**Comment by pchote** [comment]
Removing the AOE healing, and having it target one unit at a time, would make more sense than involving conditions or cooldowns.

**Comment by abcdefg30** [comment]
Balance changed much since 2017 and this does not seem to be part of the current debate.
