### ISSUE TITLE
Mistake at start release-20170527

### ISSUE THREAD

**Issue by RA23** [OpenRA/OpenRA#14078]
OpenRA has encountered a fatal error and must close. Logs:

exception-2017-09-27T054301Z.log
```Date: 2017-09-27 05:43:01Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.36403
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
   в OpenRA.Game.Initialize(Arguments args)
   в OpenRA.Program.Run(String[] args)
   в OpenRA.Program.Main(String[] args)
```
graphics.log
```System.InvalidOperationException: Can not create OpenGL context. (Error: Invalid window)
   в OpenRA.Platforms.Default.Sdl2GraphicsDevice..ctor(Size windowSize, WindowMode windowMode)
   в OpenRA.Platforms.Default.DefaultPlatform.CreateGraphics(Size size, WindowMode windowMode)
   в OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings)
   в OpenRA.Game.Initialize(Arguments args)
System.InvalidOperationException: Can not create OpenGL context. (Error: Invalid window)
   в OpenRA.Platforms.Default.Sdl2GraphicsDevice..ctor(Size windowSize, WindowMode windowMode)
   в OpenRA.Platforms.Default.DefaultPlatform.CreateGraphics(Size size, WindowMode windowMode)
   в OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings)
   в OpenRA.Game.Initialize(Arguments args)
```

**Comment by Elizadmin** [comment]
`Can not create OpenGL context. (Error: Invalid window)` has been seen in #10597 and #12401 but there is no clue.

**Comment by abcdefg30** [comment]
Looks like this is the same issue as #12313.
From https://github.com/OpenRA/OpenRA/issues/12313#issuecomment-257073001:
> OpenRA now requires at least version 4.5 of the .NET framework, looks like you are on 4.0. Can grab it [here](https://www.microsoft.com/en-ca/download/details.aspx?id=42642).

**Comment by pchote** [comment]
The installer should be preventing people from installing if they don't have .NET 4.5.

**Comment by cjshmyr** [comment]
@abcdefg30 - my comment was incorrect and runtime is not indicative of the .NET FW version -- [more here](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/versions-and-dependencies).

**Comment by GraionDilach** [comment]
It could be #12300.

**Comment by RA23** [comment]
thx, reinstal driver

**Comment by abcdefg30** [comment]
Ok, good to hear the problem is resolved.
