### ISSUE TITLE
Experience gain adjustable for garrisoned infantry.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#14086]
This is mainly focused for TD all be it RA is affected as well. Have garrisoned infantry gain less experience then compared to outside of the garrisoned structures.

This would prevent quick rank ups while inside garrison buildings and enable some balance. I can use the pillbox as an example:

Pillbox kills two minigunners and gains a rank up. The pillbox will now do slightly more damage and fire faster. Pillbox kills another four minigunners. Ranks up and does more damage and fires faster now.

With adjustable experience gains it could take about 4-6 minigunner kills before it ranks up. I do prefer to keep their damage and fire rate increase as its a nice feature to have. Problem being is ranking up is far to quickly.

This goes in line with my future idea to have garrisonable Guard Towers.

**Comment by GraionDilach** [comment]
This could be done with Cargo applying a condition to passengers and combining that with the already existing GainsExperienceMultiplier.

**Comment by pchote** [comment]
#15066 added the backend support for implementing this.

**Comment by abcdefg30** [comment]
Infantry no longer gain exp when in pillboxes since #15907.
