### ISSUE TITLE
Units on defend stance trying to attack.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#14081]
When on defend stance units are attempting to attack despite their current stance and their range.

To see what I mean have an army of any kind. Let the enemy attack your army and with your own units selected hold down ALT. You will see target lines appearing on enemy units.

This is also apparent from current release.

**Comment by netnazgul** [comment]
Duplicating observations from unrelated closed issue:
> - units tend to alternate attacking and moving when under A-move command (my V2s fired their shot, then moved one cell, then tried to fire with no ammo, moved again etc.)
> - red lines act weird - some units showed their target not on an a-move point but specific enemies at the back of enemy blob which they tried to reach ignoring closer targets

**Comment by tovl** [comment]
Target lines are no longer shown for defend stance or attack-move autotargets so I think this can be closed.
