### ISSUE TITLE
OpenRA and proxy

### ISSUE THREAD

**Issue by RA23** [OpenRA/OpenRA#14087]
At the ambassador of start a game suggests to download content, but can't. Where to register proxy settings?

**Comment by RA23** [comment]
The message turns: "Fetching list of mirrors...."
then leaves: "Error: cannot connect to remote server"

**Comment by anjew175** [comment]
Is the content/map on http://resource.openra.net/ ?
If not it needs to be uploaded so that others can download it.

**Comment by RA23** [comment]
I have downloaded an installer (polsedny release) and have started a game - for start of a concrete game the program tries to download files, but can't. I think it because of proxy, where to set parameters for this purpose?

**Comment by abcdefg30** [comment]
https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/installer/downloads.yaml contains the location from where the game tries to load the mirror list (the URL after each `MirrorList:` node). I don't think that supports proxy settings. You could try downloading the content manually and placing the extracted files at the locations specified in the `downloads.yaml` file (link above).

**Comment by abcdefg30** [comment]
Looks like the packages at http://www.openra.net/packages/ra-quickinstall-mirrors.txt already contain everything you need. For reference, your content folder should look like this after extracting the files to `Documents\OpenRA\Content\ra\v2` (if the downloaded package doesn't already provide it in the correct subfolders):
```
Documents/OpenRA/Content/ra/v2>
│   allies.mix
│   conquer.mix
│   hires.mix
│   interior.mix
│   local.mix
│   lores.mix
│   russian.mix
│   scores.mix
│   snow.mix
│   sounds.mix
│   speech.mix
│   temperat.mix
│
├───cnc
│       desert.mix
│
├───expand
│       chrotnk1.aud
│       expand2.mix
│       fixit1.aud
│       hires1.mix
│       jburn1.aud
│       jchrge1.aud
│       jcrisp1.aud
│       jdance1.aud
│       jjuice1.aud
│       jjump1.aud
│       jlight1.aud
│       jpower1.aud
│       jshock1.aud
│       jyes1.aud
│       lores1.mix
│       madchrg2.aud
│       madexplo.aud
│       mboss1.aud
│       mhear1.aud
│       mhotdig1.aud
│       mhowdy1.aud
│       mhuh1.aud
│       mlaff1.aud
│       mrise1.aud
│       mwrench1.aud
│       myeehaw1.aud
│       myes1.aud
```

**Comment by pchote** [comment]
OpenRA will use the proxy settings defined in your OS network configuration.  Game-specific overrides aren't supported.

**Comment by abcdefg30** [comment]
Closing as resolved.
