### ISSUE TITLE
Redundant condition in SwallowActor.cs

### ISSUE THREAD

**Issue by GSonderling** [OpenRA/OpenRA#14091]
Full disclosure, it is possible that campaign mode actually uses this in some way. However, at very least in skirmish mode, this condition is unnecessary.

https://github.com/OpenRA/OpenRA/blob/64afe4cfdec6494758be82e9dd72b5c411388ba0/OpenRA.Mods.D2k/Activities/SwallowActor.cs#L152-L156

Since the `sandworm.WormInfo.ChanceToDisappear` has value of 100. the condition always evaluates to true and the worm always disappears. As I said, it is possible it has some use I'm not aware of, but from here it looks like waste of resources.

**Comment by Phrohdoh** [comment]
[`ChanceToDisappear`](https://github.com/OpenRA/OpenRA/blob/64afe4cfdec6494758be82e9dd72b5c411388ba0/OpenRA.Mods.D2k/Traits/Sandworm.cs#L31) can be set in mod and map rules (via yaml).

**Comment by GSonderling** [comment]
I suppose that makes sense. I will close the issue.
