### ISSUE TITLE
fix games with specs not showing up when the "waiting" filter is applied 

### ISSUE THREAD

**Issue by shpookys** [OpenRA/OpenRA#14097]
![screenshot_2017-10-01_05-59-25](https://user-images.githubusercontent.com/16250856/31054730-3a7a5264-a66e-11e7-85b1-82d4430976fa.png)
![screenshot_2017-10-01_05-59-38](https://user-images.githubusercontent.com/16250856/31054731-3b1b18b6-a66e-11e7-8fc7-3ee9dd3949a1.png)

**Comment by kstreser** [comment]
I could not replicate the bug anymore:
![Screenshot from 2024-05-06 09-20-30](https://github.com/OpenRA/OpenRA/assets/67750158/f2f25839-67b8-4419-9cbf-ea7df2b4de12)
![Screenshot from 2024-05-06 09-20-35](https://github.com/OpenRA/OpenRA/assets/67750158/f694f3c3-2c7b-4d15-9547-a28f9548de43)

This might got fixed.

I found something else. If you deselect all filters you see games with only spectators in it:
![Screenshot from 2024-05-06 09-21-21](https://github.com/OpenRA/OpenRA/assets/67750158/3efbc8a4-5026-45b6-9641-7b7ac16e84f1)

**Comment by kstreser** [comment]
#21420
