### ISSUE TITLE
Chinook For soviets Possible Solutions.

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#14100]
As we all know the poor soviets have no chinook to transport those handy engineers to that oil across the cliffs of denial. 

So i can think 3 solutions:
1 ) add helipad to the soviets.
2 ) add an "opening" animation to the airfield like in red alert 2 with the war factory.
3 ) just add prerequisites afld to the chinook.

_4 ) do the toxic talk again about the allied cobra\huey balance never ending debate and actually never find a solution for it! i am just kidding!_

**Comment by pchote** [comment]
5) accept that it is a map balance issue, and don't ship any maps that are deliberately skewed towards one faction.

**Comment by KOYK** [comment]
True, but this will limit any map strategy that can be made using natural barriers. and i don't think that asking map authors to limit their creativity in order to go along with this is the best way to go.

Not to mention that using the chinook transport as an allied only unit is in fact what you said, it does "skewed towards one faction." and that's the allied faction. 
How many times we have seen hordes of spy units suddenly get out of chinooks bypassing land barriers?

If you ask me about balance its better to remove the chinnok transport concept all to gather for all factions.  Or at least give it also to the soviets.

The allied factions all ready can get units in too many ways behind the enemy lines. while the soviets have only a simple paradrop. In my opinion you can't ask to have beauty and functionality in the same package with out some compromises so solution 3 seems to be the only way, if no one is willing to add a simple "door opening animation"

**Comment by abc013** [comment]
The map authors can remove the chinook / add it to the soviet faction in the map.yaml themselves if they want.

**Comment by KOYK** [comment]
The map authors can also add Godzilla, whats your point? i am talking about ra it self not what map authors can add or not. You are confusing my answer to pchote about his solution, with my argument of balance that it has nothing to do with making maps.

**Comment by GraionDilach** [comment]
It's either the map author's either the mod maintainer's job (when uit gets included in the mod officially) to provide accessibility to positions required. Mental Omega axed and reworked a lot of maps before including them among it's own to make sure such island accessibility issues will be resolved - the Soviet transport there is amphibious, but a lot of maps used water cliffs around the water surrounding the tech building's island, so some of the water cliffs needed to be replaced with water slopes.

Your argument is void.

**Comment by KOYK** [comment]
You are right! Westwood studios made a terrible mistake adding the chinook to the soviets in the first place, but what do they know? I mean its not like they made any good games to have any experience right? 

Sarcasm aside, so you think that instead of adding the chinook, we should change to EA square like soulless map designs that actually force balance to the gameplay by being too unimaginative, whats next? turn ra in to tetris? oh wait some one already done that http://media.moddb.com/images/games/1/15/14718/ptvXyj9_-_Imgur.gif

If you want balance to blend with fun, you will need smart ways to do it, and not "axe" down the fun part, otherwise you downgrading the game. mental omega is not ra1 so you comparing apples and oranges here.

My argument might be void for your standards, but at least i don't "axe" down difficult problems that i can't find a solution for them, instead i am trying  to think some short of compromising, what are **you** doing? (and i am not trying to be hostile here, i just want to provoke you on thinking an actual solution rather than dismissing the idea)

And by they way none of you said any thing about why there it shouldn't be a chinnok for soviets, all i hear so far is map author this and map author that.

Come on work this problem with me other wise ill start thinking that the whole thing is a feng shui helis vs planes obsession you have.

**Comment by scskwirl** [comment]
This post made me think... But it'd take some serious SHP work.

Both factions can have helipads. One with the +, one with the H. For aesthetic. Both can also have airfields but have fun figuring out how to differentiate.

Give the Allies something like a Huey, which can only transport say 5 infantry, and at least 1 weapon infantry gives it a small machine gun like the jeep. But at least they're cheap enough to fly a small swarm in. If a group are deployed as selected, they all deploy.

Give the Soviets the Chinook. It can carry 10 infantry or X amount of vehicles depending on their size I guess (ie: packing in mammoth tanks would be insane). Slightly more expensive for the accommodations. But no guns like the huey can.

Give the soviets their hind back, allies keep the longbow. Soviets can keep Yak and MIG, while Allies could get their own plane with both the machine guns and the missiles, used in separate setups.

Helicopters should only be able to do Air-to-Ground, while aircraft can do either that or Air-to-Air, to do things like air superiority, dogfighting, etc.

**Comment by netnazgul** [comment]
What if we just somehow have customized paradrops? Paradrop is an alternative to chinook as it is btw.

**Comment by pchote** [comment]
I have no philosophical objections to giving the soviets back the helipad, chinook, and Hind.  What i *do* object to is the practical implications of dealing with the fallout from radically changing the game balance, and dealing with the community protests that would certainly come with this.

**Comment by KOYK** [comment]
@pchote What if you post a poll in http://www.openra.net/ and depending on the comments there later add it on a playtest? 
Every time a new version comes out, the section in http://www.openra.net/ is floated with comments, that means a lot of openra players or all of them are going to see it, i know it sounds unprofessional but then the issue it self has been heavy in discussions and it comes out a lot of times.

@netnazgul that indeed sounds interesting, its like ra3 logic. And can be added as a trait any way for other mods if not for this, you might need to do a separated issue about it any way.

@scskwirl adding **attacking** helis to both factions has been all ready discussed here:
https://github.com/OpenRA/OpenRA/pull/12836
And
https://github.com/OpenRA/OpenRA/pull/12831
And the result in the end was to make people angry at one an other.

**Comment by pchote** [comment]
It's not as simple as "just adding it to a playtest".  Somebody would need to take responsibility for rebalancing the whole game as part of this, and I do not see that happening.

**Comment by Smittytron** [comment]
I doubt this will be a satisfying answer but in the interest of information sharing I’ll try to explain why the competitive community would oppose this move.

- The entire point of having factions is to add flavor into the game. Factions need to have different units that are good at different things. When you give two factions the same unit, this dilutes the experience.

- When you give both factions a unit that was specific to one, you take away an advantage that faction had. After the pillbox nerf/flametower buff, this game has actually been in a relatively happy place in terms of win rate between Allies and Soviets. There are still some glaring issues (GPS for one) that inhibit fun gameplay, and I intend to pursue those in the next round of playtesting. That said, we are closing in on a point where major changes against one faction or the other make little sense in terms of adding to the gameplay experience.

- Allies currently lack vehicle versatility in the late game compared to Soviets. Combat vehicle options for allies are typically reduced to Medium Tanks and Artillery, while APCs, Flak Trucks, Heavy Tanks, V2s and Mammoth Tanks are all viable options for the Soviet player. With mobile AA, APCs, yaks, and paratroopers, Soviets have an easier time getting into the back lines of an opponent than an allied player does. 

- The APC is far and away a better drop unit than the chinook, as it also has utility as a frontline combat unit. When you are building a Chinook you are sacrificing time that could be used to build Hinds. As Soviets are not lacking in this department, it makes little sense to remove the small advantages the chinook gives to an allied player. 

> How many times we have seen hordes of spy units suddenly get out of chinooks bypassing land barriers? 

Not even remotely close to the amount of times I’ve seen a successful APC drop.

**Comment by KOYK** [comment]
@pchote I understand your point of view and i agree, but then again doesn't rebalancing also needs playtesting? isn't @soscared the test "driver" here on ra? he might do it if he's interested.

Any way i say lets leave this open for any one that is willing to add something "that will actually help to bring this thing to an end" to quote the song Act on instinct :p

**Comment by KOYK** [comment]
It wont be fixed\added, closing it.
