### ISSUE TITLE
Making "privateer" actors?

### ISSUE THREAD

**Issue by scskwirl** [OpenRA/OpenRA#14103]
I apologize in advance if something like this was brought up already; I don't know how other people would phrase what I'm describing. I've also been very out-of-the-loop with OpenRA lately, sadly.

What I mean by "privateer" (and there's probably a better name) is like, making units that use a color unused by anyone playing in the match, so you don't know who sent them to you. For example, Red vs Blue vs Green. Privateer units would be gray. Gray units end up attacking one of those teams, but they won't know which team sent them, unless something gives it away, like what kind of unit besides riflemen.

This would only especially be useful in diplomacy-powered matches, where alliances can be switched around between players; allowing allies to attack each other.

Alternatively, units color-disguised as any of the other teams. Put on a large map, also with diplomacy settings, you can make the other team decide to switch against their partners (at least useful enough for creative game tactics with AI players rather than human ones).

**Comment by KOYK** [comment]
civ3? well i like the idea but not for RA or TD. But it will be a nice trait for other mods.

**Comment by abcdefg30** [comment]
This can be done by a custom map/mod, but I don't see this implemented as default game mode.
