### ISSUE TITLE
Two yaks landing on one air field

### ISSUE THREAD

**Issue by senneschall** [OpenRA/OpenRA#14114]
[OpenRA-2017-10-04T192055Z.orarep.zip](https://github.com/OpenRA/OpenRA/files/1357169/OpenRA-2017-10-04T192055Z.orarep.zip)

While I was trying to find out the cause of #14102 I noticed that two yaks were landing and reloading on the same air field the same time.

It happens in the replay at ~11:45.
release-20170527

**Comment by netnazgul** [comment]
I think this specific bug should have been fixed in playtest already.

**Comment by fruestueck** [comment]
Bug confirmed on Releasse-180218. It does show wrong minimap cursers of multiple units and tasks.
Engeneer works (infiltrate on Map and on Minimap correct).

This bug (or yet not implemented distinction) concerns Air Units, Vehicles (Repair symbol), Spys & Mechanics (infiltrate), Ships (Repair symbol on own yard when damaged) and more. See example picture

![unbenannt](https://user-images.githubusercontent.com/25386322/37053235-df647c4a-217b-11e8-91bc-1044f0733d47.png)
