### ISSUE TITLE
Remove auto-target into fog of war from GPS

### ISSUE THREAD

**Issue by Smittytron** [OpenRA/OpenRA#14115]
There is a general consensus among competitive players that GPS has a negative impact on gameplay in its current state. One suggestion that has been touted by myself and others is to remove the ability for units to see and therefore auto attack into the fog of war at gpsdots. 

It can get silly for artillery to auto fire at assembling units long before their commander even notices what's going on. Also, as many RA units have greater firing range than their vision range, an allied player with GPS will get free shots off in most engagements. Tanya in particular can wreak havoc un-escorted with a simple A-move vs infantry dots.

Related forum post: http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=20298&sid=7e3ec7f1fa9128dba116684efb44c997

**Comment by CannotPrinter** [comment]
Instead of looking at Allies, could Soviets build something? What about the **Forward Command Post**? Give it a Radius and "Advanced Radar". Would give the structure meaning and it is a Soviet thing. 

No re-writing needed of GPS. Existing asset used.
