### ISSUE TITLE
Poor performance on ARM Chromebook running Linux

### ISSUE THREAD

**Issue by duckdodger** [OpenRA/OpenRA#14126]
Hello, so I've been trying to get OpenRA running on my Arch Linux installation on an SD card in my Asus C201 chromebook which is powered by an ARM Rockchip RK3288 SoC ([specs here](https://en.wikipedia.org/wiki/Rockchip_RK3288)) with a Mali T760 (MP4) GPU, and I'm using the Chrome OS kernel along with the Mali drivers. The game actually runs but it's incredibly slow. I learned that the Mali GPU in my system supports only OpenGL ES while OpenRA uses standard OpenGL. I would like to know whether or not it's possible to make OpenRA use OpenGL ES rendering. If you'd like some more information, I'd be happy to provide as necessary because I don't know what else to tell myself. I know at least that my device is more than capable of running this game provided it uses the proper drivers and rendering, because I'm able to run much more demanding 3D Android games from the Play Store on Chrome OS.

I realise this is a very niche problem, but I don't think it's unreasonable to hope that something can be done about this? :) I used to play this game on my desktop with some friends and I loved it, but now I'm stuck with just this Chromebook far away from my desktop.

**Comment by GraionDilach** [comment]
Pretty sure performance isn't problematic because GPU alone. 1.8 GHz is pretty low - OpenRA is a heavy resource hog.

**Comment by Icenowy** [comment]
For GPU support you may try https://github.com/ptitSeb/gl4es , which is a GLES-GL translation layer that is capable of running OpenRA now (and the author just uses OpenRA as a test to its GL2 support).

**Comment by pchote** [comment]
https://github.com/pchote/openra/tree/gles2 is an old experimental branch that adds GLES2 support to OpenRA.

**Comment by duckdodger** [comment]
@Icenowy Thanks, it looks interesting! I'll see what I can do with it and will report back.
@pchote That's great, I'll check if it's performant with this version, but how do I get GLES2 support for the latest versions of the game?

**Comment by abcdefg30** [comment]
I don't think there is more to do here.
