### ISSUE TITLE
Infantry Squad Unit Trait

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#14148]
Instead of exporting, editing, importing shp files. Why not add a trait that will allow for infantry units to move\stay in the same cell? so for example you want to add a sniper team, instead of doing all the animations & rules editing and have your head explode you could add this trait and get a new "squad" unit.

Could be like this:
```
	Squad:
		SquadUnits: sniper, spotter
		ShareDamage: false
		SpawnMembersOnHeal: false
		SpawnAnimation: 
		SpawnPosition: 0c100
		ShareRank: true
		PassengerWeight: 2
```
Something like this

**Comment by MustaphaTR** [comment]
I'm not sure if exactly what you want, but @forcecore's mod already have a similar logic.

Both stuff shown here uses same logic:
https://youtu.be/I249G5FxbPQ
https://youtu.be/8TE6k6P_NEg

**Comment by KOYK** [comment]
Yes that's a good example of what i am saying, but i can't find any trait related to this in the trait wiki, so i assume this is only for that mod? if that's the case then maybe implement it in the main openra build as well?

**Comment by MustaphaTR** [comment]
Yes, it is not in main OpenRA dlls. What i was trying to say is we already have a working code if someone can port it here.

**Comment by pchote** [comment]
Or you could use that DLL in your mod directly.

**Comment by KOYK** [comment]
pchote i would need permission to do that and i don't think that will happen. and this is a good feature any way.

**Comment by pchote** [comment]
The GPL license explicitly grants you permission to do so.  I am just offering a suggestion to help you in the short term, because I do not expect this feature to be implemented upstream.

**Comment by KOYK** [comment]
pchote thank you. 
Well now its a moral thing :p, i mean it feels like stealing some how, ill ask for permission any way.

**Comment by MustaphaTR** [comment]
I use a modified version of @forcecore's dll too, which is in fact a modified version of @GraionDilach's AS dll. As pchote said they are licenced in a way to allow you to use.

Angry Mob logic, along with Carrier, Slave Miner, Shootable Missile (RA2 V3) uses same base logic on that dll. Thinking that we need at least 2 of those for RA2 mod, adding them to here may be good. But as pchote said, there is really low to no chance it'll be implemented in short time.

**Comment by KOYK** [comment]
Hmm i get the picture, ok thanks

**Comment by forcecore** [comment]
@KOYK As discussed above, ORA engine and thus my stuff that are built upon it are GPL and does not require permission to copy, modify and/or distribute.

**Comment by GraionDilach** [comment]
@pchote IIRC the DLL alone isn't enough by now - mob logic required edits in Mods.Common as well. One would need to use the entire fork.

**Comment by KOYK** [comment]
@forcecore Thank you any way!

**Comment by KOYK** [comment]
It wont be fixed\added, closing it.
