### ISSUE TITLE
Spectators show as "Ally" in team chat

### ISSUE THREAD

**Issue by oraservers** [OpenRA/OpenRA#14140]
If a player in a lobby selects a team, and then subsequently switches to being a spectator, that spectator's chat messages will show as (Ally) to players with that same team value.

**Comment by dragunoff** [comment]
That player also keeps his color in chat messages as opposed to having neutral white color (even if not on a team). To reproduce - join a MP game, click "Play in this slot" and then switch to "Spectate". IIRC this label change is only visible in game and not in replays.

**Comment by rob-v** [comment]
Seems already fixed in dev version?

![image](https://user-images.githubusercontent.com/16348750/31743926-2f1050de-b45d-11e7-904c-e18e49e98665.png)

**Comment by rob-v** [comment]
When player switches to Spectator and back - should player keep previous Team number or better to always reset it to No team when switching to Spectator? (I can solve this issue by Team reset or ignoring Team number in chat). Let me know please.

**Comment by pchote** [comment]
Clearing the team when becoming a spec seems like the most reasonable option to me.
