### ISSUE TITLE
Server password stored in plain text in replay file

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#14157]
If you want to know the password to a server you just need to open a replay file in a text editor.

**Comment by pchote** [comment]
Replays are a log of the raw network traffic.  This is known, and can't/won't be fixed.

#2265 would allow server operators to whitelist specific players instead of relying on passwords.

**Comment by antzpantz** [comment]
Hi there, I had a look at the .orarep Replay file out of curiosity and noticed that it stores the server password in it in plain-text. Is this necessary information to store or record? And possibly even the AuthToken which I'm guessing is required to connect to the server?

And why won't it be fixed?

**Comment by antzpantz** [comment]
As far as I can tell, the HandshakeRequest and HandshakeResponse packets don't need to be recorded in the replay. I removed those packets from the .orarep file and the Replay played back fine. Though having the IPs stripped from each client info would be nice too.
