### ISSUE TITLE
TS disc grenades don't explode when hitting enemy building

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#14151]
Might be related to recent footprint refactor.

**Comment by alercah** [comment]
Is this just referring to the animation, or also to the damage? After applying the changes in #14742, I don't see explosions from the discs that hit buildings, but I do see them on units and they still damage the buildings.

**Comment by alercah** [comment]
Okay, this is interesting: the grenades sail through my own buildings on force-attack and explode on the other side, but hit enemy buildings fine. I'll try on bleed and see if that makes a difference.

**Comment by pchote** [comment]
That is how they are supposed to work IIRC (compare with the original game).

**Comment by alercah** [comment]
Ah ok. I guess that is just to reduce friendly fire, which makes sense. Weird, but ok.

(I don't have a copy of TS :( )

**Comment by MustaphaTR** [comment]
TS is freeware, you can just grab it from https://cncnet.org/ for free.

**Comment by alercah** [comment]
Looks like on bleed, the behaviour for enemy buildings is like with allied buildings, the discs sail right through. On my branch, however, they hit normally. After more investigations, the explosions not appearing simply seems to be that they are z-ordered behind the building if they hit from above, so you can't see them easily. I'm not sure if that's good or bad, but I'm confident enough to say that #14742 fixes this bug.
