### ISSUE TITLE
More linux friendly developing please

### ISSUE THREAD

**Issue by Kosti1** [OpenRA/OpenRA#14169]
An arch user here, we need more Linux friendly developing and modding
*also how many of the devs are using linux?*

**Comment by Micr0Bit** [comment]
could you specify your issue ?

**Comment by Kosti1** [comment]
Monodevelop crashes everytime I try to open the solution

**Comment by pchote** [comment]
The majority of OpenRA development is/has been done using MonoDevelop on linux or macOS.  It sounds like your distribution is just shipping broken mono packages.

You can follow the instructions at http://www.mono-project.com/download/#download-lin to get the latest versions directly from xamarin.

**Comment by Kosti1** [comment]
Kinda hard to have a broken mono when using arch linux

**Comment by Fincer** [comment]
Any debug information would be valuable. Also, which version of Mono do you use? Consider updating with `pacman` or compile Mono from source using PKGBUILD script.

https://www.archlinux.org/packages/extra/i686/mono/

https://www.archlinux.org/packages/extra/x86_64/mono/

These packages are outdated, however. Newest version is `5.4.0.201` at the moment. You should consider compiling Mono yourself.

1. Download PKGBUILD script+stuff (contents of the "trunk" folder is what you want):

https://git.archlinux.org/svntogit/packages.git/snapshot/packages-f468e07235691e8e5ba1ee3f01ced2e3363c96cf.tar.gz

2. Edit `pkgver` string in PKGBUILD and try to compile using `updpkgsums && makepkg` in the same folder where your PKGBUILD locates at. If compilation fails, there's a possibility that some of the included patches may not work or something else is an issue.

3. After successful compilation, install compiled mymonopkg.tar.xz package with `pacman -U mymonopkg.tar.xz` command.

4. Re-configure / Re-install / Re-compile your OpenRA installation and try to launch the game.

**Comment by GSonderling** [comment]
Run monodevelop from shell with verbose argument. That should give you log with exact error message. Than you just copy and paste it here. Or in monodevelop project, it depends on what exactly is the issue.


If you can, you should also enable file log for monodevelop. MONODEVELOP_LOG_FILE is the system variable you need to set. Default settings should be more than enough.

**Comment by Mailaender** [comment]
Sadly @Xamarin was bought by @Microsoft and oh wonder suddenly Linux isn't the focus anymore. I suggest to use the containerized MonoDevelop build from http://www.monodevelop.com/download/linux/ which works although it has many regressions compared to the native builds we had before.

Some upstream reports:
* https://bugzilla.xamarin.com/show_bug.cgi?id=59542
* https://bugzilla.xamarin.com/show_bug.cgi?id=51534

Closing here and pinging @directhex.

**Comment by Mailaender** [comment]
Also created https://en.opensuse.org/MonoDevelop and pinging @sysrich as we are facing a problem here, which needs to be handled on higher levels as well.

**Comment by za267** [comment]
I know this problem is closed but I thought I would add a comment anyway - I was facing exactly the same issue on Fedora 27 - seems my version of monodevelop (from the fedora repos) was packaged for Fedora 26.

Using the flatpak version of monodevelop, as recommended by mailaender, works perfectly well.
