### ISSUE TITLE
Error when opening OpenRA.Game.exe for the first time

### ISSUE THREAD

**Issue by CalumGM** [OpenRA/OpenRA#14160]
im not sure if this is only a first launch problem, but when i try to open the game the screen flashes white twice then nothing. I checked the error logs and found "System.InvalidOperationException: Can't create OpenAL device" in the graphics.log file. 
Thanks in advance

**Comment by abcdefg30** [comment]
https://github.com/OpenRA/OpenRA/issues/12526#issuecomment-269819152 suggest that you look at your sound output. IIRC people managed to 'fix' this issue by using earphones in the past.

**Comment by DevJarmo** [comment]
I have the same issue on Mac OS Mojave 10.14.2. Screen flickers and then crashes. I tried using external head phones and external speakers.

**Comment by DevJarmo** [comment]
For me... looks like installing Xcode and rebooting fixed the problem.

**Comment by abcdefg30** [comment]
Closing as fixed then, there does not seem anything to do here.
