### ISSUE TITLE
Move kennel up buildpaletteorder

### ISSUE THREAD

**Issue by anjew175** [OpenRA/OpenRA#14171]
Would be nice to keep the buildpaletteorders consistent. Right now it sits at the very end of the order despite being available straight after powerplant

**Comment by FrameLimiter** [comment]
Related: #10577

**Comment by MustaphaTR** [comment]
It was moved below to keep shortcurts same between factions, even as someone who doesn't use keyboard shortcuts, i think current behaviour is better.

**Comment by pchote** [comment]
I agree with @MustaphaTR: IMO the current behaviour is the least bad of the two bad options.

**Comment by AndriiYukhymchak** [comment]
move kennel to support building queue

**Comment by matjaeck** [comment]
The feedback here suggests that the requested change is unlikely to happen, so voting for closing to clean up the issue tracker.
