### ISSUE TITLE
Disguised spies have no attack animation if the disguise lacks a shoot sequence

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#14170]
If you disguise your Spy as an e2, medi, mech, e6, hijacker, or zombie the Spy will have no attack animation when firing his gun.

**Comment by abc013** [comment]
The spy gets revealed before he fires his weapon (what means that the attack sequence is always the spy ones).

**Comment by FrameLimiter** [comment]
He'll drop his disguise and shoot, however unless the disguise used was of an actor with a defined shoot sequence, the Spy won't utilize his own shoot animation.

If for example you add "shoot" to the medic:
Sequences:
->medi:
-->shoot:
--->Start: 56
--->Length: 58
--->Tick: 120

It'll resolve the issue when using a medic as a disguise. However this would likely be the improper way to fix the issue.

**Comment by pchote** [comment]
#14059 adds the plumbing to remove `WithDisguisingInfantryBody` completely, which would have a side-effect of fixing this bug.

**Comment by Smittytron** [comment]
Tested and this is fixed now.
