### ISSUE TITLE
No icon for OpenRA app in Windows taskbar

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#14174]
Issue is reproduced on both Windows 10 and Windows 8.1
![unknown](https://user-images.githubusercontent.com/1614714/31577215-345c5634-b113-11e7-8308-bbb41b6d4d8f.png)
![image](https://user-images.githubusercontent.com/1614714/31577219-49f39f34-b113-11e7-97b2-502c2f8f0dee.png)

However, as @pchote stated, it does show in his Windows configuration.
![f4ote30](https://user-images.githubusercontent.com/1614714/31577209-2c883608-b113-11e7-9daf-18a45a0da620.png)

**Comment by pchote** [comment]
This is the code responsible for setting the icon:

https://github.com/OpenRA/OpenRA/blob/f2b5040d309818d817fa25a3e81e0d75ef0b8ca2/packaging/windows/WindowsLauncher.cs.in#L96-L106

It would be helpful if somebody who can reproduce the problem is able to debug this and report what is going wrong.

**Comment by reaperrr** [comment]
Seems to work on Win7, so 8+ must be doing something different.

**Comment by MustaphaTR** [comment]
I'm on Win7, it doesn't work for me.

**Comment by netnazgul** [comment]
Somehow today the icon finally shows up for me... Strange bug

**Comment by netnazgul** [comment]
upd: Still happening sporadically. More times there is a generic icon, only seen the correct icon 2-3 times.

**Comment by dragunoff** [comment]
This is also the case on my Windows 7 machine - the taskbar icon is a generic one.

**Comment by penev92** [comment]
Sounds serious enough, we should try to get it fixed for the next release.

**Comment by Unit158** [comment]
Seems to be related to packaging. This occurs on my compiled version but not my installed release.

**Comment by pchote** [comment]
@Unit158: Just to clarify, are you manually compiling and running the `RedAlert.exe` etc, or just running through your IDE?  Not showing an icon when running OpenRA.Game.exe directly is deliberate, and different to the issue here.

**Comment by Unit158** [comment]
Ah, I suppose I'm running OpenRA.Game.exe directly (when compiling) in that case :)

**Comment by pchote** [comment]
There is no way to fix this without a repro case, so removing from the milestone.

**Comment by penev92** [comment]
Since I now have a PR ready for this I think we should still prioritize this for a playtest.

**Comment by netnazgul** [comment]
@penev92 if you point me to a buildable bleed I can download I can test it on my machine

**Comment by pchote** [comment]
@netnazgul: The launchers can't be built on windows, so here is an installer: https://www.dropbox.com/s/cbgp6kk9nqmheo8/OpenRA-packagetest-20171129.exe?dl=0
