### ISSUE TITLE
Strange change to "Vulcan" weapon (smallcaliber.yaml)

### ISSUE THREAD

**Issue by theKalash** [OpenRA/OpenRA#14185]
The weapon features 6 different "Warhead" attributes that deal damage. 

With the last patch a single one of these (Warhead@4Dam_2) had it's damage reduced vs "light" from 60% to 50% while the other 5 remain at 60%

Intentionally or where the other warheads overlooked?

**Comment by SoScared** [comment]
Overlooked. All warheads should have had their values changed to 60 vs Light.

**Comment by theKalash** [comment]
Oh yeah, the other way around.
