### ISSUE TITLE
Submerged units are not targets for submarines, on attack move and aggressive stances

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#14195]
Only situation : subs vs subs / missile subs.
In the following situations : 
- hold fire + attack move
- defence stance
- attack anything stance, 
player's subs won't attack enemy underwater subs (or missile subs).

When enemy subs / missile subs surface for some reason, then stances are taken into account. 

Tested with AoAGeneral, replay available.

**Comment by FRenzy-OpenRA** [comment]
Btw, tested also stealth units (Phase, Stealth Tank) : no bugs with them, stances seem to work correctly.
Only related to submerged units.

**Comment by AndriiYukhymchak** [comment]
Submarines have only water as valid target for stances in its ruleset. Was submerged omitted on purpose or was that an error?

**Comment by pchote** [comment]
It was an error.  Too bad that this wasn't reported during the playtests.

**Comment by andrii-yukhymchak** [comment]
on it

**Comment by FRenzy-OpenRA** [comment]
See  #14197 too

**Comment by theKalash** [comment]
Yep ... you can fix it by going to the ship.yaml and changing 

	AutoTargetPriority@DEFAULT:
		RequiresCondition: !stance-attackanything
		ValidTargets: Water

to 

		ValidTargets: Water, Underwater

**Comment by AndriiYukhymchak** [comment]
already @theKalash in #14198
