### ISSUE TITLE
Air units either attacking once, then quitting, or not attacking at all

### ISSUE THREAD

**Issue by SmittyShitDevs** [OpenRA/OpenRA#14193]
Air units, especially planes, will either attack once then just keep flying or fly in circles, or do nothing at all and fly in circles. Stances, and various methods of attack, don't seem to remedy this. At all.

**Comment by FRenzy-OpenRA** [comment]
Problem reproduced with airplanes : 
- on aggressive stances, they don't engage enemy
- after A-move, they acquire a target. If the target is killed, and another target is inbound, they'll start shooting the 2nd target. If there's no other target, plane will become idle, and if a new target comes afterwards, plane will stay idle, regardless of stance. 

Helis have no problem with stances.

**Comment by AndriiYukhymchak** [comment]
Checking this out. Probably issue with FlyCircle being... you know... not Idle

**Comment by matjaeck** [comment]
Stances are still an issue in release-20190314. Airplanes do not seem to care/know about them at all.
