### ISSUE TITLE
Submerged units can't be damaged by most weapons, even if revealed by boats

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#14197]
While units are submerged, even if they are revealed, most weapons don't deal damage. Only anti-underwater weapons do. 

For instance, a cruiser or a missile sub don't do damage. Neither grounds units (rocket soldiers, ...)

Although it might be a realistic behaviour IRL, it feels frustating in-game, and might need to be fixed. 

Might be related to  #14195
Also see  #14054

**Comment by abcdefg30** [comment]
Looks like this is intentional: #14054

**Comment by AndriiYukhymchak** [comment]
This is definitely intentional.

**Comment by abcdefg30** [comment]
Closing as discussed on IRC.
