### ISSUE TITLE
System.InvalidOperationException : Attempting to query the position of an invalid Target

### ISSUE THREAD

**Issue by Elizadmin** [OpenRA/OpenRA#14190]
We were eight players in the lobby and we all crashed when the game started.

__exception-2017-10-15T201722Z.log :__
OpenRA engine version release-20171014
Red Alert mod version release-20171014
on map 1e564d4e237e598bbb8412a53485267b71aa60b4 (The Desert Fox by Aneyrin).
Date: 2017-10-15 20:17:22Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Attempting to query the position of an invalid Target
   à OpenRA.Traits.Target.get_CenterPosition()
   à OpenRA.Mods.Common.Traits.AttackBomber.OpenRA.Traits.ITick.Tick(Actor self)
   à OpenRA.World.<Tick>m__3(TraitPair`1 x)
   à OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   à OpenRA.World.Tick()
   à OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   à OpenRA.Game.LogicTick()
   à OpenRA.Game.Loop()
   à OpenRA.Game.Run()
   à OpenRA.Program.Run(String[] args)
   à OpenRA.Program.Main(String[] args)

**Comment by pchote** [comment]
[The map](http://resource.openra.net/maps/23274) appears to have pre-placed badger bombers in the map editor.  This isn't supported - actors with the `AttackBomber` trait *must* be spawned by the game.  The map author can fix the problem by creating a new actor type that inherits from the badger and removes the `AttackBomber` trait.

Closing as a custom map issue.
