### ISSUE TITLE
[Suggestion] Option to disable build radius

### ISSUE THREAD

**Issue by Kosti1** [OpenRA/OpenRA#14203]
Just an option in options tab for disabling build radius

**Comment by AndriiYukhymchak** [comment]
You mean in new game settings? Or you don't want to see the UI?

**Comment by Kosti1** [comment]
I just want to have an option to disable the build radius so I can make my base bigger

**Comment by AndriiYukhymchak** [comment]
So game setting

**Comment by Kosti1** [comment]
yeah

**Comment by AndriiYukhymchak** [comment]
You don't want to play multiplayer game with this setting on, trust me. However this can be extended to a set of mutators for game that can be applied on any map, instead of changing the map (which is the way you should take I'd you want that for yourself)

**Comment by Kosti1** [comment]
I want it

**Comment by GraionDilach** [comment]
See #9422 regarding mutators.

**Comment by Kosti1** [comment]
well I added this myself to my mod

**Comment by Kosti1** [comment]
I made a pull request #14209 that implements this

**Comment by MustaphaTR** [comment]
#14209 is merged, i guess this can be closed.
