### ISSUE TITLE
[FEATURE REQUEST] Civilian Shipyard for RA mod

### ISSUE THREAD

**Issue by NethIafin** [OpenRA/OpenRA#14217]
Some maps I have in mind would like to have a civilian shipyard. A 1x1 - 1x2 building with enough health (around 1-2 health pools of a derrick). This building should be capturable from shoreline with engineer, but at the same submerged in water with 4 exits on each side (which can be blocked by shoreline). This building should be able to build ONLY transport ships and they will be very useful on maps without dedicated naval "sea" but that have some amount of rivers. Also I see them providing incentive to go for sea combat, since they allow you essentially free transportation over water

**Comment by abcdefg30** [comment]
This is supported for custom maps.
