### ISSUE TITLE
OpenGL-related client crash

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#14211]
Client crashes on game start or after game end.

Some logs

> OpenRA engine version release-20171014
> Red Alert mod version release-20171014
> Date: 2017-10-18 17:07:23Z
> Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
> Runtime Version: .NET CLR 4.0.30319.42000
> Exception of type System.InvalidOperationException: OpenGL Error: See graphics.log for details.
> в OpenRA.Platforms.Default.OpenGL.CheckGLError()
> в OpenRA.Platforms.Default.Texture.GetData()
> в OpenRA.Graphics.Sheet.CreateBuffer()
> в OpenRA.Graphics.SequenceProvider.Preload()
> в OpenRA.Map.PostInit()
> в OpenRA.Map..ctor(ModData modData, IReadOnlyPackage package)
> в OpenRA.ModData.PrepareMap(String uid)
> в OpenRA.Game.StartGame(String mapUID, WorldType type)
> в OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
> в OpenRA.Network.OrderManager.TickImmediate()
> в OpenRA.Sync.<CheckSyncUnchanged>cAnonStorey0.<>m0()
> в OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
> в OpenRA.Sync.CheckSyncUnchanged(World world, Action fn)
> в OpenRA.Game.InnerLogicTick(OrderManager orderManager)
> в OpenRA.Game.LogicTick()
> в OpenRA.Game.Loop()
> в OpenRA.Game.Run()
> в OpenRA.Program.Run(String[] args)
> в OpenRA.Program.Main(String[] args)

Graphics.log
> GL Error: 1282
> в OpenRA.Platforms.Default.OpenGL.CheckGLError()
> в OpenRA.Platforms.Default.Texture.GetData()
> в OpenRA.Graphics.Sheet.CreateBuffer()
> в OpenRA.Graphics.SequenceProvider.Preload()
> в OpenRA.Map.PostInit()
> в OpenRA.Map..ctor(ModData modData, IReadOnlyPackage package)
> в OpenRA.ModData.PrepareMap(String uid)
> в OpenRA.Game.StartGame(String mapUID, WorldType type)
> в OpenRA.Network.UnitOrders.ProcessOrder(OrderManager orderManager, World world, Int32 clientId, Order order)
> в OpenRA.Network.OrderManager.TickImmediate()
> в OpenRA.Sync.<CheckSyncUnchanged>cAnonStorey0.<>m0()
> в OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
> в OpenRA.Sync.CheckSyncUnchanged(World world, Action fn)
> в OpenRA.Game.InnerLogicTick(OrderManager orderManager)
> в OpenRA.Game.LogicTick()
> в OpenRA.Game.Loop()
> в OpenRA.Game.Run()
> в OpenRA.Program.Run(String[] args)
> в OpenRA.Program.Main(String[] args)
>  
> OpenGL Information:
> Vendor: NVIDIA Corporation
> Renderer: GeForce 940MX/PCIe/SSE2
> GL Version: 4.5.0 NVIDIA 385.41
> Shader Version: 4.50 NVIDIA
> Available extensions:
> GL_AMD_multi_draw_indirect GL_AMD_seamless_cubemap_per_texture GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_bindless_texture GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_color_buffer_float GL_ARB_compatibility GL_ARB_compressed_texture_pixel_storage GL_ARB_conservative_depth GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_depth_texture GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_indirect GL_ARB_draw_elements_base_vertex GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_ES2_compatibility GL_ARB_ES3_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_program GL_ARB_fragment_program_shadow GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_geometry_shader4 GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GLARB

**Comment by AndriiYukhymchak** [comment]
Additional info: error 1282 is GL_INVALID_OPERATION, usually appears when shaders are doing something silly

hopefully that gives more info into this

**Comment by pchote** [comment]
As discussed in IRC, this is almost certainly going to be related to using a screen recording tool that hooks into OpenGL.

**Comment by abcdefg30** [comment]
Is this still an issue with latest OpenRA/screen recording tool versions?

**Comment by abcdefg30** [comment]
Closing as nobody on Discord reported that this is still a problem.
