### ISSUE TITLE
Improve compatibility with the Itch app: Allow downloading, launching, and tipping

### ISSUE THREAD

**Issue by aaronfranke** [OpenRA/OpenRA#14214]
https://openra.itch.io/openra

Currently, the game has an Itch.io page and hosts setup files such as a `.deb` but it cannot be downloaded through the [Itch app](https://itch.io/app) due to this. It gives the error:

> No compatible downloads were found for 'OpenRA', so it wasn't installed.
> 
> Maybe it's not compatible with your platform or with the itch app yet!

Instead of hosting setup files, you should host archives. A .zip file is recognized by the Itch app, and it will extract and search for an executable file, then run that. Itch does a pretty good job at this, but in the even that it doesn't detect the executable, you can add your own launch script. It can even be told about multiple launch targets, for each OpenRA mod. [More info](https://itch.io/docs/app/faq#how-are-games-executed), [manifest guide](https://itch.io/docs/itch/integrating/manifest.html).

You may be wondering, why bother adding this feature, since it does mean more packaging work? Simply put, just like Steam, games downloaded through the Itch app can be auto-updated. It would be great to have OpenRA auto-update, to easily keep Itch users on the latest version of OpenRA.

Also, Itch has a feature where games will appear in your library permanently, even if uninstalled, if you tip a small amount to the creator, even just $1. Please allow us to donate to add OpenRA to our Itch libraries. Itch has a feature called open revenue sharing, so you can keep 100% of the donated money, or you can give Itch a portion or purchases.

**Comment by aaronfranke** [comment]
Downstream bug report: https://github.com/itchio/itch-compatibility-watchlist/issues/1090

**Comment by pchote** [comment]
Does anyone want to volunteer working on this?  I see that their docs also reference automatically pushing updates, which could, in principle, be easily added to our packaging scripts.

**Comment by aaronfranke** [comment]
First I'd like to see if we can use a single manifest for all platforms of OpenRA. This would simplify things.

~~Waiting on: https://github.com/itchio/itch/issues/1587~~ That issue has been solved!

We could still work on this and ship builds, but there is still the issue of https://github.com/itchio/itch/issues/1606, so there is no way to tell Itch to install Mono. We would rely on people having Mono installed already, unless we wanted to bundle Mono somehow.

**Comment by Mailaender** [comment]
I made an attempt but only kept https://github.com/Mailaender/OpenRA/tree/itch-app for now.

On Windows the .NET dependency is automatically sorted out, but somehow the game spits out weird error messages about traits not being found after downloading the assets just fine that I don't understand. Also, for the next version we rely on https://github.com/itchio/itch/issues/2458.

On Linux I could get it to work but I will need to bundle Mono as https://github.com/itchio/itch/issues/1606 is not resolved yet. Apparently having multiple `launch-game.sh` entries with just different parameters doesn't work. It will always only pick the first. I had to make wrappers to workaround.

**Comment by pchote** [comment]
It would make sense to defer anything here until after the net core migration is complete.

**Comment by Mailaender** [comment]
My idea was to update the package for the current release.

**Comment by Mailaender** [comment]
If you browse to https://openra.itch.io/openra in the itch App and select "Windows portable with experimental Itch App support" it should now work.

![image](https://user-images.githubusercontent.com/756669/86623439-e6ccdb80-bfc1-11ea-9a80-f274e79eb27d.png)

I repackaged it manually now and simply added the metadata for the mod selection. Not sure why it only shows the filename.

Pinging @jamesxmcintosh who requested it at https://github.com/itchio/itch-compatibility-watchlist/issues/1090.

Requested .NET Framework 4.7.2 prereq at https://github.com/itchio/itch/issues/2458 which we currently demand.

**Comment by Mailaender** [comment]
Regarding tipping: that might be problematic as the game content does not fall under a license that permits it.

**Comment by jamesxmcintosh** [comment]
I can't test this on Windows as I am now using Kubuntu but I can confirm this works with the AppImage versions.
Great work.
