### ISSUE TITLE
prevent maps from getting cheated by moneycrate

### ISSUE THREAD

**Issue by airetaM** [OpenRA/OpenRA#14223]
Make moneycrates not stackable, if a mapcreater puts many moneycrates on one place he will get a bunch of money but you only see a 500$ going up, this is only noticeable if you watch the replay then or for spectators who look at his money.
Examples for this way to cheat are here : 
http://resource.openra.net/maps/23364/
http://resource.openra.net/maps/23357/
http://resource.openra.net/maps/23085
Please report these maps.

**Comment by abcdefg30** [comment]
To be honest, I think that is a map issue we can't do much about except (what you mentioned) making it impossible to place overlapping actors. However, after a quick discussion on IRC I don't think this is going to happen. Thanks for the report though. :)
