### ISSUE TITLE
severe CPU load, when an MCV pass a long hallway clogged by enemy artilleries

### ISSUE THREAD

**Issue by Diranus** [OpenRA/OpenRA#14228]
Hello,

I've spot a serious issue with the game performance (The Red Alert variant of the game):

I played a singleplayer skirmish against one bot.

Because I think, it has to do with the pathfinding algorithm, I describe the map too.

I made a map (using the build-in map editor) with a way in the center like this:

Top player area
#.....##############
#_______________#
#_______________#
##############....#
Bottom  player area

The '#' are unpassable (stones, cliffs). The way is two fields wide and goes from one end of the map to the other.

One player needs to pass the long way to reach the other. There is no other way.

At the sides of that long way are many "creep" gun towers you need to fight first to pass the way. The way itself is free of barriers.

I was playing (as sowiet) in the bottom side, the bot player was playing (as allied) in the top side.

Near the end, when most of the gun towers where fighted, I send a MCV though the way to build a base on the other side. I used the iron shield to protect the vehicle against damaging during passing the way.

At the same time (i didn't know it), the enemy had the idea to send a few artilleries (approx. 5, very few) through the same way so it gets sightly clogged (just enough so the MCV didn't pass through).

In that situation, the CPU got heavily overloaded. I had much less than 1 fps.

The mission to send the MCV to the other side failed, because it got destroyed (the way was slightly clogged by the artilleries so it didn't pass it fast enough). The game was still extremely slow.

I nuked the artilleries away using an a-bomb. After that, the CPU overload was gone.

Here is a photo of the situation with debug graphs turned on. (a screenshot was impossible for some reason) 
https://imgur.com/a/1gV0W

You can see one side of the way. The other side looks the very same. The empty squares were filled with gun towers. You see the destroyed MCV still burning there. Around it is, where the artilleries are (you can't see them due to the fog)

I additionally filmed the situation with my smartphone, if you need that movie, please tell me.

**Comment by PunkPun** [comment]
Is this still relevant?

**Comment by PunkPun** [comment]
Fixed by HPF
