### ISSUE TITLE
Crash with Harkonnen 8 on start

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#14224]
Trying to complete the Harkonnen Campaign, but i'm getting [this crash](https://gist.github.com/MustaphaTR/544c353e468f94d34d46b84115ae249b) on the beginning of the mission. Here is the mission files: https://github.com/MustaphaTR/OpenRA/commit/d10f99ab9c9c61add0c4aeb633f108ce9cf536be

**Comment by MustaphaTR** [comment]
Looks like reason of crash was that i misspelt "mercenary" at [L177](https://github.com/MustaphaTR/OpenRA/commit/d10f99ab9c9c61add0c4aeb633f108ce9cf536be#diff-93aef4630a09d5df83040eba1ae2b0d1R177). Not sure why exactly that causes a crash like that tho.

**Comment by pchote** [comment]
We should throw a better exception and if that exception doesn't show up for free when linting the rules add a lint pass too.

**Comment by abcdefg30** [comment]
This is about setting the owner in Lua. We don't have any linting for that. We already prevent setting an invalid `OwnerInit`, so another crash like this won't happen and I filed #17163 to prevent setting the owner to a null/nil value (which results in a different crash).
