### ISSUE TITLE
Soviet Mission 6a : Radar dome capture does not fulfill secondary objective

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#14239]
Minor detail, but secondary objective is "destroy radar dome to prevent allied reinforcements" : capturing it does not fulfill the objective.

**Comment by FRenzy-OpenRA** [comment]
![2017-10-22 12_44_26-openra](https://user-images.githubusercontent.com/20139967/31861089-d7b585bc-b726-11e7-8397-e6cf57737f67.png)

**Comment by Diranus** [comment]
IMHO, you actually didn't fulfill it.
Destroying it instead works fine. :-D
