### ISSUE TITLE
Red Alert Map Editor: Wrong map size

### ISSUE THREAD

**Issue by Diranus** [OpenRA/OpenRA#14237]
Hello,

I want report you a small bug.

A map is two fields larger (in each dimension) than stated.

Steps of reproduction:
1. Create a new empty map with 64x64 fields.
2. Count the fields. It is actually 66x66 fields (but still stated as "64x64" in the map selection dialog).

I hope, this report is helpful to you^^.

**Comment by GraionDilach** [comment]
Are you sure you're not counting the map cordon part of the map?

**Comment by Diranus** [comment]
What exactly is the cordon part?
I counted all blank fields that were grass or snow.

**Comment by AndriiYukhymchak** [comment]
Cordon tiles exist for purpose. It's not a bug

**Comment by netnazgul** [comment]
Additional 1-tile border is placed on the map edges for technical reasons; it can't be used in game AFAIR. So when you create a 64x64 map, you will actually see 66x66 with coordinates from 0 to 65, but actual map dimensions are from row/column 1 to row/column 64, borders are visual only.

**Comment by abcdefg30** [comment]
Yes, I also think that is how it is intended to work. Thanks for reporting though. ^^
