### ISSUE TITLE
Tiberian Dawn Map Editor - You can put a spawn point outside of the map bouns

### ISSUE THREAD

**Issue by Diranus** [OpenRA/OpenRA#14233]
Hello,

the title already says it.

It is possible to place a spawn point outside of the map bounds in the map editor of tiberian dawn.

This makes the map unplayable for the player who gets assigned this spawn point ;-).

**Comment by LipkeGu** [comment]
I tested it in RA, yes you can ... when playling this "map", the players can move the units into the map.

**Comment by abcdefg30** [comment]
Not sure if this is something we should fix. Imho this behavior makes sense (and people should kind of expect that spawns aren't working properly when placed outside the play area). We could add a lint warning maybe?

**Comment by pchote** [comment]
I agree with @abcdefg30 here.  The map editor is a development tool, and the user must take some responsibility for using it sensibly.  It isn't worth our time to even try.

**Comment by pchote** [comment]
closing as a wontfix
