### ISSUE TITLE
Still no rpm package for OpenSUSE and Fedora

### ISSUE THREAD

**Issue by Jiri-Kremser** [OpenRA/OpenRA#14248]
Please, make the image with `release-20171014`

**Comment by pchote** [comment]
https://software.opensuse.org/download.html?project=games:openra&package=openra has `release-20171014` rpms for Fedora, CentOS, and openSUSE.

**Comment by Jiri-Kremser** [comment]
cool, last time I checked, it wasn't there. I also build the code, but I wasn't able to play with the "dev version"

Now, it works, thanks!
