### ISSUE TITLE
Brainstorming for a potential late-2017 fixup release.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#14242]
# Issues to be included in the fixup release:
|Issue|Comment|PR/fix|Is merged into bleed|Is cherry-picked for prep|
| --- | --- | --- | --- | --- |
|#12907||#14226|||
||Fix tiling errors on Haos Ridges [RA]|#14127| ✓ | ✓ |
||Fix tile error on Asymmetric Battle [RA]|#14128| ✓ | ✓ |
||Fix tile errors on several more RA maps [RA]|#14318| ✓ | ✓ |
|#14316|Fix Fort Lonestar rules|#14320| ✓ | ✓ |
|#14298|Fix RA misc infantry AutoTargetPriorities|#14300| ✓ | ✓ |
||Change Road -> Bridge tiles|#14132| ✓ | ✓ |
|#14141|Character limit/long text issues|#14167| ✓ | ✓ |
|#14176||#14199| ✓ | ✓ |
||Helis facing|#14180| ✓ | ✓ |
|#14186|||||
|#14195|Submarine fix|#14198| ✓ | ✓ |
||Clear spectators' team|#14213| ✓ | ✓ |
||Fix "Unit ready"|#14221| ✓ | ✓ |
||Update macOS launcher|#14246| ✓ | ✓ |
|#14256|Tech buildings' GPS dots|#14274| ✓ | ✓ |
|| Rename `Fake Shipyard` to `Fake Naval Yard` (RA). | #14299| ✓ | ✓ |
|#14302 |Barrel explosions (RA)|#14314| ✓ | ✓ |
||Spy voices|#14322| ✓ |  |
|#14174|Icon issues on Windows||||
|#14214|Itch app compatibility (low priority, but would be nice)||||
||Issues with (broken?) mono 3.2.8 compatibility or officially raise the version requirement.||||
||Issues with open build service compatibility (or replace it with a more streamlined solution).||||
||Possibly some RA balance adjustments (not explicitly low priority, but not likely to happen on the timescale of the release)||||

# Requested for adding:  
#14244 - Change Vulcan dmg vs Light armor (RA balance),
#13983 (#14220) - Capturing/production interaction bug,
#14275 - Capturing service depot from above/below (RA),
#14278 - Mines are not auto-targetable (RA),
#14123 - `allies02` objective fix (RA),

#14319 - D2k asset installation issue

**Comment by reaperrr** [comment]
I'd cherry-pick #14180 as well, while we're at it.

**Comment by MustaphaTR** [comment]
As RA balance, i think #14244 should go in that release, as it is a fix for a oversight from current one.

**Comment by ugotbroiled** [comment]
Please...

https://github.com/OpenRA/OpenRA/issues/13983

**Comment by reaperrr** [comment]
I think #14213 should be safe to take as well.

**Comment by penev92** [comment]
This list is getting pretty long...
Anyway, perhaps all approved suggestions should be reflected in the main post so we can keep track of what is approved and what is not.

**Comment by penev92** [comment]
Added #14174 to the list.

**Comment by pchote** [comment]
Possibly also #14275 and #14278.

**Comment by penev92** [comment]
Added those two to the "requested" list.
How about #14123? Or maybe we're expanding this too much at this point?

**Comment by pchote** [comment]
I have added @FrameLimiter's map fixes and bogus yaml discoveries to the milestone.

We probably also need #13478 as a workaround for #14178.  I have a build ready to go for that, it just needs to be pushed and PRed.

**Comment by penev92** [comment]
Added #14320 and #14300 to the list.

**Comment by Arular101** [comment]
I think this issue #14302 might be needed to be fixed too. See PR #14314 for more info and screenshots.

**Comment by pchote** [comment]
We have decided not to ship a hotfix release, but instead prioritise a proper playtest based on bleed.
