### ISSUE TITLE
Tiberian Dawn: Confusing "Unable to build more" situation

### ISSUE THREAD

**Issue by Diranus** [OpenRA/OpenRA#14243]
Hello,

I noticed some random "Unable to build more" messages during gameplay. But every time, no production really stuck. 

So I tried a bit around, when it is happening and found it^^.

I have a weapon factory like this:

![](https://imgur.com/TpxD1vg.png)

(This is a bit artifical but similar situations happen during regular gameplay if you build and "collect" many tanks. The barriers simulates a bigger army of tanks here)

It starts with only a fresh factory and without any unit (ignore the bigger army that you see in the lower part of the screenshot. It has nothing to do with it).

Now, I start building a bunch of units with that factory.

Following is happening:
1. The first unit leave the weapon factory and stay just before its door (because its target is "full" and therefore, unreachable)
2. The door of the factory stays open, after the new unit left it 
3. An "Unable to build more" is spoken, if the next unit gets ready and wants to leave the factory
4. The units before the factory make space for the new unit, so it can roll out
5. Next unit will be build and it repeats over and over. The door of the factory never closes.

I think, the phrase "Unable to build more" is a bit confusing here. The factory actually can build more (and does it as well). There is enough space around the factory and the units move away to make space.

Because the door of the factory is open, it could be a bug too.

**Comment by AshEdwardsDesign** [comment]
I've also noticed this and wondered what the hell was causing it 👍

**Comment by PunkPun** [comment]
This is no longer an issue
