### ISSUE TITLE
Mission "Finish the NOD base" - Secondary objective does not complete

### ISSUE THREAD

**Issue by Diranus** [OpenRA/OpenRA#14251]
Hello,

There seems to be another mission related bug.

I played the "Finish the NOD base" mission from the GDI campaign.

There is one secondary objective that does not complete. 

See this screenshot (I made the screenshot a few seconds before the end of the mission):
https://imgur.com/a/FHM0Q

It was bigger during the mission but I ran out of tiberium so I needed to sell a few buildings. (for example, I had a second war factory and a third refinery)

The enemy didn't destroy any of these.

My idea: The condition relies on the building of at least one of these small yellow gun towers. I didn't build any of these. I had no cash (and hungry harvesters) so I wasn't able to try around in the ending, why that objective didn't complete.

Especially in this mission with very limited tiberium I just have built what I really needed to get as much units as possible. 

But in my opinion, a base of that size (it is almost a quarter of the map) should be accepted as a base in relation to the map size and the difficulty of that mission.

**Comment by simon-v** [comment]
You seem to have also skipped building a communications center, which is the actual condition.

**Comment by Diranus** [comment]
Yes, when I remember correctly, I didn't build one, because I didn't need it. But there was no hint that I have to.

**Comment by pchote** [comment]
The simplest fix would be to make the objective clearer, e.g. "Establish a permanent base by building a Communications Center"

**Comment by simon-v** [comment]
I don't know, man, i, personally, have a hard time imagining a situation in which i'd skip building a radar as soon as it is available.

**Comment by Diranus** [comment]
Then you have another strategy to solve this mission.^^

I absolutely didn't needed it in this mission. I never thought about building one in this mission.

I give a lowest priority to have a radar, when I don't suddenly need the building options that it provides. 
Especially, if the map is that small that it is for itself already like a radar screen ;-).

My "default" strategy is basically this:
1. Start and establish continious building of cyborgs and tanks (without running out of money) as soon as possible.
2. If frequent attacks weaken the army over and over: Build a second war factory. With that factory a few harvesters and then tanks.
3. If enough tanks are there to protect each side from the base, move them away from the base to keep the enemy more far away from it. 
4. Thinking about building communication center, service depot, more advanced units etc. and probably take water/air into account.
5. Move the army as closer to the enemy base as bigger it gets... Kill his harvesters... until to finally fight him.

In that mission, I ran out of tiberium in step 3 so I didn't came to 4, because I preferred the building of units over having many buildings. To get more cash, I sold all buildings related to 2, because I had enough units to destroy the enemy base.

**Comment by abcdefg30** [comment]
> I absolutely didn't needed it in this mission. I never thought about building one in this mission.

Hence we got the secondary objective as incentive to build one. ;)

**Comment by Diranus** [comment]
Then, the objective should be more specific.

I'm for "Establish a permanent base by building a Communications Center" or something like this ;-).

When is a base considered a base? A base with a communication center? Or a base with defence towers? Or a base with n buildings?

In my opinion, a base is a base, even without a communication center.

**Comment by Smittytron** [comment]
The mission actually wants you to build all available buildings.
