### ISSUE TITLE
Minor ESC bug in the main menu

### ISSUE THREAD

**Issue by Diranus** [OpenRA/OpenRA#14252]
Hello,

here is a minor bug in the main menu navigation:

In any submenu, you can go back using the ESC key.

Works (almost) everywhere.

But not in the skirmish dialog, where you can select the player slots, player colors and so on. If you press the ESC key, nothing happens.

I've noticed this in both, tiberian dawn and red alert.

**Comment by abcdefg30** [comment]
This is because the chat is resetting when you press esc.

**Comment by Diranus** [comment]
Ok, I didn't know it.
It is a bit annoying to ESC-"backmovers" like me^^.

**Comment by abcdefg30** [comment]
Closing as resolved. (Besides, Iirc we disabled esc in the lobby so that people don't accidentally leave.)
