### ISSUE TITLE
Tiberian Dawn: Civil people speak german

### ISSUE THREAD

**Issue by Diranus** [OpenRA/OpenRA#14259]
Hello,

the game is actually in english.

But in the mission "04a - mao civil war" the nod-sided civilians speak german when you act with them.
They say "Ja" instead of "Yes" and their "OK" is spoken in german pronouncing.

**Comment by rautamiekka** [comment]
**I seem to recall** the original games had German somewhere. Or was it in the first C&C ?

**Comment by Diranus** [comment]
Tiberian dawn is the first C&C ;-).

I'm german and my original game version is german so I can't look for it^^.

**Comment by GraionDilach** [comment]
Yeah? Okay. Yeah? Okay. Yeah? Okay.

There's no Ja here, that's a Yeah.

**Comment by AndriiYukhymchak** [comment]
Looking at your issue with rocket cyborgs, I think you were forced to download germanized version. I don't seem to have same issue

**Comment by GraionDilach** [comment]
Due to the checksums in place, I don't think the gamen should work with the German version at all.

**Comment by AndriiYukhymchak** [comment]
It doesn't care for mix file with sound afaik

**Comment by Diranus** [comment]
If it sounds english to you, then everything is fine.
To me, that voice sounds very german and it is the only one.
Then it is just speaking both languages very well and at once.
And no, I didn't download a german version of OpenRA. I installed the one you can get at project website.

**Comment by AndriiYukhymchak** [comment]
Openra has to (for legal reasons) be devoid of any original red alert assets. That's why game asks you first time you install it to download assets from EA site or openra mirror with butchered version

**Comment by GraionDilach** [comment]
If we talk about the same sounds which are heard in https://www.youtube.com/watch?v=3_TdZMX_mzI, that's what the English version came with. I definitely hear the e of Yeah.

**Comment by Diranus** [comment]
I hear nothing but a wall of shooting sounds in that video^^. Too much equally loud sound at once so I can't pick one out of it.
Mine has a different and female voice.

**Comment by abcdefg30** [comment]
Sorry, not much we can do here I think.
