### ISSUE TITLE
Tiberian Dawn Map Editor: Missing check if .oramap file already exists

### ISSUE THREAD

**Issue by Diranus** [OpenRA/OpenRA#14254]
I found a dangerous bug in the map editor:

1. Create a new map and name it "test"
2. Make something beautiful and save it as "test"
3. Verify that your map is saved and available in the skirmish map selector
4. Create another new map with the same name "test"
5. Notice, that there is no "File already exists. Overwrite?"
6. Do nothing and quit the map editor. Notice the question "Exit map editor without saving?". The old map should survive.
7. Now go to the map selector in the skirmish mode. Notice that map "test" is listed twice. (This is another small bug)
8. Restart the game to workaround the bug of step 7
9. Play the map and notice, that your map from step 1 is overwritten by the second empty one without any warning. It actually saved at step 6(?) even the question was "Exit without saving?". ;-)

**Comment by abcdefg30** [comment]
You press "Save" at least once while creating the map. So overwriting is expected even without saving again before you exit. We might want to display a warning, however.

**Comment by Diranus** [comment]
Ok, then there should be a warning if you are overwriting something :-D.
