### ISSUE TITLE
Tiberian Dawn Map Editor: File name accepts a question mark

### ISSUE THREAD

**Issue by Diranus** [OpenRA/OpenRA#14255]
Hello,

the title already says it:

The map editor accepts a "?" as filename and saves the map as "?.oramap".

Tested unter Linux Mint but such filename is problematic in Windows. Have luck to handle such file in that OS ;-).

**Comment by AndriiYukhymchak** [comment]
Good catch. I'll look into that at some point

**Comment by reaperrr** [comment]
Fixed by #15089.
