### ISSUE TITLE
RA - New Tech Buildings don't have their own GPSDot

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#14256]
Hospital, Oil Derrick and Bio Lab has own GPSDots, Communications Center and Forward Command Center don't. Would be good to give those own dots too for consistency.

**Comment by Smittytron** [comment]
Guess I would have to play games with shroud on to ever get those dots. 
Would the basic Structure dot suffice here?

**Comment by MustaphaTR** [comment]
Wait, i didn't even tested that tbh, judging from the code they have no dot at all. I meant "make special dots for them" while opening this issue.
