### ISSUE TITLE
possibly a desync bug with production queues

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#14265]
Hey, I got a desync crash and luckiely Beanbrains provided me with his log.

I used a merge tool to compare the files. This is the excerpt which is different (the crash happens way later. This is approximately at 2% of the sync file). It is the only difference between those files.
My file:
```

	 3 player SirCakealot PlayerResources (35244)
		 Cash: 40668
		 Resources: 0
		 ResourceCapacity: 6000
	 3 player SirCakealot PlayerExperience (1259)
		 Experience: 1259
	 3 player SirCakealot PowerManager (1608)
		 totalProvided: 1066
		 totalDrained: 610
	 3 player SirCakealot FrozenActorLayer (446813)
		 VisibilityHash: 218365
		 FrozenHash: 361888
	 3 player SirCakealot ClassicProductionQueue (3302)
		 isActive: True
		 QueueLength: 2
		 CurrentRemainingCost: 2232
		 CurrentRemainingTime: 1116
		 CurrentSlowdown: 0
		 CurrentPaused: False
		 CurrentDone: False
		 Enabled: True
```
Beanbrain's file:
```
	 3 player SirCakealot PlayerResources (34968)
		 Cash: 40936
		 Resources: 0
		 ResourceCapacity: 6000
	 3 player SirCakealot PlayerExperience (1259)
		 Experience: 1259
	 3 player SirCakealot PowerManager (1608)
		 totalProvided: 1066
		 totalDrained: 610
	 3 player SirCakealot FrozenActorLayer (446813)
		 VisibilityHash: 218365
		 FrozenHash: 361888
 ...(missing stuff here)...
```
the first and last paragraph show discrepancies.

This is on a [modded map](https://resource.openra.net/maps/23443/), but no lint fails and it also happened to me on a standard map. In total I had 3 desync crashes since the new release came out. Cant remember any desyncs on the previous release.

**Comment by pchote** [comment]
Please link to the map on the resource center.

**Comment by CH4Code** [comment]
Done

**Comment by CH4Code** [comment]
never mind     most likely I messed up my local install while modding. Just found that I accidentally deleted all prerequisites for the nuke in my local copy of OpenRA. -.- So I could make it, but of course that would cause a desync crash..
