### ISSUE TITLE
Red Alert: Target point outside of the map in some circumstances

### ISSUE THREAD

**Issue by Diranus** [OpenRA/OpenRA#14260]
See screenshot:

https://imgur.com/a/Jh0UG
![](https://i.imgur.com/du0LFm0.png)

The inital target, where new dogs should walk after building is outside of the map, if you place the kennel at the bottom of the map.

The dogs itself behave correctly and don't walk into the black wall.

**Comment by abcdefg30** [comment]
Default rallypoints have been removed.
