### ISSUE TITLE
Idea: Ballistic miss chance trait

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#14264]
Have a trait added for gun turrets or tanks to miss shots completely much alike to CNC95 with how their tanks would miss infantry. Having this with an optional miss chance number (IE: set to 40 = 40% chance to miss) so when shots do land on the infantry it does a lot of damage.

This doesn't need to be defaulted on tanks in general but its an idea for my future progress of splitting gun turrets and Guard Towers to faction specific.

**Comment by AndriiYukhymchak** [comment]
What do you mean by miss? Completely negate damage or hot another place entirely?

**Comment by AoAGeneral** [comment]
By miss I mean on the target its aimed at. So it could hit the next cell or mini cell over.

**Comment by GraionDilach** [comment]
What is the problem with the current Inaccuracy tag?

**Comment by AndriiYukhymchak** [comment]
Yeah, already implemented. See current allied artillery

**Comment by GraionDilach** [comment]
TBH, I do have issues with current inaccuracy logic - see #9115.

**Comment by AoAGeneral** [comment]
@AndriiYukhymchak The artillery is at any target. If I wanted them to miss for specific unit types only is that already implemented?

**Comment by GraionDilach** [comment]
Completely doable - use two weapons - one inaccurate against the targets you want inaccuracy and one accurate against the accurate targets. You can use AmmoPool (asin shared ammo + SelfReload) to prevent switching-targets-ROF-abuse (notsure if TD grants rate-of-fire bonus to veterancy, if no, you can leave selfreload on the default ROF even).

**Comment by abcdefg30** [comment]
Closing as resolved.
