### ISSUE TITLE
Red Alert: Construction yard conflict

### ISSUE THREAD

**Issue by Diranus** [OpenRA/OpenRA#14261]
Hello,

I found following problem (or did I overlook something?):

You play the allied, the enemy the sowjet:

1. Capture enemie's war factory
2. Set the captured factory as primary
3. Build a MCV (it will be a sowiet one because the sowiet war factory is your primary building) 
4. Pop the MCV out to a construction yard
5. Build a war factory and place it
6. The new war factory is a sowiet one
7. Notice, that there is no way to build an allied war factory anymore, because you can't make your old allied construction yard to the primary one.

**Comment by AndriiYukhymchak** [comment]
Issue is that you can't set con yard as primary. You still can redeploy your original mcv and it will again become primary

**Comment by theKalash** [comment]
> Notice, that there is no way to build an allied war factory anymore, because you can't make your old allied construction yard to the primary one.

There is only one war factory and you get the vehicle prerequisite for all the factions you have the structures prerequisite at the time of deployment. 

Pretty sure that when you sell all your war factories and then build a "soviet" one you will still be able to produce allied vehicles (as you still have the allied structures prerequisite).

**Comment by Diranus** [comment]
If you have one allied and another sowiet war factory, both seem to be intependend.
If you sell the allied one, you loose the ability to build allied units. Same goes for the sowiet one.

And that is, what I actually tried: To bring back the ability to build allied units after selling the allied war factory. Just building a new factory didn't bringt it back. So I came to the conclusion, there is no way to build a war factory with the ability of building allied units.

But the "trick" to collapse the allied construction yard and expand it back, before you build another war factory, is working. After I tried that, I've got a "hybrid" war factory with the ability to build both types of units. If I sell all but the new one, I can still build all units.

**Comment by pchote** [comment]
The "type" of conyard is set based only on what construction yards you have active when the building is placed.  Un/redeploying the allied MCV first shouldn't affect anything.

**Comment by Diranus** [comment]
And which type the building will be, if you have both types of construction yards?

**Comment by pchote** [comment]
Both!

**Comment by Diranus** [comment]
But that was not the case until I re-expanded the allied construction yard.

**Comment by theKalash** [comment]
I just tested it and can't confirm what you describe

> If you have one allied and another sowiet war factory, both seem to be intependent.
If you sell the allied one, you loose the ability to build allied units. Same goes for the sowiet one.


All the war factories you build previous to capturing an soviet mcv will be "allied war factories". If you build a war factory after you captured a soviet conyard (so you are in possession of both, allied and soviet conyard) it will be a "hybrid war factory". There is no way to lose the ability to build allied vehicles by selling any of those war factories. 

The only possibility would be to lose/undeploy your allied mcv and then build a war factory with only the soviet conyard deployed, that will give you a "soviet only war factory". Maybe that's what happened to you?

**Comment by theKalash** [comment]
At the point you build the MCV from the captured war factory, were you still in possession of an allied conyard or was the Conyard you got from the captured war factory your only one?

**Comment by theKalash** [comment]
Ok, I figured it out. 

As mentioned above, a war factory "type" depends on which conyards are active when it is placed:

soviet conyard -> soviet war factory
allied conyard -> allied war factory
both conyard -> hybrid war factory

So I set up a game where I have both conyards and build one of each type of war factory. Now we undeploy/destroy all our conyards (build a repair pad first though).

Now what happens is, that if you build an MCV from a the captured war factory (in this case and my test, soviet) it will be a soviet MCV and when you deploy it you will only be able to build sovjet structures .. and vice versa..

MCVs build from the hybrid structure seem to default back to your original faction (so on this case it was a allied MVC). 

So they type of MVC is determined by the type of war factory that it is build from. You can switch it by just chaning the primary war factory, if you have different types. 

It's a bit unintuitive, but I think working as intended.

**Comment by Diranus** [comment]
> MCVs build from the hybrid war factory seem to default back to your original faction (so on this case it was an allied MCV).

I had the opposite case oO. A "hybrid" MCV was actually a soviet one in my case. But I played allied.

This could be the actual issue. I barely remember, I really sold the allied war factory after capturing the soviet one. I can't clearly remember. It was happening in a stressful situation in a "real" multiplayer server game. So it might depend on other gameplay conditions before.

I'm going to test it once more against a dumb bot. But not today anymore.

**Comment by theKalash** [comment]
That's the problem, there is no hybrid MVC. Only hybrid war factories that still only produce a single faction MCV. 

And mit might not be your default faction, but rather the faction of the conyard which was the primary structure while the specific war factory was build. 

This is definitely a clusterfuck with the Prerequisite system you stumbled upon. It would be almost impossible to keep track of your specific war factories in a game where you capture more then 1 different faction tech and tried to preserve them. Not a very common case fortunately.

**Comment by GraionDilach** [comment]
TBH this is the reason why I don't rely on Prerequisites->Factions in AS at all, and these issues pledge the original WW games as well (Owners in TS Required/ForbiddenHouses in RA2 can give you a lot of headaches with similar issues).

How I resolved this issue is that only captured MCVs/conyards unlock faction tech with a dummy "upgrade" actor being spawned at capture - and players start with their own upgrade actor.
