### ISSUE TITLE
Support for multipile ProducibleWithLevel: traits.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#14270]
In Zero Hour, some Generals have General's Powers that make their "normally built as rank-1 units" built at rank-2 instead, which i need for my mod.

Also expanding VeteranProductionIconOverlay to show different artworks depending on the InitialLevels of actor would be useful for that too.

**Comment by theKalash** [comment]
> In Zero Hour, some Generals have General's Powers that make their "normally built as rank-1 units" built at rank-2 instead, which i need for my mod.

This can be easily done by just editing the yaml files. Just change the "InitialLevels" attribute of the "ProducibleWithLevel" trait, to "2". 

I even supports "Prerequisites" though not "Conditions" :( 
Also haven't tested if you can have multiple with different Prerequisites. 

> Also expanding VeteranProductionIconOverlay to show different artworks depending on the InitialLevels of actor would be useful for that too.

that would be cool!

**Comment by MustaphaTR** [comment]
> This can be easily done by just editing the yaml files. Just change the "InitialLevels" attribute of the "ProducibleWithLevel" trait, to "2".

Point i was making it is, i need two of those trait, one that normally gives 1 rank, and 1 when general's power taken that makes it rank 2. I know making a unit Rank 2 directly is possible.

**Comment by SoScared** [comment]
This is something I'm interested in as currently I'm forced to use duplicate units to succeed rank add-ons beyond 1. The draw-back is that with duplicate units production is reset between the ranks.

I'm also using custom shp's to "paint" on the level 2 ranks and beyond. Having support for multiple icon-overlays would be great.

**Comment by MustaphaTR** [comment]
It seems like multipile ProducibleWithLevel: work without the VeteranProductionIconOverlay, which is what i did in Generals Alpha. You lose the icons on the UI but can do stuff without duplicates.

**Comment by SoScared** [comment]
I think I need keep the duplicates for the visual cue to the player.

Regardless, being able to produce veterancy2+ units with veterancy1 icon overlays sounds like a bug.

**Comment by SoScared** [comment]
from MicroBit's original artwork from #9080:
![iconoverlays](https://user-images.githubusercontent.com/2715583/49822067-5d6d0d00-fd7c-11e8-9512-259b632b5ee4.png)
