### ISSUE TITLE
Enemy mines are not auto-targetable, even on AttackAnything stance

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#14278]
Even if revealed by own minelayer, enemy mines can only be killed by force fire, which is very time consuming.

**Comment by FRenzy-OpenRA** [comment]
Btw I think this wasn't the case in previous release

**Comment by reaperrr** [comment]
> Btw I think this wasn't the case in previous release

If it really wasn't, it's a regression and should be fixed in the upcoming bugfix release.
