### ISSUE TITLE
Detecting the team a spy is disguised as via the Lua API

### ISSUE THREAD

**Issue by dsimmons87** [OpenRA/OpenRA#14273]
There isn't currently a way to detect which team a spy is disguised as using the Lua API. Would it be possible to expose EffectiveOwner as a property?

**Comment by VanWardawg** [comment]
I'd love to help out with this one. Would we like to just expose the Player object through the api, either the AsPlayer or the self.Owner depending on whether we are disguised or not?

**Comment by abcdefg30** [comment]
Yeah, just exposing the player sounds good. (We could also expose the `Disguised` boolean. That is a bit redundant to `self.EffectiveOwner != self.Owner` though.)

**Comment by pchote** [comment]
`Owner` is already exposed, and its important that doesn't change.  Exposing `EffectiveOwner` is the simplest and best solution.

**Comment by VanWardawg** [comment]
Ok I will add that and send a PR. It will be my first but I've already experimented and tested some changes so I think I'll be able to do this :) Thanks! is there a way to assign the bug to me then? Also is there a way to add tests for changes like this? I've been using allied mission five which has a spy in the lua script to test but couldn't find another way.

**Comment by abcdefg30** [comment]
> is there a way to assign the bug to me then?

Looks like GitHub only allows contributors to be assigned to issues.

> Also is there a way to add tests for changes like this?

Not really, we usually let the reviewers build their own testcase, or add an extra commit
(e.g. one altering mission 05a) which is removed prior to merging.

**Comment by VanWardawg** [comment]
I'll submit the pull request with those parameters and reference this bug, hopefully then I'll be considered a contributer to assign the bug to.

**Comment by VanWardawg** [comment]
![image](https://user-images.githubusercontent.com/5891831/33416620-76e23114-d552-11e7-8028-a062601f31ce.png)

**Comment by abc013** [comment]
I guess this can be closed?

**Comment by pchote** [comment]
Fixed by #14454.
