### ISSUE TITLE
OpenRA freezes after a User Account Control pop-up appears.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#14280]
Not sure if this is an issue with OpenRA or Windows, or if it is even fixable, but on Win7 when i try to open something that wants admin rights and show user account pop-up, any already open OpenRA freezes while it is on focus. It for some reason acts fine while it is not on focus. (While i'm doing alt+tab for example). Freeze is completely visual, game plays behind in fact and i can give input.

It works fine if i open the program that requires admin right first and then OpenRA. It is just an annoying problem.

This is the pop-up i'm talking about, for some reason i can't take a ss of it so here is a photo:
![1509430134232919745734](https://user-images.githubusercontent.com/7933210/32209789-321e0f60-be1b-11e7-96b4-c83a76570541.jpg)

Edit: Acutally it looks like freeze only happens if i click yes, not no.

**Comment by GraionDilach** [comment]
Could you try disabling the dimming-PC aspect of UAC? I'd moreso assume is that the dimming causes issues with the OpenGL handling.

**Comment by abcdefg30** [comment]
Windows 7 is no longer supported officially.
