### ISSUE TITLE
Opening menu no longer pauses missions/skirmish

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#14284]
Not sure if this was intentional, but this feels quite inconvenient when playing larger missions.
(Only on bleed, not prep).

**Comment by reaperrr** [comment]
Also want to mention that several PRs I merged yesterday didn't have this issue yet, so this must have slipped into bleed during the last ~2 weeks.

**Comment by pchote** [comment]
Probably introduced by #14189.

**Comment by penev92** [comment]
Yes, `git bisect` points to commit https://github.com/OpenRA/OpenRA/pull/14189/commits/409034da8e559e48e54c9fb8fcb89045dbeaaad1 of that PR.
