### ISSUE TITLE
InitialUnits don't grant LoadedCondition or PassengerConditions

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#14281]
You need to make passenger leave and enter back to Conditions to be granted properly.

**Comment by FrameLimiter** [comment]
Related: #11674

**Comment by GraionDilach** [comment]
Not really related, it's an exact duplicate IMO - tags were just basically renamed since.

**Comment by MunWolf** [comment]
It is a really easy fix, someone just has to get around to it

**Comment by penev92** [comment]
Yup, closing as duplicate.
