### ISSUE TITLE
Tiling errors on the map Alaska Anarchy Redux

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#14305]
This RA map has a few tiling errors. Here is a revised version:
https://resource.openra.net/maps/23769/

The tile errors that have been fixed:
52,46,0 √ (road connection)
94,84,0 √ (river)
94,87,0 √ (river)
94,92,0 √ (gems in river)
98,41,0 √ (road section)
104,101,0 √ (cliff)

**Comment by reaperrr** [comment]
Closed via #14318.
