### ISSUE TITLE
Tiling errors on the map Nine Lives

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#14309]
This RA map has a couple tiling errors. Here is a revised version:
https://resource.openra.net/maps/23773/

The tile errors that have been fixed:
20,20,0 √ (shoreline)
21,107,0 √ (shoreline remnant)
50,1,0 √ (road connection polish)
111,78,0 √ (road remnant)

**Comment by reaperrr** [comment]
Closed via #14318.
