### ISSUE TITLE
Tiling errors on the map Mad Science

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#14308]
This RA map has a few minor tiling errors. Here is a revised version:
https://resource.openra.net/maps/23772/

The tile errors that have been fixed:
11,21,0 √ (debris-225 was cut in half) (replaced with 1x1 equivalent debris-217)
13,58,0 √ (debris-225 was cut in half) (replaced with 1x1 equivalent debris-217)
21,37,0 √ (road connection polish)
34,52,0 √ (road remnant)
51,57,0 √ (road connection polish)
66,50,0 √ (road connection polish)
99,62,0 √ (debris-225 was cut in half) (replaced with 1x1 equivalent debris-217)
101,11,0 √ (debris-225 was cut in half) (replaced with 1x1 equivalent debris-217)

**Comment by reaperrr** [comment]
Closed via #14318.
