### ISSUE TITLE
TS: Aircrafts land instantly to reload their ammo.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#14312]
Since #13701.

**Comment by GraionDilach** [comment]
Why isn't this a regression btw?

**Comment by BGluth** [comment]
I can't reproduce this.

**Comment by GraionDilach** [comment]
It only happens when the airport/helipad is not on the base ground level. (Height: 0) Just checked it on my flat map - the bug indeed doesn't happen there.

**Comment by BGluth** [comment]
Ah right ok now I'm seeing it.

It also only seems to happen for the banshee and the orca bomber, which I think are both not VTOLs.
