### ISSUE TITLE
macOS 10.13 High Sierra/APFS support

### ISSUE THREAD

**Issue by ldebrouwer** [OpenRA/OpenRA#14315]
Open RA fails to launch on macOS 10.13 High Sierra, presumably due to the new APFS file system.

```
Nov  8 08:03:55 ldebrouwer OpenRA[10842]: /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Common/ChunkCompression.cpp:50: Error: unsupported compressor 8
Nov  8 08:03:55 ldebrouwer OpenRA[10842]: /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.1.1/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/
```

**Comment by pchote** [comment]
Works fine for me on 10.13.  Can you please provide more details on your system and any custom configuration you might have one?

**Comment by ldebrouwer** [comment]
No custom configuration, just a standard mid-2015 MacBook Pro.

```Hardware Overview:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,5
  Processor Name:	Intel Core i7
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	MBP114.0177.B00
  SMC Version (system):	2.30f2
```

**Comment by pchote** [comment]
Does this build behave any differently? [[dropbox link](https://www.dropbox.com/s/g8a1706h9dq6p7e/OpenRA-release-20171014.dmg?dl=1)]

**Comment by pchote** [comment]
Unfortunately there is not enough information to follow this up, so closing.

**Comment by GregOriol** [comment]
Adding a note to this "High Sierra" issue: I just upgraded to 10.13.4 from 10.12.6 and OpenRA (release-20180307) didn't launch, it was hanging, the icon jumping in the dock and nothing else. I re-installed it from the dmg and it works now.

**Comment by pchote** [comment]
@GregOriol you were likely seeing https://github.com/OpenRA/OpenRA/wiki/FAQ#pinwheel-of-death-when-starting-on-os-x-for-the-first-time which is also triggered by OS updates because they invalidate the font cache.
