### ISSUE TITLE
allies-03b & drop-zone-w weapon issues

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#14321]
"High: True" --> "Blockable: false":
https://github.com/OpenRA/OpenRA/blob/master/mods/ra/maps/allies-03b/weapons.yaml#L10
https://github.com/OpenRA/OpenRA/blob/master/mods/ra/maps/drop-zone-w/weapons.yaml#L8
https://github.com/OpenRA/OpenRA/blob/master/mods/ra/maps/drop-zone-w/weapons.yaml#L30

"Angle" --> "LaunchAngle":
https://github.com/OpenRA/OpenRA/blob/master/mods/ra/maps/drop-zone-w/weapons.yaml#L9
https://github.com/OpenRA/OpenRA/blob/master/mods/ra/maps/drop-zone-w/weapons.yaml#L31

**Comment by pchote** [comment]
Why aren't our lint tests catching any of these issues?

**Comment by Arular101** [comment]
I removed the FireballLauncher: Projectile: High: True in Allies 03b in this PR #14326 . This is not needed anymore in that mission.

**Comment by reaperrr** [comment]
> Why aren't our lint tests catching any of these issues?

I think we don't throw any warnings/errors on non-existing traits/properties in general.

**Comment by pchote** [comment]
We really should be throwing warnings for these...
