### ISSUE TITLE
TS can't build new Mammoth Mk after air transport was destroyed

### ISSUE THREAD

**Issue by array42** [OpenRA/OpenRA#14336]
Built a Mammoth Mk and picked it up. It was shot down. It was not possible to build another one. Should be possible to build another then.

**Comment by abcdefg30** [comment]
Looks like #13827.

**Comment by penev92** [comment]
Does that mean we have the same issue with other limited units dying inside transports, like Tanya in a APC/Chinook/Naval transport?

**Comment by MustaphaTR** [comment]
I think he means Carryall: not Cargo:.

**Comment by GraionDilach** [comment]
#15030 fixed this.
