### ISSUE TITLE
What is the status of  C&C and RA campaigns?

### ISSUE THREAD

**Issue by daninthemix** [OpenRA/OpenRA#14348]
Sorry if this isn't the correct place to ask this, but I wondered what is the status of these campaigns, as I really want to play them all the way through?

(on that note, one nice feature for later on might be a 'Full Campaign' option that gives you each mission in sequence, with cutscenes between etc)

**Comment by clemty** [comment]
See #4988 and #4989

**Comment by pchote** [comment]
I'm sorry to say that we don't have any active contributors working on the C&C or RA campaigns anymore.  @MustaphaTR has been doing some good work towards the D2K campaigns, which are now over 50% complete!

**Comment by Biofreak1987** [comment]
I'll try to finish nod 10 next week, the current progress can be viewed at: https://github.com/Biofreak1987/OpenRA.
I wanted to wait until global campaign scripts and the campaign ai got finished... which still seems to take a while.

**Comment by reaperrr** [comment]
> I wanted to wait until global campaign scripts

Wasn't at least this done already, or was that only for d2k?

**Comment by MustaphaTR** [comment]
> Wasn't at least this done already, or was that only for d2k?

Yes, it was only D2K.
