### ISSUE TITLE
Small bridge tiles on desert maps can't be destroyed/repaired

### ISSUE THREAD

**Issue by theKalash** [OpenRA/OpenRA#14346]
The small river bridge (desert tiles 620 to 627) aren't targetable by C4 or engineer repair while also seeming to be indestructible in general.

**Comment by reaperrr** [comment]
I guess you mean the RA mod?

**Comment by theKalash** [comment]
Yes, RA

**Comment by theKalash** [comment]
There also seems to be an issue with the large multi-tile bridge. While it is properly targetable, the engineer can't seem to get into the bridge hub. C4 works fine. 

In the desert tileset only. In temperate it works fine.

**Comment by Smittytron** [comment]
The desert bridge doesn't exist in civilian.yaml. If someone tackles this they might want to make the bridges on the shellmap invincible.
