### ISSUE TITLE
Custom rules map isn't displaying "This map contains custom rules" prompt.

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#14342]
When loading this custom [map](http://resource.openra.net/maps/23855/) in _multiplayer_ it isn't displaying the usual "This map contains custom rules" lobby prompt.

In singleplayer skirmish it works fine.

**Comment by pchote** [comment]
I'm unable to reproduce this bug in multiplayer, using a dedicated server.  It always shows the "This map contains custom rules" message for me.

Can you please post a screenshot showing the (lack of) messages in the chat window?

**Comment by FrameLimiter** [comment]
![maperror](https://user-images.githubusercontent.com/22008761/33232399-b2199fa6-d1d3-11e7-943c-aaadeecbefc6.png)

**Comment by pchote** [comment]
Closing as duplicate of #14060, which was fixed by #14090.

In this case the duplicated node was `^NeutralPlane`, so the symptoms were different to #14060.
