### ISSUE TITLE
Allied tech center cannot be manually powered down.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#14347]
It is the only structure in RA that is disabled by low power but can't be manually powered down, which makes it an outlier.

**Comment by abcdefg30** [comment]
I thought this is intentional for balancing reasons?

**Comment by MustaphaTR** [comment]
See #5982

**Comment by ResourceHog** [comment]
is this confirmed as an issue?

**Comment by penev92** [comment]
I don't think there has been much discussion on this.

**Comment by abcdefg30** [comment]
Closing as I don't think we get anywhere here.
