### ISSUE TITLE
Grid subdivisions/superdivisions for map editor

### ISSUE THREAD

**Issue by vsevolodZ** [OpenRA/OpenRA#14350]
I was editing my first map lately. And I thought of this ability some graphic editors have.
E.g. by default we could have grid superdivision with 4x4 regular cells marked with thicker lines or another color.
In my opinion this simple (at least it seem so, I'm not sure about this) feature will drastically improve map makers productivity, especially when they deal with symmetric maps.

**Comment by abcdefg30** [comment]
There is an option to show the grid in the editor.
