### ISSUE TITLE
Dead cacti render in incorrect palette

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#14362]
Easiest to see by blowing up the barrels near the oil derricks in "Behind the Veil".  See screenshots in #14314.

**Comment by Arular101** [comment]
Ah, to me it looked weird too, but I didn't know it was a bug. Well spotted!

**Comment by FrameLimiter** [comment]
∙All the RA desert trees have incorrect burn palettes.
∙All the RA desert tree husks are in the wrong palette.
∙Desert tree T09 burn animation has a bad offset.
∙Desert tree husk T09.Husk is missing from the editor: "ExcludedTilesets" -> "RequiresTilesets".

![desert trees](https://user-images.githubusercontent.com/22008761/32901326-8cc754f4-cabd-11e7-9661-55bb1bbb8422.png)

**Comment by GraionDilach** [comment]
>∙All the RA desert trees have incorrect burn palettes.

This one should be fixed via axing Burns in favor of WithIdleOverlay + negative SelfHealing (WIO supports custom palettes already). The actual burn animation size could then be decided from the tree's health status (more damaged-bigger burnanim).
