### ISSUE TITLE
Cant open replay files directly

### ISSUE THREAD

**Issue by xy2z** [OpenRA/OpenRA#14360]
In the last release (`release-20170527`) I could just click an .orarep file and OpenRA would open up and start playing the replay. But since I upgraded to the newest release I can't do that anymore.

I've tried used 'open with' openra.exe but it just opens OpenRA without playing the replay.

I'm using Windows 7.

**Comment by GraionDilach** [comment]
This isn't a bug but a necessity required to improve mod support and individual engine versions. See #12554.

**Comment by penev92** [comment]
Like @GraionDilach said, dropping that feature was necessary in order to move forward with the engine development plans.
Sadly it probably will not be coming back.

**Comment by pchote** [comment]
Instead, as a replacement, there is a plan to add support for a URI type handler (which do work with individual engine versions) that will let the game stream replays directly from the internet.  This then cuts out the step of downloading replays completely.
