### ISSUE TITLE
GivesBounty>LevelMod is calculated wrong

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#14381]
Currently it is increasing too quick. For ra mod (and default values), it goes from 10% on normal to 50% on 1 star. It is adding 125% (default value of LevelMod) on each level after first one, as can be seen at http://openra-red-alert.wikia.com/wiki/Veterancy

I think what should happen is either getting 125% of previous level's value (10-12,5-15,625-19,53125-24,414065) or 125% of original value (10-12,5-15,17,5-20). First makes more sense to me, but latter is more straightforward.

**Comment by Arular101** [comment]
I think the latter is better because of rounding issues.

**Comment by Smittytron** [comment]
Probably an unpopular opinion, but I wouldn't mind seeing bounties not increase on veterancy. Feels a bit like it's punishing the player for getting their units ranked up before losing them.

**Comment by Arular101** [comment]
I wouldn't mind that ether. Also considering #14301 will make vetted infantry a little bit stronger because of no rounding issues anymore.

**Comment by MustaphaTR** [comment]
> Probably an unpopular opinion, but I wouldn't mind seeing bounties not increase on veterancy. Feels a bit like it's punishing the player for getting their units ranked up before losing them.

I don't think this is an unpopular opinion. tbh, i thought this was the opinion came off last discussion about ra bounty was to remove that, but nothing has been done. Looking at the calculation, even setting it to 100 would remove it i guess so this needs to fixed even to remove it i guess.

**Comment by GraionDilach** [comment]
@Smittytron Sure, you can make LevelMod to 100 in RA to work around the core bug and while your opinion would be fulfilled, the bug would still stay in the engine.

I'd say LevelMod should be scrapped entirely to be replaced with conditional GivesBountyMultipliers. Veterancy alone might not be the sole thing which would affect bounty in the long term - Generals salvage crates came to my mind, or I dunno, Industrial Plant, individual unit upgrades...

Although that would make the implementation a bit tricky due to passengers.

**Comment by MustaphaTR** [comment]
#14363 makes `GivesBounty` conditional, we can just get rid of `LevelMod` and use multipile GivesBounty traits. (Multipile `GivesBounty` is already possible, without conditions, it doesn't help much tho.)

**Comment by GraionDilach** [comment]
Wrong, even the current stage of #14363 can't handle multiple GivesBounty traits - https://github.com/pchote/OpenRA/blob/9f851698d9571ebe8608868e951a182fb759bd48/OpenRA.Mods.Common/Traits/GivesBounty.cs#L81.
