### ISSUE TITLE
/givecash(all) can give negative cash and cause player's total cash to go negative

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#14385]
Taking cash is nice, it is not the real issue. But if we try to remove more cash than player has, it should end up at 0, not fall to negatives.
![resim](https://user-images.githubusercontent.com/7933210/32989227-44af49fc-cd23-11e7-9206-14c13e81c30f.png)

**Comment by GSonderling** [comment]
Seems very straightforward. The question is, if there is really no use for negative cash.

I can't think of any, but it still might be worth it to ask.

**Comment by reaperrr** [comment]
Fixed in ^.
