### ISSUE TITLE
WithTextDecoration trait doesnt change the colour of the owner when owner changed with lua

### ISSUE THREAD

**Issue by airetaM** [OpenRA/OpenRA#14389]
UsePlayerColor: True
Wont work in this case

**Comment by pchote** [comment]
The problem is that `WithTextDecoration` implements `INotifyCapture` when it should be using `INotifyOwnerChanged`.  This is an easy two line fix.

**Comment by pchote** [comment]
`WithTextControlGroupDecoration` suffers from the same issue, and has the same fix.

**Comment by pchote** [comment]
Fixed by #14391.
