### ISSUE TITLE
Crash when starting - Game.Mod argument missing 

### ISSUE THREAD

**Issue by Invexis** [OpenRA/OpenRA#14396]
Hi, i can't start the game at all and get this message:

"Open RA has encountered a fatal error and must be close. Refer to the crash logs and FAQ for more information"

The logfile:

```
OpenRA engine version release-20171014
Date: 2017-11-21 09:12:18Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Game.Mod argument missing.
   bei OpenRA.Game.InitializeMod(String mod, Arguments args)
   bei OpenRA.Game.Initialize(Arguments args)
   bei OpenRA.Program.Run(String[] args)
   bei OpenRA.Program.Main(String[] args)
```

Didn't find a solution in the issues and the  #faq.
Thanks in advance!

**Comment by penev92** [comment]
Don't run "OpenRA.exe". Since last release and the removal of the Modchooser, we have dedicated exes for each mod. Run those instead:
```
Dune2000.exe
RedAlert.exe
TiberianDawn.exe
```

**Comment by pchote** [comment]
We really should add an entry to the FAQ about this.

**Comment by Invexis** [comment]
Ok, got it. Thanks!
