### ISSUE TITLE
Get the remaining Harkonnen missions into the playtest

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#14392]
Since @MustaphaTR has all of them locally finished and ready for review, we should try to get them all reviewed and merged before the playtest branch-off (or before the 2nd playtest at the latest), as the first completed campaign would make for a nice advertiser.

- [x] Harkonnen 5 #14388
- [x] Harkonnen 7 #14426
- [x] Harkonnen 8 #14427
- [x] Harkonnen 9a #14429
- [ ] Harkonnen 9b #14434

**Comment by reaperrr** [comment]
@MustaphaTR I think we'll get the remaining 4 reviewed and merged faster if you file the PRs all at once, since it allows us to review the next even if there are fixes/changes requested on the previous one.

**Comment by MustaphaTR** [comment]
Will do. I'm already onto sending the Har7.
