### ISSUE TITLE
multible upleveling the ranks with one kill?

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/OpenRA#14409]
When a rockedier kills 9 soldiers, he will get 3 rank levelups and my respect,
but when he killes a harvester (cost even more that 900) he only gets promoted once.
In a nutshell, it's worth building more expensive units because your opponent can level up less.

**Comment by pchote** [comment]
A related idea that has been discussed in the distant past is to make units gain experience as they deal damage, not just when they take the killing blow.  That would have a side effect of fixing this issue.

**Comment by TheRaffy** [comment]
Lol, people would start to shoot their own walls, buildings or harvesters to repair them again just to gain the rank advantage. Blobs of mechanics and medics would get a new meaning. 
Would add some funny meta games. but might be to much in favour of the allies factions. ;D
Or it would require some friendly fire chekcs, but the medic/mechanics problem would be the same.

**Comment by MustaphaTR** [comment]
> Lol, people would start to shoot their own walls, buildings or harvesters to repair them again just to gain the rank advantage. Blobs of mechanics and medics would get a new meaning.

You don't get xp from own or ally units.

**Comment by theKalash** [comment]
> When a rockedier kills 9 soldiers, he will get 3 rank levelups

Sounds like a bug to me. Are you sure this is the case? Rocket soldier is 300$

GainsExperience condition for level up is 200%, 400%, 800% and 1600% for each level. 

Thus a rocket soldier should require the following amounts killed to level up: 

vet1: 600$
vet2: 1200$
vet3: 2400$
vet4: 4800$

Killing 9 rifle infantry should get you halfway to vet2 but no where near vet3.

**Comment by Smittytron** [comment]
Experience gain is working as expected. 1 rank-0 rocket killing 9 rifles yields one rank up, not 3. Also, killing something several times a unit's value provides multiple rank ups. A harvester is 1100 and a rocket needs 1200 for 2 ranks so this is working as expected.
