### ISSUE TITLE
Enhanced briefings

### ISSUE THREAD

**Issue by vsevolodZ** [OpenRA/OpenRA#14411]
I thought of an ability to have advanced briefing for missions, some formatting and pictures maybe, probably separate popup window to show advanced briefing page. Consider it as low budget alternative to video briefings.

**Comment by CH4Code** [comment]
Seconded. I would like to see these briefings displayed after loading the map, pausing the game until all players (non-spectators) have read and closed those briefings.

**Comment by abcdefg30** [comment]
You could make it a video and display that, for now.

**Comment by abcdefg30** [comment]
I don't think this is feasible for the default mods.
