### ISSUE TITLE
Review use of Exts.IsTraitEnabled

### ISSUE THREAD

**Issue by RoosterDragon** [OpenRA/OpenRA#14445]
`Exts.IsTraitEnabled` is being used against a collection of `TraitInfos` rather than traits in some places. It only works against traits. See https://github.com/OpenRA/OpenRA/pull/14444#discussion_r153314007.

We should review all usages and correct them.

**Comment by RoosterDragon** [comment]
Fixed some of it in #14477. I'll fix the tooltip stuff in #14444.

The one other non-tooltip related bad use I can see is https://github.com/OpenRA/OpenRA/blob/6dd42f7ab1e0cc9674c9a40398c760f94c82e45e/OpenRA.Game/Actor.cs#L141

This runs `Exts.IsTraitEnabled` on an `int2` which is always true.

However the correct method is unclear here.
- If we moved the check against the trait, what happens if there are no matches? Should it be `First` and throw? Should we use `FirstOrDefault` and assume no render bounds if there are no matches?
- `DetermineRenderBounds` only runs once at actor creation. Therefore traits enabling/disabling themselves will be ignored - do we need to change this to refresh every tick? If so we have a much bigger change on our hands as a lot of consuming code relies on `RenderBounds` being invariant. It would also have to be modified to receive updates when the bounds change.

**Comment by RoosterDragon** [comment]
@reaperrr - you refactored the bounds stuff recently - how is it intended to work?

**Comment by reaperrr** [comment]
@pchote has another refactor of the render bounds stuff in the pipeline, I'm sure he'll fix this as part of that.

**Comment by pchote** [comment]
Yes, `DetermineRenderBounds`, `IAutoRenderSize`, and a bunch of related code are about to disappear.

**Comment by RoosterDragon** [comment]
And indeed is had done so with the merging of #14482. Looks like that's everything.
