### ISSUE TITLE
The APC is only using the AA turret variant

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#14463]
In Tiberium Dawn the APC has two different turrets:
apctur.shp (barrels point at the sky) and apctur2.shp (barrels point at the ground).

Currently apctur2 isn't being used, so whether your target is in the air or on the ground, the APC always looks like it is shooting into the sky.

**Comment by reaperrr** [comment]
This most certainly requires code changes, as the turret sprite would have to change depending on current target-type (or -altitude).

**Comment by GraionDilach** [comment]
We could use WithAttackAnimation to set the turret up for the AA weapon and GrantConditionOnAttack to delay it being retracted.

**Comment by pchote** [comment]
The main issue is that the turret artwork is broken (bad pixels on many facings).

**Comment by FrameLimiter** [comment]
Closing as duplicate of #2125
