### ISSUE TITLE
Tiberian Sun - Invisble mechs

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#14462]
Just when I wanted to check the bleed to look for a bug, I found another one @.@
![invisible](https://user-images.githubusercontent.com/11763228/33457877-be37e7c4-d602-11e7-9def-09ebd2b2baba.gif)

**Comment by abcdefg30** [comment]
See #14450.

**Comment by reaperrr** [comment]
Fixed by #14482.
