### ISSUE TITLE
AI considers its harvesters 'idle' way too often

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#14467]
In short, the check for idle harvesters in HackyAI is flat out crap, making the AI perform expensive, map-wide resource searches far too often.

**Comment by airetaM** [comment]
Thats true, the best testcase for that is to make a map with some playerspawns and no ore.
After a while when he builded his proc the harvesters drive back and forth all the time and the game will get more and more sluggish. 
If you make the proc unbuildable, the game will run smooth but the ai don't build any units.
That makes the ai useless for games without minerals.

**Comment by GraionDilach** [comment]
The AI also can crash the game when it tries to order paradropped harvesters while they're still in the air. Fun times.
