### ISSUE TITLE
Units Hidden by Gap Generated Shroud Are Receiving Return Fire

### ISSUE THREAD

**Issue by Omnomon** [OpenRA/OpenRA#14475]
Under normal fog of war and natural shroud, actors that are unable to see enemy units cannot automatically fire or return fire.  However, an actor that is hidden by gap-generated shroud will take return fire when the actor in question fires upon an enemy. The actor will not be auto-targeted so long as he does not fire, but the moment that actor shoots, the enemy will return fire. 
 
Steps to reproduce in release: Build a Tesla Coil, build an enemy gap generator next to it or move an enemy MGG 7 cells away from it, place a V2 6 cells away from the tesla coil (within tesla coil firing range, but beyond its RevealsShroud@gapgen range), and have the V2 fire on the Tesla Coil. Alternatively, one could set RevealsShroud@gapgen for a rifle infantry to 1c0  in a custom map and test it that way. 

The RevealsShroud@Gapgen for most units is close enough to their normal RevealsShroud range, so when Gap Generators do get built, there is no way for the player to tell if his opponent has vision into the gap generator; most of the time, I just assume my opponent had an aircraft providing vision or that my units were just within the RevealsShroud@Gapgen range of a unit. I just happened to come across this while I was trying to make the MGG more useful in a modded map.

**Comment by pchote** [comment]
This actually has nothing to do with gap generators.  The retaliate-on-fire logic doesn't do *any* visibility checks.  You can demonstrate this by reducing the tesla coil vision range to 1 cell and then repeating the testcase above without the gap generator.

Closing to avoid confusion, but you may want to make a new issue about the real bug.

**Comment by pchote** [comment]
Note that this also strongly contributes to the "rush forward" misbehaviour that units show when attacked by artillery in the Attack Anything stance.
