### ISSUE TITLE
If there is no RearmBuildings available, helis land and freeze the game.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#14479]
I was working on #12596 and noticed this. Should be fixed for map to properly work.

To test you can just slap Chinook's LandableTerrainTypes to Hind or Longbow and use all their ammo while there is no helipad for them to rearm. In fact, they try to land without LandableTerrainTypes too, but as they can't game doesn't freeze either.

May be a regression from lastest ammo refactors.

**Comment by reaperrr** [comment]
HeliAttack goes into an infinite loop somewhere.

**Comment by reaperrr** [comment]
Not a regression (previous release already has this bug, I just checked), just another confirmation our aircraft activities are crap.

Since it doesn't affect the shipping mods by default, not a must-fix for next release, but we should at least aim for the planned activity refactor to be finished for Next+1.

**Comment by MustaphaTR** [comment]
I wanted to get Red Zone into the next version, but with that many blockers, looks like it has to wait.

**Comment by MustaphaTR** [comment]
I have investigated that a bit, after landing, unit is entering an infinite loop between [HeliAttack](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Activities/Air/HeliAttack.cs#L79) and [HeliReturnToBase](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Activities/Air/HeliReturnToBase.cs#L63) activites because of the lines i linked.

Also, IMO that landing needs a LandOnIdle check and, if LandOnIdle is false it shouldn't land to ground.

**Comment by MustaphaTR** [comment]
The code i linked above at HeliAttack doesn't looks like working anyway. After rearm, helicopters go to rally point, not continue to attack where it was attacking, which is the bahaviour we want i think.

If current behaviour is really fine, we can get rid of that dead code, which would fix the freeze.

**Comment by reaperrr** [comment]
While it doesn't directly affect the shipping mods (not counting mod maps), it should be an easy fix, so we should really try to get this sorted before next playtest.
