### ISSUE TITLE
RA - Bridge Repairing/C4ing is broken.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#14483]
Bridge Repair Huts are no longer working on bleed, should be caused by lastest changes to selection.

**Comment by pchote** [comment]
Which mod?  Works fine for me on bleed in TD.

**Comment by MustaphaTR** [comment]
RA. TD works fine indeed. TS is a bit obivious to work, its repair huts are visible.

**Comment by pchote** [comment]
Ok.  Confirmed that this is fixed by #14482.

**Comment by KOYK** [comment]
For some reason i get this bug on RA mod in desert tileset on river bridge.  Notice: made a new map and i haven't test this on existing maps.

**Comment by MustaphaTR** [comment]
RA desert bridges are not destructible, it is another bug that i think we have an issue for.
