### ISSUE TITLE
/givecash(all) defaults to info.cash when given floating point numbers

### ISSUE THREAD

**Issue by PapaSquawk** [OpenRA/OpenRA#14488]
**Reproduce:**
1. Open a single player game
2. Prompt for the chat window
3. Enter the /givecash or /givecashall command followed by a floating point number
    _i.e /givecash 5.5 or /givecashall 5.5_
4. The cash given to the player defaults to the info.cash value of 20000

**Expected Behavior:**

- The player would receive an integer value that was truncated from the floating-point argument.

After looking through the implementation of the /givecash logic with the default value residing at 20000 for any non-integer; adding functionally to accept floating point numbers may be of use for some custom /givecash values implemented by the community.

**Comment by Crusader117** [comment]
- Possible fix for this bug: 3c569f65e1a35080fab3d911c2f11ddb08cef287

**Comment by pchote** [comment]
This seems like a reasonable thing to fix.  Do you want to file a PR?
You could simplify your commit by forgetting about `int.TryParse`, since parsing an int as a float and then casting would give the same result anyway.

**Comment by Crusader117** [comment]
I have simplified the commit and have filed for a PR: #14490
