### ISSUE TITLE
If there is an always active ReloadAmmoPool trait, units don't stay on their RearmBuildings

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#14480]
So you can't really make a unit reload slowly on air and quicky on a helipad for example. If the building is their RearmBuilding too at the same time, manual rearming works while repairing is being done too, but unit leaves as repair is completed.

Even wierder behaviour is this only happens if ReloadAmmoPool is always active (i.e doesn't require a condition). If it requires a condition, even when condition is granted, unit acts like it doesn't have the trait.

**Comment by reaperrr** [comment]
> Even wierder behaviour is this only happens if ReloadAmmoPool is always active (i.e doesn't require a condition).

At least this part is basically just a wrong yaml setup.
The idea is that if you want to *accelerate* reloading, you should *disable* the slow self-reloading `ReloadAmmoPool` and enable only the one with faster reload rate while on the helipad, a single AmmoPool should *never* have more than 1 enabled `ReloadAmmoPool` traite assigned to it (may need a lint or Ruleset loading check to enforce this).

> If it requires a condition, even when condition is granted, unit acts like it doesn't have the trait.

This sounds like a genuine bug, though. I'll see if I can find something.

> If the building is their RearmBuilding too at the same time, manual rearming works while repairing is being done too, but unit leaves as repair is completed.

Note that the refactor of the rearm/repair interaction is incomplete, #14357 is next in line. It's a little unfortunate that some use-cases other than the default RA/TD behavior doesn't work yet, but we simply had too many larger issues that needed to be taken care of first, so this will have to wait for Next+1.

**Comment by MustaphaTR** [comment]
> At least this part is basically just a wrong yaml setup.
The idea is that if you want to accelerate reloading, you should disable the slow self-reloading ReloadAmmoPool and enable only the one with faster reload rate while on the helipad, a single AmmoPool should never have more than 1 enabled ReloadAmmoPool traite assigned to it (may need a lint or Ruleset loading check to enforce this).


Actually, that's what i did. With an always active ReloadAmmoPool, i was talking about something like what TD mod has, one that doesn't require a condition and always work.

**Comment by reaperrr** [comment]
That's my point. 
If you want an AmmoPool to reload faster while on a RearmBuilding, you must not use any "always active" ReloadAmmoPool for that AmmoPool at all.
An always-enabled ReloadAmmoPool implies "this AmmoPool doesn't benefit from landing at a RearmBuilding at all". There must never be more than one active ReloadAmmoPool at a time for that AmmoPool.

If you want an actor that self-reloads like TD aircraft while in the air, but reloads faster while landed on a pad/airstrip/whatever, taking TD as example you'd have to change the yaml rules of Orca/Apache to something like this:
```
ORCA:
(...)
	ReloadAmmoPool@SELFRELOADING:
		Delay: 100
		Count: 2
		RequiresCondition: !docked-to-helipad
	ReloadAmmoPool@HELIPAD:
		Delay: 50
		Count: 2
		RequiresCondition: docked-to-helipad
```

**Comment by MustaphaTR** [comment]
Reason why it is only happening for always active ones is that game is checking if there is a `ReloadAmmoPool` with `RequiresCondition == null` in `INotifyCreated.Created` rather than `!IsTraitDisabled` in `Tick` to determine if an actor Auto Reloads. https://github.com/OpenRA/OpenRA/blob/d602ec6485d06257ed30ab3fff44b34a78ff10a5/OpenRA.Mods.Common/Traits/AmmoPool.cs#L107

I guess i should wait #14357 to make Red Zone. Tyring to stuff in the middle of refactor is not helping. I'll try to review that when i find time.

**Comment by pchote** [comment]
@MustaphaTR can you please retest this after all the recent aircraft and repair/rearm changes?

**Comment by PunkPun** [comment]
`ReloadAmmoPool` trait no longer exists
