### ISSUE TITLE
32-bit PNG spritesheets support for tiles and actors

### ISSUE THREAD

**Issue by katzsmile** [OpenRA/OpenRA#14498]
Can we have 32-bit PNG spritesheets support for tiles and actors?

like this example from Factorio game:
[car.zip](https://github.com/OpenRA/OpenRA/files/1550687/car.zip)

**Comment by Mailaender** [comment]
Duplicate of https://github.com/OpenRA/OpenRA/issues/5589

**Comment by katzsmile** [comment]
duplicate issue is dated back to 2014, we still need it, 256 bit limitation for sprites in 2017-2018 is a bit eww

**Comment by Mailaender** [comment]
Please continue the discussion at #5589 or add a +1 there to voice your support/wish.
