### ISSUE TITLE
 #13882 breaks loading of some shp

### ISSUE THREAD

**Issue by jrb0001** [OpenRA/OpenRA#14538]
- https://github.com/DoGyAUT/cd/raw/3d893b924fc706d5fb3e7f97eb1d38e19f2b7b06/bits/anims/explos/explosml.shp
- https://github.com/DoGyAUT/cd/raw/3d893b924fc706d5fb3e7f97eb1d38e19f2b7b06/bits/anims/explos/s_bang16.shp
- https://github.com/DoGyAUT/cd/raw/3d893b924fc706d5fb3e7f97eb1d38e19f2b7b06/bits/anims/explos/s_bang24.shp
- https://github.com/DoGyAUT/cd/raw/3d893b924fc706d5fb3e7f97eb1d38e19f2b7b06/bits/anims/explos/s_bang36.shp
- https://github.com/DoGyAUT/cd/raw/3d893b924fc706d5fb3e7f97eb1d38e19f2b7b06/bits/anims/explos/s_bang48.shp
- https://github.com/DoGyAUT/cd/raw/3d893b924fc706d5fb3e7f97eb1d38e19f2b7b06/bits/anims/explos/s_tumu60.shp
- https://github.com/DoGyAUT/cd/raw/3d893b924fc706d5fb3e7f97eb1d38e19f2b7b06/bits/anims/explos/twlt026.shp
- https://github.com/DoGyAUT/cd/raw/3d893b924fc706d5fb3e7f97eb1d38e19f2b7b06/bits/anims/explos/twlt050.shp
- https://github.com/DoGyAUT/cd/raw/3d893b924fc706d5fb3e7f97eb1d38e19f2b7b06/bits/beamzap.shp
- https://github.com/DoGyAUT/cd/raw/3d893b924fc706d5fb3e7f97eb1d38e19f2b7b06/bits/firedustwave.shp
- https://github.com/DoGyAUT/cd/raw/3d893b924fc706d5fb3e7f97eb1d38e19f2b7b06/bits/swave.shp
- https://github.com/DoGyAUT/cd/raw/3d893b924fc706d5fb3e7f97eb1d38e19f2b7b06/bits/swaveb.shp

**Comment by pchote** [comment]
> [10:30:48] | <GraionDilach> also regarding the shpts thingy jrb0001 reported - I noticed that error myself as well
> [10:30:57] | <GraionDilach> but resaving all files affected fixed them

This suggests that it could be a problem with an external tool that has since been fixed.

**Comment by GraionDilach** [comment]
I'm notcertain about it though - IIRC one of them was one of the RA2 crate animations. Probably firepwoer, but I honestly don't remember more certainly anymore.

**Comment by Apollo-X** [comment]
I would guess its the blank frame syndrome again as all the few shps of those I bothered check have blank frames in start or end of shp.

**Comment by pchote** [comment]
```
16:10 <+pchote> ok, I see the cause of that
16:10 <+pchote> xcc appears to trim empty space off images, in this case rounding frames down to 0,0
16:10 <+pchote> but then sets type to 0, which isn't consistent with the original game
16:11 <+pchote> we have specific code that checks for 0,0 and type = 0 as invalid shps, as part of our automatic format detection
```

You can fix the problem by using a hex editor to change the type byte on any empty frames to a non-zero value.  Closing as a tooling issue.
