### ISSUE TITLE
Carryalls fly harvesters to cell 0,0 when a harvester is explicitly ordered to unload.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#14542]
This will be another regression from the order serialization changes.

**Comment by jongleur1983** [comment]
Related issues: #14537 and #14189

**Comment by jongleur1983** [comment]
Steps to reproduce:
preconditions: a Spice Refinere, a harvester, and a CarryAll (of course).
The CarryAll in D2K is autonomous, and as long as no explicit command is given to the harvester, everything's fine.

select the harvester, order it to the refinery. 
As a result (?) the CarryAll takes the harvester and flies away, resulting in a StackOverflowException

**Comment by abcdefg30** [comment]
Fixed in #14558.
