### ISSUE TITLE
NukeLaunch missile appears too early

### ISSUE THREAD

**Issue by ltem** [OpenRA/OpenRA#14541]
The missile will be displayed even if the "launch animation" is still ongoing. It should be hidden till the animation is finished.

|![stuckmissile](https://user-images.githubusercontent.com/20945684/34081445-1b8a2d0e-e34d-11e7-900a-f2ae14d35471.gif)|
|:---:|

I tried to track it down with `git bisect` (result below), not sure if I did that right.

```bash
$ git bisect good
be370cb855e88f38438a2f83aa680787dbe81219 is the first bad commit
commit be370cb855e88f38438a2f83aa680787dbe81219
Author: reaperrr
Date:   Sun Sep 3 21:55:02 2017 +0200

    Spatially partition NukeLaunch effect

:040000 040000 51cc6639a3c578e9f3b63dd089e52f5d40fc4ae9 7f176e9635f2899ac5b35e6ef18089c37a2e1244 M      OpenRA.Mods.Common
```

**Comment by reaperrr** [comment]
I might be missing something, but the only way I can imagine how my PR might have broken this is if it broke DelayedAction in general.

This is the line in question, I don't see how else the missile image could be displayed prematurely:
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/SupportPowers/NukePower.cs#L122

**Comment by pchote** [comment]
The issue is that the `NukeLaunch` constructor immediately adds the effect to the ScreenMap, even if it is not currently in the world.
