### ISSUE TITLE
Spy Plane causes crash with multiple Cloak Traits

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#14555]
Hi, I wanted to give the RA HBOX multiple `Cloak` traits, so it behaves differently when different units are garrisoned. (e.g. not uncloak on attack)
This however causes a crash if the HBOX then gets "hit" with the spy plane reveal which probably has difficulty using a `Cloak` trait which is disabled with `RequiresCondition`.

**Comment by pchote** [comment]
Please post the exception.log.

**Comment by CH4Code** [comment]
Can't reproduce anymore. This bug is ~2 months old. Must have been another bug with spyplane..
