### ISSUE TITLE
Longbow Armament LocalOffset is only utilizing one of its values

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#14577]
In Red Alert the Longbow's Armament LocalOffset doesn't currently alternate between left and right (it only shoots out of one of its two wings). Similar to #14464

**Comment by MustaphaTR** [comment]
Actually it is using one side for AA and one side for AG.

**Comment by reaperrr** [comment]
Which looks silly, though. I'll fix it as part of #14579 (if it doesn't already).
