### ISSUE TITLE
Limit amount of Power Plants AI can build

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#14586]
I'm not sure if we should just give PPs BuildLimits for AI or add a logic to say AI not build more PPs if power level is already over a value.

Currently lack of limit leads to stuff like this:
https://cdn.discordapp.com/attachments/153649279762694144/395272740762025985/unknown.png

**Comment by GraionDilach** [comment]
They should be already limited based on ratios, though.

**Comment by reaperrr** [comment]
We'd probably get the best result by removing powerplants from the ratio lists (so they don't get built randomly) and making the "minimum excess power" logic a bit smarter, at least when it comes to scaling with base size.
