### ISSUE TITLE
misplaced BridgePlaceholder on Tread Lightly (bridge glitch)

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#14592]
![flying](https://user-images.githubusercontent.com/25386322/34397250-c1c25a8c-eb74-11e7-987c-228a4207d3ab.PNG)

I guess a rather unimportend glitch for now but i didn't want to hold it back.

Replay
[OpenRA-2017-12-28T010539Z.zip](https://github.com/OpenRA/OpenRA/files/1590180/OpenRA-2017-12-28T010539Z.zip)

**Comment by MustaphaTR** [comment]
It is not the amphibious transport. That Bridge is set up at 2 cells off.

**Comment by fruestueck** [comment]
The bug is fixed but i've discovered a nother bug concerning bridges. Maby the devs are aware of due to current implementation of tunnels & brindges in work/not finished. Just didnt want to hide this from you.
The APCs "think" they are on the water underneath the bridge.

![bridges](https://user-images.githubusercontent.com/25386322/34457881-8b35f2ec-edbf-11e7-819c-0e9ed79e6d8f.JPG)

Don't know if this patch does the glitch or if it already existed. Needs maby some more testing

**Comment by MustaphaTR** [comment]
That already existed, but it doesn't look like Bridges provide any condition (unlike Tunnels), so doesn't look like a .yaml only fix.

**Comment by pchote** [comment]
`GrantConditionOnTerrain` needs to check the location's `Layer`.

**Comment by fruestueck** [comment]
Sounds like a good entry point to code on OpenRA : )
I will handle that : )
