### ISSUE TITLE
Change Standard Scrollspeed to medium (instead of minimum)

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#14603]
Scroll speed after a fresh OpenRA installation is set too low. I would opt for `medium scroll speed` preset.
If i get more than three horrays here, i'd change that : )

Not representative but a couple of guys in TD agreed on that.

**Comment by Kanar** [comment]
Completely agree.
I set my scroll speed to 160 in the yaml (which places the indicatur in the ui way off the boundries : D ).
But i use edge scrolling only to support my inverted middle mouse scrolling to reach edges of huge maps.

**Comment by Arular101** [comment]
The default scroll speed could indeed get an increase. (It seems that I have it at 25.)

**Comment by xan2622** [comment]
I agree too.
Let's make the first experience of a new OpenRA player... good.

**Comment by LipkeGu** [comment]
👍

**Comment by KhaledSakr** [comment]
I agree. It should be set to 30, which is the middle of the slider (slider range is 10 to 50). Is any taking this or can I change it?

**Comment by fruestueck** [comment]
@KhaledSakr, feel free to look into it. I remember a dev stating on [IRC](http://www.openra.net/community/) that the speed should stay like that for new players. I'd recommend to ask around first : )

**Comment by abcdefg30** [comment]
Closed by #17206.
