### ISSUE TITLE
Spectators don't always show in white in the MP server player list

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#14609]
This requires some special step to trigger, but I don't yet have a repro case.
I encountered this several times while working on the news post screenshots.

Not a showstopper for the playtest, but should be fixed before the final release.

**Comment by FrameLimiter** [comment]
If you pick a snow map and choose dark green (unacceptable color for a temperate map but okay for snow). Then jump into the spectator slot & change the map to temperate, it'll prompt "adjusted color within range and give the spectator a color.
