### ISSUE TITLE
Frozen actors won't show tooltips if the backing actor is cloaked.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#14616]
Caused by 
https://github.com/OpenRA/OpenRA/blob/6633483d121d81402e057a42c4d22c1043c62e1b/OpenRA.Mods.Common/Widgets/ViewportControllerWidget.cs#L255

Using the current real actor state to determine the frozen actor tooltip visibility is bogus.
This data needs to be cached in `FrozenActor.RefreshState` instead.

**Comment by MustaphaTR** [comment]
I'm pretty sure this affets RA mod too due to Camo Pillbox.

**Comment by dragunoff** [comment]
#13545 is probably related to this.
