### ISSUE TITLE
/kill and /dispose desynces mp games

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#14634]
[sync logs.zip](https://github.com/OpenRA/OpenRA/files/1597323/sync.logs.zip)

**Comment by pchote** [comment]
These commands need to be routed through an order that is consumed by the `DeveloperMode` trait, like all our other sync affecting commands.

**Comment by LipkeGu** [comment]
ATM these commands are handled directly inside the devcommand Methods. im on it currently due to #14657 so how i could get this in one walk?
