### ISSUE TITLE
Buildings "blink" when you reveal them

### ISSUE THREAD

**Issue by AndriiYukhymchak** [OpenRA/OpenRA#14645]
When you move into known/unknown part of the map, every building there will blink when you reveal it. Most likely something to do with renderer as building disappears for an instant then reappears

**Comment by pchote** [comment]
Duplicate of #14614 which should have been fixed by #14619?

**Comment by AndriiYukhymchak** [comment]
snap, forgot to check closed ones too. Thanks

**Comment by pchote** [comment]
Can you please confirm that this is fixed for you on the latest bleed / playtest?

**Comment by FrameLimiter** [comment]
Just checked the bleed, it's still an issue. :(

**Comment by pchote** [comment]
This is probably the opposite case to #14614 then.
