### ISSUE TITLE
Orca and Apache aren't returning when you press F.

### ISSUE THREAD

**Issue by dsimmons87** [OpenRA/OpenRA#14641]
In the release version of OpenRA, if you select an Apache or Orca and press F, they return to a helipad to heal, although that isn't working in the current playtest version.

**Comment by abcdefg30** [comment]
Is this also an issue in RA?

**Comment by dsimmons87** [comment]
Just tested RA and it worked fine. Migs, Yaks, Hinds and Longbows all return and rearm if you press f. It might be different though because RA is return to rearm, whereas TD is return to heal?

**Comment by pchote** [comment]
Probably a regression from the `AmmoPool` refactor then.

**Comment by pchote** [comment]
Confirmed that this was caused by #13538 removing `RearmBuildings: hpad` from `ORCA` and `HELI`.  IMO the best fix here is to call this a feature and remove the "Helicopters will return to base" line from the deploy button tooltip.  Tanks don't have a special button to return to the service depot after all.

**Comment by dsimmons87** [comment]
They don't, but you can send them to repair easily by just using the repair tool on them, like you would with buildings. This doesn't work for air though.

Also another strange thing, if you press f on an orca or apache, it seems to turn and face the helipad, but just doesn't move.

**Comment by pchote** [comment]
Indeed.  I addressed all of those points in the description/comments of #14649.

**Comment by dsimmons87** [comment]
Makes sense. So is this just going to get stripped out entirely then? I.e. the F key on an Orca or Apache does nothing?

I only ask because at the moment, they do turn to face the helipad as if they are thinking about going back.
