### ISSUE TITLE
Selling structures gives no refund. (TD and RA tested. Playtest)

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#14644]
Many structures and buildings in the playtest when you sell don't give any value or incorrect money values back. (IE: Selling a MCV in TD gives nothing. Selling the airfield gives 50$ back.)

This also applies to RA with a few I saw such as selling an Allied tech center gave about 50$ back while selling an airfield gave nothing.

**Comment by FrameLimiter** [comment]
It appears to be caused by the HP x100 scaling.
RA AFLD with 100000hp = -$179
RA AFLD with 1000hp = $250

**Comment by pchote** [comment]
Sounds like an integer overflow issue.  We will need to look out for similar bugs in other places where the health is multiplied with other things.

**Comment by pchote** [comment]
RA has actors with up to `1000000` health, which is only a factor of ~2000 less than Int.MaxValue.  That leaves nowhere near enough room to do calculations with.

**Comment by AndriiYukhymchak** [comment]
yep... and also when you sell refinery with resources you can get really borked

**Comment by pchote** [comment]
The simplest fix here is to make sure that anything that wants to multiply the health first casts it to a `long`.

**Comment by Arular101** [comment]
I can think of 3 solutions:
1 - What @pchote said, using a `long`.

If we don't want that:
2 - We can use the way it is calculated in the [tooltip](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Sellable.cs#L97). This works with the biggest values used in the shipped mods (works in the playtest). The calculation is split in two steps, but is still very close to the Int.MaxValue.
3 - Before multiplying the HP with the SellValue, the HP and MaxHP can be divided by 100. This will bring it back to how it was before.

Which one is the preferred solution? Then I can make a PR changing both the sell calculation and the tooltip calculation.

**Comment by pchote** [comment]
1 please.

**Comment by fruestueck** [comment]
it would also be possible to remove the 100 multiplier but maby not the best : )

**Comment by anjew175** [comment]
> It would also be possible to remove the 100 multiplier but maby not the best solution : )
Sadly not, the multiplier was added [here](https://github.com/OpenRA/OpenRA/issues/11719) to fix possibilities like [this](https://github.com/OpenRA/OpenRA/issues/11425)
