### ISSUE TITLE
Units refuse to stop on high bridges

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#14647]
I suspect that the evict-from-tunnel code is forcing them to move off.

**Comment by fruestueck** [comment]
Also, when an amphibios unit (APC) is stopped while on bridge, it sets the movetarget beneth the bridge (where you pressed Stop)

**Comment by pchote** [comment]
Indeed - the viewport-level code and the rest of the order targeting need to be taught about custom movement layers.  This is one of two major parts of work involved in #8917.

This issue specifically focuses on the bug where the stop hotkey/commandbar button doesn't work for units that are already on high bridges.

**Comment by BGluth** [comment]
Ah right. I misinterpreted that.

**Comment by tovl** [comment]
The stop command seems to work for units on high bridges now.

**Comment by fruestueck** [comment]
> The stop command seems to work for units on high bridges now.
Confirmed. Units can now also attack while beeing on a bridge.
