### ISSUE TITLE
Player names lobby tooltip

### ISSUE THREAD

**Issue by dsimmons87** [OpenRA/OpenRA#14643]
When you hover your mouse over the player count for playtest game in the lobby, it shows a tooltip with the players in the game. If the player name has a < symbol, it replaces it with &amp;lt;, and the same for > with &amp;gt;. I haven't tested all symbols, but there might be more that have this issue.

Edit: &amp;lt; was getting replaced with &lt; in this github comment, and the same for >.

**Comment by pchote** [comment]
<img width="251" alt="screen shot 2018-01-02 at 23 35 01" src="https://user-images.githubusercontent.com/167819/34513236-2c86226a-f05f-11e7-9559-1cd83ba319de.png">

**Comment by pchote** [comment]
This is a master server bug.  See https://github.com/OpenRA/OpenRAMasterServer/issues/52.
