### ISSUE TITLE
Fremen spawning from the wrong palace

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#14660]
From https://logs.openra.net/?year=2018&month=01&day=04#02:26:53

>[02:25:52] | < muh> Hi
>[02:26:53] | < muh>  I noticed that if you capture both the atreides and the corinno palace  in Harkonnen 9a (and 9b I assume) fremen support power spawns at the  corinno palace instead of atreides
>[02:27:08] | < muh> I dont know if that is expected behaviour but I guess not

**Comment by MustaphaTR** [comment]
Related to https://github.com/OpenRA/OpenRA/issues/14460

**Comment by pchote** [comment]
Adding a faction condition requirement to the production trait should fix this.

**Comment by MustaphaTR** [comment]
I would prefer faction condition (as it would be more useful for other traits too). And disable the production trait or PAP (or both) with the condition. I already coded it tbh. But needs some more work before filing a PR.
