### ISSUE TITLE
crash at intial startup

### ISSUE THREAD

**Issue by sweitzzzz** [OpenRA/OpenRA#14665]
The game experience a fatal error and must close at start up.

The only thing in any of the logs is in perf and it says 3 ms LoadMaps

I'm brand new to this so thank you in advance,

**Comment by LipkeGu** [comment]
please post the logs anyway

**Comment by sweitzzzz** [comment]
3 ms LoadMaps

I'm running windows 7 home premium
I think this is my display driver but I'm not sure. Again I'm totally new.
Mobile Intel(R) 4 Series Express Chipset Family
I'm unfamiliar with Linux

**Comment by LipkeGu** [comment]
> Mobile Intel(R) 4 Series Express Chipset Family

Try to update your Display driver :) from HERE: https://downloadcenter.intel.com/product/81507/Graphics-Drivers-for-Mobile-Intel-4-Series-Express-Chipset-Family

If you are using the Windows (own) included driver, then you should use the Vendor driver.
Microsofts OpenGL extensions lacks features that we need.

**Comment by sweitzzzz** [comment]
Thank you for trying to help me.

 I tried to update the display driver but it was already at the most up to date version. What do you mean by Vendor driver?

**Comment by LipkeGu** [comment]
When you are installing Windows or use Windows update it can update your drivers. OpenRA needs OpenGL extentions which are not available when you are using a driver which is shipped directly with Windows. We have a lot of issues with Microsoft related OpenGL extensions. Microsoft also doesnt ships mostly not the complete driver files. They ships mostly the files which are needed to get the driver working. (A Microsoft shipped (with windows) drivers does not have the ATI catalyst control center) 

So you need the vendor driver, Intel (not the microsoft shipped intel driver) 
(i gave you the download link)

> I tried to update the display driver but it was already at the most up to date version.
Did you run the installer which is shipped with the driver?

**Comment by sweitzzzz** [comment]
I installed the driver using the link provided. It appears that my graphics card is not compatible with never versions openGL. It seems to be a common issue with older HP laptops according to google searches.

**Comment by pchote** [comment]
That is a shame.  Unfortunately there is no way around the OpenGL requirement, so there is nothing else we can do here.  Sorry!
