### ISSUE TITLE
20180102 - Mechanics no longer mechanic

### ISSUE THREAD

**Issue by Beep6581** [OpenRA/OpenRA#14662]
Hello

In Playtest 20180102 the mechanics no longer fix nearby vehicles even when I attack-move them in attack anything mode. This used to work before. i.e. in 20180102 the only way to get mechanics to fix vehicles is to instruct them one by one vehicle.

This is further complicated by the fact that if I have a group of 5 mechanics and 5 medics and I click on a vehicle for the mechanics to fix it, the medics climb into the vehicle if it can carry people. Not sure this was the same in previous versions as there was no need to instruct the mechanics to fix vehicles one by one.

**Comment by MustaphaTR** [comment]
I think the issue is that Tank is missing at: https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/rules/infantry.yaml#L419 If that's the issue normal vehicles should be working fine.
