### ISSUE TITLE
"Mission Aborted" line plays even after successful complete

### ISSUE THREAD

**Issue by alercah** [OpenRA/OpenRA#14673]
When you complete a mission, you get a completion dialog that allows you to continue or leave. If you hit leave, you get the "Mission Aborted" audio line, even though it's pretty inappropriate at that point.

**Comment by pchote** [comment]
This is because D2K doesn't have a "battle control terminated" style announcement, and so someone instead decided to use "mission aborted".  It is similarly confusing in MP games.
