### ISSUE TITLE
No warning if a hotkey is used multiple times

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#14670]
There is no warning of any kind when you set a duplicate hotkey. The result is that all of the conflicting hotkey mappings stop working.

On playtest-20180102 but I assume this is also true for current release.

**Comment by LipkeGu** [comment]
Thanks for the info, i suspect it could be a regression...

**Comment by pchote** [comment]
No. This has always been the case.

**Comment by LipkeGu** [comment]
Wrong labels?!

**Comment by ltem** [comment]
I interpreted it as the intended behavior of OpenRA and using a hotkey twice as an error by the user. So giving some kind of warning/error message would be an nice feature/wish to implement.

**Comment by LipkeGu** [comment]
But the title indicates an error. "No Warning when duplicated hotkeys are set" would be better :)
