### ISSUE TITLE
Track player win/loss state on the server.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#14686]
Server-side replay saving and stat tracking both require the server to know when a player wins or loses the game.  This information is currently generated from the client-side world state.

Requiring servers to simulate the game state is an option, but a bad one.

The most feasible option will be to implement a new type of network packet (like sync, but not forwarded to other clients) that contains the player id, result (win/loss) and the tick that the result occurred.  After the server forwards the orders for frame N it can check the results from frame N - OrderLatency and then force a desync if all clients don't agree.  Disconnect results can be set directly from the serverside.

**Comment by oraservers** [comment]
Related to https://github.com/OpenRA/OpenRA/issues/13308

**Comment by ubitux** [comment]
> Requiring servers to simulate the game state is an option, but a bad one.

Why? Too much bandwidth and CPU intensive for the server?

> The most feasible option will be to implement a new type of network packet (like sync, but not forwarded to other clients) that contains the player id, result (win/loss) and the tick that the result occurred. After the server forwards the orders for frame N it can check the results from frame N - OrderLatency and then force a desync if all clients don't agree. Disconnect results can be set directly from the serverside.

Wouldn't that make it too easy for a client to cheat? Always sending a win would prevent any loss to be ever recorded (cheating would involve a simple flip of value sent). Or do you plan to detect such a pattern (too much disagreements would lead to a ban) server side?

**Comment by abcdefg30** [comment]
> Always sending a win would prevent any loss to be ever recorded (cheating would involve a simple flip of value sent).

Yes, I agree that this is a 'gap' in the proposal; off the top of my head I don't know how to prevent this though (if the server has no knowledge of the ongoing game at all). The community is small enough however to be able to spot such a cheater, so I'm not sure if this is going to be a problem in reality.

> Or do you plan to detect such a pattern (too much disagreements would lead to a ban) server side?

Yes, that is what "then force a desync if all clients don't agree" is referring to.

**Comment by pchote** [comment]
If a player wants to desync the game they can send a bogus sync hash on loss instead of a forged loss even packet - the end result would be identical.

**Comment by pchote** [comment]
Fixed by #17578.
