### ISSUE TITLE
Messy d2k building armor types

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#14681]
Hi, 
for my d2kA mod I looked into the building armor types for balance reasons and was shocked.
They are a total mess. There are **seven** types of armor for buildings, some of them shared with units and an armor type called "building", which applies only to some (random collection) of structures. 
Is there a "keep to the original" reason for the armor types of d2k buildings being an absolute mess? Someone must have exported those from the original files. 
To me it makes no sense whatsoever to have 7 different armor types randomly scattered among all structures. 

In an experiment I reduced them to "building" for all buildings except conyard which has "cy" armor and all defensive structures with "heavy" armor, except wall ("wall"). (even medium and large gun turrets had different armor types! o.O ). It had a positive effect on playability (trikes and infantry damage output vs buildings reduced to a reasonable level). 
Not to mention that right now this game is un-balanceable, because of hidden ties and multiple things that do the same thing.

If you agree I would post a PR including `^Building:Armor:Type: building` and `^Defense:Armor:Type: heavy`  into `defaults.yaml` and some deletions and fixes in the other yamls.

**Comment by pchote** [comment]
#14461 had some discussion about this.

**Comment by CH4Code** [comment]
I did some research
![messeduparmortypes](https://user-images.githubusercontent.com/16046997/34654129-6a239b52-f3f7-11e7-9735-05cdefc84542.png)
which reveals that the ora behaviour has nothing to do with the original (gruntmod edition). At least you would expect that the result of sorting by any column is the same, which isn't the case.

My guess for the mess with armor types is that weswood didn't use the armor types for buildings in their code in the end, hence they didnt care what a mess it was. My experiment isn't correct, but closer than current ora.
What I'm trying to say is that to replicate original behaviour damage values and armor types need to be reassessed, and if that needs to be done, we could use armor types that make actual sense.

**Comment by MustaphaTR** [comment]
I did some calculations with some buildings HP, damage value of trike and warhead values i see on TibEd and your required attack test values. Looks like trike is actually doing 20% damage to each building, independent of their Armor. So maybe buildings actually use CY armor. I'll do some more calculations.

**Comment by MustaphaTR** [comment]
Ok, this is what i found from my testing. I got different percentages ranging from 5 to 25, and it doesn't match the armor types. I tested with 1 trike:
![resim](https://user-images.githubusercontent.com/7933210/34667039-53bf8b2e-f478-11e7-9792-cae57b569115.png)

**Comment by MustaphaTR** [comment]
After messing with the values on TibEd, i found the real porblem. Armor trait in there doesn't do anything default values there are wrong.

**Comment by CH4Code** [comment]
So is TibEd not working on d2k or d2k game not using these values?

**Comment by MustaphaTR** [comment]
Armor: value on Building section of TibEd doesn't effect anything. Actual values D2k uses are ones above. I'll make a PR and send a .tib file for testing.

**Comment by CH4Code** [comment]
Now that almost looks like the stuff I experimented with! ^^ go ahead and take over the PR.

(Don't know if this list is needed now, but post it for checking anyway:)
![combattankarmormess](https://user-images.githubusercontent.com/16046997/34671487-258577e8-f47b-11e7-8d32-c8a83b2eb6ba.png)
