### ISSUE TITLE
[Question] New selection box system.

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#14687]
I am confused, the selection box of the turrets is defined by the size of the sprite body of the unit, and seems to ignore the turret size if able, the first turret has a valid sprite body while the second has all the graphics contained in the turret, what do I do here?

Rendering the second turret again is not an option, both units share the same inheritance / code.

![imagen](https://user-images.githubusercontent.com/11763228/34656335-d50bfd20-f3f6-11e7-98c4-79f4ea1adfaa.png)

**Comment by pchote** [comment]
Use the `DecorationBounds` property on `Selectable` to define the rectangle that you want.

**Comment by ABrandau** [comment]
I use the following traits on the turret and still get the single pixel selection box.

	Selectable:
		Bounds: 40, 30, -3, -8
		DecorationBounds: 40, 36, -3, -8
	SelectionDecorations:
		Bounds: 40, 30, -3, -8
		DecorationBounds: 40, 36, -3, -8

**Comment by pchote** [comment]
What engine version are you using?

**Comment by ABrandau** [comment]
AS Fork, and I just did the test in the current ORA bleed, and your code works there.

**Comment by ABrandau** [comment]
Just in case, this bug was causes because I added the Interactable trait on ^SpriteActor.
