### ISSUE TITLE
Refresh RA mod map pool

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#14698]
Meta issue to self and to support the discussion if required.

I'd like to revise and update the RA official map pool, as there are some popular community 1v1 maps which deserve being available for the greater number of people, also the team/FFA map would benefit from new maps.

**list was moved to [PR 14768](https://github.com/OpenRA/OpenRA/pull/14768), check there**

Feel free to comment, give feedback and provide reasons for/against any of the maps.

**Siberian Pass**: I feel it has outlived its time and is now quite "inefficient" in terms of gameplay - lots of chokes, snaky nature, refinery placement tends to be unoptimal and unbalanced between player positions. Also starting ore mines are away from each other yet in range of ore truck seeking range, so trucks tend to jump from one to another often.

**Comment by Smittytron** [comment]
I've been thinking about doing this. Main thing I'd like to see a consensus on is how many official maps per player count do we want, and which maps are untouchable?

**Comment by Arular101** [comment]
I would like to mention the winners of the [Map Design Contest 2017](http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=20044):
[
Unconventional Warfare](https://resource.openra.net/maps/20317/) - FFA (7 players) - by PizzaAtomica (second place of the MDC2017)
[Apocalypse Now](https://resource.openra.net/maps/22288/) - 1v1 - by ACM (RA-mod category winner)
[Climax](https://resource.openra.net/maps/22335/) - 2v2 - by Wippie (2v2 category winner)
[Gleann Uileloscadh](https://resource.openra.net/maps/20327/) - 3v3 - by Mac Díarmata (Big map category winner, and personal favorite)

These maps are the winners of the contest without custom rules.

**Comment by Arular101** [comment]
I also would like to mention a new version of [Behind the Veil (v3.2)](https://resource.openra.net/maps/24089/). This version makes the map quite different, but you guys know better if this version is an improvement over the current version (v2.4).

**Comment by airetaM** [comment]
I would like to see some more not mirrored maps in the selection.
The map pool would look like a gathering of mandalas with all these maps inside, except of "Rapa nui" and "Gleann Uileloscadh".
You should also look for optical glitches and repair them before putting them in.
Best you discard "Apocalypse now" btw hehe this map cant be repaired without changeing it from scratch.

**Comment by netnazgul** [comment]
@Arular101 yes, I've missed Unconventional Warfare and would probably add that, as well as Climax. 
Not sure on Apocalypse Now because it plays much worse than it looks (subjective); Gleann is also a visually appealing map, but I fear this map won't produce interesting games because it's too choky and low-eco, which leads to stale and long gameplay. 
As for BtV update - I'm not sure on it, just felt too weird and complex to me and didn't get as much popularity around as well.

@airetaM the problem with non-mirrored maps is usually that they are tough to correctly balance because they get unbalanced by definition.
I would like to see those too, if only there were at least some of them drawn.

**Comment by FRenzy-OpenRA** [comment]
Ok for the list.
From my [list on the forum ](http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=306194#306194), after testing the maps, I'd suggest looking into : 

- [Outdoor trails ](https://resource.openra.net/maps/21397/) : although map is quite huge for 4 players, it can create really intense games, where you really have to look everywhere for flanks. Games are longer, but very interesting. 
- [Sude's Digest](https://resource.openra.net/maps/21331/) : interesting broken bridges mechanics in main base (gives an impression of security, though can be repaired by the enemy).

**Comment by netnazgul** [comment]
I want more opinions on removing **Polar Disorder** and **Snow Off** - enough maps are coming in to replace these, and if we want to have playable micro maps for 1v1 there are better candidates (f.e. Lucian's [Outpost](https://resource.openra.net/maps/22525/).

Also I've flagged Siberian Pass for removal, my reasoning is in the OP

**Comment by netnazgul** [comment]
@Arular101 

> [00:08] wippie: Also, i dont think climax in its current state is official map pool material
[00:08] wippie: Someone nominated it
[00:08] wippie: Im actually working on a version with more top and bottom land which might be more appealing for competitive players
[00:09] wippie: But far from done
[00:09] wippie: In other words: Lorry broke it and i need to fix it

**Comment by Arular101** [comment]
@netnazgul No problem, just wanted to mention it so it is considered and not forgotten. I trust your judgement.

**Comment by GraionDilach** [comment]
I'd like to mention that the map pool shouldn't be pandering to the competitive playerbase alone, but also should keep in mind the offline play-for-fun "passive" people. Especially in light of how the competitive people backlashed on the last release, drafting how they would likely and gladly take the option to jump to their own rules longterm, so concentrating on their feedback _strictly_ shouldn't be the the option.

The removal of Siberian Pass IMO is actually merely competitive reasoning, while the map is quite good for casual "dated" gameplay and I don't feel it enough alone on it's own (especially in light that the map do feels balanced on first sight) to justify the removal.

**Comment by 3Lucian** [comment]
Thanks @netnazgul again for including Nuc Winter in your list.

Id really appreciate it if anyone could point me to the right place to find out information for barrel damage in the next release, as there are barrels positioned close the the derricks on that map and I would like to tweak it to make sure its not overkill.

I like Snow Off, it should stay! Outpost was just an experiment at making something smaller than it, that played "normally". It hasn't really been adopted by players, nor have i advertised it, or even refined it properly, etc. Snow Off IMO, is a more interesting map in terms of its shape as well.

**Comment by Arular101** [comment]
@3Lucian About the barrels: If someone places 1 barrel next to an oil derrick (excluding the corners), it will take approximately 20% damage, 2 barrels approximately 40% damage and 4 barrels approximately 80% damage. You can see how it will be in the next release here: #14314.

I'm also with 3Lucian about Snow Off. It is a beautiful small map and should only be replaced by other high quality small maps.

**Comment by netnazgul** [comment]
@GraionDilach @3Lucian @Arular101 primary reason for me to consider removing some maps as well as adding new ones was to not inflate the distro size too much with maps and to keep the map count reasonably maintainable. Thus I wanted to determine which maps are not widely used by people and can be left in the depths of Resource Center. Current "mods/ra/maps" folder size is ~5MB (most of that are unpacked maps though).

If this concern is not important then we can just leave all already added maps as they are.

**Comment by pchote** [comment]
We definitely don't want to add too many maps - each brings a small overhead to the load time that grows quite large in aggregate.  Just compare the load times of D2K/TD to RA - this is pretty much all map parsing.

**Comment by Arular101** [comment]
Borrowed Time has in the latest revision still some (intentional?) tiling errors in the water. A very noticeable one is in the water on the left.

**Comment by netnazgul** [comment]
Ugh, I've missed that... Would be tough to fix those considering over-water access is made there by design, but I'll try to look into it

**Comment by 3Lucian** [comment]
@Arular101 what is the damage in the current playtest in comparison to what you have detailed in your PR?

**Comment by GraionDilach** [comment]
>We definitely don't want to add too many maps - each brings a small overhead to the load time that grows quite large in aggregate. Just compare the initial load times of D2K/TD to RA - this is pretty much all map parsing.

I'd start worrying about loadtimes when they grow to be comparable with TS and so far that hasn't been the case. Also, #11420 is the only actual issue about loadtimes.

**Comment by netnazgul** [comment]
@GraionDilach I think pchote meant client load time to the main menu from start (the point where all maps are actually loaded), not loading into the game.

**Comment by GraionDilach** [comment]
The main loading screen loads a game called shellmap, there's no real difference between the two.

**Comment by pchote** [comment]
The main loading screen does the same work as the menu &rarr; game load screen, but then it also does a bunch of extra things like parsing MapPreviews for all maps and loading the the default rules, sequences, and tiles for all tilesets.

**Comment by pchote** [comment]
If you want to get this in for the next playtest then someone needs to take charge and start filing PRs ASAP.

**Comment by netnazgul** [comment]
I was a bit busy IRL through the week, but will try to do something going today
