### ISSUE TITLE
Change the sound volume configuration scale/span

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#14696]
I noticed long ago that the default supposedly 50% loudness setting for sound/music/video is insanely loud already. I never use values greater than ~20% of that slider, and while streaming something as much as 10 pixels of the slider is loud enough (checked in settings.yaml, that's ~3%). Seen the same behaviour for other people on streams (FiveAces, SoScared).

To make the control slider more useful across the whole span of it I suggest applying an exponential coefficient to its value, so that 100% will still be 100%, but the current 10% of the volume setting will have a better degree of control.

**Comment by pchote** [comment]
:+1: Human sound perception is logarithmic, so using a linear volume scale is completely wrong.

**Comment by netnazgul** [comment]
Well, it's not that easy there, as on a second thought this could be also an OS/soundcard issue as well. I saw at Abarrat's stream that he has volume set at ~50% and had the game running as loud as I would have at 10. But still expo scale should not break neither setting.

I'll try to look into it today or tomorrow, maybe it will be an easy task to do even for me :P

**Comment by netnazgul** [comment]
Preliminary code inspection shows, that there could be 2 approaches onto the task. 
1. The harder route if we want to preserve the values already applied from the settings and only change the way slider works with the value. There are a lot of generic ties between SliderWidget and sound volume values around, so modifying that would be a bit problematic, probably requiring to implement a new kind of slider that works in logarithmic scale instead of linear.
Although maybe not that hard, just need to inherit **ExpSliderWidget** from [SliderWidget ](https://github.com/OpenRA/OpenRA/blob/285e9a803067ddf8bbfee3b89f487029d6118833/OpenRA.Mods.Common/Widgets/SliderWidget.cs) and override [ValueFromPx](https://github.com/OpenRA/OpenRA/blob/285e9a803067ddf8bbfee3b89f487029d6118833/OpenRA.Mods.Common/Widgets/SliderWidget.cs#L87) and [PxFromValue](https://github.com/OpenRA/OpenRA/blob/285e9a803067ddf8bbfee3b89f487029d6118833/OpenRA.Mods.Common/Widgets/SliderWidget.cs#L92) and then change sliders for volume settings from SliderWidget to **ExpSliderWidget**.
2. The easier route is to apply the modifier somewhere in [SoundEngine itself](https://github.com/OpenRA/OpenRA/blob/7760c41bd96c1384a5ca4f26c27c99a6fd84d333/OpenRA.Platforms.Default/OpenAlSoundEngine.cs). I don't know yet how dirty that could be, and due to this change all custom settings set by users will need to be corrected and also new default value to be applied.

**Comment by netnazgul** [comment]
Tried to implement the first option, looks too dirty to me. The modification itself works to some extent though - at least now it is possible to configure the sound in a wider range of thumb movement.
https://github.com/netnazgul/OpenRA/commit/735927c65dd34f0bdc2c7be89cdc35077aeb6feb

Probably implementing the second option would be a better way to go, though I don't yet get the exact points of intrusion there.

**Comment by pchote** [comment]
The simplest (and probably cleanest) option is to keep the setting linear and apply the log transform immediately before setting `Game.Sounds.*Volume`.

**Comment by netnazgul** [comment]
yes, that's the second option I've mentioned. It's just there are quite a lot of places where it seems to be applied. Also for setting-to-volume it's exp (or rather power) transform, not log, as we are trying to expand the lower part of the setting.

**Comment by netnazgul** [comment]
yes, that's the second option I've mentioned. It's just there are quite a lot of places where it seems to be applied. Also for setting-to-volume it's exp (or rather power) transform, not log, as we are trying to expand the lower part of the setting.

**Comment by netnazgul** [comment]
> apply the log transform immediately before setting `Game.Sounds.*Volume`
It will still require 2-way transform (reading the setting to set the thumb position /  storing the thumb position to setting), and this is done directly via binding the OnChange and Value attributes of SliderWidget to corresponding settings, I don't think you can modify it right there.
But applying the transform right before `Game.Sounds.*Volume` is used is what I'm planning to try next - means modifying either Sound.cs interface or OpenAlSoundEngine.cs.

**Comment by netnazgul** [comment]
https://github.com/netnazgul/OpenRA/commit/2c1690b80f45debdb5dbc1e4e98b1646c2241db0 the way it can be done directly near the engine. 
Stored sound volume values are the same between versions, but the way they are applied are now different (new version will be more quiet on the new version), so the values will need to be updated. 100% slider value is still the same in both versions, the scaling is just a square value.
![image](https://user-images.githubusercontent.com/1614714/34789943-2ae0221a-f651-11e7-88b7-58d376afb96c.png)
