### ISSUE TITLE
Playtest 20180102: Ingame chat message sound becomes very loud over time

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#14695]
Ingame chat sound becomes way louder than it is set in settings. Initially it is_a bit_ louder than the same sound in server lobby, but then becomes even more insane.
Looks like the sound is played several times for the same message and gets stacked.

Issue is confirmed in several TD streams, but it's not yet clear what exactly causes it. Will try to gather further data for this.

**Comment by Arular101** [comment]
Noticed in [ZxGanon's stream](https://www.twitch.tv/videos/216677455?t=31m30s) (and 1 minute later the lobby notification are not loud), and some one also mentioned [here](http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=306098#306098).

Chat notifications in game are also double.

**Comment by pchote** [comment]
> Chat notifications in game are also double.

This is the real bug here.  The volume increase is just an artifact of playing the chat notification twice at the same time.

Can somebody please provide a replay and timestamp from the stream (or elsewhere) that demonstrates the bug?  This will make it easy to isolate the bug to the sending or receiving side, at which point I imagine the cause will become clear.

**Comment by Arular101** [comment]
Okay could reproduce it now.

Start two games and make a multiplayer game.
Mute the sound of one of the games.
Chat in the multiplayer game. This sound is normal (like how it was in the lobby.)
Now surrender in one of the games.
Chatting now is louder. This has maybe something to do with the neutral (and online from spectators) notification.

**Comment by pchote** [comment]
Can you please provide a replay demonstrating your repro case?

**Comment by Arular101** [comment]
[OpenRA-2018-01-14T101953Z.zip](https://github.com/OpenRA/OpenRA/files/1629232/OpenRA-2018-01-14T101953Z.zip)

First you hear both players at normal sound level. After one of the players surrenders you hear both players louder.

**Comment by pchote** [comment]
This was introduced by #13408.  It looks like the `orderManager.AddChatLine` is not being unregistered properly when the window is closed.  A simple way to confirm this is to open and then close the in-menu chat dialog several times.  Each time you do it amplifies the sound played back.

**Comment by pchote** [comment]
I expect that replacing `Game.BeforeGameStart += UnregisterEvents;` in the `IngameChatLogic` with a proper `ChromeLogic.Dispose` implementation will fix this.
