### ISSUE TITLE
Option to disable the "Auto-exclude" MCV/Engineer/Harvester logic when click & dragging to select a group

### ISSUE THREAD

**Issue by avalach21** [OpenRA/OpenRA#14694]
This was discussed on the message board and Sleipnir recommended we open an issue on github.

I am sure many players enjoy the current functionality but others (myself included) would prefer the game to operate the same way the original Westwood C&Cs did.  Currently, when selecting a group of units that includes a non-combat unit (MCV/engineer/Harvester) the MCV/Engineer/Harvester are automatically excluded from the group.

I would prefer the option to disable this logic and have the MCV/Engineer/Harvester/(basically anything inside the dragged selection) to be included in the group with no automatic exclusion.  

For example, when moving to capture a derrick or to move an MCV to take control of a certain territory, I would rather select my army along with the MCV/Engi as a group and move them together as an escort rather than having to individually move the Engi/MCV with another separate order.  Of course eventually the Engi/MCV would be given a specific instruction (capture/deploy) but I would rather issue these commands after the Engi/MCV are in motion towards their target destination rather than wasting potentially crucial seconds as they sit around waiting for a separate command from the rest of the group.
 
If there is consideration to implement this as an option, I think we would all agree to leave the current behavior as the default setting :-)

**Comment by dragunoff** [comment]
There are game situations where either behavior could be desired/useful (for example not disrupting harvesters when commanding units near them). While the default can be implemented as an option, there could also be a modifier that changes that behavior. 

For example: Normal `mouse drag` selects combat units, `Ctrl + mouse drag` selects all units.

**Comment by dragunoff** [comment]
Or `Alt + drag` can be used to unselect units (like selection tools in graphics editing software).

**Comment by avalach21** [comment]
I think that having some sort of key modifier would be an acceptable solution

**Comment by dragunoff** [comment]
Selection modifiers were also mentioned in #11767

**Comment by avalach21** [comment]
I feel that newly opened issues [14770](https://github.com/OpenRA/OpenRA/issues/14770) and [14769](https://github.com/OpenRA/OpenRA/issues/14769) are semi related to this issue.

As for issue [11767](https://github.com/OpenRA/OpenRA/issues/11767), I agree... Engineers.. Medics.. Mechanics...(MCVs, Harvesters..?  etc if I'm missing anything) should NOT run up to the attack target if they are in the selection group... they should simple ignore the command altogether.

I believe the auto exclusion should be overhauled a little bit to include medics, mechanics, minelayers and hijackers.

I then also believe that there should be a key modifier to to disable the auto exclude.

And maybe furthermore, an option in the menu as to whether the auto exclusion is enabled or disabled by default.  The modifier then would obviously enable the exclusion if the user has it disabled or it would disable the exclusion if the user has it enabled.

Sorry I'm new around here.. is there a way to combine these discussions into a single thread>?  Would that make sense?

**Comment by dragunoff** [comment]
I'm also in favor of having selection modifiers with an option to set the default action. 

> I feel that newly opened issues 14770 and 14769 are semi related to this issue.

Yes, the issues you mention are related to this one.

> Sorry I'm new around here.. is there a way to combine these discussions into a single thread>? Would that make sense?

Even though these issues(selection modifiers and attack order for non-combat units) have some things in common IMO they are distinct and should be kept separate. @avalach21

**Comment by ZxGanon** [comment]
We have experimented with different selection types in Shattered Paradise aswell.

It feels so damn good that MCV, Harvester and Engineers (and other non combat units) are outside of the main selection group.

Before that is was extremely awful.

**Comment by Smittytron** [comment]
The best way to do this would be to keep the current logic but have a key to modify a selection to grab everything. i.e. Ctrl + dragbox selects everything.

**Comment by tovl** [comment]
Shouldn't this have been closed by #15839?

**Comment by pchote** [comment]
Indeed.
