### ISSUE TITLE
Neutral bots D2k

### ISSUE THREAD

**Issue by Alex34567889** [OpenRA/OpenRA#14709]
Hello!
Please tell us how you can create neutral bots (Omnius, Vidius, Gladius) in the 2000 dune for multiplayer?
If you attack them and they were enemies. Something like the original game
What lines do I need to write in the lua script? Is it even possible

**Comment by penev92** [comment]
I don't understand the question.
Do you want to create your own AI personalities?
Do you want to create a neutral faction for a scripted map?
Do you want to change an AI player from neutral to enemy during the game?

**Comment by Alex34567889** [comment]
Yes i need to change an AI player from neutral to enemy during the game. For example. If you destroy a unit of neutral bots, they will become enemies

**Comment by MustaphaTR** [comment]
Changing diplomacy midgame is not supported. Check Har 6/8/9b to see how it is hackyly done. Simply you have to define 2 different players, one is neutral, other enemy and change the owners of the actor with lua.

**Comment by StormWingDelta** [comment]
The fun question is how to do it midgame with conditions and not make it hacky as SIN.

**Comment by abcdefg30** [comment]
> Changing diplomacy midgame is not supported.
