### ISSUE TITLE
Husks don't show owner's name in playtest-20180102

### ISSUE THREAD

**Issue by gdavegdave** [OpenRA/OpenRA#14715]
Husks used to show the name of the player who owned the vehicle. That was useful e.g. for assessing how a battle had gone whilst speccing. In playtest-20180102 (in TD, at least), only the vehicle type is displayed when a husk is hovered. Can we have the owner's name back too?

**Comment by MustaphaTR** [comment]
Related PR: #13276

Husks are no longer owned by their previous owner, but player "Neutral" (which has NonCombatant that hides the owner row) with EffectiveOwner of old owner to show remap correctly. But looks like it doesn't update the owner row in the way Disguise trait does. I removed NonCombatant from "Neutral" on a map but it still shows Neutral owner row.

**Comment by pchote** [comment]
The code that decides whether or not to show the owner row probably doesn't check the EffectiveOwner.

**Comment by MustaphaTR** [comment]
I still get neutral owner row, rather than mine on husks, even if i remove `NonCombatant` from Neutral. Even when visibility cheat is disabled. So i don't think it is the code to show or hide the owner row. I was going to test with spy too, but it doesn't look like i can make myself non-combatant, so i need to write some lua to test.

![resim](https://user-images.githubusercontent.com/7933210/34877120-bb6df5f4-f7b5-11e7-8404-825b91dd9994.png)

**Comment by MustaphaTR** [comment]
Spies work fine, there is something wrong with Husks.

Visibility Cheat disabled:
![resim](https://user-images.githubusercontent.com/7933210/34877421-01c37fc8-f7b7-11e7-9f3e-33958a68e296.png)
Visibility Cheat enabled:
![resim](https://user-images.githubusercontent.com/7933210/34877422-07ac92f8-f7b7-11e7-85c9-56a72c06bda7.png)

**Comment by pchote** [comment]
Again, the code that displays the tooltip doesn't check for the EffectiveOwner. Instead, spies special case that logic as part of their disguise tooltip, which is wrong because the effective owner handling should be logically distinct from the change in effective actor.

**Comment by pchote** [comment]
If nobody volunteers a fix for this then IMO it should be promoted to a feature (and probably properly toggled in the yaml) and dropped from the milestone.
