### ISSUE TITLE
Missing Key Combination for Waypoint Mode

### ISSUE THREAD

**Issue by patrickbucher** [OpenRA/OpenRA#14719]
There is no key combination for waypoint mode. This is quite annoying, for waypoints are one of the features I used very often, for example when annihilating an enemy's base with MIGs for good.

**Comment by pchote** [comment]
![screen shot 2018-01-13 at 18 40 38](https://user-images.githubusercontent.com/167819/34908997-5fd29b1e-f891-11e7-99b6-ec562cb3f7eb.png)

This waypoint mode?

**Comment by patrickbucher** [comment]
Exactly.

**Comment by pchote** [comment]
As mentioned in the tooltip, hold <kbd>Shift</kbd> to activate waypoint mode.

**Comment by patrickbucher** [comment]
Oh, sorry, now I got it. I thought I always had to first go into waypoint mode to tell a unit to do things one by one. But Shift does this. I used it the wrong way all the time. Sorry for the hassle.
