### ISSUE TITLE
Map Editor : Add shortcuts

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#14723]
Especially a Ctrl-C shortcut for Copy/paste
Maybe G for Grid. 

#14724 : Ctrl-D for Clone tool

**Comment by TamasKiss** [comment]
Hi! I would like to take this ticket if it is available.

**Comment by abcdefg30** [comment]
> Hi! I would like to take this ticket if it is available.

I don't think anyone is working on this at the moment, so feel free to take it. :)

**Comment by TamasKiss** [comment]
- [ ] Ctrl+C will make the user enter into copy mode without anything copied
- [ ] Ctrl+V will instantly paste the last copied assets on the cursor position (the other solution would be to enter into the paste mode, then with a mouse click place the assets)

- [ ]  Ctrl+Z -> Undo
- [ ]  Ctrl+S -> Save the map (?)
- [ ]  Ctrl+Y -> Redo
- [ ] Ctrl+[1-9] -> faction selector

**Comment by rob-v** [comment]
Grid already has F1 key, so I added Ctrl+C for Copy. Would you like some additional shortcuts in Map editor?
