### ISSUE TITLE
Click sound for StatisticsBasic, but no sound for other hotkeyed tabs

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#14726]
Self-explanatory.

**Comment by netnazgul** [comment]
Haven't digged deep enough, but probably the issue is with StatisticsBasic being a physical button in the interface, so this is triggered here
https://github.com/OpenRA/OpenRA/blob/283af60b7c39fc81006f9c8eb2a637f94dfb2353/OpenRA.Mods.Common/Widgets/ButtonWidget.cs#L140
But no such call for hotkeys.

**Comment by pchote** [comment]
There are two potential approaches here:
1. Define `DisableKeySound: true` on the `StatisticsBasic` button so that *no* tabs use buttons.
2. Add sound notifications to the `*Logic` that manages the key bindings for the other tabs.
