### ISSUE TITLE
Map Editor : Clone tool

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#14724]
Similar to Copy/paste, but persistent (until RMB is clicked, for instance, to exit the tool)
#14723 : Ctrl-D shortcut maybe.

**Comment by pchote** [comment]
How about holding a modifier key (shift?) when doing the paste?

**Comment by FRenzy-OpenRA** [comment]
Sounds good !

**Comment by Ectras** [comment]
Why don't just make the copy/paste persistent by default? That would be more intuitive with the "select once, place multiple" workflow that you have for placing map elements as well.

**Comment by Samunosuke** [comment]
I would also like to copy and paste the element multiple times. Makes it much more convenient. 
It just takes one line to remove and it works!
in EditorCopyPasteBrush.cs
Line 99					
// editorWidget.ClearBrush();
