### ISSUE TITLE
Units inside a Cargo actor with EjectOnDeath: True will not die when surrendering.

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#14735]
Tested on the same bleed as yesterday.

![surrender bug](https://user-images.githubusercontent.com/11763228/34964134-d827f704-fa2a-11e7-990f-badfae26c9ed.gif)

**Comment by abcdefg30** [comment]
Sounds like we need something like #13276 here as well.

**Comment by MustaphaTR** [comment]
I cannot reproduce on lasteset bleed. Maybe it got fixed somewhere.

**Comment by ABrandau** [comment]
Seems to have been fixed after OwnerLostAction got created.
