### ISSUE TITLE
Writing the mod name in non-full-lowercase runs launch-game.cmd, but crashes the game

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#14739]
Sorry for tittlegore, would be better if someone can reword it.

With:

    OpenRA engine version {DEV_VERSION}
    Date: 2018-01-16 18:55:35Z
    Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
    Runtime Version: .NET CLR 4.0.30319.42000
    Exception of type `System.InvalidOperationException`: Unknown or invalid mod 'Ra'.
       konum: OpenRA.Game.InitializeMod(String mod, Arguments args) c:\OpenRA\Bleed\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Game.cs içinde: satır 400
       konum: OpenRA.Game.Initialize(Arguments args) c:\OpenRA\Bleed\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Game.cs içinde: satır 366
       konum: OpenRA.Game.InitializeAndRun(String[] args) c:\OpenRA\Bleed\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Game.cs içinde: satır 251
       konum: OpenRA.Program.Main(String[] args) c:\OpenRA\Bleed\OpenRA-bleed\OpenRA-bleed\OpenRA.Game\Support\Program.cs içinde: satır 37

I guess .cmd should either give mod not found error, or run the mod correctly with lowercased name. I don't think, for example, `Ra` and `ra` can be different vaild mods, so later makes more sense.

**Comment by LipkeGu** [comment]
Duplicate Mods like ```Ts``` and ```ts``` can make problems (later)...

**Comment by RoosterDragon** [comment]
In `launch-game.cmd` we could do case sensitive comparisons: i.e. `if "%mod%" EQU "ra" (goto launchmod)` instead of `if /I "%mod%" EQU "ra" (goto launchmod)` - that would prevent you launching with a mismatched casing.

**Comment by LipkeGu** [comment]
@RoosterDragon : sounds good
