### ISSUE TITLE
PauseOnCondition does not stop AttackFrontal orders.

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#14731]
Tested on a bleed downloaded 2 hours ago.
![wolverine](https://user-images.githubusercontent.com/11763228/34922927-d23c9e14-f974-11e7-95d3-ac59789e7db2.gif)

**Comment by MustaphaTR** [comment]
Duplicate of https://github.com/OpenRA/OpenRA/issues/13355 i think. I tested with bikes there iirc.

**Comment by pchote** [comment]
Looks that way.  Closing as duplicate.
