### ISSUE TITLE
No intro in Tiberian Dawn on Mac

### ISSUE THREAD

**Issue by schpaul** [OpenRA/OpenRA#14743]
There is no intro (video) when I start TD on my Mac. I am not sure if there was a intro before like it is in RA an D2K.

Thank you.

**Comment by MustaphaTR** [comment]
TD Shellmap has been removed in a recent release, can't remember which one. It is intentional.

**Comment by schpaul** [comment]
Thank you MustaphaTR, 

but why? Is there any issue with Shellmaps in TD? 

Because I have just created a sample shell map (copied from another map) and it worked!

**Comment by dragunoff** [comment]
It was removed because it was not polished and issues kept popping up. It also showcases how a mod can use an image instead of a shellmap. See pchote's comment in PR #12465

**Comment by dragunoff** [comment]
@schpaul there is already a ticket for an option to disable/enable the shellmap #13279

**Comment by schpaul** [comment]
Ok, will close the ticket
