### ISSUE TITLE
Excesive memory consumption for the debug.log when playing tiberian sun

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#14749]
Tested this while playing mods, the file could range between 250 mb and 1.5 gb, I just tested this on the current bleed and the file reaches 25mb on 1:30 minutes, on the debug log, the program repeats this line, many infinite times.

Could not find collection '-disabled'

Abcd and Penev claim it may be chrome related.

**Comment by abcdefg30** [comment]
It looks like we have the same issue in TS.

**Comment by reaperrr** [comment]
Too late for the release now, but D2k is actually affected, too.
