### ISSUE TITLE
Units blink when transforming.

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#14744]
![transform](https://user-images.githubusercontent.com/11763228/35158087-cd5bad88-fd14-11e7-8b16-23a510aec9e9.gif)

**Comment by pchote** [comment]
I can't reproduce this on current bleed or release-20171014.  I assume this is a duplicate of #14614 and/or #14645, which were fixed by #14666?

**Comment by GraionDilach** [comment]
That's possible, the branch Nolt's on is #14557 at the moment, predating the merge of #14666 by a few PRs.

**Comment by ABrandau** [comment]
Yeah, my bad, this is the only bug I forgot to test on the current bleed.
