### ISSUE TITLE
Dedicated server console does not print announcement of 1st player to join

### ISSUE THREAD

**Issue by oraservers** [OpenRA/OpenRA#14750]
When a new instance of a dedicated server starts, and the first player joins, the first player's name and announcement "[TIMESTAMP] PlayerNameHere has joined the game." does not display in the console output. It will only display for join messages when there is at least one player in the game. Disconnect messages and subsequent join messages when at least one player is in the lobby appear not to be impacted.

**Comment by Nismirno** [comment]
Hi, 

It seems that this can be really easily fixed.
I could push a PR introducing a fix to that.

**Comment by abcdefg30** [comment]
Sure. 👍
