### ISSUE TITLE
APC break TD, hotfix?

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#14761]
Currently APC (TD) dmg against heavy armor, combined with the low price and speed makes them inbalanced as you aware of. Watching a couple of games i'd recomend or raise the question/discussion for a hotfix. 

Over all: aa, crush infantry, carry infantry
In goups good against havy armor, light armor, buildings,
Cheap and fast.

**Comment by pchote** [comment]
It looks like this has already been addressed in #14728.

**Comment by fruestueck** [comment]
yeah, i remembered that but could find it. will close this
