### ISSUE TITLE
Install advanced game content from CD on MacOS

### ISSUE THREAD

**Issue by DmitryMihailov** [OpenRA/OpenRA#14767]
Hi all!

Could someone tell me how to install game scenes, ost from add-ons on MacOS? OpenRA can't detect game CDs.

**Comment by ltem** [comment]
The data should be put into the mod-specific folder in `~/Library/Application Support/OpenRA/Content` [Link](https://github.com/OpenRA/OpenRA/wiki/Installation).

E.g. for Tiberian Dawn (cnc):
```
OpenRA/Content/cnc
├── conquer.mix
├── desert.mix
├── general.mix
├── movies
│   ├── airstrk.vqa
│   ├── akira.vqa
│   ├── banner.vqa
│   ├── bcanyon.vqa
│   ├── bkground.vqa
│   ├── bombaway.vqa
│   ├── bomb... (and so on)
├── scores-covertops.mix
├── scores.mix
├── sounds.mix
├── speech.mix
├── temperat.mix
├── tempicnh.mix
├── transit.mix
└── winter.mix

```  

However the CD detection is hardcoded , so "Localized installation CDs and expansion packs will not work" ([Link](https://github.com/OpenRA/OpenRA/wiki/Game-Content)).

From which game (Red Alert, Tiberian Dawn, Dune2k) do you want to install advanced game content?
What source are you using? (For Red Alert for example the orginal CDs, Freeware Download or The First Decade Collection)

**Comment by pchote** [comment]
Installing the game content manually isn't supported, and requires special tools (XCC Mixer).

Installing content from disc on macOS usually works fine, so we are going to need more info about your setup before we can help.

**Comment by DmitryMihailov** [comment]
My Mac:
<img width="228" alt="screen shot 2018-02-07 at 12 45 39" src="https://user-images.githubusercontent.com/23633956/35914784-d60c5ec4-0c04-11e8-8081-fbdf9405121a.png">

I was mounting downloaded expansions of D2K, RA, CNC on Windows discs, using the Daemon Tool for Mac.

**Comment by pchote** [comment]
Please try mounting the images normally, using the built in macOS image mounting feature.  Daemon tools may not be mounting them images to the /Volumes/ directory that OpenRA expects.

**Comment by DJManas** [comment]
It actually does. I see the images mounted on /Volumes/RA1 and /Volumes/RA2.

```
/dev/disk3s0 on /Volumes/RA1 (cd9660, local, nodev, nosuid, read-only, noowners)
/dev/disk4s0 on /Volumes/RA2 (cd9660, local, nodev, nosuid, read-only, noowners)
```

So I had used ccd2iso to convert clone CD images to plain ISO
```
RinceWind:Red Alert 2 - ISO 2CD djmanas$ ccd2iso Ra2\ Allied.img RA2Allied.iso
337472 sector written
Done.
```

And mounted using DiskImageMounter.app
![2018-03-10_19-35-19](https://user-images.githubusercontent.com/2048276/37245558-3dc4663a-249a-11e8-8844-f25447da12bd.png)

Ok it is a little different, now I have mounted:
/dev/disk3 on /Volumes/RA1 (cd9660, local, nodev, nosuid, read-only, noowners, mounted by djmanas)

But when I go to OpenRA - Red Alert.app and try to search for content, I get No Content found.
![2018-03-10_19-37-17](https://user-images.githubusercontent.com/2048276/37245575-7e5d5a76-249a-11e8-8027-846ff2182231.png)

I tried to quit and start app again, after mounting the iso, just to make sure.

**Comment by DJManas** [comment]
Ok, problem is with the iso, downloaded different one from [Here](https://cncnz.com/features/freeware-classic-command-conquer-games/)

And everything works.

**Comment by matjaeck** [comment]
This issue is solved and can be closed.

**Comment by jowtron** [comment]
unresolved for dune 2000, where exactly does openra look for the files? why not enable an option to just select the directory they are in rather than mounting discs etc?

**Comment by DJManas** [comment]
`/Users/<username>/Library/Application Support/OpenRA`

OpenRA installed through [HomeBrew](https://brew.sh) casks (**brew cask install openra**)
Version: **20200202**

My directory structure inside Content directory for Dune 2000 and it works. Hope it helps.
`./Content/d2k:
drwxr-xr-x  19608  2 bře  2018 v2

./Content/d2k/v2:
-rw-r--r--    1 842400  2 bře  2018 BLOXBASE.R8
-rw-r--r--    1 842400  2 bře  2018 BLOXBAT.R8
-rw-r--r--    1 842400  2 bře  2018 BLOXBGBS.R8
-rw-r--r--    1 842400  2 bře  2018 BLOXICE.R8
-rw-r--r--    1 842400  2 bře  2018 BLOXTREE.R8
-rw-r--r--    1 842400  2 bře  2018 BLOXWAST.R8
-rw-r--r--    1 842400  2 bře  2018 BLOXXMAS.R8
-rw-r--r--    15845868  2 bře  2018 DATA.R8
-rw-r--r--    1    256  2 bře  2018 FONT.BIN
-rw-r--r--    1  19570  2 bře  2018 FONTCOL.FNT
-rw-r--r--    1   1024  2 bře  2018 FONTCOL.FPL
drwxr-xr-x  253   8096  2 bře  2018 GAMESFX
-rw-r--r--    1 160330  2 bře  2018 MOUSE.R8
drwxr-xr-x   44   1408 15 kvě  2016 Movies
drwxr-xr-x   19    608 15 kvě  2016 Music
-rw-r--r--    1    768  2 bře  2018 PALETTE.BIN
-rw-r--r--    12205414  2 bře  2018 SOUND.RS

./Content/d2k/v2/GAMESFX:
-rw-r--r--    125604  2 bře  2018 AI_1MIN.AUD
-rw-r--r--    125116  2 bře  2018 AI_2MIN.AUD
-rw-r--r--    128884  2 bře  2018 AI_3MIN.AUD
-rw-r--r--    131092  2 bře  2018 AI_4MIN.AUD
-rw-r--r--    140588  2 bře  2018 AI_5MIN.AUD
-rw-r--r--    120500  2 bře  2018 AI_ABORT.AUD
-rw-r--r--    131228  2 bře  2018 AI_ATACK.AUD
-rw-r--r--    124532  2 bře  2018 AI_BDRDY.AUD
-rw-r--r--    123292  2 bře  2018 AI_BLOST.AUD
-rw-r--r--    114700  2 bře  2018 AI_BUILD.AUD
-rw-r--r--    118028  2 bře  2018 AI_CANCL.AUD
-rw-r--r--    127780  2 bře  2018 AI_CAPT.AUD
-rw-r--r--    129404  2 bře  2018 AI_DHRDY.AUD
-rw-r--r--    125372  2 bře  2018 AI_DPLOY.AUD
-rw-r--r--    128556  2 bře  2018 AI_ENEMY.AUD
-rw-r--r--    126188  2 bře  2018 AI_GANEW.AUD
-rw-r--r--    119570  2 bře  2018 AI_GLOAD.AUD
-rw-r--r--    119788  2 bře  2018 AI_GSAVE.AUD
-rw-r--r--    113204  2 bře  2018 AI_GUARD.AUD
-rw-r--r--    125956  2 bře  2018 AI_HATTK.AUD
-rw-r--r--    115628  2 bře  2018 AI_HOLD.AUD
-rw-r--r--    128884  2 bře  2018 AI_LAUNC.AUD
-rw-r--r--    139412  2 bře  2018 AI_MAP1A.AUD
-rw-r--r--    132100  2 bře  2018 AI_MAP1B.AUD
-rw-r--r--    132460  2 bře  2018 AI_MAP1C.AUD
-rw-r--r--    155212  2 bře  2018 AI_MAP2A.AUD
-rw-r--r--    132980  2 bře  2018 AI_MAP2B.AUD
-rw-r--r--    138700  2 bře  2018 AI_MAP2C.AUD
-rw-r--r--    138828  2 bře  2018 AI_MAP3A.AUD
-rw-r--r--    127028  2 bře  2018 AI_MAP4A.AUD
-rw-r--r--    134604  2 bře  2018 AI_MAP5A.AUD
-rw-r--r--    156052  2 bře  2018 AI_MAP6A.AUD
-rw-r--r--    126772  2 bře  2018 AI_MAP7A.AUD
-rw-r--r--    135188  2 bře  2018 AI_MAP8A.AUD
-rw-r--r--    130444  2 bře  2018 AI_MAP9A.AUD
-rw-r--r--    116924  2 bře  2018 AI_MEND.AUD
-rw-r--r--    124268  2 bře  2018 AI_MFAIL.AUD
-rw-r--r--    127068  2 bře  2018 AI_MONEY.AUD
-rw-r--r--    123948  2 bře  2018 AI_MWIN.AUD
-rw-r--r--    131748  2 bře  2018 AI_NEWOP.AUD
-rw-r--r--    127844  2 bře  2018 AI_NROOM.AUD
-rw-r--r--    120564  2 bře  2018 AI_ORDER.AUD
-rw-r--r--    127588  2 bře  2018 AI_PLACE.AUD
-rw-r--r--    118140  2 bře  2018 AI_POWER.AUD
-rw-r--r--    126508  2 bře  2018 AI_PREP.AUD
-rw-r--r--    127516  2 bře  2018 AI_PRMRY.AUD
-rw-r--r--    127324  2 bře  2018 AI_REINF.AUD
-rw-r--r--    116924  2 bře  2018 AI_RUN.AUD
-rw-r--r--    124140  2 bře  2018 AI_SELL.AUD
-rw-r--r--    119588  2 bře  2018 AI_SILOS.AUD
-rw-r--r--    129500  2 bře  2018 AI_SPORT.AUD
-rw-r--r--    118204  2 bře  2018 AI_TRAIN.AUD
-rw-r--r--    120660  2 bře  2018 AI_ULOST.AUD
-rw-r--r--    118844  2 bře  2018 AI_UNRDY.AUD
-rw-r--r--    125700  2 bře  2018 AI_UPGOP.AUD
-rw-r--r--    117708  2 bře  2018 AI_UPGRD.AUD
-rw-r--r--    122708  2 bře  2018 AI_WATTK.AUD
-rw-r--r--    121348  2 bře  2018 AI_WSIGN.AUD
-rw-r--r--    112666  2 bře  2018 A_ECONF1.AUD
-rw-r--r--    113610  2 bře  2018 A_ECONF2.AUD
-rw-r--r--    113610  2 bře  2018 A_ECONF3.AUD
-rw-r--r--    111442  2 bře  2018 A_ESEL1.AUD
-rw-r--r--    115426  2 bře  2018 A_ESEL2.AUD
-rw-r--r--    115426  2 bře  2018 A_ESEL3.AUD
-rw-r--r--    112726  2 bře  2018 A_FCONF1.AUD
-rw-r--r--    114963  2 bře  2018 A_FCONF2.AUD
-rw-r--r--    117999  2 bře  2018 A_FCONF3.AUD
-rw-r--r--    118327  2 bře  2018 A_FCONF4.AUD
-rw-r--r--    112726  2 bře  2018 A_FSEL1.AUD
-rw-r--r--    113845  2 bře  2018 A_FSEL2.AUD
-rw-r--r--    112726  2 bře  2018 A_FSEL3.AUD
-rw-r--r--    110489  2 bře  2018 A_FSEL4.AUD
-rw-r--r--    113049  2 bře  2018 A_ICONF1.AUD
-rw-r--r--    113009  2 bře  2018 A_ICONF2.AUD
-rw-r--r--    113665  2 bře  2018 A_ICONF3.AUD
-rw-r--r--    115722  2 bře  2018 A_ISEL1.AUD
-rw-r--r--    115681  2 bře  2018 A_ISEL2.AUD
-rw-r--r--    112297  2 bře  2018 A_ISEL3.AUD
-rw-r--r--    114687  2 bře  2018 A_VCONF1.AUD
-rw-r--r--    117839  2 bře  2018 A_VCONF2.AUD
-rw-r--r--    116279  2 bře  2018 A_VCONF3.AUD
-rw-r--r--    113775  2 bře  2018 A_VSEL1.AUD
-rw-r--r--    117671  2 bře  2018 A_VSEL2.AUD
-rw-r--r--    115039  2 bře  2018 A_VSEL3.AUD
-rw-r--r--    113485  2 bře  2018 G_SCONF1.AUD
-rw-r--r--    118912  2 bře  2018 G_SCONF2.AUD
-rw-r--r--    118517  2 bře  2018 G_SCONF3.AUD
-rw-r--r--    113583  2 bře  2018 G_SSEL1.AUD
-rw-r--r--    113117  2 bře  2018 G_SSEL2.AUD
-rw-r--r--    113165  2 bře  2018 G_SSEL3.AUD
-rw-r--r--    116035  2 bře  2018 HI_1MIN.AUD
-rw-r--r--    116555  2 bře  2018 HI_2MIN.AUD
-rw-r--r--    118803  2 bře  2018 HI_3MIN.AUD
-rw-r--r--    118115  2 bře  2018 HI_4MIN.AUD
-rw-r--r--    128611  2 bře  2018 HI_5MIN.AUD
-rw-r--r--    117403  2 bře  2018 HI_ABORT.AUD
-rw-r--r--    121331  2 bře  2018 HI_ATACK.AUD
-rw-r--r--    119843  2 bře  2018 HI_BDRDY.AUD
-rw-r--r--    113859  2 bře  2018 HI_BLOST.AUD
-rw-r--r--    1 8556  2 bře  2018 HI_BUILD.AUD
-rw-r--r--    110187  2 bře  2018 HI_CANCL.AUD
-rw-r--r--    118283  2 bře  2018 HI_CAPT.AUD
-rw-r--r--    122635  2 bře  2018 HI_DHRDY.AUD
-rw-r--r--    117339  2 bře  2018 HI_DPLOY.AUD
-rw-r--r--    121403  2 bře  2018 HI_ENEMY.AUD
-rw-r--r--    117371  2 bře  2018 HI_GANEW.AUD
-rw-r--r--    111163  2 bře  2018 HI_GLOAD.AUD
-rw-r--r--    113892  2 bře  2018 HI_GSAVE.AUD
-rw-r--r--    1 7651  2 bře  2018 HI_GUARD.AUD
-rw-r--r--    119323  2 bře  2018 HI_HATTK.AUD
-rw-r--r--    110899  2 bře  2018 HI_HOLD.AUD
-rw-r--r--    120851  2 bře  2018 HI_LAUNC.AUD
-rw-r--r--    122635  2 bře  2018 HI_MAP1A.AUD
-rw-r--r--    124651  2 bře  2018 HI_MAP1B.AUD
-rw-r--r--    120099  2 bře  2018 HI_MAP1C.AUD
-rw-r--r--    130499  2 bře  2018 HI_MAP2A.AUD
-rw-r--r--    131603  2 bře  2018 HI_MAP2B.AUD
-rw-r--r--    120291  2 bře  2018 HI_MAP2C.AUD
-rw-r--r--    128547  2 bře  2018 HI_MAP3A.AUD
-rw-r--r--    124259  2 bře  2018 HI_MAP3B.AUD
-rw-r--r--    125171  2 bře  2018 HI_MAP4A.AUD
-rw-r--r--    125043  2 bře  2018 HI_MAP4B.AUD
-rw-r--r--    129067  2 bře  2018 HI_MAP5A.AUD
-rw-r--r--    131147  2 bře  2018 HI_MAP6A.AUD
-rw-r--r--    126275  2 bře  2018 HI_MAP6B.AUD
-rw-r--r--    122443  2 bře  2018 HI_MAP7A.AUD
-rw-r--r--    128163  2 bře  2018 HI_MAP9.AUD
-rw-r--r--    126795  2 bře  2018 HI_MAP9A.AUD
-rw-r--r--    1 8563  2 bře  2018 HI_MEND.AUD
-rw-r--r--    118283  2 bře  2018 HI_MFAIL.AUD
-rw-r--r--    118539  2 bře  2018 HI_MONEY.AUD
-rw-r--r--    114835  2 bře  2018 HI_MWIN.AUD
-rw-r--r--    122307  2 bře  2018 HI_NEWOP.AUD
-rw-r--r--    123347  2 bře  2018 HI_NROOM.AUD
-rw-r--r--    113779  2 bře  2018 HI_ORDER.AUD
-rw-r--r--    117923  2 bře  2018 HI_PLACE.AUD
-rw-r--r--    114283  2 bře  2018 HI_POWER.AUD
-rw-r--r--    121563  2 bře  2018 HI_PREP.AUD
-rw-r--r--    120651  2 bře  2018 HI_PRMRY.AUD
-rw-r--r--    121235  2 bře  2018 HI_REINF.AUD
-rw-r--r--    111387  2 bře  2018 HI_RUN.AUD
-rw-r--r--    115939  2 bře  2018 HI_SELL.AUD
-rw-r--r--    113211  2 bře  2018 HI_SILOS.AUD
-rw-r--r--    119323  2 bře  2018 HI_SPORT.AUD
-rw-r--r--    1 8851  2 bře  2018 HI_TRAIN.AUD
-rw-r--r--    116555  2 bře  2018 HI_ULOST.AUD
-rw-r--r--    112299  2 bře  2018 HI_UNRDY.AUD
-rw-r--r--    118283  2 bře  2018 HI_UPGOP.AUD
-rw-r--r--    112043  2 bře  2018 HI_UPGRD.AUD
-rw-r--r--    114411  2 bře  2018 HI_WATTK.AUD
-rw-r--r--    113923  2 bře  2018 HI_WSIGN.AUD
-rw-r--r--    116082  2 bře  2018 H_ECONF1.AUD
-rw-r--r--    119231  2 bře  2018 H_ECONF2.AUD
-rw-r--r--    116423  2 bře  2018 H_ECONF3.AUD
-rw-r--r--    117208  2 bře  2018 H_ESEL1.AUD
-rw-r--r--    119445  2 bře  2018 H_ESEL2.AUD
-rw-r--r--    112726  2 bře  2018 H_ESEL3.AUD
-rw-r--r--    113845  2 bře  2018 H_ICONF1.AUD
-rw-r--r--    117087  2 bře  2018 H_ICONF2.AUD
-rw-r--r--    119527  2 bře  2018 H_ICONF3.AUD
-rw-r--r--    112343  2 bře  2018 H_ISEL1.AUD
-rw-r--r--    114487  2 bře  2018 H_ISEL2.AUD
-rw-r--r--    121055  2 bře  2018 H_ISEL3.AUD
-rw-r--r--    113845  2 bře  2018 H_VCONF1.AUD
-rw-r--r--    117208  2 bře  2018 H_VCONF2.AUD
-rw-r--r--    114963  2 bře  2018 H_VCONF3.AUD
-rw-r--r--    112086  2 bře  2018 H_VSEL1.AUD
-rw-r--r--    116082  2 bře  2018 H_VSEL2.AUD
-rw-r--r--    113845  2 bře  2018 H_VSEL3.AUD
-rw-r--r--    114283  2 bře  2018 OI_1MIN.AUD
-rw-r--r--    113635  2 bře  2018 OI_2MIN.AUD
-rw-r--r--    116171  2 bře  2018 OI_3MIN.AUD
-rw-r--r--    114019  2 bře  2018 OI_4MIN.AUD
-rw-r--r--    127900  2 bře  2018 OI_5MIN.AUD
-rw-r--r--    115843  2 bře  2018 OI_ABORT.AUD
-rw-r--r--    119187  2 bře  2018 OI_ATACK.AUD
-rw-r--r--    123515  2 bře  2018 OI_BDRDY.AUD
-rw-r--r--    118147  2 bře  2018 OI_BLOST.AUD
-rw-r--r--    1 9476  2 bře  2018 OI_BUILD.AUD
-rw-r--r--    1 9843  2 bře  2018 OI_CANCL.AUD
-rw-r--r--    117051  2 bře  2018 OI_CAPT.AUD
-rw-r--r--    118274  2 bře  2018 OI_DHRDY.AUD
-rw-r--r--    118667  2 bře  2018 OI_DPLOY.AUD
-rw-r--r--    125171  2 bře  2018 OI_ENEMY.AUD
-rw-r--r--    113449  2 bře  2018 OI_GANEW.AUD
-rw-r--r--    110094  2 bře  2018 OI_GLOAD.AUD
-rw-r--r--    110094  2 bře  2018 OI_GSAVE.AUD
-rw-r--r--    1 7587  2 bře  2018 OI_GUARD.AUD
-rw-r--r--    120651  2 bře  2018 OI_HATTK.AUD
-rw-r--r--    110611  2 bře  2018 OI_HOLD.AUD
-rw-r--r--    118963  2 bře  2018 OI_LAUNC.AUD
-rw-r--r--    125659  2 bře  2018 OI_MAP1A.AUD
-rw-r--r--    120395  2 bře  2018 OI_MAP1B.AUD
-rw-r--r--    120555  2 bře  2018 OI_MAP1C.AUD
-rw-r--r--    127771  2 bře  2018 OI_MAP2A.AUD
-rw-r--r--    119419  2 bře  2018 OI_MAP2B.AUD
-rw-r--r--    121203  2 bře  2018 OI_MAP2C.AUD
-rw-r--r--    131803  2 bře  2018 OI_MAP3A.AUD
-rw-r--r--    152795  2 bře  2018 OI_MAP4A.AUD
-rw-r--r--    121435  2 bře  2018 OI_MAP5A.AUD
-rw-r--r--    140963  2 bře  2018 OI_MAP6A.AUD
-rw-r--r--    126531  2 bře  2018 OI_MAP7A.AUD
-rw-r--r--    132251  2 bře  2018 OI_MAP8A.AUD
-rw-r--r--    133363  2 bře  2018 OI_MAP9A.AUD
-rw-r--r--    1 9638  2 bře  2018 OI_MEND.AUD
-rw-r--r--    121287  2 bře  2018 OI_MFAIL.AUD
-rw-r--r--    120479  2 bře  2018 OI_MONEY.AUD
-rw-r--r--    115694  2 bře  2018 OI_MWIN.AUD
-rw-r--r--    126339  2 bře  2018 OI_NEWOP.AUD
-rw-r--r--    124843  2 bře  2018 OI_NROOM.AUD
-rw-r--r--    114644  2 bře  2018 OI_ORDER.AUD
-rw-r--r--    117139  2 bře  2018 OI_PLACE.AUD
-rw-r--r--    112011  2 bře  2018 OI_POWER.AUD
-rw-r--r--    120947  2 bře  2018 OI_PREP.AUD
-rw-r--r--    127507  2 bře  2018 OI_PRMRY.AUD
-rw-r--r--    123155  2 bře  2018 OI_REINF.AUD
-rw-r--r--    113603  2 bře  2018 OI_RUN.AUD
-rw-r--r--    114459  2 bře  2018 OI_SELL.AUD
-rw-r--r--    114568  2 bře  2018 OI_SILOS.AUD
-rw-r--r--    125235  2 bře  2018 OI_SPORT.AUD
-rw-r--r--    1 7571  2 bře  2018 OI_TRAIN.AUD
-rw-r--r--    113451  2 bře  2018 OI_ULOST.AUD
-rw-r--r--    112299  2 bře  2018 OI_UNRDY.AUD
-rw-r--r--    118443  2 bře  2018 OI_UPGOP.AUD
-rw-r--r--    112980  2 bře  2018 OI_UPGRD.AUD
-rw-r--r--    113403  2 bře  2018 OI_WATTK.AUD
-rw-r--r--    111131  2 bře  2018 OI_WSIGN.AUD
-rw-r--r--    115695  2 bře  2018 O_ECONF1.AUD
-rw-r--r--    116215  2 bře  2018 O_ECONF2.AUD
-rw-r--r--    119919  2 bře  2018 O_ECONF3.AUD
-rw-r--r--    115431  2 bře  2018 O_ESEL1.AUD
-rw-r--r--    121151  2 bře  2018 O_ESEL2.AUD
-rw-r--r--    111535  2 bře  2018 O_ESEL3.AUD
-rw-r--r--    115679  2 bře  2018 O_ICONF1.AUD
-rw-r--r--    112799  2 bře  2018 O_ICONF2.AUD
-rw-r--r--    119791  2 bře  2018 O_ICONF3.AUD
-rw-r--r--    113287  2 bře  2018 O_ISEL1.AUD
-rw-r--r--    120663  2 bře  2018 O_ISEL2.AUD
-rw-r--r--    113127  2 bře  2018 O_ISEL3.AUD
-rw-r--r--    120564  2 bře  2018 O_SCONF1.AUD
-rw-r--r--    121196  2 bře  2018 O_SCONF2.AUD
-rw-r--r--    117208  2 bře  2018 O_SCONF3.AUD
-rw-r--r--    120564  2 bře  2018 O_SSEL1.AUD
-rw-r--r--    111608  2 bře  2018 O_SSEL2.AUD
-rw-r--r--    112726  2 bře  2018 O_SSEL3.AUD
-rw-r--r--    117208  2 bře  2018 O_VCONF1.AUD
-rw-r--r--    114963  2 bře  2018 O_VCONF2.AUD
-rw-r--r--    117208  2 bře  2018 O_VCONF3.AUD
-rw-r--r--    111192  2 bře  2018 O_VSEL1.AUD
-rw-r--r--    114963  2 bře  2018 O_VSEL2.AUD
-rw-r--r--    113031  2 bře  2018 O_VSEL3.AUD

./Content/d2k/v2/Movies:
-rwxr-xr-x   131340246 19 srp  1998 A_BR01_E.VQA
-rwxr-xr-x   110924044 20 čvc  1998 A_BR02_E.VQA
-rwxr-xr-x   113266834 21 čvc  1998 A_BR03_E.VQA
-rwxr-xr-x   1 5473260 20 čvc  1998 A_BR04_E.VQA
-rwxr-xr-x   111826886 20 čvc  1998 A_BR05_E.VQA
-rwxr-xr-x   114989266 20 čvc  1998 A_BR06_E.VQA
-rwxr-xr-x   117780544 20 čvc  1998 A_BR07_E.VQA
-rwxr-xr-x   1 9850190 20 čvc  1998 A_BR08_E.VQA
-rwxr-xr-x   1 7974710 21 čvc  1998 A_BR09_E.VQA
-rwxr-xr-x   1 8467430 20 čvc  1998 A_FINL_E.VQA
-rwxr-xr-x   1 2375132 20 čvc  1998 A_LOSE_E.VQA
-rwxr-xr-x   1 4693066 20 čvc  1998 A_MNTG_E.VQA
-rwxr-xr-x   117357118 21 čvc  1998 G_INT1_E.VQA
-rwxr-xr-x   116536144 20 čvc  1998 G_INT2_E.VQA
-rwxr-xr-x   1  642330 20 čvc  1998 G_MAPS_E.VQA
-rwxr-xr-x   1  107716 14 kvě  1998 G_PLN2_E.VQA
-rwxr-xr-x   1  547968 20 kvě  1998 G_PLNT_E.VQA
-rwxr-xr-x   113928404 20 čvc  1998 H_BR01_E.VQA
-rwxr-xr-x   1 8263512 28 čvc  1998 H_BR02_E.VQA
-rwxr-xr-x   1 4666448 20 čvc  1998 H_BR03_E.VQA
-rwxr-xr-x   111271546 20 čvc  1998 H_BR04_E.VQA
-rwxr-xr-x   116586668 20 čvc  1998 H_BR05_E.VQA
-rwxr-xr-x   115730664 20 čvc  1998 H_BR06_E.VQA
-rwxr-xr-x   1 9855076 11 črv  1998 H_BR07_E.VQA
-rwxr-xr-x   111092272 20 čvc  1998 H_BR08_E.VQA
-rwxr-xr-x   1 7537450 20 čvc  1998 H_BR09_E.VQA
-rwxr-xr-x   116579412 20 čvc  1998 H_FINL_E.VQA
-rwxr-xr-x   1 2479234 20 čvc  1998 H_LOSE_E.VQA
-rwxr-xr-x   1 3651298 20 čvc  1998 H_MNTG_E.VQA
-rwxr-xr-x   1 6791404 20 čvc  1998 O_BR01_E.VQA
-rwxr-xr-x   112232540 20 čvc  1998 O_BR02_E.VQA
-rwxr-xr-x   112015426 20 čvc  1998 O_BR03_E.VQA
-rwxr-xr-x   124945628 20 čvc  1998 O_BR04_E.VQA
-rwxr-xr-x   120670794 20 čvc  1998 O_BR05_E.VQA
-rwxr-xr-x   112748496 20 čvc  1998 O_BR06_E.VQA
-rwxr-xr-x   110477272 21 čvc  1998 O_BR07_E.VQA
-rwxr-xr-x   120127824 20 čvc  1998 O_BR08_E.VQA
-rwxr-xr-x   118114100  4 srp  1998 O_BR09_E.VQA
-rwxr-xr-x   1 7725866 20 čvc  1998 O_FINL_E.VQA
-rwxr-xr-x   1 2413672 20 čvc  1998 O_LOSE_E.VQA
-rwxr-xr-x   1 3895616 20 čvc  1998 O_MNTG_E.VQA
-rwxr-xr-x   1 1254330 22 čvc  1998 T_TITL_E.VQA

./Content/d2k/v2/Music:
-rwxr-xr-x   12850649  4 črv  1998 AMBUSH.AUD
-rwxr-xr-x   12726699 21 dub  1998 ARAKATAK.AUD
-rwxr-xr-x   12869891 21 dub  1998 ATREGAIN.AUD
-rwxr-xr-x   13514467 21 dub  1998 ENTORDOS.AUD
-rwxr-xr-x   13931374 21 dub  1998 FIGHTPWR.AUD
-rwxr-xr-x   13035722 21 dub  1998 FREMEN.AUD
-rwxr-xr-x   12876915 21 dub  1998 HARK_BAT.AUD
-rwxr-xr-x   13399387 21 dub  1998 LANDSAND.AUD
-rwxr-xr-x   1 591940 18 čvc  1998 OPTIONS.AUD
-rwxr-xr-x   13051235  4 črv  1998 PLOTTING.AUD
-rwxr-xr-x   12434125 21 dub  1998 RISEHARK.AUD
-rwxr-xr-x   12804635 21 dub  1998 ROBOTIX.AUD
-rwxr-xr-x   11410157 18 čvc  1998 SCORE.AUD
-rwxr-xr-x   12704291  4 črv  1998 SOLDAPPR.AUD
-rwxr-xr-x   13480629 21 dub  1998 SPICESCT.AUD
-rwxr-xr-x   13047967 21 dub  1998 UNDERCON.AUD
-rwxr-xr-x   12843635 21 dub  1998 WAITGAME.AUD`
