### ISSUE TITLE
Crash after changing attack stance

### ISSUE THREAD

**Issue by Aneyrin** [OpenRA/OpenRA#14762]
Hello there. Time to time OpenRa crushing after changing attack stance. Issue appears on MacOS Sierra. Please look at attached log file.
[exception-2018-01-23T231237Z.log](https://github.com/OpenRA/OpenRA/files/1657957/exception-2018-01-23T231237Z.log)

**Comment by Aneyrin** [comment]
Latest logs after issue attached (including debug menu).
[debug.log](https://github.com/OpenRA/OpenRA/files/1665407/debug.log)
[exception-2018-01-25T193830Z.log](https://github.com/OpenRA/OpenRA/files/1665408/exception-2018-01-25T193830Z.log)




[perf.log](https://github.com/OpenRA/OpenRA/files/1665409/perf.log)

**Comment by Aneyrin** [comment]
Several logs (exception.log) from last crashed games. looks like this bug appears in single and multiplayer game anytime when you randomly changing unit attack stance using hotkey or in-game icon. 

[exception-2018-01-26T231022Z.log](https://github.com/OpenRA/OpenRA/files/1669547/exception-2018-01-26T231022Z.log)
[exception-2018-01-27T000514Z.log](https://github.com/OpenRA/OpenRA/files/1669548/exception-2018-01-27T000514Z.log)

**Comment by pchote** [comment]
It looks like one of the cursors is corrupted.  Have you made any modifications to your game files?  Try redownloading OpenRA.

**Comment by Aneyrin** [comment]
Yes I changed some shp with infantry units to make them proper size c&c-like . What exactly shp occur this issue?

**Comment by pchote** [comment]
Your logs don't give enough information to be able to say which specific file is the problem, just that it is one of the mouse cursors.

Can you please confirm that the crash only occurs with your modified files?

**Comment by Aneyrin** [comment]
Yes, now I can't reproduce such issue. Thank you for help
