### ISSUE TITLE
Removing Hijackers from combat units 

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#14769]
Suggestion to remove Hijackers from combat units.

Reasons for that : 
- Hijackers don't have attack stances / can't a-move
- Sending them with an army will often get them in front (faster unit), and killed without any beneficial outcome
- Selecting all units will move them from their positions, uncloaking them.

**Comment by Smittytron** [comment]
Will throw this and minlayers (#14770) in my playtest. Going into this I think minelayers make sense for lower selection priority. The only concern with hijackers is that they are often paired with APCs. I want to see if that will cause problems before making a change.
