### ISSUE TITLE
Map Editor - Count resources in a selected area

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#14771]
Current method to know how much resources are there in a selected area, is to copy-paste it somewhere else, and do the math. Not always convenient, especially if the map lacks empty spaces. 

Not sure if it's a duplicate of #2884

**Comment by MustaphaTR** [comment]
That issue is about the total. This is duplicate of #9477 tho, which had an attempted pr of #14055.

**Comment by CH4Code** [comment]
Add a line of code to the "copy area" code which shows the ammount of ore/tib/spice in the area selected for copying.

**Comment by abcdefg30** [comment]
Seems like this was closed by #21315.
