### ISSUE TITLE
Introduce a "slowest" gamespeed option

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#14784]
This was requested by some fans who said the game is currently too fast for them.

Fortunately with @abcdefg30's guidance they were able to make the necessary change locally but I see no reason we cannot provide this properly.

**Comment by PeterAntal** [comment]
Refinement questions: to @Phrohdoh & @abcdefg30 
What speeds were desired, relative to normal? e.g. "half", or some other option?

I assume the idea here would be to throttle down the logic cycle frequency, perhaps do something tweakable, like an opt-in "Game Logic Rate Limiter" option?

I could see exposing this option under either Settings > Advanced or Settings > Display.

Seems likely that it would impair replay debuggability, and would likely be simplest to restrict to non-single player play. Not a reason to not provide, but simply to set expectations abt limitations.

Thoughts?

**Comment by abcdefg30** [comment]
The speed requested was one with a Timestep of 80.

**Comment by reaperrr** [comment]
Addressed by #14861.
