### ISSUE TITLE
Improve error message if connection to master server fails

### ISSUE THREAD

**Issue by jrb0001** [OpenRA/OpenRA#14788]
`Failed to query server list.` does not help at all to find the cause and fix the issue.

**Comment by fastslack** [comment]
I have same problem on lastest release (20180218). Any solution?

**Comment by pchote** [comment]
@fastslack are you running linux by any chance? What version of mono do you have installed?

**Comment by fastslack** [comment]
```
$ mono -V
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug
	LLVM:          supported, not enabled.
	GC:            sgen
```

Yes, linux mint sylvia / ubuntu xenial

**Comment by pchote** [comment]
Installing the `ca-certificates-mono` package should fix it.

**Comment by fastslack** [comment]
@pchote Problem solved. Thanks!

**Comment by pchote** [comment]
Mono versions < 3.12 (3.2, shipped with ubuntu 14.04 and older debians) do not include a `ca-certificates-mono` package, and users must instead manually install the certificates.  Unfortunately the `mozroots` command that used to automatically import the mozilla certificate store has bitrotted from API changes, and is no longer functional.

In the last 3 months we have had 275 sysinfo-enabled Linux players running mono versions older than 3.12.  This is ~4% of our Linux player base during the same period, or 0.9% of all players.

Considering the above, I think our best option will be to raise the minimum mono version to 3.12 on Linux (it is already 4.6 on macOS), and update the notes on the Linux download tab on the website with a note about http://www.mono-project.com/download/stable/#download-lin.  This is consistent with what we did with Ubuntu 12.04 and SDL2.

**Comment by pchote** [comment]
The sysinfo shows only 12 more entries with mono versions greater than 3.2.8 but less than 4.2.  4.2 is shipped by default in Ubuntu 16.04, so seems like a better baseline requirement than 3.12 (which nobody is running).

**Comment by abcdefg30** [comment]
Fixed by #14870 I assume.

**Comment by jrb0001** [comment]
Not fixed at all. The linked PR is about bumping the minimum mono version, this issue is about improving the error message to include informations about the cause of the failure.

**Comment by abcdefg30** [comment]
My bad then.
