### ISSUE TITLE
Engineer can sometimes destroy buildings

### ISSUE THREAD

**Issue by CDVoidwalker** [OpenRA/OpenRA#14792]
Here it's engi with 55% building damage https://www.youtube.com/watch?v=rEQqeVT9FCc

**Comment by MustaphaTR** [comment]
I think this is the intented behaviour when capturer's SabotageHPRemoval is higher than capturable's CaptureThreshold.

**Comment by CDVoidwalker** [comment]
Oh, if that's the case then it's my bad. Closing
