### ISSUE TITLE
Aircraft stop queued attacks after reloading

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#14805]
Tested on playtest-20180208

After giving a series of attack orders, and after reloading at airfields / helipads, air units won't continue the attacks. 
Planes seem to stay on airfields, helis go to rally point.

**Comment by pchote** [comment]
The cancelling behaviour was intentional, see the issues references from #12102.  We received heated complaints when we last fixed this, so ended up undoing them.

**Comment by FRenzy-OpenRA** [comment]
Ok IIUC this has to do with : 
- helos repairing
- aircraft being dragged into enemy fire, after chasing a previous target
- A-move ? 

I was more thinking actually about queued static targets, especially with soviet aircraft (no repairing issues), in which case it would be interesting to have uninterrupted attacks. But I guess it can't be dealt with as a separate behaviour, or could it be ? 

What about airplanes going back to the rally point ? That could be a compromise to know when airplanes are done reloading, and available to resume the attack.

**Comment by matjaeck** [comment]
The airfield and helipad have a reload animation so you can still tell if they're reloading even when they stay at the airfield. IMO this is a feature (abort on resupply) that just doesn't work properly yet for attack move.

**Comment by matjaeck** [comment]
Fixed by #16721.
