### ISSUE TITLE
Turn when idle trait for infantry

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#14808]
Think nobody remembered this, but in RA2 and TS infantry turned when they were idle (changed their current facing), idk if they did that back in td / ra, but I am certain tanks in d2k also aimed their turrets randomly when idle.

**Comment by Mailaender** [comment]
Duplicate of https://github.com/OpenRA/OpenRA/issues/9161.

**Comment by GraionDilach** [comment]
Uhm, no, not really, that one explicitly mentions turrets while this is about infantry.

**Comment by Mailaender** [comment]
My bad.

**Comment by GraionDilach** [comment]
@CDVoidwalker did this obne ages ago. https://github.com/AttacqueSuperior/Engine/blob/master/OpenRA.Mods.AS/Traits/TurnOnIdle.cs

**Comment by Mailaender** [comment]
Note: our implementation differs slightly now after review changes.
