### ISSUE TITLE
Dedicated servers with debian 8 and mono 5

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#14819]
From Discord from Jazz:

jaZz_KCS - Today at 1:46 AM
Debian 8 and Mono 5.8 in conjunction give me sporadic core hogging, making individual server instances hog entire cores. My servers are set so that when this happens, they loop automatically, resolving the problem. It will only loop when still in lobby mode btw, not in playing mode. Just FYI
This applies to most recent release version.

netnazgul - Today at 1:50 AM
whats a loop

jaZz_KCS - Today at 2:16 AM
Upon a completed game session, the server restarts / loops

**Comment by abcdefg30** [comment]
Is this still an issue?

**Comment by pchote** [comment]
We now require mono >= 5.18, soon to be bumped to 6.4.

**Comment by Mailaender** [comment]
https://docs.microsoft.com/dotnet/core/install/linux-debian instead might help. Closing as Debian 8 and @mono 5 are deprecated now.
