### ISSUE TITLE
Dedicated Server with Chat Flood Hotfix (release 20171014) crash in lobby

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#14821]
From console - this is in the lobby before the game starts:

Player @150.107.172.187:57238 is Ready
MymiC=('.'Q)|11@IP: �Chat.
MymiC=('.'Q)|11@IP: �Chat.
MymiC=('.'Q)|11@IP: �Chat.
MymiC=('.'Q)|11@IP: �Chat.
MymiC=('.'Q)|11@IP: �Chat.
MymiC=('.'Q)|11@IP: �Chat.
MymiC=('.'Q)|11@IP: �Chat.
MymiC=('.'Q)|11@IP: �Chat.
* Assertion at mini-exceptions.c:2073, condition `tls->signal_stack' not met

I've seen floods not crash the server before. But what happens here is, the server hangs, and doesnt know that its hung, so it just sits there frozen (delists from master server and cant be connected to manually). The same function that is use to detect chat packets for the hotfix is being use to print to console, so its probably more related to function that detects chat packets than any derivative work.

Or it could be unrelated to the hotfix

**Comment by oraservers** [comment]
This server above is not running on mono 5.2 but yes the random crashes could be related

**Comment by abcdefg30** [comment]
Please reopen if this is still an issue.
