### ISSUE TITLE
Refinery spawned harvesters should prioritize lower ore

### ISSUE THREAD

**Issue by Smittytron** [OpenRA/OpenRA#14827]
Upon spawning, harvesters will move around the entire refinery if there is ore above and to the left. This makes ore trucks move past closer ore.

As most maps have starting ore to the left/right of players, the players with ore on the left will get behind if they don't immediatley micro their harvestor upon building a refinery. 

![trucks](https://user-images.githubusercontent.com/23546299/36342503-41d99230-13c5-11e8-8602-9ea1e24b6318.png)

**Comment by GraionDilach** [comment]
I'd call this a bug tbh, asin harv is looking from ore from the building's 0,0 footpriont cell instead of it's own spawnposition.
