### ISSUE TITLE
rpm package for release-20180218

### ISSUE THREAD

**Issue by Jiri-Kremser** [OpenRA/OpenRA#14834]
Hi could you please build the rpms for Fedora? Or provide better instructions on this wiki page https://github.com/OpenRA/OpenRA/wiki/Compiling ? Can I just clone the repo, checkout some release tag, build it and play? I recall, I was trying this with the last release and wasn't able to see or join any games.

**Comment by pchote** [comment]
@Mailaender can you please save the day here?

**Comment by Jiri-Kremser** [comment]
..or perhaps if you point me to the spec file so that I could build it myself. Thank you

**Comment by Mailaender** [comment]
https://build.opensuse.org/package/show/games:openra/release needs to get updated.

**Comment by Jiri-Kremser** [comment]
I believe I've created something like pull request in that `build.opensuse.org` system, however when installing the resulting rpm. I wasn't able to find any online games in the menu :/

**Comment by Jiri-Kremser** [comment]
ha!
I guess, this doesn't seems to be correct:
```
Internal mods:
	cnc: Tiberian Dawn (release-20180218)
	d2k: Dune 2000 (release-20180218)
	modcontent: Mod Content Manager (release-20180218)
	ra: Red Alert (release-20180218)
External mods:
	cnc-playtest-20170930: Tiberian Dawn (playtest-20170930)
	cnc-release-20180218: Tiberian Dawn (release-20180218)
	d2k-playtest-20170930: Dune 2000 (playtest-20170930)
	d2k-release-20180218: Dune 2000 (release-20180218)
	ra-playtest-20170930: Red Alert (playtest-20170930)
	ra-release-20180218: Red Alert (release-20180218)
	d2k-release-20171014: Dune 2000 (release-20171014)
	ra-{DEV_VERSION}: Red Alert ({DEV_VERSION})
```

**Comment by pchote** [comment]
The internal mods setting above looks right, so i'm not sure why it fails.  Are you possibly seeing #14788?  I don't think updating the version in the spec file will be enough - some of the dependencies have been updated, so `thirdparty.tar.gz` will also need to be updated.

**Comment by Mailaender** [comment]
SmartIrc4Net.dll was removed https://github.com/OpenRA/OpenRA/commit/502c3e2bf5bad7abf98df1198c8a8af6701f2f76 but keeping the unused DLL shouldn't change anything.

https://build.opensuse.org/request/show/578722 solved this. Thanks for the submit request.
