### ISSUE TITLE
MasterServerPinger uses ListenPort instead of ExternalPort

### ISSUE THREAD

**Issue by rmoriz** [OpenRA/OpenRA#14832]
With the 20180218 release it's not possible to run multiple server instances on the same IP but different ExternalPorts. This was possible using a mixture of ListenPort/ExternalPort confguration settings and very useful with docker based deployments where routable IPv4 addresses are usually limited to the host address.

e.g.

```
docker run -d -p 1234:1234 \
             -e Name='Server 1' \
             -e Mod=ra \
             -e ListenPort="1234" \
             -e ExternalPort="1234" \
             --name trolling \
             --restart unless-stopped \
	     $IMAGE

docker run -d -p 1235:1234 \
             -e Name="Server 2" \
             -e Mod=ra \
             -e ListenPort="1234" \
             -e ExternalPort="1235" \
	     --name notrolling \
             --restart unless-stopped \
	     $IMAGE

docker run -d -p 1236:1234 \
             -e Name="Server 3" \
             -e Mod=ra \
             -e ListenPort="1234" \
             -e ExternalPort="1236" \
	     --name chat \
             --restart unless-stopped \
	     $IMAGE
```

https://github.com/OpenRA/OpenRA/commit/3ba610b53534e9da2da9ea2a843f2f47c7b2fbdc#diff-e4bcdcd60c4fd417a17c73d84a5d9641R177 uses the ListenPort to announce the server, not the ExternalPort

**Comment by pchote** [comment]
Is there anything in the meantime preventing you from setting ListenPort to match your ExternalPort in each of those docker commands?

**Comment by rmoriz** [comment]
I can work around this for now.
