### ISSUE TITLE
TS build on ice

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#14843]
Currently it is possible to build apon ice (TerrainType is `Clear`).
![unbenannt](https://user-images.githubusercontent.com/25386322/36567537-0fb7cd1a-1827-11e8-89e6-d87e09739a42.JPG)

Part of #8918

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/pull/10760.

**Comment by fruestueck** [comment]
Closed - under development.
