### ISSUE TITLE
Aircraft husk contrails are white, while normal ones are player colored

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#14849]
Looks like Contrails use actual owner and not EffectiveOwner and use Neutral player's Gray color to render for husks.

**Comment by airetaM** [comment]
Also the bounties are showed white when a husk is killing units.

**Comment by abcdefg30** [comment]
> Also the bounties are showed white when a husk is killing units.

This is indeed yet another issue... Created #14858.
