### ISSUE TITLE
TS e1 shooting over wall

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#14848]
Currently Rifleman can shoot over walls.
Disks from Diskthrowers are blocked as should.
![unbenannt](https://user-images.githubusercontent.com/25386322/36597711-4721c2b4-18aa-11e8-9b0d-64f1e292cd10.png)

**Comment by reaperrr** [comment]
This is intentional, it was that way in the original, too.

**Comment by abcdefg30** [comment]
> This is intentional, it was that way in the original, too.

I guess this is not an issue at the moment then, as balancing comes later.
