### ISSUE TITLE
Units can't damage themselves

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#14841]
Most obvious with grenadiers and flamethrowers in RA. Try ordering them to attack the cell they're standing on.

**Comment by skymanpl** [comment]
Bug or feature? 😄

**Comment by GraionDilach** [comment]
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Warheads/Warhead.cs#L47.

I hope you won1t suggest changing this default though...

**Comment by reaperrr** [comment]
I agree with @GraionDilach that this should stay the default behavior, and AffectsParent already allows to override it, so I think this can be closed.
