### ISSUE TITLE
Player name input gets reverted/loses focus while typing

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#14852]
Small but rather annoying issue: whenever anyone joins/leaves the server or types a message, player name edit gets reset/saved if you type something in it. This leads to make it very hard to change nickname to something long on a busy lobby because you'd barely have time to type 1-2 letters in.

**Comment by pchote** [comment]
Duplicate of #5802.  Follow the chain of issues/prs within for explanations on the cause and explanations of the code changes required to fix it.
