### ISSUE TITLE
2 aircraft landing on 1 airfield

### ISSUE THREAD

**Issue by anjew175** [OpenRA/OpenRA#14867]
### Issue Summary
In the replay at 11 minutes 2 aircraft land on 1 airfield after a new airfield was built. Despite the fact one of the aircraft was already armed, its my understanding this isnt intended.

#### Additional Information:
I am unsure of how to reproduce this bug. I attempted myself to show in an isolated replay but I don't know what caused it. It could be possibly a combination of having given a command to reload, placing a new airfield and giving the command to reload again.

- OpenRA Replays
[2 planes 1 airfield 11minutes.zip](https://github.com/OpenRA/OpenRA/files/1771777/2.planes.1.airfield.11minutes.zip)

It occurs at 11 minutes in my base (pink)

**Comment by fruestueck** [comment]
Seems like duplication of #14114
