### ISSUE TITLE
Tanya's Icon in barrack doesn't grayed out when Tanya is in a camo pillbox

### ISSUE THREAD

**Issue by shiningdracon** [OpenRA/OpenRA#14878]
### Issue Summary
Tanya's Icon in barrack doesn't grayed out when Tanya is in a camo pillbox.

It just a display issue, you can't build more than one Tanya.

#### System Information
- **Operating System:** Ubuntu 16.04
- **.NET / Mono Version:** Mono 5.10.0.140
- **OpenRA Version:** release-20180218
- **Mod:** Red Alert

#### Additional Information:
- Steps to reproduce
	1. Build a Tanya (Tanya's Icon becomes gray)
	2. Build a camo pillbox
	3. Put Tanya into that camo pillbox (Tanya's Icon becomes light)

**Comment by GraionDilach** [comment]
Duplicate of #5872.
