### ISSUE TITLE
Does not work with Mono from Homebrew on macOS X

### ISSUE THREAD

**Issue by yetisyny** [OpenRA/OpenRA#14879]
### Issue Summary

On macOS X, many people install Mono using the Homebrew package manager. Instructions for installing Homebrew are at its website, [https://brew.sh](https://brew.sh/). Once it is installed, the latest version of Mono that works with Homebrew, currently version 5.4.1.6, can be installed with the command-line command “brew install mono” in a terminal such as Terminal.app or iTerm2. The Mono that Homebrew installs meets the minimum version requirement for OpenRA, 4.6. While OpenRA was previously 32-bit on macOS X and this made it not work with the 64-bit Mono from Homebrew, that is no longer an issue since OpenRA has switched to 64-bit on macOS X since version release-20180218 so it should be able to work with the Mono from Homebrew as long as it is able to detect it.

The obvious workaround is to install the precompiled binary packages of Mono from the official Mono website linked to from the OpenRA website, but for people who already installed Mono from Homebrew or like to do things using Homebrew, this workaround is rather annoying, and it would be unnecessary if OpenRA were made to be able to detect and use Mono installed by Homebrew.

Typically Mono from Homebrew installs a mono executable symlinked into a directory in the PATH, and the same would be true for Mono from another package manager such as MacPorts too. So, OpenRA should, if it fails to detect an official Mono package on macOS X, open the default command shell for the current user (typically bash but some people install zsh or fish or something else instead), let it load the .bash_profile or equivalent file for whatever command shell is being used, and then check to see if there is a “mono” executable in the PATH that can be run, and if so, use it.

Or if that is too much work, just check the default location Homebrew uses of /usr/local/bin. There are also other package managers for macOS X, the main other one is MacPorts, I believe it installs things to /opt/local/bin instead of /usr/local/bin. But the method of looking for a mono executable in the PATH specified once you are in the default command shell, that would work with ANY package manager or for people who compile and build Mono and install it themselves manually.

#### System Information
- **Operating System:** macOS 10.12 Sierra
- **.NET / Mono Version:** Mono 5.4.1.6 installed by Homebrew package manager to /usr/local/bin
- **OpenRA Version:** release-20180218
- **Mod:** Red Alert, Tiberian Dawn, and Dune2000, all 3

#### Additional Information:
- Steps to reproduce
	1. Instead of installing precompiled binaries of Mono from the Mono website, install it from the Homebrew package manager on macOS X with the command “brew install mono”.
	2. Install OpenRA and try to use it with the Mono from Homebrew, and it will give you the error that Mono is not installed and require you to use the precompiled binary version of Mono instead of just working like it ought to.

**Comment by pchote** [comment]
OpenRA on macOS doesn't use the `mono` executable, but instead links against the `libmono-2.0.dylib` library (https://github.com/OpenRA/OpenRALauncherOSX/blob/master/launchgame.m#L86).

**Comment by yetisyny** [comment]
Including Mono inside the .app seems like a bad idea, Mono takes up a ton of disk space, the whole reason I filed this bug was I already had the Homebrew Mono and adding the precompiled Mono from the official Mono website wastes disk space (I DID uninstall the Homebrew Mono and switch to only using the precompiled Mono from the website, but it does not seem to have a “mono” command-line executable anymore which is a bit of a let-down since other programs, typically .exe files for Windows, might need that to be run in Mono on a Mac).

**Comment by pchote** [comment]
Prototyping for #12170 shows that the bits of mono that OpenRA *actually* depends on add up to only about 6MB when zipped.
