### ISSUE TITLE
Dependencies wont download due to SSL certificate errors.

### ISSUE THREAD

**Issue by linuxfun** [OpenRA/OpenRA#14884]
Hi all.

So I have been trying to compile the master build of OpenRA and there are three dependencies that will not download for me. These are Eluant.dll, OpenAL-CS.dll and SDL2-CS.dll.

If I try to compiled OpenRA without these I get about 152 errors and nothing will really compile.

There is only one branch of OpenRA that will compile for me and that is OpenRA-bleed

To reproduce this just download the source .zip file of the master branch of OpenRA and run make.cmd type all and press enter. It will get every other dependency apart from the three listen above. I have also tried to build this with Visual Studios 2013 and I get a little further with a white screen but then nothing else loads.

Seriously wish the builds came with the dependencies already instead of having to download them off github which may or may not have SSL and if it doesn't then my PC will not trust that connection and then will not download. 

I have even tried powershell with the exact same result.

**Comment by Unit158** [comment]
Please use the template when submitting bug reports.
What version of mono are you using?

**Comment by Unit158** [comment]
Please follow the template when submitting a bug report.

It sounds like there's an issue with a firewall or something similar that is not properly configured. Might be worth trying to find help on the IRC. #openra on freenode. Also, OpenRA uses tags for its releases, so master is seriously out-of-date.

**Comment by pchote** [comment]
Despite supporting TLS1.2, Powershell on windows does not enable it by default.  The dependency fetching therefore broke when GitHub [disabled support for TLS 1/1.1](https://blog.github.com/2018-02-23-weak-cryptographic-standards-removed/).  

A fix (#14855 - forcing Powershell to use TLS1.2) has already been merged to bleed and a hotfix release is being prepared for release hopefully within the next week.

Closing as duplicate / fixed.

**Comment by fruestueck** [comment]
I simply pulled the latest bleed,
fetched all dependancies (make.cmd) and then switched back to my (behind) working branch.
Was a workaround for me
