### ISSUE TITLE
Question: Adding shortcuts to make.cmd; d for dependencies

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#14880]
Would it be benificial to add shortcuts to the make.cmd? 
E.g. `d` for `dependencies`
`c` for `check`
`s` for `checkscript`
...

Sure it isn't necessary but could save a couple hours lifetime (counted up)

**Comment by reaperrr** [comment]
Personally, I'm in favor of this. 
Sure, the most-used 'all' command is pretty quick to enter, which also makes `dependencies` rarely used, but the check commands + `test` would benefit from this a bit more.

**Comment by fruestueck** [comment]
Switch statement could look like
```
switch ($execute)
{
	{"all",           "a"  -contains $_} { All-Command }
	{"dependencies",  "d"  -contains $_} { Dependencies-Command }
	{"version",       "v"  -contains $_} { Version-Command }
	{"clean",         "cn"  -contains $_} { Clean-Command }
	{"test",          "t"  -contains $_} { Test-Command }
	{"check",         "c"  -contains $_} { Check-Command }
	{"check-scripts", "cs" -contains $_} { Check-Scripts-Command }
	{"docs",          "d"  -contains $_} { Docs-Command }
	Default { echo ("Invalid command '{0}'" -f $command) }
}
```

**Comment by pchote** [comment]
I'd maybe put clean as "c" and then check as either "ck" or "cy" (check yaml)

**Comment by fruestueck** [comment]
I am not happy with the presentation of it
![unbenannt](https://user-images.githubusercontent.com/25386322/36950209-f011e4cc-1ff2-11e8-9d68-ff3320316856.JPG)
