### ISSUE TITLE
Do not run Open Ra  release-20180218 on XP.

### ISSUE THREAD

**Issue by Skandinav83** [OpenRA/OpenRA#14885]
Good day to all! English I do not know why I'm writing through Google Transl.

 I do not run Open RA the latest stable release is release-20180218. 
Operating system Windows XP SP 3. 
When installing the game itself, there is an error referring to the directory \ ModMetadata. 
When you run the game itself through any label goes an error. Log and screen apply.

exception-2018-03-07T061106Z.log
=> OpenRA engine version release-20180218
      Date: 2018-03-07 06:11:06Z
      Operating System: Windows (Microsoft Windows NT 5.1.2600 Service Pack 3)
      Runtime Version: .NET CLR 4.0.30319.1022
      Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library.      Check graphics.log for details.
   в OpenRA.Game.Initialize(Arguments args)
   в OpenRA.Game.InitializeAndRun(String[] args)
   в OpenRA.WindowsLauncher.RunGame(String[] args)

=>graphics.log
System.Reflection.ReflectionTypeLoadException: Не удается загрузить один или более запрошенных типов. Обратитесь к свойству LoaderExceptions для получения дополнительных сведений.
   в System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   в System.Reflection.RuntimeModule.GetTypes()
   в System.Reflection.Assembly.GetTypes()
   в OpenRA.Game.Initialize(Arguments args)
System.Reflection.ReflectionTypeLoadException: Не удается загрузить один или более запрошенных типов. Обратитесь к свойству LoaderExceptions для получения дополнительных сведений.
   в System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   в System.Reflection.RuntimeModule.GetTypes()
   в System.Reflection.Assembly.GetTypes()
   в OpenRA.Game.Initialize(Arguments args)

**Comment by GraionDilach** [comment]
Windows XP is no longer supported for a while now.

**Comment by abcdefg30** [comment]
Windows XP doesn't support the .NET version required for OpenRA. Seems like you need to update your OS, sorry.
