### ISSUE TITLE
Feature request: Debian package repository

### ISSUE THREAD

**Issue by fusion809** [OpenRA/OpenRA#14894]
Hi,

This game is great, but the interesting thing is that while you's only provide Debian packages for Linux (instead of say providing RPM and Arch packages as well, or w/e), I think RPM-based distributions have the advantage. See RPM-based distributions have package repositories (i.e. the one in the openSUSE Build Service), hence RPM-based distributions get automatic updates, but Debian-based distributions don't. Users of Debian-based distributions instead have to manually download the Debian package whenever a new release is made and then install it manually with dpkg. This can get very irritating, so I am here to ask for Debian package repositories for OpenRA. 

To be clear I am not whinging that you's only provide Debian packages, I get that users like me should be grateful you's provide any binaries at all!

Thanks for your time,
Brenton

**Comment by seancallaway** [comment]
It appears that someone has already requested that a PPA be created in #9201 and there was discussion of the openSUSE Build Service there, as well.

**Comment by pchote** [comment]
OBS is rather difficult to work with, and the OpenRA project there is no longer actively maintained.  It has been a struggle to keep it updated over the last several releases, so relying on it continuing to exist in the future would not be wise.

Updating the automated travis builds to deploy to bintray or a similar service would be a lot safer.
