### ISSUE TITLE
Performance regressed since release 20171014

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#14905]
Despite the number of performance optimizations done for the current release, there has been more than one report on this, and it matches my own impression to some extent.

The only noticable change in perf.log is that `FrozenUnderFog` seems to pop up more often.
This is an example excerpt from my perf.log on RA shellmap:

```
     5 ms [861] Trait: brik->FrozenUnderFog
     5 ms [867] Activity: Attack
     5 ms [873] Trait: brik->FrozenUnderFog
     6 ms [879] Trait: tent->FrozenUnderFog
     7 ms [889] Trait: gap->FrozenUnderFog
     5 ms [931] Effect: Bullet
     6 ms [945] Trait: 2tnk->RevealsShroud
     5 ms [952] Trait: weap->FrozenUnderFog
     6 ms [962] Activity: Attack
     5 ms [970] Trait: apwr->FrozenUnderFog
```

This is more of a worst-case and not the norm, but I imagine on large maps with many players, this will scale up accordingly.

Frozen actor logic *was* partially rewritten as part of the render/selection bounds refactor, so it's entirely possible that its performance regressed. It seems to be the best starting point, in any case.

**Comment by reaperrr** [comment]
Pinging @RoosterDragon and @pchote since I doubt anyone else will be able to figure this one out.

**Comment by pchote** [comment]
AFAIK @RoosterDragon's optimizations were profiled and tested primarily on a windows-compiled build.  It would be useful to profile the travis-compiled release build to make sure that `mcs` isn't generating unusually slow code now.

**Comment by RoosterDragon** [comment]
I've had ~10 small perf PRs I've been meaning to find the time to file, some of which address minor regressions from refactorings/bug fixes. However I felt in unfair to spam the PR queue with a bunch of PRs and create work without having time to review stuff as well.

One of them did happen to be related to FrozenUnderFog, try #14917 and see it that makes a difference. Performance here regressed when we had to start capturing a snapshot of target types for correctness.

**Comment by pchote** [comment]
@RoosterDragon, @reaperrr: Do you think we have done enough to close this yet?

**Comment by reaperrr** [comment]
In my opinion yes.

**Comment by RoosterDragon** [comment]
Agree.
