### ISSUE TITLE
RevealOnDeath not functioning for RA Aircrafts

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#14902]
RevealOnDeath attached to ^PlaneHusk and ^HelicopterHusk (#13878) is not functioning. The feature worked with the playtest0208 and dropped with the release0218.

#14804 is a related PR within that time period, altering SpawnActorOnDeath with ^NeutralPlane.

**Comment by reaperrr** [comment]
> [00:33] <+pchote> IIRC we have an issue about reverting tech structures to neutral when a player loses
[00:33] <+pchote> I can't find it
[00:34] <+pchote> but we could use that same logic on husks
[00:34] <+pchote> and then that fixes the issues with bounties and vision

**Comment by GraionDilach** [comment]
That issue is #4706. Can't see the relation though myself.

**Comment by pchote** [comment]
Husks are now spawned as neutral actors, which means that `RevealOnDeath` works for the Neutral player, not the original owner.  The only reasonable way to fix this and #14858 is to revert the change that spawned husks as neutral, reintroducing the husk disappearing on surrender issue.  It's this last point that relates to #4706.
