### ISSUE TITLE
Voxelsequences:

### ISSUE THREAD

**Issue by bodomalo** [OpenRA/OpenRA#14918]
I tried to add a voxelunit in OpenRA

when I add this to mod.yaml
Voxelsequences:
	cncred|sequences/voxels.yaml

openra crashes: `VoxelSequences` is not a valid mod manifest entry.

Can someone update this guide?
https://github.com/OpenRA/OpenRA/wiki/Adding-a-voxel-unit-ingame

**Comment by abcdefg30** [comment]
It was renamed to `ModelSequences` iirc.

**Comment by tovl** [comment]
This was fixed two years ago: https://github.com/OpenRA/OpenRA/wiki/Adding-a-voxel-unit-ingame/_compare/5d254e3289a4bfb38fa272f27f735a7c2fcd0acf...85831573567a70af3d65bd3e6a7d9a09d3ebbaf5
