### ISSUE TITLE
Website: Go for HTTPS

### ISSUE THREAD

**Issue by Echolon** [OpenRA/OpenRA#14914]
Hi,

I'd like to encourage to HTTPS-encrypt the OpenRA website. It's maybe just a game website, but HTTPS should be enabled everywhere I think. Google and Firefox even down-rate and warn of unencrypted websites! At least it's state of the art in 2018.

You can get certificates for free here: 
- https://letsencrypt.org

Anyway, thanks for your engagement - this is my favorite mod/project to follow! And of course to play! Would be even more nice to access it through HTTPS ;)

Looking forward!

- https://blog.mozilla.org/security/2017/01/20/communicating-the-dangers-of-non-secure-http/
- https://security.googleblog.com/2017/04/next-steps-toward-more-connection.html

![menu_064](https://user-images.githubusercontent.com/29168011/37431885-c6ecc3b4-27d6-11e8-80d6-4ba189beb7b4.jpg)

**Comment by ltem** [comment]
Hallo,
You put quite some effort in it but you are at the wrong issue tracker. The correct one would be here [LINK](https://github.com/OpenRA/OpenRAWeb/issues), which already has an open issue for https [LINK](https://github.com/OpenRA/OpenRAWeb/issues/372).
So I'll close this issue but you're welcome to add any miissing information.

**Comment by Echolon** [comment]
Yes, sorry. Didn't recognise that there is an extra branch for the website.

Cheers!
