### ISSUE TITLE
Ability to change the strength of the Shroud

### ISSUE THREAD

**Issue by Master0r0** [OpenRA/OpenRA#14922]
Would it be or is it currently possible to modify the strength (darkness) of the shroud?
Possibly via a Trait on Shroud,
I find that being able to see through it to some degree to read the terrain removes some of the fun and makes maps look really poor when you cannot see the civilian buildings and ruins.
Being able to make a dead end to trick a player in a mission using Untroversable Terrain is also not possible.

**Comment by MunWolf** [comment]
I think you are misunderstanding shroud for fog of war, shroud is solid (non see through).

**Comment by Master0r0** [comment]
Ah I see, apologies this seems to be an issue with the old engine version the RA2 mod is currently utilizing and I just thought I remembered seeing through the shroud on the newer versions
