### ISSUE TITLE
Map editor crashes - if items assigned to players without spawns 

### ISSUE THREAD

**Issue by Dieter122** [OpenRA/OpenRA#14924]
In the map editor...

Place 8 player spawns...

Place units/buildings/etc that are assigned to “multi0,1,2,3” etc...  

If you delete spawns and there are items on the map that can’t have a player assigned to them due to too few spawn points... it crashes to desktop.

Kind of an annoying bug.  If you make a map and want to move spawn points but alrdy assigned owners to items placed on the map... it’ll just crash if you delete spawns and goto place new ones.

**Comment by TamasKiss** [comment]
I would like to work on this. Seems like a good issue to pick up the map editor!

**Comment by abcdefg30** [comment]
Sure, go ahead. 👍
