### ISSUE TITLE
Potential bug in RemoveInfluenceInner function

### ISSUE THREAD

**Issue by tomsoftware** [OpenRA/OpenRA#14939]
Hi,

not sure if this is a problem but the function ActorMap.RemoveInfluenceInner() does not check the next node after a node that fulfils the toRemove condition.

https://github.com/OpenRA/OpenRA/blob/08ad7d7f4e1548f603c88b787abd5b5e8fa03f49/OpenRA.Mods.Common/Traits/World/ActorMap.cs#L387

- so if influenceNode.Actor is toRemove -> influenceNode is set to Next
- RemoveInfluenceInner now will check the Next.Next node.

so may

		static void RemoveInfluenceInner(ref InfluenceNode influenceNode, Actor toRemove)
		{
			if (influenceNode == null)
				return;

			RemoveInfluenceInner(ref influenceNode.Next, toRemove);

			if (influenceNode.Actor == toRemove)
				influenceNode = influenceNode.Next;
		}

is better?

**Comment by abcdefg30** [comment]
Hm, that looks indeed fishy, nice find! Did you investigate any further in the meantime?

**Comment by tomsoftware** [comment]
no, only this, just stumbled over this!
-> But I'm not 100% sure if the fix is ok and also may the old version is more faster cause there should be no Actor twice?
-> may we can break the recursion after finding the first match?
