### ISSUE TITLE
Red Alert: Starting cache 0$ needed

### ISSUE THREAD

**Issue by szg0000** [OpenRA/OpenRA#14937]
There is a gamestyle called "crates". For this gamestyle need an option to set the starting cache to 0$.

**Comment by CatGirls420-NerevarII** [comment]
Isn't that option already available? If not, you can add this to "rules.yaml" for a map:

Player:
	PlayerResources:
		SelectableCash: 0, 2500, 5000, 10000, 20000

**Comment by pchote** [comment]
Closing as per the discussion in #15029.
