### ISSUE TITLE
OpenGL driver lost connection (NVIDIA)

### ISSUE THREAD

**Issue by Gornemant** [OpenRA/OpenRA#14952]
### Issue Summary

Hi, I've recently installed the latest release and I'm adding this issue after asking for help on the IRC channel.

After launching RedAlert.exe, the game crashes after a few seconds on the menu screen (with the battle going on in the background) with the following error (The NVIDIA OpenGL driver lost connection with the display driver due to exceeding the Windows Time-Out limit and is unable to continue):
![openglerror](https://user-images.githubusercontent.com/37538849/37598580-e3e5263c-2b82-11e8-8764-e75dcef011fb.png)
Given that no actual game was started, there is no exception.log and the graphics.log is empty.
The issue is also present in TiberianDawn.exe after playing the first mission and starting the second.

I have already tried several possible fixes before adding this issue, though none helped:
- Application Access was always granted in the antivirus software: Bitdefender2018
- Reinstalling the latest NVIDIA drivers.
- Increase the TDR timer delay as described here: https://docs.microsoft.com/en-gb/windows-hardware/drivers/display/tdr-registry-keys
as well as disabling the detection completely, though this resulted in a system wide freeze which required a hard reset of the machine.
- Set the Global Power Management Mode setting in the NVIDIA control panel to "Prefer maximum performance".
- Reinstalled openra from scratch, uninstalled, deleted the game folder and the one in documents library, installed only the requested files without music and cd contents.
- Turned the resolution down to 1280,720, tried windowed mode.
- Tested the drivers with GpuTest and various OpenGL versions, no problems there nor with any other games on the system. http://www.geeks3d.com/gputest/

This led me to believe that the issue is in fact software related. To confirm I installed an older version of OpenRA (OpenRA-release-20131223) and this one worked without problems, including a 50 minutes skirmish against 2 easy AI opponents.

Downloaded and tested the following versions downloading only the required files, uninstalling and deleting all files in between installations:
- OpenRA-playtest-20170722 crashed
[LogsOpenRA-playtest-20170722.zip](https://github.com/OpenRA/OpenRA/files/1825376/LogsOpenRA-playtest-20170722.zip)
Same version TiberianDawn, skirmish against 2 AIs, crash after a few minutes.
[LogsTibDawbOpenRA-playtest-20170722.zip](https://github.com/OpenRA/OpenRA/files/1825424/LogsTibDawbOpenRA-playtest-20170722.zip)
- OpenRA-release-20150614, no crash after several minutes on the menu screen (ongoing battle in the background).
- OpenRA-release-20160508 also no crash after several minutes. Last release to work.
- OpenRA-release-20170421 crashed on the menu screen after a few seconds.
- OpenRA-release-20161019 crashed on the menu screen after about a minute.
- OpenRA-release-20161015 crashed on the menu screen after a few seconds. First release to fail.
- Tried installing latest build on top of already installed 20160508 release, crashed as soon as the exe was started. (fatal error)
- OpenRA-playtest-20160904 crashed on the menu screen. The problem occurs pretty much since the v2 content structure.

#### System Information
- **Operating System:** Windows 7 Pro 64-bit (SP1), DirectX runtime v 11.0
- **GPU:** GeForce GTS 360M, Driver v. 342.01 (last official driver supporting this gpu)
- **.NET / Mono Version:** are listed under HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Updates:  .NET Framework 4.5, 4.5.1, 4.6.1, 4.7.1; Visual C++ 2010 x86/x64 redist 10.0.40219
- **OpenRA Version:** OpenRA-release-20180307
- **Mod:** Red Alert, Tiberian Dawn

- Logs

logs attached for menu screen crash on latest build.
[Logs.zip](https://github.com/OpenRA/OpenRA/files/1825378/Logs.zip)

**Comment by pchote** [comment]
`release-20160508` &rarr; `release-20170421` introduced frame buffers to the rendering pipeline for per-pixel depth checks in TS.  It also forced the switch from .NET 4 to 4.5, but that is probably not related.

**Comment by Gornemant** [comment]
If there's a way to disable frame buffers without too much work on your end I could try that and see if that's the culprit.

**Comment by GraionDilach** [comment]
I did a search on this.

A particular case - which might be our issue as well due to the GLSL refactoring of the depth buffer- came up at https://stackoverflow.com/questions/16639749/glsl-interface-block, however I have to acknowledge that there are many reports of this happening with various games indicating a hardware/driver issue.

**Comment by Gornemant** [comment]
Checked with the Nvidia support, sadly not much help other than trying to limit pre-rendered frames, disable threaded optimization, tripple buffering and V-Sync and checking things out with with the devs.
The drivers mentioned in that issue are a bit older than mine, though the gpu is the same, though drivers stopped releasing for it in 2016. Could it be that the Shader Processor version used since 20170421 is just unsupported by the driver and/or hardware?

**Comment by abcdefg30** [comment]
Closing since there doesn't seem much to do here.
