### ISSUE TITLE
Exception of type `System.UnauthorizedAccessException`

### ISSUE THREAD

**Issue by BertRandolf** [OpenRA/OpenRA#14954]
Hi! When trying to start either Dune200.exe, TiberianDawn.exe or RedAlert.exe the game always crashes and I get this exception all the time.

OpenRA engine version release-20180307
Date: 2018-03-19 20:42:11Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.UnauthorizedAccessException`: Der Zugriff auf den Pfad "C:\Users\\Documents\OpenRA\Logs\perf.log" wurde verweigert.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   bei System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   bei System.IO.StreamWriter..ctor(String path, Boolean append)
   bei System.IO.File.CreateText(String path)
   bei OpenRA.Log.AddChannel(String channelName, String baseFilename)
   bei OpenRA.Game.Initialize(Arguments args)
   bei OpenRA.Game.InitializeAndRun(String[] args)
   bei OpenRA.WindowsLauncher.RunGame(String[] args)

After reading around a bit I learned that this exception seems to come from the folder C:\Users\\Documents\OpenRA\Logs\ being "non-writeable" in Windows. But even if I change this in the folder settings and remove the writing protection and hit OK, the folder remains non-writeable no matter what I do. Needless to say: a perf.log file does not exist in that folder.

Uninstalling, re-installing and manually trying to create a perf.log file did not help.

**Comment by abcdefg30** [comment]
Did you try deleting the Logs or OpenRA folder already? The game should recreate the directory with the correct permissions set then.

**Comment by GraionDilach** [comment]
Users\Documents? Have you edited out your username out from the path yourself during reporting your issue or is it the game skipping your username in the path?

**Comment by BertRandolf** [comment]
The user name has been edited out here for reporting purposes.
And I did try to delete the Logs and OpenRA folders manually but the problem persists.

**Comment by pchote** [comment]
Something is very wrong if your operating system won't let you write to your own documents directory!

Are you running any security software (Norton is particularly bad in this regard)?

**Comment by BertRandolf** [comment]
I am in fact running security software called "BitDefender Internet Security 2018" and this software has, in fact, caused an issue with Dune2000.exe the first time I tried to run it. it blocked the application and considered it malware as it identified several files in the openRA folder as being infected with the thread "Atc4.Detection" including the executable. I have white listed the .exe however as well as all the files identified and reinstalled OpenRA several times since then in the same directory. the problem persists however.

**Comment by Flap-Monster** [comment]
This might seem silly but are you running the .exe as an administrator ? Maybe the file permission exception is coming from the .exe rather than the dest?

**Comment by Smittytron** [comment]
Closing as 3 years old with no follow-up. Also:

> [9:11 AM] pchote: in theory was fixed by moving the support dir to AppData
