### ISSUE TITLE
Rocket Soldiers don't attack air when targeted right away

### ISSUE THREAD

**Issue by CatGirls420-NerevarII** [OpenRA/OpenRA#14957]
This is a fix I implemented in my CG420 map mods ages ago, and would like to see it used in the base game.

The problem with rocket men vs air is that, upon locking on, they delay before shooting at the air units, allowing the air units to travel 2-4 cells in a rocket soldiers range before actually being shot at.

The simple fix was increasing the ScanRange trait by 1-2 cells. Now, they attack the air units immediately upon being spotted/are within firing range.

Here is the latest CG420 map for the current release with the fix, including some other changes (ignore those, being tweaked):

https://resource.openra.net/maps/26325/

**Comment by anjew175** [comment]
This also the case in TD and I believe not just with rocket soldiers. Recon Bikes and Stealth Tanks have trouble hitting a moving target.

**Comment by CatGirls420-NerevarII** [comment]
Yeah endorse the PR here: https://github.com/OpenRA/OpenRA/pull/14960

**Comment by abcdefg30** [comment]
OpenRA has blocked this user from our GitHub organization.
