### ISSUE TITLE
Penalty for team killing

### ISSUE THREAD

**Issue by CatGirls420-NerevarII** [OpenRA/OpenRA#14968]
To prevent trolls from teamkilling, a penalty could be implemented. Maybe an option to turn this feature on or off. Maybe cash could be subtracted for each hit/damage dealt/units-or-buildings-lost. Maybe the attacking unit could be auto-killed by the game. Maybe a strike system, where after 3 strikes, the player is auto-kicked from the game.

Idk, there's a lot of ways to go about this.

**Comment by ChrisJDye** [comment]
For completeness, another possibility would be to add an option to turn off friendly fire for team unit (but not for the player's). I imagine it could be abused in some ways but I wanted to mention it anyhow.

**Comment by CatGirls420-NerevarII** [comment]
I was thinking the same thing, but sometimes it's necessary to teamkill, like, a soldier blocking a cell for perfect ref placement, and the player for some reason fails to move that soldier, instead of placing the refinery 10 cells away, just shoot the soldier. A calculated loss. Worth it, since you would get the ore much quicker :p

**Comment by pchote** [comment]
The bigger problem in both cases is with AoE damage.  Consider demo trucks as an example: If teamkilling is penalized then it would make them even more risky to use.  If teamkilling was prevented then it would make them massively OP in team games.

**Comment by ChrisJDye** [comment]
Perhaps some kind of vote-kick system would suffice. It would require the other people in the game to *not* be scumbags but wouldn't have any side effects with gameplay.

**Comment by CatGirls420-NerevarII** [comment]
Good points. I guess no matter the solution, there's pro's and con's. As expected, but I was hopeful to discover a fullproof solution,l or maybe someone else could.

Votekicking seems the best candidate so far.

**Comment by netnazgul** [comment]
@ChrisJDye votekicking ingame won't be much different from straight up surrendering as by kicking your teammate you are left with defending against more players.
Votekicking in lobby would be better, but doesn't cover smurf cases, so probably won't be as effective.

Anyway there is some moderation implemented on Abarrat's servers which is already covering this I think.

**Comment by abcdefg30** [comment]
See #3516.

**Comment by abcdefg30** [comment]
OpenRA has blocked this user from our GitHub organization.
