### ISSUE TITLE
Adding Code Of Conduct to the game itself

### ISSUE THREAD

**Issue by CatGirls420-NerevarII** [OpenRA/OpenRA#14966]
Add the code of conduct to the game, which is displayed once, upon starting the game, or upon clicking multiplayer. Maybe it could be displayed every so often, or whatever, and/or adding a button to view it after the initial display of the COC.

This way, it is assured that players read it. You could even go as far as making it unable to proceed until you scroll all the way down, or set a timer for it to disappear, or maybe something more creative.

While I advocate for free spech and freedom of expression....I guess some thing's need rules :p

**Comment by fruestueck** [comment]
It's not assured that a player reads it.

**Comment by Mailaender** [comment]
Servers already have a MOTD file where such rules can be posted: https://github.com/OpenRA/OpenRA/wiki/Dedicated#message-of-the-day

**Comment by abcdefg30** [comment]
OpenRA has blocked this user from our GitHub organization.
