### ISSUE TITLE
[Tiberian Sun] - Bugged offset and turret rotation.

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#14983]
I decided to post some giffs to explain this issue better, on the first case, you can see Holy Masters mammoth turning its turret around, where the offset rise and go down as it turns. The second case is similar to applies to turrets, as you can see, the turret might change position, mostly on the Z axis, as it moves.

This happens mostly on units that dont have a centered body or turret.

I thought the CameraPitch tag on BodyOrientation might be the cause, but I saw no changes when I tested different values between 0 and 120 (85 is the default value)

Any ideas what causes it and how to fix it?

![offset](https://user-images.githubusercontent.com/11763228/37846753-60bbd8d6-2ead-11e8-9c46-6f3b1d980764.gif)
![turret rotation](https://user-images.githubusercontent.com/11763228/37846754-60de3e30-2ead-11e8-9603-70b06dacf355.gif)

**Comment by reaperrr** [comment]
> I thought the CameraPitch tag on BodyOrientation might be the cause, **but I saw no changes when I tested different values** between 0 and 120 (85 is the default value)

That sounds very fishy, especially with regard to the firing offsets (for sprites it might at least partially be caused by the sprites' own internal offsets or position within the canvas).

**Comment by ABrandau** [comment]
Oh yes, you are right, I missed it, the value is overritten later on, but still, this is the value responsible for this problem?

**Comment by reaperrr** [comment]
It should be.

**Comment by ABrandau** [comment]
CameraPitch works, but it only seems to affect voxels, I cannot manage to see any changes on sprite based actors and the turret bug is still there.

**Comment by reaperrr** [comment]
It definitely should affect firing offsets, too.

Note that it's possible that holymasters' sprite mammoth walker needs a slightly different CameraPitch than other actors depending on the camera angle at which it was rendered.
It's also important to make sure the Turreted trait has the correct height offset, because any Armament.LocalOffset is calculated relative to that.

**Comment by ABrandau** [comment]
Yes, I am aware of that issue, but the sprite elevation should not vary with the rotation of the main body, I did some tests with CameraPitch, at most I could increase the elevation of the turret when facing to the top, but I could not remove it.

**Comment by reaperrr** [comment]
I can't spot what's wrong with the disruptor, sorry (assuming you're not talking about the last gif, of course...).

I'd need the shps and yaml to check what's wrong with the mammoth walker.

**Comment by ABrandau** [comment]
Gonna bump this topic because I got another usecase, I started doing my own mammoth variant, see how the missile turrets float on the facings that look at the bottom.
![mammoth](https://user-images.githubusercontent.com/11763228/38155118-35c54e6a-344c-11e8-9e71-622743cca8d7.png)

**Comment by pchote** [comment]
Please link to a test case. From the discussion above it sounds like something isn't being defined right on your end.

**Comment by ABrandau** [comment]
https://github.com/ABrandau/Shattered-Paradise/blob/master/rules/vehicles.yaml#L299

**Comment by ABrandau** [comment]
Solved the issue by implementing CameraPitch: 250 on the bogus units at the first try, thx for your help on the IRC chat.
