### ISSUE TITLE
AA Gun (And SAM Site) can't see as far as it can shoot

### ISSUE THREAD

**Issue by CatGirls420-NerevarII** [OpenRA/OpenRA#14993]
I'll put in a PR if you all want. But this is something that was supposed to be fixed ages ago. It can only see....6 cells I think? While it can fire 10 or more. Sure, you could use a scout unit......but why? That's not good at all. I can understand if it was to balance how overpowered aa guns are......but there's much better ways of going about that.

Before the GPS heavy nerf, GPS would allow it to see farther. But GPS-found units can no longer be auto targeted.

SAM Site suffers this also, but I think it's only 1-2 cells that it cant see compared to its firing range. An already underpowered static anti-air defense with very short range is made even weaker by this. Sure, soviets have flaks, but come on......flaks arent exactly the best option for AA. As seen by the majority of the community, endless times. Sure, it's effective, but can easily be rendered useless if it cant keep a consistent stream of fire, like say, a cliff stopping that.

**Comment by netnazgul** [comment]
I'd assume most units having range longer than vision is a feature of the current gameplay. Changing it will require overhauling the whole stuff as well

**Comment by CatGirls420-NerevarII** [comment]
What would the feature be? Lol seems kind of silly :p

**Comment by MunWolf** [comment]
It does not seem silly though? Artillery / missile units often shoot outside their "vision" range, there are even examples of this in modern RTS games where the siege tank in SC2 can shoot farther then it can see in siege mode.

I really don't see any problem with this other then possibly balance (which is debatable).

**Comment by abcdefg30** [comment]
OpenRA has blocked this user from our GitHub organization.
