### ISSUE TITLE
Tanks able to drive forward and backwards

### ISSUE THREAD

**Issue by ThisBlunt** [OpenRA/OpenRA#15017]
It would be nice if tanks can move both directions not just forward.

**Comment by CatGirls420-NerevarII** [comment]
This would let tanks retreat much easier with the current unit pathing dilemma.

**Comment by TehStex** [comment]
[THIS ?](https://github.com/OpenRA/OpenRA/issues/4968#issuecomment-38682655)

🙄

**Comment by matjaeck** [comment]
Duplicate of the issue referenced above.

**Comment by pchote** [comment]
Closing as duplicate.
