### ISSUE TITLE
Tick tanks can deploy on crossable structure foundation (can block refineries and warfactories)

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#15013]
Not sure if there is a method to correct this, because bib or idle overlays dont change the propeties of the cell, right now the game uses an idle overlay.
![tick tank bug](https://user-images.githubusercontent.com/11763228/38167897-1f122a5c-3515-11e8-95c7-fd32d8a7ec58.gif)

**Comment by ABrandau** [comment]
Making GrantConditionOnDeploy conditional might be a quick fix.

**Comment by Punsho** [comment]
This is not necessarily a bug, more of an interesting clash of mechanics. I suggest leaving it as is. It would still be best to give modders ways of preventing deployment though

**Comment by ABrandau** [comment]
> This is not necessarily a bug, more of an interesting clash of mechanics. I suggest leaving it as is. It would still be best to give modders ways of preventing deployment though

Yeah but the TS mod looks for original game accuracy, and afaik this was not possible in the original game, anyway what I was hoping to get from this was a solution to the problem, its always great to have optional stuff and we got it already, GrantConditionOnDeploy is already conditional, I would suggest closing this issue unless there is another use for it.

**Comment by GraionDilach** [comment]
IIRC bibs still need to define a terraintype to combine that with GrantConditionOnTerrain to call this done.

**Comment by pchote** [comment]
This was fixed by #17141.
