### ISSUE TITLE
Units blocking refinery and Warfactory untargetable.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#15012]
When you block a unit with something that can't be scouted (IE: Stealth tank) You can't force fire at the entrance of the refinery or war factory.

Has not been tested if this also applies in RA.

**Comment by ltem** [comment]
Possible duplicate of #14994?

**Comment by GraionDilach** [comment]
Sounds like it, yes.

**Comment by reaperrr** [comment]
Closing as duplicate then, moved the other issue to milestone.
