### ISSUE TITLE
Pathfinding fails when ordered units block each other while moving

### ISSUE THREAD

**Issue by lawando** [OpenRA/OpenRA#15039]
When you order units to move somewhere and they block each other on their way, the blocked unit will stop moving. This happens to infantry units and vehicles. See the linked GIF. One would expect that the blocked unit found a way around the unit blocking it - which is the case if a not moving unit is in their way - but they just stop at the point where they have been blocked. 
https://imgur.com/a/EEyE3

**Comment by CatGirls420-NerevarII** [comment]
Yeah this has been an issue for a while and they're all aware of it. I was going to try fixing it but it's too time consuming.

**Comment by lawando** [comment]
@CatGirls420-NerevarII Is there already an issue that describes this specific behavior? Please reference it if so, I could not find one.

**Comment by CatGirls420-NerevarII** [comment]
It's okay man. I'm not good at searching github either :p
