### ISSUE TITLE
video is blinking

### ISSUE THREAD

**Issue by YZemskov** [OpenRA/OpenRA#15046]
### Issue Summary

Video in fulscreen mode is blinking.

#### System Information
- **Operating System:** Win 7 x64
- **.NET / Mono Version:** .NET 4.7.1
- **OpenRA Version:** release-20180307

#### Additional Information:
- Steps to reproduce
	just run

- Logs
log files is empty

- Screenshots & Videos

https://www.dropbox.com/s/3c4qa5482q47xqh/VID_20180412_164115.3gp?dl=0

**Comment by abcdefg30** [comment]
> Video in fulscreen mode is blinking.

Does the game still flicker when you are in windowed mode?

**Comment by YZemskov** [comment]
> Does the game still flicker when you are in windowed mode?

No

**Comment by abcdefg30** [comment]
Hm, I'd try to update your graphic card's drivers (or downgrade them temporarily, newer NVIDIA drivers caused me some trouble in the past).

**Comment by YZemskov** [comment]
I was have a 179.19 NVIDIA drivers, and i was update it to 179.48 (latest version). Update did not help, and game still flicker. I can not found any earlier version's NVIDIA drivers. Can anybody help me downgrade drivers? It help OpenRA with this bug!

**Comment by abcdefg30** [comment]
Sorry for the late response. That is what NVIDIA suggests for downgrading drivers: https://www.nvidia.com/object/driver_rollback.html

**Comment by abcdefg30** [comment]
This issue is 4 years old and without activity, closing.
