### ISSUE TITLE
OpenRA don't work

### ISSUE THREAD

**Issue by YZemskov** [OpenRA/OpenRA#15044]
### Issue Summary

OpenRA don't work

#### System Information
Win7 x64

#### Additional Information:
Just run OpenRA

- Logs
OpenRA engine version release-20180307
Date: 2018-04-11 16:10:34Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.1
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
   at OpenRA.Game.Initialize(Arguments args)
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at OpenRA.Game.Initialize(Arguments args)

**Comment by TehStex** [comment]
Do you have `graphics.log` ?
Otherwise it can be https://github.com/OpenRA/OpenRA/issues/12313#issuecomment-372769697, as you have almost the same Windows and .Net versions and the exact same `InvalidOperationException`.

**Comment by reaperrr** [comment]
> Runtime Version: .NET CLR 4.0.30319.**1**

@YZemskov The `1` strongly indicates that you only have .NET 4.0 without any updates. OpenRA requires at least .NET 4.5.

Yyou can get 4.5.2 at https://www.microsoft.com/net/download/dotnet-framework-runtime/net452

**Comment by YZemskov** [comment]
Thak you, reaperrr. OpenRA starting, but i have other problems with video. I open a new thread.
