### ISSUE TITLE
TargetDamageWarhead can't deal damage without TargetActorCenter: true

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#15053]
I wanted to use TargetDamageWarhead for weapons with PrimaryDamageRadius of 0 in original Generals in my Generals Alpha mod, and furter testing showed me that TargetActorCenter: true is required. Not much of a problem for Heal weapons we use in TS as it is only against units which only target point is actor center. But i need to use it on stuff like MG weapons which can attack buildings.

To test remove TargetActorCenter: true from TS Heal weapon and try using the medic.

**Comment by reaperrr** [comment]
#14991 should fix that.

**Comment by reaperrr** [comment]
This should be solved now, @MustaphaTR can you re-check?

**Comment by pchote** [comment]
Lets close it instead. @MustaphaTR please reopen if this actually wasn't fixed.
