### ISSUE TITLE
Vehicles in a 3x3 shape with an empty square in the middle - can't navigate

### ISSUE THREAD

**Issue by drogoganor** [OpenRA/OpenRA#15054]
### Issue Summary
If you form vehicles in this shape:

![3x3units](https://user-images.githubusercontent.com/1639681/38767172-65520170-4020-11e8-928b-fcb2a50d9b6d.png)

And then try to move a unit to the center, it doesn't move.

#### System Information
- **Operating System:** Windows 10
- **.NET / Mono Version:** NET 4.7.1
- **OpenRA Version:** bleed
- **Mod:** RA

#### Additional Information:
- Steps to reproduce
	1. Form 8 vehicles in a 3x3 shape with the middle empty
	2. Move any vehicle to center

**Comment by abcdefg30** [comment]
Looks like the same as #6989.

**Comment by drogoganor** [comment]
This one must be wreaking havoc with pathfinding.
