### ISSUE TITLE
Aircraft pause rearming when given a stop order

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#15055]
Aircraft that are in the process of refilling their ammunition will pause rearming if they are given a stop order using the stop hotkey. 

This is counterintuitive considering that you can send Yaks to rearm with the stop hotkey. 

If there is only one Airfield and a player has multiple Yaks in one control group 

- with one being in the process of refilling ammunition 

- and the other Yaks being in the air without any ammunition left,

using the stop hotkey on the whole control group to rearm all of them will pause rearming of the Yak that is landed on the Airfield and thus block the Airfield for the other Yaks which will circle around the blocked Airfield infinitely.

Rearming of helicopters is paused too which will block the helipad for other helicopters when the RTB to rearm.

One would assume that the stop hotkey had no effect on refilling ammunition.

If stop should send them to rearm is discussed at #12487.

**Comment by BGluth** [comment]
For coming up with a solution to this, is it ok to make the assumption that the correct behavior is to continue rearming when given a stop order? Would there ever be a mod that would not want this?

**Comment by abcdefg30** [comment]
RA players have argued in the past that they want to have helicopters stay on the ground in order to allow mechanics to repair them. (However, I don't know if repairing aircraft using mechanics is still possible.)

**Comment by BGluth** [comment]
From the discussion in #12487, it sounds like using the deploy key (F) to send them back to rearm is the intended way over using the stop key (S), but I feel like issuing a stop order shouldn't stop the rearming processes (unless maybe there's a mod where it costs money to rearm or something?). Maybe issuing a stop order would not stop rearming but prevent them from automatically taking off if that's what's wanted?

**Comment by pchote** [comment]
"players like this bug" is a poor argument against fixing inarguably broken code.  Fix the bug first, then look at ways that the desired behaviour can be brought back properly.

**Comment by avalach21** [comment]
i think it would make sense to have a separate return to base hotkey , or a modifier for a secondary "deploy" function.  Also, is it currently possible to have rearming ammo have an associated cost?

**Comment by pchote** [comment]
@avalach21: could you create a separate issue for that?  The original D2K had this feature as a "retreat" button in the sidebar.  We could put it as its own button in the commandbar.

**Comment by MustaphaTR** [comment]
We already have an issue for Retreat.

**Comment by matjaeck** [comment]
Should be fixed by the merged pr referenced above.

**Comment by reaperrr** [comment]
While #15363 was an acceptable work-around for the existing code, it causes more problems than it solves for #16241, and at the end of the day it was still a hack. We need to come up with a more robust and less hacky solution, like ignoring "Stop" orders while the activities in question are running.

**Comment by reaperrr** [comment]
Fixed by #16241.
