### ISSUE TITLE
Aircraft with both infinite and finite ammo weapons should not RTB when AmmoPool empty

### ISSUE THREAD

**Issue by Smittytron** [OpenRA/OpenRA#15063]
I've been looking at adding a chaingun to the longbow that has infinite ammo in addition to its limited-ammo missiles. The aircraft will attempt to RTB when out of missiles, despite still having a functioning weapon. It will also refuse new attack orders vs valid targets until loaded.

Aircraft with multiple weapons shouldn't RTB if one weapon is still operable.

**Comment by ABrandau** [comment]
I believe a better option here would be to split the RTB code from aircraft and make it conditional, that way each modder can decide what to do on each scenario.

**Comment by pchote** [comment]
This should already be possible.  There are some subtle details to be careful of in the yaml definitions, so I strongly suspect that this is just an oversight in your yaml.  Can you please post your definitions here?

**Comment by Smittytron** [comment]
```
Armament@PRIMARY:
	Weapon: 30mm
	MuzzleSequence: muzzle
Armament@SECONDARY:
	Name: secondary
	Weapon: Hellfire
	LocalOffset: 0,213,-85, 0,-213,-85
	PauseOnCondition: !ammo
AmmoPool:
	Armaments: secondary
```
Combined HellfireAG and HellfireAA into one weapon for this. Is Armament@TERTIARY a thing if we want to keep them separate?

**Comment by Smittytron** [comment]
OK, must have been a rule overlay thing. Got it to work in dev mode.
