### ISSUE TITLE
Hinds/Longbows will continue the landing animation even after helipad is destroyed

### ISSUE THREAD

**Issue by BlackenedRA** [OpenRA/OpenRA#15060]
This allows ground units to attack the idle helicopters when they should return to the air.

**Comment by abcdefg30** [comment]
Something must have regressed #11620.

**Comment by matjaeck** [comment]
> Something must have regressed #11620.

Helicopters still take off if they are landed and you sell the helipad under them. However, they will not cancel the landing activity when the helipad is sold while they are approaching it.

**Comment by tovl** [comment]
This appears fixed in bleed.
