### ISSUE TITLE
Almost works on OpenBSD

### ISSUE THREAD

**Issue by vext01** [OpenRA/OpenRA#15070]
### Issue Summary

Make it work on OpenBSD.

#### System Information
- **Operating System:**  OpenBSD-current
- **.NET / Mono Version:** Mono 5.10.0.160
- **OpenRA Version:** bleed
- **Mod:** Ra

#### Additional Information:

After fiddling with some dll maps I got the game to launch to the main menu. However, the assets failed to download with "DNS lookup failed". I managed to get around that by manually installing the assets.

Now I'm at the main menu. I can select "single player->skirmish", but this bombs out with
"Can't connect to 127.0.0.1:...".

Looking at the console I see:
> System.Net.Sockets.SocketOptionName 0x17 is not supported at IP level

I speculate this is why no network related stuff is working.

You guys have seen this before here:
https://github.com/OpenRA/OpenRA/issues/13674

I saw beaconlib was doing:
```
udp.Client.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.ReuseAddress, true);
```

Installed a patched BeaconLib setting these to false. No joy.

Nothing unusual in the logs.

If I can get this to work, I'd like to make an OpenBSD package :)

Any ideas?

**Comment by abcdefg30** [comment]
https://github.com/OpenRA/OpenRA/issues/15004#issuecomment-376834326 worked on Fedora, maybe you have a similar issue.

**Comment by vext01** [comment]
Hrm, so I think this would look like this on OpenBSD:
```
arrakis:edd> doas cert-sync /etc/ssl/cert.pem 
doas (edd@arrakis.home) password: 
Mono Certificate Store Sync - version 5.10.0.160
Populate Mono certificate store from a concatenated list of certificates.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

Importing into legacy system store:
I already trust 0, your new list has 133
Certificate added: C=ES, CN=Autoridad de Certificacion Firmaprofesional CIF A62634068
Certificate added: C=EU, L=Madrid (see current address at www.camerfirma.com/address), OID.2.5.4.5=A82743287, O=AC Camerfirma S.A., CN=Chambers of Commerce Root - 2008
Certificate added: C=EU, L=Madrid (see current address at www.camerfirma.com/address), OID.2.5.4.5=A82743287, O=AC Camerfirma S.A., CN=Global Chambersign Root - 2008
Certificate added: CN=ACCVRAIZ1, OU=PKIACCV, O=ACCV, C=ES
Certificate added: C=IT, L=Milan, O=Actalis S.p.A./03358520967, CN=Actalis Authentication Root CA
...
Certificate added: C=CH, O=WISeKey, OU=OISTE Foundation Endorsed, CN=OISTE WISeKey Global Root GB CA
Certificate added: C=US, OU=www.xrampsecurity.com, O=XRamp Security Services Inc, CN=XRamp Global Certification Authority
133 new root certificates were added to your trust store.
Import process completed.
```

However, this doesn't seem to help.

**Comment by pchote** [comment]
The SocketOptionName warning is benign: it is related to the LAN game broadcasting, and occurs on all mono platforms. and doesn't affect functionality.

**Comment by vext01** [comment]
I see. So for some reason it looks like socket operations don't work. Any other ideas?

**Comment by pchote** [comment]
Are you sure that you don't have any sandboxing or firewall configurations active that might prevent intra-app connections? OpenRA's singleplayer works by spinning up a local server on a thread and then connecting to it over a local port.

**Comment by vext01** [comment]
I've just tried disabling the firewall altogether with the same result.

Trying ktrace...

**Comment by vext01** [comment]
Perhaps one of the developers could take a look in a OpenBSD VM?

To get it running:
 * Use `gmake` not `make`.
 * Add lines to map the right dll versions:
```
arrakis:OpenRA> grep openbsd *
Eluant.dll.config:  <dllmap os="openbsd" dll="lua51.dll" target="/usr/local/lib/liblua5.1.so.5.1" />
OpenAL-CS.dll.config:    <dllmap dll="soft_oal.dll" os="openbsd" target="/usr/local/lib/libopenal.so.3.0" />
SharpFont.dll.config:    <dllmap dll="freetype6" os="openbsd" target="/usr/X11R6/lib/libfreetype.so.28.2" />
```
 * Use `bash` not `sh` for `launch-game.sh`.

**Comment by rfht** [comment]
This issue is being fixed in mono (https://github.com/mono/mono/pull/13633) and has been fixed in OpenBSD -current (https://marc.info/?l=openbsd-ports-cvs&m=155351914829916&w=2). A working OpenRA port for OpenBSD is circulating on OpenBSD mailing lists and will likely be imported soon.

**Comment by abcdefg30** [comment]
Good to hear, closing as fixed then.

**Comment by pchote** [comment]
Is this actually fixed though? It sounds like we still need to update our .config files to add the openbsd target.

**Comment by rfht** [comment]
I'd treat the `.dll.config` and `launch-game.sh` (if needed) in a separate issue/PR. Will link below in this thread.

**Comment by rfht** [comment]
The PR for adding to Eluant's `.dll.config` is here: https://github.com/OpenRA/OpenRA/pull/16361

**Comment by rfht** [comment]
For the thirdparty modules:
https://github.com/OpenRA/OpenAL-CS/pull/2
https://github.com/OpenRA/SharpFont/pull/1
https://github.com/OpenRA/SDL2-CS/pull/2

... sorry for the initially missed and then removed `.orig` files
