### ISSUE TITLE
The capture-related-logics lack proper multiple-instance support.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#15076]
From #15072.

>While `Captures` is conditional, there are several places where the game will crash if you try to implement multiple versions with different types. There are a bunch of subtle issues involved in fixing that, which are well beyond the scope of this PR.

**Comment by pchote** [comment]
Reopening - we are still using `TraitInfoOrDefault` for `CapturesInfo` and `CapturableInfo`.
