### ISSUE TITLE
[Request] - Conditional WithRangeCircle

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#15087]
Didnt notice this wasnt conditional yet, it would be very useful for modding.

**Comment by MustaphaTR** [comment]
I already have it Conditional in Generals Alpha engine. Shouldn't be hard to port to upstream. I was just unsure what we want to do with ones shown during building placement. On my engine, it only shows ones enabled by default.

**Comment by pchote** [comment]
This has been conditional for some time now.
