### ISSUE TITLE
Refresh chrome key is missing

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#15093]
Refresh chrome is missing from the options why is that?
I was doing some edits to my mod menu and I wanted to test in game the changes while I was editing the png file without restarting the game every time, so I used ctrl+r by memory and that din't work, then I checked the options for the "refresh chrome" key and the option was missing. I also tested cnc mod just to be sure and it was missing from there too. So I presume some one removed it for some reason. Any one know how to re enable it? or the code is gone for ever and ever and I have to restart the game like 10000 times for each test? XD

**Comment by abcdefg30** [comment]
They were removed in #13974:
> [This] removes the `DevReloadChrome` and `HideUserInterface` hotkeys.  These latter two are hacks that don't (and shouldn't!) work from mod code, so they can't easily be made to work with the new system.
