### ISSUE TITLE
Dedicated Server Crash during 4v4 game

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#15099]
### Issue Summary
Server crash during game, unexplained, see attached gist

#### System Information
- **Operating System:** Debian 8
- **.NET / Mono Version:** Mono 5.8
- **OpenRA Version:** release-20180307
- **Mod:** ra

- Logs
https://gist.github.com/oraservers/08b3d77356f553a9fc1792071233ab3b

- OpenRA Replays

[Uploading OpenRA-2018-05-01T042058Z.zip…]()

**Comment by pchote** [comment]
`InterpretCommand` is a monster of a function with a bunch of dictionary lookups.  Unfortunately the log doesn't tell us anything about which may be causing this, and the replay didn't upload.

**Comment by obrakmann** [comment]
The logs are 404 and the replay is missing as well. Nothing that can be done here, unfortunately.
