### ISSUE TITLE
remove cloak detection from mamoths

### ISSUE THREAD

**Issue by shpookys** [OpenRA/OpenRA#15100]
![screenshot_1](https://user-images.githubusercontent.com/16250856/39465054-0e23f634-4cd6-11e8-9bb9-ba1e560fdaf4.png)

the mammoth tank already serves the role of mobile AA and counters infantry and other tanks it does not need to have cloak detection

**Comment by shpookys** [comment]
also the phase transport was never re-purposed so there is no point in them having cloak detection any longer.

**Comment by pchote** [comment]
For reference, this was introduced in #13790 and first shipped in release-20180218.

**Comment by abcdefg30** [comment]
Ping @Smittytron.

**Comment by Smittytron** [comment]
@SoScared What was your plan with the phase transport?

**Comment by abcdefg30** [comment]
This was fixed by #16803.
