### ISSUE TITLE
Urgent test issues about how to set up a map in a test 

### ISSUE THREAD

**Issue by firebrain7** [OpenRA/OpenRA#15110]
Urgent issues:
I want to test the code of map module in Visual Studio 2015.However, I find that I have to pass a parameter which called Uid to set up a map.In detailed, I need to use a Action called onSelect to do it.
But I wonder when to call this action in the game code? or how to set the Uid in my test code .

Thanks a lot.

System Information
Operating System: WIndows 10
NET Version: 4.5
OpenRA Version: OpenRA-release-20180307
Tools: VS 2015

![question about uid](https://user-images.githubusercontent.com/16367644/39594410-3a173b46-4f3f-11e8-948a-e42ae677b080.png)

**Comment by GraionDilach** [comment]
You shouldn't hack the game to lauch into a map directly. Why don't you just run the appropriate launcher/OpenRA.Game.exe with the appropriate Game.Mod argument with an attached debugger?

**Comment by firebrain7** [comment]
@GraionDilach 
Because I need to do the unit test(like the screenshot below. Is there any other ways?
Thank you a lot.
![question about uid](https://user-images.githubusercontent.com/16367644/39610631-4f4ee3d4-4f84-11e8-9a3f-bc1e974c8fac.png)
![snipaste_2018-05-04_10-16-22](https://user-images.githubusercontent.com/16367644/39610633-511d8ab2-4f84-11e8-9659-173b96cfce0d.png)

**Comment by abcdefg30** [comment]
There is a launch parameter for starting a map.
