### ISSUE TITLE
Artillery Rebalanced

### ISSUE THREAD

**Issue by CatGirls420-NerevarII** [OpenRA/OpenRA#15117]
I'd like to get the stuff I've already tested out of the way. The current balance team is essentially doing everything I already did in terms of making balance changes and testing them. (just an observation of something that is slowing the progression and development of this game, not sure how this got interpreted as something bad, maybe if you heard how I said it....)

(no malice here, just stating an observation that is slowing the progression and development of the game) A lot of time is being wasted doing what I've already done. I've tested my changes in hundreds of matches with great feedback. The only negative opinions I get are from trolls or people who need an excuse for why they suck at the game.

So, first up, ARTILLERY.

These values allow the artillery to remain effective, but not overpowered. Instead of 3 arty destroying a huge infantry blob, you'll 4-6 of them.
Damage vs vehicles has been buffed slightly to compensate for lack of infantry killing.
A direct hit will kill the infantry, but if it lands off to the side, it can take anywhere from 1-4 shots. With a small group of artillery firing, the aoe will make it a lot more effective.

Cost also went up, and it's speed has been slowed down. I think I buffed it bs buildings too, maybe not.

vehicles.yaml:

ARTY:
	Mobile:
		TurnSpeed: 2
		Speed: 60
	RevealsShroud:
		Range: 8c0
		RevealGeneratedShroud: False
	RevealsShroud@GAPGEN:
		Range: 4c0
	Passenger:
		Weight: 4

----------

ballistics.yaml:

^Artillery:
	Range: 12c0
	Projectile: Bullet
		Speed: 200
		Blockable: false
		LaunchAngle: 110
		Inaccuracy: 1c256
	Warhead@1Dam: SpreadDamage
        Spread: 420
		Versus:
			None: 40
			Light: 60
			Heavy: 35
			Concrete: 50

155mm:
	MinRange: 4c0

**Comment by FiveAces** [comment]
Look, if you want to be taken seriously, phrases like " The only negative opinions I get are from trolls or people who need an excuse for why they suck at the game" have absolutely no place in a PR. Trying to label anyone who disagrees with you a troll is a completely pointless ad hominem and serves no purpose other than to start a flame war. 

Regarding your proposed changes, I strongly disagree. The current Allies playstyle tends to be drawing out into a stalemate by T2, but your solution would only amplify this issue: Right now, Artilleries are the best recourse Allies have against mass infantry. Sure, Hinds are great at crowd control, but add in anything that gives enemy rocket soldiers line of sight and your helicopters can't engage any more. That leaves us with the only other Allied counter to mass infantry: Mass pillboxes. In short, nerfing the best infantry killer Allies have (while simultaneously improving its anti-vehicle capabilities for no reason whatsoever) is going to promote an even more static playstyle.

**Comment by CatGirls420-NerevarII** [comment]
Thank you for replying! :)

But man :/ I really wish people would stop assuming thing's, talking about wrong assumptions and having to explain it is a huge waste of time, for everybody.

The reason I used troll, is because the negative feedback, isn't anything intelligent. There have been people who didn't like my changes, and gave negative feedback, and I accepted it. Why? What's the difference? Well, they were nice and professional about it, and used "constructive criticism."

The majority of negative feedback, however, was from people who were rude, dishonest, ignorant, and insulting, and without saying names, I know for a fact some of these people gave negative feedback for the simple reason of not liking me.

As for starting a flame war, well, my intention was to clarify where exactly all this alleged negative feedback comes from.

Ok, next....

See, you're already starting off on a good foot, presenting yourself in the proper manner, unlike them. I hear what you're saying, I'm just curious what lead you to believe this would draw out T2 stalemates? Maybe I missed something? I'm asking because through all the tests I've done and the feedback I've gotten ingame from many people, this doesn't seem to hold true. However, if you can shed light on something I missed, maybe I can rework this to have a more beneficial impact.

I get that arty is the best anti-infantry for allies, but the changes I implemented allow artillery to remain effective, but not make the enemy suffer substantially larger looses than the cost of 3 artillery.

My changes change it from 3 required arty, to 4-6 required arty, with 4 being the requirement if you're good at arty micro/arty force fire, and can predict where to land shots so they hit. All while making arty more vulnerable in it's stats so an arty spam is easier to beat, and you don't incur heavy losses.

As for hinds, I've set mine to have a longer range than rocket men, and ran into no issues, so setting the range to the same as rocket men, or even.....idk how to translate this.....basically, if rocket men have a range of 4c0, then give hinds a range of 4c128, so the hinds can at least get some shots off before dying.

As for other options, I've given a very slight boost to the ranger against infantry, and repurposed the light tank to be anti-infantry, like an IFV. Let's face it, once you get medium tanks, you're never going to build light tanks again, because they are pretty useless, unless you manage to pull off an early game rush.

If you disagree, please, show me the light, because, nobody's perfect, I probably missed something.

But a lot of people agree on the uselessness of LT's, and even "people who matter" like competitve players, IIRC, Happy was one.

Now see, buffing arty vs vehicles, I wouldn't just blow off as "for no reason whatsoever". Allied armor can't compete with soviet armor. 1 Heavy Tank at 1150, beats 2 medium tanks at 1700 (850x2). I was told that HT to MT was balanced based on the health/cost ratio, which is fine, but also not fine, because it doesn't address the issue of the large DPS difference between MT and HT, which is why 1 HT beats 2 MT.

So there's many routes to take at this point, but what I went with is a slight buff to allied armor, while granting a nice bonus to arty to make up for it's loss of anti-infantry (which, with my changes, is still actually pretty effective).

"is going to promote a more static playstyle." See, idk, I've never run into that issue.

In fact, all of my changes together, provide a more dynamic and intense playstyle.

I mean, what I've said here in my comment, is based off of hundreds of matches and playtests with my changes, observing what goes on, coupled with the large amount of positive feedback I've received.

Don't worry, I'm not coming at you, I'm just wondering where you get your info from and what basis you have to make these assumptions. Like I said, it's possible that i may have missed something, but the results I've gotten are pretty convincing.

I hope to hear back from you soon :)

**Comment by abcdefg30** [comment]
OpenRA has blocked this user from our GitHub organization.
