### ISSUE TITLE
Differentiate Singleplayer replays and Multiplayer replays

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#15135]
I was going to start this issue by asking you guys to add a button at the end of each game asking the player to save a replay or not, with the goal of ease the search of useful replays.

I regret that idea because the change might require the opinion of the whole community, so I would rather go for this, could you add in the replay name the type of game the player is going through? wether its multiplayer or single player skirmish? (something small like SP or MP)

Right now its an agony having to search for the right replay, because every single quick skirmish test game is also there, and there is no way to differentiate them, dont forget that devs and modders must do these tests many times to ensure the game work as expected.

**Comment by lawando** [comment]
Would support a feature that asked the player if a replay should be saved. A way to handle this than requesting another user command after a player clicked "Leave" (annoying, how to treat disconnects?) would be the implementation of a battle debriefing like in old CnC titles. Game statistics are already there and somewhere stored in the replay file I assume so this should be possible to do. You could then add the functionality for saving and renaming replays to this battle debriefing screen.

I found this picture of an original RA mission debriefing screen:
http://www.mobygames.com/images/shots/l/6462-command-conquer-red-alert-windows-screenshot-mission-statistics.gif

For the moment, a feature like @ABrandau suggested which intends to make the replay file names more meaningful could use the mapname and the "gametype", like "Sidestep_180512_MP" and could be reused as a default name in a battle debriefing screen's replay options section.
