### ISSUE TITLE
Which Mono version is required? Wiki/website mismatch

### ISSUE THREAD

**Issue by aaronfranke** [OpenRA/OpenRA#15151]
https://github.com/OpenRA/OpenRA/wiki/Installation

> .NET Framework 4.5 (or Mono >= 3.2)

https://www.openra.net/download/ (Mac section)

> OpenRA requires Mono 4.6 or greater.

https://www.openra.net/download/ (Ubuntu section)

> OpenRA requires Mono 4.2 or greater.

These sources all specify different versions. Please change each to the correct minimum version that OpenRA supports.

**Comment by pchote** [comment]
The website is correct.  Mono 4.6 is required for macOS because it includes important macOS-specific fixes, but we make do with 4.2 on Linux because many distros do not ship anything newer.  I updated the wiki page.

**Comment by aaronfranke** [comment]
Just FYI, Ubuntu 18.04 ships Mono 4.6.2.7.
