### ISSUE TITLE
Veterancy change proposal

### ISSUE THREAD

**Issue by ZxGanon** [OpenRA/OpenRA#15164]
Hello guys,

my name is ZxGanon and I am the Gameplay Designer and Community Manager of Shattered Paradise, currently, I am helping OpenRA balance and gameplay with Orb’s Allies Overhaul and the recent Playtests of TD, I also make balance maps from time to time, host tournaments, and I am the current champion of TD through TDGL. 

The reason for this proposal is the lack of information behind each veterancy level, where the bonus progression of each level is not constant, and also the high amount of experience required to gain veterancy is so high, that units are not seeing much.

This proposal aims to solve these two goals, first it streamlines the bonuses obtained for every level (each one gives you the same amount), and also reduces the amount of experience required, the final part that we are still working on is the health regeneration, which is currently very low, and doesn't add much survivability on mods where units die from one or two hits.

Current Veterancy:
1 Chevron: (achieved after killing 200% of the units worth)
+5% Durability
+5% Attack damage
+5% Attack speed
+5% Movement speed
+10% accuracy
2 Chevron: (achieved after killing 400% of the units worth)
+5% Durability
+5% Attack damage
+5% Attack speed
+5% Movement speed
+10% accuracy
3 Chevron: (achieved after killing 800% of the units worth)
+5% Durability
10% Attack damage
+5% Attack speed
+10% Movement speed
+10% accuracy
Platinum Star: (achieved after killing 1600% of the units worth)
Unit gains self healing to 100%
200 hp healing each 3 seconds.
5 second damage cooldown.
+10% Durability
+10% Attack damage
+10% Attack speed
+10% Movement speed
+20% accuracy

New Veterancy:
1 Chevron: (achieved after killing 300% of the units worth)
+10% Durability
+10% Attack damage
+10% Attack speed
+10% Movement speed
2 Chevron: (achieved after killing 600% of the units worth)
+10% Durability
+10% Attack damage
+10% Attack speed
+10% Movement speed
Star (Heroic): (achieved after killing 900% of the units worth)
Unit gains self healing to 100%
1% hp healing every 3 seconds
5 second damage cooldown
+10% Durability
+10% Attack damage
+10% Attack speed
+10% Movement speed

Ranks:
Veteran (3 times unit worth)
Elite (6 times unit worth)
Heroic (9 times unit worth)
Removed Chevron 3 and made the Star the new Rank 3 (Heroic)

Each level will give you
+10% Durability
+10% Attack damage
+10% Attack speed
+10% Movement speed

which means 20% extra dps per level (as both damage and attack speed are increased in the same amount)

We removed the Accuracy bonus on each level because only Artillery was benefitting from that. On one hand, it's not something you can convert into hard data easily (like damage per second), so beginners have a harder time understanding it, and second, as far as I know, modern CnC games do not apply these bonuses. Also like mentioned above this bonus only benefitted artillery which gives more emphasis at the artillery based gameplay we all know.

Finally, the health regeneration needs some thought, because the fixed amount means low hp units get more benefit from this than high hp units, as the total amount of health they have is not considering, this generates an inconsistency where a high health unit that is veteran will never get healed while low tier veteran riflemen heal very fast.

On the other hand, since the experience a unit needs to get is based off the current cost they have, and usually higher cost units have higher HP, then higher tier units  have a higher difficulty for gaining levels, while they also get lower bonuses, as self healing isn't really worth on them.

**Comment by AoAGeneral** [comment]
Hello folks! This is AoAGeneral. Been balancing TD itself for roughly 3 years with the help of the community in TD. I have a strong knowledge basis in CNC95 using lan systems for team games and 1v1.

Currently I see a lot of numbers displayed that change the units stats when it gains a veterancy. My only concern is the needed testing on how they gain the level of these new veterancy.

At a 200% equal of their value this would make Mammoth Tanks harder to gain veterancy along with Commandos or other expensive units. (And having a Mammoth Tank or Commando on max veterancy is a lot of fun to play around with!) Would this be a bad idea in terms of balance itself since Nod units are cheaper in their cost compared to their value?

**Comment by ABrandau** [comment]
Tbh the very least that has to be done is remove fixed healing rate and turn it to percentage based, high tier units like your mammoth tank have less benefit from self healing than the rest, and add on top of that the difficulty of getting it.

About the veterancy, following your argument, the lack of an extra level will benefit Nod as they will be able to reach it sooner and gain more bonus, but if you look at the big picture, an independant unit should have a lower impact since they gain an extra 5% dps, at the cost of a 10% movement speed, which should nerf Nod units by a bit.

![image](https://user-images.githubusercontent.com/11763228/40333503-c5811bc6-5d26-11e8-8ba1-a4f83728661a.png)

Even tho the stats might differ, the idea here is to simplify the values, they could be more, they could be less, but they should be consistent as the unit levels up.

**Comment by AoAGeneral** [comment]
I can agree on being consistent. Going through the numbers and testing them would be the best idea. I just feel like at this point it might be a little to early to add it in this round.

**Comment by ABrandau** [comment]
Also check the self healing, I see no reason why use a fixed healing amount for all units.

**Comment by ZxGanon** [comment]
Yes sure we gonna try it out. Mesacer already prepares a modded example for it. Values like selfhealing or the added bonuses can be adjusted.It works well in SP but doesnt mean it would be healthy for TD. But as it has been told its about streamlining and also bringing a bit more sense to it.

Might take some time but I guess it will be worth it.

**Comment by ABrandau** [comment]
To continue with this topic, we removed the speed buffs from veterancy on SP, we havent tested much, but so far I can only say this is very handy to preseve the veteran units, because their speed buff usually makes them be the first to reach the destination, being that the enemy army, and ending out dead.

**Comment by ZxGanon** [comment]
To continue the testing on a new approach to rebalance the idea of the rank up system we have been finalizing the data:
^GainsExperience:
	GainsExperience:
		Conditions:
			300: rank-veteran
			600: rank-veteran
			900: rank-veteran
	GrantCondition@RANK-ELITE:
		RequiresCondition: rank-veteran >= 3
		Condition: rank-elite
	DamageMultiplier@RANK-1:
		RequiresCondition: rank-veteran == 1
		Modifier: 90
	DamageMultiplier@RANK-2:
		RequiresCondition: rank-veteran == 2
		Modifier: 80
	DamageMultiplier@RANK-ELITE:
		RequiresCondition: rank-elite
		Modifier: 70
	FirepowerMultiplier@RANK-1:
		RequiresCondition: rank-veteran == 1
		Modifier: 110
	FirepowerMultiplier@RANK-2:
		RequiresCondition: rank-veteran == 2
		Modifier: 120
	FirepowerMultiplier@RANK-ELITE:
		RequiresCondition: rank-elite
		Modifier: 130
	# SpeedMultiplier@RANK-1:
		# RequiresCondition: rank-veteran == 1
		# Modifier: 110
	# SpeedMultiplier@RANK-2:
		# RequiresCondition: rank-veteran == 2
		# Modifier: 120
	# SpeedMultiplier@RANK-ELITE:
		# RequiresCondition: rank-elite
		# Modifier: 130
	ReloadDelayMultiplier@RANK-1:
		RequiresCondition: rank-veteran == 1
		Modifier: 90
	ReloadDelayMultiplier@RANK-2:
		RequiresCondition: rank-veteran == 2
		Modifier: 80
	ReloadDelayMultiplier@RANK-ELITE:
		RequiresCondition: rank-elite
		Modifier: 70
	SelfHealing@ELITE:
		PercentageStep: 5
		Delay: 75
		HealIfBelow: 100
		DamageCooldown: 150
		RequiresCondition: rank-elite
	WithDecoration@RANK-1:
		Image: rank
		Sequence: rank-veteran-1
		Palette: pips
		ReferencePoint: Bottom, Right
		RequiresCondition: rank-veteran == 1
		ValidStances: Ally, Enemy, Neutral
		ZOffset: 256
	WithDecoration@RANK-2:
		Image: rank
		Sequence: rank-veteran-2
		Palette: pips
		ReferencePoint: Bottom, Right
		RequiresCondition: rank-veteran == 2
		ZOffset: 256
		ValidStances: Ally, Enemy, Neutral
	WithDecoration@RANK-ELITE:
		Image: rank
		Sequence: rank-elite
		Palette: pips
		ReferencePoint: Bottom, Right
		RequiresCondition: rank-elite
		ZOffset: 256
		ValidStances: Ally, Enemy, Neutral
	GivesExperienceMultiplier@RANK-1:
		Modifier: 150
		RequiresCondition: rank-veteran == 1
	GivesExperienceMultiplier@RANK-2:
		Modifier: 200
		RequiresCondition: rank-veteran == 2
	GivesExperienceMultiplier@RANK-ELITE:
		Modifier: 250
		RequiresCondition: rank-elite

Like we stated we have removed the movementspeed modifier to improve perfromance. Also it was odd that units got a movementspeed buff in the first place.

Also we have been experimenting with stronger selfhealing upon reaching elite/heroic rank on rank 3:
Old Selfheal Value (TD):
	SelfHealing@ELITE:
		Step: 200
		Delay: 100
		HealIfBelow: 100
		DamageCooldown: 125
		RequiresCondition: rank-elite

New Selfheal Value (SP):
	SelfHealing@ELITE:
		PercentageStep: 5
		Delay: 75
		HealIfBelow: 100
		DamageCooldown: 150
		RequiresCondition: rank-elite

The percentageheal has been drstically increased while also shorten the delay between healing intervalls. But we also increased the time between taking damage and being out of combat to harrass heroic units so it is a bit easier to prevent heroic units from healing up quickly by damaging them.

**Comment by Smittytron** [comment]
This was addressed by the veterancy overhaul from #18654.
