### ISSUE TITLE
Porting campaign missions (HELP WANTED AND NEEDED) 

### ISSUE THREAD

**Issue by BenChricton78** [OpenRA/OpenRA#15175]
I have begun to port the singleplayer missions for Tiberian Dawn to OpenRA, I am working on gdi08a, gdi08b, and gdi09. Porting these missions will be quite difficult, which is why I'm asking for people to help me port these. I'm currently porting gdi08a, so someone to handle the .yaml format would be nice. 

I'd also like people to handle the other two missions, and after we've ported them, we'll move on to the remaining GDI and Nod missions, before moving on to Dune 2000 and finally, C&C: Red Alert.

**Comment by GraionDilach** [comment]
http://nyerguds.arsaneus-design.com/cncstuff/cctxt/ccmanual.txt

https://www.youtube.com/playlist?list=PLgVvRqoxkObvfNAz_I9PsvdZ3pafMDQZ4

and the OpenRA missions.

**Comment by BenChricton78** [comment]
What about .lua? I need help to get me starting to code.

**Comment by GraionDilach** [comment]
That's exactly why I said to read the current OpenRA missions.

**Comment by GraionDilach** [comment]
Also, for RA1

http://ra.afraid.org/download.php/docs/racg110.zip and http://ra.afraid.org/download.php/docs/raspmct.zip.

**Comment by BenChricton78** [comment]
Well, to be fair, listening to a guy going through the process of making a C&C map and figuring out which trigger in the .ini is the trigger in the .lua, so that won't be a problem! Thanks.

But I still need a partner to handle the other missions whilst I work on one. That way, the missions will come out quicker.

**Comment by BenChricton78** [comment]
Thanks. I still need a partner to handle one map whilst I handle another.

**Comment by pchote** [comment]
The real bottleneck is the review process, so I wouldn't be too worried about that at this stage.

**Comment by BenChricton78** [comment]
Okay. Thanks for making me afraid of the review process, pchote.

**Comment by BenChricton78** [comment]
Also, I managed to get the games in my First Decade collection work, or at least RA2, Renegade and Generals. I had to use a fan installation for Tiberian Sun.

**Comment by BenChricton78** [comment]
As for the maps, I'll start working after my lunch.

**Comment by BenChricton78** [comment]
Ready to start working. Is it okay to use some kind of converter and then polish the maps up for their official release?

**Comment by BenChricton78** [comment]
I'm asking if it's okay to use the following converter: https://gist.github.com/Mailaender/93e8041f2535cffaf2490c307bee4553#file-map-cs-L536

**Comment by GraionDilach** [comment]
Doubt it'd help much, especially if you don't even know scripting at all. Cleaning up data converted though such generaltors (the ini->yaml ones are also messy) was always an issue when it comes to porting to OpenRA.

**Comment by Smittytron** [comment]
There's already an open PR taking a stab at GDI08a (#14998). It hasn't been updated since March, so I doubt much becomes of it. That said, it might be a good place to look to get started.

**Comment by BenChricton78** [comment]
You know what? Forget it. I'm not up to this map porting schtick. I never knew it would be a pain, so instead, I think I'll make a proper sidebar for Tiberian Dawn instead.

**Comment by lawando** [comment]
@BenChricton78 Consider to close the issue then or others have to do it later.

**Comment by GraionDilach** [comment]
I wonder if you'll intend to go through with the sidebar after you take a look at the chrome yamls.
