### ISSUE TITLE
Mod loading crashes early when mod.yaml contains incompatible formatting

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#15174]
All I did wrong in the mod.yaml was having two lines starting with a `#` comment without a tab before it in the `Packages:` category.
The exception was horribly non-descriptive, other than mentioning MiniYaml.

After fixing mod.yaml, the other yaml formatting errors at least gave proper 'BadIndent' exceptions, but we need a solution for mod.yaml, or - if that's not possible - be prepared for quite a few bug reports on this in the future.

**Comment by pchote** [comment]
```
		# select:
		#	 Start: 18
		#	 Length: 12
```

**Comment by pchote** [comment]
This is now documented at https://github.com/OpenRA/OpenRAModSDK/wiki/Update-notes:-release-20180307-to-next-release, which is linked from https://github.com/OpenRA/OpenRAModSDK/wiki/Updating-to-a-new-SDK-or-Engine-version.
