### ISSUE TITLE
[TS][bug]Can't set unrevealed terrain    
as moving destination for aircraft units

### ISSUE THREAD

**Issue by hathlife** [OpenRA/OpenRA#15170]
Play skirmish, try to use an aircraft unit as scout, and I found that I can't set unrevealed terrain as moving destination.Is it normal?

**Comment by ABrandau** [comment]
Thats exactly how the original game works, it can be disabled on defaults, under the aircraft trait.

**Comment by abcdefg30** [comment]
Yes, sadly this is not a bug but was a deliberate decision in #9945.
