### ISSUE TITLE
Selling Airstrip while vehicle unloading prevents the selling

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#15183]
In TD, if the Airstrip is sold at the very moment the cargo plane lands, the building won't be sold, and won't be able to be sold afterwards.

#### System Information
- **OpenRA Version:** release-20180307,
- **Mod:** Tiberian Dawn

**Comment by pchote** [comment]
I'm fairly certain that #15682 will have fixed this.
