### ISSUE TITLE
#15148 Regressed Auto-Calculated Selection Boxes

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#15184]
#15148
Here is RA War Factory for example:

![resim](https://user-images.githubusercontent.com/7933210/40668351-eb619bb2-636c-11e8-9ab7-a89a501165ad.png)

Selection boxes also different during and after make anim for some buildings.

**Comment by pchote** [comment]
This is a surprisingly subtle and tricky issue.  On the one hand, the code is behaving exactly as expected: actors that don't define explicit bounds fall back to asking `WithSpriteBody` for the bounding rectangle for the main body sprite.   RA/TD are now consistent with other mods that don't use Shp(TD) in that this now returns the bounding rectangle for the main body sprite, and not the artificially inflates frame rectangle.

The three options here are:
1. Decide that this is more trouble than we want to deal with right now and revert #15148.  #15194 gives us the same performance benefits, but we would lose the 16MB memory saving in RA and TD.
2. Define custom mouse bounds for the actors that have visibly regressed, the same way that we needed to in D2K and TS.
3. Rewrite the underlying sprite loading logic to propagate the frame size through to where it can be used by `IAutoMouseBounds`.  This would change the behavior consistently for all mods, and might hurt our ability to cull actors that are outside but near the edge of the viewport.

**Comment by GraionDilach** [comment]
2 sounds like the solution I'd say to go with on the longterm. 3 sounds like a hack and tbh explicit bounds are always better than anything else - hitshapes are also explicit by now afterall.

**Comment by pchote** [comment]
The issue there is that it may be too much work that nobody wants to do before the playtest.

**Comment by reaperrr** [comment]
It wasn't that bad:
#15198
