### ISSUE TITLE
Cursor only refreshes while moving

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#15191]
Possibly another regression from #15177.

**Comment by pchote** [comment]
I propose the following which should fix most of these regressions:

1. Revert the last commit from #15177 (makes steps 3 and 4 simpler to implement and review)
2. Move `SDL2HardwareCursor` and its exception type into its own file to reduce clutter.
3. Rename `IGraphicsDevice` and `SDL2GraphicsDevice` to `IPlatformInterface` and `SDL2PlatformInterface` (this has been a long time coming - half the work this class does isn't graphics!)
4. Move all the actual graphics stuff (but not cursors or window creation/teardown) to a new `SDL2GraphicsContext` class implementing a new `IGraphicsContext` interface.  `SDL2PlatformInterface` would wrap this object the same way it does `Sdl2Input`.  The graphics context can read the window handle / size / etc from the parent interface (these won't change after window creation). 
5. Restore the last commit from #15177 as a smaller `ThreadedGraphicsContext` class that now only needs to wrap the specific GL stuff.

What do you think @RoosterDragon?

**Comment by RoosterDragon** [comment]
(https://github.com/OpenRA/OpenRA/pull/15177#issuecomment-394096551) - I Agree. The issue behind most of the regressions was the change to separate the SDL and the OpenGL owning threads. The regressions are a side effect of where we don't have the calls being performed by the correct owning thread. Separating the two in the code will help remove the bad side effects.

**Comment by pchote** [comment]
Do you want to work on a PR for this @RoosterDragon?

**Comment by RoosterDragon** [comment]
I don't think I'll be able to find the time, sorry. If nobody wants to pick it up, may simply be best to deactivate the feature or revert the commit for now.

**Comment by pchote** [comment]
Ok, that's fine.  I can try and pick this up now that I know that we won't be duplicating efforts.
