### ISSUE TITLE
Polish turn speed values

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#15196]
So, from what I see on the traits page, the maximun turn speed value allowed is 255, but from the testing im doing, the value 40 already gives you an almost instant turn rate, this means 215 numbers are not used, meanwhile the difference between 1 and 2 is so big that I wish there was a number in between.

On this issue I am suggesting to change the turn speed equation a bit so it uses the whole range of numbers more consistently, why have 255 numbers if you are not going to go beyond 20, which yeah, covers the need for instant turn rates, but leaves very few options for slow turn rates.

And now I am going to post a few gifs to elaborate the idea (its around 2.2 mb)

Turn Speed 30
![turn speed 30](https://user-images.githubusercontent.com/11763228/40846745-7a732f56-6588-11e8-92c4-917111e9fe4d.gif)
Turn Speed 20
![turn speed 20](https://user-images.githubusercontent.com/11763228/40846746-7a9a4802-6588-11e8-8e56-aaf5cbbf637c.gif)
Turn Speed 10
![turn speed 10](https://user-images.githubusercontent.com/11763228/40846747-7acc2a34-6588-11e8-95a3-78dbc70a275d.gif)
Turn Speed 5
![turn speed 5](https://user-images.githubusercontent.com/11763228/40846748-7af68932-6588-11e8-9098-9f50e9f1d5a7.gif)

Edit: The unit at the left has TurnSpeed 2, while the one at the right has TurnSpeed: 1
![turnspeed1and2](https://user-images.githubusercontent.com/11763228/52295173-e27a3a00-2959-11e9-9b45-9ecace567202.gif)

**Comment by pchote** [comment]
Turn speeds are currently defined as facings/tick.  We really should convert this (and the rest of the facings code) to use WAngle directly instead.  This would improve the resolution here by a factor of 4.
