### ISSUE TITLE
[Suggestion] - Force the mod to crash at startup when inputting invalid propierties on traits. 

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#15201]
Im referencing my comment in #9810 , as an user who has to update mods constantly, I believe this will solve the issues with renaming properties of traits.

**Comment by lawando** [comment]
I assume this validation would make the startup for everyone slower but help only a few. An alternative technically unfounded suggestion could be to introduce a development startup mode that runs update rules of a specified timeframe without applying any changes. If the update rules match anything, there could be a warning or a list of the outdated properties. In the long term, such a development startup mode could be used to integrate a UI for the utility (update) functions.

**Comment by pchote** [comment]
This would be better done as part of the lint checks.

**Comment by ABrandau** [comment]
By lint checks you mean the check mod utility command? If that is the case, I think i will have to post more issues because that command take some hacks as errors, for example, if one weapon applies a Spawn Actor on Death effect, then it will complain for each weapon that doesnt, and then I cant use it because it wastes all the space on the command line on those comments.

**Comment by pchote** [comment]
I do, yes.  And yes, you should.

**Comment by ABrandau** [comment]
Well check yaml works, please check the lines that come after 173 https://pastebin.com/zPDW655H

``OpenRA.Utility(1,1): Error: Actor type cabsentry doesn't define a death animation or spawn an actor on death for weapon fireballlauncher!``

Lines like these seem to be repeated in a A * B amount where A is the amount of actors and B the amount of weapons, these sound like a bug tbh, as if the game were asking to have a specific death anim or spawn actor on death on each weapon, but implementing this is a very tedius task that doesnt solve anything nor adds extra value to a mod, I would remove this warning.

About the rest, Im going to take a look and comment if there is anything.

**Comment by pchote** [comment]
CheckDeathTypes indeed looks to be bogus, so I filed #15210 to remove it.  The other errors look like legitimate problems that you should fix on your end.

**Comment by pchote** [comment]
#15230 demonstrates why this is important even for our upstream mods.

**Comment by pchote** [comment]
I have a working prototype for this, but hit two problems preventing a quick and easy PR:
* Our default mods are full of junk values that need to be cleaned up before they will run again.
* HackyAI explicitly depends on users defining invalid property names, breaking the system.

**Comment by pchote** [comment]
The amount of bogus properties and hidden bugs in our default mods was just silly.  Adding to the milestone so that this can't happen again or to anyone else.

**Comment by GraionDilach** [comment]
Where do we define invalid properties on HackyAI?

**Comment by pchote** [comment]
The `SupportPowerDecision`s are defined directly on the trait instead of as children of a node that corresponds to a real field on the TraitInfo.  This is the only instance in the codebase that does this - even `HackyAI` does this right in all its other cases.

**Comment by pchote** [comment]
Sorry @ABrandau, I've run out of ideas on how we can do this properly without major engine changes.  Removing from the milestone.

**Comment by ABrandau** [comment]
Can you enable the code that checks the single yaml mistake on the utility? (and not on the mod) that should be good enough imo.
