### ISSUE TITLE
prevent the aircraft unit to ascent/deascent too frequently between edges

### ISSUE THREAD

**Issue by hathlife** [OpenRA/OpenRA#15208]
I upload a video on my personal wordpress page to explain this:
https://h0nm4m31k0.tk/index.php/2018/06/03/openra_helicopter_trait_problem/

**Comment by pchote** [comment]
This is a bug, not an intentional feature.  The aircraft code still hasn’t been updated to work with the terrain height map in TS.  The height prediction code from missiles needs to be extracted and generalised so that it can also be used by aircraft.

**Comment by GraionDilach** [comment]
Another option would be to use aircraft movement instead of heli movement for TS aircrafts.

**Comment by pchote** [comment]
Aircraft movement has the same underlying problem that requires the same fix.  It just manifests slightly differently (planes flying under the ground when hitting large altitude changes).

**Comment by ABrandau** [comment]
Until this bug is fixed, I suggest you to play with the ``AltitudeVelocity`` property of aircraft to work around this bug. (The faster they move, the less time they spend moving on elevation changes)

**Comment by reaperrr** [comment]
#16483 will fix that hovering/VTOL stop moving forward on altitude changes, at least, making their movement less jarring.

**Comment by pchote** [comment]
>  the height prediction should be added before we promote TS to a regularly shipping mod.

This will be just about feasible once the aircraft activity merge is completed.

**Comment by hathlife** [comment]
[See here](https://h0nm4m31k0.tk/index.php/2020/01/27/openra-openra-issue-15208/)
Sorry for not turning off the music while recording.
The issue seems to be fixed in playtest-20200118.
