### ISSUE TITLE
Differentiate between Neutral and Creep actors in-game

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#15214]
Currently, there is no way to know if a non-player actor is Neutral or Creep, except by coming into proximity, or by knowing the map.

Suggestion : add "Neutral"/"Creep (or Hostile)" under actor's name. 
See : https://i.imgur.com/0Hh2REU.jpg

**Comment by pchote** [comment]
If we wanted to go this route (i'm not convinced) then the way to do it would be enabling the stance prefixes like we do in the campaign missions.

**Comment by Smittytron** [comment]
Closing as wontfix. We discussed in Discord and the feeling is that the onus of making sure creeps are distinguishable should be on the mapmaker.
