### ISSUE TITLE
phpBB forum and spam

### ISSUE THREAD

**Issue by Beep6581** [OpenRA/OpenRA#15227]
Hey

I just read that you have a new forum, and it's phpBB. I maintained one for years, and wanted to offer a tip regarding the biggest issue we had - spam.

Let me start off by saying that the tools for creating spam are highly sophisticated, designed by highly skilled people paid handsomely for their time. Tools for combating spam in phpBB, on the other hand, lag far behind the tools for creating it.

The most effective plugins back then (I don't remember their exact names) were:
1. Blocking UTC-12 registration.
2. DNS blacklist.
3. Q&A on registration (you must change the questions every few months else its useless).

Be careful with the various phpBB captcha plugins - when I stopped using phpBB in 2016 they were all either completely ineffective or the ones which looked effective themselves had malicious code!

Good luck!

**Comment by IceReaper** [comment]
Block all ```POST``` request without the ```Referer``` request header via ```.htaccess```

**Comment by GraionDilach** [comment]
Should have been filed to OpenRA/OpenRAWeb but more preferably just told on the IRC if you ask me.

**Comment by abcdefg30** [comment]
Hey. Thanks for the tips, they were forwarded to IRC.
