### ISSUE TITLE
Frame limiter is bogus, and could be replaced with a vsync checkbox

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#15223]
#15222 highlights how badly (and worse, misleading) the Frame Limiter option in the graphics settings is

* If vsync is enabled (which should be the default on most systems) then setting the limit greater than the monitor's refresh rate or disabling it completely is irrelevant - the real FPS remains capped at the monitors refresh rate (e.g. 60 FPS for most people).
* If vsync is explicitly disabled (with [SDL_GL_SetSwapInterval(0)](https://wiki.libsdl.org/SDL_GL_SetSwapInterval) or I expect through a vendor-supplied driver config utility) then, at least on my system, the real frame rate is only vaguely correlated with the requested limit.  Setting the limiter to 10 gives a framerate of ~25, 30 gives 45, 60 gives 75, 200 gives 160, whereas disabling it gives ~230 FPS.
* If vsync is enabled with a framerate limit less than the refresh rate then I see the same wonky results as above.

It would be simpler and less bogus to replace the limit checkbox/textfield with a vsync on/off checkbox.  This is a simple patch, but depends on the current graphics rework PRs being merged first.

**Comment by reaperrr** [comment]
Note: With frame limiter disabled, scroll speed in windowed mode becomes so slow that the game is close to unplayable. I assume enabling VSync would fix that, just wanted to mention it as some players might disable VSync and then wonder why scroll speed has come crashing down.
