### ISSUE TITLE
Obsolete description for setting terrain speeds

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#15238]
Desc: "Set Water: 0 for ground units and lower the value on rough terrain."
->This description is outdated and will result in an "Attempted to divide by zero." error.

https://github.com/OpenRA/OpenRA/blob/0fc466daee53d4e0e3c157ce023844e311644dc5/OpenRA.Mods.Common/Traits/World/Locomotor.cs#L70

**Comment by noamyogev84** [comment]
Hi, I would like to take this one :)

**Comment by reaperrr** [comment]
> "Attempted to divide by zero."

@FrameLimiter Under which circumstances exactly did you get the error? Setting `Water: 0`?

**Comment by FrameLimiter** [comment]
Yep, setting any of the terrain speeds to zero will produce this error.

**Comment by Ectras** [comment]
@noamyogev84 Are you still on it?

**Comment by noamyogev84** [comment]
@Ectras no, go ahead!
