### ISSUE TITLE
D2K's building sight ranges may be wrong

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#15231]
#15201 reveals that D2K's `^Building` template defines `VisibilityType: CenterPosition` on `RevealsShroud`, but this has actually always been called `Type` and therefore has never worked.  We should check whether the ranges defined in yaml are correct (meaning that the actual ranges ingame are wrong), or whether the yaml values have been fixed individually based on the building's footprint.

**Comment by pchote** [comment]
@reaperrr do you have any memory of this back from #9458?

**Comment by reaperrr** [comment]
IIRC the range values simply match the sight ranges I got from TibEd. So because this actually used the footprint all along, I have some hope that bleed in fact behaves correctly, because I'd assume that the original values were calculated from footprint as well.
Before I reinstall Gruntmod edition, maybe @MustaphaTR or @CH4Code can recall (or check more quickly than me)?

**Comment by MustaphaTR** [comment]
Ok, wtf WW. Reveal range is centered around the bottom-right of the building.
![resim](https://user-images.githubusercontent.com/7933210/42146856-42eb050a-7dd3-11e8-834c-dc03d3b36968.png)

I don't think we would want to implement this like that, simply unbalanced and non-sensical. Current way CYard reveals looks OK to me on bleed but i'll check other buildings too (D2k shroud is broken on screenshots and Print-Screen don't work on my PC):
![resim](https://user-images.githubusercontent.com/7933210/42146951-cd82153c-7dd3-11e8-8af8-5a1872991e09.png)

**Comment by MustaphaTR** [comment]
Ok, these are what the original reveal ranges look like after adjusting them to be centered properly.
![resim](https://user-images.githubusercontent.com/7933210/42148628-abe2fe48-7ddb-11e8-9f0b-ad087a16e460.png)

They are footprint based, it seems like for some reason they were offset a bit. Also WFac also has a bit wierdness going on on top, where left has 3 cells cut from rectangular shape, while right has 5, probably another wierd calculation error on WW's side. I'll check our ranges and update if there is anything not matching, afaik not working trait properities are already removed, so we don't need to do anything about it.

**Comment by pchote** [comment]
Fixed by #15319.
