### ISSUE TITLE
The weapon "Crush" isn't used

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#15246]
RA: The weapon "Crush:" doesn't appear to be used by anything and should be removed. Crushing is handled by Crushable: CrushClasses & Mobile: Crushes.

https://github.com/OpenRA/OpenRA/blob/0fc466daee53d4e0e3c157ce023844e311644dc5/mods/ra/weapons/other.yaml#L141-L146

**Comment by reaperrr** [comment]
Closed via #15258.
