### ISSUE TITLE
Some missiles need refactoring to avoid improper spread damage

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#15249]
The MammothMissiles(td), MammothTusk(ra), and the ^SubMissileDefault(ra) missiles harm air units when firing at the ground, and harm ground units when firing at the air. This happens when a warhead capable of damaging both air & ground contains too large of a spread. Such weapons should either be split into separate AG/AA variants or simply keep their spreads ≤ 213.

Related issue:  #14860

**Comment by GraionDilach** [comment]
I'd take #14150 over this tbh.
