### ISSUE TITLE
SpawnActorsOnSell & EjectOnDeath should be made conditional

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#15243]
SpawnActorOnSell & EjectOnDeath should be made conditional so alternate sprites (e.g. RA small infantry) can be toggled via a lobby option without excessive structure/aircraft/vehicle duplication.

-> Also "~lores1.mix: lores1" should be added to the mod.yaml Packages: so that the small shok & small mech can be referenced.

**Comment by pchote** [comment]
Small sprite variants should be implemented as a per-player visual option, not using different actors.

**Comment by MustaphaTR** [comment]
Pchote is right, tho i think it would still be nice to have those conditional.
