### ISSUE TITLE
The Ore Refinery has an incorrect CustomSellValue

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#15240]
RA: The Ore Refinery has an incorrect CustomSellValue.
Ore Truck value = $1100, Ore Refinery value = $1400; the CustomSellValue should be $300 not $600. 
(Likely left over from when the game used original values: (HARV=$1400 / PROC=$2000)
https://github.com/OpenRA/OpenRA/blob/0fc466daee53d4e0e3c157ce023844e311644dc5/mods/ra/rules/structures.yaml#L1156-L1157

**Comment by abcdefg30** [comment]
@Smittytron do you think fixing this might have a negative impact on balance? (For example nerfing two refinery builds.)

**Comment by Smittytron** [comment]
This will reduce ref sales from $300 to $150 (assuming it's full health) and bounties from killing a ref from $60 to $30. It certainly doesn't look like much and I personally don't mind seeing this changed. That said we might hear some complaints about making such a change for the sake of polish.

**Comment by FrameLimiter** [comment]
Selling structures for more than they cost to build is inarguably bogus.
Cost of PROC: $1400
HARV:$1100 + PROC refund:$300 + Spawned infantry value:$240 = total:$1640

**Comment by pchote** [comment]
do we want to fix this before the playtest?

**Comment by netnazgul** [comment]
Now the only and true benefit of building ore trucks via refineries will be using a separate underused buildqueue. Before this fix you also got paid for it.

Might spur some interest into building ore trucks directly, but otherwise a legit correction.
