### ISSUE TITLE
The THF is using outdated "InfiltrateTypes" instead of "Types"

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#15250]
RA: The THF (currently disabled unit) uses an outdated trait name; "InfiltrateTypes:" should be changed to "Types:"
https://github.com/OpenRA/OpenRA/blob/0fc466daee53d4e0e3c157ce023844e311644dc5/mods/ra/rules/infantry.yaml#L508-L509
https://github.com/OpenRA/OpenRA/wiki/Traits#infiltrates

**Comment by pchote** [comment]
I already have a fix lined up for this as part of #15201.

**Comment by ABrandau** [comment]
Have fun doing a manual mass rename later on, I would keep it as it is.
