### ISSUE TITLE
Option for non-advanced only maps in the Resource Center

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#15278]
In the Resource Center, Add a checkbox to filter and remove all the "Advanced" maps.

Example : https://resource.openra.net/maps/author/SoScared/?mod=ra
There are too many duplicates of a few original maps.  Looking for those is tedious.

Removing the "advanced" maps would help find the original ones quickly.

**Comment by MustaphaTR** [comment]
This should probably go Resource center's repository.

**Comment by FRenzy-OpenRA** [comment]
Good call. Closing it here.
