### ISSUE TITLE
New comment identation system does not allow to comment out units

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#15276]
I have this unit that is commented out of the game, the reasoning is that it could be useful at some point of development. https://pastebin.com/QyEiRW6P

If I keep everything commented, the game will crash at the first inheritance.

If uncomment the unit name, it crashes at the cost property.

If I uncomment the unit named and the valued trait, the game will crash at the name property.

And if I uncomment bits of each trait, it will crash because there is incomplete data, and it will also kill the point of the comment.

As far as I can tell, this system seems to depend on uncommented values, which assumes that the user is only commenting a single trait or property, this doesnt work on practice, the modullar system of OpenRA will make people comment or uncomment things on bulk when testing, and so far its giving me the idea that I should not use comments anymore, this is very bad because I use them constantly when testing and experimenting.

**Comment by pchote** [comment]
Please read https://github.com/OpenRA/OpenRAModSDK/wiki/Update-notes:-release-20180307-to-next-release

The comment indentation needs to be consistent with surrounding nodes.  Jumping in and out levels will confuse the game.

**Comment by ABrandau** [comment]
Is there any text editing software that can do that type of identation with a hotkey? Mine applies the comment after the identation blocks, and manually fixing each line isnt really an option compared to just cutting those out.

**Comment by pchote** [comment]
Anything with a column select/cursor feature would do it.  e.g. using Textmate on macOS I can option-select a set of cursors in front of the yaml block, then press `#` once to comment out the entire block.

**Comment by ABrandau** [comment]
Fair enough, figured that out, will open again if I found a real bug then.
