### ISSUE TITLE
After compiling version release-20180307 on Fedora 26 "Failed to query server list."

### ISSUE THREAD

**Issue by Aricg** [OpenRA/OpenRA#15284]
### Issue Summary
Compiled OpenRA expect multiplayer to work.
returns "Failed to query server list."

#### System Information
Fedora 26

        $ mono --version
        Mono JIT compiler version 4.8.0 (Stable 4.8.0.520/8f6d0f6 Wed Mar 15 15:23:40 UTC 2017)
        Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen

- **OpenRA Version:** git checkout  release-20180307
- **Mod:**  Red Alert

#### Additional Information:
- Steps to reproduce

       mv ~/.openra/ ~/.openraOLD/
       git clone https://github.com/OpenRA/OpenRA.git
       cd OpenRa
       git checkout  release-20180307
       echo release-20180307 > VERSION
       make && make version 
       mono OpenRA.Game.exe Game.Mod=ra "$@"

Console:       

       Platform is Linux
       Engine version is release-20180307
       Using SDL 2 with OpenGL renderer
       Desktop resolution: 1920x1080
       No custom resolution provided, using desktop resolution
       Using resolution: 1920x1080
       Using window scale 1.00
       OpenGL version: 3.0 Mesa 17.2.4
       Using default sound device
       Internal mods:
        all: All mods (release-20180307)
        cnc: Tiberian Dawn (release-20180307)
        d2k: Dune 2000 (release-20180307)
        modcontent: Mod Content Manager (release-20180307)
        ra: Red Alert (release-20180307)
        ts: Tiberian Sun (release-20180307)
       External mods:
        ra-release-20180307: Red Alert (release-20180307)
       Loading mod: ra
       Loading mod: modcontent
       Loading mod: ra
       libpng warning: iCCP: known incorrect sRGB profile
       System.Net.Sockets.SocketOptionName 0x17 is not supported at IP level
       AL lib: (WW) FreeContext: (0x5638ec773d50) Deleting 32 Source(s)

- Logs

tcpdump shows my machine trying to hit 
   https://master.openra.net/

 Game reports: "Failed to query server list."

**Comment by pchote** [comment]
Fedora doesn't configure its mono packages properly, so https web queries fail.

Try running `sudo cert-sync /etc/pki/tls/certs/ca-bundle.crt`.

**Comment by Aricg** [comment]
![Alt Text](https://i.imgur.com/I0hxJwS.gif)
