### ISSUE TITLE
Predefined bot: on yaml won't work

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#15280]
Adding a predefined bot name under players in map.yaml won't work.
When you start a new game room (my case skirmish) the default bot will be "rush" and all other slots with **predefined** bots will be empty.

Personally I was about to make missions (coop and single) using that on my mod, with out the hassle of creating lua scripts for the AI.

**Comment by GraionDilach** [comment]
The modular AI rework opens the possibility to enable the AI through Lua via granting the respective AI functionality's condition to the respective player actor. I'd call that as a solution.

**Comment by pchote** [comment]
The modules can only be enabled on players who have are predefined as bots.

**Comment by abcdefg30** [comment]
Closing as there is no bug. Maybe looking at #17129 gives you an idea on how to use this.
