### ISSUE TITLE
Make Atom Bomb more game changing/ending

### ISSUE THREAD

**Issue by CatGirls420-NerevarII** [OpenRA/OpenRA#15309]
It's simple. The idea is to make the Atom Bomb something that will really have an effect on the tides of battle. Making it strong enough to really shake thing's up and decimate the enemy.

I've been trying this in my CG420 maps and found something that might add some excitement and motivation to gameplay.

What I did was increase the AOE (Area of Effect) across the board for the nuke as well as damages. The outer most "rings" for the AOE are only strong enough to kill units, not structures. The inner most rings are strong enough to do serious damage and kill a lot more around the target point. The medium rings have enough damage to kill weaker structures, and severely damage stronger ones.

I need to increase the damage output for medium and inner rings, and it might be....purrfect :P 

I also increased the nuke timer, so it takes longer to be ready to launch. This creates a dynamic where the nuke could be more of a target to be destroyed, as well as changing the tides of the battle in favor of the nuke owner. A slight health boost was added as well, to compensate the greater priority of a target that the nuke silo becomes.

I increased the timer by a minute or two, but I am thinking of making the Atom Bomb take 10-15 minutes to be ready for launch, as well as a final boost, as previously mentioned.

I've had nothing but positive feedback on the current changes, however, for the changes I plan on making, as previously mentioned, feedback has been positive as well as some people unsure of how it would work out. I, too, am unsure.

Thoughts?

.

.

Video clip of it in action (no idea why OBS borked the video, worked fine any other time):

https://www.youtube.com/watch?v=Q49x_GJyDe8

.

.

**YAML Edits For Damage/Area, From Weapons YAML**

.
```
Atomic:
	ValidTargets: Ground, Trees, Water, Underwater, Air
	Warhead@1Dam_impact: SpreadDamage
		Spread: 3c0
	Warhead@5Dam_areanuke1: SpreadDamage
		Spread: 3c512
		Damage: 9420
	Warhead@9Dam_areanuke2: SpreadDamage
		Spread: 5c420
		Damage: 8420
	Warhead@10Dam_areanuke2: SpreadDamage
		Spread: 7c555
		Damage: 16420
		Falloff: 1000, 368, 135, 50, 18, 7, 0
		Delay: 15
		ValidTargets: Trees
		DamageTypes: Incendiary
	Warhead@13Dam_areanuke3: SpreadDamage
		Spread: 7c222
	Warhead@14Dam_areanuke3: SpreadDamage
		Spread: 8c0
	Warhead@15Res_areanuke3: DestroyResource
		Size: 8
	Warhead@17Dam_areanuke4: SpreadDamage
		Spread: 9c0
	Warhead@18Dam_areanuke4: SpreadDamage
		Spread: 10c420
```

**Comment by abcdefg30** [comment]
OpenRA has blocked this user from our GitHub organization.
