### ISSUE TITLE
Add RequiresCondition to 'Valued' and/or 'Buildable' (Adjust AI difficulty with 'GrantConditionOnBotOwner').

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#15301]
I've been looking around for useful traits, adjusting AI difficulty levels with the 'GrantConditionOnBotOwner'. The most basic and simplest adjustments seem to be with 'Valued' and BuildDurationModifier under 'Buildable'.

'Valued' is probably the most straight forward scale of the AI difficulty, controlling both cost and production speed. 'BuildDurationModifier' would adjust only the build time (faster spending rate but the eco stay pretty much the same) but has the advantage of being applied through inheritance.

Having RequiresCondition with these traits would probably only relate to GrantConditionOnBotOwner but perhaps there are some other creative uses of it as well.

**Comment by GraionDilach** [comment]
You can deploy a workaround for now via using GCoBO to provide a prereq which allows the AI to build limited-to-AI clones until the request is coded.

**Comment by MustaphaTR** [comment]
I have CustomProductionTime and CustomProductionValue traits that can be enabled with prerequisites (not conditions) and can be filtered for different queues on my Generals Alpha engine (i use those for Tech Refinery cost reduction and General Specific cost/build time changes without needing duplicated). They may be good to go to bleed and would allow us to get rid of duplicate starport actors in D2K. The problem i see is they aren't modifiers and first active one will be the value that will be used, others are ignored.

**Comment by GraionDilach** [comment]
I plan to go over the buildtimes atleast for next+2 to rip them out to their own traits (something i already suggested in one of the PRs of @MustaphaTR) but notsure how I'll fare with the stances-refactor.

**Comment by CatGirls420-NerevarII** [comment]
This is a wonderful idea. Allowing options to choose different difficulty levels would be great, and with each option, it could scale the values mention in this post/thread.

For example:

Let's say the levels are Noob, Easy, Medium, Hard, Brutal.

Noob Level would, for example, have production speeds at 90%, making the AI produce very slowly.

Brutal Level, would have 10% production speeds, allowing much faster production, although it would need economy to support that, so....

Noob Level would prioritize eco a lot less, making minimal harvesters/trucks.

Brutal Level would prioritize eco a lot more, making much more harvesters/trucks.

__________

Squads could also be scaled, for example:

Noob Level would attack with small forces, scale at 10%, or 10 units.

Brutal Level would scale at 100%, or 100 units per attack force/squad.

__________

And maybe sometime, hopefully in the near future, an Intelligent/Adaptable AI could be coded, where better logic is used, and it can adjust it's strategy based on numerous variables, to make it seem like you're playing another human, at whichever level (Noob Level would be like playing a noob, Brutal Level would be like playing one of the top players of OpenRA).

**Comment by Mailaender** [comment]
Closing as essentially solved by #18971.
