### ISSUE TITLE
Mechanics can remote repair chronoshifted husks

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#15329]
![remoteRepairs.gif](https://i.imgur.com/5qGCNQ2.gif)

**Comment by dsimmons87** [comment]
Was going to report this issue, but with the opposite problem.

If you chronoshift some tanks into an enemy base for example, if any husks come back, it's impossible to repair them, as your mechanics just start running to where they chronoshifted back from in the enemy base.

**Comment by pchote** [comment]
Are you sure this is a regression?

**Comment by dsimmons87** [comment]
Yes this works perfectly on the release version. To reproduce:

1. Launch in debug mode.
2. Put barracks each side of the map,
3. Produce 5 rockets from one, and 5 mechanics from the other.
4. Produce a War Factory and Chronosphere near the mechanics.
5. Produce 5 medium tanks.
6. Chrono the tanks to the rockets, and force fire the tanks with the rockets. It should take two volleys per tank to turn it from a tank to a husk.
7. When the tanks return tell the mechanics to repair the husks.

On release: they will get in and repair the husks correctly.
On playtest: they will start running to the other side of the map.

**Comment by pchote** [comment]
Ok.  My gut feeling points to #15300 or #15025 as potential regression candidates.
