### ISSUE TITLE
"Failed to query server list." On mono 4.8

### ISSUE THREAD

**Issue by administrativeuser** [OpenRA/OpenRA#15334]
Platform is Linux
Engine version is release-20180307
Using SDL 2 with OpenGL renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1.00
OpenGL version: 3.0 Mesa 17.3.6
Using default sound device
Internal mods:
	cnc: Tiberian Dawn (release-20180307)
	d2k: Dune 2000 (release-20180307)
	modcontent: Mod Content Manager (release-20180307)
	ra: Red Alert (release-20180307)
External mods:
	cnc-release-20180307: Tiberian Dawn (release-20180307)
	d2k-release-20180307: Dune 2000 (release-20180307)
	ra-release-20180307: Red Alert (release-20180307)
Loading mod: ra
libpng warning: iCCP: known incorrect sRGB profile
System.Net.Sockets.SocketOptionName 0x17 is not supported at IP level <---I THINK THIS IS IT

Fedora 27

uname -a
Linux ---- 4.17.3-100.fc27.x86_64 #1 SMP Tue Jun -- --:--:03 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

mono --version
Mono JIT compiler version 4.8.0 (Stable 4.8.0.520/8f6d0f6 Thu Sep 21 07:12:44 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

**Comment by administrativeuser** [comment]
About an hour ago on release 20170930 I was able to query the server list with incompatible checked in the filters and successfully retrieved the list of all the games being hosted on the current version. Let me know if I can provide anything else helpful!

**Comment by pchote** [comment]
Fedora's mono packaging doesn't set up the certificates required for https queries.

You can fix this manually by running `sudo cert-sync /etc/pki/tls/certs/ca-bundle.crt` [ [ref](http://www.mono-project.com/docs/about-mono/releases/3.12.0/#cert-sync) ], but this really should be done by the Fedora mono packaging itself.

**Comment by administrativeuser** [comment]
Thank you so much. In the FAQ it only mentions old mono versions on linux as being the problem.

Weird that it worked on that old release

**Comment by administrativeuser** [comment]
Oh shit it totally was in there! I just read the first sentence of the paragraph and skipped it.

I added a newline to hopefully save you guys from more useless tickets in future

**Comment by pchote** [comment]
Actually, I only just added that a few seconds ago in response to this issue.  Thanks for pointing this out!

We switched over to https-only queries in release-20180218, so the older releases were immune.
Our future AppImage Linux packaging includes a local cert-sync workaround, so hopefully this will be less of an issue going forward.
