### ISSUE TITLE
Prerequisites granted by LobbyPrerequisiteCheckbox isn't counted in make-test

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#15343]
https://github.com/OpenRA/raclassic/issues/95

To test on bleed you can give `global-factundeploy` as prerequisite of ConYard and do a make-test.

**Comment by pchote** [comment]
It looks like I forgot to make `LobbyPrerequisiteCheckboxInfo` implement `ITechTreePrerequisiteInfo`.  Should be a simple fix, do you want to file a PR?

**Comment by MustaphaTR** [comment]
I'm trying to fix other lint errors on RAClassic rn. If you have time rn, you can go for it. If you don't what i'm doing shouldn't take much, i can do after it.
