### ISSUE TITLE
Minigunner and grenadier animation for Tiberian Dawn is using the wrong sprites

### ISSUE THREAD

**Issue by ccsv** [OpenRA/OpenRA#15349]
The Sprites for the Minigunner and grenadier for Tiberian Dawn is using the Red Alert sprites. 

The Minigunner and grenadier is suppose to do pushups on idle.

**Comment by BGluth** [comment]
Hmm... So I checked the minigunner sprites for the original non-OpenRA TD and they don't have any pushup animation. In the current release (20180307) the grenadier does use the pushup sequence in both TD and RA. The number of frames for the grenadier shp in OpenRA for both TD and RA are different lengths (TD: 659 RA: 565), so they shouldn't be identical, although the sequences seem to be the same and I can't easily see where the differences are.

**Comment by GraionDilach** [comment]
IIRC the TD infantry has those unused execution frames.

**Comment by BGluth** [comment]
I'm not seeing them in the shp for the minigunner.

**Comment by GraionDilach** [comment]
Ahyeah, only the civs got those. The kickboxing animations cause the differences.

**Comment by abcdefg30** [comment]
Looks like we can't do much here, then(?).
