### ISSUE TITLE
Top pixels of infantry not showing (bleed)

### ISSUE THREAD

**Issue by Smittytron** [OpenRA/OpenRA#15350]
It appears the top line of pixels on infantry is not showing for most of their facings. This is most obvious on units with bright hats like the engineer, medic and mechanic.

![no hats](https://user-images.githubusercontent.com/23546299/42729255-f7878e12-8796-11e8-80e6-cd59d4e1154f.png)

**Comment by pchote** [comment]
Probably introduced by #15148.  Can you try testing bleed commits before and after this was merged?

**Comment by Smittytron** [comment]
> Probably introduced by #15148. Can you try testing bleed commits before and after this was merged?

Yep, that's the one.

**Comment by pchote** [comment]
Fixed by #15375.
