### ISSUE TITLE
Deploying an mcv can abort the chronoshift return-to-origin teleport

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#15368]
Carried over from https://github.com/OpenRA/OpenRA/pull/15300#issuecomment-403164650.

![noChrono.gif](https://i.imgur.com/zJ5jd9A.gif)
Replay (and commit) can be found here https://github.com/abcdefg30/OpenRA/tree/noChrono

**Comment by pchote** [comment]
Closing as reported fixed by #15509.  Reopen if this is incorrect.
