### ISSUE TITLE
Lobby settings should be rembered between games

### ISSUE THREAD

**Issue by BGluth** [OpenRA/OpenRA#15381]
When creating a Skirmish/Multiplayer game it would be nice to have it remember the previous settings from the last game that was played. So for example this should include:

- The host's and any bot's settings (faction, team, etc.) but not other players
- Any connecting players will store their own settings (faction, team, etc.) locally
- Previous game specific settings (crates, starting units, etc.)

We could take this a bit further and store the settings to file somewhere for the next time the game is launched.

Edit: I'm going to take a shot at this over the next few days.

**Comment by BGluth** [comment]
Can anyone recommend a good file to store this data?

**Comment by BGluth** [comment]
I got this going for the most part (almost!). I think I can probably submit a PR tomorrow if all goes well.

**Comment by pchote** [comment]
There are hidden subtleties in this: the setting types need to be handled dynamically on a per-mod basis, and the code needs to be careful about the server vs player split and also behave sensibly with map-forced settings.  See previous discussions in #12990, #4787, #4122 for more info.

This issue duplicates #4122 and #4787, so I'll close this one.
