### ISSUE TITLE
RenderShroudCircle has no IsTraitDisabled check

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#15393]
RenderShroudCircle is always active regardless of CreatesShroud's conditional status. It should behave like RenderDetectionCircle and only be active when the trait is enabled.

**Comment by pchote** [comment]
IMO it is more important to be consistent with other base defenses.  We show the range circle for disabled tesla coils, so why should gap generators be any different?

**Comment by abcdefg30** [comment]
Closing as resolved by the above comment.
