### ISSUE TITLE
map.yaml crated from Map Editor don't have empty lines between sections

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#15399]
Not sure when this regressed, but it is a bit old as it seems to effect Generals Alpha and i haven't rebased it in more than a month.

This is from a map created on yesterday's bleed:
![resim](https://user-images.githubusercontent.com/7933210/43335626-56e0cc8e-91d8-11e8-95e5-827254dcee37.png)

**Comment by pchote** [comment]
This change came along with the yaml comments etc changes.

IMO this is a bugfix rather than a regression.

**Comment by pchote** [comment]
@abcdefg30: why the thumbs down?

**Comment by abcdefg30** [comment]
Imo empty lines between the different sections look better. That's just a personal preference though.

**Comment by pchote** [comment]
I have a fix for this sitting in my #15731 followup branch, which i'd completely forgotten about in the long delay getting that PR merged. Adding this issue to the milestone so that I don't forget again to do the mass map update and file the PR.

**Comment by pchote** [comment]
This is a prerequisite for the mass map refresh needed to apply #15731 to the default mods.
I already have an implementation for this which I will PR alongside the map updates before the next release.
