### ISSUE TITLE
Tiberium Sun/Firestorm (Base building in c&c games unattractive)

### ISSUE THREAD

**Issue by theUnnamed2** [OpenRA/OpenRA#15394]
In the old c&c games the developers had the idea that people would actually build bases, outposts and defend them. Why not revive the idea? The problem is that building bases and walls have quiet no benefit. A benefit system for the base building would give a change. An example to achieve that would be all buildings getting more health and more income when they are surrounded by a wall. To make outposts more attractive there could be something introduced that an outpost boosts the amount of income and health of all bases. An outpost would be defined for example as an mvc, a wall around it and a certain distance to another mcv/outpost. A game without building bases or outposts should be unbeneficial. Therefore the recourses should be adapted. That is my suggestion. Any other system that makes building bases/outposts more attractive would be also good!

**Comment by fruestueck** [comment]
While I like the idea of base building as you explained above I'd say that such an artificial benefit system possibly never will fit into the game. Building bases should be (or already is) attractive by itself as it provides beneftis (e.g. frontline service depo, barracks for faster reinforcement).

I still liked the idea : )

**Comment by abcdefg30** [comment]
I don't think this will be added for the default mods, sorry.
