### ISSUE TITLE
Hind colors are not obvious enough

### ISSUE THREAD

**Issue by ubitux** [OpenRA/OpenRA#15401]
In RA mod at least, the hind sprites do not use the player color obviously enough, often causing confusion in an allies matchup. Even saturated colors are often not enough to make a difference:

![2018-07-28-130052_1920x1080_scrot](https://user-images.githubusercontent.com/34467/43355961-599cd2f8-9267-11e8-8702-9dff0513c074.png)

**Comment by pchote** [comment]
Fixed by #15836.
