### ISSUE TITLE
Update the Resource Center for the new playtest(s)/release

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#15416]
https://github.com/OpenRA/OpenRA-Resources/pull/319 needs to be merged, and other potential compatibility issues tested and fixed if needed.

**Comment by dsimmons87** [comment]
If nobody's got it set up, or doesn't have time to, I can just give it another thorough test myself and merge and deploy it. But would just rather someone else checked it too given the database update.

**Comment by pchote** [comment]
I would like to look at it, but have not had time with everything else that has been going on.

**Comment by pchote** [comment]
@dsimmons87 its probably wishful thinking to expect I will have time for this any time soon.  Do you want to go ahead with this?  Could you also fix #15425 (just hardcode `sp` in the list of isometric mods) while at it?

**Comment by pchote** [comment]
Fixed by https://github.com/OpenRA/OpenRA-Resources/pull/319.
