### ISSUE TITLE
Allow players to take screenshots from the menu or to hide it.

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#15426]
Nothing critical, just an idea.

**Comment by rob-v** [comment]
You can take screenshot also in menu with Ctrl+P by default. See Settings - Input - Game Commands - Take screenshot hotkey. They are located in \Documents\OpenRA\Screenshots\... 
Could you try it?

**Comment by MustaphaTR** [comment]
My tests has shown that it only works if you aren't focusing on a textbox, like lobby chat or map editor actor filter.

**Comment by rob-v** [comment]
Yes it works in most or all dialogs when textbox doesn't have focus. e.g. in Skirmish I didn't find a way to do a screenshot except clicking on 'Choose map'. Then on return textbox doesn't have focus and you can create screenshot. In other cases such workaround might be not possible.

Should textbox ignore this hotkey (only this or more?) so it would be processed by a parent to take screenshot?

**Comment by MustaphaTR** [comment]
> Should textbox ignore this hotkey (only this or more?) so it would be processed by a parent to take screenshot?

IMO it should. Current behaviour is pretty annoying.
