### ISSUE TITLE
Shattered Paradise - Map Previews dont apply isometric logic when showing starting positions.

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#15425]
Reported by eskimo
![untitled](https://user-images.githubusercontent.com/11763228/43370269-fc8a634e-9349-11e8-9473-48d1e5ef71cd.jpg)

**Comment by pchote** [comment]
Confirmed that this is a resource center issue.

https://github.com/OpenRA/OpenRA-Resources/blob/37b8ae36e953e4434348cb77212d19e489c32658/openra/api.py#L442-L444

hardcodes the map type for each mod.
