### ISSUE TITLE
AI idle harvester handling broken

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#15437]
Must have regressed through #14889.
From a first glance I don't see why, but probably some stupid mistake.

**Comment by abcdefg30** [comment]
Maybe https://github.com/OpenRA/OpenRA/pull/14889#discussion_r173494833?

**Comment by reaperrr** [comment]
Doesn't look like it. In fact there seems to be a more fundamental issue, looks like for some reason the `activeUnits` list isn't passed properly, so harvManager.Tick doesn't find any actors.

**Comment by reaperrr** [comment]
...Stupid mistake indeed.
We pass `activeUnits` to the `harvManager.Tick()`, but since harvesters are now listed under `ExcludeFromSquads`, they're never added to `activeUnits` at all...

**Comment by pchote** [comment]
🤦‍♂️

**Comment by pchote** [comment]
This forum thread links a replay that may be useful to verify the behaviour: https://forum.openra.net/viewtopic.php?f=82&t=20594
