### ISSUE TITLE
Show geoip country for registered players

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#15448]
Some players ingame have lamented the loss of the country indicator, and we have no real plans for the rank line (currently with the Registered Player placeholder text).  We should replace this with the country display instead.

**Comment by GraionDilach** [comment]
I'd make this opt-in in the forum UCP tbh.

**Comment by matjaeck** [comment]
I'm not a big fan of displaying flags but replacing the rank label with the county name sounds good. IMO the forum interface should only be used for data that is accessible from the forum. There is already a "Location" setting in the UCP -> Profile and to me another "ShowLocation" or "ShowGeoLocation" setting in the UCP->OpenRA profile module seems confusing/misleading.

Location is also shown for anonymous users while it is understandable that we show/hide IP addresses for anonymous users / registered users, I'm not sure what would justify the privilege of registered users to hide their location. I think we shouldn't make a difference here. The location is useful information as it typically indicates what language you speak and should therefore be visible to everyone.

**Comment by anjew175** [comment]
I agree with Graion, people are kicked from games because of location

**Comment by pchote** [comment]
Ok.  This is a reasonable concern.  What is the risk of these same admins kicking anyone with an "Anonymous location" label?

**Comment by anjew175** [comment]
I think it would be best to put no information (or the placeholder) there than to display that its actively being hidden.
And though the risk may remain, it would be lessened in any case because these players do actively kick people who are or are not from specific regions.

**Comment by pchote** [comment]
Seems that the only safe option is to keep the status quo, hiding the geolocation for all registered users.
