### ISSUE TITLE
"Next Mission" button after accomplish mission

### ISSUE THREAD

**Issue by JacobTheHeartless** [OpenRA/OpenRA#15441]
I remember original game I played back in my early years of WinXP. OpenRa is quite epic but I missing classic "mission streak", that classic campaign mode feeling. When you finish mission you get menu containing buttons like restart or leave. My idea is to add "Next Mission" button in case if player accomplished mission. It will be nice if next mission is choosed and in case of multiple missions (like mission 6a, mission 6b etc.) right mission is choosed.

**Comment by avalach21** [comment]
i was wondering if any of the devs have ever had any plans or ideas to implement a full campaign like experience with the map mission select screen inbetween missions etc.

**Comment by reaperrr** [comment]
In short: yes.

**Comment by abcdefg30** [comment]
Closing as covered by #17067.
