### ISSUE TITLE
Scrolling with the right button in inverted mode registers a click upon release

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#15442]
### Issue Summary
When using the right mouse button for scrolling in inverted mode a move command is issued upon button release if any units are selected. This is not the behaviour in release-20180307 - scrolling with the right button does not register as a click.

If left click orders are enabled then scrolling with the right button causes any selected units to be deselected.

#### System Information
- **Operating System:** Windows 7
- **.NET / Mono Version:** .NET 4.7.2
- **OpenRA Version:** playtest-20180729
- **Mod:** any

#### Additional Information:
- Steps to reproduce
	1. Set right mouse button scrolling to "Inverted"
	2. Start a game
	3. Select any unit
        4. Scroll around with the right mouse button

**Comment by pchote** [comment]
Likely related to #14597.

**Comment by Kanar** [comment]
I'm sure this is easy to fix;
but my PC power supply literally exploded and I cannot look into it right now, I'm on my mobile. :(
Can someone else have a look into it?
