### ISSUE TITLE
Auth-required games should show a glyph in the server list

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#15455]
Requires master server changes.

**Comment by abcdefg30** [comment]
Do we want a filter as well?

**Comment by pchote** [comment]
I would like a filter, but we can't feasibly add one without confusing players or fundamentally rewriting the filter logic.

The filter choice is saved in the settings, with unused bits in the flag defaulting to 0, which means that everyone who has changed a filter will have these servers hidden by default.  This is unexpected, and therefore bad.
