### ISSUE TITLE
VTOL Aircraft & AttackPlane Conflict

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#15456]
When VTOL is set to True on the Aircraft trait, it is overridden by the automatic fixed wing landing procedure in the AttackPlane trait.

The plane will Vertical land if told to do so manually.

Also when VTOL is enabled & the plane tries to rearm near the left side of the screen  it just flies off the map & gets stuck.

<a href="https://ibb.co/ijBoGK"><img src="https://thumb.ibb.co/ijBoGK/harrierbug.gif" alt="harrierbug" border="0" /></a>

To add more context:

The goal I was trying to achieve while coming across this, was to have an Aircraft behave like a plane in the air but land like a Helicopter. Similar to RA2 Harriers & Black Eagles.

You can't use the AttackHeli Trait because they fly up to a target, fire & then do up to a 180 degree spin on the spot, which VTOL jet's should not do on an attack run.

**Comment by reaperrr** [comment]
Yes, the VTOL support is unfinished because the aircraft activity refactor it would need turned out to be an even bigger can of worms than I had hoped.
I have this on my TODO list, but no promises on when that will actually happen.

**Comment by tovl** [comment]
This has been fixed now.
