### ISSUE TITLE
Update forum links in wiki

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#15468]
The old `http://www.sleipnirstuff.com/forum/` is used in 64 occurrences and should be replaced with `https://forum.openra.net/`. I made some spot checks and it seems that the links stay intact after this.

Someone with push access could clone `https://github.com/OpenRA/OpenRA.wiki.git`, replace the occurrences and push the local changes.

**Comment by obrakmann** [comment]
Done: https://github.com/OpenRA/OpenRA/wiki/_compare/c6165b1449eb01152146f7094279ecccfee4b570
