### ISSUE TITLE
Optimizations for pathfinding etc

### ISSUE THREAD

**Issue by teinarss** [OpenRA/OpenRA#15460]
I am by no means an expert in this and have more used a explorational faction and with help by chrisf come to some suggestions which could improve the performance in pathfinding.

https://github.com/teinarss/OpenRA/commit/10be9f1cc4a9cd82be014d0d81b0a53d7545a44d

Things to check, most other stuff is just junk.
- Changed CPos  to use short for cordinations 
- Changed GraphConnection to use short for cost so the size is 64bits
- Using a binary heap instead of the HOT PQ

Also check the ApplyPercentageModifiersBenchmark

You can see in PathSearch.cs how i generated the data for the PQ benchmark.
This is the benchmark result, as you can see just by changing the CPos to use short we gain some performance. 
![image](https://user-images.githubusercontent.com/19173272/43676259-dde071ec-97ed-11e8-9787-5c10dc6a36e7.png)

**Comment by RoosterDragon** [comment]
- All 3 fields of a `CPos` is backed by a single `int` these days, so I'd say that one is resolved.
- Costs for a single cell are currently anchored around 100. This scaling is arbitrary but if you go too small then having to use whole numbers begins to restrict you a bit. e.g. if you want a cell to be about two-thirds as costly as another, 66 compared to 100 is decently accurate. 7 compared to 10 starts getting a bit inaccurate. Next, imagine a map that was a single long snaking path. About 50% of the map would be this path. On a 100x100 map, that gives us 100x100x50%x100=500,000 as guideline for max possible total cost. This is too big for a `ushort`. We'd probably get away with it most of the time but it feels too risky for my tastes.
- The benchmark for this looks promising, it might be nice to see if applying that change resulted in noticeable gains when it goes through the pathfinding process as a whole.

I realise this is an old issue but in summary I think exploring option 3 remains interesting.

**Comment by RoosterDragon** [comment]
In #20760, the performance of our prioirty queue was improved 3x, which is similar to the benchmark improvements shown for option 3. Therefore I don't think there's a need to investigate option 3 any further.

This issue can be closed, as all the presented options have been covered off.
