### ISSUE TITLE
Lobbies seem joinable in playtest-20180729 for some minutes after the game has started

### ISSUE THREAD

**Issue by gdavegdave** [OpenRA/OpenRA#15477]
In playtest-20180729, though a game has started, the lobby still appears joinable in the server list. This persists for a couple mins or so.

**Comment by pchote** [comment]
I wonder whether we are somehow dropping the master-server game-started ping...

**Comment by pchote** [comment]
@gdavegdave are you sure that this only affects the playtest?

**Comment by gdavegdave** [comment]
Yeah, I think so. I've played some release and haven't seen it there,
though I haven't tested it explicitly. AMHOL has experienced it in playtest
too.

**Comment by pchote** [comment]
We recently resynced the master server clock, so it would be good to separate playtest vs release from before vs after the clock fix.

**Comment by netnazgul** [comment]
Can confirm, it still lags for a minute or two before updating

**Comment by matjaeck** [comment]
I have experienced the same delay on the ShatteredParadise Servers.

**Comment by netnazgul** [comment]
Doesn't happen always though, it is somewhat sporadic. I.e. Once in 3 games I had lobby set as "playing" when I lost the game 2 minutes before. But not in the following games.

**Comment by pchote** [comment]
We can't do anything more here without more evidence to go on.  It sounds like this has already been fixed well enough, so removing from the milestone.

**Comment by netnazgul** [comment]
> 00:54] WhoCares: got that "lobby bug" again, lobby seems available but game has already been launch, try to join the lobby and "server not responding"
> [00:54] WhoCares: like in playtest
> [00:54] WhoCares: game is now displayed as running with 2 min
> [00:54] WhoCares: means it was displayed as a open lobby for almost 2 min after the game started

**Comment by pchote** [comment]
I just posted the following to our server hosts team:

> The new release server contains a bug that prevents it from updating the master server when a game starts.
> This has been reported as https://github.com/OpenRA/OpenRA/issues/15477, and is clearly visible in the jump of "waiting" games on http://www.openra.net/players/ since last weekend.
> 
> I'm not able to reproduce the issue with my own servers, but I suspect that changing the `lastChanged > lastPing` check in [MasterServerPinger.cs#L66](https://github.com/OpenRA/OpenRA/blob/03adceb65688c56b304aa71f7f4bb98320bbf6ce/OpenRA.Mods.Common/ServerTraits/MasterServerPinger.cs#L66) to `lastChanged >= lastPing` will fix the problem.
> 
> I (and, if it works, our online playerbase) would appreciate if some of our @OpenRA/server-hosts could try deploying this change to see if it fixes the issue.

If the fix works and our main hosts all adopt it then that takes the immediate pressure off shipping a quick hotfix release.

**Comment by pchote** [comment]
On further investigation, it looks like we just screwed up.  The commits in #15498 were not shipped in the last playtest or final release, either because I forgot to push the picked commits or because someone else force-pushed over them.

I have now pushed these commits to prep, and provided a branch and instructions for our main server hosts to deploy the fix.

**Comment by pchote** [comment]
The EU official servers have now been patched, so I recommend players prefer using those until we hear from other server operators.

**Comment by rmoriz** [comment]
can you please create fixed AppImages?

**Comment by pchote** [comment]
@rmoriz please try these:
https://www.dropbox.com/s/m65x7fqn0jht7hl/OpenRA-Dune-2000-x86_64.AppImage?dl=0
﻿https://www.dropbox.com/s/b36943xfiu5qvg4/OpenRA-Red-Alert-x86_64.AppImage?dl=0
https://www.dropbox.com/s/y9pf7tkvjybnnmm/OpenRA-Tiberian-Dawn-x86_64.AppImage?dl=0

If you can confirm that they work i'll share them to the server-hosts list.

**Comment by rmoriz** [comment]
TWIMC: docker image `rmoriz/openra:20180923-fix` now contains the Red Alert version. Servers `OOB Trolling prohibited` and `OOA Trolling allowed` are running that version. See https://hub.docker.com/r/rmoriz/openra/tags/  and https://github.com/rmoriz/openra-dockerfile/tree/20180923-fix
