### ISSUE TITLE
Map editor infantry are displaying both StandSequences: 'parachute' and 'stand'

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#15474]
![editor_inf_ra](https://user-images.githubusercontent.com/22008761/43680572-e8f8d768-980b-11e8-9b94-83e97f8ad569.png)

**Comment by reaperrr** [comment]
More like they show the correct stand sequence *and* the parachute sequence at the same time.

**Comment by pchote** [comment]
I'll PR a fix for this over the weekend.
