### ISSUE TITLE
Deployed unit turrets drawn under units

### ISSUE THREAD

**Issue by BGluth** [OpenRA/OpenRA#15486]
It looks like any deployable actor with turrets has it's turret's image drawn before the unit's image. Here's a gif to show it:

![turret draw order](https://user-images.githubusercontent.com/7939279/43819848-9e416210-9aa1-11e8-901a-9fcfe82886c9.gif)

Occurs on Bleed (e57f1d).

**Comment by GraionDilach** [comment]
Related: https://github.com/OpenRA/OpenRA/issues/10534#issuecomment-172236052

**Comment by pchote** [comment]
Closing as duplicate of #10534, which requires #14674 to fix.
