### ISSUE TITLE
RA: Advanced Install - Base Game Music download shows NaN in progress line.

### ISSUE THREAD

**Issue by emmalynrenato** [OpenRA/OpenRA#15489]
### Issue Summary
Red Alert mod Advanced Install - Base Game Music download shows NaN in the progress line.
I expected a valid number.

... ... ...

#### System Information
- **Operating System:**  Ubuntu 18.04
- **.NET / Mono Version:** Mono JIT compiler version 5.14.0.177
- **OpenRA Version:** git clone build from this morning
- **Mod:**  Red Alert

#### Additional Information:
- Steps to reproduce
	1. ./launch-game.sh
	2. After selecting the "Red Alert" mod, I clicked on "Advanced Install" from the
"Install Content" popup.
	3. I went to download "Base Game Music", and the progress line of text was:

  Downloading from openra.mirror.halfdata.com XXXXXXX.00/NaN bytes

where XXXXXXX was a valid number and increased in size as the download
progressed, but "NaN" stayed constant.

- Logs

$ ./launch-game.sh
Gtk-Message: 09:50:10.130: GtkDialog mapped without a transient parent. This is discouraged.
Platform is Linux
Engine version is {DEV_VERSION}
Using SDL 2 with OpenGL renderer
Desktop resolution: 1920x1200
No custom resolution provided, using desktop resolution
Using resolution: 1920x1200
Using window scale 1.00
OpenGL version: 2.1 Mesa 18.0.5
Using default sound device
Internal mods:
        all: All mods ({DEV_VERSION})
        cnc: Tiberian Dawn ({DEV_VERSION})
        d2k: Dune 2000 ({DEV_VERSION})
        modcontent: Mod Content Manager ({DEV_VERSION})
        ra: Red Alert ({DEV_VERSION})
        ts: Tiberian Sun ({DEV_VERSION})
External mods:
        ra-{DEV_VERSION}: Red Alert ({DEV_VERSION})
Loading mod: ra
Loading mod: modcontent

**Comment by pchote** [comment]
This is something that I have noticed before, but forgot to file an issue for.  I believe this happens when the mirror does not report the total file size in the http response.  If this happens, we should only report the current downloaded size, and omit the percentage and total size.

**Comment by emmalynrenato** [comment]
I made an attempt at fixing this.

See:

https://github.com/emmalynrenato/OpenRA/commit/a316977cd4a219c0502904659a27b11ce061242c

I'm new to github, so if this isn't the way you do things, just let me know what I
need to change. (I suspect there is a magical way to reference my commit in
my forked repository, in this issue comment, but I couldn't work it out).

I also looked at the OpenRA CONTRIBUTING.md document, and hopefully have the
style of the changes correct. But I wasn't exactly sure what you wanted for the text in
the commit message and whether there were any other "standard" checks/tests I
needed to do...

**Comment by emmalynrenato** [comment]
Ah, pressing the Comment button to submit my comment does the magic!

**Comment by pchote** [comment]
The code changes there look reasonable.  Do you want to try filing a pull request with your fix?

https://github.com/OpenRA/OpenRA/wiki/Contributing provides more details on the PR flow - note that life becomes much easier if you create a specific branch for the PR instead of doing it directly off your bleed branch.

**Comment by emmalynrenato** [comment]
#15493
