### ISSUE TITLE
Load map crashes with no maps/no folder

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#15492]
**Short**: When there are no maps present in the map folders the game crashes with an exception.

**Reproduce**
step 1: delete all maps from user/Openra/maps/mod/revision and programs/openra/mod/maps (except shellmaps).
step 2: press load map button in main menu

Noticed this while rebuilding a new mod with ModSDK on a second computer.

**Expected**: Load maps shows empty screen instead of crashing.

**Exception Detail**:
```
  Exception of type `System.InvalidOperationException`: Die Sequenz enthält kein übereinstimmendes Element.
     bei System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   bei OpenRA.MapCache.ChooseInitialMap(String initialUid, MersenneTwister random) in e:\GitExt\OpenRAModSDK\engine\OpenRA.Game\Map\MapCache.cs:Zeile 333.
   bei OpenRA.Mods.Common.Widgets.Logic.MapChooserLogic..ctor(Widget widget, ModData modData, String initialMap, MapClassification initialTab, Action onExit, Action`1 onSelect, MapVisibility filter) in e:\GitExt\OpenRAModSDK\engine\OpenRA.Mods.Common\Widgets\Logic\MapChooserLogic.cs:Zeile 135.
...
```

**Comment by noamyogev84** [comment]
I would like to investigate it. Can I be assigned for this issue?

**Comment by GraionDilach** [comment]
@noamyogev84 Just file a PR, we don't use assignments much.

**Comment by noamyogev84** [comment]
@CH4Code @GraionDilach just pinging you guys to kindly ask for your observation on my PR

**Comment by GraionDilach** [comment]
I will probably find time to look into PRs tomorrow evening or Sunday. Sorry for the inconvenience.
