### ISSUE TITLE
Client error showing up when spec + ready + game admin + pick spawn in the lobby 

### ISSUE THREAD

**Issue by ubitux** [OpenRA/OpenRA#15501]
Server errors show up with that combination.

How to reproduce:

- Go to a lobby
- Pick spec
- Check ready
- click a spawn point on the map

![2018-08-12-003016_504x77_scrot](https://user-images.githubusercontent.com/34467/43996664-d019fe18-9dc7-11e8-8e1f-2ecd85450fd9.png)

Edit: added "check ready"

**Comment by pchote** [comment]
Also need to have checked ready.

**Comment by abcdefg30** [comment]
I cannot reproduce this on bleed.
