### ISSUE TITLE
[TS] Stop order does not stop deployed turreted unit's turret from orienting

### ISSUE THREAD

**Issue by BGluth** [OpenRA/OpenRA#15508]
I noticed that for deployed units with turrets (Tick Tank, Juggernaut and Artillery) that issuing a stop order while the actor is aiming at something does not stop them from continuing to orient their turret to the old target (although they don't fire). It looks like all other units stop aiming when given a stop order, but not these units.

**Comment by tovl** [comment]
I cannot replicate this bug anymore in bleed. This and #15515 should probably be closed.

**Comment by pchote** [comment]
Fix confirmed.
