### ISSUE TITLE
What about "Red Alert Online" game support?

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#15513]
What do your command think about this game, about its gameplay conception?

Can/want u/going/will RA2 mod use resources from it (grafic/sounds/effects/missions) oficially?
Or support this game (full or not) like any new mod?

**Comment by GraionDilach** [comment]
Just no.

It's not even an RTS to begin with.

**Comment by reaperrr** [comment]
> It's not even an RTS to begin with.

And even if it was, that would be a sure-fire way to get into legal trouble.
What 3rd-party mods do is up to them, but 'official' support from us is definitely out of the question.

Closing as WONTFIX/WONTDO.
