### ISSUE TITLE
Playtest 20180729 Lobby Bug

### ISSUE THREAD

**Issue by TheGrinningSkull** [OpenRA/OpenRA#15516]
In the lobby, when an anonymous user becomes a spectator, their icon disappears and you can no longer view their information, despite them seeing their own information.

Unsure if this applies to registered users as well.
Images:
![img_7227](https://user-images.githubusercontent.com/30012195/44142699-eac5f4a2-a078-11e8-8a07-1739aa3ae574.jpg)
![img_7230](https://user-images.githubusercontent.com/30012195/44142713-fa21c516-a078-11e8-9d76-add5778736f5.jpg)

**Comment by pchote** [comment]
Thanks for the report.  This has already been fixed for the next playtest.
