### ISSUE TITLE
Paratroopers that cant land appear in the upper left corner

### ISSUE THREAD

**Issue by airetaM** [OpenRA/OpenRA#15520]
You can see the rank and the player have a small view then for a short moment .

![troopersbug](https://user-images.githubusercontent.com/14834585/44172087-69053b80-a0dc-11e8-8cc4-09ba2f68ef8f.png)

If there are enemys buildings the corner the troops sometimes attack it then.
Doesnt seem to happen when the destination is over water.

Release and playtest

**Comment by pchote** [comment]
Probably another regression from #14189.  We should fix this before we try to resume the FrozenActor Order rework.

**Comment by St3x** [comment]
Looks like https://github.com/OpenRA/OpenRA/issues/9750 and https://github.com/OpenRA/OpenRA/issues/13416.

**Comment by matjaeck** [comment]
Present in playtest-20190106.
