### ISSUE TITLE
Alt hotkey not working in Linux version

### ISSUE THREAD

**Issue by Xunius** [OpenRA/OpenRA#15527]
### Issue Summary

The force-move hotkey (Alt), which is also the chrono move hotkey for chrono tanks is not functioning as expected in Linux version of OpenRA.

#### System Information
- **OS:** Manjaro Linux 
- **.NET / Mono Version: ** mono  5.12.0.260-1
- **OpenRA Version:** release-20180307-1, installed via Manjaro's repo (`pacman -S`)
- **Mod:** Red Alert

#### Additional Information:
- Steps to reproduce
    1. Select any unit, hold down Alt key, cursor changes to blinking chrono icon, right or left click on map. Nothing happens. Cursor back to normal.
    2. Select chrono tank(s), hold down Alt key, cursor changes to blinking chrono icon, right or left click on map. Nothing happens. Cursor back to normal.
    3. Select unit, click on the force move button at bottom of the screen, cursor changes to blinking icon, and click on map, it works as expected.

I noticed this some time ago, I thought it might have something to do with my window manager (I was on Cinnamon before). I recently moved onto openbox and same issue persists.

**Comment by Micr0Bit** [comment]
all fine on debian

**Comment by pchote** [comment]
This topic suggests that openbox deliberately doesn't pass the alt key to applications: https://webcache.googleusercontent.com/search?q=cache:dOEX1WXaw24J:https://crunchbang.org/forums/viewtopic.php%3Fid%3D7255+&cd=4&hl=en&ct=clnk&gl=uk&client=firefox-b

The responses don't show for me, but I gathered that you can use `xev` to fix this.

**Comment by Xunius** [comment]
@pchote If alt key is not passed to openRA then the cursor did change when holding down Alt.
I still don't quite get how to use `xev` to fix, the link you pasted doesn't show all conversations. I only used `xev` previously to look up the name of a key. Can you give more hints how to do this?

**Comment by matjaeck** [comment]
https://github.com/OpenRA/OpenRA/issues/13105#issuecomment-458678533 argues that this is not an OpenRA issue (and not a bug).

**Comment by Xunius** [comment]
I got this fixed in Cinnamon now.

It turns out that I'd been searching at the wrong place. The setting for Alt key as a window-resizing hot key in the Cinnamon desktop is not in the "Keyboard" category, but in "Windows -> Behavior -> Special key to move and resize windows". After setting that to "Disabled" the Alt key works properly in OpenRA.

Havn't tried Openbox though.

**Comment by matjaeck** [comment]
Good to know. You could leave a note here if you happen to try it on OpenBox. We could add a note for this topic to the wiki [FAQ](https://github.com/OpenRA/OpenRA/wiki/FAQ/_edit) then.

**Comment by Xunius** [comment]
I tried the fix in Openbox and it worked.

Basically I edited the `rc.xml` config file at `~/.config/openbox/rc.xml`, and commented out `A-Right` mousebindings in the "Frame" section.  See this [Stackoverflow answer for more details](https://stackoverflow.com/a/29200453/2005415). Then re-config Openbox to make the change take effect.

**Comment by abcdefg30** [comment]
Good to hear you managed to resolve the issue.
