### ISSUE TITLE
PipCount: 0 still occupies pip space causing offset issues with other visible pips

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#15546]
A simple example is the ra stnk:
Give it a self reloading AmmoPool with a PipCount of zero. You'll notice the cargo pips display above the invisible AmmoPool pip row.
Ideally setting the pips to zero should also free up this unused pip space.

![pip](https://user-images.githubusercontent.com/22008761/44366802-ebef1300-a49b-11e8-8a4b-e3f63abda8da.png)

**Comment by MunWolf** [comment]
Best way to fix this would probably be to add a Where linq clause in SelectionDecorations.cs to filter out the IPips with a PipCount of 0, this would require adding a method / property to get that information from IPip.
```pipSources = self.TraitsImplementing<IPips>().ToArray();``` ->
```pipSources = self.TraitsImplementing<IPips>().Where(p -> p.PipCount()).ToArray();```

**Comment by anvilvapre** [comment]
No `IPips` trait present anymore in `bleed`.

**Comment by PunkPun** [comment]
It is indeed fixed, `WithAmmoPipsDecoration` doesn't allow 0 pips
