### ISSUE TITLE
Massive lag in Playtest 20180729

### ISSUE THREAD

**Issue by MrRocket50** [OpenRA/OpenRA#15547]
Hello everyone, I decided to install the newest version of OpenRA and when I run the game it causes a massive lag in the Main Menu (except in Tiberian Dawn) and while playing (in all mods), this does not happens in 20180307.

Windows 7 32bit
.NET 4.7.2
4GB RAM
NVIDIA geforce 7025 / NVIDIA nforce 630a
Playtest 20180729

![screen1](https://user-images.githubusercontent.com/28467698/44374511-eb1ea700-a4c4-11e8-9406-995492422c57.PNG)

**Comment by GraionDilach** [comment]
@MrRocket50 What is your CPU?

I am suspecting a single-core CPU at this point myself and in such cases, the renderer forcing context switches could also be the reason for the lower perf.

**Comment by MrRocket50** [comment]
@GraionDilach AMD Sempron(tm) 145 Processor 2.8GHz

**Comment by MunWolf** [comment]
That is a single CPU core so @GraionDilach guess is probably correct.

**Comment by pchote** [comment]
I wouldn't be surprised by a 5-10% overhead, but a 500 - 1000% overhead (which is what we are seeing here) doesn't seem at all reasonable.

**Comment by MrRocket50** [comment]
@pchote Sure.
![image](https://user-images.githubusercontent.com/28467698/44413373-979e6e80-a541-11e8-87df-8fc08efd04b4.PNG)

@reaperrr I tested the version you sent and the lag still occurs.
![image2](https://user-images.githubusercontent.com/28467698/44413482-d92f1980-a541-11e8-9d1a-a8d47fd6b189.PNG)

**Comment by pchote** [comment]
Ok, this supports my suspicion that your GPU doesn't like #15194.  Are you in a position to be able to try different GPU driver versions to see if anything changes?

**Comment by MrRocket50** [comment]
I tried to update the Drivers to the lastest version but there are no changes on performance, then I installed a old version of GPU driver from the disc and the performance graph changed to this:
![untitled](https://user-images.githubusercontent.com/28467698/44416458-4db98680-a549-11e8-9481-18f92a1429a7.PNG)
The version from the image above is from the provided link by @reaperrr while below is from Playtest 20180729.
![untitled2](https://user-images.githubusercontent.com/28467698/44416794-4e065180-a54a-11e8-9fb9-510f12d743bc.PNG)

**Comment by KOYK** [comment]
Had the same problem with playtest-20180825 but after 7-8 game restarts the lag stopped. And hardware cursor setting also worked at the final restart.

IntelCore i5-4460  
CPU 3.20GHz
RAM 8.00 GB
NVIDIA GeForce GTX 960
Windows 7 64 bit

**Comment by dreamworkerln** [comment]
![2018-12-15 05-34-46](https://user-images.githubusercontent.com/3149061/50038205-e1e5b700-002c-11e9-863b-7fb5a3c71c0e.png)

Same thing - got lag every 20-30 sec

Linux Mint 18.3
AMD Phenom(tm) II X4 980
CPU 3000.00MHz
RAM 10 GB
NVIDIA  GeForce GTX 750 Ti

no problem like this on v 20180307

**Comment by reaperrr** [comment]
We've identified the likely cause and merged a patch for it, so the next release will probably fix this.
