### ISSUE TITLE
Blank screen upon first launch

### ISSUE THREAD

**Issue by Sebbyastian** [OpenRA/OpenRA#15559]
### Issue Summary

... ... ...

#### System Information
- **Operating System:** Windows 10, 64 bit, 1703
- **.NET / Mono Version:** Include instructions on how to determine this, as you can only expect some people might be too retarded to give a fuck
- **OpenRA Version:** Whatever I downloaded today from the main website...
- **Mod:** D2K

#### Additional Information:
- Steps to reproduce
	1. Step
	2. Step
	3. ...

- Logs

Tell me where I can find logs and I'll go look for them... details, the devil is in the details...

- OpenRA Replays

- Screenshots & Videos

It's a blank screen... do you want to see a screenshot of a blank screen?

**Comment by Mailaender** [comment]
I believe this to be a duplicate of https://github.com/OpenRA/OpenRA/issues/15555 as I also got a frozen black/white window on first start.

**Comment by Mailaender** [comment]
Also this was a terrible bug report. Have a look at https://github.com/OpenRA/OpenRA/wiki/FAQ#my-game-just-crashed to give better details next time.
