### ISSUE TITLE
Wrong Version Number for freetype When Building on Windows 10

### ISSUE THREAD

**Issue by ogrady** [OpenRA/OpenRA#15552]
### Issue Summary
Fetching dependencies on Windows 10 fails for freetype 2.6.0. Closest available version number on NuGet is 2.6.1.1 https://www.nuget.org/packages/freetype/2.6.1.1

Changing the version number in `fetch-thirdparty-deps-windows.sh` seems to resolve the problem.

#### System Information
- **Operating System:** Windows 10
- **OpenRA Version:** irrelevant
- **Mod:** irrelevant

#### Additional Information:
- Steps to reproduce
	1. run `make.cmd` 
	2. enter `d` as parameter

**Comment by pchote** [comment]
https://www.nuget.org/packages/SharpFont.Dependencies/ is stuck on 2.6.0.

Are you still able to reproduce this?

**Comment by ogrady** [comment]
No, you explained to me in IRC that it probably was a problem with the NuGet backend and indeed, after cleaning and trying again everything worked properly. Sorry for forgetting to close this issue.
