### ISSUE TITLE
Failed to register current mod metadata

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#15555]
### Issue Summary
First startup seems to be problematic. Quick install also doesn't work.

#### System Information
- **Operating System:** Windows 10
- **OpenRA Version:** playtest-20180729
- **Mod:** Red Alert, Tiberian Dawn, Dune 2000

#### Additional Information:
- Steps to reproduce
	1. Launch the game

- Logs
```
Failed to register current mod metadata
System.IO.FileNotFoundException: Die Datei "C:\Users\Matthias\Documents\OpenRA\ModMetadata" konnte nicht gefunden werden.
Dateiname: "C:\Users\Matthias\Documents\OpenRA\ModMetadata"
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   bei System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   bei System.IO.Directory.CreateDirectory(String path)
   bei OpenRA.ExternalMods.Register(Manifest mod, String launchPath, ModRegistration registration)
```

The file or folder indeed doesn't exist.

![image](https://user-images.githubusercontent.com/756669/44620804-132e5180-a89b-11e8-9caa-56a6358f4337.png)

**Comment by pchote** [comment]
Does this still occur with the new playtest? Is this using the installer, or built manually?

**Comment by Mailaender** [comment]
I used the installer.

**Comment by reaperrr** [comment]
I can confirm that creating the folder fails. I did have that folder from some previous release, hence why I didn't notice while testing yesterday.

**Comment by Mailaender** [comment]
I have no idea why https://github.com/OpenRA/OpenRA/blob/bb536ee4fcf0e5d5afd6cf2537fd92b76db059cf/OpenRA.Game/ExternalMods.cs#L130 fails.

**Comment by pchote** [comment]
Can you check the permissions on the Documents\OpenRA directory?

**Comment by Mailaender** [comment]
I can confirm that this happens with OpenRA-playtest-20180825 and that whitelisting `RedAlert.exe` in Windows Defender or disabling it helps.

**Comment by pchote** [comment]
This isn't a regression on our side, so removing from the milestone.

**Comment by Mailaender** [comment]
For anyone having the same problem: see https://support.microsoft.com/en-gb/help/4028485/windows-10-add-an-exclusion-to-windows-defender-antivirus

**Comment by Mailaender** [comment]
Upon release we should probably send in a false positive report of RedAlert.exe etc. at https://www.microsoft.com/en-us/wdsi/filesubmission?persona=SoftwareDeveloper
