### ISSUE TITLE
Visualize unit move lines in observer mode

### ISSUE THREAD

**Issue by ubitux** [OpenRA/OpenRA#15576]
Structure rally point are already visible, but not unit moves lines in observer mode. It would provide a lot of insight on what the player is/was doing (move vs a-move, how the micro game is handled, understanding weird moves, ...).

Note: kind of related to waypoints (https://github.com/OpenRA/OpenRA/issues/2598, https://github.com/OpenRA/OpenRA/issues/13390, ...)

**Comment by Smittytron** [comment]
👍 This would be very handy for casting games. Can probably go unstated, but these lines should only be visible when the units are selected by the observer.
