### ISSUE TITLE
Trees vanish when killed under fog

### ISSUE THREAD

**Issue by FrameLimiter** [OpenRA/OpenRA#15579]
If a tree dies under the fog it visually disappears. The tree husks should be updated under the fog.
FrozenUnderFog: should be replaced with HiddenUnderShroud:

cnc:
https://github.com/OpenRA/OpenRA/blob/5d1c37a4c55e1ec4d8ab7d83501e4ca6eb77c985/mods/cnc/rules/defaults.yaml#L938

ra:
https://github.com/OpenRA/OpenRA/blob/5d1c37a4c55e1ec4d8ab7d83501e4ca6eb77c985/mods/ra/rules/defaults.yaml#L897

**Comment by reaperrr** [comment]
From @pchote in #15581:
> I have mixed feelings about this. On the one hand, this should fix the trees disappearing by making the husk visible, but on the other **we shouldn't be leaking that the tree has died through the fog at all**.

I had the same thought. Considering they have FrozenUnderFog, the issue described in the OP is definitely a bug, even if we end up using HiddenUnderShroud this still needs investigation as it might (or rather *should*) affect other actors as well.

**Comment by pchote** [comment]
We should do the suggested fix until this can be fixed properly.
