### ISSUE TITLE
Crash when changing map

### ISSUE THREAD

**Issue by praetp** [OpenRA/OpenRA#15575]
### Issue Summary
Crash when selecting map

#### System Information
- **Operating System**: Ubuntu 18.04
- **.NET / Mono Version:** Mono 4.6.2
- **OpenRA Version:** release-20180307
- **Mod:** Red Alert

#### Additional Information:
- Logs
see attachment
[bug.zip](https://github.com/OpenRA/OpenRA/files/2329627/bug.zip)

**Comment by pchote** [comment]
Closing as a duplicate of #15526, but this is very interesting because it confirms that this was not a new bug like as previously thought.  Thanks for the report!
