### ISSUE TITLE
OpenRA TiberianSun - Fatal Error

### ISSUE THREAD

**Issue by ILYArus1987** [OpenRA/OpenRA#15572]
[debug.log](https://github.com/OpenRA/OpenRA/files/2323569/debug.log)
[DxDiag.txt](https://github.com/OpenRA/OpenRA/files/2323584/DxDiag.txt)

The game after some time takes off in the "Skirmish" mode with bot's. :(

**Comment by MustaphaTR** [comment]
This debug log seems to be from Shattered Paradise not TS, also exception*.txt usually contains the real reasons of crashes, so please send that.

**Comment by pchote** [comment]
The debug.log contains references to Shattered Paradise and units that aren't in our TS mod.  I suggest re-filing this over at https://github.com/ABrandau/Shattered-Paradise/, but make sure that you include the exception-&lt;date&gt;.log, which contains all of the details needed to diagnose the crash!
