### ISSUE TITLE
WithIdleOverlay>IsPlayerPalette is ignored on Previews

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#15571]
I was trying to make Stinger Site with cloak palette for its camo on it. But game was crashing with Palette "cloak" not found. I made a PaletteFromPaletteWithAlpha named cloak and now it isn't showing remaps on placement preview, but it is fine when placed.

**Comment by GraionDilach** [comment]
RA2 buildings are using a lot of playerpaletted WIOs and I would have expected this bug to appear along with those, so the report is confusing to say the least.

It sounds to me moreso that something else is the culprit. What is the exact YAML setup/original crashlog?

**Comment by MustaphaTR** [comment]
RA2 seems like not effected because it doesn't define a custom `Palette:`. IsPlayerPalette seems to be ignored in this case.

**Comment by GraionDilach** [comment]
And why do you need to define both? I suspect your palette hierarchy having a wrong aspect here.

**Comment by MustaphaTR** [comment]
It is default to false and i want it to render in a different palette than building itself. IsPlayerPalette is a boolean not a palette name as in RenderSprites.

Tbh, that isn't what i needed. Camo shouldn't be player paletted, but a bug is a bug and someone may actually get blocked by this.

**Comment by pchote** [comment]
Changing https://github.com/OpenRA/OpenRA/blob/e038b8674224ebb251773a5ab82bbc05042e5ace/OpenRA.Mods.Common/Traits/Render/WithIdleOverlay.cs#L46 to 
```csharp
p = init.WorldRenderer.Palette(IsPlayerPalette ? Palette + init.Get<OwnerInit>().Value(init.World).InternalName : Palette);
```
should fix this, but I don't have a testcase to verify it.

**Comment by MustaphaTR** [comment]
This should no longer be an issue since Previews no longer override the palette.
