### ISSUE TITLE
Something is wrong with the CrateSpawner min-max calculation.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#15586]
I tryed to put CrateSpawner on Player actor to imitate original games' 1 crate for each player logic. I use Maximum and Minimum of 1, but still sometimes 2 planes spawn for some players, i couldn't figue out the issue myself:
![resim](https://user-images.githubusercontent.com/7933210/45042335-226b8700-b073-11e8-86f0-762d68a15e89.png)
Also planes seems to spawn with owner of actor trait is on. While crate itself is always WorldOwner. I dunno if there would be any reason to keep this like that. I was just keeping it to figure out the above issue. That part is an easy fix.

**Comment by reaperrr** [comment]
It's actually quite simple, the crate count is updated from the `Crate` trait when the crate is spawned (dropped from plane), so if the SpawnInterval is shorter than the time the previous plane needed to reach the drop zone, another plane is spawned before the first crate is dropped and counted.

Not sure what the best fix would be, though.

**Comment by MustaphaTR** [comment]
>so if the SpawnInterval is shorter than the time the previous plane needed to reach the drop zone, another plane is spawned before the first crate is dropped and counted.

I don't think this is the case, i'm using SpawnInterval of 3000 ticks or 2 mins. That's more than enough for crates to land.

**Comment by reaperrr** [comment]
Ok, I guess the crate is created at the beginning of the FrameEndTask afterall.
It's actually the `var toSpawn`. If both min and max are 1 and current crate count is 0, both parts of `toSpawn` return 1, so the result will be 2.
