### ISSUE TITLE
Horrible performance (Shattered Paradise)

### ISSUE THREAD

**Issue by TheHopelessThrumbo** [OpenRA/OpenRA#15592]
The title is self explanatory, my performance on game launch is horrifying. Game barely works on 5FPS, while original C&C games have no problem with 60FPS. Is it related to the engine optimisation for newer graphic cards?
-Intel HD Graphics
-Intel Core i3 M350
-6GB RAM DDR3
-Windows 7 Professional
![image](https://user-images.githubusercontent.com/39307800/45219394-0c480b80-b2ab-11e8-9a78-835fa9189071.png)

**Comment by fusion809** [comment]
Is this an issue you experience with the official mods (RA, TS, D2K)? If not, then is it possible this is a report that belongs at Shattered Paradise's repo? https://github.com/ABrandau/Shattered-Paradise. I'm sure if this really is an upstream issue (i.e. belonging to this repo), and you report it to Shattered Paradise's repo, they'll tell you.

**Comment by pchote** [comment]
170ms to render a frame is definitely something wrong between the OpenRA engine and the GPU/drivers.  The isometric support isn't optimized (one of the reasons for our own TS mod being delayed), but this is expected at a factor of 2-3 vs the stable mods, not a factor of 10.

@chrisforbes do you have any insights as to where we could start debugging this?

**Comment by reaperrr** [comment]
@TheHopelessThrumbo You mention the 'original games', I assume you mean literally the original games and not our official mods shipping with OpenRA releases/playtests?

If that's the case, could you install the latest OpenRA playtest to check whether performance is significantly different there compared to Shattered Paradise?

**Comment by TheHopelessThrumbo** [comment]
@reaperrr I tried it, and they have around 30FPS with drops. I wonder why is it so hilariously different?

**Comment by reaperrr** [comment]
@GraionDilach: i3 350M is a laptop model, so there's not much that can be done (except switching to a faster & newer laptop, or a desktop with at least a dedicated mid-range GPU from around 2010 or later).

And yeah, nearly 10x as many texture sheets as the official mods sounds like the primary culprit, that IGP probably simply has too few/weak texture units or samplers (and maybe too low memory bandwidth as well).

**Comment by TheHopelessThrumbo** [comment]
So it is just about the complexity. Hmmmm... how a theoretically more resource-hungry game can work for me better?

**Comment by pchote** [comment]
Possibly related to #15547?

**Comment by TheHopelessThrumbo** [comment]
The fact is other mods work fine.

> @GraionDilach: i3 350M is a laptop model, so there's not much that can be done (except switching to a faster & newer laptop, or a desktop with at least a dedicated mid-range GPU from around 2010 or later).
> 
> And yeah, nearly 10x as many texture sheets as the official mods sounds like the primary culprit, that IGP probably simply has too few/weak texture units or samplers (and maybe too low memory bandwidth as well).

...So this is just killing my laptop more than OatBF. Goddamit

**Comment by abcdefg30** [comment]
Closing due to the lack of activity/information.
