### ISSUE TITLE
OnEnteredProximityTrigger does not work with units with multiple attack types.

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#15602]
AFAIK our fork does not touch LUA code at all so I am posting this here, I am making a mission for Shattered Paradise, the player is supossed to scout around, capture an mcv, establish a base, steamroll and capture an objective.

For this I set up a proximity trigger when the player gets near the MCV, the game is suppossed to uncover the MCV and send a message, what I found is that the game crashes when there are tick tanks in the proxy range (Tick Tanks use both AttackFrontal and AttackTurreted).

If I remove the tick tanks, the trigger works without any issues, here is the lua log

[lua.log](https://github.com/OpenRA/OpenRA/files/2371369/lua.log)

also the mission code, https://pastebin.com/R8wZZk5r (proxy trigger is on line 84)

Do note that I have copied code from your original missions.

**Comment by abcdefg30** [comment]
The (real) issue is that the lua combat properties only work for one attack trait at the moment.
