### ISSUE TITLE
System.DivideByZeroException

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#15618]
Hi !

### Issue Summary
I got this while watching a 100 % bot game :
```
OpenRA engine version playtest-20180825
Red Alert mod version playtest-20180825
on map c3221005bf33f1f71ccc3fb7b55e580ba0ff2bd0 (Love Thy Neighbor by cpthavoc).
Date: 2018-09-15 11:17:55Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.DivideByZeroException`: Tentative de division par zéro.
   à OpenRA.WVec.op_Division(WVec a, Int32 b)
   à OpenRA.Mods.Common.Activities.ReturnToBase.Calculate(Actor self)
   à OpenRA.Mods.Common.Activities.ReturnToBase.Tick(Actor self)
   à OpenRA.Activities.Activity.TickOuter(Actor self)
   à OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act)
   à OpenRA.Actor.Tick()
   à OpenRA.World.Tick()
   à OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   à OpenRA.Game.LogicTick()
   à OpenRA.Game.Loop()
   à OpenRA.Game.Run()
   à OpenRA.Game.InitializeAndRun(String[] args)
   à OpenRA.WindowsLauncher.RunGame(String[] args)
```

#### System Information
- **Operating System :** Windows 10
- **.Net Version :** .Net 4.7.2
- **OpenRA Version :** playtest-20180825
- **Mod :** Red Alert

#### Additional Information
- Map : https://resource.openra.net/maps/24399/
- Replay : https://ufile.io/8ez40
- All non-empty logs : https://ufile.io/eojct

**Comment by abcdefg30** [comment]
I suppose https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs#L86 is to blame.

**Comment by pchote** [comment]
Confirmed that this happened because `approachCenter` was equal to `posCenter`, causing `tangentDirection` to have length 0.

We should aim to fix this for Next + 1.
