### ISSUE TITLE
The zombie has a bad frame & an incorrect start for its idle1 sequence

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#15633]
The RA zombie.shp contains a black bar on frame 108(ora-107) x,y:[13-27,1]
It also contains four black pixels that should be red blood x,y:[6,3][22,0][37,3][37,6]

The zombie idle1 sequence should start at '95' not '96':
https://github.com/OpenRA/OpenRA/blob/d9946f63e4d62e1dc4d084cc87af069e33296b99/mods/ra/sequences/infantry.yaml#L1308

Revised zombie.shp:
[zombie.zip](https://github.com/OpenRA/OpenRA/files/2407850/zombie.zip)

**Comment by pchote** [comment]
My preference is still to remove the zombie completely - this should be left for custom maps instead of included by default.

**Comment by robertschifferli** [comment]
What are you going to do with the Bio Lab then?  It only unlocks ants?  Perhaps some more ant variations could be added... I specifically remember a red fire ant from the original Counterstrike.

**Comment by avalach21** [comment]
What are you going to do with the Bio Lab then? It only unlocks ants? Perhaps some more ant variations could be added... I specifically remember a red fire ant from the original Counterstrike.
