### ISSUE TITLE
Game Crashes "/levelup" Cheat During Attack

### ISSUE THREAD

**Issue by alienfxfiend** [OpenRA/OpenRA#15636]
When I used the "/levelup" debug cheat repeatedly (4 times to Star them up) when under attack (using the Q hotkey to select all units) —the game crashes with a fatal error message box —happened to me twice using the latest version (playtest version (OpenRA-playtest-20180825)) Please fix this I thought it was the large map [Chaos Canyon] causing the crash, but after making a Run As Admin & Windows Defender exception for RedAlert.exe, it still happened again. BTW I'am using the debug menu [in Skirmish game vs CPU Turtle\Naval AI 1v1.] P.S: As a workaround I need to stop using the "/levelup" debug cheat (at least vs. a CPU, won't be a prob playing alone by my self.) Also I like how Paratroopers are veteran in the latest version of OpenRA.

**Comment by pchote** [comment]
Can you please upload the exception.log file that is written with the crash details?

**Comment by alienfxfiend** [comment]
[exception-2018-09-23T032307Z.log](https://github.com/OpenRA/OpenRA/files/2409025/exception-2018-09-23T032307Z.log)
[exception-2018-09-23T023014Z.log](https://github.com/OpenRA/OpenRA/files/2409026/exception-2018-09-23T023014Z.log)
Sure, I suspect it is the 327Z crash log, but I'm uploading another one as well...

**Comment by abcdefg30** [comment]
Reproduction case:
- rank a unit up to the maximum level
- let it gain experience the normal way (killing actors)
- use the dev cheat again

https://github.com/OpenRA/OpenRA/blob/bb536ee4fcf0e5d5afd6cf2537fd92b76db059cf/OpenRA.Mods.Common/Traits/GainsExperience.cs#L83
Consequently, the line above calculates a negative amount (as the experience required for the maximum level is lower than the experience the unit has currently).
