### ISSUE TITLE
AppImages needs a kernel module

### ISSUE THREAD

**Issue by rmoriz** [OpenRA/OpenRA#15637]
I strongly suggest you continue to provide the old package for linux because AppImages need the fuse kernel module, hence root access. It also won't work in containerized environments where the user/scope has no influence regarding OS kernels (like Docker)

**Comment by pchote** [comment]
As a workaround for servers you can use the `--appimage-extract` to extract the filesystem to a directory, and then call the `AppRun` file directly.

**Comment by rmoriz** [comment]
`launch-dedicated.sh` is gone? :(

**Comment by pchote** [comment]
It is not shipped in the AppImages, but you can grab it from https://github.com/OpenRA/OpenRA/blob/bleed/launch-dedicated.sh and change the launch line inside the loop to point at the AppImage or extracted AppRun script.

**Comment by rmoriz** [comment]
I see. I also need to download all AppImages to get a server that is capable of running all mods.

**Comment by pchote** [comment]
You might find https://github.com/IceReaper/ORASM useful as a reference.

**Comment by pchote** [comment]
Closing as we do provide a solution here.
