### ISSUE TITLE
Weird unit move - maby a bug

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#15631]
While watching the latest 5A's [shoutcast](https://www.youtube.com/watch?v=TVFA4AOMmAg&t=508s) i've noticed a strange move by an artillery at [Timestamp 08:28](https://www.youtube.com/watch?v=TVFA4AOMmAg&t=508s).
I do not have the replay at hand. Is this a bug in the engine or maby from some mod?

**Comment by abcdefg30** [comment]
Sounds like #9404.

**Comment by St3x** [comment]
You can reproduce this one easily on almost any Ore Gardens map, for example [this one](https://resource.openra.net/maps/27875/).

On the following screenshot, put any vehicle at the green spot, ask it to go to the red one, and see it "glitching" at the blue one :

![openra-2018-09-21t153738715z](https://user-images.githubusercontent.com/43476982/45891402-c9675700-bdc5-11e8-8745-8b9d14e460c9.png)
