### ISSUE TITLE
Properly cancel/finish Child-/SequenceActivities instead of nulling them

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#15632]
We have several bugs caused by unconditionally nulling or replacing activities, instead of properly canceling/finishing the current one first:

#9404
#10223
#10224
#15631
and probably quite a few more.

To fix this, we'll have to update the activity code to support propagating cancellation through activity sequences (including ChildActivity sequences).
For the sake of consistency and any potential cases that might need it, we should probably do the same for `OnActorDispose` introduced by #15622.

**Comment by reaperrr** [comment]
Moving to Future milestone as, while Next+1 is probably too optimistic, it should be at least higher priority than a lot of other things, considering the number of bugs related to this.

**Comment by obrakmann** [comment]
> We have several bugs caused by unconditionally nulling or replacing activities,

Agreed. Almost every second invocation of `SequenceActivities` is a source of bugs.

> To fix this, we'll have to update the activity code to support propagating cancellation through activity sequences (including ChildActivity sequences).

This is already happening for `ChildActivity`, and doesn't make sense for `NextActivity`.

The problem we're having are probably strictly related to `Move` activities, which cannot be cancelled on the spot. I did not take that into account when I re-wrote the base activity class. Changing `Cancel()` to return a bool was in retrospect kind of a half-assed measure and not well thought through. Nowadays I think that either reverting it to return void, or making it return the state of the activity after attempting to cancel it would be better. To support the `Move` use-case, it would probably also make sense to introduce a `Cancelling` ActivityState.
