### ISSUE TITLE
remove ip addresses from replay files

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#15647]
privacy improvement, no need to store/save/write ip addresses in/to replay files.
and possibly other tokens like auth keys.

making it possible to publish them.

**Comment by matjaeck** [comment]
Removing the IP sounds reasonable, however it is the only way to identify a non registered player. Authentication data is needed for registered players and including it should not be a privacy or security issue.

**Comment by anvilvapre** [comment]
next to removing them from save games, 
it would be better to remove the ip addresses from the network protocol in the communication between server and other clients. 
or perhaps the client ip address can be replaced by a hash.

i.e. players are now able to see other players ip addresses which shouldn't be needed.

**Comment by matjaeck** [comment]
A possible fix is to show a privacy information prompt like we do for system info that informs the user about data processing when starting the game for the first time. If the user disables the network features, multiplayer would be unavailable.

> perhaps the client ip address can be replaced by a hash.

Sounds like a good idea to me.

**Comment by pchote** [comment]
Right now the IP address is the only tool that players have to try and avoid abusive and harassing players. Removing this would not be a smart idea.

**Comment by matjaeck** [comment]
A pseudonymized hash would fulfill the same function (identification of a player) in a more privacy.

**Comment by Mailaender** [comment]
I found https://github.com/spanglel/OpenRAReplay which seems to  strip data from OpenRA replay files.
