### ISSUE TITLE
Flawed tech building capture logic when owner is defeated

### ISSUE THREAD

**Issue by DvD12** [OpenRA/OpenRA#15650]
**Release 20180923**, **Red Alert mod**

If a player is defeated while an engineer is capturing one of his tech buildings, the tech building ownership will revert to neutral but the capture process will last indefinitely, with the capture progress bar also growing indefinitely.

Replay attached - bug takes place at around 33:45

[OpenRA-2018-09-26T204047Z.zip](https://github.com/OpenRA/OpenRA/files/2421738/OpenRA-2018-09-26T204047Z.zip)

**Comment by pchote** [comment]
Fixed by #15643.
