### ISSUE TITLE
Rockets deployed from APC become uncontrollable and temporarily unowned

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#15654]
### Issue Summary
Rockets deployed from APC become uncontrollable and temporarily unowned and return to place where loaded.
... ... ...

#### System Information
- IDK, wasn't my client
- release-20180923
- Red Alert

- OpenRA

#### Replay
6:10, above right players Weapons Factory
[WTF.orarep.zip](https://github.com/OpenRA/OpenRA/files/2428731/WTF.orarep.zip)

- Screenshots & Videos
![ex](https://user-images.githubusercontent.com/1582784/46218193-9cdbae00-c376-11e8-9e5f-c9ae6116ea03.jpg)

**Comment by pchote** [comment]
Something glitched with the `EnterTransport` activity to make them lerp to the wrong location:

<img width="211" alt="screenshot 2018-09-28 at 23 11 00 2" src="https://user-images.githubusercontent.com/167819/46235811-f4c4e580-c373-11e8-8afe-9044b959f3ef.png">

I'm not immediately convinced that this is a new regression.

**Comment by pchote** [comment]
The infantry move to the front of the war factory before they return to normal control, so i'm pretty sure that `Target.Positions` for the APC is somehow falling back to its original creation location instead of its actual position.

So this is probably related to #14913 and #15505.

**Comment by AMHOL** [comment]
@pchote as far as I could tell the rockets returned to the tile on which they were loaded into the APC, I notice that Yellow loaded 4 rockets before adding one more, I wonder whether the split loading + select all by type was something to do with the issue.

**Comment by pchote** [comment]
I have tracked this down to https://github.com/OpenRA/OpenRA/blob/1abfaa94af3b3972cf0c081dc8a8626ce6bcf052/OpenRA.Mods.Common/Activities/Enter.cs#L257-L259
where `savedPos` was saved in the tick before the actors were loaded into the APC.


I don't yet understand why "always call done for movable targets and use a separate exit activity" didn't apply in this specific case and not the vast majority where we have never seen this bug before.

**Comment by pchote** [comment]
Repro case: select an infantry unit and shift-click to queue two or more EnterTransport activities into the same transport.
