### ISSUE TITLE
Content Download Restricted on some network domains.

### ISSUE THREAD

**Issue by TechnichalDoge** [OpenRA/OpenRA#15653]
1. Content download restricted on some network domains like schools.
2. Can be fixed by putting the content on a seperate hidden github and have the game install it from there.
Content download restricted. Should download normally vs. Restrict.

**Comment by TechnichalDoge** [comment]
Note the network is on a whitelist (kinda).

**Comment by Mailaender** [comment]
I assume you have to ask for permission then. Nothing we can do about it.
