### ISSUE TITLE
Messed icons in the construction panel on the right

### ISSUE THREAD

**Issue by gimpox** [OpenRA/OpenRA#15655]
Version: 20180923
The panel used to build units and/or building get messed after less than one minute.
All the standard icons representing soldiers/building disappear, and are replaced with bulky random color stripes or blocks. See the attached screenshot.
The game get quickly unusable.... :( :( :(

Previous version was working fine, indeed. 

My operating system: Ubuntu 16.04

![selection_491](https://user-images.githubusercontent.com/16726551/46235353-3eb0ca00-c37a-11e8-99ae-6fb639e110f1.jpg)

**Comment by pchote** [comment]
Possibly related to #15431.

**Comment by pchote** [comment]
Great news. I'll close this then, and any further discussion can continue in #15664.
