### ISSUE TITLE
Exception of type `System.InvalidOperationException`: TypeDictionary contains multiple instances of type `OpenRA.Mods.Common.Traits.CapturesInfo`

### ISSUE THREAD

**Issue by fusion809** [OpenRA/OpenRA#15697]
### Issue Summary
Was playing the Red Alert mod with the Tournament Island map against 4 AIs (sorry I do not recall the exact AIs, as I wasn't anticipating this), I was at position A, I had captured the AI at C's base (destroying the opponent) using my engineer, I _think it_ it was a game where I had set it so that engineers weren't re-usable. I had an unexplored map, unlimited build area, fog of war, kill bounties and other options left at defaults. It may be irrelevant but this was with my own OBS package &mdash; https://build.opensuse.org/package/show/home:fusion809/openra-bleed. My thirdparty.tar.gz file was built against commit 25307. 

#### System Information
- **Operating System:** openSUSE Tumbleweed.
- **.NET / Mono Version:** 5.10.1.47.
- **OpenRA Version:** 25307 (9cf8cba).
- **Mod:** Red Alert. 

#### Additional Information:
Re-running on the same map, same OS, same mod, with random AIs again, re-usable engineers, roughly same conditions and gameplay, after the game was manually built from the OpenRA git repo (commit number 25307 again), and started with `./launch-game.sh` failed to recreate this issue. 

I think I've given enough information for you's to try to recreate the error I had, if there's something I've missed please tell me and I shall fix that, if I remember what I did. 

Only log I kept, I'm afraid (as I was expecting my attempt to recreate it, with OpenRA manually built, that is) is the exception log: https://gist.githubusercontent.com/fusion809/900ee54b2e7da3dd5e639e5a741ca337/raw/b61cc8314c28fc9dbb9714e254e26c2dfd1c2821/log. 

- OpenRA Replays
[OpenRA-2018-10-11T055137Z.zip](https://github.com/OpenRA/OpenRA/files/2468187/OpenRA-2018-10-11T055137Z.zip)

As for screenshots/videos I must admit I was more interested in playing it than recording it, plus I was unaware the exception would occur until it happened.

**Comment by pchote** [comment]
Related to #15076
