### ISSUE TITLE
Game crashed when joining a server.

### ISSUE THREAD

**Issue by praetp** [OpenRA/OpenRA#15703]
### Issue Summary
Game crashed when joining a server.
... ... ...

#### System Information
- **Operating System:** Ubuntu 18.04
- **.NET / Mono Version:** mono Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)
- **OpenRA Version:** release-20180923
- **Mod:** Red Alert

- Logs
See attached log
[exception-2018-10-13T201805Z.log](https://github.com/OpenRA/OpenRA/files/2475812/exception-2018-10-13T201805Z.log)

**Comment by abcdefg30** [comment]
Thank you for the report! :)
This looks like the issue reported in #13915.
