### ISSUE TITLE
Forum registration & smurfing

### ISSUE THREAD

**Issue by BeanBnZ** [OpenRA/OpenRA#15700]
The idea would be to not allow choice of colour in game unless you are registered on the forum, you just get what you are given.

**Comment by pchote** [comment]
Individual server hosts can add this to their servers (add a check for the player fingerprint like https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/ServerTraits/LobbyCommands.cs#L796), but this isn't something I could support including in the default server.

The forum integration is an opt-in extra, not something to start locking standard features behind.

**Comment by matjaeck** [comment]
Someone who wants to play anonymously against weaker opponents will not stop doing so if they can't use their preferred color. IMO there is not a problem with smurfing anyways. Voting for closing.

**Comment by BeanBnZ** [comment]
Thanks :)
