### ISSUE TITLE
Make ProximityCapturable conditional

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#15714]
This will help any one who wants to make garrisoning buildings like they are in red alert 2.

For example with a cargo condition like this:

	V01:
		Cargo:
			Types: Infantry
			MaxWeight: 5
			PipCount: 5
			LoadedCondition: Loaded
			EjectOnDeath: True
		ProximityCapturable:
			CaptorTypes:  Infantry
			RequiresCondition: !Loaded

Sticky: is the only problem with this so maybe add something like:

	ProximityCapturable:
		CaptorTypes:  Infantry
		RequiresCondition: !Loaded
		StickyIfEmpty: true\false (so if its empty and false it will return to natural owner)

**Comment by KOYK** [comment]
pfff my browser is retarded. I cant edit this and add "insert code" to the first part sorry for that.

**Comment by matjaeck** [comment]
IMO the in #11214 suggested "ChangeOwner" Trait would be a better approach to implement garrisoning because it could be used together with cargo directly for example without relying on capture logic. More conditional traits are welcome though.

**Comment by KOYK** [comment]
Yea you are right.
Should I close this then? or just leave it as a condition trait request?

**Comment by KOYK** [comment]
It wont be fixed\added, closing it.
