### ISSUE TITLE
AI vehicle going through a crate

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#15715]
Hi !

### Issue Summary

I got this while watching a 100% AI game :

![ezgif-5-2d143a2f5675](https://user-images.githubusercontent.com/44304657/47242266-8614fe00-d3ee-11e8-8a24-ff20e3589f3d.gif)

#### System Information
- **Operating System :** Windows 10
- **.Net Version :** 4.7.2
- **OpenRA Version :** release-20180923
- **Mod :** Red Alert

#### Additional Information :

- Map : https://resource.openra.net/maps/12213/
- Replay : https://uploadfiles.io/g3vls __(Happens around 30:20, top right corner of the map)__

**Comment by PunkPun** [comment]
Could not reproduce it on bleed, bots seem to be correctly collecting crates.

It was likely patched in many of the crushability and occupies space PR's
