### ISSUE TITLE
Unloaded unit from naval transport become uncontrollable and temporarily unowned

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#15710]
### Issue Summary

Sorry if that's a duplicate issue, but similar to #15654, I had a bug with an unloaded MCV from a Naval transport. The MCV got locked after getting unloaded, unable to move or re-entering the transport.

#### Additional Information:
- Steps to reproduce
I actually don't know how that happened ... 

- OpenRA Replays
[OpenRA-2018-10-16 naval bug.zip](https://github.com/OpenRA/OpenRA/files/2481926/OpenRA-2018-10-16.naval.bug.zip)
At 5:00, central island.

- Screenshots & Videos
![transport-bug](https://user-images.githubusercontent.com/20139967/47000607-eb37cd80-d128-11e8-9984-a8ae256216d4.gif)

**Comment by abcdefg30** [comment]
Please reopen if this is still an issue.
