### ISSUE TITLE
Add support for discord's rich presence features

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#15712]
Discord supports interaction between people in a discord environment and players in a game. See https://discordapp.com/developers/docs/rich-presence/how-to for more information. https://github.com/Lachee/discord-rpc-csharp implements their rich presence SDK in C#. An implementation would need to be approved by Discord before it will be available. 

We already have functionality to join a lobby directly, the web server browser allows to do this. This would be a nice feature for our players in the official discord channel, too. Other interesting things would be to expose other information, like if a player is in a lobby, the main menu, or in a game, what map they are playing, game duration etc. 

A side effect of this would be to advertise OpenRA via discord.

**Comment by matjaeck** [comment]
Seems to be a can or worms and I don't want to be the one that opened it so closing again.

**Comment by pchote** [comment]
What is the problem here?

**Comment by matjaeck** [comment]
My concern was that suggesting to work on additional side-projects causes conflicts. The issue can exist though and I think it would be a nice feature, so re-opening.

**Comment by Mailaender** [comment]
This works fine when using https://software.opensuse.org/package/discord :+1:
