### ISSUE TITLE
Classic production queue: Allow item production while another item is paused.

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#15729]
This would be a compromise to solve the problems around the inherently required spam of production commands in RA. It addresses #10166 because the current mechanism is not user friendly, but for another reason than stated in this issue: resetting production of stacked core gameplay units to build specialized units.

Being able to pause per item instead of to pause per queue would allow to build any unit when you need them and continue the paused item stack after this, thus encouraging players to make use of specialized units which offered more viable options and therefore increases depth of gameplay. It really makes a difference if you have to rebuild your production stack and in many situations it will not be worthwhile to use specialized units because the advantage you would get from using them in a certain situation is eliminated by the disadvantage of resetting the production stack of core gameplay units that need to be produced continuously due to the way economy is set up for the game.

In my opinion the current mechanism restricts the potential of the game for these reasons and should be adapted so it does not conflict with the nature of OpenRA's RA. It is a missing feature for an otherwise very well working mechanism that makes the game more fun to play. The proposed feature would align very well with the existing mechanism, made it more responsive and wouldn't automate anything any further or mean to shift further away from the original.

**Comment by dragunoff** [comment]
Instead of pausing any queues this can simply be implemented as the ability to queue a unit at the top of the stack (after the currently produced unit). 

For example starting with this stack:
```
# In progress:
E1
# Queued:
E1, E1, E3, E1, E1, E3, etc.
```
The player uses a modifier, say `Alt + click`, to insert a unit at the beginning of the queue resulting in this stack:
```
# Still in progress:
E1
# Queued:
E6, E1, E1, E3, E1, E1, E3, etc.
```
If the player wishes to start construction of the inserted unit right away, they should manually cancel the "in progress" unit.

**Comment by pchote** [comment]
This is proposing a fundamental change in the classic production logic - one of the defining features of the production logic is the choice between throwing away production time (when cancelling a unit) vs getting a more appropriate unit out slightly sooner.  This would also introduce strategies such as pausing production for many items at 99%, and then releasing them all at once when someone attacks you / you capture an enemy facility / etc.

 I wouldn't object to merging a support for this (like we did for KKND's `ParallelProductionQueue`), but I would object to adopting it in our default mods (like I did for KKND's `ParallelProductionQueue`).

**Comment by dragunoff** [comment]
@pchote What I'm suggesting is not a fundamental change. It's only a modifier for pushing an item to the top of the queue - **after** the currently produced item and **without** pausing anything. This is not a fundamental change but a time-saver and a usability improvement. And as others have pointed out this would make specialty units (engies, spies, hijackers, etc.) used more often as you would not have to cancel your whole queue just to train a single E6.

@matjaeck The production UI is a whole other question that IMO deserves a separate ticket. Right now it's not very user friendly as the production commands and shortcuts are not exposed to the UI.

**Comment by pchote** [comment]
@dragunoff: indeed. I was referring to the original proposal!

**Comment by pchote** [comment]
That would be best

**Comment by matjaeck** [comment]
@dragunoff Right, let's continue this in separate issues. I don't think this ticket here serves any purpose anymore. Please open a ticket with your proposal :)
