### ISSUE TITLE
Change the random placement of mines to a sequential placement

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#15727]
I suggest changing to random placement of mines in a minefield, to a sequential placement, from the first specified point, to the second one. 
 
Currently, minelayers lose so much time going randomly from one cell to another. To avoid that, you currently have to specify small patches by small patches, which often results in forgetting idle minelayers / or adding too much micro, which is probably why nobody uses minelayers.

Also, choosing the direction (first point to second point) could be related to which area the player wants to protect first.

If this results into buffing minelayers too much, nerfing another property of minelayers could be considered : speed, number of mines, ...

**Comment by pchote** [comment]
The current minelayer UI is pretty bad for discoverability and consistency with other game mechanics, and the implementation needs a complete rewrite (once a solution to the first two points can be found).  Ideally we would replace the current system with something completely different, but I don't have any useful ideas as to what.
