### ISSUE TITLE
RA has Fatal Error and Will Close

### ISSUE THREAD

**Issue by hallodome** [OpenRA/OpenRA#15733]
<!--
 Each time I try to play, it says that Red Alert has fatal error and will close. It gives me the option to check the logs, but they are empty. I have tried to uninstall and reinstall five times. Please help!
I am on Windows 10. I am using the most recent version. I have the same error for Dune and Tiberian Sun.

**Comment by abcdefg30** [comment]
Can you please upload the exception log OpenRA created?
(See https://github.com/OpenRA/OpenRA/wiki/FAQ#my-game-just-crashed for the location of the logs folder.)

**Comment by abcdefg30** [comment]
Closing because of lack of information.
