### ISSUE TITLE
[bleed] Crash occurs when queue ordering reusable engineer after production exit.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#15734]
Log: https://pastebin.com/2XBqZd5L

I can't seem to pin down the exact reproduce steps and for whatever reason can't reproduce this in debug mode.

Rally point your barracks/tent to a distance, spam queue orders from the first rallypoint move-order. You'll probably want 'explored map: on' and fastest gamespeed to save you time. 'Reusable Engineers: on' off course.

**Comment by pchote** [comment]
Duplicate of #15697 which luckily we know exactly how to solve.
