### ISSUE TITLE
Add the ability to queue an item after the currently produced item

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#15752]
Moving here my comments from #15729 

This is a suggestion to improve the usability of the production queue by adding the ability to queue an item(unit/building) at the top of the stack (after the currently produced item).

For example starting with this stack:

```
# In progress:
E1
# Queued:
E1, E1, E3, E1, E1, E3, etc.
```

The player uses a modifier, say `Alt + click`, to insert a unit at the beginning of the queue resulting in this stack:

```
# Still in progress:
E1
# Queued:
E6, E1, E1, E3, E1, E1, E3, etc.
```

If the player would like to start construction of the inserted unit right away, they should manually cancel the "in progress" unit (i.e. this is the standard behavior of the queue).

This is not proposing a fundamental change to the way the queue works but a time-saver and a usability improvement. And as others have pointed out this would make specialty units (engies, spies, hijackers, etc.) used more often as you would not have to cancel your whole queue just to train a single E6.

**Comment by pchote** [comment]
Duplicate of #11726?

**Comment by dragunoff** [comment]
Yes, it's a duplicate - I knew I've seen that somewhere. We are both describing the same behaviour - "I want it next" for placing a priority unit before the rest of the queued units.
