### ISSUE TITLE
Desert rocks and buildings are blinking

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#15759]
Palette 'desert' should be added to RPE@desertwater and excluded from the LPR.
https://github.com/OpenRA/OpenRA/blob/b1e87e4f60175cf753697d890c0a299c202e65cf/mods/ra/rules/palettes.yaml#L107
https://github.com/OpenRA/OpenRA/blob/b1e87e4f60175cf753697d890c0a299c202e65cf/mods/ra/rules/palettes.yaml#L111
v21, v24 - water doesn't animate without RotationPaletteEffect.
v20, v29, rock3, rock5, rock6, rock7 = blinking from LightPaletteRotator.
![blinking_desert](https://user-images.githubusercontent.com/22008761/50932167-cb1b6000-1432-11e9-89ee-83712e2bc525.gif)

**Comment by MustaphaTR** [comment]
IIMO desert buildings should use the desert palette, regardless of the terrain. Not that anyone would want to use them on non-desert tileset, but still better for them to look correct on other tilesets too.

So the desert palette should be fixed so it is the same as terrain-desert.
