### ISSUE TITLE
Allow Primary building to be set by hotkey

### ISSUE THREAD

**Issue by avalach21** [OpenRA/OpenRA#15766]
It would be nice if your primary production building could be set via a hotkey.  I am not sure if this should be a separate hotkey or if this could be done using the Deploy hotkey.

I currently cant think of any conflicts where a structure has a deploy function as well as a production function..  Only MCVs and Pillboxes come to mind as structures with deploy functions, and neither of those would ever have to be set as a primary building.

ConYards in Dune2k can be set as primary, but there is currently no redeployable MCV implemented in D2K so again no conflict.

IMO it would feel intuitive to use Deploy to set a primary building (I tried it yesterday half expecting it to do it) but at the same time it is nice to have the abilities be separated if necessary somewhere down the line.  For example I currently wish return to base for aircraft was a separate hotkey from deploy as I wanted a unit to have separate hotkeys for these functions on a mod map I was working on.

So I am sure during modding someone would have a redeployable production building.. in fact I think Nod had one of those in the Firestorm expansion.. so it's settled lol. I recommend it be implemented as 2 separate hotkeys :-D

**Comment by abcdefg30** [comment]
FWIW, there already is a hotkey (kind of): Press ctrl while setting a rally point to make the structure primary.

**Comment by avalach21** [comment]
Ahh that's interesting :-)  Definitely will find it useful in normal play.  I am doing a mod map where changing primary structures quickly would be useful.  This is def a bit quicker but I'd like to be able to do it without using the mouse at all

**Comment by dragunoff** [comment]
Duplicate issues: #13820 and #12428
