### ISSUE TITLE
openra

### ISSUE THREAD

**Issue by markourb10** [OpenRA/OpenRA#15777]
cinematics fix patch for red alert openra tiberium sun dune 2000 please help

**Comment by Phrohdoh** [comment]
Can you expand on what help you're looking for, exactly?

**Comment by markourb10** [comment]
for cinematics fix in game red Alert tiberium dan and dune 2000 cinematics and audio ot working in breafing and so on

**Comment by fruestueck** [comment]
Have you downloaded the additional content via "Manage Content" in the main menu?

**Comment by matjaeck** [comment]
@markourb10 Could you give us a update about the issue? The provided information does not suffice to identify and fix your problem so without further details it is likely that the issue will be closed.

**Comment by abcdefg30** [comment]
Closing because of the lack of information.
