### ISSUE TITLE
Why do you use lua instead of C# itself as script language?

### ISSUE THREAD

**Issue by rolandwu777** [OpenRA/OpenRA#15795]
Hi,
 I am a non-gaming software engineer.  I am doing a softswitch (VoIP phone) system running on Windows . My main language is C++. I use a little bit of C#. I downloaded OpenRA and built it with/without Visual Studio 2013. I was debugging and reading through the code. This is really a impressive project. The code is nice and clean. Compile it just takes less than 30 seconds on my old Windows PC. It is really nice project. 
I saw many lua files. Later I figured these are something called "lua" scripts. I was wondering why you don't just use C# directly by replacing these lua script files with C# files. I was surprised why I could build OpenRA without downloading Visual Studio 2013, but then I realized there is a built-in csc.exe in .net framework. You could use the built-in csc.exe to compile these C# 'script' to different .dlls and load into openra. It is much easier to debug and read code using Visual Studio.

Thanks,
Roland

**Comment by abcdefg30** [comment]
I think the idea was to use a language that does not need to be compiled, so scripts can easily be distributed together with custom maps. Allowing anyone to add their own dlls and reference/execute them from maps sounds like a security risk to me.

(Looking it up I just found https://github.com/OpenRA/OpenRA/issues/2292#issuecomment-12283930, https://github.com/OpenRA/OpenRA/issues/2067 and https://forum.openra.net/viewtopic.php?f=83&t=15510 if anyone is interested in digging around in OpenRA's history. ^^)

**Comment by matjaeck** [comment]
@rolandwu777 can we close this?

**Comment by pchote** [comment]
I don't think so.  There is certainly a usecase for supporting external debuggers, but I have no feeling for what would be required to support this or whether it is even technically feasible considering the C#-Lua bridging.
