### ISSUE TITLE
[Bleed] Starting a multiplayer game with bots causes desync.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#15794]
This happens with dedicated or local. 2+ players with bots crash the game.

[exception-2018-11-05T225423Z.log](https://github.com/OpenRA/OpenRA/files/2550941/exception-2018-11-05T225423Z.log)
[syncreport-2018-11-05T225423Z.log](https://github.com/OpenRA/OpenRA/files/2550946/syncreport-2018-11-05T225423Z.log)

I assume it's related to https://github.com/OpenRA/OpenRA/pull/15750

**Comment by pchote** [comment]
Right, of course.  Doing this exclusively with conditions isn't going to work. The Activate call was important because we need the trait to only be enabled on the player controlling the bot :sweat:

**Comment by reaperrr** [comment]
I *think* this is actually an easy fix, `GrantConditionOnBotOwner` appears to work fine so we could just drop granting a condition from HackyAI in favor of using the former.
