### ISSUE TITLE
Upgrading Modded Map Failed

### ISSUE THREAD

**Issue by Zjordy** [OpenRA/OpenRA#15817]
hi
 i have a problem when i updated my map
 when i upgraded it from previous version to latest version it failed
 http://resource.openra.net/maps/29501/ 
 Title: OpenRA Resource Center - Map details - Civillian Outrage 99.21

does anyone know where the problem is? the lint check says something about duplicate RenderSprites. but i cannot find that anywhere

greetings, Zjordy

**Comment by abcdefg30** [comment]
Looks like this was a bug in our yaml files. This was fixed for the next version by #15429. You can try avoiding the use of `V19.Husk`, otherwise you will have to wait for the next release.
