### ISSUE TITLE
Incorrect chance calculations

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#15827]
We have at least two places that use `100 / chance` as a basis for resolving a probability.  Because we use integer division, any chance > 50% will be evaluated as 100% (100 / 51 == 100 / 100 == 1)

https://github.com/OpenRA/OpenRA/blob/bb536ee4fcf0e5d5afd6cf2537fd92b76db059cf/OpenRA.Mods.Common/Traits/Infantry/ScaredyCat.cs#L87

https://github.com/OpenRA/OpenRA/blob/0fca984463f29fec38bb9d21aea93c520b8ae001/OpenRA.Mods.Common/Projectiles/Missile.cs#L420

**Comment by JColstrom** [comment]
This bug is still a bug in current bleed branch

**Comment by abcdefg30** [comment]
This was fixed in #17770.
