### ISSUE TITLE
Turreted deployable actors require Turreted->InitialFacing to match GrantConditionOnDeploy->Facing otherwise the actor cannot undeploy.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#15831]
Regression from #15485.

This breaks GrantConditionOnDeploy->Facing=-1 cases.

**Comment by pchote** [comment]
The issue is not with InitialFacing/Facing. The real issue is that `WaitForTurretAlignment` doesn't work at all for units that have Turreted.RealignDelay > 0.
