### ISSUE TITLE
Red Alert: Bug in scg02ea when enemy is destroyed before convoy leaves

### ISSUE THREAD

**Issue by ManuGithubSteam** [OpenRA/OpenRA#15837]
### Issue Summary

In the second Allies mission "Five to one" there is a bug:
The mission does not end sucessfully when you manage to kill all soviet units/buildings BEFORE the convoy leaves the map. This leaves the game playable and it does never end.

My guess is:
There is a condition for checking for destruction of a building or unit after the convoy leaves. And if there are not anymore left, the game is won. But if there is nothing to destroy anymore you can never reach that condition.

#### System Information
- **Operating System:** Arch Linux x64
- **.NET / Mono Version:** not installed
- **OpenRA Version:**  release-20180923
- **Mod:** Red Alert

#### Additional Information:
- Steps to reproduce
	1. Rush to the base and start killing
	2. While you do that build some units and kill the guards on the way of the convoy
	3. Make sure you destroy all builds before the convoy leaves the map.

### Replay

[OpenRA-2018-11-16T114750Z.orarep.zip](https://github.com/OpenRA/OpenRA/files/2596818/OpenRA-2018-11-16T114750Z.orarep.zip)

#### Info:

I will look into it myself as i want to help with making missions but i just want to catalog it here.

**Comment by abcdefg30** [comment]
You forgot to kill one soviet standing in the top middle:
![grafik](https://user-images.githubusercontent.com/7704140/50766706-82b94200-127a-11e9-8898-2e7a44302bbf.png)

It probably makes sense to let all surviving units attack once the base is destroyed.
