### ISSUE TITLE
Team colors in "All Players" spectator mode

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#15833]
Currently, while spectating team games in "All Players" view, "player stance color" show all players as beige. 

It would be interesting to have an additional toggle that shows each team in a different, predefined color. (colors in : minimap + health bars)

Colors could be predefined as : Red, Blue, Green, .... / or using the standard RA colors.

**Comment by matjaeck** [comment]
Related to #15027.

**Comment by FRenzy-OpenRA** [comment]
Yes indeed, haven't found it in search bar.

**Comment by matjaeck** [comment]
This is also an issue ingame, the radar widget shows wrong colors too. This was already the case in 20180309.

**Comment by dragunoff** [comment]
Duplicate of #7497 ?

**Comment by Mailaender** [comment]
Duplicate of https://github.com/OpenRA/OpenRA/issues/2462
