### ISSUE TITLE
Stopping a unit in a tunnel makes it emerge through the ground above it

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#15853]

**Comment by matjaeck** [comment]
Related: #13239 for the question if units in tunnels should accept orders.

**Comment by mazarf** [comment]
Is it the emerging that's the issue or is it just that we shouldn't be able to stop a unit in the middle of the tunnel?

**Comment by pchote** [comment]
Emerging is the issue - this is a regression.

**Comment by MustaphaTR** [comment]
This seems to effect high bridges too. Not tested in TS but seems to be case in RA2.

**Comment by mazarf** [comment]
I found that Move.Cancel was clearing the movement path for a unit after I issued a stop.  Based on the discussion in #13239, this doesn't seem right.  After adding a layer check for this line, the unit moved through the tunnel uninterrupted.

Move.cs:154-155
```
if (path != null && self.Location.Layer != CustomMovementLayerType.Tunnel)
	path.Clear();
```
