### ISSUE TITLE
Sticky targeting: trying to move away from an object and the previous attack move command stops it.

### ISSUE THREAD

**Issue by Barrylyndon1** [OpenRA/OpenRA#15854]
A number of players have noticed the same thing, where you are clicking repeatedly and unnecessarily for a new order to cancel the previous one in order to, in the situation, move away. 

"Dropped orders" 

Unfortunately I cannot suggest any solutions, but it might have been revealed since the unit responsiveness is much higher, since this current release. 

Thanks

N/a

**Comment by matjaeck** [comment]
#14822
