### ISSUE TITLE
It is possible to Debug lua using ZeroBrane?

### ISSUE THREAD

**Issue by rolandwu777** [OpenRA/OpenRA#15852]
Hi,
 It seems OpenRA is using lua51.dll. I tried to enable lua debugger by inserting "require('mobdebug').start()". It will be like this:
WorldLoaded = function()
        require('mobdebug').start() <------------ but it does not work.
	player = Player.GetPlayer("Harkonnen")
	atreides = Player.GetPlayer("Atreides")

But it does not work. Basically, I think [require('mobdebug').start() ] will send a debug connection to IP 127.0.0.1 port 8172 back to ZeroBrane debugger. If it works well, it should be able to set break point , check call stack and watch variables. It will be very cool.

Inserting require('mobdebug').start() in a simple lua code running under lua.exe does work with ZeroBrane out of box. 

Roland

**Comment by rolandwu777** [comment]
For game players, security is critical. However, for a map/mission developer, a debugger should be useful. I could develop a much complicated map/mission with it. Don't know if there is a easy switch to turn on lua debugger. Also, I will be super excited for some time if I could figure out a way to use the debugger to debug lua script on openra.  :-D
Maybe I should dig into openra's source code to understand lua and C# integration.

Roland

**Comment by rolandwu777** [comment]
I spent many hours today to debug into C# code. I kind of make debugging using zerobrane on OpenRA working. However, it is not as good as visual studio. Here are some steps:

You will need to know how to remote debug a 'hello world' program on a regular lua program running on lua.exe first. 
https://studio.zerobrane.com/doc-remote-debugging

Here are some places need to be modified: [Warning:These modification will cause some security breach on sandbox] 
1. In scriptwrapper.lua
change package.path to
package.path = GameDir .. "/lua/?.lua;" .. package.path

2. In sandbox.lua 
add "require" after "xpcall"
It may popup more are missing variable or api in visual studio output window. You can just add them there.

3. string.rep is overwritten by OpenRa, it caused some issue when you want to watch display variable. 
in \zerobrane\lualibs\mobdebug.lua
change  local prefix = string.rep(indent or '', level)
to	  local prefix = ''

4. After that you can insert 'break point', require('mobdebug').start() in your lua script.

WorldLoaded = function()
  ....
  require('mobdebug').start() 
  ...


Roland

**Comment by MarkL4YG** [comment]
Maybe a development mode for creating/editing maps would be useful as a trade-off between end user security and being able to debug scripts as a map developer.
