### ISSUE TITLE
Compiling and Building Documentation Bug

### ISSUE THREAD

**Issue by JColstrom** [OpenRA/OpenRA#15867]
### Issue Summary
While attempting to contribute to OpenRA with some friends, we found an issue in the original Compiling and Building documentation. There was a missing step for adding an adapter in order to run tests in the test suite. 

#### System Information
- Windows 10
- Visual Studio 2017

#### Additional Information:
- Steps to reproduce
	1. Follow the steps to download and install the source code from a base level (no previous 
        installation) found here: 
        https:// github.com/OpenRA/OpenRA/wiki/Compiling
        2. Build the game in Visual Studio 2017.
        3. Open the Test Suite using the top menu bar, Test -> Windows -> Test Explorer.
        4. Try to run all tests. (this will fail due to missing adapter)

#### Solution!
The solution to this issue is actually pretty simple, even though it was pretty difficult to find originally. In the solution explorer which should be on the right hand side, right-click the solution name and choose Manage NuGet Packages for this Solution. In the NuGet - Solution tab, in the Browse tab, search for "Nunit3TestAdapter" and install it. Doing this will allow the test suite to run perfectly fine but this was missing from any documentation.

Please add this solution to the Compiling documentation directly underneath "If you'd like to edit or compile the source code using Visual Studio:" in one of the bullet points (Within the 'Windows' section).

**Comment by matjaeck** [comment]
> 4. Try to run all tests. (this will fail due to missing adapter)

> In the NuGet - Solution tab, in the Browse tab, search for "Nunit3TestAdapter" and install it.

Can someone confirm this before we add it to the wiki?

**Comment by RoosterDragon** [comment]
This is correct.

Note: This adapter still works in VS2019 for now, but the official advice is to now use nuget packages for test adapters instead.

See https://marketplace.visualstudio.com/items?itemName=NUnitDevelopers.NUnit3TestAdapter for more.

**Comment by abcdefg30** [comment]
Added a note to [https://github.com/OpenRA/OpenRA/wiki/Compiling](https://github.com/OpenRA/OpenRA/wiki/Compiling/_compare/cb4ff4e2f52d19692059f08f31de927d28647660).
