### ISSUE TITLE
A more bug free diplomacy solution

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#15862]
Ive seen a lot of free for all games ending up with players making agreements not to attack each other, in order to survive, there even times that players agree on sharing mcv's, give supply trucks, allow spies to pass in order to acquire ranks from production buildings, and even chrono mcv's in safe locations in the map in order for their "ally" to survive! 

Fragile alliance was removed because it had bugs, tho a lot of people dislike the idea of removing it (including my self).

A half finished idea came to my mind on how I could solve this, and have some form of working alliance mode.
The idea was to add on every weapon a new valid and invalid target, the weapons will change based on conditions in order to add or remove the valid\invalid targets. 

So in essence if a player was to receive a special "ally" condition, his units would be unable to target players who also receive the same condition.
For example if player 1 has condition "team a" and player 2 has condition "team a" they both wont be able target each other.
The alliances would have been form with the use of a hackish way, like training an invisible unit that would set the condition requirements to true.
Then if the players wanted to break the alliance they would build an other invisible unit that would remove the invisible unit, by the use of conditions again (DamagedByTerrain condition).

But then there is the problem of sharing visibility, and I can't think of a way of solving that.

So I was thinking since this is beyond my ability's maybe the devs would like to make a new and simple diplomacy system where the players can use in ffa games. 

This new (bug free) diplomacy could be a very basic thing like not attacking and sharing visibility. More like being a neutral. This could be a gray out lobby option that is interactable only if teams are not set in the lobby, So it would be a free for all only thing.

I am sure that if as a community like this idea and the devs are willing to work on this, we will get a nice feature for the game. So share your opinion here.

**Comment by KOYK** [comment]
Just to clarify a quote from discord, also sorry for my english.

1:57 AM] dragunoff: but you are talking about building invisible actors? or is that about the underlying implementation?
[2:20 AM] ELoyros: No sorry I mean that because adding diplomacy using hackish ways with just traits is near imposible, the devs can implement a simple diplomacy using actual code

**Comment by dragunoff** [comment]
To further clarify on discord I was commenting on the UI. I think if diplomacy is to be brought back it should have an intuitive in-game UI.
