### ISSUE TITLE
Map Editor - Ore overlay's sprite becomes offset

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#15886]
Not exactly sure what triggers this bug ( zoom/dezoom ? randomly ? ), but with time the position of the Ore overlay sprite gets offset.
![2018-12-04 18_23_53-openra](https://user-images.githubusercontent.com/20139967/49502841-43ac6100-f876-11e8-9f5c-5a033d1da56a.png)

The current workaround is to show the grid and the blue square. 
Also, closing and reopening the map resets the position.

**Comment by PunkPun** [comment]
This doesn't seem to be an issue on bleed
