### ISSUE TITLE
Map Editor - Some actors aren't copy pasted 

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#15896]
Two actors do not copy/paste in the Map Editor : player spawns, and flares.

**Comment by rob-v** [comment]
It happens for actors with OccupiesSpace: false which have no Footprint (CAMERA, FLARE, mpspawn, waypoint).
Actors to copy are not found in cellMap. I am not sure how to get it from screenMap based on CPos cell.
