### ISSUE TITLE
Add RequiresCondition property to GainsExperience

### ISSUE THREAD

**Issue by Smittytron** [OpenRA/OpenRA#15901]
Now that `Passenger` has `CargoCondition` we can look at the long requested removal of experience gain inside pillboxes. If I'm reading things right, `GainsExperience` would need a `RequiresCondition` property to make this a reality.

**Comment by GraionDilach** [comment]
You can already add GainsExperienceMultiplier: 0.

**Comment by Smittytron** [comment]
Hmm, the traits list isn't as alphabetical as I thought.
