### ISSUE TITLE
Servers with disabled spectators won't allow players to join

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#15926]
Some times if you disable spectators in a server, players will be unable to join in that server.
How to reproduce: 
1) Join server and disable spectators.
2) Ask some one to join the server with you.

**Comment by pchote** [comment]
Reproduced.

**Comment by pchote** [comment]
Regression from #15823 - slot is no longer set at the start of `ValidateClient`, so `IsObserver` (which evaluates as `slot == null`) is always true.
