### ISSUE TITLE
UPnP NatDiscoveryTimeout is too low for some routers

### ISSUE THREAD

**Issue by andreabisello** [OpenRA/OpenRA#15923]
Hi
my router has upnp enabled,
other games and emule or torrent opens port by upnp,
i installed the last version,
but still impossible to create server online because of port closed.
i can manually forward the port, but upnp support has something wrongs.
i saw old messages about this problem, but was closed years ago.
thanks

**Comment by Mailaender** [comment]
Can you upload your `nat.log` file?

**Comment by abioneperhobby** [comment]
[nat.log](https://github.com/OpenRA/OpenRA/files/2710411/nat.log)

i read the log.
i deactivated antivirus (bit defender) but nothing changed.

**Comment by abioneperhobby** [comment]
i solved giving more time for upnp activity, adding the NatDiscoveryTimeout: 5000 row.

![image](https://user-images.githubusercontent.com/2149815/50449818-02b1e480-092a-11e9-9a45-263fcedbc6a0.png)

now it work.

maybe the default value (1000ms) is not enought.

**Comment by obrakmann** [comment]
That's probably device-dependant. What kind of router are you using?

**Comment by abioneperhobby** [comment]
it's the default router given with the italian "Infostrada - Wind" company.
this is the manual
https://www.infostrada.it/fileadmin/Materiale/guidemodem/Manuale_HL_HUB.pdf
it should to be the ZYXEL VMG8825 
![image](https://user-images.githubusercontent.com/2149815/50486536-c13d3a00-09fa-11e9-8106-0bff138c1026.png)
