### ISSUE TITLE
Planes without the Rearmable trait can't exit from a FlyAttack activity gracefully on their own when they targeted the ground.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#15948]
Pausing the armaments and/or disabling the attack trait still keep the plane within the FlyAttack activity. Disabling the armaments crashes on https://github.com/OpenRA/OpenRA/blob/224377f07891693fedd667197c79fca5d77fcafb/OpenRA.Mods.Common/Activities/Air/FlyAttack.cs#L63

**Comment by GraionDilach** [comment]
This is also a regression btw, because they could a while ago and https://github.com/GraionDilach/OpenRA.Mods.AS/blob/master/Traits/SupportPowers/AirstrikePowerAS.cs literally worked based on that alone. Notsure when it regressed though.

**Comment by pchote** [comment]
What is the expected behaviour here?

**Comment by GraionDilach** [comment]
The aircraft starts idling and/or follows the next activity queued if it's `AttackAircraft` trait gets disabled.

Note that I haven't tested this since a month or two ago so this might received a fix already.

**Comment by pchote** [comment]
Fixed on bleed: the aircraft goes idle when `AttackAircraft` is disabled.

**Comment by GraionDilach** [comment]
Yep, just confirmed. Thank you.
