### ISSUE TITLE
Sequence facing bug

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#15950]
While testing the Nod10 missions, I noticed something is wrong with unit facings. This is particularly noticable with the Nod Artillery: When ordered to shoot ~noth-north-east, it will display the straight north facing, for example.

It's also somewhat noticable on vehicle L- and U-turns, if you look closely. They 'glide' more than ever before.

Probably a regression from #15936.

**Comment by GraionDilach** [comment]
Isn't this basically ClassicPredictionFudge?

**Comment by pchote** [comment]
ClassicFacingFudge is supposed to be symmetrical, and only fudges 1 frame, not 4.
