### ISSUE TITLE
Harvesters will sit idle after filling up until a spot is available for them (bleed)

### ISSUE THREAD

**Issue by Smittytron** [OpenRA/OpenRA#15960]
Testcase: Build one ref and 10 harvesters. A ref can only take three at a time while the others will sit in the ore patch after filling up.
Ideally ore trucks will head back to the ref before deciding which one gets to drop off resources first. Sitting in the ore field leaves them very vulnerable to attack.

**Comment by FrameLimiter** [comment]
https://github.com/OpenRA/OpenRA/wiki/Traits#harvester ->MaxUnloadQueue
It's to prevent overcrowded blockages at the refinery.

**Comment by Smittytron** [comment]
Apparently this isn't new to bleed. I can't begin to wrap my head around how I've never seen this before. It seems mathematically impossible with as much as I've played.

**Comment by pchote** [comment]
IMO it would be worth keeping this open as a discussion point for improving this behavior (if needed).
