### ISSUE TITLE
Add a function that will remove curently selected unit from its unit group

### ISSUE THREAD

**Issue by Falkvard** [OpenRA/OpenRA#15961]
It would be handy to be able to remove selected units from a unit group (ctrl+1~ctrl+0 groups) instead of selecting desired units and creating the group again.

**Comment by MustaphaTR** [comment]
I'm pretty sure a unit can't be in multipile groups at the same time.

**Comment by Falkvard** [comment]
The example of situation I had on my mind was: You have units defending your base and you have them in a group. You are under attack and don't have much time for micromanagement. Some of the units are damaged. You select them and move them to the repair bay, away from the combat. Then you want to select the rest of the unit group and give orders. So my idea was that as I order the damaged units to go for repairs, at the same time I would hit some key to remove them from the combat group.
It is of course possible to set them as another group, but I'm afraid that would only create mess.
