### ISSUE TITLE
Bundle Mono inside AppImage

### ISSUE THREAD

**Issue by probonopd** [OpenRA/OpenRA#15965]
### Issue Summary
AppImage says

![mono](https://user-images.githubusercontent.com/2480569/50542544-e4611880-0bb7-11e9-8589-e998644014f2.png)

As per [the AppImage philosophy](https://docs.appimage.org/introduction/concepts.html), an AppImage should bundle everything that is needed to run the application, such as the subset of the Mono runtime which is required to run OpenRA. The result is that you can copy an AppImage from one system to another and it will "just work", without having to download additional packages and without going online.

#### System Information
- **Operating System:** Linux
- **.NET / Mono Version:** None
- **OpenRA Version:** OpenRA-Red-Alert-x86_64.AppImage
- **Mod:** OpenRA-Red-Alert-x86_64.AppImage, but likely also others

#### Additional Information:
- Steps to reproduce
	1. Run e.g., `xubuntu-18.04-desktop-amd64.iso`
	2. Download `OpenRA-Red-Alert-x86_64.AppImage`
	3. Make it executable and run

**Comment by probonopd** [comment]
Using this [mono.yml](https://github.com/AppImage/pkg2appimage/blob/master/recipes/mono.yml) recipe, Mono 5.18.0.225 gets bundled. I don't have enough clue about Mono to make OpenRA work with it, though.

**Comment by pchote** [comment]
This is something i've been thinking about for a while, but only recently started filing issues about.

My current plan, hopefully for Next + 1:
* [Remove the dependency on System.Drawing and libgdiplus](https://github.com/OpenRA/OpenRA/issues/15955)
* Package the `mono-5.10.0-debian-7-x86` runtime from https://download.mono-project.com/runtimes/raw/ (the last version that Microsoft provide deb-7 builds for)
* Resurrect our old [recursive library detection script](https://github.com/OpenRA/OpenRA/blob/4c8575b1f53d5bff8b2e92e905dfe2f982f8c9f3/packaging/osx/package.sh) to identify the managed libraries we need to ship
