### ISSUE TITLE
AI can't handle frozen actors

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#15967]
They don't cancel their attack order, but also don't move towards them, causing squads to get stuck until the frozen actor is somehow revealed again.

**Comment by pchote** [comment]
Have you identified which part of the code has this problem?

**Comment by pchote** [comment]
I'd really like to fix this ASAP, but unless this is a trivial fix (i'm still hopeful it is) then IMO my comment in #15966 should apply here too.

**Comment by reaperrr** [comment]
> Have you identified which part of the code causes this?

I haven't, though my guess/hope would be that we just need to update the States to treat a FrozenActor like an Actor for attack decisions.

**Comment by pchote** [comment]
I'd start by looking for places that use `World.FindActorsInCircle` and then create `Target`s from the results.  These cases should be updated to also query `FrozenActorLayer.FrozenActorsInCircle`.

**Comment by pchote** [comment]
https://github.com/pchote/OpenRA/commit/8f95fd91f14ae6284632e26a6546fe6a0eac45d1 is as far as I got before giving up.  Theres still a nontrivial amount of work before it will compile, let alone work.

Bumping to next + 1 because I can't see any way to complete this sooner.

**Comment by pchote** [comment]
I was hoping that something like this would work as a temporary bodge for the target-sticking issue:
```diff
diff --git a/OpenRA.Mods.Common/Traits/BotModules/Squads/Squad.cs b/OpenRA.Mods.Common/Traits/BotModules/Squads/Squad.cs
index 773e38fa59..1be6c5c6bd 100644
--- a/OpenRA.Mods.Common/Traits/BotModules/Squads/Squad.cs
+++ b/OpenRA.Mods.Common/Traits/BotModules/Squads/Squad.cs
@@ -11,6 +11,7 @@
 
 using System.Collections.Generic;
 using System.Linq;
+using OpenRA.Mods.Common.Activities;
 using OpenRA.Support;
 using OpenRA.Traits;
 
@@ -77,12 +78,12 @@ public Actor TargetActor
 
                public bool IsTargetValid
                {
-                       get { return Target.IsValidFor(Units.FirstOrDefault()) && !Target.Actor.Info.HasTraitInfo<HuskInfo>(); }
+                       get { return Target.IsValidFor(Units.FirstOrDefault()) && !Target.Actor.Info.HasTraitInfo<HuskInfo>() && Target.Recalculate(Bot.Player).Type == TargetType.Actor; }
                }
 
                public bool IsTargetVisible
                {
-                       get { return TargetActor.CanBeViewedByPlayer(Bot.Player); }
+                       get { return TargetActor.CanBeViewedByPlayer(Bot.Player) && Target.Recalculate(Bot.Player).Type == TargetType.Actor; }
                }
 
                public WPos CenterPosition { get { return Units.Select(u => u.CenterPosition).Average(); } }
```

... but it doesn't seem to help. This suggests that the problem is caused by the target calculation code continuously selecting the same invalid actors that then get dropped and reselected over and over.

**Comment by pchote** [comment]
c895d5bd4dc49a4d010d73e75e772a4ec40ef7c5 makes the bot cancel attack orders against invalid targets.  I'm sure you won't be surprised to find that the bots depend on the current bug to function at all - with this commit the bot's units will stay in their base and never move to attack others.

**Comment by reaperrr** [comment]
Could we, as temporary work-around for the upcoming playtests/release, instead make bots ignore Fog/Shroud? I'm aware that would be a behavior regression, but in my opinion still better than bot squads getting stuck all the time.

**Comment by pchote** [comment]
Could work, maybe with an explicit bot check in `TargetExts.Recalculate`?
