### ISSUE TITLE
Make GUI Scale Inline With Pixel Multiplication

### ISSUE THREAD

**Issue by muchweb** [OpenRA/OpenRA#15964]
All this could be optional, but I would like to see this option.

**Currently:**
When pixel doubling is enabled, only map, and optionally cursor pointer are scaled.

**Expected:**
When pixel doubling is enabled, map, optionally cursor pointer, all GUI elements such as menus, chat, health bars, radar should be scaled.

**Comment by pchote** [comment]
My comment in #15963 about enabling the HiDPI mode applies here too.

**Comment by muchweb** [comment]
Resolved by answer in #15963
