### ISSUE TITLE
Exclude dogs from bot squads

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#15966]
RA dogs are too squishy and useless against vehicles and buildings, so bots shouldn't include them in their attack squads. They're much better left at their base as defense against early inf rushes, or engineers and spies sent by human players.

Shouldn't be tackled before #15922 is merged, though.

**Comment by pchote** [comment]
If this isn't just a trivial yaml change then IMO we should defer this to Next + 1.  The new bot plumbing enables a whole range of AI improvements, but that plumbing itself is the main thing currently delaying the playtest.  I'd prefer it if we could limit the current cycle to getting the plumbing finished and debugged, and then focus on improving the gameplay behaviour for the next cycle as this by itself would be enough to justify a new release.

**Comment by reaperrr** [comment]
> If this isn't just a trivial yaml change

It is, though. We just need to add it to `ExcludeFromSquads`, no other changes are needed.
