### ISSUE TITLE
Make HarvesterManagerBotModule request harv replacements

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#15962]
After #15922 is merged, it will be rather trivial to make `HarvesterManagerBotModule` request harvesters being built if their number is below the number of refineries, making the AI a bit better at keeping/restoring their economy.

**Comment by reaperrr** [comment]
I'd like to get that into the playtest.

**Comment by pchote** [comment]
IMO my comment in #15966 applies here too, unless we end up in a situation where we are all waiting on non-ai changes to be finished as a blocker for the playtest.
