### ISSUE TITLE
Rally points do not work on construction yards (and cause harvs to get blocked)

### ISSUE THREAD

**Issue by ubitux** [OpenRA/OpenRA#15995]
Contrary to other buildings, construction yards do not seem to be target-able, leading to the following issue:

![cyard-rp](https://user-images.githubusercontent.com/34467/50683699-420bbf80-1013-11e9-8b33-1c3b40e5530c.png)

This is particularly problematic when the rally point is set to the first expansion, trickling units supposed to go there to defend it don't, army stays out of position.

This does not happen with other buildings:

![pp-rp](https://user-images.githubusercontent.com/34467/50683742-6c5d7d00-1013-11e9-86be-820e472ed431.png)

But is OTOH behaving the same as with an invalid rally point (this one is probably fine):

![invalid-rp](https://user-images.githubusercontent.com/34467/50683798-90b95980-1013-11e9-8aef-c89d09d3668b.png)

The issue is present in both `release-20181215` and bleed @ a77d2f15b1ad84ef5bbab609fc0f6d8d0119407a

**Comment by MustaphaTR** [comment]
Construction Yard is 4x3, if you don't count the bib it is 3x3 which has a cell that is complately covered by other impassable cells probably why the issue triggers with CY but not APP

**Comment by ubitux** [comment]
That's indeed probably the case: a rally point on the cells other than the center one of the 3x3 do work. You can also reproduce the issue while stacking a bunch of airport for example:

![building-stack-rp](https://user-images.githubusercontent.com/34467/50693530-80b37100-1037-11e9-9b35-bc9670505e5c.png)

Note that an explicit order will "work" (the units will find their place around the specified area).

**Comment by MustaphaTR** [comment]
Difference may lie between (Force)Move and AttackMove orders, since rally points queue an AttackMove order.

**Comment by ubitux** [comment]
A manual attack move is adjusted to an alternative point so a manual order gets honored. I understand that adjusting the rally point itself might be complicated, especially if a building is build after the point is set.

**Comment by ubitux** [comment]
Note that a side effect of this bug is causing some harv to get stuck if you're building a building on the default rally point of the war factory. Huge penalty in early game.

**Comment by ubitux** [comment]
Yet another situation where the rally point "bugging" out:

![rally-wf](https://user-images.githubusercontent.com/34467/53088646-a4a91400-350a-11e9-9bc6-67b7184d22f9.png)

**Comment by ubitux** [comment]
Here is a gif to illustrate the difference between move and a-move:

![move-vs-amove](https://user-images.githubusercontent.com/34467/54884721-853c3880-4e74-11e9-974e-4da980e42581.gif)

Since a rally-point is a non-adjusted a-move, this might be the cause of all of this.

**Comment by abmyii** [comment]
Since, the issue has got worse - any building will now block the units.
