### ISSUE TITLE
Replaying a crashed game throws a DivideByZeroException on the replay percentage tooltip.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#15992]
It throws on https://github.com/OpenRA/OpenRA/blob/85a97998aad316a37f340b67d8f982fa2ada2278/OpenRA.Mods.Common/Widgets/Logic/Ingame/GameTimerLogic.cs#L69-L70

since TickCount is set, but FinalGameTick isn't.

Regression from #15704.

**Comment by pchote** [comment]
Not just crashes: this also happens if the player disconnects before somebody wins.

**Comment by pchote** [comment]
Repro case: Start a game, deploy MCV, quit, load replay, mouse-over timer.
