### ISSUE TITLE
Explicit harverster delivery order should be honored only once

### ISSUE THREAD

**Issue by ubitux** [OpenRA/OpenRA#15997]
**Current behavior**: if an harvester has an explicit delivery ordered to a distant refinery, it will keep doing that long distance mining forever. This is not a bug as is but desired as documented in the code `"NOTE: An explicit deliver order forces the harvester to always deliver to this refinery."` (`Harvester.cs`).

**Suggested alternative behavior**: an explicit deliver order should force the harvester to deliver to the targeted refinery only once.

The rationale being that, as far as I can tell, ordering delivery to a specific refinery happens in the following two scenarios:

1. an attack happens, harvs are ordered to go harvest somewhere else for a while by specifying a distant refinery
2. on the main base, the harv is micro-ed to harvest close ore patches. Then when the expansion is set up, one of these harv is sent to the expansion specifying a delivery on the expansion ref

In the first scenario, the player will likely forget the harv or might actually call back different harvs. This will cause the never-forgetting-harv to continue making a non-optimal path on the patch they're currently harvesting (think of a large multi mine ore patch with several refs, these harv will never pick a more optimal one).

In the second scenario, the harv will harvest back and forth between the explicit patches in the main base and the refinery expansion.

**Comment by ubitux** [comment]
I may add that in the 2nd scenario, things happening are actually even worse than expected: https://0x0.st/sRfO.mp4

**Comment by ubitux** [comment]
As pointed out on Discord, it makes sense to remember the refinery in multi-player mode, where you want to deliveries happening to an ally with your harvester. So if the deliver once is to be implemented, we probably want to remember the player to which it should deliver to when choosing the closest refinery.

**Comment by netnazgul** [comment]
Some notes from discord on this:

> 20:06] netnazgul: I generally don't like things that do some complex stuff behind the curtains and are only known to you if you actually know the code of it
> [20:08] netnazgul: maybe you can force-lock an ore truck to refinery with, I don't know, a ctrl+click
> 20:09] netnazgul: and also would be helpful if this ref lock is shown somehow. With a line or with a caption on the refinery
> [20:09] netnazgul: like selecting an ore truck you see "primary" for the refinery it is locked to

also

> 20:10] bµg: also: how do you roll back to non-ordered way?
> [20:10] bµg: except selling the ref

**Comment by matjaeck** [comment]
> I generally don't like things that do some complex stuff behind the curtains and are only known to you if you actually know the code of it

Indeed. Perhaps UI elements in a custom action bar for harvesters (explict delivery/closest ref) could help?
