### ISSUE TITLE
Hotkey widget UX improvements

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#16001]
The hotkey remapping widget is not very user friendly. There are several issues with it:
- There is no way for the user to cancel a remap in case of an input error 
- Hotkeys can not be cleared (set to an undefined state)
- An individual hotkey can not be reset to its default value
- There is no visual distinction between default and remapped keys
- Duplicate hotkeys can be set

Related issues: #14670, #3986, #13200

I will propose here a couple of approaches for how this widget can be reworked. 

### Inline variant
* **Rebind:** When clicking inside the input field the value starts blinking and a new hokey can be set
* **Accept:** A valid hotkey is automatically accepted
* **Cancel:** `Esc` key cancels the operation
* **Reset/Clear:** Reset and clear buttons are inside (or next to) the input as small icon-buttons; Default value is a slightly transparent color (like a placeholder); custom value is fully opaque; To reduce clutter these buttons should only show up when a remap is in progress;
* **Duplicate:** In case of a duplicate the input value changes to a red color and blinks until a proper key is set or the remap is cancelled
![default](https://user-images.githubusercontent.com/1355810/50712749-47045980-107b-11e9-9e34-90ec72743077.png)

### Dialog variant
* **Rebind:** When a hotkey input is clicked a dialog opens up; The dialog has buttons for all possible actions: _Clear_, _Reset_, _Accept_ and _Cancel_
* **Accept:**: Click _OK_ or press `Enter`
* **Cancel:**: Click _Cancel_ or press `Esc`
* **Reset/Clear:** Reset and clear buttons are inside (or next to) the input as small icon-buttons; Default value is a slightly transparent color (like a placeholder); custom value is fully opaque;
* **Duplicate:** In case of a duplicate a warning message is displayed in the dialog and the _OK_ button is disabled
![default](https://user-images.githubusercontent.com/1355810/50712723-2c31e500-107b-11e9-9502-02219be03e9c.png)

**Comment by pchote** [comment]
IMO the dialog variant is probably best, but I would replace the reset glyph with an explicit "Default" button to the left of OK / Cancel.

**Comment by dragunoff** [comment]
I also prefer the dialog variant because all actions are explicit. A minor downside is that it adds a step to the process which could make remapping multiple keys a little cumbersome.

I was actually thinking about moving both the _Reset_ and _Clear_ buttons out of the input and putting them next to _OK_ and _Cancel_. Like so:
![default](https://user-images.githubusercontent.com/1355810/50729070-24864500-113c-11e9-9bff-1846dcabf7cd.png)

Also thought about labeling all of the buttons, but that takes a lot of space and feels a little overwhelming:
![default](https://user-images.githubusercontent.com/1355810/50729131-27ce0080-113d-11e9-9d38-961a2a566ae4.png)

Or only the _Reset_ (default) button and leaving the _Clear_ button in the input:
![default](https://user-images.githubusercontent.com/1355810/50729158-a9be2980-113d-11e9-8bbc-d4dfda878304.png)

**Comment by dragunoff** [comment]
I've started working on implementing this. Actually made quite a bit of progress. I hope I'm on the right track, PR is on the way soon, here's a screenshot:

![openra-hotkey-remap](https://user-images.githubusercontent.com/1355810/57491778-cffbfd80-72c6-11e9-9250-b1172c13914f.png)

**Comment by dragunoff** [comment]
After discussions on #16524 and on discord it became evident that the modal dialog window UI is not the best approach here. I have reworked it into an inline dialog, but to open up space for it I decidet to move the hotkeys to a separate tab. Here's a screenshot:

![hotkey-remap-inline-dialog](https://user-images.githubusercontent.com/1355810/57914948-61a3d600-7898-11e9-95b6-230587a9548e.png)

@pchote Would this be considered for next release?

**Comment by pchote** [comment]
This is looking much better, although I think we'll need to refine the bottom bit - but i'm not yet sure exactly how.  If we can get this ready in time, I don't see why not.
