### ISSUE TITLE
Deploying harvesters would send them to the closest ore

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16027]
Deploying aircraft for them to rearm is a really good quality of life improvement, why not do the same for harvesters? If one issued a deploy order to a harvester it would go to the closest ore and mine it. It would be a small time/attention saviour.

**Comment by GraionDilach** [comment]
Some mods might want to have harvesters which use the deploy button for other options though. Like generating a temporary armor boost to protect them, etc..

**Comment by Punsho** [comment]
it could be conditional in yaml
