### ISSUE TITLE
Crash allies07 20190106

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#16020]
Crash on playtest 20190106
Allies07

Lua.log is just full with:
"pt 238 is not revealed for player USSR (0)!"

perf is filled untill 28xxx with:
"x ms [1279] Activity: CallLuaFunc"

**Comment by abcdefg30** [comment]
Another report can be found here: https://forum.openra.net/viewtopic.php?p=309632#p309632
