### ISSUE TITLE
Pillbox hits moving targets inconsistently

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16038]
The closer to a pillbox the moving target is the more hits it will take, atliest in the majority of times. I think that it is not intentional so I'm creating this issue. I made many tests and here's one of them 

![pillboxtests](https://user-images.githubusercontent.com/37534529/50837910-765de380-1365-11e9-8961-d82f16a5f469.gif)

This is not a big problem for RA because most fast units have enough health to ignore this but rather for other mods which also use this weapon type

**Comment by pchote** [comment]
Weapons are more accurate at shorter distances, so the burst will be tighter and therefore do more damage on the closer targets.

**Comment by Punsho** [comment]
Shouldn't the accuracy be perfect for a pillbox? Also it's a lot harder to balance it if it is that way

**Comment by Punsho** [comment]
Is there a particular reason why pill box has inaccuracy?

**Comment by GraionDilach** [comment]
This has nothing to do with accuracy. The Pillbox is using a fast Bullet projectile (which does not track) and delivers half of it's damage through delayed warheads (which doesn't track either).

**Comment by GraionDilach** [comment]
It's not that fast - https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/weapons/smallcaliber.yaml#L65.

OpenRA got such a projectile though, but it's called InstantHit.

**Comment by Punsho** [comment]
When I increase the projectile speed up to 6c0 then the pillbox hits the target more consistently and doesn't depend on the distance anymore. Is there any reason in particular for making the projectile slow?![ezgif-2-6cf838107677](https://user-images.githubusercontent.com/37534529/50884915-e7001100-13f4-11e9-87a7-51baaeea6419.gif)

**Comment by rautamiekka** [comment]
There's a better name for an instantly hitting projectile: hitscan.

**Comment by PunkPun** [comment]
This issue should have been closed when #16472 was merged
