### ISSUE TITLE
A few spelling errors

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#16049]
"agression" = "aggression"
https://github.com/OpenRA/OpenRA/search?q=agression&unscoped_q=agression
"offseted" = "offset"
https://github.com/OpenRA/OpenRA/search?q=offseted&unscoped_q=offseted

--
All lobby descriptions end without a period except these two:

Allow undeploying Construction Yard.
https://github.com/OpenRA/OpenRA/search?q=Allow+undeploying+Construction+Yard

Players without assigned spawn points will start as far as possible from enemy players.
https://github.com/OpenRA/OpenRA/search?q=Players+without+assigned+spawn+points+will+start+as+far+as+possible+from+enemy+players

--
All fakes end with the letter "F", except these two:

FPWR/FAPW = PWRF/APWF
https://github.com/OpenRA/OpenRA/blob/b1e87e4f60175cf753697d890c0a299c202e65cf/mods/ra/rules/fakes.yaml#L1
https://github.com/OpenRA/OpenRA/blob/b1e87e4f60175cf753697d890c0a299c202e65cf/mods/ra/rules/fakes.yaml#L227

**Comment by rmr1014** [comment]
I can take a shot at this if it's ok?

**Comment by MustaphaTR** [comment]
POWF would probably be better for fake power plant, since normal one's name is POWR.

**Comment by abcdefg30** [comment]
@rmr1014 sure, go ahead. I wouldn't change the actor names however, since that is a bit more complicated (we risk breaking maps and in theory the map importer). Do we really want to change those two internal names?

**Comment by deleted-user-1** [comment]
Actor renaming is probably not worth it but somebody could fix the "offseted" error, unless this was left unfixed intentionally since all the others have been fixed meanwhile.
