### ISSUE TITLE
Artillery moving into other artillery

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16047]
Noticed this bug in the most recent 5a stream, 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/37534529/50887057-d357a900-13fa-11e9-9150-0327cd38fdb9.gif)

[arty_bug.orarep.zip](https://github.com/OpenRA/OpenRA/files/2739922/arty_bug.orarep.zip)

**Comment by pchote** [comment]
It looked like the attack order cancelled the move order mid-way, leaving the arty between two cells. Probably another case of the long standing issues around #15632.

**Comment by reaperrr** [comment]
Yeah, the current `Move` should definitely not be cancellable until the actor has at least finished moving to the center of the current cell (or in case of infantry subcell).
