### ISSUE TITLE
Error message in the debug.log if you load any map in playtest-20190106

### ISSUE THREAD

**Issue by airetaM** [OpenRA/OpenRA#16058]
`Remote map query failed with error: File not found on remote server
URL was: https://resource.openra.net/map/hash/57b1f5905fedc3856c46bb464f0899e14c1327b6,7d502f7ccf34d4aa314cf84a8c2122b6876a6f06,ea9186a1b58e031e34ea165400b11bd7e0d96706,0b2a79b86ddd04965cf9d40ed31d76d623cc3ae9,d497e3c73b60459e3c8c53d25cb9cc21ad878a2c,57ed82ee3a4836d54c0dd05560b4e21cd3e338ba,9eba8007b1172db968df6e18bdf10c1626a65352,3d98009d3f66cdc9576a63876adce6140da9996c,c7a846ce63b1024aafc5db9e7408301b3a804a9c,d5defb1ccf6efe75da9c5b276439636a287c8fd6,b9a4ad8a52e5347940b5e569248cbdeee2935bc7,7dc591b6edfb58e580b6ed70c0b25fc7c012203b,720bdf0377abba2be7ed5fca70e19da2b0fd36d3,3a94af24afc3d43b59eecdff309bbe44c5047644/yaml`
The map will start normal but the message comes.

**Comment by PunkPun** [comment]
Couldn't reproduce
