### ISSUE TITLE
Map not found, not compatible, but pass on resource center

### ISSUE THREAD

**Issue by Zjordy** [OpenRA/OpenRA#16053]
i uploaded my map to resource center and it shows its compatible. When i try a multiplayer game on a random server it will give the error: map not found on server. When i create a server to try it then it says map not compatible.

this is the map:

https://resource.openra.net/maps/30306/

**Comment by Zjordy** [comment]
ah, that should be it, thank you , i didnt notice

**Comment by matjaeck** [comment]
@Zjordy Has your issue been solved?

**Comment by Mailaender** [comment]
Which Operating System do you run @Zjordy?
