### ISSUE TITLE
Minelayer requires Rearmable while not even using any such trait.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#16059]
This breaks minelayers which can refill themselves.

**Comment by MustaphaTR** [comment]
I said Minelayer shouldn't require Rearmable (thinking singe-use minelayers not auto-rearm) when it was added, but the response was that Minelayer trait is set up in a way specifically to use lay mines in an area, return, rearm, repeat process. Not the exact wording, but lazy to find the PR rn.

**Comment by GraionDilach** [comment]
The LayMines does TraitOrDefault lookups on Rearmable. It already handles the case.

**Comment by PunkPun** [comment]
closed by #21380
