### ISSUE TITLE
Dune2k German translation

### ISSUE THREAD

**Issue by Matthias84** [OpenRA/OpenRA#16062]
Hi, it would be cool, if the game engine would support german translation and mediafiles.

**Comment by abcdefg30** [comment]
Yes, it would be cool. :) Unfortunately, this is not trivial. We track progress at #10475 (so closing this as duplicate).

**Comment by abcdefg30** [comment]
Meanwhile you can try installing the files yourself using [this guide](https://gist.github.com/abcdefg30/a4fe1110c2727c3960e340ae2ce45bc0). However, you are on your own if something breaks.
