### ISSUE TITLE
"Add" tool for Map Editor

### ISSUE THREAD

**Issue by FRenzy-OpenRA** [OpenRA/OpenRA#16066]
The current "Copy/Paste" tool overrides what is inside the paste target. 

It would be extremely useful to have an "Add" tool that allows for adding elements, without overriding what's underneath. 

It would mainly add Actors and Resources, without overriding existing Actors and Resources. 

It would probably make use of the new filter functionality.

I'm not sure if it should use Terrain too, and how. Probably not necessary for now.

**Comment by pchote** [comment]
Cells can only have one type of resource, just like terrain.

**Comment by PunkPun** [comment]
With #20226 copy/paste is no longer a stamp tool
