### ISSUE TITLE
Bug with the "Make" command

### ISSUE THREAD

**Issue by Tr0lldr0id** [OpenRA/OpenRA#16070]
### Issue Summary
I'm trying to set up a new mod environment, and whenever I run the make command, it downloads some stuff from NuGet, and then gives me this:
make[1]: Entering directory '/home/tr0lldr0id/programming/OpenRA/OpenRAModSDK-20190106/engine'
Lua 5.1 library detection failed.
Makefile:306: recipe for target 'linux-native-dependencies' failed
make[1]: *** [linux-native-dependencies] Error 1
make[1]: Leaving directory '/home/tr0lldr0id/programming/OpenRA/OpenRAModSDK-20190106/engine'
Makefile:98: recipe for target 'engine' failed
make: *** [engine] Error 2

If I run the make command again, it skips the NuGet stuff and just gives me that. I tried to find the actual command it was running and run that manually from the terminal and got an unexpected token error, which, after some research led me here:
https://askubuntu.com/questions/372926/bash-syntax-error-near-unexpected-token
Don't know if that's relevant or not. 

I could run this command just fine a month ago, I know OpenRA got an update in there, and I also formatted Ubuntu between now and then as well. The launch-game script is also broken as of right now, but that's another issue that I think might be fixed with a new version of OpenRA.

... ... ...

#### System Information
Ubuntu 18.04
I don't know the .net or mono versions, or how to find out. Any help on finding that info is appreciated.
Having this error in both 20190106 playtest, and the 20181215 release
Red Alert
#### Additional Information:
- Steps to reproduce
	1. Run make command? I honestly don't know, with that format in there (which was just a few days ago) if anyone else even has this problem.

**Comment by pchote** [comment]
You will need to install the lua5.1 package, and possibly some of the other native dependencies listed on the [compiling](https://github.com/OpenRA/OpenRA/wiki/Compiling#linuxmac) page.

**Comment by Tr0lldr0id** [comment]
I did install it. Sudo apt-get install lua5.1. No errors. It's definitely installed on my system, is openra not finding it?
P. S. Thank you very much for responding so quickly.

**Comment by matjaeck** [comment]
Could you try it with `liblua5.1-0-dev`? I can't check it on my system atm but I'm pretty sure this is the package you're missing.

**Comment by Tr0lldr0id** [comment]
> Could you try it with `liblua5.1-0-dev`? I can't check it on my system atm but I'm pretty sure this is the package you're missing.

This did it. Thank you very much. However, I am unfortunately still getting the graphics error. However, I will start a new issue for that, as it is apparently not related to the "make" problem after all.
