### ISSUE TITLE
RA: Mission 04 Ten to one hangs

### ISSUE THREAD

**Issue by woife** [OpenRA/OpenRA#16078]
### Issue Summary
OpenRA with version "playtest-20190106" hangs in mission "04: Ten to one".
When difficulty is set to "normal", the game always hangs in this mission after about 38 seconds.

#### System Information
- **Operating System:** Kubuntu 18.10
- **.NET / Mono Version:** Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)
- **OpenRA Version:** playtest-20190106
- **Mod:** Red Alert

#### Additional Information:
- Steps to reproduce
	1. Select single player mission "04: Ten to one"
	2. Set difficulty to "normal"
	3. Start game
	4. Wait for 38 seconds
	5. Game hangs

The bug is not triggered when difficulty is kept at "easy" (default setting).
The bug does not happen in release-20181215.

When the bug happens the log files "lua.log" and "perf.log" continue to grow (quickly to the size of several MB). Both files are filled with the same line over and over.

perf.log:
     1 ms [942] Activity: CallLuaFunc
     1 ms [942] Activity: CallLuaFunc
     1 ms [942] Activity: CallLuaFunc

lua.log:
harv 159 is not revealed for player USSR (0)!
harv 159 is not revealed for player USSR (0)!
harv 159 is not revealed for player USSR (0)!

Some log files are empty, the other ones are attached to this bug report.

[debug.log](https://github.com/OpenRA/OpenRA/files/2774555/debug.log)
[lua.log](https://github.com/OpenRA/OpenRA/files/2774556/lua.log)
[perf.log](https://github.com/OpenRA/OpenRA/files/2774557/perf.log)
[server.log](https://github.com/OpenRA/OpenRA/files/2774558/server.log)

**Comment by pchote** [comment]
This is going to be related to #16020 etc, and I expect it will be fixed by #16028 and #16067 once they are complete.
