### ISSUE TITLE
AI Production Time Limit

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#16087]
Remembered while trying to rebease the Generals Alpha engine, i had time limits for AI per queue (tho per actor can be a better way to implement this) to prevent the AI from wasting their early cash to build a second dozer, mines or upgrading their Cold Fusion Reactors.

Should be pretty easy to move it to upstream, but i don't see much of a use for it in main mods, so i dunno if it would be adding useless checks to the AI code. So wanted to create an issue instead of a PR.

**Comment by pchote** [comment]
This sounds very useful for upstream - d2k can use it for the building upgrades, an Easy AI can use it to delay teching up, and more.

**Comment by MustaphaTR** [comment]
Hmm, yes. Considering the fact that D2k AI doesn't use Concrete, delaying them from upgrading ConYard would be for their good. It enables Large Concrete and Rocket Turret, which latter also requires Outpost.
