### ISSUE TITLE
Limit the messages a player can send per second.

### ISSUE THREAD

**Issue by airetaM** [OpenRA/OpenRA#16086]
Maybe 1 per second should be fine.
release-20181215
I played 2 games yesterday in wich 2 different players (not the same ip's) spammed messages to frustrate the game.
In the first game a player spammed messages from the beginning. I'm not sure if this caused the massive lag but the game was like not playable with the loud noise caused by this and most of the players leaved soon.

In the second game someone who where just about to loose started the same thing and tryed to pause the game, luckily he disconnected after a while.
I assume the messages are not typed manually.
https://www.gamereplays.org/openra/replays.php?game=92&show=details&id=335370
https://www.gamereplays.org/openra/replays.php?game=92&show=details&id=335371

**Comment by anvilvapre** [comment]
if so - please add a "wake up" button to the lobby that rings some alert sound. or a "ready up count down" button, giving players x second to ready up or to become candidates to be kicked.
players waiting in lobby often switch to other windows - which is fine. they won't notice until the lobby is full until someone makes many short typing messages - to make a sound that is different from normal chat.

i agree that disabling copy pasting in game - after lobby - could/should be disabled. it avoids many people from pasting spam in game. asumming that copy paste seems to work under Windows.

**Comment by PunkPun** [comment]
Solved by #20125
