### ISSUE TITLE
Trying to produce Airplanes in a Helipad

### ISSUE THREAD

**Issue by Tr0lldr0id** [OpenRA/OpenRA#16097]
### Issue Summary

I'm trying to flip some stuff around in the RA mod to make it a bit more like Red Alert 2. I am NOT trying to make RA2, I know that mod already exists, but I want to make things a little more like it. I'm starting with the aircraft, and I've gotten as far as making the MiG show up in the allied aircraft production tab, but it won't actually produce it. I click it, and it starts using up resources, and then just stops. The game doesn't crash, so I don't get a error in the terminal (very annoying), and I can't figure out what the problem is. It IS related to the Helipad, I made it soviet and tried producing the plane again with the same glitch. Here is my Helipad code:
(Note; there are some random extra factions in here that I added as well, but I'm using one of the default factions for testing right now so I don't think they have anything to do with it)
HPAD:
	Inherits: ^Building
	Inherits@shape: ^2x2Shape
	Selectable:
		Bounds: 48,48
	HitShape:
		UseTargetableCellsOffsets: false
		TargetableOffsets: 0,0,0, 768,-512,0, 768,512,0, -281,-512,0, -630,512,0
	Buildable:
		Queue: Building
		BuildPaletteOrder: 120
		Prerequisites: proc, ~structures.allies, ~techlevel.medium
		Description: Produces and reloads\nairplanes.
	Valued:
		Cost: 500
	Tooltip:
		Name: Airforce Command Center
	Building:
		Footprint: xx xx ==
		Dimensions: 2,3
		LocalCenterOffset: 0,-512,0
	Health:
		HP: 80000
	Armor:
		Type: Wood
	RevealsShroud:
		Range: 5c0
		RevealGeneratedShroud: False
	RevealsShroud@GAPGEN:
		Range: 4c0
	WithBuildingBib:
	Exit@1:
		SpawnOffset: 0,-256,0
		ExitCell: 0,0
		MoveIntoWorld: false
		Facing: 224
	RallyPoint:
	Production:
		Produces: Aircraft
	Reservable:
	ProductionBar:
	PrimaryBuilding:
		PrimaryCondition: primary
	Power:
		Amount: -50
	Exit@1:
		SpawnOffset: -350,350,0
		MoveIntoWorld: false
	Exit@2:
		SpawnOffset: 600,220,0
		MoveIntoWorld: false
	Exit@3:
		SpawnOffset: 200,820,0
		MoveIntoWorld: false
	Exit@4:
		SpawnOffset: 200,-300,0
		MoveIntoWorld: false
	ProvidesRadar:
	ProvidesPrerequisite@allies:
		Factions: allies, england, france, germany, america, korea
		Prerequisite: aircraft.allies
	ProvidesPrerequisite@alliesvanilla:
		Factions: allies
		Prerequisite: aircraft.alliesvanilla
	ProvidesPrerequisite@england:
		Factions: england
		Prerequisite: aircraft.england
	ProvidesPrerequisite@france:
		Factions: france
		Prerequisite: aircraft.france
	ProvidesPrerequisite@germany:
		Factions: germany
		Prerequisite: aircraft.germany
	ProvidesPrerequisite@america:
		Factions: america
		Prerequisite: aircraft.america
	ProvidesPrerequisite@korea:
		Factions: korea
		Prerequisite: aircraft.korea
	ProvidesPrerequisite@alliedstructure:
		RequiresPrerequisites: structures.allies
		Prerequisite: aircraft.allies
	ProvidesPrerequisite@alliedvanillastructure:
		RequiresPrerequisites: structures.alliesvanilla
		Prerequisite: aircraft.alliesvanilla
	ProvidesPrerequisite@englishstructure:
		RequiresPrerequisites: structures.england
		Prerequisite: aircraft.england
	ProvidesPrerequisite@frenchstructure:
		RequiresPrerequisites: structures.france
		Prerequisite: aircraft.france
	ProvidesPrerequisite@germanstructure:
		RequiresPrerequisites: structures.germany
		Prerequisite: aircraft.germany
	ProvidesPrerequisite@americanstructure:
		RequiresPrerequisites: structures.america
		Prerequisite: aircraft.america
	ProvidesPrerequisite@koreanstructure:
		RequiresPrerequisites: structures.korea
		Prerequisite: aircraft.korea
	ProvidesPrerequisite@buildingname:
	Targetable:
		TargetTypes: Ground, C4, DetonateAttack, Structure, SpyInfiltrate
	InfiltrateForSupportPower:
		Proxy: aircraft.upgraded
		Types: SpyInfiltrate
	WithDecoration@primary:
		RequiresSelection: true
		Image: pips
		Sequence: tag-primary
		ReferencePoint: Top
		ZOffset: 256
		RequiresCondition: primary
	WithRearmAnimation:

and here is my MiG code:

MIG:
	Inherits: ^Plane
	Inherits@AUTOTARGET: ^AutoTargetGroundAssaultMove
	Buildable:
		Queue: Aircraft
		BuildAtProductionType: Plane
		BuildPaletteOrder: 50
		Prerequisites: ~hpad, ~techlevel.low
		BuildDurationModifier: 50
		Description: Fast Ground-Attack Plane.\n  Strong vs Buildings, Vehicles\n  Weak vs Infantry, Aircraft
	Valued:
		Cost: 2000
	Tooltip:
		Name: MiG Attack Plane
	Health:
		HP: 7500
	RevealsShroud:
		Range: 13c0
		Type: GroundPosition
		RevealGeneratedShroud: False
	RevealsShroud@GAPGEN:
		Range: 11c0
		Type: GroundPosition
	Armament:
		Weapon: Maverick
		LocalOffset: 0,-640,0, 0,640,0
		LocalYaw: -40, 24
		PauseOnCondition: !ammo
	AttackPlane:
		FacingTolerance: 20
	Aircraft:
		RearmBuildings: hpad
		CruiseAltitude: 2560
		InitialFacing: 192
		TurnSpeed: 4
		Speed: 223
		RepulsionSpeed: 40
		MaximumPitch: 56
	AutoTarget:
		InitialStance: HoldFire
		InitialStanceAI: HoldFire
	AmmoPool:
		Ammo: 8
		AmmoCondition: ammo
	ReturnOnIdle:
	Selectable:
		Bounds: 36,28,0,2
		DecorationBounds: 40,29,0,1
	SelectionDecorations:
	Contrail@1:
		Offset: -598,-683,0
	Contrail@2:
		Offset: -598,683,0
	SpawnActorOnDeath:
		Actor: MIG.Husk
	SmokeTrailWhenDamaged:
		Offset: -853,0,171
		Interval: 2

#### System Information
- **Operating System:** Ubuntu 18.04
- **.NET / Mono Version:** I do not know what the .net or mono version is, any help on finding this info is appreciated
- **OpenRA Version:** release 20180923
- **Mod:** Red Alert

**Comment by matjaeck** [comment]
Note that issues opened in this repository involve the development of upstream OpenRA but usually not development of mods downstream. Unless the subject of your issue is a limitation, feature request or bug of the engine, it is probably a better idea to ask in the modding section of the forum or in the modding channel of the discord servet.  Links to both places can be found on openra.net. It is a good idea to ask in those places at first when experiencing issues while modding to make sure the issue has to be fixed upstream (then please report!) and not in your own code. I can't say what's the case here so take it as a general advice :)

**Comment by Tr0lldr0id** [comment]
Oh! Very sorry, I didn't realize there were separate modding forums. Thank you very much, I will close this and ask there.
