### ISSUE TITLE
Aircraft attack move to rally points

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16099]
Build an airfield next to a blob of enemy medium tanks. Produced Yaks or MiGs will attack the tanks (while in Hold Fire stance), reload, and often not reach the waypoint set on the airfield.

**Comment by MustaphaTR** [comment]
Units Attack-Move to rally points, stances don't matter in that case.

**Comment by matjaeck** [comment]
This explains the behavior. IMO they should only execute a move command.

**Comment by matjaeck** [comment]
Attack-moving to rally points as the general behavior makes sense and the issue was actually closed when MustaphaTR commented, so thanks for the feedback @GraionDilach. This behavior should be explained when implementing #13817 to avoid any misunderstandings.

**Comment by pchote** [comment]
I remain unconvinced that this is reasonable behaviour, FWIW.
