### ISSUE TITLE
Production palette audio feedback issues

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#16117]
Copied over from #16083

"Training" (or "Building") is voiced when you left-click the production that was previously put on hold. "On hold" and "Cancel" are voiced always. Also "Training" (or "Building") is voiced once when production queue for the tab is completely empty, but otherwise is completely replaced by click sound.
Is this the intended behaviour?

Also "Unit ready" is sometimes voiced 3-5 times in a row and then is silent when there are no other speech sounds at all: https://youtu.be/vucc78gWCDg

**Comment by pchote** [comment]
> Is this the intended behaviour?

Indeed it is.

> Also "Unit ready" is sometimes voiced 3-5 times in a row and then is silent when there are no other speech sounds at all: https://youtu.be/vucc78gWCDg

I can't reproduce this, even when copying your setup with three barracks building first minigunners and then rockets.  "Unit Ready" always plays at the expected time for me. Can anybody else confirm this working/not working for them?

**Comment by netnazgul** [comment]
For some reason I can't reproduce it _exactly_ either, not on pure bleed and not on the build I had when recording the video (bleed + arty force fire PR + target-on-the-move PR). But I still get occasional click sound and "Unit ready" sound skips when there are a lot of simultaneous sounds played at the same time (i.e. during attack).

**Comment by pchote** [comment]
Isn't that just our standard "sound system ignores sounds if too many things are playing at once" bug?
