### ISSUE TITLE
New PNG refactor crashes the game on 24 bit PNGs used for (embedded) icons/loadscreens.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#16120]
Examples.

[as-20181230.yaml.txt](https://github.com/OpenRA/OpenRA/files/2800023/as-20181230.yaml.txt)
[sp-{Build 20180203}.yaml.txt](https://github.com/OpenRA/OpenRA/files/2800024/sp-.Build.20180203.yaml.txt)

**Comment by pchote** [comment]
The png loader assumes that all UI sprites are 32 bit, which is true for the upstream mods.

It shouldn't be hard to have it automatically upgrade 8 or 24 bit images to 32 bit on load, but obviously there will be a performance overhead here (which you would have been paying already with the System.Drawing loader).

**Comment by GraionDilach** [comment]
8-bit works btw, only 24-bit not.
