### ISSUE TITLE
Aircraft can't attack on queued force attack

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16134]
Different from #14805 and applies only to aircraft.

<details>
  <summary>GIF</summary>

![yak](https://user-images.githubusercontent.com/37185497/51861777-5c4c6b00-233d-11e9-9f73-0d0c2951be7f.gif)

</details>

**Comment by tovl** [comment]
Just checked this in game. It's not exclusive to force attack. It ignores queued move orders randomly as well. It seems this only happens when the plane is idling.

**Comment by abcdefg30** [comment]
For context: Reopening per https://github.com/OpenRA/OpenRA/pull/16481#issuecomment-496032247.

**Comment by pchote** [comment]
No repro on current bleed.
