### ISSUE TITLE
Milestone Roadmap

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#16131]
Things we want to fix, refactor or implement for Next + 1 (ETA summer/autumn 2019).

Starting with things I'm working on myself:

## Aircraft improvements:

- ~Merge 'Heli'-specific activities into their non-Heli counterparts + clean-ups (#15803)~
- Finish Aircraft idle behavior refactor (#15873)

## Resupply system improvements:

- ~Merge `Rearm` and `Repair` activities into `Resupply` activity, including all depency changes~
- Move resupply order handling to dedicated `ResupplyManager` trait
- Refactor `Reservable` into a `Dock` trait, allowing for multiple resupply 'slots' per building and other improvements

## Animation improvements:

- Improve feature- and code consistency among *Animation traits
- Implement animation priority system to fix glitches caused by conflicting animations

Things I'd like to see, but probably won't have time or skill for to tackle myself (at least on this release cycle), but will review/test if PR'd by others:

## Pathfinding improvements:

- Remove crates and mines from pathfinding considerations (#15112)
- Cache more pathfinding calculations in `Locomotor` (#15876)

## AI/bot improvements:

- More intelligent bot base building
  - less (or zero?) randomness, at least initial build order should be fixed
  - stop spending cash on random buildings when base is large enough
- More intelligent bot capture logic (might get implemented/superseded by squad refactor)
  - bots should only build capturers on module request, to avoid wasting cash on them
  - bots should at least be able to efficiently capture nearby tech buildings
  - add optional scan radius distance limit (should help with both of the above)
- More intelligent squad system (#9021, delay to Next+1 depending on work-load?)
  - less (or zero?) composition randomness, to make squads more efficient
  - squad mission system, e.g. `Attack`, `Defend`, `Scout`, `HuntHarvesters` etc.

**Comment by pchote** [comment]
My current planned priorities are:

## Make Singleplayer Great Again
* Develop my savegame prototype into a real feature, starting with missions, expanding to Skirmish if there is time (#2743)
* Campaign progression (#15020)
* Mission flow UI (progressing to next mission without returning to the main menu) - Implementation is planned, but no issue yet.
* Overhaul the bot definitions and behaviour (#16126)

## Keep up momentum with the orders/activity rework
* Finish the order targeting rework (#16048, #15891)
* Support @reaperrr's ongoing aircraft rework
* Get #16060, #16065, and #16129 merged so we can finally be rid of "X can't be queued" bugs
* Get #16105 merged and deal with any unexpected fallout so we finally have sane AttackMove logic

## Drag Linux into the modern .NET era
* Remove `System.Drawing` dependency (#15955 and referenced issues)
* Bundle Mono 5.10 in our AppImages (#15965)
* Consider bundling Mono on macOS (#12170)

**Comment by dragunoff** [comment]
A couple of things that I'd like to contribute for Next+1:
* Revamped TD in-game UI (#7572)
* Hotkey widget UX improvements (#16001)

**Comment by matjaeck** [comment]
I'd like to contribute until the time of Next+1:

- an improved technical documentation (#14225)
- improvements to make changelogs more accessible (#16133)
- help with gameplay/platform reviews
- make textual proposals for an ingame privacy notice and see how that develops (no issue yet)

**Comment by obrakmann** [comment]
I'd like to contribute the following for Next+1:

* All the game mode stuff + match time limit + victory conditions for the domination game mode
* Now that a fix for AttackMove in sight, I'd like to add a proper Patrol activity, if possible with a order targeter and command bar button.

**Comment by Nineeva** [comment]
Love to see some additional options in the map editor that auto write a bit of script for the map such as:

- being able to choose what units a structure should make if AI controlled
- link structure production to way points.
- being able to choose if AI should rebuild a building if destroyed and repair if damaged.

Maybe a couple of other simple things like unit start health and veteran level.

**Comment by reaperrr** [comment]
Minor update: Replaced the migration of sounds to notification system with animation system improvements.

Migrating the sounds would require some plumbing changes (current notification overload assumes that sounds are UI only) and in general there are more affected places than I'd have hoped, so this will be quite an undertaking even if the changes themselves are relatively simple.

On the other hand, my animation trait refactor and priority system is approximately 80-90% done locally, so it's just a matter of tieing up some loose ends and getting through the review process, and the benefits for for us and modders are likely larger, so I think it makes sense to give this higher priority.

**Comment by teinarss** [comment]
The things i will focus on this time is.

## Adult men doing things together - Improve the game regarding MP
The title is a reference to Swedish television show

~~#15226 - Added drag direction mouse interaction for set the approach direction for airstrike and parabombs~~
#16355 - Coloring system messages yellow and added a new widget for transient messages 
#5121 -[RA] Upgrade observer/replay interface features.
#15511 - Subcell positions should be treated as a bitfield by the pathfinder/follower

Making more progress on the HPA*

**Comment by pchote** [comment]
We are now in a bugfix-only phase so that we can ship the completed features. This issue has served its purpose, so closing.
