### ISSUE TITLE
OpenRA crashes (solved); Low FPS 

### ISSUE THREAD

**Issue by dilgar** [OpenRA/OpenRA#16144]
Whenever i try to start any OpenRA game, it crashes. I'v tried i think just about everything, even updated my drivers, tried different builds. Always ends up with this error which shows in logs as follows:
Exeption log: 
OpenRA engine version NAs-Test-Build
Date: 2019-01-31 21:09:39Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidProgramException`: OpenGL Version Error: See graphics.log for details.
   в OpenRA.Platforms.Default.OpenGL.Initialize()
   в OpenRA.Platforms.Default.Sdl2GraphicsContext.InitializeOpenGL()
   в OpenRA.Platforms.Default.ThreadedGraphicsContext.RenderThread(Object contextObject)
   в System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Threading.ThreadHelper.ThreadStart(Object obj)

Graphics log:
Unsupported OpenGL version: 1.1 Mesa 6.0

OpenGL Information:
Vendor: SciTech Software, Inc.
Renderer: GLDirect 5.0 x86 (Dec 10 2007 21:11:41)
GL Version: 1.1 Mesa 6.0
Shader Version: 
Available extensions:
GL_EXT_texture_env_add GL_ARB_multitexture 

My PC specs:
Windows 7
Intel Core i3-2120 CPU 3.30 Hz 3.30 Hz
Nvidia GeForce GTX 650 Ti
8 Gigs of ram

Every drives should be in place, like Net Framework, even dreaded OpenGL, but no matter what i do, its just show me  this error log and nothing i do matters.
UPD. Reinstalled sound drives for realtek like in #12455, didnt worked either. Also, nuild verions is 20181215, same thing happend in newer playtest

**Comment by GraionDilach** [comment]
Why are you trying to use a Mesa driver on Windows for a GeForce card?

**Comment by GraionDilach** [comment]
Please unsinstall the Mesa stack, use the driver search function of NVidia's - https://www.geforce.com/drivers -  and install what it offers. That should do.

**Comment by dilgar** [comment]
Okay, ill say in UPD if that have helped

**Comment by dilgar** [comment]
I dont know how to reove Mesa stack and moreover, my PC tells that all drivers are up to date

**Comment by dilgar** [comment]
I cant find it, whats its full name?

**Comment by dilgar** [comment]
Update - funny thing, when rautamiekka said that i should delete Mesa, when i'v planted its opengl32.dll the game LAUNCEHD! But now there is another problem - insanely low FPS, which gets a tiny bit better on windowed mode, but its a different issue now so ill do some more research, as for this ticket, i think the issue partialy resolved, thanks everywone. Ill open a new ticket if low FPS will be another prominent issue.

**Comment by dilgar** [comment]
Now only FPS problem remains, as game takes 90% of CPU

**Comment by dilgar** [comment]
Apperantly the problem with this new opengl32.dll, ill try to find different version to help the situation

**Comment by GraionDilach** [comment]
Call a RL friend who knows how to game on/handle PCs in general, tell him your GPU drivers are broken and request help from him to get them reinstalled from scratch. I can't believe there is a game literally messing up the whole GPU stack.

**Comment by dilgar** [comment]
Well, its not the game itself. I'v placed the same dll that allowed to run the game, if not to take horrible FPS to account, into another one that also had opengl issue, and it too runs noticibly slower, while other games that didnt had that problem at all runs ok, majority of them. Its basicly that 1 pesky opengl32.dll which causes all the problems to me as i understad it.

**Comment by GraionDilach** [comment]
You shouldn't even need to use random opengl32.dlls. The fact you're trying such already smells. There's a deep issue within that GPU stack and to me it seems you're unable to resolve it, let alone completely understanding it.
