### ISSUE TITLE
Allied mission 06b (Cripple Iron Curtain Research): explosive barrels don't destroy fire towers

### ISSUE THREAD

**Issue by digitalheir** [OpenRA/OpenRA#16146]
### Issue Summary
I'm having trouble with this mission and looked up a strategy video. You can see in this video that shooting the barrels destroys the fire towers, while in OpenRA it only does minor damage.
https://youtu.be/oOtVfflViRg?list=PL-Ecy11VjzuxNt4IRF9st-BELMUSGwwQ9&t=199

#### System Information
- **Operating System:** Ubuntu 18.10
- **.NET / Mono Version:** Mono
- **OpenRA Version:** release-20181215
- **Mod:** Red Alert

#### Additional Information:
- Steps to reproduce
	1. Start the mission
	2. Shoot a barrel with a ship

**Comment by Smittytron** [comment]
Right now the code only has the towers being destroyed on easy difficulty.

**Comment by Smittytron** [comment]
I can file a change if desired, but this seems to have been done intentionally.

**Comment by obrakmann** [comment]
If choosing a lower difficulty setting allows you to get past the flame towers, then I'd consider it fixed.

**Comment by digitalheir** [comment]
I could manage by just sending in a few tanks. I was confused because the video is in "hard". But I guess OpenRA is more difficult than the original game? Nevermind then.

**Comment by REdalert543543** [comment]
This issue is still relevant. Tried to complete mission, but the Flame- Towers prevent that. They should be destroyed when the barrels are hit.

**Comment by abc013** [comment]
The gunships are able to hit the flametowers without being in range of those. As soon as the heavy tank targets the ships, you can move them back. The heavy tank follows over the mud bridge and you are able to kill it. The other flamethrower can be taken out by using the mcv as a shield and the rocket infantry/ships to destroy it.

Imo destroying the flame towers by killing the barrels is too easy for normal. If wanted I could make the barrels inflict more damage to the flame towers on normal.
