### ISSUE TITLE
Removing debug msgs for q and w shortcuts

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16148]
I personally use 'select unit by type' all the time as it is one of the best tools for unit micro management thus I get constant spam of msgs and chat noise
<img width="278" alt="screenshot 2019-02-01 at 23 56 57" src="https://user-images.githubusercontent.com/37534529/52152004-95f2de00-267d-11e9-9782-62132778bc14.png">
this makes it a lot harder harder to notice msgs written by spectators and other players as well as reading missed ones, I'd like it removed as it serves no significant purpose

**Comment by matjaeck** [comment]
The issue I see is that the hotkey for `Select units by type` does two different things depending on your current selection: If there are other, not selected units of same type on the screen, it will select all units of this type across screen. If all units of this type on the screen are selected, it will select across map.

This real fix is IMO to separate these two use cases and give each its own hotkey OR (what I'd prefer) to remove the selection across map functionality entirely, as this use case usually corresponds with poor micro and control. Until then, this debug information is IMO required.

**Comment by pchote** [comment]
There should be an old issue somewhere about putting these messages in their own notification area, like RA2 did.  I'm not sure the best keywords to try and find it again, however.

**Comment by Punsho** [comment]
Selection rules are clear, I personally never check that msg as I know when I select all units by type on the map and when not

**Comment by GraionDilach** [comment]
RA2 didn't have separate notification area though.

**Comment by Punsho** [comment]
I would love if it would be more consistent. When you press the button once it would select all units on screen and when twice all on the map without any arbitrary rules that are in now

**Comment by GraionDilach** [comment]
Actually, that's what RA2 did - I thought that's how it acts already.

**Comment by matjaeck** [comment]
> Removing debug msgs for q and w shortcuts

Just to clarify, this means `Remove debug messages for hotkeys Select units by type / Select all combat units`.

**Comment by pchote** [comment]
See #3278 / #6400 / #6376 etc.  There is an accessibility angle to consider here.

**Comment by Punsho** [comment]
Yeah, it is a different topic. Streamlining the selection would remove the need for these notifications entirely and I believe that it would be easy and quick to do as opposed to making everything post debug msgs

**Comment by GraionDilach** [comment]
If someone would made everything posting debug commands then those would be tied to a checkbox within Options anyway.

**Comment by pchote** [comment]
The idea was that these messages would be written to their own status line, separate to the chat and without a history scrollback.

**Comment by dragunoff** [comment]
+1 for moving that kind of messages to a separate tray and +1 for adding support for text notifications when sound isn't available. 

@Punsho What do you mean by "Streamlining the selection"?

**Comment by Punsho** [comment]
@dragunoff 
Currently selection works unreliably as when you click a button once, it will select all units of that type of screen but if all of those units are already selected it's going to select globally, this is an arbitrary rule. IMO in that case it should not select anything

**Comment by dragunoff** [comment]
@Punsho 
I think this is a very clear rule and I always found the selection functionality quite intuitive but I think I can see your pain point here. Anyway this should be the subject of a separate issue.

**Comment by Punsho** [comment]
It is very clear but it is hard to think about it in the heat of battle

**Comment by dragunoff** [comment]
I've been working towards solving this in #17737 however I realized there is a slight problem with the approach - removing the chat line also removes the beep sound leaving the user without any feedback for their keypress (except the selection changing but that may not always be the case). I guess we could work around that by adding a click sound to the keypress handler if the chat notification is disabled.

**Comment by deleted-user-1** [comment]
> removing the chat line also removes the beep sound

I don't really care about the text messages but find the "beep" sound in RA really really annoying. I'd welcome an option to disable it (also for the chat). I personally don't think any messages or sound notifications ("system-beeps") should needed anyway for select commands and think these only exist in OpenRA (and I agree they are somewhat needed here) because of a questionable/confusing input pattern for the "select by type"-hotkey.

**Comment by dragunoff** [comment]
@matjaeck See #12149 for chat beep muting.

Perhaps a better solution is to move the select by type notifications out of the chat and into a separate tray (already attempted in #16355). Or hide them altogether and change the behavior of the hotkey to be less confusing.
