### ISSUE TITLE
Red Alert: Bug in scg02ea when you're standing in the way of Soviet convoy

### ISSUE THREAD

**Issue by digitalheir** [OpenRA/OpenRA#16141]
### Issue Summary
Convoy doesn't show up and secondary objective fails
... ... ...

#### System Information
- **Operating System:** Ubuntu 18.04
- **.NET / Mono Version:** Mono 5.18
- **OpenRA Version:** release-20181215
- **Mod:** Red Alert

#### Additional Information:
- Steps to reproduce
	1. Put some units in the road that the convoy will take
	2. Wait until the voice announced "convoy approaching"
	3. I suspect the AI can't make a way around the units
        4. Sub-objective is failed

- Logs

- OpenRA Replays
Around [4:00].
I would like to see the entire playing field to see what's going on with the convoy. But how?
[OpenRA-2019-01-31T163026Z.zip](https://github.com/OpenRA/OpenRA/files/2818243/OpenRA-2019-01-31T163026Z.zip)

- Screenshots & Videos

**Comment by abcdefg30** [comment]
The convoy has two routes it can take (the one to the west you blocked) and one to the north-east. Are you sure it didn't take the other?

Either way, I admit that the convoy taking different paths is not obvious to the player. Not sure how we can improve this (could reveal shroud and place a beacon, but that might make it too easy).

**Comment by digitalheir** [comment]
Ah, that's probably it then. I thought it had just one possible route! It seems to prefer the one to the west? I did the mission by placing my troops next to the road.

Don't know it it's too easy. The convoy trucks move pretty fast so I have the feeling you can only destroy them if you already place your troops there in advance!
