### ISSUE TITLE
Wiki files are updated before version is set

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#16159]
... so `utility.ModData.Manifest.Metadata.Version` is always `{DEV_VERSION}`, as it can be seen in the generated documents.

This can probably be fixed in our .travis.yml by moving the `./update-wiki.sh $TRAVIS_BRANCH` command to the `before_deploy` hook just after `./package-all.sh ${TRAVIS_TAG} ${PWD}/build/`, which calls the make version command in each buildpackage.sh.

**Comment by deleted-user-1** [comment]
#17746 fixed this for https://github.com/OpenRA/OpenRA/wiki/Traits-(playtest), but there is still something wrong with https://github.com/OpenRA/OpenRA/wiki/Lua-API-(playtest). Unrelated though.
