### ISSUE TITLE
Can not create OpenGL context. (Error: wglMakeCurrent(): ) Windows 7

### ISSUE THREAD

**Issue by dilgar** [OpenRA/OpenRA#16171]
Windows 7 x64
Intel Core i3-2120 CPU 3.30 Hz 3.30 Hz
Nvidia GeForce GTX 650 Ti
8 Gigs of RAM
Updated drivers and game just before the loading screen crashes
[exception-2019-02-05T070927Z.log](https://github.com/OpenRA/OpenRA/files/2831125/exception-2019-02-05T070927Z.log)

**Comment by GraionDilach** [comment]
Reinstall the system. notsure what you broke but if even multiple versions of the driver reinstalled couldn't fix it, then your Windows is broken beyond what is remotely salvageable.

For the record - he caught me on Sunday night with this and I tried to debug this, but no way I managed to fix it.

**Comment by dilgar** [comment]
Well, if there is no more options...

**Comment by matjaeck** [comment]
Another option is to install Linux (Ubuntu is easy to install and well documented) as a parallel system and see if it works there. I'm also unable to play the game under windows since last release but don't have any issues on Linux.
