### ISSUE TITLE
Making fake structure prices consistent

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16187]
Most fakes have 0.1 value of the original structure but this is not true for all of them

Sub Pen costs 100, needs to cost 80
Adv. Power Plant costs, 60 needs to cost 50
Construction Yard costs 250, needs to cost 200

**Comment by Punsho** [comment]
There is no real balancing issue with this change as it fakes are already really cheep. Also it is believed that these inconsistent prices are just leftovers from other balance changes where building prices were changed but no one bothered to update fakes

**Comment by Smittytron** [comment]
Why is there a fake subpen to begin with?

**Comment by MustaphaTR** [comment]
Because original game did for some reason. It was unbuilable there too.

**Comment by Moth-Tolias** [comment]
is there a way to automatically derive the proper cost percentage via yaml?

**Comment by pchote** [comment]
Fixed by #16188.
