### ISSUE TITLE
GrantExternalConditionToProduced isn't within Traits/Conditions folder.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#16183]
Even such external conditions are within - GrantExternalConditionToCrusher is an older example.

**Comment by MDBarbier** [comment]
I have made this change and run make.test and make.check without issue. I need to test changes in default mods which I hope to do tomorrow.

**Comment by MDBarbier** [comment]
[Pull request](https://github.com/OpenRA/OpenRA/pull/16975) submitted for this issue
