### ISSUE TITLE
"Unit Ready" voice notification is silent sometimes

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#16195]
Second part of #16117 that feels like a regression.

It is not consistent, but generally you can have "Unit Ready" not voiced when for example producing 100 rifle infantry in a row - it is produced for 4-5 rifles, then is silent for the next 4-5, then sounds again for consequent ones.

**Comment by pchote** [comment]
This can be reproduced by playing the attached replay with ` || p.PlayerName == "BrotherPun"` added to the player check in `PlayPredefined`. The lack of notifications can be seen about 2 minutes in.

[UnitReady.orarep.zip](https://github.com/OpenRA/OpenRA/files/2849371/UnitReady.orarep.zip)

**Comment by pchote** [comment]
Ok, this one is really silly.  The rate limit currently doesn't discriminate players, so if *anybody in the game* has just built something it won't play for you.

**Comment by pchote** [comment]
The simplest/safest fix now is probably to revert/remove the `RateLimit` notification key. We got the key benefit from the rate limiting in a different way in #16083, and #16034 makes the most of the basic plumbing that the original rate limit PR added.
