### ISSUE TITLE
harvester sometimes tries to mine already emptied mineless ore field

### ISSUE THREAD

**Issue by Violetnred2** [OpenRA/OpenRA#16192]
[playtest-20190209.zip](https://github.com/OpenRA/OpenRA/files/2848793/playtest-20190209.zip)
if harvester empties a trail made of mineless fields that are less than 10 or less cells away from each other , it will sometimes head to and stop at seeminggly random previously emptied field for several seconds before returning to refinery.

**Comment by pchote** [comment]
This is apparently a regression vs the current stable release.

**Comment by pchote** [comment]
Regression was introduced by #15856.

Considering how awful the harvesting activities are, my preference is to bump this to Next + 1 unless this hurts normal gameplay in obvious ways.
