### ISSUE TITLE
Neutral structures can not be targeted under explored map fog (playtest-20190209)

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#16190]
There is no target cursor for neutral structures under fog when starting a game with Explored map: On. If the structure is revealed and then goes under fog again, the cursor does appear. 

To reproduce:
- Start a skirmish game on map with neutral capture-able structures (for example: Green Belt) with Explored map: On
- Build an engineer or any unit that can attack
- Try ordering the engie to capture the structure or try force firing with the attacking unit under fog w/o having revealed that part of the map

![screenshot_20190210_125554](https://user-images.githubusercontent.com/1355810/52532821-4ecab400-2d33-11e9-921e-44f92e470d4a.png)

**Comment by pchote** [comment]
From #16189:

> Repro case: Start a game with explored map enabled and *without enabling the visibility cheat* build an engineer and see that tech structures do not have a cursor. If there is a map specific component, my repro case was on the left-hand spawn on Sidestep.

> I always used the `/all` cheat when testing, which hides this regression.

**Comment by obrakmann** [comment]
The problem seems to be that while the actor's `FrozenState.Visible` flag gets set properly during creation, it gets reset to false right in the first tick.

**Comment by obrakmann** [comment]
Introduced in 95dc9cb1d2

**Comment by obrakmann** [comment]
Proposed fix below. I don't have the foggiest idea whether that's in any way correct, though.

```diff
diff --git a/OpenRA.Mods.Common/Traits/Modifiers/FrozenUnderFog.cs b/OpenRA.Mods
index 7897c6b83b..eb1ce5abba 100644
--- a/OpenRA.Mods.Common/Traits/Modifiers/FrozenUnderFog.cs
+++ b/OpenRA.Mods.Common/Traits/Modifiers/FrozenUnderFog.cs
@@ -123,7 +123,7 @@ public bool IsVisible(Actor self, Player byPlayer)
 
                void ITick.Tick(Actor self)
                {
-                       if (self.Disposed)
+                       if (self.Disposed || !created)
                                return;
 
                        VisibilityHash = 0;
```

**Comment by pchote** [comment]
Oh, I see...

I think a better fix will be to get rid of the FrameEndTask, and instead move the `if (startsRevealed)` block into Tick.
