### ISSUE TITLE
AttackLeap cancellation issues

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#16191]
Reported by Violet-n-red on Discord.

> dogs sometimes get stuck after friendly force-fire: made >50 dogs several times on different maps, selected them all and repeatedly force-fired on a cell occupied by dogs in the middle of a blob. eventuall several dogs would get stuck in a running animation while standing  still.

> happens when attack order is issued repeatedly while the dogs are around one cell away from attacking and the target is already dead

Replay demonstrating bug: [OpenRA-2019-02-10T105009Z.orarep.zip](https://github.com/OpenRA/OpenRA/files/2848769/OpenRA-2019-02-10T105009Z.orarep.zip)

**Comment by pchote** [comment]
This is another "Move-based activity as a child activity"-type bug, which we now understand thanks to @tovl's investigation and fixes.

This is fixed by the Activity changes in #16217, so we need to make a choice: take that PR for prep and take on the risk of other activities breaking if they depend on the old `ChildActivity` behaviour in unexpected ways, or take a short term / prep-only PR to remove `ChildActivity` from `LeapAttack`, which is then reverted in #16217.

My preference at this stage is a prep-only PR, and then save #16217 for Next + 1.

**Comment by reaperrr** [comment]
> My preference at this stage is a prep-only PR, and then save #16217 for Next + 1.

Sounds better/safer, yes. We don't want to run into another situation like we had with all the targeting stuff, I think.

**Comment by pchote** [comment]
I have created #16236 for Next, switched this issue over to the Next + 1 milestone, and changed #16217 to close this when merged.

If #16217 doesn't make it for any reason then we will need to re-file #16236 against bleed.
