### ISSUE TITLE
GPS Icon Not Removed for Dead Unit

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#16200]
Hey, 

I was playing a team game and there was a mysterious GPS icon that had no unit attached to it. Force firing the tile didn't remove it either.

Upon watching the replay, it appears a hijacked unit died there. Maybe it's a bug related to hijackers?

[GPS_Bug.zip](https://github.com/OpenRA/OpenRA/files/2858059/GPS_Bug.zip)

Hijacked unit dies at about ~13:30, in top left ore patch. You can reference the picture below for the location as well.

![000404](https://user-images.githubusercontent.com/42915475/52674476-b4649f00-2ef1-11e9-990b-778567953aab.png)
![000403](https://user-images.githubusercontent.com/42915475/52674477-b4649f00-2ef1-11e9-8803-787da7a4b374.png)

**Comment by reaperrr** [comment]
I guess we should try to fix this for the release.

**Comment by pchote** [comment]
This can be reproduced by hijacking a unit and then killing it.
