### ISSUE TITLE
Commit 25696 (f91d3f2) test warning: OpenRA.Utility(1,1): Warning: Actor type `harv` grants conditions that are not consumed: no-ore

### ISSUE THREAD

**Issue by fusion809** [OpenRA/OpenRA#16208]
### Issue Summary
Test suite gives the warning:

```bash
OpenRA.Utility(1,1): Warning: Actor type `harv` grants conditions that are not consumed: no-ore
```

for both "Drop Zones" and "Drop Zones - Battle of Tikiaki". 

#### System Information
- **Operating System:** NixOS 19.03pre
- **.NET / Mono Version:** Mono 5.16.0.220. 
- **OpenRA Version:** commit no 25696 (f91d3f2603bbf51afaa89357e4defcdc36138102)
- **Mod:** Red Alert.

**Comment by fusion809** [comment]
And yes this warning also appears in the Travis log at line 2037: https://travis-ci.org/OpenRA/OpenRA/builds/493785773#L2037.

**Comment by reaperrr** [comment]
@pchote: In addition to @obrakmann's attempt, I've locally tried
- nulling Harvester.EmptyCondition (`-EmptyCondition:`)
- emptying Harvester.EmptyCondition (`EmptyCondition:`)
- nulling `Harvester` and then redefining it, just without `EmptyCondition`

The first two had no effect, the 3rd gave an "Actor harv is not constructible: (...) Missing: (...).HarvesterInfo".

So I'm out of ideas as well. I doubt we want to dabble with the parser this short before the release, so I guess it's either you have an idea that works or we defer to Next+1.

**Comment by pchote** [comment]
I had a quick look at this a few days ago and found that there is definitely something wrong with the yaml merging - the resolved rules has both `RequiresCondition` and `-RequiresCondition`. Haven't had time to think about it further since then. At the least we could add in a dummy `ExternalCondition` to suppress the warning.

**Comment by pchote** [comment]
Here are a couple of testcases demonstrating the bug:
```csharp
		[TestCase(TestName = "Merged yaml files should be able to remove nodes")]
		public void MergedNodeRemoval()
		{
			var baseString = @"
Parent:
	Child:
		Key: value
";

			var mergeString = @"
Parent:
	Child:
		-Key:
";

			var resultString = "Parent:\n\tChild:";
			var baseYaml = MiniYaml.FromString(baseString);
			var mergeYaml = MiniYaml.FromString(mergeString);

			var resultYaml = MiniYaml.Merge(new[] {baseYaml, mergeYaml});
			Console.WriteLine(resultString);
			Assert.AreEqual(resultString, resultYaml.WriteToString());
		}

		[TestCase(TestName = "Merged yaml files should be able to remove nodes from inherited parents")]
		public void MergedInheritedNodeRemoval()
		{
			var baseString = @"
^Base:
	Child:
		Key: value
Parent:
	Inherits: ^Base
";

			var mergeString = @"
Parent:
	Child:
		-Key:
";

			var resultString = "^Base:\n\tChild:\n\t\tKey: value\nParent:\n\tChild:";
			var baseYaml = MiniYaml.FromString(baseString);
			var mergeYaml = MiniYaml.FromString(mergeString);

			var resultYaml = MiniYaml.Merge(new[] {baseYaml, mergeYaml});
			Console.WriteLine(resultString);
			Assert.AreEqual(resultString, resultYaml.WriteToString());
		}
```

Interestingly, only the first case fails.

**Comment by pchote** [comment]
It looks like https://github.com/OpenRA/OpenRA/blob/72c90d84a86514588af8daed9502bbe3108f24a6/OpenRA.Game/MiniYaml.cs#L322 is the problem here - `MergePartial` must be followed up with a `ResolveInherits` to process removals, but this doesn't appear to be happening when we merge over a node that is not inherited from a parent.

**Comment by pchote** [comment]
The simplest short-term workaround might be to remove the Drop Zone maps from the official list - we've carried these for years, but theres little evidence that players actually play these. https://master.openra.net/map_stats?hash=7e1a7a59689a5c9964a1d28741dc9f85d66f4166 shows a total of **9** games on release-20180923/release-20181215.

**Comment by matjaeck** [comment]
If we drop it because it is not played I have no objections, but I feel bad to drop it to hide that something is wrong (most users will never see this warning and we can track this issue here).

**Comment by FrameLimiter** [comment]
These maps have no ore, so why not just subtract all the harvester related traits? Or better yet just remove the HARV altogether and use the DTRK instead w/RenderSprites -> harv.

Also:
∙There are no engineers on these maps, so the reusable engineer checkbox shouldn't be visible.
∙Dogs no longer insta-kill, so the DogJaw warhead needs to be adjusted to kill the custom-HP shok & dog.

```
UNITCRATE:
	GiveUnitCrateAction@dtrk:
		SelectionShares: 1
		Units: dtrk

DTRK:
	Tooltip:
		Name: Bomb Truck
	Mobile:
		Locomotor: heavywheeled
	Armor:
		Type: Heavy
	Explodes:
		Weapon: CrateNuke
		EmptyWeapon: CrateNuke
	RenderSprites:
		Image: harv

Player:
	LobbyPrerequisiteCheckbox@REUSABLEENGINEERS:
		Visible: False

#weapons/other.yaml
DogJaw:
	Warhead@1Dam: TargetDamage
		Damage: 100000
```

**Comment by pchote** [comment]
Using DTRK with the DTRK artwork would be better still, IMO.  @FrameLimiter would you be interested in putting together a PR with these changes?

**Comment by FrameLimiter** [comment]
Probably better if someone else does it; I don't have github software installed and can't squash using the web interface.

**Comment by GraionDilach** [comment]
Why is this ticket closed if https://github.com/OpenRA/OpenRA/issues/16208#issuecomment-466214396 still exists and is a problem? Why doesn't it have it's own ticket to be tracked then?

**Comment by reaperrr** [comment]
It does now: #16278
