### ISSUE TITLE
Rocket dmg is inconsistent

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16202]
It's mostly visible with migs, normally 4 migs can insta-kill a harvester, sometimes they don't

![migs](https://user-images.githubusercontent.com/37534529/52713222-6c9c5100-2f9f-11e9-9009-dce17f78913f.gif)

in this gif first 2 rockets hit for 8050 each
then when the next 2 rockets hit at the same time and it shows as if only one hit for 8050
harvester starts moving
fifth rocket hits for 6359
sixth 1932
and when the last 2 ones hit it shows them as one 8050

It may be caused by increased innacuracy on maverick missiles 0c128 -> 0c512 In this gif it seems as if those missiles hit the truck directly on the edge of the collider

You can not really avoid missing with good micro and it hits perfectly 95% of the time, that's why I call it an inconsistency 

The other offender are the tusk missiles as their speed is bigger and infantry hitboxes smaller, you can see it best against standing/moving tania. Other than that other missiles miss very rarelly

**Comment by GraionDilach** [comment]
Missile projectiles are proximity by default and explode if they are within `CloseEnough` radius of a target (default value is 298 world units, ~1/3 cell) and this is a side effect of that. Enabling `AllowSnapping` logic can change this (#12437), but it might cause heavy balance implications.

**Comment by gdavegdave** [comment]
The ore truck kited the missile. I see no issue here.

**Comment by reaperrr** [comment]
@Punsho Maverick inaccuracy was reduced considerably with the last release, do you still consider this enough of an issue to leave this open or can we close this?

**Comment by Punsho** [comment]
Should open a new issue for other rockets as this was mainly focused of migs
