### ISSUE TITLE
Harvesters keep moving downwards

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16205]
Harvesters when placed on a map with no ore in scanning range keep moving downwards. It happens with AI/player owned harvesters
![harvesters](https://user-images.githubusercontent.com/37534529/52856538-5a501d80-312d-11e9-8ef7-1abf7b8d3b76.gif)

![harvs2](https://user-images.githubusercontent.com/37534529/52863738-48787580-3141-11e9-84e9-ee8db6825950.gif)

![harv3](https://user-images.githubusercontent.com/37534529/52864594-23850200-3143-11e9-83c7-6df23bccfc35.gif)

**Comment by MCV3000** [comment]
No ore and no ore mine ?
Maybe related to this : https://github.com/OpenRA/OpenRA/issues/11508#issuecomment-228157312

**Comment by Punsho** [comment]
There is ore on that map, just not in scanning radius

**Comment by MCV3000** [comment]
Oh ok.
It's more related to https://github.com/OpenRA/OpenRA/issues/9232#issuecomment-137237767 then.

**Comment by Punsho** [comment]
IMO they should stay in place and casually scan if ore appeared in said range

**Comment by Punsho** [comment]
![harv4](https://user-images.githubusercontent.com/37534529/52867281-37cbfd80-3149-11e9-9864-0553a4807c87.gif)
