### ISSUE TITLE
[TD] 2 in 1: a) Support Plane is not go away  b) Units stay over factory in one mapcell

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#16239]
a) Purple Player's Plane PWin
b) Red Player's units
See replay: https://cloud.mail.ru/public/37bE/LobyAByxd

**Comment by abcdefg30** [comment]
Closing as discussed in https://github.com/OpenRA/OpenRA/pull/16574#issuecomment-494421514. Please reopen this in case you find a new reproduction case.
