### ISSUE TITLE
Lack of Audio Cue For your Own Units being Hijacked

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#16243]
When your vehicles are hijacked, there is no audio cue it's occurred. This is particularly a problem when you lose harvesters.

**Comment by crysman** [comment]
if this is true, +1 to implement

**Comment by matjaeck** [comment]
We could try to merge the "Unit (ready)" and "(Credits) stolen" notification into a new "Unit stolen".

**Comment by GraionDilach** [comment]
[unitsto.zip](https://github.com/OpenRA/OpenRA/files/2928172/unitsto.zip)

**Comment by matjaeck** [comment]
https://vocaroo.com/i/s0qnZOTPcE03

**Comment by netnazgul** [comment]
What if we just use "Unit lost" with this? Implementing an explicit custom sound for just one situational unit seems a little bit too much.

**Comment by matjaeck** [comment]
The original game had harvester specific notifications, at least the german version had IIRC a "Sammler wird angegriffen" (harvester under attack) notification.

**Comment by Smittytron** [comment]
I agree with using 'unit lost' here. I don't like deviating from original assets when we don't have to.

**Comment by cjshmyr** [comment]
'Unit stolen' is currently used when you steal a unit, I like 'unit lost'.
