### ISSUE TITLE
Infiltrating barracks still gains veterancy on infantry spawning in pillboxes 

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#16242]
### Issue Summary
Infantry spawned inside of a pillbox still gain veterancy from spy infiltration, given that infantry in pillboxes no longer gain experience, this doesn't seem like the desired behaviour, and has always been an overpowered feature IMHO.
... ... ...

#### System Information
- **OpenRA Version:** playtest-20190209
- **Mod:** Red Alert

#### Steps to reproduce
  1. Infiltrate enemy barracks with a spy
  2. Build a pillbox
  3. Undeploy the infantry from the pillbox, it will show 1 chevron

**Comment by GraionDilach** [comment]
Veterancy has no effect within the pillboxes anymore, and it would be inconsistent that the rifleman received through a pillbox would not benefit from the free level any trained-from-barracks infantry would.

For reference: building survivors in RA2 also received the free level.

**Comment by AMHOL** [comment]
Cool, didn't know that veterancy didn't have an effect in pillboxes, thought that switching out the infantry for vetted infantry still gave the performance boost, good to know.

Closing issue.

**Comment by GraionDilach** [comment]
Oh, apparently I mixed it up - infantry in pillboxers can't gain experience but their damage ouput is still affected by the previous experience they gathered.

ŐPinging @Smittytron - you need to disable all boosts on infantry with the pillboxcondition to change this.

**Comment by matjaeck** [comment]
Voting for reopening this unless someone files a more specific issue with ^.

**Comment by Smittytron** [comment]
We nerfed pillboxes heavily by suppressing experience gain, but with the understanding that if you take the time to switch in more veteran riflemen you'll get stronger pillboxes. This is working as intended.

**Comment by pchote** [comment]
IMO the issue is more subtle than that, and we don't necessarily need to break that aspect of it.  The question is whether it is balanced for spy infiltration against the barracks to give pillboxes a buff in addition to infantry.

**Comment by Smittytron** [comment]
IMO the automatic buff is a good perk to encourage more spy use. It's still nothing like a fully vetted rifle in a pillbox.

**Comment by matjaeck** [comment]
> The question is whether it is balanced for spy infiltration against the barracks to automatically buff newly placed pillboxes in addition to just infantry.

IMO infiltrating barracks should grant better infantry but have no effect to base defences. 

> We could disable the initial veterancy for the infantry spawned in pillboxes without disabling the buffs when manually swapping a vet infantry in.

> IMO the automatic buff is a good perk to encourage more spy use. It's still nothing like a fully vetted rifle in a pillbox.

It is from my perspective conceptually inconsistent though: If you take the perspective that the pillbox is as good as the rifle inside it and apply the concept that rifles become better the more they kill, then rifles in pillboxes should rank up, maintain their (initial) rank boosts in a pillbox, and increase the pillboxes effectiveness in return. 

The concept I prefer is that pillboxes are entities with their own immutable properties (other defences can not rank up) and rifles only "enable" them.

**Comment by abcdefg30** [comment]
This seems to work as intended to me and the discussion has died down.
