### ISSUE TITLE
Defence build times are inconsistent

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16250]
Flame tower, turret, SAM site all have longer build times then the rest. Defences open fire almost at the instance they are built and one needs to nail down the exact time to control those shots. The problem is that It's hard to switch between controlling a pillbox and a ft as ft has around double it's build time.

I personally think that it's best to fix it by allowing structures to queue up attacks while they are building (you currently can not target anything). It is also possible to fix it by making all build times the same

![pill](https://user-images.githubusercontent.com/37534529/53621130-26312e00-3bfe-11e9-9cce-18ba85c4973d.gif)
![cpill](https://user-images.githubusercontent.com/37534529/53621131-27625b00-3bfe-11e9-90a7-527fa2244277.gif)
![flame](https://user-images.githubusercontent.com/37534529/53621132-2a5d4b80-3bfe-11e9-92fa-cdc1ca5ba3de.gif)
![tesla](https://user-images.githubusercontent.com/37534529/53621153-406b0c00-3bfe-11e9-9219-ad9f353a7679.gif)
![turret](https://user-images.githubusercontent.com/37534529/53621157-4365fc80-3bfe-11e9-8e3a-23211182632d.gif)
![aagun](https://user-images.githubusercontent.com/37534529/53621158-44972980-3bfe-11e9-9f9e-2ee9c04b930a.gif)
![sam](https://user-images.githubusercontent.com/37534529/53621160-45c85680-3bfe-11e9-9ec4-f2f4ce25a213.gif)
![gap](https://user-images.githubusercontent.com/37534529/53621161-47921a00-3bfe-11e9-8556-7461e937afc7.gif)

**Comment by matjaeck** [comment]
I am not a fan of the ideal that is brought up in many recent issues to make the game flat and standardise the differences - IMO these "inconsistencies" are factors that should be used to balance a game instead of eliminating them by making them "consistent".

**Comment by Smittytron** [comment]
I've never once had a problem controlling my flametowers on construction. I just don't see an issue here.

**Comment by Punsho** [comment]
Spamming attack orders helps but I don't think that should ever be a good solution. I agree as they are part of balance but I as I previously mentioned, I think it's best just to let them queue up attacks while they are building instead of blocking interactions

**Comment by pchote** [comment]
> I personally think that it's best to fix it by allowing structures to queue up attacks while they are building

This is covered by a followup that I had planned to do after #15743 - going through all the mods and implementing consistent behaviour for pausing or disabling structure functionality until the buildup is complete.  So power plants would only start giving power once they are properly built, defenses could target but would only fire once fully built, production would be queued but only actually start ticking once fully built, and so on...

In the end, I realized that this was going to cause more grief and complaints from players who had built their micro around the current behaviours than it was really worth.

**Comment by Punsho** [comment]
@pchote  Did you try gathering feedback from players? I'd be highly positive if these changes were implemented

**Comment by MustaphaTR** [comment]
>  I am not a fan of the ideal that is brought up in many recent issues to make the game flat and standardise the differences - IMO these "inconsistencies" are factors that should be used to balance a game instead of eliminating them by making them "consistent".

Altho the idea here makes sense, i disagree for this case. This is just a complately unnecessary inconsistency that should be fixed.

> I've never once had a problem controlling my flametowers on construction.

Effect of this to balancing would be a little to none, but imo this is just an unnecessary inconsistency. If fixed can be fixed under the name of polishing instead of balance.

**Comment by matjaeck** [comment]
> This is just a complately unnecessary inconsistency that should be fixed.

Flametowers deal more damage per attack then pillboxes do, but pillboxes have higher rate of fire. We can balance the initial dps when placing the structure by allowing the pillbox to attack earlier than the flametower can.

IMO some building animations also look better at a specific speed than others (pb vs ft).

**Comment by PunkPun** [comment]
Addressed by #19731
