### ISSUE TITLE
OpenRA starts only if localSupportDir exists on Windows 10 Build 18346

### ISSUE THREAD

**Issue by QuadlessPyjack** [OpenRA/OpenRA#16267]
### Issue Summary
On first install, game hangs on start because it can't write to C:\Users\<username>\OneDrive\Documents

#### System Information
- **Operating System:** Windows 10 Pro Build 18346.19h1
- **.NET / Mono Version:** Latest
- **OpenRA Version:** latest master branch build as well as bleeding branch build at commit: 7d72aae
- **Mod:** All mods (anything trying to write to [username]\OneDrive\Documents will cause this error)

#### Additional Information:
- Steps to reproduce
	1. Download and build master release
	2. Start game from VS2017 with debugger attached and relevant System.IO exceptions enabled
	3. The logging system will throw FileIO exceptions in cascade for each [CHANNEL].log file it tries to create
        4. Downloaded game content extraction will fail with FileIO exceptions

- Logs 
[debug.log](https://github.com/OpenRA/OpenRA/files/2928629/debug.log)
Please note that the debug.log file had to be manually created first. Furthermore, it seems that not all IO exceptions were logged. This could be a breaking change caused by Microsoft when they moved the Documents folder inside OneDrive. Getting the Documents folder from the C# API will return [Username]/OneDrive/Documents. Now I know this is an Insider Build of Windows so it may not be on your priority list for support and I can totally understand that, however, it might be of great use for others like me to know that creating a "Support" folder inside GameDir solves this issue.

**Comment by pchote** [comment]
Is this a new preview-build windows feature (note: I don't use Windows)? I haven't seen any reports of this kind of issue before for OpenRA, and searching online for windows onedrive documents just gives a bunch of marketing for MS Office.

**Comment by QuadlessPyjack** [comment]
I'm not sure exactly from what build onward Microsoft decided to backup the user folder by moving folders such as Documents inside OneDrive but its been like this since at least the Fast branch of Insider builds from November 2018 afaik. Can't remember a specific build version unfortunately.

**Comment by GraionDilach** [comment]
Doesn't look new to me.

https://support.office.com/en-us/article/files-save-to-onedrive-by-default-in-windows-10-33da0077-770c-4bda-b61e-8c8e8ca70ac7

 I just guess noone uses OneDrive and this is basically just another reason to move out OpenRA stuff from Documents.

**Comment by reaperrr** [comment]
@pchote As far as I can tell going by my own user data, newer games seemingly store their equivalents of everything except *content* (which is normally put into the game directory directly) in
> C:\Users\*username*\AppData\Local\*gamename*

**Comment by MustaphaTR** [comment]
AppData definetly exists in Win7, and i don't think we care about anything older.

**Comment by reaperrr** [comment]
We've definitely had reports of problems with the Documents folder even before this OneDrive issue (for example #13978), and who knows how many people who never had an OpenRA installation before try to install it and then give up on errors like this without filing a bug report.
I think this should be adressed for next release.

**Comment by pchote** [comment]
An easy workaround until we can deploy a proper fix is to add `Engine.SupportDir=C:\your\custom\path` to the game launch shortcuts.
