### ISSUE TITLE
Apache (NOD helicopter) stops guarding after killing enemy unit

### ISSUE THREAD

**Issue by crysman** [OpenRA/OpenRA#16263]
Apache (NOD helicopter) stops guarding after killing enemy unit

#### System Information
- **Operating System:** Ubuntu 18.04
- **.NET / Mono Version:** Mono JIT compiler version 5.18.0.268 
- **OpenRA Version:** latest playtest downloaded today
- **Mod:** Tiberian Dawn

#### Additional Information:
- Steps to reproduce
	1. buy a topter
	2. order it to guard a harvester
	3. let the enemy attack harvester with its unit
        4. once unit is killed, apache stops guarding

**Comment by tovl** [comment]
This looks to be a duplicate of #11439, which will be fixed by #16105.

**Comment by pchote** [comment]
Thanks for the report! Closing as duplicate of #11439.
