### ISSUE TITLE
Units group selection issue - Wrong (previously selected) group taking move order

### ISSUE THREAD

**Issue by michuzet** [OpenRA/OpenRA#16275]
### Issue Summary

As in the title of this topic. Issue appeared in game several OpenRA versions ago, it begins with one update in 2017. I've been waited for solution without rising new issue-bug on GitHub hoping that it's more popular than it's in reality, but non of the newer versions solved the issue.

#### System Information
- **Operating System:** Fedora 28/29; kernel 4.20.13-200.fc29.x86_64 and olders to 4.16.xx-xxx
- **.NET / Mono Version:** 5.18.0.268-0.xamarin.3.epel7.x86_64
- **OpenRA Version:** playtest-20190302 and olders to approx. 2017xxxx
- **Mod:** Red Alert

#### Additional Information:
- Steps to reproduce
	1. Select units and assign to group "1"
	2. Select other units and assign to group "2"
	3. Select "1" group by number key and give attack move order
	4. Select "2" group by number key and give move order - ISSUE (group "1" taking move order instead of selected group "2")

**Comment by matjaeck** [comment]
I can't reproduce this in release-20190314.

**Comment by michuzet** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  It's still there, checked today. Are you using Linux distro?                                                                                                                                                                         Pozdrawiam / Kind regardsMichal Szczep----------Sent from my BlackBerry device                                                                                                                                                                           Od: notifications@github.comWysłano: 17 marca 2019 20:27Do: OpenRA@noreply.github.comOdp. do: reply@reply.github.comDW: michuzet@gmail.com; author@noreply.github.comTemat: Re: [OpenRA/OpenRA] Units group selection issue - Wrong (previously selected) group taking first move order (#16275)  I can't reproduce this in release-20190314.

**Comment by matjaeck** [comment]
Yes, I'm on Ubuntu 18.04. Would it be possible for you to provide a gif that shows your input (bottom command bar) and the resulting described behavior?

**Comment by michuzet** [comment]
I can provide my messenger's address and live-stream my activity:
Skype -> Michu_z
Jami -> da38349a0a0de910c592ec38a465e229d6c80243 (michuzet)

**Comment by michuzet** [comment]
I'm on Ubuntu 18.04.3 now, release-20190314 - The bug remained.

**Comment by abcdefg30** [comment]
Actually, this is very easy to reproduce. Just select one unit and activate an order generator like the attack move one and then change your selection. The order generator caches the wrong set of subject actors!

**Comment by michuzet** [comment]
No, it's not solved. Another (and another) stable release rolled out and still basic game functionality does not work well (it's completely fu**** up honestly).

I think I need to send you a link to the recording showing the errors of a-move commands. Soon I will upload one.

**Comment by pchote** [comment]
If you'd given us this feedback (and yes, please provide a recording) during the last three months of playtesting we may have been able to fix your specific problem before the release came out. We do our best based on the information we have available, and as far as we know the problem was fixed.

Please remember that there are humans at the other end of these GitHub issues, there is no need to be rude.
