### ISSUE TITLE
Cannot start without sound

### ISSUE THREAD

**Issue by JasperCiti** [OpenRA/OpenRA#16284]
[exception-2019-03-09T032805Z.log](https://github.com/OpenRA/OpenRA/files/2948050/exception-2019-03-09T032805Z.log)

I could not understand why Red Alert won't launch and previously it did. Learned the hard way after many hours of frustration that my headphones were plugged out. After plugging it back in the game launched successfully!

I assume it is not possible to play OpenRA without sound because of an OpenAL bug.

Please (even if you don't fix the issue) at the very least display a more useful error that just "Fatal Error" or some sort of warning/reminder to check the speakers/headphones.

**Comment by abcdefg30** [comment]
This has been resolved since.
