### ISSUE TITLE
Map editor search input not disabled when changing tab

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#16282]
Causes unexpected behavior when you use keyboard scrolling and can not see that the reason scrolling doesn't work is that you are writing input in a disabled tab.

**Comment by deleted-user-1** [comment]
This is a real edge case, nobody uses keyboard scrolling these days. The search and tab widget logic is isolated from each other so fixing this does not seem super trivial. Can be closed IMO.

**Comment by PunkPun** [comment]
This is no longer an issue

**Comment by PunkPun** [comment]
My bad, misunderstood the issue. It's still a problem but can be seen as a reverse duplicate of #19761

**Comment by dragunoff** [comment]
A solution to #19761 is nowhere near so in the meantime this can be patched up. Should be simple.
