### ISSUE TITLE
CreateEffectWarhead does not properly account for untargetable actors

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#16308]
~No visual impact explosion. Only smudge is spawned.~
~Probably a regression.~

~If debugging and fixing it turns out to be easy, maybe sneak it into release.~

`CreateEffectWarhead` currently considers actors 'invalid' (and therefore doesn't trigger) not only if their target types are invalid, but also if they have no (enabled) targetables at all.
However, in that case it would often actually give better results if those untargetable actors were instead simply ignored completely, so the terrain below can be taken into consideration instead.

**Comment by reaperrr** [comment]
Strangely enough, this seems to only affect the first plane of an airstrike.

**Comment by reaperrr** [comment]
It looks like setting `ImpactActors: false` on the effect warhead helps, but that would break the ground/water separations.

The fact that it helps indicates that there's an actor in the impact area that is considered invalid, and the only logical candidate is the camera actor.

**Comment by reaperrr** [comment]
I think I figured out what the problem is:
If the 'y' value of SquadOffset on AirstrikePower is zero and the squad is 3+ in size, 2 planes will fly on the exact same WPos, meaning they'll be shot down and crash at the exact same tick and WPos too, invalidating each other's explosion (husks aren't targetable => invalid target).

If that's the case, I guess we should (at least optionally, perhaps even by default) completely ignore (as if they weren't even there) actors without (enabled) targetables in CreateEffectWarhead, rather than considering them an 'invalid target'.

**Comment by matjaeck** [comment]
Can you confirm it's a regression?

**Comment by reaperrr** [comment]
No, it actually isn't. I'll remove the label.
