### ISSUE TITLE
RA shellmap regressions

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#16307]
The allied water transport no longer leaves after unloading. It also doesn't seem to unload all vehicles (one time I observed it only unloading 2 medium tanks, and then just sit there).

Not sure if this is a lua regression or a problem with unloading.

**Comment by pchote** [comment]
Likely introduced by #16060?

**Comment by tovl** [comment]
Very likely. I'll look into it when I have the time.
