### ISSUE TITLE
Remove retaliation from opportunity fire

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16309]
Currently turreted units should constantly switch target to an actor that is attacking them if not given an explicit attack order. Move order cancels said attack order.
In this gif I targeted the war factory and gave a move order to the tank

![TurretBug](https://user-images.githubusercontent.com/37534529/54382447-ad6bb080-4698-11e9-9c50-349d2e782ff9.gif)

Tanks target switches to to the flak even though no such order was given nor the wf got out of range

Retaliation fire is inconsistent over all. Quote from Netnazgul
> on defence stance the tank SOMETIMES switches to other stuff
i.e. my light tank switched attacking ore truck instead of ref
but my med tank kept attacking a power plant even being viciously attacked by flamer, rifle and grenadier from all sides

In my opinion turreted units, all units should not switch targets on their own. They are chess pieces pieces after all, not live creatures. My tank switching target on it's own to a riflemen instead of the ordered tank is just bogus. I want to give a target to a tank and then move him to a better position, currently my ability to do that depends on luck.

**Comment by pchote** [comment]
I have a simple fix in mind here. Adding to the milestone so that we don't forget about it.
