### ISSUE TITLE
Make it easier to distinguish system chat messages and user chat 

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16310]
Recently an increasing number of players mimic system chat messages ("Battlefield Control: Player XY (team z) has disconnected") at game start and unfortunately sometimes other players then leave the game because they didn't notice it was trolling. This would probably not happen if the system chat messages would visually stand out.

**Comment by abcdefg30** [comment]
We could color the player names in their color.

**Comment by Punsho** [comment]
They are already coloured but people don't notice. Also one can switch their colour to be close to grey

**Comment by abcdefg30** [comment]
Ops, I figured we didn't since it should be pretty obvious what is what with colors. Are there any suggestions on how to fix this?

**Comment by matjaeck** [comment]
Sorry, duplicate of #16231.

**Comment by matjaeck** [comment]
> Are there any suggestions on how to fix this?

Treat these messages like other debug/status messages and put them in a separate widget. https://github.com/OpenRA/OpenRA/issues/16148#issuecomment-460193832

**Comment by teinarss** [comment]
Whats your opinion on making these messages yellow? (is defeated should also be yellow) And moved the transient messages to their own window.
![image](https://user-images.githubusercontent.com/19173272/54625583-d791e980-4a6f-11e9-8c21-40489e3f922d.png)

**Comment by matjaeck** [comment]
Could we 
- remove the "Battlefield Control" Prefix from the messages in the upper left? 
- limit the history in the upper left window to two messages that individually fade out after some seconds?
- color all system messages in the same color?

**Comment by teinarss** [comment]
And also of thinking to add the warnings you get from airstrike / nuclear
bomb support powers to the transient messages.

**Comment by pchote** [comment]
Yellow looks good IMO.

IMO the transient messages should be limited to one line, and be rendered possibly in bold immediately above the chat instead of in a disconnected section.

**Comment by teinarss** [comment]
Pchote do we really want to limit it to one line? I was thinking to add
some of the speach warnings to this widget and it would bigger chance to
miss them if there is only one line visible.

**Comment by teinarss** [comment]
Im guessing you mean something like this, but only one line?
![image](https://user-images.githubusercontent.com/19173272/54710431-f4015500-4b47-11e9-8fe9-81859b194a8e.png)

Should we align to the text or to the border of the chat?
![image](https://user-images.githubusercontent.com/19173272/54710467-07acbb80-4b48-11e9-9d28-64b06c98010a.png)

**Comment by matjaeck** [comment]
I'd say align by text and limit it to 3 lines.

**Comment by pchote** [comment]
IMO drop the "Battlefield Control" from the transient messages and give them a custom format (bold?)

**Comment by teinarss** [comment]
So something like this then
![image](https://user-images.githubusercontent.com/19173272/54883765-8d42ab00-4e69-11e9-8fb6-ed466f54aacf.png)
