### ISSUE TITLE
Aircraft refactor

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#16338]
This is a large untertaking spanning over several PRs, many of which depend on others, and sometimes the review process reveals things that are better split off/taken care of first, before continuing on a specific PR.

Out of the currently open PRs, the order of reviewing/merging is supposed to be:

- ~#16241, #16315~
- ~#16365 (depends on #16241 and #16315)~
- ~#16400 (depends on #16369)~
- rest of #15803's activity merging part, not as-is but split into some more smaller PRs
- #15873 (should be easier to get right when all Heli* activities are gone)

Also closes
- [ ] #13746
when done.

Related PRs:
- Refactor `Reservable` into `Dock` #16470
- Move all of `Aircraft`'s resupply handling to a central `ResupplyManager` #16446

**Comment by reaperrr** [comment]
Ping @obrakmann

**Comment by matjaeck** [comment]
> Note: I haven't decided yet, but I might split off more of the activity merging from #15803 like I did with #16241, if I get the feeling that issues with #15873 block progress for too long.

Would appreciate this for reviewing ingame.

**Comment by reaperrr** [comment]
Updated.

**Comment by tovl** [comment]
It might be a good idea to take #16315 into account here as well. The changes to `Land` and `HeliLand` there will make them more similar to each other so #16365 might want to depend on that.

**Comment by reaperrr** [comment]
Makes sense, yes.
