### ISSUE TITLE
Helicopter Landing

### ISSUE THREAD

**Issue by TheMightyAltroll** [OpenRA/OpenRA#16331]
Creating a transport helicopter **without** 'landwhenidle' toggled on, seems to be eluding me. The helicopter refuses to land to embark units. What am I doing wrong? Is there a condition for 'awaiting passengers' that allows me to enable landwhenidle?

**Comment by tovl** [comment]
You aren't doing anything wrong. Currently there is no way to create a transport helicopter without landwhenidle because there is no separate logic to make the helicopter land when units try to embark. This would need to be added to the engine.

**Comment by pchote** [comment]
This is on my list as a candidate for the next release, tied in with the creation of a new Soviet helicopter transport for RA.

**Comment by TheMightyAltroll** [comment]
> This is on my list as a candidate for the next release, tied in with the creation of a new Soviet helicopter transport for RA.

Nice. Also, the HIND would work well as a transport with reworked weapons, because irl it carried a compliment of 5-8 troops. I'm kind of normalizing Soviet/Allied factions in what they get, and adding some more units myself to my own little personal mod. It didn't make any sense to me that things like SAMs had less range than AA guns, or V2 Rockets had less range than artillery, or that the Hind was on the allies. So I've been making it a little tiny bit more 'realistic' while also trying to keep the fun of RA. I also wanted to make it less 'unit spam' and 'base creep' oriented. Recently I made sandbag walls provide limited cover to units from incoming fire.
