### ISSUE TITLE
Vision is buggy if it's ending higher then c64

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16334]
I have increased vision and weapon range of all infantry by half a cell (to look nicer) taking the example of the recent dog vision change
here's the bug 
![VisionBug](https://user-images.githubusercontent.com/37534529/54815643-240d3d00-4c9b-11e9-8e8a-d302317a14e3.gif)
Cells behind the soldiers don't go dark

It doesn't happen with a single soldier, rather a full 5 stack. Can be easily reproduced with dogs
I got this number by halfing a cell until this bug didn't was no longer present

**Comment by St3x** [comment]
Yes, cells behind five soldiers don't go dark if you move them to an adjacent cell.
It works only if you have a "full stack" in one cell, so you pay for it.
It's more like a (hidden and pro) feature than a bug.
See https://github.com/OpenRA/OpenRA/issues/14979.

**Comment by Punsho** [comment]
This would make early game significantly more stale. So nor I nor I think most of the competitive players would want this feature
