### ISSUE TITLE
Tesla coil returns fire to actors that are in fow

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16335]
This is a long standing bug
After my tesla coil gets hit by by an enemy tesla coil which is hidden in fow, mine will automatically retaliate 
![TeslaBug](https://user-images.githubusercontent.com/37534529/54816393-c7ab1d00-4c9c-11e9-9963-3038ed4cb9d5.gif)

**Comment by ZxGanon** [comment]
Yeah this is a nasty one. Artillery attacking TC while being in range of the Tesla Coil (but outside of it´s vision range) also get attacked.

So it counts not just for buildings but also for units attacking them.
