### ISSUE TITLE
Implement Stance checks in AutoTargetPriority

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#16342]
In RV the tesla troopers are automatically targeting the tesla coils to charge them makes it so if you have a tesla coil in the rally-point/attack-move path they go charge the coil instead of going to the rally-point/actual a-move target. ValidStances value in AutoTargetPriority could allow us to make them incapable of auto-targeting them during an a-move while still allowing them to target enemy coils.

**Comment by pchote** [comment]
If i'm not interpreting your request wrong, this is already supported.
`AutoTarget` lets you define a condition to activate in each stance. These conditions are then used to activate/disable `AutoTargetPriority` traits.

**Comment by MustaphaTR** [comment]
Not that stance, as in Ally, Neutral, Enemy.
