### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by tovl** [OpenRA/OpenRA#16370]
### Issue Summary
Cannot compile bleed anymore on Linux Mint 18.2 and Mono 5.18.0.240. Here is the console output:

CSC OpenRA.Game.exe
OpenRA.Game/FileFormats/Png.cs(18,31): error CS0234: The type or namespace name 'Checksum' does not exist in the namespace 'ICSharpCode.SharpZipLib' (are you missing an assembly reference?)
Makefile:291: recipe for target 'OpenRA.Game.exe' failed
make: *** [OpenRA.Game.exe] Error 1

**Comment by teinarss** [comment]
You will need to re download all the dependencies, 
run 
```
make clean
make d
```

**Comment by aaronfranke** [comment]
@teinarss The second command doesn't work:

    $ make d
    make: *** No rule to make target 'd'. Stop.

However, just running `make` worked after running the first command you posted.

**Comment by teinarss** [comment]
@aaronfranke 
`make d` is a shortcut command for `make dependency`

**Comment by abcdefg30** [comment]
I think that only works on Windows.
