### ISSUE TITLE
Infantry on TS shellmap gets stuck

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#16373]
The longer the shellmap runs, the more GDI infantry gets 'stuck' somehow before the GDI base.

They don't even show an idle animation or react to fire, so I suspect some activity doesn't properly finish. In any case, that's a regression and might affect more than just TS.

**Comment by abcdefg30** [comment]
Is this still an issue?

**Comment by reaperrr** [comment]
Doesn't look that way, no.
