### ISSUE TITLE
Honor special cases for order voices of GrantConditionOnDeploy

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16434]
#16431 adds an order voice for the deploy command for units that have the `GrantConditionOnDeploy` trait. There are some special cases that need to be taken into account, for example the RA demo truck that needs its deploy order voice removed.  Other units across the mods might also require modifications.

**Comment by pchote** [comment]
IMO adding the missing voices to the Demo Truck and other units are bug fixes. Do you have specific cases in mind that should not be using voices?

**Comment by matjaeck** [comment]
I actually went ahead after your comment in #16431 and created this issue because my understanding was "these are bugs that need to be fixed but not in this PR". I apparently misunderstood this. Feel free to close if you think we don't need this.

**Comment by matjaeck** [comment]
Or even better, reopen if you think we need it.
