### ISSUE TITLE
Beacon circle animations don't loop on support powers

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#16436]
The circle animation is only played once.

While this was apparently originally intentional, I feel it looks a bit weird/buggy.

In my opinion the circle anim should loop for support power beacons as well.

**Comment by pchote** [comment]
The idea behind this was that it provided click feedback, like the move flash animation does for regular unit orders.

I don't have a strong opinion about keeping the current behaviour if there is a consensus to change it, but i'm concerned about the visual noise if everything on the beacon is animating.

**Comment by reaperrr** [comment]
OK, I guess I probably wouldn't get approval (or at least get very mixed reactions) on a PR that adresses this in the shipping mods, so I might as well close the issue.
