### ISSUE TITLE
Resupply activity can be interrupted by attack orders

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#16432]
It is not possible to repair a vehicle at a service depot while it is attacking. From https://github.com/OpenRA/OpenRA/pull/16352#issuecomment-485285822

> That's not really the fault of the activity, and should already be the case on bleed, too. We don't really want the activity to be uninterruptible.
>
> The only way to fix that and allow units to accept attack orders while continuing to resupply would be to scratch the concept of resupplying (or attacking...) via activity completely and do that entirely via ITick/trait logic.

**Comment by deleted-user-1** [comment]
The problem was that the repairpad is blocked but that is no longer the case in default mods since  #17141.

<details>

![repairblock](https://user-images.githubusercontent.com/59416324/90321239-20d9b780-df48-11ea-8dd5-ac4c2d2ce8e2.gif)
