### ISSUE TITLE
Build system: Makefile repeats itself a lot for mods

### ISSUE THREAD

**Issue by Artoria2e5** [OpenRA/OpenRA#16439]
### Issue Summary
The current Makefile (as of 20190314 at least) repeats itself to install many files associated with the three sanctioned mods (ra, cnc, d2k). This makes it not very convenient to have the Makefile create shortcuts for extra mods, which people packaging for cool, exciting, and volatile stuff will definitely want.

### Proposed solution
Some of the work can possibly be abstract away as Makefile variables. A possibly workable (but still tedious) way could be:

<details>
<summary>bad makefile code</summary>

```Makefile
# List of official mods to create links for: {MODID}:{MODNAME}
MODS            = ra:Red_Alert cnc:Tiberian_Dawn d2k:Dune_2000

# ...
install-linux-desktop:
	@$(INSTALL_DIR) "$(DESTDIR)$(datadir)/applications"
	@for MOD in $(MODS); do \
		MODID=$$(echo $$MOD | cut -d: -f1) MODNAME=$$(echo $$MOD | cut -d: -f2 | tr _ ' '); \
		sed -e "s/{MODID}/$$MODID/g" -e "s/{MODNAME}/$$MODNAME/g" -e 's/{TAG}/$(VERSION)/g' packaging/linux/openra.desktop.in > packaging/linux/openra-$$MODID.desktop; \
		$(INSTALL_DATA) packaging/linux/openra-$$MODID.desktop "$(DESTDIR)$(datadir)/applications" ;\
	done
	@-$(RM) packaging/linux/openra-*.desktop
```

</details>

The caveat is that the only way to pass groups of values in is to use some non-space separator (like `:`) and have the shell tear it apart; it quickly gets tedious with all the echos and cuts.

Assuming GNU bash as the shell on the builder machine might make it a bit more bearable with arrays and stuff, but… I don't know. I may send in a pull request later.

**Comment by pchote** [comment]
My next PR towards #15954 will be removing these targets from the Makefile completely - the compilation target will defer to `msbuild` and the new lean csproj format for compilation.

In any case, third party mods should be built using the [Mod SDK](https://github.com/OpenRA/OpenRAModSDK), which contains its own Makefile and packaging that ship the specific engine version required by the mod. Bundling distinct mods together using the same engine files is an anti-pattern that we discourage.

The SDK Makefiles are missing an install target, which makes life more difficult than necessary for downstream packaging. You could file an issue for this on the SDK repository if you'd like.

@fusion809 packages a bunch of thirdparty mods using OBS - see https://build.opensuse.org/project/show/home:fusion809 (filter by openra-*) for examples and .spec files.
