### ISSUE TITLE
Oil derrick has selection precedence over conyard 

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#16445]
### Issue Summary
Oil derrick has selection priority over construction yard on Linux.

In a game vs Bain, I saw an engineer move for my conyard, so tried to undeploy, however, when I selected it the oil derrick had selection precedence, so I lost the game, Bain tried and said this doesn't happen on his installation, so I guess it could be Linux vs Windows?

#### System Information
- Ubuntu 18.04 LTS
- Mono JIT compiler version 5.18.1.3 (tarball Tue Apr  9 16:16:30 UTC 2019)
- release-20190314
- Red Alert

#### Additional Information:
* Select a construction yard near an oil, making sure to include both in selection
* Release mouse button
* See oil have selection precedence 

#### OpenRA Replays
https://cdn.discordapp.com/attachments/436144571613970432/570663452679471105/bain_replay.orarep

##### Linux (AMHOL):
* https://cdn.discordapp.com/attachments/436144571613970432/570661427660980264/Peek_2019-04-25_01-23.gif

##### Windows (Bain): 
* https://cdn.discordapp.com/attachments/436144571613970432/570662136569921551/2019-04-24_18-27-16.mp4

**Comment by AMHOL** [comment]
Also happens with harvesters for me, has for years, but I always thought it was just the way the engine was:

https://cdn.discordapp.com/attachments/436144571613970432/570665696451624963/Peek_2019-04-25_01-39.gif

**Comment by AMHOL** [comment]
Bain has confirmed that harvester selection precedence is the same on Windows, I have also tried with left-click orders (I use right-click or classic mode), and both behave the same in both scenarios.

**Comment by pchote** [comment]
The lower selection priority for harvesters vs combat units is a feature that is explicitly configured in the mod rules.

**Comment by matjaeck** [comment]
Harvesters look normal but I can't reproduce the selection issue with oil derricks. Might be a map specific thing?

**Comment by Punsho** [comment]
it is not a map specific thing. I downloaded the map from linked replay and it doesn't have custom rules nor I can reproduce the bug

**Comment by matjaeck** [comment]
We see in the gif from @AMHOL the view of a dead player who is trying to select enemy structures. You can not drag-select them, so the oil derrick is selected, as intended.

**Comment by AMHOL** [comment]
Oops, sorry, was pissed :laughing:
