### ISSUE TITLE
Out of sync crash

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16447]
On current release-20190314 shortly after the map started. A spectator had connection problems at game start.
[logs_replay.zip](https://github.com/OpenRA/OpenRA/files/3122819/logs_replay.zip)

**Comment by pchote** [comment]
We'll need logs from as many other players in this game as possible.  Nothing can be done from a single syncreport.

**Comment by matjaeck** [comment]
Unlikely that we get more information.
