### ISSUE TITLE
Capture animation does not stop if captor is crushed

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16440]
[OpenRA-2019-04-17T114633Z.zip](https://github.com/OpenRA/OpenRA/files/3107119/OpenRA-2019-04-17T114633Z.zip)
Reported on Discord by user DMTM:

> If a engineer gets "over run" by a vehicle while it's takeing over a building the building starts to blink endless-ly.

@Punsho's testing revealed that it only happens when the captor is crushed.

**Comment by Punsho** [comment]
Only happens with the reusable engineer

**Comment by Punsho** [comment]
Doesn't always happen, most likely it is connected to the blinking timer
