### ISSUE TITLE
Enter cursor in ts is flickering

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#16453]
In some frames the cursor is drawn below its correct position. I didn't manage to record the flickering but am sure that some frames are displayed incorrectly.

**Comment by abcdefg30** [comment]
Can you still reproduce this?

**Comment by matjaeck** [comment]
I can reliably reproduce this on Linux but am not sure about Windows. I checked the animated repair wrench cursor, but this cursor does not show any issues.

**Comment by pchote** [comment]
Can anybody still reproduce this after the cursor fixes that were included in release-20200202?

**Comment by tsunamistate** [comment]
Cannot reproduce on git-9faf9aa1b TS mod on Windows 10
All cursors are displayed correctly

**Comment by abcdefg30** [comment]
I suppose it is save to close this and wait if someone (possibly on a Linux system) encounters this issue again.
