### ISSUE TITLE
Infantry shooting undiscovered units

### ISSUE THREAD

**Issue by Vamperor** [OpenRA/OpenRA#16461]
### Issue Summary
In a game with a friend I noticed at some point that my units were firing on a target that I could not see. My expectation is that my units should not be able to fire on a unit before it has been revealed.
We played with explored map turned off and fog of war turned on. At 3:58 one of his rifleman fires at my (Vamperor's) infantry with line of sight from a nearby hospital and a nearby oil derrick in the centre of the map. At 3:59 one of my units fires back at that rifleman, without that rifleman having been revealed to me as a player.

#### System Information
- **Operating System:** Ubuntu 18.04.2 LTS
- **.NET / Mono Version:** I don't know where to find this information
- **OpenRA Version:** release-20190314
- **Mod:** Red Alert

- OpenRA Replays
[OpenRA-2019-04-28T221704Z.zip](https://github.com/OpenRA/OpenRA/files/3125668/OpenRA-2019-04-28T221704Z.zip)

**Comment by matjaeck** [comment]
Hi, thanks for reporting! I watched your replay and I'm not sure if there is an issue here. I recorded the relevant part and to me it looks the unit is targeting an enemy that has been within line of sight for just a second. I slowed it down to 50% speed btw.

<details>

![fowfire](https://user-images.githubusercontent.com/37185497/56872408-15980b00-6a29-11e9-899f-606caf65f79d.gif)

</details>

This could however be related to #14979.

**Comment by Punsho** [comment]
if this actually happened it might be related to #16335

**Comment by Vamperor** [comment]
You are technically right that the unit appears to be revealed for a split second, before it disappears again. But the only way I am able to see that is if I change the setting of the statusbars to always show as you have in the clip. If I set that to standard (which is how I play, because I never changed that setting), the unit stays pretty much invisible to me as a player and then it still feels unfair that my units suddenly start shooting something I can't see.
So maybe it is meant to work this way, but it is still weird to me that my units can apparently see my opponents statusbars and therefore shoot at something that I can't see.
