### ISSUE TITLE
Repairable activity management is bogus

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#16462]
As noted in #16352, `Repairable` badly manages the activity queue when sending units to repair, which causes bogus behaviour when other activities are queued after the repair. Most of this logic should move inside `Resupply`, using child activities.

> The issue that if you sent a unit to repair itself and immediately queue another command afterwards, that second command will be executed after the unit reaches the repair pad. After completing that order it will then drive back to the repair pad and execute the AfterReachActivities. The cause is that the latter get queued from a CallFunc. This was done to enable carryalls carrying units to repair pads.

**Comment by matjaeck** [comment]
Related: #7025

**Comment by reaperrr** [comment]
I'm currently working on this. Might need help later, but for now assigning myself.
