### ISSUE TITLE
Directional Airstrike/Paradrop logic can cause the cursor to disappear.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#16466]
See https://youtu.be/9rjRfR4JkZ8 , somewhere towards the middle, happens the second time i use the Cluster Mines.

**Comment by pchote** [comment]
It looks like this will happen if the OG is deactivated in the same tick that the cursor was hidden. The `Game.RunAfterTick` will be causing the cursor to be hidden after it was restored.
