### ISSUE TITLE
Dog becomes uncontrollable and flies off

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#16473]
Found by BigBadBain
the dog was force fired on friendly infantry to get a boost and Bain made a mistake by letting it eat his own infantry. After it the bug happens

![Dog](https://user-images.githubusercontent.com/37534529/56987806-1ea6ea80-6b97-11e9-9d2d-5f6a68119808.gif)

Replay: [Dog_Bug.zip](https://github.com/OpenRA/OpenRA/files/3132717/Dog_Bug.zip)

**Comment by matjaeck** [comment]
The attached archive is a renamed replay file. You have to rename it to *.orarep, extracting won't work.

**Comment by matjaeck** [comment]
In the moment when the dog kills the allied rifle man (at 03:18), "something" spawns in the top left corner. The dog then seems to target a non-existent target (03:19), and then targets the enemy engineer (03:20) but runs towards the thing in the top left it seems. I can't reproduce this.

**Comment by matjaeck** [comment]
Here is another replay recorded on release-20190314. At around 1:30, the engineer in the top right is killed by a dog. Debugging shows that right after https://github.com/OpenRA/OpenRA/blob/cc84daacea32f378bf13f5ca2b3f24f3869419d8/OpenRA.Mods.Cnc/Activities/Leap.cs#L97 the dog actor has location of {0,0} and the leap activity has a destination cell of {0,0}. This suits to the observed ingame behavior (revealing shroud, moving ghost).

[dog_bug.zip](https://github.com/OpenRA/OpenRA/files/3436432/dog_bug.zip)

**Comment by anvilvapre** [comment]
rabies likely.

travels to 0.0 perhaps.
