### ISSUE TITLE
Making units spawn at the closest possible location to the rally point

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16484]
This would make units get faster to the wanted location and randomness would play less of a factor in the fight for oil. 
Additionally ships would no longer get stuck behind nYards or sPens because of random chance (that happens when they are built next to land).

**Comment by matjaeck** [comment]
Doesn't this conflict with the concept of primary production buildings? What's wrong with letting the player set this explicitly?

**Comment by Punsho** [comment]
Why would it conflict? It's first calculated for the primary and if all ports are blocked it will check for others

**Comment by matjaeck** [comment]
Ah, ok (sorry, I can't really follow - my bad)

**Comment by dragunoff** [comment]
If I understand correctly "spawn points" are the building exit cells. Then it is necessary to calculate the nearest exit only once - the moment the rally point is set by the player. 

This seems like a reasonable feature.

**Comment by Punsho** [comment]
not when it is set but when a unit is built, when a new rally point is set it will only set one boolean to false, some people tend to spam click them so this is done for optimisation

**Comment by pchote** [comment]
`FirstExitOrDefault` can be replaced with a new `ClosestExitOrDefault`.

**Comment by Punsho** [comment]
I though I addressed this issue, it will sort them. Then go through the list finding the closest non-blocked exit.

**Comment by Punsho** [comment]
I also don't want to change how it is decided which production facility is going to be producing

**Comment by Punsho** [comment]
I'm almost done making it. I just need to know where should I place the previously mentioned boolean and the sorted IEnumerable of exits. Then I'll file the pr.
