### ISSUE TITLE
Attack frontal units are not firing when they have to turn

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16486]
<details>
<summary>Some examples from dog vs rifle interactions:</summary>

![DogDriveBy](https://user-images.githubusercontent.com/37534529/57131458-158b6880-6da5-11e9-98d4-b43a70fb1a10.gif)

![Dog circle](https://user-images.githubusercontent.com/37534529/57131461-17552c00-6da5-11e9-9b54-78e126a9a483.gif)

![DogCasual](https://user-images.githubusercontent.com/37534529/57131462-191eef80-6da5-11e9-9c3b-a7561f26bf67.gif)
</details>
<details>
<summary>Rifle vs Thief:</summary>

![ThiefDiveBy](https://user-images.githubusercontent.com/37534529/57132373-08bc4400-6da8-11e9-86d8-c24ab34b7be7.gif)

![Thief circle](https://user-images.githubusercontent.com/37534529/57131783-29839a00-6da6-11e9-926e-ec7ab3cf2a25.gif)
</details>
<details>
<summary>Rocket soldier vs Yak:</summary>

![PlaneDriveBy](https://user-images.githubusercontent.com/37534529/57132384-1a055080-6da8-11e9-85aa-0347317134f5.gif)

![PlaneMiddle](https://user-images.githubusercontent.com/37534529/57131599-8d599300-6da5-11e9-8e65-c2edf172a6c3.gif)
</details>

One of the ways to fix this is by giving units facing tolerance, but I think that it should be done the proper way by making units turn before shooting, opposite of how it is right now

Also one more thing for context, infantry turn instantly to their targets

**Comment by pchote** [comment]
Is this still an issue on bleed? The ChildActivity pretick fixes should mean that units will be able to fire without delay if the target is within one facing tick's tolerance.

**Comment by Punsho** [comment]
It is an issue, doesn't seem like anything has changed

**Comment by Punsho** [comment]
Why was pathfinding label added?
