### ISSUE TITLE
Crash (Windows style, no exception.log)

### ISSUE THREAD

**Issue by St3x** [OpenRA/OpenRA#16489]
### Issue Summary

Hi !

I ran a 100 % AI game and OpenRA crashed after 45 minutes.

The crash is a "The program is not responding" one, exactly like 

![excel-is-not-responding](https://user-images.githubusercontent.com/50241491/57152464-de807b80-6dd3-11e9-939b-726b16171522.jpg)

#### System Information

- Operating System : Windows 10
- .Net Version : 4.7.2
- OpenRA Version : release-20190314
- Mod : Red Alert

#### Additional Information :

Replay : https://ufile.io/nq731943
debug.log and perf.log (if it helps, because other logs are empty) : https://ufile.io/cy452gl7
Map : https://resource.openra.net/maps/12213/

**Comment by reaperrr** [comment]
As suspected, perf.log indicates this is the same infinite loop in FlyAttack as in #16322. Closing as duplicate and moved #16322 to release milestone as it doesn't seem to be that rare.
