### ISSUE TITLE
Can't build from conyard after attempted capture and engineer crushed

### ISSUE THREAD

**Issue by AMHOL** [OpenRA/OpenRA#16505]
### Issue Summary
turtel couldn't build from his conyard after the engineer was killed attempting to capture it, in the game I could see the conyard still flashing as if it was being captured.
... ... ...

#### System Information
Not my client

- OpenRA Replays
[bug.zip](https://github.com/OpenRA/OpenRA/files/3145706/bug.zip)

- Screenshots & Videos
![OpenRA_001](https://user-images.githubusercontent.com/1582784/57196490-e6851a80-6f8f-11e9-922a-bcbdcd44f625.png)
![OpenRA_002](https://user-images.githubusercontent.com/1582784/57196492-e84ede00-6f8f-11e9-9665-fecc4ec2eb14.png)
![OpenRA_003](https://user-images.githubusercontent.com/1582784/57196493-ea18a180-6f8f-11e9-9ae2-39039907bb94.png)

**Comment by pchote** [comment]
Likely related to #16440

**Comment by AMHOL** [comment]
Ahh, yes, engineer was crushed by light tank.
