### ISSUE TITLE
Redoing game lobby checkboxes

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#16519]
**Survey about checkboxes**
https://www.surveymonkey.com/r/QCQD7WH

I'm going to list checkboxes by popularity and peoples opinions in teamgames and 1v1's from my perspective. I would also like to get more opinions on this. (also we should not care what checkboxes were in the original)

**Explored Map: (default off)**
If left OFF most people don't tolerate it and just leave the game. Though there are some people who like it. It should be ON by default

**Crates: (default on)** 
A lot of people like it and a lot do not. It should stay the way it is

**Short Game (default on)**
It is always is left ON, If OFF it is just an annoyance and is frowned upon, minigames use it but they already have custom yaml files so I don't see the reason for this checkbox to exist

**Fog of War (default on)** 
If switched OFF most people don't tolerate it and just leave the game. Though there are some people who like it. It can stay the way it is

**Build off Allies (default on)**
I never saw it being OFF other then people trolling, it should be removed

**Limit Build Area (default on)**
I very rarely see it being used and people are always quick to abuse it and prove the person wrong who though it is a good idea to leave it OFF. Checkbox should be removed

**Separate Team Spawns (default on)**
It is partially broken and is usually ignored. It's only off in RAGL because there is a 1v1 4 spawn map. This feature should reworked or removed.

**Redeployable MCV (default on)**
If switched OFF it is frowned upon and I have yet to see anyone liking this feature. Checkbox should be removed

**Kill Bounties (default off)**
There are people who like it and some against it. It should be left how it is.

**Reusable Engineer (default off)**
It is frowned upon if left OFF. I have yet to see anyone ingame who prefers it over the reusable one

**Debug Menu (default off)**
It's cheats, it should stay

**Comment by reaperrr** [comment]
Generally speaking I'm in favor of removing some (at least 2) of the "virtually never changed" options, otherwise #16317 will force players to scroll down to reach the last dropdown option, which I find quite inconvenient.

**Comment by pchote** [comment]
I am planning to add dynamic vmargin support to the options bin before the playtest, which will fix the scrolling issue without needing to touch the options.

Generally speaking, I take this as a very competitive-mp-centric view, and find statements like “we should not care what checkboxes were in the original” unhelpful. Competitive play is an important part of OpenRA, but only makes up a small fraction of our total player base. You may not like that we consider offline players and “proper c&c” behaviour in our decisions, but you need to accept this if you want to work with us to get your ideas incorporated upstream.

**Comment by Punsho** [comment]
I don't want to start this discussion again but the silent majority is silent. How can you know what they want? What they like?

**Comment by GraionDilach** [comment]
The silent majority (of the C&C community) already considers OpenRA having that "very competetive mp-centric view" tbh, established by how much of an island the OpenRA community itself is. This is a reputation earned through long years and this community (both players and developers, excluding a few people) was never interested enough in changing that POV. Neither the modders coming from the legacy games, neither the OpenRA overrepresentation within the C&C remaster community council was able to change on that front.

The damage has already been done.

**Comment by lurtinigno** [comment]
Is there a way to persist different defaults for checkboxes in settings.yaml ?
Was looking for this in https://github.com/OpenRA/OpenRA/wiki/Settings but couldn't fine anything related and ended up here.

**Comment by AMHOL** [comment]
Could there perhaps be an option to automatically set the options when you join a server as host and store your personal defaults in settings.yml with a fallback to the server / current defaults?

**Comment by abcdefg30** [comment]
See #4122.

**Comment by netnazgul** [comment]
@pchote 
> Generally speaking, I take this as a very competitive-mp-centric view

That practically denied all feedback to this issue, even though part of it was legitimate.

`Separate Team Spawns` is indeed broken as seen here (reported in Discord by Lucipurr) 
![image](https://user-images.githubusercontent.com/1614714/59766962-05264300-92aa-11e9-92b8-e8ec73956d77.png)
I'm not seeing any use in this option because simple algorithm will have a lot of holes and require players restart the game (i.e. close opposite team spawns that are separated by a cliff) and won't work properly for >2 teams; sophisticated algorithm will take a lot of effort to implement for such a minor feature. Instead it is considerably easier to just setup teams in lobby manually.
