### ISSUE TITLE
dotnet.exe findings

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#16528]
#16506 regressed the dotnet.exe check and there will be no errors shown if make.ps1 can't find it.

The easiest way to trigger this is to try building it from the VS Developer Command Prompt (which also worked exactly up until that PR). Although besides providing a testcase, this point can be ignored - compiling as `make all && editbin /LARGEADDRESSAWARE OpenRA.Game.exe` is no longer necessary now with the PostProcess triggers.

Also, the warning message miscapitalizes Visual Studio.

**Comment by pchote** [comment]
Duplicate of #16517?

#16506 does not touch the check for `dotnet.exe`, so can't have regressed it. `Check-Command` refers to `make check`.

**Comment by GraionDilach** [comment]
Ahyeah, I mixed up commits and PRs. https://github.com/OpenRA/OpenRA/commit/f0d59391b5c296a026e5605348743d757b458ebf#diff-05c5cd105757a374d285de1a051f46ba broke the developer command prompt.

Closing as duplicate though.
