### ISSUE TITLE
Monster Trucks Madness: No money for transport!

### ISSUE THREAD

**Issue by Randall-Glass** [OpenRA/OpenRA#16523]
Since the OpenRA-release-20190314 there is no way to have money to buy a
transport.

In the older version capturing the silo and selling it, gave you money enough to
buy a transport.

In the present version capturing the silo and selling it, does not give you any money.

So where do you get enough money to buy a transport?

**Comment by abcdefg30** [comment]
It's not really obvious: You have to use the thief to steal money from the silo.
