### ISSUE TITLE
Project shows as broken in MonoDevelop and won't compile

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#16534]
![Screenshot from 2019-05-12 13-04-01](https://user-images.githubusercontent.com/4331210/57581371-e2d52480-74b6-11e9-8297-e9007302ca9b.png)

**Comment by obrakmann** [comment]
Introduced by #16451, 1955cac84edc9c8c0e2ccbb3b4ddc742bc2291ae

**Comment by pchote** [comment]
Are you using mono / monodevelop from https://www.mono-project.com/download/stable/#download-lin-ubuntu, or the default shipped with Ubuntu? We now require mono >= 5.4 and a similar vintage of monodevelop for compiling.

**Comment by obrakmann** [comment]
I'm using MD 7.4

**Comment by obrakmann** [comment]
Changing the project references in the solution from "Any CPU" to x86 broke it: https://github.com/OpenRA/OpenRA/compare/d216cdc0b2e5e9ae64cfd709e4f4b3273b58c668..43c4d4175af77232f28c8fdbb20179d27b5147fc#diff-c58ee0c983aa9a9476f2e868abbcc824

**Comment by pchote** [comment]
MD 7.8.2 works fine in my Ubuntu VM. Can you try updating using the upstream repo and seeing if you can reproduce the issue?

**Comment by pchote** [comment]
Problems like this may also be caused by stale build artifacts. If you haven't already, try doing a clean and full rebuild.

**Comment by obrakmann** [comment]
Updated to 7.8.2, still broken

**Comment by pchote** [comment]
Is compiling using the makefile / msbuild broken too?

**Comment by obrakmann** [comment]
no

**Comment by pchote** [comment]
Strange. Can you confirm that it works again if you switch the sln back to AnyCPU *and* remove the <Platforms>x86</Platforms> line from the csproj files (but don’t touch the <PlatformTarget>)? The csproj change will be needed for VS on Windows.

**Comment by tovl** [comment]
I seem to be having the same issue here.

I'm using MD 7.8.2, mono 5.20.1.19, Linux Mint 18.3.

Running make in the command line works without problems.

**Comment by matjaeck** [comment]
Same here, MD 7.8.2, mono 5.20.1.19, Ubuntu 18.04.

The changes suggested by @pchote seem to fix it on my end.
