### ISSUE TITLE
Turrets and other structures should expand the influence area and let other structures to be placed nearby

### ISSUE THREAD

**Issue by REdalert543543** [OpenRA/OpenRA#16542]
1. Explanation: Turrets and other defensive structures should expand the influence area. With influence area I mean that area in which you are allowed to build. This is how it works in the original game. Sometimes it's hard to build to certain areas if you are blocked by ore or some other narrow passage (where normal buildings won't fit), by expanding the influence area from all structures we would more easily be able to build through that narrow passage.

2. See Video of [a Pillbox being placed](https://www.youtube.com/watch?v=vqnKKqRlDrc&feature=youtu.be&t=753) in the original game. Here you can clearly see that it's too far away from the refinery but you can place it there because there is a turret nearby.

**Comment by matjaeck** [comment]
For the default RA mod it is a design decision that structures from the defence tab generally do not give buildable area. This is part of a concept to limit basecreep and make building placement and expanding a more important and interesting part of the game.

Usually, people use cheap structures like powerplants to "basewalk" toward a certain area, or the buildings in their buildorder. That this does not always work in narrow areas is a limitation that can not be fixed without introducing disruptive changes. You can however change this very easily in a custom mod(map).

**Comment by pchote** [comment]
This feature is already implemented through the "Limit Build Area" checkbox in the lobby options.
