### ISSUE TITLE
Switch Engineer/Harvester Selection Priorities (Quality of Life)

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#16555]
Engineer Selection Priority: 5
Harvester Selection Priority: 7

Basically, change it so engineers are selected _before_ harvesters. This is in response to a rare issue I've had, and recently learned others do too, that in a panic someone sends their harvesters instead of their engineer.

I'm not 100% sure the repercussions of this (what is priority 6?), but the goal is to change it so, when harvesters/engineers are in the same selection box, engineers are selected, not harvesters.

Harvesters are very easy to select, while engineers are not, so I don't see any issue with making this change.

**Comment by dragunoff** [comment]
We could review the whole priority hierarchy.

**Current priorities (RA):**
10 Combat units
9 (not used)
8 (not used)
7 Harvester
6 Supply truck
5 Engineer, Minelayer
4 MCV
3 Structures
2 Bridge hut
1 (not used)
0 Tech structures

A few thoughts:
* MCV should be moved up, probably above both harvester and engie. 
* Supply truck can safely go down. 
* Defensive structures can be given a higher priority than buildings.
* Bridge hut could be moved to 0

**Comment by dragunoff** [comment]
I have this arrangement for the priorities in mind:

| Priority | RA | TD | d2k
| ---: | :--- | :--- | :---
| 10 | Combat units | Combat units | Combat units
| 9 | (not used) | (not used) | (not used)
| 8 | MCV | MCV | MCV
| 7 | Engineer | Engineer | (not used)
| 6 | Harvester | Harvester | Harvester 
| 5 | Minelayer | (not used) | (not used)
| 4 | Supply Truck | Supply Truck | (not used)
| 3 | Defences | Defences | Defences
| 2 | Buildings | Buildings | Buildings
| 1 | (not used) | (not used) | (not used)
| 0 | Tech structures, Bridge hut | Tech structures | (not used)

**Comment by Orb370** [comment]
My only concern is that there's just too many priorities. Do minelayer and supply truck really need their own priority? I would sort it as follows:

Combat Units
Support Units (Engineer, Minelayer, MCV)
Economic Units (Harvester, Supply Truck)
Combat Buildings (defenses)
Buildings (Tech Structures, Normal Buildings)

The important thing is that when players select units, it should be intuitive. Having 9 different priorities is too much I think.

**Comment by dragunoff** [comment]
> The important thing is that when players select units, it should be intuitive. Having 9 different priorities is too much I think.

Yeah, I've been thinking about that too. I like your proposal. The table of priorities can then be simplified:


Priority | Actor types
--: | :--
10 | Combat units
8 | Support Units (Engineer, Minelayer, MCV)
6 | Economic Units (Harvester, Supply Truck)
4 | Combat Buildings (defenses)
2 | Buildings (Tech Structures, Normal Buildings)

**Comment by asfreitas** [comment]
Hello, I've been looking into getting involved with OpenRA. Can I tackle this issue as a good first issue?

**Comment by dragunoff** [comment]
@asfreitas Sounds great. I've been thinking about how to implement this. Since we're effectively creating selection priority tiers(categories) the actual number doesn't matter - it's more important to have a meaningful grouping. I think it'd be better to implement that with inheritable YAML templates. Something along the lines of:
```
^SelectableSupportUnit:
	Selectable:
		Priority: 8
```
and then inherit that on the actors that fall in that category:
```
E6:
	Inherits@SELECTION_TIER: ^SelectableSupportUnit
```

**Comment by asfreitas** [comment]
This is great. This is my first time contributing to open source so do you think you can help me out a bit? I'm a current cs student excited about trying but I'm also a bit worried about breaking something.

**Comment by dragunoff** [comment]
@asfreitas I will gladly help you. You can find me on the OpenRA discord, many other devs hang out there too. There is also a dev IRC channel. Links can be found here: https://www.openra.net/community/
