### ISSUE TITLE
Own Service Depot Priority (Quality of Life)

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#16554]
Basically the title.

Currently, when you send a vehicle to repair (with the repair action, wrench), it will go to the closest SD. This is fine in 1vs1's, but in team games this means sometimes your vehicle will go to a teammates SD. In a frantic game you probably won't notice your vehicle going to a different SD, meaning it basically sits in an allied base. You also lose control on rallying the vehicle after it repairs.

A simple solution would be to have vehicles go to your own SD's as a priority.

**Comment by pchote** [comment]
Makes sense to include this with the other SD fixes in the playtest.
