### ISSUE TITLE
Prevent restarting of running activities

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#16569]
It would have positive impact on demolition, enter, deliver resources, resupply, land, capture especially and some others that I didn't mention.

**Comment by pchote** [comment]
Related to #3923.

**Comment by abcdefg30** [comment]
From https://github.com/OpenRA/OpenRA/issues/16045#issuecomment-833434942:
![spamInfilitrate](https://user-images.githubusercontent.com/7704140/117287617-d4822f00-ae6a-11eb-8a4d-78f0cfc777cf.gif)
![spamInfiltrate2](https://user-images.githubusercontent.com/7704140/117287880-275be680-ae6b-11eb-8ad2-4b0a2fb3662c.gif)

**Comment by abcdefg30** [comment]
Closing as reverse duplicate of #19397.
