### ISSUE TITLE
Duplicating frames through listing them multiple times within Frames: crashes the game on load.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#16576]
The electro animation in RA1/TS/RA2 had a setup with the first four frames played three times before the fifth frame.

Setting this up via
```
	die6: electro
		Frames: 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13
		Length: 29
		UseTilesetExtension: true
		TilesetOverrides:
			DESERT: TEMPERAT
			INTERIOR: TEMPERAT
```

produces a crash however:
```
Exception of type `System.InvalidOperationException`: :0: Sequence ^BasicInfantry.die6 uses frames [0..28], but only 0..13 actually exist
   at OpenRA.Mods.Common.Graphics.DefaultSpriteSequence.<>c__DisplayClass59_1.<.ctor>b__0(Int32 frameCount)
   at OpenRA.Graphics.SpriteCache.get_Item(String filename, Func`2 getUsedFrames)
   at OpenRA.Mods.Common.Graphics.DefaultSpriteSequence..ctor(ModData modData, TileSet tileSet, SpriteCache cache, ISpriteSequenceLoader loader, String sequence, String animation, MiniYaml info)
```

**Comment by GraionDilach** [comment]
TBH, this case be worked around with Combine: usage, so this should probably just be documented somewhere.

**Comment by reaperrr** [comment]
Have you tried simply removing the `Length: 29`?

At least to my knowledge, sequence length is auto-calculated from the number of entries in `Frames`. `Length` isn't meant to be used together with that.

**Comment by GraionDilach** [comment]
Think I did and it just played the first frame as expected - since `Frames` could be used for `Facing` + `Length` combinations too. I settled down with `Combine`, because it can be used to do the same, and I finally comprehended how the yaml should be written for it after all these 3 years or so.

**Comment by Mailaender** [comment]
I also stumbled upon this when doing back and forth animations using `Frames`. See https://github.com/OpenRA/OpenRA/pull/17627 for my proposed fix.
