### ISSUE TITLE
Helicopter Take-off / Landing conflict

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16579]
From https://github.com/OpenRA/OpenRA/pull/16509#pullrequestreview-239252602:

> It seems that the helipad is already freed for other helicopters before the occupying heli has fully taken off. If you spam land orders while a heli is trying to take off (easy to reproduce with fully armed helis), weird things can happen.

<details>

![landspam](https://user-images.githubusercontent.com/37185497/57986978-f286d700-7a7b-11e9-9188-0fb5e569e5c8.gif)
</details>

> This would be much easier to fix after the TakeOff refactor in #16483.

Related to my request #16569 (I assume).

**Comment by matjaeck** [comment]
This has already improved on bleed and the remaining issues are covered by #16664 and #16569, so this can get closed I think.

<details>

![takeofflanding](https://user-images.githubusercontent.com/37185497/59158293-4ce1e900-8ab8-11e9-9715-1435f5eb4099.gif)

**Comment by pchote** [comment]
The original issue has been fixed on bleed.
