### ISSUE TITLE
Chronoshifted units sometimes don't teleport back

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#16581]
Release 20190314. Have so far noticed this only in big teamgames when the tickrate became low and couldn't reproduce it intentionally. I assume you have to issue an order within a very short timeframe to override the teleport. I think to remember that my units got duplicated like in #15793, but have to find the replay first to be sure.

**Comment by Punsho** [comment]
Never seen units duplicate but it is a common issue. I recon it is caused by blocking all possible return locations, never did testing but by not blocking them I could fully avoid the bug

**Comment by deleted-user-1** [comment]
I can't remember that they have been duplicated, not teleporting back might already be fixed on bleed @Punsho?

**Comment by PunkPun** [comment]
The bug I mentioned is fixed in the release. But when playing around I managed to teleport a unit that wasn't even in chrono selection, and the teleport was permenent. I was unable to reproduce it tho

**Comment by deleted-user-1** [comment]
Thanks, that sounds like a different bug, so this one (about not teleporting back) could get closed then I think.

**Comment by abcdefg30** [comment]
Was probably resolved by #15509 anyway.

**Comment by PunkPun** [comment]
Umm the pr linked is older than this issue

**Comment by abcdefg30** [comment]
Fair enough, I didn't pay attention to that.
