### ISSUE TITLE
Observer production icons are listed alphabetically based on queue type.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#16585]
Regression from the new observerstats.

Note that in RA atleast, this was previously structure-support-vehicle-infantry-ship-aircraft.

**Comment by teinarss** [comment]
No it was previous ordered by the order which the production building was built.
So you could have:
structure-support-vehicle-infantry-ship-aircraft.
structure-support-infantry-ship-aircraft-vehicle.
structure-support-aircraft-infantry-vehicle-ship.
etc..

**Comment by MustaphaTR** [comment]
Tha was the case for TD (normal Production), for classic production it was the order in player.yaml which is what Graion said.

**Comment by GraionDilach** [comment]
> No it was previous ordered by the order which the production building was built.

Not production building, but the ProductionQueue trait initialization. Since in RA and TS all prod queues on the Player actor, this made the order of their appearance in the observer production widget fixed between all matches.
