### ISSUE TITLE
Army and earnings graph overflow content area

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16597]
With heavy support starting units:

![armygr](https://user-images.githubusercontent.com/37185497/58383606-206a9f00-7fd9-11e9-9b6a-587ee2b35414.png)

![earnings](https://user-images.githubusercontent.com/37185497/58383609-2791ad00-7fd9-11e9-831a-70ccc412b52b.png)

Release-20190314 with heavy support starting units:

![armygraph_0314](https://user-images.githubusercontent.com/37185497/58383640-9111bb80-7fd9-11e9-81f3-065bb4ecb00a.png)

**Comment by teinarss** [comment]
Was thinking on moving the labels out from the graph area to make room, thoughts?
![image](https://user-images.githubusercontent.com/19173272/59555338-dc076900-8fb0-11e9-9624-e0e0688e8244.png)

**Comment by matjaeck** [comment]
Maybe remove the top and left white border and move the bottom border 1px up so that it is at the bottom of the content area and not below it?

**Comment by teinarss** [comment]
![image](https://user-images.githubusercontent.com/19173272/59564165-ce4ef380-9043-11e9-8fa7-574d29885d7c.png)

**Comment by pchote** [comment]
Can we have the y axis on the left, while we are at it?

**Comment by matjaeck** [comment]
The legend for the y axis is not needed when we use the `$` on the values. It would be good to put the legend for the x axis somewhere else than below it so that we have more space on the y axis. Maybe move the "m" just above the last value or horizontally right next to it?

**Comment by teinarss** [comment]
![image](https://user-images.githubusercontent.com/19173272/59564918-e2e3b980-904c-11e9-9758-8a5ded3c851c.png)

**Comment by matjaeck** [comment]
This looks good, not sure if it would look any better with my previous suggestion to move the "m", the space on the y axis seems already enough.

**Comment by teinarss** [comment]
Could remove both and change the header to "army value over time (m)"
