### ISSUE TITLE
MCV can bypass most checks and deploy anywhere if it's deployment is queued on bleed

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16600]
This may have been reported earlier but I'm unable to find the issue

A related issue #13984

**Comment by tovl** [comment]
This will be fixed in #16142.

**Comment by pchote** [comment]
Regression was introduced by the removal of the `if (State != ActivityState.Canceled)` check in #16246 ([diff](https://github.com/OpenRA/OpenRA/commit/a17cd0fa060a53ceb99c9fd60ed154086feb7acd#diff-27d71a7223c28efcd80ec32c4ca56ae4L182)). This means that `State` is now always `ActivityState.Done` in `OnLastRun` and `IsCanceled` is always *false*, even for cancelled activities.

#16748 avoids the issue by removing the `OnLastRun` (which is worthwhile as a general code cleanup), but we will probably want to fix this more generally - I will create a new issue to track this.
