### ISSUE TITLE
Juggernaut currently crashing on build in WithMoveAnimation as DefaultAnimation is null

### ISSUE THREAD

**Issue by Gerseras** [OpenRA/OpenRA#16637]
If you build a Juggernaut it will instantly crash the game with a null reference exception in WithMoveAnimation as DefaultAnimation is null thats sadly all i could get out of it as i checked the yamls for the juggernaut and the where last changed like a year or so ago. Also i have a openra bleed pulled on the 30th of April in which this crash does not occur.
[exception-2019-06-04T211546Z.log](https://github.com/OpenRA/OpenRA/files/3254534/exception-2019-06-04T211546Z.log)

**Comment by pchote** [comment]
Confirmed. Looks like #16535 missed this case.
