### ISSUE TITLE
Yak attack plane frozen mid-flight on Mass Confliction map

### ISSUE THREAD

**Issue by fusion809** [OpenRA/OpenRA#16646]
### Issue Summary
I would expect the yak attack plane to keep flying, but it has frozen oddly, mid-flight and is not moving at all, even after waiting for a few minutes. 

#### System Information
- **Operating System:** Arch Linux.
- **.NET / Mono Version:** Mono 5.20.1.
- **OpenRA Version:** commit 27cfa9b1f08668f39e66f7ecf73cca11dbf8db36.
- **Mod:** Red Alert. 

#### Additional Information:
- I'm not entirely sure how to reproduce, besides just loading my replay and saved game.

- Logs
[logs-20190607.zip](https://github.com/OpenRA/OpenRA/files/3263916/logs-20190607.zip)

- OpenRA Replays
[replay-20190607.zip](https://github.com/OpenRA/OpenRA/files/3263928/replay-20190607.zip)

- OpenRA saved game
[saved-20190607.zip](https://github.com/OpenRA/OpenRA/files/3263929/saved-20190607.zip)

- Screenshots & Videos
![Screenshot_20190607_095351](https://user-images.githubusercontent.com/4717341/59073713-9d681380-890b-11e9-8858-1726f43c1e88.png)

(See almost in the lower centre of the screen, the cyan yak attack plane).

**Comment by matjaeck** [comment]
On bleed aircraft get stuck in the air when they automatically return to rearm and the only airfield is lost. The replay didn't work for me but I saw in the savegame that the cyan AI had no airfield and the yak was facing towards its base so I assume this is the cause.
