### ISSUE TITLE
Support infiltrating super weapons to reset/delay charge time

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#16647]
This was discussed on discord and the [forum](https://forum.openra.net/viewtopic.php?f=82&p=310369&sid=eba72cf3e9787b3ca4d034b6caedae22#p310369) recently and the idea has so far received good feedback. A use case could be the RA spy which would get a new ability, replacing their ability to infiltrate refineries for cash which was moved to the thief in last release.

Both a relative and absolute delay have been discussed. Allowing to set an absolute delay in ticks would work for all use cases I think.

**Comment by pchote** [comment]
An absolute delay does not make much sense - why would the player opt for this when they could achieve the same goal much more easily by infiltrating a power plant?

**Comment by matjaeck** [comment]
To clarify what at least my understanding of the feature is: The spy infiltrates the nuke silo and this will cause a penalty on the charge time, setting it from for example 01:00 minute to 02:00 minutes remaining. Infiltrating power plants is useful to deny the nuke regardless of chargetime (although it is ofc a penalty for charge time). The idea is that infiltrating the silo would cause a much higher charge penalty than infiltrating the powerplants. This would allow a player who has build his nuke some time after the other player did to launch his nuke first or, if the player didn't build one, buy some time before it hits.

**Comment by pchote** [comment]
Resettting the timer completely would be much clearer from a gameplay perspective. This would make the iron silo/iron curtain/chronosphere very attractive spy targets, which can be countered by building walls around them - these buildings do not have bibs, so spies cannot be dropped inside the walls using a chinook.

**Comment by matjaeck** [comment]
The counterargument is that you reset a potentially game ending nuke with a $400 unit. I don't say it is imbalanced, but this was the concern.

**Comment by GraionDilach** [comment]
Reset is what RA2 did and ORA Spy logic takes more from RA2 than actual RA1 anyway.

**Comment by Orb370** [comment]
I agree on reset. Makes more sense.

A static delay could end up with someone sending 5 spies into an IC, for example. The timer would be 5 minutes or more. That doesn't really make sense.

A building can be walled off from spies with an easy investment of 200 in wired fence (or even 120 if the balance change on that goes through).

Also, Spies cost 500, not 400. British Spies cost 250.

Should this be extended to GPS? My gut says no, but it might make sense to have it included too.

**Comment by matjaeck** [comment]
After further discussion on discord some days ago I agree as well on reset for super weapons. The charge bars should be made visible when a player scouts the ic/chrono/nuke. Not sure about GPS.
