### ISSUE TITLE
Helicopters move to waypoint after rearming before continuing an attack

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16642]
Expected side effect of #16584 that should be fixed separately after the PR is merged to not block @reaperrr's ongoing aircraft rework.

The former behavior was that they immediately continued their attack. 

However, as noted in https://github.com/OpenRA/OpenRA/issues/13474#issuecomment-489583608 and https://github.com/OpenRA/OpenRA/issues/14805#issuecomment-489581494 a related fix is to abort the attack activity in these cases when `AbortOnResupply` is true.

**Comment by pchote** [comment]
Fixed on bleed: Helicopters with `AbortOnResupply: false` return directly to their target after reloading. Helicopters with `AbortOnResupply: true` remain sitting on the pad and don't move to the rally point at all (a different / new bug).
