### ISSUE TITLE
L/S turns during move often don't completely finish turn

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#16651]
It's not just a visual issue in RA/TD due to `UseClassicFacingFudge`, TS voxel units indicate that it really is the movement itself that often doesn't complete turning towards the closest (targeted) of the 8 main movement directions.
This indicates that `MovePart` doesn't calculate the number of necessary fraction steps entirely correctly.

**Comment by pchote** [comment]
Is this a recent regression?

**Comment by reaperrr** [comment]
No, it's been like that for quite some time, I think.
