### ISSUE TITLE
AIs seem dead in Red Alert

### ISSUE THREAD

**Issue by fusion809** [OpenRA/OpenRA#16679]
### Issue Summary
In a game I just started the AIs seem to be doing nothing but deploying the MCV. After that they just sit there, they do not construct any buildings at all. 

#### System Information
- **Operating System:** Arch Linux.
- **.NET / Mono Version:** Mono 5.20.1.
- **OpenRA Version:** c8a42cb. 
- **Mod:** Red Alert.

#### Additional Information:
**Steps to reproduce:**
- Start a Red Alert single player game against an AI.
- Check on whether the AIs you're playing against are doing anything, but deploying their MCVs. 

- Logs
[logs-20190610.zip](https://github.com/OpenRA/OpenRA/files/3272025/logs-20190610.zip)

- OpenRA Replays
[orarep-20190610.zip](https://github.com/OpenRA/OpenRA/files/3272027/orarep-20190610.zip)

- OpenRA saved game
[orasave-20190610.zip](https://github.com/OpenRA/OpenRA/files/3272028/orasave-20190610.zip)

- Screenshots & Videos

![Screenshot_20190610_222025 (cropped)](https://user-images.githubusercontent.com/4717341/59195382-295d9200-8bcf-11e9-959f-2f9b8d2cb1c7.png)

(See how even after 11 minutes of gameplay Rush AI has done absolutely nothing)

**Comment by fusion809** [comment]
Also affects commit 26150 (b59ae476e).

**Comment by fusion809** [comment]
Commit 25149 (44e41cc0546c5a69f4d0ec63e3f8904de92f2840) is the latest unaffected commit.

**Comment by dragunoff** [comment]
This also happens in TD.
