### ISSUE TITLE
Mobile>RequiresCondition is broken

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#16678]
If it is defined, doesn't matter what the conditions are. The units are incapable of moving. I didn't update RV to use PauseOnCondition instead of RequiresCondition for Mobile trait and last engine update i did complately broke all the mobile units. Removing RequiresCondition: chronodisabled made them move again.

Tested on TS on upstream by changing ^Vehicle:>Mobile>PauseOnCondition to RequiresCondition with opposite conditions and it happens there too.

**Comment by pchote** [comment]
Regression from #16607. The `IObservesVariables` implementation is hiding the version in, and therefore breaking, the conditional trait plumbing. This also affects the other traits modified in that PR.
