### ISSUE TITLE
Can't start games

### ISSUE THREAD

**Issue by otakuboy92** [OpenRA/OpenRA#16675]
### Issue Summary

When trying to load any of three games it states upon executing the file it will state "Tiberium Dawn has encountered a fatal error and must close. Refer to the crash logs and FAQ for more information"

#### System Information
- **Operating System:** Windows 10 Home Premium
- **.NET / Mono Version:** Unsure
- **OpenRA Version:** release-20190314
- **Mod:** All

#### Additional Information:
- Steps to reproduce
	1. Click on .exe or shortcut for any game
	2. See fault
	
- Logs

[Crash logs.zip](https://github.com/OpenRA/OpenRA/files/3270248/Crash.logs.zip)

**Comment by mytbk** [comment]
Strange, graphics.log says unsupported OpenGL version, and want you to install the latest graphics driver. What graphics card and driver are you using?

**Comment by otakuboy92** [comment]
Hey thanks for the help. pretty old device.

Mobile Intel(R) 4 Series Express Chipset Family (Microsoft Corporation - WDDM 1.1) - Version 8.15.10.2702

**Comment by pchote** [comment]
The WDDM drivers provided by Microsoft do not include OpenGL, which OpenRA needs. Try looking for the full driver package from Intel.

**Comment by LipkeGu** [comment]
https://www.intel.de/content/www/de/de/support/articles/000005733/graphics-drivers.html

**Comment by Smittytron** [comment]
Closing as OP didn't respond.
