### ISSUE TITLE
OpenRa Crash at the start 

### ISSUE THREAD

**Issue by Biinout** [OpenRA/OpenRA#16683]
Hello
Sorry for my english im french 
I want to install OPENRA and crash at the start

View my logs 

OpenRA engine version release-20190314
Date: 2019-06-10 17:23:54Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
   à OpenRA.Game.Initialize(Arguments args)
   à OpenRA.Game.InitializeAndRun(String[] args)
   à OpenRA.WindowsLauncher.RunGame(String[] args)

My computer is Dell E4300 and works windows 10 64 Bits 

Thanks you help me

Benoit

![image](https://user-images.githubusercontent.com/51675172/59214640-c8768f80-8bb7-11e9-840b-ad5b2fcfc6b2.png)

**Comment by teinarss** [comment]
Looks like you are missing graphics drivers with Opengl support.

**Comment by GraionDilach** [comment]
Google says that's an Intel GMA 4500MHD there. The chip is claimed to have support for OpenGL 2.1, but the driver necessary for it doesn't even supported under Win10.

It doesn't meet the system requirements. Nothing to do there.
