### ISSUE TITLE
Support explicit ordering songs and use it to reorder playlists

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16681]
Currently songs are ordered alphabetically but there are cases where you need a custom order and can not rename the files. Supporting this would allow us to reorder our playlists to equal the playlist order of the original games. These are small aspects that contribute to recreating the feel of the original games. Original playlist (taken from cncnet so not sure if 100% authentic): https://imgur.com/a/zTXX0X7

**Comment by GraionDilach** [comment]
Songs are ordered in the order they are listed within `music.yaml`. There's no engine-limitation/override here.

RA2 has ithe order transferred from the WW theme.ini counterpart.

**Comment by matjaeck** [comment]
Thanks, I didn't know that. Closing.

**Comment by GraionDilach** [comment]
You can still use the CnCNet screenshots to reorder the music within the YAML as a polish though - they are legitimate in this regard.
