### ISSUE TITLE
intuitive use of the "burrow" trait from tiberian sun.

### ISSUE THREAD

**Issue by WhoCaresora** [OpenRA/OpenRA#16706]
I have a request regarding a tiberian sun mechanic used in Shattered paradise. the "underground travelling" or "burrow"

Right now the Devil Tongue "DT" (flame tank traveling underground), travels from A to B directly underground  on simple move command. It  prevents the DT to respond correctly to click-related order without witnessing the tank going and exiting the ground sometime in a chaotic fashion. 
This behaviour makes it almost impossible to use in the same selection of multiple unit type in army plays.

I'm aware the behaviour depends on values that can be adjusted in the mod but the players can't be aware of those parameters without a huge experience of using the feature. Which is kinda the opposite of intuitive.

I was wondering if the underground travelling could be handled the same way as the blink of chrono tank on a modifier (could even be the same : "alt").

- simple move command : normal click on map/minimap : DT acts like a normal vehicle to the waypoint. (does not go underground) 
- modifier + move command : lets say in this case force move so --alt + click-- on map/minimap :  DT travel right away underground to the waypoint as it does now.

With that change, the underground behaviour would be only triggered by the player's will and feels controllable. Second advantage; the DT  would respond to every existing order like a normal vehicle. Third advantage you could yourself with the incoming queuing system controlling perfectly the portion of the journey you want underground and out of the ground.

Additional infos : 
-unit can't be given new orders while travelling in the ground : I'm ok with that and think it is a cool feature and makes sense. Players have to take it in account before issuing the undeground travel.
-A cursor support would be a must

**Comment by dnqbob** [comment]
> -unit can't be given new orders while travelling in the ground : I'm ok with that and think it is a cool feature and makes sense. Players have to take it in account before issuing the undeground travel.

however, underground units cannot get out of surface the same time, which means you still have to do a lots of clicking to let them to attack the same target.

**Comment by pchote** [comment]
Shattered Paradise has implemented its own behaviour for underground units that is quite different to our "normal" behaviour:
* Orders can't be issued to units that are underground
* Units prefer to go underground for much smaller distances, as short as 3 cells(!)

The comments here seem to be specifically related to these two changes, so this would be best filed against https://github.com/ABrandau/Shattered-Paradise-SDK/issues - OpenRA's TS doesn't/won't suffer from these!
