### ISSUE TITLE
Vehicles and infantry now move around crates, instead of collecting them (like for potential rewards)

### ISSUE THREAD

**Issue by fusion809** [OpenRA/OpenRA#16717]
### Issue Summary
For quite a while since the latest release I've noticed that vehicles and infantry move *around* crates, instead of moving over them to collect rewards/damage/alike under Red Alert.

#### System Information
- **Operating System:** Arch Linux.
- **.NET / Mono Version:** Mono 5.20.1.
- **OpenRA Version:** db0c6d8, among other commits.
- **Mod:** Red Alert.

#### Additional Information:
- Move a vehicle along a path that should bring it into contact with a crate and watch as it moves *around* it instead of over it. 

- Logs
[logs-20190621.zip](https://github.com/OpenRA/OpenRA/files/3311597/logs-20190621.zip)

- OpenRA Replays
[replay-20190621-crate-walk-around.zip](https://github.com/OpenRA/OpenRA/files/3311602/replay-20190621-crate-walk-around.zip)

(~10 mins in I move my rocket launcher V2 towards a crate and it moves around it, instead of over it).

**Comment by matjaeck** [comment]
The same thing has probably also regressed the crush ability from #16315 for helicopters.

**Comment by Punsho** [comment]
I always thought that this is intentional. Crates give random effects and one of them is a napalm explosion that kills the unit. Thus I though crates are only picked up when they are specifically clicked on.

**Comment by MustaphaTR** [comment]
I noticed the issue on RV while doing an engine update but i decided not to because of #16678. It is not just avoiding the crates, they can't collect them at all.

**Comment by pchote** [comment]
This is only a problem for paradropped crates in RA, so probably related to #16661 and probably unrelated to any helicopter issues.

**Comment by MustaphaTR** [comment]
Makes sense, RV crates are paradropped too.
