### ISSUE TITLE
BeaconLib.Beacon: Method 'System.Net.Sockets.UdpClient.AllowNatTraversal' not found.

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#16728]
### Issue Summary
When launching a dedicated server on Debian 9, prior to any game starting, server logs contain the following error:
```
BeaconLib.Beacon: Method 'System.Net.Sockets.UdpClient.AllowNatTraversal' not found.
```

The servers are playable even with this error in the logs. I have been experiencing crashed servers causing CPU utilization to reach 100%, but am having trouble reproducing it. I am not sure if these two bugs are related.

#### System Information
- **Operating System:** Debian GNU/Linux 9 (stretch)
- **Kernel:** Linux 4.9.0-9-amd64
- **.NET / Mono Version:** Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1)
- **OpenRA Version:** release-20190314
- **Mod:** Red Alert

#### Additional Information:
- Steps to reproduce (Debian 9/bash)
	1. `sudo apt update && sudo apt --assume-yes upgrade`
	0. `sudo apt --assume-yes install git`
	0. `git clone https://github.com/OpenRA/OpenRA.git ~/openra`
	0. `cd ~/openra`
	0. `git checkout tags/release-20190314`
	0. `echo "release-20190314" >| VERSION`
	0. `sudo apt --assume-yes install make`
	0. `make version`
	0.  `sudo apt --assume-yes install zip unzip`
	0.  `sudo apt --assume-yes install mono-devel libfreetype6 libopenal1 liblua5.1-0 libsdl2-2.0-0 xdg-utils zenity wget`
	0. `make all`
	0. `Name="OpenRA Dedicated Server Crashtest" nohup ./launch-dedicated.sh &`
	0. `cat ../.openra/Logs/dedicated-server.log`

- Logs

```
BeaconLib.Beacon: Method 'System.Net.Sockets.UdpClient.AllowNatTraversal' not found.
Initial mod: ra
Initial map: c61af2fa9f32777dd1ca53630144f829c2592eca
Master server:
[...]
```

**Comment by Mailaender** [comment]
I am trying to compile https://github.com/rix0rrr/beacon on @openSUSE with Mono 6.8 and I got exactly the same error. https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.udpclient.allownattraversal is part of the .NET API but seems unimplemented on Mono. The crash was fixed in https://github.com/OpenRA/OpenRA/pull/13351 only the error message in the logs remains.

**Comment by Mailaender** [comment]
I searched through the Mono code and the method is available since ~6 years. Just had to update the compiler as this is .NET 4 API. My best guess is you just need to update your old Mono from https://www.mono-project.com/download/stable/ and try again.
