### ISSUE TITLE
Make all does not depend on make version

### ISSUE THREAD

**Issue by shoter** [OpenRA/OpenRA#16732]
### Issue Summary
I would expect that `make all` would prepare for me **all** what is needed to play the game. It turns out that after `make all` I am also supposed to execute `make version` to be able to play multiplayer games. This behaviour is super confusing. 

`Make all` should also depend on `version` so players will be able to play multiplayer games without figuring out what's going on.

#### System Information
- **Operating System**: Debian
-  Mono: Mono JIT compiler version 5.20.1.19 (tarball Thu Apr 11 09:07:22 UTC 2019)
- **OpenRA Version:** release 2019 march
- **mod** : all mods

#### Additional Information:
- Steps to reproduce
	1. Execute `make all`
	2. When you launch any mod you have {{Dev_Version}} instead of actual version.

**Comment by GraionDilach** [comment]
Do note that `make version` ruins a development folder with overriding the mod versions. Implementing this would mean developers cannot test their in-progress branches without having additional diffs reverted constantly.

In-development stuff should suit developers first and not the players.

**Comment by abcdefg30** [comment]
Sorry, I agree with @GraionDilach here. Most of the time `make all` is used will be during development, when we don't want to set any version strings. Is running `make version` not mentioned in the documentation? (If so we should really fix that.)

**Comment by pchote** [comment]
Note that the source package advertised on http://www.openra.net/download/ does pre-set the version strings.

**Comment by amphyploid** [comment]
I agree with @shoter about it being super confusing. Even worse is that it's not documented anywhere. It would probably be best to have two choices: `make release` and `make dev`, which include `make all` + `make version` automatically setting the `VERSION` file to the appropriate version. Just my 2¢.

**Comment by GraionDilach** [comment]
It is documented.

>If you download the source code using Git and want to play online you must run make.cmd with the version command to set the in-game version string. This step is not required if you download the source tarball.

https://github.com/OpenRA/OpenRA/wiki/Compiling

**Comment by teinarss** [comment]
One little thing is see it's missing under the Linux/Mac section

**Comment by abcdefg30** [comment]
I adjusted the docs: https://github.com/OpenRA/OpenRA/wiki/Compiling/_compare/b94ec05a7dc5fa67dc9eb218e4a781c1bcaea107...dbe047274c3d08f52e854c9d83b135b1bf41b3fd
