### ISSUE TITLE
Classic production does not have a Parallel counterpart.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#16758]
While ParallelProduction was added for KKND, it is much closer in principle to the WW kind of traditional evolved-shared-queue design than the Blizzard/EALA-based individual queues and thereby would provide a nice alternative/twist to RA modmaps, since converting to parallel requires no UI modding.

Relevant downstream code: https://github.com/AttacqueSuperior/Engine/blob/master/OpenRA.Mods.AS/Traits/Player/ClassicParallelProductionQueue.cs

**Comment by Mailaender** [comment]
Implemented in #17822.
