### ISSUE TITLE
Stacked my wall on enemy pillbox

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/OpenRA#16766]
### Issue Summary
Syncron placing wall and pillbox caused stacked structures?

#### System Information
- **Operating System:** Windows 10
- **.NET / Mono Version:** ?
- **OpenRA Version:** release-20190314.
- **Mod:** Red Alert

#### Additional Information:
- Steps to reproduce
	Maybe have Players placing these structures at the same cycle at the same cell?

- OpenRA Replays && Screenshots 
[PillboxWallBug.zip](https://github.com/OpenRA/OpenRA/files/3384294/PillboxWallBug.zip)

Thanks!

**Comment by yuantse** [comment]
May this is a duplicate issue.
Similar description at #16635 
[Defence structure can be placed in same position as wall](https://github.com/OpenRA/OpenRA/issues/16635)

**Comment by abcdefg30** [comment]
True, looks like a duplicate.
