### ISSUE TITLE
D2K: Automatic carryalls override player harvest positions.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#16775]
If a carryall picks up the harvester, the harvester will always be delivered to the closest spice patch.

Should be a  `new FindAndDeliverResources(self, self.World.Map.CellContaining(self.CenterPosition))` at https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Activities/DeliverResources.cs#L61 and a `new FindAndDeliverResources(self, targetCell)` at https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Activities/HarvestResource.cs#L59 probably. Fix untested.

(The original reason I noticed this is because chrono miners also use these interfaces and those broke down too, which I fixed within the trait code instead.)

**Comment by teinarss** [comment]
Closed by #16778
