### ISSUE TITLE
DeliversCash break unit voices.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#16773]
It does not check for the order string in `VoicePhraseForOrder`, breaking all traits loaded after it.

**Comment by pchote** [comment]
This is probably the same issue that @MustaphaTR reported in Discord but doesn't seem to have filed an issue for.

**Comment by GraionDilach** [comment]
DeliversExperience and MadTank are also affected from a quick check.

**Comment by GraionDilach** [comment]
And probvably it is the same issue, because @MustaphaTR asked me to check if I'm affected as well - and when I was, I decided to debug the cause.
