### ISSUE TITLE
Persistant force fire

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16779]
<details>

![persistantff](https://user-images.githubusercontent.com/37185497/61251066-b4dfbb00-a759-11e9-958e-7a07114e61f4.gif)

**Comment by matjaeck** [comment]
Close if intentional, after all it is consistent with how tanks behave, Might want to give aircraft unlimited ammo then (would also be in line wit the ideas for the cargo hind).

**Comment by tovl** [comment]
This is not intentional. This should not happen when `PersistentTargeting == false`. Apparently force-attack overrides this somehow.

**Comment by pchote** [comment]
Probably introduced by #16369. It looks like the requested target in `AttackFollow`/`AttackAircraft` is not being cancelled when the attack activity is cancelled.

**Comment by tovl** [comment]
The `PersistentTargeting` parameter was specifically introduced in #16369 to prevent this. 
I did some testing and this only seems to happen when the aircraft resupplies before being given a new order.
