### ISSUE TITLE
MAD tank does not self-destruct when queuing move order after deploy order

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16780]

**Comment by pchote** [comment]
`MadTank` is another (and hopefully the last?) trait that manually wrangles/mangles the activity queue. Making the deploy behaviour a self contained activity should fix this as well as clearing out some more technical debt.

**Comment by fruestueck** [comment]
This bug was fun to reproduce. The MAD tank gets really mad xD staying on the map and destroing stuff until killed. Could be a feature xD
