### ISSUE TITLE
Stop order on rearming planes makes them take off

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16781]
Not sure if intentional.

**Comment by reaperrr** [comment]
This is even doubly unintentional: Planes (unlike helis) should not take off on resupply, and the "Stop" order should not make aircraft stop resupplying in general.

The latter is a regression from making the take-off a child activity of Resupply: The old work-around of re-queueing Resupply relied on Resupply ending _before_ the take-off was triggered.

I have an idea how to fix that, and if TakeOffOnResupply: false is really ignored, that obviously needs to be fixed as well.

**Comment by tovl** [comment]
I cannot reproduce this on current bleed. This has already been fixed by #16721

**Comment by matjaeck** [comment]
Can confirm that this is now fixed.
