### ISSUE TITLE
Healthy Aircraft on service depot

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#16784]
- Currently it is possible to cmd a **full health** heli to the service depot. It will not block the service depot for vehicles. If damaged, it will land and repair.
![heli-repair-full-health](https://user-images.githubusercontent.com/25386322/61298820-30d01680-a7df-11e9-902b-20fb18022000.gif)

- Currently it is possible to send a full health airplain to the service depot. It will **block** the sd for other vehicles.
A stop command does nothing. If the Airplain gets damanged on the SD, it will **not** repair. A repair cmd, and a stop cmd will do nothing. Only a takeoff will help.
![yak-repair-full-health](https://user-images.githubusercontent.com/25386322/61298837-36c5f780-a7df-11e9-9e31-e869dc28008c.gif)

Both tested on bleed. Tested with RA, TD and TS.
I guess the **solution** is to forbid landing to healthy Aircrafts (similar to vehicles).
Regression of #16721 i guess.

EDIT: In TS a carryall and transporter, both can land with full health on the SD.

**Comment by pchote** [comment]
Sounds like we are missing an "if full health continue to the next activity" check somewhere in the `Resupply` activity.
