### ISSUE TITLE
Sevice depot repaier anim doesn't stop

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#16785]
All tested on Bleed.
- In TD & RA the service depot continues its repair animation, when a damaged vehicle got destroyed while repairing. This does not happen on TS or D2K.
![sd-bug-apc-repair-exitondeath3](https://user-images.githubusercontent.com/25386322/61312257-561d4e80-a7f8-11e9-8c0b-72965189dab5.gif) (updated gif)

- ~In D2k, a Unit beeing repaired on the SD will not move away from the SD when a Stop-cmd is issued.~ not an issue

- ~In TS, a APC containing Marines will eject them on death while on the SD. Maby intendet - looks nice.~ splitted into new issue

Sorry that I didn't test it sooner! More testing on D2K needed to iron all bugs out

**Comment by reaperrr** [comment]
> This does not happen on TS or D2K.

That's because they use `WithRepairOverlay` which works a bit different.

Anyway, #16788 should fix the first issue, but not the other two so it would be better to open separate issues for them.

**Comment by fruestueck** [comment]
Issues splitted
