### ISSUE TITLE
Red Alert: Kennel need more EXIT point.

### ISSUE THREAD

**Issue by exelpro** [OpenRA/OpenRA#16792]
EXIT@1 and EXIT@2 are blocked.
AI does not cancel training.

![OpenRA-2019-07-17T135907846Z](https://user-images.githubusercontent.com/53005938/61382050-f81b6480-a8e6-11e9-92fb-5f863687c58d.png)

Exit@1:
RequiresCondition: !being-captured
    SpawnOffset: -280,400,0
    ExitCell: 0,1
    ProductionTypes: Dog, Infantry
Exit@2:
    RequiresCondition: !being-captured
    SpawnOffset: -280,400,0
    ExitCell: -1,0
    ProductionTypes: Dog, Infantry

![OpenRA-2019-07-17T121619314Z](https://user-images.githubusercontent.com/53005938/61382141-28630300-a8e7-11e9-9fe7-3b02525f5c65.png)
![OpenRA-2019-07-17T142253858Z](https://user-images.githubusercontent.com/53005938/61383580-ec7d6d00-a8e9-11e9-83a7-30549c732923.png)

Exit@3:
.
.
ExitCell: <-  -1,-1 or 0,-1 or 1,-1?
.

English is not my native language.

**Comment by tovl** [comment]
Related to #10843

**Comment by tovl** [comment]
Was fixed by #17183
