### ISSUE TITLE
TS: destroyed APC ejects infantry on service depot

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#16791]
Splitted Issue from #16785 to address issues seperatly.

- In TS, a APC containing Marines will eject them on death while on the SD. Maby intendet - looks nice.
Watch second half of the following GIF
![sd-bug-apc-repair-exitondeath3](https://user-images.githubusercontent.com/25386322/61312257-561d4e80-a7f8-11e9-8c0b-72965189dab5.gif) (updated gif)

On bleed.

**Comment by Smittytron** [comment]
I can't reproduce the bug

**Comment by PunkPun** [comment]
On bleed infantry immediately after being spawned leave the service depot
