### ISSUE TITLE
No repair queue for aircrafts

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#16796]
Bug (or missing feature) on release & bleed, tested with yak and longbows.

If two damaged aircrafts are send to repair, the first will go to the SD, the second to helipad/airfield and idle there. Planes will block the aircraft, helicopters won't block the helipad.
![heli-wrong-rtb](https://user-images.githubusercontent.com/25386322/61454211-8da70a80-a960-11e9-96bd-38b56083830b.gif)

Copmared to this, vehicles will enter a queue for the service depot.

EDIT: The second aircraft will move to the airfield/helipad and retain a "green-move-target-line" to the SD.

**Comment by matjaeck** [comment]
Possible duplicate of #12991.

**Comment by fruestueck** [comment]
> Possible duplicate of #12991.

While 12991 refers to Heli only, #16712 is more precise. It affects all aircraft.
