### ISSUE TITLE
Request: Allow reordering spawnpoints in the Map Editor

### ISSUE THREAD

**Issue by Schneckenhof** [OpenRA/OpenRA#16801]
# Feature Request:

### Please add an In-Editor option to set the Lettering when placing a spawn point on the map using the built in map editor. Thank you.

As it is currently, spawn points seem to be lettered alphabetically based on the chronological order in which you place them. 

Example: First placed point is A, Send point placed is B, Third is C, etc etc.

### Bonus: It would be really helpful if you saw "Spawn A" or simply "A" instead of "Spawn Point" on the actual spawn point that is placed.

**Note: I am told this is a Feature request and not a bug.**

**Note: I didn't see a similar issue posted before when I skimmed the issues list with the map editor tag.**

## Why is this an issue?

**If you ever need to adjust a spawn point and want it to have the same lettering as it was before you moved it, them you have to Delete and replace all Spawn points on the entire map, and then replace them in the in the exact chronological order you previously had placed them.**

**Alternatively you can apparently edit the YAML file, or do some command line voodoo.**

This is a lot to ask of someone who just wants to assemble map pieces together to make a nice playable map without having to learn actually learn Assembly.

A simple option to edit the spawn point in the map editor would alleviate this.

## Example problem:

When you need to move or adjust a spawn point the map editor decides for you that Spawn C out of 8 Spawn locations is now Spawn J.** You as the editor have no say in the matter. It takes an excessive amount of time and frustration to fix this simple issue.

## Typical Scenario:

Imagine you have a map similar to say, ore gardens, where the spawns are laid clockwise in a circle. Spawn point A is at 7 O'clock and spawn point H is at 5 O'clock. (Think of a clock face).

This conveys a lot of information really quickly to the host and the players in the lobby.

Everyone getting into the lobby knows Immediately that:
1) it is likely that the match is being played East Vs West (Left Vs Right) and 
2) that the teams will probably be ABCD vs EFGH in the current game. 
The players know this, the host knows this. When everyone is yelling at the host to "gogogogogo" and he's checking teams. He see's ABCD is all on a team and EFGH is all on a team, and click's go. Everyone's happy.

Imagine the map editor (you) made a minor mistake in placing a spawn point, and spawn point C isn't centered correctly. What do you do?

1) You go into the map editor, delete the spawn point that you know was C.
--By the way, they all just say something like "spawn point", Not A, or B, or Spawn A, or Spawn B.
2) You then place a new spawn point where C should be so that it is centered where you want it.
3) You then exit the map editor, save, and upload the new file.
4) You go to play the game. Suddenly the left side is AB **J** D vs EFGH.

Obviously this isn't too much of an issue.

Now let's imagine you did this with 3 spawn positions.
Now its Team1 AIJD vs Team2 EKGH. 

Real quick, without looking at the last line. Who is on on team one, and who is on team 2? 

Is J on team 1 or 2? 
Is I? 
K?

People are thrown off, host has a harder time remembering that J is on Team 1 and not Team 2. etc, and probably starts the game with incorrect teams.
It happens quite often when maps are lettered in a weird way.

## Closing:

Please help fix this to improve the lives of Map Makers and Map Editors.
Thank you.

## Additional information (probably irrelevant):

System: Windows 10 (but its hardly relevant)
OpenRA Version: Release 20190314

## Experiment:
Steps to reproduce:

1) Set a timer.
2) Go into map editor. 
3) Pick any map. 
4) Delete a spawn point (lets say C) and place a new one 1 single tile above where the previous one was.
5) Exit map editor. 
6) Notice in the preview that the lettering on that map has changed.

7) **Now go and fix it back to the way it was with all the spawn points having the exact same letters, and being in the exact same location as they were previously.**

**Note: Deleting this version and loading a previous version from a backup is cheating.**

8) Check Timer. 
9) How long did that take you to fix? Post the map name and time in the comments.

Thank you again for reading this. 

### Edit: I have added some headings and sections in Markdown for easier readability.

**Comment by PunkPun** [comment]
This can now be achieved by #21255
