### ISSUE TITLE
Mechanic Cancels Orders when Exiting Barracks

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#16809]
If there is a vehicle nearby to repair while the mechanic is exiting the barracks, it will ignore all orders and start repairing the vehicle. Once it starts repairing it can then be given orders.

This probably applies to any unit that "attacks", but is particularly annoying with Mechanics since it will cancel a husk salvage order.

**Comment by pchote** [comment]
This was fixed by #16105 on bleed.
