### ISSUE TITLE
HitShape breaks with MiniYaml conventions

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16817]
https://github.com/OpenRA/OpenRA/blob/86c8dfe96e7f54a37c5a01a2120c8523571c52fa/mods/ra/rules/defaults.yaml#L432-L434

I can circumvent other specialties that would be invalid in "real" YAML to parse OpenRA MiniYaml in other languages but this one is a problem as it breaks with indentation logic.

Can I assume that this is a special case and can/will get fixed?

**Comment by pchote** [comment]
Maybe i'm missing something obvious, but I don't see anything wrong with that code. Can you please elaborate?

**Comment by reaperrr** [comment]
I don't see a difference to, for example, weapon projectiles or some AI definitions, either (wrt sub-properties of properties, assuming that's what this is about).

**Comment by matjaeck** [comment]
I thought it should be 

```
HitShape:
        Type: Circle
        Radius: 128
```

or 
```
HitShape:
        Shape: 
                Type: Circle
                Radius: 128
```
I don't really know how to explain but this can not be parsed because the property can define an "object" but not an "object" and a "value" at the same time. Maybe there is no such convention, that would be unfortunate.

**Comment by matjaeck** [comment]
I didn't notice when writing that this is the standard for weapon definitions, so I'll try to find a workaround.
