### ISSUE TITLE
You can deploy onto other units

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16826]
In TS I gave the Subterranean APC ability to transport vehicles on bleed
Then moved tick tank into it and **double** clicked the deploy button

![Bug](https://user-images.githubusercontent.com/37534529/61622944-7462ce80-ac7e-11e9-925f-0bb90fd42500.gif)

**Comment by Punsho** [comment]
I just realised that this bug can also be reproduced in RA with MAD tanks and Transports. Tho it doesn't show the glitchy undeploy from the gif above

**Comment by pchote** [comment]
The issue here isn't related to transports and isn't specific to TS.

`GrantConditionOnDeploy` has regressed to allow units to allow these units to deploy when they are off-grid. This can be reproduced with a normal move order and the `/terrainoverlay` mode to compare vs the standard cell grid.

**Comment by tovl** [comment]
Currently, `DeployForGrantedCondition` doesn't check if the deploy location is valid at all. 

To fix this, `DeployForGrantedCondition` should call `deploy.CanDeploy()` in `OnFirstRun`.
