### ISSUE TITLE
Leaving a multiplayer game should trigger a surrender

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16829]

**Comment by matjaeck** [comment]
Alternatively, add a win condition for when all opponents either surrendered or left.

**Comment by MustaphaTR** [comment]
> Alternatively, add a win condition for when all opponents either surrendered or left.

This is a better solution imo.

**Comment by Punsho** [comment]
Another solution might be giving that players units to the neutral faction and stopping harvesters from working

**Comment by abcdefg30** [comment]
Also see #13284 and #2022.
