### ISSUE TITLE
Mission lua typo

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#16833]
The `GuardBase` function has a typo (Line 91) in the following mission-AI.lua:

- [nod08a-AI.lua](https://github.com/OpenRA/OpenRA/blob/2c6c2c00b40110ffeb1bbaf9cc870e7b67f0ea8d/mods/cnc/maps/nod08a/nod08a-AI.lua)
- [nod08b-AI.lua](https://github.com/OpenRA/OpenRA/blob/2c6c2c00b40110ffeb1bbaf9cc870e7b67f0ea8d/mods/cnc/maps/nod08b/nod08b-AI.lua)
- [nod09-AI.lua](https://github.com/OpenRA/OpenRA/blob/2c6c2c00b40110ffeb1bbaf9cc870e7b67f0ea8d/mods/cnc/maps/nod09/nod09-AI.lua)

`Trigger.OnDamaged(building, function(guard)`
should be
`Trigger.OnDamaged(building, function()`

**EDIT**:
Also, after Line 128 and 153 (`Trigger.AfterDelay([...])` of Functions
`ProduceInfantry = function(building)`
and
`ProduceVehicle = function(building)`
a `return` Statement is missing.

Otherwise the Function could be sheduled twice.

**EDIT2**:
The AI.lua builds building replacements without checking for available space. It builds over units, buildings and walls. I did't find a corresponding lua command to fix this. I guess it needs its own Issue.

**Comment by abcdefg30** [comment]
This might already be fixed in #16568. Otherwise I'll do it there.

**Comment by abcdefg30** [comment]
> The AI.lua builds building replacements without checking for available space. It builds over units, buildings and walls. I did't find a corresponding lua command.

There exists none. This is a known problem since those missions don't use our normal AI.
