### ISSUE TITLE
RA airfield near east border: planes take more time outside the map

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#16835]
On `bleed` in `RA` Build an airfield next to the east map border. Build a yak.
Compared to `release` it takes much longer (and more circles) until the yak is back on the battlefield.

Regression.

**Comment by pchote** [comment]
The actual regression here is that non-vtol aircraft are no longer moving to the rallypoint after taking off. When the airfield is on the east edge this leaves them circling off-map until the repulsion eventually pushes them back in.

**Comment by pchote** [comment]
Closing as reverse-duplicate of #16912.
