### ISSUE TITLE
Unloading actors ignore passability (and sometimes infantry)

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#16848]
Regressions from #16698 (only noticed them now, unfortunately):

- actors being unloaded ignore passability, tanks on the southern beach landing spot on RA shellmap - as well as infantry unloaded on bridges - will go to impassable cells and as a consequence get stuck there.

- I saw a tank entering a cell occupied by (allied) infantry at least once.

**Comment by reaperrr** [comment]
Possibly related to #16845.

**Comment by teinarss** [comment]
It's possible that this will get fixed by the pr from pchote.

**Comment by reaperrr** [comment]
No, I opened this instead of commenting on the PR because I confirmed that it's both on pchote's PR and bleed.

**Comment by teinarss** [comment]
Could it be that we need to update cache directly in this case instead of
waiting for the end of the frame?
