### ISSUE TITLE
replace pause key with key that is available on laptops

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#16843]
many play the game using a laptop.
my laptop has a meta pause key, but the game/sdl does not recognize  it as being the pause key.
a player paused the game before he left, leaving it impossible to un pause.
add a second key or replace the pause key. or make the blinking pause icon in the top clickable.

**Comment by abcdefg30** [comment]
Fwiw you can remap the hotkey in the settings panel. (So I don't really see the need of a second key.)

**Comment by anvilvapre** [comment]
didn't realize you can remap. 
all players that do not have a working pause key should do that.

**Comment by abcdefg30** [comment]
Closing as "fixed" then.
