### ISSUE TITLE
RA modding problem

### ISSUE THREAD

**Issue by Jeff560BZHfr** [OpenRA/OpenRA#16867]
Hello.

I have a problem on the Openra Tiberium Dawn map maker.

Can you help me to fix this?
I removed accidently the spawn players points before saving, and now, the game crash when i want to open it...

What can i do to fix this problem, i have only the ".oramap" file, i don't have the ".yaml" one to check each element...

The link of my map here : https://resource.openra.net/maps/32267/

Thanks a lot :)

**Comment by reaperrr** [comment]
.oramap files are really just .zip files containing the actual map files, including the map.yaml file.

Just rename the file ending to .zip and any zip program (or even the OS itself) should be able to unzip the files. 

Then add an 'mpspawn' actor with 'Multi0' as owner and a
```
PlayerReference@Multi0:
	Name: Multi0
	NonCombatant: False
	Faction: Random
```

to map.yaml, zip everything back and rename the zip to oramap again, and the map should (probably) work again.

**Comment by abcdefg30** [comment]
@Jeff560BZHfr were you able to resolve this problem?

**Comment by Jeff560BZHfr** [comment]
Thanks a lot, it works so good now :dancing_men: 

It's cause i didn't want any MCV or Conyard in first minutes on the map, i removed too much things to fix the problem. Lol

Thanks again for your help :)
