### ISSUE TITLE
Forgive me if i asked a silly question, how the arc math in MovePart class works?[located in Move.cs]

### ISSUE THREAD

**Issue by Ma-Y** [OpenRA/OpenRA#16866]
<img width="832" alt="Screen Shot 2019-07-31 at 3 09 54 PM" src="https://user-images.githubusercontent.com/48705967/62191027-4891c800-b3a5-11e9-90bb-8dcaf7f1a348.png">

I want to understand specifically the EnableArc part, ignore my drawing skill.
<img width="630" alt="Screen Shot 2019-07-31 at 3 13 25 PM" src="https://user-images.githubusercontent.com/48705967/62191267-c81f9700-b3a5-11e9-98a2-a6ceef1f53d6.png">

of course it is used here to interpolate the position between two cells when moving.
<img width="956" alt="Screen Shot 2019-07-31 at 3 14 08 PM" src="https://user-images.githubusercontent.com/48705967/62191360-ebe2dd00-b3a5-11e9-86e4-b176ae39dcb8.png">

**Comment by matjaeck** [comment]
Hi @Ma-Y, thanks for getting in touch with OpenRA! Usually issues are used to track bugs or feature requests. For answers to generic code questions I can recommend to join the OpenRA discord or our IRC channel - both are linked at openra.net!
