### ISSUE TITLE
Replace or remove actors of non-existing players when saving in the editor

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#16868]
As seen in #16867 you can easily place a new `mpspawn` and a few actors assigned to that player, then remove the spawn and the map will crash when loading the editor. Just remapping the owner of such units to an existing player (e.g. "Neutral" if it exists) on map save (to avoid losing actors when moving a spawn) sounds like a good idea to me. We can also consider removing such actors. (Perhaps this can be done if there are no valid players defined.) Opinions?

**Comment by GraionDilach** [comment]
IIRC the classic games removed actors of nonexistant owners on game load.

**Comment by PunkPun** [comment]
This now crashes on bleed
