### ISSUE TITLE
Request: Ship map 'Climax 2v2' with Red Alert

### ISSUE THREAD

**Issue by phrohdoh** [OpenRA/OpenRA#16865]
Add Climax 2v2 to the official Red Alert map pool.

Comments lately from both high level experienced players and new players have motivated me to ask to add this map to the official map pool.

https://resource.openra.net/maps/32269/

---

_copied from https://github.com/OpenRA/OpenRA/pull/16864/_

**Comment by airetaM** [comment]
The map is full of visual tile errors wich maybe should be fixed first.
I made a short list ( didnt look for roads but they seem to be okay )
cliff errors
27,17
117,70
1,124
36,106
72,45
104,73
108,80
62,57
88,59
92,55
84,53
(mostly missed tile 156)

87,90 and 42,40 twisted cliffs cut in mid

in area around 83,59 several cutted cliffs

106,107 cutted water cliff

86,104 and 71,22 cutted beach tiles

51,38 ore on cliffs ( will not appear in game, just if you counted the ore )

**Comment by wippie-openra** [comment]
Hey Materia. I went in a bit sceptical but you were absolutely right. I reviewed and performed work on  the rocks/cliffs/beaches. 

I started working on this map a long time and many revisions back. Thats were most of the above problems have their origin. Roads have recently been reworked. 

New upload at https://resource.openra.net/maps/32278/

**Comment by Smittytron** [comment]
Was added by #16990
