### ISSUE TITLE
bug in game : Exception of type `System.NullReferenceException`

### ISSUE THREAD

**Issue by woodgreat** [OpenRA/OpenRA#16881]
OpenRA engine version release-20190314
Red Alert mod version release-20190314
Date: 2019-08-05 04:13:53Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: 
at   OpenRA.Mods.Common.Widgets.Logic.LobbyUtils.ShowSlotDropDown(DropDownButtonWidget dropdown, Slot slot, Client client, OrderManager orderManager, MapPreview map)
   在 OpenRA.Mods.Common.Widgets.Logic.LobbyUtils.<SetupEditableSlotWidget>c__AnonStorey15.<>m__2(MouseInput _)
   在 OpenRA.Mods.Common.Widgets.ButtonWidget.HandleMouseInput(MouseInput mi)
   在 OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   在 OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   在 OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   在 OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   在 OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   在 OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   在 OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   在 OpenRA.Widgets.Ui.HandleInput(MouseInput mi)
   在 OpenRA.DefaultInputHandler.<OnMouseInput>c__AnonStorey2.<>m__0()
   在 OpenRA.Sync.RunUnsynced[T](Boolean checkSyncHash, World world, Func`1 fn)
   在 OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input)
   在 OpenRA.Platforms.Default.Sdl2Input.PumpInput(Sdl2PlatformWindow device, IInputHandler inputHandler)
   在 OpenRA.Platforms.Default.Sdl2PlatformWindow.PumpInput(IInputHandler inputHandler)
   在 OpenRA.Renderer.EndFrame(IInputHandler inputHandler)
   在 OpenRA.Game.RenderTick()
   在 OpenRA.Game.Loop()
   在 OpenRA.Game.Run()
   在 OpenRA.Game.InitializeAndRun(String[] args)
   在 OpenRA.WindowsLauncher.RunGame(String[] args)

**Comment by pchote** [comment]
This will almost certainly be caused by an error in a custom map.

Can you please tell us what map causes the crash?

**Comment by Smittytron** [comment]
Closing as this is likely a custom map and OP never responded.
