### ISSUE TITLE
Starting units can overlap in the same cell

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#16880]
Another regression from #16698

<img src="https://user-images.githubusercontent.com/167819/62433927-5beabd80-b72e-11e9-87cb-1c999ac3f829.png">

**Comment by ubitux** [comment]
Ah, just realized this was already reported. Here is a demo on how to reproduce it.

![stack2](https://user-images.githubusercontent.com/34467/62447147-f36b0300-b764-11e9-869d-a21d3f2e5b3f.gif)

**Comment by teinarss** [comment]
> 
> 
> Ah, just realized this was already reported. Here is a demo on how to reproduce it for non-starting units.
> 
> ![stack2](https://user-images.githubusercontent.com/34467/62447147-f36b0300-b764-11e9-869d-a21d3f2e5b3f.gif)

This is another issue that OP, its also fixed in #16861

**Comment by ubitux** [comment]
Ah, sorry about that. I'm still able to reproduce with your branch though.

**Comment by teinarss** [comment]
Are you sure? How?

**Comment by ubitux** [comment]
```
% git describe
playtest-20140607-13402-g18d3864d7
```
(This is `(HEAD detached at teinarss/fix_lm_cache2)`)

I ran `make`, `./launch-game.sh Game.Mod=ra`. Then I'm doing simple standard moves, waiting for 1-2 second between each order to find the best cell I could make them converge to.

Should we move to another issue?

**Comment by pchote** [comment]
To clarify, this issue is specifically about units spawned at the start of the game from the "Starting Units" lobby option. This involves a quite different code path to the other issues.

**Comment by woody3407** [comment]
Ok
