### ISSUE TITLE
ForceEnter no longer works.

### ISSUE THREAD

**Issue by tovl** [OpenRA/OpenRA#16889]
You can no longer order a helicopter with full ammo to land on a helipad with alt-move. This functionality was introduced in #16509 but something has regressed it in the mean time.

**Comment by matjaeck** [comment]
I also noticed this but was not sure if it had worked for fully armed helicopters before. It does work when the helicopter can rearm.

**Comment by pchote** [comment]
Regression was introduced by 4d857dcb46bf048882dfdd305a1148bf9ccd4909.

**Comment by pchote** [comment]
@reaperrr can you provide some context on the explicit `Info.TakeOffOnResupply` checks there, which is disabling this for helicopters?
