### ISSUE TITLE
[devtest-20190807] Can't queue attack move while staying in waypoint mode

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#16907]
When holding Shift, Attack move (and I suppose Assault move as well) can't be issued, orders are queued as common move. Requires unpressing Shift (thus exit the Waypoint mode), press A, then hold Shift and queue Attack move as expected.

**Comment by netnazgul** [comment]
I guess duplicate of #16381

**Comment by Punsho** [comment]
related #16381
