### ISSUE TITLE
Plane queued orders don't work properly

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#16911]
They are on hold-fire stance

![Yaks](https://user-images.githubusercontent.com/37534529/62761882-7c00e080-ba90-11e9-9c96-cfee2d575a08.gif)

![Yaks2](https://user-images.githubusercontent.com/37534529/62761945-a5ba0780-ba90-11e9-8374-1d025cc16a91.gif)

**Comment by matjaeck** [comment]
Is this the testbuild or bleed?

**Comment by Punsho** [comment]
both

**Comment by matjaeck** [comment]
It doesn't happen when there are queued orders orders before the queued attack orders.

**Comment by pchote** [comment]
I expect this is caused by https://github.com/OpenRA/OpenRA/blob/7cfc65010f9eb3a5f8f3b4145e918fa8f2419f8f/OpenRA.Mods.Common/Traits/Attack/AttackFollow.cs#L160-L170 not checking whether the activity was explicitly queued.

**Comment by matjaeck** [comment]
I tried to track down when the regression was introduced but the prior bug that aircraft don't fire on queued attacks makes it really hard. It was introduced after da6bf1a57dc8ead29fbe40b82a20c115451f5442, perhaps in f16ff9eaa0e6ae5dbe55c307f358aab4084abaa8 or 9abf715fd7b2fc5a364f8bee70c865a0ebc1f0ea?
