### ISSUE TITLE
Keep attack move cursor if shift is held

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#16924]
To see the issue hold `shift` then press and release `a` then hold `a`. First mouse click will be an attack order followed by a MOVE order then followed by attack move orders. That move order shouldn't exist

**Comment by matjaeck** [comment]
Cannot reproduce.

**Comment by matjaeck** [comment]
Can you provide a reproduction? I'm not sure if I can reproduce the issue.

**Comment by Punsho** [comment]
I can reproduce it on bleed and on the second devtest with the provided steps


![Attackmove](https://user-images.githubusercontent.com/37534529/62827391-f20f5f80-bbd6-11e9-85af-aec13fa1c23f.gif)
![attackmove2](https://user-images.githubusercontent.com/37534529/62827390-f20f5f80-bbd6-11e9-9bcf-5e3ecd0f42d7.gif)

**Comment by pchote** [comment]
Holding a will trigger the key repeat mechanism after whatever your OS-defined repeat-delay is. If you click before the repeat kicks in, or between the repeat cycles, it will (correctly) issue a move order.

**Comment by Punsho** [comment]
It is the auto repeat. What could be done is attack modifier being carried over between commands if shift is held. IIRC SC2 has modifiers implemented this way

**Comment by matjaeck** [comment]
But it isn't a modifier. You're not suposed to hold down the a-move hotkey like you would do with force fire or force move. See #16908.

**Comment by Punsho** [comment]
I wasn't talking about keyboard modifiers.

**Comment by matjaeck** [comment]
I see. So the proposal is to keep the current OG activated for subsequent orders when shift is held whereas it is currently deactivated after an order.
