### ISSUE TITLE
[devtest-20190810] Unload animation plays twice

### ISSUE THREAD

**Issue by Basti504** [OpenRA/OpenRA#16932]
See GIFS below, it does not happen always.

For Pillbox
![GitHub Logo](https://i.imgur.com/z8JgpuR.gif)

And APC
![GitHub Logo](https://i.imgur.com/RgGyT4r.gif)

**Comment by pchote** [comment]
Related to #16901, but its not clear whether this is an evolution of the same bug or if that one was solved and this is an unrelated regression.

**Comment by pchote** [comment]
Confirmed as duplicate of #16901.
