### ISSUE TITLE
[devtest-20190810] Infantry animation stutter when spawning

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#16930]
Self-explained, easily reproduced. Prob. not easily noticed on my gif though =/
![openra-inf-bug](https://user-images.githubusercontent.com/1614714/62834753-74d8fe80-bc59-11e9-8922-214a86720751.gif)

**Comment by pchote** [comment]
Possibly related to #16932 / #16901.

**Comment by pchote** [comment]
Fixed by #16938.
