### ISSUE TITLE
Decide on and implement coherent behavior when ordering planes to land

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#16936]
In RA/bleed for fully armed planes the enter-blocked cursor is shown when pointing on an unreserved airfield. Nevertheless, they land when you click on the airfield. The underlying question here is if fully armed planes should always be able to land on unreserved airfields (= always show enter cursor) or if the behavior for helicopters should be applied (= show blocked cursor unless ordered to force-land).

**Comment by matjaeck** [comment]
My personal preference is to always show the enter cursor / always allow landing. I find this fits better with their behavior to stay landed after rearming.

**Comment by reaperrr** [comment]
> In RA/bleed for fully armed planes the enter-blocked cursor is shown when pointing on an unreserved airfield.

That's just an unintentional regression, aircraft without `TakeOffOnResupply` were meant to always show the enter cursor (unless the target is reserved).
