### ISSUE TITLE
Make service depot passable

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#16934]
~~Tested on ea80a13b111c022e0ab7ae401ccdfa53b4d3e36b. Players expect that they can place the service depot anywhere without worrying about path finding since it should be completely passable.~~

Initially thought it was always like this, but turned out to be a feature request.

**Comment by abcdefg30** [comment]
I think that is how it always worked. Fwiw, fixing that might lead to pathfinding issues like you have with the ERCC refinery, where units try to path through occupied area (in this case when a unit repairs in the middle) even if they could go around it. Perhaps the pathfinding fixes that are currently added help here already.

**Comment by matjaeck** [comment]
You are right - it has at least been like this in last release. I remembered it wrong.

**Comment by tovl** [comment]
The fact that this is not a regression does not mean it is a bad idea though. Making the service depot passable can easily be done based on bleed. Units being repaired in the middle still block other units like they should.

**Comment by matjaeck** [comment]
> The fact that this is not a regression does not mean it is a bad idea though. 

> `[18:32:49] | <abcdefg30> we could repurpose it to a feature request`

Reopening for discussion.

**Comment by matjaeck** [comment]
One consideration for me is always how it was in the original and our current setup is accurate.
