### ISSUE TITLE
Bug: Engineer remote capturing plus designated getaway Ranger freezing

### ISSUE THREAD

**Issue by FiveAces** [OpenRA/OpenRA#16948]
Last Monday, I had an interesting bug (or rather a series of bugs) occuring live on stream.

Here's a sequence of things happening in order:
-I had a Ranger with an engineer inside, ordered him to move to an oil derrick and then unload the passenger.
-Upon exiting the vehicle, I ordered my engineer to capture the derrick - due to the transport bug present in the bleed version, however, he spawned where he was picked up rather than at the exit cell.
-Rather than teleporting to his designated cell after a couple frames like other infantry do when exhibiting the transport bug, the engineer remained stationary at his point of entrance and captured the derrick from across half the map.
-Since I had previously ordered him to return to his vehicle after capturing, he then started running all the way across the map to meet up with the ranger - all that while providing 0 cells of vision.
-During all that, my Ranger was completely blocked from moving and did not accept any orders whatsoever. Stop commands issued to either unit did not work.
-Only after arriving at his target destination did the engineer return to accepting commands.

This might be 100% attributed to the Transport unload bug, but since the ranger being blocked felt like an unrelated issue to me, I opened this thread. If there's nothing else to it, feel free to delete it or move it to the transport bug discussion.

Clip: https://www.twitch.tv/videos/466330524?t=01h30m32s

Replay: 

[RangerBug.zip](https://github.com/OpenRA/OpenRA/files/3510828/RangerBug.zip)

**Comment by pchote** [comment]
Thanks for the report!

This is a hilarious consequence of #16901, which already has a fix open at #16938.
I'll keep this open for now, though, until someone can explicitly verify the repro case (issue the capture order before the engineer blinks back to its proper location) and fix in #16938.

**Comment by pchote** [comment]
Fixed by #16938 (I hope!)
