### ISSUE TITLE
Attack-move behaviour regressions

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#16940]
The previous complaints about attack move have been focused and investigated on FiveAces' stream tonight (TODO: hopefully can link the VOD after the stream is complete).

The root of the problem seems to be that infantry drop into the attack childactivity and don't let go - they end up chasing something that is too far away to attack, ignoring anything else that *is* in attack range.  Units chasing targets in the opposite direction to the attack-move location's target line also appears to be causing confusion.

Both issues could be improved by having `AttackMoveActivity` store the actor's position when it acquires a target and use some vector math to cancel the attack activity if it moves too far from the acquire-position to order-position line.

It is going to be tempting to scope creep this bugfix into the long-missing hold-ground stance, but that would open up a pandoras box wrt regressions and rebalancing. Better to limit the scope to attack move here, which can be treated as a prototype for a more general fix in a future dev cycle.

**Comment by tovl** [comment]
Even if you limit the chase range with attack-move you will still have units going in the opposite direction. You would also still have units blundering into a hostile force to give chase to one enemy. 

Also, adding a defined range would be opaque and gives little control to the player. I already have some ideas to mitigate this, but that will have to wait for Next+1.

I think perhaps the simpler to implement and more intuitive to use solution (for now) would be to disallow attack-moving units to chase units altogether (similar to defensive stance). Especially at this short notice that would give the least chance of regressions and I guess many players would prefer it for it's predictability.

**Comment by pchote** [comment]
That is indeed much simpler. Worth a try :+1:

**Comment by netnazgul** [comment]
https://www.twitch.tv/videos/466330524 permalink (hopefully)

**Comment by fruestueck** [comment]
[52:55](https://www.twitch.tv/videos/466330524?t=00h52m55s) i guess.

[01:30:28](https://www.twitch.tv/videos/466330524?t=01h30m28s) for engi exiting jeep at previous loading position
