### ISSUE TITLE
Field of view has resilience with multiple units per cell

### ISSUE THREAD

**Issue by ubitux** [OpenRA/OpenRA#16952]
A typical group of 5 infantry has a field of view "memory" depending on where it comes from; it's not a perfect circle:

Coming from east:
![from east](https://user-images.githubusercontent.com/34467/63209264-beed3480-c0de-11e9-90bf-aff1ba751ada.png)

Coming from west:
![from west](https://user-images.githubusercontent.com/34467/63209265-bf85cb00-c0de-11e9-8ebb-6c1a30b74bde.png)

Coming from north:
![from north](https://user-images.githubusercontent.com/34467/63209266-bf85cb00-c0de-11e9-9e3d-21e3adb82d08.png)

Coming from south
![from south](https://user-images.githubusercontent.com/34467/63209267-bf85cb00-c0de-11e9-9258-307f20c6af4f.png)

This means this blob will have an even stronger defender advantage depending on which direction the enemy comes from (an enemy blob of 5 infantry will have to walk 2 cells in the dark instead of 1 while getting shoot at).

This issue **is** also reproducible with diagonal movements.

This issue **is not** reproducible with a single infantry.

This issue is reproducible with `release-20190314` and `bleed` @ 2c24a607

**Comment by matjaeck** [comment]
This is also described in https://github.com/OpenRA/OpenRA/issues/14979#issuecomment-376009722.

**Comment by Punsho** [comment]
Probably the issue I posted was wrong but it is still related #16334
