### ISSUE TITLE
Shellmap attacks are broken

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#16960]
Reported on Discord: units end up stranded and idle. ~Regression from #16942.~

**Comment by pchote** [comment]
The `allowMove` parameter probably should be toggled for AI, like we do for AutoTarget.

**Comment by pchote** [comment]
Looks like this is actually from #16938, so closing in favour of PR discussion.

**Comment by pchote** [comment]
Wrong again. It turns out that this is an old bug, caused by a scripting oversight, which nobody had noticed until they were specifically looking for devtest bugs.

**Comment by tovl** [comment]
It seems there are two distinct bugs here:
- Troops unloaded by the APCs are never given orders. This is a simple oversight in the shell script.
- Paratroopers are given an OnIdle trigger, but this somehow never triggers. This seems to be a bug somewhere deeper.

**Comment by pchote** [comment]
> Paratroopers are given an OnIdle trigger, but this somehow never triggers. This seems to be a bug somewhere deeper.

This is a regression from #16564. `SendParatroopers` claims to be returning a list of the actors to be paradropped (and this is what the Lua API expects), but the PR changes them to be created and added to the list from a FrameEndTask. The immediate return value from that method will be an empty list.
