### ISSUE TITLE
Remove or alter AppearsOnMapPreview on ^Wall

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#16967]
Spotting buildings on the map preview is great but sharing color with fence/sandbag/walls clutters the view on many maps. Imo. capture targets should be obvious so I'd suggest to change the color or simply remove it.

Examples on bleed:
![_mappreview1](https://user-images.githubusercontent.com/2715583/63381416-ec650700-c398-11e9-98b1-e4051166cb36.png)

Examples using
```
^Wall:
	AppearsOnMapPreview:
		Terrain: Tree
```
![_mappreview2](https://user-images.githubusercontent.com/2715583/63381627-5ed5e700-c399-11e9-9b6e-a13bbd122a6d.png)

TD oil pumps are 1x1 cells and are virtually invisible with maps decorated with walls.

I'd love to bring in a PR on the issue but seeing #16448 I wouldn't know how to get about it.

**Comment by pchote** [comment]
The lobby previews match what is shown ingame. Are you suggesting we remove the player color from the radar too?

**Comment by matjaeck** [comment]
> The lobby previews match what is shown ingame

Actually not - as described in the request, the position of capture targets is not visible in the previews, and they do not look identical to walls ingame. Until there is a solution for #3359, the requested change provides this information in exchange for information about walls. The position of walls is not as important as the position of capture targets, so it's an improvement for players (who don't know the map).

**Comment by pchote** [comment]
Using the Great Sahara example above:

![Screenshot 2019-08-22 at 11 05 04](https://user-images.githubusercontent.com/167819/63506130-c5a7ed00-c4cc-11e9-94a6-ffbdcbd524f6.png)

![Screenshot 2019-08-22 at 11 05 13](https://user-images.githubusercontent.com/167819/63506132-c771b080-c4cc-11e9-9996-be5b487d2851.png)

The walls are displayed as Neutral-player white in both.

**Comment by matjaeck** [comment]
Welp, thanks for clarifiying. I agree that minimap and preview should be identical, but still think it's an improvement to know where capture targets are located. Perhaps it's better to handle this in / wait for #3359.

**Comment by SoScared** [comment]
Yeah you're gonna have to decide if you're comfortable with that. For the sake of useful pre-game information I wouldn't personally mind it. Also worth noting, while in-game the minimap doesn't show any neutral/player structures until it's scouted by the player.

**Comment by MustaphaTR** [comment]
When i added AppearsOnMapPreview to Walls, i was thinking about actual walls like on KotG. I forgot about the fences.

**Comment by pchote** [comment]
What colour did the original game use for these? We have a `Wall` terrain type, which is a more logical choice than `Tree`.
