### ISSUE TITLE
Unit will not repair if sort of close by shipyard

### ISSUE THREAD

**Issue by Basti504** [OpenRA/OpenRA#16965]
Excuse the vague title, it is better explained below.

Playing the new devtest 20190818 in single player missions I encountered that a ship that was damaged was near the shipyard. When the ship was ordered to repair at the shipyard, the boat ignores this order and does not move.

I reproduced it in image below. It looks like there is a (1 cell wide?) circle around the shipyard where the boat will not execute the repair order. If I move the boat one cell away from the shipyard it will move and repair, the "repairing" sound plays.

![This is a image](https://i.imgur.com/DYY0dwF.gif)

**Comment by reaperrr** [comment]
I suspect that the "move near" part checks against the syards' footprint (closest cell), while the "close enough to repair" part checks against the center of the syard.

**Comment by pchote** [comment]
This is indeed correct, and I think I remember there being a specific reason for this rather than using `Target.IsInRange`. Can you elaborate on that @reaperrr?

**Comment by reaperrr** [comment]
We changed that in #16789 to fix #16782.

A short-term fix might be to use `Target.IsInRange` again, but of course only for `RepairableNear` actors.

**Comment by pchote** [comment]
That sounds like the best solution. Do you want to file a PR?

**Comment by reaperrr** [comment]
Yeah, will do, probably tomorrow.

**Comment by pchote** [comment]
Fixed by #16969.
