### ISSUE TITLE
OpenRA Replay can be saved into mp4 or any other video format

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/OpenRA#16970]
For now, openra reply file format only contains some game data, when openra play reply, it will start a new game, rule the game with these data
but I think it could be better if openra can provide the video format export, so that we don't need to use other software to record the game.

**Comment by abcdefg30** [comment]
Sorry, I don't understand how this is supposed to work. Which part of the map would be recorded, or would the entire map be recorded? Which view (none, all players, a single player, ...) would be used? And so on. It does sound better to me to actually use a recording software that is built for such things.

**Comment by cookgreen** [comment]
> Sorry, I don't understand how this is supposed to work. Which part of the map would be recorded, or would the entire map be recorded? Which view (none, all players, a single player, ...) would be used? And so on. It does sound better to me to actually use a recording software that is built for such things.

Well
1. Which part of map: current viewport
2. Which view: current player

**Comment by netnazgul** [comment]
So basically you want to integrate something as complex as OBS into OpenRA engine.

Don't really see it viable, where instead you can use "other software" created specifically for this task.
