### ISSUE TITLE
Asset browser frame counter starts from 0

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#16991]
![asset-browser-framecount](https://user-images.githubusercontent.com/1355810/63656149-54508e80-c799-11e9-959a-ad12049f4151.png)

The sequence shown above has 8 frames but the counter to the right shows "0/7". Which is correct if we count from 0, but this is misleading as there are a total of 8 frames. I wonder if this was made on purpose or is an oversight.

**Comment by abcdefg30** [comment]
I am pretty sure that is on purpose. We use that counting method in the sequence yamls as well.

**Comment by dragunoff** [comment]
Yes, that makes sense. Ok, closing this then.
