### ISSUE TITLE
CRASH with emty logs

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#16997]
Test run Openra lastest release and playtest on Sumsung N100SP, Windows x86.
CRASH after run, in several seconds of black screen.
How can I see/find core of the issue?

**Comment by abcdefg30** [comment]
This sounds more like a graphics card issue to me if OpenRA is crashing without writing logs.

**Comment by yaaaaa** [comment]
Intel Graphics Media Accelerator (GMA) 3600 Series is not supported?

**Comment by Smittytron** [comment]
Closing as nothing to go with here.
