### ISSUE TITLE
Possible to move a unit onto a harvester

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#17009]
![grafik](https://user-images.githubusercontent.com/7704140/63979270-bf130a00-cab8-11e9-968e-430038759c74.png)

Branch/commit: https://github.com/OpenRA/OpenRA/commit/624255f3245299b8383786e375fef59244c3b0fe
Replay: [OpenRA-2019-08-29T212529Z.zip](https://github.com/OpenRA/OpenRA/files/3557484/OpenRA-2019-08-29T212529Z.zip) around minute 15:45 in the enemy base.

**Comment by abcdefg30** [comment]
Reproduction case is relatively simple: Just call in a harvester via `Reinforcements.Reinforce`.

**Comment by reaperrr** [comment]
I guess that's [SpawnActorEffect](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Effects/SpawnActorEffect.cs)'s fault for using `MoveTo` (which ignores other actors).

The safest/fastest fix would probably be to revert the changes to `ReinforcementGlobal` from #16015 and reintroduce them once we have a proper, reliable fix for `SpawnActorEffect`.

**Comment by GraionDilach** [comment]
I've fixed SpawnActorWarhead in AS to prevent stacking a few weeks ago myself.

**Comment by tovl** [comment]
I'm confused. `MoveTo` doesn't ignore other actors, does it?

**Comment by matjaeck** [comment]
This was fixed by #17133, wasn't it?

> Resolves the specific case of #17009.

**Comment by abcdefg30** [comment]
Yes.
