### ISSUE TITLE
Earnings and army graphs are not/weirdly updated (Bleed)

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#17002]
Hi !

### Issue Summary

As an observer of a 100 % AI game, I noticed earnings and army graphs were not updated.
They showed values for the first minute only.
I waited a bit and saw the values for the second minute showing at the 14th game minute.
Like one earning/army graph minute = seven game minutes ?
Screenshots are self explanatory.

Edit : the values for the 3rd minute appeared at the 21st game minute so there is definitively a ratio of 7 between the graphs time and the game time.

#### System Information

- Operating System : Windows 10
- .Net / Mono Version : .Net 4.7.2
- OpenRA Version : bleed
- Mod : Red Alert

#### Additional Information:

- Steps to reproduce :
Observe a game for at least 14 minutes.

![OpenRA-2019-08-28T155005162Z](https://user-images.githubusercontent.com/54636529/63871719-b3dab400-c9bc-11e9-9f90-fe6174951611.png)

![OpenRA-2019-08-28T155336140Z](https://user-images.githubusercontent.com/54636529/63871794-d967bd80-c9bc-11e9-86f0-9d6349a5b781.png)

**Comment by GraionDilach** [comment]
The game needs to be observed on _fast_ gamespeed to properly reproduce.
