### ISSUE TITLE
[playtest 20190825] make chronosphere work on landed aircraft (helicopters)

### ISSUE THREAD

**Issue by fanick1** [OpenRA/OpenRA#17027]
Title says it all - the chronosphere does not work on helicopters that are landed, where landing a helicopter feature has been added in the latest playtest. I'm not saying this is extremely important but if you imagine the endless possibilities :)

**Comment by netnazgul** [comment]
Iron Curtaining and Chronoshifting landed air units actually worked in devtests, but was explicitly removed.

**Comment by tovl** [comment]
Not quite: Iron Curtain worked, chronoshift did not. That was the reason Iron Curtaining was disabled for the short term, because for balance reasons it would need to be both or nothing.
