### ISSUE TITLE
High bridges are broken

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#17031]
Units do not pass over them anymore.

![resim](https://user-images.githubusercontent.com/7933210/64079719-5f547300-ccf3-11e9-8f09-957d01fe7b9d.png)

**Comment by tovl** [comment]
Jumpjet troopers and subterranean units are also broken. Must be the same problem.

**Comment by teinarss** [comment]
Correct, missed the whole aspect on Custom Movement Layers in the Locomotor Cache! :P
