### ISSUE TITLE
[playtest-20190825] Cargo unload bug

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#17047]
Reported on #bug-reporting

goat:
> at approx 03:45 I have an apc with 3 rockets and an engi, yet when I told it to unload the first time only the engi exited. not sure if I somehow managed to cancel the unloading?

https://cdn.discordapp.com/attachments/279290580201373696/618580877978632192/goatblackenedpt.orarep

**Comment by pchote** [comment]
The replay shows that goat gives the APC a move order, which cancels the unload order before it completes.
