### ISSUE TITLE
[playtest-20190825] RA: Landed helicopters can be Iron Curtained

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#17051]
Reported in #bug-reporting.

Grounded helicopters can be ICed. Those landed on a helipad can't be directly targeted (cause they land between cells), but IC on a helipad covers the landed helicopter as well.

![image](https://user-images.githubusercontent.com/1614714/64373641-57663d00-d02b-11e9-8d5b-8c93a8c2bf43.png)

**Comment by netnazgul** [comment]
Further testing - planes can be Iron Curtained as well (when landed on an Airfield).

**Comment by tovl** [comment]
I'm not sure if this is a bug or a serendipitous feature. Is there a specific reason for not wanting to allow iron curtains on airplanes?

**Comment by pchote** [comment]
If nothing else it will have an unexpected impact on balance, so it would be wise to disable until the community has had a chance to properly test and rebalance if needed.

**Comment by abcdefg30** [comment]
We also don't allow chronoshifting them iirc. Imho it should be both or nothing. :+1: to disabling it for the short term.

**Comment by pchote** [comment]
Chronoshifting planes from the airfield to the ground would be bogus (it would need to kill them instead). Chronoshifting force-landed helicopters could be interesting, but I expect it would require significant changes to the chronoshifting code.
