### ISSUE TITLE
Heli take off auto Attackmove

### ISSUE THREAD

**Issue by UppsAlert** [OpenRA/OpenRA#17054]
(Playtest) Their is a weird thing after you land Black Hawks and Longbows.
After they take off again they are on a invisible (no redline) Attackmove order.
First I thought they change their stance, but no its just a attackmove.
[after take off attack move bug.zip](https://github.com/OpenRA/OpenRA/files/3585926/after.take.off.attack.move.bug.zip)

**Comment by matjaeck** [comment]
I remember a conversation in an issue or PR where reaperrr points out that fixing this requires changes deeper in the the activity code, but can't find it.

**Comment by abcdefg30** [comment]
I suppose #17017 is fixing this?
