### ISSUE TITLE
Multi-Sequence Format

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/OpenRA#17069]
Since OpenRA only support one Sequence Format in mod

mod.yaml:
```
SpriteSequenceFormats:
    DummySequenceFormat:
        ....
    PlaceHolderSequenceFormat:
        ...
```

**Comment by pchote** [comment]
This can be implemented at the mod level - define your own `DummyAndPlaceholderSequenceFormat` that detects the format and then picks which parsing rules to use.

**Comment by cookgreen** [comment]
> This can be implemented at the mod level - define your own `DummyAndPlaceholderSequenceFormat` that detects the format and then picks which parsing rules to use.

But if so, you need the additional code to detect the extension

**Comment by yaaaaa** [comment]
D2k use different support format for seqenses by default, nut we may write extension dirrectly, if use "AddExtension: false" trait

**Comment by yaaaaa** [comment]
but PNG parser not exist code to use it for sequences, and this will not work before https://github.com/OpenRA/OpenRA/commit/c1e307240425b3053755a360659daa00f384a799 or https://github.com/OpenRA/OpenRA/pull/16885 is not merged. Do I get it right?

**Comment by GraionDilach** [comment]
PNG parser exists for indexed PNG already. KKND can be used to provide examples because the originally provided example in #15800 is gone.

**Comment by yaaaaa** [comment]
> 
> 
> PNG parser exists for indexed PNG already. KKND can be used to provide examples because the originally provided example in #15800 is gone.

Thanks!! but I cant understand what is wrong - i just copy this files on the bits folder? and copypast code from KKND

```
	idle: bits/MWall.png
		Length: 16
	damaged-idle: bits/MWall.png
		Start: 16
		Length: 16
	make0: bits/MWall.png
		Start: 32
	make1: bits/MWall.png
		Start: 33
	make2: bits/MWall.png
		Start: 34
	icon: bits/Buttons.png
		Start: 13
```
and have same issue - unit note have sequense named IDLE...

**Comment by GraionDilach** [comment]
You need AddExtension: false in the sequence and include the frame metadata in the PNG.

**Comment by yaaaaa** [comment]
Yes, i go this, but when i replace MWall.png to another, i gon an issue:
Exception of type `System.InvalidOperationException`: :0: Sequence hive.idle uses frames [0..15], but only 0..0 actually exist
   в OpenRA.Mods.Common.Graphics.DefaultSpriteSequence.<>c__DisplayClassb.<.ctor>b__0(Int32 frameCount) в c:\games\RTS\04.10.19\Yuris-Revenge-master\engine\OpenRA.Mods.Common\Graphics\DefaultSpriteSequence.cs:строка 208
i must change format of my PNG files? its palette?

**Comment by GraionDilach** [comment]
1. Download https://github.com/IceReaper/KKnD/blob/master/mods/kknd1/bits/Buttons.png 
2. OpenRA.Utility --png-sheet-export kkndbuttons.png 
3. Read the new yaml created next to it and compare it with the PNG
4. Place a yaml formatted the same next to your MWall.png
5. OpenRA.Utility --pngh-sheet-import MWall.png
6. Notice how MWall.png's filesize increased
7. Use the new MWall.png instead of this last one
8. ???
9. PROFIT!

**Comment by yaaaaa** [comment]
```
Microsoft Windows [Version 10.0.18970.1005]
(c) Корпорация Майкрософт (Microsoft Corporation), 2019. Все права защищены.

C:\WINDOWS\system32>C:\games\RTS\openrakknd\OpenRA.Utility --png-sheet-export kkndbuttons.png
Run `OpenRA.Utility.exe [MOD]` to see a list of available commands.
The available mods are: kknd, kknd1, kknd2, modcontent


C:\WINDOWS\system32>C:\games\RTS\openrakknd\OpenRA.Utility --png-sheet-export kknd buttons.png
Run `OpenRA.Utility.exe [MOD]` to see a list of available commands.
The available mods are: kknd, kknd1, kknd2, modcontent


C:\WINDOWS\system32>C:\games\RTS\openrakknd\OpenRA.Utility.exe kknd

Необработанное исключение: System.NotSupportedException: Предпринята попытка загрузить сборку из сетевого ресурса, что в предыдущих версиях .NET Framework могло привести к помещению сборки в "песочницу". Этот выпуск .NET Framework не включает политику CAS по умолчанию, поэтому данная загрузка может быть опасной. Если эта нагрузка не предназначена для изоляции сборки, включите переключатель loadFromRemoteSources. Дополнительные сведения см. на странице http://go.microsoft.com/fwlink/?LinkId=155569.
   в System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   в System.Reflection.Assembly.LoadFile(String path)
   в OpenRA.ObjectCreator..ctor(Manifest manifest, InstalledMods mods)
   в OpenRA.ModData..ctor(Manifest mod, InstalledMods mods, Boolean useLoadScreen)
   в OpenRA.Program.Main(String[] args)

C:\WINDOWS\system32>

i will try
```

**Comment by GraionDilach** [comment]
kknd1

**Comment by GraionDilach** [comment]
Regardless, this ticket should be closed, because there is no need for it. A single customized sprite loader already covers all the cases required.

**Comment by yaaaaa** [comment]
i Agree, many sankses! i will try it
