### ISSUE TITLE
Image links are broken on "Creating a new unit" wiki guide

### ISSUE THREAD

**Issue by phrohdoh** [OpenRA/OpenRA#17072]
https://github.com/OpenRA/OpenRA/wiki/Creation%20of%20a%20new%20unit%20for%20OpenRA%20(step%20by%20step)

We should probably host images on GitHub directly if we're able to.

---

Reported by `russia_nekto` [on Discord](https://discordapp.com/channels/153649279762694144/388282819371204608/620719950281048064).

**Comment by yaaaaa** [comment]
++
And please add to tutorial how to prepare and use sequense.png files without convertion into shp, touch a invisible and playercolor moments, and about its pallete...

**Comment by Mailaender** [comment]
https://github.com/Mailaender/OpenHV/commit/ad77a4710fc6d384e82f3da2b2c415fb0bea56d8 might help you there. Use

```
OpenRA.Utility.exe ra --png-sheet-import PNGFILE
```

I kept the .yaml file I used in the repository although the data is now inside the .png file.

**Comment by Mailaender** [comment]
I [removed](https://github.com/OpenRA/OpenRA/wiki/Creation-of-a-new-unit-for-OpenRA-(alternative)/_compare/480954d73823e18ff2b00f93df78e25507e4cf09...6f5c82d21110bcf97241f6fccb90e597fde91eb7) the tutorial as it is useless without the screenshots.
