### ISSUE TITLE
System.DivideByZeroException: Attempted to divide by zero

### ISSUE THREAD

**Issue by Pummelchen** [OpenRA/OpenRA#17082]
#17025 Issue Summary

Game crashed with "Fatal Error" while playing a custom 256x256 map with 2x6 players, of which 11 were AI.

#### System Information
- Windows Server 2019
- .NET 4.6/7/8 .. many editions installed as its a developer notebook
- OpenRA engine version playtest-20190825
- Red Alert mod version playtest-20190825
- RA

#### Additional Information:
I made a plain simple map, mostly water, two strips of grass on north and south side and each strip as 6 starting points. Bit of ore in each corner of the strip, very simple design.

While the game was running for maybe 30 min, it suddenly crashed with "Fatal Error".

[exception-2019-09-11T150049Z.zip](https://github.com/OpenRA/OpenRA/files/3601438/exception-2019-09-11T150049Z.zip)

**Comment by teinarss** [comment]
Fixed by #17045
