### ISSUE TITLE
Idea: Spy infiltrating tech buildings

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#17091]
A spy could sabotage e.g. the allied tech center to reset (or delay) the Satelite countdown or force the orbiting sattelite to mailfunction (for some downtime) or crash.

The same could be applied to the chronosphere, iron curtain and missile silo (timer reset).

A side effect could be players protecting tech buildings with walls or dogs.

The topic was discussed a few times (#2285, #10732) in a similar way but the idea of a timer reset did not came up as far as I read. If the spy is already to powerful or there is no need for additional useage scenarios feel free to close this topic.

**Comment by matjaeck** [comment]
We had a similar discussion in #16647 and there have so far not been any general objections against a reset ability.

**Comment by fruestueck** [comment]
Thank you. I'll close this one
