### ISSUE TITLE
Aircraft trait is not conditional

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#17096]
It is a problem in TS as aircraft can be EMPed. There's no way to stop an aircraft from moving and loading / unloading cargo

**Comment by GraionDilach** [comment]
Technically - EMP crashed aircrafts in TS which is already doable with triggering a `KillsSelf` so it should not be a problem there.

**Comment by pchote** [comment]
[LandOnCondition](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Air/Aircraft.cs#L154) should hopefully cover most other usecases. We could consider promoting this to the conditional (paused?) trait behaviour.

**Comment by Punsho** [comment]
I tried adding `LandOnCondition: empdisable` on TS aircraft and when I give them a move order while they're EMPed they lift up and permanently freeze. They do not respond to any orders in that state even when the EMP effect wears off

**Comment by tovl** [comment]
`LandOnCondition` is broken beyond repair (I have no idea if it ever was functional) and is not currently used for anything. It should just be removed and maybe reimplemented from scratch if there is an actual usecase that cannot be done in any other way.

**Comment by Punsho** [comment]
If we make EMP crash flying aircraft and leave it at that it would only be detrimental to gameplay. Aircraft are very expensive and losing a flock of them would usually lead to defeat. We need to have proper warnings and a longish delay on EMP cannon so you'd have time to react. I'll probably make a PR for adding this feature and we can figure out balance when TS is closer to release

It still would not make sense to have landed aircraft blowup so that issue remains

**Comment by GraionDilach** [comment]
In standard TS gameplay EMP can't even affect units in air - neither the EMPCannon, neither the Mobile EMP could reach flying aircraft. The sole usecase of the EMP crash in TS was used by the Ion Storm, which crashed all flying units and sank the Hover MRLS in water.

Sure, landed aircraft just got disabled, but I presume that can be done with a `SpeedMultiplier: 0` for now.

**Comment by tovl** [comment]
If subterranean units go to the surface at the nearest available spot when EMPed, then it would also make sense for aircraft to land at the nearest available spot when EMPed. It would be less disproportionately punishing, but still allows it to be used meaningfully against airborne units.

This should be implemented by making `Aircraft` pausableConditional so it would work the same as `Mobile`.

**Comment by Punsho** [comment]
It should work the same as `mobile`. 
As Graion said in the original EMP didn't work on airborne Aircraft. EMP should only hit landed ones and disable them. But I'm not saying that it shouldn't be possible to disable midair for modders though
