### ISSUE TITLE
Infantry units can stack on top of each other

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#17106]
Place the rally point of barracks on top of one of its exits then in quick succession order a few infantry. Those which came from the selected exit will stack on top of each other.

**Comment by netnazgul** [comment]
I have an even more funnier repro - drop X paradrops into the same location:

![openra_paratroopers](https://user-images.githubusercontent.com/1614714/64962866-e3d0f500-d8a0-11e9-9c1f-ce7100c63697.gif)

**Comment by tovl** [comment]
This could be the same bug as in #17009. Possibly related to the `Locomotor` cache. Since this seems to happen only with newly spawned units it might be that the cache is updated too late (or too early)?

**Comment by teinarss** [comment]
Will take a look at it tomorrow!

**Comment by teinarss** [comment]
These two are two different bugs. 

Dropping paratroopers on the same location is present on the last release too. Question is how we want to handle that? Dont drop the cargo if there is no empty subcell?

![para](https://user-images.githubusercontent.com/19173272/65070351-c24d3780-d98c-11e9-8351-fbf22a052248.gif)

**Comment by GraionDilach** [comment]
Yes. Paratroopers need to be refactored anyway - in RA2, paraplanes just kept coming back constantly picking up free cells if they still had units to drop.

**Comment by netnazgul** [comment]
I guess paratroopers are fine to be fixed later and are a separate issue from the OP.

I've seen the OP yesterday when FiveAces undeployed 2 rocket soldiers into the same subcell from 2 rangers. They also fired in the same tick, so the only way to spot that was to hear the increased fire sound volume.
