### ISSUE TITLE
TS vehicles / aircraft do not emit smoke when damaged

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#17109]

**Comment by abcdefg30** [comment]
Kind of a duplicate of #9409.

**Comment by GraionDilach** [comment]
Keep in mind that in TS, vehicles spawned smoke when they go damaged, and periodically spawned sparks during damaged. (RA2 broke this latter and only Ares restored it.)

RV has accurate-to-TS behaviour.

**Comment by Punsho** [comment]
I wonder what #7365 is about then

**Comment by GraionDilach** [comment]
#7365 is about the harvester animation having wrong offset.

https://github.com/OpenRA/OpenRA/blob/bleed/mods/ts/sequences/vehicles.yaml#L21

**Comment by Punsho** [comment]
closing this as duplicate of #9409.
