### ISSUE TITLE
TS: Hunterseeker broken

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#17111]
The hunterseeker just flies circles (or stays put) at own base. Not sure if regression or yet not fully implemented.

Replay on request.

How to reproduce

1. Start skirmish
2. debug cmd `/all`
Or play a game against 7 bots 
3. build hunterseeker and launch it

**Comment by Punsho** [comment]
it is not implemented yet #12918

**Comment by fruestueck** [comment]
Thx
