### ISSUE TITLE
Non-remap red pixels on deployed TS Tick Tank

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#17118]
From #17117:
https://user-images.githubusercontent.com/7704140/65043286-eb54d480-d95a-11e9-88e2-b411b750eb2c.png

Those red pixels look like conversion errors in the sprite that should be remappable.
Easy fix, so we shouldn't delay this forever just because there are technically more important things to do.

**Comment by ghost** [comment]
Is this still an issue? I can take a look at it, if it's really easy. Where can I get started?

**Comment by reaperrr** [comment]
You would have to extract the gatick/gttick.shp files from the TS mix files (temperat.mix and snow.mix, probably), fix them in something like OS SHP Builder and submit a PR with the fixed shps in the bits subfolder.

**Comment by ghost** [comment]
I had found the gatick/gttick.shp in the asset browser, but am having a difficult time with the utility program. I thought the command --extract would extract the *.mix file, that isn't the case. I'm not sure if it can extract the *.mix files, and didn't see anything to repack it either. I tried asking in IRC but didn't get a response, sorry to bother you about this.
