### ISSUE TITLE
Please add flip facings to engine for modders.

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#17120]
https://github.com/IceReaper/Earth2140/blob/master/OpenRA.Mods.E2140/Graphics/Earth2140SpriteSequence.cs

(to srites economy)

**Comment by dragunoff** [comment]
The idea here is to add support for sequences made of sprites that contain only half of the facings with the engine creating the other half by mirroring on the Y axis. 

This is possible with `Combine` blocks but the YAML becomes bloated. The example linked above works around that by generating the YAML.

**Comment by yaaaaa** [comment]
in my variant its needs mirroring on the X axis.

**Comment by pchote** [comment]
`FlipX` and `FlipY` can be defined in sequence blocks or `Combine` sub-blocks to mirror frames in x/y.

**Comment by dragunoff** [comment]
Well, then this needs to be documented. Ideally with some examples.

**Comment by reaperrr** [comment]
They're booleans, so `FlipX: true` for horizontal mirroring and `FlipY: true` for vertical.

The `building_napalm` explosion (misc.yaml) in RA/TD mods uses `FlipX: true`.

**Comment by GraionDilach** [comment]
#15377 could be the ultimate example case here.

**Comment by yaaaaa** [comment]
Thanks, its really work
