### ISSUE TITLE
Questions: msam AA missions, Airstrikesquad spacing

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#17128]
While converting cnc missions a couple of questions came up:

1) In vanilla TD a GDI msam is able to not only attack ground but also airborne units. This is especially notable in gdi08b as the player is given two msam's to shoot down enemy reinforcement chinooks.
Could we add AA abillity to campain rules for msam units?
Or is there any particular reason against it?

2) As the Airstrike squadsize in vanilla TD for missions (like 08a, 08b, 09) is two, the spacing between the remining A10 bombers is to big which results in almost no damage on the actual target cell. How could I reduce that spacing with yaml?

**Comment by Punsho** [comment]
You can play with weapon reload time and amount of ammo to change bomb spacing

**Comment by fruestueck** [comment]
> 
> 
> ... bomb spacing

Its about the space between the A10 Bombers.

![a10-spacing](https://user-images.githubusercontent.com/25386322/65228855-840a6200-dacb-11e9-96f3-b507c9f496b2.gif)

To kill the light tank, over 10 Airstrikes are needed. An arty dies with the first strike

**Comment by pchote** [comment]
The spacing between the planes is controlled by the `SquadOffset` parameter on `AirstrikePower`.

**Comment by fruestueck** [comment]
That helped a lot. Didn't find it in the cnc rulesets as it is only written in ra and d2k

Any thoughts on msam AA abillity for missions?

**Comment by abcdefg30** [comment]
For 1: Would giving the player two APCs instead work (they can shoot aircraft)?

**Comment by fruestueck** [comment]
That would do the job as well. I'll add one APC as two kill a hinook in no time. The msam's are a nice addition as they are not buildable in the mission.
