### ISSUE TITLE
gl_DrawCalss from Renderables overdraws so much Dune2 mod

### ISSUE THREAD

**Issue by alexeik** [OpenRA/OpenRA#17130]
![blendmode](https://user-images.githubusercontent.com/318732/65262513-2e59a800-db13-11e9-93ca-bd4f9f075995.png)

**then this Flush disabled**
we got constant batchrate=8 on left  and variable batchrate on right with Enabled.
on bleed branch(assume it is  left sided) we will have batchrate=11 not 8. because of prev issues for gl_DrawCalls in SmudgeLayers & BuildableTerrainLayer.

below animated gif.
![2019-09-19_19h27_01](https://user-images.githubusercontent.com/318732/65262767-b9d33900-db13-11e9-8ae3-fc8c7a9badd6.gif)

**Comment by pchote** [comment]
What is the actual problem you are trying to raise?

When a mod switches drawing modes the engine is forced to flush the buffed draw calls.

**Comment by alexeik** [comment]
to make batch count value on right, just downloaded bleed branch and run.

**Comment by alexeik** [comment]
im just do some stuff in dune2, and notice this anomalous.
now i rerun official mods and there are normal batches.
but in dune2 mod, its as on animation.
sprites comes with variable BlendMode and it forces to call gl_DrawCalls too much.

**Comment by GraionDilach** [comment]
@alexeik The default blendmode is not `None` but `Alpha`. So if an entry lacks the blendmode and another has None, the switch makes sense. Also, D2k also comes with different blending modes, so that should also be affected.

@pchote: What I interpret is that there are just too many context switches from the usage of different blendmodes. Could the renderables be reordered somehow to decrease the amount of flushing required, or would that interfere with the Z-ordering?

**Comment by alexeik** [comment]
how to set BlendMode for sprite? yaml or what part ?
need some test to make a batch test of sprites in game to decrease calling gl_DrawCalls.

**Comment by GraionDilach** [comment]
BlendModes are set in YAML - https://github.com/OpenRA/d2/search?l=YAML&q=blendmode - which correspond to https://github.com/OpenRA/OpenRA/blob/afe3e24cda980ac8dfc4507767443851d5a29a26/OpenRA.Platforms.Default/Sdl2GraphicsContext.cs#L191.

**Comment by alexeik** [comment]
its like a blend sprites between map tiles sprites?

**Comment by GraionDilach** [comment]
@pchote Watching the main menu of the Dune 2 mod with pixel doubling mode leads to a constant 40 batches per second on my system after the harvesters arrive and start doing their job (both on https://github.com/OpenRA/d2/pull/146 and on the release-20190314 version). No changes in code were made.

![image](https://user-images.githubusercontent.com/1136302/65517162-8cef9f00-dee2-11e9-91ee-d62e2c0df4ed.png)

Ignore the huge rendering time, I have VSync enabled within the NVidia driver and that throws off the rendering graphs.

**Comment by alexeik** [comment]
@GraionDilach the cause is Renderables with different BlendMode.
Wait till scenario of shellmap ends and u will see 9-11 batches constantly.

**Comment by abcdefg30** [comment]
https://github.com/OpenRA/d2/issues/151 was resolved.
