### ISSUE TITLE
String Export tool

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/OpenRA#17148]
We can make a translation export tool or utility command which can export all string defined in rules, sequences, chromes, etc to a single yaml file
We can add an attribute something like `Translatable` or `Localization` to attch it into the field which will be exported

**Comment by cookgreen** [comment]
And we also need a GUI-based translation tool which can translate the string into the target language.

**Comment by abcdefg30** [comment]
What about https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/UtilityCommands/ExtractLanguageStringsCommand.cs ?

Also see #10475.

**Comment by cookgreen** [comment]
@abcdefg30 
![image](https://user-images.githubusercontent.com/21171007/65667762-f4d4ef80-e072-11e9-9c41-cf359cd79bec.png)

**Comment by abcdefg30** [comment]
Ah well, looks like that command is broken: #17149.

**Comment by cookgreen** [comment]
@abcdefg30 I think you guys can try this one:
https://github.com/cookgreen/Yuris-Revenge/blob/master/OpenRA.Mods.YR/UtilityCommands/ExportTranslationStringCommand.cs

**Comment by Mailaender** [comment]
There is already a `[Translate]` field and a translation system in the background. It is just disabled (see the options) as it is incomplete.

**Comment by reaperrr** [comment]
Closing as duplicate and since the utility command has been fixed.
