### ISSUE TITLE
RA: spy should target fake structures

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#17145]
As discussed in 5A' latest stream, spies can be missused to reveal fake structures as they can't be ordered to enter a fake structure.

Should we fix this?

There are a couple of options:
1) A spy gets consumed and a Fake tag is added to the building visible for the player and allies
2) same as 1) but the spy walks out again (not consumed)
3) spies reveal fake structures on sight

**Comment by pchote** [comment]
> A spy gets consumed and a Fake tag is added to the building visible for the player and allies

This has been implemented for a long time. I just tested it, and it still works.
