### ISSUE TITLE
Can't build pre-1908: 'UpdatesDerrickCount' could not be found

### ISSUE THREAD

**Issue by oldnaari** [OpenRA/OpenRA#17151]
### Issue Summary

Gives the following error when building using make.cmd, or make.ps1
```
error CS0246: The type or namespace name 'UpdatesDerrickCount' could not be found (are you missing a using directive or an assembly reference?) [C:\Users\user\Documents\GitHub\OpenRA-fork\OpenRA.Mods.Common\OpenRA.Mods.Common.csproj]
```
#### System Information
- **Operating System:** Windows 10
- **.NET / Mono Version:**  .NET 4.6.1 and others
- **OpenRA Version:** pre-1908

**Comment by abcdefg30** [comment]
Looks like @teinarss forgot to pick https://github.com/OpenRA/OpenRA/commit/1e6660ecb2a529854518cbb8ea395c10f839052e to prep! This also causes the build to fail since then which nobody noticed...

**Comment by abcdefg30** [comment]
I force pushed the commit onto prep, so this should be fixed now. Thanks for the report.
