### ISSUE TITLE
Use extension to find the suitable sprite loader to load a sprite

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/OpenRA#17152]
For now, openra traverse all the sprite loaders defined in mod.yaml to load a sprite, it is not a good idea, I think we should use extension to find a suitable sprite loader to load a sprite.
We can add extension property to ISpriteLoader, and when load a sprite, check the extension and we will load it
And the loader order defined in the mod.yaml also effect the load result, such as:
if I change `SpriteFormats: ShpTS, TmpTS, ShpTD, PngSheet` to `SpriteFormats: ShpD2, ShpTD, TmpRA, TmpTD, ShpTS, PngSheet`
the the engine notice an error: `xxx.des is not a valid sprite`

**Comment by GraionDilach** [comment]
Are you fully aware that your own YR project uses multiple extensions for SHPs? (default shp, terrains tem, des, urb, ubn, sno, lun and finally sha for mouse?
Are you fully aware that such a case would cause conflict between different SHP parsers?

**Comment by cookgreen** [comment]
> Are you fully aware that your own YR project uses multiple extensions for SHPs? (default shp, terrains tem, des, urb, ubn, sno, lun and finally sha for mouse?
> Are you fully aware that such a case would cause conflict between different SHP parsers?

We can define extension as a string array

**Comment by Mailaender** [comment]
We currently check for magic bytes in the file header which is far more reliable. Example:

https://github.com/OpenRA/OpenRA/blob/c2bc313bf0dde3b2f89b1db76ec4455292572e51/OpenRA.Mods.Cnc/SpriteLoaders/TmpTDLoader.cs#L41-L51
