### ISSUE TITLE
optimization, map mouse button and modifier flags to sdl2 ones

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#17172]
Possible optimization.

Why use custom mouse button and mouse button key modifier flags rather than using the same value as defined in SDL2. This is already done for key codes.

In SdlInput.cs it avoid the need for each mouse movement to have to execute at least 5 comparisons, 5 logical AND operations + 5 logical OR operations, plus possible casts to int. 

`
                static MouseButton MakeButton(byte b)                           
                {                                                               
                        return b == SDL.SDL_BUTTON_LEFT ? MouseButton.Left      
                                : b == SDL.SDL_BUTTON_RIGHT ? MouseButton.Right 
                                : b == SDL.SDL_BUTTON_MIDDLE ? MouseButton.Middle
                                : 0;                                            
                }                                                               
                                                                                
                static Modifiers MakeModifiers(int raw)                         
                {                                                               
                        return ((raw & (int)SDL.SDL_Keymod.KMOD_ALT) != 0 ? Modifiers.Alt : 0)
                                 | ((raw & (int)SDL.SDL_Keymod.KMOD_CTRL) != 0 ? Modifiers.Ctrl : 0)
                                 | ((raw & (int)SDL.SDL_Keymod.KMOD_LGUI) != 0 ? Modifiers.Meta : 0)
                                 | ((raw & (int)SDL.SDL_Keymod.KMOD_RGUI) != 0 ? Modifiers.Meta : 0)
                                 | ((raw & (int)SDL.SDL_Keymod.KMOD_SHIFT) != 0 ? Modifiers.Shift : 0);
                } 
`

A lot of statements to check if the "middle mouse button" + "shift" was pressed.

Executed for each mouse event.

Alternatively you could perhaps use a mapping table, but depending on the values used by SDL it would have to be of size int.

**Comment by abcdefg30** [comment]
Closing as per https://github.com/OpenRA/OpenRA/pull/20138#issuecomment-1228926302.
