### ISSUE TITLE
AI squads frequently end up sitting idle after encountering enemy units

### ISSUE THREAD

**Issue by blackhand1001** [OpenRA/OpenRA#17171]
### Issue Summary
AI squads often end up sitting idle after attacking something. This is especially noticeable if you have two bots playing against each other the whole map will have idle units all over it doing nothing after a while especially if they encountered enemy units on the way to their objective. Adding some kind of loop that checks their status and if they are idle for a certain length to get new orders should solve the issue. 

#### System Information
- **Operating System:** Windows 10
- **OpenRA Version:** Playtest 20190825

**Comment by blackhand1001** [comment]
![OpenRA-2019-10-04T174528463Z](https://user-images.githubusercontent.com/5246342/66228452-764d0300-e6ad-11e9-9c9c-a84d9e8d4e89.png)

Almost all of the allied units in this screenshot are sitting idle.

**Comment by GraionDilach** [comment]
It's probably the latter, coupled with the fact how idle squads are assembled from the closest to center-of-the-base units.

**Comment by reaperrr** [comment]
Another issue might be visibility. Bots no longer ignore their own fog/shroud, so if they kill a target while all other enemies are outside their vision range, they might not continue attacking as squads currently lack some "continue moving in the enemy direction if there are no visible targets" logic.

**Comment by blackhand1001** [comment]
I am not sure its the visibility in this case as I had fog of war off and reveal map turned on. Not sure if those toggles affect the AI though.

**Comment by blackhand1001** [comment]
I don't think this is a visibility issue either. They literally stop doing anything until they get damaged by something. You can drive right past them quite often.

**Comment by blackhand1001** [comment]
This seems to only occur when there are naval units present on the map. I wonder if the squads are being ordered to attack naval units that are out of range and therefore sit idle.

**Comment by abcdefg30** [comment]
That sounds possible, considering #3468, #16478 and #3763.

**Comment by blackhand1001** [comment]
Yeah this appears to be the case. Running two ai against each other on a path beyond with naval disabled and the issue is not occuring yet.

**Comment by RoosterDragon** [comment]
AI attacking units they can't reach was fixed in #20227, so this likely resolves the issue where the ground units were idle due to trying to attack naval units..
