### ISSUE TITLE
Selected subterranean units invisible when submerged 

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#17186]
A selected subterranean unit should not become invisible for the owner and spectators when submerged.

<details>

![Peek 2019-10-06 00-00](https://user-images.githubusercontent.com/37185497/66261390-a7702500-e7cc-11e9-86b7-7dcc29be0ace.gif)

**Comment by pchote** [comment]
Related to #12912.

**Comment by abcdefg30** [comment]
Duplicate of #13163?

**Comment by matjaeck** [comment]
> Duplicate of #13163?

Friendlies in tunnels show the health bar and selection box and. The health bar / cargo pips / group should be available/visible for the player when/always when submerged. I would suggest to use icons only for detected units like GPS does.

**Comment by pchote** [comment]
Closing as reverse-duplicate of #17680.
