### ISSUE TITLE
MoveIntoWorld activity forces map-placed actors to undeploy on game start

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#17184]
Regression from #16938.

Repro case:
1. Place a deployable actor (e.g. Thumper in D2k or tick tank / sensor array / juggernaut in TS) using the map editor
2. Add `DeployState: Deployed` to the init list in `map.yaml` or use #16947 to set the Deployed flag.
3. Start the game.

The `MoveIntoWorld` activity forces the actor to immediately undeploy.

**Comment by abcdefg30** [comment]
If the mobile trait is disabled, #17133 should fix this.

**Comment by tovl** [comment]
The Mobile trait is not disabled, so that won't help directly. But with both #17133 and #17131 we can maybe reuse the `mobile.Immovable` check to disable the `creationActivity.`
