### ISSUE TITLE
Map just freezes in Linux

### ISSUE THREAD

**Issue by 0xA1B2** [OpenRA/OpenRA#17190]
The latest stable version suddenly stops doing nothing under Clear Linux. I have a large 256x256 map with 6 AI bots to watch them, but I tried 2x and in Linux the game screen just freezes after about 30 min. In Windows is continues, same custom map. 

There is no crash log created, as such I cannot report the logs.

**Comment by abcdefg30** [comment]
Sounds like another instance of #17173. Thanks for the report however.
