### ISSUE TITLE
D2k harvesters optically blink and then move to pickup location when dropped

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#17209]
I was able to reproduce this on bleed and prep-1908, devtest-20191006 but not on devtest-20191003.

<details>

![2](https://user-images.githubusercontent.com/37185497/66512047-6cc20180-ead8-11e9-8ab6-7bcc8bbcc28d.gif)

Sometimes they will slide back through cliffs.

**Comment by pchote** [comment]
Almost certainly a regression from #17189.

**Comment by matjaeck** [comment]
[Here](https://imgur.com/a/WxPooLf) are some examples of the behavior depending on when you press the stop hotkey when the unit is waiting to be picked up.

**Comment by abcdefg30** [comment]
Fwiw, I hacked a fix based on pchote's work together here: https://github.com/OpenRA/OpenRA/compare/bleed...abcdefg30:moveFix
However, I'm not sure if that is the way to move forward.
