### ISSUE TITLE
Make Burns conditional and add DeathTypes

### ISSUE THREAD

**Issue by henskelion** [OpenRA/OpenRA#17246]
Adding these features to the Burns trait would open up a lot of possibilities, like making it so flameweapons can cause continuous damage to buildings and trees. I also find the lack of a DeathTypes feature to be a little strange considering so many other traits carry it.

**Comment by reaperrr** [comment]
It's simply one of the oldest traits that hasn't gotten a real refactor yet.
But yeah, it's something that should be done sooner rather than later.

**Comment by GraionDilach** [comment]
Sequences can be inherited now so the trait should be axed for good. `WithIdleOverlay` + negative `SelfHealing` covers _all_ the current usecases and more.
