### ISSUE TITLE
Carryalls can be ordered to pickup submerged units

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#17248]
Reproducible on current bleed but not on release-20190314. See the gif below:

<details>

![carrysubmerge](https://user-images.githubusercontent.com/37185497/67081556-a90bf680-f197-11e9-80f2-910e30c8db89.gif)

**Comment by tovl** [comment]
The subterranean unit glitching out after being dropped off is actually the same issue as #17209 and is resolved by #17221. Carryalls are still able to pick up submerged units on that PR though. This can probably be resolved by using the same interface introduced there for deployed units.
