### ISSUE TITLE
Infantry reinforcement glitch in allies-02

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#17256]
They move to the top left subcell it seems and only then follow their path. Appears to be a regression from  #17235 (no reproduction on 763e6d81092cef28e0aa521ecfb760d4ba422b26). 

<details>

![intoworld](https://user-images.githubusercontent.com/37185497/67148385-5cabde00-f29f-11e9-9984-ca3aee64a5b5.gif)

**Comment by pchote** [comment]
`Reinforcements.Reinforce` is explicitly specifying a `CenterPosition` that is different to its `Location`, so #17235 is behaving as expected by making them move back into the cell grid before continuing.
