### ISSUE TITLE
WithPermanentInjury should be deleted in favor of a GrantConditionOnDamageState + WithInfantryBody combination.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#17261]
Cyborgs in TS/RA2 were in prone state with the prone speed multiplier applied to them when injured. This is not doable in this state.

**Comment by reaperrr** [comment]
IMO `WithPermanentInjury` should just go away. We already have `GrantConditionOnDamageState` and `GrantConditionOnHealth`, and both have a `GrantPermanently` flag.

Basically, I'm inclined to say it should already possible to replicate the original Cyborg behavior entirely via conditions, without WPI.

**Comment by GraionDilach** [comment]
Even better.
