### ISSUE TITLE
Unable to force move helicopters above buildings with LMB orders

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#17262]
Since #16509, it is no longer possible to force-move a helicopter above structures when using classic mouse orders (LMB). Instead, the helicopter will land at a nearby cell. The problem does not exist for RMB orders, because a normal move order will work there (but will select the structure with LMB orders, hence force move needed to be used). This was already noted in the last bullet point of https://github.com/OpenRA/OpenRA/pull/16509#pullrequestreview-239252602, now opening the issue as requested in https://github.com/OpenRA/OpenRA/pull/17099#issuecomment-544294034.

The use case in RA is crashing helicopters into buildings (after enemy units shot them down).

**Comment by pchote** [comment]
The obvious fix here is to make the force-move modifier override selection - we already have plumbing in place to do this for other order types.

A surprising number of people appear to be using LMB orders (side note: we should add this to the sysinfo packet), so I would like to prioritize this and the other LMB issues for Next + 1.

**Comment by matjaeck** [comment]
Force move is already overriding the selection for LMB orders in release-20190314. The problem results from the added force landing feature for VTOLS, which conflicts with the generally required force move for LMB to override the selection.

**Comment by tovl** [comment]
This may be an unpopular opinion, but if it where up to me I would have dropped classic mouse orders a long time ago. It is simply not feasible to have a 'classic' equivalent for every advanced order feature we introduce for normal mouse orders. And demanding that features be cut or neutered because they cannot be used with classic mouse orders will unreasonably hold us back with UI modernization efforts. There is a reason no RTS uses this control scheme anymore, even the newer C&Cs dropped it. It is just not as extensible as the modern control scheme is, so we cannot expect every feature we introduce to be fully utilizable with classic mouse orders.

**Comment by pchote** [comment]
The point was raised in the Discord channel that this specific problem affects both left and right click orders for enemy structures where the default cursor is attack rather than move.

**Comment by tovl** [comment]
> Both C&C3 and RA3 supported left-click orders.

I stand corrected. Although they did drop it by default, which was a break with the way the older games did it. It seems they where struggling with the same issue we are dealing with now regarding the nostalgia factor. I also now realize why they decided to require both mouse buttons be pressed for drag-orders, which I always considered a puzzling ergonomic downgrade over just using right-click drag: It was a concession to be compatible with left-click orders.

> How much more newer do you need?

To be fair, 2007 is hardly recent anymore :wink:

> This specific problem affects both left and right click orders for enemy structures where the default cursor is attack rather than move. 

That is an argument I can get behind, although it doesn't affect my opinion on left-click orders in general.

**Comment by GraionDilach** [comment]
Generals was the first game which added RCO as a default to satisfy and align the game with the Blizzardcraftification direction that game took. Right click orders themselves never had any explicit reason to exist besides to pander to Blizzard's dominance.

**Comment by netnazgul** [comment]
The OP only works with RMB orders when over your own or allied buildings. Simple right click over an enemy building will just attack it. Force move is thus the same for both LMB and RMB orders - aircraft lands at the next free cell.
