### ISSUE TITLE
ProductionParadrop throws an NRE if all exits are occupied at production.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#17270]
On https://github.com/OpenRA/OpenRA/blob/ae34410c8077a45d3dae20419aa63659cf0718a6/OpenRA.Mods.Common/Traits/ProductionParadrop.cs#L90

It's a single-line fix, compared with
https://github.com/OpenRA/OpenRA/blob/ae34410c8077a45d3dae20419aa63659cf0718a6/OpenRA.Mods.Common/Traits/Production.cs#L118

**Comment by abcdefg30** [comment]
I actually already have a branch fixing this, but am still waiting for #17222.
