### ISSUE TITLE
Tonya is nearly worthless without "auto-targeting" & attack-move.

### ISSUE THREAD

**Issue by weabooz** [OpenRA/OpenRA#17271]
Not sure when this change happened? And yes I realize that in the original game you had to manually target. But this isn't the original. 

I have a large "2k" screen and infantry are very small, and a miss click will just tell Tonya to go walk into the enemy like a dumbass. Especially easy to do if the target is moving or theres a group (or a dog running at you.)

Can't imagine what it would be like for someone on a 4K monitor or larger. 

Who even complained about how it was? Please explain the thought process behind this change?

**Comment by GraionDilach** [comment]
There is no unit in the games as "Tonya".

Tanya can autotarget and attack-move. Are you playing missions with higher difficulties? Because it's part of the mission themes there.

**Comment by weabooz** [comment]
No just playing on "normal" and why would you inconsistent unit behavior like this!?

**Comment by GraionDilach** [comment]
Play on easy then. The missions are supposed to be more accurate to the legacy game. Having explicit control is an artificial challenge, sure but adds to the difficulty spike.

**Comment by Punsho** [comment]
You can use pixel doubling to help with the clicking. Rebind the shortcut to `v`or some other easily reachable button and you'll be good to go. Another issue might be that you are using very high mouse sensitivity, in that case you should know that having it high is detrimental to all RTS's

**Comment by weabooz** [comment]
I am aware of pixel doubling but I can still argue that Fog of War wasn't in the original game and that makes it harder too. 

Easy mode is for PUSSIES SO NO.

**Comment by abcdefg30** [comment]
The only difference between easy and normal is that Tanya doesn't autotarget on normal. Easy mode does not impact the health or attack damage of enemies. So imho (and others on IRC agree) this is "won't fix". (The situation might change once we overhaul the difficulty settings of the entire campaign, but that won't happen too soon.)
