### ISSUE TITLE
Infantry are no longer able to dodge crushes

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#17290]
The entering-cell warning appears to be running much later than it should be, leaving infantry insufficient time to move. Regressed somewhere between `playtest-20190825` and `playtest-20191021`.

Bisect suggests that this was introduced by 4f884f98356cf1c7773663e7cd83526d397a18df, and restoring that check does seem to fix this issue. It seems that case *was* important, although its not immediately obvious to me how we get from that to `INotifyCrushed.WarnCrush`.

**Comment by teinarss** [comment]
The solution would be to have it check if its a subcell unit, if I remember
correctly it behaved diffrently when it was a subcell unit than a fullcell,
didn't think it would make any diffrence. I can fill a pr with a fix
tomorrow.
