### ISSUE TITLE
Add missing load/unload animation to RA APC

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#17295]
In the original, a door at the rear of the APC opens on loading/unloading. The door animation is only shown when the APC is facing at NE/NW. I'm not sure if the vehicle prefers that facing when loading/unloading or if it is random. It would be cool if the door animation could be added.

 It's also interesting to see that in the original all passengers exit into the same cell. See the animation below. 

<details>

![apc](https://user-images.githubusercontent.com/37185497/67889671-91e1e700-fb4f-11e9-8aaa-2f66929abb94.gif)

**Comment by obrakmann** [comment]
OpenRA had that in the early days, it was later removed to get rid of the inconsistency. See #2916 and related SRs.

**Comment by matjaeck** [comment]
> OpenRA had that in the early days, it was later removed to get rid of the inconsistency. See #2916 and related PRs.

Right, I haven't thought of the consequences for gameplay when submitting the issue. I think the current behavior (all passengers exit immediately into adjacent cells) makes it easier to use APCs so can agree that removing the animation is a result from a modernization of this game mechanic.

Since the issue is specifically aimed at the RA APC, I'll close it as presumed "won't fix".
