### ISSUE TITLE
Possibly publish a small bugfix release in ~2 months

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#17307]
This release cycle already took too long, and some of the plans for Next+1 may again lead to a rather long and tricky test-bugfix-playtest-bugfix-playtest cycle.

Additionally, some of us devs suffer from both time constraints and mental/motivational exhaustion from the current release cycle, so the next few months are likely to remain slow in terms of progress on bleed.

The catch is that due to the amount of changes the current release cycle introduced, chances are rather high that even those playtests may not be enough to catch everything in time, plus there are already some PRs filed that, while too late/risky to be picked to prep this short before the planned release, still look like good candidates for a relatively quick follow-up release, due to either being bugfixes or having a (presumably) good "low risk, notable benefit" ratio.

This meta issue is meant as a place to collect those candidates until we make the call whether such a stop-gap release would make sense or we'd be better off moving on and just trying to keep Next+1 a bit more focused in scope and and amount of code changes.

Note: To keep scope and risks limited, only PRs that should be backwards-compatible with prep-1908 and are generally low-risk/easy-to-test should be included.

Bugfixes/Misc improvements:
- [x] #17150
- [x] #17166
- [x] #17233
- [x] #17245
- [x] #17353
- [x] #17363 
- [x] #17381

Performance improvements:
- [x] #17397

Mod improvements/bugfixes:
- [x] #16958
- [x] #16966
- [x] #17364
- [x] #17372

AI fixes:
- [x] #17276
- [x] #17298
- [x] #17309
- [x] #17321

**Comment by matjaeck** [comment]
After reconsidering, I think we should try to add #17312 here and make it an AI overhaul themed release.

**Comment by reaperrr** [comment]
@pchote do you think #17222 and/or #17245 could go into prep, or are they too risky in your opinion?

**Comment by pchote** [comment]
#17222 is already there (via #17223). #17245 seems reasonable.

**Comment by tovl** [comment]
I think we should include #16760 and #17365 in the bugfix release as polish/fixup to the selection mode feature introduced in the last release.

**Comment by pchote** [comment]
#17529 means that it is no longer possible to compile any of our stable releases or any SDK-based mods based on them from a clean repository.

We need to get the hotfix, which now has the GeoIP fix, out ASAP.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/releases/tag/release-20200202
