### ISSUE TITLE
Infantry after helicopter shot down on water tile

### ISSUE THREAD

**Issue by Starwolf1111** [OpenRA/OpenRA#17304]
Hi,

I've noticed in the lastest playtest (20191021) that sometimes when an helicopter is shot down over a water tile, the pilot jump out and it result in a paratrooper and then riflemen.
Instead of drowning, it stay where it landed (i.e water tile!).

**Comment by teinarss** [comment]
Duplicate of #17286 and already fixed.

**Comment by matjaeck** [comment]
Thanks for the report and playtesting though!
