### ISSUE TITLE
Please Fix AI Airplane Bug Red-Alert

### ISSUE THREAD

**Issue by Paladin22Shield** [OpenRA/OpenRA#17319]
### Issue Summary
When playing against a Soviet AI player - attacking the computer with submarines the AI will attack with air planes. if the submarine submerges while the plane is coming into range it will crash the game 100% with yaks. havent gotten far enough in a game to find out if the Migs do also 
... ... ...

#### System Information
- **Windows 10** Usually playing on the server with a Mac as the second person
- - Last stable release
- **Red Alert**

#### Additional Information:
- Steps to reproduce
	1. Setup server with AI player set to Soviet Naval 
	2. Start server and build subpen
	3. build submarines and send to attack imminent AI subpen
        4. attack and then wait for yak to approach or force attack out of range of ground forces
        5. when yak almost in range attack then stop
        6. Yak will fly to sub location and attempt to attack submerged sub
        7. Game will crash

**Comment by pchote** [comment]
Have you tried the playtest release? This should be fixed there.

**Comment by Paladin22Shield** [comment]
ok, sorta rushed that report into so it could get checked on the new
release. if it is already fixed, thank you

and thank you and the team for the great game.

**Comment by Smittytron** [comment]
Looks like this was fixed. Otherwise we would have noticed while testing #19036
