### ISSUE TITLE
HERE: OpenRA engine version release-20190314 Date: 2019-11-12 13:40:27Z Operating System: Windows (Microsoft Windows NT 6.2.9200.0) Runtime Version: .NET CLR 4.0.30319.42000 Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.    at OpenRA.Game.Initialize(Arguments args)    at OpenRA.Game.InitializeAndRun(String[] args)    at OpenRA.WindowsLauncher.RunGame(String[] args)

### ISSUE THREAD

**Issue by Seeker990** [OpenRA/OpenRA#17325]
### Issue Summary

... ... ...

#### System Information
- **Operating System:** [e.g. Windows 10, Mac OS 10.12, Ubuntu 16.04, ...]
- **.NET / Mono Version:** [e.g. .NET 4.7.1, Mono 4.6.2, ...]
- **OpenRA Version:** [e.g. release-20180218, playtest-20180208, ...]
- **Mod:** [e.g. Red Alert, Tiberian Dawn, Dune2000, ...]

#### Additional Information:
- Steps to reproduce
	1. Step
	2. Step
	3. ...

- Logs

- OpenRA Replays

- Screenshots & Videos

**Comment by teinarss** [comment]
You will need to provide `graphics.log`.

**Comment by matjaeck** [comment]
Voting for closing as OP fails to meet minimum expectations. Pasting error messages in the title and not providing any further information is not acceptable.
