### ISSUE TITLE
GrantConditionOnDeploy: cannot grant timed condition

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#17331]
This makes it impossible to say, have an Mammoth Tank variant that has an portable Iron curtain device on it. 
GrantExternalConditionPower: can specify an Duration: for the condition it puts on the affected units, so GrantConditionOnDeploy: probably should able to do that too.

**Comment by pchote** [comment]
Related: #15688.

**Comment by GraionDilach** [comment]
AS have an implementation for years. Including conditional support.

**Comment by MlemandPurrs** [comment]
Ive taken the GrantTimedConditionOnDeploy from CA mod seems to be working seamlessly.

**Comment by PunkPun** [comment]
Related #12542

**Comment by abcdefg30** [comment]
Should be closed by #20824.
