### ISSUE TITLE
JamsMissiles: is not conditional

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#17332]
This makes it impossible to have it continue functioning when loaded into an Naval transport. 
Give mrj: mrj-inside under an PassengerConditions: within Cargo: 
then put JamsMissiles: with an RequiresCondition: mrj-inside under it on the Naval transport.
It wont work as JamsMissiles: isnt conditional.

**Comment by MustaphaTR** [comment]
It is conditional on upstream. I guess you were working on lastest release: https://github.com/OpenRA/OpenRA/pull/16225
