### ISSUE TITLE
Actors cannot have multiple Cargo: traits

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#17330]
This makes it not possible to have, say an Transport that carries Infantry and Vehicles seperately but at the same time. Or an APC that doubles its capacity upon reaching Elite rank. Or an APC that gets its carry capacity reduced when its critically damaged. It doesnt work even if you configure it such that only one Cargo: with the same Types: of multiple given Cargo@: will be active one at a time as this doesnt accepts RequiredCondition:
Probably should able to become useable as such.

**Comment by GraionDilach** [comment]
Related to #14184.
