### ISSUE TITLE
Opt-out option/setting for GeoIP

### ISSUE THREAD

**Issue by abmyii** [OpenRA/OpenRA#17343]
Not sure why this hasn't been done already to preserve anonymity. It doesn't make a difference at all to the game.

**Comment by matjaeck** [comment]
Related to the discussion in #15647.

**Comment by pchote** [comment]
GeoIP is resolved using a local database shipped with the game files, it doesn't do any online queries.

**Comment by abmyii** [comment]
I know that, but even so it is a bit intrusive. I think a hash would be incredibly easy to implement, and would provide all necessary functions.

**Comment by abmyii** [comment]
In fact I don't the IP should be shown under any condition. The country one can be optional. Thoughts?

**Comment by pchote** [comment]
We originally tried to remove the IP display as part of the player authentication feature. We restored it after wide complaints from players, who felt that they lost the only tool they had available to identify and block trolls.

**Comment by abmyii** [comment]
Hashes would be identical too, right?

**Comment by abmyii** [comment]
Slightly more difficult but plausible (and a better solution, perhaps) is to generate 2/3 random words:
https://what3words.com/

Just throwing that idea in.

**Comment by pchote** [comment]
Hashes would change as soon as the player reboots their router / forces a dhcp lease refresh. I know that players used to maintain a list of the IP ranges used by the worst abusers so they could be avoided.

**Comment by abmyii** [comment]
> Hashes would change as soon as the player reboots their router / forces a dhcp lease refresh.
How if it is produced from the IP? If the IP changes then I don't see how that is relevant - you couldn't identify them anyway.

**Comment by matjaeck** [comment]
Although i generally support the idea of pseudonymization by hashing  - wouldn't that need to be quite a long hash to avoid duplicates and provide a reasonable level of encryption?

**Comment by abmyii** [comment]
It can be reveresed, but really if right now it is plainly shown then *any* level of abstracting will be good. As for collisions then that probably wouldn't be a problem with > ~8 bytes (no expert in the least).

**Comment by pchote** [comment]
> If the IP changes then I don't see how that is relevant

IPs from each ISP tend to be localized within ranges, and its these ranges that players were using to identify abusive players.

**Comment by abmyii** [comment]
So I am assuming first two parts (xxx.xxx) remain the same? If so then each part can be hashed and then identical parts will be easy to recognise. It will be easier to reverse, but the main focus is to not show it plainly.

BTW I am not familiar with how the servers are run, so when trying to block a player, can't they see the actual IP/range in the server logs? If so then it is not an issue as this is only meant for the player's label in the lobby.

**Comment by matjaeck** [comment]
>  can't they see the actual IP/range in the server logs? If so then it is not an issue

This is actually the only real issue when looking at it from a privacy law standpoint. It surely is within the legitimate interest of the controller (the server owner) to temporarily store and use the IP-addresses to offer and protect their services, however they formally would need to inform their users when entering the lobby about how personal data is processed. Showing the IP-address in the lobby is something you probably can do with the reasoning to enable other players to take legal action against harassment.

**Comment by abmyii** [comment]
> This is actually the only real issue when looking at it from a privacy law standpoint. It surely is within the legitimate interest of the controller (the server owner) to temporarily store and use the IP-addresses to offer and protect their services, however they formally would need to inform their users when entering the lobby about how personal data is processed.

To me this is a given - whenever I connect to the internet I *know* that servers are going to be able to see my (external) IP. What I don't agree with however, is anyone else being able to see it (in this case the other players).

> Showing the IP-address in the lobby is something you probably can do with the reasoning to enable other players to take legal action against harassment.

I'd don't quite follow you, but if you mean that the player's IP is used when banning (is it? - I don't know) then what I am postulating is that the 8-bit hash would be used instead to refer to the player, rather than the IP.

**Comment by pchote** [comment]
Remember that server hosts typically don't do any specific management of their servers (although some hosts do make an exception). Kicking and temporary bans are made by the first player to join the server, who becomes the temporary admin.

**Comment by matjaeck** [comment]
My consideration was that the IP would be sufficient information for the ISP to find out the real person behind it. And that exposing it within the lobby enables other players to take legal action against somebody, which wouldn't be possible otherwise, as IPs are usually not stored by the server owner afaik.

**Comment by abmyii** [comment]
Yes, I thought so. In that case an IP-range ban isn't even possible, is it? If so, it wouldn't matter what identifier (IP or hash) was used.

**Comment by abmyii** [comment]
> My consideration was that the IP would be sufficient information for the ISP to find out the real person behind it. And that exposing it within the lobby enables other players to take legal action against somebody, which wouldn't be possible otherwise, as IPs are usually not stored by the server owner afaik.

Exactly, that and many other reasons for not showing it publicly. Cannot really do much about server config/logs, though I don't have any idea about the laws regarding it.

**Comment by pchote** [comment]
As above - my understanding is that the community used to (and maybe still does) keep a list of ip ranges for the troublemakers and use the ip exposed in the tooltip to recognise and kick them.

**Comment by matjaeck** [comment]
> Exactly, that and many other reasons for not showing it publicly. 

My comment was meant as an argument for why it *is* in the interest of players that IPs are exposed.

**Comment by abmyii** [comment]
> keep a list of ip ranges for the troublemakers and use the ip exposed in the tooltip to recognise and kick them.

This can be converted to a list of hashes and then serve the same functionality.

> My comment was meant as an argument for why it is in the interest of players that IPs are exposed.
Sorry, must have misread your comment. Why would legal action ever need to be taken (has it happened previously? I don't think this is common at all in internet gaming). Also the IP hash can be reversed, and the logs *do* contain the IPs.

**Comment by abmyii** [comment]
I understand that there are many *good* reasons for keeping IPs visible, but I really do think that obscuring them (in an ideal fashion) is paramount to any issues along the way.

**Comment by praetp** [comment]
Why is the country not shown for registered players ? I don't mind my country would be shown but I don't want my IP address to be shown. 
Trouble makers can always use a VPN - it is hard to stop them.

**Comment by abmyii** [comment]
> Why is the country not shown for registered players ? I don't mind my country would be shown but I don't want my IP address to be shown.

Yes, I don't really understand the rational behind not showing registered players' country - I guess it is because they are easier to block (account as reference).

**Comment by abmyii** [comment]
> As above - my understanding is that the community used to (and maybe still does) keep a list of ip ranges for the troublemakers and use the ip exposed in the tooltip to recognise and kick them.

Wait, are they referring to the list to identify troublemakers *by eye* or are they adding it to some server list?

**Comment by pchote** [comment]
Yes, by eye. This is the only mechanism players have to identify trolls (and we have had several episodes in the past with surprisingly vicious people trying to hurt the MP scene), so they make do with what they can.

**Comment by abmyii** [comment]
The hashes are quite easy to read already, and can be formatted to make them even easier. Hashing the last octet isn't a bad idea though.

**Comment by abmyii** [comment]
How about hashing each octet? That way, even if the IP changes, most of the hash will be the same.

**Comment by abmyii** [comment]
So, for example, with 127.0.0.1:
'9b34f1ce.48454cb2.48454cb2.b6ecc8b2'
And with 127.0.0.2:
'9b34f1ce.48454cb2.48454cb2.b6ecc8b2'

**Comment by pchote** [comment]
IMO hashing each octet is worse than nothing because it provides an illusion of security while being (a) trivially reversible and (b) adding code overhead.

**Comment by abmyii** [comment]
With regards to ISP-provided IP ranges, I know very little about the subject, but doesn't the last octet change *only* (else how would anyone recognise it)? Either way the hash would be made up of two sub-hashes; one from the static portion and one from the dynamic portion.

Also, I can't see many people (even vicious ones) restarting their router simply to re-join a server. And restarting hardly guarantees a change in IP:

> You'll read most everywhere that a dynamic IP address can change "at any time." True, but not likely. The fact is, even if you have a dynamic IP address it's possible that it won't change for months on end.
(https://whatismyipaddress.com/dynamic-static)

Anyway, once they rejoin with a new IP + hash, the hash will just be blocked once somebody realises they are a troublemaker - just the same as on an IP.

*Side note, there is also the `intdigest` function, which for `127.0.0.1` provides this:
`2426094911`
Which could be formatted as:
`242.609.4911`*

**Comment by abmyii** [comment]
Oh, didn't think of the most obvious solution - rather than "hashing" (i.e. make a hash of the) last three octets, they can be hash using `#`. I think now that we've been on different pages the whole time.

**Comment by abmyii** [comment]
Can we please agree on at least a basic amount of abstraction - even just the last three digits?

**Comment by matjaeck** [comment]
> Why is the country not shown for registered players ?

@praetp See the discussion in #15448.

**Comment by abmyii** [comment]
The conclusion of issue/discussion #15448 was this:
> Seems that the only safe option is to keep the status quo, hiding the geolocation for all registered users.
 
Why not the same for non-registered users? I understand that it is easier to make "connections" with a registered player, but I don't feel comfortable with mine being advertised either. Does it serve any particular purpose at all?

**Comment by pchote** [comment]
The same reason as the IP - it provides a means to reduce the anonymity of anonymous players.

**Comment by abmyii** [comment]
Why both?

**Comment by matjaeck** [comment]
There seems to be a general misunderstanding here -- OpenRA servers are not operating in the dark web or anything. While I share your privacy concerns to a certain degree, there is no obligation to enable players in multiplayer games to stay completely anonymous. In fact, I believe this would be counterproductive for the community. Displaying the country does not at all conflict with user privacy.

**Comment by abmyii** [comment]
> There seems to be a general misunderstanding here -- OpenRA servers are not operating in the dark web or anything. While I share your privacy concerns to a certain degree, there is no obligation to enable players in multiplayer games to stay completely anonymous. In fact, I believe this would be counterproductive for the community. Displaying the country does not at all conflict with user privacy.

No you are misunderstanding my question. I was wondering why the conclusion of issue/discussion #15448 was:

> Seems that the only safe option is to keep the status quo, hiding the geolocation for all registered users.

Which implies it is unsafe to reveal registered players' location, but yet not unsafe for unregistered players. Personally I err on the side of it being unnecessary for anyone's location to be shown (or at least be able to enable/disable it), regardless of "dark net" or not - it's a matter of personal choice. As for the IP then I think that is even more intrusive, and I think that should definitely be pseudonymization, if only by hiding the last octet.

**Comment by matjaeck** [comment]
> Which implies it is unsafe to reveal registered players' location

It doesn't. We introduced the authentication feature and more or less accidentally dropped the country information for registered players unless I missed something. The issue you are commenting on was about re-introducing this feature, but due to the objections in the issue, it was decided to keep everything as it is. To avoid trouble, and not because it was considered "unsafe" in any way for players.

Showing the country may be unnecessary in your opinion, but it does not do anything bad, does it? I find it useful since it indicates what language a player speaks and what timezone they live in. It also indicates whether a server location is a good choice - if I see that only players from Europe are on a US server, I can suggest to switch to a EU server so everyone has a better connection. The issue I can understand is that people said they would get preemptively banned because some people assumed their connection was bad (which often is not the reason for ingame-lag). Registering an account solves that problem and I could get behind adding an option for displaying it in the player profile, but see no gain in doing so for anonymous players.
 
You are technically right that the shortened IP alone is probably sufficient for identifying players. But in reality, people remember some digits plus "person from country X". It's just another layer of information that is easier to remember.

You so far have given little information about why it is a problem to show the country information.

**Comment by abmyii** [comment]
anjew175 Made this point:
> I agree with Graion, people are kicked from games because of location in some cases. Id rather not advertise my location, personally

Which others agreed with:
> Ok. This is a reasonable concern. What is the risk of these same admins kicking anyone with an "Anonymous location" label?

So it was deemed a concern.

> Showing the country may be unnecessary in your opinion, but it does not do anything bad, does it?

It can. I've only played on servers once in a blue moon and yet I saw a player from Canada getting some flak for apparently no reason.

> I find it useful since it indicates what language a player speaks and what timezone they live in. It also indicates whether a server location is a good choice - if I see that only players from Europe are on a US server, I can suggest to switch to a EU server so everyone has a better connection.

I understand, but most of these aren't critical - even the EU/US servers. Besides, I wouldn't be surprised if most players don't bother to turn off their location - it will be convenient for the few that do mind and will not harm anyone else.

> The issue I can understand is that people said they would get preemptively banned because some people assumed their connection was bad (which often is not the reason for ingame-lag). Registering an account solves that problem and I could get behind adding an option for displaying it in the player profile, but see no gain in doing so for anonymous players.

Why not? The same situations would occur regardless of if you are registered or not, and as I have mentioned above, they do occur.

> You are technically right that the shortened IP alone is probably sufficient for identifying players. But in reality, people remember some digits plus "person from country X". It's just another layer of information that is easier to remember.

People are more likely to remember the beginning and end of an item (https://en.wikipedia.org/wiki/Serial-position_effect), so perhaps the middle part (one or both) should be hashed.

> You so far have given little information about why it is a problem to show the country information.

Above.

One other consideration is that even if we decide that it is best to keep IP fully visible then we could remove country location as most people won't bother to look-up the location.

I feel that the most realistic (not my favorite) solution, considering the problems, is for the IP to be abstracted slightly and the country to be shown. That way connections can be made, but without locating with so much accuracy.

Sorry for the long comment - just trying to explain my views.

**Comment by matjaeck** [comment]
> I feel that the most realistic (not my favorite) solution, considering the problems, is for the IP to be abstracted slightly and the country to be shown.

Agreed, and thanks for taking the time to explain it. What you say is understandable, but there are other reasonable motivations that might conflict with your view. So we often have to make compromises.

**Comment by abmyii** [comment]
> Agreed, and thanks for taking the time to explain it. What you say is understandable, but there are other reasonable motivations that might conflict with your view. So we often have to make compromises.

Thanks for taking the time to read it! Could we try my last suggestion? I think it is a reasonable compromise between both views. Please explain if you don't agree.

**Comment by abmyii** [comment]
Just a quick case-in-point, got a bit of flak myself for something happening where I am - obviously due to my location being visible. I think that, in a way, showing the country is just as much - if not more - problematic than the IP (though not as intrusive).
TBH I found the situation interesting because we discussed it a bit after, but others may have found that stressful or upsetting.

**Comment by abmyii** [comment]
With regards to the country I've had an interesting idea which might be the perfect compromise - why not generalise to continent? That way you can get an idea of where a player is from (and which server they should be on if necessary), without being too intrusive. Thoughts?

**Comment by Mailaender** [comment]
Country level is anonymous enough.
