### ISSUE TITLE
Clean up PR queue

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#17351]
The PR queue is a bit too long and messy for my taste.

In my opinion we should try to clean it up a bit before we file more PRs for Next+1.

To do that in a slightly more focused fashion, this ticket is meant to list the lowest-hanging fruits for getting PRs merged soonish as well as discussion on which PRs could be closed (either temporarily or permanently) due to lack of progress or too many dependencies.

PRs that (in my opinion) are fairly trivial and don't necessarily need a +2:
~#17338~
~#17303~
~#17255~
~#16815~

PRs that may require a bit more reviewing/testing than the above, but nothing too troublesome and/or don't affect the shipping mods:
#17216
~#17264~
~#17321~
~#17224~
~#17136~
#17102
~#16793~

PRs that already have a +1 and (currently) no unadressed comments/bugs (or miss a label):
~#17183~
~#17222~
~#17076~
~#16977~
~#16696~ &rarr; future milestone

PRs that should get some priority treatment due to being dependencies for other PRs:
~#16999~
#17014
~#16834~ &rarr; #17514
~#16696~ &rarr; future milestone

Either take over and finish, or close:
~#16672~
~#16701~ &rarr; ~#17625~

Potentially close and move to Future milestone:
~#16396~ &rarr; future milestone
~#16390~ &rarr; future milestone
~#16186~ &rarr; future milestone
~#16151~ &rarr; future milestone

**Comment by dragunoff** [comment]
#16760 seems like a straight-forward one too

**Comment by tovl** [comment]
I'll add my vote to closing those last four PRs. They have not been worked on for a very long time and have grown quite stale in the mean time. Also, the authors have not responded to earlier requests for status updates and three out of the four where by new contributors who have sadly not been involved since.

**Comment by pchote** [comment]
PR queue has now been cleaned wrt the milestone. We are now just waiting on reviews.
