### ISSUE TITLE
Sound issue when loading savegames in-game

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#17359]
From the website comments:
"If in-game you load a saved game too many times(about 3 times), unit sound stops working, I gotta return to main menu and load from there to fix the issue."

**Comment by matjaeck** [comment]
http://www.openra.net/news/release-20191117/#comment-4694794568

He also noted that

> Another issue is while I'm playing, music suddenly stops working. I gotta restart it on the music menu.

I tried to reproduce the issue but without success so far.

**Comment by GraionDilach** [comment]
The music issue is #14153.

**Comment by pchote** [comment]
I also can't reproduce this, so without any extra information to suggest otherwise I expect that this is our standard Windows-OpenAL heisenbug.

There's nothing to action on, so removing from the milestone.

**Comment by vollkorn1982** [comment]
I have the same issue on Ubuntu 18.04, which leads me to believe this is not related to the OS. I'm a former software dev and could provide some debugging info, if someone lets me know what is of interest.

**Comment by pchote** [comment]
@abcdefg30 have you found a repro case so we can try to fix this?

**Comment by abcdefg30** [comment]
Yes, you need to open the menu on a timing when you lose a mission (just press esc once you hear "mission failed"). The manually opened menu will mute the world sounds, but the game over logic opens it again somehow and then plays the fmv. This causes `cachedDisableWorldSounds` being set to `true` and thus muting all sounds when leaving the menu after loading: https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Widgets/Logic/Ingame/MenuButtonsChromeLogic.cs#L106

**Comment by abcdefg30** [comment]
https://github.com/OpenRA/OpenRA/blob/006a87692a2d4ae5d3e5ea3c55ea1a41d81b0378/OpenRA.Mods.Common/Widgets/Logic/Ingame/LoadIngamePlayerOrObserverUILogic.cs#L78 will likely be the problem here, I'll try to make that check if the menu is already open.

**Comment by abcdefg30** [comment]
The much bigger issue here seems to be that `UI.CloseWindow` does not trigger `onExit`!
