### ISSUE TITLE
What can we do on this project?

### ISSUE THREAD

**Issue by ayodele-olufemi** [OpenRA/OpenRA#17389]
### Please have us do something
Hi Admin, 
I belong in a group of 2 students and currently taking a software testing class. I chose to work on this project because I felt it would be fun and --easy, but I guess I was wrong. 

#### Task: 
1. Find and report bugs and/or
2. Run/Add tests. 

#### Problem: 
We've since been playing this game, but we can't find bugs.  Apparently, the game is a lot more advanced that we initially thought. Thanks to all the wonderful contributors. We've been able to build the game and run the tests, but that hasn't gotten us much points to pass. Its almost getting to the end of the semester and we can't change projects at this point.

The professor have instead asked us to talk to Admin and see if they can have us do anything. Please point us at what we could work on. 

Thank you. 
#### PS: The was the only way I could think of in order to be able to contact Admin.

**Comment by abcdefg30** [comment]
Hello and thanks for your interest in the project.
Sadly, I don't think we have any open task involving traditional (unit) testing at the moment.

An interesting idea might be having a look at "HeuristicWeightPercentage" of our pathfinder: https://github.com/OpenRA/OpenRA/blob/04912ea996851bdb6aa0a2093487d3181206a29c/OpenRA.Mods.Common/Pathfinder/PathSearch.cs#L69-L76
The linked comment already gives an explanation of what the property does (basically if you set it higher the finder is faster, but gives less optimal paths). I also suggest looking at https://github.com/OpenRA/OpenRA/pull/17334#issuecomment-554661724.
What you could do here is:
1) Design a few test cases for unit pathfinding (perhaps on a custom map, and move units using a Lua script or by hand)
2) Look at how different heuristic percentages do on those testcases (optimal path and pathfinding-time wise)
3) Use the gathered data to find what an optimal value for this percentage would be


I think this would certainly give you something to write about.

Another idea would be benchmark-testing @teinarss new HPA pathfinder (I think the most recent version is at https://github.com/teinarss/OpenRA/tree/hpa2), but afaik he's not 100% finished yet, so this might be a bad idea.

**Comment by Mailaender** [comment]
You will notice that this game has surprisingly few unit tests. However it has an interesting interface called `ILintPass` which checks the mods for consistency. https://github.com/OpenRA/OpenRA/blob/a74235bdbc8f5e3dac31348582b8012d60585eee/OpenRA.Mods.Common/UtilityCommands/CheckYaml.cs#L63-L78 It is very important for automatic QA and grew a lot in size. Performance is terrible though #13937 and the system is not so smart when throwing. #15114 #6975 There is also some debate on a refactor. #13533 You could also think of new checks for maps and mods that help spot errors.
