### ISSUE TITLE
Unable to build near infiltrated construction yard of enemy

### ISSUE THREAD

**Issue by Dennis-Q** [OpenRA/OpenRA#17390]
### Issue Summary
After taking over the enemies construction yard you should be able to build building near it. This was not possible during a multiplayer game I played with a friend. I was 'Germany', while he was playing as 'Ukraine'. After taking over the construction yard with an engineer, I was not able to build a Tesla Coil near it but this was not possible. 

#### System Information
- **Operating System:** Windows 10
- **.NET / Mono Version:** .NET (not sure which version, don't think it's relevant)
- **OpenRA Version:** release-20191117
- **Mod:** Red Alert

#### Additional Information:
- Steps to reproduce
	1. Start multiplayer over the network, together with one other player: 
	2. Build Power Plant + Barracks
	3. Build Engineer
	4. Send engineer to enemy Construction Yard & take over. 
	5. Build Tesla Coil & try to place it near the taken construction yard.

- Logs
No useful information for this issue and/or overwritten.

- OpenRA Replays
11.50 takeover by enemy construction yard using two engineers. Captured around 12:05. Then Tesla Coil was build but I was not able to place it. Tried this around 12.45, just when the engineer of the enemy tries to take it back, but was not possible. You can not see this action in the reply.
[OpenRA-2019-11-27T072141Z.zip](https://github.com/OpenRA/OpenRA/files/3896170/OpenRA-2019-11-27T072141Z.zip)

- Screenshots & Videos
None available

**Comment by Dennis-Q** [comment]
We are not sure, but maybe it is a feature / works as designed. As soon as the engineer from the enemy starts to take back the construction yard, it seems that building constructions around the construction yard being taken back are not possible anymore...

**Comment by abcdefg30** [comment]
Yes, you can't place structures near a construction yard that is being captured. So it only didn't work for you when an enemy captures the conyard? Then it is not a bug indeed.

**Comment by Smittytron** [comment]
> We are not sure, but maybe it is a feature / works as designed. As soon as the engineer from the enemy starts to take back the construction yard, it seems that building constructions around the construction yard being taken back are not possible anymore...

> Yes, you can't place structures near a construction yard that is being captured. So it only didn't work for you when an enemy captures the conyard? Then it is not a bug indeed.

Yep, that's working as intended.
