### ISSUE TITLE
Contrails with a ContrailLength less than 6 are not rendered.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#17394]
This is undocumented.

The sole following line
https://github.com/OpenRA/OpenRA/blob/dad21fe8792cc5d50115ff9f41094cfbe34ced9d/OpenRA.Mods.Common/Graphics/ContrailRenderable.cs#L61 implies that contrails must have a length of 5 atleast however even 5 breaks thenafter due to the math within the `Renderable`.

**Comment by Mailaender** [comment]
Resolved by  https://github.com/OpenRA/OpenRA/pull/19089.
