### ISSUE TITLE
Game freezes on launch on Ubuntu

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#17391]
### Issue Summary
Building and launching the bleed branch on Ubuntu causes the game to freeze - nothing is rendered and the window becomes unresponsive. After terminating the program the crash window appears but no logs are created.

#### System Information
- **Operating System:** Ubuntu 19.04
- **GPU** 4 × AMD A10-7300 Radeon R6
- **.NET / Mono Version:** mono 6.4.0.198
- **OpenRA Version:** bleed

Bisecting reveals 36c48e1785efc792a789313379383681e78e70e7 as the culprit. So this has got something to do with "Using a glDebugMessageCallback instead of glGetError". What can I do to help track down the problem?

Ping @vesuvian

**Comment by GraionDilach** [comment]
Check your GPU driver. WildfireGames claim that should be functional on that system (Ctrl-F on R6 at https://feedback.wildfiregames.com/report/opengl/feature/GL_KHR_debug) but it bases that on a very small sample pool.

**Comment by dragunoff** [comment]
`glxinfo -B` gives me this:
```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD KAVERI (DRM 2.50.0, 5.0.0-20-generic, LLVM 8.0.0) (0x130a)
    Version: 19.0.2
    Accelerated: yes
    Video memory: 1024MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 911 MB, largest block: 911 MB
    VBO free aux. memory - total: 2026 MB, largest block: 2026 MB
    Texture free memory - total: 911 MB, largest block: 911 MB
    Texture free aux. memory - total: 2026 MB, largest block: 2026 MB
    Renderbuffer free memory - total: 911 MB, largest block: 911 MB
    Renderbuffer free aux. memory - total: 2026 MB, largest block: 2026 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 1024 MB
    Total available memory: 3067 MB
    Currently available dedicated video memory: 911 MB
OpenGL vendor string: X.Org
OpenGL renderer string: AMD KAVERI (DRM 2.50.0, 5.0.0-20-generic, LLVM 8.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.0.2
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.0.2
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.0.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by GraionDilach** [comment]
You can try updating mesa - it's on 19.2.6 now.

**Comment by dragunoff** [comment]
Some developments:
- Tried on a fresh Ubuntu 19.10 installation - got the same crash
- Commenting out the call to `glDebugMessageCallback` lets me run the game
- Running w/ `Graphics.PreferGLES=true` makes no difference
- Running [pchote's release-20191117-renderertest1](https://github.com/pchote/OpenRA/releases/tag/release-20191117-renderertest1) produced this `graphics.log`: https://pastebin.com/u3dxgu1r

<details>

```

High - GL Debug Shader Compiler Output: Error - 0:88(6): error: could not implicitly convert operands to relational operator
  at OpenRA.Platforms.Default.OpenGL.BuildErrorText (System.Int32 source, System.Int32 type, System.Int32 severity, System.Text.StringBuilder message) [0x00000] in <0995a5fdaeef400abfafc330f637d74e>:0
  at OpenRA.Platforms.Default.OpenGL.DebugMessageHandler (System.Int32 source, System.Int32 type, System.UInt32 id, System.Int32 severity, System.Int32 length, System.Text.StringBuilder message, System.IntPtr userparam) [0x00000] in <0995a5fdaeef400abfafc330f637d74e>:0
  at System.Object.wrapper_native_0x7f418a80e7a0 (System.UInt32 ) [0x00000] in <285579f54af44a2ca048dad6be20e190>:0
  at OpenRA.Platforms.Default.Shader.CompileShaderObject (System.Int32 type, System.String name) [0x00000] in <0995a5fdaeef400abfafc330f637d74e>:0
  at OpenRA.Platforms.Default.Shader..ctor (System.String name) [0x00000] in <0995a5fdaeef400abfafc330f637d74e>:0
  at OpenRA.Platforms.Default.Sdl2GraphicsContext.CreateShader (System.String name) [0x00000] in <0995a5fdaeef400abfafc330f637d74e>:0
  at OpenRA.Platforms.Default.ThreadedGraphicsContext+<>c__DisplayClass23_0.<RenderThread>b__9 (System.Object name) [0x00000] in <0995a5fdaeef400abfafc330f637d74e>:0
  at OpenRA.Platforms.Default.ThreadedGraphicsContext+Message.Execute () [0x00000] in <0995a5fdaeef400abfafc330f637d74e>:0
  at OpenRA.Platforms.Default.ThreadedGraphicsContext.RenderThread (System.Object contextObject) [0x00000] in <0995a5fdaeef400abfafc330f637d74e>:0
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00000] in <285579f54af44a2ca048dad6be20e190>:0
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <285579f54af44a2ca048dad6be20e190>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <285579f54af44a2ca048dad6be20e190>:0
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x00000] in <285579f54af44a2ca048dad6be20e190>:0
  at System.Threading.ThreadHelper.ThreadStart (System.Object obj) [0x00000] in <285579f54af44a2ca048dad6be20e190>:0
 
OpenGL Information:
Vendor: X.Org
Renderer: AMD KAVERI (DRM 2.50.0, 5.3.0-24-generic, LLVM 9.0.0)
GL Version: OpenGL ES 3.2 Mesa 19.2.1
Shader Version: OpenGL ES GLSL ES 3.20
[...]

```

</details>

**Comment by pchote** [comment]
@dragunoff did you try launching all mods? If https://github.com/OpenRA/OpenRA/issues/17528#issuecomment-573862422 is the same as this issue it implies that you may be able to launch TD without problem.

**Comment by dragunoff** [comment]
@pchote Yes, I tried all mods and got the same result. I tried your rendertests again but I'm not even getting a graphics.log anymore so the one linked above may be related to something else... 

Output of `glxinfo -B`:

<details>

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD KAVERI (DRM 2.50.0, 5.3.0-24-generic, LLVM 9.0.0) (0x130a)
    Version: 19.2.1
    Accelerated: yes
    Video memory: 1024MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 992 MB, largest block: 992 MB
    VBO free aux. memory - total: 1936 MB, largest block: 1936 MB
    Texture free memory - total: 992 MB, largest block: 992 MB
    Texture free aux. memory - total: 1936 MB, largest block: 1936 MB
    Renderbuffer free memory - total: 992 MB, largest block: 992 MB
    Renderbuffer free aux. memory - total: 1936 MB, largest block: 1936 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 1024 MB
    Total available memory: 3067 MB
    Currently available dedicated video memory: 992 MB
OpenGL vendor string: X.Org
OpenGL renderer string: AMD KAVERI (DRM 2.50.0, 5.3.0-24-generic, LLVM 9.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.2.1
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.2.1
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.2.1
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

</details>

**Comment by pchote** [comment]
#17603 has been merged, but keeping this open and on the milestone until we can find a proper resolution to the issue.

The current plan (discussed in IRC) is to release the first playtest as-is, but toggle `Graphics.DisableGLDebugMessageCallback` to true by default before the release unless we can find a more specific set of conditions to automatically disable the feature on.

**Comment by ripper81** [comment]
I can confirm the crash and complete desktopfreeze on my system.

Systemspecs:
CPU: AMD Ryzen 3600
RAM: 16 GB 
GPU: AMD Radeon Rx 590
Driver: AMDGPU + MESA 19.3.3
OS: Kubuntu 19.10 64bit

**Comment by pchote** [comment]
@ripper81 can you please post the output of `glxinfo -B`?

**Comment by ripper81** [comment]
> @ripper81 can you please post the output of `glxinfo -B`?
```
heiko@pc-heiko:~$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: Radeon RX 590 Series (POLARIS10, DRM 3.36.0, 5.5.2-050502-generic, LLVM 9.0.1) (0x67df)
    Version: 19.3.3
    Accelerated: yes
    Video memory: 8192MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 7717 MB, largest block: 7717 MB
    VBO free aux. memory - total: 8059 MB, largest block: 8059 MB
    Texture free memory - total: 7717 MB, largest block: 7717 MB
    Texture free aux. memory - total: 8059 MB, largest block: 8059 MB
    Renderbuffer free memory - total: 7717 MB, largest block: 7717 MB
    Renderbuffer free aux. memory - total: 8059 MB, largest block: 8059 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8192 MB
    Total available memory: 16384 MB
    Currently available dedicated video memory: 7717 MB
OpenGL vendor string: X.Org
OpenGL renderer string: Radeon RX 590 Series (POLARIS10, DRM 3.36.0, 5.5.2-050502-generic, LLVM 9.0.1)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.3.3 - kisak-mesa PPA
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.3.3 - kisak-mesa PPA
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.3.3 - kisak-mesa PPA
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by w-wallner** [comment]
I can confirm the game freeze.
But for me it was not a complete system freeze, I could end the game by sending the TERM signal via the KDE task manager and return to my desktop.

By adding **Graphics.DisableGLDebugMessageCallback=true** I can start the game.

**Systemspecs:**
CPU: Intel i5-7600K CPU @ 3.80GHz
RAM: 16 GB
GPU: AMD Radeon RX 580
Driver: AMDGPU + MESA 19.2.8
OS: Kubuntu 19.10 64bit

$> glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: Radeon RX 580 Series (POLARIS10, DRM 3.33.0, 5.3.0-29-generic, LLVM 9.0.0) (0x67df)
    Version: 19.2.8
    Accelerated: yes
    Video memory: 4096MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 4.5
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 3826 MB, largest block: 3826 MB
    VBO free aux. memory - total: 4025 MB, largest block: 4025 MB
    Texture free memory - total: 3826 MB, largest block: 3826 MB
    Texture free aux. memory - total: 4025 MB, largest block: 4025 MB
    Renderbuffer free memory - total: 3826 MB, largest block: 3826 MB
    Renderbuffer free aux. memory - total: 4025 MB, largest block: 4025 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 4096 MB
    Total available memory: 8192 MB
    Currently available dedicated video memory: 3826 MB
OpenGL vendor string: X.Org
OpenGL renderer string: Radeon RX 580 Series (POLARIS10, DRM 3.33.0, 5.3.0-29-generic, LLVM 9.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.2.8
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.2.8
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
