### ISSUE TITLE
Planes don't turn towards their target if it is in weapon range

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#17413]
## This release
![RegressedMiG](https://user-images.githubusercontent.com/37534529/69955875-5bf5a100-1507-11ea-9021-2e8b07059446.gif) 
## Last release
![NormalMiG](https://user-images.githubusercontent.com/37534529/69955869-59934700-1507-11ea-82c3-d7ab8d1c64bc.gif)

When a target in range is selected planes instead of turning towards it try their hardest to complete the strafe. It makes microing aircraft significantly harder as you have to manually turn them towards their target for them to actually shoot. We had dozens of reports on Discord about how unresponsive MiGs are, it is a major regression and needs to be addressed in the hotfix

**Comment by penev92** [comment]
Modern planes woudn't need to turn (depending on the type of weapon), so I suggest making this optional at the mod level.

**Comment by pchote** [comment]
Modern planes *probably* have the ability to fire their weapons while facing in a different direction to the target to go with that ;)

**Comment by penev92** [comment]
*Some modern or futuristic planes in some potential mods may have weapons that they can fire at a target without having to face it directly. So I suggest making this optional at the mod level, **ideally per-weapon**.
😉

**Comment by tovl** [comment]
Regression was caused by #16945.
