### ISSUE TITLE
(bleed) Spectators' radar starts without resource drawn and does not update resource status in Disable Shroud view mode.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#17422]
Selecting all or any player's view then selecting back refreshes the radar minimap and shows the resources.

Case in point - refresh was done in the first moments only.
![image](https://user-images.githubusercontent.com/1136302/70144946-4b782e80-169f-11ea-83ee-59708ace17dd.png)

**Comment by abcdefg30** [comment]
Fixed in #17672.
