### ISSUE TITLE
Attack Move Doesn't Register (Regression)

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#17438]
Consistently on the new release my attack moves are registered as move commands.

I noticed on playtest and made some mentions, but I'm absolutely certain now. After playing RAGL all season on the old release and moving to the new release, I went from almost no accidental move commands to 3 in the same match.

Something about issuing the attack move quickly, but I can't say how to reproduce it. I just know it's a regression. 

This really impacts competitive play since accidental move commands almost always lose you the game if a big fight happens.

**Comment by Orb370** [comment]
Managed to reproduce it.

If you spam attack orders an old release it's always an attack move (a+ right click).

On new release there's move orders mixed in.

**Comment by matjaeck** [comment]
Potentially related to https://github.com/OpenRA/OpenRA/issues/16924#issuecomment-520185322.

**Comment by pchote** [comment]
@dragunoff has confirmed that this is a real regression, introduced by ad099b5c980d5856a4100f89de383cc9086899ff. This commit changed the logic in the `MODIFIER_OVERRIDES` key handler from always handling the attack move hotkey to only handling it if a modifier was pressed. It seems that there is some lower level issue with the default `ButtonWidget` hotkey handling that was accidentally (or perhaps intentionally?) hidden by the override.

Not tested, but I expect that again handling the default attack-move hotkey inside `MODIFIER_OVERRIDES` should restore the previous release behaviour.

**Comment by abcdefg30** [comment]
#17552 was merged.
