### ISSUE TITLE
Frame counter doesn't count properly during/after load screen

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#17445]
If you pay close attention to the FPS counter you might notice something like this:
When starting up a mod, the FPS goes 0 -> 35 -> 60;
When coming back from the Content manager, the FPS goes 0 -> 500 -> 60;
(assuming it's limited at 60).

> pchote  Today at 4:06 PM
> yeah, that'll be because we don't use the normal render loop while loading
> so it will be counting all of the frames that happened during the load screen as if they were in one second

**Comment by anvilvapre** [comment]
Is this a bug? Worth the time to fix, as the fix will be complex/unclean. Isn't showing FPS sort of a debug/dev feature.
Is it still present?
