### ISSUE TITLE
Harvesters won't assign to a refinery if war factory rallypoint blocked

### ISSUE THREAD

**Issue by abmyii** [OpenRA/OpenRA#17448]
Disabled because of pathfinding costs? Anyway, should seek to closest, I guess.

**Comment by abmyii** [comment]
Weirdly enough it doesn't always happen. Another annoying problem is that they sometimes will seek to an obviously more distant refinery.

**Comment by abmyii** [comment]
I realised what it was - another rally-point issue. When it's blocked units just become passive.

**Comment by dragunoff** [comment]
See #15995
