### ISSUE TITLE
Auto-completion issues

### ISSUE THREAD

**Issue by abmyii** [OpenRA/OpenRA#17446]
When using auto-completion it can be a bit annoying when you want to toggle team/all chat - you have to erase everything (I believe pressing `Home` would also work though I haven't tested it). Perhaps we should change either toggle or autocomplete (Ctrl+Tab/Space?) to another key?

**Comment by abcdefg30** [comment]
Imho it would be better to change the team chat toggle to another key than to remove tab completion for player names.

**Comment by abmyii** [comment]
Yeah, it's a useful feature, and I don't suggest we remove it either. Maybe keep autocomplete as `Tab` and the toggle key to `Shift/Ctrl+Tab` or `Ctrl+Space`?

**Comment by anjew175** [comment]
I agree, this is quite an annoyance but is still kind of a rare situation.

Personally I'd rather have consistency with where the message is being sent by having separate key bindings for team chat and all chat like in Valve games and leave tab autocomplete. I've seen quite a few people say things intended for team chat in all because of how it toggles between them.

Short of this, another convention in other games is using tab to toggle the chat so I'd rather keep this functionality bound to tab and move autocomplete to something else. The problem is I don't see any other keybinding as easy as tab for autocomplete and may make the command redundant (except for ridiculous names with symbols etc)

**Comment by abmyii** [comment]
I find it happening quite often, personally.

> bindings for team chat and all chat

More hotkeys aren't desirable.

> tab to toggle the chat
Interesting idea - how about tab to enable, and tab again for autocomplete? There's no reason why it cannot be reused.

**Comment by anjew175** [comment]
> More hotkeys aren't desirable.

In some FPS games they add have completely separate keys but I've it quite common in strategies games to make a modifier, so shift+enter is team and enter is all chat (or vice versa). 
This is just an option in order to create consistency in chat usage, no writing into the wrong chat because of what you last used.

> how about tab to enable, and tab again for autocomplete? There's no reason why it cannot be reused.

Im not 100% sure what you mean by this unless you are saying a double tap to tab is autocomplete. I'd kinda prefer the current logic since double tapping can create some weird situations not too dissimilar to the current issue. The current method doesn't auto-fill a name if the current word doesn't make up somebodies name, so you can still get around it easily without having to delete ur entire sentence.

**Comment by abmyii** [comment]
Actually I'm all for "as many hotkeys as you need", but others aren't so enthusiastic. Your suggestion is good, but I think there are simpler solutions - one issue I see is that you would have to cancel and switch to the other chat in the case that you decide to write in the alternate chat.

> I'm not 100% sure what you mean by this unless you are saying a double tap to tab is autocomplete.

Sorry, that was a mistake. My proposed solution is to have `Ctrl+Tab` or `Shift+Tab` as the toggle between Team/All, and keep `Tab` as the autocomplete button.

**Comment by dragunoff** [comment]
> 
> 
> Imho it would be better to change the team chat toggle to another key than to remove tab completion for player names.

I am leaning more towards having separate keys to open the chat modes (for example `Enter` for team and `Shift + Enter` for all-chat). This takes away the cognitive load of "did I toggle the chat?" because the chat was opened with a distinct key (key combination). The option to toggle once opened can be preserved even with separate keys. Seems like the best of both worlds 🤔

**Comment by abmyii** [comment]
So `Enter`/`Shift+Enter` **&** `Tab`/`Shift+Tab` if I understand correctly?

**Comment by dragunoff** [comment]
An example arrangement (I'm not sure what'd be better for <kbd>Enter</kbd> - team or all chat):

| Hotkey | Description |
|:---|:---|
|<kbd>Enter</kbd>|Open team chat (all chat in case no team)|
|<kbd>Shift</kbd>  + <kbd>Enter</kbd>|Open all chat|
|<kbd>Shift</kbd>  + <kbd>Tab</kbd>|Toggle team/all chat (when chat is open)|
|<kbd>Tab</kbd>|Autocomplete (player names and chat commands)|

**Comment by abmyii** [comment]
Should I remove `Tab` toggling team/all chat even when no completion available?

**Comment by abmyii** [comment]
@dragunoff It has been a while - any progress on this?

**Comment by dragunoff** [comment]
> @dragunoff It has been a while - any progress on this?

@abmyii No, but I still stand behind my suggestion above. You are welcome to work on that if you're still interested. 

> Should I remove `Tab` toggling team/all chat even when no completion available?

I think it's better to have separate hotkeys for toggling and auto-complete. So the <kbd>Tab</kbd> key should only do auto-completion and toggling the team/all mode should be done with <kbd>Shift</kbd> + <kbd>Tab</kbd>.

**Comment by abmyii** [comment]
@dragunoff Sounds good, I'll work on this now!

**Comment by dragunoff** [comment]
> @dragunoff Sounds good, I'll work on this now!

@abmyii Great! Try to make the hotkeys rebindable, like I suggested in https://github.com/OpenRA/OpenRA/pull/17469#issuecomment-566535810

**Comment by abmyii** [comment]
> > @dragunoff Sounds good, I'll work on this now!
> 
> @abmyii Great! Try to make the hotkeys rebindable, like I suggested in [#17469 (comment)](https://github.com/OpenRA/OpenRA/pull/17469#issuecomment-566535810)

https://github.com/OpenRA/OpenRA/pull/17469#issuecomment-566540039 still applies I believe, however I think at least making the modifiers customisable is doable. Thoughts?

**Comment by dragunoff** [comment]
> 
> [#17469 (comment)](https://github.com/OpenRA/OpenRA/pull/17469#issuecomment-566540039) still applies I believe, however I think at least making the modifiers customisable is doable. Thoughts?

Ah, shoot... I forgot about that :thinking: Two approaches come to my mind:
1. Let the auto-complete (`Tab`) and mode toggle (`Shift+Tab`) keys remain hard-coded. You can add a `OnShiftTab` callback to the `TextFieldWidget` to handle the input.
1. Create a new `ChatTextFieldWidget` that extends `TextFieldWidget` but supports re-bindable hotkeys for auto-completion and mode toggling. Basically just override the `HandleKeyPress` method.

The first approach is of course simpler.

**Comment by abmyii** [comment]
> > [#17469 (comment)](https://github.com/OpenRA/OpenRA/pull/17469#issuecomment-566540039) still applies I believe, however I think at least making the modifiers customisable is doable. Thoughts?
> 
> Ah, shoot... I forgot about that thinking Two approaches come to my mind:
> 
>     1. Let the auto-complete (`Tab`) and mode toggle (`Shift+Tab`) keys remain hard-coded. You can add a `OnShiftTab` callback to the `TextFieldWidget` to handle the input.
> 
>     2. Create a new `ChatTextFieldWidget` that extends `TextFieldWidget` but supports re-bindable hotkeys for auto-completion and mode toggling. Basically just override the `HandleKeyPress` method.
> 
> 
> The first approach is of course simpler.

Pushed my current work (#19460) - I think that already covers approach #1. How about the idea of making just the modifiers (Shift/Ctrl/Meta/None) customisable?

**Comment by dragunoff** [comment]
> Pushed my current work (#19460) - I think that already covers approach #1. How about the idea of making just the modifiers (Shift/Ctrl/Meta/None) customisable?

I think using the standard OpenRA hotkey mechanism is the way to go :thinking: Because in this case the modifiers do not really act as modifiers - it is the combination of modifier + key that together act as a single hotkey.

**Comment by abmyii** [comment]
> > Pushed my current work (#19460) - I think that already covers approach #1. How about the idea of making just the modifiers (Shift/Ctrl/Meta/None) customisable?
> 
> I think using the standard OpenRA hotkey mechanism is the way to go thinking Because in this case the modifiers do not really act as modifiers - it is the combination of modifier + key that together act as a single hotkey.

Ah right. What would be the benefits of approach #2 - what else could a user want to set as the hotkeys for controlling the chat?

**Comment by dragunoff** [comment]
> 
> Ah right. What would be the benefits of approach #2 - what else could a user want to set as the hotkeys for controlling the chat?

I doubt many users would want to rebind but that doesn't matter much, using hotkeys first of all helps with discoverability - the user can see that these hotkeys exist and what they do. Then they may want to rebind them but that's for the user to worry about.

**Comment by abmyii** [comment]
I see.

> Create a new `ChatTextFieldWidget` that extends `TextFieldWidget` but supports re-bindable hotkeys for auto-completion and mode toggling. Basically just override the `HandleKeyPress` method.

I'm not sure I would be able to do this, at least without quite a bit of trouble due to my low familiarity with C# and the OpenRA code-base, but I a possible compromise is to list these in the hotkey page, but as static/unmodifiable hotkeys. I was also thinking to add a tooltip to the `All` / `Team` tag that the chatbox has, which tells the user that they can use those hotkeys to switch between them. Thoughts?

**Comment by dragunoff** [comment]
> 
> I'm not sure I would be able to do this, at least without quite a bit of trouble due to my low familiarity with C# and the OpenRA code-base, but I a possible compromise is to list these in the hotkey page, but as static/unmodifiable hotkeys. I was also thinking to add a tooltip to the `All` / `Team` tag that the chatbox has, which tells the user that they can use those hotkeys to switch between them. Thoughts?

After some tinkering with the concept of user hotkeys for autocomplete/toggle I think it may be a bit too much. Creating a new `ChatTextfieldWidget` works but allowing the user to mess with the keys in a text field may be is not a good idea. So I see couple of ways to improve discoverability for the hard-coded keys:
1. List them as non-modifiable keys (but currently there is no functionality for doing that)
2. Add a tooltip to the button (a new tooltip template would have to be created - one that can hi-lite text in the label)

I'd say go for the tooltip solution as that seems sufficient.

We can continue this discussion in #19460
