### ISSUE TITLE
[20191117] Performance issues investigation

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#17443]
New release introduced some yet undiscovered performance problems that are more evident in mass-player games. 
One of the examples - this video ([experimental build](https://github.com/pchote/OpenRA/releases/tag/release-20191117-renderertest1) is used, but this shouldn't have impacted the overall performance) shows general drop of tickrate somewhere around players obtaining Radar technologies. Notable performance improvement happens around 15:55 when the Demo Truck explodes in the middle of an attacking army.
https://youtu.be/2TxqVSOasa4
The replay seems to not have any performance impact when being watched, 100% speed doesn't produce any framerate drops.
https://cdn.discordapp.com/attachments/388282819371204608/653814939546550282/perftest-4v4.orarep

Another replay, this time 3v3 on Union Sacree, where ingame experience was severely hampered by lag. Again, replay doesn't show any of that.
https://cdn.discordapp.com/attachments/388282819371204608/653817212330573824/perftest-3v3.orarep

Recent stream by FiveAces also included a bunch of mass-player games, most of which were quite laggy.
https://www.twitch.tv/videos/516708450

Conclusion is it is likely that players' PC power and network connection might still be the prevalent performance factor, probably deteriorated due to some recent engine changes, or wasn't even influenced by them and stayed at the same rate, just got more highlight.

**Comment by pchote** [comment]
The first replay is a clear cut case of #17377. By the mid-game there are about 20 aircraft on the field, each taking ~1ms of tick time to evaluate.

**Comment by netnazgul** [comment]
That doesn't really explain the sudden tickrate increase after 16:00 in video; also the replay worked perfectly for me. Or is it just combined evaluation time for all players that exceeds the allowed tick length and consistently stutter-steps the game?

**Comment by pchote** [comment]
It will be hard to say for certain why it sped up without knowing what was going on on the other player's machines. What I *can* say for certain is that significantly more than half of the total tick time on my machine in that replay is spent evaluating aircraft visibility, which by itself blows past the total tick time budget available for the frame.

**Comment by netnazgul** [comment]
I see. Nerfing aircraft vision understandably won't solve the underlying problem though, but should probably be done as a temporary measure to basically allow people to play the game while the solution is sought.

**Comment by reaperrr** [comment]
> I see. Nerfing aircraft vision understandably won't solve the underlying problem though, but should probably be done as a temporary measure to basically allow people to play the game while the solution is sought.

We already have a band-aid fix (#17397) for a (most likely) upcoming hotfix release, as well as a proper, more thorough long-term fix in the works (#17383). Lowering aircraft visibility shouldn't be necessary (and probably wouldn't help enough anyway).

**Comment by pchote** [comment]
I also have another fix planned for prep that may give a further ~1.5-2x improvement.

**Comment by airetaM** [comment]
I was the top pink player in the first game and must say some of the lags might be related to the aircraft.
Also the navy and bridges surely where a problem.
> Notable performance improvement happens around 15:55 when the Demo Truck explodes in the middle of an attacking army.

With this explosion a tank gets killed wich where tracked by 2 gunboats.
A strange thing is that the replay is starting at Hour 1:28:11 and counting backwards.
The other replays seem to be normal timed.
Maybe the chronosphere at the end of my replay really changed the time :D

![chrono](https://user-images.githubusercontent.com/14834585/70565854-3fa2d580-1b93-11ea-9eeb-4d873a169b51.png)

The replay file
https://www.file-upload.net/download-13816882/OpenRA-2019-12-09T193545Z.orarep.html

**Comment by netnazgul** [comment]
> A strange thing is that the replay is starting at Hour 1:28:11 and counting backwards.
It was because the host set 90min time limit.

**Comment by abcdefg30** [comment]
Closing since the aircraft bottleneck was resolved afaik.
