### ISSUE TITLE
Planes chase targets from idle position on defend stance

### ISSUE THREAD

**Issue by Punsho** [OpenRA/OpenRA#17476]
When testing the fix for the plane strafing I spotted a regression on bleed, it's not in prep as of now. Planes if left idle on defend stance, go for a fly by whenever a unit enters their weapon range. 

Easiest test case is spawn in an AI and once it gets a harvester out, leave a Yak idling next to it.

**Comment by tovl** [comment]
The regression seems to be introduced in 801f5ba525f184299c3215bbab4b119055bb7de8.

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/pull/17619 for a proposed fix.
