### ISSUE TITLE
Disable cheats in multiplayer

### ISSUE THREAD

**Issue by clintmoyer** [OpenRA/OpenRA#17488]
### Issue Summary

I'm not sure if this was a design feature but I could not find existing documentation on it. It is common to expect cheats available in single-player mode to be disabled for online multiplayer. Currently the game creater can disable the debug menu, but the user can just open the chat console and enter cheat commands that way. It looks like maybe this was intended but the chat notifies everyone of the action?

https://strategywiki.org/wiki/OpenRA/Cheats

#### System Information

All systems impacted

#### Additional Information:
- Steps to reproduce
	1. Create new online game or join existing
	2. Enter cheat command in chat console

**Comment by pchote** [comment]
The cheat chat commands are always available in singleplayer games, regardless of the debug menu option. They should only be available in MP if the debug option is enabled.

**Comment by clintmoyer** [comment]
Okay thanks for clarifying. Is there any place we can document that or is it just an implicit design assumption?

**Comment by abcdefg30** [comment]
I don't think we have a place to document this (if at all then, at https://github.com/OpenRA/book if someone wrote a section about the commands there).

**Comment by clintmoyer** [comment]
Okay since the update recommended is for another repository, going to close this.
