### ISSUE TITLE
Weather Station and other missing options.

### ISSUE THREAD

**Issue by Judian81** [OpenRA/OpenRA#17510]
I have played all the missions of OpenRA - Red Alert and it just works fine.
I played skirmish as every country there is to select. I was good playable. 
But i found out.

Maybe am wrong but should there not be a weather station? In the startup of the Red Alert i see the weather station passing by. Another thing is i do not know if i am right. But did France not had a very big gun available?

Another thing is are England, France, German, Rusland and Ukraine the only country's to be selected?
I thought Amerika was an option too. And i do not remember if there were more soviets. But in my mind it was balanced to chose between Soviet and Allies.

**Comment by abcdefg30** [comment]
The missing things you are describing are from Red Alert 2.

**Comment by Judian81** [comment]
Ow oké my bad. I coud also remember you could select a building and chose if the new created unit should be on agressive stance or so what ever. But that shall then i think also be for Red Alert 2.

**Comment by Judian81** [comment]
[https://www.dropbox.com/s/1rd6fv3aizncp7l/Naamloos.jpg?dl=0](url)

**Comment by Judian81** [comment]
![Naamloos](https://user-images.githubusercontent.com/46109964/71486146-3b262000-2815-11ea-94a7-3cbcf2b9993a.jpg)

What kind of building is this?

**Comment by Mailaender** [comment]
Whatever the mapper wants. It's called `MISS` short for mission objective.

**Comment by Judian81** [comment]
sorry for taking your time. i will rest my case.
