### ISSUE TITLE
Screen frezes when several units are selected

### ISSUE THREAD

**Issue by hacikenks** [OpenRA/OpenRA#17516]
I select several units, then "shift+ ctrl + left click" to queue an attack move. Sometimes my screen permanently freezes, especially if I have selected too many units. I can hear the sounds after the freeze. 

I am not 100% sure, if the freeze is triggered by "shift+ ctrl + left click". It could be a more general problem.

My screen froze again after watching the replay. 
... ... ...

#### System Information
- **Operating System:** Windows 10 
- **.NET / Mono Version:** NET 4.0
- **OpenRA Version:** release-20191117
- **Mod:** Red Alert

- OpenRA Replays
Attached. Username : closed

[OpenRA-2019-12-29T155023Z.zip](https://github.com/OpenRA/OpenRA/files/4008268/OpenRA-2019-12-29T155023Z.zip)

**Comment by hacikenks** [comment]
The screen froze again in another game. This time I was not pressing ctrl +shift. I was only moving several units.  So the issue is not related to ctrl + shift.

[OpenRA-2020-01-01T154802Z.zip](https://github.com/OpenRA/OpenRA/files/4014241/OpenRA-2020-01-01T154802Z.zip)

**Comment by abcdefg30** [comment]
Odd, the replay does not freeze for me. Did the game crash/freeze for the other players as well?

**Comment by hacikenks** [comment]
I have not encountered this problem in the new version
