### ISSUE TITLE
Move AssetBrowserLogic SupportedFormats

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#17523]
Every mod has to duplicate the `chrome/assetbrowser.yaml` for the line `SupportedFormats: ` which is a bit of a non-sense. I suggest to move it to `metrics.yaml` which seems to be a general dumping ground as it also contains `ColorPickerActorType` used for the asset browser.

**Comment by pchote** [comment]
Another option would be an `IGlobalModData` module in `mod.yaml`.
