### ISSUE TITLE
performance, Sdl2Input, PumpInput

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#17520]
./OpenRA.Platforms.Default/Sdl2Input.cs

PumpEvents seems to be called each frame. Most of the time SDL_PollEvent will not return any input events, since the user has not generated them. 

The MakeModifiers and inputHandler.ModifierKeys however is always called each time PumpInput is called. Since it seems that pressing a modifier key will result also in an event it would best to initialize the modifier only once when at least one event was polled. I.e. to set the modifiers inside the PollEvent while loop (once).

This avoids both functions being always called in PumpInput (each Frame) without the resulting value being used or the value having been changed.

(Also the MakeModifiers method is quite expensive considering it only maps an SDL modifier to an RA modifier which are basically similar. Why not make the types/enum values equal and be able to cast the modifier flags.)

```
                public void PumpInput(Sdl2PlatformWindow device, IInputHandler inputHandler, int2? lockedMousePosition)
                {                                                               
                        var mods = MakeModifiers((int)SDL.SDL_GetModState());   
                        inputHandler.ModifierKeys(mods);
.
                        while (SDL.SDL_PollEvent(out e) != 0)  {
....
```

**Comment by Shkarlatov** [comment]
Please close this issue. Changes are already accepted

https://github.com/OpenRA/OpenRA/blob/f8ed768e39e4a4a9428cb46ae62377cad7e6d0e2/OpenRA.Platforms.Default/Sdl2Input.cs#L66-L68

**Comment by anvilvapre** [comment]
Alexander pointed out this is merged: https://github.com/OpenRA/OpenRA/blob/f8ed768e39e4a4a9428cb46ae62377cad7e6d0e2/OpenRA.Platforms.Default/Sdl2Input.cs#L66-L68
