### ISSUE TITLE
Graphics: flickering artifacts

### ISSUE THREAD

**Issue by joha2** [OpenRA/OpenRA#17528]
First of all: Nice games! Keep up the good work! 

Unfortunately, I have some graphics problems, which render openra and mods unplayable on my AMD machine with `amdgpu` driver.

### Issue Summary
Flickering graphics artifacts like mentioned in

https://bugs.freedesktop.org/show_bug.cgi?id=107428

Although, it seems to be, status is fixed there. See attachments there too, to get an impression. There are several links to commits, which might be responsible. Further, there is some hint on a type cast error, which is maybe already fixed. So this should not be an issue anymore. (The discussion is from September, 2018.)

I've only managed to get a screenshot from the whole game window:
![20191230_openra_bug_small](https://user-images.githubusercontent.com/12564815/71604080-3ee0dc00-2b60-11ea-91e0-00fbaa49a606.png)

The gif gives only an impression of small area in this window:
![20191230_openra_bug](https://user-images.githubusercontent.com/12564815/71604184-c7f81300-2b60-11ea-85f4-a2be3bd07c9e.gif)

#### System Information
- **Operating System:** GNU/Linux Mint 18.3
- **.NET / Mono Version:** release 20191117 Appimage
- **OpenRA Version:** release 20191117 Appimage
- **Mod:** Red Alert, Tiberian Dawn, Dune2000

Output from the game:
```
Platform is Linux
Engine version is release-20191117
Using SDL 2 with OpenGL renderer
Desktop resolution: 1920x1080
Using resolution: 1024x768
Using window scale 1.00
OpenGL version: 3.0 Mesa 18.0.5
Using default sound device
Internal mods:
	modcontent: Mod Content Manager (release-20191117)
	ra: Red Alert (release-20191117)
External mods:
	cnc-release-20191117: Tiberian Dawn (release-20191117)
	d2k-release-20191117: Dune 2000 (release-20191117)
	ra-release-20191117: Red Alert (release-20191117)
Loading mod: ra
```

lspci VGA controller:
```
08:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Raven Ridge [Radeon Vega Series / Radeon Vega Mobile Series] (rev c8)
```

`glxinfo -B`:
```
name of display: :0.0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: X.Org (0x1002)
    Device: AMD RAVEN (DRM 3.33.0 / 5.3.8-050308-generic, LLVM 6.0.0) (0x15dd)
    Version: 18.0.5
    Accelerated: yes
    Video memory: 991MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: X.Org
OpenGL renderer string: AMD RAVEN (DRM 3.33.0 / 5.3.8-050308-generic, LLVM 6.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.5
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 3.0 Mesa 18.0.5
OpenGL shading language version string: 1.30
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 18.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
```

#### Additional Information:
- Steps to reproduce
	1. just start the game

- Logs
n/a

- OpenRA Replays
n/a

- Screenshots & Videos
see above

Hope this helps in solving this issue.

Best wishes
Johannes

**Comment by pchote** [comment]
Can you please try the test build from https://github.com/pchote/OpenRA/releases/tag/release-20191117-rendertest2 and report back if it changes anything?

**Comment by joha2** [comment]
@pchote thanks for your very fast response! The rendertest2 app images show the following behaviour:
* Red Alert: crashed before reaching the main menu (had to be terminated by `kill`)
* Dune 2000: crashed before reaching the main menu (had to be terminated by `kill`)
* Tiberian Dawn: all fine (no graphics errors observable after a short testing)

**Comment by pchote** [comment]
Ok, that's a good sign. Can you please share the `graphics.log` file that is written out to either `~/.openra/Logs/` or `~/.config/openra/Logs/` when RA or D2k crashes?

**Comment by joha2** [comment]
Dear @pchote both games lead to an empty `graphics.log` file. Crashed means: Both games lock up during loading, but music plays. The `graphics.log` file stays empty. Is there a setting, where I can force some output to `graphics.log`?

**Comment by joha2** [comment]
@pchote Happy new year! I played around a bit with the rendertest2 app images and realized that none of them generates a `graphics.log` file. All files (except `install.log` and `traitreport.log`) are touched when calling the app images, but the files stay empty:
```
joha2@akila ~/.c/o/Logs> pwd; ls -l
/home/joha2/.config/openra/Logs
total 28
-rw-rw-r-- 1 joha2 joha2 7081 Jan  2 18:54 debug.log
-rw-rw-r-- 1 joha2 joha2    0 Jan  2 18:53 geoip.log
-rw-rw-r-- 1 joha2 joha2    0 Jan  2 18:53 graphics.log
-rw-rw-r-- 1 joha2 joha2  806 Dec 27 12:25 install.log
-rw-rw-r-- 1 joha2 joha2    0 Jan  2 18:43 lua.log
-rw-rw-r-- 1 joha2 joha2    0 Jan  2 18:53 nat.log
-rw-rw-r-- 1 joha2 joha2 6392 Jan  2 18:54 perf.log
-rw-rw-r-- 1 joha2 joha2    0 Jan  2 18:53 server.log
-rw-rw-r-- 1 joha2 joha2    0 Jan  2 18:53 sound.log
-rw-rw-r-- 1 joha2 joha2 4242 Jan  1 20:09 traitreport.log
```
Do you have an idea, what to do next?

**Comment by pchote** [comment]
I'm fairly confident that the bugs are in your graphics card drivers, and that there isn't going to be much we can do within OpenRA to fix them.

The rendertest2 build changes the rendering APIs we use from OpenGL 2 to OpenGL 3, which I was hoping would bypass whatever problem is going on within your system - and the fact that TD now runs without error suggests that is partly the case. Unfortunately it seems that RA and D2k hit an even worse case, crashing outright instead of showing glitches.

The rendertest builds are still a work in progress, and possibly still buggy. I'll comment here when a new test build available and we'll see whether the crashes go away.

**Comment by joha2** [comment]
@pchote thanks for your fast and thorough response! Yeah the graphics drivers are for sure buggy, since the `amdgpu` driver has the problem of also crashing from time to time with a page fault error locking up the whole os. This problem was mitigated in the 5.3.8 kernel I use atm in such a way that there happens a soft recover which prevents system from crashing. Also this soft recover failes sometimes.

Yes, please ping me, if there is a new rendertest app image to test. I would be happy to assist you here.

Best wishes
Johannes

**Comment by pchote** [comment]
Give https://github.com/pchote/OpenRA/releases/tag/release-20191117-rendertest3 a try.

**Comment by joha2** [comment]
Hey @pchote, thanks for the link to the new version. Unfortunately, the behavior of the games did not change:
 * Dune-2000 gets until `Fueling Carry Alls` and locks up (no music)
 * Red-Alter gets until `Splitting Atoms` and locks up (with music)
 * Tiberian-Dawn runs normally (no graphics errors, with music and sounds)

`graphics.log` again is empty. 

Hope this helps!

Best wishes
Johannes

**Comment by pchote** [comment]
Can you try downloading https://github.com/pchote/OpenRA/releases/tag/release-20191117-rendertest4 and launching it from the commandline as `./OpenRA-Red-Alert-x86_64.AppImage Graphics.DisableGLDebugMessageCallback=true`? (only needs to be done once, the game will remember the new setting)

**Comment by joha2** [comment]
Hey @pchote thanks for providing rendertest4. I started all three games and they all just work, no crashed or flickering artefacts. I don't know whether this is due to a new version or due to the command line parameter, you provided, but it is awesome :smile: Anyway, the `graphics.log` is still empty. If I can test more on this, just ping me. Big thanks!

**Comment by pchote** [comment]
Great news! I'll mark #17603 to close this when it is merged.

**Comment by joha2** [comment]
Hey guys, hey @pchote 

I just downloaded the newest release (AppImage) 20200202 and unfortunately, the original bug of this issue is appearing again. All mods, ra, dune2000, td have this problem. Also I tried to use `./OpenRA-Red-Alert-x86_64.AppImage Graphics.DisableGLDebugMessageCallback=true`, but it didn't change anything. Rendertest4 is still working without any issues. If I could do anything to help with this regression, please let me know.

Best wishes and stay safe
Johannes

**Comment by pchote** [comment]
The 20200202 release is still based on mid-2019 era code, so doesn't have any of these fixes!

We should have a new release out in a few days based on playtest-20200426 which should hopefully still work without issue.

**Comment by joha2** [comment]
Thanks @pchote for your fast response and thanks for the information regarding the new release. I am eager for the new release, then :-) Best wishes and stay safe!
Johannes
