### ISSUE TITLE
Add visual indicator when sound is muted

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#17549]
The hotkey to mute sounds could be pressed accidentally and in the heat of battle the player might not notice the chat notification and wonder why the sound is off. Displaying a persistent visual indicator would be helpful to quickly assert whether the sound has been muted.

See  https://github.com/OpenRA/OpenRA/pull/17482#discussion_r362676920

**Comment by pchote** [comment]
The chat notification is also currently displayed in the wrong colour.

**Comment by dragunoff** [comment]
#6400 is related

**Comment by pchote** [comment]
If we can quickly agree on a size and location for the indicator I will be able to add the artwork as part of #17494 etc and save a redundant set of png sheets from going into the git history.

**Comment by teinarss** [comment]
Top right corner, left of the minimap? Something like this https://commons.wikimedia.org/wiki/File:Mute_Icon.svg with color and black borders would make it easy to see.

**Comment by dragunoff** [comment]
Some mockups, in-game:
![openra-audio-muted-indicator--cnc-game](https://user-images.githubusercontent.com/1355810/71723248-a46ceb00-2e34-11ea-93ec-299f4e6e34ad.png)
![openra-audio-muted-indicator--ra-game](https://user-images.githubusercontent.com/1355810/71723249-a46ceb00-2e34-11ea-954b-81288beede8e.png)

In replays:
![openra-audio-muted-indicator--cnc-replay](https://user-images.githubusercontent.com/1355810/71723251-a5058180-2e34-11ea-9c09-def6f887230c.png)
![openra-audio-muted-indicator--ra-replay](https://user-images.githubusercontent.com/1355810/71723250-a5058180-2e34-11ea-8ea3-f267afca014d.png)

Next to the sidebar:
![openra-audio-muted-indicator--cnc-game-sidebar](https://user-images.githubusercontent.com/1355810/71723488-7b992580-2e35-11ea-9b3c-19f43974bc23.png)
![openra-audio-muted-indicator--ra-game-sidebar](https://user-images.githubusercontent.com/1355810/71723489-7b992580-2e35-11ea-9dd1-c0af36ae1532.png)

My thoughts:
- I think it looks better in the middle of the screen as it doesn't clash with other parts of the UI.
- Adding a text label makes it clearer and more visible
- A shadow/stroke is needed for the notification to stand out against the background
- The size and positioning can be further adjusted, this is just a quick mock-up. Here is the SVG I put together if anyone wants to play with it: https://drive.google.com/open?id=1pnBGTnvOWqdLleS71fztBut3OA1R8siV

**Comment by abcdefg30** [comment]
Putting it in the top mid will conflict with our Lua mission text.

**Comment by pchote** [comment]
Aligning it to the right is probably our best bet for avoiding overlaps with other text. We may have to omit the text to make sure it doesn't clash at the smallest screen sizes.

**Comment by pchote** [comment]
![](https://i.imgur.com/aX4iVhP.png)

Added glyph to #17494 and #17495.
