### ISSUE TITLE
Wish: restart button on mission lua.error

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#17540]
When testing lua scripts ingame, the "Restart" button comes in handy but it got disabled during the latest UI changes.

I would prefer to have it available after an lua error, again.

Often the error is due to a minor typo in the script (alt+tabbing and changing it). The restart button is missed

**Comment by Mailaender** [comment]
This might make sense for developers (quick restart) but players should probably report the error before restarting the mission and erasing the logs?
