### ISSUE TITLE
Pillboxes do not fire

### ISSUE THREAD

**Issue by fusion809** [OpenRA/OpenRA#17555]
### Issue Summary
Pillboxes and camo pillboxes do not fire and do not even seem capable of firing as there's no mechanism order them to. Turrets still fire, however.

#### System Information
- **Operating System:** Arch Linux
- **.NET / Mono Version:** Mono 6.4.0.
- **OpenRA Version:** 7622147.
- **Mod:** Red Alert.

#### Additional Information:
Under OpenRA, built from commit 7622147 load this saved game:
[Ascent.zip](https://github.com/OpenRA/OpenRA/files/4021974/Ascent.zip)

- Logs
[logs-20200104.zip](https://github.com/OpenRA/OpenRA/files/4021977/logs-20200104.zip)

- OpenRA Replays
[replay-20200104.zip](https://github.com/OpenRA/OpenRA/files/4021978/replay-20200104.zip)

**Comment by pchote** [comment]
Regression was introduced by a9d7535915824d88c78643e7fa6142a1c8691702 in #17376.

This commit moved the passenger notification logic into the `Cargo` constructor, where it suffers from the trait initialization order problems that always occur when gameplay logic is accidentally put into a trait constructor.
