### ISSUE TITLE
Feature : Supply truck having resupply role.

### ISSUE THREAD

**Issue by WhoCaresora** [OpenRA/OpenRA#17577]
If this has never been considerate : 

Supply truck acting like a mechanic but instead of replenishing health point, can replenish ammo pool.

-Could be used stationary near any helipad airport to help to rearm faster.
-Could be used to replenish mine layers on the field or faster on the sd.
-Could be used to rearm helicopter anywhere thank to the force land. This would give a boost to helicopter play.

As the "primary" role remains the fund transfert this unit would present a risk to feed high cash to the opponent. it would also need to think correctly the value of the resupplying to be in adéquation with the price and fact any player can get back the full value of the unit at anytime.

**Comment by CortexReaver** [comment]
Hope we'll see it in a new versions :P

**Comment by abcdefg30** [comment]
There is https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Conditions/ProximityExternalCondition.cs which can be used to enable a `ReloadAmmoPool` trait on the target actor, so this should already be doable in map-mods.

**Comment by PunkPun** [comment]
It is possible, but I didn't think this needed closing as this is an idea/suggestion for the base mods

**Comment by abcdefg30** [comment]
It is very unlikely this will happen for the base mods however.
