### ISSUE TITLE
Ore truck's "mining orders" are displayed with a green line instead of a red line.

### ISSUE THREAD

**Issue by WhoCaresora** [OpenRA/OpenRA#17574]
Ore truck's "mining orders" are displayed with a green line instead of a red line.

This can lead to misreading ore truck real order and end up with idle oretruck on empty tile when the intent was to eco transfert and mine.

**Comment by abcdefg30** [comment]
Hm, I think that was deliberately done in #16549. Also see #16616.

**Comment by tovl** [comment]
It always was green. I initially made it red in #16549, but then reverted it in response to review requests; the main point being that such changes would need to be discussed separately. The discussion in #16616 glossed over it and it became lost in the arguments over line widths. After that, it simply never came up again (and I got sick of arguing about lines).

**Comment by WhoCaresora** [comment]
Well, red line for oretruck does the trick because it is rare to find yourself selecting them with other unit other than an emergency order or a mistake. i can't really think about a situation where you could be annoyed/mistaken about the color red for oretruck under mining order.

That being said, I'm totally for a "blue" color line for technical "non weaponized" action such as harvester unit or minelayer and ... what else ?

**Comment by abcdefg30** [comment]
> It always was green.

No, it has been red since many years: https://github.com/OpenRA/OpenRA/blob/a0dc38c252aaebcf002dc5a070b9fe9cd1308c21/OpenRA.Mods.Common/Activities/FindResources.cs#L130 (this commit is almost 5 years old, and the real change is even older.)

**Comment by tovl** [comment]
Huh...somehow pchote got me convinced it was something I changed: https://github.com/OpenRA/OpenRA/issues/16616#issue-450012374, https://github.com/OpenRA/OpenRA/issues/16616#issuecomment-497102414 and then I mistakenly "reverted" it.

Well, at least we can all agree that it should be red (or at least nobody really wanted it to be green).

**Comment by pchote** [comment]
Honest mistake on my part - my focus in those comments was on the changes to the blue and yellow lines, and I also agree that red is reasonable for harvesting.
