### ISSUE TITLE
Mute music in lobby and main menu

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#17584]
Nearly every time I enter the lobby the first thing I do is to go to the music tab, start a track, then pause it. This hack allows me to stop the background music. I do this because often I have to sit in the lobby for long periods of time during which I want to be hearing chat beeps but not the background music. Someone was asking about this on discord recently and I realized that players may not be aware of this hack. An option could be added to mute the background music in lobbies and maybe also in the menu in general.

**Comment by Punsho** [comment]
In that case I just mute music

**Comment by dragunoff** [comment]
> 
> 
> In that case I just mute music

Muting music doesn't cut it because I want to listen to those Frank Klepacki tunes in-game but not while hanging in a lobby for long time. 

I have made a working prototype of the feature but I wonder if it should be muting background music in all menu screens or just in the lobby? The background music in menus is not so annoying because less time is spent there and one could argue that it's part of the experience. 🤔
