### ISSUE TITLE
Consider making the color validators of the default mods more strict

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#17582]
As noted in #17272, the color validator is not very restrictive and allows very similar colors (both to the terrain and other players).

**Comment by KOYK** [comment]
I wish to make a request for this, in my mod I want to add TeamColorPresets that are somehow hard coded? like the white color or colors that are very close to white. So I wish that colors that are set by the mod.yaml under TeamColorPresets to overwrite the ColorValidator code and allow them to exist without revoking the player color and re assign a new one. Is that possible?

**Comment by Mailaender** [comment]
https://github.com/OpenHV/OpenHV/search?q=d0a090 I currently have both a team color and a terrain color defined with the same value as the palette is limited. The validator does not kick in.
