### ISSUE TITLE
Improve usability when remaping duplicate hotkeys

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#17599]
## Motivation

Recently I played the game on a new PC and since I use a highly customized hotkey layout I had to remap a lot of keys. However that proved to be quite cumbersome because if I the key I'm trying to remap is already bound to something else I'd first have to go to that other binding and change it. So it becomes a multi-step back and forth process:

1. Try to remap X
1. Receive warning that this key is already mapped to Y
1. Find Y
1. Remap Y (or clear it)
1. Go back to X and complete intended the remap

## Proposed solution

I suggest we add a way to override the duplicate during the initial remap. This would make the process much easier because it would eliminate the back and forth to remap the other key. 

1. Try to remap X
1. Receive warning that this keys is already mapped to Y
1. Override Y

I came up with two ways to represent this in the dialog:

### Additional "Assign / Override" button

![hotkey-override--button](https://user-images.githubusercontent.com/1355810/72810578-8b529f80-3c66-11ea-8be1-65ed73a34a92.png)

This button would be always visible but only become active when there is a duplicate. The downside is that in most cases this button would not serve any purpose.

This can be worked-around by having the button appear inside the input field only when necessary:

![hotkey-override--inline](https://user-images.githubusercontent.com/1355810/72988652-56288780-3df5-11ea-86d9-1126b3a9fba4.png)

### An overlay dialog

![hotkey-override--dialog](https://user-images.githubusercontent.com/1355810/72810717-cce34a80-3c66-11ea-9c86-5e5a7235267a.png)

This works around the need to have a third button. The downside is that it obscures the original dialog and we'd have to repeat everything to make ourselves clear (hotkey description, desired key combo, duplicate hotkey description).

**Comment by dragunoff** [comment]
A working prototype: 
![изображение](https://user-images.githubusercontent.com/1355810/73102554-c1a84d00-3efa-11ea-98c9-0440d3b5ca87.png)

Perhaps the button looks a little off

**Comment by abcdefg30** [comment]
> This button would be always visible but only become active when there is a duplicate. The downside is that in most cases this button would not serve any purpose.

We could always show the assign button and require the user to press it to set a hotkey. The text could then change to "override" in case of a conflict. (I hope that will make immediately clear to the user what is going on and what the override button is going to do, i.e. "aha, instead of assigning I need to override this key".)

**Comment by dragunoff** [comment]
> 
> 
> > This button would be always visible but only become active when there is a duplicate. The downside is that in most cases this button would not serve any purpose.
> 
> We could always show the assign button and require the user to press it to set a hotkey. The text could then change to "override" in case of a conflict. (I hope that will make immediately clear to the user what is going on and what the override button is going to do, i.e. "aha, instead of assigning I need to override this key".)

Yes, that's an option too. I thought about it but forgot to mention it in the OP. The downside is that it adds a step to the rebinding process (user always has to press "Assign" instead of the game auto-assigning a valid key). 

When a key is in this limbo state a "Cancel" button also makes sense - if the user realizes they don't want to assign/override a key.

**Comment by abcdefg30** [comment]
I don't think an extra action is a problem here while explicit assigning is an improvement. (The user now knows for sure they set the key. Before they were left wondering if they needed to press enter, or if leaving the field cancelled, etc.) Fwiw, if I was to just change a single hotkey and didn't know the code, I would not immediately use the back button to leave but make sure the game actually set the hotkey by switching to another key and back.

As you said, a cancel button would be useful for similar reasons. If we already have assign then cancel might be superfluous however.
It might also get very crowded with two more buttons, so we could use your overlay idea and always show the overlay once a key is pressed? (I'm not yet completely sold on that.)

**Comment by dragunoff** [comment]
I have prototyped both approaches (1) explicit "Assign" button and (2) auto-assign with "Override" when needed) and I think that auto-assign works better. I find it more fluid and easier to use - there are less steps needed for a rebind and it also falls in line with the approach OpenRA has taken for other settings - they instantly apply. With an "Assign" button an extra step is required of the user, even when using the "Reset" button on a hotkey (as there may be duplicates).

However we're running out of space in the dialog when the "Override" button is visible all the time:
![override-hotkey](https://user-images.githubusercontent.com/1355810/73481933-72a06300-43a5-11ea-87d4-f511a2c5b51b.png)

Perhaps we should put the description on its own line (like in earlier prototypes of the dialog):
![изображение](https://user-images.githubusercontent.com/1355810/73482505-8c8e7580-43a6-11ea-9493-4d90eb7d6b76.png)
