### ISSUE TITLE
Queued deploy orders from keyboard cause unit to deploy then instant undeploy.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#17598]
We first noticed this in RV, but after further testing issue exists in SP and bleed TS too. You can test with deployable stuff in TS (Tick Tank, Sensor Array, Artillery, Juggernought). It only happens when you use the keyboard shortcout (F by default). Clicking the deploy button on the bottom left menu or clicking the unit itself work fine. Non-queued deploy orders from the keyboard also work fine. But for queued deploy orders from keyboard, even as the first order (you can just shift+f, no need for prior move orders), the unit will instantly undeploy.

**Comment by pchote** [comment]
All deploy orders, or just `GrantConditionOnDeploy`?

**Comment by MustaphaTR** [comment]
Only tested with GCoD stuff. Lemme see.

**Comment by MustaphaTR** [comment]
Cannot reproduce the issue with TS MCV, so i guess only GCoD.

**Comment by pchote** [comment]
Regression also affects d2k (thumpers) on the prep branch.

**Comment by pchote** [comment]
Regression was introduced by #17552, which causes key-up (and key repeat) events to queue N deploy orders. We picked the regression to the hotfix, so we will need to fix this there too.
