### ISSUE TITLE
Prompt the user on settings panel reset

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#17600]
## Motivation

The "Reset" button in the settings panel performs a destructive action and there is no way to recover from an accidental press of the button.

## Proposed solution

Prompt the user to confirm the action when the "Reset" is used. A simple dialog should suffice. 

![reset-settings-prompt](https://user-images.githubusercontent.com/1355810/72812127-9ce97680-3c69-11ea-9e5b-61edbb67e098.png)

Related issue: #9774

**Comment by dragunoff** [comment]
Working prototype:
![изображение](https://user-images.githubusercontent.com/1355810/73103763-780d3180-3efd-11ea-96ea-e8f0986c696a.png)

I'm open to suggestions on the wording.

**Comment by abcdefg30** [comment]
Imho the original text "Are you sure you want to reset the settings in this panel?" was better. (Is this text too long?) We could change the title to "Reset \"Hotkeys\" Settings" to mention the panel name.

**Comment by dragunoff** [comment]
Yup, looks better:
![reset-prompt](https://user-images.githubusercontent.com/1355810/73106725-c07c1d80-3f04-11ea-92b6-f14c82549925.png)

**Comment by Snurre86** [comment]
I like the last one better.

**Comment by pchote** [comment]
Reset "<tab name>" Settings looks odd, IMO. How about just Reset <tab name>?

**Comment by dragunoff** [comment]
With the wording I want to make it clear that only the settings in the current tab will be reset. There is however a separate issue with the "Reset" button - before pressing it there is no indication that it resets only the current tab. I thought for a very long time that it resets all settings, and I suppose many players think the same. It's kinda implied by the layout - the button is attached to the whole panel, on the same level as the "Back" button. Without changing the layout what we could do is change the label or add a tooltip :thinking:
