### ISSUE TITLE
Allow conyard to accept and queue mcv's order.

### ISSUE THREAD

**Issue by WhoCaresora** [OpenRA/OpenRA#17602]
some people experience "conyard deployment issue"
As you can now make a conyard undeploy with a force move order,
and shift queue a deploy order
I guess people started to do the following sequence : force move + shift + f
The problem is :
Conyard won't accept the shift F before being in mcv form
So the player thinks the deploy order is queued but it is not.

I would like to improve the new ALT+MOVE for conyard by allowing the conyard to queue any order an mcv can take.

**Comment by pchote** [comment]
This should be an easy usability improvement, so tentatively adding to the milestone.

**Comment by Snurre86** [comment]
Yes queue orders that are currently not allowed, like if the mcv is close to a wall when you queue a deploy order.
