### ISSUE TITLE
Allies 05a, captured warfactory does not grant servicedepot

### ISSUE THREAD

**Issue by Basti504** [OpenRA/OpenRA#17613]
## Reproduction
Playing the latest release 20191117 and mission allies 05a. With the 2 engineers given from the start I captured the soviet conyard and the soviet war factory. But building the service depot is not allowed because it requires a war factory, while I do own a (captured) war factory.

When I build a (second) warfactory myself, the service depot was allowed to be build.
This seems like a bug to me.

STEPS TO REPRODUCE THE ISSUE

With the two engineers, capture the conyard and war factory. Service depot is not allowed to be build.

EXPECTED BEHAVIOR

It should not matter how I acquired the war factory, building it myself or capturing it should not matter for the service depot requirements.

If needed I can post a savegame, but the steps should be simple enough.

## Screenshots / Screen recordings / Replays

![Image](https://imgur.com/mT831AH.png)

**Comment by pchote** [comment]
The pre-placed structure is a map-specific `WEAP.infiltratable`. Adding an explicit `ProvidesPreqrequisites` granting `weap` should fix this, but we should make sure to check whether any other missions with custom building overrides suffer from the same issue before PRing.

**Comment by pchote** [comment]
Other cases to check:

## RA
Monster Tank Madness defines a `DOME.NoInfiltrate`
Soviet Soldier Volkov and Chitzkoi defines `CCEN` (but i'm not sure if this mission has engineers)
Survival01 has `AFLD.mission` and `ATEK.mission`

## D2k
atreides-02b defines `outpostnopower`
atreides-05 defines `barracks.harkonnen`

## TD
Several missions (nod07c, nod08a, nod08b, nod09) define overrides, but all appear to already define the prereq overrides.
