### ISSUE TITLE
Units are able to get seen out of line of sight

### ISSUE THREAD

**Issue by UppsAlert** [OpenRA/OpenRA#17632]
It is a older problem that Units can seen sometimes out of line of sight.
It got captured during Five Aces streaming https://www.twitch.tv/videos/543191811?t=0h40m56s on the playtest (area around the Ranger next to the yellow player's base).
[Units are able to get seen out of line of sight.zip](https://github.com/OpenRA/OpenRA/files/4131331/Units.are.able.to.get.seen.out.of.line.of.sight.zip)

**Comment by abcdefg30** [comment]
![grafik](https://user-images.githubusercontent.com/7704140/73778792-10bc7080-478c-11ea-8b51-9ea9cb6a8af5.png)
Doesn't look like a bug to me.
