### ISSUE TITLE
Incoming/LaunchSpeechNotification/Sound only work for some *Power:s.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#17635]
`PlayLaunchSounds()` function gets called from Nuke, IonCannon, Airstrike, Paradrop, SpawnActor and PrerequisiteChargeDrain powers, and GPSPowers separately play LaunchSpeechNotification/Sound but not Incoming. The rest of the *Power:s do not play those notifications.

Altho this is an easy fix, not sure if there is a reason why `PlayLaunchSounds()` isn't called from `SuperWeapon.Activate()`, so i don't know if it all should be moved there, or it should be added to missing powers.

**Comment by abcdefg30** [comment]
Powers like `ParatroppersPower` can get activated from outside of the `Activate` override, but we still want to play their sounds. I think that was the reason we didn't call the method in the superclass.

**Comment by MustaphaTR** [comment]
Makes sense, i'll make a PR with the function added to the rest of the powers then.
