### ISSUE TITLE
Reverses crashes although the referenced frames exist

### ISSUE THREAD

**Issue by Dzierzan** [OpenRA/OpenRA#17646]
It seems that Sequences can have Reverse which allows the animation to go back and forth. Cool. However I discovered it might have a bug.

My pngsheet has 10 frames. Frames 3-10 are supposed to be the animation which should go back and forth. If I setup such parameters:

	production: harbor.png
		Start: 3
		Length: 7
		Reverses: True
		Tick: 120

The game will crash as it expects more frames. The crashlog says 

> Sequence harbor.production uses frames [3..14], but only 0..9 actually exist

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/17627 solves this.

**Comment by Mailaender** [comment]
It seems `Reverses` only works for Tiberian Sun because the sprite has the shadow frames at the end which increase the length of the sprite frames although those aren't used by reversing.
