### ISSUE TITLE
Ability for lobby host to kick spectator in game

### ISSUE THREAD

**Issue by WhoCaresora** [OpenRA/OpenRA#17656]
It would be interesting to extend the power of a lobby admin (host) in game with the ability to kick spectators.

Spectators are often the cause of a game being restarted for the following reasons : 

-performance issues
-Lag issues
-Anything related to the in game "all chat"

Sometime asking a spectator to leave is enough, but all the involved player and respectful spec would like to be able to kick an undesired spec or just an afk spec causing issues.

I don't have a particular preference to implement it but i guess a "kick" button in scoreboard would do the trick with a "confirm" chat box to be sur not to missclick  "Confirm kick on xxxxx YES NO"

**Comment by pchote** [comment]
This has been raised as an important feature for fighting the ongoing troll problem, so tentatively adding to the milestone as a wishlist item (shouldn't significantly block the first playtest)
