### ISSUE TITLE
Attempting to stream game on Discord causes System.InvalidOperationException to be thrown

### ISSUE THREAD

**Issue by iskandarzulkarnaien** [OpenRA/OpenRA#17660]
## Issue Summary

Am running dev version of OpenRA. Attempting to stream any game on Discord causes `System.InvalidOperationException` to be thrown. Game then crashes (logs attached below)

## Reproduction

Stream any OpenRA game on Discord, the debugger will show the exception. Game crashes once program execution is resumed.

## Logs

[graphics.log](https://github.com/OpenRA/OpenRA/files/4174694/graphics.log)

**Comment by pchote** [comment]
> GL_INVALID_ENUM error generated. Operation is not valid from the core profile.

This means that the streaming tool is attempting to inject invalid legacy OpenGL calls into OpenRA. 
This is a bug with Discord rather than OpenRA, so i'm sorry to say that there is nothing we can do to fix this here.
