### ISSUE TITLE
Neural Upscale

### ISSUE THREAD

**Issue by AI-Guru** [OpenRA/OpenRA#17671]
What about scaling up the visual assets with Deep Neural Networks?

https://www.pcgamer.com/this-doom-mod-uses-neural-network-image-upscaling-to-improve-on-a-classic/

**Comment by cool-pants** [comment]
I think this is a good idea but do you know how it works for games.  Like for images we can improve the GAN using low and high res images. But what about games, does it upscale the textures?

PS: This is a genuine question as i am quite a noob in AI and CNN. Thank you.

**Comment by AI-Guru** [comment]
You would upscale all assets offline. The DOOM-assets are very convincing.

**Comment by abcdefg30** [comment]
With the remastered graphics this is obsolete now.
