### ISSUE TITLE
Won't go full screen on external display (Mac)

### ISSUE THREAD

**Issue by janoist1** [OpenRA/OpenRA#17687]
On Mac, it won't go fullscreen on external display. Game always starts in main screen (MacBook built-in) so that I'm guessing it simply won't detect me moving it to the external screen as the resolution is already given by the built-in screen at startup.

Screenshot:

![Screenshot 2020-02-15 at 21 48 42 (2)](https://user-images.githubusercontent.com/1331668/74595760-6b33b780-503d-11ea-96c0-4d48a189d7b4.png)

Anyway, the game is awesome!!!!! I love every little piece if your work!!!

**Comment by pchote** [comment]
The default behaviour is to open on the display that you have configured as primary in macOS. The quick workaround for now is to change this in your display settings before launching OpenRA.

The development branch (which should hopefully be released as a new playtest in a couple of weeks) includes a new option in the settings menu to set a different display. I believe this fixes the main issue here, so I'll close this as already fixed :smile:

In the longer term, the ability for the game to resize itself when moved between displays in mission control will come after #16821.

**Comment by janoist1** [comment]
Great! Thanks for letting me know! 👍
