### ISSUE TITLE
Can we just make special actors like Player Position and Camera unselectable and untargetable in all order?

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#17681]
In openra's engine, Player Position and Camera are also actors but they can sometimes block normal selecting and targeting order, especially the Player Position block the construction yard when try to attack it.

**Comment by dnqbob** [comment]
It is a flaw but I think it is strange when something block target when attack the construction yard at Player Position.

**Comment by pchote** [comment]
Can you please provide a reproduction case to demonstrate the issue? Spawn points and cameras do not occupy space and aren't targetable or selectable, so there should be no mechanism for them to influence selection or targeting.

**Comment by dnqbob** [comment]
Vs Ai,  when you attack the AI construction yard at their own Player Position,  you can move your cursor around the image of construction yard and find sometimes the attack cursor become select cursor,  by press the button you can lose your select collection

**Comment by dnqbob** [comment]
Original repair order cursor also has this problem: when repair the damaged structure just cover the Player Position actor,  which is normally your construction yard,  you can also move around construction yard image and find that at probably center of the image the cursor became unrepairable.

**Comment by dnqbob** [comment]
probably I should say although I know those actors are tagged as 'unselectable' but some of the cursor functions are still considering them in their selection set. let even them completely ignore those very special actors. 

Those functions including attack,  capture,  repair,  powerdown and probably,  sell.

**Comment by pchote** [comment]
> when repair the damaged structure just cover the Player Position actor, which is normally your construction yard, you can also move around construction yard image and find that at probably center of the image the cursor became unrepairable.

I can't reproduce this in bleed RA or TD. What mod/version are you seeing this on?

**Comment by dnqbob** [comment]
I know some orders like attack order can apply to unselectable things like tree and wall.  So please give them a tag that is even more special to help in ignoring them in all the order set.

**Comment by MustaphaTR** [comment]
@pchote Can you test with left click orders, i feel like that may be an issue with it.

**Comment by pchote** [comment]
> I know some orders like attack order can apply to unselectable things like tree and wall. So please give them a tag that is even more special to help in ignoring them in all the order set.

This has always been the case: attack uses `Targetable`, repairing uses `Repairable`, capturing uses `Capturable`, and so on.

> @pchote Can you test with left click orders, i feel like that may be an issue with it.

Still no repro, on both bleed and the current release.

**Comment by dnqbob** [comment]
On TS mod.  Now the repair order works good but normal attack can be wrong(not Ctrl attack).

**Comment by dnqbob** [comment]
I am sorry for mistakes there. It seems except TS mod all other mods work well on fixing this bug at current version.

**Comment by pchote** [comment]
Confirmed when attacking an enemy conyard. This is probably a regression from #17291.

Edit: Confirmed that this was introduced by 8f5be6160f.
