### ISSUE TITLE
selection box/bar for subterranean units will disappear when subterranean 

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#17680]
During my modification, I find that selection box/bar or all renderable objects that bounded with the subterranean unit will gone once they are subterranean. Is it a bug or feature?

**Comment by pchote** [comment]
Bug, and previously tracked in #17186.

Unfortunately, GitHub hides issues that were posted by now-deleted accounts from searches, so that ticket is now compromised. We can use this one to track the issue going forward.

**Comment by dnqbob** [comment]
I suggest to make a always-render-first attribute for renderable objects. By using those we can get visual information when actors get covered by other actors' image or simply covered by terrains.

**Comment by pchote** [comment]
That is covered by #13163. Lets keep this one focused on the missing selection box which I expect should be a simple regression from a previous change.

**Comment by dnqbob** [comment]
> That is covered by #13163. Lets keep this one focused on the missing selection box which I expect should be a simple regression from a previous change.

Really? I thought this was probably a complex problem.
