### ISSUE TITLE
ScaredyCat's AttackPanicChance does not work

### ISSUE THREAD

**Issue by augustus8825** [OpenRA/OpenRA#17683]
## Issue Summary

The ScaredyCat trait has a subtrait called AttackPanicChance which is supposed to affect the chance the unit has to flee when it recieves damage. Changing this values doesn't work and the unit will always flee when attacked.

## Reproduction

This can be reproduced by acquiring or making a unit that has the ScaredyCat trait, giving it AttackPanicChance: (Any #) and attacking it. The unit will always panic.

## Expected behavior

The  AttackPanicChance should be calculated for. E.g if AttackPanicChance is set to 50, the unit has a 50 chance of panicking when it recieves damage.

**Comment by pchote** [comment]
The field description is wrong: `AttackPanicChance` actually sets the probability to panic when the actor attacks something else (it is also implemented incorrectly, so won't even work properly for this). The probability of panicing when attacked is hardcoded at 100%.
