### ISSUE TITLE
Nod Missions 9, 10a, and 10b of Tiberan Dawn have you play as GDI via the sidebar UI.

### ISSUE THREAD

**Issue by RedlerSchnyder** [OpenRA/OpenRA#17690]
Exactly as it says, although a small issue. But don't understand why your playing as GDI when it's supposed to be a nod mission.

**Comment by pchote** [comment]
The player definitions on these missions appear to be missing `LockFaction: True`, which means that the faction is randomly chosen - sometimes Nod, other times GDI.
