### ISSUE TITLE
Flame tower does not autoattack enemy units, nor does the AA gun, but the Tesla coil does

### ISSUE THREAD

**Issue by fusion809** [OpenRA/OpenRA#17691]
## Issue Summary
Simply put, under commit 4203a3191f987823083e75c8fe0ee29d157143ac flame towers and AA guns do not auto-attack enemy units (namely infantry and air units, respectively), although strangely Tesla coils do. 

## Reproduction
Load this replay and observe how AA guns and flame towers do not seem to auto-attack, they attack later, but only because I order them to:

- [replay-20200216.zip](https://github.com/OpenRA/OpenRA/files/4209469/replay-20200216.zip)

**Comment by pchote** [comment]
This is going to be a regression from #17619.
