### ISSUE TITLE
Failed to initialize hardware cursors. Falling back to software cursors.

### ISSUE THREAD

**Issue by BestDistress** [OpenRA/OpenRA#17713]
6 players - 2 human (1 MacOS; 1 Windows 10); all on Release 20200202 playing Red Alert.

Playing Bombardment Islands; although it happens on other maps as well. Causes a full lockup of the game; debug log shows:

Failed to initialize hardware cursors. Falling back to software cursors.

Error was: Failed to create hardware cursor `repair` - Failed to create cursor: CreateIconIndirect(): The parameter is incorrect.
[debug.log](https://github.com/OpenRA/OpenRA/files/4239627/debug.log)

**Comment by pchote** [comment]
Thanks for the report. We are tracking this issue in #10172, so closing as duplicate.
