### ISSUE TITLE
macOS: suppress shortcut cmd+Q

### ISSUE THREAD

**Issue by drunsinn** [OpenRA/OpenRA#17725]
The default key combination for terminating applications under macOS is cmd+Q. In OpenRA, the key combination cmd+<number key> combines units into a group.
This can lead to a premature end of the game.

In the hotkey settings the key combination for cmd+Q can be assigned, but it will always terminate the application.

The key combination should be intercepted to prevent the application from being terminated without asking. Alternatively, a dialog should be displayed asking if you really want to quit the application.

**Comment by ghost** [comment]
@drunsinn I'm thinking of having a go at making this happen.  My thoughts are that perhaps Cmd + Q should only be blocked if you're in a game or map editor, etc..  Or to look at it the other way around, Cmd + Q would still work if you're in the menus.

**Comment by drunsinn** [comment]
I think that would be a good solution!
When the user is not in a game there is no progress that could be lost by accidentally exiting the application . 👍

**Comment by ghost** [comment]
I've provided an implementation in pull request #18438

**Comment by ghost** [comment]
The pull request implementing this was merged. In the end it was easier to just always suppress Cmd + Q
