### ISSUE TITLE
Unable to close game window by clicking on close button

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#17739]
## Issue Summary
When running in windowed mode the game window won't close when clicking on the close button. The game keeps running. Hitting <kbd>Alt</kbd> + <kbd>F4</kbd> works though.

OS: Windows 7
OpenRA version: bleed

Bisecting leads to ce8112fb5a1f6ee915ec25f701a1a06d385eef1a.

## Reproduction
Start the game in windowed mode. Click on the button that closes the window.

## Expected behavior
The game window should close, terminating the application.

## Screenshots / Screen recordings / Replays
![uC277sOVxT](https://user-images.githubusercontent.com/1355810/75616503-913b7a80-5b5a-11ea-8155-e794d80c23d1.gif)

**Comment by pchote** [comment]
No repro on macOS.

Do you have similar resposiveness issues with the minimize and restore buttons? The latter is a known problem when the threaded renderer is enabled under Windows, although we are at a complete loss as to why.

**Comment by dragunoff** [comment]
The minimize button works fine. I just noticed that closing from the context menu and the window menu doesn't work either.
![6tk0nvHtTw](https://user-images.githubusercontent.com/1355810/75616673-cc3ead80-5b5c-11ea-9f6f-80fffa098056.gif)

**Comment by abcdefg30** [comment]
I can't reproduce this on Windows 10 either.

**Comment by Mailaender** [comment]
Works fine on KDE/Linux.

**Comment by dragunoff** [comment]
Probably specific to an OS/hardware combination. Oddly enough it's not happening on playtest-20200303. And I also noticed that the window of the dev versions has thicker borders:
![openra-window-borders-win7](https://user-images.githubusercontent.com/1355810/75826173-92b1b080-5daf-11ea-91c0-cd29a44423a2.png)

**Comment by pchote** [comment]
The only recent change that could affect that is #17640 - try cleaning and refetching dependencies on bleed.

**Comment by dragunoff** [comment]
Cleaning and refetchting fixed it. Sorry for the false bug report.
