### ISSUE TITLE
Blurry dropdown arrow sprites

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#17740]
## Issue Summary

Dropdown arrow sprites are blurry. 

OS: Widows 7
OpenRA version: bleed

Bisecting leads to de4a7cecf0719aa3249eec5222ed78e5fa53b3df.

## Screenshots
![dropdown-arrows-blurry](https://user-images.githubusercontent.com/1355810/75616571-38201680-5b5b-11ea-8a92-90e6e72f2a6c.png)

**Comment by pchote** [comment]
This was caused by a conflict between the changes in  62af58c2e6a678e2da387277aa936b8801884191 and de4a7cecf0719aa3249eec5222ed78e5fa53b3df, which together cause the sprite to be offset by a half a pixel and therefore blur.
