### ISSUE TITLE
Falling Snow (Dust Assumed) Disappears on Zoom/Pan

### ISSUE THREAD

**Issue by augustus8825** [OpenRA/OpenRA#17757]
## Issue Summary

On maps like ‘Nuclear Winter’ the snow that falls can disappear when you zoom in/out or pan the map.

## Reproduction

Start a match on Nuclear Winter and zoom in and out or pan the map. The falling snow will disappear. I haven’t tested this on other maps with similar weather effects yet.

## Expected behavior

Falling snow/dust should stay despite zooming/panning the screen.

**Comment by pchote** [comment]
This was missed when overhauling the annotation rendering. This should be an easy fix which i'll PR tonight.
