### ISSUE TITLE
[playtest-20200301+] Firing rifle soldier is uncrushable

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#17755]
Detected when testing #17754.

![openra_crush_bug](https://user-images.githubusercontent.com/1614714/75699999-76841580-5cc2-11ea-83f6-b04027ec5687.gif)

**Comment by pchote** [comment]
Regressed by 85a5b6cc1747899ef067b1027148fd817924af69.

This affects all crushing, not just units that are firing.
