### ISSUE TITLE
[playtest-20200301] Turreted units don't stop to attack targets if acquired

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#17751]
Demos were recorded for Assault Move command, but a simple Attack Move on Defend stance is also sufficient to reproduce the issue.

Current release behaviour:
![openra_tanks_assault_old](https://user-images.githubusercontent.com/1614714/75631824-390e8200-5c07-11ea-8eb0-dedc838071eb.gif)

Playtest behaviour:
![openra_tanks_assault_pt](https://user-images.githubusercontent.com/1614714/75631829-3f9cf980-5c07-11ea-9d9a-41fa0dc01932.gif)

**Comment by pchote** [comment]
Probably caused by #17619.
