### ISSUE TITLE
[playtest-20200303] Hint is drawn below UI (when editing hotkeys)

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#17764]
Hint is only displayed when text for hotkey combination doesn't fit the box, which is the case on the screenshot.

![image](https://user-images.githubusercontent.com/1614714/76013285-b8ae9080-5f28-11ea-873d-e21361622267.png)

**Comment by dragunoff** [comment]
Only happens when in-game. I had the same issue here: https://github.com/OpenRA/OpenRA/pull/16590#discussion_r287606935
