### ISSUE TITLE
Tablet input not working correctly after SDL2 update

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#17766]
I use a Wacom tablet and the input is not working correctly after the SDL2 udpate (8d23994a045709094476f149125f34d7a83963e7). So far only tested on Windows 7.

The issue is that clicks don't register correctly - clicking once registers as a hover. Sometimes it gets stuck in the mouse-down state. I have to spam click to get an actual click.

![yTbdqRwVHC](https://user-images.githubusercontent.com/1355810/76029111-827b0c00-5f3c-11ea-82b1-573e84a7d4d9.gif)

EDIT: In fulscreen mode no clicks are registered at all. And in RA even cursor movement is not picked up.

**Comment by abcdefg30** [comment]
Is that a thing we can fix on our side, or just a SDL bug?

**Comment by hathlife** [comment]
My Intuo PT M (CTH690) perform correctly with latest commit on win10 1909. May be win7 compatibility problem.

**Comment by dragunoff** [comment]
I can no longer reproduce this on Windows 7 and it doesn't happen on Linux.
