### ISSUE TITLE
A half-finished translation function branch needs evaluating and suggestion

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#17793]
Hi, here. Some of my friends who forcus on translation moudle for OpenRA has finished coding translation part in openra in code (except LUA translation for mission text so half-finished). [The repository](https://gitee.com/CastleJing/OpenRA_Src) is on gitee instead of github so you can not see here by now. I will describe his design biefly here, and if you think it is worthy and maintainable to merge into "bleed" then I will push this branch in github to further evaluate and see if we can get a merge here.

A `Translator` class is made to read localization text ( in each mod's "language" folder as YAML) and fonts information, and when `intializeMode()` in `Game` , a instance of  `Translator` is created and get data from `ModData`. 
![note1](https://user-images.githubusercontent.com/13763394/76394983-571b7580-63b1-11ea-88e3-91290b78a320.jpg)

After this the `FileLoader` will read and return fonts to `Translator`.
![note2](https://user-images.githubusercontent.com/13763394/76395013-67335500-63b1-11ea-94bc-1d0ee2d0ef38.jpg)

Then a new tab "language" is created in UI and when people change it, it will require a game restarting to set the language.
![UI](https://user-images.githubusercontent.com/13763394/76395549-88e10c00-63b2-11ea-8c4b-d107795bb30d.png)

In addition, this branch includes a new font  ("Source Han Sans", free for commercial use so I guess it is ok for gpl 3.0) file for the localization we are working on.

**Comment by dnqbob** [comment]
~~However, the because `[translate]` is unusable here so in some place, my friend has to use regular way to load localization text from the `FileLoader`~~

fixed now

**Comment by Mailaender** [comment]
https://gitee.com/CastleJing/OpenRA_Src has commit messages in Chinese and when you click on a commit or the source code, it requires registration, so no one can be expected to review it. See https://github.com/OpenRA/OpenRA/pull/18965 for an alternative approach.
