### ISSUE TITLE
Clicking the Directory dropdown on Save Map screen freezes the game.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#17797]
I noticed this on RV first while trying to add something to the shellmap. Tested on the playtest-20200303 RA mod too, also happens there.

**Comment by abcdefg30** [comment]
Odd, I can't reproduce it on bleed or prep. You only opened the shellmap, then went to save it and opened the directory dropdown, nothing more?

**Comment by MustaphaTR** [comment]
Yes, that's exactly what i did. I just tested on bleed too, also happens there.

**Comment by Mailaender** [comment]
Can't reproduce either. What happens when you rename your OpenRA support folder?

**Comment by MustaphaTR** [comment]
It doesn't freeze when i add a local Support folder. I think something getting blocked while trying to access the user folder in My Documents. Might be a regression from #16587.

**Comment by Mailaender** [comment]
Try https://support.microsoft.com/en-us/help/4028485/windows-10-add-an-exclusion-to-windows-security or whatever anti ransomware solution you are using.

**Comment by MustaphaTR** [comment]
My Anti-virus already has my OpenRA folder whitelisted and adding the OpenRA user folder too doesn't fix it.

**Comment by Mailaender** [comment]
Also to the ransomware protection?

![Manage Ransomware Protection ](https://www.ghacks.net/wp-content/uploads/2019/08/How-to-enable-Ransomware-Protection-2.jpg)

**Comment by MustaphaTR** [comment]
This is what i see on the on that page, my Windows Defender is disabled:
![resim](https://user-images.githubusercontent.com/7933210/76749379-750c2000-678d-11ea-9b55-7b8eb1e73416.png)

**Comment by Mailaender** [comment]
What happens if you disable Avast Antivirus?

**Comment by pchote** [comment]
I just saw a freeze when clicking on the "Control Scheme" dropdown, and IIRC @dragunoff mentioned seeing this too when clicking on the full-screen display dropdown.

It seems this is a problem with dropdowns in general, not the map editor and not related to antivirus.

**Comment by pchote** [comment]
Regression was introduced by de4a7cecf0719aa3249eec5222ed78e5fa53b3df.
