### ISSUE TITLE
TD, bleed: bad AFLD rallypoint

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#17820]
Incomming units stay on airfield. Dropship flys circles if that spot is occupied.
On bleed.

![grafik](https://user-images.githubusercontent.com/25386322/77124026-0c999900-6a42-11ea-869c-74701912bde8.png)

**Comment by abcdefg30** [comment]
Units are nudged out of the way for me. Is there some special reproduction case where units don't move out of the way when a new delivery is incoming?

**Comment by abcdefg30** [comment]
I tried https://github.com/abcdefg30/OpenRA/commit/d1c0f5a52c4041f70dd64e9d629492877daebc3e
![grafik](https://user-images.githubusercontent.com/7704140/77150699-c7528700-6a94-11ea-8a7e-ceadbf016ca0.png)
but that only defers the problem: The first unit moves off the airfield to the rally point and then blocks the second unit from moving off directly. The third unit will nudge them out of the way but have the delivery plane make two circles.
Not sure what we can do to avoid this (or if we want to).

**Comment by pchote** [comment]
We can fix this by properly (and finally) implementing correct/multiple exits for the airfield so it behaves like everything else.

**Comment by fruestueck** [comment]
> Units are nudged out of the way for me. Is there some special reproduction case where units don't move out of the way when a new delivery is incoming?

They are nudged out of the way properly. There is no special way to reproduce it. Just start any game and build  a afld unit.

Each unit arriving stays on the airfield (after pusing the previous away - and that results in dropships flying circles). The first unit doesn't depart as well.

**Comment by AoAGeneral** [comment]
Only thing I was able to do was build an airfield up against a cliff. Unit stops on that spot. When the C17 flies in it circles but ends up nudging the unit aside.

EDIT: Nevermind. Got it to happen here in the playtest version. Off first airfield in replay https://www.dropbox.com/s/n4odwah6raj651x/Airfield%20Stuckage.orarep?dl=0
