### ISSUE TITLE
What about WEB platform support?

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#17836]
https://www.reddit.com/r/openra/comments/fmcke2/managed_to_get_openra_running_in_the_browser/

**Comment by pchote** [comment]
Questions like this are best asked in the Discord or IRC channels.

To answer: the comment describing the video explains that the `mono-wasm` cross compiler generates code that only runs at 1-5 FPS, and that they don't believe this to be fixable.

**Comment by Joelius300** [comment]
Do you think this won't ever be an option? .NET 5 will allow targetting WebAssembly and as part of Blazor WebAssembly, a fine tuned wasm mono runtime exists, which might be able to bring better performance than the cross compiler `mono-wasm` which was used here. Also through Blazor WASM, Microsoft will keep improving C# -> WASM capabilities and performance.  
Even if it won't be part of the official development for now, I think this would definitely be an area worth exploring once .NET 5 hits.

**Comment by firsturdiev** [comment]
Maybe it's time to rethink about it

**Comment by Starkakrats** [comment]
Hello. I found that rosebud ai has a WebAssembly port of openra: https://rosebud.ai/play/openra.
They have a blog about it: https://lab.rosebud.ai/engineering/porting-openra-to-the-browser. But they do not provide the source code, even the compiled assets.
