### ISSUE TITLE
[TS] Wrong offset for rendering the subterranean radar rotating line

### ISSUE THREAD

**Issue by sorcerer86pt** [OpenRA/OpenRA#17842]
## Description

When checking the subterranean radar, the line that rotates is at wrong offset, and thus ruins the visual effect.

## Reproduction
Launch TS, and progress until you can build the subterranean radar unit, and deploy it. Check it's coverage.

## Expected behavior
Line centered at middle, rotating, and the extremity of the line touching the circumference line

## Screenshots / Screen recordings / Replays
![Base Profile Screenshot 2020 03 24 - 11 38 45 22](https://user-images.githubusercontent.com/11853415/77431714-fe96a000-6dd4-11ea-9a30-fcf0d61c0eb3.png)

[video of radar coverage](https://drive.google.com/file/d/1JqrqitoTHKVEmUuTRlYvQjHOsziR2_M5/view?usp=sharing)

**Comment by pchote** [comment]
This will be another regression from the annotation renderable changes.

**Comment by sorcerer86pt** [comment]
Ah okay, i see.
