### ISSUE TITLE
[playtest-20200303] Map editor: player spawn delete/copy bug

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#17867]
`mpspawn` actor info persists somewhere on undo/redo queue when the actor gets copied and/or deleted. 

When `mpspawn` is deleted (with right-click), it is still seen on the minimap, and you get it back when copying a patch with its location.

https://youtu.be/PM46W0_xbX0

**Comment by pchote** [comment]
The issue appears to be that #16900 added special case logic when adding the spawn point actor, but forgot to add corresponding special case logic to clean up after deleting it. This leaves stale data in the cellmap, which is used for rendering the radar and for copy/paste.
