### ISSUE TITLE
Google DeepMind AlphaStar AI for OpenRA

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#17869]
Hi !

I searched in this repository but I found nothing related.
The Idea/Whislist template was quite not applicable to this "issue" so I replaced all the text.

First of all I love OpenRA, I play since few years.

I see there are plenty of commits, issues, pull requests and debates about AIs in OpenRA.

Some of you have probably heard about AlphaStar, the AI developed by Google for Starcraft 2 :
https://deepmind.com/blog/article/alphastar-mastering-real-time-strategy-game-starcraft-ii

To sum up :
- AlphaStar is multiple agents who fought against each other
- The agents fought "in memory" for about two weeks, these two weeks representing around two centuries in real time
- AlphaStar is now a GrandMaster player in Starcraft 2 (which is the highest level), for all three races, and is able to beat professional gamers

At this time AlphaStar is still playing on the Starcraft 2 ladder :
https://www.youtube.com/watch?v=GltEFJIAhbQ

I'm a developer but I've never studied deep learning, so do you think it's possible to implement a DeepMind AI for OpenRA ?

The main problem is that it's probably not easy to implement, but on the other hand all issues, bugs and so on regarding the AI would "vanish" as it would deep learn and self optimize ?
For example, an agent stuck because of pathfinding issues or lack of agression could be beaten by some other "better" agent and automatically replaced.

It's more a question than a feature request so feel free to close this if it's beyond OpenRA's goals.

Thanks !

**Comment by PunkPun** [comment]
I'm not one of the devs but what Google DeepMind is really impressive. It took tremendous investment and talent to achieve. OpenRA simply doesn't have the resources to do the same, so it is very unlikelly for this to happen in the near future. 

However as the AI field is progressing fast and at an increasing rate we might see more technology emerge that would enable us to use deep learning AI for such complicated games as OpenRA mods for significantly less resources

**Comment by WalterBarrett** [comment]
An additional problem is that OpenRA isn't finished yet. There's a good chance that an AI player could rely on a strategy that doesn't work anymore, or rely on pathfinding to work the way it does in previous versions, etc. That would require retraining the AI, and the AI would take a long time to retrain.

**Comment by ghost** [comment]
Yes you are right.
I've seen multiple guides, tutorials and videos about implementing reinforcement learning in software such as rts games (https://www.tensorflow.org/guide and others).
It would be more like a complete independent project than some sort of mod or extension for OpenRA.
I close this issue because it's beyond the development of OpenRA.
Even if someone looks into this it may not be for the next few years.
