### ISSUE TITLE
Cargo>EjectOnDeath can cause desyncs

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#17863]
In RV destroying an occupied Battle Bunker in a MP game can crash the game with a desync. I debugged the cargo code and found the following, copy pasting from Discord:
> It seems like it doesn't/can't calculate the `CurrentAdjacentCells` as the unit dies, because actor's CenterPosition is null. Causes creation of an Invalid Target and ends up with an empty `CurrentAdjacentCells` which kills the units instead of unloading. But, if the `CurrentAdjacentCells` was already calculated and cached for another reason (hovering over the building calculates that to get Unload cursor). `CurrentAdjacentCells` will have values in it and the units will unload. But in a MP game this may be cached for a player and not for the other. If that's the case game tries to kill the units on one side and unload them on other, desyncing the game.

> I think the fact that we couldn't reproduce this on upstream (after adding EjectOnDeath: true to PillBoxes) was the initial cargo and maybe a bit of luck, we might've triggered it initially but we went for trying to unload and reload the pillboxes first after first 2 tries.

**Comment by abcdefg30** [comment]
https://github.com/OpenRA/OpenRA/pull/20515 was reverted in https://github.com/OpenRA/OpenRA/pull/21507
