### ISSUE TITLE
The color validator prevents picking some preset colors

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#17874]
![image](https://user-images.githubusercontent.com/1614714/77948169-a62c3a80-72cd-11ea-8ddf-6ed1718f9e67.png)
Top-left (pink) and bottom-right (black) colors are on the palette, but can't be picked. Both "could not be adjusted enough".

![image](https://user-images.githubusercontent.com/1614714/77948470-20f55580-72ce-11ea-8bd1-af618e02835f.png)
The color highlighted above can be picked, but is *slightly* adjusted into allowed range. Black can't be picked.

For the sake of testing, D2K situation is the same as RA.

Another observation is that if a color was automatically readjusted, it gets randomized next time the map is changed.

**Comment by KOYK** [comment]
I wish mod.yaml preset colors could completely overwrite color validator. That will allow to add the original colors that TD used on multiplayer. And allow mod authors to have full control over the preset colors.

**Comment by abcdefg30** [comment]
Actually reopening since I think it is a valid request to have predefined colors being whitelisted.

**Comment by pchote** [comment]
That really should have its own issue, IMO. It is a feature request rather than a bug, and would require order changes that we really don't want to put into a final playtest.

**Comment by abcdefg30** [comment]
Ok, done as #17941. I didn't mean to have this on the milestone, just forgot to remove this issue from it.
