### ISSUE TITLE
Move Limit Build Area from MapBuildRadius into LobbyPrerequisiteCheckbox

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#17873]
## Motivation
Area build limit can have tremendous impact in user mods, and the ability to balance this is vital, conditions (via GrantConditionOnPrerequisite) and\or Prerequisites, will help to control that aspect.

In my case I have a unit that works as an outpost for some time now, and I had to use the following solution, all this time: 
*NOTE look at the description provided on the LobbyPrerequisiteCheckbox*
```
LobbyPrerequisiteCheckbox@OUTPOST:
	ID: outpost
	Label: Outpost
	Description: Enables the Outpost unit, best used with "Limit Build Area" ON
	Enabled: False
	DisplayOrder: 10
	Prerequisites: outpost_on
```
And
```
MOV:
	Buildable:
		Prerequisites: ~outpost_on, ~anyfix, ~techlevel.medium
		Queue: Vehicle.GDI, Vehicle.Nod, Vehicle.Nodda
		Description: Deploys into an Outpost.\n  Unarmed
```
In my perspective this gives the feeling of duck-taped feature. 
Also Area build limit not providing Prerequisites or conditions, prevents further balance solutions and **new features**.

## Proposed solution

Move Limit Build Area from MapBuildRadius into LobbyPrerequisiteCheckbox

## Side effects

None

## Alternatives

Not worth mentioning.

**Comment by pchote** [comment]
A simple alternative would be to add an option for `MapBuildRadius` to grant a condition on the world actor when it is enabled, which can then toggle `ProvidesPrerequisite` for all players.

**Comment by KOYK** [comment]
It wont be fixed\added, closing it.
