### ISSUE TITLE
Sometimes when quitting the game openra starts a redundant process that doesn't let me open the game

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#17888]
On macOS after a crash or on quitting the game, openra starts a redundant process, that doesn't let me open the game until I stop it with an external tool such as activity monitor or restart pc

![Screen Shot 2020-04-01 at 18 06 48](https://user-images.githubusercontent.com/37534529/78153991-60de4900-7444-11ea-85dd-d38e7b1cf2fc.png)

It has been like this for what it seems an eternity. I forgot to report it earlier

**Comment by PunkPun** [comment]
![Screen Shot 2020-04-01 at 18 21 12](https://user-images.githubusercontent.com/37534529/78155024-9fc0ce80-7445-11ea-99a3-5c9cb568afa3.png)


![Screen Shot 2020-04-01 at 18 22 12](https://user-images.githubusercontent.com/37534529/78155153-c4b54180-7445-11ea-847d-1e5038ce5152.png)

**Comment by pchote** [comment]
Can you please test whether https://github.com/pchote/OpenRA/releases/tag/devtest-20200413 fixes the issue?

**Comment by PunkPun** [comment]
The "Reopen" button does not reopen the game, but the issue described above is gone

**Comment by pchote** [comment]
This dialog shouldn't be appearing at all! The fix was supposed to suppress it...

**Comment by pchote** [comment]
I have generated a new build at the same link as above. Can you please give it another try?

**Comment by abcdefg30** [comment]
What is the status here?

**Comment by PunkPun** [comment]
status is probably here #17887. This issue is false, this process bug was happening all the time in the past, but now it appears very rarely. It is not connected to the reopen button and seems to have only been a correlation

**Comment by PunkPun** [comment]
I cannot reliably reproduce it

**Comment by pchote** [comment]
Can you please test the old https://github.com/OpenRA/OpenRA/releases/tag/release-20190314 and report whether you can reproduce this or #17887 at all?

Our second easiest option (the easiest is to drop support completely) to maintain support for 10.9-10.12 after changing our default target to .NET core will be to package a separate Legacy-OSX build that relies on a system mono install, like we used to do before release-20191117.

**Comment by PunkPun** [comment]
I can't reproduce it, and when I write /crash I get only the popup by openra. The one done by macOS doesn't show up
