### ISSUE TITLE
When quitting playtest a fatal error popup appears

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#17887]
On macOS I get 2 tables when I quit the game in any way
![Screen Shot 2020-04-01 at 18 06 41](https://user-images.githubusercontent.com/37534529/78153559-dd245c80-7443-11ea-915a-e0521145180e.png)
![Screen Shot 2020-04-01 at 18 06 48](https://user-images.githubusercontent.com/37534529/78153564-ddbcf300-7443-11ea-819f-efd6c93bf331.png)

**Comment by pchote** [comment]
Can you please open a terminal, run `/Applications/OpenRA\ -\ Red\ Alert.app/Contents/MacOS/OpenRA` (replace `/Applications/` with wherever OpenRA is installed) to launch the game, quit it, and copy the contents of the terminal output here?

**Comment by PunkPun** [comment]
```
AL lib: (WW) 32 Sources not deleted
2020-04-02 16:15:34.649 OpenRA[2864:280640] launchgame exited with code 11
```

**Comment by pchote** [comment]
Can you please run `MONO_LOG_LEVEL=debug /Applications/OpenRA\ -\ Red\ Alert.app/Contents/MacOS/OpenRA > ~/openra.log 2>&1`, exit the game as soon as you see the main menu, and upload the `openra.log` file in your home directory (warning: will have ~80K lines) here?

**Comment by PunkPun** [comment]
here it is [openra.log](https://github.com/OpenRA/OpenRA/files/4421679/openra.log)

**Comment by pchote** [comment]
Can you please test whether https://github.com/pchote/OpenRA/releases/tag/devtest-20200413 fixes the issue?

**Comment by PunkPun** [comment]
Partially, now only "Red Alert quite unexpectedly" table pops up

**Comment by pchote** [comment]
I have generated a new build at the same link as above. Can you please give it another try?

**Comment by PunkPun** [comment]
Nothing changed from the last version

**Comment by pchote** [comment]
This means that I don't understand what is actually wrong here, so unfortunately won't be able to fix it. Something inside the `mono` binary is causing the macOS crash dialog to appear (but only on 10.12, AFAIK) and return an exit code of 11. Suppressing the exit code on our end is not sufficient to prevent the dialog.

**Comment by pchote** [comment]
@Punsho do you see the same errors when compiling and running from source using a system mono install, or only in the packaged apps?

**Comment by RobFog** [comment]
@Punsho Are you still getting the crashes with the latest release version? I reported #18048.

**Comment by PunkPun** [comment]
> @Punsho Are you still getting the crashes with the latest release version? I reported #18048.

Yes

> @Punsho do you see the same errors when compiling and running from source using a system mono install, or only in the packaged apps?

I missed this, only packaged. When I compile bleed it works perfectly

**Comment by RobFog** [comment]
> > @Punsho do you see the same errors when compiling and running from source using a system mono install, or only in the packaged apps?
> 
> I missed this, only packaged. When I compile bleed it works perfectly

Ah, that is interesting. And hopefully, it makes the issue easier to figure out. :-)
