### ISSUE TITLE
Game crashes when trying to open a map with the editor

### ISSUE THREAD

**Issue by WhoCaresora** [OpenRA/OpenRA#17895]
## System Information

- Operating System:  win10
- OpenRA Version: playtest-20200329
- OpenRA Mod: RA

## Exception log

```
OpenRA engine version playtest-20200329
Red Alert mod version playtest-20200329
on map 848518edffb519f3c3ef552234230bbe11b4fda3 (Agenda 2v2[AR] by WhoCares).
Date: 2020-04-03 10:45:50Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.ArgumentException`: Un élément avec la même clé a déjà été ajouté.
   à System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   à System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   à OpenRA.Primitives.SpatiallyPartitioned`1.Add(T item, Rectangle bounds)
   à OpenRA.Mods.Common.Traits.EditorActorLayer.Add(EditorActorPreview preview, Boolean initialSetup)
   à OpenRA.Mods.Common.Traits.EditorActorLayer.Add(String id, ActorReference reference, Boolean initialSetup)
   à OpenRA.Mods.Common.Traits.EditorActorLayer.WorldLoaded(World world, WorldRenderer wr)
   à OpenRA.World.LoadComplete(WorldRenderer wr)
   à OpenRA.Game.StartGame(String mapUID, WorldType type)
   à OpenRA.Mods.Common.Widgets.Logic.MainMenuLogic.<>c__DisplayClass15_0.<LoadMapIntoEditor>b__0()
   à System.Action`1.Invoke(T obj)
   à OpenRA.Game.LogicTick()
   à OpenRA.Game.Loop()
   à OpenRA.Game.Run()
   à OpenRA.Game.InitializeAndRun(String[] args)
   à OpenRA.WindowsLauncher.RunGame(String[] args)


```

## Additional information

Map can be played but crashes the game when you try to open it in the editor.

**Comment by pchote** [comment]
I expect this to be another regression from #17867.

**Comment by WhoCaresora** [comment]
https://resource.openra.net/maps/33981/

this map and all mod map derivated

**Comment by teinarss** [comment]
> 
> 
> https://resource.openra.net/maps/33981/
> 
> this map and all mod map derivated

This map doesn't exist on RC.

**Comment by teinarss** [comment]
The problem is that the map contains two actors with the same id `Actor176`
```
	Actor176: t01
		Owner: Neutral
		Location: 46,34

	Actor176: mpspawn
		Location: 91,48
		Owner: Neutral
```

**Comment by pchote** [comment]
Possibly related to undo/redo - are we recalculating the actor id when applying the redo action?

**Comment by teinarss** [comment]
`AddActorAction->Do()->EditorActorLayer->Add()` always calls NextActorName().

**Comment by WhoCaresora** [comment]
Sry about the map being out of RC, I made a "spring" cleaning in my uploads and forgot about this. that is wierd, i don't think i edited this map with a playtest having the undo redo.

**Comment by teinarss** [comment]
Then this have nothing to do with undo redo, only that the symptom is showing. 
The fix is to give one of the actors a unique id.

**Comment by WhoCaresora** [comment]
ok, I'll look into the map and fix my yaml.

Sorry for the inconvenience.

**Comment by pchote** [comment]
the question is: how did the duplicate id end up in there?

We should also not crash on duplicate id, and instead treat the second one as an override for the first (usual yaml-merging convention).

**Comment by abcdefg30** [comment]
I disagree. Defining two actors with the same ID is bogus and seeing that this is used for scripting might have unexpected effects. We should crash with a better exception though.

**Comment by pchote** [comment]
at the very least we should be detecting this error and preventing the map from being used in the lobby, like we do for bogus rules. Malicious players should not be able to crash other people by intentionally starting a game with a bad map.

**Comment by pchote** [comment]
@teinarss mentioned that they had a PR ready to go for this.
