### ISSUE TITLE
TD Release v20200202 vehicle stuck on bridge

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#17891]
DESCRIPTION
Nod buggy stuck at bridge South East in replay

STEPS TO REPRODUCE THE ISSUE
Repair bridge drive vehicle over.

EXPECTED BEHAVIOR
Drive over bridge.

Replay:

https://www.dropbox.com/s/lrshzzda932d3zt/Bridge%20Stuck.orarep?dl=0

Issue references from:

#9378 - Reported issue
#15025 - Fixed issue.

---

Not sure if it makes a difference but in the issue reported vehicles left a husk then got stuck. In the replay no vehicle is destroyed but got stuck anyways.

**Comment by abcdefg30** [comment]
Closing as stale, please re-open this if it is still reproducible.
