### ISSUE TITLE
[OpenRA.Server] Launch-dedicated.cmd default values crashes on SupportDir

### ISSUE THREAD

**Issue by NenoLoje** [OpenRA/OpenRA#17901]
By default, in the [launch-dedicated.cmd](https://github.com/OpenRA/OpenRA/blob/bleed/launch-dedicated.cmd) file, the following value is defined for `SupportDir`:

```
set SupportDir=""
```

When running OpenRA.Server.exe this results in a DirectoryNotFoundException:

```
Unhandled Exception: System.IO.DirectoryNotFoundException
   at OpenRA.Platform.OverrideSupportDir(String path)
   at OpenRA.Server.Program.Main(String[] args)
```

Screenshot:

![grafik](https://user-images.githubusercontent.com/13981145/78471093-cecd8d80-772e-11ea-994f-9ccacd9ca276.png)

Expected:
- The game should not crash and instead provide a more meaningful error message.

Suggested:
- Maybe we should not just check if the value is empty, but if the value is a valid directory.

**Comment by pchote** [comment]
Can anybody else on Windows reproduce this? The server has a [specific check](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Server/Program.cs#L26) that should be guarding against this being empty.

**Comment by NenoLoje** [comment]
@pchote Yes, there is a check - but it only checks for an empty string and `SET=""` on Windows is not empty, it's actually `""`.

Would you mind if a add a check if SupportDir actually exists? Or is there a scenario, where it could not (yet) exist?

**Comment by pchote** [comment]
> Would you mind if a add a check if SupportDir actually exists? Or is there a scenario, where it could not (yet) exist?

This would be a bad idea in the general case - if the server host tells the server to use a specific directory and that directory doesn't exist then this should be a fatal error. Having it successfully run but using an unexpected directory can lead to harder to debug issues.

We can fix the quoting issues in the cmd file and ideally should report the directory path before throwing the exception.

**Comment by NenoLoje** [comment]
@pchote Agreed on _fatal error_ - but this one is an **_unhandeled_** exception.

Personally, I would not recommend allowing any unhandled exceptions to surface to users - being a fatal error or not, it should be handled.

**Comment by pchote** [comment]
How would you define "handling" an exception in this case? The exception message contains all the important information that is needed to debug and resolve an issue. I don't see what we'd gain by catching the exception and then manually formatting the same output.

**Comment by NenoLoje** [comment]
@pchote I suggest making the error message more approachable to non-developers. There are people who are not very technical and want to set up a dedicated server. When they run into an unhandled exception, it does not really encourage them to continue.

A "DirectoryDoesNotExist" exception might sound clear enough for and me and other devs out there, but a regular user would possibly prefer a different wording.

**Comment by abcdefg30** [comment]
Fwiw, when I use the launch script with no support directory set it doesn't crash on my system.

**Comment by pchote** [comment]
Working fine in my Windows 10 VM too:
<img width="801" alt="Screenshot 2020-04-11 at 18 44 49" src="https://user-images.githubusercontent.com/167819/79050837-947b5900-7c24-11ea-928b-54e9d43e6e41.png">

**Comment by pchote** [comment]
I just noticed that @NenoLoje's screenshot shows the install location for the release build, and can reproduce the crash above by copying the playtest/bleed launch-dedicated.cmd into the release install.

So closing this as already fixed on playtest.
