### ISSUE TITLE
HealUnitsCrateAction doesn't heal (just) units

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#17912]
The current implementation heals all actors, including buildings. The trait should either be fixed or renamed to reflect what it actually does.

IMO the best solution would be to rename it to `HealActorsCrateAction` and add a `TargetTypes` property that can be used to control which actors are affected.

**Comment by abcdefg30** [comment]
Those crates in the original also healed all actors (units), so it would be better to rename the trait if you insist.

**Comment by MlemandPurrs** [comment]
i would prefer having control over what it heals as pchote suggests.

**Comment by MlemandPurrs** [comment]
i just remembered: it might have been good if can use this with an radius, for locally healing units in vicinity instead being global only.
