### ISSUE TITLE
Allied mission 01 doesn't end when Einstein is extracted

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#17926]
Didn't win even though I successfully saved Einstein and his heli left the map.

Could be a more general problem, since there haven't been any real changes to the mission in a long time.

**Comment by Mailaender** [comment]
I last tested it during https://github.com/OpenRA/OpenRA/pull/17911 and it worked fine so it has to be some very recent change.

**Comment by abcdefg30** [comment]
I couldn't reproduce it locally. Are there any specific reproduction steps? Did the mission just not end or did it fail instead of succeeding? (E.g. by Tanya getting killed?)

**Comment by reaperrr** [comment]
Ok, it was on a local branch based on #17910, so that's by far the most likely culprit. Closing for now.
