### ISSUE TITLE
[playtest-20200329] Color picker logs about adjusting the value which is not changed

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#17924]
![openra_color_picker](https://user-images.githubusercontent.com/1614714/79047034-fc2da600-7c1c-11ea-99a5-e4a7f0bcf496.gif)

Testcase - in TD, pick the color №5 from the preset palette and then open/close the picker. Initially it is `B6F706`, changes once to `B9F806` then doesn't change anymore regardless of what is said in the log.

**Comment by netnazgul** [comment]
`F7B3B3` gets flagged, but not changed in D2K.

**Comment by pchote** [comment]
Related to #17874.

**Comment by pchote** [comment]
The issue here is that the colour defaults are specified in RGB but the color picker works in HSL. Converting the (valid) RGB to HSL and back gives a different (invalid) RGB. The validator then adjusts this back to the same (valid) RGB that we started with and the process repeats.
