### ISSUE TITLE
Map options: Crates off. Start of game: 2 circling Badgers are spawned. 

### ISSUE THREAD

**Issue by wippie-openra** [OpenRA/OpenRA#17928]
If you start a game with option Crates Off, the badgers that drop the crates are spawned. They do not have directions, so they just circle at the place of spawn. 

Proposed solution: Do not spawn badgers when crates are turned off

**Comment by pchote** [comment]
Are you sure that you weren't just playing that map that has two circling badgers placed on it by the map author?

**Comment by wippie-openra** [comment]
Youre right. Confirmed by map maker. Issue can be closed.
