### ISSUE TITLE
Trait wiki won't load 90% of the time

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#17942]
As the title says, https://github.com/OpenRA/OpenRA/wiki/Traits won't load for me 90% of the time.
I usually open the cache version of it. But some times even that wont work.
Maybe consider an alternative wiki host?

**Comment by Mailaender** [comment]
See https://docs.openra.net/ for an alternative.

**Comment by KOYK** [comment]
@Mailaender thank you

**Comment by Mailaender** [comment]
You can also use https://github.com/OpenRA/docs/blob/master/api/playtest/traits.md if you want a more plain design. For some reason those have higher timeouts than the wiki.

**Comment by KOYK** [comment]
wow thats even better!! thank you again man
