### ISSUE TITLE
Request: Energy or Mana logic for cooldown abilities

### ISSUE THREAD

**Issue by henskelion** [OpenRA/OpenRA#17958]
Currently there are a few units with an energy/cooldown ability system (most notably the Chrono Tank), however these units use their own logic specific to that unit, making the cooldown system inflexible for modding. Ideally what we could have is something similar to Starcraft/Warcraft unit energy, where certain special abilities cost energy, which slowly recharges over time. This logic would likely require the addition of a dedicated special ability key for units, since while the deploy key could also be tied to using certain special abilities (ie Yuri Clones in RA2 requiring their psi-blast deploy ability to consume energy), this is less than ideal.

While this wouldn't have too many implications for the existing C&C ORA mods, since the classic WW C&C games didn't have energy/cooldown mechanics, this would open up a lot of possibilities for modders.

**Comment by abcdefg30** [comment]
I suppose the current condition system can be used for this: Have a trait granting conditions over time, and the ability traits only enabled once a certain amount of conditions have accumulated (and then some more custom logic to revoke used conditions when activating an ability).

**Comment by pchote** [comment]
Implementing some kind of general mana system that ties in to all of the standard traits, but without any specific design constraints as to how it would work, doesn't seem at all feasible or realistic to me. This IMO is an example of the kind of thing that the SDK mod dll plumbing is perfect for - the mod can design and define its desired behaviour and then implement whatever traits it needs with mana support.

**Comment by KOYK** [comment]
What @abcdefg30 said, also TimedConditionBar trait could help visualize the recharging mana bar I think (ive never worked with it). 

The real problem for such mods wont be the mana mechanic, but the abilities, for example you have a unit that is a wizard, I would dislike to see such a unit not be able to use some short of "spellbook" and only be able to "deploy" one ability (like yuri).

The command and conquer games that had the game mechanic for units to use multiple abilities was Generals-ZH and C&C 3 TW-KW.

A similar system like that will solve a lot of modding problems, and open the doors for new mod ideas. But there is an other problem, who will be motivated to make the code for it.

**Comment by abcdefg30** [comment]
I guess we can close this due to scope and complexity until there are concrete ideas on how the engine needs to change in order to let modders code/create an implementation.

**Comment by abcdefg30** [comment]
I suppose #17823 even gives an example for how to do this.

**Comment by penev92** [comment]
FWIW #17823 provides a pretty specific solution which is insufficient for the general case of actors having "energy" or "mana" and then "abilities" to use it. So far our main excuse for not having that is that the UI is not designed for that, which isn't really great, especially when we're talking about community mods.

> Implementing some kind of general mana system that ties in to all of the standard traits, but without any specific design constraints as to how it would work, doesn't seem at all feasible or realistic to me. 

Working like a second health pool, or even an ammo pool would be generic enough (if we properly supported either of those I guess they could be used as such by the modders directly).
