### ISSUE TITLE
My Multiplayer is freezing constantly

### ISSUE THREAD

**Issue by Y2chaos** [OpenRA/OpenRA#17950]
- Operating System: Windows 10
- OpenRA Version:  20200202

I am having this issue constantly right now.

Intel core i7-7700k cpu @ 4.2GHz, 4201 Mhz, 4 core 8 logical processors.
16GB RAM
GeForce GTX 1070

Half way through a game with mates, slight lag, heavy lag then I freeze. Can still select objects and they audibly respond. I get disconnected from the game and my other two mates can continue fine, I'm stuck on the game map, can scroll anywhere. but nothing is moving, no audio from other battles, just my units etc.

**Comment by pchote** [comment]
The behavior you describe is normal / expected when your network drops. When you lose connection to the server you still have the ability to scroll around and interact with things, but gameplay can't progress past the last state.

**Comment by penev92** [comment]
Sounds like a network issue on the reporting side that we can't do anything about.
