### ISSUE TITLE
Replace hardcoded cell trigger locations by waypoints using ScriptTags

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#17962]
I saw the suggestion on Discord to create an extra system for this, but I think we can already do that (even more flexible) by using `ScriptTags`. I see this as three points:
- Make the map editor visualize existing tags (similar to the debug tags) and tie that to a checkbox
- Expand the actor editor inside the map editor to allow for adding and removing tags
- Actually replace the `CPos` tables by placing waypoints with a respective tag

**Comment by pchote** [comment]
My idea for the visualizations was to have the trigger areas drawn as continuous region with a specific mode for painting/clearing. Using individual actors still has the problem of conflicting with other actors that may be in those cells wrt mouse interaction.

**Comment by abcdefg30** [comment]
Hm, I haven't thought about this, but/since I think this won't be a problem in practice with waypoints. While implementing it as some paint over the map sounds nicer, it will also be more complicated and sounds less flexible to me. (E.g. we still have to handle discrete regions like there are in Exodus.)
Part of this suggestions was that I thought I might extend this to replace some of our manually created tables of enemy actors (something like the lab guards in the first Allied mission).

**Comment by abcdefg30** [comment]
Closing after discussion on Discord.
