### ISSUE TITLE
Allow Bots to sent messages based on their actions\reactions

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#18018]
## Motivation

Well it will be fun

## Proposed solution

Use the debug messages that AI sent and filter them to look like chat messages ie remove details like "searching for cell x to place refinery" and allow only useful ones like I am attacking, I am low in money, I am under attack. Also limit the number of messages that are being sent. 

I am under attack message could be triggered the same way mini map events are being announced, With the addition of a fake message that looks like its coming from the AI.

Low on money message could be triggered by the current amount of money the AI has when it reaches a preset value, with the combination of a timer, for example sent message when AI has less than $100 for 5 min. 

I am attacking could work by using a filtered debug message that only reveals the attacking part of the AI action, without cell coordinates and so on.

An other cool thing could be response and greeting messages, like when the game starts say "good luck have fun", or "good game" at the end of the game. Responses like returning a greeting can be hard to implement since users could spam them by saying hi to the AI repeatedly, unless if they could be triggered once. Those messages could be system messages masked to look like they are being sent from the AI.

## Side effects

Could be hard to implement

## Alternatives

Can't think of any

**Comment by Jushdrug** [comment]
making this somewhat more usefull than constantly anoying players with irrelevant info would be to ping the map and tell the AI's allies important info in the chat like commencing attacks (allowing players to join), sneak attacks and superweapon usage. 

To that end, creating a whole interaction menu might be in order (to control or coordinate with ai).

**Comment by KOYK** [comment]
Never mind, I think this is unrealistic for now. Also other more important PRs have to finish, this could wait for now.

**Comment by abcdefg30** [comment]
We can still keep the issue open for the future.

**Comment by KOYK** [comment]
It wont be fixed\added, closing it.
