### ISSUE TITLE
Weather effect faster with higher framerate

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#18025]
Snow particles move much faster with higher framerate.
Tested with Playtest 20200426 and Releasse 20200503, on 60Hz Monitor, Win10 and over 900 FPS. Also notable with 120 FPS. I guess it's the same with higher refresh rate Panels.

Reproduce:

- Disable VSync and Frame Limiter in Settings
- Start Game on Snow Themed Map with Snow a weather effect
- With 900 Frames the Snow particle jump around

**Comment by reaperrr** [comment]
While this is something we should fix, since it can be worked around with VSync/frame limit this shouldn't delay the next release, so moving to Next+1.
