### ISSUE TITLE
Map editor undo function only undoes one tile at a time

### ISSUE THREAD

**Issue by OmegaBolt** [OpenRA/OpenRA#18027]
For example if you fill a space and hit undo, it will only undo the last tile filled rather than the entire fill action.

Reported as bug because pchote on discord:
> that sounds like a bug

**Comment by markelz0r** [comment]
Is fill action even a thing? By looking into this I can tell that we have  `readonly Queue<UndoTile> undoTiles` but that keeps track of individual cells that are  forming up a tile, but nothing that I could find resembles something like a collection of tiles that we should be undoing

**Comment by pchote** [comment]
Hold shift while placing a tile.

**Comment by markelz0r** [comment]
> Hold shift while placing a tile.

Right, but it looks like there is no specific `IEditorAction` defined for undoing this and we are solely relying upon `PaintCell` adding a new `PaintTileEditorAction` to `editorActionManager`. So in my head this is less of a bug and more the way currently things are although undoing an entire FloodFill should be something relatively easy to implement
