### ISSUE TITLE
Carryall Pickup Loop

### ISSUE THREAD

**Issue by Logicon2020** [OpenRA/OpenRA#18030]
## Issue Summary

Carryall gets stuck in loop while picking up harvesters or vehicles heading to repair bay. The carryall will drop down, then raise back up in a loop leaving the vehicle stuck in place.  The vehicle cannot be stopped or moved by another carryall and only be destroyed.

## Reproduction

Unknown way of reproducing as it's random.  Has happened twice when a harvester has been repaired and is then issued a return to refinery order.  And happens randomly when picking up a harvester from a spice field.

## Expected behavior

Carryall picks up vehicle as normal

**Comment by pchote** [comment]
Can you please upload a replay from one of the games where you saw this happen?

**Comment by abcdefg30** [comment]
I didn't get the exact same result, but should be close enough to see that something is wrong here.
![](https://i.imgur.com/O70sYxl.gif)

Send a harvester to repair but have a unit already on the depot so the harvester gets stuck on the transit-only tile. Then order it to harvest.

Replay for reference: [OpenRA-2020-05-04T165344Z.zip](https://github.com/OpenRA/OpenRA/files/4576028/OpenRA-2020-05-04T165344Z.zip)

**Comment by Logicon2020** [comment]
This is exactly what I mean, thanks!  It seems to bug out/get confused over the repair bay more often than not.

**Comment by pchote** [comment]
The carryall logic will need to be updated to understand the transit-only tiles. It is unfortunate that this wasn't picked up during the playtests.

**Comment by Logicon2020** [comment]
I did actually play with the playtest but didn't think to report it, as I didnt know if anyone else had caught it.

**Comment by Logicon2020** [comment]
That rhymes.. anyway thanks for the help :)
