### ISSUE TITLE
Invalid control group persistent state between carriers and units

### ISSUE THREAD

**Issue by ubitux** [OpenRA/OpenRA#18062]
How to reproduce:

1. produce an APC
2. produce a small group of infantry
3. set a control group on the infantry
4. put the infantry inside the APC
5. move the APC
6. double hit the control group number

Expected result: jump camera to the carrier (or do nothing in the worst case)

Current result: jump camera to the place where units where last seen (that is, when entering the vehicle)

In the case the vehicle is in the same control group as the set of units, it will move the camera in the middle of where units entered the vehicle and where the vehicle currently is. This makes the behavior even more confusing.

Tested with `openra-20200503` but I'm pretty sure it was also the case in previous versions.

**Comment by pchote** [comment]
Sounds like we are missing an IsInWorld check when calculating the target camera position. Should be an easy polish win, so adding to Next + 1.
