### ISSUE TITLE
Display defeated status at sidebar players list too when observing

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#18074]
On the observer UI, perhaps it would be good if we can display this (Lost) there too on the list (see pic)
![defeatedplayers](https://user-images.githubusercontent.com/48881353/81502826-fe9d2180-92e8-11ea-98f7-226bcc317c8b.png)

**Comment by abcdefg30** [comment]
#14491 sounds like the better solution imho.

**Comment by dragunoff** [comment]
Removing dead players from the list indeed sounds like a better solution.
