### ISSUE TITLE
Mine Layer fields can be dragged into the black borders of certain maps, causing the mine layer to become 'stuck'

### ISSUE THREAD

**Issue by Eyes88** [OpenRA/OpenRA#18081]
## Issue Summary

DESCRIPTION
When the user enters into a game and builds a mine layer, they will notice it is possible to hold Ctrl + Right click (for modern control scheme) or Ctrl + Left click (for classic control scheme) to create a dragged mine field. If, however, the user does this on a map with a black border, it is possible for this dragged selection to include the black border. If this occurs, the mine layer will attempt to place mines in the border, but because it is unable to do so, it will simply remain stationary (as the unit AI attempts to reach the area to be mined). As a result, the mine layer will not complete any further actions unless the user interacts with the mine layer directly.

## Reproduction

STEPS TO REPRODUCE THE ISSUE
1. Launch OpenRA build: release-20200503
2. Once the game has loaded, click on the Singleplayer menu option.
3. Click on the Skirmish menu option.
4. Select a map that has black borders (for example, Shadowfiend II [AR]
5. Select the Russia faction (for example) & remove the AI from the game. 
6. Click the Start Game button.
7. Once in the game, build the necessary buildings in order to build a mine layer.
8. Once the mine layer has been built, move it near one of the edges of the map (next to the black border). 
9. Use the mine drag technique mentioned above so that part of the selection is on the black border.
10. Observe the results.

## Expected behavior

EXPECTED BEHAVIOR
The mine drag cannot select areas off the border of the map. Or, if this is not possible, after a few seconds the mine layer should recognise it cannot reach the destination and continue with the rest of the its tasks.

## Screenshots / Screen recordings / Replays

Please see attached video for reference
[Mine Drag Issue.zip](https://github.com/OpenRA/OpenRA/files/4609576/Mine.Drag.Issue.zip)

**Comment by abcdefg30** [comment]
This was fixed by #18101.
