### ISSUE TITLE
Index out of bounds while loading skirmish custom map

### ISSUE THREAD

**Issue by Samunosuke** [OpenRA/OpenRA#18092]
## Issue Summary

The skirmish game crashes on loading my own custom map with a index out of bounds exception.
(Cnc)

## Reproduction

Tested with "release-20200503"

1. Select Skirmish mode
2. Select the map "Rumble in the jungle 2"
3. Choose one cabal bot player on 2nd slot
4. Select the start position "A" for the player
5. Select the start position "G" for the bot
6. Start the game -> the game crashes

## Expected behavior

The game should just start, or the map editor should tell me if something is wrong with the map.
I have chosen 8 Multiplayer positions in the map, I thought this should also work for the skirmish mode, am I wrong?

## Screenshots / Screen recordings / Replays

[rumbleInJungle2.zip](https://github.com/OpenRA/OpenRA/files/4618608/rumbleInJungle2.zip)
[exception-2020-05-12T194406Z.log](https://github.com/OpenRA/OpenRA/files/4618610/exception-2020-05-12T194406Z.log)

**Comment by Samunosuke** [comment]
I have found the OpenRA.Utility which allows to check the map. This tool gives me the following output:
OpenRA.Utility.exe cnc --check-yaml C:\Users\MyUser\Documents\OpenRA\maps\cnc\release-20200503\rumbleInJungle2.oramap
Testing map: Rumble in the Jungle 2
OpenRA.Utility(1,1): Error: Actor Actor683 owner Multi0 is not one of ValidOwnerNames: Neutral
OpenRA.Utility(1,1): Error: Actor Actor956 owner Multi1 is not one of ValidOwnerNames: Neutral
OpenRA.Utility(1,1): Error: Actor Actor1240 owner Multi3 is not one of ValidOwnerNames: Neutral
OpenRA.Utility(1,1): Error: Actor Actor1304 owner Multi2 is not one of ValidOwnerNames: Neutral
OpenRA.Utility(1,1): Error: Actor Actor1420 owner Multi4 is not one of ValidOwnerNames: Neutral
OpenRA.Utility(1,1): Error: Actor Actor1493 owner Multi5 is not one of ValidOwnerNames: Neutral
OpenRA.Utility(1,1): Error: Actor Actor1563 owner Multi6 is not one of ValidOwnerNames: Neutral
OpenRA.Utility(1,1): Error: Actor Actor1604 owner Multi7 is not one of ValidOwnerNames: Neutral
OpenRA.Utility(1,1): Error: Actor Actor1753 owner Multi8 is not one of ValidOwnerNames: Neutral
Errors: 9

What does this mean? How can I place buildings on the map which are by default owned by the player of the respective spawn point? Is this even possible without touching the "yaml" file by hand?

**Comment by abcdefg30** [comment]
This means that your "mpspawn" actors are owned by a playble player and not by the Neutral player. That results in spawns not being created when the respective player slot is not filled. Most likely your crash is exactly because of that. Try changing the owner of those "mpspawn" actors to Neutral.

**Comment by Samunosuke** [comment]
I am sorry, I misunderstood how this works. I really thought I have set the "spawn" point to the same owner as the bases I have prepared for them on the map.
Why is it possible to change the owner of a "spawn" point to multi0 or multi1...?
If this should not be possible and it just causes troubles like I had, then I would recommend it to lock this function for a spawn point.

**Comment by markelz0r** [comment]
I think we could handle this better anyway in `WorldLoaded` rather than crash the game. I am not sure if we can recover from this error though and carry on since there will be a mismatch between available `spawns` and `SpawnPoint` requested

**Comment by PunkPun** [comment]
Should we call this user error and won't-fix?

**Comment by abcdefg30** [comment]
We have `RequiresSpecificOwners` now.
