### ISSUE TITLE
Carryall should able to grant a condition to self while being carrying an actor

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#18105]
Carryall can be sold on Service Depot while carrying a vehicle, causing the unit its carrying and self to disappear, wasting the value of carried unit. Have to prevent that and carryall trait doesnt have any condition for granting to self while carrying something. So i can suggest adding an field that functions similar to the LoadedCondition of Cargo trait.

In my RA based mod, made Chinooks able to carry select few light Vehicles. At the same time made it so that Vehicle and Aircraft can get sold when docked on the Service Depot for half their value.
Now if an Chinook docks on the Service Depot while carrying an Vehicle it can be sold for its own value, wasting the value of carried unit.
On APC's managed to prevent getting sold when on FIX via utilizing the loadedcondition.
For Carryalls this was not possible due to lack of condition to grant to self while carrying something.

**Comment by pchote** [comment]
We should also add `INotifySold` handling to match `Cargo`.
