### ISSUE TITLE
RA: Concrete wall gets placed on the helipad

### ISSUE THREAD

**Issue by VonNah** [OpenRA/OpenRA#18115]
![glitch](https://user-images.githubusercontent.com/65423234/82094345-650cb000-96ec-11ea-890b-0eb708092aca.png)

In the process of the helipads build animation, the player placed a concrete wall on the same tile that was occupied by a cell of the helipad. The replay file is available in the OpenRA discord bug-reporting channel.

[replay_Hpad_glitch.zip](https://github.com/OpenRA/OpenRA/files/4637151/replay_Hpad_glitch.zip)

**Comment by Smilex** [comment]
I was not able to reproduce this in the dev version. Maybe I misunderstood, but I played on the slowest speed and while the helipad was building, I tried to build a wall inside the helipad

**Comment by Smittytron** [comment]
Reverse duplicate #18186
