### ISSUE TITLE
Idea: walls should block line-of-sight

### ISSUE THREAD

**Issue by praetp** [OpenRA/OpenRA#18113]
Static defences such as mines, fences and walls are an underused feature of the game.
Walls could be more useful if they would block the line of sight for all vehicles and infantry (but not aircraft). It makes sense: after all, you cannot look over a wall.

Maybe this is hard to implement as I don't think we have any precedent where a unit's native line of sight is masked.

**Comment by pchote** [comment]
IMO this would be too much of a gameplay departure for the C&C-based mods, but could be an interesting feature for community mods to explore.

**Comment by Smittytron** [comment]
Closing as wont-fix. We won't be doing this in official mods.
