### ISSUE TITLE
Redesign ActorInit implementation

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#18118]
Our current ActorInit implementation goes right back to the very early days of the engine, and really isn't fit for the purposes that we would like to use it for.

The main limitation comes from supporting only one init of each type, which necessitates awkward bespoke workarounds for turrets and plugs, and no ability to specify e.g. multiple health states once @reaperrr's per-hitshape health work is merged. There is also very limited interop between runtime-initialized state vs yaml-initialized state - e.g. `ParentActorInit` or `ChronoshiftChronosphereInit` which reference actors aren't supported from yaml.

These two points are major blockers for direct save/load support in the future, and limit what we can do in the map editor and initial map state.

I have prototyped a new implementation that resolves these issues by assigning meaning to our currently arbitrary @ suffix labels on traits. *Inits can be labelled with the same suffix in `map.yaml` or Lua to direct them to a specific trait. Inits tagged with an instance label will only be used by that trait, but labelled traits can fall back to unlabelled inits if a more specific init is not available.

Example syntax in map.yaml:
```
Actor93: ca
	Location: 20,86
	Owner: Allies
	Facing: 64
	TurretFacing: 0
	TurretFacing@PRIMARY: 128
	ChronoshiftReturn: 100
	ChronoshiftOrigin: 30,90
	ChronoshiftChronosphere: Chronosphere
```

This will create a cruiser with a primary turret facing of 128 and a secondary turret facing of 0. After 100 ticks it will chronoshift back to the defined origin, triggering the animation on the preplaced actor with a map name `Chronosphere`.

The syntax from lua is more awkward thanks to the limitation that @ cannot be used in keys when using the assignment syntax:
```lua
local inits = { Owner = allies, Facing = 64, Location = CPos.New(20, 87) }
inits['TurretFacing@PRIMARY'] = 128
inits['TurretFacing@SECONDARY'] = 0
local unit = Actor.Create("ca", true, inits)
```

I plan to file PRs towards this implementation in the near future so that my next set of PRs to fix the turret facing issues can also remove the `FacingsInit` workarounds.

**Comment by tovl** [comment]
> I have prototyped a new implementation that resolves these issues by assigning meaning to our currently arbitrary @ suffix labels on traits.

There are several traits that define a string yaml parameter (usually called "name") with the sole purpose of linking specific traits to each other (e.g. `Armament`). Would this also be able to replace those?

**Comment by pchote** [comment]
In principle yes, but i'm not yet sure whether we want to do this: the current setup supports multiple traits sharing the same `Name`, which would not be possible under this new system. We would need to be sure that forcing a single name per instance will not break any usecases before making that change.
