### ISSUE TITLE
Allow TS AI to Producess Aircraft

### ISSUE THREAD

**Issue by Alfredlang1989** [OpenRA/OpenRA#18137]
I added planes to the units to be built in the ai.yml. Unfortunately, the TestAI then rebuilds. 

The problem is easy to fix.
Please change the line 28 in the OpenRA.Mods.Common / Traits / BotModules / UnitBuilderBotModule.cs file

public readonly HashSet UnitQueues = new HashSet {"vehicle", "infantry", "plane", "ship", "plane",};

to
public readonly HashSet UnitQueues = new HashSet {"vehicle", "infantry", "plane", "ship", "plane", "air"};

**Comment by abcdefg30** [comment]
You don't need to change the code, but can override those values in yaml. See #18140.

**Comment by Mailaender** [comment]
The unit queues

> Vehicle, Infantry, Plane, Ship, Aircraft

probably shouldn't be hard-coded in this redundant way.
