### ISSUE TITLE
[Idea] In Editor Maps Scripting and Unit Editor

### ISSUE THREAD

**Issue by ben132** [OpenRA/OpenRA#18136]
This is a request for an in editor map scripting.  I was think of this in a way similar to warcraft 3's editor.  But also with the ability to add UI elements via Editor or scripting,

**Comment by Smittytron** [comment]
Closing after discussion in our Discord github-cleanup channel for being unlikely to be implemented.

If someone did want to resurrect this [here's a video](https://www.youtube.com/watch?v=C0vWzNgMjbM) from the original that may help.
