### ISSUE TITLE
GPU information is not available

### ISSUE THREAD

**Issue by maps13** [OpenRA/OpenRA#18138]
## System Information

- Operating System:  Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
- OpenRA Version: OpenRA engine version release-20200503
- OpenRA Mod: Red Alert
- Source: Official download package OR self-compiled OR third-party package
- For self-compiled or third-party packages: Mono version

## Exception log

```
OpenRA engine version release-20200503
Date: 2020-05-17 18:17:25Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Failed to initialize platform-integration library. Check graphics.log for details.
   in OpenRA.Game.Initialize(Arguments args)
   in OpenRA.Game.InitializeAndRun(String[] args)
   in OpenRA.WindowsLauncher.RunGame(String[] args)


```
Inside the graphics.log there is this error:
System.InvalidProgramException: Failed to initialize low-level OpenGL bindings. GPU information is not available. ---> System.ArgumentNullException: Il valore non può essere null.
Nome parametro: ptr
   in System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   in OpenRA.Platforms.Default.OpenGL.Bind[T](String name)
   in OpenRA.Platforms.Default.OpenGL.Initialize(Boolean preferLegacyProfile)
   --- Fine della traccia dello stack dell'eccezione interna ---
   in OpenRA.Platforms.Default.OpenGL.Initialize(Boolean preferLegacyProfile)
   in OpenRA.Platforms.Default.Sdl2GraphicsContext.InitializeOpenGL()
   in OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor(Size requestEffectiveWindowSize, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile requestProfile)
   in OpenRA.Platforms.Default.DefaultPlatform.CreateWindow(Size size, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile profile)
   in OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings)
   in OpenRA.Game.Initialize(Arguments args)
System.InvalidProgramException: Failed to initialize low-level OpenGL bindings. GPU information is not available. ---> System.ArgumentNullException: Il valore non può essere null.
Nome parametro: ptr
   in System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   in OpenRA.Platforms.Default.OpenGL.Bind[T](String name)
   in OpenRA.Platforms.Default.OpenGL.Initialize(Boolean preferLegacyProfile)
   --- Fine della traccia dello stack dell'eccezione interna ---
   in OpenRA.Platforms.Default.OpenGL.Initialize(Boolean preferLegacyProfile)
   in OpenRA.Platforms.Default.Sdl2GraphicsContext.InitializeOpenGL()
   in OpenRA.Platforms.Default.Sdl2PlatformWindow..ctor(Size requestEffectiveWindowSize, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile requestProfile)
   in OpenRA.Platforms.Default.DefaultPlatform.CreateWindow(Size size, WindowMode windowMode, Single scaleModifier, Int32 batchSize, Int32 videoDisplay, GLProfile profile)
   in OpenRA.Renderer..ctor(IPlatform platform, GraphicSettings graphicSettings)
   in OpenRA.Game.Initialize(Arguments args)

## Additional information

My graphics card:
ATI X1400
Versione del pacchetto di driver	8.332-070108a1-041484C-Acer	
Fornitore	ATI Technologies Inc.	
Versione driver 2D	7.01.01.569	
Percorso file del driver 2D	\REGISTRY\MACHINE\SYSTEM\ControlSet001\Control\Class\{4D36E968-E325-11CE-BFC1-08002BE10318}\0000	
Versione Direct3D	7.14.10.0464	
Versione 	6.14.10.0660	
Catalyst® Control Center Version	0108.2146.2565.38893

**Comment by maps13** [comment]
Additional info about my graphic card:

Produttore scheda grafica	Powered by ATI	
Chipset grafico	ATI Mobility Radeon X1400	
ID del dispositivo	7145	
Venditore	1002	
		
ID del sottosistema	0094	
ID del sottosistema del venditore	1025	
		
Tipo di bus	PCI Express	
Impostazioni correnti del bus	PCI Express	
		
Versione BIOS	009.012.001.010	
Numero di serie BIOS	BK-ATI VER009.012.001.010.018431	
Data BIOS	2006/02/02	
		
Dim. memoria	895 MB	
Tipo di memoria	HyperMemory	
		
Clock principale in MHz	446 MHz	
Clock di memoria in MHz	342 MHz	
		
Visualizzazione primaria	Sì

**Comment by reaperrr** [comment]
According to https://de.wikipedia.org/wiki/ATI_Mobility_Radeon, the highest OpenGL version supported by the X1400 is 2.0, and OpenRA currently requires at least 2.1.
And even if the hardware supported it, there's no guarantee that the drivers do (we only haven't raised the minimum required OGL version to 3.0 yet because some Intel IGPs that officially support it actually have incomplete/broken OGL 3.0 drivers).

**Comment by pchote** [comment]
Indeed, i'm sorry to say that there is nothing we can reasonably to do let OpenRA work on that GPU.
