### ISSUE TITLE
Targetlines not displaying for full duration

### ISSUE THREAD

**Issue by anjew175** [OpenRA/OpenRA#18158]
## Issue Summary
Target lines are not displaying on automatic for the full duration intended

https://streamable.com/h6851u

**Comment by pchote** [comment]
It turns out that `Delay` is being counted in rendered frames, not ticks. Probably a regression from the switch to annotation renderables.

**Comment by netnazgul** [comment]
Technically, it should be in actual seconds and should be tied to neither framerate nor logic ticks. If you tie it to logic ticks, changing the game speed will impact the timing, while pausing the game will make the lines displayed all the time.
