### ISSUE TITLE
CustomSellValue should have a field for able to yield full amount given

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#18189]
In my RA based mod given Refineries an build cost of 1500 and Harvesters 1200, that meant when Refinery gets sold it should yield 300. An CustomSellValue with 300 was given, however it was yielding 150 because presence of Sellable trait on the actor, which tells it by default RefundPercent: 50, so needed to change that into 100 too on this building in order to obtain desired result of 300 when sold.

**Comment by pchote** [comment]
I don't understand. Structures are supposed to only refund half their value when sold. Consider a regular power plant, which costs $300 to buy and sells for $150. A Refinery is likewise worth $300 (after subtracting the harvester), so why shouldn't it also sell for $150?

**Comment by MlemandPurrs** [comment]
1200 Harvester is included in the price of Ref, as its coming free, so it should give the 300 in difference, not half of it.

**Comment by pchote** [comment]
The cost-to-buy of the refinery is $300, right? Why should a $300 refinery sell for $300 when a $300 power plant sells for only $150 (and all other buildings likewise sell for half of their cost to buy).

**Comment by Smittytron** [comment]
If you want it to yield $300, is there an issue with setting the custom value to $600 to yield the desired $300?
