### ISSUE TITLE
Reestablish "DisableWindowsDPIScaling" option in settings which was removed with release 20200503

### ISSUE THREAD

**Issue by christoph110** [OpenRA/OpenRA#18206]
REQUEST MOTIVATION
With the latest release 20200503, the settings property "DisableWindowsDPIScaling" was removed which denies the user to play a the native screen resolution if OS DPI scaling is set to a different value than 1.
Please reenable the option "DisableWindowsDPIScaling" in the settings so that the advanced user can choose depending on his needs.

PROPOSED SOLUTION
As far as I have seen, enabling the option "DisableWindowsDPIScaling" leads to necessary adaptions in at least
- Sdl2PlatformWindow.cs
- Renderer.cs

EXPECTED SIDE EFFECTS
- unknown (due to my lack of knowledge of the source code)

ALTERNATIVES
The Windows 10 compatibility mode allows to disable the DPI scaling for applications. However, this does not work: In some parts of the code the DPI scaling is correctly recognized to be 1, but the native resolution of the screen is still considered including the OS DPI scaling.

**Comment by pchote** [comment]
The `DisableWindowsDPIScaling` variable was added to allow testing and developing of our own HiDPI support, which was finally compled in the latest release. We hadn't considered your use case for this, and I would personally be against restoring a special case flag just for this.

Instead, we can generalize the `OPENRA_DISPLAY_SCALE` environment variable override that is currently only used on Linux to work on macOS and Windows too. You can then [set the override](https://docs.oracle.com/en/database/oracle/r-enterprise/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0) through the windows GUI.

**Comment by pchote** [comment]
If you install the test build from https://github.com/pchote/OpenRA/releases/tag/release-20200503-graphicstest1 you will be able to set `OPENRA_DISPLAY_SCALE` to 1 using the instructions I linked just above.

**Comment by christoph110** [comment]
@pchote : Nice, this works to solve the issue.
(setting the environmental variable is a little bit less comfortable than using the settings.yaml but I agree that as long as there are not more people with this issue, there is no sense in making more effort).

**Comment by dnqbob** [comment]
Hi, here, so currently OpenRA cannot set the `OPENRA_DISPLAY_SCALE` to disable the DPI right?

I think for laptop user this function is quite important for the DPI is always set to 1.25+ otherwise the text will be too small in some text/code editor.

**Comment by pchote** [comment]
As mentioned above, I have a commit that adds the environment variable parsing to Windows, which I will PR before the next playtest is branched.

**Comment by dnqbob** [comment]
Question: does Linux also have DPI settings? can we also make one for Linux system user?
