### ISSUE TITLE
Public Key always copied to clipboard on opening ORA and already logged in

### ISSUE THREAD

**Issue by anjew175** [OpenRA/OpenRA#18217]
## Issue Summary
Every time the ORA application is opened, my public key is copied to my clipboard despite my account already being logged in. This doesn't happen if you are not logged in

## Reproduction
1. Log into auth account
2. Close game
3. Re-Open, wait till main menu is visible then check clipboard

edit: I'm on Windows 7

**Comment by Mailaender** [comment]
I can't reproduce this on Linux.

**Comment by abcdefg30** [comment]
I can't on Windows 10 either.

**Comment by cjshmyr** [comment]
Was able to reproduce it a bit differently, Windows 10.

Opened the client for the first time today and it was in my clipboard afterwards. Didn't happen on subsequent launches.

**Comment by deleted-user-1** [comment]
See also #15604, #15560.

**Comment by Mailaender** [comment]
You probably didn't clear your clipboard between the reloads.

**Comment by cjshmyr** [comment]
I can reproduce this. Happens occasionally when launching TD with an account that's already been linked, no logging out required. Between tests I'm clearing the clipboard (and since this morning's test I've rebooted).

**Comment by anjew175** [comment]
> You probably didn't clear your clipboard between the reloads.
And you're probably just unable to reproduce it

https://streamable.com/sadcfl

**Comment by anjew175** [comment]
In case it’s helpful
https://www.streamable.com/sadcfl
