### ISSUE TITLE
Define and polish resupply / carryall interaction

### ISSUE THREAD

**Issue by deleted-user-1** [OpenRA/OpenRA#18220]
## Motivation

Currently (7a78c378512c3092d407090f807a3ab2efe48702) carryalls can drop their cargo on a service depot when you queue the "release"-order (does not work when the carryall is already landed). But regardless of the health state of the carried vehicle, the unit will just stay there and not be repaired. 

Another issue is that when you order a damaged vehicle to repair and then order a carryall to pick it up while it is still repairing, the unit will stay on the depot but not respond to any orders unless you override the pick up order by ordering the carryall to move somewhere. This is probably a bug itself but also relevant in the context of defining what the behavior for carryalls should be:

- Should they be able to drop damaged cargo on the depot for repair?
- Should they be able to land on the depot and repair cargo without releasing it?
- Should a player be able to order carryalls to pick up units that are being repaired/resupplied?

## Proposed solution

Sending carryalls to the service depot to repair their cargo could be a nice feature. I think it would fit best with the current mechanic if you still had to release the unit with an explicit drop order. Then the dropped vehicle would automatically start repairing and leave the depot to the designated rally point.

Picking up units from the service depot should be possible, but the carryall should wait until the unit is ready and has left the depot to an area where it can stop for getting picked up.

## Side effects

There could be problems to distinguish between cargo health and carryall health. Carryalls also need to be able to be repaired when they're damaged, maybe even when they hold cargo. A carryall with full health is not allowed to land on the depot but one with cargo that is damaged should.

## Alternatives

Don't support drop-repair and disallow landing carryalls on service depots when they hold cargo or are at full health.

**Comment by pchote** [comment]
> Should they be able to drop damaged cargo on the depot for repair?

No. Only next to it. The current behaviour is probably a regression from the transit-only cell PR(?)

> Should they be able to land on the depot and repair cargo without releasing it?

No.

> Should a player be able to order carryalls to pick up units that are being repaired/resupplied?

Yes, but the unit should move off the pad before it is picked up (using the same logic we have to undeploy ticktanks/juggernauts).

**Comment by deleted-user-1** [comment]
I should have said that I meant TS Carryalls.

**Comment by deleted-user-1** [comment]
Seriously @Mailaender, learn how to label issues correctly, is it that hard?
