### ISSUE TITLE
Laggy rendering performance

### ISSUE THREAD

**Issue by christoph110** [OpenRA/OpenRA#18221]
SYSTEM INFORMATION
- Operating System: Windows 10 Professional
- Prozessor: Intel i5 CPU
- Graphic card: NVIDIA GeForce GT 540M (1GB)
- OpenRA release: 20200503 (issue appeared first in playtest 20200301)

DESCRIPTION
The rendering starts to lag periodically after some time of running (see performance graph in screenshot below):
- the lags appear only after some time (~1min) of running the game
- no lags appearant with release 20200202 and appeared with playtest 20200301
- "render" and "render_flip" cycle time rises from 13ms to >60ms
- lags appear periodically (every ~3secs)
- lags appear only for the "render_flip" cycle when setting "DisableWindowsRenderThread: True". When  "DisableWindowsRenderThread: False" only the "render" cycle lags. 
- using "CapFramerate: True" (with e.g. 50 Hz) delays the start of the first lag but then the lags appear with the same periodicity as without "CapFramerate"
- switching Vsync on or off (either in-game or in the graphic driver GUI) does not seem to influence this behavior.

![OpenRA-Performance](https://user-images.githubusercontent.com/59751309/83444152-3c561b80-a44b-11ea-83c4-633367624121.jpg)

**Comment by pchote** [comment]
Does this test build help at all? https://github.com/pchote/OpenRA/releases/tag/release-20200503-graphicstest1

**Comment by christoph110** [comment]
@pchote : The "graphictest1" works like a charm for the screen resolution/scale issue (https://github.com/OpenRA/OpenRA/issues/18206).
However, the performance issue seems to be unrelated to the screen resolution/scale (although both appeared with the changes for the playtest release 20200301).

**Comment by abcdefg30** [comment]
Closing as stale, there have been several changes to the rendering code since this was opened.
