### ISSUE TITLE
LeavesTrails use facing value as delay

### ISSUE THREAD

**Issue by evgeniysergeev** [OpenRA/OpenRA#18249]
## Issue Summary

LeavesTrails incorrectly creates SpriteEffect, spawnFacing value used as delay, facing always set to zero

## Reproduction

Found in d2 mod
https://github.com/OpenRA/d2/pull/184

## Expected behavior

Trails should use correct facing and delay should be controlled by StartDelay config option

## Screenshots / Screen recordings / Replays

![vertical-trails](https://user-images.githubusercontent.com/3105609/83619392-7b43b880-a594-11ea-8636-1eb5e8b3216a.png)

All trails on this screenshot is vertical, but vechicles moved randomly here

**Comment by pchote** [comment]
#18228 fixes this.
