### ISSUE TITLE
Command & Conquer Remastered Edition

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#18241]
REQUEST MOTIVATION
PROPOSED SOLUTION
EXPECTED SIDE EFFECTS
ALTERNATIVES

Hi !

Yes you all know it (all of you, don't lie) : the C&C Remastered Edition is out.

After playing around a bit in Tiberian Dawn and Red Alert I'm quite sad about this Remastered Edition.
- You can't zoom as far as OpenRA does so you can see somehow two dozens buildings maximum on screen at the same time. There is simply no macro in the Remaster.
- There are no "competitive shortcuts" (I would say "Starcraft 2 style" like OpenRA does but it's not exactly this).
- A-Bomb can't destroy a MCV (so what, pay and defend your A-Bomb to destroy a power plant ?)
- Badgers are attacked by anti-air (what's the value added there ?)
- No don't-attack-my-hind-above-your-PP-or-it'll-be-painful-but-you-have-to-let-me-have-some-vision-above-your-base tactics because air units simply vanish on death.
- AI didn't attack me for 20 minutes, I had to attack it and it finally lost its few heavy tanks against my 20 mammies (I had some time).
- No attack move (No attack move ! (Really, no attack-move for a Remaster in 2020, marauders, stalkers and cracklings would be upset)).
- No stances nor a stances bar like OpenRA does (usable on tablets and other mobile platforms).
- The long-time OpenRA "Press F to deploy" joke ? Way above the "Press F to pay respects" meme ? Nope, no default F to deploy here (it was an instinctive reaction in my first Remaster skirmish game but nothing happened).
- If you want to monitor your super-expensive-slow-to-build-and-long-to-produce weapon, then click on the CORRESPONDING TAB.
- The "antennas" on the mammoth tank are not even aligned in all facings.

Ok ok, I hear you, purists, "the game wasn't like that in 1995", but we are not in 1995, we are in __2020__ !
Ultra-fast-and-heavy-competitive fights and stuff !

Other players will have certainly some other things to say, it is only my first impression.
I really like the upgraded definition, the fan service, the trailers and the people around (see Joseph Kucan's trailer 1 day before the launch), but it's not like something Starcraft I Remaster would be afraid of.
I hoped something like "Listen to us you Stracraft noobs... that Tiberium smell in the morning...". :)
How about my competitive-OpenRA-2020-Ukraine build order which is totally messed up in this Remaster (build a power plant and immediately an APP but no flame thrower to defend it because the building production queue is the only one building production queue, and why not building an immediate tech center after all ?) ?
It looks like they didn't improve it, they just redesigned it, really nicely I have to admit, but like we are still in 1995.
Honestly, I launched the Remaster like "Some original 95 devs upgraded it, original source code, FMVs and so on, OpenRA will not be able to handle it", but finally OpenRA is technically and "balancingally" really far away above... from the balanced nuke to the LUA modding including the attack-move, the stances stuff, the 2.5D engine and so on (and on).
I paid two copies of this Remaster because I was like "woah", and after few hours I'm finally like "Where is my OpenRA setup ?".
I'm sure Jim Vessela, Joseph Kucan and others wanted some fun, some nostalgia, but with maximum 20 buildings on the screen, a useless A-Bomb and no attack-move, on 4K screens in 2020 (I saw some __HDPi__ ""issues"" on the OpenRA repo few months ago), what can I say...
I have to click on every single enemy unit if I want to win a game (can't "send my units with an attack-move, "H" to back to my base to build, "double 1" to re-monitor my attack, "H" re-back to my base to macro, "double 1" to re-monitor my attack, "H" to re-back to defend my base against some push, "double 1" to re-monitor my attack, write "surprise surprise" in the chat, "H" to re-back to my base to wall here and there, and so on" like we do in OpenRA ...).
While I'm writing this, I didn't even see a single enemy AI rifleman attacking my deployed-but-not-doing-anything-MCV for 20-30 minutes.
"Edit" : Five heavy tanks attacked my MCV and it finally died after 20+ minutes. This is not competitive.
Regarding the ~7800 stars on GitHub and the (sometimes tenacious) debates about balancing, C&C Remastered can't actually compete against OpenRA.
I hope it will evolve and in any case I hope OpenRA will support the Remastered assets (setting the installation directory like OpenRA does for the original CDs or something like that).

_This is so sad._
Feel free to close this non-issue issue and see you on the battlefield !

(Why should I write this on an Origin or Steam forum ?)

**Comment by tovl** [comment]
Closing, as this is not what github issues are for.

Btw, there already is an open issue for importing remastered assets: #18239
