### ISSUE TITLE
Game freezes when restarting a game multiple times

### ISSUE THREAD

**Issue by deleted-user-1** [OpenRA/OpenRA#18250]
## Issue Summary

Operating System: Linux (Unix 4.15.0.101)
Runtime Version: Mono 6.8.0.123 (tarball Tue May 12 15:11:57 UTC 2020) CLR 4.0.30319.42000
Commit: fb27a25e5291282ef5b6f44f849f0ed68d56c6cc

I can reliably freeze the game by restarting a skirmish game with bots that I launched from the lobby multiple times.

## Reproduction

Start a skirmish game with >3 bots in TD, D2K, RA or TS and restart it multiple times from the ingame menu. It might have to do with the amount of bot that you add, with many, the game sometimes also freezes on the first restart.

## Expected behavior

Game restarting in a reasonable time frame.

**Comment by abcdefg30** [comment]
I also encountered this a few times, but never could work out what causes this. We should probably at least have another look for the next release.

**Comment by Mailaender** [comment]
I propose https://github.com/OpenRA/OpenRA/pull/18700 to improve this.
