### ISSUE TITLE
My game crashed

### ISSUE THREAD

**Issue by kslstn** [OpenRA/OpenRA#18251]
## System Information
- Operating System:  macOS 10.15.5 (19F101)
- OpenRA Version: release-20200503
- OpenRA Mod: Tiberian Dawn mod version release-20200503
- Source: Official download package

## Exception log
> OpenRA engine version release-20200503
> Tiberian Dawn mod version release-20200503
> on map 9cc07c6305f093b87bfb4fa0e9d8405e05d27c5f (C&C64 Special Ops - GDI 1 by Westwood Studios).
> Date: 2020-06-06 20:01:40Z
> Operating System: OSX (Unix 19.5.0.0)
> Runtime Version: Mono 6.4.0.198 (2019-06/fe64a4765e6 Wed Sep 18 14:14:51 EDT 2019) CLR 4.0.30319.42000
> Exception of type `Eluant.LuaException`: [string "BindingSupport.lua"]:30: Unable to convert parameter 0 to Actor
>   at Eluant.LuaRuntime.Call (System.Collections.Generic.IList`1[T] args) [0x000c9] in <c8bc0b4612b543268b8307855c69585a>:0 
>   at Eluant.LuaRuntime.Call (Eluant.LuaFunction fn, System.Collections.Generic.IList`1[T] args) [0x00032] in <c8bc0b4612b543268b8307855c69585a>:0 
>   at Eluant.LuaFunction.Call (System.Collections.Generic.IList`1[T] args) [0x00007] in <c8bc0b4612b543268b8307855c69585a>:0 
>   at Eluant.LuaFunction.Call (Eluant.LuaValue[] args) [0x00001] in <c8bc0b4612b543268b8307855c69585a>:0 
>   at OpenRA.Mods.Common.Scripting.ProductionQueueProperties+<>c__DisplayClass3_2.<Build>b__4 (OpenRA.Actor factory, OpenRA.Actor unit) [0x00098] in /Users/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Scripting/Properties/ProductionProperties.cs:172 
>   at (wrapper delegate-invoke) System.Action`2[OpenRA.Actor,OpenRA.Actor].invoke_void_T1_T2(OpenRA.Actor,OpenRA.Actor)
>   at OpenRA.Mods.Common.Scripting.ScriptTriggers.OpenRA.Mods.Common.Traits.INotifyProduction.UnitProduced (OpenRA.Actor self, OpenRA.Actor other, OpenRA.CPos exit) [0x00090] in /Users/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Scripting/ScriptTriggers.cs:176 
>   at OpenRA.Mods.Common.Traits.Production+<>c__DisplayClass6_0.<DoProduction>b__0 (OpenRA.World w) [0x000cc] in /Users/travis/build/OpenRA/OpenRA/OpenRA.Mods.Common/Traits/Production.cs:92 
>   at OpenRA.World.Tick () [0x001a9] in <d572d317940047d2a5a305d62d990530>:0 
>   at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x001bc] in <d572d317940047d2a5a305d62d990530>:0 
>   at OpenRA.Game.LogicTick () [0x0003e] in <d572d317940047d2a5a305d62d990530>:0 
>   at OpenRA.Game.Loop () [0x000f1] in <d572d317940047d2a5a305d62d990530>:0 
>   at OpenRA.Game.Run () [0x0003c] in <d572d317940047d2a5a305d62d990530>:0 
>   at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00010] in <d572d317940047d2a5a305d62d990530>:0 
>   at OpenRA.Program.Main (System.String[] args) [0x00044] in <d572d317940047d2a5a305d62d990530>:0 

## Additional information
Crashes occurred twice during ~45 minutes of game play. Both times in the bonus GDI level after several minutes of playing.

**Comment by pchote** [comment]
Thanks for the report. This was fixed by #18152 for the next release.
