### ISSUE TITLE
Mine Layer Bot Module

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#18266]
I imagine this to be a mixture of the defense building placement and the MCV deployment routines.

**Comment by pchote** [comment]
This should instead be handled by proper squad team-type logic - see #9021. Bot-level modules is simply the wrong approach for team handling.

**Comment by MlemandPurrs** [comment]
With the current stupidity of AI it would end up mining its own Ore field, losing own harvesters.
