### ISSUE TITLE
WeatherOverlay doesn't respect spectator zoom-out

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#18276]
As reported by Happy [on Discord](https://discord.com/channels/153649279762694144/279290580201373696/721156474776191036), the WeatherOverlay doesn't work as intended when a spectator zooms out too far, but rather sticks to the x1 viewport:
![](https://media.discordapp.net/attachments/680897994828283914/721152276735197244/unknown.png?width=1194&height=671)
This would be related to the recent changes from #17424 and #17839.

**Comment by pchote** [comment]
Repro case may require 125% OS DPI scaling.
