### ISSUE TITLE
Tooltip remains after leaving/switching the menu

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#18301]
Reported by Happy on Discord:
![](https://cdn.discordapp.com/attachments/279290580201373696/723222375889633360/unknown.png)
Hover over a player and then close the menu again using the hotkey. I think I saw the same in the map editor (hover over an item and then open the menu via the hotkey). We should probably just always clear tooltips when changing the (menu) widget.

**Comment by pchote** [comment]
This should be an easy fix - we just need to `UI.ResetTooltips` when opening the menu.

**Comment by PavolMolnar** [comment]
Hello everyone. I would be interested in contributing by fixing this issue. Could I be assignet to it? Thank you.

**Comment by abcdefg30** [comment]
Done. Happy coding. :)
