### ISSUE TITLE
My game crashed

### ISSUE THREAD

**Issue by hacikenks** [OpenRA/OpenRA#18329]
## System Information

- Operating System:   WINDOWS 10
- OpenRA Version: Release 20200503
- OpenRA Mod: Red Alert
- Source: Official download package

## Exception log

```
Log has not been created
```

## Replay

Replay has not been created

## Additional information

![20200605_225605](https://user-images.githubusercontent.com/16431356/85794281-a30ee200-b736-11ea-83c4-7dffe34346b8.jpg)

In he middle of the game my screen goes insane and the program does not respond. Please see the attachment.
[20200626-122340_958mHKKB.compressed.zip](https://github.com/OpenRA/OpenRA/files/4836446/20200626-122340_958mHKKB.compressed.zip)

**Comment by pchote** [comment]
This looks like a GPU driver crash. Does it happen often, or was this a one off?

**Comment by hacikenks** [comment]
> This looks like a GPU driver crash. Does it happen often, or was this a one off?

It happens quite often. Not in every game but every 10 games or so.

**Comment by pchote** [comment]
Try switching the "OpenGL Profile" in OpenRA's display settings to "Legacy". Does this help?

**Comment by hacikenks** [comment]
Problem solved by setting the display settings to "Legacy"
