### ISSUE TITLE
VXL hover units slide when turn around

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#18327]
We have already discussed the aircraft pitch and roll by using the new system of VXL,  so how about make hover tank slide too?  In mission movie the hover MRLS can slide when turn around and it is kinda cool.  Since the hover units VXL aren't affect by ramp so maybe we can try this and see if it will turn out to be a cool idea.

**Comment by tovl** [comment]
https://github.com/OpenRA/OpenRA/pull/18293#pullrequestreview-438709675 seems relevant here as well.
