### ISSUE TITLE
Un-Hard code shadows

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#18328]
## Motivation

The original TD used a more light shadow color\transparency, It seems like a detail but TBH when I play the original game and then switch into OpenRa the nostalgic feeling is not there. The shadows are on every unit and building, and the overall picture it just doesn't feel right.

Here is an example
![OpenRA-2020-06-25T163024433Z](https://user-images.githubusercontent.com/5400487/85784203-b4ed8680-b730-11ea-8de8-e7a2d2db37f3.png)

## Proposed solution

Un-hard code the shadow

## Side effects

Unknown

## Alternatives

Unknown

**Comment by Mailaender** [comment]
It already is configurable https://github.com/OpenRA/OpenRA/blob/f0c808d2fc2a5df94660c1d32efaa5f96c4b3626/mods/cnc/rules/palettes.yaml#L75-L80

**Comment by KOYK** [comment]
Can this be used along with player color palette?

**Comment by pchote** [comment]
No. The shadow used within other palettes is hardcoded.

**Comment by KOYK** [comment]
It wont be fixed\added, closing it.
