### ISSUE TITLE
D2k carryall flies idle after picking up a harvester

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#18336]
https://www.youtube.com/watch?v=YfEGC0uaSsU

**Comment by reaperrr** [comment]
I see two possible fixes:

- make the harvester reject any further orders once the carryall has gotten to that point in the pickup process
- make carryalls drop their load again if something broke the activity sequence

Maybe we should even do both?

**Comment by reaperrr** [comment]
Maybe it's a timing issue, but I have trouble reproducing it locally. When I try that, the carryall always still delivers the harv to the refinery, and then the harvester moves as close as it can to the impassable terrain I clicked on. Maybe this was somehow fixed as byproduct of some recent PR?

Anyway, unless someone finds a reliable way to reproduce it, this doesn't seem like a must-fix for the next release to me.

**Comment by pchote** [comment]
I also can't reproduce this on release-20200503 or bleed.

**Comment by abcdefg30** [comment]
Closing then until someone comes up with a case.
