### ISSUE TITLE
OpenRA will have buffs from Pentagon Developers? Any confirm this "Deep" functional?

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#18331]
The following lists Gamebreaker teams and their two video games:

    Aurora Flight Sciences is teamed with MIT and will use StarCraft II and Google Research Football
    BAE is teamed with UC Santa Barbara and AIMdyn and will use StarCraft II and the AFRL Strategem Wargame
    Blue Wave AI Labs will use SpringRTS: 1944 and OpenRA
    EpiSci will use miniRTS and StarCraft II
    Heron Systems will use DeepRTS and StarCraft II
    Lockheed-Martin is teamed with Cycorp and will use Multi-agent Particle Environment and SpringRTS: 1944
    Northrop-Grumman has teamed with Hazard Software and Matrix Games and will use Command: Modern Operations and TORCS
    Purdue University will use microRTS and StarCraft II
    Radiance Technologies is partnered with BreakAway Games and will use FreeCiv and Zero-K

**Comment by deleted-user-1** [comment]
What is the reported bug, support question or requested feature here? What's the closing condition?

Speculating about random news articles is better done in the one of the gazillion other places of the web.

**Comment by yaaaaa** [comment]
This is intresting thing to add AI in Engine.
And questions is exist too:
Has any progress of this? Or plans about it?
Closing condition prerequist any ansver, I removed link to news site.

**Comment by dnqbob** [comment]
see project: AI improvement

**Comment by Mailaender** [comment]
According to https://www.darpa.mil/news-events/2020-05-13 they will just use OpenRA and don't plan to contribute anything back. This is military research after all.
