### ISSUE TITLE
Support for Depth Enabled RGBA Terrain

### ISSUE THREAD

**Issue by mabulsoud** [OpenRA/OpenRA#18333]
## Motivation

Currently OpenRA supports RGBA terrain tiles which is awesome! However, you can't enable depth with them since the zdepth data is hardcoded to look at I + <number of normal frames> of the same tileset but it is also hardcoded to be indexed.

## Proposed solution

The proposed solution would be to allow for depth frames to be defined separately from the tileset frames. Essentially that would allow you to have and RGBA color frames with an accompanying 8bit file for depth data.

Please find some files for testing that at this[ link](https://drive.google.com/file/d/1u6GhqoHQn5velbRCHJ4gGFTZ8MgZrrDC/view?usp=sharing)

## Side effects

I do not expect any side effects from adding this ability as it wouldn't affect the default mods. but it would allow third party to utilize RGBA sprites for isometric mods.

## Alternatives

Add the ability for OpenRA to interpret depth data in RGBA tilesets. Althought I imagine this would be significantly harder and possibly have unintended consequences.

**Comment by pchote** [comment]
I suspect the better fix here will be to add support for 32bit depth frames, with the fragment shader combining the four colour channels to allow an expanded depth range. The community mods that want to use higher bit depths typically also want to use higher resolutions, so 256px of depth data isn't going to be enough. This sidesteps the issue of mixing 32 and 8 bit data on the tileset side.

**Comment by mabulsoud** [comment]
I believe it would still be useful to have them defined in separate files with different frame sizes which is currently defined as metadata on each png. This allows for depth data that's a different size than the image data which is necessary in some cases, such as oversized tiles/self LAT
