### ISSUE TITLE
Something about "Codacy/PR Quality Review" 

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#18332]
It is not the game bug report here, but the code testing bot on PR checking in OpenRA.

In OpenRA code standard it is said the "{}" is ignored when there is only one line in code block. However,

<img width="421" alt="note" src="https://user-images.githubusercontent.com/13763394/85847220-9a231c80-b7d9-11ea-9c08-0a222436077a.png">

<img width="355" alt="note2" src="https://user-images.githubusercontent.com/13763394/85847229-9e4f3a00-b7d9-11ea-9e8b-252a5ffeaa4e.PNG">

"Codacy/PR Quality Review" give me red cross because of this. Although PR quality checking bot here is pretty amazing and help me optimaze the code at certain point, it makes me confused when comes to this problem.

**Comment by deleted-user-1** [comment]
> but the code testing bot on PR checking in OpenRA.

You can ignore that, in fact it's been only active for some hours and has been removed meanwhile. It's not part of OpenRAs CI and shouldn't be relevant.

**Comment by abcdefg30** [comment]
Yes, Codacy was an experiment gone wrong, you can ignore it and it will go away once you (force) push to the branch again.
