### ISSUE TITLE
Add random faction information to the replay viewer 

### ISSUE THREAD

**Issue by Yara-smurf** [OpenRA/OpenRA#18342]
## Motivation
It is currently not possible to identify if a player selected random faction or not when reviewing replays. It could also be very useful for the casters in the introduction of a game. Apparently the info is already within the replay source so it might be easy to add. 

## Proposed solution
I think simply adding to the label (Random) should be sufficient. 
Example: 
Player 1: Ukraine (Random) 
Player 2: Germany 

## Side effects
@abcdefg30 mentioned that there was a problem with the UI in a previous release and that is why this feature was removed before.

**Comment by Yara-smurf** [comment]
As suggested by Bug, covering all randoms would be of course important :) 

Player 1: Ukraine (Random)
Player 2: Russia (Random Soviet)
Player 3: France
Player 4: Germany (Random Allies)

**Comment by dragunoff** [comment]
IIRC this used to work by changing the player view and then the faction info also changed to the render player's point of view. Adding the label in brackets is straight-forward, I can PR if this is an acceptable solution:

![image](https://user-images.githubusercontent.com/1355810/102927272-5155d300-449f-11eb-85f6-3a1a8a937b78.png)
_Player view_

![image](https://user-images.githubusercontent.com/1355810/102927188-279cac00-449f-11eb-8bc7-e41e7331ce2d.png)
_Spectator view_

But IMO it's a bit confusing as it's not clear what the text in the brackets means (i.e. that England is Allies and Russia is Soviet or?).

**Comment by pchote** [comment]
I agree that this would be confusing. A more intuitive (but more work) option could be to create a new set of faction flags that diagonally cut between the grey/blue/red random flag and the resolved faction flag and keep the label as it is.

**Comment by dragunoff** [comment]
It depends on the artwork because the diagonal cut won't work for the current TD factions. So some more work would be needed to work out the icons. 

Another unobtrusive (but less useful) approach is to put that info in a tooltip.

**Comment by pchote** [comment]
The even easier option would be to use the random flag but the resolved faction name. Or we could do that just for TD and use my initial suggestion for RA?

Edit: Or perhaps invert your screenshot above, so it is e.g. `[ ? ] Any (Ukraine)`

**Comment by dragunoff** [comment]
Yeah, that could work. Some quick mocks:
![factions-cnc](https://user-images.githubusercontent.com/1355810/102930711-a5fc4c80-44a5-11eb-8422-53bc57dcafdf.png)
![faction-ra-3](https://user-images.githubusercontent.com/1355810/102930714-a694e300-44a5-11eb-9ffc-26de8624720a.png)
![faction-ra-2](https://user-images.githubusercontent.com/1355810/102930716-a694e300-44a5-11eb-8fc8-329a45142a34.png)
![faction-ra](https://user-images.githubusercontent.com/1355810/102930718-a694e300-44a5-11eb-82d0-178d7e54cee5.png)

**Comment by dragunoff** [comment]
This works better:
![ra-2020-12-28T185635603Z](https://user-images.githubusercontent.com/1355810/103237112-5f986900-494f-11eb-816a-465f9e0c1ff7.png)

**Comment by pchote** [comment]
Looks reasonable to me. Can you check that we don't cut off any text when using the longest combination of random faction label + faction name across the default mods?

**Comment by dragunoff** [comment]
> Looks reasonable to me. Can you check that we don't cut off any text when using the longest combination of random faction label + faction name across the default mods?

I tested across the default mods and didn't see any text clipping.
