### ISSUE TITLE
Implement fine control for Health remaining in Editor

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#18358]
It would be good if there was an additional text field where can directly input %value of health remaining. Or perhaps it would be in steps of 5% 
Sure the added slider is nice but it can be an balance issue if had intend all neutral structures to have exact 50% remaining health and one or more ended up having slightly above or below that. Need to manually check by opening the .map with an text editor to ensure it didnt, rendering the function of this rather obsolete.

**Comment by pchote** [comment]
I had originally vaguely planned to support a numeric input field (with the standard +/- buttons) for this kind of thing, but never got around to building it.

**Comment by abcdefg30** [comment]
This was fixed by #18652.
