### ISSUE TITLE
don't render if game minimized or paused

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#18354]
Proposal to listen to SQL_WindowEvent to detect if the game Window is hidden or minimized.
https://wiki.libsdl.org/SDL_WindowEvent

Proposal to not render the World and UI when the Window is not visible to the user - but still running - and/or when the game is paused.

The game will use less resources when not used by the end user. I.e. player in between games, spectators switching to discord, etc.

To keep animations in sync RenderTicks perhaps do need to be processed(?).

Game logic is preferably also paused when no game is/was active.

Leaving the game currently running - on i.e. the shell map/main menu - causes the game (on Linux) to still use a lot of CPU (50%) with the result that it heats up laptops. You now can't leave the game running while doing other things.

**Comment by pchote** [comment]
See #17837.
