### ISSUE TITLE
Paradropped units move to top-left if an order is given during the drop

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#18372]
After a recent engine update to upstream in RV, trying to give an order to units being paradopped on a map with height causes them to move to top-left first. They move normally there and the move order cannot be stopped with stop command, after they reach there you can order them with no issue. This seem to only happen on maps with heights, i couldn't reproduce the issue on 2 flat maps, but i could easily trigger it on a map with height. I didn't try maps with height but also places where height is 0. I checked around the paradop code on RV engine, didn't see any difference from upstream to cause this. I couldn't test it on upstream to see if i can reproduce there either tho, as TS only base mod with map height don't have Paradroppers.

**Comment by abcdefg30** [comment]
Was #18343 included in your engine? It might be a similar issue.

**Comment by MustaphaTR** [comment]
Doesn't seem like it. Will do another engine update to see if that fixes it.

**Comment by MustaphaTR** [comment]
Yeah, this seems to be fixed.
