### ISSUE TITLE
Waypoint mode issue

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/OpenRA#18409]
nr1995:
While holding [Shift] for waypoint mode,
your unit(s) should not move, even after clicking on open ground.
Currently, they begin moving as soon as you lay down the first position.

Also, it could use a different/clearer line, like vanilla does.

https://github.com/cookgreen/Yuris-Revenge/issues/152

**Comment by tovl** [comment]
Duplicate of  #12408
