### ISSUE TITLE
Edit [Shift] and [Ctrl] Issue

### ISSUE THREAD

**Issue by cookgreen** [OpenRA/OpenRA#18410]
nr1995: 
We get access to most of the hotkeys in the game,
but there's no option to change the [Shift] key (waypoint mode),
or the [Ctrl] key (force attack mode).
It would be nice to have some customisation there too.

https://github.com/cookgreen/Yuris-Revenge/issues/151

**Comment by dragunoff** [comment]
Already tracked in #15879

**Comment by tovl** [comment]
Closing as duplicate.
