### ISSUE TITLE
Reorder the Display tab in Settings

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#18426]
I think some of the tabs in the Settings menu are getting a bit overcrowded.
And with issues like #18242 and #18400 the Display tab is definitely going to be one of them (since those two warrant the addition of two new checkboxes in that tab).
So I was thinking we can do something like the Generals settings, where you have a button to open up additional visual settings.

<details>
<summary>So starting with this (the current TS Settings menu, which is shared across mods):</summary>

![image](https://user-images.githubusercontent.com/7137365/88066873-f5e18b00-cb76-11ea-93e9-d2cc5c899435.png)
</details>
I made some rough quick mockups:
<details>
<summary>From this</summary>

![image](https://user-images.githubusercontent.com/7137365/88067054-2b867400-cb77-11ea-8af3-293edef795f5.png)
where some things are reordered and more logically grouped spacialy...
</details>

<details>
<summary>to finally this</summary>

![image](https://user-images.githubusercontent.com/7137365/88067107-3c36ea00-cb77-11ea-9ba1-194f8c8fc6b3.png)
</details>

Where the `Advanced` button either opens a popup with additional settings or replaces the tab entirely and gives you a set of extra toggleables like these:

![image](https://user-images.githubusercontent.com/7137365/88067387-9932a000-cb77-11ea-9823-3349963baede.png)

I want to resolve the two issues/features that this one may or may not be blocking, but I want to gather some opinions before thinking of doing this one.

P.S.: Mine is a rough mockup so I'm open to alternatives.

P.P.S.: @cjshmyr did note "I'd personally move stance colors checkbox in there too", but I personally find that a bit questionable.

**Comment by pchote** [comment]
Right-handed checkboxes look weird, IMO.

**Comment by penev92** [comment]
I figured someone might bring that up.
Going with @cjshmyr's suggestion would actually resolve that issue (but break the symmetry).

**Comment by dragunoff** [comment]
How about left-aligning and stacking  all the settings in a scroll pane and not worrying about layout or hiding things behind an "Advanced" toggle?

At the same time we can switch to vertical tabs layout which would allow the settings to be broken up into more tabs (also allowing mods to add their own tabs).

And of course any changes to the layout here would be much easier with Yoga. So it's a good time to bounce some ideas around.

**Comment by pchote** [comment]
There are strong parallels between this and #6354, so ping @dragunoff for thoughts and comments. This might provide a route to a clearer UI for #17737?

Edit: beat my ping by literally seconds 😓

**Comment by pchote** [comment]
The "advanced" options here aren't really advanced, nor are they really "display". A simpler approach that could eventually lead into @dragunoff's more ambitious suggestion could be to simply add a new "Interface" tab that should still just about fit horizontally.

**Comment by penev92** [comment]
Of all the suggestions I like the new tab the best, so I'm all for that 👍 

As much as I'd like to try out Yoga though, I do want to see the two linked issues resolved.

**Comment by ghost** [comment]
I would be careful about adding tabs that will just about fit if there's any possibility of the interface needing to accommodate more verbose languages than English.
