### ISSUE TITLE
TD: Harvesters don't cancel docking animation when refinery is killed

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#18422]
https://cdn.discordapp.com/attachments/279290580201373696/734516370179358750/Harvester_Unload_no_Ref.mp4

Reproduction: Kill the refinery right when the harvester starts turning to dock.

**Comment by KOYK** [comment]
Just information: In the original game harvesters where destroyed along with the refinery.

**Comment by pchote** [comment]
@Orb370 do you have the replay for that? It would make this much easier to diagnose and solve.

**Comment by Orb370** [comment]
[Harvester Dock Bug.zip](https://github.com/OpenRA/OpenRA/files/5273048/Harvester.Dock.Bug.zip)

**Comment by Orb370** [comment]
[Harvester Docking Bug TD.zip](https://github.com/OpenRA/OpenRA/files/5367548/Harvester.Docking.Bug.TD.zip)

If you give a harvester a new order while it's turning to dock, a similar bug occurs. Probably same cause.
