### ISSUE TITLE
We need a condition when transit to subterranean

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#18437]
To be simple: we need a condition granted when actor is transitting to subterranean but not done.  And it will be important for VXL&SHP actor to behave a digging into ground or play a sequence of digging or sth.

**Comment by pchote** [comment]
Conditions are designed for states rather than events, and we already have `GrantConditionOnSubterraneanLayer` managing the dig animations and `Move` (once #9012 is resolved) the body tilting. What else is needed here?

**Comment by dnqbob** [comment]
`GrantConditionOnSubterraneanLayer` give condition only when actors are subterranean layer,  that means we can not apply sequence only when it is completely underground (and it should be impossible to see anything subterranean if we follow the rules of TS).

**Comment by abcdefg30** [comment]
Doesn't `SubterraneanTransitionSequence` do that?

**Comment by dnqbob** [comment]
So the condition of GrantConditionOnSubterraneanLayer is not very good at control sequence and animation of digging action in my opinion.

**Comment by abcdefg30** [comment]
Yes, the condition is not meant for transitions.

**Comment by dnqbob** [comment]
> Doesn't `SubterraneanTransitionSequence` do that?

```
void PlayTransitionAudioVisuals(Actor self, CPos fromCell)
		{
			if (!string.IsNullOrEmpty(Info.SubterraneanTransitionSequence))
				self.World.AddFrameEndTask(w => w.Add(new SpriteEffect(self.World.Map.CenterOfCell(fromCell), self.World,
					Info.SubterraneanTransitionImage,
					Info.SubterraneanTransitionSequence, Info.SubterraneanTransitionPalette)));
```

the sequence here seems to refer to the digging animation image,  which should be the earth and dirt when digging.

**Comment by abcdefg30** [comment]
Which brings us back to what you want to do. Apparently it is not playing a sequence when changing layers?

**Comment by dnqbob** [comment]
~~Umm,  to make a condition for transition.  That will be helpful when we are making subterranean actor (especially in SHP) with a good transition animation~~

**Comment by dnqbob** [comment]
> Apparently it is not playing a sequence when changing layers?

~Yes~ No
Sorry for the reply mistakes here (what I mean was that it was correct(yes) that it was not playing a sequence when changing layers)

**Comment by abcdefg30** [comment]
So what you want is a general `With...Animation` trait that uses some `OnLayerChanged` interface to change the unit animation?

**Comment by dnqbob** [comment]
yes,  dude.  And that will be nice.

**Comment by dnqbob** [comment]
At first I thought a condition applied when subterranean transition so game maker or modders can use normal WithMovingAnimation for the transition animation. (although I don't know if changing layers will be considered as moving) 

But WithLayerTransitionAnimation alike is also a good idea and it will make the yaml more readable. I think both ideas are ok for me.

**Comment by dnqbob** [comment]
gif related. 
I think a proper transit animation can be applied here and also a probably improved `WithUnloadAnimation` can make this drill pod better. 
![1](https://user-images.githubusercontent.com/13763394/88462922-a639f100-cee1-11ea-8956-f9444c575433.gif)
As you can see the drill pod sequence is not that pleasant. Because `GrantConditionOnSubterraneanLayer ` isn't good at it and `WithUnloadAnimation`Always start too early at stage of open and too late in close.
