### ISSUE TITLE
`Furthest` Camera level still appears with `AllowNativeZoom: false`, if the native resolution is bigger than Far.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#18435]
We have been trying to limit the camera level for the player to default "Medium", i changed "Far" to the default "Medium" and "Medium" to somewhere between "Close" and "Medium". But on Ganon's end now "Furthest" option appears, but with `AllowNativeZoom: false`, it is identical to "Far". If that is true, it uses the Native screen resolution as expected. But when it is false, i think Further shouldn't appear at all.

**Comment by pchote** [comment]
I forgot to add a `AllowNativeZoom` check in `SettingsLogic` to hide the `Furthest` option, which is otherwise correctly being ignored when the mod disables it.
