### ISSUE TITLE
TakeOffOnCreation does not prevent take off and blocks exit

### ISSUE THREAD

**Issue by deleted-user-1** [OpenRA/OpenRA#18444]
## Issue Summary

`TakeOffOnCreation: false` will not prevent aircraft from taking off, instead they do take off and at the same time block unit production, as if they were reserving the pad/airfield when returning to base (although they aren't). So there is likely something else with reservations not working correctly. This happens regardless of waypoint being set. 

## Reproduction

```miniyaml
Aircraft:
    TakeOffOnCreation: false
```

## Expected behavior

"Does this actor automatically take off after creation?"

Tested on 5401ace5408c47876d1a7c601bf20038439fe57b .

**Comment by MlemandPurrs** [comment]
this is still happening on release 20210321

**Comment by Mailaender** [comment]
There is now https://github.com/OpenRA/OpenRA/pull/20825 ready for testing.
