### ISSUE TITLE
Outer braces are flagged as a style error by editorconfig

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#18445]
#18415 added `csharp_prefer_braces = false:error`, which means that the code like:

```csharp
// Set density based on the number of neighboring resources
var adjacent = 0;
for (var u = -1; u < 2; u++)
{
	for (var v = -1; v < 2; v++)
	{
		var cell = c + new CVec(u, v);
		if (resources.Contains(cell) && resources[cell].Type == type.Info.ResourceType)
			adjacent++;
	}
}
```

is flagged as an error, with a suggestion that it should instead be changed to

```csharp
// Set density based on the number of neighboring resources
var adjacent = 0;
for (var u = -1; u < 2; u++)
	for (var v = -1; v < 2; v++)
	{
		var cell = c + new CVec(u, v);
		if (resources.Contains(cell) && resources[cell].Type == type.Info.ResourceType)
			adjacent++;
	}
```
which breaks our rule against hanging braces.

Some basic searching suggests that `csharp_prefer_braces = when_multiline` may be a better fit, but I haven't been able to find a strict definition of what that rule actually requires.

**Comment by ocdi** [comment]
@pchote I originally authored that PR, and apologise for setting it to `false:error`. I probably should have not been so agressive with that setting. There are two aspects, it was originally without severity, but set to `false` and in response to some PR feedback, I observed that Visual Studio wasn't flagging my code as incorrect, per your code standards.

I believe you are correct, it should be `when_multiline`.

Having said all that, I have not been able to get this warning to flag in Visual Studio 2019 (16.6.4).

**Comment by ocdi** [comment]
Actually upon further reading of https://github.com/dotnet/roslyn/issues/40912 it appears this feature is not fully implemented or operational, and it also reads to me that the `when_multiline` is in use, it would require braces for the single line statements, with return on following line, which I know is against your coding standard.

Perhaps this setting should be removed entirely.
