### ISSUE TITLE
Box selection of units behaves weirdly when mixing mine layers and other units

### ISSUE THREAD

**Issue by sdjmchattie** [OpenRA/OpenRA#18456]
## Issue Summary

When playing as allies in the RA mod, you can build mine layers.  If you do this and the place the mine layers near units of other types, the selection mode by dragging a box starts to behave strangely.  As you drag the box over mine layers, each mine layer becomes selected, but as soon as you touch a unit that's not a mine layer, all the previously selected mine layers become deselected and cannot be added to the selection during this mouse drag.  If you start the selection with units that are not mine layers, all mine layers that enter the selection area are not selected.  The system prefers to select non-mine layers and won't tolerate mixed selections.

## Reproduction

1. Start a skirmish game as Allies.
2. Build a construction yard, power, refinery, war factory and service depot.
3. Construct two tanks and a mine layer and move them to an open location.
4. Click and drag to draw a box around the units.

## Expected behavior

All three unit should be selected.

## Actual behaviour

The two tanks get selected and the mine layer is not selected.  If the box touched the mine layer first, it becomes selected to start with, and loses selection when the first tank touches the selection box.

**Comment by abcdefg30** [comment]
This sounds like intentional behaviour to me, as selecting Minelayers is IIrc handled like for example Harvesters: Army first, then "support" units. You should be able to select all units in the box by holding down `ctrl`. (And holding `alt` should only select the Minelayers not support units.)

**Comment by sdjmchattie** [comment]
OK yes you're right.  I didn't realise that was intentional behaviour but those key combinations do make the selection work in the way you described.

**Comment by abcdefg30** [comment]
Ok, good to know the issue is 'resolved'. :)
