### ISSUE TITLE
FireClusterWarhead missing CurrentMuzzleFacing

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#18452]
The Rank 5 abilities were crashing the game since the last engine update in RV. Seems like FCW is missing CurrentMuzzleFacing while creating the ProjectileArgs. Adding it fixes the crash.

https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Warheads/FireClusterWarhead.cs#L80

**Comment by pchote** [comment]
Should be a simple fix, do you want to file a PR?
