### ISSUE TITLE
Add support for upfront payment production

### ISSUE THREAD

**Issue by deleted-user-1** [OpenRA/OpenRA#18451]
## Motivation

The current production system takes away a lot of strategic options by forcing you to spend your resources as fast as you earn. With upfront production cost payment combined with tech trees, games can have more depth, more interesting balance options and make player decisions more meaningful, resulting in overall more diverse gameplay.

## Proposed solution

Add support for payment in advance.

**Comment by tovl** [comment]
This would also make tiberium silos actually useful.

**Comment by dnqbob** [comment]
good point for mod and non-cnc alike RTS developing

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/21295
