### ISSUE TITLE
AI attempts to kill tanks and base defences with dogs

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#18478]
Dogs chase tanks

**Comment by abcdefg30** [comment]
Basically the same as #3468.

**Comment by PunkPun** [comment]
Then it might be good to merge this issue into #3468

ping @Mailaender

**Comment by PunkPun** [comment]
ping @Mailaender

**Comment by Mailaender** [comment]
Duplicate of #3468
