### ISSUE TITLE
OpenRA talk/workshop @ Kieler Open Source und Linux Tage Online?

### ISSUE THREAD

**Issue by m23project** [OpenRA/OpenRA#18507]
Hi,

does anybody like to hold a talk or make a workshop about OpenRA during the Kieler Open Source und Linux Tage Online (18th + 19th of September 2020)?

More information at https://kieler-linuxtage.de/referenten-info .

Cu Hauke

**Comment by Mailaender** [comment]
I submitted a talk that will also cover https://github.com/OpenHV/OpenHV/issues/144.

**Comment by Mailaender** [comment]
https://kieler-linuxtage.de/p/KOLT20#471
