### ISSUE TITLE
My game crashed

### ISSUE THREAD

**Issue by codename-warhammer09** [OpenRA/OpenRA#18504]
## System Information
- Operating System:  Windows 10
- OpenRA Version: Release 20200503
- OpenRA Mod: Red Alert
- Source: Official Download Package

## Exception log
OpenRA engine version release-20200503
Red Alert mod version release-20200503
Date: 2020-08-09 17:12:19Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object.
   at OpenRA.ModData.PrepareMap(String uid)
   at OpenRA.Game.StartGame(String mapUID, WorldType type)
   at OpenRA.Game.LoadShellMap()
   at OpenRA.Mods.Common.LoadScreens.BlankLoadScreen.StartGame(Arguments args)
   at OpenRA.Game.InitializeMod(String mod, Arguments args)
   at OpenRA.Primitives.ActionQueue.PerformActions(Int64 currentTime)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)

## Additional information
OpenRA has been working completely normal for a while and I have been playing it for a while. But today It crashed at the main menu when I run it and it crashes at the same point. At multiple tries it has been observed to not even get past the loading screen and crashes. I did reinstall it multiple times to no effect. The exception log didn't even generate for literally most of the times it crashed. I had to restart my computer, and then it barely generated the crash report above. I did try and run it on compatibility mode as well. Nothing seems to work.

**Comment by Mailaender** [comment]
Can you upload your `perf.log` (which shows the maps it's trying to load) and `debug.log` (for completion sake)?

**Comment by Mailaender** [comment]
Compatiblity mode won't get you far (this isn't an old game) but turning off Windows Defender Ransomware protection or other Anti Virus protecting your file system (I suspect that is why it can't write logs) may help.

**Comment by codename-warhammer09** [comment]
Well, this is awkward. It seems to have fixed itself. Thanks for replying though.
