### ISSUE TITLE
"SquadManagerBotModule" bugs and question

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#18500]
### Bug Report:

It seems there are in fact two ground squad both using `GroundState` logic right? Rush and Assault squad.

In `TryToRushAttack(IBot bot)`, although there is a filter which is `unit => unit.IsIdle` try pick out units that should probably not in any squad but it is not that effective. Sometimes the Rush squad can still cover some of the Assault squad units, which will lag both of the squads when they heading towards different directions. I observed one in my playtest.

In addtion, `ProtectOwn` can also build a protection squad with other squads units.

### Question:

I find "SquadManagerBotModule" use `AttackOrFleeFuzzy` which is related to a third party DLL. How is the cost effect of this dll related class? I mean even if it is a wonderful component, if it is time costing we still need a simpler method on can-attack section, considering there can be 8+ AI in OpenRA maps and we need performance other than precise results.

**Comment by deleted-user-1** [comment]
It seems you are in the middle of a refactor with work spanning over three different upstream repositories. Are you sure the purpose of this issue is understandable for other people and that it wouldn't be better to discuss your ideas and questions in irc, forum or discord?

I find it hard to understand what the bug is, but this could very well be because I'm not a developer. If this is a bug report, could you outline what the actual issue here is? Or is this an enhancement request? Then outline the motivation and proposal if possible. It is currently not clear to me under which condition this issue can be resolved.

**Comment by deleted-user-1** [comment]
Based on the linked PRs it seems that this issue is about AI units being assigned to multiple squads at the same time.

**Comment by dnqbob** [comment]
To understand the **first bug**,  firstly,  there in fact two ground squads (Rush and Assault) in squad manager. They use the same ground state machine but have different recruitment and initial target. 

The problem is the recruitment method of Rush team has a chance to recruit an Assault squad unit,  and due to regroup mechanics of ground squad state machine,  the shared units will regroup to different squad every tick and lag the other squad.  When two squads heading towards different locations,  the two squads will both stuck and the shared units will wander between squads until enemy come at face.  If enemy won't come,  the both squads will recruit members but stuck at the same place,  which will also lag the game if stuck units are too many.

**Comment by dnqbob** [comment]
Then the second bug,  the protection team also has this bug,  and it's even worse in code. When attacked,  the recruitment of protection squad will call all the units can fight around a certain base center,  ignores whether it is already in squad or not.

**Comment by dnqbob** [comment]
The third is a performance worries,  I don't know if the fuzz dll is time costing and responsible for lagspike which appears at late game in original bleed.

**Comment by deleted-user-1** [comment]
So both the first and second issues have in common that units are in more than one squad at the same time. Do you think it makes sense and is possible to fix this issue isolated from other improvements you might want to do? Then this issue could focus on this part and leave AI design considerations to future discussions.

**Comment by dnqbob** [comment]
I think it should be fixed,  for at least first bug. Because it is relatively isolated and has the possibility on lagging the game (The protection squad in squad manager is also what I want to fix due to the same lagging concern, maybe after first problem. The patch I offered to other mods is AI overall updates and it is isolated from the bleed branch here).
