### ISSUE TITLE
Address issues identified by PVS-Studio

### ISSUE THREAD

**Issue by phrohdoh** [OpenRA/OpenRA#18518]
https://medium.com/pvs-studio/unicorns-break-into-rts-analyzing-the-openra-source-code-89d32ce5a5a1
- [x] meaningless conditions
  - [x] Analyzer warning: V3022 Expression ‘Active’ is always true. SupportPowerManager.cs 206
  - [x] Analyzer warning: V3022 Expression ‘highlightStart > 0’ is always true. LabelWithHighlightWidget.cs 54
  - [x] Analyzer warning: V3063 A part of conditional expression is always true if it is evaluated: cancelButton != null. ConfirmationDialogs.cs 78
- [x] unreachable code
  - [x] Analyzer warning: V3022 Expression ‘!order.Queued && currentTransform.NextActivity != null’ is always false. TransformsIntoTransforms.cs 44
- [x] use of uninitialized variable in constructor
  - [x] Analyzer warning: V3128 The ‘Frames’ field is used before it is initialized in constructor. CursorSequence.cs 35
- [x] potential typos
  - [x] Analyzer warning: V3127 Two similar code fragments were found. Perhaps, this is a typo and ‘oldMapRamp’ variable should be used instead of ‘oldMapHeight’ Map.cs 964
- [x] always returning `true` (Note: ticked because this is a false positive that won't be fixed)
  - [x] Analyzer warning: V3009 It’s odd that this method always returns one and the same value of ‘true’. LobbyCommands.cs 123
- [x] unnecessary `null` checks
  - [x] Analyzer warning: V3022 Expression ‘lobbyInfo == null’ is always false. LobbyCommands.cs 851
- [x] possible `NullReferenceException`s
  - [x] Analyzer warning: V3125 The ‘logo’ object was used after it was verified against null. Check lines: 236, 222. ConnectionLogic.cs 236
- [x] use `*OrDefault` method variants in place of `Get` & `null` checks (since `Get`-type methods throws if not found)
  - [x] Analyzer warning: V3063 A part of conditional expression is always true if it is evaluated: terrainGeometryTrait != null. MapEditorLogic.cs 35
  - [x] Analyzer warning: V3022 Expression ‘frameSlider != null’ is always true. AssetBrowserLogic.cs 128
- [x] lost assignment
  - [x] Analyzer warning : V3008 The ‘widget.Bounds.Width’ variable is assigned values twice successively. Perhaps this is a mistake. Check lines: 78, 75. SpawnSelectorTooltipLogic.cs 78
- [x] "Checking the default value" (more possible NREs)
  - [x] Analyzer warning: V3146 Possible null dereference of ‘tooltip’. The ‘FirstOrDefault’ can return default null value. Disguise.cs 192

**Comment by phrohdoh** [comment]
Since #18519 has been merged, it'd be good to check-off the issues it addressed.

**Comment by pchote** [comment]
Can someone edit the opening post to include the specific error messages? This will make it a lot easier to check off fixes.

For example this one has been fixed:
> V3022 Expression ‘Active’ is always true. SupportPowerManager.cs 206

but this one hasn't yet:
> V3022 Expression ‘!order.Queued && currentTransform.NextActivity != null’ is always false. TransformsIntoTransforms.cs 44

**Comment by phrohdoh** [comment]
> Can someone edit the opening post to include the specific error messages?

Good idea.  Done.

**Comment by KonH** [comment]
@phrohdoh 
Code around "unreachable code" issue is changed several times so it can be considered as outdated.
Also, it looks like the last issue in the list already fixed in https://github.com/OpenRA/OpenRA/pull/18604 and can be marked.
As I see now issue can be closed (all tasks done) or required analytics re-run.

**Comment by abcdefg30** [comment]
> Code around "unreachable code" issue is changed several times so it can be considered as outdated. Also, it looks like the last issue in the list already fixed in #18604 and can be marked. As I see now issue can be closed (all tasks done) or required analytics re-run.

Thanks for the reminder, I filed #19710 for the last bullet point then this should be resolved.
