### ISSUE TITLE
IndexOutOfRangeException

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#18523]
## System Information

- Operating System : Windows 10
- OpenRA Version : release-2020-05-03
- OpenRA Mod : Red Alert
- Source : Official download package

## Exception log

OpenRA engine version release-20200503
Red Alert mod version release-20200503
on map 59a4ba5e01e47cfccd0a6f7285eda8f6d8ac103d (Hot Tactical War 4 by Castle of Doom).
Date: 2020-08-14 20:49:29Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IndexOutOfRangeException`: L'index se trouve en dehors des limites du tableau.
   à OpenRA.Mods.Common.Traits.Locomotor.GetCache(CPos cell)
   à OpenRA.Mods.Common.Traits.Locomotor.CanStayInCell(CPos cell)
   à OpenRA.Mods.Common.Traits.MobileInfo.CanStayInCell(World world, CPos cell)
   à OpenRA.Mods.Common.Activities.MoveAdjacentTo.<CandidateMovementCells>b__14_0(CPos c)
   à System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   à OpenRA.Mods.Common.Activities.MoveAdjacentTo.CalculatePathToTarget(Actor self, BlockedByActor check)
   à OpenRA.Mods.Common.Activities.Move.EvalPath(BlockedByActor check)
   à OpenRA.Mods.Common.Activities.Move.OnFirstRun(Actor self)
   à OpenRA.Activities.Activity.TickOuter(Actor self)
   à OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act)
   à OpenRA.Activities.Activity.TickChild(Actor self)
   à OpenRA.Mods.Common.Activities.MoveAdjacentTo.Tick(Actor self)
   à OpenRA.Activities.Activity.TickOuter(Actor self)
   à OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act)
   à OpenRA.Activities.Activity.TickChild(Actor self)
   à OpenRA.Activities.Activity.TickOuter(Actor self)
   à OpenRA.Traits.ActivityUtils.RunActivity(Actor self, Activity act)
   à OpenRA.Actor.Tick()
   à OpenRA.World.Tick()
   à OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   à OpenRA.Game.LogicTick()
   à OpenRA.Game.Loop()
   à OpenRA.Game.Run()
   à OpenRA.Game.InitializeAndRun(String[] args)
   à OpenRA.WindowsLauncher.RunGame(String[] args)

## Replay

Replay available at https://ufile.io/yd7irz1m

## Additional information

We were playing a 4v4 game with nothing special and it suddenly crashed.
I don't know the map, maybe it has some fancy stuff.
Complete Logs directory available at https://ufile.io/bv6teqs4

**Comment by deleted-user-1** [comment]
Hi, thanks for taking time to report this. This was first reported in #18034 and fixed by #18083. Next release will include the fix.
