### ISSUE TITLE
D2k harvester at repair pad is stuck with carry-all

### ISSUE THREAD

**Issue by dandrejvv** [OpenRA/OpenRA#18522]
## Issue Summary

Harvester that is finished being repaired on the repair pad just can't move away and the carry-all just keeps on moving up and down above the harvester and it never ends until you sell or destroy the repair pad. You also can't command them to move or stop or anything (I've tried a lot).

## Reproduction

After you have a refinery and harvester, build a repair pad and order a carry-all. Command the harvester to move to the repair pad and the carry-all will transport it to the repair pad. Once the harvester needs to move from the repair pad, the carry-all gets stuck and the harvester is also stuck.

## Expected behavior

The carry-all should be able to pick up the harvester from the repair pad and drop it off where it was before.

## Screenshots / Screen recordings / Replays

Let me know if this is necessary

**Comment by Smittytron** [comment]
This will be fixed in the next release by #18350.
