### ISSUE TITLE
Invalid path in uninstall registry entry

### ISSUE THREAD

**Issue by CH4Code** [OpenRA/OpenRA#18535]
## Issue Summary

DESCRIPTION
My registry cleaner tool found a (potential) problem with one of the uninstall paths stored in the windows registry. (invalid file path)
The path in QuietUninstallString seems to be incorrect, since the file name of the uninstaller is uninstallER.exe not uninstall.exe.
Btw. I have no idea what quiet uninstall is and if it is important or not.
Cheers,
    SirCake

## Reproduction

STEPS TO REPRODUCE THE ISSUE

1. win key + type "regedit"
2. navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\OpenRA folder
3. look at the QuietUninstallString ;)

## Expected behavior

EXPECTED BEHAVIOR
path is ..\..\..\uninstaller.exe /S

## Screenshots / Screen recordings / Replays

![grafik](https://user-images.githubusercontent.com/16046997/90512688-cfefdc00-e15e-11ea-90f9-6229641acbc0.png)

**Comment by pchote** [comment]
This will be a simple fix, so adding to the milestone.

**Comment by phrohdoh** [comment]
https://github.com/OpenRA/OpenRA/blob/c2026dc254a81e7c11fbff48230ca57fe979e3d8/packaging/windows/OpenRA.nsi#L229 is the file & line that need to be updated.
