### ISSUE TITLE
Player can build over specific cliffs

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#18545]
## Issue Summary

This is an old issue that need to be fixed.
Players are able to build over specific cliffs.

## Reproduction

![build over cliffs](https://user-images.githubusercontent.com/5400487/90698342-1f322b80-e289-11ea-85a4-f980fd7609cf.png)

## Expected behavior

Players should not be able to build over cliffs

**Comment by pchote** [comment]
IIRC from previous discussions this is only possible for certain specific cliff orientations, and IMO is a map design bug. The map author should put a rock, tree, or other blocker to stop this if that is their intention.

**Comment by KOYK** [comment]
Fair enough, I will close this then

**Comment by pchote** [comment]
This is still a legitimate bug IMO, just easier to fix than some might assume.

**Comment by KOYK** [comment]
~~ill keep it open for the time being then, I was going to make PR for it, if it is accepted or not it will be fine by me.~~
Never mind.
