### ISSUE TITLE
Add support for multiple sound effects to pick from in weapon report

### ISSUE THREAD

**Issue by henskelion** [OpenRA/OpenRA#18541]
Currently the sound effects used for weapons firing is very limited, since a weapon can only have a single sound effect applied to it. Ideally this could be improved so that a weapon will have a list of audio files to randomly pick from under Report for every instance of the weapon firing, since only have a single sound for every weapon type is very archaic and unrealistic.

**Comment by phrohdoh** [comment]
Some references links:
- https://github.com/OpenRA/OpenRA/blob/d52e4793fe1c240a3dcd6e6ea37eb27514c2e3d4/mods/ts/weapons/smallguns.yaml#L28
- https://github.com/OpenRA/OpenRA/blob/d52e4793fe1c240a3dcd6e6ea37eb27514c2e3d4/OpenRA.Game/GameRules/WeaponInfo.cs#L84-L85
- https://github.com/OpenRA/OpenRA/blob/d52e4793fe1c240a3dcd6e6ea37eb27514c2e3d4/OpenRA.Game/Sound/Sound.cs#L144-L161

**Comment by abcdefg30** [comment]
So this already works as requested in the OP?

**Comment by phrohdoh** [comment]
> So this already works as requested in the OP?

I _think_ it is expected to work already _iff_ one of these methods is invoked:

https://github.com/OpenRA/OpenRA/blob/d52e4793fe1c240a3dcd6e6ea37eb27514c2e3d4/OpenRA.Game/Sound/Sound.cs#L153-L161

`Armament.FireBarrel` appears to invoke the 2nd one from above:

https://github.com/OpenRA/OpenRA/blob/9c4fd0e3d37f64b0c426b152ab364a6baa0ca51e/OpenRA.Mods.Common/Traits/Armament.cs#L329-L330

@henskelion, are you able to provide a small reproduction case of this issue?

**Comment by henskelion** [comment]
So it looks like this is all just a big mistake, probably induced by me staying up until 5am to work on my mod. I just tested the weapon report sounds some more and realized they do indeed select randomly from a list, and I was just being stupid.

You can close this issue, sorry for wasting your time.
