### ISSUE TITLE
Anti air - less than 100% hit

### ISSUE THREAD

**Issue by marcos737** [OpenRA/OpenRA#18569]
Hi,

i have one proposal for anti air attack. Now, every hit of rocket / bullet is 100 % (when unit is in range). I am proposing to use less than 100%  of hit. How much, it need to be tested. This can bring more fun for game.

Thanks

**Comment by abcdefg30** [comment]
Feature-wise, this is already possible by setting the inaccuracy of the bullet. Balance suggestions are better discussed on the forums or Discord (it isn't as visible here and won't get much discussion), so I'd suggest taking ideas there.
