### ISSUE TITLE
OpenRA 20200503 crashes with Windows 10 Version 2004

### ISSUE THREAD

**Issue by Claudedeus** [OpenRA/OpenRA#18568]
Downloaded and installed OpenRA-release-20200503-x64 after Windows (10 Pro) update to Version 2004 OS Build: 19041.450 and Experience Pack: 120.2212.31.0.
Tried to launch Tiberian Dawn, got a pop-up saying: 
SDL_app: TiberianDawn.exe - Bad Image
![TiberianDawn](https://user-images.githubusercontent.com/64212554/91531565-5622d400-e950-11ea-8bcb-48c5ab3b6cd3.png)

Clicking to close the message it comes back three or four times before disappearing (if that helps any).

**Comment by abcdefg30** [comment]
Hi, this looks like an error in your graphics card driver (I suppose it is NVIDIA?). Can you try updating your driver?

**Comment by Claudedeus** [comment]
Sorry for the delay guys, but I'm in Australia...
Updating the Nvidia driver did the trick. (I have a GeForce GT 1030). But for those that may have the same issue, note that straight after the Windows update to 2004, there was an update (KB4569745) of .NET framework 3.5 and 4.8 as well, so I'm not sure what caused the issue (even though I think one update requires the other...)
Thank you abcdefg30 !! 👍

**Comment by Claudedeus** [comment]
Hasta la vista baby! Good gaming everyone!
