### ISSUE TITLE
Airstrike Power provides permanent vision

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#18564]
![001526](https://user-images.githubusercontent.com/42915475/91325065-c1be4300-e790-11ea-9cf2-c17248fc3c40.png)

Using the airstrike support power near the edge of the map and taking the long way (does not approach from that edge) results in permanent vision.

Does not affect other support powers (spy plane, parabombs, etc).

**Comment by dragunoff** [comment]
Thanks for the report. This was fixed in #18294
