### ISSUE TITLE
Make "Elite" units auto-target in attack-moves the best enemy unit

### ISSUE THREAD

**Issue by Yara-smurf** [OpenRA/OpenRA#18576]
## Motivation
To make "Elite" ("General") units more interesting, we could give them instead of a simple damage-percentage-increase a special feature where they will auto-select the best enemy unit. Rockets go always for tanks in their range, Rifles for other Rifles, etc. 

## Proposed solution
Tanks -> Tanks 
v2 -> inf 
Rifles -> rifle 
Rocket -> Tank
... -> ... 

Might be not so easy, as the best-enemy-unit it different for each unit, so it would have to specified for all of them :/ 

## Side effects
Not sure if there are any negative side effects.

## Alternatives
To keep it as it is with a damage-bump for them.

**Comment by Yara-smurf** [comment]
Ah, possible impact in game: 
They are really juicy and enemies probably have to micro-shoot them first, as they are so dangerous. Increases the skill-ceiling.

**Comment by pchote** [comment]
The `AutoTargetPriority` traits were designed with exactly this kind of use case in mind, so there are no technical barriers for implementing this. It should even be doable in mod maps on the current release.

**Comment by Yara-smurf** [comment]
That is great news! 

I will discuss with some others what they think and who should be the AutoTargets and post it here.

**Comment by Smittytron** [comment]
I brought this up in the Discord balance-and-playtesting channel. Most disagreed as they felt it didn't add much. There were some that opined auto-target takes too much away from micro.

Closing as there's not enough support to look into this.

**Comment by Leo512bit** [comment]
Sorry that it's a year later I might have some time now to pick up on this. I feel it can make veterancy more useful, because right now its kind of underwhelming for those who don't play competitively.
