### ISSUE TITLE
Eluant-LuaException - [string "BindingSupport.lua"]:30: Unable to convert parameter 0 to Actor

### ISSUE THREAD

**Issue by capgenemy** [OpenRA/OpenRA#18584]
## System Information
- Operating System:  Windows 10
- OpenRA Version: 20200503
- OpenRA Mod: Tiberian Dawn mod
- Source: Official download package

## Exception log
```
OpenRA engine version release-20200503
Tiberian Dawn mod version release-20200503
on map 8a31e50d90e3a472f9ca951b482c9d5d74a65e4f (C&C64 Special Ops - GDI 1 by Westwood Studios).
Date: 2020-09-03 23:06:04Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `Eluant.LuaException`: [string "BindingSupport.lua"]:30: Unable to convert parameter 0 to Actor
   en Eluant.LuaRuntime.Call(IList`1 args)
   en Eluant.LuaRuntime.Call(LuaFunction fn, IList`1 args)
   en Eluant.LuaFunction.Call(IList`1 args)
   en OpenRA.Mods.Common.Scripting.ProductionQueueProperties.<>c__DisplayClass3_2.<Build>b__4(Actor factory, Actor unit)
   en System.Action`2.Invoke(T1 arg1, T2 arg2)
   en OpenRA.Mods.Common.Scripting.ScriptTriggers.OpenRA.Mods.Common.Traits.INotifyProduction.UnitProduced(Actor self, Actor other, CPos exit)
   en OpenRA.Mods.Common.Traits.Production.<>c__DisplayClass6_0.<DoProduction>b__0(World w)
   en OpenRA.World.Tick()
   en OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   en OpenRA.Game.LogicTick()
   en OpenRA.Game.Loop()
   en OpenRA.Game.Run()
   en OpenRA.Game.InitializeAndRun(String[] args)
   en OpenRA.WindowsLauncher.RunGame(String[] args)
```

## Additional information
This crash happens on a saved game of level "C&C64 Special Ops - GDI 1". It always crashes in the same moment, a few seconds after loading my savegame. Before that, It crashed when I was playing. Then I loaded my savegame and after that, it crashed in the same situation, but there's not an understandable reason for it to happen (I tried several things for myself, like making all units and queues stop, but it haven't worked). I attach my savegame for better testing. Thank you so much!!

[C&C64 Special Ops - GDI 1.zip](https://github.com/OpenRA/OpenRA/files/5171837/C.C64.Special.Ops.-.GDI.1.zip)

**Comment by abcdefg30** [comment]
Thanks for the report!
This was already fixed by #18152 for the next release. :)
