### ISSUE TITLE
Allow to specify the unit stance for buildings

### ISSUE THREAD

**Issue by MVBarros** [OpenRA/OpenRA#18594]
## Motivation

There is currently no way to define the default stance for new units.  This can be tedious as new units may be created with a stance that is not ideal for the current situation, and the player as to manually set it.

## Proposed solution

Allowing to define a stance to production buildings. Units that come out of these buildings will inherit this stance. This was present in CnC 3, but not the original games. It can be a great quality of life and user experience improvement.

**Comment by deleted-user-1** [comment]
Duplicate of #13817?
