### ISSUE TITLE
Civilians wander onto Tiberium and spawn Visceroids

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#18600]
This random event can give an advantage to one player, or just end the game if it occurs in the first few minutes.

A possible solution is to have civilians avoid Tiberium, as suggested here: #18421

**Comment by pchote** [comment]
We could bodge a workaround, but really the whole `Wanders` code needs a rewrite. My understanding is that this was a nice-to-have rather than a critical issue, so bumping to Next + 1.
