### ISSUE TITLE
Facing support for idle overlay

### ISSUE THREAD

**Issue by ABrandau** [OpenRA/OpenRA#18609]
Right now, the only way to add extra decorations to a unit is an idle overlay, this supports custom offsets and custom palettes, but does not support facings, if you were to add something like a flashlight or a speaker tower into a vehicle, there is no way to make it support such, you can add a second instance of WithSpriteBody but that does not have palette support, limiting you to the original 256 colors.

**Comment by reaperrr** [comment]
We'll want to keep the (ab)use of multiple sprite bodies per actor to a minimum anyway, so this is a reasonable request in more than one way. Should target Next+1.
