### ISSUE TITLE
Infantry and vehicles stand still after being built, despite rally direction given to their creator (barracks, war factory, etc.)

### ISSUE THREAD

**Issue by fusion809** [OpenRA/OpenRA#18611]
## Description

I've been playing a game of RA built from commit 290e214 (I played a git build of RA yesterday and it didn't have a problem) and engineers and vehicles when they're built stand still even though I've clicked on the barracks and set a path where I want them to go once they're built. If you click on the engineers or vehicles individually and order them to go somewhere (even the exact same place as you've set the rally point for the barracks to) they will, however.

## Reproduction
Play Red Alert built from commit 290e214 on the Vegetation map (may exist with other maps, but the only map I've tried to reproduce this with so far is Vegetation), build a barracks, click on it and click on somewhere you want the engineers to go (shouldn't matter where, it doesn't seem to matter where you set the rally point) and you should notice this bug (as the engineers will not go anywhere). 

## Expected behaviour
For the engineers to go where they're ordered?

## Screenshots / Screen recordings / Replays
I'm still playing the game, so I can't give you the replay, but here's a saved game if it helps:

[Veg.zip](https://github.com/OpenRA/OpenRA/files/5222283/Veg.zip)

**Comment by fusion809** [comment]
Here's my replay, just finished the game I was playing.

[static-vehicles-and-infantry.zip](https://github.com/OpenRA/OpenRA/files/5222326/static-vehicles-and-infantry.zip)

**Comment by fusion809** [comment]
Oh and I found the latest commit that I played that had no problems with it, b16cbea.

**Comment by MustaphaTR** [comment]
Already has a PR for fix: #18605

**Comment by fusion809** [comment]
Yep it works at fixing this bug.
