### ISSUE TITLE
Add Tileset check for Bridge trait

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#18659]
## Motivation

If any one wants to add compatibility between TD and RA maps so they can work under the same mod, the bridge trait will pose as problem because it won't look for a tileset, so for example, if snow tileset is taken from RA and placed on TD, it will result on having cliffs being used as bridges, because the bridge trait looks only for the terrain template.

## Proposed solution

Add Tileset check for Bridge trait

## Side effects

Can't think of any.

## Alternatives

Can't think of any.

**Comment by KOYK** [comment]
It wont be fixed\added, closing it.

**Comment by pchote** [comment]
This will be addressed when bridge artwork definitions are moved to sequences (needed for remaster compatibility).
