### ISSUE TITLE
build queue multiplier buttons to build many with one click

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#18653]
on high ore maps i typically build constantly 10 soldiers of certain types.

it means i constantly have to click 10 times to fill up the build queue. allowing me to focus on the game after.

request:
- have three icon/buttons labelled x5 x10 x20 in the build tab of barrack units.
- allow players to enable/disable them with one click.
- once enabled, clicking a build item will queue 5, 10 or 20 of the items.
- similar cancelling items from the queue will cancel x items.

goal:
- less mouse clicks, anti rsi, be able to quickly queue the building of 100s of units 
- avoid the build queue running empty, i.e. after you queued 50 units you give up clicking to find out later the 50 were built and no units are already not being build for minutes

alternative:
- vim-like keyboard shorcuts .. allowing you to type ':&lt;number&gt;' and after click the item you want to build or cancel. i.e. ':99' would queue the build of 99 units of the next unit clicked.
- rather than icons some short cut key i.e. ctrl + click will queue 10 items over 1

**Comment by dragunoff** [comment]
The <kbd>Shift</kbd> key already acts as a multiplier for the build queue. However it is hard-coded to 5 units. Adding UI that exposes this and allows for changes is something that I have also thought about. The technical implementation shouldn't be hard but the UI will need some consideration (the UI may also expose other production queue options and modifiers). I think putting together a mock-up would be useful.

**Comment by anvilvapre** [comment]
i didn't knew about the shift key. good to know.

**Comment by anvilvapre** [comment]
Open for many years. Not wanted enough.
