### ISSUE TITLE
south america and asia default server

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#18655]
quite often players from asia and south america join in on eu or us game servers. their connection aren't always the fastest. 

because they are kicked out of many games for their connection speeds it might be nice to try to get a community going in those areas by having one or few good servers in that region.

**Comment by Mailaender** [comment]
@Baxxster has it on the agenda https://www.patreon.com/orahosting/membership defined as a stretch goal.

**Comment by anvilvapre** [comment]
Number of servers seems to have increased over the years in different geo locations.
