### ISSUE TITLE
Add Tiberian Sun forest fire/tree burning logic

### ISSUE THREAD

**Issue by henskelion** [OpenRA/OpenRA#18657]
Tiberian Sun included logic for tree flammability. This didn't just mean fire weapons damage trees, but that warheads with the "sparky" function would set trees on fire, creating a looping flame animation on the tree that would slowly damage it, while also having a random chance every frame to spread to nearby trees.

Articles on how this logic worked can be found here and here:

https://www.modenc.renegadeprojects.com/TreeFlammability

https://www.modenc.renegadeprojects.com/TreeFire

**Comment by Mailaender** [comment]
This is how I did it https://github.com/OpenHV/OpenHV/commit/92f63592cc65da61e7cc3bc43da862a4dbb2f701 in @OpenHV.

**Comment by pchote** [comment]
The TreeFlammability and TreeFire entries give a good explanation on how to implement the ignition and spread probabilities.

The damage and animation switching from big to small to none is implemented using the standard animation system with FIRE1, FIRE2, FIRE3 in art.ini that are essentially self documenting.
