### ISSUE TITLE
/bin/sh: 1: msbuild: not found Makefile:172: recipe for target 'cli-dependencies' failed make: *** [cli-dependencies] Error 127

### ISSUE THREAD

**Issue by WuDiDaBinGe** [OpenRA/OpenRA#18690]
## Issue Summary

/bin/sh: 1: msbuild: not found
Makefile:172: recipe for target 'cli-dependencies' failed
make: *** [cli-dependencies] Error 127

## Reproduction

Ubuntu 16.04 
I haved used the command in install.md but i still get this issue.

## Screenshots / Screen recordings / Replays
yuxiubin@yuxiubin-VirtualBox:~/文档/OpenRA$ make all
/bin/sh: 1: msbuild: not found
Makefile:172: recipe for target 'cli-dependencies' failed

**Comment by OpenOP2Admin** [comment]
https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu

https://www.mono-project.com/download/stable/#download-lin install mono-complete

**Comment by OpenOP2Admin** [comment]
Did this help the guy? Should we wait for a response prior to closing?

**Comment by WuDiDaBinGe** [comment]
> Did this help the guy? Should we wait for a response prior to closing?

Yes I haved this issue.Thank you！
