### ISSUE TITLE
AI Airstate broken on TS/RA2 maps

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#18705]
## To put it simple about this bug

Because the elements in `checkIndice` array are always positive in scanning function:

```
var checkIndices = Exts.MakeArray(columnCount * rowCount, i => i).Shuffle(owner.World.LocalRandom); 
```

while in those isometric maps in TS/RA2, the cell index can be negative like:
<img width="469" alt="1" src="https://user-images.githubusercontent.com/13763394/95671771-39272500-0bcd-11eb-82a1-a571e1d364fb.png">
and the bounds index are not like the one used by RA1 maps.

Therefore, those negative index positions can be never targeted by any air force, which simply disables the air force that scanning from positive to negative and causes misbehaviour of AI.

## A possible simple fix
I change
```
			var checkIndices = Exts.MakeArray(columnCount * rowCount, i => i).Shuffle(owner.World.LocalRandom);
			foreach (var i in checkIndices)
			{
				var pos = new CPos((i % columnCount) * dangerRadius + dangerRadius / 2, (i / columnCount) * dangerRadius + dangerRadius / 2);
				
				if (NearToPosSafely(owner, map.CenterOfCell(pos), out detectedEnemyTarget))
				{
					if (needTarget && detectedEnemyTarget == null)
						continue;

					return pos;
				}
			}
```

into

```
			var checktime = columnCount * rowCount;

			for (var i = 0; i < checktime; i++)
			{
				var pos = map.ChooseRandomCell(owner.World.LocalRandom);

				if (NearToPosSafely(owner, map.CenterOfCell(pos), out detectedEnemyTarget))
				{
					if (needTarget && detectedEnemyTarget == null)
						continue;

					return pos;
				}
			}
```
Which will be more random and drop the average consideration, but compatible to isometric maps in TS/RA2. The interval of bot_tick is short (and it will run frequently), so air force can always find a target during my test.

## About better fix
My simple fix is good on isometric maps but I don't know if it is good for RA1/TD maps. And this fix drop the average consideration across the map, which I hope someone can have better idea on that.

**Comment by dnqbob** [comment]
if you agree I will pull request my fix here, or I will fix it for RV/SP only.

**Comment by reaperrr** [comment]
In my opinion a better solution to work around this for now would be to simply change `var pos` to

```
				// RectangularIsometric can have negative cell indices, which doesn't mesh with the positive assumption below.
				// For now we just use a completely random map cell on isometric maps instead.
				// TODO: Come up with a smarter solution for RectangularIsometric maps/mods.
				var pos = map.Grid.Type == MapGridType.RectangularIsometric ? map.ChooseRandomCell(owner.World.LocalRandom)
					: new CPos((i % columnCount) * dangerRadius + dangerRadius / 2, (i / columnCount) * dangerRadius + dangerRadius / 2);
```
and leave the rest untouched. That way we won't regress the non-isometric mods.

**Comment by dnqbob** [comment]
> 				var pos = map.Grid.Type == MapGridType.RectangularIsometric ? map.ChooseRandomCell(owner.World.LocalRandom): new CPos((i % columnCount) * dangerRadius + dangerRadius / 2, (i / columnCount) * dangerRadius + dangerRadius / 2);

Could we just simply divide those into two `if` or even two different function?


Update: because the array is unnecessary for RectangularIsometric maps.
