### ISSUE TITLE
StartBurstReport sounds plays repeatedly if used with an armament with a FireDelay

### ISSUE THREAD

**Issue by darkademic** [OpenRA/OpenRA#18729]
## Issue Summary

If an armament has a FireDelay and you use StartBurstReport, the sound will play repeatedly on every shot of the burst (as if Report was used) instead of only on the first shot of the burst. Without FireDelay, the sound plays once at the start of each burst as expected.

See: OpenRA.Mods.Common.Traits.Armament.FireBarrel()

Burst must somehow be equalling args.Weapon.Burst on each shot despite Burst being decremented.

## Reproduction

Make a weapon with Burst > 1 and a StartBurstReport sound but no Report sound. Use the weapon on an armament which has a FireDelay.

## Expected behavior

StartBurstReport should work the same irrespective of whether an armament has a FireDelay.

**Comment by pchote** [comment]
Is this a new regression on bleed, or something from the last release?

**Comment by darkademic** [comment]
> Is this a new regression on bleed, or something from the last release?

The behaviour is the same on latest release and bleed.
