### ISSUE TITLE
Running the game with Launch.Benchmark=true and starting a bot skirmish crashes the game

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#18725]
No exception.log is created.

**Comment by Mailaender** [comment]
It seems

https://github.com/OpenRA/OpenRA/blob/815bbc6ee82a8df308b5ecdea5d86857c2e2d7e7/OpenRA.Game/Game.cs#L953-L960

hits right when I leave the shellmap.

**Comment by abcdefg30** [comment]
I suppose this is meant to be used together with the Map argument to directly launch into a map (and not get "noise" from the shellmap).

**Comment by Mailaender** [comment]
Okay, guess I need to create a dedicated performance testing map for that then. Outcommenting

https://github.com/OpenRA/OpenRA/blob/a375f0e58a0d82db4e752a4e700d8d8365304716/OpenRA.Game/World.cs#L614

also helps. You only have to manually remove previous map entries from the files.
