### ISSUE TITLE
make it so that when a units that are headed to the repair pad/helipad wont be selected with other combat units(wishlist)

### ISSUE THREAD

**Issue by Zoniier** [OpenRA/OpenRA#18739]
title describes it all. make units heading back to repair/reload have a different selection group like the engineer/harvesters so that they don't get selected with the rest of the units when dragging a selection box?

**Comment by CortexReaver** [comment]
"Empty units" are often used as a bait for air defense. Not sure about that one.

**Comment by abcdefg30** [comment]
Closing as stale.

**Comment by PunkPun** [comment]
Rather as a duplicate of https://github.com/OpenRA/OpenRA/issues/17537
