### ISSUE TITLE
U/L-turns often don't end on one of the 8 N/NE/E... facings

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#18732]
This has become even more noticable with the updated classic facing fudging.

In my opinion it might be enough to just force the facing to the closest of the 8 main facings on the last tick of a U/L-move.

**Comment by pchote** [comment]
It might be worth studying the original games's track (between-cell) movement logic to get a proper feel for the behaviours that our special turns were trying to emulate.
