### ISSUE TITLE
Subterranean actors can start shooting while underground

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#18734]
Saw this in a TS AI game, a Devil's Tongue was constantly firing at a cell from underground (even when there weren't visible enemies on that cell).
Nearby enemies above also tried to attack it, but at least didn't shoot (this bug is possibly not directly related and just the AI code ignoring layers).

**Comment by pchote** [comment]
> (even when there weren't visible enemies on that cell)

Maybe an edge case in the AI frozen actor targeting?

**Comment by dnqbob** [comment]
I remember I found the same issue here.

You can use AttackMove to any enemy actors to reproduce this bug
