### ISSUE TITLE
RangeLimitModifier

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#18747]
I'm currently using the RangeModifier for veterancy in TD

https://docs.openra.net/en/latest/release/traits/#rangemultiplier

However, it came up that this doesn't affect RangeLimit. This means some missile based weapons dud before reaching their full (new) range.

It would be great if someone could add this, otherwise I'll have to do a non-ideal workaround.

**Comment by pchote** [comment]
Would there be any downside to simply applying the existing range modifiers to rangelimit?

A new `IRangeLimitModifier` is complicated by the fact that the range limit is a missile-specific thing, so its not really appropriate to add this to the `ProjectileArgs`, which means that we need to query the traits from the source actor every time a missile is created.

Adding a flag to Missile to optionally apply the range modifier to the range limit would be a compromise, but IMO unnecessarily messy compared to just universally applying it.

**Comment by Orb370** [comment]
Hm, I can't think of any downsides. Wanting to modify range without modifying rangelimit seems like a very niche use case.
