### ISSUE TITLE
Creeps should have color that is not identical to Neutral

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#18754]
Neutral hostile (Creep) is using same house color as Neutral passive, it should have a different color by default for easy identification.
Can propose defining an dark-grey near black, or simply black color to be used by the Creeps, seeing as Neutral is white.

**Comment by pchote** [comment]
IMO the best solution here is to make the default player definitions part of the mod-defined map format, when that feature eventually happens.

**Comment by abcdefg30** [comment]
This is already possible by giving creeps a color in map.yaml.
