### ISSUE TITLE
locally extract .MIX files on download and use the asset files directly

### ISSUE THREAD

**Issue by Jushdrug** [OpenRA/OpenRA#18767]
## Motivation

pros:
1. easy access to game assets for modders and map makers without having to learn how to deal with .MIX files.
2. no more need extract/repack (for modders at least).
3. with a seperate utility to handle the unpacking, regressions caused by updates to the game can be avoided.
4. opparently such an extract utility already exists and could be repourposed.
5. the code would probably be cleaner if it dealt with the files directly.

cons:
1. depending on how deeply .MIX is rootet in the games code it might be a lot of work to refactor.

## Proposed solution

after downlaoding game assets unpack them to an appropriate folder structure. The game will access the files directly intead of loading them from archives.

## Side effects

licensing issues?

**Comment by pchote** [comment]
Windows has significant performance problems with opening many small files, so another side effect would be increased loading times for many players. This also isn't compatible with our plan to read assets directly out of a steam/origin install without copying or modifying anything.

**Comment by abcdefg30** [comment]
Sorry, I don't think this is feasible.
I suggest simply extracting all the files with XCC once if you want them at the ready. Then you don't need to deal with it later on. Fwiw though, modding with those files will almost inevitably bring the need to use tools like the mixer or shp Builder regardless.
