### ISSUE TITLE
SetUpPlayer may lookup stance for player that it does not yet have a stance on. Bleed.

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#18764]
In bleed. Possible trivial bug. 

In World.cs `SetUpPlayer` is called prior to ensuring that a player `p` has a stance on any other player `q`.

In theory in `SetupPlayer` a stance could be looked up - in the stance dictionary - for a player that does not exist. I assume that in practice this does not occur.

Possible solution, call `SetUpPlayer` at the end of the same loop - after a stance for `q` is set.

OpenRA.Game/World.cs
225:                                    SetUpPlayerMask(p, q);
246:            void SetUpPlayerMask(Player p, Player q)

**Comment by pchote** [comment]
#18677 might already fix this?

**Comment by abcdefg30** [comment]
The initial stances are set in `CreatePlayers`. #18677 does rewrite a good chunk of it too, removing stance setups in World.cs.
