### ISSUE TITLE
ShadowLength

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#18776]
Sequences like

```salt
	idle:
		Length: 3
		ShadowStart: 3
		ShadowZOffset: 1768
		Combine:
			bits/base.png:
				Length: 3
				Reverses: true
				Tick: 150
			bits/base-shadow.png:
				Length: 1
				Offset: 7, -17
```

will not work 

```
OpenRA.Utility(1,1): Error: OpenRA.Mods.Common.Lint.CheckSequences failed with exception: OpenRA.YamlException: Sequence base.idle's shadow frames use frames [3..5], but only [0..3] actually exist
```

probably large due to this

https://github.com/OpenRA/OpenRA/blob/dd7b8b24af7d14cb086bb8c62e1b2f07122cb6f1/OpenRA.Mods.Common/Graphics/DefaultSpriteSequence.cs#L392-L395

so I propose a new field `ShadowLength` which allows shadow sprites to have a different length.

**Comment by pchote** [comment]
How would this actually work? The shadow logic from TS splits an image with the first N real images followed by N shadows. How do you match M shadows to N images if M != N?

**Comment by Mailaender** [comment]
I just realized that I can write a mod specific `SpriteSequence` for this which works differently so this shouldn't happen here where Westwood simply duplicated the artwork.
