### ISSUE TITLE
IsAlliedWith, unclear

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#18791]
May i ask,

I'm asking since the code is called often,

The below code is unclear to me. Even after reading it multiple times. 

If suspect the first two lines should be an if-else statement. Why look up the effective owner to then overwrite it again - or why set it to then call a method to set it again to the same value - seems costly. 

I assume the second statement is to make a cloaked unit only appear cloaked to the enemy. The two calls to IsAlliedWith seems overhead in some cases(?).

Is there a difference between IsAlliedWith(RenderPlayer) and IsAlliedWith(LocalPlayer)? I assume for spectators there is. But shouldn't the IsAlliedWith be called with the player argument then in both cases? And couldn't the second call be avoided?

https://github.com/OpenRA/OpenRA/blob/7b75a78e38a3772995f4217c4bcb8cc94c09f37a/OpenRA.Game/Player.cs#L237-L248

I suspect this is what is meant
```
                                var apparentOwner = a.Owner;
                                var effectiveOwner = a.EffectiveOwner;
                                if (effectiveOwner != null && effectiveOwner.Disguised)
                                {      
                                        // Only show cloaded to the enemy?
                                        if (!a.Owner.IsAlliedWith(worldRenderPlayer /* possibly null, shouldn't this be player? */))
                                                apparentOwner = effectiveOwner.Owner;
                                }

                                if (apparentOwner == player)
                                        return stanceColors.Self;

                                if (apparentOwner.IsAlliedWith(player))  // Possible second call
                                        return stanceColors.Allies;

                                if (!apparentOwner.NonCombatant)
                                        return stanceColors.Enemies;
     

```

Also, perhaps `IsAlliedWith` could check for `p == this` to avoid having to look up a stance on itself.

**Comment by pchote** [comment]
See #18677

**Comment by anvilvapre** [comment]
I see that `IsAlliedWith` checks against `this` there, great. However the `PlayerStanceColor` method didn't change.
