### ISSUE TITLE
ThreadedGraphicsContext synchronous?

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#18800]
Some questions, thoughts,

Wouldn't it be just simpler to only support a `Func<object, object>` and have a `bool isAction` and ignore the result if it was an action. Avoids the three `if` statements for function with parameters. Passing a null argument for a functions/actions that has no parameters.

https://github.com/OpenRA/OpenRA/blob/13596c14746da96cc2cfcf11703345db292cc734/OpenRA.Platforms.Default/ThreadedGraphicsContext.cs#L203-L226

Also it seems access to `messageException` in line 280 is without lock. Perhaps you should set it only if not already set in `Execute`. In theory you could read an invalid/half object pointer because multiple messages resulting in two instances of an exception. Or a better solution would be to check the `messageException` while having the lock on messages.

Also `messageException` is never cleared - which would mean the game would have to exit or the exception would keep being thrown. I.e. all messages queued after will result in the same exception. This seems reasonable.

In `QueueMessage` line 186 `if (messages.Count == 1)` shouldn't this be `if (messages.Count > 1)`. Does it need to be a list then?

In general. Doesn't it currently mean that only one message can be queued and executed async - that `messages` will never be larger than size one? That when `messages` is size one it can only be the consumer having the lock - blocking `QueueMessage` from adding more messages. Doesn't it make execution synchronous - with multiple threads - still? And even though the consumer will pick up the action as soon as it can - holding the lock shortly - it will only pick up the next once the current is done executing.

**Comment by RoosterDragon** [comment]
Having support for some extra signatures helps when we're fitting the existing methods into the available signatures.

Supporting action and func with no params allows us to map signatures like `dispose = texture.Dispose;` and `getScaleFilter = () => texture.ScaleFilter;` without large amounts of ceremony.

Losing that ability forces you into the more contorted reshaping some functions have to go through, e.g. `setData1 = colors => { texture.SetData((uint[,])colors); return null; };` to return a null it will ignore anyway, or in general when parameters get involved and need to be shoved into a tuple and unwrapped again: `setEmpty = tuple => { var t = (ValueTuple<int, int>)tuple; texture.SetEmpty(t.Item1, t.Item2); };`

Given an if-else chain with 4 options costs nothing performance wise, this is a nice readability improvement.

----

`messageException` is marked as `volatile`. This ensures the required atomic reads/writes. (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/volatile)

You're correct that it is never cleared. Its purpose is to ensure any exception generated on the rendering thread is eventually rethrown on the game thread. We can't recover from it, but throwing the exception gives us a better chance at debugging it than if the rendering thread ignored it, we lose the stack trace and the game "stops working" but doesn't actually crash.

----

Multiple messages can be queued. You can call `QueueMessage` multiple times to do so. I'll put the code that process messages (in the rendering thread) and the code that queues messages from the calling thread at the bottom for reference.

When you have 0 messages, and queue the first one, we use the `if (messages.Count == 1) Monitor.Pulse(messages);` to tell the render thread to wake up. This will unblock it from the `Monitor.Wait(messages);` if it was blocked there and it will start processing the whole queue.

This process in not blocking - QueueMessage doesn't then wait for the render thread to catch up. The `Pulse` signals the render thread that it now has work to do, but `QueueMessage` has no synchronization that waits for that work to complete.

So why `if (messages.Count == 1)` and not `if (messages.Count > 1)`? If we have one message in the queue, we've already pulsed the render thread to wake it up and get to process all queued messages. It doesn't go back to sleep until the queue it empty (`if (messages.Count == 0) Monitor.Wait(messages);`). If we queue a 2nd message, pulsing again does nothing. The render thread isn't waiting to be woken up - it's already been woken up to process the earlier messages.

We only need to pulse to tell the render thread to say "there used to be no messages, but now there are some". Pulsing to say "there were already some messages, we've added another" is not required.

```c#
// QueueMessage
lock (messages)
{
	messages.Enqueue(message);
	if (messages.Count == 1)
		Monitor.Pulse(messages);
}

// Message loop in RenderThread
Message message;
while (true)
{
	lock (messages)
	{
		if (messages.Count == 0)
		{
			if (messageException != null)
				break;

			Monitor.Wait(messages);
		}

		message = messages.Dequeue();
	}

	if (message == null)
		break;

	message.Execute();
}
```

**Comment by anvilvapre** [comment]
Thanks for explaining in detail.

When I read your explanation and the the documentation of `Pulse` and `Wait` i now understand how it would have to work.

So only during - when - the consumer is executing a message - outside the lock - there is time for the producer to add more messages.

Curious about what level of parallelism it brings - how many messages can be queued and forgotten about by the producer - and i.e. in how many cases messages are function calls where a the consumer waits for a results.

But i assume the real advantage is for the producer to have time already to work on generating the/a next message.

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/pull/15177 has some benchmarks from when the feature was first added. Note, however, that this is not enabled under Windows which has something seriously wrong with its (Windows/SDL/???) message queue (enabling off-the-main-thread GL rendering breaks minimizing/restoring the game window).

**Comment by anvilvapre** [comment]
Thanks. Feel free to close this issue.

Different question related to rendering. Profiling shows a lot of time in spent in Array.Copy. 

Couldn't `SpriteRenderer` make use of an `IVertexBuffer` buffer over a `Vertex[]` array as temp buffer? Avoid the copy step in DrawBatch? Or is the last expected to potentially be graphics memory - would it matter? It only is GL binded with when used inside a framebuffer. DrawBatch could swap the bufffer and return an empty one for the renderer to use next.
