### ISSUE TITLE
Server.Connection lastReceivedTime

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#18803]
`lastReceivedTime` is updated even when `Poll` returns `no data` - which is always when there is no data received from the client.

`lastReceivedTime` is currently rather `lastReadTime`.

I assume it currently means that a connection will only be dropped once it times out on OS, TCP level. Could mean that the 60 second connection timeout is only reached 60 seconds after it actually times out. Although `server.DropClient()` is probably already called earlier when Poll does indicate data - and data of zero length is read.

Perhaps intended. Perhaps only update `lastReceivedTime` when data was received.

https://github.com/OpenRA/OpenRA/blob/8f9c212921c3e6bfc4a1cd08221f04b88d6d4f5e/OpenRA.Game/Server/Connection.cs#L57

**Comment by anvilvapre** [comment]
@Mailaender Why did you reopen? To be able to implement the 'polish'? If so, i can do it some time. I would do it by only updating the last received time if `poll` returns data.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/18810 didn't address it at all.

**Comment by anvilvapre** [comment]
Fixed already in last release. `lastReceivedTime` is only update if actual data was received.
