### ISSUE TITLE
TransformIntoAircraft, ResolveOrder, orderstring not checked

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#18813]
Possible bug?
All other `IResolveOrder` check the `order.OrderString` and only execute logic if they support the order.
In this method a check is done first, but after - at any order - the rest of the code is executed.
I assume it runs at each random order.

Don't see directly what this does? Transforms a building into an aircraft? Couldn't see it being used in game in RA.

https://github.com/OpenRA/OpenRA/blob/3aaaa95618b251ba771e3d6fb898d6253dc0c1a8/OpenRA.Mods.Common/Traits/Buildings/TransformsIntoAircraft.cs#L126

**Comment by abcdefg30** [comment]
> Possible bug?

Indeed a bug, see #18821.
