### ISSUE TITLE
Performance waste in "FuzzyStateMachine.ChangeState" used in all squad states

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#18818]
Although it won't cause any bug but when we set `rememberPrevious: true` it will cache the previous state which is only used in `RevertToPreviousState`, and current AI state machine don't have anywhere to use `RevertToPreviousState`.

I want to fix this after my AI fixes are merged. I have already pushed a thing [in RV-engine](https://github.com/MustaphaTR/OpenRA/pull/7/commits/446ab1ce1440394dfa5c12de529d37b7235093a0) which works smoothly.

**Comment by anvilvapre** [comment]
Interesting why they would call it a FuzzyStateMachine. I don't see fuzzy logic being applied.
Also curious why it would only maintaine the one previous state. Why it wouldn't be a stack model.

1. Note that `previousState` is only set if `rememberPrevious` is set to `true` when calling `ChangeState`. This seems to be the case in most cases/always.
2. Classes that implement IState do not seem to have many fields. Making their memory footprint limited. But this ofcourse can depend on the implementation/mod.
3. I can confirm `RevertToPreviousState` never seems to be called.

Option 1. Might be best to offer support to enable/disable it. If disabled calling `RevertToPrevious` state could raise an exception.

Option 2. Adjust all calls to `ChangeState` with no second argument. Set the default value for the second argument `rememberPrevious` to false.

Option 3. Is a fix needed?
