### ISSUE TITLE
Bot places buildings on bibs and exits blocking itself

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#18816]
![image](https://user-images.githubusercontent.com/756669/98450726-594ff280-213f-11eb-968c-3a0378df855d.png)

![image](https://user-images.githubusercontent.com/756669/98450737-72f13a00-213f-11eb-8905-ce0ee57e924b.png)

**Comment by pchote** [comment]
This is going to be a regression from #18689. The bib cells are probably not being considered in the ActorMap.

**Comment by ABrandau** [comment]
Yeah the footprints might be broken

![image](https://user-images.githubusercontent.com/11763228/98464738-92ba4980-21a3-11eb-8d5f-4493243779fb.png)

![1](https://user-images.githubusercontent.com/11763228/98464720-82a26a00-21a3-11eb-8730-dcd15da4a856.gif)
