### ISSUE TITLE
Problems with (Voxel) Barrels

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#18811]
I was messing around with the unused voxels of TD/RA units in RA2 files in RV, noticed some issues with the units with barrels.

First of all Turret facing in the editor is messed up for the units with barrels. They start as seen in the image below and they do not turn properly along with the base if you slide the base Facing slider.
![resim](https://user-images.githubusercontent.com/7933210/98284183-cd5c9000-1fb1-11eb-9736-0b06315fcb89.png)

Second issue doesn't appear to happen in the editor, but only ingame. The barrel is offset wrong, Mammoth and Artillery has `-256,0,0` and `-512,0,0` Turret Offset respectively but their barrel go down rather than go back. 
![resim](https://user-images.githubusercontent.com/7933210/98284374-14e31c00-1fb2-11eb-945c-c5bb3c911b6e.png)

I've so far only tested this in RV, but i doubt this being related to custom engine, i haven't touched the parts about those. Will check TS later, but wanted to post this first.

**Comment by MustaphaTR** [comment]
Yeah, i can reproduce the first issue in TS on bleed too.
![resim](https://user-images.githubusercontent.com/7933210/98286412-06e2ca80-1fb5-11eb-8042-e66aa19080e1.png)

**Comment by pchote** [comment]
This will be a regression from #18418.
