### ISSUE TITLE
#18774 did not fix the Z fighting.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#18812]
The commit has been in my RV-engine branch for a while now, but in RV i'm still getting Z-fighting with Yuri Statues and Tank Bunkers. In both cases the Z fighting happens between a sprite and a voxel, i feel like the issue maybe lying there.

**Comment by abcdefg30** [comment]
Can you find a reproduction case in the default mods?

**Comment by MustaphaTR** [comment]
I messed around with TS Laser Turret a bit, but couldn't reproduce any flickering there. It has its own issues but not the same thing that is happening in RV. Also when i removed DepthSprite/ZOffset stuff from Laser Turret, the turret's Z location against the base were varying, but no flickering were happening without turning it.
