### ISSUE TITLE
Is there any order can make actors follow a certain actor which is not "Guard"?

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#18819]
Is there any order can make actors follow a certain actor which is not "Guard"?

I am making a gruelling-run-state (hit and **run**) for AI, which is all units in squad retreat briefly after gruelling-hit-state. 

The direct way is to retreat to random own building, but the Pathfinder of OpenRA is not very good: even 10 units retreat to base from enemy base will cause spikelag, which rise high with my blood pressure in performance window and eat up FPS. Gruelling-run-state and gruelling-hit-state will switch frequently in combat, and spikelag will always be here. 

Use AttackMove (to squad leader) like ground-attackmove-state that I just fixed in #17997 is also not good with this usecase: gruelling squad need to follow the team leader continuously in gruelling-run-state, any hesitation means death, unlike ground-attackmove-state. 

Guard order (to squad leader) needs Guardable trait for leader otherwise it will crash the game, and I really need other units to follow the team leader to retreat briefly instead of return fire halfway.

so what I want is, a pure/easy to use follow order. Is there any in engine?

**Comment by abcdefg30** [comment]
https://github.com/OpenRA/OpenRA/blob/13581c030d1499dd4e7d83fd3f5898704aba500f/OpenRA.Mods.Common/Activities/Move/Follow.cs

**Comment by dnqbob** [comment]
Question 2.

Is there any order related to this `follow`? When I use follow in Squad states it is better to use `owner.Bot.QueueOrder(new Order(...));` instead of changing activity.

**Comment by abcdefg30** [comment]
No, afaik there is no order to do that.

**Comment by dnqbob** [comment]
Ahhh... just headache, I know this activity used in guard but there is nowhere else to use it.
