### ISSUE TITLE
Make walls block chronotank missiles and remove LockOn

### ISSUE THREAD

**Issue by deleted-user-1** [OpenRA/OpenRA#18822]
## Motivation

- A weapon system that teleports next to its target does not need guided missiles. 
- I don't like the look of guided chronotank missiles (no, I have no replays and no further reasoning).
- You can not defend super weapons with walls against chronoshifted chronotanks and them shooting through walls looks not good. You should have to use artillery or v2s which in turn are easier to kill.
- Enable turreted vehicles with opportunity fire to dodge missiles (won't happen to often but highlights their role to attack static targets

Please forward to discord balance channel and competitive players for decision.

## Proposed solution

- Remove LockOn
- Make walls block missiles

## Side effects

Annoying discussions in the discord balance channel :D

## Alternatives

I mostly care about them shooting above walls but don't see other alternatives than making walls block missiles.

**Comment by Orb370** [comment]
All missile weapons shoot over walls.

If this does go through, I think we'd need a new model to distinguish it so it's not confusing. Some kind of rocket model.

**Comment by deleted-user-1** [comment]
Alright thanks for reading!
