### ISSUE TITLE
InvalidDataException: nuyell1.aud is not a valid sound file!

### ISSUE THREAD

**Issue by NikeJoshua** [OpenRA/OpenRA#18828]
## System Information

- Operating System:  Windows (Microsoft Windows NT 6.2.9200.0)
- OpenRA Version: OpenRA engine version release-20200503
- OpenRA Mod: 
Tiberian Dawn mod version release-20200503
- Source: Official download with manually added .Mix files from original release game discs (automatic install didn't recognise the discs)
- For self-compiled or third-party packages: Mono version

## Exception log

```
OpenRA engine version release-20200503
Tiberian Dawn mod version release-20200503
on map 3615cd2f56bb1ad870d976787e2b15d321759ef2 (01:   Storm the Beachhead by Westwood Studios).
Date: 2020-11-14 15:16:00Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.InvalidDataException`: nuyell1.aud is not a valid sound file!
   at OpenRA.Sound.LoadSound[T](String filename, Func`2 loadFormat)
   at OpenRA.Exts.GetOrAdd[K,V](Dictionary`2 d, K k, Func`2 createFn)
   at OpenRA.Sound.PlayPredefined(SoundType soundType, Ruleset ruleset, Player p, Actor voicedActor, String type, String definition, String variant, Boolean relative, WPos pos, Single volumeModifier, Boolean attenuateVolume)
   at OpenRA.Mods.Common.Traits.Voiced.OpenRA.Traits.IVoiced.PlayVoiceLocal(Actor self, String phrase, String variant, Single volume)
   at OpenRA.VoiceExts.PlayVoiceLocal(Actor self, String phrase, Single volume)
   at OpenRA.Mods.Common.Traits.Sound.DeathSounds.OpenRA.Mods.Common.Traits.INotifyKilled.Killed(Actor self, AttackInfo e)
   at OpenRA.Mods.Common.Traits.Health.InflictDamage(Actor self, Actor attacker, Damage damage, Boolean ignoreModifiers)
   at OpenRA.Mods.Common.Warheads.DamageWarhead.InflictDamage(Actor victim, Actor firedBy, HitShapeInfo hitshapeInfo, IEnumerable`1 damageModifiers)
   at OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, IEnumerable`1 damageModifiers)
   at OpenRA.Mods.Common.Warheads.DamageWarhead.DoImpact(Target target, WarheadArgs args)
   at OpenRA.GameRules.WeaponInfo.Impact(Target target, WarheadArgs args)
   at OpenRA.Mods.Common.Projectiles.Missile.Explode(World world)
   at OpenRA.Mods.Common.Projectiles.Missile.Tick(World world)
   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.WindowsLauncher.RunGame(String[] args)

```

## Additional information

The game crashes early GDI mission 1, i assume by the gunboat killing one of the enemies near the shoreline as the sound file in question is a death scream.
The sound files were copied from an original release English European release CD (as mentioned above, installer didn't recognise the game discs). When opened in XCC Mixer 1.47, the sound file (sounds.mix->nuyell1.aud) played fine.
I'm not sure this is the cause, but a google search found that some of the original release .AUD files (including nuyell1.aud) used a different compression scheme (SND1). More info and code for a potential fix can be found here:
https://lists.ffmpeg.org/pipermail/ffmpeg-cvslog/2012-January/046281.html

**Comment by pchote** [comment]
Can you please attach a copy of your nuyell1.aud that causes the crash here?

**Comment by NikeJoshua** [comment]
[nuyell1.zip](https://github.com/OpenRA/OpenRA/files/5541003/nuyell1.zip)

**Comment by abcdefg30** [comment]
This is the same issue I ran into at https://github.com/OpenRA/OpenRA/pull/18254#issuecomment-644947899.

**Comment by Mailaender** [comment]
The file has a sound flag of 0:

![image](https://user-images.githubusercontent.com/756669/101283709-71696f00-37dc-11eb-90aa-e211e1d569bb.png)

while we expect 1 or 2:

https://github.com/OpenRA/OpenRA/blob/8d1f72c104210339265f3b8fec9477a68ec55197/OpenRA.Mods.Cnc/FileFormats/AudReader.cs#L20-L25

**Comment by Mailaender** [comment]
We don't ship the file during asset download:

```
mono --debug OpenRA.Utility.exe ra --extract nuyell1.aud
System.IO.FileNotFoundException: File not found: nuyell1.aud
```

**Comment by abcdefg30** [comment]
`nuyell1.aud` is from TD, so I would expect the command to work when using `cnc` instead.

**Comment by Mailaender** [comment]
Data size, compression type and sound flag differ from the file I extracted from the downloaded asset pack:

![image](https://user-images.githubusercontent.com/756669/101375680-fbced300-38af-11eb-8d80-718263ae76f1.png)

**Comment by Mailaender** [comment]
~~According to https://github.com/electronicarts/CnC_Remastered_Collection/blob/7d496e8a633a8bbf8a14b65f490b4d21fa32ca03/TIBERIANDAWN/WIN32LIB/SOUNDINT.H#L53 the soundflag `0` is valid and means no compression.~~

**Comment by Mailaender** [comment]
Correction: the sound format is regular Westwood compression, but the sound flag is `0` which is again invalid according to https://github.com/electronicarts/CnC_Remastered_Collection/blob/7d496e8a633a8bbf8a14b65f490b4d21fa32ca03/TIBERIANDAWN/WIN32LIB/AUDIO.H#L51-L53 so the original game should crash as well with this file or simply not play it. When I hack around the invalid data exceptions I hear a distorted scream with some noise. My best guess is file corruption? Or is this from a censored version where someone removed death screams by invalidating the sound file?

**Comment by reaperrr** [comment]
For the record, XCC Mixer plays the file just fine (no distortion), and shows it as being 8 bit (which would explain why neither flag is set, it's neither stereo nor 16bit, afterall).

**Comment by Mailaender** [comment]
Interesting. Making the sample bits configurable sadly doesn't change things. It is still noise.

```diff
diff --git a/OpenRA.Mods.Cnc/AudioLoaders/AudLoader.cs b/OpenRA.Mods.Cnc/AudioLoaders/AudLoader.cs
index 0cadd71142..6f18b6f344 100644
--- a/OpenRA.Mods.Cnc/AudioLoaders/AudLoader.cs
+++ b/OpenRA.Mods.Cnc/AudioLoaders/AudLoader.cs
@@ -54,7 +54,7 @@ bool ISoundLoader.TryParseSound(Stream stream, out ISoundFormat sound)
 	public sealed class AudFormat : ISoundFormat
 	{
 		public int Channels { get { return 1; } }
-		public int SampleBits { get { return 16; } }
+		public int SampleBits { get { return sampleBits; } }
 		public int SampleRate { get { return sampleRate; } }
 		public float LengthInSeconds { get { return AudReader.SoundLength(sourceStream); } }
 		public Stream GetPCMInputStream() { return audStreamFactory(); }
@@ -62,13 +62,14 @@ public sealed class AudFormat : ISoundFormat
 
 		readonly Stream sourceStream;
 		readonly Func<Stream> audStreamFactory;
+		readonly int sampleBits;
 		readonly int sampleRate;
 
 		public AudFormat(Stream stream)
 		{
 			sourceStream = stream;
 
-			if (!AudReader.LoadSound(stream, out audStreamFactory, out sampleRate))
+			if (!AudReader.LoadSound(stream, out audStreamFactory, out sampleBits, out sampleRate))
 				throw new InvalidDataException();
 		}
 	}
diff --git a/OpenRA.Mods.Cnc/FileFormats/AudReader.cs b/OpenRA.Mods.Cnc/FileFormats/AudReader.cs
index f6fcc3c4b8..2eeec83066 100644
--- a/OpenRA.Mods.Cnc/FileFormats/AudReader.cs
+++ b/OpenRA.Mods.Cnc/FileFormats/AudReader.cs
@@ -20,6 +20,7 @@ namespace OpenRA.Mods.Cnc.FileFormats
 	[Flags]
 	enum SoundFlags
 	{
+		_8Bit = 0x0,
 		Stereo = 0x1,
 		_16Bit = 0x2,
 	}
@@ -54,7 +55,7 @@ public static float SoundLength(Stream s)
 			return (float)samples / sampleRate;
 		}
 
-		public static bool LoadSound(Stream s, out Func<Stream> result, out int sampleRate)
+		public static bool LoadSound(Stream s, out Func<Stream> result, out int sampleBits, out int sampleRate)
 		{
 			result = null;
 			var startPosition = s.Position;
@@ -64,10 +65,15 @@ public static bool LoadSound(Stream s, out Func<Stream> result, out int sampleRa
 				var dataSize = s.ReadInt32();
 				var outputSize = s.ReadInt32();
 
+				sampleBits = 0;
+
 				var readFlag = s.ReadByte();
 				if (!Enum.IsDefined(typeof(SoundFlags), readFlag))
 					return false;
 
+				sampleBits = readFlag == (int)SoundFlags._8Bit ? 8 : 16;
+				System.Console.WriteLine(sampleBits);
+
 				var readFormat = s.ReadByte();
 				if (!Enum.IsDefined(typeof(SoundFormat), readFormat))
 					return false;
```

**Comment by reaperrr** [comment]
Well, going by file size the file isn't using the IMA compression that regular 16bit AUD files use, so I assume it would need a different decoder.

**Comment by Mailaender** [comment]
Reading

https://github.com/OpenRA/OpenRA/blob/8d1f72c104210339265f3b8fec9477a68ec55197/OpenRA.Mods.Common/FileFormats/WavReader.cs#L92-L93

I think you are half right. The code needs to be adapted further. Some findings:

https://github.com/TheAssemblyArmada/Chronoshift/blob/develop/src/game/audio/adpcm.cpp#L160
https://github.com/TheAssemblyArmada/Chronoshift/blob/develop/src/game/audio/audio.cpp#L256

Is this a file from Sole Survivor?

**Comment by Mailaender** [comment]
Actually, this is https://wiki.multimedia.cx/index.php/Westwood_ADPCM_Audio which is always 8 bit and used for death screams. Tried my luck with the example code provided https://github.com/Mailaender/OpenRA/tree/aud-8 but I didn't get too far. The noise is now inaudibly silent.

**Comment by Mailaender** [comment]
https://samples.mplayerhq.hu/game-formats/westwood-aud/westwood-adpcm.txt and I can confirm MPlayer can play it.

**Comment by ShikiSuen** [comment]
Are you getting the file from CNC-TD Remastered?

CNC-TD Remastered ships the original installers of Tiberian Dawn and Red Alert.
I am afraid that some of those files are not utilizable by OpenRA at this moment.

Here comes my case: https://github.com/OpenRA/OpenRA/issues/19214

P.S.: The installer ISO files retrieved from CNCNZ works well with OpenRA.

**Comment by reaperrr** [comment]
EA lost the source code of the old games at some point, so the one they retrieved might have been an earlier revision and missing some later updates to the sound files.
