### ISSUE TITLE
Structures can be placed on refinery pads

### ISSUE THREAD

**Issue by tux314159** [OpenRA/OpenRA#18840]
## Issue Summary

DESCRIPTION
In the latest dev build (on 19 Nov) is now possible to place structures on refinery pads, also blocking the harvesters.
![refpad-block](https://user-images.githubusercontent.com/56342471/99642677-b96f5e80-2a86-11eb-82e8-d87c5bffdaa3.png)
![refpad-block-2](https://user-images.githubusercontent.com/56342471/99642682-bb392200-2a86-11eb-9553-f863f5c71a4f.png)

This was not possible in the latest release.

A git bisect revealed that daa8c74c375d88999fa4671cecb45fe4222d2548 is the breaking commit; it makes buildings placeable
in shadows, but also makes them placeable on refinery pads.

## Reproduction

STEPS TO REPRODUCE THE ISSUE
1. Build a refinery
2. Build something else and place it on the refinery pad
3. The harvester is blocked as well

## Expected behavior

EXPECTED BEHAVIOR
It should not be placeable

## Screenshots / Screen recordings / Replays

![refpad-block](https://user-images.githubusercontent.com/56342471/99642677-b96f5e80-2a86-11eb-82e8-d87c5bffdaa3.png)
![refpad-block-2](https://user-images.githubusercontent.com/56342471/99642682-bb392200-2a86-11eb-9553-f863f5c71a4f.png)

**Comment by abcdefg30** [comment]
Thanks for the report! We currently have #18824 in the queue which will fix this.

**Comment by tux314159** [comment]
Fixed now hahaha
