### ISSUE TITLE
What are ALL the balancing changes from the original Red Alert? 

### ISSUE THREAD

**Issue by Leo512bit** [OpenRA/OpenRA#18842]
## Motivation

I'm experimenting with advanced mapping and I want to make a hybrid rules set for one of my maps that has a mix of the original Red Alert rules and the openra rules

**Comment by dragunoff** [comment]
It would be difficult to compile such a list as the RA mod is quite different from the vanilla Red Alert game. However you can have a look at https://github.com/OpenRA/raclassic - it is a mod for OpenRA that strives to recreate the classic RA gameplay and balance.

**Comment by abcdefg30** [comment]
Looking at raclassic is indeed the best idea here.
