### ISSUE TITLE
Add medic/mechanic range to pillboxes?

### ISSUE THREAD

**Issue by tux314159** [OpenRA/OpenRA#18845]
## Motivation

Pillboxes currently only work for infantry that fire ammunition of some sort... it would be nice if they could house medics/mechanics who can heal/fix from within.

## Proposed solution

Let Medics and Mechanics heal from pillboxes

## Side effects

Defending might be easier, adding on to defender's advantage

**Comment by abcdefg30** [comment]
This idea was sadly already rejected in #18570.
