### ISSUE TITLE
Bibs no longer count towards building adjacency

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#18852]
bleed:
![grafik](https://user-images.githubusercontent.com/7704140/100159258-b375e500-2ead-11eb-977c-66eccb57c5c1.png)
release-20200503
![grafik](https://user-images.githubusercontent.com/7704140/100159168-8fb29f00-2ead-11eb-8e6e-60e99f5e1d72.png)

Possibly another regression from #18689.

**Comment by pchote** [comment]
I would be tempted to call this a feature/bugfix if it weren't for the balance implications 😞
