### ISSUE TITLE
[devtest-20201128] Attack move non honored after first killed

### ISSUE THREAD

**Issue by ubitux** [OpenRA/OpenRA#18867]
![devtest-20201128](https://user-images.githubusercontent.com/34467/100519168-828bfd80-3196-11eb-9859-227530495c0c.gif)

Happens around 13:30 - 14:00 in the following replay: [buggy-atk-north-m13-m14.orarep.gz](https://github.com/OpenRA/OpenRA/files/5610800/buggy-atk-north-m13-m14.orarep.gz)

Wasn't able to reproduce with a simple harv attack scenario. It might have to do with the enemy tesla vision, but it's just a wild guess.

**Comment by OpenOP2Admin** [comment]
this happens all the time in the current release when you are a-moving. players take advantage of it with flanks (make the flank army run away into the untargetable shroud). you can a-move an army in response, but if one opposing infantry or tank is killed, then the a-move stops. havent tried on devtest.

**Comment by pchote** [comment]
As with #18871 the infantry are sitting in the Turn activity which prevents them from being able to shoot.

<img width="609" alt="Screenshot 2020-11-29 at 10 39 53" src="https://user-images.githubusercontent.com/167819/100539575-65573d80-322f-11eb-9653-4f9d810a9438.png">
