### ISSUE TITLE
Boats near the Shore Line Be Able to Pass

### ISSUE THREAD

**Issue by Quetip** [OpenRA/OpenRA#18864]
![image](https://user-images.githubusercontent.com/14940856/100492529-fd073f80-30fa-11eb-9094-8a2021f37618.png)

## Motivation

The motivation behind this request is to not waste money producing ships that can't be used. Currently, if you build a sub pen or naval yard too close to shore (that is L shaped in one form or another) and produce a unit it will get stuck unless the structure is sold or destroyed.
REQUEST MOTIVATION

## Proposed solution

Recommend we make the boats passable through a edge/section of the sub pin/naval yard footprint.
PROPOSED SOLUTION

## Side effects

The only side effects I can think of is the sprite of boats crossing over a naval structure not rendering properly.
EXPECTED SIDE EFFECTS

## Alternatives

Not making naval production structures buildable near a section of shore where units could potentially get stuck.
ALTERNATIVES

**Comment by pchote** [comment]
In the next release you will be able to place a rallypoint in the open area of water, and boats will prefer to use the exits facing that instead of spawning randomly next to the shore.

**Comment by Quetip** [comment]
Good to hear.
