### ISSUE TITLE
[devtest-20201128] Attack order doesn't work if the target is on the edge of vision range

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#18871]
Rifle soldiers are issued an attack-move order, engineers are on a simple move command. Rifles don't attack the enemy and just rotate into it until it comes 1 cell closer than vision range limit.
![openra_vision_attack_bug](https://user-images.githubusercontent.com/1614714/100537793-883c1e80-323c-11eb-9c37-cdd58e710e9b.gif)

Replay file:
[ra-2020-11-29T090205Z.zip](https://github.com/OpenRA/OpenRA/files/5611911/ra-2020-11-29T090205Z.zip)

**Comment by pchote** [comment]
Confirmed that the infantry stay in the Turn activity. Possibly a regression in the FacingTolerance?

<img width="391" alt="Screenshot 2020-11-29 at 10 33 23" src="https://user-images.githubusercontent.com/167819/100539457-7d7a8d00-322e-11eb-93c1-8c580db04768.png">

**Comment by abcdefg30** [comment]
> Possibly a regression in the FacingTolerance?

Fwiw, #18856 doesn't change anything here.

**Comment by Orb370** [comment]
[Comparing Release and Devtest.zip](https://github.com/OpenRA/OpenRA/files/5618766/Comparing.Release.and.Devtest.zip)

Definitely a regression.

**Comment by Orb370** [comment]
After a lot of testing, I've narrowed down the issue to a PR from June 19th. 

https://github.com/OpenRA/OpenRA/pulls?q=is%3Apr+closed%3A2020-06-19..2020-06-19

Bug is present in #18294, but absent in #18302

**Comment by pchote** [comment]
Related to #16486, which the change from int to WAngle faces has made worse.
