### ISSUE TITLE
libretro port?

### ISSUE THREAD

**Issue by DartPower** [OpenRA/OpenRA#18876]
Hi there, i have a idea, you want to port to libretro?
This is will be cool, really :)

Check this also please :)
https://www.libretro.com/index.php/mission/
https://docs.libretro.com/development/cores/developing-cores/
https://www.libretro.com/index.php/powered-by-libretro/
https://docs.libretro.com/development/cores/opengl-cores/

**Comment by abcdefg30** [comment]
Considering the amount of work required to make this work and OpenRA already running on modern distros I don't think the core team has the time to work on this, sorry.
