### ISSUE TITLE
Bleed: Discord invites don't allow you to join as a spectator

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#18887]
Once all the player slots are filled you can't use it anymore. Says it's "full".

![Discord](https://user-images.githubusercontent.com/42915475/101066133-01e94a80-3564-11eb-82e8-a448859ad634.png)

**Comment by deleted-user-1** [comment]
Is it an oversight or was this intentionally not tagged for next (asking because it's related to the RP feature for Next)? @teinarss do you plan adding joining for specs/know if this is doable?

**Comment by pchote** [comment]
Discord have blocked any new projects from using its dedicated spectator button.

I don't think there's any reason why we can't just say that there are N + 1 player slots if the server has spectators enabled, though.
