### ISSUE TITLE
Lua API Spawnpoints

### ISSUE THREAD

**Issue by patrickwieth** [OpenRA/OpenRA#18889]
REQUEST MOTIVATION
It is nice that you can get a spawnpoint ID via Lua API, but this id does not really help you. It would be better if you could get reference to the spawnpoint actor, to do things like read out the spawnpoint of a player. (otherwise you have to wait some ticks into the game to get the mcv and read out the mcv position)

PROPOSED SOLUTION
Return Spawnpoint Actor with a function

EXPECTED SIDE EFFECTS
More functionality for mappers, might cause more requests

**Comment by pchote** [comment]
I will add a `CPos HomeLocation` property that exposes the new abstraction introduced in #18672 to Lua.
