### ISSUE TITLE
Captured buildings do not become cloaked by nearby Stealth Generators

### ISSUE THREAD

**Issue by Samsterious** [OpenRA/OpenRA#18891]
## Issue Summary

An Engineer entering a building to capture it changes its owner but does not cause the building to update its cloaked state if the new owner has a Stealth Generator nearby. Adding a new Stealth Generator or toggling one of the existing ones off and on correctly updates the cloaked state.

This was noticed in the Tiberian Sun mod.

## Reproduction

• Place a powered Stealth Generator nearby a capturable building, such as a Hospital or Armory.
• Capture the building with an Engineer

The newly-captured building will not be cloaked.

• Toggle the Stealth Generator off and back on

The newly-captured building will now be cloaked.

## Expected behavior

A captured building should update its cloaked state when changing owners.

## Screenshots / Screen recordings / Replays

![capture](https://user-images.githubusercontent.com/20689511/101225220-be670d00-3645-11eb-8384-68e5a5bddf42.gif)

**Comment by ghost** [comment]
Looking into this
