### ISSUE TITLE
TD, Bleed: Taking damage prevents Sam Site from Turning

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#18901]
[Sam Site Turning Bug.zip](https://github.com/OpenRA/OpenRA/files/5649518/Sam.Site.Turning.Bug.zip)

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/blob/b1560ae69ceece55d9c5b40d5a1ed71d4c408c86/OpenRA.Mods.Cnc/Traits/Render/WithEmbeddedTurretSpriteBody.cs#L67-L71

is setting `QuantizedFacings` to 1 (the number of facings of the closed sequence) when it takes damage while closed.
