### ISSUE TITLE
Don't ask for sending system details every time again

### ISSUE THREAD

**Issue by deleted-user-1** [OpenRA/OpenRA#18907]
## Motivation

When using the AppImages, it does remember the setting for the Opt-In dialog for sending system details but will show the dialog on every startup. It should be enough to show the dialog once for every install.

## Proposed solution

Show the dialog once and then use the saved setting without asking again.

**Comment by pchote** [comment]
This has never happened for me.

**Comment by deleted-user-1** [comment]
Maybe it's limited to AppImages - I reproduced it before submitting the issue. When confirmed and I quit and start the game again, the checkmark is set but the dialog is shown. And when I don't check the checkbox, the dialog is shown without checkmark. So it saves the setting but keeps showing the dialog screen on startup.

**Comment by pchote** [comment]
This has never happened to me when running the AppImages!

**Comment by matjaeck** [comment]
I found out what caused it: In my settings.yaml was a duplicate entry:

```
Debug:
	SystemInformationVersionPrompt: 4
	UUID: b56328f0-2f81-4d71-858a-580aa7e56283
	DisplayDeveloperSettings: True

...

Debug:
	SystemInformationVersionPrompt: 3
	UUID: b56328f0-2f81-4d71-858a-580aa7e56283
```
Not sure how it got there, I can't remember that i entered this manually but maybe I copied my older settings once before I cleaned up my .openra folder, then paste it and then the game wrote the new entry into it when starting the game the first time?

Anyway, that's the reproduction-case for https://imgur.com/a/NljYDiA.

So I don't need this issue anymore... is there anything else what's interesting here?

**Comment by matjaeck** [comment]
I found out what caused it: In my settings.yaml was a duplicate entry:

```
Debug:
	SystemInformationVersionPrompt: 4
	UUID: ...
	DisplayDeveloperSettings: True

...

Debug:
	SystemInformationVersionPrompt: 3
	UUID: ...
```
Not sure how it got there, I can't remember that i entered this manually but maybe I copied my older settings once before I cleaned up my .openra folder, then paste it and then the game wrote the new entry into it when starting the game the first time?

Anyway, that's the reproduction-case for https://imgur.com/a/NljYDiA.

So I don't need this issue anymore... is there anything else what's interesting here?

**Comment by deleted-user-1** [comment]
I found out what caused it: In my settings.yaml was a duplicate entry:

```
Debug:
	SystemInformationVersionPrompt: 4
	UUID: ...
	DisplayDeveloperSettings: True

...

Debug:
	SystemInformationVersionPrompt: 3
	UUID: ...
```
Not sure how it got there, I can't remember that i entered this manually but maybe I copied my older settings once before I cleaned up my .openra folder, then paste it and then the game wrote the new entry into it when starting the game the first time?

So I don't need this issue anymore... is there anything else what's interesting here?

Edit: Sorry for the e-mail spam - I had to remove some information from the reply that I didn't want to be public...
