### ISSUE TITLE
Medics play heal animation while moving

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#18908]
https://clips.twitch.tv/StrongMistyMooseJebaited

Probably a regression from #18893.

**Comment by abcdefg30** [comment]
I think the bigger/general problem is that we allow units to move while they're still attacking. This is very visible with the grenadier. (Even on the last release you can move it before the throw, causing the grenade to appear out of nowhere.)

**Comment by pchote** [comment]
Do we want to disable unit movement at the start of the attack, like we do for dogs?

**Comment by abcdefg30** [comment]
Yes, I think pausing the Mobile trait would be the best option. (Which afaik should make units move after completing the attack.)

**Comment by Smittytron** [comment]
`Do we want to disable unit movement at the start of the attack, like we do for dogs?`

Players need to be able to abort an attack or this will feel clunky.

**Comment by pchote** [comment]
How about this: 0536a74a39dad38145fe579cbbd50f8e40c22a78?

Reverting #18893 fixes the issue here, and the FrameEndTask implements a different solution for #17743.

This would stop us from losing the holiday game period to arguments over infantry not being able to move after firing.
