### ISSUE TITLE
Poor performance after harvesters use up available ore/gems

### ISSUE THREAD

**Issue by beercanchicken** [OpenRA/OpenRA#18910]
DESCRIPTION
In certain situations an AI can create a higher demand for ore than what the map produces.  This is apparent when using a map that has isolated base areas.  When the AI has multiple harvesters and runs the available ore down to the immediately generated supply (and the AI cannot reach more ore/gems), momentary but impactful performance lag spikes occur.

STEPS TO REPRODUCE THE ISSUE
Use this map (Big A Lake) for a demonstration:
[https://resource.openra.net/maps/36796/](https://resource.openra.net/maps/36796/)

- Begin a skirmish game on this map with multiple AIs
- Play until one of the AI players runs its gem supply down to the mines
- The game should begin to show spikes in performance lag
- Destroy the ore trucks and the lag goes away; allow more ore trucks to chase a desperate supply of ore and the problem gets worse

EXPECTED BEHAVIOR
AI ore harvesters act normally, however there is a performance impact when many units are chasing a sparse ore supply.

edit: tested on pchote's 20201207-devtest build

**Comment by dnqbob** [comment]
I guess it is the harvester bot module, and I got a similar bug in CA long time ago.
https://github.com/Inq8/CAmod/issues/23

Although they used their own harvester bot module but it also happened in normal harvester bot module.

**Comment by Mailaender** [comment]
Yes, it is doing a costly pathfinder check every 50 ticks by default. See also https://github.com/OpenRA/OpenRA/issues/9367.

**Comment by beercanchicken** [comment]
![Screenshot_20201209_171648](https://user-images.githubusercontent.com/75708164/101704533-e3f87a00-3a7c-11eb-9ad3-9339c8f2ca04.png)

The lag spikes seem to coincide with these clusters of Invalid resource search locations.

**Comment by deleted-user-1** [comment]
> This is apparent when using a map that has isolated base areas. 

Sounds to me like https://github.com/OpenRA/OpenRA/issues/12435, potentially happening when the harvesters try path to ore on the other isolated part of the map and then it stops when ore on the accessible part has regrown. 

Potentially unrelated to harvester code.

**Comment by Mailaender** [comment]
The harvester has a domain index check so it won't waste too much effort on impossible paths.

**Comment by anvilvapre** [comment]
I believe it does 2 path findings. First one to find ore/gems around it, then once found it will do another path find to plan a path to it.

**Comment by Mailaender** [comment]
As it says
> Ordering to invalid

I guess in that case it is only doing one

https://github.com/OpenRA/OpenRA/blob/6810469634d43a7a3e8ab2664942e162c3f4436a/OpenRA.Mods.Common/Traits/BotModules/HarvesterBotModule.cs#L147-L157
which seems to be very costly despite the domain index check.

Maybe we should do a check if the resource layer in that specific domain index is empty and then stop searches.

**Comment by anvilvapre** [comment]
#19532 optimizes this very slightly.

**Comment by reaperrr** [comment]
What I learned is that the enemy avoidance check in the harvester bot module increases the cost by a factor of roughly about 5(!).

With a performance implication that massive, I'm not convinced the enemy avoidance logic is worth it, and I don't see an easy way to significantly reduce its cost (reducing the scan radius will also reduce its effectiveness).

**Comment by pchote** [comment]
That code calls `world.FindActorsInCircle` for every cell in the pathfind - oof!

This and several other AI related features could be improved/optimized by having a player-level "enemy danger heat map" which uses something like the support power targeting logic to calculate the danger in coarse bins across the map so that harvesters / engineers / MCVs can avoid them, or squads can attack them.
