### ISSUE TITLE
META: Fix repo website link not using https-protocol

### ISSUE THREAD

**Issue by deleted-user-1** [OpenRA/OpenRA#18928]
It just looks bad since all modern browsers warn users that the website they are sent to (http://www.openra.net/) is not using a secure connection. Just link to https://openra.net/ in the repo description or add a TLS-certificate for the www-Domain instead. It doesn't really make any difference for the users because it's a static site, but IMO it looks unprofessional and it's an easy fix.

**Comment by pchote** [comment]
Fixed to https://www.openra.net instead.

**Comment by deleted-user-1** [comment]
I remember the RC-map download or something else could not use https - if that's fixed you could also consider to enforce https in your hosting backend to redirect to https when using a http link.
