### ISSUE TITLE
Investigate attack-move regression w/ Sardaukars

### ISSUE THREAD

**Issue by deleted-user-1** [OpenRA/OpenRA#18935]
> In Dune 2000, I found that Sardaukars do "Attack Move" in strange way. When enemy unit is situated forward, then Sardaukars can stay. 

https://forum.openra.net/viewtopic.php?f=82&t=21333&p=312565#p312565

Reported by: Adrian

Potentially a regression from #18549.

**Comment by abcdefg30** [comment]
Apparently Sardaukars have two weapons with differing ranges active at all times. Unfortunately the weapon with larger range is used for range calculations by `AutoTarget` while `Attack` then tries to use the first weapon with the smaller range and can't shoot.

**Comment by pchote** [comment]
Can we just explicitly set `ScanRadius: <smaller weapon range>` on its `AutoTarget` definition?

**Comment by abcdefg30** [comment]
Yes, but imo having two weapons where only one appears to be ever used is still bogus. We can use the override as workaround unless @penev92 can confirm what the original did in time for the next playtest.

**Comment by VonNah** [comment]
Also Sardaukars currently use the wrong _sound file_ when firing at armored targets like tanks or **buildings**! `MGUN2.WAV` (= anti-infantry firing sound) should be replaced with `20MMGUN1.WAV` (= anti-tank/building firing sound).

I checked their original capabilities and compared them with OpenRA:

- a Sardaukar needs to fire 19 times to destroy an Atreides Combat Tank both in OpenRA and vanilla Dune 2000

- a Sardaukar needs to fire 29 times to destroy an Atreides Barracks both in OpenRA and vanilla Dune 2000

- a Sardaukar needs to fire 8 times to kill a Light Infantry unit in OpenRA, but just **6** times to kill one in vanilla Dune 2000.

Now I think we should only increase their damage against infantry accordingly. Their anti-tank/building damage is on par with the original game and they need their secondary firing mode sound fixed as mentioned above.

**Comment by pchote** [comment]
I guess that explains why they have two weapons then: one is anti-infantry, the other anti vehicle/building?

**Comment by VonNah** [comment]
Correct.

**Comment by pchote** [comment]
Proposed fix:

* Update the `M_LMG` and `M_HMG` target types based on the description above, so one weapon (I assume `M_HMG`?) is only valid versus buildings/vehicles, and the other only valid versus infantry.
* Add a new `Range` field to AutoTargetPriorityInfo (defaults to -1, target is rejected if Range >= 0 and Range < distance).
* Set custom AutoTargetPriorities for Sardaukar so that AutoTarget can use the ScanRadius from the longer ranged weapon but ignores targets that are outside the range but otherwise valid for the shorter weapon.

**Comment by VonNah** [comment]
Both `M_LMG` (anti-infantry) and `M_HMG` (buildings/vehicles) have the range of 3 cells. 

![sardranges](https://user-images.githubusercontent.com/65423234/104121844-56d56900-5339-11eb-9477-3717deddc485.PNG)

They automatically scan for valid targets within range (3 cells) and fire on them.

**Comment by MustaphaTR** [comment]
On OpenRA, M_LMG's Range is 2c512 and M_HMG's Range is 3c512. If you mean that they are both 3 in original, changing them to match would of course fix the issue for them but i would still rather a fix for a case like this where range difference is intended.

I don't have TibEd installed rn, so can't check the original values myself.

**Comment by VonNah** [comment]
TibEd:
![TibED_Sardaukar](https://user-images.githubusercontent.com/65423234/104219953-b1a0ba80-5436-11eb-9443-92c3e1f211bd.png)

Sight = Range = **3**

A Sardaukar doesn't need a range difference for his weapons. 

We want to bring the **D2k mod in line with the original game**, don't we?

**Comment by pchote** [comment]
Tibed for me says that `M_HMG` has a range of 112 and `M_LMG` a range of 80. I assume these are given in pixels, because 80 / 32 = 2.5 and 112 / 32 = 3.5 cells?

**Comment by MustaphaTR** [comment]
Sight is the vision range, not weapon range. I think what PChote said would be correct, considering all these values on OpenRA should be already correct to original.

**Comment by VonNah** [comment]
Now I see the problem. The Sardaukar **also** fires his **M_HMG** at _infantry_ in the original (his sight range equals his HMG firing range and you can hear the `20MMGUN1.WAV` firing sound):

![M_HMG](https://user-images.githubusercontent.com/65423234/104227547-7e175d80-5441-11eb-98db-4fa04ba19f4f.png)


He **only** uses his `M_LMG` (`MGUN2.WAV`) when he engages enemy _infantry_ in close combat (2.5 cells)! 

The OpenRA range values should be of course correct.

Why they use **both** their weapons when dealing with _infantry_ (depending on range), but then switch to the HMG only when firing at tanks/buildings is something I don't have an answer for.

My mistake in the beginning was that I targeted my own infantry and when they were not in close combat range Sardaukars used the **M_HMG**. This is why I thought that both weapons have the same range.

**Comment by pchote** [comment]
@abcdefg30 do you mind if I file a PR implementing my proposed fix above (since you've assigned yourself this issue)?

**Comment by abcdefg30** [comment]
I don't mind.
