### ISSUE TITLE
Connection lost while playing vs AI

### ISSUE THREAD

**Issue by Beep6581** [OpenRA/OpenRA#18932]
playtest-20201213
`OpenRA-Red-Alert-playtest-x86_64.AppImage` in Sabayon Linux.

When playing the Europe map with all opponent spots filled with various AI, far into the game a message pops up, something along the lines of "Connection to localhost lost: 127.0.0.1:32123". I took a screenshot but lost it on reboot. I reproduced twice. At that point I can still order my units around using the mouse, but the game ignores most keystrokes, though some still work, e.g. I can hold shift to give several orders.

If I keep playing, despite the message in the middle of the screen and despite most keyboard input not working, trying to get the satisfaction of ending the game, eventually mouse input fails as well. It's as if the game locks the cursor to the middle of the screen horizontally/vertically. If I alt+tab back to KDE, the mouse cursor is still locked and unusable. If I quickly move the cursor, it jumps right back to the center position. I have to kill the game to unlock it.

The `server.log` shows this:
```
[2020-12-15T11:39:47] Failed to set socket option on 127.0.0.1:0: Protocol option not supported
[2020-12-15T11:39:47] Initial mod: ra
[2020-12-15T11:39:47] Initial map: affb2fdc49d93e9c6eac29225d3c354418aedc81
[2020-12-15T11:39:47] Client 0: Accepted connection from 127.0.0.1:49562.
[2020-12-15T11:39:47] Johnson (127.0.0.1:49562) has joined the game.
[2020-12-15T11:39:47] Order lag is now 3 frames.
[2020-12-15T11:39:47] Player @127.0.0.1:49562 is NotReady
[2020-12-15T11:41:13] Order lag is now 1 frames.
[2020-12-15T13:25:21] Dropping client 0 for excessive order length = 134682
```
[ra-2020-12-15T104113Z.orarep.zip](https://github.com/OpenRA/OpenRA/files/5695975/ra-2020-12-15T104113Z.orarep.zip)

**Comment by pchote** [comment]
Note that the replay needs to be patched with a metadata block before it will show up in the replay browser.

This is a ~70 minute 1vbots game on the Europe map. The uncompressed replay is 155MB, and the bots build up huge armies in their bases, so my first assumption is that this was the expected outcome from trying to play vs many bots on a disconnected island map.

There is a chance that this may be a regression related to the recent AI changes, so deeper investigation is needed. If not (and maybe even if so), we should disable bots on this map or drop it again from the map pool.
