### ISSUE TITLE
missile can live forever on certain condition

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#18944]
![bug](https://user-images.githubusercontent.com/13763394/102712351-82959e00-42fb-11eb-90ef-84108b3d53b8.gif)

Only happens in SP so far and it is an old bug.

I suggest adding an timer for missile projectile to make it disappear when it is stuck like that.

**Comment by Mailaender** [comment]
Interesting, but it needs a repro case here. Some unit in some thirdparty mod is too vague to be remotely fixable.

**Comment by dnqbob** [comment]
```
	Projectile: Missile
		TerrainHeightAware: true
		CruiseAltitude: 4000
		MinimumLaunchAngle: 255
		MaximumLaunchAngle: 255
		MaximumLaunchSpeed: 0c543
		MinimumLaunchSpeed: 0c301
		Speed: 700
		Blockable: false
		Shadow: true
		HorizontalRateOfTurn: 160
		VerticalRateOfTurn: 160
		RangeLimit: 28c291
		AllowSnapping: true
```

1. arm aircraft with this projectile to attack both air and ground. (you can use Banshee to test it) 
2. it is better tested in TS mod, because I don't know if first generation game mod will have this bug since the second generation game mod is more complicated on motion calculations.
