### ISSUE TITLE
Not many players using playtest, playtestday to the rescue!

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#18946]
Not many testers in FFA or big games in playtest.
_The new balance with resets of superpowers and others will not be tested._

We need playtestday! (or something else)

One way to fix it:
**Playtest day**

- All servers also have one MOTD on for example Tuesdays, it says: "Tuesdays are playtest day. Please use playtest on that day if it's newer"
- Servers change some of the servers automatically also to playtest on that day
- Discord and IRC bots write message to correct channel that day that is is playtest day
- The playtest servers (if newer) comes on top on playtestday, if it's installed.
- Message to players or text in main menu say that its playtestday, ask if you want to switch to detected newer playtest.
- One server on top named "playtest day, please install that" on release-serverlist if that is older
-Some other ideas...

Even one of them will help. Even once a month or second week will help.

**Comment by abcdefg30** [comment]
I think it would be good to organise this on Discord. A ticket in the issue tracker doesn't get as much traction from the community.
