### ISSUE TITLE
Overhaul settings panel layout

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#18952]
Seems that the settings panel was not conceived with extensibility in mind and over time has become a little too crammed. Adding new settings is difficult on most panels (Display, Input, Advanced) and adding new tabs is also limited to the width of the panel.

I've put together a proposal that can solve both problems by:
1. Putting all settings in a scroll panel (stacked, ideally one per setting per "line")
1. Moving tabs to the side and stacking them 

![Settings Window](https://user-images.githubusercontent.com/1355810/102932522-1f496e80-44a9-11eb-8c03-0bf4a0ce3ec7.png)

**Comment by pchote** [comment]
Comment:

Moving the settings inside a scrollpanel is a good idea, but we don't have any precedent for vertically stacked tabs so i'm not sure that would look/feel right. Would you be able to show a more concrete mockup of this in the RA and TD UI layout?

Spitballing:

What if we showed all of the settings in the same scrollpanel with separators between them, and presented the buttons on the left as buttons (under a "Jump To" heading?) instead of tabs? This would be a more efficient use of space instead of having half-empty scrollpanels for the audio and whatever we end up splitting the Display tab into. It would then also be amazing if we could add a search box that hid all but matching settings.

I don't know how the hotkey settings would fit in this... maybe have a button to pop out a dedicated panel like many other games do?

**Comment by beercanchicken** [comment]
The vertical stack convention to select the contents of a dynamic area to the right is used commonly in other software.  It could be done using the standard button or possibly a select widget with each pane as an option (styled with a total height greater than the combined height of the options.)  Throwing in a +1 for this modification.

**Comment by dragunoff** [comment]
A select widget could work as well, especially combined with a search field:
![Settings Window (filter)](https://user-images.githubusercontent.com/1355810/102985146-5d7d7700-4517-11eb-813e-f27e809da7d8.png)

Hotkeys would then need to be handled in a popup dialog.

I am more inclined towards the first option though - it would be easier to implement and it give some more flexibility (e.g. hotkeys). I will put together some mockups using game assets.

**Comment by dragunoff** [comment]
Another option is to use the side column from the mission and asset browser:
![Settings Window (filter)](https://user-images.githubusercontent.com/1355810/102990113-80138e00-451f-11eb-8649-7863a95c90ac.png)

**Comment by dragunoff** [comment]
Here's a mockup of my initial idea:
![openra-ts-settings-panel-mockup](https://user-images.githubusercontent.com/1355810/102990182-a5a09780-451f-11eb-81fa-291eb6f1705b.png)

I think it works for the common UI as it resembles the replay browser and the asset browser. It would probably look out of place in TD but TD can keep the top tabs for the time being.

**Comment by dragunoff** [comment]
I've started working on this (not for TD, yet) and I'm overall quite happy with the result. Here are some screens from a WIP - feedback is welcome:
![Screenshot_20210919_192722](https://user-images.githubusercontent.com/1355810/133935518-efbf8e85-c11d-4bae-baec-e128dbb977cd.png)
![Screenshot_20210919_192736](https://user-images.githubusercontent.com/1355810/133935521-9fc41406-6198-44f6-a837-7a25436e9b2e.png)
![Screenshot_20210919_192646](https://user-images.githubusercontent.com/1355810/133935517-5db3017e-92ae-434c-8ed2-e23b473e1f07.png)
![Screenshot_20210919_192753](https://user-images.githubusercontent.com/1355810/133935522-9240fd30-b2be-4686-9dec-9ac3903c6a24.png)
![Screenshot_20210919_192821](https://user-images.githubusercontent.com/1355810/133935523-ebfbb52e-195e-4db1-8043-5e2ffdbddfbf.png)

**Comment by dragunoff** [comment]
I converted TD to the new layout as well and also changed the game info panel to vertically stacked tabs for consistency. I think it looks nice and is also a small step towards #16596.

![Screenshot_20210922_172916](https://user-images.githubusercontent.com/1355810/134363220-74e776d3-98dd-43c0-8adc-35a4cd661d14.png)
_Settings panel with vertical tabs_

![Screenshot_20210922_172900](https://user-images.githubusercontent.com/1355810/134363207-0d7c2019-b0e4-4ced-b8f5-10cf4036525d.png)
_Game info panel with vertical tabs_
