### ISSUE TITLE
Playtest 20201213 hangs on launch

### ISSUE THREAD

**Issue by hannesoid** [OpenRA/OpenRA#18956]
## Issue Summary

The latest Playtest hangs on launch.

## Reproduction

Launch the OpenRA-playtest-20201213

## Expected behavior

It should launch

## Actual behaviour

It stays on the launch screen indefinitely
<img width="1200" alt="Bildschirmfoto 2020-12-23 um 22 53 52" src="https://user-images.githubusercontent.com/1856655/103039681-c4c81500-4571-11eb-800a-166ac11f785f.png">

## System
macOS Big Sur 11.1
iMac Pro 10core 32GB, Vega 64 16GB

…any logs you need?

**Comment by anvilvapre** [comment]
Could you try collecting a mono stack dump.

```
# Start ITerm
# Start bash shell
bash
# Start game by entering full path to install location
/fullpathto/appimage &
# Echo process id of last started application. Not sure this will be the mono process.
echo $!
# Or
ps -auxw | grep mono # On Linux, on Mac the options are a bit different. 
# Or look it up in the process manager.

# After send a QUIT signal to the process. The process will be interrupted but will keep running.
kill -QUIT <processidnumberofmono>
# It should cause mono to display a stack trace, showing what the OpenRA main game thread is currently doing.
# Repeat kill command a few times to see if the (top) output changes. 
# Share the output. 
```

And please share the exception and graphics log if they are present.

**Comment by hannesoid** [comment]
I just figured out it may be using dotnet rather than mono. I cloned the repo and ran it with dotnet 5, then killed the stuck dotnet process. The crash report looks a bit like there may be a recursion, but not sure how to interpret it:

[dotnet_2021-01-18-103316_Hanness-iMac-Pro.log](https://github.com/OpenRA/OpenRA/files/5829219/dotnet_2021-01-18-103316_Hanness-iMac-Pro.log)

In the logs folder, the only updated log files after running are these:

<img width="608" alt="Bildschirmfoto 2021-01-18 um 10 27 41" src="https://user-images.githubusercontent.com/1856655/104896725-cec61380-5977-11eb-8212-a77f4be4b34e.png">

[perf.log](https://github.com/OpenRA/OpenRA/files/5829147/perf.log)
[nat.log](https://github.com/OpenRA/OpenRA/files/5829148/nat.log)

**Comment by pchote** [comment]
Playtest 20201213 requires mono, the switch to .NET 5 happened after it was branched. Was your opening report also built from source, or running the download from the website?

**Comment by hannesoid** [comment]
ah, thanks for the info. I originally downloaded it from the website though. 

Now I just cloned the repo (`bleed` branch) and ran it from Visual Studio for Mac (with dotnet I guess). 
Fyi, this is where it seems to be hanging in `Game.cs`
<img width="847" alt="Bildschirmfoto 2021-01-18 um 10 51 02" src="https://user-images.githubusercontent.com/1856655/104899894-b1934400-597b-11eb-995f-97df583a170a.png">

**Comment by hannesoid** [comment]
Is Visual Studio for Mac the recommended way of developing/debugging it? (I just installed this for the first time)

**Comment by pchote** [comment]
Ok, thats really helpful: that shows that the game is waiting for the UPnP discovery to return, which apparently is never happening. UPnP is disabled by default because it is unstable, and is known to cause problems exacty like this. I guess that you were able to run previous versions of OpenRA, and at some point turned it on in the Advanced settings?

If you open `~/Library/Application Support/OpenRA/settings.yaml` with a text editor and change the `DiscoverNatDevices: True` line to `DiscoverNatDevices: False` (or just delete the line, or the entire file) it should solve the problem.

**Comment by hannesoid** [comment]
Ha, perfect, that worked! Thanks so much @anvilvapre and @pchote for helping!
I removed the `DiscoverNatDevices: True` line from  `~/Library/Application Support/OpenRA/settings.yaml`.

For the record for non-techy people, 
1. open TextEdit app
1. Hit CMD+SHIFT+G to open the folder `~/Library/Application Support/OpenRA`
1. open `settings.yaml`
1. remove the line `DiscoverNatDevices: True`
1. save the file

**Comment by FikriRNurhidayat** [comment]
I have the same issue, but I ran the game on Arch Linux btw.
Changing the `DiscoverNatDevices: False` doesn't work for me, since by default it is not there, and the default value is `False`.

Version: 20210321-1

**Comment by taoeffect** [comment]
Hi guys, I'm running into a similar issue trying to run the RA2 mod: #804

I want to try this solution, however, `settings.yaml` doesn't exist, so I don't know how to modify it... what should it look like, or how do I generate it?

FYI, `bleed` does run, but I get a hang (with a completely black screen) running `release-20210321` (needed by ra2)

**Comment by taoeffect** [comment]
Hi guys, I'm running into a similar issue trying to run the RA2 mod: https://github.com/OpenRA/ra2/issues/804

I want to try this solution, however, `settings.yaml` doesn't exist, so I don't know how to modify it... what should it look like, or how do I generate it?

FYI, `bleed` does run, but I get a hang (with a completely black screen) running `release-20210321` (needed by ra2)


EDIT: I opened issue #20639 for this
