### ISSUE TITLE
Wrong and unused Mechanic audio files in Red Alert

### ISSUE THREAD

**Issue by VonNah** [OpenRA/OpenRA#18962]
Field mechanics (Allied support units) are missing two "Move" audio files **myes1.aud**, **mrise1.aud** which were falsly coded as their "Select" voices. These were also missing the file **mlaff1.aud**. Furthermore their "Action" voices are lacking the **myeehaw1.aud**.

Those missing aud files are all available in OpenRA's Red Alert sounds.mix.

I fixed my **voices.yaml** in OpenRA\mods\ra\audio like this:

MechanicVoice:
	Voices:
		Select: mhuh1,mhowdy1,**mlaff1**
		Move: mboss1,mhear1,myes1,mrise1
		Action: mhotdig1,mwrench1,**myeehaw1**
		Die: dedman1,dedman2,dedman3,dedman4,dedman5,dedman7,dedman8
		Burned: dedman10
		Zapped: dedman6

Now our mechanics have the appropriate aud files Weswood Studios originally assigned to them in 1997's Aftermath expansion for Command & Conquer: Red Alert.

I hope that this issue gets fixed for the next OpenRA release.

**Comment by abcdefg30** [comment]
Those two aren't in the `sounds.mix` I have locally either.

**Comment by VonNah** [comment]
Those sounds are located in the sounds.mix from the Aftermath expansion. I Installed it manually after buying Red Alert and its expansions from Origin. These files we are talking about were then put in the regular sounds.mix I had before installing the expansion via "Manage Content" in OpenRA Red Alert.

![aftermath3](https://user-images.githubusercontent.com/65423234/103140703-bf89d800-46e1-11eb-8245-127bcd215331.PNG)

**Comment by abcdefg30** [comment]
We extract those files to `Content\ra\v2\expand` as it looks, so it should be possible to use them.

**Comment by abcdefg30** [comment]
Tbh, I find `mlaff1` to be a very weird selection sound, and personally wouldn't include it.
