### ISSUE TITLE
Units sitting in AttackMove doing nothing

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#18974]
Reported by upps on the community discord.

https://user-images.githubusercontent.com/167819/103178601-24793580-487c-11eb-85c8-7c65ef24acf0.mp4

[ra-Server-2020-12-27T162604Z.orarep.zip](https://github.com/OpenRA/OpenRA/files/5745089/ra-Server-2020-12-27T162604Z.orarep.zip)

The infantry are sitting in the base `AttackMoveActivity` for several seconds without having any active child activities, which I didn't think was possible.

<img width="744" alt="Screenshot 2020-12-27 at 19 42 13" src="https://user-images.githubusercontent.com/167819/103178635-67d3a400-487c-11eb-8034-19f3454bcf35.png">

**Comment by pchote** [comment]
This is (to no big surprise) ~caused~ revealed by the sight/scan range mismatch on RA infantry.

The infantry get stuck in a loop:
* `AttackMoveActivity.Tick` begins, sees `ChildActivity == null `, and scans for a target
* `autoTarget.ScanForTarget` returns `pbox 1064`, which the video above shows is frozen under the fog immediately outside their sight range
* A new attack activity is queued with `allowMovement: false`, and then immediately run
* `Attack.TickAttack` bails with `AttackStatus.UnableToAttack` because the target is a frozen actor and its not allowed to move into sight range
* The inner attack returns via the final `return true` and is discarded
* `AttackMoveActivity.Tick` therefore ends the tick with a null child

**Comment by pchote** [comment]
I believe that https://github.com/OpenRA/OpenRA/commit/c8af8f3a2115aa1be7ef394308c0fc31d7a1dd5a should fix this, but don't really want to go to the effort of constructing a test case to prove it.

Can someone else take this the rest of the way?

**Comment by deleted-user-1** [comment]
> because the target is a frozen actor and its not allowed to move into sight range

Why does sight/being a frozen actor matter here (why should it matter)? Shouldn't it all be based on the weapon range (i.e. why is it not allowed to move when it is outside range and why doesn't it attack when it is inside range)? Other units too attack frozen actors when in weapon range.

**Comment by pchote** [comment]
> Other units too attack frozen actors when in weapon range.

This isn't quite correct. Units will respond to manual orders to attack frozen actors, but with only a couple of exceptions (artillery) will not automaticaly attack frozen actors.

**Comment by deleted-user-1** [comment]
> > Other units too attack frozen actors when in weapon range.
> 
> This isn't quite correct. Units will respond to manual orders to attack frozen actors, but with only a couple of exceptions (artillery) will not automatically attack frozen actors.

Hm that's surprising me although I remember something about artillery type units being special in some regard. However tesla coils attacking frozen actors of enemy base defences (and it being considered "bad") was afaik the reason for the balance changes done to them. So there are some other units that do auto-attack frozen actors.

**Comment by abcdefg30** [comment]
Wouldn't the better fix be to let `AttackMove` have `AutoTarget` scan using the weapon range? In general we might need to adjust that logic to not always use the maximum of the first `AttackBase` trait.

**Comment by pchote** [comment]
I take back my previous comment about this being caused by the sight/scan range mismatch. That is not the bug here, just the edge case that exposes it.

AttackBase defines
https://github.com/OpenRA/OpenRA/blob/2fee62af4d551d575afe85398a64f35b90511b9a/OpenRA.Mods.Common/Traits/Attack/AttackBase.cs#L42-L43
and AttackFrontal's AttackActivity conforms to this behaviour by not automatically firing on frozen actors. Its not explicitly documented, but IMO reasonably intuitive that the attack activity would move the actor within sight range if it is either explicitly given a frozen actor, or an existing target becomes frozen due to loss of sight. This isn't that different to the actor moving if the target moves out of range. In both cases, the actor will not move and instead abandon the target if the activity was created with `allowMove: false`.

The problem here is that `AutoTarget` is ignoring this property, which means it is giving an invalid target to the attack activity. Changing the scan radius might hide the bug, but does not change the fact that the current code is wrongly ignoring this field.

**Comment by deleted-user-1** [comment]
>  IMO reasonably intuitive that the attack activity would move the actor within sight range if it is either explicitly given a frozen actor, or an existing target becomes frozen due to loss of sight. This isn't that different to the actor moving if the target moves out of range. In both cases, the actor will not move and instead abandon the target if the activity was created with allowMove: false

I guess that's reasonable for explicit attack orders, it's RA's (intended) sight and range setup that might cause unexpected results here.

> The problem here is that AutoTarget is ignoring this property, which means it is giving an invalid target to the attack activity.

Also note that this is happening in AttackMove, which never should stop because some target has become invalid for some reason imo. I'd expect the unit to move on to the location then. In that case, the infantry would have re-targeted the pillbox I assume.
