### ISSUE TITLE
TD Harvesters do not have a regular explosion and sound effect

### ISSUE THREAD

**Issue by VonNah** [OpenRA/OpenRA#18975]
Only if a Harvester has harvested Tiberium, it makes/reports an explosion effect and sound upon its destruction.

Empty Harvesters just leave a burning Husk without making/reporting the aforementioned effects upon their destruction.

In the original game they make a huge explosion and report **xplos.aud**.

I added the corresponding **fball1.shp** because I can't find it in the OpenRA repository. 

[fball1.zip](https://github.com/OpenRA/OpenRA/files/5745173/fball1.zip)
![harvexplo1](https://user-images.githubusercontent.com/65423234/103179677-47a8e280-4886-11eb-8831-c154d0456256.png)
![harvexplo2](https://user-images.githubusercontent.com/65423234/103179678-4a0b3c80-4886-11eb-95fe-b509256d86c3.png)

**Comment by pchote** [comment]
Did you want to include a fix for this in #18972? It should just require an additional `Explodes@EMPTY` definition that triggers a `UnitExplodeHarvEmpty`. fball1.shp is available (it shows up in the asset browser), so shouldn't need to be added separately.

**Comment by VonNah** [comment]
Yes I will try to fix the Harvester in #18972.

**Comment by VonNah** [comment]
#18972

**Comment by reaperrr** [comment]
Fixed in #18972.
