### ISSUE TITLE
Infiltrating super weapons does not reset active targeting cursor

### ISSUE THREAD

**Issue by deleted-user-1** [OpenRA/OpenRA#19014]
An activated nuke/chrono/ic cursor (or selection in case of chrono) will not reset to the default cursor when the structure is infiltrated. The power can not be used though.

The cursor should instead be reset to make it consistent and tell the player that he can not use the power. It's a polish on the first look but could be frustrating if you for example have some units already in the chrono selection and are scanning the enemy base for a good location, only to learn on execution that it doesn't work. Feature was introduced in #17783.

**Comment by pchote** [comment]
Likewise if the player goes into low power.
