### ISSUE TITLE
MCV does not have a notification to play when transforming and broken TransformNotification trait

### ISSUE THREAD

**Issue by VonNah** [OpenRA/OpenRA#19046]
## Issue Summary

You don't hear EVA saying _"New construction options"_ when converting your MCV into a Construction Yard across all OpenRA mods. 

For testing purposes I added the missing `TransformNotification` trait to mods\d2k\rules\vehicles.yaml which added said notification, but the issue here is that when players still have their original Construction Yard and then build another MCV which they convert into a second one, they are going to hear the notification again. This is not how it works in the original games.

## Reproduction

Just add the `TransformNotification` trait to mods\d2k\rules\vehicles.yaml. It should look like this:

![mcvnotification](https://user-images.githubusercontent.com/65423234/104384644-b1cdb280-5529-11eb-90ed-55627d756eb2.PNG)

Launch OpenRA and deploy your MCV. You should be greeted with _"New construction options"_. Now build another MCV and deploy it. 

Although your initial Construction Yard enabled you to build structures you are still going to hear _"New construction options"_ again. 

## Expected behavior

You should not hear _"New construction options"_ for a second time after transforming another MCV when you already have a Construction Yard.

**Comment by abcdefg30** [comment]
This is not a bug with TransformNotification which should play on every transform. We need to change how the "New Construction Options" notification is played at the moment: #19048
