### ISSUE TITLE
Reduce Tanya's firing rate

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#19055]
The consensus of feedback is that the attack fixes have made Tanya too powerful. I believe that the current firing rate is also so fast that the attack animation does not have time to finish before the next shot.  We should make it burst: 2 and reduce the firing rate to at least the point where the firing animation works properly.

**Comment by matjaeck** [comment]
Needed though quite sad, she was definitely broken but in a lovely way that actually worked. I liked how it was balanced by flawed mechanics, as I liked that broken parabombs were balanced by randomness. Maybe it's not as bad as I imagine right now, lets see... Burst seems reasonable, I'll miss the gun sound though.

Just an alternative thought: What if she gets some sort of dynamic inaccuracy, like when she stands still for some timeframe, her precision approximates 100% and when shes moved, she will be at 85% or so, and the longer she stands still the better her accuracy gets. No idea if this would be fun, I just think the nerf is boring (although seems correct) and feels overhasty so wanted to suggest something.

**Comment by matjaeck** [comment]
Ah I see the animation is the key point here, so this is unrelated to the recent attack move changes. Nvm then.

**Comment by MlemandPurrs** [comment]
in e7's attack anim fires the gun 5 times within one sequence of attack.

**Comment by pchote** [comment]
This is what I had in mind:

https://user-images.githubusercontent.com/167819/104821097-75ec6300-5831-11eb-9e3c-41ea831507d9.mov

This is using the same 5 &rarr; 7 tick *average* firing rate nerf suggested by the competitive community, but is implemented as 4 + 10 ticks to sync up with the animation and to sound a bit better than a uniform rate.
