### ISSUE TITLE
Building on Arch Linux: .NET dependency issue

### ISSUE THREAD

**Issue by fusion809** [OpenRA/OpenRA#19050]
## Issue Summary
I noticed that the version of .NET in Arch's official repositories was no longer adequate for building OpenRA, due to this error:

```bash
/data/GitHub/others/OpenRA/OpenRA.Launcher/OpenRA.Launcher.csproj : error NU1201: Project OpenRA.Game is not compatible with net50 (.NETFramework,Version=v5.0). Project OpenRA.Game supports: netstandard2.1 (.NETStandard,Version=v2.1) [/data/GitHub/others/OpenRA/OpenRA.sln]
/data/GitHub/others/OpenRA/OpenRA.Launcher/OpenRA.Launcher.csproj : error NU1201: Project OpenRA.Game is not compatible with net50 (.NETFramework,Version=v5.0) / linux-x64. Project OpenRA.Game supports: netstandard2.1 (.NETStandard,Version=v2.1) [/data/GitHub/others/OpenRA/OpenRA.sln]
```

I then thought the obvious solution would be downgrade my .NET packages to the 2.1 version. This I did by installing the following AUR packages:

* [dotnet-runtime-2.1](https://aur.archlinux.org/packages/dotnet-runtime-2.1)
* [dotnet-sdk-2.1](https://aur.archlinux.org/packages/dotnet-sdk-2.1)

Then I got a different error:

```bash

/usr/share/dotnet/sdk/2.1.811/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(150,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Standard 2.1.  Either target .NET Standard 2.0 or lower, or use a version of the .NET SDK that supports .NET Standard 2.1. [/data/GitHub/others/OpenRA/OpenRA.Game/OpenRA.Game.csproj]
/usr/share/dotnet/sdk/2.1.811/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(150,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Standard 2.1.  Either target .NET Standard 2.0 or lower, or use a version of the .NET SDK that supports .NET Standard 2.1. [/data/GitHub/others/OpenRA/OpenRA.Mods.Cnc/OpenRA.Mods.Cnc.csproj]
/usr/share/dotnet/sdk/2.1.811/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(150,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Standard 2.1.  Either target .NET Standard 2.0 or lower, or use a version of the .NET SDK that supports .NET Standard 2.1. [/data/GitHub/others/OpenRA/OpenRA.Mods.Common/OpenRA.Mods.Common.csproj]
/usr/share/dotnet/sdk/2.1.811/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(150,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Standard 2.1.  Either target .NET Standard 2.0 or lower, or use a version of the .NET SDK that supports .NET Standard 2.1. [/data/GitHub/others/OpenRA/OpenRA.Mods.D2k/OpenRA.Mods.D2k.csproj]
/usr/share/dotnet/sdk/2.1.811/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(150,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Standard 2.1.  Either target .NET Standard 2.0 or lower, or use a version of the .NET SDK that supports .NET Standard 2.1. [/data/GitHub/others/OpenRA/OpenRA.Platforms.Default/OpenRA.Platforms.Default.csproj]
```

Now I'm kind of stuck. 

## Reproduction
Install all dependencies for OpenRA listed here: https://archlinux.org/packages/community/any/openra/. Then install dotnet-runtime-2.1 and dotnet-sdk-2.1 from the AUR, and use the following commands (assuming you are in an up-to-date copy of the OpenRA GitHub repository):

```bash
make clean; make; cd packaging/linux; ./buildpackage.sh $(git rev-list --branches $(git-branch) --count).git.$(git log --oneline | head -n 1 | cut -d ' ' -f 1 | head -c 7) ~/Applications/OpenRA
```

## Expected behavior
For OpenRA's AppImage to successfully build.

**Comment by pchote** [comment]
OpenRA's AppImage packaging now require .NET 5.0. .NET Core 2.1 is now two major revisions out of date.

#19026 adds support for compiling local builds using either .NET 5.0 or mono, but that won't help with building AppImages (note: the dependencies for *running* the AppImages haven't changed).

**Comment by pchote** [comment]
https://aur.archlinux.org/packages/dotnet-sdk-preview/ might be what you need.

**Comment by fusion809** [comment]
Thanks, bizarre that the first error seemed to asking me to use .NET 2.1 though. I'm in the process of installing dotnet-sdk-preview, if I find it works I'll close this issue.

**Comment by fusion809** [comment]
Yep, builds fine with dotnet-sdk-preview, thanks.

**Comment by pchote** [comment]
Ah, I see. .NET Standard 2.1 != .NET Core 2.1, and in fact you need at least .NET Core 3.0 to compile against .NET Standard 2.1. Microsoft naming at its best 😁
