### ISSUE TITLE
My game crashedException of type `System.InvalidOperationException`: Unit `neutralfabricator` does not have a sequence named `dead`

### ISSUE THREAD

**Issue by Akudann89** [OpenRA/OpenRA#19065]
## System Information

- Operating System:  OPERATING SYSTEM
- OpenRA Version: ENGINE VERSION
- OpenRA Mod: GAME MOD
- Source: Official download package OR self-compiled OR third-party package
- For self-compiled or third-party packages: Mono version

## Exception log

```
PASTE LOG HERE
```

**Comment by dnqbob** [comment]
dude I think you should push to 
https://github.com/ABrandau/Shattered-Paradise-SDK

This is the upstream branch which only response for RA/CNC/TS

**Comment by reaperrr** [comment]
The exception strongly suggests that this is either a yaml setup issue or missing sprite file in a third-party mod. Closing as it's very unlikely to be an issue with OpenRA, nor providing any information suggesting otherwise.
