### ISSUE TITLE
Minelayer should follow same path back and only then head to SD

### ISSUE THREAD

**Issue by praetp** [OpenRA/OpenRA#19070]
## Motivation
The mine layer is vulnerable on its way back to the SD as it simply takes the shortest route. When sending the mine layer to its destination, the user can shift-queue a desirable path (typically a safe route away from enemy units). But on the way back the mine layer will often drive through the enemy base leading to its demise.
Implementation this feature will make the mine layer more useful. 

## Proposed solution
When the mine layer has placed its mines, it should take the same way back. When done, it should go to the nearest SD (if not already there).

I did not check if it is feasible to implement this... I can imagine the game does not store the previous path taken for instance..

**Comment by abcdefg30** [comment]
Closing as wontfix/duplicate of #4380. See https://github.com/OpenRA/OpenRA/issues/4380#issuecomment-799767521 for a proposed solution.
