### ISSUE TITLE
Barrel explosions should create fireball effects in adjacent cells

### ISSUE THREAD

**Issue by Smittytron** [OpenRA/OpenRA#19079]
Looking at Remasters, barrels are supposed to produce large fireball effects in the adjacent cells (up, down, left, right) in addition to their own cell.

**Comment by VonNah** [comment]
Barrels also use an incorrect impact/explosion sound. In the originals they reported multiple sounds **simultaneously**, but I am not sure how to replicate this in OpenRA.

You can hear it loud and clear in the first soviet mission:

https://youtu.be/HYO0_0OtIS4?t=184

**Comment by Smittytron** [comment]
Barrels should also use `large_napalm` explosion.

**Comment by Mailaender** [comment]
Try using https://docs.openra.net/en/latest/playtest/weapons/#fireclusterwarhead
