### ISSUE TITLE
SAM Site couldn't be sold in Remastered TD

### ISSUE THREAD

**Issue by KautionORA** [OpenRA/OpenRA#19094]
## Issue Summary

with debug menu and /all , I Was Making a compound to blow it up at the start of the stream, around minute 10 i started making pps, walls and fences along with SAM sites, the SAM site on the top right corner of the walls next to the pps, i couldnt sell that.

## Screenshots / Screen recordings / Replays

https://cdn.discordapp.com/attachments/761941266966904832/804034834276155392/unknown.png

[SAM site sell bug.zip](https://github.com/OpenRA/OpenRA/files/5886243/SAM.site.sell.bug.zip)

**Comment by pchote** [comment]
This was on a sync-compatible build with playtest-20201213.

**Comment by pchote** [comment]
It turns out that this is basically the same issue as #18969 - `TickIdle` runs the close animation while the building is being sold, cancelling and locking it. #18996 isn't sufficient, we need to be checking if its disabled too.
