### ISSUE TITLE
D2kBuilding & removal of LaysTerrain means D2k concrete no longer functions correctly

### ISSUE THREAD

**Issue by OmegaBolt** [OpenRA/OpenRA#19097]
Since LaysTerrain was removed, and merged into D2kBuilding, the functionality required for Dune 2000's concrete is no longer met.

D2kBuilding that has "AllowInvalidPlacement: true" means it will place the concrete on ANY terrain type below the foundation. Previously LaysTerrain had a check of its own for suitable terrain to override, but with D2kBuilding the concrete shares that check with the building itself.

In the intended functionality is that concrete only gets placed on clear rock tiles, and any invalid tiles are ignored.

![invalid](https://user-images.githubusercontent.com/8225171/106314182-44c45780-6261-11eb-9ab7-59963aac2532.jpg)

**Comment by pchote** [comment]
~tbh i'm not sure this is something that we need to fix - we specifically decided in the previous PR that it was going to be too hard to support both D2k's concrete laying behaviour and arbitrary modding use cases on the same trait. This is why it is now on `D2kBuilding` in `OpenRA.Mods.D2k`.~

~We'll eventually need to implement a new trait for TS-style concrete, and this may be more suitable for modders. Until then, they still have the option of implementing the specific logic they need in their own mod dll.~

Nevermind, i misinterpreted this as a modding request. I see now that this is actually a problem in the playtest d2k.
