### ISSUE TITLE
Improve server list validation

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#19098]
I've spent an unpleasant evening playing cat and mouse with somebody who has been trying (and occasionally succeeding) to take down the multiplayer services by crafting malicious server advertisements.

I have mitigated this on the server side, but this has highlighted two things that should also be fixed client side to improve robustness:
* `MapCache.QueryRemoteMapDetails` needs to filter null entries from `uids`.
* `ServerListLogic.RefreshServerList` should parse the `GameServer`'s using a loop, and drop just the malformed entry on a parse failure - not the entire server list.

**Comment by KOYK** [comment]
crafting malicious server advertisements?
Does that mean that we are in danger while in-game or something? if so when is it going to be fixed?

**Comment by pchote** [comment]
Fortunately no.

1. Everything is fine now.
2. When things weren't fine, it just crashed the game or said "failed to query games". There is no way for this to do anything actually harmful beyond stopping people from being able to play online.

**Comment by deleted-user-1** [comment]
> I've spent an unpleasant evening playing cat and mouse with somebody who has been trying (and occasionally succeeding) to take down the multiplayer services by crafting malicious server advertisements.
> 
> I have mitigated this on the server side

Thanks for immediately taking care of it .
