### ISSUE TITLE
Aircraft Repair Queuing Bug

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#19091]
Aircraft will not queue to repair. If you try to repair a 2nd aircraft the order won't be recognized until the 1st one finishes it's repair order (even before it reaches the repair facility). Applies to both TD and RA.

**Comment by deleted-user-1** [comment]
See also similar #18313 and #16712. Related: #18373

**Comment by Orb370** [comment]
Gosh dang it, I thought I made an issue on this. Thanks.
