### ISSUE TITLE
Mouseover whole mapname in map chooser

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#19108]
For long names, you cannot see the end of the name, and then you are not sure what version of the map you have.

My fix is to try to delete maps, then you can see the whole name.
Mouseover displaying whole name of map would be nice.

**Comment by anvilvapre** [comment]
Then you are using Very long map names? Over 20 characters of the map name are shown when I open the map chooser. Why not just use a name less than these 20 characters?
