### ISSUE TITLE
CarryCondition function for Carryall trait is broken

### ISSUE THREAD

**Issue by henskelion** [OpenRA/OpenRA#19116]
I tried to use CarryCondition under the Carryall trait to make it so that air transports are slower while carrying something, but it had no effect. However I used conditions to make it so air transports are slower when transporting units inside as cargo, and that did work. So it's likely that CarryCondition just doesn't work right, especially seeing as nothing in OpenRA actually uses this feature.

**Comment by Mailaender** [comment]
Works for me.
