### ISSUE TITLE
Regression in Allies 05a prison break

### ISSUE THREAD

**Issue by Smittytron** [OpenRA/OpenRA#19111]
In Allies 05a, after infiltrating the prison to free Tanya, the prison attacks itself to simulate the gun shots in the prison break. This no longer occurs and you can only hear Tanya's voice lines without the gunshots. This regressed in the last cycle between release-20200503 and playtest-20201213

**Comment by abcdefg30** [comment]
I removed the shots after @pchote asked me to for visual polish.

**Comment by abcdefg30** [comment]
Actually my bad, it was @obrakmann and @reaperrr asking me in #12896. (@pchote only asked me to remove the hack actor, not the effect.)

The discussion is at https://github.com/OpenRA/OpenRA/pull/12896#discussion_r112685539.
