### ISSUE TITLE
[Discussion] Interest in Growth / Product Contributor? 

### ISSUE THREAD

**Issue by colinplamondon** [OpenRA/OpenRA#19128]
## Motivation
I'm an OpenRA user for a year, and have a background as a startup founder / growth consultant. Seeing the new OpenRA ladder and RAGL tools, it struck me what cool product improvements they were. This is me throwing my hat in the ring and seeing if the OpenRA community would be interested in me contributing on Growth. 

I think today's OpenRA is better than any AAA RTS release since... Supreme Commander? It's really, really good. More people should discover it. 

Plus, I haven't heard of any open source project taking on growth in a systematic way. I think it'd be EXTREMELY good for the world to have an example of growth that's in the open. How to go about setting this stuff up, how to do event instrumentation, what kinds of emails work, what don't, just the general blocking and tackling that goes to helping a product grow faster. It's not really common knowledge.  

It's extremely hard for people new to tech, and new to product, to learn about growth without working their way up a ladder. It'd be way better if, like with engineering, junior product and growth people could contribute to open source projects as well.  

## Proposed solution
Implementing a basic growth stack, measuring player retention, and taking on a basic. This would require some client support, in the form of some basic event integration. 

1. **Basic Event and User Instrumentation.** I'd capture the events necessary to power this stack, and keep it to a minimum to minimize overhead. 
2. **Setup of Segment / [Customer.io](http://customer.io) / Amplitude, Getting OpenRA into Segment Startup Program.** This would be straightforward, we'd just need to work out how to have shared credentials for the maintainers of OpenRA. OpenRA would gain access to tens of thousands of dollars in free software, including $5k in Google Cloud credit. 
3. **Opt-In Splash Screen on First Run.** We'd add a step to OpenRA's first run that heavily incentivizes giving us your email. In so doing, you opt-in to tracking. The initial target would be getting to a 30% opt-in rate. 
4. **Optional Email Collect on Download.** Entirely optional, but top of the funnel. This usually gets a 15-20% opt-in, and makes it possible to optimize the installation and onboarding process.
5. **Behavioral implementation of OpenRA Academy Content.** I'd be happy to implement the emails, and work with the Academy folks to figure out how to make this smart and targeted to new users. Right now, this is buried. By putting it front and center of the onboarding experience, we should be able to drastically improve the rate at which new users onboard onto OpenRA.

For my part, I'm not a C++ developer, but would be able to handle some light backend coding to support new functionality with serverless functions. 

After some basic events are instrumented, I'd be able to help a lot with managing a content pipeline from OpenRA academy into opt-in email series, iterating on outgoing emails, and reporting on metrics / KPIs / experiments to the developer and user community.

### Enable Future In-App Improvements
With a foundational set of events, we would have SO much more data to play with to power in-game improvements. Some ideas could include:

1. **Integrated Build Order Trainer.** For new users, let them select their desired built order, and then highlight the buildings, including some dynamic tips around "thinking" about eco. 
2. **Mistake Alerts.** This could be something like building too many rockets for unit comp, rockets before the opponent could have a refinery, not scouting, or building radar before your third barracks. Highlighting the mistake, with a well-written, friendly, informative reason why, would help them avoid it in real-time.  
3. **Highlighted Lesson.** Based on recent games, highlight a "Lesson" from OpenRA Academy, and link off to a YouTube. This could be very, very lightweight at first: from data analysis, figure out what the most common mistakes are that lead to player churn, and surface info to help with that. No need to boil the ocean.
4. **Engagement Review.** If we track in-game "Major Engagements", it'd be possible to deep-link to engagements. We already have the replay. We already have arbitrarily large zoom distance. If it's possible to

If we structure the data for this in the right way, it'd probably be possible to put the bulk of this logic in the backend. It'd be awesome to have  

### More Detailed Concept / Proposal
Below's a link to a Loom video, and a Notion link, that goes into more detail on what I'm thinking.

**Loom Link:** https://www.loom.com/share/3c2c0eb057e84232b3b8d2f9ba54c66d
**Notion Link:** https://www.notion.so/thebeam/OpenRA-Growth-4268b09005dc465db45cec294896c31a

**Comment by Smittytron** [comment]
We appreciate and see the value in the ideas brought forward here, but we have limitations that would prevent work on this issue. After discussing this in Discord, we don't think it's feasible to go forward with this right now. Simply put, we don’t have the developer bandwidth to tackle the event tracking system this would require, and we're concerned that a system that could be perceived as explicit user tracking might cause significant blowback from some of our core demographics.

**Comment by colinplamondon** [comment]
Cool - thanks for following up @Smittytron . Best of luck, and as a user, goddamn love what you guys are putting out :)
