### ISSUE TITLE
Add option for fog of war to slowly generate back instead of being instant

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#19126]
Add option for fog of war to slowly generate back instead of being instant, same way as tiberium wars 3\KW
This should be as an option for user made mods, the point of this issue is not to be adapted by the official mods, but to allow modders use it on their mods.

**Comment by MlemandPurrs** [comment]
This might be interesting.
There even can be interaction with GAP generator's mechanism, ensuring they slowly regenerate shroud beyond their effective radius, the extra generated shroud generated this way would be not tied to their presence acting as normally explorable instead.

**Comment by KOYK** [comment]
It wont be fixed\added, closing it.
