### ISSUE TITLE
Game crashed every time, when i try to watch Mission Brief in Dune 2000

### ISSUE THREAD

**Issue by RobajziCloud** [OpenRA/OpenRA#19124]
## Issue Summary
I installed additional content in Dune 2000, and when I try to watch Mission Brief, the game crashed every time. But other games OpenRA Red Alert & OpenRA - Tiberian Down work perfectly, with briefings videos. 

DESCRIPTION

## Reproduction

I opened the game Dune 2000.
Click on Single player
Click on Mission
Chose any mission 
Click Watch Briefing

I am on MacBook Pro 13 with Apple M1

and every time game crashed

## Expected behavior

I expect to play the Mission Brief

## Screenshots / Screen recordings / Replays

Here is installed Campaign Briefings from CD.
<img width="583" alt="Screenshot 2021-02-03 at 16 29 57" src="https://user-images.githubusercontent.com/78492876/106769294-14076800-663d-11eb-91ca-eac9e42530e4.png">

Here is my exceptional file from crash
[exception-2021-02-03T153128Z.log](https://github.com/OpenRA/OpenRA/files/5919523/exception-2021-02-03T153128Z.log)

And here is warning
<img width="250" alt="Screenshot 2021-02-03 at 16 31 58" src="https://user-images.githubusercontent.com/78492876/106769589-69dc1000-663d-11eb-8fed-5e973cb1875c.png">

**Comment by pchote** [comment]
This is going to be a regression from #18661.

**Comment by PeterJakobsen** [comment]
Have this one as well.
I am on Windows 10.

**Comment by GEOGRU** [comment]
windows 10 can confirm =/

**Comment by msnjuegos** [comment]
I am having the same problem in Debian testing with the last Appimage version.
Here is the exception log 
[exception-2021-04-13T045348Z.log](https://github.com/OpenRA/OpenRA/files/6301333/exception-2021-04-13T045348Z.log)

**Comment by jimmyhsu** [comment]
Same exact issue as @msnjuegos, here's the log:
[exception-2021-10-23T035458Z.log](https://github.com/OpenRA/OpenRA/files/7402236/exception-2021-10-23T035458Z.log)

Movies were manually installed from the "Dune 2000: Gruntmods Edition" for the English Cutscenes

**Comment by reaperrr** [comment]
The fix was picked to prep before the last release, so reopening for now as it seems something still isn't entirely right.

**Comment by pchote** [comment]
IIRC gruntmods ships 0 byte dummy files as placeholders for the real movies. Crashing is the expected behaviour if those fake files are manually copied into OpenRA.

**Comment by abcdefg30** [comment]
We could just log an error and not play a video instead (similar to how we handle sounds that do not exist).
