### ISSUE TITLE
Smooth projectile rotation

### ISSUE THREAD

**Issue by Dzierzan** [OpenRA/OpenRA#19146]
Hi,

Well, the idea is to have an option in OpenRA where facings for projectiles are not required, at least the art for that. There could be art for one facing and the engine could rotate is automatically as soon as the projectiles rotates towards the target.

This is the feature I'd love to have for my OpenSA project, as the original Swarm Assault game did that for their projectiles. Currently I had to rip the art for bullets and create facings for them, which is not ideal.

https://github.com/Dzierzan/OpenSA/issues/28

Here's an example how it works in the original game.
https://i.imgur.com/LXlhsGW.gif

**Comment by Dzierzan** [comment]
Alright, I am closing this. I realized it's a feature which only benefits me and it's unlikely it will be done for ORA.

**Comment by pchote** [comment]
I want this feature one day, and it could potentially benefit the default mods by allowing us to interpolate between e.g. the limited aircraft facings.
