### ISSUE TITLE
mobile radar jammer won't jam missile subs

### ISSUE THREAD

**Issue by rcornelmas** [OpenRA/OpenRA#19159]
## Issue Summary

DESCRIPTION
mobile radar jammer don't deflect missile shot by submarines 

## Reproduction

STEPS TO REPRODUCE THE ISSUE
In the debug menu placing jammers around power plant or construction yards ,enemy missile subs can still guide their missile perfectly to the building 

## Expected behavior

missiles shoot by subs to be deflected away or round the building
EXPECTED BEHAVIOR

## Screenshots / Screen recordings / Replays

![OpenRA-2021-02-16T071737826Z](https://user-images.githubusercontent.com/79133135/108030513-0cca5c00-7038-11eb-8e71-7cfec5132d8e.png)

**Comment by reaperrr** [comment]
This isn't really a bug. It's just that sub missiles (intentionally) use the `Bullet` projectile, since they're meant to be non-tracking, ballistic artillery missiles. We'd have to make them use the `Missile` projectile to 'fix' this, but the question is, do we really want non-tracking, ballistic missiles to be jammable to begin with? It would make balancing a lot more tricky, since missile subs would become much easier to counter than cruisers.

**Comment by rcornelmas** [comment]
According to https://openra-red-alert.fandom.com/wiki/Mobile_Radar_Jammer
"The Mobile Radar Jammer defends nearby units against many missiles. Any guided missile is affected. This includes the missiles of: MiGs, submarines, mammoth tanks, chrono tanks, Longbows, etc. If it's homing - it's affected. "
so according to this wiki what submarines they meant ...?

**Comment by ParselyBunny** [comment]
This MRJ behavior is not intuitive given the unit's in-game description. The Mobile Radar Jammer's description says "Jams nearby enemy radar domes and deflects incoming **missiles**", so it's reasonable to expect missiles from missile subs to be deflected (and then be surprised when they aren't).

Here's a list of units and how they're affected by MRJ
## Missile/Rocket Units 
**Affected by MRJ**
- chrono tank 
- phase transport
- MIG 
- longbow
- destroyer
- rocket soldier
- mammoth tank
- SAM site
- subs (the torpedoes are deflected)

**NOT Affected by MRJ**
- V2
- missile sub

If the MRJ description was accurate, it might say something like "deflects incoming missiles, rockets, and torpedoes, except from missile subs and V2 rocket launchers". That's verbose though, so alternatively, change MRJ to say "deflects guided projectiles" and then explicitly clarify in the V2 and missile sub descriptions that they fire unguided projectiles.

**Comment by rcornelmas** [comment]
thanks for explaining that clearly ...  now iam closing this issue as it turned to be not a bug after all  ..
 may be i will open a suggestion for that later as a way to counter missiles from subs cause really they are hard near impossible  to stop when they are in masses
