### ISSUE TITLE
playtest20210131 install error on windows 7

### ISSUE THREAD

**Issue by eclaircs** [OpenRA/OpenRA#19157]
![openra_error](https://user-images.githubusercontent.com/72183556/107978645-1d5ae200-6ff8-11eb-9e73-078329fd55c1.png)

What's wrong with this one? Is my .NET too old?

**Comment by pchote** [comment]
Playtest 20210131 requires .NET Framework 4.7, and the next release will require .NET 5.0.

It looks like you're running Windows Vista, which microsoft have stopped supporting and won't run either framework. I'm sorry to say that you will have to update to Windows 7 or newer (or a Linux distribution) if you want to run OpenRA going forward.

**Comment by abcdefg30** [comment]
Microsoft has also ended support for Windows 7, so sadly we can't do more to support it.
