### ISSUE TITLE
Unable to start OpenRA PlayTest 20210131 (linux)

### ISSUE THREAD

**Issue by kreely** [OpenRA/OpenRA#19162]
## Issue Summary
Couldn't start OpenRA.

DESCRIPTION
./OpenRA-Red-Alert-playtest-x86_64.AppImage 
Platform is Linux
Engine version is playtest-20210131
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
Using SDL 2 with OpenGL (Embedded) renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1.00
OpenGL renderer: llvmpipe (LLVM 11.0.1, 128 bits)
OpenGL version: OpenGL ES 3.2 Mesa 20.3.4
Using default sound device
Failed to create secure directory (/run/user/1000/pulse): No such file or directory
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
AL lib: alsa_open_playback: Could not open playback device 'default': Device or resource busy
Failed to open device. Falling back to default
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
AL lib: alsa_open_playback: Could not open playback device 'default': Device or resource busy
Internal mods:
	modcontent: Mod Content Manager (playtest-20210131)
	ra: Red Alert (playtest-20210131)
External mods:
	ra-playtest-20210131: Red Alert (playtest-20210131)
Loading mod: ra
Loading mod: modcontent
Killed
Bail out! Gtk:ERROR:../../../../gtk/gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /org/gtk/libgtk/icons/48x48/status/image-missing.png: Unrecognized image file format (gdk-pixbuf-error-quark, 3)

## Reproduction

chmod u+x ./OpenRA-Red-Alert-playtest-x86_64.AppImage  
./OpenRA-Red-Alert-playtest-x86_64.AppImage  

## Expected behavior

Running game/startup screen

**Comment by pchote** [comment]
Can you provide some info on your hardware and software (distro/version/etc) setup?

Seeing this try to run under llvmpipe is suspicious, since I doubt that would ever be able to provide anywhere near a playable experience.

**Comment by kreely** [comment]
Devuan chimaera (64 bit), running under Qemu (with HyperV acceleration) on Windows 10 (64 bit).
X Server is VCXSrv (v1.20.9.0).
I appreciate I don't have (at all) an optimal environment. I just wanted to try it out and see if it worked.
The error above looks relatively generic? Looks like a missing file... Though if that file is related to a GL Surface, it could be problems with llvmpipe and rendering?
Should note, I can run vlc in this environment and it works pretty well with videos. I can also run Chromium BSU and it's fairly playable.
I'd completely understand if this bug isn't a high priority for the team.
Thanks.

**Comment by kreely** [comment]
I'd be happy if someone took note of the issue and closed it.
Based on my env. being quite odd.

**Comment by anvilvapre** [comment]
just some ideas ...

are you able to get `glxgears` running? as proof that opengl works.
have you installed libmesa, the software opengl renderer? because your virtual gpu likely doesn't have opengl support you will to fall back on (slow) software rendering.
what does the output of `xrandr` show.
is depth 32 or 24 in any of the modus shown by `xdpyinfo`.

is you visual perhaps 16bit colors, where the game perhaps requires 24 or 32 visual depth.

**Comment by kreely** [comment]
After installing libegl1-mesa-dev, it works.
It is a bit slow, as one would expect, but it goes. Well done everyone.
