### ISSUE TITLE
Add Yaml rules for Tiberian Sun 1tnk 2tnk 3tnk and ftnk

### ISSUE THREAD

**Issue by Leo512bit** [OpenRA/OpenRA#19180]
## Motivation

The RULES.INI in TS had the code for them.

## Proposed solution

I would add them but I don't have the time to learn git right now.

## Side effects

Extra complexity for the civilian-vehicles.yaml.

## Alternatives

Don't add them.

**Comment by reaperrr** [comment]
> The RULES.INI in TS had the code for them.

That's not correct. The original TS rules.ini (and art.ini) doesn't have entries for any of them.
Firestorm at least added the FTNK, but that's about it.

If your rules.ini has them, it's not the original file, but a modded one.

**Comment by Leo512bit** [comment]
> > The RULES.INI in TS had the code for them.
> 
> That's not correct. The original TS rules.ini (and art.ini) doesn't have entries for any of them.
> Firestorm at least added the FTNK, but that's about it.
> 
> If your rules.ini has them, it's not the original file, but a modded one.

Well its in mine and it says its official and I don't remember moding it but I did have it on an old HDD so I might have. Should I add the cut vehicle rules and keep #19188 open but with the same values as the ^Cannon for a place holder until we can get decide on what values we should use or call it quits?

Edit Pushed the wrong button

**Comment by Mailaender** [comment]
They are early test data for Westwood and @pchote as well https://forum.openra.net/viewtopic.php?f=83&t=16215 Sadly the image links are broken, but we had those voxels in the TD mod during development. They look quite alpha and likely won't make a return.
