### ISSUE TITLE
Building bridge trough Naval Yard/Sub Pen

### ISSUE THREAD

**Issue by bearoforange** [OpenRA/OpenRA#19190]
## Issue Summary
You can repair bridge and it will build trough water buildings.

## Reproduction
 1.  Explode/Break a bridge
 2.  Build Naval Yard/Sub Pen on the way of the bridge
 3.  Repair bridge using Engineer

## Expected behavior
I expected the bridge would not be repaired (the engineer would not repair it) or, in the worst case, Naval Yard would break (like naval units).

## Screenshots / Screen recordings / Replays
![image](https://user-images.githubusercontent.com/60433273/109284667-29814380-7831-11eb-9cd4-7f5810b9c870.png)
https://drive.google.com/file/d/1HIRNlw9y-kiO5YNqb3GS9QKRScSQMItB/view?usp=sharing - replay

**Comment by Smittytron** [comment]
Duplicate #9416
