### ISSUE TITLE
Possibilty to make an android port

### ISSUE THREAD

**Issue by strikersix23** [OpenRA/OpenRA#19206]
I don't know if this is considered a duplicate as I am suggested new technologies that have popped up since the android port was thought of.
Mono c# can be used and visual studio 2019 has .dotnet development target for android

As for the sdl2 that's done and I believe in the ndk

For the OpenGL issue there is gl4es which supports more than android

Links

https://github.com/ptitSeb/gl4es

https://docs.microsoft.com/en-us/xamarin/android/get-started/hello-android/hello-android-quickstart?pivots=windows
https://www.mono-project.com/docs/about-mono/

https://discourse.libsdl.org/t/building-sdl2-0-10-in-android-studio-3-4-2-in-windows-10/26481

**Comment by Mailaender** [comment]
Duplicate of
https://github.com/OpenRA/OpenRA/issues/10604
https://github.com/OpenRA/OpenRA/issues/8217

**Comment by pchote** [comment]
While this may now be technically feasible(?), the major problem remains that all of the in-game interfaces and experiences are designed around having both a mouse and a keyboard. Redesigning the game and gameplay around a small-physical-size touchscreen is beyond the scope of what we could reasonably consider doing as part of the core project. This would also create a huge additional support burden dealing with the wide range of Android hardware, most of which won't be powerful enough to run the game well.

If someone were to create an OpenRA android port and demonstrate it works well then we might consider integrating it, but I am fairly confident that this is not something that will be lead from within the core project.

**Comment by tarek369** [comment]
https://github.com/tarek369/OpenRA for android

**Comment by Mailaender** [comment]
There is also https://github.com/bbit-git/OpenRA
