### ISSUE TITLE
openra support slopes ????

### ISSUE THREAD

**Issue by annopnod** [OpenRA/OpenRA#19256]
openra support slopes ????
see:
https://www.youtube.com/watch?v=pylabbamDgQ

**Comment by penev92** [comment]
Yes, OpenRA does support slopes. There are a TS and a RA2 mod being worked on, along with a whole bunch of spinoffs. What is the question here?

**Comment by Leo512bit** [comment]
> Yes, OpenRA does support slopes. There are a TS and a RA2 mod being worked on, along with a whole bunch of spinoffs. What is the question here?

I think @annopnod is asking if the Ra mod does.


> openra support slopes ????
> see:
> https://www.youtube.com/watch?v=pylabbamDgQ

Yes openra does but not the Ra mod (for modmaps anyways)

**Comment by abcdefg30** [comment]
Indeed, mods using the isometric terrain can use slopes.
