### ISSUE TITLE
The late game lags caused by Log.cs

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#19260]
Found by @CastleJing

Castle found that logs of OpenRA updates itself along with the game so he worried there may be some lags related to log's frequently I/O to file system.
Meanwhile, at line 71 in Log.cs
```
Writer = TextWriter.Synchronized(writer)
```
which looks very suspicion, but Microsoft document gives little about the cost of this synchronized writer.

During my test, after delete `AddChannel` and `Write`, at late game the performance improved from 27-34 FPS to 32-39 FPS (which means 18%~14%) with 400+ actors in world, in this case I guess we need to look into it.

Possible fixes:
1. Give an option on player to output log or not for better game performance
2. Reduce I/O cost. Like give a buffer for write content.
3. Both above.

**Comment by teinarss** [comment]
Related to #19029
