### ISSUE TITLE
Aircraft Idle Speed Unaffected by SpeedMultiplier or Pausing

### ISSUE THREAD

**Issue by darkademic** [OpenRA/OpenRA#19278]
The SpeedMultiplier trait has no effect on aircraft idle speed, which means it's possible for aircraft to move faster while idling than when flying if they're affected by a condition intended to reduce aircraft speed.

Turn speed is also not affected.

If you pause the Aircraft trait while the aircraft is idling, this also has no effect.

Came across this as I was attempting to make a weapon that freezes aircraft in place, but it only worked when the aircraft wasn't idling.

The FlyIdle activity class references the speeds directly from the Aircraft Info without applying any modifiers as in the Aircraft class itself.

Ideally turn speeds should be affected too, otherwise applying a zero speed multiplier causes an idling aircraft to just spin in place.

**Comment by pchote** [comment]
Does pausing the `Aircraft` trait not already do what you want? This is how it works for `Mobile`, at least.

**Comment by darkademic** [comment]
> 
> 
> Does pausing the `Aircraft` trait not already do what you want? This is how it works for `Mobile`, at least.

Ah, nah, should've mentioned that as part of the issue, pausing Aircraft also has no effect if the aircraft is idling.
