### ISSUE TITLE
Script error in situation-critical: playtest-20210131

### ISSUE THREAD

**Issue by Randall-Glass** [OpenRA/OpenRA#19271]
Script error in situation-critical: playtest-20210131

Post Mon Mar 22, 2021 7:46 am
Playing around with situation-critical in playtest-20210131.

Don't know if this script error is serious enough to be considered.

Modified map.yaml so I could see the whole map.

Got the scientist into the bio-research center.

Used the missile subs to destroy missile silos, and the bio-research center.

Sams were left intact.

Not one Sam site was destroyed.

And yet the game said that all objectives had been met.

Including destroying the sam sites.

What gives?

Played again it with no mods

[Here is the replay](https://drive.google.com/file/d/1L8KdsPvAYo6XsYnDDONDHQd2FxOoLShw/view?usp=sharing).
.

Got the scientist into the bio-research center.

With the missile subs on attack anything, the subs took out the
bio-research center.

And there were some sam sites left.

**Comment by Smittytron** [comment]
Msubs have 14 range in the original and 20 in OpenRA (formerly 16). The missile silos are 15 cells away from the water.

We could either have a campaign specific override of 14 cell range for msubs, or I could change up the script to make samsite killing a secondary objective.
