### ISSUE TITLE
Screensaver with continuous skirmish bots playing against each other

### ISSUE THREAD

**Issue by stitch** [OpenRA/OpenRA#19272]
## Motivation

I have fond memories of Red Alert, but don't have the time to play it. To still enjoy the love, i think it would be more than awesome to have a screensaver version of OpenRA. This would simply perform skirmish matches of bots against each other, with some randomization to make every battle go down differently. With or without sound it would be totally enjoyable to see the constant movements of tanks and infantry. I used to just let the engine run in the game and see what the computer made of it, back in the days.

## Proposed solution

Have OpenAI run as a screensaver with bot battles. Use a screensaver component and somehow wrap the OpenRA libraries in it so it runs.

## Side effects

People may find odd behavior in the bots playing the game. More people be able to run the game in the office and such, so possibly more adaptation.

## Alternatives

Just starting the game and let it do it's thing. It's not the same, because it requires manual interaction.

**Comment by pchote** [comment]
Consistent cross-platform support is an important goal for OpenRA. Screensavers are very os-specific, so this isn't going to be feasible to implement as a core project feature sorry.

This doesn't mean that somebody else couldn't create an external project to do this, though!
