### ISSUE TITLE
Add "Not use map settings" option in skirmish and multiplayer

### ISSUE THREAD

**Issue by yaaaaa** [OpenRA/OpenRA#19274]
If chekpoint is Acive, then game not load unit changes, scripts from map and use default balance.
It let us to play any custom or compagin maps in skirmish and multiplayer and have default balanse.
And prebeat that situations, then somebody changed in map some parameters, request to play on it, and win, using own changes.

**Comment by pchote** [comment]
This is not technically feasible. Maps with custom rules often (and campaign missions *always*) don't define the map-level features needed by the default ruleset, such as spawn points. Attempting to play these maps with the map settings disabled will simply crash the game.
