### ISSUE TITLE
'zombie' actor in map editor that does not get removed on deletion

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#19287]
![undeleteable](https://user-images.githubusercontent.com/48881353/112681567-fa85de00-8e7f-11eb-92d8-a49d938797a3.gif)
saving the map as loose files and then inspecting map.yaml shows that indeed the actor has got deleted, it just resisted being cleared in the editor for some reason. Reload the map showed no traces of it.

**Comment by PunkPun** [comment]
Regression from #16772

The issue is that `EditorActorPreview` overrides GetHashCode and hashes its ID. What this means is that when the actor is stored in `SpatiallyPartitioned` dictionary and its name is changed, the actor becomes nolonger accessible
