### ISSUE TITLE
Dune 2020 music installer installs WAITGAME.AUD as WAITGAME.A

### ISSUE THREAD

**Issue by zaidan** [OpenRA/OpenRA#19299]
OS: `Arch Linux, 5.11.10-arch1-1`
Arch Linux openra package version: `20210321-1`

## Issue Summary
Dune 2020 music installer installs `WAITGAME.AUD` as `WAITGAME.A`. 
While all other files have been installed correctly, it is still possible to install the music again.
It is not possible to complete the music installation without manual workaround.
The `Music` folder on the CD contains the following files:

```
ambush.aud
arakatak.aud
atregain.aud
entordos.aud
fightpwr.aud
fremen.aud
hark_bat.aud
landsand.aud
options.aud
plotting.aud
risehark.aud
robotix.aud
score.aud
soldappr.aud
spicesct.aud
undercon.aud
waitgame.aud  
```

## Reproduction
Install Music with Dune 2000 CD

See the log in #14289 - it contains the unexpected rename:
https://github.com/OpenRA/OpenRA/issues/14289#issuecomment-341905666

## Workaround

* Rename `WAITGAME.A` to `WAITGAME.AUD` in `~/.config/openra/Content/d2k/v2/Music`

Music is shown as installed

## Expected behavior
Installer should install `WAITGAME.AUD` as `WAITGAME.AUD` to complete installation.

**Comment by pchote** [comment]
Thanks for the report!

This was actually already fixed in #19176, but I made a mistake when backporting the fix to the release branch (only picked the second of two commits 😓). The fix works correctly on the development branch and will come out in the next playtests hopefully not too far in the future.
