### ISSUE TITLE
`Lockhandicap` has no effect on UI

### ISSUE THREAD

**Issue by Leo512bit** [OpenRA/OpenRA#19303]
## Reproduction

Add `Lockhandicap: true` to a player in `map.yaml`.

## Expected behavior

The handicap dropdown menu should be disabled

**Comment by pchote** [comment]
Confirmed:
https://github.com/OpenRA/OpenRA/blob/75a3bb4f0bff6c518247cc52eebe25ae61eaaac1/OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyUtils.cs#L588
