### ISSUE TITLE
`Handicap` trait gets treated as the `team` trait 

### ISSUE THREAD

**Issue by Leo512bit** [OpenRA/OpenRA#19304]
## Issue Summary
The `Handicap` trait gets treated as the `team` trait.

## Reproduction

This is the code I used
```
Players:
	PlayerReference@Neutral:
		Name: Neutral
		OwnsWorld: True
		NonCombatant: True
		Faction: england
	PlayerReference@Creeps:
		Name: Creeps
		NonCombatant: True
		Faction: england
		Enemies: Multi0, Multi1, Multi2
	PlayerReference@Multi0:
		Name: Multi0
		Playable: True
		Faction: Random
		Enemies: Creeps
	PlayerReference@Multi1:
		Name: Multi1
		Playable: True
		Faction: Random
		Enemies: Creeps
		LockHandicap: True
		Handicap: 95
	PlayerReference@Multi2:
		Name: Multi2
		Playable: True
		Faction: Random
		Enemies: Creeps

```
The same code was used for #19303
## Screenshots / Screen recordings / Replays

![ohbug](https://user-images.githubusercontent.com/64435704/112939802-f5739980-90e0-11eb-8b5d-01adbb96f94f.png)

**Comment by pchote** [comment]
Confirmed:
https://github.com/OpenRA/OpenRA/blob/75a3bb4f0bff6c518247cc52eebe25ae61eaaac1/OpenRA.Game/Server/Server.cs#L97-L98
