### ISSUE TITLE
[Linux] does not compile on Debian stable i386

### ISSUE THREAD

**Issue by senneschall** [OpenRA/OpenRA#19309]
## Issue Summary
Unfortunately you don't provide a binary for those pre-historic non-amd64 computers like I have one, so I went ahead and tried to compile it on i386.
INSTALL.md says that you should be fine with mono >= 5.18. Debian 10 has 5.18 in the repository, but it fails:

>$ make TARGETPLATFORM=unix-generic
>OpenRA requires the 'msbuild -verbosity:m -nologo' tool provided by Mono >= 5.18.
>make: *** [Makefile:87: all] error 1

That does not make sense, the dependency is fulfilled:

> $ mono --version
> Mono JIT compiler version 5.18.0.240 (Debian 5.18.0.240+dfsg-3 Wed Apr 17 18:22:39 UTC 2019)
> Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
>        TLS:           __thread
>        SIGSEGV:       altstack
>        Notifications: epoll
>        Architecture:  x86
>        Disabled:      none
>        Misc:          softdebug 
>        Interpreter:   yes
>        LLVM:          supported, not enabled.
>        Suspend:       preemptive
>        GC:            sgen (concurrent by default)

## Reproduction

1. install Debian 10 i386
2. install all dependencies (mono-complete, libsdl2*, liblua5.1*, libopenal1*, libfreetype6*
3. download the latest source code `OpenRA-release-20210321.tar.gz`
4. make TARGETPLATFORM=unix-generic

**Comment by pchote** [comment]
Debian packages the compiler but not the `msbuild` tool, which is the .NET equivalent of packaging GCC but not `make`. Adding the upstream repository and installing the `mono-devel` package should resolve this.

**Comment by senneschall** [comment]
Indeed, that solves the issue. Thanks!
