### ISSUE TITLE
tooltip over shrouded civilian building shows caption tree.

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#19313]
release latest stable.

trivial bug.

civilian building has caption 'civilian building' when terrain is explored. once fog covers the building, hovering the building shows the caption 'tree'.

**Comment by abcdefg30** [comment]
This is probably some overlap issue with a nearby tree. Something similar can be seen with a few flame towers and trees on the Exodus map.

**Comment by Mailaender** [comment]
![image](https://user-images.githubusercontent.com/756669/125210597-17181b80-e2a1-11eb-961c-5d02d7d75df6.png)

Can't reproduce.
