### ISSUE TITLE
[Feature request] Random map generator

### ISSUE THREAD

**Issue by Shkarlatov** [OpenRA/OpenRA#19330]
I propose to implement a random generation of maps with variable settings. These changes will increase the replayability of the game.

- choice of map size (small, medium, large, huge)
- selection of the number of players \ available slots (or always use the maximum number)
- selection of the amount of resources (percentage of the size of the map)
- selection of the amount of water (rivers, lakes, sea)
- the size of the territory not occupied by water and mountains (any impassable things)

In the game itself, it should be like this:
add the "generated maps" tab to the map selection menu. 
On this tab there will be map settings, a "generate" button and a list of previously generated maps with a preview.

Maps will be saved in "maps \ {mod} \ generated"

When playing a network game, the card must be loaded from the host (server) (#17023)

Or add this functionality to the map editor.

I saw #2806. There might be problems with biomes, but in this proposal it is only necessary to join the tiles together. Maybe this stuff will help [The Constrained Tile Placement Algorithm behind Generate Worlds](https://ijdykeman.github.io/procedural_generation/2019/11/08/generate-worlds-algorithm.html) or [WaveFunctionCollapse](https://github.com/mxgmn/WaveFunctionCollapse)

**Comment by pchote** [comment]
The problem is that the tilesets in the first 3 games were not designed for any kind of automation, and are very non-symmetric (you might have equivalent cliff tiles for 3 facings but not the 4th). This makes it very difficult to do any kind of generators.

**Comment by Dzierzan** [comment]
I also think this is not feasible. RA/TD tilesets are not perfectly symmetrical to create easy masks. And I don't see anybody here to who would spend weeks or perhaps months to create such feature.

OpenHV or OpenSA mods could have that in theory achieve that, as their tilesets are dead simple, yet even here I don't see it happening either.

**Comment by Shkarlatov** [comment]
But it is possible to manually mark tiles for side compatibility. Something similar is already in the templates (for example  ra/tilesets/desert.yaml)

There will be problems with the fact that the templates are of different sizes. Most likely the task will be NP-completeness (as Knapsack problem).

**Comment by Shkarlatov** [comment]
You were right. the problem simply cannot be solved in a reasonable time.
2 biggest problems:
- tiles of different sizes
- tiles of partially different sides 

Example:
![sh36](https://user-images.githubusercontent.com/1247023/114826072-1540d800-9dd8-11eb-9bec-c47b0f3cee3d.png) - one tile 

<table>
<tr>
    <td>Clear</td>
</tr>
</table>

![sh24](https://user-images.githubusercontent.com/1247023/114826119-25f14e00-9dd8-11eb-9e39-7e38e3ba2dad.png) - template of 9 tiles

<table>
<tr>
    <td>Rock</td>
    <td>River</td>
     <td>Rock</td>
</tr>
<tr>
    <td>River</td>
    <td>River</td>
   <td>Clear</td>
</tr>
<tr>
    <td>River</td>
    <td>Water</td>
   <td>River</td>
</tr>
</table>

It is impossible to mark up manually, because the tiles are very large and it is problematic to take into account all partial cases.
