### ISSUE TITLE
With "move jumpy-ness" fix, speed of 128 results in faster movement than it should

### ISSUE THREAD

**Issue by darkademic** [OpenRA/OpenRA#19347]
If a ground unit is given a speed of 128, with a locomotor that travels at 100% speed on clear, it will travel much faster than it should (racing ahead of otherwise identical units with speeds of 127 and 129).

If 100% speed on clear is used, 128 would be the new speed for the APC and Phase Tank in the RA mod.

Pertains to: https://github.com/OpenRA/OpenRA/pull/19220

**Comment by pchote** [comment]
I've confirmed the regression but haven't looked into why it happens.
