### ISSUE TITLE
Unhardcode "moveflsh"

### ISSUE THREAD

**Issue by Dzierzan** [OpenRA/OpenRA#19346]
OpenRA requires `moveflsh` to work. While it's a cool thingy, does it really have to be hardcoded? It should be an optional thing to have.

**Comment by pchote** [comment]
Sounds reasonable to me.

We could perhaps introduce a new `OrderEffects` world trait that defines the move flash details and also whether the target flashes use a classic-style color overlay or a TS-style multiplicative brightening.

**Comment by dragunoff** [comment]
> 
> We could perhaps introduce a new `OrderEffects` world trait that defines the move flash details and also whether the target flashes use a classic-style color overlay or a TS-style multiplicative brightening.

Or whether the target sprite should flash at all because some games may want  to do an AoE or StarCraft style blinking circle/rectangle.
