### ISSUE TITLE
doc/INSTALL: mention `dotnet msbuild` in case `msbuild` is not there

### ISSUE THREAD

**Issue by Artoria2e5** [OpenRA/OpenRA#19352]
## Motivation
It appears that some (read: mine) installations of .NET Core, specifically the `5.0.100-preview.6.20318.15` I got for PowerShell building on macOS, do not ship a `msbuild` command but instead puts it inside `dotnet msbuild`.

## Proposed solution
`INSTALL.md` should mention the possibility and provide a workaround, namely putting a shell script wrapper in PATH. The wrapper should be called `msbuild`, put in PATH, and have only two lines:

```
#!/bin/sh
exec dotnet msbuild "$@"
```

## Side effects
None.

## Alternatives
The makefile can be changed to call `dotnet msbuild`, but I am not sure about the consequences. It's supposed to always be there for .NET 5, right?

**Comment by pchote** [comment]
`msbuild` should only be used when compiling under Mono. When using .NET5 it should be using `dotnet build` (assuming you're on the development branch, the previous release requires mono).

**Comment by Artoria2e5** [comment]
The makefile appears to be still calling `msbuild`. I think that's an oversight?

**Comment by Artoria2e5** [comment]
Odd, for some reason it's not taking the RUNTIME=dotnet branch. No problem on your end from a quick read of the Makefile; gonna close the issue.
