### ISSUE TITLE
Infantry overlap

### ISSUE THREAD

**Issue by Leo512bit** [OpenRA/OpenRA#19356]
## Issue Summary

2 infantry units overlapped

## Reproduction

Don't remember

## Expected behavior

Should not overlap.

## Screenshots / Screen recordings / Replays
![20210415125747_1](https://user-images.githubusercontent.com/64435704/115163189-88f31700-a05c-11eb-9c3f-fd39a1b6ac49.jpg)

**Comment by abcdefg30** [comment]
Were those units overlapping stationary or only while moving? If the latter, this will likely not be feasible to address. If the former, a replay would be good (as a reproduction case).

**Comment by Leo512bit** [comment]
They were moving I'm not sure if I have the replay when I have time I'll try to find it

**Comment by abcdefg30** [comment]
> They were moving

Closing as wontfix (for now) then since there's not much we can feasibly do about it.
