### ISSUE TITLE
^Plane: with Aircraft: with IdleBehavior: ReturnToBase hangs Midair when last Airfield actor gets sold

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#19366]
^ exactly what it says on the Tin can.
Also sorry if its duplicate.

**Comment by ThomasChr** [comment]
This is a duplicate for https://github.com/OpenRA/OpenRA/issues/20373
As the new one has nice pictures and a few comments we should close this one here.

**Comment by PunkPun** [comment]
Closing as reverse duplicate of #20373
