### ISSUE TITLE
FreeActor: AllowRespawn Wont work

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#19378]
## Issue Summary

In my mod Apolyton I have set the temple of nod and the Adv.coms to give a free "renegade" unit upon placement, the unit will attack wonder by its own and its supposed to be re-spawned upon death. 
Ive tried using conditions and without them, but wont re-spawn it after its death.

## Reproduction

```
TMPL:
	FreeActor:
		Actor: renegade
		SpawnOffset: 1,2
		AllowRespawn: True
		EditorFreeActorDisplayOrder: 4
		RequiresCondition: !disabled && !powerdown && !build-incomplete && !being-demolished && !renegadeout

ANY_UNIT_WILL_DO:
	GrantCondition@RenegadeOut:
		Condition: renegadeout
```

## Expected behavior

FreeActor: AllowRespawn should work.

## NOTE
I really like the AllowRespawn on the trait and it can come handy in many situations, who ever came up with the idea thank you!

**Comment by MlemandPurrs** [comment]
GrantCondition@RenegadeOut: should be on the TMPL itself, be a GrantConditionOnPrerequisite@ instead that is pointing to Renegade's unit id, and Renegade should provide ProvidesPrerequisite@unitname: to be used for it.

**Comment by KOYK** [comment]
oh damn, I forgot about that lol, thank you for reminding me.

**Comment by KOYK** [comment]
Hmm I did
```
	GrantCondition@RenegadeOut:
		Condition: renegadeout
	FreeActor:
		Actor: renegade
		SpawnOffset: 1,2
		AllowRespawn: True
		EditorFreeActorDisplayOrder: 4
		RequiresCondition: renegadeout
```

Just to test it out and still did not work. Unless if i forgot something else **again**. I think this is a legit bug.

**Comment by reaperrr** [comment]
I think you're misunderstanding how `AllowRespawn` works.

All it does is to allow respawns when `FreeActor` gets disabled and then re-enabled.

In your example above, it never gets disabled since `GrantCondition` itself is always enabled, so there cannot be a respawn after the initial free actor.

**Comment by KOYK** [comment]
Ahh that makes sense. 
Thank you! @reaperrr
