### ISSUE TITLE
Add soviet variation of Hind, when soviets capture helipad or have double tech

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#19406]
## Motivation

It will make more sense and look good

## Proposed solution

Allow for soviets to use the Hind sprite (SHP) file instead of blackhawk, when they capture a helipad or have double tech

## Side effects

None

**Comment by KOYK** [comment]
Maybe assign this to me, I can do it this week.

**Comment by Leo512bit** [comment]
Thats a good idea!

**Comment by pchote** [comment]
I wouldn't support this. It just adds extra maintenance hassle without any real in-game benefit. Adding assets simply because they are otherwise unused is not a good enough justification by itself.

**Comment by KOYK** [comment]
> I wouldn't support this. It just adds extra maintenance hassle without any real in-game benefit. Adding assets simply because they are otherwise unused is not a good enough justification by itself.

You misinterpret me, probably because of my english, and therefor how I expressed my idea.

This is purely aesthetic, and not a case of adding unused assets, here are the reasons in more detail:

1: If we are going to have compatibility with the art assets from the remasters, we don't have a high definition art of the blackhawk unit, so we will return to the hind sprite.

2: Dune mod already has this setup with its art style, by replacing the art for the same units, based on faction. 
maintenance wont be a problem more than it is for the dune mod.

3: This change is also about lore, we should see this as a continuation\upgrade of the blackhawk PR.

**Comment by abcdefg30** [comment]
Closed via https://github.com/OpenRA/OpenRA/pull/19408#issuecomment-841190851.
