### ISSUE TITLE
Turn OpenRA into a Libretro Core for RetroArch and RetroPie 

### ISSUE THREAD

**Issue by Ryan14411** [OpenRA/OpenRA#19410]
When you choose to use the libretro API, your program gets turned into a single library file (called a ‘libretro core’). A frontend that supports the libretro API can then load that library file and run the app. The frontend’s responsibility is to provide all the implementation-specific details, such as video/audio/input drivers. The libretro core’s responsibility is solely to provide the main program. You therefore don’t have to worry about writing different video drivers for Direct3D, OpenGL or worrying about catering to all possible input APIs/sound APIs/supporting all known joypads/etc. This is none of your concern at the libretro core implementation level.

RetroArch also has online play and crossplay features and works on almost every android device, smart tvs, consoles plus many other devices and could bring lots of players to OpenRA

**Comment by pchote** [comment]
Rewriting all of the input/audio/rendering code to use a new API would take considerable effort and is out of scope for the core project, but I would be happy to provide tips for anyone who was interested in developing this as an external port of OpenRA.

This isn't an actionable issue, so in the spirit of the ongoing issues cleanup effort I will close this immediately.

**Comment by Ryan14411** [comment]
Thankyou if i can find someone interested i will be in touch thanks

**Comment by Ryan14411** [comment]
its my believe that you will not have to rewrite much if you read my first comment? i am wrong?
