### ISSUE TITLE
CD'S (ISOS) aren't detected

### ISSUE THREAD

**Issue by CamJRP** [OpenRA/OpenRA#19428]
## Expected behavior: Properly detection of red alert isos

More information:
OS: Linux Mint 20.1
Type of packaging for OpenRa: Flatpak.
Where are you mounting the Isos: /media/user/CD1or2/

**Comment by pchote** [comment]
Can you please file an issue at https://github.com/flathub/net.openra.OpenRA?

This is not something that we are able to fix here.

**Comment by CamJRP** [comment]
Ok i will, thanks for the answer

**Comment by Mailaender** [comment]
https://github.com/flathub/net.openra.OpenRA/issues/15
