### ISSUE TITLE
Dune 2000 always show Game Music Requires Disc

### ISSUE THREAD

**Issue by ZhiZe-ZG** [OpenRA/OpenRA#19421]
## Issue Summary

Even I installed  the music file from disc image.  It will show "Requires Disc" in Manage Content  (after "Game Music").
Then I loaded disc image again, detected again, installed again and restart the game.
The "Requires Disc" still there.

DESCRIPTION

## Reproduction

STEPS TO REPRODUCE THE ISSUE

## Expected behavior

EXPECTED BEHAVIOR

**Comment by pchote** [comment]
Thanks for the report. Closing as a duplicate of #19299, which has already been fixed for the next release.
