### ISSUE TITLE
D2kBuilding concrete placement ignore Min/MaxColor of the tile.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#19435]
In RV the terrain is set up to use Min/MaxColor for the radar, TerrainTypes mostly has 000000 as the color. I noticed while playing on the Dune map on RV, the concrete area was showing up as Black on the radar. I checked on the map editor just to be sure and the preplaced concrete on the map uses the Min/MaxColor porperly.

Ingame:
![Concrete Ingame](https://user-images.githubusercontent.com/7933210/120214242-e02ffe00-c23c-11eb-998e-744b5daa6ed7.png)
In the Editor (it is close to Rock color but not the same, you may need to look closely):
![Concrete Editor](https://user-images.githubusercontent.com/7933210/120214225-db6b4a00-c23c-11eb-81a7-a99c27e095c1.png)

Here is the Terrain definition for Concrete:
```
	Template@2500:
		Categories: Concrete
		Id: 2500
		PickAny: True
		Images: d2kconc01.des, d2kconc01a.des, d2kconc01b.des
		Size: 1, 1
		Tiles:
			0: Road
				MinColor: CE8C42
				MaxColor: CE8C42
```

**Comment by anvilvapre** [comment]
Possibly related to `Min|MaxHeightColorBrightness`?

After that a `left` and `right` color value is selected between `MinColor` and `MaxColor` a scale is applied to that color if `terrainInfo.MinHeightColorBrightness` or `terrainInfo.MaxHeightColorBrightness` does not equal `1.0f`.

The scale is based on
`var scale = float2.Lerp(terrainInfo.MinHeightColorBrightness, terrainInfo.MaxHeightColorBrightness, Height[uv] * 1f / Grid.MaximumTerrainHeight);`

Could this be the cause, that the scale is near zero?

**Comment by pchote** [comment]
The custom concrete layer doesn't actually use the terrain template definitions, so the minimap colours are based on the terrain types which as explained are defined to be black.
