### ISSUE TITLE
SpriteRenderer SetRenderStateForSprite  has a probability of getting the wrong sheetindex

### ISSUE THREAD

**Issue by MisakiQiQi** [OpenRA/OpenRA#19438]
## Issue Summary

The class SpriteRenderer‘s method    SetRenderStateForSprite  can get wrong secondarySheetIndex，will cause shader get wrong depth 
texture，will cause some bug like below image。

![23423](https://user-images.githubusercontent.com/84283714/120920316-bb320400-c6f0-11eb-8edd-b76e23fcce1b.png)

## Reproduction

add a litte code  to  function  SetRenderStateForSprite at last line  can vertiy this  bug like below

`	if (sheetIndex == secondarySheetIndex && ss != null && ss.SecondarySheet!=s.Sheet)
			{
				Console.WriteLine("Have Problem????");
			}
`

this bug will trigger when sheet and secondarysheet all cache miss, then secondarysheetindex will  error
## Expected behavior

when  secondarysheet!=null and sheet!=secondarySheet   ,   sheetindex need not equal to secondarySheetIndex

## Screenshots / Screen recordings / Replays

if  change the shader( combined.frag)  frag_color to  output  vTexSampler.t, ,will get below result.

so  vTexSampler.t have some error

![bbb](https://user-images.githubusercontent.com/84283714/120920585-16b0c180-c6f2-11eb-9085-74a879ffac9e.png)

**Comment by dnqbob** [comment]
Notice it in RV SP sometimes.

**Comment by pchote** [comment]
Fixed by #19563.
