### ISSUE TITLE
Reimplement barrels as subcell actors

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#19432]
Initial idea here: https://forum.openra.net/viewtopic.php?p=312986#p312986

> why aren't barrels considered infantry?
> if they were, then infantry could pass through them at their own risk and tanks can run over & crush them at their own risk.
> this would increase the risk/reward of navigating near barrels since unit pathing would direct them through the barrels instead of around.

**Comment by netnazgul** [comment]
I assume this might have a lot of implications with regards to singleplayer missions. With this in mind, this implementation should be toggle-able through YAML, default off.

A cheaper solution might be to implement an actual infantry-type actor with Speed: 0, no weapons, ExplodeOnDeath and having a barrel sprite. I guess this can already be modded into a map.

**Comment by abcdefg30** [comment]
> I assume this might have a lot of implications with regards to singleplayer missions.

I don't think any map relies on barrels to block passages, so unless I'm missing something it shouldn't be a problem.

**Comment by abcdefg30** [comment]
Closing for now since this would require a re-write of how the building trait works. In the meantime the workaround mentioned in the second comment can be used.
