### ISSUE TITLE
D2K Add smoke effects on health lower than 50%

### ISSUE THREAD

**Issue by oldnaari** [OpenRA/OpenRA#19454]
REQUEST MOTIVATION

In the original Dune 2000 when vehicles are damaged they start to move slower. This is noticeable in the campaign missions because it makes it harder to rush into the enemy territory bypassing their defenses.

PROPOSED SOLUTION

The system should work as follows:
* When vehicle health is lower than 50%, it starts emitting smoke particles.
* The smoke effect ends after some time
* The effect should resume in case of any negative health update (excludes repairing).
* When below 50% health, movement speed is reduced (regardless of whether the smoke animation is playing)

**Comment by oldnaari** [comment]
I did some 30 measurements and here are some insights on the numbers. Please note that 30 appeared a very small number for this feature, so please take everything with a little grain of salt.

* The particle effect duration is a random number **[15, 40)**. Additionally, it seems to be a multiple of 5.
* Each unit seems to have its own speed for the damaged state. We can do some rough approximation using **0.75** as the speed factor for all units.

If someone wills to dig into the data, you can find the .csv here https://github.com/oldnaari/D2K-Damaged-units-data

**Comment by Leo512bit** [comment]
It should be easy to implement the unit slowing when its damaged just with a `GrantConditionOnDamageState`  and with the `SpeedMultiplier` traits if I have time I might do a PR but I'm not sure about the smoke.

**Comment by Leo512bit** [comment]
The speed part is done. #19468

**Comment by abcdefg30** [comment]
Would it be possible to do the smoke in a similar fashion to the smoke on damaged aircraft in RA? (E.g. https://github.com/OpenRA/OpenRA/blob/fe129956bb1b3f7e3231c11f306f7387d36f0630/mods/ra/rules/aircraft.yaml#L34-L40)

**Comment by Leo512bit** [comment]
I was thinking of doing like the husk fires.
https://github.com/OpenRA/OpenRA/blob/fe129956bb1b3f7e3231c11f306f7387d36f0630/mods/ra/rules/defaults.yaml#L996-L999

**Comment by abcdefg30** [comment]
Re-opening for the fire/damage overlay.

**Comment by VonNah** [comment]
Afaik openra doesn't support the original d2k vehicle/building smoke animation. 

It needs **"Substractive alpha"** as a new `BlendMode` and maybe a "Rise up(smoke)" feature.

**3747 - 3754** are the mod's DATA.R8 asset browser frames you need. 

![ex_smoke3](https://user-images.githubusercontent.com/65423234/123655507-91b35680-d81e-11eb-9355-454318cc3bf7.PNG)

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/pull/19491 though it seems our substractive is not the same as Dune 2000 substractive or the palette is wrong. It could be using an embedded one like shroud. Where did you get that cool editor?

**Comment by VonNah** [comment]
You can download it from here: https://forum.dune2k.com/topic/29391-d2keditor-20-released/ (needs a forum account)

**Comment by oldnaari** [comment]
I want to note that in the original game, the slowness effect doesn't affect harvesters. It may be important for balance

**Comment by abcdefg30** [comment]
> I want to note that in the original game, the slowness effect doesn't affect harvesters. It may be important for balance

I filed #19720 to account for this.
