### ISSUE TITLE
Allow Map Editor to load > 64 Spawn Points

### ISSUE THREAD

**Issue by 0xA1B2** [OpenRA/OpenRA#19478]
Hello,

if by accident a map is created with > 64 spawn points, the map cannot be load anymore later on, thus all work is lost. There is no warning on saving that the map has > 64 spawn points.

Please allow the map editor to load maps > 64 spawn points so the excess spawn points can be deleted. Thanks.

Pummelchen.

**Comment by pchote** [comment]
Related: #18781.

**Comment by Leo512bit** [comment]
You can just open the map file and modify `map.yaml`
