### ISSUE TITLE
[bleed] "Preferred color" rectangle thumbnail displays value from settings.yaml, not actual ingame color

### ISSUE THREAD

**Issue by netnazgul** [OpenRA/OpenRA#19471]
It is possible to supply "settings.yaml" with any value for color picker. Current color picker reimplementation modifies this value for the game, but the invalid value is still displayed in "Preferred color" in Settings. However the value is displayed correctly in game lobby.
![image](https://user-images.githubusercontent.com/1614714/123553054-e228a680-d781-11eb-8cb1-8b49dba2781e.png)
![image](https://user-images.githubusercontent.com/1614714/123553070-f2d91c80-d781-11eb-8dea-e88f9b169e31.png)

Also, when pitch black is added, it is replaced by gray in Color picker example display, but pink is actually selected after Color picker is closed.
![image](https://user-images.githubusercontent.com/1614714/123553107-18febc80-d782-11eb-8a90-775af2c3c9d9.png)

**Comment by Leo512bit** [comment]
I knew that this new color picker was bad.....
