### ISSUE TITLE
Muti-Hitshape with armor will result in unit take 100% damage

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#19485]
## Issue Summary
If we set more than one Hitshape (with valid armor), then all Hitshape receive 100% damage

## Reproduction

Trait:
```
	### hitshape1
	HitShape@front:
		TargetableOffsets: 550,0,0, 550,-300,0,  550,300,0
		ArmorTypes: ArmorA
		Type: Rectangle
			VerticalTopOffset: 532
			VerticalBottomOffset: 0
			TopLeft: -366, -612
			BottomRight: 366, -312

	### hitshape2
	HitShape@other:
		TargetableOffsets: -550,0,0, -550,-300,0, -550,300,0, 0,0,0, 0,-300,0, 0,300,0
		ArmorTypes: ArmorB
		Type: Rectangle
			VerticalTopOffset: 512
			VerticalBottomOffset: 0
			TopLeft: -366, -312
			BottomRight: 366, 612

```
Weapon
```
	HitShape@Dam: SpreadDamage
		Damage: 5500
		Spread: 0c20
		Falloff: 100, 100, 0
		Versus:
			ArmorA: 1
			ArmorB: 1

```

Let actor1 has hitshpe1, 
actor2 has hitshpe2, 
actor3 has hitshape1 and hitshape2, 
then use weapon attack these actors. If the bug goes normally, you will find actor3 lose significant much more HP than actor1 and actor2. 

We are going to make directional armor by using hitshapes and this bug confuses us.

**Comment by pchote** [comment]
I think this might be intentional, but @reaperrr is the person to ask.

You can either make sure you have multiple non-overlapping shapes, or if you have a specific weakpoint that you want to take 150% damage you can have that overlap with its own armor type that takes 50% damage (added to the normal 100% from the main hitshape).

**Comment by dnqbob** [comment]
> overlap with its own armor type that takes 50% damage (added to the normal 100% from the main hitshape).

On Milk's finding, no matter how many hitshapes nor where they are (they can pilled up with each other) , if we have more than 2 hitshape, then the damage is 100%. 

Add: I don't see code I found support this phenomenon when I try to solve this bug, strange.

**Comment by dnqbob** [comment]
Ah dude sorry
It is a warhead doesn't belong to OpenRA main stream cause this.
