### ISSUE TITLE
Veinholes are not rendered

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#19511]
![image](https://user-images.githubusercontent.com/756669/125447339-c8fe9d9a-e37d-4cc0-94c9-61c80a7146c4.png)

Map is Sunstroke.

**Comment by pchote** [comment]
Before #19090 veinholes were imported with the wrong location (due to originally having the wrong footprint definition), and IIRC caused exactly this. The default TS maps were fixed by reimporting them, but Sunstroke wasn't updated because I don't have the original file.

**Comment by Mailaender** [comment]
https://ppmforums.com/topic-15379/sunstroke-2/ is where I got it from.
