### ISSUE TITLE
Crash when restarting the game after changing between fullscreen and windowed mode

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#19518]
I consistently get the following when changing from `Windowed` mode to `Fullscreen` or back and then restarting from the settings menu using "Restart Now":
> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by Mailaender** [comment]
I can't reproduce this.

**Comment by pchote** [comment]
This is a windows-specific issue, so I would be surprised if you could.
