### ISSUE TITLE
D2k map importer causes unnecessary lint errors if another mod uses D2k dll.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#19527]
![resim](https://user-images.githubusercontent.com/7933210/125955749-554f1893-eb89-427a-aa8a-04714717a055.png)
From RV, i recently added D2k.dll to the mod for Concrete logic for D2k tileset. Make test gives this errors since D2k units aren't a part of the mod.

**Comment by pchote** [comment]
One option could be for the command to add an `if (mod == "d2k")` check and silently continue for anything else.

**Comment by MustaphaTR** [comment]
The TS importer shows a warning message saying actor couldn't be found in the mod during the import, not sure if it is the case with TD/RA1 one too. I think D2k importer could do the same rather than preemptively lint checking for the actors.
