### ISSUE TITLE
Game Crash on start

### ISSUE THREAD

**Issue by PowaBanga** [OpenRA/OpenRA#19526]
Hi

- Operating System:  Archlinux ( linux  5.12.3-1 , Cinnamon desktop )
- OpenRA Version: 20210321-1
- OpenRA Mod: Red Alert
- Source: Official Archlinux repository

## Exception log
```
ls ~/.config/openra/Logs/
client.log  geoip.log     install.log  nat.log   server.log
debug.log   graphics.log  lua.log      perf.log  sound.log

```

## Replay
On the first start, i "quick install" and the game start normaly. On all start after the first start, the game stay bloqued on the first screen 
this one :
![this one](https://i.ibb.co/2cwr7Vx/Capture-d-cran-du-2021-07-16-09-51-17.png)

## Additional information
if i remove content "Content folder" only, the game stay bloqued on this screen, exactly like this screenshot : 
![](https://i.ibb.co/xqLvC3P/Capture-d-cran-du-2021-07-16-09-50-47.png)

**Comment by abcdefg30** [comment]
Possibly the same as https://github.com/OpenRA/OpenRA/issues/19434#issuecomment-855385979?

**Comment by PowaBanga** [comment]
ha yes, it's exactly the same, thank you !
