### ISSUE TITLE
AppearsOnRadar, expensive Sync

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#19536]
Version: bleed.

0.6% of hash calculation time is spent in calculating the hash for the `AppearsOnRadar` class.
This is the most time spent on across all sync objects. The time is spent in the dynamic hash function `dynamicClass::hash_AppearsOnRadar`.

The class itself has few properties and fields. The parent class `ConditionalTrait` only calculates the sync on the `IsTraitDisabled` property.

This suggests that there are a lot of `AppearsOnRadar` objects (likely one for each Actor). And/or that evaluating `IsTraitDisabled` is an expensive method to call - i.e. the `BooleanExpression` as set in the trait info.

Request:

Optimize the time spent in calculating the sync to reduce overall sync time.

Possible solutions:
- Create an extra `ConditionalTraitUnSynced` trait. Does `AppearsOnRadar` really need to be synced for this specific type?
- Remove the sync attribute on `ConditionalTrait.IsTraitDisabled`. Unwanted.
- Cache the last outcome of `IsTraitDisabled` as a field of `ConditionalTrait`. Calculate the sync on this boolean. Quick fix.
- Reduce the cost of calculating `IsTraitDisabled`. Since this configured in/by `TraitInfo` you cannot control this.
- Best. Do not allow Sync attribute on properties - or at least not properties with 'expensive' get methods.

**Comment by anvilvapre** [comment]
The game spends 28% of its time calculating sync hashes. Kind of a 'waste of time' - although the purpose is important.

**Comment by pchote** [comment]
> And/or that evaluating `IsTraitDisabled` is an expensive method to call - i.e. the `BooleanExpression` as set in the trait info.

The `IsTraitDisabled` getter doesn't evaluate any logic, it just returns the value of the autogenerated backing field which is changed only when the conditions on the actor change.

**Comment by anvilvapre** [comment]
Because the issue is related to sync properties in general - and not specific properties on which sync is calculate I consider this a duplicate of https://github.com/OpenRA/OpenRA/issues/19535. 

So let me close this one.
