### ISSUE TITLE
mission, ...109, unable to complete?

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#19548]
version: current release

one mission name ends with outpost109,

when starting it sais "invalid configuration option".

even after capturing all buildings and bridges, oil, forward coms, the map does not end?

one or two zombies appear to be not  enemy.

does one need to capture civilian buildings?

**Comment by pchote** [comment]
I think you might have downloaded https://resource.openra.net/maps/34588/, which inserts itself into the singleplayer mission list while apparently not actually supporting singleplayer play.

It should go away if you go into the skirmish map selector and delete it from the custom tab.

**Comment by anvilvapre** [comment]
yeah, that's the one.
