### ISSUE TITLE
Dune: House Ambassadors/Embacies

### ISSUE THREAD

**Issue by benhbell** [OpenRA/OpenRA#19545]
## Motivation
It seems like there are a lot of dead discussions and challenges around alliances in red alert and dune, a lot of it stemming from the non-trivial nature of managing the UI and other downstream issues. Wanted to see if using units and triggers it might be possible to sidestep some challenges and get a similar game benefit.

The goal is to provide players with a way to ally with another person on the map, as well as unally. 

## Proposed solution
Once a outpost is built players can build an embassy. Embassy can train ambassadors for each player on the map. 
* When an ambassador is built, they will be allied with that player (one way)
*  In order to have a two way alliance, both players need to have an embassy. 
* Victory conditions will only work for players that you are allied to being the remaining player.

## Side effects
The biggest side effects here are potential issues around victory conditions. It would also be great if additional functions and properties were available https://docs.openra.net/en/latest/release/traits/ so that this kind modders and mappers could create more alliance scenarios. 

Some icons and units might be needed depending on the available sprites and what not. Something I am happy to help with.

## Alternatives
Having text commands where users have to enter `ally <player name>`. I would have approached this first if I saw any events in the docs around detecting what players type. The feel of killing an ambassador you have to a player when you betray them also seems better. 

Honestly, anything that allows in-game alliances for Dune without full on UI would be a game changer (couldn't resist)

**Comment by benhbell** [comment]
@mikeik thought of this as a sidestep to some of those issues with your feature request.

**Comment by abcdefg30** [comment]
Unfortunately the UI isn't the biggest problem, but rather that it's hard to change allegiances between players after the game has already started without breaking a lot of things (e.g. autotargeting).

**Comment by benhbell** [comment]
Oh man. that's too bad.

**Comment by abcdefg30** [comment]
Closing as covered by #15061.
