### ISSUE TITLE
Activity.GetTargets not used.

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#19541]
`Activity.GetTargets()` seems to never be called. Yet it is overridden in each activity. It could be removed(?).

For the `Move` activity it seemed expensive - as the target array is reversed there. But the method is never called.

Also when drawing target nodes when actors are selected the method does not seem to be called. 

When removing the method from `Activity` there are no compile errors of the method not existing. Only for sub classes not being able to override the method.

**Comment by teinarss** [comment]
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Render/SelectionDecorationsBase.cs#L51 ?

**Comment by anvilvapre** [comment]
hm. that didn't show up while compiling.
only called if developer mode is enabled.
