### ISSUE TITLE
certain custom maps will not show in-game

### ISSUE THREAD

**Issue by Therapist1911** [OpenRA/OpenRA#19554]
I downloaded a bunch of maps from the resource center, certain ones will not show at all in the game when you click change map, or in map editor. It's like it doesn't exist. But it's clearly in the correct folder with all the other maps. One example is DC uprising. I just downloaded it, it's not showing. I quit and relaunch OpenRA, nothing. If it matters, it says it uses an urban tileset and that it's parsed by current release of OpenRA. How do I get these maps to show? Thanks.

**Comment by pchote** [comment]
DC uprising is appears to be a map for the Romanovs Vengeance mod. Are you trying to use it with RV or something else?

**Comment by Therapist1911** [comment]
I was trying to use it in Red Alert. My bad.
