### ISSUE TITLE
UPnP option not working with OpenRa

### ISSUE THREAD

**Issue by 12sunflowers** [OpenRA/OpenRA#19567]
I do not have private IP address. When i turn on UPnP in options OpenRa i cant hosting games it says

_master server communication established
Warning: server port is not accessible from the internet
game has not been advertised online_

I am already turned on UPnP and portforward manually TCP 1234 port in my router, its not help.

In others games like Popre.net, CnCnet i am successfully can host games without problems they are automatically make access rules in NAT section on my router and all work good.

Why UPnP not working for OpenRa?

**Comment by pchote** [comment]
OpenRA is different to CnCNet and the original games: while it does offer the ability to create a server as an advanced feature, this is not the standard way to play online and most people should not try to use it. You do not need to create your own room, these are instead hosted by the community and are available for anybody to join and use through the server browser. Just pick an empty server and you will become the admin and have the ability to change maps and set game rules. Invite your friends to join the same server, and kick anybody who you don't want.

To answer your actual question:

CnCNet piggybacks on the original game networking, which use the UDP protocol, while OpenRA uses TCP.
UDP can be tunneled through various complicated network layouts in ways that TCP can't, due to the fundamentally different ways that the two protocols work. The UPnP protocol can't change that.

**Comment by 12sunflowers** [comment]
Ok. Thanks for quick reply.

And for what UPnP is in options OpenRa?

So. Without private IP i can`t host own games?

**Comment by pchote** [comment]
Based on the information I saw you mention earlier on the discord, I believe not. But this shouldn't be a big problem because the dedicated servers available through the server browser have exactly the same functionality as hosting a custom server except for changing their name or specifying a password.

**Comment by Mailaender** [comment]
> Why UPnP not working for OpenRa?

Upload you `nat.log` see https://github.com/OpenRA/OpenRA/wiki/FAQ#my-game-just-crashed for the location.

**Comment by pchote** [comment]
That won't help, we already know that they are behind a carrier grade nat and that their router does not have a public facing IP for UPnP to configure.

**Comment by abcdefg30** [comment]
Closing since there is not much for us to fix in regards to UPnP here.

**Comment by Mailaender** [comment]
It would still be helpful to see the output of the log file. Maybe this scenario can be detected somehow.

**Comment by 12sunflowers** [comment]
@abcdefg30 @Mailaender  @pchote 

Why for this game popre.net UPnP is working, but for OpenRa not?

![Popre net2](https://user-images.githubusercontent.com/2568511/128614086-6eaa675c-7efa-4a5e-a814-04157ecadb11.png)
![Popre net1](https://user-images.githubusercontent.com/2568511/128614090-ddc9f80a-7925-4b7f-a262-4d9f30871ae3.png)

**Comment by pchote** [comment]
The first screenshot shows that Populous uses UDP, which like I explained above can be tunneled.

**Comment by 12sunflowers** [comment]
Thanks. And OpenRa can not do like Populous?

**Comment by 12sunflowers** [comment]
> UDP can be tunneled through various complicated network layouts in ways that TCP can't, due to the fundamentally different ways that the two protocols work. The UPnP protocol can't change that.

@pchote 
And for what OpenRa have feature UPnP in options if its not working here?

**Comment by 12sunflowers** [comment]
> Upload you `nat.log` see https://github.com/OpenRA/OpenRA/wiki/FAQ#my-game-just-crashed for the location.

@Mailaender 
[Logs.zip](https://github.com/OpenRA/OpenRA/files/6949882/Logs.zip)

**Comment by Mailaender** [comment]
> System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host

I don't know if we can use this error message to detect carrier grade NAT and display a FAQ message.

Nonetheless, @pchote was right: your router is detected, ports are opened and closed properly, but it isn't enough:

```
Open.NAT Information: 0 : UPnP Response: Router advertised a 'urn:schemas-upnp-org:service:WANIPConnection:1' service!!!
Open.NAT Information: 0 : Found device at: http://192.168.0.1:2828/gateway.xml
Open.NAT Information: 0 : 192.168.0.1:2828: Fetching service list
Open.NAT Information: 0 : Found device at: http://192.168.0.1:2828/gateway.xml
Open.NAT Information: 0 : 192.168.0.1:2828: Parsed services list
Open.NAT Information: 0 : 192.168.0.1:2828: Found service: urn:schemas-upnp-org:service:WANIPConnection:1
Open.NAT Information: 0 : 192.168.0.1:2828: Found upnp service at: /upnp/control/vdrzcjwjjf/wanipconn-2
Open.NAT Information: 0 : 192.168.0.1:2828: Handshake Complete
Open.NAT Information: 0 : Stop Discovery
Open.NAT Information: 0 : GetExternalIPAsync - Getting external IP address
Open.NAT Verbose: 0 : SOAPACTION: **GetExternalIPAddress** url:http://192.168.0.1:2828/upnp/control/vdrzcjwjjf/wanipconn-2
Open.NAT Information: 0 : CreatePortMapAsync - Creating port mapping Tcp 1234 --> 192.168.0.17:1234 (OpenRA)
Open.NAT Verbose: 0 : SOAPACTION: **AddPortMapping** url:http://192.168.0.1:2828/upnp/control/vdrzcjwjjf/wanipconn-2
Open.NAT Information: 0 : DeletePortMapAsync - Deleteing port mapping Tcp 1234 --> 192.168.0.17:1234 (OpenRA)
Open.NAT Verbose: 0 : SOAPACTION: **DeletePortMapping** url:http://192.168.0.1:2828/upnp/control/vdrzcjwjjf/wanipconn-2
```

We already have some UPnP improvements in the pipeline for the next release https://github.com/OpenRA/OpenRA/pull/19114 but it will only speed up the discovery, not solve this problem. Maybe ask your provider for IPv6 support, as I read that IPv4's limited address space is the reason why they do this.

**Comment by 12sunflowers** [comment]
> Maybe ask your provider for IPv6 support

@Mailaender 
My provider does not support IPv6 it now, but it should appear in the future. IPv6 can help solve the problem UPnP for game even without private IP?

**Comment by Mailaender** [comment]
Not necessarily, but they often imply this weird restriction because they don't have enough IPv4 addresses. See https://en.wikipedia.org/wiki/Carrier-grade_NAT

**Comment by 12sunflowers** [comment]
@Mailaender 
I do not understand why you make UPnP feature option in game if it not work and useless? 
Write honestly in the requirements  that for hosting is needed private IP.

**Comment by Mailaender** [comment]
[Added it to the FAQ](https://github.com/OpenRA/OpenRA/wiki/FAQ/_compare/7f49d28e4fa0c082027b2903ad841b47e7cb6ff7...0ae79533595e52b7d74a5a182cdaea723e7554e6).
