### ISSUE TITLE
Is Tiberian Sun removed from bleed branch?

### ISSUE THREAD

**Issue by eclaircs** [OpenRA/OpenRA#19605]
And why? Will you continue to develop it? I like it the most in the series.
Where is the Openra IRC chat room now? Is it still on the freenode.net? So few people in the chat room.

**Comment by penev92** [comment]
Hello. TS hasn't been removed - it is still very much there, and there are currently several PRs open working on it.
The IRC moved to [Libera](https://web.libera.chat/#openra), but most communication is done on [Discord](https://discord.openra.net/) now.

**Comment by abcdefg30** [comment]
The mod is still here: https://github.com/OpenRA/OpenRA/tree/bleed/mods/ts
