### ISSUE TITLE
GPU Acceleration

### ISSUE THREAD

**Issue by 0xA1B2** [OpenRA/OpenRA#19614]
Once there are hundret items on the map, OpenRA gets really slow. When do you consider to use the GPU to outsource computation ?

Today you can run millions of items smoothly:

https://store.steampowered.com/app/1468720/Ultimate_Epic_Battle_Simulator_2/

**Comment by IceReaper** [comment]
They use some techniques like Indexed and Instanced rendering. In combination with bindless textures, a whole scene with several thousand different models in several million of different instances can render in way under 1 millisecond using a single (!) opengl call. The bottleneck is (as always) the cpu <-> gpu communication. That however requires OpenGL 4.5+ So not likely soon without dropping old machines completely. GL 4.5+ Should be ~ Geforce 600 Series and above.

**Comment by nightlyworker** [comment]
Please don't drop old machines. Thanks for insightful comment @IceReaper

**Comment by abcdefg30** [comment]
There's nothing more directly actionable in this issue, so closing.
