### ISSUE TITLE
Images slightly outside of the viewport are cut off

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#19621]
Introduced by ef1aee5e95a79cebc79f120e80fff2c69790e089 the renderer starts to cut of sprites that are not completely inside the viewport.

![ra](https://user-images.githubusercontent.com/756669/130322712-6d8a958d-e859-4ec8-a459-6709d4cf3c9b.png)

**Comment by IceReaper** [comment]
Same on OpenKrush :-P
![image](https://user-images.githubusercontent.com/1322277/130323641-05c1b749-a41d-4440-a735-0434e535671b.png)

**Comment by dnqbob** [comment]
is this one the same bug?
![1](https://user-images.githubusercontent.com/13763394/130553041-2a498950-4c7e-40fe-9916-5747303d7024.gif)

**Comment by Mailaender** [comment]
See if #19622 fixes it for you.
