### ISSUE TITLE
Question: .NET 5 release requires VS19?

### ISSUE THREAD

**Issue by fruestueck** [OpenRA/OpenRA#19630]
Hello!

I was having some issues building the latest bleed on my device with a VS2017 (.net 4.6ish) installation.

Figured out open ra switched to .net 5 this year. The [OpenRA Compiling wiki entry](https://github.com/OpenRA/OpenRA/wiki/Compiling) states VS2017 as its minimum requirement but according to the [dotnet.microsoft website](https://dotnet.microsoft.com/download/visual-studio-sdks) .NET 5.0 SDK is only available for VS2019+.

May I update the wiki to VS2019?

**Comment by abcdefg30** [comment]
Hi!

> May I update the wiki to VS2019?

It would be good if you have the time to correct that (and any other outdated information).
