### ISSUE TITLE
Player's buildings explode with high handicap and without concrete (Dune 2000)

### ISSUE THREAD

**Issue by 6AKU66** [OpenRA/OpenRA#19633]
## Issue Summary

Buildings explode if player have high handicap and place buildings not on concrete (Dune 2000)

## Reproduction

1. Set up your handicap to 95%
2. Order wind traps
3. Place it on ground without concrete

## Expected behavior

BOOM

**Comment by pchote** [comment]
`D2kBuilding` probably wants to be calling `InflictDamage` with `ignoreModifiers: true`.
