### ISSUE TITLE
Recent OpenRA version: features removal and brutal nerfs?

### ISSUE THREAD

**Issue by Demiosis** [OpenRA/OpenRA#19644]
Since I updated I cannot have multiples building queues on my production facilities!
example: 1 barracks producing rocket launcher soldiers and the other engineers.

Along with it I notice a severe nerf for the Humvees, Jeeps, Trikes, Raider trikes , Stealth trikes , they practically cannot do anything to infantry anymore and are only useful  as a vision bot for your infantry reducing Ordos in Dunes to a very mediocre faction..

**Comment by reaperrr** [comment]
> Trikes, Raider trikes , Stealth trikes , they practically cannot do anything to infantry anymore and are only useful as a vision bot for your infantry reducing Ordos in Dunes to a very mediocre faction..

D2k balance was brought in line with the original, which included changes to the area of effect and damage falloff. This isn't a bug in any case, at most it's a balance issue.

> Along with it I notice a severe nerf for the Humvees, Jeeps,

According to the changelog, there haven't been any changes to Humvees and Jeeps (I assume you're referring to Tiberian Dawn). They still kill infantry several times faster than in the original games, too, I just tested.

> Since I updated I cannot have multiples building queues on my production facilities!
example: 1 barracks producing rocket launcher soldiers and the other engineers.

The only official OpenRA mod that ever supported this to my knowledge has been TD, and it still works there...?

**Comment by penev92** [comment]
> D2k balance was brought in line with the original, which included changes to the area of effect and damage falloff.

In any case Trikes and their variants are still the most OP unit in the game as far as I'm aware.

**Comment by Demiosis** [comment]
I see , well maybe I had a skewered memory of the build queues, I swear I seen it in other games but it just my brain that have wishful thinking XD also yes I just tried Tiberian dawn and it felt fine like last time I played so nvm this issue and welp I had a very hard time winning with raider trike spam with late rocket boys vs 2 standard A.I's dunno what im doing wrong here XD

**Comment by abcdefg30** [comment]
Closing as resolved then.
