### ISSUE TITLE
SIGSEGV in Mono Runtime on startup when installing from xtradeb

### ISSUE THREAD

**Issue by BitWire** [OpenRA/OpenRA#19670]
## System Information

- Operating System:  Ubuntu 20.04.3 LTS
- OpenRA Version: release-20210321
- OpenRA Mod: no mods
- Source: APT Package Manager
- Mono Version: Debian 6.8.0.105+dfsg-2 Wed Feb 26 23:23:50 UTC 2020
        TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

## Exception log

No exception.log present

## Additional information

No matter which version i started (D2K, CNC, RA), the game crashes before launching with the message below:
```
Platform is Linux
Engine version is release-20210321

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
Aborted (core dumped)
```
Hardware:
i7-3770
GTX-650Ti with nvidia-driver-460

**Comment by Mailaender** [comment]
You could try if using https://www.mono-project.com/download/stable/#download-lin-ubuntu fixes it.

**Comment by pchote** [comment]
Are you running the AppImage files from the website? These package their own runtime, so the system mono install shouldn't change things.

You could try [compiling from source](https://github.com/OpenRA/OpenRA/blob/release-20210321/INSTALL.md#linux) to see if the problem goes away when using system libraries (but note that the dependencies and steps are different for release-20210321 which I linked compared to the development branch).

**Comment by BitWire** [comment]
@Mailaender Will give it a try after the appImage.

@pchote
I am running the packaged version from the ubuntu apt repositories and their dependencies.

Thanks for the suggestions. I will give feedback once i tried

**Comment by BitWire** [comment]
@pchote the AppImage works fantastically. thanks for the suggestion!
@Mailaender the newer mono didnt work for me sadly, still sigsev. I'll add a valgrind log i made to the ticket, and open another ticket in the xtradeb launchpad

[crashdump.log](https://github.com/OpenRA/OpenRA/files/7217555/crashdump.log)
Again thanks a lot for your help

**Comment by anvilvapre** [comment]
The log suggests its xorg, GL, sdl related due to `XCloseDisplay`. I assume library compatability issues. Not game code related.

**Comment by Mailaender** [comment]
Report it at https://bugs.launchpad.net/xtradeb if the issue persists.
