### ISSUE TITLE
MainMenuLogic, SetNewsStatus, connection exception not shown.

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#19684]
bleed

During start up news cannot be retrieved on my host. This is correct. 

As a result `SetNewsStatus($"Failed to retrieve news: {e}");` is called in `MainMenuLogic`. However I cannot see this message being rendered in the UI anywhere. 

The news pull down menu shows 'Battlefields News' and when opening the pull down it shows the I assume default release notes. Not the message or exception stack as string. 

How to reproduce:  disconnect or block your inet connection, see that no error/fail message is showns that indicates the news could not be retrieved.

**Comment by abc013** [comment]
For me, it actually shows something:
![grafik](https://user-images.githubusercontent.com/21260178/138968669-ced0c577-1716-43b0-b337-bbc225cc107b.png)

Maybe we should use `SetNewsStatus($"Failed to retrieve news: {e.Message}");` instead, which would lead to the following result: 
![grafik](https://user-images.githubusercontent.com/21260178/138968806-9d398253-a660-4bf8-a331-af85d8391bf3.png)

**Comment by anvilvapre** [comment]
bleed?

i noticed when i was working on font.measure. i twas measuring a stack trace that was never shown on screen on my system.

**Comment by abc013** [comment]
> bleed?

yes.
> The news pull down menu shows 'Battlefields News' and when opening the pull down it shows the I assume default release notes. Not the message or exception stack as string.

Thinking about it, news are cached in `news.yaml`, which means that if the game can't get to the website, it will display the cached message instead. But if there is no cached message, the error (stack trace) will be displayed. I'll file a PR to implement the change I have mentioned before.
