### ISSUE TITLE
A crash related with Exit trait (and probably plus AI)

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#19707]
See [issue](https://github.com/ABrandau/Shattered-Paradise-SDK/issues/42)

**Comment by Mailaender** [comment]
I doubt it is related to AI. Probably just bad timing of an exit being searched while the building is sold or destroyed. Compare https://github.com/OpenHV/OpenHV/commit/0ec7e2553dd55f7801290e11b6e3b64f53b3db94

**Comment by dnqbob** [comment]
However, about AI I only change the Squad related and it is nothing related to production and exit.

**Comment by dnqbob** [comment]
I will test your code on replay to see if it can solve this problem.
