### ISSUE TITLE
Lobby options dropdown description should make sense in a disabled state

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#19700]
While working on #19461 I noticed that some of the dropdown lobby options have tooltips that don't sound good when the controls are disabled (e.g. "Change the difficulty of the mission"). The controls can be disabled when the user is not the lobby admin and of course when viewing them on the new in-game panel.
![image](https://user-images.githubusercontent.com/1355810/134862446-1a8a7504-b1c4-4cb9-af96-541058b06a83.png)

The strings that need changing:
- "Change the difficulty of the mission"
- "Change the amount of cash that players start with"
- "Change the units and abilities at your disposal"
- "Change the rate at which time passes"
- "Change the units that you start the game with"

## Proposed solution
Alter the text in a way that makes sense in both disabled and enabled state. For example "Change the difficulty of the mission" could simply become "The difficulty level of the mission".
![image](https://user-images.githubusercontent.com/1355810/134862640-eb5a0150-6b08-4ba4-ae18-1db04597cb2f.png)

## Side effects
The verb is gone from the description.

**Comment by pchote** [comment]
The suggested change makes sense. Do you plan to do a PR?

* "The difficulty of the mission"
* "The amount of cash that players start with"
* "The units and abilities at your disposal"
* "The rate at which time passes"
* "The units that you start the game with"
