### ISSUE TITLE
Crash when pressing Esc in-game

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#19735]
On current bleed, when pressing Esc during a Skirmish I got this:

![esc-crash](https://user-images.githubusercontent.com/2857877/136701472-a724944d-60cf-4e37-9938-6447ab4875d4.png)

**Comment by abcdefg30** [comment]
I cannot reproduce this right away. It cancels some input mode there; were you in some order generator?

**Comment by abcdefg30** [comment]
@penev92 also reported he gets this on the RA2 mod when using the latest engine.

**Comment by abcdefg30** [comment]
Seems like this only happens when "Check Sync around Unsynced Code" is disabled(!). The culprit is https://github.com/OpenRA/OpenRA/commit/1dc0a603c75132776f669789e89596b15245ea26.
