### ISSUE TITLE
RA: Official Map Europe is Bugged

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#19740]
![2021-10-10 20_59_30-Window](https://user-images.githubusercontent.com/42915475/136719726-791af593-dcea-4fa4-9196-a8850e3367d6.png)

Some map actors are flagged as creeps, which screws up the AI into trying to attack them.

**Comment by airetaM** [comment]
I´ve spotted some visual bugs on this map if you want to fix them.
![europeBugs](https://user-images.githubusercontent.com/14834585/137394628-3aeb4460-82cf-419a-a47f-2bdf1ba3628e.png)

**Comment by JMegaTank** [comment]
https://github.com/OpenRA/OpenRA/pull/19742
