### ISSUE TITLE
Bug on TileSelecter in Map editor

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#19744]
TA makes it own terrain but when it comes  into the side bar of map editor, it doesn't look right.

The tileset imgs are all the same size but become scattered and disordered on TileSelecter. 

![-72895858a02c5edd](https://user-images.githubusercontent.com/13763394/136891217-a7251a58-8ebd-46dc-846f-2eb44c17ea08.png)

**Comment by abcdefg30** [comment]
Can you provide a reproduction case in TS?

**Comment by dnqbob** [comment]
ummmm, maybe we push this version of TA?

**Comment by dnqbob** [comment]
wait for a second

**Comment by dnqbob** [comment]
mod: https://gitee.com/CastleJing/TiberianAurora
engine it uses: https://gitee.com/CastleJing/TA_Engine/tree/TA_AI_Engine_Update/

img is in mods/ta/content/terrain_tem/, but I don't suggest to put it in TS, because we use ra2 viewpoint on terrain.

Sorry for tons of Non-english commit but we don't change related code in c#

**Comment by penev92** [comment]
It is not as noticeable in [OpenRA/ra2](https://github.com/OpenRA/ra2), but I did spot a few such issues:
![image](https://user-images.githubusercontent.com/7137365/136934666-7429c04f-b04f-4cb9-b678-50db8961796a.png)
![image](https://user-images.githubusercontent.com/7137365/136934734-eafa97b2-199d-4561-a3ff-97b14d04fdaf.png)
![image](https://user-images.githubusercontent.com/7137365/136934778-9dd62639-c35c-432d-b83d-441deff7828d.png)
![image](https://user-images.githubusercontent.com/7137365/136934798-e0d618c3-5450-4abb-98de-c5f04245fa1f.png)
![image](https://user-images.githubusercontent.com/7137365/136934880-71397f8e-c891-4b91-b207-9bb54e529abd.png)

This is with a WIP version of RA2 that is updated to use current OpenRA `bleed`, so it is an upstream engine issue (or a tile definition issue ... somehow).

**Comment by penev92** [comment]
TS on `bleed` also has a few of these, where the water you see on the left is the selected "template" (149) from the palette on the iright, but it looks broken into tiles in the palette:
![image](https://user-images.githubusercontent.com/7137365/136935736-89caa3d7-3ab9-4d87-91f7-dd171139ce6c.png)

**Comment by pchote** [comment]
I suspect the problem is that the individual tile offsets are not being scaled correctly when templates are automatically downsized to fit within the sidebar width.
