### ISSUE TITLE
Add support for 48kHz Stereo AUD files (and possibly replace the defaults) 

### ISSUE THREAD

**Issue by Leo512bit** [OpenRA/OpenRA#19764]
## Motivation 
https://forums.cncnet.org/topic/3557-hd-music-pack-for-red-alert-version-2-with-stereo/
https://forums.cncnet.org/topic/3563-hd-music-pack-for-tiberian-dawn-in-game-music/

## Feature / Enhancement

Add support for 48kHz Stereo AUD files and possibly make the ones that I linked above the default. As the game's AUD player doesn't like them and they are higher quality.

## Side effects

Bigger file sizes.

**Comment by reaperrr** [comment]
We can't make them the default for legal reasons, and we support several other audio formats by now, including the one used by the remasters' stereo music, so I don't think this will happen anytime soon, if ever.

**Comment by Leo512bit** [comment]
> We can't make them the default for legal reasons, and we support several other audio formats by now

I figured that will happen and I know that the game supports other formats but the AUD player doesn't support these files.
