### ISSUE TITLE
🔔 Ethereum phishing detected on www.OpenRa.net 🔔

### ISSUE THREAD

**Issue by melroy89** [OpenRA/OpenRA#19762]
Ethereum Phishing Detection is triggered on www.openra.net according to [MetaMask](https://metamask.io/).

![image](https://user-images.githubusercontent.com/628926/137817071-1c7bd0f4-1f04-49ce-97c0-1bfb19954b6c.png)

Please, take this seriously.

Regards,
Melroy

**Comment by melroy89** [comment]
Never mind, I think it's a bug at Metamask? You are not on the whitelist.

https://github.com/MetaMask/eth-phishing-detect/issues/5622

**Comment by abcdefg30** [comment]
Seems like https://github.com/MetaMask/eth-phishing-detect/pull/5636 will fix this, so hopefully upcoming versions of Metamask won't run into this problem.
