### ISSUE TITLE
Error "wine64: command not found" when build package for windows

### ISSUE THREAD

**Issue by CastleJing** [OpenRA/OpenRA#19781]
## Issue Summary

I used the packaging tool to package OpenRA of the bleed branch, and got the following error 

```sh
./buildpackage.sh: line 51: wine64: command not found
```

and line 51 of packaging/windows/buildpackage.sh is

```sh
wine64 rcedit-x64.exe "${BUILTDIR}/${LAUNCHER_NAME}.exe" --set-icon "${BUILTDIR}/${MOD_ID}.ico"
```

## Reproduction

```sh
cd packaging
./package-all.sh release-xxxxxxxx ~/out
```

## Expected behavior
```sh
Patching /home/castle/OpenRA/packaging/windows/build/RedAlert.exe:
 - Setting /LARGEADDRESSAWARE
 - Setting /subsystem:windows
./buildpackage.sh: line 51: wine64: command not found
windows package build failed.
```

**Comment by abcdefg30** [comment]
Do you have `win64` installed?

**Comment by pchote** [comment]
https://github.com/OpenRA/OpenRA/blob/8416dc3f2dde1d1cbda590c7ddae974b82273257/packaging/windows/buildpackage.sh#L6-L9

is missing a check for `wine64`. https://github.com/OpenRA/OpenRAModSDK/pull/171 will need to be updated too.

**Comment by CastleJing** [comment]
> 
> 
> Do you have `win64` installed?

no, I just tried to install wine64 and the problem seems to be solved, maybe there needs to be a check and reminder here
