### ISSUE TITLE
Improve fullscreen support on MacBook Pro's with notch on screen

### ISSUE THREAD

**Issue by laszlotuss** [OpenRA/OpenRA#19816]
## Issue Summary

The new MacBook Pros with M1 Pro or M1 Max has a new screen with a notch on the top center.
Using the default **Windowed video mode** will result in a top padding which pushes off-screen the bottom part of the game.

## Reproduction

Set to **'Windowed' video mode**.

## Expected behavior

The default **Windowed video mode** should still have a top padding while the bottom should fits the screen.
## Screenshots / Screen recordings / Replays

![OpenRA_Fullscreen_issue](https://user-images.githubusercontent.com/2952613/143873895-9d437df6-06cb-4718-8daa-062cd6e3b290.jpg)

**Comment by wiesmann** [comment]
For me the bug happens in non-windowed mode. 
One workaround I found is to use the legacy Open-GL full-screen mode.

**Comment by petergombos** [comment]
I'm having the same issue with non-legacy fullscreen mode

**Comment by pchote** [comment]
This is going to be difficult for me to debug and fix without having access to a notched machine to test with.

Probably related to a mismatch between https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs#L268 and https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Platforms.Default/Sdl2PlatformWindow.cs#L294.

**Comment by wiesmann** [comment]
Another workaround is to open the information for the app in the Finder and to check the box "Scale to Fit below built-in Camera". 

<img width="377" alt="OpenRaScaleCamera" src="https://user-images.githubusercontent.com/398765/158171279-82b8a098-f8d9-4707-9b72-83f4400251d4.png">

**Comment by chenny** [comment]
I'm having the same issue with  fullscreen mode

**Comment by laszlotuss** [comment]
> I'm having the same issue with fullscreen mode

Just tick the **_Scale to Fit below built-in Camera_** settings on each **.app** properties as @wiesmann said and use the non legacy full screen mode then  you will be fine.

**Comment by pchote** [comment]
TODO: make a test build with https://developer.apple.com/documentation/bundleresources/information_property_list/nsprefersdisplaysafeareacompatibilitymode for testing.
