### ISSUE TITLE
General-like building process support

### ISSUE THREAD

**Issue by ZhiZe-ZG** [OpenRA/OpenRA#19813]
## Motivation

Can the building method that requires construction workers in "General" be realized as an option for the game engine?
Adding these options can enrich the game mode.

## Proposed solution

PROPOSED SOLUTION

## Side effects

EXPECTED SIDE EFFECTS

## Alternatives

ALTERNATIVES

**Comment by abcdefg30** [comment]
It is possible to do these via Lua or custom traits (I believe mods like Medieval Warfare used to do this). However, I think this is unlikely to be used in the default mods and therefore out of scope for the default mods, sorry.
