### ISSUE TITLE
On GiveUnitCrateAction allow to define a Sequence: to be played when crate gets picked up.

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#19825]
In one of my mods have implemented a GiveUnitCrateAction@minefield: that seeds neutral hostile land mines around the unit. 
It can appear to the player as if nothing had happent as few units can detect Landmines, and the unit might have been on its own far from any detector.
To better transmit to the player that the unit has been trapped in a minefield would like to assign a sequence that will get played when this pickup occurs.

**Comment by MustaphaTR** [comment]
The animation on crate actions come from the default CrateAction trait, every CrateAction should be already supporting this. https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Crates/CrateAction.cs#L28

**Comment by MlemandPurrs** [comment]
ah, it works.
-1 issue.
