### ISSUE TITLE
Question: On desync, does OpenRA have a possibility that not disconnect all players?

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#19834]
On Oct 31st we used SPSC (basically SP with a localization) on test a desync that happens on AI use Mind Control (we will ask helps later in another issue). 2 human players vs 2 AI with a server.

However, we find that when desync happens, there is a chance that only one player get desync and game crash while the other still in game and only see the game crash player disconnected from server.

**Comment by dnqbob** [comment]
https://github.com/MustaphaTR/OpenRA/commits/rv-engine
This is our latest rebase version

**Comment by pchote** [comment]
This is probably related to jrb's servers?

**Comment by dnqbob** [comment]
Is this normal on certain condition or it is a bug?

**Comment by dnqbob** [comment]
> This is probably related to jrb's servers?

I really got no idea, this bug/feature make our debug very hard to produce a sync report

**Comment by dnqbob** [comment]
Add: we actually use our own server but I don't know if it is also happens to jrb's servers

Add: is it also server related?

**Comment by abcdefg30** [comment]
A client should receive the sync orders from all other players, therefore all or none should crash with out of sync with the default implementation. This is likely related to some custom changes/server implementation.

**Comment by dnqbob** [comment]
@MustaphaTR  do we have some custom change on server code?

**Comment by MustaphaTR** [comment]
There are a few server related changes on rv-engine, but i'm not exactly sure what exactly they done. One change is on Timestamps to enable spectators to catch up if they lag back on jrbs servers. I'm not sure if there are any old changes to the server code in rv-engine branch that could cause this.

**Comment by pchote** [comment]
Fixed by #19958.
