### ISSUE TITLE
CNCTFD DVD not detected when trying to install additional data (Ubuntu snap package, USB external drive)

### ISSUE THREAD

**Issue by UnasZole** [OpenRA/OpenRA#19841]
## Issue Summary

When trying to install additional data from an original CNC TFD DVD, I get "Detect Disc or Installation" -> "Game Content not found".

## Reproduction

- Install openRA on Ubuntu using snap package (release-20210321, revision 1359 )
- Download freeware contents using Manage Content (no problem, game runs perfectly)
- Plug an external DVD drive in USB and insert the CNCTFD disk (it is correctly mounted under /media/<username>/CNCTFD and is perfectly browsable)
- Restart OpenRA, go to Manage Content and try to install the missing data.

-> Get "Game Content not found"

Wondering if it could be related to the Ubuntu Snap package, I checked and noticed that the openra snap package does not have the removable-media plug - I'm not completely sure if that matters (I'm no expert at all when it comes to snap).
I tried to explicitly enable it with "sudo snap connect openra:removable-media :removable-media", but no effect.

## Expected behavior

Should detect the disc and proceed to installing the additional data.

**Comment by Mailaender** [comment]
Sounds like a sandboxing problem. Report it at https://github.com/diddlesnaps/openra/issues
