### ISSUE TITLE
Broken attack move for vehicel with turret weapon

### ISSUE THREAD

**Issue by UppsAlert** [OpenRA/OpenRA#19845]
When a vehicel with a turret weapon get another attack move order while attacking a unit in range, then it will move further across the attack move line until it lost track of the target. Then the vehicel will stop, if another target is in range.  This includes Tesla Tanks Mammoths, Rangers and so on.

https://user-images.githubusercontent.com/54892539/146076908-346defd1-d295-4fbc-8de2-fb8e8486cf75.mp4

yes .... my exchange graphic card cant handle OBS :´(

**Comment by Tailog2** [comment]
I've looked into the code. I guess it should work in that way. The AttackMoveActivity method was made that it will stop and attack up until it has target in the range. So I am not quite sure that this is a bug.

**Comment by CJure** [comment]
Just to make it sure, correct behaviour would be to continue attacking target that is already attacking and not move? Or to attack next possible target in the way and not move out of "range" of current target?

**Comment by abcdefg30** [comment]
> correct behaviour would be to continue attacking target that is already attacking and not move?

I would argue yes, as that would be consistent with giving a direct attack order and with non-turreted units.

**Comment by UppsAlert** [comment]
> Just to make it sure, correct behaviour would be to continue attacking target that is already attacking and not move?

Yes this would be correct, if you ask me this would be a huge bugfix.
