### ISSUE TITLE
ChangesHealth incorrect work

### ISSUE THREAD

**Issue by CuteCasibFox** [OpenRA/OpenRA#19855]
## Issue Summary

DESCRIPTION
When HP of the Actor is less 100 ChangesHealth is not works, but start to work from 100 and more. Health not change with Step and 
PercentageStep.

## Reproduction

STEPS TO REPRODUCE THE ISSUE
I set Step and PercentageStep: -1 with Delay: 2. StartIfBelow: 101

## Expected behavior

EXPECTED BEHAVIOR
Health should changes health when HP is less than 100.

## Screenshots / Screen recordings / Replays

Here is file of map with different test actors.
[newmap7.zip](https://github.com/OpenRA/OpenRA/files/7777318/newmap7.zip)

**Comment by reaperrr** [comment]
This isn't a bug, but rather an expected limitation of `StartIfBelow` being an integer percentage (which we won't change for performance and stability reasons).

The "problem" is that the further you go below 100 HP, the more coarse the the formula operates.
For example, if an actor has only 10 default HP, `StartIfBelow` needs to be at least 110 (or higher) if you want the trait to change HP even at full health.

Not sure if this is worth adressing at code level, so in the meantime either use a higher `StartIfBelow` value (the rounded-down integer result of `StartIfBelow * HP` needs to be at least 1 higher than HP), or work with higher HP values to work around this.

**Comment by CuteCasibFox** [comment]
Thanks for explanation. I evaded it by using KillsSelf in most cases. In Best Map Evur temporal actors used Burns and I changed it to ChangesHealth and then to KillsSelf.

**Comment by abcdefg30** [comment]
Closing as resolved then.
