### ISSUE TITLE
Wrong Version in winget

### ISSUE THREAD

**Issue by MSchaefer83** [OpenRA/OpenRA#19866]
## Issue Summary

Whenever you run winget upgrade --all, the installation of OpenRA is performed.
The problem is that winget shows the local installation as version "release-20210321". But version "20210321" is available, without release.

DESCRIPTION

## Reproduction

STEPS TO REPRODUCE THE ISSUE
Install openra with "winget install openra.openra"
Than make a update.
"winget upgrade --all" or "winget upgrade openra.openra".

## Expected behavior

EXPECTED BEHAVIOR

**Comment by Mailaender** [comment]
That package is maintained at https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/OpenRA/OpenRA and has its own bugtracker.
