### ISSUE TITLE
Installing game content under Linux | Documentaton

### ISSUE THREAD

**Issue by TheNerdyHamster** [OpenRA/OpenRA#19876]
When trying to install game-content under Linux without a "file manager" or mounting tool that sets the type to CDRom, the wiki dosen't mention where the ISO's should be mounted.
After viewing the source code, there seems like there is three paths that are searched when running Linux:
https://github.com/OpenRA/OpenRA/blob/bf7ec4aec19c1b9768f6641206538434afe52efe/OpenRA.Mods.Common/Widgets/Logic/Installation/InstallFromDiscLogic.cs#L122-L132

### Changes to wiki
```diff
Downloading Original Game CDs
<...>
+
+### Game media within Linux (normal installation)
+When running OpenRA directly without sandboxing, and adding the original game content from a game ISO image, you have +multiple path options:
+- `/media/openra`
+- `/media/{user}/openra`
+- `/mnt/openra`

+Example:
+```
+$ mount -o loop,uid={uid} CD1_ALLIED_DISC.ISO /media/openra
+```
+ 
Game media within Linux Flatpak installation
<...>
```

Need to double check if permissions is required for the game contnt to be found.

_Feedback is wanted, and happily discussed_

**Comment by abcdefg30** [comment]
Changes make sense, so 👍 to adding this to the wiki.

**Comment by TheNerdyHamster** [comment]
New section can be found [here](https://github.com/OpenRA/OpenRA/wiki/Game-Content#game-media-within-linux-normal-installation)
