### ISSUE TITLE
feature request:add game plugin 

### ISSUE THREAD

**Issue by annopnod** [OpenRA/OpenRA#19870]
add game plugin lua script and OpenRA API folder path Plugin
and use ra/weapons/test.yaml add line to yaml 

''script'': ''Plugin/Weapons/Comet.lua''

Plugin/SuperWeapons/PsychicDominator.lua //Psychic Dominator action (from tibed 1.7 yuri)
Plugin/Weapons/MindControl.lua //yuri mind control
Plugin/Weapons/Comet.lua //prism tank weapons (from tibed 1.7 yuri)

Plugin/Weapons/Comet.lua 
algorithm find near  enemy and kill

**Comment by abcdefg30** [comment]
Sorry, from this description it is not quite clear what the issue is. Custom modifications can be added to maps but are not included with the base game. The forums and/or Discord are better places for sharing custom modifications.

**Comment by annopnod** [comment]
custom game mod using lua script and openra api
