### ISSUE TITLE
Non-essential map files are ignored in uid generation

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#19888]
Map uid (probably short for unique id) only takes into account `.yaml` `.bin` and `.lua` files. Meaning that if any of the other file formats are different between maps they will be treated as the same. Possibly causing desyncs. It should also take into consideration `.shp` `.png` `.pal` `.aud` formats as well (the list is probably longer). Alternatively it should take into account all files present in a map

This bug or "intentional feature" would be very annoying if #19885 was merged

**Comment by PunkPun** [comment]
As discussed via discord, we don't want to include all files in uid generation as that may cause significantly increase load time. As a way of optimisation uid is generated only from files that could cause desyncs. While map.png doesn't cause desyncs, it is preloaded in lobby logic and only updated once uid has changed. One solution here is to include map.png into uid generation

**Comment by anvilvapre** [comment]
You could include a version number of a map in the generation of the guid. The map developer can then bump up the version if needed - i.e. if he changes some files.

Also many maps mentions version in their name. Good to make this an official field - if not already. This could also allow you to filter only on last versions of a map i.e. *gardens v5162700.

**Comment by PunkPun** [comment]
> You could include a version number of a map in the generation of the guid

it's already included as all yaml files are included into uid generation

> Also many maps mentions version in their name. Good to make this an official field - if not already. This could also allow you to filter only on last versions of a map i.e. *gardens v5162700.

This is scope creep and deserves its own issue. Regardless, most maps don't have versions so we may not want to waste UI space for it. Secondly changing the map name to me seems like already a good default solution. I don't see a need to add an official way of versioning, unless we get around to integrating resource centre into the game
