### ISSUE TITLE
detect CD for snap installed openra

### ISSUE THREAD

**Issue by Saroumane** [OpenRA/OpenRA#19929]
## Motivation

I have installed the latest `openra` ( release-20210321 ) on Ubuntu with snap.
`$ sudo snap install openra`
I could not find help on wiki about detecting the ISO CD image (to install missing assets)

## Proposed solution

I found a solution :
`$ sudo connect openra:removable-media`

I suggested to add it to the wiki :
https://github.com/OpenRA/OpenRA/wiki/Game-Content/_compare/c1d07baa5b25b4fa970287cf1ebb22839721d109...cf9ae3d7fd9fcaed2d26e9d3a115eaf3e2efe42a
( + typo corrected : https://github.com/OpenRA/OpenRA/wiki/Game-Content/_compare/cf9ae3d7fd9fcaed2d26e9d3a115eaf3e2efe42a...a8079919f79d30c2898b58a8f2d26c466245200f )

**Comment by Mailaender** [comment]
To enable this by default, someone has to start a voting procedure. https://forum.snapcraft.io/t/process-for-aliases-auto-connections-and-tracks/455 explains the process.

**Comment by Mailaender** [comment]
Documented at https://github.com/OpenRA/OpenRA/wiki/Game-Content#linux-snap so nothing else we can do from here.
