### ISSUE TITLE
AppImage crashes on Ubuntu when Content folder exists

### ISSUE THREAD

**Issue by branttaylor** [OpenRA/OpenRA#19937]
## System Information

- Operating System:  Ubuntu 21.10
- OpenRA Version: release-20210321
- OpenRA Mod: None
- Source: Official download package

## Exception log

```
empty
```

## Additional information

```
Red Alert has encountered a fatal error.
Please refer to the crash logs and FAQ for more information.

Log files are located in /home/<username>/.config/openra/Logs
The FAQ is available at http://wiki.openra.net/FAQ
```

The game will open once and then fail to open after that. However I noticed that if I navigate to `~/.config/openra` and delete the `Content` folder, I can open it again only one time and it will download the content and successfully load once. This even works with saved games if they are present in `~/.config/openra` before that game load, provided that you delete the `Content` folder first.

I also get this when I open:
![image](https://user-images.githubusercontent.com/30937728/154868786-208c23b4-0ade-4e90-a507-dd152c3ce8a9.png)

**Comment by branttaylor** [comment]
![image](https://user-images.githubusercontent.com/30937728/154868786-208c23b4-0ade-4e90-a507-dd152c3ce8a9.png)

**Comment by Leo512bit** [comment]
AppImage corrupted?

**Comment by Mailaender** [comment]
Works on @openSUSE Leap and Tumbleweed.

**Comment by toose** [comment]
I have the same issue on ubuntu 20.04, though it hangs whilst loading at the splash screen. Like @branttaylor said, the game will load up and play flawlessly the first time around, but each subsequent load of the appimage hangs. Also, `exception.log` doesn't exist, and deleting `~/.config/openra/Content` and re-running the appimage will allow me to re-select `quick install` and play the game properly.

**Comment by necrashter** [comment]
I face the same issue on Linux Mint 21 Cinnamon, exactly as @toose described. Can reproduce with the latest stable AppImage `release-20210321`. I tried compiling the same version from source, but the issue persisted.

I compiled the latest `bleed` branch (commit 757c4d84c7f5d1d05e02119f668b0a2d8173fd76) and it fixed this issue. However, that version was unstable and kept crashing after starting the game for another reason.

**Comment by ghost** [comment]
Is it correct there is no update / workaround for this? 

In my case it throws a fatal error dialog in the splash screen. Removing content folder is not a workaround in my case. It happens again.

There is no `exception.log` created in my case as well.

Some general information:

Running on Ubuntu 22.04 LTS
Installed it by downloading the app image.
```
Platform is Linux
Engine version is release-20210321
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1,00
OpenGL renderer: Mesa Intel(R) HD Graphics 620 (KBL GT2)
OpenGL version: 4.6 (Core Profile) Mesa 22.0.5
Using default sound device
Internal mods:
	modcontent: Mod Content Manager (release-20210321)
	ra: Red Alert (release-20210321)
External mods:
	ra-release-20210321: Red Alert (release-20210321)
Loading mod: ra
Killed
```

**Comment by PunkPun** [comment]
Does the latest playtest work for you? https://www.openra.net/download/

**Comment by necrashter** [comment]
I got a new computer and installed Ubuntu 22.04. I can no longer reproduce this issue on latest stable AppImage release (`20210321`). It seems to work fine, `Content` folder doesn't cause a crash. I have no idea what fixed it.

@crittje I think you are facing a different issue if removing `Content` folder doesn't fix it. If you have a dedicated GPU, try running the game with it. Also, update your drivers if you have nvidia.

FYI, I have GTX 1650 which I use to run the game. I didn't try running it with integrated graphics card.

**Comment by ghost** [comment]
> Does the latest playtest work for you? https://www.openra.net/download/

@PunkPun Yes it does. Do not have any sounds during playtime. But that is something else (do have it on splash screen of release build). Thanks for the suggestion.

**Comment by ghost** [comment]
> I got a new computer and installed Ubuntu 22.04. I can no longer reproduce this issue on latest stable AppImage release (`20210321`). It seems to work fine, `Content` folder doesn't cause a crash. I have no idea what fixed it.
> 
> @crittje I think you are facing a different issue if removing `Content` folder doesn't fix it. If you have a dedicated GPU, try running the game with it. Also, update your drivers if you have nvidia.
> 
> FYI, I have GTX 1650 which I use to run the game. I didn't try running it with integrated graphics card.

Yes probably. Playtest does not seem to have this issue for me however.

**Comment by PunkPun** [comment]
There will be a new playtest soon fixing the sound issue on linux. In the meantime you could use https://github.com/pchote/OpenRA/releases/tag/playtest-20221224-audiofix

It's the current newest playtest with the sound fix
