### ISSUE TITLE
Pillboxes target armor units that they are ineffective against, instead of infantry; should be the opposite

### ISSUE THREAD

**Issue by StevenL-Up** [OpenRA/OpenRA#19959]
## Motivation

REQUEST MOTIVATION

When faced with multiple units, Pillboxes sometimes choose to target the units their weapons are not effective against, instead of targeting units they can kill.  In the specific instances I have seen, it seems that they choose the more expensive unit, regardless of effectiveness.

https://user-images.githubusercontent.com/66263703/158489910-49984911-d134-45d9-918d-ae6239e0dbb6.mp4

This may be a more general 'issue' affecting multiple weapon types, not just pillboxes.  Though it seems most egregious here.

## Proposed solution

PROPOSED SOLUTION
When faced with multiple units, Pillboxes should auto-target infantry and not heavily-armored vehicles.  They should target the units their weapons are most effective against, instead of wasting away at units they can barely hurt. I realize this can be fixed with actively choosing which units they target, but I think they should be smarter than that.

They should evaluate the available targets in range and choose the ones that they can be most effective against, instead of the most expensive unit.

## Side effects

EXPECTED SIDE EFFECTS

Pillboxes are more effective. Pillboxes do not target vehicles when infantry is present.

## Alternatives

ALTERNATIVES

**Comment by Leo512bit** [comment]
This can already be done with `AutoTargetPriority` but I wonder if this is a good idea because there is some strategy with getting pillboxes to target tanks as well as microing pillboxes to only shoot inf.

**Comment by ghost** [comment]
Interesting.
I remember there are target priorities in games like Starcraft 2 : https://liquipedia.net/starcraft2/Automatic_Targeting.
It works well in these games, and it doesn't seem to bother players, even professional ones, but I don't know how it would be in Red Alert.

The existing `AutoTargetPriority` used in the default rules seems to be more an "attack or don't attack" flag than a relative targeting priority between actors, including how they are threats to each other.
According to your video, from the pillbox POV, the bazookas, the grenadiers and the flamethrower would have a high ATP (say 3) while the riflmen, the flak and the APC would have a low one (say 1), so the pillbox would still attack the APC if there are no other threats in sight.
Dogs and unarmed buildings would have an ATP of 0 aginst each other.

For a modded map, it would be nice to generate automatically some sort of "relative ATP table" in the beginning of the game, related to the stats of the modded actors.
And, if it happens, an option to enable or disable this relative ATP would be useful in the game options.

**Comment by penev92** [comment]
Based exactly on the link you provided, and this part in particular:
> Void Rays target [Overlords](https://liquipedia.net/starcraft2/Overlord), [Roaches](https://liquipedia.net/starcraft2/Roach) and [Drones](https://liquipedia.net/starcraft2/Drone) all exactly the same, as none of them are considered threats

the pillbox should not discriminate between tanks and infantry, because they are both threats.

**Comment by tux314159** [comment]
also pillboxes are already OP, if you remove the need for pillbox micro... man oh man

**Comment by StevenL-Up** [comment]
> also pillboxes are already OP, if you remove the need for pillbox micro... man oh man

Pillboxes are only "OP" against massed infantry, and currently only if there are no armor units present.  Even with this change they can be mitigated by supporting your Inf with vehicles or aircraft, or by scouting so you know where they are and going around them.

**Comment by tux314159** [comment]
No they also OP against inf+tanks, if you manually select the infantry

**Comment by abcdefg30** [comment]
As explained above this is possible to do via custom rules, but won't be included for the default ruleset, as it has been deemed to much of "the game playing itself" in past discussions.
