### ISSUE TITLE
Unable to control group units in macOS 10.12.6

### ISSUE THREAD

**Issue by ykartsev** [OpenRA/OpenRA#19964]
Hi dear OpenRA community!
First of all, thank you for an amazing opportunity to remember my childhood and play this iconic game again with enhanced abilities!

I have an issue... Since I have macOS 10.12.6, I've installed version OpenRA-release-20210321-compat.dmg. Most of the hotkeys are working fine, but I'm unable to group using Ctrl+number. Shift+selection adds to selection fine, but grouping does not work.

Is this a known issue or am I doing something wrong?

Thank you in advance.

**Comment by dragunoff** [comment]
Hi @ykartsev, on MacOS the control group keys are hard-coded to <kbd>Cmd</kbd> so you should use that instead of <kbd>Ctrl</kbd>. Things will change in the next release because the control group keys will be exposed to the user for re-binding (see #19666).

**Comment by abcdefg30** [comment]
Closing as per @dragunoff comment. Let us know if you need further help.

**Comment by ykartsev** [comment]
Thank you @dragunoff, that worked!
