### ISSUE TITLE
Have an option in developer options to allow force loading incompatible maps.

### ISSUE THREAD

**Issue by Leo512bit** [OpenRA/OpenRA#19961]
## Motivation

Sometimes maps with large rules has lots of invalid syntax which makes impractical to fix for just updating it to the next version, so exception can be handy to just fix enough for the map to work. 

Right now there is only 2 ways to get an incompatible map loaded by OpenRA.

- The map editor
- Setting the map as a shellmap.

Both of these options are flawed; the issues with the shellmap are quite obvious, and if you load a map in the map editor sometimes it will load just fine and you won't get that desired crash.
## Proposed solution

![openraoptions](https://user-images.githubusercontent.com/64435704/159134606-6c1f13e6-9c60-4c89-be9a-d8458affb9fe.png)
Add an option in developer options to allow force loading incompatible maps.

## Side effects

Almost none because most players don't know how to enable developer options.

## Alternatives

N/A

**Comment by abcdefg30** [comment]
Considering the error is already known (and logged to `debug.log`) at that point, it would make more sense to display the error in the chat. I filed #19963 to track this. Meanwhile I suggest either looking into `debug.log` or using the `--check-yaml` command of the utility.

**Comment by Leo512bit** [comment]
For one if my maps I tried looking in `debug.log` but I couldn't find any error anywhere and using `--check-yaml` is not ideal because many mappers don't care about proper syntax and only care if the game just loads it which can make it challenging to update a map that many issues especially if you didn't wrote it and don't want to waste your time fixing syntax.
