### ISSUE TITLE
d2k-a.yaml 、d2k-a.yaml、d2k-a.yaml中的WAITGAME.AUD都错写为WAITGAME.A

### ISSUE THREAD

**Issue by hnsylzg** [OpenRA/OpenRA#19984]
OpenRA\mods\d2k\installer
中的d2k-a.yaml 、d2k-a.yaml、d2k-a.yaml中的
^SupportDir|Content/d2k/v2/Music/WAITGAME.A: WAITGAME.AUD
WAITGAME.A应为WAITGAME.AUD

**Comment by abcdefg30** [comment]
The installer can only install from the English sources.

**Comment by pchote** [comment]
I believe this was a duplicate of #19299, which has been fixed by #19176.
