### ISSUE TITLE
Align OpenRA d2k balance with original D2k

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#20021]
I installed old Dune2k recently to compare original D2k balance with OpenRA d2k. And found some significant differences.
firstly lets compare some units VS units from original D2k with OpenRA:

(gifs have different speeds because of upload size restrictions - ignore that)

Siege tank VS infantry in original D2k:
![origD2k siegeVSinfantrygif_optimized](https://user-images.githubusercontent.com/100044015/166301032-ddcbc8e4-a8a0-49db-ab94-2bc10ea89c9c.gif)

Siege tank VS infantry in OpenRA:
![openraD2k siegeVSinfantry_optimized](https://user-images.githubusercontent.com/100044015/166301097-551355ae-c3e4-414e-8efd-a030c83b667d.gif)

Missile tank VS tank  original D2k:
![origD2k missileVStank_optimized](https://user-images.githubusercontent.com/100044015/166301166-aa1f0782-7b39-4747-a8b9-3a31449ada1f.gif)

Missile tank VS tank  in OpenRA:
![openraD2k missileVStank_optimized](https://user-images.githubusercontent.com/100044015/166301246-82f702d3-e5fa-4aa2-9a77-a639c20e3f3b.gif)

Infantry VS infantry orig. D2k:
![origD2k infantryVSinfantryblob_optimized](https://user-images.githubusercontent.com/100044015/166301299-059614c9-69dc-4dd0-b71d-bdce5dcaf56f.gif)
Infantry VS infantry OpenRA:
![openraD2k infantryVSinfantry_optimized](https://user-images.githubusercontent.com/100044015/166301350-6373c7e8-804a-4156-b931-1f972603cc29.gif)

In this table I put some most noticing differences:

![table01](https://user-images.githubusercontent.com/100044015/166301611-ae5e4acb-9dc4-46de-9baa-51d84a6f86e6.png)

PROPOSED SOLUTION

**Missile tank**

 To fix Missile tank I figure that best way is  set _DamageCalculationType_ to **HitShape**. With this you dont need change damage and FallOff properties. But you must set correct **Hitshapes** to all units.  After some testing I end with this nubmers: 
Vehicle HitShape: 300
lightVehicle HitShape:  240 
infatry HitShape: 128
Due fact that trikes and quad have no splash damage on nearby units, I guess that they hitshape is  lower that HitShape on other vehicles. From my test I see that Hitshape has no effect on ClosestTargetablePosition so other warheads stay unaffected with this change.
Also inaccuracy for Missile tank unit is lower compare to other units, but it seem it still rise with range a little. 

table02: Missile tank before/after
![table02](https://user-images.githubusercontent.com/100044015/166302418-47dcc525-5ead-45bc-9cd0-7bf3ce7a95d0.png)
* only  1 or 2 units was affected.
You can see that besiced  infantry the Missile tank representation is quite accurate now.

**Siege tank:** 

![origD2k siegeVSinfantryblob_optimized](https://user-images.githubusercontent.com/100044015/166302678-4d44e4c4-c837-4712-a82e-b711f81fdfa8.gif)

From gif u can see that Siege tank Warhead have cca 2c0 AoE. You can also see that prone effect on infantry applies randomly. This cannot by done in OpenRA yet I propose to set prone effect just to  1c112.
Table03: siege tank before/after
![table03](https://user-images.githubusercontent.com/100044015/166303013-05e63d63-fef4-4f77-8301-7f541d9d8702.png)

**Light infantry:**

In original D2k there are differences in damage when unit is shooting Horizontally/vertically and when it shooting by diagonal. In table04 the ‚→‘ indicates what damage unit cause while shooting horizontally/vertically  and ‚↗‘ what damage is caused when shooting on diagonals.
From table u can see that light infantry has problem only in InfantryVSinfantry case.  
One solution to this is set damage VS none  to 0 on [Warhead@1Dam] and add second warhead to LMG that affects only none armor with this properties:
[LMG_newWarhead.txt](https://github.com/OpenRA/OpenRA/files/8605282/LMG_newWarhead.txt)

Table04: Light infantry before/after
![table04](https://user-images.githubusercontent.com/100044015/166303997-08a2f405-5369-4e4d-bc96-d3d04c665951.png)

ALTERNATIVES

There are alternative approach how to fix this issues, but this one works and are pretty close to original D2k
My yaml code:
[Weapons changes.txt](https://github.com/OpenRA/OpenRA/files/8605394/Weapons.changes.txt)
[rules changes.txt](https://github.com/OpenRA/OpenRA/files/8605395/rules.changes.txt)

FINAL THOUGHTS

If you need more evidence let me know I will post them here.
I will go throw every unit so we can have as close d2k as possible. But because its lot of work and testing I will add following units to comments below. I’m expecting to be finished at the end of this week.
After this is finish and new play test will come out, I would like to move with D2k balance beyond original d2k balance. Because original D2k was everything but not well balanced ;)

**Comment by PunkPun** [comment]
#17972 was the last attempt at balancing D2K

**Comment by pchote** [comment]
#17972 showed that inaccuracy introduces a significant element of randomness to the damage applied in the original game. How are you controlling for this here?

**Comment by Porenutak** [comment]
I spend several hours doing things like this:
![origD2k infantryVSinfantryblob_optimized](https://user-images.githubusercontent.com/100044015/166329298-a2916f85-8dea-48f3-bffa-750f080552d3.gif)
and everytime I'm checking what is remaining HP on units that are next to the killed unit. What is average number of shoots to kill unit. (its usually the same number)etc. 
But properties as inacurracy, range, FallOff are already done well. The problem with #17972 was that it didnt work in every situation. 
From my tables you can see that it works fine in most cases. 
It works perfectly on Trooper unit. It works perfectly with light infantry (expect infantry VS infatry)
Only problem with SiegeTank was wrong AoE.
Missile tank is only case up to date where inacurracy and ClosestTargetablePosition dont work . Not if dont raise Damage or AoE

**Comment by Porenutak** [comment]
due to archiving, I'm posting here  all documentation that I already posted on Discord also  with test map where you can test proposed solution for some units.
[sonic tank.odt](https://github.com/OpenRA/OpenRA/files/8694947/sonic.tank.odt)

[Combat tank and others.odt](https://github.com/OpenRA/OpenRA/files/8694949/Combat.tank.and.others.odt)

[siege.odt](https://github.com/OpenRA/OpenRA/files/8694951/siege.odt)

[infantry.odt](https://github.com/OpenRA/OpenRA/files/8694941/infantry.odt)

[Missile tank.odt](https://github.com/OpenRA/OpenRA/files/8694942/Missile.tank.odt)

[01originald2kbalance.zip](https://github.com/OpenRA/OpenRA/files/8694959/01originald2kbalance.zip)
