### ISSUE TITLE
 TrustFailure prevents installation

### ISSUE THREAD

**Issue by RossBoylan** [OpenRA/OpenRA#20051]
## Issue Summary

Using downloaded AppImage on Debian 11 on the initial run it wants to download additional content.
Quick Install leads to `Download failed: Error: TrustFailure (Authentication failed, see inner exception.)`

Though not directly relevant to this bug, I tried the full install with a RA 95 CD; it was never recognized.

## Reproduction

1. Running current Debian stable release, 11, aka bullseye on amd64 architecture. regular user.
2. Download https://github.com/OpenRA/OpenRA/releases/download/release-20210321/OpenRA-Red-Alert-x86_64.AppImage.
3. Set executable bit and launch.
4. Select Quick Install.
5. Indicated error occurs.

~/.cache/.config/openra/Logs/install.log is
```
Fetching mirrors from http://www.openra.net/packages/ra-quickinstall-mirrors.txt
Downloading https://republic.community/hosted/files/command-and-conquer/openra/ra-quickinstall.zip
Deleting temporary file /tmp/hmpiaunk.dfm
Download failed: Error: TrustFailure (Authentication failed, see inner exception.)
```
perf.log is the only other non-0 length log file.  I don't see an inner exception anywhere.

## Expected behavior

I expected the program would download the files it needed and continue to play the game.

I installed OpenRA on a Debian 10 system a few months ago and had no problems with the quick install.  I was similarly unable to use my CD to provide full content.

## Environment
I think the AppImage is mostly self-contained, but I'll note that I see no installation of mono or .net packages; they don't even seem to be available for Debian 11 (as Debian packages in main, contrib, or non-free).  I have installed VSCode direct from MS; it was on the Debian 10 system also.  VSCode may include .net.

**Comment by RossBoylan** [comment]
The network environment also differs from my previous, successful, installation.  Before the system that ran the game was also the primary router, firewall, DNS for my local network.  In the current, failing, setup, most of the functionality is provided by a Deco router.  Maybe it's blocking some packets that got through before?

**Comment by RossBoylan** [comment]
On a hunch, I installed the `ca-certificates-mono` package on the host system, which installed a lot of `mono` dependencies.  Now I can do the quick install and start the game.

```
root@barley:~# aptitude install ca-certificates-mono
The following NEW packages will be installed:
  ca-certificates-mono cli-common{a} libmono-btls-interface4.0-cil{a} libmono-corlib4.5-cil{a} libmono-corlib4.5-dll{a} libmono-i18n-west4.0-cil{a} libmono-i18n4.0-cil{a} 
  libmono-security4.0-cil{a} libmono-system-configuration4.0-cil{a} libmono-system-core4.0-cil{a} libmono-system-numerics4.0-cil{a} libmono-system-security4.0-cil{a} 
  libmono-system-xml4.0-cil{a} libmono-system4.0-cil{a} mono-4.0-gac{a} mono-gac{a} mono-runtime{a} mono-runtime-common{a} mono-runtime-sgen{a} 
0 packages upgraded, 19 newly installed, 0 to remove and 0 not upgraded.
Need to get 7,255 kB of archives. After unpacking 24.0 MB will be used.
```

I don't know if the certificates themselves or the other `mono` stuff did the trick.  

I'm not sure what the `{a}` means in the new package list, and can't find it documented.  I'm guessing it just means automatic install, as opposed to `ca-certifcates-mono`, which is manually requested.

The system was built up from a minimalist `debootstrap` installation;  the necessary packages might be present anyway in a more standard installation.

Possible significance:
  1. Add a note, on the web and/or in the instructions when you click, noting the need to install `ca-certificates-mono`.  The scope of that is unknown to me outside of current stable Debian 11.  Probably other Debian derivatives (Ubuntu) will behave similarly.
  2. Include the necessary files in the AppImage.

**Comment by pchote** [comment]
.NET 6 has a different networking implementation to mono, so this has hopefully already been indirectly fixed for the next release.

**Comment by Mailaender** [comment]
The `ca-certificates-mono` package probably has a call to `cert-sync /etc/ssl/ca-bundle.pem` or wherever Debian stores the certificate.

**Comment by Mailaender** [comment]
Can you check if the problem persists with https://github.com/OpenHV/OpenHV/releases? It is already serving .NET 6 AppImages for a while now.

**Comment by RossBoylan** [comment]
@Mailaender Since I already did something to get past the problem, I don't think I can run much of a test.

I also do not follow @pchote remarks about .NET 6.

I thought the image was self-contained, and so am surprised that it apparently depends on the host system setup.

**Comment by Mailaender** [comment]
AppImages are not fully self-contained. They require some libraries like FUSE on the host system and apparently the Mono certificate sync from a previous installation. I am closing this as Mono was deprecated. #19780
