### ISSUE TITLE
Player Mute / Disable chat button

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#20073]
Related issues #13182, #7448, #5775

I'm thinking of adding such a feature but first want to discuss how should it work. 

I think the best approach would be to add a personalised option to every player. There should be a mute all button somewhere. Mockup:

<img width="998" alt="mockup" src="https://user-images.githubusercontent.com/37534529/173636439-ad4023d1-b7e1-4da8-be61-60ed5a9a31e6.png">

The mute would be only per game / per match. But for replays we need an additional option, some people don't want to see chat right of the bat. Perhaps a checkbox to mute chat in replays could be inside `Advanced` options.

Now onto how the mute should look like. I can think of a couple of options. 
- Message isn't seen
- It is seen that a message has been sent, but contents aren't shown e.g. `20:18 Pillbox: muted`. No sound is played but one can unmute and then read the contents. Multiple messages in a row could stack like `Game Event Notifications`
- Second option normally, first option in replays when the global mute is passed.

**Comment by PunkPun** [comment]
Of course the option shouldn't exist for AI, in skirmish lobbies we might want to not even leave UI space for it. Or perhaps the option could just be greyed out, so we could avoid UI overheads

**Comment by pchote** [comment]
The speaker icon is associated with sound. This should use a 🗨️ style icon instead.

**Comment by PunkPun** [comment]
#6138 related

**Comment by CortexReaver** [comment]
May be go further and try to implement blacklists (blocking by account and IP)? Waiting for such feature for years.

**Comment by PunkPun** [comment]
This is an unrelated issue

**Comment by CortexReaver** [comment]
> This is an unrelated issue

k, sorry. Then I'll create a separate issue later.
