### ISSUE TITLE
Add basic desync tests

### ISSUE THREAD

**Issue by matjaeck** [OpenRA/OpenRA#20085]
> I usually start an 8 AI game with two teams on max speed and max starting units with two spectating clients. Without the fix it usually desyncs within at least 5 minutes.

**Comment by abcdefg30** [comment]
This would require running the game on the test runners. I think constructing basic test cases for other things by using Lua scripted maps was already discussed, but I don't remember if an issue already exists for that. As for desyncs itself, the seem to be rare enough that we don't really need an extra test, but it probably wouldn't hurt either.

**Comment by Mailaender** [comment]
https://grumpygamer.com/unit_testing_games is possible but really hard to setup especially this.

**Comment by matjaeck** [comment]
Closed as too hard.
