### ISSUE TITLE
Enable discussion board for this repository?

### ISSUE THREAD

**Issue by ShikiSuen** [OpenRA/OpenRA#20096]
Github supports discussion board feature for each repository.

I would like to ask some questions regarding your experiences of cross-platform development with C#. However, I'm afraid that such question is not suitable in the issue tracker. (Nor suitable in other OpenRA-related communities mentioned in this repo since my question might be too geek).

**Comment by PunkPun** [comment]
It's probably best suited for https://discord.openra.net/

**Comment by ShikiSuen** [comment]
@Punsho Thanks for your recommendation. My thoughts:

1. Discord is hard to track discussion records if someone is almost not using Discord at all. It just takes too many steps to log in Discord and click through chatrooms just for seeing whether there's a reply. // GitHub discussions make things much simpler.
2. Discord is banned by GFW.
3. Discord is only suitable for game-related discussions. For developer-related discussions, especialy regarding hard technique topics like "How did you people achieve cross-platform key input event handling in OpenRA?", it is likely to be either ignored or flown by other discussions.

**Comment by Mailaender** [comment]
There is a @phpBB based https://forum.openra.net/ already.

**Comment by ShikiSuen** [comment]
@Mailaender Thanks. I forgot that I already had an account there. :)
I saw that there is no general development subforum  but only a mod subforum. Let me assume that the mod subforum is the right place. Please let me know if that's the wrong place.

Closing this issue now since that it appears that my suggestion has been denied.

**Comment by PunkPun** [comment]
> I saw that there is no general development subforum but only a mod subforum. 

That's because most of the dev talk happens on discord
