### ISSUE TITLE
Question: how to generate synchronized reports on muti-players without using dedicated sever?

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20090]
How to generate synchronized reports on muti-players without using dedicated sever?

and if I open 2 players on 1 computer, will the synchronized report conflict with each other (like filename) ?

**Comment by abcdefg30** [comment]
Go to your `settings.yaml` and add `EnableSyncReports: True` in the `Server` section.
```
Server:
	EnableSyncReports: True
```

**Comment by dnqbob** [comment]
> will the synchronized report conflict with each other (like filename) ?

It does conflict
