### ISSUE TITLE
Lobby and Debug Menu options are unresponsive

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#20102]
the culprits are in https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Widgets/Logic/Lobby/LobbyOptionsLogic.cs#L107-L110

I don't really know how this should be fixed. I would imagine we'd have to use an intermediate value for checkbox. It would toggle instantly and then once we have confirmation from the server, would set the intermediate to the correct value

**Comment by PunkPun** [comment]
Many of the debug menu options are also unresponsive, as mentioned in #11585

**Comment by anvilvapre** [comment]
Related #18833
