### ISSUE TITLE
Feature:custom mod use lua script

### ISSUE THREAD

**Issue by annopnod** [OpenRA/OpenRA#20126]
lua script is dynamic but yaml is static 
1.superweapon or weapon exsimple Prism Forwarding  see ares (https://ares-developers.github.io/Ares-docs/new/buildings/prismforwarding.html)
2.ai script

**Comment by abcdefg30** [comment]
I'm not sure I understand the request. Writing traits in Lua is not supported/feasible. (Traits are created using C#.) The second point is covered by #4947. Are there any specific Lua functionalities you are missing/asking about?

**Comment by Porenutak** [comment]
>  Are there any specific Lua functionalities you are missing/asking about?

maybe off topic, but what I really miss, is able to call LUA fuction by actor it self when some condition is granted (with reference to that actor in called fuction). Right now the only way how to do that is Sorting all actors, for every player, in every **tick** with _GetActorsByType_ and check if condition is there. Which is performance heavy and cause lags in every MP games after 10 min.

**Comment by annopnod** [comment]
oh can use c# Traits. 
ai script i not sure  LUA fuction with jit (LuaJIT) add performance

**Comment by abcdefg30** [comment]
Closing as answered.
