### ISSUE TITLE
Delay first worm appearance on the map.

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#20153]
Worms start spawning right after game start, which really broke every early game. Loosing first harvester or delaying your eco in early game leave you very behind. But when worms start spawn after 10 or 15 min in game its not as big deal. (it dont affects eco so much as you have many harvesters at this point or you can use some cheap trike to get rid of worm)

Proposed solution

Implement new lobby option that allows set you delay for worm first appearance. This is already done in lot of custom maps via LUA script, but I thing it’s good idea to have this ability for all maps by default.

Alternative 

Hardcode spawn delay for first worm  somewhere between 8-15 minutes.

![wormspawndelay](https://user-images.githubusercontent.com/100044015/181774618-86bcb485-8c9a-464b-a644-d25b1adb9950.png)

**Comment by PunkPun** [comment]
I think the following should be considered

- Remove Worms checkbox
- Rename dropdown to `Spawn Worms`
- Add an option `never`
- Rename other options with the style of `after 5 min`

**Comment by Porenutak** [comment]
sure why not

**Comment by Porenutak** [comment]
preview with Punks suggestions:

![Screenshot (160)](https://user-images.githubusercontent.com/100044015/190649247-d0dd7078-8501-4aeb-b41b-bba49f537bb2.png)

**Comment by PunkPun** [comment]
Related #16631
