### ISSUE TITLE
Which cost more? GlobalLightingPaletteEffect or IgnoreWorldTint

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20166]
Now we have 2 ways on making the sequence unaffected by world light:
1. we can set up a palette that ignores light by using `GlobalLightingPaletteEffect`
2. we can simply add `IgnoreWorldTint: true` to the related sequence

My question is, which one is more performance friendly?

**Comment by anvilvapre** [comment]
You could measure it?

The second seems faster as it avoids applying the GlobalLightingPaletteEffect - which is an IPaletteModifier trait - each render frame. (See WorldRendere.RefreshPalette). 

The second - tint - results in a modifier on the alpha channel of - all pixels of - the sprite. 

Unfortunately the game will each render tick create for each renderable a new renderable object. I.e for image renderables each frame a SpriteRenderable. As a constructor argument the sprite renderable will receive a palette and tintModifier argument/modifier based on 2. Each time a new sprite renderable is rendered - with will always some tint modifier. On top of that pallette modifiers will be applied. Palette modifiers will be applied on each color in the palette. 

Someone else should confirm.

**Comment by dnqbob** [comment]
Thanks.

> IPaletteModifier trait - each render frame. (See WorldRendere.RefreshPalette).

So this one seems to consume more cpu resource for there is 256 colors for each palette.

**Comment by pchote** [comment]
Closing as resolved.
