### ISSUE TITLE
Harvesters reroutes to Refinery are broken on bleed

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#20162]
DESCRIPTION
Harvesters only go to the nearest refinery even there are more refineries near by. This happens in D2k mod in bleed.
I tried to increase UnloadQueueCostModifier and reduce MaxUnloadQueue, but didnt see any difference.
![d2k-2022-08-04T084904957Z](https://user-images.githubusercontent.com/100044015/182815356-66cd62de-e37e-4055-a506-5b3e8d13203e.png)

harvester to refinery routing on bleed: 

https://user-images.githubusercontent.com/100044015/182817586-9f06d96a-af5c-4833-a17a-dbc38d31dd8b.mp4

expected behavior (20210321 release):

https://user-images.githubusercontent.com/100044015/182816054-41892ff3-c7c4-4d67-8e8a-12fde72081ed.mp4

**Comment by darkademic** [comment]
I was getting slightly different behaviour on RA bleed. Harvesters would always return the the oldest refinery, regardless of which is closest. You could order a harvester to return to a specific refinery, but once it unloaded and returned to the field it forgot the last refinery and reverted to the oldest one again.

**Comment by PunkPun** [comment]
> I was getting slightly different behaviour on RA bleed. Harvesters would always return the the oldest refinery, regardless of which is closest. You could order a harvester to return to a specific refinery, but once it unloaded and returned to the field it forgot the last refinery and reverted to the oldest one again.

I have a suspicion that it's a regression from #19591. https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Harvester.cs#L214 
relies on paths being sorted by distance, but if it isn't theoretically you should get the behaviour you are currently describing

**Comment by PunkPun** [comment]
theory confirmed, harvesters search properly before #19591 was merged
