### ISSUE TITLE
Ability to disable power for production buildings

### ISSUE THREAD

**Issue by CortexReaver** [OpenRA/OpenRA#20193]
Original CNC has it, may be is there some technical reason why it still not implemented yet? Also sorry if it was closed already, but I unable to find it.
Multiple behavior variants for disabled production building:
1) Able to produce units from disabled factory (can set as primary), slowing down the production line.
2) Unable to produce units from disabled factory completely (cannot set as primary), slowing down the production line.
3) If set primary, production speed become limited for corresponding unit type. There is a possibility to cheat, when you set as primary fully powered building and then quickly switching to disabled one.

Can't quite remember how it was in original, but I'll go with first one.

**Comment by abcdefg30** [comment]
Tiberian Sun was the only one of the earlier C&Cs to allow powering down production buildings, see #10188.
