### ISSUE TITLE
Crash when starting a game

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#20194]
Likely a regression from #19752 as the code crashes in OrderBuffer. 

To reproduce the crash

- launch the game
- open Skirmish
- open the map browser
- click OK without selecting a map
- click Start Game.

[exception-2022-08-15T160012Z.log](https://github.com/OpenRA/OpenRA/files/9338837/exception-2022-08-15T160012Z.log)

This is most likely related to #20057.

**Comment by PunkPun** [comment]
It appears that when you follow this sequence, `Conns` are dropped in `Server.cs`

**Comment by PunkPun** [comment]
There are multiple check to avoid picking the same map again, my theory is that some crucial code gets blocked. Checks are all over the place and I haven't been able to find the culprit yet

**Comment by teinarss** [comment]
Easiest solution would be to just disable the ok button if no new map is selected,
