### ISSUE TITLE
Different Building Mechanics

### ISSUE THREAD

**Issue by ben132** [OpenRA/OpenRA#20191]
This might be possible anyway, but I haven't seen it in any mod, so it would be interesting to be able to create a Faction that builds differently like that of Starcraft and later C&C games.  For example, (SC) Zerg build units that become buildings and (RA3) Soviets build on locations rather that prebuilding, whereas (RA3) Allies build like standard of OpenRA, prebuild then place on location.

**Comment by abcdefg30** [comment]
This is already possible, and there are even mods with custom traits for this. It is unlikely this is getting implemented in the default mods however.
