### ISSUE TITLE
Surrender - give buildings

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#2022]
When one players quits, surrenders, or get disconnected, they should give their units to team players... Random, the weakest, or a list they can choose from...
##

**Comment by GSonderling** [comment]
How about giving those buildings to AI instead? It wouldn't be effective as a human player, but it would at least fight.

From my experience in RTS, when I get bunch of buildings suddenly, I need some time to take account of them. Not to mention the obvious fact that my base just got way larger and harder to defend. 

Timeo Danaos et dona ferentes, if you know what I mean.

**Comment by Carko** [comment]
@GSonderling that is true, but on the other hand, you would have to completely change your strategy (the one you were working on with a teammate) as the AI won't care about what you intended to do.

I don't think there is a win-win situation here - you either get to manage more resources suddenly, you lose them completely, or AI (which you have no control of) gets them.

**Comment by MustaphaTR** [comment]
I should note that this is possible just with yaml changes now, at least to Neutral, so people can capture an use them.
