### ISSUE TITLE
Saving a game with an empty name

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#20233]
## Issue Summary
It's possible to save a game with an empty name. The save file is valid and can be loaded but it's not great UX.

## Reproduction
1. Start a skirmish game.
2. Open save dialog.
3. Erase the name in the text field.
4. Save the game.

## Expected behavior
A save game with an empty name should not be allowed - the save button should become disabled or a prompt should be displayed.

## Screenshots / Screen recordings / Replays
![image](https://user-images.githubusercontent.com/1355810/187426959-b4c146f1-dba3-45e0-ac06-fc2db633cf37.png)
![image](https://user-images.githubusercontent.com/1355810/187427012-ff6348ef-a368-45a6-b482-297d2582b3b1.png)

**Comment by The-Zen-Cat** [comment]
Submitted pull request to fix issue by disabling save button until name is entered.
