### ISSUE TITLE
Saving a map without a name or author

### ISSUE THREAD

**Issue by dragunoff** [OpenRA/OpenRA#20236]
## Issue Summary
The game won't stop you from saving a map without a name or an author.

## Reproduction
![image](https://user-images.githubusercontent.com/1355810/187448684-87de87fb-8161-45de-a56f-e4bf99ce3b53.png)
![image](https://user-images.githubusercontent.com/1355810/187449025-e6daba68-c3ac-4c30-ac4e-3dfaf2e74856.png)

## Expected behavior
The game should disable the "Save" button or display a prompt.

**Comment by The-Zen-Cat** [comment]
I have reproduced and fixed this issue!  I'll get it to a Pull request shortly.
