### ISSUE TITLE
Shroud does not render when FoW is disabled.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#20243]
Looks like https://github.com/OpenRA/OpenRA/pull/19599 regressed more stuff. Noticed while engine updating Sole Survivor, which has FoW disabled by default.

![resim](https://user-images.githubusercontent.com/7933210/187904212-a6e85f2a-4b93-4c24-a4d7-eaf95f337053.png)

**Comment by PunkPun** [comment]
@anvilvapre
