### ISSUE TITLE
IAcceptResource to maintain Occupance count

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#20288]
`ClosestProc` in `OpenRA.Mods.Common/Traits/Harvester.cs` uses quite an expensive query to calculate how much harvesters are already associated with a `IAcceptResources` trait.  It queries all harvesters to see if they are linked to IAcceptResources trait - for each trait. 

An optiomization would be to just maintain an Occupancy count per `IAcceptResources`. Harvesters would have to increment and decrement this value. 

The value indicates how many harvesters are associated with the trait. Allowing the spreading of harvesters over traits/refineries.

Relevant whenever a harvester tries to find a new refinery.

**Comment by PunkPun** [comment]
That's part of the plan with the docking refactor. I'm waiting for a few PR's to be merged before I get to optimising it
