### ISSUE TITLE
Enable Battlefield News for Community Events

### ISSUE THREAD

**Issue by KautionORA** [OpenRA/OpenRA#20298]
Title is pretty obvious, Battlefield News hasn't changed since the launch of the latest version (a year and a half ago)

we've had discussions about this and nobody seemed to be against it at the time, Using Battlefield news for Events like RAGL or tournaments of any kind would be an ideal way of informing literally every single person that opens up the game, as we all know most players are not in our discords or are active on the forum.

this is a feature that is already in the game but isn't being used, would be nice to put it to good use.

**Comment by pchote** [comment]
Battlefield News *was* used for events like RAGL and map contests, but the community stopped submitting posts for it.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRAWebsiteV3/blob/master/gamenews is the file you are looking for. Closing here.
