### ISSUE TITLE
Allow weapon with no damage warheads to be fired

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20348]
## Motivation
On third part mod we have many weapon that only apply a condition or display an effect, instead of using a damage warhead. However, we need to code every weapon a damage warhead in order to make it working

## Proposed solution
Change:
![image](https://user-images.githubusercontent.com/13763394/194285005-fb4158ac-2906-45df-825a-108db138948f.png)
 in `AttackBase` to only checkout if there is any valid `Armament` to be used

## Side effects
Should not have any side effect right?

**Comment by PunkPun** [comment]
it looks like this check was added 8 years ago https://github.com/OpenRA/OpenRA/commit/c972b39687b5cabfa48ea5b5c19e77803fe3acf5

**Comment by dnqbob** [comment]
> it looks like this check was added 8 years ago [c972b39](https://github.com/OpenRA/OpenRA/commit/c972b39687b5cabfa48ea5b5c19e77803fe3acf5)

Looks like this check is part of damage calculation on `AttackBase` at that time.
