### ISSUE TITLE
Cache armaments in AttackBase

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20358]
In `AttackBase`, I find `Armaments` is a delegate, and be used frequently. I wonder if we change it to an array that directly caches armaments, will it be a good performance improvement?

**Comment by PunkPun** [comment]
AttackBase could cache in a way that Armaments notify the class on becoming enabled or disabled

**Comment by dnqbob** [comment]
oh I mistakes that

**Comment by PunkPun** [comment]
I meant that it could be implemented in that way. I'm not sure how it actually works
