### ISSUE TITLE
Crash due to modified collection on actor destroyed

### ISSUE THREAD

**Issue by benjamincburns** [OpenRA/OpenRA#20355]
## System Information
- Operating System:  macOS 12.6
- OpenRA Version: bleed branch, commit 7f677f1
- OpenRA Mod: ra
- Source: self-compiled
- Mono version: 6.12.0.122

## Exception log

```
OpenRA engine version {DEV_VERSION}
Red Alert mod version {DEV_VERSION}
on map b884e9d4e8e59f89b0f338e32fdc52a0a51b6ae4 (Desert Shellmap by Scott_NZ).
Date: 2022-10-08 21:16:48Z
Operating System: OSX (Unix 21.6.0.0)
Runtime Version: Mono 6.12.0.122 (2020-02/c621c35ffa0 Wed Feb 10 00:51:43 EST 2021) CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Collection was modified; enumeration operation may not execute.
  at System.Collections.Generic.Dictionary`2+Enumerator[TKey,TValue].MoveNext () [0x00013] in <36514b14425c4337b446653c547aa9c3>:0 
  at OpenRA.Scripting.ScriptObjectWrapper.Unbind (System.Type targetType) [0x00042] in /Users/bburns/projects/OpenRA/OpenRA.Game/Scripting/ScriptObjectWrapper.cs:66 
  at OpenRA.Scripting.ScriptActorInterface.OnActorDestroyed () [0x0002c] in /Users/bburns/projects/OpenRA/OpenRA.Game/Scripting/ScriptActorInterface.cs:54 
  at OpenRA.Actor.<Dispose>b__90_0 (OpenRA.World w) [0x00065] in /Users/bburns/projects/OpenRA/OpenRA.Game/Actor.cs:423 
  at OpenRA.World.Tick () [0x001ba] in /Users/bburns/projects/OpenRA/OpenRA.Game/World.cs:449 
  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x000c4] in /Users/bburns/projects/OpenRA/OpenRA.Game/Game.cs:624 
  at OpenRA.Game.LogicTick () [0x00041] in /Users/bburns/projects/OpenRA/OpenRA.Game/Game.cs:648 
  at OpenRA.Game.Loop () [0x00129] in /Users/bburns/projects/OpenRA/OpenRA.Game/Game.cs:820 
  at OpenRA.Game.Run () [0x0003c] in /Users/bburns/projects/OpenRA/OpenRA.Game/Game.cs:873 
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00010] in /Users/bburns/projects/OpenRA/OpenRA.Game/Game.cs:308 
  at OpenRA.Launcher.Program.Main (System.String[] args) [0x00046] in /Users/bburns/projects/OpenRA/OpenRA.Launcher/Program.cs:32 
```

## Additional information
Crash occurs not long after running the game. Sometimes it seems to run for longer than others before crashing, but I hadn't made it into an actual game session when any of the crashes occurred.

Not sure if it matters, but this is running on an M1 Pro.

**Comment by benjamincburns** [comment]
This seems to be a mono bug.

The code in question is [here](https://github.com/OpenRA/OpenRA/blob/a2a34dafdec5c10c233fa65cd52e5519e6d1b1f3/OpenRA.Game/Scripting/ScriptObjectWrapper.cs#L66-L68).

```
protected void Unbind(Type targetType)
{
	foreach (var m in members)
		if (targetType == m.Value.Target.GetType())
			members.Remove(m.Key);
}
```

This is totally fine in netcore 3.0+, as mutating a dictionary using the `Remove` or `Clear` methods during enumeration is fine:

>An enumerator remains valid as long as the collection remains unchanged. If changes are made to the collection, such as adding elements or changing the capacity, the enumerator is irrecoverably invalidated and the next call to [MoveNext](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.enumerator.movenext?view=net-6.0) or [IEnumerator.Reset](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.enumerator.system-collections-ienumerator-reset?view=net-6.0) throws an [InvalidOperationException](https://learn.microsoft.com/en-us/dotnet/api/system.invalidoperationexception?view=net-6.0).
>
>**.NET Core 3.0+ only: The only mutating methods which do not invalidate enumerators are [Remove](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.remove?view=net-6.0) and [Clear](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.clear?view=net-6.0).**

[Source](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.getenumerator?view=net-6.0#remarks) (emphasis mine).

It would appear that mono doesn't implement this behaviour, however.

I tried modifying the code to avoid modifying the dictionary during enumeration. Unfortunately there doesn't seem to be any great way to do this without creating another temporary collection of KVPs or key strings. Mono's stop-the-world garbage collection doesn't really put up with this very well however, and game performance seems to degrade over time.

**Comment by pchote** [comment]
Likely a regression from #20150.

**Comment by benjamincburns** [comment]
```
protected void Unbind(Type targetType)
{
    var toRemove = new List<string>();
    foreach (var m in members)
        if (targetType == m.Value.Target.GetType())
            toRemove.Add(m.Key);
    foreach (var k in toRemove)
        members.Remove(k);
}
```

Here's the modified `Unbind` that avoids the issue, but introduces too much object churn IMO to be useful under mono.

**Comment by benjamincburns** [comment]
Looks like I'm incorrect to call this a mono bug, as mono is intended to track .NET framework, not .NET core. Removing the dependency on mono for unix-like systems would likely be ideal.

https://stackoverflow.com/a/58618694/203705

**Comment by abcdefg30** [comment]
> Here's the modified `Unbind` that avoids the issue, but introduces too much object churn IMO to be useful under mono.

I propose #20356 which disables this code path for our default .NET 6 builds, and re-uses the `toRemove` list to save some performance.

**Comment by anvilvapre** [comment]
Interesting. I was aware when implementing and read in the docs it had to be save from a certain .net version. Later Roosterdragon made a remark about it. 

How does it relate to the crash info mentioning it uses mono 6? Yet in the source you check for mono 5 or greater?
