### ISSUE TITLE
Aircraft with IdleBehavior: ReturnToBase hang midair when last actor they can return to gets sold

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#20373]
![hangingaircraft](https://user-images.githubusercontent.com/48881353/195992836-3b123213-3a13-4fe3-abc9-05ecff4b4a99.gif)
If you set IdleBehavior: ReturnToBase inside an Aircraft:, then sell the last building that actor can return to, this issue happens where they all hang midair.

**Comment by ThomasChr** [comment]
I think behavior "ReturnToBase" can only be set by a mod, because it's hardcoded in Aircraft.cs - correct?

**Comment by ThomasChr** [comment]
This would be a very rough first try:
```
Index: OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs b/OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs
--- a/OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs	(revision acc2c11e6952e342546e84adb06cdad28839c699)
+++ b/OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs	(date 1666104704613)
@@ -104,7 +104,7 @@
 				}
 
 				// Prevent an infinite loop in case we'd return to the activity that called ReturnToBase in the first place. Go idle instead.
-				self.CancelActivity();
+				QueueChild(new FlyIdle(self, aircraft.Info.NumberOfTicksToVerifyAvailableAirport));
 				return true;
 			}
```

**Comment by MlemandPurrs** [comment]
oh, totally forgot i have opened this issue before

**Comment by MlemandPurrs** [comment]
> I think behavior "ReturnToBase" can only be set by a mod, because it's hardcoded in Aircraft.cs - correct?

No, its one of the possible options: Land, ReturnToBase, LeaveMap, and None.

**Comment by ThomasChr** [comment]
And where can I change them? Sorry, I'm not deep into OpenRA :-)

**Comment by abcdefg30** [comment]
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Air/Aircraft.cs#L38 exposes the `IdleBehavior` to yaml.

**Comment by ThomasChr** [comment]
So it's exposed to a yaml-File. But I still need to create a yaml-File to change it, correct?
It's not changeable in the GUI in a completely unmodified OpenRA version?

**Comment by abcdefg30** [comment]
> This would be a very rough first try:
> 
> ```
> Index: OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs b/OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs
> --- a/OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs	(revision acc2c11e6952e342546e84adb06cdad28839c699)
> +++ b/OpenRA.Mods.Common/Activities/Air/ReturnToBase.cs	(date 1666104704613)
> @@ -104,7 +104,7 @@
>  				}
>  
>  				// Prevent an infinite loop in case we'd return to the activity that called ReturnToBase in the first place. Go idle instead.
> -				self.CancelActivity();
> +				QueueChild(new FlyIdle(self, aircraft.Info.NumberOfTicksToVerifyAvailableAirport));
>  				return true;
>  			}
> ```

That doesn't look bad on a first glance. Did you test this patch?

**Comment by ThomasChr** [comment]
I tested it by hand, yes. It did what it was supposed to do.
I've not written any tests though and I'm not quite sure how to write a test for it.

**Comment by abcdefg30** [comment]
> So it's exposed to a yaml-File. But I still need to create a yaml-File to change it, correct? It's not changeable in the GUI in a completely unmodified OpenRA version?

There is no GUI for changing it yes. But every mod already contains yaml files with the definitions for units, so it can be changed in one of those files. For example the `frigate` in Dune 2000 defines: https://github.com/OpenRA/OpenRA/blob/3be0e9e8a57f648d11150cfb9632bd8488037c64/mods/d2k/rules/aircraft.yaml#L85-L86

**Comment by abcdefg30** [comment]
> I've not written any tests though and I'm not quite sure how to write a test for it.

We don't have any automated tests for those gameplay elements, so testing by hand alone is fine. :)
