### ISSUE TITLE
Support for changing actor's production icon 

### ISSUE THREAD

**Issue by Dzierzan** [OpenRA/OpenRA#20397]
Hello!
It would be nice to have support for some kind of suffix for changing actor's sequence **icon** to let's say sequence **icon-clicked** when you click on actor's icon to start production.

This is something I require for my OpenSA project. An example is in issue below:

https://github.com/Dzierzan/OpenSA/issues/191

**Comment by PunkPun** [comment]
Could you be more specific? What widget specifically you want to support stateful names? From the linked issue I don't understand what is missing / desired.

**Comment by Dzierzan** [comment]
Ability to change actor's icon when it is being produced. Right now you only render clock sequence on top of icon sequence.

The linked issue clearly shows that as soon as you click on actor's icon, it changes to a new one. But comes back to the default one if it is not active (not producing specific actor). ORA doesnt support it.

**Comment by PunkPun** [comment]
oh those are actor icons?

**Comment by PunkPun** [comment]
I'm sorry I really need to see a comparison of how it is vs how it should be. I'm not familiar at all with that game

**Comment by PunkPun** [comment]
How does it work? You select an actor icon and then it continuously produces that actor? Because if that's the case then I didn't know openra supported that. Incase it doesn't support, then such a feature would be best implemented as its own widget rather than using ProductionPaletteWidget

**Comment by Dzierzan** [comment]
I believe you are paying too much attention to the wrong thing. The thing you descibed is indeed not supported by `ProductionPaletteWidget`, however this ticket is not about it. It's about the changing of the icon itself as soon as you click it. You can even multiply the queue up to 100, but the icon's sequence is meant to be let's say `icon-clicked` as long as you produce a specific actor. As soon as the last actor was produced, the icon should change back to default `icon` sequence. That is my "wish list".

If I were to reproduce SA's in game UI, that'd require total new `ProductionPaletteWidget` (like OpenKrush did it). However I only require this (hopefully) small change so make it more or less like the original Swarm Assafult in game UI.

**Comment by PunkPun** [comment]
So not icon-clicked but icon-active?

**Comment by ThomasChr** [comment]
Can we maybe have some pictures alongside the description?

**Comment by Dzierzan** [comment]
@PunkPun 

The name doesn't matter here, can be `icon-clicked`, can be `icon-active`.

@ThomasChr 

That. but ignore the fact that clicking the other icon cancels the previous one. It is another feature which I am not requesting in this ticket.

![111024509-717e9980-83df-11eb-8338-d53d2ecc885d](https://user-images.githubusercontent.com/17529329/197832998-0809d70b-a23e-4db2-a675-f818a45ab998.gif)

**Comment by Dzierzan** [comment]
Since it's a feature which only I need, I'll close it.
