### ISSUE TITLE
Misclick through sidebar

### ISSUE THREAD

**Issue by MikillRosen** [OpenRA/OpenRA#20413]
## Issue Summary
The sidebar has holes between the category buttons where you click on the game instead of the sidebar. This means you can select a unit and when you click on the sidebar holes, you end up ordering your unit to move. This is why I misclick in OpenRA more often than in the original C&C games.

## Reproduction
Select a unit and click just between the category buttons in the sidebar.

## Expected behavior
Nothing happens

## Screenshots / Screen recordings / Replays
(Red dot is where my cursor is.)
![ra-2022-10-30T182119112Z](https://user-images.githubusercontent.com/51423707/198894973-60f0bc51-3998-49db-b75a-ecb44e2aa351.png)

**Comment by ThomasChr** [comment]
If the mouse pointer is between the categories (and an unit is selected) you get the normal "move" pointer and right clicking lets the unit move to the position under the sidebar:
![image](https://user-images.githubusercontent.com/13014163/198968234-5ae011bc-5b4d-42b2-9c0b-853190405b61.png)

You also get the move pointer between the unit builiding buttons, but if you right click nothing happens:
![image](https://user-images.githubusercontent.com/13014163/198968383-1dca767e-3f04-41dc-8711-d6196c911f98.png)

**Comment by ThomasChr** [comment]
Does not happen in "release-20210321" - seems like a git bisect job...

**Comment by ThomasChr** [comment]
I bisected the hell out of it...
```
ad4425d11e1d14af4b8f926f04ebe58d139cbf8a is the first bad commit
commit ad4425d11e1d14af4b8f926f04ebe58d139cbf8a
Author: Ivaylo Draganov <dragunoff@gmail.com>
Date:   Sat Nov 21 21:33:57 2020 +0200

    Use cached transforms for images in widgets

 OpenRA.Mods.Common/Widgets/DropDownButtonWidget.cs | 18 +++++++++++-------
 OpenRA.Mods.Common/Widgets/ProductionTabsWidget.cs | 11 +++++++----
 OpenRA.Mods.Common/Widgets/ScrollPanelWidget.cs    | 11 +++++++----
 OpenRA.Mods.Common/Widgets/WidgetUtils.cs          | 10 ++++++++++
 4 files changed, 35 insertions(+), 15 deletions(-)
```
**I tried to confirm this git bisect manually but I couldn't confirm. So I'm not sure if it's correct!!**
**Tried a second time to bisect, having c0ea95ca46e318582079f204a1072c72f00d293d as the first bad commit - which absolutely makes no sense. Maybe my build pipeline is not working correctly sometimes. Giving up on the bisect now!**

Good to know: There are 3 versions here:
1. Having the click pointer. (the same as when on the buttons)
2. Having the not-click pointer. (the same as when your cursor is on terrain where your unit can't go)
3. Having the normal move pointer (the same as when your cursor is on terrain where your unit can go)

I bisected for cursor number 2.

**Comment by dragunoff** [comment]
Also happens in TD in these areas:
![image](https://user-images.githubusercontent.com/1355810/201077693-b4252eba-cf9f-4577-834a-1818a74db1f1.png)
![image](https://user-images.githubusercontent.com/1355810/201077771-02b78154-29d0-4331-ade5-baa5a05394d2.png)

**Comment by ThomasChr** [comment]
Also happens in last release... not on all the positions, but at least here:
![image](https://user-images.githubusercontent.com/13014163/201086889-a7b91c19-fc7a-4f04-9429-da9dcbfb6dd3.png)

So then bisect is out of the question. We tried to hunt it down but the cursor system is kind of complicated...
I got -kind of- fix it by giving the ContainerWidget the default Cursor. But I'm pretty unsure if thats the right way:
```
Index: OpenRA.Game/Widgets/Widget.cs
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/OpenRA.Game/Widgets/Widget.cs b/OpenRA.Game/Widgets/Widget.cs
--- a/OpenRA.Game/Widgets/Widget.cs	(revision b733b10f27e1cb4a00789148e005cc296dacfd0e)
+++ b/OpenRA.Game/Widgets/Widget.cs	(date 1668082067867)
@@ -568,7 +568,7 @@
 		public ContainerWidget(ContainerWidget other)
 			: base(other) { IgnoreMouseOver = true; }
 
-		public override string GetCursor(int2 pos) { return null; }
+		public override string GetCursor(int2 pos) { return "default"; }
 		public override Widget Clone() { return new ContainerWidget(this); }
 		public Func<KeyInput, bool> OnKeyPress = _ => false;
 		public override bool HandleKeyPress(KeyInput e) { return OnKeyPress(e); }
```
(also it doesn't fix the one position I mentioned at the top of this post... So we need a better approach)

**Comment by ThomasChr** [comment]
I finally bisected it!
Here we go:
```
e7cfd2765caf6e42c4cd688bc96ced13dfcc29dd is the first bad commit
commit e7cfd2765caf6e42c4cd688bc96ced13dfcc29dd
Author: Matthias Mailänder <matthias@mailaender.name>
Date:   Sun Oct 18 18:37:04 2020 +0200

    Make UI cursors configurable.

 OpenRA.Game/Game.cs                                      | 2 +-
 OpenRA.Game/Orders/UnitOrderGenerator.cs                 | 6 +++++-
 OpenRA.Game/Widgets/Widget.cs                            | 6 +++++-
 OpenRA.Mods.Common/Orders/PlaceBuildingOrderGenerator.cs | 8 +++++++-
 OpenRA.Mods.Common/Widgets/ButtonWidget.cs               | 4 ++++
 OpenRA.Mods.Common/Widgets/RadarWidget.cs                | 3 ++-
 mods/common/metrics.yaml                                 | 4 ++++
 7 files changed, 28 insertions(+), 5 deletions(-)
 ```
Good commit 96c455464429eebb845bf60bff8ce04e07a1617e:
![image](https://user-images.githubusercontent.com/13014163/201298844-3c794f05-d3fd-4fbe-801a-1d94e45c0013.png)

Bad commit e7cfd2765caf6e42c4cd688bc96ced13dfcc29dd:
![image](https://user-images.githubusercontent.com/13014163/201298863-246c9c5c-ef3a-4d6f-b88b-70425c0821d2.png)

Just to have it here also, even with the good commit we still have a few places where we can click through the sidebar. This is release-20210321:
![image](https://user-images.githubusercontent.com/13014163/201312911-adacdd77-6c1b-456f-8fdc-bda45b03a6c6.png)
(you can also click there and the unit drives there...)
