### ISSUE TITLE
Classic Sidebar

### ISSUE THREAD

**Issue by MikillRosen** [OpenRA/OpenRA#20412]
One of the reasons I don't prefer playing OpenRA is because of the modern sidebar. I prefer switching around the structure and unit categories with just 4 hotkeys. This sidebar has separate categories for Vehicles, Aircraft, and in RA, Naval Vessels which increases how many hotkeys needed for the category buttons. If y'all could add an option to turn the sidebar to be like the sidebar from Red Alert 2, that would be great.

**Comment by abcdefg30** [comment]
I'm sorry but this is unlikely to happen for the default mods. This is possible in theory by (local) yaml adjustments, but maintaining two chrome definitions and systems in the default mods is out of scope.

**Comment by Mailaender** [comment]
→ https://github.com/OpenRA/raclassic/
