### ISSUE TITLE
WithColoredOverlay should support Alpha

### ISSUE THREAD

**Issue by MlemandPurrs** [OpenRA/OpenRA#20433]
WithColoredOverlay was changed to accept Color instead of Palette, this has resulted in overlays of this type becoming non-transparent as its not allowing to set A: to 128 like could do before when it was using palette.

**Comment by darkademic** [comment]
You can just specify the alpha as part of the colour, e.g. Color: 51aeda1c (1c being the alpha, equivalent to 28 in RGBA).

**Comment by MlemandPurrs** [comment]
> You can just specify the alpha as part of the colour, e.g. Color: 51aeda1c (1c being the alpha, equivalent to 28 in RGBA).

Yepp, this functioned. thanks.
