### ISSUE TITLE
Virtual functions for modding (OpenRAModdingSDK)

### ISSUE THREAD

**Issue by oldnaari** [OpenRA/OpenRA#20447]
I am using OpenRAModdingSDK. 
This means when adding a feature, I can't and shouldn't edit existing classes in OpenRA.Mods. I need to create separate classes as children and add changes by overriding the related methods. 

Here comes the problem. There are many functions that are not virtual, and thus cannot be edited during the modding. From my experience, a method appears to be virtual only if it is overridden somewhere in the project.

I suggest when creating new methods make them virtual by default, maybe with minor exceptions. Also, suggest doing a refactoring of the existing codebase, to have all methods virtual (again there might be exceptions).

**Comment by IceReaper** [comment]
I had this a lot on OpenKrush development. Mostly make a PR with the methods you need, and its very likely accepted ;)

**Comment by pchote** [comment]
Closing as not being specifically actionable. Virtual methods have a performance overhead so we don't want everything to be virtual by default.
