### ISSUE TITLE
Misclick through sidebar (2)

### ISSUE THREAD

**Issue by ThomasChr** [OpenRA/OpenRA#20453]
See: https://github.com/OpenRA/OpenRA/issues/20413
There is still one misclick left, this one:

You can click here, and the units will move accordingly: 
![image](https://user-images.githubusercontent.com/13014163/201607208-afcd3a05-1c83-4bfb-a5ab-51f4cac03085.png)

**Comment by ThomasChr** [comment]
Also these two misclicks are still there, reported here: https://github.com/OpenRA/OpenRA/issues/20413#issuecomment-1310133835
![image](https://user-images.githubusercontent.com/13014163/201646393-d9e23ae1-25d3-44d8-a797-3b8dfbc56416.png)
![image](https://user-images.githubusercontent.com/13014163/201646414-05dbe4ab-8bb8-41d1-ac91-add5da6aa09b.png)

**Comment by dragunoff** [comment]
World interaction is also possible by clicking around the production tabs and the command bar buttons in RA:
![Screenshot from 2022-11-14 13-49-48](https://user-images.githubusercontent.com/1355810/201654509-7750e48f-3259-485d-97ce-e77beea61b5b.png)
![Screenshot from 2022-11-14 13-47-15](https://user-images.githubusercontent.com/1355810/201654513-a30d1b55-b58c-4869-9cd6-be2f166b1c71.png)

and around the command bar buttons in D2k:
![Screenshot from 2022-11-14 13-51-58](https://user-images.githubusercontent.com/1355810/201654497-b7b31299-4e47-4720-ac7a-f56f46fcb218.png)

**Comment by PunkPun** [comment]
Oh hmm, It shows the correct cursor but still gives "Unrevealed Terrain" tooltip?

**Comment by PunkPun** [comment]
you can also right click on the whole queue selection panel to move units, it's not just the gaps

**Comment by ThomasChr** [comment]
This is getting out of control :-(

**Comment by ThomasChr** [comment]
@abcdefg30 Not quite sure if we really should close here. Yes, my PR fixed a few things (which is good!), but dragunoffs comment is still not fixed. Re-open this one, or open another issue?

**Comment by ThomasChr** [comment]
Thanks!

**Comment by PunkPun** [comment]
@dragunoff mentioned on discord that all of these were fixed
