### ISSUE TITLE
Desync related with issueing an order to actor that will be not in world at the end of the frame

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20478]
Issue related: https://github.com/OpenRA/OpenRA/issues/20469
May related to commit: https://github.com/OpenRA/OpenRA/commit/6421c1751546ad275e4e00546a78046761c45ce2

I tried many time to make a reproducing version on d2k, but I faild due to following:

d2k's spice is too rich and widely spread at any time, and harvester can auto scan resource from a very large radius, which result in the HarvesterBotModule cannot find any idle harvester at any map and any time (you can try this yourself)

when I reduce harvester's auto scan and spice spawning, another strange bug comes to me: carryall just pick up the harvester under order of HarvesterBotModule but doing nothing and get into flyidle.

So I have to give you https://github.com/ABrandau/Shattered-Paradise-SDK/tree/sync-test2 as testcase.

~~1. When we send orders to local player we use `EchoConnection`~~
~~On recieving, we directly queue orders to next frame of `orderManager`.~~

~~2. When we send orders to other players, we send a serialized data package to other client by using `NetworkConnection`.~~
~~On recieving, we parse the orders to executing frame of `orderManager`.~~

~~However, when we parse orders in `NetworkConnection`, we drop order with subject actor of `IsInWorld == false` (see "Order.cs", line 111 and "Order.cs", line 196). This may cause desync when sender's `EchoConnection` excutes the order with actor of `IsInWorld == false`, while `NetworkConnection` find that on the executing frame, the subject actor is not in world so the order is dropped.~~

There is a sync report caused by this: [sp10modirestore.zip](https://github.com/OpenRA/OpenRA/files/10072506/sp10modirestore.zip)
This will happen when actor just go inside transport or just being carried by carryall, before an order really takes an effect on its frame.

**Comment by dnqbob** [comment]
add: The analysis below is still not correct at where the `IsInWorld` is changing. See  https://github.com/OpenRA/OpenRA/pull/20480

Make clear the causing, but kinda

*Note: the "order" refered in following content:
1. is not immediate order (something like chat with other client)
2. order type is `Fields`, which means it is battle field order

## The ticks within a tick in game
We know that a tick of game will run following ticks in order:
1. Order tick (see Game.cs, line 615)
1.1 Receive orders (see Game.cs, line 615 => OrderManager.cs, line 280)
1.2 Send orders (see Game.cs, line 620 => OrderManager.cs, line 300)
1.3 Process orders (see Game.cs, line 620 => OrderManager.cs, line 300)

2. World tick -> Actors tick, run the actor related, which includings activity tick (see Game.cs, line 627 => World.cs line 441)

3. World tick -> Traits tick, run all the trait  (see Game.cs, line 627 => World.cs line 443)
*Note: AI players use `ModularBot` to issue the orders to `OrderManager`

4. World tick -> Effect tick, run all the effect (see Game.cs, line 627 => World.cs line 445)

5. World tick -> Frame end task (see Game.cs, line 627 => World.cs line 448)
it execute something like the lines in `AttachUnit` of the carryall
```
				self.World.AddFrameEndTask(w =>
				{
					cargo.World.Remove(cargo);
					carryable.Attached();
					carryall.AttachCarryable(self, cargo);
				});
```

## How the bug happens
We have 2 clients in game: C1, C2

#### At frame "x"
At frame "x", the bot in C1 generates an order about actor "A", by bot trait. When the order is generate, "A" is in world.

1. The order is issued to `OrderManager` of C1.

2. Then, the world is changed by other traits tick, effects and frame end task. Actor "A" can be not in world after those.

#### At frame "x+1"

1. C1 send the order:
1.1 C1 will send order (serialized) to C2 (see Connection.cs, line 232)
1.2 Upon acknowlege C2 is recieved, C1 will directly store it from `sentOrders` (see Connection.cs, line 335)

2. C1 execute the order from storage

2. C2 first deserialize order data, then execute it. (However, in deserialization, C2 cannot find actor "A" in `GetActorByID()` because it is not in world. The order is abandoned)

3. Desync happens. C1 executes the order change  actor "A" but C2 doesn't.

Add: following order fields also have the same desync concern:
1. when `Target` field is `TargetType.Actor` or `TargetType.FrozenActor`(see "Order.cs", line 123 and line 134)
2. when `Grouped` field contains actors that is not in world  (see "Order.cs", line 188)
3. when `ExtraActors` field contains actors that is not in world  (see "Order.cs", line 175)

**Comment by PunkPun** [comment]
> C2 first deserialize order data, then execute it. (However, in deserialization, C2 cannot find actor "A" in GetActorFromID() because it is not in world. The order is abandoned)

`GetActorFromID()` function doesn't exist in the engine, and I can't find any IsInWorld checks within the order handling code so I suspect that this issue is limited to your custom engine

**Comment by PunkPun** [comment]
Oh I see. You just miswrote. It's called `GetActorById()`

**Comment by dnqbob** [comment]
> Oh I see. You just miswrote. It's called `GetActorById()`

Sorry, that is a really mistake

**Comment by PunkPun** [comment]
Regression from #19632
Related #19930

**Comment by dnqbob** [comment]
Take me quite sometime to clear my mind from `EchoConnection`

**Comment by dnqbob** [comment]
If what I describe in https://github.com/OpenRA/OpenRA/pull/20479#issuecomment-1326465249 is correct, I think we have some ways to fix this desync issue:

1. Check the ACK order which storage as `OrderPacket.orders[]` while we are going to execute it. https://github.com/OpenRA/OpenRA/pull/20479

2. We disallow actor is not in world resolve order.

~~3. All orders generated/checked at the end of the frame end task.  https://github.com/OpenRA/OpenRA/pull/20480~~

**Comment by dnqbob** [comment]
I tried many time to make a reproducing version on d2k, but I faild due to following:

1. d2k's spice is too rich and widely spread at any time, and harvester can auto scan resource from a very large radius, which result in the `HarvesterBotModule` cannot find any idle harvester at any map and any time (you can try this yourself)

2. when I reduce harvester's auto scan and spice spawning, another strange bug comes to me: carryall just pick up the harvester under order of `HarvesterBotModule` but doing nothing and get into `flyidle`.

So I have to give you https://github.com/ABrandau/Shattered-Paradise-SDK/tree/sync-test2 as testcase.
