### ISSUE TITLE
Changing facing/turret/health of an actor in map editor disables hotkeys.

### ISSUE THREAD

**Issue by BlackenedRA** [OpenRA/OpenRA#20482]
If you edit any of these by typing in numbers rather than using the slider your hotkeys will be disabled, including escape, until you select another actor.

Steps to reproduce are easy:
select actor
type in a different facing/health/turret
try and use escape/c/v/f1/etc.

**Comment by ThomasChr** [comment]
It seems to me that the cursor is stuck in the (number) entry field and doesn't react to Keys like ESC. Changing the dropdown fields doesn't change that, but I could click the actor name, and with the first ESC the cursor leaves the actor name field and the second ESC worked as before. Could you try that @BlackenedRA ?
