### ISSUE TITLE
Map editor seems to randomly disable hotkeys

### ISSUE THREAD

**Issue by BlackenedRA** [OpenRA/OpenRA#20483]
This is probably related to #20482 but so far I can't figure out a definite reason as to why it happens. Usually I have a podcast or music running and alt tab in and out of the client so maybe that contributes to it showhow? Next time it happens I'll try to remember exactly what I was doing when it happens.

**Comment by BlackenedRA** [comment]
I think I've figured out what happens. For some reason it seems the search function in the tiles section gets triggered. This explains why you lose hotkeys except for hitting escape twice since that backs you out of the search box.

As to why this happens I'm still not sure. I've had it happen when using tiles and when placing actors.

**Comment by PunkPun** [comment]
We've fixed a bunch of related bugs, Is it still an issue?

**Comment by BlackenedRA** [comment]
I haven't worked on new maps in a little bit now. I'm not sure but I'll keep this in mind whenever I kickstart maps again.

**Comment by PunkPun** [comment]
#20920 is the only issue I'm aware of. I'm closing this as being superseded
