### ISSUE TITLE
Changing names of actors and then deleting them freezes them in map editor

### ISSUE THREAD

**Issue by BlackenedRA** [OpenRA/OpenRA#20481]
If you change the name of an actor and try to delete it later, the actor won't disappear, but will be deleted when you save and reload the map.

Steps to reproduce are easy:
open map
select an actor from the list and place on map
rename the actor
delete actor.
The image will be frozen.

You can still select the actor but the ok selection will be greyed out.

**Comment by ThomasChr** [comment]
I could get OK to work when I change something, but yes, the actor does still seem off and isn't there anymore after saving and reloading. @BlackenedRA How exactly do you delete the actor? Via the menu or via right click?

**Comment by PunkPun** [comment]
The bugs with actor deletion in map editor were fixed
