### ISSUE TITLE
The abstract path should never be searched for an unreachable point

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#20508]
A crash I found

Ping @RoosterDragon. The replay still crashes on #20498 so this is a different error

```
Exception of type `System.Exception`: The abstract path should never be searched for an unreachable point. Abstract cell 162,25 failed to route to abstract cell.
```

[crash.orarep.zip](https://github.com/OpenRA/OpenRA/files/10149167/crash.orarep.zip)

**Comment by PunkPun** [comment]
It crashed when I produced submarines

**Comment by RoosterDragon** [comment]
Thanks - I have made an adjustment to #20498 which resolves this crash as well.
