### ISSUE TITLE
Location of .oramap files Playtest 20221203

### ISSUE THREAD

**Issue by HakkaTjakka** [OpenRA/OpenRA#20514]
Hello.
I have downloaded the Linux version: 
```
OpenRA-Red-Alert-playtest-x86_64.AppImage  
```
from:
```
http://www.openra.net/
```

If i make a map and save it with OpenRA, i can not find them. 
Any idea where these files are in the Linux filesystem? 

Thanks...

**Comment by HakkaTjakka** [comment]
Sorry, found them...

**Comment by abcdefg30** [comment]
Closing as resolved then.
