### ISSUE TITLE
Audio Device: No Sound Output

### ISSUE THREAD

**Issue by phpet** [OpenRA/OpenRA#20526]
## Issue Summary

DESCRIPTION
Sound is not working in Windows 11. Build: playtest-20221203

## Reproduction

STEPS TO REPRODUCE THE ISSUE
When you go to Settings Audio, the Audio Device drop down has a single entry:
No Sound Output

## Expected behavior

EXPECTED BEHAVIOR
When you go to Settings Audio, the Audio Device drop down should display a list of all the sound profiles available in Windows.

## Screenshots / Screen recordings / Replays

![sound](https://user-images.githubusercontent.com/33682688/205987313-5ae56c30-8f76-4d54-b5dc-52ef320ab9c3.png)

**Comment by abcdefg30** [comment]
Just to make sure: At least one sound device was enabled in Windows?

**Comment by phpet** [comment]
Yes, at least one sound device is enabled. See the attached screenshots.

The sound works just fine in Windows from a browser or any other game. This only happens with OpenRA.

There is an error that shows up in the sound.log file:

Failed to initialize OpenAL device. Error was System.InvalidOperationException: Can't create OpenAL context
   at OpenRA.Platforms.Default.OpenAlSoundEngine..ctor(String deviceName)
   at OpenRA.Platforms.Default.DefaultPlatform.CreateSound(String device)

![s2](https://user-images.githubusercontent.com/33682688/206219080-2fe39a35-567d-4554-a4cd-a421dae50094.png)
![s1](https://user-images.githubusercontent.com/33682688/206219086-d23e9778-58df-449b-912d-7759fc3453b6.png)

**Comment by Maltstar** [comment]
same issue under linux  on the playtest version [playtest-20221223](https://github.com/OpenRA/OpenRA/blob/playtest-20221223/INSTALL.md), no sound device available to select on the sound setting. Outside OpenRA, the sound works fine with every application.

**Comment by pchote** [comment]
Does it work correctly on release-20210321?

**Comment by Maltstar** [comment]
I did not try but I am going to.

**Comment by Maltstar** [comment]
Otherwise this output of the console when I launch the playtest version:
```

`Platform is Linux (X64)

Engine version is playtest-20221223

Runtime: .NET CLR 6.0.12

Using SDL 2 with OpenGL (Modern) renderer

Desktop resolution: 1920x1080

No custom resolution provided, using desktop resolution

Using resolution: 1920x1080

Using window scale 1.00

OpenGL renderer: AMD RENOIR (LLVM 13.0.1, DRM 3.42, 5.15.0-56-generic)

OpenGL version: 4.6 (Core Profile) Mesa `22.0.5`

Using default sound device

Failed to open device. Falling back to default

Internal mods:
	modcontent: Mod Content Manager (playtest-20221223)
	ra: Red Alert (playtest-20221223)

External mods:
	ra-playtest-20221223: Red Alert (playtest-20221223)
	d2k-playtest-20221223: Dune 2000 (playtest-20221223)

Loading mod: `ra`
```

It seems that the default behavior is to use a default sound device which do not match any physical device:
```
Using default sound device
Failed to open device. Falling back to default
```

**Comment by Maltstar** [comment]
> Does it work correctly on release-20210321?

No, it is the same behavior as for the playtest version.

![image](https://user-images.githubusercontent.com/101098152/209416580-aad7b445-29d3-404c-a3d6-11ca506a13a1.png)

**Comment by pchote** [comment]
I suspect that both issues are likely to be caused by openal-soft not being compiled with support for whatever audio backend is in use on your systems.

**Comment by onixlas** [comment]
Same issue with the latest playtest on linux. Everything works perfectly with release version

**Comment by Maltstar** [comment]
You mean the release on linux?

**Comment by Maltstar** [comment]
> Same issue with the latest playtest on linux. Everything works perfectly with release version

You mean the release on linux?

**Comment by Maltstar** [comment]
> I suspect that both issues are likely to be caused by openal-soft not being compiled with support for whatever audio backend is in use on your systems.

What should I do? install openal-soft before OpenRA or is the compilation of openal-soft part of the building process for OpenRA?

**Comment by onixlas** [comment]
> > Same issue with the latest playtest on linux. Everything works perfectly with release version
> 
> You mean the release on linux?

Yep. Both release and playtest versions run on linux. Both installed via appimage from the official website

**Comment by Maltstar** [comment]
> > > Same issue with the latest playtest on linux. Everything works perfectly with release version
> > 
> > 
> > You mean the release on linux?
> 
> Yep. Both release and playtest versions run on linux. Both installed via appimage from the official website

Did you get warning message about "dotnet" during the installation process (make) for the release:
```
It was not possible to find any installed dotnet SDKs
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
      https://aka.ms/dotnet-download

It was not possible to find any installed dotnet SDKs
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
      https://aka.ms/dotnet-download
 Determining projects to restore...

  All projects are up-to-date for restore.

  It was not possible to find any installed dotnet SDKs
  Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
      https://aka.ms/dotnet-download

It was not possible to find any installed dotnet SDKs
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
      https://aka.ms/dotnet-download

  OpenRA.Game -> /home/johnson/used/Game/OpenRA-release-20210321-source/bin/OpenRA.Game.dll
  OpenRA.Mods.Common -> /home/johnson/used/Game/OpenRA-release-20210321-source/bin/OpenRA.Mods.Common.dll
  OpenRA.Mods.Cnc -> /home/johnson/used/Game/OpenRA-release-20210321-source/bin/OpenRA.Mods.Cnc.dll
  OpenRA.Utility -> /home/johnson/used/Game/OpenRA-release-20210321-source/bin/OpenRA.Utility.exe
  OpenRA.Server -> /home/johnson/used/Game/OpenRA-release-20210321-source/bin/OpenRA.Server.exe
  OpenRA.Mods.D2k -> /home/johnson/used/Game/OpenRA-release-20210321-source/bin/OpenRA.Mods.D2k.dll
  OpenRA.Platforms.Default -> /home/johnson/used/Game/OpenRA-release-20210321-source/bin/OpenRA.Platforms.Default.dll
  OpenRA.Test -> /home/johnson/used/Game/OpenRA-release-20210321-source/bin/OpenRA.Test.dll
  OpenRA.Launcher -> /home/johnson/used/Game/OpenRA-release-20210321-source/bin/OpenRA.exe`
```

I installed dotnet with snap but it seems that OpenRA is not able to detect it.

**Comment by Maltstar** [comment]
> > > > Same issue with the latest playtest on linux. Everything works perfectly with release version
> > > 
> > > 
> > > You mean the release on linux?
> > 
> > 
> > Yep. Both release and playtest versions run on linux. Both installed via appimage from the official website
> 
> Did you get warning message about "dotnet" during the installation process (make) for the release:
> 
> ```
> It was not possible to find any installed dotnet SDKs
> Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
>       https://aka.ms/dotnet-download
> 
> It was not possible to find any installed dotnet SDKs
> Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
>       https://aka.ms/dotnet-download
>  Determining projects to restore...
> 
>   All projects are up-to-date for restore.
> 
>   It was not possible to find any installed dotnet SDKs
>   Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
>       https://aka.ms/dotnet-download
> 
> It was not possible to find any installed dotnet SDKs
> Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
>       https://aka.ms/dotnet-download
> 
>   OpenRA.Game -> /home/johnson/used/Game/OpenRA-release-20210321-source/bin/OpenRA.Game.dll
>   OpenRA.Mods.Common -> /home/johnson/used/Game/OpenRA-release-20210321-source/bin/OpenRA.Mods.Common.dll
>   OpenRA.Mods.Cnc -> /home/johnson/used/Game/OpenRA-release-20210321-source/bin/OpenRA.Mods.Cnc.dll
>   OpenRA.Utility -> /home/johnson/used/Game/OpenRA-release-20210321-source/bin/OpenRA.Utility.exe
>   OpenRA.Server -> /home/johnson/used/Game/OpenRA-release-20210321-source/bin/OpenRA.Server.exe
>   OpenRA.Mods.D2k -> /home/johnson/used/Game/OpenRA-release-20210321-source/bin/OpenRA.Mods.D2k.dll
>   OpenRA.Platforms.Default -> /home/johnson/used/Game/OpenRA-release-20210321-source/bin/OpenRA.Platforms.Default.dll
>   OpenRA.Test -> /home/johnson/used/Game/OpenRA-release-20210321-source/bin/OpenRA.Test.dll
>   OpenRA.Launcher -> /home/johnson/used/Game/OpenRA-release-20210321-source/bin/OpenRA.exe`
> ```
> 
> I installed dotnet with snap but it seems that OpenRA is not able to detect it.

I get removed of the warning by uninstalling dotnet in snap and installing directly with the defaut package manager of my distro, in this case I am using Ubuntu, I followed this procedure https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu?source=recommendations

But still no improvement regarding the sound settings.

**Comment by Maltstar** [comment]
> > I suspect that both issues are likely to be caused by openal-soft not being compiled with support for whatever audio backend is in use on your systems.
> 
> What should I do? install openal-soft before OpenRA or is the compilation of openal-soft part of the building process for OpenRA?

I installed openal-soft, then reboot and compiled again the release and now the sound is working for the relase. :)
I tried then to start the playtest but still not sound.

**Comment by Mailaender** [comment]
> Failed to initialize OpenAL device. Error was System.InvalidOperationException: Can't create OpenAL device
   at OpenRA.Platforms.Default.OpenAlSoundEngine..ctor(String deviceName) in /home/runner/work/OpenRA/OpenRA/OpenRA.Platforms.Default/OpenAlSoundEngine.cs:line 130
   at OpenRA.Platforms.Default.DefaultPlatform.CreateSound(String device) in /home/runner/work/OpenRA/OpenRA/OpenRA.Platforms.Default/DefaultPlatform.cs:line 28

on Linux `sound.log`

**Comment by tremby** [comment]
Everything works fine for me on Linux in the current release (release-20210321) but I have no sound in the current playtest (playtest-20221224).

```
Using default sound device
Failed to open device. Falling back to default
```

**Comment by pchote** [comment]
@onixlas @tremby can you please test https://github.com/pchote/OpenRA/releases/tag/playtest-20221224-audiofix ?

**Comment by bttger** [comment]
> @onixlas @tremby can you please test https://github.com/pchote/OpenRA/releases/tag/playtest-20221224-audiofix ?

Thank you for the quick fix! It works for me. I had the same issue that was described here with the recent playtest version.

**Comment by onixlas** [comment]
> @onixlas @tremby can you please test https://github.com/pchote/OpenRA/releases/tag/playtest-20221224-audiofix ?

Works fine for me!
