### ISSUE TITLE
Adding community tilesets into default mods?

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#20536]
It look's like we will not have custom tiles in maps anytime soon. (#9684) So I want ask what are opinion on adding community tilesets into D2k by default. 
In this examples entire BLOXBASE  tileset are reskinned:

- First example can be fully incorporated into D2k ARRAKIS tilesets
- Second probably must be incorporated as new tileset (in similar way like RA have SNOW, TEMPERAT, etc)

BLOXICY:

![BLOXICY](https://user-images.githubusercontent.com/100044015/206897693-84d5466d-e461-4529-920d-8b74e6ebc05c.png)

GEIDY PRIME:
![bloxbGiedyPrime](https://user-images.githubusercontent.com/100044015/206897891-dba1dad6-5a69-48f9-bacd-d024a4f8ba13.png)

**Comment by Leo512bit** [comment]
These are not "true" tilesets, they are just reskins of the default tileset via palette swap.

**Comment by Porenutak** [comment]
No, they are not. First one have new ice tiles on which you can build on, also some new . Second have new tiles instead of dune tiles. And if you look closer you can see that rest have additional layer on it.

**Comment by Leo512bit** [comment]
> No, they are not. First one have new ice tiles on which you can build on, also some new . Second have new tiles instead of dune tiles. 

Huh? Really? because with every OpenRA map that I came across that has "custom tilesets" are just palette swaps.

**Comment by PunkPun** [comment]
That's because custom tilesets are not supported. As it's written in the issue's summary

**Comment by Leo512bit** [comment]
So is it done using custom actors?

**Comment by Porenutak** [comment]
In this issue I'm asking if we can merge these tiles into default D2k mod, so you don't need to use custom actors (for tiles you can build on its probably not even possible), so every mapper can use them. And what are opinions of maintainers about this topic.
IMO it increase possibilities for map makers to make more interesting maps (Like C&C net and original D2k already have)
I pick up this two tileset because they are in high quality. One expand existing tileset, one is completely new.

**Comment by MlemandPurrs** [comment]
more ice tiles sounds about nice.
geidi prime is not arrakis, so no to that one.

**Comment by MikillRosen** [comment]
I'd also like to point out that in the Giedi Prime tileset, there are faint camera symbols which implies that a watermarked image is used on it. I'll mark the most noticeable one
![206897891-dba1dad6-5a69-48f9-bacd-d024a4f8ba13](https://user-images.githubusercontent.com/51423707/207920115-cad3957a-b250-46b1-a641-5b2ec72f0178.png)

**Comment by Porenutak** [comment]
Didnt notice that :(

There is one more question related to Tiles. There is certain cliff tiles that are accessible only by infantry, but are available only from few angles. I created these cliff types from missing angles. Here's some examples:
![EnhacedAssets-0280](https://user-images.githubusercontent.com/100044015/208305627-ec4ce2ac-a2c0-446b-b586-1125195db6b7.png)
![EnhacedAssets-0281](https://user-images.githubusercontent.com/100044015/208305629-2696aa3b-0e67-447a-95e3-d58f64351657.png)
![EnhacedAssets-0282](https://user-images.githubusercontent.com/100044015/208305630-139be924-c1fe-4ce5-904a-1a1c50701e61.png)
![tiles_transitions_top_right](https://user-images.githubusercontent.com/100044015/208305947-94a7ee01-500e-4c53-a800-ee266ca525cc.png)
It's harder to add these as Map Actors as they should be accessible only by infantry. And this time there will be no copy right doubts as they was created by me. 

I did similar for missing cliff-type-changer tiles in Arrakis tileset:
![tile transition 1](https://user-images.githubusercontent.com/100044015/208306081-20b17e64-aa15-46fc-9282-0c5dd15fa383.png)
![tile transition 2](https://user-images.githubusercontent.com/100044015/208306083-34e46c46-1dcc-4195-a50e-e6dc9f1184fa.png)
![tile transition 3](https://user-images.githubusercontent.com/100044015/208306085-d15672b4-886d-483f-b38d-64bd6f3b57e9.png)
![tile transition 4](https://user-images.githubusercontent.com/100044015/208306087-c366badf-7a9c-4a02-b1b5-f26472b21ba1.png)
![tile transition 5](https://user-images.githubusercontent.com/100044015/208306089-1648b691-1c4c-45e0-b26d-7eb0b96b2bbb.png)
![tile transition 6](https://user-images.githubusercontent.com/100044015/208306090-de36cf7b-1966-4f18-b3d0-83bc04a7ec07.png)
![EnhacedAssets-0263](https://user-images.githubusercontent.com/100044015/208306094-6a004623-ca8c-4b77-9c28-0ef46b3a8249.png)
![EnhacedAssets-0264](https://user-images.githubusercontent.com/100044015/208306095-1fdab7e6-0f43-4e42-bae5-e08adfc215ac.png)


It is possible to add these?

**Comment by MlemandPurrs** [comment]
^
those can be added with ease.
more directions being made available for infantry ramps would open up new possibilities in map making for sure.

also cant move on without stating:
one idea i had regarding infantry ramps was to make breakable loose cliffs like those in TiberianSun, that when sufficiently damaged turns into one such infantry ramp.

**Comment by Porenutak** [comment]
> one idea i had regarding infantry ramps was to make breakable loose cliffs like those in TiberianSun, that when sufficiently damaged turns into one such infantry ramp.

Same here. I already done some and they are free to use:
[newTilesTest.zip](https://github.com/OpenRA/OpenRA/files/10359233/newTilesTest.zip)



https://user-images.githubusercontent.com/100044015/210978374-70bb52d9-d537-4008-abe9-ddec23358d1b.mp4

**Comment by Porenutak** [comment]
So if there will be a consensus Im willing to make PR which will add Ice tileset. Tilesets is authored by Kipp. I talked with the author if there is any problems with copy rights and he confirm me that they are make fully by him and we can use them. Tileset also include smudge layer for them.
You can find more info here:
https://forum.dune2k.com/topic/29441-release-new-custom-ice-tileset-for-dune-2000/

**Comment by Porenutak** [comment]
I guess silence means not gonna happen, so closing.
