### ISSUE TITLE
LUA WorldLoaded = function() is broke when new locomor is added via map rule.

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#20545]
version: playtest-20221203
To better understand this edge case bug use this map:

[01scripttest.zip](https://github.com/OpenRA/OpenRA/files/10221100/01scripttest.zip)

Script use WorldLoaded = function() to add Carryall at player starting position. 
Script  work's as should on stable release-20210321, but didn't work on playtest. (no starting units are found) BUT if you delete **Locomotor@TANK_harkonnen:** from **test.yaml** it start working as expected.

**Comment by abcdefg30** [comment]
It works for me on bleed.

**Comment by Porenutak** [comment]
On my PC it doesn't work even on bleed
Bleed:

https://user-images.githubusercontent.com/100044015/207433608-f3c38933-33cf-4ae0-9440-0079a258ddb2.mp4

Expected behavior stable release-20210321:

https://user-images.githubusercontent.com/100044015/207433675-6dcc29ef-5eb3-43f6-b355-c6d9f7a1b4af.mp4

**Comment by Porenutak** [comment]
Problem only occour when Locomotor is defined in World trait instead of ^BaseWorld. Closing.
