### ISSUE TITLE
Tilesets

### ISSUE THREAD

**Issue by HakkaTjakka** [OpenRA/OpenRA#20549]
I'm working on a c/c++ program to read the OpenRa tiles for RA.
From .mix files and other locations. With XCC, and the app.
But it confuses me. Can somebody help me out? I can not match the codes from the .bin from the .oramap onto the right images...

https://github.com/HakkaTjakka/Project-OpenRA-Map-Editor

**Comment by abcdefg30** [comment]
https://github.com/OpenRA/OpenRA/blob/4ffd81bd412771e68c9b1dc84477276ecb2bc730/OpenRA.Game/Map/Map.cs#L375 and onwards has the code that reads the tiles.
