### ISSUE TITLE
Map-mods with MiniYAML #comments pass lint but don't start

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#20551]
DESCRIPTION
I update these maps for playtest-20221203:

https://resource.openra.net/maps/49293/
https://resource.openra.net/maps/49292/
https://resource.openra.net/maps/49291/

Lint check is OK and maps works without any error in skirmish.
But in multiplayer you cant start a game, or access option menu. No error logs displayed. I try every server available in playtest, same result.
I also try maps on local dedicated server and everything works as should there, but on pulbic ones nothing.

**Comment by Porenutak** [comment]
After some investigation a figure out that problem is caused be **comments** in yaml. 
If there is any kind of **#** symbol in map yaml. server will not start a map.
here's a test case:
[mapwithcomments.zip](https://github.com/OpenRA/OpenRA/files/10240846/mapwithcomments.zip)

Upload this map to resource center. Map wouldn't work on any public server.
But if you delete all comments and all **#** symbols from map yaml files map start working as should.
Again this happens only on playtest public servers. Not on local Dedicated servers, not on skirmish.

**Comment by pchote** [comment]
At least part of the problem is that the yaml parser is not correctly handling empty comments for the base64'd yaml served by the RC (the problem doesn't happen when loading from a local map).

Testing with map https://resource.openra.net/maps/55473/

The input yaml:
```miniyaml
Rules:
	# server dont know this is a comment
	
	
	mcv:
		Mobile: # server dont know this is a comment
			Speed: 31
		RevealsShroud:
			Range: 2c768
	
	#
	# even this is not recognize by server lint check as comment
	#
	
	thumper:
		Buildable:
			Prerequisites: ~disabled
```
is parsed to:
```miniyaml
Rules:
	mcv:
		Mobile:
			Speed: 31
		RevealsShroud:
			Range: 2c768
	#:
	#:
	thumper:
		Buildable:
			Prerequisites: ~disabled
```

The following bodge avoids the issue, but obviously is not a proper fix.
```diff
diff --git a/OpenRA.Game/MiniYaml.cs b/OpenRA.Game/MiniYaml.cs
index 3d160b3994..969875ebdd 100644
--- a/OpenRA.Game/MiniYaml.cs
+++ b/OpenRA.Game/MiniYaml.cs
@@ -291,7 +291,7 @@ static List<MiniYamlNode> FromLines(IEnumerable<ReadOnlyMemory<char>> lines, str
                                                }
                                        }
 
-                                       if (keyLength > 0)
+                                       if (keyLength > 0 && line[keyStart] != '#')
                                                key = line.Slice(keyStart, keyLength).Trim();
 
                                        if (valueStart >= 0)
```

**Comment by pchote** [comment]
I think this may be the correct fix, but don't have time to deal with unit tests or ingame testing:

```diff
diff --git a/OpenRA.Game/MiniYaml.cs b/OpenRA.Game/MiniYaml.cs
index 3d160b3994..48344807bb 100644
--- a/OpenRA.Game/MiniYaml.cs
+++ b/OpenRA.Game/MiniYaml.cs
@@ -282,7 +282,7 @@ static List<MiniYamlNode> FromLines(IEnumerable<ReadOnlyMemory<char>> lines, str
                                                if (commentStart < 0 && line[i] == '#' && (i == 0 || line[i - 1] != '\\'))
                                                {
                                                        commentStart = i + 1;
-                                                       if (commentStart <= keyLength)
+                                                       if (i <= keyLength)
                                                                keyLength = i - keyStart;
                                                        else
                                                                valueLength = i - valueStart;
```

Unit test suggestion:
```diff
diff --git a/OpenRA.Test/OpenRA.Game/MiniYamlTest.cs b/OpenRA.Test/OpenRA.Game/MiniYamlTest.cs
index 90a4d6721a..04025a1fbc 100644
--- a/OpenRA.Test/OpenRA.Game/MiniYamlTest.cs
+++ b/OpenRA.Test/OpenRA.Game/MiniYamlTest.cs
@@ -39,7 +39,13 @@ public void TestParseRoundtrip()
        8.1.1:
        8.1.2: Test
        8.1.3: # Test
+#
+# Top level comment
+#
 9: # Test
+       #
+       # Indented comment
+       #
        9.1.1:
        9.1.2: Test
        9.1.3: # Test
```

**Comment by pchote** [comment]
FWIW I think the reason this occurs for RC maps but not local maps is that RC maps parse the yaml with an extra level of indentation compared to directly parsed maps.
