### ISSUE TITLE
Give descriptions to AI types.

### ISSUE THREAD

**Issue by MikillRosen** [OpenRA/OpenRA#20554]
OpenRA needs descriptions for its AI players, especially the ones with vague names like "Watson", "Gladius" etc.

**Comment by pchote** [comment]
Those names are intentional specifically *because* the differences between them are vague. They have different play styles which are not necessarily any harder or easier than others.

**Comment by MikillRosen** [comment]
No offense, but that sounds stupid. Why do we have to figure out what the AI types do unlike in RA?

**Comment by abcdefg30** [comment]
It's rather that RAs types are the odd one out, the difference between those AIs is "vague" as well.

**Comment by Mailaender** [comment]
Duplicate of https://github.com/OpenRA/OpenRA/issues/16126
