### ISSUE TITLE
Control group labels on units misaligned with keys

### ISSUE THREAD

**Issue by TommyHawk97** [OpenRA/OpenRA#20562]
## Issue
Just tried the Tiberian Dawn HD playtest and found this 1 minor problem on it. For example, if you set a group of units as group 1 on your keyboard, they will be labelled as 0 in game. 

## Screenshot

Even checked the settings, you can see it is all set correctly but still the problem is there.

![image](https://user-images.githubusercontent.com/19512358/208279972-21ec552b-f9e7-4588-a759-a163f6c714e3.png)

**Comment by pchote** [comment]
Its a bug in the Tiberian Dawn HD mod. The issue doesn't occur upstream.
