### ISSUE TITLE
If all exits are blocked, vehicles are stuck on repair pad

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#20583]
If there are more vehicles waiting for repair pad they have tendency to stuck.
version: playtest-20221224

https://user-images.githubusercontent.com/100044015/209473999-66a92016-7812-42c7-85ea-19ca4d3df9b0.mp4

https://user-images.githubusercontent.com/100044015/209474001-b02c4a43-f3a6-47b5-a315-9581c9faec79.mp4

**Comment by PunkPun** [comment]
This isn't dune exclusive. It just seems in the video you need 5 units to block the SD instead of 9?

**Comment by Porenutak** [comment]
Can't reproduce this issue anymore. Probably fixed by  #20618 ?
Closing

**Comment by PunkPun** [comment]
It should still be an issue. It'll be fixed with the docking refactor, #20621 should already help the situation
