### ISSUE TITLE
Discord Game Invite Doesn't work (Regression, Playtest)

### ISSUE THREAD

**Issue by Orb370** [OpenRA/OpenRA#20598]
![2023-01-03 16_27_04-Window](https://user-images.githubusercontent.com/42915475/210445002-7fb61792-ea30-40fe-8f53-8dd4579ae698.png)
^Is missing on playtest

**Comment by PunkPun** [comment]
Regressed in #19719?

**Comment by Mailaender** [comment]
No, in https://github.com/OpenRA/OpenRA/pull/19676.
