### ISSUE TITLE
Cursor Lock Feature - Multiple Display

### ISSUE THREAD

**Issue by MYRWYR** [OpenRA/OpenRA#20592]
Motivation

When using multiple displays, there seems to be no way lock the cursor from within OpenRA. This is not terrible, but does make panning horizontally a bit more tricky; we have to remain aware of the cursor location

Solution

I have found pretty comprehensive code in C that facilitates a cursor lock;
https://github.com/flx0/lock_cursor

Side Effects

I don't know how difficult this would be to implement, nor whether it has been implemented already - wholly or partially. I'm including it under Feature Request because I do not want to leave this under bug reports when it might not be a bug.

**Comment by pchote** [comment]
There's a "Lock Mouse to Window" option in the settings menu &rarr; Input panel. This works when fullscreen with multiple monitors as well as in windowed mode.
