### ISSUE TITLE
Lua library requires Microsoft Visual C++ 2015-2022 Redistributable

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#20631]
Current playtests crash on Windows with
```
System.DllNotFoundException: Unable to load DLL 'lua51' or one of its dependencies: The specified module could not be found. (0x8007007E)
```

It was reported on Discord that installing `Microsoft Visual C++ 2015-2022 Redistributable` (v14.34.31931) fixes it.

**Comment by pchote** [comment]
For completeness:

<img width="980" alt="Screenshot 2023-01-23 at 22 04 40" src="https://user-images.githubusercontent.com/167819/214160611-4c571f65-3a58-4b6c-ae4a-ad944089e258.png">
<img width="980" alt="Screenshot 2023-01-23 at 22 08 06" src="https://user-images.githubusercontent.com/167819/214161173-138322be-e2fd-4a04-88cf-f52aa20af171.png">
<img width="1002" alt="Screenshot 2023-01-23 at 22 08 26" src="https://user-images.githubusercontent.com/167819/214161181-28e596cd-4cc1-447c-b3a7-a8a9aa9ee1c7.png">
<img width="995" alt="Screenshot 2023-01-23 at 22 09 19" src="https://user-images.githubusercontent.com/167819/214161190-92be88e4-d6fb-4f9f-beaf-a0a8f593a75c.png">
