### ISSUE TITLE
Sonic Tank armor type Encyclopedia inconsistency

### ISSUE THREAD

**Issue by oldnaari** [OpenRA/OpenRA#20649]
I have noticed that both sonic tank and devastator units have this line in encyclopedia:

```
They are very resistant to bullets and high explosives, but vulnerable to missiles and high caliber guns.
```

But they have different armor types:

Sonic Tank:
```
	Armor:
		Type: light
```

Devastator
```
	Armor:
		Type: heavy
```

Don't know what is the correct way to resolve the inconsistency.

**Comment by abcdefg30** [comment]
It seems like all heavy and light armored vehicles have roughly the same description.

**Comment by oldnaari** [comment]
I suggest using the same entries as in the original Dune for the encyclopedia. I can create a PR if you agree with that idea. It seems such inconsistencies appear there too, but for me, it is ok so long as it is vanilla.

**Comment by Porenutak** [comment]
I think  we already use same Encyclopedia/Armor  entry and as in original D2k. Inconsistency comes from original d2k it self. #20650 looks to me like right way to fix this.
