### ISSUE TITLE
Source code including ApplicationID violates Discord Developer TOS

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#20656]
https://github.com/OpenRA/OpenRA/blob/fe129956bb1b3f7e3231c11f306f7387d36f0630/mods/all/mod.yaml#L39

> d. Developer Credentials
> 
> [You will use any developer credentials (**such as your Application ID**, passwords, keys, tokens, and client secrets) we assign to you solely with your Application and the applicable APIs (and will not permit or enable any other Application to use them) and will treat them as Discord confidential information (as described below). Without limiting the foregoing, you will keep API keys and tokens encrypted in any files or other materials accessible by third parties (other than your Service Providers, subject to Section 12(a)). **For the avoidance of doubt, developer credentials may not be embedded in open source projects.**](https://discord.com/developers/docs/policies-and-agreements/developer-terms-of-service#d-developer-credentials)

Recently, someone told us in Veloren's Discord server that including ApplicationID for Discord Rich Presence in open source code is against the Discord developer TOS.  I checked some other open-source games that I knew had the rich presence feature and found out about this line of code (there are some other lines from specific mods' yaml files).

**Comment by penev92** [comment]
Those ToS mean open-source projects can't have a Discord integration, which is just insane.

**Comment by PunkPun** [comment]
> c. Open Source Software
>
> Some of the software required by or included in our APIs may be offered under an open source license, as may be listed in the Documentation. Open source software licenses constitute separate written agreements. To the limited extent the open source software license expressly supersedes the Terms, the open source license instead sets forth your agreement with Discord solely for the applicable open source software.

**Comment by ghost** [comment]
> To the limited extent the open source software license expressly supersedes the Terms, the open source license instead sets forth your agreement with Discord solely for the applicable open source software.

Does OpenRA have a separate agreement?

**Comment by abcdefg30** [comment]
Thanks for notifying us! The easiest solution is probably moving the ID to a pipeline variable written to a file (like the VERSION file) by the packaging scripts.

**Comment by penev92** [comment]
That again leaves it sitting in plaintext in the installed files, which from a technical side doesn't change anything. Funnily enough sometimes the legal side isn't technically sound though, so idk if it changes anything from a legal side.

**Comment by abcdefg30** [comment]
We cannot hide it from the end user no matter what, but we can move it out of the repository. (Which is how I understood "embedded in open source projects".)

**Comment by abcdefg30** [comment]
For the record: The end result of our Discord discussions was that the ID is merely not be included "for the avoidance of doubt", which is not the same as it being forbidden. (Also, it is written in plain text into the registry/MIME database for the feature to work for any app, so it is unlikely this is actually anything Discord considers an issue.)
