### ISSUE TITLE
Game can start with all players in the same team

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#20653]
It is possible to start a game where all players are in the same team. Then they are allies in game and there is no win condition.

**Comment by abcdefg30** [comment]
Is there a good reason to prevent this? I often start games with "all players" (one player) on the same team while testing things and maps like Fort Lonestar want all players to be in the same team.

**Comment by deniz1a** [comment]
Oh ok it just seemed like a bug to me, I'm closing this issue.
