### ISSUE TITLE
Icons and launchers are not working as sudo make install doesn't work

### ISSUE THREAD

**Issue by jackokring** [OpenRA/OpenRA#20666]
Simple, `sudo install` doesn't work as `dotnet` is not found for the root user account. `./launch-game.sh` works fine. There is no suitable edit of the `*.desktop` files to launch `launch-game.sh Game.Mod=` in the `Exec` line. It freaks and complains with no launch and no errors printed.

Chromebook, Crostini container.

**Comment by Mailaender** [comment]
The correct command is `sudo make install` and `sudo make install-linux-shortcuts` for `.desktop` files. See https://github.com/OpenRA/OpenRA/blob/bleed/INSTALL.md#linux
