### ISSUE TITLE
PT 2023.02.19 cash tick sound dosnt sounds correct

### ISSUE THREAD

**Issue by UppsAlert** [OpenRA/OpenRA#20683]
the cash tick sound dosnt get played correct.
Ignore the buildings placement sound which is also sounds incorrect (other PR)

https://user-images.githubusercontent.com/54892539/219972162-45cc8f2c-b084-4bab-84a9-fbb57c317be0.mp4

**Comment by praetp** [comment]
I also have this problem. Seen on Ubuntu 22.04.

**Comment by abcdefg30** [comment]
This should've been fixed by #20363.
