### ISSUE TITLE
PT 2023.02.19 holding down the building/defence tab key produce a hammering sound

### ISSUE THREAD

**Issue by UppsAlert** [OpenRA/OpenRA#20682]
PT 2023.02.19 holding down the building/defence tab key produce a hammering sound.

https://user-images.githubusercontent.com/54892539/219971606-cfbc2173-cc8e-429d-9053-5917b94c09bf.mp4

This mp4 file includes two different bugs.

**Comment by PunkPun** [comment]
Changing the click sound interrupt type fixes it

```diff
 ClickSound: BUTTON1
-	InterruptType: Interrupt
+	InterruptType: Overlap
```

**Comment by PunkPun** [comment]
Or at least should, I can't reproduce the original issue
