### ISSUE TITLE
VSync does not cap the framerate in windowed mode

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#20681]
![image](https://user-images.githubusercontent.com/756669/219957889-33ed3076-0315-4da7-808c-d1410520dad2.png)

For me, it stays uncapped. VSync works in other games.

**Comment by anvilvapre** [comment]
The game uses https://wiki.libsdl.org/SDL2/SDL_GL_SetSwapInterval in SetVSyncEnabled.
This is specifically for an OpenGL context.
The results is not checked and i.e. SDL_GetError() is not called. 
The hint SDL_HINT_RENDER_VSYNC is not set. Which is said to only apply for the SDL renderer and not the OpenGL context.

Proposal would be to check the result code and log a warning to Graphics.log if VSync could not be enabled.

My assumption, from what i read long ago, was that enabling vsync would only impact glSwapBuffers, that it would only impact the moment when the off screen buffer would be replaced with on screen buffer. To reduce tear. (?)

**Comment by RoosterDragon** [comment]
I can confirm the VSync option is working for me on bleed, and on release-20231010.

Perhaps an SDL update resolved this since this issue was initially reported?

Or perhaps this is environment specific? - I'm on Win 11 for reference.

**Comment by Mailaender** [comment]
I can confirm that it correctly caps the frame rate in windowed mode on a multi monitor setup with both monitors set to 60 Hz using Kubuntu 23.10, so it should be working correctly.
