### ISSUE TITLE
Fix unused translation strings in community mods producing warnings

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#20693]
Community mods may reference the translation from `common|languages/en.ftl` but not need all of them, which will cause the Utility to produce warnings about unused translations.
Reported by @drogoganor for DR, which doesn't use crates, but gets liter errors/warnings about
```Fluent
## CrateSpawner
checkbox-crates =
    .label = Crates
    .description = Collect crates with units to receive random bonuses or penalties
```

Since this can happen to other mods which may not implement a lot more than just crates, I think a good solution would be to **add a list of translation strings to be ignored when linting**. Then DR can add the crate strings and other mods can add whatever they don't need.

**Comment by pchote** [comment]
IIRC there was a plan to split the monster `en.ftl` into smaller files. Having a specific `lobbyoptions-en.ftl` that mods can omit would be a simple fix.

**Comment by penev92** [comment]
That would still require the mod to create its own copy with 90% of the translations, so still not great.
I like @abcdefg30's suggestion better - (find a way to) add support translation removals like we do for traits.

**Comment by pchote** [comment]
IMO the more fundamental thing here is that cnc-specific concepts like crates are in common at all.

**Comment by penev92** [comment]
I *kinda* agree, but let's not forget this could have just as easily been about shroud, fog or the debug menu. So focusing on the crates won't solve the underlying issue.

**Comment by pchote** [comment]
yes, which is why I settled on suggesting that lobby options should be considered separately to the other translations 😉

**Comment by PunkPun** [comment]
The current approach to such translations is to not lint for unused translations. Rather only lint when a required translation is missing. 

We still need to figure out how to properly handle unused strings, especially when it comes to yaml-defined translation id's

**Comment by PunkPun** [comment]
We are no longer showing unused translation strings as errors, updated the titile

**Comment by RoosterDragon** [comment]
What about a property allowing opting-out from the linter checking for unused keys in that file?
```miniyaml
Translations:
	common|languages/en.ftl
		CheckUnusedTranslations: false
	some-mod|languages/en.ftl
```

The linter could have a message added to tell you that this option exists, if it detects any unused keys.

**Comment by pchote** [comment]
The rule updater will automatically skip any files that are imported from another mod - what if we did the same here (but ignoring unused rather than skipping outright)?

Basically the same as @RoosterDragon's suggestion, but implicit.
