### ISSUE TITLE
changed code signature in macOS v 20230225?

### ISSUE THREAD

**Issue by suschizu** [OpenRA/OpenRA#20701]
hello - can you confirm the changed code signature - thanks!

EXPECTED Paul Chote (J9RC5GHDAV)  
FOUND Matthias Mailander (XT33TSN4G6)

**Comment by penev92** [comment]
Hello. That's a change from @pchote to @Mailaender. ~~I don't know how or why~~, but it's still legit. Happened because this time around @Mailaender handled the macos certificates.

**Comment by Mailaender** [comment]
It costs $ 99 annually, and we decided to split the share.
