### ISSUE TITLE
harvesters push engineer aside, ending capture process

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#20716]
latest release,

bug/feature,

engineer tries to capture ref .. while standing in region of ore. many harvesters. harvesters push engineer away(?) while it is trying to capture. ending the capture process. making it impossible for the engineer to capture in the neighbourhood of harvesters and/or units in general.

**Comment by PunkPun** [comment]
Harvesters are allowed to crush enemy engineers. This is a non-issue

**Comment by anvilvapre** [comment]
even when not controlled by player?

**Comment by anvilvapre** [comment]
they weren't crushing, just pushing him aside.

**Comment by PunkPun** [comment]
The engineer got lucky and dodged

**Comment by anvilvapre** [comment]
i was capturing, it didn't dodge. it was mine.

**Comment by penev92** [comment]
I guess the best way to demostrate what happened would be to capture a gif/video or provide the replay.

**Comment by abcdefg30** [comment]
Shouldn't units only be nudged by allied units when they are idle?

**Comment by PunkPun** [comment]
> Shouldn't units only be nudged by allied units when they are idle?

it was nudged, or rather avoided a crush from an enemy unit

**Comment by abcdefg30** [comment]
I thought this was about own units pushing the engineer. If this is about enemy units then this is a wontfix.

**Comment by PunkPun** [comment]
I did mention it in my first comment

**Comment by abcdefg30** [comment]
I interpreted @anvilvapre's answer to that, that it was his harvester that nudged the engineer.

**Comment by PunkPun** [comment]
he was capturing an enemy refinery

**Comment by anvilvapre** [comment]
enemy harvesters did. my engineer was standing in/near ore pits. 

feel free to close.
