### ISSUE TITLE
Generated launcher .exe files are missing metadata

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#20713]
Release 20210321:
![image](https://user-images.githubusercontent.com/7137365/222063473-210a461d-da7d-40ee-aecc-9a6b79dbb529.png)

Release 20230225:
![image](https://user-images.githubusercontent.com/7137365/222063538-9316131c-e23c-43d7-9e3a-95741af57e76.png)
![image](https://user-images.githubusercontent.com/7137365/222063581-33c41d32-0f02-4954-8b37-9f1d14da244d.png)

Obviously due to the switch from .NET 4.7 to .NET 6 (which deals with .exes as an after thought).

**Comment by abcdefg30** [comment]
I guess we could also put a reference to COPYING or AUTHORS in the Copyright field?

**Comment by Mailaender** [comment]
Related: https://github.com/OpenRA/OpenRAWebsiteV3/pull/43

**Comment by pchote** [comment]
IMO the best solution here would be to generate an `AssemblyInfo.cs` dynamically at the start of the packaging scripts. This could then embed the actual build version instead of a dummy 1.0.0.0.

**Comment by penev92** [comment]
I am fairly sure that wouldn't work because the info just doesn't get applied to the EXE, just the DLL.
