### ISSUE TITLE
MacOS m1 pro, m2 pro, left click not working properly anymore

### ISSUE THREAD

**Issue by marcbalas** [OpenRA/OpenRA#20715]
## Issue Summary

DESCRIPTION
[in the lastest release](https://github.com/OpenRA/OpenRA/releases/tag/release-20230225), On MacOS m1 Pro monterey, the single left click doesnt work anymore in the menu and in the game. Now a double click or CMD+click is required to do the left click action.
 It is working in [the previous prerelease](https://github.com/OpenRA/OpenRA/releases/tag/playtest-20230218).
Same behaviour with the trackpad or a mouse. 
 

## Reproduction

STEPS TO REPRODUCE THE ISSUE

[Install release](https://github.com/OpenRA/OpenRA/releases/tag/release-20230225) on a macos m1 pro monterey and launch the game. The single left click does not do allow to click on buttons in the menu.

## Expected behavior

EXPECTED BEHAVIOR

The single left click should be mapped to the same action as previous prerelease.

**Comment by strombirdy** [comment]
I was encountering the same issue. This is the workaround that almost every time works for me:
- do not install the games, just open the dmg and select the game you would like to play
- if left click does not work, just exit the game, unmount the dmg file and re-mount it
this often helps to get the left click working again.

I think this occurs if the Mac was in Standby with mounted DMG oder the DMG stayed open a long time.

**Comment by marcbalas** [comment]
thanks a lot. It works for me too.

**Comment by carefreepineapple** [comment]
I was having the same issue with the m2 pro.  Rather than dealing with the solution above, which is tedious, I opted to roll back to the prior stable build, 20210321.

Easiest way that I found with brew was to uninstall and then download the prior stable cask and install.
```
~$ brew remove openra
~$ wget https://github.com/Homebrew/homebrew-cask/blob/03373d6bc04252aa125cbb64334f19b4cfb8c231/Casks/openra.rb
~$ brew install --cask ./openra.rb
```

**Comment by Mailaender** [comment]
I skimmed https://github.com/libsdl-org/SDL/releases but can't find the issue in the changelog. You could still try to replace the SDL2 binary in OpenRA with a newer one to see if it is fixed or where it regressed.

**Comment by PunkPun** [comment]
Please test wether this [devtest build](https://github.com/PunkPun/OpenRA/releases/download/devtest-20230412/OpenRA-devtest-20230412.dmg) fixes your issue.
