### ISSUE TITLE
Utility doesn't write logs, yet refers you to read the logs

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#20733]
On crash the channel gets added, but nothing is written

https://github.com/OpenRA/OpenRA/blob/939f715e3c1cd82a080a26d57c29b5f049f6f4bb/OpenRA.Utility/Program.cs#L129-L131

This happens because the main process ends before async writing is done. I tried to delay the main process by adding this
```C#
for (var i = int.MinValue; i < int.MaxValue; i++);
for (var i = int.MinValue; i < int.MaxValue; i++);
for (var i = int.MinValue; i < int.MaxValue; i++);
```
after the aforementioned code, and surprise. The utility.log was no longer of 0 bytes length

**Comment by anvilvapre** [comment]
`Log`-ing became multi threaded. It tries to flush all log channel messages to a log file each five seconds. So after five seconds the content should be available?

What seems very odd it that both a thread and a timer are started. Where the thread tries to do constant read and writes to the channel and the timer is used to flush to disk. Both threads access the same channels. Both the timer and thread will respond to the same cancelation token being set.

In `Log.Dispose` the timer may not get time to be triggered a last time - as it is disposed immediately. But the thread should at least always also flush to disk when the cancellation token is set - at the end of `DoWork`.
