### ISSUE TITLE
scroll key sometimes stuck

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#2075]
When I use the keyboard for scrolling sometimes the arrow feels "stuck" as I endlessly scroll into 1 direction. When I press the opposite key the scrolling simply stops instead of going into the different direction. I can only navigate via radar or backspace (to HQ) then. It vanishes after sometime, but it is really annoying. Happens often, but hard to reproduce.
##

**Comment by abcdefg30** [comment]
I can reproduce this on latest bleed.

**Comment by rob-v** [comment]
Fixed by PR #13115
