### ISSUE TITLE
units stance icon reverts after savestate

### ISSUE THREAD

**Issue by BlackenedRA** [OpenRA/OpenRA#20755]
Basically what title says. If you change your units to a different stance and then save the game when you reload the game the unit's stance icon will be back to the default. (The unit will retain whatever stance it was in though)

**Comment by PunkPun** [comment]
did you have them selected?

**Comment by BlackenedRA** [comment]
I'm not sure what exactly you mean?

You can quickly check for yourself. 
Load up a skirmish 
/all
 build some units and switch their stance to another one. 
Save. 
Reload and they stance will visually look as the default stance but they'll retain the stance you gave them.

**Comment by ThomasChr** [comment]
Can reproduce on latest bleed ae1983fabaaaf7878c7076d8c3ea81d882de9488
After loading a save game these three Buggys are in Hold Fire Stance (they don't attack the enemy Ore Truck) - but the Icon is on Defend Stance - which is wrong. 
![image](https://user-images.githubusercontent.com/13014163/226955830-b0df42f3-eeb9-4dda-9073-d78d930a754c.png)

**Comment by ThomasChr** [comment]
This one will fix the problem, but as always I'm not quite sure if I'm at the right location, and if we really need to do that every time when selecting units: #20759

**Comment by ThomasChr** [comment]
When we're loading the savegame we're setting the Stance via the "SetUnitStance"-Order. Which sets the unit in the right Stance.
What we aren't doing is setting PredictedStance - thats why the button is not highlighted.
When clicking the button the called function is StanceSelectorLogic.cs!SetSelectionStance() which sets the PredictedStance and thus changes the button highlight:
![image](https://user-images.githubusercontent.com/13014163/227193326-f394257a-c495-491f-9f21-c51754d1eda6.png)

**Comment by ThomasChr** [comment]
PR #20759 Should fix the bug now the right way.
