### ISSUE TITLE
Utility should not crash before update rules are ran

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#20847]
Currently we crash on yaml errors before update rules even have a chance to run. From 129db98 we resolve yaml before running update rules

This issue was found when the update rule refused to work with the crash `There are no elements with key SpawnMPUnits to remove`. 

This is unacceptable, Instead it should have first ran the `RenameMPTraits` which would have fixed the error.

**Comment by Mailaender** [comment]
You could simply merge those two rules.

**Comment by PunkPun** [comment]
That wouldn't work at all. The issue here is that we resolve yaml before running rules. Merging rules doesn't adressed that, if anything, it would make the situation worse as we wouldn't have the option to run rules that don't need resolving first.

Currently we resolve before every rule, even those which don't need it

**Comment by Mailaender** [comment]
I mean merge the two conflicting/depending update rules.

**Comment by PunkPun** [comment]
If 2 large rules have nothing to do with each other and only depend due to a single variable then it doesn't feel correct

**Comment by penev92** [comment]
I don't see how merging rules would help, but I also think it is a bad idea - we try to have rules be as "immutable" as possible once merged to avoid issues for downstream mods that follow bleed.
