### ISSUE TITLE
Teleport is dysfunctional in current bleed branch!

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20870]
Reported by @EoralMilk 

This bug should be related to https://github.com/OpenRA/OpenRA/commit/ad683d922691aff013ac84d2c023a61d6594fc41, this commit makes the Teleport (and similar traits in third-party mod) dysfunctional. Neither deploy order nor force move order can trigger the Teleport now.

**Comment by PunkPun** [comment]
The third party scripts might be at fault here?
