### ISSUE TITLE
Map preview saving takes incredibly long on massive maps

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#20922]
It feels as if the application is frozen. For testcases see Spinning Earth or World Theatre

This loop is at fault

https://github.com/OpenRA/OpenRA/blob/f794cf69f94bc56db2dcf0d09974b17a9d24f4d1/OpenRA.Game/Map/Map.cs#L808-L854

**Comment by RoosterDragon** [comment]
Turning `positions` into a `Dictionary<MPos, Color>` outside the loops would likely fix that.

**Comment by PunkPun** [comment]
~~maybe a cell layer would be better?~~

ah mb it's MPos

**Comment by anvilvapre** [comment]
perhaps reuse minimap/radar (unsafe) impl.
