### ISSUE TITLE
Not a request just a noob question

### ISSUE THREAD

**Issue by staaandup** [OpenRA/OpenRA#20925]
Hello, I have a newbie question. I want to play Dune 2000 and was wondering if I should download the files in the releases section:
'OpenRA-Dune-2000-x86_64.AppImage'
'OpenRA-Dune-2000-x86_64.AppImage.zsync'
And if I do, where should I put them? And if I shouldn't touch them, could someone please explain what they are?
Also, since I chose to use the portable version of openRA, how can I create a shortcut to openRA because there are only 'OpenRA.Server.exe' and 'OpenRA.Utility.exe', do I need a shortcut, or can I just start Dune2000.exe and play directly?

**Comment by abcdefg30** [comment]
The AppImage files are just usable on Linux, you won't need them on Windows. Starting `Dune2000.exe` is enough to play.

**Comment by staaandup** [comment]
i See, Thanks!

**Comment by abcdefg30** [comment]
You're welcome, hope that resolved your question. :)
