### ISSUE TITLE
Box selecting units in replays should bring up an army value

### ISSUE THREAD

**Issue by BlackenedRA** [OpenRA/OpenRA#20936]
This would be a really nice feature for casting/reviewing replays as it could give incredible insight to just how much value was lost during an attack/defense.

I'm sure it could be extended to live spectators too.

**Comment by dragunoff** [comment]
Do you mean the army value of the selected units? Or the army value stats graph/panel? I think something like #16687 would be a good solution.

**Comment by BlackenedRA** [comment]
yeah this can be closed. I'll add my thoughts to #16687 since that's a more beneficial feature.
