### ISSUE TITLE
Units attacking unreachable causes game freezing

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#20948]
As the number of units being stuck increases, the game will suffer severe lag and sometimes freezing(generally 20 units can freeze the game), and you PC will catch a fever -- I think it is as bad as a crash, or worse. Unlike human player, AI will likely to enclose their units or attack unreachable without any awareness, so this bug is a bomb for any game includes AI players. 

Behold the increasing tick time in this GIF. AI will order more unit like this, then the game will be basically unplayable.
![pathfinding-lag](https://github.com/OpenRA/OpenRA/assets/13763394/dc665e8a-88d8-4b7c-a258-da205c7f75bc)
You can simply reproduce this bug by using units enclosed to attack somewhere unreachable.
update:
1. Units being stuck by enclosed immovable actors can cause greater lags
2. Units being stuck by terrain also cause lag, but not as much as in 1.

This can also lead to an unhealthy gameplay and way to do bad thing that can damage hardware: player can attack unreachable intendly to overheat server and other players' PC while making the game freezing.

**Comment by dnqbob** [comment]
Problem comes from `MoveAdjacentTo`

And `Attack` and `AttackFollow` activity

**Comment by dnqbob** [comment]
The lag is caused by following: 
(i). `MoveWithinRange` check where can attack.
(ii). the horrible pathfinding 4 times on initializing a `Move`
(iii). stuck actor frequently notify other actors that it is stuck and this cell cannot enter
in `Move`

**Comment by PunkPun** [comment]
closed by #21164

**Comment by dnqbob** [comment]
No, I don't think #21164 can solve the issue about lag by unit enclosed.

**Comment by PunkPun** [comment]
it just did

**Comment by dnqbob** [comment]
let me have a test then

**Comment by PunkPun** [comment]
while it isn't a fully effective solution and better perf could be achieved by managing activities better, the perf impact no longer is noticeable by eye

**Comment by dnqbob** [comment]
fix confirmed. We can close this issue.

**Comment by RoosterDragon** [comment]
I wasn't initially expecting this to be helped by #21164, but testing confirms the lag is reduced.

In hindsight, this would be because we do 4 pathfinding attempts with different BlockedByActor settings. Prior to #21164 all 4 attempts would need a full search, leading to a lag spike. With #21164, three of the 4 attempts will instantly fail if you've blocked the units in with buildings, and only the 4th attempt needs a full search.

That means units trapped in only need the cost of one path search now, whereas it could've been up to 4x as expensive before. This means the performance is on par with units not trapped in, which are likely to only need one path search as well.

I didn't expect it, but a nice win!

**Comment by dnqbob** [comment]
[stucky and laggy.zip](https://github.com/OpenRA/OpenRA/files/13256933/stucky.and.laggy.zip)

This is a test map that will freeze the game in previous version. In current version we can see https://github.com/OpenRA/OpenRA/issues/20948 in test map is greatly ceased by https://github.com/OpenRA/OpenRA/pull/21164 but it is still here when enclosed unit is attacking far away places

**Comment by RoosterDragon** [comment]
@dnqbob Can you open a new issue to track that?

**Comment by dnqbob** [comment]
https://github.com/OpenRA/OpenRA/issues/21187

**Comment by dnqbob** [comment]
Guys, I just find https://github.com/OpenRA/OpenRA/pull/21164 is not working for TS.mod.

We need re open this issue.
