### ISSUE TITLE
Credits window doesn't render wordwrapped text correctly

### ISSUE THREAD

**Issue by michaeldgg2** [OpenRA/OpenRA#20971]
## Issue Summary

When `LabelWidget` is configured to wrap text using `WordWrap: True`, the text inside the label is wrapped in terms of maximum width, but long lines overlap with other lines. The reason is that `CreditsLogic.ShowCredits` renders each line from credits file as separate `LabelWidget`

## Reproduction

Remove manual wraps in `AUTHORS` file in the part with credits to libraries/services at the end of the file.

## Expected behavior

The text should be properly wrapped and lines should not overlap with each other.

## Screenshots

![credits_wordwrapping](https://github.com/OpenRA/OpenRA/assets/119738087/8a1c6466-6513-46df-aaa1-0cbe160a790b)

**Comment by sa3047** [comment]
Hi, I would like to work on this issue. I am new to **OpenRA** community, would like to contribute to this project. 
Any help/guidance would be appreciated. thanks in advance.

**Comment by abcdefg30** [comment]
Hi! Feel free to work on this issue. Most of us are available on our [Discord](https://discord.openra.net), so feel free to ask there or here on GitHub if you need any help. For the very basics on contributing we also have https://github.com/OpenRA/OpenRA/wiki/Contributing in our wiki.

**Comment by sa3047** [comment]
@abcdefg30 I have solution ready for this issue, but I have few questions.

1.  How can I get the char width of the CREDITS_PANEL.? I am able to see the width but I think that width is in pixel e.g. (410,460)
2. In which project I should put a common utility function?

Thanks and appreciate your help.

**Comment by PunkPun** [comment]
All classes that inherit `Widget` have the `Bounds` variable. There is also `RenderOrigin`, and `RenderBounds` is the combinations of the 2.

I'm also pretty sure proper wrapping is implemented in quite a lot of places, just can't recall any atm. `LabelWidget` uses `WrapText` which is in the `WidgetUtils` class

**Comment by abcdefg30** [comment]
You can use the `Measure` method of a font to get how long a text is and compare that to the width of the panel.

**Comment by anvilvapre** [comment]
relates #20311
