### ISSUE TITLE
trolls keep pausing/unpausing the game

### ISSUE THREAD

**Issue by vvaezian** [OpenRA/OpenRA#21002]
I have encountered this issue multiple times recently. 

Proposed solution:
- Limit the number of times a player can pause a game (2 times seems reasonable).

**Comment by pchote** [comment]
Playing whack-a-mole on abusable features isn't a great strategy - trolls will simply move onto a new tactic (e.g. stalling the game by dragging the game window / ctrl-z on Linux / etc).

The only really viable approach to deal with people who don't want to play in good faith is to remove them from the game, e.g. via vote-kick.

**Comment by vvaezian** [comment]
I get your point, but I think the proposed PR doesn't improve the current state considerably. After exercising the vote kick, the game would practically end (because of the unbalanced number of players in each team). That would be the same outcome as the current state where people leave after seeing someone keeps pausing/un-pausing.

I think the reliable way for dealing with trolls is to detect them in the game lobby before the game starts, which is not possible currently because people can change their names. Yes there are special servers for subscribed users only, but I believe since the current subscription process is a bit complex, there are many unsubscribed users. If social login gets added, then enforcing logging in would make sense, which could solve the troll issue to a great extend.

**Comment by PunkPun** [comment]
If a person is intent on causing harm it's already an unbalanced number of players, not only is a player not participating in your team, he could be fighting against its interests

I'm also unfamiliar with these subscriber servers, do you mean creating a forum account? That's simple and free of charge.

**Comment by vvaezian** [comment]
By "special servers for subscribed users only" I meant the servers that require forum account. But now I see even for those the user can change their names. 
The point is if users are identifiable by a unique id (which they cannot change, unless they create a new account which requires a new email), then spotting trolls becomes much easier. This requires account creation process and enforcing login for playing the game. While the forum account is fairly straightforward to create, but social login is much simpler for the users. Currently I guess less than third of the users have forum account.

**Comment by anvilvapre** [comment]
Wouldn't it be an idea to let the game always generate a unique id for each player/installation. That would contain an authentation code/value-check. The value would be saved in settings.yaml. The game regenerates it if not set or invalid. Only x mins after generating it allows the player to join a multi player game. The id replaces the IP prefix in the game lobby - is a more private personal user id. It does not replace nick registration. Has no server side components. The id could be regenerated by the player from the settings dialog. During install the id could already be set without requiring any delays.

Only technical players who would take a lot of effort would be able to change the player-id quickly inbetween games.

**Comment by abcdefg30** [comment]
People could simply change the code that is sending the ID to always send a new random one and run their self-compiled build with that.

**Comment by anvilvapre** [comment]
> People could simply change the code that is sending the ID to always send a new random one and run their self-compiled build with that.

yeah, but then they went through a lot of effort to get there. then they are allowed to have their "fun".

**Comment by dnqbob** [comment]
> yeah, but then they went through a lot of effort to get there. then they are allowed to have their "fun".

Actually there is a much simplier way to ruin the gameplay experience without touching code. Player can enclosed 50 infantry by using walls and order them to attack far away place, which can make the game almost freezing.

**Comment by anvilvapre** [comment]
> > People could simply change the code that is sending the ID to always send a new random one and run their self-compiled build with that.
> 
> yeah, but then they went through a lot of effort to get there. then they are allowed to have their "fun".

meaning that's the difference between trolling out of boredom and intentionally wanting to do harm.
