### ISSUE TITLE
Something about Target.Invalid

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#21031]
Run code as following:

```
			var a = Target.Invalid;
			if (a == Target.Invalid)
				TextNotificationsManager.AddSystemLine("=="); // or any other output
			else
				TextNotificationsManager.AddSystemLine("!=");
```

You will always get `!=` as output, which means a var is granted value `Target.Invalid` will never equal to `Target.Invalid`.

Then, we have Autotarget.cs, line 261:
```
			// Respect AutoAttack priorities.
			if (Stance > UnitStance.ReturnFire)
			{
				var autoTarget = ScanForTarget(self, AllowMove, true);

				if (autoTarget != Target.Invalid)  <--- obviously always true
					attacker = autoTarget.Actor;
			}
```

**Comment by abcdefg30** [comment]
https://github.com/OpenRA/OpenRA/blob/aac1bae89980ddeb225f16f2b8a4c1ca0748fb5b/OpenRA.Game/Traits/Target.cs#L243-L244 is the code in question. I think that was deliberate, but seems like we need to re-evaluate that since it is easy to make mistakes.

**Comment by pchote** [comment]
It was deliberate, and changing it is liable to break things in unexpected ways.

Consider something like the following in an activity `Tick` method:
```
if (target != lastTarget)
    doSomething();
lastTarget = target;
```
`doSomething` is evaluated if the target is explicitly changed by other code.
Currently, `doSomething` is *also* evaluated if the target is implicitly changed by said target dying.

This latter case would no longer be true if the equality behaviour changed.

Code that really does want to check that a target isn't invalid should be checking against `autoTarget.Type != TargetType.Invalid`.
