### ISSUE TITLE
AI actors do not fight back when they're being attacked.

### ISSUE THREAD

**Issue by Dzierzan** [OpenRA/OpenRA#21051]
As the title says.

Here's the latest bleed 2f696b2ce758680f61ef2943906c3a3ef10b9fbb where it works:
![bleed](https://github.com/OpenRA/OpenRA/assets/17529329/c929c83e-b753-4fa9-9f92-5d2940ebe0eb)

The latest `prep-2307` commit f4c186b7a6b545c4d2adce896c7959b64794fa85 where it doesn't work.
![prep](https://github.com/OpenRA/OpenRA/assets/17529329/aa5b12c6-186e-4fdf-9e5f-80eca5574e44)

**Comment by PunkPun** [comment]
fixed by #21034
