### ISSUE TITLE
Units should blink when being healed by a medic

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#21068]
![medic](https://github.com/OpenRA/OpenRA/assets/37534529/c69d4acf-9cf6-43f8-9327-accd098e3e7f)

**Comment by JovialFeline** [comment]
Should that apply to the Red Alert mod as well?

https://github.com/OpenRA/OpenRA/assets/4985264/6da0f922-3ba0-416b-8752-9a34108d9757
