### ISSUE TITLE
Modifiers can lead to ReloadDelay becoming 0, freezing the game when unit fires.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#21073]
Noticed a new freeze in GenAlpha after engine update, i assume this is a regression from #20675. The PR adds check for ReloadDelay being defined as 0, but seems to have forgotten about modifiers.

Here's a full scrap upgraded Quad Cannon (ReloadDelay of 1) under the influence of a Speaker Tower (%90 Reload Delay modifier). You can see Selection UI shows its ReloadDelay as 0. Ordering the unit to fire freezes the game. 
![image](https://github.com/OpenRA/OpenRA/assets/7933210/cd49a81d-31b5-472e-9928-6413071d04bd)

On the version before the engine update the same setup still gives 0 as ReloadDelay on the UI, but seems to act same as 1. I think ReloadDelay should be properly capped at 1 to avoid the crash.

**Comment by dnqbob** [comment]
@PunkPun I think we need a crash tag here, this is as severe as a crash.
