### ISSUE TITLE
Paradropping is broken on bleed.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#21078]
Noticed in GenAlpha first again and can reproduce on RA too. They just spawn in air, and jump to ground when ordered to move. Not sure when this one got regressed tho. Only effects the ParatroopersPower, EjectOnDeath on Aircraft work fine.

![image](https://github.com/OpenRA/OpenRA/assets/7933210/fa3e3e6a-9f13-4d9f-b7d9-1c872f0b701e)

**Comment by PunkPun** [comment]
does #21076 fix it?

**Comment by JovialFeline** [comment]
> does #21076 fix it?

It does for me.

**Comment by MustaphaTR** [comment]
> does #21076 fix it?

Yes.
