### ISSUE TITLE
Starting Actor can't be found via LUA WorldLoaded function

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#21091]
Version: playtest

test case:
[luabug.zip](https://github.com/OpenRA/OpenRA/files/12804162/luabug.zip)

This bug is not present in stable 230225 version.

**Comment by abcdefg30** [comment]
Apparently this is a regression from @RoosterDragon's https://github.com/OpenRA/OpenRA/commit/95f675becdf440974c1d73d7efd7a60add6d0c9b.
