### ISSUE TITLE
AttackedGarrisoned does not trigger uncloak

### ISSUE THREAD

**Issue by JovialFeline** [OpenRA/OpenRA#21093]
## Issue Summary

This issue is for bleed. Actors with the AttackGarrisoned trait no longer uncloak with this attack. It appears to stem from https://github.com/OpenRA/OpenRA/pull/20675/commits/fca63d79cc65dfa18d43aee0dc8f8eba3fc35229

## Reproduction

Build a Camo Pillbox in Red Alert, force-attack the ground, and see if the structure uncloaks.

I've also thrown in a test map. This has some cloaked pillboxes, a normal Phase Transport, a Phase Transport with a garrison attack, and a cloaked Turret for comparison.
[ghostbox.zip](https://github.com/OpenRA/OpenRA/files/12818205/ghostbox.zip)

## Expected behavior

A Camo Pillbox should temporarily uncloak when it attacks.

## Screen recordings

Some pillboxes that are visible for the first few moments, before their cloak starts. A cloaked Turret acts as expected:

https://github.com/OpenRA/OpenRA/assets/4985264/87c5d4d4-3877-45d4-a2be-3e048527fc8a

Some pillboxes are detected and return fire, but they remain cloaked:

https://github.com/OpenRA/OpenRA/assets/4985264/51e72003-50af-4848-a516-450889bd5b7f

**Comment by PunkPun** [comment]
Regression from #20675. AttackGarrisoned notifies the infantry inside for attacking instead of the pillbox
