### ISSUE TITLE
AutoCrusher ignore "RequiresCondition"

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#21102]
Version: playtest-20230927

test case:
[test.zip](https://github.com/OpenRA/OpenRA/files/12841760/test.zip)

**Comment by PunkPun** [comment]
Weird. It seems #20386 forgot to make it conditional. One solution would simply be to remove `PausableConditionalTrait` inheritance

**Comment by Porenutak** [comment]
> Version: playtest-20230927
> 
> test case: [test.zip](https://github.com/OpenRA/OpenRA/files/12841760/test.zip)

I forgot to notice that " _PauseOnCondition_" is also ignored.
