### ISSUE TITLE
My map with no errors in Lint check doesnt work on dedicated servers

### ISSUE THREAD

**Issue by airetaM** [OpenRA/OpenRA#21111]
https://resource.openra.net/maps/54567/

Its says it is not compatible with this version (release-20231010) of openra and it works fine when i start it on my own not public server.

There ar no entrys in any of the logs, so it seems like i have no possibility to find out what the problem is.

**Comment by dsimmons87** [comment]
Hi, I've have the same issue on another map. You can find out what the problem is by starting your own dedicated server, then entering as a player and selecting the map so that it pulls it from the Resource Center. If you the check dedicated-server.log for your server it has the error. I've done this for your one and it's:

`[2023-10-11T19:04:27] Failed to load rules for `DefendersII` with error: MiniYaml.Merge, duplicate values
found for the following keys: -LobbyPrerequisiteCheckbox@GLOBALBOUNTY: [-LobbyPrerequisiteCheckbox@GLOBALB
OUNTY (at <no filename available>:490),-LobbyPrerequisiteCheckbox@GLOBALBOUNTY (at <no filename available>
:490)]
`

**Comment by PunkPun** [comment]
The other map in question was https://resource.openra.net/maps/54548/ which errored with 
> Map Timian [RAGL-15] failed lint with error: Image 'hole' does not have any sequences defined. (Actor type `lcrhti`)

**Comment by PunkPun** [comment]
The weird part was that I'm unable to reproduce this error locally. Not with the utility nor with local dedicated server

**Comment by airetaM** [comment]
@PunkPun for my map i can say that the issue was that i fixed the map before by removing this:
`Player:
	-LobbyPrerequisiteCheckbox@GLOBALBOUNTY:`
and added
`Player:
	LobbyPrerequisiteCheckbox@GLOBALBOUNTY:
		Enabled: False
		Locked: True
		Visible: False`
That i had another yaml file with:
`Player:
	-LobbyPrerequisiteCheckbox@GLOBALBOUNTY:`
surely prevented the Lint from detecting the error

**Comment by Porenutak** [comment]
> https://resource.openra.net/maps/54567/
> 
> Its says it is not compatible with this version (release-20231010) of openra and it works fine when i start it on my own not public server.
> 
> There ar no entrys in any of the logs, so it seems like i have no possibility to find out what the problem is.

Probably same issue as #20551 ?

Try to remove all commets and "#" letters in your yaml files.

**Comment by Porenutak** [comment]
> > https://resource.openra.net/maps/54567/
> > Its says it is not compatible with this version (release-20231010) of openra and it works fine when i start it on my own not public server.
> > There ar no entrys in any of the logs, so it seems like i have no possibility to find out what the problem is.
> 
> Probably same issue as #20551 ?
> 
> Try to remove all commets and "#" letters in your yaml files.

Nah its not that issue.

**Comment by Porenutak** [comment]
I start uploading my own maps. And have same issue. No lint errors on my PC, but maps doesn't work on servers.
maps: 
https://resource.openra.net/maps/54620/
https://resource.openra.net/maps/54619/

**Comment by dsimmons87** [comment]
> I start uploading my own maps. And have same issue. No lint errors on my PC, but maps doesn't work on servers. maps: https://resource.openra.net/maps/54620/ https://resource.openra.net/maps/54619/

Those maps aren't even showing up for me in the map selector when I'm trying to get the logs for you.

By the way if anyone else is getting this problem, I've set up a dedicated server called "Z Slow Toaster Server". If you go to that server in the game, and select your map, you can then see the dedicated server log for in on the link below:

http://178.128.163.234/server-log/

**Comment by dsimmons87** [comment]
> I start uploading my own maps. And have same issue. No lint errors on my PC, but maps doesn't work on servers. maps: https://resource.openra.net/maps/54620/ https://resource.openra.net/maps/54619/

Pun pointed out to me that this was D2K not RA which is why it wasn't working for me!

I've got the logs for these now below:

```
[2023-10-12T15:02:26] Map Death Depths Pro- Enhanced 0.95 failed lint with error: Image `rock_decoration01` does not have any sequences defined. (Actor type `rock_decoration01`)
[2023-10-12T15:02:26] Map Death Depths Pro- Enhanced 0.95 failed lint with error: Image `ice_tileset_big0` does not have any sequences defined. (Actor type `ice_tileset_big0`)
[2023-10-12T15:02:26] Map Death Depths Pro- Enhanced 0.95 failed lint with error: Image `ice_tileset_decoration011` does not have any sequences defined. (Actor type `ice_tileset_decoration011`)
[2023-10-12T15:02:26] Map Death Depths Pro- Enhanced 0.95 failed lint with error: Image `ice_tileset_decoration012` does not have any sequences defined. (Actor type `ice_tileset_decoration012`)

[2023-10-12T15:02:35] Map Stone Plateaus - Enhanced 0.95 failed lint with error: Image `rock_decoration01` does not have any sequences defined. (Actor type `rock_decoration01`)
[2023-10-12T15:02:35] Map Stone Plateaus - Enhanced 0.95 failed lint with error: Image `ice_tileset_big0` does not have any sequences defined. (Actor type `ice_tileset_big0`)
[2023-10-12T15:02:35] Map Stone Plateaus - Enhanced 0.95 failed lint with error: Image `ice_tileset_decoration011` does not have any sequences defined. (Actor type `ice_tileset_decoration011`)
[2023-10-12T15:02:35] Map Stone Plateaus - Enhanced 0.95 failed lint with error: Image `ice_tileset_decoration012` does not have any sequences defined. (Actor type `ice_tileset_decoration012`)
```

I've also put up a d2k server as above so you can load the map on it and check the logs if you need to while trying to get it to work

**Comment by airetaM** [comment]
@dsimmons87

> By the way if anyone else is getting this problem, I've set up a dedicated server called "Z Slow Toaster Server". If you go to that server in the game, and select your map, you can then see the dedicated server log for in on the link below:

Thank you that really helps, it seems like this problem is affecting many of my modmaps.

**Comment by Therapist1911** [comment]
> > I start uploading my own maps. And have same issue. No lint errors on my PC, but maps doesn't work on servers. maps: https://resource.openra.net/maps/54620/ https://resource.openra.net/maps/54619/
> 
> Pun pointed out to me that this was D2K not RA which is why it wasn't working for me!
> 
> I've got the logs for these now below:
> 
> ```
> [2023-10-12T15:02:26] Map Death Depths Pro- Enhanced 0.95 failed lint with error: Image `rock_decoration01` does not have any sequences defined. (Actor type `rock_decoration01`)
> [2023-10-12T15:02:26] Map Death Depths Pro- Enhanced 0.95 failed lint with error: Image `ice_tileset_big0` does not have any sequences defined. (Actor type `ice_tileset_big0`)
> [2023-10-12T15:02:26] Map Death Depths Pro- Enhanced 0.95 failed lint with error: Image `ice_tileset_decoration011` does not have any sequences defined. (Actor type `ice_tileset_decoration011`)
> [2023-10-12T15:02:26] Map Death Depths Pro- Enhanced 0.95 failed lint with error: Image `ice_tileset_decoration012` does not have any sequences defined. (Actor type `ice_tileset_decoration012`)
> 
> [2023-10-12T15:02:35] Map Stone Plateaus - Enhanced 0.95 failed lint with error: Image `rock_decoration01` does not have any sequences defined. (Actor type `rock_decoration01`)
> [2023-10-12T15:02:35] Map Stone Plateaus - Enhanced 0.95 failed lint with error: Image `ice_tileset_big0` does not have any sequences defined. (Actor type `ice_tileset_big0`)
> [2023-10-12T15:02:35] Map Stone Plateaus - Enhanced 0.95 failed lint with error: Image `ice_tileset_decoration011` does not have any sequences defined. (Actor type `ice_tileset_decoration011`)
> [2023-10-12T15:02:35] Map Stone Plateaus - Enhanced 0.95 failed lint with error: Image `ice_tileset_decoration012` does not have any sequences defined. (Actor type `ice_tileset_decoration012`)
> ```
> 
> I've also put up a d2k server as above so you can load the map on it and check the logs if you need to while trying to get it to work


Thanks dsimmons87. Your log helped a lot and I was able to fix my maps. I don't understand why OpenRA's log doesn't show this information. It doesn't seem like it should be too much of a problem to at least make the utility catch these errors. No sequences defined and missing files.

**Comment by dsimmons87** [comment]
> > > I start uploading my own maps. And have same issue. No lint errors on my PC, but maps doesn't work on servers. maps: https://resource.openra.net/maps/54620/ https://resource.openra.net/maps/54619/
> > 
> > 
> > Pun pointed out to me that this was D2K not RA which is why it wasn't working for me!
> > I've got the logs for these now below:
> > ```
> > [2023-10-12T15:02:26] Map Death Depths Pro- Enhanced 0.95 failed lint with error: Image `rock_decoration01` does not have any sequences defined. (Actor type `rock_decoration01`)
> > [2023-10-12T15:02:26] Map Death Depths Pro- Enhanced 0.95 failed lint with error: Image `ice_tileset_big0` does not have any sequences defined. (Actor type `ice_tileset_big0`)
> > [2023-10-12T15:02:26] Map Death Depths Pro- Enhanced 0.95 failed lint with error: Image `ice_tileset_decoration011` does not have any sequences defined. (Actor type `ice_tileset_decoration011`)
> > [2023-10-12T15:02:26] Map Death Depths Pro- Enhanced 0.95 failed lint with error: Image `ice_tileset_decoration012` does not have any sequences defined. (Actor type `ice_tileset_decoration012`)
> > 
> > [2023-10-12T15:02:35] Map Stone Plateaus - Enhanced 0.95 failed lint with error: Image `rock_decoration01` does not have any sequences defined. (Actor type `rock_decoration01`)
> > [2023-10-12T15:02:35] Map Stone Plateaus - Enhanced 0.95 failed lint with error: Image `ice_tileset_big0` does not have any sequences defined. (Actor type `ice_tileset_big0`)
> > [2023-10-12T15:02:35] Map Stone Plateaus - Enhanced 0.95 failed lint with error: Image `ice_tileset_decoration011` does not have any sequences defined. (Actor type `ice_tileset_decoration011`)
> > [2023-10-12T15:02:35] Map Stone Plateaus - Enhanced 0.95 failed lint with error: Image `ice_tileset_decoration012` does not have any sequences defined. (Actor type `ice_tileset_decoration012`)
> > ```
> > 
> > 
> > I've also put up a d2k server as above so you can load the map on it and check the logs if you need to while trying to get it to work
> 
> Thanks dsimmons87. Your log helped a lot and I was able to fix my maps. I don't understand why OpenRA's log doesn't show this information. It doesn't seem like it should be too much of a problem to at least make the utility catch these errors. No sequences defined and missing files.

No probs. I just put this up as I saw few people were having this issue, but I'm not involved with the game engine at all. Pun was in in those conversations and the devs do check here, so I'm sure it's something they are are aware of and probably planning to fix.

**Comment by Kevwaggy** [comment]
hey @dsimmons87 I'm having this same issue, i see your server is still there but i can't access the logs?

**Comment by dsimmons87** [comment]
> hey @dsimmons87 I'm having this same issue, i see your server is still there but i can't access the logs?

Sorry, that's back up now

**Comment by Uienbrok** [comment]
@dsimmons87 I'm also experiencing this. Can't get my modmap to run on a dedicated server. Can't find the Z Slow Toaster Server though. Is it down? I'm looking for the ra server.

**Comment by dsimmons87** [comment]
> @dsimmons87 I'm also experiencing this. Can't get my modmap to run on a dedicated server. Can't find the Z Slow Toaster Server though. Is it down? I'm looking for the ra server.

Oh yea it looks like it died with an unhandled exception. I'll paste it below in case it's any use to you, but the server should be back up now.

`Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenRA.Mods.Common.Server.LobbyCommands.ClientJoined(Server server, Connection conn) in /home/runner/work/OpenRA/OpenRA/OpenRA.Mods.Common/ServerTraits/LobbyCommands.cs:line 1349
   at OpenRA.Server.Server.<>c__DisplayClass62_0.<ValidateClient>g__CompleteConnection|0() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Server/Server.cs:line 580
   at OpenRA.Server.Server.<>c__DisplayClass62_1.<ValidateClient>b__5() in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Server/Server.cs:line 684
   at OpenRA.Server.Server.CallbackEvent.OpenRA.Server.Server.IServerEvent.Invoke(Server server) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Server/Server.cs:line 1521
   at OpenRA.Server.Server.<>c__DisplayClass55_0.<.ctor>b__2(Object _) in /home/runner/work/OpenRA/OpenRA/OpenRA.Game/Server/Server.cs:line 364
Aborted (core dumped)
`

**Comment by Kevwaggy** [comment]
I have no idea what to do with this information, the line isn't in any of my added .yamls

`duplicate values found for the following keys: -IgnoredEnemyTargetTypes: [-IgnoredEnemyTargetTypes (at :6174),-IgnoredEnemyTargetTypes (at :6174)]
[2023-12-02T15:13:51] Player @[ip masked]:59270 is NotReady`

**Comment by dsimmons87** [comment]
> I have no idea what to do with this information, the line isn't in any of my added .yamls
> 
> `duplicate values found for the following keys: -IgnoredEnemyTargetTypes: [-IgnoredEnemyTargetTypes (at :6174),-IgnoredEnemyTargetTypes (at :6174)] [2023-12-02T15:13:51] Player @[ip masked]:59270 is NotReady`

I'd ask on the OpenRA discord as there's a lot of people there that can help

**Comment by Uienbrok** [comment]
> I have no idea what to do with this information, the line isn't in any of my added .yamls
> 
> `duplicate values found for the following keys: -IgnoredEnemyTargetTypes: [-IgnoredEnemyTargetTypes (at :6174),-IgnoredEnemyTargetTypes (at :6174)] [2023-12-02T15:13:51] Player @[ip masked]:59270 is NotReady`

Maybe something is inherited twice?

**Comment by Therapist1911** [comment]
hey, @dsimmons87. Your Z Slow Toaster Server is not visible in the server list. I need to fix some maps so I need to use your server. Thanks.

**Comment by dsimmons87** [comment]
> hey, @dsimmons87. Your Z Slow Toaster Server is not visible in the server list. I need to fix some maps so I need to use your server. Thanks.

Yes, sorry it died somehow. It's on a pretty weak server somewhere on the internet and I think it's maxing out the RAM, so I've killed MySQL on there which was using a lot which might stop it dying

**Comment by RoosterDragon** [comment]
I've been able to determine the root cause of the issue, and #20965 fixes this. So once the next release is available, these errors will stop appearing. The errors were a bug - there was nothing wrong with the maps.

The cause happens during the Merge step for MiniYaml files. Where we take multiple inputs files and produce a single combined output file.

When handling removal nodes, e.g. `-LobbyPrerequisiteCheckbox` - there was a bug where we would modify the *input* by mistake.

When using the resource centre, we receive a single input and mess it up. When we deal with it again later, we've introduced duplicate nodes and cause an error. The error will either be complaining about duplicate nodes, or it will be a side effect or a removal processing twice. e.g. an error about missing sequences because we removed them when they were still needed. Conversly when the map is loaded locally, we are always loading a fresh copy of the input file, so when we mess it up we get away with it because we don't use it again afterwards.

#20965 fixes this by making it impossible to modify the input files, so now it's impossible to mess them up.
