### ISSUE TITLE
Old assets installation from the Remaster does not work in all cases

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#21129]
Reported by @xcom169 in https://github.com/OpenRA/OpenRA/issues/18239#issuecomment-1761304146 with the path `D:\SteamLibraryHdd\steamapps\common\CnCRemastered`. TiberianDawnHD can find the assets, which means that the setup for RA and TD is likely incomplete.

**Comment by tinix0** [comment]
It seems that paths in libraryfolders.vdf have backslashes escaped and they do not get unescaped while looking for the files, which messes with FS.ResolveCaseInsensitivePath splitting. If I manually unescape the backslashes in debugger the files get detected and installed correctly.

**Comment by xcom169** [comment]
Only the next stable in 2026 will contain this fix?
