### ISSUE TITLE
lost maps and game saves on snap

### ISSUE THREAD

**Issue by Janevski** [OpenRA/OpenRA#21139]
On Ubuntu 22.04, i am using OpenRA installed via snap, current version is:
openra                     release-20231010  1409   latest/stable    lucyllewy*   -

And today, all of a sudden, when i start OpenRA, all my custom maps and savegames are missing.

Expected behaviour is to not lose data across those dreaded automatic snap upgrades.

**Comment by PunkPun** [comment]
No data is lost, the maps are just a in a different folder. If they aren't modded you can just transfer them to the new version and they should work

On linux the path to the app support directory should be `~/.config/openra` or to put in in a nother way `$XDG_CONFIG_HOME/openra/openra`
