### ISSUE TITLE
About applying fast inverse sqrt root in OpenRA

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#21163]
The sqrt calculation in OpenRA is not cheap, do we have any possibility to use fast inverse sqrt root from Quake?

https://betterexplained.com/articles/understanding-quakes-fast-inverse-square-root/

**Comment by RoosterDragon** [comment]
Do you have an example of the sqrt calculation in OpenRA causing slowness for you?

Since the inverse sqrt, `1/sqrt(x)`, is different then  `sqrt(x)`, we can't use that suggestion since it's calculating something different.

**Comment by dnqbob** [comment]
> Do you have an example of the sqrt calculation in OpenRA causing slowness for you?

Our sqrt has a loop in calculation, I think it can be optimized.

> Since the inverse sqrt, 1/sqrt(x), is different then sqrt(x), we can't use that suggestion since it's calculating something different.

Maybe simply 1/(1/sqrt(x)) will do without loop?

**Comment by pchote** [comment]
The fast inverse square root algoirthm only works for floating point numbers. OpenRA's implementation is specifically for operating on integers. There is nothing to be done here.
