### ISSUE TITLE
Rare crash related to SpawnActorOnDeath/Building (get trait from destroyed actor)

### ISSUE THREAD

**Issue by michaeldgg2** [OpenRA/OpenRA#21161]
## System Information

- Operating System:  Windows 8.1
- OpenRA Version: bleed (some time from 10/2023)
- OpenRA Mod: OpenE2140 (but likely reproducible in vanilla OpenRA)
- Source: self-compiled

## Exception log
```
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (world 0 (not in world))
at OpenRA.TraitDictionary.CheckDestroyed(Actor actor) in E:\Dev\OpenRA\OpenE2140\engine\OpenRA.Game\TraitDictionary.cs:line 84
at OpenRA.TraitDictionary.Get[T](Actor actor) in E:\Dev\OpenRA\OpenE2140\engine\OpenRA.Game\TraitDictionary.cs:line 89
at OpenRA.Actor.Trait[T]() in E:\Dev\OpenRA\OpenE2140\engine\OpenRA.Game\Actor.cs:line 382
at OpenRA.Mods.Common.Traits.Building..ctor(ActorInitializer init, BuildingInfo info) in E:\Dev\OpenRA\OpenE2140\engine\OpenRA.Mods.Common\Traits\Buildings\Building.cs:line 289
```

## Additional information
Unfortunately repro steps are (currently) unknown. It happened in OpenE2140 while the Power Plant had been exploding (i.e. when `SpawnActorOnDeath` kicked in).

![opene2140_powerplant_explosion](https://github.com/OpenRA/OpenRA/assets/119738087/59444363-19ab-4030-a308-70e2351a7609)

OpenE2140 uses original, unmodified `SpawnActorOnDeath` and `Building` traits. Here are the definitions of the Power Plant building (`shared_buildings_power_plant`) and the crater actor (`power_plant_crater`):

https://github.com/OpenE2140/OpenE2140/blob/4999e3d102d5bebd2ce913892aaac0e21dd4b154/mods/e2140/content/shared/buildings/power_plant/rules.yaml

(`shared_mcu_power_plant` is not relevant, it's MCV-type actor to construct the Power Plant)

**Comment by abcdefg30** [comment]
What killed the power plant? There should be no way the `world` actor is destroyed while a game is still running which hints at a bug in custom code.

**Comment by michaeldgg2** [comment]
Actually, I think the crash happened while I was trying to exit the game (via Alt+F4), so that would explain the World actor being destroyed.

And as I said both `SpawnActorOnDeath` and `Building` traits have not been touched in OpenE2140. If I had even slightest feeling that my code would cause this, I would not report this as an issue, believe me.

Unfortunately as much as I want to, I'm not able to reproduce this, so I understand there's not much you (devs) or I (modder/coder) can do about this now.

**Comment by Mailaender** [comment]
Closing as a non-existing world is an invalid game state. Nothing to be fixed here.
