### ISSUE TITLE
out of sync in frame 1

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#21189]
ra: Red Alert (release-20231010)

multi player game stopped working - did not crash - just now.

out of sync in frame one.

possibly because the game started while at the same time i was still joining as spec. not sure.

```
Sync Report System Info:
Out of sync frame: 1
Recorded frames: 0,0,0,0,0,0,0
Recorded frames do not contain the frame 1. No sync report available!
```

**Comment by basilin642** [comment]
Could you please add some information?

like your OS, runtime version, distrib source, log file, replay file...
I suppose it will be helpful)))

**Comment by abcdefg30** [comment]
We can't really do anything here without syncreports, or a reproduction case.
