### ISSUE TITLE
Artillery on RA shelmap doesn't render explosions when hitting terrain

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#21213]
https://github.com/OpenRA/OpenRA/assets/37534529/6a354dcd-654e-41f1-ad8e-70399ef6405b

**Comment by alex-buchanan** [comment]
Is anyone currently working this issue, would like to become a contributor if possible?

**Comment by PunkPun** [comment]
It seems to be related to paratroopers, we should first investigate wether #21076 fixes it

**Comment by JovialFeline** [comment]
> It seems to be related to paratroopers, we should first investigate wether #21076 fixes it

What tests I've done seem to confirm both.

**Comment by PunkPun** [comment]
I saw the videos on discord, thanks for confirming,
