### ISSUE TITLE
Carryall is trying pick up Harvester while its still in the Factory

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#21229]
Version: Bleed

https://github.com/OpenRA/OpenRA/assets/100044015/a593d0e2-f713-48ab-8ced-111ee132ec0d

**Comment by tysonliddell** [comment]
I'd like to have a go at fixing this.

**Comment by penev92** [comment]
@tysonliddell ok, great!
Keep in mind that if you need to discuss anything it's easiest to reach us on Discord.

**Comment by PunkPun** [comment]
Is it fixed by #21076 ?

**Comment by tysonliddell** [comment]
@PunkPun it looks like it 🎉. I cannot reproduce the error when checking out 56bbb7d0eba26d777dbf4a29a014609455796712, the tip of your `fix-transports` branch.

**Comment by tysonliddell** [comment]
In particular, it's bac3bfe81e701a5f06d86823aefd38c4dde3c113 that fixes it.

**Comment by Porenutak** [comment]
> Is it fixed by #21076 ?

Confirm, #21076 fix this issue.
