### ISSUE TITLE
TS Power plant plugs are rendered incorrectly

### ISSUE THREAD

**Issue by CDVoidwalker** [OpenRA/OpenRA#21256]
## Issue Summary

The plugs are not rendered as in original game. First upgrade is not visible at all, second adds in the spot to the left, middle slot remains empty.

## Reproduction

Add plugs to power plant.

## Expected behavior

The plugs are rendered on their respective places

## Screenshots / Screen recordings / Replays

Here's example of upgraded power plants with plugs 0, 1, 2 from left to right.
![image](https://github.com/OpenRA/OpenRA/assets/25931859/1268f43e-3a58-4a73-ab8f-8d4707b55a6d)

**Comment by PunkPun** [comment]
related #15049, #13968, #14335
