### ISSUE TITLE
Is the localization system coming soon?

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#21264]
We have extacted most of the localization text so far, so could we apply the localiztion system quickly and then we have some tests on font and line break for non-English language?

**Comment by PunkPun** [comment]
One of the next steps would be allowing localisation itself. Though when it comes to UI resizing it's definitely not happening any time soon. There's currently no plans nor man power to take on that task. #3774

Before we rush ahead and allow localisation we should go over all the current translation keys and polish them up. That's a prerequisite for next release.

related #10475

**Comment by PunkPun** [comment]
related #10475

**Comment by PunkPun** [comment]
#20693 will also need to be addressed for next release
