### ISSUE TITLE
Attack move is broken if unit have multiple armaments

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#21266]
Trike and Raider use Two Armaments. One for damage and one just for muzzle effect.
In first video you can see how Attack move behave if muzzle armament is on:

https://github.com/OpenRA/OpenRA/assets/100044015/6682e9bd-07b9-4226-9048-50d9dcd0f9be

after killing infantry in range unit stuck and wouldnt attack even if you order Attack move again. You must use manual targeting or move command. This is annoing in heat of combat.

On second video is how Raider behave without muzzle armament (and how it should behave):

https://github.com/OpenRA/OpenRA/assets/100044015/2b871998-26e3-4034-ac6c-4beedba8668c

Its even worst for trikes. muzzle have negative offset there. Increasing muzzle range in weapon definition to mach primary armament doenst fix this.

I was trying to fix this almost a year with Trying various range variables for muzzle or primary weapon. But it still sometimes happend and sometime not. I have multipley replays where ppl still complain about this.

Key balance here is that Trike must 0.5 more range that infantry, so it can kill LI in first 2 sub-cells but must move forward to kill the rest.

Best solution would be if we somehow can exclude muzzle armament from searching for targets. And tell engin that it is just a decoration.

test case:
[muzzleBug.zip](https://github.com/OpenRA/OpenRA/files/13715760/muzzleBug.zip)

Ps. same bug happen for Fremen when you use Attack everything commander agains buildings.

**Comment by PunkPun** [comment]
Why do you need a separate muzzle armament? Just reuse the same?

**Comment by Porenutak** [comment]
Because muzzle effect show itself 3x per shot.

**Comment by Porenutak** [comment]
Now when I thinking about it, could we define muzzle as anim with 3 same frames per angle?

**Comment by Porenutak** [comment]
My assumption with trike here was wrong. This happens only if armaments have different range. So if the muzzle is on same range as primary armamant it didnt stuck (But still move to close to the target that it should - but that is not part of this issue )
Fremen unit have 2 armaments with different range and is affected by this bug:

https://github.com/OpenRA/OpenRA/assets/100044015/4b508348-9275-4e20-bc55-16da96765314

**Comment by PunkPun** [comment]
This isn't a bug, but a feature. We want to support fake weapons.

The bug in d2k was fixed in #21267

**Comment by Porenutak** [comment]
Trike bug will be fixed here: #21900
but Fremen issue in video above is still present. This is because Fremen use 2 armament with different range but same target types. (this is not a problem for unit using multiple armaments but for different target types.)
This will be fixed in upcoming balance patch where fremen will have same range for both weapons.
