### ISSUE TITLE
Strange Stuff Going on

### ISSUE THREAD

**Issue by jedininja28** [OpenRA/OpenRA#21270]
Hey, I have been having some real crappy issues with the game engine, where it will lag out my mouse, or bog down the tick timer to  screw with gameplay. i encountered this same error on Fortnite for ps4, 5 and pc versions. its a real pos glitch, it also seems to screw with the audio quantization at iteration points to (spoof) bs into the audio. 

I do not have a reliable internet connected but I will try to leave the game client loged in in order to report issues.

Also, which version of ORA has the c&c3 build menu in ra?

**Comment by abcdefg30** [comment]
Hi. We can't help you further without any (of the performance) logs or other information from the game. You can try changing to borderless window mode in the settings or experiment with VSync or other options in the display settings.

There is no default OpenRA mod which has multi-queues in RA, only Tiberian Dawn has it.
