### ISSUE TITLE
Do not use IOrderEnumerable as fields.

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#21283]
Minor improvement.

In below two files a `teams` field of type `IOrderEnumerable` is used. Proposal to replace them with an List/array to allow for faster access. 

OpenRA.Mods.Common/Widgets/Logic/Ingame/ObserverShroudSelectorLogic.cs
OpenRA.Mods.Common/Widgets/Logic/Ingame/ObserverStatsLogic.cs

IOrderEnumerable seems to sort keys in the call to `GetEnumerator`. Which would mean sorting would take place each time when iterated - each `for` loop. https://referencesource.microsoft.com/#System.Core/System/Linq/Enumerable.cs,2543

**Comment by RoosterDragon** [comment]
We'd likely want to convert the entire `world.Players.Where(...).GroupBy(...).OrderBy(...)` chain. But unless it's a hotspot, the LINQ is much easier to understand than the equivalent code without LINQ. Do you have some performance numbers that would let us judge if this is a worthwhile change?

**Comment by anvilvapre** [comment]
My propsal was simpler. To just call ToArray at the end and to store the list. Then at least the sorting would not happen more often. Only in the second case/file i noticed a for loop over the `teams` field. In that loop the sorting is no longer even relevant i believe (not sure if remem correct).

So to transform them to an array or list.

**Comment by RoosterDragon** [comment]
If the results can't change, yes that makes sense.
