### ISSUE TITLE
Portable Install on macOS

### ISSUE THREAD

**Issue by kelvSYC** [OpenRA/OpenRA#21288]
## Motivation
Some documentation suggests the ability to have a "portable install" of OpenRA, wherein the game files needed from the original games are installed to a folder named `Support`, rather than at `Library/Application Support/OpenRA`. However, when trying to place the `Support` folder in the same directory as the OpenRA executable(s) and moving the files from the default location to the `Support` folder, OpenRA is unable to find the game assets.

Not tested is having a symlink in `Library/Application Support/OpenRA`, but that would still not be nearly as portable as desired.

A cursory glance at the source code suggests that the `Support` folder might need to be located inside the application bundle, which inhibits the ability to upgrade the app itself.

## Proposed solution
Allow for the `Support` folder to be in the same directory as the application bundle, rather than possibly inside. A cursory glance at the source code suggests that some files in `Library/Application Support/OpenRA` are best left there, while others are best left in `Support`, but there seems to be an implication that this is an all-or-nothing affair.

## Side effects
This proposed solution may have side effects relating to the installation of the game assets, wrt whether they go in the default or `Support` directories, that the application might not be able to adequately answer in a cross-platform way.

## Alternatives
Not tested was the symlinking of the `cnc` or `ra` directories in `Library/Application Support/OpenRA` to locations within the application directory.

**Comment by abcdefg30** [comment]
From @pchote on Discord:
> it is if they want to write a script to launch it from the commandline setting the Engine.SupportDir argument, otherwise no
the .app is read-only and signed so its not possible to use a support dir in the engine dir
