### ISSUE TITLE
Desync related to Hovers

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#21297]
At 0741439dd6face978a46bf3b0e7a3e4f363280b2
[disnyc.zip](https://github.com/OpenRA/OpenRA/files/13919524/disnyc.zip)

**Comment by dnqbob** [comment]
I think it is due to we change WorldVisualOffset in renderer instead of logic ticker.
![捕获](https://github.com/OpenRA/OpenRA/assets/13763394/af71e8f0-5af7-45d1-b497-14b0f21c5a47)

**Comment by PunkPun** [comment]
#21252
