### ISSUE TITLE
Game partially freezes when in map editor you press the play button, and then exit map editor

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#21290]
It seems #20120 had the issue on being merged. How did we not catch it :notlikethis:

debugging revealed that the issue seems to lie in `OrderManager.World` becoming null, which then makes `Game.IsCurrentWorld` check false

**Comment by Mailaender** [comment]
Maybe fix this in UI? Just disable the menu faster like in https://github.com/OpenRA/OpenRA/pull/21498.

**Comment by PunkPun** [comment]
Rather, a new OrderManager is created which doesn't have a reference to World
