### ISSUE TITLE
ValidRelationships on Captures Trait is broken 

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#21304]
version: bleed

If you set ValidRelationships  on Captures to Neutral u be able to capture all units (enemy, neutral, ally)
if you set ValidRelationships  to Enemy or Ally you cant capture anything (including Enemy or Ally)

testcase:
In CnC mod change ValidRelationships in engineer Captures@CATURESHUSK:

or try this testcase in d2k:
[husktest.zip](https://github.com/OpenRA/OpenRA/files/13962134/husktest.zip)

**Comment by PunkPun** [comment]
related #21055

**Comment by Porenutak** [comment]
Infiltrates is also broken if you have multiple Capturable traits in Actor

**Comment by Porenutak** [comment]
Problem was elsewhere. Closing
