### ISSUE TITLE
Carryall spawned as starting units or via script are not flying Idle

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#21305]
version: bleed

Testcase:
[carrytest.zip](https://github.com/OpenRA/OpenRA/files/13962196/carrytest.zip)

**Comment by PunkPun** [comment]
I suppose we could give call TakeIff activity to starting units #21076

**Comment by PunkPun** [comment]
or it might actually make more sense to spawn aircraft at cruise altitude

**Comment by abcdefg30** [comment]
Yes that would be the preferred solution.
