### ISSUE TITLE
Huge pathfinding cost when unit stand on immobile terrain needs to move to attack

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#21301]
Testcase: use https://github.com/ABrandau/Shattered-Paradise-SDK/commit/368813f870745f58720ba646eaa14682d578ac97
(engine version 0741439dd6face978a46bf3b0e7a3e4f363280b2)

1. Choose map with cliffs
2. Use Mutant faction, build Queens
3. Make the queen spawn egg on cliff, wait for hatching
4. Build a fast unit (for example, Ravager) attracts the unit that stuck on cliff, then move out its attack range
5. Huge lag

**Comment by PunkPun** [comment]
the solution is to not spawn units on impassable terrain. The pathfinder was designed to handle this scenario in case of bugs, but it's not done efficiently

**Comment by dnqbob** [comment]
![无标题](https://github.com/OpenRA/OpenRA/assets/13763394/ea3fac55-0045-4e09-aead-50ca8312ecd5)
