### ISSUE TITLE
Units can move over pre-placed aircraft on the ground

### ISSUE THREAD

**Issue by michaeldgg2** [OpenRA/OpenRA#21339]
## Issue Summary

Aircraft, which are pre-placed in the editor, can be run over other units.

## Reproduction

Place aircraft in editor, play the map and try moving any unit on the cell with the aircraft.

## Expected behavior

Units should not move over aircraft, when it's on the ground.

## Screenshots / Screen recordings / Replays

![openra_aircraft_influence_bug](https://github.com/OpenRA/OpenRA/assets/119738087/c5ae06d8-f6a5-487e-8d6a-80afc6c8e3d4)

At the time of writing, it's reproducible on [current bleed](https://github.com/OpenRA/OpenRA/commit/12e1d327eff1759bd8a9d452f8baf10a1513ced2).

**Comment by PunkPun** [comment]
the solution might want to address #21305 as well
