### ISSUE TITLE
Random crash related to HierarchicalPathFinder

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#21330]
version: bleed

I get these  random crashes on my various WIP branchs.

this one is purely from bleed:
[exception-2024-02-05T103004Z.log](https://github.com/OpenRA/OpenRA/files/14164381/exception-2024-02-05T103004Z.log)

replay:
[Crash-replay.zip](https://github.com/OpenRA/OpenRA/files/14164397/Crash-replay.zip)

map:
[01scriptrework.zip](https://github.com/OpenRA/OpenRA/files/14164404/01scriptrework.zip)

In a replay I was going with carryall to the map edge and pick up vehicle. Carrayll start idle move beyound map region and game crash. BUT cant reproduce!

Second example also from current bleed (without any custom code):

Replay:
[replay.zip](https://github.com/OpenRA/OpenRA/files/14164472/replay.zip)

Map:
[buildingvfx.zip](https://github.com/OpenRA/OpenRA/files/14164474/buildingvfx.zip)

**Comment by PunkPun** [comment]
> purely from bleed

please link the head commit on which you tested on

**Comment by Porenutak** [comment]
https://github.com/Porenutak/OpenRA/commit/feadfccf712d85d1c214ee68c6e2585ec06ec003

**Comment by Porenutak** [comment]
But if you try map above, just on bleed the resoult should be the same.

**Comment by LipkeGu** [comment]
![CrushAbleCanbeNull](https://github.com/OpenRA/OpenRA/assets/2057932/16ddd184-cc15-403d-9e3e-17475130319f)

**Comment by LipkeGu** [comment]
fixed with #21328
