### ISSUE TITLE
Scroll bug when chat is opened

### ISSUE THREAD

**Issue by soyilai** [OpenRA/OpenRA#21344]
## Issue Summary

Opening the chat while scrolling down with the down key, the camera keeps moving

## Reproduction

1. Enter a game
2. While in-game, hold the down key
3. While holding the down key, open the chat with enter

## Expected behavior

Stop scrolling when another action interrupts it.

## Screenshots / Screen recordings / Replays

Can't do right now.

**Comment by rivest-oss** [comment]
Bug in action (screen recording):
    https://github.com/OpenRA/OpenRA/assets/71992692/a529fd44-b157-445b-b07c-11dd7c5f576e

Ctrl + J is what the screen recorder uses to start/stop the recording itself.
