### ISSUE TITLE
sort users on graph in view mode in order

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#21374]
as spectator or in replays, its hard too see who has the most income. Sorting the users according to all or some ticks will help that. 
![Screenshot_20240324_02341422](https://github.com/OpenRA/OpenRA/assets/526956/ecb0d570-b153-4b11-a81d-bcccad1b78b1)

**Comment by ryanjschneebaum** [comment]
Hello! I am a senior in college studying computer science and am really interested in contributing to the project, but am new to open source contribution. I would love to attempt implementing this fix so please let me know if I could take this on and if I can please let me know if there's anything I should do besides following the procedures detailed in the "Contribute" section of the ReadMe. Thank you!

**Comment by PunkPun** [comment]
Hello 👋 
This shouldn't be a difficult feature considering its scope is limited to earnings graph. If you need guidance with anything specific feel free to ask, we are most active on discord

**Comment by ryanjschneebaum** [comment]
https://github.com/OpenRA/OpenRA/pull/21410

**Comment by PunkPun** [comment]
closed by #21410
