### ISSUE TITLE
Crushing do not work properly on slopes.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#21375]
Something that was noticed in Shattered Paradise, but i can reproduce the issue with TS on bleed as well. I did a quick edit to allow crushing friendly infantry and set WarnProbablity to 0 test, and these infantry are not dying when a vehicle passes over them.
![image](https://github.com/OpenRA/OpenRA/assets/7933210/6d218afd-84f9-41b5-bb82-b34f5100ba39)

I think it maybe a regression from #20333, but i haven't tested before the commit to confirm it.

**Comment by PunkPun** [comment]
you mean units overlap instead of being crushed?

related: #20539

**Comment by MustaphaTR** [comment]
> you mean units overlap instead of being crushed?

Yes. Vehicles just pass thru the occupied cell without killing the unit.

**Comment by towelcoded** [comment]
This was caused by infantry not being counted as standing on the ground while on ramps. I have fixed this so they can now be run over properly.
