### ISSUE TITLE
Game crash / too high memory usage on start if too many maps

### ISSUE THREAD

**Issue by cclecle** [OpenRA/OpenRA#21407]
## Motivation
If the game is loaded with a lot of custom maps (100+ in my tests), then the memory usage explode to 2, 3 GB or more and might crash.
The next release will introduce server map list accessible to client, so map list will probably get bigger, especially on dedicated server

## Proposed solution
Do not let map Packages openned in memory after app start. 
Open the package for discovery/checking/lint on start, then close the package, and finally reoppenn the package only when needed.

## Side effects
Maybe a very small delay on map start because the package will have to be reopenned, should be unsignificant.

## Alternatives
Accept having 3, 4 or more GB of ram per instance to allows game to run .

**Comment by PunkPun** [comment]
closed by #21408
