### ISSUE TITLE
Unable to install openRA using C&C Ultimate Collection

### ISSUE THREAD

**Issue by Pentazer** [OpenRA/OpenRA#21414]
I tried to search for a similar topic and couldn't find one specifically mentioning the ultimate collection. The only other threads of a similar nature are talking about the "remastered collection" but not the Ultimate Collection.

## Issue Summary
Open RA doesn't detect my steam install of the C&C Ultimate collection:
https://store.steampowered.com/bundle/39394/Command__Conquer_The_Ultimate_Collection/

I have them installed but when I tell open RA to detect my install, it can't find them.

## Reproduction
Install OpenRA and attempt to detect Ultimate collection content. 

## Expected behavior
OpenRA should be able to detect the Ultimate Collection and use its content to install properly.

**Comment by JovialFeline** [comment]
Unless I have mistaken your issue, https://github.com/OpenRA/OpenRA/pull/21355 has already addressed this on the development branch. There just hasn't been a release or hotfix put out since then.

**Comment by Pentazer** [comment]
Oh, yes you're right. Looks like it has already been acknowledged. Strange, it didn't show up when I searched for it under the issues section.

**Comment by PunkPun** [comment]
Closed as solved by #21355
