### ISSUE TITLE
TSVeinsRenderer do not actually translate the name on the tooltip.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#21426]
Noticed while applying the related changes to SP. On bleed, in TS mod, the tooltip for Veins looks like this:

![image](https://github.com/OpenRA/OpenRA/assets/7933210/0fb6bf7d-a2d7-45ce-ac29-18ab958df181)

**Comment by PunkPun** [comment]
regression from #21386
