### ISSUE TITLE
Voxels aren't rotated inside caryall's

### ISSUE THREAD

**Issue by PunkPun** [OpenRA/OpenRA#21430]
regression from #21271

https://github.com/OpenRA/OpenRA/assets/37534529/790e104b-6569-41fa-8f21-831c05b26857

**Comment by 136166** [comment]
Why is there a carryall in C&C!?

**Comment by Porenutak** [comment]
Dune inspiration :D

**Comment by PunkPun** [comment]
regression from #21271
