### ISSUE TITLE
Visual glitches in D2k

### ISSUE THREAD

**Issue by Porenutak** [OpenRA/OpenRA#21444]
After transition to R16 format some artwork got weird green glitch. So far I notice this on Light infanty and trooper icons and crush animation.
![icon glitch](https://github.com/OpenRA/OpenRA/assets/100044015/edf6878f-44ab-4523-a92a-688fece476ad)
![crush](https://github.com/OpenRA/OpenRA/assets/100044015/ed57d040-ec69-4f8b-8708-29448131561e)

These glitches are not present in artwork it self, its engine problem.

**Comment by Porenutak** [comment]
Just for reference, same artwork opened via resource editor:
![infantry](https://github.com/OpenRA/OpenRA/assets/100044015/37659155-6754-42db-bec0-c7010393590b)
![trooper](https://github.com/OpenRA/OpenRA/assets/100044015/c9a6cdf3-1922-47b9-8b97-ab8a4c40cbae)
![crushanim](https://github.com/OpenRA/OpenRA/assets/100044015/f972d210-a92b-4d62-8341-ce0396819970)

**Comment by Porenutak** [comment]
also all icon borders are broken.
![d2k-2024-06-12T073422363Z](https://github.com/OpenRA/OpenRA/assets/100044015/a9ac4228-b176-44a4-af5e-7c9b5d34f6a6)

**Comment by pchote** [comment]
This is *supposed* to be handled by the `-Remap:` in the icon sequence definition - so the regression is probably related to yaml sequence merging.

A workaround if this can't easily be fixed would be to change to `Remap: 00000000` (note: needs to have all 8 0's or it won't work).
