### ISSUE TITLE
ProtableChrono is dysfunctional

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#21466]
At current bleed branch, https://github.com/OpenRA/OpenRA/commit/446d37b832f00d1ab0896bd9741ba3b7ece1ada8

**Comment by PunkPun** [comment]
regression from #21391

ping @RoosterDragon

**Comment by dnqbob** [comment]
So, is https://github.com/OpenRA/OpenRA/pull/21469 fixed that without other side effect? I am going to close my PR if so.

**Comment by RoosterDragon** [comment]
Yes, it fixes the regression with the chrono and also retains the desired behaviour change for cancelling MoveOntoAndTurn.
