### ISSUE TITLE
ActorIndex, use ActorInfo.constructOrderCache

### ISSUE THREAD

**Issue by anvilvapre** [OpenRA/OpenRA#21485]
The `ActorIndex` implementations currently use `TraitDictionary.WithInterface<T>(int actorId)` to determine if an actor implements a certain trait and therefore if it should be indexed. 

This triggers a binary search in the trait container of trait type `T`. This is a quite expensive way to determine if an actor should be added to the index. Additionally all traits are searched and returned - where only a check is done to see if the actor implements the trait.

At the same time `ActorInfo` currently already maintanis a list of all traits that the actor implements. Proposal to change this cache also into a dictionary and to let actor index use this as a faster way to determine if an actor should be indexed. 

Seems that ActorIndex is currently only used by bots.

Code:

https://github.com/OpenRA/OpenRA/blob/dccab8fd21e84e32540990c8654ca46ae9d53cd3/OpenRA.Mods.Common/ActorIndex.cs#L119

and

https://github.com/OpenRA/OpenRA/blob/dccab8fd21e84e32540990c8654ca46ae9d53cd3/OpenRA.Mods.Common/ActorIndex.cs#L148

**Comment by RoosterDragon** [comment]
`ActorInfo` exposes `HasTraitInfo` which already does a dictionary lookup, so we don't even need to introduce a new dictionary, just calling that method will work.

The overall change is indeed sensible, you'll just need to adjust the callers from dealing in traits to trait-infos, but I don't believe there's anything preventing that.
