### ISSUE TITLE
Offset and length were out of bounds on `utility --png`

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#21536]
```
Error: Utility application crashed. See utility.log for details
Unhandled exception. System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at OpenRA.Mods.Common.UtilityCommands.ConvertSpriteToPngCommand.OpenRA.IUtilityCommand.Run(Utility utility, String[] args) in OpenRA/OpenRA.Mods.Common/UtilityCommands/ConvertSpriteToPngCommand.cs:line 76
   at OpenRA.Program.Run(String[] args) in OpenRA/OpenRA.Utility/Program.cs:line 118
   at OpenRA.Program.Main(String[] args) in OpenRA/OpenRA.Utility/Program.cs:line 45
```

**Comment by RoosterDragon** [comment]
Do you know the full command passed to the utility?

**Comment by Mailaender** [comment]
To reproduce try this
```sh
./utility.sh ra --extract temperat.pal
./utility.sh ra --png mods/ra/bits/gpsdot.shp temperat.pal
```

**Comment by RoosterDragon** [comment]
Adding the following check inside `FrameLoader.GetFrames` reveals the issue: We have frames whose `Offset+Size` region doesn't fit inside the region given by their `FrameSize` - we allocate an array to cover the `FrameSize` area - so we end up writing out of bounds when the data doesn't fit within this region.


`ShpTSFrame` and `ShpTDSprite.TrimmedFrame` appear to be causing this when they `// Pad the dimensions to an even number to avoid issues with half-integer offsets.` - they pad the raw data and the `Size` - but they don't pad the `FrameSize` to account for this. I believe they need to fix their FrameSizes up as well. However the tweaks I've tried so far end up messing up the rendering.

```c#
for (var i = 0; i < frames.Length; i++)
{
	var frame = frames[i];
	var minFrameWidth = frame.Size.Width + frame.Offset.X;
	var minFrameHeight = frame.Size.Height + frame.Offset.Y;
	if (frame.FrameSize.Width < minFrameWidth || frame.FrameSize.Height < minFrameHeight)
		throw new InvalidOperationException(
			$"{filename} frame {i} has invalid sizes: " +
			$"FrameSize ({frame.FrameSize}) must be equal to or larger than " +
			$"Size+Offset ({frame.Size}+{frame.Offset}={new float2(minFrameWidth, minFrameHeight)}).");
}
```

**Comment by RoosterDragon** [comment]
An alternative approach is to state that `Offset+Size` is allowed to define a region that extends outside the region given by `FrameSize`. In this scenario the utility command (and elsewhere?) should instead be prepared for this and allocate an array for the intersection of the two regions.

**Comment by PunkPun** [comment]
I think the main issue is the conversion algorithm assuming that the only thing the engine can do to a frame is padding. I recon a more sensible approach would be to add a `noEdit` flag to frame loading.

**Comment by PunkPun** [comment]
This is not a regression, the reproduction steps crash on stable as well. However we did add another scenario where this could crash
