### ISSUE TITLE
ts/ra/d2k glyphs-3x.png and cnc chrome-3x.png are incorrectly sized

### ISSUE THREAD

**Issue by drogoganor** [OpenRA/OpenRA#21540]
## Issue Summary
At commit `b58c1ea`, exports of ArtSrc svg's to the *-3x.png files didn't fill the whole image dimensions.

ts/ra/d2k glyphs-3x.png were at image dimensions 1024x1024, but the actual content was at 768x768.
cnc chrome-3x.png was at image dimensions 4096x2048 but the content was at 3072x1539

I broke this in my next commit `2ced4ab` (24 Jan 2024) with the png exports at the full image dimensions.
Please see the example image for ts glyphs-3x.png below. Left is incorrect, right is correct.
![image](https://github.com/user-attachments/assets/0aae6187-ebc9-44eb-9e73-b41463c7ff51)

Exported images should be like the image on the right.

**Comment by Mailaender** [comment]
Sorry, my bad.
