### ISSUE TITLE
MP maps with custom lobby options need to be tested wrt language strings

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#21618]
There is a suspicion that custom lobby options have been broken by the translation rework, but someone needs to actually verify this.

1. Create / update a map with a custom lobby dropdown option (e.g. difficulty) **that has its label and options defined in a ftl file**
2. Upload map to the RC
3. Select this map on a server
4. Join the server as a client **that doesn't have the map installed locally**
5. Switch to the options tab once the MapPreview has been populated from the RC

**Comment by sgmustafi** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
