### ISSUE TITLE
Official maps do not show a preview in www.openra.net/games/ Server Browser

### ISSUE THREAD

**Issue by aigles1** [OpenRA/OpenRA#21640]
Official maps do not show a preview in www.openra.net/games/ Server Browser since they are not on the resource center.
![Screenshot 2024-11-03 175751](https://github.com/user-attachments/assets/dce5838c-d458-4415-8a53-0ee8c9c54729)
![Screenshot 2024-11-03 175807](https://github.com/user-attachments/assets/0272bb32-321c-429b-94d6-dc83362a7dec)

**Comment by abcdefg30** [comment]
Thanks for the report. This should be fixed now by @dsimmons87 uploading the official maps to the RC. (The version should be compatible with the upcoming playtest.)
