### ISSUE TITLE
Linux Dune 2k playtest 20241116 appimage no music and videos

### ISSUE THREAD

**Issue by JoshuaPettus** [OpenRA/OpenRA#21658]
## Issue Summary

Since the update to content V3, music and videos are being ignored, and are not part of the content list in game.   I can confirm that these files are still in the Music and Movies folders within the v3 directory.  Very odd considering they are detected by the Content Management and has them as installed.

Have seen this on both Fedora 41 and Ubuntu 24.10 machines with the appimage

## Reproduction

STEPS TO REPRODUCE THE ISSUE

Insert CD, 
Have content manager rip the Music and Video files. 
See that they are in the v3/Movies and v3/Music folders
No dice in game

EXPECTED BEHAVIOR
That these work

**Comment by penev92** [comment]
Hello, thanks for the report. #21651 should already have that covered.
Basically the installer knows to install them, but then the game forgets to load them. Will be fixed for next playtest 🙂

**Comment by JoshuaPettus** [comment]
Dang sorry,  I figured someone must have seen this but I couldn't find it in the search.  Will close since it's a duplicate
