### ISSUE TITLE
Playtest 20241116 appimages are not working (execv error: No such file or directory)

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#21652]
Reported by milkman on [Discord](https://discord.com/channels/153649279762694144/279290580201373696/1308362762300293130):
![grafik](https://github.com/user-attachments/assets/4f6a3330-3044-4e63-82a4-ed6a0a1fb9ad)

> execv error: No such file or directory

**Comment by pchote** [comment]
I'm unable to reproduce the problem using the AppImages on the website (on an x64 machine) or with self-built AppImages (on aarch64)

**Comment by anvilvapre** [comment]
Can't reproduce on Linux 64bit.

**Comment by Mailaender** [comment]
Not reproducible on Fedora. Can you elaborate on the setup where this problem occurrs?

**Comment by PunkPun** [comment]
@pchote 
> it is apparently caused by appimagelauncher no longer being compatible with newer appimage runtimes
try disabling that and i bet it will work

**Comment by Mailaender** [comment]
The bug report does not mention `appimagelauncher`.

**Comment by tux314159** [comment]
This smells like a shared library error, ldd would help see what's missing

**Comment by Mailaender** [comment]
https://github.com/TheAssassin/AppImageLauncher/issues/656
