### ISSUE TITLE
Window Of OpenRA cannot be restored after Minimized

### ISSUE THREAD

**Issue by dnqbob** [OpenRA/OpenRA#21667]
Happens on Win 10 on https://github.com/OpenRA/OpenRA/commit/1af1ebd9e36b493056ebabfac5b3d428c6946d0a

Reproduction:
1. Open OpenRA
2. Minimized window of OpenRA while game loading.
3. There is chance that the window cannot be restored.

Add: it will be easier to reproduce if you also open an app like Screen2GIF(2.34.5) after doing 2.

**Comment by pchote** [comment]
Likely to be a regression from #21645.

**Comment by RoosterDragon** [comment]
We should revert that PR.

**Comment by PunkPun** [comment]
@dnqbob could you test whether current bleed works with just that commit reverted?

**Comment by dnqbob** [comment]
Test on OpenRA bleed, as well as the down stream mod (SP) use the newest engine code has this commit, all prove that it is the commit (https://github.com/OpenRA/OpenRA/pull/21645.) cause this issue. After reverting, issue is solved.
