### ISSUE TITLE
Capturing enemy buildings should allow some builds

### ISSUE THREAD

**Issue by psydev** [OpenRA/OpenRA#2187]
I think if you capture a construction yard, barracks, etc. that you should be able to build the things that you have in common with the opponent, at least. Right now when I capture an enemy conyard, all I can build is a power station. I don't know what the current consensus is on building another side's units, but building things in common seems reasonable to me.

Left to do:
- [x] Tiberian Dawn https://github.com/OpenRA/OpenRA/pull/5685
- [x] Red Alert https://github.com/OpenRA/OpenRA/pull/5759
- [x] Dune 2000 https://github.com/OpenRA/OpenRA/pull/5891
- [x] Tiberian Sun

**Comment by Phrohdoh** [comment]
Closed via #7376.
