### ISSUE TITLE
Spy capture sign on tech center not working

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#2285]
The spy capture sign on tech center is wrong, not the same as the other buildings

**Comment by Unit158** [comment]
Any more ideas for this? It would nice to close this issue.

**Comment by Mailaender** [comment]
http://cnc.wikia.com/wiki/Spy_(Red_Alert_2) has some ideas. Resetting support powers is one. Maybe get the (sub) factions special units.

**Comment by Phrohdoh** [comment]
Can we keep *something* from RA2 out of RA?

**Comment by GraionDilach** [comment]
Changing IronCurtain (curtain buildings, DemoTruck too) and Chronosphere (teleport enemy to water, keep cargo intact) to RA2 level were always NOTTODO.

The veterancy thingie was required, Spies were useless. I acknowledge though that this is unneeded - we don't have a good-enough unit idea from RA1 to make sense here.

We could also bring out two units from TD maybe, like the SSM Launcher for Soviet BLab and the Stealth Tank for Allied BLab, but that still sounds odd to me.

**Comment by pchote** [comment]
Can we keep *something* from TD out of RA? :wink:

**Comment by GraionDilach** [comment]
Ofcourse, I only brought those up as an if-you-really-want-it option, I'm more towards wontfix.

**Comment by pchote** [comment]
Spys have been significantly overhauled several times since 2012, so I think we're now done with this.
