### ISSUE TITLE
auto group teams

### ISSUE THREAD

**Issue by chilvence** [OpenRA/OpenRA#2301]
Forgive me for posting just to make a feature request, not an actual bug;

One thing that I have always been waiting in vain for cnc to add is automatic team creation. It is an OCD of mine to team units the second they come out of the barracks. 

Selecting units with the mouse was always a pig of an interface decision in my opinion, you dont have quick or accurate enough control, and you end up with finger strain! plus it isn't any reflection of the intense level of organisation in real world militaries. 

Perhaps if you hold control while adding units to the queue, the interface could get the hint and add those units to the first available empty team number, until the numbers are exhausted.  That seems to me the simplest way rather than the most exacting, but since I generally add units to the queue in growth 'spurts', anything more complicated might just be overkill. You can always quickly reassign teams anyway.

Projecting even further, it would be cool to have the teams represented as buttons on the gui somewhere, with little pips and icons - remember Battlezone?

So that is my two cents - a small feature with large implications. It may just be me, but since the interface is obviously not slavishly constrained to the original model, I thought it might be worth mentioning.
##

**Comment by abcdefg30** [comment]
Our interface has seen quite some revamps/improvements since 2012, but I don't see auto-teams happening. (No idea how it would fit into the UI.)
