### ISSUE TITLE
Support Dune 2000 patch 1.06 gamefiles

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#2344]
The http://dune2k.com/Download/30 DATA.R8 from Dune 2000 version 1.06 patch has more frames and currently fails to extract. Using code from http://code.google.com/p/dune2000plusone/source/browse/trunk/Dune2k1/ResourceEditor/ResourceEditor/Form1.cs with explicit permission by mvi and a very permissive license might help. It also adds new terrain tilesets with white houses (it says 2, but I only see 1 namely BLOXXMAS) and new units: grenade thrower with icon, stealth raider icon. Most work might be indexing all the frames manually again as the numbers change.

**Comment by pchote** [comment]
We're going to need this if we want to support asset installation from digital sources (like the d2k gruntmods edition).  The best approach will be to split our installation source into "original disk files" and "1.06 patch files", and offer our own download for the patch files for people who want to install from an original disk.

**Comment by pchote** [comment]
WIP at https://github.com/pchote/OpenRA/tree/d2k-106.
