### ISSUE TITLE
Character # cannot be escaped in settings file

### ISSUE THREAD

**Issue by Unksi** [OpenRA/OpenRA#2407]
What happened:

Using character # in the settings file will mark rest of the line as a comment. This cannot be escaped with character .

What was expected:

That the # character is treated just like any other character when escaped with \

Other:

This would be useful with values ServerName and (not yet merged) DedicatedMOTD
##

**Comment by MustaphaTR** [comment]
> In the case of escaping with `\#` what if someone wants a string to end with \ and also wants to provide an inline comment?

You can escape a \ with a \ here (or anywhere else that uses Markdown), same should be possible for the game.
