### ISSUE TITLE
Airplanes should not reveal that much while on the ground

### ISSUE THREAD

**Issue by Carko** [OpenRA/OpenRA#2535]
While in the air, airplanes have large reveal range due to their altitude, however on the ground it should be limited - their reveal range on the ground is currently much beyond anything else which should not be the case.

Probably the best would be either to linearly increase their reveal range depending on the altitude or have a separate reveal range for when they are landed.
##

**Comment by kyrylo** [comment]
Especially important for transport helicopters.

**Comment by penev92** [comment]
Also easily doable now thanks to some recent changes.

**Comment by kyrylo** [comment]
@penev92 any plans? :)

**Comment by kyrylo** [comment]
@chrisforbes was this fixed of rejected?

**Comment by Micr0Bit** [comment]
why is this closed ?

**Comment by reaperrr** [comment]
The logic is basically there now, but not implemented in our mods due to balancing concerns and transition issues.

**Comment by Smittytron** [comment]
I don't think you'll hear many complaints from the balance side on this one. 
Though I would change the title to "Airplanes should not reveal that much **while** on the ground". I keep reading it as airplanes should not see many ground units while flying over which naturally results in a double-take.

**Comment by Smittytron** [comment]
Closing as wont-fix after discussion in the github-cleanup Discord channel. While this would be easy to do with conditions there was no interest in this change.
