### ISSUE TITLE
ARM: should be expanded

### ISSUE THREAD

**Issue by Generalcamo** [OpenRA/OpenRA#2618]
Right now, ARM: only defines minimum distance. What I would like it to do it also have an option to:

a. Not display trail and contrail while arming
b. while arming, not home into a target
c. While arming, go a set speed before going to the normal speed
d. Have two sounds: One for firing, one for armed.

**Comment by pchote** [comment]
Missiles are now significantly more flexible.  Please create new issues if they still don't cover your use case.
