### ISSUE TITLE
Stats ingame v2.0

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#2650]
Its amazing, wishlist for next:

- [ ] Make the screen smaller when fewer players
- [x] after game stats
- [x] stats view when dead
- [ ] make it more transparent?
- [ ] combined team view, and team view also on all (line for teams in graph)
- [ ] fix for long player names.. (should be banned)
- [ ] afk icon for players

**Comment by Tunefix** [comment]
I would also wish that all "per minute" stats freezes when a player is defeated/surrender.
Then you would get a more accurate measurement of earnings and actions.

**Comment by abcdefg30** [comment]
See #3451.

**Comment by pchote** [comment]
Reverse duplicate of #5121.
