### ISSUE TITLE
FireDelay should do range check before firing (and be abortable)

### ISSUE THREAD

**Issue by psydev** [OpenRA/OpenRA#2710]
When a unit has FireDelay, it can shoot outside its range after the delay has passed.
So, if a unit leaves range of a weapon, it will still be shot at as though it were in range. An extreme example is the Obelisk, which has a FireDelay of 90:
http://i.imgur.com/LMaeHvg.jpg

Long after the tank has left range, the Obelisk still fires its laser. There should probably be range checking before firing.

With that said, the FireDelay on some units are small: 2 for submarines, 8 for flamethrowers, 15 for grenadiers. Perhaps if Firedelay is < 5 then the range checking can be ignored.

Also: when a unit has been ordered to fire, but is in the FireDelay phase, the firing cannot be aborted by pressing 'S'. Right now, the Obelisk cannot be stopped from firing while charging up, which takes 3 seconds.

**Comment by abcdefg30** [comment]
Can't reproduce the Obelisk issue.
