### ISSUE TITLE
Minimap and unit selection bug

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#2793]
1. Create a radar
2. Click on the minimap and move the rectangle (on the minimap) to change the battlefield view.
3. Without releasing your left mouse button, move your cursor somewhere else (for example on the battlefield view).

You'll notice that the rectangle unit selection has already been created at the minimap's position (when you tried to move the view with the minimap).

I think that if a player clicks on the minimap, OpenRA shouldn't start the unit selection.
It should detect if the cursor is over the minimap or over the battlefield view.

Playtest 20130316

**Comment by Mailaender** [comment]
A fix has been proposed at https://github.com/OpenRA/OpenRA/pull/7267.
