### ISSUE TITLE
Word jump and selection with CTRL (+SHIFT) + arrow key in lobby

### ISSUE THREAD

**Issue by xan2622** [OpenRA/OpenRA#2794]
In the lobby chat, the user should be able to perform several actions related to words and selection:
- [x] jump to the start of the sentense with CTRL+Home
- [x] jump to the end of the sentense with CTRL+End
- [x] jump to previous word with CTRL+left arrow
- [x] jump to next word with CTRL+right arrow
- [x] select the whole sentense (and see the selection) with CTRL+SHIFT+Home 
- [x] select the whole sentense (and see the selection) with CTRL+SHIFT+End
- [x] select the previous word (and see the selection) with CTRL+SHIFT+left arrow
- [x] select the next word (and see the selection) with CTRL+SHIFT+right arrow

<a href="http://www.hostingpics.net/viewer.php?id=270758ScreenShot001.png"><img src="http://img15.hostingpics.net/thumbs/mini_270758ScreenShot001.png" alt="Heberger image" /></a>

**Comment by pchote** [comment]
This is controversial, because these shortcuts are windows-specific.  OSX, for example, uses ctrl+arrow keys for switching workspaces, and uses alt+arrow(+modifiers) for jumping words.

**Comment by x-a-n-a-x** [comment]
Hmm... Can't OpenRA detect the kind of OS it runs on, and according to this, manage the shortcuts accordingly ?

**Comment by ChaoticMind** [comment]
@x-a-n-a-x yes it can detect, at least it can easily do so now, not sure about at the time of posting.
btw, the first two checkboxes are already implemented (home and end, no need for ctrl, or?)

**Comment by joealam** [comment]
It looks like the word-jumping part of this is done, but the selection isn't.

I can take a look, if this is still a feature request?

**Comment by pchote** [comment]
This was fixed by #14980.
