### ISSUE TITLE
Biome map generator

### ISSUE THREAD

**Issue by xan2622** [OpenRA/OpenRA#2806]
Among all new features of the upcoming new map editor (https://github.com/OpenRA/OpenRA/issues/2805), there could also be a "Biome map generator".

What is a "biome" ?
http://en.wikipedia.org/wiki/Biome

One of the most famous example of games that use a biome map generator is Minecraft. http://www.minecraftwiki.net/wiki/Biome

It would be useful to have such a tool in OpenRA Map Editor. This would fasten the creation of maps for modders.

Reference documentation : 

http://gamedev.stackexchange.com/questions/20551/a-simple-map-four-biomes-and-how-to-distribute-them

http://www-cs-students.stanford.edu/~amitp/game-programming/polygon-map-generation/
##

**Comment by Smittytron** [comment]
Closing as wont fix after github-cleanup discussion in Discord. This issue would be too much to create and maintain.

**Comment by Mailaender** [comment]
I may try to get my hands on it. Not here but in @OpenHV.
