### ISSUE TITLE
Halt the Game on Desync

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#2850]
Instead of throwing an exception and crashing
- indefinitely pause the game
- inform the user about what happened
- let him pan around the camera to assess the situation

optional, but awesome
- high-light the actor with desynced traits with a palette effect
- dump the trait values to file / screen on click
- switch to observer mode with DevCheats buttons enabled
##

**Comment by abcdefg30** [comment]
The game no longer quits on desync: #19958
