### ISSUE TITLE
Automatically update default settings documentation

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#2858]
Do the same with https://github.com/OpenRA/OpenRA/wiki/Settings as #2808 does with https://github.com/OpenRA/OpenRA/wiki/Traits
##

**Comment by pchote** [comment]
The documentation strings were added in #8247.  It would now be a simple to write a utility command to extract them.

**Comment by Mailaender** [comment]
We still need to do the Travis CI automation so we don't forget it during releases.
