### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#2889]
http://chocolatey.org brings package management to Windows (finally!) and allows automatic dependency resolution. We only need to create the required http://chocolatey.org/packages for OpenRA:
- [x] .NET 4.0 client profile is pre-existing
- [ ] OpenAL redistributible (optional, currently bundled)
- [ ] SDL2 (optional, currently bundled)
- [ ] freetype6 (optional, currently bundled)
- [ ] zlib1 (optional, currently bundled)
- [ ] liblua51 (optional, currently bundled)

As it is fully PowerShell scriptable so we could add in some nice newbie friendly things like Pixel Shader Version detection #2534 or checking if only Windows default drivers without OpenGL support are installed.

We can even use it to [set up a development environment](https://github.com/chocolatey/chocolatey/wiki/DevelopmentEnvironmentSetup) fast for beginners:
- [x] .NET 4.0 SDK is pre-existing
- [x] Git/GitHub for Windows (pre-existing)
- [x] Visual Studio Express 2012 for Windows Desktop (pre-existing)
- [x] or maybe SharpDevelop (pre-existing)
- [x] Paint.NET (for [Pixelart](https://github.com/OpenRA/OpenRA/wiki/Pixelart), pre-existing)

**Comment by Mailaender** [comment]
Stumbled upon https://chocolatey.org/packages/openra by @AnthonyMastrean.

**Comment by AnthonyMastrean** [comment]
I'm happy to migrate that package and maintainership here! I can also provide guidance on implementation.

**Comment by Mailaender** [comment]
I created https://github.com/OpenRA/Chocolatey where you can submit it via a pull request so you retain authorship of the initial commits.

**Comment by AnthonyMastrean** [comment]
Looks like I can't fork until there's at least one commit... throw an empty Readme in there?

**Comment by Mailaender** [comment]
Done.

**Comment by AnthonyMastrean** [comment]
https://github.com/OpenRA/Chocolatey/pull/1
