### ISSUE TITLE
Fix Allied Mobile AA (Balancing)

### ISSUE THREAD

**Issue by Surrealistik** [OpenRA/OpenRA#2892]
Just a repost really of issues discussed on Sleipnir's forum here:

http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=16183

Summary: Allies have no viable mobile anti-air. Rocket soldiers are too slow, vulnerable and ineffective vs most aircraft, especially Yaks, to be effective counters relative to their cost/build time, and Longbows are too late tier and too costly to be practical.

**Comment by pchote** [comment]
Balance has changed a lot since 2013, so there's not much we can do with this ticket -> closing.
