### ISSUE TITLE
Additional Spy Functionality

### ISSUE THREAD

**Issue by Surrealistik** [OpenRA/OpenRA#2901]
Spies should be able to detect and kill each other with their silenced pistols (Spy vs Spy/counterintelligence). A Spy only attacks in this way if it's disguised as an allied unit (or undisguised), and not an enemy one to avoid blowing its cover.

As per the following thread:

http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=16145

As an alternative to these infiltration effects, you can have Spies place remotely detonated explosives in buildings it infiltrates, which also includes production facilities, power plants, super weapons, tech centres and defensive structures (takes about as long as an Engineer capture to set explosives), reemerging after the explosives are set. You gain sight of the infiltrated structure. The Spy can 'deploy' in order to detonate all placed explosives, which instantly destroys the buildings they're planted in after a short delay (~3 seconds). This is similar to capabilities he demonstrated in Soviet Mission 3 from the original campaign. This effect is in addition to existing infiltration effects for the Radar Dome and Ore Refinery. Just before the buildings detonate, the victimized player will hear the triggering Spy proclaim: "For king and country" in his suave Connery voice.

If the Spy is killed before it can detonate its explosives, those explosives become harmless, and the Spy's controller loses sight of the structures it has infiltrated.

Spies can have their price increased (+100%) to compensate for this increased versatility. To help keep them useful for stealing credits, you could reimburse 50% of their cost on infiltration of Ore Refineries.

**Comment by CCob** [comment]
I agree, there is little to counter a spy if you are allied v allied, short of spotting the little fella with your own eyes, which his difficult on large maps

**Comment by Unit158** [comment]
Dogs were implemented for a reason...
