### ISSUE TITLE
Save areas of the map

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#2956]
Here is a mockup image I have made :
![744383ScreenShot001](https://f.cloud.github.com/assets/1732773/340398/67d4ab42-9d4f-11e2-8812-31166abc40cb.png)

(note that to fit the minimap size, buttons (which look like tabs) should be a bit smaller)

There could be new icons next to the minimap:

- clicking on the " + " button would record the current position of the view and add a new "button" with a digit to quickly go to this position later

- clicking on the " - " button would remove a previously recorded position (the player would have to select it first before being able to click on the " - " button)

**Comment by x-a-n-a-x** [comment]
Now, when I look at mock-up that I made, I tend to not like it anymore. After all, it would clutter the minimap. Nevertheless, the issue is still valid: I still wish there could be a way to save areas of a map with hotkeys.

**Comment by SzabKel** [comment]
C&C Generals uses Ctrl+Fn keys (F1-F8) to save camera position and jumps to them with F1-F8 keys. We can't use as it is, becouse the production keys are bound to function keys on OpenRA.

**Comment by MustaphaTR** [comment]
> The later C&C games had hotkeys for bookmarking viewport locations.

Later? I know that Dune 2000 has bookmarks on F9-12 and possibly RA and TD too. That's  not a new thing.
