### ISSUE TITLE
infantry deaths inherit scale

### ISSUE THREAD

**Issue by psydev** [OpenRA/OpenRA#3031]
Currently when an infantryman which uses the Scale trait dies, their infantry death animation does not inherit the scale, and shows at their original size, which can be quite large.
Would be nice if fixed.
Thank you.
##

**Comment by Unit158** [comment]
http://i.imgur.com/oQPSXSv.gif Reported 2015/08/13 by Astor via IRC

**Comment by MustaphaTR** [comment]
I think Scale should go to Sequence .yaml files, rather than being under RenderSprites. I use Scale: tag a lot, it maybe hacky but useful.

**Comment by GraionDilach** [comment]
Scale is bad and you should feel bad. It should be axed for good because it just encourages plain wrong stuff.

**Comment by GraionDilach** [comment]
@MustaphaTR You can play the ignorant thumbsdowner card, but I've said more than a year ago why Scale is bad - https://github.com/OpenRA/OpenRA/pull/10244#r48102518. Don't call me uncooperative if I just don't repeat myself.

**Comment by MustaphaTR** [comment]
> The new WithDecoration proposal denies the use of that trait for WW-styled EMP/mindcontrol/AttachEffect.Animation usecases - forcing WithIdleOverlay for such which gets affected by Scale and ultimately leads into severe issues due to some passive encouragement from usecases like here.

Are you tring to say some uses it and some doesn't? That's exactly why it should be moved to sequences.

Even tho you commented to me there i don't remember seeing that comment so sorry for that.

Something is badly coded doesn't mean it should  be removed, but fixed. Of course i don't know how hard that would be but that's my policy.

**Comment by pchote** [comment]
> I think Scale should go to Sequence .yaml files, rather than being under RenderSprites. I use Scale: tag a lot, it maybe hacky but useful.

We are going to have to do this in order to support the remaster assets. A few things (e.g. desert scorches, civilian fields) are rendered with a 256px cell size instead of 128px so will need to be downscaled. The scale feature is at least conceptually reasonable when used for HiDPI world assets that are already likely scaled at standard zoom.
