### ISSUE TITLE
make crates not show up within certain distance of start location

### ISSUE THREAD

**Issue by psydev** [OpenRA/OpenRA#3076]
There is a problem where the AI is unable to deploy its construction yard if a crate starts right next to it. 

Also, to make things a bit fairer, it would be nice if at the beginning of the game, crates didn't start out next to your starting location, and they were farther away from your base.

There should be an option to specify the minimum distance a crate  can be from your start location at the beginning of the game. (And maybe a time limit for when this minimum range expires, say ~60 seconds default).

**Comment by obrakmann** [comment]
This problem was now solved with a spawn delay for crates. This solves both the inherent unfairness and the AI deployment problem.
