### ISSUE TITLE
Show (and allow editing of) actor facings in the editor

### ISSUE THREAD

**Issue by chrisforbes** [OpenRA/OpenRA#3159]
Currently configuring the FacingInit requires yaml hacking, and that's silly for something like setting a unit's facing.

**Comment by Mailaender** [comment]
I just added this to #4496. Select an actor and use the mouse-wheel. It comes with a live preview that works very smoothly with Voxel actors.

![image](https://cloud.githubusercontent.com/assets/756669/6430882/e39e618a-c01d-11e4-8b3c-b3c91f5dd63b.png)

Would close this now as I doubt we will ever implement it in the WinForms editor, but @pchote insisted at https://github.com/OpenRA/OpenRA/issues/6771#issuecomment-76592628 so I keep this open.

**Comment by Unit158** [comment]
Can we have an alternative to the mouse wheel to change the facing? Some sort of keyboard binding as well?

**Comment by Mailaender** [comment]
Yes, that is easy.

**Comment by chrisforbes** [comment]
Some kind of click+drag gesture from the unit in the desired direction
would work well.

On Mon, Mar 2, 2015 at 6:33 AM, Matthias Mailänder <notifications@github.com

**Comment by Mailaender** [comment]
That is a lot more difficult.

**Comment by penev92** [comment]
I really don't think the implementation (and usage) of this needs to be difficult. Lets keep this as simple as possible.

**Comment by pchote** [comment]
The new editor is going to need to grow a proper properties/actorinit panel in the medium term future, so I also vote for keeping this simple for now. Hotkeys should be fine.

**Comment by Mailaender** [comment]
@pchote removed my unlimited scroll-wheel actor facing editing from #4496 (which I did with Voxels in mind) and replaced it with a left click rotate by 22.5°C but still https://github.com/OpenRA/OpenRA/pull/8065 then solved this.
