### ISSUE TITLE
Helicopters sometimes don't land in the middle of the pad

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#3177]
![helicopter-landing](https://f.cloud.github.com/assets/756669/434733/280dbad2-af68-11e2-9281-b799d2271f10.png)

Happens seldom and I don't know how to reproduce probably when helis are fighting over the landing spots #2375.
##

**Comment by reaperrr** [comment]
@Mailaender Have you seen this in recent months? I haven't, but wanted to ask before closing this.

**Comment by Mailaender** [comment]
In Tiberian Sun, but that may be unrelated (probably height map stuff) and as this isn't reproducible there hasn't been anything to fix for two years now so I guess we can give up here.

**Comment by abcdefg30** [comment]
I can easily reproduce this:
![helibug](https://cloud.githubusercontent.com/assets/7704140/9832290/72749e00-5976-11e5-96b8-a1bc8fba1996.gif)

**Comment by FrameLimiter** [comment]
This was resolved in release-20161015.
