### ISSUE TITLE
Forbid specific player names

### ISSUE THREAD

**Issue by owerner** [OpenRA/OpenRA#3200]
Some player names should not be allowed to use:
Open
Closed
Hard AI
etc...

**Comment by Mailaender** [comment]
Duplicate nicknames should also be avoided not just for technical reasons.

**Comment by MicroJOo** [comment]
another problem is ascii-art as name ... its hard to name this people ingame ... : 

┌∩┐(◣_◢)┌∩┐
 
 	̿' ̿'\̵͇̿̿\з=(◕_◕)=ε/̵͇̿̿/'̿'̿ ̿ 

 	ዞᏜ℘℘Ꮍ ℬℹℛʈዞᗬᏜᎽ

id also like to see a letter - limitation so you can see what the people write  : 

![openra 2015-01-05 00-28-58-00](https://cloud.githubusercontent.com/assets/9139965/5607992/0263cf2e-9472-11e4-8d41-3b583bf4cad0.png)

**Comment by kyrreso** [comment]
Or materia upside down.. I cannot tab-complete m or a..

**Comment by Mailaender** [comment]
> I'd also like to see a letter - limitation

Reasonable request, see https://github.com/OpenRA/OpenRA/issues/7739.
