### ISSUE TITLE
make map-reveal crate disable fog for 5-10 seconds instead of just revealing terrain

### ISSUE THREAD

**Issue by psydev** [OpenRA/OpenRA#3212]
Suggestion: make map-reveal crate disable fog for 5-10 seconds instead of just revealing terrain.
This makes the crate useful. Some games already start with the map revealed, and once you have most of it explored, the crate is not very useful, but having a glimpse of your opponent's units and getting an updated on their base building is a good thing to have.

**Comment by pchote** [comment]
I personally like this idea, but this has been discussed on and off in IRC over the years and is rejected for being too powerful.  Closing ticket as part of a wider issue tracker cleanup.
