### ISSUE TITLE
Ore trucks should avoid "friendly" mines

### ISSUE THREAD

**Issue by ScottNZ** [OpenRA/OpenRA#3270]
With the recent mine changes apparently they will drive over mines and damage themselves.
##

**Comment by mmmh81** [comment]
This item is old, but still valid. I agree with everything written above: Units (harvesters as well as others) should not avoid projectiles, but having them drive over friendly mines is very annoying indeed.

**Comment by reaperrr** [comment]
Closed via https://github.com/OpenRA/OpenRA/pull/12337.
