### ISSUE TITLE
Game events notification

### ISSUE THREAD

**Issue by xan2622** [OpenRA/OpenRA#3278]
Maybe there could be an option (checbox) to enable/disable "game events notifications" like a building that has been destroyed ?

Sometimes when a player uses the Ion Cannon or the Nuke bomb against some of my buildings, they get destroyed too quickly for me to know what have been destroyed (especially if my current view is not focussed on my base).

With such a notification, I would be able to know how many and which buildings have been destroyed. What was there before the strike.
##

**Comment by matjaeck** [comment]
Related: #6354
