### ISSUE TITLE
Change default unit stance to defend for land units and returnfire for cloaked units [$48]

### ISSUE THREAD

**Issue by ScottNZ** [OpenRA/OpenRA#3285]
Nobody actually wants them to default to AttackAnything.

**Comment by obrakmann** [comment]
I think I'll take a stab at this in the next cycle

**Comment by penev92** [comment]
YesPleaseThankYou!

**Comment by obrakmann** [comment]
The code is ready (https://github.com/OpenRA/OpenRA/compare/bleed...obrakmann:default-stance-defend), but a PR is blocked on #8184, as far as I'm concerned.
