### ISSUE TITLE
PCX support for individual cameos

### ISSUE THREAD

**Issue by Deformat** [OpenRA/OpenRA#3309]
Basically, allow a cameo to have a specific palette, or allow it to be loaded as a .PCX file.

**Comment by Mailaender** [comment]
> allow a cameo to have a specific palette

Reverse duplicate of https://github.com/OpenRA/OpenRA/issues/8464.

**Comment by pchote** [comment]
We now support per-icon palettes, which should be sufficient.

**Comment by Mailaender** [comment]
I guess the specific request for PCX is because of legacy compatibility with RA2 mods?

**Comment by GraionDilach** [comment]
Kinda but those RA2 modders should know that any cameo PCX they have can be separated into an SHP-PAL combination with XCC Mixer in four clicks. I'm fine with this.
