### ISSUE TITLE
The 'Jump to base' hotkey is useless if the Construction Yard is destroyed

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#3318]
In some cases, there is a small problem with the "Jump to base" hotkey : 

If you lose your main Construction Yard, you can't use this hotkey anymore...
It would be nice to go back to the barracks, war factory or outpost ?

**Comment by bryanwilbur** [comment]
I submitted a fix which works like the original Red Alert.  The hot key will jump to the oldest non-destroyed building.
