### ISSUE TITLE
In-Game Map Editor [$140]

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#3377]
Instead of the buggy WinForms (which is even depreceated on Windows) based map editor (that does not work on Mac #2939, #2295 etc.) we could consequently redo it in-game with OpenRA widgets. This way we could use the existing renderer to avoid code duplication and glitchy quick hacks as well as get Voxel support for free. Depends on

- [x] Ability to save maps
- [x] Adding actors
- [x] Change the terrain tiles
- [x] Place resource patches

This might even get us co-op mapping if done right.

WIP at https://github.com/OpenRA/OpenRA/pull/4496

**Comment by Mailaender** [comment]
I just added a Grid button re-using the existing developer cheat:

![image](https://cloud.githubusercontent.com/assets/756669/6317788/4a915f82-ba6a-11e4-8388-511c22afb268.png)

**Comment by Mailaender** [comment]
I also now color code the actor list by player so mission creators keep an overview:

![image](https://cloud.githubusercontent.com/assets/756669/6317825/c2917f3c-ba6d-11e4-8235-d380d2c318d1.png)

**Comment by Mailaender** [comment]
Added a tooltip containing the actor reference keys which is useful when scripting missions:

![image](https://cloud.githubusercontent.com/assets/756669/6320031/de458a78-bad3-11e4-84fe-ab009becc490.png)

**Comment by Phrohdoh** [comment]
Very nice work @Mailaender!

**Comment by dan9550** [comment]
It just needs a Lua editor :P

Excellent work though, really look forward to using it.

**Comment by TheRaffy** [comment]
Holy crap I didn't noticed that your progress at this gone so far!
Very good work! 

I'm heavy interested in norming (making an standrad) for the tiles of the ra and td tilessets.
To allow a future option "Play this map with the x tilesset " (temperate, desert, snow, winter, jungle)
(creating the missing tiles of each set. To have all shapes and sizes)

**Comment by penev92** [comment]
Here's yet another feature request for the map editor: togglable observer-style shroud/fog.
In some missions/scripted maps unit sight ranges might be important. I am thinking infiltration missions, sneaking around enemy bases, stuff like that. The map creator should be able to see what each player would be able to see ingame. I assume all of this should be doable by reusing existing code, so it shouldn't be too hard, I hope.

**Comment by Mailaender** [comment]
Added the value of the placed resource tile to the tooltip which is useful for creating tournament grade maps with balanced resource patches:

![image](https://cloud.githubusercontent.com/assets/756669/6427235/4fe28e5a-bf7b-11e4-90c1-2505d06cf3d5.png)

**Comment by Phrohdoh** [comment]
`$200` is proper.

**Comment by pchote** [comment]
Showing the value for a single tile isn't going to be very useful.  People creating tournament grade maps are going to need to know the value of the whole resource field, and aren't likely to tally the individual cells themselves.

**Comment by penev92** [comment]
More like "calculate the value withing the selected box" maybe ?

**Comment by Mailaender** [comment]
I now added temporary player color remaps so you keep an overview about the spawn points:

![image](https://cloud.githubusercontent.com/assets/756669/6430232/24a2c026-c001-11e4-8e3f-fd4b944f84d1.png)

and I made the editor aware about the players visibility:

![image](https://cloud.githubusercontent.com/assets/756669/6430293/de4c8e56-c003-11e4-8c2c-37ed0f31a8c1.png)

**Comment by Mailaender** [comment]
Also added an icon so you can see CAMERA actors:

![image](https://cloud.githubusercontent.com/assets/756669/6430437/389fbdf0-c00a-11e4-8dcf-db61387aad0d.png)

**Comment by penev92** [comment]
Nice!

**Comment by Phrohdoh** [comment]
That camera actor view is very nice, reminds me of professional engines. :)

**Comment by Mailaender** [comment]
I took http://www.fileformat.info/info/unicode/char/1f3a5/index.htm as a reference.

**Comment by Mailaender** [comment]
I took the effort to adapt the UI to the Tiberian Dawn mod standards:

![image](https://cloud.githubusercontent.com/assets/756669/6758856/b8c298c8-cf3b-11e4-9cd6-f12d07f27bc2.png)

and fixed the spawn and point remaps:

![image](https://cloud.githubusercontent.com/assets/756669/6758819/7d9371f0-cf3b-11e4-8088-c7e3ae92ab6f.png)

![image](https://cloud.githubusercontent.com/assets/756669/6759034/23272e44-cf3d-11e4-9948-2965856edc61.png)

**Comment by Mailaender** [comment]
Also works with Red Alert 2 from https://github.com/Phrohdoh/oramod-ra2

![RA2](http://i.imgur.com/JBfHK0Y.png)

if you patch the mod.yaml to re-use the current chrome yaml layout:

```diff
diff --git a/mod.yaml b/mod.yaml
index 62aa76d..569739e 100644
--- a/mod.yaml
+++ b/mod.yaml
@@ -84,13 +85,13 @@ Assemblies:
 	./mods/ts/OpenRA.Mods.TS.dll
 
 ChromeLayout:
-	./mods/ra2/chrome/ingame.yaml
-	./mods/ra2/chrome/ingame-player.yaml
-	./mods/ra2/chrome/ingame-observer.yaml
-	./mods/ra2/chrome/ingame-chat.yaml
-	./mods/ra2/chrome/ingame-diplomacy.yaml
-	./mods/ra2/chrome/ingame-fmvplayer.yaml
-	./mods/ra2/chrome/ingame-menu.yaml
+	./mods/ra/chrome/ingame.yaml
+	./mods/ra/chrome/ingame-player.yaml
+	./mods/ra/chrome/ingame-observer.yaml
+	./mods/ra/chrome/ingame-chat.yaml
+	./mods/ra/chrome/ingame-diplomacy.yaml
+	./mods/ra/chrome/ingame-fmvplayer.yaml
+	./mods/ra/chrome/ingame-menu.yaml
 	./mods/ra2/chrome/ingame-info.yaml
 	./mods/ra2/chrome/ingame-infoscripterror.yaml
 	./mods/ra2/chrome/ingame-infobriefing.yaml
@@ -98,8 +99,8 @@ ChromeLayout:
 	./mods/ra2/chrome/ingame-infostats.yaml
 	./mods/ra2/chrome/ingame-observerstats.yaml
 	./mods/ra2/chrome/ingame-debug.yaml
-	./mods/ra2/chrome/ingame-leavemap.yaml
-	./mods/ra2/chrome/mainmenu.yaml
+	./mods/ra/chrome/ingame-leavemap.yaml
+	./mods/ra/chrome/mainmenu.yaml
 	./mods/ra2/chrome/settings.yaml
 	./mods/ra2/chrome/credits.yaml
 	./mods/ra2/chrome/lobby.yaml
@@ -120,6 +121,7 @@ ChromeLayout:
 	./mods/ra2/chrome/color-picker.yaml
 	./mods/ra2/chrome/install.yaml
 	./mods/ra2/chrome/dropdowns.yaml
+	./mods/ra/chrome/ingame-editor.yaml
 
 Weapons:
 	./mods/ra2/weapons.yaml
--
```

**Comment by Mailaender** [comment]
Updated the resource $ calculating tooltip to cover the whole patch:

![image](https://cloud.githubusercontent.com/assets/756669/6768680/90513dc8-d07a-11e4-920b-a1a5df90495e.png)

**Comment by TheRaffy** [comment]
That is f***ing brilliant! Maps can now become more balanced! Another great step to speed up mapping. It was realy annoing to count all  or patches.  

Maybe you like to add a future feature, that is showing the distance from the closest edges of the map for ore and mineral mines. ( would help for symetric positioning)

**Comment by WolfGaming** [comment]
Does it work for gems and does it calculate only the gem patch or adds it to gold patches?

**Comment by Mailaender** [comment]
It counts all connected resources, but takes different values into account.

**Comment by pchote** [comment]
We're now in the final stretch - the following prs introduce the final engine changes to support the editor:

- [ ] #7937
- [ ] #7875 
- [ ] #8017
- [ ] #8025
- [ ] #8027
- [ ] #8034

Once these are merged then the main editor pr will be relatively lightweight (and hopefully uncontroversial).

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/8065 has been merged.
