### ISSUE TITLE
Make guarding units have minimum selection priority

### ISSUE THREAD

**Issue by ScottNZ** [OpenRA/OpenRA#3387]
Use case: Order mrj to guard a tank/group of tanks. Easily order the tanks around without accidentally touching the mrj's guard order
##

**Comment by Smittytron** [comment]
Closing as wontfix after discussion in Discord. This could cause equally frustrating events where a player attempts to dragbox the guarding units only to catch another unit in the corner and fail. Also Guard doesn't really work atm (#7628)
