### ISSUE TITLE
Add a selection decoration for stances

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#3437]
Units with an assigned stance should get an icon in the bottom-left corner of their selection box, and we should drop the horrible Debug: text when switching stance.
##

**Comment by Phrohdoh** [comment]
#7466 (and #7551 by extension) may be useful here (as ideas).

**Comment by MicroJOo** [comment]
the "xp - ranks" on the top right corner allready takes a lot of space ... specially on infantry you would cut like half of the frames when they have 2 icons ... i would like to see the acutally unit ... not a bunch of icons ...

**Comment by rob-v** [comment]
> Units with an assigned stance should get an icon in the bottom-left corner of their selection box

Is this needed once we have #13442? I don't remember games having this indicator directly in selection box.

**Comment by pchote** [comment]
It is not.  I will close it once we have the command bar in all our default mods.
