### ISSUE TITLE
Have enemy units reveal themselves when they shoot at your units

### ISSUE THREAD

**Issue by ScottNZ** [OpenRA/OpenRA#3476]
This should go some ways into fixing the artillery balance problems.

**Comment by GraionDilach** [comment]
For the record, TS/RA2 worked like this.

**Comment by MustaphaTR** [comment]
In TS/RA2 there was a Weapon tag as `RevealOnFire=` which is default to yes. But some weapons like Sniper's `[AWP]` has changed to `no`.

**Comment by reaperrr** [comment]
This has been decided as "won't fix" for RA/TD, and has been adressed for D2k & TS. Engine support was added with https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Effects/RevealShroudEffect.cs (enabled via `RevealOnFire` trait).
