### ISSUE TITLE
Game logic for seaborne aircraft carriers

### ISSUE THREAD

**Issue by wuschel** [OpenRA/OpenRA#3481]
Currently, there is no support for aircraft carriers in OpenRA. 

Two kinds of aircraft carriers would be great to have: 

a) a carrier for VTOL type of aircraft (helicopters, harriers), preferably for allies.
b) a carrier of jets e.g. a jump start carrier with a ramp, preferably for soviets.

Planes should be able to land, repair and rearm on carrier vessels. Optionally, carriers should also have on-board weaponry - but this is not necessary.

See also: http://www.sleipnirstuff.com/forum/viewtopic.php?f=83&p=285423#285423

**Comment by pchote** [comment]
Reverse duplicate of #3787
