### ISSUE TITLE
In-game kicking

### ISSUE THREAD

**Issue by skyfaller** [OpenRA/OpenRA#3516]
It should be possible to kick players (and spectators) while playing a game. Sometimes a troll doesn't reveal themselves as a troll until you have already started playing a game.
##

**Comment by 3Lucian** [comment]
+1000

**Comment by StexoO** [comment]
Isn't the game ruined anyway if you kick/ban a player ingame ?
The reputation (https://github.com/OpenRA/OpenRA/issues/2265) could avoid that.

**Comment by Micr0Bit** [comment]
what @StexoO said ... 

this ticket here is pretty old (2013)

**Comment by 3Lucian** [comment]
You might want to kick a spec who is lagging - especially for games on stream, or you might want to vote kick a player for a number of reasons, team killing being one of them, an idle player (or spec) not leaving a server once a game has finished, etc.

its a useful function, and shouldn't be too hard to implement.
