### ISSUE TITLE
Trailing whitespace chars in mod.yaml

### ISSUE THREAD

**Issue by cgf123** [OpenRA/OpenRA#3541]
Having trailing whitespace characters in mod.yaml triggers 'illegal character' exceptions.

eg 	mods/abcmod/infantry.yaml (whitespace)

While it's not good practice, it is a minor mistake so it is annoying that it isn't tolerated.

**Comment by Mailaender** [comment]
That has been included in the latest playtest. Re-open if this is still a problem.
