### ISSUE TITLE
Maps not available on the server should not be selectable

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#3558]
but greyed out in the dedicated host scenario.

**Comment by Mailaender** [comment]
That would be bad for servers which rsync with the resource site though.

**Comment by Mailaender** [comment]
> A simpler solution (borrowed from the Generals lobby) is to split the map list into separate official and unofficial sections, and disable the unofficial map list on dedicated servers.

Added in https://github.com/OpenRA/OpenRA/pull/8207.

**Comment by pchote** [comment]
Not quite.  We're still missing:
> disable the unofficial map list on dedicated servers.

And in practice many servers do have custom maps available, so that's still not a great solution.
