### ISSUE TITLE
Move orders can give away hidden structures

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#3671]
Issuing a move order to a location reveal the presence of an invisible frozen building.

The move target line should indicate the original ordered position, and the actor move as close as they can.

The fix for this probably wants to be tied in to a more general fix for move orders into unpathable terrain, which currently causes the unit to do nothing.
##

**Comment by fruestueck** [comment]
This isn't an issue anymore. Tested with shroud on RA mod and with a stelth generator in TS.

**Comment by reaperrr** [comment]
> The fix for this probably wants to be tied in to a more general fix for move orders into unpathable terrain, which currently causes the unit to do nothing.

Such a fix would probably also make things like group pathing easier to implement.
