### ISSUE TITLE
Smart Infantry Units : they could move to let the player install a building [$30]

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#3682]
What about infantry units that automatically move if the player tries to install a building where they are standing ?

It would just be a short move, just to let the building being placed.

**Comment by Phrohdoh** [comment]
:+1:

**Comment by MicroJOo** [comment]
:+1:

**Comment by epicelite** [comment]
What about vehicles?

**Comment by Phrohdoh** [comment]
What about them? This could be applied to any actor assuming it is just a listener trait.

**Comment by Phrohdoh** [comment]
A solution has been offered at #7800.
