### ISSUE TITLE
The build palette isn't big enough to display all buildings of all factions

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#3699]
The Build Palette isn't big enough to display all possible builidngs (after enabling "Build Everything" in the Cheats menu).

What about adding extra tabs, one for each faction : 

![build_evertything_tabs](https://f.cloud.github.com/assets/1732773/982413/6ba36318-07ed-11e3-9c6b-c1e26c4e98dc.png)

This way, it would be possible to filter the buildings.

Here are the logos (PNG):
![build_evertything_tabs2](https://f.cloud.github.com/assets/1732773/982430/2bf5694e-07ef-11e3-884b-9e1c8bae5bcb.png)

**Comment by obrakmann** [comment]
Fixed for the new production palette (used in RA) in #7227. Once d2k gets a new UI, it can switch to the new palette and benefit as well.
