### ISSUE TITLE
Repair pad pathfinding

### ISSUE THREAD

**Issue by Trelotrino** [OpenRA/OpenRA#3757]
In all mods when I use the Repair pad and set a waypoint somewhere and the repaired vehicle finds a single blocking unit or building in its linear path it just simply stop and don't move anymore unless I give it a new order.

Perhaps it is related to the path finding algorithm which has also many issues. Some unit stop moving in a large group even it has enough space to do it.
##

**Comment by rob-v** [comment]
Fixed by PR #13093
