### ISSUE TITLE
Disable parts of the tech tree when a building gets powered down

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#3769]
to punish people powering down their radar all the time. I noticed this behavior in C&C 3: Tiberium Wars.
##

**Comment by pchote** [comment]
We now have engine level support for this via `ToggleConditionOnOrder` &rarr; `ProvidesPrerequisite`.  I don't think the current balance of the default mods could support this as a gameplay mechanic, so closing as fixed.
