### ISSUE TITLE
Spawn child unit that attacks target

### ISSUE THREAD

**Issue by HSFOutcast** [OpenRA/OpenRA#3787]
Would love to see this function in OpenRA.

In short. A unit should be able to spawn a child unit that attacks the target for the master unit, if child gets destroyed, it will be automatically replaced after a set amount of time.

Example. Red Alert 2 - Allied Destroyer - It has a main gun to bombard coastal target, and a Osprey Helicopter docked in the rear that will lift of and bomb enemy subs.

Example 2. Red Alert 2 - Allied Carrier - It's a ship that launches 3 fighters that attacks a target from very long range. If a fighter gets shot down, it will replace it after a set amount of time.

It would be even better if you could set it so that it either replace units auto. or that the player need to pay to replace the unit (might be hard to code in)
##

**Comment by forcecore** [comment]
I have it in my mod but requires engine modification too.
Not making PR though...
https://github.com/forcecore/OpenRA/blob/yupgi-20170527/OpenRA.Mods.yupgi_alert/Traits/Spawner.cs

**Comment by Mailaender** [comment]
We added it in https://github.com/OpenRA/ra2/pull/682.

**Comment by abcdefg30** [comment]
Closing as resolved then.

**Comment by Leo512bit** [comment]
> Closing as resolved then.

But this is not upstream though....

**Comment by abcdefg30** [comment]
We generally avoid adding custom traits that are not used by any of the default mods to the main repository.
