### ISSUE TITLE
Encyclopedia

### ISSUE THREAD

**Issue by HSFOutcast** [OpenRA/OpenRA#3788]
Something that might take a while to add but would be totaly worth it imo.

In Dune 2 you could check an encyclopedia with all units in that game.

We could use something like that in openRA (it wont be much use when you play multiplayer, but it will be a nice touch imo)

A good example here is the game "Battle for Wesnoth".

**Comment by x-a-n-a-x** [comment]
@AlexaDeWit : any news about this issue and your branch ?

**Comment by AlexaDeWit** [comment]
@x-a-n-a-x Sorry man, life has taken and adventurous series of events and my time has been very limited. Work has essentially been abandoned for the foreseeable future. Hopefully someone with more time and ambition will take up the cause :3
