### ISSUE TITLE
Unit commandbar

### ISSUE THREAD

**Issue by HSFOutcast** [OpenRA/OpenRA#3789]
I think this will save us alot of headache in the future.

The idea is to have a small commandbar for units so that we can have specific unit commands for special units.

i.ex. Generals uses a HUGE commandbar, Good example is the humvee that can be upgraded on a per unit basis with drones.

Better example. RA3 have a very small commandbar for units that could be used for secial functions ranging from a button to order aircraft to return to base ASAP or maybe have tanks that can have deployable smoke grenades. (it will also enrich the modding experiences some)

Implemented in:
- [x] RA #13488
- [x] TD #13442
- [x] D2k #13552
- [ ] TS

##

**Comment by x-a-n-a-x** [comment]
I am commenting here (not to flood @WolfGaming's https://github.com/OpenRA/OpenRA/pull/11815 PR with interface-related discussion).

WolfGaming requires these (Orders) icons: 
**Attack Move, Guard, HoldFire, ReturnFire, Defend, AttackAnything, Deploy, Place Minefield, Unload**

But I tend to think that we should also add other handy icons: 
**Jump to base, Select all combat units, Select units by type, Cycle production facilities, Stop, Scatter, Cycle Stance, ...**

What do you think? Please tell me which icons you all want to add onto this bar, before I (or someone else) really start working on them.

Here is a first mockup-image for this "Orders-bar":

![orders_frame_02](https://cloud.githubusercontent.com/assets/1732773/17643184/438fb152-6162-11e6-8d4a-d2bf36f12eb1.png)

As you can see, the interface (a bit similar to the one from RA2) is placed at the bottom of the screen and is compatible with the 800x600 resolution (but the Performance Text and Graph will have to be moved 15 pixels higher).

Btw, this is just a mockup-image, the bar won't be necessary this wide. It's up to you, guys, to tell me which icons you want. PS: I tend to prefer colored icons.

**Comment by GraionDilach** [comment]
IMO a bottombar is a bad idea. I didn't looked much into the PR, but from what I've seen the whole setup is aimed to be expandable, being a huge leap to create spells/abilities (Generals, Warcraft) and stuff like that, with the options depending on that actual selection and not stuff like production or selection buttons. Also, the Stances were already listed among the requested buttons, so I guess WG aims to ahve them shown like in AoE2 where all stances were selectable and it wasn't a cycle to spam until the chosen one comes.

**Comment by WolfGaming** [comment]
just to elaborate on xanaxes wishes (Jump to base, Select all combat units, Select units by type, Cycle production facilities, Stop, Scatter, Cycle Stance, ...) If we want to implement these I would probably need to add another Order UI element that looks for these order definitions on a trait inside the player actor as making the logic for these buttons work with the current implementation is impossible.

**Comment by pchote** [comment]
> Here is a first mockup-image for this "Orders-bar":

Sorry to be be a party pooper, but I really don't like this mock up.  It is very cluttered, and I can't interpret what half of the icons are supposed to mean.  Making it do *everything* makes it hard to do any specific *something*, which then defeats the purpose of having the UI.  If we are going to add a command-bar at all then its functionality needs to be carefully planned/designed.

**Comment by x-a-n-a-x** [comment]
pchote: icons shown in the mock up are mostly placeholder ones. 
Indeed, as you said, this interface/functionality needs to be carefully planned.

**Comment by x-a-n-a-x** [comment]
Current progress: 

![orders_frame_03](https://cloud.githubusercontent.com/assets/1732773/17832863/47752fde-670e-11e6-8b70-e8cbbc097167.png)

move, attack move, hold fire, return fire, defend, attack anything, deploy, mine, unload

**Comment by StexoO** [comment]
This command bar is a huge progress for touchscreens.

**Comment by 3Lucian** [comment]
could this tab perhaps the openable/closable, accessible for those that wish to use it, help keep it out of the way for those who don't. 

perhaps attach it as a tab style thing behind the map/building window, off to the left of the production tabs/maps?

example:

![47752fde-670e-11e6-8b70-e8cbbc097167](https://cloud.githubusercontent.com/assets/24759755/21469793/3895669c-cab3-11e6-8e5f-485b6b7211a7.png)

Ignore the now sideways icons, i did this is MS paint in about 3 mins.

**Comment by pchote** [comment]
D2K PR now up at #13552.  Moving to next release milestone because TS is not required for the playtest, but *is* required for the final release (because I want to be able to finally kill the `UnitCommandWidget`).

**Comment by reaperrr** [comment]
Closed via #13802.
