### ISSUE TITLE
New (shared) Gamemode

### ISSUE THREAD

**Issue by HSFOutcast** [OpenRA/OpenRA#3793]
Would love to se some additional options in multiplayer, It would be cool if you could select so teams can use one (or all) of three options.

Option 1: Shared Power - easy explanation, all team members shares power.

Option 2: Shared Economy - also easy. all team members share the same resources, this game mode could be fun in the way that if one player uses to much of the economy to fuel his warfront, the other player will be lacking on his warfront, and so on.. A nice balance must be found.

Option 3: Shared controls - This is awesome for new players that might need some guiding or if for a diffrent type of gamemode. In this gamemode the teams are locked, (i'll let you guys decide if you start with one MCV or if all players in the team get their own MCV). either way, all units are controlable by all players, that way a player thats not that experienced can experience head on and even help another player ingame.

**Comment by pchote** [comment]
A third party mod could implement this by creating a new https://github.com/OpenRA/OpenRA/blob/master/OpenRA.Game/Traits/ValidateOrder.cs trait that allows multiple players to order the same units, and then tweak the lobby UI and game-start traits to give matching behaviour there.

This is a really specific use case that introduces additional complexity to the already busy lobby UI, so I think i'll call this one as out of scope for our default mods.
