### ISSUE TITLE
If engineer captures a building there is no warning sound

### ISSUE THREAD

**Issue by m0nk33** [OpenRA/OpenRA#3797]
We need some kind of warning sound if your buildings are being captured by an engineer. E.g. the "building under attack" standard sound or even better something like "buldings being captured". 
##

**Comment by Smittytron** [comment]
I've seen this brought up awhile back so I'll leave a comment. This would be strongly opposed by competitive players. Warning a player every time an engi cap is happening would make stopping an engineer too easy. Engineer caps would virtually disappear from competitive play.

**Comment by GraionDilach** [comment]
This looks like another engine ticket closed based on feedback from a specific mod.

**Comment by Mailaender** [comment]
You are right. The trait doesn't need to be enabled for the ra mod.

**Comment by abcdefg30** [comment]
I don't see a real reason for this if there is no usecase. It will be trivial to implement (upstream or downstream) in case it is needed. Maybe something can even be done with `BeingCapturedCondition`.
