### ISSUE TITLE
Service/repair pad should be able to sell units

### ISSUE THREAD

**Issue by HSFOutcast** [OpenRA/OpenRA#3798]
If you want to stay true to the original Red Alert then you should be able to sell units while they are on the repair/servicepad.

If im not mistaken that was an function in atleast RA1.

**Comment by pchote** [comment]
This is now straightforward to implement using upgrades:
* Make the service depot apply an upgrade to currently docked units
* Use the upgrade to enable the Sellable trait on vehicles

**Comment by Snurre86** [comment]
The Tool tip should not show that you sell the Nod Buggy if you in fact are about to sell the Repair Facility.
![openra game_2016_11_21_08_03_34_074](https://cloud.githubusercontent.com/assets/7798635/20473501/701a53be-afc1-11e6-9856-c45c80e66774.png)
![openra game_2016_11_21_08_03_36_546](https://cloud.githubusercontent.com/assets/7798635/20473503/701c13c0-afc1-11e6-99a4-97acedd288d8.png)

PS could not get the dollar icon to show in the screenshots.

**Comment by Snurre86** [comment]
If we want current status of no reselling of the vehicle we need this icon.
![openra game_2016_11_21_08_03_34_074](https://cloud.githubusercontent.com/assets/7798635/20474003/802d05c8-afc4-11e6-88b9-4bc61a03004c.png)

**Comment by pchote** [comment]
Selling vehicles in the original games (before they removed the feature) always smelled of a bug when units were on top of buildings that they couldn't easily fix (especially since @epicelite mentioned infantry selling on walls above).  It never worked very well or had a real purpose in the game.  I consider us not having it to be a feature.

**Comment by GraionDilach** [comment]
It might started out as that, but RA2 (and maybe TS already) had separate selling cursors for vehicles and buildings, which implies an Ascended Glitch to me.

**Comment by pchote** [comment]
Yep, but then they removed it completely in YR (or was it one of the RA2 patches?).

**Comment by GraionDilach** [comment]
It was YR - probably they did this for the Grinder to be unique.

**Comment by hypercube33** [comment]
Also note that the hot keys are jacked up for some of the mods - X should scatter units, not bring up the sell cursor.

**Comment by Phrohdoh** [comment]
Ctrl-X scatters, iirc.

**Comment by abcdefg30** [comment]
> Also note that the hot keys are jacked up for some of the mods - X should scatter units, not bring up the sell cursor.

Sounds like someone messed with your hotkey setup. The power down cursor is triggered when pressing `x` (and yes, `ctrl` + `x` is scatter): https://github.com/OpenRA/OpenRA/wiki/Hotkeys

**Comment by hypercube33** [comment]
CTRL+X is dumb since X is the scatter from original CNC.

To that point however, it doesn't work worth a shit anyway...

The sell function is good because you have units that can take husks and hijack vehicles - which is an attack on your part, but if you don't, for example, actually want the unit, you can sell it for cash.

Also, crates may give you stuff you dont want. Or if you're nearly dead, selling off units to buy an MCV.

**Comment by Snurre86** [comment]
No change.
![openra game_2017_03_18_00_44_18_558](https://cloud.githubusercontent.com/assets/7798635/24067332/4c69e4fa-0b7b-11e7-8061-831bc76d6a01.png)
![openra game_2017_03_18_00_44_21_285](https://cloud.githubusercontent.com/assets/7798635/24067331/4c66b3f2-0b7b-11e7-8d9b-eacd08ccc5fe.png)

**Comment by Snurre86** [comment]
You are not selling the yak.
![openra game_2017_03_18_00_02_21_298](https://cloud.githubusercontent.com/assets/7798635/24173859/2b8798de-0e8e-11e7-9619-057e644c744b.png)

**Comment by forcecore** [comment]
Very ancient topic but once you guys sort out "Engineer to enter/repair" priority problem by force move order, then you might be able to use "DeliversCash": make units "Force enter" FIX then they will turn into cash!

**Comment by Smittytron** [comment]
After discussion in our github-cleanup Discord channel I'm closing this as won't-fix. To summarize:

>  8:45 AM] pchote: I still see it as a hack to work around a bug in the original game engine where the sell cursor would act on anything on top of a building (can still be abused to see things in front of walls)
- A few mentioned they feel selling from the SD doesn't fit the modern approach of OpenRA
- There would be a few edge cases to work out like how do you prevent a player from accidently selling one when they meant to sell the other.
- I mentioned using the $ command the same way we use the repair wrench to order a vehicle to go to SD to be sold. Someone would have to be willing to tackle that and it wouldn't cover the other issues.
- Nothing seems to be in the way of modders adding this if they want.
