### ISSUE TITLE
Global Conquest mode

### ISSUE THREAD

**Issue by KOYK** [OpenRA/OpenRA#3814]
ok this one its huge but its worth it for many reasons!
walk with me on this one

imagine this

![globalcon](https://f.cloud.github.com/assets/5400487/1097199/ce400890-170c-11e3-9270-efa94c79af4b.JPG)

1) a map with regions made by shp files(so you can attack them)

2) turn based movement  

3) battles start in a battle map NOT in the global map

4) battle maps are unique for each region

5) armys per region or continental (like north america= +1 army) or user defined 36 per user + continental.or 2 per user you know user\server defined ect..

6) diplomacy for traitors like hasan (tiberian sun) or civilians,mutants,sadukar. give regions to other players. transfer money or units by convoys,
every map the convoy passes Through  is one turn for the convoy to reach the region. (this could be a mission for the enemy to stop it or steel it.) or even allow to other allied players to build in the same region.

7) dynamic join ect. players that have armys in neighborhood regions can enter the battlemap in the middle of the battle after a specific time and aid or divide other players

8) reinforcements like above but the army is yours, builded by you, controled by you.

9) armys that enter the  battle map are changing region the global map as well and stays ther after battle IF are still alive

10) battle maps that have 2 or more winner allied players on them are changing owner by vote or can have it together (2 or more bases per battlemap defined by the server) EXCEPT if the battle was defensive in that situation the region stays to the defender allied player

11) the battle maps must have entry points for the enemy\allied forces to join in
and that can be the 4 corners and the 2 vertical  2 horizontal (ect +) lines in the battlemap based on the region map

12) to enter a battlemap that have sea saround it you must have transport ship and that means you need a shipyard in a region that have sea on it.
except if the map got an entry point that connected to the land

13) after battle you can revisit the battle map and build buildings and defenses(the number of buildings that you can build per turn is specified by the server)

14) you CANT build everywhere in the battle map in the re-visit mode, every map will have starting point ware the bases of the owner and his allies will stay and build in a limited space around the starting point. this space is defined by the battlemap arthur /maker/creator.

15) in the global map the user will be able to make build units for defense(the number is defined by the server per region) in regions but the specified build region must have the appropriate building to do so.

16) you can occupy regions with only troops but you understand the minus on that.

17)  players can name ther bases in the global map

18) you need to make a research in the global map to have new buildings and units and super weapons ect... 

19) regions=shp will have the color of the owner or server defined color

20) players names will shown in the owning regions.

21) in the global map you will able to see your units per region money tech ect...

22) money will rise every turn by 3 ways 
A) specified by the server ex. for every region +1000 money per turn
B) the above plus the money you have in a battle after you win (if the above set to zero you will have to do battles to earn money)
G) you will earn money per turn by having a continent(europe,africa,ect) under your\allied control

23) the global conquest mode can be used for making singleplayer campaigns too!
with films and staff.

24) films may be add  in multiplayer too for coop games "player vs scenario\AI" or "players vs Players scenario"  films can showed up at the start of a battle in win or loose.

25) coop games will have the option of losing a region permanently or be able to re-take or it can be for specific regions.

26) a game save option must added for global conquest and for battle maps (revisit mode is a save but it can be loaded in any time from the global map with out interrupting the global turn and its used to store ware the buildings\units  will be in the next battle(its not something that will load a saved battle! its like a map editor,fro placing units\buildings per turn)

27) this can be used for avery game ra td ts ra2 dune!

i am not a programmer and i will not be i have try it but dint work out many times!!!
so dont ask me to make it! or learn C#

i hope this will be added but i know it will take a long long long long long time to be added or it will never added...

**Comment by pchote** [comment]
This is a huge feature that is out of scope for our default mods.  This could be done by a third party mod, and then if that became popular we could perhaps consider merging the feature upstream.
