### ISSUE TITLE
Unreachable crate behind refinery [$10]

### ISSUE THREAD

**Issue by dn150** [OpenRA/OpenRA#3871]
A crate landed top left of the refinery (just behind it). I tried to send riflemen to it, but when I right click to select the area of the crate, instead it selects the entrance to the refinery, and the riflemen block my ore trucks.

OpenRA release-20130915

**Comment by deniz1a** [comment]
A possible solution is first detecting if there's an overlap of selection boxes. If there is, the selection could be based on the base tiles/cells of the building. If the cursor is over the tiles of nuclear silo for example, it gets selected, if it moves over to the base tiles of the power plant, it gets selected...

**Comment by deniz1a** [comment]
Or generally make selection cursor only active on building tiles.

**Comment by deniz1a** [comment]
This is a general issue with cursor-actor interaction. If I understand it correctly, the bounds are considered to determine if an actor is selectable. I think it should be footprint cells for buildings and cell or subcell for units. Bounds are the rectangles that are shown when something is selected.

All the buildings in this image are unselectable, untargetable etc:
![unreachable2](https://cloud.githubusercontent.com/assets/6599106/6735343/3db34130-ce66-11e4-889f-e8f8a3335837.png)

**Comment by penev92** [comment]
Take a look at D2k's High Tech Facility and Ix lab. You will notice they both have the same footprint, both are tall, but only the first one has the described problem. This is because the Ix lab's selection box, while not completely correct, is shorter and doesn't cover the cells behind the structure completely. Here's a nice and easy way to fix this.

**Comment by jimmywatson** [comment]
From #7662 
"Just tested, with the silo being built first it does seem to allow repair. Might be engine related to how it handles base tiling and select-able objects that may have overlapping tiles."

![14618830-ca44-11e4-9a5e-3b2e1e6e8e22](https://cloud.githubusercontent.com/assets/11268975/6945568/91c225ee-d892-11e4-8039-d47d98c63cad.png)

**Comment by reaperrr** [comment]
While it would be even better if the engine was smart enough to decide this per cell by checking passability/space occupance, for all three currently shipping mods this has been solved by decoupling visual selection boxes from selectable area and reducing the latter on problematic buildings in #8388.
