### ISSUE TITLE
Changelog and Folders in map.oramap

### ISSUE THREAD

**Issue by Kaito-Kid** [OpenRA/OpenRA#4063]
I would prefer if you can put a rules.yaml and sequences.yaml file in the oramap-package. (for better structuring)

It would be also heart if you can implement a change log in map.yamls because i make many map-updates and the players ask me whats new there.
##

**Comment by pchote** [comment]
rules.yaml/sequences.yaml was implemented in #10839.
Support for reporting text (including changelogs) in the lobby was added in #11993.
