### ISSUE TITLE
Save last map by name not hash, auto-enable developer cheats and live rule reloading when modifying maps while the game is running

### ISSUE THREAD

**Issue by Kaito-Kid** [OpenRA/OpenRA#4067]
Every time I change something on a map I have to
1) start the OpenRA-Game
2) Select the Map
3) Turn Debug-Mode on
4) Ingame activate the Cheats (for testing)
5) testing and close the Game
And if I change one small thing I have to do all 5 steps

suggestion1) The Map what was choose the last time is saved in settings.yaml

suggestion2) You can (actually) define in map.yaml with Cheats: true that debug is activated. Maybe you can also choose what Cheats are at game-start activated

suggestion3) This utopian but maybe it is possible to take over the changes from map.yaml without restarting  the game

**Comment by Mailaender** [comment]
This bug is probably un-close-able as it contains 3 wishes that are mostly unrelated to each other. I suggest you open new ones for each individual feature request. Also try to avoid very generic titles.
