### ISSUE TITLE
Add a drop-down menu (in Settings) to quickly change resolution

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#4120]
Please add a drop-down menu in the Display Settings to quickly change resolution.

No need to remove the textfields (those which are used to manually enter a custom resolution) but a new menu could list common resolutions (4:3 and 16:9) as well as the last entered custom resolution.

![resolution](https://f.cloud.github.com/assets/1732773/1508824/b67f2b80-4a1c-11e3-8168-a11622dcc4f0.gif)

**Comment by pchote** [comment]
This is covered more comprehensively by #10382.
