### ISSUE TITLE
Aircraft Carrier traits

### ISSUE THREAD

**Issue by xan2622** [OpenRA/OpenRA#4157]
Could it be possible to add new traits for the aircraft carrier to let it: 
- [ ] rearm aircrafts while also still being mobile
- [ ] repair aircrafts while also still being mobile
- [ ] let it create new aircrafts after being imobilized
##

**Comment by MustaphaTR** [comment]
>  let it create new aircrafts after being imobilized.

I'm pretty sure Produces: trait already works with mobile actors.

**Comment by Mailaender** [comment]
We added it in https://github.com/OpenRA/ra2/pull/682.

**Comment by abcdefg30** [comment]
Closing as resolved then.
