### ISSUE TITLE
AI drop-down menu more visible (RA)

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#4158]
The recent changes on this drop-down menu made it almost perfect (talking about ease of use) but the RA red theme sometimes makes things hard to recognize.

What if the whole UI got darker as soon as drop-down menus are used ?
This would help the player focus on the menu choices.

![uidarker_dropdownmenu](https://f.cloud.github.com/assets/1732773/1580060/3d20bbf4-51b1-11e3-930c-25db4202ffdb.gif)

**Comment by x-a-n-a-x** [comment]
Closing this issue since it's not likely to be added (I agree to say that the idea was somehow weird.. in a way). 

Then, why did I create this issue? 
My goal was mostly to point out the limits of our current UI engine (how the drop-down menus look cluttered and skimpy, especially the sub-titles: slots, bots).

**Comment by Phrohdoh** [comment]
I agree that we could use more contrast in the UI themes.
