### ISSUE TITLE
Fix Helicopters shadows

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#4164]
Here is an example of how helicopters shadows should look ingame (on the left):
![untitled-1](https://f.cloud.github.com/assets/1732773/1589508/b2ff3a6a-5271-11e3-864c-76692c9514e3.gif)

I think helicopter blades should blend with the helicopter body.

**Comment by pchote** [comment]
Reverse-duplicate of #6019.
