### ISSUE TITLE
Map Chooser Sorting options

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#4165]
I could be interesting to add Sorting Options for the map chooser.
For example: 
- sort by the number of times a map has been played
- sort by map name
- sort by author
- sort by map rating
- sort by the number of players the map is made for

![e676966](https://cloud.githubusercontent.com/assets/1732773/3489544/773605c8-0535-11e4-8877-9be253db2d50.gif)

For the map rating system, maybe it could be done online at http://content.open-ra.org/ ? (ihptru is making a new version of his website).

For the 'number of times a map has been played', maybe the server could record statistics based on players' choices, ingame.

**Comment by pchote** [comment]
This has been almost completely covered by the search/filter feature.
