### ISSUE TITLE
Move BuildPaletteOrder to ChromeMetrics

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#4180]
##

**Comment by pchote** [comment]
I don't think this is relevant anymore, so closing.

**Comment by Mailaender** [comment]
I opened it up due to the following line, which is still part of the code base:

https://github.com/OpenRA/OpenRA/blob/bb536ee4fcf0e5d5afd6cf2537fd92b76db059cf/OpenRA.Mods.Common/Traits/Buildable.cs#L49-L50

**Comment by pchote** [comment]
Removed in #15599.
