### ISSUE TITLE
Building destruction should leave crater smudges

### ISSUE THREAD

**Issue by ScottNZ** [OpenRA/OpenRA#4197]
##

**Comment by reaperrr** [comment]
I think the most sensible way might be to deprecate the very limited and unflexible `WithBuildingExplosion`, add a `CenterPosition/Footprint` switch to `Explodes` and use that instead.

That way, we could use a weapon that spawns smudges. Another positive side-effect would that we could then define the delay on the warhead and getting rid of `WithBuildingExplosion` would mean getting rid of a trait that uses `DelayedAction`.

**Comment by GraionDilach** [comment]
Another gain of having Explodes instead of WBE is the damagetypes support.
