### ISSUE TITLE
Easy to understand exception messages for all YAML problems [$15]

### ISSUE THREAD

**Issue by Angusm3** [OpenRA/OpenRA#4226]
most of the time I can tell what the exception log is telling me, ie "there aren't any frames there" for something I mussed up in the sequences, or "this file isn't there" for an shp I forgot to convert to the proper format

but there are so many exception logs that just say something like 
"Value cannot be null."  that I can't figure out and I need to go into the chat, or look through everything I've changed since I last tested the game

so it would be nice to have a couple lines at the top or bottom of the exception log that say "check your prerequisites in the structures.yaml under the item FSAL" or something like that

- [x] #4225 
- [x] #3568

**Comment by Mailaender** [comment]
I guess things like https://github.com/OpenRA/OpenRA/pull/7581 count to this, but the described problem is far too generic. Closing. Please provide us real problems and cases describing how to reproduce them to get them fixed.

**Comment by Mailaender** [comment]
@pchote I think you can claim this bounty with https://github.com/OpenRA/OpenRA/pull/8000.
