### ISSUE TITLE
Better Medic AI.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#4292]
It would be nice if the medic would not run up, and stand next to, the current target if they were selected when choosing said target. In one of the Tiberian Sun patches the Medic would auto heal nearby injured infantry and not run twords the enemy.

**Comment by Snurre86** [comment]
Also see: #6624 #5507 #5028

**Comment by pchote** [comment]
Medic targeting was overhauled for the last release, so I believe this is now fixed.
