### ISSUE TITLE
HealthRadius of 10 unfitting for large buildings

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#4310]
Right now, even large buildings like Construction Yards are technically no easier to hit than silos, defenses or standing vehicles.

This is not only unrealistic, but also not in line with the original, where a direct hit to any cell occupied by a building would deal full damage.

My suggestion would be to give buildings sized 2x2 and larger appropriate HealthRadiuses, but of course in terms of balancing that might open a can of worms initially because inaccurate artillery weapons would become much more effective against large buildings, so this would need quite a bit of testing and fine-tuning.
##

**Comment by MustaphaTR** [comment]
I guess we can say this is fixed by recent targeting changes.
