### ISSUE TITLE
Proposal: make JEEP, ARTI, FLAK, TRUK and 1TNK transportable with TRAN

### ISSUE THREAD

**Issue by wuschel** [OpenRA/OpenRA#4312]
Hi, before I make any changes in this direction I would like to discuss this:

I propose to let JEEP, ARTI, FLAK, TRUK and 1TNK be transportable with TRAN. The motivation behind this is simple: Give the allied player an alternative route for harassment. Of course, each TRAN would be capable to transport one vehicle.

I guess the best way to implement this would be the creation of a vehicles-light.yaml file and a VehiclesLight vehicle class, as add the *Passenger: Weight: big number* to vehicles that should not be allowed to be air-lifted will affect their capability to be transported by sea. Any better ideas? Comments?

**Comment by pchote** [comment]
This is technically possible, but is unlikely to happen in the RA mod.

**Comment by Mailaender** [comment]
Duplicate of https://github.com/OpenRA/OpenRA/issues/8954 if done right.
