### ISSUE TITLE
cmd+click on Mac OS X (20131223)

### ISSUE THREAD

**Issue by rmoriz** [OpenRA/OpenRA#4351]
On 20131223-Release cmd+click does not work on Mac OS X to command troops anymore.
##

**Comment by weaverryan** [comment]
Confirming this still doesn't work on the latest playtest release (nor does that release have left+click, but that was added back in #7501 

Is this happening for all OSX users? Any workaround that anyone knows of?

Thanks!

**Comment by whi7ed3vil** [comment]
Two-finger pad clicks actually work in my experience. It's a pain in the rear, though.
