### ISSUE TITLE
Verified in-game names.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#4410]
Ok so what if you could log-into openRA with an account to have your username verified. (Indicated by a gold star infront if your name, you can't change your name while in this state and no other verified users can have the same name.) This way we don't have people running around stealing others name's.

We can still allow people to play account free just like now, but with logging in as an option.

This would also allow stat-tracking and even a ladder!

Now the main issue is deciding where people should make an account to use in openRA. Should we have our own custom server, or just use GetHUB accounts? 

Pros and cons of each need to be analyzed.

**Comment by pchote** [comment]
Closing as duplicate (only 2 and half years late).
