### ISSUE TITLE
Detect Xinerama

### ISSUE THREAD

**Issue by xaionaro** [OpenRA/OpenRA#4440]
On the first running, OpenRA is maximizing to pseudo full-screen. But it doesn't check Xorg server for Xinerama, so the screen stretches through 3 monitors on my system, that is really inconvenient.

IMHO, OpenRA should be able to detect Xinerama and maximize only through 1 monitor.

> Desktop resolution: 5280x1080
##

**Comment by pchote** [comment]
The version of SDL2 shipped in the AppImages include Xinerama support.
