### ISSUE TITLE
Color picker area is not filled with colors.

### ISSUE THREAD

**Issue by xaionaro** [OpenRA/OpenRA#4451]
When I start openra instance and trying to pick the color, I see next window:

![Colorpicker_bug0](http://ut.mephi.ru/imgs/other/openra-colorpicker-bug0.png "color picker bug")

Bug is constantly repeated on my system. How can I help with debugging?

Related: https://github.com/OpenRA/OpenRA/pull/3169

**Comment by penev92** [comment]
This was fixed in #8618.
