### ISSUE TITLE
Forbid deep black via "~/.openra/settings.yml" editing on client side

### ISSUE THREAD

**Issue by xaionaro** [OpenRA/OpenRA#4452]
It is forbidden to pick deep black color via "color picker", but permitted to get deep black color via "~/.openra/settings.yml" editing. Looks like a bug and should be fixed, IMHO.

In #4425 it was decided, that deep black should be forbidden. So I think it should also be forbidden via "~/.openra/settings.yml" editing.

**Comment by abcdefg30** [comment]
> On #2820 i'm going to validate the player color upon entry on the server (and color change while already in lobby). I can add a simple logic that doesn't allow anything below 0x33 (51) which already is the lower limit for the HSL color picker.

#6239 was merged.
