### ISSUE TITLE
Line damage projectile

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#4458]
There is no line damage yet, making disruptors, railguns and sonic tanks practically useless.

**Comment by Unit158** [comment]
Looking at this a second time, Raycasting makes no sense for this. A proper collision detection algorithm is needed. fun.

**Comment by Mailaender** [comment]
@Bynnar18 has been working on this https://github.com/Bynnar18/OpenRA/compare/sonics in secret.

**Comment by pchote** [comment]
That looks like a direct copy of our existing LaserZap projectile?

**Comment by Unit158** [comment]
You're mistaken. That is the rendering effect for the TS disruptor beam.

**Comment by Bynnar18** [comment]
It's based heavily on the LaserZap, but it does render a sonic beam.
