### ISSUE TITLE
Sardaukar do not deal damage when crushed

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#4476]
A small feature, should probably be put on the back burner until other stuff is done.
##

**Comment by Phrohdoh** [comment]
Did they deal damage to the crushing actor?
How much? Vs which armors? etc.

**Comment by Unit158** [comment]
OmegaBolt should have those values.

**Comment by OmegaBolt** [comment]
No. We don't have any information on any units death weapons... well, we have the weapon stats but nothing saying a unit blows up with X weapon. So it'd need to be tested and guessed-ed.

**Comment by MustaphaTR** [comment]
Note that Saboteurs also deal Cruch damage.

**Comment by Unit158** [comment]
Looks like this was fixed at some point, but this issue was never closed.

**Comment by ltem** [comment]
Something is off. The death explosion doesn't damage the crushing vehicle in OpenRA but for example buildings nearby. 

I crushed several Sardaukars and Grenadiers with a harvester in a local multiplayer game and it didn't take any damage (both sides were controlled by myself by using two OpenRA instances). The `Hold Fire` stance prevented attack damage from the infantry.


Additional information from the original game:
- Saboteurs should have death explosion damage as well.
- There is no explosion effect and sound played if the unit gets crushed. 
- There is a "scream" sound played when the infantry gets crushed, which I cannot find in the d2k content folder.

I made some gifs to illustrate the effect and to show how (little) damage the vehicle takes (Source: Gruntmods). 

|![gren_crush](https://user-images.githubusercontent.com/20945684/32703380-36408148-c7f5-11e7-8d2b-d10a57a066fc.gif)|![sab_crush](https://user-images.githubusercontent.com/20945684/32703381-365fa10e-c7f5-11e7-8577-7ace0bed9167.gif)|![sard_crush](https://user-images.githubusercontent.com/20945684/32703382-367b4332-c7f5-11e7-831a-c495abbbd175.gif)|
|:----:|:---:|:---:|
|Grenadier|Saboteur|Sardaukar|

**Comment by penev92** [comment]
Sounds like we're not done here, unfortunately.

**Comment by Mailaender** [comment]
This was added in https://github.com/OpenRA/OpenRA/pull/9340.
