### ISSUE TITLE
Setup sides, factions, colors, map options and actor propreties (facing, health, stance?) in map editor.

### ISSUE THREAD

**Issue by kaneCVR** [OpenRA/OpenRA#4488]
Scripting missions for OpenRA mods is very difficult right now. One way to make it easier would be to allow player setup in the map editor. I propose:

- ability to add/remove players/factions
- setup, lock / unlock factions and colors
- setup default map options like mission/map type (conquest, campaign, etc), fog, shroud, crates, etc
-  setup Actor properties and behaviour (facing, health, stance) - right click menu maybe?

**Comment by Mailaender** [comment]
Cleaning up the bug tracker from cluttered meta bugs. Please keep it one wish per issue.

**Comment by Mailaender** [comment]
We forgot about health: https://github.com/OpenRA/OpenRA/issues/10818.
