### ISSUE TITLE
Pan view button occasionally "sticks"

### ISSUE THREAD

**Issue by AgentAAA** [OpenRA/OpenRA#4522]
the icon for "pan view" can sometimes be clicked to turn pan view on and then refuse to turn off after being clicked a second time. This issue appears to be surmounted by turning on the "erase actors and resources" function via clicking the eraser icon, and turning the now-functioning "Pan view" function off via clicking the hand icon.
seems to happen randomly and go away equally randomly.

**Comment by pchote** [comment]
This has been fixed by the new editor.
