### ISSUE TITLE
Implement unit priority for rearm and repair

### ISSUE THREAD

**Issue by pizzaoverhead** [OpenRA/OpenRA#4549]
When sending a group of units to repair or rearm at a service depot, helipad or airfield, priority should be given to units with the greatest need of the structure (heavily damaged, no remaining amunition), followed by those closest to it. Currently, a group of heavily damaged units around the a service depot may wait for a fully repaired unit to arrive from some distance away.
##

**Comment by matjaeck** [comment]
This would be nice.

**Comment by Smittytron** [comment]
Ideally repair/rearm would be first-come first-serve so that there is no wasted time. The problem with the request here is the inverse is also a problem: Units ready to repair waiting on a lower health unit to make it's way across the map.

Closing this issue as it's unlikely to happen.
