### ISSUE TITLE
AI should make use of oil derricks

### ISSUE THREAD

**Issue by pizzaoverhead** [OpenRA/OpenRA#4561]
Currently AI players ignore capturable oil derricks. Capturing these should be prioritised from the start. When oil derricks are available and ore is limited or unavailable, AI players should not build multiple refineries. Small teams of infantry and light vehicles could be assembled to escort the engineers or their transports, and then guard the captured derricks. An AI-owned derrick under attack should cause the AI to send support units and repair it if damaged.

**Comment by MustaphaTR** [comment]
They now capture the Oil Derricks after AI Engineer logic implemented. Also Normal and Turtle use them with my PR. I think this may be closed.

**Comment by pchote** [comment]
@MustaphaTR: add "Fixes #4561" to the description of your PR, and github will automatically close this when it is merged.  We do not manually close tickets before a PR is merged.

**Comment by obrakmann** [comment]
This is already in the playtest, if only for one AI, so closing is fine, IMO.

**Comment by pchote** [comment]
See #12206.
