### ISSUE TITLE
Shock trouper's seem lackluster

### ISSUE THREAD

**Issue by Doctormedic** [OpenRA/OpenRA#4589]
Their porpuse seems vague,If it is for rifle and rocket control flamethrowers are better and cheaper,they are slow,requiring a mass to take down 1 mediumtank and overall useless.
At least the testla tank can withstand some hits.

**Comment by MicroJOo** [comment]
#7794 should improve it

**Comment by Unit158** [comment]
Is this still true? I personally think they're pretty bad-ass now.
