### ISSUE TITLE
More crate goodies?

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#4590]
Why don't we have a larger variety of crate goodies? 

Lemme see if I can whip up a few ideas,

Positive effects:
 - Spy Satellite: Select an area of the map to reveal and it stays revealed for 60 seconds.
 - Double your power for XX seconds.
 - Temporarily increased build speed.
 -  Free random building of your side, no cost and pre-built.(shows up in the super-weapons area but you can only place it like any other building.) (Obviously we don't want people with 2 nuke silo's so that has to be taken into account.)

Negative effects:
 - Reduce your power for XX seconds.
 - Shuts down your base defenses for XX seconds.
 - Teleports the unit that picked up the crate to a random spot on the map. 
 - Lose $1000.

I literally just made these ideas up on the spot so feel free to dismiss them as stupid.

**Comment by pchote** [comment]
Crates have been overhauled a couple of times since this was created, so closing.
