### ISSUE TITLE
Chinook doesn't block vehicles when landed

### ISSUE THREAD

**Issue by ScottNZ** [OpenRA/OpenRA#4605]
Affects RA. May or may not affect TD.
##

**Comment by Snurre86** [comment]
Here is a picture showing it. The heli can not pick up crates but if you land with an infantry on a hill with only 2 cells and a crate on 1 of them you can eject the infantry unit on the crate and then move the tank from the crate in the helis cell.
![xg04jyj](https://cloud.githubusercontent.com/assets/7798635/6340587/ebdbf788-bbc0-11e4-991f-170b41f94709.png)
More pictures:
![openra game_2015_02_24_09_43_32_610](https://cloud.githubusercontent.com/assets/7798635/6345975/aa28e26a-bc0b-11e4-809e-adcc9ea78f4e.png)
![openra game_2015_02_24_09_43_49_627](https://cloud.githubusercontent.com/assets/7798635/6345979/b540cce4-bc0b-11e4-9f62-be1bbe075f3e.png)
![openra game_2015_02_24_09_43_59_841](https://cloud.githubusercontent.com/assets/7798635/6345982/c13ed46e-bc0b-11e4-8e6c-bd32b58fa446.png)
![openra game_2015_02_24_09_44_04_129](https://cloud.githubusercontent.com/assets/7798635/6345985/c73f1234-bc0b-11e4-9ad5-7abd0db18a88.png)
![openra game_2015_02_24_09_44_10_413](https://cloud.githubusercontent.com/assets/7798635/6345988/cdfb502e-bc0b-11e4-81ba-8e3ec99dc2c0.png)
![openra game_2015_02_24_09_44_18_578](https://cloud.githubusercontent.com/assets/7798635/6345994/d5b2a2c2-bc0b-11e4-8de3-a27f537ed47b.png)

**Comment by matjaeck** [comment]
Present in playtest-20180729.
