### ISSUE TITLE
Unit production stalls when structure's rally point is occupied

### ISSUE THREAD

**Issue by RiderRockon** [OpenRA/OpenRA#4736]
This seems to be the case for all unit producing structures. When a unit pops out of it and cannot path to the rally point (because the rally point is blocked by another unit) the unit will stop moving where it is and prevent further production.

I'd suggest the unit attempt to move as close to the rally point as possible instead, so as to not inhibit unit production.

**Comment by Mailaender** [comment]
Fixed again in https://github.com/OpenRA/OpenRA/pull/7416.
