### ISSUE TITLE
Kamikaze as secondary attack for Yaks and Migs

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#4751]
When a Yak or Mig crashes into a building it inflicts more damage than it would using its weapons. It would be a nice feature to have a secondary attack for planes to crash themselves into targets. This would also require implementation of secondary attack option in general.

**Comment by pchote** [comment]
Players can micro aircraft to do this, but adding it as an explicit order is not likely to happen in the RA mod.
