### ISSUE TITLE
Own destroyed building visible through the darkness

### ISSUE THREAD

**Issue by Temeez** [OpenRA/OpenRA#4754]
I am fairly sure that airfield was the last one get destroyed.
https://www.dropbox.com/s/gpzg5c6kzc8f7ho/OpenRA.Game%202014-02-27%2021-41-37-819.png

**Comment by obrakmann** [comment]
See also #7916

**Comment by pchote** [comment]
Have the recent changes to frozen actors and visibility fixed this?

**Comment by obrakmann** [comment]
Just tested it, it's fixed.
