### ISSUE TITLE
Exit transport command can't be queued.

### ISSUE THREAD

**Issue by VVheat** [OpenRA/OpenRA#4774]
If I order an APC to move from A to B, then hold down SHIFT, then click on the APC, the move command will be canceled, and the APC will deploy its infantry at its current location.

If I order an APC to move from A to B, then hold down SHIFT, then push F, the APC will move to location B and then do nothing.

This was tested in the TD mod.
##

**Comment by matjaeck** [comment]
Present in RA for playtest-20180729, however queued deploy command for MCV works.
