### ISSUE TITLE
Remember faction for the mod?

### ISSUE THREAD

**Issue by VagueVigor** [OpenRA/OpenRA#4787]
Would be nice, but simple addition.

So if i play almost always with Allies, i dont have to select it every time i play.

**Comment by TheRaffy** [comment]
also nice would a remining of the server filters: waiting empty protected started incompatible

**Comment by rob-v** [comment]
PR created https://github.com/OpenRA/OpenRA/pull/12990

Added support for per mod settings in settings._mod_.yaml file. Currently supported options:

Player - Name, Color, LastServer (MP Direct IP Address:port)
Skirmish - Faction, Team
Multiplayer - Faction, Team
Server - all options from settings.yaml (MP Create Game name, port, map,...)

**Comment by xlucn** [comment]
Does this feature request also cover number of AIs, AI's factions and maybe more? Or is there another issue for those?

The reason I come up with these is that, if I play a local, multi-player map with AIs, I have to click dozens of times to add an AI to new slot, configure the AI's type, team, handicap, etc. However, for these settings, I don't want many changes between every game.

**Comment by PunkPun** [comment]
Try using the `Slot Admin` dropdown in skirmish lobby. With it you can easily fill the lobby with AI's

**Comment by xlucn** [comment]
Thanks, that's better, haven't found about that.

Although, it still could not cover all the cases. E.g., if I love to play 2v4 or 3v5, or 1v2 with 15% handicap for AIs, or positions. Slot admin does not provide endless possible fine tunes, which I might like to keep the same for many games.
