### ISSUE TITLE
Craters should be removed when placing a building or deploying an MCV on top of it.

### ISSUE THREAD

**Issue by VVheat** [OpenRA/OpenRA#4791]
Right now, after the building is sold, or the MCV unpacked, the crater is still there.

This would let players undo the damage they did to the map.

**Comment by evgeniysergeev** [comment]
Any news on this issue?
This video illustrate issue: https://streamable.com/t945

**Comment by yaaaaa** [comment]
Евгений, мод dune2? где можно последить за прогрессом?

**Comment by evgeniysergeev** [comment]
#11207 will helps to clean the ground.
