### ISSUE TITLE
Redefined stances

### ISSUE THREAD

**Issue by pizzaoverhead** [OpenRA/OpenRA#4819]
A proposal for some changes to stances for discussion. Hold fire and return fire remain unchanged.
- Hold fire - Don't react automatically to enemy units.
- Return fire - Open fire on the source of any damage, never move. Default stance for stealth units.
- Hold ground - Open fire on anything that enters range, never move. Default stance.
- Defend - Scan for targets in an area up to n cells beyond the unit's range from its starting point, move to attack any targets found, return to the starting position when the unit is destroyed or has moved. Default stance for AI.
- Pursue - Scan for targets in an area up to n cells beyond the unit's range from its current position, move to attack any targets found.

Are there too many stances currently? Would the Defend stance as defined here be more useful than the current AttackAnything stance? Should the default stance for stealth tanks be hold fire, and return fire for snipers?
##

**Comment by Smittytron** [comment]
> Smitty: Can we consider #4819 as superseded by the stance overhaul from a few years ago?
> pchote: IMO yes, there are still issues with the current stance setup but i believe they are better captured under other open issues
