### ISSUE TITLE
Aircraft facing jittery in some directions

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#4824]
When flying in certain directions, aircraft jitter heavily between two facings, which is rather annoying to look at.

This is probably happening because the aircraft has less available facings than there are directions and in some cases the engine has trouble to decide which facing frame corresponds best with the exact flight direction, switching back and forth between the two closest facings.

**Comment by penev92** [comment]
How did the originals handle these cases?

**Comment by reaperrr** [comment]
> How did the originals handle these cases?

Purely guesswork at this point, but I suspect WW fudged the edge cases to the next facing closer to north/0 and south/128, respectively, to make up for the rendering perspective.


Fwiw, higher `FacingTolerance` on `AttackPlane`/`AttackHeli` eases the jittering, but also increases the chance of a facing frame used that looks rather off compared to the flight direction.

**Comment by tovl** [comment]
Some jitter at the logic level is to be expected. The issue is that that should not be visible in the graphics. The general solution to such problems is to add hysteresis to the sprite facing look-up. In other words, if the yaw of the unit is somewhere between two sprite facings, the unit should prefer the facing it is already on, instead of the facing that is closest to its actual yaw. (of course, the range over which the facing is memory-dependent does not need to cover the entire span between two sprite facings.)

**Comment by pchote** [comment]
It looks like the original game applied small rotations to the sprite itself to bridge the facing gaps. See https://github.com/electronicarts/CnC_Remastered_Collection/blob/master/REDALERT/AIRCRAFT.CPP#L416-L419 and follow its use through `Techno_Draw_Object` and `CC_Draw_Shape` to `GraphicBufferClass::Scale_Rotate`.

It should be relatively straightforward for us to add a similar rotation parameter to `SpriteRenderable`, but we will need to think about how to expose this to yaml in a way that would be useful both for this use case and others (e.g. a top-down mod may want to define just one sprite, and rotate it for all angles).

**Comment by deleted-user-1** [comment]
> It looks like the original game applied small rotations to the sprite itself to bridge the facing gaps. See https://github.com/electronicarts/CnC_Remastered_Collection/blob/master/REDALERT/AIRCRAFT.CPP#L416-L419 and follow its use through `Techno_Draw_Object` and `CC_Draw_Shape` to `GraphicBufferClass::Scale_Rotate`.
> 
> It should be relatively straightforward for us to add a similar rotation parameter to `SpriteRenderable`, but we will need to think about how to expose this to yaml in a way that would be useful both for this use case and others (e.g. a top-down mod may want to define just one sprite, and rotate it for all angles).

Note that the facing-jitter is noticeable with planes in original RA though.
