### ISSUE TITLE
Update max players info when player slots are closed?

### ISSUE THREAD

**Issue by VagueVigor** [OpenRA/OpenRA#4842]
If i want to have 2v2 game on 8v8 map, new people just keep joining because they see that its filled only 4/16.

Would be nice if the max players would update when you close/open player slots.
##

**Comment by rob-v** [comment]
You can still join even when game has no open slots (I can't check it now)?
It can't be done simply by updating lobby client, as it doesn't receive number of open/closed ports, only:
	Players: 0
	MaxPlayers: 3
	Bots: 0
	Spectators: 0
It would require server change, I don't know if it would be approved and even if I have access.

**Comment by rob-v** [comment]
This issue was fixed in 2014, it can be closed.
