### ISSUE TITLE
"Autodirector" for spectator mode

### ISSUE THREAD

**Issue by partouf** [OpenRA/OpenRA#4848]
A couple weeks ago I started a branch in order to code a spectatormode in which you can let the computer decide what's hot and what's not in an observed game.

Newer games like League of Legends, CS: Go, Dota2 and even older games of which I didn't know, have an automatically directed camera view for the viewer to use.

This isn't really something a caster would use, but there could be still moments where you would like the camera not to be on something meaningless while you need to do something else.

Or maybe you want to casually sit back, relax and watch a replay without having to do anything.

Aside from potentially crazy software patents that may or may not be valid in your country http://www.reddit.com/r/leagueoflegends/comments/1x3v1u/riot_games_granted_us_patent_on_spectator_mode/ - I still wanted to give it a go and code it.

So I have a basic version I haven't touched for a week or so, and I would like to get some wild criticism or suggestions on this.

Code:

https://github.com/partouf/OpenRA/compare/bleed...autodirector

This is an old video, because for some reason the one I recorded just now hasn't been saved: http://www.twitch.tv/partouf/b/506940934

Edit: oh it did save after all: http://www.twitch.tv/partouf/b/509993907

(visual difference from current version and that one recorded is that there's now a checkbox (or key F5) to enable the autodirector (default off), and most decisionmaking is less buggy)

There still plenty of bugs to fix, like
- some wrong decisions when armies are close enough to pan the camera, but still jumps
- some moments where the camera gets stuck, probably because of units that still have IsAttacking on eventhough they're not doing anything
- attacking helicopters or planes sometimes aren't really registering

Stuff I still want to implement myself, like watch dropping nukes and similar airweapons for example.

And I still need to test and see if it works just as well with regular people playing the game.

But as I said, I would like to know what other people think of it and what ideas you might have.

**Comment by pchote** [comment]
IIRC this was a cool feature, and we certainly wouldn't turn it down if somebody wanted to resurrect your old code for it.  On the other hand, this feature is far enough out of scope that I don't think we will drive to implement it ourselves, so there isn't a lot of benefit to keeping this open.
