### ISSUE TITLE
Implement a restart mission button

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#4874]
This would be useful for single player but also for multi player game. It would restart the game with the same settings. In multiplayer, there could be a logic similar to the ready tick box in game lobby. If every player agrees, the game restarts.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/issues/10264 has been proposed to add it.

**Comment by abcdefg30** [comment]
#10264 was merged.
