### ISSUE TITLE
Map editor doesn't copy actors in selected area

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#4885]
When I select an area and use the stamp tool to duplicate that area, actors like ore mines and trees are not carried over. Maybe there should be a more straightforward copy/cut/paste selection tool. Because it is not possible to cut a selection at the moment.

**Comment by GrayHatter** [comment]
+1

**Comment by Mailaender** [comment]
The WinForms editor has been removed and so far we don't have a stamp tool. See https://github.com/OpenRA/OpenRA/issues/5241 for an alternative idea on how to solve this.

**Comment by Mailaender** [comment]
Implemented in https://github.com/OpenRA/OpenRA/pull/9885.
