### ISSUE TITLE
D2k Devastator Self Destruct

### ISSUE THREAD

**Issue by Sircrashalot** [OpenRA/OpenRA#4926]
Could you guys add an ability to self destruct or is that already possible?
##

**Comment by Mailaender** [comment]
At first I tried to refactor MADTank into re-usable traits for like `PreventsTeleportOnCondition`, `EjectDriverOnCondition` and  `ShakeOnCondition`, but `ShakeOnCondition` would require another `ITick` for a periodical shake. The split of `Suicides` and `AttackSuicides` was tried first as it made sense to separate two different order types https://github.com/Mailaender/OpenRA/tree/devastator-suicide but it didn't play well with `GrantConditionOnDeploy` to glue together the rest which didn't activate when using the right-click deploy. Only the hotkey hack and command bar triggers all of them at once. So I abandoned this approach.

I went with a simpler version https://github.com/Mailaender/OpenRA/tree/devastator-overload in #13884 where only one state controls everything. Once the reactor overload is triggered the devastator will take damage over time, display an overlay and the explosion type changes to something more "devastating". The original might have had a one-click boom (don't know) but I also assume nuclear reactor meltdowns don't work that way and this is better controllable as you maneuver your tank into an enemy blob.
