### ISSUE TITLE
D2k Random faction

### ISSUE THREAD

**Issue by Sircrashalot** [OpenRA/OpenRA#4931]
Is it only me or does someone else have the same problem with random factions? When i try to use random as a faction player 1 always gets harkonnen and player 2 Atreides.

**Comment by obrakmann** [comment]
Is this still a problem? I just tried it on bleed and got three different factions after only three tries.

**Comment by Mailaender** [comment]
Also can't reproduce. It is possible this issue exists, but we need more evidence.

**Comment by pchote** [comment]
The activity in the shellmap has probably added enough entropy to the system to reduce the effects.
