### ISSUE TITLE
Add shortkey to reload helis/planes ?

### ISSUE THREAD

**Issue by VagueVigor** [OpenRA/OpenRA#4950]
The 'F' button tells them to land, even if they are fully loaded with ammunition.

Would save a lot of clicking if there was a button that made them land only if they are missing any ammunitions. Maybe 'R' button would be good for it.
##

**Comment by rob-v** [comment]
PR #13124

**Comment by pchote** [comment]
The worst part of this was addressed in release-20161019 by preventing fully loaded aircraft from blocking the airfield/helipad.  :-1: for having separate hotkeys for "return all the units I have selected to base" vs "return only some of the units I have selected to base": effectively managing your units is part of playing the game and separates good players from bad.
