### ISSUE TITLE
Add a dead zone before activating lasso selection

### ISSUE THREAD

**Issue by VagueVigor** [OpenRA/OpenRA#4952]
Currently it seems like it goes through all the units under the mouse cursor, and selects all units that overlaps with the mouse.

That causes some serious problems and makes it hard to select units most of the time.

Couldnt this be made so it would always select only the topmost unit and break the selection procedure there?

The old behaviour could still be used if you press SHIFT at the same time when you click; then it could go through all the units under it.

**Comment by Mailaender** [comment]
Fixed in https://github.com/OpenRA/OpenRA/issues/7501.
