### ISSUE TITLE
Add reverse gear to vehicles

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#4968]
Instead of only being able to move in one direction, vehicles could also move in the reverse direction with a decreased speed. This would also make it possible for units that have to face their targets, to shoot while retreating, like artillery and V2 for example. And wheeled vehicles would not turn on the spot like tracked vehicles, but they would reverse and maneuver like cars do.

**Comment by PunkPun** [comment]
#19393 has added support for moving backwards

**Comment by PunkPun** [comment]
> #19393 has added support for moving backwards

Closing
