### ISSUE TITLE
Make health bars 2 pixels shorter

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#4976]
Currently health bars are the same size than its building (48 px).
It makes health bars look weird if buildings are placed side by side:

![screenshot001](https://cloud.githubusercontent.com/assets/1732773/2558261/4dcd3aa8-b73d-11e3-9bfc-4edabb4c96fe.png)

I think 2 pixels should be removed (-1 pixel on each side of the health bar) to make it look like this:

![screenshot002](https://cloud.githubusercontent.com/assets/1732773/2558277/0964312c-b73e-11e3-85cc-e3eac50bb374.png)

So 46px health bars for buildings like Power Plants...
and 22px health bars for silos..

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Graphics/SelectionBarsRenderable.cs#L151 for everyone who wants to work on this.
