### ISSUE TITLE
Ugly kerning in new mod switcher.

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#5017]
##

**Comment by RoosterDragon** [comment]
Is this still an issue? It looks OK to me these days.

![](http://i.imgur.com/nLpKgKM.png)

**Comment by pchote** [comment]
I expect it is.  We still aren't using the kerning hints that are built into the font files.

**Comment by Mailaender** [comment]
The mod chooser was removed. https://github.com/OpenRA/OpenRA/issues/12554
