### ISSUE TITLE
AI fires on stealth unit even when cloaked

### ISSUE THREAD

**Issue by foulowl** [OpenRA/OpenRA#5018]
Reproduce by creating a stealth tank, set stance to holdfire, then drive it into the enemy's base. Unsure if base defenses are supposed to cause the stealth tank to decloak, but even without base defenses, the enemy AI will build some units, then start firing on the exact location of the stealth tank. 

Same thing for other units that have received a stealth crate as well.

**Comment by obrakmann** [comment]
In TD all infantry units will detect cloaked units that are directly next to them. In RA, some units and buildings have the ability to detect stealth units in a wider area. But generally, this has been fixed as part of #7097.
