### ISSUE TITLE
Mechanic and medic don't auto-heal while guarding

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#5028]
If a mechanic or medic is given the order to guard a unit using the d key, they no longer auto-heal units around them. This would be the whole purpose of using guard move for mechanics and medics. They would heal units in the middle of battle and it would be easier to manage them.

**Comment by Snurre86** [comment]
When the mechanic and medic is on guard duty the game should ignore him like it does with the ore miner when making a selection box.

**Comment by obrakmann** [comment]
This has been fixed in #8768
