### ISSUE TITLE
Tech building ideas

### ISSUE THREAD

**Issue by dan9550** [OpenRA/OpenRA#5030]
Some ideas:

* When you have captured a tech hospital your inf should have a little icon in the selection box to indicate they are being healed by the hospital (i swear this was in ra2 couldn't find a picture)

* Capturable Biolab makes inf immune to tiberium perhaps? not even sure what the biolab does at the moment couldn't find it in the YAML either.

**Comment by Mailaender** [comment]
> Capturable Biolab makes inf immune to tiberium perhaps? not even sure what the biolab does at the moment couldn't find it in the YAML either.

Draw a hazmat suit icon and create a new upgrade that can be purchased from there. Code is in place since we merged https://github.com/OpenRA/OpenRA/pull/8114.

**Comment by GraionDilach** [comment]
How would it work? Neither Armor, neither TargetTypes are upgradable (this is a good example why I want TargetType upgrading would look like most others, not via #8339's UpgradedTargetTypes).

I do agree something like
```
^Infantry
TargetableUnit:
		TargetTypes: TiberiumDamage
		UpgradeTypes: biolab
		UpgradeMaxEnabledLevel: 0
```

would be nice but we cannot have such.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/wiki/Traits-(playtest)#poisonedbytiberium is upgradeable.

**Comment by GraionDilach** [comment]
Oh, I overlooked that it has a separate trait. -_-

**Comment by pchote** [comment]
:+1: to removing the buildable dinos and adding a tib-heal upgrade.
