### ISSUE TITLE
Replay Viewer : switch view to teammate base

### ISSUE THREAD

**Issue by xan2622** [OpenRA/OpenRA#5047]
Currently in the Replay Viewer, if you watch a 1v1, you can switch views after selecting Player1 then EasyAI. The view moves from one base to the other one.

But if you play a 2v1 (for example), the view can't be switched from Player1 to Player2 (if they are in the same team). 
##

**Comment by abcdefg30** [comment]
Switching view doesn't appear to change the viewport any more, so this is no longer an issue.
