### ISSUE TITLE
Ingame Map Editor : Reset Map

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#5067]
![screenshot001](https://cloud.githubusercontent.com/assets/1732773/2625086/d944f9c0-bd7a-11e3-9121-8f91102eb81c.png)

**Comment by pchote** [comment]
This duplicates the existing new-map functionality, so isn't needed.

**Comment by x-a-n-a-x** [comment]
Not really... Creating a new map and resetting the current one are different things

**Comment by Mailaender** [comment]
Implementation wise it is identical. Clicking "New" in MS Paint will also not erase every pixel, but instead just open a new blank canvas. However we may want to avoid too many buttons as we don't have the usual UI widgets such as toolbars and menus lines where you would expect such features and can't run into space problems.
