### ISSUE TITLE
Add support for using 8-bit PNGs instead of SHPs

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#5075]
All this converting back and forth between various shp/tmp file formats and palettes is quite annoying.

It would be great if there was the option to use 8-bit PNGs just like SHPs, preferably with the optional possibility to use the PNGs' own palette.

As for how to solve multiple frames, I have no idea whether [ab]using MNG, APNG or even simply 1 massive PNG containing all frames (and then telling the engine per yaml what dimensions each frame should have) is the best solution. The latter would have the highest compatibility with image editing programs, though.

Outside the legacy mods this would make things so much easier, IMO. OS SHP Builder still has a buggy(shp TS)/broken(shp TD) saving mechanism, and converting back and forth between PNG and SHP/TMP via XCC or command line is annoying as heck. To be able to just drop your edited PNG with its own palette into the bits folder and be done with it would be so much more convenient, and save modders tons of time.
##

**Comment by yaaaaa** [comment]
I think you may use pink colors of palette to playercolors, and transparent color of palette to transparent background.
