### ISSUE TITLE
Units spawn in top left corner of map, revealing shroud

### ISSUE THREAD

**Issue by cjshmyr** [OpenRA/OpenRA#5076]
Map cordon size seems to have something to do with the reveal. Can only reproduce this on maps with 1x1 cordon (and probably 2x2 / 3x3)

![capture](https://cloud.githubusercontent.com/assets/566742/2638901/fe6bd140-beb7-11e3-8632-6d00e5d5ea6f.PNG)

To reproduce:
- Pick RA map Seaside 2 or Chaos Canyon (126x126 with 1x1 cordons)
- Build a barracks anywhere
- Move camera to top left corner of the map
- Build E1/DOG and notice the fog will vanish for a brief second, and shroud will be gone. DOG reveals a bit more.

**Comment by Mailaender** [comment]
It has returned.

**Comment by Mailaender** [comment]
Seems to be gone now.

**Comment by pchote** [comment]
o_O
