### ISSUE TITLE
CNC orcas are underpowered against what they should be powerful towards

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#5080]
Orcas should be anti tank, not anti infantry. Currently, they are better vs infantry than tanks. It takes a long time for three orcas to destroy a medium tank.

**Comment by pchote** [comment]
There have been a few releases with balance changes since this ticket was created, and no further discussion about this aspect of the balance.

**Comment by Unit158** [comment]
This was actually fixed by a patch that psydev and I made last April.
