### ISSUE TITLE
Veterancy for non-combat units.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#5095]
Non-combat units should be able to gain veterancy in a way besides crates. Harvesters gain rank for ore deposited at a refinery, engineers for buildings captured, mechanics for repairs done etc.

Maybe a full rank ore truck can carry 25% more ore!? I don't know use your imagination!
##

**Comment by nerai** [comment]
Should any unit be able to gain veterancy by doing only automated tasks? It seems wrong to me, considering the game is intended to be micro-heavy in things such as this?

**Comment by penev92** [comment]
No. Otherwise we might as well give tanks veterancy over time when idle in your base "because they are defending it".
Veterancy for non-combat units only makes sense for engineers and medics, when they are performing their respective jobs.

**Comment by GraionDilach** [comment]
Harvesters could gain rank by crushing infantry and getting better armor for it.

**Comment by nerai** [comment]
Pardon my ignorance, but wasn't GraionDildach's suggestion implemented in the original C&C? Though I think not in RA yet.

**Comment by GraionDilach** [comment]
Only TS and RA2 had experience (TS also had a veterancy factor of 5, means a TS harv had to crush 7000$ worth of infantry to actually gain a level) which resulted with the practical usecase of none.

Ah, and in TS/RA2 the veterancy crate granted the veterancy level all the time without checking if the unit can gain experience at all.

**Comment by epicelite** [comment]
@penev92 Collecting resources is doing a job, attack units can gain rank by automatically shooting at whatever. Why can't a harvester get rank for doing its job, funding your army?

**Comment by MustaphaTR** [comment]
> Ah, and in TS/RA2 the veterancy crate granted the veterancy level all the time without checking if the unit can gain experience at all.

Not sure about TS, but RA2 checks units Trainable= vaule and current veterancy for veterancy crate powerup. If unit isn't trainable or alrealy elite, veterancy bonus turns into money. If a trainable unit gets a veterancy crate powerup, non-trainable units also doesn't get veterancy.

**Comment by GraionDilach** [comment]
It only checks the one unit which picked the crate up, not the ones which were around the crate by then.

**Comment by Smittytron** [comment]
We've been moving away from allowing non-combat units to receive veterancy. I'd say this was superseded by #14125.
