### ISSUE TITLE
Give engineers attack stance to automatically capture buildings

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#5101]
If there are lots of buildings to capture, there is no way to make engineers capture them automatically. There could be a stance where they automatically capture neutral and/or enemy buildings within a radius. This is practically necessary for specialized maps such as "Great Oily Divide" where there are tons of oil derricks that need to be captured.
##

**Comment by tovl** [comment]
This was never actually addressed. Letting engineers actually use stances seems like a reasonable request.

**Comment by Smittytron** [comment]
After discussion in Discord, I'm closing this as wontfix. (This was also labeled wontfix in #15661) 
There was sentiment against the game playing itself, but also this wouldn't fit with consumable engineers.
