### ISSUE TITLE
Check file path for map if previous map hash could not be matched

### ISSUE THREAD

**Issue by cjshmyr** [OpenRA/OpenRA#5111]
When developing a map (particularly the yaml, not lua) the map's hash changes, so the map needs to be continually found in the map chooser after each edit.

When setting the lobby's initial map, the game checks if the previously played map still exists (by matching the hash). If there's no match, we could also check if the file path to the map still exists, and if so then set that as the initial map.

edit: clarity

**Comment by abcdefg30** [comment]
This has been solved.
