### ISSUE TITLE
can't pick up crate near bridge

### ISSUE THREAD

**Issue by psydev** [OpenRA/OpenRA#5131]
Infantry couldn't pick up crate near bridge. I thought I saw another passing infantryman walk right over it but not pick it up.

When I click on that tile to pick it up, nothing happens.

Screenshot:
http://imgur.com/J4FDlAi
##

**Comment by FrameLimiter** [comment]
I 'm pretty sure this issue has been fixed. Regarding the screenshot above; that cell is now accessible.

**Comment by pchote** [comment]
Sounds plausible.  This can always be reopened if it turns out to not be fixed.
