### ISSUE TITLE
Ingame Map Editor: The rectangle selection doesn't surround buildings completely

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#5173]
The rectangle selection for the "Iron Curtain building" is not surrounding it completely. 

![screenshot001](https://cloud.githubusercontent.com/assets/1732773/2758245/d6a4bf5a-c98e-11e3-8f44-3607713d5414.png)

**Comment by Mailaender** [comment]
Got this under control now for everything that does not use `WithIdleOverlay`.

**Comment by Mailaender** [comment]
Finally fixed completely in https://github.com/OpenRA/OpenRA/pull/7457.
