### ISSUE TITLE
Ingame Map Editor: Buildings are not placed correctly on the ground

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#5174]
Buildings are not placed correctly on the ground.

![screenshot003](https://cloud.githubusercontent.com/assets/1732773/2758634/e681f802-c993-11e3-9f6c-eeeac1149e9a.png)

**Comment by Mailaender** [comment]
Finally resolved this. https://github.com/OpenRA/OpenRA/issues/4496 is now taking building dimensions into account.

> This is essentially the same problem as #5173.

Actually not. 

> There's no way that it's going to be perfect when it's merged.

Except when @pchote is in command.
