### ISSUE TITLE
Ingame Map Editor: Actor/Tile selection bug

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#5175]
There is an Actor/Tile selection bug in Mailaender's ingame map editor.

1. Select an actor
2. use it on the ground
3. right click on an empty area
4. try to left click again to "draw" the tile (it won't work)
5. try to reselect the same actor in the list to "draw" the tile (it won't work)

**Comment by Mailaender** [comment]
Fixed it in the latest revision of https://github.com/OpenRA/OpenRA/pull/4496.
