### ISSUE TITLE
Ingame Map Editor : Add tooltips over actors and tiles

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#5176]
I think there should be tooltips when the cursor hovers an actor or tile.
This will help recognize actors and tiles (some of them can look almost the same).

![screenshot002](https://cloud.githubusercontent.com/assets/1732773/2761736/5088e1e2-c9e0-11e3-8458-d2dbb569b62a.png)

**Comment by Mailaender** [comment]
@ScottNZ's `GetTooltipText` introduced in https://github.com/OpenRA/OpenRA/pull/7096 made this very simple. Updated https://github.com/OpenRA/OpenRA/pull/4496 with tooltips working for tiles, resources and actors.
