### ISSUE TITLE
Building is not placed if a unit moves onto the tiles at the last moment

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#5201]
1) Tiles are all white, I click to place the building
2) After I click to place it but before it is built, a unit moves onto one of the tiles where the building should stand.
3) Building is not built. I have to click the build palette and choose it again to place it

No tiles were red before placing the building and there was no "unable to build" warning sound.

This is easily reproducible by having a building ready and placing it on an area where a unit is just about to move into.

It seems like there is a delay between placing a building and the time it is actually built. If, during this time, a unit moves onto the tiles of the building then nothing happens.

**Comment by pchote** [comment]
I'm going to close this since there's nothing that can be done here.
