### ISSUE TITLE
Turreted units wait until they are in range of target before aiming turrets

### ISSUE THREAD

**Issue by psydev** [OpenRA/OpenRA#5203]
It would make more sense if a turreted unit would rotate its turret around to face the target it is chasing as soon as it gets the order to attack, as opposed to waiting until it drives into range, and only then beginning to slowly rotate its turret to aim.

**Comment by reaperrr** [comment]
@OpenRA/engine-hackers 
I'm actually surprised that nobody has bothered to fix this yet. Not only does it look a bit weird, it also puts turreted units at a disadvantage if the target is positioned on the opposite direction of the current turret facing, and last but not least, facing the target constantly was also how the original games did it.

The main problem is that turret facings are only updated via `Attack*.CanAttack`, which doesn't tick constantly and returns `false` if weapons are currently reloading. 
Instead, turrets should face the target as long as `IsAttacking` is `true`.

**Comment by Mailaender** [comment]
I wonder if this is a regressions, because I remember turrets as in gun turrets actively seeking and pointing towards enemies that they even can be used as a detection device. That behavior might have existed only long ago though.
