### ISSUE TITLE
MLRS turret keeps "twitching" between up and down position, when tracking a moving target

### ISSUE THREAD

**Issue by psydev** [OpenRA/OpenRA#5204]
Not sure why this happens, exactly. Sometimes it's when the MLRS is rotating to track the moving target, but only sometimes. 

Better behaviour would be for it to stay up until it has reason to put it down (receives new orders to move).
##

**Comment by Smittytron** [comment]
Can the idea behind #14393 be applied here?

**Comment by GraionDilach** [comment]
Notreally, because this issue isn't caused by lack of facings for a state.

**Comment by Arular101** [comment]
There is maybe a possibility to fix it by only raising the rockets when it is aiming, using the same conditions system. I'll investigate it.

**Comment by Arular101** [comment]
@Smittytron, I've it working that it only raises the turret when it is shooting. After all the rockets are launched, the turret is down again. There is no twitching anymore. Is this something that you would like for TD? Then I can file a PR for that.

**Comment by Smittytron** [comment]
>  After all the rockets are launched, the turret is down again. There is no twitching anymore. Is this something that you would like for TD? Then I can file a PR for that.

That sounds like the desired behavior. If we can get both the V2 and MRLS fixed that'll be a pretty big polish win for the next release.
