### ISSUE TITLE
Make blinking effect on window when player joins?

### ISSUE THREAD

**Issue by VagueVigor** [OpenRA/OpenRA#5229]
Usually when i host, i dont stare the game room constantly. This can cause people to wait for nothing since i am not aware of the situation.

It would be useful if the window started to blink (in the taskbar) when someone joins or sends message in the game room. But it should do that only when the window isnt active or visible.

Currently the only way to know if anyone joined my game, is to turn up the volume. But i also like listening music, so it doesnt work very well.

**Comment by pchote** [comment]
I believe that we don't have the platform support to do this, and even if we did I can imagine many players getting quite annoyed by this feature.  I don't see this as being implementable for those two reasons, so closing.
