### ISSUE TITLE
Ingame Map Editor: Movable actors

### ISSUE THREAD

**Issue by xan2622** [OpenRA/OpenRA#5241]
After seeing Mailaender's latest comment (about the ingame map editor): https://github.com/OpenRA/OpenRA/issues/3377#issuecomment-42101971 that made me think : "we should really be able to move all these actors".

That's why I hope that you'll consider adding a toolbar with a few buttons ; and one of them could let the player move actors.

![2cbcb9f4-d2b0-11e3-88ab-9fc0b8d73092](https://cloud.githubusercontent.com/assets/1732773/2870342/68354960-d2bf-11e3-940a-b28b676b32dd.png)

**Comment by Mailaender** [comment]
I implemented actors using cut and paste without a toolbar button. Simply left click on an actor and place it somewhere else. This is indeed quite handy. Check the latest revision of #4496.

**Comment by Mailaender** [comment]
Sadly it didn't make it into https://github.com/OpenRA/OpenRA/issues/8065. =(

**Comment by pchote** [comment]
This can now be done using copy/paste.

**Comment by x-a-n-a-x** [comment]
copy != move
Couldn't a "move/paste" button be added in the map editor ?
