### ISSUE TITLE
Shroud outside map borders should have a different color

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#5249]
It is difficult to tell where the map edges are without scouting. I think it would be better if the shroud that is outside the map borders had a different color, such as dark gray instead of black.

**Comment by pchote** [comment]
The changes over the last several months to dramatically improve the shroud performance and support TS/RA2 make this unfeasible to implement.  The edge of the map, edges of the rendered shroud, and scissor rectangle do not line up cleanly in the way implied/requested in the mockups above.

**Comment by bairesearch** [comment]
I would recommend always (only if possible; ie on sufficiently large maps) preventing the user from centring their view on a position which would result in them seeing content (shroud) outside of the map. This would require readjusting the view position during zoom-out, if the user is currently zoomed in on a position that is bordering the edge of the map.
