### ISSUE TITLE
Allow 3 infantry in a pillbox at one time?

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#5283]
What if we do this? Might make them a bit more useful late game.

**Comment by MicroJOo** [comment]
because this is a idea to improve the pillbox ... and make it more usefull late game for the balance ... i would say #7794 is a different fix , but definitely more gently

**Comment by Phrohdoh** [comment]
Pillboxes have been buffed since this ticket was opened and last discussed and nothing more has come of this, so I am closing it.
