### ISSUE TITLE
A.I Dividing by zero in Skirmish Game

### ISSUE THREAD

**Issue by Adelric-115** [OpenRA/OpenRA#5284]
Hello guys!

Just posting here to try and grab some support for a mod I'm working on, while testing the A.I in-game, every single darn time, the A.I places any structure down on the map, the game crashes to desktop. It only happens with the "Allies" Faction, which has been heavily edited as part of my mod, everything works fine for a player, the problem is purely A.I

![exception 2](https://cloud.githubusercontent.com/assets/7146407/2938489/970fe880-d90e-11e3-8941-61480d455c03.png)

There is the log, if possible. I'd greatly appreciate a timely reply, as I'm working within a development cycle here and wouldn't like to be held off for very long

**Comment by RoosterDragon** [comment]
Fixed by #7715.
