### ISSUE TITLE
Build-in screenshot capturing

### ISSUE THREAD

**Issue by pavlos256** [OpenRA/OpenRA#5317]
Add a shortcut key to take screenshots (Print screen?).

The screenshot file names could be similar replay filenames (date/time) and could be stored in a directory structure similar to replays (`Replays/<modname>/<version>/*`).

**Comment by barrystaes** [comment]
This might need polishing. I have issues with this:

- Pressed CTRL+P in mainmenu but no indication whether screenshot actually was taken.
- Cant see/edit shortcut from settings menu. (it appeared this option was not available)
- Dont know where the screenshots are saved.

Tested on playtest 20150329.
I just wanted to report a render bug yesterday, but PrtScrn gave a black image and ci could not find a screencapture option in OpenRA.

**Comment by penev92** [comment]
@barrystaes Please refer to my comment on #7624 about the bug.
