### ISSUE TITLE
make.ps1 occasionally fails to exit after building

### ISSUE THREAD

**Issue by ScottNZ** [OpenRA/OpenRA#5363]
It will occasionally pause indefinitely after invoking MSBuild and just sit there, as if MSBuild isn't exiting after the build is complete, or the waiting code is broken.
##

**Comment by matjaeck** [comment]
@ScottNZ do you know if this is still an issue?

**Comment by abcdefg30** [comment]
I don't remember seeing something like this recently. Can reopen if you can reproduce the issue.
