### ISSUE TITLE
Expose Tech Level to End User via GUI

### ISSUE THREAD

**Issue by foulowl** [OpenRA/OpenRA#5416]
WolfGaming did some work allowing tech levels as a feature:
https://github.com/OpenRA/OpenRA/pull/5280
https://github.com/OpenRA/OpenRA/issues/4956
Now I would like to see these tech levels exposed to the end user via the GUI.
- [x] Tiberian Dawn https://github.com/OpenRA/OpenRA/pull/5833
- [x] Red Alert #5901
- [x] Dune 2000 https://github.com/OpenRA/OpenRA/pull/5898
- [ ] Tiberian Sun
##

**Comment by reaperrr** [comment]
Still missing in TS, adding to Future milestone so we don't lose track of this.

**Comment by pchote** [comment]
#11176 and followups will fix this as a side-effect.

**Comment by reaperrr** [comment]
I think we should implement TS tech levels before we ship the first alpha, added to milestone.

**Comment by MustaphaTR** [comment]
I'm working on TS Tech Levels.
