### ISSUE TITLE
"Cannot deploy here" sound is misleading.

### ISSUE THREAD

**Issue by phrohdoh** [OpenRA/OpenRA#5450]
When attempting to placing a structure in an invalid location the user gets auditory feedback of
`Cannot deploy here.`
We should use (possibly have someone piece together) something closer to `Cannot build here.`
##

**Comment by kaneCVR** [comment]
Changing the "Cannot deploy here" notification will further detract from the original game. I for one am against it.

**Comment by TheRaffy** [comment]
If somebody explains me where I can find the sounds ill do the sound.

**Comment by Smittytron** [comment]
Closing as part of our Discord github-cleanup initiative.
