### ISSUE TITLE
Add a button to locate active or primary production buildings

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#5486]
Under each production tab there could be a button which says locate active/primary building and when pressed, that building would be centered on the screen and selected. It would be useful when there are lots of bases scattered around the map.
##

**Comment by dragunoff** [comment]
Double tapping seems like an intuitive way to perform that action, however I can see two issues:
1) accidental activation moving your camera away
2) players spamming the building/defense hotkey a few seconds before a construction is complete to get it on their cursor as quickly as possible (I do it and I've seen it on streams)

**Comment by dragunoff** [comment]
I'd like to suggest a unified solution to both this and #15842 (rally point hotkey). The idea is to have a hotkey that selects the production facility associated with the active production tab. Double tapping would center the viewport on it. And when the facility is selected naturally a rally point can be placed.

**Comment by MustaphaTR** [comment]
Your point 3 above doesn't really make sense, if there is multiple queue, there is no primary building.

**Comment by dragunoff** [comment]
> 
> 
> Your point 3 above doesn't really make sense, if there is multiple queue, there is no primary building.

Each building in a multi-queue production has its own tab so the hotkey would select the active one.
