### ISSUE TITLE
Port missions to the new Lua API

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#5490]
The new https://github.com/OpenRA/OpenRA/wiki/Lua-API has landed in https://github.com/OpenRA/OpenRA/pull/5190. Time to update the maps and enhance the standard library. Some shared deficiencies of both old and new Lua API:

- [x] #4400 Missing cell triggers
- [x] #4541 Lua integration of objectives panel 

Red Alert
------------

| Mission                          | Basis        | Assignee       | PR      | Status
|-------------------------------|--------------|------------------|----------|---------|
| allies-01-classic             | old Lua     | @Mailaender | #6377 | done |
| allies-02-classic             | old Lua     | @Mailaender | #6379 | done |
| ~~allies01~~                  | legacy C# |                       |            | redundant |
| allies02 (co-op)             | legacy C# | @obrakmann | #11316 | done |
| allies03 (co-op)             | legacy C# | @Mailaender | #11679 | done |
| allies04 (co-op)             | legacy C# | @Mailaender |#11702 | done |
| desert-shellmap             | old Lua    | @pchote        | #5190 | done  |
| fort-lonestar                   | legacy C# | @Mailaender | #5469 | done |
| intervention                   | old Lua     | @obrakmann | #6762 | done  |
| monster-tank-madness | legacy C# | @abcdefg30  | #6552 | done |
| soviet01-classic            | legacy C# | @Mailaender | #6796 | done |
| survival01                     | legacy C# |  @abcdefg30 | #6934 | done |
| survival02                     | legacy C# |  @abcdefg30 | #7164 | done |

Tiberian Dawn
------------------

| Mission      | Basis        | Assignee       | PR      | Status
|---------------|--------------|------------------|----------|---------|
| gdi01         | old Lua     | @Mailaender | #5782 | done |
| gdi02         | old Lua     | @obrakmann | #6324 | done |
| gdi03         | old Lua     | @Mailaender | #6795 | done |
| gdi04a       | old Lua     | @obrakmann | #6762 |  done  |
| gdi04b       | old Lua     | @obrakmann | #6762 |  done  |
| gdi04c       | old Lua     | @obrakmann | #6325 | done |
| nod01       | old Lua     | @obrakmann | #6326 | done |
| nod03a     | old Lua     | @obrakmann | #6327 | done |
| nod03b     | old Lua     | @obrakmann | #6328 | done |
| shellmap    | old Lua     | @pchote       | #5190 | done |

**Comment by Mailaender** [comment]
We can add @ScottNZ's take on allies-01 as an additional difficulty like @abcdefg30 did in https://github.com/OpenRA/OpenRA/pull/8359.

**Comment by obrakmann** [comment]
We're finally done with this \o/. Only took more than two years ;)

**Comment by abcdefg30** [comment]
🎉 🎉 Good job everyone.
