### ISSUE TITLE
Concrete walls cant be sold beside buildings

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#5552]
If you have a barrier behind a building you have to sell the building before you can sell the barrier.
![concrete wall can t be sold 1](https://cloud.githubusercontent.com/assets/7798635/3184023/b4831b4a-ec7c-11e3-88b2-731a83efd991.png)

**Comment by Snurre86** [comment]
Says in the tool tip that I sell the Flame tower but sells the Repair pad.
![openra game_2016_11_21_07_28_54_206](https://cloud.githubusercontent.com/assets/7798635/20472752/555c6814-afbc-11e6-9b91-67bc2962bf35.png)
![openra game_2016_11_21_07_28_56_546](https://cloud.githubusercontent.com/assets/7798635/20472761/5eceede0-afbc-11e6-9b86-f87de50ea993.png)

**Comment by pchote** [comment]
I'm not sure I would classify "identifying and fixing bugs with our selection priority engine code" as Easy...

**Comment by abcdefg30** [comment]
I thought that this is more an issue with the actor's bounds layout. But actually, as the tooltip is shown this could be worse, yeah.

**Comment by Snurre86** [comment]
Still happens but when you see both health bars you are always selling the service depot.
