### ISSUE TITLE
Refund information missing [$5]

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#5563]
There should be a way to see how much you get for selling a building.

How much do I get from selling this structure?
![Illustration with tooltip](https://cloud.githubusercontent.com/assets/7798635/3198816/473c87ea-ed5f-11e3-8d60-2591363a8885.png)

**Comment by obrakmann** [comment]
Fixed by #7595. Collect your beer money, @WolfGaming!

**Comment by Snurre86** [comment]
Fixed in (playtest 2015-04-18)
![2015-04-22 17_58_54-greenshot](https://cloud.githubusercontent.com/assets/7798635/7279180/59b7607c-e91a-11e4-8685-ec9db59545ed.png)

**Comment by WolfGaming** [comment]
Ohh yeah there was a bounty in this.

Totally forgot.
