### ISSUE TITLE
Sniper Unit: Adding standing firing frames & Voice

### ISSUE THREAD

**Issue by NukemBro** [OpenRA/OpenRA#5578]
Using the flame-trooper as a template to create the sniper unit, the "standing" firing frames were never created for the sniper unit since it was established that the sniper would always "prone" fire. Now, this isn't the case, as the Sniper unit fires standing up, but the standing firing frames need to be added. 

Also, the sniper unit currently uses GenericVoice, maybe it would be a good idea to distinguish selecting/ordering a sniper unit with a different voice than that of the typical e1,e3, etc.

Edit: Firing frames are added, also added in some "reloading" frames for the sniper in between shots.

![comparison](https://cloud.githubusercontent.com/assets/1801219/3210144/7b21b3b8-eea5-11e3-8a6b-ed6c7211d930.png)
##

**Comment by MicroJOo** [comment]
this can be closed

**Comment by penev92** [comment]
Not really. While the snipers are now unbuildable, they are still in the game and any number of custom maps (or mods) can use them.

**Comment by pchote** [comment]
I think it would be better to remove them completely: custom maps can add their own artwork (either fixed or not) back if they want snipers.

**Comment by PunkPun** [comment]
> I think it would be better to remove them completely: custom maps can add their own artwork (either fixed or not) back if they want snipers.

I completely agree, this issue should be closed and snipers should no longer be a part of openra

**Comment by Leo512bit** [comment]
Can't this at least be closed? Unless if I'm missing something the frames are now there.
