### ISSUE TITLE
Configurable map scrolling buttons

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#5587]
I think the "Middel-Mouse Scrolling" option should be removed and replaced with a configurable map scrolling option. Some games use the right mouse button for scrolling, my personal favorite but other players may have other preferences that are not met with just a use or don't use option.
![untitled](https://cloud.githubusercontent.com/assets/7798635/3212077/0420d804-ef43-11e3-92a2-76958bb7f894.png)

**Comment by penev92** [comment]
I'm all *for* right-click scrolling as it is ... everywhere. The middle-click scrolling is slow and uncomfortable. Also Edge scrolling is always either too slow or too imprecise.

**Comment by penev92** [comment]
I guess this is pretty much superseded by #9399.
