### ISSUE TITLE
Add support for using 32-bit RGBA sprites instead of SHPs

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#5589]
PNG would be the most sensible choice, I think.

Similar to #5075, but for hi-color/true color.
##

**Comment by GraionDilach** [comment]
There is no actual need for this one.

The 256-colored palette limit can be worked around with custom palettes - and basically all overlays can have their own palette. Also, there's no palette limit in the engine - I already passed the 256 palette limit which was supposed to break the game but that hasn't happened yet.

OpenRA doesn't force any asset to work on a specific palette and - at the moment - custom 32-bit palette loaders are already functional, so you can have palettes with differenjt alpha values per slot. IOW, OpenRA is able and should follow Sudden Strike here - which used 32bit JASC palettes for alpha channel.

**Comment by reaperrr** [comment]
Closing due to ^.
