### ISSUE TITLE
Smaller minimaps on map list?

### ISSUE THREAD

**Issue by VagueVigor** [OpenRA/OpenRA#5669]
It would be nice to have some option to change minimaps size in the map list, so its easier to browse through the list.

Example:
![](http://i5.minus.com/i66ZMBKG2vtXF.png)

This almost doubles the minimaps on one page and you can still see the maps as good as before.

I also removed useless information such as "large / small / huge" etc, and creator and map type; i think those could be shown only when you sort map by those options.

If you want to play large or small map, you probably sort the maps by size first. and so on.

Just so you can see the difference, before:
![](http://i3.minus.com/ibz7LtqE1zHBrP.png)

**Comment by pchote** [comment]
This was resolved by the new multiplayer UI rework.
