### ISSUE TITLE
C4 on airfield/hpad won't destroy landed airplanes

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#5671]
Before planting C4:
![airplainbug1](https://cloud.githubusercontent.com/assets/7704140/3341484/e1b30004-f888-11e3-93fb-797d382eae33.png)
After:
![airplainbug2](https://cloud.githubusercontent.com/assets/7704140/3341485/e32e5640-f888-11e3-9764-2efa173637e2.png)

**Comment by obrakmann** [comment]
`Reservable` can't really be used for this, since it doesn't know when planes actually land. It would be weird for planes to drop out of the sky just because the reserved airfield got blown up.

Anyway, this was fixed by #11620, which makes aircraft take off if their host dies.
