### ISSUE TITLE
Installation removed all mods in the mods folder, including non-standard ones

### ISSUE THREAD

**Issue by UberWaffe** [OpenRA/OpenRA#5684]
I just went from playtest 20140602 to release 20140608 and noticed that it had deleted all mods from the mods folder, and not just those included in the installation.

It would be nice if there was a warning that this will occur, or (even better) it only deleted the standard mods from the mods folder.

**Comment by atlimit8** [comment]
Then closing #8992 should close this one.

**Comment by pchote** [comment]
This was resolved by allowing mods to be loaded from the support directory.
