### ISSUE TITLE
Audio Device info to short

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#5723]
Look at my options in the picture do you know what they are?
![openra game_2014_06_23_10_09_29_346](https://cloud.githubusercontent.com/assets/7798635/3355107/6dcb2022-faae-11e3-96b3-8864e02ba564.png)

**Comment by Snurre86** [comment]
Release-20151224
![untitled323324](https://cloud.githubusercontent.com/assets/7798635/12224331/f995744c-b7ed-11e5-95ee-1d1101159a50.png)

**Comment by pchote** [comment]
Making this use our now-standard text trunction code (which truncates at the end) will reduce code duplication and fix this as a side-effect.
