### ISSUE TITLE
Show map size in lobby

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#5743]
Like 100x100.

**Comment by deniz1a** [comment]
The map selector shows map sizes, so I don't think this is necessary anymore. Were they already being shown when I opened this issue? Anyway, I'm closing this.

**Comment by Unit158** [comment]
This hasn't been resolved yet and should be reopened.

**Comment by pchote** [comment]
I'm not convinced we want this in the main lobby view.

**Comment by penev92** [comment]
Now any player can open the map browser and see the map size there, so I think we're done here.
