### ISSUE TITLE
Allied helipad - new unit causes existing helicopter to disappear

### ISSUE THREAD

**Issue by htowens** [OpenRA/OpenRA#5820]
I found this bug by sending an existing helicopter (hind) to be serviced on the helipad, while another was under construction. The helicopter was still on the pad at the point of completion of the new helicopter; when the construction was completed, only 1 unit left the helipad.

This was particularly noticeable as the existing unit was team 0 - after the new unit was created, team 0 was no longer assigned.

This looks related to the new behaviour of the allied helipad (previously it would have said "unable to build more" while another unit was on the pad, particularly if a queue was in place, but now they leave the pad automatically).

**Comment by MicroJOo** [comment]
i cant confirm this bug ....

**Comment by pchote** [comment]
Not reproducible on recent releases, so closing.
