### ISSUE TITLE
Rocket infantry stays out of firing range

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#5841]
I noticed that when you order a TD rocket trooper to fire on te ground outside of its weapon range, it will only move closer but not start firing. Looks like it stays about 1 cell out of weapon range.
##

**Comment by obrakmann** [comment]
I can't reproduce this on current bleed. @reaperrr, can you please check again?

**Comment by reaperrr** [comment]
Can't reproduce it anymore and haven't noticed it recently, either.

**Comment by reaperrr** [comment]
Actually just witnessed this again, still not fixed.

**Comment by reaperrr** [comment]
![example1](https://cloud.githubusercontent.com/assets/2857877/10865081/bdb4ce34-8000-11e5-9a5c-c2b4a0c2db15.png)

The bazooka inf in the lower-right corner was ordered to shoot at the same cell as the rest, but neither shoots nor moves closer.

**Comment by RoosterDragon** [comment]
@reaperrr has diagnosed the cause of the problem - https://github.com/OpenRA/OpenRA/pull/9802#issuecomment-152755390. If the unit is in a subcell that is too far away it is still out of range - however `MoveWithinRange` doesn't care because it's still on a cell that's within range so it doesn't move it any closer. If the unit was on a closer subcell it would be ok.

**Comment by reaperrr** [comment]
It would probably help if we had something like 'FindSubCellsInAnnulus'.

**Comment by GraionDilach** [comment]
I am worried if the random targetoffsets will increase the exposition of this one though.

**Comment by reaperrr** [comment]
Probably, but it's something we should have fixed sooner anyway. Moving to Next milestone.

**Comment by pchote** [comment]
We already used targetablepositions for range calculations, and I wouldn't expect the small position tweaks to change things here *that* much.
