### ISSUE TITLE
Units/Vehicles footprints

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#5858]
IRC discussion:
http://logs.ihptru.net/?year=2014&month=01&day=20#22:34:42

![footprints](https://cloud.githubusercontent.com/assets/1732773/3492559/17f1cf8a-05ac-11e4-950e-16c0aaecca3b.png)

It might make sense to add footprints for SNOW or DESERT maps.

**Comment by x-a-n-a-x** [comment]
ghost: are these images mock-ups or ingame screenshots ? (I am talking about the one on the left).
Have you made SHPs for these footprints? Is there a branch somewhere that we could test?

**Comment by Bynnar18** [comment]
This probably could be adapted if implemented for wake animations like TS and RA2 have for movement on water.

**Comment by penev92** [comment]
OK, so we will need this at some point.

**Comment by Phrohdoh** [comment]
@Bynnar18 good point wrt the amphibious APC, added the TS label.

**Comment by Micr0Bit** [comment]
#11112
