### ISSUE TITLE
Missing map editor tiles for D2k missions

### ISSUE THREAD

**Issue by 54x** [OpenRA/OpenRA#5875]
So, I started manually reproducing maps for D2k in ORA format, and noticed that even in the first map there's some major things missing. I concreted the tiles I couldn't find for reference...

![a1v1 missing tiles](https://cloud.githubusercontent.com/assets/3319884/3503328/9018d40e-062e-11e4-8829-0cba3a00ca7c.png)

1 - There should be a 3 wide 1 tall crater here, it's pretty distinctive and definitely not in the available tiles.

2 - We don't seem to be able to place dense spice in the editor.

3 - This may need to be scripted by lua eventually, however a worm should spawn here.

4 - We're missing the corner graphic for the smooth rock-sand transition here, where the southwest corner is rock and all the other corners are sand. This is also the bottom-most concrete tile, but I forgot to highlight that one, too.

5 - Essentially the same issue as 4, but this time it's the corner where the northwest is rock and all other corners are sand. I've checked and the two other corners of this type are usable, and all four corners with three corners rock and one corner sand show up fine as well, so it's just these two one-tile corners that are missing.

Unlabelled - For the other two unlabelled concrete tiles, there's a 1-square rock graphic with an odd smudge that goes here, but I suspect it's somewhere in a larger formation in the map editor and I haven't found it to cut it up.

Everything but (3) should definitely be fixed for multiplayer maps anyway, so even if an import is worked out for D2k missions, the other "missing tiles" will still need resolving.

For comparison, here's what it should look like completed, including units and structures:

![a1v1 complete](https://cloud.githubusercontent.com/assets/3319884/3503397/22d6a086-0630-11e4-92bf-4291c6d99e6d.png)

**Comment by Mailaender** [comment]
Closing as https://github.com/OpenRA/OpenRA/issues/7147 and https://github.com/OpenRA/OpenRA/pull/7135 have been merged.

**Comment by 54x** [comment]
The importer map looks great, and will just need units placed for it to work out. :)

The shroud issue is just related to how OpenRA renders the edges of maps, and is probably its own issue if people want the edge of the map to slice smoothly like it did in the original Westwood games.

**Comment by penev92** [comment]
The map importer now imports maps with all of the units and buildings as well ;)
