### ISSUE TITLE
Strange Render(Infantry) attack anim errors

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#5884]
- [ ] 1) Sometimes the last frame will be omitted. As a result, the last frame with a muzzle flash is shown instead of the last frame of the animation (so if the attack anim is 6 frames long, frame 5 is shown at the end).
- [x] 2) Even after being ordered to stop, infantry tends to not go back into idle state, at least it doesn't go back to idle animations.

This screenshot shows both problems (the rifle infantry has been ordered to stop and actually stopped shooting quite a while ago):

![render-error](https://cloud.githubusercontent.com/assets/2857877/3512958/964e7924-06be-11e4-93b7-a8a896b9bb67.png)

For the record, it has been like that for ages, I just kept forgetting to report it.

**Comment by penev92** [comment]
Can someone confirm this is still present issue after #7483 was merged?

**Comment by reaperrr** [comment]
Issue 2) was fixed by #7090, but issue 1) still persists. Easily reproducable by letting TS rifle infantry or ghost stalker shoot to the right.

That being said, most other infantry is not affected, and the TS minigunner and stalker have identical sequences (number of frames), maybe it's something in the sequence code?

**Comment by Phrohdoh** [comment]
RA2 Conscripts stuck on the last frame of `shoot` while they are actually idling:
![image](http://i.imgur.com/eFBUAOs.png)

**Comment by matjaeck** [comment]
I can reproduce a similar error in playtest-20180729, but I'm not sure if this one is congruent with this issue, as the original comment indicates the error occurred regardless of an issued stop order:

![101](https://user-images.githubusercontent.com/37185497/44034500-8a3a90f0-9f0d-11e8-9826-553474b8f779.gif)

In this case, the stop order was issued during the frame(s) that shows the muzzle flash and the stop order caused to stop the sequence at this frame.

However, this does not always happen: Sometimes the "fixed" muzzle flash frame will only last for a couple of seconds after the unit stopped firing, then it goes over to the idle sequence. As the gif above shows, it is also possible to that the muzzle flash frame stays "fixed" (maybe only when it is stopped in the last frame?).

**Comment by reaperrr** [comment]
Fixed by https://github.com/OpenRA/OpenRA/pull/15701.
