### ISSUE TITLE
Minimap shows harvested resources, even if not discovered

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#5908]
On playtest-20140709:
![minimapbuga](https://cloud.githubusercontent.com/assets/7704140/3529761/435efb50-079d-11e4-94a8-16b8f78c0ccb.png)
![minimapbugb](https://cloud.githubusercontent.com/assets/7704140/3529762/476687b8-079d-11e4-9428-e0585255291c.png)
![minimapbugc](https://cloud.githubusercontent.com/assets/7704140/3529862/6d760a72-079e-11e4-8a0e-1633df048ff9.png)
Appears when the fog of war is disabled.
(In the pics I used the spysatellite.)
##

**Comment by pchote** [comment]
The "All players" view is a union of all the player's sight.  What you're suggesting is an intersection, which would be equivalent (when applied to shroud) to having the whole map hidden except for the parts that *everyone* has explored.  That doesn't make a lot of sense.

**Comment by pi99y** [comment]
Please also take look at this related issue #9155 which does almost the opposite - doesn't show the discovered buildings under the fog of war on the mini-map. Thanks.

**Comment by Mailaender** [comment]
I fiddled around with it and this is harder to fix than I thought. Not even sure what is the best approach here. Create a new interface/celllayer for the radar to query or keep the special logic: "resources hidden under fog, but not during first init as we don't if the map started with fog explored" inside RadarWidget.

**Comment by pchote** [comment]
That data already exists, and is what we render in the world.  The radar just needs to use it, instead of the true resource state.

**Comment by Mailaender** [comment]
Not sure why I overcomplicated it so much. Indeed the `FogObscures` check is already done `RenderContent` for easy re-use: https://github.com/Mailaender/OpenRA/blob/hide-minimap-resources/OpenRA.Mods.Common/Traits/World/ResourceLayer.cs#L168

**Comment by SoScared** [comment]
@Mailaender I'm not sure how much people have nagged you guys about this issue in the past but it's a problem being mentioned very frequently among players the past few years. A fix would definitely be an improvement competitive wise.

**Comment by Mailaender** [comment]
I tried to fix it, but essentially failed in the end. https://github.com/OpenRA/OpenRA/pull/11672

**Comment by SoScared** [comment]
Ah ok. Looks like the path continued with #12093 . Here's to hoping^^

**Comment by pchote** [comment]
That ticket has fallen off the bottom of my TODO list, so somebody else will need to pick it up if it is to be fixed in the forseeable future.

**Comment by matjaeck** [comment]
As there has passed some time since the last comment it is worth noting that this is present in playtest-20180729.

**Comment by pchote** [comment]
I still consider this to be the main blocker for enabling explored map in the default game rules.
