### ISSUE TITLE
Implement queued reloading for aircraft [$69]

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#5966]
Since aircraft need to be reloaded, it is very time consuming and boring to reload 20 helicopters at one helipad for example. But if there was a feature that reloaded each aircraft one after another when a group of them are ordered to reload, it would make this process much easier. The same logic could also be applied to repairs at the service depot.

**Comment by fusepilot** [comment]
Agreed, this make helicopters too time consuming to use.

**Comment by reaperrr** [comment]
I'll give it a try, I have an idea that might work.

**Comment by reaperrr** [comment]
Two people expressed interest in dealing with this during the last 2 1/2 months and I haven't made much progress, so I've un-assigned myself.

**Comment by bateramos** [comment]
I'm looking into it. Almost ready.
