### ISSUE TITLE
There's no way to select the CD location

### ISSUE THREAD

**Issue by hobarrera** [OpenRA/OpenRA#5970]
The UI has an option to install music from the CD, however there's no way to select the location of an ISO file, or where the CD is mounted, making it impossible to select the source for the data.
I also haven't had access to any devices with optical (cd) readers for years, and expecting users to have one is a bit unrealistic nowadays.

**Comment by Mailaender** [comment]
I just tested it. Latest Mono 4 and/or our new content installer https://github.com/OpenRA/OpenRA/pull/11375 fixed it. I can right-click in Nemo to mount the ISO and it is discovered by OpenRA.
