### ISSUE TITLE
Units shouldn't fire at targets if their projectile can't reach them

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#6000]
Submarines for example fire torpedos even if there are rocks in the middle. And if they're close to the obstacle, they damage themselves through splash damage. The same applies to flame tower shooting at a target behind a wall that is next to it.
##

**Comment by WolfGaming** [comment]
![image](https://cloud.githubusercontent.com/assets/3696546/6604392/ea069c5e-c81f-11e4-8ac6-e24aec433dbe.png)

**Comment by penev92** [comment]
This is the same as the problem with dogs and kliffs, worms and cliffs, bullets and walls, etc.
I don't feel like searching for those now, otherwise I'd close it as duplicate.

**Comment by pchote** [comment]
Superseded by #12635.
