### ISSUE TITLE
Power shown on selected power plants.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#6011]
Like RA2.
![image](https://cloud.githubusercontent.com/assets/7933210/3640614/fc07ebec-10a5-11e4-961f-45dca765bda7.png)
Maybe as
![image](https://cloud.githubusercontent.com/assets/7933210/3640694/75dc1e60-10a7-11e4-9226-4015d6e8b6ac.png)

**Comment by MustaphaTR** [comment]
I think this is no longer needed. We have power as numbers on UI. Only CnC mod has power bar.

**Comment by Phrohdoh** [comment]
This is needed.

**Comment by sinf** [comment]
Clicking a big building is easy and fast. Waiting for tooltips to appear or squinting eyes to see the tiny power meter next to radar isn't as convenient. MustaphaTR's sketch looks alright but I'd rather have a slightly bigger font.
Something like this:
![screenshot](https://cloud.githubusercontent.com/assets/9487531/7437306/1737c9de-f05f-11e4-963e-4c3346c2cf98.png)
