### ISSUE TITLE
Use a key modifier (e.g. shift) to disable line building

### ISSUE THREAD

**Issue by PUOjACKz** [OpenRA/OpenRA#6032]
Hi, I have found (while playing), that if you start to build up a wall, around your base (at least on the TD mod active, but I think even with the RA one), and you have another one, few cells away, the engine try to connect the two separate walls (even if around 7/8 cells away). I suggest that, while with the mouse you have a wall-piece, and you're deciding where to put it, you can limit the cell-row completion feature, pressing Left-Shift (to just put a single piece of wall, in the highlined cell), or Left-CTRL, just to have a more limited row-completion (of just around 5/6 cells-lenght), in order to ease the creation of siege protection walls around turrets. 

It would be a good idea having, by default, to put just one piece of wall and then, if the player want, extend the cell-lenght coverage, using the CTRL or Shift keyboard buttons.

**Comment by pchote** [comment]
:+1: for this.
