### ISSUE TITLE
New D2K UI

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#6043]
In order to harmonize interfaces accross mods (see #5972 and #5108), here are some proposals about a possible new Dune2000 UI. For the moment, they are just WIP, mockups, ideas.

test1:
![dune2000_test1b](https://cloud.githubusercontent.com/assets/1732773/3670921/ab41ab3a-1249-11e4-9144-fac3cb727f1b.png)

test2 (the one I like least):
![dune2000_test2](https://cloud.githubusercontent.com/assets/1732773/3670784/f54217b2-1247-11e4-9429-1fe15d160dcb.png)

test3:
![dune2000_test3](https://cloud.githubusercontent.com/assets/1732773/3670888/51409574-1249-11e4-8a06-fae0f81423f7.png)

As you can see, the color of the small planet in the middle could change, depending on the faction (blue: atreides, green: ordos, red: harkonnen). Or maybe we want the whole UI to change its color, something like that: http://forum.dune2k.com/topic/25963-release-dune-2000-resource-editor/  ?

**Comment by penev92** [comment]
How is this coming along? :)

**Comment by Mailaender** [comment]
This can now finally fix https://github.com/OpenRA/OpenRA/issues/3699. Is anyone still working on this?

**Comment by x-a-n-a-x** [comment]
I am but there are things I won't be able to do:
- [ ] code the vertical powerbar
- [ ] code the purchase/upgrade/starport buttons
- [ ] fix the backgrounds of Order buttons (heal, repair, sell, options, beacon, power, retreat)

**Comment by Mailaender** [comment]
I think all of these things are pretty unrelated. Can you submit what you have right now?

**Comment by x-a-n-a-x** [comment]
https://github.com/x-a-n-a-x/OpenRA/tree/newD2KUI

**Comment by Mailaender** [comment]
I made some changes to the PNG file. Cutting it in half to not waste empty texture and fixing the background artwork that did not work well when repeated. There was also a lot of wrong coordinates for the buttons.

![image](https://cloud.githubusercontent.com/assets/756669/5893650/6f45dc92-a4ec-11e4-8b0f-c9a4dabc4418.png)

Filed https://github.com/OpenRA/OpenRA/pull/7384 for review.

**Comment by penev92** [comment]
I can't check the PR right now, but that screenshot seems to be missing some things from the image @x-a-n-a-x provided today on IRC:
![](https://cloud.githubusercontent.com/assets/1732773/5345135/9dfd7ad8-7f15-11e4-9dbd-049e59f5c485.png)
Namely the buttons above the build palette and the power bar.

**Comment by Mailaender** [comment]
That seems to be an old version missing the per-faction buttons from https://github.com/OpenRA/OpenRA/issues/6043#issuecomment-65908391, but yes some order buttons are missing or using the wrong symbolism. My guess is that the flag should be diplomacy (which is currently the flash with the green background), but I am not entirely sure if it was intention or just yet another coordinate problem in @x-a-n-a-x's repository. I also don't know what the shield with the + is about.

**Comment by penev92** [comment]
Ah, right. It is the same one.
The shield is for **Guard** mode. The flash should be for toggling building power On/Off.
But I don't think I like the Upgrade and Starport buttons being put with the rest of the production tabs :|

**Comment by pchote** [comment]
> Upgrade and Starport buttons being put with the rest of the production tabs

These are queues, just like the ones we have for the different factories.  They should be treated the same way as the other queues, unless we want to go back to the original D2K behaviour where everything was on the one palette except for upgrades and the starport.

**Comment by Mailaender** [comment]
I don't want to expand the scope of https://github.com/OpenRA/OpenRA/issues/7384 on starport and upgrade queues as I am personally exhausted by those long running pull requests that become more complex and error prone with every new feature they have to implement to maybe get looked at for review and merging.

**Comment by penev92** [comment]
Absolutely. Make the upgrade button disabled and the starport as it is. We just want the UI from this PR. We obviously can't expect 1 PR to change the UI, add upgrades to the buildings and an upgrade queue, fix the airdrop delivery and change the starport ordering logic.

**Comment by Mailaender** [comment]
Please don't confuse "not now" with "not at all" and note that http://i.imgur.com/q5ro7HR.png is just a mockup and not something that was ever implemented.

**Comment by x-a-n-a-x** [comment]
Thank you Mailaender for helping me make this UI work. 
I cloned your branch and I made some modifications to it (UI fixes).

https://github.com/x-a-n-a-x/OpenRA/commits/new-d2k-build-palette-backup

**Comment by Mailaender** [comment]
I used the "gears" icon for the light factory and the "shield" for the heavy one which produces armored vehicles such as tanks. This seems to make sense in the context, but as these symbols are used for settings and defense, that may be confusing. If you find better symbolisms go ahead.

> there is no Defense button (the shield symbol) should gather Concrete Walls, Gun Tower, Rocket Tower (imo)

That would sneak in a balance change we undid many releases ago. We don't have enough buildings for that queue and the mod is already very spammy.

**Comment by Mailaender** [comment]
In fact I would like to combine the light and heavy factory queue sometime in the future.

**Comment by x-a-n-a-x** [comment]
> *In fact I would like to combine the light and heavy factory queue sometime in the future.*


done (in my branch)

**Comment by penev92** [comment]
I want to give a **big** :-1: to merging all vehicles in a single production queue.

**Comment by x-a-n-a-x** [comment]
I thought the same about the Defense button but after testing a bit, I can live with Concrete Walls, Gun Tower, Rocket Tower being merged with other Buildings. Especially if Mailaender says that the mod is already very spammy.

**Comment by MustaphaTR** [comment]
I think light and heavy vehicles to be in different tabs. Because they are building from different buildings. Same tabs means we can't build them at same time. If we can  build a heavy and light vehicle at same tab and same time, this won't be problem.

**Comment by penev92** [comment]
The idea is to make the mod less spammy (which would *hopefully* increase tactical gameplay).

**Comment by Mailaender** [comment]
The unit spam is also a performance problem, but well I guess we should keep those balance changes out for now (as they seem to be controversial) and focus on getting the port to the new UI done especially since it fixes some long-term problems. Changing the queues is easy at any point.

**Comment by penev92** [comment]
As I understand @x-a-n-a-x has already done the queue merge, so let's keep it (no point in undoing it now just to do it again later) and see how that goes.

**Comment by Mailaender** [comment]
The problem with @x-a-n-a-x's branch is that he is trying to do too many things at once instead of focusing to get an already complex problem solved and integrated. That is the reason this is so painful and long-running. Damn, I shouldn't have mentioned balancing changes. I guess https://github.com/OpenRA/OpenRA/pull/7384 will land in review hell soon.

**Comment by x-a-n-a-x** [comment]
Everything seems fine now since I have based my current branch: 
https://github.com/x-a-n-a-x/OpenRA/commits/new-d2k-build-palette-backup 
...on your own new-d2k-build-palette branch, Mailaender.

Light and heavy vehicles are combined (as suggested). 
The scrolling Queue is there too..

There are still some little tasks to do (see https://github.com/OpenRA/OpenRA/issues/6043#issuecomment-71561491) but my branch seems quite stable to me.

**Comment by Mailaender** [comment]
Sounds great, I will integrate your changes in my pull request at the weekend. You can also file one yourself if you don't want to wait.

**Comment by Mailaender** [comment]
Updated https://github.com/OpenRA/OpenRA/pull/7384:

![image](https://cloud.githubusercontent.com/assets/756669/5991813/bb093c94-aa07-11e4-96bd-7c7f04556d64.png)

**Comment by Mailaender** [comment]
Added a decorational vertical power bar (with some pixel art fixes) to hide the repetitive wood grain:

![image](https://cloud.githubusercontent.com/assets/756669/5991868/88fd1de4-aa0a-11e4-8dde-b89c32a1239f.png)

**Comment by penev92** [comment]
Looks good. Just a few small things:
1. The power bar should probably be a few pixels shorter and start a few pixels lower so that it is aligned with the horizontal line that is below the order buttons.
2. The production tab icons: if we are going with no defense tab and a combined vehicle tab, I think the "gear" and the "shield" tabs should be replaced by the "tank" icon tab that contains all vehicles.
3. The "gear" order button from your previous screenshot is used for the debug menu, isn't it?
It looks weird with that one missing. Maybe keep it there at all times and just disable it when cheats are not tuned on?

**Comment by Mailaender** [comment]
We are not going with a combined vehicle queue for now.

**Comment by Mailaender** [comment]
Updated https://github.com/OpenRA/OpenRA/pull/7384 with some final touchups by @x-a-n-a-x:

![image](https://cloud.githubusercontent.com/assets/756669/5993327/5e48d21c-aa4d-11e4-9330-79521071d518.png)

**Comment by x-a-n-a-x** [comment]
Here is the latest update: 
![screenshot003](https://cloud.githubusercontent.com/assets/1732773/5993394/54f24d4a-aa4f-11e4-8421-2145e96c81c2.png)

**Comment by x-a-n-a-x** [comment]
I have tried to modify the texture behind the Production buttons (the Buildings one especially) to not make the pattern mismatch the other texture (I hope you understand what I am saying..). Here is the result of this test: 
https://www.dropbox.com/s/kpx0uftg6gonnwq/ScreenShot003a.png?dl=0

I have also been asked to align the Vertical powerbar with the Production tabs and with the Production palette. I had no other choice than to shorten the powerbar ; but now, here is what I get (the vertical powerbar is incorrectly repeated):
https://www.dropbox.com/s/77rgtidttkj6ff5/ScreenShot003.png?dl=0

The vertical powerbar "worked" on Mailaender's screenshot because dots where repeated too (the top and bottom parts of the powerbar where placed out of the repeating area). So, I am wondering if the vertical powerbar is really needed on the sidebar ? I mean.. couldn't it be added when the game starts, like the other production tabs or symbols? (I just ask.. I still can try to find a workaround to add it on the UI itself).

**Comment by Beep6581** [comment]
Would look much better if the background texture did not have the repetitive pattern. Use GIMP's Resynthesizer for that.

**Comment by x-a-n-a-x** [comment]
I have tried a similar technique but it's not that easy not to create a repetitive pattern with a 48 pixels high area.. I think it's (almost good now).

**Comment by x-a-n-a-x** [comment]
Current status of my branch with my latest changes:

Normal UI:
![screen-shot__fffff2](https://cloud.githubusercontent.com/assets/1732773/6091918/1e5da814-aec4-11e4-8d10-18c9c726d35d.PNG)

With "Build Everything" enabled:
![screen-shot__fffff1](https://cloud.githubusercontent.com/assets/1732773/6091916/19690588-aec4-11e4-8bce-f69c5eba241c.png)

**Comment by penev92** [comment]
The texture is fine IMO, and the power bar depends on whether we can get someone to get it working in time. I think it's fine to have it a s placeholder for the next playtest, but it definitely needs to be done by the time a release comes along.

**Comment by x-a-n-a-x** [comment]
After pchote's comments on IRC, I am currently working on a modified D2K UI with smaller minimap and Order buttons placed closer.

**Comment by pchote** [comment]
This is looking much better.  Great job :)

Note that my request to move the buttons closer together will mean that the clickable areas will overlap.

A relatively straightforward future improvement would be to add a "clickable region" definition for buttons: a polygon area defined by a list of x,y pairs (with straight lines between them), with x/y = 0.0 at the left/top, and x/y = 1.0 at the right/bottom of the button's width/height.

It is simple to calculate whether a point (the mouse location) is inside a polygon using the even-odd or winding rules.  Wikipedia or google should give some hints on how to use these, and I have also dug out https://github.com/pchote/raytracing-grid-diagram/blob/master/typedefs.c which has examples of both (`testPolygonAgainstSource` and `newTestPolygonAgainstSource`).

**Comment by x-a-n-a-x** [comment]
Latest changes:
https://github.com/x-a-n-a-x/OpenRA/commits/new-d2k-build-palette4

![screen shot 02-07-15 at 11 33 pm](https://cloud.githubusercontent.com/assets/1732773/6094234/e62fcf22-af21-11e4-9c62-41130568b500.PNG)

TODO:
- fix the minimap with overlapping UI elements

http://logs.openra.net/?year=2015&month=02&day=07#20:57:37

**Comment by penev92** [comment]
I'm going to miss the power bar...
Also expect a lot of complaints about the overlapping areas of the order buttons.
With that said, it looks good.

**Comment by x-a-n-a-x** [comment]
The powerbar might come back (later). 
One step at a time, young padawan :-)

**Comment by Mailaender** [comment]
Updated #7384 with your recent changes and resolved the repetitive background texture problem by not expanding the build palette too much:

![image](https://cloud.githubusercontent.com/assets/756669/6096016/99d0ec3e-af7a-11e4-9c1f-e2ee4a337ec2.png)

**Comment by x-a-n-a-x** [comment]
Usefull when the player enables "Build Everything" but please keep the default Buildings tab show 6 rows. I would dislike to scroll down to reach the IX Lab and Palace.

**Comment by Mailaender** [comment]
That will highlight your repetitive texture though:

![image](https://cloud.githubusercontent.com/assets/756669/6096157/46adfac0-af83-11e4-85e5-6814fb37e51a.png)

**Comment by Mailaender** [comment]
It is not that bad though: updated https://github.com/OpenRA/OpenRA/pull/7384.

**Comment by x-a-n-a-x** [comment]
I know but seeing all the buildings in the first Buildings tab (without scrolling down) is important imo.

**Comment by x-a-n-a-x** [comment]
BIG update guys! Thanks to pchote, mailaender and scott, here is how the UI looks:
![screen shot 02-08-15 at 12 30 pm](https://cloud.githubusercontent.com/assets/1732773/6096395/010ac06e-af8f-11e4-9b54-e583056f5f82.PNG)

**Comment by WolfGaming** [comment]
Lovely :)

**Comment by Mailaender** [comment]
Here we go again. I am a bit tired of copying your changes from those various branches and commits into https://github.com/OpenRA/OpenRA/pull/7384 which you could easily do on your own, but to make things less dull I added support for the insignias you never setup in YAML, but introduced recently to your artwork:

![image](https://cloud.githubusercontent.com/assets/756669/6098074/4edf5b4e-afd3-11e4-843a-29080714b2ca.png)

**Comment by penev92** [comment]
:+1: 
Except the missing debug button.

**Comment by x-a-n-a-x** [comment]
The Debug button has already been implemented. It's just not shown here on the screenshot.

**Comment by penev92** [comment]
I know, it looks good with it.
But it would probably need a disable state so that we don't have that empty space in regular games.

**Comment by x-a-n-a-x** [comment]
hmm... I don't know. 
I think the button shouldn't be displayed if the option is disabled (the current behavior is ok, imo).
Btw, in most games, the debug and diplomacy buttons will not be displayed.

**Comment by penev92** [comment]
Well if the diplomacy button is not there, than I suppose it's acceptable...
But 90% of the games won't have a debug button :|

**Comment by Phrohdoh** [comment]
I'm fine with excluding it just as we do in ra.

**Comment by Mailaender** [comment]
I think the reason for the missing debug button is missing artwork (it just repeats the settings gearwheel) so that should be easily fixable.

**Comment by penev92** [comment]
It is supposed to be a gearwheel I think.

**Comment by x-a-n-a-x** [comment]
The Debug button worked fine in my https://github.com/x-a-n-a-x/OpenRA/tree/new-d2k-build-palette4-bis branch. 

And the artwork is there in the chrome.png file too:
https://github.com/OpenRA/OpenRA/blob/b0f986887c9b8a66cf3474cf4d0026d452dd5eee/mods/d2k/uibits/chrome.png

**Comment by x-a-n-a-x** [comment]
Thanks @pchote and @Mailaender for helping me with this UI. 
I wouldn't have been able to make it without both of you.

**Comment by Mailaender** [comment]
I was talking about https://raw.githubusercontent.com/OpenRA/OpenRA/bleed/mods/ra/uibits/chrome.png which lacks a debug button artwork. Although it is technically the same menu with another tab open now, identical icons somehow defeat the purpose of symbols (quick discoverability).

**Comment by x-a-n-a-x** [comment]
Good point, Mailaender. I will create a new symbol for the Debug button and suggest it to you, guys.

**Comment by WolfGaming** [comment]
Good job on this, then we could finally remove the legacy build queue stuff, and good riddance it was.

**Comment by x-a-n-a-x** [comment]
my first suggestion (16x16 symbol, a mix of gear and wrench):

![chrome](https://cloud.githubusercontent.com/assets/1732773/6130175/bf7bdc3a-b143-11e4-9cac-60dd51ff0e59.png)

Closer view:

![screen shot 02-10-15 at 04 41 pm](https://cloud.githubusercontent.com/assets/1732773/6130190/d545198c-b143-11e4-9197-5760c40a32b8.PNG)

Finding a good symbol is not that easy since we already use a gear for "Settings" and a wrench tool for "Repair".

**Comment by pchote** [comment]
I would prefer we just remove the debug button.  It hasn't been needed since the big ingame menu overhaul.

**Comment by penev92** [comment]
So what do we do with the empty space on the D2k UI?

**Comment by x-a-n-a-x** [comment]
I have mixed feelings about removing the Debug button. I kinda liked it.
And if we remove it completely, there will really be an empty space..

**Comment by Mailaender** [comment]
> Good job on this, then we could finally remove the legacy build queue stuff, and good riddance it was.

We still need a new build palette for the Tiberian Sun mod.

**Comment by MustaphaTR** [comment]
> We still need a new build palette for the Tiberian Sun mod.

It will be better if we release TS mod with a new build balette.

**Comment by Mailaender** [comment]
The mockups from http://www.sleipnirstuff.com/forum/viewtopic.php?f=83&p=288650#288650 may be a good starting point to create a proper build palette for the WIP ts mod.
