### ISSUE TITLE
New shortcut: CTRL+rClick -> instant cancel unit that is being built [$20]

### ISSUE THREAD

**Issue by VagueVigor** [OpenRA/OpenRA#6082]
I really hate the slowness of canceling some unit from building; first it makes it on hold, and then after 10 clicks (because game lags), it will finally cancel it.

It would be super awesome if there was shortcut to insta-cancel anything.

So if you CTRL+rightclick, it would CANCEL the unit (you get money back from whatever was used for it before). Not just remove 1 from queue like the current cancel behaviour acts now; in current way its really hard to cancel something if you have 100 on queue.

**Comment by r34ch** [comment]
This would make more sense if it instantly cancelled all queued units of that type. Rather than mashing shift+rclick

**Comment by Mailaender** [comment]
Implemented in https://github.com/OpenRA/OpenRA/pull/9595. @ChaoticMind please collect your bounty.
