### ISSUE TITLE
Request: C&C Covert Operations missions

### ISSUE THREAD

**Issue by ccsv** [OpenRA/OpenRA#6096]
I am not sure if the C&C Covert Ops expansion missions were added yet or is it WIP?

 GDI Missions
- Blackout
- Hell's Fury
- Infiltrated!
- Elemental Imperative
- Ground Zero
- Twist of Fate
- Blindsided

Nod Missions
- Bad Neighborhood
- Deceit
- Eviction Notice
- The Tiberium Strain
- Cloak and Dagger
- Hostile Takeover
- Under Siege:  C&C
- Nod Death Squad

Also there are several dino missions too.
##

**Comment by abcdefg30** [comment]
Closing as covered by #4988.
