### ISSUE TITLE
Add a production handicap option

### ISSUE THREAD

**Issue by pizzaoverhead** [OpenRA/OpenRA#6103]
Currently games between players of different skill levels are generally short and unenjoyable. Having a +/- multiplier option for production in the lobby would allow a wider range of skill levels to play together, and allow challenges such as four humans versus a single 400% production AI.
##

**Comment by Smittytron** [comment]
Though not exclusively handicapping production, handicaps were introduced by #18971, which satisfies the crux of this issue.
