### ISSUE TITLE
RA1 Gap technology fails to work when Shroud is disabled

### ISSUE THREAD

**Issue by Chertograd** [OpenRA/OpenRA#6123]
What I mean is that if Shroud is turned off in the game settings (most of my friends like to play with it off because seeing the terrain is a huge thing if you don't remember the map), then units/buildings like the Gap Generator or the vehicle that does the same thing don't work at all. We tried and it basically did nothing.

Could this be fixed in any way so that the Allies don't lose 2 units when one game setting is turned off? :O

**Comment by MicroJOo** [comment]
@ScottNZ  : this makes the current france - faction useless

**Comment by deniz1a** [comment]
OK how about this: Gap generators generate Fog of War and not shroud. It hides buildings within its range and even if the enemy discovers these buildings, they disappear again under FOW when his units leave the area. This would basically produce the same function for gap gen but it would also be compatible with no shroud option. Also this way the gap gen wouldn't draw attention to itself. It would look as if there isn't anything there.

And if in lobby settings FOW is disabled, then gap gen paints empty terrain within its radius. So again, it looks like nothing is there unless enemy units have visual contact.

What do you think?

**Comment by pchote** [comment]
@deniz1a: that is basically the idea that i've been pushing for for months (e.g. [1](http://logs.openra.net/?year=2014&month=10&day=26#01:35:55), [2](http://logs.openra.net/?year=2015&month=02&day=22#14:43:56)), so :+1: (but not the cloaking with FOW disabled).

**Comment by deniz1a** [comment]
OK. Then gap gen would be useless if FOW and shroud both are disabled but so is Satellite.
