### ISSUE TITLE
Implement Attack move + Left click

### ISSUE THREAD

**Issue by havok13888** [OpenRA/OpenRA#6126]
Implement an option to use Attack move + left click for players comfortable with using the system similar to blizzard games.

More here: http://www.reddit.com/r/openra/comments/2c56cs/attack_move_left_click/
##

**Comment by Unit158** [comment]
I'm going to say that we want to keep true to C&C here, and extra interaction models will not be maintainable, so :-1:

**Comment by penev92** [comment]
As long as someone comes up with a better name than "Blizzard-style mouse orders" and actually implements it as an option in the settings menu I guess the "modern gamers" might like it...
I don't expect anyone here to go ahead and implement it though, nor do I expect that it will be merged easily if someone else implements it anyway.

**Comment by GraionDilach** [comment]
This is the A-move - A then click afaik.

**Comment by Unit158** [comment]
He's asking for the ability to attack and use attack move at the same time with the mouse.

**Comment by matjaeck** [comment]
> Well attack can be right click while simultaneously when you use Attack move, left click becomes the attack button and right click becomes cancel

The request is that the order generator activated by the attack move hotkey or the command bar uses left click as action button, while the standard action button remains right click. Basically how the support power cursor works.

**Comment by pchote** [comment]
This option doesn't fit in either of our supported control schemes. I don't see how this would be feasible at all, let alone easy to implement, so closing as a wontfix.
