### ISSUE TITLE
Sonar pulse can be used as an overpowered spyplane

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#6145]
It can instantly reveal any location on the map once every 30 seconds.

This should be restricted to water only (or more specifically a list of terrain types specified in the power), and the shroud reveal should be removed.
##

**Comment by deniz1a** [comment]
Also is sonar pulse tied to any structure? It should require radar or something.

**Comment by Phrohdoh** [comment]
@deniz1a One topic per issue please.
