### ISSUE TITLE
Global player experience

### ISSUE THREAD

**Issue by Phoib** [OpenRA/OpenRA#6154]
In the Generals/BFME games, there was a global experience meter, used to buy special powers.

After an X amount of exprience (Called SkillPoints in Generals), players got awarded SciencePurchasePoints, with which Special Powers could be bought.

In order to facilitate such a system, there has to be a way to track global experience for a player, and add experience to a player, on the basis of the GivesBounty trait.

**Comment by GraionDilach** [comment]
This got added by now.
