### ISSUE TITLE
Regression: Oberserver UI, Power countdown hidden under options & statistics buttons

### ISSUE THREAD

**Issue by UberWaffe** [OpenRA/OpenRA#6191]
The very top-most of the globally displayed countdown timers (GPS / Nuke) is hidden under the options and statistics buttons.

In this image: http://s10.postimg.org/rqn8wo915/Error01.png you can see Yellow has a nuke, but its countdown is displayed under the buttons. (You can barely make out a single slither of yellow of the countdown).

**Comment by pchote** [comment]
Fixed by #6737.
