### ISSUE TITLE
Atmosphere Effects?

### ISSUE THREAD

**Issue by scskwirl** [OpenRA/OpenRA#6200]
Any way for a mod to include atmosphere effects such as day/night, hot/clear/overcast, rain/storm/snowing, etc?

Except for maybe very small "rain" sprites, this wouldn't need more than some way to darken or change the hue on the screen (for example, a hot day would have a slight yellow to look like the sun searing through the map, or night would make the map much darker).

Being able to cycle through them with programmable timers in a widget would be great too, to add even more variety to the game.

Extra idea: rain/snow effect would slightly slow movement of units, and storms would temporarily disable the radar, if desired.

**Comment by x-a-n-a-x** [comment]
And what about adding a moving fog ?
http://media.moddb.com/images/mods/1/11/10740/sshot348.jpg

**Comment by obrakmann** [comment]
Added in #8766
