### ISSUE TITLE
Lag causes replays to stop [$58]

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#6241]
ive noticed this in several replays , if the (real) game got slowed down because of lags (but the whole game went fine) it can cause replays to stop the playback after a certain amount of minutes (being watched) and remain that way ...

so basicly , you can loose (good?) replays if there was connection problems involved during the real game

**Comment by bnemer** [comment]
Same happens when a player disconnects, or is dropped after a minute of disconnection.

**Comment by fgdzfggsfgsfgsf** [comment]
Here are a few example replays where this happens.
https://www.dropbox.com/s/fyjvioc2vkyvm3g/Openra%2020150424%20release%20replays%20freezing.zip?dl=0

**Comment by grouzen** [comment]
Why this bug is still open? ;)

**Comment by Unit158** [comment]
I understand you're being slightly sarcastic, but none of the devs so far have wanted to do the debugging to figure out why this happens. Just because there is money associated doesn't mean it's worth the time to do.

**Comment by Herve-M** [comment]
As fist see it's impossible to load an old replay with the last release or bleed version.
Even if I work with the good version (for replay from @fgdzfggsfgsfgsf release-20150424), I can't debug (attach to process) the released version without the debug symbol.

So is it possible to load a replay from release into a dev version ? (as using same release / dev version)

**Comment by penev92** [comment]
You can `git checkout release-20150424` and build that. Then you will need to change the mod's version in mod.yaml to `release-20150424` and you can then load the replay.

**Comment by Herve-M** [comment]
@penev92 Thanks for info !
