### ISSUE TITLE
Different sounds for joining/leaving/messages ?

### ISSUE THREAD

**Issue by VagueVigor** [OpenRA/OpenRA#6246]
Most of the time i just listen to the game to know if people join my game room. But the problem is that i cant tell difference from those players that leave my room. Same happens when someone sends a message.

So could we have it customizable to put your own wav files for:
- Player has joined the room.
- Player has left the room.
- A message has been received.

**Comment by Smittytron** [comment]
Browsed through each mod's available sounds; here's what I think would work:

**RA**
bleep11 - Player joined
bleep12 - Player left
bleep6 - Lobby option changed
**CNC**
country4 - Player joined
bleep2 - Player left
country1 - Lobby option changed
**D2K**
stealth2- Player joined
stealth1 - Player left
endlist1 - Lobby option changed
**TS**
orcaup - Player joined
orcadwn - Player left
boop - Lobby option changed

Chat sounds would remain as they are now.

**Comment by dragunoff** [comment]
I recently also went through the available sounds looking for a fitting sound for player name pinging. There are sounds that could work such as those proposed by @Smittytron. However I think it could work out better if we design our own sounds (or use some public domain/open license samples) 🤔 I know this is much more work and we might need a person with the right skills but I want to put this idea on the table.

**Comment by PunkPun** [comment]
Tbf I like selected sounds for all base mods, except for RA. They really feel TD like and don't fit RA at all

**Comment by PunkPun** [comment]
I've taken a look again while keeping in mind that players will be constantly assaulted by the sounds. This is the list I came up with

For RA
- bleep11 - Player joined
- bleep12 - Player left
- bleep17 - Lobby option changed

For TD
- bleep2 - Player joined
- beepy3 - Player left.
   - This is the best I could find. Though I'm still not a fan of it.
- beepy6 - Lobby option changed

for D2K
- CHAT1 - Player joined.
   - The chat sound sounds like an entrance sound. It would be nice if we were able to change the chat sound itself to something else.
- ENDLIST1 - Player left
- SCORTIK1 - Lobby option changed

**Comment by PunkPun** [comment]
with #20050 adding sounds just a matter of changing the yaml definitions in metrics.yaml

**Comment by Mailaender** [comment]
Why did you ask for removal of the sounds we had in #20050 then?

**Comment by PunkPun** [comment]
I did not ask for removal. I was just not happy with the sounds that were selected

**Comment by PunkPun** [comment]
#21265 added them for d2k
