### ISSUE TITLE
Issue with order click area (diamond-shaped cells)

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#6247]
I noticed this when I tested a larger cellsize of 110x64 (diamond shape), basically I have to click almost smack in the middle of a cell, otherwise the move/attack order will be issued to the nearest adjacent cell even if the mouse was within the targeted cell at the time of clicking.

Maybe the click area isn't scaled with cell size?

**Comment by reaperrr** [comment]
To reproduce this, simply enable the cell grid in the TS debug options and order some unit around a little. You'll notice that more often than not, the move order will be off by 1 cell.

**Comment by pchote** [comment]
I expect this will be fixed as a side-effect of rewriting the screen -> cell conversion to be heightmap aware (whenever that happens).

**Comment by Phrohdoh** [comment]
I've reported this in another issue but cannot locate it at the moment. Filter with the TibSun label.

**Comment by Mailaender** [comment]
We now have height map support. https://github.com/OpenRA/OpenRA/pull/6901 Can you retest?

**Comment by reaperrr** [comment]
Yes, issue still persists. In fact, Terrain Geometry grid cheat makes this quite easy for anyone to reproduce. If you click just slightly "south-west" of the center of a cell, the order will go to the cell south-west of the cell you click on.

Exactly like #6840, by the way, so it's probably not an issue with orders, but an underlying flaw in the coordinate calculation.
