### ISSUE TITLE
Harvesters refuse to harvest sometimes

### ISSUE THREAD

**Issue by VagueVigor** [OpenRA/OpenRA#6269]
I click to the ore, but it automatically goes somewhere else as if it couldnt find any ore from there:

http://i1.minus.com/ilava7nkKIyvB.jpg

I think this bug sometimes fixes itself during the game.

**Comment by reaperrr** [comment]
This was before the harvester search refactor, and I haven't noticed this specific issue since then, so I guess this can be closed.
