### ISSUE TITLE
Unit and Turret ROT should be brought in line with Speed

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#6276]
1) Abbreviations don't follow OpenRA's style conventions, so ROT should be renamed to something like RateOfTurn/TurnRate/TurnSpeed, or something along those lines.

2) In comparison to Speed, which uses world units, ROT is too coarse-grained and should use  comparable values for consistency and more fine-grained control (for example: what is now a turn rate of 3, should be 128 for RA/TD).

**Comment by reaperrr** [comment]
1) has been adressed, while 2) would be a pain since facings and WDist are different concepts, so this can be closed.

**Comment by pchote** [comment]
2) will be addressed when somebody builds up the courage to finish replacing facings with WAngle.
