### ISSUE TITLE
^Vehicle inheritance bloat

### ISSUE THREAD

**Issue by scskwirl** [OpenRA/OpenRA#6285]
As requested this is being filed as a bug.

There is a ^Vehicle class, but none of the other "vehicles" seem to inherit its traits, like ^Tank or ^Plane.

**Comment by GraionDilach** [comment]
Is this still valid after the cleanups of @reaperrr last month or so?

**Comment by penev92** [comment]
I don't think so.
Also I can't check, because there is no mod mentionet.
But in any case I've been oveh the definitions quote a few times during the past half year and I don't think this needs to remain open any more.
