### ISSUE TITLE
Include MetaData:Author: somewhere in the main menu?

### ISSUE THREAD

**Issue by scskwirl** [OpenRA/OpenRA#6286]
Should we nclude MetaData:Author: or some other kind of "tag" somewhere in the main menu's labels?

Over or under the version number, maybe to the side, or the bottom or corners of the screen, etc.

examples of what the text could say:

MyMod (c) 2010 by Creator

by CreationTeam

Metadata should of course keep the specific details separate. In other words, the Author is not "2010 Creator", but you can include a Year: trait to that effect.
##

**Comment by pchote** [comment]
Fixed by #15204.
