### ISSUE TITLE
chinook eject cargo with parachute whilst in air

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#6290]
this idea exists in 2 different ways :
1. make cargo dropable per right-mouseclick on the chinook whilest in air
2. give cargo a %-chance (for each filled slot individual) to survive when chinook has 0 hp ... giving em the possibility to basicly "jump out of the chinook and open up a parachute"
   ![](https://cloud.githubusercontent.com/assets/1997864/3983102/d38893e4-287c-11e4-8de1-bc229dd4bde8.png)

we could add both , or just one of these options

this will open up the way for interesting strategys without the fear of loosing the fragile chinook with 8-slot valuable cargo (the chinook itself for 900 is a good price , but still not just a peanut) 
soviets for example , have the option to "iron-cutain" a naval transporter ... sadly , we cant "iron curtain" planes ...

if there is any problem with the balance , we could still adjust chinooks HP , lower the %-chance to survive , nerf the number of seats , adjust chinooks price
##

**Comment by Smittytron** [comment]
Closing as wontfix as part of our Discord github-cleanup initiative. We won't be doing this for shipped mods.
