### ISSUE TITLE
FMVs for expansion missions from C&C Red Alert

### ISSUE THREAD

**Issue by ccsv** [OpenRA/OpenRA#6295]
In the Playstation Version of the expansion Red Alert: Retaliation FMV were added to the missions. These FMVs were not included in the expansions Aftermath and Counterstrike but were added in a patch for The first Decade.

Red Alert Retaliation Allies FMVs
http://www.youtube.com/watch?v=rBGLtn15h9Q

Red Alert Retaliation Soviet FMVs
http://www.youtube.com/watch?v=diJFBZk9uFY

Ant missions
http://www.youtube.com/watch?v=R6SFNzfWdc4

Will these be included in OpenRA?

**Comment by pchote** [comment]
These videos weren't included in the freeware release of RA, so we can't really use these.
