### ISSUE TITLE
Different Notifications Narrator/Sounds for different teams

### ISSUE THREAD

**Issue by scskwirl** [OpenRA/OpenRA#6353]
There is only one narrator for any faction in any mod, with notifications.yaml only accepting one .aud file at a time.

What about using the same suffix effect in the voices.yaml for narrating too? Make it sound like each faction's interface has different narration and sound effects.

**Comment by Phrohdoh** [comment]
@scskwirl does [the way RA2 does it](https://github.com/Phrohdoh/oramod-ra2/blob/master/notifications.yaml#L1-L12) resolve this issue?

**Comment by scskwirl** [comment]
Totally forgot about this thread. lol

Looks like it does. I didn't test it yet.

But yes, have a prefix string that then points to which set of sound effects to use. So if I wanted to, I could have different voices for each specific team. That looks like it here.

**Comment by pchote** [comment]
I think it would be a good idea to rework our audio definition parsing to match our new sequence parsing (#7631).  Each mod can then define its own way to optimally resolve the filename for each notification type, without conflicting with other mods.
