### ISSUE TITLE
First frame of most animations is omitted [$20]

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#6389]
I'm aware this could be considered a clone of other issues, but those other issues just describe specific symptoms caused by this underlying issue.

I've tried to find the exact problem, and I *think* there's something wrong with PlayThen in Animations. 1-frame animations and the first frame of any longer animation need insanely high tick values just to sometimes show up, while the 2nd frame of any 2+ frames animation is pretty much always displayed.

If the problem is that something is ticking too fast for the first frame to be visible and hard to fix properly, we should at least artificially delay the start of an animation until that problematic point has passed.

In any case, fixing this would close #3706, #4025, and probably #5884.

Additionally, this is a blocker for replacing DeadBuildingState with a normal death animation, unless we want to use the same awfully ugly, hacky work-around as for the D2k muzzle flashes (just look at the muzzle ```Frames:```, you'll see what I mean). I'd prefer to see this fixed and get rid of the D2k muzzle hacks instead.

**Comment by Mailaender** [comment]
Fixed in https://github.com/OpenRA/OpenRA/pull/7483.
