### ISSUE TITLE
Notify a player of gameplay events when all audio is muted

### ISSUE THREAD

**Issue by Fincer** [OpenRA/OpenRA#6400]
For example: When an enemy attacks your base, you get a EVA warning "Our base is under attack". Additionally, and optionally, this information could be offered with a basic text string somewhere on the screen (bottom left?), so if audio is muted for some reason the player still gets information that his/her base is under attack. Same thing with super weapons, airstrikes etc.

As a player, I'm forced to mute my computer audio in some situations (school, public spaces etc.). If I still would like to play OpenRA muted, I don't currently get information if my base is under attack or what is happening around the map. It's not very nice to see your base is half-destroyed just because you were not allowed to use audio in gameplay.
##

**Comment by dragunoff** [comment]
Related: #6354 and #3278
