### ISSUE TITLE
AI improvements

### ISSUE THREAD

**Issue by Fincer** [OpenRA/OpenRA#6401]
1: AI doesn't realize to build troops when it should

AI doesn't use its full resources when earning a lot of money. Expected behaviour is to build more infantry, tanks, navy and stuff, but instead, AI decides to build more Ore Silos to store money. This gives no challenge to a human player and makes the gameplay very boring overall. The forementioned event happens especially when playing with low tech levels and in maps with lots of ore.

2: AI should capture buildings

Does AI capture oil derricks? Or does it try to take enemy/your buildings? As far as I've seen, there is no such feature yet. Would be great improvement because it adds game dynamics and interaction between players.

3: AI descriptions

Red Alert AI descriptions are quite understandable. However, I have no idea about C&C TD AI behaviours. How does Watson, or Cabal act in the game field? How do they differ from each other? These unclear and mythic AI titles should be described clearly to a player to improve gaming experience to the end-user.

4: Adjustable AI difficulty

As far as I can remember, there were such feature in the original Red Alert. AI difficulty should be adjustable so players could improve their gaming experience. Scale could be something like...

Very Easy - Easy - Normal - Hard - Very Hard - Insane/Brutal

**Comment by Mailaender** [comment]
Thanks for your feedback. This should be split into multiple resolvable bug reports.
