### ISSUE TITLE
Trees/Shrubbery should burn when using a flame thrower

### ISSUE THREAD

**Issue by Fincer** [OpenRA/OpenRA#6403]
Expected behaviour for trees is to burn when using flame-based weapons. As far as I've tested, nothing happens currently.
- [x] Tiberian Dawn #11180
- [x] Red Alert #11377
- [x] Tiberian Sun ~~#11405 #11484~~ #18730

**Comment by r34ch** [comment]
At a minimum this should apply for nuke weapons too.

**Comment by Mailaender** [comment]
Reopening and adding a checklist for the other mods.

**Comment by Leo512bit** [comment]
How are we going to handle this for RA&TD now?
