### ISSUE TITLE
Terrain Tunnels

### ISSUE THREAD

**Issue by scskwirl** [OpenRA/OpenRA#6410]
To add a third dimension to the map, include a terrain implementation that allows units to go under map tiles (natural bridges, caves, etc.) Probably use a value that tracks how high a tile is, and where a unit is?

In lieu of #6357, It would be cool to have these just as easily destroyed, but suppose a nuke or chronoshift was used; how will the engine know if it wants to teleport/destroy the tiles inside or out?

**Comment by pchote** [comment]
This can be implemented in two stages:

1. Implement an explicit move-through-tunnel order and activity:
   * When issued the order units move to the tunnel footprint, are removed from the actor map, lerp across the map to the linked tunnel, then are reinserted into the actor map.
   * Units should remain selectable when they are "in" the tunnel, but are made invisible (using an upgrade?)
    * Tunnel activity is non-cancelable, so any orders issues while in the tunnel are queued until after it leaves.
2. Implement automatic pathing through tunnels:
   * Change the pathfinder to explicitly track connections from each cell to adjacent neighbours.
   * Tunnels (and later high bridges) insert new connections into this layer - for tunnels this is simply a direct link from one entrance to the other, with a fixed cost.

**Comment by GraionDilach** [comment]
>Units should remain selectable when they are "in" the tunnel, but are made invisible (using an upgrade?)
The rendering behaviour of the units-in-tunnels in WW games were the same as the ones underground. Maybe grant an upgrade for below-ground-level?

**Comment by penev92** [comment]
Once the current actor-behind-cliff issue (the actor being rendered *above* the cliff) is resolved, wouldn't simply hacking the actor's `CenterPosition.Z` hide it underground?

**Comment by pchote** [comment]
yes, but tunnels are a reasonably straightforward feature that i'm hoping will make it in long before we finish the renderer rewrite needed for that.

**Comment by GraionDilach** [comment]
The upgrade would still be good if we get through the Targetable* thingies to make units in tunnels unaffected by the war above them.

**Comment by pchote** [comment]
A preview of things to come: https://www.dropbox.com/s/xtups4l1jormalx/jumptunnels.m4v?dl=0

**Comment by GraionDilach** [comment]
W-w-wait.... TS JUMPJET LOGIC?! D:

**Comment by pchote** [comment]
A jumpjet is just a portable sky-tunnel generator, after all :wink:

**Comment by GraionDilach** [comment]
True, now that you mention... I never looked at it that way.

**Comment by pchote** [comment]
And to complete the set, we have the portable underground-tunnel generator and the above-ground tunnel: https://www.dropbox.com/s/yqyrlgog3v6awsy/digbridge.mov?dl=0

**Comment by WolfGaming** [comment]
@pchote Love the digging :P
I assume it is still a work in progress? (If not, the shadow at the end there bugged out)
