### ISSUE TITLE
False audio-feedback when using F-hotkeys.

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#6460]
If an actor is not buildable (due to your techtree) atm but is visible in the build palette you can use the F1-12 hotkey corresponding to it and get the "building" audio feedback, when in fact it is not building.

**Comment by Mailaender** [comment]
Can't reproduce. Probably fixed by https://github.com/OpenRA/OpenRA/pull/7461/https://github.com/OpenRA/OpenRA/pull/7699.
