### ISSUE TITLE
Game crashes when (one) Map(s) contains invalid Data

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#6491]
I had tried to change the Map size of the Testmap from "128,128" to "130,130"
The Game chrashed with Exception "The Map contains invalid Data"

The Exception is thrown in file:
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Graphics/Minimap.cs

At Line: 37			var mapTiles = map.MapTiles.Value;

It Seems when we have 4 maps and one of these Maps contains invalid Data, the game will crash :(
We should "ignore or skip" this Map and notice the User about this "invalid Map Data" instead of Crashing to Desktop :( and proceed the Next Map

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Map/Map.cs#L40

**Comment by Unit158** [comment]
Please reopen this, as the crash is indeed a flaw.

**Comment by LipkeGu** [comment]
```
Red Alert Mod at Version {DEV_VERSION}
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IndexOutOfRangeException`: Der Index war außerhalb des Arraybereichs.
   bei OpenRA.CellLayer`1.get_Item(MPos uv) in d:\Projekte\OpenRA\OpenRA.Game\Map\CellLayer.cs:Zeile 99.
   bei OpenRA.Graphics.Minimap.TerrainBitmap(TileSet tileset, Map map, Boolean actualSize) in d:\Projekte\OpenRA\OpenRA.Game\Graphics\Minimap.cs:Zeile 55.
   bei OpenRA.Graphics.Minimap.RenderMapPreview(TileSet tileset, Map map, Ruleset resourceRules, Boolean actualSize) in d:\Projekte\OpenRA\OpenRA.Game\Graphics\Minimap.cs:Zeile 144.
   bei OpenRA.MapCache.LoadAsyncInternal() in d:\Projekte\OpenRA\OpenRA.Game\Map\MapCache.cs:Zeile 175.
   bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()
```

**Comment by LipkeGu** [comment]
set the map bounds to something crazy... 1,1,10000,10000 for example on a 128x128 map ... :/

**Comment by pchote** [comment]
The recent map refactoring fixed the startup crash when any map had a bogus MapSize.  It will still crash if you try to load a map with a bogus size, but that is caught by the lint tests and isn't really different to other map corruption crashes.
