### ISSUE TITLE
Walls are too strong

### ISSUE THREAD

**Issue by StexoO** [OpenRA/OpenRA#6559]
If a player builds a bunch of walls (with some anti-air or artillery behind), he can block the game forever.
He spends around 1000 $ to build his walls, my 2500 $ nuclear missile (after have waited 9 mins) destroys only five of his walls, and he can rebuild them in 3 s for 100 $.
Even a mammoth tank needs to shoot at it 8 or 9 times during almost 30 seconds to destroy a wall. 3 seconds later, the wall is back.
It's frustrating to see a player hidden and idle behind his walls when you have a very heavy firepower in front of these walls, shooting at them during minutes and minutes (even with nuclear missiles or nuke trucks) and seeing this player always rebuilding them every 3 s, indefinitely.
Some games are stuck because of that.

![sans titre](https://cloud.githubusercontent.com/assets/8930382/4425042/7e024938-45a5-11e4-979b-de75bc00e794.png)

Weaken walls or add an option to disable them ?

**Comment by pchote** [comment]
This ticket is a bit too general to act on (no specific requests), and this has sat stale for over a year, so closing.
