### ISSUE TITLE
D2K - Gun and Rocket Turret Build Anims

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#6578]
They have build anim at normal d2k. But they haven't build anim at OpenRA.
##

**Comment by Unit158** [comment]
We should take another look at this now that the rendering traits have been refactored.

**Comment by pchote** [comment]
I wrote some commits which will be included with #9981 to separate wall connections from the wall rendering traits.  Once that has been merged it will be relatively easy to fix this.

**Comment by sorcerer86pt** [comment]
[rocket turrent](https://drive.google.com/file/d/1x-XtSTHZTjfSKeUzoH0nZbOljDXVylpg/view?usp=sharing
)
[silo](https://drive.google.com/file/d/1eN6GNRq7U_5kM-tgT2kAwAPSyQcYDVS5/view?usp=sharing
)

[gun torrent](https://drive.google.com/file/d/1Is85i0f2_uD8JWx4mv1dppj-2ZUG3Mey/view?usp=sharing)
