### ISSUE TITLE
[TS] The ts-packages.zip with Firestorm Content

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#6611]
https://github.com/LipkeGu/TSIniFiles/blob/master/ts-packages.zip
- The files (hva,shp,vxl,ini etc) which are in expand01.mix are in local.mix
- Contains the Firestorm TileSets + Marble Madness TileSets
- Contains the Firestorm Sounds (english)

Use this only for Development time because we have no install logic for Firestorm :/

**Comment by pchote** [comment]
Thanks for the link.  We know about your ts rules repo, and use it as a quick reference for checking the inis.  There's nothing actionable in this ticket, so closing.
