### ISSUE TITLE
"Explore" and "Search & destroy" orders

### ISSUE THREAD

**Issue by StexoO** [OpenRA/OpenRA#6618]
"Explore" could order the selected unit(s) to move randomly to unknown parts of the map (or with a predefined pattern) in order to discover the map without having to do it manually. 
"Search & destroy" could do the same thing as "Explore", but with an attack-move order, useful to quickly find the last hidden MCV on the map.

**Comment by pchote** [comment]
There are a lot of people who are strongly opposed to adding features that "make the game play itself for you", and I suspect this will fall under that.  I have no particular objection to this idea, but I don't see this as something that will be added so i'll close this.
