### ISSUE TITLE
"gg" as immediate capitulation

### ISSUE THREAD

**Issue by StexoO** [OpenRA/OpenRA#6619]
Not very important, but according to the conventional politeness in video games, such as "gl" for “good luck” or "hf" for “have fun”, "gg" (for “good game”) is used to end a game. It could be another way to capitulate if written in the chat, instead of going in the menu and selecting Surrender.
("gg" : https://www.youtube.com/watch?v=rQPTPiionxI&t=80m50s)

**Comment by HenrytheSlav** [comment]
I would go for /gg. I use gg when one of the players is defeated as an goodbye in response to his gg. :1: for either countdown and/or /gg command. But not for just gg.

**Comment by penev92** [comment]
This also turns it from a politeness to a "get me out of here" shortcut.

**Comment by HenrytheSlav** [comment]
True, but /surrender takes as much time as closing it by mouse. /gg is very fast.

**Comment by GraionDilach** [comment]
/gg is cryptic and sounds "pr0 elitist" to me with all the toxic it involves. :-1:

**Comment by abcdefg30** [comment]
You can type `/s` and then autocomplete with tab.

**Comment by penev92** [comment]
Not sure what the issue with the 1.5 seconds longer quit time, but autocomplete is there to save the day, apparently.
`/gg` would just introduce duplicate behavior and I don't think it's worth the extra code (even if only 2-3 lines).

**Comment by HenrytheSlav** [comment]
I didn't actually know about the autocomplete feature. I yield then.
