### ISSUE TITLE
Add SplitFacings option to various Render traits

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#6631]
The SplitFacings functionality of WithMuzzleFlash would be very useful on 
- RenderUnit 
- RenderInfantry 
- WithTurret 
- WithBarrel

Advantages:
- per-facing sequence Offsets, ZOffsets, Lengths, Tick rates and so on
- possibility of per-facing SHPs rather than a single monolithic SHP*

*would save me a TON (talking about weeks rather than days) of work on a high-profile project I'm working on

**Comment by pchote** [comment]
I have implemented this at the sequence level on my sequence-rework development branch.  It depends on several as-yet unmerged PRs, so it may be a while until it filters through to bleed...

The current syntax for an aggregate sequence (for the TD e4.muzzle) looks like:
```
	muzzle:
		Combine:
			flame-n:
				Length: *
				Offset: 1,6
			flame-nw:
				Length: *
				Offset: 8,7
			flame-w:
				Length: *
				Offset: 8,2
			flame-sw:
				Length: *
				Offset: 7,-2
			flame-s:
				Length: *
				Offset: 1,-2
			flame-se:
				Length: *
				Offset: -5,-2
			flame-e:
				Length: *
				Offset: -7,2
			flame-ne:
				Length: *
				Offset: -7,8
		Facings: 8
		Length: 13
```

**Comment by reaperrr** [comment]
Would it be possible (or is it already possible) to define Defaults for the sub-sequences too, so that in your example ```Length: *```would only need to be defined once? That would save quite some space on actors where this approach is taken for multiple sequences like body, turret and muzzle and which have 32 facings.

**Comment by reaperrr** [comment]
Adressed by #9547.
