### ISSUE TITLE
When an infantry unit transforms the other infantry unit appears in the middle of the cell

### ISSUE THREAD

**Issue by Angusm3** [OpenRA/OpenRA#6639]
I've got a sniper that deploys into a prone sniper, if he's not in the center of the cell when he deploys into his prone unit, the prone version will appear in the center of the cell, same with transforming back, so I assume there's nothing to tell where a transforming unit is within a cell, but I know it's in there as I've seen commands concerning pinpoint cell location in the lua files.

**Comment by pchote** [comment]
This can now be done using upgrades instead of `Transforms`.  Refer to the d2k thumper as an example.
