### ISSUE TITLE
Add a trait that gives out ammo/health to units in the vicinity.

### ISSUE THREAD

**Issue by scskwirl** [OpenRA/OpenRA#6661]
A trait that has a radius or a deploy target for other units, so they can get health recovered or limited ammo supplies replenished.

Optionally, include an effect where it uses pips and counts each pip as a "supply" that gives health or ammo, and needs to be restocked at the service depot.
##

**Comment by reaperrr** [comment]
>  We don't have anything similar for reloading.

This will be solved once my AmmoPool reloading refactor is complete.

**Comment by MustaphaTR** [comment]
This can be closed now. ReloadAmmoPool trait now allows ammo to be given in the way Pchote described above.
