### ISSUE TITLE
Rush the replay page at OpenRA Resource Center [$10]

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#6669]
By God I miss the old replay resource site. I know our beloved developers are doing their best to get the new replay page up at OpenRA Resource Center http://resource.openra.net/replays up and running ASAP but I'd rather see this finished sooner rather than later. Posting and downloading replays is just so damn FUN and I'm sure, a great asset to a thriving player base. Here's a small incentive for it's completion (bounty).

**Comment by Mailaender** [comment]
We did all we can do client side. https://github.com/OpenRA/OpenRA/pull/7458 This now needs to get tied up to the web interface: https://github.com/OpenRA/OpenRA-Resources/issues/253.

**Comment by Mailaender** [comment]
There is now http://www.gamereplays.org/openra/portals.php?show=news&news_id=965839 If that does not satisfy you, I suggest you revoke the bounty. Otherwise @pchote should probably claim it as he did the work in #7458.

**Comment by pchote** [comment]
@Mailaender: You did the work that actually solved the issue, so you're welcome to the bounty if @SoScared is happy with our solution.
