### ISSUE TITLE
AI doesn't check bounds before deploying

### ISSUE THREAD

**Issue by StexoO** [OpenRA/OpenRA#6683]
![mcvroom](https://cloud.githubusercontent.com/assets/8930382/4519257/1034196a-4cb5-11e4-8dee-2aa85527e08b.png)

**Comment by StexoO** [comment]
The AI is also able to deploy its construction yard out of the bounds of the map by one cell (the MCV is in the map).

**Comment by StexoO** [comment]
Just found two lost screenshots.
![ai chmod777_ 1](https://cloud.githubusercontent.com/assets/8930382/8553775/0059dfca-24e6-11e5-9498-d92b91ec2c11.png)
![ai chmod777_2](https://cloud.githubusercontent.com/assets/8930382/8553776/0245edec-24e6-11e5-917f-391b3c57b1f5.png)

**Comment by Basti504** [comment]
This is not just only possible for AI (Release 20150919, RA mod). 

When you queue a deploy command on a moving MCV it will validate the deploy command on the actual position (when you queue the deploy command) while the MCV is still moving. When the MCV is at the end of the move, it deploys regardless of anything in the surrouding cells. Yes, ANYTHING (actors,terrain), try it. In fact, the cell the MCV is standing on at the end of movement is ignored if it is not buildable/deployable normally.

I would think that when the actual deploy is executed, the position of the MCV and its surroundings should be checked again, regardless the owner is AI or not.
