### ISSUE TITLE
If a bridge becomes damaged under a unit, it is no longer possible to move the unit [$25]

### ISSUE THREAD

**Issue by StexoO** [OpenRA/OpenRA#6684]
A grenade damaged the bridge under the four guys (they were there before receiving the grenade), I can no longer move them. Happens with vehicles too.
![stuck](https://cloud.githubusercontent.com/assets/8930382/4519266/59fe9f16-4cb5-11e4-8a41-bfd5ef20ddd4.png)

**Comment by pchote** [comment]
Confirmed that this is still an issue on playtest-20151114

**Comment by Codes4Fun** [comment]
I created a [fix](https://github.com/OpenRA/OpenRA/pull/10728) for [7539](https://github.com/OpenRA/OpenRA/issues/7539), and after reproducing this issue, and testing it against my change the issue doesn't happen anymore.
