### ISSUE TITLE
Radiated ground after any given effect.

### ISSUE THREAD

**Issue by scskwirl** [OpenRA/OpenRA#6709]
Make a way to radiate terrain tiles with an ominous glow with a programmable RGB color effect, and a consequential effect for keeping a unit in there too long.

Example, ion cannon can leave a red glow for a very hot terrain that will burn up a unit. nuclear missile can leave a red glow for a poisoned terrain that should melt the unit.

**Comment by pchote** [comment]
Duplicate of #3605.
