### ISSUE TITLE
Tiberian Sun CD - setup.mix

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#6721]
i buyed Tiberian Sun German CDs with Firestorm and i found a Directory named "Setup" which contains a Setup.mix which also contains:

- Bitmaps
- Setup background music
- some sound effects
- fnt files
- palettes
- shp files

![ts_setup mix](https://cloud.githubusercontent.com/assets/2057932/4573848/8efe2720-4f96-11e4-94ab-dd3fa49d80dc.png)

i can upload the content for further research maybe we can take use of this content :)

https://github.com/LipkeGu/TSIniFiles/blob/master/ts_setup.zip

**Comment by Mailaender** [comment]
None of that is currently used and it never can be as the installer can't depend on the stuff it is about to install.

**Comment by penev92** [comment]
I don't get the "we won't use those assets" thing. Why? We should make the most of the assets the original games provide.

**Comment by Mailaender** [comment]
I am more like cleaning the bug tracker. This is something that could be stored at https://github.com/OpenRA/OpenRA/wiki but this is not really explaining something that could be fixed.

**Comment by pchote** [comment]
The long term plan is to do all installation via the mod-chooser anyway.
