### ISSUE TITLE
Unified directory/namespace layout

### ISSUE THREAD

**Issue by atlimit8** [OpenRA/OpenRA#6735]
Before OpenRA.Mods.Common gets too far, a standard layout of directories and namespaces should be created to (eventually) organize all mods including external ones. 
Obviously, namespaces will be the same as the directory paths with `.` instead.

Option 1 - based largely on current OpenRa.Mods.* & OpenRA.Game:
 * Activities
 * AI
 * Commands
 * Effects
 * FileFormats
 * FileSystem
 * GameRules
 * Graphics
 * Lint
 * Orders
 * Player
 * Primatives
 * Render
  * Modifiers
 * Scripting
  * Global
  * Properties
   * Player
   * World
 * Server(Traits)
 * SpriteLoaders
 * SupportPowers
 * Traits
 * UtilityCommands
 * Warheads
 * Widgets
  * Logic
 * World(Traits)

Option 2:
 * Commands
 * FileFormats
 * FileSystem
 * GameRules
 * Graphics
 * Lint
 * Primatives
 * SpriteLoaders
 * UtilityCommands
 * Widgets (main widgets for mod)
  * Logic
 * &lt;Category&gt; - grouped by functionality, usually in a separate namespace. &lt;Category&gt; must not be one of the above.
  * Activities
  * AI
  * Effects
  * Interfaces.cs - or -
  * Interfaces
    * Traits.cs
    * &lt;Sub-category&gt;.cs
  * Orders
  * Render
    * Modifiers  - or - just RenderModifiers
  * Scripting
    * Global - Lua globals (not a namespace)
    * Properties - Actor script properties (not a namespace)
      * Player - for the `Player` actor (not a namespace)
      * World - for the `World` actor (not a namespace)
  * SupportPowers
  * Traits
    * Player (not a namespace)
    * World (not a namespace)
  * Warheads
  * Widgets
    * Logic
Category names should agree between mods based on functionality.

**Comment by penev92** [comment]
Does anyone remember where the "specific" vs "big" namespaces discussion happened? I want to pick that up again, but I can't remember where it was.

**Comment by reaperrr** [comment]
#7036.

**Comment by penev92** [comment]
Thanks @reaperrr, but I already got shut down on IRC, so ... never mind.

**Comment by Phrohdoh** [comment]
Can this be closed?

**Comment by penev92** [comment]
Yeah, I guess so.
