### ISSUE TITLE
Allow adding multiple infantry units on same block and display them in formation?

### ISSUE THREAD

**Issue by VagueVigor** [OpenRA/OpenRA#6771]
Currently you can only place 1 infantry unit per one block. It's a bit silly looking if you want to place many infantry units on the map.

Wouldn't it be cool if you could add 5 in one block and the game would render them as they would be rendered normally when many infantry units are in same block?

Here could be suggested formations for all 5 amounts:

1:
```
   
  x 
   
```

2:
```
x   
   
   x
```

3:
```
x   
  x 
    x
```

4:
```
x   x
   
x   x
```

5:
```
x   x
  x 
x   x
```

**Comment by Mailaender** [comment]
I just added sub cell awareness to https://github.com/OpenRA/OpenRA/pull/4496.

**Comment by pchote** [comment]
All these tickets should be referenced from #4496's description so that they can be closed (only) once it is finally merged.
