### ISSUE TITLE
WSA file format support

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#6781]
Instead of the laborious workaround to create static splash screens https://github.com/OpenRA/OpenRA/wiki/Mapping#creating-previews-from-the-td-campaign-maps we could add support for http://dune2.ben.savoch.net/formats/wsa/ and play that animation in the mission select window. That will also keep our source code repository clean from binary files and make the release download smaller again.
##

**Comment by pchote** [comment]
Implemented in https://github.com/OpenRA/d2/blob/master/OpenRA.Mods.D2/SpriteLoaders/WsaD2Loader.cs for D2.  It may require some compatibility tweaks for the later games.

**Comment by Mailaender** [comment]
http://www.shikadi.net/moddingwiki/Westwood_WSA_Format is a good resource.
