### ISSUE TITLE
Add support for rectangular hitboxes [$100]

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#6820]
The health radius is suboptimal for visually rectangular and/or long units (tanks, ships, some buildings). While it might complicate the damage calculations compared to a simple radius, it would allow for hitboxes matching the visual shape, and might even be a first step towards directional armor.

**Comment by huwpascoe** [comment]
I'm taking on this issue as discussed in irc. I've decided on
Radius for infantry
Axis-aligned rectangle for structures
Capsule (line segment with radius) for vehicles
Polygons which I can't honestly find a good use case for but am including them anyway.

Will deliver a PR soon.

**Comment by pchote** [comment]
The polygon (note: we already have helper functions for polygon intersection testing) covers the vehicle and structure case, so you could avoid some work and duplication.

**Comment by TheRaffy** [comment]
Is this related to any melee attack`?

**Comment by huwpascoe** [comment]
PRs merged. I claim this bounty!

**Comment by pchote** [comment]
Unfortunately this broke our unit tests #10325.
