### ISSUE TITLE
Snipers hidden depending on their environment

### ISSUE THREAD

**Issue by StexoO** [OpenRA/OpenRA#6828]
Snipers could be always visible if they are in the middle of nowhere, like in the center of a desert plain, and become cloaked if they are near some trees (for example). So the environment would have an impact on the gameplay (and on map creation) instead of being simply walkable/non-walkable areas.

**Comment by Phrohdoh** [comment]
#7794 renders the RA Sniper unit unbuildable.

**Comment by pchote** [comment]
Snipers have been removed from the RA mod, so this is no longer necessary.
