### ISSUE TITLE
Smudges have tendency to be spawned on the cell south of impact

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#6840]
Particularly noticeable in TS, because "south" means the cell south-west of the impact in this case.

Might actually be an issue with `Inaccuracy`, though.
##

**Comment by GraionDilach** [comment]
Cannot reproduce this in current bleed. Do this bug still exist?

**Comment by reaperrr** [comment]
Can't reproduce it anymore, either.
