### ISSUE TITLE
Bundled thirdparty

### ISSUE THREAD

**Issue by rapgro** [OpenRA/OpenRA#6863]
Please provide build instructions for all the 3rdparty libraries etc.

In Fedora, distribution of prebuilt assemblies is not allowed. All has to be based on available sources, also for legal reasons.
https://fedoraproject.org/wiki/Packaging:Mono?rd=Packaging/Mono#Distributing_Prebuilt_Assemblies

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/issues/7346 removes the `thirdparty/windows` directory. Now only Mac binaries are left.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/7479 will remove the last Windows binary from the source tarball.

**Comment by Mailaender** [comment]
This is not yet resolved completely.
