### ISSUE TITLE
Video Game Trailer - Post-Halloween Release

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#6891]
I had a positive experience from a thread on Github that was about planning the preview video for the June release. Ideas, scripts and feedback was gathered onto one place which enabled me to complete a decent video in about 2-3 weeks. So why not do this again, only this time there is no real deadline and the sky's the limit :)

I've already begun working on a new trailer video - basically an improvement of the previous one made back in february. However, with a recent reply on a thread of mine on Sleipnir I was intrigued to explore alterations that could mean a more radical change from my original idea of a remake: http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&p=287914#287914

Any suggestions or comments on this trailer will be taken into account - everything from broad ideas and visions to small nit-pickings of the finest details along the way. I will post updates on the project's status when necessary and visit this issue frequently to make sure I'm not missing anything.

**Comment by SoScared** [comment]
I'm confident the video will be ready sometime in the summer, hopefully together with the next release date. I got the effects and scenes almost ready and I'm currently gathering gameplay footage from the latest playtest.

I'm sparse about sharing results but here's a peak of the draft and foundation for the first 10 seconds from work done this winter (video unlisted on youtube, please don't share link on other public forums): https://www.youtube.com/watch?v=pFFJYGiBIkc

**Comment by Phrohdoh** [comment]
@SoScared The video looks nicely polished and entertaining so far!
One nit I have is at 0:16 you have `Open Red Alert` at the bottom left of the screen when in fact the engine supports much more than Red Alert and is named `OpenRA`.

**Comment by SoScared** [comment]
@Phrohdoh OpenRA will be the title coming up at the start. I was thinking of cycling through the titles Open Red Alert, D2k, Open TD etc. but that might come off as confusing.

**Comment by Mailaender** [comment]
Could be confused with https://github.com/damiencarol/openredalert.

**Comment by penev92** [comment]
Any progress here, @SoScared ?

**Comment by SoScared** [comment]
Been picking up the work lately after a long brake. Think I'll have it ready by August-September.

**Comment by penev92** [comment]
Would be great if we can time it for the mid-August tournament, or a release (which I imagine would come by the end of August). :)

**Comment by SoScared** [comment]
Need help with a new opening scene.

The first gameplay scene after the intro bit starts from the widest possible perspective and moves into the action. The new 'disable UI in-game' option intrigued me to change the opener.

example:
![bloggif_55c6907e10fc3](https://cloud.githubusercontent.com/assets/2715583/9152839/9916fa38-3e39-11e5-992d-6c77d6607de1.gif)

Nukes are overkill as an opener:D I need another player to act on one side on a simple classical red alert battle - attacking Soviet forces on an Allied base. Setting everything up with the Debug Menu. The final cut will only be a short intersection of the action, no more than about 3 seconds long, but it will be the viewer's first encounter with OpenRA's gameplay footage. I'll record everything from the replay viewer at a later time so don't worry about screwing up.

Anyways, here is the set-up:

playtest20150808
map: Chaos Canyon

I'll play Allied in panic mode:)
![allied base info](https://cloud.githubusercontent.com/assets/2715583/9152894/09a25674-3e3c-11e5-98a5-0ffde29509af.png)

You'll have fun attacking as Soviet. Looks complicated but is really simple:
![soviet narrow info](https://cloud.githubusercontent.com/assets/2715583/9152895/0bbca36a-3e3c-11e5-842e-c94ca108f17a.png)

Timing is easy, the Soviet attack will cue the Allied staged movement. Just use control groups.

![soviet wide info](https://cloud.githubusercontent.com/assets/2715583/9152896/10846888-3e3c-11e5-86f9-08facf588273.png)

**Comment by SoScared** [comment]
Just give me a signal on IRC and we can get started:D

**Comment by SoScared** [comment]
It's surely gonna take a while longer than expected but quality is getting there.

Have a preview: https://www.dropbox.com/s/8mtgnhii5116anf/Produced_14.mp4?dl=0

(download for better quality)

**Comment by TheRaffy** [comment]
wow.. that was unexpected skill.

**Comment by pchote** [comment]
Looks good so far, but I have a couple of important requests:
* Please change Open Red Alert to OpenRA. "Open Red Alert" is a completely different project to OpenRA.
* The transition from the Westwood Studios logo to "Open Sourced!" gives the impression that we have opensourced the original code.  Please change this to something like "Remade and open source"

**Comment by SoScared** [comment]
As mailander pointed out on IRC, I need to check with EA/Westwood studios if I can use their trademark like this. Already got permission from Klepacki for the track so I'm hopeful to get a reply on a request.

Didn't know about 'Open Red Alert' as a different project. Easy fix.

I could change the running opening titles to something like: 1) Open Sourced 2) Remade 3) OpenRA and start the RA mod sequence with simply 'Red Alert'

The start of the Rick Roll replaced the start of the D2K sequence.

**Comment by pchote** [comment]
We're now converging quickly on our December/Christmas/Holiday release.  I guess that we're not going to be able to get this done in time now?

**Comment by SoScared** [comment]
No. The sad truth is that I've neglected to work on this consistently and to this date has a lot left to be done before the video can be published. The main issue is that I'm using a lot of experimental effects that I'm still learning to use properly (wanting it to look as professional as possible). I'm soon done with an exam and with some other non-related projects in December so I expect to pick up the pace soon, but unfortunately it looks highly unlikely to have it finished with the next release.

**Comment by Mailaender** [comment]
Closing this to relieve you of the pressure and clean up our bug tracker.

**Comment by Mailaender** [comment]
I thought about making a trailer series by reading out http://www.openra.net/about/ maybe with 4 videos (1 for the engine and 3 others per mod) and with an enforced pronunciation of the words highlighted in red by @pchote in the style of the Act of Agression faction gameplay trailers:

* https://www.youtube.com/watch?v=uFjOZMpJGaw
* https://www.youtube.com/watch?v=UXCRk84A1WQ
* https://www.youtube.com/watch?v=3-_VFnLAaak

but I neither have the video editing skills nor the epic trailer voice to make it sound cool.
