### ISSUE TITLE
choppy gameplay

### ISSUE THREAD

**Issue by gpolitis** [OpenRA/OpenRA#6923]
I'm experiencing choppy gameplay when I play against the AI (skirmish). I've never played a network game, so I can't tell if happens there as well. It happens in every single game I play. It happens with both bleed and master branches. It's very, very noticable. I don't think it's a hardware problem as I have a relatively high end system build (Intel Core i7-4578 Haswell, 16GB RAM, SSD).

Do you guys have any idea what could be the cause of this? If I know what I'm looking for (approximatelly), I may be able to dig deeper into it.

**Comment by Mailaender** [comment]
Closing as it seems to be out of our hands and we don't have enough information to investigate further.
