### ISSUE TITLE
Water Mine Layer ... how it works and how to balance

### ISSUE THREAD

**Issue by Seradest** [OpenRA/OpenRA#6952]
Simple Idea for RA 1

Owner: Allies, Soviets
Cost: $900 

A slow small ship used by both sides to lay Watermines. Allies and Soviets use it to lay anti-ship mines.
It is slow and has no weapons to directly combat enemy units.
He can ship 3 Mines maximum
and they cannot be seen and can only be resupplied by using the Sub Pen or Naval Yard.
Resupplying cost credits.
An Mine has an Range attack of 9 cells,stronger in the middle than at the border.

**Comment by TheRaffy** [comment]
That's a nice idea and I really like the unarmed mine layer ship idea and think i saw somewhere a water mine asset in the asset browser. 
But I'm also not a fan of that 9 cell detonation suggestion -> 1 cell should be enough. The damage should enough to one hit a gunship, but not the other water units in my opinion.
And why should they cost something, when other mines are free that doesn't make a sense in my head, and would be extra work. Mines 4 free!

I don't know what the naval imbalance is. Maybe that allies can reach all places with chrono, where soviets only have narwhals? and some islands doesn't have beaches?

**Comment by pchote** [comment]
This is out of scope for our default RA mod, but could be done in a custom map or a third party mod.
