### ISSUE TITLE
Silo's needed alert goes of way too often

### ISSUE THREAD

**Issue by chriseilander** [OpenRA/OpenRA#6955]
I don't know at which point the originals started nagging about building silo's, but I think that due the increased gameplay speed of openra, the "silo's needed" alert goes of way too often.

I did see some nice ideas from https://github.com/OpenRA/OpenRA/issues/3816 that wouldn't have the need for this alert, and changing the mechanic of the silo's completely. I can live with that.

**Comment by colonelpopcorn** [comment]
Is this something we should surface in the options menu? This sounds more like a preference that should be able to be tweaked by each individual user.
