### ISSUE TITLE
Found bug i think,the AI in RA has problems of stuck at the edge of the map...

### ISSUE THREAD

**Issue by Seradest** [OpenRA/OpenRA#6961]
when you play an map an start at the buttom and you build 2 factorys at the edge of the map.
then the ore trucks get stuck there because one of them want in and one of them want out.

to fix this.

1.make 1 cell at the edge of every map un-build-able but the units can walk/drive over it.
2.Make the pathfinding so intelligent that the units know there is no other way and drive back to an place who is more space to drive around the other vehicle. 
##

**Comment by abcdefg30** [comment]
Harvesters getting stuck is probably resolved by #16408 and related PRs.
