### ISSUE TITLE
Recreate D2k Saboteur Power

### ISSUE THREAD

**Issue by OmegaBolt** [OpenRA/OpenRA#6976]
In Dune 2000 the Ordos Palace had a support power whereby it would charge up -> you click the icon -> it releases the Saboteur from the Palace.

This is also used for the Fremen power given to the Atreides so I suggest the following things should at least be editable:

-Type of units to create
-Building to spawn from
-Number of units to create
-Recharge time

Multiple copies of the building just speed up the recharge too, so this could be an option (whether to increase charge speed or provide multiple copies of the power).

**Comment by Mailaender** [comment]
We have a https://github.com/OpenRA/OpenRA/wiki/Traits#spawnactorpower for quite some time now.

**Comment by GraionDilach** [comment]
That's not really the same, this should be a ProductionPower instead (along with TS HunterSeeker).

**Comment by pchote** [comment]
This has now been implemented.
