### ISSUE TITLE
DefaultCash property ignored if 5000 is selectable choice

### ISSUE THREAD

**Issue by OmegaBolt** [OpenRA/OpenRA#6977]
Example code:
	PlayerResources:
		SelectableCash: 2500, 5000, 7000, 10000
		DefaultCash: 7000
		AdviceInterval: 650

As long as 5000 is a choice in SelectableCash then 5000 will be used regardless of DefaultCash. If you remove the SelectableCash option of 5000 then it will use the correct DefaultCash.

EDIT: Also if the DefaultCash is not 5000 it gives an immediate chat notification that you have set the credits to DefaultCash, despite it being... default.

**Comment by GraionDilach** [comment]
This is fixed now.
