### ISSUE TITLE
Humvee and Buggies damage

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#6981]
The damage modifiers of these two units do way to much vs armored. Did a game in 1v1 and 2v2 where they are able to destroy Harvestors pretty quickly along with buildings.

The humvees were able to destroy APCs relatively quickly aswell as light tanks. 

Its possible that they do a seemingly large amount of damage is because of their five shot burst fire. But if that is reduced to a single fire like in CNC95 that may present issues vs infantry. Since the infantry were improved in their range vs humvees and buggies to prevent range kiting. 

If its possible to have their armor vs damage reduced.

EDIT: Maybe a reduction to 15%.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/8303 has been merged.
