### ISSUE TITLE
Bib is not drawn if the attached building itself is completely offscreen, but bib is not.

### ISSUE THREAD

**Issue by chrisforbes** [OpenRA/OpenRA#6987]
##

**Comment by sinf** [comment]
I'll just put this here because it is relevant and you can see how distracting it is:
![pop20](https://cloud.githubusercontent.com/assets/9487531/7542939/6ade2cb2-f5c9-11e4-9a63-215820c58e1a.gif)

**Comment by reaperrr** [comment]
I'll try to fix this before the next release.
