### ISSUE TITLE
Vehicles can't move to nearby walled tile

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#6989]
![wallblocker](https://cloud.githubusercontent.com/assets/7704140/5155707/e989d1f0-7294-11e4-82c1-756296fe98a9.png)
This unit won't drive in there (tile right to the tank) if you give the move order right now.

**Comment by abcdefg30** [comment]
This issue is back.

**Comment by rob-v** [comment]
Fixed by #13321 ?

**Comment by pchote** [comment]
Fixed by #15339.
