### ISSUE TITLE
The new Prerequisites implementation - please bring back the Owner: trait.

### ISSUE THREAD

**Issue by kaneCVR** [OpenRA/OpenRA#6992]
Hi guys. I've been having a really tough time with the current Prerequisites implementation. Assigning the same unit to 2 or 3 out of four sides (my mod Tiberian Origins has 4 sides) is quite difficult now that the Owner trait is defunct. To get my mod working again, I've had to clone a lot of buildings just to be able to assign certain units to a specific race. For example - 3 out of 4 sides can build a helipad. Allies have HPAD, and GDI and NOD have GPAD (CnC .shp). The allies have the Apache helicopter, GDI has the Orca, and NOD has the Banshee gunship (RA hind.shp). For me to be able to assign these units to just one side, I had to code 3 helipad buildings (HPAD, GPAD and NPAD), otherwise there is no way to make individual aircraft available to one side only buildable trough the same structure.

The above mentioned is just an example... assigning units and structures for single player missions is even harder - I have to code almost the entire rules file in the mission.yaml! My mod has missions in witch you can build the RA war factory, and later the GDI war factory / NOD airstrip as the game progresses. Previously, i just needed to put the Owner trait in the mission's yaml for what you can and can't build / who can build it - but with the current system it's very hard.

T;L DNR - PLEASE BRING BACK THE OWNER: TRAIT!

**Comment by Mailaender** [comment]
Closing as we now have https://github.com/OpenRA/OpenRA/wiki/Tech-levels-and-Prerequisites.
