### ISSUE TITLE
AI doesn't build MCVs to expand it's base

### ISSUE THREAD

**Issue by StexoO** [OpenRA/OpenRA#7007]
MCVs have their own AI (moving around and deploying), so the AI could build up to 5-6 MCVs randomly (not if it has 5-6 construction yards) in order to get better building speed, map control, nuke/Tanya prevention, ...

**Comment by Mailaender** [comment]
While testing https://github.com/OpenRA/OpenRA/pull/7644 I saw an AI bot get his Construction Yard trashed, build a new MCV and moved that one towards the enemy base to deploy. We may simply let it build an MCV every now and then.

**Comment by pchote** [comment]
The ai now does this, and particularly loves doing so in D2K now.
