### ISSUE TITLE
Ranked MCV loses its rank when deployed

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#7021]
![ranked mcv](https://cloud.githubusercontent.com/assets/8930382/5220729/ce6f2888-7669-11e4-92ff-a1ffea2ec603.png) -> ![unranked const yard](https://cloud.githubusercontent.com/assets/8930382/5220730/ce71ae6e-7669-11e4-9aa3-f6070b21a1a5.png) -> ![unranked mcv](https://cloud.githubusercontent.com/assets/8930382/5220731/ce725daa-7669-11e4-9348-4057896778cb.png)
##

**Comment by Smittytron** [comment]
> The real bug is that the MCV can collect level-up crates. The other mods specifically disable this for MCVs.

Looks like `–GainsExperience` to the MCV can fix this. Depending how far you want to take this, it can be added to harvesters and possibly other non-combat vehicles as well. 

TD has Gains Experience applied to individual vehicles sans the MCV and harvester, while RA has xp under `^Vehicles`.

Expanding this even further; GainsExperience can be moved to `^Vehicles` in TD to bring it in-line with the other mods and cut some lines of .yaml.

I’m up for tackling this with some direction on how far to go.

**Comment by pchote** [comment]
Having the individual vehicles inherit only the behaviours they need is the proper approach.  Having monolithic inheritance and then trying to undo things is fragile and bad style.

**Comment by Smittytron** [comment]
So make RA like TD on this one?

**Comment by pchote** [comment]
Yeah.  In most cases where RA and TD differ, the TD approach is better.
