### ISSUE TITLE
Ore trucks don't go back to work after have been repaired

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#7025]
Could they be sent automatically to the nearest ore path ?

![repaired truck](https://cloud.githubusercontent.com/assets/8930382/5220990/b1758168-766f-11e4-9fc0-921d2721bb90.png)
##

**Comment by abcdefg30** [comment]
Queueing a harvest order as follow-up to a repair is possible nowadays, and harvesters going off on their own after an explicit (repair) order is likely not desired.
