### ISSUE TITLE
Unable to know who is defeated when several players have the same name

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#7027]
Could you attribute numbers to AIs (like their slot number) or keep the players' color in debug messages ?

![who is defeated](https://cloud.githubusercontent.com/assets/8930382/5221118/af2a2de8-7672-11e4-8f0f-37c445e6939c.png)
##

**Comment by HenrytheSlav** [comment]
I think it would be ideal to show just Name in color, however, we should solve #7592 first to make it always readable.

**Comment by rob-v** [comment]
PR  #13232
