### ISSUE TITLE
Use upgrades to untangle implicit Building trait dependencies

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#7035]
A number of traits include workarounds to disable their functionality until the building make animation has completed.  These all require querying the Building trait, and many of them do it without properly accounting for the trait construct order which causes them to break if the order that the traits are specified in the yaml is changed.

We can now use @atlimit8's new upgrade/disabled trait system to replace these hardcoded hacks:
1. Introduce a new trait that implements `INotifyBuildComplete` and grants an upgrade when the construction is complete / revokes the upgrade before selling.
2. Set `UpgradeMinEnabledLevel` for the traits that should only be enabled once the construction is complete. 
##

**Comment by reaperrr** [comment]
Note to anyone who might take this on (including myself):
The way #9124 implements the deploy animation looks like a good example of how to do this.

**Comment by reaperrr** [comment]
We should try to get this into Next+1, as this is a prerequisite to fix some long-standing issues.

**Comment by pchote** [comment]
We now have support for granting a condition while the make animation plays (`WithMakeAnimation.Condition`), so we now just need to adapt the mod rules and fix any traits that work with `INotifyBuildComplete` but not conditions.

**Comment by pchote** [comment]
There are now only 4 places left that do this - we should aim to finish cleaning this up alongside the building lock code
