### ISSUE TITLE
Starting RA menu bug.

### ISSUE THREAD

**Issue by TSnake41** [OpenRA/OpenRA#7041]
Sometimes, when I go to the menu of RA I have the replay of Shell Map played.

**Comment by abcdefg30** [comment]
What's the status here? Are you still able to reproduce this @TSnake41?

**Comment by TSnake41** [comment]
Now, I have update this game (to release-20141029) and thats reproduces when I have launch then. I don't know when this reproduces because it's random but very often.

**Comment by obrakmann** [comment]
Can you check if it still occurs for you with the latest playtest (playtest-20150408)? Thanks!

Note: if you want to go back to release-20141029 after testing this, you should probably make a backup of your maps folder (Documents/OpenRA/maps in Windows) if you have any custom maps.

**Comment by TSnake41** [comment]
At the moment, after test the lastest playtest, I didn't have this problem at the start.
