### ISSUE TITLE
OpenRA.Editor.exe loads nothing

### ISSUE THREAD

**Issue by TehRoast** [OpenRA/OpenRA#7044]
Every time I try to load the editor nothing happens. No screen loads, no message saying it failed to run, the only thing that happens is a slight instance where the program icon flickers the same way all program icons do before a window is opened. I tried running as administrator and still the same issues happens. I then tried to test compatibility under multiple different settings and still nothing happens. It's as though the editor was just an empty icon to click on... Is there a special program I need to install? The game runs just fine. I would like to make my own maps to play with and share.

 I'm running a stock Dell with an Intel Core i5-4440 CPU @ 3.10 GHz RAM 12 GB with a 64-bit OpSys, x64-based processor running Widows 8.1

I can't begin to fathom how a program that's so seemingly antiquated could be so incompatible and yet it's counterpart could run so smoothly.

**Comment by pchote** [comment]
This has been fixed by the new editor.
