### ISSUE TITLE
Command-line arguments and some sort of "URI scheme" ?

### ISSUE THREAD

**Issue by StexoO** [OpenRA/OpenRA#7058]
It's an Idea/Feature.
The short idea is to be able to join an OpenRA server from anywhere outside OpenRA, like adding a Join button in front of every game listed on http://www.openra.net/games/.
The long idea is to be able to create links like _openra://123.123.123.123:1234_ (I don't know if it really has a connection with http://en.wikipedia.org/wiki/URI_scheme, I never investigated it) which would be interpreted by the operating systems into something like _openra.exe -connect 123.123.123.123:1234_.

**Comment by pchote** [comment]
https://github.com/pchote/OpenRA/tree/new-osx-launcher (which I will PR during the next release cycle) implements this for OS X.

**Comment by Mailaender** [comment]
I submitted https://github.com/OpenRA/OpenRA/pull/7934 but could not yet get it to work. Doing like Steam and Hedgewars does it according to the FreeDesktop specs. Not sure what is going on.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/8208 does it for Windows.
