### ISSUE TITLE
Dog jumps up the hill

### ISSUE THREAD

**Issue by zstyblik** [OpenRA/OpenRA#7077]
I guess this shouldn't be possible, but dog jumped up this cliff and killed Tanya. :) Picture is from RA SP Allied mission 03a *Dead End*. There is a small unit stationed below this cliff with one dog.

![dog_bug](https://cloud.githubusercontent.com/assets/6183869/5327722/8e3b091c-7d5d-11e4-8052-c0d11731a99b.png)

**Comment by pevers** [comment]
This is reproducible and this is also happening with dogs jumping over walls.

**Comment by penev92** [comment]
It's not a feature. It's actually a well-known bug and I'm pretty sure there's an issue open for it.

**Comment by kyrylo** [comment]
Actually, it can be turned into a feature :) Ever heard of [Chitzkoi](http://cnc.wikia.com/wiki/Chitzkoi)?

**Comment by elegantandrogyne** [comment]
Easy to reproduce in Allied 05. Move your spy below the chainlink fence, wait for the doggies and see them jump over the fence.

**Comment by TheRaffy** [comment]
I like this, and it's easy to reproduce. The dog should be able to jump with the crl+left key like other units can fire on the ground or at bridges. that would boost the value of this unit a lot!!

**Comment by pchote** [comment]
Reverse-duplicate of #7506.
