### ISSUE TITLE
units don't stop shooting even when stance is changed and unit moved

### ISSUE THREAD

**Issue by zstyblik** [OpenRA/OpenRA#7086]
May be I'm doing something wrong here, but-

I've noticed this in RA SP mission _Monster Tank Madness_. Your units cross/come over the bridge and you have a small Soviet base to clear out, naval yard to cap(I think) and then move on.
- clear out soldiers and flame towers
- then order one of your tanks to start shooting at or get him within shooting of any building
- change stance to HoldFire
- yet the tank keeps on shooting
- move tank away from the building - you can tell he keeps on tracking his target
- move tank back close to the building, resp. withing firing range - firing resumes even though unit is in HoldFire stance
- unless of course stance is changed by moving unit around. Which probably isn't true, because cycling stance for given unit cycles stances in expected and continuous order where we left off
- once the building is capped, target is released

**EDIT:** actually being within shooting range is enough to trigger this. It also can be reproduced by placing target on the ground/map via CTRL. Once the target is acquired, unit won't give it up.
##

**Comment by pchote** [comment]
Our current `Attack*` setup gets in the way of resolving (2) without introducing nasty side-effects. 3860cacb615d7f7ac68ce8b26acb10762335fe62 basically works, but will cancel any other activities that might be active or queued.

To fix this, we really need to centralize the active target to a `Target` field on `AttackBase`.  The users of this field should then be smart enough to do whatever cleanup they need when this changes to `Target.Invalid`.

**Comment by matjaeck** [comment]
> There are really two distinct issues here, which are both different to #6170:

> 1. Turreted actors never cancel their target, even if you explicitly order them to stop.  This has been known for a while, but I couldn't find a ticket for it when I searched.

>  2. Units don't cancel their target when switching stances.  This is more controversial, and some people will argue that it is a feature not a bug.  I personally think that units should drop their target when going to a more restrictive stance (e.g. AttackAnything to HoldFire), but not in the other direction.

Nr. 1 has been fixed, Nr. 2 is also discussed in #8373.

**Comment by zstyblik** [comment]
> Nr. 1 has been fixed, Nr. 2 is also discussed in #8373.

Feel free to close this issue, if it's not relevant anymore or has been superseded. :)
