### ISSUE TITLE
"base under attack" not played when distant building is under attack

### ISSUE THREAD

**Issue by zstyblik** [OpenRA/OpenRA#7104]
I believe player should be notified when any of his buildings are being attacked, not just those which are in the vicinity of Construction Yard.

For example, on RA SP map _Intervention!_. You start on a small island, move to the mainland and leave some buildings behind. AI does para-drop on the islad a bit later and attacks buildings you've left behind, yet no sound is played nor notification on radar is shown about this.
##

**Comment by Smittytron** [comment]
Tested on some big maps, can't reproduce.
