### ISSUE TITLE
Random crash on openSUSE 13.2

### ISSUE THREAD

**Issue by ErcVitez** [OpenRA/OpenRA#7105]
Random ingame crash (sometimes even in menu), openSUSE 13.2 GNOME 3.14.
game repo and lutris version too.

exception.log:
Red Alert Mod at Version release-20141029
Operating System: Linux (Unix 3.16.6.2)
Runtime Version: Mono 3.8.0 (tarball Fri Oct 10 15:00:11 UTC 2014) CLR 4.0.30319.17020
Exception of type `System.NullReferenceException`: Object reference not set to an instance of an object
  at OpenRA.Server.Server.<Server>m__0 (System.Object _) [0x00000] in <filename unknown>:0 
  at System.Threading.Thread.StartInternal () [0x00000] in <filename unknown>:0

**Comment by Mailaender** [comment]
Sadly the recorded stack trace is far too short to be of much diagnostic use. You could try https://github.com/OpenRA/OpenRA/wiki/Compiling and running the latest development version to 1) check if it is already fixed and 2) run it with a debugger attached to identify what is null. Please reopen once this happens again and the exception.log is longer and exposes a bit more information.
