### ISSUE TITLE
not defined sound actor in yaml crash the map

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#7137]
What I want, is then no sound actor is defined (old maps), then standard is used.
This way we need to update less, and old maps could be played without needing hard to use update (comparing yaml's)

See also #7136

**Comment by Mailaender** [comment]
The crashes are done on purpose, because someone did not setup the rules properly: compare https://github.com/Mailaender/OpenRA/blob/lint-voices/OpenRA.Game/Sound/Sound.cs#L328. A lint rule is an excellent idea as these are easy to miss, so I added one: https://github.com/OpenRA/OpenRA/pull/8412.
