### ISSUE TITLE
Migrate to Open.NAT and replace Mono.Nat

### ISSUE THREAD

**Issue by rapgro** [OpenRA/OpenRA#7140]
The project Mono.Nat is nearly dead. 

Since mono-nat (respectively as the old name) is retired in Fedora and can not be wake up easily, I would like to know how far the plan is to migrate to Open.NAT as promised already in some other issue (number unkonwn?).

**Comment by rapgro** [comment]
The nterry fork has a build problem cause of automake failure.

Can you please provide a patch to disable / remove the anyhow b0rken mono-nat feature? As it turns out, this dependency is mostly needed to support XP users. Fedora should find another way to handle NAT issues, IMHO.

**Comment by Mailaender** [comment]
You can still use older Mono.Nat versions with OpenRA.

**Comment by pchote** [comment]
We discussed this again in IRC, and I suggested that we could modify OpenRA to (gracefully) disable the UPNP feature if the mono.nat dll isn't found.  This would be a straightforward way to work around Fedora's strict packaging restrictions that are blocking us from being packaged upstream.

**Comment by Mailaender** [comment]
Sure, but Mono.Nat is very easy to package: https://build.opensuse.org/package/show/openSUSE:Factory/mono-nat

**Comment by pchote** [comment]
Yep, but according to the earlier discussions the whole problem here is that Fedora won't accept dead/unmaintained libraries into their repositories.

**Comment by Mailaender** [comment]
FuzzyLogicLibrary is also "unmaintained". Eluant and SDL2-CS are both forked and the latter one is rolling release. Mono.Nat is the least problem with the actively developed https://github.com/nterry/Mono.Nat fork.

**Comment by rapgro** [comment]
No. This bug is about Mono.NAT / Open.NAT only.


From downstream (Fedora): https://bugzilla.redhat.com/show_bug.cgi?id=1166897#c7

As it turns out, the github tarball luckily includes LICENSE and AUTHORS. Unfortunately, this tarball does not provide any Makefile nor Makefile.in files, but Makefile.am only. I tried to tweak that somehow with autoreconf or automake, but without any success so far.

Please help to use automake properly. Otherwise, I would suggest to leave mono-nat as dead as it is ("to not wake up any bad zombie").

For reference, I'll upload the spec file without any claim to fix FTBFS.

https://raphgro.fedorapeople.org/review/mono/mono-nat/mono-nat.spec


Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.JMcPjo
+ umask 022
+ cd /home/build/rpmbuild/BUILD
+ cd Mono.Nat-Mono.Nat-1.1.0
+ pushd src
~/rpmbuild/BUILD/Mono.Nat-Mono.Nat-1.1.0/src ~/rpmbuild/BUILD/Mono.Nat-Mono.Nat-1.1.0
+ autoreconf -i
configure.ac:5: installing './install-sh'
configure.ac:5: installing './missing'
Makefile.include:65: error: 'pkglibdir' is not a legitimate directory for 'SCRIPTS'
Mono.Nat/Makefile.am:96:   'Makefile.include' included from here
autoreconf: automake failed with exit status: 1
error: Bad exit status from /var/tmp/rpm-tmp.JMcPjo (%build)

**Comment by Mailaender** [comment]
http://www.nuget.org/packages/Mono.Nat/1.1.3 states 

> Removed archaic makefile stuff

as a feature. I think you should not complain here, but instead send a pull request towards https://github.com/nterry/Mono.Nat to get autotools support back or compile with xbuild.

**Comment by rapgro** [comment]
The BoltEngine fork builds fine with xbuild. This issue can be considered as fixed.

**Comment by Mailaender** [comment]
> Er that is it's easy to port to 4.0 just resyntax like two lines of code

I just tried. Open.NAT seems to heavily rely on the [Task-based Asynchronous Pattern](https://msdn.microsoft.com/en-us/library/system.threading.tasks.task(v=vs.110).aspx) which is .NET 4.5 exclusive so this isn't easily done. At least for me.

**Comment by Mailaender** [comment]
We will also loose Fedora support (which is still on ancient Mono 2.10) by the way if we migrate to Open.NAT as the .NET 4.5 async support was added in http://www.mono-project.com/docs/about-mono/releases/3.0.0/#profile, but I think it is about time for Fedora to wake up there and not our fault that Mono is unmaintained there.

**Comment by pchote** [comment]
That kind of defeats the purpose though, considering that the primary motivation for this change was as a prerequisite for an official Fedora package.  I hadn't considered the effect of the .net version bump on older mono versions - so this is a bigger issue than just Windows XP.

**Comment by Mailaender** [comment]
Yeah, pretty ironic. 

I took a look at Open.NAT again, because for some reason Mono.NAT simply does not work for me anymore and I have no idea why. Even the detailed NAT logging isn't working so I have no means to debug it. However porting to .NET 4.0 and loosing support for older platforms is out of the question as UPnP is an optional convenience function although it significantly reduced support request https://github.com/OpenRA/OpenRA/wiki/FAQ#nobody-can-join-my-online-game.

**Comment by rapgro** [comment]
Mono 3.x is delayed for F22 → https://fedoraproject.org/wiki/Changes/Mono_3

So please make NAT feature as optional. Either by patch or GUI. Request to reopen this issue.

**Comment by Mailaender** [comment]
It is already optional. Go to Settings - Advanced.

**Comment by rapgro** [comment]
The package for Mono.NAT builds just fine. Still waiting for a reviewer to approve it. So I should suggest to use Open.NAT since the futuristic F22 release and keep going with Mono.NAT for the moment. Does that sound reasonable for you?

**Comment by Mailaender** [comment]
You are missing the point. We can't go with Open.NAT although it is superior in architecture, because we can't raise the .NET framework version to 4.5 without dropping support for legacy OS like Windows XP (or latest Fedora).

**Comment by rapgro** [comment]
So this is CANTFIX and UPnP seems to be never supported properly in official Fedora package.

**Comment by Mailaender** [comment]
I am astonished by the bureaucracy of the Fedora project. Looking at https://bugzilla.redhat.com/show_bug.cgi?id=1166897#c2 it seems to be worse than Debian. In contrast this is how it is done in openSUSE by the way: https://build.opensuse.org/request/show/133378

**Comment by Mailaender** [comment]
Gave it a try at https://github.com/OpenRA/OpenRA/pull/7692.

**Comment by Mailaender** [comment]
Not technically possible and WONTFIX from Open.NAT, sorry.

**Comment by rapgro** [comment]
> I am astonished by the bureaucracy of the Fedora project. 
This issue has nothing to do with bureaucracy. Mono's just horribly slow and lazily maintained in Fedora, unfortunately.
https://bugzilla.redhat.com/show_bug.cgi?id=1089426

**Comment by rapgro** [comment]
There are semi-official builds at Copr for both Mono 3 and 4. Maybe use those repos to provide official Fedora builds from OBS?
Mono4 https://copr.fedoraproject.org/coprs/tpokorra/mono/
Mono3 https://copr.fedoraproject.org/coprs/elsupergomez/mono/

**Comment by Mailaender** [comment]
OBS is not connected to COPR. Feel free to send a submit request to https://build.opensuse.org/project/show/games:openra though.

**Comment by rapgro** [comment]
IMHO using COPR in OBS is wrong. We should move the whole stuff to COPR then, at least for concerns about clean Fedora packaging.

**Comment by rapgro** [comment]
Ported to .Net 3.5
https://github.com/lontivero/Open.NAT/pull/31

**Comment by Mailaender** [comment]
I made a new attempt: https://github.com/OpenRA/OpenRA/pull/10281

**Comment by Mailaender** [comment]
and another one: https://github.com/OpenRA/OpenRA/issues/11286.
