### ISSUE TITLE
Soviets don't have any hero units

### ISSUE THREAD

**Issue by elegantandrogyne** [OpenRA/OpenRA#7199]
There's no Soviet counterpart for Tanya in OpenRA. 
The original Red Alert had Tanya for both factions. In Counterstrike (or Aftermath?), Westwood introduced Volkov and Chitzkoi... they could be a nice addition.

**Comment by kaneCVR** [comment]
Just implement Volkov and give him Tanya's stats.

**Comment by Phrohdoh** [comment]
@kaneCVR That is a terrible way to balance a game.

**Comment by pchote** [comment]
Why do the soviets need a direct counterpart to Tanya?

**Comment by MicroJOo** [comment]
:-1:

**Comment by Mailaender** [comment]
The idea seems to be very unpopular. Closing for now.
