### ISSUE TITLE
Load dynamically map

### ISSUE THREAD

**Issue by juliendelplanque** [OpenRA/OpenRA#7200]
I was trying to create a dedicated OpenRA server on my Raspberry Pi so I downloaded a release and rsync map from resources. When I connected on the server on my Raspberry Pi, it crashed because it runned out of RAM while loading the maps.

I think this shouldn't happen, maps should be loaded when it is needed. They should not use more that 400 mb of RAM...

Maybe using a B-Tree could fix this.

**Comment by Mailaender** [comment]
Closing as we already improved on this.
