### ISSUE TITLE
AI difficulty on all currently available 3 games plus some tweaks.

### ISSUE THREAD

**Issue by timot** [OpenRA/OpenRA#7209]
We've had some lanparties and for the sake of nostalgia, we just look to play some 4vsX computer-stomping (or getting stomped by them) >:)

  Anyway, i think the hardest AI definitely should receive a tune-up, its cool to try to "crack-a-turtle-shell" when playing vs AI, defending endless waves of brutal attacks and trying to advance from that hard situation into offensive mode. As some previous posts mentioned, harvesters could be limited (or maybe you're dealing with the pathfinding problem instead) or harvesters could bring in some extra cash for hardest AI to compensate and to keep them sharp all the time, instead of building extremely excessive amounts of harvesters. C&C3 Brutal Steamrollers was the real cool AI to play agains, for example! =) This would probably need one extra difficulty level for current three settings.
  
This might not be the highest priority for now, but these tune-up / tweaking issues would be definitely great for ppl like me or some friends of mine, who doesnt really enjoy doing Player vs Player, but just vs AI for fun and talking stuff on voicecomm or lanparty!

 Thanks for contributing and making this game, it makes our nostalgia-gaming possible :) I wish i had the skill to contribute and help, but no can do, will have to take the bastard-role of just suggesting stuff!

**Comment by DavidARussell** [comment]
I thought the AI (particularly in Red Alert) was tough primarily by cheating with regard to things like unit build times and cost?

**Comment by Mailaender** [comment]
The Tiberian Dawn AI was cheating by getting a lot of more cash from harvested resources and the Red Alert one started with a built base on higher difficulties. This is not what we want to reimplement. You probably want https://github.com/OpenRA/OpenRA/issues/6103 to make enemies (bot or human) artificially more challenging.
