### ISSUE TITLE
Crash Cinnamon after exit game

### ISSUE THREAD

**Issue by avesgit** [OpenRA/OpenRA#7234]
Linux Mint LMDE After exit game Cinnamon crashed and this result
![2014-12-31 12 24 46](https://cloud.githubusercontent.com/assets/6238773/5586698/0bf0edd4-90e8-11e4-9989-576bbe53e690.png)
![2014-12-31 12 24 15](https://cloud.githubusercontent.com/assets/6238773/5586699/0c1e4d9c-90e8-11e4-8098-0e894000867c.png)
![2014-12-31 12 23 46](https://cloud.githubusercontent.com/assets/6238773/5586700/0c4ae6b8-90e8-11e4-98dd-081f9df10e88.png)

after restart all good. This bug only with openra game thanks

**Comment by LipkeGu** [comment]
I reported this issue to the developers maybe they can give as any Information about this crash

**Comment by Bynnar18** [comment]
I also run Linux Mint with Cinnamon and haven't run into this issue.

**Comment by Mailaender** [comment]
Closing as not reproducible and maybe upstream related. We definitely need more info about what we can do about this.
