### ISSUE TITLE
Busy loop in server.cs (High CPU usage)

### ISSUE THREAD

**Issue by asl97** [OpenRA/OpenRA#7237]
problem:
CPU usage over 100% (shown in `top`)

step to reproduce:
1. start game using mono (`mono OpenRA.Game.exe`)
2. start a skirmish (then check CPU usage)

cause:
After starting the game (match/skirmish), the [server/listener (TcpListener) would stop](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Server/Server.cs#L656), the stopped TcpListener somehow cause the [Socket.Select](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Server/Server.cs#L163) not to block and thus resulting a busy loop (High CPU usage)

possible solution:
1. use `Thread.Sleep` in the loop
2. exclude `listener.Server` from the checkRead after the game started,  note: there MUST be some kind of check to prevent `System.ArgumentNullException: All the lists are null or empty.` (and maybe also a Thread.Sleep)

system:
fedora 21 (linux)
mono 2.10.8 (on 29/12/2014) and mono 3.10.0 (from 30/12/2014)
opengl 2.1

the different version of mono is cause pchote suggested that it could be the reason to the high cpu load so i updated it on 30/12/2014

i also notice it long ago when i was using fedora 19 (i don't remember the mono version) but back then, i just thought it was cause my laptop wasn't powerful enough.

notes:
i am able to reproduce the busy loop using this code: http://asl97.pythonanywhere.com/paste/cpp/7a9d9bd1-d5c0-43bc-a49e-13fc86d12b01

this problem might have existed since [May 26, 2012](https://github.com/OpenRA/OpenRA/commit/3f0fafb3801a92d9ee6d5f3e73dcdeff6db31954#diff-e34ac0a837f43698d67024b60cd1cf12R425)

irc: (find `asl97` for my chat messages)
[29/12/2014](http://logs.openra.net/index.php?year=2014&month=12&day=29)
[30/12/2014](http://logs.openra.net/index.php?year=2014&month=12&day=30)
[31/12/2014](http://logs.openra.net/index.php?year=2014&month=12&day=31)

**Comment by LipkeGu** [comment]
is it able to make this async???
