### ISSUE TITLE
Create a true headless OpenRA.Server.exe

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#7252]
instead of always checking against `Game.Settings.Server.Dedicated` and deciding individually whether it should be loaded.

**Comment by penev92** [comment]
I'm not familiar with the server code, but won't this introduce a lot of duplicate code?

**Comment by ihptru** [comment]
I assume, it's only about an executable to run server individually, using OpenRA.Game namespace

**Comment by Mailaender** [comment]
Redundancy should be avoided during this exercise.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/8632 removes all the SDL2/OpenAL/OpenGL dependencies from OpenRA.Game.exe which is probably a first step towards not needing those installed on dedicated servers.
