### ISSUE TITLE
Travis compiling script should not continue when exitcode returns non-zero

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#7255]
In a few build on travis i noticed that the script will continue, when a part of the script failing...

for example... CSC failes while it compiles the editor ... after that the script continues ... with openra-utility.exe ```--check_yaml``` at the end, travis will say... error, that fact!

we should abort the script on the first error that is happening .. instead of continue the script.

in this log the compiler fils but the script continues... :(

https://travis-ci.org/OpenRA/OpenRA/builds/45725147

**Comment by Mailaender** [comment]
I looked through http://docs.travis-ci.com/user/build-configuration/ but I can't find the right setting.

**Comment by LipkeGu** [comment]
the problem is in your make file

**Comment by Mailaender** [comment]
I don't think so. We fail correctly there. This is Travis behavior we don't seem to be able to control.
