### ISSUE TITLE
Unable to move unit on Desert Twister

### ISSUE THREAD

**Issue by asl97** [OpenRA/OpenRA#7258]
When starting a game in Dune2000 with the map Desert Twister,
Player/Ai that started at spawn A or C, they will be unable to move their MCV.

if the game is started with support, some if not all of the unit will be unable to move.

**Comment by penev92** [comment]
I can confirm that this is OK in the Halloween release.
Also I started a game to test it, saw that only half of my starting units can move and got distracted. Some time later I found the units I had moved were dead (AI got them), but my MCV and the rest of the starting force was untouched (only 5-10 cells from where the others died). The clock showed 33:xx.
I suspect the AI ignored those completely, but can't be too sure.

**Comment by obrakmann** [comment]
fwiw, I can't reproduce that on either spawn points A or C

**Comment by MatthijsBenschop** [comment]
Mirage madness has a similar problem where units are unable to go to the far left or right side of the map.

**Comment by penev92** [comment]
So it's not about the starting units/locations. It's about certain regions.
