### ISSUE TITLE
Clean up D2k YAML files.

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7274]
Example:
Combat tanks for all 3 Houses (`COMBATA`, `COMBATH`, `COMBATO`) have some traits attached to them that are also attached to `^COMBAT`, which they all inherit from. (with no changes to the traits' Info) This is not much of an issue, but I think it would be nice polishing.
I'm mainly dropping this here because I don't currently have the time to do it. If anyone feels like doing it - go ahead. If not - I hope I'll get around to it eventually.

**Comment by penev92** [comment]
Unfortunatelly #7477 won't fix this completely. There are things still left like `carryall.infantry:` still using the default aircraft `CruiseAltitude`, which is almost half of that defined on the other carryalls.
Also `carryall.scripted:` is a hack that should be removed when harvester insurance gets implemented.
There are probably other things as well. :/

**Comment by pchote** [comment]
How much of this is still relevant after the rules rewrite?

**Comment by reaperrr** [comment]
I'm sure I fixed most of these during the migration to original balance. I'll try to check later.

**Comment by penev92** [comment]
I believe we can close this now. Thanks!
