### ISSUE TITLE
Failed to open BO for returned DRI2 buffer

### ISSUE THREAD

**Issue by tekkentux** [OpenRA/OpenRA#7277]
Game crashes directly after starting it on debian jessie. Almos all log files remain empty. Output and logs below:

tekkentux:~$ openra
Platform is Linux
Using SDL 2 with OpenGL renderer
Desktop resolution: 1600x900
No custom resolution provided, using desktop resolution
Using resolution: 1600x900
Detected OpenGL version: 3.0
Using OpenAL sound engine
Using default device
Available mods:
	cnc: Tiberian Dawn (release-20141029)
	d2k: Dune 2000 (release-20141029)
	modchooser: Mod Chooser (release-20141029)
	ra: Red Alert (release-20141029)
Loading mod: modchooser
Failed to open BO for returned DRI2 buffer (1600x900, dri2 back buffer, named 9).
This is likely a bug in the X Server that will lead to a crash soon.
Stacktrace:

  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) object.wrapper_native_0x7f904b40f240 (OpenTK.Graphics.OpenGL.ClearBufferMask) <0xffffffff>
  at OpenTK.Graphics.OpenGL.GL.Clear (OpenTK.Graphics.OpenGL.ClearBufferMask) <0x0001e>
  at OpenRA.Renderer.Sdl2.Sdl2GraphicsDevice.Clear () <0x0003f>
  at OpenRA.Graphics.Renderer.BeginFrame (OpenRA.int2,single) <0x00064>
  at OpenRA.Game.RenderTick () <0x001e7>
  at OpenRA.Game.Loop () <0x001a3>
  at OpenRA.Game.Run () <0x0006b>
  at OpenRA.Program.Run (string[]) <0x0004f>
  at OpenRA.Program.Main (string[]) <0x000ff>
  at (wrapper runtime-invoke) <Module>.runtime_invoke_int_object (object,intptr,intptr,intptr) <0xffffffff>

Native stacktrace:

	mono() [0x4b5ca0]
	mono() [0x50edab]
	mono() [0x424183]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0) [0x7f90555148d0]
	/usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x353ccd) [0x7f9049bbeccd]
	/usr/lib/x86_64-linux-gnu/dri/i965_dri.so(+0x30ea48) [0x7f9049b79a48]
	[0x405a54c4]

Debug info from gdb:

[New LWP 19700]
[New LWP 19699]
[New LWP 19695]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f90555144c9 in __libc_waitpid (pid=19701, stat_loc=0x7f905604318c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
40	../sysdeps/unix/sysv/linux/waitpid.c: Datei oder Verzeichnis nicht gefunden.
  Id   Target Id         Frame 
  4    Thread 0x7f9053034700 (LWP 19695) "mono" sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:85
  3    Thread 0x7f9044e9e700 (LWP 19699) "threaded-ml" 0x00007f905523918d in poll () at ../sysdeps/unix/syscall-template.S:81
  2    Thread 0x7f904069c700 (LWP 19700) "mono" 0x00007f905551418d in nanosleep () at ../sysdeps/unix/syscall-template.S:81
* 1    Thread 0x7f905601e780 (LWP 19694) "mono" 0x00007f90555144c9 in __libc_waitpid (pid=19701, stat_loc=0x7f905604318c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40

Thread 4 (Thread 0x7f9053034700 (LWP 19695)):
#0  sem_wait () at ../nptl/sysdeps/unix/sysv/linux/x86_64/sem_wait.S:85
#1  0x00000000006371d6 in mono_sem_wait ()
#2  0x00000000005af5d4 in ?? ()
#3  0x000000000059178b in ?? ()
#4  0x000000000062ba1d in ?? ()
#5  0x000000000063bd93 in ?? ()
#6  0x00007f905550d0a4 in start_thread (arg=0x7f9053034700) at pthread_create.c:309
#7  0x00007f9055241ccd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 3 (Thread 0x7f9044e9e700 (LWP 19699)):
#0  0x00007f905523918d in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f9047c86cc1 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#2  0x00007f9047c782a1 in pa_mainloop_poll () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#3  0x00007f9047c7893e in pa_mainloop_iterate () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#4  0x00007f9047c789f0 in pa_mainloop_run () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#5  0x00007f9047c86c56 in ?? () from /usr/lib/x86_64-linux-gnu/libpulse.so.0
#6  0x00007f904781ea98 in ?? () from /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-5.0.so
#7  0x00007f905550d0a4 in start_thread (arg=0x7f9044e9e700) at pthread_create.c:309
#8  0x00007f9055241ccd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 2 (Thread 0x7f904069c700 (LWP 19700)):
#0  0x00007f905551418d in nanosleep () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f9047ecc328 in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
#2  0x00007f9047ed7ce3 in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
#3  0x00007f9047ecb9da in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
#4  0x00007f905550d0a4 in start_thread (arg=0x7f904069c700) at pthread_create.c:309
#5  0x00007f9055241ccd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

Thread 1 (Thread 0x7f905601e780 (LWP 19694)):
#0  0x00007f90555144c9 in __libc_waitpid (pid=19701, stat_loc=0x7f905604318c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
#1  0x00000000004b5d3d in ?? ()
#2  0x000000000050edab in ?? ()
#3  0x0000000000424183 in ?? ()
#4  <signal handler called>
#5  0x00007f9049bbeccd in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#6  0x00007f9049b79a48 in ?? () from /usr/lib/x86_64-linux-gnu/dri/i965_dri.so
#7  0x00000000405a54c4 in ?? ()
#8  0x000000000146de00 in ?? ()
#9  0x0000000040d5bfe6 in ?? ()
#10 0x0000000000000da9 in ?? ()
#11 0x00007fff36b6be30 in ?? ()
#12 0x00007fff36b6bb80 in ?? ()
#13 0x0000000000000da9 in ?? ()
#14 0x0000000000000db9 in ?? ()
#15 0x000000000000003c in ?? ()
#16 0x00007f903a129e50 in ?? ()
#17 0x0000000040e3845f in ?? ()
#18 0x0000000000004000 in ?? ()
#19 0x00007f90486b2ef0 in ?? ()
#20 0x00007f90486b31c0 in ?? ()
#21 0x0000000040e38230 in ?? ()
#22 0x0000000000000000 in ?? ()

=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

Aborted
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
tekkentux:~$ ls -al .openra/Logs/*
-rw-r--r-- 1 tekkentux tekkentux   0 Jan  5 13:15 .openra/Logs/debug.log
-rw-r--r-- 1 tekkentux tekkentux   0 Jan  5 13:15 .openra/Logs/geoip.log
-rw-r--r-- 1 tekkentux tekkentux   0 Jan  5 13:15 .openra/Logs/graphics.log
-rw-r--r-- 1 tekkentux tekkentux 147 Jan  5 13:15 .openra/Logs/perf.log
-rw-r--r-- 1 tekkentux tekkentux   0 Jan  5 13:15 .openra/Logs/server.log
-rw-r--r-- 1 tekkentux tekkentux   0 Jan  5 13:15 .openra/Logs/sound.log
-rw-r--r-- 1 tekkentux tekkentux   0 Jan  5 13:15 .openra/Logs/syncreport.log
tekkentux:~$ cat .openra/Logs/*
     3 ms LoadMaps
    21 ms Actors
    32 ms Weapons
    33 ms Voices
    50 ms Notifications
    33 ms Music
    33 ms Movies
     1 ms TileSets
tekkentux:~$

**Comment by tekkentux** [comment]
Allso this rarely crashes the whole x server!

**Comment by RoosterDragon** [comment]
Looks like the same issue as #1177. Appears to be a driver issue. There's some suggested workarounds in the comments you can try.

**Comment by obrakmann** [comment]
Sorry, nothing we can do about this on our side. Here's the link to the relevant issue in the Debian BTS: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=762809
