### ISSUE TITLE
Change the order in which Makefile commands are executed?

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7279]
With all the recent additions for CI and style enforcing, the automated builds have become annoyingly slow. The "make test" section is taking Travis a long time (mainly due to the amount of maps for RA).
This could be very annoying for new people (or ones who forget, like me) to wait for it to finish only to break on "make check", because you forgot to run the check locally (I only do when I get reminded of it).
I don't think it would be unreasonable to move "make check" before "make test". Anyone else?

Also "make test" runs in the following order:  RA (63 maps), TD (32 maps), D2k (12 maps), TS (2 maps). This can be really annoying if you want to check D2k or TS, which only take a few seconds, unlike the previous.

I think when dealing with potential "crashes" that might make you start over it is best to move the faster checks before the slower ones.
I'm opening an issue instead of a PR because I want to hear some feedback first.

**Comment by pchote** [comment]
Sounds good to me.

**Comment by penev92** [comment]
I guess #7294 closed this, unless anyone wants some additional tweaks.
