### ISSUE TITLE
Add Sandworm sound effects

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7290]
There should be:
 - [ ] ~~Slight hissing sounds when the worms moves (not sure if we have such)~~
 - [ ] Lightning sound when random lightnings (mentioned in #7289) are implemented
 - [x] Worm attack sound (not the voice notification that says "Worm attack") #8013

**Comment by penev92** [comment]
Hm, there wasn't such a sound in the original, was there? I wasn't sure about that one. Removing it in that case.

**Comment by Mailaender** [comment]
http://d2kplus.com/soundeffecttool.php allows you to search for the unknown file names.
