### ISSUE TITLE
Remove husks prematurely if they are blocking a production building's exit

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7293]
A husk standing in front of your tank factory can be really annoying. It could also hurt you if you are in a hurry to get more vehicles out on the field.

Here you see a destroyed Devastator's husk blocking the Heavy Factory's exit, and the MCV, which is ready, is just waiting inside, blocking the production of any other units as well:
![](http://i.imgur.com/jBaXNwO.png)

**Comment by abcdefg30** [comment]
You can force fire on the husk to destroy it.

**Comment by penev92** [comment]
>[17:53] penev_> it did cross my mind
[17:53] penev_> but question is, will a player remember that in the heat of battle
[17:53] penev_> will he have the time to do it
[17:53] penev_> and will he have a suitable unit to do it with
[17:53] penev_> nearby
[17:54] penev_> cause if you have nothing that can destroy husks around, you are still screwed

;)

**Comment by Phrohdoh** [comment]
@penev92 That line of thinking is intentional. This was implemented like this on purpose.

Will you remember that engineers can repair structures?

**Comment by pchote** [comment]
This is a legitimate gameplay strategy that took a lot of work to fine tune, so I don't like the idea of removing it.  You can shoot or capture the husk to remove it.

**Comment by penev92** [comment]
I'm not talking about removing anything. I'm talking about making Husks implement `INotifyBlockingMove`. If the factory is blocked it notifies actors so they can `Nudge`. Husks can't `Nudge`, so they can be notified to disappear (only by a production structure).

**Comment by Phrohdoh** [comment]
I don't like the idea of asking a husk to disappear because it is in the way.

The player should destroy or capture it, IMO.

**Comment by penev92** [comment]
OK, I guess we don't want this.
