### ISSUE TITLE
Selling a power plant with Unlimited Power toggled on decreases power

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#7317]

**Comment by Mailaender** [comment]
It also doesn't display the `Inf` in the build palette anymore.

**Comment by Phrohdoh** [comment]
That is true but I had assumed that was intentional, silly me.

**Comment by Mailaender** [comment]
This probably regressed in https://github.com/OpenRA/OpenRA/pull/6768.
