### ISSUE TITLE
Please reduce / close issues which are open but indirectly (superseeded) fixed! :(

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#7320]
I looked over a few "crash" issues and noticed that many issues are open but already fixed :(
Example  #6033 #4720

Mailaender said this is an duplicate of #6941 so we should close issues which are already fixed but relaying on other Issues :(

i also put an comment on the fix (after it was merged) for #6941 where i agree thaht the Fix works :/

**Comment by Phrohdoh** [comment]
We are not psychic and do not have super memory.
If you come across something that has been fixed make a comment requesting a close.

**Comment by LipkeGu** [comment]
ok :)
