### ISSUE TITLE
Teams Together

### ISSUE THREAD

**Issue by huwpascoe** [OpenRA/OpenRA#7326]
Lobby Rework TODO - "teams together" option for team games -- will eliminate most need for manual spawnpoint choosing.

**Comment by Phrohdoh** [comment]
#5734, #2992, #5715

**Comment by obrakmann** [comment]
This has been requested quite a few times in the past, as Phrohdoh's list shows. #2992 is the current agreed upon solution to achieve this goal. Closing as duplicate.
