### ISSUE TITLE
Ability to have normal and advanced chronosphere

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#7330]
Steps to reproduce:
- Be allies, france or england. Enemy is germany
- Build a chronosphere
- Capture the german construction yard
- Build an advanced chronosphere (normal chronosphere has vanished from the build menu)

**Comment by Phrohdoh** [comment]
@ScottNZ is this an oversight or intentional?

**Comment by dan9550** [comment]
Doesn't seem like an issue to me, you've captured an additional con yard you should be able to gain its tech.

**Comment by penev92** [comment]
Sounds legit to have both to me, but question is is that OP?
("has vanished from the build menu" on the other hand doesn't sound nice)

**Comment by ScottNZ** [comment]
This is intentional.

**Comment by penev92** [comment]
I mean that if you replace it in the build menu, it doesn't make much sense to be able to build both.
I have no preference on the subject, but my opinion is we should either have both in the build menu (only for Chronosphere, since it's a special case), or only be able to build one.

**Comment by ScottNZ** [comment]
You can't build both. It's hidden from the build menu because the prerequisites are no longer fulfilled.

**Comment by penev92** [comment]
But as @abcdefg30 said, you can kind of "cheat" your way around that by having the normal Chrono built before you acquire the advanced one.
Perhaps we should consider having the normal one block the building of the advanced one, so you have to sell the old one in order to make the better one?

**Comment by ScottNZ** [comment]
I'm currently happy with how things currently are.

**Comment by Phrohdoh** [comment]
Closing this as it was clearly a design choice.

**Comment by cjshmyr** [comment]
It was design to let a player not buy >1 unless they do some convoluted step? Really?

Despite @ScottNZ being happy, there's a design flaw if you are intentionally preventing players from building both chronospheres from the palette yet you can still manage it with certain steps.

**Comment by ScottNZ** [comment]
I hadn't considered the build limits. They should probably share the same limitation.

**Comment by penev92** [comment]
:+1:  for that.

**Comment by pchote** [comment]
You can move both powers on to the same actor, and then use a faction prereq on the power to enable only one of them
