### ISSUE TITLE
D2k - create separate Sardaukar actor for house Corrino

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7332]
I have not had a chance to check this, but it has been mentioned here on GitHub before, and I saw it in several Dune 2000 wiki sites - the Emperor sardaukar are supposed to be better than the Harkonnen ones. This will require we make such an actor for house Corrino with better stats.
How much better and in what way remains to be determined.
I am leaving this here for easier tracking of remaining tasks.
Anyone can feel free to do it if they feel like it.
##

**Comment by UberWaffe** [comment]
According to Dune (the books) Lore, the Sardaukar are the emperor's elite troops. At one point, assisting the Harkonnen, but still the emperor's.

As such, I vote to also rename the Harkonnen one to something like "Assault Trooper" or something similar.

**Comment by penev92** [comment]
Point taken, but the game did have trainable sardaukar for the Harkonnen.
As a matter of fact, Dune 2000 doesn't keep too close to the lore of the books (for better or worse), so I suggest we keep with the game on this one.
Also if we rename them, then the only place one can see some sardaukar would be the missions (if we ever get that far with them, since they are only in the last few).
