### ISSUE TITLE
Game-Timer is important 

### ISSUE THREAD

**Issue by MicroJOo** [OpenRA/OpenRA#7338]
after the new UI for Red-Alert was released , it took some time (as regular player) until ive made my peace with it ... but ... 
there is one element , that still bothers me alot , and that is the game-timer .. sadly squished into the new 250x500 user-interface as 30x10 pixel graphic output ... which is almost a "6x-sized-down" version from our old timer ... here for comparison ( old one is left , and new one right ) :

![timer](https://cloud.githubusercontent.com/assets/9139965/5780224/205c39ea-9da9-11e4-89d4-865e03cde5e9.png)

its not as easy to catch the timer in the new UI anymore ... but it should be easy ,  the game-timer is a important element in "RTS-Multiplayer"-games because ... time-management is essential for these type of games ... and should be easily and quick  "accessible" for a players eye 
i show you guys 2 more screenshots , the first one with the old UI ... and the 2nd with the new UI ... please check out the timer in both screenshots ... and think about , which one would suit better for a regular rts - player ...  

![timer1](https://cloud.githubusercontent.com/assets/9139965/5780386/8e785dea-9daa-11e4-8653-8f0e40199c43.png)

![timer2](https://cloud.githubusercontent.com/assets/9139965/5780391/976b8576-9daa-11e4-9f97-1358d6141be4.png)

bzw.: ... in the replay-user-interface ... there is a ticker that constantly switches with the time ... showing a text that says what speed you are playing the replay ... and also when you pause the game ... unfortunately ... this ticker get faster with your chosen replay-speed ... which (on max) switches "timer" and "text" in every second ...  this is another concern 

**so , my suggestion / idea is ... to have (only) the timer back to its old behavior ... separated and centered with a proper size**

**Comment by chrisforbes** [comment]
I think we should explore options for a more visible timer -- not just throwing it back where it used to be.

**Comment by dan9550** [comment]
IMO i like the timer in its new position. Maybe we should have a hotkeyed test widget that displays more "verbose" game stats e.g. time, ping?, player score, kills, etc. Much like in AoE where you could press some button and see a running score for each player.

**Comment by chrisforbes** [comment]
AOE needing every game to start with mashing F4 & F11 until all the
critical stuff is shown was *bad* ;)

**Comment by dan9550** [comment]
we're going to have to define critical then aren't we ;)

**Comment by MicroJOo** [comment]
there doesnt seem to be a lot of interest nor is there anyone except me having a issue with the timer  , so i close this for now
