### ISSUE TITLE
AI-units don't realign turret after attacking and moving back to base

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#7340]
#6503 is broken again

I noticed, that some AI-units not realign its turret when they attacked and moving back to base

A Titan was moving backward to the AIs Base and aimed my tank.... after i destroyed the aimed tank the titan has realign its turret :/

- My idea is to check the Range when the range is larger than X Cells then the AI should drop the target

**Comment by pchote** [comment]
I can't repro this on latest bleed, so I assume this has been fixed by one of the prs improving turret behaviour this year.
