### ISSUE TITLE
EMP Cannon should act as SupportPower (EMPSpecial)

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#7349]
We introduced the EMP logic for TS to get this work but we should transform them to an EMPSpecial as like in vanilla TS.

In the Moment the EMP is a game killer because:
- When i build of a Wall of EMP Cannons the Game will lag
- The EMP Cannon is firering every second
- Buildlimit should be limited to 1

**Comment by pchote** [comment]
There is a long-standing plan to replace our overly specific nuke/ion cannon/etc powers with a general one that fires an Armament.  This isn't so simple now that we have beacons, but the possibility can be reinvestigated after adding the traits to support this here.

**Comment by LipkeGu** [comment]
we have buildlimit so we can accomplish the last point :)

**Comment by LipkeGu** [comment]
Sorry the EMP Cannon isnt a supperweapon... more likes an supportWeapon so i renamed them to support power (EMPSpecial)

**Comment by abcdefg30** [comment]
#11445 fixed this except for the build limit.
