### ISSUE TITLE
"Build everything" dev cheat should override the build limit for actors

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7352]
As I understand, it currently doesn't, which seems weird to me. Also might prevent you from properly/easily testing an actor that has a build limit. (Or just prevent you from having some fun with 
10 * Mammoth Mk 2 in the enemy base :D )

**Comment by LipkeGu** [comment]
+1

**Comment by Phrohdoh** [comment]
I guess. :+1:
