### ISSUE TITLE
Drop Ressources when Ressourcelimit is reached

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#7359]
In earlier Games like RA/TS/RA2 when a Player has reached the limit of storageable Ressources the Ressources are wasted.

In OpenRA Harvesters cannot unload ressources when the ressource limit is reached and blocks
another Harvester to unload collected Ressources.

In this Case we should go the way:

- define an PerModOption to Say "WaitWhenFull" -> 0 / 1
- or go the legacy way of the older games for all mods

**Comment by reaperrr** [comment]
:-1: to forcing that, this behaviour should at least be toggle-able by the modder.

**Comment by chrisforbes** [comment]
We used to do this, but changed it to block as wasting the resources added
nothing but needless penalty. The storage mechanism is already a bit odd
for new players; wasting their resources made it actively hostile.

The blocking-other-harvesters argument is silly -- all you're blocking
other harvesters from doing is wasting their resources too.

**Comment by LipkeGu** [comment]
But older games used this and we should make TS as like it was in this behavor... or we use exceeded tiberium to grow veins :) so the player will manipulate the world ...

**Comment by MicroJOo** [comment]
what about instead of "wasting" it just spilling it on the ground around the refinery ? 
the penalty here would be just "wasted time" instead of money ... and the worst scenario , less building space

**Comment by cjshmyr** [comment]
@MicroJOo Then OpenRA will get bug reports about why the truck drivers are stupid and don't just wait, or you'll get players having to micro trucks and telling them to stop/go

**Comment by MicroJOo** [comment]
@cjshmyr : yeah , this could cause madness ... well , i wouldnt go so far , to spill all the ore in 1 second on the ground  , just enough every couple of seconds to give people a warning to buy stuff (preferable a silo)

**Comment by pchote** [comment]
This was implemented by #10201.
