### ISSUE TITLE
TS - mutant hijackers voice mixed with music

### ISSUE THREAD

**Issue by MicroJOo** [OpenRA/OpenRA#7366]
this little guy here is playing music-files along with the voice-file when you give him orders

![mutant hijacker](https://cloud.githubusercontent.com/assets/9139965/5829379/a80fa320-a111-11e4-8967-ec4842023b61.png)

**Comment by LipkeGu** [comment]
Yes indeed, but this file is copyrighted by Westwood, so we cant change them afik. In other words is this a Bug / Suggestion / Easteregg ???

**Comment by ScottNZ** [comment]
Not a bug. The music is part of his voice. http://cnc.wikia.com/wiki/Mutant_hijacker

**Comment by LipkeGu** [comment]
```
If the player listens closely when the hijacker responds, they will hear music in the background of his response. 
```
