### ISSUE TITLE
Add hotkeys for activating support powers

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#7369]

**Comment by penev92** [comment]
I'd be more than happy with removing the Ctrl + F1/F2/F3/... combinations from the production and using those for super weapons/player abilities (like it was in Tiberium Wars). :+1:

**Comment by Phrohdoh** [comment]
@penev then you need to devise a hotkey system for production.

**Comment by pi99y** [comment]
How about _Shift_ + F1/F2/F3/... for the powers?

**Comment by pchote** [comment]
Shift is used as the queue 5 production modifier.

**Comment by pi99y** [comment]
Pardon my ignorance, but isn't that only with clicks (Shift + click)?
Right now it doesn't queue 5 powerplants if I press Shift + F1.

**Comment by penev92** [comment]
@Phrohdoh not really. Having hotkeys for those is just pointless.
And yes, currently Shift + Fx does nothing.

**Comment by MicroJOo** [comment]
this is a personal :-1:  ... because i dont need that

**Comment by pchote** [comment]
Shift+hotkey not queueing multiple is a bug, and shouldn't be used to justify overloading the key for support powers.

I'm all for adding hotkeys for support powers, but it doesn't seem feasible to use the modifier+function keys.

**Comment by penev92** [comment]
If I read #5544 correct, it is not a bug, but a removed feature. Also having hotkeys for superweapons tends to be a lot more useful than having hotkeys for production slots 13-24... or is that also just me?

**Comment by pi99y** [comment]
What if clicking the mouse scroll wheel activates the power selection and then scrolling the wheel cycles trough currently charged ones?
Left click fires.
During the selection any other click (including scroll wheel and keys) deactivates the selection.

It would need an indication of the currently selected power (while still choosing) however... for example a small thumbnail near the cursor - like the one that is being used to show where and when the fired power will hit the map.

This however I feel is more error-prone than a simple hotkey selection, but maybe still better than none?

**Comment by MicroJOo** [comment]
clicking mouse scroll wheel is allready used for scrolling on the map per "click and drag"  ... this is a very important thing , because you can skip quickly large map areas with that

**Comment by pi99y** [comment]
Oh I see... Neat feature by the way!
The hotkey Wiki (https://github.com/OpenRA/OpenRA/wiki/Hotkeys) should mention it so more people know about it.

Ctrl + Shift + F1/F2/F3... then? :) Eh, that's already too much keys I think, not really convenient...
