### ISSUE TITLE
Radius difference before and after building

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#7371]
Here are some images of the difference between before and after placing them
SAM Site, Tesla Coil, AA Gun and Gap Generator:
![openra game_2015_01_25_16_09_24_147](https://cloud.githubusercontent.com/assets/7798635/5891897/975704c6-a4ac-11e4-9a47-b756716be65f.png)
Tesla Coil:
![openra game_2015_01_25_16_03_06_964](https://cloud.githubusercontent.com/assets/7798635/5891894/447722e0-a4ac-11e4-921a-d702e5e04559.png)
AA Gun:
![openra game_2015_01_26_00_14_12_107](https://cloud.githubusercontent.com/assets/7798635/5893747/5fc83a68-a4f0-11e4-8650-8481ce9b93fa.png)
Gap Generator:
![openra game_2015_01_26_00_16_09_236](https://cloud.githubusercontent.com/assets/7798635/5893755/984ff8d0-a4f0-11e4-8724-fb15fb7cd8c9.png)

**Comment by MicroJOo** [comment]
same goes for : AA , GapGenerator and Tesla
_______________________________________________
pillbox, c-pillbox , flame towers and turrets are fine

**Comment by obrakmann** [comment]
The difference seems to be that all structures not affected are 1x1, while the affected ones are 1x2 or 2x1.

**Comment by penev92** [comment]
That was my thinking, but the Tesla coil, AA gun and Gap generator look like they are 1x1 from the screenshots above.

**Comment by Snurre86** [comment]
Also the health bar is to high on tesla coil and aa gun.

**Comment by Snurre86** [comment]
No change in release 2015-04-24.

**Comment by HenrytheSlav** [comment]
Tesla, AA and Gap take 1x2 cells ingame.

**Comment by penev92** [comment]
Yes, I was wrong - it's not about the building footprint. Those are 1x2 with a 1x1 footprint.

**Comment by HenrytheSlav** [comment]
Isn't better question witch one is true, so we know where the problem lies?

**Comment by Snurre86** [comment]
It seem as if no one was able to deal with this case of falls advertisement on release-20151224

**Comment by pchote** [comment]
Fixed in #10477.

**Comment by Snurre86** [comment]
This is now fixed.
