### ISSUE TITLE
D2K: Units shouldn't follow sandworms once the 'Stop' command is issued

### ISSUE THREAD

**Issue by nuliukas** [OpenRA/OpenRA#7377]
For the time being, units keep following and attacking sandworms even if the 'Stop' command is issued. They actually do stop following a particular sandworm, but the effect of the 'Stop' command only lasts until the next occasion, when a new sandworm enters their view. The undesired effect of this is sandworms deforming defensive lines, which are formed having enemy units in mind.

As I see it, it should be possible to make units attack sandworms while standing their ground. So that the sandworms would still get attacked and yet it would not lead to the fragmentation of defensive lines.

**Comment by abcdefg30** [comment]
You can use the "Defend"-Stance (ctr + z).

**Comment by penev92** [comment]
That would also happen with any enemy unit that comes into range and then runs away. This is why we have unit stances (on an unrelated topic we really need a UI widget for those btw).

**Comment by Phrohdoh** [comment]
A UI widget for stances is an action bar which is not a simple task.

**Comment by penev92** [comment]
Never said it was. But it was really useful in Tiberium Wars. Also I didn't know we had stances in OpenRA until one day someone randomly mentioned them on IRC, because there is nothing to show the unit's current stance.

**Comment by pchote** [comment]
> there is nothing to show the unit's current stance.

#3437

**Comment by penev92** [comment]
I don't really see why this is still open :?

**Comment by obrakmann** [comment]
me neither.
