### ISSUE TITLE
Classic left-click orders

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#7381]
Left click to select units and issue orders. This also needs to catch miss-clicks that result from this setup.

**Comment by Mailaender** [comment]
It was removed recently in https://github.com/OpenRA/OpenRA/issues/6949.

**Comment by Bynnar18** [comment]
As I understand, this was a really annoying feature to implement and was somewhat buggy when it was in before. I'm all for it though, the right-click orders just make the entire game feel off. I can't stand it! I can completely understand if no one wants to mess with it, but if it were reimplemented, that'd be a large improvement in my opinion.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/7501
