### ISSUE TITLE
TD "Install Game Content" dialog incorrectly states music cannot be downloaded

### ISSUE THREAD

**Issue by clemty** [OpenRA/OpenRA#7389]
playtest: 20150118 / win32

TD "Install Game Content" dialog incorrectly states music cannot be downloaded but has to be installed from original media when it has been possible to download it easily from within openra for some time now

edit: I realized after submitting that the text means that music will not be downloaded using this dialog, however it may be worthwhile to point out the music can be easily downloaded later

![tdmusic](https://cloud.githubusercontent.com/assets/10729559/5924323/16acd70a-a65b-11e4-93e9-f78509a2ecc0.png)

**Comment by Mailaender** [comment]
This is actually correct. At this stage you won't get music in the downloaded package.

**Comment by GraionDilach** [comment]
transit.mix is in the package so you will get some tracks - for example, the Map Theme - and that'll let you pass the music check actually.

**Comment by Mailaender** [comment]
Nope, we kept that in mind https://github.com/OpenRA/OpenRA/blob/bleed/mods/cnc/mod.yaml#L155 and if not someone broke it.

**Comment by GraionDilach** [comment]
Oh, yeah, sorry, I skimmed that line.
