### ISSUE TITLE
In-game menus should not reveal factions of enemies who chose "any" faction.

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#7391]
The game menus (preferences, diplomacy) instantly reveal factions of enemy players (or AI) who chose "any" as their faction. 

I feel this should be changed since choosing "any" (random) should give the player the advantage of surprise. It also balances out the fact that they can't plan ahead (the details - which with factions implemented will hopefully become more important) before the game starts. 
I feel this would give players another strategic option.
It would also make scouting more important.

I think that at least some other popular RTS games already have this mechanic (Starcraft?).

I'm not saying that menus should get updated with faction information once the player has been scouted/their units spotted, just leave it at "Any" / "???" / "random". If it's doable it wouldn't hurt of course.

Showing factions of your allies should be left as is (shown).
What do you think?

**Comment by cjshmyr** [comment]
Good idea, I'm all for it

**Comment by penev92** [comment]
Totally agreed. Also the faction information should be easily updated when you find out a player's faction.

**Comment by Phrohdoh** [comment]
How would you discover the player's faction?

**Comment by x-a-n-a-x** [comment]
As soon as the shroud reveals the ennemy ?

**Comment by pchote** [comment]
I'm all for changing the ingame player list to show the random flag and "random" for those players (including allies) to match the list match what was shown in the lobby.  IMO there is no need to update this list once they are discovered (that's just unneeded complication), and this shouldn't affect the world tooltips.

**Comment by penev92** [comment]
Well updating the player list would make it easier to keep track of your enemies (once you or an ally has spotted them).

**Comment by pi99y** [comment]
Yay!
@Phrohdoh, @x-a-n-a-x Yes, as soon as the shroud reveals their units or structures.
@pchote, @penev92 Yes, updating the list isn't necessary, but is convenient.

**Comment by Phrohdoh** [comment]
I don't see the gain from this if it is nullified as soon as I spot a dog or harv, etc.

**Comment by penev92** [comment]
But it makes people get off their lazy asses and move around the map if they want some intel.

**Comment by Phrohdoh** [comment]
That is also an integral part of playing the game.

**Comment by AoAGeneral** [comment]
The only issue I had with "Any" was the second the game starts you can just hit esc and see the factions. (This is true in TD anyways). So the element of surprise is pointless in that regard. 

Hit esc "Oh its nod. ima do this."

I do agree that the tooltips should still pop up with the faction belonging too. As it also creates for that player playing as random "Should I scout? Or stay hidden? If I scout that player will know." Creates a few alternate elements.

**Comment by pi99y** [comment]
@Phrohdoh If you encountered their units it's because you scouted or they chose to reveal themselves by attacking etc... The player could have chosen to move base, avoid contact and then surprise you with some faction specialty.

World tool tips are not a problem, since they only show when you can see the unit/building.

It's not like every game will be totally different after this, it just gives new options.

**Comment by LipkeGu** [comment]
yes but some factions have unique buildings, so you know when in RA2 is a grand cannon then it is france ;)

**Comment by Phrohdoh** [comment]
@LipkeGu We don't currently have RA2 and faction-specific structures are not so prevalent currently.

**Comment by pi99y** [comment]
@LipkeGu There's nothing wrong in recognizing a building... eventually you will know the faction of your enemy... It's just that learning it from a menu is a cheap way of doing it and it ruins some strategic options for the "random faction" players.

**Comment by WolfGaming** [comment]
It would add unnecesary complications if we updated the faction since it would also be updated as soon as an enemy unit comes in range even if the non random player didnt see it, also there is the problem of cloaked units.

**Comment by StexoO** [comment]
Let's say a player chooses "Any". If the other players don't know his faction until they discover him, he should have hidden icons (or question marks) in his production tabs until he builds his barracks. At this time he will know (ie see) what his faction is.
If the other players don't know his faction at the beginning, he shouldn't know it too, otherwise he has a little advantage. :P

**Comment by pi99y** [comment]
@WolfGaming Agreed! Don't update menus or update only if world tooltip was triggered on one of their units/buildings, so there's no questionhe the player saw it (but that's probably too complicated).

@StexoO Player gets to see his own faction from the start, c'mon seriously... and if you need some kind of reasoning for that: The MCV driver tells him who sent him, that's why he knows the faction... :)

**Comment by penev92** [comment]
@WolfGaming cloaked units won't be a problem.
And for all those "the player must see the unit/structure himself, not just have it revealed" - no. Come on! You are a military commander with a bunch (at least one) assistants (thing EVA). There is no point in *not* updating the player-list-dialog-thingy.

**Comment by pi99y** [comment]
Can this get implemented without the UI update first please, so that it's in game faster (since it's basically cheating) and maybe get polished later? Thank you.

**Comment by Phrohdoh** [comment]
How is this cheating?

**Comment by penev92** [comment]
We went over this in the above comments - you know what your enemy is.
I'd be OK with getting this in the game with no UI updates, if anyone feels like implementing it. I can also point to what needs to be done and where for the actual "discovery", but I don't have the time to do it myself.
