### ISSUE TITLE
Suggestions for the mission Intervention

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#7396]
In the Intervention mission it would be better if the air-striking of the civilian village started after you place your MCV on the main island.

Maybe there should be some more play after the air force command is captured, like use the soviet aircrafts.

**Comment by obrakmann** [comment]
> In the Intervention mission it would be better if the air-striking of the civilian village started after you place your MCV on the main island.

Nope, that doesn't make any sense. Your presence there is a direct response to the air strikes already happening.

> Maybe there should be some more play after the air force command is captured, like use the soviet aircrafts.

Not really, I'm pretty happy with the way the mission works now. I have some ideas how to change the mission, but they are minor and mostly boil down to limiting the availability of helicopters on higher difficulties.

Thanks for your suggestions, though.
