### ISSUE TITLE
Possibility to play as random/any faction within a certain side (allied/soviet)

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#7397]
Let's say a player wants to play with soviet side because he likes a certain unit, but still wishes some randomness within soviet factions.

Should there be an option for "Any allied" and "Any soviet" in addition to "Any" faction when setting up a game? I think so.

And please don't use this as a point of why issue #7391 should not be implemented :)

**Comment by Phrohdoh** [comment]
:+1:

**Comment by abcdefg30** [comment]
:+1:

**Comment by MustaphaTR** [comment]
:+1:

**Comment by Phrohdoh** [comment]
I have a working impl for this but I'm learning some more of git and nuked it.
I should be able to PR it soon.

**Comment by Mailaender** [comment]
Added in https://github.com/OpenRA/OpenRA/pull/7476.
