### ISSUE TITLE
Build Plots

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#7410]
Similar to LotR: BFME.
The initial implementation may be limited to 1x1 footprints for sanity.

This issues serves as a reminder to myself so I don't get sidetracked so easily.

**Comment by chrisforbes** [comment]
Add an image of what you mean?

**Comment by Phrohdoh** [comment]
[wikia](http://bfme.wikia.com/wiki/Build_Plots)

**Comment by Phrohdoh** [comment]
This is not as simple as I thought it would be, I'm working on this in my (very rare) free time.

Feel free to unassign me and have someone else get it done faster, if desired.

**Comment by Phrohdoh** [comment]
This is not as simple as I thought it would be, I'm working on this in my (very rare) free time.

Feel free to unassign me and have someone else get it done faster, if desired.

**Comment by Bynnar18** [comment]
I'm not quite sure how these work functionally but they seem kind of like component slots in Tiberian Sun and could probably be used as such.

**Comment by Phrohdoh** [comment]
This is actually completely separate from Component upgrades (which TS will use once art-upgrades are supported).

See an implementation attempt by myself at #5471 for that topic.

**Comment by Phrohdoh** [comment]
I don't think this fits upstream.

**Comment by Phrohdoh** [comment]
Sorry, I didn't mean to re-open this.
