### ISSUE TITLE
Video installation

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#7412]
`ExtractFilesFromCD` needs an optional flag for `~movies1.mix, ~movies2.mix` and we could think about if our mirror network is strong enough to handle the downloads of those files (around 400 MB each).

**Comment by dan9550** [comment]
These files actually contains some duplicates, i have old code floating around (probably) that extracted the movies. But ideally they should be contained within one data file once installed. IMO anyway.

**Comment by Mailaender** [comment]
Indeed, http://nyerguds.arsaneus-design.com/fullcnc/media/ combines both movies into one MIX file and compresses that again: download size is reduced by around 50%.

**Comment by dan9550** [comment]
That would probably be the best idea in regards to us providing a download for the movie assets.

**Comment by pchote** [comment]
We've been working towards this with the recent mod browser changes.

**Comment by pchote** [comment]
I've finally started building out the long-planned content manager (ui is not final):

![screen shot 2016-04-30 at 23 21 35](https://cloud.githubusercontent.com/assets/167819/14938870/50f8b260-0f2a-11e6-84fd-7d7c711d3a79.png)
![screen shot 2016-04-30 at 23 12 04](https://cloud.githubusercontent.com/assets/167819/14938848/9fd5304e-0f29-11e6-9e26-ff1c887b992e.png)
![screen shot 2016-04-30 at 23 11 04](https://cloud.githubusercontent.com/assets/167819/14938847/9e6dd602-0f29-11e6-9112-5182a52a82cb.png)

Related to #9479, #9082, https://github.com/OpenRA/ra2/issues/124
