### ISSUE TITLE
Change Map Crash

### ISSUE THREAD

**Issue by Zjordy** [OpenRA/OpenRA#7414]
hi, when i click change map, the game crash.
this is +- since after i installed the play test version, which i deleted, but still i can't change map in the standard (helloween) version.
I play on a mac book pro

**Comment by Phrohdoh** [comment]
When you load maps in a new version they are updated to reflect the engine changes.

If the map in question is a custom map try removing it then redownloading it.

**Comment by Zjordy** [comment]
hey,
thanks for the replythe game crashes when i click on change map, so its not about custom map onlyi will try to remove all maps maybe then it will work again


Date: Sat, 31 Jan 2015 15:30:10 -0800

**Comment by TheRaffy** [comment]
ya, that happened to me also after I installed the playtest version. 
It's somehow nasty. 

Map Directory of Windows User:
UrUser *\Documents\OpenRA\maps\ra

**Comment by Phrohdoh** [comment]
The binary map format changed from version 1 to 2 recently.

When these changes occur the game updates all existing maps, meaning old versions can no longer use them.

**Comment by LipkeGu** [comment]
when did the map format change?! Interventation has the same MD5 as like in the Playtest :/

**Comment by LipkeGu** [comment]
@Zjordy can you upload the exception.log file? 

when i use version 6 maps they will not show up in the map chooser

**Comment by Zjordy** [comment]
thanks for the help everyone my problem had been solved. I deleted all my ra1 maps, also those who were in another folder then my ra .exe folder.
i have also deleted my ra1 before, so i don't think i can find the exception.log file
