### ISSUE TITLE
How to add crates on a custom map (Im new and would like to know it)

### ISSUE THREAD

**Issue by Eldees** [OpenRA/OpenRA#7419]
I would like to know how to change crates on custom map and how the plane drop more crates.

**Comment by obrakmann** [comment]
Define "change crates". But https://github.com/OpenRA/OpenRA/wiki/Traits#cratespawner should be your first stop. AFAIK, it's not possible for a badger to drop more than one crate at each pass.

**Comment by Mailaender** [comment]
Have a look at the Drop Zone maps which are all about crates: https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/maps/drop-zone/map.yaml#L187

**Comment by Eldees** [comment]
ok thanks

**Comment by Eldees** [comment]
Hmm first it worked but crates didnt spawned faster then it didnt worked and clicking on the map with editor let it shut down and now it says not compitable with this version of openra really frustrating

**Comment by Eldees** [comment]
Smudges:
This i had done first
Rules:
World:
	CrateSpawner:
		Minimum: 1
		Maximum: 32
		SpawnInterval: 15
		WaterChance: 0

Sequences:

VoxelSequences:

Weapons:

Voices:

Notifications:

Translations:

**Comment by Mailaender** [comment]
I suggest you post your map and problems to http://www.sleipnirstuff.com/forum/viewforum.php?f=80. This is not really the place and it is hard to do remote diagnostics with only bits of information.

**Comment by Eldees** [comment]
Ok thx ill give it a try at the website
