### ISSUE TITLE
Transforming with low hp causes invulnerability

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#7426]
See https://github.com/OpenRA/OpenRA/pull/7130#issuecomment-72467231.

Steps:
1. Set ```mcv``` [Health](https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/rules/vehicles.yaml#L298) to ```16```.
2. Set ```M1Carbine``` [chance](https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/weapons.yaml#L331) against ```light``` to ```100```.
3. Go ingame and build one mcv and one rifle man.
4. Shoot a single time on the mcv.
5. Deploy and undeploy it.

**Comment by penev92** [comment]
Is it possible this might be linked to the ConYard issues we've been hearing about lately, @obrakman?
