### ISSUE TITLE
Reduce the using of selectable -> bounds by fixing and using resolutions (size) from SHPs

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#7427]
#7420 , and other PRs ... we are using select->bounds and hardcoding a size which is illformed, in in every SHP, there is an Image wiith Resolutions which we could use so we get the right Size of the SHP

Selectbounds should only be used on units like UFO (TS) where the image is larger than > 300px
also we can change this in one shoot by reading the Size and resolution from the SHP

**Comment by LipkeGu** [comment]
Also we could do a littlebit math on buildings which are part of 2 or more SHPs :/

**Comment by Unit158** [comment]
You can't just expect the bounds to be correct from the resolution. Automatically determining the bounds for anything would be a waste of resources IMO.

**Comment by Phrohdoh** [comment]
These values being in yaml are the exact opposite of hardcoding.
If we were to calculate bounds based on pixels *then* we are hardcoding.

**Comment by LipkeGu** [comment]
They are correct, look in XCC mixer :) anyway the are at maximum 254kb more memory IMO but alot of smarter work

**Comment by Phrohdoh** [comment]
The SHPs are not cached.
Instead they are pushed into a (very large) texture so we can draw directly from the generated image, instead of individual SHP files.

@LipkeGu Where are you getting the "additional 8 bytes" value from?

**Comment by pchote** [comment]
@Phrohdoh: the needed information is already cached by the game, so there would be very little additional work.  Just change `RenderSprites.AutoSelectionSize` to aggregate over all of the sprites instead of taking the first.

**Comment by Unit158** [comment]
Someone will need to explain to me in detail what they mean, because I cannot understand the message @LipkeGu is trying to convey, sorry. Do the bounds of the SHP fit the unit or building exactly? I'm very confused how this would work.

**Comment by LipkeGu** [comment]
@Unit158: TS-SHPs contains already the information in the Header (Color, ZData, Resolution (Size) and many more) so we can grab these Informations from the Header. Pchote has a little Part already used in its map editor branch :) for the MiniMap :)

**Comment by Phrohdoh** [comment]
I'm still not a fan of this idea. :-1:

**Comment by LipkeGu** [comment]
@Phrohdoh : I can understand you, but every time we had to fix bounds over bounds over bounds, when we implement this and using selectbounds as overwrite (when sizes are set in yaml) so we can disable them.

Why we shouldnt use Data, which are already present, to correct selection bounds?

**Comment by pchote** [comment]
@Phrohdoh: I'm not sure what your objection is – the engine has always done this auto-bounds calculation.  The problem is that the existing code assumes that the actor uses a single sprite (like RA/TD), and this fails for TS/D2K.  This ticket is more of a bug than a feature request.

**Comment by Mailaender** [comment]
I have code in place at https://github.com/OpenRA/OpenRA/pull/4496/files#diff-9660801996d2ef982ea0c07e319eaf66R99 that works reasonable in most cases.

**Comment by Unit158** [comment]
This has not yet been fixed, why did you close it?

**Comment by Mailaender** [comment]
I believe we fixed it in https://github.com/OpenRA/OpenRA/pull/7457.
