### ISSUE TITLE
Select by type key doesn't work

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#7434]
By pressing W key once, it is possible to select all units of the same type that are on screen. By double pressing it all same type units on the map are selected. Once this double pressing has been used, it is not possible to activate the one-press behaviour again. Any press of W will select all units on the entire map.

**Comment by penev92** [comment]
Just deselect and press W again.

**Comment by deniz1a** [comment]
I do that. This seems to work for infantry but not for Yaks.

**Comment by deniz1a** [comment]
OK I didn't get the intended behaviour. If you have already selected all the units of the same type that are on screen, pressing w once will select across map.
