### ISSUE TITLE
ConfigurableStartingUnits can not be updated by map.yaml

### ISSUE THREAD

**Issue by Computerfreaked** [OpenRA/OpenRA#7443]
After some discussion on IRC I was asked to file a ticket about this.

See https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Map/Map.cs#L70

ConfigurableStartingUnits seems to be hard coded to true and in  public void UpdateServerSettings(Session.Global settings) there is also no updating done.

I have not tested this in game but people suggested this might be a bug.

**Comment by Mailaender** [comment]
Try the drop zone maps (or any scripted map) to see that you are completely wrong. This is not hard-coded, it just defaults to true.
