### ISSUE TITLE
Underscore is not shown in lobby chat

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#7447]
If the last message in lobby chat (the one at the very bottom) has an underscore ( _ ), it is not shown until another message pushes it upward. This functionality is essential for the use of the smiley ._.

**Comment by jabbink** [comment]
Seems to work here in the Red Alert mod, or are you talking about a different chat window?

![image](https://cloud.githubusercontent.com/assets/2461972/6327668/dc0edf26-bb5e-11e4-9ec0-24c6abc8048b.png)

**Comment by pevers** [comment]
I think he means this :)

![bug_chat](https://cloud.githubusercontent.com/assets/3428649/6327861/4dc7bbea-bb61-11e4-9f8b-f01766fec5be.png)

**Comment by jabbink** [comment]
:+1:

**Comment by penev92** [comment]
That's definitely not what I understood       from the description. Thanks
for clarifying :)
