### ISSUE TITLE
Ability to mute players in the game lobby and ingame 

### ISSUE THREAD

**Issue by karona75** [OpenRA/OpenRA#7448]
Title is self explanatory. If the country flags are going to stay the ability to mute certain players will be useful. Country of origin easily becomes a target for trolls. Something like /ignore or a mute checkbox could fill the need.
##

**Comment by x-a-n-a-x** [comment]
I think it's a legitimate idea.. 
And it will probably be requested later by other players when the lobby IRC chatroom will be back : 
https://github.com/OpenRA/OpenRA/pull/3859

I just think that the "targeted player" should get informed that he got muted. Don't you think?

**Comment by karona75** [comment]
That sounds fair. Would at least allow the muted player to beaware that certain people won't be able to see anything he types in a team game.

**Comment by obrakmann** [comment]
Related to #5775

**Comment by LipkeGu** [comment]
we could add Country-filter :)

**Comment by x-a-n-a-x** [comment]
@LipkeGu : that would be a little bit racist, don't you think?

**Comment by LipkeGu** [comment]
@x-a-n-a-x : no it doesnt... because you could limit the connection to your server by country (GeoIP) whats the sense when you will connect from China with a ping from 193ms which will get higher and higher and you arent able to understand what they mean (writing) every game has this
