### ISSUE TITLE
Escape key does not work in menu

### ISSUE THREAD

**Issue by Computerfreaked** [OpenRA/OpenRA#7450]
In the RA mod (other mods not tested), go to single player, skirmish.

Pressing the escape key here does not go back to the menu like in all other menu's. Not sure if this is intended for some reason?

**Comment by pchote** [comment]
The logic for this was that the penalty for accidentally pressing escape is quite high (losing your match configuration, or dropping out of a multiplayer server).

**Comment by Computerfreaked** [comment]
Okay that explains. Thanks!
