### ISSUE TITLE
Build area below structures does not extend as far as it should

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#7459]
Introduced by #7155

before:
![screenshot from 2015-02-10 18 07 57](https://cloud.githubusercontent.com/assets/4331210/6132094/9ee7d796-b150-11e4-822b-4fef46c6fe73.png)

after:
![screenshot from 2015-02-10 18 05 28](https://cloud.githubusercontent.com/assets/4331210/6132095/9ee814a4-b150-11e4-9e1e-d374cc59c646.png)

**Comment by penev92** [comment]
It's probably time to remove those hacky Bibs.
