### ISSUE TITLE
Friendly and owned spy insignia (from Mental Omega).

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#7466]
The popular RA2 mod Mental Omega gives spys a special insignia that denote that the actor is:
a) A spy
b) An allied unit (or owned by you)

This insignia is not visible to enemies and cannot be 'discovered' even if the disguise is discovered.

![Screenshot](http://mentalomega.com/images/news_img/item_insignia.jpg)

**Comment by MustaphaTR** [comment]
:+1: It will be good, if we'll use this on OpenRA.

**Comment by Unit158** [comment]
Have you contacted the author to make sure we can indeed use his resource? (assuming the license doesn't already say so.)

**Comment by cjshmyr** [comment]
I'd only ask if you had it already coded, if this is going to happen.

**Comment by Phrohdoh** [comment]
I don't think we should use the art from MO.

**Comment by Phrohdoh** [comment]
I'm going to try to implement this.

**Comment by penev92** [comment]
Opening again because support for this has been added, but a decoration is still missing.

**Comment by x-a-n-a-x** [comment]
As requested on IRC (http://logs.openra.net/?year=2015&month=05&day=23#16:06:09), here are some possible symbols:

![7466_2](https://cloud.githubusercontent.com/assets/1732773/7785126/12629f90-0182-11e5-82a2-229b411790bd.png)

And here are 4 and 9 (rgb non-indexed PNG files):
![star7466](https://cloud.githubusercontent.com/assets/1732773/7785132/238ada94-0182-11e5-8ca1-9f7dc98bb62e.png)

![eye7466](https://cloud.githubusercontent.com/assets/1732773/7785130/1fb5d310-0182-11e5-92e0-e523939ac333.png)

**Comment by x-a-n-a-x** [comment]
Now that #8478 is merged for spies, is there a plan to add a symbol (a star: see my previous message) for allied/friendly units?

**Comment by GraionDilach** [comment]
That star was used for hero identification in MO (practically Tanya/Commandoes had it). I don't know if we're interested in such.

**Comment by penev92** [comment]
I like the idea for hero units. Added it to the checklist at #7551.

**Comment by GraionDilach** [comment]
I'll do that tomorrow then.
