### ISSUE TITLE
D2k actor duplicates from Starport break the Select Units hotkey

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7469]
This has been around for a long time and has always bugged me, but it's not very high on my TODO list. Hopefully someone can take care of it.
The problem:
Right now we have duplicate actors for everything that can be purchased from the starport:
Actor `Trike` and actor `Trike.Starport` are identical, except for their prerequisites and build queue.
Having 5 of each type, selecting one and pressing the Select Units hotkey (`W` by default) will only select 5 trikes, because the actor type names are different.

Just in case someone decides to fix this and needs a pointer:
**Option 1:**
>[20:52] <+pchote> Probably wouldn't be hard to add support for multiple buildable traits
[20:52] <+pchote> Which would do it
[20:52] <+pchote> May not be the best solution though

**Option 2:**
>[20:53] <+pchote> Another idea would be some kind of production proxy trait
[20:53] <+pchote> Which the producer checks for on creation, and replaces the actor
[20:56] <+pchote> That would be even easier implementation wise, but maybe a bit ugly from an architectural pov

**Option 3:**
>[21:01] <+pchote> There's only two ways this can be fixed
[21:01] <+pchote> Either on the production side like ^, or by making the selection code able to consider equivalence over multiple types
[21:01] <+pchote> Without making that end slow
[21:04] <penev> now that ^ would be hacky

**Comment by MustaphaTR** [comment]
We may add anything like in Ares.dll.

http://ares-developers.github.io/Ares-docs/new/typeselect.html?

**Comment by penev92** [comment]
That should be what **Option 3** means, I think.

**Comment by matija-hustic** [comment]
Would Option 3 be acceptable if implemented through a new property e.g. 'Class' of the 'Selectable' trait? Then all units with the same Selectable.Class could be selected when double-clicking or using selection hotkeys.

**Comment by Phrohdoh** [comment]
That's a pretty standard way of doing things, :+1:

**Comment by penev92** [comment]
#8212 was merged.
