### ISSUE TITLE
D2K production tooltip icons are wrong

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#7470]
It looks like chrome.yaml wasn't updated for the new icon positions.

![screen shot 2015-02-13 at 19 37 46](https://cloud.githubusercontent.com/assets/167819/6193978/00bd97e4-b3b8-11e4-81b2-635f90f7fdba.png)

**Comment by x-a-n-a-x** [comment]
The glyphs are in the chrome.png file (so it's not a problem with missing artwork): 
https://raw.githubusercontent.com/OpenRA/OpenRA/bleed/mods/d2k/uibits/chrome.png

In chrome.yaml: 
https://github.com/OpenRA/OpenRA/blob/bleed/mods/d2k/chrome.yaml

replace:

(line 24) sidebar-bits: chrome.png
(line 25) production-tooltip-time: 476,0,16,16
(line 26) production-tooltip-power: 444,0,16,16
(line 27) production-tooltip-cost: 412,0,16,16

by:

(line 24) sidebar-bits: chrome.png
(line 25) production-tooltip-time: 430,208,16,16
(line 26) production-tooltip-power: 494,176,16,16
(line 27) production-tooltip-cost: 494,144,16,16
