### ISSUE TITLE
Remove spy's ability to disguise as a dog

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#7478]
Does he wear a dog costume?

**Comment by deniz1a** [comment]
Also he can disguise as a zombie and a giant ant. Zombie is OK I think but how can he become a giant ant? Is that a mechanical ant that he gets in and controls?

**Comment by Phrohdoh** [comment]
:+1: for a `string ExceptTypes` on `Disguise`.

**Comment by Unit158** [comment]
Is this a needed deviation from the original? Is there any benefit to the gameplay if this is added?

**Comment by GeertJohan** [comment]
Wouldn't an explicit whitelist make more sense?

**Comment by chrisforbes** [comment]
I kindof like the silly disguises...

**Comment by elegantandrogyne** [comment]
Well... so much for the context:
Spy disguising was not implemented in the original RA (the spy was always seen by the enemy as one of their rifle infantry), the first time it appeared was in RA2. You could disguise a spy as a dog, cow, bear, 'gator or any other critter (and, funny enough, the spy-as-a-dog seemed to move as fast as a real dog did!). I don't remember if they fixed it in Yuri's Revenge, but it's repaired in an YR's total conversion mod called Mental Omega. 

As for me, I'd fix it and let spies disguise as human troops only (except for hero units - Tanya and Volkov, provided that he makes it into OpenRA).

**Comment by MustaphaTR** [comment]
>  I don't remember if they fixed it in Yuri's Revenge

No, they can disguise as dog in Yuri's Revenge too.
