### ISSUE TITLE
Aircraft attack move issues

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#7481]
If a Yak or a Mig is given attack move order and there is a target on the way, it attacks the target and then comes back to airfield to rearm. After rearming it continues the attack move starting from the airfield. This happens once and after that it comes back to base and just circles above construction yard and doesn't rearm or go to the attack move location.

Helicopters have a different behaviour. After they attack the target and run out of ammo, they come back to helipad, rearm and continue the attack move. If they encounter another target (or the same target), they attack it and come back to helipad for the second time. But instead of landing and rearming, they immediately skip to the attack move once they arrive at helipad. Since they carry out the attack move without ammo they come back to helipad at first enemy encounter and this repeats as a loop. 

Aircraft attack move works if a second airfield/helipad is built. After that it does this rearming and attack moving action until no target remains along the path and it arrives at attack move location.

I think the reason is that the airfield/helipad is reserved for some reason after the first rearming and the aircraft can't land. It is also not possible to give a manual landing order. When a second airfield/helipad is built it works.

This happens in latest release and playtest.

**Comment by penev92** [comment]
This sounds like the issue @obrakmann wanted to fix. :)

**Comment by deniz1a** [comment]
Also generally, it would be better if multiple aircraft rearmed as a queue. Right now if there are not enough airfields/helipads, multiple aircraft rearming order doesn't work. But I this is a different issue.
