### ISSUE TITLE
[TS] Option for Day / Night behaver based on realtime timezone

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#7485]
A nice feature would be when we have an option to set, that the Lighting (Day & Night) relates to the Realtime :)

So when it is night in Real so the game will also switch to night and reverse :) 
depending on the clock we could make the game more relalistical :) 

So we can "change the experience" in campain missions ... 
- We could define Objectives for night and Day
- Maybe other

**Comment by x-a-n-a-x** [comment]
https://github.com/OpenRA/OpenRA/issues/6200

**Comment by penev92** [comment]
I especially like the missions part.
Imagine nighttime affecting unit's vision (like in some games). This can be used to give players new opportunities at night, like sneaking through the back door.
But don't tie this to the computer's clock. Some people are only able to play after work for example.
How about doing something like DotA's (probably Warcraft 3 had it) time system - several minutes of "day", followed by several minutes of "night" and a clock that shows what time of day it is.

**Comment by LipkeGu** [comment]
Yes im only mean the lightning (for the beginning) then we could show what we can do :) BUT i dont say, related to the clock i wrote based on the Day/Night behaver as a feature we/you could disable this feature in the Options/Lobby Dialog :)

**Comment by dan9550** [comment]
i like the idea of having realtime lighting effects, some things in my opinion which would have to be kept in mind.
* It would not affect missions, they would have there own time
* It would be toggle-able
* Maps be able to overide it

**Comment by Bynnar18** [comment]
Other maps can have independent day/night cycles, but it might be cool for a shellmap.

**Comment by penev92** [comment]
Oh, you're right.

**Comment by pchote** [comment]
This can now be done using lua on a per-map basis.
