### ISSUE TITLE
Riflemen(e1) in hunt mode fire endless on barbed wire

### ISSUE THREAD

**Issue by Computerfreaked** [OpenRA/OpenRA#7496]
Order riflemen to hunt and they will attack barbed wire and obviously never destroy it.

**Comment by penev92** [comment]
That should be an easy fix.
And also should be true for any actor, not just e1, right?

**Comment by Computerfreaked** [comment]
As far as I believe no actor should fire upon barbed wire unless specifically instructed to do so (for which we have no command as discussed in other issue).

The problem is not as bad with rocketsoldiers etc as they will destroy the barbed wire and would not get "stuck" firing on a piece of very narrow steel ;)

I don't know if units performing attackmove will also fire on barbed wire. I could find out in about 2 hours from now...

**Comment by pchote** [comment]
Try removing the `Huntable` trait from the actor definition.

**Comment by penev92** [comment]
Actually I just checked the YAMLs and did some math.
A single e1 would take 27 shots to destroy a single piece of barbed wire in RA :)

**Comment by Computerfreaked** [comment]
Aha, It seems they were firing on something **behind** the fence. And I do confirm at some point they do destroy the fence...

My bad, can be closed...

**Comment by penev92** [comment]
I just checked. The walls don't gave `Huntable` (in RA), so we're OK.
