### ISSUE TITLE
Aircraft targeting actors that are too close

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7499]
I don't know what happened here:
![](http://i.imgur.com/K7QYvlF.png)

The AI built a ranger, I ordered my Mig to attack. (It fired once and missed).
The ranger started moving back and forth like a viceroid and the Mig just kept circling above it. They kept doing that for over 5 minutes.

**Comment by pevers** [comment]
Reproducable:
1. Enemy build harvester
2. You build choppa
3. Fly very close to the harvester and start attacking.

The helicopter will never hit the target and keeps shooting until it is out of ammo.

![screenshot from 2015-02-24 00 09 38](https://cloud.githubusercontent.com/assets/3428649/6339834/b8876efa-bbb9-11e4-88ba-70451ff29521.png)

**Comment by penev92** [comment]
Regarding planes though:
1. Build a Ranger and a Mig.
2. Tell the Ranger to Guard the Mig (makes it follow it).
3. Tell the Mig to shoot the Ranger.

**Comment by reaperrr** [comment]
Hm, can you guard enemy units, too?

**Comment by penev92** [comment]
Doubtful, why?
