### ISSUE TITLE
Add Graph for Memory Usage and more Debug Infos

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#7502]
Some Games like Minecraft Prints the MemoryUsage from the Process and the Video Memory (vram) onto the Screen. We could implement some points this in our Performance Graph 

This could allow us to see in which moments how many Memory is used and maybe lower the Memory Cosumption

- Driver Information (For example: Nvidia Geforce 550 GTX TI - 1 GB VRAM Nvidia Display Driver Version: 450.52)

- Video Memory (using X MB of <Max VRAM> MB)
- Sys Memory (Using x MB from xxxxMB)
- Ressource Memory (mounted files and loaded content) (Using xx MB from xxxx MB)
- Also how Memory is assigned to OpenRA from the System (assinged 2GB)

This could give as informations for optimazions based on Memory usage

**Comment by obrakmann** [comment]
I feel most of these things are things that your OS should be able to do better.

**Comment by LipkeGu** [comment]
@obrakmann the values are only examples :)

**Comment by Mailaender** [comment]
> Driver Information

We already dump those in graphics.log upon crash.

> Video Memory (using X MB of MB)

I tried to find out how to do it, but the answer is

> "you don't need to know, you don't want to know, and it would not help you anyway"

via http://stackoverflow.com/questions/4552372/determining-available-video-memory
