### ISSUE TITLE
[Discussion] Red Alert "Flamethrower"

### ISSUE THREAD

**Issue by MicroJOo** [OpenRA/OpenRA#7503]
recently i was talking to @ScottNZ about the new wave of people (mostly new players) ... using APC-Flamerushes in almost every game ... and that this (soviet) Attack itself is way easier to perform compared to the (allies) defense ... 
it might be possible to defend 1 apc with 5 flamethrowers , but even then it can be really hard , if you dont expect the apc ... (and seriously ... people should have the chance to to setup a quick  defense for every sneaky/easy rush-tactics) 

i do agree that it is a appropriate tactic for a soviet player , and i still want people to use it ... but it should atleast cost some attention and micromanagement for the attacker... not just a click to drive the apc to the location and then a "f"-key hit to watch the enemy struggling to not loose his mcv within the first 5 minutes ... 

@ScottNZ said , we could make the APC slower ... so there is more time to bring the APC down ... 

turrets for example cant reach a apc because he is too fast (there is a exception when the apc drives frontal directly towards the turret , which basicly never happens)

Pillboxes have the problem to get triggered by the APC , but does no damage whatsoever ... instead , the owner of the Pillbox has to wait until the enemy "unloads" the flamethrowers ... and then he has to manually target every enemy .... after every dead target , the pillbox-targeting will jump back to the enemy Apc (depends on the randomness of the "cargo drop" ... ) and you have to pick the next target again ... 

the pillbox-cannon needs for every passenger 2 shots ... (the flamethrower might have less health then a e1 ... but its enough so the pillbox needs still 2 bursts to bring a flamethrower down) 

but its not like my enemy has to put his man in any danger .... the high armor + hp + speed of the apc ... allows easily to avoid defense-structures and just choose a different location and drop the cargo out of defense-range 

a pillbox does 30 damage on infantry ... 
e1 has 50hp 
flamethrower has 40hp 

this has a hudge impact when 5 enemy flamethrowers get unloadet right beside a Construction Yard

so there is definitly more then just a slower apc  ... i have a few ideas 

- flamethrower should not have the same range like a e1 ... (seriously , if we talk about a close-combat unit then we should tweak the range down ... we basicly give flames the same range as a bullet )

- flamethrowers should have the abillity to take out the passengers inside a pillbox , leaving a empty pillbox (or maybe just a chance) 

- similar to the grenadier , there should be a chance for the flamethrower to "explode" ... leaving a 2-3 cell "flame carpet" on the ground for a short time  , which hurts other infantry when stepping over it (or standing inside) ... this chance to explode should preferable depend on the facing-direction of the flamethrower ... and the direction of the bullet

dont get me wrong , i really like the unit ... but currently ... it only does a "shitload" of damage on buildings (grenadiers have the exact same purpose) ... just with a different sprite-sheet 

so im open for new ideas ... or balancing in terms of the flamethrower/apc

**Comment by penev92** [comment]
How about just more adequate defenses?

**Comment by epicelite** [comment]
Just fix pillboxes to prioritize infantry and turrets vehicles like I said before, microing is a thing but there should be some common sense from the AI. 

The pillbox might shoot at infantry instead of the vehicle, but it still might not shoot at the infantry you want it to.

**Comment by MicroJOo** [comment]
there was a couple of talks ... about the pillbox , changing it ... so it withstands better infantry rush 

along with the new introduced production-multiplier which gave barracks and helipads/airfields (easy and fast to produce) a significant "spam rate" for their units ... we got a "infantry" problem generally ... quite early ingame ... ( @chrisforbes might remember the discussion ingame) 
so people start attacking with 20-30+ infantry (mixed) under 3 minutes ingame ... which is very hard to defend , and very often leads to "packing up the mcv" (which throws the players back in terms of tech)

so there was a discussion about changing the weapons for the pillbox (different then we currently do) ... even buffing them ? ... cant quite remember ... i had the idea about adding more slots in a pillbox , to increase firepower , speed and so on ... (chrisf or pchote didnt like the idea because its too close to RA2 )

i wouldnt touch the turret , because thats acutally a pretty balanced defense

**Comment by penev92** [comment]
This actually sounds like infantry (or infantry production) needs a nerf.
But I don't play RA (original or ours) so I can't talk about balance.

**Comment by MicroJOo** [comment]
yeah im just saying ... the flamethrower-apc .... and the infantry-mob-rush .... are both different problems ... 

the mob-rush effects pretty much both factions , while allies have even a harder time to defend it ... because the pillboxes do only selective damage ... which can be good against a paradrop squad for example ... but for a 20/30 mob 
a soviet-flameturret might stop a few infantry squads because of the splash-damge on the whole cell ... but its still a pain because you have to force-fire on the rocket-troops first ... in order to keep your defense alive ... problem , due to a good infantry mix you cant bring them all down in time 

the barracks-production multiplier doesnt effect the apc rush ... (you can do that with only 1 barrack) 

overhauling the pillbox could fix more then 1 problem for infantry (atleast for allies)

**Comment by epicelite** [comment]
Another thing I previously suggested, let the pillbox hole multiple infantry and each one can fire on a different target at the same time.

Why does nobody listen to me?

Flame tower seems fine as-is. It can 1 shot groups of infantry if thats not enough for you maybe this isn't your game? 
I dunno maybe remove the 2 round burst, and increase rate of fire?

**Comment by obrakmann** [comment]
My suggestion would be to decrease max HP for the flamethrowers to 30, and/or add the explode on death chance.

This should make pillboxes more effective against flamethrowers while not nerfing the flamethrowers offensive powers.

**Comment by penev92** [comment]
Not bad. I've already ran into D2k grenadiers (my own) decimating my forces when dieing... so we could do that here.

**Comment by MicroJOo** [comment]
@obrakmann : i also tend to your solution  ... but it might be a radical one ... because soviets are ment to be the "rushy" faction ... so this might be unwanted from a couple soviet-players 

@epicelite : calm down , tweaking the flame-tower was an idea to reduce the "infantry-mob-rushes" under 3 minutes ... you might have had a game vs James ... then you know what im talking about  ... (as said , this effects both factions , thats why ive mentioned soviets flame-tower)

**Comment by penev92** [comment]
I thought they were supposed to be the steamrolling faction.

**Comment by MicroJOo** [comment]
im sure @ScottNZ has the answer to "what soviets supposed to be ... 

@obrakmann : we could probably fix several issues regarding "infantry rushes" like the flamethrower-apc and the 3-minute-mob by tweaking the defense-structures against infantry ... 
you combine your idea "30hp and/or add the explode on death chance" + my idea to let a "flame-carpet" appear on the ground when a.)  a flamethrower-unit explodes , and b.) a flametower shoots a flaming ball on a cell (making a cell impassable without getting burn-damage aka. hp-drain)

**Comment by kyrylo** [comment]
I do agree it's indeed a problem. I do agree that it requires almost no skill or micro control to perform such a rush. I'd like to propose another solution not mentioned here so far.

Since flamethrowers are usually used in early game for rushes (based on my experience), you shouldn't really make any changes to pillboxes whatsoever (because pillboxes are useful during the entire match). My suggestion is to increase the price of a flamethrower. Since it's a rush, it should punish your economy, so if it fails, you should be behind economically. Currently, a flamethrower costs $300. An APC costs $850. Thus, the cost of 1 APC and 5 flamethrowers is equal to $2350. Seems pretty expensive, but maybe it makes sense to make this rush even more expensive by increasing the price of a flamethrower to $500 (the total cost of the rush will be $3350). Also, sometimes I see people using 3 APC's with 15 flamethrowers. Countering this with a single pillbox is impossible (without losing a building or two), so the increased price should not allow a rusher to produce that many flamethrowers.

I also noticed people tend to cooperate and use chinooks (Allies) with flamethrowers (Soviet). I suppose that with the increased price this option is now more viable, because teammates could share the cost of the rush.

However, this solution doesn't attempt to solve the problem of easy microcontrol of flamethrowers. But maybe with the increased price it won't be the problem anymore.

**Comment by MicroJOo** [comment]
@kyrylo : thats a good approach to solve the problem ... but that would most likely make the "grenadier" for rushes more attractive ... 160$ per unit ... 
and it woudnt solve the problem that we have rush-tactics that get constantly get used in almost every game (some people dont even try to do something else)... with a 95% success rate and without the need for any skill

**Comment by pi99y** [comment]
Maybe flamethrowers should be available a bit later in the game? Maybe after War factory or Radar dome (+current requirements: Flame Tower and Barracks)?

**Comment by MicroJOo** [comment]
scott said @IRC , he wants to polish the factions first .. before reshaping infantry (flamethrowers , snipers) ... he might change something regarding soviet factions ... 

lets wait and see what he comes up with , maybe there will be another detail we have to consider for a flametrooper-tweak

**Comment by MicroJOo** [comment]
@ScottNZ suggested ... the we could shift flamethrower up on the tech-tree .... for example like the original did ... soviets would still have a 5-slot beefy apc to rush rockettroops , grenadiers , shocktroopers ... and so on ... 
http://cnc.wikia.com/wiki/Flamethrower_infantry_%28Red_Alert_1%29
![flamy](https://cloud.githubusercontent.com/assets/9139965/6316960/1f9861e8-ba3a-11e4-8d92-eab894b2c9ae.png)

**Comment by cjshmyr** [comment]
fun fact, it was moved down from requiring stek a long time ago to encourage use :)

**Comment by ScottNZ** [comment]
I think it could work if we treat flamers as a sort of upgrade to grenadiers

**Comment by Bynnar18** [comment]
Well there is the middle ground of putting it with the radar dome. It's not as high up as the tech center as to be too far up to bother with but isn't as easy as a barracks and flame tower.

**Comment by pi99y** [comment]
Agreed @Bynnar18, Tech Center is a bit toomuch.

**Comment by ScottNZ** [comment]
It would be a bit silly to keep shock trooper at stek as well then.

**Comment by MicroJOo** [comment]
@cjshmyr  didnt agree to a stek as requirement ... 

and i agree with @ScottNZ  here ... considering that we just "shift" the problem , and we dont tweak anything on flamethrowers , apc or pillboxes ... and you can still use Grenadier if you want a early rush ... or how about a squad of Rocket-troops ... 5 of them are a pain against harvesters ... 

techcenter will be fine

**Comment by pchote** [comment]
The obvious (to me) resolution would be to fix #5294 and then encourage people to build walls to defend against this.

**Comment by MicroJOo** [comment]
what @pchote said + #7794 (Buff pillbox against infantry) ... i would say , we can close this for now
