### ISSUE TITLE
Missile code needs refactoring

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#7509]
It needs at least the following improvements, in my opinion:

- proper 3D math
- ROT should apply to vertical movement as well (maybe as separate VerticalROT)
- customisable launch angle
- support for lazy curve flight behavior (like Bullets with Angle, but with target tracking)
- support for straight flight path instead of the current "move to target's Z height as quickly as possible" behavior
- support for Airburst (as in TS)
- support for voxel artwork

These would be nice to have as well:
- acceleration (instead of constant speed from launch to impact)
- customisable cruise altitude
- customisable explosion altitude (might be better than just Airburst)

**Comment by pchote** [comment]
We also need support for voxel artwork for TS/RA2.

**Comment by Phrohdoh** [comment]
Nice list. I'll try and help over any free time I get (whether that be code or discussions on IRC).

**Comment by reaperrr** [comment]
> We also need support for voxel artwork for TS/RA2.

True.

Additionally, I think 
- ```TurboBoost``` should define an integer percentage instead of just a bool with hardcoded value
- ```High``` should be renamed to ```Blockable```, and 
- related: ```BlocksBullets``` should be renamed to ```BlocksProjectiles``` and define a customisable ```BlockHeight``` value which should then be compared to the projectile's altitude when it passes that actor (applies to all projectile types, of course).

**Comment by reaperrr** [comment]
Supercedes #3736.

**Comment by GraionDilach** [comment]
>ROT should apply to vertical movement as well (maybe as separate VerticalROT)
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Effects/Missile.cs#L32

**Comment by reaperrr** [comment]
```MaximumPitch``` works very different than a ```VerticalROT``` as I mean it would. For starters, it's Tan so the curve gets flatter the closer the missile is to the desired height. This looks fine for MiGs' Mavericks and anti-air missiles, but not bazookas and other surface-to-surface missiles. It's also more difficult to get right than a VerticalROT would be. Set the value too low, and the missile might miss its target because it didn't reach pos.Z = 0 quickly enough. Set it too high and the missile moves to zero height too quickly, flying at zero altitude most of the way which looks especially bad in isometric perspective (no visible shadow).

**Comment by pchote** [comment]
Fixed by #8717 and followups.
