### ISSUE TITLE
Facings are broken on imported maps

### ISSUE THREAD

**Issue by ScottNZ** [OpenRA/OpenRA#7516]
4be5c0338532fba5f6d635ba24825ec9cfb7372b removed `Facing: 0`, except the default facing is 128, not 0. A bunch of medium tanks on the desert shellmap (and other units on other maps) are facing the wrong way because of this.

**Comment by obrakmann** [comment]
Is there a reason that the default is 128? Because I'd rather change that to 0 than undoing all the map.yaml changes.

**Comment by pchote** [comment]
I suspect this may have been to match the original games (but somebody should actually check this).

**Comment by penev92** [comment]
So 0 means North and 128 is South.
I don't know what the default facing is in TD and RA.
I've only seen one Dune 2000 map editor, but that had the default facings to North.
We really should check the original games before reverting this.

**Comment by reaperrr** [comment]
Default facing in TD/RA is 0 (north).

**Comment by Mailaender** [comment]
I thought this was more difficult when looking at the facing calculations, but @obrakmann already silently proposed a fix: https://github.com/OpenRA/OpenRA/issues/7519
