### ISSUE TITLE
Distinguish ally and enemy chat messages

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#7518]
It would be better if the in-game chat showed teammate and enemy messages differently. For example when a teammate says something it could be green underlined and when enemy player posts a message red underline? Or some other way to make them different.

**Comment by epicelite** [comment]
[TEAM]Player: This is an example of a team message.
Player: This is an example of a public message.

**Comment by penev92** [comment]
What he means is that public messages can come from both allies and enemies.

**Comment by deniz1a** [comment]
Yes and if I don't know the names of the players, I have to look at diplomacy window to see if the public message was sent by an ally or enemy.
