### ISSUE TITLE
No super-weapons option in skirmish/multiplayer

### ISSUE THREAD

**Issue by SMPJavan** [OpenRA/OpenRA#7523]
It would be quite nice to be able to disable super-weapons in skirmishes and multiplayer games. I'd be happy to implement this feature.

**Comment by deniz1a** [comment]
Yes, the medium tech level removes super weapons but it also removes other high tech units/structures.

**Comment by penev92** [comment]
Yes please. No superweapons lobby option.

**Comment by LipkeGu** [comment]
duplicate of: #6583, #4957

is already includeded ... see: #6583

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/issues/4957#issuecomment-48833361

**Comment by LipkeGu** [comment]
maybe we should enable this function as lobby option but disable it by default :/ as @chrisforbes already said in another PR

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/pull/10580.
