### ISSUE TITLE
Remove obsolete DLL references from mod.yaml files

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7526]
One of the reasons for migrating all the code from `OpenRA.Mods.RA` to `OpenRA.Mods.Common` was that a mod should not depend on another mod in any way (for the official mods, at least).
But I see `mod.yaml` files containing this:

> Assemblies:
>     ./mods/common/OpenRA.Mods.Common.dll
>     ./mods/ra/OpenRA.Mods.RA.dll
>     ./mods/cnc/OpenRA.Mods.Cnc.dll
>     ./mods/d2k/OpenRA.Mods.D2k.dll

Once the migration to `Mods.Common` is complete each mod should reference only the common DLL and its own.
Putting this here so I don't forget about it as easily.
##

**Comment by pchote** [comment]
This will break some of the existing custom maps for RA, which rely on functionality from the other dlls (like the TD ion cannon).

**Comment by penev92** [comment]
So... no?

**Comment by pchote** [comment]
It probably makes sense to remove the TS and D2K dlls, as these don't contain anything useful outside their own mods (yet).

**Comment by Mailaender** [comment]
With that argument you also have to keep the D2k logic if someone wants sandworms and carryalls in a RA custom map.

**Comment by pchote** [comment]
I'm not aware of any shipping maps that reuse D2K specific logic.

**Comment by Mailaender** [comment]
Removed the D2k DLL only for now in https://github.com/OpenRA/OpenRA/pull/7570/.

**Comment by penev92** [comment]
OK I'm starting to have doubts about this.
Other than an ugly `mod.yaml` what other drawbacks could loading all the DLLs have?

**Comment by Phrohdoh** [comment]
There is no reason to do it if it is unnecessary.
That's one less assembly to load and iterate over the namespaces/types it contains.

**Comment by penev92** [comment]
The point is we do all sorts of crazy stuff to give mappers as much freedom as possible. And this will be taking away from them the ability to use traits from other mods in maps.
No Ion cannons in RA/D2k, no WormSpawners in TD/RA (someone had actually asked about how that would be possible on sleipnirstuff a while ago; that was for civilians, not worms).
And while I do want to clean the YAML files, it may not be worth it if it limits mappers.

**Comment by Phrohdoh** [comment]
Sorry wrong button.

**Comment by ScottNZ** [comment]
Let map.yamls have a list of dlls to load?

**Comment by Mailaender** [comment]
Is that technically possible?

**Comment by pchote** [comment]
Yes, but we would need to be careful about doing it in a way that doesn't introduce a giant security hole.

**Comment by penev92** [comment]
As long as you don't have any problematic DLLs already in your OpenRA folder, you're OK. And that should be none of the maps' concern.

**Comment by Phrohdoh** [comment]
I think that idea falls under "don't use something (a DLL) you can't analyze (read the source to)".

**Comment by Mailaender** [comment]
Looks like https://github.com/OpenRA/OpenRA/issues/12659 solved this.
