### ISSUE TITLE
Was able to recharge 5 helis on 3 helipads at the same time

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#7545]
Here is an image, if you look closely you can see two helicopters on the far right pad and one helicopter in between the pads. 
![8317451c-bce8-11e4-9ef6-b0eb8e7e88f1](https://cloud.githubusercontent.com/assets/7798635/7874831/52c0b0cc-05b5-11e5-94e0-a1ef32ef87ad.png)
##

**Comment by penev92** [comment]
I couldn't say what happened there, of course, but our docking-related stuff is really hacky:
 - The harvester-refinery docking is a hack
 - The vehicle-repair pad is basically "tell the vehicle to walk to these coodinates and repair itself"
 - I assume the vehicler-rearm facility does the same

I've been wanting to redo those as a follow up of the cleaning I did in #7098 and make docking generic enough to handle (properly) all kinds of docking and use it for the above 3, but I haven't had the time or energy.
Still, this looks to be a two-part thing. I'm going to guess that:
 1. The helicopters chose rearming locations at the same time, so the check whether that helipad was already reserved was somehow skipped
 2. The hacky way we do rearming (if we do it like the repairing) was unable to stop the helicopters from landing  (and rearming) at the same helipad.

This is just a guess, but might be a good starting point if someone decides to investigate this.
If it is correct, both points will need fixing, as they are different bugs.

**Comment by Snurre86** [comment]
if you look closely you can see that one of them did not land in the center of the heli pad.

**Comment by reaperrr** [comment]
> The helicopters chose rearming locations at the same time, so the check whether that helipad was already reserved was somehow skipped

@penev92: I had a look at the landing code for something unrelated, spotted this in ```Helicopter``` and ```Plane``` traits:
```if (!self.HasTrait<FallsToEarth>()) // TODO: Aircraft husks don't properly unreserve.
					ReserveSpawnBuilding();```

Of course all aircraft in RA mod have the ```FallsToEarth``` trait, so reserving is effectively completely broken at the moment...

**Comment by Snurre86** [comment]
Was able to recharge 5-6 hinds at 4 helipads in release 2016-10-19.
![openra game_2016_11_21_09_43_20_417](https://cloud.githubusercontent.com/assets/7798635/20476057/55f156c8-afcf-11e6-9f7f-cef7269baa4c.png)

**Comment by pchote** [comment]
I don't see any stacking issues in the screenshot or linked video?

**Comment by Snurre86** [comment]
Am I mistaken? I will do some more testing.

**Comment by Snurre86** [comment]
No need for it, might be fixed.
