### ISSUE TITLE
Unable to force fire on 3/4 cells on a bridge

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#7546]
If i force fire on the one cell that gives me an attack order icon the bridge gets destroyed but the units continue shooting after the bridge is destroyed. If I force fire at any of the other tree cells it will only show a move order icon and will only result in a move order unless there is a unit occupying that cell. 
The working cell:
![116f1fa4-bceb-11e4-80f8-c55c6c46a78e](https://cloud.githubusercontent.com/assets/7798635/7874867/eba70e9e-05b5-11e5-91df-603f487a5dd3.png)
The none working cells:
![22e8cce4-bceb-11e4-9d47-c9b897cd4ae2](https://cloud.githubusercontent.com/assets/7798635/7874872/f2aad55e-05b5-11e5-9209-f1c698a8e410.png)

**Comment by Snurre86** [comment]
Reproduce by studying the bridges in mission "Survive 02".

**Comment by atimoschenkow** [comment]
I think it is caused by the tiles of the bridge being defined as Rock inside YAML.
