### ISSUE TITLE
TD: Light Tanks vs Medium Tanks. Tanks vs Bikes.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#7549]
Light Tanks vs Medium Tanks:

This is a very hard one for me. This is a double edge sword. The Light Tanks can seemingly out perform the medium tanks with numbers of say 10 vs 7. Which I figured the Mediums would win. However if the mediums are evenly numbered or close the mediums win.

The problem could be that the light tanks perhaps shoot a tad bit to fast? But then this could create issues vs other units (Such as Nod vs Nod or other GDI units.) So im not entirely sure how to make a work around on this. Maybe a slight medium tank HP increase? Turrets turn rate is a bit faster? What do you guys think?

-------

As for the bikes, I think when the fix comes through and are able to implement the build speed modifiers from the price the price rate can stay at 600. But perhaps the bikes range is to far vs tanks? Its got a 2 ranger advantage then the tanks itself. Perhaps knocked to a 1 range different?

**Comment by chrisforbes** [comment]
@AoAGeneral how are you measuring this? Is everyone just sitting there blasting away until one side is all destroyed, or are you keeping the units moving as in a real engagement?

**Comment by AoAGeneral** [comment]
Units are moving in a real engagement. Pulling back tanks when you can when one is damaged. Harder to do vs Light Tanks however as they move faster then Medium Tanks. Specially since the game still has the slight glitch where you can circle a unit and they won't shoot. When considering terrain locations its pretty even in most regards. Usually its whoever makes the first move loses their stuff. Unless they play smart and use artillery with aircraft for sight. The main issue as I said is light tanks can out power the medium tanks by just a slight amount. Considering, that medium tanks take twenty seconds to build and light tanks take fifteen seconds. It is a pretty easy way to catch up. Specially if used with E3. Losing tanks as GDI comes up as more time costing rather then resource costing.

This however, I think is fine in determinations of speed. I do like the speed differences of medium and lights. This I believe is fine.

**Comment by AoAGeneral** [comment]
Reducing the Light Tanks HP -10 should help. It will also help in various other categories as well.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/8303 has been merged.
