### ISSUE TITLE
Move away from mod-specific engine code (part 86): Countries and Races

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7552]
As I've mentioned a couple of times before, the `Country` and `Race` are really out-of-place in the engine. They might have been OK once (years ago), but not any more.
You have `Country` and `Race` in the code and in YAML, but the players see factions, countries, alliances of countries, Great Houses, etc.
Currently we have:
 - Tiberian Dawn: GDI vs Nod (government vs terrorists, or faction vs faction)
 - Red Alert: Russia vs USA (country vs country), more popular as USSR vs The Allied Nations (faction vs faction)
 - Dune 2000: Atreides vs Harkonnen vs Ordos (houses) vs Corrino/Emperror (house/faction/government) vs Fremen vs Smugglers vs Mercenaries (factions)

We'll be having also:
 - Tiberian Sun: GDI vs Nod (government vs terrorists, or faction vs faction) (include the Scrin to get a `species`)
 - Firestorm: GDI vs Nod (government vs terrorists, or faction vs faction)
 - Red Alert 2: Russia vs USA (country vs country)
 - Yuri's revenge: Russia vs USA vs Yuri (country vs country vs faction)

Hopefully one day:
 - Generals: USA vs China vs GLA (country vs country vs terrorist faction)
 - Zero Hour: USA vs China vs GLA vs Gen1 vs ... (country vs country vs terrorist faction vs rogue faction 1 vs rogue faction 2 vs ...)

Unofficial mods may include:
 - Civilizations
 - Empires
 - Kingdoms
 - Tribes
 - Races
 - Species

The engine code should be generic enough for all official mods (and as much as possible for any unofficial).
So I am proposing (again) to switch any mentions of `Country`, `Race`, `House`, `Species`, etc. in the code with the generic enough `Faction`.

My earlier statement can be found [here](https://github.com/OpenRA/OpenRA/pull/7399#issuecomment-74166608).

**Comment by Phrohdoh** [comment]
I still disagree with this notion as you can call them all whatever you'd like.

Why not use Tribe? Organization? etc.

**Comment by penev92** [comment]
Because the GDI empire might not agree to be called a "kingdom". And if Stalin hears you call his forces a "tribe" he'll have you shot on sight and then skinned.
I also don't get the specie "France" o.O

**Comment by Phrohdoh** [comment]
The discussions for that have been "remove Ore and add Resources" or similar.
The point is this is all just a matter of labels.

**Comment by penev92** [comment]
This not being a bug or a much-wanted feature is no reason to trash the idea. The code does contain a lot of weird class/variable names in this regard.

**Comment by pchote** [comment]
:+1: to renaming the `Country` trait to `Faction`, the Country -> Race field to `ID`, and the `Race`/`Owner` fields on other traits to `Faction`.

**Comment by penev92** [comment]
Just for reference for anyone that missed the discussion on IRC (and for my future reference):
[Current naming](http://pastebin.com/gnPNxq10) vs [intended naming](http://pastebin.com/Xc8KnjBV)

**Comment by LipkeGu** [comment]
This makes the "Side scripting" also easier to understand :+1:

**Comment by Bynnar18** [comment]
I don't know about ever getting past Tiberian Sun since everything past that is not freeware but I do agree with the idea here. Race makes it sound like some sort of Warcraft engine so I approve of some generic naming. :+1:
