### ISSUE TITLE
Add inheritance support to weapons [$15]

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#7556]
Currently only actors can inherit, while weapons have to be fully duplicated even if you need only a single change.

This would probably allow to shrink the number of yaml lines for weapons quite a bit.

**Comment by Phrohdoh** [comment]
:+1:

**Comment by chrisforbes** [comment]
:+1:

**Comment by LipkeGu** [comment]
:1:

**Comment by Phrohdoh** [comment]
@LipkeGu one step at a time.

**Comment by MustaphaTR** [comment]
:+1:

**Comment by hypercube33** [comment]
Er, why not fix bugs before suggesting optimizations?
