### ISSUE TITLE
sovite missing hind attack helicopter

### ISSUE THREAD

**Issue by christopherSlavik** [OpenRA/OpenRA#7557]
should give soviet the hind, it is soviet tech, allied forces do not have hind, allied attack helicopter moves faster then hind, both should rocket structures and tanks, and gun troops, allied should have airfield and para troops and the yak, mig is soviet tech, but should make a new unit for allied the phantom (f5) http://en.wikipedia.org/wiki/Northrop_F-5

**Comment by Bynnar18** [comment]
I'm pretty sure the reason it was moved to the Allies in the first place was a balance decision. With the Yak, the Soviets don't really need the Hind for anything. 

If I get your point, you want to make both factions the same, aside from cosmetic differences which means nothing and probably would unbalance the game giving Allies Paratroopers. It's balanced as is and doesn't need any changing aside from changing the Hind to something a little more Allied with the same functionality.

:-1:

**Comment by MicroJOo** [comment]
:-1:  close please

**Comment by penev92** [comment]
That sounds like a very questionable balance decision though.

**Comment by christopherSlavik** [comment]
yeah it needs a new model and sidebar icon , the hind is just straight soviet bugs me, but game is fun keep up the great work guys.

**Comment by penev92** [comment]
Unfortunately we are lacking in the modeling department, so new units are not likely to happen :/

**Comment by Phrohdoh** [comment]
I'm not a fan of both sides having a helipad and airstrip (therefor helis and jets).

**Comment by MustaphaTR** [comment]
I agree with @Phrohdoh. Current status is better.

**Comment by Mailaender** [comment]
See also wiki.openra.net/FAQ#this-is-not-true-to-the-original
