### ISSUE TITLE
Rename D2K actors/effects/weapons to match the original game

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#7558]
This would bring D2K in line with the other mods, and make it easier to compare stats against other tools (TibEd / our own new ones).  I suggest two changes, however: changing everything to lower case to avoid the current issues OpenRA has with case sensitivity, and replacing the spaces in the weapon names to underscores.

Units:

```
LIGHT_INF
TROOPER
ENGINEER
THUMPER
SARDAUKAR
TRIKE
RAIDER
QUAD
HARVESTER
COMBAT_TANK
MCV
MISSILE_TANK
DEVIATOR
SIEGE_TANK
SONIC_TANK
DEVASTATOR
CARRYALL
ORNITHOPTER
FREMEN
NSFREMEN
SABOTEUR
DEATH_HAND
SANDWORM
FRIGATE
```

Buildings:

```
CONSTRUCTION_YARD
CONCRETE
CONC2
WIND_TRAP
BARRACKS
SIETCH
WALL
REFINERY
MEDIUM_GUN_TURRET
OUTPOST
LARGE_GUN_TURRET
AT_HIGH_TECH_FACTORY
HIGH_TECH_FACTORY
LIGHT_FACTORY
SILO
HEAVY_FACTORY
STAR_PORT
REPAIR_PAD
RESEARCH_CENTRE
ATREIDES_PALACE
HARKONNEN_PALACE
ORDOS_PALACE
IMPERIAL_PALACE
SP_OUTPOST
```

Weapons:

```
LMG
BAZOOKA
ROCKET
HMG
80MM GUN
155MM HOWITZER
SOUND
HYDRA
110MM GUN
BULLET10
BULLET11
BULLET14
NEW ROCKET
NON HOMING
MTANK PRI
MTANK SEC
DEVIATOR
DEVBULLET
DEVASTATOR
ORNIBOMB
DHBOMB
SPICEEXPL
WORM
DEBRIS
DEBRIS2
DEBRIS3
DEBRIS4
BARRELHIT
SARDDEATH
CRATE
M_LMG
M_HMG
```

Explosions / effects:

```
EX_HARV
EX_ROCKET
EX_BAZOOKA
EX_155MMGUN
EX_NEW ROCKET
EX_HMG
EX_TANKGUN
EX_MG
EX_BANG11
EX_BANG13
EX_BANG14
EX_SMOKE3
EX_WHITEN1
EX_FLASH
EX_DEVIATE
EX_GREENEXP
EX_TRAIL
EX_TRAIL3
EX_WORM
EX_WORMDUST
EX_WORMSN1
EX_WORMSN2
EX_WORMSN3
EX_WORMSN4
EX_WORMSN5
EX_WORMSN6
EX_PUFF
EX_THPUFF
EX_HARVDUST0
EX_HARVDUST1
EX_HARVDUST2
EX_HARVDUST3
EX_HARVDUST4
EX_HARVDUST5
EX_HARVDUST6
EX_HARVDUST7
EX_CASH
EX_DEVASTATOR
EX_DEVDEATH
EX_FLAME
EX_FLAME2
EX_TRAIL2
EX_SMOKE4
EX_TRIKEM
MUZ_TANK
MUZ_DEVAS
MUZ_GTUR
EX_DHM
EX_WALL
EX_REF
EX_DEVSPARK1
EX_DEVSPARK2
EX_DEVSPARK3
EX_CRATEREVEAL
EX_CRATENOMAP
EX_CRATESTEALTH
EX_DEATHHAND
EX_SPICEBLOOM
EX_BUILDING
```

**Comment by Phrohdoh** [comment]
Makes perfect sense. :+1:

**Comment by penev92** [comment]
And I assume this should all be done between merging the d2k-raceart PR and the rebalancing. :|

**Comment by pchote** [comment]
The best next step after d2k-raceart will be a pr that fixes the actor names and the tech tree / prerequisites (including the upgrade queue).

**Comment by penev92** [comment]
Those two could do with their own PRs IMO, but otherwise that's what I was
thinking.

**Comment by pchote** [comment]
My (print-actor-data)[https://github.com/pchote/OpenRA/tree/print-actor-data] branch makes a start on printing the original game stats for our use.

**Comment by pchote** [comment]
Units/buildings/weapons have been done.  Do we want to rename the explosion sequences too for consistency?

**Comment by penev92** [comment]
I'll leave that to @reaperrr because I'm neutral.

**Comment by reaperrr** [comment]
To be honest, by now I don't think it's important enough for the effort involved and I'm busy enough already.

**Comment by MustaphaTR** [comment]
I can take a look to this when i find time, if we really want to rename them too.

**Comment by penev92** [comment]
Almost 9 years later, I feel the ship has sailed on this one.

**Comment by abcdefg30** [comment]
Probably.

**Comment by PunkPun** [comment]
Unless @Porenutak is interested

**Comment by Porenutak** [comment]
Nah, Im fine with ORA names.
