### ISSUE TITLE
Friendly fire on civilians in "Monster tank madness"

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#7563]
Here you can see my light tank running over a civilian and making the secondary objective fail.
![907f686c-bf1b-11e4-8f4b-63058d3e94a5](https://cloud.githubusercontent.com/assets/7798635/7874914/8ece6c16-05b6-11e5-88b0-e1211f36bbe3.png)

**Comment by penev92** [comment]
Would simply removing the `Crushable` trait from the civilians work?

**Comment by ScottNZ** [comment]
I think it would be better to have your units not crush any neutral units at all (maybe unless explicitly told to with force-move).

**Comment by Snurre86** [comment]
Here I get +$35 for crushing these 5 civilians.
![openra game_2015_03_10_13_32_24_720](https://cloud.githubusercontent.com/assets/7798635/6574975/90ce939e-c72a-11e4-88d9-2c68bcf589e5.png)

**Comment by Snurre86** [comment]
Still happens in newest release 2015-04-24.
