### ISSUE TITLE
Units should shoot at enemies within range while they're moving in the AttackAnything stance

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#7566]
At least those units that can fire while moving. They wouldn't stop and engage the enemy like they do with attack move but they would shoot at them while they're passing by.
##

**Comment by penev92** [comment]
Agreed. You do have Force Move for when you want them **not** to shoot at stuff.

**Comment by deniz1a** [comment]
Or you can change stance to hold fire.

**Comment by pchote** [comment]
Turreted actors have always behaved like this.

**Comment by deniz1a** [comment]
But currently they don't shoot at enemies when a move order is given? They continue shooting while they move if they have already picked up a target but they don't pick up targets when they move.

**Comment by pchote** [comment]
Move orders are for moving. It sounds like you want an attack-move that works as described in #7567.

**Comment by deniz1a** [comment]
That sounds like a separate issue. What I suggested was to just use the turrets of tanks while they're moving. This wouldn't change the movement of units.

**Comment by LipkeGu** [comment]
#7340

**Comment by Mailaender** [comment]
They will continue to shoot if the correct stance is selected. I always smash stop to avoid my units wrecking havoc when I am about to capture something with low health.

**Comment by deniz1a** [comment]
They will continue shooting if they had already selected a target before move order was issued. But they will not pick up new targets while they're moving along the way. What I suggested was that they should pick up new targets along the way and shoot at them while moving as long as the target is within range. So this is a separate issue than to continue shooting. And when you press stop, the moving units start shooting like they do normally, so your second sentence doesn't make sense. And that is a separate issue too: #6170. So why was this issue closed?

**Comment by deniz1a** [comment]
And this is also the behaviour in Red Alert 2. There, the units don't fire at buildings by default but they will fire at other units while they're moving.

**Comment by Mailaender** [comment]
Please be more specific with your requests and don't mix them with unrelated things.

**Comment by deniz1a** [comment]
So is this a wontfix?

**Comment by Mailaender** [comment]
More like a WORKSFORME.

> Turreted actors have always behaved like this.

**Comment by pchote** [comment]
The request here is a bit different to our current behaviour: @deniz1a wants the auto-acquiring behaviour from our attack-move, but the attacking behaviour of our regular move (which currently only works if the unit already has a target).  I think this is a reasonable request for our AttackAnything stance, but the other modes should behave as they do now.

**Comment by deniz1a** [comment]
Yes, that's what I was trying to say.

**Comment by pchote** [comment]
Fixed by #16112.
