### ISSUE TITLE
Actors should lose targets

### ISSUE THREAD

**Issue by pevers** [OpenRA/OpenRA#7567]
Currently on bleed. I can do an attack move on a moving enemy and the unit will chase the target even if the unit disappears on under the shroud. I tested this by attacking an enemy MVC with a soldier and move the MVC over the whole map. The soldier will move until it is in range, but will not fire because the MVC is still under the shroud.

EDIT: Maybe I'm not 100% sure if this is true, I'll investigate this issue.

**Comment by pevers** [comment]
I think improving AutoTarget.cs will fix both issues regarding lines under the shroud https://github.com/OpenRA/OpenRA/issues/7498 and dropping invisible targets (but still moving to the last known location).

**Comment by LipkeGu** [comment]
#7340

**Comment by penev92** [comment]
Yes, a fix should close both issues. I don't think this will be very hard to do, considering that the Attack* activities check the target's state on every tick. So they only need one more check - whether the target is visible.

**Comment by Snurre86** [comment]
The target line on a hind will reveal the location of the target it was shooting at when had to go back and recharge until it is done recharging.

**Comment by penev92** [comment]
Even with #7547 closed, I'm still keeping the `Easy` label, because I gave a solution in my last comment.
I also want to add (regarding the target losing): Once you discover that the target is not visible (if it is an actor - `TargetType.Actor`) create a new target with `TargetType.Terrain` at the actual target's last known coordinates.
Note: `TargetType.FrozenActor` might need some considering.

**Comment by pevers** [comment]
@penev92 i was really busy but i can probably fix that next week.

**Comment by Phrohdoh** [comment]
Do not do Target = null, use Target.Invalid, please.

**Comment by pchote** [comment]
@penev92: Throwing away the target when it becomes invisible is easy, but fixing the gameplay elements that break when you do that will probably be much harder.

**Comment by penev92** [comment]
I know this might have some gameplay implications, but we can't be sure what until we see it ingame.
