### ISSUE TITLE
D2K - Game crashed when a sandworm is eating a lifting harvester.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#7568]
It happened on playtest.

Log is here;
http://www.mediafire.com/download/wb6wb48ghwzsdb3/exception3.log

**Comment by MicroJOo** [comment]
Dune 2000 Mod at Version playtest-20150118
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.NullReferenceException`: Nesne başvurusu bir nesnenin örneğine ayarlanmadı.
   konum: OpenRA.Mods.D2k.Traits.AutoCarryall.<Render>c__Iterator0.MoveNext()
   konum: OpenRA.Actor.<Renderables>c__Iterator14.MoveNext()
   konum: System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   konum: System.Linq.Enumerable.<ConcatIterator>d__71`1.MoveNext()
   konum: System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   konum: System.Linq.Enumerable.<ConcatIterator>d__71`1.MoveNext()
   konum: System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   konum: System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
   konum: System.Linq.Enumerable.<ConcatIterator>d__71`1.MoveNext()
   konum: System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   konum: System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   konum: OpenRA.Graphics.WorldRenderer.GenerateRenderables()
   konum: OpenRA.Graphics.WorldRenderer.Draw()
   konum: OpenRA.Game.RenderTick()
   konum: OpenRA.Game.Loop()
   konum: OpenRA.Game.Run()
   konum: OpenRA.Program.Run(String[] args)
   konum: OpenRA.Program.Main(String[] args)

**Comment by Mailaender** [comment]
Does this also happen in bleed? We already have a similar fix included: https://github.com/OpenRA/OpenRA/pull/7421.

**Comment by Mailaender** [comment]
The code has since been refactored. The AutoCarryall trait is gone now. Several fixes have been made to fix race conditions where pickup and harvesters death became a problem.
