### ISSUE TITLE
TD UI

### ISSUE THREAD

**Issue by xan2622** [OpenRA/OpenRA#7572]
Just some ideas, mock-ups that I have created for a possible TD UI.

![chrometd2](https://cloud.githubusercontent.com/assets/1732773/6432196/c1990bd6-c049-11e4-9c84-210d4e77f97e.png)
##

**Comment by penev92** [comment]
Pretty :)

**Comment by Bynnar18** [comment]
Just my opinion, but I think the metal should be darker kind of like the original TD UI.

**Comment by dan9550** [comment]
Would you be happy yo make a mock up with a darker grey texture like the original, with the green buttons, but buttons with the grey textured background rather than the black ones?

**Comment by Bynnar18** [comment]
I think that'd be preferable, but I can't really say until I see it. I just would prefer something more like the original.

**Comment by x-a-n-a-x** [comment]
> Just my opinion, but I think the metal should be darker kind of like the original TD UI.

Btw, by "original" TD UI, it depends on which game you are talking about:

![command-conquer-tiberian-dawn-mac-screenshot1](https://cloud.githubusercontent.com/assets/1732773/6446291/63608cee-c10a-11e4-9435-403bb92bf2b9.jpg)

or

![download-cc-tiberian-dawn](https://cloud.githubusercontent.com/assets/1732773/6446293/65ff657e-c10a-11e4-875c-813811f4f34b.png)

I would really prefer that we choose to go for a lighter UI. 

***

> Would you be happy yo make a mock up with a darker grey texture like the original, with the green buttons, but buttons with the grey textured background rather than the black ones?

Are we obliged to mimic the original UI ? I don't really like how it looks:

![fghjffawn2](https://cloud.githubusercontent.com/assets/1732773/6447114/224f8b8c-c110-11e4-93e4-49c3c63b2b13.png)

**Comment by pchote** [comment]
I think the right-hand version of the latest mockup looks great.

**Comment by Bynnar18** [comment]
I suppose, you're correct. I'm more fond of the non-DOS UI, but the right hand mockup does look pretty good. We might as well go with it if I'm the only one in opposition.

**Comment by x-a-n-a-x** [comment]
This is not my favourite UI (and it's an euphemism) but please, let me add some glass effect over these black buttons:

![224f8b8c-c110-11e4-93e4-49c3c63b2b13](https://cloud.githubusercontent.com/assets/1732773/6451635/11b104b6-c130-11e4-9cc4-9251c25ed0c8.png)

**Comment by RoosterDragon** [comment]
Black glass looks the best of the three to me.

**Comment by Bynnar18** [comment]
The right is definitely better. The tiny black outline makes the buttons more defined.

**Comment by StexoO** [comment]
Do you plan to mimic the power jauge there ?
![mimic](https://cloud.githubusercontent.com/assets/8930382/6461583/781cd560-c1a1-11e4-816b-95b18ea8b74d.jpg)

**Comment by Phrohdoh** [comment]
Agree with @RoosterDragon here.

**Comment by x-a-n-a-x** [comment]
> @StexoO said:
> Do you plan to mimic the power jauge there ?

Yes, that is more or less my plan.

**Comment by dan9550** [comment]
@x-a-n-a-x as reluctant as you are i love the work you've done mimicking the classic UI. I think it looks great.

our differences in opinion make me kind of wish we had selectable skins in a way just to make everyone happy.

**Comment by x-a-n-a-x** [comment]
I have temporarily postponed the TS UI to work on the RA2 UI https://github.com/Phrohdoh/oramod-ra2/issues/11. Btw, some ingame-player.yaml errors (for the TS UI) still block me from having a working and testable UI.

And even if I like the idea to have a "skins switcher" in the options, I doubt it will easily be implemented. How would they managed by OpenRA? And where will the chrome.yaml, ingame-player.yaml, and all the PNG file be stored? Wouldn't it create a mess in the OpenRA sub-folders tree?

**Comment by WolfGaming** [comment]
If we could make a texture pack kinda thing we could just put them in folders/zips and throw them in a texture pack directory.

We would need to decide though if the yaml files should be with the pngs, if we have only one static yaml (so all images need to be same size etc) or we introduce a system where the textur packs modify certain parts of the yaml.

I like the first option the best of these.

**Comment by Biofreak1987** [comment]
Any Progress on this?
I'm looking forward to the new TD UI

**Comment by x-a-n-a-x** [comment]
It's more or less postponed until I finish the RA2 UI.

**Comment by eukos16** [comment]
Really like the latest mockup.

**Comment by Biofreak1987** [comment]
Still nothing new about this ui redesign?

**Comment by x-a-n-a-x** [comment]
It is still postponed but you have just given me interest in finishing it.

**Comment by x-a-n-a-x** [comment]
Update : I am currently working on the yaml files. I think you can expect a first playable (but still WIP) demo of the interface by the end of the week-end.

**Comment by x-a-n-a-x** [comment]
The UI is getting along nicely but I am facing some problems:
- the whole mod UI has been broken (this is a little bit annoying, I admit)
- the horizontal factory switcher (with left and right arrows to select the next factory) is not there yet
- the production icons are not displayed even if I expand the MCV

So.. things are pretty much broken at the moment.
https://github.com/x-a-n-a-x/OpenRA/tree/TDUI

**Comment by pchote** [comment]
I've said it before, on IRC, but I'll add it here for completeness too: I've never liked the wide "concrete" edges around the build palette, and would strongly prefer if we kept that hanging out the bottom like we do in the current UI.  This UI feature distinguishes TD from our other mods, and evokes the feeling of the C&C3 sidebar: http://vignette4.wikia.nocookie.net/cnc/images/d/db/Command_Conquer_3-Tiberium_Wars.jpg/revision/latest?cb=20111130000812

**Comment by x-a-n-a-x** [comment]
I don't like them much either. To be honest, I planned to change the bottom part later. 
I didn't know that the idea was to mimick the C&C3 UI (that I like much, BTW).

By uploading an incomplete UI onto this branch, I just wanted to show a first draft of the UI, ingame.
I just wanted to have a working interface first, then the idea was to polish the UI afterward.

**Comment by pchote** [comment]
3 looks really good, IMO.

**Comment by dan9550** [comment]
2 over 1, 3 looks "modern" i think i would have to see it in game to decide though.

**Comment by x-a-n-a-x** [comment]
Branch https://github.com/x-a-n-a-x/OpenRA/tree/TDUI2 updated:
- new buttons
- the gray texture should be correctly displayed on all Settings windows
- glass effect added to buttons (only on the ingame sidebar interface)

TODO/bugs: 
- map previews should all have their frame similar to a "checkbox"  (check the replay browser as an example)
- the music tab features "panel-texture" as background. I tend to like it but other mods don't have that
- In Settings > Display: you can notice that a sentense is not readable because of its gray color
- all windows : the buttons placed at the bottom are overlapping 1px on the main window
textfield-focus color looks too vivid

**Comment by Biofreak1987** [comment]
It would be nice if you could also move the map timer and add the numeric power display like you did in your old previews... I just find the numeric stuff faster to read and the current map time just looks welll, you know.

**Comment by pchote** [comment]
If you pushed the production buttons together and to the right (so that there is no grey frame between the individual buttons – like C&C3 does in the image I linked above) there would be enough space to move the three order buttons to the left of them.  You would then have plenty of space above the minimap to display the cash, power, timer, and menu button.

**Comment by pchote** [comment]
I did some tweaks based on how I would like this to look/work (mainly making the buttons bigger, and getting rid of the multiple step levels).

![sidebar](https://cloud.githubusercontent.com/assets/167819/12373570/5eaf46c4-bc75-11e5-9e75-4f91001e1e34.png)

**Comment by x-a-n-a-x** [comment]
Here is my latest version of the UI (based on pchote's suggestions, on IRC):
https://github.com/x-a-n-a-x/OpenRA/tree/TDUI-pchotesidea_blurbg


TODO/Bug:
- [ ] Place a glass effect at the bottom (not shown on this ingame screenshot), over the Production Buttons (Buildings, Defense..) and over the Production Queue Tabs as well. 

![screenshot001](https://cloud.githubusercontent.com/assets/1732773/12430701/4a4ec546-bef1-11e5-987d-849a736dde9a.gif)

**Comment by Biofreak1987** [comment]
I do like the way this is turning out. The icons have been green in those older previews... did you drop that idea or will it be used for the nod version?

**Comment by pchote** [comment]
There are a couple of places where there is sharper contrast than IMO looks good:
* The sharp grey-black transition between the radar background and the cash line below it (both should be black, so that this is seamless)
* The sharp grey-black transition between the disabled production buttons and enabled ones. These should be made darker.

I also think it looks a bit odd to have the combined radar+cash bin taller than it is wide.  Chopping off 20 pixels to make it square looks more balanced.

Mockup with all suggestions:

![tweaked](https://cloud.githubusercontent.com/assets/167819/12432555/e1a8903c-bef3-11e5-9db1-46f11a761c5d.png)

**Comment by x-a-n-a-x** [comment]
My latest branch : https://github.com/x-a-n-a-x/OpenRA/tree/TDUI-pchotesidea_6

**Comment by Biofreak1987** [comment]
What happend to the green buttons and text? White looks a bit meh imo... otherwise I like it.

**Comment by GraionDilach** [comment]
I'd assume white is GDI, green is Nod.

**Comment by dan9550** [comment]
That is looking awesome.

**Comment by x-a-n-a-x** [comment]
Here is another alternative branch I have been working on (based on some pchote's comments on IRC): https://github.com/x-a-n-a-x/OpenRA/tree/TDUI-pchotesidea_7

![screenshot001](https://cloud.githubusercontent.com/assets/1732773/15808034/6ada9f40-2b6d-11e6-870e-038f6800a11c.png)

Question : do we really want to also add the timer in the middle of the UI (between the power and silo values)? as shown in this mockup: https://github.com/OpenRA/OpenRA/issues/7572#issuecomment-172232385

**Comment by Biofreak1987** [comment]
I would prefer if the map timer moves into the ui like it is the case for all the other mods. This would also open up some space that mappers can use to display mission specific info (See soviet07).

**Comment by x-a-n-a-x** [comment]
ok, I have just added the timer as well in my github branch.

**Comment by Biofreak1987** [comment]
Ok, after testing it:

- The old map timer still seems active
- I guess the green buttons from earlier designs got dropped?
- Could we display the faction emblem while the radar is not active?
- Regarding my last question, how difficult would it be to support the funpark emblem for said missions?
![cnc_funpark](https://cloud.githubusercontent.com/assets/4711816/15831963/5667ef50-2c20-11e6-9887-9d3917dca6e7.png)

**Comment by Biofreak1987** [comment]
Something that I've asked a few months back:
Will Nod and GDI share the same design or will there be variations? Like it's the case for all the other mods.

**Comment by Biofreak1987** [comment]
Anything new on this? Or is any sort of development pretty much on hold until the next stable is out?

**Comment by x-a-n-a-x** [comment]
Here is what I made today: 
![screenshot002](https://cloud.githubusercontent.com/assets/1732773/19004414/2b032320-8756-11e6-897f-aa39abae231c.png)

Todo:
- make the production tabs green (they are currently red)
- find a way to modify the font colors for power/time/cash labels (they are currently white)
- create a darker UI for the nod faction (with red colored labels/buttons)

**Comment by dan9550** [comment]
I like the green, the white on the UI looks a tad bland. other than that (+1)

**Comment by x-a-n-a-x** [comment]
Hmm.. You're the second person to prefer the green colors and I do prefer them too over the white buttons. I will wait for more feedback but if the consensus goes this way, I'll try to make the green UI more contrasted and make a PR (once this is all finished).

**Comment by pchote** [comment]
That specific use of soft green + gradient has poor contrast against the button and surrounding grey frame (with is bad for usability), and clashes pretty badly with the other greens that we use in the minimap and power bar.

**Comment by Sininini** [comment]
I think those buttons should be flat, currently they look out of place.

**Comment by dan9550** [comment]
If the buttons around the minimap were green including the power, game time, and cash indicators and values. that should be fine. The red borders around the build palette should be a grey.

In my head that sounds like a good idea. May need to tweak the power and cash bars for that to work.

**Comment by Biofreak1987** [comment]
Yeah, that green doesn't appear to work so well on the current design of the UI... but I'm not a fan of white either.

**Comment by Biofreak1987** [comment]
Is there any progress on this? I'm surprised that it isn't finished.

**Comment by dragunoff** [comment]
Overall I like the WIP displayed here and I think this definitely should be resurrected - the TD mod could use an UI upgrade as currently it is rather bland. 

A couple of functional enhancement would also be nice - especially adding the numbered power indicator, as right now you need to hover your mouse over the power bar to see the exact amount of power.

**Comment by xan2622** [comment]
I am resurrecting my work on the TD UI. For now, I have a branch with a single UI with white icons. 
https://github.com/xan2622/OpenRA/tree/TDUI-white

I still don't know how to make the Production Queues not red (the frame that surrounds the factories numbers and left and right arrows). If someone knows..

I plan to create another branch to demonstrate how it looks like with a GDI UI (green icons) and a NOD UI (red icons & maybe darker background texture).

**Comment by dragunoff** [comment]
I've tested the UI - great work :-) I realize this is a work in progress but I have a couple of remarks:

1) I was surprised when I saw the sad face emoticon on low power :-) How about simply making that power icon red?
2) Personally I prefer the white icons but I think that there is not enough contrast between currently selected tab and unavailble tabs. Even in the screenshot below the first tab(available, but not selected) pops out because it has more contrast than the rest. 
![openra-2018-01-31t233334658z](https://user-images.githubusercontent.com/1355810/35653533-749c3d20-06f1-11e8-9d18-81215890d76a.png) ![openra-2018-01-31t233334658z2](https://user-images.githubusercontent.com/1355810/35653534-74c41200-06f1-11e8-83f1-9869f0f4c373.png)

**Comment by xan2622** [comment]
Here are the PSD files, for those who want to integrate this sidebar UI into OpenRA.
There are git branches above that you can use to test the current state of the UI.

https://www.dropbox.com/sh/hi67giafc0zqu5e/AACWl4JKRSuHWXHRaTaA9_fIa?dl=0

**Comment by BenChricton78** [comment]
@xan2622 I'm going to integrate it into OpenRA. I'll test the state of the UI and see if it's ready.

**Comment by BenChricton78** [comment]
How do I integrate it into OpenRA?

**Comment by BenChricton78** [comment]
I've tested it. All I need to do now is replace the sad emoji with a red power symbol, and have the factions' symbols in the screen of the UI.

**Comment by pchote** [comment]
Adding to the milestone so that we don't forget this.

**Comment by dragunoff** [comment]
I've managed to make green production tabs and support power background for GDI. However tooltips are still red. I tried sorting that out but it's a whole other mess it seems... And I'm not sure whether I wanna go that way for GDI - perhaps because I'm so used to the red panels in TD :-)

![openra-2019-01-02t000247532z](https://user-images.githubusercontent.com/1355810/50577817-36fd3780-0e39-11e9-8542-b1b8441688a6.png)

**Comment by dragunoff** [comment]
Nod UI with light panels (same as GDI) but with red buttons. I feel like this is the best combo so far: light panels for both factions, with green buttons for GDI and red buttons for Nod.

![cnc-ui-nod--light](https://user-images.githubusercontent.com/1355810/50697695-a64a7580-104b-11e9-8ce4-12ec8ca57dbb.png)

**Comment by dragunoff** [comment]
**Test builds** with the new UI can be downloaded from here: 
https://drive.google.com/drive/folders/152J4jvXVkpINDhEQuEK1qgx039nuH3ti?usp=sharing

**Comment by xan2622** [comment]
Congratulations @dragunoff for finishing the work that I started a long time ago.
