### ISSUE TITLE
AAC Decoding

### ISSUE THREAD

**Issue by dan9550** [OpenRA/OpenRA#7575]
Am i  crazy? Just thought of this while researching AAC, not quite sure what libraries and things are out there but what are peoples thoughts on an AAC implementation if it is feasible?

I know we have had talks about Vorbis in the past, this could be an alternative.

**Comment by Mailaender** [comment]
https://en.wikipedia.org/wiki/Advanced_Audio_Coding#Licensing_and_patents

**Comment by dan9550** [comment]
my mistake :S in my defense it was late and i hadn't slept a lot.
