### ISSUE TITLE
AI use their harvester attack player base once give them weapon.

### ISSUE THREAD

**Issue by TGHoly** [OpenRA/OpenRA#7578]
I put the gun to Harvester it appear AI send them along with their army to attack my base and stop their harvesting activity entirely.

**Comment by DavidARussell** [comment]
Obviously not desirable behaviour, but it is quite logical from the AI's point of view: the harvester has heavy armour and lots of health, so if you give it a weapon then (to the AI) it suddenly looks like a super-heavy tank.

**Comment by TGHoly** [comment]
Yeah i also mass harvester attack Yuri player in Ra2YR quite often however it's stupid when you decide to All-in with all your harvesters anyway. :p
