### ISSUE TITLE
"Game settings" Tab in Settings menu

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#7583]
Here you can change in game behavior like:
- Default stances on different units/turrets (the default stance a units/turrets have when entering the world).
- If you want to empty the apc/transport helicopter etc. or just exit one unit when you press "unit command -Deploy" (default f) or press deploy directly on the unit. See #7604
- I̶f̶ ̶y̶o̶u̶ ̶w̶a̶n̶t̶ ̶u̶n̶i̶t̶s̶ ̶t̶o̶ ̶s̶h̶o̶t̶ ̶i̶n̶ ̶r̶a̶n̶g̶e̶ ̶t̶a̶r̶g̶e̶t̶s̶ ̶o̶n̶ ̶m̶o̶v̶e̶ ̶o̶r̶d̶e̶r̶s̶ ̶o̶r̶ ̶n̶o̶t̶ ̶(̶s̶e̶e̶ ̶#̶7̶5̶6̶6̶)̶

![5331a950-c25b-11e4-9195-024931d7d926](https://cloud.githubusercontent.com/assets/7798635/7874958/117e635a-05b7-11e5-9390-f943845a1f16.png)

##

**Comment by pchote** [comment]
This isn't really actionable, as we don't have any options that could be displayed in such a menu.  Please file separate issues for those.
