### ISSUE TITLE
Support (icon) sequence name variant for veterancy.

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#7585]
RA2 needs this for most trainable actors. [RA2 icon list](http://xhp.xwis.net/ra2_icons/).
`e2icon` -> `e2uico`.

**Comment by WolfGaming** [comment]
So this will basically be icon change on upgrade right?

Since we also need to activate an upgrade to instantly increase the veterancy on the produced unit I think that would be the best way.

**Comment by Phrohdoh** [comment]
Correct.

**Comment by pchote** [comment]
Option 2 of #7469 would allow this, but that is still a bit of a hack.

**Comment by Mailaender** [comment]
You may want to solve this with an overlay instead. https://github.com/OpenRA/OpenRA/issues/8210

> many of the RA2 units used beta variants of the cameos for upgraded (Crazy Ivan), was missing (Harrier, defences, navy can also gain veterancy in your logic, this was impossible even in Ares-enhanced YR), or went bogus (Cosmonaut to Laser Rocketeer).

**Comment by GraionDilach** [comment]
Take the overlay included in the RA1 mod - itself being a highre quality remake of the RA2 chevron featured on the RA2 cameos.
