### ISSUE TITLE
Copyright infringement: Sniper cameo

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#7588]
There is a problem with the Sniper icon. The cameo has to be modified as soon as possible.
Thanks to Tomsons26 for noticing this.

Original image:
http://stocktrek-images.artistwebsites.com/featured/image.html?catalogid=STK102163M

Our icon:
![screen shot 03-04-15 at 08 09 pm](https://cloud.githubusercontent.com/assets/1732773/6491170/bf2f4af4-c2ab-11e4-8d87-14419e33cc8a.PNG)

EDIT:
Who did it? 
We should also check the Zombie icon too.

**Comment by Mailaender** [comment]
I think @NukemBro contributed it.

**Comment by Unit158** [comment]
Are you sure this is infringement? Have we received a C&D letter?

**Comment by Mailaender** [comment]
If Stocktrek is the owner of the image and not just selling reprints of a public domain military photography, then this is violating http://www.stocktrekimages.com/licensing.asp

**Comment by chrisforbes** [comment]
I think this warrants talking to them about it.

**Comment by MicroJOo** [comment]
no , this icon is from a military site ... hang on , ill search for the link

**Comment by tomsons26** [comment]
No one said russia :/
Good to hear it's fine after all, its a fitting cameo.
Strange the wiki image did not pop up when i reverse searched it.

**Comment by MicroJOo** [comment]
@tomson26 : just saying , the flaktruk is from a russian site ... and we cant use that :/

**Comment by Phrohdoh** [comment]
Closing as we are definitely allowed to use this.
