### ISSUE TITLE
Copyright infringement: Mobile Flak cameo

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#7589]
There is a problem with the Mobile Flak icon. The cameo has to be modified as soon as possible.
Thanks to Tomsons26 for noticing this.

Original image, check the second image from the bottom:
http://tanks73.ru/btr40.html

Our image:
![screen shot 03-04-15 at 08 39 pm](https://cloud.githubusercontent.com/assets/1732773/6491602/a31f0748-c2ae-11e4-8e07-e4396f7d1818.PNG)

**Comment by x-a-n-a-x** [comment]
http://www.sleipnirstuff.com/forum/viewtopic.php?f=83&p=286374#286374

**Comment by Mailaender** [comment]
Pinging @katzsmile.

**Comment by Mailaender** [comment]
Asking for permission to use the photo as a basis (it is heavily edited and then transformed into pixel art) may be quicker than creating a new one.

**Comment by katzsmile** [comment]
Just made new icon http://www.sleipnirstuff.com/forum/viewtopic.php?f=83&p=288983#288983

**Comment by x-a-n-a-x** [comment]
Thanks @katzsmile. 
But as I told you on skype, I just think the canon is too big for the truck. Otherwise :+1: for using a cc image.

**Comment by OmegaBolt** [comment]
Something I did: https://www.dropbox.com/s/fodf4gacxfhf11d/FlakTruck.png?dl=0

Uses this image as a base which it says is public domain: http://en.wikipedia.org/wiki/BTR-40#/media/File:%D0%9C%D1%83%D0%B7%D0%B5%D0%B9_%D0%B2%D0%BE%D0%B5%D0%BD%D0%BD%D0%BE%D0%B9_%D1%82%D0%B5%D1%85%D0%BD%D0%B8%D0%BA%D0%B8_%D0%9E%D1%80%D1%83%D0%B6%D0%B8%D0%B5_%D0%9F%D0%BE%D0%B1%D0%B5%D0%B4%D1%8B,_%D0%9A%D1%80%D0%B0%D1%81%D0%BD%D0%BE%D0%B4%D0%B0%D1%80_%2829%29.jpg

**Comment by katzsmile** [comment]
please redo your cameo OmegaBolt. and this time try be more accurate

**Comment by penev92** [comment]
?

**Comment by Bynnar18** [comment]
What's wrong with his cameo? The truck seems a bit vibrant, it could use a darker texture in my opinion, but it looks accurate in design.

**Comment by OmegaBolt** [comment]
Personally katzsmile, yours looks more like an artillery than the flak truck that's ingame and I think lacks sharpness compared to the other RA cameos.

But I don't mind whether this goes into the mod or not, someone just posted that Wikipedia picture of it today suggesting a cameo should be made, so I had a go at it. If it's too inaccurate then don't use it.

**Comment by katzsmile** [comment]
i can even render, but just dont want to waste time for this.

**Comment by x-a-n-a-x** [comment]
Suggestion:
![flaktruck2](https://cloud.githubusercontent.com/assets/1732773/6653411/20732e3c-ca92-11e4-9ffd-b1545e83d0e5.png)

**Comment by OmegaBolt** [comment]
![sidebar](https://cloud.githubusercontent.com/assets/8225171/6653627/729ca3b0-ca91-11e4-9a6c-3eab4ecec76b.png)

**Comment by penev92** [comment]
:+1:

**Comment by Phrohdoh** [comment]
:+1:

**Comment by Bynnar18** [comment]
Other than the text needing to be "Flak Truck" :+1:

**Comment by OmegaBolt** [comment]
The unit is called Mobile Flak ingame.

**Comment by Bynnar18** [comment]
Oh my bad then, although I do think Flak Truck is better.

**Comment by Mailaender** [comment]
Can you file a pull request?
