### ISSUE TITLE
Provide a set of preset player colors to choose from.

### ISSUE THREAD

**Issue by Nelax** [OpenRA/OpenRA#7590]
I like the ability to make your player color a custom color but I also think it would be nice if we had preset colors to choose from or an ability to favorite certain colors. So for people who may like to use blue with Allies and red with Soviets or something similar with GDI/Nod, they wouldn't need to memorize the color selectors settings. Probably just polish, but I figure it would be a good feature.
##

**Comment by Smittytron** [comment]
Can now save custom colors with #14853.
