### ISSUE TITLE
InfiltrateForExplorationReset.

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#7596]
Necessary for RA2.
Infiltration of a radar resets the target's shroud to their current fog (anything not visible by units at that moment).

This is *not* [InfiltrateForExploration](https://github.com/OpenRA/OpenRA/wiki/Traits#infiltrateforexploration).

**Comment by Mailaender** [comment]
In fact it is. It already does it. The name is a a bit misleading and the https://github.com/OpenRA/OpenRA/wiki/Traits documentation has not been updated since the last release. See https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.RA/Traits/Infiltration/InfiltrateForExploration.cs
