### ISSUE TITLE
add bib to fake cronosphere 

### ISSUE THREAD

**Issue by MicroJOo** [OpenRA/OpenRA#7600]
![7cpxvbl](https://cloud.githubusercontent.com/assets/9139965/6526077/f6f322fe-c40d-11e4-9b98-5255add3c37d.png)

**Comment by abcdefg30** [comment]
I think you're mixing things up... the "real" chronosphere has a bib.

**Comment by MicroJOo** [comment]
thank you but @penev92 allready told me
