### ISSUE TITLE
More benefits for keeping the radar online

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#7605]
Possible handicaps for off-lining the radar:
1. Not reveal the fog of war around it if offline.
2. Not detect cloaked units if offline.
3. Still use -20 power when offline.
4. Same health as fake radar when offline.
5. Radar tech tree is disabled if radar is offline.

Possible benefits for on-lining the radar:
1. Make the radar screen more attractive (details not coming).
2. Make units that need radar to be built shot 1 cell longer if radar is online.
3. Make units that need radar to be built more accurate if the radar is online.
4. Make units that need radar to be built see 1 cell longer if radar is online.

Other:
I think there should be an arrow on the screen showing where a beacon is placed before a radar has been possible to build or on lower tech levels.

![openra game_2015_03_10_09_56_12_884](https://cloud.githubusercontent.com/assets/7798635/6571726/cc6606fe-c70b-11e4-81f7-4eea39f66b2b.png)
##

**Comment by deniz1a** [comment]
Same health as fake radar is not good.

**Comment by Mailaender** [comment]
See also https://github.com/OpenRA/OpenRA/issues/3769.

**Comment by abcdefg30** [comment]
> 2) Not detect cloaked units if offline.
> 4) Don't detect cloaked units.

What's the difference here?

**Comment by Snurre86** [comment]
denisuana you can't just add a statement with no arguments.

**Comment by ScottNZ** [comment]
I proposed a while ago to have the radar dome (and other buildings that require power) not provide prerequisites if they are powered down. So you'll need a powered radar dome to build things that require a radar dome etc

**Comment by Snurre86** [comment]
ScottNZ: Well it would help some but you would still just power on and off as needed?

**Comment by ScottNZ** [comment]
Some important units require the radar dome (hind, arty are two notable Allied examples), so I can see people leaving it up permanently.

**Comment by Snurre86** [comment]
ScottNZ: what happens to the hind, arty when radar is offline you suggest?

**Comment by ScottNZ** [comment]
Nothing, but since most players build them constantly it should be fine to do this.

**Comment by Snurre86** [comment]
Some good players don't tech up at all I find, I don't want to encourage that I think.

**Comment by ScottNZ** [comment]
Not really convinced that this is a bad idea tbh

**Comment by Snurre86** [comment]
Added to possible handicaps, I don't know if it alone is enough, that's all.

**Comment by MicroJOo** [comment]
sry @ScottNZ ... but losing the requirements just by powering them down is ridiculous ...  
thats is what you cant built : 

AA , Helipad , SamSite , Airfields , Snipers* , Artys , V2s .... Destroyers ... 

i would understand when we lose the requirements when a radar-dome is destroyed ... but not by powering it down

**Comment by Snurre86** [comment]
Also an issue about it based on losing your power plant = losing your radar.

**Comment by Snurre86** [comment]
We are open to suggestions about how to make the radar screen/radar online more attractive, that is what this issue is all about.

**Comment by akhilman** [comment]
I propose to make radar just like Aliases GPS but only inside coverage area. This also will make GAP generator much more useful.

**Comment by Snurre86** [comment]
akhilman how does that differ from right now?

**Comment by akhilman** [comment]
@Snurre86 right now radar dome have view field slightly larger then all other units. I suggest to decrease view filed but make radar dome mark units with symbols like GPS Satellite does but only around radar itself. This GPS like field might be like two or three times larger then current radar dome view field. Of course radar dome should work only while powered on. This changes will increase value of radar dome as defence building.

**Comment by Snurre86** [comment]
That  will also make radar placement really aggressive I think which will make people want them more tanky. I don't know right now might think about it later.

**Comment by Micr0Bit** [comment]
i think i did discuss that before, but there was the idea to cut off all communication (text-chat and beacons) as long as you do not have a radar being online.

This got rejected though, because the UI affecting the gameplay in such a way is a "no-no".

**Comment by MustaphaTR** [comment]
I still think #12272 should be considered. I told about that to @SoScared on IRC and would be happy if will  be included in his balance tests.

**Comment by Smittytron** [comment]
Low vision and loss of stealth detection have been implemented. I don't see any of the other requests on this ticket happening.
