### ISSUE TITLE
Add an install-like option to the windows make script

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#7613]
tomsons26 requested on IRC a way to separate out the compiled/runnable game files from the source code to simplify distribution of WIP rewire test builds.  This is basically the same functionality as our `make install` option under linux/osx, so it would make sense to port this behaviour to windows.

This should not package an installer or do any other installer-like things.
##

**Comment by Phrohdoh** [comment]
:+1:

**Comment by abcdefg30** [comment]
This is likely obsolete now with the ModSDK.
