### ISSUE TITLE
actors/ressources overlapping units

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#7615]
this is probably a rambling issue through all mods (especially d2k) ... in red alert a couple if civilian - structures ( the corn - fields for example) ... didnt check TD 
definitely not a release blocker , but its noticeable since a couple of years now 

![overlap2](https://cloud.githubusercontent.com/assets/9139965/6543365/4859e9e6-c519-11e4-82b3-d5bed75e4cc7.png)
##

**Comment by Mailaender** [comment]
This may be fixable by tweaking the ZOffset in https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/sequences/misc.yaml#L635

**Comment by Smittytron** [comment]
This was fixed by #19137
