### ISSUE TITLE
Dependency issues with new OBS packaging for Fedora 21.

### ISSUE THREAD

**Issue by PanzerFurrry** [OpenRA/OpenRA#7620]
Release-20141029 fails to install on Fedora 21 due to dependency problems.

Steps to reproduce:
* Download Package for Fedora 21 '_openra-20141029-3.1.noarch.rpm_' from OBS http://software.opensuse.org/download.html?project=games:openra&package=openra as instructed from official page http://www.openra.net/download/ . 

* yum localinstall openra-20141029-3.1.noarch.rpm returns error due to dependency issue.

-----

Fedora 21 comes with packages lua-5.2.2-8 and compat-lua-libs-5.1.5-2, however the new OBS installer requires compat-lua-libs-5.1.4 and refuses to proceed with installation. 

> yum localinstall openra-20141029-3.1.noarch.rpm 
Loaded plugins: langpacks
Examining openra-20141029-3.1.noarch.rpm: openra-20141029-3.1.noarch
Marking openra-20141029-3.1.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package openra.noarch 0:20141029-3.1 will be installed
--> Processing Dependency: compat-lua-libs = 5.1.4 for package: openra-20141029-3.1.noarch
--> Finished Dependency Resolution
Error: Package: openra-20141029-3.1.noarch (/openra-20141029-3.1.noarch)
           Requires: compat-lua-libs = 5.1.4
           Installed: compat-lua-libs-5.1.5-2.fc21.x86_64 (@fedora)
               compat-lua-libs = 5.1.5-2.fc21
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

NOTES: 
* Playtest-20150118 doesn't suffer from this issue, .rpm installs against compat-lua-5.1.5-2.fc21

* Old manually build version '_openra-release.20141029-1.noarch.rpm_' installs without issues

------
uname -a
Linux 3.18.7-200.fc21.x86_64 #1 SMP Wed Feb 11 21:53:17 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Mailaender** [comment]
I backported the fix to the release https://build.opensuse.org/package/rdiff/games:openra/release?linkrev=base&rev=16 Can you try and report back once the build finishes and the mirrors synced?

**Comment by PanzerFurrry** [comment]
This new build '_openra-20141029-4.1.noarch.rpm_' installs without errors.

> yum localinstall openra-20141029-4.1.noarch.rpm 
Loaded plugins: langpacks
Examining openra-20141029-4.1.noarch.rpm: openra-20141029-4.1.noarch
Marking openra-20141029-4.1.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package openra.noarch 0:20141029-4.1 will be installed
--> Finished Dependency Resolution
Installed:
  openra.noarch 0:20141029-4.1
