### ISSUE TITLE
cant see the worm eating my harvester 

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#7621]
![worm eating](https://cloud.githubusercontent.com/assets/9139965/6546966/7b98a798-c5c8-11e4-91d5-95ce52ac44c5.png)

when the worm-swallow gets triggered  ... the owner + friends of the vehicle should always see the worm - animation imo (before the fog comes back)
##

**Comment by penev92** [comment]
I'm not convinced about the "Dune 2000" label. This is the case in all mods when you lose a unit - you instantly lose visibility. I think a workaround for that specifically for the worms will be just a big hack.
We could, however, keep player visibility of the area for a second after an actor dies, which will also fix this.

**Comment by MicroJOo** [comment]
for other units  atleast you always have a  "death animation" before its getting dark
