### ISSUE TITLE
not possible to take a screenshot in the replay mode

### ISSUE THREAD

**Issue by emrekoc-uvt** [OpenRA/OpenRA#7624]
Prtscreen returns a screenshot of the initial screen not the actual screen. I use windows 8.1.

**Comment by MicroJOo** [comment]
this is true , i do use fraps to get some screenshots ... because i get this here when using Prtscreen : 

![openra screen](https://cloud.githubusercontent.com/assets/9139965/6547846/063905fc-c5e5-11e4-8a7e-60705bd5294a.png)

**Comment by penev92** [comment]
I've noticed that I get ^ when trying to take screenshots in Fullscreen mode (replay or ingame).
I've tried the Windows Print Screen, I've tried the Windows Snipping tool, and I've tried [Lightshot](https://app.prntscr.com/en/index.html).
Works in Windowed mode, though.
I suspect this is a OpenGL and/or Windows problem.

**Comment by Mailaender** [comment]
Never had any problems with https://www.kde.org/applications/graphics/ksnapshot so this is probably a Windows related issue. No idea how to fix it though.

**Comment by penev92** [comment]
@emrekoc-uvt can you confirm that this happens only in replay mode for you? And does windowed/fullscreen matter?

**Comment by LipkeGu** [comment]
no i get this also in the entire game =(

**Comment by Snurre86** [comment]
It might be a OpenGL and/or Windows problem, but I get it to work only if I use MSI Afterburner to take screenshots!
This is also the case in the original TD/Red Alert on Windows 7.
