### ISSUE TITLE
[TS] crash when trying to set up players

### ISSUE THREAD

**Issue by MicroJOo** [OpenRA/OpenRA#7627]
did want to figure out how to acutally set up player ... (@pchote  "ingame map editor branch")
placed some "player icons" on the map ... and then i swiched to "multi1 / multi0" ... tried to place them on the map ... crashed 

http://pastebin.com/ktpB4UAQ

Tiberian Sun Mod at Version {DEV_VERSION}
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.18408
Exception of type `System.ArgumentNullException`: Der Wert darf nicht NULL sein.
Parametername: key
   bei System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei OpenRA.ReadOnlyDictionary`2.get_Item(TKey key) in d:\OpenRA-ingame-map-editor\OpenRA.Game\Primitives\ReadOnlyDictionary.cs:Zeile 77.
   bei OpenRA.Mods.Common.Widgets.MapEditorWidget.HandleMouseInput(MouseInput mi)
   bei OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) in d:\OpenRA-ingame-map-editor\OpenRA.Game\Widgets\Widget.cs:Zeile 353.
   bei OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) in d:\OpenRA-ingame-map-editor\OpenRA.Game\Widgets\Widget.cs:Zeile 344.
   bei OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) in d:\OpenRA-ingame-map-editor\OpenRA.Game\Widgets\Widget.cs:Zeile 344.
   bei OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) in d:\OpenRA-ingame-map-editor\OpenRA.Game\Widgets\Widget.cs:Zeile 344.
   bei OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) in d:\OpenRA-ingame-map-editor\OpenRA.Game\Widgets\Widget.cs:Zeile 344.
   bei OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi) in d:\OpenRA-ingame-map-editor\OpenRA.Game\Widgets\Widget.cs:Zeile 344.
   bei OpenRA.Widgets.Ui.HandleInput(MouseInput mi) in d:\OpenRA-ingame-map-editor\OpenRA.Game\Widgets\Widget.cs:Zeile 90.
   bei OpenRA.DefaultInputHandler.<>c__DisplayClass7.<OnMouseInput>b__6() in d:\OpenRA-ingame-map-editor\OpenRA.Game\Input\InputHandler.cs:Zeile 49.
   bei OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn) in d:\OpenRA-ingame-map-editor\OpenRA.Game\Sync.cs:Zeile 182.
   bei OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input) in d:\OpenRA-ingame-map-editor\OpenRA.Game\Input\InputHandler.cs:Zeile 49.
   bei OpenRA.Renderer.Sdl2.Sdl2Input.PumpInput(IInputHandler inputHandler) in d:\OpenRA-ingame-map-editor\OpenRA.Renderer.Sdl2\Sdl2Input.cs:Zeile 86.
   bei OpenRA.Renderer.Sdl2.Sdl2GraphicsDevice.PumpInput(IInputHandler inputHandler) in d:\OpenRA-ingame-map-editor\OpenRA.Renderer.Sdl2\Sdl2GraphicsDevice.cs:Zeile 286.
   bei OpenRA.Graphics.Renderer.EndFrame(IInputHandler inputHandler) in d:\OpenRA-ingame-map-editor\OpenRA.Game\Graphics\Renderer.cs:Zeile 156.
   bei OpenRA.Game.RenderTick() in d:\OpenRA-ingame-map-editor\OpenRA.Game\Game.cs:Zeile 531.
   bei OpenRA.Game.Loop() in d:\OpenRA-ingame-map-editor\OpenRA.Game\Game.cs:Zeile 632.
   bei OpenRA.Game.Run() in d:\OpenRA-ingame-map-editor\OpenRA.Game\Game.cs:Zeile 650.
   bei OpenRA.Program.Run(String[] args) in d:\OpenRA-ingame-map-editor\OpenRA.Game\Support\Program.cs:Zeile 111.

**Comment by Mailaender** [comment]
This happened on an unknown and probably outdated revision. Please re-open if this also happens in the current playtest-20150531.
