### ISSUE TITLE
Add a changelog entry for the PRs that move generic RTS code to Mods.Common

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7629]
I've been wanting to do this for a long time and I finally got some time. Since it is quite the changelog entry, and some PRs on it are pretty old (but still undocumented) I wanted to run it here first for a quick discussion, to see if there are objections.
I went through [the Common project file's history](https://github.com/OpenRA/OpenRA/commits/bleed/OpenRA.Mods.Common/OpenRA.Mods.Common.csproj) and got almost all PRs.

Here is the result:
* Moved generic RTS code to the `OpenRA.Mods.Common` project. [[#6511](https://github.com/OpenRA/OpenRA/pull/6511), [#6493](https://github.com/openra/openra/pull/6493), [#6521](https://github.com/openra/openra/pull/6521), [#6536](https://github.com/openra/openra/pull/6536), [#6632](https://github.com/openra/openra/pull/6632), [#6640](https://github.com/openra/openra/pull/6640), [#6663](https://github.com/openra/openra/pull/6663), [#6667](https://github.com/openra/openra/pull/6667), [#6705](https://github.com/openra/openra/pull/6705), [#6714](https://github.com/openra/openra/pull/6714), [#6723](https://github.com/openra/openra/pull/6723), [#6727](https://github.com/openra/openra/pull/6727), [#6682](https://github.com/openra/openra/pull/6682), [#6852](https://github.com/openra/openra/pull/6852), [#6733](https://github.com/openra/openra/pull/6733), [#6732](https://github.com/openra/openra/pull/6732), [#6894](https://github.com/openra/openra/pull/6894), [#6897](https://github.com/openra/openra/pull/6897), [#6898](https://github.com/openra/openra/pull/6898), [#6906](https://github.com/openra/openra/pull/6906), [#6917](https://github.com/openra/openra/pull/6917), [#6921](https://github.com/openra/openra/pull/6921), [#6963](https://github.com/openra/openra/pull/6963), [#7013](https://github.com/openra/openra/pull/7013), [#7036](https://github.com/openra/openra/pull/7036), [#7106](https://github.com/openra/openra/pull/7106), [#7107](https://github.com/openra/openra/pull/7107), [#7122](https://github.com/openra/openra/pull/7122), [#7129](https://github.com/openra/openra/pull/7129), [#6964](https://github.com/openra/openra/pull/6964), [#7153](https://github.com/openra/openra/pull/7153), [#7157](https://github.com/openra/openra/pull/7157), [#7162](https://github.com/openra/openra/pull/7162), [#7194](https://github.com/openra/openra/pull/7194), [#7254](https://github.com/openra/openra/pull/7254), [#7263](https://github.com/openra/openra/pull/7263), [#7271](https://github.com/openra/openra/pull/7271), [#7282](https://github.com/openra/openra/pull/7282), [#7295](https://github.com/openra/openra/pull/7295), [#7316](https://github.com/openra/openra/pull/7316), [#7316](https://github.com/openra/openra/pull/7316), [#7337](https://github.com/openra/openra/pull/7337), [#7307](https://github.com/openra/openra/pull/7307), [#7354](https://github.com/openra/openra/pull/7354), [#7435](https://github.com/openra/openra/pull/7435), [#7436](https://github.com/openra/openra/pull/7436), [#7564](https://github.com/openra/openra/pull/7564)]

(Just for storage: http://pastebin.com/X6imrmmB)

**Comment by penev92** [comment]
Also I'm not sure what to do with #6673 and #7606.

**Comment by WolfGaming** [comment]
It seems as though #7606 already has a pretty good changelog so I dont think it needs to be in this one.
The changelog at #6673 doesnt really tell you what that PR did so I think it should be in this changelog entry.

Those are my opinions at least :)

**Comment by deniz1a** [comment]
Wait. Then should there also be a changelog entry for this PR?

**Comment by Phrohdoh** [comment]
These movements are just namespace maintenance so I see no need for a changlog entry. :-1:

**Comment by pchote** [comment]
Seems reasonable to document these, so :+1: from me as long as you put them all in the right parts of the changelog (the earlier ones in your list were done in earlier releases, and shouldn't be grouped with the new ones).

**Comment by penev92** [comment]
>These movements are just namespace maintenance so I see no need for a changelog entry.

Apart from the massive amount of work that went in there, there are 2 good reasons to have an entry:
1. The project is no longer one giant mess (well there are smaller messes in it, but those are totally different). Six months ago the solution was pretty horrific. We finally have a well-structured project architecture.
2. I was thinking people need to be made aware that the solution is not as horrible any more months ago. [This post](http://www.ppmsite.com/forum/viewtopic.php?p=525111#525111) just confirms my point.

**Comment by Mailaender** [comment]
:+1: Some people at ppmsite.com were unaware of our undertaking and thought modders still have to heavily rely on the Red Alert DLL.

**Comment by obrakmann** [comment]
[Fixed](https://github.com/OpenRA/OpenRA/wiki/Changelog/_compare/2bd53a02671b23485ac212828cb946eb82111519%5E...2bd53a02671b23485ac212828cb946eb82111519)

**Comment by penev92** [comment]
Thanks.
