### ISSUE TITLE
Conditional sequence enable/disable. [$50]

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#7632]
TS and RA2 will need this.

Examples being the GDI radar and the Allied service depot (and conyards).

**Comment by Mailaender** [comment]
Already implemented in https://github.com/OpenRA/OpenRA/issues/5124, https://github.com/OpenRA/OpenRA/pull/5138, https://github.com/OpenRA/OpenRA/pull/5134 and https://github.com/OpenRA/OpenRA/pull/5373.
