### ISSUE TITLE
Screenshot on Wikipedia and ModDB is horribly outdated

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#7642]
The screenshot at http://en.wikipedia.org/wiki/Command_%26_Conquer:_Red_Alert and the header background at http://www.moddb.com/games/openra clearly show the old sidebar layout and one infantry per cell.  This means it is at least 4 years out of date.

It should be simple for someone with edit access to add a recent screenshot that at least includes the new RA sidebar.

**Comment by penev92** [comment]
Also after #7540 has been merged, maybe it's time to fix the mod description on the ModDB's page.

**Comment by Snurre86** [comment]
I think Matthias Mailänder has to update a new picture on commons as it is in his account and it is non-free. I have no access to http://www.moddb.com/games/openra.

**Comment by MustaphaTR** [comment]
I should also update pictures in Turkish Wikipedia. They are also  with old menus. https://tr.wikipedia.org/wiki/OpenRA

**Comment by Snurre86** [comment]
You could try but they might just get deleted.

**Comment by deniz1a** [comment]
Should OpenRA have its own article on Wikipedia?

**Comment by Phrohdoh** [comment]
I do not think there is enough content to justify a Wikipedia article.

**Comment by Mailaender** [comment]
http://gaming.wikia.com/wiki/Encyclopedia_Gamia may be a better place.

**Comment by deniz1a** [comment]
Spring rts has its own page: http://en.wikipedia.org/wiki/Spring_Engine
Maybe after openra gets ts and ra2 mods officially then it would be worth creating a new article.

**Comment by Mailaender** [comment]
I see not a single reliable secondary source on that article. That page pretty much fails https://en.wikipedia.org/wiki/Wikipedia:Notability so it is a very bad example.

Regarding this topic. Everyone has access to ModDB and Wikipedia to upload a current screenshot.

**Comment by Mailaender** [comment]
Similar sites that allow users to upload screenshots which could need an update

* http://www.mobygames.com/game/openra/screenshots
* http://osgameclones.com/#Command%20&%20Conquer-clones
* http://www.holarse-linuxgaming.de/wiki/openra
* http://wiki.ubuntuusers.de/Spiele/OpenRA#Bildschirmfotos

The main problem is the lack of any/good screenshots in suitable size/formats.

**Comment by Mailaender** [comment]
Maybe SDL2 is making things hard for players especially on Windows so brought back an improved version of an in-game screenshot function in https://github.com/OpenRA/OpenRA/pull/7930 again.

**Comment by MustaphaTR** [comment]
I have uploaded new ScreenShots to OpenRA page Turkish Wikipedia and RA page in English Wikipedia.

**Comment by Mailaender** [comment]
You are aware that you are violating the https://commons.wikimedia.org/wiki/Commons:Screenshots rules by uploading screenshots of the Freeware assets?!

**Comment by MustaphaTR** [comment]
[İncelemeelemanı](https://tr.wikipedia.org/wiki/Kullan%C4%B1c%C4%B1_mesaj:%C4%B0ncelemeelemani) said me i can upload OpenRA screenshots to Commons. I also not had problem about them.

**Comment by pchote** [comment]
Great, thanks @MustaphaTR.  That just leaves a new 950x150 image for the moddb header, and a 1024x768 image for the moddb preview.

**Comment by x-a-n-a-x** [comment]
I have updated headers for google+, facebook, moddb and desura.

**Comment by Mailaender** [comment]
Thanks!
