### ISSUE TITLE
Boats get stuck in naval yard

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#7643]
Here you can see me placing the naval yard next to the south edge but this happens close to shore as well.
![openra game_2015_03_11_12_37_39_035](https://cloud.githubusercontent.com/assets/7798635/6595583/ea6e6232-c7eb-11e4-88d9-a005e66d0957.png)

**Comment by penev92** [comment]
This also happens when you block this, or any of your other production structures. The units have nowhere to go, as the exit is blocked. Not really an issue, as long as you don't do it on purpose.

**Comment by Snurre86** [comment]
I did build two boats before this one got stuck.

**Comment by obrakmann** [comment]
This is not a bug.

**Comment by Phrohdoh** [comment]
It is an annoyance though.
Perhaps we should check a (configurable) range of tiles for accessibility for each exit?

**Comment by Snurre86** [comment]
Well it did ruin the mission and a restart was needed.
