### ISSUE TITLE
Tile glitch in D2k

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7651]
I was spamming the Grow Resources button when this little visual glitch happened:
![](http://i.imgur.com/7pt0CfJ.png)
The tiles were OK up until that point. I am guessing this is due to a wrong tile definition (transition tile defined as sand, so the spice was able to "grow" there and replace it), but I can't investigate that now.

**Comment by pchote** [comment]
Duplicate of #4243.  This affects a bunch of tiles.
