### ISSUE TITLE
Put game options in lobby under the map

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#7655]
There is enough room to put the options under the map preview in lobby, if the chat area is reduced in width. Here's a crude mockup of how it could be done. A slight size adjustment may be needed but this would bring a noticable advantage I think.

![lobbysettings](https://cloud.githubusercontent.com/assets/6599106/6630564/f24e5f38-c922-11e4-92a1-2fd5633fe2d9.png)

**Comment by deniz1a** [comment]
There is some room to enlarge the whole window so there is more room to put options. Below is the lobby screen on 1024x768 resolution.

![lobby1024x768](https://cloud.githubusercontent.com/assets/6599106/6630803/b182489a-c925-11e4-93f9-f4f2719257b5.png)

**Comment by x-a-n-a-x** [comment]
I have created another mockup image, with correct checkboxes locations and placement.
The only way to make all these options fit in this "frame" would be to add a vertical scrollbar (imo):

![screenshot001](https://cloud.githubusercontent.com/assets/1732773/6633423/96fa6d22-c948-11e4-81bd-0e38212343bb.gif)

**Comment by pizzaoverhead** [comment]
Fit the chat input field width to the chat window's width and move the Start Game button to the right of the Back button.

Standard convention is to have a form's accept button in the bottom right, with its cancel button to the left of it. When I first started playing OpenRA, I often found myself accidentally backing out of the lobby by reflex.

**Comment by x-a-n-a-x** [comment]
![screenshot001](https://cloud.githubusercontent.com/assets/1732773/6645311/b2bd0326-c9bb-11e4-9048-9ac81f84dac5.gif)

**Comment by abcdefg30** [comment]
Hm, what about having the `Back` button nearby the chat input (on the right of it)?

**Comment by x-a-n-a-x** [comment]
![17c6](https://cloud.githubusercontent.com/assets/1732773/6645954/b4c114fa-c9c0-11e4-828c-ad1ed8d2b9f4.gif)

**Comment by penev92** [comment]
This looks good.

**Comment by RoosterDragon** [comment]
Bikesheddy opinion: This is making the UI pretty crowded/busy.

**Comment by pchote** [comment]
> Bikesheddy opinion: This is making the UI pretty crowded/busy.

I agree. It also requires more user interaction than the existing setup because you need to manually scroll the panel to view all of them, instead of just clicking the options button.

**Comment by obrakmann** [comment]
I agree with the "too crowded" assessment.  What I personally would like to see is to have the players and options dialogs in tabs instead.

**Comment by pchote** [comment]
This conflicts with the new design of the lobby with the new global chat, so isn't feasible.
