### ISSUE TITLE
unable to repair silos that sit behind the refinery

### ISSUE THREAD

**Issue by jimmywatson** [OpenRA/OpenRA#7662]
If you build a refinery in RA mod then build two silos behind the refinery. Upon the silo and refinery taking damage from a nuke, you are only able to repair the refinery and not the two silos.

Logic currently allows the user to build silos behind the refinery, however on mouseover or touch the refinery is selected rather than the silo.

Asset:
R = refinery
O = silo

ORO
RRR
RRR
RRR

Logic:
R = refinery
O = silo

RRR
RRR
RRR
RRR

Also replicated on mouse and keyboard. Occurs in stable, playtest and bleed.

**Comment by Mailaender** [comment]
Very similar to https://github.com/OpenRA/OpenRA/issues/3871

**Comment by jimmywatson** [comment]
True, looking at the logic it appears the the top section of the refinery is overlaying the base tile of the silo - possibly due to it being built first (and possibly other tiles looking at the other bug report) tile for the refinery or first object planted. Going to try building the silo first, then the refinery to see if the first base tile takes precedence.

**Comment by obrakmann** [comment]
So similar that it's a duplicate ;)

**Comment by jimmywatson** [comment]
Just tested, with the silo being built first it does seem to allow repair. Might be engine related to how it handles base tiling and select-able objects that may have overlapping tiles. 
![logic](https://cloud.githubusercontent.com/assets/11268975/6651644/14618830-ca44-11e4-9a5e-3b2e1e6e8e22.png)

**Comment by deniz1a** [comment]
Actually this is not a duplicate of #3871. This one is about unreachable actors, #3871 is about unreachable map cells. The latter will be fixed by comparing cursor position to OccupiedCells() I think.

**Comment by deniz1a** [comment]
This was fixed in #8388.
