### ISSUE TITLE
kennel placement is blocking dogs from spawning

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/OpenRA#7663]
if you aren't careful while you are placing your kennel building you might end up placing it 1 cell north of another building or unwalkable terrain. The result is that your dogs can't get spawned in front of the kennel.

Suggestion: 
- make a 2 celled building, add a 1 cell bib infront the kennel

**Comment by WolfGaming** [comment]
Or make it so the dogs can go out the front or right side of the building.

**Comment by x-a-n-a-x** [comment]
I confirm the bug. So for the moment we can't sing: https://www.youtube.com/watch?v=He82NBjJqf8 (cause dogs are blocked in the kennel).

![screenshot002](https://cloud.githubusercontent.com/assets/1732773/7429740/5f2bde4a-f007-11e4-9ee5-d289817c08e5.png)

**Comment by Phrohdoh** [comment]
This is just a case of the kennel only having a single `Exit`, which is being blocked.

**Comment by TheRaffy** [comment]
Does other buildings have more than one exit?

**Comment by Phrohdoh** [comment]
Most do, but there are a few that were overlooked.

**Comment by TheRaffy** [comment]
Found the structure.yaml:
Okey, If I'd like to add more exits, what values would make sense?

...
KENN:
	.....
	RallyPoint:
		RallyPoint: 0,2
	Exit:
		SpawnOffset: -280,400,0
		ExitCell: 0,1
...
TENT:
	Bib:
	RallyPoint:
	Exit@1:
		SpawnOffset: -42,810,0
		ExitCell: 0,2
	Exit@2:
		SpawnOffset: -725,640,0
		ExitCell: 0,2

**Comment by GraionDilach** [comment]
I don't think another exit would make sense considering that the kennel has only only one visual exit (barracks have two). I'd moreso consider making the cell in front of the kennel to a bib.

**Comment by TheRaffy** [comment]
I don't know maybe the kennel has a second opening in the back :D^^ No, you'r right!

**Comment by Unit158** [comment]
There should be an exit that goes to the side imo. It looks like the dog should be able to get out of the kennel via the front then going sideways.

**Comment by penev92** [comment]
Bottom line is if you want to block it - you can, and there is nothing the game (or developers) can do about it.

**Comment by TheRaffy** [comment]
I disagreee penev, there's a huge difference between a bulidng that is blocked by a unit and a building that is blocked just because you build it. Every building besides the kennel has at least a bib infront of the structure, which creates space for units to spawn. This Post is not about blocking buildings with a tank for example. Rather about placing can make the building useless.

**Comment by Unit158** [comment]
We don't have 1 cell bibs afaik, you'd need to make them.

**Comment by TheRaffy** [comment]
So the asset of a bibis missing (verticalley 2 cells) ?

**Comment by Unit158** [comment]
It's not missing. It doesn't exist. I'm somewhat doubtful it ever will.

**Comment by TheRaffy** [comment]
![temperate-bib-0001](https://cloud.githubusercontent.com/assets/5147014/9112468/0ebddaf0-3c4f-11e5-8792-3875859583af.png)
![desert-bib4-0000](https://cloud.githubusercontent.com/assets/5147014/9112470/0ec449ee-3c4f-11e5-9f42-7f819d5fe78a.png)
![desert-bib4-0001](https://cloud.githubusercontent.com/assets/5147014/9112469/0ebeb9e8-3c4f-11e5-9861-b3c52e7cc0a7.png)
![snow-bib4-0000](https://cloud.githubusercontent.com/assets/5147014/9112471/0ec4ed7c-3c4f-11e5-9b73-ec8312e1b773.png)
![snow-bib4-0001](https://cloud.githubusercontent.com/assets/5147014/9112472/0ec5b6f8-3c4f-11e5-8b44-5fcfe93fcca2.png)
![temperate-bib-0000](https://cloud.githubusercontent.com/assets/5147014/9112473/0ec82cf8-3c4f-11e5-8b1b-5b73e48a9fa7.png)

**Comment by TheRaffy** [comment]
Here are the png's in case the art part was the thing.

**Comment by TheRaffy** [comment]
I created the shp files. But I need somebody to check these files.
(note the sno bib is using the temperate pal as it seems to be normal that way.)

https://www.dropbox.com/s/a1cqqibutoqxiu7/bib4.des?dl=0
https://www.dropbox.com/s/xofxolpsu9y5no3/bib4.temp?dl=0
https://www.dropbox.com/s/z669lqvxtyn76u1/bib4.sno?dl=0

**Comment by TheRaffy** [comment]
The bin for the Interior tileset is missing.!!

**Comment by abcdefg30** [comment]
I think this was solved by #10095.
