### ISSUE TITLE
RevealsShroud trait active even when shroud/fog are disabled

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#7669]
In a test game with over 100 yaks and migs where I had disabled fog/shroud in map options - and later per cheat as well, to be sure - ```RevealsShroud``` was the only thing that continously ate over 1 or 2 ms according to perf.log.

Disabling this trait when both fog and shroud are disabled might help performance a little in games/maps where this is the case.

**Comment by reaperrr** [comment]
> Disabling this trait when both fog and shroud are disabled might help performance a little in games/maps where this is the case.

Scratch that.
With about 180 migs and yaks, ms per tick went down from ~42-45 to ~6(!) just by commenting out ```RevealsShroud``` on both of them.

In other words, there is a MASSIVE amount of performance wasted on maps with fog/shroud disabled.

**Comment by Phrohdoh** [comment]
An interesting idea, though we would either have to split fog/shroud ranges out into different traits or only disable (return early) `RevealsShroud` if both are disabled.

**Comment by reaperrr** [comment]
We should do the latter in any case. I've just done that locally and the difference is indeed as massive as described above. The ```UpdateVisibility``` function appears to be a real resource hog.

**Comment by RoosterDragon** [comment]
#7577 should improve this, even in the case where shroud/fog is still enabled.

**Comment by reaperrr** [comment]
@RoosterDragon, I just tested my changes on your 7577-branch and even there the performance gains on maps with both disabled were massive.

I've pushed my changes here, feel free to review/tweak and use them as you see fit: https://github.com/reaperrr/OpenRA/tree/shroud-visibility-perf

Simply disable both fog and shroud and then use cheats to build huge amounts of yaks or migs. Once batches reaches about 200, it's 6.5ms/tick with my changes vs. ~40ms on your original branch.

We could take this one step further and check not only for whether fog & shroud are disabled, but also whether only fog is disabled but the whole shroud has been revealed by actors.

**Comment by deniz1a** [comment]
This might be unrelated but where is the variable cachedLocation, which is defined in CreatesShroud.cs, used? It appears to be never used by anything? Is that preparation for a feature that will be implemented later?

Also the same for these:
https://github.com/OpenRA/OpenRA/search?q=cachedLocation&type=Code&utf8=%E2%9C%93

**Comment by penev92** [comment]
Better move those (unrelated) questions to IRC.
