### ISSUE TITLE
AI MCV deployment decisions

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7676]
Just another AI issue. Probably a duplicate of something.

I was just testing something, minding my own business, when suddenly, a wild MCV appeared!
I sometimes disable the AI player when testing unrelated stuff, sometime I just leave it.
So the MCV just came to my base and decided to undeploy:
![](http://i.imgur.com/I4xYeR6.png)

This is where the AI's base should be:
I assume the crate got in the way and the MCV couldn't unpack, so it decided to come to my patch of rock, for some reason...
![](http://i.imgur.com/qtQMtmi.png)

**Comment by Mailaender** [comment]
This seems to be a seldom constellation. https://github.com/OpenRA/OpenRA/issues/3076 may fix this, too.

**Comment by TGHoly** [comment]
I mod TD when I allow AI build MCV i found they send their new MCV direct to me and deploy it on my base. :p

**Comment by Mailaender** [comment]
This was solved with a spawn delay https://github.com/OpenRA/OpenRA/issues/3076#issuecomment-48434257 and improving the deployment logic. https://github.com/OpenRA/OpenRA/pull/11463
