### ISSUE TITLE
Support per-mod hotkeys

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7680]
Different mods may want different hotkeys for mod-specific stuff.
Example is the production tabs, as shown in #7541.
This would include mostly having a different Input tab in the Settings menu, I assume.
##

**Comment by rob-v** [comment]
I don't know now if custom hotkeys for mod specific actions are supported, but different hotkeys (those displayed in Input tab) per mod are now ready, see #8276.

**Comment by pchote** [comment]
Fixed by #14379 and related PRs.
