### ISSUE TITLE
Black screen Windows 8.1

### ISSUE THREAD

**Issue by fjlaubscher** [OpenRA/OpenRA#7682]
Hi guys

When I start up OpenRA I am presented with a black screen. The mouse cursor does change to the OpenRA cursor however.

I have tried running this in compatibility mode and as administrator but still no luck.
Also I have updated my latest intel HD graphics drivers.

I am running Windows 8.1 on a Lenovo T540p notebook with the following specs:
Intel Core i7-4710MQ (2.5 GHz x 8)
16GB RAM

**Comment by Mailaender** [comment]
Any hints in the log files? See https://github.com/OpenRA/OpenRA/wiki/FAQ for the location.

**Comment by fjlaubscher** [comment]
@Mailaender 
Nothing I can see.

All the log files are empty except for perf.log
Which contains this:

          SpriteFonts
    18 ms |   PrecacheColor C:\Program Files (x86)\OpenRA\mods/common/FreeSans.ttf 14px White
     5 ms |   PrecacheColor C:\Program Files (x86)\OpenRA\mods/common/FreeSans.ttf 14px Red
     5 ms |   PrecacheColor C:\Program Files (x86)\OpenRA\mods/common/FreeSansBold.ttf 14px White
     5 ms |   PrecacheColor C:\Program Files (x86)\OpenRA\mods/common/FreeSansBold.ttf 14px Red
     6 ms |   PrecacheColor C:\Program Files (x86)\OpenRA\mods/common/FreeSansBold.ttf 24px White
     5 ms |   PrecacheColor C:\Program Files (x86)\OpenRA\mods/common/FreeSansBold.ttf 24px Red
     5 ms |   PrecacheColor C:\Program Files (x86)\OpenRA\mods/common/FreeSansBold.ttf 18px White
     5 ms |   PrecacheColor C:\Program Files (x86)\OpenRA\mods/common/FreeSansBold.ttf 18px Red
     5 ms |   PrecacheColor C:\Program Files (x86)\OpenRA\mods/common/FreeSans.ttf 10px White
     4 ms |   PrecacheColor C:\Program Files (x86)\OpenRA\mods/common/FreeSans.ttf 10px Red
     5 ms |   PrecacheColor C:\Program Files (x86)\OpenRA\mods/common/FreeSansBold.ttf 10px White
     4 ms |   PrecacheColor C:\Program Files (x86)\OpenRA\mods/common/FreeSansBold.ttf 10px Red
   106 ms --------------------------------------------------
     6 ms LoadMaps
     5 ms Actors
     0 ms Weapons
     0 ms Voices
     5 ms Notifications
     0 ms Music
     0 ms Movies
     0 ms TileSets


Maybe I should try and build the solution from source and see if I can find anything while debugging?

**Comment by Mailaender** [comment]
Is OpenRA allowed to read C:\Program Files (x86)\OpenRA\mods\*\maps and rules?

**Comment by Mailaender** [comment]
> I have tried running this in compatibility mode and as administrator but still no luck.

Maybe this is the cause. I don't know what happens if you run the game with admin rights, especially with the in-game content download. You may have left OpenRA in a state where normal users can't execute it anymore. Try un-installing and deleting `%USERPROFILE%\Documents\OpenRA`.

**Comment by fjlaubscher** [comment]
Just updated my intel HD display drivers. Seems to be working fine now.

My bad

**Comment by obrakmann** [comment]
Thanks for letting us know. Have fun!
