### ISSUE TITLE
Faction logo is visible in the radar bin on wide/tall maps

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7688]
Took me a while to figure out what is wrong with the minimap here:
![](http://img.prntscr.com/img?url=http://i.imgur.com/UNRLGJJ.png)

Then I realized it's the Atreides logo, which the map can't cover completely, so it's showing.
Related to #7384 and #7456.

Might be worth checking the other mods as well?

**Comment by pchote** [comment]
This is an error in the D2K sidebar yaml, and should be an easy fix.  It will not be an issue in RA (because I went to specific lengths to prevent this).

**Comment by Mailaender** [comment]
Proposed fix at https://github.com/OpenRA/OpenRA/pull/7693.
