### ISSUE TITLE
Add new labels for the issue tracker

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7690]
Here are two suggestions that might be useful:
**1.** Add an "Art"/"Artwork" label. Not to be confused with the "UI" label. This can be useful in cases like "rework a stealth effect", "create a new projectile effect", "create a new contrail effect", "change unit build palette image", etc.
**2.** Add "Windows"/"Linux"/"MacOS" labels. We get quite a few OS-specific issues, so those would be useful.

**Comment by Mailaender** [comment]
Okay, :+1:

**Comment by obrakmann** [comment]
yeah, me too. [Went ahead and added those](https://github.com/OpenRA/OpenRA/labels)

**Comment by Mailaender** [comment]
I tagged some bugs with OS labels.
