### ISSUE TITLE
Possible CPos -> MPos conversion miscalculation

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7701]
Something I noticed when testing my `Map.ChooseClosestEdgeCell()` method today:
This line here:  `var mpos = pos.ToMPos(this);` seems to give me a proper X (U) coordinate, but the Y (V) coordinate is off. It seems like it's `Map.Bounds.Top + 2*actual_V_Offset`.
~~You can test this by getting #7664 and running TS on the blank map. I added a way to easily test by issuing Move orders. Such an order will result in calculating the edge cell that is closest to the actor and drawing a target line to it.~~

**Comment by reaperrr** [comment]
Surely the underlying issue behind #6247.

**Comment by penev92** [comment]
Test case was removed.

**Comment by pchote** [comment]
I believe that this has been fixed as part of my heightmap changes in the last couple of releases (e.g. #8859).  Feel free to reopen if you can find new repro cases.
