### ISSUE TITLE
Add support for SSI SHP type 1.10

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#7716]
As used in some SSI games and MechCommander 1.
I consider this solved if support for the presumably MC1-exclusive variant - where the first 6 bytes do unknown stuff and the regular header only starts at the 7th byte - is added as well (should be easy since there don't seem to be any other differences).

Source code for SHPEd05 can be found here (old C++ program):
https://github.com/reaperrr/MechComRTS/tree/bleed/docs/shped05-sourcecode

**Comment by Phrohdoh** [comment]
Do you have any other documentation?

**Comment by reaperrr** [comment]
Yes, I have the source-code of a working SSI-SHP editor.

**Comment by Phrohdoh** [comment]
Fantastic! Shall I assign you to this issue then?

**Comment by reaperrr** [comment]
I was more hoping someone else does this for me =), but I guess that would be quicker than waiting for something to happen without my doing.

**Comment by Phrohdoh** [comment]
Revisiting this: Does OpenRA really need to support this sprite format, or could you make use of a custom loader in a mod assembly?

**Comment by reaperrr** [comment]
Yeah, a loader in a mod assembly makes more sense (actually, I already have one, thanks to @penev92), this can be closed.
