### ISSUE TITLE
Make actor height (and Z height for targeting) customisable

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#7717]
Should affect blockable projectiles and possibly flying actors.
Needed for TS (and my MechCommander RTS mod).
- [x] customisable height for blocking actors
- [ ] custom target point ZOffset for projectiles
##

**Comment by Phrohdoh** [comment]
I don't understand the
>Z height for targeting
part..

**Comment by reaperrr** [comment]
I guess that was poorly worded on my part. It means that projectiles fired at this actor should not simply fly towards and explode at its feet (assuming it is a tall ground unit like a mech), but rather fly towards and explode at a specified height above ground. Basically, ```Height``` would be the equivalent of the TS height, while something like ```TargetHeight``` would define the point/height that weapons target and shoot at.

**Comment by Phrohdoh** [comment]
In that case, :+1:

**Comment by reaperrr** [comment]
Made some nice progress on this:
![customz](https://cloud.githubusercontent.com/assets/2857877/12072763/33757a6c-b0f1-11e5-9907-2abd01a92120.png)
