### ISSUE TITLE
Some times an e1 ejects from bombing a vehicle

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#7725]
Here you can see a Rifle man spawning from the heavy tank husk.
![openra game_2015_03_24_02_28_54_857](https://cloud.githubusercontent.com/assets/7798635/6794077/d9e5f290-d1cd-11e4-8f9d-35404207905c.png)

**Comment by Phrohdoh** [comment]
This is caused by [EjectOnDeath](https://github.com/OpenRA/OpenRA/wiki/Traits#ejectondeath).
The proper fix would be to add an interface that is `IPreventsEjectOnDeath` (better name?) in the same way that `IPreventsTeleport` works.

**Comment by Mailaender** [comment]
Isn't that expected behavior? I also remember the originals spawning infantry from bombed buildings.

**Comment by Snurre86** [comment]
Yes they did, but not when Tanya bombed the buildings. In original TD buildings would randomly spawn 0-2 rifle men when the commando bombed buildings.

This does not change the gameplay that much, but you might have to wait idle for her to heal up at points.

**Comment by Mailaender** [comment]
Having it configurable is probably a good idea though. https://github.com/OpenRA/OpenRA/issues/7726

**Comment by MicroJOo** [comment]
@Phrohdoh , @Mailaender :  this is indeed expected behaiviour ...
