### ISSUE TITLE
Debug menu and Options show only Debug menu

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#7728]
In bleed 2015-03-24 TS you can't get options menu up in game.

Pressing "Debug menu cog" or "SHIFT+ESC" show Debug menu
Pressing "Options cog" or "ESC" show Debug menu
![openra game_2015_03_24_14_38_09_810](https://cloud.githubusercontent.com/assets/7798635/6802854/ea1344cc-d233-11e4-929f-b7ecf0213ee9.png)
![openra game_2015_03_24_14_38_14_162](https://cloud.githubusercontent.com/assets/7798635/6802866/f76535ae-d233-11e4-86dd-2faabb86e176.png)

**Comment by Phrohdoh** [comment]
Currently (as shown in your screenshots) you see both menus all the time.
The left-most is the pause menu while the center is the debug menu.
So this behavior is expected, but TS does differ from the other mods (it doesn't use tabs).
Resolving that will 'fix' this.

**Comment by Snurre86** [comment]
You are right I was able to open the options menu from the debug menu

**Comment by Snurre86** [comment]
just close it if you think it is as expected

**Comment by Phrohdoh** [comment]
This can be kept open as reference until the UI is made to match the other mods.

**Comment by Mailaender** [comment]
For some reason the game info stats are not shown. Not sure why. The chrome yaml should be loaded.

**Comment by obrakmann** [comment]
it's missing this:
```diff
--- a/mods/ts/mod.yaml
+++ b/mods/ts/mod.yaml
@@ -202,6 +202,9 @@ Fonts:
        Title:
                Font:./mods/common/FreeSansBold.ttf
                Size:32
+       MediumBold:
+               Font:./mods/common/FreeSansBold.ttf
+               Size:18
        BigBold:
                Font:./mods/common/FreeSansBold.ttf
                Size:24
diff --git a/mods/ts/rules/world.yaml b/mods/ts/rules/world.yaml
index 05a4496..031aa8a 100644
--- a/mods/ts/rules/world.yaml
+++ b/mods/ts/rules/world.yaml
@@ -178,4 +178,6 @@ World:
        ScreenShaker:
        RadarPings:
        StartGameNotification:
+       ObjectivesPanel:
+               PanelName: SKIRMISH_STATS
```

**Comment by Mailaender** [comment]
> But FWIW, I kinda like it that way. I certainly use the debug cheats more often than I'd like to see the scores when I'm in ts.

Just smash `SHIFT` +  `ESC`. We loose no developer convenience or functionality. Filed https://github.com/OpenRA/OpenRA/issues/8179.
