### ISSUE TITLE
Laser beam start/end point "facing" extremely coarse-grained

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#7729]
Basically, the effect seems to know only four 'facings' (up, down, left, right), at least for the start and end of the line. Becomes very noticable with wider beams, see TS sonic tank for example.

**Comment by pchote** [comment]
This is a side-effect of using the legacy GL "wide line" support.  Another limitation is that there is a driver-specific limit to the width the lines can be drawn.

We need to replace this with our own DIY line rendering using colored polygons, which also improves our compatibility with newer GL versions (including ES) that have dropped support for this feature.
