### ISSUE TITLE
Allied 5a: Tanyas tale - Issues

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#7735]
Completing all mission objectives before Tanya leaves cashes the game.
![openra game_2015_03_24_23_47_08_756](https://cloud.githubusercontent.com/assets/7798635/6824401/3ece46c4-d2f2-11e4-9977-265655a5950e.png)
leads to
![openra game_2015_03_24_23_49_18_615](https://cloud.githubusercontent.com/assets/7798635/6824402/4738945e-d2f2-11e4-99e4-59c93465b3d0.png)

Also see:
 #7724 Tanya can't reach the v2
#7730 Tanya get crushed under heavy tank.
#7725 Some times an e1 ejects from bombing a vehicle

**Comment by Snurre86** [comment]
lua.log see http://pastebin.com/ZHN649st

**Comment by Snurre86** [comment]
Maybe put a medic or engineer in the mission will make it possible for average players to complete it with Tanya.

**Comment by Phrohdoh** [comment]
I don't see a crash here.

**Comment by abcdefg30** [comment]
> Maybe put a medic or engineer in the mission will make it possible for average players to complete it with Tanya.

I plan to rework the difficulties. Will have a look how to implement your idea.

**Comment by Mailaender** [comment]
How did you manage to get pass the flame tower station with the V2?

**Comment by Snurre86** [comment]
Destroyed the v2 by not blowing up the buildings so the v2 can see you and you can allure it in and blow it up.  then the flame tower is just run for it ...

**Comment by Snurre86** [comment]
This is fixed in playtest 2015-04-18.
![openra game_2015_04_24_21_05_11_862](https://cloud.githubusercontent.com/assets/7798635/7326485/e9b9ff34-eac5-11e4-92de-b95af3117a24.png)
![openra game_2015_04_24_21_05_42_453](https://cloud.githubusercontent.com/assets/7798635/7326488/eeaab2a4-eac5-11e4-97df-a2f5266e02b3.png)
![openra game_2015_04_24_21_05_47_702](https://cloud.githubusercontent.com/assets/7798635/7326494/f9775958-eac5-11e4-86e5-20d690158e7b.png)
