### ISSUE TITLE
TS imported civilian structures have incorrect art offsets.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#7744]
The buildings added by #7223 have incorrect artwork offsets.  This can be seen for the civilian structures and bridge huts in:

![tssnow](https://cloud.githubusercontent.com/assets/167819/6873535/e2c28116-d4a8-11e4-98af-78ec8d6ae26a.png)

**Comment by reaperrr** [comment]
Expected as much. I'll try to fix them over the weekend.

**Comment by pchote** [comment]
They are also missing damage frame definitions.
