### ISSUE TITLE
Debug option for showing cell coordinates

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#7750]
Being able to see which cell is which have been useful in a multitude of situations when debugging.
I suppose this will want to use something like the performance text for useability reasons, printing the coordinates of the mouse cursor.
I consider this also a pretty basic requirement for a map editor.
##

**Comment by Phrohdoh** [comment]
:+1:
![world](https://camo.githubusercontent.com/b081cd0dd2a901f5637d8051cc29ced0649bf53a/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f343936353438372f323236323130312f37383035386532342d396535362d313165332d393939382d3739613262303063303438392e676966)
![cells](https://camo.githubusercontent.com/054764a57a7a646501cff85b57ff69e2a239aa41/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f343936353438372f323236323130332f37383137396266302d396535362d313165332d386632362d3763643332363932636662662e676966)

**Comment by penev92** [comment]
As long as it doesn't become too visually polluting or too render-taxing, the second image would be the most helpful. :+1:

**Comment by Mailaender** [comment]
Now that https://github.com/OpenRA/OpenRA/issues/8694 has been rejected is https://github.com/OpenRA/OpenRA/pull/9089 sufficient?

**Comment by penev92** [comment]
No, actually my original request was to have this ingame when "Show Terrain Geometry" is enabled, for debugging purposes. So this is still not fully resolved.

**Comment by teinarss** [comment]
Closed by #16442
