### ISSUE TITLE
RA - 3. Soviet Subfaction

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#7778]
I think numbers of subfactions should be same. I don't have any idea about special units but country may be Georgia SSR or Poland.

**Comment by sillyflip** [comment]
I would suggest Belarus or Kazakhstan as a Soviet sub-faction, both were part of the Soviet Union. One special unit could be the BMP 1 which would be replacement for the Soviet APC. It could be amphibious and do slightly more damage but hold less infantry. The art for the unit could be the APC chassis + Light Tank turret.

**Comment by MustaphaTR** [comment]
Other special units may be fake soviet structures. So we don't need new graphics to do them.

**Comment by deniz1a** [comment]
I think before adding new countries, the ones in the original games should be added first. Red Alert Aftermath had these countries:

![ra_countries](https://cloud.githubusercontent.com/assets/6599106/6896306/91ec2c00-d6f2-11e4-984d-bf7afeb4f405.png)

**Comment by MustaphaTR** [comment]
I don't think all orginal countries should be added. Orginal game has 6 Allied County but 2 Soviet County. Has a very big difference about numbers.

**Comment by penev92** [comment]
1. Adding countries for the sale of having "equal counts" is not an argument and should notbe done.
2. Adding countries just because the original game had them is a bad argument and should not be done.

Adding countries because you have a (sort of) unique gameplay idea for them to be built around is a good argument, and the only such that I've heard during the several discussions that took place both here and on IRC over the last 2 days.

**Comment by deniz1a** [comment]
But those are independent. You can have a unique gameplay idea and you can add that to any country you want. Country names are arbitrary. It is generally better to have more factions and more variety among them.

**Comment by penev92** [comment]
Why should country names be arbitrary?
And if you have an idea you can pick a suitable country name for it, from the original game or not.
But these are two different discussions - this issue is not about the original names, it's about "why not add a bunch more subfactions?".

**Comment by deniz1a** [comment]
I didn't say country names should be arbitrary. I said they currently are. What does Germany have to do with time travel and teleportation? What does France have to do with gap gen? etc.
Of course you should have some good ideas about the units of the country you want to add. But in general, more factions are better I think and more diverse factions are also better. And if new countries are going to be added I also thought the ones in the original game should be implemented first. 

So you also would like to add more factions if they have interesting differences?

**Comment by penev92** [comment]
If they are diverse enough, sure.
Also I believe the germans having chrono stuff is based around Einstein's contributions to the C&C games.

**Comment by cjshmyr** [comment]
> Adding countries for the sake of having "equal counts" is not an argument and should not be done.

Sigh. Equality *is* an argument, and I'm not a fan of shutting down arguments before they begin. It makes a whole lot of sense to add a new country, but like you say penev, only if there's a good idea to back it up.

For soviet, maybe a country with emphasis on tesla.

**Comment by lasselaak** [comment]
An equal amount of soviets/allieds woult make the random faction odds 50/50. Playing almost purely with random factions this would be a nice thing. This though could easily be added as an option even with a different number of allied / soviet countries. e.g. first a 50/50 random between allied/soviet and the a random take on the subfaction.

**Comment by WolfGaming** [comment]
@lasselaak The current random implementation chooses between soviet and allies first before choosing subfaction so there is a 50/50 between allies and soviet.

**Comment by MustaphaTR** [comment]
There is also a random from any side. So currently it is 40/60 not 50/50.

**Comment by pchote** [comment]
@MustaphaTR: what @WolfGaming meant was that the "random from any side" option picks between "random allies" and "random soviet" with 50/50.  There is an equal chance of getting an allied vs a soviet country, but overall more chance of getting say Russia than Germany.

**Comment by WolfGaming** [comment]
So lets say we had 2 allied countries and 5 soviet,
with the current system we have both of the allied teams would have a 25% chance of being chosen, while a soviet team would only have a 10% chance of being chosen.

aka 25% * 2 allied teams = 50%
and 10% * 5 soviet teams = 50%
so 50% chance of either soviet or allied.

**Comment by pchote** [comment]
There is no strong gameplay drive for this, so closing.

**Comment by HenrytheSlav** [comment]
What is the story of China in RA verse and is it communist/ally of the USSR?

**Comment by TheRaffy** [comment]
I would like to see a faction with no teslacoile, no tesla troopers. only tesla tanks, snipers, and some extra stuff against spys, like higher spy detection, cheaper/faster/stronger dogs. and something with an huge view, like the chinook from the allies, Maybe a only anti air submarine!  
I still don't get, why the longest range weapon and the highest view unit and the gap gen is all at the same faction. ya, soviets have the most tanky unit.
