### ISSUE TITLE
tech building that capitalises oil revenues?

### ISSUE THREAD

**Issue by clasm** [OpenRA/OpenRA#7779]
capture this building and it leverages oil income. so if you already got (say) one derrick making 1k per minute, this becomes (say) 10k available to you at all times.

but if you lose the derrick, all gone.

maybe call it "Bond Market"

could be fun way to hint at capitalist war finance in openra engine? :D
##

**Comment by deniz1a** [comment]
Calling it an oil refinery would be better then. Or oil purifier...

**Comment by clasm** [comment]
thx, but not exactly what i was going for (although i guess i made it sound similar)

with this building, instead of using your oil money to fight the war, you use your oil money to pay interest on a giant loan that gives you megabuxxx to fight the war.

**Comment by pchote** [comment]
This can be implemented using lua in a scripted map.  Closing to help clean up the issue list.
