### ISSUE TITLE
UI is probably leaking somewhere

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#7781]
Tick counter breaks when clicking on Skirmish (or 'Back' in Missions) in any mod, and I've just been able to reproduce this for a 2nd time:
![ohnoes1](https://cloud.githubusercontent.com/assets/2857877/6886157/00aaa432-d635-11e4-861a-6895402961cf.png)

**Comment by reaperrr** [comment]
You can still load a different mod which fixes this, it's just the background that gets garbled up.

**Comment by pchote** [comment]
Probably #7248.

**Comment by obrakmann** [comment]
Fixed by #7822.
