### ISSUE TITLE
Playing as "any" (random) should not favor side with more subfactions

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#7788]
I think the game should first decide a random side (allies, soviets) and then a random subfaction of that side. I asked @pchote who confirmed that currently the side with more factions will be favored (picked more often).

**Comment by WolfGaming** [comment]
It is already like that, pchote was wrong this one time :)

**Comment by pi99y** [comment]
Great! :)

**Comment by obrakmann** [comment]
Indeed, [here is](https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/rules/world.yaml#L129) where that happens (introduced in #7476).

**Comment by x-a-n-a-x** [comment]
To fix the problem of the side that has more subfactions, couldn't it be possible to generate a "weighted (faction) randomization" ?
