### ISSUE TITLE
Statistics window off-center

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#7795]
In Red Alert and Dune 2000 mods the statistics window is off-center (positioned top-left). TD is fine.

Tested on Win 8.1, Pseudo-Fullscreen mode (if it matters).

![ora_statistics_w](https://cloud.githubusercontent.com/assets/10639257/6896467/f9bc684c-d6eb-11e4-8d08-52cb4bca4c72.jpg)
##

**Comment by obrakmann** [comment]
AFAIK, that is on purpose. The dialog has the same position in observer mode, and I just left it where it already was. I was asked to move it to the center for the TD mod [back in September](https://github.com/OpenRA/OpenRA/pull/6397#issuecomment-54688630). I don't have a preference either way, though.

**Comment by pi99y** [comment]
I don't have a preference either (centered, left aligned), but I think it should be **consistent** with other menus and probably also across mods.

**Comment by Mailaender** [comment]
We can make the window movable. https://github.com/OpenRA/OpenRA/pull/2965

**Comment by MustaphaTR** [comment]
:+1:  to @Mailaender 's idea.

**Comment by pchote** [comment]
The window movement code is horribly broken and incomplete.  That would be a bad idea.

**Comment by dragunoff** [comment]
The new statistics UI has been merged in #16406 so this shoud be closed.
