### ISSUE TITLE
Display/GPU select

### ISSUE THREAD

**Issue by Nerus87** [OpenRA/OpenRA#7801]
Hi, i have two display connected to deferents GPU. Maser is APU, second is Radeon, game on start always use Radeon and I want to run this game on Integrated. Please add feature or fix this if is a bug.

Regards, Nerus.

**Comment by Mailaender** [comment]
That has to be resolved at Operating System level with your vendor supplied tools. It is crazy to implement something like this on every platform and for every driver on our own. Sorry.

**Comment by penev92** [comment]
The ATI drivers' UI should provide you with that option anyway.

**Comment by Nerus87** [comment]
Nope, this is a desktop not a Laptop where u have some think like Powersaving.

**Comment by penev92** [comment]
I'm talking about the ATI Catalyst Control Center.

**Comment by qiou** [comment]
If you want to play on the APU and don't like the GPU, disable it or remove it from your computer.
The GPU is better than the APU in term of games though.

**Comment by Nerus87** [comment]
@penev92 "I'm talking about the ATI Catalyst Control Center."
Yes I know but there is no any switch

@qiou 
1) "If you want to play on the APU and don't like the GPU, disable it or remove it from your computer."
- Yes I can do on this way, but I want to have were activated both monitors.

2) The GPU is better than the APU in term of games though.
- APU is above specification of 2D OpenRA engine.
