### ISSUE TITLE
IDisable interacts badly with upgradable traits (e.g. broken TS stealth generation)

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#7807]
Toggling an actor's functionality (naradr -> radar bin) should not change whether or not it is receiving a proximity upgrade.
Perhaps this coupling should be pulled out and made configurable/intentional, if it is not already.
I could not find anything directly tying these logics together in a clear manner.

![cloakgen-oddity](https://cloud.githubusercontent.com/assets/4861023/6912574/dbcc3cb6-d738-11e4-90b2-1de892b2600a.gif)

This gif also shows that a proximity upgrade (and possibly others) restart the current animation, but that issue is unrelated.

If I am wrong about anything here please let me know and close this as necessary.
##

**Comment by pchote** [comment]
This is another side-effect of the IDisable interface (the legacy method for disabling traits on an actor) interacting badly with upgradable traits.  There is a hardcoded check in `Cloak` to not activate if the actor is disabled.

In order to fix this we need to remove that old interface and change powerdown etc to work using upgrades.

**Comment by Phrohdoh** [comment]
@pchote Should this be closed as a result of #12503 being merged?

**Comment by pchote** [comment]
Not yet, lets save that until `IDisable` has been completely removed.  That is now close enough to insist that it is done for the next release, so moving to the appropriate milestone.

**Comment by reaperrr** [comment]
I have a local WIP branch that gets rid of `IDisable` on power-related traits (`RequiresPower` and `CanPowerDown`) which should bring us a good deal closer to that, as the other remaining usages of `IDisable` seem individually trivial in comparison.*

*Of course there might still be some implicit dependencies I'm not aware of.
