### ISSUE TITLE
Mono 2.10 build failure

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#7808]
`OpenRA.Mods.Common/UtilityCommands/FixClassicTilesets.cs(73,61): error CS0219: The variable 'oldLength' is assigned but its value is never used`

This breaks our automated fedora packaging, which is forced to run on a disgustingly outdated version of mono.

**Comment by pchote** [comment]
Interestingly this error is correct - `oldLength` is left over from some older code, and is now unused.  Looks like it is a bug in newer monos that this wasn't caught.

**Comment by Mailaender** [comment]
This is an easy fix on our side then. Alternatively I could also package Mono 3.10 for Fedora in the https://build.opensuse.org/project/show/games:openra repository.
