### ISSUE TITLE
remove NUnit

### ISSUE THREAD

**Issue by huwpascoe** [OpenRA/OpenRA#7825]
NUnit is only taking up space. No one has really taken to unit testing and it's very clear that integrated testing is preferred. I don't see any reason to keep the extra dependencies and csproj around.

Revert #6797

**Comment by Unit158** [comment]
:-1:

I really object to this because it is still used, and I still use it.

**Comment by pchote** [comment]
Unit testing is a good idea for things that can be properly unit tested -- like the file format parsers and coordinate transforms (ideally also aspects of rendering, but that is going to be tricky without an offscreen rendering context).  It would make sense to use NUnit to run the integration tests.
