### ISSUE TITLE
OpenRA fails to parse some hotkeys (§,~,ä,ö)

### ISSUE THREAD

**Issue by sinf** [OpenRA/OpenRA#7838]
Any hotkeys that are displayed in the input menu with their SDL keycode (e.g. "126" instead "Tilde") aren't parsed properly on startup, they're reset back to defaults and finally  forgotten the next time you play.

Console output includes this line:
> FieldLoader: Cannot parse `126 None` into `GuardKey:Hotkey`; substituting default `D None`

Edit: just to clarify what this is about. This affects keyboards with some weird keys (a german or a scandinavic one will do). Any keys can be mapped via the ingame input menu and it works fine but as soon as the game is restarted the keybindings are reset.

**Comment by pchote** [comment]
How are you setting these (apparently) bogus hotkeys?

**Comment by sinf** [comment]
Via the ingame input settings menu (press an UI item, then press a key on keyboard -> key is configured).
I suspect the cause of this problem is OpenRA.Game/Input/Keycode.cs:KeycodeExts not returning a string for all keys. My proposed fix is to generate names for unknown/exotic keys (i.e. "KEY_XXX" where XXX is the key code).
