### ISSUE TITLE
Improve RA Soviet faction balance

### ISSUE THREAD

**Issue by ScottNZ** [OpenRA/OpenRA#7869]
Replace their abilities with better ones.

**Comment by GrayHatter** [comment]
Is there a way to tell if you're playing on snow or on grass?

maybe give soviets a bonus if their unit is on snow?

**Comment by pi99y** [comment]
I like the idea but I fear people might then refuse to play on snow or even make snow maps...
Maybe this should be complemented with another bonus for grass maps so this doesn't happen?
Something along... "Soviet infantry units have speed bonus on snow but on grass they have a defensive/armor bonus."

**Comment by GrayHatter** [comment]
maybe swap it around too, anyone on the allies side gets a defensive bonus on snow, and a speed bonus on grass. Anyone from the soviets side gets the speed, bonus on snow and a defensive bonus on grass?

You could tool it around a bit, find the combo that works... But make sure that you add a canadian faction, that gets a bonus to everything on snow!
