### ISSUE TITLE
Screen horizontal lines glitch + black border at top + mouse position off

### ISSUE THREAD

**Issue by barrystaes** [OpenRA/OpenRA#7870]
I found that on one computer OpenRA was nearly unusable. Things i noticed:
- the menu mouse pointer Y position is off. Mouseover and clicks correspond though.
- the menu dropdown-fields scroll buttons are unresponsive (not even mouseover). Hence i cant select an AI to skirmish with.
- there where horizontal line glitches. As if every ~30 pixels one line was missing. Especially noticeablewhen the menu shell map is scrolling, but also in the OpenRA logo.
- when in Pseudo-Fullscreen / Fullscreen i saw a black bar at the top of the screen.

I tried every combination of Pseudo-Fullscreen / Fullscreen / Windowed with Hardware Cursor and found no solution. With the latter the mouse Y offset varies though. 

See attached screenshot: demonstrating most of the above:
![openra screenshot 3](https://cloud.githubusercontent.com/assets/1420588/6997244/fc42386c-dbb4-11e4-9d68-876e2a111a45.png)
_(the mouse actually was above Mods button, despite mouseover)_

I was unable to screencapture fullscreen (i reported that to #5317), but i can say the mouse can enter black bar. I also suspect the black bar height corresponds with the number of horizontal line glitches, and it appears the mouse Y position is less off when near the bottom of the screen. It all seems interrelated.

Tested on release-20141029 and playtest-20150329. I cant remember seeing the problem before that.
Computer specs: Windows Vista SP2 64bits, native resolution 1360x768, Geforce G210.

PS. I am a programmer and willing to troubleshoot this myself, in case i might be the only one that can replicate this so far. Any insights welcome!
I would like to play OpenRA while spending weekends with my in laws. :)

_UPDATE: better screenshot and added indication_
##

**Comment by pchote** [comment]
Do you have DPI scaling enabled in your OS config?

**Comment by obrakmann** [comment]
@barrystaes: can you try to delete your settings.yaml file and see if the issue persists?

**Comment by barrystaes** [comment]
@pchote Windows DPI setting is "standard size (96 DPI)".
@obrakmann Where is the `settings.yaml` file located?

**Comment by obrakmann** [comment]
in C:\Users\<User>\Documents\OpenRA (or C:\Documents & Settings\<User>\, depending on your OS version), IIRC.

**Comment by barrystaes** [comment]
Ok i removed `settings.yaml` and that fixed the dropdown issue.

**Comment by barrystaes** [comment]
Now upgraded to v20150427 (same pc) and again the same issue.. 

I changed to windowed 800x600 and fulls creep,  tried removing `settings.yaml` but this time it doesn't help.

**Comment by barrystaes** [comment]
Removed openra folder in documents, and uninstalled+ reinstalled. But again same problem.

**Comment by pchote** [comment]
A lot has changed in the graphics stack since 2015, so closing as stale.  Please comment if this is still a problem, and we can reopen the issue.
