### ISSUE TITLE
Graphical glitches in the main menu

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#7877]
I sometimes get graphical glitches when returning to the main menu screen (playtest 20150405):

![menu_broken](https://cloud.githubusercontent.com/assets/10639257/7001629/7d4e7f00-dc3d-11e4-8c8b-6a29079eae37.jpg)
![menu_broken2](https://cloud.githubusercontent.com/assets/10639257/7001630/7f7fe20a-dc3d-11e4-9135-55c66ab641d7.jpg)

It seems to be caused by ALT-TABing out of the game to another window (Firefox running java) and returning to the game. So far it only appeared in the main menu - even if the gameplay looked OK after "returning" to the game's window (so after going back to the menu). It doesn't happen every time, and it happened after watching replays and after regular games as well.

I have shellmap disabled, using pseudo-fullscreen mode and running Windows 8.1 with Intel HD graphics.

**UPDATE:**
The easiest way to reproduce this seems to be to ALT-TAB while you're switching mods. 
- once I managed to freeze Windows (8.1) while doing this
- sometimes you lose sight of the mouse pointer (but the mouse works, you can see menu buttons changing color when you manage to hover over - might be a separate issue)
- sometimes the menus doesn't get displayed (not even text) (when it happened the OS froze)

**Comment by pchote** [comment]
It looks like something is trashing the textures on your GPU.  I'm tempted to blame one of @RoosterDragon's memory-reduction changes, but if nobody else can reproduce it then it's probably something else on your system.

**Comment by RoosterDragon** [comment]
I'm able to occasionally reproduce the missing mouse cursor. It *seems* to happen when you switch to a mod having had hardware cursors on, but after you load software cursors have become active instead (I believe this is a fallback mechanism for when hardware cursors fail sometimes). Switching mod again brings the cursors back. I bet the missing cursors is really the same error as #7942 though.

I can't ever reproduce the screwed up graphics. But I imagine @pchote is on the right lines about one of my changes trashing something on the GPU. @pi99y is this issue reproducible on the release from 2014-10-29? That would help us determine if we changed something that broke it or if it really us something off on your system in particular.

**Comment by pchote** [comment]
#8049 shows that you're doing OpenGL stuff from multiple threads.  This is a good way to trash things on the GPU under certain drivers :)

**Comment by Tailorware** [comment]
I still have the missing cursor problem with the current release-20150919. When the game is started via desktop icon, no cursor is visible. 
I am using windows 8 on a lenovo y70 gaming laptop.
