### ISSUE TITLE
Disable Nuke function in Red Alert

### ISSUE THREAD

**Issue by TheCazz78** [OpenRA/OpenRA#7879]
I like to disable Nuke for everyone when I create a server.
Sometime it is fun to use Nuke but most of the time I like to use tanks and that to win a game.

**Comment by penev92** [comment]
IMO there should be a `Superweapons: Disabled/Limited/Unlimited` dropdown in the lobby settings.
(where `Limited` limits them to 1 ofc, `Unlimited` removes build limits for them)

**Comment by pchote** [comment]
Fixed by #10580.
