### ISSUE TITLE
Player color validation: still not enough contrast to terrain [$22]

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#7902]
Despite the color validation colors that are too close to terrain can still be chosen (and are actually even auto-suggested after color validation "strike").

![hard_2_see](https://cloud.githubusercontent.com/assets/10639257/7043746/69cd609e-ddec-11e4-82bd-8b28fa6cb54d.jpg)

Fixing it would also boost significance of the stealth units.

Random color suggestions need work too (example: first suggest colors of all available hues before repeating a hue ...)

**Comment by fgdzfggsfgsfgsf** [comment]
Yeah the dark green should really be disallowed, it massively affects gameplay, seeing the GPS icons through shroud is a nightmare.  Just had a game where not much happened, I scanned the opponents base about 5 times and somehow missed the dark green icon for their a building(nuke).
