### ISSUE TITLE
TD SAM sites don't close after losing their target

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#7926]

**Comment by obrakmann** [comment]
Never mind, that already happened in the last release

**Comment by penev92** [comment]
The problem here actually is that ... it doesn't lose the target - #7567.
#7654 should fix this.

**Comment by pchote** [comment]
> Never mind, that already happened in the last release

Are you sure about this?  It looks pretty broken, and I don't remember seeing that before now.

**Comment by obrakmann** [comment]
Some finding from a little debugging this morning:

1. When the SAM site is tracking a target:
`AttackPopupTurreted` inherits from `AttackTurreted` which in turn inherits from `AttackFollow`. The SAM site will close if the `idleTicks` counter crosses a threshold. The counter is reset to 0 every time `AttackPopupTurreted.CanAttack` runs, which happens every tick because it's called in `AttackFollow.Tick`, so the counter never gets higher than 1.

2. When the SAM site is idle:
The state tracking doesn't work properly. The only state that will make the SAM turn into the direction where the close animation can start is `PopupState.Open`. However, somehow it never gets out of the `PopupState.Rotating` state. Also the `turreted.DesiredFacing` value is reset to null somewhere along the way, so the turret never turns.
