### ISSUE TITLE
Intervention! mission become Soviet VS Soviet in playtest20150408

### ISSUE THREAD

**Issue by carlos444** [OpenRA/OpenRA#7935]
![screenshot-openra](https://cloud.githubusercontent.com/assets/2613235/7105507/fe5a2c86-e14f-11e4-82b1-f2bfaedd1a37.png)

This is in Linux(deb) edition.
Where is allied?

**Comment by obrakmann** [comment]
This is interesting. The player's faction seems to be randomized. Sometimes it's allies, sometimes soviets.  Happens on the other missions as well.

**Comment by carlos444** [comment]
Indeed!

**Comment by obrakmann** [comment]
The problem [begins here](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Player.cs#L89), where `Player::ChooseCountry()` is called with the default `requiresSelectable` value of `true`. The country given in the player reference isn't selectable, so `ChooseCountry()` [defaults to using a random country](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Player.cs#L58).
