### ISSUE TITLE
Editor crashes on startup, playtest 04-08-2015

### ISSUE THREAD

**Issue by GiantCrocodile** [OpenRA/OpenRA#7939]
I'm using the playtest from 04-08-2015 (mm-dd-yyyy) and the editor is crashing on start up. Is there a specific log I should provide to you? I'm running Windows 8.1 x64.

Edit: I deleted any log and started the editor again. It still crashes but no log gets created so I can't supply you with further log details.

**Comment by penev92** [comment]
A screenshot of the error dialog would be a good start.

**Comment by GiantCrocodile** [comment]
It is the default 'OpenRA.Editor.exe stopped to work'-windows error.

**Comment by pchote** [comment]
You need to run the game and install the RA game assets before you can run the (legacy) editor for any mod.  We are hoping to include a new and much improved editor with the release after next.

**Comment by obrakmann** [comment]
@GiantCrocodile: please let us know if installing the mod assets solved this issue for you. Thanks!

**Comment by GiantCrocodile** [comment]
Oh, I'm sorry! I've forgot to add my comment and close this one.

Yes downloading the mod assets fixed the crash for me. An error or something for this would be nice.

**Comment by obrakmann** [comment]
Thanks for the update. The external editor will be phased out soon-ish and be replaced with an internal one which you'll only be able to access if you already have the assets.
