### ISSUE TITLE
Playtest 20150408 cursor not visible after program start

### ISSUE THREAD

**Issue by powerkane** [OpenRA/OpenRA#7942]
courser  in play test 20150408 when starting with the redalert mod loaded will not show courser but if you start with the tibirian dawn mod loaded courser will be there it just doesnt load if u load it with the ra mod preloaded example if you play the ra mod then quit then run the game again the cursor will be gone tried on 3 diff pcs

**Comment by obrakmann** [comment]
What is your OS and hardware? I've seen something that could be described like that on an older PC of mine. It only occured when the system had been running for a long time and I've started the game upwards of several dozen times. Rebooting fixed it.

**Comment by chrisforbes** [comment]
If we fail to create the HW cursors, we should probably fall back to SW cursors. This also smells like we're causing the windowing environment to leak cursors. This sort of thing was definitely possible on Windows back in the day -- I'm not sure if it's still a factor.

**Comment by pchote** [comment]
> If we fail to create the HW cursors, we should probably fall back to SW cursors.

We should already be doing this, but it may be bugged.

**Comment by RoosterDragon** [comment]
@powerkane: A similar problem has been rectified for another user in playtest 20151031 (#9490) - can you give the new playtest a go and let us know if this is still a problem for you?

**Comment by penev92** [comment]
Closing in favor of #10172.
