### ISSUE TITLE
Player looks like AI in lobby

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#7946]
Repo case:
Go to this map and select a slot below the bot:
![playerai_a](https://cloud.githubusercontent.com/assets/7704140/7116113/2752769e-e1ef-11e4-9c34-2492d96cc8ba.png)
Change the map back to blank:
![playerai_b](https://cloud.githubusercontent.com/assets/7704140/7116114/283101d4-e1ef-11e4-8238-68a473e64bfc.png)

Game starts as normal (I'm abcdefg30 again) and as you can see in the chat, messages are still correct as well.

Happens in other mods as well:
![player_bot_buga](https://cloud.githubusercontent.com/assets/7704140/7116158/a92c9816-e1ef-11e4-8280-b2932e11e4b0.png)
##

**Comment by MicroJOo** [comment]
duplicate #3200 , please close

**Comment by abcdefg30** [comment]
I didn't chose that name... That did the lobby.
This isn't only about the name; if you look at the second screenshot, you can see that you can get the AI menu on players using this bug.

**Comment by obrakmann** [comment]
Probably similar to #7022 and #6754

**Comment by abcdefg30** [comment]
Looks like this was fixed by #13290.
