### ISSUE TITLE
Unloading harvester has pixel errors

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#7949]
There are three red dot pixels visible while a harvester is unloading at refinery.

**Comment by reaperrr** [comment]
Which mod?

**Comment by penev92** [comment]
A screenshot is usually the best approach with such issues.

**Comment by deniz1a** [comment]
Red Alert. I couldn't take screenshot because it flickers.

**Comment by MicroJOo** [comment]
when the refinery is overloadet and the harvester stuck in a "unloading loop" ... you can see the dots ... pause the game , then you can make a screenshot

![harvesterdots](https://cloud.githubusercontent.com/assets/9139965/7138492/03339c0c-e2c1-11e4-87db-5824a48217d3.png)

**Comment by MicroJOo** [comment]
fixed it ... someone has to grab the file and put it in ra/bits 

https://www.dropbox.com/s/qdgo7mqo5zgtwtl/harv.shp?dl=0
