### ISSUE TITLE
OpenRA needs a Quick Build feature!

### ISSUE THREAD

**Issue by Chubzdoomer** [OpenRA/OpenRA#7964]
Red Alert 2 had this handy feature in which once a building had been constructed, you could simply press the hotkey corresponding to its tab (Q for regular, W for defenses) in order to place it.  I'm not sure what its official name was, but I've always called it the "Quick Build" feature.

The Quick Build method is significantly quicker and easier than the one featured in OpenRA in which you must first switch over to the correct tab, then either click on the building's portrait or press the corresponding F-key in order to place it.

Both methods have their pros and cons:

[Red Alert 2]
+ Faster to place buildings (Quick Build)
- Slower to start constructing buildings (no hotkeys)

[OpenRA]
+ Faster to start constructing buildings (hotkeys)
- Slower to place buildings (no Quick Build)

So why not give us the best of both worlds?  Keep the F-key system, but allow us to quickly select (and place) "finished" buildings via the Quick Build method!

I hope this will be considered for a future build, because it would make the gameplay even more fluid and intuitive than it currently is.

**Comment by LunaticEdit** [comment]
Right now there's "change production tab" back/forth hotkeys. What if we made each production tab have a specific hotkey. That way if you press it once, you jump to that production tab. If you press a production hotkey while on that tab, it auto-builds the last thing you built on that tab (if applicable). That way you can have quick jumping between specific tabs AND quick builds using the same keys.

**Comment by Chubzdoomer** [comment]
Doesn't OpenRA already have hotkeys for each production tab by default?  I just loaded up the latest build and the hotkeys are E, R, T, and Y (Regular buildings, defenses, infantry, and vehicles).

**Comment by LunaticEdit** [comment]
That's true, completely forgot about that. For kicks I'll see if I can throw something together!

**Comment by penev92** [comment]
Selecting the ready structure for placement when you select a tab sounds good to me.
