### ISSUE TITLE
Infantry go to repair pad along with damaged vehicles

### ISSUE THREAD

**Issue by Beep6581** [OpenRA/OpenRA#7969]
Playtest 20150408
Group infantry and vehicles, send the group to a repair pad. The undamaged vehicles stay, the damaged vehicles go, and so do the optimistic infantry.
##

**Comment by penev92** [comment]
All selected infantry are issued a Move order toward the repair pad (regardless of health state) because they don't have the `Repairable` trait that manages the interaction of vehicles with the repair pad.

**Comment by Beep6581** [comment]
No longer valid.
