### ISSUE TITLE
Some desert maps use temperat trees.

### ISSUE THREAD

**Issue by clemty** [OpenRA/OpenRA#7973]
This is probably the correct behavior, but it is markedly different from earlier versions of openra
screenshot is from Tiberium Oasis, included in the latest playtest

![trees](https://cloud.githubusercontent.com/assets/10729559/7215783/cf2ce9d6-e5e5-11e4-8c95-78a305af7cdb.jpg)

**Comment by Mailaender** [comment]
The correct fix would be to remove the temperat trees and replace them with desert ones. We already fixed the editor in https://github.com/OpenRA/OpenRA/pull/5372.
