### ISSUE TITLE
RA road minimap color is wrong

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#7977]
The minimap shows roads as brown, but they are actually more grey.  This is most visibly bogus where roads pass over bridges (which show the correct color).

![road](https://cloud.githubusercontent.com/assets/167819/7218024/c7e80a8e-e6a8-11e4-9a4b-35aaae45cc5b.png)

**Comment by Mailaender** [comment]
I did this on purpose in https://github.com/Mailaender/OpenRA/commit/3ced83e94e0a23f1d866048a9521dd2134b41601 so you can differentiate roads, from bridges, from cliffs though.

**Comment by MicroJOo** [comment]
@pchote : its a good thing , streets are easier to detect on the mini-map (and previews)

**Comment by dan9550** [comment]
i feel the grey is easier to notice, that is it contrasts better.

**Comment by abcdefg30** [comment]
I'm with @Mailaender and @MicroJOo.

**Comment by pchote** [comment]
IMO it doesn't need to go completely grey, but the saturation needs to be dialed back a notch so it doesn't contrast so garishly.
