### ISSUE TITLE
Red Alert: Attack move shows mine location

### ISSUE THREAD

**Issue by megavirus11** [OpenRA/OpenRA#7994]
When a player builds a minelayer and lays mines for the enemy, the enemy will be able to see the location of the mines when Attack moving.
- Build minelayer
- Lay mines
- Enemy player will Attack Move to the enemy base
- Enemy units will target mine locations when refreshing Attack Move Command if a mine is close
##

**Comment by pchote** [comment]
It seems to be a bit more subtle than this.  I was able to reproduce this (and also discovered #7995) the first time I tried, but not a second time.

**Comment by FrameLimiter** [comment]
This was fixed by #12171
