### ISSUE TITLE
GDI Dropship Bay

### ISSUE THREAD

**Issue by BlueJersey112** [OpenRA/OpenRA#8003]
Deep in the code for Tiberian Sun, there was something about a Reinforcement Bay. I remember one of the guys from Petroglyph Studios in a forum thread saying that it was a GDI structure and was supposed to act like the CHOAM Starport in the Dune series of games (except that a GDI dropship, instead of Carryall would be used to deliver the units).

This would be a very cool addition to the open-source version of Tiberian Sun that would help complete what the original creators wanted to do with the game.

**Comment by penev92** [comment]
This will have no place in the official TS mod, unfortunately, because that is planned to be an exact remake.
Any custom mod, however, is free to include that (and more).

**Comment by Unit158** [comment]
Well, an exact remake until we get it done.

**Comment by pchote** [comment]
This is a bit out of scope for our default TS mod, but can be added by custom maps or third party mods.

**Comment by GraionDilach** [comment]
The Dropship Bay was included in TS as a map asset though (without any functions) so I'd have said this should be closed when it gets added to the yaml, but ahwell.

**Comment by BlueJersey112** [comment]
That's alright, the Dropship Bay is a bit of an extra to start with. But thanks for filling me in.
Mike 


    On Sunday, November 22, 2015 5:12 AM, Zimmermann Gyula <notifications@github.com> wrote:
 

 The Dropship Bay was included in TS as a map asset though (without any functions) so I'd have said this should be closed when it gets added to the yaml, but ahwell.—
