### ISSUE TITLE
Path finder should ignore blocking units when pathing over bridges

### ISSUE THREAD

**Issue by MutterOberin** [OpenRA/OpenRA#8008]
Changes to Path Finding Algorithm:

1) Handling of temporally occupied tiles. For example a bridge with a tank on it. It is still possible to go over that bridge. In most cases the tank will be gone when reaching the bridge.

2) TS: Handling of automatic gates. A gate is a occupied tile until it opens.

**Comment by pchote** [comment]
2) is already handled in #9981.

**Comment by pchote** [comment]
1) is how the path finder is *supposed* to work, but for some reason this no longer appears to be the case.

**Comment by pchote** [comment]
I stumbled over the cause for 1) and fixed it in #11470.
