### ISSUE TITLE
`make check` fails under mono 4.0

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#8015]
Mono 4.0 removes the 3.5 build targets that Stylecop (or maybe stylecopplus?) is compiled against. I expect this will break travis once the official release is pushed to the repos.

```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'Microsoft.Build.Framework, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at OpenRA.Mods.Common.UtilityCommands.CheckCodeStyle.Run (OpenRA.ModData modData, System.String[] args) [0x00087] in /Users/paul/src/OpenRA/OpenRA.Mods.Common//UtilityCommands/CheckCodeStyle.cs:39 
  at OpenRA.Utility.Program.Main (System.String[] args) [0x0015a] in /Users/paul/src/OpenRA/OpenRA.Utility//Program.cs:54 
[ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'Microsoft.Build.Framework, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at OpenRA.Mods.Common.UtilityCommands.CheckCodeStyle.Run (OpenRA.ModData modData, System.String[] args) [0x00087] in /Users/paul/src/OpenRA/OpenRA.Mods.Common//UtilityCommands/CheckCodeStyle.cs:39 
  at OpenRA.Utility.Program.Main (System.String[] args) [0x0015a] in /Users/paul/src/OpenRA/OpenRA.Utility//Program.cs:54 
make: *** [check] Error 1
```

**Comment by Mailaender** [comment]
I don't think we use the MSBuild part. Maybe we should switch to http://www.nuget.org/packages/StyleCop/.

**Comment by obrakmann** [comment]
It looks like we need to solve this soon-ish, since it appears that travis will update to mono-4.0 (which is also the reason why builds currently fail): https://github.com/travis-ci/travis-ci/issues/3776#issuecomment-96794169

**Comment by akoeplinger** [comment]
btw. Mono 4.0 doesn't remove the build targets, you should still be able to compile against the .NET 2.0/3.5 profile.

**Comment by Mailaender** [comment]
Filed https://github.com/OpenRA/OpenRA/pull/8047 as an emergency measure.

**Comment by Mailaender** [comment]
https://github.com/DotNetAnalyzers/StyleCopAnalyzers is probably the way to go. However I haven't figured out how to embed it into our command line utility or the build process.

**Comment by Mailaender** [comment]
Filed https://github.com/OpenRA/OpenRA/pull/8196 so we get command line StyleCop back ASAP (so please review and merge this in time).
