### ISSUE TITLE
helicopter gets overlapped by buildings

### ISSUE THREAD

**Issue by MicroJOo** [OpenRA/OpenRA#8018]
probably regression from #7842

![regression chopper](https://cloud.githubusercontent.com/assets/9139965/7332662/d9a0b04a-eb4a-11e4-9083-123a4852dc42.png)

**Comment by Phrohdoh** [comment]
Possibly related to https://github.com/OpenRA/OpenRA/pull/7904#issuecomment-90997724.

**Comment by penev92** [comment]
Yes, it's the same thing. The aircraft flies low enough for the renderer to get confused.
