### ISSUE TITLE
Server cannot detect latency and drops players

### ISSUE THREAD

**Issue by bluescreen** [OpenRA/OpenRA#8019]
It seems the server sometimes cannot detect latency and drops players off. It is also possible to join multiple times.

![bildschirmfoto 2015-04-25 um 15 18 01](https://cloud.githubusercontent.com/assets/339613/7333041/af040f76-eb5e-11e4-8644-918c137c9361.png)

**Comment by Unit158** [comment]
Chatting doesn't work either. There is something wrong after the player connects.

**Comment by bluescreen** [comment]
Would be great if you can fix this soon. Right now there is only one server playable for Tiberian Dawn

**Comment by Mailaender** [comment]
@xaionaro Can you look into this?

**Comment by ihptru** [comment]
Restarted all servers, hope that helps.

**Comment by abcdefg30** [comment]
Works for me now. @bluescreen?

**Comment by bluescreen** [comment]
Yes all server seem to work find now. Thanks!
