### ISSUE TITLE
Battlefield News stops blinking if you switch mods

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#8022]
The Battlefields News button stops blinking if you switch mods.

This is a little bit annoying because a player might miss the message if he/she switches mods.

After switching mods, a news.yaml file is added in the content folder while the player hasn't even clicked on the Battlefield News button/drop-down menu.

**Comment by pchote** [comment]
We now open the panel instead of blinking, which is much harder to miss.
It's not possible to keep the panel open across mod switch because the dropdown is dismissed as read as soon as the player clicks the switch mod button (this is just how our dropdowns work in general).
