### ISSUE TITLE
Rubber band selection does not work while AttackMove is active

### ISSUE THREAD

**Issue by ozzyyzzo** [OpenRA/OpenRA#8023]
Hello,

Since 24042015 release there is an annoying bug which is causing selection of units difficult when using hotkeys. Say you are selecting some units and move them using attack command then try to select another group by dragging on screen.. it doesn't work as it should.

In other words.. when your cursor is green you can select and re-select any group of units by dragging on screen... if you cursor is red you can't .

**Comment by ozzyyzzo** [comment]
Oops this concerns

**Comment by MicroJOo** [comment]
to make this easy ... "attack-move" doesnt switch back to the normal cursor (the green one ,which would allow you to select units again) ... instead it stays on the red cursor until the player right-clicks somewhere ...

**Comment by ozzyyzzo** [comment]
this regression is affecting all mods.

**Comment by penev92** [comment]
How is this even a bug?
AttackMove (A) isn't a modifier like Shift.
Also you *can* exit this mode by left-clicking somewhere.

**Comment by pchote** [comment]
@penev92: this is a bug because the behaviour of our activated order generator modes (attack move, guard, etc) is inconsistent with the default order generator.  There is no need for drama or hostility over this.

**Comment by ozzyyzzo** [comment]
closed with 20150919

**Comment by ozzyyzzo** [comment]
Bug still active in latest 20151031 playtest. Would be cool if it will be fixed for next xmas release because for each selection using Attack key it requires unselection to get rid of previous one.

Which is severly affecting units management time.

hth

**Comment by ozzyyzzo** [comment]
Hello, i think that there is still a problem with the selection as some previously selected groups seem to be updated with new target positioning (from current units selection or something) orders while the group is not selected anymore.. There are also strange behaviors with spawning points of buildings re affected to strange places with the same idea as previously described .. a building was selected and unselected then another unit is controled and when i come back to the building spawning point has been set silly.. 
Finally, some unwanted building constructions seem to be added to the construction queue.. could be also on units construction queue but more rarely than buildings.

You can find a replay which is showing a group of 4 soldiers that are located in the middle of the map,
around 30s , When they were selected the order was to attack on left side (i'm intensively using attack key when i'm playing. ) then i have selected another unit or building (can't remember what is was..,also  too bad that selection can't be shown during the replay) and then you will notice that the 4 soldiers group will change direction to the right just like another order was given... but it wasn't at all, then i need to re select and re assign a new attack to the left.. :-/

As it occurs a lot when i'm playing (really too often definitely) , i think it is a bug related to this previous topic rather than myself doing silly/strange things with the mouse or keys.. ^^

you can find the replay there : 

 http://www.jeuxdecartes.ovh/data/OpenRA-2016-10-selectionBug.orarep


hth

**Comment by pchote** [comment]
It sounds like OpenRA is thinking you are clicking in places that you aren't.  Do you have any mouse control utilities (for macros or other custom behaviour) installed?

**Comment by ozzyyzzo** [comment]
yep that's right i'm just using attack key 'a' and selecting / unselecting  normally units.

It is also really difficult to reproduce as i 've tried to do so but wasn't able to do it playing alone..

Also it seems to occur more often with lag.

**Comment by ozzyyzzo** [comment]
or i would say that openra is affecting clicking places to current and previously selected units / buildings for some reasons.

**Comment by pchote** [comment]
If things are being added to your construction queue then the game thinks you are either clicking on the sidebar or that you're pressing the production hotkeys.

**Comment by ozzyyzzo** [comment]
i'm not using production keys shortcuts at all.. so i think it is related to the same clicking places problem.

**Comment by ozzyyzzo** [comment]
if it can helps while selecting / unselecting clicking places for units i can still maintain attack key pressed or unpressed § pressed alternatively... that's what i'm calling using 'attack' key intensively when i'm playing :)

**Comment by Micr0Bit** [comment]
maybe fixing #11896 could also fix this here ?
