### ISSUE TITLE
Music plays for one track, then doesn't continue

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#8033]
In RA the music starts to play on the splash screen and continues when you are ingame. Once the first track finishes however, it does not continue to play the rest of the tracks.

Release 20150424
Ubuntu 14.10

**Comment by penev92** [comment]
Did you tick the "Loop" checkbox in the music menu?

**Comment by reaperrr** [comment]
I noticed that, too. It just repeats that one track from the shellmap and doesn't cycle through the playlist.

**Comment by r34ch** [comment]
@penev92 Loop is not enabled. I assume it means loop the *individual* track? (There is no tool-tip to clarify)

@reaperrr After joining a match, when the track ends I just get silence.

**Comment by obrakmann** [comment]
Fixed with #8562.
