### ISSUE TITLE
Crash after the game is over

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#8039]
release-20150424, RA mod, after the multiplayer game was over and people left the game crashed
on Windows 8.1

syncreport.log: http://s000.tinyupload.com/index.php?file_id=57408451882591823956
exception.log: http://s000.tinyupload.com/index.php?file_id=83440802256113661905

(it doesn't show up in the replay...)
replay: http://s000.tinyupload.com/index.php?file_id=06116473230166988506

**Comment by penev92** [comment]
>[19:48] <penev> so... the game desyncs when someone kills OpenRA while ingame, right?
[19:48] <penev> Alt + F4 for example
[19:49] <penev> my money is on someone doing exactly that when the score screen popped up 

I believe we already have a ticket for that, but can't look for it now.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/issues/4563

**Comment by pi99y** [comment]
Seems that people are now abusing this to crash everyone's clients (mid-game)...

**Comment by MicroJOo** [comment]
people dont abuse anything ... its a out-of-sync that "can" happen when someone quits during a game ... and because of other things ... so please .. dont freak out

**Comment by pi99y** [comment]
OK, seems that it is indeed harder to reproduce/abuse than I thought...

**Comment by Mailaender** [comment]
The logs are gone. No way to investigate it.
