### ISSUE TITLE
Dune 2000 carryall goes under the refinery

### ISSUE THREAD

**Issue by sinf** [OpenRA/OpenRA#8042]
Right wing of this carryall is intersecting the refinery:
![carryallclipping](https://cloud.githubusercontent.com/assets/9487531/7339265/9578abf2-ec71-11e4-8be1-74d024a20137.png)

**Comment by penev92** [comment]
That is a series of well-known z-sorting problems, but I could only find #8018 now.

**Comment by Mailaender** [comment]
I believe this was addressed by https://github.com/OpenRA/OpenRA/pull/7862 which fixed the Dune 2000 refinery top overlay being rendered twice.
