### ISSUE TITLE
OpenGL Error- Crash  when starting the game 

### ISSUE THREAD

**Issue by MicroJOo** [OpenRA/OpenRA#8049]
started openra.exe , crashed ... 

exception.log 

Red Alert Mod at Version release-20150424
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.18408
Exception of type `System.InvalidOperationException`: OpenGL Error: See graphics.log for details.
   bei OpenRA.Renderer.Sdl2.ErrorHandler.CheckGlError()
   bei OpenRA.Renderer.Sdl2.Texture.GetData()
   bei OpenRA.Graphics.Sheet.CreateBuffer()
   bei OpenRA.Graphics.Sheet.GetData()
   bei OpenRA.Graphics.Util.FastCopyIntoSprite(Sprite dest, Bitmap src)
   bei OpenRA.Graphics.SheetBuilder.Add(Bitmap src)
   bei OpenRA.MapCache.LoadAsyncInternal()
   bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()

____________________________________________________________________________

graphics.log

GL Error: InvalidOperation
   bei OpenRA.Renderer.Sdl2.ErrorHandler.CheckGlError()
   bei OpenRA.Renderer.Sdl2.Texture.GetData()
   bei OpenRA.Graphics.Sheet.CreateBuffer()
   bei OpenRA.Graphics.Sheet.GetData()
   bei OpenRA.Graphics.Util.FastCopyIntoSprite(Sprite dest, Bitmap src)
   bei OpenRA.Graphics.SheetBuilder.Add(Bitmap src)
   bei OpenRA.MapCache.LoadAsyncInternal()
   bei System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()

OpenGL Information:
Vendor: 
Renderer: 
GL Version: 
Shader Version: 
Available extensions:

**Comment by pchote** [comment]
It looks like one of @RoosterDragon's perf prs has introduced OpenGL calls from worker threads. This is a recipe for disaster, and is probably also the cause of #7877.

**Comment by Mailaender** [comment]
Can you please test if https://github.com/OpenRA/OpenRA/pull/8103 fixes it?

**Comment by MicroJOo** [comment]
@Mailaender : this was a 1-time-crash ... so i cant just reproduce it ... testing a possible fix for this is a "neverending test"
