### ISSUE TITLE
Remove/delay/wait TD clone-function in crates

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#8058]
Hi.

Most of the games in TD are played with crates off. That is because the players say it will end the game early.. Even when we play 3 vs 3... When you then loose you construction yard, often all hope is lost. 
Can the "clone units" have 5-10 min waiting time? Can crates wait before they arrive? Can anything be done? At least the player AoA want a change in crates, and he play TD alot. 
please help us find a way to make players use it again...

**Comment by Mailaender** [comment]
I vote for removal. It seems a bit unpolished and ridiculous. Why do they just multiply. There is no cargo plane dropping them, they just appear out of nothing. Also I agree: the balancing is terrible. One recon bike. Find a crate when scouting the enemy. Five recon bikes. Trash the enemy base. Game over. Restart.

**Comment by abcdefg30** [comment]
What about adding a delay to them and use a paratroopers support power?
This could be playercontrolled or just drop the units at the crates location.

**Comment by kyrreso** [comment]
ping, still needed..
