### ISSUE TITLE
TD: Engineers damaging buildings don't trigger a notification

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#8062]
##

**Comment by obrakmann** [comment]
What kind of notification do you mean? I get an "Our base is under attack".

**Comment by Unit158** [comment]
The last game I played had no notification whatsoever. It might have been a cooldown thing but a "building captured" notification such as the one found in d2k when a building is stolen may be in order.

**Comment by abcdefg30** [comment]
Closing as this doesn't appear to be present on the last release.
