### ISSUE TITLE
Fix or remove Appveyor CI

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#8069]
It is extremely slow, and fails now almost all of the time for reasons unrelated to the pr being tested (either timing out during checkout, or failing to fetch packages from nuget).  This has gone from amusing, through ridiculous, and now sits in the completely unacceptable basket.

**Comment by Phrohdoh** [comment]
:+1:

**Comment by pchote** [comment]
It is now also failing when it succeeds: #8065 shows "AppVeyor build failed", but then "Build success" when clicking through to the details page.

**Comment by Mailaender** [comment]
I opened some tickets at http://help.appveyor.com/discussions/problems as these are a lot of different issues we are having. They are probably all rooted by the http://azure.microsoft.com/en-us/status/#history connectivity problems.

**Comment by obrakmann** [comment]
I'm all for removing it. Appveyor is pretty aweful. I suggest to move back to travis' non-docker infrastructure and use its caching ability instead. I'll try to get something working.

**Comment by Mailaender** [comment]
We can cache the whole thirdparty directory once https://github.com/OpenRA/OpenRA/pull/7953 is reviewed and merged.

**Comment by Mailaender** [comment]
Filed https://github.com/OpenRA/OpenRA/pull/8077 as promised.
