### ISSUE TITLE
Negating double inherited traits does not work

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#8086]
If a trait is on the default (`^Helicopter` e.g.) and on the actor (`TRAN`) then simply negating it (with `-`) won't work. Tested with `LeavesHusk` on the TD `TRAN` (`LeavesHusk` is on `TRAN` but not on the default. Adding it to default also breaks the custom removal on a map).
Also noticeable with `TRAN` in #8048 and `Selectable`. [Another example.](https://gist.github.com/abcdefg30/0e6a3f33e099f5e0efd2)

Sorry if I'm too confusing. ([Here](https://gist.github.com/abcdefg30/bb8959d4c9b9a7640a50) is my IRC spam regarding this.)

**Comment by pchote** [comment]
Does it work if you add the removal twice?  The first removal will probably be removing the inherited override, so that your actor then ends up with the unmodified parent rules.

**Comment by abcdefg30** [comment]
> Does it work if you add the removal twice?

No. Either the map is disabled or `Exception of type "System.InvalidOperationException": No free spawnpoint.` shows up.

**Comment by pchote** [comment]
Ok.  This will require a rework of my rework.  It won't be particularly hard, but also isn't trivial.

**Comment by pchote** [comment]
I have a branch that probably fixes this (https://github.com/pchote/OpenRA/commits/yaml-removals), but I don't really feel like writing unit tests or doing ingame tests for it just yet.

**Comment by Mailaender** [comment]
Looks like this is already fixed? At least the `TRAN` example in nod04b https://github.com/OpenRA/OpenRA/commit/c23ee1be2e58bcc512ceb106d56a619bab48eb33#diff-cc6e2c8cab65841973b60343a8c32f0eR548
