### ISSUE TITLE
D2k map importer (or tileset) regression

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#8089]
Three months ago, the D2k map importer was merged.
Shortly before it was, I took the screenshot found [here](https://github.com/OpenRA/OpenRA/issues/5875#issuecomment-67397799), ingame from a map I had imported with it. Notice how there are no obvious visual problems.
![](http://i.imgur.com/BPfq1xA.png)

Today I tried to import the same map using the latest bleed (commit a310411bcc70dce87d63d115862583a7b2af6265).
The result was:
![](http://i.imgur.com/yXShwGU.png)

I then checked out the branch that the map importer was merged from (commit 922af4d9cf0b99942f6b0823b16691782e8ddb33, 3 months ago) and reimported the map. The result was this:
![](http://i.imgur.com/pGLEACb.png)

**And finally, this is how the map *should* look:**

![](http://i20.photobucket.com/albums/b215/pa-pa-pa/mapYYYY-12-DD_06-30-35.png)

Obviously even the originally imported map was not perfect, but it was much, much better than what bleed imported today.

**EDIT:** The map importer was merged on 18.02. The 28.03 playtest produces the same results as current bleed, which means the situation regressed during the first 5 weeks after it was merged. This seriously cuts down on commits that need to be checked.

**Comment by reaperrr** [comment]
I'd suggest to start with checking 
https://github.com/OpenRA/OpenRA/commit/edbb31afe1c8d8a11ca277cf45d4a958e8abe487

 and if that still works, check
https://github.com/OpenRA/OpenRA/commit/491c851c875f236fa4a3b4f05ad5371d775ef9f8

**Comment by penev92** [comment]
Good call, @reaperrr, it was 491c851c875f236fa4a3b4f05ad5371d775ef9f8.
Pinging @pchote.

**Comment by Mailaender** [comment]
The diff was too large for GitHub's web interface so I guess it slipped through unreviewd. https://github.com/OpenRA/OpenRA/pull/7707/files#diff-cfaa3ded05e69dddf4b1e0b933eabaf9

**Comment by pchote** [comment]
This is because the d2k importer assumes that the tileset name == template image.  The whole purpose of my earlier pr series was to remove that kind of magic translation.  If you change your input arguments to include the `.R8` at the end of the filename then it should work.

**Comment by penev92** [comment]
Looks like you are right.
