### ISSUE TITLE
Why not Generals instead of countries for RA?

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#8093]
Then we can have more options for making stuff?

**Comment by obrakmann** [comment]
There are no plans to support Generals in the foreseeable future.

**Comment by Phrohdoh** [comment]
It has been discussed many times before that "more options for stuff" doesn't inherently make the game better or more balanced.

**Comment by Mailaender** [comment]
We had bots with WW2 general names. I personally don't want to see Rommel etc. in the game again.

**Comment by epicelite** [comment]
NO you guys I mean like! In Red Alert mod you have "Germany, France, etc" which special unit or whatever. Why don't we just have different generals for the soviets/allies because I mean there's only so many countries in Red Alert.
