### ISSUE TITLE
[Packages Mirror] Germany - Berlin

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#8107]
i had uploaded the packages for the Mods to my VPS. Maybe we can add them to the list. All Packages are taken from ppm

TS
``
http://81.169.246.181/ts-packages.zip
``
CNC
``
http://81.169.246.181/cnc-packages.zip
``
RA
``
http://81.169.246.181/ra-packages.zip
``
D2K
``
http://81.169.246.181/d2k-103-packages.zip
``

**Comment by baxxxster** [comment]
I guess you can suggest them here: https://github.com/OpenRA/OpenRAWeb/tree/master/content/packages

**Comment by LipkeGu** [comment]
https://github.com/OpenRA/OpenRAWeb/pull/214
