### ISSUE TITLE
mobile gap-truck tweak

### ISSUE THREAD

**Issue by MicroJOo** [OpenRA/OpenRA#8112]
i've done some calculations , compared the "Mobile Gap Generator" with our "Gap Generator"
i see no reason for a Allies (french)  player to build a Mobile Gap Genrator (especially with the majority of games being about establishing a basewalk to win) and those stats : 
___________________________________________________________________________
Mobile Gap
$ 1200
0:29
220 hp
Mobile
             
Gap
 $ 1100 (with powerplant)
0:28 (with powerplant)
1000 hp
None Mobile
__________________________________________________________________________
Both have the same gap-range

~~imo , a candidate for a buff~~ ... especially because its supposed to be a "faction special" for france ... 
*Edit: not a buff , but a rule-tweak

**Comment by penev92** [comment]
#7665 promises to make it better.

**Comment by MicroJOo** [comment]
@penev92 : that wont make any difference ... i dont see a reason for a player to build a "mobile gap-generator with  -780 hp , $100 more costs and almost equal buildtime ... just because of its mobility ... and some "#7665 - shroud changes" ?

**Comment by HenrytheSlav** [comment]
What about making them able to cover a big area between set of 2/3/4 trucks? They would work as array. But still easy to kill.

**Comment by pchote** [comment]
Is this still relevant after all the recent rebalancing?
