### ISSUE TITLE
Decouple Selection Bounds from visual selection box

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#8120]
In my opinion this should be solved more like in the originals, where the visible selection box was purely cosmetic and not directly related to actual selectable area.

In other words, ```Bounds``` should control the selectable area just like now, while something like ```SelectionBoxSize``` (possibly moved to ```SelectionDecorations```) should control the size and position of the visible selection box.

**Comment by pchote** [comment]
Related to #6987.

**Comment by reaperrr** [comment]
Closed via  #8388.
