### ISSUE TITLE
Voice is played twice when selecting actor(s) via group key

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#8121]
Something must be wrong in ```Selection```-related code. When selecting a group via group key, the "Select" voice is played twice.

**Comment by LipkeGu** [comment]
its not a bug, ra2 has this feature (response) :) and other games too

**Comment by penev92** [comment]
It is played **twice**. It *is* a bug.

**Comment by penev92** [comment]
OK I tracked it down.
In `Sdl2Input.cs`, where all the input handling is done, there is a `switch` with [these two cases](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Renderer.Sdl2/Sdl2Input.cs#L139-L140).
Both of these cases trigger `inputHandler.OnKeyInput(keyEvent);`, which leads to everything being done twice.

To be honest, I'm surprised everything else that is tied to the keyboard works.

**Comment by pchote** [comment]
Key down and key up are separate events (one fires when the key is depressed, and the other when it is released).  Most of the widget / world input code handle them correctly, but apparently not the selection group code.
