### ISSUE TITLE
Music File not playing as intended

### ISSUE THREAD

**Issue by sajwang** [OpenRA/OpenRA#8127]
So I imported some music from Itunes and used an online m4a to wav converter.
Website: http://www.zamzar.com/uploadComplete.php?convertFile=m4a&to=wav
It works fine in Windows Media Player and Audacity, and tests fine in CNC Mixer. The Aud file I make out of it plays okay too.

Yet when I play the music in game, the music player seems to barf (make all the jokes about my taste in music you want ;) )

For example: I put in a song called Prescription Beats (Chemical Brothers)- there's a strong percussion in the beginning and its relatively fast in tempo.

When CnC plays it, it is slow, constantly sounding as though it is about to crash (thankfully it doesn't, but the point remains.)

Does anyone know what causes this?

**Comment by sajwang** [comment]
I forgot to add, it also slows down some songs and lowers the tempo.

**Comment by GraionDilach** [comment]
What did you use for WAV->AUD converting? Sounds like if the file kept the bitrate.

Technobabble: AUDs are 22 kHz mono. Source file is probably 44 kHz stereo. If the converter messed itself up/doesn't support changing channelamount/frequency range, then the 0end result will gonna slow down either to 1/2x or 1/4x speed.

**Comment by sajwang** [comment]
I will admit in terms of judging audio files by frequency it's a little over my head, but that site I used actually seemed to just be a bad site (probably guilty of what you said.) I used another website and didn't have this issue anymore. 

Thanks!

**Comment by penev92** [comment]
I take it this can be closed now?
