### ISSUE TITLE
Auto-restart doesn't know that a map is being created

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#8133]
Let's say you have really well started your map and for a reason, you want to change the display mode or resolution. you can do that in Settings but there's no warning about the map you are editing.. 

it could be a problem (it wouldn't be that smart to want to change the resolution while creating a map but who knows...)

So, maybe there should be a warning or a small dialog window asking the user to save the map before restarting OpenRA.

**Comment by Mailaender** [comment]
Actually, no this is redundant. Everyone knows that restarting applications or your computer doesn't automatically safe your progress. The warning on leaving the editor is enough.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/issues/8134 would be a much better solution.
