### ISSUE TITLE
Ingame Map Editor: tile glitch

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#8135]
I noticed a "tile glitch" in the editor : ater applying a tile (temperat tileset, debris, tile 107) on the ground and then, selecting another one in the sidebar, I noticed that, for half a second, a tile is displayed over the map, then quickly vanishes.

Steps to reproduce it:  select a big tile, use it, then right click (to unselect the tile), then reselect the tile in the sidebar. You'll notice that the tile quickly appears like a ghost for 1/4 second.

**Comment by pchote** [comment]
I can't reproduce this following your steps on #8065.

**Comment by x-a-n-a-x** [comment]
https://www.dropbox.com/s/2t5jzbez0n0pmi1/rec.mp4?dl=0

**Comment by pchote** [comment]
Fixed in #8065.

**Comment by x-a-n-a-x** [comment]
But you've also been able to reproduce it, right ?

**Comment by pchote** [comment]
I reproduced it and then fixed it.
