### ISSUE TITLE
AppVeyor Windows build significantly slower than Mono build running on Microsoft Windows

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#8153]
My numbers on Win7x64, i5-2500 CPU, RA shellmap:

OSX release 20150424: avg ~4.0-4.5 Tick / ~2.5-3.0 Render
Win release 20150424: avg ~5.5-6.0 Tick / ~4.0-4.5 Render

So the mono build is at least roughly 30-50% faster with identical compile settings (Debug mode, no optimization).

**Comment by pchote** [comment]
```
23:27 < pchote> I was really hoping that the release builds under windows were just that much better
23:27 < pchote> but oh well
23:27 < pchote> do you want to file an issue with some numbers?
23:28 < pchote> we can resurrect antares's branch that shifts the windows builds back to travis
23:29 < pchote> and this gives us some evidence stronger than "pchote has the heebie jeebies" to merge it
```

**Comment by obrakmann** [comment]
If anyone else wants to compare, here is current bleed (git-7154ce4) [compiled on Appveyor](https://ci.appveyor.com/api/buildjobs/lpv6k3b1d675q8iy/artifacts/OpenRA-.exe), and here's bleed [compiled with mono](https://seacloud.cc/d/5d1adbebce/files/?p=/openra/OpenRA-mono-20150513.exe)

**Comment by Mailaender** [comment]
That is terrible news. Is the slowness undone if you compile OpenRA with msbuild/VS in Release mode on Windows?

**Comment by Mailaender** [comment]
I tested the AppVeyor Windows build (setup extracted using Wine, adding only the .dll.conf files) vs. a self-compiled Makefile build running on Linux/Mono and I can't find a significant performance difference. My assumption is that it is not the generated IL code that is slow or too different, but some kind of flag that is set which only the original .NET runtime seems to adhere.

**Comment by reaperrr** [comment]
That flag is probably only set in debug mode then, because while I haven't tested with 20150424 in particular yet, both my previous tests as well as @RoosterDragon's Release config branch showed a massive performance advantage for Release config over Debug config when compiling with msbuild/VS.

**Comment by RoosterDragon** [comment]
I can confirm similar speedups as @reaperrr reports. Running on Windows the OSX build has noticeably lower times than the Windows build. I tried both the MS and mono runtimes and they produce similar numbers for both binaries.

Compiling the 20150424 release (via Visual Studio) in release mode with optimizations on produces results comparable to the OSX binary.

**Comment by Mailaender** [comment]
Can you file a pull request enabling the Release configuration so we can feed that through AppVeyor?

**Comment by pchote** [comment]
@Mailaender: That is a significant and risky change, and should not be done without very careful testing and consideration.

We have a history of windows-release builds generating code that desyncs against mono-compiled builds.  This is a large part of why we have always (before the nuget changes and its increasingly escalating damage control fixups) used the same binary / toolchain for all of our official builds.

**Comment by Mailaender** [comment]
Sounds like the only solution then. Filed https://github.com/OpenRA/OpenRA/pull/8187.
