### ISSUE TITLE
3rd-party mod dlls need custom config on Windows systems with older .NET

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#8156]
On Windows machines which don't have .NET versions newer than 4.0 installed, a custom OpenRA.Game.exe.config with this content is needed to avoid a ```SystemNotSupportedException``` with custom, directly downloaded 3rd-party mod DLLs:

http://www.codeitive.com/0HmeqUeeVq/c-configure-loadfromremotesources-through-code-not-appconfig.html

**Comment by Mailaender** [comment]
I filled https://github.com/OpenRA/OpenRA/issues/8198 for you as we definitely want to support the modding community and get this fixed in the next release.
