### ISSUE TITLE
Dune 2000 harvester sand out animation is glitchy

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#8160]
![sandouta](https://cloud.githubusercontent.com/assets/7704140/7619986/c8d41506-f9bc-11e4-86b6-b525b332a2d0.png) ![sandoutb](https://cloud.githubusercontent.com/assets/7704140/7619987/cb0ccc3c-f9bc-11e4-8136-3c55df094308.png)
It's somehow cut there.

**Comment by obrakmann** [comment]
Wouldn't be surprised if that is just the original art. Does #7979 make it any better?

**Comment by abcdefg30** [comment]
The screenshots are from #7979, but the glitch also exists on bleed.

**Comment by Mailaender** [comment]
We didn't change the sand out animation, that is the original sprite and I don't know what is glitchy there. The perspective is always a little strange in the pre-isometric Westwood games.
