### ISSUE TITLE
[PAPERCUT] Release installs under \OpenRA Playtest\

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#8165]
Or is it something I did?

**Comment by epicelite** [comment]
Or maybe this should be [POLISH]?

**Comment by deniz1a** [comment]
I think the maintainers assign appropriate labels, don't worry about it.

**Comment by pchote** [comment]
> Or is it something I did?

Yes, it is something you did.  We would appreciate it if you could do some basic research before filing bug or feature request tickets, as it takes valuable time for us to deal with them.
