### ISSUE TITLE
Reconsider the rendering blend modes.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#8168]
#7979 introduced a transluency parameter for all blend modes, but did not remove the dedicated `Transluency` mode.  This is a) a design smell, and b) potentially confusing ("what's the difference between normal blending with translucency, and translucent blending with translucency" asks the openra modder).

Our blend mode selection needs to be reconsidered in light of this new behaviour, and have their channel blending set up in a way that makes sense with and without translucency.

**Comment by Mailaender** [comment]
It seems our Translucency blend mode is a unique one and not covered by anything else. https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Renderer.Sdl2/Sdl2GraphicsDevice.cs#L290

I don't think people are stupid. Also PhotoShop seems to work the same. You get a selection of blend modes and an alpha slider. Not sure what you want to "reconsider" here.

**Comment by pchote** [comment]
The current blend modes are ad-hoc, and don't follow a consistent design.  At a minimum I expect we will want to rename the `Translucency` blend mode.  I strongly suspect that the proper fix will be to remove the sequence `Translucency`, and implement proper pre-multiplied alpha options on the palettes themselves.

**Comment by pchote** [comment]
Pre-multiplied alpha is definitely the way to go.  It gives us proper sand blending (which #7979 didn't achieve) as well as removing the unwanted plumbing.  I will have a PR for this later today.

![premultiply](https://cloud.githubusercontent.com/assets/167819/7667377/08a4c972-fbfd-11e4-8005-86055bfa9610.png)

**Comment by Mailaender** [comment]
:+1: The resulting sprite looks a lot better. In my case the alpha essentially hides that the wrong blend mode is chosen by making it less bright.
