### ISSUE TITLE
Leaving game in spectator breaks replays

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#8169]
When a player that is spectating leaves a current sessioned game the replays stops at that point. This happens in TD. The game itself will continue on just fine however. But the replay stops at that exact point when a player leaves spectator.

**Comment by penev92** [comment]
Was that player the one who provided the replay?

**Comment by Glanzor** [comment]
I am having the exact same problem.
And always with replays from games I got by participating myself, as a player.

**Comment by fgdzfggsfgsfgsf** [comment]
Pretty sure this happens at least some of the time in RA as well (maybe every time).

**Comment by pchote** [comment]
This was fixed in the last release.
