### ISSUE TITLE
windows: build system should check for existence of Visual C++ 2010 redistributable

### ISSUE THREAD

**Issue by clemty** [OpenRA/OpenRA#8180]
during my attempts to build openra the resulting build would crash on startup with a misleading error about freetype not being installed, but worked after some help from #openra and installing the Visual C++ 2010 redistributable

it would make sense to warn/error during the build (either by 'make all' or 'make dependencies') if VC2010 is not installed on a system

**Comment by LipkeGu** [comment]
http://stackoverflow.com/questions/27154519/using-powershell-cmdlet-to-list-installed-software-and-extract-software-name
