### ISSUE TITLE
France, reveal fake buildings easily!

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#8181]
If you double click (to highlight all of same type) on a fake building, it won't also highlight the real one revealing it to enemies easily. Works the other way around too, double click real building doesn't highlight fake ones.

Found by me, confirmed by Penev.

**Comment by pchote** [comment]
Why does double click to select all even work on enemy actors?

**Comment by penev92** [comment]
The problem is the same as #7469, but I agree that it shouldn't even work with enemy actor.

**Comment by epicelite** [comment]
Simple fix then, right?
