### ISSUE TITLE
AttackMove is broken for some unit types with "Defend" stance

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#8184]
While working on https://github.com/OpenRA/OpenRA/compare/bleed...obrakmann:default-stance-defend I noticed that AttackMove is broken for E3s when their stance is set to "Defend" (in ra at least, didn't test the other mods or other units yet). They acquire a target, but aren't close enough to fire and won't move in range. E1s don't seem to have that problem.

![screenshot from 2015-05-17 20 34 06](https://cloud.githubusercontent.com/assets/4331210/7671571/c15d7fb6-fcd6-11e4-96b3-89d543922590.png)
![screenshot from 2015-05-17 20 31 43](https://cloud.githubusercontent.com/assets/4331210/7671570/c15d77b4-fcd6-11e4-98c3-3d3ee9475ecb.png)

I can reproduce this in release-20141029, so it's not really a recent bug.

**Comment by obrakmann** [comment]
I found the problem. E3 has two weapons, a bazooka against ground targets with a range of five cells, and a MANPAD with a range of 7.5 cells. When a target gets within the MANPADs range, the E3 stops to attack, but can't because it's not a suitable weapon for the target. It can't go any closer though, either, because it's stance is "Defend", so it cannot move during the attack.

**Comment by matija-hustic** [comment]
Could you check if #8768 solved this?

**Comment by abcdefg30** [comment]
I was.
