### ISSUE TITLE
TS - Ingame map editor lets us place SNOW tiles in the TEMPERAT theatre

### ISSUE THREAD

**Issue by cjshmyr** [OpenRA/OpenRA#8188]
Check out the Misc Buildings, Clear tabs, etc. This isn't the case the other way around.

**Comment by LipkeGu** [comment]
are they listed in temperat.ini?

**Comment by pchote** [comment]
This is another "Blame westwood" case.  Those tiles are indeed defined in the vanilla temperat tileset.
