### ISSUE TITLE
Ingame map editor crashes when loading modded maps that fail YAML check.

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#8194]
They would normally just be "not compatible with this version OpenRA".

**Comment by Mailaender** [comment]
Which map editor?

**Comment by Unit158** [comment]
The new one.

**Comment by Mailaender** [comment]
I fear we need this. Just swallowing the error forces you to search for the problem manually.

**Comment by Phrohdoh** [comment]
I don't think crashing out is a good idea.
We could print out the errors to a UI pane similar to bogus Lua scripts.
