### ISSUE TITLE
[TS] AI is losing its path on the map....

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#8205]
https://github.com/LipkeGu/openra-replays/commit/a243d61001ff630ed0810716e6a8360f7ef7feb3

This attached Replay shows an problem what is mainly "crazy" ... for the CPU when the AI is trying to attack =(

pay attention to the situation when the AI tries to go for the first Attack.. (near the top-right of the Map)

Edit: it happends two times... :/

**Comment by Virtlink** [comment]
@LipkeGu The link to your replay is dead. Is this still an issue?

**Comment by pchote** [comment]
Replay is not available, so we can't do much more with this ticket.
