### ISSUE TITLE
Render performance significantly worse on some hardware

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#8213]
I doubt that OpenRA is at fault here (though SDL2 might be), but when it comes to Renderer performance, OpenRA performs over 2x slower on a GTX 960 with 352.84 drivers vs. a Radeon 7790 (last WHQL drivers).

Performance is far less consistent, too. Initially performance is normal, then ms per Render tick go up from ~5 to ~14ms for a short time-span, and over time these time-spans grow more frequent and longer until it's ~12-14ms/tick all the time (regardless of how much is going on on-screen, btw).
With my old Radeon 7790 I didn't have this performance issue, it breezed through at ~4-5ms all the time (latest release/bleed).

**Comment by chrisforbes** [comment]
Sounds like nVIDIA's bug to me.

**Comment by LipkeGu** [comment]
you should report this to nvidia =/

**Comment by Mailaender** [comment]
Closing as an upstream vendor problem.
