### ISSUE TITLE
What would it take to run on Android?

### ISSUE THREAD

**Issue by barrystaes** [OpenRA/OpenRA#8217]
I may well not be the only one that would like to play OpenRA on their Android device. :)
I was wondering .. what would we need to do to compile OpenRA as an Android app?

As an example i see the [OpenTTD Android port](https://github.com/pelya/openttd-android) by @pelya. OpenTTD also uses SDL2 and looks the same on Android except for some button padding. Not sure what else came at play.

Another port reference i found are the insights in this 4-part blog series by Julien Jorge:

- [Porting a C++ game to Android, the case of Andy's Super Great Park](http://blog.stuff-o-matic.com/post/2013/09/07/Porting-a-C-game-to-Android%2C-the-case-of-Andy-s-Super-Great-Park)
- [ASGP's Android Port Part II: from SDL 1.2 to SDL 2](http://blog.stuff-o-matic.com/post/2013/09/15/ASGP-s-Android-Port-Part-II%3A-from-SDL-1.2-to-SDL-2.)
- [http://blog.stuff-o-matic.com/post/2013/10/08/ASGP-s-Android-Port-Part-III%3A-from-OpenGL-Direct-Mode-to-GLES](http://blog.stuff-o-matic.com/post/2013/10/08/ASGP-s-Android-Port-Part-III%3A-from-OpenGL-Direct-Mode-to-GLES)
- [ASGP's Android Port Part IV: building the APK](http://blog.stuff-o-matic.com/post/2013/10/20/ASGP-s-Android-Port-Part-IV%3A-building-the-APK)

Now ofcourse OpenRA is not written in C++.. Would that be a show stopper? Any other problems that may need attention?

**Comment by pelya** [comment]
OpenTTD uses SDL1.2, not SDL2. I've looked at OpenRA a long time ago, but I
could not port C# code, as it depended on Windows stuff too much. I'm sure
there is C# for Android, but binding it to SDL is going to take a long time.

**Comment by Phrohdoh** [comment]
[Xamarin](https://store.xamarin.com/)'s pricing is one thing.
Another is more OpenGL (ES) specifics that I can't comment on.
@Mailaender, @chrisforbes.

**Comment by pelya** [comment]
Mmm, spamlink.

**Comment by Phrohdoh** [comment]
@pelya I'm not sure what you mean, that page is in no way spam.

**Comment by pelya** [comment]
Sorry, did not notice that you are talking about C# engine for Android.

You may as well use Unity, which is free for non-commercial use, and
supports C#.

**Comment by pchote** [comment]
There are a number of technical issues blocking this:

* Like @Phrohdoh mentioned above, xamarin charge for the android and iOS toolchains.
* The mobile platforms don't support JIT compilation, and so somebody would need to rewrite the network sync verification code.  It may also block reflection and dynamic libraries, which would completely rule out openra running there.
* The mobile platforms don't support OpenGL (only the ES versions), and so somebody would need to rewrite the rendering code and shaders.
* There are still a bunch of situations where performance becomes unbearably bad on normal computers.  Even if somebody were to resolve the above points it is unlikely to run well.

**Comment by Mailaender** [comment]
See also http://www.reddit.com/r/openra/comments/2w165v/openra_for_android/ We get that asked quite often on social media. We could even think of adding it to the https://github.com/OpenRA/OpenRA/wiki/FAQ

**Comment by berniek** [comment]
hehe reading about it would run slow.... well back in the day Red Alert ran pretty fine on my 486dx2 with 4MB RAM...
But yeah I admit OpenRA looks pretty great and it's a feat that you have come this far with it.
Good job guys.

**Comment by pchote** [comment]
Back in the day my bicycle had no problems riding down stairs... that doesn't mean that i'd want to try it with my car today!  One of our mods uses the same graphics as the original RA, but everything else is completely different.  It's not meaningful to compare the performance of the original games with ours :)

**Comment by Blackbird88** [comment]
>The mobile platforms don't support JIT compilation
You're wrong just saying. Android does support it. See any emulator.

**Comment by Ed-Fernando** [comment]
There have been interesting developments, from the Microsoft + Xamarin camp, in the past months. The Xamarin SDK has been [open sourced](http://open.xamarin.com/), Visual Studio 2015 has a free [**_Community_**](https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx) flavour for open source projects that incidentally also supports the entire Xamarin framework (albeit, limited to Windows & Mac OS X for development) and Microsoft has [released .NET Core 1.0](https://blogs.msdn.microsoft.com/dotnet/2016/06/27/announcing-net-core-1-0/) as the foundation of .NET for Windows, Mac OS X and Linux! I understand that the absence of Linux as a development platform, courtesy VS 2015, is a big let down (is definitely the case for me). My knowledge of C# is at a very elementary level and my understanding of the internals of OpenRA is zero. I'm a big fan of your work :alien: and understand how much of an effort it would be to go mobile. So, I merely wonder if these announcements bear any significance to the project with regards to mobile platforms?

**Comment by pelya** [comment]
For me Xamarin is not relevant to OpenRA, C# was available for Android for
quite some time (through Unity), Xamarin does not add anything new for game
development.
Last time I've checked two years ago, OpenRA used some Windows-specific C#
libraries, and could not be compiled on Linux.

On Tue, Jun 28, 2016 at 1:51 PM, Edilbert Fernando <notifications@github.com

**Comment by Phrohdoh** [comment]
OpenRA does not use Windows-specific libraries, else it wouldn't run on Linux and OS X.
Unity uses Xamarin tech to target mobile platforms.

**Comment by tarek369** [comment]
Ported for android https://github.com/tarek369/OpenRA
