### ISSUE TITLE
[Wiki] Explain how NEW Contributors can setup VS to always use tabs...

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#8218]
i had made 2 screens to show up how users can setup VS to use tabs...
maybe we could add these to the Style Guidelines wiki page :/

https://github.com/LipkeGu/Other-crap
##

**Comment by Mailaender** [comment]
Good idea. https://github.com/OpenRA/OpenRA/wiki/Coding-Standard may be the place.

**Comment by Phrohdoh** [comment]
:+1:

**Comment by LavenderMoon** [comment]
Adding explanations for how to set VS to use tabs and how to install StyleCop. Might include a tutorial on how to do an interactive Git rebase later on.

**Comment by Unit158** [comment]
This should be moved/copied onto the wiki todo list.

**Comment by aydjay** [comment]
This issue can be closed as the wiki now has this information.

https://github.com/OpenRA/OpenRA/wiki/Coding-Standard#set-visual-studio-to-use-tabs-instead-of-spaces
