### ISSUE TITLE
Dropping A-bombs on newest bleed looks weird

### ISSUE THREAD

**Issue by matija-hustic** [OpenRA/OpenRA#8238]
I didn't pay much attention before, but I think it just started doing it when I pulled bleed today after two days. Does it happen to anyone else with the newest bleed?

![untitled](https://cloud.githubusercontent.com/assets/5747153/7788557/c9e9061c-0237-11e5-9ac4-857cf9798505.png)

**Comment by obrakmann** [comment]
Yep, confirmed. Too bad you didn't open the issue 15 minutes sooner ;)

**Comment by pchote** [comment]
This was an oversight on my part in #8176.  Easily fixed.
