### ISSUE TITLE
ISpeedModifier does not work anymore

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#8260]
Both `TakeCover` and `ScaredyCat` are affected. Tested on RA and TS.

**Comment by penev92** [comment]
That *might* have something to do with my 2 warhead PRs (actually the first one).

**Comment by Mailaender** [comment]
Shall we revert them or do you want to fix it?

**Comment by penev92** [comment]
Turns out my changes had nothing to do with it. Still, I filed a fix.
