### ISSUE TITLE
Dune2k crash [playtest-20150524]: KeyNotFoundException

### ISSUE THREAD

**Issue by nuliukas** [OpenRA/OpenRA#8262]
Dune2k mod playtest-20150524 just crashed after an hour of playing in single player on Ubuntu 15.04. I am new here so I do not know what debug data I should provide. Exception.log reads:

> Dune 2000 Mod at Version playtest-20150524
> Operating System: Linux (Unix 4.1.0.40100)
> Runtime Version: Mono 3.2.8 (Debian 3.2.8+dfsg-4ubuntu4) CLR 4.0.30319.17020
> Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key was not present in the dictionary.
>  at System.Collections.Generic.Dictionary`2[OpenRA.Actor,System.Drawing.Rectangle].get_Item (OpenRA.Actor key) [0x00000] in <filename unknown>:0
>  at OpenRA.Primitives.SpatiallyPartitioned`1[OpenRA.Actor].Remove (OpenRA.Actor item) [0x00000] in <filename unknown>:0
>  at OpenRA.Traits.ScreenMap.Remove (OpenRA.Actor a) [0x00000] in <filename unknown>:0
>  at OpenRA.Mods.Common.Traits.Mobile.RemovedFromWorld (OpenRA.Actor self) [0x00000] in <filename unknown>:0
>  at OpenRA.World.Remove (OpenRA.Actor a) [0x00000] in <filename unknown>:0
>  at OpenRA.Actor+<ChangeOwner>c__AnonStorey1.<>m__0 (OpenRA.World w) [0x00000] in <filename unknown>:0
>  at OpenRA.World.Tick () [0x00000] in <filename unknown>:0
>  at OpenRA.Game.InnerLogicTick (OpenRA.Network.OrderManager orderManager) [0x00000] in <filename unknown>:0
>  at OpenRA.Game.LogicTick () [0x00000] in <filename unknown>:0
>  at OpenRA.Game.Loop () [0x00000] in <filename unknown>:0
>  at OpenRA.Game.Run () [0x00000] in <filename unknown>:0
>  at OpenRA.Program.Run (System.String[] args) [0x00000] in <filename unknown>:0
>  at OpenRA.Program.Main (System.String[] args) [0x00000] in <filename unknown>:0

**Comment by abcdefg30** [comment]
Do you have the replay from the crashed game?

**Comment by nuliukas** [comment]
Yes, you can find it here: https://www.dropbox.com/s/zgmf1uvfr0w82qz/OpenRA-2015-05-25T211025Z.orarep?dl=0

FFWD until around 59 min. I have no idea what triggered the crash.

**Comment by obrakmann** [comment]
Seems like it was a harvester.
![screenshot from 2015-05-26 12 11 10](https://cloud.githubusercontent.com/assets/4331210/7810223/75c21640-03a0-11e5-82e8-6841e26cdb0c.png)

**Comment by pchote** [comment]
My first guess is that something (probably related to the carryall code) is trying to move the harvester actor after it has been removed from the world.  It doesn't exist in the screenmap, and so that blows up when it tries to remove it a second time (as part of the position updating).

**Comment by obrakmann** [comment]
This is the sequence of additions/removals from world that lead to the crash:
```
Remove: PickupUnit
Add: DeliverUnit
Remove: PickupUnit
Remove: ChangeOwner
```

**Comment by pchote** [comment]
That looks to me like the deviator weapon triggering on the same tick that the harvester is picked up.  Adding an IsInWorld check to `TemporaryOwnerManager` should fix it.

**Comment by RoosterDragon** [comment]
#8268 looks like it will fix this issue, but there are a couple of other things we should probably consider:
- Should attempting to add an already added or remove an already removed actor from the world be made to throw an exception? That might catch some similar logic errors.
- ```SpatiallyPartitioned``` throwing in its Remove method helped surface this error, but really should it's signature be change to ```bool Remove(...)``` to match how most other collections deal with removals?
