### ISSUE TITLE
Bot destroy there own vehicles

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#8263]
Here some thing strange happen, the light tank start to shot the bridge beside it self and then destroy the bridge and itself and I get a unit lost sound even do i did not lose any units (looking at the images again I see that I lost the infantry).
![openra game_2015_05_26_01_28_50_209](https://cloud.githubusercontent.com/assets/7798635/7803410/e5785398-034e-11e5-8ba3-1042e2032a77.png)
![openra game_2015_05_26_01_29_24_171](https://cloud.githubusercontent.com/assets/7798635/7803412/ea993bf8-034e-11e5-8587-060f0a58871b.png)

**Comment by qiou** [comment]
Did you lose your infantry with the bridge ? On the second screen, there's no more infantry. Maybe it's the cause of the unit lost sound.

**Comment by pchote** [comment]
What mission is this?  I suspect that the player definitions aren't set up right, which causes the world actor owner to be set to the player.  This causes the bridge (plus all the trees etc) to be owned by the player, and means that the enemy will attack it.  The tank blowing up when the bridge dies is a known and very old bug with bridges.

**Comment by obrakmann** [comment]
It's gdi05b, and it's not `OwnsWorld`, but just the `Enemies` setup that's wrong. I'll send a fix.

**Comment by Snurre86** [comment]
Yes the infantry (e1) x5 next to the medium tanks just vanish. That may have cause of the unit lost sound. 

Also my only harvester died 3 cells from the bridge at my new play true to day.
![openra game_2015_05_27_00_37_17_705](https://cloud.githubusercontent.com/assets/7798635/7825219/906bf32a-040a-11e5-8009-4ba487791f30.png)
