### ISSUE TITLE
Crash at Allied mission 2 on may 2015 playtest

### ISSUE THREAD

**Issue by HenrytheSlav** [OpenRA/OpenRA#8266]
Red Alert Mod at Version playtest-20150524
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.Exception`: Actor type `e2` does not define a death animation for weapon with damage types `Prone50Percent, TriggerProne`!
   v OpenRA.Mods.Common.Traits.WithDeathAnimation.Killed(Actor self, AttackInfo e)
   v OpenRA.Traits.Health.InflictDamage(Actor self, Actor attacker, Int32 damage, DamageWarhead warhead, Boolean ignoreModifiers)
   v OpenRA.Traits.HealthExts.InflictDamage(Actor self, Actor attacker, Int32 damage, DamageWarhead warhead)
   v OpenRA.GameRules.DamageWarhead.DoImpact(Actor victim, Actor firedBy, IEnumerable`1 damageModifiers)
   v OpenRA.Mods.Common.Warheads.SpreadDamageWarhead.DoImpact(WPos pos, Actor firedBy, IEnumerable`1 damageModifiers)
   v OpenRA.GameRules.DamageWarhead.DoImpact(Target target, Actor firedBy, IEnumerable`1 damageModifiers)
   v OpenRA.GameRules.WeaponInfo.<Impact>c__AnonStorey2.<>m__0()
   v OpenRA.GameRules.WeaponInfo.Impact(Target target, Actor firedBy, IEnumerable`1 damageModifiers)
   v OpenRA.Mods.Common.Effects.Bullet.Explode(World world)
   v OpenRA.Mods.Common.Effects.Bullet.Tick(World world)
   v OpenRA.World.<Tick>m__4(IEffect e)
   v OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
   v OpenRA.World.Tick()
   v OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   v OpenRA.Game.LogicTick()
   v OpenRA.Game.Loop()
   v OpenRA.Game.Run()
   v OpenRA.Program.Run(String[] args)
   v OpenRA.Program.Main(String[] args)

**Comment by HenrytheSlav** [comment]
I am actually getting this also in level 1. I'll check skirmish.

**Comment by pchote** [comment]
This will crash whenever an infantry is killed by whatever weapon is triggering this.

We really need a lint rule to statically verify that we have fixed all of these errors.

**Comment by penev92** [comment]
A lint rule would be overkill for this oversight, but would be helpful for custom maps/mods and for us when defining new weapons.

**Comment by pchote** [comment]
Are you volunteering to manually check every weapon definition across our four mods to make sure that there aren't other missing cases? :)

**Comment by HenrytheSlav** [comment]
Me? Nah, I am just reporting this, I don't really understand C.

**Comment by pchote** [comment]
@HenrytheSlav: That was directed at @penev92 :)
