### ISSUE TITLE
LocalOffset doesn't work correct in TS viewing angle

### ISSUE THREAD

**Issue by DoGyAUT** [OpenRA/OpenRA#8274]
It looks like OpenRA doesn't use the right viewing angle for LocalOffset. I tested the same unit with the same settings in the RA mod - result was that the offset was 100% correct while in TS I got this result:
![localoffset](https://cloud.githubusercontent.com/assets/12551040/7843405/c5499b2a-04a9-11e5-9752-34a9b616878d.png)

**Comment by pchote** [comment]
It looks like the camera angle used for rendering the voxel is out of sync with the camera angle used for calculating the offset distortion.  Could you post the actor rules? It's possible that this has been misconfigured there.

**Comment by DoGyAUT** [comment]
GTMTNK:
	Inherits: ^Tank
	Valued:
		Cost: 500
	Tooltip:
		Name: Archon Tank
	Buildable:
		Queue: Vehicle
		BuildPaletteOrder: 10
		Prerequisites: ~gaweap, ~!t1
	Mobile:
		Speed: 56
		ROT: 5
		Crushes: wall, crate, infantry
	Health:
		HP: 400
	Armor:
		Type: Light
	RevealsShroud:
		Range: 6c0
	Turreted:
		ROT: 3
	Armament@PRIMARY:
		Weapon: 90mm
		LocalOffset: 900,0,500
		MuzzleSequence: muzzle
	AttackTurreted:
	AutoTarget:
	RenderSprites:
	RenderVoxels:
		NormalsPalette: RA2normals
	WithVoxelBody:
	WithVoxelTurret:
	WithMuzzleFlash:

In RA this works without problems.

**Comment by pchote** [comment]
The TS `^Tank` default overrides the camera pitch, which appears to support my theory about the angle mismatch between offsets and art.

**Comment by Phrohdoh** [comment]
This (probably for the same reason) hinders some progress in RA2.

**Comment by DoGyAUT** [comment]
Even if I use the default RA CameraPitch (113) the offset is still wrong calculated, with the same results. North faceings are too low and south facings are too high.

**Comment by penev92** [comment]
I think I may have a fix for this, but it will wreak havoc on the weapon offsets of every actor in every mod, so it might take a while to fix those for the official mods (which would most likely be a requirement for merging the fix into bleed).

**Comment by DoGyAUT** [comment]
Well penev's fix works without problems. Only drawback is that all actors have the get readjusted offset values but that is acceptable given the result:

![offset](https://cloud.githubusercontent.com/assets/12551040/8023429/9ebe51ce-0d0c-11e5-9485-80b58ff6d4b4.png)

They work flawless.

**Comment by penev92** [comment]
Apparently this causes more issues than it solves, though :(
I might need help.
