### ISSUE TITLE
Bridges that gets destroyed killes units that are more then 2 cells away from the bridge

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#8278]
Version Bleed:
Here you can see a bot destroying a bridge and then killing itself and 5x e1's (the e1's vanishes) in TD mod.
![openra game_2015_05_26_01_28_50_209](https://cloud.githubusercontent.com/assets/7798635/7855744/56d61558-0524-11e5-9d99-1fcbc8bc60f6.png)
![openra game_2015_05_26_01_29_24_171](https://cloud.githubusercontent.com/assets/7798635/7855751/5d7a8614-0524-11e5-9d66-9e20d25356aa.png)
Another Bleed_2015-05-29:
![openra game_2015_05_29_23_58_59_997](https://cloud.githubusercontent.com/assets/7798635/7894957/5d833a9a-0676-11e5-8ac5-a2715f33d415.png)

Here I destroy the bridge myself and my only harvester gets killed even if it is 3 cells away from the bridge cell.
![openra game_2015_05_27_00_37_17_705](https://cloud.githubusercontent.com/assets/7798635/7855753/62b7e356-0524-11e5-84c4-2c6fa1a97b81.png)

Version Playtest_2015-05-24:
![openra game_2015_05_28_15_24_05_495](https://cloud.githubusercontent.com/assets/7798635/7861053/1c2dc9da-054e-11e5-87a5-8c46e937786c.png)
##

**Comment by Snurre86** [comment]
Copy of cropped images:
![openra game_2015_05_26_01_28_50_209](https://cloud.githubusercontent.com/assets/7798635/7855542/d2157dfa-0522-11e5-9abe-da5feed9ea27.png)
![openra game_2015_05_26_01_29_24_171](https://cloud.githubusercontent.com/assets/7798635/7855561/fa916532-0522-11e5-9efa-8b41e2b40418.png)
![openra game_2015_05_27_00_37_17_705](https://cloud.githubusercontent.com/assets/7798635/7855629/7c6a6e6e-0523-11e5-8ca7-1eb43971423a.png)

**Comment by penev92** [comment]
Is this bleed, release or playtest?

**Comment by Snurre86** [comment]
Sorry forgot to mention the versions here is an update.

**Comment by Snurre86** [comment]
Still happens in TD in latest playtest.

**Comment by abcdefg30** [comment]
Fixed by  #15025.
