### ISSUE TITLE
Engineer dies and capture a building at the same time

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#8280]
Playtest_2015-05-24
Here is an image of me losing and capturing a barracks with the same engineer.
![openra game_2015_05_28_16_03_34_125](https://cloud.githubusercontent.com/assets/7798635/7862143/61f3dee0-0554-11e5-9b04-3f87e85d0912.png)
##

**Comment by pchote** [comment]
Looks like the EndFrameTask for spawning the death animation is missing an IsInWorld check.

**Comment by Snurre86** [comment]
Also the unit lost sound was triggered.

**Comment by Snurre86** [comment]
This is hard to reproduce so I might not be able to.

**Comment by Snurre86** [comment]
Have not been able to reproduce so I will close this until i am able to.
