### ISSUE TITLE
5a mission in TD preview

### ISSUE THREAD

**Issue by HenrytheSlav** [OpenRA/OpenRA#8287]
Hi guys, I am not able to help you with coding, so I will try and catch out and repair small bugs/irregularities in game. 

I played TD missions when I noticed that GDI 5a mission map has badly cut edges, so I used 4b map as alpha channel and cleared it up a bit.
![map](https://cloud.githubusercontent.com/assets/12610736/7884846/ea76163a-0620-11e5-852a-5c1511b2d7f9.png)
I am not sure where to put it so please, use it as you wish, you can discard it completely if you think its unimportant.

You can see improvement here.
![5a](https://cloud.githubusercontent.com/assets/12610736/7884881/14102e40-0621-11e5-8c33-2537cb98ee14.png)

Cheers

**Comment by Mailaender** [comment]
Thanks!
