### ISSUE TITLE
Intervention: losing MCV loaded in transport doesn't fail mission

### ISSUE THREAD

**Issue by MER-C** [OpenRA/OpenRA#8294]
Version: Playtest 20150524
Mission: Intervention (Red Alert)

Steps to reproduce:

1) Proceed normally by building a power plant, ore refinery, naval yard and transport.
2) Load the MCV into the transport.
3) Get the transport sunk while carrying the MCV by heading towards the turrets in the top left.

This should fail the mission but doesn't.

**Comment by pchote** [comment]
#8226 puts the framework in place to be able to fix this.  A subsequent PR will be able to add an actor disposed trigger, which will be called from all situations that cause an actor to be permanently removed from the world (dying, dying in a transport, selling, etc).

**Comment by matjaeck** [comment]
> This should fail the mission but doesn't.

Present in playtest-20180729.

**Comment by Smittytron** [comment]
> A subsequent PR will be able to add an actor disposed trigger, which will be called from all situations that cause an actor to be permanently removed from the world (dying, dying in a transport, selling, etc).

I believe the above is done now. Problem is an actor reference won't transfer on transformation, in this case MCV to Conyard and back.

**Comment by pchote** [comment]
the mcv disposed trigger could check the map for the presence of a construction yard, and attach a new trigger to that (and vice versa)? If a replacement isn't found, fail.
