### ISSUE TITLE
Game crashes when opened

### ISSUE THREAD

**Issue by Rowan94** [OpenRA/OpenRA#8314]
so i opened the game when i downloaded it and it worked fine then i got off then tried to open it an hour later and it loads the screen goes black then white and then crashes comes up with openRA has stopped working then a little box saying openRA closed from a fatel error view logs FAQ's and quit. i don't understand, so i restarted my computer and when i opened it when my com rebooted it worked again ???? then i got out of it went to work came back tried to open it a 2nd time crashed, i just tried to open it after a restart and it crashed please help!

**Comment by Unit158** [comment]
Can you please post the exception.log? Hit view logs when the game crashes, then post the contents of exception.log to a site such as pastebin.

**Comment by penev92** [comment]
Start by looking at the logs, as the crash dialog suggests. Then post exception.log here if needed.

**Comment by Rowan94** [comment]
thats the problem i go to view logs and that exception.log is not there

**Comment by Unit158** [comment]
Have you tried uninstalling and reinstalling OpenRA?

**Comment by Rowan94** [comment]
no i have not i will try that now

**Comment by Rowan94** [comment]
alright i have uninstalled it and reinstalled it but still crashes

**Comment by penev92** [comment]
What operating system are you using?
Is there *any* log that isn't empty?

**Comment by Rowan94** [comment]
Windows 7 64-bit
8gb ram
Intel duel core 3.20ghz
Intel HD graphics card 

and no their all empty

**Comment by Unit158** [comment]
This may be caused by a malfunctioning anti-virus in that case. Please add OpenRA as a false positive and try again :)

**Comment by Rowan94** [comment]
how do you open in a false positive

**Comment by Rowan94** [comment]
i have Norton 360 and i just turned the firewall off and it still crashed

**Comment by Rowan94** [comment]
i worked it out and it is fixed thanks guys for your help
