### ISSUE TITLE
"Sand Shores"

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#8317]
Currently in D2k, the worms can attack on tiles that are slightly covered by rock (transitioning from sand to rock). The animation not only looks really bad, but as there is rock, my first intuition is that the worm should not be able to attack there. Perhaps these tiles should be changed so that they are neither buildable nor shai-hulud territory?

**Comment by penev92** [comment]
I just checked the sandworm definition. It does not allow for movement on such tiles, which means those tiles have wrong terrain definitions.

**Comment by Mailaender** [comment]
Probably related to https://github.com/OpenRA/OpenRA/issues/4243 which also be addressed by tileset tweaks.
