### ISSUE TITLE
Ingame Map Editor : Forbid to place several actors on the same location

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#8323]
The ingame map editor allows to place several actors on the same location, resulting in having overlapping tanks for example.

While it could be interesting to have 3 or 5 infantry units at the same location, it doesn't make sense for tanks or other vehicles.. Maybe the sidebar could offer: 1 infantry unit, 3 infantry units and 5 infantry units to be placed?

http://logs.openra.net/?year=2015&month=05&day=31#16:34:06

**Comment by Mailaender** [comment]
I assume we don't want this following the discussion at https://github.com/OpenRA/OpenRA/pull/9138.
