### ISSUE TITLE
Fremen sometimes uses atreides engineer voice when selected

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#8324]
This was from content from CD (North American release).

**Comment by reaperrr** [comment]
d2k voices.yaml looks fine, and .aud files from our download content package sound as they should. Maybe an issue with the CD's assets.

**Comment by pchote** [comment]
Is this still a problem?  There have been a couple of recent PRs to fix d2k voices.

**Comment by Unit158** [comment]
I'll test it when the next playtest comes around.

On 2015-11-22, at 10:22 AM, Paul Chote <notifications@github.com<mailto:notifications@github.com>> wrote:


Is this still a problem? There have been a couple of recent PRs to fix d2k voices.

**Comment by pchote** [comment]
The current playtest should be sufficient for testing.

**Comment by abcdefg30** [comment]
#9674 ?

**Comment by penev92** [comment]
Should be fixed.
