### ISSUE TITLE
Grenadiers have no attack voice when trained as ordos (and possibly hark)

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#8326]

**Comment by reaperrr** [comment]
only grenadiers or other infantry as well?
There is no difference on yaml level (grenadiers use the default InfantryVoice), so this could be an Owner-related regression from #8012.

**Comment by Unit158** [comment]
Sardaukar and Fremen both preformed fine.

**Comment by reaperrr** [comment]
Fremen have their own faction-independent voice with owner prefix disabled. Sardaukar use GenericVoice which doesn't use prefixes for move and select, either.

Better testcases to check would be minigunners and vehicles.
According to my own test just now, it's broken for minigunners as well (probably all infantry using InfantryVoice).

**Comment by Unit158** [comment]
I'll have to re-test. It may be the same bug as my fremen issue.
