### ISSUE TITLE
Whole screen flickers especially in TS mod

### ISSUE THREAD

**Issue by wenzeslaus** [OpenRA/OpenRA#8340]
I'm trying the (awesome!) Tiberian Sun mod and the whole screen is flickering (in self-compiled OpenRA on Linux). In TS mod the whole screen (or map, it's hard to tell) flickers when in the main game menu (with the map in the background) and in the game itself. It looks like the color of the whole screen is changing to black.

I'm getting some flickering in RA mod too and even in the recent playtest. In the game, when I go to the menu (with Esc) unrevealed terrain appears for short periods of time. When I return to main menu I get the flickering again (black color appearing) but it seems that it is in longer period then in TS mod.

Noting is happening when I play in windowed mode but in fullscreen and pseudo-fullscreen, screen flickers.

I'm using Lubuntu 15.04 (Vivid Vervet) with LXDE desktop environment, Openbox windows-manager, LightDM display manager and the following configuration:

Graphics card info (`lspci | grep -i graphics`):

```
00:02.0 VGA compatible controller: Intel Corporation Core Processor Integrated Graphics Controller (rev 02)
```

CPU info (`cat /proc/cpuinfo | head -n 27`):

```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 37
model name      : Intel(R) Core(TM) i5 CPU       M 480  @ 2.67GHz
stepping        : 5
microcode       : 0x2
cpu MHz         : 1599.000
cache size      : 3072 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm pcid sse4_1 sse4_2 popcnt lahf_lm ida arat dtherm tpr_shadow vnmi flexpriority ept vpid
bugs            :
bogomips        : 5319.60
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:
```

OpenGL version (`glxinfo | grep "OpenGL"`):

```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ironlake Mobile 
OpenGL version string: 2.1 Mesa 10.5.2
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 10.5.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
```

Mono version (`mono --version`):

```
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    TLS:           __thread
    SIGSEGV:       altstack
    Notifications: epoll
    Architecture:  amd64
    Disabled:      none
    Misc:          softdebug 
    LLVM:          supported, not enabled.
    GC:            sgen
```

I see that the Mono version is quite old (Feb 2014), so I have tried the new one:

```
Mono JIT compiler version 4.0.1 (tarball Tue May 12 15:39:23 UTC 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    TLS:           __thread
    SIGSEGV:       altstack
    Notifications: epoll
    Architecture:  amd64
    Disabled:      none
    Misc:          softdebug 
    LLVM:          supported, not enabled.
    GC:            sgen
```

However, I get the same flickering in playtest. Now it is visible in the main menu right away without going to game first. I was not able to check bleed branch because with `make all` I get:

```
CSC fixheader.exe
error CS8001: Warning as Error: SDK path could not be resolved
Compilation failed: 1 error(s), 0 warnings
Makefile:257: recipe for target 'fixheader.exe' failed
make: *** [fixheader.exe] Error 1
```

This happens after successful `make dependencies` preceded by `make clean` (and `git clean -f`). It might be caused by some mess in the system due to the packages from external sources but I don't know.
##

**Comment by Phrohdoh** [comment]
Unfortunately I can't help debug this but I must thank you for the effort you put into an awesome bug report issue.

**Comment by LipkeGu** [comment]
Intel IGDs have some problems with OpenGL as far i know... for example the 950g series ... 
did you try another Kmod?

**Comment by wenzeslaus** [comment]
Sorry, I have do idea what do you mean by Kmod.

I'm using one other application which uses OpenGL and it works but I guess that these things can be pretty random.

**Comment by Mailaender** [comment]
I would try updating Mesa to the latest bug fix 10.5.6 release. Maybe you are lucky and it is already resolved. The 10.5 branch is marked as development release. You could also try downgrading to a slightly older, but more stable branch like 10.4

**Comment by Mailaender** [comment]
I am just guessing though. This is probably a case for @chrisforbes.

**Comment by chrisforbes** [comment]
@LipkeGu shouldn't be any problems with OpenRA on this chip. This is several generations on from the horrible 945/950.

**Comment by wenzeslaus** [comment]
I can't no longer reproduce it. Now tested on different computer with OpenGL 3.0 Mesa 17.0.7 on Ubuntu 16.04 (xenial). I suggest closing unless anybody else had the same issue.

```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 17.0.7
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 17.0.7
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 17.0.7
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

**Comment by abcdefg30** [comment]
Ok, good to hear the bug vanished for you.
