### ISSUE TITLE
[Render] Tooltips / Chatwindow is rendered every tick...

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#8347]
i noticed that the Batches are get kicked up when i press (ONLY) Enter (to write some things) but the Chatwindow is every tick the Same. When im closing the Window, the batches goes down.

The Same can be noticed on the Tooltip... hold a cursor over your units... tooltip shows up and batches goes also up... moving the cursor away tooltip-batches goes down...

it seems the engine is rendering things which are every ticks the same... :/

IDEA: we could render the tooltips / window only once and update it only when it changes...

**Comment by pchote** [comment]
The engine renders *everything* every tick – that's just how it works.  The UI could be rendered into its own framebuffer and then only redrawn when things change, but this would require a significant rewrite of both our widget and renderer systems.
