### ISSUE TITLE
Space RTS mod

### ISSUE THREAD

**Issue by x-a-n-a-x** [OpenRA/OpenRA#8355]
Please read this IRC log to know what this possible mod could be: 
http://logs.openra.net/?year=2015&month=05&day=26#18:27:26

***
Here is a list of possible things that this mod could feature (feel free to share your own ideas too):
- [ ] a space tileset (with stars and nebulas)
- [ ] animated planets
- [ ] animated asteroids
- [ ] animated gas clouds
- [ ] units and "buildings" for two factions (starships, starbases, factories, satellites, probes...)
- [ ] worm holes, black holes, spatial anomalies ...
- [ ] starship shields -- see https://github.com/OpenRA/OpenRA/issues/5777
- [ ] starships/buildings upgrades (new canons?)
- [ ] NPC pirates (third faction?)
- [ ] repair/attack drones (flying like bees around the ship)
- [ ] EMP bombs
- [ ] veteran units
- [ ] cloaked units (or maybe only for a short duration)
- [ ] solar power plant satellites 
- [ ] some units/buildings could need to be refuelled regularly to work properly (to keep their shield ON for example) -- see https://github.com/obrakmann/OpenRA/tree/fuel
- [ ] ships that can salvage wrecks
- [ ] crates (shield boosters, money, temporary enhanced ships speed, enhanced damages)
- [ ] damages that can affect starships : loss of an engine, of a weapon ...
- [ ] a starport could let the player hire mercenaries 
- [ ] escape crew capsules
- [ ] gravitational attraction ?
- [ ] edgeless maps ?
- [ ] some missions could take place on planets (with ground units/buildings)
- [ ] some missions could take place inside big ships (interior tileset)

**Inspiration:**
Starsector: http://www.ubuntuvibes.com/2012/02/starfarer-open-world-space-combat-and.html
Limit Theory: http://ltheory.com/ --- https://www.youtube.com/channel/UC4mchQbkE7ssZYXIgaY4PHg
Celestial Command: http://celestialcommand.com/
Interplanetary: http://interplanetary.weebly.com/
Distant Worlds: https://www.youtube.com/watch?v=kg9_wWR8LOk
Endless Space: https://www.youtube.com/channel/UChJbOHWpIGxpoEZKGYW4hmA
Shallow Space: http://shallow.space/
...

**Comment by WolfGaming** [comment]
Interesting...

**Comment by x-a-n-a-x** [comment]
Resources/Tools:

*nebulas* 
http://alexcpeterson.com/spacescape/
http://www.mainsequencesoftware.com/Gallery
http://opengameart.org/content/space-skyboxes-1

*asteroids*
http://opengameart.org/content/low-poly-rocks

**Comment by x-a-n-a-x** [comment]
Closing the issue to clear the Issues list (since this ticket will take months/years to be done, if it gets done).

**Comment by GraionDilach** [comment]
@OmegaBolt just started a space RTS project as his personal experiment on the other day though.

**Comment by OmegaBolt** [comment]
They sound like entirely different projects.

**Comment by Phrohdoh** [comment]
They are indeed entirely different but @x-a-n-a-x was right to close this for now.
Hopefully someone will see this ticket if they have an interest.

**Comment by Mailaender** [comment]
I think it is better to keep personal TODO list for thirdparty projects on other issue trackers.
