### ISSUE TITLE
Undisguised Spy can infiltrate buildings

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#8358]
The spy should be disguised to be able to infiltrate buildings.

**Comment by ScottNZ** [comment]
Why?

**Comment by MicroJOo** [comment]
uh , no

**Comment by Snurre86** [comment]
If turrents and units know can see him for what he is buildings should also.

**Comment by GraionDilach** [comment]
Infiltration should not rely upon disguise. If the player managed to get the infiltrator into the building without even a disguise, that's a moment of brilliance from the infiltrator's side and not something the game should punish.

**Comment by Phrohdoh** [comment]
Structures don't "see" who is infiltrating them (and couldn't do anything about it anyway) as they aren't sentient.

**Comment by deniz1a** [comment]
But they have infantry inside that get out when you sell the building? So wouldn't they resist infiltration if the spy is undisguised?

**Comment by cjshmyr** [comment]
Engineers don't need a disguise to enter buildings (TD/classic behavior) so I don't think this will fly.

**Comment by obrakmann** [comment]
I'm against this as well. :-1:

**Comment by Unit158** [comment]
:-1:

I am already bothered enough by the fact that they can no longer disguise as dogs.

**Comment by penev92** [comment]
Well, I think it's pretty much unanimous - #NotAnIssue.
