### ISSUE TITLE
Custom orders/scripts

### ISSUE THREAD

**Issue by StexoO** [OpenRA/OpenRA#8362]
It would be useful to be able to set some custom orders, like "Undeploy" -> MoveTo -> Deploy, when you select one of your construction yards, press one (user-defined) key and right click to some location.
And it could be enhanced like "Label" -> MoveToNextAdjacentCell -> ShootInRange -> "Goto Label" when you select some units, press another (user-defined) key and right-click on a location on the map.

**Comment by penev92** [comment]
Next after that is probably
start game -> press user-defined key -> watch the game play itself.

**Comment by Unit158** [comment]
I like the idea, but :-1: for having this as a default part of the engine. Orders are meant to be a code-level abstraction not seen by the user, and creating & managing them properly in a use case like this will probably be a pain.

**Comment by StexoO** [comment]
@penev92 no no no, the goal is to automate only the tasks you do repeatedly in specific situations, and only when you have to do them (and without missing any "frame" in the game when you do them because it would be automated). The game will never know when or where you want to move your construction yard, and if you don't react it will be destroyed.
For example, when you attack a base with a bunch of vehicles, you do your hit and run manually : A -> right-click -> A -> right-click -> A -> right-click ... (so the vehicles penetrate enemy defenses WHILE damaging everything, they always attack the units that are directly in front of them instead of continuing to fire on that building over there, they block production buildings, they leave husks in the base, and so on).
Long games are sometimes a little bit painful (damaged desk, burning mouse, ...)
On the other hand I don't think any RTS allows custom orders like this and there is probably a reason. oO

**Comment by pchote** [comment]
It would be a nightmare to implement a useable UI for this, and as you have said no other games support it (probably for exactly this reason).  Sorry, but this is not a realistic feature to include in OpenRA.
