### ISSUE TITLE
The death sound of the artillery and V2 is their firing sound

### ISSUE THREAD

**Issue by StexoO** [OpenRA/OpenRA#8367]
I don't know if it's intended or not but when you destroy an artillery or a V2 your hear its firing sound, not a sound played when you destroy a vehicle.

**Comment by StexoO** [comment]
I'm not sure for the artillery, I'll try to check that.

**Comment by epicelite** [comment]
I noticed this with V2 but never remembered to say anything! Thanks!

**Comment by StexoO** [comment]
Apparently only the V2 is concerned.
