### ISSUE TITLE
The difficulty level should show in the menu

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#8372]
It is strange that the difficulty level is not shown before you open the "pull down menu".
![openra game_2015_06_04_00_46_33_034](https://cloud.githubusercontent.com/assets/7798635/7973182/3d6a06f4-0a53-11e5-85c0-01daf49615ea.png)
![openra game_2015_06_04_00_46_26_780](https://cloud.githubusercontent.com/assets/7798635/7973189/47030ecc-0a53-11e5-98e2-d78b197d420e.png)
https://www.youtube.com/watch?v=RUrlddwGN1M&t=0m1s

**Comment by ushalin** [comment]
I have started working on this.
