### ISSUE TITLE
Changing the units stance should also stop its current action

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#8373]
https://www.youtube.com/watch?v=RUrlddwGN1M&t=7m
##

**Comment by penev92** [comment]
I totally disagree.

**Comment by Snurre86** [comment]
well the only way to get a tank from stop shooting a enemy building is "s", not even moving it away will it stop until the building is out of reach. In my opinion the game is getting more and more out of the reach or new players.

**Comment by pchote** [comment]
Changing stance should stop its current action *if that action is inconsistent with the new stance*.  It would be silly to cancel a move order, for example.

**Comment by Snurre86** [comment]
Should it stop the move order if the tank is chasing a unit and the stance is changed to "defend" ?
Will it be possible to differentiate between move and chase and would it be to complicated?

**Comment by Snurre86** [comment]
The same way a unit will immediately start firing on an enemy going from hold fire to attack it should stop firing going from attack to hold fire stance.

**Comment by matjaeck** [comment]
Another thing to note is that you can not stop an attacking unit when it is in attack anything stance and has a target in range. So you have to change the stance to stop it, unlike in all other stances where you have to issue a stop order to stop the attack.

**Comment by matjaeck** [comment]
Although it is just polishment, fixing this would have a very positive impact on the usage of stances. I hope this can be implemented as outlined in https://github.com/OpenRA/OpenRA/issues/8373#issuecomment-108766913 in the near future.

**Comment by pchote** [comment]
This should be a lot more feasible after all the activity work that has happened in the last 4 years.
Speculatively adding to the milestone.

**Comment by matjaeck** [comment]
This looks quite complicated to solve in my unexperienced eyes and should not block the release. Several things need to be taken into account:
- we can not just cancel the current activity, as we don't want to cancel moving
- units must still be able to attack on explicit order
- units should stop aiming at targets

**Comment by pchote** [comment]
The simplest way to handle this is to add an `OnStanceChange` method to the base activity class. The attack activities can then override this to check the old and new stance and cancel themselves if the current target is no longer compatible.
