### ISSUE TITLE
D2K turret build animations are missing.

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#8378]

**Comment by Mailaender** [comment]
We could re-use the silo crumble animation here. The reason I didn't do that in the past was that the turret Z-Offset and appearance was glitchy. May be easy to solve though.

**Comment by MustaphaTR** [comment]
Duplicate of #6578

Orginal Turret Build Anim is same as silo's one.

**Comment by penev92** [comment]
Closing as duplicate.
