### ISSUE TITLE
Selectable boolean on Selectable trait is confusing

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#8381]
We should either try to remove it, or rename it and add a description to make it more clear why and for what it is needed.

**Comment by Phrohdoh** [comment]
AFAIK its removal is planned.

**Comment by Unit158** [comment]
The only reason why the boolean exists is because we still don't have properly functioning oraml removals.

**Comment by reaperrr** [comment]
The only case I came across so far that seems to require it are TD/RA ```BridgeHut```s. They seem to need the trait's ```Bounds``` to be targetable by C4/Engineers, since they don't have art and ```AutoSelectionSize``` therefore doesn't work on them.

**Comment by reaperrr** [comment]
^
I was right. I just tested it, if you give the bridge huts an empty SHP matching their dimensions and ```RenderSimple``` (+ ```BodyOrientation```), the ```Selectable``` trait isn't needed at all.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/issues/8086 isn't really a blocker as you can avoid the inherited negating easily and simplify the yaml rules again once it is fixed. We just need a upgrade rule here and remove this legacy workaround.

**Comment by reaperrr** [comment]
Closed via  #8388.
