### ISSUE TITLE
Jittery game play

### ISSUE THREAD

**Issue by MrDrizz** [OpenRA/OpenRA#8384]
I get jittery game play after I've been playing for a while. I'm on Ubuntu-MATE 15.04.
video demo https://www.youtube.com/watch?v=WGkGbKDsIeQ
The issue happens even in the latest version.

I don't get this in the Windows version.

**Comment by abcdefg30** [comment]
Could you enable "Show Performance Graph" (Settings -> Advanced) and post a picture of it, please?
Also: On which maps does that happen, or occurs this on all maps?

**Comment by Unit158** [comment]
Perhaps even more importantly, are you running the game on the same hardware as the windows version?

**Comment by MrDrizz** [comment]
Unit158, Yes it is the same hardware. 

Very odd this, I've enabled debug and performance graph and the issue hasn't re-surfaced the couple times I played.

abcdefg30, yes on all maps that are skirmishable

**Comment by RoosterDragon** [comment]
Your video makes me think this is the same issue as #4584. You can see the lag spike in their perf graph of something trying to do pathfinding every second.

**Comment by Mailaender** [comment]
Does updating http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives help?
