### ISSUE TITLE
OpenRA won't start

### ISSUE THREAD

**Issue by BoxHeaD78** [OpenRA/OpenRA#8386]
When I try to start OpenRA it happens nothing. I just can see "OpenRA.exe" and "OpenRA.Game.exe" in the Task-Manager but it happens nothing.
I'm using the OpenRA release-20150424.

**Comment by Unit158** [comment]
Are you running an anti-virus?

**Comment by BoxHeaD78** [comment]
Thank you for the fast answer.
I disabled my anti-virus. Still nothing.

**Comment by penev92** [comment]
Anything happening in any of the logs?
Does the game show up in your task bar?

**Comment by BoxHeaD78** [comment]
The game doesn't show up in my task bar and I have nothing in the logs.

**Comment by BoxHeaD78** [comment]
Ahh now it works.
I deleted the OpenRA folder in the documents.
