### ISSUE TITLE
Mission objectives should show difficulty level

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#8396]
What difficulty level am I playing here?
![openra game_2015_06_06_12_59_17_141](https://cloud.githubusercontent.com/assets/7798635/8019389/e8e04e7c-0c4b-11e5-8dc8-23c760cf367d.png)
##

**Comment by Snurre86** [comment]
Is this easy?

**Comment by Smittytron** [comment]
This would fit well with a general information/rules tab suggested in #12349
