### ISSUE TITLE
Dedicated requires libgdiplus

### ISSUE THREAD

**Issue by moviuro** [OpenRA/OpenRA#8403]
That is a bug, as pointed out by @pchote on IRC.
See http://ix.io/iXm

**Comment by pchote** [comment]
This is really a mono bug.  Mono pulls in this dll whenever we access anything from System.Drawing even if we don't need it.  We will need to remove all references to that namespace from the server code to avoid this on our end.

**Comment by pchote** [comment]
There's not much we can do to solve this (except petitioning upstream), so closing.
