### ISSUE TITLE
Make some mandatory things POSIX-compliant

### ISSUE THREAD

**Issue by moviuro** [OpenRA/OpenRA#8406]
See #8405 : The scripts needed to build and run the server (dedicated) on FreeBSD have been updated to be POSIX compliant.
The rest should, too.
The makefile should be modified to allow FreeBSD (```uname -s``` returns ```FreeBSD```) and the fetch dependencies & configure dependencies scripts for Linux work for FreeBSD too, now that they are POSIX.

**Comment by obrakmann** [comment]
Fixed in #8405.

**Comment by Mailaender** [comment]
I didn't know so few was required to make it work. Filed https://github.com/OpenRA/OpenRA/pull/8408.
