### ISSUE TITLE
Maps with custom rules slow down game start

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#8407]
http://resource.openra.net/maps/3149 seems to be a good worse case scenario.

**Comment by penev92** [comment]
I've said this before: lua bindings slow things down.
We also reveal the world to the player before it is fully initialized (lua bindings just highlight that), which causes really frustrating lag at the beginning.

**Comment by pchote** [comment]
My recent map overhaul has completely changed the way custom rules are loaded.  This has either been fixed, or is now unfixable.
