### ISSUE TITLE
Soviet mission 5 coversion

### ISSUE THREAD

**Issue by HenrytheSlav** [OpenRA/OpenRA#8414]
Hello guys! I started with conversion of the Soviet 5th mission from the original campaign, however after recreating map and actors, I seem to be unable to do the scripting. I knew how to do it in RAED, but Lua is just too confusing for me, sorry. To complete it, I either need someone willing to do it or someone willing to answer my (probably dumb) questions. I did look at the wiki and all the tutorials, but for example I couldn't force the three guys at the start to even move. I tried to do ActorName.ScriptedMove (x,y), ActorName.ScriptedMove (waypointname.Location), and so on, but it never worked, log said he can't convert 0 to CPos. I tried to define CPos by using waypoint or raw coordinates, but in vain.

I can send you the files if you tell me where,I cut the crashing lua from it.

**Comment by Mailaender** [comment]
Join the chat via http://www.openra.net/community/ and be sure to post your code somewhere like https://gist.github.com/ so we can help you.
