### ISSUE TITLE
Add an argument to set game folder

### ISSUE THREAD

**Issue by moviuro** [OpenRA/OpenRA#8419]
I'm in the process of writing a rc.d script for FreeBSD, but I notice weird behaviors. I believe an argument explicitly setting the workdir would fix the issues I'm facing.
E.g.

```
mono --debug /home/openra/OpenRA/OpenRA.Game.exe OpenRA.Home=/home/openra
```

So that logs will go in  `/home/openra/.openra`
##

**Comment by abcdefg30** [comment]
We do have a `Engine.SupportDir` launch argument now.
