### ISSUE TITLE
Using alternate palettes for actor icons.

### ISSUE THREAD

**Issue by scskwirl** [OpenRA/OpenRA#8434]
There is a hard-coded chrome palette that runs the icons.

When using assets between mods, there is no current method to override this and read from another palette to keep the correct color.

Use a trait inside Buildable: for each item that will need the effect?

**Comment by Phrohdoh** [comment]
I can't find a hard-coded palette anywhere for production icons.

**Comment by GraionDilach** [comment]
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Widgets/WidgetUtils.cs#L30 sounds like such to me.
