### ISSUE TITLE
[Map Editor] One Click Forest painting

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#8436]
In Finalsun it was able to paint a forest with trees. it switches the trees when they  are placed. we could also implementig such thing.

the Creater cklics a button "paint forest" and the Editor selects 4 random trees and paint a forest with these selected trees on the map. instead of selecting every tree as its own :(

**Comment by pchote** [comment]
Sounds reasonable.  This could be easily implemented using a custom editor brush that parses a special grouping trait on the actors.

**Comment by LipkeGu** [comment]
#10652

**Comment by pchote** [comment]
Reverse duplicate of #10655.
