### ISSUE TITLE
Choose starting sound by type of Map

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#8437]
i noticed on our official shellmap, that the music begins to play right after game start.
when i save my map as shellmap and she gets loaded after game start only an "battlefield control..." sound is played.

an idea would be to select the sound by the type of the map

* shellmap = main menu music / scripted sound
* regulary = battlefield control...

**Comment by GraionDilach** [comment]
The music is set up in the LUA script (also being less restrictive there). I don't see the benefit of this over that..

**Comment by Mailaender** [comment]
Yes, we don't want that hard-coded. See the map.yaml and map.lua of our existing shellmaps.
