### ISSUE TITLE
Harvester logic makes this mission unplayable, AI can't harvest.

### ISSUE THREAD

**Issue by HenrytheSlav** [OpenRA/OpenRA#8446]
Ok, so this is making my conversion undoable. Technically, I could make little trace of ore to the base so it would be closer than the ore on the island, but this is just hiding the problem and it looks damn stupid. Also, if a new harv is produced, it gets stuck right away. And there could be other missions with even worse scenarios. So the harvester logic needs to be adapted to deal with this/new command has to be made to force the AI harvester to mine from a specific field. :)

![bez nazvu](https://cloud.githubusercontent.com/assets/12610736/8045272/6bd2557c-0e32-11e5-8f8f-00feafbf6e76.png)

**Comment by obrakmann** [comment]
Please post your map and lua script somewhere to make debugging this easier.

**Comment by pchote** [comment]
We should provide a lua function for harvesting a specific cell in any case.

**Comment by HenrytheSlav** [comment]
https://drive.google.com/file/d/0B8k1mGfwPlwzbVNLQzVNTkZTWEU/view?usp=sharing

**Comment by abcdefg30** [comment]
This doesn't look like a scripting problem to me. If I build my own refinery up there (refinery location from the screenshot), the spawned harvester moves at the cost and idles there.

**Comment by penev92** [comment]
That seems logical, considering our pathfinding issues. The question here is how do we trick this particular harvester in this mission to work.

**Comment by Mailaender** [comment]
Seems to be fixed by https://github.com/OpenRA/OpenRA/pull/8622.
