### ISSUE TITLE
Add option to disable naval yard/sub pen in lobby.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#8450]
So I can play on more maps without it quickly divulging into spam subs/ships ASAP and gg.

**Comment by penev92** [comment]
The only feasable way that can be done is by having game modes - all infantry, all naval, all land, etc. But even so, I don't see it happening.

**Comment by Phrohdoh** [comment]
:-1: should we disable mcvs next so it doesn't become RTS spam?

**Comment by Mailaender** [comment]
You can solve this by defining tech levels. Disabling a whole build queue just because you made a bad experience is definitely nothing for the official mods.

**Comment by GraionDilach** [comment]
Main issue with the techlevel dropdown list is that it is a dropdown list... you can have only one of them selected at a time, so combining them would need dozens of entries - while you could just use said dropdown list to list major gamemodes.

I'd definitely like to see a feature of defining additional checkboxes with their own yaml overrides (like how CnCNet5 client did theirs at http://media.moddb.com/images/mods/1/11/10865/go.png - you pick a checkbox and it's respected rules gets parsed after main, but before maps' entries are read).

I do agree with the rejection of the OP idea, however.
