### ISSUE TITLE
ingame editor: use full screen height for tile window

### ISSUE THREAD

**Issue by clemty** [OpenRA/OpenRA#8451]
currently the ingame editor window only uses a small area of the available screen estate, and requires the user to scroll through the list to find a tile

editing would be easier if the tile window stretched all the way down to the bottom of the screen, or if the window auto-resized for tabs where there are only few options (e.g. 'overlays')

![editor](https://cloud.githubusercontent.com/assets/10729559/8067003/2965e726-0eeb-11e5-95b1-11ca2d86d5ae.png)

**Comment by aydjay** [comment]
Would be nice to leave the default height but allow the user to drag the
height that they want.

**Comment by clemty** [comment]
I don't think OpenRA suppports resizable windows/widgets
