### ISSUE TITLE
Random connection problems on dedicated servers

### ISSUE THREAD

**Issue by BoxHeaD78** [OpenRA/OpenRA#8454]
Hello,
I got a annoying Problem with my dedicated Server.
My problem is that nobody can connect to the server, if there is only 1 player slot available.
For example if I have a 2 player map and there is 1 player in the lobby nobody is able to connect to the server.
If I have a 8 player map and there are 7 players in the lobby is nobody able to connect to the server.
So the last slot can't be filled.

**Comment by Mailaender** [comment]
Which version are you running?

**Comment by BoxHeaD78** [comment]
Im running on the version "release-20150424"

**Comment by Mailaender** [comment]
Does it also happen on playtest-20150531?

**Comment by BoxHeaD78** [comment]
I have to try it with the other version. 
I found out that the problem is happening randomly. Some people can connect to the server and other can't connect. So the problem does not only occur when the server is waiting for 1 guy.

**Comment by BoxHeaD78** [comment]
It seems that the problem does not occur in the version "playtest-20150531".
I played several matches without problems.

**Comment by Mailaender** [comment]
Closing as fixed than. We are also about to release a new stable version. https://github.com/OpenRA/OpenRAWeb/pull/227
