### ISSUE TITLE
Ingame keyboard shortcuts are broken

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#8456]
* Player sidebar has the same shortcuts for all top buttons except diplomacy. They all show Esc. When Esc is pressed, options menu opens.
* In observer sidebar, pressing Esc switches shroud selector to "All Players" view and doesn't open options menu.
* In map editor, pressing Esc changes zoom levels and doesn't open options menu.

**Comment by penev92** [comment]
Bleed?

**Comment by deniz1a** [comment]
Bleed and release... So keyboard shortcuts are not working in latest release, how was that not noticed...

**Comment by penev92** [comment]
Couldn't reproduce any of the mentioned problems on bleed. My bet is you messed up your hotkeys while working on the text field PR.

**Comment by deniz1a** [comment]
ahahah oh right...
