### ISSUE TITLE
Parachuters are killable by placing a building under them

### ISSUE THREAD

**Issue by HenrytheSlav** [OpenRA/OpenRA#8458]
Hi guys, this would probably also work with another actors under the parachuters. Basically, for some time before landing and after their jump from the plane you can still place buildings under them. On the screen you can see a squashed troop near the soviet barracks flag.

![bez nazvu](https://cloud.githubusercontent.com/assets/12610736/8079902/1adf206e-0f68-11e5-866d-4f9c0e870b6b.png)

**Comment by pchote** [comment]
This is intentional behaviour.

**Comment by pchote** [comment]
#8339 may change this.

**Comment by HenrytheSlav** [comment]
Oh, sorry then :)
