### ISSUE TITLE
Chat cursor is not aligned in lobby

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#8459]
It looks like this on bleed:
![lobby_chat](https://cloud.githubusercontent.com/assets/6599106/8097983/5e9d54b2-0ff2-11e5-9584-bc9ad3bd56d8.png)

**Comment by penev92** [comment]
I'm on a 3-day old bleed and it's OK:
![](http://i.imgur.com/xj1MNM4.png)
So whatever it is, it's new.

**Comment by Mailaender** [comment]
My fault. Sorry. Will be fixed by https://github.com/OpenRA/OpenRA/issues/8469.
