### ISSUE TITLE
Cell selection on diamond (iso) perspective broken again

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#8463]
Horizontal axis is fine, but vertically it is off by a half cell. Moving the cursor on the lower half of a cell selects the cell below (easy to see when using the terrain geometry debug overlay in TS).

**Comment by pchote** [comment]
Can you bisect to find what regressed this?

**Comment by reaperrr** [comment]
Finally found the time to track this down.

This seems to have been (re-)introduced by #7847.

**Comment by pchote** [comment]
This was actually introduced by #7748.  I've found the problem, but need to sit down and work out the correct maths for the fix.
