### ISSUE TITLE
Intermittent freezing in AI matches with >6 players

### ISSUE THREAD

**Issue by hxazgalor** [OpenRA/OpenRA#8466]
![open-ra_1](https://cloud.githubusercontent.com/assets/12862476/8133435/e89aedd2-115a-11e5-9400-a154fe89b588.jpg)

I have game slowdowns on maps with more than 4 players, but the problem is more prevalent with 6 or more in a map. Every 1-2 seconds the game will freeze for about 1-1.5 seconds before unfreezing, after which it freezes again and the process repeats itself.

I'm running a HP Pavilion g4 laptop, with a Intel Core i5-3210M CPU, 4GBs of RAM, and a Radeon HD 7670M with integrated Intel HD Graphics 4000 as my graphics card.

Please do advise, thank you.

**Comment by RoosterDragon** [comment]
Possibly the same as #8384 and/or #4584.

**Comment by penev92** [comment]
This doesn't seem to be the pathfinding though. 
Unfortunately the AI tends to be pretty bad performance-wise, especially if you cripple it, thus limiting its options.

**Comment by hxazgalor** [comment]
It starts acting this way once battles get hectic. Even when it winds down to the endgame, the freezing still persists.

This is more prevalent in Dune 2000, where even in a 4v4 this kind of freezing will happen sooner or later.

**Comment by reaperrr** [comment]
D2k usually has less buildable area, so I suspect that this is caused by the AI base builder. It tries to find space for something, fails, tries again, fails etc.

**Comment by hxazgalor** [comment]
At the moment, is there a solution to this (other than keeping matches small), or is it still being worked on by the devs?
