### ISSUE TITLE
Destroyers unable to do damage under fog of war

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#8476]
Here is a video. https://www.youtube.com/watch?v=LGCuNfjkBpc

here is the replay watch with newest release 2015-04-24 - Time in replay 19:19
http://s000.tinyupload.com/?file_id=16775446299068524813

**Comment by penev92** [comment]
Everything in that video is so tiny I can't see the power plant's health bar, but it looks like three destroyers take a while to destroy a building that is being repaired. I can't see the problem.

**Comment by Snurre86** [comment]
If you care the video show that the destroyers do extremely low damage to the building when it is under the fog and destroys the building as soon as i move one of them closer to reveal the fog over the building. What do you want me to do about your problem with the video?

**Comment by AoAGeneral** [comment]
I didn't see any destroyes in your posted replay. But in the video itself its not fog of war causing the issue its a ballistics issue. This is common in TD as well.

Take a look at your destroyer when its hitting its mark. The missile is hitting directly onto the target perfectly. Now take a look when the boats move and they are all shooting. Two of them are off centered from hitting the target which is 'missing' and not striking the target. While only one is hitting the mark each time.
