### ISSUE TITLE
Missing dependency mono(ICSharpCode.SharpZipLib) on Fedora 22

### ISSUE THREAD

**Issue by PanzerFurrry** [OpenRA/OpenRA#8486]
Release-20150614 fails to install on Fedora 22 due to dependency problems.

Steps to reproduce:

Download Package for Fedora 21 'openra-20150614-1.1.noarch.rpm' from OBS http://software.opensuse.org/download.html?project=games:openra&package=openra as instructed from official page http://www.openra.net/download/ .

"dnf install openra-20150614-1.1.noarch.rpm" returns error due to dependency issue.

```
dnf install openra-20150614-1.1.noarch.rpm
Last metadata expiration check performed 2:51:01 ago on Mon Jun 15 07:10:19 2015.
Error: nothing provides mono(ICSharpCode.SharpZipLib) = 0.86.0.518 needed by openra-20150614-1.1.noarch
```
```
mono --version
Mono JIT compiler version 4.0.1 (tarball Thu May 28 04:56:48 EDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
```
```
Linux CENTURION 4.0.4-303.fc22.x86_64 #1 SMP Thu May 28 12:37:06 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Mailaender** [comment]
Try adding the repository as instructed:

> cd /etc/yum.repos.d/
> wget http://download.opensuse.org/repositories/games:openra/Fedora_21/games:openra.repo
> yum install openra

**Comment by Mailaender** [comment]
It will then automatically install the dependencies such as https://build.opensuse.org/package/show/games:openra/sharpziplib

**Comment by davidstrauss** [comment]
The repository URL is now (and the old link doesn't work): `http://download.opensuse.org/repositories/games:/openra/Fedora_23/games:openra.repo`

**Comment by Mailaender** [comment]
I fixed the URL mentioning yum in https://github.com/openSUSE/software-o-o/pull/76 and kept all dependencies bundled https://build.opensuse.org/package/show/games:openra/release to simplify distribution.
