### ISSUE TITLE
RA - Soviets have Helipads on Desert Shellmap

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#8487]
Possibly they are not visible during shellmap is playing but there are 3 Helipads owned by Soviets you can see on editor. Normally Soviets are unable to build helipads. I looked to Lua and they are not used. So i don't see any problem to remove them. I think they was buildable by soviets before like orginal RA and you forgot to remove them on Shellmap.

**Comment by ScottNZ** [comment]
The Soviet helipads were intentional.

**Comment by abcdefg30** [comment]
So, keep them?
