### ISSUE TITLE
Vehicle turrets are not aligned with vehicle bodies after loading a map

### ISSUE THREAD

**Issue by ScottNZ** [OpenRA/OpenRA#8489]
![turret](https://cloud.githubusercontent.com/assets/1712619/8158294/fb6a26ba-13af-11e5-95cc-32295496f921.png)
##

**Comment by HenrytheSlav** [comment]
I guess the only reason why that is an issue is that the utility converts rotations a bit wrong and it saves different turret/body rotations. Maybe it would be good to look here.

**Comment by matjaeck** [comment]
The RA shellmap of playtest-20180729 does not show this issue anymore.
