### ISSUE TITLE
New Release 20150614 wont load 

### ISSUE THREAD

**Issue by ugotbroiled** [OpenRA/OpenRA#8492]
Using Mac OS 10.9.5 the new release gets stuck opening on the black screen just after opening the application.  
![screen shot 2015-06-15 at 3 49 56 pm](https://cloud.githubusercontent.com/assets/12901045/8169233/42208c78-1376-11e5-9b50-8b9a92748936.png)

**Comment by ugotbroiled** [comment]
Downloaded the newest version of Mono MRE and still having the same issue.

**Comment by pchote** [comment]
This is a mono bug: mono freezes before it even touches the OpenRA code while it reindexes all the fonts on your machine (despite the fact that we don't need or want them).  Give it a few minutes, and it will start working again.  It will only need to do this once each time after you upgrade mono.

**Comment by ugotbroiled** [comment]
Thank you!
