### ISSUE TITLE
DllNotFoundException: Unable to load DLL 'freetype6.dll'

### ISSUE THREAD

**Issue by RedAlert2** [OpenRA/OpenRA#8493]
Just installed the 20150614 release, but could not launch it.

From exception.log:
Inner Exception of type `System.DllNotFoundException`: Unable to load DLL 'freetype6.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

The file 'freetype6.dll' is in the OpenRA.exe directory.
OS: Windows 7

**Comment by penev92** [comment]
Please make sure you have Microsoft Visual C++ 2010 Redistributable or later.

**Comment by RedAlert2** [comment]
Thanks. Installed Microsoft Visual C++ 2010 Redistributable and it is now working perfectly.

**Comment by Mailaender** [comment]
I intend to bring back the check during setup: https://github.com/OpenRA/OpenRA/pull/7609 as there seem to be Windows 7 systems in the wild that don't have the 2010 version installed. See also https://github.com/OpenRA/OpenRA/pull/8360.

**Comment by GraionDilach** [comment]
:+1: for bringing in such a check... there's even a report of this by a guest on the ModDB profile who fixed it via getting a version from sourceforge...?

**Comment by Mailaender** [comment]
You can test https://ci.appveyor.com/project/OpenRA/openra/build/1.0.3936/artifacts and give your thumps up at https://github.com/OpenRA/OpenRA/pull/7609.

**Comment by Mailaender** [comment]
Added FAQ entry ([diff](https://github.com/OpenRA/OpenRA/wiki/FAQ/_compare/ea6343f9c1baaf039c6453a258994646043f405f...74811b1a9400ca68cadb395f454393756864e45f)) as this is going to be a problem. Failed to do the check at install time. https://github.com/OpenRA/OpenRA/issues/7609 We may want to do the check on game start instead which gives us more flexibility.

**Comment by RedAlert2** [comment]
Was installing OpenRA on another machine, did a search for the C++ package but a slightly different link came up, turns out there are 4 different package available for download:

Microsoft Visual C++ 2010 Redistributable Package (x86)
Date Published: 4/12/2010
https://www.microsoft.com/en-us/download/details.aspx?id=5555

Microsoft Visual C++ 2010 Redistributable Package (x64) 
Date Published: 4/12/2010
https://www.microsoft.com/en-us/download/details.aspx?id=14632

Microsoft Visual C++ 2010 SP1 Redistributable Package (x86) 
Date Published: 3/3/2011
https://www.microsoft.com/en-us/download/details.aspx?id=8328

Microsoft Visual C++ 2010 SP1 Redistributable Package (x64) 
Date Published: 3/3/2011
https://www.microsoft.com/en-us/download/details.aspx?id=13523

I am wondering if there are any performance difference between them?

**Comment by Mailaender** [comment]
We only support the x86 one. Windows will probably auto-update to SP1 once you install https://www.microsoft.com/en-us/download/details.aspx?id=5555

**Comment by RedAlert2** [comment]
I see, thanks!

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/8983 could solve this.
