### ISSUE TITLE
Crashes when MapEditor + Zoom 0.5 + right click

### ISSUE THREAD

**Issue by joemaro** [OpenRA/OpenRA#8495]
release 20150614
win7 64
using hardware cursors

Here is exception log file:

Red Alert Mod at Version release-20150614
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.34209
Exception of type `System.IndexOutOfRangeException`: Der Index war außerhalb des Arraybereichs.
   bei OpenRA.CellLayer`1.get_Item(CPos cell)
   bei OpenRA.Mods.Common.Widgets.EditorDefaultBrush.HandleMouseInput(MouseInput mi)
   bei OpenRA.Mods.Common.Widgets.EditorViewportControllerWidget.HandleMouseInput(MouseInput mi)
   bei OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   bei OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   bei OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   bei OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   bei OpenRA.Widgets.Widget.HandleMouseInputOuter(MouseInput mi)
   bei OpenRA.Widgets.Ui.HandleInput(MouseInput mi)
   bei OpenRA.DefaultInputHandler.<OnMouseInput>c__AnonStorey2.<>m__0()
   bei OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   bei OpenRA.DefaultInputHandler.OnMouseInput(MouseInput input)
   bei OpenRA.Renderer.Sdl2.Sdl2Input.PumpInput(IInputHandler inputHandler)
   bei OpenRA.Renderer.Sdl2.Sdl2GraphicsDevice.PumpInput(IInputHandler inputHandler)
   bei OpenRA.Graphics.Renderer.EndFrame(IInputHandler inputHandler)
   bei OpenRA.Game.RenderTick()
   bei OpenRA.Game.Loop()
   bei OpenRA.Game.Run()
   bei OpenRA.Program.Run(String[] args)
   bei OpenRA.Program.Main(String[] args)

**Comment by pchote** [comment]
Thanks for the report!  This was fixed by #8430, which will be included in the next playtest.
