### ISSUE TITLE
D2K - Outpost offset is wrong

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#8504]
Comparison;
![radar offset](https://cloud.githubusercontent.com/assets/7933210/8233550/24287ce0-15d7-11e5-956f-c13b734c44eb.png)

**Comment by penev92** [comment]
OK, we should consider if we want to change that:
 - The original (like C&C games at the time) had to have bibs on buildings to provide units with a way to move around the base (somewhat applicable in our case, but not too much).
 - The artwork matches a 3x3 structure better than a 3x2 one, IMO.

**Comment by pchote** [comment]
If we're going on opinions, I think the original looks better.

**Comment by HenrytheSlav** [comment]
I'd go for original because base clogging.
