### ISSUE TITLE
Ingame Map Editor - Editor fails to find palette in Map file.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#8507]
I have a Tech Power Plant on my map uses CnC template palette on RA mod. They are placed on map but if i open map on editor game crashes and log says Palette `cnc` does not exist. Palette file is in .oramap archive and works when playing. But editor crashes.

**Comment by pchote** [comment]
Please share the map that has this problem.

**Comment by MustaphaTR** [comment]
http://resource.openra.net/maps/3373

**Comment by pchote** [comment]
Palettes must be defined on the `^BaseWorld` actor if you want them to work in the editor.

**Comment by MustaphaTR** [comment]
Thanks it works now.

But why? It is a realy odd limitation.

**Comment by pchote** [comment]
This is by design, rather than by limitation.  The editor does not create a normal world, but instead its own EditorWorld.  Common traits that are used by both must be defined on ^BaseWorld, which both inherit from.

**Comment by MustaphaTR** [comment]
Ok, i understand.
