### ISSUE TITLE
TD: should missions play "win1" once the primary objective is achieved?

### ISSUE THREAD

**Issue by clemty** [OpenRA/OpenRA#8510]
gdi01 plays this track, but no other mission does

**Comment by clemty** [comment]
to rephrase, is it better if the missions explicitly play the track, or should the track be played by the status window which pops up when all primary objectives are met?

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/8710 solves this nicely.

**Comment by penev92** [comment]
#8710 was merged.

>[00:08] < GraionDilach> all missions play victory music
[00:08] < penev> closing then
[00:09] < GraionDilach> at C&C mod, missions even play side-specific victory music
