### ISSUE TITLE
"Civilian killed" notification when killing the APC in the top-right base in Oum Hadjer

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#8530]
##

**Comment by clemty** [comment]
mentioned as intended behavior in #8048

**Comment by obrakmann** [comment]
Maybe we shouldn't play the death sound if the unit isn't in the world. Maybe optionally, only enabling it for tanya and the rambo guy?

**Comment by abcdefg30** [comment]
As far as I can see, the APC has civilians loaded, which you do kill by killing the APC. This sounds like expected behaviour to me. What do you think is the issue here?

**Comment by Smittytron** [comment]
After playing a bit of Remastered, my guess is that the civilian killed notification isn't meant to be played on every civilian death. Probably only on missions where the civilians are allied with the player.
