### ISSUE TITLE
Warthog hunt "Destroy the GDI base" objective is incorrect

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#8531]
You need to destroy everything in order to achieve this.  The wording should be changed to "Destroy all GDI forces", or the trigger changes to all buildings destroyed.

**Comment by clemty** [comment]
this matches the way the original mission was scripted
I lean towards making the trigger fit the objective (and not the other way around)

**Comment by clemty** [comment]
I've fixed that locally, will commit tomorrow

**Comment by clemty** [comment]
fixed with merged commit #8561
