### ISSUE TITLE
Some missions are missing "Reinforcements have arrived" notification at the start

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#8534]
Noticed with "Repair the GDI Base (b)", but probably affects others too.

**Comment by clemty** [comment]
happens in these missions:
* gdi05a
* gdi05b
* nod02a
* nod02b
* nod03a
* nod03b
* nod04a
* nod05
* nod06a (also when transport is sent in in the end)
* nod06b (only when transport is sent in the end)
* nod06c (also when transport is sent in in the end)
