### ISSUE TITLE
Show range diameter in replay for turrets

### ISSUE THREAD

**Issue by Snurre86** [OpenRA/OpenRA#8543]
Add to the turrets the same circle that is on the "Construction yard" that represent the diameter of the range in replay.
![openra game_2015_06_22_15_20_27_468](https://cloud.githubusercontent.com/assets/7798635/8282666/8d8ea4b6-18f2-11e5-9d85-41e9c65e4f65.png)
![openra game_2015_06_22_15_20_18_226](https://cloud.githubusercontent.com/assets/7798635/8282645/7f1ae124-18f2-11e5-97cf-7e081b9e8c3c.png)
![openra game_2015_06_22_15_20_23_371](https://cloud.githubusercontent.com/assets/7798635/8282654/859a552a-18f2-11e5-8d5f-f7ef8885d1e2.png)

**Comment by obrakmann** [comment]
I agree, we should do that.
