### ISSUE TITLE
Utility gets rotations inverted by Y-axis

### ISSUE THREAD

**Issue by HenrytheSlav** [OpenRA/OpenRA#8544]
Hi guys, while converting maps from original soviet RA campaign I noticed a lot of units facing walls and stuff. The problem is apparently in the utility, which converts the rotations badly. In two screenshots, there is original map shown in RAED with correct rotations, and then screenshot of unchanged converted map. You can see that for example harvester remains same, facing down, while the units near the wall completely change direction left to right, and those facing SW now face SE and reverse.

![openra 2015-06-22 19-14-39-64](https://cloud.githubusercontent.com/assets/12610736/8288055/f22dae96-1913-11e5-836b-0df5bdaf8ac0.png)
![bez nazvu](https://cloud.githubusercontent.com/assets/12610736/8288056/f2301848-1913-11e5-9be9-8f20371ef249.png)

**Comment by clemty** [comment]
I suspect the utility does it right, and OpenRA itself displays the units incorrectly.

from http://cnc.wikia.com/wiki/Tiberian_Dawn_Mission_Manual
>direction which it is facing. 0=north, 32=north-east, 64=east,
>96=south-east, 128=south, 160=south-west 192=west, 224=north-west.

I converted a TD mission (scg30ea), when run in C&C95 1.06, the gunship faces left; after importing it into OpenRA it faces right (yaml contains "Facing: 192" for the boat). (After manually changing it to 64 it faces east)

**Comment by Unit158** [comment]
Facings should work in the direction of bearings if they do not do so already.

**Comment by HenrytheSlav** [comment]
Closed in #11227.
