### ISSUE TITLE
Starting spec

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#8551]
It would be nice for new players and vets alike to have a 10s spec at the start of the match to see the map and chat with players. 

As a toggleable option (enabled by default) a match starts paused with the entire map revealed. A visual timer audibly counts down from 10 to 0 at which point the camera snaps back to your MCV, the shroud cloaks as usual and the 'battlefield control initialised' sound plays.

There is nothing more frustrating than playing a new map and realising it's tiny and that your initial build order has just doomed you or that you placed your REF by some ore without a mine because you couldn't make out the minimap in the lobby.

**Comment by Unit158** [comment]
I think disabling shroud by default would be a better idea. I really don't understand how people can stand playing with it...

**Comment by deniz1a** [comment]
Disabling shroud by default would currently break Red Alert balance because Gap Generators would be useless. I was trying to fix that in #7665 but a refactor of satellite code was required for it.

**Comment by chrisforbes** [comment]
Just starting with the shroud fully revealed (not disabled!) doesn't break
anything.

**Comment by chrisforbes** [comment]
(Well, there are some minor changes -- reveal map crate becomes pretty
useless; exploration resets (via spy, or crate) become more extreme.)

**Comment by deniz1a** [comment]
Oh right, there should be another lobby option called Reveal Shroud or something...

**Comment by AoAGeneral** [comment]
I like having the shroud on. With the shroud on you can't find oil derricks, bridges, and choke points from the start of the game. Shroud being off however is new user friendly in a multitude of ways. With more advanced play its best to have on. Deters pre-planning strategic play and derives the emphasis on scouting. More so true if your enemy plays as random all the time.

**Comment by pchote** [comment]
I agree that this is frustrating, but I don't see this feature being implemented as requested.  This is more an argument to disable the shroud by default, IMO.
