### ISSUE TITLE
Break down spritesheets into individual graphic files?

### ISSUE THREAD

**Issue by scskwirl** [OpenRA/OpenRA#8552]
This is more of a proposal than an issue. It's hard to explain in text, pardon if it's unclear...

What if, instead of putting all the graphics on spritesheets, such as that of UIbits and other non-SHP graphics, make each individual graphic their own file?

Looking at the UI chrome, there is a lot of picking out graphic WxH and X/Y values off of one sheet.

One downside I can think of to doing this is the extra memory and resources needed to manage every single graphic, but I think as far as modding goes, it is a lot more direct.

For example, the factions played, right now, can share the same infantry/vehicle/aircraft/etc icons off of the same sheet. I can even make separate sheets for the factions. To label each of those icons on the team's chrome, I'd refer to a coordinate on the sheet, and a specific width/height amount of pixels for it to fit.

Using individual graphics files, I can either select the very one I'll draw onto, or if I want to resize it for a custom UI, I can, and in a Trait, point out which file I want to use, and its width/height.

So, if I want a different icon for each team, I make another graphic of that icon, relabel both the file and the Trait definition in the chrome, and it will read specifically the image.

**Comment by pchote** [comment]
The engine supports this, so modders are free to do it if they want.  They will need to deal with the performance overheads that come from that decision, however.
