### ISSUE TITLE
Access violation when using SHP builder

### ISSUE THREAD

**Issue by sajwang** [OpenRA/OpenRA#8570]
Hi all,

I was creating a unit with a custom sprite set (welll, a transport ship slapped on top of a cruiser) and tried the following:

Cmd prompt conversion- I got an unknown pixel format error. 

Shp compilation using Shp builder- imported my PNG file but shp builder sees it as one big sprite and refuses to see it any other way.

Constructing a Shp frame by frame- brute forcing copy posting eavh image frame by frame. This os where I run into access violations; it won't let me add any frames. I tried an older shp builder version but the current OpenRa version doesnt accept it.

I appreciate any help!

**Comment by Mailaender** [comment]
> Cmd prompt conversion- I got an unknown pixel format error.

I can only guess from here, but it probably wasn't an indexed palette 8-bit PNG file.

**Comment by GraionDilach** [comment]
Use XCC Mixer. http://xhp.xwis.net/utilities/

**Comment by sajwang** [comment]
Thanks! I just set up a new SHP told it how many frames i needed and brute forced it.
