### ISSUE TITLE
Tiberian Sun infantry can't board APCs anymore

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#8573]
Reproducible on Hot Springs mpa. Might be a height related issue.

**Comment by penev92** [comment]
It would be pretty easy to verify if it's height-related (btw you wanted an example of where the blank map would be useful).
But as far as I remember, we've always had this issue - cargo (among other things) can't deal with height and expects everything to be at height 0.

**Comment by Phrohdoh** [comment]
See #7904
