### ISSUE TITLE
Satellite reveals some submerged subs

### ISSUE THREAD

**Issue by Fahrradkette** [OpenRA/OpenRA#8578]
Playing a 2v2 as soviet I could see some enemy subs after my teammate got the sattelite up. On my screen the enemy subs were shown as surfaced. When trying to force-attack them, the cursor disappeared.

Felt the same like ticking "disable shroud and fog" in the debug menu, except for the "staying surfaced" part.

Failed to reproduce it on a local game using multiple client instances.

**Comment by pchote** [comment]
We've fixed a lot of visibility, targeting, and GPS related bugs for the next release.  Unfortunately there's not enough concrete info here to go on, so there's not much benefit for keeping this open.  Please open a new ticket with screenshots or a replay if you can reproduce this on the newer playtests / winter 2015 release.
