### ISSUE TITLE
Music ends unexpectedly when pressing "Start Game" in the lobby

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#8587]
Introduced in #8568.

**Comment by reaperrr** [comment]
The way I understand it, stopping it when the world changes is not wrong. I think It should restart when starting a game, though.

**Comment by penev92** [comment]
@GraionDilach is already on it, as far as I know.

**Comment by pchote** [comment]
I consider this a feature, but it would be nice if we could fade it out instead of stopping abruptly.

**Comment by pchote** [comment]
In 99% of cases you will be transitioning from either the shellmap or score music (once somebody finally decides to implement it), so there's not much value to persisting the music state.

**Comment by GraionDilach** [comment]
It's already fixed in #8562.

**Comment by GraionDilach** [comment]
This is caused by the fact that worlds overlap in the memory, the garbage collector will only trigger stopping the music after the new world has already been constructed.

**Comment by obrakmann** [comment]
Closing as it's expected behaviour.
