### ISSUE TITLE
Massive AI performance issues related to water units

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#8588]
Not only does the AI run into problems when trying to build sub pens/ship yards when there's no water nearby (#8569), it actually gets even worse when it does manage to build a pen/yard and then tries to attack land enemies with water units (and vice versa). This causes huge lag spikes.

We should consider disabling naval buildings and ships for all RA AIs except the Naval AI, at least until those performance issues are fixed at code level. Currently, playing games with AI in the RA mod is a nightmare in terms of performance.
##

**Comment by chrisforbes** [comment]
How about we fix it instead? What is it actually doing?

**Comment by penev92** [comment]
My guess is ridiculous attempts at pathfinding.

**Comment by RoosterDragon** [comment]
See also #9021.

**Comment by reaperrr** [comment]
Reverse duplicate of #12435.
