### ISSUE TITLE
Sound engine should support streaming

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#8593]
Simply uncompressing AUD/IMA ADPCM into memory before playing them is not exactly efficient. In case of IMA 22khz/stereo (let alone 44khz/st) it can even cause a noticable lag spike when a large music file is loaded.

**Comment by RoosterDragon** [comment]
Now music is no longer cached (#13461) - we pay the loading penalty every time, and this would assist in making it less noticeable.

**Comment by aydjay** [comment]
It looks like there is a project which allows streaming of various file formats: [https://github.com/naudio/NAudio](url)

Unfortunately it is for windows only but they do support ADPCM.

Maybe it is possible to see what they have done and see if it is possible to implement a solution which would be suitable for OpenRA.

**Comment by reaperrr** [comment]
Since we have a PR for it now, might as well move to Next release milestone.

**Comment by Mailaender** [comment]
You can collect your bounty at https://www.bountysource.com/issues/23256122-sound-engine-should-support-streaming
