### ISSUE TITLE
Light post in TS breaks when under stealth cover

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#8601]
![screenshot from 2015-06-25 20 18 53](https://cloud.githubusercontent.com/assets/4331210/8416465/3acd043e-1ea6-11e5-8dd6-bf82c8a56093.png)

**Comment by reaperrr** [comment]
I'm not sure the light post should be cloakable (as it shouldn't be buildable or player-owned under normal circumstances), but of course the alpha effect shouldn't break like that.

**Comment by penev92** [comment]
I do miss #7876...

**Comment by Mailaender** [comment]
I gave it a second try in https://github.com/OpenRA/OpenRA/pull/8996.

**Comment by Mailaender** [comment]
It won't however fix this clash. Those two palette effects don't work well together.
