### ISSUE TITLE
TD Ranking

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#8603]
Ranking I think is a good addition but the ranking is way to powerful. Rank 1 and 2 in example for recon bikes and infantry causing them to move way to fast for any vehicle to catch up to them. At max rank bike they move faster then the A10 planes.

Suggestion: Make small gains for ranking rather then big upgrades

**Comment by Unit158** [comment]
Another idea: We could change how things are upgraded when they rank up. ATM, most "AA" weapons are too slow to be very effective versus air, so we could see about improving the weapon when the unit ranks up, and reduce the speed (for example).

**Comment by AoAGeneral** [comment]
This could be a good idea. However, some people may prefer to have faster speed and regret the rank up system instead.

**Comment by penev92** [comment]
Addressed in #9017.
