### ISSUE TITLE
Unable to Start OpenRa Playtest - 0628 (Mac OSX)

### ISSUE THREAD

**Issue by oukjweather** [OpenRA/OpenRA#8606]
I downloaded the latest playtest (OpenRA-playtest-0628) for Mac OSX and have been unable to get it to start. I can start the release and all is well. I try to start the playtest and it crashes. All I get is a black screen. I don't get to the loader screen. The activity monitor shows the OpenRA process unresponsive along with com.applle.geod. I quit everything again and restarted and the same behavior. There was nothing in the logs to suggest what is going on. debug.log is empty and exception.log is un modified.

**Comment by pchote** [comment]
Please see the discussion in #8492 for an explanation of why this happens and how to fix it.
