### ISSUE TITLE
Crash playing online

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#8608]
Game was really chugging for me on this map. Happened right after another player had connection problems. Logs and replay linked. Latest release.

http://expirebox.com/download/7e20aab7b28ff6894348158479604312.html
(48h link)

http://pastebin.com/Lms5aK8t

**Comment by Mailaender** [comment]
> Exception of type `System.InvalidOperationException`: Out of sync in frame 5996: Blame Tick.
> Compare syncreport.log with other players.

**Comment by penev92** [comment]
We need the `syncreport.log` files from the other players to be able to do anything about this.

**Comment by r34ch** [comment]
I should add Ubuntu 14.04 x64

**Comment by greenfield** [comment]
This might be a similar problem:
http://pastebin.com/CUAW6N8f

**Comment by penev92** [comment]
The problem is that the game lost synchronization between the players.
The only way to find out what went wrong (usually with just one of the players) is to have the `syncreport.log` files from all of them and compare those. The differences inside are what tells us what the problem is.

**Comment by greenfield** [comment]
I see. Thank you for the response :)
