### ISSUE TITLE
Team set in PlayerReference is ignored for unplayable players

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#8623]
E.g. https://github.com/abcdefg30/OpenRA/commit/6b393c3cceee8d136b4cd729ecf8c2626f120226 gives me
![lockteam](https://cloud.githubusercontent.com/assets/7704140/8486156/1617f32e-2103-11e5-95b6-b0b647af21d3.png)
(I forced the Soviets team to `2` actually.)

**Comment by Unit158** [comment]
This is probably related to the fact that colour choice for the bots is ignored as well. (I can't find the pr)
