### ISSUE TITLE
Game Crash - RA Skirmish

### ISSUE THREAD

**Issue by mistikal** [OpenRA/OpenRA#8633]
Have had this a few times, and the reccuring theme is this happens when a building/unit is about to die/etc.

In the YAMLs, I do have one additional vehicle, one additional missile, one additional small-cal weapon, however even with my modifications removed the game still crashes in the same fashion.

Have reinstalled twice and used different maps, no change.

> Red Alert Mod at Version playtest-20150628
> Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
> Runtime Version: .NET CLR 4.0.30319.34209
> Exception of type `System.OverflowException`: Arithmetic operation resulted in an overflow.
>   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
>   at OpenRA.Traits.PlayerResources.Tick(Actor self)
>   at OpenRA.World.<Tick>m__3(TraitPair`1 x)
>   at OpenRA.WorldUtils.DoTimed[T](IEnumerable`1 e, Action`1 a, String text)
>   at OpenRA.World.Tick()
>   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
>   at OpenRA.Game.LogicTick()
>   at OpenRA.Game.Loop()
>   at OpenRA.Game.Run()
>   at OpenRA.Program.Run(String[] args)
>   at OpenRA.Program.Main(String[] args)

I notice it also mentions traits, so here is the trait report:

> IPaletteModifier: 195218
> IPostRender: 195217
> IRenderShroud: 195217
> IRenderOverlay: 195217
> Production: 183984
> ITickRender: 30664
> ITick: 30664
> INotifyIdle: 30664
> IStoreResources: 30664
> IRadarSignature: 30147
> ISync: 20444
> PlayerResources: 48
> EditorActorLayer: 30
> ILoadsPlayerPalettes: 11
> TechTree: 8
> DeveloperMode: 8
> PowerManager: 6
> RadarPings: 3
> IRender: 2
> ResourceType: 2
> MenuPaletteEffect: 2
> IRenderModifier: 2
> IDisable: 2
> INotifyCreated: 2
> INotifyAddedToWorld: 2
> ITechTreePrerequisite: 2
> IWorldLoaded: 1
> ICreatePlayers: 1
> ActorMap: 1
> ScreenMap: 1
> TerrainGeometryOverlay: 1
> ILoadsPalettes: 1
> MissionObjectives: 1
> IFogVisibilityModifier: 1
> Shroud: 1
> Health: 1
> Buildable: 1
> SupportPower: 1
> ChatCommands: 1
> HelpCommand: 1
> IValidateOrder: 1

**Comment by penev92** [comment]
Seems like you have so many refineries/silos/other actors with the `StoresResources` trait, that you hit an integer overflow. Either you changed the capacity of one of those, or you have a million refineries. I'm going to bet on the first one.

**Comment by mistikal** [comment]
Ah yes, forgot I altered the refinery to hold some more cash. Will change it now and see what happens.

**Comment by mistikal** [comment]
Just done two short games, neither crashed, likely fixed. Thank you!
