### ISSUE TITLE
Screen resolution rendering

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#8638]
About once every 20 times I run openRA, the resolution stretches vertically off the top of the screen and buttons are hard to click on. In the screenshot attached, the mouse is over the button, but it does not give the visual hover until the mouse is dragged further down. The top of the border is off the screen and text is rendered with artefacts.

Ubuntu 14.04lts x64

http://i.imgur.com/4i4ayjL.png

**Comment by Unit158** [comment]
I can't reproduce this.

**Comment by pchote** [comment]
We don't interact with the window manager directly, so this will be an upstream bug in Ubuntu or SDL.

Not much we can do about it unless you can provide specific steps to reproduce so we could debug a workaround, sorry.
