### ISSUE TITLE
Indication of map with custom rules in multiplayer lobby

### ISSUE THREAD

**Issue by Basti504** [OpenRA/OpenRA#8651]
It would be nice if one could see that a map contains custom rules by some kind of a indicator in the multiplayer lobby. Something similar to the "Advanced" label on the Resource Center. A player would know in front that the game may behave in a totally different way.

Especially if people are creating identical named maps with cheating-like rules and crappy trol-sounds, as I encountered this morning.

Example:
http://resource.openra.net/maps/3525 (clone)
http://resource.openra.net/maps/64/ (origional)

**Comment by Mailaender** [comment]
I think @cncnet has this, too. Added a similar warning to our lobby. https://github.com/OpenRA/OpenRA/issues/8652
