### ISSUE TITLE
Veterancy wiki article is outdated

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#8657]
https://github.com/OpenRA/OpenRA/wiki/Veterancy needs an update.

**Comment by penev92** [comment]
It will be even more so after #8572 is merged.
Better wait for that before updating the wiki.

**Comment by ValarianRossi** [comment]
I just went through and made several changes to this to reflect stuff with the Upgrade Manager. Let me know if I missed anything.

**Comment by abcdefg30** [comment]
Looks good to @Phrohdoh and me, so I guess this is fixed. Thanks @ValarianRossi!
