### ISSUE TITLE
Chronoshift did not chrono all units back

### ISSUE THREAD

**Issue by Basti504** [OpenRA/OpenRA#8670]
Just encountered an interesting bug, when I chronod my tanks "german"-style into the enemy base the game surprisingly chronod all units back except one at the end of the chrono action.

![Permanent Chrono](http://i.imgur.com/MklvNAu.gif)

Replay:
https://www.dropbox.com/s/3qfqkdbp9ck3toi/OpenRA-2015-07-06T183755Z_chrono.orarep?dl=0
(Around 17:30)
##

**Comment by Basti504** [comment]
After some playing with the source code, I see the reason it does not teleport that unit back. 
In the same game, the same breakpoint is hit when propably another chronoshift was busy.

Hope this helps :) 

![Alt code](http://i.imgur.com/A2KhZlD.png)

**Comment by epicelite** [comment]
Happens sometimes to me too, dont know why.

**Comment by penev92** [comment]
Thanks for the thorough report!
Also it's nice to see people debugging their own issues. This would save us some time. :)

**Comment by WolfGaming** [comment]
Seems like the return teleport is not finding any valid cells to return the units to.
Are the original cells of the units occupied by other units?

**Comment by Basti504** [comment]
Here the chrono origin of the Gif in the first post.
Not quite blocked it seems, apart from the one tank.

![Alt text](http://i.imgur.com/kj5xfio.gif)

**Comment by Townes27** [comment]
Here's a replay where zero units are chronod back.
OpenRA release-20150614
Map: Squirrels Tournament
Around minute 39:00 Peddaa chronos 5 Mammoth Tanks of LizardLipz into dent's base.
They don't return even though the original cells aren't being occupied.
http://s000.tinyupload.com/index.php?file_id=17891347556467610837

**Comment by Basti504** [comment]
After some more digging around in the source code I found it a nice challenge to track down what happens with that one tank not teleporting back as it is consequently reproducible using the replay of that game. The debugging I did in the posts above were not the actual problem as they were targeted to other actors. I did not think about how to solve this issue as I am not that familiar with the codebase, only track it down.

So here comes… 

1) First to track the tank itself some code was added to see the ActorId on the screen itself, so the tank is identifiable.

2) Using the ActorId from that one tank it was possible to follow the code that is executed for that tank using conditional breakpoints. It is actually quite nice to see the game in a sort of “Step mode” using the conditional breakpoints.

Below the start of chronoshift, the current activity gets canceled and the teleport queued.
![alt](http://i.imgur.com/eOj4dCl.png)
![alt](http://i.imgur.com/zjIGBv0.png)

3) After some tracking I see the teleport getting executed.
![alt](http://i.imgur.com/k4h7pR0.png)

4) The tanks have been teleported and a lot of Move… activities are executed. Now its waiting until the units gets teleported back 
![alt](http://i.imgur.com/i9RfgXR.png)

5) Finally the tanks are teleported back (see stack trace), except the one tank (Id 1392). So from here it should get interesting.
![alt](http://i.imgur.com/izI06x9.png)

6) So the return teleport activity is actually queued as it should be.
![alt](http://i.imgur.com/IHCUQw0.png)

7) This is where is gets funky, in this specific case an activity is already queued for tank 1392, so its gets set as the next one. This is some kind of recursive tree it seems?
![alt](http://i.imgur.com/L0An0Fu.png)

8) In the MovePart class the queuing is done, but redirected to another class.
In the Cancel function above there is also a call to Base.Cancel. Maybe the call to the base object should also be done on the Queue function to fix this issue?
![alt](http://i.imgur.com/7Jazyze.png)

9) Jumping to the Activity.cs class itself the same code is present as in Actor.cs to do the NextActivity thing.
![alt](http://i.imgur.com/9MuvrMw.png)

10) Returning from that function it is seen that the “object” is not actually updated for some reason as can be seen in the Locals window. So no NextActivity is set, and the TelePort activity is probably lost.
![alt](http://i.imgur.com/iOgdfQ3.png)

11) After this it is obvious that the teleport will not be executed as can be seen from the last screenshots.
![alt](http://i.imgur.com/tvIxl73.png)
![alt](http://i.imgur.com/X83Qdma.png)
![alt](http://i.imgur.com/mGX8WBU.png)

I hope this helps tracking this issue down. From my own experience I know timing or 1 out of 1000 wrongs issues are the best ones. 

**Comment by penev92** [comment]
Hey, nice debugging :)
I particularly like the on-screen actor IDs. That would have been so helpful in so many situations :X  Feel like PR-ing the code?
Now, for your report:
>This is some kind of recursive tree it seems?

The Activities are stored in a linked list, so close. ;)
But I think you were right the first time - according to your earlier screenshots the `Teleport` activity *does* run, just returns prematurely due to lack of target cells. I will run the replay to verify shortly.

**Comment by penev92** [comment]
Hm, actually it seems I don't have the  map that the game was played on.

**Comment by Basti504** [comment]
This is the map used in the replay.
https://www.dropbox.com/s/nx9fbr82dj0aiuk/Destination-v11-11.oramap?dl=0

**Comment by Basti504** [comment]
> But I think you were right the first time - according to your earlier screenshots the  Teleport  activity does run, just returns prematurely due to lack of target cells. I will run the replay to verify shortly.

Monitoring the ActorID, these points were hit when the Actor was a husk. In all the cases the Actor was not that one tank (1392), so I ignored those cases.

But to make the "teleport not executing" a bit more strong I took another approach at tracking the code using some non-conditional breakpoits with printing to the Output window.

![alt](http://i.imgur.com/twl20MV.png)
![alt](http://i.imgur.com/Zn1yGOA.png)

At the start of the chronosphere, the units are nicely transported to the enemy base. The ActorID's are lining up nicely.

![alt](http://i.imgur.com/dJGbop8.png)

But when returing the units, we can see that the teleport activity is planned, but not executed as the 1392 ActorId is not being teleported. As seen on the OpenRa window, the husks are still there, but there are not teleported as the BestCell is null, but in case of the tank  1392 the **whole** teleport activity is not executed as can be seen in Output windows.

![alt](http://i.imgur.com/CPKN6wk.png)

**Comment by Basti504** [comment]
Finally I managed to reproduce it in a skirmish match. The GIF tells the story.

http://i.imgur.com/lylDYxw.gif (its big)

**Comment by penev92** [comment]
Oh I think I get it now.
Issuing **and cancelling** a new order when the "teleport back" activity is in the queue breaks stuff.
So timing would be pretty important for reproducing.

**Comment by Basti504** [comment]
By hacking a bit further I managed to capture the Teleport activity in the Move activity by adding one line, see below. (Although this breaks the game quite hard with an infinite loop when unloading a harverster)

![Alt](http://i.imgur.com/lujXyLu.png)

But even when the Teleport Activity is captured the Teleport will be ignored as the Move activity will return `This` and further activities down the list are ignored.

![Alt](http://i.imgur.com/yQMJezg.png)
