### ISSUE TITLE
Music player stops after first song

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#8671]
RA mod, no shuffle, no loop selected. When game launches, music starts to play automatically. But it stops after the first song. I have the full scores.mix installed.

**Comment by penev92** [comment]
#8562 fixes that.

**Comment by GraionDilach** [comment]
Someone close this as being a duplicate of #8033, please.

**Comment by penev92** [comment]
I set up your PR to close this automatically when merged.
