### ISSUE TITLE
Benchmarking

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#8673]
We already measure CPU and rendering performance and display it in-game when activated under *Settings* - *Advanced*. It is also possible to run replays via double-click or the command line as well as start semi-deterministic games using Lua scripts as seen in our shellmaps.

For @phoronix-test-suite integration we need some kind of machine readable output format for those. Either dump it to the console, into a log text file or raw values into CSV. I don't know what is preferable here.

**Comment by pchote** [comment]
See also http://logs.openra.net/index.php?year=2015&month=07&day=07#03:52:21

**Comment by Mailaender** [comment]
and http://www.phoronix.com/forums/forum/phoronix/phoronix-test-suite/809405-openra-test-suite

**Comment by Mailaender** [comment]
@chrisforbes Is https://github.com/OpenRA/OpenRA/pull/10133 something that would work for Intel as well?
