### ISSUE TITLE
Disguised spies are not defined as spies

### ISSUE THREAD

**Issue by StexoO** [OpenRA/OpenRA#8677]
At least for spectators.
This guy is not a Magic Hat rocket soldier but is an Alapepitua spy.
![spyfaction](https://cloud.githubusercontent.com/assets/8930382/8554522/92a105b2-24ea-11e5-9615-f5571b954902.png)

**Comment by pchote** [comment]
Please include the version when posting gameplay issues.  There's a good chance this has either been fixed by (if running release), or broken by (if running playtest) the latest playtest.

**Comment by StexoO** [comment]
Sorry, I saw this in the release-20141029. I can't check if it's reproducible in the latest versions at the moment.

**Comment by penev92** [comment]
I believe this is what #8298 intended to fix.

**Comment by GraionDilach** [comment]
#8478 should also work there.

**Comment by deniz1a** [comment]
#8699 fixes this.

**Comment by pchote** [comment]
This has now been fixed.
