### ISSUE TITLE
Adding Weather-Overlay for rain and snow

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/OpenRA#8687]
Hey,
after 3 days getting into the code, finally some progress. Here's the first screenshot.
![screenshot 2015-07-08 18 17 00](https://cloud.githubusercontent.com/assets/5147014/8582733/f6d04f96-25c8-11e5-8645-c5ccfee241c4.png)

**Comment by TheRaffy** [comment]
I tryed to use  some bigger flakes.
![screenshot 2015-07-08 23 55 55](https://cloud.githubusercontent.com/assets/5147014/8583361/43757b6a-25cd-11e5-850c-9e2cf7cdc6f0.png)

**Comment by dan9550** [comment]
OMG most awesome thing ever!

This looks good, apart from snow being a little out of place in the desert.

**Comment by Phrohdoh** [comment]
@TheRaffy Consider opening a PR so you can get code/yaml help easier, if you'd like.
Good job so far.

**Comment by TheRaffy** [comment]
![screenshot 2015-07-22 16 52 26](https://cloud.githubusercontent.com/assets/5147014/8828685/ba8337ee-3093-11e5-8be2-24cbf887f57a.png)
![screenshot 2015-07-22 17 03 51](https://cloud.githubusercontent.com/assets/5147014/8828687/bc457ec0-3093-11e5-97f8-ce78ec24ec8f.png)

**Comment by dan9550** [comment]
@TheRaffy Is that the rain scrolling with the camera movement? or just different set angles?

**Comment by TheRaffy** [comment]
![screenshot 2015-07-23 19 08 06](https://cloud.githubusercontent.com/assets/5147014/8856951/60e79942-316e-11e5-8bbf-806479856cc4.png)

**Comment by TheRaffy** [comment]
The particles stay at the same position over the map if you scroll the viewport, besides  the wind blowing them away. Also the wind is changing directions and intensity.

**Comment by TheRaffy** [comment]
I have to pause my work at the weather overlay, to work at other parts of the Bachelor Thesis. Thanks for help everyone!

**Comment by cjshmyr** [comment]
Looks really nice so far!

**Comment by TheRaffy** [comment]
For those who like to see it in action :D https://github.com/TheRaffy/OpenRA/tree/WeatherOverlay

**Comment by x-a-n-a-x** [comment]
The snow effect is looking really really really good!

The rain is good too but could it be possible to add short animations at random locations to mimic the raindrops hitting the ground? example : https://youtu.be/pyMq_88pfG4?t=123

**Comment by TheRaffy** [comment]
Hey, xanax good idea, I added it to the list of Could have features^^. Maybe this can get combined with some animations for the impact. but this will not happen in the near feature.

**Comment by x-a-n-a-x** [comment]
And what about adding a moving fog ?
http://media.moddb.com/images/mods/1/11/10740/sshot348.jpg
