### ISSUE TITLE
TD: difficulty selection dropdown should show selection

### ISSUE THREAD

**Issue by clemty** [OpenRA/OpenRA#8696]
currently you have to click on it and open it to see which difficulty is selected
changing this to show something like "Difficulty: Easy" would improve usability

![difficulty](https://cloud.githubusercontent.com/assets/10729559/8605500/0c5b8264-2686-11e5-977f-bfed16ca817a.png)

**Comment by Phrohdoh** [comment]
Good idea!

**Comment by obrakmann** [comment]
It should, I agree. Still a duplicate of #8372 :)
