### ISSUE TITLE
Support powers statistics

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#8706]
Can you add the number of ~~superweapons~~ support powers used in the statistics ?

**Comment by GraionDilach** [comment]
What defines a superweapon? Sonar Pulse and the Nuke are both a support power for the game.

**Comment by StexoO** [comment]
Oh sorry I wanted to say support powers. Nuclear missiles, iron curtains, paratroopers, ...

**Comment by Smittytron** [comment]
Closing as wontfix as part of our github-cleanup initiative. If someone ever makes an elaborate end game score screen this might have a place there, but I don't see that happening anytime soon.
