### ISSUE TITLE
One spy should affect one building and only one

### ISSUE THREAD

**Issue by StexoO** [OpenRA/OpenRA#8707]
It's a bit odd to be able to shut the power down in an entire base with only one spy.
A spy in an advanced power plant should block this power plant only, so the player has temporarily 200 less energy.
Doing this, a player attacked with spies can handle them by managing his power and a player attacking with spies has a bit more to do to stop an entire base than moving around only one $ 250 guy.

**Comment by Unit158** [comment]
IMO, right now it is the only reason why spies are worth their salt.

**Comment by GraionDilach** [comment]
We merged in RA2-like veterancy granting for infiltrating production buildings some days ago, this can be changed, I guess.

**Comment by pchote** [comment]
Getting a spy into an enemy base is risky, so the benefits of pulling it off need to reflect that.  Why would I waste my money and attention to temporarily disable a single power plant?

**Comment by Snurre86** [comment]
Sounds to me like you never use the spy your self and don't want others to use it on you.

**Comment by Unit158** [comment]
I'd even be fine if it only shut down all defenses but kept production strong, but it shouldn't only affect one power plant.

**Comment by penev92** [comment]
Closing as a #wontfix based on general consensus.

**Comment by StexoO** [comment]
@Snurre86 No, spies sounds to me like walls. Blocking instead of playing. If I have to manage a spy I would like to be able to counter it and if I send a spy I don't want to shut down my enemy's production and defense but I would like to damage him. Spies should be less strong or more expensive. :'/

**Comment by Nineeva** [comment]
If you don't like spies in your bases, build a few dogs or use walls more often.

**Comment by StexoO** [comment]
The problem is about the possibility to power down an entire base (defense, radar, GPS, production speed and so on) with only one cheap spy. All their other abilities are quite balanced.
It would be balanced if a spy had an "attack" of -200 power. You would have to send five spies to get your -1000 power and completely block your opponent for a while but you would have to pay $ 2500 for it.
Anyway it's closed now. 😃
