### ISSUE TITLE
Too many range circles

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#8730]
I was placing a turret and this happened:
![rangecircles](https://cloud.githubusercontent.com/assets/6599106/8733094/70e594ac-2c0a-11e5-9dd5-acb0a3719274.png)

I think only range circles of the same type should be shown. No con yard circles while placing turret for example. Also, enemy circles are also shown here...

**Comment by deniz1a** [comment]
I just had an idea: how about filling these circles with a semi-transparent overlay? So, defense buildings could have red filled range circles...

**Comment by obrakmann** [comment]
You have dev cheats enabled.

**Comment by deniz1a** [comment]
oh.. ok thanks
