### ISSUE TITLE
AI Destroys Oil Derricks

### ISSUE THREAD

**Issue by atlimit8** [OpenRA/OpenRA#8736]
While testing, I noticed the Naval AI target and destroy the oil derricks before focusing on its enemy.
Unlike #4561, this is about attacking them instead. This might be fixable by changing the faction of the oil derricks. I noticed this on Artic Triangle Affair map where the oil derricks are on islands not between the two bases.

**Comment by abcdefg30** [comment]
This is indeed caused by `Creeps` owning the oil derricks on Artic Triangle Affair.
