### ISSUE TITLE
Implement interface members explicitly.

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#8739]
This would remove the temptation to call interface members from unrelated code, and would make implementations a bit more clear when methods and/or fields have vague names.

Input / opinions?

**Comment by pchote** [comment]
Just to make it clear, what @Phrohdoh is proposing is that traits that implement e.g. `IIssueOrder` would then declare `public Order IIssueOrder.IssueOrder(...)`, which then hides it from the set of public methods that are exposed on the trait by itself.  This would dramatically cut down on the noise that shows up in IDE autocompletes, and makes it harder to circumvent our existing interface code.

I'm all for this change, but it's going to be a massive job if we don't automate it.

**Comment by penev92** [comment]
I still don't get it. Can you provide an example?

**Comment by Phrohdoh** [comment]
Current:
```
public class Foobar : INotifyOwnerChanges
{
    public void OnOwnerChanged(Actor self, Player oldOwner, Player newOwner) { }
}
```

Proposed:
```
public class Foobar : INotifyOwnerChanges
{
    public void INotifyOwnerChanges.OnOwnerChanged(Actor self, Player oldOwner, Player newOwner) { }
}
```

**Comment by penev92** [comment]
The idea behind this being that e won't call
```
var foobar = new Foobar();
foobar.OnOwnerChanged(...);
```
but rather
```
a.Trait<INotifyOwnerChanges>().OnOwnerChanged(...);
```
I assume?

**Comment by Phrohdoh** [comment]
Correct. We already call interface members on objects that are returned (`TraitsImplementing`) as interfaces, so this would prevent you from calling `foobar.OnOwnerChanged(...);`.

**Comment by chrisforbes** [comment]
+1 to this proposal.

**Comment by chrisforbes** [comment]
@Phrohdoh I suggest doing this a few traits at a time. It doesn't have to be a big bang.

**Comment by Unit158** [comment]
I'll start doing this in my open prs

**Comment by Phrohdoh** [comment]
```
[14:51:57]	<Phrohdoh> pchote: Are you ok with me starting the explicit interface implementations with this PR?
[14:52:27]	<pchote> not unless you are willing to commit to rolling the change through our existing traits
[14:52:36]	<pchote> or have a specific reason why you need it here
[14:53:04]	<Phrohdoh> I'd like to do it for other traits, but I know no one else will care and it'll cause rebase hell and conflicts over and over.
[14:53:45]	<pchote> it would be best to hold off on that until some of the others with opinions on engine / code style have had a chance to discuss it 
```

**Comment by Phrohdoh** [comment]
Interfaces given the `RequiresExplicitImplementation` attribute from #10143 can now be statically checked.

This can be closed because that PR was merged.
