### ISSUE TITLE
Crash when your spies coppy your tranya

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/OpenRA#8740]
If you are using a spy to clone a tanya and try to move your tanya-spy the game frezzes. I noticed it and was able to reproduced it at my weather overlay branche.

Can somebody reproduce it?

**Comment by TheRaffy** [comment]
I used  this https://github.com/TheRaffy/OpenRA

**Comment by Phrohdoh** [comment]
`This branch is 1 commit ahead, 2077 commits behind OpenRA:bleed`
You need to rebase.
