### ISSUE TITLE
Distinguish between 'ambient' and regular music

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#8746]
There are still a few cases that are poorly handled by our music playlist code because we are trying to apply a one-size-fits-all approach to two different use cases.

Consider the shellmap as an example: main menu music is a standard feature across almost all games, and is usually a low-key ambient music loop.  In our current implementation we treat the shellmap music as a regular track and (based on user preferences) cycle between all the available songs or stop playing anything after the song has completed its first playthrough.  Even worse, if the player has the default RA content download (which only includes one track) then the main menu will loop Hell March - one of our least low-key ambient tracks!  We have similar problems with the Ion Storm ambient track in TS, and the end-game victory/loss tracks.

A simple (and I believe the best) way to handle these cases is to introduce an `AmbientMusic` property on the `MusicPlaylist` trait.  If this is set, then it is looped (ignoring any player music preferences) as the default music choice.  If the file is defined but not present (music content not installed) then it should play nothing instead of selecting an alternative track.  Player selected music (and the InitialMusic trait property) take precident over the ambient music, but the ambient track should start again as soon as the regular playlist runs out of songs or is manually stopped in the music player.

Ambient tracks should also be displayed slightly different in the music player: they show the name and progress in the bottom player, but the playback controls (play/pause/next/prev) should be disabled.

**Comment by TheRaffy** [comment]
Is this related to trait world AmbientSound?

**Comment by GraionDilach** [comment]
No, this is related to the music handling cleanup I've started a while ago. It's 80% aimed towards me anyway.

**Comment by pchote** [comment]
Implemented in #8876.
