### ISSUE TITLE
Disable music autoplay if there are insufficient installed tracks.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#8747]
If the player has less than two regular tracks available (ignoring shellmap and score tracks, which are going to be hidden from the player) then we should not autoplay them during regular games.  This will avoid the issue where we loop hell march continuously in RA.

I'm sure we used to do this in the past, but it must have been lost in one of the refactors.

**Comment by GraionDilach** [comment]
After the music-hiding gets done, we could use ShippedSoundtracks for this - it wouldn't count hidden music and as long as there isn't more than SS (oh my), it'd stop autoplaying the playlist.

**Comment by pchote** [comment]
Fixed by #8876.
