### ISSUE TITLE
Statistics show two chronosphere icons

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#8750]
Map is the official Vegetation.
![stat](https://cloud.githubusercontent.com/assets/6599106/8784387/8718ac64-2f2a-11e5-9488-ac87df535686.png)

**Comment by abcdefg30** [comment]
My guess is that the second inactive power is shown.
(Yes, there are two `ChronoshiftPower`s: [structures.yaml](https://github.com/OpenRA/OpenRA/blob/4792ff336b89c2b18672a01583657dc3d574236d/mods/ra/rules/structures.yaml#L338-L366))
