### ISSUE TITLE
Remap TS refinery/silo icon color to player color

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#8803]
Tiberian Sun uses the same production icon with different "player" color (Yellow for GDI, Red for Nod) for several structures ([source](http://xhp.xwis.net/ts_icons/)):
 - Refinery
 - Silo
 - EMP Cannon

Since that is a bit restrictive, and we have the technology, I propose we remap those to the actual color the player is.
Those aren't building decoration colors. Those parts of the buildings are remapped to the player color. So why not remap them on the icons as well?

**Comment by pchote** [comment]
I like the idea of this.  It should be possible without any code changes by defining an appropriate palette remap and then using a custom palette for all the icons.

Does someone want to build a test case?

**Comment by GraionDilach** [comment]
I fail to see why is that restrictive. Those are duplicated cameos stored within the sidebar mixes.

Now why remapping them won't work: they do not share the color index. What you propose is to have a PlayerColorPalette trait variant which can remap different colors based upon race. Also I'm not even certain if remapping those can be done without AA issues, considering that the TS cameo palette is a funky rainbow.

For the record, the GDI refinery uses colors around 90 for the gold, but the Nod refinery cameo uses colors around 18 - yet they share the base palette.

![icons](https://cloud.githubusercontent.com/assets/1136302/8895291/eae7e454-33d4-11e5-90a1-e9a727c02091.png)

**Comment by penev92** [comment]
It's enough to use only one of the two and remap it to whatever color the player is. No need to be able to remap both.

**Comment by GraionDilach** [comment]
That'll probably still involve remaking the cameos themselves to make sure AA won't break them.

**Comment by GraionDilach** [comment]
Also having this feat on some structures alone and not on every one of them will look odd if the player does not play with the associated color of the faction.

**Comment by penev92** [comment]
Custom mods can do this for every actor (structure and unit) if they want. TS just doesn't have the artwork for it.

**Comment by Mailaender** [comment]
Those icons are not 100% identical. It is not just the remap color, but also the texture. See http://xhp.xwis.net/ts_icons/ for reference. https://github.com/OpenRA/OpenRA/pull/8799 already takes care about it.

**Comment by Mailaender** [comment]
This will only work if someone wants to make a RA/TD DOS icon mod/set. http://cnc-comm.com/community/index.php?topic=1295.0

**Comment by reaperrr** [comment]
Harvesters, too (for the record).

**Comment by penev92** [comment]
The icons look pretty identical to me.
Harvesters aren't, though, because the yellow on one is replaced with grey with red stripes on the other.
