### ISSUE TITLE
Health bars disappear over enemy units after selecting them when "Always show status bars" is enabled

### ISSUE THREAD

**Issue by obrakmann** [OpenRA/OpenRA#8804]
Introduced in a3bd007ac708019ff4d6ffa7d4aee7c377b57d97 (part of #8388), according to git bisect.

**Comment by pevers** [comment]
I tested this on 3b25a2029a4dd81fed3068ed357b1d5a83252704, but it doesn't seem to happen.

**Comment by obrakmann** [comment]
Thanks for noticing! You're right. Fixed by #8805 then.
