### ISSUE TITLE
Always default to team chat during game

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#8821]
When a player is still in game, chat should default to team, when enter is pressed. Avoids accidental messages to enemy players.

**Comment by obrakmann** [comment]
You mean, when you close the chat box after writing a message to everyone, it should open again in team mode, basically ignoring the previous mode?

**Comment by penev92** [comment]
:+1:

**Comment by GraionDilach** [comment]
Excuse me, I'm not sure how this works, but most games had separate buttons for team and globalchat (RA2 used Backspace for team, Enter for global). How does OpenRA works there atm?

**Comment by pchote** [comment]
As @obrakmann said, we already default to team chat at the start of the game if you have human team mates.  Our current behaviour is to then persist whatever the last chat mode was when starting a new message, which is a nice compromise between the two camps of "always team" vs "always everyone", and follows the principle of least surprise.  :-1: to changing away from this.

**Comment by deniz1a** [comment]
OK. Then how about making all chat mode more distinguishable? Like with different color?

**Comment by PrinceBlueblood** [comment]
usually use team chats early at the game to ask which thing to do and what kind of role we play (usually in 3 v 3 to 4 v 4 game), like you secure the possible naval line, you go hind-and-arty, the other you pull defenses and spam as many as possible riflemen and rocketmen and tanks (or flak trucks) to act as the hammer...

Next is switch chat to all saying gghf and trade japes, team communications is more useful with bacons anyway, they gives the exact location on radar...

wait, you're those who powered radar always down? lol

**Comment by Mailaender** [comment]
> we already default to team chat at the start of the game if you have human team mates
