### ISSUE TITLE
Map edge rendering is different for observers

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#8827]
Map edges look different depending on whether RenderPlayer is null or not.
Player view:
![player-edge](https://cloud.githubusercontent.com/assets/6599106/8948378/5c5752c4-35af-11e5-94f2-6aefab73ef01.png)

Disable shroud view:
![observer-edge](https://cloud.githubusercontent.com/assets/6599106/8948386/6bb131b8-35af-11e5-9c27-315e4726bb36.png)

**Comment by pchote** [comment]
I can't reproduce this on bleed.  Please provide steps to reproduce.

**Comment by reaperrr** [comment]
Disable shroud and fog from lobby before starting a game, then it will be as described above.

**Comment by obrakmann** [comment]
Confirmed. It isn't as bad with #8792, but still buggy.

**Comment by deniz1a** [comment]
This happens when shroud is turned off in lobby.
