### ISSUE TITLE
make version doesn't work if git is not set as environment variable in Windows

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#8828]
On Windows, when I use the make command "version", it says unable to locate git. I have git installed and have local git repository. Is there a way to get the path of git.exe in the make script?

**Comment by Unit158** [comment]
This is caused by an incorrect development environment setup.

**Comment by deniz1a** [comment]
Oh ok. Does git setup ask to add it to %PATH%?

**Comment by ScottNZ** [comment]
There's no single "Git setup" on Windows, which might make this tricky to resolve. There are many different Git wrapper clients.

**Comment by obrakmann** [comment]
Not an openra issue. You can also use `make version <version>` to set a version explicitly, which doesn't require git.
