### ISSUE TITLE
Game crashes on startup

### ISSUE THREAD

**Issue by neednewsocks** [OpenRA/OpenRA#8837]
Hi all,

When I start the game on Mac OS 10.10.4 I just get a spinning wheel and I have to force quit. It was working perfectly before until I downloaded the latest stable release 20150614. I tried to download the latest mono framework and re-install but same issue.

I then deleting the opera content folder and tried but same issue. Anyone else experience this or any ideas how I can solve it?

I can't see an exceptions log file created...

Thanks,
Kerry

**Comment by pchote** [comment]
This isn't a crash, but a known issue where mono (before even running openra code) reindexes your system font caches.  Let it run for a few minutes and complete its task, then openra will run normally.
