### ISSUE TITLE
Remove weather effects from Fort Lonestar

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#8841]
```
21:46 < Yellow_TheRaffy> hey chrisf Mailänder once said he found the rain and thunder aud files in a branche of you. where did you get these files from?
21:47 <+chrisf> Yellow_TheRaffy: i dont remember
21:48 <+chrisf> Yellow_TheRaffy: i suggest you find similar files with clear provenance.
21:53 <+pchote> chrisf: we shouldn't be shipping them ourselves if we don't know their history
21:59 <+chrisf> pchote: we shouldnt be shipping them, yes.
22:00 <+chrisf> pchote: i didnt think we were -- they were just in my weather test branch
22:01 <+chrisf> i have mentioned that they needed to be replaced before
22:01 <+chrisf> this is one of the reasons i didnt propose my branch be merged
```

**Comment by TheRaffy** [comment]
Or find some sounds
<chrisf> anything CC0/CC-BY/CC-BY-SA would be fine to include

**Comment by GraionDilach** [comment]
https://www.freesound.org/people/barrygusey/sounds/134909/
https://www.freesound.org/people/hifijohn/sounds/242735/ second and fourth one
https://www.freesound.org/people/netaj/sounds/193170/

These sound appropriate. Should I convert?

**Comment by Unit158** [comment]
A pitch shift on the rain might be in order + a little reverb. It sounds synthetic atm.

**Comment by GraionDilach** [comment]
https://www.freesound.org/people/jongrubbs/sounds/202899/ then?

**Comment by Phrohdoh** [comment]
That last one sounds pretty harsh (almost too sharp) IMO. Perhaps just drop the overall volume on it, then I'd say give it a go.

**Comment by GraionDilach** [comment]
https://www.freesound.org/people/vibe_crc/sounds/50058/ if that's too harsh.

**Comment by Unit158** [comment]
That's it :sunglasses:

**Comment by GraionDilach** [comment]
The aud format itself is a lowpass filter with it's 22kHz.

**Comment by Unit158** [comment]
The sample stays well within 22kHz :)
