### ISSUE TITLE
Completely replace OpenRA.Test with OpenRA.Utility.exe or Support It

### ISSUE THREAD

**Issue by atlimit8** [OpenRA/OpenRA#8849]
It seems that `OpenRA.Test` does not provide much functionality and I have issues with running it on my system:
`dmcs -t:library -out:OpenRA.Test.dll OpenRA.Test/OpenRA.Game/*.cs -r:mods/common/OpenRA.Mods.Common.dll -r:OpenRA.Game.exe -r:nunit.framework.dll -r:System.dll -r:System.Core.dll -r:System.Data.dll -r:System.Data.DataSetExtensions.dll -r:System.Drawing.dll -r:System.Xml.dll -r:thirdparty/download/ICSharpCode.SharpZipLib.dll -r:thirdparty/download/FuzzyLogicLibrary.dll -r:thirdparty/download/Mono.Nat.dll -r:thirdparty/download/MaxMind.Db.dll -r:thirdparty/download/MaxMind.GeoIP2.dll -r:thirdparty/download/Eluant.dll && nunit-console OpenRA.Test.dll`
results in:
```
OpenRA.Test/OpenRA.Game/ActorInfoTest.cs(67,9): warning CS0219: The variable `i' is assigned but its value is never used
OpenRA.Test/OpenRA.Game/ActorInfoTest.cs(88,9): warning CS0219: The variable `i' is assigned but its value is never used
Compilation succeeded - 2 warning(s)
NUnit version 2.4.8
Copyright (C) 2002-2007 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.

Runtime Environment - 
   OS Version: Unix 4.1.3.2
  CLR Version: 4.0.30319.17020 ( 4.0.2 (Stable 4.0.2.5/c99aa0c Mon Jul 13 18:57:35 UTC 2015) )

Symbol file /tmp/nunit20/ShadowCopyCache/8873_635738788612624820/Tests/assembly/shadow/0f6609dd/157c8393_1a1a8a4e_00000001/OpenRA.Test.dll.mdb doesn't match image (null)

Tests run: 0, Failures: 0, Not run: 0, Time: 0.014 seconds


```
That probably is something with my system, but it is another possible dependency / point of failure.

**Comment by pchote** [comment]
The premise of unit tests hasn't really panned out: unit tests aren't suitable for our trait code, and nobody has shown interest in writing tests for our core engine code.  I wouldn't complain if somebody were to file a PR removing the test dll.

**Comment by RoosterDragon** [comment]
I am disinclined to see it removed.

**Comment by Unit158** [comment]
I wrote some unit test that haven't been merged as I haven't finished the implementation of proper collision testing, it would be annoying to see that work go.

**Comment by atlimit8** [comment]
@Unit158, could they be refactored to run from `OpenRA.Utility.exe` instead?

**Comment by Unit158** [comment]
Maybe. I would prefer if they weren't due to the nature of nunit, however.

**Comment by atlimit8** [comment]
What part(s) of NUnit are preferred?

**Comment by Unit158** [comment]
The assertion and profiling tools are nice.

**Comment by Mailaender** [comment]
Having not enough unit tests is not a valid reason to remove all tests. Has been rejected before in https://github.com/OpenRA/OpenRA/issues/7825.

This works fine in the IDE:

![image](https://cloud.githubusercontent.com/assets/756669/4724824/1bf9dd42-5954-11e4-9124-fcbcd3cb81f9.png)

and AppVeyor.

> NUnit version 2.4.8

Try upgrading to a recent version. We compile with NUnit 2.6.4 so the console should match that.

**Comment by pchote** [comment]
@Mailaender you're still missing the *or support it* part.  We curren't don't support this from the commandline, which means that it won't work from travis or people without a working version of monodevelop.

**Comment by Mailaender** [comment]
He is just using an ancient NUnit version. It is 2.4 is two major release behind.

**Comment by atlimit8** [comment]
I'm not against a `make nunit` - a NUnit makefile target. I could add it myself.
I use `alias m='make all && make check && make test && mono --debug OpenRA.Game.exe'` to check changes especially for rebasing and refactoring including using `... sed -i s/this/that/g ...`. It would be nice if all testing could be done from the command line.

**Comment by atlimit8** [comment]
Well, I got `dmcs -t:library -out:OpenRA.Test.dll OpenRA.Test/OpenRA.Game/*.cs -r:mods/common/OpenRA.Mods.Common.dll -r:OpenRA.Game.exe -r:nunit.framework.dll -r:System.dll -r:System.Core.dll -r:System.Data.dll -r:System.Data.DataSetExtensions.dll -r:System.Drawing.dll -r:System.Xml.dll -r:thirdparty/download/ICSharpCode.SharpZipLib.dll -r:thirdparty/download/FuzzyLogicLibrary.dll -r:thirdparty/download/Mono.Nat.dll -r:thirdparty/download/MaxMind.Db.dll -r:thirdparty/download/MaxMind.GeoIP2.dll -r:thirdparty/download/Eluant.dll && nunit2-console OpenRA.Test.dll` working.

Should I add the `nunit` makefile target? I suspect something like `nunit2-console OpenRA.Test.dll || nunit2-console OpenRA.Test.dll` or `NUNIT = $(which nunit-console || which nunit2-console)` will be needed for protability and possibly `pkg-config --libs`.

**Comment by atlimit8** [comment]
Should NUint be added to https://github.com/OpenRA/OpenRA/wiki/Compiling?

**Comment by Mailaender** [comment]
Documenting the dependency definitely won't hurt.

> We currently don't support this from the commandline, which means that it won't work from travis

It will work from Travis http://docs.travis-ci.com/user/languages/csharp/#Running-unit-tests-(NUnit%2C-xunit%2C-etc.) However enabling that would be redundant to AppVeyor which also stores the results nicer.

**Comment by atlimit8** [comment]
I have been having problems using a copy of NUnit downloaded to the thirdparty directory, but I might try again.

**Comment by Mailaender** [comment]
Try

`nunit-console OpenRA.Test.dll`

then open `TestResult.xml`:

```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!--This file represents the results of running a test suite-->
<test-results name="OpenRA.Test.dll" total="0" failures="0" not-run="0" date="2015-10-17" time="16:24:30">
  <environment nunit-version="2.4.8.0" clr-version="4.0.30319.17020" os-version="Unix 3.16.7.24" platform="Unix" cwd="/home/matthias/Entwicklung/OpenRA" machine-name="mPad-X230.site" user="matthias" user-domain="mPad-X230.site" />
  <culture-info current-culture="de-DE" current-uiculture="de-DE" />
  <test-suite name="OpenRA.Test.dll" success="True" time="0.018" asserts="0">
    <results>
      <test-suite name="OpenRA" success="True" time="0.016" asserts="0">
        <results>
          <test-suite name="Test" success="True" time="0.015" asserts="0">
            <results>
              <test-suite name="ActorInfoTest" success="True" time="0.000" asserts="0">
                <results />
              </test-suite>
              <test-suite name="CoordinateTest" success="True" time="0.000" asserts="0">
                <results />
              </test-suite>
              <test-suite name="MiniYamlTest" success="True" time="0.000" asserts="0">
                <results />
              </test-suite>
              <test-suite name="OpenRA" success="True" time="0.001" asserts="0">
                <results>
                  <test-suite name="Game" success="True" time="0.001" asserts="0">
                    <results>
                      <test-suite name="ActionQueueTest" success="True" time="0.000" asserts="0">
                        <results />
                      </test-suite>
                    </results>
                  </test-suite>
                </results>
              </test-suite>
              <test-suite name="OrderTest" success="True" time="0.000" asserts="0">
                <results />
              </test-suite>
              <test-suite name="PlatformTest" success="True" time="0.000" asserts="0">
                <results />
              </test-suite>
            </results>
          </test-suite>
        </results>
      </test-suite>
    </results>
  </test-suite>
</test-results>
```

**Comment by atlimit8** [comment]
It's downloading a working NuGet package that gave me problems. I installed a newer version on my system and got `make nunit` working. The problem is with downloading to and using NUnit from `thirdparty/download`
