### ISSUE TITLE
Tall buildings: Cannot repair or sell building above

### ISSUE THREAD

**Issue by Alex2395** [OpenRA/OpenRA#8857]
There seems to be an issue with tall buildings (Tesla Coil, Advanced Guard Tower, Allied AA Gun, etc.). I didn't manage to repair or sell a building that I placed directly above it. These tall defense buildings seem to have a larger "selectbox" or whatever. Also I cannot order units to position above them.
I wonder why I couldn't find a ticket already addressing this issue.
Version: current master branch

**Comment by obrakmann** [comment]
This was fixed with #8388, which is already in the current playtest.
