### ISSUE TITLE
Defeated player's buildings should be removed from fog

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#8864]
When a player is defeated, all its frozen images should be removed from fog of war.
##

**Comment by abcdefg30** [comment]
This can be easily done with the trait introduced in #8797.

**Comment by pchote** [comment]
I disagree with this: the frozen actors represent the state that a player last saw the world.  If we start arbitrarily removing things from that then we open up inconsistencies with e.g captured structures (including tech structures) and arguments about other cases that should also be removed.

I'm going to close this as a wontfix, but of course others are free to object and reopen this.
