### ISSUE TITLE
Terrain Geometry Overlay does not respect heightmaps.

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#8871]
![screen shot 2015-08-01 at 9 11 25 am](https://cloud.githubusercontent.com/assets/4861023/9022119/773d8952-382d-11e5-9d39-c05bcec3520f.png)

**Comment by pchote** [comment]
Not a bug.  The blue cells show the projected cells that cover the currently highlighted cell (the bottom one in the power footprint, which has the wider orange line).  That part of the terrain is at an odd height level, so the projected cells are staggered with respect to the ground.

**Comment by Phrohdoh** [comment]
So the cells ought to be staggered in the opposite direction, in my opinion.
It may not be a bug, but it isn't visually pleasing or helpful. It is inaccurate.

**Comment by pchote** [comment]
I'm not sure what you expect it to look like, but this has nothing to do with the building placement preview (if that is what is confusing you).  This is showing the projection of the current mouse cell to the projected (shroud) space.
