### ISSUE TITLE
Music in Dune 2000 and Tiberian Sun is gone

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#8884]
It displays "No music installed" although the .aud and scores.mix are in place.

**Comment by pchote** [comment]
Does it come back after a restart or five?

I've had this happen in RA and TS.

**Comment by Mailaender** [comment]
For Dune 2000 it is AUD filename a case-sensitivity issue.

**Comment by Mailaender** [comment]
@dan9550 noticed it over a week ago and filed https://github.com/OpenRA/OpenRA/issues/8884 so I guess this must have regressed around that time. Not sure where and when yet.
