### ISSUE TITLE
Add multi palette support for tilesets.

### ISSUE THREAD

**Issue by MigEater** [OpenRA/OpenRA#8885]
I request the ability to use custom pallets within each tileset, with something like this for example.

	Templates:
		Template@0:
			Palette: isotem.pal

		Template@1:
			Palette: isosno.pal 

This would greatly expand the possibilities of custom terrain for 3rd party mods.

**Comment by pchote** [comment]
This would be reasonably straightforward: change the `TerrainSpriteLayer` in `TerrainRenderer` to a `Dictionary<PaletteReference, TerrainSpriteLayer>` like I did for `ResourceLayer` in #8649.

**Comment by epicelite** [comment]
Can we use this to combine 2 different pallets into one? I'd like to see a map with a desert, temperate, and tundra islands.

**Comment by Phrohdoh** [comment]
@epicelite this wouldn't combine palettes as that doesn't make sense, but it would allow the use of multiple.

**Comment by Mailaender** [comment]
@gangster-ppm also asked for this.

**Comment by gangster-ppm** [comment]
Awaiting it beeing merging :+1:
