### ISSUE TITLE
Palette error on orca bomb water (splash) effect

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#8898]
on TEMPERAT tileset.

**Comment by GraionDilach** [comment]
All water splash effects used player palette in TS. They probably are using effect right now.

**Comment by reaperrr** [comment]
Actually, judging by a quick glance at some weapons, this probably affects all weapons on both tilesets. The explosions were set up before we had any maps with water, so this went unnoticed before.
