### ISSUE TITLE
Suggestion: Connect the web pages

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/OpenRA#8904]
Hey, I noticed that there are alot sub pages and they are not connected enough in my opinion.
I suggest to add a link to gamereplays.org at the resource center
and also to add the resources center at the navigation bar of the main page.

This could boost value of these sub pages.

**Comment by deniz1a** [comment]
There are links to resource center and gamereplays here:
http://www.openra.net/community/

**Comment by TheRaffy** [comment]
I know, and think they are too hidden.

**Comment by deniz1a** [comment]
Oh ok. Yes it would be better if resource center had a more prominent link.

**Comment by Unit158** [comment]
Please post this in Openra/OpenRAWeb

**Comment by Mailaender** [comment]
See also https://github.com/OpenRA/OpenRA-Resources/issues/260.
