### ISSUE TITLE
Refactor UI to better support TS

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#8919]
TS used cameo.pal for icons, but sidebar.pal for clock animation (gclock2.shp), and darken.shp to darken icons when that item currently wasn't buildable (build limit reached, something else in production etc.).

Our current setup is a mostly-hardcoded mess:
Taking `ProductionPaletteWidget` as primary example, `clock` animation name is hardcoded, sequence `idle` is hardcoded, and it's hardcoded to use the same palette as the icon of that actor (which can be problematic for modders that use multiple icon palettes).
`cantBuild` (equivalent of TS darken) is hardcoded to Animation `clock`, sequence `idle` and sequence frame index 0. 
And finally, `ShadowIndex: 255` doesn't seem to work on palettes, likely the same issue as #8596 (making TS' `darken.shp` unusable for its intended purpose).

**Comment by LipkeGu** [comment]
also this problem is on RA2 (or will be)

**Comment by reaperrr** [comment]
This has been adressed by #9129.

**Comment by GraionDilach** [comment]
Not entirely, observer production clocks are still hardcoded, see #9220.
