### ISSUE TITLE
Edge scrolling not disabled while dragging in map editor minimap

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#8924]
In map editor, drag the viewport in minimap towards the right and top edge of the screen. Edge scrolling moves the screen even when mouse doesn't move. This doesn't happen in game.
##

**Comment by rob-v** [comment]
@deniz1a I can't reproduce it. Could you try again?

**Comment by PunkPun** [comment]
This happens because there's a gap between minimap and edge of the screen, so when your mouse exits the minimap and goes to the corner it uses normal panning behaviour.

I call this a non-issue
