### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#8926]
Compiling bleed looks like this:
![compile](https://cloud.githubusercontent.com/assets/6599106/9049816/0df3ed6e-3a4f-11e5-800b-851885aede54.png)

**Comment by penev92** [comment]
Are you *sure* this is bleed? Travis would have errored on those.
Also I don't get any warnings.

**Comment by Unit158** [comment]
This is because of Nunit, in which this will preform correctly.

**Comment by deniz1a** [comment]
This looks fixed now, I don't get any warnings.
