### ISSUE TITLE
Utility's output takes up too much vertical space.

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#8930]
![screen shot 2015-08-03 at 7 18 44 pm](https://cloud.githubusercontent.com/assets/4861023/9050577/c44635d0-3a14-11e5-8f64-22dcacb11936.png)

I can't even see the output of the previous commands, or the first few commands.

**Comment by Unit158** [comment]
One solution is to pipe it to less, but a dedicated help command or something would be nice.

**Comment by chrisforbes** [comment]
Just pipe to a pager. Don't reinvent that wheel.

On Tue, Aug 4, 2015 at 12:25 PM, Christopher Grant <notifications@github.com

**Comment by Unit158** [comment]
@chrisforbes I was thinking of not showing the needlessly verbose options when you just type in the name & mod like that.

**Comment by penev92** [comment]
That nice formatting is actually quite the improvement over what we had before.
How does one even run out of vertical space on a modern computer?

**Comment by pchote** [comment]
Is this a wontfix?

**Comment by Unit158** [comment]
i dont think this is a wontfix, but not very high priority.

**Comment by penev92** [comment]
:-1: to reverting the PR that made this nice and readable and going back to the old hard to read bunch of letters.
Other than that I don't mind it either way.

**Comment by atlimit8** [comment]
:-1:
Using a pager is a fairly basic skill for using command line interfaces. Even Windows has `more`.
One can type: *...*`OpenRA.Utility.exe `*mod*`|more` in the most common command line shells of Linux, Mac OSX, and Windows.

I vote that this be closed.
