### ISSUE TITLE
DeployToUpgrade does not provide any animations or sounds.

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#8932]

**Comment by penev92** [comment]
[Proof of the oposite](http://i.imgur.com/pBfXvvA.gif).

**Comment by Unit158** [comment]
Note: the above is not currently in bleed.

**Comment by Mailaender** [comment]
So are you going to add it? At the moment `DeployToUpgrade` is completely unused.

**Comment by Mailaender** [comment]
I did experiments https://github.com/Mailaender/OpenRA/compare/change-sequence some time ago.
