### ISSUE TITLE
Minimap opens several times when surrendering

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#8935]
(This gif loops unfortunately, but the minimap opens at least twice.)
![minimapopenb](https://cloud.githubusercontent.com/assets/7704140/9058706/93099ce8-3aa3-11e5-9665-5dc1057a145f.gif)

**Comment by pchote** [comment]
This is a regression from the last release, so we should fix it before the next.
I suspect #8105 to be the cause.

**Comment by deniz1a** [comment]
I can't reproduce this in bleed.

**Comment by pchote** [comment]
It is easy to reproduce.  Start a skirmish with more than 2 teams, then immediately surrender.

**Comment by deniz1a** [comment]
Reverting a77e9c0 fixes this.

**Comment by pchote** [comment]
Adding a guard so that it only queues/executes that RunAfterDelay once will be sufficient.
