### ISSUE TITLE
Cyborg commando plasma will fly forever

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#8959]
I was fooling around with TS and noticed that if you fire plasma at the correct location with a bunch of cyborgs, it will fly in a loop and never hit its target.

**Comment by Unit158** [comment]
I can't seem to reproduce this as it has to hit a very specific target, it seems.

**Comment by reaperrr** [comment]
When `RangeLimit` was measured in ticks, the default was 'unlimited', and the CyCannon didn't define a custom `RangeLimit`. The refactor to WDist has adressed that by defaulting to weapon range.
