### ISSUE TITLE
Actors belonging to the Neutral player reveal fog and shroud for spectators

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#8961]
Happens when you select the "All Players" visibility option, and my guess is it's pretty new.

**Comment by obrakmann** [comment]
Looks like that was my fault again: git bisect found fc8a34a7a2684dbe317e6dc25a4b7ccde65812e1

**Comment by Mailaender** [comment]
Proposed fix at https://github.com/OpenRA/OpenRA/issues/8964.
