### ISSUE TITLE
Lua exception dialog no longer works properly

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#8962]
The PR that removed the forced end-game screen regressed our handling of script errors.

The game will now throw up the regular game menu when the script crashes, with the error message showing as plain text below the center panel tabs (which are visually more prominent, so make the error less obvious).  The player can return to the game which then remains paused with no obvious indication why.

The return to game button should be disabled if the game was ended due to a script error, and the briefing tab should be hidden so that the error message takes priority.

**Comment by deniz1a** [comment]
Why should return to map button be disabled if there was a script error?

**Comment by penev92** [comment]
To make it crystal clear that the game broke.

**Comment by deniz1a** [comment]
What if I want to look at the map? The error message could be displayed in a more obvious way.

**Comment by Phrohdoh** [comment]
@deniz1a Then look at the map in the map editor. That isn't the point of this issue.

**Comment by pchote** [comment]
Prior to #8105 we had an unambiguious error dialog:
![luaerror](https://cloud.githubusercontent.com/assets/167819/9106004/89ce98fa-3c14-11e5-8d47-68d30a655f5a.png)

Afterwards it is now hidden as a modified objective:
![luabriefing](https://cloud.githubusercontent.com/assets/167819/9106013/9cef9b8c-3c14-11e5-8313-f332f7acd488.png)

This change has already caused confusion, with @OmegaBolt reporting on IRC a "bug where I can't unpause" the game because he didn't notice the lua exception.
