### ISSUE TITLE
Replay hotkeys for pause/play/speed

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#8972]
More convenience to an already damn good replay viewer. I'm looking through tons of replays searching for that special shot. A simple set for hotkeys (preferably customizable) would make the experience that much better. I think one hotkey for play/pause and one for increase/decrease speed would be the most convenient.

**Comment by pchote** [comment]
Good idea, and this should be relatively easy.

**Comment by StexoO** [comment]
I just hit [Space] to pause a replay, like in any video player, but nothing happened. :disappointed_relieved: 
So :+1:

**Comment by SoScared** [comment]
#10933 looks good.
