### ISSUE TITLE
Equalize Soviet and Allies 'building' tab for easier hotkey configuration.

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#8973]
Getting to know the hotkeys for buildings in RA is a little too hazardous if you switch between factions now and then. Hotkeys are now assigned to 'slots' and so could it not be an idea to give the factions an equal 'building' slot design? All the TD and D2K factions share the same 'building' slot design which invites the player to learn them faster.

The Soviet Kennel push the entire 'building' tab +1 spot off the Allies' design:
![buildtabs3](https://cloud.githubusercontent.com/assets/2715583/9121143/b7b696f2-3c80-11e5-8fc9-73021c90629f.png)

Other tabs differs as well off course (defense, infantry etc.) but that doesn't look like trouble.

**Comment by Unit158** [comment]
This should be done :D

**Comment by deniz1a** [comment]
Why not remove kennel and train dogs in barracks?

**Comment by penev92** [comment]
:+1: I like it!
I think the naval stuff can go after war factory or even radar though.

**Comment by pchote** [comment]
Bare in mind that our icon layout is chosen so that prerequisites are unlocked continuously: each tech step unlocks icons immediately to the right or below it.  It makes sense to break this rule for the kennel to make allies vs soviets consistent, but I recommend not making any other changes.

**Comment by penev92** [comment]
Here's an unrelated idea - put naval stuff on the ref, not on power plants. That way you get them at the same time you get the war factory.

**Comment by pchote** [comment]
That would have implications for island maps where you might want to use an engineer + transport to go derrick hunting.

**Comment by cjshmyr** [comment]
:+1:

**Comment by MicroJOo** [comment]
:+1:
