### ISSUE TITLE
Vehicle Move animation freeze after perform attack.

### ISSUE THREAD

**Issue by TGHoly** [OpenRA/OpenRA#8977]
I have test TS mod on bleed version of openra and try mod something on it but I notice this problem which not only happen on my unit but also effect with official unit like Wolverine.

Unit move animation work fine until I order him to attack then their move animation become freezing and can't recover for entire game. 

![img](http://i55.photobucket.com/albums/g152/Holy_Master/mastodon_glitch_zpsp0nvmqj9.gif)

[info]
- Unit still able to switch animation base on their activity .
- As if unit away stuck at first frame of move animation on each direction .
- My unit use similar code to Openra Wolverine.
- Wolverine also suffer from this glitch
- Not sure if Vehicle with turret also effect by this but Titan doesn't seem to effect with this bug..
- This bug not effect with Titan not sure if it effect only with non-turret vehicle.

**Comment by Mailaender** [comment]
Why are there 2 mouse cursors in the video? Is that another glitch?

**Comment by GraionDilach** [comment]
I'd assume it's the recorder software being off.

**Comment by TGHoly** [comment]
it just from recording program which no need to care about. :p

**Comment by Mailaender** [comment]
Can you verify https://github.com/OpenRA/OpenRA/issues/8988 fixes it for you?

**Comment by TGHoly** [comment]
ah yes seem like it's same problem.
