### ISSUE TITLE
OpenRA.Utility.exe Color Picker

### ISSUE THREAD

**Issue by atlimit8** [OpenRA/OpenRA#8984]
Parse in the form *base_color* `,` *saturation* `,` *lightness* `,` *alpha* and output rgb[a]/hsl[a].
Where:
  * *base_color* is one of:
    * `rgb` `,` *red* `,` *green* `,` *blue*
    * [`hsl` `,`] *hue* : HSL (hue, saturation, lightness) values (*hue*, 255, 255)
    * *knownColor* : parsed by `Enum<KownColor>.TryParse` (See System.Drawing.KnownColor)
  * *saturation* is multiplied by *base_color* saturation to get the final saturation (colourfulness - 0 is grey)
  * *lightness* is multiplied by *base_color* lightness to get the final lightness (brightness - 0 is black)
  * *alpha* is the opacity/alpha channel

Options for shortening:
  * Default missing to 255 filling from alpha. Ex: `Blue, 127` is blue with 50% opacity/alpha
    * This would allow for using rgba semantics like `rgb, 0, 0, 255, 127` to represent blue with 50% opacity/alpha
  * Default empty to 255. Ex: `Blue, , , 127` is blue with 50% opacity/alpha
    * The number of components is more deterministic

Since there have been remarks about the HSL used by OpenRA being counterintuitive, this might help:
  * Component text: *numerator* `/` *denominator*
    * Component value = `255 *` *numerator* `/` *denominator*
    * Except *hue* is `256 *` *numerator* `/` *denominator*
    * Allows for `hsl, 180/360, 50/100, 50/100`
  * Component text: *percentage* `%`

**Comment by pchote** [comment]
This feels like a really overcomplicated solution for what we need.  I don't see why the game needs to worry about this - A utility command that lets people convert RGB &harr; HSL would be much simpler.

**Comment by atlimit8** [comment]
That sounds like a reasonable alternative; however, KnownColor conversions should also be included then. The other stuff would also be helpful. Perhaps even adding `x%` as well.

**Comment by pchote** [comment]
The could be included in the utility, but I don't think they should be included in our core color parsing.

**Comment by Unit158** [comment]
I don't feel a converter in the utility would really suffice. I'd rather have an html page included with our distribution that includes a display of the colour selected and possibly a colour picker. it would also do the conversions. This could probably also be put (ported) in the map editor at some point.

Especially for UX, I believe that proper tools such as ^ are in order. I'd be happy to make it too, given the number of js libs out there it would probably be pretty simple.

**Comment by Phrohdoh** [comment]
:-1: for separating tooling into the utility *and* an html page.

**Comment by Unit158** [comment]
Well, I'm going to say :-1: for utility only. I want to do this in a UI, not have to use some other tool to find the colour I like then put it into another tool.

**Comment by atlimit8** [comment]
Perhaps it could be added like the Asset Browser.

**Comment by atlimit8** [comment]
Actually, a "Color Picker" (like "Asset Browser") could share code with a utility command allowing access to the same converter from both a GUI, with point and click options, and the command line.

**Comment by Phrohdoh** [comment]
While it isn't optimal, you can use the player color picker to get valid HSL values (in settings.yaml), so that code could be reused in a general color-picker.

**Comment by atlimit8** [comment]
I thought of the same thing.
