### ISSUE TITLE
Unified MiniYaml Color Syntax

### ISSUE THREAD

**Issue by atlimit8** [OpenRA/OpenRA#8986]
Currently, MiniYaml parses `Color` using [a]rgb format and `HSLColor` using hsl[a] format.
They should be one of these:
  * *red* `,` *green* `,` *blue* [`,` *alpha*]
  * *hue* `,` *saturation* `,` *lightness* [`,` *alpha*]
  * Either by prefix:
    * `hsl,` *hue* `,` *saturation* `,` *lightness* [`,` *alpha*]
    * `rgb,` *red* `,` *green* `,` *blue* [`,` *alpha*]

**Comment by Phrohdoh** [comment]
I don't understand what you're proposing.
Parse HSLColor with HSL and Color with RGB?

**Comment by atlimit8** [comment]
No, both with the *same* format or accept both formats for each.

**Comment by Phrohdoh** [comment]
How are the formats different in the eyes of modders?
You have 3 required fields and 1 optional currently and in your suggestion, from my understanding.

**Comment by atlimit8** [comment]
Except, `Color` type fields currently use [a]rgb while `HSLColor` type fields currently use normalized hsl.

**Comment by atlimit8** [comment]
This is so that they don't have to know if the field is of type `Color` or `HSLColor` by having `FieldLoader` parse input the same channel format for both.

**Comment by Phrohdoh** [comment]
But they should know the difference as they are entering different color-space values and may get unintended colors if we don't warn/fail on them.

**Comment by atlimit8** [comment]
The purpose this is to make that not an issue by using the same color-space input for both types.

**Comment by atlimit8** [comment]
Conversion would be used as needed for the underlying type `Color` or `HSLColor`.

**Comment by atlimit8** [comment]
Another option would be to use either `Color` or `HSLColor` exclusively.

**Comment by pchote** [comment]
Accepting the third option as valid input for both Color and HSLColor sounds good to me.  Note that this won't impact the normalized hsl vs conventional hsl confusion.

**Comment by atlimit8** [comment]
If the third option is used, should the old formats be parsed with a deprecation warning for a while?
