### ISSUE TITLE
Move asset installation code and UI into the mod chooser.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#8990]
The original plan for our mod chooser has always included asset management, but this second phase has not yet happened.  This is going to be a relatively big job to do fully, but this is a simple first step to get the ball rolling.

I expect the following steps to be involved:
* Cache the `ContentInstaller` mod data inside the `ModMetadata` objects that are read at game start.
* Move the mod installation check from `BlankLoadScreen` to `ModBrowserLogic`, and run it when selecting a new mod in the UI.
* Replace the "Play" button text in the mod chooser with "Install" if installation is required, and open the installation dialog instead of launching the mod.
* Keep a check for missing content in `BlankLoadScreen`, but return to the mod chooser if it fails instead of showing a dialog.
* Adjust the music installation code to also go via the mod chooser.
* Adjust the dialog theme to fit our website-inspired UI.

**Comment by Mailaender** [comment]
We can then also stop shipping the relatively large mouse sprites.

**Comment by LipkeGu** [comment]
We could also integrate an dropdown list for expansion packs 

when i select TS it would show a list of custom mods whish requires this mod to work.

**Comment by pchote** [comment]
@LipkeGu: that is covered by #8991.
