### ISSUE TITLE
Add mod / engine version dependencies.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#8991]
There is currently no programmatic way for mods to declare what engine version they support.  This causes confusion for players who install outdated mods that then crash.

We can combine this with a mechanism for supporting proper expansion mods to prevent duplication and add support for game expansions like YR to RA2 (as there has been a lot of hostility to the idea of integrating YR into @Phrohdoh's unofficial RA2 mod).

I suggest doing the following:
* Add a `RequiresMods:` block to mod.yaml.  A hypothetical YR mod that extends a standalone RA2 mod could, for example, declare
```yaml
RequiresMods:
	common: release-20170104
	ra2: 3.0-beta
```
* Add a mod.yaml to the `common` mod dir that supersedes our `all` development mod and stores the "core" engine version.
* Add checks to `ModBrowserLogic` to ensure that the declared mods are available and have their assets installed (depends on #8990).  Display a warning and disable the play button if they are not all available.

**Comment by Phrohdoh** [comment]
I am very much behind this proposal in its entirety. :+1:

As an aside I am willing to work on YR (when the time comes) and this would make it much easier to develop YR on top of the existing RA2 because (as noted) I do not plan on them being released together.

**Comment by LipkeGu** [comment]
also Firestorm can use this logic.

**Comment by Unit158** [comment]
Firestorm can use our existing logic, but I see no need to separate TS and FS
