### ISSUE TITLE
Aircraft have wrong minimap cursor

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#9009]
Planes have attack cursor for airfields and helicopters for helipad. When clicked, they land and don't attack it.
##

**Comment by penev92** [comment]
I tested aircraft on yesterday's bleed not 12 hours ago, so I'll need a lot more context here.

**Comment by deniz1a** [comment]
Context: current bleed. minimap cursor.

**Comment by deniz1a** [comment]
Select a plane. move cursor over own airfield in minimap. Cursor changes to attack. It should be landing cursor.

**Comment by deniz1a** [comment]
Actually they don't even have the correct attack cursor, it's a broken version of that. And this is not only for aircraft but for the rearm/repair/give supply cursor in general. What's the name of that cursor?

**Comment by fruestueck** [comment]
Bug confirmed on Releasse-180218. It does show wrong minimap cursers of multiple units and tasks.
Engeneer works (infiltrate on Map and on Minimap correct).

This bug (or yet not implemented distinction) concerns Air Units, Vehicles (Repair symbol), Spys & Mechanics (infiltrate), Ships (Repair symbol on own yard when damaged) and more. See example picture

![unbenannt](https://user-images.githubusercontent.com/25386322/37053235-df647c4a-217b-11e8-91bc-1044f0733d47.png)

Issue title could be changed (e.g. "wrong minimap icons")

**Comment by matjaeck** [comment]
The comment above is also valid for release-20190314.

**Comment by PunkPun** [comment]
This is no longer an issue
