### ISSUE TITLE
Crushing walls with Mammoth tanks doesn't work (anymore)

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#9011]
See http://resource.openra.net/maps/4045/ for a test map with enemy owned walls.

**Comment by pchote** [comment]
All four mods have the same basic setup for walls (which is kind of redundant in D2K, since nothing crushes them).  Are you sure this only affects TD?

**Comment by Mailaender** [comment]
I guess this is broken for a longer time, because I never saw wall crushing and thought it was TD exclusive. Adding it to D2k to make the Deviator look more badass might be an interesting idea.

**Comment by pchote** [comment]
I bet this is another regression from #8866.  See also #9013.

**Comment by Mailaender** [comment]
Confirmed. That fixes it.
