### ISSUE TITLE
Units don't enter Buildings with the Cargo Trait

### ISSUE THREAD

**Issue by Biofreak1987** [OpenRA/OpenRA#9013]
To test this, either assign a Building with the Cargo Trait or empty a pillbox in red alert. The enter Arrow will display but the Unit refuses to enter the Building.

**Comment by pchote** [comment]
This is another regression caused by the incorrect `IPositionalble` query in the IsAtGroundLevel check.  That needs to be `IOccupySpace` instead.  I noticed that yesterday while debugging another issue

http://logs.openra.net/index.php?year=2015&month=08&day=08#17:33:22
