### ISSUE TITLE
Playtest skirmish crash

### ISSUE THREAD

**Issue by clemty** [OpenRA/OpenRA#9033]
playtest-20150808

my orca and an AI orca killed each other, then the AI initiated an airstrike. Game was unresponsive for a few seconds, then crashed back to desktop (win7)

replay file: http://www.pipelinestall.org/stuff/OpenRA-2015-08-11T094144Z.orarep

**Comment by penev92** [comment]
Can you please post the exception as well?

**Comment by RoosterDragon** [comment]
That replay file fails to parse and so doesn't show up in the browser for me - it might be corrupt if the crash was sudden (assuming nobody else and can load it and it's not just me being dumb).

**Comment by pchote** [comment]
The replay browser and version checks require the metadata block that is written to the end of the replay at game end.  That isn't written when the game crashes, but it is possible to force playback by adding a dummy block or hacking out the metadata checks in the game.

**Comment by clemty** [comment]
>Can you please post the exception as well?

[10:19:33]	<clemmy> pchote: that's usually exception.log or smthn? no such file. the two newest files after the crash were debug.log and perf.log, I still have the debug.log but it doesn't look unusual

**Comment by pchote** [comment]
I fixed the replay, but can't play it because the map (hash: `c4ab8b7074ff016e8b88cebcbccc01c56acf4427`) is not shipped with the game or available on the resource center.

**Comment by LipkeGu** [comment]
@clempty: can you upload the map?

**Comment by clemty** [comment]
I don't have access to the machine it crashed on until later this week.
I didn't install any custom maps, so it is strange that the hash does not match; I'll investigate further but currently I'm leaning towards closing this as "could not reproduce"

**Comment by clemty** [comment]
>What map were you using?

I was using the shipped "The Sentinel" map - I uploaded the file to http://www.pipelinestall.org/stuff/thesentinel.oramap

`openra.utility` reports the hash as `c4ab8b7074ff016e8b88cebcbccc01c56acf4427`

**Comment by penev92** [comment]
@pchote if you don't have the time, consider uploading the fixed replay, and maybe someone else will take a look.

**Comment by LipkeGu** [comment]
i will test this map...

**Comment by LipkeGu** [comment]
```
Tiberian Dawn Mod at Version {DEV_VERSION}
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IndexOutOfRangeException`: Der Index war au..erhalb des Arraybereichs.
   bei System.Array.Clear(Array array, Int32 index, Int32 length)
   bei OpenRA.Mods.Common.Widgets.RadarWidget.Tick()
   bei OpenRA.Widgets.Widget.TickOuter() in D:\Wichtig\Projekte\OpenRA\OpenRA.Game\Widgets\Widget.cs:Zeile 430.
   bei OpenRA.Widgets.Widget.TickOuter() in D:\Wichtig\Projekte\OpenRA\OpenRA.Game\Widgets\Widget.cs:Zeile 432.
   bei OpenRA.Widgets.Widget.TickOuter() in D:\Wichtig\Projekte\OpenRA\OpenRA.Game\Widgets\Widget.cs:Zeile 432.
   bei OpenRA.Widgets.Widget.TickOuter() in D:\Wichtig\Projekte\OpenRA\OpenRA.Game\Widgets\Widget.cs:Zeile 432.
   bei OpenRA.Widgets.Widget.TickOuter() in D:\Wichtig\Projekte\OpenRA\OpenRA.Game\Widgets\Widget.cs:Zeile 432.
   bei OpenRA.Widgets.Widget.TickOuter() in D:\Wichtig\Projekte\OpenRA\OpenRA.Game\Widgets\Widget.cs:Zeile 432.
   bei OpenRA.Widgets.Widget.TickOuter() in D:\Wichtig\Projekte\OpenRA\OpenRA.Game\Widgets\Widget.cs:Zeile 432.
   bei OpenRA.Widgets.Widget.TickOuter() in D:\Wichtig\Projekte\OpenRA\OpenRA.Game\Widgets\Widget.cs:Zeile 432.
   bei OpenRA.Widgets.Ui.Tick() in D:\Wichtig\Projekte\OpenRA\OpenRA.Game\Widgets\Widget.cs:Zeile 73.
   bei OpenRA.Sync.<>c__DisplayClass13_0.<CheckSyncUnchanged>b__0() in D:\Wichtig\Projekte\OpenRA\OpenRA.Game\Sync.cs:Zeile 170.
   bei OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn) in D:\Wichtig\Projekte\OpenRA\OpenRA.Game\Sync.cs:Zeile 187.
   bei OpenRA.Sync.CheckSyncUnchanged(World world, Action fn) in D:\Wichtig\Projekte\OpenRA\OpenRA.Game\Sync.cs:Zeile 170.
   bei OpenRA.Game.InnerLogicTick(OrderManager orderManager) in D:\Wichtig\Projekte\OpenRA\OpenRA.Game\Game.cs:Zeile 444.
   bei OpenRA.Game.LogicTick() in D:\Wichtig\Projekte\OpenRA\OpenRA.Game\Game.cs:Zeile 507.
   bei OpenRA.Game.Loop() in D:\Wichtig\Projekte\OpenRA\OpenRA.Game\Game.cs:Zeile 631.
   bei OpenRA.Game.Run() in D:\Wichtig\Projekte\OpenRA\OpenRA.Game\Game.cs:Zeile 671.
   bei OpenRA.Program.Run(String[] args) in D:\Wichtig\Projekte\OpenRA\OpenRA.Game\Support\Program.cs:Zeile 111.
   bei OpenRA.Program.Main(String[] args) in D:\Wichtig\Projekte\OpenRA\OpenRA.Game\Support\Program.cs:Zeile 39.

```

**Comment by LipkeGu** [comment]
This Crash is related to the Triangle on the minimaps Radasignature. It seems the Radarwidget tries to update invalid Cells on the Minimap.
