### ISSUE TITLE
Repulsion prevents helicopters from landing on helipad

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#9035]
When you have more than 1 helicopter selected and order them to enter a helipad, the heli who reserves the pad more often than not won't be able to land because repulsion from the surrounding helicopters prevents that.

**Comment by MicroJOo** [comment]
confirmed

**Comment by GraionDilach** [comment]
Was that confirmation in latest bleed? The aircraft-terrain-height PR resulted with Starcraft I-like stacking of helis - not just like RA2, where they can be stacked during moving but they also stack after stopped/attacked.

**Comment by MicroJOo** [comment]
i only know it from our current release ...

**Comment by penev92** [comment]
Yes, having them land on bleed is hard-at-best. Also the aircraft repulsion should prevent any stacking.

**Comment by pchote** [comment]
Fixed by #11393.
