### ISSUE TITLE
Enemy health bars show up above shroud in the 20150808 playtest

### ISSUE THREAD

**Issue by CountHanx** [OpenRA/OpenRA#9037]
![openra-2015-08-10t160249z](https://cloud.githubusercontent.com/assets/13749527/9199343/2e60b232-4042-11e5-9dc8-a81d551369e2.png)

This was a normal skirmish game against bots in Tiberian Dawn. I think it was also present in the previous playtest, but I'm not 100% sure. I had the "Always Show Status Bars" option enabled.

**Comment by deniz1a** [comment]
This could be fixed together with #8758.

**Comment by deniz1a** [comment]
I can't reproduce this in bleed.

**Comment by penev92** [comment]
Reproduced on bleed.
Seems like fog hides health bars, but shroud doesn't. So to reproduce - turn fog off in the lobby.

**Comment by cjshmyr** [comment]
Seems to only check fog visibility here: https://github.com/OpenRA/OpenRA/blob/bea021a069fa3f80a55539924899d3f4fe7f8127/OpenRA.Game/Graphics/WorldRenderer.cs#L186 - I wonder if this check always behaved this way?

**Comment by pchote** [comment]
The internals of `FogObscures` completely changed as part of the shroud rework / gps fixes.  This must be hitting some strange edge case.

**Comment by pchote** [comment]
`FrozenUnderFog.IsVisible` is missing a shroud check. Compare with `HiddenUnderFog`.
