### ISSUE TITLE
Lua scripted SupportPower subclass or Lua countdown clocks for SupportPowerTimerWidget

### ISSUE THREAD

**Issue by atlimit8** [OpenRA/OpenRA#9042]
Two ways:
- Lua scripted `SupportPower` subclass:
  - Requires `SupportPower` subclass trait on actor (can be Player, maybe World).
  - Can use other `SupportPower` features such as radar pings.
  - Can allow player to click to activate.
  - There will need to be a way for Lua code to link to the trait.
- Lua countdown clocks for `SupportPowerTimerWidget`:
  - Requires changes to `SupportPowerTimerWidget` to support two types of countdown timers.
  - Can use a simple Lua interface: `UserInterface.CreateCountdownTimer(DateTime.Minutes(10), function() ... end[, HSLColor.Blue])`.

Uses:
- Allies 02 - convoy clock.
- Monster Tank Madness - super tanks' self-destruct timer.
  - `UserInterface.CreateCountdownTimer(selfDestructCount, SelfDestruct, TimerColor)`
- Survival 01
- Survival 02

Uses (`SupportPower` subclass only):
- Custom support powers via Lua.
##

**Comment by abcdefg30** [comment]
We can display custom text via Lua for a while now, so I consider this fixed.
