### ISSUE TITLE
Cannot install Tiberian Dawn Music 

### ISSUE THREAD

**Issue by BBarnes005** [OpenRA/OpenRA#9043]
I have my The First Decade disc in, but the "Install Music" button doesn't appear in the Music window  for the Tiberian Dawn mod, but I was able to install the music for Red Alert from the TFD Disc just fine. Am I doing something wrong? 

 ![openra-2015-08-12t060347z](https://cloud.githubusercontent.com/assets/13760294/9217517/0e4b85a2-408e-11e5-9f48-c7aba8e5e774.png)

This was using the latest test version.

**Comment by GraionDilach** [comment]
Ouch, okay, this is my fault. TD's `ShippedSoundtracks` says 2, transit.mix has all the 4 songs, but all songs from that mix are hidden!
