### ISSUE TITLE
Can't set waypoints for chrono tanks using shift

### ISSUE THREAD

**Issue by Townes27** [OpenRA/OpenRA#9046]
Setting waypoints using shift doesn't work for chronotanks.
The tank chronos to the first waypoint and then does nothing, meaning it neither drives to the next waypoint nor waits until it can chrono again in order to chrono to the next waypoint.
According to penev in irc it may be due to teleporting cancelling all other activities.

Furthermore, waypoints also do not work if the tank has just chronoed and you're then issuing the waypoint order command using shift.
##

**Comment by cjshmyr** [comment]
The PortableChrono trait uses both `alt` and `shift` for teleportation orders, originally it was meant to be just `alt` but Linux users encountered problems, so we added `shift` in for teleports as well. As a result that broke the shift queuing behavior as you've reported here.

Code causing the issue: https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.RA/Traits/PortableChrono.cs#L136

**Comment by Townes27** [comment]
What kind of problems? 
While alt doesn't seem to work on my Debian system, altgr works fine for teleportation orders.

**Comment by pchote** [comment]
Fixed by #13488.
