### ISSUE TITLE
Black tiles for ra interior Tileset leave smudges

### ISSUE THREAD

**Issue by Biofreak1987** [OpenRA/OpenRA#9049]
See Screenshot

![black_tileset_smudges](https://cloud.githubusercontent.com/assets/4711816/9226962/7396157a-4111-11e5-9037-bea6c49103ce.png)

I don't think it's supposed to be like that

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/tilesets/interior.yaml#L11
