### ISSUE TITLE
Delay for CrateSpawner

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#9055]
I understand that the unit duplication crate has been removed from all mods (which is needed). However I think this is just a bandaid. 

In the first 5 minutes of any mod, 1v1 especially, are critical. Crates really mess up games in these first 5 minutes. Unit dupe crates are the worst, then light tank crates in RA (light tank husk blocking REF or WF) then money crates. Even death crates are annoying as early map control and LoS is paramount. 

This is especially true on very small 1v1 maps.

**Comment by pchote** [comment]
Is this a bug report, or a feature request?

If it's a request, then I agree that we should have a configurable initial delay in the crate spawner to avoid breaking the game balance when somebody finds a money or unit crate right next to their base.

**Comment by r34ch** [comment]
A request accidentally published before I added an explanation.

**Comment by SMIFFGIG** [comment]
Sounds like a good idea
