### ISSUE TITLE
Actor sight range has a hardcoded upper limit

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#9061]
As revealed in #9053.
Actor sight range is limited by the size of `Map.TilesByDistance`, which is defined as
`static readonly CVec[][] TilesByDistance = InitTilesByDistance(MaxTilesInCircleRange);`.
This means that it is calculated once at game start and is the same for all maps.
`Map.MaxTilesInCircleRange` is defined as `public const int MaxTilesInCircleRange = 50;`, which means there is effectively a hardcoded upper limit on the sight range one can put on an actor.

To be fair, `TilesByDistance`, which is used in `Map.FindTilesInAnnulus()` (only), is used for all kinds of stuff other than visibility as well, which means there is an upper limit of 50 cells for quite a few things.

*P.S.: The actual limit for visibility is currently 49, because of*
```
public static IEnumerable<PPos> ProjectedCellsInRange(Map map, WPos pos, WDist range)
{
	// Account for potential extra half-cell from odd-height terrain
```

This can easily be changed to account for each map's size and adjust accordingly. That can be coupled with lint checks that would give proper warnings to modders and mappers about ranges that are too big. (there comes a point when the range is too big for the map).

**Comment by Unit158** [comment]
We used to clamp this value to prevent the crash as was reported. I have a feeling that someone removed it in the past and forgot to add it back again or pchote didn't update it.

**Comment by penev92** [comment]
Apparently #notabug. Based on IRC discussion.

**Comment by Unit158** [comment]
This is indeed a bug, as it crashes :open_mouth:

**Comment by Phrohdoh** [comment]
There is a difference between an individual not wanting to take their time to fix it as they don't see it fit, and something not being a bug.

**Comment by Mailaender** [comment]
This wants to have a lint check to check for bogus value before run time. You may want to revive or at least get some inspiration from https://github.com/OpenRA/OpenRA/issues/7112.
