### ISSUE TITLE
settings.yaml is conflicting when running multiple servers on same users

### ISSUE THREAD

**Issue by baxxxster** [OpenRA/OpenRA#9065]
I'm having some issues with running multiple servers on same users (Linux verified).

It seems on start the server writes the settings to settings.yaml in .openra/ directory.

Earlier I've noticed a problem where the server name could actually be affected by this and duplicate, if the servers started up too fast (Sorted with adding a sleep in the script) - But I've experienced another "worse" problem now.

Even though I'm starting my servers first, without any Server.Password, if I then start other servers, on the same user, but with Server.Password parameter, the first servers too, get locked (I guess it re-reads settings.yaml every now and then, and finds the Password-parameter).

Is there any way to create a settings.yaml per server? Maybe settings-$PID.yaml if it's easy to get the PID on all OS'es.

It's very "time consuming/waste" to create own user for every server you might want to change the settings on.

Hope there's a solution to a more multi-setup friendly environment :)

**Comment by pchote** [comment]
You can currently do this on a per-install basis by creating a directory called Support in the main game dir (requires write permissions, obviously). We have a ticket somewhere about adding a --support-dir startup flag for setting it at runtime.

**Comment by cjshmyr** [comment]
Have ran into the password thing too, but to unset the password you can use an empty string arg - `Server.Password=""`
