### ISSUE TITLE
TD: rename "v37" civilian building?

### ISSUE THREAD

**Issue by clemty** [OpenRA/OpenRA#9067]
According to http://nyerguds.arsaneus-design.com/N64Project/editing/cut_stuff.txt
>Civilian Building "The Studio" [V37]
>Is unused in PC C&C; represents the Westwood Studios building

According to http://www.giantbomb.com/westwood-studios-inc/3010-261/ Westwood Studios was located at 5333 South Arville, Suite 104, Las Vegas (which may be a PO box?), but google maps/earth shows a similar building there: https://www.google.com/maps/place/36%C2%B005'34.9%22N+115%C2%B011'59.2%22W/@36.093025,-115.199777,228m/data=!3m1!1e3!4m2!3m1!1s0x0:0x0

edit:
currently it is called:
- Civilian Building

but maybe this would be more accurate:

- Westwood Studios Building

**Comment by Mailaender** [comment]
We already support generic tooltip names https://github.com/OpenRA/OpenRA/pull/6613 so we can have both:

```yaml
Tooltip:
		Name: Westwood Studios
		GenericName: Civilian Building
```

In fact all those civilian buildings had names attached: http://nyerguds.arsaneus-design.com/cnc95upd/inirules/structs.ini
