### ISSUE TITLE
Consider adding new track to RA mod (title music)

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#9069]
There was this gentleman called sbeast on the forums some time ago offering his track to be used with OpenRA: http://www.sleipnirstuff.com/forum/viewtopic.php?t=17379&highlight=

mediafire: http://www.mediafire.com/listen/ic1ieq1lkl8p7dp/OpenRA.mp3

I found out he has a YouTube channel: https://www.youtube.com/user/sbeast64

What I like about this track (Hell March cover), in addition to being really good is that it's style fits well with the c&c soundtrack. The track is being offered freely. The appeal could be to reinforce the uniqueness of OpenRA's RA mod and the nature of it's voluntaryism. It could also encourage getting more valuable free offers from songwriters. Imagine having equally good, or better, unique tracks for all the mods (title music). If feasable, I feel this would be worthy of consideration.

**Comment by GraionDilach** [comment]
It does not fit along with the RA OST. The guitar is pretty much spot on, but everything else are too modern and would stand out.

**Comment by SoScared** [comment]
I see your point but I think part of the idea IS to stand out. The modern style shouldn't be that big of a deal as the RA itself is modernized.

**Comment by Unit158** [comment]
If he distributed it as a MIDI, we might be able to make it work. Alas, it is not. I think this would be extremely appropriate for trailers, tournaments and such, but I would find it to distracting from the rest of the retro feel of the game.

**Comment by GraionDilach** [comment]
@SoScared If it's part of the idea, then the idea is bad. Such a quality jump is jarring in the long run for the actual user.

Consistency is important.

**Comment by penev92** [comment]
I like it.

**Comment by SoScared** [comment]
I can see the quality jump from and to the original soundtrack could be a problem. I could get back to the creator and see if he wants to work on it based on this feedback.

**Comment by pchote** [comment]
Our big music rework hasn't even made it to a release yet, so I think its a bit premature to be debating this now.  IMO our new title (I assume you mean shellmap) music is a better fit than hell march (the original and/or this rework).

**Comment by SoScared** [comment]
Sounds good. We can put this topic on ice then.

**Comment by dan9550** [comment]
It's not C&C if its not Frank Klepacki. At least that's my motto hehe.

**Comment by MicroJOo** [comment]
i agree with @dan9550 and @GraionDilach

**Comment by Mailaender** [comment]
Closing this as we don't have a system to ship custom music yet and someone posting a link with a music track isn't giving us the guarantee he is the rightful owner of the track which might cause :copyright: problems. The song is of good quality. I suggest you use it for a promotional video like https://github.com/OpenRA/OpenRA/issues/6891.
