### ISSUE TITLE
Crash when setting Documents\OpenRA to hidden

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#9078]
Tried hiding the OpenRA folder in my Documents. W10

http://pastebin.com/7u5KFVxq

**Comment by LipkeGu** [comment]
Did you select ONLY the Folder or all files also inside this folder?

**Comment by LipkeGu** [comment]
could be fixed by this idea: #9079

**Comment by Unit158** [comment]
I think this is a wontfix because the error is between the chair and keyboard :s

**Comment by r34ch** [comment]
I understand it was my doing, but seems odd the folder is hidden in linux but not in windows. 

This clutters the my Documents on Windows which is a shame for those of us with OCD.

**Comment by Phrohdoh** [comment]
Windows does not allow 'hidden' files with the leading `.` as Linux / OS X does so we simply cannot hide it.

The intention is not hiding the files, for what its worth, it is following a convention for the user's home directory.

**Comment by r34ch** [comment]
Forgive my ignorance, but why would you need a leading `.` in the windows path? I thought the hidden property in windows was a separate attribute?

**Comment by DeadlySurprise** [comment]
>The intention is not hiding the files, for what its worth, it is following a convention for the user's home directory.

We could move the folder to the Documents/My Games sub folder which most post vista games use.

And as a side note you can hide the folder by moving it and making a hidden symbolic link to it, that's how I do it.

**Comment by Mailaender** [comment]
Closing for now as the crash has been resolved and we can't change Windows file system behavior. On Unix hiding just means hiding and not also read-only which is what confused the Mac and Linux users here. Don't hide the contents of the folder as suggested in the first comment.
