### ISSUE TITLE
How can i get the CabfileIDs for German TFD DVDs?

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#9081]
OpenRA says the Disk was not found... but changelog says support is there :(
something different between german and US disks?!

I looked already in the PR but no one has documented how we can find the IDs and how they are calculated

**Comment by GraionDilach** [comment]
That's possible that they are different. Most of the C&Cs were localized in Germany (Generals and TibDawn were even heavily censored) which could not fit alongside the English versions on the DVD.

**Comment by LipkeGu** [comment]
i have uploaded the Data1-Header here ... (data1.hdr and data1.cab)

https://github.com/LipkeGu/Other-crap/tree/master/DE10J

**Comment by pchote** [comment]
We don't support non-english versions of original disks either, so i'm not convinced this is an issue.  There is a lot of work to go before we will support translations.

**Comment by LipkeGu** [comment]
We only need the MIX files ... when i use the german NOD disk OpenRA will also run with this... the problem here is the Filetable inside the Cab

**Comment by Unit158** [comment]
I'm worried that a user will put a localized disk and expect a translated game. Some things such as cameos will be "translated", no?

**Comment by LipkeGu** [comment]
I dont expect some things ... the changelog says "Support for TFD" but the german DVDs are not supported i meaning only installing content from the cab files :/ not translated games ... 

Our install logic doesnt find the files iin the Cabs

**Comment by LipkeGu** [comment]
i found out how to get these ids

https://gist.github.com/DSUK/e243103217bac918b175
