### ISSUE TITLE
Desync when Cargo.InitialUnits is used

### ISSUE THREAD

**Issue by Zjordy** [OpenRA/OpenRA#9094]
Game Crash when i build modded Plane
 on this version: "Civillian Outrage BETA 48a"   http://resource.openra.net/maps/4168
out of sync

**Comment by penev92** [comment]
We need the sync.logs from the other players as well to compare in order to do anything about it.

**Comment by deniz1a** [comment]
This is for release-20150614.
Here are the sync reports: https://gist.github.com/deniz1a/89ad3eafc2fe6b7fbf8e
synxreport-1 and syncreport-2 are equal. syncreport-3 has the following entries that are missing from the other two:
````
	 131 c1 hello Mobile (192)
		 PathHash: 0
		 Facing: 192
		 CenterPosition: 0,0,0
		 FromCell: 0,0
		 ToCell: 0,0

	 132 c1 hello Mobile (192)
		 PathHash: 0
		 Facing: 192
		 CenterPosition: 0,0,0
		 FromCell: 0,0
		 ToCell: 0,0

	 133 c2 hello Mobile (192)
		 PathHash: 0
		 Facing: 192
		 CenterPosition: 0,0,0
		 FromCell: 0,0
		 ToCell: 0,0

	 134 c2 hello Mobile (192)
		 PathHash: 0
		 Facing: 192
		 CenterPosition: 0,0,0
		 FromCell: 0,0
		 ToCell: 0,0

	 135 c2 hello Mobile (192)
		 PathHash: 0
		 Facing: 192
		 CenterPosition: 0,0,0
		 FromCell: 0,0
		 ToCell: 0,0
````

**Comment by deniz1a** [comment]
I found the cause of the crash:
````
		Cargo:
			MaxWeight: 5
			PipCount: 5
			InitialUnits: c1,c1,c2,c2,c2
````
When the line with InitialUnits is removed, game does not crash.

**Comment by Zjordy** [comment]
ok cool , but then that means that i can't have any cargo in the plane ? i wanted some civvies to jump out of  the plane. or might someone know an alternative to make this happen ?

**Comment by pchote** [comment]
Nothing looks obviously bogus in that code, but putting the `CreateActor` calls inside a FrameEndTask could may fix it.

**Comment by Zjordy** [comment]
oh ok i don't know how to do that, oh and by the way this code of mine works in single player just get out of sync in multiplayer

**Comment by pchote** [comment]
@Zjordy: Remove the `WithCargo` trait from `cyak`.  That is causing your desync.  I will file a PR that fixes this properly, but that trait doesn't do anything useful for you anyway. You should also remove `Paradrop`, which does not work for player controlled units.

**Comment by pchote** [comment]
You should also really use the `--check-yaml` utility command, which will tell you about any rule definition errors in your map.  You have a few of them.

**Comment by Zjordy** [comment]
hey thanks pchote ill try to make my dyak again soon.  and how do i run this --check-yaml? im on a mac if that makes  any difference

**Comment by pchote** [comment]
You can open a terminal, and then type `mono /Applications/OpenRA.app/Contents/Resources/OpenRA.Utility.exe ra --check-yaml ~/Library/Application\ Support/OpenRA/maps/ra/civ48a.oramap`.
You'll want to replace `/Applications/` with the location you've copied the OpenRA.app, and `civ48a.oramap` is the map you want to test (works for both packaged oramaps and also unpacked directories).

**Comment by Zjordy** [comment]
awesome thank you :)
