### ISSUE TITLE
Humanlike Infantry will get produced in kennels

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#9098]
I discovered a bug when the player build ONLY a kennel but no barracks he can produce tanya and infantry from it.

Reproduce case:

- enable devbuildall cheat
- build a kennel and barracks
- sell the barracks

we should also ensure that infantry can only produced in barracks regardless of having cheats enabled or not.

**Comment by pchote** [comment]
> enable devbuildall cheat

This is expected behaviour with cheats enabled.  The same thing happens for helicopters/aircraft and their associated structures.

**Comment by LipkeGu** [comment]
it is in this case expected or will this be fixed?

**Comment by GraionDilach** [comment]
Funstuff: using the devbuildall cheat does not enable crossqueueing at individual ones - the subqueues will not get merged like this.
