### ISSUE TITLE
Game crash when trying to load a mod (Tiberian sun or RA2)

### ISSUE THREAD

**Issue by salvadorc17** [OpenRA/OpenRA#9104]
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.17929
Exception of type `System.IO.FileNotFoundException`: El sistema no puede encontrar el archivo especificado. (Excepción de HRESULT: 0x80070002)
   en System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   en System.Reflection.Assembly.LoadFile(String path)
   en OpenRA.ObjectCreator..ctor(Manifest manifest)
   en OpenRA.ModData..ctor(String mod, Boolean useLoadScreen)
   en OpenRA.Game.InitializeMod(String mod, Arguments args)
   en OpenRA.Mods.Common.Widgets.Logic.ModBrowserLogic.<LoadMod>c__AnonStorey1.<>m__0()
   en System.Action.Invoke()
   en OpenRA.Primitives.ActionQueue.PerformActions()
   en OpenRA.Game.LogicTick()
   en OpenRA.Game.Loop()
   en OpenRA.Game.Run()
   en OpenRA.Program.Run(String[] args)
   en OpenRA.Program.Main(String[] args)

**Comment by Phrohdoh** [comment]
This looks like you tried to launch RA2 without the TS mod, which cannot be done.

**Comment by salvadorc17** [comment]
I cant enter irc for some reason, whats the main problem i have booth ts mod and ra2, but not game files, those are still requiered, and how to insert them into open RA?

**Comment by Phrohdoh** [comment]
You need to build the engine which will build the missing DLL file(s).

**Comment by LipkeGu** [comment]
You can download the game files for TS by clicking Download. The Game files for RA2 cant be distributed due to legal reasons. but can be done manually

**Comment by penev92** [comment]
OK this was solved over IRC.
