### ISSUE TITLE
Cannot compile OpenRa.Mods.common VS 2010

### ISSUE THREAD

**Issue by salvadorc17** [OpenRA/OpenRA#9111]
Error	34	An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type	OpenRA.Mods.Common

**Comment by penev92** [comment]
File and line of the error?
Also how are you compiling it? Getting a fresh copy from GitHub and then through VS?

Do we even support VS 2010?

**Comment by salvadorc17** [comment]
There are not file and line specifications, is the project itself. Yes i get a fresh copy, added third party libs, and compiled, OpenRa.Game worked and some other, but not OpenRa.mods.common. Not sure if VS 2010 can make difference for VS 2012/2013

**Comment by cjshmyr** [comment]
I'm pretty certain the compatibility is only there for 2012 and higher, luckily it is free (and much better these days) to use.

**Comment by salvadorc17** [comment]
Ok will test using vs 2012 and post results..

**Comment by salvadorc17** [comment]
Tested on Vs2012 and Xamarin, solved.
