### ISSUE TITLE
Out of Sync crash in my own server

### ISSUE THREAD

**Issue by Zjordy** [OpenRA/OpenRA#9112]
hey almost every time i play (my mod map) in my own server i get a out of sync crash.
sometimes even while in the lobby where you choose spots and countries.
i don't know much about port forwarding but ive set my upnp settings on to make a server , and i used to have not this much crashes

**Comment by Unit158** [comment]
You'll need to post the sync.log files (of EVERYONE) before we can help.

**Comment by Zjordy** [comment]
ok ive now tried it with different maps and different servers and it still happens with me and Rhyanelol

**Comment by Zjordy** [comment]
had one good game and it happened again after, now reinstalling openra

**Comment by penev92** [comment]
Reinstalling won't help. But if you provide us with the syncreport.log files from both players, we may be able to.

**Comment by deniz1a** [comment]
@Zjordy: You're really good at finding out of sync bugs.

**Comment by Zjordy** [comment]
haha is that a good thing finding desync bugs? kind of annoying to crash everyone out of the game,   btw reinstalling the game  (and also reconfiguring some minor modem settings) seemed to help :)

**Comment by deniz1a** [comment]
Reinstalling fixed the desync?

**Comment by deniz1a** [comment]
And yes it's a good thing to find them, so they can be fixed.

**Comment by Mailaender** [comment]
Sounds like a dirtied install where not every mini yaml rule was replaced?

**Comment by deniz1a** [comment]
Shouldn't the game then compute a hash of all yaml files and not start the game if it's different from the server's?

**Comment by Phrohdoh** [comment]
@deniz1a way ahead of you, #7833.
