### ISSUE TITLE
Sandstorms instead Fog of War

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#9119]
in dune2 (or d2-the golden path) there was a random event appearing ingame ... beside worms crawling out of the sand ... also "sandstorms" appeared several times in a game ... 

they "recreated" the shroud (dune had no fog of war) ... 

https://youtu.be/ZwvdEGmpeDI?t=10m33s

we could add this feature , instead of the fog of war (allready a feature that didnt exist in the original) so it fits the mod ... 

![d2sandstorm](https://cloud.githubusercontent.com/assets/9139965/9393231/2fcaf542-4781-11e5-9f50-65c4acb2f57f.png)

**Comment by penev92** [comment]
[22:10] <penev> tldr a random sandstorm appears and resets the shroud at a random time
[22:11] <penev> which is a very nice mod-specific compromise between having fog and not having it IMO

**Comment by GraionDilach** [comment]
Shouldn't this be done via lua?

**Comment by Unit158** [comment]
It could be, but if we want it to be done across the mod, a trait is worth the time :)

**Comment by GraionDilach** [comment]
Then we could move TS ion storms, day-night scripts etc etc into traits. Notsure if I like.

**Comment by penev92** [comment]
I think a dedicated trait here (controllable through lua, sure, why not) is fine here.

**Comment by TheRaffy** [comment]
Additionalley there could be some sand storm particles shown by the WeatherOverlay.
https://github.com/OpenRA/OpenRA/pull/8766

**Comment by Micr0Bit** [comment]
@reaperrr : opinion ? ... this would make the d2k-mod even more unique from trom ra / td ... 

i wish i could convince paul to like this idea , but he persists on having "fog of war" in all mods no matter what , whenever i start talking about it

**Comment by TheRaffy** [comment]
poor microbit ;(
(I think it would be unique and add some value, but I don't like to code that ;)

**Comment by Micr0Bit** [comment]
it lets my heart bleed to close this ... cause i was sure this would be a really nice feature ... but it looks like theres not much interest ... i tried several times to convince paul about this without success , and since im pretty much alone with my oppinion ... this aint gonna happen 

:disappointed:

**Comment by pchote** [comment]
I think this is a fun feature, and its actually already doable on individual maps using lua.  I just don't see it as a replacement for the fog – they are completely different things with different purposes.
