### ISSUE TITLE
Show custom map rules in lobby

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#9122]
If a map has custom rules, there is a warning in lobby. It would be even better if those custom rules could be viewed there.

**Comment by pchote** [comment]
I don't like this idea. Most players don't know or care about the technical details of how custom rules are defined, and so this would be visual clutter for them that makes the game feel less friendly / useable for them.

**Comment by Phrohdoh** [comment]
I agree with @pchote here.
If players wants to investigate the custom rules in detail they can either play the map and find out or inspect the files outside of the game.

**Comment by xp65** [comment]
I agree with @pchote as well. It's even fun to have special maps and not know all of it in the beginning. That's part of exploring that map, like a real army would need to do. Same as in the missions, not knowing where an enemy or danger is lurking around the corner.

**Comment by penev92** [comment]
Well, it doesn't look like this is happening.
