### ISSUE TITLE
OpenRA cannot start, OpenTK required??

### ISSUE THREAD

**Issue by salvadorc17** [OpenRA/OpenRA#9125]
OpenTK.Graphics.GraphicsContextMissingException: No context is current in the calling thread (ThreadId: 1).
   en OpenTK.Graphics.GraphicsBindingsBase.LoadEntryPoints()
   en OpenTK.Graphics.OpenGL.GL.LoadAll()
   en OpenRA.Renderer.Sdl2.Sdl2GraphicsDevice..ctor(Size windowSize, WindowMode windowMode) en C:\Users\Usuario\Documents\Visual Studio 2008\OpenRA-ra2-master\OpenRA.Renderer.Sdl2\Sdl2GraphicsDevice.cs:línea 87

**Comment by penev92** [comment]
Can you give a bit more context?

**Comment by salvadorc17** [comment]
What do you mean more context, im trying to run OpenRa (compiled version) and i cannot start game, that error is showed in logs/graphics. logs/exception show this:
Exception of type `System.InvalidOperationException`: No suitable renderers were found. Check graphics.log for details.

**Comment by Unit158** [comment]
What OS are you on, etc.

**Comment by salvadorc17** [comment]
Windows 7 64 bits, and i have all prerequisites installed, becuase i can run downloadable version normally, but not the compiled..

**Comment by GraionDilach** [comment]
Did you do a `make dependencies`?

**Comment by salvadorc17** [comment]
Yes i did make all depencencies, and for compile it requested for OpenTK, then in OpenRa.Game and OpenRa.Sdl2.Renderer, it still requiered??

**Comment by Mailaender** [comment]
The engine shouldn't require that. I submitted a fix in https://github.com/OpenRA/OpenRA/pull/8632. Your problem is unrelated though. Not a Windows guy, but try following the instructions at https://github.com/OpenRA/OpenRA/wiki/Compiling#windows oh and your Visual Studio version might be too old.

**Comment by salvadorc17** [comment]
I was using VS 2012 for latest compilation test, and i have followed instructions, why you said engine will not requiere, there are classes that have OpenTK:

OpenAlSound.cs:

using OpenTK;
using OpenTK.Audio.OpenAL;

static string[] QueryDevices(string label, AlcGetStringList type)
		{
			// Clear error bit
			AL.GetError();

**Comment by Mailaender** [comment]
and that is exactly what https://github.com/OpenRA/OpenRA/pull/8632 is trying to change.

> Yes i did make all depencencies

`make dependencies` is a command. See https://github.com/OpenRA/OpenRA/wiki/Compiling#windows for further explanations.
