### ISSUE TITLE
Chrono crash, explored terrain using crate

### ISSUE THREAD

**Issue by xp65** [OpenRA/OpenRA#9127]
release-20150614

The game crashed after I used the chrono, but to a location I normally could not, but the terrain was already explored using a special crate. It resulted in "Out of sync" with AdvancedChronoshift

```
Red Alert Mod at Version release-20150614
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Out of sync in frame 5876.
 OrderString: "AdvancedChronoshift" 
	 Subject: "player 4". 
	 TargetActor: "" 
	 TargetLocation: 29,18.
	 TargetString: "".
	 IsImmediate: False.
	 Player(PlayerName): General

 Compare syncreport.log with other players.
   bij OpenRA.Network.OrderManager.OutOfSync(Int32 frame, Int32 index)
   bij OpenRA.Network.OrderManager.CheckSync(Byte[] packet)
   bij OpenRA.Network.OrderManager.<TickImmediate>c__AnonStorey0.<>m__0(Int32 clientId, Byte[] packet)
   bij OpenRA.Network.ReplayRecorderConnection.<Receive>c__AnonStorey0.<>m__0(Int32 client, Byte[] data)
   bij OpenRA.Network.EchoConnection.Receive(Action`2 packetFn)
   bij OpenRA.Network.ReplayRecorderConnection.Receive(Action`2 packetFn)
   bij OpenRA.Network.OrderManager.TickImmediate()
   bij OpenRA.Sync.<CheckSyncUnchanged>c__AnonStorey0.<>m__0()
   bij OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   bij OpenRA.Sync.CheckSyncUnchanged(World world, Action fn)
   bij OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   bij OpenRA.Game.LogicTick()
   bij OpenRA.Game.Loop()
   bij OpenRA.Game.Run()
   bij OpenRA.Program.Run(String[] args)
   bij OpenRA.Program.Main(String[] args)
```

All files including replay can be found here: https://drive.google.com/folderview?id=0BynHp26MoAw-fjJxVklYTmQzTjNvZzhUbEQ4MTJoV2d1bkVZVlBMU25QcnA0eU1FR1BnTzg&usp=sharing

Thanks for looking into this

**Comment by penev92** [comment]
Do you have the `syncreport.log` files from other players?

**Comment by xp65** [comment]
Sadly I do not have that. The other player is unknown to me, it was a random player in multiplayer.

**Comment by deniz1a** [comment]
#9075 might fix this.

**Comment by xp65** [comment]
@deniz1a you might be right, it might be related. It seems the information isn't shared with the other players, therefor crashing in this case.  As your code hasn't been submitted, then this is still an open error. Your code may therefor not only fix replays, but also fix this actual ingame error. This however is an assumption and needs verification.

**Comment by Basti504** [comment]
The crash is reproducible, using two clients.

* Got the world-reveal crate
* Build chrono
* Chrono units to somewhere on the map I am 100% sure did not reveal by my units
* Crash

Below the sync reports. don't mind the {DEV_VERSION}, it's self-compiled release 20150614 downloaded from https://github.com/OpenRA/OpenRA/releases

Player 1;Appelflap ; Did the chrono, initiated the crash
Player 2:Appelflap2; Did nothing actually.

https://www.diffchecker.com/u0mtgqou

**Comment by deniz1a** [comment]
This also happens in bleed. And #9075 fixes it, just tested.
