### ISSUE TITLE
Replace tabbed production palette with distributed queues

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#9128]
In Tiberian Dawn, each production building has its own tab in production palette. It is cumbersome to switch between multiple tabs. And it is not possible to see all queues at once. How about replacing this with distributed queues?

It would work like this: There is a single production tab like in Red Alert. Let's say you have multiple weapons factories. When you build a vehicle, it is queued to the primary factory. When you click on its icon again while the first one is being built, it is queued to the next free factory. The progress clock of the second vehicle is overlaid on the same icon with a different color.

This would make building things a lot easier and you would have an overview of all queues.

**Comment by Phrohdoh** [comment]
You build at a particular factory based on its position in the world.
Queuing to an essentially random factory is a terrible idea for that reason.

**Comment by GraionDilach** [comment]
:-1:

You're forgetting that TD factories does not always share the build options. Your proposal is also less intuitive for the user.

**Comment by deniz1a** [comment]
Not random. The first one would be the primary factory, other ones would be in the reverse order that they were built...

**Comment by deniz1a** [comment]
Oh ok, I thought all factories had the same build options.

**Comment by penev92** [comment]
They don't share faction-specific items.
Also that *is* a random choice of factory.
I say "no" as well because of less controll, and it also makes it almost like ra/d2k/ts.

**Comment by pchote** [comment]
:-1: from me too.  This idea appears to be universally rejected, so closing.

**Comment by x-a-n-a-x** [comment]
It reminds me of another "similar" idea I had : #2997

It seems @deniz1a is like me, an "idea brainstormer" :-)  
I don't blame him for trying to enhance OpenRA but the other devs are right here : it might not be a good idea to radically change the way TD (or our 3 main mods) work.

**Comment by Mailaender** [comment]
Please only post realistic goals on this tracker. Use the forums to brain storm together.

**Comment by deniz1a** [comment]
Ok.
