### ISSUE TITLE
Old Mod content isnt unloaded while content installer is in use.

### ISSUE THREAD

**Issue by LipkeGu** [OpenRA/OpenRA#9132]
When we install the playtest for example then we have no mod content. After we install the first mod the behavor is normal. (we have only on mod) @penev92 reported in the first TFD PR that he got an OOM when he installs content from the TFD DVD.

I ran OpenRA in VS to research this behaver and found out that the mod content will not be unmountet / unloaded WHILE WE INSTALLING mods.

i started Red alert and switched to cnc to install content from the TFD DVD and VS reports that the process has about 1 GB memory in use after the installer loads cnc the memory usage was at 340 MB but shortly after extraction the usage at 1,5 GB

http://i.imgur.com/3CvrLk8.png

the loaded content was Red Alert before i installed cnc

IMO this could raise in race conditions an out of Memory Exception.

**Comment by pchote** [comment]
See #8990.

**Comment by penev92** [comment]
This sounds wrong.
Have you verified that launching TD directly works any better?
Also remember that there is a lot of extracting and inflating of data going around.

**Comment by LipkeGu** [comment]
* Have you verified that launching TD directly works any better? : Yes i verified it 4 times also with other mods. The Mix files are mounted you can see it by installing ra from TFD disks and deleting main.mix (from ra) after restart the memory without main.mix is drastically lower ~350MB when CnC starts directly

**Comment by Mailaender** [comment]
Resolved by https://github.com/OpenRA/OpenRA/issues/9263 I suppose.
