### ISSUE TITLE
Dune 2000 - Crashes on Arch / Gnome-Shell

### ISSUE THREAD

**Issue by Lokke** [OpenRA/OpenRA#9149]
When i play D2K on Arch and change the volume via the hardware keys on my notebook the game stops running.

I am running Arch (x64) with Gnome 3.16.2 on an Intel Ironlake Mobile 
##

**Comment by Unit158** [comment]
For clarification: the game just hangs? Is it specific to D2K?

**Comment by Mailaender** [comment]
Closing as Arch and GNOME Shell have moved on and either way we need more information to find the cause for this. Reopen if this is still a problem.
