### ISSUE TITLE
Add music tab to RA and D2K lobbies.

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#9153]
http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=18463

I would really like to see this, as I often have to leave a lobby while casting to turn my music on.

**Comment by r34ch** [comment]
Yes, after the first track finishes I often have to do this too.

**Comment by SoScared** [comment]
Agreed with Unit158, casting would be more seamless with the music option available in the lobby! Hope to see this for RA and eventually D2K as well.

**Comment by pchote** [comment]
We need to tweak the lobby layout to integrate the global chat tab, which should make space available for this as a side effect.

**Comment by SoScared** [comment]
Wow global chat access sounds exciting. I love what you've with the lobby already. Looking forward to this

**Comment by pchote** [comment]
The music will be integrated into the main lobby interface in all mods once #9451 is finished:

![](http://i.imgur.com/A8YdYRb.png)

(ignore the space to the right of the chat area - that hasn't been finished yet).
