### ISSUE TITLE
Bleed - Can target & attack cloaked buildings

### ISSUE THREAD

**Issue by RoosterDragon** [OpenRA/OpenRA#9157]
See also #8899.

In TS, buildings protected by a Nod stealth gen get an attack cursor when you mouse over them and can be attacked. #9090 will prevent the tooltips appearing, but not prevent attacks.

A quick test shows this also affects camo pillboxes in RA, but not subs - so it seems to be building related.

**Comment by pchote** [comment]
This will also affect the camo pillboxes in RA.

**Comment by reaperrr** [comment]
Sounds like `TargetableBuilding` might be to blame, just speculation though.

**Comment by penev92** [comment]
I'd say you're right, because it's OK for units.

**Comment by reaperrr** [comment]
Actually no, that's not the problem.
I gave stealth generator TargetableUnit and removed TargetableBuilding, no change.

What I noticed when testing against an AI (with shroud/fog disabled) that I could target vehicles, but NOT the construction yard. As soon as the stealth gen was placed, the vehicles became untargetable, while the cyard suddenly became targetable.

I suspect there's actually something wrong with the visibility check of actors with a footprint.

**Comment by RoosterDragon** [comment]
Visibility queries are different with fog disabled since #9071.

I did my tests with shroud & fog enabled.

We should check stable isn't affected by this.

**Comment by reaperrr** [comment]
#9180 doesn't fix the cursor, but the attacking. If we can fix the cursor as well, this is solved.

**Comment by penev92** [comment]
Seems like the target (Stealth Generator) is considered a `FrozenActor` (which sounds quite wrong, given the screenshot below). Source is `UnitOrderTargeter.GetCursor() - var underCursor`. This eventually gets to `AttackBase.CanTarget()`, which has no problems with frozen actors and that results in a `UnitOrderResult` being dispatched successfully for that target.

![](http://i.imgur.com/qTnUo8A.png)

**Comment by reaperrr** [comment]
We should check again now that #8727 was merged, but the tooltip might need #9090.

**Comment by abcdefg30** [comment]
Just for the record (as #9090 was merged):
> 21:29 (+abcdefg30) antares79: is #9157 now fixed?
21:29 (+antares79) nope

**Comment by reaperrr** [comment]
Only 2 of the 3 issues have been solved (`TargetableBuilding` did not check whether an actor was cloaked and the tooltip leakage), the `UnitOrderTargeter` issue @penev92 mentioned probably still applies.

Since it seems visibility-related, we should test whether replacing `FrozenUnderFog` with `HiddenUnderFog` "fixes" it.
