### ISSUE TITLE
Utility crash on latest bleed

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#9158]
`Received args: --check-code-style OpenRA.Platforms.Default
System.TypeLoadException: Der Typ "OpenRA.RendererAttribute" in der Assembly "OpenRA.Game, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" konnte nicht geladen werden.
   bei System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   bei System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   bei System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   bei System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   bei System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   bei System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   bei System.Reflection.RuntimeAssembly.GetCustomAttributes(Boolean inherit)
   bei StyleCop.StyleCopCore.LoadAddins(String path, Byte[] publicKey)
   bei StyleCop.StyleCopCore.LoadAddins(String path, Byte[] publicKey)
   bei StyleCop.StyleCopCore.LoadAddins(String path, Byte[] publicKey)
   bei StyleCop.StyleCopCore.LoadAddins(String path, Byte[] publicKey)
   bei StyleCop.StyleCopCore.LoadAddins(String path, Byte[] publicKey)
   bei StyleCop.StyleCopCore.Initialize(ICollection1 addInPaths, Boolean loadFromDefaultPath)
   bei StyleCop.StyleCopConsole..ctor(String settings, Boolean writeResultsCache, String outputFile, ICollection1 addInPaths, Boolean loadFromDefaultPath, Object hostTag)
   bei StyleCop.StyleCopConsole..ctor(String settings, Boolean writeResultsCache, String outputFile, ICollection1 addInPaths, Boolean loadFromDefaultPath)
   bei OpenRA.Mods.Common.UtilityCommands.CheckCodeStyle.Run(ModData modData, String[] args)
   bei OpenRA.Utility.Program.Main(String[] args) in e:\OpenRA_work_clean_20150501\OpenRA.Utility\Program.cs:Zeile 53.`

**Comment by reaperrr** [comment]
When trying to run make.cmd check.

**Comment by abcdefg30** [comment]
You probably have an (now) unused folder with stuff in it lying around.
I encountered a similar problem in #7504.

**Comment by reaperrr** [comment]
Ok, after deleting obsolete folders and files and re-fetching/-re-compiling it works now.
