### ISSUE TITLE
ActorInit.GetInitKeys is unused.

### ISSUE THREAD

**Issue by Unit158** [OpenRA/OpenRA#9160]

**Comment by pchote** [comment]
It will be used by the actor init panel in the map editor.

**Comment by Unit158** [comment]
Why did you close this? It hasn't been resolved yet.

**Comment by Mailaender** [comment]
Your question was answered. What do you want to resolve here?

**Comment by Unit158** [comment]
This should be open until the issue is resolved, aka, GetInitKeys becomes used.

**Comment by Phrohdoh** [comment]
I agree with @Unit158.
The intention is known to a developer but is actually not fulfilled yet.
