### ISSUE TITLE
LUA: make it possible to build structures

### ISSUE THREAD

**Issue by clemty** [OpenRA/OpenRA#9164]
Barracks.Build({"e1"}) works but Yard.Build({"pyle"}) doesn't seem to do anything. LUA api only mentions "actors" as a result of Build() so I think placing structures is not currently supported

Telling the AI to build structures would be useful to make the AI rebuild its base in TD single-player missions

Additional things to consider:
- tell the AI where to build (i.e. in missions, rebuild at site of previously destroyed building)
- if that does not work (actor occupying that space on the map), build where it is possible instead as long as it is in the build radius of the construction yard
##

**Comment by Unit158** [comment]
You should be able to use actor.create and do everything in lua in the mean time

**Comment by HenrytheSlav** [comment]
Check soviet05 on how we did the base buildup. The sequence was dveloped by me and @abcdefg30 made it cyclic and conditional and reduced it by approx. 200 lines :)

**Comment by abcdefg30** [comment]
Closing as duplicate of #4493.
