### ISSUE TITLE
LUA: make it possible to sell structures

### ISSUE THREAD

**Issue by clemty** [OpenRA/OpenRA#9167]
original single player TD AI when cornered would often sell its buildings

it took a bit of fun from the game if one loses targets that way, but if selling is possible the AI opponent could sell in a fraction of endgames, making AI less predictable

other instances where this may be useful:
- AI does no longer have construction yard and refinery and needs money: sell silos
- AI does no longer have harvester and no means (building or money) to build one: sell refinery
- AI has no longer enough power for Obelisk or Advanced Guard Tower and no construction yard to build powerplant: sell useless defense structures

related to #9164
##

**Comment by abcdefg30** [comment]
This was added in #11702.
