### ISSUE TITLE
Refuse files with UTF-8 BOM via git-hook or Travis

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/OpenRA#9169]
Example implementation:

Note that OS X's `head` uses `-c n` while (I believe) Ubuntu's uses `--bytes=n`.

```bash
#!/bin/sh

utf8_bom=$(printf "\xEF\xBB\xBF");
bomfiles=$(
	find . -not -iwholename "*.git*" -type f |
	while read filename ; do
		if [ $(head -c 3 "$filename") = $utf8_bom ] ; then
			echo "$filename"
		fi
	done
);

if [ -n "$bomfiles" ] ; then
	echo "The following files have UTF-8 BOM:"
	echo "$bomfiles"
        echo "\nCommit rejected."
	exit 1
fi

exit 0
```

**Comment by Unit158** [comment]
Can you submit a PR with this as a git hook?

**Comment by Phrohdoh** [comment]
Unfortunately no.
I do not know the proper way to set up git hooks that will apply to everyone.

**Comment by chrisforbes** [comment]
Nak. Why are we being cranky about this? It's benign, and windows editors
really like to add it.

- Chris

**Comment by RoosterDragon** [comment]
You could update the .editorconfig for .cs files as a way to get those consistent without being as heavy handed.

Please don't force anything on .sln or .csproj - Visual Studio will just streamroll over those which would be a big pain for Windows users.
