### ISSUE TITLE
ProductionAirdrop in RA

### ISSUE THREAD

**Issue by ivicok** [OpenRA/OpenRA#9170]
I'm experimenting with the Nod-like production of vehicles with RA Airfield; I've defined the Reinforce audio and a C17 actor, but still I'm receiving this error when I actually build a unit:

```
Exception of type `System.Collections.Generic.KeyNotFoundException`: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at OpenRA.ReadOnlyDictionary`2.get_Item(TKey key)
   at OpenRA.Mods.Cnc.Traits.ProductionAirdrop.<Produce>c__AnonStorey0.<>m__0(World w)
   at OpenRA.World.Tick()
```

**Comment by GraionDilach** [comment]
It would be helpful if you could show the full building code somewhere.

**Comment by ivicok** [comment]
sure -


AFLDX:
	Inherits: ^Building
	Buildable:
		Queue: Building
		BuildPaletteOrder: 50
		Prerequisites: ~structures.soviet, ~techlevel.low
	Valued:
		Cost: 200
	Tooltip:
		Name: Airfield
		Description: Provides a dropzone for vehicle reinforcements. Supports Aircraft\n  Special Ability: Paratroopers\n  Special Ability: Spy Plane
	Building:
		Footprint: xxxx xxxx
		Dimensions: 4,2
	Health:
		HP: 2000
	Armor:
		Type: Concrete
	RevealsShroud:
		Range: 7c0
	Exit@1:
		SpawnOffset: -1024,0,0
		ExitCell: 3,1
	RallyPoint:
	ProductionAirdrop:
		Produces: Vehicle, Aircraft, Plane
		ActorType: C17
	WithDeliveryAnimation:
	Reservable:
	ProvidesPrerequisite@soviet:
		Race: soviet, russia, ukraine
		Prerequisite: vehicles.soviet
	ProvidesPrerequisite@sovietvanilla:
		Race: soviet
		Prerequisite: vehicles.sovietvanilla
	ProvidesPrerequisite@russia:
		Race: russia
		Prerequisite: vehicles.russia
	ProvidesPrerequisite@ukraine:
		Race: ukraine
		Prerequisite: vehicles.ukraine
	AirstrikePower@spyplane:
		OrderName: SovietSpyPlane
		Prerequisites: aircraft.soviet
		Icon: spyplane
		ChargeTime: 180
		Description: Spy Plane
		LongDesc: Reveals an area of the map\nand cloaked enemy units.
		SelectTargetSound: slcttgt1.aud
		EndChargeSound: spypln1.aud
		CameraActor: camera
		CameraRemoveDelay: 150
		UnitType: u2
		QuantizedFacings: 8
		DisplayBeacon: true
		BeaconPoster: camicon
	ParatroopersPower@paratroopers:
		OrderName: SovietParatroopers
		Prerequisites: aircraft.soviet
		Icon: paratroopers
		ChargeTime: 360
		Description: Paratroopers
		LongDesc: A Badger drops a squad of infantry\nanywhere on the map.
		DropItems: E1,E1,E1,E3,E3
		SelectTargetSound: slcttgt1.aud
		AllowImpassableCells: false
		QuantizedFacings: 8
		CameraActor: camera.paradrop
		DisplayBeacon: true
		BeaconPoster: pinficon
	AirstrikePower@parabombs:
		OrderName: UkraineParabombs
		Prerequisites: aircraft.ukraine
		Icon: parabombs
		ChargeTime: 360
		Description: Parabombs
		LongDesc: A squad of Badgers drops parachuted\nbombs on your target.
		SelectTargetSound: slcttgt1.aud
		CameraActor: camera
		CameraRemoveDelay: 150
		UnitType: badr.bomber
		QuantizedFacings: 8
		DisplayBeacon: true
		BeaconPoster: pbmbicon
		SquadSize: 3
		SquadOffset: 1792,1792,0
	ProductionBar:
	SupportPowerChargeBar:
	PrimaryBuilding:
	Power:
		Amount: -20
	ProvidesPrerequisite@buildingname:

**Comment by ivicok** [comment]
It seems to me I've solved the issue - without the Reservable: trait the airdrop production works as it should.
