### ISSUE TITLE
Clean up OpenRA repository(?)

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#9184]
There are a few branches here that look like they can be deleted, but I'm not 100% sure on any of them (because it puzzles me that they are still there to begin with).

- water-troopers
- revert-8501-bleed_streams
- coverity-badge
- avoid-duplicate-overcrowded-bugs
- desktop-l10n

**Comment by Mailaender** [comment]
Update your remote. They only exist locally. https://github.com/OpenRA/OpenRA/branches/all
