### ISSUE TITLE
Long bridge engineer repair is broken

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#9192]
It seems the path finder does not allow it to enter the invisible bridge hut. Test map: Poland raid.

**Comment by Mailaender** [comment]
On coastal influence it only works from the north side, but never from the south side.

**Comment by reaperrr** [comment]
Maybe the placement of the invisible bridge hut is the problem. We should test whether #9327 fixes this.

**Comment by Mailaender** [comment]
I tested it and sadly it doesn't. Something else must have regressed here. I assume the method which decides which bridge tiles and bridge huts belong together. Pretty sure that used to work.

**Comment by reaperrr** [comment]
This was actually introduced in #8639, more specifically 26ce7b5.
