### ISSUE TITLE
Move DEB packaging to Ubuntu PPA

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#9201]
They will then run in a clean VM similar to official packages which enhances quality. Also people get a repository for automatic updates. We can also add dependencies like libSDL2 for old LTS versions there.

Interested people in maintaining this can have a look at https://launchpad.net/~openra-developers
##

**Comment by ProfessorKaos64** [comment]
I did just add this to my SteamOS repository. If folks want specific Debian builds (SteamOS is based on Debian Jessie), I can easily build it using pbuilder for Ubuntu etc.

packages.libregeek.org

I know, old thread, but thought i'd put it out there.

**Comment by Mailaender** [comment]
If you want to get listed on http://www.openra.net/download/ you can submit a pull request to https://github.com/OpenRA/OpenRAWeb.

**Comment by ProfessorKaos64** [comment]
Will do. I will submit this soon. Thanks.

**Comment by Mailaender** [comment]
Debian package metadata is also available from https://github.com/ckorn/PlayDeb

**Comment by Mailaender** [comment]
According to https://blog.launchpad.net/cool-new-stuff/beta-test-git-recipes git should be now supported, but I don't know how well nor if the git submodules in the history still breaks Launchpad.

**Comment by RockyTV** [comment]
Why not move .deb packaging to the openSUSE download page?

**Comment by Mailaender** [comment]
I suggested it once https://en.opensuse.org/openSUSE:Build_Service_Debian_builds as it is indeed technically possible, but no one wanted to maintain it. https://wiki.ubuntuusers.de/Open_Build_Service also has a quick intro in German, but SUSE technology in general isn't popular in the Ubuntu world.

**Comment by RockyTV** [comment]
Moving to the SUSE build system would be ideal for users like me who want to host a OpenRA server in Debian based distros but can't because the current "build system" for .DEB requires you to actually use a Debian OS (what happens when the OS doesn't have a graphical interface?). 

Why not setup an automatic job to compile and build new releases? Just setup a webhook, have a script to do packaging and voilà!

**Comment by mdeguzis** [comment]
@RockyTV , not really, pbuilder isn't overly difficult to setup. I build packages on Arch Linux regularly with it, for Debian/SteamOS. Now OBS is nice since it does handle RPM.

**Comment by pchote** [comment]
We already have an automatic job to compile and build releases: that is what builds the current deb plus the windows and macOS installers.

**Comment by Mailaender** [comment]
The technical difficulties on Launchpad (bazar git import erroring because of the use of sub modules in the past) are probably still unresolved and this isn't really getting any momentum I propose https://github.com/OpenRA/OpenRA/issues/12663 instead.

**Comment by RockyTV** [comment]
Honestly, I don't get why Ubuntu and Debian packages aren't included in the openSUSE download page.

**Comment by Mailaender** [comment]
Feel free to send a submit request to revive this feature. I had all packages (including PKGBUILD) combined there ~2 years ago: https://build.opensuse.org/package/show/games:openra/release?rev=14

**Comment by Mailaender** [comment]
https://www.ubuntuupdates.org/package/getdeb_games/xenial/games/getdeb/openra was packaging it in the past https://bugs.launchpad.net/getdeb.net/+bug/992306 but GetDeb is gone. https://github.com/ckorn/PlayDeb/tree/trusty/openra is the last release.
