### ISSUE TITLE
Crash online

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#9210]
Crash on doubles. Posting in-case anyone else leaves logs

http://expirebox.com/download/cd8ebc4c6e31181f5c28718704fee738.html

Ubuntu x64 14.04.3

**Comment by Szunti** [comment]
My logs:
http://expirebox.com/download/e4f0d302def8fc62d393d9635497b689.html

**Comment by Szunti** [comment]
Syncreport.logs are the same unfortunately.

**Comment by Mailaender** [comment]
Nothing we can do to investigate. Try the new http://www.openra.net/news/playtest-20150830/
