### ISSUE TITLE
20150614 - Exception of type `System.FormatException` - wrong format

### ISSUE THREAD

**Issue by MicroJOo** [OpenRA/OpenRA#9213]
Red Alert Mod at Version release-20150614
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.FormatException`: Die Eingabezeichenfolge hat das falsche Format.
   bei System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   bei System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   bei System.String.Format(IFormatProvider provider, String format, Object[] args)
   bei System.IO.TextWriter.WriteLine(String format, Object[] arg)
   bei OpenRA.Log.Write(String channel, String format, Object[] args)
   bei OpenRA.Network.SyncReport.DumpSyncReport(Int32 frame)
   bei OpenRA.Network.OrderManager.CheckSync(Byte[] packet)
   bei OpenRA.Network.OrderManager.<TickImmediate>c__AnonStorey0.<>m__0(Int32 clientId, Byte[] packet)
   bei OpenRA.Network.ReplayRecorderConnection.<Receive>c__AnonStorey0.<>m__0(Int32 client, Byte[] data)
   bei OpenRA.Network.EchoConnection.Receive(Action`2 packetFn)
   bei OpenRA.Network.ReplayRecorderConnection.Receive(Action`2 packetFn)
   bei OpenRA.Network.OrderManager.TickImmediate()
   bei OpenRA.Sync.<CheckSyncUnchanged>c__AnonStorey0.<>m__0()
   bei OpenRA.Sync.CheckSyncUnchanged[T](World world, Func`1 fn)
   bei OpenRA.Sync.CheckSyncUnchanged(World world, Action fn)
   bei OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   bei OpenRA.Game.LogicTick()
   bei OpenRA.Game.Loop()
   bei OpenRA.Game.Run()
   bei OpenRA.Program.Run(String[] args)
   bei OpenRA.Program.Main(String[] args)

**Comment by Mailaender** [comment]
Fixed by  #8137.
