### ISSUE TITLE
stuck in windowed mode

### ISSUE THREAD

**Issue by jakfrosty** [OpenRA/OpenRA#9235]
I'm stuck in windowed mode and nothing is working to fix it  ...the in menu mouse stops at 1 inch before the setting and playgame buttens and then gives me my desktop mouse....

**Comment by jakfrosty** [comment]
nope nvm I had to turn my screen to inverted sideways portait just to fix it lmao

**Comment by Phrohdoh** [comment]
This was an issue with your window manager directly then, not OpenRA?
