### ISSUE TITLE
Badger planes interfere with move order

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#9252]
When a badger plane is clicked with the move cursor, unit moves to badger's location and not to the cell under the cursor. This can be tested with Crate Test map: http://resource.openra.net/maps/4446/
##

**Comment by penev92** [comment]
Reproducible with any aircraft. Clicking on an airborne actor issues a move order for the cell that actor is flying over, not the one that it's visually at (which makes sense, but some might consider it a bug).

**Comment by matjaeck** [comment]
This was fixed.
