### ISSUE TITLE
Allied 5a: Tanyas tale - Spy being detected.

### ISSUE THREAD

**Issue by lacombar** [OpenRA/OpenRA#9253]
I'm not sure whether it's a gameplay issue, or just something I missed.

The description of the mission reads:

    Your spy can move past any enemy unit, without being detected.

However, both soldiers and the flame tower are able to detect (and kill) the spy when he passes within their range. The flame tower locks the western entry, and the two soldiers prevent any entry from the south gate.

Version: playtest-20150830 running on Fedora 22

**Comment by Unit158** [comment]
you have to disguise the spy first

**Comment by lacombar** [comment]
oh... looks like my RA skill need to be re-sharpened :-) My bad for the noise.

**Comment by kojow7** [comment]
Can someone please mention how to disguise the spy? I have tried as many key combinations as I can think of and still can't see how to disguise the spy. I don't see any documentation on how to do this either.

**Comment by ScottNZ** [comment]
Select the spy and right click an enemy infantry unit

**Comment by kojow7** [comment]
Thank you!
