### ISSUE TITLE
Hard lock-up when a game is reloaded.

### ISSUE THREAD

**Issue by lacombar** [OpenRA/OpenRA#9254]
This is a bit synthetic, but describe the problem:

Step to reproduce:
 - start a single player mission (or skirmish)
 - leave the game
 - re-start a mission (or skirmish)

Problem:
 - game freeze

Note:
 - quitting the frozen game only seems possible by sending a SIGKILL to the `mono` process
 - no usable logs seem to be produced

Environment: playtest-20150830 on Fedora 22

**Comment by pchote** [comment]
Does fedora 22 still ship the ancient mono 2.10?  If it does, your first step should be to upgrade to mono 4.0 or newer.

**Comment by lacombar** [comment]
yes :-(

    % rpm -q mono-core    
    mono-core-2.10.8-8.fc21.x86_64

Could this affect game play issues I'm encountering ?

**Comment by Unit158** [comment]
Yes, we do not support mono 2.0.

**Comment by pchote** [comment]
> Could this affect game play issues I'm encountering ?

Definitely.  Mono 2.10.8 is nearly 4 years(!) outdated, totally unsupported by the upstream maintainers, and full of known bugs.  It's embarrassing for Fedora that they are shipping such broken software, and a giant support pain for us.

**Comment by Mailaender** [comment]
Fedora 23 which is currently in alpha will ship Mono 4.0.3 http://pkgs.org/search/mono-core There is not much we can do until then. CC @rapgro

**Comment by Mailaender** [comment]
Try http://www.mono-project.com/docs/getting-started/install/linux/#centos-fedora-and-derivatives

**Comment by rapgro** [comment]
See https://fedoraproject.org/wiki/Changes/Mono_4
