### ISSUE TITLE
gdi01: cannot complete secondary objective

### ISSUE THREAD

**Issue by clemty** [OpenRA/OpenRA#9276]
I build all three buildings, but the objective is not marked as completed

I am reworking some aspects of the script in gdi01 and the objective will be marked as "completed" then, but I wonder: can anyone complete the objective, and what exactly causes it?

**Comment by obrakmann** [comment]
Works for me on both playtest and bleed.

**Comment by clemty** [comment]
works for me now too, strange
thanks for testing!
