### ISSUE TITLE
Soviet Airfield active animation played incorectly

### ISSUE THREAD

**Issue by gangster-ppm** [OpenRA/OpenRA#9285]
Active animation of airfield is played only when it rearms aircraft
Steps to reproduce:
1. Start Soviet 02
2. Buid yak
3. Attack somethind with plane and return for rearming on any of two airfields.
4. Watch difference 
##

**Comment by pchote** [comment]
> Active animation of airfield is played only when it rearms aircraft

I have confirmed that this is what OpenRA does.  What is the expected behaviour?

**Comment by Smittytron** [comment]
Working as intended. It's actually helpful to the player to visually see if a plane is rearming or not.

**Comment by Smittytron** [comment]
Looking at Remasters they have it as the inverse. The lights only ever stop blinking as a plane reloads. Not sure what's better.

**Comment by Smittytron** [comment]
After bringing this up in Discord, we're going to stick with what we have for now. Our current airfield behavior is consistent with helipad reloading, (lights only flash when reloading ammo), which is a helpful indicator for players.
