### ISSUE TITLE
CreatesShroud inherits from RevealsShroud, but are functionally disjoint.

### ISSUE THREAD

**Issue by atlimit8** [OpenRA/OpenRA#9297]
`CreatesShroud` inherits from `RevealsShroud`, but every actor with `CreatesShroud` also has  `RevealsShroud` in the MiniYaml (`GAP` in `mods/ra/rules/structures.yaml:78-83`, `MGG` in `mods/ra/rules/vehicles.yaml:504-507`).

Separating the two would be the most flexible option.

`CreatesShroud` *currently* derives from `RevealsShroud`:
```c#
	public class CreatesShroud : RevealsShroud
	{
		public CreatesShroud(Actor self, CreatesShroudInfo info)
			: base(self, info)
 		{
```

I'm proposing that that be change to:
```c#
	public class CreatesShroud : AffectsShroud
	{
		public CreatesShroud(Actor self, CreatesShroudInfo info)
			: base(self, info)
 		{
```
where `AffectsShroud` is an absract base class for `RevealsShroud` & `CreatesShroud`.

**Comment by Phrohdoh** [comment]
Could you please reword this? I can't make any sense of it.
>A solution for keeping the ranges in sync would be to have negative a range in CreatesShroud mean use range from RevealsShroud.

**Comment by atlimit8** [comment]
Wording slightly changed and example added.

**Comment by Phrohdoh** [comment]
What should happen if an actor `CreatesShroud` but doesn't `RevealsShroud` and gives `-1`?

**Comment by atlimit8** [comment]
Not sure, either default to 0 or report an error.
Perhaps the best solution would be to default to 0, but have `OpenRA.Utility.exe `*mod*` --check-yaml` report an error.

**Comment by pchote** [comment]
The two traits share the same plumbing, but their functionality is separate.  Linking the ranges of the traits would be a bad idea.

**Comment by atlimit8** [comment]
OK, then they should be completely separated.

**Comment by atlimit8** [comment]
@pchote upon rereading, I wonder if you think that they are currently separate. As mentioned above, `CreatesShroud` **currently** derives from `RevealsShroud`:
```c#
	public class CreatesShroud : RevealsShroud
	{
		public CreatesShroud(Actor self, CreatesShroudInfo info)
			: base(self, info)
 		{
```

I'm proposing that that be change to:
```c#
	public class CreatesShroud
	{
		public CreatesShroud(Actor self, CreatesShroudInfo info)
 		{
```
-or-
```c#
	public class CreatesShroud : AffectsShroud
	{
		public CreatesShroud(Actor self, CreatesShroudInfo info)
			: base(self, info)
 		{
```
where `AffectsShroud` is an absract base class for `RevealsShroud` & `CreatesShroud`.

**Comment by pchote** [comment]
I know that CreatesShroud derives from RevealsShroud - I was responding to the wording of your first post, which sounds like you were thinking that this derivation implies that the CreatesShroud trait also reveals shroud (it doesn't).

You could split the plumbing into a base class and then have two stub classes that inherit it, but I don't see the need.  We are not going to have more than the current two traits that use it.

**Comment by penev92** [comment]
Those two use the same code to do completely different things. Copying all that code from `RevealsShroud` to `CreatesShroud` just to remove the inheritance is a "no". A common base abstract class like `AffectsShroud` would be fine, but doesn't sound like it's worth it. Or maybe it could make the idea easier to understand to new readers?

**Comment by atlimit8** [comment]
It seems wrong to have `CreatesShroud` "is a" (inherit from) `RevealsShroud` when `CreatesShroud` (conceptually) is *not* a `RevealsShroud`. I'm leaning towards creating `AffectsShroud` in `OpenRA.Mods.Common/Traits/RevealsShroud.cs` since that is the smallest remedy.

**Comment by atlimit8** [comment]
It could, in theory, cause problems in the future if code fetches `RevealsShroud` expecting it to mean the actor reveals shroud, or at least that the range is how much shroud is revealed. Reading subclasses shouldn't be required to know how (most) classes function and especially their purpose - `RevealsShroud` serves both to provide reveals shroud behaviour and as a base for `CreatesShroud` which serves a different purpose.

I agree with @penev92 that someone new could may not understand it. In fact, they probably wouldn't look at `CreatesShroud` if they're concerned with revealing shroud behaviour but not shroud creation behaviour.

**Comment by pchote** [comment]
> It could, in theory, cause problems in the future if code fetches `RevealsShroud` expecting it to mean the actor reveals shroud, or at least that the range is how much shroud is revealed.

This is a good point, and more than enough justification by itself to split out an `AffectsShroud` base class.
