### ISSUE TITLE
Rules.ini and Art.ini to MiniYaml converters

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#9305]
The tileset import is a huge success. As TS/RA2 mods have a lot of assets, setting those up manually can take some time. Tasks like setting up basic stats like hitpoints, reveal range, building footprint, overlays are easily automatizable. https://github.com/LipkeGu/CNC-INI-Converter could need a C# conversion, code cleanup and then get integrated as a utility command.

**Comment by LipkeGu** [comment]
as far im familar now with C# so far and could convert it these days phrodoh has also a starting point... as far i know

**Comment by pchote** [comment]
I think this is something best maintained as an external project.  Moving tools like this into the core project significantly increases the barrier to entry (we have stricter code requirements and reviews).  This also makes life harder for on the people working on the core engine/mod code, as we are then forced to change and test stacks of external code on top of whatever we are doing - just think about how much trouble the legacy map and tileset editors caused us.

**Comment by LipkeGu** [comment]
we should wait until we have proper TS support atm there is alot of changing in the rules..

**Comment by Mailaender** [comment]
I don't think this is maintainable outside this repository and it will probably not be found.

**Comment by LipkeGu** [comment]
https://github.com/Phrohdoh/ini2ora

**Comment by Mailaender** [comment]
None of them uses the OpenRA code base and they both don't cover the use-case "get things started". Both are missing sequence definitions which are the most annoying and easiest to automatize. Phrohdoh's makes use of non-existing inheritance and references weapons that are also not set up. So I had to write my own:

* https://github.com/Mailaender/OpenRA/compare/import-sequences
* https://github.com/Mailaender/OpenRA/compare/import-rules

They are not yet finished and don't produce a playable game, but are enough to create stubs you can work with and preview in the map editor:

![image](https://cloud.githubusercontent.com/assets/756669/9833022/5974412c-5989-11e5-89d5-4501c330d5b2.png)

**Comment by Mailaender** [comment]
Added in https://github.com/OpenRA/OpenRA/pull/10714 and https://github.com/OpenRA/OpenRA/pull/10715.
