### ISSUE TITLE
Demo trucks don't explode when destroyed

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#9310]
They only explode when deployed. This is in current bleed.

**Comment by reaperrr** [comment]
Yaml looks fine, probably a bug in `Explodes`.

**Comment by deniz1a** [comment]
They explode in playtest.

**Comment by reaperrr** [comment]
Introduced by #9279.

**Comment by reaperrr** [comment]
Not just demo trucks, unit explosions in general are broken.

**Comment by deniz1a** [comment]
How does that PR cause this? Explodes.cs looks ok here:
https://github.com/OpenRA/OpenRA/pull/9279/files#diff-e04a2cc5f098b4b5187bbbe6904e8af4

**Comment by deniz1a** [comment]
The cause is not #9279. Demo truck explodes with that PR.

**Comment by deniz1a** [comment]
Yes I checked it and #9279 causes this. But how?
