### ISSUE TITLE
turret-move animation?

### ISSUE THREAD

**Issue by ivicok** [OpenRA/OpenRA#9312]
I'm trying to make a mech .shp for OpenRA - it has animated legs and a turret, taken from a separate .shp file

The problem is: the turret simply stays at its position, while it should move relatively to the central mount during the walk animation, e.g. - 
![2-timbgren](https://cloud.githubusercontent.com/assets/13980246/9783025/ee1b6b78-57a1-11e5-995a-7797d90a7d91.gif)

What are the options to implement this? Is it possible to define a specific move animation for turrets? Or do the voxel turrets behave differently from sprites?

this is my base file - ![mc1](https://cloud.githubusercontent.com/assets/13980246/9782995/b1af3d36-57a1-11e5-8bd5-fc7c37f9f198.gif)
##

**Comment by Unit158** [comment]
This will require some custom code, and may be somewhat tricky to do properly.

**Comment by penev92** [comment]
`WithMoveTurretedAnimation`
Nothing is stopping us from having that, and it should be pretty straight-forward to implement.

**Comment by pchote** [comment]
Note that we do this to a limited extent with infantry (their "turret" moves when they go prone).  You can write your own turret subclass that moves the offset in response to whatever arbitrary function fits your artwork.

**Comment by ivicok** [comment]
Is it possible to write such a subclass by editing the .yaml files?

**Comment by reaperrr** [comment]
I've implemented this in my MechCommander mod, I'll submit a PR when I find the time to clean it up a bit.
