### ISSUE TITLE
Firing over barbed wire and sandbags

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#9320]
In the original games, I believe units could fire over barbed wire and sandbags, but that it would block the paths of light vehicles and infantry.

In oRA, these seem to block projectiles too, making them more like cheap weak walls. I think it would be  more interesting to allow units to shoot through them but still block the paths of light vehicles and infantry.

That is unless it is actually a ray-caster issue that these units can't fire over them?

**Comment by pchote** [comment]
Makes sense.  I don't see why we shouldn't do this in TD and TS too.

**Comment by reaperrr** [comment]
Agreed.
