### ISSUE TITLE
Melee ant and zombie fix

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/OpenRA#9331]
I noticed that Ants can't attack diagonal.
Mandible: are using 1c0 as range. Also found zombie with claw does the same.

ants and zombies should get fixed to 1c256 or 1c512.

**Comment by Phrohdoh** [comment]
@TheRaffy this hasn't been resolved yet.

**Comment by TheRaffy** [comment]
Yes, but we have like 2 issues to the same problem. and the other seams to be more solution orientated (Pullrequest).

**Comment by pchote** [comment]
Our conventions are to only close tickets once the PR fixing them has been merged.  This is usually done automatically by including "Fixes #XXXX" in the commit or PR description.

**Comment by TheRaffy** [comment]
That's nice! and makes sence.Thanks for sharing the infomations.
