### ISSUE TITLE
Husks don't chronoshift back to original location

### ISSUE THREAD

**Issue by abcdefg30** [OpenRA/OpenRA#9349]

**Comment by pchote** [comment]
This regression may have been introduced by the husk/viceroid spawner merge?

**Comment by abcdefg30** [comment]
Shouldn't, as I didn't touch that code at all: [Diff](https://github.com/OpenRA/OpenRA/pull/8744/files#diff-72f5025743864a1bd2ce4b95283f1a7bR112)

Will test that though.

**Comment by abcdefg30** [comment]
The bug seems to be already present in 1bc84275fd36a3ad2575a04947855338ecd40ac4, the commit before #8744.

**Comment by obrakmann** [comment]
Is this really a regression? In which release did it use to work? Any chance that this is just a duplicate of #8670?
