### ISSUE TITLE
Units & buildings under GAP are auto targeted when GPS is available

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#9351]
(Playtest 20150830)
If player A's units & buildings are masked by a GAP generator, player B does't have vision of those units or their GPS icons (correct behaviour), however player B's units still auto target (attack move) units and buildings under the GAP.

Test replay: http://www.megafileupload.com/9l4h/GPSunderGAP.orarep

**Comment by pi99y** [comment]
If it helps, I _think_ this is also present in the last release (20150614).

**Comment by penev92** [comment]
Yes that actually would help a lot. If it was present in that, then we can release now without waiting (indefinitely at this point) for a fix.

**Comment by pi99y** [comment]
...but that would be terrible :), it should get fixed now (since it renders GAP generators almost useless).

**Comment by HenrytheSlav** [comment]
We are past the adding new things phase and now only stabilising the branch before release. No new features are being added unless they are crucial bugfixes or repairing the already included stuff for the new release.

I wouldn't say this is major problem.

**Comment by pchote** [comment]
This might be similar / have the same cause as #9037.

**Comment by penev92** [comment]
The replay you provided gives me an "Unknown Map" label so I can't view it.

**Comment by pi99y** [comment]
Yeah, I made a custom map to test this when i posted the replay... I din't know the map is not included with the replay.
This should be the one: http://www.megafileupload.com/dyhJ/testgap.oramap

**Comment by obrakmann** [comment]
A fix for the issue can be found here: https://github.com/OpenRA/OpenRA/compare/bleed...obrakmann:fix9351_fix_gps-gapgen-targeting, but it doesn't quite pass muster yet.

**Comment by pchote** [comment]
Confirmed that this exists in release-20150614 and bleed, so bumping to the next release milestone.
