### ISSUE TITLE
Crash when stealth tank stealths

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#9353]
```
Exception of type `System.InvalidOperationException`: Palette `cloak` does not exist
```

Regression from #8996.  Unfortunately this PR removed the lint attribute that would have caught this error at the same time it made it refer to an invalid palette.

**Comment by Mailaender** [comment]
I had to because of https://github.com/OpenRA/OpenRA/issues/9101. This will be fixed by https://github.com/OpenRA/OpenRA/pull/9358.
