### ISSUE TITLE
D2k : Cannot select all of a certain unit depending where it has been built from.

### ISSUE THREAD

**Issue by Raymond-cnc** [OpenRA/OpenRA#9360]
Okay this is a bit difficult to explain. It is a Dune 2000 bug.

Issue: All units aren't being selected. Example: Click on a combat tank then use the select all unit hotkey. It will select all the combat tanks that were built from the factory, or the starport, but not both. You will see combat tanks that haven't been inlcuded in the selection, those are from the other production facility. To select those too you must shift click one of the other combat tanks and then use the select all unit hotkey.

**Comment by pchote** [comment]
Thanks for the report!
We have already fixed this for the next release.
