### ISSUE TITLE
Add shortcut for "move,land and deploy"

### ISSUE THREAD

**Issue by marcos111** [OpenRA/OpenRA#9374]
Hi!

Is possible add the hotkey for "move to selected point and deploy" for the chooper, APC .....? I think it will be very helpful.

thanks

**Comment by r34ch** [comment]
shift + F would be a nice feature

**Comment by pchote** [comment]
Duplicate of #4774.  You should be able to do this by holding shift while issuing the deploy order, but this doesn't work for transports.

**Comment by marcos111** [comment]
Ok, thanks
