### ISSUE TITLE
Bridge bug(s)

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#9378]
https://www.dropbox.com/s/rnmgqsk5bb9n626/weird%20bridge.orarep?dl=0

im paolo_luigi in this game , top-right player

10:52 - tanya walks to the bridge top right 
![4](https://cloud.githubusercontent.com/assets/9139965/9976813/ecc10bca-5eef-11e5-8f96-fe861877ecb5.png)

11:04 - bridge blows up , 1 harvester gets destroyed ... 2 harvester that was on their way to cross the bridge stopped before the destroyed bridge ... and i could not give them any orders ... i simply lost the control of em 
![2](https://cloud.githubusercontent.com/assets/9139965/9976810/de776faa-5eef-11e5-8d19-9c7b74e52f06.png)

11:09 - started building a engineer to repair the bridge
11:50 - engineer repairs the bridge and the 2 harvesters immediately got destroyed , leaving husks on the bridge 
![1](https://cloud.githubusercontent.com/assets/9139965/9976803/b5b6f824-5eef-11e5-83c9-8102a5ac251a.png)

13:43 - i was giving 1 harvester the order to move somewhere else (while he was on this particular repaired bridge) and then he got stuck on the bridge , i lost complete control of him and couldnt give him any order until the end of the game 
![5](https://cloud.githubusercontent.com/assets/9139965/9976834/73467d1a-5ef0-11e5-9299-4a8a9103f839.png)
##

**Comment by abcdefg30** [comment]
See also #7539.

**Comment by abcdefg30** [comment]
Affects also TD, see #10977.

**Comment by abcdefg30** [comment]
Fixed by #15025.
