### ISSUE TITLE
Harvesters transported by Carryalls are ordered to find resources by the AI

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#9385]
Technically it counts as waiting and idle so it constantly forces path searches for new resources which is expensive and needless. Revealed by the debug message I added in https://github.com/OpenRA/OpenRA/pull/9256.

**Comment by LavenderMoon** [comment]
What would be the best way to handle this? Should we add a state for being transported, or add a specific check to the AI against this?

**Comment by Mailaender** [comment]
Adding `IsInWorld` checks might be sufficient.
