### ISSUE TITLE
visual glitches ubuntu

### ISSUE THREAD

**Issue by shiby77** [OpenRA/OpenRA#9388]
since release 20150614 I do have sometimes visual glitches showing up in games (see attachment). it is flickering and sometimes just appears a few seconds but also can stay for the hole game.

I use ubuntu 15.04 and Mono 3.2.8 (Debian 3.2.8+dfsg-4ubuntu4)
![openra-2015-09-19t210111z](https://cloud.githubusercontent.com/assets/10208403/9978282/fa46f264-5f26-11e5-8fd3-dcc31b864db2.png)

**Comment by Mailaender** [comment]
Try updating your drivers (higher chance something changes) and the Mono version (doubt it's the problem) from external repositories.

**Comment by Mailaender** [comment]
http://www.omgubuntu.co.uk/2016/02/ubuntu-15-04-support-ends-no-more-updates so I am closing this.
