### ISSUE TITLE
Game hangs in the middle of game play

### ISSUE THREAD

**Issue by Tailorware** [OpenRA/OpenRA#9391]
RA Mod
on Windows 8
on i7 12GB lenovo Y70 Gaming Laptop

Game just stops in the middle of game play

Uploaded logs here: https://www.dropbox.com/s/khicz0rx64d0nr5/Open%20Ra%20Logs.zip?dl=0
##

**Comment by clemty** [comment]
at first I thought exception.log hints towards a problem with opening the music file, but then I noticed that that log file is about 2 weeks older than the rest of the log files

**Comment by Mailaender** [comment]
Was it a skirmish game? Were other programs running while you was playing? For some reasons you disconnected due to some kind of network error:

```
Initial mod: ra
Initial map: f00ac3545a04dd454a451919a23cb8c90b90e793
Client 0: Accepted connection from 127.0.0.1:49354.
Order lag is now 3 frames.
Order lag is now 1 frames.
Player @127.0.0.1:49354 is NotReady
Dropping client 0 because reading the data failed: System.Net.Sockets.SocketException (0x80004005): Eine vorhandene Verbindung wurde vom Remotehost geschlossen
   bei System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   bei OpenRA.Server.Connection.ReadDataInner(Server server)
Initial mod: ra
Initial map: f00ac3545a04dd454a451919a23cb8c90b90e793
Client 0: Accepted connection from 127.0.0.1:49357.
Order lag is now 3 frames.
Order lag is now 1 frames.
Player @127.0.0.1:49357 is NotReady
```

**Comment by Tailorware** [comment]
Thank you for the analysis.
Yes I were playing a skirmish game. But there was not much else going on on the PC. Maybe McAfee did  something it should not have done.
I dont know how to go on. Shall I try to reproduce the bug? Is there some thing I can do to provide you with debug infos? Will anyone care?

**Comment by pchote** [comment]
When you say "stops" do you mean that the game completely froze up (nothing worked at all), or did just the gameplay stop, letting you still use the mouse cursor and scroll the map etc.

If you could still interact with the game, then that is consistent with the network error noted above.  OpenRA still uses an internal network connection (from your computer back to your computer - nothing actually goes over the network) for skirmish games, and it is plausible that McAfee thought this was a threat for whatever reason and killed the connection.

**Comment by Tailorware** [comment]
the game completely froze, I saw the "please-wait-circle" and I had to finally kill the game with Alt-F4.

**Comment by abcdefg30** [comment]
Is this still an issue with the latest version?

**Comment by abcdefg30** [comment]
Closing since there has not been any activity since a while.
