### ISSUE TITLE
Disabled dropdown button separator is using the enabled variant

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#9392]
Noticed during testing https://github.com/OpenRA/OpenRA/pull/9387 when seeing the two buttons side by side:

![image](https://cloud.githubusercontent.com/assets/756669/9980458/5137615c-5f9b-11e5-9838-7010d620224d.png)
##

**Comment by LavenderMoon** [comment]
The arrow should be grayed out too, right?

**Comment by dragunoff** [comment]
There is no artwork for the inactive arrow in and no chrome definitions for the inactive arrow and separator.

**Comment by dragunoff** [comment]
This was partially fixed in #17495, #17504 and #17506
![disabled-dropdown](https://user-images.githubusercontent.com/1355810/73105286-4007ed80-3f01-11ea-863e-f6dc3dca0a81.png)

The separator doesn't have a disabled state.

**Comment by PunkPun** [comment]
This is no longer an issue. I assume #17663 fixed it
