### ISSUE TITLE
Dune 2000 mission selector doesn't work well on small resolutions

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#9393]
![image](https://cloud.githubusercontent.com/assets/756669/9980467/9b967bac-5f9b-11e5-8cff-194aa1f6b720.png)

It is overlapping with other (developer) widgets and I can't select fastest from https://github.com/OpenRA/OpenRA/pull/9387.

**Comment by clemty** [comment]
also, the text box for the mission briefing is far too wide - a width of 50-60 (50-75) characters is recommended for legibility: http://baymard.com/blog/line-length-readability (the top line in the screenshots consists of ~110 chars)

**Comment by pchote** [comment]
We could perhaps solve both issues by moving the dropdown boxes to the right, roughly halving the width of the description field.  This would break the symmetry, which might look a bit weird.

**Comment by penev92** [comment]
Just make the mission panel 20 pixels or so shorter, and move the labels + dropdown menus up a bit. It's a very simple fix that doesn't break anything and would look just as good. There is no reason for the mission list to be so long, since we only have 2 missions.

**Comment by pchote** [comment]
That would be a much simpler fix, I agree.

I can incorporate it into #9387 if that doesn't get merged first.

**Comment by pchote** [comment]
I fixed #9387 so this is no longer required.
