### ISSUE TITLE
More options for scrolling with the mouse button and scrolling speeds. [$70]

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#9399]
I'm at a loss to explain but scrolling with the middle mouse button doesn't feel right to me. It would be nice to have an customizable option on this, or to simply be able to choose between several options including the right mouse button.

Seeing that there's been quite a few requests in the past on scroll speed options, I'd like to include in this issue as well. Now also with a small bounty;)

**Comment by penev92** [comment]
I found a number of other issues with the same feature request and did some cleaning, as seen above.

**Comment by SoScared** [comment]
hot diggity-dang

**Comment by LavenderMoon** [comment]
This seems to have two components:

- [ ] Allow using the Scroll button for RA2-style scrolling.
- [ ] Allow rebinding the Scroll button from Mouse 3 to Mouse 2.

(Just jotting some notes down.)

**Comment by SinineSiil** [comment]
https://github.com/OpenRA/OpenRA/issues/9275 bit related - would make scrolling experience a lot better for some.

**Comment by penev92** [comment]
This has also been extensively discussed on IRC many times. Rebinding the buttons doesn't seem very likely to be feasable. The main issue with this is the "left-click orders" mouse setup will need special handling.

**Comment by LavenderMoon** [comment]
I've been wanting to revive my super-flexible FNA controls setup project for a while now, which I was designing to handle stuff just like that. I got the core key/button/etc logic working, but I never got around to analog input (thumbsticks, mouse movement, sliders, accelerometers) and differentiating between clicks and drags (handling C&C style "orders/selection vs box selection" and "deselection vs mouse scrolling" were explicit design goals) or proper (de)serialization. After I dust the bitrot off it, add mouse support, add defaults/profile support (so you can offer defaults of Right-Click Orders and Left-Click Orders), and genericize it so it doesn't rely on any FNA-specific stuff, I'll look into doing that. (This is how I enjoy spending my free time.)

As a stopgap, I'd recommend right-click orders keep "scroll map" on middle mouse for those used to the ORA default controls, and hardcode orders to have left-click orders "scroll map" on right-mouse for those used to the Westwood default controls.

**Comment by SoScared** [comment]
#9518 enables option to scroll with the right mouse button. right on! If we could get the maximum scroll speed increased a for edge scrolling, this issue would close and the bountry go to JoppyFurr (reference penev92) for his TD right click scroll code.

**Comment by SoScared** [comment]
Now that the joystick option for Mouse 2 is up and running, are there any incentive to work on rebinding the Scroll button from Mouse 3 to Mouse 2? Personally I find drag scrolling superior to joystick but using Mouse 3 button, still even after many years, is still very annoying.

I understand the joystick was added in the prospect of TS, RA2. I think it's important to note that the originals had way lower resolutions and needed the joystick as a more effective means to scroll over big distances. On OpenRA, I think the drag-scroll is vastly superior to control the camera, especially on 720p and up. We even have double-pixeling hotkey binded so that most maps can be dragged to a certain location in a split second with drag scrolling. In the end it's a personal preference but I hope there's enough interest to complete this ticket sooner rather than later :)
