### ISSUE TITLE
AI seems to have two BaseBuilders per construction yard

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#9403]
At least in TD. It has a strong tendency to build two radars and two adv. comm. centers even with just 1 construction yard.

So either they have one more basebuilder than they should, or base builders don't stick to their queue type (base or support).

**Comment by reaperrr** [comment]
The AI probably doesn't check whether the build queue is faction-specific, and ends up using both the Nod and GDI queues for building structures/support.

**Comment by pchote** [comment]
HackyAI's `FindQueues` method tries to account for that, but there be other code that doesn't.

**Comment by reaperrr** [comment]
Bad news, it's not just TD. I just spectated an AI game in RA, and the behavior is the same, almost all buildings are built in pairs (only notable exception was tent + kennel, but they're both inf production buildings). It's as if the build order is duplicated to each build queue.
