### ISSUE TITLE
Add damaged actor decorations

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#9409]
D2k (and possibly later games) had vehicles smoking when badly damaged, and buildings having flames here and there.
While purely decorational, it adds a nice feel to the game.
##

**Comment by Phrohdoh** [comment]
Reference #7551

**Comment by penev92** [comment]
I was thinking of something more specific (and simpler to use because of that) like `WithDamagedAnimation/Overlay`, but that could also work.
Depends on how we do other damage-induced changes like reduced speed and such. If we go for upgrades on low health (either on DamageState change or on HP < X%), then `WithDecoration` might be the obvious choice. If not, these traits can directly implement `INotifyDamageStateChanged` and do their thing quite easily.

**Comment by GraionDilach** [comment]
'WithDamageAnimation' sounds good to me, because while vehicles can have it implemented on ^Vehicle, buildings must use offsets to have this. Also TS and RA2 had this feature.

**Comment by reaperrr** [comment]
Maybe we should rename and refactor `Burns`.

**Comment by pchote** [comment]
We have a `WithSmoke` trait for this, which has always been used in RA and TD.

**Comment by GraionDilach** [comment]
`WithSmoke` won't work with TS though - in that one, smoke used particles.

**Comment by Mailaender** [comment]
Tiberian Dawn and Red Alert also had flames on damaged buildings

![image](https://cloud.githubusercontent.com/assets/756669/14409572/9fa4b10c-ff17-11e5-9d07-9492cd9d4d1d.png)

and the exploded buildings left flames as well:

![image](https://cloud.githubusercontent.com/assets/756669/14409584/e7c43b7e-ff17-11e5-9060-3619ad96a011.png)

which isn't implemented yet as well.

**Comment by GraionDilach** [comment]
Maybe one with the rights should remove all mods now that all of them are listed...

**Comment by pchote** [comment]
The flames did damage, and weren't just decorational. @ScottNZ did a prototype implementation ages ago. http://logs.openra.net/?year=2013&month=11&day=21#05:00:39

**Comment by GraionDilach** [comment]
They were only decorational in RA2 from what I remember, even TS had damage on them.

**Comment by pchote** [comment]
Damaged decorations can now be done using conditions and With* traits, so this ticket can now cover adding the flame overlays to the mods.  This would be best done with a new trait that specifies a list of valid WVec positions and a list of sequences that can be drawn at them.  A subset can then be drawn at any time while the trait is active.

**Comment by pchote** [comment]
#13314 and followup PRs set up several targetable positions for each structure which can be used either directly or copied to a new trait so they can be adjusted independently for the flames.

**Comment by PunkPun** [comment]
Nothing was implemented for TS, should this issue issue remain open?
