### ISSUE TITLE
Support "destructible" terrain (D2k style)

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#9410]
Concrete in Dune 2000 is apparently destructible. As you can see [here](https://www.youtube.com/watch?v=6aOen-y6K1g&feature=youtu.be&t=955). That used to be a 3x3 concrete slab just a couple of minutes earlier.
I don't know what are the specific conditions to destroy concrete in D2k, but I suppose it would be pretty easy for whoever decides to do this to ask on [the FED2k forums](http://forum.dune2k.com) and get a quick answer.
##

**Comment by pchote** [comment]
This could be done using similar logic to #8918.
