### ISSUE TITLE
Add "mutators" (minichanges) to the game.

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#9422]
The CnCNet-based clients are famous for having plenty checkboxes for game modes - e.g. http://media.moddb.com/images/mods/1/11/10865/go.png - which are implemented as small ini chunks read between global rules and map rules (or maybe after map rules, notsure on this part). This is really nice from a logic POV as it implies the game settings being absolutely flexible but clutters the UI and doesn't scale well when it comes to multiple mods.

A better implementation would be what UT2004 did - http://i330.photobucket.com/albums/l422/kassulke29/ScreenShot001.jpg - , having a fifth tab in the lobby screen where players could enable/disable these mutators instead of having dozens of checkboxes.

Settings like destructible bridges or harvester immunity would be a great example to be restored this way. Probably this would need mod-specific saved settings though.
##

**Comment by pi99y** [comment]
I like the idea!

**Comment by HenrytheSlav** [comment]
I support it, but 90% of players won't bother checking up to hundreds of possible modifiers (I know I didn't) and never forget that our playerbase is kinda small.

**Comment by pchote** [comment]
This is a decent interface for boolean options, but it would need some iteration to support our drop-down options (starting units, tech level, etc).  Having each choice as a separate mutator would be really clunky.

**Comment by GraionDilach** [comment]
This wouldn't replace the current "Game Settings" tab. I'd only intend this to be used by the misc bool game settings as well.

**Comment by pchote** [comment]
Most of our game settings *are* mutators.  I don't think its a great idea to have two similar concepts split across different panels, especially since we need to unhardcode and move the current set of game options on to trait(info)s anyway.

**Comment by LavenderMoon** [comment]
To clarify, these will be part of the mods themselves/Mods.Common, and not allow the server to create it's own unique mutations, right?

It would be nice to list the mutators each server uses (that isn't set to it's default value) in the server browser, if that could be incorporated into the UI in a feasible way. Allowing the user to filter out servers that (don't) use certain mutator settings would be nice, too, though I imagine that wouldn't play well with the "show incompatible servers" feature, as those can be from different mods and thus would not have the same list of mutators to use.

**Comment by GraionDilach** [comment]
I imagined these being single yamls stored somewhere in a separate folder under the mod code (with the exact depth as map yamls), without any C# code themselves but I guess I didn't think this through.

**Comment by GraionDilach** [comment]
>@pchote i'm still completely unconvinced that interesting game modes can be done independently of the map file

Mental Omega would like to speak with you. There are unique game modes in it which doesn't depend on map rules at all, only strictly global rules (two examples I can tell are Scavengers mode, where crate chances increased, and vehicles must be picked up by them then reverseengineered at conyards to make them buildable and Bomb Derby, where instead of an MCV, you start with a Demo Truck and all your starting support units are terrorists on a bike, asin also suicide units).

**Comment by pchote** [comment]
Sure, but then you're stuck with a limited UI feature that can only show 2 or 3 out of N game modes that a mod might like to implement.

**Comment by penev92** [comment]
<*insert quotes from [this comment](https://github.com/OpenRA/OpenRA/pull/14209#issuecomment-341382353) here*>

**Comment by pchote** [comment]
The discussion in that pr also misses all the things that make this very difficult (and possibly not worth the effort) to implement:
* loading the mutators into a Ruleset in the lobby so that the rule validity checks can be applied
* dealing with mutators that affect the lobby state (modifying or adding bots, factions, or even other mutators)
* linting all possible combinations of mutators

**Comment by MustaphaTR** [comment]
@pchote has a point.

I'm not sure who was it, someone on discord said about adding somthing like a GrantConditionCheckboxLogic, could be a better approach, if not as much as porper mutators, still flexible and shouldn't be hard to do lint checks on them.

**Comment by pchote** [comment]
It would need to be two `GrantConditionOnWorldCheckboxLogic` and `GrantConditionOnPlayerCheckboxLogic` traits (conditions need to target a specific actor), but that could otherwise work reasonably.

**Comment by penev92** [comment]
I believe that was @abcdefg30's suggestion :D (and mine ... or really close to it)

**Comment by GraionDilach** [comment]
I don't want to see this being carried forward. Mutators shouldn't affect the lobby state at all. The first and third point aren't really different from what maps are already doing - it's only mutator-map rules conflicts which are a potential cause of problems which would need resolution, but I don't want to brainstorm on it after the direction this took.

Let this die in peace.

**Comment by Mailaender** [comment]
Reverse duplicate of #14325
