### ISSUE TITLE
Spies dont detect other spies

### ISSUE THREAD

**Issue by MeSaber** [OpenRA/OpenRA#9424]
(Red Alert)
As the description of spies say it detects other spies. However it dont in my tests.

While walking up with a spy to a disguised enemy spy it will still remain disguised and your troopers wont shoot it.

Second fix, when you choose country it says special: spies, however all allies got spies.. it should say cheaper spies (or something like that)
##

**Comment by ScottNZ** [comment]
The special is `British Spy`, which doesn't imply anything happens to regular spies.

**Comment by reaperrr** [comment]
Closed via #12565.
