### ISSUE TITLE
Paratroopers aren't dropped

### ISSUE THREAD

**Issue by Townes27** [OpenRA/OpenRA#9426]
Around 27:30 you can hear the sound when a badger drops the paratroopers but they don't appear even though they could land where they were supposed to.

Player: ð
Replay: http://s000.tinyupload.com/index.php?file_id=65762730555913695461
##

**Comment by matjaeck** [comment]
We tested paradrops in #16564 and nobody noticed such an issue. This has probably been fixed meanwhile.
