### ISSUE TITLE
"Enable Pixel Doubling" on small 4k monitor isn't enough...

### ISSUE THREAD

**Issue by bobosch** [OpenRA/OpenRA#9427]
Tested with Release 20150919 on linux

I'm using a 28" 4k monitor. The units are really small. Even with enabled pixel doubling. Would be nice if this option would be replaced by a "Zoom" (none, 2x, 3x, 4x) option or possibility to use the mouse wheel to zoom during the game.

By the way: The build menu on top right isn't affected by pixel doubling :-(

**Comment by penev92** [comment]
All I can say to this is "tough...".
A 20-year-old game's assets are naturally not meant to be visible on a miniature screen with 4k resolution. Neither are modern-day games, for that matter.
The widgets (radar, build palette, etc.) are intentionally unaffected by pixel doubling.

And "zooming" has been discussed a lot and has been decided it's just not feasable with those assets. Also I'm pretty sure we already have an issue open with a feature request for "zooming", so if you don't mind I'll close this now.

**Comment by GraionDilach** [comment]
A workaround is to specify a custom fullscreen resolution in the user settings - even though the UI hides the width/height boxes when fullscreen is selected, it still works when specified manually.

**Comment by bobosch** [comment]
@GraionDilach The workaround doesn't work here :-( Yes, a possibility to specify the fullscreen resolution would do the trick.
@penev92 Sorry, I found no issues like this. #6405 requests a configurable fullscreen resolution. Would be fine for me, too.
