### ISSUE TITLE
TS component towers are broken

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#9428]
Astor reported 2 issues with the TS component towers (discovered in his own mod):
As it turns out, 3 weeks ago 21186c10b6a37b72402229ca0ac03444eea27dd3 broke the component tower's make animation (possibly for other structures as well).
And 9da56f51e21064088f29e14d90839c27e10f240a broke their firing.

I was unable to find any other broken actors.

**Comment by reaperrr** [comment]
I swear I noticed and fixed the make animation before it was merged, no idea how this got broken again.

**Comment by reaperrr** [comment]
What I suspect is that we have an initialization order issue here. I can imagine that this happens because the render traits need to be loaded after `Building`, but we can't make `WithSpriteBody` require `Building` for obvious reasons.

In other words, we probably need #8848 to fix this.
