### ISSUE TITLE
New stance: HoldPosition+Fire

### ISSUE THREAD

**Issue by MeSaber** [OpenRA/OpenRA#9429]
(OpenRA)
Many times you want your troopers to not move and still be able to fire (without being fired at first 'ReturnFire')

But there is no such stance right?

'Defend' stance chases after enemies if im not totally mistaken.

I see much strategical depth in this stance, where usually the other stances fail at doing so because they have a free will to move without being told so and dying.

**Comment by ScottNZ** [comment]
Defend does not chase. AttackAnything does.

**Comment by penev92** [comment]
Defend just sits there, shooting at anything in range. Same as HoldPosition in other games.

**Comment by MeSaber** [comment]
ok thx.. then someone mislead me to think defend chases.. sorry
