### ISSUE TITLE
AI Hind instantly spotting enemy cammo. pillbox

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#9432]
(Release: 20150919)
In the attached replay at ~4:41min you can see an AI Hind instantly attack a cammo. pillbox that has not attacked yet.

http://www.megafileupload.com/5cbi/AIdetectingSpies.orarep

**Comment by abcdefg30** [comment]
Duplicate of #2959.

**Comment by pi99y** [comment]
Wait, is this really the same as the spy problem?

**Comment by abcdefg30** [comment]
At least similar https://github.com/OpenRA/OpenRA/issues/2959#issuecomment-18122475.

If you wish I'll reopen this though.

**Comment by pi99y** [comment]
I guess it's ok to close it then :)
