### ISSUE TITLE
How to compile for Linux?

### ISSUE THREAD

**Issue by YuGiOhJCJ** [OpenRA/OpenRA#9433]
Hello,

With OpenRA-release-20150919, I do:
$ make dependencies
Fetching StyleCopPlus from NuGet
Fetching StyleCop files from NuGet
Fetching ICSharpCode.SharpZipLib from NuGet
Fetching MaxMind.GeoIP2 from NuGet
Fetching SharpFont from NuGet
Fetching NUnit from NuGet
Fetching Mono.Nat from NuGet
Fetching FuzzyLogicLibrary from NuGet.
Fetching SDL2-CS from GitHub.
Fetching Eluant from GitHub.
Detected Lua 5.1 library at /usr/lib/liblua.so.5.1.5
Eluant.dll.config has been created successfully.
Updating GeoIP country database from MaxMind.
$ make all
CSC fixheader.exe
make: dmcs: Command not found
make: *** [fixheader.exe] Error 127

I am following the instructions from the "INSTALL.md" file in the "Linux" section.

What am I doing wrong please?
A missing requirement?

Thank you.
Best regards.

OS: Slackware 14.1
Kernel: Linux 3.18.20

**Comment by abcdefg30** [comment]
I probably can't help as I'm on windows, but does using only `make` work (without `all`)?

**Comment by ihptru** [comment]
Looks like there is no mono compiler on your system, try to install `mono-dmcs`. I also think this package is included into `mono-complete`

**Comment by GraionDilach** [comment]
Yes, `mono-complete` installs `mono-dmcs`.
