### ISSUE TITLE
Can't scroll while the graphical UI is hidden

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#9434]
Ctrl + Shift +H (hiding the UI)..  locks the screen , literally ... this might be good for a slow static screenshot of something ... but you probably cant make  a "series" of quick screenshots ... or a video

i think this #8582 is not the fully solution for #6779
##

**Comment by Micr0Bit** [comment]
i relate #9434 in case someone want to fix it ...

**Comment by pchote** [comment]
The hide UI hotkey was removed in release-20180305.
