### ISSUE TITLE
Starport frigates clock at the border of the map instead of exiting

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#9439]
Can be observed in @SoScared's stream: https://youtu.be/VfoRznIOAKI?t=43m13s I don't know the map so I can't exclude a border error in the map definition. This is also not good performance wise, because the delivery actors are never cleaned up.
##

**Comment by penev92** [comment]
For the record that is "Battle for Dune" and is one of the official maps.

**Comment by MustaphaTR** [comment]
Can't watch the video right now, but is that the same issue with TD Cargo Planes, when Airfield is too close the edge and Plane can't get enough altitude and is not deleted. And isn't that already fixed.
