### ISSUE TITLE
Spatially partition IEffects

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#9443]
We render every effect in the world, including those that are outside the screen bounds.  Adding a new `SpatiallyPartitioned<IEffect> partitionedEffects` to ScreenMap for use by the WorldRenderer should give us a reasonable rendering performance win.  As an added bonus this should cut the rendering workload to the point where it is feasible to interleave actor and effect renderables, which fixes a big chunk of polish issues.

**Comment by RoosterDragon** [comment]
Is the interleaving as simple as ensuring both the actors and effects are affected by the sort in `WorldRenderer.GenerateRenderables`? If so we can already afford that on the RA shellmap easily.

**Comment by Mailaender** [comment]
I tried a simple approach without partiion IEffects https://github.com/Mailaender/OpenRA/tree/effects-viewport but it seems sprites have a different definition of screen bounds compared to all other renderables

**Comment by pchote** [comment]
Your definition of the viewport bounds are incorrect in that branch.  That will cause you to render effects on only 1/4 of the visible screen.

**Comment by pchote** [comment]
Fixed by #13979.
