### ISSUE TITLE
In-game mod browser/installer

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#9455]
https://github.com/OpenRA/OpenRA/issues/9028 and https://github.com/OpenRA/OpenRA/issues/9029 are good ideas, but they have bad discover-ability by the players. They need to already know that thirdparty mods exist, where to find them and that you can install those just like browser addons. This proposal may however not exclude the previous ideas of "manual" installations from URLs and in-game updating, but rather complete it.

Other Open Source game engine projects already solved this:

Inspiration:
- https://bananas.openttd.org
- https://springrts.com/wiki/Games

An in-game browser lists assets and mods available for download via the repository. That way you can discover a whole palette of mods you didn't know about. Downside is that this relies on a (yet non-existing) web-service. It may be in the scope of http://resource.openra.net though. Might also be the best way to ship mini mods ("mutators") https://github.com/OpenRA/OpenRA/issues/9422.

With the rejection of https://github.com/OpenRA/OpenRA/pull/9396 I thought this further. If separating mods and engine completely is the preferred way, we probably need this badly so people don't first start the game and see "Choose your battlefield: no mods installed" and quit, uninstall, comment "doesn't work", because they forgot to click on an `openra-mod://mods.openra.net/ra-release-2042-10-23.zip` URL somewhere hidden in the news post.

We probably have to ship a blank engine with just a `modbrowser` mod. A benefit of not including any non-free content and downloading everything on first game start may be that this open the doors for inclusion in official Linux repositories if we ever want this especially in ones with long release cycles.

Synchronizing the releases of all currently supported mods together with the engine isn't a trivial matter though and probably will lead to some player base fragmentation. On the other hand, very actively developed mods don't have to wait for another release cycle to do balancing adjustments etc.
##

**Comment by x-a-n-a-x** [comment]
I totally love this idea. :+1:  
The arguments explained here make sense.

Tbh, I also thought about this idea a while ago but for maps (similar to #3357 ?).
But I think this idea could indeed be expanded to mods vith an online mod browser.

**Comment by pchote** [comment]
The implicit suggestion from #9028 and #9029 is that the resource center would then be use used as the map and mod browser.  That gives a much better browsing experience and is *much* less work to implement than a custom in-game mod browser.

**Comment by pchote** [comment]
> Synchronizing the releases of all currently supported mods together with the engine isn't a trivial matter though and probably will lead to some player base fragmentation. On the other hand, very actively developed mods don't have to wait for another release cycle to do balancing adjustments etc.

This is now covered by #12554, and the centralized database of mods is covered by https://github.com/OpenRA/OpenRA-Resources/issues/204.
