### ISSUE TITLE
Lua: standardize naming of player?

### ISSUE THREAD

**Issue by clemty** [OpenRA/OpenRA#9456]
Currently, for TD missions the player is either referenced as "GDI/Nod" or "player"
- `player = Player.GetPlayer("GDI")` (gdi01)
- `gdi = Player.GetPlayer("GDI")` (gdi04a)

should this be made consistent throughout all TD missions?

I'd prefer to always use "player/enemy" for factions for two reasons:
- makes code more readable
- makes code more reusable (copy&paste a function from a gdi to a nod mission without having to deal with gdi/nod mixups; also half the missions capitalize the player as "Nod", the other half as "nod")

this should reduces the chance for bugs (uppercase VS lowercase "GDI", and accidentally referencing the wrong player)
##

**Comment by penev92** [comment]
Sure, sounds reasonable.

**Comment by abcdefg30** [comment]
We probably want to use `Player` then, as it's a global variable.
> Public variable names are PascalCase.

**Comment by clemty** [comment]
that won't work: it would lead to
```
Player = Player.GetPlayer("GDI")
Enemy = Player.GetPlayer("Nod")
```

which leads to:
```result = string: "[string \"BindingSupport.lua\"]:30: Player 'clem' does not define a property 'GetPlayer'"```

**Comment by abcdefg30** [comment]
Oh, yeah. Forget it then.

**Comment by obrakmann** [comment]
Personally, I prefer using the real faction names. Using player/enemy works in TD, since there are only two factions, but as soon as you get to RA or D2k, you run into problems with that scheme.

**Comment by clemty** [comment]
currently RA and D2k use ```player``` for the player, and faction names (in lowercase) for the enemies. TD has a few instances where a third faction is needed (abandoned GDI base, Civillians), a descriptive string is used in these cases

**Comment by atlimit8** [comment]
An alternative that keeps PascalCase would be `LocalPlayer`  and `EnemyPlayer` (or just `Enemy`). `World.LocalPlayer` is the engine's reference to which `Player` is controlled by the user.
Others could also use the `Player` suffix (ex: `GdiBasePlayer` for an abandoned GDI base).

**Comment by pchote** [comment]
In our scripts *all* script defined variables are local.  The "global" variables in this case are our api provided tables.  Having capitalised script variables just confuses things, IMO.

**Comment by atlimit8** [comment]
If script variables can be directly accessed by other scripts if they are loaded by the same map, then then it is some kind of public global scope. However, I am fine with all Lua variables starting with a lowercase letter and the exposed API with a capital.
