### ISSUE TITLE
Invisibility issues

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#9470]
I did a test game to try to show this properly.
[Here](https://www.dropbox.com/s/tw1w9bu7zkql5a4/OpenRA-2015-09-27T231419Z.orarep?dl=0) is a 5-minute-long replay. The version is commit 0e9257abcf39e2118b7b53df5c9f13fad429b828. The mod is TS.

 - At first AI ignored my stealth generators. Then at some point just decided to get rid of them (admittedly I may have missed it building an unit with stealth detection).
 - Notice how the titan doesn't stop firing at my soldiers when they restealth. Infantry around the titan don't, which may mean it has something to do with turret targeting.

**Comment by reaperrr** [comment]
Might be something in AttackTurreted then.
