### ISSUE TITLE
Editor: cash counter on individual resource field

### ISSUE THREAD

**Issue by senneschall** [OpenRA/OpenRA#9477]
Feature request: a text box on each individual resource field so map balancing becomes easier.

Similar to other games, see -> http://www.kamremake.com/wp-content/uploads/2014/01/maped2.png

**Comment by StexoO** [comment]
https://github.com/OpenRA/OpenRA/issues/3377#issuecomment-84567459 ?

**Comment by penev92** [comment]
That wasn't implemented though. Currently there is just a global counter.

**Comment by HenrytheSlav** [comment]
Definitely :+1: for Idea, saves a lot of time.

**Comment by Mailaender** [comment]
The downside of my tooltip over the patch was that finding all the neighbors was very CPU expensive (at least the way I implemented it) although usability was nice. An easier to implement approach suggested by @pchote was to allow a selection square lasso similar to how the mine layer works, but probably with just the borders rendered not sprite overlays (like we did the minelayer in past releases) and then update the counter at the top accordingly.

**Comment by Mailaender** [comment]
In fact it wasn't that expensive. I just had an infinite loop problem and re-calculated the patch whenever the mouse moved a pixel rather than traversed into a new cell. Fixed those problems and resubmitted my improved attempt again in https://github.com/OpenRA/OpenRA/pull/14055.

**Comment by PunkPun** [comment]
You can now count with #21315
