### ISSUE TITLE
Add "Install Content" support for C&C The Ultimate collection.

### ISSUE THREAD

**Issue by ebajumpaa** [OpenRA/OpenRA#9479]
C&C the ultimate collection looks to be windows only, and requires Origin, as it's a digital only collection.

would require identifying if the OS is windows, Origin is installed, and the game needed is installed.
Then Identifying the path of the installed game.

* registry path for windows xp: `HKEY_LOCAL_MACHINE\SOFTWARE\\EA Games\Command and Conquer Red Alert\Install Dir\`
* registry path for 64bit(OS) 7,8, and 10: `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\EA Games\Command and Conquer Red Alert\Install Dir\`

**Comment by pchote** [comment]
I have a mostly finished prototype of this at https://github.com/pchote/OpenRA/tree/more-installers.
