### ISSUE TITLE
Creating a new unit SHP - alternative

### ISSUE THREAD

**Issue by ivicok** [OpenRA/OpenRA#9481]
An alternative method to the other tutorials - https://github.com/OpenRA/OpenRA/wiki/Creation%20of%20a%20new%20unit%20for%20OpenRA%20(step%20by%20step) and https://github.com/OpenRA/OpenRA/wiki/Converting-a-3D-infantry-model-to-sprites

I'm using three programs - 3dsMax 9, Bulk Rename Utility (http://www.bulkrenameutility.co.uk/Download.php) and SHP Builder (http://www.ppmsite.com/?go=shpbuilderinfo)

**3dsMax**: we make a model with a shadow plane and sunlight, eventually also spotlights from opposite sides, if some faces get too dark;
- for a usual tank, I'm using 32 cameras placed in a circle above the model clockwise; 63° from the infantry/sprite tutorial is a good angle (an example here - https://drive.google.com/file/d/0B5zJIBBQb3EhQnhjczM0U0Zublk/view?usp=sharing)
- if you're not using TS-like voxel barrels, it's good to make them somewhat larger; they tend to lose pixels in conversion

**3dsMax rendering**: first, as the tutorials mention, you need to turn off anti-aliasing, namely under the Rendering/Render Scene/Renderer and Customize/Preferences/Rendering
- under Render Scene/Common Parameters I'm setting only the Output Size 420x420
- the actual rendering is made by the Rendering/Batch Render function: here we Add 32 entries (or as many cameras you made) and for every one we set an output file (for the sake of simplicity, the example uses from 1 to 32.png; 24bit RGB)
- if you're rendering an animated model, you have to set the output Range under Render Scene
- clicking Batch Render button then creates you 32 .png's
- it takes time, but a file with a preset Batch Render can be used as a template for other models
- if the unit has a turret, do two renders: one for the chassis, the other for the turret; just make sure you don't overwrite the first output

**Bulk Rename Utility**: let's open the program and drag and drop all the .png's we've made inside, sorting them by name
- under Remove we can chose the digits 0123456789; under Add/Prefix we choose the unit name; finally under Numbering we create a Suffix, starting at 0, Incr. 1, Pad 4 (important for SHP builder)
- then we select all the files and Rename

![bru](https://cloud.githubusercontent.com/assets/13980246/10158028/6c2bcb9c-668f-11e5-8325-0af638955690.png)

**SHP Builder**: now we can make a single .shp file from the output pictures; open the program, choose File/Import and select the first frame (name0000.png)
- select the optimization; under Frame Size choose the desired frame size (e.g. infantry 50x39, mammoth tank 48x48), under Extra Settings choose Auto select background by pixel 0,0; then, click ok
- use the fifth tool icon Replace Color to select the correct colors for team and shadow; beware the dark shades receiving the background color (0 in RA palette)
- now we save it as SHP(TS) and put to our mod/bits

**Comment by GraionDilach** [comment]
That wiki article was made by a modder a while ago. I understand your intention but this is the wrong place for it - you should probably repost this to the forums.

**Comment by pchote** [comment]
@GraionDilach: or moved directly to a wiki article.

**Comment by penev92** [comment]
Well this is the right thing to do. Definitely better than quietly updating the wiki without getting feedback first. ;)

**Comment by ivicok** [comment]
I'd be happy to add it as a commentary to the wiki, just I don't know how... As an issue, it can be accessed by a practical url, at least.

**Comment by Mailaender** [comment]
I suggest you create a new wiki page https://github.com/OpenRA/OpenRA/wiki/_new and link it at https://github.com/OpenRA/OpenRA/wiki/Pixelart.

**Comment by ivicok** [comment]
ok, the new page is here - https://github.com/OpenRA/OpenRA/wiki/Creation-of-a-new-unit-for-OpenRA-%28alternative%29

**Comment by x-a-n-a-x** [comment]
Thank you ivicok for your tutorial. I am sure it will help modders a lot.

It's always nice to have alternative ways to create SHP files, especially since it's not possible to create them with the OpenRA.Utility (under Windows) anymore. Long story [here](https://github.com/OpenRA/OpenRA/issues/4426).

**Comment by ivicok** [comment]
I'm not using IRC, but you can contact me here, FB or twitter anytime, and I'd be happy to help, as far as I can
