### ISSUE TITLE
Scatter() sometimes fails to clear the actors from their current positions

### ISSUE THREAD

**Issue by simon-v** [OpenRA/OpenRA#9484]
Often Scatter() is used in scripts to clear actors from a position. Unfortunately, the underlying Nudge() function does not quite insist on choosing a cell that is not the one where the unit is right now as the destination for the move. As a result, there is always a chance that an actor that was ordered to Scatter() stays where he is, which is probably not what was intended.

@pchote thinks it would be "easy" to add this. Me, i don't understand the relevant piece of code well enough to tell if that's the case.

**Comment by obrakmann** [comment]
There already is a `Scatter` method, and it's doing exactly what you describe (even the forcing bit).

The only instance where it would fail if there aren't any neighboring cells which the unit could enter.

However, the actual move activity is a queued action. Are you maybe immediately calling `actor.Stop()` after `actor.Scatter()`? Then the move to the neighbor cell would be canceled.

**Comment by simon-v** [comment]
What i did was:
```Utils.Do(BunchaGuys, function(a)
    if not a.IsDead then
        a.Scatter()
    end
end)```
I urge you to show me my mistake.

As a clarification, it only happened once during all of my tests. Unfortunately, Scatter() working properly 99.9999% of the time is not quite good enough, because it requires the application of hacks to make it work in cases when you specifically *need* those BunchaGuys to clear the area.

Meanwhile, it has been suggested that the canceled move order might be related to #5968. If that is the case, could someone suggest a sensible workaround until this gets addressed?

**Comment by simon-v** [comment]
My code contains now
a hack ugly like warfare;
This issue is closed.

**Comment by pchote** [comment]
> it requires the application of hacks to make it work in cases when you specifically need those BunchaGuys to clear the area.

It sounds like you're trying to use the scatter feature for a use case that it wasn't intended for.  If you absolutely need units to move outside of a specified area then you may want to issue explicit move orders instead.

**Comment by penev92** [comment]
By the way, our Scatter could use some improving based on the code from #9239.
