### ISSUE TITLE
Cursor disappearing after changing video mode

### ISSUE THREAD

**Issue by Super6-4** [OpenRA/OpenRA#9490]
Release:
20150919 (Latest)

Reproduce:
1. Backup and remove your settings.yaml
2. Start OpenRA and load a mod (in my case, Red Alert)
3. Open settings, and change Mode from Pseudo-Fullscreen (default), to Fullscreen
4. Choose Restart Now (Restart Later seems to have the same effect)
5. No cursor, and restarting OpenRA again will not fix the issue

If you back out to the Mod screen, the cursor will reappear. If you then load a mod, the cursor will remain visible (temporary fix, at least until another OpenRA restart).

**Comment by Super6-4** [comment]
Seems to be fixed in playtest 20151031

**Comment by penev92** [comment]
That's good news.

**Comment by kohenkatz** [comment]
I am experiencing this bug again in playtest 20151129.  The described steps to reproduce and the temporary workaround are the same as in the original bug report.

**Comment by penev92** [comment]
See #10172, which is a more general issue for the same problem.
