### ISSUE TITLE
Replay viewer and observer should enable selecting unit type by double clicking units

### ISSUE THREAD

**Issue by SoScared** [OpenRA/OpenRA#9492]
This was possible with earlier releases, and seem to have got lost in later development. It was so nice to  double click units (especially key units, e.g. harvesters, aircrafts...) as an observer and quickly see the amount of them. Same thing with structures. I'm hoping this is something that can easily come back to us.
##

**Comment by obrakmann** [comment]
It's already possible, even in the current release, but only in per-player views. Please let us know if that is sufficient for your use case.

**Comment by SoScared** [comment]
Oh ok! I never figured that out. Also now just learned that you can switch between per-player views in teams by pressing the same team view button. Obviously it would be more convenient having the option with all-players/shroud-disabled (e.g. battles and quick turn of events) and make future casting more seamless. If it's not too much trouble I'd love to have the ticket open in hopes of someone having a stab at it.

**Comment by matjaeck** [comment]
@SoScared can we close this as a reverse duplicate of #16044 which has more activity and a PR that addresses the issue?

**Comment by SoScared** [comment]
Fine with me!
