### ISSUE TITLE
Show server browser and lobby at the same time.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#9493]
Something like this? 
That way you can tell if everyone else is hopping onto another server and can go join them.

Over 5000 hours in MSpaint:
https://lh3.googleusercontent.com/-U6kHc13Rv6M/Vgv_GHQa6tI/AAAAAAAABaY/7_xfWtizmVI/s1280-Ic42/openRA%252520servers.JPG

**Comment by pchote** [comment]
The next release will include a redesigned lobby and server browser interface, which will let you chat with people in the server browser and in other servers.
