### ISSUE TITLE
Remove redundant actor GADPSA from TS rules

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#9497]
I guess all the rebases caused #9124 to drop the GADPSA removal. With the MobileSensorArray using upgrades to deploy now, that actor has been made redundant and is currently unused YAML.

**Comment by Mailaender** [comment]
:-1: This will break map import and complicate editor actor placement. https://github.com/LipkeGu/TSIniFiles/blob/master/rules.ini#L4231

**Comment by pchote** [comment]
It doesn't need to - the ts importer can include an actor translation table like all of our editors do for overlays and like d2k does for actors.

**Comment by Phrohdoh** [comment]
Just to bring this to everyone's attention:
The reasoning above breaks half of the argument for not renaming actors.
>the ts importer can include an actor translation table

1) map import
2) familiarity

**Comment by penev92** [comment]
FWIW I'd like to break that argument entirely. ;)
