### ISSUE TITLE
Filename case inconsistencies

### ISSUE THREAD

**Issue by GraionDilach** [OpenRA/OpenRA#9498]
Okay, so where to begin, right now OpenRA treats filename-cases quite serious sometimes.

Filenames of loose files under Windows are case-insensitive.
Filenames of loose files under Linux are case-sensitive.

Filenames of files inside MIXes will be case-insensitive in all OS. I didn't tested bag or big, but I assume them being the same as mix.

Consistency can only be achieved if the game starts to pretend to be fully case-insensitive at Linux but noidea if that worths it. Per asset hacks like the one suggested at https://github.com/OpenRA/OpenRA/pull/9483#issuecomment-144515789 are definitely not helping IMO.

**Comment by LavenderMoon** [comment]
It's worth considering that enforcing case-sensitivity for loose files on Windows would likely have a lower overhead and have less gotchas than enforcing case-insensitivity for loose files on Linux. For example, what do we do if we're looking for `rules.ini`, and all we have are files called `Rules.ini` and `RULES.INI` in the same directory? Of course, that leaves us with case-sensitivity for loose files and case-insensitivity for packaged files.

**Comment by penev92** [comment]
That case should never happen. It's a design flaw if you have such a case.

**Comment by pchote** [comment]
I agree.  The OpenRA engine and default mods are designed to be case-sensitive, and if a windows-based modder decides they want to screw things up by having multiple files with conflicting names, then it is their problem to fix it.

**Comment by penev92** [comment]
You mean *nix-based. That's not possible on windows.

**Comment by LavenderMoon** [comment]
So how do we tackle this? Do we enforce case-sensitivity for case-insensitive file systems (NTFS) and have the linter throw an error when it finds a file that is a case-insensitive match for file that isn't found?

**Comment by pchote** [comment]
I'm not sure we can/should.  A case-sensitive file presence lint check would be the best bet, but we can't do that because our lint tests are run on travis, which doesn't have a copy of the game assets (and so will fail by default).

**Comment by GraionDilach** [comment]
You guys went off here a bit. The issue is that MIX contents will always be case-insensitive - as long as there's a `redalert.mix`, *nix systems will find `E1.SHP`, `e1.shp`, even `e1.sHp` within the mix.

(Actually used example, we're using capital letters in TS sounds, while Mixer renders them in small case - infact, Mixer only renders something in capital letters if it's an ID or was saved as such in the XCC LMD but the LMD format isn't a WW format and something only Mixer uses, and there are also tools for creating mixes which does not create LMDs to parse for over-sensitivity checks).

**Comment by pchote** [comment]
We use capital letters for TS sounds for consistency with the original rules.ini.  Mix is the only case-insensitive package, because it doesn't store filenames at all.  In the future we will probably change it so that we only accept filenames that are specified in the global or local mix databases, which then lets us remove all of the horrible special-case code in the engine that works around the missing filenames.

**Comment by LavenderMoon** [comment]
@pchote I meant we should throw an error if we don't find `Rules.ini` or such, but do find `RuLeS.InI`. If there's no files, then Travis wouldn't fail.

**Comment by GraionDilach** [comment]
This was tackled with the recent use-filename-from-XCC-gmd/lmd-instead-of-hashing PR by @pchote.
