### ISSUE TITLE
Multiple units commanded to service depot causes stuck units

### ISSUE THREAD

**Issue by mtnguyen100** [OpenRA/OpenRA#9503]
Sometimes if several units are commanded to be repaired at a single Service Depot, if a rally point is set to a location parallel to a unit that is sitting next to the Service Depot, the unit that has been recently repaired will be stuck at the Service Depot. Although this can be fixed by a simple micro of the unit to another direction, players may not notice it before it is too late.
##

**Comment by obrakmann** [comment]
Units will exit the repair pad in the direction of the rallypoint. Immediately after placing a repair pad, I usually set the rallypoint to the opposite direction of the front lint (ie. opposite from the direction where damaged units would most probably approach from) to prevent this issue. This will mitigate most instances of stuck units.

However, we could of course try other exits when the immediately obvious one is blocked. That doesn't currently happen.

**Comment by anjew175** [comment]
Not only does a unit on the exit block unit movement  but a unit on the entrance will stop it from entering and buildings + terrain will stop a unit following the rally point as it tries to take the quickest route (straight) and becomes stuck. (steps to reproduce: place a building between the repair pad and its rallypoint ending).

I noticed something very unique though, this rally point will cause the unit to actually displace every unit along the route UNLESS the other units came from the rally point. This is only attributed to the repair pad, all other rally points work as normal.

**Comment by matjaeck** [comment]
> Sometimes if several units are commanded to be repaired at a single Service Depot, if a rally point is set to a location parallel to a unit that is sitting next to the Service Depot, the unit that has been recently repaired will be stuck at the Service Depot.

> Units will exit the repair pad in the direction of the rallypoint, so if that cell is blocked, they won't leave.

> Not only does a unit on the exit block unit movement but a unit on the entrance will stop it from entering and buildings + terrain will stop a unit following the rally point as it tries to take the quickest route (straight) and becomes stuck. (steps to reproduce: place a building between the repair pad and its rallypoint ending).

This is fixed, the unit blocking the exit cell will move away and if the path to a rally point is blocked, units will move around the obstacle. The unit only gets stuck on the depot when the rally point is unreachable (#15995).
