### ISSUE TITLE
D2k grenadier idle animation looks wrong

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#9516]
The white line above his head is the weapon offset, shown by the combat debug overlay (the offset is wrong, but ignore that for the moment).
The issue is that he is facing one way, while the animation seems to be facing the other.

![](http://i.imgur.com/fc61q40.png)  ![](http://i.imgur.com/exm9sSS.png)

**Comment by Mailaender** [comment]
See https://github.com/OpenRA/OpenRA/issues/10806.
