### ISSUE TITLE
D2k cloak sounds

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#9519]
Dune 2000 only has a cloak sound on the Saboteur. Fremen and Stealth Raiders don't get cloaks sounds.
And none of the above 3 actors has an uncloak sound.
##

**Comment by abcdefg30** [comment]
Do we really want no cloak/uncloak sound on some units?

**Comment by penev92** [comment]
I personally don't even pay attention at all. It was @pchote who pointed out our fremen sound annoying, so I checked the original game and opened this issue.

**Comment by riiga** [comment]
I thought I'd fix this, but it seems to be fixed ingame and in the yaml files already, so perhaps the issue should be closed?
