### ISSUE TITLE
Resources growing/spreading logic should be configurable seperatly from each other

### ISSUE THREAD

**Issue by Dutchygamer** [OpenRA/OpenRA#9525]

**Comment by penev92** [comment]
Also as I understand, those work separately in TS.

**Comment by pchote** [comment]
Duplicate of #9524.

**Comment by penev92** [comment]
Not as far as I understood it.  :?

**Comment by GraionDilach** [comment]
The resource seed splitting should be configurable per resource. #9524 is just related. I can understand why they overlap but even then that other issue should be closed then.

**Comment by Mistranger** [comment]
Done: https://github.com/OpenRA/OpenRA/pull/13428
