### ISSUE TITLE
Pillbox does not shoot infantry on a specific spot

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/OpenRA#9529]
force fire gets rejected ... and it does not get triggered when its a enemy unit 

![pillbox fire](https://cloud.githubusercontent.com/assets/9139965/10265370/18b97c28-6a2e-11e5-95b4-b060ea76b155.png)

**Comment by MicroJOo** [comment]
still present in 20151224

![redline](https://cloud.githubusercontent.com/assets/9139965/12059541/8ed76a04-af5d-11e5-92ee-cb83f62dbac9.png)

**Comment by atlimit8** [comment]
They look like they might not be in one of the fire port cones.

**Comment by Phrohdoh** [comment]
An overlay for that would be useful.
Even if it is just a simple triangle.

**Comment by pchote** [comment]
There is an overlay for this (combat debug).

**Comment by pchote** [comment]
Reproduced and confirmed that it is along the line of the fire cones.  Increasing the angle by 1 to ensure there is an overlap between adjacent ports should fix this.

![screen shot 2015-12-31 at 18 16 41](https://cloud.githubusercontent.com/assets/167819/12067048/d7a1b32e-afea-11e5-91c0-a2fee0db901a.png)

**Comment by r34ch** [comment]
Appears to be the same issue as #7536

**Comment by Snurre86** [comment]
![yrajipg](https://cloud.githubusercontent.com/assets/7798635/6340441/923bb0d4-bbbf-11e4-9cec-4c8a987780fe.png)

**Comment by Snurre86** [comment]
This seems to be the top right guy in the tile that the pillboxes can't target (shown in red in the picture).
![untitleddghd](https://cloud.githubusercontent.com/assets/7798635/12224491/609a1752-b7f2-11e5-8b4b-1458cac5a44e.png)

**Comment by Micr0Bit** [comment]
thx @abcdefg30
