### ISSUE TITLE
"Go to base" hotkey doesn't work when cheats are enabled

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#9530]
[This query](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Widgets/WorldCommandWidget.cs#L194) returns an empty list, because `world.RenderPlayer` is `null` for some reason. This is happening in a normal game, where I am an active player.
From there onward nothing happens.

P.S.: Seems to be a regression from #9307.

**Comment by obrakmann** [comment]
Your report is confusing for several reasons:

1. when you're playing yourself, while the game is running, `RenderPlayer` should never be `null`, except if you have cheats enabled and shroud disabled.

2. The code you linked to has nothing to do with the Home key. 'Home' centers the screen on the selection, it does not cycle between base buildings (that's the 'H' key).

3. Both 'Home' and 'H' work for me on bleed.
