### ISSUE TITLE
Make game last a few more seconds after it ended

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#9538]
Just 3 seconds more would allow more die/nuke/fun things after game ends.

**Comment by MicroJOo** [comment]
we could add the same logo at the end as in the original ... in those 3 seconds (also one for "failed") 
im not sure about the other mods what their endscreen looked like , cant remember

![missacc](https://cloud.githubusercontent.com/assets/9139965/10268547/dfd8c122-6abc-11e5-91a0-af332136abcc.png)

**Comment by obrakmann** [comment]
This is already possible. See the `GameOverDelay` property of the [`MissionObjectives`](https://github.com/OpenRA/OpenRA/wiki/Traits#missionobjectives) trait. It does exactly what you're asking for, and has existed for over a year. You can set it yourself in custom maps. There's upper limit of 2147483647, which corresponds to a bit more than 24 days, which will probably be enough.

The current delay of 1.5 seconds is used to keep sound effects from overlapping with the end game video. It is unlikely that that will be changed in shipped mods.

**Comment by MicroJOo** [comment]
someone removed my comment here and then closed the issue , so ill just post it again ... 

what i said was , if we had little time-window we could add the "mission accomplished" the original used

![mission acc](https://cloud.githubusercontent.com/assets/9139965/10451788/9a748066-71a2-11e5-9daa-54c133851fc7.png)

**Comment by kyrreso** [comment]
Like in World-cup when the players rush to kick the ball after the referee ends the game.. I want that 4 sec fun at the end seeing that nuke coming down
