### ISSUE TITLE
Units cannot be ordered to move under paradropping crates

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#9555]
or infantry. I cannot comment about units moving under paradropping infantry in the last release but I'm _almost_ sure you could move a unit under paradropping crates. Now a unit will be directed to a cell adjacent to the crate until it has landed.

This means you can no longer waypoint a unit to collect a crate and go back to its original destination until the crate has landed.

**Comment by Snurre86** [comment]
The cell the crate is parachuting towards are blocked.
![openra game_2016_12_01_20_03_22_440](https://cloud.githubusercontent.com/assets/7798635/20808130/bd55e416-b801-11e6-9dcb-9df6ec9c57d2.png)
