### ISSUE TITLE
Replace chronotank blue charging pips to pink charging bar

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#9558]
Currently the chronotank has a single 'chronoshift' / 'blink' ability. Although I would *love* to see it have a double blink ability, I think using pips to display a 'support power' charging is inconsistent with the other support powers which display a pink bar as they charge. This could confuse newer players where pips represent passengers (or ore harvested in ore trucks)

The hue of the blue is also hard to see against temperate terrain.

![ctank](https://cloud.githubusercontent.com/assets/3636652/10310227/d1308c18-6c38-11e5-8e1a-3bd9f8b45405.png)

**Comment by Mailaender** [comment]
I assume the pips were due to a RA95 limitation we don't share so it makes sense to change this.
