### ISSUE TITLE
host is searching for map

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#9569]
Just a * or something when the host is searching for maps

**Comment by penev92** [comment]
What's wrong with typing "Hold on, I'm selecting a map" in the chat?

**Comment by kyrreso** [comment]
when you are all alone, searching between 100 of maps. And a lot of ppl join and start chatting.. 
The search letter will crash the game for many, so you have to look for your map, and its usually not sorted by letters...
Some get kinda angry when you are not responding...

**Comment by penev92** [comment]
What crashes?
Maps are sorted by player count and then alphabetically. You can use the search field to search either by name or by player count by typing a number.

**Comment by kyrreso** [comment]
The Search Field are crashing the game for many players.
But finding the best map often takes time.

**Comment by penev92** [comment]
The search field only crashes if you have a bogus map (with a missing Author or Name field). And that has been fixed now.
The fix will be in the next playtest.
Until then you can remove this map - http://resource.openra.net/maps/5923  from your maps and it will stop crashing.

**Comment by kyrreso** [comment]
Ok. I removed the map, so it might be another one then. But I have heard a lot of ppl having this issue, so that fix are welcome. In the meantime we should report the maps, and disallow syn/download since that would help a lot of users.

**Comment by kyrreso** [comment]
Still hope this is a valid wish, just that * when host is searching for maps

**Comment by rob-v** [comment]
PR #13011

![obrazok](https://cloud.githubusercontent.com/assets/16348750/24218092/4b17a950-0f42-11e7-9ec3-e2993e27aa2d.png)
