### ISSUE TITLE
mapeditor wish: camera should be the startposition

### ISSUE THREAD

**Issue by kyrreso** [OpenRA/OpenRA#9572]
I am dropping spawn points, since I have no mcv's. 
That makes me think I could put Camera on startposition.

Should be possible to do that without LUA

**Comment by pchote** [comment]
> Should be possible to do that without LUA

Why?  Lua works well enough for this, so I don't see the need for duplication.

**Comment by obrakmann** [comment]
I don't see the need either. It takes two additional lines of yaml and three lines of lua to do this:

```yaml:
Rules:
	World:
		LuaScript:
			Scripts: map.lua
```

```lua
WorldLoaded = function()
	Camera.Position = CPos.New(54, 31)
end
```

**Comment by Phrohdoh** [comment]
```lua
WorldLoaded = function()
    Camera.Location = WPos.New(x, y, z)
end
```
