### ISSUE TITLE
crash on create new map

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#9574]
Added a file name and clicked save on the initial map details dialogue. Current release. Ubuntu 14.04

http://pastebin.com/8SJuVmPB

**Comment by penev92** [comment]
>`System.UnauthorizedAccessException`: Access to the path "/usr/lib/openra/mods/ra/maps/both_ways.oramap" is denied.

Change your save location to the support directory.

**Comment by abcdefg30** [comment]
See https://github.com/OpenRA/OpenRA/issues/9531#issuecomment-145329888 and thus #9507.
