### ISSUE TITLE
D2K - Yellow Placement Overlay when building on Concrete

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/OpenRA#9579]
Like in PS Edition of D2k.
![screenshot_2015-08-21-20-48-14](https://cloud.githubusercontent.com/assets/7933210/10396667/6af0d194-6eac-11e5-9d95-eb7ab85b058d.png)
##

**Comment by penev92** [comment]
I don't see the reason for this, as our building placement preview is actually better than this in my opinion.

**Comment by Mailaender** [comment]
We don't have yellow in Dune 2000, but grey (DATA.R8 frame 0) and white (DATA.R8 frame 2).

**Comment by MustaphaTR** [comment]
Gray one is coded to shown as red when building is unplaceable, right? This is not hard thing to make.
