### ISSUE TITLE
Tanya can't damage explosive barrels

### ISSUE THREAD

**Issue by steelphase** [OpenRA/OpenRA#9591]
as the title says Tanya can not damage explosive barrels. I have identified a potential solution, but not sure if this is the appropriate fix.

Looks like the Warhead@1Dam: SpreadDamage of Colt45 needs to be changed to

    ValidTargets: Ground, Infantry

instead of 

    ValidTargets: Infantry

**Comment by reaperrr** [comment]
That would allow Colt45 to target *all* ground targets. Since barrels are a special case (compared to other buildings or vehicles, which should be C4'd instead) it would likely be best to add `Barrel` to the barrel's target types, and then change Colt45 to `ValidTargets: Barrel, Infantry`.

**Comment by steelphase** [comment]
I updated the yaml, and that does resolve it.

@reaperrr any idea why the ValidTargets of Colt45, and it's Damage warhead differ?

**Comment by GraionDilach** [comment]
ValidTargets on the weapon means targeting allowance. ValidTargets on the DamageWarhead means warhead damage delivery. This is good for weapons which missed their target/has AOE damage, but also fixed targets - an AA missile might only be used against aircraft, but if said aircraft reached the airfield before the missile could catch up then the airfield should also be damaged via listing Ground only at DamageWarhead for example.
