### ISSUE TITLE
Rename "Show Bot Debug Messages" & expose debug messages to Lua

### ISSUE THREAD

**Issue by clemty** [OpenRA/OpenRA#9598]
it would be useful to have toggle-able debug messages in single-player missions which could remain in the code after merging - this could serve as a way to comment the mission code as well

This could be tied to the "Show Debug Messages"-Setting (maybe prefix the messges with "Lua: "?), but in that case the setting should be renamed to something like "Show Bot/Lua Debug Messages")

(currently I'm using Media.DisplayMessage for debugging and removing them before pushing)

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/9599/ implemented it although retaining "bot debug messages" as a separate button.
