### ISSUE TITLE
CustomSelectionSize might be broken

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#9609]
#9607 indicates it doesn't work as intended.

**Comment by Mailaender** [comment]
My best guess is that it doesn't define something like `Selectable.Priority` so it will be overlapped occasionally. If we allow `Selectable` to move from OpenRA.Game to OpenRA.Mods.Commons the fix will be easy.

**Comment by pchote** [comment]
I agree that this is probably selection priority related.

**Comment by pchote** [comment]
I take that back.  The bridge problems were introduced by 26ce7b5, not the selection sizes.
