### ISSUE TITLE
Use spatial partitioning to speed up frozen actors

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#9614]
One of our biggest perf hogs is FrozenActorLayer, which checks every frozen actor for visibility every tick.  We could save a lot of perf by tracking dirty flags for each bin in a spatial partition, and only ticking the frozen actors that are in dirty bins.

**Comment by Mailaender** [comment]
Is this also responsible for the performance problem just after game start? See https://youtu.be/5E650aiCGYo the trees popping up with a few seconds delay.

**Comment by pchote** [comment]
In part, most probably.  That specific problem should have been fixed by #9250, but that change will eventually need to be reverted (after fixing this) before we can introduce forest fires.
