### ISSUE TITLE
Toggling team chat should have its own hotkey

### ISSUE THREAD

**Issue by deniz1a** [OpenRA/OpenRA#9616]
Currently, tab is used for both player name completion and switching between team chat and all players chat. It would be better if team chat had its own hotkey.

**Comment by pchote** [comment]
We've already been over this several times (including changing it at least twice) in previous github issues/prs and IRC. We determined that tab is the only sensible choice for this key (see the previous discussions for the history behind this), and provide a button for people who prefer to use a mouse.

**Comment by deniz1a** [comment]
Ok then how about making it configurable in settings or yaml? Currently it's hardcoded here:
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Widgets/Logic/Ingame/IngameChatLogic.cs#L96
