### ISSUE TITLE
Map preview duplication

### ISSUE THREAD

**Issue by impulse9** [OpenRA/OpenRA#9617]
Map browser shows preview duplicates after each save within the editor if there were any changes made (does not apply if you just keep saving the map without making changes to it). This does not create extra files, it fills the menu with extra previews which all point to the same file.

![testmap_ra](https://cloud.githubusercontent.com/assets/2159248/10428625/20fa7f06-70f3-11e5-9d2e-067e216987e5.jpg)

**Comment by Mailaender** [comment]
[Changelog](https://github.com/OpenRA/OpenRA/wiki/Changelog-(bleed)/_compare/b1540f7409c20a25037971371c664df2a7cd33ec...e36551a304fbc8e6b5636903e080b90a77067721)
