### ISSUE TITLE
Licensing: specify GPL version in headers and README.md

### ISSUE THREAD

**Issue by akien-mga** [OpenRA/OpenRA#9626]
The licensing info in the README.md and in headers currently states: "It is made available to you under the terms of the GNU General Public License as published by the Free Software Foundation. For more information, see COPYING."

It does not specify which version of the GPL applies. When checking COPYING, one can see it is the GPL version 3, but there is no mention as to whether the "or any later version" clause applies. I would suggest to make it clearer at least in the README.md, and ideally also in the code header. If you go for GPLv3+ (3 or any later version), a typical license declaration would read:

```
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
```

**Comment by Mailaender** [comment]
It was changed to GPLv3+ by @chrisforbes & friends in 2010. https://github.com/OpenRA/OpenRA/commit/a72d19e754e049c75d8e73d7a9b502b09303d308
