### ISSUE TITLE
Encrypt teamchat (or otherwise don't send it to other team)

### ISSUE THREAD

**Issue by ChaoticMind** [OpenRA/OpenRA#9642]
Team chat should probably be encrypted with some simple symmetrical key scheme, or otherwise not sent to the all clients. Otherwise anyone can modify their client to see all opponent's teamchat, like [so](https://github.com/ChaoticMind/OpenRA/commit/1ad9784128108c70266b29f82d442d112a6218dc)

However, if I understand it correctly, all orders go through the dedicated server or game host, so if we choose to not send it all clients, the host would still be able to cheat. Besides, if we don't send them, they can't be shown in replays.

If we encrypt the chat instead, we will need to transfer the key between team members in some peer to peer fashion.

This has implications on whether replays would show all teamchat or not. If we want to show all teamchat in a replay, we'll need to transfer the keys to all opponents after the game has ended. This of course won't work if the game crashes or a player quits (although they could perhaps also be sent on surrender/abort).

**Comment by pchote** [comment]
If somebody wants to modify their client in order to cheat there are far better things (cheat / information wise) to hack than the enemy chat.  Adding an encryption layer for chat is total overkill.

**Comment by ChaoticMind** [comment]
Well... I agree.
