### ISSUE TITLE
Don't try to return fire if invisible and the attacker is out of reach

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#9669]
Firing with a V2 rocket launcher near a camo pillbox makes the pillbox try to return fire.
That means it uncloaks to shoot. But the V2 is outside it's weapon's radius, so it can't attack it.
Result is the camo pillbox sits there uncloaked until the target is destroyed or until ordered to Stop.

I suppose the same thing will apply to air attackers and perhaps to stealth defenses in TS.

If the actor cannot return fire, it shouldn't uncloak at all. (In this case I wasn't even targeting the pillbox, I was shooting at the ground 2 cells away from it.)
##

**Comment by matjaeck** [comment]
Can not reproduce this in playtest-20180729.

**Comment by pchote** [comment]
Likely fixed by #10750.
