### ISSUE TITLE
Tanya shoots at enemy structures

### ISSUE THREAD

**Issue by huwpascoe** [OpenRA/OpenRA#9673]
Tanya shoots at enemy structures instead of holding fire.

**Comment by reaperrr** [comment]
Sounds more like a stance issue, the Colt45 yaml looks fine to me.

**Comment by pchote** [comment]
Tanya shouldn't be able to shoot at structures in *any* stance.

**Comment by abcdefg30** [comment]
She stops doing that when removing `Ground` from `ValidTargets`.

**Comment by reaperrr** [comment]
> She stops doing that when removing Ground from ValidTargets.

Yes, but that should *not* be necessary (and would break shooting at barrels again). `Structure` is listed under `InvalidTargets`, which should override `ValidTargets`. 

Replacing Ground with Barrel would fix it for this particular case, but my point is that it seems something doesn't work as it should. With the given yaml rules, she should already only be able to shoot at unoccupied terrain and barrels, not all buildings.

**Comment by RoosterDragon** [comment]
I placed Tanya near a power plant, and the power plant doesn't list `Structure` as a target type by the time that check is reached in code - so it doesn't get excluded.

POWR defines
```
Targetable:
		TargetTypes: Ground, C4, DetonateAttack, SpyInfiltrate
```

BasicBuilding defines
```
Targetable:
		TargetTypes: Ground, C4, DetonateAttack, Structure
```

In code, the power plant has a single targetable trait, with the target types of those from the POWR  definition. Lots of other buildings seem to have a similar thing going on in their YAML.

Bisect suggests 277ac04f85d4af2162c67f0d47505f6e05b0735c introduced the issue.

**Comment by RoosterDragon** [comment]
Would the fix for this be to go to everything that inherits BasicBuilding and ensure any Targetable includes `Ground, C4, DetonateAttack, Structure`?

**Comment by reaperrr** [comment]
> Would the fix for this be to go to everything that inherits BasicBuilding and ensure any redefinition of Targetable includes Ground, C4, DetonateAttack, Structure?

Yes.
