### ISSUE TITLE
Add 'Flip/Mirror' functionality for sequences

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#9677]
Some older 2D games (Dune 2, MechCommander 1, AoE to give some examples) only had art for part of the facings 'clock', and then flipped/mirrored them to cover the rest.

This could also save modders some work if they make custom graphics that don't have a 'bias' towards left or right (muzzle flashes with facings, units in a 100% top-down perspective or with the 'light source' placed in the middle etc.).

Preferrably, this should be customisable per sub-sequence when combining aggregate sequences.

**Comment by penev92** [comment]
@evgeniysergeev is currently working on that for Dune 2. ;)

**Comment by penev92** [comment]
Actually mods based on Genie-based games will also need this (AoE, SW:GB, ...). Just for the record.

**Comment by evgeniysergeev** [comment]
for dune2 need 'vertical' and combination 'vertical'+'horizontal' flip too.

**Comment by evgeniysergeev** [comment]
support for drawing sprites flipped or mirrored is in #9723

**Comment by evgeniysergeev** [comment]
implemented in ##9724 (will works only after #9723 will be merged)

**Comment by evgeniysergeev** [comment]
#9770 allow to flip sprites in sequences + allow to use frames in combined sequences. Flipping will work only then #9723 will be merged.

**Comment by reaperrr** [comment]
Has been implemented by the PRs mentioned above.

**Comment by evgeniysergeev** [comment]
#11206 is related to this issue
