### ISSUE TITLE
Weird visual 'drop' when vehicles exit factory in TS

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#9678]
Only noticable in isometric perspective. They suddenly 'drop' by a few pixels when they move past a certain point after exiting the factory. Applies to voxel and sprite actors alike, so probably not just a visual issue.

**Comment by teees** [comment]
Looks like this: http://gfycat.com/PresentConsiderateGreendarnerdragonfly

**Comment by teees** [comment]
Probably related: actors exiting wf clipping through other actors

http://gfycat.com/InfiniteCreepyHagfish
