### ISSUE TITLE
Global chat: user bin tooltips should show IP and country.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#9685]
##

**Comment by GraionDilach** [comment]
Why IP? That worries me a bit tbh, we shouldn't release their IP to everyone.

**Comment by pchote** [comment]
To prevent trolls and nick-stealers.  We already expose the IP for all players in the lobby in the same way.

**Comment by GraionDilach** [comment]
This is a huge privacy concern still and I don't know any games which does this as well - they only used IPs for direct IP and never revealed others' on a lobby screen. I understand that this is kinda "simpler" than running a registration system on the IRC protocol, but this sounds quite abusive to me in the long run.

**Comment by Mailaender** [comment]
We could only show the vhost like `openra-66A92FDB.range213-122.btcentralplus.com` which is unique and gives away enough information to verify someone's approximate origin.

**Comment by pchote** [comment]
They can still be mapped back to IP, and are monster strings to display in the UI.

**Comment by KakolIsSomewhatGay** [comment]
@pchote Doing this would be a huge security concern, OpenRA already shows all connected IP's to clients  on the server chat/setup window which I strongly object to and can be abused very easily. You could have randomly generated IDs for example.

A Client requests to join the Server.
  The Server generates a random 12 number string for the Client.
    The Client joins and the Server sends the ply.rid with it.

I'm sure that this is possible in pretty much any language & will solve the IP identifier/nick stealer issue.

**Comment by pchote** [comment]
The global chat feature has been removed.
