### ISSUE TITLE
Veins: implement proper rendering

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#9688]
It uses LAT similar to d2k, but has additional variants for slope tiles.

**Comment by zzattack** [comment]
Here's something I found:
http://files.zzattack.org/img/upload/veins.png

Also, this might be relevant:
https://github.com/zzattack/ccmaps-net/blob/ca6745d892f315e2e8d80acb289c7d22d65cb62d/CNCMaps.Engine/Map/Operations.cs#L97

**Comment by Mailaender** [comment]
This would require another resource layer with a different rendering mode to co-exist. Not sure how to solve this.

**Comment by Mailaender** [comment]
Resolved by #19090.
