### ISSUE TITLE
.Attack() doesn't work in recent builds

### ISSUE THREAD

**Issue by Biofreak1987** [OpenRA/OpenRA#9693]
The computer isn't attacking objects like barrels with the .Attack() command in recent builds. You can check this in the intro for soviet02a, soviet03 or soviet07.

**Comment by obrakmann** [comment]
Introduced in #8768 according to git bisect.

**Comment by obrakmann** [comment]
So, it seems that the E1 can't find any suitable weapon against the barrel. I guess this will end up being just a yaml issue.

![screenshot from 2015-10-24 00 01 47](https://cloud.githubusercontent.com/assets/4331210/10706000/c3300aa0-79e2-11e5-9041-d94848619387.png)

**Comment by obrakmann** [comment]
@Biofreak1987: I filed a fix for this issue in #9736. Can you please check whether the maps now work correctly?

**Comment by Biofreak1987** [comment]
Maps seem to work correctly with this pr.
