### ISSUE TITLE
Actors with `Hovers` should not hover while changing altitude

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#9721]
Currently aircraft "hover" while landing/taking off.
We can fix that inside `Hovers` once `Aircraft` gets its long-needed overhaul.
Also the Hover MLRS shouldn't hover while going up/down slopes (unless that requires too much of a hack to be justifiable).

**Comment by GraionDilach** [comment]
The Hover MRLS did hovered during slopes in the orig game though iirc.

**Comment by atlimit8** [comment]
Perhaps setting `MinAirborneAltitude` > 1 after merging #9716 would suffice. I didn't change any behavior when I added that property, figuring that it would be tuned later.

**Comment by Mailaender** [comment]
Will https://github.com/OpenRA/OpenRA/pull/10162 fix the problem?

**Comment by teees** [comment]
#10163 will
