### ISSUE TITLE
Leaving a game should not boot player to the main menu

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#9726]
(current bleed) 
Leaving a (multiplayer) game boots you all the way to the main menu. This is not ideal since players will probably want to join another match (and this involves more clicking) or they should at least be encouraged to join another.

While this might be more important for multiplayer I don't see why it should be any different for skirmish games (which should actually preserve all the settings from the last match).
##

**Comment by pchote** [comment]
We already do this when leaving the lobby, so it makes a lot of sense to also do this from inside the game. :+1:

**Comment by MustaphaTR** [comment]
Closed by https://github.com/OpenRA/OpenRA/pull/15361
