### ISSUE TITLE
Boosted tesla will break the balance 

### ISSUE THREAD

**Issue by MicroJOo** [OpenRA/OpenRA#9727]
i dont even need a playtest to figure that one out 

they do get more range and damage when being boosted by shocktroopers , this is totally inacceptable beside the fact that it is a "RA2" feature ... i dont get the point why we should add every new feature to the "RA1"-mod ... as if our RA-Mod is the laboratory monkey here  for all the feature experiments

the Teslas are allready badass defense-structures , with the highest range and damage of "all" defense structures ... the ONLY thing you encourage by allies , is to spam even more artys ... 

why ? you ask ... cause allies have the weakest tanks ... medium-tanks and light-tanks are cannon fodder and teslas just have a "Grill-Fest" when allies tanks roll up ... thats why nobody is using them in a serious attack ... and thats why everyone spams artys instead 

now with the shocktroopers boosting teslas ... you dont need to be einstein to see that this is inappropriated

https://github.com/OpenRA/OpenRA/issues/2330
https://github.com/OpenRA/OpenRA/issues/4589
https://github.com/OpenRA/OpenRA/pull/8563

@Mailaender : please , we all know your "#this-is-not-true-to-the-original"-philosophy ... when theres controversy about a new feature .... but people play "Red Alert1" because it is called "Red Alert1" ... so lets "keep" it Red Alert1 atleast slightly

@pchote @obrakmann : 
we should consider to remove the "stat boost" and just have the Tesla "powered" when there is a PowerOutage ... with the help of shocktroopers ... i think that would be fair enough , cause Allies can cause a PowerOutage

@Unit158 @Phrohdoh : .... thx

**Comment by MicroJOo** [comment]
@pchote : you dont have to completely remove it ... 
we could realise one of my old ideas to compensate ... cause the "Mobile Gap Generator" is also a faction-special .. (france) ... just like the shocktroopers (russia) 

https://github.com/OpenRA/OpenRA/issues/6998
"Mobile Gap Generator
Add the ability to act as a "lightning protector" ... with the range of a Tesla Coil ... forcing Tesla-Lightning to aim at the Mobile Gap when its range is crossing the Tesla (coil , tank and shok)...
raised lightning-resistance so it can survive a couple of tesla hits ... "

![zap](https://cloud.githubusercontent.com/assets/9139965/10692871/95b6ad02-7994-11e5-9e51-f75a88075846.png)

**Comment by atlimit8** [comment]
* The stat boost should be removed.
* a "lightning protector" might be OK, but it won't balance things unless France and Russia were the only factions
* Even if those 2 are done, more balancing would be required.

**Comment by StexoO** [comment]
https://github.com/OpenRA/OpenRA/pull/8563 is titled "Tesla boost for RA2 mod" and this feature is only in RA2 so seeing this feature in RA1 means "this feature works, now let's cut the code from RA1 and paste it into RA2" ?
Why not an "Allow tesla boost" option in RA1 AND RA2 ? If it's unbalanced you could play against 10 players with this feature available only for you.
Generally and IMHO all the "controversial" choices could become options (checkboxes or something), so all the players would unconditionally love everything, no more [add->delete]s or [delete->add]s for the developers, and OpenRA would be "pre-modded". :yum:

**Comment by atlimit8** [comment]
Removal from the RA mod would be the easiest balancing solution.

**Comment by MicroJOo** [comment]
atlimit : yeah , probably ... dont take my idea seriously ... i was just pointing out a workaround without having it removed or tweaked down

**Comment by Phrohdoh** [comment]
>@Phrohdoh : .... thx
What? Why was I mentioned in this?

**Comment by Unit158** [comment]
I have the same question as Phrohdoh, and would like to be kept out of any further conversation if possible.

On 2015-10-23, at 9:15 PM, Taryn Hill <notifications@github.com<mailto:notifications@github.com>> wrote:


@Phrohdoh<https://github.com/Phrohdoh> : .... thx
What? Why was I mentioned in this?

**Comment by Mailaender** [comment]
Then balance it properly. I also don't see why this is my problem. https://github.com/OpenRA/OpenRA/issues/2330 is a brain child of @chrisforbes and @ScottNZ. It wasn't in the original isn't really a valid argument. Also boosting RA2 support all together now was rejected in https://github.com/OpenRA/OpenRA/pull/9396 so there is nothing I can do.

**Comment by Phrohdoh** [comment]
@Mailaender I don't see how that is relevant to @MicroJOo's points here.
