### ISSUE TITLE
Unit tests for MiniYaml parser

### ISSUE THREAD

**Issue by atlimit8** [OpenRA/OpenRA#9733]
Parsing bugs should be collected and analyzed to create unit (NUnit) tests.

Issues to be tested:
- [ ] #9196 -  yaml inheritance breaks in conjunction with yaml removals
  - #9710 - possible fix - no unit test

Please post (links to) MiniYaml bugs here.
##

**Comment by RoosterDragon** [comment]
See https://github.com/OpenRA/OpenRA/pull/9710#issuecomment-158542027.

**Comment by pchote** [comment]
We now have reasonably comprehensive (afaik) unit tests for the MiniYaml code, so closing as fixed.
