### ISSUE TITLE
Occasional [Attack]Move Activity lag spike of over 100ms on RA shellmap

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#9740]
It only happens rarely, approximately once in 5000-6000 ticks on average for me (no reason to revert any PRs over this) and given its seldom occurence, it might have been happening for a while already and not be a recent regression (or not even a regression at all and just more visible now that other performance issues have been fixed).

But either way, I think it's worth investigating, over 100ms on my system (i5-2500) probably means over 200ms on many other systems. It's quite noticeable because usually, all these Move-related activities take less than 10ms on my system, according to perf.log.
##

**Comment by RoosterDragon** [comment]
Which specific ticks have these lag spikes for you? If you run the shellmap again - do you get a lag spike on those exact same ticks?

**Comment by reaperrr** [comment]
No, I already checked that, it happens randomly. It's just that I got it once in a 4647 tick run (at tick 3615) and twice in a 16485 tick run (at ticks 10961 and 16180). The only reproducable thing is that it does occur eventually on nearly every shellmap run, but at completely random ticks and as rarely as mentioned.

**Comment by RoosterDragon** [comment]
Might be garbage collection, particularly if it's not just the Move activity, but just any random thing.

**Comment by reaperrr** [comment]
It's almost always the `AttackMoveActivity`, though on one occasion I saw a similar spike for `Attack`, too.

**Comment by RoosterDragon** [comment]
`AttackMoveActivity` absorbs a fair bit of CPU when calling `autoTarget.ScanAndAttack`.  #9734 should improve that a large amount though.

The rest of the CPU is spent on running the `inner` activity - which is movement. That basically means improving pathfinder performance even more. :)

**Comment by PunkPun** [comment]
Is this still relevant?

**Comment by penev92** [comment]
I'd say no. The issue isn't actionable and we've had a lot of perf improvements over the almost 7 (!) years since this was opened, as well a reworked pathfinder in the works.
