### ISSUE TITLE
Group selection excludes mcv

### ISSUE THREAD

**Issue by Biofreak1987** [OpenRA/OpenRA#9761]
Selecting a group of units that has a mcv, will always exclude the mcv. I dunno if it's supposed to behave like this but I've noticed it while working on the soviet06 missions.

**Comment by pchote** [comment]
This is intentional: see the Priority field on https://github.com/OpenRA/OpenRA/wiki/Traits#selectable

**Comment by Biofreak1987** [comment]
Ah, ok then.
