### ISSUE TITLE
Settings menu seperate back/apply buttons

### ISSUE THREAD

**Issue by RichSuther** [OpenRA/OpenRA#9774]
Would be nice if the Settings menus had a back (Cancel) and Apply button.

The Apply button should be disabled until the changes have been made, when clicked apply changes.

The back button should only then return the to the previous menu not applying changes, even if the UI has changed state.

The reset (to default) button could also be a bit clearer showing it only affects the currently selected tab.
##

**Comment by PunkPun** [comment]
The reset (to default) has been made cleaner, the entire hotkey UI was reworked

**Comment by dragunoff** [comment]
The described "apply/cancel" flow is not implemented and probably won't be. The settings in OpenRA are instantly applied and I recon that's not a bad way of doing things - it's a common pattern in games and in many other kinds of applications and even in some operating systems.
