### ISSUE TITLE
Make sandworms miss their food

### ISSUE THREAD

**Issue by MicroJOo** [OpenRA/OpenRA#9776]
now while i was working out the hijacker-buff ... i had contact with a trait called "WarnProbability" which is basicly the chance to avoid getting crushed by ... i guess evading the vehicle ? anyway ... 

how about we add a trait similar to this , to d2k's vehicles ... could call it "WormProbability" ... and this value could be derived from the speed of the unit ... the faster the unit is , the higher is the chance of the worm "missing" his food ... still shooting out of the sand but not getting the unit ... 

and this trait is only active when the unit is actually moving ... 

this way , we could give even slower units ... like Harvesters and Tanks a second chance , as long as they are "moving" (preferable to the next stable underground)

**Comment by UberWaffe** [comment]
Isn't this already indirectly done by virtue of fast units being able to get to safe ground faster?

**Comment by MicroJOo** [comment]
but there should be also a chance to save a harvester or a tank ...

**Comment by MicroJOo** [comment]
since the last couple of playtests i did ... i think this could be too much for the worm 

now that we have the thumpers (and they are pretty effective against worms) i think the worm doesnt need a nerf like this (not at this point) 

so will close this for now
