### ISSUE TITLE
Game Camera control like Tiberium Wars

### ISSUE THREAD

**Issue by PUOjACKz** [OpenRA/OpenRA#9781]
In Tiberium Wars, you can move the player camera, in the battlefield, pressing and keeping pressed the right mouse button. Then an arrow would appear and, accordingly to how much the player move the mouse, on the direction he/she likes, the camera would move in such direction, more and more quickly. I think this would been a bad idea, if implemented, especially how people are used to resort on this feature, in order to quickly take a look on the discovered battlefield areas.

**Comment by penev92** [comment]
This was implemented and will be in the next playtest under the name "Joystick scrolling".
