### ISSUE TITLE
Attempted to finalize an undisposed DisposableAction. heli (355) reserved fix (77)

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#9783]
http://pastebin.com/zPePbUm8

git-549f8a9 RA

**Comment by pchote** [comment]
Are you able to explain a bit of the context around this?  Was it in the middle of a game, or at the end (when you quit / leave). Was it multiplayer, or singleplayer?  Do you have a replay?

**Comment by r34ch** [comment]
@pchote RA multiplayer after 20 mins or so; me playing about with helicopters mainly.

Attached is the replay although it crashes much earlier than it did in game.
http://expirebox.com/download/212b6615aef1176ab171b984862773ec.html

And the error when playing the replay back;
http://pastebin.com/0XPg4VJR
