### ISSUE TITLE
Gems patches with a "greener" gem

### ISSUE THREAD

**Issue by StexoO** [OpenRA/OpenRA#9795]
If you watch this replay from RA95 https://www.youtube.com/watch?v=AFb-xgDDf7Q you can see one or two kind(s) of gem patches with a "greener" (diagonal) gem on it.
I don't see this patch in the OpenRA Map Editor and I don't remember seeing this in RA95 (I don't have the game right here to check), so is this patch missing from OpenRA or is this a modded RA95 ?
I also found this picture in the "MONEY MANAGEMENT" section of this page http://redalert1.com/skill.php :
![im1](https://cloud.githubusercontent.com/assets/8930382/10804199/8e46aa0a-7dc6-11e5-9397-31bd4d35f000.jpg)

**Comment by MicroJOo** [comment]
indeed , there is also a more cyan looking gem , a really shiny one .. just like the green one ... 

the reason that we dont have it , is because our gem-growing doesnt support some of the gem-sprites or a similar reason  ... @pchote knows why

**Comment by Mailaender** [comment]
Investigated this a bit and filed https://github.com/OpenRA/OpenRA/issues/10066. It was more difficult to debug this in the past, because we didn't have a map editor with proper resource rendering.
