### ISSUE TITLE
RA2: Unit prereq descriptions are inconsistent about refineries

### ISSUE THREAD

**Issue by scshunt** [OpenRA/OpenRA#9803]
The hover-description of some buildings is inconsistent about what a refinery is called. Some (Soviet Radar) say "Ore Refinery", some (War Factory) say "Refinery".

**Comment by atlimit8** [comment]
RA2 is not in this repository and is probably just a MiniYaml text inconsistency.
Find the origin repository of the RA2 mod you are using.
