### ISSUE TITLE
RA2: Kirovs crash

### ISSUE THREAD

**Issue by scshunt** [OpenRA/OpenRA#9804]
Was playing a game where I got the following crash:

    Red Alert 2 Mod at Version {DEV_VERSION}
    on map 8854f37b07d825819ac91b5fca488d4ca16764de (dustbowl by Westwood Studios).
    Operating System: Linux (Unix 4.2.0.1)
    Runtime Version: Mono 3.2.8 (Debian 3.2.8+dfsg-10) CLR 4.0.30319.17020
    Exception of type `System.InvalidOperationException`: Actor type 'zep' does not define a quantized body orientation.
      at OpenRA.Mods.Common.Traits.BodyOrientation+<BodyOrientation>c__AnonStorey0.<>m__0 () [0x00000] in <filename unknown>:0 
      at System.Lazy`1[System.Int32].InitValue () [0x00000] in <filename unknown>:0 

This appears to happen whenever a Kirov tries to deploy.

**Comment by Phrohdoh** [comment]
Please see https://github.com/Phrohdoh/OpenRA/issues/20 and note that upstream (OpenRA/OpenRA) does not house the RA2 mod.
