### ISSUE TITLE
Replace MiniYaml Ticks with Delay/Duration

### ISSUE THREAD

**Issue by atlimit8** [OpenRA/OpenRA#9810]
`Delay` has become the standard way of denoting an interval in ticks. There are 10 fields that use `Ticks`, 42 that use `Delay`, and 2 more that use `DelayInTicks`:

```
OpenRA.Game/Traits/DrawLineToTarget.cs:19:              public readonly int Ticks = 60;
OpenRA.Mods.Common/Traits/AmmoPool.cs:45:               public readonly int ReloadTicks = 25 * 2;
OpenRA.Mods.Common/Traits/AmmoPool.cs:51:               public readonly int SelfReloadTicks = 25 * 2;
OpenRA.Mods.Common/Traits/Harvester.cs:35:              public readonly int LoadTicksPerBale = 4;
OpenRA.Mods.Common/Traits/Harvester.cs:38:              public readonly int UnloadTicksPerBale = 4;
OpenRA.Mods.Common/Traits/Player/StrategicVictoryConditions.cs:25:              public readonly int TicksToHold = 25 * 60 * 5;
OpenRA.Mods.Common/Traits/Render/WithInfantryBody.cs:21:                public readonly int MinIdleWaitTicks = 30;
OpenRA.Mods.Common/Traits/Render/WithInfantryBody.cs:22:                public readonly int MaxIdleWaitTicks = 110;
OpenRA.Mods.Common/Traits/SelfHealing.cs:21:            public readonly int Ticks = 5;
OpenRA.Mods.Common/Traits/Wanders.cs:22:                public readonly int TicksToWaitBeforeReducingMoveRadius = 5;
```

```
OpenRA.Game/GameRules/WeaponInfo.cs:43:         public readonly int ReloadDelay = 1;
OpenRA.Game/GameRules/WeaponInfo.cs:57:         public readonly int BurstDelay = 5;
OpenRA.Mods.Cnc/Traits/SupportPowers/IonCannonPower.cs:27:              public readonly int CameraRemoveDelay = 25;
OpenRA.Mods.Cnc/Traits/SupportPowers/IonCannonPower.cs:39:              public readonly int WeaponDelay = 7;
OpenRA.Mods.Common/AI/HackyAI.cs:51:            public readonly int MinimumAttackForceDelay = 0;
OpenRA.Mods.Common/AI/HackyAI.cs:61:            public readonly int StructureProductionInactiveDelay = 125;
OpenRA.Mods.Common/AI/HackyAI.cs:65:            public readonly int StructureProductionActiveDelay = 0;
OpenRA.Mods.Common/AI/HackyAI.cs:68:            public readonly int StructureProductionRandomBonusDelay = 10;
OpenRA.Mods.Common/AI/HackyAI.cs:71:            public readonly int StructureProductionResumeDelay = 1500;
OpenRA.Mods.Common/AI/HackyAI.cs:81:            public readonly int CheckForNewBasesDelay = 1500;
OpenRA.Mods.Common/Effects/Bullet.cs:60:                public readonly int TrailDelay = 1;
OpenRA.Mods.Common/Effects/Bullet.cs:68:                public readonly int ContrailDelay = 1;
OpenRA.Mods.Common/Effects/Missile.cs:86:               public readonly int HomingActivationDelay = 0;
OpenRA.Mods.Common/Effects/Missile.cs:112:              public readonly int ContrailDelay = 1;
OpenRA.Mods.Common/Traits/Air/AttackPlane.cs:20:                public readonly int AttackTurnDelay = 50;
OpenRA.Mods.Common/Traits/Armament.cs:42:               public readonly int FireDelay = 0;
OpenRA.Mods.Common/Traits/Attack/AttackCharge.cs:27:            public readonly int InitialChargeDelay = 22;
OpenRA.Mods.Common/Traits/Attack/AttackCharge.cs:30:            public readonly int ChargeDelay = 3;
OpenRA.Mods.Common/Traits/Buildings/BaseProvider.cs:24:         public readonly int InitialDelay = 0;
OpenRA.Mods.Common/Traits/Buildings/Bridge.cs:27:               public readonly int RepairPropagationDelay = 20;
OpenRA.Mods.Common/Traits/Buildings/Exit.cs:31:         public readonly int ExitDelay = 0;
OpenRA.Mods.Common/Traits/C4Demolition.cs:30:           public readonly int FlashesDelay = 4;
OpenRA.Mods.Common/Traits/Cloak.cs:24:          public readonly int InitialDelay = 10;
OpenRA.Mods.Common/Traits/Cloak.cs:27:          public readonly int CloakDelay = 30;
OpenRA.Mods.Common/Traits/Crates/CrateAction.cs:32:             public readonly int TimeDelay = 0;
OpenRA.Mods.Common/Traits/Harvester.cs:27:              public readonly int SearchForDeliveryBuildingDelay = 125;
OpenRA.Mods.Common/Traits/Player/ConquestVictoryConditions.cs:19:               public readonly int NotificationDelay = 1500;
OpenRA.Mods.Common/Traits/Player/MissionObjectives.cs:49:               public readonly int GameOverDelay = 1500;
OpenRA.Mods.Common/Traits/Player/PlaceBuilding.cs:26:           public readonly int NewOptionsNotificationDelay = 10;
OpenRA.Mods.Common/Traits/Player/StrategicVictoryConditions.cs:34:              public readonly int NotificationDelay = 1500;
OpenRA.Mods.Common/Traits/Render/WithBuildingExplosion.cs:28:           public readonly int Delay = 0;
OpenRA.Mods.Common/Traits/SupportPowers/AirstrikePower.cs:37:           public readonly int CameraRemoveDelay = 25;
OpenRA.Mods.Common/Traits/SupportPowers/NukePower.cs:28:                public readonly int FlightDelay = 400;
OpenRA.Mods.Common/Traits/SupportPowers/NukePower.cs:47:                public readonly int CameraRemoveDelay = 25;
OpenRA.Mods.Common/Traits/Turreted.cs:24:               public readonly int RealignDelay = 40;
OpenRA.Mods.Common/Traits/World/CrateSpawner.cs:32:             public readonly int InitialSpawnDelay = 0;
OpenRA.Mods.Common/Warheads/Warhead.cs:33:              public readonly int Delay = 0;
OpenRA.Mods.RA/Traits/MadTank.cs:37:            public readonly int ChargeDelay = 96;
OpenRA.Mods.RA/Traits/MadTank.cs:41:            public readonly int DetonationDelay = 42;
OpenRA.Mods.RA/Traits/PortableChrono.cs:24:             public readonly int ChargeDelay = 500;
OpenRA.Mods.RA/Traits/SupportPowers/GpsPower.cs:87:             public readonly int RevealDelay = 0;
OpenRA.Mods.RA/Traits/SupportPowers/ParatroopersPower.cs:47:            public readonly int CameraRemoveDelay = 85;
```

```
OpenRA.Mods.Common/Traits/Wanders.cs:25:                public readonly int MinMoveDelayInTicks = 0;
OpenRA.Mods.Common/Traits/Wanders.cs:28:                public readonly int MaxMoveDelayInTicks = 0;
```

---

I propose:

```
DrawLineToTarget: Ticks => Duration
AmmoPool:  ReloadTicks => ReloadDelay
AmmoPool:  SelfReloadTicks => SelfReloadDelay
Harvester: LoadTicksPerBale => BaleLoadDelay (@pchote)
Harvester: UnloadTicksPerBale => BaleUnloadDelay (@pchote)
StrategicVictoryConditions: TicksToHold => HoldDuration
WithInfantryBody: MinIdleWaitTicks => MinIdleDelay
WithInfantryBody: MaxIdleWaitTicks => MaxIdleDelay
SelfHealing: Ticks => Delay
Wanders: TicksToWaitBeforeReducingMoveRadius => ReduceMoveRadiusDelay
Wanders: MinMoveDelayInTicks => MinMoveDelay
Wanders: MaxMoveDelayInTicks => MaxMoveDelay
AttackCharge: ReloadTime => ReloadDelay (noted by @reaperrr)
```
##

**Comment by pchote** [comment]
Sounds good to me.  I suggest
```
Harvester: LoadTicksPerBale => BaleLoadDelay
Harvester: UnloadTicksPerBale => BaleUnloadDelay
```

**Comment by reaperrr** [comment]
There's also `ReloadTime` in `AttackCharge`.

**Comment by reaperrr** [comment]
As far as I can tell, this has been solved.

**Comment by GraionDilach** [comment]
There's still Interval on AnnounceOnKill though.

**Comment by reaperrr** [comment]
> There's still Interval on AnnounceOnKill though.

There are a few Intervals on HackyAI as well, so I'm reopening for now.

**Comment by lawando** [comment]
Below is a list of current occurrences of "interval". My proposed changes are written after "->". I'm not really happy with having 3 different names for "Trail-Delays" and would prefer to unify them if possible. In some cases "interval" sounds better than delay (like in ScanInterval) but if the goal is to get rid of "interval" in names then those should be changed too.

```
HackyAI
  AssignRolesInterval -> AssignRolesDelay
  RushInterval -> RushDelay
  AttackForceInterval -> AttackForceDelay
AutoTarget / SupportPowerDecision
  MinimumScanTimeInterval -> MinimumScanTimeDelay (?)
  MaximumScanTimeInterval -> MaximumScanTimeDelay (?)
RepairableBuilding
  RepairInterval ->RepairDelay
RepairsUnits
  Interval -> RepairDelay 
Burns
  Interval -> DamageDuration
CashTrickler
  Interval -> TrickleDelay (?)
DamagedByTerrain   
  DamageInterval -> DamageDelay
Demolition
  FlashesDelay -> InitialFlashDelay
  FlashInterval -> FlashDelay
  FlashDuration
BaseAttackNotifier
  NotifyInterval -> NotificationDelay
EnemyWatcher
  ScanInterval -> ScanDelay (?)
  NotificationInterval -> NotificationDelay
HarvesterAttackNotifier
  NotifyInterval -> NotificationDelay
ResourceStorageWarning
  AdviceInterval -> NotificationDelay
PowerManager
  AdviceInterval -> NotificationDelay
SeedsResource
  Interval -> SeedingDelay (?)
SmokeTrailWhenDamaged
  Interval -> SmokeTrailDelay
"Powers"
  ChargeInterval -> ChargeDelay
CrateSpawner
  SpawnInterval -> SpawnDelay
LeavesTrails
  MovingInterval -> MovingDelay
  StationaryInterval -> StationaryDelay
WithIdleAnimation
  Interval -> AnimationDelay
AmbientSound
  Interval -> SoundDelay
AnnounceOnKill
  Interval -> NotificationDelay 
Sandworm
  TargetRescanInterval -> TargetRescanDelay
WormManager / ActorSpawnManager
  SpawnInterval -> SpawnDelay
MadTank
  ThumpInterval -> ThumbDelay
Projectile
  DamageInterval -> DamageDelay
  TrailInterval -> TrailAnimationDelay
```

**Comment by pchote** [comment]
Note that interval vs delay are describing logically different things: intervals repeat periodically, while delays are one-offs triggered by some other event.

**Comment by reaperrr** [comment]
To be honest, by now I think we should consider only renaming things in the future if
- we're refactoring the trait holding that property anyway, or
- the name is blatantly out of line with nearly the entire rest of the code (like *Time property names were with the delay/interval/duration entries, or EmitInfantryOnSell was with its generalistic nature)

I think @ABrandau (and at least 1 or 2 other modders) have raised the (imo valid, though the old update rule system takes a good amount of blame for that) point that minor renames over semantics/spelling just make things a bit more inconvenient for modders when updating.

I light of that and @pchote's comment, it might be better to just leave the Intervals untouched and close this as "partially solved and the rest is fine/WONTFIX".

**Comment by pchote** [comment]
I was under the impression that we were broadly happy with the current system, and had mostly completed renaming things to fit:
* *Interval for periodic timers.
* *Delay for delays between something and something else.
* *Duration for the amount of time that something should happen for once started.

There are various cases where a single thing might want to more than one of these, e.g. a blinking light might have a BlinkDelay from when it was first on, and repeat every BlinkInterval after that, for BlinkDuration ticks each cycle.

**Comment by lawando** [comment]
Indeed, I messed that up. The keys in the list are accurately described as intervals as far as I can tell from looking at the code. The following keys could be renamed to use delay/duration:

```
Aircraft
  NumberOfTicksToVerifyAvailableAirport
```
Apart form this I couldn't find any other notation in ticks that should be renamed.

One could rename those that are only called "interval" to something more specific like "RepairInterval" or "DamageInterval", however that's not the point of this issue. I made some proposals nevertheless:
```
RepairsUnits
  Interval -> RepairInterval (unify with RepairableBuilding)
Burns
  Interval -> DamageInterval (unify with  DamagedByTerrain)
CashTrickler
  Interval -> CashInterval (specify)
EnemyWatcher
  NotificationInterval -> NotifyInterval (unify wit other occurrences)
SeedsResource
  Interval -> SeedingInterval (specify)
WithIdleAnimation
  Interval -> AnimationInterval (specify)
AmbientSound
  Interval -> SoundInterval (specify)
AnnounceOnKill
  Interval -> NotifyInterval (unify wit other occurrences)
```
I'm not really sure if the following do just update positions: 
```
SmokeTrailWhenDamaged
  Interval -> TrailUpdateInterval
LeavesTrails
  MovingInterval -> MovingTrailUpdateInterval
  StationaryInterval -> StationaryTrailUpdateInterval
Projectile
  TrailInterval -> TrailUpdateInterval
```

**Comment by ABrandau** [comment]
Yes, renames are always an inconvenience for modders, mostly for three reasons.

First, that you have to rename all traits and properties on each mod to get it working again. (This has already been fixed with the latest upgrade rule change)

Second, Even tho the mod is going to update itself, the modder memory will not, the yaml user will not be able to remember all the changes of the properties and will use the old names, this will lead to frustration because **the game does not tell you that you are inputting a wrong property** , meaning they will do blank changes, that they wont be able to spot after doing atleast 3 or 4 tests. (AFAIK @Phrohdoh is partially fixing this issue with a plugin)

Third, Modders cannot trust the upgrade rule completely, as its not something that can handle exceptions, for example, on Shattered Paradise I have aircraft that dont need to rearm, after the ammunition fix, the Property ``PauseOnCondition: !ammo`` was applied to all my aircraft, which didnt do anything at first glance because SP comes from a time where you needed to give infinite ammo to aircraft to get this effect anyway, but weeks later, after doing some changes to the units, I started to wonder, why my unit only fires 5 shots when the burst says 10? Then I noticed.

The end result here is that, after each engine upgrade, we **have to** delay the patches atleast for a week to check if everything works as normal. Now, @pchote asked us to delay the release of Shattered Paradise until some performance fixes are merged upstream, so OpenRA gets a **good image as a first impression**, this is completely understandable, but you guys should understand we have the same problem when property names are changed, after a patch, a **bug is likely to slip through**, and that means new users can get the idea that the game is buggy, this is my fault for not checking, **yes it is**, but the real cause are **these renames**. 

My suggestion here is to have something that checks for invalid properties, and if possible, make the mod crash when a trait has a wrong property (of course, this will need an exception that mentions where is the error) , on the other hand, fixing the traits page would be also very helpful, as it allows you to see the traits. I remember there was an utility command to print all the current traits, I will have to test it to elaborate further.

**Comment by reaperrr** [comment]
As far as I can tell, this is pretty much solved as far as the original issue goes.
If someone feels anything from the discussion here still needs to be adressed in some way, in my opinion they should open a new ticket and link this one there.
