### ISSUE TITLE
Captured production building does not show production progress bar

### ISSUE THREAD

**Issue by Basti504** [OpenRA/OpenRA#9811]
Noticed during a multiplayer game, could easily reproduce in a test game with AI. Release 20150919 

![Image](http://i.imgur.com/9HlaztI.png)

Top war factory one was build by myself
Bottom war factory was captured with engineer

Captured barracks showed the same behaviour.

**Comment by pchote** [comment]
Should be an easy fix.  Adding to the release milestone, but the fix may not make the first playtest.
