### ISSUE TITLE
Allied War Factory is drawn above some units in front of it

### ISSUE THREAD

**Issue by scshunt** [OpenRA/OpenRA#9814]
Build an allied WF and place a unit along the long side of it (the side facing the user). The unit is drawn under, not on top of, the building.

**Comment by atlimit8** [comment]
If this is for RA2, this is in the wrong repository.

**Comment by Mailaender** [comment]
Yep, this is a Z-sorting configuration issue by @Phrohdoh & friends. Post those problems at https://github.com/Phrohdoh/OpenRA instead.
