### ISSUE TITLE
Restore OrderDelay = 1 for missions/skirmish

### ISSUE THREAD

**Issue by reaperrr** [OpenRA/OpenRA#9817]
Before the refactorings related to gamespeed, singleplayer games were always set to an order delay of 1. This is no longer the case, and particularly on 'fastest', the delay is very noticable when navigating the UI.

It would be nice if we could restore the old "force order delay to 1 when it's a singleplayer game, regardless of game speed" behavior.

**Comment by pchote** [comment]
Oops.
