### ISSUE TITLE
Now that RA2 is free, should we put Volkov back in?

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#9819]
I only recall him being removed due to using RA2 assets?

**Comment by MicroJOo** [comment]
im pretty sure we are still "not allowed" to ship files from RA2 ... 

just because its free to download (right now) ... doesnt mean you can take the files and do whatever you want with it

**Comment by Phrohdoh** [comment]
There is a difference between (temporarily) free downloadable games and games that have become freeware/abandonware, RA2 does not fall in that second category.

**Comment by reaperrr** [comment]
Volkov could make a return as long as no RA2 assets are used, but yeah, RA2 is still not (and possibly never will be) freeware, that situation hasn't changed.

**Comment by GraionDilach** [comment]
The old Volkov also used the A Path Beyond cameo, FYI. The voice issue can be solved if we modify the infantry voice/record a new one for it, but a cameo will also be needed.

**Comment by r34ch** [comment]
In RA1 the same gnrl shp was used for volkov in multiple missions as well as the same voice.

Apart from the cameo, why would RA2 assets be used over existing assets?

**Comment by GrayHatter** [comment]
I admittedly only skimmed the EULA, but the problem is shipping the assets because they're not yet abandonware. But if EA is willing to ship the assets for us (as they are). We wouldn't be infringing anything by providing information on how to repurpose them.

The issue with RA2 unless I'm missing something, is that until it becomes abandonware; you already have to own a copy of the assets. Which EA is now providing. So... why can't we?

**Comment by Phrohdoh** [comment]
Why *should* Volkov be included in the game?
What benefit does the game (and its balance) gain?

**Comment by MustaphaTR** [comment]
I've always thought that if one side has a hero unit all should have.

I remember previously someone said that Shock Troopers are counterpart of Tanya, now Shock Troopers are Russian Subfaction Specific. So i think we should add it back. (I fact i never seen him in OpenRA, it was already removed when i started to play.)

**Comment by MicroJOo** [comment]
whats the reason to add volkov ? soviets are fine as they are ... "stacked" with all sort of anti-tank weapons  ... i see no reason for volkov being in other then "being cool" ... but that just no option , cause we have to balance the whole shit again and again and again

last time everyone want snipers , now everyone wants volkov ...

**Comment by Mailaender** [comment]
DON'T rip the Red Alert 2 voices again. We already have a voiceset setup for Stavros/General/Volkov: https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/audio/voices.yaml#L135
