### ISSUE TITLE
Stealth Detection is broken/not functional

### ISSUE THREAD

**Issue by DoGyAUT** [OpenRA/OpenRA#9820]
DetectCloaked seems not to be working at all.

It also looks like RenderDetectionCircle doesn't work too.

**Comment by reaperrr** [comment]
What version and mod did you test?

Because on latest bleed, both still work in the cnc mod.

**Comment by penev92** [comment]
There is no detection circle in TS on latest bleed fwiw.

**Comment by DoGyAUT** [comment]
Check TS mod, Sensor doesn't have a detection circle.

My Dogs can't detect my scouts (custom mod) - it worked in older builds (early oct)

**Comment by reaperrr** [comment]
You're in all likelyness affected by the same issue as the TS sensor:

`DetectCloaked`'s `Range` was recently converted from cells to world units (where `1024` or `1c0` equals 1 cell), adding `c0` to your detection range will likely fix both (as it does on TS' sensor array).

**Comment by DoGyAUT** [comment]
Yes seems that was the problem!
