### ISSUE TITLE
Current playtest -20151031 Crushing spawns visceroids.

### ISSUE THREAD

**Issue by AoAGeneral** [OpenRA/OpenRA#9831]
This was present in the bleed but I thought it was because I was crushing on the tiberium. (Even though that doesnt happen in the original.)

I just played the playtest with some others and its been spawning them randomly by crushing. Im not sure if its only with minigunners or all infantry type. Tested with just light tanks so far.

**Comment by obrakmann** [comment]
Confirmed. The reason this happens is that [crushing doesn't use a warhead](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.Common/Traits/Crushable.cs#L64), so [this check](https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Mods.RA/Traits/SpawnActorOnDeath.cs#L76) does not work as expected and the viceroid is spawned anyway.
