### ISSUE TITLE
Global chat: Consider renaming "Leave Chat" button

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#9832]
Some feedback from the ingame chat: someone was worried that the "Leave Chat" button might kick them from the local server chat as well as the global chat.

**Comment by pchote** [comment]
Would "Sign out" be sufficiently clear to distinguish global vs server chat and disconnecting chat vs leaving server?

**Comment by penev92** [comment]
I don't know, "Leave Chat" is clear enough for me.

**Comment by pchote** [comment]
I'm inclined to agree.
