### ISSUE TITLE
Lobby-interface text overlapping

### ISSUE THREAD

**Issue by MicroJOo** [OpenRA/OpenRA#9840]
![graphical issues](https://cloud.githubusercontent.com/assets/9139965/10866348/d1e6f5a6-802a-11e5-9dae-cf7cf9d105c3.png)

**Comment by pchote** [comment]
We can fix this by testing the text width against the label width. If it overlaps, try removing a character and appending a `...`.  Repeat until the text width is less than the label width.

**Comment by pchote** [comment]
The same fix should also be applied to player names in the lobby & ingame score screen, server names in the MP browser, and map names in the map chooser.

**Comment by abcdefg30** [comment]
I think difficulties, too.
At the moment, the `real tough guy` difficulty has the same issue.
