### ISSUE TITLE
TerrainSpriteLayer memory sink

### ISSUE THREAD

**Issue by huwpascoe** [OpenRA/OpenRA#9841]
Whilst profiling https://github.com/OpenRA/OpenRA/pull/9627, I came across this hard-to-miss memory sink. It happens each time you start another map. Here's the difference from baseline to after jumping between skirmish and title screen for a while:

OpenRA.Graphics.TerrainSpriteLayer
+114 instances
+209,198,208 bytes

Almost all of that memory is composed of OpenRA.Graphics.Vertex[] inside the TerrainSpriteLayer.

**Comment by penev92** [comment]
Oh, that sounds like the reason behind my OutOfMemory exceptions (and https://github.com/Phrohdoh/OpenRA/issues/59).

**Comment by RoosterDragon** [comment]
@penev92: You would need to have started dozens of games for this to eat up enough memory to be a likely candidate for your OOM problems. If your can provoke an OOM without starting many games than I expect the root cause of your problem is different.
