### ISSUE TITLE
Battlefield News does never update

### ISSUE THREAD

**Issue by Mailaender** [OpenRA/OpenRA#9843]
It never did. I can only refresh by deleting the news yaml. Might be a localized (running de_DE Linux) Mono problem with dates.

![image](https://cloud.githubusercontent.com/assets/756669/10867826/93f07400-8077-11e5-945a-2662e6a43f15.png)

**Comment by penev92** [comment]
Interesting.
It seems like mine is at
>2015-07-16 12-00-00:
	Title: Another tournament is coming!
	Author: Christopher Grant

which is fairly old as well. So it's probably not your system's fault as I'm on an en_EN Windows.

**Comment by pchote** [comment]
```
10:52 <+pchote> penev: check your settings.yaml - what does NewsFetchedDate say?
10:52 <+penev> NewsFetchedDate: 2016-01-26 19-00-00
10:52 <+penev> wow WAT
10:52 < GraionDilach> lol
10:52 <+pchote> yeah, that'll be why it isn't updating
```
The simple fix here is to remove the rate limiting and `NewsFetchedDate` field.  Querying once per main menu opening still isn't all that much.

**Comment by penev92** [comment]
Or remove it and get the date from `news.yaml` instead. At least that one is reliable.

**Comment by pchote** [comment]
The date in news.yaml is the date that the post was written (which remains fixed), so is not useful for this.

**Comment by Mailaender** [comment]
Mine is:

```yaml
Game:
	NewsFetchedDate: 2015-11-10 19-00-00
```

so I thought this could be YYYY-MM-DD vs YYYY-DD-MM or something, but either way it should already have updated itself.

**Comment by GraionDilach** [comment]
That's YYYY-MM-DD and in that case it would update itself after Nov 10th - which is still far away.

I had it working all the time btw.

**Comment by pchote** [comment]
Month vs day ordering doesn't explain @penev92's 2016 date.

**Comment by RoosterDragon** [comment]
You could also try ignoring dates from the future.
