### ISSUE TITLE
Unit `jumpjet` does not have a sequence named `die3`

### ISSUE THREAD

**Issue by waclaw66** [OpenRA/OpenRA#9844]
Red Alert 2 Mod at Version {DEV_VERSION}
on map 8854f37b07d825819ac91b5fca488d4ca16764de (dustbowl by Westwood Studios).
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Unit `jumpjet` does not have a sequence named `die3`
   v OpenRA.Graphics.SequenceProvider.GetSequence(String unitName, String sequenceName) v d:\OpenRA-RA2\OpenRA.Game\Graphics\SequenceProvider.cs:řádek 65
   v OpenRA.Graphics.Animation.PlayThen(String sequenceName, Action after) v d:\OpenRA-RA2\OpenRA.Game\Graphics\Animation.cs:řádek 111
   v OpenRA.Mods.Common.Effects.Corpse..ctor(World world, WPos pos, String image, String sequence, String paletteName)
   v OpenRA.Mods.Common.Traits.WithDeathAnimation.<>c__DisplayClass1.<SpawnDeathAnimation>b__0(World w)
   v OpenRA.World.Tick() v d:\OpenRA-RA2\OpenRA.Game\World.cs:řádek 293
   v OpenRA.Game.InnerLogicTick(OrderManager orderManager) v d:\OpenRA-RA2\OpenRA.Game\Game.cs:řádek 496
   v OpenRA.Game.LogicTick() v d:\OpenRA-RA2\OpenRA.Game\Game.cs:řádek 520
   v OpenRA.Game.Loop() v d:\OpenRA-RA2\OpenRA.Game\Game.cs:řádek 644
   v OpenRA.Game.Run() v d:\OpenRA-RA2\OpenRA.Game\Game.cs:řádek 684
   v OpenRA.Program.Run(String[] args) v d:\OpenRA-RA2\OpenRA.Game\Support\Program.cs:řádek 117
   v OpenRA.Program.Main(String[] args) v d:\OpenRA-RA2\OpenRA.Game\Support\Program.cs:řádek 39

**Comment by pchote** [comment]
We aren't tracking the external red alert 2 bugs in this issue tracker, sorry.

**Comment by penev92** [comment]
For RA2 issues refer to [the RA2 repository](https://github.com/Phrohdoh/OpenRA/issues).

**Comment by waclaw66** [comment]
Thanks, I'll report there.
