### ISSUE TITLE
Attack-move works unreliably in new playtest

### ISSUE THREAD

**Issue by Aaron-Lloyd** [OpenRA/OpenRA#9851]
I was playing the playtest online and was quite frustrated that the attack-move function seemed to only work about 60% of the time. Another player in the game I played complained of the same thing.

**Comment by penev92** [comment]
What happens in the other 40% of the time?

**Comment by Aaron-Lloyd** [comment]
It gives a regular move order.

**Comment by obrakmann** [comment]
Sorry to be a pain, but does "regular move order" mean that the target line is actually green, or that the target line is red, but the unit is just not attacking while moving?

If it is the latter, please post a replay where that occurs.

**Comment by Aaron-Lloyd** [comment]
Line was green, had to regive orders.

**Comment by MicroJOo** [comment]
i was unable to reproduce a 40% chance of failing to be a regular move instead of a attack-move ... 

it happend , but maybe once in 20-30 attack-move clicks

**Comment by Aaron-Lloyd** [comment]
This was on Red Alert for me too. I tried reproducing the results with a couple skirmishes, agreed that the number of issues were a lot lower than the initial multiplayer game issues I was having.

Also worth noting that I believe the game that was giving issues was being played at the "faster" game speed, maybe it has to do with that?

**Comment by Phrohdoh** [comment]
Could you provide us with replays please?

**Comment by Aaron-Lloyd** [comment]
GameReplays.org doesn't seem to work with the playtest. Let me know if this link works.

http://wikisend.com/download/349242/OpenRA-2015-11-01T040004Z.orarep

The game was played on Asymmetric Battle. Newwe mentions attack-move issues towards the end of the game (After I surrender) in the chat, I agree with him.

**Comment by pi99y** [comment]
Happens in single and multiplayer games - if that helps.

**Comment by penev92** [comment]
The only time I was able to reproduce this was when I was spamming orders like crazy and I couldn't press A as quickly as I right-clicked.
Unfortunately replays don't give us much because they only contain the order the unit reacted to - there is no way to know what was pressed by the player.

**Comment by pi99y** [comment]
This is interesting, it was really easy for me to reproduce the time I posted the above replays (I intentionaly played them just to demonstrate it), however I just tried again and could not do it in the first few minutes. I don't think it's fictional since others reported it too...

I'm on Windows 8.1 btw (and latest playtest).

**Comment by pi99y** [comment]
Since this mostly happened to me during the start of the game when everything is black due to the shroud, and I can't reproduce it on "explored map", I'm now thinking it's because I clicked on unreachable terrain that was obscured by shroud. 
 
Perhaps a cursor should "detect" trough shroud if the terrain underneath is unreachable and change to some kind of no "no-go" icon to indicate the order won't be executed? (at least until behaviour is changed so that units move towards goal as close as they can until they can't get closer)

**Comment by pchote** [comment]
@pi99y: What you are reporting is different to the original topic of this issue, which is that units seem to be treating attack-move orders as regular move orders.

**Comment by pi99y** [comment]
True, my bad.

**Comment by RoosterDragon** [comment]
Hi @Aaron-Lloyd, a few of us have tried reproducing this issue (we've been discussing this in IRC) but we've been unable to do so. Are there any further pointers you can give us to aid in trying to work out what it is? We're a bit stuck on this one.

Does this only happen for online games at faster game speed? What about offline games and/or normal game speeds?

**Comment by Aaron-Lloyd** [comment]
I'm honestly not sure, all I can say is that it was definitely an issue in that one game. I also remember it being mentioned on one of either FiveAces or SoScared's streams when they were testing the playtest, so I think there's something to it. As stated above there doesn't seem to be as much an issue in single player.

I just reinstalled the playtest, in skirmish I was able again to very rarely replicate the issue (much less so than that one game).

**Comment by pchote** [comment]
I suspect that this may just be the normal MP order latency (which also affected singleplayer in the first playtest - #9817).  If you double click with the attackmove order active (because the first doesn't go through immediately) then the second one will override the amove order with a regular move order.

**Comment by fgdzfggsfgsfgsf** [comment]
This is still happening in the very latest playtest, in both MP and skirmish, no lag in the MP game and my computer can easily handle OpenRA in both MP and skirmish.  It seems to happen if you attack move and then quickly left click to deselect the troops your were moving.  Doesn't happen in the release, and makes me pretty sad to miss out on all the new features, but this is a deal breaker for me unfortunately.

**Comment by obrakmann** [comment]
Finally found a way to reliably reproduce this:
```
[17:27:12]	<antares79> when you right-click (in attack-move), hold the right mouse button, then left-click and then release the *right* button, the units move instead of attack-moving 
```

**Comment by Aaron-Lloyd** [comment]
Fantastic news! That must be it, glad to see this should be resolved before next release. :)

**Comment by obrakmann** [comment]
I wouldn't bet on it. We're still discussing if it's a real bug or if it "works as designed". What you're doing with your clicking is basically bogus. You start a new order with the second click before your first click is even finished. It's unfortunate that it regresses from the last release (in the last release, mouse clicks registered when you put the button down, now they do when you release the button), but on the plus side we get the joystick scrolling for it. It would be a shame having to remove that. We'll try to figure out a different way to solve this. If we can't find one, I suspect this will not be fixed after all.

**Comment by fgdzfggsfgsfgsf** [comment]
For me you don't actually have to hold the right mouse button, just doing the clicks in rapid succession is enough.

I wouldn't want to break right button scrolling for those who use it, but this feels like a regression for a feature I'm not sure is all that popular (arrow key scrolling anyone?).  OpenRA is already a game where you have to be conscious of spam-clicking, I feel adding more waiting (click a, right click, pause, right left click) is less than ideal, especially in intense battles.

**Comment by penev92** [comment]
1) Nobody uses arrows to scroll, sorry. 2) "Joystick" scrolling is how **every** C&C game after RA did it.

The scrolling method won't change if I can help it.

**Comment by Aaron-Lloyd** [comment]
If 'joystick' scrolling is what I think it is, why can't it be mapped to the middle button with an option in the input menu to be able to change between joystick scrolling and drag scrolling? I guess it depends on the mouse, but pressing the middle button isn't particularly hard.

I just don't think it's worth risking having everyone complain at stable release about poor attack-move responsiveness (which is what everyone I've played the playtest with describes it as) for this joystick scrolling.

**Comment by obrakmann** [comment]
Agreed. I've just filed #10182. It would be great if you could check it out and see if that fixes the issue for you.

**Comment by Phrohdoh** [comment]
@penev92 I've used the arrows to scroll in many games.
Saying "Nobody does X" without numbers or proof is bogus, please refrain from doing so.

**Comment by penev92** [comment]
Fine, nobody that actually plays seriously. Last I checked you had no mouse and was playing with a trackpad, which is not that much different from "who in their right mind would play an RTS game on a touchscreen" ;)

**Comment by Phrohdoh** [comment]
When I play OpenRA I use a mouse.
When testing I don't feel the need to pull the mouse out.
