### ISSUE TITLE
CnC64 Special Ops GDI01 crashes after training an engineer from a captured Hand of Nod

### ISSUE THREAD

**Issue by hacklex** [OpenRA/OpenRA#9863]
The title says it all. After capturing the Hand of Nod to the east of the player's base, I tried to train an engineer there. The engineer popped out properly, and the game crashed immediately after.
The corresponding log entry says
"Fatal Lua Error: [string "BindingSupport.lua"]:30: Actor 'e6' does not define a property 'AttackMove'
   в OpenRA.Scripting.ScriptContext.FatalError(String message)
   в OpenRA.Mods.Common.Scripting.ScriptTriggers.TickIdle(Actor self)
   в OpenRA.World.Tick()
   в OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   в OpenRA.Game.LogicTick()
   в OpenRA.Game.Loop()
   в OpenRA.Game.Run()
   в OpenRA.Program.Run(String[] args)
   в OpenRA.Program.Main(String[] args)"

I guess one should fall back to simple move if no AttackMove is possible...

**Comment by pchote** [comment]
Looks like there are two problems here:

* e6 doesnt define AttackMove: JustMove: true
* the script forgot to unregister orders from captured factories
