### ISSUE TITLE
DisableOnUpgrade disables cloak on deployed mobile sensors array (TS)

### ISSUE THREAD

**Issue by teees** [OpenRA/OpenRA#9864]
https://github.com/OpenRA/OpenRA/blob/bleed/mods/ts/rules/shared-vehicles.yaml#L143-L145

**Comment by pchote** [comment]
We should replace the last uses of actor-level disabling with upgrades, and then remove the `IDisable` interface completely.  It worked well in the past, but doesn't play nicely with these new and more-complicated units.

**Comment by penev92** [comment]
See my Tick Tank PR.

**Comment by atlimit8** [comment]
#9438 does what @pchote [suggests](https://github.com/OpenRA/OpenRA/issues/9864#issuecomment-152988096). Another PR that splits out `DisableMovementOnUpgrade` from `DisableOnUpgrade`.

**Comment by atlimit8** [comment]
I tested deploying mobile sensors array with #9438 and the cloak is fine/fixed.
