### ISSUE TITLE
spice blooms appear too fast (and loud)

### ISSUE THREAD

**Issue by MicroJOo** [OpenRA/OpenRA#9866]
they pop up way too often (right at the start of the game) although they are meant to appear when the spice is gone ... beside that , they are kinda loud ... and you hear em constantly exploding ... i cant remember hearing this in the original all the time 

in the original : 
>so you have a patch of spice ...and once all of it is gone .... those spice blooms appeared ... and they did indeed explode at some time , but the explosions werent that loud ... and you had (atleast for a good amount of time) the chance to destroy them by yourself

i hope this isnt another unfinished feature ...

**Comment by pchote** [comment]
Has this been resolved now?

**Comment by MicroJOo** [comment]
@pchote : its better now
