### ISSUE TITLE
Connecting to Global IRC chat causes closing OpenRA to hang

### ISSUE THREAD

**Issue by Aaron-Lloyd** [OpenRA/OpenRA#9869]
So I discovered that if at any point I connect to the global IRC chat, quitting OpenRA will hang and It'll either take 10s+ to close or I'll need to ctrl+alt+del and force close the game. If I just watch a replay though I don't have this issue and the game closes normally.

This is on the Halloween playtest, while using Windows 7.

**Comment by GraionDilach** [comment]
A step ahead of you, although not fixed yet. See #9855.

**Comment by cjshmyr** [comment]
Can confirm I have encountered this a handful
