### ISSUE TITLE
D2k, Trikes and Raiders muzzle anim no longer displays

### ISSUE THREAD

**Issue by OmegaBolt** [OpenRA/OpenRA#9876]
As the title says, on playtest-20151031 the muzzle flashes don't appear.

Had a look into the yamls but couldn't see why myself.

**Comment by reaperrr** [comment]
I can't reproduce this, they show up for me. I still suspect this might be Tick rate related, `Tick: 50` is just a work-around for #9243 and might not be 100% reliable.

**Comment by reaperrr** [comment]
Ok, I managed to reproduce it.
The muzzle works fine when shooting at the ground, but not when shooting at actors. Likely a target validation issue.
