### ISSUE TITLE
Idea for silo usefulness.

### ISSUE THREAD

**Issue by epicelite** [OpenRA/OpenRA#9878]
When you build a silo it gets a 10% bonus of ore put into it every time a ore truck dumps a load at your refinery. If you build more silo's your bonus is not increased, but spread out amongst those silo's.

So you can choose to build a single silo, but your enemies will know to take it out and you lose all of your bonus. However, If you build more silos you have a greater chance of getting your bonus but it till take longer.
IE: 2 silo's = each get 5% and such I'm not good at math.

This can create some target-of-opportunity situations where you're in the middle of an attack and see your enemies silo is almost full, so you should take the time to destroy it so they get no bonus.

Can you guys even understand what I'm saying?

**Comment by obrakmann** [comment]
Added your post to #3816, since the discussion there is still active. Closing here.
