### ISSUE TITLE
Generate Init, Warhead, Projectile, [& Widget] Documentation

### ISSUE THREAD

**Issue by atlimit8** [OpenRA/OpenRA#9880]
Warheads and projectiles already have `Desc` attributes, the trait documentation generator should be reusable, and generated documentation should make it easier for modders to understand these without reading the source code (which not everyone can do).

These would require other pages in the wiki for publishing.
##

**Comment by StormWingDelta** [comment]
This needs to so be done because it is like hunting for a needle in a haystack at the moment.
