### ISSUE TITLE
RA, Soviet 04a mission, radar dome reinforcements

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#9892]
I tried asking this in IRC, but got no response - so here it is:

(playtest 20151031)
When I was playing the single player mission (RA, soviet 04a) the briefing states that killing the enemy radar dome would cut of their reinforcements. It didn't *seem* to be true.

Can you please check the mission scripting?
Thanks.

**Comment by abcdefg30** [comment]
It looks like only the infantry reinforcements arrive regardeless of the radar dome destruction.
All other reinforcements have checks like [this one](https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/maps/soviet-04a/soviet04a-reinforcements_teams.lua#L40) as far as I can see.

Do we want to disable infantry reinforcements when the radar is destroyed?

**Comment by pi99y** [comment]
I thought I saw light tanks/rangers coming after radar was down...

**Comment by abcdefg30** [comment]
Actually, that can happen. The checks happen when the reinforcements are "called", means: Check if radar dome is destroyed -> if no, send reinforcements in x minutes (4 to 7). When these reinforcements arrive, the script checks if the radar dome is destroyed and "calls" new reinforcements in x minutes if no.

**Comment by pi99y** [comment]
Here's the replay. You decide :)
Radar destroyed at ~74%, new tanks in the right side, above bridges (revealed by my plane) at ~93%.
http://www.megafileupload.com/5rm9/reinforce.orarep

**Comment by obrakmann** [comment]
I just debugged this, the units that appeared came from [here](https://github.com/OpenRA/OpenRA/blob/bleed/mods/ra/maps/soviet-04a/soviet04a-reinforcements_teams.lua#L65-L80). The reinforcements were scheduled several minutes in advance, while the radar still existed, but won't be scheduled again when the radar is dead. Do we want to change that, ie. move the check for the dead radar higher?
