### ISSUE TITLE
"PR: Needs Fixup" label for minor changes that don't invalidate "PR: Needs +2"

### ISSUE THREAD

**Issue by atlimit8** [OpenRA/OpenRA#9897]
"PR: Needs Fixup" label would be applied after "PR: Needs +2" when a reviewer would like to merge the pull request but a test commit needs to be removed or some other relatively minor changes should or need to be made first.

The label should be orange like "PR: Rebase me!" since it is also a simple rewrite label.

**Comment by Phrohdoh** [comment]
How is this different from `Changes Requested`?

**Comment by pchote** [comment]
#9894 is actually a bit more subtle than that.  The dates *are* correct, but they don't account for the prep vs bleed branch distinction.

**Comment by atlimit8** [comment]
@Phrohdoh "PR: Changes Requested" states or would state that the functionality the the pull request should/must be changed (more work) while this would imply that the pull request functionally acceptable but needs quick changes to be merged.
Although "PR: Needs +2" with "PR: Changes Requested" could be used the same way, but would be harder to distinguish especially since someone can add "PR: Changes Requested" after "PR: Needs +2" and not remove "PR: Needs +2" possibly by forgetting.
Basically, this would say use `git rebase` and/or `git commit --amend` and get done < 1minute.

I wouldn't be against the idea of using this for minor changes that don't invalidate "PR: Needs +2". I have had pull requests where one person adds "PR: Needs +2" and then someone else adds "PR: Changes Requested" and then I consider whether the "PR: Needs +2" because of the requested changes. As a minor change label, this would help prioritize pull requests when not having much time.

I have also seen "PR: Has dependencies" (and probably "PR: Changes Requested") be used for pull requests where the test commit needs to be removed for merging.

@pchote's comment does lessen my enthusiasm about this idea.

**Comment by Phrohdoh** [comment]
I don't buy that requesting changes means changing functionality or that the usage will change.
It simply means *something* needs to change, even if that is only a date.

Note that we had *a ton* more labels in the past that were never touched, and therefor removed.

**Comment by pchote** [comment]
I like the idea of having a separate label for fixups and then having changes requested invalidate earlier reviews.  We have had cases in the past where an earlier +1 has been carried over past a complete rewrite, and then pr merged with other silly regressions.

This is a good idea completely separate to the upgrade rules issue.

**Comment by atlimit8** [comment]
Updated description.

**Comment by atlimit8** [comment]
Well, I added it so I'm closing this.
