### ISSUE TITLE
engineVersion pseudo-dates

### ISSUE THREAD

**Issue by atlimit8** [OpenRA/OpenRA#9899]
Since #9894 is caused by `engineVersion` having reasonably close to merge dates that fell between playtest and release, I propose using pseudo-dates where the estimated month for the target playtest/release is used for pull requests. Scripts would update these in `OpenRA.Mods.Common/UtilityCommands/UpgradeRules.cs` when publishing a playtest or release

Ex:
    \* 20151201 -> "PR: For stable"
    \* 20160301 -> Next + 1
    \* ---
    \* playtest on say 20160224
    \* replace `engineVersion < 20160301` with `engineVersion < 20160224` in `OpenRA.Mods.Common/UtilityCommands/UpgradeRules.cs`

Pull request could be merged without changing `engineVersion` even if there is a playtest in between.

The `bleed` probably should also be updated to keep `engineVersion` for the upgrade rules in sync.
##

**Comment by pchote** [comment]
Fixed by #14964.
