### ISSUE TITLE
cnc64gdi01 air-strike support power

### ISSUE THREAD

**Issue by ghost** [OpenRA/OpenRA#9903]
ION cannon has been disabled (probably to eliminate the easy one shot kill on the bio lab objective) but the air-strike support power is granted upon building a comms centre which is still a one shot kill on the bio lab. 

Might be same in the original but the oRA balance of the air strike makes this mission easy to complete with a couple orcas and a comms centre.
##

**Comment by Smittytron** [comment]
Don't know where this was fixed but an airstrike now barely makes a dent in the Biolab and the AI immediately begins repairs.
