### ISSUE TITLE
Game crash on startup!

### ISSUE THREAD

**Issue by j-hopkins** [OpenRA/OpenRA#9914]
Hello,

I am using *Ubuntu 15.10* on an ivybridge intel laptop. when starting the game fresh. Once the main screen loads, I attempt to adjust the system volume via volume key(f10) and the "fn" function button. I will see the volume bar graphic reduce volume and it locks up the game. Other system processes seem fine. I recreated this issue 3 times before submitting.

Hope its nothing, or at least an easy fix!

**Comment by penev92** [comment]
Wait, is it crashing, or is it freezing?
Also we've established that the game doesn't like something else being rendered on top of it, like your volume bar indicator.
Pretty sure that's SDL, and not our code.

**Comment by pchote** [comment]
We only use SDL for creating the window and input - this is more likely to be a graphics driver bug.

**Comment by obrakmann** [comment]
I assume you're using Intel graphics then, right. If so, then this is a kernel bug, and you'll be getting these messages in your `/var/log/messages` file when the crash occurs:
```
[drm:intel_pipe_config_compare [i915]] *ERROR* mismatch in ips_enabled (expected 1, found 0)
```

This is apparently fixed in kernel 4.3. See this Ubuntu bug for more information: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1492764

**Comment by j-hopkins** [comment]
FIrstly, WOW.

your response time, amazing. Seriously, with Devs like this, I cannot WAIT
until the next release. THANK YOU.

Secondly, I have confirmed the bug lies with ubuntu as I was able to
finally test the "playtest" on another machine. Bummer for me, great for
you! less time potentially working on little stuff, more for what matters.

Sorry for wasting your time, thanks for the clarification.

**Comment by AMHOL** [comment]
Same issue on 15.04, happens when I'm in game (only in actual gameplay) and take focus off the game window, laptop completely freezes up and I have to force restart

**Comment by j-hopkins** [comment]
Got got up at work and failed to close this, thanks for taking care of it!

**Comment by penev92** [comment]
No problem :)
