### ISSUE TITLE
Attack cursor can be visible for a frozen actor under the shroud

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#9930]
Reported by @penev92 in IRC.

Explained in diff form:
```diff
diff --git a/OpenRA.Game/Traits/Player/FrozenActorLayer.cs b/OpenRA.Game/Traits/Player/FrozenActorLayer.cs
index 260f502..f4ed2f6 100644
--- a/OpenRA.Game/Traits/Player/FrozenActorLayer.cs
+++ b/OpenRA.Game/Traits/Player/FrozenActorLayer.cs
@@ -97,6 +97,10 @@ void UpdateVisibility()
                                }
                        }
 
+                       // TODO: If Visible == true but the whole footprint is covered by shroud
+                       // (e.g. from a gap generator, hide-map crate, or debug cheat) we need to set Visible = false.
+                       // If we don't do this the player will see an attack cursor through the shroud.
+
                        if (Visible && !wasVisible)
                                NeedRenderables = true;
                }
```

It isn't immediately obvious to me how to fix this without hurting perf.  The brute-force fix (which we may have to go for) is to loop over the footprint a second time and check against `shroud.IsExplored`.

**Comment by pchote** [comment]
In the long term we probably want FrozenActorLayer to register a callback against `Shroud.CellsChanged` and only tick the frozen actor when the visibility near it changes.  This would give us a decent perf improvement overall, counteracting the slower individual ticks.

**Comment by pchote** [comment]
A simple short term workaround is to add checks for shroud and early-exit before querying for the frozen actor under the mouse.  There are a few (at least three) places this would need to be done.

**Comment by RoosterDragon** [comment]
The performance hit is something we can happily accept if we need to.
