### ISSUE TITLE
Reduce difficulty of ra map Fort Lonestar

### ISSUE THREAD

**Issue by cjshmyr** [OpenRA/OpenRA#9938]
After playing with a handful of players and seeming to only make it a couple minutes in, might be time to lower the difficulty of this map. We could also scale the map's difficulty based on playercount if it already isn't.

**Comment by Phrohdoh** [comment]
Bumping ambient to `0.55` feels like a good start.
![](http://i.imgur.com/qRGGmhJ.png)

**Comment by GrayHatter** [comment]
Please don't, this is one of the maps that my group and I can always play because we haven't beaten it yet.

**Comment by cjshmyr** [comment]
Could introduce difficulty settings for those who want to casually play it, leaving the current iteration as the Hard difficulty

**Comment by obrakmann** [comment]
Closed by #10205.
