### ISSUE TITLE
Lighting on fort lonestar

### ISSUE THREAD

**Issue by cjshmyr** [OpenRA/OpenRA#9939]
Map is a bit dark, and we could also add in some light sources

**Comment by Phrohdoh** [comment]
Bumping ambient to `0.55` feels like a good start.
![](http://i.imgur.com/qRGGmhJ.png)

**Comment by penev92** [comment]
I think a few light towers in the fort itself should be enough. Also I think we could add headlights to most vehicles, which would be a nice polish touch. Increasing the global lighting may be a bit overkill.
