### ISSUE TITLE
Use ExternalConditionInit to transfer external conditions on Transform

### ISSUE THREAD

**Issue by penev92** [OpenRA/OpenRA#9940]
`Transforms` is notorious for having a series of drawbacks, but it's still a viable option for MCVs.
One of the recent games of the Big Team Tournament ([SlepinirStuff thread](http://www.sleipnirstuff.com/forum/viewtopic.php?f=82&t=18950)) showed FiveAces using an Iron Curtain on his ally's ConYard when it was under attack. His ally (I can't remember who was playing, but the replay and/or stream video can be easily found) though, in a hurry to save his ConYard, packed it into an MCV a second after the Iron Curtain was activated.
The MCV, of course, didn't have the invulnerability upgrade, and died shortly after.

We now have the means to remedy this situation - the `UpgradeInit` that was added recently allows us to copy all upgrades that currently affect the ConYard to the MCV, which will make the Iron Curtain effect persist over to the other actor. (Note: we need to be careful not to refresh the timer on timed upgrades though!)
##

**Comment by penev92** [comment]
Eh, scratch that. I guess I got ahead of myself. It was `PlugsInit` that was added by me recently, and `DeployedInit` is currently in an open PR by @atlimit8, but I guess I was mistaken about the `UpgradeUnit` thing being a real thing.
Anyway, it should be a very simple addition, and it can find other uses other than in `Transforms`.

**Comment by pchote** [comment]
Good idea.  I guess we should be able to split `PlugsInit` into an `UpgradesInit` type, with `PlugsInit` subclassing that to add whatever plug-specific extras it needs.

**Comment by pchote** [comment]
This may also be useful for actor &rarr; husk modifiers for artwork, etc.

**Comment by atlimit8** [comment]
See #9031.

**Comment by pchote** [comment]
With the current state of the conditions system this will need to be limited to the ExternalCondition traits.  Updated the issue title to reflect this.

**Comment by pchote** [comment]
Even restricting this to `ExternalConditions` is difficult because granted conditions return a unique token that can be used to later revoke it.  Transforming to a new actor changes both the actor and the token.

**Comment by MustaphaTR** [comment]
The TransferTimedExternalConditionOnTransform trait added in https://github.com/OpenRA/OpenRA/pull/15300 should close this.
