### ISSUE TITLE
GPS only shows icons for vehicles

### ISSUE THREAD

**Issue by pi99y** [OpenRA/OpenRA#9954]
Playtest 20151031
GPS satelite only shows icons for vehicles (& not for infantry).

Also see #9953 (but this, or the new "defend" stance, does not appear to be the reason for #9953)

**Comment by r34ch** [comment]
Pause for thought: I kind of like this. 

It gives soviets a limited way of being sneaky late game. Allies currently have _such_ an easy time slaughtering infantry (tanya, hinds, arty, PBs) that this 'element of surprise' might give soviets a small window of opportunity to do some damage with these poor cannon fodder late game and open up some interesting diversionary tactics. 

A couple longbows at this level provide loads of LoS so its not exactly overpowered and seeing infantry from a WW2 satellite orbiting in space always seems a little _too_ good even for the RA fantasy universe.

But obviously implemented as a feature and not a bug. Discuss.

**Comment by pi99y** [comment]
I do like it as well (!), since I've always thought GPS was too powerful and diminished importance of scouting. It was confirmed by @penev92 to be unintentional.
I'm all for the change, but "scared" of the allied player's reaction to this.
Whenever I toyed with an idea of somehow nerfing the GPS (time-limited, temporarly disabled by blackouts, limited to only targeted areas,... )  I was told  ~"it was such an essential allied mechanic that this should not be touched".

Fingers crossed.

**Comment by r34ch** [comment]
I cannot replicate this on bleed.

**Comment by pi99y** [comment]
But you can on current playtest, right?

**Comment by r34ch** [comment]
I cannot replicate it on playtest either. Do you have a replay? 

The only thing I can think of is that someone disguised their spys as their own normal troops. Spy do not appear on radar.

**Comment by pi99y** [comment]
Replay: http://www.megafileupload.com/i35A/funkyGPS.orarep

I was testing the #9953 issue and I had DEBUG menu ON (is that what causes it?)

Set view to player "pi99y" and look the 5 rangers movig into AI's base at about 2 minutes (53-54%) of the game. Before I have vision of ther base you can only see the GPS icon for their harvester, when my rangers try to enter their base there's a ton of infantry which had no GPS icons.

**Comment by penev92** [comment]
Sorry mate, but this is what I see in your replay:
![openra-2015-11-10t203819z](https://cloud.githubusercontent.com/assets/7137365/11075050/c8a6b20a-87fb-11e5-86f5-44045c52bc2a.png)

If you look really closely, there **are** a bunch of small purple dots, which are pretty hard to see (open image in new tab for best results).

**Comment by abcdefg30** [comment]
Ah yeah, I can see them too.

**Comment by pchote** [comment]
That doesn't necessarily mean that there isn't a bug; only that it doesn't occur in replay mode.  I can believe there being an broken edge case when cheats are enabled.

**Comment by pchote** [comment]
Ah hang on, I thought this was the other buggy GPS thread.  It is not plausible that there is a bug that causes infantry to be displayed differently to vehicles, so I believe that @penev92's description is correct.

**Comment by pi99y** [comment]
Wow, now this is embarrassing... :)
Yes, zoomed in and now that you pointed them out I can see them too. Damn purple on green.
Sorry guys, this was not intentional.

But @r34ch 's idea of making a feature out of this still stands! :)

**Comment by penev92** [comment]
Such idea is best discussed at the forums first, IMO. Alternatively you should open a ticket for it. I believe we're done with this one.
