### ISSUE TITLE
Suggestion: Hide GPS icons when player has low power [$10]

### ISSUE THREAD

**Issue by r34ch** [OpenRA/OpenRA#9962]
The GPS launch count down is paused when the Allied tech centre has low power but once launched, GPS dots can be seen even when the player has low power.

This means that the only way to sneak attack allied players after this point is to destroy the tech centre. This reduces the effectiveness of attacking a players power supply.

**Comment by pi99y** [comment]
I'm all for limiting the GPS!
- GPS diminishes importance of scouting
- like mentioned, this would allow sneak attacks
- the change is logical and since the Allied are supposed to be the "tech" faction this is the downside (more dependent on power)

**Comment by GraionDilach** [comment]
@penev92 S_i_ggistion?

**Comment by penev92** [comment]
:+1: 
As a one-up I'd like to suggest "Hide GPS icons when player has low power or the radar is offline/non-existent".

**Comment by pi99y** [comment]
:+1:  to @penev92 's radar suggestion

**Comment by klaas1** [comment]
Agree with all of the above, GPS is too strong and relatively easy to maintain once up.
