### ISSUE TITLE
Minimap orders don't work in the left click control scheme

### ISSUE THREAD

**Issue by PUOjACKz** [OpenRA/OpenRA#9965]
In the original C&C, you could select an unit, or a group of them and you could pilot them directly on the radar window, or order them to attack. Having such feature could nice, but in case, having even a "zoom" button that can let the user zoom in a particular area and giving order, avoiding the problem that the points are to small to locate, would help its usage.

So if you have to give an attack or patrol command, you can do that, without moving the main camera, and lose sight of what is going on there.

**Comment by pchote** [comment]
This has always been supported in OpenRA.  Please file specific bugs if there are certain commands that don't work on the minimap.

**Comment by PUOjACKz** [comment]
I have tried to use it, but it doesn't work. At least, not working on TD mod.

**Comment by pchote** [comment]
Are you using the left click control scheme? It wouldn't surprise me if it didn't work for that because we use the left mouse button for moving the viewport.

**Comment by MustaphaTR** [comment]
I'm not sure why but it wasn't working for me for a long time too. Yes, i'm using left controls. It stopped to work for me short after i post #5981. I was previously using normal cursor scheme, as left one was completly broken before removed and readded. I need to check is left really reason of it.

**Comment by SMIFFGIG** [comment]
Same here, latest stable release
