### ISSUE TITLE
Externally capturing a building cancels its production

### ISSUE THREAD

**Issue by cjshmyr** [OpenRA/OpenRA#9983]
Unintentionally introduced with #6766, which still can be reproduced (#8146) regardless. When externally capturing a building, its entire production queue is cleared out and made unavailable until the capture is either completed or halted.

**Comment by penev92** [comment]
Are we sure this is a bug and not intentional?

**Comment by GraionDilach** [comment]
In the RA mod it might be a feature. I do consider this as a bug though if a modder wants to have a Black Lotus around and instead of actually capturing just abuse her long range externalcapturing to halt all production (Gen didn't suspended the queues at start neither).

**Comment by pchote** [comment]
It's a bug.

**Comment by obrakmann** [comment]
Duplicate of #8122.
