### ISSUE TITLE
Implement player authentication via hidden global chat messages.

### ISSUE THREAD

**Issue by pchote** [OpenRA/OpenRA#9990]
This is a specific proposal for how to implement #2265 / #4410 using identified IRC nicknames and a call/response via PRIVMSG.

1.  Enable identification / name enforcement on the IRC server backend (ping @baxxxster).
2.  The server sends a random blob to the client as part of the `HandshakeRequest` and stores it as part of the server-side client data (which is stripped out before sending to other clients).
3.  The client generates a random blowfish (or substitute a different algorithm if we want more security) key, stores it for future use in the `GlobalChat` class, and then encrypts the blob using this key and our existing `Blowfish` code.
4.  The client returns the encrypted blob and their authenticated IRC nickname as part of the `HandshakeResponse` (or empty data if they do not want to authenticate).  New keys are generated for each handshake, so there is no problem with this data being saved in replays.
5.  The client joins the server as normal and the server assigns a status of AUTHENTICATING if they returned an auth response, or UNAUTHENTICATED if they did not (stored as another field on Client, which is shared with all clients).
6.  The server, which has its own connection to the global IRC network (but doesn't join any channels) sends a PRIVMSG containing the encrypted data to the nickname returned in the handshake.
7.  The client, which is of course already logged into IRC, receives the PRIVMSG, decrypts it using the stored key, and then responds via PRIVMSG.  The IRC nick enforcement means that a malicious player that puts somebody elses IRC name in the handshake response cannot receive this message.
8.  The server checks that that the response matches the original blob sent in the handshake request.  If it matches then the server is confident that the client is who they say they are and sets their status to AUTHENTICATED.  If it does not agree, or if it does not recieve a response within an appropriate timeout, then it sets their status to UNAUTHENTICATED.

The lobby UI then uses the authentication status shared by the server to show an appropriate icon in the ping/admin block.  Player names are _not_ required to match the IRC nickname, but the IRC nickname _will_ be shown in the ping/admin block tooltip.

Clients who connect via a regular IRC client would be able to see these background messages and send data to the servers.  This is not a problem because those messages don't contain any sensitive information, and the server would ignore any responses that it doesn't expect or understand.  The server IRC connection can also be used for server management (cc @cjshmyr, who is implementing this for #6538).

A similar process can be used for authenticating servers against a central player stats database, but that is significantly out of scope of this initial implementation.

**Comment by pchote** [comment]
Updated with full details on how to implement this.  I'm assuming that the server-IRC connection is first implemented as a part of #6538, so I haven't elaborated on that.

**Comment by pchote** [comment]
An alternative approach which is simpler, but less robust.  Including it here for completeness, but I think the method above is better:

2. The client receives a `HandshakeRequest` from the server, with no changes to what it currently contains.
3. The client generates a random blob, PRIVMSGs it to a dedicated IRC bot, and adds it to the `HandshakeResponse` along with their IRC name.
4. The server PRIVMSGs the IRC bot the IRC name and blob from the response.
5.  The IRC bot returns either true or false depending on whether the blob matches what it has stored.

The problem with this approach is that it can behave badly if there is latency in the IRC connection: the server may be able to query the IRC bot before the client message goes through, and this will cause the authentication to falsely fail.

**Comment by GraionDilach** [comment]
What about people with multiple PCs? Both ideas imply to me that one has to throw the settings.yaml back'n'forth between PCs/OSes to successfully authenticate if (s)he wants to reuse his/her old nick on the second PC/OS.

**Comment by pchote** [comment]
Authentication with the IRC channel is done with a username/password that you type into the server browser.  Connecting from multiple machines *at the same time* isn't allowed, but there is no issue with connecting from one machine at a time.

**Comment by chrisforbes** [comment]
Self ping @chrisforbes to do crypto review

**Comment by pchote** [comment]
Building this on IRC is a terrible idea.  Closing.
