### ISSUE TITLE
Husks aren't targetable on refinery pads

### ISSUE THREAD

**Issue by cjshmyr** [OpenRA/OpenRA#9998]
Caused by husks having no `Selectable:` `Priority:`. If an actor isn't selectable, it'll default to having the lowest selection priority possible.

Unit targeting code checks for all actors under cursor, and picks the actor with highest priority: [UnitOrderGenerator.cs:L24](https://github.com/OpenRA/OpenRA/blob/206f64494965c08d89db618cdea2f519c355b091/OpenRA.Game/Orders/UnitOrderGenerator.cs#L24)

**Comment by pchote** [comment]
Proposed fix: when not drag selecting the overlap should be resolved by distance to centre before priority.

**Comment by atlimit8** [comment]
Like #9927?

**Comment by pchote** [comment]
indeed.

**Comment by atlimit8** [comment]
`((long)pixelDistance << 32) + actor.Info.SelectionPriority()`

**Comment by atlimit8** [comment]
That should make 1x1 buildings behind refineries accessible as well.

**Comment by pchote** [comment]
@atlimit8: Do you want to fold a fix for this into #9927?
